### ISSUE TITLE
TSX Regressions

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#10001]
GALCIV SPU TEST was used to measure the performance regressions. (the perf regressions are also present in games, but for the sake of making this simple and clear i've only added the SPU Tests.) Notice how the Spinlock, PUTLLUC and PUTLLC performance test results are now atrocious.

Master:
SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 2123 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2311 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 20240 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 21462 ms (PS3: 4443 ms)
SPU Integer Perf completed in 2320 ms (PS3: 8666 ms)
SPU Float Perf completed in 476 ms (PS3: 2379 ms)
SPU SpinLock completed in 15446 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 18172 ms (PS3: 3853 ms)
PUTLLC Perf completed in 17796 ms (PS3: 3364 ms)
PUT Perf completed in 920 ms (PS3: 3984 ms)
--Completed 10 tests in 101266 ms--

Before #9048:
SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 1421 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 1722 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 6162 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 8808 ms (PS3: 4443 ms)
SPU Integer Perf completed in 2665 ms (PS3: 8666 ms)
SPU Float Perf completed in 641 ms (PS3: 2379 ms)
SPU SpinLock completed in 4214 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 3972 ms (PS3: 3853 ms)
PUTLLC Perf completed in 9910 ms (PS3: 3364 ms)
PUT Perf completed in 947 ms (PS3: 3984 ms)
--Completed 10 tests in 40467 ms--

Those two regressed it:
#9048 and #9195

**Comment by nitroos-ai** [comment]
Retest with latest master.

**Comment by Yahfz** [comment]
Closing as fixed by #11265
