### ISSUE TITLE
Small specks on models in Persona 5

### ISSUE THREAD

**Issue by theuhdirector** [RPCS3/rpcs3#10005]
## Quick summary
Many models have small white or colored spots on them, most notably in darker areas. This effect changes with the angle of the camera and sometimes is not visible at all.

## Details

Please describe the problem as accurately as possible.

#### 1. Please attach RPCS3's log.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6178679/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
[NPEB02436_20210321201808_capture.zip](https://github.com/RPCS3/rpcs3/files/6178696/NPEB02436_20210321201808_capture.zip)

#### 3. Please attach screenshots of your problem.
It's very noticeable in dark places, such as here in Leblanc.
![leblanc_bad](https://user-images.githubusercontent.com/44654353/111926698-400f6900-8a84-11eb-84a3-44c9d0bb6386.png)
Moving the camera upwards can sometimes negate the effect entirely.
![leblanc_moved](https://user-images.githubusercontent.com/44654353/111926696-3f76d280-8a84-11eb-8a77-47daf60a78fe.png)
Bright places, like the school, don't really have this issue. However, you can still see it in dark areas like on the chairs.
![school](https://user-images.githubusercontent.com/44654353/111926699-400f6900-8a84-11eb-8a2d-ba028f678e05.png)

#### 4. Please provide comparison with real PS3.
I don't have a real PS3 available at the moment, but if you look at the second image, that's pretty much what it's supposed to look like.

#### 5. Please provide your system configuration:
* OS: Windows 10 build 19043
* CPU: Ryzen 5 2600
* GPU: Radeon RX 580 8GB
* Driver version: 21.3.1

#### Additional info:
I tried just about every setting to try and stop this, and the only one I could find that actually removed the problem entirely was using the Shader Interpreter only setting in the emulator. But I can't actually use that to play the game due to the framerate.

**Comment by MSuih** [comment]
This is an engine bug that happens when scaling isn't set to multiple of 100. Try 200% or 300% scaling and the dots should disappear.

I'll close the issue as scaling is known to cause issues for games that weren't designed with it in mind.
