### ISSUE TITLE
Dual screen woes with DPI mismatch as seasoning

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#10027]
Basically, two things:

- when using multiple screens, the game window will always open up on the main screen, instead of the screen the GUI resides on,
- and in that case, the dimensions of the game window will be *wildly* wrong.

To be more specific, I have two screens: the one in my laptop: `1080p@1.25x`, and my regular monitor: `1080p@1.00x`. If I open a game with the GUI residing on my regular monitor, the game window will pop up on my laptop screen, positioned as such that the left (exactly) 500px of the screen is not covered with the game, and the dimensions of the window will be `1920 × 1440`.

![image](https://user-images.githubusercontent.com/10439488/112728510-f6ad9680-8f27-11eb-8493-717239f476bb.png)

Dragging the window over to my regular monitor will result in Windows dividing the window size back as per my DPI scaling config, resulting in a `1536 × 1152` window size, looking roughly like this:

![image](https://user-images.githubusercontent.com/10439488/112728573-455b3080-8f28-11eb-9392-4cf51220bbc9.png)

The desirable behaviour is that the game window should be the largest integer multiple of 720p that fits the given screen, in respect to the DPI scale used.

**Comment by Megamouse** [comment]
try with #10036

It might fix the issue. The Window should be hopefully clamped to the edges of the target screen now.
I don't have a second screen at the moment. So I need confirmation if this is a good solution.

**Comment by dio-gh** [comment]
Tomorrow. (today but later)
