### ISSUE TITLE
[Feature Request] Modernize the application's icon

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#10024]
It's been bugging me for a while, but @DAGINATSUKO's website thumbnail looks infinitely better than the current RPCS3 app icon, or even the repo's logo.

This one, I mean:
![image](https://user-images.githubusercontent.com/10439488/112701114-02e61500-8e90-11eb-95fc-dc51fcbc61b7.png)

What do you guys think, would it be okay if the current icon and repo logo was swapped out with this? She agreed to adjust it to different icon sizes. Looks plenty decent on the taskbar, imo:

![new-icon](https://cdn.discordapp.com/attachments/669999687662829599/825312524802326538/unknown.png)

**Comment by dio-gh** [comment]
@Megamouse any objections? The general reception seems to be overwhelmingly positive.

**Comment by Yahfz** [comment]
Current RPCS3 icon looks like hot garbage. Only a madman would say no to this change, I can't believe we didn't do that before tbh. Also, yes.  I just used the amazing contribution label unironically probably for the first time.

**Comment by MsDarkLow** [comment]
That madman is right here you know. I strongly hate the squared background. My suggestion is to just give it rounded edges.

**Comment by dio-gh** [comment]
Way ahead of you, this is just a mockup I hacked in.

**Comment by MsDarkLow** [comment]
Oh in that case then I have no objections

**Comment by JohnHolmesII** [comment]
I mean, I like the current one
