### ISSUE TITLE
Pinning RPCS3 to taskbar resets to old icon after #10029

### ISSUE THREAD

**Issue by YuriNator557** [RPCS3/rpcs3#10034]
## Quick summary
RPCS3 now opens with the new icon, but if you pin it to the taskbar (on windows 10 at least), it resets to the old icon. After doing this once, it stops letting you pin it to the taskbar and you need to restart.

#### Please attach screenshots of your problem.
https://user-images.githubusercontent.com/76178650/112892986-f6e99580-90d1-11eb-9eb5-6797bc5a6deb.mp4

####  Please provide your system configuration:
* Windows 10 20H2
* Ryzen 7 3700x
* Radeon RX 580 driver 2.0.`168
* etc.

**Comment by Megamouse** [comment]
this looks like some registry crap on windows if you ask me.
Sadly we can't really fix that. (I think).
It might resolve itself by rebooting a trillion times.

**Comment by dio-gh** [comment]
https://neosmart.net/wiki/clear-icons-cache/#How_to_clear_the_icons_cache_in_Windows10

**Comment by Megamouse** [comment]
I can. but I'm doing more important stuff

**Comment by Megamouse** [comment]
Closing. This is a windows issue as far as I can tell
