### ISSUE TITLE
vulkan-1.dll error

### ISSUE THREAD

**Issue by boludoz** [RPCS3/rpcs3#10037]
Vulkan-1.dll error.

I got this error because I don't have vulkan support in the drivers (although it could theoretically be possible, they were never released). To fix the problem, I installed VulkanRT and was able to play with decent FPS, but I wish you didn't ask for this to run because most people don't know that OpenGL can be used.

Tested in APU A10 6800K with no Vulkan support.

**Comment by Megamouse** [comment]
Where is the log file

**Comment by MSuih** [comment]
There's no useful information in the log, the current dll check is not done by rpcs3.

I think issue https://github.com/RPCS3/rpcs3/issues/5953 should be used for discussion about the vulkan-1.dll error dialog, additional issues are unneccessary.
