### ISSUE TITLE
Regression: FPS drop in LittleBigPlanet games (#10036)

### ISSUE THREAD

**Issue by Boii1** [RPCS3/rpcs3#10045]
## Quick summary
FPS Drops from 5 to 10

## Details
Latest update from Pull Request #10036 (rpcs3-v0.0.15-12026-e557c962_win64) drops performance in LBP1 by a decent margin, hardware unrelated since I'm using a 5950X/3080/32GB 3600 16 18 18 38. So whatever was added there kills the performance. Update right before it works perfectly fine and runs at 30FPS.

**Comment by Gorialis** [comment]
I can replicate this on BCUS98148 and NPEA00241, and this also affects sequels LBP2 (tested BCUS98245) and LBP3 (tested BCUS98362, BCES01663)

**Comment by ScottNash042** [comment]
update or close ??

**Comment by elad335** [comment]
Heavily outdated, closing. Open a new issue if persists.
