### ISSUE TITLE
State of Breakpoints not saved between sequential launches of the same application

### ISSUE THREAD

**Issue by LucasRitter** [RPCS3/rpcs3#10059]
## Quick summary

Breakpoints at the start of an application only get tripped on the first launch after RPCS3 has been opened. Any new launches past that will no longer trip those breakpoints.

## Details

https://user-images.githubusercontent.com/20494846/113447841-f36c4c00-93fa-11eb-9bea-fab1bf901438.mp4

#### 1. Please attach RPCS3's log.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6251005/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
- Not a graphical issue -

#### 3. Please attach screenshots of your problem.

\- See Details section-

#### 5. Please provide your system configuration:
* OS Windows 10
* CPU AMD Ryzen 7 3700X
* GPU NVidia GeForce RTX 3070
* Driver version 465.89.0.0
* etc.

#### Please include.
The game I was experiencing this with was DJ Hero 2 (BLES00896 - v1.00) at offset 0x13310, which is the start of FSGGameInitialise(), a function called super early in the lifecycle of the game.

**Comment by elad335** [comment]
Well actually breakpoints should have been cleared because saving the state of breakpoints for each application is unimplemented. So it's just a GUI that does not clear it internally properly.

**Comment by LucasRitter** [comment]
So I'd have to reset the breakpoints when I relaunch the application?

**Comment by elad335** [comment]
I think its better to rename this issue to "breakpoints' state are not saved between sequantial launches of the same application" or something.
