### ISSUE TITLE
TEKKEN 6 Freeze after new updates 

### ISSUE THREAD

**Issue by 1BOSBACK** [RPCS3/rpcs3#10060]
## Quick summary
Tekken 6 Freeze on loading PPU modules, on old version11996 it works fine.

## Details
Starts good like always, tested on 11996 it works, also if change PPU decoder it works on new version but slow.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
* bild 0.0.15-12035-a1d31f64 Alpha
#### 2. Please attach TWO logs:
* One for the build with regression.
* One for the build that works as expected.

##### How to obtain RPCS3's log:
* Run the game until you find the regression.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc. 

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc. 
	And drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 4. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 6. Please provide your system configuration:
* OS Windows 10 Pro 64bit
* CPU Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz | 8 Threads 
* GPU NVIDIA GeForce RTX 2060 SUPER
* Driver version running on driver 465.89.0.0
* etc. ram 24gb
![TEKKEN 6](https://user-images.githubusercontent.com/81833386/113457164-67185400-940f-11eb-80f5-567c17934ae2.jpg)

#### Please include.
* Anything else you deem to be important

**Comment by AniLeo** [comment]
Incorrect report, very unlikely that 12035 introduced this, plus the previous good build you mention is 24 PRs behind that one.

**Comment by 1BOSBACK** [comment]
Well before it worked, all the games work i even change the game disk .
![Tekken 6 2](https://user-images.githubusercontent.com/81833386/113457853-30dbd400-9411-11eb-9a2f-11b00b509e83.jpg)

**Comment by AniLeo** [comment]
The point is correctly flagging the build that regressed it as indicated on the issue guidelines

**Comment by 1BOSBACK** [comment]
And here see the Tekken 6 Working on old Version 
![Tekken 6 old v emu](https://user-images.githubusercontent.com/81833386/113457984-9def6980-9411-11eb-928d-455634970b0f.jpg)

**Comment by 1BOSBACK** [comment]
But in new one just stop, it works only if i change interpreter PPU decoder to fast, but FPS is 23-60.
Testaste on 3 Different Tekken 6 Disk happens the same.

**Comment by AniLeo** [comment]
Please ask for support on Discord and reopen the issue when you understand how a Regression Report works, your report doesn't follow the guidelines at all

**Comment by 1BOSBACK** [comment]
ok i see thanks.
