### ISSUE TITLE
Overlays: Handle multiple message dialogs at once

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#10064]
~Currently, if we open a message dialog while another one is already open, the emulator might hang or crash.
I don't know if this is a misuse from our side or if there's a flaw in how we open, render and close the overlays.~

Opening two cellMsgDialogs - for example one with open_msg_dialog and another with cellMsgDialog - at once does not work as expected, since it re-uses the old dialog instead of another one.
We should either force close the old one or have multiple handles for example.

See #14040 for more information.

**Comment by Megamouse** [comment]
Merging as hot fix / workaround

**Comment by SupervisedThinking** [comment]
I've experienced quite the same issue https://github.com/RPCS3/rpcs3/commit/e557c962fbeb319dddf7652fde9f0bea235e469e because after the merge of the native ingame PPU compilation GoW collection hangs in 9 out of 10 starts at the PPU (LLVM) linking stage.

**Comment by Megamouse** [comment]
@SupervisedThinking try the next master update in half an hour or so.

**Comment by SupervisedThinking** [comment]
PR10072? I'm already compiling head + PR for tests

**Comment by Megamouse** [comment]
It's already merged.
So fetch master and try the latest commit

**Comment by kd-11** [comment]
Any simple test-case to reproduce this? In theory opening a new dialog should just close the existing one and everything should continue as usual.

**Comment by MSuih** [comment]
Wasn't this related to PPU modules now being message dialogs? So in theory game opens some dialog and loads more PPU stuff, which then causes RPCS3 to open another dialog on top of that and crash.

**Comment by Megamouse** [comment]
TEKKEN 6 opens a dialog right after ppu compilation.
If you disable the "skip_this_one" workaround, you'll find it hang itself.
Another way to test this is probably to force a progr dialog while some msg dialog is open.
I'm assuming that the game hangs because the msgdialog is killed before the game can kill it.
So having the progress dialog on some layer above would probably be a good solution

**Comment by Megamouse** [comment]
Btw. The work around works so far. So there is no rush in implementing this

**Comment by kd-11** [comment]
Needs a retest after the unification work a while ago.

**Comment by Megamouse** [comment]
I'll probably have to fake this somehow

**Comment by kd-11** [comment]
The incoming dialog should not present until the previous one is done.
I think the overlay manager already does this? Or at least that was the idea, I have to check how much was already working.

**Comment by Megamouse** [comment]
Repurposed and updated the description.

**Comment by Megamouse** [comment]
Nevermind. the function returns CELL_SYSUTIL_ERROR_BUSY but the game doesn't care.
