### ISSUE TITLE
Grand Theft Auto IV white sreen

### ISSUE THREAD

**Issue by joker5bb** [RPCS3/rpcs3#10063]
Grand Theft Auto IV fails to load 
****need to uncheck Use native user interface in Emulator tab of settings to get a compile 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6253135/RPCS3.log)

- RPCS3 v0.0.15-12039-e57f36fc Alpha | HEAD | Firmware version: 4.87
- Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz | 12 Threads | 63.91 GiB RAM | TSC: 3.598GHz | AVX+ | FMA3 | TSX disabled by default
- Operating system: Windows, Major: 10, Minor: 0, Build: 19042, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'Radeon (TM) Pro Duo' running on driver 2.0.179 x2
S UPDATER: RPCS3 is up to date!

**Comment by Megamouse** [comment]
Please retry with the latest update

**Comment by Megamouse** [comment]
assuming fixed with the latest progress dialog changes

**Comment by joker5bb** [comment]
not fixed

**Comment by xddxd** [comment]
Works fine here, there is a white screen while the PPU modules are compiling, but the game runs normally after compilation is done.
