### ISSUE TITLE
Regression: MGS4 [BLUS30109] no longer boots (#10065)

### ISSUE THREAD

**Issue by clothedsnake** [RPCS3/rpcs3#10068]
## Quick summary
MGS4 (BLUS30109) no longer boots.

## Details
The US disc version of MGS4 (BLUS30109, patch 2.00) no longer boots. Attempting to boot the game results in a persistent white screen, as per the attached screenshot. The US digital release (NPUB31633, 2.00 pre-applied) is not affected.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
Regression introduced in build 12046, which persists into 12047 and 12048. Build 12040 boots MGS4 fine.

#### 2. Please attach TWO logs:
Regression build: [RPCS3_0.0.15-12048_regression.log](https://github.com/RPCS3/rpcs3/files/6259919/RPCS3_0.0.15-12048_regression.log)
Working build: [RPCS3_0.0.15-12040_working.log](https://github.com/RPCS3/rpcs3/files/6259920/RPCS3_0.0.15-12040_working.log)

#### 4. Please attach screenshots of your problem.
![MGS4 screenshot](https://user-images.githubusercontent.com/17098511/113610731-6c5ee400-9645-11eb-8acb-f0d6bcd27a45.png)

#### 6. Please provide your system configuration:
* OS: Windows 10 21H1 x64
* CPU: Ryzen 3950X
* GPU: 5700 XT
* Driver version: Radeon Adrenalin 21.3.2

**Comment by cipherxof** [comment]
I can confirm I also have this issue.

OS: Windows 10 19042
CPU: Ryzen 3700x
GPU: RTX 3080
Driver version: 461.72

**Comment by TrantaLocked** [comment]
On my end the game boots to menu with PPU in Interpreter and/or SPU in Interpreter. If SPU is in LLVM or ASMJIT, startup is either frozen (no window loads) or usually white screen like OP. Build is 0.0.15-12048-f64a7bb8.

**Comment by Megamouse** [comment]
Please retry with the latest update

**Comment by clothedsnake** [comment]
> Please retry with the latest update

Seems to be fixed, thanks.
