### ISSUE TITLE
God of war 3 not stable

### ISSUE THREAD

**Issue by cyber390** [RPCS3/rpcs3#10077]
Hi , Recently I downloaded the latest build of rpcs3 and tried to play god of war 3 it was so laggy i barely get 10fps
And when i installed the older version of rpcs3 (version 0.12) i was getting 12 fps and maybe 20 . So the new build is just getting bad. And only some games are running on a 4 core processor . The games are only good at 6 core and above . Is there anyway to play god of war 3 at a 4core spec

My spec
Intel 15 4690k
Nvidia gtx 970
16gb ram

I cant play god of war 3 even at 20 or 30 fps . HELP!
I even tried game patches and all still its bad...

**Comment by MsDarkLow** [comment]
GitHub is not a place for [Support](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support). 
This is not an issue and you failed to read the template that shows up when creating the issue. Please close the issue. 
Also your corelet CPU is not enough for this game.
