### ISSUE TITLE
Regression: GT6 Force closes after #9772

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#10079]
After PR #9772, GT6 force closes when entering the garage with the car set to a C63 AMG with the calcitweiss color, not sure if other cars do this. Last working build is 0.0.14-11749-5b044a93

Log from latest master: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6281757/RPCS3.zip)
VS Debugger screenshot:
![Screenshot_surface](https://user-images.githubusercontent.com/1712979/114101174-06d15880-98ce-11eb-9f24-ad001f8c1a09.png)

**Comment by elad335** [comment]
Fixed by #10080
