### ISSUE TITLE
Persona 4 Arena Ultimax [NPEB02176] Regression

### ISSUE THREAD

**Issue by digitaldude555** [RPCS3/rpcs3#10082]
## Quick summary
![Screenshot (428)](https://user-images.githubusercontent.com/26138653/114210940-b9ee9000-9968-11eb-8d98-8a8a1b6dde7c.png)
Pressing x will then close the game.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.

RPCS3 v0.0.15-12057-d10584ac Build where it stopped working. #10076 

* One for the build with regression.
[Persona4ArenaBroken.zip](https://github.com/RPCS3/rpcs3/files/6287187/Persona4ArenaBroken.zip)
* One for the build that works as expected.
[Persona4ArenaWorking.zip](https://github.com/RPCS3/rpcs3/files/6287189/Persona4ArenaWorking.zip)

@Megamouse

**Comment by Megamouse** [comment]
Can you test the PR build please ?
