### ISSUE TITLE
Game won't load anymore - deadly premonition

### ISSUE THREAD

**Issue by raspinall** [RPCS3/rpcs3#10096]
The first time I played this in rpcs3 a couple days ago, it booted right up and I played for about an hour without any issues.  Today, I tried to resume my game but the game window just goes black after showing the auto-save notification, and the log repeatedly cycles the following messages:

U cellCamera TODO: cellCameraSetAttribute(dev_num=0, attrib=9=LED, arg1=0, arg2=0)
U cellGem TODO: cellGemGetStatusFlags(gem_num=0, flags=*0x1e1b2e8)
U cellGem TODO: cellGemGetStatusFlags(gem_num=1, flags=*0x1e1b2f0)
U cellGem TODO: cellGemGetStatusFlags(gem_num=2, flags=*0x1e1b2f8)
U cellGem TODO: cellGemGetStatusFlags(gem_num=3, flags=*0x1e1b300)
U cellCamera TODO: cellCameraSetAttribute(dev_num=0, attrib=9=LED, arg1=0, arg2=0)

in what appears to be an endless loop.  I haven't changed any settings from the last time it worked.  Can anyone help?

**Comment by Megamouse** [comment]
The issue template clearly stated that you should upload a log file containing a session in which this happened.
So please do so.

**Comment by raspinall** [comment]
This was resolved by clearing all game caches.
