### ISSUE TITLE
Tron: Evolution [BLUS30457]: Flickering when moving camera

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#10098]
Flickering occurs as you move the camera around. It looks like the lighting changes depending on the cam angle.

![1](https://user-images.githubusercontent.com/20983844/114318068-10221700-9ac0-11eb-9050-932e664a9dce.png)

![2](https://user-images.githubusercontent.com/20983844/114318070-11ebda80-9ac0-11eb-85e9-5f1d3297a7ac.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6292611/RPCS3.log.gz)

RSX Capture:
https://drive.google.com/file/d/1WykkXBNVKv9t816VdbKTrIC9NYN7JyFT/view?usp=sharing

Config:
Windows 10 64-bit
GeForce GTX 3070
AMD 5900x@ 4.8ghz
32GB RAM

**Comment by GitArUs** [comment]
Something similar is reported in #8603. Although it says about "small sections" it can be observed as big sections on walls as well. Could You try with shader mode set to "Shader interpreter only" ? (Yes, it will be slow).

**Comment by legend800** [comment]
Nope no diff. Actually makes it worse and causes the screen to be too bright and increases blooms way too much. Strange.

![2021-04-16 00_32_09-PS3](https://user-images.githubusercontent.com/20983844/114988584-5a522200-9e4b-11eb-9e81-f688f978f7fc.png)

**Comment by legend800** [comment]
Still active as of 0.0.16-12427.

**Comment by Darkhost1999** [comment]
PR #10733 by kd-11
Fixes this issue can be closed
