### ISSUE TITLE
Fatal error on 0.0.15-12078

### ISSUE THREAD

**Issue by vit0rph3nom** [RPCS3/rpcs3#10101]
## Quick summary

Fatal error: some thread has probably deadlocked. Aborting. Thread id =22644

## Details

Found this issue on the version 0.0.15-12078 while trying to restart the emulation or closing it with different games, every time the emulator hanged and crashed with this error. Rolled back to 0.0.15.12039 and didn't experience the same problem again. Didn't got a log due to the emulator crashing and closing.

![image_2021-04-12_013757](https://user-images.githubusercontent.com/82357725/114341235-ac373700-9b2f-11eb-94e1-952c8d77c083.png)

* OS = Windows 10 x64
* CPU = Intel Xeon e3 1245v2
* GPU = GTX 1660ti
* Driver version  = 461.09

**Comment by Megamouse** [comment]
Can you try to find the exact version that introduced this behaviour?

**Comment by vit0rph3nom** [comment]
![awd](https://user-images.githubusercontent.com/82357725/114464997-e69ae580-9bbc-11eb-9c9f-f06b4a125256.png)

i was using this build when i had this error.

**Comment by AniLeo** [comment]
That's not the question, the question is what build introduced this problem, as required by the Regression Template in order to flag the PR that introduced the breaking change.

It's literally impossible that 10093 caused this since it doesn't touch any code.

**Comment by vit0rph3nom** [comment]
well i'm not understanding what you mean by "build" in this case, because that was the version or build or whatever you wanna call where i got this problem, and i don't know why this could be "impossible" since i LITERRALY post the print. As i said before, i rolled back to a previous version i was using and didn't got this error at all since yesterday.

**Comment by AniLeo** [comment]
The build where you got this issue isn't the build that introduced it. The gap of builds you mention between the known good build and the current one you're crashing on is too big. As the Regression Template mentions and I just said, we need the exact build that introduces this crash. You need to do binary search using your known interval to pinpoint exactly what build introduced this issue so we can know what PR introduced it.

**Comment by Megamouse** [comment]
Or in simple terms:
Test the versions between the two versions you mentioned ([see here](https://rpcs3.net/compatibility?b)).
Start with the version that's in the middle between the one you noticed the bug and the one you rolled back to and so on and so forth until you find the exact version that introduced the bug.

**Comment by vit0rph3nom** [comment]
Oh i got it, i'm going to download and test the versions in between the 2 i reported to see if i get the same error. TY for the help.

**Comment by vit0rph3nom** [comment]
I've just tested multiple versions between the one i have installed and the one that the crash happen, even tested the same build again and didn't got the issue again, nothing changed, everything configured the same between all versions. Now i'm curious to know what could have caused this.

**Comment by Megamouse** [comment]
Random error.
