### ISSUE TITLE
Regression: Incorrect texture decoding/rendering

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#10106]
Presumably from #10090, don't have more information at this point

Two of the affected games are God of War HD and Killzone 

![image](https://user-images.githubusercontent.com/10283761/114422927-9c126c80-9bae-11eb-8388-a5d4b89eb9ce.png)
![image](https://user-images.githubusercontent.com/10283761/114422958-a16fb700-9bae-11eb-80d0-38e59ae7761b.png)

@kd-11

**Comment by kd-11** [comment]
Seems to only affect vulkan. Mipmaps for some formats are not populating correctly.

**Comment by kd-11** [comment]
Mipmap pitch was calculated using the wrong parameter. Fixed by https://github.com/RPCS3/rpcs3/pull/10107.
