### ISSUE TITLE
On-Screen Keyboard (OSK) unable to output blank fields

### ISSUE THREAD

**Issue by SeongGino** [RPCS3/rpcs3#10100]
## Details

When using the OSK for text input, entering a blank field (specifically **when the text field is pre-filled, and is then deleted intentionally by the user** - does _not_ apply if the initial input is already blank) instead prints out the example text `[Enter Text]` verbatim.
This is typically a non-issue in some games like Demon's Souls, where it's only used in profile creation and a player probably isn't going to use a blank name; however, Tales of Vesperia for PlayStation 3 [BLJS10053] allows six-character text to replace the default names of party members. Attempting to blank out the field (which would reinstate the character's original designated name) instead creates a custom character name `[Enter` (yes, the bracket isn't closed - remember, six characters).

This wouldn't be a real issue, if one of the characters' default first names wasn't `Estellise` or `Estelle` (in English translation); either of which obviously is beyond six alphanum characters.

#### Screenshots
(Click the links for video demonstration; images provided merely show the end result of the bug)
[Tales of Vesperia w/ English Patch [BLJS10053]](https://i.imgur.com/P50A58P.mp4)
![bugeng](https://user-images.githubusercontent.com/7321839/114324521-89d5f700-9af8-11eb-9815-beb008a60af7.png)

[Demon's Souls [BLUS30443]](https://i.imgur.com/aUuOdXu.mp4)
![dsbug](https://user-images.githubusercontent.com/7321839/114324627-28faee80-9af9-11eb-9d43-80e522220d05.png)

#### 4. Please provide comparison with real PS3.
Without ability to record off a real PS3, I can at least confirm that blanking out fields works as intended on hardware - i.e. blank'd text results in game-defined behavior for blank input, not printing out the OSK-provided placeholder text like on RPCS3 (in context of these examples, ` ` becomes `Estellise`/`Estelle` in Vesperia, `Please enter a name` in DeS, etc.)

#### System Configuration:
* RPCS3 0.0.15-12079 06dc99ab
* Windows 10 20H2
* Intel i7-4790k
* NVIDIA GeForce GTX 1060 6GB
* NVIDIA Driver ver. 465.89 (Public)

#### Other Notes:
* For BLJS10053, version demonstrated is an English Patched version; the same has been tested and applies to unmodified Japanese region version as well.
![bug](https://user-images.githubusercontent.com/7321839/114324544-ab36e300-9af8-11eb-89e2-bba7fa6c3985.png)

**Comment by Megamouse** [comment]
This sounds like a regression to me.
I think I even know which commit broke it.
I'm sure it works if you use disable the native user interface in the settings.
