### ISSUE TITLE
Top Spin 4 crashes with: F {RSX [0x0182a14]} SIG: Thread terminated due to fatal error: Verification failed

### ISSUE THREAD

**Issue by danniss10** [RPCS3/rpcs3#10138]
## Quick summary
Please briefly describe what has stopped working correctly.

Top Spin 4 used to play perfectly fine but now every time I play the game, RPC3 crashes after the start menu with this error:
F {RSX [0x0182a14]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\GL\GLHelpers.cpp:558[:3], in function scale_image)

The crash usually happens once game play actually starts. 

## Details
Please describe the regression as accurately as possible.

F {RSX [0x0182a14]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\GL\GLHelpers.cpp:558[:3], in function scale_image)

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
* Please see [How to find the build that caused a regression](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression.3F) in our wiki.
* You can find [History of RPCS3 builds](https://rpcs3.net/compatibility?b) here.

I am not sure the exact version that caused the crash but the game was working fine around the end of March 2021. I updated on April 15th, 2021 to the latest version. I have since tried going back to an older version but when I do that the bug still stays. Is it possible some other meta data gets cached?

#### 2. Please attach TWO logs:
* One for the build with regression.
* One for the build that works as expected.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6330479/RPCS3.log)

##### How to obtain RPCS3's log:
* Run the game until you find the regression.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc. 

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc. 
	And drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 4. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 6. Please provide your system configuration:
* OS: Windows 10
* CPU:
* GPU
* Driver version
* etc.

ASUS - ROG Zephyrus G14 14" Gaming Laptop - AMD Ryzen 9 - 16GB Memory - NVIDIA GeForce RTX 2060 Max-Q - 1TB SSD

#### Please include.
* Anything else you deem to be important

**Comment by kd-11** [comment]
I am unable to reproduce this crash. Perhaps a screen recording could help.

**Comment by kd-11** [comment]
Ask to reopen if issue persists.
