### ISSUE TITLE
F VM: Access violation reading location 0x0 (unmapped memory) [type=u32] MGS3 HD Edition

### ISSUE THREAD

**Issue by Maxterino** [RPCS3/rpcs3#10144]
Hello,

So when i defeat Volgin and goes to the cutscene where he gets in the Shagohod, the cutscene ends and should go to gameplay to defeat the shagohod. However when the cutscene ends, the game goes black to load the gameplay but freezes in the black screen and i get the error F VM: Access violation reading location 0x0 (unmapped memory) [type=u32] in the RPCS3 log. Can you guys help me out? Thank you!

**Comment by AniLeo** [comment]
---

**Please read the respective issue template before opening an issue**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
