### ISSUE TITLE
RPCS3 save/load UI does dualshock 3 stop work " recognize input commands",

### ISSUE THREAD

**Issue by Kojikun1** [RPCS3/rpcs3#10154]
## Quick summary
RPCS3 save/load Ui does dualshock 3 stop work " recognize input commands",

## Details
All games that use the save/load  UI, make the controller stop work,
the dualshock 3 remains connected and recognized in the emulator but the commands do not work,
the games that have a own save ui and load automatically does not have this problem
The Problem occurs with bluetooth and cable
the dualshok 4 working fine.

ps : I using a original genuine sony dualshock 3
and  Nefarius' DsHidMini driver with bluetooth.

for bypass this issue need to disconnect and reconnect a controller after the save loads

#### 1. Please attach RPCS3's log.
 Hatsune Miku project Diva F
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6336584/RPCS3.log.gz)
Nier Replicant Log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6336589/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Before anyone will ever start looking into this, someone has to confirm if this also happens without the Nefarius driver.

**Comment by Megamouse** [comment]
Might be fixed by #10160 (Next update)

**Comment by Kojikun1** [comment]
@Megamouse unfortunately did not fix the problem

**Comment by HerrHulaHoop** [comment]
Try it wired instead of bluetooth. If that doesn't work, completely uninstall Nefarius' driver and try with the Don't driver (wired obviously).

**Comment by Kojikun1** [comment]
@HerrHulaHoop wired as the same problem with Nefarius' driver i will try with sony driver.

**Comment by Kojikun1** [comment]
After disassembling and cleaning the dualshock 3, in addition to improving contacts, this fixed the problem.
probably some problem in the dualshock, it was working correctly but something was causing this behavior
