### ISSUE TITLE
[Feature Request] Syscall monitor (procmon style)

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#10150]
A facility for monitoring all sorts of syscalls / libcalls would be pretty useful for all kinds of forensics, such as game modding (file format research) or just general bug hunting. Would perhaps allow for reducing the scope of the logging facility, and make it only responsible for logging emulator events. Especially if these event reports could be exported into file.

It would also curb users being scared by red text in the log window, courtesy of game developers. I'm not sure if the two things should still end up in the same logfile though behind the scenes.. maybe?

Thinking about something procmon style stuff here all in all. Sort of ties into #8465.

**Comment by elad335** [comment]
What you want is built-in assembler fot single instruction. So for PPU syscalls you assembler the instruction `li r11, (syscall number)` and then use the memory string search to find it.

**Comment by elad335** [comment]
Libcalls locations and their function names are already logged, it's called library imports.

**Comment by dio-gh** [comment]
Not really sure we're on the same page. I want not just a list of syscall/libcall names the games use, but rather a list of every time a call is made, with all the arguments passed, realtime. This is why I kept referring to procmon.

Example screenshot from procmon:
![image](https://user-images.githubusercontent.com/10439488/115264287-74834d00-a136-11eb-9562-784aeaef448b.png)

**Comment by elad335** [comment]
It's not as fancy as requested, but #14125 is merged now.
