### ISSUE TITLE
[Demo's Souls] Poor performance for the entirety of some gaming sessions (intermittent issue)

### ISSUE THREAD

**Issue by Nicholas-Steel** [RPCS3/rpcs3#10153]
## Quick summary
Performance/frame pacing is sometimes terrible during the entirety of a game session. issue is immediately noticeable during gameplay and the effect is observable in the Performance OSD statistics. Quitting emulation (no need to quit RPCS3) and restarting it can resolve it.

## Details

1) Open RPCS3
2) Launch game.
3) The game will either perform as expected or perform terribly until you stop emulation.
4) Quit the game and then re-launch it, you don't need to close RPCS3.
5) The game will either perform as expected or perform terribly until you stop emulation.

When the problem transpires it _feels_ like the game is running at a frequently fluctuating FPS, somewhere around 30FPS even though all indicators indicate 50+FPS.

https://www.youtube.com/watch?v=PhOBJYca7Tg
My 3rd attempt at demonstrating the phenomena succeeded (2:29), previous attempts are included in the video for comparison. Note the highly volatile Frame Timing in the OSD chart as well as the game stuttering during the 3rd attempt. No setting changes were made and no other software was interacted with during & between attempts at producing the issue.

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6335545/RPCS3.log.gz)

#### 5. Please provide your system configuration:
* Windows 10 (latest stable release)
* Ryzen 3700X
* Geforce 1070Ti
* 465.89 & older

#### Other
Has been observed since September 2020, when I first started using RPCS3. Originally thought it was a misconfigured motherboard BIOS setting causing weird performance issues in RPCS3 but now I know it's RPCS3 specific and the issue is intermittent.

**Comment by Megamouse** [comment]
We don't support issues that were created with applied patches.
