### ISSUE TITLE
Regression: SPU LLVM issues on games such as The Last of Us, Uncharted 3 (#10164)

### ISSUE THREAD

**Issue by BSoDGamingYT** [RPCS3/rpcs3#10165]
Latest master at time of posting (0.0.15-12131) has both a graphical and gameplay progression regression in The Last of Us and Uncharted 3

I believe this issue may only affect icelake/rocket lake CPUs when using SPU LLVM, and be caused by https://github.com/RPCS3/rpcs3/pull/10164 as it was the change added in this version.

The Last of Us before this change (0.0.15-12130)
![Capture (1)](https://user-images.githubusercontent.com/38402209/115434100-964d0480-a208-11eb-8aeb-78a498ac6fe3.png)

After (0.0.15-12131)
![21](https://user-images.githubusercontent.com/38402209/115434125-9d741280-a208-11eb-97e7-b49caef86fd9.PNG)

This change seems to also cause Uncharted 3 to hang/crash when loading in game. TLOU has similar stability issues which seem to be related, but it at least loads into gameplay.

If additional information is required, please ask

**Comment by AniLeo** [comment]
Confirmed

**Comment by Nekotekina** [comment]
I can temporarily disable some ICL features, unless they improve performance so significantly. Or just wait for fix.

**Comment by Whatcookie** [comment]
I'll just open a PR to remove the icelake shufb paths for now, I don't have enough games on my laptop to test everything right now

**Comment by Nekotekina** [comment]
Did you run spu elf tests? At least https://github.com/RPCS3/ps3autotests/tree/master/tests/cpu although there were others

**Comment by Whatcookie** [comment]
I've tried running them before, but they never worked. Only the ppu tests worked for me. Do they work for you?

**Comment by Nekotekina** [comment]
That's strange, I think they do. Did you make sure to have spu elf hearby?

**Comment by Whatcookie** [comment]
Yes, I've downloaded both `spu_alu.ppu.elf` and `spu_alu.spu.elf` it still closes before printing anything

**Comment by Nekotekina** [comment]
I see, let me try to fix it.

**Comment by Nekotekina** [comment]
Oops.

**Comment by Whatcookie** [comment]
I think I figured it out after all
