### ISSUE TITLE
[Feature Unrequest] Remove CTRL+S from the hotkeys

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#10161]
So as it turns out, to my absolute delight, pressing CTRL + S closes your game.

...

Why? *Why?*

I was in the middle of making a new mouse hook demonstration, meaning I wanted to get ahead of myself, skip the deref chain tracing, and just hardcode in some memory addresses for KAMI to hook onto. In this case however, that meant a grand total of 9 addresses, which took a great pain to gather. Didn't help that GTHD is very sensitive to pausing, so I always ran the chance of it hanging on me.

Then I made the mistake of accidentally pressing CTRL+S twice, by reflex, after switching away from Visual Studio to the game window. You may guess what happened.

Who thought this was a good idea? Why? Has that person not heard of Alt+F4 before? In what world is it a good idea to bind unconditional exit to the same button as most other applications' save feature?

My absolute best wishes to the OP of #2831, thank you for pissing me *way* off on this beautiful early morning.

**Comment by Megamouse** [comment]
Still not as bad as accidentally typing some password into the group chat when you thought you had the terminal in focus

**Comment by dio-gh** [comment]
did that happen to you or did that happen to me
