### ISSUE TITLE
Motorstorm crashes before game initialized @ "Building SPU Cache" - Linux  [SIG: Thread terminated]

### ISSUE THREAD

**Issue by TheBrinkOfTomorrow** [RPCS3/rpcs3#10179]
## Quick summary
Motorstorm crashes before game initialized.

 
## Details
Command line output:
$ ./rpcs3-v0.0.15-12142-087dccd1_linux64.AppImage' 
Debugger: 0
mv: /tmp/.mount_rpcs3-3dyMpz/usr/lib/libselinux.so.1: no version information available (required by mv)
RPCS3: PPU[0x1000000] Thread (main_thread) [0x00ba8b90]: SIG: Thread terminated due to fatal error: Verification failed
(in file ../Utilities/File.cpp:1325, in function write) (errno=22)

Motorstorm crashes with above error upon starting the game....  [has always worked previously.  Last played about 2 months ago].  Using Vulkan graphics pipeline.
Screen shot attached.

#### 1. Please attach RPCS3's log.
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/6365133/RPCS3.log.zip)

#### 4. Please provide comparison with real PS3.
n/a

#### 5. Please provide your system configuration:
* OS - Ubuntu 20.10, 
* CPU - Ryzen 5600X
* GPU - Radeon RX 5700 XT
* Driver version - Kernel 5.11.6, Mesa 21.2.0-devel (git-42658ab 2021-04-23 groovy-oibaf-ppa)
* Vulkaninfo: GPU id : 1 (AMD RADV NAVI10 (ACO)):

![motorstorm-crash-2021-04-23 08-01-14](https://user-images.githubusercontent.com/36106138/115868304-42aa0900-a40a-11eb-94bd-2fa2466aa55d.png)

**Comment by gamrXerus** [comment]
I can confirm all my games cannot boot when using Vulkan on linux because of this same issue.
![bug6](https://user-images.githubusercontent.com/19245344/116126249-6aac9d00-a694-11eb-9f58-25199330eb0b.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6379024/RPCS3.log.gz)
Core i5 8600K
Radeon RX 6800
 Ubuntu 21.04
Kernel 5.11.0-16 Mesa 21.2.0-devel (git-a02a0df 2021-04-26 hirsute-oibaf-ppa)

**Comment by gamrXerus** [comment]
UPDATE: Seems to be a driver issue. I purged the oibaf ppa and reverted to standard Ubuntu drivers. That fixed the issue. Perhaps a bug report should be sent to Mesa developers.
