### ISSUE TITLE
Sonic Unleashed Crash Regression

### ISSUE THREAD

**Issue by RandomAnimeGamer** [RPCS3/rpcs3#10189]
## Quick summary
Sonic Unleashed crashes are more common and vary greatly in the latest build of RPCS3 (0.0.15-12155-7197dd75 Alpha).

## Details
In build 0.0.11-10736-d3585e1f Alpha, Sonic Unleashed works on my hardware using default settings, with low performance.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6371139/RPCS3.log.gz)

In build 0.0.11-10736-d3585e1f Alpha, Sonic Unleashed works on my hardware using the recommended RPCS3 Wiki Settings (1us Driver Wake-Up Delay), with slightly better performance.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6371141/RPCS3.log.gz)

In build 0.0.15-12155-7197dd75 Alpha, Sonic Unleashed crashes randomly on my hardware using the recommended RPCS3 Wiki Settings (Tried changing **Driver Wake-Up Delay** between _1us_ and _200us_, tried changing **Shader Mode** between _Async (multi threaded)_ and _Async with Shader Interpreter_).
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6371170/RPCS3.log.gz)

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.15-12155-7197dd75 Alpha

#### 2. Please attach TWO logs:
* One for the build with regression.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6371170/RPCS3.log.gz)
* One for the build that works as expected.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6371141/RPCS3.log.gz)

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
Not a graphical regression.

#### 4. Please attach screenshots of your problem.
Screenshots are not effective to describe the issue, the game will freeze-frame and stay there, while an error is logged on RPCS3.

#### 5. Please provide comparison with real PS3.
PS3 doesn't crash randomly.

#### 6. Please provide your system configuration:
* Windows 10 (64-bit)
* Intel i7-6700K (4Ghz)
* AMD RX 580
* Radeon Software Version 20.11.1

#### Please include.
Prior to attempting to write these logs, the game would crash on areas like the second cutscene, first cutscene, loading screens, etc. Upon generating the log to upload here for the latest RPCS3, it went way further than normal with no game configuration changes (I got all the way up to the end of the second stage before it crashed).

These crashes are not the purple crash (Not logged as a fatal error), it's a "red crash" (Logged as a regular error).

**Comment by RainbowCookie32** [comment]
There are a fair amount of builds between 0.0.11-10736 and 0.0.15-12155. Did you test builds between those two, or just assumed the latest build introduced the issue? I don't think that build specifically would introduce random freezes.

**Comment by AniLeo** [comment]
It's literally impossible that `0.0.15-12155-7197dd75 Alpha` introduced this regression looking at the code since Sonic Unleashed doesn't use sys_fs_fnctl 0xE0000025

**Comment by RandomAnimeGamer** [comment]
I'll have to test more later. I'm honestly super exhausted today, it'll have to wait.

**Comment by RandomAnimeGamer** [comment]
I checked the logs more in-depth and found that a TSX function was referenced in the logs. Upon disabling TSX on 0.0.15-12155, the game is working with no crashes. Given the tendency of Sonic Unleashed to have SPU thread locks, I think that this is related to recent TSX Regressions regarding performance. #10001

**Comment by elad335** [comment]
I will fix soon a common random crash I encountered on my end which can even cause RPCS3 to not respond.
