### ISSUE TITLE
NULL-dereference (crash) with The Last of Us

### ISSUE THREAD

**Issue by jvoisin** [RPCS3/rpcs3#10198]
## Quick summary
While trying to boot The Last of Us™ [BCES01584], RPCS3 encounters a NULL-pointer dereference and crashes, with this in the logs:

```
E ppu_loader: Already linked function '0xFF05DD1F' in module 'libsmvd2'
S sys_prx: Loaded module: “/dev_flash/sys/external/libsmvd2.sprx” (id=0x23008100)
F VM: Access violation reading location 0x0 (unmapped memory) [type=u0]
```

## Details

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6379849/RPCS3.log.gz)

**Comment by Satan86** [comment]
Set default resolution to 1280x720 and it shouldn't crash, increase resolution scale instead.

**Comment by clienthax** [comment]
![1jolpq](https://user-images.githubusercontent.com/1056270/116142790-3b1c8580-a6d2-11eb-865f-533ee963ff04.jpg)
I can't believe you actually opened a issue for a pirated game.
