### ISSUE TITLE
Uncharted 3 Drake’s Deception F VM: Access violation reading location 0x2b8 (unmapped memory) 

### ISSUE THREAD

**Issue by sector24** [RPCS3/rpcs3#10190]
When you start the game Uncharted 3 Drake's Deception BCES01175 appears for about 5 seconds loading-black screen and spinning ring, and then the game freezes. I tried different versions of the emulator, but everything is the same, the following error appears in the log:
F VM: Access violation reading location 0x2b8 (unmapped memory) [type=u32]
S SPU: New block compiled successfully x9

PC: Win10 x64 intel i7-9700KF 4.1 GHz 16GB RAM GTX1080

![image](https://user-images.githubusercontent.com/80105112/115996818-8ad35200-a5e9-11eb-8411-78e2922ab413.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6372130/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6372131/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Bad settings together with a bunch of game patches are enabled, this is an invalid ticket.

---
Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by sector24** [comment]
> Bad settings together with a bunch of game patches are enabled, this is an invalid ticket.
> 
> Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).
> 
> The issue has been marked as **Invalid** and closed.

Please tell me how to solve the problem or where I need to write to help solve this problem?
