### ISSUE TITLE
Burnout Paradise: in-game clock not in sync with system clock

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#10195]
In Burnout Paradise there is a "Time Of Day" option to permit the game to match the console's time based on its internal clock.  However, in testing it appears the game's clock is 7 hours ahead of the system clock even though the time as shown in RPCS3's settings matches the host system's time.   Thanks to PR #8837 console time can be manually adjusted as 7 hours behind the host system time, though this shouldn't be necessary.

Another possibility is that the system is accounting for time zone differences, and if that were true, the ability to set time zone would be nice to expose in the RPCS3 system menu (@bevanweiss any thoughts here?).

System specs:
* OS: Linux Mint 20.1 / kernel 5.11
* CPU: Intel i7-10870
* GPU: Nvidia GTX 3070
* Latest commit tested: 4c2a11b6d0e4edef24b7a26fd01f3fc59c820221

**Comment by elad335** [comment]
Might be russian time zone related, specifically.

**Comment by Shoegzer** [comment]
Interesting, something hard-coded I suppose.  I would think defaulting to UTC time with an option to change time zone based on offset would be ideal.

**Comment by Nekotekina** [comment]
Hi, can you test the PR without adding time offset?

**Comment by Shoegzer** [comment]
Thanks @Nekotekina.  With your PR and with RPCS3 reset to system time, the ingame time is now only 1 hour behind RPCS3/system time.  I believe that's due to daylight savings time.  It would be great if RPCS3 could account for this as @Megamouse mentioned, as manual adjustment is still required without it.  Regardless though, this is nice progress.

**Comment by Nekotekina** [comment]
Interesting, I don't know how summertime is interpreted. I guess I need to take a look at it.

**Comment by Megamouse** [comment]
I would assume that it is just a 1 for daylight saving.

**Comment by MSuih** [comment]
In windows api it is the amount of minutes the standard time is adjusted by, could be something similar here as well.

**Comment by Nekotekina** [comment]
Okay, pushed an update.

**Comment by Shoegzer** [comment]
Fantastic @Nekotekina - with your PR update the game now detects the time exactly as specified in the RPCS3 settings.  Assuming the code will detect when DST ends again in the winter months, I'll close this issue once merged (or feel free to yourself).  Thanks so much!
