### ISSUE TITLE
Spider-Man™: Edge of Time [BLUS30760] - Heavy Lighting Flicker

### ISSUE THREAD

**Issue by TheRealPSV** [RPCS3/rpcs3#10196]
## Quick summary
Intense lighting flicker in Spider-Man™: Edge of Time [BLUS30760], found during the level "Things Fall Apart".

## Details
At certain points in the game, there seems to be heavy lighting flickering, almost like a bloom effect is snapping on and off, or like a flickering fluorescent light is in the scene.

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6373813/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
RSX Capture: [BLUS30760_20210425221348_capture.zip](https://github.com/RPCS3/rpcs3/files/6373840/BLUS30760_20210425221348_capture.zip)

To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).
* Attempted to create RenderDoc capture, but it just caused RPCS3 to crash.

#### 3. Please attach screenshots of your problem.
Normal: ![normal](https://user-images.githubusercontent.com/6434386/116021380-16fb6e80-a616-11eb-99c9-e5c1869f2ffe.jpg)
Flicker frame: ![flickeron](https://user-images.githubusercontent.com/6434386/116021389-1bc02280-a616-11eb-8810-5ccd7d5cbb39.jpg)

Video example (includes performance overlay): 
https://user-images.githubusercontent.com/6434386/116021446-35fa0080-a616-11eb-8186-f5c3d8ca5a15.mp4

#### 4. Please provide comparison with real PS3.
Flickering was not present on real PS3.

#### 5. Please provide your system configuration:
* OS - Win10 Pro x64 v20H2 (build 19042.928)
* CPU - AMD Ryzen 9 5950X 16-Core Processor@3.40 GHz
* GPU - Nvidia RTX 3090
* Driver version - Nvidia driver v466.11
* RAM - 64 GB
* RPCS3 version - RPCS3 v0.0.15-12161-9609767c Alpha

#### Other
Seems similar to #10098, except it happens even when camera isn't moving. Tried using shader mode set to "Shader interpreter only", which stops the flickering but, similarly to the referenced issue, causes the game to look completely washed out.

**Comment by digitaldude555** [comment]
@TheRealPSV retest

**Comment by TheRealPSV** [comment]
> 
> 
> @TheRealPSV retest

No change as of RPCS3 v0.0.17-12655-1cdb2c6a Alpha.
Log attached: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7029320/RPCS3.log.gz)

**Comment by Darkhost1999** [comment]
This looks a lot like Tron Evolution flicker that has been fixed. Can we get a retest of this issue see if it's still present now?

**Comment by TheRealPSV** [comment]
> This looks a lot like Tron Evolution flicker that has been fixed. Can we get a retest of this issue see if it's still present now?

Just tested in v0.0.22-13764-7530b3c9 Alpha, looks like the flicker's gone. I'll go ahead and close the issue. Thank you!
