### ISSUE TITLE
PS3 controller not working correctly

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#10202]
Thanks very much for read my topic.
Using Ubuntu 20.04 with RPCS3 0.0.15-11949 and installed HIDAPI with PS3 controller original.
RPCS3 show PS3 connected, but the left and right analog not work and buttons are inverted. Triangle is square, X is circle and etc.
In same OS the controller work correctly with others emulators.
I will test with current release 0.0.15-12163 in Ubuntu 21.04 and will post results.

Other detail is in https://github.com/libusb/hidapi say
"Warning: Only run the code you understand, and only when it conforms to the device spec. Writing data at random to your HID devices can break them."
I had connected another PS3 controller original, but also had installed qtsixa.
The controller had worked for few minutes and after in controller in area below battery was very hot and led the light was very weak at point not light. The controller was "damaged". If connecting the OS show that an "PS3 controller" was connected, but not input.
I not understand if qtsixa or hidapi had damaged that controller.
I saying here to share all above.

**Comment by Augusto7743** [comment]
using information from
https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration
and created /etc/udev/rules.d/99-ds3-controllers.rules
now the controller works and has problems if using evdev.
Support is in forum and not here, but I has an damaged controller and reading information about hidapi very care about use another controller if hidapi can damage controller.
Is secure use ps3 controller with hidapi in rpcs3 current version ? hidapi has bugs ?
I only had created that topic to avoid damage in controller of others users.

**Comment by Megamouse** [comment]
Superseded by #10495
