### ISSUE TITLE
Iron Man [BLUS30134] black lines and crashing

### ISSUE THREAD

**Issue by TheRealPSV** [RPCS3/rpcs3#10215]
## Quick summary
Iron Man [BLUS30134] (v1.02) crashes after a little while in-game with repeated "RSX: Cache miss at address 0xC9ACA200. This is gonna hurt..." messages.

Also noticing black lines/bars popping in on screen randomly.

## Details

Problem happened in "Mission 6: Flying Fortress", the game plays fine for a while, then RPCS3 entirely crashes; the entire application exits.

Additionally black lines/bars keep popping up on-screen.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6408815/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
RSX Capture (not at exact frame of glitch) [BLUS30134_20210430231132_capture.zip](https://github.com/RPCS3/rpcs3/files/6408816/BLUS30134_20210430231132_capture.zip)

#### 3. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/6434386/116769515-c8c9df00-aa0a-11eb-9101-262398b88334.jpg)
Video (easier to see the graphical issue): https://user-images.githubusercontent.com/6434386/116769613-5efe0500-aa0b-11eb-957a-32dafaefbe03.mp4

#### 4. Please provide comparison with real PS3.
Flickering and crashing do not occur.

#### 5. Please provide your system configuration:
* OS - Win10 x64 v20H2
* CPU - AMD Ryzen 9 5950X 16-Core Processor @ 3.40 GHz
* GPU - Nvidia RTX 3090
* Driver version - Nvidia Driver v466.11
* RAM - 64 GB

**Comment by AniLeo** [comment]
Your RPCS3 folder is on Program Files, where it should never be, move it to somewhere that it's not a weird permissions Windows directory
Also, disable `Multithreaded RSX` when testing for instability in RSX, and always test with stock resolution scale

**Comment by TheRealPSV** [comment]
Updated the issue with a new log and information on a graphical issue I forgot to show previously. (Issue did occur on version of RPCS3 the old log was tested against.)

**Comment by Realmantik** [comment]
@TheRealPSV , can you provide a save file for testing?

**Comment by TheRealPSV** [comment]
> @TheRealPSV , can you provide a save file for testing?

Sure thing, here you go: [BLUS30134SL.zip](https://github.com/RPCS3/rpcs3/files/6412606/BLUS30134SL.zip)

**Comment by kd-11** [comment]
A cache miss is nothing to be worried about.

**Comment by TheRealPSV** [comment]
Not sure what changed, but as of 0.0.17-12599-b7e4de6e, the game is working fine again. Closing for now.
