### ISSUE TITLE
Persona 5 (BLUS31604) crash after using items

### ISSUE THREAD

**Issue by Ledarium** [RPCS3/rpcs3#10219]
## Quick summary
When resolution scaling is enabled (I have tried 1080p, 1440p, 2160p), the game crashes after using item in Palace. 

## Details

My actions: 
1. go out of save room
2. go to menu
3. restore HP or SP
4. press O to exit from item menu to game menu
5. crash with message `Segfault reading location 0000000000000044 at 00007fe6281f954c`. Location and address seem to be persistent between crashes and also when I try to reproduce it in different palaces

#### 0. Make sure you're running with settings as close to default as possible
All settings are default except `Strict rendering` disabled and resolution scaling set to 1080p

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6408383/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
N/A

#### 3. Please attach screenshots of your problem.
N/A

#### 4. Please provide comparison with real PS3.
N/A

#### 5. Please provide your system configuration:
* OS: Manjaro Linux 21.0.3
* CPU: Ryzen 5 2600
* GPU: Radeon RX 570 Series (POLARIS10, DRM 3.40.0, 5.10.30-1-MANJARO, LLVM 11.1.0)
* 16 GB of RAM

**Comment by AniLeo** [comment]
The log file you uploaded is corrupted, manually compress the text log and upload that

**Comment by Ledarium** [comment]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6409218/RPCS3.zip)
Retried with `RPCS3 v0.0.16-12199-b8477a47 Alpha | master`

**Comment by Ledarium** [comment]
Actually, I was able to reproduce this without resolution scaling,

**Comment by Ledarium** [comment]
Bug seems to be Vulkan-specific. Here I am doing same actions, but with OpenGL enabled:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6409479/RPCS3.zip)

**Comment by AniLeo** [comment]
Try with amdvlk, may be radv specific

**Comment by Ledarium** [comment]
> radv specific

Looks like it. There is no crash when I am using `amdvlk` with this line in log: `RSX: Found vulkan-compatible GPU: 'Radeon RX 570 Series' running on driver 2.0.181`.

**Comment by kd-11** [comment]
So it crashes in any palace? Or just a specific one?

**Comment by sylveonsylvia** [comment]
> So it crashes in any palace? Or just a specific one?

in my own testing it crashes in every palace and in mementos

**Comment by Ledarium** [comment]
> > So it crashes in any palace? Or just a specific one?
> 
> in my own testing it crashes in every palace and in mementos

yes, also can sometimes crash outside of palace
