### ISSUE TITLE
Stuck at "Loading PPU Modules" using ASMJIT

### ISSUE THREAD

**Issue by JulianGro** [RPCS3/rpcs3#10223]
When trying to run something using ASMJIT, RPCS3 gets stuck on "Loading PPU Modules" and crashes when trying to exit the game.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6409432/RPCS3.log.gz)

* OS Linux Mint 19.3
* CPU Intel i7-7800x
* GPU Nvidia GTX 1080
* Driver version 450.119.03

If I switch the PPU Encoder to precise, I don't even get the "Loading PPU Modules", I only get a blackscreen with the performance overlay.

**Comment by Augusto7743** [comment]
Have tried clean all caches ?

**Comment by JulianGro** [comment]
Deleting all caches fixes the issue and I don't have any way of telling what broke the cache and how.

**Comment by silviuzlota** [comment]
Any solution for this issue?
