### ISSUE TITLE
Split-Screen Games Run at Half-Speed

### ISSUE THREAD

**Issue by jeremybris** [RPCS3/rpcs3#10237]
## Quick summary
There are less frames per second in split-screen mode.

## Details

- From v. 0.0.7-9233 and after, it is not a regression.
- It is not a resolution upscaling problem. Using "Strict Rendering Mode", at 720p, the issue persists. 
- 2 players is 1/2 the speed it would be in singleplayer. 4 players is 1/4 the speed.
- In a game that shares the same screen for multiplayer, such as MLB 16 at 450 % resolution, there is a 10% F.P.S. loss when adding one player, but no more after adding more players (probably a separate issue).
- The levels being loaded are in the same area, where each player can see the other player on each screen, so in theory, it shouldn't require more processing power to render more things. It should be the same number of things.
- This may be related to #10069 , in that maybe the split-screen code just needs to be updated.

| Game | 1 Player & Log | 2+ Player(s) & Log |
| ------------- | ------------- | ------------- |
| Motorstorm Apocalypse | ![Capture125dxfh](https://user-images.githubusercontent.com/11889359/116944471-8f2fe880-ac43-11eb-8a8b-dc07f16d535f.PNG) [RPCS3 Motorstorm 1 Player.log](https://github.com/RPCS3/rpcs3/files/6418408/RPCS3.Motorstorm.1.Player.log) | ![Captur124efzafswa21](https://user-images.githubusercontent.com/11889359/116944480-9525c980-ac43-11eb-95c9-427b6797f02c.PNG) [RPCS3 Motorstorm 2 Player.log](https://github.com/RPCS3/rpcs3/files/6418413/RPCS3.Motorstorm.2.Player.log) |
| Call of Duty: Modern Warfare 3 | ![Capture1677](https://user-images.githubusercontent.com/11889359/116944495-9ce56e00-ac43-11eb-9751-6d1e30d793ef.PNG) [RPCS3 Call of Duty 1 Player.log](https://github.com/RPCS3/rpcs3/files/6418464/RPCS3.Call.of.Duty.1.Player.log) | ![Capture7178](https://user-images.githubusercontent.com/11889359/116944506-a1118b80-ac43-11eb-814b-25f26027a8c2.PNG) [RPCS3 Call of Duty 2 Player.log](https://github.com/RPCS3/rpcs3/files/6418466/RPCS3.Call.of.Duty.2.Player.log) |
| Tom Clancy's Rainbow Six Vegas 2 | ![Capture16](https://user-images.githubusercontent.com/11889359/116944610-d0c09380-ac43-11eb-9d86-dec347d531a1.PNG) [RPCS3 Rainbow Six 1 Player.log](https://github.com/RPCS3/rpcs3/files/6418491/RPCS3.Rainbow.Six.1.Player.log) | ![Capture17677](https://user-images.githubusercontent.com/11889359/116944619-d4ecb100-ac43-11eb-936d-08064fbdb856.PNG) [RPCS3 Rainbow Six 2 Player.log](https://github.com/RPCS3/rpcs3/files/6418492/RPCS3.Rainbow.Six.2.Player.log) |

#### 5. Please provide your system configuration:
* OS - Windows 10, Latest Version
* CPU - AMD Ryzen 9
* GPU - RTX 2080 Super, Latest Version

#### Other details
* I was only able to notice this because of Megamouse's recent work, #10173. Thanks Megamouse and everyone else. :)
Tell me if I have mispoken.

**Comment by RainbowCookie32** [comment]
This just sounds as performance being lower because the game has more stuff to do, not a specific issue by itself.

**Comment by dio-gh** [comment]
> The levels being loaded are in the same area, where each player can see the other player on each screen, so in theory, it shouldn't require more processing power to render more things. It should be the same number of things.

Each player sees a different perspective of the game world. Depending on how the rendering is done by the games, split-screen absolutely can incur a massive performance hit.

**Comment by Asinin3** [comment]
`maybe the split-screen code just needs to be updated.`
This isn't how emulation works. We're emulating the way the game implemented its split screen functionality. You can see the exact same performance issues on a real console when you play games in split screen.

**Comment by AniLeo** [comment]
Closing since there seems to be no bug, just an expected performance drop from the game having to render itself twice
On console, you can get decent performance, but you already know how very demanding scenarios work on RPCS3

**Comment by jeremybris** [comment]
> Each player sees a different perspective of the game world. Depending on how the rendering is done by the games, split-screen absolutely can incur a massive performance hit.

Good point. I forgot about perspective. I've tried to make the perspectives as close to identical as possible in the examples I've given.

>This isn't how emulation works. We're emulating the way the game implemented its split screen functionality. You can see the exact same performance issues on a real console when you play games in split screen.

@Asinin3 @AniLeo I did not know that first part, but your third sentence is not true. I've played Motorstorm Apocalypse on the PS3, and this is not what happens. The game runs at 30 frames per second on PS3 in singleplayer, and when switched to 4 player, it does not lose 15 frames per seconds. It maintains 30 frames per second, showcased in these videos: https://www.youtube.com/results?search_query=motorstorm+apocalypse+4+player . Sorry, I should have included a comparison with the PS3 in the original description; _something is being rendered more times than it should_. But I understand if you want to keep this closed.

**Comment by RainbowCookie32** [comment]
> I've tried to make the perspectives as close to identical as possible in the examples I've given.
Even if you do the game likely still renders the game twice, at least for the most part. Once per player POV.

> something is being rendered more times than it should.
RPCS3 drops framerate when the PS3 doesn't. That doesn't necessarily mean that stuff is being rendered more times than needed. RPCS3 doesn't have a splitscreen rendering path or something like that. The game runs its own rendering code, which the emu translates and executes. 
There are a multitude of games that don't have performance issues on a PS3 but do on RPCS3, and we don't have issues open for those either in general. This is not a specific problem, it's just a general performance drop caused by the game having more stuff to draw on screen.

**Comment by jeremybris** [comment]
@ rainbow Literally, the issue right before mine is about performance (# 10235) lol. Performance issues are reported. This is not a general problem. It is a specific problem. It specifically happens when split-creen is activated.

**Comment by RainbowCookie32** [comment]
That issue is a pretty specific condition, where performance degrades considerably after leaving the game running on a specific area. See draw call setup time massively increasing with time (~2900us -> ~42000us), so there's clearly a bug somewhere.

This is *not* a specific issue, it's just RPCS3's performance not being good enough to handle rendering a scene twice.

**Comment by Asinin3** [comment]
`I've played Motorstorm Apocalypse on the PS3, and this is not what happens.`
Not what I meant. Yes, real consoles may not have dipped in frames as much in split screen, or at all. But they still met a more hardware intensive situation that lowered the performance/available performance.

Anyway, this issue is rather pointless as it serves no purpose other than saying "performance bad pls fix". If an issue can't provide something specific for a developer to investigate then their may as well be no issue as of course performance improvements are on the list of things to do.

**Comment by jeremybris** [comment]
There are two conjectures here, and they don't have to be in opposition:

| I believe I understand your conjecture now, that, for example, Motorstorm runs faster on the PS3, and is capped at 30 F.P.S., and that's why you don't see the performance dip. | I have supplemented this issue, my conjecture, with: reproducible steps, comparison to PS3, multiple games, and logs. To me, it's not "performance bad pls fix". It's "identifiable bug present, please fix". |
| ------ | ------ |

Thanks for trying to clarify anyway. Hopefully, rainbow is right, we need faster computers or faster emulation. But as is, we have more powerful computers than a PS3 right now, and I believe the game is running faster or equal to than it did on PS3 in singleplayer, at 40 F.P.S., 720p.

![Comparison](https://user-images.githubusercontent.com/11889359/117085157-06827c80-ad17-11eb-84ff-3ab8b50b606e.png)
