### ISSUE TITLE
RPCS3 crashes at startup (win 8.1+)

### ISSUE THREAD

**Issue by ddscentral** [RPCS3/rpcs3#10243]
RPCS3 crashes at startup.

Error message:
Verification failed
(In file rpcs3\util\vm_native.cpp:336 [:3], in function shm) (e=0x00000001[1])
Thread Id = <number>

I suspect this could be related to the most recent commit, but I'm not absolutely sure.
Tried both building from source and downloading the prebuilt version from rpcs3.net, same error.

![rpcs3_crash](https://user-images.githubusercontent.com/26443023/117197716-d5767a80-adf0-11eb-9756-a97259fd6a22.png)

System specs (in case it's system dependent):
OS: Windows 10 x64
CPU: AMD Ryzen 9 5950X
GPU: Nvidia RTX 3090
GPU driver version: 465.89

**Comment by Nekotekina** [comment]
You say the most recent commit, but did you actually test two latest versions? Thanks.

**Comment by ddscentral** [comment]
It was a suspicion at first but I can confirm that hard-resetting Git tree to the previous commit (546b52200b7c0d00edbc22d55a7b4bb1b9497f94) and rebuilding fixes the startup issue on my Ryzen system.

Tested the latest version on a different system with an Intel CPU and Nvidia GPU and it does run fine. Not sure if this issue CPU specific though as that system has different driver and OS versions.

**Comment by Nekotekina** [comment]
It may be related to your OS configuration. What filesystems are in use? Where Windows is installed and what temp path it uses?

**Comment by ddscentral** [comment]
Good point. My configuration is indeed a bit unusual.

My local drives are all formatted as NTFS, except for the TEMP which is on small RAM disk formatted as FAT32 (I don't want temporary files to pile up). It seems the latest update does not like that as changing the TEMP variable to a path on an NTFS drive fixes the issue. Perhaps it has something to do with those sparse files.

Since my RAM disk software does not allow me to choose a file system (always uses FAT32), I've added a small script at startup to convert the RAM disk to NTFS.

Even though this won't likely be a problem for the vast majority of users, it would still be worthwhile to note somewhere in the docs that the %TEMP% directory has to be on an NTFS drive. Unless you can workaround the issue somehow to avoid errors at startup.

Problem fixed.

BTW, a bit off-topic but what's the reason for using those sparse files ?

**Comment by Nekotekina** [comment]
It's a trick to obtain overcommit memory support by mapping sparse file in memory (which doesn't occupy disk space) and combine it with copy-on-write mode (which doesn't write anything back on the disk). I'm still experimenting with it.

**Comment by Teriand** [comment]
Same crash after on 12218 build, 12213 work fine.

```
---------------------------
RPCS3: Fatal Error
---------------------------

			<p style="white-space: nowrap;">
				<p>Unhandled Win32 exception 0xC0000005.<br>
Segfault writing location 0000000000000000 at 000007fefcf7c4d2.<br>
Thread: Main Thread.<br>
Instruction address: 000007fefcf7c4d2.<br>
Function address: 000007fefcf7c410 (base+0xc410).<br>
Module name: 'KERNELBASE.dll'.<br>
Module base: 000007fefcf70000.<br>
RPCS3 image base: 0000000000010000.</p>
<p>Thread id = 3648.</p><br>
				HOW TO REPORT ERRORS:<br>
				<a href='https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support'>https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support</a><br>
				Please, don't send incorrect reports. Thanks for understanding.<br>
			</p>
			
---------------------------
OK   
---------------------------
```

OS win7
All NTFS disk
I am using symlinks to another didks:
![image](https://user-images.githubusercontent.com/26705069/117569959-c1709880-b0d0-11eb-8652-c65e13ad8609.png)

But rename 3 folder dont help.
what other information can help?

**Comment by Nekotekina** [comment]
I'm not sure, need someone with backstack from VS

**Comment by Nekotekina** [comment]
Please test #10261

**Comment by Linblow** [comment]
Same error as @Teriand
It throws the same 0xC0000005 exception on startup, under windows 7 pro x64.
v0.0.15 works fine

**Comment by Nekotekina** [comment]
Please don't post win7 errors here. Chances are it will never be fixed.
