### ISSUE TITLE
[Feature Request] Rename default username in UI

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#10242]
The current default username "User" cannot be edited in the RPCS3 UI under "Manage > User Accounts" as the option to rename is unselectable.  Instead, `~/config/rpcs3/dev_hdd0/home/000000001/localusername` must be manually edited.  Being able to do so within the UI would be easier and more intuitive.

Note that the UI permits creation of a second account where the username can be renamed.

**Comment by Megamouse** [comment]
You can rename the first one, but it is only possible if it's not the active user

**Comment by Shoegzer** [comment]
Thanks @Megamouse, I assume you mean to create a second user, log in to that account (thereby activating it) and then renaming the first (deactivated) user.  If so, what inhibits changing the name of the active account, is it a limitation in the way RPCS3 manages accounts or something imposed by the PS3 itself?
