### ISSUE TITLE
Clarify GPL license type

### ISSUE THREAD

**Issue by ilian** [RPCS3/rpcs3#10255]
Could you clarify if RPCS3 is licensed under GPL-2.0-only, or GPL-2.0-or-later? This info is required in order for me to package RPCS3 on NixOS.
You can find more info about this clarification on the [GNU website](https://www.gnu.org/licenses/identify-licenses-clearly.html).

**Comment by HerrHulaHoop** [comment]
The project is licensed under GPL-2.0-only but some files differ by specifying different license headers.

**Comment by Megamouse** [comment]
Maybe mention that in readme.md

**Comment by Megamouse** [comment]
I see. It's already mentioned.
But i would also like to see a definitive license instead of that vague mention

**Comment by HerrHulaHoop** [comment]
Add `-only` after GPLv2 in the README in your next PR. 
The rest of the wording is apt and sufficient IMO.

**Comment by AniLeo** [comment]
By the way, tags are not stables, so you might want to package the latest version as of now instead of an old one
