### ISSUE TITLE
Metal Gear Solid HD Collection BLUS30847 - Infinite Loading Screen/Black Screen

### ISSUE THREAD

**Issue by JonesTheMantis** [RPCS3/rpcs3#10256]
Starting Metal Gear Solid 3 in the HD Collection only ends in a black screen which goes on indefinitely

Starting the game using the compatible settings given in the wiki takes me to the game select screen as normally.
But booting up Snake Eater will only lead to the 'Metal Gear HD Collection' logo to blink a few times in the bottom right of the screen (loading) and then the screen just goes complete black and nothing happens.

My system specifications are:
Windows 10 Version 20H2
Intel i5 8400
NVidia GTX 1060 with Driver 466.27
32GB DDR4 RAM

Sorry for my bad English, if you need any other information, I can provide.

I have viewed a lot of threads on this exact issue but none have worked for me so far.
Thanks in advance.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6446169/RPCS3.log)

**Comment by AniLeo** [comment]
Log file shows your dump is corrupted
