### ISSUE TITLE
Regression: Fatal error after update from the build v0.0.16-12217

### ISSUE THREAD

**Issue by toshph** [RPCS3/rpcs3#10260]
The RPCS3 doesn't start after updating to the latest version. It runs on rpcs3-v0.0.16-12217. It fails to run on rpcs3-v0.0.16-12218 and newer versions with the following error:
`Verification failed
(in file D:\a\1\s\rpcs3\util\vm_native.cpp:336[:3] in function shm) (e=0x00000001[1])
Thread id = 10300`
The screenshot:
![rpcs](https://user-images.githubusercontent.com/76447336/117571612-f6ccb480-b0d7-11eb-9db2-80448608d936.PNG)

I've tried a clean install. It doesn't help.

It doesn't create a log for the new version.
This is the log of the build v0.0.16-12217 (a clean install):
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6447456/RPCS3.log.gz)

The system configuration:
* Windows 8.1 x64
* Intel i7 4770K
* Geforce 1050TI
* Driver version 466.27

**Comment by Nekotekina** [comment]
Please test #10261

**Comment by Nekotekina** [comment]
Actually a dublicate.

**Comment by jokoputera** [comment]
Newest version (0.0.16-12237) have the same crash D:\a\1\s\rpcs3\ with Vulkan file. Ill send the sceeenschot later

**Comment by toshph** [comment]
Now it starts without problems (0.0.16-12237).
