### ISSUE TITLE
Top Spin 4 [NPEB00830] Crashes after latest RPCS3 update

### ISSUE THREAD

**Issue by ysarkain** [RPCS3/rpcs3#10263]
## Quick summary

Top Spin 4 now crashes with a fatal error when going from intro video -> ingame

## Details

I was testing out Top Spin 4 last night with no issues, played for about 90 minutes with no problems.  Did not save the logfile.
I had run the updater yesterday afternoon so I was on that day's version.

This morning I started RPCS3 up again, ran the updater, but when I tried to play Top Spin 4, it shows a fatal error in the console and the game hangs.  This occurs either when you hit a button to skip the intro scene, or if you let the intro play through.

**·F 0:00:31.576377 {RSX [0x00590c0]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderTargets.cpp:313[:3], in function get_surface)**

All settings were left untouched.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
* Please see [How to find the build that caused a regression](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression.3F) in our wiki.
* You can find [History of RPCS3 builds](https://rpcs3.net/compatibility?b) here.

Broken version:  RPCS3 v0.0.16-12235-a4f4b81e Alpha | HEAD

Working version: RPCS3 v0.0.16-12226 or 12227, did not keep that log file.

#### 2. Please attach TWO logs:
* One for the build with regression.
* One for the build that works as expected.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6448172/RPCS3.log)

#### 6. Please provide your system configuration:
* OS - Windows 10 (20H2)
* CPU - i9-10900KF
* GPU - Nvidia Geforce RTX 2080 FE
* Driver version - Up to date - 466.27

**Comment by ysarkain** [comment]
Works fine after rolling back to RPCS3 v0.0.16-12231-31b55e00 Alpha | HEAD

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6448220/RPCS3.log.gz)

**Comment by jokoputera** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/59791277/117771528-68376f00-b260-11eb-87c5-fda4137011c0.png)
here, it says : D:\a\1\s\rpcs3\emu\rsx\vk\vkrenderpass.cpp:83[:25], in function **get_renderpass_key**

should i open a new thread or this one is the same?
