### ISSUE TITLE
Verification failed, vm.cpp

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [RPCS3/rpcs3#10275]
## Quick summary
Running a game fails with this error, subsequent to which the emulator crashes altogether:

![image](https://user-images.githubusercontent.com/30529572/118112228-58579080-b402-11eb-8920-bf60f176ee5b.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6471820/RPCS3.log)

* OS: windows 10
* CPU: intel i7 8750H
* GPU: Nvidia GTX 1050 Ti

**Comment by MSuih** [comment]
@Nekotekina can you look into this? We're getting a lot reports about it after  #10272 was merged

**Comment by Gael2433** [comment]
Heres a my log to add onto the pile.
[_RPCS3.log](https://github.com/RPCS3/rpcs3/files/6471904/_RPCS3.log)

**Comment by L04DB4L4NC3R** [comment]
> @Nekotekina can you look into this? We're getting a lot reports about it after  #10272 was merged

I can confirm this. I downloaded the emulator and it was working fine. This bug started showing up when I updated it.

**Comment by jeff3779** [comment]
same here, can't launch a game
![rpcs3 bug](https://user-images.githubusercontent.com/55166658/118117934-7f0acc80-b3ec-11eb-977d-8a32f31da1a7.jpg)

**Comment by jeff3779** [comment]
sry the log 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6472081/RPCS3.log)

**Comment by Nekotekina** [comment]
It should be fixed, just need a confirmation from PR #10276

**Comment by Asinin3** [comment]
Just use edit function rather than double-posting.
But anyway, neko released a Pull Request to fix this: https://github.com/RPCS3/rpcs3/pull/10276 
Download from: https://api.cirrus-ci.com/v1/artifact/task/4858601031335936/Artifact/rpcs3-v0.0.16-2a26bc66_win64.7z

**Comment by Asinin3** [comment]
@Nekotekina Fixed issue on my machine.

**Comment by L04DB4L4NC3R** [comment]
Issue is fixed on my machine too. Thanks!
