### ISSUE TITLE
Rock Band 3 Song Loading Bug

### ISSUE THREAD

**Issue by ryantaylor24** [RPCS3/rpcs3#10277]
## Quick summary
Rock Band 3 Songs will momentarily buffer on the song select page, before finally passing through after a couple of seconds of loading and giving an error in the log. 

In the final update that worked, the song select screen showed various titles that it recommends you can purchase from the PS store. However, in the next update the songs are no longer there, probably because it's not able to connect. Somehow the game can't load it's disc songs properly without having that connection. Graphical settings have no impact on this error, as far as I'm aware. 

Regressed build is #9258 https://github.com/RPCS3/rpcs3/pull/9258, it was last working on Pull #9255 https://github.com/RPCS3/rpcs3/pull/9255

![image](https://user-images.githubusercontent.com/45437492/118119255-1572ca00-b3bc-11eb-9159-fdbfa89f1e40.png)
here is the working build, with the song American Pie showing

![image](https://user-images.githubusercontent.com/45437492/118119404-523ec100-b3bc-11eb-8d28-0f4f59c092ee.png)
And here is the regressed build, with the song American Pie and others missing. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6472131/RPCS3.log.gz) <- Working Build

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6472153/RPCS3.log) <- Regressed Build

Special Settings
- Write Color Buffers is required for various textures to properly load. 

- OS: Windows 10
- CPU: Ryzen 5 3600
- GPU: RTX 2060 Super

-

**Comment by RipleyTom** [comment]
Set Network status to connected?

**Comment by Megamouse** [comment]
closing as the user has their settrings set to "disconnected" and the builds before the regression seem to have been disregarding the connection state.
