### ISSUE TITLE
fios cache makes desync  according to language u use in TLOU

### ISSUE THREAD

**Issue by Tarek2013** [RPCS3/rpcs3#10293]
I found that when use use french language in the last of us, the voices are desync in some area (here Bidonville eg)
But,when u select other language (english,italian,spanish,...) all works perfectly
I saw that the TTY show 'threads fios error cell' but it could also come from firmware detection (almost of texts in alerts like saves or internet stay in english when region console is in europe with fr language).
[RPCS3(french).log.gz](https://github.com/RPCS3/rpcs3/files/6494549/RPCS3.french.log.gz)
[RPCS3(english).log.gz](https://github.com/RPCS3/rpcs3/files/6494550/RPCS3.english.log.gz)
[RPCS3(Italian).log.gz](https://github.com/RPCS3/rpcs3/files/6494551/RPCS3.Italian.log.gz)
I'm using the last rpcs3 version with lastest nvidia drivers (windows 10,GTX 1080 32go ram and SSD samsung)

**Comment by Megamouse** [comment]
Maybe the game desyncs audio in french on ps3 too 🧐

**Comment by Tarek2013** [comment]
You're right
Effectively, french audio has issue on PS3 too..
