### ISSUE TITLE
I have a problem running a game

### ISSUE THREAD

**Issue by juan20348** [RPCS3/rpcs3#10295]
When I try to run a game its give me an error

F SIG: Thread terminated due to fatal error: Unknown context dma 0x0
(in file D:\a\1\s\rpcs3\Emu\RSX\gcm_enums.cpp:1176[:22], in function to_context_dma) (e=0x0000007e[126])

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6496846/RPCS3.log)

**Comment by RainbowCookie32** [comment]
Unsupported hardware way below minimum requirements, there's no fix. Use [our discord server](https://discord.me/RPCS3) for support, not the issue tracker.

**Comment by AniLeo** [comment]
Since hardware is below minimum requirements don't ask for support before you upgrade your PC, there's nothing to do with that one.
