### ISSUE TITLE
Regression: Persona 5 - Black and blue screens prevent me from seeing the game properly (#10299)

### ISSUE THREAD

**Issue by WalkinOnBeats** [RPCS3/rpcs3#10301]
## Quick summary
I updated RPCS3 a few hours ago, and every time I open up Persona 5, there is a black loading screen. Then when I enter the game, the screen turns blue and I can't see anything. So far, this is the only changes I've noticed.

## Details

**1. Please attach RPCS3's log.**
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6503348/RPCS3.log)

**3. Please attach screenshots of your problem.**
![image](https://user-images.githubusercontent.com/84406252/118702170-9548cc00-b7e2-11eb-9856-095c24548114.png)
![image](https://user-images.githubusercontent.com/84406252/118702188-9b3ead00-b7e2-11eb-9fa8-b7f165c959b8.png)

**5. Please provide your system configuration:**
* OS: Windows 10 Enterprise
* CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
* GPU: Intel(R) UHD Graphics 620
* Driver version: 27.20.100.8337

#### Please include.
* Anything else you deem to be important
Here are my current settings:
![image](https://user-images.githubusercontent.com/84406252/118704662-6122da80-b7e5-11eb-9f5d-10a68d91fd29.png)
![image](https://user-images.githubusercontent.com/84406252/118704715-6c760600-b7e5-11eb-927b-3469fd3ba280.png)

**Comment by RainbowCookie32** [comment]
Regression was introduced on #10299

**Comment by Nekotekina** [comment]
Waiting for LLVM build, discarding the latest commit for now.

**Comment by Nekotekina** [comment]
I think it's fixed, sorry about this. LLVM is a scary beast to tame.
