### ISSUE TITLE
SSAO bug with resolution scaling in NaughtyDog games

### ISSUE THREAD

**Issue by Linear524** [RPCS3/rpcs3#10316]
**Any** version if RPCS3 on **any** hardware shows some SSAO scaling bug in Last of Us. It looks like black half-transparent lines on any geometry if resolution scaling is used above native 720p. But - there is some funny part of this issue = if you will set resolution scaling to 4K - this bug will disappear and overall image will looks just as intended. So this bug doesn't appear if you use native resolution or scaling 300% (4K). Otherwise - 4K mode not playable because of massive slowdown and unstable backend behavior due to overload...

I think there is some error in scaling coefficients for SSAO function and it can be fixed without heavy surgery in RSX emulation.
![screenshot-2021_05_19_22_59_51](https://user-images.githubusercontent.com/84367301/119090097-fc59c100-ba2c-11eb-9716-63a85fedc653.jpg)
![screenshot-2021_05_19_22_59_06](https://user-images.githubusercontent.com/84367301/119090107-fe238480-ba2c-11eb-99ad-9133c4112da0.jpg)

**Comment by Linear524** [comment]
P.S. - I know that there is a special patch for removing SSAO from TLoU, but I don't like to disable important features in games, and I think accurate emulation of all RSX features are more important for RPCS3, rather than temporary speed gain with improper rendered graphics output...

**Comment by kd-11** [comment]
Try 1440p (2x scaling)
If it works with integer scaling modes its likely because dividing some values with fractions does not work cleanly.

**Comment by Linear524** [comment]
Tried 2x and every possible combination - only native and 4K works correctly :P
P.S. - on real PS3 hardware 720p looks pretty good because its overall picture is antialiased by MLAA... But current RPCS3 condition have some error of reproducing correct MLAA in TLoU and everything looks horrible in 720p. Is there any chance of fixing this MLAA for TLoU ?
(every other game I tested have correct working MLAA on RPCS3, even Uncharted series)

**Comment by maz-1** [comment]
Same thing happens with uncharted 2 & 3


> Tried 2x and every possible combination - only native and 4K works correctly :P
> P.S. - on real PS3 hardware 720p looks pretty good because its overall picture is antialiased by MLAA... But current RPCS3 condition have some error of reproducing correct MLAA in TLoU and everything looks horrible in 720p. Is there any chance of fixing this MLAA for TLoU ?
> (every other game I tested have correct working MLAA on RPCS3, even Uncharted series)

Try to install reshade and enable fxaa/smaa (or vkbasalt under linux). I get really good anti-aliazing with vkbasalt.

**Comment by Xcedf** [comment]
SSAO in TLoU actually important, it generates some data that required for blizzard-fog effect during winter levels, prevents it from crashing.

**Comment by Linear524** [comment]
A bit unrelated, but I've discovered an interesting thing with latest builds:
Usually I using combination of WCB + RCB for TLoU, because it helps to render some tricky effects like cone lights with flies or distant objects shading... But recently I tried to add Write Depth Buffers + Read Depth Buffers activated and suddenly - it is not slowed down overall gameplay, but actually adds some 1~2 fps ! Also current combination of WCB+RCB+WDB+RDB helps to render some mirror images with correct geometry and produces correct data for DoF effect !
So now, moving further, if we use that combination and NOT using MLAA-disabling patch, (only GPU-path patch is needed, and nothing more in whole patch list), = we will get a lot of disabled effects working ! Overall, it produces:
- Correct Depth of Field effects (while aiming + static DoF for distant objects) are works 100% now !
- Color and Gamma correction is now working !
- Film grain layer is now working (MLAA-disabling patch ruined it before)
- Dynamic exposure is now working correctly !
- Some specular shade effects now works correctly on blood splatters and characters eyes with motion effects.
- Sun GodRays effect now works partially (half-left section OK, but half-right section is broken due to lack of precision in xfloat function. Accurate xfloat option fixes this, but it brakes other function :P)
The only things which is still broken in TLoU on RPCS3 is:
- MLAA doesn't work (broken shader translation or layer)
- Volumetric lighting with Godrays is still broken (no vector input data for rendering pipeline)
- Torch light shadowmaps is broken (#9588)
- Some lens dirt layers are missing. (looks like depth bug problems/z-buffer)

So if someone interested in emulation TLoU with more correctly rendered graphics, try this settings:
| CPU settings at default but without Idle loop detection.
| GPU settings with activated WCB+RCB+WDB+RDB on Vulkan API and Native resolution. Framelimit and Antialiasing = Auto
Use FSR with 50% sharpening in order to compensate Native resolution scaling to bigger screen size.
| Advanced and Debug settings are at Defaults too. (Accurate RSX reservation is needed if TSX is disabled)
| Patches - disable all patches, except GPU path patch. Only this one is needed.

I know it will slow down emulation speed, but it will give more PS3 effects back to life :)
Accuracy is more important right now than speed optimization.

**Comment by Xcedf** [comment]
@Linear524, confirm, that's a major progress actually, now WCB+RCB+WDB+RDB are able to handle depth effects even with Depth behind Alpha (Depth viewport) and even with Motion Blur, I remember on older builds that wasn't possible.

**Comment by Linear524** [comment]
Hi Xcedf !
Sure, here is the screenshots of Sun's volumetric lighting and Xfloat issue:
![screenshot-2021_08_16_22_08_17](https://user-images.githubusercontent.com/84367301/129656508-b05f9f38-e879-4122-82c2-4cd17011928a.jpg)
![screenshot-2021_08_16_22_08_29](https://user-images.githubusercontent.com/84367301/129656517-30352366-10f4-4c3d-9f8f-89ff4aaf8026.jpg)
![Accurate-Xfloat-4](https://user-images.githubusercontent.com/84367301/129656528-6f447803-9d0f-400a-bbdb-05e7a45aa007.jpg)
![Accurate-Xfloat-2](https://user-images.githubusercontent.com/84367301/129656545-1d565d52-8639-4f27-8733-9a9bdbe4dc4c.jpg)
![Accurate-Xfloat-1](https://user-images.githubusercontent.com/84367301/129656558-351c4e5f-9f39-442e-94bc-e2dd5a7a616c.jpg)
![Accurate-Xfloat-5](https://user-images.githubusercontent.com/84367301/129656566-2a4686b6-f7c7-4691-8016-fd4480364c6a.jpg)

**Comment by Linear524** [comment]
And here is original screenshots:
[Xfloat.zip](https://github.com/RPCS3/rpcs3/files/6996723/Xfloat.zip)

**Comment by Xcedf** [comment]
@Linear524 did you try Resolution Scale Threshold for SSAO scale, for example Bloom's are 160x160, perhaps some will work for SSAO

**Comment by Xcedf** [comment]
@Linear524 Ok found that godrays require SPU FCEQ instrution to be accurate, you can use Illusion's build to activate it separately without the rest of Xfloat, and avoid major slowdown and artefacts.

**Comment by Linear524** [comment]
**@Xcedf**  Thanks !
Is it possible to merge #8729 to master build ? 
(I don't know where to get latest illusion builds :P )
And about SSAO scaling - I don't use any IR scaling functions anymore. Even if we will find suitable resolution scale threshold for SSAO = it will break lens flares and other important things. Actually, I have my own crazy theory about scaling in PS3 games:
- if all RSX function will be emulated correctly, to run all shaders properly, all effects and layers, and all antialiasing modes (MLAA, multisampling, EdgeAA, etc...) - it will produce correctly rendered image output in native 720p, just what original hardware does and what exactly game developers built in their code... Then we will be able to simply scale final image with FSR function and it will be the best image quality from PS3 rendered game. What I mean here is just one simple thing - native 720p is really enough if all functions works correctly. Internal resolution scaling will always break something more or less, and oversharpening image with high resolution not always a good choice = some details should be blurred and not crisp. That's how PS3 devs make their initial design to use limited hardware power in the right way... Other important reason to not use IR scaling = some games uses mesh trimming and scaled image will have a lot of empty pixel holes unless dedicated patch will be written... 
- I've played MGS3, Shadow of the Colossus, ICO, Killzone2, GoW3 from start to finish in Native 720p and without any patches, and it looks really nice because MLAA works fine in these games and overall picture stretches fine to 1080p (and now we have FSR postprocess scaling, awesome !)
-
So now I think it is better to wait until RSX depth issues, precision issues and shader bugs will be fixed, and then play TLoU in native 720p with all special effects and FSR scaling (^_^)

**Comment by Xcedf** [comment]
If you want to try here's Illusion build with https://github.com/RPCS3/rpcs3/pull/8729 included
https://mega.nz/file/aFpinIhY#L7DwAGMwdkjIssyU9Sev5XNYJvlq1PSF7K2VZH8UYP4
Also resolution scaling no longer breaks lens flares, kd fixed it long ago.

**Comment by Linear524** [comment]
@Xcedf  Thanks !
Will try that build tonight.
By the way, do you have any idea how to fix floating grass bushes in Uncharted series ? It looks like a vertex shader translation bug, but it affects Naughty Dog's games in this weird way. Maybe some SPU instruction need more precise calculation ? (like FCEQ)

**Comment by Xcedf** [comment]
@Linear524 tried all possible accurate  options, nothing seems to affect floating grass in Uncharted.

**Comment by mjd180** [comment]
The discussion in this pull request is all over the map! Can we please stick with the original, titled issue (which, btw, I can't replicate), & save the rest for the forums? If this has been fixed, it should be closed.

**Comment by Asinin3** [comment]
Rename issue to indicated Uncharted games also affected

**Comment by Linear524** [comment]
Well... A lot of things were changed since I've created this issue ticket. And now we have nice FSR upscaling which is greatly helps with "720p-only" games ! So I'm closing this issue because 720p is really enough for any PS3 game with combination of 16x anisotropic filtering + properly emulated antialiasing (MSAA or MLAA) and with FSR upscaling applied...
The only thing needed to be fixed up in TLoU is:
- Broken Torch Light Shadow maps.
- Broken MLAA shader.
- Missing or screwed depth layers with lense dirt flares.

**Comment by joaocandre** [comment]
From what I understand, this should be fixed for current upstream versions, but it's happening to me on Uncharted 2.

**Comment by mjd180** [comment]
> From what I understand, this should be fixed for current upstream versions, but it's happening to me on Uncharted 2.

Same with ‘Uncharted 3, unless you use the disable SSAO patch.

**Comment by mjd180** [comment]
> Well... A lot of things were changed since I've created this issue ticket. And now we have nice FSR upscaling which is greatly helps with "720p-only" games ! So I'm closing this issue because 720p is really enough for any PS3 game with combination of 16x anisotropic filtering + properly emulated antialiasing (MSAA or MLAA) and with FSR upscaling applied... The only thing needed to be fixed up in TLoU is:
> 
> * Broken Torch Light Shadow maps.
> * Broken MLAA shader.
> * Missing or screwed depth layers with lense dirt flares.

This issue should never have been closed. And certainly not with the above reason.
