### ISSUE TITLE
Regression: TOKYO JUNGLE NPEA00275 from 12070 to 12292

### ISSUE THREAD

**Issue by Bandabydoo** [RPCS3/rpcs3#10314]
The main error I've been getting and I've seen around a couple of places is 
"F VM: Access violation reading location 0xed154224 (unmapped memory) [type=u32]"
They say to disable "Accurate LLVM DFMA" or use a different SPU Decoder both of which I've tried on latest build to no avail game will not boot. 
I saw someone suggest builds older and yeah it functions enough to get into game without the requirement of tweaking any settings. 

Specs in DxDiag and Logs for each build I tried

[DxDiag.txt](https://github.com/RPCS3/rpcs3/files/6519179/DxDiag.txt)
[Tokyo Jungle Broken 0.0.16.log](https://github.com/RPCS3/rpcs3/files/6519180/Tokyo.Jungle.Broken.0.0.16.log)
[Tokyo Jungle Working  0.0.15.log](https://github.com/RPCS3/rpcs3/files/6519181/Tokyo.Jungle.Working.0.0.15.log)

**Comment by RainbowCookie32** [comment]
Missing the build that actually introduced the regression. There are a lot of builds on the range you mentioned on the title
