### ISSUE TITLE
RPCS3: no games work - crashes Windows 7 64 AMD-chipset Nvidia Graphics 16gb Ram

### ISSUE THREAD

**Issue by hjjr78** [RPCS3/rpcs3#10327]
HP Desktop Tower (small form factor)
Windows 7 64 bit Home
AMD chipset with virtualization
3.0 ghz Quadcore (4 threads)
16 gigs of RAM
Nvidia Geforce GT 1030

Heavenly Sword:
     Game modules were processed; game starts up but crashes after the first text appears on screen.
     UPDATE: game made it to title screen but crashes.
[Logs.zip](https://github.com/RPCS3/rpcs3/files/6526641/Logs.zip)

Castlevania Lords of Shadow 2:
     Game modules were processed (emulator crash occured at end of process); game does not start and crashes emulator on 
     start up.

Both of these games are labled as "Playable" but yet they do not play.
I've also noticed extremely high CPU usage while game modules are being processed for the first time (raises cpu temps!).

I've tried the the vulkan setting and opengl settings.  I actually get a little further with opengl but always end in emulator crashing and closing.

**Comment by Megamouse** [comment]
Your CPU is almost as old as the PS3.
How do you expect to run any game on this emulator :)

**Comment by Megamouse** [comment]
You pirated the games anyway.

**Comment by Zangetsu38** [comment]
Is gameboy cpu 😅

**Comment by hjjr78** [comment]
I won't be running any emulator games but I can run all other commercial
games at max graphics and rps.  Rpcs3 is poorly optimized.  It requires 8
to 16 cores to even begin to push it.  Do you know how much $$ 8 to 16
cores in a cup will cost...  A lot and given the fact the PS3 did not even
cost 1k when it 1st came out, it was not built with that kind of money.
Consoles are meant to play back games...they are not who Pass like Windows
so why in the hell does Rpcs3 needs so many resources just to play back a
game...?

Don't bother replying, I deleted the emulator.  Better of getting the
console.

**Comment by AniLeo** [comment]
Locked, spare us from the cringe
