### ISSUE TITLE
cmake errors

### ISSUE THREAD

**Issue by DocMAX** [RPCS3/rpcs3#10321]
can't build anymore:
```
game /usr/src/github/rpcs3/build # cmake ..
-- No build type selected, default to Release
-- Did not find googletest, tests will not be built. To enable tests place googletest in '<spirv-dir>/external/googletest'.
CMake Error at CMakeLists.txt:64 (add_subdirectory):
  The source directory

    /usr/src/github/rpcs3/3rdparty

  does not contain a CMakeLists.txt file.


-- Initializing RPCS3_SRC_DIR=/usr/src/github/rpcs3/rpcs3
CMake Error at rpcs3/CMakeLists.txt:42 (include):
  include could not find requested file:

    /usr/src/github/rpcs3/3rdparty/qt5.cmake


-- RPCS3_GIT_VERSION: 12297-dcfd29c2
-- RPCS3_GIT_BRANCH: master
-- RPCS3_GIT_FULL_BRANCH: local_build
-- Configuring incomplete, errors occurred!
See also "/usr/src/github/rpcs3/build/CMakeFiles/CMakeOutput.log".
See also "/usr/src/github/rpcs3/build/CMakeFiles/CMakeError.log".

```

**Comment by AniLeo** [comment]
You're not building correctly, follow BUILDING.md and ask for support on one of our community platforms if you need help

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
