### ISSUE TITLE
rpcs3_vm file issue

### ISSUE THREAD

**Issue by 2580660019** [RPCS3/rpcs3#10325]
I found a file in C:\Users\user_name\AppData\Local\Temp named rpcs3_vm file, it appears 33GB lager, but my cleanner tool could detect it every time after rpcs3 runs, could it be fixed, quite annoying!

**Comment by b1acksnow** [comment]
issue on this problem https://github.com/RPCS3/rpcs3/issues/10312
I think it's already fixed in https://github.com/RPCS3/rpcs3/pull/10319

**Comment by Nekotekina** [comment]
It's a sparse file, it occupies 0 bytes (unless you are on win 7). But maybe your cleaner tool could possibly be blind to that fact.

**Comment by 2580660019** [comment]
oh thx, and I deleted rpcs3_vm multiple times, it will not affect any functions of rpcs3 right?

**Comment by MSuih** [comment]
The file itself isn't used for anything and nothing is written to it. Deleting it is fine.

**Comment by 2580660019** [comment]
> The file itself isn't used for anything and nothing is written to it. Deleting it is fine.

thx so much！

**Comment by MonfGeiger** [comment]
getting this vm file too. in folder, shows as 32 GB, but checking its properties tab, shows as 0 bytes on disk.

running windows 10 pro 64 bit, got 16 GB of ram, and im running RPCS3 Version: 0.0.16-12301-309759b7 Alpha

**Comment by Nekotekina** [comment]
And what's the problem? It's supposed to be like this.
