### ISSUE TITLE
Removing game icon from list after deleting its data

### ISSUE THREAD

**Issue by Krishster** [RPCS3/rpcs3#10338]
I may be wrong, but i saw that after installing folder games, when we delete all its data the game icon still exist and shows in the UI list.

I know that hiding the game from list will do the changes. But i noticed if we rename the main game folders, the game icon is disappear automatically.

Then if possible make some options in the UI, so that instead of hiding, we can remove the game icon after deleting all its data.

Thanks.

**Comment by Megamouse** [comment]
- What is a "Folder game" ?
- Which game icon? Did you add a custom icon?

A game is only displayed if a game was found.
If you delete anything without using the GUI then you have to click the refresh button.
If the game is still displayed, then it must still be existing somewhere. Right click the game on the list and select "Show location"

**Comment by Krishster** [comment]
1. Games other than .pkg files consist of folder. The game boots after selecting folder.
2. I have not added any custom icon rather UI shows after booting a game from folder.

After deleting game cache and data in UI, icon still shows. But if we rename main game folder, its icon disappear from UI list.

**Comment by Megamouse** [comment]
Did you try what I wrote?

**Comment by Megamouse** [comment]
You didn't follow the issue template.
We need to know what platform you are on and how you deleted the game.

**Comment by Krishster** [comment]
I am using Windows 10 pro version.
Here are some screen shots regarding the problems i want to share.
1. Game icon showing in the list.
![Screenshot_1](https://user-images.githubusercontent.com/64323517/119823396-646b4400-bf12-11eb-80e5-611cf29a0729.jpg)
2. I am removing all caches and data. But icon still shows in list.
![Screenshot_2](https://user-images.githubusercontent.com/64323517/119823439-764ce700-bf12-11eb-9eb1-7d24eabf427d.jpg)
3. Main game in folder.
![Screenshot_3](https://user-images.githubusercontent.com/64323517/119823523-9086c500-bf12-11eb-88af-319201133776.jpg)
4. I am renaming main folder.
![Screenshot_5](https://user-images.githubusercontent.com/64323517/119823599-aac0a300-bf12-11eb-8008-f6ee27be3ab0.jpg)
5. After renaming, icon disappears. No need for hiding.
![Screenshot_6](https://user-images.githubusercontent.com/64323517/119823779-d2b00680-bf12-11eb-9df9-e0dfaf3f3fcc.jpg)

there should be an option in RPCS3 GUI for removing game icons instead of hiding.

**Comment by Krishster** [comment]
Even deleting data from RPCS3>Icons or RPCS3>dev_hdd does not remove icons. I think it may be actually linked with the main game folder and when we rename folder, its path changed, thus RPCS3 lost its link with folder and game icon disappear.

**Comment by RainbowCookie32** [comment]
I don't see the problem here.

RPCS3 adds the game to the list after you boot it and stores its path in games.yml, which is why it disappears when you rename it. Removing all caches won't make it disappear from there because, well, you are removing the caches, not the game.

What's being shown there is the game you booted, messing with files in the Icons or dev_hdd0 folders won't make a difference.

**Comment by Krishster** [comment]
well is not it possible to modify games.yml so that game icons may be deleted in the GUI ?
