### ISSUE TITLE
[Feature Request] Add more Launch Command options

### ISSUE THREAD

**Issue by CuddleBear92** [RPCS3/rpcs3#10332]
## Quick summary
Add more Launch Command options like open game in fullscreen, exit when game closes and set gamepad preset/type

## Details

Having more Launch commands would be useful for a bunch of use-cases, but prob mainly Streaming options like SteamLink, Moonlight, Nvidia Game Stream and so on.
Allowing for launch commands enables easier usage with such services by allowing users to make shortcuts for different uses. 
It could allow users to say open the game in fullscreen, close the client with the game and set the controller type to xinput for full SteamLink support.
Users might not want to manually change global or per-game settings every time they play it at the desktop or on the couch, launch commands would enable this without the need of more configs.

For example with Steam and its SteamLink, over the AppleTV/iOS app it gives the host client an xinput signal no matter what type of controller you are using, they would want to force such a controller config for those shortcuts.
Launching in fullscreen and exiting with close ofc makes sense for ease of use. 

Currently we only have --no-gui as far as im aware which is great, but a few more options would be neat.

**Comment by Blackbird88** [comment]
--fullscreen could reuse the code of the **Automatically start games at boot** option I think. Surprised it wasn't done already.
