### ISSUE TITLE
Fight Night Round 4 [BLUS30285] AI stops working mid fight - PPU LLVM

### ISSUE THREAD

**Issue by Mookie19** [RPCS3/rpcs3#10339]
## Quick summary
During any fight, randomly the AI fighter will stop attacking; in addition to this your character cannot lean anymore either. Which is how I quickly tell.

## Details
As described above. 

Settings for this post were completely RPCS3 defaults, including resolution (no scaling).
When testing I cleared all caches prior aswell. Switching to PPU: Fast fixes the issue, with obvious framerate issues present. Changing the SPU does nothing for the problem.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6540542/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
N/A

#### 5. Please provide your system configuration:
* OS Win 10 Rev.19041
* CPU Ryzen 5 3600X
* GPU RTX 2070 Super
* Driver version 466.47
* RPCS3 installed on SSD

#### Please include.
if I forgot anything, just ask I will update.

*side note, I've seen this issue present from forums dating back to march of 2018, so I don't think its a 'regression'.

**Comment by Asinin3** [comment]
You made the issue so you have the ability to close it with the big red close button. But, I'll close it for you.
