### ISSUE TITLE
RPCS3 fails to build on flathub

### ISSUE THREAD

**Issue by Lctrs** [RPCS3/rpcs3#10343]
## Quick summary
RPCS3 fails to build on flathub since 3 days

## Details
You can see the log of one of the failing build here : https://flathub.org/builds/#/builders/19/builds/5783

Faulty commit is one of 2491aad6f2caa5cd1138e244021d28564c3b11f9, 4b239a0b878bb9c3e992b90771191921737e202a, or 2768727e2fecbeb501968ca2cb1dcafd3658653b.

**Comment by MSuih** [comment]
Seems like https://github.com/RPCS3/rpcs3/commit/2491aad6f2caa5cd1138e244021d28564c3b11f9 removed limits.h include from wrong file.

**Comment by Lctrs** [comment]
Yep. With the patch below, it builds fine : 

```
diff --git a/rpcs3/Emu/RSX/Overlays/overlay_controls.h b/rpcs3/Emu/RSX/Overlays/overlay_controls.h
index 7102e0eb6..99521601a 100644
--- a/rpcs3/Emu/RSX/Overlays/overlay_controls.h
+++ b/rpcs3/Emu/RSX/Overlays/overlay_controls.h
@@ -20,6 +20,7 @@
 #include <sys/types.h>
 #include <pwd.h>
 #include <libgen.h>
+#include <limits.h>
 #endif
 
 #ifdef __APPLE__
```

https://flathub.org/builds/#/builders/35/builds/5809/steps/6/logs/stdio
