### ISSUE TITLE
DualShock 3 - Pressure sensitive buttons and SixAxis

### ISSUE THREAD

**Issue by Blackbird88** [RPCS3/rpcs3#1034]
Now I understand this isn't priority, because no games using this stuff are working yet, but I'd like to mention them with some info.

http://forums.pcsx2.net/Thread-XInput-Wrapper-for-DS3-and-Play-com-USB-Dual-DS2-Controller
With the DS3 XInput Wrapper and custom **XInput1_3.dll** it includes you can use both those features just like real PS3 does.
Source is included AFAIK.

PCSX2 already supports the buttons with custom Lilypad plugin called **LilyPad-Scp-r5875.dll** included in **Win32** folder of the wrapper.

Silent from GTAForums also managed to make both features work in GTA series using the DLL as well.
http://gtaforums.com/topic/562765-iiivcsaasi-ginput/

As a bonus here is SixAxis working in GTA San Andreas PC version
https://www.youtube.com/watch?v=KYOogVJKIeo

**Comment by tambry** [comment]
Once we get games running that use this, it will probably be interesting to implement it. But right now it probably isn't priority and is rather a long-term goal.

**Comment by Blackbird88** [comment]
Yeah I understand that man. It's literally in the first paragraph, but I just wanted to let you know there is no need to do it the hard way when this exists ;)

**Comment by mirhl** [comment]
Just for the records, [this](http://gtaforums.com/topic/562765-iiivcsaasi-ginput/?p=1066552403) is the post with the actual juicy stuff

**Comment by raven02** [comment]
Supported by https://github.com/RPCS3/rpcs3/pull/2733

**Comment by Blackbird88** [comment]
I don't see any mention of DS3. DS4 doesn't have pressure sensitive buttons.

**Comment by mirh** [comment]
I'm not sure who's your linux man of trust (Nekotekina I think?)
But you may want to ping him with this https://bugzilla.kernel.org/show_bug.cgi?id=195643

**Comment by osirase** [comment]
Damn, this would be very useful. I was just testing Ragdoll Kung Fu (Awesome local friend couch gameplay) and it's missing a lot of functionality without sixaxis support. I only have DS3's. I'm using ScpToolkit and xinput works, but no sixaxis support. Don't games like MGS4 need sixaxis love? Would be lovely to see this support added at some point. Can't wait to play Ragdoll Kung Fu again with my friends.

**Comment by dreaddymck** [comment]
Do you have a tutorial is can use to get my sixaxis usb to work?
Got this far: https://raw.githubusercontent.com/dreaddymck/ubuntu-notes/master/.config_linuxjoystick.yml

Stuck on the right analog.

**Comment by JMC47** [comment]
Now that the Metal Gear Solid HD Collection is in-game and working fairly well all things considered, the lack of support for pressure sensitivity face buttons pretty noticeable.  You can't easily hold-up guards without firing because you have to slowly release the button Snake/Raiden to lower his weapon without firing. I also know some racing games can use the pressure sensitive face buttons for feathering the gas if you choose the classic control style instead of using triggers.  The only way to realistically do this would be to interface with a DS3 though.

I know this probably isn't all that useful to add, but, having some test cases for it will be nice when it is attempted.

**Comment by vassilmladenov** [comment]
@JMC47 an alternative could be to have a game-specific fix in the emulator. From what I understand, the Xbox 360 version of the HD collection had slightly modified controls because the 360 controller’s buttons were not pressure sensitive.

**Comment by suyash691** [comment]
Are there any plans to have fireshock support (https://github.com/ViGEm/FireShock)? It is pretty stable and has support for pressure sensitive keys

**Comment by mirh** [comment]
Yes, whatever nefarius will come up with in the future is possibly/likely/hopefully "the good thing".
But for the moment there's no real competitor feature, stability and compatibility wise to SCP original driver.

**Comment by suyash691** [comment]
Feature-wise fireshock has more features (as in more dualshock functionalities are available), the drivers have been working on my PC for the past 3 weeks ( have been using the ds3 as my daily driver).
However without nefarius's assistance I do not see this being added to RPCS3 (he had to maintain a separate lilypad plugin which supports fireshock and the entire ds3 suite)

**Comment by nefarius** [comment]
Everything FireShock related on github is outdated, a complete rewrite is in development including exposing pressure data without the need for hacks like in SCP times. I'm using PCSX2 for a reference implementation.

**Comment by nefarius** [comment]
It might look at times that I don't make any progress or might have even abandoned working on a true SCP successor. This is far from the truth. It's just really hard to keep everybody updated through so many communication channels and at the same time go full throttle on driver development with the *very* small team we still are.

**Comment by Arturbc** [comment]
Is too hard add simulated version of 6 axis?

I have in my mind use mouse on emulator's window, left button and drag simule x and y drag/shake and right button simule rotation axis.

This is helpful in games that this features is required like Heavy Rain.

Thanks.

**Comment by SnakeSosa** [comment]
Wanted to try out the emulator for first time and finish Locoroco Cocoreccho which i never got to but it basically uses nothing but sixaxis.
I am using chronus max and my ps3 controller so its just xinput. 
Does anyone know of a workaround or any updates on implementation of sixaxis?
Thanks and amazing work with all ye have accomplished already!!

**Comment by hmuk09** [comment]
As I understand, #5641 solved this issue. Shouldn't it be closed?

**Comment by mirh** [comment]
That's definitively nice and dandy (also cutely similar to the [first method ever](https://www.engadget.com/2006/12/07/use-your-sixaxis-on-windows-sony-hearts-microsoft-after-all/))
The fact is though, it seems windows-only, you cannot use bluetooth and that, you know, it'd prevent you from using the controller anywhere else. 

I'm not expecting Benjamin to fix the first issue (:see_no_evil:), but there's definitively quite much still to do.

**Comment by MSuih** [comment]
After #5888 the Dualshock 3 handler should work on linux as well.

**Comment by HerrHulaHoop** [comment]
Just to add, DS3 works on Linux using both USB and Bluetooth. However, on Windows it only works using USB.

**Comment by CookiePLMonster** [comment]
ScpToolkit is still usable though, isn't it? Since native DualShock 3 support requires a specific driver, supporting SCP API extensions may still be viable.

**Comment by HerrHulaHoop** [comment]
ScpToolkit is an XInput wrapper right? Just use the XInput pad handler and it should work without any issues.

**Comment by CookiePLMonster** [comment]
It is, of course, and it indeed works flawlessly. However, ScpToolkit also
comes with a (optional) replacement xinput1_3.dll you can place in the
application directory, which exposes one additional documented function to
obtain pressure sensitive button data from the gamepad.

Thus, even though it's XInput ideally I'd like to see it supported as a
separate option in RPCS3 controls config. It could also be managed by
XInput option but that'd make the implementation needlessly complex IMO.

**Comment by Megamouse** [comment]
Wouldn't placing this dll in the rpcs3 dir force rpcs3 to use it anyway? (Not rhetorical)

**Comment by RipleyTom** [comment]
Official sony ds3 drivers support sixaxis & pad pressure buttons which are supported by our ds3 pad handler. If you use steam it also lets you use that driver to play xinput games and is a lot better than scp(which uses a service, requires extra communication between processes which adds latency).

**Comment by CookiePLMonster** [comment]
> Wouldn't placing this dll in the rpcs3 dir force rpcs3 to use it anyway? (Not rhetorical)

Yes, that's the idea, but you also need to make use of an additional function not exported by stock XInput. Else it won't poll pressure sensitive data.

Although actually RPCS3 will **not** load this DLL, since it is loading them only from system32. For this use case, it would have to be changed.

**Comment by mirh** [comment]
> Official sony ds3 drivers support sixaxis & pad pressure buttons which are supported by our ds3 pad handler.

You mean the famous PS3SDK/PSNow drivers? TIL 
> If you use steam it also lets you use that driver to play xinput games and is a lot better than scp

It's still is kind of a hack though, isn't it? And I'm not sure how steam would be supposed to be lighter or nicer than a plain daemon. 
Anyway, in other news @nefarius should be almost maybe perhaps in the process of finally releasing his ***definitive*** DS3 driver. Bluetooth, usb, and I think also extensions eventually. 
Maybe if you are a RPCS3 team member (or a cookie-eating gamehack star) you can get fast tracked into the beta.

**Comment by nefarius** [comment]
Just approach me if you need anything, I'm currently just so booked with tasks and all over the place I tend to forget/drop topics unintentionally if not reminded.

**Comment by RipleyTom** [comment]
I've personally lost all interest in supporting windows so if you want to implement nef/scp support feel free to do so.

**Comment by CookiePLMonster** [comment]
I intend to look into this, but right now I prioritized looking into other weird things going on in XInput backend (potentially broken dirty state for vibration) etc.
