### ISSUE TITLE
Armored core 5 

### ISSUE THREAD

**Issue by dulsan** [RPCS3/rpcs3#10360]
## Quick summary
When the mech goes into a lit area or anywhere for that matter, the screen gets a bunch of flickering boxes which does not go away and leads to the game eventually crashing. 

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6558234/RPCS3.log.gz)

#### 3. Screen shots:
![image](https://user-images.githubusercontent.com/13959909/119931146-2dee0180-bfc4-11eb-83ac-58a5a666a616.png)

* OS: windows 10
* CPU: Intel i7 9700
* GPU: Nvidia 1660ti
* Driver version: 466.47

**Comment by YuriNator557** [comment]
Graphical issues require a RenderDoc and RSX capture. Can you please post these?

**Comment by dulsan** [comment]
I now sure on how to create a renderDoc but, I do have an RSX capture:

[BLUS30516 RSXcapture.zip](https://github.com/RPCS3/rpcs3/files/6603379/BLUS30516.RSXcapture.zip)

**Comment by dulsan** [comment]
Strange thing is, this problem goes away when write color buffers is turned on but, the game still crashes if I complete a mission. When the game crashes it shows:
F VM: Access violation writing location 0x0 (unmapped memory) [type=u32]

**Comment by ScottNash042** [comment]
update or close ???

**Comment by Megamouse** [comment]
closing due to inactivirty
