### ISSUE TITLE
Loading a saved game in some games freezes the emulation (starting with 0.0.16-12330)

### ISSUE THREAD

**Issue by PeterTh** [RPCS3/rpcs3#10363]
## Quick summary
The title is a quick summary.

## Details
In Tales of Graces F [BLUS30903], loading a save freezes the game starting with this particular version. To be precise, it freezes immediately after selecting a save game on the save selection screen, before showing the confirmation prompt. 
It's 100% reproducible.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.16-12330 // pull request #10357

#### 2. Please attach TWO logs:
* One for the build with regression: [RPCS3_REGRESSION.log](https://github.com/RPCS3/rpcs3/files/6563217/RPCS3_REGRESSION.log)
* One for the build that works as expected: [RPCS3_OK.log](https://github.com/RPCS3/rpcs3/files/6563227/RPCS3_OK.log)

#### 6. Please provide your system configuration:
* OS Windows 10 20H2
* CPU Intel 9900k
* GPU Geforce RTX 3090

**Comment by Megamouse** [comment]
possibly fixed with #10367

**Comment by Nekotekina** [comment]
Fixed for me, although I can't tell for all games.

**Comment by Megamouse** [comment]
The bug should appear in all native user interface instances where user interaction was needed, when the user closes the dialog (by any means).
This includes save data dialogs, user selection dialogs, osk dialogs and all message dialogs that let you press ok or cancel.

**Comment by Megamouse** [comment]
Please reopen if the issue persists
