### ISSUE TITLE
The last of us: unexpected glow when aiming a thrown item

### ISSUE THREAD

**Issue by askinghyena** [RPCS3/rpcs3#10364]
## Quick summary
when using the bow, or any other throwable item in TLOU, the end of the aim line is covered by a large glowing blob. the glow seems to go away whenever aiming through a transparent object, making the aim line normal.

## Details

After some discussion on the help channel on discord, on 2021-05-27, kd-11 chipped in and gave his opinion. his words were: 
"As for the 'glow' thing, its an arithmetic clipping issue. The values get overblown due to some incorrect instructions somewhere and you get very large brightness values in small regions. The game's post-process then smears this crap values around and makes the region of effect even bigger than it should be."

#### 0. Make sure you're running with settings as close to default as possible
Custom config: 
  Accurate RSX reservation access: true
  PPU LLVM Java Mode Handling: true
  Frame limit: 60
  Shader Mode: Async with Shader Interpreter
  Write Color Buffers: true
  Read Color Buffers: true
  Driver Wake-Up Delay: 200
  Vblank Rate: 120
Audio:
  Enable Buffering: true
  Desired Audio Buffer Duration: 100
  Sampling Period Multiplier: 100
  Enable Time Stretching: true
  Time Stretching Threshold: 75

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://drive.google.com/file/d/1wDytqi8chdF6fXYLywpTLa8CbLDMO-tc/view?usp=sharing)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.

[BCUS98174_20210527185612_capture.rrc](https://drive.google.com/file/d/1R56FDWGbP-bRnOcOIeU_XU4imw6Rd7wU/view?usp=sharing)

unfortunately, I could not figure out how to get a renderdoc capture from the emulator. i've read the help page linked on this form and it was no help. please point me to an appropriate tutorial, or detailed instructions specific to RPCS3, if they exist.

#### 3. Please attach screenshots of your problem.
typically looks like this
![TLOU glow](https://user-images.githubusercontent.com/84941840/120049763-fe052500-bfe8-11eb-9ceb-f999d93f0c2a.PNG)

although in some low light environment, the glow doesnt appear. the end of the aiming line just seems rainbow colored without glow.
![TLOU no glow in low light](https://user-images.githubusercontent.com/84941840/120050203-9059f880-bfea-11eb-8c14-75e9a0d75300.PNG)

in some cases, aiming through other textures seems to remove the bug entirely.
![TLOU no glow through other textures](https://user-images.githubusercontent.com/84941840/120050143-4ec94d80-bfea-11eb-91e0-f919e7075da1.PNG)

#### 4. Please provide comparison with real PS3.
I don't have a PS3 anymore, it died a couple years ago. :(
here's a screenshot of what the aiming line should look like, taken from the internet.
![756553-the-last-of-us-left-behind-playstation-3-screenshot-throwing](https://user-images.githubusercontent.com/84941840/120049710-d31ad100-bfe8-11eb-819a-dfa6228902a9.png)

#### 5. Please provide your system configuration:
* WIN 10 pro N
* AMD ryzen 7 3800X
* GeForce GTX 970, driver version 27.21.14.5671
* B550M DS3H motherboard
* 2x8Gb 3600hz DDR4 RAM

#### Please include anything else you deem to be important.
i'm looking into this mostly because i'd like to run TLOU with MLAA enabled. i have a kinda capable CPU, and the low frames bother me less than not having access to "hearing mode". the only major graphical downside to this, is this aiming graphical issue. it makes aiming with the bow or a thrown item impossible. to me, it seems that with other patches applied, this is the only bug making this game bothersome to play with MLAA.

**Comment by Xcedf** [comment]
This issue is a result of a main issue - the broken models of aiming reticles, as you may notice for yourself, there's no glowing mess around the good looking parts of aiming reticles.

**Comment by askinghyena** [comment]
> 
> 
> This issue is a result of a main issue - the broken models of aiming reticles, as you may notice for yourself, there's no glowing mess around the good looking parts of aiming reticles.
I'm not sure i understand. why are the models broken on emulator, but not on original hardware? i don't remember anything like this when i played through the game on PS3.

**Comment by Xcedf** [comment]
Perhaps it's because PS3 and RPCS3 are two totally different things

**Comment by Yahfz** [comment]
> > This issue is a result of a main issue - the broken models of aiming reticles, as you may notice for yourself, there's no glowing mess around the good looking parts of aiming reticles.
> 
> I'm not sure i understand. why are the models broken on emulator, but not on original hardware? i don't remember anything like this when i played through the game on PS3.

did you really just ask why an emulator in alpha has issues that the original hardware don’t? lol

**Comment by Xcedf** [comment]
Just a guess, but it seems this some color correction issue
using Uncharted 3 for this
here's unpatched render
![14](https://user-images.githubusercontent.com/7060586/141526560-c6c6662b-c9ef-4f8d-a977-d249336c5ea0.jpg)
made a patch that disables this color correction, but line looks thicker
![13](https://user-images.githubusercontent.com/7060586/141526616-3f47a6d5-6994-433a-8a9e-517e84fe5236.jpg)
and here's the thing I guess causes the glowy mess
render from the console
![12](https://user-images.githubusercontent.com/7060586/141526812-eb99c944-2800-4e1c-afdb-eac7f5054622.jpg)

**Comment by Xcedf** [comment]
Fixed with https://github.com/RPCS3/rpcs3/pull/11151, please close.
