### ISSUE TITLE
AppImage fails to run, GLIBCXX_3.4.29 not found

### ISSUE THREAD

**Issue by mastercoy** [RPCS3/rpcs3#10378]
## Quick summary
Newer versions of the prebuilt app images fail to run on LTS distributions.

## Details
Expected: AppImage works
Reality: rpcs3: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by rpcs3)

 lsb_release -a
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```

**Comment by Mew8000** [comment]
G
