### ISSUE TITLE
Regression in RDR, FPS is too low.

### ISSUE THREAD

**Issue by moaalseiari** [RPCS3/rpcs3#10379]
## Quick summary
Please briefly describe what has stopped working correctly.
RDR FPS is too low for some reason.

[https://ibb.co/BK3wCp5](url)

https://ibb.co/BK3wCp5

## Details
Please describe the regression as accurately as possible.
Regression is hurting the gaming performance of my RPCS3, the fps is only 49.7 FPS at 300% Resolution Scaling.
Need mesa-git support and vulkan implementation for more performance.

#### 6. Please provide your system configuration:
* OS Arch Linux
* CPU Ryzen 9 5900x 
* GPU RX 6800 XT
* Driver version mesa-git (Open Source)
* etc.

#### Please include.
* Anything else you deem to be important

GG NO RE @Yahfz

**Comment by AniLeo** [comment]
No information, no build that regressed this, not even a comparison between current and previous.

**Comment by moaalseiari** [comment]
I will provide comparison upon request my lady.

**Comment by AniLeo** [comment]
Follow the regression template, we need the exact build that regressed what you're reporting. As it is, there's no issue on your ticket.

**Comment by moaalseiari** [comment]
> Follow the regression template, we need the exact build that regressed what you're reporting. As it is, there's no issue on your ticket.

Yes, but the FPS should be 60 FPS locked. I shall submit all the required documents at the earliest.

**Comment by AniLeo** [comment]
No, it shouldn't. Game's target is 30fps, anything above is extra. Either way, a regression is relative difference between two points in time, you've only provided one which doesn't show any regression.

**Comment by moaalseiari** [comment]
Ok you can completely remove this or close for no comments. I will issue a new ticket following the guidelines. 

Bu
