### ISSUE TITLE
Unreal Engine games are rendered in red when resolution scaling is applied

### ISSUE THREAD

**Issue by galano6** [RPCS3/rpcs3#10373]
## Quick summary
Some Unreal Engine games are rendered in red when resolution scaling is applied.

## Details
Running UE games with 300% (or anything above 100%) resolution upscale causes red screen glitch. At 100% resolution scaling the issue is gone. Everything apart the resolution scaling is on the default setting.

## RSX capture
[BLUS30565_20210529190014_capture.zip](https://github.com/RPCS3/rpcs3/files/6565044/BLUS30565_20210529190014_capture.zip)

## Screenshots
Shadows of the Damned™ [BLUS30653]
![0001](https://user-images.githubusercontent.com/71184221/120078633-a0d4a680-c0b0-11eb-92f0-746dadf05d53.jpg)

Silent Hill Downpour [BLUS30565]
![0002](https://user-images.githubusercontent.com/71184221/120078636-a500c400-c0b0-11eb-8cee-600fba38407e.jpg)

## System configuration:
RPCS3 0.0.16-12341-d81a5b14 Alpha
Windows 10 Pro
GTX 1070
Nvidia Driver 466.27.0.0
Ryzen 5900x

**Comment by RainbowCookie32** [comment]
Resolution scaling is a hack and doesn't work nicely with all games. We don't usually accept issues about it, unless it's a regression.

Pretty sure you can fix that by increasing scale threshold, 512x512 I think.

**Comment by MSuih** [comment]
Resolution scaling will never work with every single title as the games themselves were not meant to be rendered in these resolutions. It is not something that we can fix.

But as said you might be able to work around this with right settings. Ask in discord for help with emulator configuration.
