### ISSUE TITLE
Unimplemented syscall sys_game_get_system_sw_version

### ISSUE THREAD

**Issue by bengl3rt** [RPCS3/rpcs3#10376]
## Quick summary

Trying to run PS3Load, https://store.brewology.com/get/homebrew.php?id=42&fid=643

Seems it wants an FW version number, perhaps this can be extracted from the header of the FW image at FW install or runtime?

Last thing that happens before it exits:

U PPU TODO: Unimplemented syscall sys_game_get_system_sw_version -> CELL_OK (r3=0xd00feee8, r4=0xd00feee4, r5=0xd00feee0, r6=0xd00feedc, r7=0xd00feed8, r8=0x5a, r9=0xe9, r10=0x1400)

## Details

Full log output

E SIG: Failed to set thread affinity 0xff: error 1. x2
F SIG: Thread terminated due to fatal error: Segfault reading location 00000000000000e8 at 00007fcc2c9fefc4.
Emu Thread Name: 'Usb Manager Thread'.

F profiler: cpu_thread::flush_profilers() has been called incorrectly.
E SIG: Failed to set thread affinity 0xff: error 1. x2
- RSX: Found vulkan-compatible GPU: 'Intel(R) HD Graphics 630 (KBL GT2)' running on driver 20.2.6
- RSX: Found vulkan-compatible GPU: 'GeForce GTX 1060' running on driver 460.73.1.0
E RSX: Your GPU does not support depth bounds testing. Graphics may not work correctly.
S GUI: Boot successful.
S PPU: LLVM: Loaded module v4-kusa-J2yywnvyEk0007fasv7RPp-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-CAmFPSWeEMZipoLviUXSKW-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-8A2PMTA4SzNpEuq86RJ6M9-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-s2gsK5RujrGMYKXGxji6Lw-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-3yMb5CqchHA26CKKUEcYE8-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-nrPcbGsdVwAWcNSvCxpw3j-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-L2PQAvkfJSGU8HuMgPj85E-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-F7NhvGZbmdaav3bvLNp3n0-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-VVpch2zMaboEPoCvc501dt-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-8L2XXhHzKdM2GcM4n2wqii-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-JzeWEng62G75JsXVYp00mG-00000P-skylake.obj
S SPU: SPU Runtime: Built the interpreter.
E SIG: Failed to set thread affinity 0xff: error 1. x8
U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0100ce0)
S PPU: LLVM: Loaded module v4-kusa-1z3Pyu8YVnnorJiQ2hfu1e-00000P-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0100a50)
S PPU: LLVM: Loaded module v4-kusa-XCgQWMc1s99n1WTwrpWvw4-00000P-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S PPU: LLVM: Loaded module v4-kusa-GsbjiwC5Sm3exFcR5udHpE-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-gRWSbPdZHFQq5essKqQVjk-00000P-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0100df0)
E SYS: 'sys_fs_fstat' failed with 0x8001002a : CELL_EBADF [1]
S PPU: LLVM: Loaded module v4-kusa-t1xTtC1PVoW6Jh636RxJVQ-00000P-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-2wS6UCQGvL8KpqZwEg6HX7-00000P-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libnet.sprx” (id=0x23001c00)
S PPU: LLVM: Loaded module v4-kusa-fLV79QqHgPi90UziTsWrHo-00000P-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23001d00)
U sys_mutex TODO: sys_mutex_create(): unexpected adaptive (0x1000) x2
E SYS: 'sys_fs_fstat' failed with 0x8001002a : CELL_EBADF [1]
U sys_mutex TODO: sys_mutex_create(): unexpected adaptive (0x1000)
E SYS: 'sys_fs_fstat' failed with 0x8001002a : CELL_EBADF [1]
E SYS: 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [2]
U PPU TODO: Unimplemented syscall sys_game_get_system_sw_version -> CELL_OK (r3=0xd00feee8, r4=0xd00feee4, r5=0xd00feee0, r6=0xd00feedc, r7=0xd00feed8, r8=0x5a, r9=0xe9, r10=0x1400)
F SIG: Thread terminated due to fatal error: NV3089_IMAGE_IN_SIZE: unknown operation (0)
(in file /root/parts/rpcs3/src/rpcs3/Emu/RSX/rsx_methods.cpp:1062, in function image_in) (errno=11)

**Comment by brian218** [comment]
Solved by #12787 in Oct 11, 2022.
