### ISSUE TITLE
Disable glDepthBoundsEXT for Intel HD graphics

### ISSUE THREAD

**Issue by woody2014** [RPCS3/rpcs3#1038]
On my hd4600 instant crash.

**Comment by andre4688** [comment]
my hd4000 instant crash game all

**Comment by raven02** [comment]
Fix here - https://github.com/DHrpcs3/rpcs3/pull/1039

**Comment by woody2014** [comment]
Not crashing,only showing black screen except scrogger.

**Comment by raven02** [comment]
Yep , i tested few games , some games are black screen but some display okay .Probably some recent commit break it.

**Comment by raven02** [comment]
It should all working again now in RSX branch.

**Comment by woody2014** [comment]
can you upload a build to emunewz pls.

**Comment by tambry** [comment]
Closing because this is technically fixed.

**Comment by tambry** [comment]
Actually never mind, forgot it's on the RSX branch.

**Comment by tambry** [comment]
@woody2014 Is this fixed?

**Comment by Altaiar** [comment]
no

**Comment by Altaiar** [comment]
in latest build with write color buffers and read color buffers  show everything but somting is wrong in borders screen 
sry for my bad english

**Comment by raven02** [comment]
Tested on Intel HD and it should be no problem.Closed
