### ISSUE TITLE
Killzone 3

### ISSUE THREAD

**Issue by StalkerDolg** [RPCS3/rpcs3#10389]
Hello. I don’t know what the problem is with Killzone 3. I know the game hasn’t gotten into playable status yet. But nevertheless, I saw a lot of footage on YouTube, where the game worked well. I wanted to start the game for the test, but when I start the game I see only a black screen and colored inscriptions with an error in the log.
Is there a problem with my PC? Or what?
![Безымянный](https://user-images.githubusercontent.com/50276678/120303615-bc42ea00-c31a-11eb-8876-d353d1dfee47.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6575259/RPCS3.log)

**Comment by Asinin3** [comment]
Github isn't for support. Use our discord server's help channel. https://discord.me/rpcs3
