### ISSUE TITLE
Tales of Xillia [BLES01815] Graphics not showing correctly on latest versions of RPCS3

### ISSUE THREAD

**Issue by bajulador** [RPCS3/rpcs3#10385]
It also happens on Tales of Xillia 2 [BLUS31397];
Tested on 0.0.16-12351-a7d4da25 Alpha;

E SYS: 'sys_ppu_thread_detach' failed with 0x80010002 : CELL_EINVAL [1];
E SYS: 'cellSaveDataListAutoLoad' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1];
E SYS: 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [2];
E SYS: 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [3];
E SYS: 'sceNpDrmIsAvailable' failed with 0x80010006 : CELL_ENOENT [1];
E SYS: 'sceNpDrmIsAvailable' failed with 0x80010006 : CELL_ENOENT [2];
E SYS: 'sceNpDrmIsAvailable' failed with 0x80010006 : CELL_ENOENT [3].

![0002](https://user-images.githubusercontent.com/59267216/120252432-df0dc980-c25a-11eb-9648-ae0b13ff6015.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6572673/RPCS3.log)

**Comment by RainbowCookie32** [comment]
Missing the build that introduced the issue and the user's hardware.

**Comment by bajulador** [comment]
I don't really recall when that happened, but it was during last month. I'm sorry, I just checked the game today and was surprised by the results. My hardware:

Ryzen 3 2200g 3.5GHz
Radeon RX 570 4GB
16GB RAM 2400MHz

**Comment by RainbowCookie32** [comment]
Time to find the build then, as indicated by the issue template. See [this wiki article](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression.3F) for a guide on finding the build that introduced the issue.

**Comment by giraffehce** [comment]
> Time to find the build then, as indicated by the issue template. See [this wiki article](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression.3F) for a guide on finding the build that introduced the issue.

0.0.16-12349 is when it started. Previous builds don't have the text rendering issue.

**Comment by bajulador** [comment]
giraffehce is right, the build where the problem started is 0.0.16-12349 for sure

**Comment by RainbowCookie32** [comment]
That'd be #10380 that introduced the issue :thinking:

**Comment by Nekotekina** [comment]
I think I fixed it, please try the PR mentioned (https://github.com/RPCS3/rpcs3/pull/10392)

**Comment by Nekotekina** [comment]
Should be fixed, feel free to reopen if something occurs.

**Comment by bajulador** [comment]
Just wanted to add that both Tales games are now working. Thanks Nekotekina

![ToX1](https://user-images.githubusercontent.com/59267216/120392235-990e3f80-c306-11eb-813e-0e89985c332b.png)

![ToX2](https://user-images.githubusercontent.com/59267216/120392239-9ad80300-c306-11eb-803d-7cf5f47934ea.png)
