### ISSUE TITLE
[Feature Request] add tab allowed game updated for within rpcs3 

### ISSUE THREAD

**Issue by Mew8000** [RPCS3/rpcs3#10399]
## Quick summary
Add tab game game updates that click get game updates for rpcs3 

## Details

Please describe the feature as accurately as possible.
Thier tab call game updates thier download game updates games have in rpcs3 app so use it without go 3rd party software or apps like discord bot but for rpcs3 emulator it self

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
Effect way game updates do for rpcs3 app 

#### 2. Please tell us, why your feature is important to RPCS3.
Because people download game updates for rpcs3 emulator it self by 3rd party apps or websites.

#### 3. Please attach screenshots of the feature implemented in other projects.
Like bot work on discord 

#### 4. Please provide your system configuration:
* win 10
* ryzen 9 4900hs 
*rtx 2060 max q

**Comment by RainbowCookie32** [comment]
See #10083, it was already decided not to add this feature.
