### ISSUE TITLE
F VM: Access violation reading location 0x3f4d47e8 (unmapped memory) [type=u0]

### ISSUE THREAD

**Issue by zzzdn1** [RPCS3/rpcs3#10396]
## Quick summary
so, I play Dynasty Warriror Gundam Reborn [NPUB31531] and install all DLC, before using DLC it's working fine, but after installng, it's broken 

## log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6583921/RPCS3.log.gz)

## Evidence
the rpcs3 : https://youtu.be/nWDzTLCkREM
the game : https://youtu.be/cYz2AQCbC_U

## system configuration:
* OS : Windows
* CPU : Ryzen 5 4600
* GPU : Nvidia 1650ti
* RPCS3 version : RPCS3 v0.0.16-12361-6c44664c Alpha

**Comment by YuriNator557** [comment]
You are missing the license files for your DLC. Please read the wiki page relating to dumping PSN content to learn how to do this:
https://wiki.rpcs3.net/index.php?title=Help:Dumping_PlayStation_3_games#Dumping_PSN_games
