### ISSUE TITLE
Compilation failure regression regarding SPIRV from #10384

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#10390]
[output.txt](https://github.com/RPCS3/rpcs3/files/6577676/New.Text.Document.txt) using VS 16.11 preview 1

**Comment by Megamouse** [comment]
I had the same issue yesterday.
I assumed it was fixed since both cirrus and appveyor build fine

**Comment by Megamouse** [comment]
Maybe try removing cmakecaches ?
I can't test for a while

**Comment by elad335** [comment]
Did git clean -f -X seems ok.
