### ISSUE TITLE
Regression: Nurarihyon no Mago: Hyakki Ryouran Taisen [BLJM60255] no longer boots (#9227)

### ISSUE THREAD

**Issue by shinslash** [RPCS3/rpcs3#10395]
The game screen freeze at "Loading PPU Modules".
this game was broken by PR RPCN 0.3.5 #9227 https://github.com/RPCS3/rpcs3/pull/9227  it now prevents the game from booting
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6583600/RPCS3.log.gz)

**Comment by Mew8000** [comment]
Gg

**Comment by AniLeo** [comment]
> Function aborted: sceNpMatching2CreateContext
