### ISSUE TITLE
[Feature Request] Please Add DirectX 12 support

### ISSUE THREAD

**Issue by danprice142** [RPCS3/rpcs3#10394]
## Quick summary
Please briefly describe what feature you would like RPCS3 to have.

## Details

Please describe the feature as accurately as possible.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.

#### 4. Please provide your system configuration:
* OS
* CPU
* GPU
* Driver version
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by AniLeo** [comment]
We already have Vulkan, which is a superior API and also multi-platform. D3D12 support was dropped a long time ago.
