### ISSUE TITLE
Sonic Unleashed Crashing on Save Data Load

### ISSUE THREAD

**Issue by TheCommandoChicken** [RPCS3/rpcs3#10403]
Attempting to load a 100% save file results in the game freezing immediately after the "Don't close the game while it's saving" screen, this error is most recently logged:
_F VM: Access violation reading location 0xd2719014 (unmapped memory) [type=u32]_
The emulator crashes on restarting or stopping the game. This does not occur when loading data created by starting a new game.

Additionally, the menu may appear as a jumbled mess with overlapping UI elements all loaded in at once, though I was unable to reproduce this for a screenshot.

HARDWARE:
Radeon RX 570
Ryzen 7 2700X
16 GB DDR4 @ 3000MHz

Here's the complete log:
[log.txt](https://github.com/RPCS3/rpcs3/files/6600002/log.txt)

And here's my settings:
[config_BLUS30244.txt](https://github.com/RPCS3/rpcs3/files/6600023/config_BLUS30244.txt)

**Comment by AniLeo** [comment]
Issue doesn't follow the guidelines, but you're trying to load a non-decrypted save-file, thus why it crashes.
