### ISSUE TITLE
Bakugan Battle Brawlers upscaling bug

### ISSUE THREAD

**Issue by Mew8000** [RPCS3/rpcs3#10400]
Bakugan Battle Brawlers has a upscaling bug when higher res.

720p
![Screenshot (24)](https://user-images.githubusercontent.com/85289208/120689759-6ed99080-c472-11eb-802a-10e4188d4f4f.png)
1072p
![Screenshot (21)](https://user-images.githubusercontent.com/85289208/120689784-76009e80-c472-11eb-8221-4108cd56839d.png)
1080p
![Screenshot (22)](https://user-images.githubusercontent.com/85289208/120689804-7dc04300-c472-11eb-9bad-510b3d402017.png)
![Screenshot (23)](https://user-images.githubusercontent.com/85289208/120689818-8284f700-c472-11eb-8bf3-52ed39125a58.png)
720p log file
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6593424/RPCS3.log.gz)
1080p log file
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6593428/RPCS3.log.gz)

**Comment by Mew8000** [comment]
1080p has aa then 720p does and 1072p has glitch's.

**Comment by RainbowCookie32** [comment]
Resolution scaling is a hack, and not all games react nicely to it. We don't accept issues about games misbehaving above 100% scaling if they work fine at 100%.

**Comment by Mew8000** [comment]
1440p looks a litte batter 720p

**Comment by Mew8000** [comment]
Any bug game left game itself is playable

**Comment by Mew8000** [comment]
@RainbowCookie32 I see is aa bug in game looks aa problem ps3 ver did

**Comment by Toxin60009** [comment]
Also FSR does work in this game and yes have beat it just someone upload playable report to rpcs3 fourms at this point.

**Comment by Toxin60009** [comment]
Also FSR does work in this game and yes people have beat it just someone upload playable report to rpcs3 fourms at this point.
