### ISSUE TITLE
Resistance Fall Of Man VK_ERROR_OUT_OF_DEVICE_MEMORY

### ISSUE THREAD

**Issue by RinMaru** [RPCS3/rpcs3#10419]
## Quick summary
Ive been trying to play the resistance series at 150% Res Scale (1080p) and have noticed Vulkan eats up all 4GB of vram very quickly while Open GL never goes above 2.9GB in the same area.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6611854/RPCS3.log)

#### 5. Please provide your system configuration:
* Windows 10
* Ryzen 5 5600X
* RX 480 4GB
* 21.5.2
* 20GB DDR4 RAM

#### Please include.
*Vulkan also seems to crash at random before the max Vram is reached.

**Comment by kd-11** [comment]
See https://github.com/RPCS3/rpcs3/issues/9050
1. Disable MSAA. MSAA does not work with OpenGL so you get lower usage.
2. Vulkan has to be more careful with object lifetime management unlike OpenGL where the driver handles things for us.

If it does indeed fully crash with VK_ERROR_OUT_OF_DEVICE_MEMORY attach a log here. There is cleanup that kicks in at high VRAM usage (usually becomes aggressive at 90% utilization, so ~3.6GB or so) and this threshold is by design. I do not consider this a bug at the moment unless there is an observable side-effect directly caused by the VRAM utilization.

**Comment by RinMaru** [comment]
In the log it does say its attempting to free up resources but crashes the entire emu after that im not sure if this is the same error your talking about but heres another log
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6620415/RPCS3.zip)

**Comment by RinMaru** [comment]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6620471/RPCS3.zip)

heres a log with the bug you mentioned
VK_ERROR_OUT_OF_DEVICE_MEMORY

**Comment by kd-11** [comment]
Thanks, I'll take a look.

**Comment by Augusto7743** [comment]
Only to add information.
Here the game using more GPU power is TMNT Turtles in Time reshelled.
Have moments the GPU usage is 100 % and funny detail is in same machine testing UC2-GT6-KZ3 and some games the GPU usage is below of 80 %.
TMNT Turtles in Time reshelled cpu usage is less half amd fx raw power and has moments that the GPU goes to 100 % and game has FPS slowdowns being the only game that use totally the GPU thus not being possible configure any scale settings.
Another detail is has games with less graphic quality using much more VRAM than KZ2-UC1-UC2-GT6 and games.

**Comment by RinMaru** [comment]
> Only to add information.
> Here the game using more GPU power is TMNT Turtles in Time reshelled.
> Have moments the GPU usage is 100 % and funny detail is in same machine testing UC2-GT6-KZ3 and some games the GPU usage is below of 80 %.
> TMNT Turtles in Time reshelled cpu usage is less half amd fx raw power and has moments that the GPU goes to 100 % and game has FPS slowdowns being the only game that use totally the GPU thus not being possible configure any scale settings.
> Another detail is has games with less graphic quality using much more VRAM than KZ2-UC1-UC2-GT6 and games.

Im guessing your gonna need to post a log of these games crashing otherwise its not much info

**Comment by Augusto7743** [comment]
Thanks for your reply.
My post not was about games crashing , but to say that some games with less graphics quality are using much more the GPU and VRAM than the games with best graphics.
Enabling or disabling MSAA is the same result.
Not demading fix. Only sharing information to devs.
Perhaps has really something in graphics renderer doing useless work and using VRAM more than the needs.
I may configure to use an high scale value to some games , but TMNT Turtles in Time reshelled not is possible use scale if not the game will run very slow and using much VRAM even using less half in each CPU core.
I not known a game using the GPU more than TMNT Turtles in Time reshelled even seeing performance in GT6, UC2, KZ2 and others.

**Comment by kd-11** [comment]
Seems to be a thing with insomniac PS3 engine. I was able to reproduce this with Rachet & Clank: A crack in Time. Even at 720p with MSAA (this engine needs MSAA to avoid garish visuals when dynamic resolution scaling is active) it easily reaches 4GB memory usage after 20 minutes.

**Comment by RinMaru** [comment]
> Seems to be a thing with insomniac PS3 engine. I was able to reproduce this with Rachet & Clank: A crack in Time. Even at 720p with MSAA (this engine needs MSAA to avoid garish visuals when dynamic resolution scaling is active) it easily reaches 4GB memory usage after 20 minutes.

well that narrows it down at least. only game that hasn't crashed on me is Tools of Destruction

**Comment by kd-11** [comment]
1080p + MSAA should not crash anymore on 4G cards. Retest and update.

**Comment by RinMaru** [comment]
seems to be fixed thank you ^^
