### ISSUE TITLE
Input: Discuss a new design for input profiles.

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#10410]
Use case: Guitar Hero games can have bands of up to 1 Mic + 1 Guitar + 1 Drums + 1 Bass

Currently you can only change the Device Class for all players, changing device on one player changes it for all players, so you can't have Player 1 as Guitar and Player 2 as Drums, for example.

**Comment by Megamouse** [comment]
You are probably not using different profiles.
Someone else made this mistake in discord recently as well.

It's kinda confusing how profiles work.

**Comment by AniLeo** [comment]
What if profiles become default per player? So "Player 1 Default" and so on

Right now, it's very weird from an UI perspective

**Comment by Megamouse** [comment]
You would have to come up with a design spec.
I'm not a profile user, nor do I run different pad configurations.

Changing the topic to discussion.

**Comment by slyponto** [comment]
just want to reiterate that pr 12637 made all my beloved input profiles good as nothing.

**Comment by AniLeo** [comment]
Of course, that's the point of redesigning the profile system. You need to create them again.
