### ISSUE TITLE
error: use of undeclared identifier 'err'

### ISSUE THREAD

**Issue by devilmac** [RPCS3/rpcs3#1041]
Hi DHrpcs3 team,

at this link http://pastebin.com/tvYggfEw you can find an error occurred during the compilation of this project.
I'm using a Mac to compile __rpcs3__

thanks for your support.

**Comment by zecoxao** [comment]
well, i just replace err with 0 or any other integer since it gets that in u64 format. but it's not the most clean solution

**Comment by MoochMcGee** [comment]
Replace it with errno and include errno.h.

**Comment by tambry** [comment]
@devilmac Has this been fixed by the latest commit?

**Comment by devilmac** [comment]
@tambry Sorry, I had no time to test it.
