### ISSUE TITLE
God Of War HD  infinite loading screens

### ISSUE THREAD

**Issue by snowboundmage2** [RPCS3/rpcs3#10425]
God Of War® HD [NPUA80490]

Randomly, some loading screens will be stuck loading. The loading logo still pulses colours, but the loading never ends.

[RPCS3.log gow1 infinite loading screen opengl.gz](https://github.com/RPCS3/rpcs3/files/6619178/RPCS3.log.gow1.infinite.loading.screen.opengl.gz)
[RPCS3.log gow1 infinite loading screen.gz](https://github.com/RPCS3/rpcs3/files/6619179/RPCS3.log.gow1.infinite.loading.screen.gz)
[RPCS3.log gow1 infinite loading on save menu same place.gz](https://github.com/RPCS3/rpcs3/files/6619180/RPCS3.log.gow1.infinite.loading.on.save.menu.same.place.gz)
[RPCS3.log gow1 infinite loading on vulcan.gz](https://github.com/RPCS3/rpcs3/files/6619181/RPCS3.log.gow1.infinite.loading.on.vulcan.gz)
[RPCS3.log gow1 infinite loading screen 2.gz](https://github.com/RPCS3/rpcs3/files/6619182/RPCS3.log.gow1.infinite.loading.screen.2.gz)
[RPCS3.log gow1 infinite loading screen opengl (2).gz](https://github.com/RPCS3/rpcs3/files/6619183/RPCS3.log.gow1.infinite.loading.screen.opengl.2.gz)
[RPCS3.log gow1 infinite loading screen opengl 3 didnt even get in game.gz](https://github.com/RPCS3/rpcs3/files/6619184/RPCS3.log.gow1.infinite.loading.screen.opengl.3.didnt.even.get.in.game.gz)
[RPCS3.log gow1 minotaur boss fight bug.gz](https://github.com/RPCS3/rpcs3/files/6619185/RPCS3.log.gow1.minotaur.boss.fight.bug.gz)
[RPCS3.log post minotaur boss fight crash.gz](https://github.com/RPCS3/rpcs3/files/6619186/RPCS3.log.post.minotaur.boss.fight.crash.gz)
[RPCS3.log.gz gow1 opengl infinite loading.gz](https://github.com/RPCS3/rpcs3/files/6619187/RPCS3.log.gz.gow1.opengl.infinite.loading.gz)
[RPCS3 gow1 infinite loading screen.log](https://github.com/RPCS3/rpcs3/files/6619188/RPCS3.gow1.infinite.loading.screen.log)
[RPCS3 gow1 infiniteloading post ares.log](https://github.com/RPCS3/rpcs3/files/6619189/RPCS3.gow1.infiniteloading.post.ares.log)

Windows 10
Intel Core i7 7700K @ 4.20GHz
32.0GB RAM
3071MB NVIDIA GeForce GTX 1080 Ti
Latest Drivers

**Comment by RainbowCookie32** [comment]
Test if disabling TSX changes anything, same for #10420

**Comment by snowboundmage2** [comment]
Dont' mean to be too optimistic, but I just went through the full intro in one straight go. I think that fixed both my issues.
Ill reopen the issues if need be
