### ISSUE TITLE
[Feature Request] Trophy pop-up sound

### ISSUE THREAD

**Issue by Kilowog01** [RPCS3/rpcs3#10427]
I would like to hear sound in the trophy notification. Trophies are a reward, often for a very large effort. And at the moment the RPCS3 notification does not transmit this sensation of reward, it is hollow, lifeless, lack magic, lacks...sound.

## Details
1. User loads PS3 firmware
2. RPCS3 extracts the trophy notification sound from dev_flash\vsh\resource\system_plugin.rco
3. When the pop-up is called -> PlaySound (Snd_trophy.wav)
4. Boom, trophies are 500% better now

Parts of RPCS3 that would be affected by this feature:
* Firmware installation
* Trophy notifications
* Settings menu (Option to disable the notification sound)

**Comment by marcoluc97** [comment]
#11078

**Comment by Hasster1** [comment]
Shouldn't this be closed now?

**Comment by Darkhost1999** [comment]
The only thing missing from the feature request I believe is .rco extraction to the sound folder.
Which isn't that a legal concern? The current noise is a QT beep right? Unless you upload your own sound named appropriately.
So are we waiting for someone to make a playlist of sounds?

**Comment by Megamouse** [comment]
Yes

**Comment by poudink** [comment]
Legal concern how? Wouldn't the sound be extracted automatically by RPCS3 from the user provided firmware, as proposed by the first post? What's the legal concern here?  It's not like RPCS3 would be distributed with the sound.

**Comment by Megamouse** [comment]
I'd say this is implemented.
I don't know if someone wrote a tutorial, but you need to copy some file to some dir and then it works.

Decrypting random fw files seems out of scope for this issue.
