### ISSUE TITLE
[NPUB31140] God Mode - sprx loading issues

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#10432]
This game somehow ends up loading the HLE version of CellSpursJq and freezes on boot.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6626571/RPCS3.log.gz)

**Comment by kd-11** [comment]
Closing as may be user error. Will reopen otherwise.

**Comment by kd-11** [comment]
Seems valid. I could reproduce even with fw 4.88.
It appears only version 1.0.0 is affected?

**Comment by clienthax** [comment]
Can't reproduce

**Comment by Megamouse** [comment]
Me neither. Must be user error after all 🤣

**Comment by kd-11** [comment]
Loaded the same installation from another OS and it works with the same config. Closing, seems to just be code gremlins.
