### ISSUE TITLE
[Regression] Unable to launch MGS4 after emulation stopping speed improvement

### ISSUE THREAD

**Issue by Killer-9000** [RPCS3/rpcs3#10433]
## Quick summary
After the commit I can no longer start the game, it crashes nearly instantly. 

## Details
I've tested with just the single commit changes. The cleanup method introduces is failing on the ensure.
CPUThread.cpp:1127

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
#10411 

#### 2. Please attach TWO logs:
* One for the build with regression.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6626636/RPCS3.log)
* One for the build that works as expected.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6626592/RPCS3.log.gz)

#### 6. Please provide your system configuration:
* OS - Windows 10
* CPU - AMD Ryzen 7 3700x
* GPU - AMD Radeon 590

**Comment by Megamouse** [comment]
Doesn't it work with the latest build?
Please add a log with the crash in the latest build.
There have been (maybe only partial) fixes for that bug after the "emulation stopping speed" commit.
So a newer one would be very helpful as well.

**Comment by Killer-9000** [comment]
Yep the hotfix that elad did fixed it, not getting the issue anymore.
