### ISSUE TITLE
Cache issues, Failed to initialize sparse file, booting issues.

### ISSUE THREAD

**Issue by MainTomato** [RPCS3/rpcs3#10448]
- **Quick summary**

For me to get RPCS3 to boot correctly without an error I need to completely delete the cache file. First time boot and deleting the cache makes the programs work every time. Without this the program would fail to boot with the cache made on boot.

- **Details**

```
Failed to initialize sparse file in '/home/tomato/.var/app/net.rpcs3.RPCS3/cache/rpcs3/'
It seems this filesystem doesn't support sparse files (22).
(in file rpcs3/util/vm_native.cpp:459[:4], in function shm) (errno=22)
Thread id = 140608804164992.

HOW TO REPORT ERRORS:
https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support
Please, don't send incorrect reports. Thanks for understanding.
```

- **RPCS3's log**
https://bin.snopyta.org/?048d156c0fd40613#2UY62k2sxsPiLscdJ49RsQTC5gM5oejMcwfDqnrGxVzQ

- **System Configuration**

* OS: Linux Mint 20.1 Cinnamon
* CPU: AMD Ryzen 5 3600 6-Core Processor × 6
* GPU: GeForce GTX 1080 Ti
* Driver version: 460.80
* RPCS3 Version: 0.0.16-1-dfbd63df Alpha (Flatpak, same result on appimage)

#### Please include.
* Anything else you deem to be important

**Comment by Nekotekina** [comment]
What filesystem(s) you use on mentioned paths?

**Comment by MainTomato** [comment]
Ext4, Linux Filesystem.

**Comment by MainTomato** [comment]
Older versions of the software still work just fine. I believe this started In 0.0.16

**Comment by Nekotekina** [comment]
Try latest master.

**Comment by MainTomato** [comment]
0.0.16-12394-6f874be4 boots successfully.
