### ISSUE TITLE
[Regression] New builds require an 32gb file in root that's only needed at runtime

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#10440]
New builds add a new 32gb file (rpcs3_vm) every time app is launched (if it doesn't exist). While I know this was added for future work, this file is still seen as a 32gb file by the system and apps. 

Google Drive and other backup apps will take a whole day to upload this, assuming it's uninterrupted. That's a complete waste of bandwidth as well as money since you pay for different storage amounts. I pay for a 2 tb backup so this one useless file is consuming almost 1/20th of my entire paid backup!

Please change it so it's created and destroyed as part of starting and close app if this is really needed. Worst case add a setting to disable this at the cost of whatever. There's no reason why this needs to persist outside of runtime. 

![2021-06-10 23_13_47-28% complete](https://user-images.githubusercontent.com/20983844/121639558-8d76f300-ca41-11eb-9116-abde93312014.png)

Config:
Windows 10 64-bit
GeForce GTX 3070
AMD 5900x@ 4.8ghz
32GB RAM

**Comment by MSuih** [comment]
If nothing else is possible, adding a file extension (like .tmp) to it would allow people to filter the file out of their sync process. Right now it has no extension so it would have to be filtered by name, which some software do not support.

**Comment by Nekotekina** [comment]
I can try to remove archive flag.

**Comment by Nekotekina** [comment]
@legend800 please remove Archive flag and check if it keeps getting uploaded.

**Comment by legend800** [comment]
What archive flag? As msuih mentioned, it needs a custom extension so it can be filteres out in backup tools at least.

**Comment by Nekotekina** [comment]
In file properties, other properties, "File is ready to be archived" or something.

**Comment by legend800** [comment]
Google drive and other backup apps don't care about that flag. That's a Windows only thing about compressing after a period of time or something.

The only way for this issue to be resolved is to either delete the file on exit or add a custom extension so it can be added to the ignore list in the various apps.
