### ISSUE TITLE
Vulkan Async Sc thread takes 100% CPU when using OpenGL renderer

### ISSUE THREAD

**Issue by linkmauve** [RPCS3/rpcs3#10443]
## Quick summary
A thread named Vulkan Async Sc is taking 100% of one core despite not using Vulkan.

## Details

Please describe the problem as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://linkmauve.fr/files/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
N/A

#### 3. Please attach screenshots of your problem.
N/A

#### 4. Please provide comparison with real PS3.
N/A

#### 5. Please provide your system configuration:
* OS: ArchLinux
* CPU: i7-8700k
* GPU: R9 270X (a UHD630 is also present on the system and has a Vulkan driver, but is unused here)
* Driver version: mesa master (21.2.0-devel commit a084e79a491)
* etc.

#### Please include.
* Anything else you deem to be important
I was previously using the Vulkan backend when on the Intel card, before acquiring this R9 270X, so some settings might have carried over.

**Comment by Megamouse** [comment]
the log is inaccessible

**Comment by kd-11** [comment]
I have the async scheduler thread only spawning when the vulkan renderer is being initialized, but I can reproduce this issue. Investigating.

**Comment by kd-11** [comment]
It's triggered by automatic type management. I've added a thread early exit in case incompatible options are active. Fix will be available in the next PR.
