### ISSUE TITLE
Kidou Senshi Gundam Extreme VS Full Boost [NPJB00512] Custom BGM Function Playback Nonfunctional

### ISSUE THREAD

**Issue by nomakewan** [RPCS3/rpcs3#10457]
## Quick summary
While the game can see custom BGMs on the emulated hard drive, the game errors out trying to play or apply them.

## Details

MP3s placed in dev_hdd0\music\Custom are detected by the game's custom soundtrack feature and displayed in a list as expected. However, attempting to play any of them or replace one of the ingame BGMs with them errors out with an error message (in Japanese) that reads: "Failed to play file. The music data has either been deleted, is corrupted, or may be in an unsupported format." These are the same MP3s that I use on the real console for this same game without issue (joint stereo, 192kbps, 44.1 kHz). I did test 128kbps MP3s just to see if it was a complexity issue but these had the same error.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6653475/RPCS3.log.gz)

#### 5. Please provide your system configuration:
* OS: Windows 7 x64
* CPU: Intel i7-4790K
* GPU: nVidia GTX1070
* Driver version: 466.11

**Comment by Megamouse** [comment]
Does this happen with all mp3s ?
Maybe it can't handle the Japanese characters in the filenames?
Try the ones that only have roman letters if you didn't already

**Comment by nomakewan** [comment]
Yes, unfortunately this happens with all MP3s. I originally only tested with a single MP3 that had only roman letters, which was how I found the bug. This led me to try all the rest of the songs that I used on the real console, and found the same bug. So the complexity of the MP3 encoding and the characters in the filename all appear to be irrelevant in this case.

**Comment by Megamouse** [comment]
I think wipeout hd (if i remember correctly) also has this functionality and seems to work for other users.
In case that you own the game as well, you might wanna check if it works there for you, so that we can rule out that it regressed

**Comment by nomakewan** [comment]
I tested using the demo for Wipeout HD. Custom BGMs work perfectly fine ingame. The game did crash the emulator fatally 2 laps into the race, but as this is just the demo, I can't tell if that has anything to do with this and am assuming it doesn't. After all, attempting to play the music in EXVSFB doesn't crash anything, it simply doesn't work at all.

**Comment by nomakewan** [comment]
I've attached the log from playing the demo of Wipeout HD to this post. The emulator crashed before it could generate the GZip version, so I zipped it instead. Interestingly enough, the game automatically chose one of my BGMs with Japanese characters in the filename, so that doesn't appear to be an issue in Wipeout either.
[RPCS3log.zip](https://github.com/RPCS3/rpcs3/files/6678188/RPCS3log.zip)

**Comment by InquisitorDavid** [comment]
I can confirm this bug for the game as well (NPJB00512). I also had a library of songs I used in my original game that I tried to copy over to the MUSIC folder.

Interestingly, when selecting the custom BGM option, the option to select the folder containing the custom MP3s also intermittently disappears. I would have to leave the custom BGM menu, then return to 'try' to make the option show again, and that doesn't always work.

This may point to an issue with reading the directory structure as requested by the game - the emulator may, at one load, correctly read/enumerate the external folders used, but then when reading a second time, the connection is no longer made.

This is using 0.0.16-12408-aaa20c0f Alpha, latest auto-update at time of writing.

Here's a video I uploaded demonstrating both the error when reading, and the disappearing Custom Folder: [https://youtu.be/QOXFFSpuKmw](url)

Note that the first two items listed are:
1. BGMs internal to the game
2. Installed DLC BGMs

**Comment by nomakewan** [comment]
InquisitorDavid, the bug with 'Custom' disappearing actually occurs on real hardware as well. If you attempt to set a custom BGM that has a compatibility issue, it will fail, and the custom folder will no longer be selectable as an option. However, if instead of setting the BGM you instead play it in the menu (triangle instead of circle), it will simply pop the error message but still allow you to navigate the custom BGM selection.

That said, on real hardware none of these particular MP3s have any compatibility issues, so that isn't the problem. It's just that the folder disappearing is unrelated to the problem of these MP3s not being compatible in RPCS3.

**Comment by InquisitorDavid** [comment]
Oh. Never put an incompatible MP3 back then, so didn't know.

But yeah, the error is happening and triggering that bug too. Guess the disappearance won't need to be fixed.

**Comment by PandaPyre** [comment]
Hi there; I've been having similar issues with SSX 2012 and I'm wondering if this issue's been solved yet or not. The game will initially recognize my playlist in the music folder, but will fail to recognize it a second time if I go back into the same menu. Once in the game itself, all I get is glitchy audio, so it seems to be trying to load SOMETHING there. Is the folder disappearance glitch native to only this game, or PS3 in general? I wonder why Wipeout seems to work fine.

**Comment by nomakewan** [comment]
Updating to confirm that this bug is unchanged on the latest version of RPCS3 (0.0.17-12475-aaac4c1b). I have attached a clean log to this post. The log is just firing up the emulator, starting the game, going straight to the BGM settings, and attempting to play one of the MP3s. Just like the first post.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6825022/RPCS3.log.gz)

**Comment by nomakewan** [comment]
Updating to confirm that this bug is still present in the current version of RPCS3 (v0.0.20-13167-8c9090fd). A clean log is attached. As always, it's just firing up, loading the game, going to custom BGM, and attempting to play a single custom MP3 file.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7855973/RPCS3.log.gz)

**Comment by nomakewan** [comment]
Confirming this bug is still present in the current version of RPCS3 (v0.0.20-13286-e39797d8). Clean log is attached. As always, it's just starting emulator, starting the game, proceeding straight to the custom BGM options, and then attempting to play a single MP3. It's always said this, but as a note there appears to be an issue with the try_to_int64 function being used to enumerate the available MP3 files in dev_hdd0\music. Hope that helps.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8081616/RPCS3.log.gz)

**Comment by Megamouse** [comment]
The try_to_int64 errors just mean that the metadata string cannot be converted to a number.
In this case, the metadata did not contain any track number, so the default -1 was used.
You could use exif to read the metadata of the mp3 and check if it really doesn't contain any track info.

I added some improved logging to #11547

**Comment by nomakewan** [comment]
It looks like the enhanced logging has been merged into the main branch, so I've updated the test. All the files I used on my PS3 had their metadata stripped, so yes, that's exactly why those errors were popping up. I dropped the music folder down to just a single MP3 with an English title and added a track number to its metadata for now. Here is a new log in the current version of RPCS3 (v0.0.20-13291-91d7f28c).

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8103131/RPCS3.log.gz)

**Comment by Megamouse** [comment]
So does it work?

**Comment by nomakewan** [comment]
If you mean, is it able to play any of the files, no. It's still broken the exact same way as the first post.

**Comment by Megamouse** [comment]
I added even more logging.

**Comment by Megamouse** [comment]
Okay. I fixed the disappearing custom music lists.
It should be in the master build in an hour or so.

And I also implemented the music playback.
It only works for single files at the moment (no playlists), and some random mp3s do not work.
But that isn't our fault, it's the fault of the playback library we use.

I'll let you know when you can test it.

**Comment by Megamouse** [comment]
can you test this Pull Request once it has built? (maybe in 20-30 minutes)
#11560

I added a Qt music handler.
You have to enable it in the IO tab in the settings dialog.

No rush.

**Comment by nomakewan** [comment]
Looks like that pull request failed a check and so didn't get automatically built. The one adding additional logging did, and the additional logging is now implemented on my end, but the one enabling qt music handler did not as it doesn't appear as an option in I/O.

**Comment by Darkhost1999** [comment]
Only MacOS failed so if you're not using Mac.
https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_download_builds_from_a_pull_request_on_GitHub?

https://cirrus-ci.com/task/6412619186700288
Just download the artifact

**Comment by nomakewan** [comment]
My apologies, I was not aware of the ability to download an individual pull request like that. I've just tested it and it appears to be working perfectly with EXVSFB! So once this pull request gets merged into the main branch, it will indeed close this issue. Awesome work, thank you so much!! Attached is a log for completion's sake. Per usual, it's just launching the emulator, firing up the game, going straight into the BGM settings menu, and then attempting to play one of the custom MP3s. Except this time, it works!

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8104999/RPCS3.log.gz)

**Comment by Megamouse** [comment]
does it also work while playing, or only in the menu?

**Comment by nomakewan** [comment]
Works perfectly ingame as well! :)
