### ISSUE TITLE
Regression: Black Artifacts on Motorstorm Apocalypse (#10382)

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#10459]
After 0.0.16-12355-98f534b1 (#10382), Motorstorm Apocalypse displays black aritfacts all over the screen: 
![image](https://user-images.githubusercontent.com/61447828/122188262-2c4a8780-ce66-11eb-893d-f12675bb1de5.png)
Same results with ogl, SRM, all RSX buffers and CPU blit.
Last working build log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6661611/RPCS3.log.gz)
Latest master log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6661617/RPCS3.log.gz)
RSX capture: https://drive.google.com/file/d/15aS5ubPL2lgOAMWqavp-_wAcVrQNmspb/view?usp=sharing
Specs: 5600x, 1050 Ti driver 466.63, Windows 10 21H1

**Comment by kd-11** [comment]
Needs renderdoc trace and probably more bisecting. Was OpenGL broken before? The PR does not touch OGL. Also try removing shader cache before running.

**Comment by Satan86** [comment]
OpenGL was broken before, the PR made Vulkan break the same way as ogl already was. 
Got RDCs for before and after the PR on vulkan and another for ogl https://drive.google.com/file/d/11WmIdLJtNxLuTo9XqdSnh9xyA3hpj1wY/view?usp=sharing

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/10489
