### ISSUE TITLE
Overlord Raising Hell [BLUS30143] regression from ingame to loadable (#7229)

### ISSUE THREAD

**Issue by digitaldude555** [RPCS3/rpcs3#10460]
## Quick summary
Game has gone from Ingame to loadable.

## Details
Regressed after #7229 

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
rpcs3-v0.0.8-9365-aeed349a_win64 first build with regression.

#### 2. Please attach TWO logs:
Log from first build with regression and current master.
[RPCS3Regression.zip](https://github.com/RPCS3/rpcs3/files/6662484/RPCS3Regression.zip)
[RPCS3OverlordMaster.zip](https://github.com/RPCS3/rpcs3/files/6662488/RPCS3OverlordMaster.zip)
Log from Last working build.
[RPCS3OverlordLastWorking.zip](https://github.com/RPCS3/rpcs3/files/6662485/RPCS3OverlordLastWorking.zip)

**Comment by elad335** [comment]
Retest with #10466
