### ISSUE TITLE
Regression with Sonic CD

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1047]
Sonic CD start breaking from this commit https://github.com/RPCS3/rpcs3/commit/3cf80b08313f0633e11bb8a927866c38ea2f8297

E {PPU[1] Thread (main_thread)[0x000be9b4]} sys_spu TODO: Unsupported SPU Thread options (0x2)
E {PPU[1] Thread (main_thread)[0x000be9b4]} sys_spu TODO: Unsupported SPU Thread options (0x2)
E {PPU[1] Thread (main_thread)[0x000be9b4]} sys_spu TODO: Unsupported SPU Thread options (0x2)
E {PPU[15] Thread (INITASYNC)[0x000bdf34]} cellSysutil error: cellSaveDataAutoLoad2: Couldn't find save entry (NPUB30624-AUTO)
E {PPU[43] Thread (playeSpursHdlr0)[0x00000000]} Exception: Access violation reading location 0x0
E {PPU[43] Thread (playeSpursHdlr0)[0x00000000]} Information: is_alive=1, m_last_syscall=0x0 ()

**Comment by Nekotekina** [comment]
@raven02 @gopalsr83 I fixed some SPU syscalls so sys_spu_thread_group_start() now initializes SPU local storage instead of sys_spu_thread_initialize(). It seems that current SPURS implementation is broken because it relies on old implementation when installing hacks.

**Comment by raven02** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/1062
