### ISSUE TITLE
RenderDoc bugs

### ISSUE THREAD

**Issue by wheelmac92** [RPCS3/rpcs3#10470]
RPCS3 with Vulkan crashes when I try to take RenderDoc captures in the most demanding PS3 games (God of War 3, Call of Duty MW2, etc) but does not crash with simpler games like Skate 3. Taking an RSX capture without booting a game, and then trying to take a renderDoc capture, does not make a difference.

RPCS3 with OpenGL can "finish" a capture in games like Cod MW2, but the result is corrupted, and full of vertex explosions, that do not appear in-game in RPCS3

I am using a GTX 1050 with 2gb of VRAM, could it be a vram shortage?

**Comment by elad335** [comment]
https://github.com/baldurk/renderdoc

**Comment by wheelmac92** [comment]
I also tried RPCS3's "Debug -> Renderdoc compatibility mode" but now instead of Renderdoc crashing, it makes all my monitors go black and shut off, then eventually come back on, and then it crashes

**Comment by elad335** [comment]
Thanks for reporting, I believe you should be reporting at https://github.com/baldurk/renderdoc instead.

**Comment by kd-11** [comment]
Renderdoc capturing of "high demanding PS3 games" will need 32GB of RAM at a minimum. System RAM tends to matter far more than VRAM for capturing. Either way, this isn't our bug.
