### ISSUE TITLE
Error linking rpcs3

### ISSUE THREAD

**Issue by latot** [RPCS3/rpcs3#1048]
Hi, here a error compiling rpcs3, log:

[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/AutoPause.cpp.o
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/rMsgBox.cpp.o
Linking CXX executable ../bin/rpcs3
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/rpcs3.dir/Emu/Memory/vm.cpp.o: referencia sin definir al símbolo 'shm_unlink@@GLIBC_2.2.5'
/lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld devolvió el estado de salida 1
rpcs3/CMakeFiles/rpcs3.dir/build.make:7491: fallo en las instrucciones para el objetivo 'bin/rpcs3'
make[2]: *** [bin/rpcs3] Error 1
CMakeFiles/Makefile2:263: fallo en las instrucciones para el objetivo 'rpcs3/CMakeFiles/rpcs3.dir/all'
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:116: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

Adding rt to target_link_libraries in rpcs3/CMakeList.txt  : 

[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/rMsgBox.cpp.o
Linking CXX executable ../bin/rpcs3
CMakeFiles/rpcs3.dir/Emu/SysCalls/Modules/sysPrxForUser.cpp.o: En la función `lwmutex::const_be_u32_t<4294967295u>::operator be_t<unsigned int, unsigned int> const() const':
/home/pipe/Documentos/Git-Repos/rpcs3/rpcs3/Emu/SysCalls/lv2/sys_lwmutex.h:32: referencia a `lwmutex::const_be_u32_t<4294967295u>::value' sin definir
CMakeFiles/rpcs3.dir/Emu/SysCalls/Modules/sysPrxForUser.cpp.o: En la función `lwmutex::const_be_u32_t<0u>::operator be_t<unsigned int, unsigned int> const() const':
/home/pipe/Documentos/Git-Repos/rpcs3/rpcs3/Emu/SysCalls/lv2/sys_lwmutex.h:32: referencia a `lwmutex::const_be_u32_t<0u>::value' sin definir
CMakeFiles/rpcs3.dir/Emu/SysCalls/Modules/sysPrxForUser.cpp.o: En la función `lwmutex::const_be_u32_t<4294967294u>::operator be_t<unsigned int, unsigned int> const() const':
/home/pipe/Documentos/Git-Repos/rpcs3/rpcs3/Emu/SysCalls/lv2/sys_lwmutex.h:32: referencia a `lwmutex::const_be_u32_t<4294967294u>::value' sin definir
CMakeFiles/rpcs3.dir/Emu/SysCalls/Modules/sysPrxForUser.cpp.o: En la función `lwmutex::const_be_u32_t<4294967293u>::operator be_t<unsigned int, unsigned int> const() const':
/home/pipe/Documentos/Git-Repos/rpcs3/rpcs3/Emu/SysCalls/lv2/sys_lwmutex.h:32: referencia a `lwmutex::const_be_u32_t<4294967293u>::value' sin definir
collect2: error: ld devolvió el estado de salida 1
rpcs3/CMakeFiles/rpcs3.dir/build.make:7491: fallo en las instrucciones para el objetivo 'bin/rpcs3'
make[2]: *** [bin/rpcs3] Error 1
CMakeFiles/Makefile2:263: fallo en las instrucciones para el objetivo 'rpcs3/CMakeFiles/rpcs3.dir/all'
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:116: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

Thx

**Comment by Syphurith** [comment]
@latot Well..That seems you are facing some compilation errors. Maybe it relates to Neko's recent work, about sys lv2 cleanup.. Hope it can be fixed later.
4294967295 = 0xFFFFFFFF(32 bit signed: -1). But it seems to be missing one param of `be_t`.

**Comment by devilmac** [comment]
Hi,
I hava a similar problem, the following:
Linking CXX executable ../bin/rpcs3
**Undefined symbols for architecture x86_64:**
  "lwmutex::const_be_u32_t<0u>::value", referenced from:
      lwmutex::const_be_u32_t<0u>::operator be_t<unsigned int, unsigned int> const() const in sys_lwmutex.cpp.o
      lwmutex::const_be_u32_t<0u>::operator be_t<unsigned int, unsigned int> const() const in sysPrxForUser.cpp.o
  "lwmutex::const_be_u32_t<4294967293u>::value", referenced from:
      lwmutex::const_be_u32_t<4294967293u>::operator be_t<unsigned int, unsigned int> const() const in sysPrxForUser.cpp.o
  "lwmutex::const_be_u32_t<4294967294u>::value", referenced from:
      lwmutex::const_be_u32_t<4294967294u>::operator be_t<unsigned int, unsigned int> const() const in sysPrxForUser.cpp.o
  "lwmutex::const_be_u32_t<4294967295u>::value", referenced from:
      lwmutex::const_be_u32_t<4294967295u>::operator be_t<unsigned int, unsigned int> const() const in sys_lwmutex.cpp.o
      lwmutex::const_be_u32_t<4294967295u>::operator be_t<unsigned int, unsigned int> const() const in sysPrxForUser.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/rpcs3] Error 1
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2

I'm using a Mac OS X Yosemite x64.
Thanks a lot!

**Comment by Syphurith** [comment]
@devilmac Well pity for that. I could build rpcs3 with VS on Windows.
VS doesn't point any severe errors in the `sys_lwmutex.cpp`, but this seems to be the cause.
Eh.. Well, one question for you two "Which latest standard your compiler can use?"
Try change the line `/rpcs3/Emu/SysCalls/lv2/sys_lwmutex.h:32`:
From `return be_t<u32>::make(value);` To `return ((be_t<u32>*)this)->make(value);`.
To see if that compiles and runs correctly. (It pass with VS2013..)

the `make` is from `be_t<u32>`, which is a template class and that function the line belongs is an override function of operator (). I don't know why it fails on your machine, exactly.

BTW, maybe you can *try figure out how to setup the TRAVIS* for a Mactonish build.
Even it can not show us the real reason why it stuck at least it shows after which merge we fail.

**Comment by latot** [comment]
Hi, i'm using gentoo 64 with gcc 4.8.4, well i try your recomendation but not lucky, the same error, checking the commits i can't say specifically wich caused this, because are to many differents errors and fixes.

the lastest working was in 31bf130b1c7acf78ef334a2bdb0550971e6d2821
and the first compilation with the error was e5de176b162b70abfd72399d48e026d0ab64db6f

Thx.

**Comment by Syphurith** [comment]
@latot There aren't many difference in `sys_lwmutex.cpp` between the two commits, but many in `sys_lwmutex.h`. I can not understand the compilation error message.. what does it mean, `no definition` or `definition is not as reference`? Please give me the English version..
BTW you can try gcc 4.9.0+. Later verion of gcc would support latest standard better.

IIRC, `static` vars and `global` vars have their own location in Global/Static Zone of PE/ELF.
and `const` functions and `const` vars doesn't generate real symbols but be replaced instead.
I doubt if that is the real reason why compiler doesn't find the corresponding reference.
However that is at least true in C, maybe not in C++. I used to be a C Programmer not C++'s.
Static vars definition in struct is not allowed in C, but allowed in C++ (struct behaves as class).

You can try this:
```
	struct const_be_u32_t
	{
		static u32 value = _value;

		operator const be_t<u32>() const
		{
			return be_t<u32>::make(value);
		}
	};
```
Still linking the executable now. Would tell you if that runs correctly on my machine.

**Comment by latot** [comment]
Hi again, now works, first i need add rt to target_link_libraries in rpcs3/CMakeList.txt

with gcc 4.8.4 works with the change
u32 value = _value;

with gcc-4.9.0 works fine without the change.

**Comment by Syphurith** [comment]
@latot So that's good news. You may add rt in CMakeList.txt and make a pull.
@devilmac Well what is your using GCC version?

**Comment by Syphurith** [comment]
Made changes according to @Bigpet said in #1049. 55fc008d472e0c4b0f203f4f85fc11e876ce7406 Still waiting for more confirmation.

**Comment by devilmac** [comment]
@Syphurith on my Mac I use this C compiler:
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix

refer to this issue #994

**Comment by Syphurith** [comment]
@devilmac then would 55fc008 this pass the compilation and run as before?

**Comment by latot** [comment]
yay, now works perfectly. Thx, waiting @devilmac confirmation.

**Comment by Syphurith** [comment]
I'm sorry @latot about my pull. Since the ADDITIONAL_LIBS could be better solved..

**Comment by Bigpet** [comment]
This is odd I can't reproduce the linker error with gcc 4.8.2

**Comment by Bigpet** [comment]
Alright, could recreate it with clang 3.4, it is kind of redundant, so I think we can just remove  lwmutex::const_be_u32_t::value

**Comment by devilmac** [comment]
Sorry guys, but for some days I can't try if the fixes work on my side.
I'll tell you the response when I'll can try.

Thanks for all.

**Comment by Syphurith** [comment]
@devilmac @latot is the issue still present now? I thought it would go after #1052.
If not and you're using 3.4.x or 3.5.x version of clang please try update to 3.6.

**Comment by latot** [comment]
working for me, waiting @devilmac to close it, i'm using clang 3.5. thx

**Comment by devilmac** [comment]
Sorry for the delay, I was in vacation.
I'm trying to build the project right now and it seems that the compilation process was completed successfully.
