### ISSUE TITLE
Stopping emulator took too long. Some thread has probably deadlocked. Aborting. Thread id = 9772

### ISSUE THREAD

**Issue by calvinvalerian** [RPCS3/rpcs3#10480]
When closing a window an error message pop up referring Thread id = 9772

See the video log:
https://youtu.be/JN-tAncz64M

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6686986/RPCS3.log)

- No longer own real PS3

![Screenshot (186)](https://user-images.githubusercontent.com/18316781/122772172-4c000680-d2d1-11eb-8e8b-9ecc846070d0.png)

**Comment by Megamouse** [comment]
![image](https://user-images.githubusercontent.com/23019877/122785428-abe7b480-d2b3-11eb-82a6-ec3f91dd2a5b.png)

**Comment by calvinvalerian** [comment]
I've tried all in your screenshot no luck. Still return

Stopping emulator took too long. Some thread has probably deadlocked. Aborting. Thread id = 9772

**Comment by Megamouse** [comment]
I think this error is too generic to warrant an issue.
There have been many changes since June.
Reopen if it still happens consistently
