### ISSUE TITLE
BCAS25003 renderer not properly working!

### ISSUE THREAD

**Issue by jakoaltrd** [RPCS3/rpcs3#10484]
## Quick summary
renderers are not working properly, both vulkan and opengl  in GOW3!

## Details
1. opengl renderer suffers from a low fps, which is 20fps, and graphics are too shinny that are not visiable. just as the shot shows.(when I can't choose graphics card in opengl mode)
2. vulkan renderer nearly can't work at all, it shows 2 fps, I use the defalt settings.

#### 5. Please provide your system configuration:
* OS win10
* CPU intel i7-11800H
* GPU RTX3070 laptop
* Driver version 461.88
* etc.

#### Please include.
![2021-06-22](https://user-images.githubusercontent.com/67615360/122858113-514e6700-d34c-11eb-98d5-21cc8fcd4f3f.png)
<img width="939" alt="2021-06-22 (3)" src="https://user-images.githubusercontent.com/67615360/122859148-1b11e700-d34e-11eb-9e12-8259bd162972.png">

* Anything else you deem to be important
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6690939/RPCS3.log.gz)
the build version is the lateset.I didn't upload RSX capture cause it can't process this file here,maybe later do that again!

conclusion:
This is a very important description, please pay more attention:
----the story goes back to 2018, at that time most games suffered from a low speed in RPCS3 until neko released a asychronous shader compiling update, but my computer is too slow to run many 3A titles. so I hadn't used rpcs3 for a long time, but I always keep an eye on how RPCS3 is going , and I saw it gained great improvments since then , like UI ,which is the same as a real PS3, speed and accuracy enhanced, and some other compatbility stuff, then the time went to now, today rpcs3 must be able to run most games in accept speed and quality. but it doesn't , on my pc, I think it can simulate any game , because its hardware is the latest, which is shown above. then I decide to find the reason myself, I set all the settings on default, and use opengl as my backend, but I can't choose my graphics card(I had a dedicated card and a integrated card), and the framerate is quite low 20fps, besides, the graphics seems had some issues as shown above. then I changed to vulkan, with rtx3070, the framerate  slow down to 2 fps, that's quite strange, so I analyze there must be some settings I missed , or I used the wrong version! but I'am sure you developers know how to fix this, it is not a big deal for you. so give me some advices or guidlines. and I will keep testing it and post more results.
----anyway, I am a big fan of RPCS3, and I think you guys are doing a great job, I will support it via the patron just like before I did, maybe someday I will be a developer, and join your team!

**Comment by MSuih** [comment]
God of War 3 requires Write Color Buffers to be enabled.

In future, please use our discord to ask for help with emulator and do not open issues to github about it.
