### ISSUE TITLE
Vulkan backend isn't working after Nvidia driver update 471.11

### ISSUE THREAD

**Issue by alfredolvera** [RPCS3/rpcs3#10486]
## Quick summary
Vulkan backend isn't working after Nvidia driver update 471.11

## Details
After the update, all games display a static black frame with the Vulkan backend. Some games do have audio. This is consistent with the latest 4 builds that I tested. Opengl works fine, same settings. Clearing all caches didn't helped

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
RPCS3 0.0.16- 12409-3c614d95

#### 2. Please attach TWO logs:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6698237/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6698387/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6698408/RPCS3.log)

#### 6. Please provide your system configuration:
- SYS: RPCS3 v0.0.16-12409-3c614d95 Alpha | HEAD
- SYS: AMD Ryzen 7 5800X 8-Core Processor | 16 Threads | 31.91 GiB RAM | TSC: 3.800GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19042, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3070' running on driver 471.11.0.0
- SYS: Firmware version: 4.87

#### Please include.
* Anything else you deem to be important

**Comment by RainbowCookie32** [comment]
Both logs are empty, please attach logs from a session with the issue.

**Comment by Illynir** [comment]
No problem for me. Try to do a clean installation of the driver, it must be corrupted.

**Comment by alfredolvera** [comment]
![image](https://user-images.githubusercontent.com/50789842/123018247-d5780d00-d393-11eb-8c41-84c2d6202084.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6698169/RPCS3.log)

New log updated and a screen of a game that freezes there but there is still sound.

@Illynir Do you have the same GPU as me or from the same series? Because I tried Cemu with the Vulkan backend and several Vulkan games like Doom Eternal and only RPCS3 has this issue, which leads me to believe that this isn't a faulty driver installation.

**Comment by RainbowCookie32** [comment]
> ·! 0:00:06.077637 SYS: Disabling logging...

Logging is silenced :upside_down_face:

**Comment by alfredolvera** [comment]
@RainbowCookie32 Sorry about that, I didn't remembered that I silenced it. New log updated.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6698195/RPCS3.log)

**Comment by Illynir** [comment]
@alfredolvera I have RTX 2060.

**Comment by alfredolvera** [comment]
@Illynir This was with today's released drivers, right?

**Comment by alfredolvera** [comment]
Added more logs of "playable" reported games to the main thread. I forgot to add that I already tried several reboots, power off-on cycles and several other Vulkan games. They all work fine. I tried 4 older versions of RPCS3 and they all show the same issue. Yesterday everything was working fine and no config changes were made since then. The only thing different is the new Nvidia driver, that was released earlier today.

**Comment by kd-11** [comment]
> Added more logs of "playable" reported games to the main thread. I forgot to add that I already tried several reboots, power off-on cycles and several other Vulkan games. They all work fine. I tried 4 older versions of RPCS3 and they all show the same issue. Yesterday everything was working fine and no config changes were made since then. The only thing different is the new Nvidia driver, that was released earlier today.

I'd start by just running the basic samples that ship in the emulator in /dev_hdd0/game/TEST12345
If the basic triangle isn't showing, that means vulkan isn't working on your system. This is more of a support issue, I would recommend first using DDU to nuke the old driver and try reinstalling. We can keep the ticket open in case we have a flood of reports, although this is not our bug.

**Comment by Illynir** [comment]
> 
> 
> @Illynir This was with today's released drivers, right?

Yes.

**Comment by alfredolvera** [comment]
Hi all. I just ran DDU from safe mode, reinstalled the latest drivers, reboot without quick start and the same issue persist. Log now shows in some games: 

F SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKQueryPool.cpp:46[:4], in function poke_query)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error)

@kd-11 I tried to run the triangle test and it shows a STATIC multicolored triangle. 
![image](https://user-images.githubusercontent.com/50789842/123111799-d09e7200-d402-11eb-9c24-80942700c70d.png)

I also tried removing all caches again from all the tested games. Didn't worked.
More logs added: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6702478/RPCS3.log)
Triangle Test: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6702472/RPCS3.log)

Retested Doom Eternal running on Vulkan and CEMU triple-checked that also ran un Vulkan and everything works fine.

![Volume{66030e09-7c15-62c6-4b8d-16cee49b0c55} Screenshot 2021 06 23 - 09 17 11 92](https://user-images.githubusercontent.com/50789842/123113343-1a3b8c80-d404-11eb-8674-d03e25c27385.png)

Thanks for looking into it, guys.

**Comment by MSuih** [comment]
@alfredolvera triangle test is meant to be static. It's purposefully designed to be the simplest possible rendering job for emulator and is only useful for validating if the emulator can output some kind of an image to screen.

If you want a test with movement, try the cube sample from same location. It'll spin around, quite fast as well if you have decent rig.

**Comment by alfredolvera** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6702561/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6702576/RPCS3.log)
@MSuih I tried the cube same and it also froze. Log here:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6702595/RPCS3.log)

Tested 7 different games, removed all cache from all, they all display a black screen or a static screen from the last "Linking PPU modules".

**Comment by kd-11** [comment]
Disable asynchronous texture streaming, or set the async scheduler in advanced tab to "host".
The difference between cube test and triangle test is only the use of textures in cube.

**Comment by 13xforever** [comment]
Same issue with 470.42.01 drivers for Linux

**Comment by 13xforever** [comment]
Changing async scheduler doesn't help, only disabling async texture streaming altogether

**Comment by kd-11** [comment]
We have a tracker for async here: https://github.com/RPCS3/rpcs3/issues/9968
If it keeps being a problem, I can also just forcefully disable the option on Nvidia GPUs until I get back to the async compute stuff.

**Comment by alfredolvera** [comment]
Changed async scheduler to "host": Hard crash. Log attached:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6703737/RPCS3.log)
F SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\vkutils\sync.cpp:199[:5], in function wait_for_event) (e=0x00000057[87])
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error) (e=0x00000057[87])

Shader mode to "Legacy" or "Shader Interpreter", same crash. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6703752/RPCS3.log)

**Comment by alfredolvera** [comment]
Can confirm that disabling "Asynchronous Texture Streaming" did the trick. Everything works now.

Thanks @kd-11

**Comment by kd-11** [comment]
@alfredolvera You need to **disable** asynchronous texture streaming for this one. The driver is serializing my queues with higher priority afforded to the graphics queue which is submitted after the streaming one. This is unfortunate and requires the feature disabled or at least reworked for nvidia drivers. The overhead may cause it to not be worth implementing though which would lead to me just disabling it outright for nvidia.

**Comment by Mew8000** [comment]
@kd-11 Also outher bug says no found GPU on a pc that meets system requirements because load vulkan up on Nividia drivers 471.1 and specs laptops are Ryzen 9 4900hs rtx 2060 max q

**Comment by Mew8000** [comment]
When will problem be fixed. @kd-11

**Comment by Yoshi9800** [comment]
Update driver to 471.41 it works with Vulkan in rpcs3 once more

**Comment by Yoshi9800** [comment]
Hey kd11 why Fixing bug for diver not newest one they Fixing the bug with 471.41 so update drivers fix vulkan on Rpcs3 emulator
