### ISSUE TITLE
Not Working in 32 bit

### ISSUE THREAD

**Issue by raamisful123** [RPCS3/rpcs3#10481]
When i  was downloaded rpcs3 latest version from its original website but i got a message that this app cant run cause i use 32 bit system and this app is only works on 64 bit so please tell me is there any way to use latest version of rcpcs3 in 32 bit x-86 based system cause i also download 32 bit version buts that too old and not working i want latest one on 32 bit please help me.

**Comment by RainbowCookie32** [comment]
You can't run RPCS3 on a 32bit OS. And if you are running a 32bit OS, chances are your PC is too old to run RPCS3 decently.

**Comment by MSuih** [comment]
RPCS3 requires 64-bit operating system due to some architectural decisions and we have no plans of changing this.

**Comment by Nekotekina** [comment]
Poor souls.
