### ISSUE TITLE
[Regression] Stopping Emulator took too long

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#10499]
Regression caused by #10490 on all games:

![image](https://user-images.githubusercontent.com/23019877/123540524-b97fbd00-d73f-11eb-995c-fbf4db78f3d7.png)

**Comment by elad335** [comment]
hmm ok assignment operator doesn't pass in inheritence, @Nekotekina. (I'm afk)

**Comment by Megamouse** [comment]
Just a reminder: Please test these obvious things before submitting or merging.
It's not hard to click on some games a couple of times

**Comment by Nekotekina** [comment]
Welp sorry about this
