### ISSUE TITLE
[Feature Request] Recompile all games at once

### ISSUE THREAD

**Issue by wheelmac92** [RPCS3/rpcs3#10504]
## Quick summary

Problem:
If someone wants to copy/paste all their PS3 games from one computer to another, they need to wait for PPU and SPU compiling for each game, and you need to click each game to begin compiling

Solution:
Can there be a feature for all games to have PPU and SPU compiled, so that someone can click one button and then come back to the computer in a few hours, with every game ready to go?

## Details

Please describe the feature as accurately as possible.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
Installation

#### 2. Please tell us, why your feature is important to RPCS3.
Easier setup

#### 3. Please attach screenshots of the feature implemented in other projects.
N/A

#### 4. Please provide your system configuration:
Windows 10
i7 7700hq
GTX 1050

**Comment by MSuih** [comment]
There is already an option to compile PPU caches for all games, I think it was under `File > All Games > Create PPU caches` or something like that.

SPU and Shader modules must be encountered during runtime to compile them, it's not possible to sense them from game files for compilation.

Closing as all requested features have either been implemented or are not possible to do.

**Comment by wheelmac92** [comment]
@MSuih It says "Create PPU Caches", does it also do SPU cache?

**Comment by MSuih** [comment]
It creates PPU caches and nothing else. SPU caches are only _loaded_ when launching game, not _created_. To create SPU cache, you must actually play the game to encounter the spu programs.
