### ISSUE TITLE
Resident Evil 0 HD & Resident Evil 1 HD - Ingame Whitescreen

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#10502]
Both resident evil remasters have a whitescreen while ingame (Menu and maps looks fine) but in the gameplay everything is white, you can only hear the sounds. This games were working fine some weeks ago.

Tried using write color buffer and other options enabled / Disabled with no results.

My system:

Nvidia GTX 970
i7 4790k
16 GB DDR3
Windows 10 x64

**Comment by RainbowCookie32** [comment]
> This games were working fine some weeks ago.

Then it's a regression and you should search for the build that broke them. You are also missing logs, one from a good build, and one from the latest one (as indicated on the issue templates).

**Comment by Silanda** [comment]
I've got the Japanese physical releases of these games, and the white screen seems to be caused by upscaling. At native res the graphics appear. I haven't checked to see if they worked when upscaled. They do have some other issues though, and I will probably report those later.

**Comment by LuismaSP89** [comment]
They're actually PAL games. I also tested without upscaling, all settings by default, and the result is the same. In any case thanks for your help : )

**Comment by mortdeus** [comment]
> > This games were working fine some weeks ago.
> 
> Then it's a regression and you should search for the build that broke them. You are also missing logs, one from a good build, and one from the latest one (as indicated on the issue templates).

this is literally the smartest approach to bug reporting i've seen so far, and i've been looking at these issue logs on github for ages now.

**Comment by LuismaSP89** [comment]
This issue is solved in the latest builds. Closing.
