### ISSUE TITLE
ModNation Racers not Booting With Error

### ISSUE THREAD

**Issue by JasonOcelots** [RPCS3/rpcs3#10511]
I have been having trouble with the game ModNation Racers (serial is BCUS98167) (game is marked as playable) I am on the latest update (1.11). The game was dumped from my own disk with no scratches or smudges on it. However, every time I boot up the game, I get this error: F VM: Access violation reading location 0x0 (unmapped memory) [type=u32]: and then it gives me a black screen. I have no idea how to fix this, even after toying with settings for hours. Specs: Windows 10 64-bit, NVIDIA GeForce GTX 1660 Ti, 8.0GB RAM, Intel Core i5-9400F CPU @ 2.90 GHz. My RPCS3.log file can be found here: https://drive.google.com/file/d/1-79JQ7Buo57smhm9zeN6RTBOPc1lJkFP/view?usp=sharing

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
