### ISSUE TITLE
VK_ERROR_FEATURE_NOT_PRESEN

### ISSUE THREAD

**Issue by leonardojimenez1990** [RPCS3/rpcs3#10518]
## Quick summary
Your GPU driver does not support some required MSAA features.
Try updating your GPU driver or disable Anti-Aliasing in the settings.

## Details

Assertion Failed! Vulkan API call failed with unrecoverable error: Requested feature not available (VK_ERROR_FEATURE_NOT_PRESENT)
(in file /root/parts/rpcs3/src/rpcs3/Emu/RSX/VK/vkutils/device.cpp:423, in function create)
(in file /root/parts/rpcs3/src/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107, in function die_with_error)
Thread id = 139689307039040.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6782726/RPCS3.log)

#### 5. Please provide your system configuration:
* Ubuntu 20.4
* Intel i71065G7 8gb Ram
* intel iris Plus graphics
* Vulkan
* etc.

#### Please include.
* Your GPU driver does not support some required MSAA features.
Try updating your GPU driver or disable Anti-Aliasing in the settings.
Assertion Failed! Vulkan API call failed with unrecoverable error: Requested feature not available (VK_ERROR_FEATURE_NOT_PRESENT)
(in file /root/parts/rpcs3/src/rpcs3/Emu/RSX/VK/vkutils/device.cpp:423, in function create)
(in file /root/parts/rpcs3/src/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107, in function die_with_error)
Thread id = 139689307039040.

**Comment by MSuih** [comment]
> Try updating your GPU driver or disable Anti-Aliasing in the settings.
Did you try to disable antialiasing already?

**Comment by AniLeo** [comment]
User error, and using old build. It's automatically disabled on newer builds, but even on old builds the error is very clear.

**Comment by leonardojimenez1990** [comment]
@AniLeo, @MSuih Thank you. all right
