### ISSUE TITLE
Cannot build  on mac m1

### ISSUE THREAD

**Issue by czkboy** [RPCS3/rpcs3#10527]
## Quick summary
Cannot build  on mac m1

## Details

/Users/k/rpcs3/3rdparty/libpng/libpng/arm/arm_init.c:49:4: error: "PNG_ARM_NEON_FILE undefined: no support for run-time ARM NEON checks"
#  error "PNG_ARM_NEON_FILE undefined: no support for run-time ARM NEON checks"
   ^
1 error generated.
make[2]: *** [3rdparty/libpng/libpng/CMakeFiles/png_static.dir/arm/arm_init.c.o] Error 1
make[1]: *** [3rdparty/libpng/libpng/CMakeFiles/png_static.dir/all] Error 2
make: *** [all] Error 2

**Comment by AniLeo** [comment]
If you haven't noticed, Mac M1 isn't X86_64

**Comment by czkboy** [comment]
what a pity

**Comment by czkboy** [comment]
> If you haven't noticed, Mac M1 isn't X86_64

Can arm be supported？

**Comment by MSuih** [comment]
It won't be easy but it should still be possible. You just need to find someone who'd be both skilled and interested enough to figure it out.

**Comment by czkboy** [comment]
I use “cmake .. -DCMAKE_OSX_ARCHITECTURES="x86_64;x86_64h" -DCMAKE_BUILD_TYPE=Release” to build

**Comment by AniLeo** [comment]
Even regular X86_64 Mac build doesn't work. You need to use one of the supported OSes.
