### ISSUE TITLE
The Last of us on RPCS3 don´t run after compiling shaders

### ISSUE THREAD

**Issue by juliocl98** [RPCS3/rpcs3#10529]
I have installed The last of us on the emulator, it start compiling everything as always but when he start compiling the shaders just before showing the main menu it's blocks & stop working.

I have a:
Windows 10 v.21H1
Ryzen 5 5600x
Asus RTX 3070 (driver version 471.11)
16 gb ram memory

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6795824/RPCS3.log)

**Comment by RainbowCookie32** [comment]
Use [our discord server](https://discord.me/RPCS3) to ask for support.

**Comment by juliocl98** [comment]
Ok, i will, it should be on #help right?

**Comment by RainbowCookie32** [comment]
Yes. Close this issue as well, please.

**Comment by juliocl98** [comment]
Ok. Thanks for the help
