### ISSUE TITLE
Cannot build with system FAudio on Linux

### ISSUE THREAD

**Issue by Hirato** [RPCS3/rpcs3#10524]
Some recent refactoring allows building with the system faudio, instead of including it as a 3rd party submodule by specifying `-DUSE_SYSTEM_FAUDIO=ON` at build time
Unfortunately, doing so results in this error during the build process
	
	CMake Warning at 3rdparty/CMakeLists.txt:226 (find_package):
	By not providing "FindFAudio.cmake" in CMAKE_MODULE_PATH this project has
	asked CMake to find a package configuration file provided by "FAudio", but
	CMake did not find one.

	Could not find a package configuration file provided by "FAudio" with any
	of the following names:

		FAudioConfig.cmake
		faudio-config.cmake

	Add the installation prefix of "FAudio" to CMAKE_PREFIX_PATH or set
	"FAudio_DIR" to a directory containing one of the above files.  If "FAudio"
	provides a separate development package or SDK, be sure it has been
	installed.

The package does provide such files, however, the casing is different.

	/usr/lib/cmake/FAudio/
	/usr/lib/cmake/FAudio/FAudio-config.cmake
	/usr/lib/cmake/FAudio/FAudio-targets-release.cmake
	/usr/lib/cmake/FAudio/FAudio-targets.cmake

If I specify the correct filename with the `CONFIGS` option, i.e. `find_package(FAudio REQUIRED CONFIGS FAudio-config.cmake)`
I now get this new error, so some more work than just correcting the file path is required.
I however know nothing of cmake and have no idea how to do this.

	CMake Error at 3rdparty/CMakeLists.txt:358 (add_library):
	add_library cannot create ALIAS target "3rdparty::faudio" because target
	"FAudio" does not already exist.

**Comment by illusion0001** [comment]
#10397 might be culprit

**Comment by hcorion** [comment]
@p01arst0rm did you test this path?
Also, you didn't add the `target_compile_definitions(FAudio INTERFACE -DHAVE_FAUDIO)` to the system faudio if branch, so RPCS3 wouldn't even use it if it was fixed.

**Comment by p01arst0rm** [comment]
i did test it, but i must have forgotten to change that back when reverting the directory changes. Ill make a quick PR to fix :)

**Comment by p01arst0rm** [comment]
@Hirato you can also fix this quickly by renaming the config file to FAudio.cmake. what linux distro are you using?

**Comment by Shoegzer** [comment]
Confirmed, having faudio-related compilation issues here too.  CMake complains about SDL2 version:
```
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
CMake Error at 3rdparty/CMakeLists.txt:232 (message):
  -- RPCS3: FAudio requires SDL 2.0.9 or newer.
```
However, this test system exceeds the minimum version:
```
$ apt version libsdl2-2.0-0 
2.0.10+dfsg1-32.0.10+dfsg1-3
```
Testing with Linux Mint 20.2 / kernel 5.11 using gcc 11.1.0 and cmake 3.20.2.

**Comment by p01arst0rm** [comment]
> Confirmed, having faudio-related compilation issues here too. CMake complains about SDL2 version:
> 
> ```
> -- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
> CMake Error at 3rdparty/CMakeLists.txt:232 (message):
>   -- RPCS3: FAudio requires SDL 2.0.9 or newer.
> ```
> 
> However, this test system exceeds the minimum version:
> 
> ```
> $ apt version libsdl2-2.0-0 
> 2.0.10+dfsg1-32.0.10+dfsg1-3
> ```
> 
> Testing with Linux Mint 20.2 / kernel 5.11 using gcc 11.1.0 and cmake 3.20.2.

this error only shows if you arent building with the system version of FAudio. you need to reset your cmake cache or make sure to pass in the build arg

**Comment by hcorion** [comment]
Ensure you also have libsdl2-dev installed alongside libsdl2.

**Comment by Shoegzer** [comment]
@p01arst0rm Thanks, I should have caught that myself.  That said, my cmake cache was already reset (it was a fresh build to a new build dir).  Shouldn't cmake have completed successfully using 3rdparty faudio?   This issue has never occurred before and rpcs3 compiled successfully as recently as build 9b050a33e40cffa87e9385d73d5352c981e95982.

@hcorion Thanks, but that was installed as well.

**Comment by p01arst0rm** [comment]
i was also getting that error, untill i reset my cmake cache

**Comment by p01arst0rm** [comment]
might be a good idea to add a find package for system sdl2 just to make sure it doesn't fail if someone builds once then changes their arguments

**Comment by Shoegzer** [comment]
@p01arst0rm Thanks, though again I was building to a clean directory so cmake cache was already effectively reset.  Interesting that you had those results when not resetting though, not sure why I'm getting it here but any suggestions are welcome.

For what it's worth, I also observe the same issue as the OP above when setting `-DUSE_SYSTEM_FAUDIO=ON`
