### ISSUE TITLE
fatal error: flatbuffers/flatbuffers.h: No such file or directory

### ISSUE THREAD

**Issue by akaelover** [RPCS3/rpcs3#10532]
Hello, I am getting this error when compiling the program

FAILED: rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/Cell/lv2/sys_net.cpp.

In file included from /var/tmp/portage/portage/games-emulation/rpcs3-0.0.17-r1/work/rpcs3-0.0.17/rpcs3/Emu/NP/rpcn_client.h:20,
                 from /var/tmp/portage/portage/games-emulation/rpcs3-0.0.17-r1/work/rpcs3-0.0.17/rpcs3/Emu/NP/np_handler.h:11,
                 from /var/tmp/portage/portage/games-emulation/rpcs3-0.0.17-r1/work/rpcs3-0.0.17/rpcs3/Emu/Cell/lv2/sys_net.cpp:26:
/var/tmp/portage/portage/games-emulation/rpcs3-0.0.17-r1/work/rpcs3-0.0.17/rpcs3/Emu/NP/generated/np2_structs_generated.h:7:10: fatal error: flatbuffers/flatbuffers.h: No such file or directory
   
* OS:  Gentoo
* CPU: Ryzen 2700x
* GPU: GTX 1080
RAM:16GB 

I use this ebuild to compile
https://data.gpo.zugaina.org/tatsh-overlay/games-emulation/rpcs3/

**Comment by AniLeo** [comment]
This just seems to be a case of missing flatbuffers dependency on your system.
Nowhere in that build file is there any mention to flatbuffers.

**Comment by hcorion** [comment]
Closing as not our bug, it's an issue with your build script

**Comment by maxmadzz** [comment]
try use “stefantalpalaru” overlay,rpcs3 git version can be build
