### ISSUE TITLE
[Feature Request] "Always connected" virtual gamepads.

### ISSUE THREAD

**Issue by murtisoft** [RPCS3/rpcs3#10531]
_Please forgive me if this was mentioned before, couldnt find anything simiIar via search._

**Is it possible to implement an "always connected" feature for gamepads?**

Such a feature exists in other emulators including pcsx2 for example. The virtual PS3 will never know if a gamepad is disconnected or not, virtual gamepad will always stay connected and real connections will be handled entirely by the operating system.

**Comment by Mewtwo5555** [comment]
Yeah nice have might fix the  Simpsons game where need disconnected and reconnect the gamepad add always on gamepad then gamepad bug probably be fix

**Comment by Megamouse** [comment]
No. Because the Simpsons want the controller to be connected afterwards.

This feature doesn't make any sense. It's just bloatware in my opinion

**Comment by MSuih** [comment]
It can make sense for people who have faulty usb cables/connectors. If the controller gets disconnected even for a split second many games will pop up some kind of menu or dialog that pauses the game, which you will have to dismiss. Sometimes it'd be better to lose input for that split second if it means that you don't have to constantly close a dialog message.

But then again this issue could easily be resolved by getting a new cable or controller.

**Comment by elad335** [comment]
It makes some sense for poor bluetooth connection when you get too far the adapter as well. I don't say that it should always behave this way, just as an option requiring explicit enabling by the user.

**Comment by Megamouse** [comment]
With that logic we should also add an optional ultra performance mode, because some users might have old computers that don't reach 60fps in all games

**Comment by elad335** [comment]
We did, it's called "clocks scaling".

**Comment by murtisoft** [comment]
To be frank, I would like this feature mainly because of parsec arcade. This would allow any game to be drop in/drop out whenever.
Beyond that, I think of this as a quality of life improvement since this would allow you navigate 2 player menus without connecting a second controller first.

**Comment by Megamouse** [comment]
We probably need a fake input renderer for the second one.

But how does parsec work? Does it work as a xinput device or something similar?

**Comment by Sora3100** [comment]
Parsec uses ViGEm for it's input handling, it can either emulate a 360 gamepad (XInput) or a DS4 one (DirectInput).

**Comment by Megamouse** [comment]
This still doesn't explain why it needs the controller always connected.
Doesn't it just work like connecting any other controller?

**Comment by Sora3100** [comment]
I'm honestly not sure either, the controller gets connected when someone joining the session presses a button on their gamepad, and stays active until the application gets stopped (in the case of Arcade) or the host stops hosting (in the case of computer sharing)

**Comment by murtisoft** [comment]
It does work like connecting a regular xinput controller. Currently, everytime a player quits, the game gets paused because the controller was disconnected. Obviously it wont resume until another player decides to join and activate their controller. That can take up to minutes at a time.
Parsec Arcade allows random people to join your game. Some of these people just want to check out what you are playing for example, they might play for a minute and leave. That means constant interruptions. It gets even worse if you want to play 2+ players, but i didnt want to torture myself.
I managed to achieve something similar using Universal Control Remapper, Remapping xinput2 to xinput3, and using xinput3 for 2ndplayer. So xinput3 stays connected, and parsec assigns xinput2 to whoever joins. But that is a horrible duct tape solution that barely works.

**Comment by Megamouse** [comment]
Tbh this sounds more like something you should be able to configure in parsec

**Comment by murtisoft** [comment]
Yeah, I understand why you would say that. Thanks anyway.

**Comment by Darkhost1999** [comment]
I can argue both ways on this discussion.
I agree giving the user an option to say to their game that a controller is connected although the device status is disconnected is a great idea.

The argument is that the feature is practically useless even if your game is being interrupted by choosing to play with Parsec. Honestly I can't count the number of times a disconnected controller notification has "saved my life" in a game over a simple dead battery.
So given that the ps3 itself has a safety feature designed specifically with this type of feature request in mind. The request would be entirely bloat where there aren't enough benefits that I can think of.

**Comment by elad335** [comment]
I also think there should be an opposite feature as well: pause the emulation if any of the controllers got disconnected BEFORE even the game knows about it.

**Comment by Darkhost1999** [comment]
In hindsight. Shouldn't Parsec be implementing this feature?
Virtual gamepads always connected. So as to run a Dummy connection until a real controller connects.

**Comment by murtisoft** [comment]
> In hindsight. Shouldn't Parsec be implementing this feature? Virtual gamepads always connected. So as to run a Dummy connection until a real controller connects.

Parsec is already a flimsy program, and there is now a third party client doing what I asked.
But as I said, even though I asked for this for parsec at the time, this feature exists in many other emulators. ¯\_(ツ)_/¯
