### ISSUE TITLE
Skydive: Proximity Flight [NPUB30618] graphics issue 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#10534]
SYS: RPCS3 v0.0.17-12446-6a7324ab Alpha | HEAD
    SYS: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz | 8 Threads | 15.96 GiB RAM | TSC: 2.808GHz | AVX+ | FMA3
    SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 18363, Service Pack: none, Compatibility mode: 0
    RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1070' running on driver 471.11.0.0
    SYS: Firmware version: 4.88

it has this problem with the graphics 

![FPS_ 60 03 _ Vulkan _ 0 0 17-12446 _ Skydive_ Proximity Flight  NPUB30618  7_11_2021 7_36_38 PM](https://user-images.githubusercontent.com/45731484/125201307-9a287a00-e27f-11eb-9da6-99df062214a0.png)

![FPS_ 60 03 _ Vulkan _ 0 0 17-12446 _ Skydive_ Proximity Flight  NPUB30618  7_11_2021 7_36_50 PM](https://user-images.githubusercontent.com/45731484/125201314-9f85c480-e27f-11eb-84f3-97a4939dc5de.png)

capture file

https://drive.google.com/file/d/1hisN45ds5utIEIQefZvQGaxpWde0nrLd/view?usp=sharing

log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6797202/RPCS3.log.gz)

**Comment by benderscruffy** [comment]
still the same issue

**Comment by benderscruffy** [comment]
still the same issue

**Comment by Triticum0** [comment]
Seems to be rendering better
![NPUB30618_screenshot_2024_01_06_00_14_42](https://github.com/RPCS3/rpcs3/assets/71127352/6c41a2a2-702a-4cd7-b13f-b09d1a03d3aa)

Need updating or should be closed
