### ISSUE TITLE
Naruto Ultimate Ninja Storm 3 Issue: Game data must be installed on ps3 HDD

### ISSUE THREAD

**Issue by sriravela1607** [RPCS3/rpcs3#10535]
![image](https://user-images.githubusercontent.com/59233235/125216680-eaf29f80-e28c-11eb-9513-f4bc20957752.png)
This is the issue on Ultimate Ninja Storm 3 after successfully downloading and loading the game onto rpcs3. 

Log: 
![image](https://user-images.githubusercontent.com/59233235/125217179-0dd18380-e28e-11eb-8144-830c2bb8a5f2.png)

It does not let me choose YES or NO, so I am eternally stuck on that screen without any clue on what to do. 
How do I fix this? 

Specs: 
CPU - i7-10700K
GPU - Integrated Graphics UHD 750

**Comment by sriravela1607** [comment]
What do you mean by it has to be downloaded on a ps3 HDD, can i still download it onto rpcs3?

**Comment by sriravela1607** [comment]
Why did u close it?

**Comment by AniLeo** [comment]
Doesn't follow the repository issue guidelines
