### ISSUE TITLE
Go! Sports Ski™ [NPUA80070] yellow graphics issue 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#10533]
- SYS: RPCS3 v0.0.17-12446-6a7324ab Alpha | HEAD
- SYS: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz | 8 Threads | 15.96 GiB RAM | TSC: 2.808GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 18363, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1070' running on driver 471.11.0.0
- SYS: Firmware version: 4.88

The game is playable only it has this problem with the graphics maybe something to do with https://github.com/RPCS3/rpcs3/issues/10530 not sure

![FPS_ 60 18 _ Vulkan _ 0 0 17-12446 _ Go! Sports Ski™  NPUA80070  7_11_2021 7_01_55 PM](https://user-images.githubusercontent.com/45731484/125200192-e329ff80-e27a-11eb-9acc-fca6e2b1d932.png)

capture file 

https://drive.google.com/file/d/1m3AWUrk0iOMHZiu_tyMehVtqnt5wLdKI/view?usp=sharing

log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6797142/RPCS3.log.gz)

**Comment by benderscruffy** [comment]
still an issue
![Capture](https://user-images.githubusercontent.com/2696404/135595056-459005f2-be45-4c48-9656-a47bd8350400.PNG)

**Comment by nitroos-ai** [comment]
Retest please!

**Comment by benderscruffy** [comment]
RPCS3 Version: 0.0.25-14495-8ac99680 Alpha | master
this is still an issue

**Comment by Realmantik** [comment]
![go sports ski game](https://github.com/RPCS3/rpcs3/assets/22906342/69007c92-007b-4764-b82f-e5329fb73ecc)
Looks good now.
