### ISSUE TITLE
Cannot style QComboBox QAbstractItemView::item

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#10548]
I'm in the process of trying to create a nice, modern theme based on Envy, but I've hit a bit of a roadblock when trying to fix the combobox dropdowns.

From what I can tell from docs and random posts, you're supposed to style it using the following selector:
```css
QComboBox QAbstractItemView::item {
    /* my styling comes here */
}
```

The issue is, this doesn't seem to work out of the box, apparently. There's a [relevant SO thread](https://stackoverflow.com/questions/29939990/qcombobox-style-for-choosen-item-in-drop-down-list) about the issue, but sadly that's as far as I can understand what's going on. Seems like it needs to be adjusted from the codebase's side.

I'd need it to increase the line height for each item, and to alter the hover background color (as well as give them a border radius):

![image](https://user-images.githubusercontent.com/10439488/125777138-0c731b96-bf27-4bf4-abe1-341bd4070e5d.png)

**Bonus:** tips to restore the drop down arrow would be much appreciated, cause every time i touch the `background` property of `QComboBox::drop-down`, they die a quick death.

**Comment by Megamouse** [comment]
Any code? We can't fix what we can't see

**Comment by Megamouse** [comment]
Idk what you did to kill the arrow, but you can set the colors e.g. like this:
```
QComboBox QAbstractItemView {
	selection-color: black;
	selection-background-color: green;
}
```

Sadly changing the size of the items isn't possible without writing an rpcs3 wrapper for the QComboBox, which I think is just gonna add yet another annoying thing to look out for and that everyone needs to start using.
The easiest way would be to get Qt to fix it on their side, but this would mean you'd have to wait who knows how long until it gets added to some distant Qt version.

**Comment by dio-gh** [comment]
That does work for the colors, but yeah, I'd kinda need height too. I guess a no is a no, rip.

**Comment by dio-gh** [comment]
> Idk what you did to kill the arrow

Poked around some more, seems like you cannot touch the `background-color` or the `border` properties when using the `QComboBox::drop-down` selector. Guessing that's not expected behaviour?

Not sure if I should go bark at the Qt guys with this, I'd probably need to repro it on a minimal example that's not RPCS3.

**Comment by dio-gh** [comment]
Fixed it with hacks 😋 Beautiful, non-invasive hacks.

![image](https://user-images.githubusercontent.com/10439488/126022054-c4d52bf9-fd96-4f4d-b28d-d6e830d3e504.png)

The inability to change the height of each item in the drop-down, and the inability to make the drop-down's box-shadow disappear (and the corners to curve) is still kind of a blue ball, but liveable.
