### ISSUE TITLE
No game can boot after updating to version 0.0.17-12447-a34201eb Alpha

### ISSUE THREAD

**Issue by calvinvalerian** [RPCS3/rpcs3#10542]
Just updated few minutes ago to version 0.0.17-12447-a34201eb Alpha and none of my PS3 games can boot.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6813686/RPCS3.log)

VIDEO
https://youtu.be/vNwTB50y9-8

![Screenshot (186)](https://user-images.githubusercontent.com/18316781/125567397-a290ded7-d22a-453a-9cfc-f92327079f6b.png)

**Comment by MSuih** [comment]
Try to disable async texture streaming

**Comment by calvinvalerian** [comment]
Still not working

**Comment by calvinvalerian** [comment]
Does this happen to you too @MSuih?

**Comment by AniLeo** [comment]
> Failed to load node: YAML exception: yaml-cpp: error at line 1, column 3: unknown escape character: 

Bad config file

**Comment by calvinvalerian** [comment]
> > Failed to load node: YAML exception: yaml-cpp: error at line 1, column 3: unknown escape character:
> 
> Bad config file

What particular config file need to be changed?

**Comment by AniLeo** [comment]
One of the YAML files, log doesn't say, you can try removing the config files and have the emulator regenerate new ones, could also be some imported patch
This falls under support request, so submit a support request on the appropriate platform

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by calvinvalerian** [comment]
I have tried removing the .yml files and still don't work.

**Comment by calvinvalerian** [comment]
Okay finally I got it working. Reinstall.
