### ISSUE TITLE
Flatbuffers (AUR vs AppImage)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#10544]
Currently, RPCS3 builds with Flatbuffers 1.11.0
The rpcs3-git AUR builds with the latest version, currently Flatbuffers 2.0.0

This can be causing Networking issues on the AUR build that don't happen on the AppImage

We should ensure Flatbuffers parity between AUR and AppImage by either:
1. Updating flatbuffers submodule to 2.0.0 and regenerating the precompiled headers
2. Having the AUR build 1.11.0 and use that instead

**Comment by hcorion** [comment]
I'll change the AUR build to use the submodule 1.11.0, though it does make sense to update our submodule to 2.0 since we allow building with system flatbuffers, this issue will keep coming up unless we update it.
Are there any issues for doing that?

**Comment by AniLeo** [comment]
Flatbuffers have been updated to 2.0.0 already on RPCS3, latest version currently available on arch is 2.0.6

**Comment by RipleyTom** [comment]
Updated to v2.0.6 with https://github.com/RPCS3/rpcs3/pull/11870 .
