### ISSUE TITLE
Vulkan option not available after certain circumstances

### ISSUE THREAD

**Issue by Buba98** [RPCS3/rpcs3#10550]
On my laptop (Windows 10), but most probably on any systems that rely on multiple GPUs, after an update of the driver of my graphic card, the discrete GPU and Vulkan rendering option is no longer available. In my case, with an integrated GPU + a discrete NVIDIA GPU.  In order to make the GPU and the Vulkan option appear again, it is required to disable the internal GPU from the device manager (with RPCS3 closed) then enable it again. Now, when I start RPCS3 again, the discrete GPU is again available as well as the Vulkan rendering option.

**Comment by kd-11** [comment]
This can only mean the iGP does not support vulkan, if it does, both GPUs are available. We do not implement the vulkan loader, that part is done by Khronos. However, windows has GPU allocation if you're using something like optimus. That is, the application will not even be able to see the dGPU unless you add a power plan for rpcs3.exe. The same should happen with vulkan tools (e.g vulkaninfo) that rely on the official vulkan loader.
I would start by running vkdiag (see https://github.com/13xforever/vkdiag/releases) and vulkan samples from the official tools repository at https://github.com/KhronosGroup/Vulkan-Tools/releases specifically the cube.exe and vulkaninfo.exe and see if they are able to see your dgpu by default.
