### ISSUE TITLE
the new repo name, coverage, orphis

### ISSUE THREAD

**Issue by Syphurith** [RPCS3/rpcs3#1055]
I've seen those in [`citra-emu/citra`](https://github.com/citra-emu/citra) making travis-ci and appveyor build - and upload those through ftp. their `.travis.yml` was changed so that many commands could be done in several seperate shell scripts.
So they don't need standalone buildbot.
The repo name of rpcs3 was changed from `DHrpcs3/rpcs3` to `RPCS3/rpcs3`, thus broke some connections between the repo and formly registered webservice (such as appveyor and coverall.io). I don't know whose account that used in those registeration form, I would just report this and be quiet.
BTW i don't know where else was effected by this.

```
$ if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then coveralls --extension .c --extension .cpp --extension .h; fi
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
{u'message': u"Couldn't find a repository matching this job.", u'error': True}
```

Seems coveralls failed just related to the new name.

**Comment by Bigpet** [comment]
I think we can delete the appveyor script, it never really worked out well for us, we always exceeded built-times (partially because it took so long to clone dependencies like wxWidgets). If we need windows build then I think we can still use the server Orphis offered us so graciously (which we never really did much with)

**Comment by Syphurith** [comment]
Well, so appveyor support may be removed now. How about their FTP built binary to their sever?
BTW, Coverity and Coveralls seems .. duplicate?

**Comment by Bigpet** [comment]
Yeah, I'm not really sure what the point of coveralls was (and I haven't looked into coverity either). So maybe the people that merged those can tell you about that.

Not sure what you mean about build binary. I don't think we have an FTP setup anywhere to host builds.

**Comment by Syphurith** [comment]
@Bigpet Oh well. Still trying to deal with the git-version-gen.cmd

**Comment by Syphurith** [comment]
@Bigpet Had a try to investigate those projects orphis hosts, it seems to be not a fully automatic way.
Humanly speaking, the repo seems not include the full instructions for buildbot to start.
From [PPSSPP#70](https://github.com/hrydgard/ppsspp/)

*The server is accessible there: http://teamcity.orphis.net and you can see the build log and test result for all the platforms (although the tests don't run on Android yet)*

So orphis is using teamcity for CI. And..

*No worries!
What I do is creating a new branch with my new changes and rebase this one only on top of master, then make a pull request from it. And you don't do any real work from it except force pushing changes when reviews are done.*

Seem easy? But i think we would have to contact **Orphis** to get more "how-to" for setting up.

**Comment by Bigpet** [comment]
@Syphurith I don't think you understood right, we already got login credentials for his teamcity server and it used to build just fine, but since we had no host for the builds I didn't know where to upload them. Also it just builds things after they're merged, so it wasn't workable as a CI integrated into Github

**Comment by Syphurith** [comment]
@Bigpet Well. So let me regard orphis not to be a CI.
Have read a bit about the coverage, i think that is test related. The coverage tools shows us how much possibility of each part not to be called. [MSDN](https://msdn.microsoft.com/en-us/library/jj159523.aspx) and those are classified as Unit-Test tool.

**Comment by paulsapps** [comment]
This is an example of what coveralls gives you: https://coveralls.io/r/paulsapps/SUDM and of course a % covered badge.

**Comment by Syphurith** [comment]
@paulsapps Thanks for your info, ~~however the development for main branch and features is somehow halted now here~~. Still you can try to create a patch for this repo. Many thanks.

**Comment by tambry** [comment]
Is this still relevant, or can it be closed?
