### ISSUE TITLE
BLES01190 - Dead Space 2 Working playable

### ISSUE THREAD

**Issue by Zkrapper** [RPCS3/rpcs3#10567]
Noticed that this title wasn't in the compatibility list and just wanted to report that this game is fully playable.
I experienced a few crashes along the way but this was often during highspeed cutscenes or more intense graphical load (during end-game for example) also experienced well-known glitch on Chapter 13 with disappearing battery cell. (but this is sometimes to be expected anyway)
Overall I appreciate the work you put in to this project and many thanks for enabling me to play this PS3 classic :)

i7-7700HQ @ 3.8GHz (Laptop)
16GB GDDR4
GTX 1060 6GB

**Comment by Megamouse** [comment]
Thanks, we appreciate it.

But github is not the place to report this. Use the rpcs3 forum instead.
