### ISSUE TITLE
[Feature Request] Support for custom LUT

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#10564]
I don't feel like using reshade just for a LUT. So native support would be awesome.

Should work just like reshade, where you have a neutral lut in png format, apply your color correction to it via photoshop or other such software, and apply that lut via RPCS3.

**Comment by dio-gh** [comment]
Sorry to hear that, but personally, I disagree. Features like this imo are feature creep, and belong to ReShade or similar injectors.

**Comment by lextra2** [comment]
How is it feature creep if most other emulators support shaders without reshade?

**Comment by dio-gh** [comment]
I don't see why it would stop being a feature creep just because numerous other products decide to include it.

Unless an integration can offer a higher fidelity and more elaborate shader injection, I don't see the point. May as well include the entirety of ReShade in-tree then.

**Comment by lextra2** [comment]
Well, just adding ReShade to rpcs3 would indeed be bloat.
The lut is basically just an overlay. No need to have something complex like reshade be added just for that.

Think of it like resolution scale or the fps monitor. Both of them are technically "feature creep" but very nice to have.

Having native support to load a lut should be very minimal to implement, with basically no performance penalty (0.02ms in reshade) and can make for a nice visual upgrade.

**Comment by dio-gh** [comment]
Resolution scaling is a complex feature, and heavily dependent on the emulator. There's merit to having it integrated, to the extent that frankly, I'm not even sure if it could be done through external means.

The fps monitor is a much better point, matter of fact, the feature creep discussion did pop up when it was still just in plans. The monitor osd itself however also displays information you cannot get with external tools, namely the load distribution between the various components (PPU, SPU, RSX). This makes it a more insightful performance metric overlay than any external tool could be.

Though if I think about it, maybe it could fit in the future. There are plans for texture and shader replacement for example, at which point adding a feature like this would be perfectly fitting and fine. It could also offer you better results.

But on it's own, I'm not so sure. (This is just my take though.)

**Comment by lextra2** [comment]
It is a fair point. And keeping an eye on feature creep is a good thing.

**Comment by kd-11** [comment]
Closing, we'll not be supporting and maintaining fully customizable post-processing suites any time soon.
