### ISSUE TITLE
[Regression][Linux] Extremely slow save op IO

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#10573]
Seems to be an extension of https://github.com/RPCS3/rpcs3/issues/9857
Affects linux only afaict. I have the dev_hdd folders mapped to an NTFS drive which probably makes the issue possible. The freezing lasts from about 5 seconds to over 15 seconds in the worst cases. This test uses Dark Souls II (NPUB31358) and is unplayable due to this freezing. The game autosaves very often just like DeS and all the other games in the series.

Excerpt when the freezing happens:
```
W cellSaveData: savedata_op(): Fileop: file="USER.DAT", type=0, op=2
W cellSaveData: savedata_op(): Fileop: file="2USER.DAT", type=0, op=1
W cellSaveData: savedata_op(): Fileop: file="04USER.DAT", type=0, op=2
W cellSaveData: savedata_op(): Fileop: file="204USER.DAT", type=0, op=1
W cellSaveData: savedata_op(): Fileop: file="0EUSER.DAT", type=0, op=2
W cellSaveData: savedata_op(): Fileop: file="20EUSER.DAT", type=0, op=1
```

Ryzen 1700
Arch, Kernel 5.12.7
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6836070/RPCS3.log.gz)

**Comment by elad335** [comment]
Retest with #10574

**Comment by kd-11** [comment]
It still freezes unfortunately, although not as severe. The wait time is down from 10+ seconds to about 5 but still not serviceable.
It is a sync() somewhere, very likely in pending_file::commit. I had just NOP'ed unix_file::sync for my gameplay and that hid the issue successfully.

**Comment by kd-11** [comment]
Removing the sync() in pending_file::commit does drop the freezing down to sub-1s but still feels very stuttery. Not sure which approach is the most compliant here since a pending file I assume must always exist on disk.
I'll see if I can optimize it a bit.
