### ISSUE TITLE
Minecraft doesn't load

### ISSUE THREAD

**Issue by GYKgamer** [RPCS3/rpcs3#10570]
I got Minecraft ps3 version and I wanted to use rpcs3 to play it but when I load it it just crashes rpcs3 and doesn't load any game.
I tried and waited for Minecraft to load, I've even tried changing the settings but that didn't even work please give me any fix thanks.

**Comment by GYKgamer** [comment]
Please can someone help its my first time using rpcs4

**Comment by clienthax** [comment]
![image](https://user-images.githubusercontent.com/1056270/126067161-4c8822a6-53d3-4460-ae8e-bfcf0b9b0bd2.png)

**Comment by GYKgamer** [comment]
thanks
