### ISSUE TITLE
[Feature Request] Mounting Updates/DLC from PKG without installation

### ISSUE THREAD

**Issue by galano6** [RPCS3/rpcs3#10584]
**Quick summary**
"Mounting" game updates and DLCs from PKG files without installation.

**Details**
Would it be possible to "mount" PKG (PSN Games and/or DLCs and Updates) files instead of installing them?

For example you could start a game directly from the PKG file and if there are any files that are required to be written on the HDD, then those files (and only those files) would be saved  in /dev_hddX/.  The rest of the files would be dynamically linked to files inside PKG and accessed directly from PKG so the emulator would "think" that all the files are in the correct directory.

Another example would be "mounting" updates. Some update files are massive in size and installing them all takes a lot of space. Instead you could just link them (in order, if required by the game) and access the files directly from PKGs. I know some updates need to be installed in specific order and maybe it would be possible to "merge" and "mount" all PKGs at the same time as a virtual /dev_hddX/ folder, so the file structure is like on the real PS3. Again, all files that would have to be written would be written in the "real" /dev_hddX/ and in the end you would have a virtual /dev_hddX/ directory, which would be a combination of the "real" /dev_hddX/ install directory and read-only data files from all the selected PKGs.

Same goes for DLCs. TLOU DLC is about 5GB. I only have the main game on disc and bought the DLC as an addon from PSN, so I don’t own the standalone version of Left Behind, therefore I have to install this huge PKG and it basically takes double the space (PKG file/backup + installation, which is about 10GB in total). If I could just "mount" the PKG it would save me 5GB. And that's only for one game.

**1. Please describe, what part of RPCS3 would be affected by your feature:**
* Patches
* Installation

**2. Please tell us, why your feature is important to RPCS3.**
1. That would save a lot of disk space. 

2. It would greatly benefit compatibility with game launchers such as Playnite or Launchbox, because you would link them to PSN PKG files directly and not to your RPCS3/ dev_hdd0/ folder where the games are installed, which would be great if you decided move your RPCS3 folder. With this feature you wouldn’t have to change the path in the game launchers every time you move/reinstall RPCS3.

**3. Please attach screenshots of the feature implemented in other projects.**
There’s already an emulator that does exactly that and I think it’s a great feature. You can see it in this video by BSoD:

https://youtu.be/EqkW61NjDpU?t=541

**Comment by elad335** [comment]
That's nice and all but there is only one problem: that only works for read-only files and files on /dev_hdd0 are writeable.

**Comment by dio-gh** [comment]
I don't see how that is an issue, could just copy/write files that are modified to the real folder then, as needed.

Hauling around PKGs is a massive pita. Didn't know this ticket existed, I'd like it to be extended for whole games also.

**Comment by clienthax** [comment]
Wouldn't having 10 update pkgs for example take more space than just installing them and deleting the pkg?
I don't see the point of this feature

**Comment by elad335** [comment]
PKG file contents are alsi encrypted, runtime decryption on the file can be very slow.

**Comment by dio-gh** [comment]
This is a preservational issue. You want the PKGs preserved, but you also want to use them. This means having to double up on space.

As for speed, I've only ever tested the sequential extraction of PKGs, those seemed to be well above the speed of the PS3 HDD. I'm not sure about the throughput with the decryption overhead present, nor during random accesses. Would need testing.

**Comment by Megamouse** [comment]
I'm with clienthax. I'd rather just install all files and have a fast experience than keeping hundreds of pkgs around.

It would also be a nightmare. You would have to know which update package contains which file and which is the latest and so on. And you'd have to know which game uses which package.

So no.

**Comment by clienthax** [comment]
+ for preserving storage isn't exactly expensive these days

**Comment by dio-gh** [comment]
Again, I'd prefer this for whole games personally. Not updates.

**Comment by Megamouse** [comment]
What if it modifies all files and you end up with double the space anyway?

**Comment by Megamouse** [comment]
What if it modifies all files and you end up with double the space anyway?

**Comment by dio-gh** [comment]
I'd be impressed.

**Comment by elad335** [comment]
If it was for other simple file formats such as TAR it could have been beneficial, but it isn't.

**Comment by MSuih** [comment]
I think this conversation has run it's course. If someone wants to fiddle with emulated file system then I'd recommend spending time on implementing ISO/CHD support instead of this.

**Comment by elad335** [comment]
I didn't say decryption doesn't exist I said it's slow.

**Comment by elad335** [comment]
> You really want to redownload all the patches after you delete the game and then decide to play it again? And what happens when Sony finally pulls the plug on PS3 games/DLC/Updates?

I don't understand this argument. Data is data whether it is in multiple packages or in a single directory it represents the same thing, if you're afriad from PSN store shutdown then keep either of them or both.

**Comment by galano6** [comment]
>I didn't say decryption doesn't exist I said it's slow.

I didn't say that either. I thought that encrypted NSP files work with Ryujinx and it's not slow (at least I didn't notice any slowdowns), so it should be at least similar with RPCS3. But again, I don't know, I'm not a programmer. If I were, I'd write code for PKG mounting myself :)

>Data is data whether it is in multiple packages or in a single directory it represents the same thing,

I understand that there are people who have all their PS1, PS2, PS3 ISOs/ROM/s/documents/game files mixed up in one directory (probably on their desktop :) - I know a lot of people with their "entire PC" on their desktop) and that's ok. But there are also people who like their ISOs/PKGs organized. That's all there's to it. 

Keeping both files (PKG and installed) is the main reason I made this feature request - it's not effective to keep the PKG and install the PKG. I'd like to do it Ryujinx way - keep the original PKG and mount it, so it takes less space and is a tidy way to keep your files organized.

**Comment by Megamouse** [comment]
Tbh, at this point out could ask gaben to skip installing games on steam just have a single file.
But that's not how it works does it?

**Comment by elad335** [comment]
PKG is not a compressed archive, it doesn't really make a real world difference in disk space.

**Comment by galano6** [comment]
>Tbh, at this point out could ask gaben to skip installing games on steam and just have a single file.
But that's not how it works or is it?

You download the games directly to your PC. You don't have installers and you don't install games from installers, like in times before digital distribution. And even then, game installers were on CDs/DVDs. You completely miss the point of this feature.

>PKG is not a compressed archive, it doesn't really make a real world difference in disk space. 

That's also part of the problem - they are not compressed. So if you have 1 GB PKG game and want to install it, the PKG + installed files = 2 GB of storage space. Now you can delete the PKG or keep it for the future. If you delete it, nothing changes for you, the game still occupies 1 GB. If you want to keep it, you lose 1 GB of storage space. With this feature implemented, it would be only 1 GB as PKG would be mounted (again, I think most of the files inside the PKG are assets, so files you'd have to write are probably few MB in size). So for people who don't care about PKGs lose nothing, the game still occupies 1 GB after they delete the PKG. For people who want to store their PKGs for the future, it would also take only 1 GB instead of 2 GB. So everybody wins.

But we can discuss it for hours. What's important is this - is it even be possible? It would be nice if RPCS3 coders could shed some light on the matter. Because if it's completely impossible, then no point in wasting time for further discussion.

However, if it looks like something that could be implemented fairly easy, then why not?
