### ISSUE TITLE
Sly 4 stops on startup with VM: Access violation reading location 0x0 (unmapped memory) [type=u32]

### ISSUE THREAD

**Issue by nitram3** [RPCS3/rpcs3#10583]
Quick summary
When starting Sly 4, emulator freezes on SPU cache building. This error is displayed in the console: VM: Access violation reading location 0x0 (unmapped memory) [type=u32]

Details
When starting Sly 4, emulator freezes on SPU cache building or in the case of deleting all caches first, on compilation of PPU modules (screenshots of both cases included). This error is displayed in the console: VM: Access violation reading location 0x0 (unmapped memory) [type=u32]. I've tried running the game both on default config and on recommended config for this title. I'm not sure if this is only happens with this game since it is the only one I own.
The problem was also present on an older graphics driver but I don't know the version of it unfortunately.

RPCS3's log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6840600/RPCS3.log)

Screenshots of your problem
![rpcs3_xlDuJPUVbb](https://user-images.githubusercontent.com/80164065/126157494-a47f9da0-b909-4028-8215-d44ed1f26a0a.png)

![rpcs3_NbWzahS3kL](https://user-images.githubusercontent.com/80164065/126157517-dc9d9e41-d3b3-442a-bafc-66c31fcf5be7.png)

![rpcs3_BFdE25TEBL](https://user-images.githubusercontent.com/80164065/126157527-c2ec6939-6f71-4a7a-a192-f25e162a4acd.png)

System configuration:
OS: Windows 10 pro v21H1  build: 19043.1110
CPU: i7 4790k
GPU: gtx 1660 ti
Driver version: 471.11

**Comment by YuriNator557** [comment]
You should not put the game folder into dev_hdd0/game, please move it out of there and put it somewhere else.

If you need further support, please join the Discord server and ask there.

**Comment by nitram3** [comment]
I installed this game from a .pkg file, and based on the RPCS3's quickstart guide, \dev_hdd0\game\ is the default installation destination.
So I feel this is an emulator issue.

**Comment by RainbowCookie32** [comment]
Yet your game has the serial of a disc game, which are not installed from .pkg files.
So I feel this is a pirated game issue.

**Comment by Yoshi9800** [comment]
@RainbowCookie32 he is useing driver 471.1 which is broken. So probably try downgrade the driver know work with rpcs3.
@nitram3 for you fix bug with sky 4 downgrade your driver to 467 to 469. Or wait to see if 472 fix it

**Comment by Megamouse** [comment]
Obviously broken pirated version
