### ISSUE TITLE
The Config and Pads buttons are confusing

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#10592]
This is a well known UX issue.

The Config and Pads buttons at the top are global-only, which often causes people to keep wondering why their config changes are not taking effect.

The current layout also makes it difficult for people to notice that custom configs exist, as they are tucked away into the right click context menu of the game list.

Another tidbit that could be argued is that the "global configuration" name is a misnomer, since it is not that; it is the *default configuration*. It's only *global* if no custom configurations exist.

This ticket is a tracker for potential resolutions to this issue.

Current possible resolutions are:
- pop-ups on first interaction with either type of configs [by asinine]
- drop-down list offering both kinds when a game is in selection [by asinine]
- having icons for both the "global" and the custom configs up at the top [by asinine]
- making the icons up top completely bound to the games (always a custom config), and tucking away the "global" config into the navbar at the top [by dio]
- pop-ups on game boot, conditionally [by mega]

**Comment by Asinin3** [comment]
The only confusing thing I see for users is when they create a custom config without understanding how it works. And that the main settings button won't affect games with a custom config. For most users, they don't create a custom config so it doesn't matter for them.

The best way to address this imo, is with a simple dialog pop-up when making your first custom config. (maybe scan custom config folder and see if there's already a file in there before prompt appears?). And just have it say something like:

> This will create a custom configuration for GAMENAME. If you make any changes here and save, then all future setting changes will have to be done here as it will not be using the global configuration. Custom configurations can be removed by right-clicking a game with the ICON icon.

Never seen people run into the pad settings because almost no one creates custom pad settings for games.

**Comment by dio-gh** [comment]
> For most users, they don't create a custom config so it doesn't matter for them.

I'm not sure this is true, per-game configs are a highly coveted feature at PCSX2 for example. Games often need special tending to, so custom configs are basically a necessity. Especially in lieu of automatically set recommended configs.

> because almost no one creates custom pad settings for games.

It's a necessity if you want to use KB+M.

**Comment by Darkhost1999** [comment]
When I first started using rpcs3 I didn't even know that custom configs were a thing. So to have to create a custom config just to get a "warning" message not only would've been like um...? What did I break? But upon reading it the first thoughts are. Why didn't the global config tell me that custom configs even exist at all? Why isn't there a drop down tab in the top bar of global config to choose <game serial> [game name]?
And this might be a solution.
Global configs informing in a short sentence about custom configs exist. And a drop down tab to edit each games configs. With apply, apply all, cancel, cancel all, and save, save all buttons.

With gamepads I still don't see much of an issue other than that people might wish to be informed that custom gamepad configs exist. It should require some brain cells to know that global can't overwrite custom.

**Comment by Asinin3** [comment]
Another suggestion would be: If the user has a game selected it will give two drop-down buttons. "Open Global Settings", "Create/Change custom config for selected game". If a game isn't selected, either just open global or grey out the second option. If you do click the create custom settings button then the warning from above will appear.
 
 This addresses the issue of users not knowing it exists, and the warning tells people how it works.

**Comment by lextra2** [comment]
For the custom config part, make a window pop up once the user opens the config window.
IMO it should say something like:
`Did you know? You can create individual configs for each game.
To do so, right-click on the game and select "create a custom config".`
And give the pop-up the "Do not show again" checkbox.

**Comment by Megamouse** [comment]
Why not just add a dialog that asks on every boot unless you explicitly boot the game from the context menu or unless you disable the dialog

**Comment by dio-gh** [comment]
Do you make that decision that often? As in, the decision of booting with the ""global"" or the custom config.

If not, especially if extremely not, then the idea of making people do it anyways is probably not a sound one.

**Comment by Megamouse** [comment]
I'm not the one who has troubles with it.
I'd just disable it and basta

**Comment by dio-gh** [comment]
Disable what? The way I put it in the OP as per my idea?

**Comment by Megamouse** [comment]
The dialog I just mentioned.
I'm not gonna explain what basta means.

**Comment by dio-gh** [comment]
Let's think it through.

So there's an issue, where people keep modifying the ""global"" config, in the presence of a custom config, making their changes are not take effect.

If there was a dialog popping up on every game boot, asking people what they want to pick, then as I highlighted, the frequency of that would greatly overshoot the actual number of times they want to make that decision. This means that if you also provided them with a "disable this dialog" option, that would remember their pick, and the issue would come back in full force.

If they decide to make the "go with the global cfg" option remembered, you killed the custom cfg feature. If they decide to make the "go with the custom cfg" option remembered, then UX issue remains. It achieved you nothing, just more frustration.

It's not that the idea of a popup dialog would be inherently bad though. Your idea made me think of a solution, where a popup you described would be triggered (*without the ability to disable it*), **only** if:
 - there was a modification made to the ""global"" config AND there was a custom cfg present
 - OR if there was a modification made to the custom cfg AND the last boot was forcefully made with the ""global"" cfg (through the dialog or the context menu)

This would cover all bases, and only present the user with a decision, when there's actually a decision to be made. I'm adding it to the original post above, as one of the possible resolutions.

**Comment by Darkhost1999** [comment]
I believe the point of having a global config is to have the ability to adjust settings used in every single game on your list. Whereas there's only a small handful of games I only need to configure 1-3 settings for specifically for an individual game.
If I'm forced to see a dialog box every time I boot a game simply because I want high resolutions and/or my emulator tab options to apply globally to all of my configs. I'd hunt every single rpcs3 file to forcibly disable the box.

Although, I am beginning to think we're putting a lot of time and thought into discussing solutions that could simply benefit making a Full RPCS3 Guide (with pictures and videos) to replace the Quickstart Guide where someone adds information like How to Configure Pads or How to Configure Settings.
If anyone doesn't read the guide than they're simply beyond anyone's help.

Any and all nonsensical settings, information, etc deemed worthy of being called nonsensical can simply just be explained to make sense through the guide.

**Comment by dio-gh** [comment]
btw mega

> I'm not the one who has troubles with it.

it's hardly a me issue either:

![image](https://user-images.githubusercontent.com/10439488/127713073-5fb6269a-dc5d-484c-b7ff-2f0ef3946381.png)

Gonna wait out Aug 5 (end of the survey) though, then I'll just pick an option of the many and make that as the feature request. No discussion is being had anymore anyways.

**Comment by dio-gh** [comment]
Won't update or track this ticket anymore. Please pick any one of the possible resolutions and/or close. Unsubscribing.

**Comment by Megamouse** [comment]
I feel like this discussion has gone stale.
There's always the possibility to open a new ticket, if someone has some specific idea.
