### ISSUE TITLE
Exiting fullscreen mode on a High DPI screen does not scale or fit to screen correctly.

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#10594]
When exiting from full screen mode no matter double click or alt + enter. I am no longer greeted with a title bar and this has made closing a game really annoying that it has pushed my last nerve into reporting this issue. I am using a High DPI screen so be aware of that if trying to reproduce. You absolutely can not reproduce this issue with windows scaling at 100%. I have found the regression in which shown below the issue began. If you look at the images you will be able to identify everything that I am able to describe. The error only occurs when toggling out of full screen irregardless of any settings at all. That does mean that the emulator tabs option for boot game in full screen has no effect on the issue.

RPCS3 Version: 0.0.15-12025
![image](https://user-images.githubusercontent.com/60384196/126337322-e58ff370-edbf-432f-bd61-78e98c3326ac.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6848992/RPCS3.log)

RPCS3 Version 0.0.15-12026
![image](https://user-images.githubusercontent.com/60384196/126337543-7add27f5-0cc4-41b4-911c-1b52ebcafa14.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6848999/RPCS3.log)

`There is of course a WORKAROUND to the issue. Not a fix.`
I did some testing to find things that work and things that do not.
*At 720p everything works with recommended scaling of 100%
*At 1080p recommended scaling is at  150% and is broken until changed to 100%
*At 4k the recommended scaling is at 300% broken until lowered to 200% or lower.
all other tests and resolutions or scaling I found to be over tedious and can provide more info if needed.

Let me know if there is anything that I can possibly provide that may help.

**Comment by Darkhost1999** [comment]
I did want to add that I first noticed this issue on Windows 10. The fact that I am using Windows 11 in these screenshots is irrelevant to my tests.

**Comment by Megamouse** [comment]
Try changing the rounding policy (cli arg)

**Comment by Darkhost1999** [comment]
Can I get a tutorial on how to?

**Comment by Megamouse** [comment]
For example run it with
--dpi-rounding 2

You can choose a value from 1 through 5.
 
See here:
![Screenshot_20210720-183109](https://user-images.githubusercontent.com/23019877/126361629-060c0e19-94de-4d5e-b496-8820b47a1170.png)

**Comment by dio-gh** [comment]
1 to 5 throws errors in the log..

**Comment by Megamouse** [comment]
Interesting error you got there.
It would be a shame if you shared it

**Comment by dio-gh** [comment]
![image](https://user-images.githubusercontent.com/10439488/126362273-864185ab-7ca1-493d-8001-8cdb640b2820.png)

**Comment by Darkhost1999** [comment]
Fixed #10596
