### ISSUE TITLE
[Linux] Build fails due to FAudio / SDL2

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#10597]
RPCS3 currently cannot build in linux due to FAudio / SDL2.  Build fails whether or not  `-DUSE_SYSTEM_FAUDIO=ON` is specified.
```
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
CMake Error at 3rdparty/CMakeLists.txt:232 (message):
  -- RPCS3: FAudio requires SDL 2.0.9 or newer.
```
However, this test system exceeds the minimum version:
```
$ apt version libsdl2-2.0-0 
2.0.10+dfsg1-32.0.10+dfsg1-3
```
A bisect was performed on this issue, ensuring a clean build directory/cmake cache each time. It seems #10397 is the cause. Results from the final bisect run:
```
CMake Error at 3rdparty/CMakeLists.txt:232 (message):
  -- RPCS3: FAudio requires SDL 2.0.9 or newer.

-- Configuring incomplete, errors occurred!
See also "/home/testing/Desktop/rpcs3/build/CMakeFiles/CMakeOutput.log".
See also "/home/testing/Desktop/rpcs3/build/CMakeFiles/CMakeError.log".
testing@venus:~/Desktop/rpcs3/build$ cd ../rpcs3/
testing@venus:~/Desktop/rpcs3/rpcs3$ git bisect bad
285b9dad833fbeb8cb9db2033217f544db9f01e9 is the first bad commit
commit 285b9dad833fbeb8cb9db2033217f544db9f01e9
Author: polar <polar@ever3st.com>
Date:   Thu Jul 8 20:31:45 2021 +0100

    Refactor faudio submodule (#10397)
    
    * updated bad header import
    * added faudio shared library option

 3rdparty/CMakeLists.txt                | 13 +++++++++----
 rpcs3/Emu/Audio/FAudio/FAudioBackend.h |  2 +-
 2 files changed, 10 insertions(+), 5 deletions(-)
```
Information:
* OS: Linux Mint 20.2 / kernel 5.11
* GCC ver: 11.1.0
* CMake ver: 3.20.2 
* Commit tested: 1d85c9d2010d0a9b905b88cedcc62a4036cfa00b
* [Build Log](https://github.com/RPCS3/rpcs3/files/6852775/build.txt)
* [CMakeOutput.log](https://github.com/RPCS3/rpcs3/files/6852688/CMakeOutput.log)
* [CMakeError.log](https://github.com/RPCS3/rpcs3/files/6852689/CMakeError.log)
* [CMakeCache.txt](https://github.com/RPCS3/rpcs3/files/6852765/CMakeCache.txt)

This information was originally posted to #10524 though this report was made since that one was unrelated and closed.  @p01arst0rm your assistance would be welcome, thanks.

**Comment by p01arst0rm** [comment]
on it. could you please send version info for FAudio, SDL2, gcc, cmake. could you also confirm that you've hard reset the repository and started with a clean cmake cache.

**Comment by p01arst0rm** [comment]
@Shoegzer I cannot reproduce any kind of error with the build; SDL2 and FAudio are linked correctly and RPCS3 runs just fine. I need more information about your build environment

**Comment by Shoegzer** [comment]
Thanks much @p01arst0rm.  Below is the information you asked for (and all related cmake and build logs are posted above) but I'm happy to provide anything else you need.  

On resetting the repository and starting with a clean cmake cache - all I do is simply delete the rpcs3 build directory entirely, and retrieve the entire repo again.  That should be sufficient right?  Or is something else needed?

```
$ apt version libfaudio-dev
20.04-2

$ apt version libsdl2-dev 
2.0.10+dfsg1-3

$ gcc --version
gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0

$ cmake --version
cmake version 3.20.2
```

**Comment by Shoegzer** [comment]
Update: I did some more digging and discovered that CMake had been reporting `-- RPCS3: FAudio requires SDL 2.0.9 or newer.` since before #10397 was merged.  However, that PR adds `FATAL_ERROR` to the `SDL2_VERSION` requirement which now causes CMake to fail.

I then added two status messages to the new `3rdparty/CMakeLists.txt`, as follows:
```
if (NOT SDL2_FOUND OR SDL2_VERSION VERSION_LESS 2.0.9)
   message(STATUS "SDL2 Found: ${SDL2_FOUND}")
   message(STATUS "SDL2 Version: ${SDL2_VERSION}")
   message(FATAL_ERROR "-- RPCS3: FAudio requires SDL 2.0.9 or newer.")
```
I then ran CMake - results from terminal:
```
-- SDL2 Found: 1
-- SDL2 Version: 
```
So, apparently it's finding SDL2 but not obtaining its version info, the latter triggering the `FATAL_ERROR`.  This is odd considering that the test system is a recent fresh install and uses the default Ubuntu repo SDL2.  

How are you resetting the repo and cleaning the cache, is it any different from what I stated in my previous post?  Also, what distro are you using?  If it's Ubuntu or derivative then I'm thinking CMake will fail on those systems as it stands now.

Again I'm happy to run more tests, get more info or help dig into the code some more if needed.  @hcorion any assistance or thoughts of your own to add here would also be welcome.

**Comment by p01arst0rm** [comment]
i'm running Manjaro Arch. I tested from a fresh clone and build. ran the following commands:
```
git clone https://github.com/RPCS3/rpcs3
cd rpcs3
mkdir build
cd build
cmake .. -DUSE_SYSTEM_FAUDIO=true
make -j4
```

**Comment by Shoegzer** [comment]
I'm using similar (though I use git clone --recursive) although I tried your process from a fresh build directory and got the same results i.e.:
```
CMake Error at 3rdparty/CMakeLists.txt:228 (message):
  -- RPCS3: FAudio requires SDL 2.0.9 or newer.
```
So this could be the case for others with Ubuntu-based systems.

**Comment by p01arst0rm** [comment]
i would imagine its an issue with the deb repos being outdated or incorrectly built.

**Comment by p01arst0rm** [comment]
try uninstalling FAudio and SDL2 with apt, then build & install both into the system using the git repository.

**Comment by hcorion** [comment]
Do you think you could dump the files in `/usr/lib/cmake/SDL2/` onto GitHub Gist or something, perhaps Mint is doing something strange with the cmake files.

**Comment by Shoegzer** [comment]
Perhaps incorrectly built, though the repo's SDL2 is `2.0.10` so that should be fine.  Since this is basically a fresh install of Mint 20.1 (upgraded to 20.2), reinstalling those would probably not resolve anything.  I can try it, but I'd rather first have a report from at least one other Ubuntu-based tester, preferably Mint, as I suspect they'll encounter the same issue.  

If so, then it may be worthwhile to either remove `FATAL_ERROR`, turn FAudio off by default, or add a note for Ubuntu users in [BUILDING.md](https://github.com/RPCS3/rpcs3/blob/master/BUILDING.md) to turn it off manually.

**Comment by Shoegzer** [comment]
@hcorion the only directory in `/usr/lib/cmake` is `clang-10`.  There's a `/usr/lib/x86_64-linux-gnu/cmake/SDL2/` but it only contains `sdl2-config.cmake`.  That file's contents are as follows:
```
# sdl2 cmake project-config input for ./configure scripts

set(prefix "/usr") 
set(exec_prefix "${prefix}")
set(libdir "${prefix}/lib/x86_64-linux-gnu")
set(SDL2_PREFIX "/usr")
set(SDL2_EXEC_PREFIX "/usr")
set(SDL2_INCLUDE_DIRS "${prefix}/include/SDL2")
set(SDL2_LIBRARIES " -lSDL2")
string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES)
```

**Comment by hcorion** [comment]
Ah, right, it'll be in that folder on Ubuntu. That's odd though. On the [Ubuntu file list for libsdl2-dev](https://packages.ubuntu.com/hirsute/amd64/libsdl2-dev/filelist) it lists a
`/usr/lib/x86_64-linux-gnu/cmake/SDL2/sdl2-config-version.cmake`
which should also be in that folder.

**Comment by hcorion** [comment]
Do you know what version of Ubuntu Mint 20.2 pulls it's packages from?

**Comment by Shoegzer** [comment]
We're getting closer!

Mint 20.2 is based on Ubuntu 20.04, and uses its repo.  Take a look [here](https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/libsdl2-dev_2.0.10+dfsg1-3_amd64.deb.html), notice `sdl2-config-version.cmake` is nowhere to be found.

**Comment by hcorion** [comment]
What happens if you don't check the version in rpcs3's SDL2 check @Shoegzer ? It's so odd that 20.04 would omit the file that specifies the version. What are you doing Ubuntu?!

**Comment by hcorion** [comment]
Oh, I see what happened 🤦 it's not Ubuntu's fault. It's CMake's. 
https://github.com/libsdl-org/SDL/commits/main/sdl2-config-version.cmake.in

**Comment by Shoegzer** [comment]
Haha!  Actually I tested a bunch of things earlier which caused CMake to succeed:

* Bypassed SDL2 version check
* Removed FATAL_ERROR
* Declared -DUSE_FAUDIO

So yeah, it seems anybody using at least Ubuntu 20.04 will fail to compile current rpcs3 source unless they do something like what I've done above first.  

And yup, it does seem SDL2 is the root cause, I suppose a workaround could be added to CMakeLists to force CMake to check the version in some other manner for specific distros?  Otherwise, perhaps one of my suggestions above could work.

**Comment by hcorion** [comment]
Well yeah, since SDL2 has screwed us from checking the version on 2.0.10 and Ubuntu 20.04 likely isn't going to update their SDL2, we're stuck between a rock and a hard place. @Shoegzer did you want to PR the removing of the FATAL_ERROR?

I think eventually we'll update the SDL2 min to 2.0.12, but since there's obviously still distros in use with 2.0.10 as their latest version we can't really right now.

**Comment by Shoegzer** [comment]
Sure I can do the PR, give me a few.  We just need to recognize that it may cause slight confusion for anyone who doesn't look at cmake output, and then expects FAudio but doesn't get it.  Perhaps something to note in BUILDING.md.

And yeah bumping the SDL2 minimum right now might be hard on anyone with lower requirements, I figured there'd be an unambiguous path forward for those who want to use FAudio but I do see your point.

**Comment by p01arst0rm** [comment]
its strange that i dont get this error on arch systems, guess they added a fix in the recipe.

**Comment by Shoegzer** [comment]
@p01arst0rm what version of SDL2 are you using?
@hcorion I could also add a note to CMakeLists to address any confusion, so it could read something like:
```
message("-- RPCS3: FAudio requires SDL 2.0.9 or newer.")
message("-- Note: Ubuntu-based distros such as 20.04 with SDL 2.0.10 meet this requirement but fail to build FAudio due to missing sdl2-config-version.cmake which was since resolved in 2.0.12.")
```
What do you think?

**Comment by hcorion** [comment]
I like that idea 👍

**Comment by p01arst0rm** [comment]
cmake messages are generally very hard to see, especially with rpcs3's current buildsystem where verbose/debug messages arent labelled correctly. I don't think we should rely on people combing through their cmake logs to check for warnings.

**Comment by hcorion** [comment]
Though they don't fail to build as I understand? RPCS3 will still build fine with FAudio, the CMake version is just detected improperly?

**Comment by p01arst0rm** [comment]
i'd imagine if someone tried to build with an older version of SDL2 they'd run into problems even though the cmake build didnt halt. could be confusing. im not really sure what the best thing to do would be :)

**Comment by hcorion** [comment]
Yeah, this approach means that people on SDL2 < 2.0.10's build will fail for an unspecified reason.

**Comment by p01arst0rm** [comment]
it might just be best to fallback to the builtin version, that would make the most sense.

**Comment by p01arst0rm** [comment]
we could add sdl2 to the 3drparty dir, and add a system/builtin switch. instead of failing the build when sdl2 doesnt return a valid version, just fallback to the builtin version.

**Comment by hcorion** [comment]
I don't want to add a builtin SDL2, since RPCS3 doesn't use it directly.

Thinking about it more, I think the best approach here requiring minimum 2.0.12, and then if we fail to find a sufficient version, we throw a message and continue compiling without FAudio.

**Comment by p01arst0rm** [comment]
something like this would work a treat


```
# FAudio
set(FAUDIO_TARGET 3rdparty_dummy_lib)
if(USE_FAUDIO)
	# FAudio depends on SDL2
	find_package(SDL2)
	if (NOT SDL2_FOUND OR SDL2_VERSION VERSION_LESS 2.0.9)
		message(STATUS "RPCS3: FAudio requires SDL 2.0.9 or newer.")
		message(STATUS "       since a valid SDL2 version cannot be found")
		message(STATUS "       FAudio building will be skipped.")
		set(USE_FAUDIO False)
	else()
		if (USE_SYSTEM_FAUDIO)
		message(STATUS "RPCS3: Using system FAudio")
		find_package(FAudio REQUIRED CONFIGS FAudio-config.cmake)
		add_library(3rdparty_FAudio INTERFACE)
		target_link_libraries(3rdparty_FAudio INTERFACE FAudio)
		target_compile_definitions(3rdparty_FAudio INTERFACE -DHAVE_FAUDIO)
		set(FAUDIO_TARGET 3rdparty_FAudio)
	else()
		message(STATUS "RPCS3: Using builtin FAudio")
		set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build shared library")
		add_subdirectory(FAudio EXCLUDE_FROM_ALL)
		target_compile_definitions(FAudio INTERFACE -DHAVE_FAUDIO)
		set(FAUDIO_TARGET FAudio)
	endif()
endif()

```

**Comment by hcorion** [comment]
Yes, with an elseif() instead of just else 😄 Can you PR that?

**Comment by p01arst0rm** [comment]
i can PR it

where would you want an `elseif()` ?

**Comment by hcorion** [comment]
Here
```
	else()
		if (USE_SYSTEM_FAUDIO)
```

**Comment by p01arst0rm** [comment]
nope, thats two different checks. you want it to skip all building if SDL2 isnt found, and then build (but check what type) if it is. :)

**Comment by hcorion** [comment]
Oh I see, yeah I was reading it wrong, looks fine

**Comment by p01arst0rm** [comment]
ok ill make a PR :) any way to make the warning message cleaner?

**Comment by hcorion** [comment]
Looks fine to me from a language perspective, could maybe change from STATUS to WARNING though, to be a little more explicit in code.

**Comment by p01arst0rm** [comment]
yeah, true
