### ISSUE TITLE
Gundam Target in Sight [BLES00034] Game crashes randomly RSX Fatal Error

### ISSUE THREAD

**Issue by Shuneferus** [RPCS3/rpcs3#10600]
Game crashes randomly generating log:
F SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKQueryPool.cpp:46[:4], in function poke_query)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error)
The error log is attached.
System: Windows 10
GPU: GTX 1060 6GB driver 471.11
CPU: Xeon E5-2660 v3 @3.3ghz 32gb of ram 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6859754/RPCS3.log)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/10611 if this is a recent regression.
Otherwise, just try using strict rendering mode first.

**Comment by Shuneferus** [comment]
The game now runs in strict rendering mode. Thanks.

Em seg., 26 de jul. de 2021 às 18:42, kd-11 ***@***.***>
escreveu:
