### ISSUE TITLE
[NPEB01888] 50 FPS goes to 30 FPS

### ISSUE THREAD

**Issue by Giganticus275** [RPCS3/rpcs3#10608]
Before of the update RPCS3 0.0.17 , The game FPS decreased a lot , slow frames. When i go close to opponent , the FPS increases at 60 FPS but when i stay in distance it decreases at 27 FPS. All my configurations are in recommendation for increase the FPS but no changes.

i will give the video about it to helps in understanding the trouble. 
Video Link : https://www.mediafire.com/file/io0rnacwp4qcm2p/Npeb01888_Fp_Decreased.mp4/file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6872988/RPCS3.log.gz)

![FPS](https://user-images.githubusercontent.com/87907551/126879663-a78c2d9d-60a6-49ff-8892-335f1c9f03ad.png)

**Comment by AniLeo** [comment]
Does not follow the regression report guidelines, the game is missing licences and there are settings modified from defaults without any explanation to why they were changed

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
