### ISSUE TITLE
stopping emulator took too long some thread has probably deadlocked aborting Thread id=18720

### ISSUE THREAD

**Issue by ethancolon** [RPCS3/rpcs3#10606]
<img width="947" alt="Capture" src="https://user-images.githubusercontent.com/67854275/126861625-17323e60-aed1-416a-a9a4-b800e99246c2.PNG">
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6872084/RPCS3.log)

**Comment by Yoshi9800** [comment]
@ethancolon I see useing 471.11 still update to 471.41 it fixed rpcs3 for me so try it first.
