### ISSUE TITLE
F SIG: Thread terminated due to fatal error: Verification failed (in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTexture.cpp:236[:4], in function copy_buffer_to_image)

### ISSUE THREAD

**Issue by two4teezee** [RPCS3/rpcs3#10625]
F SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTexture.cpp:236[:4], in function copy_buffer_to_image)

Build 12535 and up to the latest build (12538) return the same error regardless of software loaded when using Vulkan (opengl seems to work but is quite slow, past Vulkan performance was very strong). Build 12522 works flawlessly for my configuration, so the issue may have been caused by fixes introduced in 12535 (notably #10611, #10612 @kd-11 [apologies if mentions are frowned upon in this community]).

I did all of my testing with Hot Shots Golf: Out of Bounds with build 12522 and all builds released after it; however, the bug was consistent regardless of software used. Clean installs, all default options.

Windows 10 (21H1, latest update)
i7-8700K
NVIDIA 1080Ti, latest drivers
16gb RAM

Log generated with build 12535 attached.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6898011/RPCS3.log)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/10628
