### ISSUE TITLE
PS3 Eye Camera Support on RPCS3 

### ISSUE THREAD

**Issue by Ralf-Rollan** [RPCS3/rpcs3#10638]
The feature so you can connect your PS Eye Camera to the RPCS3 would be perfect for games like “Wonderbook: Book of Spells/Potions”

Really will appreciate if someone can make this happen cause I think is the only “hardware” compatibility missing on RPCS3

**Comment by Yoshi9800** [comment]
@Ralf-Rollan No thier still no ps move support but do think added before ps move support because need to games. Ps move move cool way to play games then need in tames

**Comment by Megamouse** [comment]
Implemented

**Comment by mirh** [comment]
So.. I have seen #11016, but as I was hinting in the DS driver issue I was wondering: would there any point in doing a USB passthrough to the real PS3Eye?
After seeing how small `libcamera.sprx` is (also how little libeyetoy is mentioned in the other few related files like `avc_util.sprx`, `avc_plugin.sprx` and `sys_audio.sprx`) I see how HLE is basically what they were already doing themselves with *cellCamera*.. But given the lackluster status of the device drivers (also `sysconf_plugin.sprx` mentions some camera settings?) it would seem like something rad to be had.
