### ISSUE TITLE
I need some help with God of war ascension

### ISSUE THREAD

**Issue by XxDeStRoYeRxX1** [RPCS3/rpcs3#10648]
OS Win10Pro
CPU OctaCore Intel Core i7-9700K, 4600 MHz (46x100)
GPU Gigabyte Z390 Gaming X (4 PCI-E x1, 2 PCI-E x16, 2 M.2, 4 DDR4 DIMM, Audio, Video, Gigabit LAN)
Driver version 471.41
etc.
im gonna leave here the log im gonna need help bcs i see on youtube that the others can play game but i can't play it always freezes after the logo and if im lucky and get to main menu when im pressing to play the game freezes again so im gonna really need some help here
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/6925346/RPCS3.log.zip)

**Comment by XxDeStRoYeRxX1** [comment]
why did you close it ? can't you just tell me what to do or are you guys so bored to answer

**Comment by RainbowCookie32** [comment]
If anything, we are bored of people not reading the guidelines.

This is not the place for support, go to our Discord server instead. https://discord.me/RPCS3
