### ISSUE TITLE
Regression: Verification failed in function as_rtt on several games

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#10643]
In GTA V Father/Son mission cutscene Verification Fail occurs always at the same spot
![31](https://user-images.githubusercontent.com/7060586/127788264-10cca1a3-0f00-494b-9fd6-a2821cf4156d.jpg)
Started with https://github.com/RPCS3/rpcs3/pull/10447

First broken build:
0.0.16-12400
log: [RPCS3_broken.gz](https://github.com/RPCS3/rpcs3/files/6913591/RPCS3_broken.gz)

Last working build:
0.0.16-12398
https://github.com/RPCS3/rpcs3/pull/10447 
log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6913603/RPCS3.log.gz)

**Comment by kd-11** [comment]
I'm not sure whether to close this or not, as the underlying cause of this issue is the same and well known.

**Comment by AniLeo** [comment]
See duplicate #10801, also happens on Beyond Good & Evil HD

**Comment by Darkhost1999** [comment]
![Screenshot 2022-01-10 161640](https://user-images.githubusercontent.com/60384196/148847798-c58b4944-1a51-41d3-be7e-bd2ad9ae707d.png)
Seems to be working just fine here
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7842222/RPCS3.zip)

**Comment by Xcedf** [comment]
@Darkhost1999 did you watch cutscene completely and it still works or you skipped it?

**Comment by Darkhost1999** [comment]
Watched completely. You can skip the cutscenes?

**Comment by Xcedf** [comment]
Yes it's skipable, press X or O

**Comment by Xcedf** [comment]
Ok, I think I got it now
@Darkhost1999 saw your setting in the log, you have WCB disabled, it's required for a few things in the game and apparently being not very stable

**Comment by Darkhost1999** [comment]
Sorry the log had multiple processes in it and you probably noticed my nfs rivals settings.
For the future readers I got all RSX buffers enabled, disable zcull occlusion queries in debug tab (helps water), accurate RSX reservation access, and FSR.
Pretty much the settings that are currently on the wiki page for the game minus resolution scale threshold and TSX (my cpu does not support TSX).
