### ISSUE TITLE
Regression: Games crashing on boot (#10641)

### ISSUE THREAD

**Issue by AphelionWasTaken** [RPCS3/rpcs3#10653]
## Quick summary
Some games are crashing after compiling PPU modules and shaders.

## Details
The Last of Us, Uncharted 2, Yakuza Ishin, and likely other games are crashing after compiling modules and shaders, before going into gameplay. 

I did notice a PPU trap error in the log of The last of Us and Uncharted 2 on the broken builds. With TLoU, the trap error occurred just before the crash; Uncharted 2 crashed with a purple trap error. Logs for both games are below.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
Broken - 0.0.17-12588-9f67e00e
Last Working - 0.0.17-12586-2dd0f488

#### 2. Please attach TWO logs:
TLoU Working - [RPCS3 TLoU Before.log](https://github.com/RPCS3/rpcs3/files/6934540/RPCS3.TLoU.Before.log)
Uncharted 2 Working - [RPCS3 Uncharted 2 Before.log](https://github.com/RPCS3/rpcs3/files/6934558/RPCS3.Uncharted.2.Before.log)

TLoU Broken - [RPCS3 TLoU After.log](https://github.com/RPCS3/rpcs3/files/6934542/RPCS3.TLoU.After.log)
Uncharted 2 Broken - [RPCS3 Uncharted 2 After.log](https://github.com/RPCS3/rpcs3/files/6934543/RPCS3.Uncharted.2.After.log)

#### 4. Please attach screenshots of your problem.
<img width="961" alt="TLoU Freeze" src="https://user-images.githubusercontent.com/61633628/128259475-2e312dca-89f7-4292-bd88-8a8808ea8cad.png">

#### 6. Please provide your system configuration:
* OS - Windows 10
* CPU - 9900K
* GPU - 3080
* Driver version - 471.41.0.0

**Comment by elad335** [comment]
This is probably some special behaviour of COOPRATE_WITH_SYSTEM SPU groups, will hw test this evening.

**Comment by elad335** [comment]
Should be fixed by #10658

**Comment by elad335** [comment]
Any update?

**Comment by RainbowCookie32** [comment]
TLoU and UC2 are working fine for me on master now

![image](https://user-images.githubusercontent.com/16805474/128457296-adac60d1-c1b4-446a-b34c-d1fce5c90c03.png)

![image](https://user-images.githubusercontent.com/16805474/128457484-74e11789-d399-45cc-8cbd-38a7aa6fec2d.png)
