### ISSUE TITLE
Regression: The shadows disappred after (#10637) 

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#10662]
**Before:**
![screenshot-2021_08_05_22_33_32](https://user-images.githubusercontent.com/38318848/128417814-8d6025e4-23a3-4d7a-a939-6e44c2a0e1c9.png)
**After:**
![screenshot-2021_08_05_21_36_35](https://user-images.githubusercontent.com/38318848/128416091-250998be-e883-49f2-8260-e13723079397.png)
**RSX Capture:**
**Link:** [RSX-Capture-(RPCS3 v0.0.17-12565-before #10637 )](https://drive.google.com/file/d/1Ci5KYqTAtsqReo5kjvjjvXIo4_nkxajV/view?usp=sharing)
**RSX Capture:**
**Link:** [RSX-Capture-(RPCS3 v0.0.17-12598)](https://drive.google.com/file/d/1BfWKto2PhOMY0XgasEwOJGtHdRJZxLmT/view?usp=sharing)

**Details:**
-RPCS3 RPCS3 v0.0.17-12598 ]-
-Game:  NARUTO Shippuden: Ultimate Ninja Storm Generations [BLES01481]
-Issue: missing shadows [Vulkan/OpenGL]

OS: Windows 10 64-bit
CPU: Intel i7-10700
GPU: GTX 1660 - ( Driver version: 471.41.0.0 )

**Comment by kd-11** [comment]
Verify if fixed by https://github.com/RPCS3/rpcs3/pull/10668

**Comment by Emulator-Team-2** [comment]
@kd-11 
Fixed by  #10668
![screenshot-2021_08_06_23_44_16](https://user-images.githubusercontent.com/38318848/128574088-786f0fe9-1394-4c0b-9fb1-82e8d3dbb4cb.png)

**Comment by SatansFavSuccubus** [comment]
I think this was fixed? Most recent build has restored the shadows in all the games I play. (Motorstorm/PR/Apo | Killzone 2 | Modnation Racers) Thank you to whomever fixed it.
