### ISSUE TITLE
[Feature Request] Denoiser/Deblocker

### ISSUE THREAD

**Issue by Chaython** [RPCS3/rpcs3#10678]
## Quick summary
A denoiser/deblocker 

## Details
Some games are very noisy, whether it be Developers intent, an artifact, or an issue with RPCS3's scaler. So it would be nice to implement a mpeg and white denoiser as well as a deblocker.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
*Gameplay

#### Please include.
An example of a very noisy game is Siren.
![2021-08-08 03_43_09-Greenshot](https://user-images.githubusercontent.com/6486343/128627912-1641d3de-8de2-42c4-90f6-dda26169869d.jpg)

**Comment by VelocityRa** [comment]
The game is supposed to look like that and I don't see how a denoising shader in RPCS3 would make much sense (if it could even work at all).
This is more akin to film grain, with some smooth perlin noise-looking effect on top. It would not be easy to to remove it. It's a lot more fitting to make a patch for the game that removes its film grain pass.

So, it seems out of scope for RPCS3, you did not even mention any other games with noticeable film grain and even if there are, and there is sufficient interest in getting them removed in a generic way, there is probably no magical algorithm that would work for every one's film grain/noise implementation.

**Comment by VelocityRa** [comment]
The game is supposed to look like that and I don't see how a denoising shader in RPCS3 would make much sense.

If it it could even work, that is. Even this example is more akin to film grain, with some smooth perlin noise-looking effect on top. It would probably not be easy to remove it algorithmically. It's a lot more fitting to make a patch for the game that removes its film grain pass.

So, it seems out of scope for RPCS3, you did not even mention any other games with noticeable film grain and even if there are, and there is sufficient interest in getting them removed in a generic way, there is probably no magical algorithm that would work for every one's film grain/noise implementation.

**Comment by Chaython** [comment]
I assume, from the cutscenes, were it's showing a camera UI that there's meant to be filmic noise.
But in any screenshot I've seen/ the gameplay I saw there was significantly less noise, if any.
Though I assume most glossy images and video encoders have denoising which compensated for and hid the noise of the game.

**Comment by lextra2** [comment]
Looks like incorrect rendering from rpcs3. Realtime denoiser for 3D is not realistic. Whats more realistic is a game specific patch to remove some shader related effects.

**Comment by Chaython** [comment]
Using the denoise shaders in Reshade had slight blurring with no noticeable change to the noise.
Looking at the depth buffer, shows that everything is noisy and overly sharp. So I'd assume it's not just a post processing overlay.
But of course I am merely an ape.
![2021-08-08 14_58_32-Greenshot](https://user-images.githubusercontent.com/6486343/128645577-256f21c7-d128-45c9-abbc-31d467a68f7e.jpg)

**Comment by dio-gh** [comment]
RPCS3 couldn't do a better job at this than ReShade shaders can, and so I'll just repeat what I always say: please just stick to ReShade.

In the future, it's probably going to be possible to modify, add, and remove shaders from games, at which point you could cut the relevant shader that does the effect in the game with ease. You could cut it from the game as is with some game patching right now, if you have the expertise.

Overall, I suggest closing this in favor of #4045. As explained, shader editing/replacement will cover this use case too.

**Comment by Long-FA** [comment]
I don't have this game but you should double check to see if real PS3 also has noise or not. And yeah Reshade works well with RPCS3 but it has to be run every time you use RPCS3 if you dont want to opt for global Vulkan settings.

**Comment by kd-11** [comment]
Closing, this is not something we're likely to support and maintain any time soon.
