### ISSUE TITLE
PSMove Left Click Combo

### ISSUE THREAD

**Issue by AlphaDelta9** [RPCS3/rpcs3#10672]
Start and Circle for PSMove no longger work, only Triangle still work

Last working build 12576
[12576.RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6948843/12576.RPCS3.log.gz)
Regression since build 12586
[12586.RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6948842/12586.RPCS3.log.gz)

**Comment by Megamouse** [comment]
Not a regression. It's recommended to use a mouse with at least 5 buttons.
The new controls are:

o Left click: T
o Right click: ~/Move button
o Middle click: X
o Back (Button 4): Circle
o Forward (Button 5): Square
o Left + Right click (or button 6): Select
o Left + Middle click (or 7): Start
o Middle + Right click (or 8): Triangle
