### ISSUE TITLE
[Feature Request] Advanced cellOsk and native overlay implementations

### ISSUE THREAD

**Issue by Dormant-Hero** [RPCS3/rpcs3#10675]
## Quick summary
Keyboard to work more closely to how it did on PS3.

## Details

On the PS3 there was a way of typing in MGO2 whilst moving and using macros. Not sure if there is a way to get this for RPCS3. Currently to type with keyboard you have an issue with it being in the background when in fullscreen also. Sometimes the keyboard can glitch or stay open which can crash the game too.

I have explained in bit detail in this unlisted video https://www.youtube.com/watch?v=Zwq4Xk6wcvI . 

I may post PS3 footage if the issue is not clear still. 

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* UI

#### 2. Please tell us, why your feature is important to RPCS3.

Not sure that it is or how many games need the keyboard, but it would help with more closely emulating the PS3 experience. 

#### 3. Please attach screenshots of the feature implemented in other projects.

N/A

#### 4. Please provide your system configuration:
* OS Windows 10 (I can use manjaro)
* CPU AMD Ryzen 9 3900x
* GPU RTX 2060
* Driver version 471.11

#### Please include.
* Anything else you deem to be important

I could not find this posted already, therefore I can assume it is not on the priority list.

**Comment by Megamouse** [comment]
The issue is not clear. So please post ps3 comparisons.

**Comment by Dormant-Hero** [comment]
No worries. I will keep trying to explain the best I can. 

I made a video here https://www.youtube.com/watch?v=GnsJCcHoRso to show how it works on PS3.

Differences are as follows from what I can see:

-Game recognizes my keyboard as shown by the keyboard symbol at the start of the video. This did not happen on emulator.
-I can type and move at the same time. This did not happen on the emulator.
-In fullscreen I can type and see what I am inputting. This does not happen with the emulator when using keyboard.
-I can use marco functions such as F1 to use commands. This does not happen on the emulator.

I hope this is slightly clearer.

**Comment by MSuih** [comment]
Did you try changing the keyboard handler in io tab of settings? This should make the game see that you have a keyboard connected

**Comment by Dormant-Hero** [comment]
Hi @MSuih,

You are right. It does register when I have keyboard handler on. I forgot why I had turned it off. The video below will show the issue with keyboard handler on also. It may make you vomit. Good luck.

https://youtu.be/c_ipLNUdsx0

**Comment by marcoluc97** [comment]
I dunno if this can help but @Megamouse what do you think?
![20210808_112244](https://user-images.githubusercontent.com/9196583/128627321-55217e27-39a8-4ba0-906a-00b687ef88d2.jpg)

**Comment by Dormant-Hero** [comment]
@marcoluc97 If anything will help I will build you a statue of remembrance.

**Comment by dio-gh** [comment]
There's one thing I'm not sure I understand; why do you have native OSK off on purpose? (pic is from your first video)

![image](https://user-images.githubusercontent.com/10439488/128645367-4dd85bc3-a5b4-4de2-a7da-1b1f86ca1b16.png)

This would let the full virtual keyboard be shown at least, similar to how a real PS3 does it (pic is from your second video)

![image](https://user-images.githubusercontent.com/10439488/128645426-c61605a7-08a4-4a9f-b0fb-be571642ccea.png)

So overall, I can see two missing pieces to the puzzle:
- that full OSK won't be possible to be dragged around like on the PS3 I'd assume
- there's no minified text input widget (the one that'd let you type normally into the chat otherwise)

I'm not sure if trying to bring up the minified text input will crash the emu or not with native OSK enabled, so I'd recommend checking the full text input widget first (the one on the pic above).

**Comment by Megamouse** [comment]
I'm sure he wants to type using a keyboard. that's why

**Comment by dio-gh** [comment]
Ah right, forgot that the native OSK won't let you use your keyboard right now. (Please add/fix?)

**Comment by Megamouse** [comment]
While most of these features are not particularly difficult to tackle, they are very extensive and time consuming.
I'll try to test mgo2 and implement some of the logic presented here, after I fixed the pressure sensitivity issues in the coming week or so.

Basically it all comes down to missing functionality in both the OSK overlay frontend and the cellOsk backend.

**Comment by Dormant-Hero** [comment]
Yes definitely understand not at the top of the agenda. Appreciate the response also :).

**Comment by Megamouse** [comment]
The next upcoming master build (the one after 0.0.18-12802) should contain some updates regarding this issue.
I fixed some backend logic, which specifically improved seperate_window stuff.
Don't expect any visual changes though.

Please let me know if anything changes.

**Comment by Dormant-Hero** [comment]
> The next upcoming master build (the one after 0.0.18-12802) should contain some updates regarding this issue.
> I fixed some backend logic, which specifically improved seperate_window stuff.
> Don't expect any visual changes or changes regarding keyboard input though.
> 
> Please let me know if anything changes.

Thanks I will check it out.

**Comment by Dormant-Hero** [comment]
Okay checked it out. Nothing changed as you may have suggested in your response. 

Let me know if there is anything else to test that I may have forgot. 

Keyboard works in menus still, but still very weird behavior in game. Video below showing some of the weird stuff. 

https://www.youtube.com/watch?v=o5KH6Es8krc

**Comment by Dormant-Hero** [comment]
Hi Mega,

When do you think you will feel like looking at this one again? I know there are probably more important issues, but I would just like to check. 

![PussInBootsGIF](https://user-images.githubusercontent.com/79374258/145200956-d359dd33-ebc8-4179-8a89-3f9d4f92ef57.gif)

**Comment by Megamouse** [comment]
Christmas is a busy time. So don't expect anything until late January. Provided there's nothing more pressing popping up.
And even then it's probably not gonna be a really noteworthy change, since there's a lot to figure out before we can change the visuals (which will probably come last).
For example, adding keyboard support first needs a new flag for input focus implemented, which will be annoying. Then we'll have to hook the keyboard backend up, which might also be a slight challenge, and finally we need to interpret the input in the OSK code and make sure there's no double input if KB is used as controller.

Insert sad dog meme here

**Comment by Dormant-Hero** [comment]
Thanks for the answer. Some people in the MGO2PC discord were interested so I thought I would ask :).

**Comment by marcoluc97** [comment]
#11834 can help at all for this situation? Is some testing needed before merging or after is better?

**Comment by Dormant-Hero** [comment]
Hi All,

Just wanted to make an update in relation to where we are up to in relation to keyboard support for this **one** game XD.

Here is a video https://youtu.be/T8dudpEM6P4 . The video shows that the keyboard works with native user interface when pressing select twice in a game and using the osk. Also shows that I can no longer go to the next map/match due to keyboard not closing maybe?

Of course originally this works without having to press select to bring up the OSK as there is a unique process in this game specifically which does not require it. You can see how it worked here as a refresher here https://www.youtube.com/watch?v=GnsJCcHoRso . 

My log below:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9904704/RPCS3.log.gz)

**Comment by Dormant-Hero** [comment]
Sorry one thing I forgot to mention is I still cannot type to assign a macro in the game either. Video below with a log.

https://youtu.be/vCnlBOMnxB4

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9904751/RPCS3.log.gz)

**Comment by Dormant-Hero** [comment]
Hi Team,

Hoping you are all well and have had a great start to 2023. We went to check if there were any changes with typing in the this game. Sadly I do not think there are noteworthy changes/improvements but we did make a very high quality video to show what happens along with the log. 

I would be highly grateful if a hero is out there that can get the keyboard to function as it did on PS3 without the OSK and with the macros. The processes for this feature are numerous I believe and unique to this game. This is the last process /noticeable improvement left over that the PS3 version has over the PC. Though our community may be small (7.7k) you would make us very happy. 

Please see the video below and log attached. 

 https://youtu.be/Kk-D7rUzO9k
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10439866/RPCS3.log.gz)

**Comment by Dormant-Hero** [comment]
Megamouse is a legendary hero. I shall build statues in his name and honour. Though the entire gaming industry may not know who you are we will remember you as the hero that nobody knew. The keyboard emperor. 

I will await for the rebase from Triggerhappy for mgo2 to double check if any issues with this new OSK working with macros. 

As requested we have a GIF of the feature brought about so you never forget this absolute landmark of an achievement. 

The below shows Triggerhappy typing and then pressing enter to push text into the chat for everyone to see. It also shows him use macros that allow for quick communication. 

![osk10](https://user-images.githubusercontent.com/79374258/215260783-3d3a8a6a-6a53-4983-909d-9371355b9919.gif)
