### ISSUE TITLE
Rsx branch issues

### ISSUE THREAD

**Issue by Bigpet** [RPCS3/rpcs3#1067]
Alright, so it seems that the "rsx" branch got deleted somehow, then restored and now either merged with or rebased onto a different commit than it originally was.

The latest state before all the rebasing/merging and random "fixes" on top is apparently https://github.com/Nekotekina/rpcs3/tree/4574d08e652d12747614b25ad6101f0568053779 

So we can either

* try to puzzle together what happened in https://github.com/RPCS3/rpcs3/tree/rsx and try to figure out what got merged into what (and potentially have to rebase/merge again later when/if it gets into master)
* force push https://github.com/Nekotekina/rpcs3/tree/4574d08e652d12747614b25ad6101f0568053779 into the rsx branch and do the merging once the author decides that he wants to merge it

**Comment by Bigpet** [comment]
Hm, it seems like either way the squashed mega commit is less than ideal https://github.com/RPCS3/rpcs3/commit/28569df3b0f0db2ba1e2a3f97275c93417b969fc

So I think it would be best in either case to force push the old version with individual commits even if we re-apply https://github.com/RPCS3/rpcs3/pull/1065 afterwards

**Comment by Zangetsu38** [comment]
@Bigpet There is also an urgent need to update the RSX branch with master branch, in the present state, there has too much conflict brought the difference to the master branch recently, particular with the new PPU Interpreter 2, if we wait too much to do it's going to be a huge mess with no name.

**Comment by Bigpet** [comment]
@Zangetsu38 well I would very much like the author to state that intend before we do that.

**Comment by Zangetsu38** [comment]
@Bigpet I do not mean to merge rsx connect with the master.
But updating the rsx branch with the master branch.
Otherwise it will be a little messy to.

**Comment by tambry** [comment]
@Bigpet Is this still relevant?

**Comment by tambry** [comment]
Doesn't seem to relevant anymore.
