### ISSUE TITLE
Regression - analog joysticks don't work after PR #10674

### ISSUE THREAD

**Issue by GitArUs** [RPCS3/rpcs3#10680]
Analog sticks work in pad configuration window, but are ignored by games.

0031c416 is ok:
[RPCS3-0031c416.log](https://github.com/RPCS3/rpcs3/files/6950639/RPCS3-0031c416.log)

d4802cc7 is bad (many FindAxisDirection = -1 messages):
[RPCS3-d4802cc7.log](https://github.com/RPCS3/rpcs3/files/6950643/RPCS3-d4802cc7.log)

* OS: Fedora 34
* Controler: Logitech F710 (evdev)

**Comment by Megamouse** [comment]
Just for testing purposes: Does it work if you assign any button to the new "Pressure Sensitivity Mode" ?

**Comment by GitArUs** [comment]
Still does not work after button assignment, although those FindAxisDirection messagess no longer appear in log.

**Comment by Megamouse** [comment]
please try with this:
https://github.com/RPCS3/rpcs3/pull/10682

**Comment by GitArUs** [comment]
No change. Still spamming errors without button assigned and analog input does not work.
[RPCS3-828be442.log](https://github.com/RPCS3/rpcs3/files/6951173/RPCS3-828be442.log)

**Comment by Megamouse** [comment]
Ok. I pushed another fix. Please try again.

**Comment by GitArUs** [comment]
Error spam fixed, joysticks still don't work.

**Comment by Megamouse** [comment]
It probably works now. I didn't see that evdev has event codes with value 0, which was used internally to handle the special button.

**Comment by GitArUs** [comment]
Does not work, 16693f4c still broken.

**Comment by vipulbhandari82** [comment]
Broken for me too.

Ubuntu 21.04
RCPS3 0.0.17-12615-430fd759 Alpha
