### ISSUE TITLE
Regression: broken MLAA shader after PR "rsx: Texturing improvements #10637"

### ISSUE THREAD

**Issue by Linear524** [RPCS3/rpcs3#10691]
Postprocessing MLAA shader got broken in all previously working titles after PR 10637
Last correct working build was: RPCS3 v0.0.17-12565-8af694da
And after that all master builds suffer with incorrectly constructed mosaic pixels, which is result of broken MLAA, or lowered precision in MLAA sampling function...

![MLAA1](https://user-images.githubusercontent.com/84367301/128817789-46aa748c-102f-40c0-b7f3-c46e9a9bb153.jpg)
![MLAA2](https://user-images.githubusercontent.com/84367301/128817794-6f022993-4406-4b53-bf5e-26e54b87717b.jpg)
![MLAA3](https://user-images.githubusercontent.com/84367301/128817795-96a5bc6d-01d0-4945-bf6b-eb1d7c33bb86.jpg)

Tested rig:
- SYS: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz | 14 Threads | 31.83 GiB RAM | TSC: 2.594GHz | AVX+ | FMA3 | TSX disabled by default
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1080' running on driver 471.41.0.0
- SYS: Firmware version: 4.87

Tested games with proved regression:
- God of War 3
- God of War Ascention
- Persona 5
- Metal Gear 3
- Metal Gear 2
- Killzone2
- Killzone3
- Shadow of the Colossus
- Ico
- and a lot of other titles, which had correct MLAA-filtered image output before.

WCB is always On, because it helps render all special effects in games.
Native resolution (Because it is the only correct option for correct MLAA reproduction)
Everything else is set to Default

**Comment by kd-11** [comment]
Likely fixed by https://github.com/RPCS3/rpcs3/pull/10689. Did you try that PR?
It is now merged anyway, try master after the new builds are ready.

**Comment by Linear524** [comment]
Will test that new PR tonight, thanks :)

**Comment by Linear524** [comment]
Confirming - regression is fixed ! :)
Thanks (^_^)
Now even Journey works perfectly with MLAA and fully playable !)
![screenshot-2021_08_10_21_45_39](https://user-images.githubusercontent.com/84367301/128962384-58ce3b8f-6c0a-4c70-9d0c-0756e45441ac.png)
![screenshot-2021_08_10_21_46_28](https://user-images.githubusercontent.com/84367301/128962387-824761c2-5194-4d5f-a841-a032359b1fe3.png)
![screenshot-2021_08_10_21_48_01](https://user-images.githubusercontent.com/84367301/128962390-7e61e40b-aa3c-4493-9bc2-899f8a0d3999.png)
