### ISSUE TITLE
the last of us all backgrand going to black

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#10695]
## Quick summary

The background turns black
This problem exists throughout the game

## Details

The background turns black
This problem exists throughout the game

I changed all the settings but there is still problem is exist
There is a problem exist with Vulcan and OpenGL

I created a video in under

#### 1. Please attach RPCS3's log.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6965179/RPCS3.zip)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc 
capture that demonstrate it.
#### 3. Please attach screenshots of your problem.
![0](https://user-images.githubusercontent.com/25039098/128954850-d8cfd07b-b620-409a-8056-30cd497c64c1.jpg)

![1](https://user-images.githubusercontent.com/25039098/128954862-af63938f-86c1-438c-a0d1-bc1ec3a69b96.jpg)

i Capture a video and upload to youtube

https://youtu.be/mH4U9tHk0yM

#### 5. Please provide your system configuration:
* OS 
windows 10 version 21H1 build 19043

* CPU
ryzen 3900x

* GPU
Nvidia  780 Ti

* Driver version
Nvidia Driver Version  471.41

#### Please include.
* Anything else you deem to be important

**Comment by Linear524** [comment]
Oh man... Switch your GPU API to Vulkan.
Apply MLAA disable patch.
Apply GPU side patch
Apply culling disable patch.
Turn Write Color Buffers and Read Color Buffers to "ON"
These settings will produce closest to original graphics, at least on current RSX emulation stage...
And stop using OpenGL - it is slow and buggy.

**Comment by AniLeo** [comment]
Bad settings, closing as bad report

**Comment by aakh1361** [comment]
Yes, it was a mistake in my settings
