### ISSUE TITLE
OSX compiling error

### ISSUE THREAD

**Issue by saber00** [RPCS3/rpcs3#1069]
Hi, I followed the building section, and when I got to the part "git submodule update --init", I get this error: "fatal: Not a git repository (or any of the parent directories): .git"

I have installed glew and wxwidgets, and when I try to skip the command and do "cd rpcs3 && cmake CMakeLists.txt && make && cd ../" it would give me this error: http://pastebin.com/FuVK2T51

Thanks in advance

**Comment by Bigpet** [comment]
have you actually used "git clone https://github.com/RPCS3/rpcs3.git" to download the repository?

Because just downloading the *.zip file will not give you the needed files.

Edit: yeah, just looked at the Readme, I can see how that would be confusing

**Comment by saber00** [comment]
That was exactly what I did. I did git clone https://github.com/RPCS3/rpcs3.git

**Comment by Syphurith** [comment]
@saber00 It seems your local repo was broken. You can try to clone it again using `git://` protocol.
If you still fail to execute `git submodule init --update` you would not have `wxWidgets`,`LLVM`, and other submodules. If you are sure your network is quite laggy, you may come to irc and ask for a git bundle or simply an archived local repo, that `wxWidgets` and `LLVM` are huge you know..

**Comment by saber00** [comment]
@Syphurith Wait so is it "git submodule init --update" because what I did was "git submodule update --init"?

**Comment by Syphurith** [comment]
@saber00 Once it is initialized and updated, you only need to track the main repo.
So many times i just type `git pull --progress --all -v -p` to update all the remotes.
`git submodule init --update` to init and update the submodules.
`git submodule update --recursive` to update all initialized submodule (recursively).
BTW if you tried a wrong command, git would just refuse to execute.
There are many GUI packages for Git if you can not get used to its command line.

**Comment by saber00** [comment]
I'm still getting the same error: "git submodule init --update fatal: Not a git repository (or any of the parent directories): .git" even after cloning a new git, what are all of the requirements to build it?

**Comment by Syphurith** [comment]
@saber00 I'm so glad to see it may be solved. Hope you good luck with it.
