### ISSUE TITLE
[Minor Issue] Spelling Inconsistency in Settings

### ISSUE THREAD

**Issue by sami0505** [RPCS3/rpcs3#10692]
I know this isn't the biggest issue in the world, but it is low hanging fruit. While in the description of GPU>Additional Settings> VSync, it is spelled as "Artifacts" which is the American English spelling, in the description of the new GPU>Upscaling>Enable FSR Upscaling it is spelled as "Artefacts" which is the British English spelling. If you find the time to even it out, feel free to. Thank you~

**Comment by dio-gh** [comment]
Thanks for reporting.

@RedDevilus Please keep low-effort trolling on Discord, preferably contained within #off-topic too.

**Comment by MSuih** [comment]
Keep the issue open until the pull request has been merged

**Comment by sami0505** [comment]
> Keep the issue open until the pull request has been merged

Ah, ok.
