### ISSUE TITLE
[Feature Request] Whitelist Kamen Rider Summonride Portal USB device

### ISSUE THREAD

**Issue by ZohaibIrfan** [RPCS3/rpcs3#10694]
Add support of Kamen Rider Summonride's USB peripheral in order to progress ingame.

The peripheral's ID is 
VID: 0E6F
PID: 200A

It's not currently whitelisted in RPCS3's sys_usbd

Currently, the game gets stuck here, asking for device connection. I've installed WinUSB drivers to the device and nothing is detected yet.
![image](https://user-images.githubusercontent.com/76737765/128933752-8a01f091-0c9f-4c00-bfb1-4ced8291d428.png)

**Comment by ZohaibIrfan** [comment]
Can confirm it works by updating sys_usbd.cpp with the required usb id. If anyone can put it to master that'd be great.

https://user-images.githubusercontent.com/76737765/129794986-68409a1b-92dc-4714-a9e0-a4f26cea53c8.mp4

[sys_usbd.zip](https://github.com/RPCS3/rpcs3/files/7002842/sys_usbd.zip)

**Comment by marcoluc97** [comment]
Please test #10722 @ZohaibIrfan
