### ISSUE TITLE
Silent Hill Downpour  RSX: Driver crashed 

### ISSUE THREAD

**Issue by xevious89** [RPCS3/rpcs3#10696]
## Quick summary

·F 0:05:44.725878 {RSX [0x004d16c]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)

## Details

I play this game 4K/60FPS config. whitout problems with the driver NVIDIA 466.77 (6.10.2021)

But since the last three updates drivers 471.11 (22.06.2021), 471.41 (19.07.2021), 471.68 (10.08.2021) the game always crash but only when 60fps config is put it (120 hz vblank).
It runs normal in 4K but when i try to run the game at 60fps it crash (not happen with the old driver)

* Attach the log:
	[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6971381/RPCS3.log.gz) (471.68)
        [RPCS3_466.log.gz](https://github.com/RPCS3/rpcs3/files/6971397/RPCS3_466.log.gz) (466.77) (here´s my log with the old driver running normally without crash)

Ryzen 5 5600X 
RTX 2060 (Driver: 471.68)
2x8G DDR4 3200MHz
Windows 10 Pro 21H1 (19043.1151)

Any reason for that to happen?
I stick with the old driver?

Thanks.

**Comment by RinMaru** [comment]
Never had the game crash for me. Well it has crashed once but never did it again.

**Comment by kd-11** [comment]
470 series driver is broken in many vulkan applications, not just rpcs3. The steps required to actually debug the crash are also not simple and I do not have a turing card.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/11401
Request to reopen if the problem persists.
