### ISSUE TITLE
God of War III freezes

### ISSUE THREAD

**Issue by toto621-linux** [RPCS3/rpcs3#10702]
## Quick summary
- When I try to save, game have 50% to freeze at save slot selection.
- After  ~1hour of smooth gameplay, game freeze.

## Details
Title: God of War® III
Serial: BCES00510
Version: 1.03
- Each time I try to use save point, I have 50% of ending with game freeze then RPCS3 crash. Sometimes save work as intended.
- After extended gameplay  without problems (most of the time I can play  approximatively 1hour without issues), the game suddenly freeze and RPCS3 crash.

## System summary
RPCS3 v0.0.17-12629-063df641 Alpha
CPU: Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz | 16 Threads | 31.94 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 2070
RAM: 32Gb of DDR4
SSD: Samsung 860 Pro 1TB
OS: Windows 10, Build: 19042

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6981828/RPCS3.log)

**Comment by AniLeo** [comment]
Several bad settings deviating from defaults being used with no explanation to why
Submit this as a support request instead
