### ISSUE TITLE
Installing on Hirsute Hippo

### ISSUE THREAD

**Issue by bjbalken-zz** [RPCS3/rpcs3#10729]
Hello!

I love your project and I just wanted to say that your documentation is fantastic. I am currently trying to get it installed on Hirsute Hippo and I had a couple issues that had very easy fixes but I just wanted to post here in case you want to add a note to the BUILDING.md documentation. When I installed gcc11, I had to specify CC=/usr/bin/gcc-11 (and similar for CXX). Then for installing Qt5, the ppa doesn't suport hirsute yet so the easiest way I found was just to install from the Qt website. But then I had to run the Qt maintenance utility and explicitly install 5.15.2 (because by default I got Qt6). Glad I went to all the trouble because I love this project and also I'm going to be using gcc11 and Qt6 soon. But I hope that this saves other Hirsute users some time and confusion.

Thanks,
Brendan

UPDATE:

A better solution for getting qt5 was this:
sudo apt-get install qtbase5-dev
sudo apt-get install qtdeclarative5-dev

**Comment by Megamouse** [comment]
@AniLeo @hcorion  please evaluate

**Comment by Megamouse** [comment]
I wanted to install hippo soon anyway. maybe I can share my own info then.

**Comment by hcorion** [comment]
It's pretty straightforward, we just need to add an extra note in the Ubuntu Qt installation to install the regular qt5base-dev if your version is new enough

**Comment by nitroos-ai** [comment]
Reached end of life.

**Comment by Megamouse** [comment]
I forgot to take notes when I installed it. But it was really not hard.
Closing because it's not really an issue with the emulator
