### ISSUE TITLE
Intel: ANV: FSR upscaling black screen

### ISSUE THREAD

**Issue by A-w-x** [RPCS3/rpcs3#10726]
## Quick summary

If FSR is enabled, rpcs3 shows a black screen but the game is running in background

[log1.log](https://github.com/RPCS3/rpcs3/files/7007721/log1.log)

capture of a game, if can help
[BLES00231_20210818084814_capture.rrc.zip](https://github.com/RPCS3/rpcs3/files/7007727/BLES00231_20210818084814_capture.rrc.zip)

* OS: ArchLinux
* CPU: i7-1165g7
* GPU: intel xe
* Driver version: mesa git

**Comment by kd-11** [comment]
We know what's wrong with it and multiple ways to fix it, though the underlying cause is a driver deficiency in mesa. I'll commit a workaround and suggest improvements to the driver team. The windows driver does not have this problem.

**Comment by AniLeo** [comment]
Yeah, tested this earlier already, it shows corrupted image or a black screen even on iGPU as old as HD 530, but it can be fixed

**Comment by A-w-x** [comment]
i still get a black screen on xe
am i supposed to update mesa too?

**Comment by AniLeo** [comment]
What game did you test? Try with gs_gcm_cube.elf from TEST12345. Works fine here. Same as Persona 5.

**Comment by A-w-x** [comment]
everyone i have :P

black screen with the test

oh, it is the combo resolution scale + fsr = black screen
default res scale + fsr is ok

**Comment by kd-11** [comment]
Post your log when it is working vs not working

**Comment by A-w-x** [comment]
[working.log](https://github.com/RPCS3/rpcs3/files/7031188/working.log)
[notworking.log](https://github.com/RPCS3/rpcs3/files/7031189/notworking.log)

cube test

**Comment by AniLeo** [comment]
FTR I tested 125% (900p) FSR to 1080p and cube works here

**Comment by A-w-x** [comment]
my res scale is set to 50%

**Comment by AniLeo** [comment]
50% (360p) to 1080p (90% RCAS)

![Screenshot from 2021-08-23 12-03-21](https://user-images.githubusercontent.com/10283761/130437077-d5635f76-20c7-415a-aad1-fda808537406.png)

**Comment by A-w-x** [comment]
![output](https://user-images.githubusercontent.com/80461138/130492949-6c85a0b6-4b6a-473f-b984-29ba85564e91.gif)

**Comment by kd-11** [comment]
Maybe try mesa-git. The exact same steps work fine on RADV and I do not own any Xe hardware to check what could be going on with your setup. However, note that at 100% scaling with fixed size window, FSR is actually inactive. If you want to check if 100% scaling works, enabled FSR and then maximize the game window.

**Comment by A-w-x** [comment]
this is mesa-git
100% works with max window and fullscreen

>= 100% works
< 100% black screen

**Comment by kd-11** [comment]
Then you only have 1 option left:
Install vulkan sdk tools and run the application with debug output enabled (from the hidden debug tab). If there is no extra info in the log you will have to report the bug to mesa and have them look at it. If there is some info I can try to work with that.

**Comment by A-w-x** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7034817/RPCS3.log)

**Comment by kd-11** [comment]
Mesa issue introduced with PR https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/10624
Its easy enough to work around.

**Comment by kd-11** [comment]
Fix CI job: https://cirrus-ci.com/task/4840702497521664
@A-w-x Test when the build is ready. If you build from source yourself you will have to grab the fsr branch from my fork or simply import this commit: https://github.com/kd-11/rpcs3/commit/66f6adc8fdc52bd31d1d3fa9f4a65be7b679ec7c

**Comment by A-w-x** [comment]
fix is working, thanks
