### ISSUE TITLE
Ridge racer 7 random video freeze

### ISSUE THREAD

**Issue by A-w-x** [RPCS3/rpcs3#10727]
random video freeze in main menu and in game (you need luck to go in game :P )
the game is still running in background

log of a lucky run, in game freeze
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/7008126/RPCS3.log.zip)

* OS: ArchLinux
* CPU: i7-1165g7
* GPU: intel xe
* Driver version: mesa git

rpcs3-git

**Comment by legend800** [comment]
This is a dup of other open issues. Please search before submitting a new issue.

https://github.com/RPCS3/rpcs3/issues?q=is%3Aissue+is%3Aopen+ridge+racer

**Comment by A-w-x** [comment]
they all talk about crashes, maybe that one is similar or the same, closing this anyway
