### ISSUE TITLE
SSAO bug with resolution scaling in the Uncharted Series  

### ISSUE THREAD

**Issue by mjd180** [RPCS3/rpcs3#10734]
Presumably fixed in The Last of US recently (issue appears to have been closed), this bug still plagues all three Uncharted games. Any recent version of RPCS3 on any hardware shows some SSAO scaling problem. It looks like black half-transparent lines on any geometry if resolution scaling is used above default/native 720p. But, interestingly, if you set resolution scaling to 4K/300% - this bug will disappear and overall image will looks just as intended. This is on a 4k monitor, so YMMV.

Attached is a shot of the bug as previously reported from TLOU:
![119090097-fc59c100-ba2c-11eb-9716-63a85fedc653](https://user-images.githubusercontent.com/61510543/130269459-1cacb69c-faa1-4097-8183-958a5b890084.jpg)

**Comment by aakh1361** [comment]
Confirmed
I have the same problem in TLoU and uncharted

**Comment by Linear524** [comment]
It is just the same copy of my reported issue:
https://github.com/RPCS3/rpcs3/issues/10316
Don't see any reason for duplicating this, even with my old screenshots 8P

**Comment by mjd180** [comment]
Well, the reason was in the very first sentence (“issue appears to have been closed”). Now this issue has been closed as well (seemingly, due to complaint of “duplication” for something that no longer existed at time of creation)?

**Comment by Asinin3** [comment]
The linked issue was never closed... This is a duplicate and shouldn't have been created.

**Comment by suyash691** [comment]
@Asinin3 the linked issue has been closed without an actual fix (it has been closed as the OP of that thread was satisfied with the workaround of using fsr instead of actual fix to resolution scaling of SSAO effects). So I think we need to either reopen this or that one
