### ISSUE TITLE
Metal Gear Solid 3 HD - Visual artifacts issue

### ISSUE THREAD

**Issue by LYNCfjorir** [RPCS3/rpcs3#10730]
OS - Windows 10
CPU - Ryzen 5600X
GPU - RX 6700 XT 12Go

When trying to run Metal Gear Solid 3 form the HD collection (using the settings recommended in the wiki), I get important artifacts in both the cutscenes and gameplay ([captures](https://github.com/RPCS3/rpcs3/files/7011300/captures.zip)), I haven't found anything like that while searching the internet (the closest was the one with the shadow in cutscenes that was fixed with the _read color buffer_ option.

Here is the [RPCS3 log](https://github.com/RPCS3/rpcs3/files/7011315/RPCS3.log).

Thanks in advance

**Comment by AniLeo** [comment]
Disable MSAA/Anti-Aliasing
If it doesn't happen anymore you can close the issue, it's a known driver bug

**Comment by LYNCfjorir** [comment]
Brilliant, thanks a lot :)
