### ISSUE TITLE
Resolution problem in 1080

### ISSUE THREAD

**Issue by Zangetsu38** [RPCS3/rpcs3#1073]
I have this sort of bug on several games, it withstands 1080 but when the game launches are taken in 1080, but the window is 720, so it's been a black block on the rest.
![capture d ecran 2015-05-04 14 52 07](https://cloud.githubusercontent.com/assets/5261759/7453847/ca91176e-f26d-11e4-841b-f52526df6040.png)
![capture d ecran 2015-05-04 14 56 58](https://cloud.githubusercontent.com/assets/5261759/7453852/d75b9212-f26d-11e4-8342-c1b13392a0f6.png)

**Comment by Syphurith** [comment]
@Zangetsu38 I don' know if you should change `./rpcs3/Emu/RSX/GL/GLGSRender.cpp`. It announced `RSXThread::m_width = 720;` in 1431 from function `OnInit`. But it should be changable in rpcs3 Settings, as in *Ini.GSResolution.GetValue*. And it is maintained with scaling.
You may use VS2013 to track down the function calls..
Well for a 1366*768 laptop, gea170e8 does render worse in 1080p (not only black zones).

**Comment by Zangetsu38** [comment]
@Syphurith 
No, after testing it has nothing to do with this line.

**Comment by Syphurith** [comment]
@Zangetsu38 Well. so the m_width is scaled correctly. Maybe in RSX rendering..
BTW I don't know if rpcs3 can detect the GS settings supported by the game..

**Comment by Zangetsu38** [comment]
hmm @Nekotekina please help for this ^^

**Comment by Nekotekina** [comment]
@Zangetsu38 What do you want? Your first screenshot is 3840×2160 and seems terribly upscaled. I don't have 4K monitor, so I don't understand what's going on.

**Comment by Zangetsu38** [comment]
@Nekotekina  No, nothing to do with my 4K screen, the window is well in 1080, but over 200%, so if I see anything XD.
I always had this problem on single games, (even with a 1080 screen), the games are set in 1080, also rpcs3, so the game is displayed in 1080, but not the GS window, it makes the board black as I show it.

**Comment by Nekotekina** [comment]
With 1920x1080 display resolution you can't normally use 1920x1080 game resolution in window mode because some part is invisible anyway. Just use 720p.

**Comment by Zangetsu38** [comment]
Yes that's right the problem, and it does just that on some games, and "just to 720p" is not a solution, there is the problem.
So it must be resolved, it must be turned games in 1080 without a problem.

**Comment by Nekotekina** [comment]
It's not the priority anyway, and 720p works fine. Why you need 1080p so much?

**Comment by Zangetsu38** [comment]
Because it is simply better, and that is a problem to solve, so I point it just to make it solved ^^.

**Comment by vlj** [comment]
By the way the use of shader make it nearly impossible to support arbitrary resolution. Some shader uses resolution dependant constants for fullscreen filter, like width, 1 over width, 2 over width...and I'm not sure we can reliably detect them.
We're bound to which resolution the game is internally using.

**Comment by vlj** [comment]
Fixed with D3D12
