### ISSUE TITLE
Ratchet & clank tools of destruction softlock

### ISSUE THREAD

**Issue by A-w-x** [RPCS3/rpcs3#10731]
After ~30 minutes or a bit more of gameplay the game softlocks
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/7012883/RPCS3.log.zip)

* OS: ArchLinux
* CPU: i7-1165g7
* GPU: intel xe
* Driver version: mesa git

**Comment by Asinin3** [comment]
Still an issue?

**Comment by A-w-x** [comment]
yes
