### ISSUE TITLE
Get rid of bundled cacert file for windows

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#10743]
Currently Windows builds come with a cacert.pem file as network features won't work without it.

However, this shouldn't be neccessary as Windows has built-in way to handle certificates. There should be a way to configure curl (+ wolfssl?) to use Schannel, which would allow us to get rid of this certificate bundle.

**Comment by oltolm** [comment]
This was fixed by [#14870](https://github.com/RPCS3/rpcs3/pull/14870), wasn't it?
