### ISSUE TITLE
rsx: Unimplemented dynamic register indexing

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#10742]
List of known games:

**Dead Island:**
<details> 
<summary>(Screenshots.)</summary>

![1](https://user-images.githubusercontent.com/38318848/130363445-4583c9e7-c245-4ab3-a8be-fbb3813bf33f.png)
![2](https://user-images.githubusercontent.com/38318848/130363450-31687cdf-27d3-4915-97d3-dec3baebcc64.png)

</details>

(RenderDoc/RSX Capture/shaders cache)
**Link:** 
[rdc capture-vk](https://drive.google.com/file/d/1ukslYSAbJAQTqdQtHMB0q-sJEEOo-5F4/view?usp=sharing)
[rsx capture](https://drive.google.com/file/d/1-jnOOrv-SDWcVIE8kUkoe5vnZpBBSrcY/view?usp=sharing)
[shaders cache](https://drive.google.com/file/d/1_AH2ZzirzMqw67PPJ2N3YcGXfQHRG_VX/view?usp=sharing)

----------------------------------------------------------------------------------------------------------------------------------------------
**Dead Island Riptide:**
<details> 
<summary>(Screenshots.)</summary>

![1](https://user-images.githubusercontent.com/38318848/130363360-c6f21d0d-4666-4deb-a7b8-960f4ffe0eca.png)
![2](https://user-images.githubusercontent.com/38318848/130363364-d6bee19c-55c2-45fa-9d30-10d0ae01e47d.png)
![3](https://user-images.githubusercontent.com/38318848/130363368-a419e222-b664-4c5b-8cbc-b6e7bc6fc0df.png)

</details>

(RenderDoc/RSX Capture/shaders cache)
**Link:** 
[rdc capture-vk](https://drive.google.com/file/d/1nzEefjBTAr5GFe5-yr_B-1pnTJIMqe9S/view?usp=sharing)
[rsx capture](https://drive.google.com/file/d/1MdxjEDKK_kZWdEVgVwyXftqlmxhk7Xr1/view?usp=sharing)
[shaders cache](https://drive.google.com/file/d/1LkGyXhUV-SwzNLIwePbhCWI6dr2P0t3i/view?usp=sharing)

**Details:**
-RPCS3-0.0.17-12654
-Issue: Broken and overbloom lighting in game.
-rsx_log.error("Dynamic register indexing is unimplemented. Report this to developers!");

OS: Windows 10 64-bit
CPU: Intel i7-10700
GPU: GTX 1660 - ( Driver version: 471.68.0.0 )

**Comment by kd-11** [comment]
Relates to https://github.com/RPCS3/rpcs3/pull/10733

**Comment by Darkhost1999** [comment]
Is this issue the same as #6798 ?

**Comment by Shoegzer** [comment]
@Darkhost1999 This is related as far as the overbloom issue goes, though as @kd-11 stated in #10746 the dynamic register indexing issue is not.

**Comment by kd-11** [comment]
Let's follow the bloom issue in the other ticket. I actually know what's wrong with it, no need to open more tickets for the same thing.

**Comment by digant73** [comment]
> Let's follow the bloom issue in the other ticket. I actually know what's wrong with it, no need to open more tickets for the same thing.

@kd-11 so maybe a forgotten issue (bloom) that could be easily fixed now? I refer to this ticket and also #11122 (both reporting bloom  issues). I see PR #10733 and #10746 fixed something but also broke something (e.g. #10733 reported as regressing PR on #11122)

**Comment by Bobble80** [comment]
> > Let's follow the bloom issue in the other ticket. I actually know what's wrong with it, no need to open more tickets for the same thing.
> 
> [@kd-11](https://github.com/kd-11) so maybe a forgotten issue (bloom) that could be easily fixed now? I refer to this ticket and also [#11122](https://github.com/RPCS3/rpcs3/issues/11122) (both reporting bloom issues). I see PR [#10733](https://github.com/RPCS3/rpcs3/pull/10733) and [#10746](https://github.com/RPCS3/rpcs3/pull/10746) fixed something but also broke something (e.g. [#10733](https://github.com/RPCS3/rpcs3/pull/10733) reported as regressing PR on [#11122](https://github.com/RPCS3/rpcs3/issues/11122))

You mentioned the bloom issue in Tron, that’s still there along with black squares appearing alongside the overblown bloom in game. 

And there’s a similar bloom / lighting issue happening in Transformers - Fall of Cybertron too. 
https://github.com/RPCS3/rpcs3/issues/13106

**Comment by kd-11** [comment]
> > Let's follow the bloom issue in the other ticket. I actually know what's wrong with it, no need to open more tickets for the same thing.
> 
> [@kd-11](https://github.com/kd-11) so maybe a forgotten issue (bloom) that could be easily fixed now? I refer to this ticket and also [#11122](https://github.com/RPCS3/rpcs3/issues/11122) (both reporting bloom issues). I see PR [#10733](https://github.com/RPCS3/rpcs3/pull/10733) and [#10746](https://github.com/RPCS3/rpcs3/pull/10746) fixed something but also broke something (e.g. [#10733](https://github.com/RPCS3/rpcs3/pull/10733) reported as regressing PR on [#11122](https://github.com/RPCS3/rpcs3/issues/11122))

The dynamic register indexing feature needs hardware verification. Basically I have to feed the hardware a list of input registers and then construct the instruction the same way tron does and see what happens. It's tough to find the time (and equipment) for these lengthy experiments these days hence the stall on some of these tickets.
