### ISSUE TITLE
Are you aware that some chinese company filled a trademark on RPCS3 in Europe (EUIPO)?

### ISSUE THREAD

**Issue by someshittyeletronicmusicband** [RPCS3/rpcs3#10749]
https://euipo.europa.eu/eSearch/#details/trademarks/018454390
![018454390_page-0001](https://user-images.githubusercontent.com/89416947/130503051-ab9b7a14-6d7d-49ad-928c-20bd9d40e1ab.jpg)

**Comment by MSuih** [comment]
We're aware. Use our Discord server for discussion, not github
