### ISSUE TITLE
be_t and templates

### ISSUE THREAD

**Issue by Syphurith** [RPCS3/rpcs3#1074]
~~In those tiny situations, even a single function call would count.~~
**I could not connect to IRC to see you, so i posted this here. (D-Lined?)**
`be_t` was called in many files and many times. Maybe its LE and BE value could be cached and use a sync operation to update the other one when one is changed, so that its ToLE, ToBE could just return internal values instead of any calculation.
Also, there are many template classes now, like `se_t` only be used in `be_t` conversions. I don't know how to write templates indeed, cause i can only use C not C++. I am afraid of using these too much, like what happens when you want to simply write "HelloWorld" into a text file in Java.
I doubt highly about the performance difference of my suggestion. If it can be proved useless, please tell me and let me close this issue. *Hope you have more luck in developing.*

**Comment by Bigpet** [comment]
I tend to agree that the templates aren't always written in a very readable manner.

As for using "memoization" or duplicating LE and BE values. I suspect there's not much of a speedup to gain there. Maybe you can provide an example of it actually being faster and not just taking up data cache space.

**Comment by Syphurith** [comment]
@Bigpet I tried to read the code today, however failed in rebuilding the connections around it. If you search for `be_t` in the whole repository there are about 200+ of them, so i doubted its effect.. I did not succeeded when estimated its result. Would simply try to set a cache for LE value first since itself holds a `m_data` of BE value.. Hope it doesn't break rpcs3..

**Comment by Syphurith** [comment]
Unfortunately there are many static asserts checking those sizes of structs embeded `be_t`.
So many errors. Still the main purposes of the `ToLE` and `ToBE` are left to be checked.

**Comment by Bigpet** [comment]
you can't just add a member to be_t , the reason why the size is important is that you can just cast a random memory address to a be_t. If you introduce a new member variable for the cache you would overwrite memory.

**Comment by Syphurith** [comment]
That's it. So should think twice for what the purpose the callers have.. I stopped trying to change those.

**Comment by Nekotekina** [comment]
I'm afraid you can do nothing here: be_t<> is almost OK, and you can't avoid swapping byte order at all. Just try to understand it better.

**Comment by Syphurith** [comment]
OK, now i would just close this issue.
