### ISSUE TITLE
Chrome crashes rpcs3

### ISSUE THREAD

**Issue by SamEPK** [RPCS3/rpcs3#10753]
## Quick summary
Whenever Chrome is open RPCS3 crashes when I boot or install something like firmware or roms.
Closing it successfully prevent it from crashing tho

## Details

RPCS3's log. :
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7035024/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7035025/RPCS3.log.gz)

My system configuration:
* OS = Windows 10 64bits
* CPU = Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
* GPU = GeForce GTX 950

**Comment by ST-PABLO** [comment]
The same thing has been happening to me, did you ever figure it out?

**Comment by MSuih** [comment]
Is this caused by some specific addons/extensions being installed to chrome? We've been trying to figure this out but have not been able to reproduce.

Also I'm pretty sure this is a regresson, which means some combination of chrome or rpcs3 versions should work.

**Comment by CookiePLMonster** [comment]
It might also be helpful to check if RPCS3 truly freezes waiting for another process by going in the Task Manager -> Details -> select `rpcs3.exe` -> right click -> Analyze Wait Chain

![image](https://user-images.githubusercontent.com/7947461/132837481-f338e8f0-7d7c-4a8e-8477-c24612b0c540.png)

If RPCS3 is stuck waiting on something, it'll be listed in this dialog.

**Comment by ST-PABLO** [comment]
> Is this caused by some specific addons/extensions being installed to chrome? We've been trying to figure this out but have not been able to reproduce.
> 
> Also I'm pretty sure this is a regresson, which means some combination of chrome or rpcs3 versions should work.

I have no idea what causes this, I scoured the internet for this issue and i found one post and i tested to see whether chrome was the issue. Spoiler alert: it was, but I have no idea why exactly this is happening. The only new extension ive recently installed was fdm. I will see if removing it will fix the issue 

> It might also be helpful to check if RPCS3 truly freezes waiting for another process by going in the Task Manager -> Details -> select `rpcs3.exe` -> right click -> Analyze Wait Chain
> 
> ![image](https://user-images.githubusercontent.com/7947461/132837481-f338e8f0-7d7c-4a8e-8477-c24612b0c540.png)
> 
> If RPCS3 is stuck waiting on something, it'll be listed in this dialog. You may then try to kill these processes from there and see if RPCS3 unfreezes.

I looked at the wait chain and it just said it wasnt responding. No other explanation

**Comment by Megamouse** [comment]
This is most likely caused by the potato cpu.

**Comment by ST-PABLO** [comment]
> This is most likely caused by the potato cpu.

I have a ryzen 7 3700 and it started happening randomly, it was working fine up until september.

**Comment by ProbuxKQ** [comment]
> The same thing has been happening to me, did you ever figure it out?

i was told to come here and try to tell you guys about what happened with opera gx and rpcs3 for me. so basically when i use opera gx and rpcs3 at the same time rpcs3 stops responding. apparently this is the chromium version opera uses 83.0.4254.70 but i couldnt find the one for opera gx. hope this helped

**Comment by Megamouse** [comment]
Closing as inactive and unable to reproduce
