### ISSUE TITLE
Samurai Warriors 3 Z   or 4  and 4-II

### ISSUE THREAD

**Issue by Isamiyuu** [RPCS3/rpcs3#10757]
Samurai Warriors 3 Z [BLJM60313]
Samurai Warriors 4 [BLJM61144]
Samurai Warriors 4-II [BLJM61257]

Samurai Warriors Series Have the same problem 

## Details
Last RPCS3  build
The cutscenes and opening movies are Delay is not smooth .
After updating the latest version, the video and audio are out of sync, and the video is slow and not smooth. 
It won't be like this before the update .  
Only the movies has a problem .

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7039825/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7039830/RPCS3.log)

#### 5. Please provide your system configuration:
 SYS: RPCS3 v0.0.17-12663-c1f31d37 Alpha | HEAD
- SYS: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz | 16 Threads | 15.88 GiB RAM | TSC: 3.600GHz | AVX-512+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 960' running on driver 471.68.0.0
- SYS: Firmware version: 4.88

Thanks team .

**Comment by AniLeo** [comment]
Incomplete regression report, missing what build regressed it

**Comment by Isamiyuu** [comment]
> 
> 
> Incomplete regression report, missing what build regressed it

SORRY .
Last RPCS3 master build
Forgot which version was normal before .
This's This is the problem video I recorded .
https://www.mediafire.com/file/x5gz5i6hetdrmfl/2021-08-25_03-04-42.mkv

**Comment by Isamiyuu** [comment]
The new version status is still unresolved, the normal old version has been found 0.017 12652

**Comment by MSuih** [comment]
Should be fixed by #10763. If the issue persists this can be reopened.

**Comment by Isamiyuu** [comment]
> 
> 
> Should be fixed by #10763. If the issue persists this can be reopened.

Thanks .  fixed.
