### ISSUE TITLE
Brek graphics in Fuse™ [BLES01724]

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#10766]
(The image is from another PR, but it looks the same on master)
![Untitled](https://user-images.githubusercontent.com/23019877/130850088-d5584a95-5614-40e1-950c-668b76d598da.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7049288/RPCS3.log.gz)

[RSX Capture](https://mega.nz/file/dkwhSQIY#vl1kEu65kY-vPxYaaE6W3jwXyUKT3lcSmOi4GA_40XE)

**Comment by kd-11** [comment]
Still borked?

**Comment by Megamouse** [comment]
yes:
https://mega.nz/file/9lgG0IJZ#OCUFGUrE2aH63uVdLcT9X55yA5WBx84yIxY7sJmR9jY

**Comment by Megamouse** [comment]
![image](https://user-images.githubusercontent.com/23019877/132250607-770ed121-d208-48b6-ae9e-2134e8015751.png)

**Comment by Xcedf** [comment]
A regression as it turned out, PR #8439
build 10505 - first broken
![15](https://user-images.githubusercontent.com/7060586/146658087-48ae16b5-56de-4e35-919c-3d672d9a8636.jpg)
build 10504 - last working
![14](https://user-images.githubusercontent.com/7060586/146658094-3b2d6912-066e-4ce9-8a05-b54850d27229.jpg)

**Comment by Xcedf** [comment]
Hacky solution to work on recent builds
![image](https://user-images.githubusercontent.com/7060586/146662569-571c386d-0b99-4770-ab1d-eac140b07da4.png)
![12](https://user-images.githubusercontent.com/7060586/146662573-f4312a5c-5941-4ccd-8eb9-ad9f9b62f102.jpg)

**Comment by Edenia3** [comment]
> Hacky solution to work on recent builds ![image](https://user-images.githubusercontent.com/7060586/146662569-571c386d-0b99-4770-ab1d-eac140b07da4.png) ![12](https://user-images.githubusercontent.com/7060586/146662573-f4312a5c-5941-4ccd-8eb9-ad9f9b62f102.jpg)

https://www.youtube.com/watch?v=iGTBl01iwnE

**Comment by gperea602** [comment]
@Xcedf hello where i can i find that settings because i cant find it in any .yml on rpcs3 folder you can help me please ?

**Comment by Xcedf** [comment]
@gperea602 it's not a setting, it's a hacky rpcs3 build.

**Comment by gperea602** [comment]
@Xcedf you can give me a link to download that version ¿?

**Comment by Xcedf** [comment]
@gperea602 https://mega.nz/file/HJ4BmSiR#CdqQQcM_3uvLXzDG__p8LsSgdeDDx9Ysz4t7AcxCBFU
place file into your rpcs3 folder and play with it

**Comment by gperea602** [comment]
> @gperea602 https://mega.nz/file/HJ4BmSiR#CdqQQcM_3uvLXzDG__p8LsSgdeDDx9Ysz4t7AcxCBFU place file into your rpcs3 folder and play with it

thank you very much man

**Comment by kd-11** [comment]
Tagging so I don't forget about this one.
