### ISSUE TITLE
[BLUS30115] Condemned 2: Memory corruption crash

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#10761]
This game still suffers from some problems with graphics and compiling shaders. I found new bug.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7042402/RPCS3.log.gz)

**Comment by kd-11** [comment]
How reproducible is the crash? Does it happen each time at the same place? There is a lot of missing information here.

**Comment by kd-11** [comment]
We have "atomic FIFO mode" and "accurate RSX reservations" now in the advanced tab, the corrupted shaders shouldn't be an issue anymore. The remaining graphics glitching (excluding shader interpreter) is fixed by https://github.com/RPCS3/rpcs3/pull/12762.

**Comment by kd-11** [comment]
Closing, let's track in https://github.com/RPCS3/rpcs3/issues/5495
