### ISSUE TITLE
[Regressions] Resistance 3

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#10775]
Currently found 3 regressions in Resistance 3.

</details>

- [ ] Aim visual bug. This happens only when I aim. Reproducible. Cleaning caches does not help.<details>
This appears after #10257 
![screenshot-2021_08_27_22_03_20](https://user-images.githubusercontent.com/22906342/131193737-01e9aea9-0917-4d14-a350-96653ad75662.png)
Before 
![screenshot-2021_08_27_22_08_38](https://user-images.githubusercontent.com/22906342/131194169-1c62bd21-7d5c-419c-993c-486fc8860b79.png)
[RPCS3_aim_bug.log.gz](https://github.com/RPCS3/rpcs3/files/7069635/RPCS3_aim_bug.log.gz)
[RPCS3_no_aim_bug.log.gz](https://github.com/RPCS3/rpcs3/files/7069636/RPCS3_no_aim_bug.log.gz)
[BCES01118_aim_bug_capture](https://drive.google.com/file/d/1LrxBO41I8P9OrpJDSwaf8S4DIZ47WhSn/view?usp=sharing)
[BCES01118_no_aim_bug_capture](https://drive.google.com/file/d/1b4BgbYzVZQ2RvwKx-Y5QvT6Vko5Rgp-K/view?usp=sharing)
- [ ] Shadow bug.<details>
This appears after #8398
![screenshot-2021_08_28_20_56_01](https://user-images.githubusercontent.com/22906342/131228004-fd5df4bf-40c0-4a30-9559-bee5e3d65590.png)
Before 
![screenshot-2021_08_28_20_42_39](https://user-images.githubusercontent.com/22906342/131228006-2b9c02e6-1ecf-49b0-860d-29f03f0dd7fb.png)
[RPCS3_no_shadow_bug.log.gz](https://github.com/RPCS3/rpcs3/files/7071269/RPCS3_no_shadow_bug.log.gz)
[RPCS3_shadow_bug.log.gz](https://github.com/RPCS3/rpcs3/files/7071270/RPCS3_shadow_bug.log.gz)
[BCES01118_shadow_bug_capture](https://drive.google.com/file/d/1z-rGLWZysXUwdtizK3pSWT6yULZLY0u4/view?usp=sharing)
[BCES01118_no_shadow_bug_capture](https://drive.google.com/file/d/1xrxO5r6myGxooZ9rc8yMROo1GB3PnGwZ/view?usp=sharing)
</details>

- [ ] OpenGL bug.<details>
This appears after #9613 
![screenshot-2021_08_28_23_36_10](https://user-images.githubusercontent.com/22906342/131231890-910a1d36-eb0e-4fbd-99b5-7ecf83d5b7e3.png)
Before 
![screenshot-2021_08_28_23_42_35](https://user-images.githubusercontent.com/22906342/131231891-4da29de7-71c1-4f00-879a-69b61277c783.png)
[Resistance_3_OpenGL_bug_renderdoc_capture](https://drive.google.com/file/d/1aJTTIt14zwuTEX4DwFwahGXcYvEY31Ee/view?usp=sharing)
[Resistance_3_OpenGL_no_bug_renderdoc_capture](https://drive.google.com/file/d/178w0vd4Enlq-cAWfKxKsvqPycZOpQUs-/view?usp=sharing)
[BCES01118_OpenGL_bug_rsx_capture](https://drive.google.com/file/d/1QgPD14ZRZBJJuApCTnSF22cEspA-Eigq/view?usp=sharing)
[BCES01118_OpenGL_no_bug_rsx_capture](https://drive.google.com/file/d/1ac1qCVUpmmIu34KyUp7iTUAWk7nWjEqj/view?usp=sharing)
[RPCS3_no_OpenGL_bug.log.gz](https://github.com/RPCS3/rpcs3/files/7071538/RPCS3_no_OpenGL_bug.log.gz)
[RPCS3_OpenGL_bug.log.gz](https://github.com/RPCS3/rpcs3/files/7071539/RPCS3_OpenGL_bug.log.gz)
</details>

- AMD Ryzen 5 3600 
- Windows10, 19041
- GPU: 'GeForce GTX 1650' running on driver 456.71.0.0
- SYS: Firmware version: 4.87

**Comment by Wontell** [comment]
I can confirm this bug, have the same, came to report them too.
OP, can you please remind me whats the last build that it worked fine?

**Comment by Wontell** [comment]
BTW this is for Resistance 3 [BCES01118]

**Comment by Xcedf** [comment]
Nice catch! never thought that aiming was actually working. Was able to debug it:
file surface_store.h
line 802:
changed from:
if (access.is_transfer() && access.is_read() && surface->write_through())
to:
if (access == rsx::surface_access::transfer_read && surface->write_through())

The result:
![12](https://user-images.githubusercontent.com/7060586/131231668-fa71c64f-7ea1-4913-a2a4-336548b69c82.jpg)
![13](https://user-images.githubusercontent.com/7060586/131231670-41b2c669-1a28-4df4-b829-ab0777a93001.jpg)

**Comment by Wontell** [comment]
> Nice catch! never thought that aiming was actually working in Resistance 3. Was able to debug it:



Hi, can you consider creating a patch as temporary solution? The new patch update came 2 days ago and allows code change

**Comment by AniLeo** [comment]
You can't patch (and shouldn't be able to patch) emulator code. As a temporary solution, use the older build prior to the regression.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/10788
I just reused the old enumeration constant for read access without thinking and we ended up with a valid access qualifier of 0 which just breaks everything. Stupid mistake from my side.

**Comment by kd-11** [comment]
This ticket handles the zoom issue, for the others, please open separate tickets.
