### ISSUE TITLE
[NPUB30225] Lara Croft and the Guardian of Light no longer boots

### ISSUE THREAD

**Issue by Chezlin21** [RPCS3/rpcs3#10771]
## Quick summary
[NPUB30225] Lara Croft and the Guardian of Light Regression is no longer boots

## Details
F VM: Access violation reading location 0x4 (unmapped memory) [type=u32]

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
[NPUB30225] Lara Croft and the Guardian of Light Regression is no longer playable. Last working build is RPCS3 0.0.13-11214. No longer boots in builds including and following RPCS3 0.0.13-11215. 

#### 2. Please attach TWO logs:
* One for the build with regression.
* One for the build that works as expected.

##### How to obtain RPCS3's log:
[[NPUB30225]PlayableRPCS3.log](https://github.com/RPCS3/rpcs3/files/7062453/NPUB30225.PlayableRPCS3.log)
[[NPUB30225]RegressionRPCS3.log](https://github.com/RPCS3/rpcs3/files/7062454/NPUB30225.RegressionRPCS3.log)

#### 6. Please provide your system configuration:
* OS Win10
* CPU Ryzen 3900x
* GPU 2080 super

**Comment by benderscruffy** [comment]
this goes ingame again
can be closed
