### ISSUE TITLE
Frametime Hiccups

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#10777]
Very recently(within the week) every game in rpcs3 has frametime hiccups of 80-100 ms every second or so. Thought it was my system, but old versions of rpcs3 work fine.

Here is my system:
- SYS: RPCS3 v0.0.17-12674-ddb04214 Alpha | HEAD
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 471.68.0.0
- SYS: Firmware version: 4.85

This is an emulator wide problem so I don't know what else to add.

Thank you for your patience.

**Comment by AniLeo** [comment]
You need to follow the issue guidelines and submit a correct issue
