### ISSUE TITLE
PlayStation Home: offline 1.86 build crashes randomly

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#10773]
## Quick summary
When emulating the offline build of PlayStation Home (part of the Destination Home project) the game will randomly crash.

## Details
When emulating the offline build of PlayStation Home (part of the Destination Home project) the game will randomly crash, my computer's fan will then spin up really fast like it's trying to do something, but it never does.  This does not happen on real PS3 consoles.  It seems to happen in the Navigator most of the time, usually when flipping through the scene selector.  The log spams "Unregistered Function Called" whenever the Navigator is open, so that might be a lead.

#### Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7064470/RPCS3.log.gz)

#### Please attach screenshots of your problem.
![1](https://user-images.githubusercontent.com/58268914/131078351-a40303e5-c5a6-4dad-8986-87b97e8525b5.PNG)
![2](https://user-images.githubusercontent.com/58268914/131078361-58951aa7-f705-4fe9-a71f-af5ead106913.PNG)

#### Please provide your system configuration:
* OS - Windows 10 v19043 64-bit
* CPU - Intel Core i9-10900K
* GPU - NVIDIA RTX 2080 Super
* Driver version - 466.27
* etc. - 64 GB DDR4 Memory

#### Please include.
This is the only gamebreaking problem left apart from performance which will improve eventually.

**Comment by spookysniper** [comment]
try going to advanced tab and enable read colour buffers

**Comment by SlyCooperReloadCoded** [comment]
This doesn't work.  Also, an update - this doesn't only happen in the Navigator, it can happen any time.  For example, the Resistance turret minigame:

![1](https://user-images.githubusercontent.com/58268914/131225101-ba92f40d-79b1-477b-83f9-5e909fd7c308.PNG)

Also, despite my computer's normally-silent fan spinning up VERY loud whenever it crashes, Task Manager doesn't show anything abnormal:

![Capture2](https://user-images.githubusercontent.com/58268914/131225125-a091beeb-8780-4669-88c5-33f6eaf928a7.PNG)

**Comment by spookysniper** [comment]
post up some pics of your rcps3. CPU, GPU, ADVANCED and DEBUG settings , the debug tab can be added in by going into the GuiConfings folder and into CurrentSettings.ini and changing showDebugTab=false to showDebugTab=true

**Comment by AniLeo** [comment]
The settings are already on the log file

**Comment by spookysniper** [comment]
ok ill just paste the log ones over and try to recreate do it that way, thanks

**Comment by spookysniper** [comment]
Try this 
In GPU check:
Write colour buffers
Multithreaded rsx
And change number of shader compiler threads to auto
In ADVANCED check:
PPU LLVM Accurate vector NaNs
Uncheck Debug console mode
In Debug check: 
Force CPU blit emulation
And change PPU thread count to 3 
Your other settings should be fine

**Comment by SlyCooperReloadCoded** [comment]
With those settings it doesn't boot at all, crashing before attempting to boot with:

F VM: Access violation reading location 0x60000000 (unmapped memory) [type=u64]

Without those settings it works apart from this random crash issue.  I had to undo all those settings to get it to boot again.

**Comment by spookysniper** [comment]
![cpu](https://user-images.githubusercontent.com/45374856/131233168-d86bf966-f881-48cc-b667-ee0e79e4d1c8.png)
![gpu](https://user-images.githubusercontent.com/45374856/131233171-ea31cb7c-cabd-4ee8-9e46-c5bd66d0c96d.png)
![advanced](https://user-images.githubusercontent.com/45374856/131233176-7bd8762a-b186-467d-86ae-a224bb79f8f5.png)
![debug](https://user-images.githubusercontent.com/45374856/131233178-320016cf-0539-4879-adba-8a97d5278beb.png)

these are the settings i use except i dont try to run it at 60fps that being said it never crashed when i tried it

**Comment by SlyCooperReloadCoded** [comment]
I'm pretty sure it has something to do with that Unregistered Function or something else not in the settings.  If some people don't crash with similar settings, then it's something more complex.

**Comment by spookysniper** [comment]
yh i went on you original settings and for the most part it was pretty stable the only way i could crash it was by playing that resistance minigame (or any minigame) then go to the scene selector and start scrolling up and down it a few times , it never crashed in open play though when i tried this..

**Comment by spookysniper** [comment]
think i have narrowed it down to the advanced tab try checking PPU LLVM Accurate Vector NaNs and Un-checking PPU LLVM Precompilation (pretty sure this alone is the issue)

**Comment by SlyCooperReloadCoded** [comment]
"playing that resistance minigame (or any minigame) then go to the scene selector and start scrolling up and down it a few times"

Yeah, this is when it happens.  I''ll try with those settings, although disabling precompilation sounds like a bad idea.

**Comment by SlyCooperReloadCoded** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7073069/RPCS3.log.gz)

Nope, tried your settings and it still crashes.  You're correct about how to trigger the crash, playing any minigame then scrolling through the scene navigator does trigger the crash.

**Comment by SlyCooperReloadCoded** [comment]
Wait, I forgot to disable PPU LLVM Precompilation, when I did it doesn't seem to crash anymore.  Don't close this issue yet, it's a random crash, so it might still happen.

**Comment by SlyCooperReloadCoded** [comment]
Yep, I was right, it still crashes just as often when enabling PPU LLVM Accurate Vector NaNs and disabling PPU LLVM Precompilation.  Those options seem to delay the crash by a lot, but it always happens eventually.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7073100/RPCS3.log.gz)

**Comment by spookysniper** [comment]
bit of a longshot here but i was testing something else on rpcs3 and the game wouldn't boot up unless i signed the eboot a particular way  if you get a eboot resigner tool and try the different signing options, cfw and debug it might help something

**Comment by SlyCooperReloadCoded** [comment]
I really do think it's that Unregistered function that's the issue.  All crashes happen shortly after the log repeatedly spams Unregistered Function.  It's the same one each time, so it this one function was implemented, the crashes would go away.

**Comment by SlyCooperReloadCoded** [comment]
Now that the keyboard issues and graphical issues are completely fixed, this is now the only remaining issue.  Any updates on it?  That unregistered function has to do with this, I just know it.

**Comment by SlyCooperReloadCoded** [comment]
Okay, I'm glad I kept this issue open, it also crashes on DEX firmware, however that same fullscreen workaround seems to also work here.  So strange.

**Comment by SlyCooperReloadCoded** [comment]
Okay, after some more testing, I'm calling the "computer gets really loud crash" fixed, no idea what fixed it though.  However there's still the issue where it occasionally locks up when you select a new scene in the Navigator.  But my fix of entering then exiting fullscreen makes it continue.
