### ISSUE TITLE
Regression: Resistance 3. Shadow bug (#8398)

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#10789]
Shadow bug.<details>
This appears after #8398
![screenshot-2021_08_28_20_56_01](https://user-images.githubusercontent.com/22906342/131228004-fd5df4bf-40c0-4a30-9559-bee5e3d65590.png)
Before 
![screenshot-2021_08_28_20_42_39](https://user-images.githubusercontent.com/22906342/131228006-2b9c02e6-1ecf-49b0-860d-29f03f0dd7fb.png)
[RPCS3_no_shadow_bug.log.gz](https://github.com/RPCS3/rpcs3/files/7071269/RPCS3_no_shadow_bug.log.gz)
[RPCS3_shadow_bug.log.gz](https://github.com/RPCS3/rpcs3/files/7071270/RPCS3_shadow_bug.log.gz)
[BCES01118_shadow_bug_capture](https://drive.google.com/file/d/1z-rGLWZysXUwdtizK3pSWT6yULZLY0u4/view?usp=sharing)
[BCES01118_no_shadow_bug_capture](https://drive.google.com/file/d/1xrxO5r6myGxooZ9rc8yMROo1GB3PnGwZ/view?usp=sharing)
</details>

- AMD Ryzen 5 3600 
- Windows10, 19041
- GPU: 'GeForce GTX 1650' running on driver 456.71.0.0
- SYS: Firmware version: 4.87

**Comment by kd-11** [comment]
Captures are too old, I'll have to try and reproduce another way.

**Comment by Realmantik** [comment]
[Resistance 3 Shadow Bug RenderDoc Capture](https://drive.google.com/file/d/1CQIrCgfseUc6yA6dFqlIj9LIMD7lLLpU/view?usp=sharing)
[BCES01118_shadow_bug_rsx_capture](https://drive.google.com/file/d/1Gd8aT0FshlebjuUfSW2rhso08U5l1AZ5/view?usp=sharing)

Captures made on RPCS3 v0.0.17-12687-b07960d3 version

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/10792. Please confirm when it is ready.
