### ISSUE TITLE
Regression: Uncharted 2 BCES00757 flickering surfaces (#9377)

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#10796]
Found a regression from an old PR - https://github.com/RPCS3/rpcs3/pull/9377, which is still here, some surfacest under certain camera angle may go flickering in Ucnharted 2.
footage from current master:
https://www.youtube.com/watch?v=q4_mT0bhGNM

RPCS3 11347:
![13](https://user-images.githubusercontent.com/7060586/131360732-a0b61109-e858-4c88-bd2a-dc2538cb5c17.jpg)
footage of issue:
https://www.youtube.com/watch?v=IYXbR8oRaQU

RPCS3 11346:
![12](https://user-images.githubusercontent.com/7060586/131360822-d036f1f6-c3a8-467d-b0c0-b7685ceb527e.jpg)
footage of normal looking surface:
https://www.youtube.com/watch?v=HChqcI3envk

Logs:
[RPCS3_working.log.gz](https://github.com/RPCS3/rpcs3/files/7077617/RPCS3_working.log.gz)
[RPCS3_broken.log.gz](https://github.com/RPCS3/rpcs3/files/7077619/RPCS3_broken.log.gz)
[RPCS3_master.log.gz](https://github.com/RPCS3/rpcs3/files/7077621/RPCS3_master.log.gz)

Captures:
First broken:
RSX capture - https://mega.nz/file/mF5wQB5T#tncCS9a4rsnka1fkiFgGDFHjYfrDP7fN3s7hk4CSeCI
Last working:
RSX capture - https://mega.nz/file/PJ4g0ByC#u2Hh5nlDhYlW_EwU1Fh4Pr-oofT2dUfVTnYAikcVtU4
Current master:
RSX capture - https://mega.nz/file/uVg0EJ4C#_Tuf027eBlEwEWqbjSFpNFfePXk5LY16dltbyCdHHuo
RenderDoc - https://mega.nz/file/6Ep0GJBa#iNpKnLQ1onZUA8Eo3GXJTK29UQ9dHQh6sVC9L99Pb3o
Unfortuantely RenderDoc refuses to launch my old builds 11346/47

My system:
i9 9900k
gtx 1070
Drv: 458.06

**Comment by Xcedf** [comment]
A little update:
found out that this issue cause by smth from prefetch_fragment_program function, disabing it's call and shutting down some of verifications allows me to render without issue on older version, unfortunately newer ones don't allow me to shut down those verifications without emu crash.

**Comment by Xcedf** [comment]
update 2:
analyzed prefetch_fragment_programm func a bit, was able to get a hacky fix, works for current master as well
![image](https://user-images.githubusercontent.com/7060586/134038439-89802206-82f5-4bb3-ab92-5f977eda756c.png)

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/11125
