### ISSUE TITLE
Resistance 3. Fatal Error. Verification failed in function copy_transfer_regions_impl

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#10798]
This crash happens on Vulkan and OpenGL. Reproducible at level in metro. 
[RPCS3_OpenGL_Error_log.zip](https://github.com/RPCS3/rpcs3/files/7080006/RPCS3_OpenGL_Error_log.zip)
[RPCS3_Vulkan_Error_log.zip](https://github.com/RPCS3/rpcs3/files/7080010/RPCS3_Vulkan_Error_log.zip)

RPCS3 v0.0.17-12690-b5dcfb34
AMD Ryzen 5 3600
Windows, 19041
GeForce GTX 1650 running on driver 456.71.0.0
Firmware version: 4.87

**Comment by kd-11** [comment]
Please mention which game it is. I often read these reports on my phone, it helps if I can tell what I need from a glance.

**Comment by kd-11** [comment]
Still an issue?

**Comment by Realmantik** [comment]
Currently cannot reproduce. But I found another bug. Half of the screen differs from another. But this happens only when level starts, after some short time this goes to normal
![Resistance 3  new aiming bug](https://user-images.githubusercontent.com/22906342/149585231-4cdc067f-d97e-46a1-9ee1-19ae3f15f132.png)
.

**Comment by kd-11** [comment]
Test with 'legacy' shader compiler. If it still happens, enable RCB/RDB/WCB/WDB and see if that fixes it. If that doesn't work open a new ticket.

**Comment by kd-11** [comment]
Closing this issue as fixed in master.
