### ISSUE TITLE
[BLUS30794] Failure to properly compile fragment shader

### ISSUE THREAD

**Issue by pianistrevor** [RPCS3/rpcs3#10797]
## Quick summary
Reproducible error; game fails to compile a shader when transitioning sections in the game.

## Details

On the very first level of the game (Lego Harry Potter Years 5-7), entering the doors inside the Ministry of Magic (after the paper airplane) causes a compilation error and terminates the game and the program.

There are no graphical tears or visual glitches; the game simply hangs on the black screen.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

Obtained clean install of v0.0.17-12693 Alpha [2021-08-30].
Settings changed:
SPU Decoder: ASMJIT
Framelimit: Off
Turned on PPU LLVM Accurate Vector NaNs

#### 1. Please attach RPCS3's log.
* Run the game until you find the issue.
* Completely close RPCS3, or move to the next step in case it has crashed.

RPCS3 crashed, so I have pasted the relevant log information:

E RSX: ERROR: 0:372: 'texture2DReconstruct' : no matching overloaded function found 
ERROR: 0:372: 'process_texel' : no matching overloaded function found 
ERROR: 0:372: 'assign' : cannot convert from ' const float' to ' temp highp 3-component vector of float'
ERROR: 0:372: '' : compilation terminated 
ERROR: 4 compilation errors. No code generated.

E RSX: 
F SIG: Thread terminated due to fatal error: Failed to compile fragment shader
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKProgramPipeline.cpp:28[:25], in function compile)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc.
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 5. Please provide your system configuration:
* OS
Windows 10 x64 21H1 19043.1165
* CPU
AMD Ryzen 9 3900X 12-Core Processor
* GPU
NVIDIA GeForce RTX 2070 SUPER
* Driver version
471.68.0.0
* etc.

#### Please include.
* Anything else you deem to be important

When I stop the game before it crashes, I get an error about deadlocked threads. Perhaps that is another issue, though.

**Comment by YuriNator557** [comment]
Log file is missing.

**Comment by pianistrevor** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7118786/RPCS3.log)
Sorry about that! Here it is.

**Comment by YuriNator557** [comment]
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7118786/RPCS3.log)
> Sorry about that! Here it is.

We need the log generated by RPCS3 and not a copy of whatever was in the UI as it does not contain all the information we require. It can be found directly under the RPCS3.exe.

**Comment by pianistrevor** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7119764/RPCS3.log)
This one?

**Comment by pianistrevor** [comment]
It crashes when I hit the bug, I'll work on it.

**Comment by pianistrevor** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7119860/RPCS3.log)
Here we are!

**Comment by Darkhost1999** [comment]
Why is multithreaded RSX enabled?
Only enable settings that are needed for the game to boot or run.

**Comment by pianistrevor** [comment]
> Why is multithreaded RSX enabled?
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7123037/RPCS3.log)
Issue persists with it off. I had turned it on to improve the game's performance in the meantime because it takes roughly 5 minutes to get to the point that produces the bug and generate a log file.

**Comment by pianistrevor** [comment]
As of 0.0.21-13393-3002e592 Alpha, this is no longer an issue. Thanks!
