### ISSUE TITLE
Fedora 34 XFCE - libpng and /usr/bin/sh errors with latest build. Games not loading

### ISSUE THREAD

**Issue by tokenwizard** [RPCS3/rpcs3#10802]
## Quick summary
Running the latest AppImage build (rpcs3-v0.0.17-12698-43cc62d2_linux64.AppImage) I'm seeing Warnings int he Terminal related to libpng (see screenshot). Also, there is an error about /usr/bin/sh and 'which' that looks potentially bad (again see screenshot)

## Details

Possibly related to above-mentioned errors or related to DLC installs...
Warhawk was running fine in prior build (rpcs3-v0.0.14-11745-423cc168_linux64.AppImage). In that older build, I do still get the error about 'which' in reference to /usr/bin/sh but the game ran in that build up until I installed DLC pkg files and a "DLC Fix" pkg. Upon re-launching, I realized there was a new version available so I downloaded that. 

Now when I launch Warkhawk in either the older version or the current one, I see updated graphics related to the DLC, but while generating SPU Cache, it crashes with a Segfault. 

#### 0. Make sure you're running with settings as close to default as possible
No patches running for Warhawk and no additional setting changes have been made. 

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
Create RSX Capture option is greyed out while no games are running. 

#### 3. Please attach screenshots of your problem.
Screenshot from Terminal for troubleshooting purposes:
![image](https://user-images.githubusercontent.com/24832561/131569572-5098990c-d849-4d1c-a33a-2a5d82afd6c0.png)
![image](https://user-images.githubusercontent.com/24832561/131570058-c4b25f53-85c9-4c56-a229-5142f209c410.png)

#### 4. Please provide comparison with real PS3.
These issues were never present on PS3 and seem specific to the emulator

#### 5. Please provide your system configuration:
* OS - Fedora 34 XFCE
* CPU - AMD Ryzen 7 3800X
* GPU - AMD Radeon RX 5700 XT 8 GB GDDR6 SDRAM 
* Driver version 3314.0 (HSA1.1,LC) - OpenCL 2.0

#### Please include.
libpng errors present int he terminal only with latest AppImage build. 
/usr/bin/sh 'which' syntax error present in this build and prior build

**Comment by tokenwizard** [comment]
Ok, I removed the cache folder for this title (.cache/rpcs3/cache/BCUS98117) and relaunched the latest AppImage and now the game does at least load. 

I will try re-applying the DLC pkg files and see if it breaks again. 

FYI I am still seeing the libpng and /usr/bin/sh errors in the terminal as in the screenshot in my previous post.

**Comment by AniLeo** [comment]
Closing due to the presence of pirated game files. Dump your game legitimately and don't install any extra files that do not come from your copy of the game.
