### ISSUE TITLE
Folklore freezes at startup

### ISSUE THREAD

**Issue by LoneWolf31589** [RPCS3/rpcs3#10821]
Folklore™ [BCES00050] freezes at startup after the first or second launch. If you delete the shader cache, it will start correctly once or twice. It can also start if you restart the emulator several times.
FullHD + Vsync, the other settings are standard.

For example:
F SIG: Thread terminated due to fatal error: AU queuing error(0xffffffea): Invalid argument
(in file D:\a\1\s\rpcs3\Emu\Cell\Modules\cellVdec.cpp:304[:27], in function exec) (e=0x00000008[8])

System configuration:
Windows 10 X64 21H1
Core i7 9700F
32Gb DDR4
GeForce GTX970 (Driver 471.96)

[Screens.zip](https://github.com/RPCS3/rpcs3/files/7111383/Screens.zip)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7111400/RPCS3.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7111401/RPCS3.log.gz)

Rare error:
[RPCS3 - new log.zip](https://github.com/RPCS3/rpcs3/files/7111415/RPCS3.-.new.log.zip)
[Rare error.zip](https://github.com/RPCS3/rpcs3/files/7111417/Rare.error.zip)

**Comment by Megamouse** [comment]
I don't have this issue.
Maybe your game files are corrupt ?

**Comment by LoneWolf31589** [comment]
Error:
F VM: Access violation reading location 0x0 (unmapped memory) [type=u32]
[RPCS3_log.zip](https://github.com/RPCS3/rpcs3/files/7112083/RPCS3_log.zip)

**Comment by MSuih** [comment]
You've installed disc game as a pkg file, this mode is not supported right now. Dump the disc properly using the methods listed in quickstart.
