### ISSUE TITLE
Since version 0.0.14-11664, rpcs3 does not support cheatebootpkg and modifying eboot.bin 

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#10831]
If the modified eboot.bin (cheat file) is run, the simulator will crash and exit . If PPU Decoder is setting to interpreter, eboot.bin (cheat file) can be run normally.  But not all cheating eboot.bin are crashes, so it's strange .

**Comment by arcadee1977** [comment]
https://github.com/RPCS3/rpcs3/pull/9627

WIN10 1909
8700K
1070TI
16G

**Comment by arcadee1977** [comment]
the title is wrong, should Since version 0.0.14-11671

**Comment by Megamouse** [comment]
Does not use the issue template in any way and noone understands the problem anyway
