### ISSUE TITLE
Motorstorm - Pacific Rift (BCUS98155) Graphical Regression

### ISSUE THREAD

**Issue by SatansFavSuccubus** [RPCS3/rpcs3#10834]
Summary:
The tire tracks left by the vehicles are now completely broken textures that take on whatever colour is being rendered around them (after-image effect?) as if they were holes within the game world. Before today's update it was fine. Using previous RPCS3 .EXE builds does not fix the issue. 

**RPCS3 Version: 0.0.18-12720-00618995 Alpha** (Before this build the game was near 100% perfect emulation)

RSX Capture: https://www.dropbox.com/s/ghpiklzbdu9vzgl/BCUS98155_20210907094246_capture.rrc?dl=0

Screenshots:

https://i.gyazo.com/b3be3f94f8ca23498655438c6557f065.jpg

https://i.gyazo.com/51c0151a97f0fe10b161da66ae0a29ea.jpg

https://i.gyazo.com/50eff8162f8c310dfb9229f12769a7cb.jpg

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7123212/RPCS3.log)

**Comment by AniLeo** [comment]
Incorrect report, that build only changes tooltip text and thus is impossible that it introduced any regressions

**Comment by SatansFavSuccubus** [comment]
> Incorrect report, that build only changes tooltip text and thus is impossible that it introduced any regressions

I was playing the game a few hours ago, perfect everything, then I updated to the version that merged the zCULL relaxation thing,

**Comment by AniLeo** [comment]
Relaxed ZCULL has been merged for over a year, the recent ZCULL update made it more accurate by default, not the opposite

Missing the build that introduced the regressions as per the regression guidelines
