### ISSUE TITLE
[Feature Request] Catalan language

### ISSUE THREAD

**Issue by dragonDScript** [RPCS3/rpcs3#10835]
This is an issue to track the translation of rpcs3 to the catalan language. I'll do it myself.

**Comment by Megamouse** [comment]
There is no official translation.
See other issues

**Comment by dragonDScript** [comment]
When there is, please reopen this issue @Megamouse.

**Comment by MSuih** [comment]
Translation status is tracked in https://github.com/RPCS3/rpcs3/issues/4259, you can follow it for updates.

We have not yet decided how we will manage and accept translations, but most likely not through issues like these.
