### ISSUE TITLE
rsx branch breaks Linux build

### ISSUE THREAD

**Issue by MoochMcGee** [RPCS3/rpcs3#1084]
The Direct3D 9 renderer assumes that d3d9.h is an available header file, which is not true on Linux.

**Comment by Syphurith** [comment]
Well RSX branch is just where they test the implementation for RSX renderer out. RSX is the "GPU" used in PS3 but its internals are kept out of public. I don't think it offers Linux support currently.
BTW you can always try to fix that yourself, if later been proved working.
