### ISSUE TITLE
Audio broken on SPU LLVM - Shadow of Mordor [BLUS31059]

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#10842]
When using LLVM audio cuts out and never recovers.

ASMJIT works but LLVM has many improvements to the game.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7130052/RPCS3.log.2.gz)

**Comment by Darkhost1999** [comment]
Just a status update after the spu PR merged. Audio still cuts out.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7186567/RPCS3.log.gz)

**Comment by Yahfz** [comment]
Just tried reproducing the issue but the audio never stopped working for me. The most that happened to me was a random popping noise that latest less than a second.

**Comment by Darkhost1999** [comment]
Thanks for responding. I validated my game files, updated RPCS3, right clicked my game and booted with default config.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7278764/RPCS3.log.gz)
Within the first 5 minutes without jumping down from the tower audio cut out and never recovered.
Audio continues working fine with ASMJIT. Overall benefits still gained by using LLVM.
I can try clearing caches if it'll help.

**Comment by YuriNator557** [comment]
Confirmed on latest master
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7688705/RPCS3.log.gz)
I think it may have something to do with wraith mode? Seems to cut out around 30 seconds after using it in my case at least

**Comment by Darkhost1999** [comment]
Meanwhile audio would recover for me but go out 6 times in 5 minutes recover 7.
The frequent pop put is a little more annoying than the audio not recovering but hopeful.

**Comment by Darkhost1999** [comment]
Purely default settings. No longer reproducible. I feel like a setting does cause this. But that's why issue trackers say use default settings.
Who knows maybe it was fixed in the past couple months.
