### ISSUE TITLE
Fist of the North Star: Ken’s Rage 2 BLES01801 0.0.18-12718 vertices bug again

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#10851]
The issue 4906 was fixed in 0.98 and now is happen again , but only around of sprite and not above sprite exactly how the screenshot below being now in few size vertices.
https://user-images.githubusercontent.com/21184987/42931242-911868b8-8b15-11e8-9963-98433d3cb17c.png
Only happen when much sprites are in screen and is displayed around of more of 4 sprites on screen.
Hard to screenshot because happen in miliseconds.

reference
https://github.com/RPCS3/rpcs3/issues/4906
https://github.com/RPCS3/rpcs3/issues/4632

[RPCS32.zip](https://github.com/RPCS3/rpcs3/files/7147135/RPCS32.zip)

**Comment by Augusto7743** [comment]
The bug has returned in in another way.
I will try a video capture and after post here screenshot.

**Comment by Megamouse** [comment]
try with default settings

**Comment by Augusto7743** [comment]
The issue not happen in current version.
Need more test.

**Comment by Megamouse** [comment]
So can we close the issue then?

**Comment by MsDarkLow** [comment]
I've managed to trigger the issue, however I don't have any reliable method to do so.
Here's a clip: 

https://user-images.githubusercontent.com/9060436/145122471-9d680307-1f81-4118-a1a0-6c7344009a19.mp4

Full footage:

https://user-images.githubusercontent.com/9060436/145122494-f2132385-0cfb-4956-bd7f-c76435347ace.mp4

**Comment by Triticum0** [comment]
Had the same issue recently as well we properly need to when it regressed and also seem to affect dynasty godseekers aswell

**Comment by Augusto7743** [comment]
I will close it because that issue not happen since several previous versions.
Thanks RPCS3 team.

@Triticum0
dynasty godseekers is from Dynasty Wars series ? If yes poissibly Hokuto no Ken Ken's Rage 2 and dynasty godseekers use the same game program code.

**Comment by Triticum0** [comment]
I can still reproduce the bug
