### ISSUE TITLE
Teenage Mutant Ninja Turtles: Out of the Shadows [NPUB31217] 0.0.18-12718 not display the stage 2 boss

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#10852]
In arcade mode in stage 2 boss not is displayed the boss. The boss come in a train and is displayed correctly inside of train, but when the train open the doors the boss is vanished and the game progress to stage 3 even not fighting against the boss.
In few times the stage 2 boss is displayed.
log1 default settings and log2 accurate xfloat enabled

![4screen](https://user-images.githubusercontent.com/21184987/132934574-77518e88-1de2-4174-903c-4a7f687545dc.jpg)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7147139/RPCS3.zip)

**Comment by Bodipie** [comment]
It's cool to see someone else enjoying this game. by any chance do you still have the game files? if so, can you please send me the steam_api.dll file? The game has been removed from steam and every digital store.

**Comment by Triticum0** [comment]
Seems to be fixed
![NPUB31217_screenshot_2024_01_06_03_10_03](https://github.com/RPCS3/rpcs3/assets/71127352/b4d79c72-6575-495d-a0ac-6ad86412e56a)
