### ISSUE TITLE
Change configuration window size for Linux

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#10854]
Using here Lubuntu (Ubuntu using LXQT).
Some settings not are displayed on screen if using an 1366X768 monitor.
User need click an empty area on window and after press enter to save settings , but not is possible change not visible settings and the user need manually edit config files.

![23screen](https://user-images.githubusercontent.com/21184987/132934855-ee9c07ac-7261-47b2-bafa-2b097d7aa642.jpg)

![ssscreen](https://user-images.githubusercontent.com/21184987/132934857-893f80a7-aaf6-4986-b883-7fb2d9e40fe0.jpg)

**Comment by Megamouse** [comment]
Duplicate of #7420
