### ISSUE TITLE
Tales of Graces f [BLES01617] fails to boot after #10810

### ISSUE THREAD

**Issue by Gael2433** [RPCS3/rpcs3#10856]
## Quick summary
Tales of Graces f [BLES01617] simply exits after loading modules/cached shaders.

## Details
After #10810 the game simply exits after loading/compiling modules/shaders with the following message:
 "Unimplemented syscall syscall_988 -> CELL_OK (r3=0x4, r4=0x0, r5=0x0, r6=0x7f7f7f7f7f7f7f7f, r7=0x30000000, r8=0x8f6ab8, r9=0xffffffff, r10=0x9fd8a0)"

Broken build: RPCS3 v0.0.18-12732-f98595be Alpha #10810

#### 2. Please attach TWO logs:
Log with error:
[RPCS3_regression.log.gz](https://github.com/RPCS3/rpcs3/files/7147454/RPCS3_regression.log.gz)
Log from build before regression:
[RPCS3_working.log.gz](https://github.com/RPCS3/rpcs3/files/7147455/RPCS3_working.log.gz)

#### 6. Please provide your system configuration:
Microsoft Windows 10 Home Version 20H2 (OS Build 19042.1165)
 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
NVIDIA GeForce GTX 1070 (466.77.0.0)

#### Please include.
This came up on #help channel on the discord with the US PSN version(NPUB31133), therefore it is safe to assume that all other copies of this title are affected.

**Comment by yoshiftj** [comment]
Also running the NPUB31133. Same issue.

6. Please provide your system configuration:
Microsoft Windows 10 Professional Version 21H2
Intel(R) Core(TM) i9-9990kcp CPU @ 5.00GHz OC'd
NVIDIA GeForce RTX 2080 (471.96)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7147483/RPCS3.log)

**Comment by elad335** [comment]
@yoshiftj @Gael2433 #10857

**Comment by Gael2433** [comment]
Fixed by #10857
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7147702/RPCS3.log.gz)
