### ISSUE TITLE
No longer seeing Virtual File Systems & Firmware after last 3 updates

### ISSUE THREAD

**Issue by ThePapaw** [RPCS3/rpcs3#10862]
## Quick summary
All updates after 0.0.18-12732 Virtual File Systems and Firmware are no longer seen. Thus no roms are found. I backtracked and 0.0.18-12729 is the last working version.

## Details

Please describe the problem as accurately as possible.

#### 1. Please attach RPCS3's log.
First log is all working before update

[RPCS3 (before update).log](https://github.com/RPCS3/rpcs3/files/7149870/RPCS3.before.update.log)

Second log starts before update, then update, then after update.

[RPCS3 (before-during-after update).log](https://github.com/RPCS3/rpcs3/files/7149871/RPCS3.before-during-after.update.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc.
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 3. Please attach screenshots of your problem.
First screenshot is all working before update using v0.0.18-12729

![Before Update](https://user-images.githubusercontent.com/51170894/132994322-5b1161c0-6781-46c2-b578-a78f01cece46.jpg)

Second screenshot is after update.

![After Update](https://user-images.githubusercontent.com/51170894/132994337-e2466280-31bf-417d-a3d5-19ef41ebdce6.jpg)

#### 5. Please provide your system configuration:
* OS - Win 10 Pro
* CPU  - 8086k
* GPU - 1080TI FTW
* Driver version - 471.96
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by ehw** [comment]
I can confirm this issue occurred with 0.0.18-12732. For some reason, if I open a game manually that is supposed to be in the list, the games will reappear on the menu. However, they'll disappear again if I close out of the emulator.

**Comment by elad335** [comment]
@ehw #10863

**Comment by slyponto** [comment]
same here. any fix yet? thanks

**Comment by kd-11** [comment]
@elad335 This issue is not fixed.
Specifically, disc games are still force-reinstalling to the wrong dev_hdd0, I guess because they cannot see it is mounted externally.
This is happening with all disc games that install partial content to dev_hdd0.

**Comment by DefaltBR** [comment]
I can confirm issue is still not fixed. Same as KD-11.... I'm using a dev_hdd0 externally to the emu folder and everything seems fine until i boot a game... All other games disappear from the list as soon as you boot a game, also any game data (any updates installed) to the game you're booting dissapears along with all the others, so it boots at 1.00 disc version instead of 1.11...
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7181478/RPCS3.log.gz)

**Comment by ThePapaw** [comment]
@kd-11 @DefaltBR I am not having this issue?? It is working for me okay

**Comment by DefaltBR** [comment]
It seems it happens only when you create a custom config for the game... If you boot using global settings (either launching a game without custom config set or right clicking and selecting global settings) it launches normally and nothing disappears. If you use "custom" or "global" the issue occurs...
