### ISSUE TITLE
Dangerous option: Boot with manually selected configuration

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#10867]
The initial config override code was CLI only, and was not really meant for normal use (although some people probably used it for their 3rdParty frontend).

Since there is now a new (imho bloatware) option to manually select a config exposed to the user, there will be issues regarding options that are only meant to be present in global configs, like VFS.

Therefore this option needs to be either treated the same way as a custom config or the global config should always be applied no matter what from now on.

**Comment by elad335** [comment]
Ok, I think there is a much better solution you are not seeing: Adding a random indentifier into each global config, each user will have a unique identifier in global settings and custom settings created from will have the same identifer.
Each time a user imports a config with an identifer mismatch, VFS settings of global config should be used.
I will work on it in few days.

**Comment by Megamouse** [comment]
This is hilariously weird. Stop making everything more complicated than it needs to be

**Comment by elad335** [comment]
No, it's not weird, this is a common programming technique used for checking data expiration and comparing with source data (here VFS settings' validation checking). Ever heard of something called std::weak_ptr? This is a huge :smoothbrain: brain moment. If you have complaints and suggestions for improvements please elaborate on them.

**Comment by Megamouse** [comment]
This is not about sharing your settings with others.
This is solely about the loader implementation

**Comment by Megamouse** [comment]
Regarding your use case, I'd rather detach the VFS to a unique settings file

**Comment by elad335** [comment]
Maybe the only thing should remain in config.yml is BDVD location, because you want that per game if you ever need it. (hidden developer setting)

**Comment by Megamouse** [comment]
From discussions on github it appears that the new option is not something we should present to the user, since that is what custom configs are for and the original purpose is CLI usage only.
Furthermore it presents a new way to confuse users and also a new way to spawn GitHub issues about wrong usage etc.
The use case is very narrow here.

So I'd suggest fixing any still-present loader issue, removing or hiding the option, and if necessary discuss if such a special new settings file is something we should implement

**Comment by elad335** [comment]
The option is still a QoL change, it presents a way to test shared configs without modifying or even potentially erasing your custom config. I think there's only a problem with it's connection to hist filesystem which can be resolved.
