### ISSUE TITLE
Need for Speed: Carbon [BLUS30016] / Boot failed

### ISSUE THREAD

**Issue by xYaroslavGTx** [RPCS3/rpcs3#10864]
If game booting by "Boot with global configuration" or "Boot with custom configuration" it returning error "Boot failed: reason: Invalid file or folder, path: D:/rpcs3/dev_hdd0/disc/BLUS30016/PS3_GAME", but if game booting by "Boot with manually selected configuration", it starts normally.

![image](https://user-images.githubusercontent.com/16084829/133001472-635bccdf-45dd-4a47-b27c-b363f6c87d31.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7150228/RPCS3.log)

**Comment by elad335** [comment]
You have modified BDVD path... IT SHOULD NEVER BE TOUCHED leave it an empty string.

**Comment by elad335** [comment]
***
VFS:
  $(EmulatorDir): ""
  /dev_hdd0/: $(EmulatorDir)dev_hdd0/
  /dev_hdd1/: $(EmulatorDir)dev_hdd1/
  /dev_flash/: $(EmulatorDir)dev_flash/
  /dev_flash2/: $(EmulatorDir)dev_flash2/
  /dev_flash3/: $(EmulatorDir)dev_flash3/
  /dev_usb000/: $(EmulatorDir)dev_usb000/
  /dev_bdvd/: $(EmulatorDir)dev_bdvd/
  /app_home/: ""
***

Should empty as app_home.

**Comment by xYaroslavGTx** [comment]
Yep, solved. Thanks.
