### ISSUE TITLE
[Feature Request] Higher Mouse Acceleration

### ISSUE THREAD

**Issue by pizzabuoi** [RPCS3/rpcs3#10870]
Can you bump up the mouse acceleration please? I can barely do a 90 degree turn with several mouse movements. Could you set it to something extremly high like a 1000? It probably breaks the feature if it's too high but at least we can try.

**Comment by Asinin3** [comment]
https://github.com/RPCS3/rpcs3/issues/5909

**Comment by Megamouse** [comment]
The current maximum is 30.
Seems pretty overkill to me already.

**Comment by Megamouse** [comment]
you have to understand that at some point the acceleration doesn't matter anymore, because a DualShock3 stick only has as a maximum value of 255, which is reached pretty quickly.
Maybe try moving the mouse slower with a high acceleration value.
