### ISSUE TITLE
Star Ocean 5 - Freeze at game startup with OpenGL

### ISSUE THREAD

**Issue by Metafalica** [RPCS3/rpcs3#10879]
## Quick summary
Game boots into main menu, but when I choose to start the game it freezes at "Now loading..." screen. When Vulkan is used it freeze with different reason in same place - https://github.com/RPCS3/rpcs3/issues/10880.

#### Please provide your system configuration:
* rpcs3-v0.0.18-12750
* Windows 10 x64
* i7 880
* Radeon RX 570
* 21.4.1

#### Please include.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7179200/RPCS3.log)

When I press stop button when the game frozen I get things shown on the screenshot.
![so5_startup_freeze_open_gl](https://user-images.githubusercontent.com/5286295/133643871-0aa22bf0-726d-4ca8-a233-36caf55f0429.png)

**Comment by Asinin3** [comment]
We don't need three separate issues for this game not being able to boot. Half the log errors are not why its crashing anyway. Pls merge them
