### ISSUE TITLE
Rpcs3 crash when loading save persona 5

### ISSUE THREAD

**Issue by Smolhuman** [RPCS3/rpcs3#10872]
I get this pink error shown in pic when trying to load save and everything stops working.
Used to work very well before, no errors no crashes.
Attached log and pic

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7166933/RPCS3.log)

![whackerror](https://user-images.githubusercontent.com/52026052/133374737-334d8ad4-26a0-4e50-8dc7-2e77c58c96cf.png)

**Comment by Smolhuman** [comment]
For some context there was a power outage, save got corrupted, tried using my backup and i get this error.

**Comment by AniLeo** [comment]
Pirated game detected.
