### ISSUE TITLE
Splinter Cell: Blacklist Crash in the title screen

### ISSUE THREAD

**Issue by elementos123** [RPCS3/rpcs3#10875]
## Quick summary
The game cash in the title screen

## Details
When i start Splinter Cell: Blacklist, when arrive to the title screen i get a error in pink color

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
![image](https://user-images.githubusercontent.com/45992848/133533356-0a732578-f130-41df-8645-bce310861d76.png)

#### 2. Please attach TWO logs:
* One for the build with regression.

![image](https://user-images.githubusercontent.com/45992848/133535684-40545374-10b4-498f-916a-9bd9a3cc714b.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7174287/RPCS3.log)

**RPCS3 0.0.18-12746-e3eaf5f2 Alpha**

* One for the build that works as expected.

![image](https://user-images.githubusercontent.com/45992848/133534139-2d15cf9c-9eaa-4043-a0a2-20c5139b21cd.png)

**RPCS3 0.0.9-10152-cce946f1 Alpha**

#### 4. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

![image](https://user-images.githubusercontent.com/45992848/133535816-fda3ca11-0051-4153-a9f7-3b1109356b70.png)

#### 5. Please provide comparison with real PS3.

I don't have the real PS3, so i can't do it

#### 6. Please provide your system configuration:

* Operating system name:  Microsoft Windows 10 Home

* Operating system version:  10.0.19043 N/D Compilation 19043

Edición -> Edition
Versión -> Version
Instalado el -> Installed the
Compilación del sistema operativo -> Operating system compilation
Experiencia -> Experience

![image](https://user-images.githubusercontent.com/45992848/133534648-9bc204f5-df90-4753-a3f7-1af64929202d.png)

* AMD Ryzen 7 2700X Eight-Core Processor 4.00 Ghz

* NVIDIA Geforce 1050 TI 4GB

* Drivers -> 471.96. Date: 08/31/2021

**Comment by YuriNator557** [comment]
Are you sure 10152 is the last working build? There's a lot of builds between the two and I haven't seen anyone asking about this recently?

**Comment by elementos123** [comment]
I thought so, but after seeing your comment, I've been testing builds from 400 days ago. 

In the end I discovered that the origin of the crash is in version 0.0.11-10743 and in version 0.0.11-10742 it works at low fps, less on the loading screen that remains at 30 FPS.  

Here you have the logs of both versions:

CRASHED: -> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7177569/RPCS3.log)

WORK -> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7177620/RPCS3.log)


![Screenshot_1](https://user-images.githubusercontent.com/45992848/133610844-a31a37ca-9ea2-4cf4-87a8-a745a745b2af.png)

A greeting

**Comment by Megamouse** [comment]
seems to be a regression caused by #8710
