### ISSUE TITLE
NCAA basketball 10 BLUS30444 not responding

### ISSUE THREAD

**Issue by jpuente20** [RPCS3/rpcs3#10888]
## Quick summary
When I try to run the game for the first time. it stops on the installing phase and upon checking the logs it shows some errors. 

E cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLUS30444”, errDialog=0x0, funcStat=*0x12e7100, container=0)
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/ICON0.PNG” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/PIC1.PNG” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd1.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd4.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd6.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd7.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/boot1.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data1.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/createplayercache1.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/gfx1.big” [1]

Please describe the problem as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
https://github.com/RPCS3/rpcs3/files/7187440/RPCS3.log.gz

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

![](https://user-images.githubusercontent.com/53957416/133829854-86da549e-d1e4-4b2f-8293-6821a2524e80.png)
#### 5. Please provide your system configuration:
OS windows 10
CPU I5-10th gen
GPU GTX1650TI
Driver version
etc.

#### Please include.
* Anything else you deem to be important

**Comment by Asinin3** [comment]
Dont spam our github issue tracker....
