### ISSUE TITLE
Bug: Gran Turismo 5/6 desyncs

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#10882]
Gran Turismo games are very unstable on RPCS3, they all have random softlocks. The only setting that "helps" is using PPU/SPU interpreters which slows the game to a crawl to get a few extra minutes of gameplay.

There are two types of desyncs in these games:
- RSX desyncs: When the screen freezes but the game is still running in the background. Happens a lot in CPUs without TSX instructions, Accurate RSX Reservations helps if your CPU is good, but if it's weak and lacks TSX, you'll have them all the time.
- SPU desyncs: When the graphics still render but the game physics are frozen, so you get to see effects like smoke, rain, flashing lights and stuff like that still working, but the game and physics are frozen in time. Input doesn't work and sound is cut out. It's not specifically an SPU issue, as multiple game threads stop working, both on PPU and SPU.

SPU Desync Example
![desync](https://user-images.githubusercontent.com/61447828/133736637-698aceaf-174f-4b37-a55b-ef98c62bf72b.gif)

I've added logs for desyncs too, but they don't print any errors to the log file.

- Gran Turismo 5 Prologue
This game is the most stable, you can play for quite a long time before getting a desync. It's SPU desyncs behave differently compared to the other two games, instead of freezing the physics and input, it only cuts out the audio. If it happens mid-race, you can finish it, but the game will then freeze at the next loading screen and won't save your progress. 
I didn't manage to make the game desync in time to get a log that isn't 2gb (it spams the log a lot), but here it is anyway [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7184257/RPCS3.log.gz)

- Gran Turismo 5
The first game to get SPU desyncs that actually immediately freeze gameplay, GT5 doesn't care much about how good your CPU is, desyncs may happen quickly or take hours. More cars in a race increases the chance of a quick desync, but if you're really dedicated you can finish the game. Here's the log file: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7184529/RPCS3.log.gz) 

- Gran Turismo 6
GT6 is the most unstable of them all, along with all other issues (especially in 1.22), desyncs run rampant, being difficult to finish a race without desyncing. It's SPU desyncs behave the same as GT5. Log file: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7184661/RPCS3.log.gz) 

These tests were done with a Ryzen 5 5600x, GTX 1050 Ti running on Windows 10 21H1.

**Comment by elad335** [comment]
It's a longshot, but please test with #13631.

**Comment by Shoegzer** [comment]
Tested Gran Turismo 5 [BCUS98114], patched to 2.17, with #13631.  Unfortunately, this did not resolve the issue.  Desyncs now occur immediately at start of a race, as opposed to within 10-30 seconds on master.  

Tested with settings per the [wiki](https://wiki.rpcs3.net/index.php?title=Gran_Turismo_5) and also defaults.

Log: [RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/11184648/RPCS3.log.zip)

**Comment by steven88ita** [comment]
The ONLY time I was able to play 2+ hours without crash was when audio stopped early (like as soon as the game start).  
log: (sorry for the size)
https://www.4shared.com/s/fZw05_H8Ajq

And I'd like to report a timer-bug of IC-3 license where the game doesn't get the actual time I set
My time: 1:18:244
![ic-3 best1](https://user-images.githubusercontent.com/19331900/233777011-0f4c7c29-14ff-49d3-a1f5-cc74738bdbb0.png)
game gets 1:18:332 (so gold is not possible)
![ic-3-time bug1](https://user-images.githubusercontent.com/19331900/233777031-063018cc-18a7-4ca1-8e68-2044d7ff1f02.png)

**Comment by steven88ita** [comment]
I attached a log when the game freezed short after started, hope it helps to developers
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11301725/RPCS3.log.gz)

Would it be any useful to give you a log just after  after the sound stops working? because usually after that the game is going to freeze

**Comment by steven88ita** [comment]
I attached a log when the game freezed short after launched:

this is when crashed at start:
[RPCS3 crash start.log.gz](https://github.com/RPCS3/rpcs3/files/11304553/RPCS3.crash.start.log.gz)
this is when audio cuts (happens very often):
[RPCS3 (audio cuts).log.gz](https://github.com/RPCS3/rpcs3/files/11304552/RPCS3.audio.cuts.log.gz)
both are for very few seconds after occurring about 3 minutes logs after running rpcs3, hope it helps to developers

**Comment by Canvas02** [comment]
Here is my log from GT5 prologue, after the sound cuts off 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11525418/RPCS3.log.gz)

**Comment by Charlesna2guerra** [comment]
> [steven88ita](/steven88ita)

Sorry if this is a dumb question, but, how can i put this archive on my emulator/gran turismo game?

**Comment by hoholee12** [comment]
rsx desync still occasionally happens on latest master

**Comment by ameenross** [comment]
> rsx desync still occasionally happens on latest master. Only for GT5, I haven't encountered any freezes on GT6 however.

I can second that. Apparently I have no TSX instructions, but my CPU is definitely powerful enough. I can run a race for 2 laps just fine at about 40 FPS until it desyncs.

GT6 is quite stable, although it does require "Force CPU blit" to prevent flickering. Framerate is a little bit lower, but quite playable.

**Comment by dreams-of-formaldehyde** [comment]
This issue also occurs on real hardware. Seems to be caused by the RSX running too fast compared to the CELL, I can easily trigger this on real hardware with a fast rsx clock speed occasionally. the easiest way to trigger this is on a less demanding track where the gpu has little work to do or at 720p, You need the maximum car count possible for gt5 or 6 to reliably trigger it. Seems to be unfixable possibly as it has to do with how the game works.

**Comment by Satan86** [comment]
Obviously an unstable overclock will cause issues on real hardware, I also run an OCd RSX on my console and never ran into a single issue in dozens of hours of GT5, and RSX desyncs have already been fixed on RPCS3 with the use of Accurate RSX Reservations + Atomic RSX FIFO Accuracy.

**Comment by dreams-of-formaldehyde** [comment]
> Obviously an unstable overclock will cause issues on real hardware, I also run an OCd RSX on my console and never ran into a single issue in dozens of hours of GT5, and RSX desyncs have already been fixed on RPCS3 with the use of Accurate RSX Reservations + Atomic RSX FIFO Accuracy.

It is stable. The issue is rare but mainly occurs on any console above 600/750 and slowly increases as you go higher it seems.
I have tested:
CXD5300GGB 950/1000 (most common on here due to the high frequency, can happen multiple times in a long game session), CXD2982GB 650/850, and CXD5300DGB 700/900. They are stable for several hour sessions in The Last Of Us with the fps unlocked and the camera rotating. The main thing to understand here is that with a faster gpu on real hardware the same problem occurs. The lower the frequency the lower the chance is essentially.
