### ISSUE TITLE
NCAA BASKETBALL 10 issue 

### ISSUE THREAD

**Issue by jpuente20** [RPCS3/rpcs3#10887]
## Quick summary
When I try to run NCAA BASKETBALL with the new update but encounter an error on the install game set up

## Details
E cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLUS30444”, errDialog=0x0, funcStat=*0x12e7100, container=0)
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/ICON0.PNG” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/PIC1.PNG” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd1.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd4.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd6.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd7.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/boot1.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data1.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/createplayercache1.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/gfx1.big” [1]
Please describe the problem as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
* Run the game until you find the issue.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	E cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLUS30444”, errDialog=0x0, funcStat=*0x12e7100, container=0)
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/ICON0.PNG” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/PIC1.PNG” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd1.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd4.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd6.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data/audio/aems/xcrowd7.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/boot1.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/data1.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/createplayercache1.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30444/USRDIR/gfx1.big” [1]

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7187440/RPCS3.log.gz)
#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc.
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
![image](https://user-images.githubusercontent.com/53957416/133829854-86da549e-d1e4-4b2f-8293-6821a2524e80.png)
#### 5. Please provide your system configuration:
* OS windows 10
* CPU I5-10th gen
* GPU GTX1650TI
* Driver version
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by Asinin3** [comment]
Read the top line of your post again.
`Please do not ask for help or report compatibility regressions here, use RPCS3 Discord server or forums instead.`
