### ISSUE TITLE
Star Ocean 5 Freeze at "Now loading..." screen.

### ISSUE THREAD

**Issue by Metafalica** [RPCS3/rpcs3#10880]
## Quick summary
Game boots into main menu, but when I choose to start the game it freezes at "Now loading..." screen.
The errors in log are different for Vulkan and OpenGL.

#### Please provide your system configuration:
* rpcs3-v0.0.18-12750
* Windows 10 x64
* i7 880
* Radeon RX 570
* 21.4.1

#### Please include.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7179340/RPCS3.log) - Vulkan (Unknown magnify filter 0x0).
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7179747/RPCS3.log) - Vulkan (Unknown register name: unk)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7179791/RPCS3.log) - Vulkan (Dead FIFO commands queue state has been detected!)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7179394/RPCS3.log) - OpenGL.

When I press stop button when game is frozen with OpenGL emulator crashes with the errors on the screenshot. With Vulkan it just closes without showing any errors.
![so5_startup_freeze_open_gl](https://user-images.githubusercontent.com/5286295/133648591-cb59e0fe-6645-42a5-8c6f-aa1c3d1f14d5.png)

I think the freeze is somehow related with shaders compilation. Each time I start the game it compile more and more shaders till freeze, so each next time it goes further into gameplay because of previously compiled shaders.

**Comment by Asinin3** [comment]
The fatal Magnify error isn't why it's crashing merge with the openGL one.

**Comment by kd-11** [comment]
Needs a retest with atomic FIFO. I'll close for the moment with https://github.com/RPCS3/rpcs3/pull/13361 which solves the shader compiling crash.

**Comment by Metafalica** [comment]
What is atomic FIFO? I tested this game just yesterday and still same crashes happened. Do I need to enable something in settings?
