### ISSUE TITLE
[BCJS30042] White Knight Chronicles II JP v1.15 Text Input Bug

### ISSUE THREAD

**Issue by xsm1997** [RPCS3/rpcs3#10894]
## Quick summary

When press square button to perform in-game chat, the text input shows. Whether I cancel or confirm the text input, the input box will not show anymore, causing the game waiting for it and almost not playable.

## Details

In the game, when pressing square button to perform an in-game chat, the text input box appears prior to the in-game chat panel. After I type something or just cancel the text input, the text input box closes. At this point, the `E SYS: 'cellOskDialogAbort' failed with 0x8002b302 : 0x8002b302 [1]` shows. After that if I activate in-game chat again, no input box will be shown, and the I cannot exit in-game chat, just like the game waiting the dialog for opening. By the way, other dialog (for example, info dialog or something) will also not show, causing the game to wait for it, and not playable.

![image](https://user-images.githubusercontent.com/4453837/133929314-aaeaa6bf-0eee-46d9-80ee-4cf38a2b3177.png)

#### 1. Please attach RPCS3's log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7192167/RPCS3.log.gz)

#### 4. Please provide comparison with real PS3.

On my real PS3, when I press square button, the text input dialog will not show immediately. It will show after I press circle button to comfirm it. And I can repoen the dialog after closing it.

![IMG_20210919_213143](https://user-images.githubusercontent.com/4453837/133929478-571ca803-d275-466f-a921-d62ab7e03f45.jpg)
![IMG_20210919_213158](https://user-images.githubusercontent.com/4453837/133929480-657f33bf-70aa-4d78-a331-705cd81f183d.jpg)

#### 5. Please provide your system configuration:
* OS: Windows 11 insider beta channel
* CPU: AMD Ryzen 5800X
* GPU: Nvidia Geforce 2080Ti
* Driver version: 471.96

#### Please include.
* Anything else you deem to be important

As far as I tested, the game is playable despite the bug. Maybe you could update the compatibility list.

**Comment by Asinin3** [comment]
Did you input Japanese characters, or English characters? Some Japanese games break if you put in English letters.

**Comment by xsm1997** [comment]
> Did you input Japanese characters, or English characters? Some Japanese games break if you put in English letters. e.g NieR Replicant

Even I input nothing, the bug persists.

**Comment by xsm1997** [comment]
Okay, just figured it out.

We need to send a `CELL_SYSUTIL_OSKDIALOG_FINISHED` when aborting a OSK dialog which is using seperate windows mode. If not, the game will have an infinity loop calling `cellOskDialogAbort`.

A simple and ugly patch:

```
diff --git a/rpcs3/Emu/Cell/Modules/cellOskDialog.cpp b/rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
index 2a8c46c40..0bd9c5b3d 100644
--- a/rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
+++ b/rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
@@ -235,12 +235,6 @@ error_code cellOskDialogLoadAsync(u32 container, vm::ptr<CellOskDialogParam> dia
 
 	osk->on_osk_input_entered = [wptr = std::weak_ptr<OskDialogBase>(osk)]()
 	{
-		const auto osk = wptr.lock();
-
-		if (g_fxo->get<osk_info>().use_separate_windows.load())
-		{
-			sysutil_send_system_cmd(CELL_SYSUTIL_OSKDIALOG_INPUT_ENTERED, 0);
-		}
 	};
 
 	input::SetIntercepted(true);
@@ -340,7 +334,10 @@ error_code getText(vm::ptr<CellOskDialogCallbackReturnParam> OutputInfo, bool is
 error_code cellOskDialogUnloadAsync(vm::ptr<CellOskDialogCallbackReturnParam> OutputInfo)
 {
 	cellOskDialog.warning("cellOskDialogUnloadAsync(OutputInfo=*0x%x)", OutputInfo);
-	return getText(OutputInfo, true);
+	auto result = getText(OutputInfo, true);
+	g_fxo->get<osk_info>().use_separate_windows = false;
+	g_fxo->get<osk_info>().osk_continuous_mode  = CELL_OSKDIALOG_CONTINUOUS_MODE_NONE;
+	return result;
 }
 
 error_code cellOskDialogGetSize(vm::ptr<u16> width, vm::ptr<u16> height, u32 /*CellOskDialogType*/ dialogType)
@@ -382,6 +379,12 @@ error_code cellOskDialogAbort()
 		// Check for open dialog. In this case the dialog is only "Open" if it was not aborted before.
 		if (state == OskDialogState::Abort)
 		{
+			if (g_fxo->get<osk_info>().use_separate_windows.load())
+			{
+				sysutil_send_system_cmd(CELL_SYSUTIL_OSKDIALOG_FINISHED, 0);
+				return static_cast<s32>(CELL_OK);
+			}
+			
 			return static_cast<s32>(CELL_MSGDIALOG_ERROR_DIALOG_NOT_OPENED);
 		}
 
```

Notice 1: We should not fire the `CELL_SYSUTIL_OSKDIALOG_INPUT_ENTERED` command every time we type a character. That will lead to the game sending all incomplete inputs once we type a character.

Notice 2: We should clear the seperate windows relate flags when unloading an OSK dialog. If not, the regular OSK dialog opening the next time will not work properly, as it thinks to be a seperate windows dialog, which is sending `CELL_SYSUTIL_OSKDIALOG_INPUT_ENTERED` not `CELL_SYSUTIL_OSKDIALOG_FINISHED` when ending input, causing no input and OSK dialog never shows twice in the game.

I do not know if the ugly patch is in real behavior of a real PS3, and if it can break other games. But it works fine to the game, while also have some acceptable bugs:

1. When cancelling the OSK dialog, it will lead to an immediately open of another same OSK dialog.
2. When finished the OSK dialog, whether typing anything or not, the game remains at in-game chat panel. When we press circle, it reactivates OSK dialog without setting seperate windows flags. And that leads the game to ignore the input, and fires another same OSK dialog with setting seperate windows flags.

BUT I think those bugs violate the normal logic of a real PS3. On a real PS3, text input lies on the in-game chat panel, and it does not show OSK dialog at first. When pressing circle, the OSK dialog appears. I think since the time we enter in-game chat panel, the OSK dialog routines are applied. We should not face the condition that OSK dialog closed when opening in-game chat panel in normal logic.

So maybe we should write a functional OSK dialog with seperate windows?

Looking forward to your great work! :)

**Comment by Megamouse** [comment]
Seperate windows mode hasn't been implemented yet.
I wrote the current seperate windows behaviour solely on a (less) educated guess.

The hack you are presenting is not optimal, I can try to look into it sometime.
Anyway, there is another issue open for this (related to metal gear online)

**Comment by xsm1997** [comment]
I can comfirm using Qt windows the main bug of the issue does not happen.

But I think the rest of the patch should be applied, as they are not hack.

For notice 1, if not do so, the every character I typed in the Qt window will send out. This is not intentional indeed.
For notice 2, if not do so, after opening a separate windows mode OSK dialog, closing it, then opening a regular OSK dialog, closing it, and then I cannot open the regular OSK dialog again. (the `use_separte_windows` flag never set to false)

**Comment by Megamouse** [comment]
Please test with the linked Pull Request

**Comment by xsm1997** [comment]
The issue is not resolved when using native ui. When using Qt ui, all worked fine.

here are the logs:
[RPCS3.native.log.gz](https://github.com/RPCS3/rpcs3/files/7196140/RPCS3.native.log.gz)
[RPCS3.qt.log.gz](https://github.com/RPCS3/rpcs3/files/7196141/RPCS3.qt.log.gz)

When native ui enabled, I did following steps in game:
1. Opened the in-game chat panel by pressing square button.
2. The native OSK dialog showed up. I cancelled the dialog by pressing cross button.
3. Pressed cross button to exit in-game chat panel.

Then the game fell into an infinity loop calling `cellOskDialogAbort`.
If I input something or just accept the OSK dialog in step 2, the message will send out and immediately another OSK dialog will show up. I cannot exit in-game chat panel. This is the correct logic of the game in real PS3, because the game excepts continuous input, and it will fire an OSK dialog again after the previous dialog closed.

By the way, the game will still send out every character I input with the PR applied. Simply remove the logic in `on_osk_input_entered` can solve the issue, but I do not know if it is optimal.

**Comment by Megamouse** [comment]
You were right. Although the implementation wasn't as straightforward as just changing a couple of lines of code.
Please try again with the updated pull request.

**Comment by Megamouse** [comment]
ah. wait. There's still some more logic to add

**Comment by Megamouse** [comment]
It should now work to some extent.
The main issue remaining - if you ignore the fact that we always show a fullscreen dialog at the moment - is that we currently always just open the dialog in a blocking fashion during the load phase and then just close it again.
In theory it has to run async and stay open until it is closed by the game (in this case).

**Comment by xsm1997** [comment]
The issue is resolved by appling the updated PR.
I will close the issue when the PR get merged.
