### ISSUE TITLE
My RPCS3 does not open

### ISSUE THREAD

**Issue by SolicitedPoet2** [RPCS3/rpcs3#10892]
My problem is that my RPCS3 does not open at all, this is just visible in task manager and this is not showing up
So I went to see the log file and what showed up is this: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7190500/RPCS3.log)
I tried to reinstall my graphics drivers and it didn't work
Any solution?

Please provide your system configuration:

OS:Windows 10

CPU:i5-10400 2.90 GHZ

GPU:Nvidia Geforce GTX 1650

Driver version:471.96

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
