### ISSUE TITLE
[BLUS30009] Full Auto 2: Battlelines graphical issues

### ISSUE THREAD

**Issue by wolfestridershooter** [RPCS3/rpcs3#10890]
## Quick summary:
Graphical errors that appear in Full Auto 2: Battlelines that seem to be based on distance from the object.

## Details:
Particle effects become progressively more green as the camera moves away from them.

Particle effects become blocky as the camera moves away from them.

Dynamic destruction created models (I think they are called that) show corrupted textures as the camera moves away where breaks in the original non broken model occur.

#### 1. Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7187724/RPCS3.log.gz)

#### 2. RSX captures:
https://mega.nz/file/kCp0hLxL#o5St1k0SnABQRl9dm34Fh6-3uMwHKjypBgJyGgcM0X8

#### 3. RenderDoc captures:
I followed the provided guide in the default debug post but couldn't figure out how to get RenderDoc working with RPCS3 so sadly I can't provide any captures.

#### 4. Problem in action:
https://www.youtube.com/watch?v=RfLRxR37sH8
Through almost the entire video you can see the green particle issue.
From 1:38 to 2:33 you can see the blocky particle effect issue.
From 2:40 to until the end of the video you can see corrupted texture issue.

#### 5. Comparison with real PS3:
https://www.youtube.com/watch?v=3BD340ofbeU
From 14:35 to 14:40 you can see that the fire and other particle effects render correctly.
At 22:39 you can see that same support that was shown in my video looks fine in this video on real PS3 hardware.

#### 6. System configuration:
* OS: Windows 10
* CPU: i7 6700k
* GPU: 2080 SUPER
* Driver version: 471.96
* RPCS3 version: 0.0.18-12757-b30ac485

**Comment by Asinin3** [comment]
Still an issue? did you try turning Write Color Buffers on, and other depth buffer settings on advanced tab?

**Comment by ChwaraeTeg** [comment]
Tested on RPCS3 v0.0.29-15723-8c0debfe using default settings, wasn't able to reproduce any of these issues.
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13460922/RPCS3.log.gz)

**Comment by kd-11** [comment]
Closing as fixed. If the problem can be reproduced, request to reopen.
