### ISSUE TITLE
THE DARKNESS (BLUS30035 + BLES00058) ALT + ENTER / DOUBLE CLICK into OR out of FULL SCREEN drops FRAMERATE. 

### ISSUE THREAD

**Issue by SolomonGrundyThanksForTheTurkey** [RPCS3/rpcs3#10907]
THE DARKNESS (BLUS30035 + BLES00058) experiences a massive drop in framerate when ALT+ENTER or DOUBLE CLICK are used to ENTER or EXIT FULL SCREEN.

More information in my second comment below.

**Comment by Darkhost1999** [comment]
Can you confirm the specific build to break the game and provide logs for both following the regression report template?

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
I believe the build is : 0.0.18-12802

I've attached both logs below (1st one is the game running as it should just not in full screen, second is the regression when entering full screen):

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7207255/RPCS3.log)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7207267/RPCS3.log)

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
Still happens on latest build : 0.0.18-12810

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7210252/RPCS3.log) - adding this log of the unstable framerate bc it looks vastly different from the others after setting SPU block size to mega w no change.

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
interestingly enough, the game seems to go back to stable fps when you die (loading in a death cutscene) and reload into the level - but attempting to full screen after it has fixed itself leads back to an FPS drop.

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
Can confirm this only happens with The Darkness. Every other game tested works at a constant 60FPS regardless to full screen or windowed.

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
I may be wrong, but it seems the logs indicate an eject and reinsert disc function upon full screening & it janks up everything.

**Comment by kd-11** [comment]
Could be related to https://github.com/RPCS3/rpcs3/issues/10910

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
Testing it right now, with latest build... and that fixes it!

 Thanks so much for your hard work !
