### ISSUE TITLE
Can't load elf file in some location

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1090]
Hi,
if I load an elf file located in "E:\UsersData\Desktop\SWemu\tests\gcm\cube\cube.ppu.elf" the load fails.
However if I load it from "E:\UsersData\Desktop\cube.ppu.elf" it works.

I suspect there is a bug with long path but I have no idea why.

**Comment by Syphurith** [comment]
I haven't ever experienced such when using master branch. Are you talking about rsx branch?

**Comment by vlj** [comment]
No, I'm talking about the master branch.

**Comment by vlj** [comment]
I have some details with warning level :

W fs::file::open('C:/Users/Vincent/Documents/GitHub/ps3autotests/tests/rsx/dev_bdvd.path', 0x1) failed: error 0x2
W fs::file::open('C:/Users/Vincent/Documents/GitHub/ps3autotests/tests/rsx/PARAM.SFO', 0x1) failed: error 0x2
W fs::file::open('C:/Users/Vincent/Documents/GitHub/rpcs3/bin/dev_usb000/ps3autotests/tests/rsx/primitives/primitives.ppu.elf', 0x1) failed: error 0x3
E Opening 'C:\Users\Vincent\Documents\GitHub\ps3autotests\tests\rsx\primitives\primitives.ppu.elf' failed
S (S)ELF: boot done.

**Comment by Syphurith** [comment]
Please show the full log and the git hash of the commit. 487 files different between rsx and master now.
I tried to find `open("` and `Opening` in rsx branch of rpcs3 but failed (used astrogrep).

**Comment by Bigpet** [comment]
Hm, those are "0x2 File not found" and "0x3 Folder not found". I wonder, my first suspicions are either the forward slashes (unlikely) or some issue with "ConvertUTF8ToWChar" (my best bet at the moment)

**Comment by Syphurith** [comment]
The `/` and `\` caused much troubles. However i would still wait for the corresponding git hash value.

**Comment by Bigpet** [comment]
why? I can reproduce this in master and there haven't been many changes in the file or vfs code?

**Comment by Syphurith** [comment]
You reproduced the issue? I ran the rpcs3 executable with a longer name days ago.

**Comment by Bigpet** [comment]
It's not about the length of the names. I could reliably reproduce this by cloning rpcs3 and the autotests into the same directory and opening any of the autotests.

**Comment by Bigpet** [comment]
Well the issue seems rather unrelated to the file opening, but rather that the folder gets translated to "rpcs3/bin/dev_usb000"

**Comment by Syphurith** [comment]
Oh.. I loaded several autotest elfs but not ever meet such an issue. That may due to the path config..

**Comment by Bigpet** [comment]
Alright it's `vfsDevice* VFS::GetDeviceLocal(const std::string& local_path, std::string& path) const` that's broken. I just need to think about which method is correct. Either returning "/dev_usb000/../../ps3autotests" so going beyond root or just returning vfs devices that have a full sub-path match. I think going beyond root might be confusing so I tend to favor the latter.

Both methods work in the case of opening simple *.elf files but the first method just feels wrong

**Comment by Syphurith** [comment]
So glad you find out why. ~~Waiting for full compiler warnings..~~ Hope it be solved.
