### ISSUE TITLE
Samurai Warriors 4 : Empires Audio issue and graphic flickering

### ISSUE THREAD

**Issue by rubyr47** [RPCS3/rpcs3#10909]
i just download rpcs3 today and i never use this before but when i try SW4:Empires the audio is little bit.. strange like corrupt ddrrreeeeeeekkkkkk something like that and graphic sometime flickering in black color. please help me thank you :)

**Comment by MSuih** [comment]
Github isn't the place to ask support from. Join our Discord instead
