### ISSUE TITLE
Motorstorm Pacific Rift crashes on some tracks

### ISSUE THREAD

**Issue by captainh00ch** [RPCS3/rpcs3#10908]
## Quick summary

Motor Storm Pacific Rift crashes on some tracks. It seems semi-random, but I've had consistent crashes on one. (Second one on Earth festival)

## Details

The game starts and works fine, and the tracks that don't crash run relatively well on 20-30 fps. Menu as well.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7210342/RPCS3.log)

* OS Win10 Pro 64bit Ver. 20H2 Build 19042.1237
* CPU AMD Ryzen 7 3700X @ 3.60 GHz
* GPU GTX 1080
* Driver version GeForce GRD Ver.457.51

EDIT: Updated Nvidia drivers, issue persists

**Comment by Asinin3** [comment]
What the hell are these settings? PPU Fast interperter? Accurate Xfloat on a game that doesn't need it? You're also using mega block size which can hurt stability. And community game patches. Also Multi-threaded RSX has issues with Write color Buffers and can cause stability issues, turn MT RSX off, it barely affects performance anyway. Go back to default settings + wcb and try it again. Regardless, the log doesn't show any kind of fatal error and you didn't list a way to reproduce the issue or anything so a developer can't really do anything with this.

Closing.

**Comment by captainh00ch** [comment]
Haha oh man oh god I'm completely new to this emulation thing. I couldn't really find any good info on the best settings for the game so I just kinda goofed around till it worked like a madman with a hammer in a TV repair shop. I'll look into your feedback and see if I can't fix it myself. Thank you so much for answering.

**Comment by Asinin3** [comment]
As far as settings go, typically just defaults + upping res scale and maybe turning on anisotropic filtering works for most titles. Then you just check the wiki https://wiki.rpcs3.net/index.php?title=MotorStorm:_Pacific_Rift for any required settings. I would ask in our discord server https://discord.me/rpcs3 before opening an issue on GitHub if you're not sure about it.

**Comment by captainh00ch** [comment]
Thanks for the info. I realized the problem was that I'd goofed up burning the disc. I reburned, and saw that I was missing like 2 gigs last time. New burn works like a charm.
