### ISSUE TITLE
`Linking CXX executable ../bin/rpcs3` fails

### ISSUE THREAD

**Issue by kattjevfel** [RPCS3/rpcs3#10913]
## Quick summary
When compiling rpcs3-git from AUR all goes well up until the very last step where the build fails.

## Details

I am not quite sure at what commit things broke, but I have 9c2d94ca1aa1bf03dc8c594e6c167b27a952e41c compiled and running well, so it's some time after that commit, I'll have to bisect later.

I am running Arch Linux and am compiling in a clean chroot with the stable repos.

```
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Input/pad_thread.cpp.o
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Input/xinput_pad_handler.cpp.o
[100%] Linking CXX executable ../bin/rpcs3
/usr/bin/ld: rpcs3qt/librpcs3_ui.a(mocs_compilation.cpp.o):(.data.rel.ro._ZTV16osk_dialog_frame[_ZTV16osk_dialog_frame]+0x78): undefined reference to `osk_dialog_frame::Close(bool)'
/usr/bin/ld: rpcs3qt/librpcs3_ui.a(mocs_compilation.cpp.o):(.data.rel.ro._ZTV16osk_dialog_frame[_ZTV16osk_dialog_frame]+0x98): undefined reference to `non-virtual thunk to osk_dialog_frame::Close(bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/build.make:467: bin/rpcs3] Error 1
make[2]: Leaving directory '/build/rpcs3-git/src/build'
make[1]: *** [CMakeFiles/Makefile2:11848: rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make[1]: Leaving directory '/build/rpcs3-git/src/build'
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/build/rpcs3-git/src/build'
```

**Comment by Megamouse** [comment]
I can't find anything that indicates that behaviour.
Try a realclean for libemu and librpcs3

**Comment by kattjevfel** [comment]
Assuming you mean `make realclean`, that can't really be applied since I start from scratch each build, there's nothing to clean.

**Comment by kattjevfel** [comment]
It builds outside of the chroot, must be something wrong with my system, ccache or missing dependencies in the pkgbuild (that is then perhaps pulled in automagically on my system). Closing as it's not this projects fault.
