### ISSUE TITLE
vulkan: large performance regression since 0a8d9a12

### ISSUE THREAD

**Issue by Oschowa** [RPCS3/rpcs3#10911]
Since commit 0a8d9a12, there is a large performance regression when using the vulkan renderer on my system in multiple games (tested with RAGE and Demon's Souls, log files are from RAGE). E.g. RAGE goes from 60 fps to around 15 fps in some scenes with `perf` showing most of the time is spent in memmove.

#### 2. Please attach TWO logs:
* One for the build with regression.
[RPCS3-broken.log.gz](https://github.com/RPCS3/rpcs3/files/7212863/RPCS3-broken.log.gz)

* One for the build that works as expected.
[RPCS3-working.log.gz](https://github.com/RPCS3/rpcs3/files/7212869/RPCS3-working.log.gz)

#### 6. Please provide your system configuration:
* OS Arch Linux
* CPU Ryzen 3700x
* GPU AMD 6700XT
* Driver version RADV git or AMDVLK v-2021.Q3.6

This system has resizable BAR, including vulkaninfo just in case:  
[vulkaninfo.txt](https://github.com/RPCS3/rpcs3/files/7212877/vulkaninfo.txt)

**Comment by MSuih** [comment]
Add your game to #10910 instead, no need to open multiple issues for same bug
