### ISSUE TITLE
Meta: performance regression after #10900

### ISSUE THREAD

**Issue by YuriNator557** [RPCS3/rpcs3#10910]
## Quick summary
After PR #10900, DJ Hero 2 runs a lot slower than it did before.

## Details
Before regression it was running at a smooth 60fps on every stage, now the performance is cut in half at best (averages about 25-30fps)

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
RPCS3 v0.0.18-12802-3c7ada8e Alpha

#### 2. Please attach TWO logs:

[dj2slow.log.gz](https://github.com/RPCS3/rpcs3/files/7212851/dj2slow.log.gz)
[dj2notslow.log.gz](https://github.com/RPCS3/rpcs3/files/7212854/dj2notslow.log.gz)

#### 4. Please attach screenshots of your problem.

![normal speed](https://user-images.githubusercontent.com/76178650/134397241-d252b709-c951-471c-9e68-d4470f2ce6e8.jpg)

![slowspeed](https://user-images.githubusercontent.com/76178650/134397271-4a856151-ed55-40d4-aecc-04f13a83b032.jpg)

#### 5. Please provide comparison with real PS3.
Solid 60fps on every stage.

#### 6. Please provide your system configuration:
* OS: Windows 10 21H1
* CPU: Ryzen 7 5800x
* GPU: RTX 2070 Super
* Driver version: 471.96

**Comment by kd-11** [comment]
Including https://github.com/RPCS3/rpcs3/issues/10911 here as well

**Comment by kd-11** [comment]
I accidentally broke the upload heap, a fix is on the way.
