### ISSUE TITLE
RESISTANCE FALL OF MAN (BCUS98107) freezes randomly during gameplay

### ISSUE THREAD

**Issue by SolomonGrundyThanksForTheTurkey** [RPCS3/rpcs3#10919]
Build : 0.0.18-12815-e4aff539 ALPHA

Previously I've played 10 hours without any crashes, now I experience crashes at random intervals in time... sometimes 5 minutes, sometimes an hour. 

Only setting that differs from global is a V-blank of 120, but it happens when you use global config as well. 

Below is a log of the crash:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7220313/RPCS3.log)

**Comment by AniLeo** [comment]
Does not follow issue guidelines, missing what build regressed it.

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
most likely its the current build, as I mentioned above - it worked previously as i played almost 9 hours with no issues on the previous build.

**Comment by AniLeo** [comment]
We need exact bisecting, follow the issue guidelines

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
Apologies, but unfortunately I can't provide that - but hopefully someone else can.

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
I'm going to close this - after a few more hours of testing, I can confirm the freeze happens on one specific level, but isn't always a guarantee... so you can complete the level before the chance of a freeze.

there are no more freezes following level completion.
