### ISSUE TITLE
Online play on Skate 3

### ISSUE THREAD

**Issue by Alpher-Dark** [RPCS3/rpcs3#10924]
## Quick summary
Please briefly describe what feature you would like RPCS3 to have.

## Details

Online play on RPCN on PSN for Skate 3.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay

#### 2. Please tell us, why your feature is important to RPCS3.
Because online play would be nice

#### 4. Please provide your system configuration:
* OS: Windows 10 21H1
* CPU: Intel i7 10875H
* GPU:Nvidia GeForce RTX 2070 SUPER Max-Q
* Driver version: 471.96
* RAM: 16GB 2933 Mhz

#### Please include.
Skate 3 to have the latest update, if possible, if not at least PSN online play.

**Comment by Asinin3** [comment]
Skate 2/3 already has a developer looking at making a custom server https://docs.google.com/spreadsheets/d/1Wn2EkQj_bZpgrT-xiDbqHkx91jcCHn34nXkl2Sv0GOs/edit#gid=0
But that's besides the point. Don't open useless issues like this..

**Comment by MSuih** [comment]
To clarify, we will not implement custom servers as part of rpcs3. Those will be separate projects
