### ISSUE TITLE
Graphic bug NARUTO SHIPPUDEN - Ultimate Ninja STORM Generations BLUS30792

### ISSUE THREAD

**Issue by CbS78** [RPCS3/rpcs3#10922]
When passing the game, I found this graphic bug! https://imgur.com/a/jwlNkZN
Is there a way to fix it?

**Comment by CbS78** [comment]
How can I issue a message about this error so that it is not closed?

**Comment by YuriNator557** [comment]
Maybe if you followed the template that appeared instead of entirely ignoring it...

**Comment by CbS78** [comment]
Excuse me! They couldn't help me on the forum, so I turned here. Then, I'll just wait until this is fixed in subsequent versions of the emulator. Thanks!
