### ISSUE TITLE
NARUTO Shippuden: Ultimate Ninja Storm Generations [BLUS30792] Graphic Bug

### ISSUE THREAD

**Issue by CbS78** [RPCS3/rpcs3#10923]
Problem Details: The default settings are used! When using Naruto's Ultimate Jutsu, a hissing effect appears on the characters. The game works stably at 30 FPS, no more graphic errors, except for this one, were noticed! In any arena, when fighting with any character, if you choose Naruto (Rasenshuriken), when using Ultimate Jutsu, a hiss effect appears on both characters.

RPCS3 log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7229260/RPCS3.log.gz)
 RSX Capture: [RSX Capture.zip](https://github.com/RPCS3/rpcs3/files/7229215/RSX.Capture.zip)
Details:
-RPCS3 RPCS3 v0.0.18-12817 ]-
-Game: NARUTO Shippuden: Ultimate Ninja Storm Generations [BLUS30792]
-Issue: a hissing effect appears on the characters. [Vulkan/OpenGL]
OS: Windows 8.1 64-bit
CPU: i3-6100 3.70 GHz
GPU: GT 730 2 GB GDDR5
Driver version: 471.68.0.0

Emulator: ![img](https://i.imgur.com/oGkcDMk.png)
PS3: ![img](https://i.imgur.com/zHlwCe9.png)

**Comment by Asinin3** [comment]
It's possible this is fixed with settings. Try all the buffer settings on advanced tab, strict mode on gpu tab, with write color buffers. And use ASMJIT Recompiler. Also your log is broken and just has hex...?

**Comment by Asinin3** [comment]
Ok so yeah you broke the log file by renaming it from rpcs3.log.gz to rpcs3.log and then zipping it.... When you should've just uploaded it as rpcs3.log.gz without changing anything. Well it works if you rename the file back

**Comment by CbS78** [comment]
I have corrected the RPCS3 log file.

**Comment by CbS78** [comment]
Unfortunately, none of the settings that You recommended helped!

**Comment by Asinin3** [comment]
Thats fine. It's worth testing just incase, edit the first post with the settings you tried and lets clean up the comments :)

**Comment by CbS78** [comment]
Do you mean to change the RPCS3 log to a new one, with new settings?

**Comment by CbS78** [comment]
I have updated the RPCS3 log

**Comment by Asinin3** [comment]
No, I meant to delete comments that are irrelevant because there was too many cluttering up the issue report. And edit the original post with all the settings you used so its cleaner.
