### ISSUE TITLE
Resolution Scale (Disable Strict Mode) can be adjusted by an amount other than 25%

### ISSUE THREAD

**Issue by Nicholas-Steel** [RPCS3/rpcs3#10932]
## Quick summary
Resolution Scale (Disable Strict Mode) can be adjusted by an amount other than 25%

## Details

This slider is meant to increment/decrement in lots of 25% but if you mess around with it enough by dicking around with the mouse you can make it change by a different amount!

It seems to happen when clicking (and holding down the mouse button) on a vacant portion of the bar to cause the Slider to move along it and then as you continue to hold the mouse button down... repeatedly moves the Slider along the bar rapidly in increments/decrements of 25% until the Slider reaches your mouse courser position. When it starts moving repeatedly, slide the mouse courser along the bar as it does so.

#### 3. Please attach screenshots of your problem.
![unknown 2](https://user-images.githubusercontent.com/11567846/134801341-71ecaff2-3d7d-4c55-b56b-c5e737e3cdc6.png)
![unknown](https://user-images.githubusercontent.com/11567846/134801342-41e0c3a8-3872-4ebc-bc5b-1d37dd580436.png)

#### 5. Please provide your system configuration:
Windows 10 21H1
RPCS3 Version: 0.0.18-12824-df96be19 Alpha

**Comment by Asinin3** [comment]
This isn't a bug. Arrow keys work too btw.

**Comment by Megamouse** [comment]
not our issue. we just use the parametrized Qt slider
