### ISSUE TITLE
Tekken Tag Tournament 2 Black Screen with DLC installed

### ISSUE THREAD

**Issue by Krizael** [RPCS3/rpcs3#10946]
## Quick summary
After Installing the DLC for Tekken Tag Tournament 2, a ·F 0:01:09.116740 {PPU[0x1000021] Thread () [0x00368018]} SIG: Thread terminated due to fatal error: PPU Trap! occurs

## Details
I've downloaded and updated the emulator to latest version (0.0.18-12846) and installed ps3 firmware version 4.88
Next, I've added the game, using the "add game" option and proceed to install the packages containing the DLCs
With only the updates packages, the game run as intended, but after the installation of the Character and Stages DLC, the above error kept occurring, no matter the version of the game.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7252405/RPCS3.zip)

Windows 10 Pro 21H1
Ryzen 7 3700X Overclocked (4.4GHZ
Zotac GTX1060 6GB
GPU driver ver. 472.12.0.0
24GB  RAM 3000 Mhz

**Comment by RainbowCookie32** [comment]
Bad settings, missing licenses, DLC from a different region. Unlikely that it's an issue with the emulator itself, looks more like a broken pirated game or user error.
