### ISSUE TITLE
Error while linking PPU Modules

### ISSUE THREAD

**Issue by tpdsantos** [RPCS3/rpcs3#10947]
Hey all,

I used this emulator before with great success in the past (don't remember version but the last time I played it was in the end of last year).

All this time had passed and I remembered to play again, so I downloaded the latest version from the official website and I get the error found in the log file, regarding the `SPURecompiler.cpp` file.

I tried with the three games that I have (Dante's Inferno, God Of War Collection I and II) but with no success, the game gets stuck during compilation stage always in the last module, specifically during "Linking PPU Modules"

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7259615/RPCS3.log)

What could that be?

Thank you,
Tiago

**Comment by mochyusup** [comment]
Got the same problem right after I updated mine just now. Every game got that same error now.
![image](https://user-images.githubusercontent.com/8454063/135462112-b8788b71-bf5e-47b1-8943-7576c06d98ae.png)

**Comment by Asinin3** [comment]
Probably a regression on avx-512 CPU's only. Revert to https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-8b3a3e4ac825689d1a8879a465c822c9c0065676/rpcs3-v0.0.18-12852-8b3a3e4a_win64.7z
Latest worked for me on the mentioned games but I don't have an avx-512 CPU.

**Comment by mochyusup** [comment]
Confirmed that reverting it to that version works fine. So it is indeed a bug that's introduced recently. Thanks.

**Comment by Nekotekina** [comment]
Oops.

**Comment by MSuih** [comment]
@tpdsantos @mochyusup Either of you willing to test the fixup?
Download windows artifact from here: https://cirrus-ci.com/task/4948199254261760

**Comment by tpdsantos** [comment]
I can test but only at night, will write back with the result

**Comment by mochyusup** [comment]
I've confirmed that in RPCS3 Version: 0.0.18-12859-71b15c1f Alpha, the problem is now fixed. Thanks.

**Comment by tpdsantos** [comment]
I confirmed it as well, works perfectly now, thank you very much
