### ISSUE TITLE
MotorStorm Apocalypse [BCES00484] MC/ATV driver doesn't render correctly

### ISSUE THREAD

**Issue by captainh00ch** [RPCS3/rpcs3#10940]
On the story mode, the MC/ATV driver model isn't rendered correctly, but rather invisiblish. This also occures sometimes when customizing vehicles. The model renders correcly once the game is paused (ingame pause, not emu pause) It also renders correctly more often when run through RenderDoc (But then the framerate is like 1FPS and everything else is super wonky so I guess that's too big a trade off) The glitch usually starts when the intro sequence is complete and the race starts. I have on rare occations had the model render correctly for about a second before glitching out. The game itself is playable and the glitch doesnt seem to have any impact on performance.

Screenshots:
![msapoglitch](https://user-images.githubusercontent.com/91194747/134980764-16e55082-cb00-49e9-8693-3b0c0a3b8f04.JPG)

![msapoglitch_2](https://user-images.githubusercontent.com/91194747/134985283-3c511eb2-4835-4591-b7a8-3e280471ae61.JPG)

Log:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7239167/RPCS3.log.gz)

RSX Capture:
https://drive.google.com/file/d/1t630vAo8CK-f_t2fmUteZImd3LyuM4i8/view?usp=sharing

RenderDoc Capture:
https://drive.google.com/file/d/1yh45vnhKQu1U3IjM3IU3xv8Hs6wX5Tnu/view?usp=sharing

Specs:
Windows 10 Pro 20H2 (Build no. 19042.1237)
GeForce 1080
Ryzen 7 3700X @ 3.60 GHz
32GB DDR4 @ 1066MHz

**Comment by Megamouse** [comment]
please disable all patches and try again

**Comment by captainh00ch** [comment]
Disabled all patches, and tried again. Problem persists.

Screenshot:
![image](https://user-images.githubusercontent.com/91194747/135995804-e907da16-4b55-49ea-8b37-28f5bc11aedc.png)

Log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7284473/RPCS3.log.gz)
:

**Comment by captainh00ch** [comment]
Hey! This no longer happens! How neat.

**Comment by MSuih** [comment]
This isn't happening for me either, I think the issue can be closed now.
