### ISSUE TITLE
Deadlock in rsx_fp_dynamic_test2.ppu.elf

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1094]
When running the rsx_fp_dynamic_test2.ppu.elf, it works for a 4 or 5 seconds (it's a dezoom effect), then the emulator halts. It waits at line 106 in Callback.cpp.
The callstack is quite short : 

rpcs3-x64.exe!CallbackManager::Init::__l2::<lambda>() Line 106	C++
rpcs3-x64.exe!thread_t::start::__l2::<lambda>() Line 1405	C++

**Comment by raven02** [comment]
RSX branch has fixed some GCM callback issue but not too sure if related to this or even can apply to master branch

https://github.com/RPCS3/rpcs3/commit/4574d08e652d12747614b25ad6101f0568053779

**Comment by raven02** [comment]
@vlj , this is the real running of rsx_fp_dynamic_test2.ppu.elf .Thanks @O1L sharing this to me .

https://www.shadertoy.com/view/ldf3DN

**Comment by vlj** [comment]
I have this error message, don't know if it's related or fixed by rsx branch :

E {RSXThread} Exception: RSXThread::ReadIO32(addr=0x1eed0000): RSXIO memory not mapped

**Comment by raven02** [comment]
Yes #1097 did fix this issue however it break some of other games that also result in "RSXIO memory not mapped"

**Comment by vlj** [comment]
Is vm::ptr<CellGcmContextData>::callback well emulated ?
I'm trying to enable the jump flag but for some reasons I have "bad flip" error now with Arkedo2, and it never returns.

**Comment by vlj** [comment]
When the RSXIO memory not mapped error is thrown, the offset parsed by RSXThread is wrong at this line :
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/RSXThread.cpp#L2510

It takes values that looks deterministic. I don't know why but it looks like JUMP instruction are modified (corrupted ?) in a deterministic fashion.

Forcing the offset to 0 in RSXThread.cpp "fix" the error for Arkedo 2 but the rendering is wrong with lot of "illegal/unknow command" error.
Does rpcs3 support multiple command buffer ? PS3 app allocate command buffers per 64kb chunk that can be subdivided in 2, maybe it's what's Arkedo 2 is doing.

**Comment by raven02** [comment]
@DHrpcs3 ,any insight here?

**Comment by vlj** [comment]
This commit https://github.com/vlj/rpcs3/commit/27d5941b244dec1a1d96d81712621931b0b39325 seems to fix both dynamic test 2 and arkedo 2.

Unfortunatly sometimes the app refuses to launch with a sys_fs_error for instance, or a segfault when launching interpreter.

**Comment by vlj** [comment]
Fixed
