### ISSUE TITLE
RAPs not being moved to the proper place

### ISSUE THREAD

**Issue by jacob1218** [RPCS3/rpcs3#10951]
## Quick summary
#10849 changed the file structure of RAPs, but RPCS3 still installs them incorrectly

## Details
RPCS3 still attempts to install RAPs via drag-n-drop with the old file structure, rendering games unplayable unless the user creates the structure.

**Comment by AniLeo** [comment]
RAPs don't have "file structure", they're a 16-byte key. This issue doesn't make much sense.
