### ISSUE TITLE
Dante's Inferno heavily stuttering audio during battle

### ISSUE THREAD

**Issue by calvinvalerian** [RPCS3/rpcs3#10953]
## Quick summary
Audio heavily stuttering during battle

VIDEO
https://youtu.be/9H4Ywx6xxDM

PC Specs are in the video

**Comment by YuriNator557** [comment]
## Please do not ask for help or report compatibility regressions here, use [RPCS3 Discord server](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/) instead.

from the template you completely ignored
