### ISSUE TITLE
God of War 3 BCES00510 doesn't boot after #10849 (Regression)

### ISSUE THREAD

**Issue by bilalfakhouri** [RPCS3/rpcs3#10950]
Hi

God of War 3 BCES00510 doesn't boot after #10849 pull request, affected build version: RPCS3_0.0.18-12783
It stuck at "Building SPU cache..." then the game window closes, emulator doesn't crash
LOG:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7263438/RPCS3.log.gz)

Latest working build: RPCS3_0.0.18-12776, commit: #10885
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7263444/RPCS3.log.gz)

I used default RPCS3 settings in both versions, I did a clean install for both versions

Specs:
Ryzen 3900x
RTX 2080 SUPER
64GB RAM DDR4 3000 MHz

Thanks RPCS3 team!

**Comment by YuriNator557** [comment]
Works fine for me?
![image](https://user-images.githubusercontent.com/76178650/135721466-fa0936d9-40f9-4218-a884-7c072d4b71b1.png
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7271655/RPCS3.log.gz)
)

**Comment by YuriNator557** [comment]
Works fine for me?
![image](https://user-images.githubusercontent.com/76178650/135721486-a3141ef1-d9d9-4ed9-b99f-e25e42a33a87.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7271657/RPCS3.log.gz)

**Comment by bilalfakhouri** [comment]
I tested BCES00510 version, it doesn't work here . . I don't have BCES00799 version to test (which you use) 

If you have BCES00510 version, well, try to make a test with that, it might be there something, or in general if anyone have BCES00510 version please make a test

**Comment by YuriNator557** [comment]
I strongly doubt there is a difference

**Comment by mimimi085181** [comment]
BCES00510 seems to work for me. I'm running v0.0.18-12862-63f16d7a, updated the game to version 1.03, and the only setting i changed is vsync, i think. I do get ingame, to actual gameplay.

Specs:
Ryzen 5900X
GTX 1070
32GB RAM DDR4 3600

**Comment by bilalfakhouri** [comment]
Thanks mimimi085181

I figured it out, I tested BCES00510 1.00 (without installing 1.03 update), after installing 1.03 update the problem gone, now God of War 3 BCES00510 boots properly

@mimimi085181 Can you try it without 1.03 update just to confirm that?

Not sure if this issue count as regression, I think it is, because on real PS3 BCES00510 1.00 boots normally

**Comment by mimimi085181** [comment]
I removed the update by moving the BCES00510 folder in dev_hdd0\game to somewhere else, and it still boots up just fine.

**Comment by bilalfakhouri** [comment]
Weird . . I did the same "moving the BCES00510 folder in dev_hdd0\game to somewhere else" and the game didn't boot.

**Comment by bilalfakhouri** [comment]
Probably I found out what the real problem, I was booting the game from mounted ISO disc image, extracting ISO image to a folder and booting the BCES00510 1.00 from that folder works

The problem must be related to a mounted disc image, either from my workflow to create a disc image, or from how RPCS3 handles mounted disc image

**Comment by Megamouse** [comment]
Isos are not supported

**Comment by bilalfakhouri** [comment]
Mounted ISOs, not ISOs
