### ISSUE TITLE
Playstation All Stars: freeze in main menu

### ISSUE THREAD

**Issue by A-w-x** [RPCS3/rpcs3#10969]
## Quick summary
game freezes on main menu

this the output after the freeze, related?
![Screenshot_2021-10-08_15-46-28](https://user-images.githubusercontent.com/80461138/136587255-d2848b54-b7d2-471c-a73a-15ad120dd3ed.png)

#### 5. Please provide your system configuration:
* OS: Archlinux
* CPU: i5-1035g7
* GPU: iris plus 940
* Driver version: mesa git

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7312734/RPCS3.log.gz)

rpcs3 built from master

**Comment by MSuih** [comment]
You can probably work around this by disabling native 16-bit float support from Config > Advanced > GPU. But keep the ticket open for now.

**Comment by kd-11** [comment]
You can get rid of validation issues using strict rendering option

**Comment by kd-11** [comment]
Actually those errors are caused because of resizing the vulkan window while rendering. Harmless. Unless your spamming window resize constantly for some reason this is not an issue.
I'm not convinced the reported freezing is caused by vulkan/RSX unless proven otherwise. Untagging.

**Comment by A-w-x** [comment]
you mean rpcs3 render window?
i did not resize the window at all

**Comment by kd-11** [comment]
```
·E 0:01:15.278170 {RSX [0x0253acc]} RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 1014, 669, Requested = 1017, 671
·W 0:01:15.278180 {RSX [0x0253acc]} RSX: Swapchain initialization failed. Request ignored [1017x671]
·E 0:01:15.292651 {RSX [0x0265ac4]} RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 1009, 668, Requested = 1010, 668
·W 0:01:15.292669 {RSX [0x0265ac4]} RSX: Swapchain initialization failed. Request ignored [1010x668]
·! 0:01:15.306267 {RSX [0x0277abc]} RSX: Swapchain: present mode 0 in use.
·E 0:01:15.342351 {RSX [0x029bacc]} RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 993, 658, Requested = 996, 662
·W 0:01:15.342364 {RSX [0x029bacc]} RSX: Swapchain initialization failed. Request ignored [996x662]
·E 0:01:15.359803 {RSX [0x02adac4]} RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 984, 650, Requested = 988, 655
·W 0:01:15.359818 {RSX [0x02adac4]} RSX: Swapchain initialization failed. Request ignored [988x655]
·! 0:01:15.376331 {RSX [0x02bfabc]} RSX: Swapchain: present mode 0 in use.
·E 0:01:15.410863 {RSX [0x02e3acc]} RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 961, 630, Requested = 962, 632
·W 0:01:15.410877 {RSX [0x02e3acc]} RSX: Swapchain initialization failed. Request ignored [962x632]
·! 0:01:15.426792 {RSX [0x02f5ac4]} RSX: Swapchain: present mode 0 in use.
·! 0:01:15.474942 {RSX [0x032bacc]} RSX: Swapchain: present mode 0 in use.
·E 0:01:15.475999 {RSX [0x032bacc]} RSX: ERROR: [Validation] Code 0 : Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x7f88685e4ae0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (960,630), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (959,630), minImageExtent = (959,630), maxImageExtent = (959,630). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
```
This is from your second log (after disabling fp16). Note, the Max dimensions are from the old window size, the requested dimensions are from the current window size. This only happens during window resize including maximize/minimize and border drag.

Either way, this is just a distraction from the real problem which has nothing to do with these messages.

**Comment by A-w-x** [comment]
no freeze in main menu on latest build, but it freezes in-game randomly, i ll get log and attach here
