### ISSUE TITLE
Watch_Dogs (NPEB01433) Garbage data being fed to RSX

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#10978]
## Quick summary
The game constantly feeds garbage data into RSX, making it compile a ridiculous amount of shaders that aren't actually shaders.

## Details

Watch Dogs looks correctly-rendered (apart from its few graphical issues) at around 5000 shaders.  However, the game constantly compiles them even in scenarios where it's already fully compiled all the ones in that area.  During my playthrough I compiled over 300,000 shaders, it was only then that I knew something was wrong.  Everything looked correctly-rendered around 20 minutes into the playthrough, everything after that was garbage data.  I know it's garbage data because you can compile shaders infinitely by running around a small area while rotating the camera.  I once did this for 30 minutes straight and compiled 50,000 shaders.  I should mention that the visuals during the "compilation" don't match what the visuals look like when it's compiling the real shaders.  When it compiles the real shaders, there's pop-in, effects actually starting to appear for the first time, and a brief colored effect appearing for a split second and never appearing again for that effect.  The visuals for the garbage data being compiled is weird - black rectangles with colored outlines, multi-colored splotches, the entire screen going black except for a green square in the upper-left-hand corner, things like that which don't actually make anything else render or match up to any ingame effect.  It's the same visuals appearing constantly, just in different places on the screen.  It becomes blatantly obvious that these aren't shaders when you see it for yourself ingame.  Screenshots of the visuals are below:

#### 1. Please attach RPCS3's log.
I made this log with the Vulkan SDK installed, Strict Rendering Mode enabled, and Debug Output enabled:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7317856/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.

![1](https://user-images.githubusercontent.com/58268914/136705779-12d51fd4-12f1-41c4-a699-3802284b7790.png)

![2](https://user-images.githubusercontent.com/58268914/136705784-147d0e6d-2a11-4120-9fc6-b0016cb68453.png)

![3](https://user-images.githubusercontent.com/58268914/136705792-ab078ef7-4be6-41fa-9a59-aae3328de7ec.png)

![4](https://user-images.githubusercontent.com/58268914/136705797-021dcd5c-2f8e-46b0-a1fd-fe1377dcdf9b.png)

![5](https://user-images.githubusercontent.com/58268914/136705800-44528670-220c-45cf-a7fc-3e6ed7eb5619.png)

#### 4. Please provide comparison with real PS3.

Real consoles don't use shaders, so this section doesn't apply to this issue.

#### 5. Please provide your system configuration:
* OS: Windows 10 x64 Build 19043
* CPU: Intel Core i9-10900K
* GPU: NVIDIA RTX 2080 Super
* Driver version: 466.27

**Comment by Xcedf** [comment]
@SlyCooperReloadCoded this issue looks  the same to one I saw in GTAV, I don't have Watch Dogs can you please try those areas where you have issue with WCB enabled on this build
https://mega.nz/file/bdhmVLDK#i4HSM-MyqZrR62j0HNyUQnTSfRAbwiqrHSRBfj0Vk0E

**Comment by SlyCooperReloadCoded** [comment]
This is still an issue as of 0.0.19-13052-5e158bd3.  A while ago, the log started to print this error whenever it compiles the garbage data:

E RSX: [Unimplemented warning] Conflicting texture decode options in the shaders detected. Base option=14, selected=18

This could be unrelated but it's worth mentioning.

**Comment by nitroos-ai** [comment]
Retest with latest master. #11381

**Comment by SlyCooperReloadCoded** [comment]
It no longer displays those errors, and upon further testing these seem to be actual shaders.  My shader cache is over 40000 big and I don't get this anymore.  I'll close this.
