### ISSUE TITLE
Kingdom Hearts 1.5 ReMix (BLUS31212) No Sound

### ISSUE THREAD

**Issue by AubbyLobby** [RPCS3/rpcs3#10970]
## Quick summary
Booting up Kingdom Hearts 1.5 Final Mix gives no sound when starting up game, and crashes the emulator upon exit of the game.

## Details
Upon launching KH 1.5 Remix, sometimes the sound plays when launching and selecting which game you would like to play. When selecting Kingdom Hearts 1, no sound plays at all. Not even changing any audio settings in the emulator fixes the problem. I ran the game with the 60 fps patch in the beginning and sound played perfectly, albeit the dialouge is fast on some parts. When I switched over to 30 fps, that's when the sound issue occured and it won't allow me to fix it in anyway. Using deafult settings doesn't fix the issue. When closing the game, the emulator crashes.

## Log
![RPCS3.log](https://github.com/RPCS3/rpcs3/files/7314163/RPCS3.log)

## Screenshot
![Screenshot 2021-10-08 170444](https://user-images.githubusercontent.com/85417781/136624654-603eca67-cc47-4acc-a2ac-f72c7571ee7f.png)

## System Configeration
* Windows
* Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
* NVIDIA GeForce RTX 2060
* Version: 471.96
* RPCS3 Version: 0.0.18-12869-8e311273 Alpha

**Comment by Megamouse** [comment]
![image](https://user-images.githubusercontent.com/23019877/139562133-7cdd2fc3-63fb-4ac9-be65-90e0611d5e3e.png)
