### ISSUE TITLE
SOCOM 4 hangs when loading

### ISSUE THREAD

**Issue by OnlyDevelops** [RPCS3/rpcs3#10976]
## Quick summary
When loading SOCOM 4, instead of loading into the game, it throws an error about sephamore_acquire has timed out: 
`E RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x50300750`

## Details

The sephamore_acquire has timed out error/crash always occurs, even when increasing driver recovery/timeout settings:
```
Driver Recovery Timeout: 30000000
Driver Wake-Up Delay: 99000
```
Please provide your system configuration:
```
- SYS: RPCS3 v0.0.18-12869-8e311273 Alpha | HEAD
- SYS: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz | 12 Threads | 31.28 GiB RAM | TSC: 3.306GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 5.4.0-88-generic, Version: #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1070' running on driver 470.74.0.0
- RSX: Found vulkan-compatible GPU: 'llvmpipe (LLVM 12.0.0, 256 bits)' running on driver 0.0.1
- SYS: Firmware version: 4.86
```

I have tried with all SPU and PPU decoder settings, and even tried with SPU loop detection off, and 1 SPU thread: 
![](https://i.imgur.com/T35lwBt.png)

**Comment by illusion0001** [comment]
Post logs

**Comment by Megamouse** [comment]
closing as no log was provided after multiple requests.
