### ISSUE TITLE
Dungeon Siege 3 [BLES01161]: Game freezes often when compiling new SPU blocks

### ISSUE THREAD

**Issue by tech2c** [RPCS3/rpcs3#10971]
## Quick summary
Upon loading a save game when SPU cache had been cleared, the game will freeze whilst the log shows it is still counting up with "S SPU: New block compiled successfully x123..." for a few seconds after the game freezes. 

No purple or red text shown in log when the freeze occurs.

Building the SPU cache prior helps, but the game will freeze when entering new areas anyway.

#### 5. Please provide your system configuration:
* OS: Windows 10
* CPU: Ryzen 3700x
* GPU: Nvidia RTX3060ti
* Driver version: 471.11

Latest rpcs3 build.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7315128/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Multithreaded RSX is enabled along with Write Color Buffers which may cause crashes

**Comment by tech2c** [comment]
Ok tested again, same freeze unfortunately.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7448044/RPCS3.log.gz)

**Comment by tech2c** [comment]
I am attaching my save file which will consistently demonstrate the freeze.

Instructions to replicate this issue:
1. Load into the save slot 00 save file attached.
2. Walk the character forward
3. Button mash past the dialogue screens
4. Walk to the edge of the bridge and wait (see screen capture). It will freeze within 5-10 seconds.

After you run this game once it would have created a SPU and shader cache. This seems to help it get a bit further on next try but will freeze again a little later. Remove SPU and shader cache to quickly make it freeze again as listed above.
[BLES01161-SAVR-00-SAVE_SLOT.zip](https://github.com/RPCS3/rpcs3/files/8129582/BLES01161-SAVR-00-SAVE_SLOT.zip)

![image](https://user-images.githubusercontent.com/92201819/155456671-4cb2925c-54c4-4163-94c8-fe8fca7accaf.png)

**Comment by tech2c** [comment]
Tested with latest master and can no longer replicate the freeze. Issue is fixed - well done devs!
