### ISSUE TITLE
RSX Compilation failed - I can't run anything

### ISSUE THREAD

**Issue by spiraluc** [RPCS3/rpcs3#10973]
This error has been shown to me for a long time, but after pull request - Do not allow to unpause after fatal error occured in emulation #10833, I can't click play and ignore this error. Before that pull request I could press play and the game worked without a problem. I get this error after starting the game when shaders are compiled.

If i try play for example project diva F, I get this error:

F RSX: Compilation failed: Compute shader failed to compile with the following errors:
ERROR: 0:3: error(# 385) Binding point for: buffer block must be equal or greater than 0 and less than: GL_MAX_SHADER_STORAGE_BUFFER_OBJECT_BINDINGS
ERROR: 0:29: error(# 143) Undeclared identifier: data
ERROR: 0:29: error(# 145) Left of "[" is not of type array, matrix, or vector: data
ERROR: 0:29: error(# 160) Cannot convert from: "float" to: "highp unsigned int"
ERROR: 0:30: error(# 145) Left of "[" is not of type array, matrix, or vector: data
ERROR: error(# 273) 5 compilation errors. No code generated

source: #version 430
layout(local_size_x=64, local_size_y=1, local_size_z=1) in;
layout(binding=9, std430) buffer ssbo{ uint data[]; };

#define KERNEL_SIZE 1

// Generic swap routines
#define bswap_u16(bits) (bits & 0xFF) << 8 | (bits & 0xFF00) >> 8 | (bits & 0xFF0000) << 8 | (bits & 0xFF000000) >> 8
#define bswap_u32(bits) (bits & 0xFF) << 24 | (bits & 0xFF00) << 8 | (bits & 0xFF0000) >> 8 | (bits & 0xFF000000) >> 24
#define bswap_u16_u32(bits) (bits & 0xFFFF) << 16 | (bits & 0xFFFF0000) >> 16

// Depth format conversions
#define d24f_to_f32(bits) (bits << 7)
#define f32_to_d24f(bits) (bits >> 7)

uint linear_invocation_id()
{
uint size_in_x = (gl_NumWorkGroups.x * gl_WorkGroupSize.x);
return (gl_GlobalInvocationID.y * size_in_x) + gl_GlobalInvocationID.x;
}

void main()
{
uint invocation_id = linear_invocation_id();
uint index = invocation_id * KERNEL_SIZE;
uint value;

{
value = data[index];
data[index] = bswap_u16(value);
}
}

F RSX: Linkage failed: Compute shader(s) were not successfully compiled before glLinkProgram() was called. Link failed. 

CPU: Intel Core 2 Duo E7500
GPU: AMD HD 7570 2GB (openGL only) (driver 16.2.1)
RAM: 8GB 
WIN 10 (21H1)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7315462/RPCS3.log)

**Comment by elad335** [comment]
> Ignore this error

LMAO

**Comment by spiraluc** [comment]
Can I ask why is that issue invalid? Because before that project diva F ran stable 30FPS. According to the quickstart guide i pass the minimum HW requirements.

**Comment by YuriNator557** [comment]
You did not follow the template that appeared when selecting to make a bug report

**Comment by YuriNator557** [comment]
> your cpu is well below minimum requirements, and on top of that rpcs3 doesn't see a gpu. are you trying to run this with an iGPU or do you actually have one?


It is technically above minimum requirements (it is an x86 CPU and the GPU supports OGL 4.4) but it is very underpowered

**Comment by kd-11** [comment]
It's easy enough to work around, we can keep it open, I'll push a fix with a batch of incoming shader fixes.
It's not very convenient to have aliasing binding points but OGL is included for legacy support afterall.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/10975 should fix this, you can test the artifact from the CI build.
