### ISSUE TITLE
sceNpDrmIsAvailable returns success code if RAP is missing

### ISSUE THREAD

**Issue by NicknineTheEagle** [RPCS3/rpcs3#10984]
sceNpDrmIsAvailable function returns CELL_OK even if RAP file is missing which does not match the behavior of the real PS3 (if you deactivate your licenses). This often causes the game to read encrypted garbage from EDAT and usually crash. The function is supposed to return a fail code in case of missing RAP but it's not known which one exactly. Will need to also check NPD header since free license does not need RAP.

Here's a log from an example crash in SONIC THE HEDGEHOG [BLES00028], I have installed a DLC without RAP: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7322512/RPCS3.log.gz)

**Comment by elad335** [comment]
Test with #11013.
