### ISSUE TITLE
[NPUB31489] El Chavo Kart crashes when loading the initial menu

### ISSUE THREAD

**Issue by ranplayer** [RPCS3/rpcs3#10988]
## Quick summary
El Chavo Kart should start normally (but it is crashing when loading the initial menu screen)

## Details
 It is crashing when loading the initial menu screen.

#### 1. Please attach RPCS3's log.
- [RPCS3.tar.gz](https://github.com/RPCS3/rpcs3/files/7325266/RPCS3.tar.gz)
- [RPCS3-console.log](https://github.com/RPCS3/rpcs3/files/7325267/RPCS3-console.log)

#### 5. Please provide your system configuration:
* OS: Manjaro Linux
* CPU: Core i7-4510U
* GPU: GT 740M (2GB)
* Driver version: 470.74
* Kernel: 5.10.70

#### Please include.
- Line of interest in the console log: `U PPU TODO: Unimplemented syscall syscall_988 -> CELL_OK (r3=0x1, r4=0x0, r5=0x1, r6=0x0, r7=0xd003fcc4, r8=0x20a14f0, r9=0x0, r10=0x1000000)`

**Comment by YuriNator557** [comment]
That normally indicates corruption of some kind, normally save data or game files, have you tried deleting these and reinstalling?

**Comment by ranplayer** [comment]
No. I'm going to try it.
