### ISSUE TITLE
Broken spotlight shadows in TLoU

### ISSUE THREAD

**Issue by Linear524** [RPCS3/rpcs3#10983]
The last remaining broken shadows in The Last of Us is the spotlight shadows.
KD-11 noted that it is another broken virtual cubemap type, so here is the screenshots:
![A1](https://user-images.githubusercontent.com/84367301/136771861-8e5a9b95-4126-4df1-8133-4c8f0d71a8fa.jpg)
![A2](https://user-images.githubusercontent.com/84367301/136771892-c312dfbc-dba2-4c86-ad45-fc0b2a93adfa.jpg)

**Comment by Yahfz** [comment]
Missing Renderdoc or RSX Capture + log.

**Comment by kd-11** [comment]
This is why the PS3 comparisons are important, I have to game bugs with youtube videos because of this. Sometimes even the silliest things can have escaped developers attention.
