### ISSUE TITLE
Regression on few GCM samples

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1098]
@vlj , probably can help to take a look

1.fw_fog.ppu.elf
2.fw_stencil_reflect.ppu.elf
3.user_clip.ppu.elf
4.number of PGSL samples

0(77) : error C7623: implicit narrowing of type from "vec4" to "float"
0(78) : error C7623: implicit narrowing of type from "vec4" to "float"
0(79) : error C7623: implicit narrowing of type from "vec4" to "float"

**Comment by vlj** [comment]
Submitted a fix

**Comment by raven02** [comment]
Thanks a lot @vlj
