### ISSUE TITLE
Auxiliary file not loaded properly

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1099]
When I try to load the file fw_fog.elf it fails with the following message:

W fs::file::open('C:/Users/Vincent/Desktop/SWEMU/tests/gcm/dev_bdvd.path', 0x1) failed: error 0x2
W fs::file::open('C:/Users/Vincent/Desktop/SWEMU/tests/gcm/PARAM.SFO', 0x1) failed: error 0x2
E 'BreakPoints.dat' is broken (version=0xcccc, break_count=0xcccccccc, marked_count=0xcccccccc, length=0x6)
S (S)ELF: boot done.
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x50dd0, attr=*0x3acc8)
W {PPU[0x1] Thread (main_thread)[0x0002a0a4]} sys_memory: sys_memory_get_user_memory_size(mem_info_addr=0xd000fc04)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x50bd8, attr=*0x3acc8)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x50368, attr=*0x3acc8)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x50390, attr=*0x3acc8)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x503b8, attr=*0x3acc8)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x502a0, attr=*0x3acc8)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x502c8, attr=*0x3acc8)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x502f0, attr=*0x3acc8)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x50318, attr=*0x3acc8)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x50340, attr=*0x3acc8)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x50f20, attr=*0x464b8)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x50ea0, attr=*0x464b8)
W {PPU[0x1] Thread (main_thread)[0x00037528]} sysPrxForUser: sys_lwmutex_create(lwmutex=*0x50ee0, attr=*0x464c8)
W {PPU[0x1] Thread (main_thread)[0x000373e8]} cellSysmodule: cellSysmoduleLoadModule(id=0x000e: CELL_SYSMODULE_FS)
W {PPU[0x1] Thread (main_thread)[0x00026444]} sys_fs: sys_fs_open(path=*0xd000fa00, flags=0, fd=*0xd000f7b0, mode=0, arg=*0x0, size=0x0)
W {PPU[0x1] Thread (main_thread)[0x00026444]} sys_fs: *** path = '/app_home/fwArgs.txt'
W {PPU[0x1] Thread (main_thread)[0x00026444]} fs::file::open('C:/Users/Vincent/Desktop/SWEMU/tests/gcm/fw_fog/fwArgs.txt', 0x1) failed: error 0x2
E {PPU[0x1] Thread (main_thread)[0x00026444]} sys_fs error: sys_fs_open('/app_home/fwArgs.txt'): failed to open file (flags=0, mode=0)
W {PPU[0x1] Thread (main_thread)[0x00036ec8]} cellGcmSys: _cellGcmInitBody(context_addr=0x50144, cmdSize=0x80000, ioSize=0x100000, ioAddress=0x20100000)
W {PPU[0x1] Thread (main_thread)[0x00036ec8]} cellGcmSys: *** local memory(addr=0xc0000000, size=0xf900000)
W {PPU[0x1] Thread (main_thread)[0x00036ec8]} cellGcmSys: cellGcmInit(): 256MB io address space used
W {PPU[0x1] Thread (main_thread)[0x00037328]} cellSysutil: cellVideoOutConfigure(videoOut=0, config_addr=0xd000fbd4, option_addr=0x0, waitForEvent=0x0)
W {PPU[0x1] Thread (main_thread)[0x00036f68]} cellGcmSys: cellGcmSetFlipMode(mode=2)
W {PPU[0x1] Thread (main_thread)[0x000370c8]} cellGcmSys: cellGcmSetTileInfo(index=0, location=0, offset=0, size=3801088, pitch=5120, comp=0, base=0, bank=0)
W {PPU[0x1] Thread (main_thread)[0x00036f48]} cellGcmSys: cellGcmBindTile(index=0)
W {PPU[0x1] Thread (main_thread)[0x000370c8]} cellGcmSys: cellGcmSetTileInfo(index=1, location=0, offset=3801088, size=3801088, pitch=5120, comp=0, base=0, bank=0)
W {PPU[0x1] Thread (main_thread)[0x00036f48]} cellGcmSys: cellGcmBindTile(index=1)
W {PPU[0x1] Thread (main_thread)[0x000370c8]} cellGcmSys: cellGcmSetTileInfo(index=2, location=0, offset=7602176, size=3801088, pitch=5120, comp=9, base=0, bank=0)
E {PPU[0x1] Thread (main_thread)[0x000370c8]} cellGcmSys error: cellGcmSetTileInfo: bad compression mode! (9)
W {PPU[0x1] Thread (main_thread)[0x00036f48]} cellGcmSys: cellGcmBindTile(index=2)
W {PPU[0x1] Thread (main_thread)[0x00037008]} cellGcmSys: cellGcmBindZcull(index=0)
W {PPU[0x1] Thread (main_thread)[0x00018058]} sys_event: sys_event_queue_create(equeue_id=*0x2000017c, attr=*0xd000fb10, event_queue_key=0x0, size=32)
W {PPU[0x1] Thread (main_thread)[0x0001807c]} sys_event: sys_event_port_create(eport_id=*0x474fc, port_type=1, name=0x0)
W {PPU[0x1] Thread (main_thread)[0x00018098]} sys_event: sys_event_port_connect_local(eport_id=0x11, equeue_id=0x10)
W {PPU[0x1] Thread (main_thread)[0x00037048]} cellGcmSys: cellGcmSetFlipHandler(handler_addr=264152)
W {PPU[0x1] Thread (main_thread)[0x00037148]} sys_io: cellPadInit(max_connect=4)
W {PPU[0x1] Thread (main_thread)[0x000371c8]} sys_io: cellKbInit(max_connect=4)
W {PPU[0x1] Thread (main_thread)[0x000372c8]} sys_io: cellMouseInit(max_connect=4)
W {PPU[0x1] Thread (main_thread)[0x00037028]} cellGcmSys: cellGcmMapMainMemory(ea=0x20600000,size=0x8000000,offset_addr=0x46c38)
W {PPU[0x1] Thread (main_thread)[0x00037408]} cellSysmodule: cellSysmoduleIsLoaded(id=0x000e: CELL_SYSMODULE_FS)
W {PPU[0x1] Thread (main_thread)[0x00037488]} cellFs: cellFsStat(path=*0x20000030, sb=*0xd000f8f8) -> sys_fs_stat()
W {PPU[0x1] Thread (main_thread)[0x00037488]} sys_fs: sys_fs_stat(path=*0x20000030, sb=*0xd000f8f8)
W {PPU[0x1] Thread (main_thread)[0x00037488]} sys_fs: *** path = '/host_root/sample_data/graphics/gcm/fw_fog/WorldMapHi.gtf'
E {PPU[0x1] Thread (main_thread)[0x00037488]} sys_fs error: sys_fs_stat('/host_root/sample_data/graphics/gcm/fw_fog/WorldMapHi.gtf') failed: not found
E {PPU[0x1] Thread (main_thread)[0x00020c44]} Unimplemented syscall 988: syscall_988 -> CELL_OK
W {PPU[0x1] Thread (main_thread)[0x000373c8]} cellSysmodule: cellSysmoduleUnloadModule(id=0x000e: CELL_SYSMODULE_FS)
E {PPU[0x1] Thread (main_thread)[0x00022dac]} Unimplemented syscall 988: syscall_988 -> CELL_OK
W {PPU[0x1] Thread (main_thread)[0x00037628]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x5)
W {PPU[0x1] Thread (main_thread)[0x00037628]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x6)
W {PPU[0x1] Thread (main_thread)[0x00037628]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x7)
W {PPU[0x1] Thread (main_thread)[0x00037628]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x8)
W {PPU[0x1] Thread (main_thread)[0x00037628]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x9)
W {PPU[0x1] Thread (main_thread)[0x00037628]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0xa)
W {PPU[0x1] Thread (main_thread)[0x00037628]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0xb)
W {PPU[0x1] Thread (main_thread)[0x00037628]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0xc)
W {PPU[0x1] Thread (main_thread)[0x00037628]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x4)
W {PPU[0x1] Thread (main_thread)[0x00037628]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x3)
W {PPU[0x1] Thread (main_thread)[0x00037648]} sys_process: sys_process_exit(status=0x1)
S {PPU[0x1] Thread (main_thread)[0x00037648]} sys_process: Process finished
W {RSXThread} RSX thread aborted

**Comment by Syphurith** [comment]
@vlj is the file there? Also please use gist/paste to show the full log next time.

**Comment by vlj** [comment]
The file is in C:\Users\Vincent\Desktop\SWEMU\root\host_root\sample_data\graphics\gcm\fw_fog but I don't know where to put it so that it's recognised by rpcs3

**Comment by Bigpet** [comment]
I'm guessing this is a special case for SDK samples and the "\host_root\" directory maybe setting the mountpoint "host_root" to "C:\Users\Vincent\Desktop\SWEMU\root\host_root" (in the vfsmanager) in your case might help.

I don't think there's anything we can do to "guess" a sensible default for this

**Comment by raven02** [comment]
i did try to do similar thing to mount /host_root./ and test the human.elf , it is not working now (it worked before)

**Comment by raven02** [comment]
@vlj may i have your private email ? i want to share something with you useful . thanks

**Comment by vlj** [comment]
@raven02 yes it's vljn.ovi at gmail dot com

**Comment by vlj** [comment]
@Bigpet if I set host_root to the full path in vfs manager, it can't load the .elf file anymore :
E Opening 'C:\Users\vljn_000\Desktop\SWEmu\tests\gcm\fw_fog\fw_fog.ppu.elf' failed

**Comment by Bigpet** [comment]
vlj: Well that's because everything you open needs to be in the sub-folder of at least one mount-point

Previously "host_root" was the "empty" mount point for you (which can open any directory). Either create a new "empty" mount-point or move the *.elf

**Comment by vlj** [comment]
Ok got it working
