### ISSUE TITLE
Resistance 3 Visual Bug

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#11001]
Bug happens when the camera is looking at the light source. Tried different options but it occurs anyway.

![screenshot-2021_08_30_22_13_24](https://user-images.githubusercontent.com/22906342/137187853-2745a227-1dfe-41fc-ba37-0afd3824be5a.png)

![screenshot-2021_08_29_18_51_09](https://user-images.githubusercontent.com/22906342/137187942-53cc78b3-0bcd-4832-a1cb-1573d9fd4069.png)

![screenshot-2021_08_29_20_52_27](https://user-images.githubusercontent.com/22906342/137188116-cc4df107-0ca3-4ed5-8b6f-20627010662a.png)

[RenderDoc capture](https://drive.google.com/file/d/1At7LoMp9tseLLZKN0WJ8pk6CpqIRPQ8Z/view?usp=sharing)
[RSX capture](https://drive.google.com/file/d/1qXRNw6ESWervo3Xor2fMzmPS9Q0_kOAp/view?usp=sharing)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7340341/RPCS3.log.gz)
- AMD Ryzen 5 3600 
- Windows10, 19041
- GPU: 'GeForce GTX 1650' running on driver 456.71.0.0
- SYS: Firmware version: 4.87

**Comment by Realmantik** [comment]
> 
> 
> Looks the same as #7076

It is the same. I think. But no one mentioned this game.

**Comment by Xcedf** [comment]
@Realmantik there's no point to mention this game, all new engine Insomniac games on PS3 have this issue, and if any of them will be fixed other will be as well, for now it's a duplicate issue

**Comment by MSuih** [comment]
I agree, this can be placed as a comment to the mentioned issue
