### ISSUE TITLE
Issue with unlocking Soldier's Trophy on Demon's Souls [BLUS30443]

### ISSUE THREAD

**Issue by blazingwinter** [RPCS3/rpcs3#11003]
## Quick summary
Despite having all weapons to unlock the Soldier's Trophy (http://demonssouls.wikidot.com/trophy-weapons) the trophy will not pop. Running BLUS30443 version of Demon's Souls.

## Details
I've been struggling for a few days to figure out how I can get it to pop. I have tried having all of them in my inventory at once, equipping all of them, and dropping each one and picking it back up. I have checked countless times at the wikidot to make sure I have everything listed there, and I definitely do. Today, I have removed the TROPUSR.DAT file from the trophies file, and tried to see if resetting the trophies would help. It did not, however for the first time, I have noticed in the log (**on the application home screen, not the log file**) that it says:

 `E SYS: 'sceNpTrophyUnlockTrophy' failed with 0x80022915 : SCE_NP_TROPHY_ERROR_ALREADY_UNLOCKED [1]`

This occurred after the trophy reset, and after I had put all the weapons into my inventory, which would imply to me that I should have had the trophy unlocked at that moment, but the game has registered that I have already gotten the trophy, but I haven't as I reset the trophies already, and didn't even have it before the reset.

#### 1. Please attach RPCS3's log.
https://www.mediafire.com/file/d8bsucedfgdsr0e/DeS_Soldiers_trophy.log/file

#### 3. Please attach screenshots of your problem.
All weapons in inventory
![image](https://user-images.githubusercontent.com/92473553/137201821-815cc6ac-4bc0-4b16-95f0-626579bc64b9.png)
![image](https://user-images.githubusercontent.com/92473553/137201898-d1678630-b60b-4057-b1d0-cf0cf40c2cc8.png)
![image](https://user-images.githubusercontent.com/92473553/137201932-3a4e3e56-8d80-4f3d-be64-1dd6bcf64028.png)
![image](https://user-images.githubusercontent.com/92473553/137202188-a20c07c9-456d-4438-8b3b-1901350fddf2.png)
![image](https://user-images.githubusercontent.com/92473553/137201979-66cdbc24-79af-4873-acd3-f788a1114df4.png)
![image](https://user-images.githubusercontent.com/92473553/137202003-93cf405e-3ee8-4fe5-a694-21402fce93e3.png)
![image](https://user-images.githubusercontent.com/92473553/137202029-49a718e6-f247-4b74-82da-1131fa08cd57.png)
![image](https://user-images.githubusercontent.com/92473553/137202047-325ce0d4-0c10-461f-9a3a-b5e07a925101.png)
![image](https://user-images.githubusercontent.com/92473553/137202079-a9ddae0a-259f-4001-9919-93bfb160c758.png)

Trophies screen showing I haven't unlocked it:
![image](https://user-images.githubusercontent.com/92473553/137202456-ee752adb-bc9f-43a7-b156-be7b289360cd.png)

This is from before I reset the trophies. It still isn't unlocked after resetting either.

#### 4. Please provide comparison with real PS3.
n/a

#### 5. Please provide your system configuration:
* OS: Windows 10
* CPU: Intel i7-9700k @3.60GHz
* GPU: Nvidia GTX 1070

#### Please include.
Don't know if it will help, but here's my previous TROPUSR.DAT file before I reset the trophies: https://www.mediafire.com/file/aq3gqtbb9py70fx/TROPUSR.DAT/file

**Comment by blazingwinter** [comment]
> Looking at the screenshots I can't see the Talisman of Beasts

Whoops, overlooked that one for the screenshots, but here it is:
![image](https://user-images.githubusercontent.com/92473553/137413214-d91e0c20-3a8c-47f5-af26-cee6d77b22ed.png)

Regardless, I have done everything with the Talisman of Beasts that I did with others before this post (i.e. dropping it and picking it back up), and I still do not have the trophy.

**Comment by mshpakov** [comment]
Just got the Solider Trophy.. Can't confirm this issue. BLUS30443
![изображение](https://user-images.githubusercontent.com/33029350/151656862-bc2abcc4-efdf-4dee-b59d-a155a117b7e3.png)

**Comment by Megamouse** [comment]
Let's assume this is fixed
