### ISSUE TITLE
PlayStation Home: Device lost when entering certain scenes, but only sometimes

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#11004]
## Quick summary

Loading into certain scenes will occasionally produce a Device Lost error.

## Details
When loading into certain scenes, it will occasionally give a "unrecoverable error - device lost" error with purple text.  It seems to only be a few that do this like The PlayGround, which is what I used to create the log.  This also crashes RPCS3 so it doesn't produce a compressed version of the log.  This crash is incredibly inconsistent as you can get the crash three times in a row then not get it for dozens of times, then get it once, and then not get it ever again.  But the log I attatched was during a streak of three of these crashes.  I also tried going at it with no cache each time, but this doesn't seem to be a factor as it made no difference.

#### 1. Please attach RPCS3's log.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7342229/RPCS3.log)

#### 3. Please attach screenshots of your problem.

![Capture](https://user-images.githubusercontent.com/58268914/137236673-97c1a741-5250-4c4c-a749-857a310141f0.PNG)

#### 4. Please provide comparison with real PS3.

A real console enters the scene as normal, never having any problems.

#### 5. Please provide your system configuration:
* OS:  Windows 10 Pro x64 Build 19043
* CPU:  Intel Core i9-10900K
* GPU:  NVIDIA RTX 2080 Super
* Driver version:  496.13

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/11401
Request to reopen if problem persists.
