### ISSUE TITLE
Top spin 4 player face

### ISSUE THREAD

**Issue by hoangcowboy** [RPCS3/rpcs3#11010]
## Quick summary
My rival player face is a mess

## Details

I am playing Top Spin 4 smoothly but my rival player face messed up, resolution is 1280 * 720, scale 200%, I have already checked Force Cpu blit emulation in Debug tab of RPCS3 config menu.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7350011/RPCS3.log.gz)

![Top Spin bug](https://user-images.githubusercontent.com/26183138/137413326-4751fe35-ab4b-4516-af93-be54fc782baf.PNG)

![Top Spin bug](https://user-images.githubusercontent.com/26183138/137413526-d2de0690-149a-40dd-a205-7f48b67bfffe.PNG)

#### 5. Please provide your system configuration:
* OS Windows 10
* CPU 5600x
* GPU Rtx 3070
* Driver version 472.12
* etc.

**Comment by AniLeo** [comment]
Pirated game detected, closed and locked
