### ISSUE TITLE
color buffer write/read doesn't work

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1102]
If I enable color buffer read and color buffer write in graphic options, cube_mrt.ppu.elf test show a black screen in GL mode.

For information in d3d12 there is no cube either, I checked and that's because the RTT texture are zeroed, thus their alpha component is too.
I checked with d3d12 too and depth_read.ppu.elf test with some hacking, the color buffer are properly send to memory so that's an issue with the address pointer provided via m_context_dma_color_a or an issue with cell emulation.

**Comment by raven02** [comment]
Humm it should work .This is running from master build in opengl mode

![mrt](https://cloud.githubusercontent.com/assets/3000282/7873491/a0cd52d2-05d5-11e5-8a06-2e2b65ee03e1.jpg)

**Comment by raven02** [comment]
Yes , i remember if both options enabled , it will black screen in most samples as well as in commercial games. DH told read color buffer is quite experimental .

**Comment by vlj** [comment]
You're right, closing
