### ISSUE TITLE
Regression: Ratchet and Clank: All 4 one Demo NPEA90106 (#6483)

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#11026]
Some surfaces are flickering with colors in All 4 one Demo, maybe in other Insomniac games, looks like this:

https://youtu.be/J7cRma8Hcvs
started with https://github.com/RPCS3/rpcs3/pull/6483
analyzed it's code a bit, reverted the part that responsible
the way it looked before regression and looks after revert
https://youtu.be/7I7lSPbmsU0
the exact changes of revert:
VKDraw.cpp
![image](https://user-images.githubusercontent.com/7060586/137701905-1ecd6cfd-0b0a-4dc9-a9a6-e0f434fe54be.png)
VKGSrender.cpp
![image](https://user-images.githubusercontent.com/7060586/137702023-b8b3b783-9d6b-45b5-87ee-829c009aa982.png)

Logs:
master: [RPCS3_broken.gz](https://github.com/RPCS3/rpcs3/files/7363227/RPCS3_broken.gz)
master + revert:[RPCS3_fixed.gz](https://github.com/RPCS3/rpcs3/files/7363229/RPCS3_fixed.gz)

My system:
i9 9900k
gtx 1070
Drv: 458.06

**Comment by kd-11** [comment]
Known limitation with WCB/WDB and Vulkan specifically. I'll have to find a better workaround.
