### ISSUE TITLE
Screen saver not inhibited in MATE desktop environment

### ISSUE THREAD

**Issue by dariox86** [RPCS3/rpcs3#11033]
MATE desktop environment [does not implement](https://github.com/mate-desktop/mate-screensaver/issues/57) org.freedesktop.ScreenSaver. It does expose org.mate.ScreenSaver instead. Under MATE «Prevent display sleep while running games» is greyed out in RPCS3 because it looks for org.freedesktop.ScreenSaver and it does not find it. I have used MATE for years and this is the first time I have come across this issue with an application not inhibiting the screen saver. Perhaps other applications are doing it in a more generic way. I know it may be MATE's fault, but it should be trivial to add support for it. I may take care of it if you so wish.

**Comment by dariox86** [comment]
Forgive if I am wrong: on top of that I see no permission granted for org.freedesktop.ScreenSaver in the Flatpak manifest.

**Comment by AniLeo** [comment]
Does it happen with the AppImage?

**Comment by dariox86** [comment]
I see the option «Prevent display sleep while running games» greyed out with AppImage. Same goes for Flatpak and rpcs3-git from Arch User Repository.

**Comment by Megamouse** [comment]
```
if defined(HAVE_QTDBUS)
	QDBusInterface interface("org.freedesktop.ScreenSaver", "/ScreenSaver", "org.freedesktop.ScreenSaver", QDBusConnection::sessionBus());
	return interface.isValid();
#else
	return false;
#endif
```

**Comment by Megamouse** [comment]
you're on an outdated commit. I force pushed when I saw that it doesn't build.

**Comment by dariox86** [comment]
OK, thank you.
