### ISSUE TITLE
Play sound when pressing F12 Screenshot key

### ISSUE THREAD

**Issue by danieljromero15** [RPCS3/rpcs3#11035]
Not sure if this is the right place to do it, but here goes.

I was wondering if a sound could be added when you take a screenshot (maybe customizable, not sure how difficult that would be unless it could be replaceable in the files without a dedicated GUI). As of right now, rpcs3 just logs it, but it's difficult to tell if a screenshot was actually captured if you're running a game in fullscreen (with a single monitor).

**Comment by MSuih** [comment]
I think we could show an icon or some other indicator for it on the overlay instead, similar to compiling shaders message.
