### ISSUE TITLE
Unable to open gran turismo 5 it gets stuck in "buliding spu cache"

### ISSUE THREAD

**Issue by matewar** [RPCS3/rpcs3#11042]
I tried change al spu settings deleting spu cache going back to default settings but nothing worked I was able to get past "buliding spu cache" once but the screen just stayed black
[log.zip](https://github.com/RPCS3/rpcs3/files/7385551/log.zip)

**Comment by MSuih** [comment]
From the log it looks like you're booting a disc game that's been installed to dev_hdd0, most likely because it's a pkg conversion. These aren't supported right now, you need a proper disc dump.
