### ISSUE TITLE
Certain vehicles will freeze the game and the emulator upon being selected in Motorstorm: Pacific Rift

### ISSUE THREAD

**Issue by VVVaire** [RPCS3/rpcs3#11043]
Been playing the game using rpcs3 recently, it runs fine and is basically playable for the most part besides frame drops towards the beginning of races and a rare crash every once in a while. However, immediately upon selecting certain vehicle models before a race, the game will freeze up and the log gives this message:

Unknown register name: unk
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKCommonDecompiler.cpp:155[:23], in function get_varying_register_location)

Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7387289/RPCS3.log)

**Comment by kd-11** [comment]
"unk" is usually a sign of corrupted shader memory. Try increasing RSX wakeup delay and see if it helps.

**Comment by Augusto7743** [comment]
Tested with rpcs3-v0.0.19-12975 Motorstorm Pacific Rift both 2 demos versions.
The game is crazy, but not crashing.
In some moments cars are being partialy rendered or with some parts being vertex.
Bike running without biker.
The performance is more slow than few previous versions.

**Comment by Augusto7743** [comment]
@VVVaire
Have tested Motorstorm Pacific Rift with 0.0.19-13055 ? The demo version was fixed.
