### ISSUE TITLE
Latest AppImage's AppRun now a html document instead of ELF file

### ISSUE THREAD

**Issue by krazynez** [RPCS3/rpcs3#11067]
## Quick summary
Latest AppImage does not work ("rpcs3-v0.0.18-12953-78bcb0fd_linux64.AppImage") error: 
`execv error: Exec format error`

## Details
AppRun is now an html document instead of and ELF file in the squashfs_root if extracted from the AppImage.
However the previous build ("rpcs3-v0.0.18-12949-ac300c73_linux64.AppImage") has the AppRun as the ELF and works properly.

**Comment by hcorion** [comment]
Fixed by https://github.com/RPCS3/rpcs3/commit/47da39a2ff562817b2f204e8fbf5223403ddbf1e
