### ISSUE TITLE
The Cursed Crusade freezes at the main menu

### ISSUE THREAD

**Issue by Ahmed-E-86** [RPCS3/rpcs3#11076]
## Quick summary
The Cursed Crusade freezes at the main menu. 

## Details
The Cursed Crusade [NPUB30683] freezes at the main menu whatever I use Vulkan, or OpenGL. I was able to start a new game once every 10 tries, but it freezes afterwards.

#### RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7437966/RPCS3.log)

#### 5. Please provide your system configuration:
* OS:  Kubuntu 21.10
* CPU: Intel Core I5 4200M
* GPU: AMD HD Radeon 8750M
* Driver version: Mesa 21.2.4

**Comment by Megamouse** [comment]
Works perfectly fine.
I think this is caused by your 8 years old 2 core potato laptop cpu

**Comment by elad335** [comment]
Slow CPU shouldn't be a reason for crashes freezing, it's invalid to make it sound like it is. If there is s gane that low system performance may trigger timeout assertation failures, then lowering Clocks Scale is the solution.

**Comment by Ahmed-E-86** [comment]
> Slow CPU shouldn't be a reason for crashes or freezing, it's invalid to make it sound like it is. If there is a game that low system performance may trigger timeout assertation failures forv it, then lowering Clocks Scale is the solution.

Thanks! That solved the issue.

**Comment by Ahmed-E-86** [comment]
> Works perfectly fine. I think this is caused by your 8 years old 2 core potato laptop cpu

I did not know that a CPU with only 2 cores is not enough for this emulator. Thanks for Potato label BTW.

**Comment by RainbowCookie32** [comment]
You can check the minimum and recommended requirements on the Quickstart guide :)
https://rpcs3.net/quickstart
