### ISSUE TITLE
LinearToSwizzleAddress seems wrong in fw_multi_texture.ppu.elf

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1107]
When I run in fw_multi_texture.ppu.elf with opengl, I have a flat orange-pink half window whereas there should be a kindof gradient.

Using GPU Perf Studio 2 I saw that the texture used seems wrong, all 8 of them are identical, and they are reproduced here :

![dc2_fs_texture_0](https://cloud.githubusercontent.com/assets/6413475/7903289/22fcafd4-07d7-11e5-98ad-da737eb0bd49.png)

Since the test use swizzled texture I think the LinearToSwizzleAddress algorithm may be wrong.

**Comment by vlj** [comment]
Actually the texture data passed to RSXThread look wrong too, it's full of the same 255, 255, 127, 100 pixel...

**Comment by raven02** [comment]
Humm , i instead of getting the following when run it using master build .

![multi_tex](https://cloud.githubusercontent.com/assets/3000282/7915395/d39603da-08af-11e5-8b1e-785eef1d9cb5.jpg)

**Comment by vlj** [comment]
With interpreter 2 ? with master I don't have the pink gradient either.

**Comment by raven02** [comment]
@vlj , yes , it runs with interpreter 2 . I tried run with original interpreter , same result .Probably difference between AMD and NV?

**Comment by vlj** [comment]
Err sorry, I used the elf from short waves binary, but using another one make the same output as yours.

**Comment by tambry** [comment]
@vlj You can probably then close the issue.

**Comment by raven02** [comment]
@vlj .Good to hear.

**Comment by vlj** [comment]
@tambry the result is still wrong, it should'nt display 2 shaded rectangles and a black box below, but a single shaded rectangle.

**Comment by vlj** [comment]
The issue is partly fixed with this PR:
https://github.com/RPCS3/rpcs3/pull/1112

Unfortunatly I still get 4 square instead of 1.

**Comment by tambry** [comment]
@vlj I'd guess that #1112 further probably amplified the issue, but it doesn't matter, since DH said that the swizzling algorithm is correct. Could you provide a screenshot of the test running on a real PS3, for reference of what it should look like?

**Comment by vlj** [comment]
If an algorithm that left half the texels with undefined values is "correct"  then I won't spend my time wasting time on fixing gl backend bugs.

**Comment by Syphurith** [comment]
@vlj Well you may contact @B1ackDaemon via iRC for the PS3 running screenshot.. Or if that is impossible for you to prove that or tired of that, you can continue your developing on your own repo, but no merge request sent here.. I don't know about RSX rendering, really. However if that is rendered incorrectly, there should be a proper way to do that.  I am not sure about my suggestions for you, but i think that is not just wasting time. please, Please consider that.
