### ISSUE TITLE
Verification failed:  (in file D:\a\1\s\rpcs3\Loader\PSF.cpp:118)

### ISSUE THREAD

**Issue by gavink10** [RPCS3/rpcs3#11083]
i tried booting rpcs3 to play some NCAA 14 and i got an error that said "Verification failed: 
(in file D:\a\1\s\rpcs3\Loader\PSF.cpp:118)" ive never had any issues with rpcs3 so im quite lost

heres the log

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7447355/RPCS3.log)

**Comment by Megamouse** [comment]
Disappear with your old-ass build!

**Comment by gavink10** [comment]
> Disappear with your old-ass build!

thanks, really helpful.
