### ISSUE TITLE
God of War Collection [BCES00791]: Narrow graphics at 1080p

### ISSUE THREAD

**Issue by rtentser** [RPCS3/rpcs3#11099]
Both games render incorrectly when the default resolution is 1080p.

God of War 1 HD:
![Error1](https://user-images.githubusercontent.com/34958119/139831397-58ae82d1-3e84-4db2-9353-ba290cfd9a43.png)
[RPCS3 (1).log](https://github.com/RPCS3/rpcs3/files/7459882/RPCS3.1.log)

God of War 2 HD:
![Error2](https://user-images.githubusercontent.com/34958119/139831456-0f616832-8833-48c4-9d33-d505571339f6.png)
[RPCS3 (2).log](https://github.com/RPCS3/rpcs3/files/7459883/RPCS3.2.log)

**Comment by YuriNator557** [comment]
The game internally renders at 960x1080, I believe this is normal behavior

**Comment by Satan86** [comment]
I mean, it looks fine at 16:9 on PS3, so one would think it should also look like that on RPCS3. You can use Stretch To Display Area to make it the correct aspect ratio as a workaround for now

**Comment by rtentser** [comment]
> You can use Stretch To Display Area to make it the correct aspect ratio as a workaround for now

It works. Thank you!

**Comment by rtentser** [comment]
Strangely, 720p with FSR looks better. Less aliased, at least.

**Comment by Asinin3** [comment]
Why not just use 1280x720, then set res scale to 150% for 1080p, 200% for 1440p etc?

**Comment by illusion0001** [comment]
PS3 behavior would stretch the game to fill 16:9 window. This should be a bug.

**Comment by Megamouse** [comment]
If you look at the log, you will find that after loading the actual game, it uses cellVideoOutConfigure to set the resolution to CELL_VIDEO_OUT_RESOLUTION_960x1080

**Comment by Megamouse** [comment]
can you post a log with 720p ?

**Comment by YuriNator557** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7463953/RPCS3.log)
This is for BCES00800, hopefully there's not much difference

**Comment by rtentser** [comment]
720p:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7465673/RPCS3.log)
 
> Why not just use 1280x720, then set res scale to 150% for 1080p, 200% for 1440p etc?

The bug is a bug. Also i wanted to check which is performing better: can't get stable 60 fps in this game with scaling on my gpu (gt 1030).
