### ISSUE TITLE
"Muddy" audio with PPU JIT compared to PPU Interpreter

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1109]
game - Sonic CD.
Samples:
[Interpreter](https://clyp.it/i30ao0co)
[JIT](https://clyp.it/kh2gmcew)

But "small" in-game clips sound normal ("Sega", rings sound, menu selection "ding", etc.)

**Comment by Nekotekina** [comment]
I think it's LLVM JIT bug, not audio system bug.

**Comment by danilaml** [comment]
Should be fixed in fd5fbab1153850a1cd2a778ccb61dcdd0e6d547c
