### ISSUE TITLE
Not exactly sure what the issue is

### ISSUE THREAD

**Issue by kamijoutouma** [RPCS3/rpcs3#1110]
here is a log
E Unimplemented function 'cellFsUtime' in 'sys_fs' module (0x7bcc50)
E Unimplemented function 'cellOskDialogGetSize' in 'cellSysutil' module (0x7bd370)
E Unimplemented function 'cellOskDialogUnloadAsync' in 'cellSysutil' module (0x7bd390)
E Unimplemented function 'cellOskDialogDisableDimmer' in 'cellSysutil' module (0x7bd3f0)
E Unimplemented function 'cellOskDialogSetSeparateWindowOption' in 'cellSysutil' module (0x7bd430)
E Unimplemented function 'cellOskDialogAddSupportLanguage' in 'cellSysutil' module (0x7bd4b0)
E Unimplemented function 'cellOskDialogLoadAsync' in 'cellSysutil' module (0x7bd4d0)
E Unimplemented function 'cellOskDialogSetKeyLayoutOption' in 'cellSysutil' module (0x7bd5d0)
E Unimplemented function 'cellOskDialogAbort' in 'cellSysutil' module (0x7bd5f0)
E Unimplemented function 'cellOskDialogSetInitialKeyLayout' in 'cellSysutil' module (0x7bd630)
E Unimplemented function 'cellOskDialogSetLayoutMode' in 'cellSysutil' module (0x7bd690)
E Unimplemented function 'cellMusicSetSelectionContext2' in 'cellMusicUtility' module (0x7bd7b0)
E Unimplemented function 'cellMusicSetVolume2' in 'cellMusicUtility' module (0x7bd7d0)
E Unimplemented function 'cellMusicGetPlaybackStatus2' in 'cellMusicUtility' module (0x7bd7f0)
E Unimplemented function 'cellMusicFinalize2' in 'cellMusicUtility' module (0x7bd810)
E Unimplemented function 'cellMusicGetSelectionContext2' in 'cellMusicUtility' module (0x7bd830)
E Unimplemented function 'cellMusicSetPlaybackCommand2' in 'cellMusicUtility' module (0x7bd850)
E Unimplemented function 'cellMusicSelectContents2' in 'cellMusicUtility' module (0x7bd870)
E Unimplemented function 'cellMusicInitialize2' in 'cellMusicUtility' module (0x7bd890)
E Unimplemented function 'cellMusicGetVolume2' in 'cellMusicUtility' module (0x7bd8b0)
E Unimplemented function 'sceNpMatching2DestroyContext' in 'sceNp2' module (0x7be770)
E Unimplemented function 'sceNpMatching2GetWorldInfoList' in 'sceNp2' module (0x7be790)
E Unimplemented function 'sceNpMatching2SearchRoom' in 'sceNp2' module (0x7be7b0)
E Unimplemented function 'sceNpMatching2SignalingGetConnectionStatus' in 'sceNp2' module (0x7be7d0)
E Unimplemented function 'sceNpMatching2CreateServerContext' in 'sceNp2' module (0x7be7f0)
E Unimplemented function 'sceNpMatching2LeaveRoom' in 'sceNp2' module (0x7be810)
E Unimplemented function 'sceNpMatching2Term2' in 'sceNp2' module (0x7be830)
E Unimplemented function 'sceNpMatching2SignalingGetConnectionInfo' in 'sceNp2' module (0x7be850)
E Unimplemented function 'sceNpMatching2AbortRequest' in 'sceNp2' module (0x7be870)
E Unimplemented function 'sceNpMatching2GetServerInfo' in 'sceNp2' module (0x7be890)
E Unimplemented function 'sceNpMatching2GetEventData' in 'sceNp2' module (0x7be8b0)
E Unimplemented function 'sceNpMatching2JoinRoom' in 'sceNp2' module (0x7be8f0)
E Unimplemented function 'sceNpMatching2ContextStartAsync' in 'sceNp2' module (0x7be910)
E Unimplemented function 'sceNpMatching2RegisterContextCallback' in 'sceNp2' module (0x7be930)
E Unimplemented function 'sceNpMatching2SignalingGetPingInfo' in 'sceNp2' module (0x7be950)
E Unimplemented function 'sceNpMatching2GetServerIdListLocal' in 'sceNp2' module (0x7be970)
E Unimplemented function 'sceNpMatching2CreateContext' in 'sceNp2' module (0x7be990)
E Unimplemented function 'sceNpMatching2RegisterSignalingCallback' in 'sceNp2' module (0x7be9b0)
E Unimplemented function 'sceNpMatching2DeleteServerContext' in 'sceNp2' module (0x7be9f0)
E Unimplemented function 'sceNpMatching2RegisterRoomEventCallback' in 'sceNp2' module (0x7bea10)
E Unimplemented function 'sceNpMatching2GetRoomDataExternalList' in 'sceNp2' module (0x7bea30)
E Unimplemented function 'sceNpMatching2CreateJoinRoom' in 'sceNp2' module (0x7bea50)
E Unimplemented function 'sceNpMatching2ContextStop' in 'sceNp2' module (0x7bea70)
E Unimplemented function 'sceNpMatching2Init2' in 'sceNp2' module (0x7bea90)
E Unimplemented function 'cellSysutilAvc2GetPlayerInfo' in 'cellSysutilAvc2' module (0x7beab0)
E Unimplemented function 'cellSysutilAvc2SetVoiceMuting' in 'cellSysutilAvc2' module (0x7bead0)
E Unimplemented function 'cellSysutilAvc2UnloadAsync' in 'cellSysutilAvc2' module (0x7beaf0)
E Unimplemented function 'cellSysutilAvc2LoadAsync' in 'cellSysutilAvc2' module (0x7beb10)
E Unimplemented function 'cellSysutilAvc2JoinChatRequest' in 'cellSysutilAvc2' module (0x7beb30)
E Unimplemented function 'cellSysutilAvc2StartStreaming' in 'cellSysutilAvc2' module (0x7beb50)
E Unimplemented function 'cellSysutilAvc2InitParam' in 'cellSysutilAvc2' module (0x7beb70)
E Unimplemented function 'cellSysutilAvc2LeaveChatRequest' in 'cellSysutilAvc2' module (0x7beb90)
E Unimplemented function 'cellSysutilAvc2IsMicAttached' in 'cellSysutilAvc2' module (0x7bebb0)
E Unimplemented function 'cellSysutilAvc2GetSpeakerMuting' in 'cellSysutilAvc2' module (0x7bebd0)
E Unimplemented function 'cellSysutilAvc2SetSpeakerMuting' in 'cellSysutilAvc2' module (0x7bebf0)
E Unimplemented function 'cellSysutilAvc2GetVoiceMuting' in 'cellSysutilAvc2' module (0x7bec10)
E Unimplemented function 'cellOskDialogExtRegisterKeyboardEventHookCallback' in 'cellOskExtUtility' module (0x7bed70)
E Unimplemented function 'cellOskDialogExtSetInitialScale' in 'cellOskExtUtility' module (0x7bed90)
E Unimplemented function 'cellOskDialogExtSetBaseColor' in 'cellOskExtUtility' module (0x7bedb0)
E Unimplemented function 'cellOskDialogExtRegisterConfirmWordFilterCallback' in 'cellOskExtUtility' module (0x7bedd0)
E Unimplemented function 'cellOskDialogExtRegisterForceFinishCallback' in 'cellOskExtUtility' module (0x7bedf0)
E 'BreakPoints.dat' is broken (version=0xe6b0, break_count=0x0, marked_count=0x75b32a40, length=0x6)
E {PPU[0x1] Thread (main_thread)[0x007bd230]} sys_spu TODO: Unsupported SPU Thread options (0x2)
E {PPU[0x1] Thread (main_thread)[0x007bd230]} sys_spu TODO: Unsupported SPU Thread options (0x2)
E {PPU[0x1] Thread (main_thread)[0x007bd230]} sys_spu TODO: Unsupported SPU Thread options (0x2)
E {PPU[0x1] Thread (main_thread)[0x007bd230]} sys_spu TODO: Unsupported SPU Thread options (0x2)
E {PPU[0x1] Thread (main_thread)[0x007bd230]} sys_spu TODO: Unsupported SPU Thread options (0x2)
E {PPU[0x1] Thread (main_thread)[0x007bd090]} cellSpurs error: _cellSpursJobChainAttributeInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd1f0]} cellSpurs error: cellSpursJobChainAttributeSetName
E {PPU[0x1] Thread (main_thread)[0x007bd070]} cellSpurs error: cellSpursCreateJobChainWithAttribute
E {PPU[0x1] Thread (main_thread)[0x007bd190]} cellSpurs error: cellSpursGetJobChainId
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd090]} cellSpurs error: _cellSpursJobChainAttributeInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd070]} cellSpurs error: cellSpursCreateJobChainWithAttribute
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd0f0]} cellSpurs error: cellSpursJobGuardInitialize
E {PPU[0x1] Thread (main_thread)[0x007bd290]} cellSpurs error: cellSpursRunJobChain
E {PPU[0x1] Thread (main_thread)[0x007bde90]} cellResc error: cellRescCreateInterlaceTable : CELL_RESC_ERROR_NOT_INITIALIZED
E {PPU[0x1] Thread (main_thread)[0x007bcf10]} cellGcmSys error: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1] Thread (main_thread)[0x007bcf10]} cellGcmSys error: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1] Thread (main_thread)[0x007bcf10]} cellGcmSys error: cellGcmSetTileInfo: bad compression mode! (11)
E {PPU[0x1] Thread (main_thread)[0x007bcf50]} cellGcmSys TODO: cellGcmSetZcull(index=0, offset=0xfd0000, width=768, height=960, cullStart=0x0, zFormat=0x2, aaFormat=0x3, zCullDir=0x0, zCullFormat=0x1, sFunc=0x5, sRef=0x0, sMask=0xff)
E {PPU[0x1] Thread (main_thread)[0x007bcf10]} cellGcmSys error: cellGcmSetTileInfo: bad compression mode! (7)

**Comment by Syphurith** [comment]
Mostly the issues are SPU or RSX related. `Unsupported SPU Thread options (0x2)`, and `cellSpursJobGuardInitialize` (or other `cellSpurs` errors) and `cellGcmSetTileInfo` (or other `cellGcm` errors) for RSX. That could be the common situation for most games.
The main development of rpcs3 meets a block, and there is another being done secretly.
Also please report the log to forum, not here. This is for the accurately known issues (like Feature XXX broke the game, aka regression) or .. well not a log yep.

**Comment by Bigpet** [comment]
I don't think this is a useful issue report.

It doesn't even mention which game was tested and is really too non-descriptive to serve as the "SPURS implementation is still incomplete and buggy" reminder issue.

**Comment by kamijoutouma** [comment]
.hack//versus
I'll get the serial for it later if you want it

**Comment by kamijoutouma** [comment]
You'll have to import it from Japan though

**Comment by Syphurith** [comment]
@kamijoutouma I'm so sorry that RSX and SPU implementation are just WIP now. So any related issues aren't accepted cause we can't know exactly that is a bug or unimplemented feature. If you own a console you may setup the enviorment and help devs deal with the RE - If so please contact them on the IRC. At least our LOG message doesn't show enough information related.. So sorry.

**Comment by Bigpet** [comment]
@Syphurith  no, we do accept specific issue just fine. Even not very specific ones, but this was literally just a log dump and like I said there's better places to put those.

**Comment by Syphurith** [comment]
@Bigpet Oh well. I misunderstood that. BTW what about the next project? rpcs3 accepts only commits about RSX rendering these days. So i highly doubt what is going with the sh*t SPUs.

**Comment by tambry** [comment]
@Syphurith What's wrong with SPU implementation? AFAIK we have only SPU thread options and such unimplemented and everything else should be in working order.

**Comment by Syphurith** [comment]
@tambry I might be wrong. What i remembered is, there are many `Unsupported SPU Thread Option (0x2)` in most game logs.. And there are also many lines that indicates `CellSpurs` or `Sync` erros.

**Comment by tambry** [comment]
@Syphurith So far "Unsupported SPU Thread Option (0x2)" doesn't seem to have effected much. And yeah, HLE implementation of cellSpurs and cellSync are quite bad right now.

**Comment by Syphurith** [comment]
@tambry Orz. Thanks for reply me with clarification. Wish the next gen be soon.
