### ISSUE TITLE
Fifa 19 random freeze/crash

### ISSUE THREAD

**Issue by A-w-x** [RPCS3/rpcs3#11101]
## Quick summary

this game randomly freezes or crashes in-game

[fifa.log.zip](https://github.com/RPCS3/rpcs3/files/7462256/fifa.log.zip)

#### 5. Please provide your system configuration:
* ArchLinux
* i7-1165g7
* intel xe
* mesa git
* rpcs3-git (aur)

**Comment by nitroos-ai** [comment]
Does the game crashes as much with OpenGL?

**Comment by A-w-x** [comment]
yes
[fifaogl.log.zip](https://github.com/RPCS3/rpcs3/files/7470444/fifaogl.log.zip)
