### ISSUE TITLE
Arcade Namco System 357/359/369 Games support

### ISSUE THREAD

**Issue by BrodyGaming420** [RPCS3/rpcs3#11100]
## Quick summary

Being able to properly boot up and play Namco System 357/369/359 games

## Details

This feature would technically would just be I/O or JVS emulation with some dongle patches, since the games already properly boots up in RPCS3 because they behave and boots up almost exactly like PS3 games, just with those 2 issues wich causes said games to refuse to play, as shown on this image (Game shown here is Taiko no Tatsujin, this game uses Analog Drums as the controllers, error 19-1 is an dongle error as it's trying to look for something in dev_usb)
![image](https://user-images.githubusercontent.com/82914096/139860169-f79c0707-43cc-4566-a5df-de37c57e1f2e.png)
![image](https://user-images.githubusercontent.com/82914096/139861362-58c75341-1c6c-4438-833c-823f3c711314.png)

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
Gameplay
Debugging
etc.

#### 2. Please tell us, why your feature is important to RPCS3.
important for game and arcade preservation, these games are already getting out of support and there are some other people eager to emulate these games easily

#### 3. Please attach screenshots of the feature implemented in other projects.
there is (as far as i know) no progress of this feature in any other project yet, so there's no screenshots from this feature on other projects

#### 4. Please provide your system configuration:
OS: Windows 10 Home
CPU: Intel i5-10300H
GPU: NVIDIA GeForce GTX 1650
Driver version: 30.0.14.9649

KEEP IN MIND: these games technically already runs in RPCS3, there's no need to implement decryption keys or anything else to the emulator, only problem would be the taiko no tatsujin games since those use analog drums as the game input unlike some other games, the dongles doesnt decrypts any sort of data since there's no need to decrypt anything to begin with

**Comment by clienthax** [comment]
Needs logs

**Comment by BrodyGaming420** [comment]
> Needs logs
oops, i'm dumb and forgot to include logs, here is a log of me trying to run one of the games (Taiko no Tatsujin: Green Ver.)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7477590/RPCS3.log)
for context/reference, on this one it gets stuck in this screen with these checks
![image](https://user-images.githubusercontent.com/82914096/140404420-2690c3c3-7333-408a-875a-899aeec28469.png)
results are different throughout different games

**Comment by REZICIAK2** [comment]
Hey can i get a hold of you somehow? I'll like to get the tnj on rpcs3

**Comment by REZICIAK2** [comment]
> > Needs logs
> 
> oops, i'm dumb and forgot to include logs, here is a log of me trying to run one of the games (Taiko no Tatsujin: Green Ver.)
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7477590/RPCS3.log)
> for context/reference, on this one it gets stuck in this screen with these checks
> ![image](https://user-images.githubusercontent.com/82914096/140404420-2690c3c3-7333-408a-875a-899aeec28469.png)
> results are different throughout different games
> 
> 

Is there a way to get a hold of you?

**Comment by BrodyGaming420** [comment]
i will test this out once i get back home, thanks!

**Comment by BrodyGaming420** [comment]
> Needs a retest with the upcoming build. Go to Manage -> Virtual File System -> dev_usb and configure the devices (doubleclick on the list entry)

Taiko no Tatsujin(S111) (AKA Green Version) boots up and runs flawlessly on my end
![image](https://user-images.githubusercontent.com/82914096/167951270-ab6e7f7f-cae6-4aac-9c6c-5ea192b50f22.png)
it has a tiny bit of input lag on the drums but it's an improvement from last time and it's actually playable now, good job everyone!
https://file.garden/YbNIs_tBp0P7hfMo/Rpcs3%202022.05.11%20-%2017.31.17.02.DVR.mp4

**Comment by Megamouse** [comment]
If i understood correctly the drums are not emulated Pads, but used directly?

If they are in fact emulated pads you could try to decrease the pad sleep to decrease input lag.
You could also try to use the Multithreaded pad handler, although that one is only really useful if you do multiplayer with different pad handler (e.g. player 1 xinput and player 2 ds4).

**Comment by BrodyGaming420** [comment]
> If i understood correctly the drums are not emulated Pads, but used directly?
> 
> If they are in fact emulated pads you could try to decrease the pad sleep to decrease input lag. You could also try to use the Multithreaded pad handler, although that one is only really useful if you do multiplayer with different pad handler (e.g. player 1 xinput and player 2 ds4).

where is this "pad sleep" option?

**Comment by Megamouse** [comment]
Should be in the IO settings tab.

**Comment by AoeNagi** [comment]
How can I read the data on my HDD with a PC?

**Comment by AoeNagi** [comment]
How can I read the data on taiko HDD with a PC?

**Comment by Megamouse** [comment]
@BrodyGaming420 can this issue be closed or are there still specific problems with the systems?

**Comment by BrodyGaming420** [comment]
> @BrodyGaming420 can this issue be closed or are there still specific problems with the systems?

the only problem would be the laggy emulated USIO on weaker CPUs (sorry for the delayed reply, i've been busy this week)



> Should be in the IO settings tab.

i checked there and it only has the multithreaded pad handler options, nothing related to "pad sleep" there

**Comment by Megamouse** [comment]
Well then you could try to edit it manually in the config.yml (or the game's custom config)

**Comment by BrodyGaming420** [comment]
> Well then you could try to edit it manually in the config.yml (or the game's custom config)

it didnt had any difference when i lowered the pad handler speed value, odd

**Comment by Megamouse** [comment]
Well. This is out of scope of this issue.
If it doesn't help then no idea.

**Comment by anxious132** [comment]
Tekken 6 Vanilla, is running but with Error 8
log :
![4e5e16_ab9f9c4a61f14d9d99b55f284f79c9c9_mv2](https://user-images.githubusercontent.com/110099202/181227745-87de4aca-a825-49ba-a0cc-58e310c61858.jpg)

E SYS: 'cellNetCtlInit' failed with 0x80130102 : CELL_NET_CTL_ERROR_NOT_TERMINATED [1]
U PPU TODO: Unimplemented syscall sys_game_watchdog_start -> CELL_OK (r3=0x5, r4=0x1, r5=0x0, r6=0x6b6340, r7=0x0, r8=0x6bd838, r9=0x800bf4, r10=0x6d9100)
S PPU: LLVM: Loaded module v5-kusa-KSs9JzJU0dS673WTN14GGy-00001G-sandybridge.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libatrac3plus.sprx” (id=0x2300fa00)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
U PPU TODO: Unimplemented syscall sys_game_watchdog_clear -> CELL_OK (r3=0x32160f00, r4=0x0, r5=0x0, r6=0x6b6340, r7=0x0, r8=0x6b4fe8, r9=0x32160f00, r10=0x32160f00)
S sys_usbd: Ldd device matchup for <PS3A-USJ>, assigned as handled_device=0x1
U PPU TODO: Unimplemented syscall sys_game_watchdog_clear -> CELL_OK (r3=0x32160f00, r4=0x0, r5=0x0, r6=0x6b6340, r7=0x0, r8=0x6b4fe8, r9=0x32160f00, r10=0x32160f00)x1830

**Comment by taeintheface** [comment]
> Needs a retest with the upcoming build. Go to Manage -> Virtual File System -> dev_usb and configure the devices (doubleclick on the list entry)

how do you configre the divices sorry if my english is bad english is my second language

**Comment by OndaCouch421** [comment]
is mouse input supported for any of these titles i know some of these games are shooters. just trying to find more information about it.

**Comment by Alidonis** [comment]
> Doesn't look like a full log file

my bad! here it is. the full one.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14483389/RPCS3.log)
