### ISSUE TITLE
CURL/SSL does not work on local linux builds 

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#11124]
On a test system confirmed to have network connectivity, proper DNS settings etc., RPCS3 cannot download patches.

Specifically, selecting `Manage` > `Game Patches` > `Download latest patches` throws the exception `an error occurred during the download process`.  

Log information: 
`E {TID: 139662672787200} NET: Curl error: SSL connect error`

Can bisect if necessary, in case this isn't a known network-level issue.

Test system information:
* OS: Linux Mint 20.2 / kernel 5.11
* CPU: Intel i7-10870H
* Compiler: gcc 11.1.0
* Build tested: dc0793b731f87569b730a037524beb6ad4309698
* Log from bad build: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7515651/RPCS3.log)
* Log from good build: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7515700/RPCS3.log)

**Comment by AniLeo** [comment]
Cannot reproduce

**Comment by Shoegzer** [comment]
Okay but what OS did you test against?

More information:

- The issue occurs even with a clean config, after removing `~/.config/rpcs3`
- Using old binaries I had previously compiled, I discovered that builds prior to August 30th (after commit 67813737279dba78593b13e2407b71b37bb1d9f8) work, but builds after Sept. 11th (after commit c7f5475b5647e616f8da38112ee8e253beae850a) do not, so the bad commit must be somewhere in between.
- This issue is likely related to commit ee6e4c493d782fff5f92cbdad6c14f904f02012a as it's the only SSL/TLS related commit in the above date range, but I can't be sure (@p01arst0rm can you comment?)
- With the above in mind, I attempted to bisect to the exact commit, but received the message below regarding LLVM.  However, this exception is no longer thrown in builds against master, so it must have been fixed between then and now.

```
CMake Warning at 3rdparty/llvm.cmake:29 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "11.0".

  The following configuration files were considered but not accepted:

    /home/testing/Desktop/rpcs3/build/3rdparty/llvm_build/lib/cmake/llvm/LLVMConfig.cmake, version: 1.0.23
    /usr/lib/llvm-10/cmake/LLVMConfig.cmake, version: 10.0.0
    /lib/llvm-10/cmake/LLVMConfig.cmake, version: 10.0.0
```

**Comment by p01arst0rm** [comment]
the only changes made in that patch were to system/builtin building, try changing either and seeing if it makes a difference

**Comment by Shoegzer** [comment]
Thanks @p01arst0rm.  I'm not sure what you mean by system/builtin as I don't see that directory in the build tree, but in master, I attempted to replace all the files you changed in your PR as listed [here](https://github.com/RPCS3/rpcs3/commit/ee6e4c493d782fff5f92cbdad6c14f904f02012a) with versions of the same files from an earlier good build.  However, the build failed to compile with:

`rpcn_client.cpp:(.text+0x35e9): undefined reference to wolfSSL_write_dup`

Here's an [ldd result](https://pastebin.com/TpNgTQ6k) run against a build from today's master without the above changes.  The libraries look fine to me and although I see no reference to ssl libs, there was no reference from a good build either.

Finally, here's a [CMake log](https://pastebin.com/RT2nTNe0) in case it helps.

**Comment by Megamouse** [comment]
In theory this issue is invalid, as you didn't upload a proper log of the latest official master build.
In case you are building from scratch: did you update all submodules before building?

**Comment by Shoegzer** [comment]
@Megamouse I uploaded the log and posted above.  I'm building from scratch, and doing this with every build to update submodules:

`git clone --recursive https://github.com/RPCS3/rpcs3.git
`

**Comment by Megamouse** [comment]
Does the issue appear with the appimage

**Comment by Shoegzer** [comment]
Good suggestion, and actually no it doesn't.  Perhaps this is due to an out-of-date library from the ubuntu repo?

**Comment by hcorion** [comment]
Yes, that would be the problem. The ubuntu repo you're using should be building WolfSSL with write dup enabled.

**Comment by Shoegzer** [comment]
@hcorion thanks, but I believe it IS building with write dup enabled - the write_dup error I posted above only occurred after I compiled against a bad build with certain files replaced from a good tree, as part of a separate test, and is probably unrelated to the main issue?

And if I'm wrong, is there a way for Ubuntu users to work around this, to continue compiling working builds into the future?

**Comment by hcorion** [comment]
What system libraries are you using? Have you tried building with the built-in curl and wolfssl submodule?

**Comment by Shoegzer** [comment]
Thanks, as I mentioned above here's an [ldd output](https://pastebin.com/TpNgTQ6k) from current master.  Also from the [CMake log](https://pastebin.com/RT2nTNe0) above it seems I'm already doing that:

`-- RPCS3: building libcurl + wolfssl submodules`

**Comment by hcorion** [comment]
Try building with system curl

**Comment by p01arst0rm** [comment]
> Thanks @p01arst0rm. I'm not sure what you mean by system/builtin

theres a couple of flags you can specify to the cmake configure, ``USE_SYSTEM_WOLFSSL`` and ``USE_SYSTEM_CURL``. try enabling/disabling both or either and retest

**Comment by p01arst0rm** [comment]
> Thanks, as I mentioned above here's an [ldd output](https://pastebin.com/TpNgTQ6k) from current master. Also from the [CMake log](https://pastebin.com/RT2nTNe0) above it seems I'm already doing that:
> 
> `-- RPCS3: building libcurl + wolfssl submodules`

the ldd doesnt show curl as properly linked to the binary 🤔

**Comment by Shoegzer** [comment]
Thanks.  I tried a build of master with:

`$ cmake -USE_SYSTEM_WOLFSSL -USE_SYSTEM_CURL ../rpcs3`

However, the build seemed to ignore this and use the same 3rdparty submodules, as shown [here](https://pastebin.com/PSeWTP6g) (I also included the make log with this one as well).  As expected, the rpcs3 binary couldn't download the patch file.

Hopefully these are the right libraries, but for confirmation:

```
$ apt list libwolfssl-dev
Listing... Done
libwolfssl-dev/focal,now 4.3.0+dfsg-2 amd64 [installed]

$ apt list libcurl4-openssl-dev
Listing... Done
libcurl4-openssl-dev/focal-updates,focal-security,now 7.68.0-1ubuntu2.7 amd64 [installed]
libcurl4-openssl-dev/focal-updates,focal-security 7.68.0-1ubuntu2.7 i386
```

**Comment by Megamouse** [comment]
try
cmake -DUSE_SYSTEM_WOLFSSL -DUSE_SYSTEM_CURL ../rpcs3

**Comment by Shoegzer** [comment]
Thanks, I suppose that should have been obvious.  Actually I believe it's:

`cmake -DUSE_SYSTEM_WOLFSSL=TRUE -DUSE_SYSTEM_CURL=TRUE ../rpcs3`

That said, the wolfssl lib in the ubuntu repo is outdated anyway:

```
-- Checking for module 'wolfssl>=4.7.0'
--   Requested 'wolfssl >= 4.7.0' but version of wolfssl is 4.3.0
CMake Error at /usr/local/share/cmake-3.20/Modules/FindPkgConfig.cmake:556 (message):
  A required package was not found
```

**Comment by p01arst0rm** [comment]
hang on where are you building from?

**Comment by Shoegzer** [comment]
Building from Linux Mint 20.2 which uses ubuntu 20.04 package base.

**Comment by Megamouse** [comment]
please test https://github.com/RPCS3/rpcs3/pull/11137

it may tell us more about the error.

**Comment by Shoegzer** [comment]
Hey thanks: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7516509/RPCS3.log)

Notably: `Details: SSL_connect failed with error -313: received alert fatal error`

`--verbose-curl` didn't seem to do anything though (same results as the above).

**Comment by Megamouse** [comment]
Look at the console output

**Comment by Megamouse** [comment]
Also, try after compiling wolfssl with --enable-debug

**Comment by Shoegzer** [comment]
The console doesn't provide any related output, what am I missing?  

Also, if I understand you correctly, you're asking me to compile and install a separate wolfssl library using `./configure --enable-debug`.  Is that right?
