### ISSUE TITLE
Regression: Some disc games deadlocking or crashing on startup (#10849)

### ISSUE THREAD

**Issue by Alopex-AU** [RPCS3/rpcs3#11126]
## Quick summary
Some physical disc backups are no longer booting correctly after build V0.0.18-12776

## Details

Starting with build V0.0.18-12783, some disc based backups (all IRD verified) completely deadlock either during building or verification of cache, are being mislabelled as HDD boot games that are corrupt, or are outright crashing, where all of them booted perfectly using the previous build V0.0.18-12776.

I have tested many builds after 12783, including the most recent as of writing V0.0.19-12996, all of which act the same. No setting have been altered from default.

Upon force closing a stalled game, RPCS3 crashes.

Games I have experienced this with so far are:

Sly Cooper: Thieves in Time (BCUS98247) deadlock during cache checking or building
The Sly Trilogy (BCES00968) deadlock during cache checking or building
Anarchy Reigns (BLUS30632) automatically shuts down after caching
Shadows of the Damned (BLUS30653) shuts down after caching, citing HDD boot game corrupted
Lollipop Chainsaw (BLUS30917) shuts down after caching, citing HDD boot game corrupted

Edit: additions:

Tales of Xillia (BLUS31006) claims install data is corrupted, even when no install data is present.
Tales of Xillia 2 (BLUS31397) deadlock after caching, same memory error as the Sly games, but does not crash the emulator when closing.
Tales of Graces F (BLUS30903) deadlock during cache as the Sly games, but does not crash when closing.

The PSN digital versions of the above are unaffected and boot just fine.

#### 6. Please provide your system configuration:
* Windows 7 SP2 64bit
* Intel i7 4790K 4ghz
* Radeon R9 290X
* Radeon Software 21.5.2

Image and logs:

![RPCS3-deadlocked](https://user-images.githubusercontent.com/93702059/140795841-ce1d321c-f9ed-4159-a878-9cf58068efca.jpg)

[Build 12776 Working.zip](https://github.com/RPCS3/rpcs3/files/7499182/Build.12776.Working.zip)
[Build 12783 Regressions.zip](https://github.com/RPCS3/rpcs3/files/7499183/Build.12783.Regressions.zip)

**Comment by bilalfakhouri** [comment]
Are you using mounted ISOs?
Might be same as #10950

**Comment by Megamouse** [comment]
Isos are not supported

**Comment by elad335** [comment]
Reading a read-only disc directory with an accessible filesystem is supported.

**Comment by Alopex-AU** [comment]
> Are you using mounted ISOs? Might be same as #10950

I'm using mounted ISOs on a daemon tools virtual drive.

> Isos are not supported

I understand RPCS3 doesn't load ISOs directly, but hasn't accessing the filesystem from a disc image via a virtual drive always been supported? It's always been the method I've used and works flawlessly for my entire set of backups up until this small number of them broke in build 12783.

**Comment by Megamouse** [comment]
It seems to be some fuckup with game directories that have a drive letter as root.
Unless someone changed some checks like write access etc.

**Comment by Foxxcoon** [comment]
Unfortunately still bugged as of today. Doesn't even matter if it's a disc or not, RPCS3 just can't handle booting from the root of a drive anymore.

Some more games that are affected:
3D Dot Game Heroes
Anarchy Reigns
Afro Samurai
Armored Core Verdict Day
Birds of Steel
Blood Drive
God of War Collection
Wipeout 2

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10352548/RPCS3.log.gz)

(also the Discord Bot claims that booting from discs is not supported in this case, even though this is from the same drive that RPCS3 is located in and it really shouldn't matter anyways with mounted decrypted ISOs)
I've tried to bring this issue up in Discord Help some times already but was always shut down with "ISOs are not supported"...
