### ISSUE TITLE
Please add Fullscreen

### ISSUE THREAD

**Issue by SuperIsakSwahn** [RPCS3/rpcs3#11128]
## Quick summary
Please briefly describe what feature you would like RPCS3 to have. Fullscreen, it significally increases your fps

## Details

Please describe the feature as accurately as possible. Theres only windowed borderless

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay my computer might actually barely be able to play cars 2 because of the increased fps. No idea what to put on the other stuff, fullscreen shouldn't really have much to do with that I think.
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.

#### 3. Please attach screenshots of the feature implemented in other projects.
Not quite sure why that would help you but im sure you need it if you ask https://superisakswahn.tumblr.com/private/667314154131111936/tumblr_9jeUY9JHVSfpQMdbB
#### 4. Please provide your system configuration:
* OS windows 10
* CPU Intel Core i5-4670K
* GPU NVIDIA GeForce GTX 1070 (GP104-200) [NVIDIA]
* Driver version 456.71 (Assuming it was for the gpu)
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by isJuhn** [comment]
see discussion in #3650
