### ISSUE TITLE
Resistance Fall of Man freezes in a certain place

### ISSUE THREAD

**Issue by StalkerDolg** [RPCS3/rpcs3#11132]
This game has a "playable" status, but it looks like it turned out to be broken.
At the very beginning of the chapter entitled "Path of Least Resistance" we see a helicopter taking off, and at this moment the game freezes, and purple inscriptions appear in the log. Can someone fix this.
P.S. I've tried reinstalling the emulator, deleting configs and cache. Nothing helped.
![Безымянный](https://user-images.githubusercontent.com/50276678/141066410-9a02bcb2-0150-410f-90fc-22766de58056.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7510590/RPCS3.log)

**Comment by MSuih** [comment]
According to your log you've installed disc game to dev_hdd0/game, most likely because it's an iso2pkg conversion. These are not supported right now. Get a proper disc dump first before opening issues.

**Comment by StalkerDolg** [comment]
I was filming a working dump. But then I installed a patch with fan localization into Russian. On the console, the patched version runs without problems

**Comment by AniLeo** [comment]
You need to use a clean copy when submitting these types of issues.

**Comment by MSuih** [comment]
If the issue is caused by that localisation then you need to ask that project to fix it. If it isn't then submit a report without the modification installed
