### ISSUE TITLE
[Feature Request] create a chromebook version

### ISSUE THREAD

**Issue by EliTheFox17** [RPCS3/rpcs3#11131]
## Quick summary
Please briefly describe what feature you would like RPCS3 to have.

## Details

Please describe the feature as accurately as possible.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.

#### 4. Please provide your system configuration:
* OS
* CPU
* GPU
* Driver version
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by clienthax** [comment]
![unknown](https://user-images.githubusercontent.com/1056270/141030426-99d9f8ca-6fe7-4dd4-b6c4-a7fb6fb8abb2.png)

**Comment by EliTheFox17** [comment]
> ![unknown](https://user-images.githubusercontent.com/1056270/141030426-99d9f8ca-6fe7-4dd4-b6c4-a7fb6fb8abb2.png)

It could tho

**Comment by EliTheFox17** [comment]
it could

**Comment by clienthax** [comment]
![image](https://user-images.githubusercontent.com/1056270/144665281-2ea0fb94-47a5-4940-bca1-dd5c901d9860.png)
