### ISSUE TITLE
Regression: Sprite corruption issue in Disgaea D2 [BLES01939] (#9738)

### ISSUE THREAD

**Issue by GittallioB2k** [RPCS3/rpcs3#11136]
## Summary

Occasionally, certain sprites of the 2D characters in Disgaea D2 will suffer from graphical corruption.
It seems to appear randomly on battle stages but there is a reliable way of triggering the issue in the game's main hub (see reproduction instructions).

I managed to pinpoint that **the regression being introduced by #9738** - any build before that (11727 and lower) does not seem to exhibit this issue whereas any later one (11736 and newer).

## Reproduction

Issue can be reproduced with BLES01939 and default settings quite easily:

1. start a new game, skip all dialog by double pressing triangle until you reach the main base
2. save the game and close it
3. start the game load the save again
4. from the base, take the upper left exit to the dojo room
5. turn around and use the exit you came from to return to the base again
6. again enter the dojo room

After entering the dojo room the second time, Etna's sprite (the red haired girl) will get corrupt.

Having a save of being at the base, the issue can reliably be reproduced beginning at step 3.

## Screenshot

![dd2_sprite_glitch](https://user-images.githubusercontent.com/94079700/141190327-62479e51-6a00-433c-a692-54304f6cca2c.png)

## Other Notes

From my testing, this affects Windows and Linux builds, OpenGL and Vulkan renderer, integrated Intel graphics as well as Nvidia GPUs.
None of the available options in the CPU, GPU, Advanced or Debug tab seem to help getting rid of the issue on the builds affected by it.

**Comment by illusion0001** [comment]
Provide RSX Capture + Log

**Comment by Darkhost1999** [comment]
Also if a save file is needed to reproduce the issue. Please provide that as well.

**Comment by GittallioB2k** [comment]
> Also if a save file is needed to reproduce the issue. Please provide that as well. Since the message says start a new save and later "having a save at the base can help". It sort of sends a mixed message.

Sorry, I guess I worded that poorly. I meant: the issue is indefinitely reproducible beginning at step 3 once you have the save.

The save is really easy to create. Just start a new game and skip the dialogs (double press triangle) and exit the first room until you reach the main base, then position your characters near the top left exit. It takes less than a minute to create the save from a freshly booted game.

Anyhow, here is a save file with the characters right in front of the upper left exit to the dojo. It was created on the updated 1.40 version of the game: [Save_BLES01939_v1.40.zip](https://github.com/RPCS3/rpcs3/files/7522637/Save_BLES01939_v1.40.zip)

**Comment by GittallioB2k** [comment]
> Provide RSX Capture + Log

Log + RSX Capture (Vulkan): [Log_and_RSX_Vulkan.zip](https://github.com/RPCS3/rpcs3/files/7522648/Log_and_RSX_Vulkan.zip)

Log + RSX Capture (OpenGL): [Log_and_RSX_OpenGL.zip](https://github.com/RPCS3/rpcs3/files/7522646/Log_and_RSX_OpenGL.zip)
 
... I hope I did it right.

**Comment by AniLeo** [comment]
Tagging @kd-11

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/11203

For future reports, please do not assume we understand how to play the games. It took me an embarrassingly long amount of time to figure out where "the base" is and even after that to find the dojo (which is upper-left in isometric but lower left in screen coordinates btw). Other than that, good job with the instructions, once I figured that out it was really easy to repro.
