### ISSUE TITLE
Convert_swizzle.elf regression

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1113]
It caused by invalid location calling from NV3089_IMAGE_IN_SIZE

E {RSXThread} Exception: GetAddress(offset=0x0, location=0x1130000): invalid location

**Comment by Altaiar** [comment]
when i run super frog give this ...... 
http://s3.picofile.com/file/8194803484/Capture.PNG

**Comment by tambry** [comment]
@Altaiar Yes? What's the problem? Most games don't. And swizzle2D of NV3089_IMAGE_IN_SIZE is unimplemented, thus there may be some problems (graphical glitches maybe), but I doubt it would make the game fail to link a shader.

**Comment by Altaiar** [comment]
problem is why program has stopped working!

**Comment by tambry** [comment]
@Altaiar Well, maybe you would be nice enough to debug the program using Visual Studio 2013 and tell us why it encountered something so fatal forcing it to stop working?

**Comment by Syphurith** [comment]
@Altaiar the rpcs3 has problem existing in its memory management as i recalled. Someone seems tried to use VLD to detect the memory problem, however the vld needs much modification and the plan failed. If you could use any tool related to memleak or other detection you are nice to go.
Almost all of those '0x........ can not be read/write' are problems in memory usage, which is servious and caused the program from running further. If you can archive a version of rpcs3 which doesn't have any memory problems.. that's awesome and it may enable devs to develop even more.
Even the clues about just this issue would help. Well if you can't find out why and don't want to learn about its internals, i'm very sorry there would be no solution present for you.
If you don't understand what i said, or just don't believe it. Feel free to blame me, yep.

**Comment by tambry** [comment]
@raven02 Is this still an issue?

**Comment by danilaml** [comment]
@tambry it should be fixed by #1327, but couldn't test myself since I don't have that sample.
