### ISSUE TITLE
[Feature Request] [RPCN] Reset password

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#11142]
Currently there is no way to reset an RPCN password, so if it's lost or forgotten, the original email/username cannot be used again.  This feature would permit users to reset their password and continue using the same email/username.

One suggestion: include a "Reset Password" button in the RPCN global config, which would then query the user for the email address associated with the account.  A one-time token would be sent to the address, which would then be input by the user in a separate RPCN dialog along with the new password to effect the change.

Note: The existing option to "Change Password" is inaccessible, at least in my experience, perhaps because the above feature is intended in the future.  If so, please feel free to close this request.

**Comment by aggregate1166877** [comment]
So much this. I decided to do 'Set Password' thinking it will reset the password. I did _that_ because my token wasn't being emailed to me (I'm unsure why the previous token stopped working). Now my original (randomly generated, not saved) password is gone and I can't reset it. It's a pretty hollow feeling knowing I have to discard the account I've used for a year now and go with a secondary email address.

**Comment by metraberryy** [comment]
pretty much the exact situation described in the last post here just happened to me
would be nice if this could be worked on soon

**Comment by Shoegzer** [comment]
@aggregate1166877 That happened to me for the same reason as well, and I've been offline since then.  I'm guessing this isn't easy an easy feature to add.

It would be great to at least confirm "Change Password" is just a placeholder rather than somehow made availble e.g. triggered through a hidden config option, though even then it would probably require knowledge of the original password, and if so a reset feature is still badly needed.

**Comment by Shoegzer** [comment]
I tested this issue against #12073 which implements the change password feature, and it works well, so I will close it now.  Thanks much @RipleyTom.

As a side-note/question: change password testing worked against the official server, though testing against the test server (where the account was originally created) triggered a connection error.  Does this mean the test server has been decommissioned and the official server is recommended now, or will it be brought back online for future testing?

**Comment by MSuih** [comment]
Test server is used whenever the server side of RPCN needs more testing and for normal use we recommend the official one. As there is nothing new to test right now the test server has been shut down, but it'll come back online once the next update pops up.
