### ISSUE TITLE
RSX: Some (or maybe many?) members of rsx::thread and its subclasses aren't properly reset between boots

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#11143]
Contrary to what you'd expect, rsx threads aren't actually destroyed between boots, which means they have to be manually initialized and reset when the emulator stops.

This small detail can lead to human error, which means developers may not know this and simply add a bunch of members, believing that the stuff is surely reset on the next boot, or they may just forget to deal with this properly.

Why do I tell you this? Because currently there are a bunch of members that are **not** properly reset and therefore contain old data that is carried over to the next game boot.

One such example would be `display_buffers`, which starts as a zero initialized array of objects on the first boot, but magically contains random data on the second game boot.

Plz fix, thx

**Comment by elad335** [comment]
This is not true, display_buffers is just initialized afterwards. And RSX is resetted each boot by FXO which isis why we have FXO instead of magic globals.

**Comment by Megamouse** [comment]
Ah indeed. The confusion came from some internal talks with the cat.
I tested and you're right.

**Comment by kd-11** [comment]
I'll perform an audit to figure out if anything else was missed.

**Comment by elad335** [comment]
I find a tad irritating to look for such bugs, I suggest zeroizing FXO's buffer at game stopping and RPCS3 process spawn.

**Comment by kd-11** [comment]
Partially addressed by https://github.com/RPCS3/rpcs3/pull/11151/commits/bcecdab24bf22ea64f97e8cd7095869e93d54845.
I'll do some minor housekeeping to prevent such issues in future, just needs some refactoring once I fix the main regressions in my queue.
