### ISSUE TITLE
Just Cause 2 no longer boots, claims files are missing when they aren't

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#11145]
## Quick summary

Just Cause 2 claims its own files are missing or corrupted, will not boot.

## Details

On RPCS3 v0.0.19-13006-8b3ed7b5, the game attempts to boot but can't find "key.edat" even though this file clearly exists.   Tried re-dumping the game and starting over with no caches, no luck.  After compiling PPU modules and on every subsequent boot, RPCS3's UI will claim "ERROR: Game data is corrupted.  The application will be terminated."  This was not an issue a few updates ago.

#### 1. Please attach RPCS3's log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7525132/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.

![Capture](https://user-images.githubusercontent.com/58268914/141416540-63e2638d-328a-4dfc-b8ce-9a2edfc2702e.PNG)

#### 4. Please provide comparison with real PS3.

Real PS3 consoles are able to find all the files and have no problems booting the game.

#### 5. Please provide your system configuration:
* OS: Windows 10 x64 Build 19043
* CPU: Intel Core i9-10900K
* GPU: NVIDIA RTX 2080 Super
* Driver version: 496.13

**Comment by Asinin3** [comment]
Find where it broke

**Comment by elad335** [comment]
Test abd upload log with #11146

**Comment by SlyCooperReloadCoded** [comment]
Oh no, my inexperience with GitHub is showing.  How do I download that?  I looked around for artifacts on that page as well.

**Comment by krazynez** [comment]
Click the "Artifacts" download button

 https://cirrus-ci.com/task/5639130123075584

**Comment by SlyCooperReloadCoded** [comment]
That change fixes it.  I noticed edat changes happening recently, I figured it was that.
