### ISSUE TITLE
rpcs3 only starting when sudo is used

### ISSUE THREAD

**Issue by Dhamma-valence** [RPCS3/rpcs3#11157]
When I run the rpcs3 binary I made from source as a normal user, it segfaults because of something related to gfxrecon / vulkan. I get this output:

```
rpcs3
Debugger: 0
vkBasalt err:   no good config file
[gfxrecon] INFO - Initializing GFXReconstruct capture layer
[gfxrecon] INFO -   GFXReconstruct Version 0.9.9 (122c06e)
[gfxrecon] INFO -   Vulkan Header Version 1.2.189
[gfxrecon] ERROR - fopen(gfxrecon_capture_20211114T223649.gfxr, wb) failed (errno = 13)
[gfxrecon] FATAL - Failed to initialize TraceManager
RPCS3: Vulkan Device Enumeration Thread: SIG: Thread terminated due to fatal error: Segfault reading location 0000000000000000 at 00007ff738122a65.
Emu Thread Name: 'Vulkan Device Enumeration Thread'.

This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
```

Whenever I run the AppImage, it also does not run, giving the following (different) output:
```
Debugger: 0
qt.qpa.plugin: Could not find the Qt platform plugin "minimal" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

zsh: abort      ./rpcs3-v0.0.19-13010-7dc3a50d_linux64.AppImage
```

Strangely enough however, when I run either the binary or the AppImage as root using sudo, it runs perfectly fine. The splash screen about reading the quickstart guide comes up, the main gui launches, and I'm able to boot games just fine. I actually tried using the snap as well, but it had the exact same problem.

I have to wonder if this is a permissions issue with the libraries it depends on, since I've had some issues with that with other programs recently (though I believe I fixed that by using getfacl on a snapshot and setfacl to restore original permissions),  and it would make sense if that were the case since root could run it, but a regular user could not. However, after using `ldd` and `stat`ing the list of rpcs3's linked libraries, they all have the open permissions 0777 which ought be accessible root and normal users alike.

I've also tried changing the qt platform plugin to xcb instead of minimal using $QT_QPA_PLATFORM; I've tried directly giving the binary the plugin path by manually setting $QT_PLUGIN_PATH as well as $LD_LIBRARY_PATH.

I get the feeling that I've just mucked up something totally obvious, but so far I have no clue as to what that could be.

**Comment by MSuih** [comment]
For the appimage issue, you could try to install xcb stuff with this command: `sudo apt-get install libx11-xcb1 libxcb1 libxcb-xinerama0`

As for the vulkan issue, it seems to be entirely caused by gfxreconstruct. "Vulkan Device Enumeration Thread" is just checking if you have any vulkan-compatible rendering devices, if it crashes then there's some driver which fails to even init properly. We can't really do anything to driver issues on our side.

**Comment by MSuih** [comment]
```
[gfxrecon] ERROR - fopen(gfxrecon_capture_20211114T223649.gfxr, wb) failed (errno = 13)
[gfxrecon] FATAL - Failed to initialize TraceManager
```
Errno 13 is access denied, by the way. So there's clearly a configuration issue with gfxrecon. I'd recommend asking them for help, or to disable it entirely.

**Comment by Megamouse** [comment]
Based on a real naive google search, VKBASALT_CONFIG_FILE is probably not properly set in path

**Comment by Dhamma-valence** [comment]
You mentioning $VKBASALT_CONFIG_FILE got me on the path of looking at related variables and I managed to finally fix it!

The final command which worked (And happened to fix Lutris as well!) was:
`VK_INSTANCE_LAYERS='' VK_LAYER_PATH='' VULKAN_SDK='' QT_QPA_PLATFORM='' ENABLE_VKBASALT=0 MANGOHUD=0 rpcs3`

These variables' original values were:
```
VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation:VK_LAYER_LUNARG_gfxreconstruct   
VK_LAYER_PATH=/home/$USER/vulkan/1.2.189.0/x86_64//etc/vulkan/explicit_layer.d
VULKAN_SDK=/home/$USER/vulkan/1.2.189.0/x86_64/                               
QT_QPA_PLATFORM=minimal
ENABLE_VKBASALT=1
MANGOHUD=1
```
Now some of those unset variables might not be necessary and I'll eventually go through them one-by-one to see what's needed and what isn't, but for now just having it work is good enough! It's been such a pain meticulously checking out different possible causes and it feels so good to have finally figured out what was wrong.

I'm not 100% sure what the issue *really* is, though for some context I use GOverlay to manage the system-wide settings for Mangohud, VKBasalt, and ReplaySorcery. That plus some of the VK/VULKAN related variables which likely got recently changed after installing the vulkan SDK in order to build RPCS3 is why these variables were set in the first place. Hopefully this can help anyone in the future having this kind of issue,

**Comment by Megamouse** [comment]
Glad you found ou
