### ISSUE TITLE
[Feature Request] RSX Capture shows some kind of  User feedback

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11156]
## Quick summary
When I create an RSX capture every single time the game just looks like it's broken. With that kind of a visual feedback my mind is racing with `Did I get a capture? Did it even work? Am I safe to upload this? Will I get criticized for an incomplete capture?`

## Details
Add a progression bar or output a trophy/notifcation/icon that says RSX captured upon completion.
Maybe add a QT beep at the completion of a capture.

Cause all I know is when I open an RSX capture inside of RPCS3. It just looks like a single frame of the actual game I was playing. With a measurable performance overlay FPS and everything but like it's a 1 frame constant video.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Utilities

#### 2. Please tell us, why your feature is important to RPCS3.
People can feel confident in providing the necessary information satisfied and knowledgeable that the information was acquired successfully.

#### 3. Please attach screenshots of the feature implemented in other projects.
I don't know of any other projects that utilize an RSX capture.

#### 4. Please provide your system configuration:
* Windows 11
* Ryzen 5 3600
* GTX 1660S 
* WSL driver 510.06
* N/A

#### Please include.
* Anything else you deem to be important
Providing information that is visible to the User significantly increases confidence and improves future issue reports as there is a whole lot less confusion.
I honestly think the best thing to do would be to cout a message like `RSX capture complete. You may find your capture in your RPCS3/captures directory`
Or include this message in the view log/tty

**Comment by RainbowCookie32** [comment]
Emulation is paused and there's a message in the log if a capture is successful.
![image](https://user-images.githubusercontent.com/16805474/141691567-1270f604-f450-4077-9ae4-76209b8bad1a.png)

**Comment by Darkhost1999** [comment]
So emulation is supposed to be capable of resuming and I can continue playing without closing all of RPCS3? Is the capture instantaneous for you or does it take a minute or 2?

I just have never seen that message and I am able to open an RSX capture I've taken. But have never resumed emulation or as said seen that feedback.

**Comment by RainbowCookie32** [comment]
It should be capable of resuming, and it shouldn't take long in most cases. How long it takes probably depends on the game, in the example above it was instantaneous but it was just a black screen right after booting a game.

**Comment by Darkhost1999** [comment]
The video is still processing HD. But I hope to show what I mean and in the process identify if I am at fault such as I did not wait long enough therefore adding value to a progress bar of some kind. Or if there is an issue displaying a message that RSX was captured.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7534336/RPCS3.zip)
https://youtu.be/fhiV6dCU1BM

**Comment by Darkhost1999** [comment]
Can we still implement this with the rsx overlay instead of "hold start to resume."
If rsx capture "Frame capture saved successfully to $path./n Hold start to resume gameplay"
