### ISSUE TITLE
Demon's Souls stuck on loading screen

### ISSUE THREAD

**Issue by berwyngabriel** [RPCS3/rpcs3#11154]
I followed a bunch of guides about settings required for Demon's Souls to work, including the all-important shader one. However, all I get is [this](![image](https://user-images.githubusercontent.com/94285736/141674245-4c68cfda-d765-460b-b669-96318ae8b450.png)) and then it's just stuck.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7533420/RPCS3.log)

I don't know how to find performance overlay

I don't know how to find system config, sorry.

**Comment by YuriNator557** [comment]
![image](https://user-images.githubusercontent.com/76178650/141675850-d195bbec-9132-4a78-be9d-9b59023e167c.png)
