### ISSUE TITLE
Could we get a custom build for Uncharted

### ISSUE THREAD

**Issue by INFINITY99K** [RPCS3/rpcs3#11170]
Since Uncharted 4 and Lost legacy are coming to PC I'd like to see a build that is "optimised" to run Uncharted on RPCS3 to play the full trilogy but, at the moment unfortunately, the game suffers from unbearable FPS instability ranging from 60FPS - 18FPS but, what is worse that it drops in the sequences that should be, you know exciting drops in the range of between 23 ~ 25 FPS and the problem that it stays there and also the vegetation problem (floating plants) on NVIDIA hardware.

Just imagine if you come up with a Custom Build capable of running Uncharted at 60fps (or even at 30fps) the graphics mods will come and people are going to make graphics packs and inject to the game directly so, people could test the so called "definitive experience" and that's going to be awesome and actually I am working on a one that could be applied to the game's ROM (specifically AI Upscaled PS4 video sequences and the PS3 Textures) but what discourages from it is that the FPS is so low and so unstable.

The amount of work you poured into this emu is unimaginable even Sony didn't bother with the PS3 and decided to leave its legacy in the dust and continue on with their new consoles but, I just we get a custom build that streamlines some of the problems with those specific games.

Rig:
- Ryzen 3700X, 4.5GHz.
- 16GB Ram 
- RTX 2070 Super.

**Comment by MSuih** [comment]
This issue tracker is for the main emulator version only, not for custom builds
