### ISSUE TITLE
i cant run the game wait i missing 

### ISSUE THREAD

**Issue by prince911** [RPCS3/rpcs3#11179]
![image](https://user-images.githubusercontent.com/24402355/142726924-8dc3a207-0eb5-4516-93f2-f9b5d389ff66.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7574555/RPCS3.log)

**Comment by krazynez** [comment]
I recommend you join the [Discord](https://discord.com/invite/s9hBeHXt) and upload your log to the #help channel.
