### ISSUE TITLE
5-8 buzz controllers crash

### ISSUE THREAD

**Issue by MarcusRivet** [RPCS3/rpcs3#11174]
## Quick summary
So playing most buzz games works flawlessly with up to 4 buzz controllers but buzz games supports up to 8 players and you need to use 2 usb buzz recievers if you want to connect more than 4 buzz controllers. But rpcs3 just crashes as soon as I launch any buzz game with 2 usb buzz recievers connected. If I try to put in the second buzz usb reciever after launching the game, it just doesn't work to connect any more controllers. I will gladly donate 100 euros for whoever is willing to do this job. (I just spent 500+ euros for an entire buzz setup and was really sad to discover that playing more than 4 players doesn't work) 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7572179/RPCS3.log)

**Comment by RipleyTom** [comment]
https://github.com/RPCS3/rpcs3/pull/11193 may fix, please test :).

**Comment by MarcusRivet** [comment]
Will test it in 2 hours and let you know the results

**Comment by MarcusRivet** [comment]
Unfortunately crash still happens if I start any of the Buzz games with both USB dongles connected and still doesn't work connecting any more controllers if I try to connect the second buzz USB dongle after the game is already started almost as if RPCS3 doesn't know the second dongle exists, but it is noticed by Windows as I can connect the controllers to the dongle but they get absolute 0 response or contact with RPCS3.

Video of what happens with both Buzz USB dongles connected + log:

[RPCS3 with both Buzz USB dongles connected.log](https://github.com/RPCS3/rpcs3/files/7590918/RPCS3.with.both.Buzz.USB.dongles.connected.log)
https://user-images.githubusercontent.com/94709127/143107675-0d28ff72-b96f-4d83-8d41-8e0521e1b040.mp4

Video of what happens with only one Buzz USB dongle connected + log:

[RPCS3 with one Buzz USB dongle connected.log](https://github.com/RPCS3/rpcs3/files/7590922/RPCS3.with.one.Buzz.USB.dongle.connected.log)
https://user-images.githubusercontent.com/94709127/143107880-95f1b321-befb-4cdb-a4ae-2c9298395da1.mp4

**Comment by RipleyTom** [comment]
We don't support hotplug for usb atm.
Can I get a log with `Log: {sys_usbd: Trace}` (you need to set that as the last line of your game config)?

**Comment by MarcusRivet** [comment]
This should be it if I did it what you asked correctly

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7591110/RPCS3.log)

**Comment by RipleyTom** [comment]
Updated the PR, please test again ty :).
