### ISSUE TITLE
Sly 2 black screen bug

### ISSUE THREAD

**Issue by RookTheRH** [RPCS3/rpcs3#11175]
After a few seconds of gameplay, game turns black, you are able to go into the menus, but that's it.

**Comment by Asinin3** [comment]
Read the wiki, it tells you that the game needs llvm java mode enabled on advanced tab settings to fix the issue.
By the way, the setting was set to on by default months ago, so you probably have an old custom config for the game, it works fine with default settings.

**Comment by RookTheRH** [comment]
Oh I got that on, I was messing around with custom boot settings for sly 2
specifically after that and I fixed it, I though I start from the defaults
and run it slowly up to the 4k res I wanted to achieve, and when I compared
the previous settings and the custom ones only one thing stood out. In cpu,
in additional settings, I left "enable SPU loop detection" unmarked, turned
off, and that fixed it somehow.
