### ISSUE TITLE
my dualsense controller dosen't work with rpcs3

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [RPCS3/rpcs3#11180]
## Details
Please describe the problem as accurately as possible.
my dualsense controller dosen't work with the dualsense config in rpcs3. (using bluetooth)
evdev works, the controller works in steam, and other programs. 
the udev rules were configured correctly according to discord and the rpcs3 wiki
the controller works with root (games don't launch, so i can't use root)

#### 1. Please attach RPCS3's log.
log shows the same thing as the image
#### 3. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/45927311/142744804-9e5fabc5-7140-4c72-a0b5-52051c948686.png)

#### 5. Please provide your system configuration:
* OS arch linux 
* CPU ryzen 7 4700u 
* GPU integrated graphics
* Driver version mesa 21.30

**Comment by AniLeo** [comment]
Cannot reproduce

**Comment by Etaash-mathamsetty** [comment]
> Cannot reproduce

are you using arch linux?
It worked fine in ubuntu

**Comment by AniLeo** [comment]
Manjaro, arch-based

**Comment by Etaash-mathamsetty** [comment]
> Manjaro, arch-based

manjaro has some configurations out of the box
arch dosen't have them
I have to manually add/install those

**Comment by Megamouse** [comment]
There is zero information here without a log file.

**Comment by Etaash-mathamsetty** [comment]
> There is zero information here without a log file.

`
﻿RPCS3 v0.0.19-12971-46a54f54 Alpha | HEAD
AMD Ryzen 7 4700U with Radeon Graphics | 8 Threads | 15.01 GiB RAM | TSC: 1.996GHz | AVX+ | FMA3
Operating system: POSIX, Name: Linux, Release: 5.15.2-arch1-1, Version: #1 SMP PREEMPT Fri, 12 Nov 2021 19:22:10 +0000
Qt version: Compiled against Qt 5.15.2 | Run-time uses Qt 5.15.2
·! 0:00:00.000001 SIG: Thread time: 0.000000s (0.000000Gc); Faults: 0 [rsx:0, spu:0]; [soft:2 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.011707 SYS: Initialization times before main(): 0.047109s
·! 0:00:00.011782 SYS: argc: 1, argv: 'rpcs3'
·A 0:00:00.198718 {Vulkan Device Enumeration Thread} RSX: Found vulkan-compatible GPU: 'AMD RADV RENOIR' running on driver 21.3.0
·W 0:00:00.198780 {Vulkan Device Enumeration Thread} RSX: Unknown chip with device ID 0x1636
·! 0:00:00.199363 {Vulkan Device Enumeration Thread} SIG: Thread time: 0.029558s (0.000000Gc); Faults: 0 [rsx:0, spu:0]; [soft:2774 hard:12]; Switches:[vol:13 unvol:9]; Wait:[0.000s, spur:0]
·! 0:00:00.199393 CFG: Setting the default renderer to Vulkan. Default GPU: 'AMD RADV RENOIR')
·! 0:00:00.199435 SYS: Setting user ID '00000001'
·! 0:00:00.207190 VFS: VFS config missing. Using default settings. Path: /home/etaash/.config/rpcs3/vfs.yml
·! 0:00:00.207337 SYS: Using VFS config:
$(EmulatorDir): ""
/dev_hdd0/: $(EmulatorDir)dev_hdd0/
/dev_hdd1/: $(EmulatorDir)dev_hdd1/
/dev_flash/: $(EmulatorDir)dev_flash/
/dev_flash2/: $(EmulatorDir)dev_flash2/
/dev_flash3/: $(EmulatorDir)dev_flash3/
/dev_usb000/: $(EmulatorDir)dev_usb000/
/dev_bdvd/: ""
/app_home/: ""
·! 0:00:00.207351 VFS: Mounted path "/dev_hdd0" to "/home/etaash/.config/rpcs3/dev_hdd0/"
·! 0:00:00.207357 VFS: Mounted path "/dev_flash" to "/home/etaash/.config/rpcs3//dev_flash/"
·! 0:00:00.207362 VFS: Mounted path "/dev_flash2" to "/home/etaash/.config/rpcs3//dev_flash2/"
·! 0:00:00.207366 VFS: Mounted path "/dev_flash3" to "/home/etaash/.config/rpcs3//dev_flash3/"
·! 0:00:00.207371 VFS: Mounted path "/dev_usb" to "/home/etaash/.config/rpcs3/dev_usb000/"
·! 0:00:00.207375 VFS: Mounted path "/dev_usb000" to "/home/etaash/.config/rpcs3/dev_usb000/"
·! 0:00:00.207379 VFS: Mounted path "/app_home" to "//"
·! 0:00:00.207394 SYS: Applying global config: /home/etaash/.config/rpcs3//config.yml
·! 0:00:00.210502 SYS: Logged in as user '00000001' with the username 'User'
·A 0:00:00.210660 SYS: Firmware version: 4.88
·! 0:00:00.282344 GUI: Current language changed to English (en)
·! 0:00:00.286574 Compat: Database file not found: /home/etaash/.config/rpcs3/GuiConfigs/compat_database.dat
·! 0:00:03.836381 Input: Loading pad config (title_id='', profile='Default', strict=1)
·! 0:00:03.836426 Input: Loading pad profile: '/home/etaash/.config/rpcs3/input_configs/global/Default.yml'
·! 0:00:03.839688 Input: Loading pad config (title_id='', profile='Default', strict=1)
·! 0:00:03.839728 Input: Loading pad profile: '/home/etaash/.config/rpcs3/input_configs/global/Default.yml'
·! 0:00:04.595178 evdev: Axis info for Wireless Controller Touchpad: ABS_MT_TRACKING_ID (MT Track ID+) => minimum=0, maximum=65535, fuzz=0, resolution=0
·! 0:00:04.595190 evdev: Axis info for Wireless Controller Touchpad: ABS_MT_POSITION_Y (MT PosY+) => minimum=0, maximum=1079, fuzz=0, resolution=0
·! 0:00:04.595195 evdev: Axis info for Wireless Controller Touchpad: ABS_MT_POSITION_X (MT PosX+) => minimum=0, maximum=1919, fuzz=0, resolution=0
·! 0:00:04.595200 evdev: Axis info for Wireless Controller Touchpad: ABS_Y (LY+) => minimum=0, maximum=1079, fuzz=0, resolution=0
·! 0:00:04.595203 evdev: Axis info for Wireless Controller Touchpad: ABS_X (LX+) => minimum=0, maximum=1919, fuzz=0, resolution=0
·! 0:00:04.595206 evdev: Axis info for Wireless Controller Touchpad: ABS_MT_SLOT (Slot+) => minimum=0, maximum=1, fuzz=0, resolution=0
·! 0:00:04.670311 evdev: Axis info for Wireless Controller: ABS_RZ (RZ+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:04.670324 evdev: Axis info for Wireless Controller: ABS_HAT0Y (Hat0 Y+) => minimum=-1, maximum=1, fuzz=0, resolution=0
·! 0:00:04.670328 evdev: Axis info for Wireless Controller: ABS_RY (RY+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:04.670331 evdev: Axis info for Wireless Controller: ABS_HAT0X (Hat0 X+) => minimum=-1, maximum=1, fuzz=0, resolution=0
·! 0:00:04.670335 evdev: Axis info for Wireless Controller: ABS_RX (RX+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:04.670338 evdev: Axis info for Wireless Controller: ABS_Z (LZ+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:04.670341 evdev: Axis info for Wireless Controller: ABS_Y (LY+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:04.670345 evdev: Axis info for Wireless Controller: ABS_X (LX+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:04.832940 evdev: Axis info for Wacom HID 5215 Finger: ABS_MT_TRACKING_ID (MT Track ID+) => minimum=0, maximum=65535, fuzz=0, resolution=0
·! 0:00:04.832954 evdev: Axis info for Wacom HID 5215 Finger: ABS_MT_POSITION_Y (MT PosY+) => minimum=0, maximum=6960, fuzz=0, resolution=40
·! 0:00:04.832958 evdev: Axis info for Wacom HID 5215 Finger: ABS_MT_POSITION_X (MT PosX+) => minimum=0, maximum=12372, fuzz=0, resolution=40
·! 0:00:04.832963 evdev: Axis info for Wacom HID 5215 Finger: ABS_Y (LY+) => minimum=0, maximum=6960, fuzz=0, resolution=40
·! 0:00:04.832966 evdev: Axis info for Wacom HID 5215 Finger: ABS_X (LX+) => minimum=0, maximum=12372, fuzz=0, resolution=40
·! 0:00:04.832970 evdev: Axis info for Wacom HID 5215 Finger: ABS_MT_SLOT (Slot+) => minimum=0, maximum=9, fuzz=0, resolution=0
·! 0:00:05.032942 evdev: Axis info for Wacom HID 5215 Pen: ABS_Y (LY+) => minimum=0, maximum=17399, fuzz=4, resolution=100
·! 0:00:05.032956 evdev: Axis info for Wacom HID 5215 Pen: ABS_X (LX+) => minimum=0, maximum=30931, fuzz=4, resolution=100
·! 0:00:05.032961 evdev: Axis info for Wacom HID 5215 Pen: ABS_PRESSURE (Pressure+) => minimum=0, maximum=4095, fuzz=0, resolution=0
·! 0:00:05.032965 evdev: Axis info for Wacom HID 5215 Pen: ABS_TILT_X (Tilt X+) => minimum=-90, maximum=90, fuzz=0, resolution=57
·! 0:00:05.032968 evdev: Axis info for Wacom HID 5215 Pen: ABS_TILT_Y (Tilt Y+) => minimum=-90, maximum=90, fuzz=0, resolution=57
·! 0:00:05.032971 evdev: Axis info for Wacom HID 5215 Pen: ABS_MISC (Misc+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:05.246518 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_MT_TRACKING_ID (MT Track ID+) => minimum=0, maximum=65535, fuzz=0, resolution=0
·! 0:00:05.246532 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_MT_TOOL_TYPE (MT TType+) => minimum=0, maximum=2, fuzz=0, resolution=0
·! 0:00:05.246537 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_MT_POSITION_Y (MT PosY+) => minimum=0, maximum=2097, fuzz=0, resolution=32
·! 0:00:05.246540 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_MT_POSITION_X (MT PosX+) => minimum=0, maximum=3209, fuzz=0, resolution=32
·! 0:00:05.246545 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_Y (LY+) => minimum=0, maximum=2097, fuzz=0, resolution=32
·! 0:00:05.246548 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_X (LX+) => minimum=0, maximum=3209, fuzz=0, resolution=32
·! 0:00:05.246552 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_MT_SLOT (Slot+) => minimum=0, maximum=4, fuzz=0, resolution=0
·! 0:00:06.206481 evdev: Axis info for Wireless Controller Touchpad: ABS_MT_TRACKING_ID (MT Track ID+) => minimum=0, maximum=65535, fuzz=0, resolution=0
·! 0:00:06.206494 evdev: Axis info for Wireless Controller Touchpad: ABS_MT_POSITION_Y (MT PosY+) => minimum=0, maximum=1079, fuzz=0, resolution=0
·! 0:00:06.206498 evdev: Axis info for Wireless Controller Touchpad: ABS_MT_POSITION_X (MT PosX+) => minimum=0, maximum=1919, fuzz=0, resolution=0
·! 0:00:06.206502 evdev: Axis info for Wireless Controller Touchpad: ABS_Y (LY+) => minimum=0, maximum=1079, fuzz=0, resolution=0
·! 0:00:06.206506 evdev: Axis info for Wireless Controller Touchpad: ABS_X (LX+) => minimum=0, maximum=1919, fuzz=0, resolution=0
·! 0:00:06.206509 evdev: Axis info for Wireless Controller Touchpad: ABS_MT_SLOT (Slot+) => minimum=0, maximum=1, fuzz=0, resolution=0
·! 0:00:06.312928 evdev: Axis info for Wireless Controller: ABS_RZ (RZ+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:06.312942 evdev: Axis info for Wireless Controller: ABS_HAT0Y (Hat0 Y+) => minimum=-1, maximum=1, fuzz=0, resolution=0
·! 0:00:06.312945 evdev: Axis info for Wireless Controller: ABS_RY (RY+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:06.312949 evdev: Axis info for Wireless Controller: ABS_HAT0X (Hat0 X+) => minimum=-1, maximum=1, fuzz=0, resolution=0
·! 0:00:06.312952 evdev: Axis info for Wireless Controller: ABS_RX (RX+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:06.312955 evdev: Axis info for Wireless Controller: ABS_Z (LZ+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:06.312958 evdev: Axis info for Wireless Controller: ABS_Y (LY+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:06.312962 evdev: Axis info for Wireless Controller: ABS_X (LX+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:06.419587 evdev: Axis info for Wacom HID 5215 Finger: ABS_MT_TRACKING_ID (MT Track ID+) => minimum=0, maximum=65535, fuzz=0, resolution=0
·! 0:00:06.419601 evdev: Axis info for Wacom HID 5215 Finger: ABS_MT_POSITION_Y (MT PosY+) => minimum=0, maximum=6960, fuzz=0, resolution=40
·! 0:00:06.419605 evdev: Axis info for Wacom HID 5215 Finger: ABS_MT_POSITION_X (MT PosX+) => minimum=0, maximum=12372, fuzz=0, resolution=40
·! 0:00:06.419610 evdev: Axis info for Wacom HID 5215 Finger: ABS_Y (LY+) => minimum=0, maximum=6960, fuzz=0, resolution=40
·! 0:00:06.419613 evdev: Axis info for Wacom HID 5215 Finger: ABS_X (LX+) => minimum=0, maximum=12372, fuzz=0, resolution=40
·! 0:00:06.419617 evdev: Axis info for Wacom HID 5215 Finger: ABS_MT_SLOT (Slot+) => minimum=0, maximum=9, fuzz=0, resolution=0
·! 0:00:06.582935 evdev: Axis info for Wacom HID 5215 Pen: ABS_Y (LY+) => minimum=0, maximum=17399, fuzz=4, resolution=100
·! 0:00:06.582950 evdev: Axis info for Wacom HID 5215 Pen: ABS_X (LX+) => minimum=0, maximum=30931, fuzz=4, resolution=100
·! 0:00:06.582955 evdev: Axis info for Wacom HID 5215 Pen: ABS_PRESSURE (Pressure+) => minimum=0, maximum=4095, fuzz=0, resolution=0
·! 0:00:06.582958 evdev: Axis info for Wacom HID 5215 Pen: ABS_TILT_X (Tilt X+) => minimum=-90, maximum=90, fuzz=0, resolution=57
·! 0:00:06.582962 evdev: Axis info for Wacom HID 5215 Pen: ABS_TILT_Y (Tilt Y+) => minimum=-90, maximum=90, fuzz=0, resolution=57
·! 0:00:06.582965 evdev: Axis info for Wacom HID 5215 Pen: ABS_MISC (Misc+) => minimum=0, maximum=255, fuzz=0, resolution=0
·! 0:00:06.819685 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_MT_TRACKING_ID (MT Track ID+) => minimum=0, maximum=65535, fuzz=0, resolution=0
·! 0:00:06.819698 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_MT_TOOL_TYPE (MT TType+) => minimum=0, maximum=2, fuzz=0, resolution=0
·! 0:00:06.819703 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_MT_POSITION_Y (MT PosY+) => minimum=0, maximum=2097, fuzz=0, resolution=32
·! 0:00:06.819706 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_MT_POSITION_X (MT PosX+) => minimum=0, maximum=3209, fuzz=0, resolution=32
·! 0:00:06.819711 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_Y (LY+) => minimum=0, maximum=2097, fuzz=0, resolution=32
·! 0:00:06.819715 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_X (LX+) => minimum=0, maximum=3209, fuzz=0, resolution=32
·! 0:00:06.819717 evdev: Axis info for MSFT0001:00 04F3:3140 Touchpad: ABS_MT_SLOT (Slot+) => minimum=0, maximum=4, fuzz=0, resolution=0
·E 0:00:09.460990 HID: DualSense hid_open_path failed! Reason: 000000000adef0a0
·E 0:00:09.461019 HID: One or more DualSense pads were detected but couldn't be interacted with directly
·E 0:00:09.461023 HID: Check https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration for intructions on how to solve this issue
·! 0:00:11.309207 Input: Saving pad profile config to '/home/etaash/.config/rpcs3/input_configs//active_profiles.yml'
·! 0:00:11.316033 Input: Saving pad config profile 'Default' to '/home/etaash/.config/rpcs3/input_configs/global/Default.yml'
`

**Comment by Etaash-mathamsetty** [comment]
I am just going to use evdev for now while this gets sorted

**Comment by RainbowCookie32** [comment]
Would be cleaner and easier to read if you post the file instead of copying it to the comment (which also turned it into one massive line).

**Comment by Megamouse** [comment]
You clearly have some fucked up permissions in your system if it only works with root access.

**Comment by MSuih** [comment]
> the udev rules were configured correctly according to discord and the rpcs3 wiki
> the controller works with root (games don't launch, so i can't use root)

Did you change the vendor and product id's to match Dualsense? Wiki only lists the ones for dualshock 3 and 4, you'll have to look up which id's your own controller uses

**Comment by Etaash-mathamsetty** [comment]
> You clearly have some fucked up permissions in your system if it only works with root access.
how to fix:
sudo pacman -S steam 
I wonder what steam has to do with a dualsense controller

**Comment by qurious-pixel** [comment]
I had custom udev rules at `/etc/udev/rules.d` and it worked everywhere except RPCS3 (only as evdev).
When I added to the steam-input rules at  `/lib/udev/rules.d` it worked.


```
# PS5 DualSense controller over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="0ce6", MODE="0660", TAG+="uaccess"

# PS5 DualSense controller over bluetooth hidraw
KERNEL=="hidraw*", KERNELS=="*054C:0CE6*", MODE="0660", TAG+="uaccess"
```
