### ISSUE TITLE
UI Stylesheets options are gone

### ISSUE THREAD

**Issue by AlfredoRodda** [RPCS3/rpcs3#11195]
## Quick summary
The UI Stylesheets options are gone. The only theme available is Default (Bright).

## Details
1. Open RPCS3.
2. Press Configuration in the tool bar, then GUI in the drop down box.
3. In the UI Stylesheet section, try to change to something other then the Default (Bright).
4. The only option is Default (Bright).

#### Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
Regression build - RPCS3 Version: 0.0.19-13040-59f253ba Alpha
Commit - #11189

#### Please attach TWO logs:
* One for the build with regression.
 [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7596859/RPCS3.log)
* One for the build that works as expected.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7596861/RPCS3.log)
 
#### Please attach screenshots of your problem.
Before
![workingrpcs3](https://user-images.githubusercontent.com/92961316/143266436-f5bc005f-e599-441d-b874-77dd690eea14.png)

After
![brokenrpcs3](https://user-images.githubusercontent.com/92961316/143266502-b3ee8a89-e1c9-4427-b989-4cbdb05e7d06.png)

#### Please provide your system configuration:
* OS - Linux
* CPU - AMD Ryzen 7 1700
* GPU - AMD RX 580
* Driver version - Mesa 21.2.5

**Comment by MSuih** [comment]
A fix is being attempted with #11194, it would be nice if someone could test it

**Comment by AlfredoRodda** [comment]
I just tested an artifact for that build (RPCS3 Version: 0.0.19-13044-4ff040a6 Alpha) and themes can be selected again. I did not test anything else other than seeing if themes could be selected and applied.
