### ISSUE TITLE
Logitech G27 and T500 RS Gear Shift Won't Work w/ Daytona USA

### ISSUE THREAD

**Issue by hellshakeyan0** [RPCS3/rpcs3#11198]
## Quick summary
Neither of the aforementioned devices work with RPCS3 after installing WinUSB drivers. RPCS3 reads them, but no input works once game is launched. Have tried the devices independent of each other with no change in results.

## Details

Please describe the problem as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
Log Attached

#### 3. Please attach screenshots of your problem.
N/A, as car does nothing immediately after start

#### 5. Please provide your system configuration:
Windows 10 2004
AMD Ryzen 5 3600 | 12 Threads | 15.95 GiB RAM | TSC: 4.200GHz | AVX+ | FMA3
GPU: NVIDIA GeForce GTX 1660 SUPER (496.49)

#### Please include.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7598240/RPCS3.log)
![image](https://user-images.githubusercontent.com/83040254/143300946-cacede39-e841-4ac2-8f29-1ca90dda61a2.png)
![image](https://user-images.githubusercontent.com/83040254/143300955-8798c301-6697-4070-8e1d-1c0b64dc0681.png)

**Comment by RipleyTom** [comment]
Can you try with latest master again?
And if that doesn't work can you upload a log with
```
Log:{sys_usbd: Trace}
```
as the last line of your config.

**Comment by RipleyTom** [comment]
Stale issue, it's been tested more recently as working( https://github.com/RPCS3/rpcs3/issues/14969 ).
