### ISSUE TITLE
DJ Hero 2 hangs when loading a song if using an emulated turntable, stuttery audio if using a real turntable

### ISSUE THREAD

**Issue by shockdude** [RPCS3/rpcs3#11201]
## Quick summary
On RPCS3 0.0.19-13052 (#11193) and newer, DJH2 hangs when loading songs when using an emulated turntable.
With only 1 real turntable connected, DJH2 loads the song and goes ingame, but hitches (drops to 0FPS for a few seconds) while loading, and ingame has more laggy/stuttery audio vs. the previous build.

## Details
To enable an emulated table, you have to make a custom config and, in the I/O tab, enable 1 emulated turntable.
For the emulated table's Pad 1 binds to work properly, you have to set Pad 1's device class to DJ, or any device class where the game doesn't detect a regular pad like a Rock Revolution Drum. Otherwise, the game intercepts the pad's controls before the emulated turntable's, and you can't go ingame.
Go ingame and load any song from QuickPlay

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
RPCS3 0.0.19-13052 (#11193)

#### 2. Please attach TWO logs:
Logs with `Log: {sys_usbd: Trace}` set

**RPCS3 0.0.19-13051**
Real Turntable: [RPCS3_13051_realtable.log.gz](https://github.com/RPCS3/rpcs3/files/7607042/RPCS3_13051_realtable.log.gz)
Emulated Turntable (pad device class DJ): [RPCS3_13051_emulatedtable_deviceclassDJ.log.gz](https://github.com/RPCS3/rpcs3/files/7607043/RPCS3_13051_emulatedtable_deviceclassDJ.log.gz)
Emulated Turntable (pad device class Rock Revolution Drum): [RPCS3_13051_emulatedtable_deviceclassRRD.log.gz](https://github.com/RPCS3/rpcs3/files/7607045/RPCS3_13051_emulatedtable_deviceclassRRD.log.gz)

**RPCS3 0.0.19-13052**
Real Turntable: [RPCS3_13052_realtable.log.gz](https://github.com/RPCS3/rpcs3/files/7607047/RPCS3_13052_realtable.log.gz)
Emulated Turntable (pad device class DJ): [RPCS3_13052_emulatedtable_deviceclassDJ.log.gz](https://github.com/RPCS3/rpcs3/files/7607048/RPCS3_13052_emulatedtable_deviceclassDJ.log.gz)
Emulated Turntable (pad device class Rock Revolution Drum): [RPCS3_13052_emulatedtable_deviceclassRRD.log.gz](https://github.com/RPCS3/rpcs3/files/7607049/RPCS3_13052_emulatedtable_deviceclassRRD.log.gz)

#### 4. Please attach screenshots of your problem.
Game hangs here when using an emulated table:
![image](https://user-images.githubusercontent.com/27760396/143540183-9614b199-2ad6-4b66-99ed-68cacdc32e54.png)

#### 5. Please provide comparison with real PS3.
N/A since this deals with emulated tables.
On a real PS3, multiple real turntables should work fine.

#### 6. Please provide your system configuration:
* OS: Windows 10 21H2
* CPU: Intel i7-4720HQ
* GPU: Nvidia GTX860M
* Driver version: 472.12

**Comment by MSuih** [comment]
Crafty mentioned that this might only happen when DISC0.IMG is extracted (which is required when adding custom songs). Also I think he mentioned that it continues after the hang if you just let it load things for like 5 minutes.

**Comment by shockdude** [comment]
This issue was produced on an unmodded DJH2 dump, with intact DISC0.IMG.
5 minutes is a pretty long load time I think. But I can check that later.

**Comment by MSuih** [comment]
He might've gotten confused with the emulated vs real thing then

**Comment by RipleyTom** [comment]
Please test https://github.com/RPCS3/rpcs3/pull/11202.

**Comment by shockdude** [comment]
Thanks for looking into this!

I think the loading screen hang and stutters are fixed.
[RPCS3_PR11202_emulatedtabledj_fixedhang.log.gz](https://github.com/RPCS3/rpcs3/files/7610453/RPCS3_PR11202_emulatedtabledj_fixedhang.log.gz)

However, tabbing out of RPCS3 (or clicking outside the window, etc) sometimes causes inputs to no longer be detected by the game after tabbing back in.
[RPCS3_PR11202_emulatedtabledj_taboutnoinput.log.gz](https://github.com/RPCS3/rpcs3/files/7610456/RPCS3_PR11202_emulatedtabledj_taboutnoinput.log.gz)
[RPCS3_13051_emulatedtabledj_taboutinput.gz](https://github.com/RPCS3/rpcs3/files/7610459/RPCS3_13051_emulatedtabledj_taboutinput.gz)

**Comment by RipleyTom** [comment]
I very much doubt the issue you describe has anything to do with my PR.

**Comment by shockdude** [comment]
I can't pinpoint for sure because of the nature of it being random, but I have never had emulated table inputs stop being detected in previous stable builds, or heard about it from other players, after tabbing out & back in.
Meanwhile I can semi-consistently cause table inputs to stop being detected in the PR build by tabbing out & back in.

I somehow got inputs to stop being detected without tabbing out at all, currently trying to reproduce.
[RPCS3_PR11202_emulatedtabledj_notaboutnoinput.log.gz](https://github.com/RPCS3/rpcs3/files/7610513/RPCS3_PR11202_emulatedtabledj_notaboutnoinput.log.gz)

**Comment by RipleyTom** [comment]
I added a commit to the PR for some extra logging.

**Comment by shockdude** [comment]
Using extra logging build

No inputs after a few tabouts:
[RPCS3_PR11202_2_emulatedtabledj_taboutnoinput.log.gz](https://github.com/RPCS3/rpcs3/files/7610601/RPCS3_PR11202_2_emulatedtabledj_taboutnoinput.log.gz)

Fluke where inputs stopped responding after a successful input, without a tabout in between:
[RPCS3_PR11202_2_emulatedtabledj_inputthennoinput.log.gz](https://github.com/RPCS3/rpcs3/files/7610602/RPCS3_PR11202_2_emulatedtabledj_inputthennoinput.log.gz)

**Comment by RipleyTom** [comment]
Alright it was my fault(it had nothing to do with alt tabbing though :D).
Pushed fix.

**Comment by shockdude** [comment]
New build seems to behave correctly!
