### ISSUE TITLE
Broken Screen artifacts - Journey [NPEA00288] 

### ISSUE THREAD

**Issue by Zorklis** [RPCS3/rpcs3#11207]
## Details
Journey is the only game that these broken screen artifacts keep appearing.
Video that can better describe my problem
![vlcsnap-2021-11-27-21h52m06s523](https://user-images.githubusercontent.com/85455465/143720847-dcdf044f-7e1f-48e4-9040-bce15ad5902d.png)
https://www.youtube.com/watch?v=cwflhKyJzkU

**Comment by illusion0001** [comment]
Artifacts of MLAA at low framerate

**Comment by Yahfz** [comment]
The game will artifact when failing to hit the game's target framerate which is 30fps. You can fix this by changing the game's target framerate by lowering the vblank frequency until it matches a framerate that your CPU can achieve.
