### ISSUE TITLE
[Regression] Multiple games not opening after #11103

### ISSUE THREAD

**Issue by YuriNator557** [RPCS3/rpcs3#11216]
## Quick summary
As per title, the XMB/VSH fails to boot after #11103 was merged.
{RSX [0x0012a94]} SIG: Thread terminated due to fatal error: Invalid aspect ratio 0
(in file D:\a\1\s\rpcs3\Emu\RSX\rsx_utils.cpp:174[:32], in function get_aspect_ratio) (e=0x0000007e[126])

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
v0.0.19-13068-9bb46aa9 (#11103)

#### 2. Please attach TWO logs:
[notworking.log](https://github.com/RPCS3/rpcs3/files/7637872/notworking.log)
[working.log](https://github.com/RPCS3/rpcs3/files/7637871/working.log)

#### 5. Please provide comparison with real PS3.
Emulator bug, XMB works fine

#### 6. Please provide your system configuration:
* OS: Windows 10 21H2
* CPU: Ryzen 7 5800x
* GPU: RTX 2070 Super
* Driver version: 472.12

**Comment by YuriNator557** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7638071/RPCS3.log)
God of War 3 also affected

**Comment by Asinin3** [comment]
RPCS3's native UI screen where it shows modules compiling or loading from cache is also no-longer working, the screen just stays black until its finished.

I tested and can confirm these games are working: Red Dead Redemption, Skate 3, Killzone 3, Persona 5, Dante's Inferno, R&C, R&C A Crack in Time, Tomb Raider, Sly Cooper: Thieves in Time, Drakengard 3, Kingdom Hearts 1 HD, God of War 1
