### ISSUE TITLE
[Regression] Overlay progress dialog not shown during initial compilation

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#11218]
Apparently the culprit:
https://github.com/RPCS3/rpcs3/pull/11103/commits/1bb57549b504d0a7fbe5f3e9911fccf705bda736

**Comment by kd-11** [comment]
It's caused by zero-initializing the display stuff. Very odd.

**Comment by kd-11** [comment]
Check with https://github.com/RPCS3/rpcs3/pull/11219
