### ISSUE TITLE
[Feature Request] Launch screen refresh

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#11225]
This would replace the existing launch screen data with a simple progress dashboard that aims to:

* Be easier to see
* Be more informative to the user
* Preserve continuity through the preparation process
* Refresh the look with one that is a bit more graphical

Here is a mock-up of what I have in mind (the background is shown in grey to be sure it renders properly in browser/github dark modes):
![rpcs3_dash](https://user-images.githubusercontent.com/12475371/144693845-8f8d969e-8c31-4f17-93b0-66015aabc622.png)
As overlaid on a game load screen:
![RPCS3](https://user-images.githubusercontent.com/12475371/144693719-84eff1b6-1a3c-4055-a810-ac811da4d7f3.png)
Optionally, for the sake of simplification, the details line ("Building SPU Cache" etc.) could be either removed or moved to the window title bar.

**Comment by Darkhost1999** [comment]
You can change the background image of such loading screens with a right click of game -> custom images -> import custom shader loading background.
If such a feature is enabled then I believe the background should be transparent so as to maintain and keep the custom image option.
I feel like showing the user all the progress bubbles is a good idea as it will help as said communicate transparency of what the emulator is doing while you wait for the game to boot. Even if the game doesn't take too long to boot.

**Comment by Shoegzer** [comment]
Thanks for your thoughts.  I think a black-translucent (vs. transparent) background as I suggested should still work with custom images while framing the data and making it easier to see in cases of bright images.  Wouldn't you agree?

And agreed that progress bubbles would be nice for a variety of reasons, they were actually what got me started thinking about this.

**Comment by Asinin3** [comment]
This will give people the misunderstanding that they are nearly about to boot the game when at final steps even though they are far from it + I don't like how it looks, most of the comments I have seen about this have similar thoughts. The issue tracker is bloated enough as it is with feature requests that we won't implement. Going to close.

**Comment by Shoegzer** [comment]
It just shows general progress in the process, percentage and progress bar could be removed.  Anyway it's too bad you don't like the look, but again this was intended as notional to be picked apart to generate ideas for something different.  At least I think the current startup UI could benefit from a translucent background and rendering all progress bars on the screen at once.  Hopefully something simple wouldn't take too many cycles to implement but if the issue tracker is too bloated atm then that's fine.  Other priorities are what they are.
