### ISSUE TITLE
RPCS3 starts game, but nothing pops up.

### ISSUE THREAD

**Issue by Mr-Build3r** [RPCS3/rpcs3#11237]
## Quick summary
Hi I have recently tried setting up RPCS3 on my Ubuntu computer, but I cannot seem to get any games running, with a bunch of errors for missing files. It says the game is running, but no other window show up.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7663597/RPCS3.log)

![Screenshot from 2021-12-06 16-13-41](https://user-images.githubusercontent.com/95645049/144924076-f50ed8ac-bcfb-48a2-84c1-e462525a56a1.png)
![Screenshot from 2021-12-06 16-13-46](https://user-images.githubusercontent.com/95645049/144924077-721c954c-c696-489d-9f91-20c4b9d08298.png)

#### 5. Please provide your system configuration:
Ubuntu 21.10
Intel i7-9750H
Intel UHD 630 (driver 21.0.3)
GTX 1660 Ti (driver 470.86.0.0)

I have tried both graphic cards and reinstalling.

**Comment by RainbowCookie32** [comment]
USB manager thread seems to be dying
```
·F 0:00:10.272748 {Usb Manager Thread} SIG: Thread terminated due to fatal error: Segfault reading location 00000000000000e8 at 00007f77d06e0fc4.
Emu Thread Name: 'Usb Manager Thread'.

·F 0:00:10.272774 {Usb Manager Thread} profiler: cpu_thread::flush_profilers() has been called incorrectly.
```

Might be worth mentioning that OP seems to be running RPCS3 as a Snap, not sure if it could interfere with anything.

**Comment by Mr-Build3r** [comment]
> USB manager thread seems to be dying
> ```
> ·F 0:00:10.272748 {Usb Manager Thread} SIG: Thread terminated due to fatal error: Segfault reading location 00000000000000e8 at 00007f77d06e0fc4.
> Emu Thread Name: 'Usb Manager Thread'.
> 
> ·F 0:00:10.272774 {Usb Manager Thread} profiler: cpu_thread::flush_profilers() has been called incorrectly.
> ```
> 
> Might be worth mentioning that OP seems to be running RPCS3 as a Snap, not sure if it could interfere with anything.

Is there another way of running it instead of snap? I'll try it other ways too and see if the problem persists.

**Comment by RainbowCookie32** [comment]
We provide appimages on our website

**Comment by Mr-Build3r** [comment]
I followed the website guide, and that solved my issue. Thank you!
