### ISSUE TITLE
Pc crashes

### ISSUE THREAD

**Issue by Kejse** [RPCS3/rpcs3#11234]
So i'm having this problem that when i launch a game on the emulator the whole pc just turns off more precisely it crashes a bit after it starts compiling the ppu modules is this a problem with a fix?

my specs are
CPU= i7-2600 3.40Ghz
GPU= GT 730 4g
OS=Windows 10 professional edition
Ram= 16gb

the logs are
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7660442/RPCS3.log)

**Comment by clienthax** [comment]
Sounds like a hardware issue with your PC.
Have you checked that your system isn't overheating / unstable overclock?

**Comment by Kejse** [comment]
> 

i just noticed that even if the app is open it uses 100% of my gpu F guess i won't play jojo eyes of heaven
