### ISSUE TITLE
PS3 Hardware Documentation

### ISSUE THREAD

**Issue by ADormant** [RPCS3/rpcs3#1123]
I know it wouldn't be a trivial amount of work but could you consider writing a PS3 hardware documentation like the ones available for the PS1, GBA and DS?  I know rpcs3 wiki has some links to pdfs but something more exhaustive could be very helpful for contributors and also for hardware preservation.
 I am talking about something like this
https://github.com/simias/psx-guide/blob/master/guide.tex
https://svkt.org/~simias/guide.pdf
http://problemkaputt.de/psx-spx.htm
http://problemkaputt.de/gbatek.htm

**Comment by vgturtle127** [comment]
Have you tried PlayStation Developer Wiki?

http://www.ps3devwiki.com/ps3

**Comment by takhlaq** [comment]
url in above comment has typo (or the site's changed since)

assuming intended to link:
http://www.psdevwiki.com/ps3/Main_Page

**Comment by vgturtle127** [comment]
@tambry Do you think we should just close this?

@takhlaq Updated link, thanks.

**Comment by raven02** [comment]
Probably the documentation can be put on rpcs3.net if necessary .I'm closing this for this moment.
