### ISSUE TITLE
PPU LLVM Regression after #9760

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#11230]
A few games and Mandelbrot doesn't work after #9760.
I narrowed it down to some select architectures not working. When targetting LLVM to compile for Haswell, Skylake and Tigerlake it works fine. 
When compiling PPU LLVM modules for Rocket Lake and Icelake in mandelbrot RPCS3 closes itself.
(PPU Interpreter precise and fast works fine with every architecture, so only PPU LLVM is affected).
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7656767/RPCS3.log)

**Comment by Whatcookie** [comment]
Can't reproduce on my tigerlake laptop, or on my skylake desktop running under the intel sde, running on linux.

**Comment by Yahfz** [comment]
Just tested Linux and its unaffected by this. Its windows side only.

**Comment by Yahfz** [comment]
Tested with #11239 . Not fixed still. 
#11239 log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7669976/RPCS3.log)
