### ISSUE TITLE
Gran turismo 5 regression

### ISSUE THREAD

**Issue by coolllman** [RPCS3/rpcs3#11246]
0.0.19-13084 regression
Gran turismo 5 black screen on start video, disapear cars texture

**Comment by coolllman** [comment]
#11231

**Comment by coolllman** [comment]
![Untitled](https://user-images.githubusercontent.com/17841647/145563785-1757028d-f482-4db7-94c6-5527a0e9ffaf.png)

**Comment by YuriNator557** [comment]
Considering the cited PR, does it do this on SPU ASMJIT?

**Comment by Megamouse** [comment]
Upload log file

**Comment by coolllman** [comment]
Yes, ASMJIT fix all problems, but fps low

**Comment by coolllman** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7693329/RPCS3.log)
