### ISSUE TITLE
rpcs3 window not showing up

### ISSUE THREAD

**Issue by SetStream-wasdwasd** [RPCS3/rpcs3#11248]
When i click rpcs3.exe the window is not showing up but rpcs3 runs in task manager using 0 cpu. And in the log are my pc specs.
Before I reinstalled windows rpcs3 worked correctly.

**Comment by RainbowCookie32** [comment]
This isn't the place to ask for support, use [our Discord server](https://discord.me/RPCS3) for that.

**Comment by SetStream-wasdwasd** [comment]
Ok sry
