### ISSUE TITLE
Buzz Quiz World freezes with wired buzz controllers

### ISSUE THREAD

**Issue by Dais05** [RPCS3/rpcs3#11241]
After about 1 minute game freezes, when I quit game RPCS3 crashes and I get this error (Thread ID is different each time):

![image](https://user-images.githubusercontent.com/68423336/145097997-81472074-3f50-4bc4-86df-84378c6974e0.png)

This only happens with buzz controllers connected, when I unplug buzz controllers and try to run game with dualshock 4 or another gamepad, game doesn't freeze and works perfectly fine. 

It seems to be same problem that has already been reported here:
https://forums.rpcs3.net/thread-201712.html
https://forums.rpcs3.net/thread-196046.html
https://forums.rpcs3.net/archive/index.php/thread-179917.html

#### 1. Please attach RPCS3's log.
https://mega.nz/file/8hcFFawB#UNPCoJTITSUDEvQNSc1t286BZRv1iUuI3Y_vyL6DWs8

#### 3. Please attach screenshots of your problem.
moment when game freezes:
![image](https://user-images.githubusercontent.com/68423336/145097766-7248429f-3b0d-49ee-8cdb-72e3c7251689.png)

#### 5. Please provide your system configuration:
* OS: Windows 10 Pro 64bit (10.0, build 19042)
* CPU: AMD Ryzen 5 5600x
* GPU: NVIDIA GeForce RTX 3070

**Comment by MarcusRivet** [comment]
https://github.com/RPCS3/rpcs3/issues/11182 Do you have this issue as well?

**Comment by MarcusRivet** [comment]
Oh btw. To fix your issue, try this:

You need to make your device use WinUSB drivers. For this you can use a software called Zadig which I will provide in the steps below.

1: Plug your Buzz controllers into your PC.
2: Install Zadig on your Computer (https://github.com/pbatard/libwdi/releases/download/v1.4.1/zadig-2.7.exe).
3: Open Zadig, select 'Options', then select 'List all devices', then in the scroll window you will now see a lot of devices, here you need to find which device is your Buzz controllers, most likely it is a device called 'Wbuzz'. once you've find the correct device and selected it, you need to scroll up/down in the window to the right until it shows 'WinUSB' and click 'Replace driver'. Then it may give you a warning but just hit 'Yes' or 'Ok' on it to proceed with the install. Let it install the driver then now you can try to reopen RPCS3 and launch Buzz and try playing buzz quiz world.

Let me know if it worked for you.

**Comment by Dais05** [comment]
> 

yes I have same graphic glitches. but with your fix using Zadig works :) finally we can play without freezes or crashes! Thank you.

**Comment by MarcusRivet** [comment]
Glad it fixed the issue for you ! :D

**Comment by MarcusRivet** [comment]
Btw since you have the same graphical bug, can you comment under here saying that you have the same issue? https://github.com/RPCS3/rpcs3/issues/11182 It will help the cause hopefully reaching a staff's attention to fix the issue :)

**Comment by norko1232** [comment]
> After about 1 minute game freezes, when I quit game RPCS3 crashes and I get this error (Thread ID is different each time):
> 
> ![image](https://user-images.githubusercontent.com/68423336/145097997-81472074-3f50-4bc4-86df-84378c6974e0.png)
> 
> This only happens with buzz controllers connected, when I unplug buzz controllers and try to run game with dualshock 4 or another gamepad, game doesn't freeze and works perfectly fine.
> 
> It seems to be same problem that has already been reported here: https://forums.rpcs3.net/thread-201712.html https://forums.rpcs3.net/thread-196046.html https://forums.rpcs3.net/archive/index.php/thread-179917.html
> 
> #### 1. Please attach RPCS3's log.
> https://mega.nz/file/8hcFFawB#UNPCoJTITSUDEvQNSc1t286BZRv1iUuI3Y_vyL6DWs8
> 
> #### 3. Please attach screenshots of your problem.
> moment when game freezes: ![image](https://user-images.githubusercontent.com/68423336/145097766-7248429f-3b0d-49ee-8cdb-72e3c7251689.png)
> 
> #### 5. Please provide your system configuration:
> * OS: Windows 10 Pro 64bit (10.0, build 19042)
> * CPU: AMD Ryzen 5 5600x
> * GPU: NVIDIA GeForce RTX 3070

Could you please tell me how you changed the language to czech? That woulf be very helpful!
