### ISSUE TITLE
Uncharted: Drake's Fortune [BCES00065]

### ISSUE THREAD

**Issue by BurAndBY** [RPCS3/rpcs3#11255]
## Quick summary
Please briefly describe what is not working correctly.
After some time game freezes after some inconsistent time in Chapter 2 
## Details
After some time game freezes after some inconsistent time in Chapter 2 and when trying to close gives this error:
![image](https://user-images.githubusercontent.com/48630651/145719259-a39f5a5f-9725-4503-836c-dbe52acf458d.png)

#### 5. Please provide your system configuration:
* OS: Windows 10 20H1
* CPU: AMD Ryzen 5 2600
* GPU: NVIDIA Geforce GTX 1650

**Comment by BurAndBY** [comment]
Forgot to attach logs
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7699061/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7699062/RPCS3.log.gz)

**Comment by YuriNator557** [comment]
## Please do not ask for help or report compatibility regressions here, use [RPCS3 Discord server](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/) instead.
