### ISSUE TITLE
Weird Graphical Gitches on The Fancy Pants Adventures™

### ISSUE THREAD

**Issue by Fancy2209** [RPCS3/rpcs3#11253]
## Quick summary
Please briefly describe what is not working correctly.
On the game The Fancy Pants Adventures™ [NPUB30343] there are some textures who are missing or have some noise

#### 1. Please attach RPCS3's log.[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7697440/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7697442/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
I tried to get the renderdoc capture but it was too confusing
Heres the RSX
[RSX.zip](https://github.com/RPCS3/rpcs3/files/7697500/RSX.zip)

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.
![Captura de ecrã de 2021-12-11 17-00-36](https://user-images.githubusercontent.com/64917206/145686898-25be6fd6-e668-4efc-9c13-380e197ba5c1.png)
![Captura de ecrã de 2021-12-11 17-00-22](https://user-images.githubusercontent.com/64917206/145686905-aa077f27-51ce-4220-86a2-f1a644e7d186.png)
![Captura de ecrã de 2021-12-11 16-59-49](https://user-images.githubusercontent.com/64917206/145686908-2846ea3a-f3db-4747-890a-c9e25bba7f33.png)
![Captura de ecrã de 2021-12-11 16-59-40](https://user-images.githubusercontent.com/64917206/145686909-bf881096-9941-4378-8237-761656e300a8.png)
![Captura de ecrã de 2021-12-11 16-59-34](https://user-images.githubusercontent.com/64917206/145686911-4cb46258-8f20-43bb-975e-007275803c90.png)

#### 4. Please provide comparison with real PS3.
https://www.youtube.com/watch?v=XEEjMk20ims

#### 5. Please provide your system configuration:
OS: Pop!_OS 21.04 x86_64 
Kernel: 5.15.5-76051505-generic 
Resolution: 1366x768 
CPU: Intel i3-2330M (4) @ 2.200GHz 
GPU: AMD ATI Radeon HD 6400M/7400M Series 
Memory: 1552MiB / 3872MiB 

#### Please include.
* Anything else you deem to be important
It seems that on NVIDIA GPUs this bug doesn't happen as I asked someone else with the demo on RPCS3 and they had none of these weird graphical glitches
Ignore the fact it thinks I'm using my iGPU, i'm using my dedicated AMD dGPU.

**Comment by AniLeo** [comment]
·! 0:08:37.938272 {RSX [0x0000000]} RSX: GL RENDERER: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2) (Intel Open Source Technology Center)
·! 0:08:37.938314 {RSX [0x0000000]} RSX: GL VERSION: 4.4 (Core Profile) Mesa 21.2.2
·! 0:08:37.938317 {RSX [0x0000000]} RSX: GLSL VERSION: 4.40

i965 driver is [not supported](https://github.com/RPCS3/rpcs3/wiki/Graphics-Driver-Issues#intel-mesa) and has been removed from mainline mesa on 22.0. Use your dGPU or wait for next mesa stable with the crocus driver.

**Comment by nitroos-ai** [comment]
According to https://www.phoronix.com/scan.php?page=news_item&px=Intel-Crocus-Default-Gallium3D if you have Mesa 21.3 installed you could try crocus with _MESA_LOADER_DRIVER_OVERRIDE=crocus ./rpcs3_.

**Comment by Fancy2209** [comment]
> ·! 0:08:37.938272 {RSX [0x0000000]} RSX: GL RENDERER: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2) (Intel Open Source Technology Center) ·! 0:08:37.938314 {RSX [0x0000000]} RSX: GL VERSION: 4.4 (Core Profile) Mesa 21.2.2 ·! 0:08:37.938317 {RSX [0x0000000]} RSX: GLSL VERSION: 4.40
> 
> i965 driver is [not supported](https://github.com/RPCS3/rpcs3/wiki/Graphics-Driver-Issues#intel-mesa) and has been removed from mainline mesa on 22.0. Use your dGPU or wait for next mesa stable with the crocus driver.

I don't know why I posted the wrong GPU
I use my dgpu, who is a Radeon HD 6470M
atleast I should since I use DRI_PRIME=1 when runnung the game

**Comment by Fancy2209** [comment]
Also very weirdly, if I add `MESA_LOADER_DRIVER_OVERRIDE=r600` it says `do_winsys_init: DRM version is 1.6.0 but this driver is only compatible with 2.12.0 (kernel 3.2) or later.`
