### ISSUE TITLE
Tales of Graces f missing X button texture in menu with OpenGl

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#11260]
The X button icon/texture is missing on OpenGl in Tales of Graces f.
I can recreate it 100% in the attached RSX capture

OpenGl:
![NPEB01288_screenshot_2021_12_15_23_40_55](https://user-images.githubusercontent.com/23019877/146276112-0ceb30cb-52a7-4a15-8154-8d35ad4bb32b.png)

Vulkan:
![NPEB01288_screenshot_2021_12_15_23_39_34](https://user-images.githubusercontent.com/23019877/146275997-b6a0528e-47de-45d3-9061-0a33f4492e1f.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7723216/RPCS3.log.gz)
[NPEB01288_20211215234535_capture.zip](https://github.com/RPCS3/rpcs3/files/7723228/NPEB01288_20211215234535_capture.zip)

**Comment by AniLeo** [comment]
Can reproduce on radeonsi (mesa 21.3.1)

**Comment by orbea** [comment]
There are also similar issues with OpenGL and radeonsi in Tales of Xillia.

**Comment by kd-11** [comment]
Seems to have been fixed. Cannot reproduce on AMD or NV.

**Comment by Megamouse** [comment]
Indeed. I wonder what fixed it... (not gonna investigate though)
