### ISSUE TITLE
gta 5 freezes

### ISSUE THREAD

**Issue by triplethreat1469** [RPCS3/rpcs3#11261]
so im on arch linux 
and when i try to start gta 5 it freezes 
log 

S SPU: New block compiled successfully x9
F {SPU[0x4000100] Thread (PrimaryCellSpursKernel4) [0x05ee0]} SIG: Thread terminated due to fatal error: Segfault executing location 00007f49186e8dc0 at 00007f49186e8dc0.
Emu Thread Name: 'SPU[0x4000100] PrimaryCellSpursKernel4'.

S SPU: New block compiled successfully x17

**Comment by triplethreat1469** [comment]
why was this closed

**Comment by AniLeo** [comment]
Completely ignores issue guidelines

**Comment by triplethreat1469** [comment]
where can i find the guideines

**Comment by MSuih** [comment]
When you start to write a new issue there's a template in the text box which you're supposed to follow.

The main thing you missed is:
> Please do not ask for help or report compatibility regressions here, use [RPCS3 Discord server](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/) instead.
