### ISSUE TITLE
Failure to boot P4AU

### ISSUE THREAD

**Issue by GeetahrGG** [RPCS3/rpcs3#11264]
I'm honestly not sure what I'm doing wrong but I can't figure out how to get Persona 4 Arena Ultimax (NPUB31563) to boot properly. Apologies if I'm missing something obvious. I'm not sure if I'm missing something or it's a hardware issue, just haven't been able to find other answers

Specs:
Windows 10 x-64
CPU: AMD Ryzen 7 3700X 8-Core
GPU: NVIDIA GeForce RTX 2060
Driver Version 30.0.14.9709

Here is the log:

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7731730/RPCS3.log)

Thanks!

**Comment by YuriNator557** [comment]
## Please do not ask for help or report compatibility regressions here, use [RPCS3 Discord server](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/) instead.

Looks like bad game files
