### ISSUE TITLE
[Feature Request] New native menu that looks like ps3 xmb

### ISSUE THREAD

**Issue by ps3member** [RPCS3/rpcs3#11267]
It would be a fantastic idea to create a RPCS3 CFW 4.88. Maybe i'm a little bit crazy, but hear the idea before jude me.

RPCS3 should boot directly inside RPCS3 CFW 4.88 from where we could launch game, but how?
Well this new CFW, non compatible on official PS3 hardware should have:
- same patch as ps3 cfw to install unsigned pkg and boot unsigned code (i mean homebrew and other stuff)
- custom coldboot.raf (the ps3 logo visible on boot)
- custom plugin for setting category (some sprx and rco) to remove non useful stuff and by adding prcs3 setting. The setting file should, of course, be accessible by RPCS3 CFW (so.. dev_hdd0? dev_flash3?)
- custom xml game category and patch some sprx to show ps3 iso inside game column
- paching lv0, lv1 and lv2 to boot games through RPCS3 engine and not by ps3 engine
- replacing PSN with RPCN
- including ps1emu (duckstation), ps2emu (pcsx2), psp emu (ppsspp) and psvita emu (vita3k) to run ps1, ps2, psp and psv games directly from RPCS3 CFW XMB
- also adding settings for those ^ emulators in settings category
- release RPCS3 as a custom linux ISO that boots directly in RPCS3 XMB. As a file manager we could use the file manager by zahr (the one also available on managunz). Also boot option should be used directly bi RPCS3 cfw

by the way there're a lot of devs that could helps to make that cfw
- evilnat
- habib
- joonie
- bguerville
- DeViL303
- .....

you right, i'crazy :P

cheers

**Comment by Darkhost1999** [comment]
I agree a custom XMB would be really nice to make after the existing VSH/XMB is working.
The thought is for very longterm when there isn't the requirement to use Sony firmware at all. If and when that ever comes a possibility.

**Comment by ps3member** [comment]
I was also thinking that it will be even better to create a rpcs3 cfw based on ps3 ofw, decompiling sprx and rco, editing them, patching lv0, lv1 and lv2 and repacking the pup. This way rpcs3 could boot directly in rpcs3 cfw that could boot games directly from official xmb (of course by patching syscall and by adapting rpcs3 we can do almost everything)

**Comment by ps3member** [comment]
@AniLeo why did you close this feature request? Did i say something wrong?

**Comment by Darkhost1999** [comment]
I see nothing wrong with the feature request other than the information being uninformed in a lot of aspects and this being one of those "longterm" tags for after all the firmware libraries are no longer required from Sony. That's if and when ever potentially possible.
Because that isn't predictable as to when yes I'd probably close the issue too with out of scope for now and wait a century before reopening such a request.

**Comment by KaylaD23** [comment]
darkhost1999 the problem i see is once the vsh/xmb is fully implemented with all relevant functions then theres no need for what this person is proposing as the xmb would just do what its supposed to do and games would play as they are supposed to and if you want to run homebrew the option for installing cfw would be there rpcs3 would think its actually an authentic ps3 soo just a pointless feature request in my opinion specially for the time it would take to develope when the devs could use that time to further improve upon things making the emulator ever more closer to an actual ps3.
