### ISSUE TITLE
Error with KH1.5 HD remix

### ISSUE THREAD

**Issue by florian96** [RPCS3/rpcs3#1126]
Hey i got this error in the Console with Kingdom hearts 1.5 HD remix.

E Unimplemented function 'cellFsUtime' in 'sys_fs' module (0x32bb7c)
E Unimplemented function 'l10n_convert_str' in 'cellL10n' module (0x32c714)
E Unimplemented function 'l10n_get_converter' in 'cellL10n' module (0x32c74c)
E 'BreakPoints.dat' breakpoint db is broken (file is too short, length=0x6)

**Comment by PZerua** [comment]
Read the FAQ: http://www.emunewz.net/forum/showthread.php?tid=61854 .

Rpcs3 stills in development, at the moment It can only run some 2D games.

**Comment by Zangetsu38** [comment]
36d game works, The guided fate paradox ^^ and Disgaea 3 but is Ony 3d game works
