### ISSUE TITLE
God of war hd cutscenes black bar bug psn ver

### ISSUE THREAD

**Issue by Yoshi20004** [RPCS3/rpcs3#11270]
## Quick summary
When in fmv movie you get black bar buttom of screen 

## Details summary 
When you fmv movie on God of war hd psn thier black bar bug

#### 3. Please attach screenshots of your problem.
![Screenshot_20211220-155525](https://user-images.githubusercontent.com/96413420/146832199-7692c696-a81d-4ece-bd67-222e08ca30fd.jpg)

#### 4. Please provide comparison with real PS3.
Does have black bar with fmv movie at all
#### 5. Please provide your system configuration:
* windows 11
* Ryzen 9 4900hs 
* rtx 2060 max q
* 496.5

**Comment by Yoshi20004** [comment]
@kd-11 @AniLeo @illusion0001 do any of you guys know when bug happens only with psn and dev get this bug fixed please.

**Comment by Megamouse** [comment]
If legit, then this might possibly be a regression caused by the recent aspect ratio stuff.

**Comment by kd-11** [comment]
> If legit, then this might possibly be a regression caused by the recent aspect ratio stuff.

That's how its supposed to look. Original PS3 footage: https://youtu.be/jP_G3fzZTBI?t=120

**Comment by kd-11** [comment]
This is typical of all PS2 era games by the way because CRTs were the primary target and overscan was (and kinda still is) a thing. You can change the size in the options menu of the game.

**Comment by Megamouse** [comment]
oh. I thought the issue was regarding the size mismatch of the top and bottom bar.
But the screenshot doesn't even show the whole frame, so whatever
