### ISSUE TITLE
Arkedo 3 has horizontal band instead of blue gradient.

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1127]
When running Arkedo 3 : Pixel, there is a png decode error :

E {PPU[0x1] Thread (main_thread)[0x000768a8]} cellPngDec error: pngDecodeData: stbi_load_from_memory failed

I heavily suspect it's the reason there is horizontal blue/white line in game instead of the blue gradient that the game should features.
Using GPU perf studio 2 the texture used for the effect is a 16x1024 one, which is a weird size (it's neither a 1x1024 nor a more "squared" one), and the content seems random blue/white texel. I think it was wrongly decoded in the first place.

**Comment by tambry** [comment]
@vlj Is this still a problem?

**Comment by raven02** [comment]
If we use the cellPngDec LLE module , it decode all correct .

**Comment by tambry** [comment]
And that's the reason for #1359 :)

**Comment by raven02** [comment]
Cool .
