### ISSUE TITLE
Custom resolution does not work in windowed mode

### ISSUE THREAD

**Issue by NicknineTheEagle** [RPCS3/rpcs3#11276]
## Summary
Custom resolution setting does not seem to apply in windowed mode, it looks like the game still displays in 720p. It works fine in fullscreen mode, though. Tested multiple games (Need for Speed Carbon [BLES00020], Sonic the Hedgehog 4: Episode II [NPEB00717]). Issue is possibly driver-specific.

## Logs
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7757282/RPCS3.log.gz)
RSX capture (windowed mode): [BLES00020_20211221212234_capture.zip](https://github.com/RPCS3/rpcs3/files/7757286/BLES00020_20211221212234_capture.zip)

Windowed screenshot:
![windowed](https://user-images.githubusercontent.com/6665256/146980136-803f0d3b-7340-4ca9-a891-4bff84a40fe5.png)

Fullscreen screenshot:
![fullscreen](https://user-images.githubusercontent.com/6665256/146980156-e692b3e4-e0e2-4116-90ab-fa04751fb2dc.png)

## PC specs
* OS: Windows 10 Pro 20H2 (64-bit)
* CPU: Intel Core i5-9600KF @ 4.3 GHz
* GPU: GeForce RTX 2060 Super
* Driver version: 471.96

**Comment by Megamouse** [comment]
what did you expect from a 720p viewport?

**Comment by nastys** [comment]
Even though the window size is basically 720p, it should still look anti-aliased like in the fullscreen 1080p screenshot. Instead, it looks like it renders at native res (which is likely < 720p).

**Comment by Megamouse** [comment]
Compare the regular unscaled 720p image with your first screenshot and you will see a massive difference

**Comment by NicknineTheEagle** [comment]
> Compare the regular unscaled 720p image with your first screenshot and you will see a massive difference

What massive difference? It looks same.
![image](https://user-images.githubusercontent.com/6665256/146983644-7304fdc8-153e-4fd2-96e7-74a0cb05d18c.png)

**Comment by Megamouse** [comment]
This game is probably a bad example, but your 720p picture is a blurry mess compared to the windowed 4K image.
I also have NV and I don't see such bad aliasing in my games 🤔

**Comment by NicknineTheEagle** [comment]
I can barely tell the difference, I had to directly compare them side-by-side and it kind of looks like the unscaled screenshot is slightly blurrier, mostly noticeable on details such as Audi logo. Still, one would expect a lot bigger difference between the two.

**Comment by Megamouse** [comment]
Btw, If anything then it's a downscale issue, not a resolution scale issue.
You can use F12 to make a proper screenshot.
It should be the full 4K image no matter how big your viewport is.

**Comment by NicknineTheEagle** [comment]
> Btw, If anything then it's a downscale issue, not a resolution scale issue.

Yeah, that seems more likely.

>You can use F12 to make a proper screenshot.
It should be the full 4K image no matter how big your viewport is.

You're right, that indeed produces 4K image.
![BLES00020_screenshot_2021_12_21_22_11_10](https://user-images.githubusercontent.com/6665256/146985000-e608c82a-5ac0-4c40-8914-b6dcb67c3ead.png)

**Comment by NicknineTheEagle** [comment]
Actually, here's 1080p windowed:
![image](https://user-images.githubusercontent.com/6665256/146985548-924cca5c-a55e-467c-9cf6-93d4b6ac150e.png)

It looks a little worse than 1080p fullscreen. I'm guess downscaling works differently in windowed and fullscreen?

**Comment by nastys** [comment]
It's probably because the window size is not _exactly_ 1920x1080, so the scaling is a bit uneven.

**Comment by Megamouse** [comment]
you are comparing a native 1080p 1:1 pixel to pixel image with an image that is being downscaled from 1080p to some other resolution due to the borders.

In case you didn't know, the image will always look better if you have a higher display/window resolution. That's the reason why people buy 4K screens 😅

**Comment by Megamouse** [comment]
also, if 1:1 is not possible, then something like 2:1 is still better than something like 2.5:1 (which might be the case if you have a "windowed fullscreen")

**Comment by NicknineTheEagle** [comment]
> In case you didn't know, the image will always look better if you have a higher display/window resolution. That's the reason why people buy 4K screen.

Gee, thanks, Captain Obvious, what would I do without you?
The reason I got confused is because I've played games in 720p with anti-aliasing in the past and they tended to look better than this and downscaled custom resolution is essentially SSAA. Perhaps it's something about PAR to DAR ratio as it was suggested before.

**Comment by NicknineTheEagle** [comment]
![image](https://user-images.githubusercontent.com/6665256/146988140-82d7e325-7bb2-457a-a7fd-b2f91215b44f.png)

Here's 200% (1440p) downscaled to 720p. Definitely appears to be something about downscaling and ratios.
