### ISSUE TITLE
Audio issues : Gundam Extreme VS Full Boost Game 

### ISSUE THREAD

**Issue by JayJayuser** [RPCS3/rpcs3#11277]
## Quick summary
Audio issue: BLJS10250 / Gundam Extreme VS Full Boost Game 

BLJS10250 / Gundam Extreme VS Full Boost Game Audio issue (buzzing sound on fight stage) 
when using RCPS3 december 2021 version.
(No problem using Nov. 2021 version)

#### 1. Please attach RPCS3's log.RPCS3 v0.0.19-13110-47e4a95d Alpha | HEAD
Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz | 16 Threads | 31.84 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
Qt version: Compiled against Qt 5.15.2 | Run-time uses Qt 5.15.2
Thread time: 0.000000s (0.001177Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.004003 SYS: Initialization times before main(): 0.111107Gc
·! 0:00:00.004006 SYS: argc: 1, argv: 'D:\RPCS3 Version 0.0.18-12846-f90bf2dd Alpha [2021-09-29]\rpcs3.exe'
·A 0:00:00.152879 {Vulkan Device Enumeration Thread} RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 960' running on driver 496.13.0.0
·A 0:00:00.152895 {Vulkan Device Enumeration Thread} RSX: Found vulkan-compatible GPU: 'Intel(R) UHD Graphics 630' running on driver 0.402.199
·! 0:00:00.157482 {Vulkan Device Enumeration Thread} SIG: Thread time: 0.093750s (0.367170Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.157503 CFG: Setting the default renderer to Vulkan. Default GPU: 'NVIDIA GeForce GTX 960')
·! 0:00:00.157517 SYS: Setting user ID '00000001'
·! 0:00:00.159786 VFS: Loading VFS config. Path: D:/RPCS3 Version 0.0.18-12846-f90bf2dd Alpha [2021-09-29]/config/vfs.yml
·! 0:00:00.159941 SYS: Using VFS config:
$(EmulatorDir): ""
/dev_hdd0/: $(EmulatorDir)dev_hdd0/
/dev_hdd1/: $(EmulatorDir)dev_hdd1/
/dev_flash/: $(EmulatorDir)dev_flash/
/dev_flash2/: $(EmulatorDir)dev_flash2/
/dev_flash3/: $(EmulatorDir)dev_flash3/
/dev_usb000/: $(EmulatorDir)dev_usb000/
/dev_bdvd/: ""
/app_home/: ""
·! 0:00:00.159951 VFS: Mounted path "/dev_hdd0" to "D:/RPCS3 Version 0.0.18-12846-f90bf2dd Alpha [2021-09-29]/dev_hdd0/"
·! 0:00:00.159956 VFS: Mounted path "/dev_flash" to "D:/RPCS3 Version 0.0.18-12846-f90bf2dd Alpha [2021-09-29]//dev_flash/"
·! 0:00:00.159957 VFS: Mounted path "/dev_flash2" to "D:/RPCS3 Version 0.0.18-12846-f90bf2dd Alpha [2021-09-29]//dev_flash2/"
·! 0:00:00.159959 VFS: Mounted path "/dev_flash3" to "D:/RPCS3 Version 0.0.18-12846-f90bf2dd Alpha [2021-09-29]//dev_flash3/"
·! 0:00:00.159961 VFS: Mounted path "/dev_usb" to "D:/RPCS3 Version 0.0.18-12846-f90bf2dd Alpha [2021-09-29]/dev_usb000/"
·! 0:00:00.159962 VFS: Mounted path "/dev_usb000" to "D:/RPCS3 Version 0.0.18-12846-f90bf2dd Alpha [2021-09-29]/dev_usb000/"
·! 0:00:00.159964 VFS: Mounted path "/app_home" to "//"
·! 0:00:00.160017 SYS: Applying global config: D:/RPCS3 Version 0.0.18-12846-f90bf2dd Alpha [2021-09-29]//config.yml
·! 0:00:00.162390 SYS: Logged in as user '00000001' with the username 'User'
·A 0:00:00.163705 SYS: Firmware version: 4.65
·! 0:00:00.215398 GUI: Current language changed to English (en)
·! 0:00:00.405602 Compat: Finished reading database from file: D:/RPCS3 Version 0.0.18-12846-f90bf2dd Alpha [2021-09-29]/GuiConfigs/compat_database.dat
·! 0:00:00.837361 NET: Starting download from URL: https://update.rpcs3.net/?api=v2&c=47e4a95d
·! 0:00:00.837596 SYS: New timer resolution: 496 us (old=997 us, min=15625 us, max=500 us)
·S 0:00:01.533877 UPDATER: RPCS3 is up to date!

**Comment by Hasster1** [comment]
You do know, that you need to attach the log file itself, right?

**Comment by Megamouse** [comment]
closing as invalid and inactive
