### ISSUE TITLE
[Feature Request] additional option for popout Log:tty

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11283]
## Quick summary
As it seems I've only ever accidentally been able to make certain parts of the UI popout of their set places and be able to be viewed as separate windows.

## Details

There's a few things I noticed. First is if you toggle on or off the view Log:tty that the position of the window restores to its default locked into the UI position. I've clicked every and clicked and held everywhere. Looked for an icon of the 4 direction arrows saying I can move the window around. And it just seems like the window doesn't want to popout. My toddler has gotten it to popout more than I have honestly when he smacks my keyboard or throws my mouse.
Anyways my point is the context menu for the log:tty.
The one that has copy, select all, clear, fatal, error, todo, success, warning, notice, trace, stack mode (Log), show thread prefix.
Could use an additional popout the log:tty button. That way when clicking and dragging or doing all of that has a fail safe and a backup. Also for those that struggle can actually use the existing feature purposefully. 

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* Debugging
* UI
* Patches
* Installation
* etc.

Technically all of these. Can help you see errors and detect which settings you may want to use. Added convenience of not having to locate the exact spot at the correct angle with the specific technique I can't figure out or it's just broken on my machine.
The installation of things can easily be readable for success and warnings or errors.
See if patches applied, and adds something to a context menu to enable the floating windows mode or whatever the proper name is.

#### 2. Please tell us, why your feature is important to RPCS3.
Helps give a physical visual button that can be pressed instead of an invisible quirky feature people discover by accident.

#### 3. Please attach screenshots of the feature implemented in other projects.

I do not have OBS installed to demonstrate and screenshot.

#### 4. Please provide your system configuration:

In case this is actually an issue that the log isn't dragging out of it's home.
* Windows 11 beta
* Ryzen 5 3600 
*GTX 1660S 
* 497.29
Logitech m510 mouse with Logitech input drivers from windows OS.

#### Please include.

I typed a lot. Essentially asking for an added context menu to make the view -> log:tty popout and become it's on window. Aiding in a real software button we can intentionally and purposefully push to move the window to a full maximized view,  potentially another monitor, and increase the ease of reading a log separate from the games list and default interface position. If such a feature already exists and I'm. Oblivious to it. Please point it out.
Clicking and holding then dragging doesn't seem to work for me for every one of my purposeful attempts.

**Comment by Darkhost1999** [comment]
Also if a hotkey exists lmk. Please and thank you.

**Comment by Megamouse** [comment]
I don't know what's the problem. There already exist standard buttons:
![image](https://user-images.githubusercontent.com/23019877/147222848-32d3774a-3f7a-4db4-b347-e0f4697043a2.png)

**Comment by Darkhost1999** [comment]
I'll change theme and double check. Haven't observed those buttons being there for a while.

**Comment by Darkhost1999** [comment]
Fixed. :facepalm:
View -> Show title bars
