### ISSUE TITLE
Cod World at War regression

### ISSUE THREAD

**Issue by coolllman** [RPCS3/rpcs3#11281]
Cod World at War regression after 0.0.19-13117
After
![Screenshot_20211223-021423_VNC Viewer](https://user-images.githubusercontent.com/17841647/147153953-f60c8908-cbdc-4199-9bf7-ec5b20b832de.jpg)
Before
![Screenshot_20211223-025634_VNC Viewer](https://user-images.githubusercontent.com/17841647/147154140-9a9d672e-b541-4b05-b1e8-97a72ba4e01a.jpg)

**Comment by kd-11** [comment]
Please attach RSX captures, I cannot fix it without some kind of trace. You can dump RSX captures from the rpcs3 menubar under "Utilities" entry.

**Comment by coolllman** [comment]
RSX capture
https://drive.google.com/file/d/1rx1lCydKYOuQ1O3FIBosDdUJbuiwDZcW/view?usp=drivesdk

**Comment by Emulator-Team-2** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/11301.

**Comment by coolllman** [comment]
Yes fixed, thank you so much kd-11 for your hard work.
