### ISSUE TITLE
asmjit built_function (since commit dcd0110) prevents RPCS3 from running on macOS

### ISSUE THREAD

**Issue by nastys** [RPCS3/rpcs3#11287]
Since commit dcd0110, RPCS3 crashes before even showing the game list, with
```Verification failed
(in file /Users/nastys/rpcs3/rpcs3/util/vm_native.cpp:286[:3], in function memory_protect) (errno=13)
Thread id = 0x107bd3600.
```

With a debugger, I have been able to find which function called mprotect by looking at the stack:
```
thread_ctrl::emergency_exit(std::basic_string_view<char,std::char_traits<char>>)
fmt::raw_verify_error(src_loc const&,char8_t const *)
utils::memory_protect(void *,unsigned long, utils::protection)
asmiit::inline_runtime::~inline_runtime()
```
By commenting out the ``utils::memory_protect`` line in ``asmiit::inline_runtime::~inline runtime()``, RPCS3 does run, but attempting to use asmjit for SPU results in a segfault (while using the interpreter still works fine).

I have also modified vm_native.cpp to log every pointer that goes through mprotect:
```
mprotect ptr64: 0x14000000
mprotect ptr64: 0x14001000
mprotect ptr64: 0x14002000
mprotect ptr64: 0x14003000
mprotect ptr64: 0x14004000
mprotect ptr64: 0x14005000
mprotect ptr64: 0x14006000
mprotect ptr64: 0x14007000
Debugger: 0
mprotect ptr64: 0x14008000
mprotect ptr64: 0x14009000
mprotect ptr64: 0x1400a000
mprotect ptr64: 0x04800000
mprotect error 13 # EACCES
```

No log file is created at all.
Tested on both M1/Rosetta and Intel.

**Comment by Nekotekina** [comment]
Seems related to hardened runtime https://developer.apple.com/documentation/security/hardened_runtime

**Comment by nastys** [comment]
I haven't signed RPCS3 at all, so the hardened runtime shouldn't be enabled to begin with. I also keep SIP disabled.
I've also tried signing it, adding entitlements, and even running it as root.

**Comment by Nekotekina** [comment]
Okay, it still looks like a security mechanism. Try to replace rx with wx in memory_protect call.

**Comment by Nekotekina** [comment]
Nvm, I think I found it:
https://stackoverflow.com/questions/60497896/self-modifying-code-on-darwin-10-15-resulting-in-malformed-mach-o-image/60505259#60505259
The workaround doesn't look easy to implement, I'll think what can be done instead.

**Comment by Nekotekina** [comment]
Workaround should be on master

**Comment by nastys** [comment]
The workaround works on my M1 with macOS 12.1 and spurs_test performs the same as my fork:rmacs3 (which basically has the built_function commit reversed).
However, I've also tried building a9303acf (which was before this workaround) on macOS 10.14 (Intel) and it doesn't seem to be affected from this issue, at least on that machine (copying anything I build on the Intel one to the M1 makes it crash with ``illegal instruction``, for some reason).

**Comment by Nekotekina** [comment]
Not sure I understand what remains to fix, current workaround seems fine.

**Comment by nastys** [comment]
Indeed. I guess it's currently the only fix when targeting Catalina or newer.
