### ISSUE TITLE
NPUB30811 Test drive ferrari racing legend (#11268)

### ISSUE THREAD

**Issue by Emule01** [RPCS3/rpcs3#11285]
![Capture d’écran 2021-12-23 151917](https://user-images.githubusercontent.com/96583243/147252920-05075555-d51d-4609-ae55-ee9a49bf488b.png)
same  issue  in race, the  road  become invisible  in front of the car ...   this start with newest  rpcs3 build 0.0.19.13117 , it was great  before  with build 0.0.19.13114

**Comment by kunit1** [comment]
You should test with latest master as it might have been fixed with [11301](https://github.com/RPCS3/rpcs3/pull/11301)

**Comment by AniLeo** [comment]
Issue is unfinished, no log file / system information, likely fixed too as indicated above, closing. Ask to reopen with a log file if it's reproduceable on current master.
