### ISSUE TITLE
Resistance 3 freeze

### ISSUE THREAD

**Issue by coolllman** [RPCS3/rpcs3#11294]
![BFBA3F49-F2CF-4F17-BA84-8BF090EEC596](https://user-images.githubusercontent.com/17841647/147385957-383b6d92-bb36-47a0-990d-b9b01a1aed31.png)

**Comment by coolllman** [comment]
Everytime 5-10 min freeze and rpcs3 close
Log
https://drive.google.com/file/d/1Qxdji7dnMBZLmkhEzHPfqQfWDhiUNvRs/view?usp=drivesdk

**Comment by YuriNator557** [comment]
may be related to #10926

**Comment by AniLeo** [comment]
Closing due to lack of detail, assuming it's a duplicate, track it there and check again after the issue with recent NV drivers is solved
