### ISSUE TITLE
[BLUS30947] Ni No Kuni Wrath of the White Witch

### ISSUE THREAD

**Issue by SaintZeroZ** [RPCS3/rpcs3#11295]
## Quick summary
Anytime I get into a battle or the overworld the background clips over the foreground.

## Details
I've played both default and changing settings. Everytime I play the grass and backgrounds clip over the foreground blocking a portion of the screen. I've tried disabling anti-aliasing, setting antisotropic filter to 16x, writing color buffers, strict rendering mode, writing and reading color buffers.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7776150/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
[BLUS30947_20211225130333_capture.zip](https://github.com/RPCS3/rpcs3/files/7776151/BLUS30947_20211225130333_capture.zip)

#### 3. Please attach screenshots of your problem.
![rpcs3 screenshot](https://user-images.githubusercontent.com/92452497/147391154-4eae87f8-d245-4d4d-afef-30eeac2a70a5.PNG)

Can't do a renderdoc capture

**Comment by MarioSonic2987** [comment]
This regression is caused by #11268.

![image](https://user-images.githubusercontent.com/20027681/147392916-797b1ea1-86fa-44c7-a1e7-3b5681ca2a4e.png)
![image](https://user-images.githubusercontent.com/20027681/147392918-e909bca5-f328-43fc-abbd-22f6e83d49a2.png)

**Comment by SaintZeroZ** [comment]
So what do I do? I don't know a lot about all this. Do I just wait for rpcs3 to update?

**Comment by MSuih** [comment]
You've done everything you can. Now you'll wait and maybe a developer will fix this in future. Might be soon, might take months or even years in worst case.

**Comment by SaintZeroZ** [comment]
Okay thank you. Should I keep this open until it gets fixed? I understand todays Christmas so people might not be working on it. Merry Christmas.

**Comment by orbea** [comment]
> Should I keep this open until it gets fixed?

Yes, please keep it open until its fixed.

**Comment by SaintZeroZ** [comment]
Alright will do. I've been using version 13114 like the other person who shown in his screenshot until then. I'll just transfer saves and then close when it gets fixed.
