### ISSUE TITLE
Netflix [NPUP00030] Fatal illegal socket error

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11308]
Netflix on PS3 gives a Fatal illegal socket error after PR #11304

2 logs:
* One for the build with regression.
#11304 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7781814/RPCS3.log)
* One for the build that works as expected.
#11307 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7781818/RPCS3.log.gz)

**Comment by clienthax** [comment]
Looks like Netflix was using some of the functionality implemented by that PR, was likely just handling the error codes nicely before,
Opens port 1900 for SSDP and uses IP_MULTICAST_TTL + IP_ADD_MEMBERSHIP.

**Comment by Darkhost1999** [comment]
Ok so now the feature is implemented correctly an error was dug up. Understandable

**Comment by clienthax** [comment]
Yep.. windows is def not liking the data structure passed into setsockopt for IP_ADD_MEMBERSHIP.
SYS_NET_IP_MULTICAST_IF has similar issues.

Not quite sure why SYS_NET_IP_MULTICAST_TTL is failing however

**Comment by Darkhost1999** [comment]
> IP_ADD_MEMBERSHIP seems to fail.
* Just a status update following https://github.com/RPCS3/rpcs3/pull/11496
Status unchanged [log](https://github.com/RPCS3/rpcs3/files/8011372/RPCS3.log)
But is the cause of this error the same?
```F 0:00:28.403856 {PPU[0x1000018] Thread (NBP_POOL [2] (pt)) [0x017905f4]} SIG: Thread terminated due to fatal error: sys_net get_last_error(is_blocking=0, native_error=10014): Unknown/illegal socket error
(in file D:\a\1\s\rpcs3\Emu\Cell\lv2\sys_net.cpp:354[:23], in function get_last_error) (e=0x0000271e[10014])
W 0:00:28.404011 {PPU[0x1000018] Thread (NBP_POOL [2] (pt)) [0x017905f4]} SYS: Emulation has been frozen! You can either use debugger tools to inspect current emulation state or terminate it.

**Comment by Darkhost1999** [comment]
I assume SYS_NET_IP_MULTICAST_IF and SYS_NET_IP_MULTICAST_TTL are still at fault?

**Comment by Darkhost1999** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8011391/RPCS3.log)
My mistake https://github.com/RPCS3/rpcs3/commit/987166f4da20e19d01777d0bfad64a811d8de1d1 does fix the issue.
I'll wait for master to receive update before closing

**Comment by RipleyTom** [comment]
It's been merged, closing.

**Comment by Darkhost1999** [comment]
Yes it's been merged but the master branch still has no check for updates including this fix
