### ISSUE TITLE
No games boot on RPCS3 for WIndows OS

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11302]
## Quick summary
Whole emulator not just the game window closes after PPU's are compiled or before a single module is linked.

#### Please attach TWO logs:
* One for the build with regression.
#11292 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7777215/RPCS3.log)
* One for the build that works as expected.
#11301 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7777216/RPCS3.log.gz)

#### Please provide your system configuration:
* WIndows 11 Beta
* Ryzen 5 3600
* GTX 1660S
* 497.29

**Comment by Nekotekina** [comment]
~~Nice.~~ Do interpreters work?

**Comment by Darkhost1999** [comment]
yes
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7777235/RPCS3.log.gz)

**Comment by coolllman** [comment]
Not work with fix, the same bug: exit on loading ppu modules

**Comment by Darkhost1999** [comment]
Thanks Neko. I blinked and the game was booted. I didn't believe it
