### ISSUE TITLE
Regression: VSH Browser (#8431)

### ISSUE THREAD

**Issue by clienthax** [RPCS3/rpcs3#11305]
## Quick summary
VSH Browser worked before https://github.com/RPCS3/rpcs3/commit/54308920522adc7c850335f607f2fc44cd5b6797
Removing the check lets it load up properly again.

**Comment by Linear524** [comment]
Latest revisions boots XMB/VSH fine:
![1699](https://user-images.githubusercontent.com/84367301/147622171-35318878-7ebf-45d1-bc8d-8b28dc1d12d1.jpg)
![1700](https://user-images.githubusercontent.com/84367301/147622173-543fd7cb-7cec-4056-8f9d-a9c568a79d32.jpg)

The only issue I have with it - I can't set HDMI mode and installed pkg games won't boot (they never boot before either)

**Comment by AniLeo** [comment]
This issue is not about VSH functionality other than the Web Browser

**Comment by AniLeo** [comment]
Retested on current master, still an issue

**Comment by marcoluc97** [comment]
Now after cellHttp?

**Comment by clienthax** [comment]
Cellhttp has nothing to do with the issue.

**Comment by AniLeo** [comment]
Still an issue on 0.0.25-14465
