### ISSUE TITLE
[Feature Request] remove the need for post on Rpcs3 forums check by a mod

### ISSUE THREAD

**Issue by Toxin60009** [RPCS3/rpcs3#11310]
## Quick summary
As it is now rpcs3 forums post need check mods which not cases because slow down staff for playable report.

## Details

It should be just post what on Rpcs3 forums and shows up for everyone It make things go faster and staff done at faster place.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* it would post show up  right away not after mod looks at it.

#### 2. Please tell us, why your feature is important
Because slow down staff like playable report wait to allowed on and thier no way people 1 day just see post on or not.

#### Please include.
* it's should because make easier for playable report to made and done.

**Comment by Megamouse** [comment]
Not related to the software

**Comment by Toxin60009** [comment]
Please just remove it because make it take long post made.
