### ISSUE TITLE
AMDVLK Driver doesn't allow Games to boot since #11288

### ISSUE THREAD

**Issue by JoshuaHasNoClue** [RPCS3/rpcs3#11313]
## Quick summary
Using the AMDVLK driver on Linux doesn't allow Games to boot (even on OpenGL). Only the Mesa Drivers (RADV) work.

## Details
Whilst trying to play games on the AMDVLK driver, the emulator crashes on Vulkan and hangs on OpenGL. Forcing the use of RADV it just works. This is the case starting with Pull request #11288 

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
[RPCS3_AMDVLK_OpenGL.log.gz](https://github.com/RPCS3/rpcs3/files/7792948/RPCS3_AMDVLK_OpenGL.log.gz)
[RPCS3_RADV_OpenGL.log.gz](https://github.com/RPCS3/rpcs3/files/7792949/RPCS3_RADV_OpenGL.log.gz)

#### 3. Please attach screenshots of your problem.
Running OpenGL on the AMDVLK Driver
![Bildschirmfoto von 2021-12-30 13-37-12](https://user-images.githubusercontent.com/93594656/147752616-a08df45d-0976-46de-94a4-c60f663d1050.png)

#### 4. Please provide comparison with real PS3.
Not Possible: Issue on Linux

#### 5. Please provide your system configuration:
endeavourOS (Linux 1.15.11-arch2-1)
Ryzen 5 2600
Radeon RX Vega 64
AMDVLK 2021.Q4.3-1

**Comment by kd-11** [comment]
Are you running a X11 session or a wayland session?

**Comment by JoshuaHasNoClue** [comment]
Wayland

**Comment by kd-11** [comment]
Does vulkan work? OpenGL does not use amdvlk but radeonsi.

**Comment by JoshuaHasNoClue** [comment]
Vulkan does not work. Both OpenGL and Vulkan only work when forcing RADV for some reason.

**Comment by shinra358** [comment]
GPD Win 3 i7-1195g7 intel
Nothing works under vulkan either and opengl games have reduced playability as well unlike on my nvidia 980m, i7-4960x laptop (where everything works normally with same setup).

**Comment by AniLeo** [comment]
Since when can you use amdvlk on an Intel GPU?

**Comment by JoshuaHasNoClue** [comment]
Something fixed this, I don't know what commit, but I am closing this
