### ISSUE TITLE
Prince Of Persia 2008 performance degradation

### ISSUE THREAD

**Issue by transient-sepia** [RPCS3/rpcs3#11316]
## Quick summary
Prince Of Persia 2008 performance degradation on newer builds.

## Details
Game starts fine with default settings, but as soon as the first tutorial combat encounter starts, FPS tanks to low 20s and the log gets flooded with messages like `Stale surface at address ... will be deleted`. I skimmed through various old builds and discovered that the last known good build for this game is 0.0.14-11749 (making pull #9772 the one to break things). With that build I can continue well into the game past tutorial section. 

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
* Build 0.0.14-11751 (pull #9772)

#### 2. Please attach TWO logs:
* One for the build with regression - [RPCS3-13137.log](https://github.com/RPCS3/rpcs3/files/7795254/RPCS3-13137.log)
* One for the build that works as expected - [RPCS3-11749.log](https://github.com/RPCS3/rpcs3/files/7795253/RPCS3-11749.log)

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
No graphical regression, only performance issue.

#### 4. Please attach screenshots of your problem.
No screenshots needed due to this being only a performance issue.

#### 5. Please provide comparison with real PS3.

No comparison was done with real hardware.

#### 6. Please provide your system configuration:
* Windows 10.0.19043
* Intel i7-8700K
* NVIDIA RTX 2080 Ti
* Driver 497.29

#### Please include.
No additional information.

**Comment by kd-11** [comment]
I know what causes it, I'll see about speeding up the operations.
