### ISSUE TITLE
Sample applications [TEST12345] shows as corrupted data in VSH

### ISSUE THREAD

**Issue by illusion0001** [RPCS3/rpcs3#11326]
Missing launcher, metadata (param.sfo), icon0, pic0

**Comment by MSuih** [comment]
If this information is added then they'll also show up in emulators game list, I don't think we want that. I suppose that could be countered by making emulator ignore that directory when loading dev_hdd0 to list

**Comment by Vestrel** [comment]
Maybe move them into separate directory altogether?

**Comment by illusion0001** [comment]
Yea
