### ISSUE TITLE
Mortal Kombat II [NPUB30004] Incorrect colors.

### ISSUE THREAD

**Issue by levonnn** [RPCS3/rpcs3#11324]
Majority of colors aren't correct.

## Details

Default settings. The issue affects the whole game. Colors appear inverted. Tried both Vulkan and OpenGL.

#### 1. Please attach RPCS3's log.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7799792/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.

[NPUB30004_20220103011343_capture.zip](https://github.com/RPCS3/rpcs3/files/7799800/NPUB30004_20220103011343_capture.zip)

#### 3. Please attach screenshots of your problem.

![NPUB30004_screenshot_2022_01_03_00_44_13](https://user-images.githubusercontent.com/46363559/147889567-94cc6ee1-36a4-4b8f-b92f-8b885ab42753.png)

#### 5. Please provide your system configuration:
Win 7 64
i7
GTX 760

**Comment by Megamouse** [comment]
I think that was the smurf edition

**Comment by ChwaraeTeg** [comment]
Re-tested with v0.0.29-15711 and can confirm issue is still present. Tried enabling WCB+RCB+WDB+RDB and SRM but these made no difference.

RPCS3:
![Emulator](https://github.com/RPCS3/rpcs3/assets/104720038/6e89fc34-39cf-49db-ace6-d40475d9dc69)

Comparison with console:
![Console](https://github.com/RPCS3/rpcs3/assets/104720038/dbcf491c-a979-49fd-8f5c-2cb9be94c78f)

Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13259988/RPCS3.log.gz)

**Comment by kd-11** [comment]
Likely palette lookup issues.

**Comment by kd-11** [comment]
Or maybe just BGR scanout lol. I need to check this.

**Comment by kd-11** [comment]
> Or maybe just BGR scanout lol. I need to check this.

This was correct. The developer messed up the output formats so we need to correct before submit.
Fixed by https://github.com/RPCS3/rpcs3/pull/15003

**Comment by Triticum0** [comment]
@kd-11 This also fixes Joust and properly all Foundation 9 Entertainment but there is another issue to do with the game or my rip making the game unplayable for me.
So ask [ChwaraeTeg](https://github.com/ChwaraeTeg) to retest then close #14001
