### ISSUE TITLE
3D Dot Game Heroes Custom characters loaded through external Save Data are blank and crash the game

### ISSUE THREAD

**Issue by JazzyFuture** [RPCS3/rpcs3#11336]
So in 3D Dot Game Heroes I tried to transfer over some custom characters I have in the PS3 version, putting them in RPCS3\dev_hdd0\home\00000001\savedata, cause that seemed like the only way for them to read them like putting them on a USB on PS3, yet all the details are blank including name, class, gender, and the actual voxel placement.
Characters included in the game don't have this issue, am I just doing something wrong? I even tracked down the GameSpy Links and couldn't get them to work.

**Comment by Megamouse** [comment]
I think you should try to figure this out with help on discord before opening an issue here
