### ISSUE TITLE
Uncharted: Drake's Fortune crashes at the specific spot in jungles

### ISSUE THREAD

**Issue by Emogop** [RPCS3/rpcs3#11331]
After the boat episode at the very beginning I turned out to be in the jungles. And there is the spot where I can't go through, because of the crash.

I'm using the latest build RPCS3 Version: 0.0.20-13145-0d4543ca Alpha
Unfortunately I don't what the latest stable build was, but seen how people went at least as far as 4 chapter I have no doubt it's a regression.

What I already tried:
*TSX on/off
*Driver delay: default/725
*ASMJIT/LLVM

* OS Win 10 21H1
* CPU i7 6700 3,7 ghz  (ES)
* GPU 1060
* Driver version: 471.96

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7806354/RPCS3.zip)

**Comment by Megamouse** [comment]
disable patches

**Comment by Emogop** [comment]
For some reason installing the 1.01 update helped. I'm closing the issue.
