### ISSUE TITLE
[Documentation] Deletion of VSH/XMB config files does not fully reset configuration

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#11330]
VSH/XMB troubleshooting documentation as found [here](https://wiki.rpcs3.net/index.php?title=Help:Frequently_Asked_Questions) states:

> In case you somehow manage to brick it, you can try removing the dev_flash2 and dev_flash3 folders from the RPCS3 directory. This will put you back at square one (you'll need to do the initial setup all over again).

In practice, this does not fully work.  

Quitting XMB without saving may cause the emulated system to report corrupted files:

![pic2](https://user-images.githubusercontent.com/12475371/147978263-ee301db8-54e0-40c2-a6c8-3d4c4a61afb9.png)

Following this, the screen turns black and hangs (it is assumed the emulated system is not actually restarting / restoring files).

Removing `~/.config/rpcs3/dev_flash2` and `dev_flash3` directories resets user data, but still results in the above screen being displayed.  It is currently unknown how to fully reset the system to a scratch config and correct this condition.

Test details:
* OS: Linux Mint 20.2 / kernel 5.13
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070
* Driver version: 470.86
* Commit tested: 0d4543ca2a3d23a21d5ac9ba8654bddcf143c438
* Firmware: 4.87

**Comment by mjd180** [comment]
Workaround not mentioned in wiki: back/circle out to proceed.

**Comment by clienthax** [comment]
Ugh.

**Comment by Shoegzer** [comment]
Nice catch, and ugh seconded.  It seems the "Back" option simply avoids a system restart and rebuilds the database anyway ("Back" is a bit deceiving as it doesn't go back to the previous menu item, which is why I hadn't checked it).  So yes I think this workaround would be good to have in the wiki.  

Also - besides deleting `dev_flash2` and `dev_flash3` I also tried deleting `dev_hdd0/vsh` but that didn't clear the condition either.  So whatever specifc db path/file triggers the condition could also be explained in the wiki.

**Comment by DesGres** [comment]
![image](https://user-images.githubusercontent.com/97255562/148444858-b4f89b3b-8a97-42a1-89d5-6a9627663e73.png)

Looks like a turnoff file is generated in the temp folder , if you close the XMB correctly it is auto deleted , manual closing stops it from clearing , so it is present upon next boot and forces the recovery mode.

Make sure you delete it to avoid the enforced recovery

**Comment by clienthax** [comment]
Alternatively we can just do a naughty and lie about that file existing, which will be a nicer experience

**Comment by JimScript** [comment]
dev_hdd0\mms also controls some vsh functions; mainly the xmb icons that appear for content.
