### ISSUE TITLE
Games Crashing upon launch, after updating to the macOS fixes #11342

### ISSUE THREAD

**Issue by Danke-Boi** [RPCS3/rpcs3#11346]
Well, I have been able to play many games using this emulator, most notably Ace Combat

Before updating, I was able to launch Ace Combat Assault Horizon, and mess with settings and do various things (Ace Combat runs at about 23fps average, but that's a different issue). But after updating, no new game will launch. I have a considerable library, and I tried specifically GT5

0. This part was done, but to the M1 settings (ASMJIT, Disable On-Disk Shader Cache) ASMJIT allows GT5 to become playable, by making buying used cars not crash the game. The other was recommended by a dev (I forget who, saw it in a YouTube demonstration of Persona 5)
1. I have updated to every MacOS build that has come out since Monday night (lol) that has passed on CirrusCL

#### 2. Please attach TWO logs:
* One for the build with regression.
* RPCS3: PPU[0x1000000] Thread (main_thread) [0x01c76908]: SIG: Thread terminated due to fatal error: Too many open files. Raise the limit and try again.
(in file /private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/rpcs3/util/vm_native.cpp:331[:5], in function shm) (errno=24)
QThreadPipe: Unable to create pipe: Too many open files
QEventDispatcherUNIXPrivate(): Cannot continue without a thread pipe
zsh: abort

3. Does not apply

#### 4. Please attach screenshots of your problem.

<img width="142" alt="Screen Shot 2022-01-07 at 11 13 51 AM" src="https://user-images.githubusercontent.com/72051710/148572636-ad1cf91c-c863-4d9b-8e9a-819cd8d2462a.png">
The entire Emulator freezes
#### 5. Please provide comparison with real PS3.
Um... the game doesn't crash on startup on my PS3

#### 6. Please provide your system configuration:
* MacOS 11.6.3
* M1
* 7 core M1
* ???
* 8GB RAM (MacBook Air cannot go higher than this)

#### Please include.
I believe I am either running out of RAM, or I need to enable on disk cache. Either that, or I need to somehow increase max thread count. How would I do that? What negative effects would that have?

**Comment by Danke-Boi** [comment]
New update came out 2 hrs ago, installed it, and I am getting new errors.
I thought I copy pasted the error, but I didn't. It described the location of the fault and an ID, and the emulator recognized that the game was freezing and gave me the option to close it. I'll run it again and take a screenshot.

**Comment by isJuhn** [comment]
Invalid issue, #11342 was never merged and is now closed. Also missing logs in any case.
