### ISSUE TITLE
Audio Crackling

### ISSUE THREAD

**Issue by RinMaru** [RPCS3/rpcs3#11344]
Lately Audio has been crackling and I've narrowed it down to the default Sound Buffering at 48ms. turning it up to 125ms gets rid of the issue but im not sure why all the sudden its needed to be changed this started happening around the same time cubeb got added but not sure its the cause

RPCS3 v0.0.20-13150
Windows 11
Ryzen 5 5600X
RX 480 4GB
20GB DDR4 RAM

**Comment by Vestrel** [comment]
Test with #11345

**Comment by RinMaru** [comment]
> Test with #11345

that fixed it thank you
