### ISSUE TITLE
Persona 5 loading freeze. Kamoshita Castle 2F

### ISSUE THREAD

**Issue by Beautrick** [RPCS3/rpcs3#11340]
Game freezes at the loading screen when i try to enter another location of the palace. Specifically Komshita Castle 2F 

## Details

Here are the error logs, I don't really understand the issue at all.

E SYS: 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'cellGameDataCheck' failed with 0x8002cb05 : CELL_GAME_ERROR_BROKEN, psf::error='OK', type='3' CATEGORY='HG' [1]
E SYS: 'cellGameContentPermit' failed with 0x8002cb22 : CELL_GAME_ERROR_FAILURE [1]
S sys_prx: _sys_prx_unload_module(id=0x23011800, flags=0x0, pOpt=*0x0): name='libsysutil_game.sprx'
E SYS: 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [2]
S RSX: Program compiled successfully
E SYS: 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [3]
S RSX: Program compiled successfully x46
F {PPU[0x1000004] Thread (gfdJobQueueFiberWorker) [0x0098cf9c]} VM: Access violation reading location 0x1 (unmapped memory) [type=u0]
E SYS: Stat: 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [[x10]](url)

* OS = Microsoft Windows 10
* CPU = Intel Core i7 8750H
* GPU = NVIDIA GeForce GTX 1050 Ti
* RAM = 16GB

I already attached my log files, hopefully someone can figure out the issue.

**Comment by AniLeo** [comment]
Pirated game detected, closed and locked
