### ISSUE TITLE
[Feature Request] Use RPCS3 as CLI/shared library

### ISSUE THREAD

**Issue by dragonDScript** [RPCS3/rpcs3#11362]
It'd be nice to be able to use RPCS3 (e.g. launch games, change settings) from a CLI or shared library. This way we could have alternative GUIs for it

**Comment by MSuih** [comment]
You can already run rpcs3 with --no-gui and giving a path to the games EBOOT.BIN file. See --help for the list of CLI options.

Closing this as it's already implemented.

**Comment by dragonDScript** [comment]
Launching games is already implemented, but most features aren't.

**Comment by MSuih** [comment]
You can reopen the issue after you're reworded the original message to more clearly indicate which features are still missing.

**Comment by Darkhost1999** [comment]
A lot of command line requests are here as well
https://github.com/RPCS3/rpcs3/issues/5312

**Comment by dragonDScript** [comment]
> You can reopen the issue after you're reworded the original message to more clearly indicate which features are still missing. Try making a list of them, for example.

> (e.g. launch games, change settings) from a CLI or shared library. This way we could have alternative GUIs for it

I won't make a list that lists every RPCS3 feature as you can understand. But here is a program that does the same with Epic games: https://github.com/derrod/legendary

**Comment by Megamouse** [comment]
you can always fork the project and implement your own User Interface.
I don't know why this should be our task.

**Comment by MSuih** [comment]
Adding a cli argument for every single functionality of RPCS3 is going to be a monumental effort, just to get a feature that 95% of our users won't be using.

If there are more important commands missing from CLI then you can suggest for those to be added, but we're not going to add hundreds and hundreds of arguments so that someone can add this emulator to their frontend and beg for donations.

**Comment by dragonDScript** [comment]
> you can always fork the project and implement your own User Interface. I don't know why this should be our task.

Because why reinvent the wheel?

> Adding a cli argument for every single functionality of RPCS3 is going to be a monumental effort, just to get a feature that 95% of our users won't be using.

> If there are important commands missing from CLI then you can suggest for those to be added, but we're not going to add hundreds and hundreds of arguments so that someone can add this emulator to their frontend and beg for donations.

We're talking about basic things, like the settings.

**Comment by HerrHulaHoop** [comment]
Settings has been exposed through CLI. You can point it to a `config.yml` file with the `--config` parameter and it will boot with the settings mentioned there. As mentioned, make a list of features that you feel needs to be added and list them down. We can then discuss if they can be added to CLI or not. There's no point of these broad-stroke feature requests.
