### ISSUE TITLE
PERSONA 5 [BLUS31604] Stopped working on version 0.0.20-13175-949e93be Alpha

### ISSUE THREAD

**Issue by vcrispoli** [RPCS3/rpcs3#11368]
Every time I tried to boot the game in this version the following error messages showed up:
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS31604/USRDIR/ps3.cpk” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS31604/USRDIR/data.cpk” [1]

Important to notice that game was running like a charm up to this update.

Thanks!
V.

**Comment by kd-11** [comment]
Closing, fixed by https://github.com/RPCS3/rpcs3/pull/11370
