### ISSUE TITLE
Resistance Fall of Man [BCUS98107] Random freezes "Some thread has probably deadlocked"

### ISSUE THREAD

**Issue by yeetmeister64** [RPCS3/rpcs3#11364]
Hello Everyone!

Recently started playing Resistance 1, however when using vulkan game freezes, sometimes instantly sometimes after 10-15 minutes,crashing my gpu drivers during it, tried multiple driver versions but it didnt help, when i close the game i see the error code "Some thread has probably deadlocked", i tried enabling and disabling Multithreaded RSX but it doesnt help, the game works fine on opengl but the performance is suboptimal

system configuration:
* Windows 11
* Ryzen 5 5500U
* GPU: Amd Vega 8
* Driver: Adrenalin 22.1.1
* RAM: 16GB 3200mhz
* Storage: 512GB nmve ssd

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7857170/RPCS3.log)

**Comment by AniLeo** [comment]
Please retest and update this issue with AMD drivers 23.2.1 or newer as recently there have been changes that positively impact RPCS3.

**Comment by FahrentH8t** [comment]
I think this is fixed by now.
