### ISSUE TITLE
Games do not boot after #11178

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#11360]
After PR #11178 was merged path handling got broken in some way. Booting any disc game with it just shows "Booting failed: The selected file or folder is invalid or corrupted." error, and booting any HDD game makes emulator close after loading caches.

[broken_disc.RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7851617/broken.RPCS3.log.gz)
[broken_hdd.RPCS3.log](https://github.com/RPCS3/rpcs3/files/7851629/broken_hdd.RPCS3.log)
[working.RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7851618/working.RPCS3.log.gz)

Tested on windows, have gotten confirmation that linux is unaffected. The previous version (which was rollbacked on rpcs3.net/downloads) works fine.

**Comment by MSuih** [comment]
To elaborate further, disc games seem to be missing last part of path:
```
Invalid disc directory for the disc game BLUS30464. (D:\Emulaattori\Pelit\PS3\Skate 3PS3_DISC.SFB)
```
This should have a backslash between Skate 3 folder and PS3_DISC.SFB file.

For HDD games, it finds the game but seems to fall apart when trying to create llvm modules:
```
LLVM: Failed to create module file: D:/Emulaattori/RPCS3/cache/NPUB30051/ppu-UMeENWzxQ2JeUEYMu0F1C0SPz1tX-D:\Emulaattori\RPCS3\dev_hdd0\game\NPUB30051\USRDIREBOOT.BIN/v5-kusa-WZNb4YM3dk1CRgTv8bVf2a-00000G-znver2.obj.gz (Invalid arguments)
```
The path start from beginning in middle of message.

**Comment by Darkhost1999** [comment]
Digital games still show
Dev_hdd0/game//USRDIR
1 too many /

**Comment by kd-11** [comment]
Closing as fixed by https://github.com/RPCS3/rpcs3/pull/11370

**Comment by MSuih** [comment]
Yes, seems to have fixed the issues

**Comment by DemetriussXVII** [comment]
I started facing the same issue as of the latest updates, my old games work fine but any new game I try whether it's a disc or PKG give me the exact same error.
