### ISSUE TITLE
Bug: Image resource files generated as folders in macOS

### ISSUE THREAD

**Issue by reece394** [RPCS3/rpcs3#11371]
## Quick summary
Image resources in ~/Library/Application Support/rpcs3/Icons/ui are generating as folders and not .png files like they should be
## Details
Image resources in ~/Library/Application Support/rpcs3/Icons/ui are generating as folders and not .png files like they should be resulting in console logs of E RSX: Image resource file `/Users/reece/Library/Application Support/rpcs3/Icons/ui/fade_top.png' not found
#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7863818/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
N/A

#### 3. Please attach screenshots of your problem.
**Currently looks like:**
<img width="1032" alt="Screenshot 2022-01-13 at 15 18 24" src="https://user-images.githubusercontent.com/31659691/149357663-bc8ea3e7-ab07-451b-8b85-59c3482d34b9.png">

**Should look like: (Files Taken From Windows Build)**
<img width="1032" alt="Screenshot 2022-01-13 at 15 24 25" src="https://user-images.githubusercontent.com/31659691/149358414-cccd06f5-db24-4de7-8b16-358cb7cc94ef.png">

#### 4. Please provide comparison with real PS3.
N/A

#### 5. Please provide your system configuration:
*OS macOS 12.1 Monterey
*CPU Apple M1 Max 10 Core
*GPU Apple M1 Max 32 Core
*RAM/GPU Memory 32GB (Shared)
*Driver version 0.2.890

**Comment by MSuih** [comment]
Should be fixed after #11444 if you just delete the current folders and launch rpcs3. Ask for this to be reopened if the issue persists.

**Comment by reece394** [comment]
Confirmed that #11444 fixes this issue for macOS as well
<img width="1032" alt="Screenshot 2022-01-27 at 12 20 04" src="https://user-images.githubusercontent.com/31659691/151357699-ae401de0-3bd2-4619-b7a9-3f1fbcffe8ea.png">
