### ISSUE TITLE
Arch Linux, build issues. 

### ISSUE THREAD

**Issue by Tombert** [RPCS3/rpcs3#1137]
Hello!  

When trying to build this, I initially get an error saying 

```
Library `jit' not found in list of llvm libraries.
```

I was able to resolve this by changed the installed `llvm` with `llvm35`, but now I get a different error: 

```
CMakeFiles/rpcs3.dir/build.make:6281: recipe for target 'CMakeFiles/rpcs3.dir/Gui/MainFrame.cpp.o' failed
make[2]: *** [CMakeFiles/rpcs3.dir/Gui/MainFrame.cpp.o] Error 1
CMakeFiles/Makefile2:188: recipe for target 'CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [CMakeFiles/rpcs3.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
```

Any idea how to fix that?

**Comment by Bigpet** [comment]
I don't think your second log contains the actual error that happened, it just contains the messages that indicate that an error happened. What is the actual compilation error message?

**Comment by Tombert** [comment]
I copied out a bit more context from the error. 
http://hastebin.com/seduratibu.cs

**Comment by danilaml** [comment]
Does it still occur with latest commit?

**Comment by Tombert** [comment]
Hello! 

This is the error message I get now: 

```
[  0%] Generating something_that_never_exists
-- Found Git: /usr/bin/git (found version "2.4.5") 
[  0%] Built target GitVersion
Linking CXX executable /home/tombert/projects/rpcs3/bin/rpcs3
/usr/bin/ld: cannot find -lasmjit
collect2: error: ld returned 1 exit status
CMakeFiles/rpcs3.dir/build.make:7562: recipe for target '/home/tombert/projects/rpcs3/bin/rpcs3' failed
make[2]: *** [/home/tombert/projects/rpcs3/bin/rpcs3] Error 1
CMakeFiles/Makefile2:188: recipe for target 'CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [CMakeFiles/rpcs3.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by danilaml** [comment]
looks like problems with linking asmjit. Try answers from here http://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary

**Comment by kopiersperre** [comment]
@Tombert Could you solve the build issue?

**Comment by kurogetsusai** [comment]
I have a problem with asmjit too, on Ubuntu 15.04, but it looks like the asmjit header is missing.
```
[ 54%] Building CXX object CMakeFiles/rpcs3.dir/Emu/Cell/SPUASMJITRecompiler.cpp.o
/home/user/tmp/rpcs3/rpcs3/rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp:14:20: fatal error: asmjit.h: No such file or directory
 #include "asmjit.h"
                    ^
compilation terminated.
CMakeFiles/rpcs3.dir/build.make:6167: recipe for target 'CMakeFiles/rpcs3.dir/Emu/Cell/SPUASMJITRecompiler.cpp.o' failed
make[2]: *** [CMakeFiles/rpcs3.dir/Emu/Cell/SPUASMJITRecompiler.cpp.o] Error 1
CMakeFiles/Makefile2:188: recipe for target 'CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [CMakeFiles/rpcs3.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
```

Also I had to install these packages, which are not included in the dependencies section in README.md: libavcodec-ffmpeg-dev libavformat-ffmpeg-dev libswscale-ffmpeg-dev

**Comment by Bigpet** [comment]
@kurogetsusai did you forget to also pull the submodules?

**Comment by kurogetsusai** [comment]
Yeah, sorry, I forgot... Now it's better, but I cannot link the executable.
```
Linking CXX executable rpcs3
/usr/bin/ld: cannot find -lasmjit
collect2: error: ld returned 1 exit status
CMakeFiles/rpcs3.dir/build.make:8665: recipe for target 'rpcs3' failed
make[2]: *** [rpcs3] Error 1
CMakeFiles/Makefile2:188: recipe for target 'CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [CMakeFiles/rpcs3.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
```
It looks like it's the same problem as issue #705, but this time "cd rpcs3 && cmake CMakeLists.txt && make && cd ../" does not fix it.

You can see the log (from my stdin and stderr after running the command above), I don't see anything helpful there: https://gist.github.com/kurogetsusai/3db06a4faf95965506b1

**Comment by Aaahh** [comment]
Cd rpcs3 twice
Then run that stuff

**Comment by kurogetsusai** [comment]
Oh, twice instead of three times. Now everything works, thanks!
So I guess @Tombert did the same mistake, if he gets the same error.
