### ISSUE TITLE
rpcs3 crashes while building cache for NCAA 14

### ISSUE THREAD

**Issue by FrickParkRanger** [RPCS3/rpcs3#11374]
NCAA 14 was just downloaded and will not started properly. The game crashes while Building Cache. Generally completes 539 of 540 and then rpcs3 crashes. 

Can anyone help solve the issue? 

[RPCS3-2nd.txt](https://github.com/RPCS3/rpcs3/files/7866793/RPCS3-2nd.txt)

**Comment by RainbowCookie32** [comment]
Support is provided on [our Discord server](https://discord.me/RPCS3), not here. Close the issue and head to the help channel there (or just give up, NCAA 14 won't run well on an A10-5750M anyways)
