### ISSUE TITLE
[Feature Request] Streaming

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11376]
• Add the disable exclusive fullscreen optimization setting to the UI.
• Rename the setting while at it. By omitting the `disable` word.

![Screenshot_20220114-161124_Moonlight.png](https://user-images.githubusercontent.com/60384196/149592150-247e6210-10b9-4523-b4db-7a614b973d1a.png)

> **True should equal enabled**
> **False should equal disabled**

•How will it effect RPCS3?
UI

•Why is this setting important you may ask?

1. Reduces end user error.
2. Improves explaining to people in help how to stream
3. Adds clarity to the custom config for those who do not understand double negatives.

**Comment by lextra2** [comment]
Your title is very missleading. But I agree, adding a toggle for exclusive fullscreen mode to the UI would be useful.

**Comment by Megamouse** [comment]
There's a difference between forcing exclusivity and "force disabling" exclusivity.

As far as I can tell we don't actually enable/disable exclusive fullscreen.
I think the current "force disable" simply means that we prohibit the driver to use exclusive fullscreen.

So I don't think renaming the option would be correct.

(I don't claim that I'm an expert in this topic though, so I might be wrong)

**Comment by Darkhost1999** [comment]
Makes sense. If the implementation was in the GUI then people wouldn't be looking at the custom config and asking about double negatives.
This request was made while annoyed with #help.

**Comment by Megamouse** [comment]
It could probably be renamed to "Allow exclusive Fullscreen mode".
Don't know if that would be much better though 😉

**Comment by lextra2** [comment]
"Allow exclusive Fullscreen mode" sounds much better to me.

**Comment by kd-11** [comment]
Thing is, the driver is not required to ask us about it. Usually it will decide to go exclusive or not and we beg the driver to avoid doing it if possible. No guarantees are made about what will happen.

**Comment by MSuih** [comment]
The option should be expanded to allow force enabling as well, not just force disabling.

**Comment by Darkhost1999** [comment]
Adding this option to the UI also benefits https://github.com/RPCS3/rpcs3/issues/7975
Instead of being config only. So those with HDR displays and those who stream games are both receiving a user friendly addition to the user interface.
Where the name inside the config isn't as important as the setting in the UI should be Ticked= HDR/Streaming and unticked= Not HDR/Streaming
