### ISSUE TITLE
[Feature Request] Color logic for message log Tab to make it readable / meaningful for users

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#11384]
Hello,
i thing that Log tab should and could be much more readable for users. Its could be done by simple using some color logic:
- some info messages to make - black color
- some operations which are not just info - green
- errors - red and bold
-  warnings - red
  
 Is is now messega printed by some print something to log method, it could be simply overloaded.. by making some LogError, LogInfo, LogWarning methods.. or just by addtional message parameter - message typ.

  So far is log mess, all except initial information are red.. and for normal user is hard to identify if some message is good or bad.. to add color logic would be much better, user friendliness is half of success of some product.

**Comment by Megamouse** [comment]
I really don't know what this is supposed to mean, so I'll close

**Comment by ruthan** [comment]
Different colors for different types of message in Log Tab..

**Comment by RainbowCookie32** [comment]
Which RPCS3 already has?

**Comment by Darkhost1999** [comment]
> So far is log mess, all except initial information are red

Basically sounds like you're playing non-playable games.
Typically the colors go
-> green success
-> red error
-> purple fatal error
-> Yellow TODO

Right click your log:TTY 
![Screenshot_20220115-162101_Moonlight.png](https://user-images.githubusercontent.com/60384196/149639477-d6b48267-80ad-4488-9a8b-0f4f18d60903.png)
Ensure you didn't accidentally change this to the wrong one

**Comment by ruthan** [comment]
Im posting this based on my log all after initial initialization is red:
![image](https://user-images.githubusercontent.com/1702944/149639660-b138655a-e72a-46ff-8139-0b67904d22bf.png)

**Comment by RainbowCookie32** [comment]
Those are all errors, as the E and the color suggests. Seeing as you jump from the initial logged stuff to errors, you probably have some log channels muted somewhere, as there should be a bunch of green there (boot successful, cache loading, etc).

Not all errors mean "something went wrong, the game is broken". A function that tries to open a file can return an error for a non-existent file, but the games might actually expect and handle this error by creating/copying it.

It doesn't take away from the fact that the function returned an error though, and RPCS3 is printing it accordingly.
