### ISSUE TITLE
opengl crashs emulator in BLUS31319-[Hatsune Miku Project DIVA F]

### ISSUE THREAD

**Issue by annahana** [RPCS3/rpcs3#1138]
System :
windows 10
graphiccard AMD Radeon HD 6450
ram 4gb
cpu Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz

problem
if i run the game with opengl on the emulator shows a black window for 2 seconds with 4 frames per secound and crashs 
if i switsh to Null renderer the game boots up with no problems (i must change/delate the opening video file becaus it is not supportet at the moment)

i hope it is posible to corect the grapic problem 

change atachet rpcs3.png zu .7z
![hatsune miku rsx](https://cloud.githubusercontent.com/assets/13276505/8623041/4498b300-272f-11e5-8dfb-fbd57e0ffe24.PNG)
![rpcs3](https://cloud.githubusercontent.com/assets/13276505/8623057/6ca59854-272f-11e5-8ea7-8e48cab77016.png)

**Comment by tambry** [comment]
@annahana There's no log file anywhere with your issue to be found... Also, what's the error message from the supposed OpenGL crash? And yeah, it's a commercial and wont run for at least a couple more years without graphical glitches or crashes. I honestly don't see the problem, aside from your barely understandable grammar.

**Comment by annahana** [comment]
the log is in the picture beound the first picture and must be saveed on the pc and the ending .png must be changet to .7z

made it because the log is 60 mb

**Comment by tambry** [comment]
@annahana I can't see any OpenGL errors in there. It doesn't even seem to crash, but instead seems to be closed by the user. It doesn't seem to display things right and work properly, like almost any other commercial game. Makes me doubt if you actually read the (FAQ)[https://github.com/RPCS3/rpcs3/wiki/FAQ]

**Comment by annahana** [comment]
in the .7z packag ar 2 logs on with gl and on without the smal is with gl


![crash](https://cloud.githubusercontent.com/assets/13276505/8632993/ef3049ce-27b4-11e5-8833-a31fa5d45a09.PNG)

**Comment by tambry** [comment]
@annahana RSX should be emulated always and obviously RSX emulation isn't perfect and I would be suprised why you would ever want to run it without RSX emulation (aka null renderer). Not exactly sure why we even have a null renderer, but I guess there's a reason.

**Comment by annahana** [comment]
just navigate to the music room and play them in the game would be cool for the moment.
rsx is real slow. without rsx music plays in full spead, that would be good in music gams that nead no slowdown and i know the buttons combi to play.  but there is no way to navigate witout a window for the game. software renderer would be good for that with renderer change in games.

**Comment by annahana** [comment]
in Newest build the game runs without crashs
