### ISSUE TITLE
White Knight Chronicles™ [BCES00225] constantly crashes with various RSX errors.

### ISSUE THREAD

**Issue by Gael2433** [RPCS3/rpcs3#11383]
Please see the comment for additional information.
Original report:
## Quick summary
White Knight Chronicles™ [BCES00225] crashes at random during gameplay with always the same RSX error.

## Details
White Knight Chronicles™ [BCES00225] crashes during gameplay with the following RSX error:

`Unknown magnify filter 0x0
(in file D:\a\1\s\rpcs3\Emu\RSX\gcm_enums.cpp:872[:22], in function to_texture_magnify_filter)`

#### 0. Make sure you're running with settings as close to default as possible
Default emulator settings with a fresh rpcs3 install and newly dumped disc thats been validated with PS3 ISO Rebuilder.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7875697/RPCS3.log)
Log can also be found here on the rpcs3 discord server:
https://discord.com/channels/272035812277878785/319224795785068545/931986738119839774

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
N/A

#### 3. Please attach screenshots of your problem.
N/A

#### 4. Please provide comparison with real PS3.
The game does not randomly crash on a real ps3.

#### 5. Please provide your system configuration:
Rpcs3-v0.0.20-13182-df24cff0
Microsoft Windows 10 Version 21H1
Intel Core i7-3770
Nvidia Geforce GTX 1070 running on driver 511.23.0.0
16Gb DDR3 RAM 1333Mhz

#### Please include.
* Anything else you deem to be important

Installing the game update has no effect and the issue still persists.

I have had this same error occur on Ni no Kuni: Wrath of the White Witch [BLES01555] which is a later title by the same developer, however I have not played the game that much to confirm if it also happens constantly there.

PS3 Iso Rebuilder result:
![BCES00225_rebuilder](https://user-images.githubusercontent.com/69867624/149634822-e9711e12-5da9-46e0-ab52-3a9f110b1e82.png)

**Comment by Gael2433** [comment]
Did some testing with Write Color Buffers enabled and it lasted much longer, this time crashing with a different error:
`Unknown surface antialiasing format 0x1
(in file D:\a\1\s\rpcs3\Emu\RSX\gcm_enums.cpp:908[:22], in function to_surface_antialiasing)`
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7876829/RPCS3.log)
https://discord.com/channels/272035812277878785/319224795785068545/932231783876005929

**Comment by kd-11** [comment]
Just increase your driver wakeup delay, this is a sign of game memory getting corrupted probably due to threads going out of sync.

**Comment by Gael2433** [comment]
Increasing driver wakeup delay seems to solve the problem

**Comment by bnthomason** [comment]
Increasing driver wakeup delay does seem to delay, not fix the problem. This freezing happens in both WKC 2 and WKC

**Comment by audiowylde2345** [comment]
Is this still an issue? A lot of what I found is from years ago
