### ISSUE TITLE
Dark Sector: exception with sin_vport = 0

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#11395]
This issue is present on Dark Sector Demo, and most likely also on the full game.

The game calls sys_net_bnet_bind with SYS_NET_SOCK_DGRAM_P2P.
The sin_vport is 0, so currently we throw an exception.

According to spec 0 is not supposed to be used as vport, so it should probably either return an error or default to 3658.
This needs to be tested on hardware.

Anyway, doing either of the above lets me go ingame in the demo.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7884911/RPCS3.log)

**Comment by Darkhost1999** [comment]
Getting ingame would close this issue. Interesting discovery.
https://github.com/RPCS3/rpcs3/issues/11273

**Comment by Megamouse** [comment]
nah. that issue comes way later and is not present in the demo.

**Comment by Megamouse** [comment]
fixed
