### ISSUE TITLE
Watch Dogs - Strange vertical stripes when upscaling

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#11398]
## Quick summary
When the Resolution Scale for Watch Dogs is set to anything higher than 100%, a strange stripe patterns appears.

## Details
When the Resolution Scale for Watch Dogs is set to anything higher than 100%, a strange pattern appears where vertical stripes cover the screen.  This is the only issue not fixed by PR 11381.  This seems to be a distance-based effect as it seems to follow the skybox kinda, looking straight down makes it disappear, and slowly looking back up makes it creep back onto the screen.  I messed around with Resolution Scale Threshold to no avail.  No other upscaling-related issues occur in this game.

#### 1. Please attach RPCS3's log.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7885752/RPCS3.log)

#### 3. Please attach screenshots of your problem.

![1](https://user-images.githubusercontent.com/58268914/149860744-1748be72-065c-4dec-9693-fa63901be938.PNG)
![2](https://user-images.githubusercontent.com/58268914/149860755-090aa7cc-9b8a-4f28-af83-899058d3aec5.PNG)

#### 4. Please provide comparison with real PS3.

Real hardware can't reach higher than native resolution so this can't be used as a comparison.

#### 5. Please provide your system configuration:
* OS: Windows 10 x64 Build 19043
* CPU: Intel Core i9-10900K
* GPU: NVIDIA RTX 2080 Super
* Driver version:  497.29

**Comment by kd-11** [comment]
Closing. Resolution upscaling is an enhancement and may not go over well with all titles. If there is no bug at native resolution then we do not track upscaling artifacts as bugs unless it is a regression.
