### ISSUE TITLE
Game Window Title customization doesn't work

### ISSUE THREAD

**Issue by domportera** [RPCS3/rpcs3#11393]
## Quick summary
Hand-editing the Game Window Title in Settings -> Emulator doesn't alter the game window title

## Details
I tried changing it to this:
%T [%t] | FPS: %F | %R | %V

Basically, just moving the title to the front

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 3. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/6530600/149743994-b675f241-89c8-4960-833a-1abffbbd7f7f.png)

#### 5. Please provide your system configuration:
* OS - Windows 10
* CPU - Ryzen 7 5800x
* GPU - RTX 2070

**Comment by YuriNator557** [comment]
Missing log
If you have a custom config, please ensure it has been changed on that as well

**Comment by Megamouse** [comment]
cannot reproduce.
the user is probably using a custom config

**Comment by domportera** [comment]
i had since restarted my emulator and so the log was empty
i DO have a custom config for this game, totally my bad. sorry!
