### ISSUE TITLE
Bug: Texture flickering/Artifacting on GoldenEye 007: Reloaded [NPUB30752] on macOS Vulkan/MoltenVK

### ISSUE THREAD

**Issue by reece394** [RPCS3/rpcs3#11400]
## Details
Textures are flickering heavily when in the first training area. Walls are becoming see-through at certain angles and the gun is clipping through the characters hands.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7890432/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
[NPUB30752_20220118154543_capture.rrc.zip](https://github.com/RPCS3/rpcs3/files/7890436/NPUB30752_20220118154543_capture.rrc.zip)

#### 3. Please attach screenshots of your problem.

https://user-images.githubusercontent.com/31659691/149971897-c70c64c9-0be5-40e0-8bd8-75929dd6f9a2.mp4

#### 4. Please provide comparison with real PS3.
Should display without artifacting 

#### 5. Please provide your system configuration:
* OS macOS 12.1 Monterey
* CPU Apple M1 Max 10 Core
* GPU Apple M1 Max 32 Core
* RAM/GPU Memory 32GB (Shared)
* Driver version 0.2.890

#### Please include anything else you deem to be important
Has worked for other users with different system configurations [here](https://forums.rpcs3.net/thread-201343.html?highlight=NPUB30752),  [here](https://forums.rpcs3.net/thread-182369-page-2.html) and [here](https://www.youtube.com/watch?v=V9a3PdlUZcs)

**Comment by kd-11** [comment]
Let's track moltenvk bugs in https://github.com/RPCS3/rpcs3/issues/11414
If the issue is not present on other platforms, it belongs on the mac-only tracker.

**Comment by NanoFlowGaming** [comment]
Been 2 years, and bug still hasn't been fixed. It's probably due to MoltenVK though so it's understandable.
