### ISSUE TITLE
MK vs DC Universe (black screen)

### ISSUE THREAD

**Issue by Sunderland93** [RPCS3/rpcs3#11407]
## Quick summary
After compiling all PPU Modules, game is not started. Only black screen

## Details

The log contains this error: `F {PPU[0x1000000] Thread (main_thread) [0x00035df4]} VM: Access violation writing location 0x0 (unmapped memory)`

#### 1. Please attach RPCS3's log.
Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7899524/RPCS3.log)

#### 5. Please provide your system configuration:
* OS: Debian 11
* CPU: AMD Ryzen 5 3600
* GPU: AMD Radeon RX570 4G
* Driver version: Mesa 20.3.5
* Linux: 5.10

**Comment by AniLeo** [comment]
Broken pirated dump, closing as invalid
