### ISSUE TITLE
 a software that will make finding compatability problems 500x possibly more quick

### ISSUE THREAD

**Issue by exaltedkiller** [RPCS3/rpcs3#11405]
## Please do not ask for help or report compatibility regressions here, use [RPCS3 Discord server](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/) instead.

the name of the software is cheat engine
cheat engine lets you change the game speed from 2x to 500x more quick in the game
pretend the game is 12 hours long
pretend you change the speed to 30x 
you will be able to complete the game in 24 minutes
hack your health with cheat engine to try to dont die in the game
change the game speed movee in the game till you find a compatablity problem
save the game and exit cheat engine and exit the game so all the original game software structure goes back to its original state
 start the game again to the saved game now you at the compatablity problem with original software structure

you work 8 hours a day(pretend every game is 12 hours long) you will be able to complete 20 games a day
you will be able to complete 600 games in 30 days, in 2 mounths 1200 games will be completed

you emulator creator tell me if you will try this or anybody that knows how to fix game compatablity problems

download link for cheat engine
https://cheat-engine.en.uptodown.com/windows

## Quick summary
Please briefly describe what is not working correctly.

## Details

Please describe the problem as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
* Run the game until you find the issue.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc.
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 5. Please provide your system configuration:
* OS
* CPU
* GPU
* Driver version
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by YuriNator557** [comment]
this report assumes you can even run some games faster than full speed

invalid

**Comment by MSuih** [comment]
There are severial shortcomings with this approach and I don't want to waste anyones time discussing them on a github issue. Feel free to join our Discord instead.

**Comment by exaltedkiller** [comment]
tell me the negatives to this idea

**Comment by Margen67** [comment]
> tell me the negatives to this idea

Here are a few:
https://github.com/mborgerson/xemu/issues/662
https://github.com/RPCS3/rpcs3/issues/11405
https://github.com/Vita3K/Vita3K/issues/1589
https://github.com/xenia-project/game-compatibility/issues/1902
https://github.com/xenia-project/game-compatibility/issues/1903
https://github.com/xenia-project/game-compatibility/issues/1864
https://github.com/xenia-project/game-compatibility/issues/1863
https://github.com/xenia-project/game-compatibility/issues/1862

**Comment by alyssakeik** [comment]
> > tell me the negatives to this idea
> 
> [mborgerson/xemu#662](https://github.com/mborgerson/xemu/issues/662) #11405 [Vita3K/Vita3K#1589](https://github.com/Vita3K/Vita3K/issues/1589) [xenia-project/game-compatibility#1902](https://github.com/xenia-project/game-compatibility/issues/1902) [xenia-project/game-compatibility#1903](https://github.com/xenia-project/game-compatibility/issues/1903) [xenia-project/game-compatibility#1864](https://github.com/xenia-project/game-compatibility/issues/1864) [xenia-project/game-compatibility#1863](https://github.com/xenia-project/game-compatibility/issues/1863) [xenia-project/game-compatibility#1862](https://github.com/xenia-project/game-compatibility/issues/1862)
