### ISSUE TITLE
simd.hpp vec_alloc verification failed since #11403 (Rosetta)

### ISSUE THREAD

**Issue by nastys** [RPCS3/rpcs3#11409]
## Quick summary
Since #11403, launching any game results in:
```
RPCS3: SIG: Thread terminated due to fatal error: Verification failed
(in file /private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/rpcs3/util/simd.hpp:120[:4], in function vec_alloc) (errno=2)
RPCS3: profiler: cpu_thread::flush_profilers() has been called incorrectly.
RPCS3: Verification failed
(in file /private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/rpcs3/util/simd.hpp:120[:4], in function vec_alloc) (errno=2)
```

## Details
This seems to affect M1 Macs running RPCS3 with Rosetta. It doesn't seem to affect Intel Macs.
Commenting out line 120 ``ensure(~vec_allocated);`` results in an error at line 373 ``ensure(!g_vc->emit(op, r, std::forward<Args>(args)...));``, and removing the ensure around that line fixes the issue and RPCS3 is able to launch games.
I've also tried deleting ``Caches/rpcs3`` and ``Application Support/rpcs3``.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
https://cirrus-ci.com/task/5042319962406912

#### 2. Please attach TWO logs:
* One for the build with regression.
* One for the build that works as expected.

[RPCS3_broken.log](https://github.com/RPCS3/rpcs3/files/7901543/RPCS3_broken.log)

[RPCS3_noensure.log](https://github.com/RPCS3/rpcs3/files/7901565/RPCS3_noensure.log)

#### 6. Please provide your system configuration:
* OS macOS 12.1
* CPU Apple M1
* GPU 7-core
* Driver version
* etc.

**Comment by Nekotekina** [comment]
What's the CPUID of VirtualApple btw? Can't find what capabilities it supports.

**Comment by Red1860** [comment]
Still getting the error when opening any game in the latest commit:
https://github.com/RPCS3/rpcs3/commit/d572d90bb751acc76576ebfa783c27aa0186d95c

**Comment by MSuih** [comment]
Are you sure you're on latest commit @Red1860? There is no verification in line 120 anymore so your error should be impossible to trigger.

**Comment by Red1860** [comment]
@MSuih hi, yes I am trying the latest commit however I didn't build it myself. I downloaded the macOS version from [here](https://cirrus-ci.com/task/6651966599200768)

**Comment by dalnew** [comment]
> @MSuih hi, yes I am trying the latest commit however I didn't build it myself. I downloaded the macOS version from [here](https://cirrus-ci.com/task/6651966599200768)

I tried the same build which says it includes this fix but I'm still seeing the same error. I tried removing the rpcs3 cache, is there some other reset that needs to happen?

**Comment by Nekotekina** [comment]
Very strange, it should be fixed in master.

**Comment by MSuih** [comment]
If this is still `simd.hpp:120[:4]` error then the build you've downloaded doesn't have the update, possibly because of some ccache configuration error for mac builds. We'd need a confirmation from someone who can compile it for themselves.

If the error message points to some different line or file then you'll need to tell which one it is.

**Comment by Red1860** [comment]
So I was trying to build it from source but I am getting this error

```
-- Could NOT find Qt5 (missing: Qt5_DIR)
CMake Warning at 3rdparty/qt5.cmake:10 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.15.2) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:48 (include)
```

**Comment by MSuih** [comment]
Building rpcs3 on mac isn't straightforward, there's a bunch of things that need to be done (including setting up and using x86-64 homebrew applications instead of the native ones). We don't have official build instructions yet, they will be added in future once things stabilize a bit. #11222 contains some vague instructions but some parts of it are out of date already.

**Comment by nastys** [comment]
I've built master but now I get this error:
```
RPCS3: SIG: Thread terminated due to fatal error: Verification failed
(in file /Users/nastys/fork/rpcs3/rpcs3/util/simd.hpp:378[:6], in function unary_op) (errno=2)
RPCS3: profiler: cpu_thread::flush_profilers() has been called incorrectly.
RPCS3: Verification failed
(in file /Users/nastys/fork/rpcs3/rpcs3/util/simd.hpp:378[:6], in function unary_op) (errno=2)
```

**Comment by nastys** [comment]
> What's the CPUID of VirtualApple btw? Can't find what capabilities it supports.

> FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTSE64 MON DSCPL VMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 AES SEGLIM64

**Comment by Nekotekina** [comment]
Thanks, I fixed bug

**Comment by nastys** [comment]
Yep, #11413 fixes it. Thanks!
