### ISSUE TITLE
Face Gui Options Don't Save

### ISSUE THREAD

**Issue by shinra358** [RPCS3/rpcs3#11417]
Win10 21h2
When choosing to not view things by unchecking them in the gui like logs in the bottom gui window, or setting the icon size and row amount, and even whether you left the emu maximized, those particular settings do not carry over when you exit the emu and restart it. It reverts back to the default viewing settings.

**Comment by Megamouse** [comment]
no log provided

**Comment by shinra358** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7908126/RPCS3.log)

After tinkering around it said I had an update today from the version I had 2 days ago.
After installing, same thing but I got those settings to finally save only by initiating rpcs3 in administrator mode. Then those settings saved. They don't seem to save if you aren't in admin mode.

**Comment by Megamouse** [comment]
We can't control how you manage your file permissions on your operating system.
This is clearly an issue on your side. Sorry.
Please look for help on our discord

**Comment by shinra358** [comment]
This is not an issue on my side. This is a default setup. None of my permissions are tinkered with and this is a brand new system i just got. You should integrate admin to be automatically activated in the exe if the program doesn't function correctly without it. No other emu has this problem and I'm also playing on an external drive so it is not in a system folder.

**Comment by shinra358** [comment]
I literally had to go and check run in admin mode for the exe. I should not have to do that as a user.

**Comment by RainbowCookie32** [comment]
If you have to run RPCS3 as admin to avoid an issue, then there's a problem on your side. 99.9% of the users run RPCS3 just fine as a normal users, with the 0.1% remaining ones being the ones that extract RPCS3 to some weird place or have some other permissions issue

**Comment by shinra358** [comment]
this is a FRESH install. i just got this system. there is no problem on my side and no other emu i have to do this with. what the....

**Comment by Megamouse** [comment]
just try and find out if:
- your windows user settings are weird.
- your folder permissions are weird (probably the whole root directory)
- you might have unpacked the data with admin permissions
- whatever other weird issue one might have
