### ISSUE TITLE
BioShock 2 [NPUB30392]: Freezes in OpenGL

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#11418]
## Quick summary

Freezes while ingame. Freezing can occur anywhere from 0-15 minutes into gameplay and seems to occur no matter where the player is in the game.

## Details

This was determined not to be related to #11391 as the issue was specific to Vulkan.

The following excerpt from the log posted below suggests this is related to shader compilation shading:

`·E 0:10:08.753547 SIG: Thread [rsx::thread] is too sleepy. Waiting for it 18130.508µs already!
`

During this test, the attempt to go ingame from the main menu only resulted in a black screen with "Compiling Shaders..." appearing in the bottom-left.

Note that this issue may occur with other titles as well, though this hasn't been confirmed.

## System configuration

* OS: Linux Mint 20.3 / kernel 5.13
* CPU: Intel i7-10870H
* GPU: NVidia GTX 3070
* Driver version: 495.46
* Commit tested: 3942a464fe6f09bd964b37f98e49f1d5af826886
* Logfile: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7909944/RPCS3.log.gz)

**Comment by kd-11** [comment]
I was unable to reproduce on windows, driver 511, GTX 1050 Ti.
This may be a linux thing? I'll test it out later, though my GPU cannot run under linux due to novideo messiness. I'll try with radeonsi instead.

**Comment by kd-11** [comment]
Similar report: https://github.com/RPCS3/rpcs3/issues/11309

**Comment by kd-11** [comment]
I retested this. No crash observed using linux + Radeon mesa drivers after 30 minutes of idling around the starting area. Graphics glitches, but no crash.

**Comment by Darkhost1999** [comment]
I get crashing trying to continue my game on OpenGL. Vulkan is fine.

https://user-images.githubusercontent.com/60384196/170150973-c4235eaa-72d7-4af3-a262-52197a0198ce.mp4

Both logs have the issue was just testing resolution scale
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8766930/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8766951/RPCS3.log)

Savedata
[BLUS30420-20220329_081235.zip](https://github.com/RPCS3/rpcs3/files/8766964/BLUS30420-20220329_081235.zip)
Hope this helps

**Comment by kd-11** [comment]
@Darkhost1999 Can you still reproduce? I've been using this game to test the OpenGL updates and it works great on my end with current master.

**Comment by Darkhost1999** [comment]
Works on my macine. I really like this part. Telekinesis
![image](https://user-images.githubusercontent.com/60384196/192400993-fc7881c4-c0b2-4e4c-991a-81fa7ca1cd92.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9650344/RPCS3.log)
Performance is sub optimal but it working is what matters

**Comment by MSuih** [comment]
I think we can mark this as fixed for now for now. If someone can still trigger this then the issue can be reopened.
