### ISSUE TITLE
LLVM is broken with latest merges + no sound in sonic CD

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1141]
With these merges :
3aefa2b4e19b612cb81a2fe25c9d914a88601d01
aad293df1a64fc6d87249ec882b6bcabba2d6db4
b08c3186befb43d5703e3e69ff85c3a29241ac09

in all game I can test llvm can't boot the game anymore (work fine with ppu interpreter 2).
There is also no more sound/music in Sonic CD.

**Comment by danilaml** [comment]
There is sound in Sonic CD for me, although I managed to get "no sound" situation playing with settings but it fixed itself after I restarted emu (not the game).

**Comment by vlj** [comment]
Fixed
