### ISSUE TITLE
LittleBigPlanet [NPEA00241] closes after compiling on 1.30 update

### ISSUE THREAD

**Issue by Culeradi** [RPCS3/rpcs3#11419]
The game window closes after compiling. This only occurs on 1.30 update, as older updates start the game.

https://user-images.githubusercontent.com/82603798/150526195-ef14288c-ef4d-46d9-86ed-b38b785b0361.mp4

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7913490/RPCS3.log)

**Comment by MSuih** [comment]
Did you remember install all updates up to 1.30 in correct order? That often happens when some updates have been skipped.

**Comment by Culeradi** [comment]
The game was already on 1.20 so I assumed it isn't requiered, but sure I can check out if it'll fix it.

**Comment by Culeradi** [comment]
Hey thanks, that seems to fix the issue. I thought that the updates for LBP were 1.20 and 1.30, turns out there are some between (1.25, 1.26 1.27 etc.).

**Comment by Alfonz101** [comment]
where can I get the update files?

**Comment by Darkhost1999** [comment]
> where can I get the update files?

Recommended to join the discord and use the RPCS3 discord bot. Basically game updates come directly from Sony's servers and we have a convenient bot setup to connect to the bot to provide users with game update files for their games. You can also dump the files from your ps3.

**Comment by mrwallace888** [comment]
I have this issue myself on LBP GOTY (US), but even after updating all 11 updates in order to 1.30, it still does it. I tried using default settings and turned on Write Color Buffer on the wiki and it hasn't changed anything.
