### ISSUE TITLE
[Feature Request] SPU Instructions Accuracy Levels.

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#11420]
After testing a lot of games and talking to whatcookie, most of the titles are fine with having just FCGT + FNMS accuracy set to approximate while the rest being innacurate (approximate float set to false), which improves performance. 

With that being said, we agreed that it could be a good idea to have accuracy options just like ZCull Accuracy. The way it would work is exactly like Zcull Accuracy options does. Three Levels of accuracy with a drop like this:

1- Precise - Accurate Xfloat (nothing changes here)
2- Approximate (default) - The current approximate float we have as default. (nothing changes here)
3- Relaxed (New) - All the instructions are "innacurate" except FCGT + FNMS  which should be set to approximate.

This improves performance in some titles, unifies some settings into one and encourages (even if very little) users to not directly fiddle with the config file.

**Comment by Nekotekina** [comment]
I think it can be done but I'd prefer to keep approximate switch separate for a different reason.

**Comment by Yahfz** [comment]
We won't change anything in Accurate Xfloat or Approximate float they'll be kept as is. All we are doing is adding another option called "Relaxed Float" (or whatever we decide its best), which has approximate float disabled for all instructions except FCGT and FNMS. Unless you're talking about something else?

**Comment by Nekotekina** [comment]
That's a cosmetic issue of keeping two check boxes for accurate/approximate options, not really important.

**Comment by Xcedf** [comment]
FCGT+FNMS only still good speedup for GoW3

**Comment by kd-11** [comment]
This was a discussion that led to creation of many hacked builds a few years ago. Maybe we can get a comparison table of sorts using the base recommended spec ( r5 3600 I believe)

**Comment by Augusto7743** [comment]
Is possible test current version using xfloat "Relaxed" setting ?

**Comment by Yahfz** [comment]
> Is possible test current version using xfloat "Relaxed" setting ?

No. You'd need a custom build for that.

**Comment by Augusto7743** [comment]
Where is a custom build for download using current version ?
xfloat relaxed will be added in main build ?

**Comment by Whatcookie** [comment]
You can test relaxed xfloat using https://github.com/RPCS3/rpcs3/pull/11461
