### ISSUE TITLE
RPCS3 fails to run using Vulkan with Intel Iris Xe on Linux 

### ISSUE THREAD

**Issue by ruineka** [RPCS3/rpcs3#11423]
## Quick summary
I am unable to use RPCS3 using Vulkan when using Intel Iris Xe graphics on Linux.

## Details

I get this error when attempting to run a game using the Vulkan API
` ../src/intel/vulkan/anv_image.c:528: add_aux_surface_if_supported: Assertion !(image->vk.usage & VK_IMAGE_USAGE_STORAGE_BIT)' failed.`

Please describe the problem as accurately as possible.

HDR is not supported on Linux and there should be a check to avoid trying to use VK_IMAGE_USAGE_STORAGE_BIT on Linux. From what I gather it's reporting that it's supported when in reality it is not. When doing research I found this https://gitlab.freedesktop.org/mesa/mesa/-/issues/178

**Comment by kd-11** [comment]
MSAA does not work properly on linux hardware. Just set to disabled in GPU settings instead of auto

**Comment by ruineka** [comment]
> MSAA does not work properly on linux hardware. Just set to disabled in GPU settings instead of auto

I switched Anti-Aliasing to off (Emulate PS3 multisampling layout) and tested Vulkan again and it crashes with the same VK_IMAGE_USAGE_SHORTAGE_BIT failed error. ![PXL_20220122_073103126.jpg](https://user-images.githubusercontent.com/16360335/150629388-14da8abf-d512-4b62-8a78-cf82fa62d652.jpg)

**Comment by kd-11** [comment]
Are you maybe using a custom config for the game?

**Comment by ruineka** [comment]
> Are you maybe using a custom config for the game?

I was, I changed the settings in the custom settings and the global and it was the same. I just tried removing the config all together to see if it changed anything and it's still not working.

**Comment by ruineka** [comment]
I tested a much older build of RPCS3 v0.0.14-11603 and Vulkan is working with MSAA disabled.

**Comment by ruineka** [comment]
I went through all the builds to find when things broke on Intel.

Build v0.0.17-12645-47e784d5 (Works)
Build v0.0.17-12646-8848dc66 (Does not work)

All builds after v0.0.17-12646-8848dc66 do not work.

**Comment by kd-11** [comment]
I know what breaks it, will revert. This will reintroduce graphics artifacting though, the forcing of the storage bit is there to work around some problems which are not possible to solve without using 'strict mode' .

**Comment by ruineka** [comment]
> I know what breaks it, will revert. This will reintroduce graphics artifacting though, the forcing of the storage bit is there to work around some problems which are not possible to solve without using 'strict mode' .

Gotcha, I'm assuming this either used to work with older versions of Mesa or non Iris Xe hardware? I almost wonder if this should be a toggle for people who don't experience crashing when using storage bit.

**Comment by kd-11** [comment]
> > I know what breaks it, will revert. This will reintroduce graphics artifacting though, the forcing of the storage bit is there to work around some problems which are not possible to solve without using 'strict mode' .
> 
> Gotcha, I'm assuming this either used to work with older versions of Mesa or non Iris Xe hardware? I almost wonder if this should be a toggle for people who don't experience crashing when using storage bit.

After looking at the Xe capabilities chart, I think its not all formats that have this problem, only some of them.
As a compromise I have made it so that we only apply the workaround when the driver reports that it will allow it.
https://github.com/RPCS3/rpcs3/pull/11424

**Comment by ruineka** [comment]
> > > I know what breaks it, will revert. This will reintroduce graphics artifacting though, the forcing of the storage bit is there to work around some problems which are not possible to solve without using 'strict mode' .
> > 
> > Gotcha, I'm assuming this either used to work with older versions of Mesa or non Iris Xe hardware? I almost wonder if this should be a toggle for people who don't experience crashing when using storage bit.
> 
> After looking at the Xe capabilities chart, I think its not all formats that have this problem, only some of them.
> As a compromise I have made it so that we only apply the workaround when the driver reports that it will allow it.
> https://github.com/RPCS3/rpcs3/pull/11424

This fixes the crashing but it did introduce graphical fuzz to the game that was not present in versions prior to the commit that causes the crashing. Enabling "Strict rendering mode" and "Write Color Buffers" does not correct this.

![PXL_20220122_185231063.jpg](https://user-images.githubusercontent.com/16360335/150651682-59295a7e-a3c7-4aa0-afc2-3df45acb733e.jpg)

![PXL_20220122_185019371.jpg](https://user-images.githubusercontent.com/16360335/150651685-c6efb095-44e5-406f-9535-9a9d00882fa9.jpg)

**Comment by AniLeo** [comment]
Nothing we can do, need to wait for the VK_VALVE_attachment_feedback_loop_layout extension to be accepted on spec and implemented by ANV

**Comment by ruineka** [comment]
> Nothing we can do, need to wait for the VK_VALVE_attachment_feedback_loop_layout extension to be accepted on spec and implemented by ANV

Good to know I'll put the request in to show that there is a need. Thanks.

**Comment by AniLeo** [comment]
The DCC issue won't happen with SRM so you're hitting the bug I linked above instead, test with Mesa 21.2 and it shouldn't happen if you want to be sure.

**Comment by ruineka** [comment]
> The DCC issue won't happen with SRM so you're hitting the bug I linked above instead, test with Mesa 21.2 and it shouldn't happen if you want to be sure.

Alright I'll check this out and make sure. You might already be aware of this, but I'm finding that the Windows build performance is drastically better than the Linux one (at least on Intel).

**Comment by AniLeo** [comment]
Even though iris is usually better in RPCS3, anv's performance is not that bad, something else is wrong, can't tell what, the linux drivers are faster than the Windows ones, at least in pre Xe hardware.

**Comment by ruineka** [comment]
> Even though iris is usually better in RPCS3, anv's performance is not that bad, something else is wrong, can't tell what, the linux drivers are faster than the Windows ones, at least in pre Xe hardware.

Interesting, I'll continue to try and figure out the root cause for this. Normally I have found ANV to be exceptional with performance so I'm rather shocked to see it being so poor using RPCS3 at the moment.

**Comment by kd-11** [comment]
I just checked intel state on my laptop and ANV is completely broken. It has artifacts all over and is very slow. OpenGL works fine though (Iris driver). I'm using a UHD 620 on a KabyLake-R CPU. Something broke either on our side or their side, not sure. Obviously the other GPUs are fine, NV and AMD render fine with and without MSAA.
