### ISSUE TITLE
[Feature Request] Decrypt and Dump Running Executable

### ISSUE THREAD

**Issue by illusion0001** [RPCS3/rpcs3#11428]
Sometimes finding klic for encrypted elf is difficult (i.e The Orange Box updates)

**Comment by clienthax** [comment]
Isn't this what Utilities -> Decrypt PS3 Binaries already does?

**Comment by illusion0001** [comment]
Nada. Attempt to decrypt when elf is running `E GUI: Failed to decrypt "C:/rpcs3-ugh/dev_hdd0/game/BLUS30055/USRDIR/BIN/TF.SELF".`
Attempt to decrypt when it's not running
![](https://cdn.discordapp.com/attachments/930763884363644938/932207615755321364/unknown.png)

**Comment by elad335** [comment]
Have you actually succeeded decrypting after entering the KLIC?

**Comment by elad335** [comment]
Plus no log no slog!

**Comment by illusion0001** [comment]
> Have you actually succeeded decrypting after entering the KLIC?

I don't know the klic for this title, and it's disc game with encrypted elf with update installed

> Plus no log no slog!

Oop.  [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7921325/RPCS3.log.gz)

**Comment by elad335** [comment]
Perhaps it's already decrypted?

**Comment by illusion0001** [comment]
EA seem to encrypt elfs with klic for whatever reason on a disc game update. Haven't check the binaries on disc.

**Comment by Gael2433** [comment]
Would be nice to have a debug option to dump klic as they are used.

**Comment by illusion0001** [comment]
Webman has an option for this yea

**Comment by illusion0001** [comment]
`MGS4.SELF` is encrypted on disc 2.00 update.
