### ISSUE TITLE
[BLES00246] Metal Gear Solid 4: Stuck compiling PPU modules

### ISSUE THREAD

**Issue by IngwiePhoenix** [RPCS3/rpcs3#11439]
## Quick summary
Can not get in-game, stuck at compiling PPU caches. Let it run for a good forever and this is what I see now:

![image](https://user-images.githubusercontent.com/2893716/150854644-cdd946f1-9834-4e76-8aea-c408710e4eff.png)

All I see in the log (log level set to TODO) is the phdr error.

I should note, this is an older dump, but considering that the PPU cache keeps trying to grow bigger and bigger, I thought I'd report it anyway. But my dump might also be damaged (rescued from an old HDD).

## Details

After adding the game from it's dump folder, I tried to start it by using the default settings. And that is how I saw the PPU cache screen - and, increasing from time over time. I left it running while watching Youtube, and you see the result above. (It's still running. I am curious what happens when the bar grows full.)

The only error message I see is:

```
E ppu_loader: Unknown phdr type (0x00000007) x40
```

My thought is, that once the defective header is found, the rebuild begins anew over and over, effectively being stuck in a sort-of infinite loop. The increase of new objects to be cached seems to be 134. Other messages in the log are only success messages.

After closing the game window, I got this error dialog:
![image](https://user-images.githubusercontent.com/2893716/150856445-c2db3e65-f69b-40c7-8b47-e6ca1c4949b2.png)

And with all that done, here is the log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7928543/RPCS3.log)

#### 5. Please provide your system configuration:
* OS: Windows 10
* CPU: AMD Ryzen 9 3900X
* GPU: NVIDIA 2080 TI
* Driver version: 496.76.0.0 (reported as such in the log)
* RPCS3 version: 0.0.20-13224-59203729

**Comment by kd-11** [comment]
Unknown phdr type is harmless. Something else is going on. Renamed for better visibility.

**Comment by JesseTG** [comment]
This happens with me as well.

- OS: Windows 10
- CPU: AMD Ryzen Threadripper 2950X 16-Core Processor    3.50 GHz
- GPU: nVidia GeForce RTX 3060
- Driver version: 511.79
- RPCS3 version: 0.0.21-13350-04df3928 Alpha

No log yet because I'm trying to run the game now, and I'm about to leave to run some errands.

**Comment by JesseTG** [comment]
Ah ha! I don't know what the cause was, but the emulator finished compiling the shaders successfully. I let it run while I was out, so I don't know how long it took (I was gone for about two and a half hours).

**Comment by lKobi** [comment]
Still an issue, this game takes a long while to compile here, more than any other game, and seems the emulator has a useless timeout that halts the process...

**Comment by rainxh11** [comment]
![image](https://user-images.githubusercontent.com/35665161/210173391-601a7596-84b8-48f6-b460-dcfca0589b58.png)


Longest PPU Compilation ever experienced in RPCS3 and still going more than hour

**Comment by MSuih** [comment]
It it stuck, or is it just progressing slowly? MGS4 module compiling can take several hours on slower systems because of the *unique* way the game was built.

**Comment by xCENTx** [comment]
can confirm that it just takes some time. . took roughly 1hr 40 mins. I have a pretty decent PC as well

- Ryzen 5600x
- RTX 3060Ti
- 64GB @ 3600MHz
- 2TB 970EVO SSD (specific drive associated with RPCS3 & MGS4, boot drive is separate)

![image](https://github.com/RPCS3/rpcs3/assets/80198020/07320128-73d8-4533-9718-40c2812f6f46)

# RPCS3 CPU SETTINGS
- PPU Decoder: Recompiler (LLVM)
- SPU Decoder: Recompiler (LLVM)
- SPU XFloat Accuracy: Relaxed Float
- Additional Settings:
-- Enable SPU Loop Detection: TRUE

**Comment by elad335** [comment]
Not a bug, mgs4 just have lots of modules, if you do not want to compile them in one go then disable PPU LLVM Precompilation in Advanced tab.

**Comment by Graphicgamersx** [comment]
i had the same issue, but it works! took me 7 hours.
