### ISSUE TITLE
black ops 2 is crashing with VK_ERROR_OUT_OF_HOST_MEMORY

### ISSUE THREAD

**Issue by C-Flire** [RPCS3/rpcs3#11442]
Game crashes after the Dolby logo, while on an older version it went past the intro cinematic
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7934546/RPCS3.log)

*Intel Core I7 1165G7
*Intel Iris Xe graphics
*16gb ram

**Comment by C-Flire** [comment]
Issue seems to have appeared between rpcs3-v0.0.11-10611-acf51f0e and rpcs3-v0.0.13-11389-e5603fec_win64

**Comment by kd-11** [comment]
Crash is caused by a width 0 image existing, not sure if its a regression or not.

**Comment by C-Flire** [comment]
It seems like the crash can be avoided in the latest version using a patch that removes the intro

**Comment by JoXJoXD** [comment]
how to resolve this crash??
