### ISSUE TITLE
You broke the asmjit repo

### ISSUE THREAD

**Issue by kode54** [RPCS3/rpcs3#11457]
## Quick summary
/asmjit/asmjit.git no longer contains the matching commit hash for the commit used by the latest stable release of RPCS3 source in this repo.

## Details
It used to be possible to fetch 0.0.20 from the named tag in this repository and build with the associated submodules. Now the associated commit for /asmjit/asmjit.git no longer exists in that repository.

```
fatal: Fetched in submodule path '3rdparty/asmjit/asmjit', but it did not contain eae7197fce03fd52a6e71ca89207a88ce270fb1a. Direct fetching of that commit failed.
```

**Comment by Megamouse** [comment]
the tag is just a tag, nothing more

**Comment by AniLeo** [comment]
There is no such thing as stable release of RPCS3

**Comment by kode54** [comment]
Then I should delete the stable RPCS3 AUR package. Thanks.

**Comment by AniLeo** [comment]
If you're interested, we maintain rpcs3-git, you can use it

https://aur.archlinux.org/packages/rpcs3-git/

**Comment by kode54** [comment]
No problem. I am requesting the faux "stable" package to be deleted anyway. I am tired of "updating" it anyway.
