### ISSUE TITLE
Option to disable deadzone of 13%

### ISSUE THREAD

**Issue by coolllman** [RPCS3/rpcs3#11455]
Is it possible to add a function  to disable deadzone of 13% as dualshock 3, in duashock 4 and dualsense better sticks and with program ds4windows i delete this deadzone for xinput and gameplay is smooth, but games like killzone’s and uncharted require a gyroscope and really this cool option let me play with dualsense without ds4windows.

**Comment by Megamouse** [comment]
this makes zero sense

**Comment by MSuih** [comment]
You can adjust deadzones in bottom right corner, drag the slider all the way to left to disable the deadzone.
![image](https://user-images.githubusercontent.com/19759300/151587818-f1345589-197f-49ab-af42-b5cfb7d0bd72.png)

**Comment by coolllman** [comment]
I did this when i make the slider to 0 in xinput the deadzone is removed but in dualsense and ds4 it remains. In xinput, at the slightest deviation of the stick, movement begins, in any other deadzone it remains. (sorry for my bad english)

**Comment by coolllman** [comment]
When i use both dualsense and dualshock 4 with slider deadzone in 0, deadzone not removed, when use as xinput - deadzone is removed

**Comment by Megamouse** [comment]
you need to change the deadzone for each player or controller type individually

**Comment by coolllman** [comment]
I know that and i did that, i create custom gamepad config and only on xinput deadzone remove all.
Deadzone remove not working
![Screenshot_20220129-100118_VNC Viewer](https://user-images.githubusercontent.com/17841647/151646645-a9bf46ec-bd77-42e9-ade2-799252dd3efe.jpg)
Deadzone remove with
![Screenshot_20220129-100202_VNC Viewer](https://user-images.githubusercontent.com/17841647/151646648-f4ace3e1-beb5-4567-baeb-6c94116b5ffe.jpg)

**Comment by coolllman** [comment]
Need any other info?

**Comment by Darkhost1999** [comment]
What was definitely confusing was why gyroscope was mentioned at all.
But here is what I understand:
* When using an xinput controller if I have moved the deadzone slider in pads settings to 0 and clicked save. The xinput controller allows movement without any deadzone at all.
* If I use my dualshock 3, 4 or dualsense controller in RPCS3 and go to pads settings move the deadzone slider to 0 and click Save. My controllers movements respond as if the deadzone is still there.
Is this something to do with how the native sixaxis drivers work or is this an RPCS3 issue?

**Comment by Megamouse** [comment]
Cannot reproduce

**Comment by Danielet89** [comment]
Why closed this as completed if is it not solved 😅?

**Comment by Megamouse** [comment]
Because we have a deadzone and the configurable anti-deadzone (defaults to 13%).
So there's nothing left to do here anyway.

**Comment by Danielet89** [comment]
So if a problem occurs, does it stem from the game itself?

**Comment by Megamouse** [comment]
Games add their own deadzone if they fancy.
You'd have to disable it with a custom patch.

**Comment by Danielet89** [comment]
Oh ok thx for the info

**Comment by Danielet89** [comment]
Found the solution .
![20250105_125316](https://github.com/user-attachments/assets/43ead9ff-664e-43e9-9444-594673484777)
 By setting the anti dead zone, the desired calibration can be achieved manually for almost perfect behaviour

**Comment by Danielet89** [comment]
https://github.com/user-attachments/assets/96f49e50-720e-4173-84cf-f89278816122
