### ISSUE TITLE
God of war 3,  Working buffer not big enough

### ISSUE THREAD

**Issue by Monsterhuntter** [RPCS3/rpcs3#11450]
After about 1-2 hours of gameplay, the graphics break and then it crashes, with this error, Working buffer not big enough
I us the recommended settings 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7947222/RPCS3.log)

 

* OS
* Windows11
* CPU
* Ryzen 9 5900X
* GPU
* GTX 970
* Driver version
* 511.23

**Comment by nitroos-ai** [comment]
Try the option "Disable Vulkan Memory Allocator" in debug tab.

**Comment by kd-11** [comment]
I have a plan to fix this variant of the buffer not big enough error as long as the system still has usable graphics memory. We can just flush the buffer and spawn a new one as long as we have enough memory for it. Of course the error will still happen on low end systems without enough RAM+VRAM but it shouldn't happen in this case.

**Comment by Monsterhuntter** [comment]
I don't want to make you any more work, but now I have a new error ;/
Vulken device lost error
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7954459/RPCS3.log)
