### ISSUE TITLE
God of War III, freezes if you die 2 many times

### ISSUE THREAD

**Issue by zeroking1998** [RPCS3/rpcs3#11459]
if you die like 5-10 times and load frome the last checkpoint, It's freezes the game

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7964341/RPCS3.log)

**Comment by mfdsrax2** [comment]
You are too weak to become god of war

**Comment by YuriNator557** [comment]
Please use master build, not a PR when reporting these

**Comment by zeroking1998** [comment]
> Please use master build, not a PR when reporting these

Oh sorry, I forgot to switch to the master build, I upload a new log

**Comment by Megamouse** [comment]
patches applied. invalid
