### ISSUE TITLE
Pads: Ability to connect xbox controller on Mac

### ISSUE THREAD

**Issue by Pleaseaddstufformac** [RPCS3/rpcs3#11458]
## Quick summary
Please briefly describe what feature you would like RPCS3 to have.

## Details

Please describe the feature as accurately as possible.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.

#### 4. Please provide your system configuration:
* OS
* CPU
* GPU
* Driver version
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by YuriNator557** [comment]
As far as I'm aware, macOS does not have XInput

**Comment by Neirene** [comment]
MacOS 12 Monterey and 11 BigSur supports the Xbox One and Series controllers natively, but also they can make them work with SDL within the rpcs3 if they want at an internal level to extend the support for xbox wheels, fightsticks , etc.

**Comment by vaczy** [comment]
I also waiting for xbox one support on RPCS3 on MAC (M1, Monterey)
Hope you will make it guys... :)

**Comment by emmetmorris** [comment]
Any gamepad support please :(

**Comment by lovozeto** [comment]
Would love to see this implemented

**Comment by yurifpinto** [comment]
Also would love to see this working natively. For people trying to make an XBox One (or similar) controller work on a Mac in the meantime, give the Controllers app (https://vividmachine.com/controllers/) a try.

I tried Enjoyable, which would successfully remap all buttons to keyboard keys, except for the back triggers, which it wouldn't recognize. I also tried launching RPCS3 via Steam and remapping the controls there, but it had some weird behaviors with the directional analog sticks. Controllers was able to map everything successfully.

**Comment by ericreldridge** [comment]
> Also would love to see this working natively. For people trying to make an XBox One (or similar) controller work on a Mac in the meantime, give the Controllers app (https://vividmachine.com/controllers/) a try.
> 
> I tried Enjoyable, which would successfully remap all buttons to keyboard keys, except for the back triggers, which it wouldn't recognize. I also tried launching RPCS3 via Steam and remapping the controls there, but it had some weird behaviors with the directional analog sticks. Controllers was able to map everything successfully.

Any chance you could share your configuration with vivid machine controllers? I'm not having much luck with the analog sticks

**Comment by guikeller** [comment]
Looking at the PCSX2 source it seems that they use SDL2 to make 'other' controllers work on Win/Linux/Mac.

C++ Headers: https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Frontend/SDLInputSource.h
C++ Code: https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Frontend/SDLInputSource.cpp 

Then all that RPCS3 users would need to do is map their controllers to the ENV var using a tool like "SDL2 Gamepad Tool by General Arcade" ( https://generalarcade.com/gamepadtool/ ) for example.

If I was proficient at CPP I would give it a crack in creating a PR but unfortunately is not my forte.

**Comment by amurgshere** [comment]
I would also love support to be added for the native Xbox Controller support in MAC OS, please add this, as MACOS doesn't even support the old DualShock 3 controller wirelessly any more, and even wired you have to use a special script to activate the controller every time you plug it in.

**Comment by Traace** [comment]
I just found this issue when I was confused why my xbox one s controller doesn't work in rpcs3. Even Apple Arcade games does support it.

Please add support for xbox controllers to the macOS version

**Comment by NotLazy** [comment]
> I just found this github issue when I was confused why my xbox one s controller doesn't work in rpcs3. Even Apple Arcade games do support it.
> 
> Please add support for xbox controllers to the macOS version

+1 please add xinput support on macOS or add the game controller framework support mentioned in #11902

**Comment by Megamouse** [comment]
This should work now with SDL
