### ISSUE TITLE
[Feature Request] Cirrus Cl Donation

### ISSUE THREAD

**Issue by Danke-Boi** [RPCS3/rpcs3#11456]
## Quick summary
I would like to donate some money in order to get you guys the 10$ a month plan from Cirrus, so you don't run into issues with maximum number of concurrent processor that are usable at any one time.

## Details

Potentially faster compiling (especially for Windows)

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
Debugging?

#### 2. Please tell us, why your feature is important to RPCS3.
It allows progress to be made at a somewhat faster pace.
#### 3. Please attach screenshots of the feature implemented in other projects.
Dunno any other projects that have a paid subscription.
#### 4. Please provide your system configuration:
* MacOs Big Sur 11.6.3
* M1
* 7 core
* .0.2.xxxx
* 8Gb RAM

It's up to you guys to tell me if it's something that would be useful, or something that wouldn't be used at all. I am not entirely sure, as I am a veritable novice at C++, let alone the PowerPC architecture, so I am not really in the loop. I would love to see better M1 compatibility, which is why I know any C++ at all, but I understand that A. there are proportionally few people who have M1 laptops, and B. This is open source, so someone would have to do the work and submit it (it's gonna be about a year - 2 before I am at a level in which I can help). If this offer is something you would 100% want, how should I send the money? To whom?

**Comment by Danke-Boi** [comment]
<img width="778" alt="Screen Shot 2022-01-28 at 11 19 17 AM" src="https://user-images.githubusercontent.com/72051710/151582990-fe59d096-0438-4047-abbe-e0181e16f558.png">
Here is the thing that "inspired" me to make this _tremendous_ offer. lol

**Comment by Darkhost1999** [comment]
There is a patreon for donations
https://www.patreon.com/Nekotekina
The only side effect of using patreon is you don't guarantee your money goes towards specifically what you're requesting you want it to go to. 
Rather it goes towards supporting Neko and KD to assist in working on the emulator full time and acquire new hardware for better overall compatibility with more diverse testing.

**Comment by Danke-Boi** [comment]
Thank you. 

To Clarify: I wasn't specifically saying this should only go towards MacOS stuff, I was hoping it might but it was never a requirement. More the CL (or CI?) subscription.

On that note; however, is there anything I _can_ do to help with the M1 stuff? 

Also, I looked at the developer page to find out what I need to learn, and evidently it's a lot. What I was struggling with was understanding what exactly some of this meant. For example: right now I don't know why all MacOS programs havn't been compiled as ARM programs, because my limited knowledge leads me to believe that it is simply a drop down menu option in XCode. Why is this wrong, and what does it actually take to implement that compatibility? Is there not a way to simply use Metal? How are graphics APIs implemented in this program, and more commonly in others? Would looking into the PCSX2 implementation of Metal help at all given the similarity between the PS2 and 3? How do some games run faster in software mode (i.e running off of my CPU?) than GPU in PCSX2 (and by extension rpcs3?), especially considering the fact that CPUs are significantly slower at every aspect of graphical computing?

**Comment by MSuih** [comment]
For the CI part: I'm not really sure how much benefit the 10 dollar tier would give. The build won't be instant no matter how much money you throw at it and the scheduling time seems very short as-is. I think donating to patreon would be better use of your time. But this is just my personal opinion on this issue.

As for the latter half of your post, it seems like a textbook case of Dunning-Kruger. You know enough about the subject to say something but you don't know enough to understand why your reply sounds silly to a person who knows more. You can ask your questions in our discord server if you want to, I'm not going to go through each one of them here.

**Comment by Danke-Boi** [comment]
> Dunning-Kruger

erm, from what I've seen this requires that I not acknowledge my limited knowledge. My knowledge in this matter is about as deep as modern art (read: not deep). I am aware that my questions sound stupid, but that is why I am asking them, because asking questions is one of the best ways to learn. I asked them as well because when I go to find the answers on the interwebs (lol), I am having trouble understanding the answers, so having interaction with a human helps my brain piece things together. And by looking on the internet, I mean going to Apple's website and reading through the Metal documentation on how it handles, well, everything. I understood maybe 10% of that, and that's generous.

**Comment by nastys** [comment]
RPCS3 generates machine code, x64 code specifically. If you compiled RPCS3 for ARM, you'd get an "illegal instruction" error (if anything) as soon as the recompiled code is fed to the CPU.
RPCS3 needs a new recompiler that generates ARM assembly code instead of x64 (and so far, only PPU interpreter had been done).

**Comment by Danke-Boi** [comment]
> 

Sounds like my understanding of how this works is even smaller than I had previously thought. Guess I get to research compilers for the next 2 hours!

**Comment by nastys** [comment]
As for the GPU renderer being slower than software in PCSX2, that actually happens on Linux and Windows sometimes, too.
It's possibly because of the difference between the PS2 GPU and modern GPUs and APIs, which requires additional processing, sometimes with bottlenecks due to API or hardware limitations, or maybe lack of optimisations. It definitely does not apply to RPCS3.

**Comment by Danke-Boi** [comment]
Is the additional processing handled on the GPU side as well as the actual graphical calculations? If so, is there a way to offload the additional processing to the CPU?

**Comment by HerrHulaHoop** [comment]
GitHub is not the place for this discussion. Please move over to Discord.
