### ISSUE TITLE
NCAA 14 RSPC3 PRoblem 

### ISSUE THREAD

**Issue by camjuice** [RPCS3/rpcs3#11451]
F {RSX [0x0100438]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTexture.cpp:81[:4], in function copy_image_to_buffer)

Keep running into this issue

**Comment by kd-11** [comment]
A complete log is required, normally we close tickets without a log. By chance this crash is something I was working on for some other purpose, so I'll tag it for now and close when the fix is up.
