### ISSUE TITLE
The emulator has stopped compiling PPU modules at all

### ISSUE THREAD

**Issue by Basmurd** [RPCS3/rpcs3#11460]
The emulator has stopped compiling PPU modules at all, both with a clean installation and with an installation on top of the old version, and just freezes for no apparent reason.

**Comment by YuriNator557** [comment]
## Please do not ask for help or report compatibility regressions here, use [RPCS3 Discord server](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/) instead.
