### ISSUE TITLE
OFFICAL BUZZ CONTROLLER FREEZING AND CRASHING RPCS3

### ISSUE THREAD

**Issue by ScottishST** [RPCS3/rpcs3#11481]
Official buzz remotes work great within each Buzz game on rpcs3 but after roughly 30 seconds it freezes and displays the error 

PPU[0x1000000] Thread (main_thread) [0x00c785e8]} sys_usbd: Usb transfers are saturated

not playable with official wireless remotes.

wireless buzz controllers needed to play any of the buzz games to allow the full quiz experience

**Comment by marcoluc97** [comment]
Really what is it difficult to understand, fill the template and so please share the logs.

**Comment by mikekastam** [comment]
@ScottishST what was the solution to your problem? I am having the same error in my Mac OS Sonoma with my wireless original buzzers. Thank you
