### ISSUE TITLE
Disgaea D2 not displaying texts within menus on Mac M1

### ISSUE THREAD

**Issue by Neirene** [RPCS3/rpcs3#11487]
## Quick summary

Disgaea D2 [BLUS31313] is not displaying texts within the menus on the latest rpcs3 build for Mac(13249)

## Details

You cannot see any text rendered within the menus, fields such as the characters stat windows displaying your units EXP, weapon mastery, Aptitude, HP, Mana, etc.

#### 1. Please attach RPCS3's log.

Log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8006823/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.

RSX Capture
[BLUS31313_20220205003119_capture.rrc.zip](https://github.com/RPCS3/rpcs3/files/8006819/BLUS31313_20220205003119_capture.rrc.zip)

#### 3. Please attach screenshots of your problem.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5244595/152616639-86506d6d-d08e-49c3-ba34-fbdc1793c02a.png">

#### 4. Please provide comparison with real PS3.

![image](https://user-images.githubusercontent.com/5244595/152616383-1dcb2fae-37ed-4931-8e93-858474daffb8.png)

#### 5. Please provide your system configuration:
* OS MacOS Monterey 12.2
* CPU Apple M1
* GPU Apple M1
* RAM 16GB

**Comment by kd-11** [comment]
Tracked by https://github.com/RPCS3/rpcs3/issues/11414
