### ISSUE TITLE
linking ppu modules 

### ISSUE THREAD

**Issue by dannykont** [RPCS3/rpcs3#11483]
I try to run God of war ascension on the RPCS3 emulator, although I struggle with an issue, it tried to load ppu modules and then it goes to a screen of duplex, it is stuck in this loop, I can't resolve this 
![image](https://user-images.githubusercontent.com/98988002/152434977-cc8d3841-ab7c-4c46-ac2f-6773363fe970.png)
![image](https://user-images.githubusercontent.com/98988002/152435441-e5f1e354-8702-4488-a20b-c7ebaadcf0c7.png)

Log: 
S sys_prx: _sys_prx_unload_module(id=0x23003400, flags=0x0, pOpt=*0x0): name='libresc.sprx'
U PPU TODO: Unimplemented syscall syscall_988 -> CELL_OK (r3=0x1, r4=0x0, r5=0xd0100874, r6=0x0, r7=0x30000010, r8=0xe4768, r9=0x100000000000000, r10=0x1000000)
U sys_prx TODO: _sys_prx_stop_module(): cmd is 8 (stop function = *0x3f04d8)
U sys_prx TODO: _sys_prx_stop_module(): cmd is 8 (stop function = *0x390814)
U PPU TODO: Unimplemented syscall syscall_988 -> CELL_OK (r3=0x2, r4=0x0, r5=0x0, r6=0x0, r7=0x0, r8=0x3e9, r9=0x70, r10=0xd0100b60)
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
U sys_prx TODO: _sys_prx_stop_module(): cmd is 8 (stop function = *0x3f04d8)
U sys_prx TODO: _sys_prx_stop_module(): cmd is 8 (stop function = *0x390814)
S sys_process: Process finished -> /dev_hdd1/duplex.self
F SYS: Failed to access continuous config: 
S cellSysutil: Retained cache from parent process: C:/Users/Daniel/OneDrive/Desktop/Videogames/PS3/dev_hdd1//caches/BCES01741_BCES01741/
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2060 SUPER' running on driver 511.65.0.0
S Input: XInput device 0 connected
S PPU: LLVM: Loaded module v4-kusa-i2g9Cw2QkdFHuxFUfFs8Qv-00001G-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-SbgoMwk86ryFRa2S3RoppY-00001G-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-iHzVJWE38UsYMV1fPdwchs-00001G-skylake.obj
S SPU: SPU Runtime: Built the interpreter.
U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0100ce0)
S PPU: LLVM: Loaded module v4-kusa-1z3Pyu8YVnnorJiQ2hfu1e-00001G-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0100a50)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0100a50, a3=0x0)
S PPU: LLVM: Loaded module v4-kusa-XCgQWMc1s99n1WTwrpWvw4-00001G-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S PPU: LLVM: Loaded module v4-kusa-GsbjiwC5Sm3exFcR5udHpE-00001G-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-gRWSbPdZHFQq5essKqQVjk-00001G-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
S PPU: LLVM: Loaded module v4-kusa-fLV79QqHgPi90UziTsWrHo-00001G-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23001200)
U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0100df0)
S PPU: LLVM: Loaded module v4-kusa-UnNP3fZh95wiCGy3Q0csRy-00001G-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libresc.sprx” (id=0x23003400)
S cellSysutil: Mounted existing cache at C:/Users/Daniel/OneDrive/Desktop/Videogames/PS3/dev_hdd1//caches/BCES01741_BCES01741/
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES01741/USRDIR/EBOOT.BIN” [1]
S sys_prx: _sys_prx_unload_module(id=0x23003500, flags=0x0, pOpt=*0x0): name='libsysutil_game.sprx'
S PPU: LLVM: Loaded module v4-kusa-qAE5LW7t8xT9tNggSrSJhv-00001G-skylake.obj
S PPU: LLVM: Loaded module v4-kusa-1v8Qb7coSU1k54TtmJzrt4-00001G-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libpngdec.sprx” (id=0x23003900)
S sys_prx: _sys_prx_unload_module(id=0x23003900, flags=0x0, pOpt=*0x0): name='libpngdec.sprx'

**Comment by Darkhost1999** [comment]
This is obviously pirated

**Comment by dannykont** [comment]
obviously, is there a way to buy a not pirated version and run it on pc?

**Comment by Darkhost1999** [comment]
Many ways to buy the game. 
* https://www.amazon.com/dp/B00FF9S8IM/ref=cm_sw_r_apan_glt_i_96ANAHECF054TGXSCB82

Many resources to get started dumping games::
* https://rpcs3.net/quickstart
* https://wiki.rpcs3.net/index.php?title=Help:Dumping_PlayStation_3_games

**Comment by dannykont** [comment]
> Many ways to buy the game.
> 
> * https://www.amazon.com/dp/B00FF9S8IM/ref=cm_sw_r_apan_glt_i_96ANAHECF054TGXSCB82
> 
> Many resources to get started dumping games:
> 
> * https://rpcs3.net/quickstart
> * https://wiki.rpcs3.net/index.php?title=Help:Dumping_PlayStation_3_games

but this is a physical version of the game not a digital, how can I play the game on the emulator legally?

**Comment by AniLeo** [comment]
If you don't want to read then we can't help you further. Either way, this isn't the place for support. Locking.
