### ISSUE TITLE
BLES00028 aka Sonic 2006 almost works now

### ISSUE THREAD

**Issue by RenegadeSaiyan** [RPCS3/rpcs3#1149]
I literally get to the GSframe but then in the debugger this happens. sys_fs: sys_fs_open('/dev_bdvd/PS3_GAME/USRDIR/ps3/archives/system.arc') failed: device not mounted Any way to fix this would be helpful.

**Comment by tambry** [comment]
@RenegadeSaiyan You're missing the file. Check if your original copy of the game contains the file at the specified path.

**Comment by RenegadeSaiyan** [comment]
I have system.arc, but I just need a way to mount the file

**Comment by RenegadeSaiyan** [comment]
![image](https://cloud.githubusercontent.com/assets/13460618/8852884/b4568fd2-3125-11e5-948f-209d3eba67af.png)

**Comment by Ru4slan** [comment]
Try:BLES00028/USRDIR/ps3/archives/system.arc

**Comment by tambry** [comment]
@Ru4slan And where is he suppoused to try that?

**Comment by RenegadeSaiyan** [comment]
@Ru4slan define try

**Comment by RenegadeSaiyan** [comment]
I gotta it to boot after mounting files using RPCS3's virtual file system manager and well, it hangs on the first loading screen due to missing save file features, I will try again once these features are added in to the emulator.

**Comment by tambry** [comment]
@RenegadeSaiyan You can probably close the issue, since it really isn't an issue.

**Comment by RenegadeSaiyan** [comment]
K
