### ISSUE TITLE
God of war origins collection no longer works

### ISSUE THREAD

**Issue by Siddharth-Tiwari10** [RPCS3/rpcs3#11499]
## Quick summary
Please briefly describe what has stopped working correctly.

## Details
Please describe the regression as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
* Please see [How to find the build that caused a regression](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression.3F) in our wiki.
* You can find [History of RPCS3 builds](https://rpcs3.net/compatibility?b) here.

#### 2. Please attach TWO logs:
* One for the build with regression.
* One for the build that works as expected.

##### How to obtain RPCS3's log:
* Run the game until you find the regression.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc.
	And drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 4. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 6. Please provide your system configuration:
* OS
* CPU
* GPU
* Driver version
* etc.

#### Please include.
* Anything else you deem to be important
![FPS_ 60 03 _ Vulkan _ 0 0 20-13263 _ God of War®_ Origins Collection  BCUS98289  07-02-2022 13_49_31](https://user-images.githubusercontent.com/99172319/152753296-0083b6c2-e961-4e89-8b78-36e5e5639737.png)
![RPCS3_ Fatal Error 07-02-2022 13_32_21](https://user-images.githubusercontent.com/99172319/152753307-b52b0d86-d0a4-4803-89af-e4216bfdbf89.png)
![RPCS3_ Fatal Error 07-02-2022 13_49_46](https://user-images.githubusercontent.com/99172319/152753313-ee5b7b7d-d31e-473d-a4c8-aa969e8191bc.png)It worked correctly yesterday but the there was a power cut so my pc turned off I couldn't close the game properly so after that whenever I open the game it opens but after that when I select the games of the two in the collection It shows these errors

**Comment by Asinin3** [comment]
GitHub isn't for support. And you didn't even follow any of the issue reporting template. What you provided isn't even helpful for us to locate the issue or help you. I would tell you to use Discord instead, but you spammed our developers in private messages, so it's on you to fix the issue. Maybe treat people who are developing an emulator for free, and providing free tech support with some respect.
