### ISSUE TITLE
Regression: Rock Band 3 flickering wildly during gameplay (#11491) 

### ISSUE THREAD

**Issue by jnackmclain** [RPCS3/rpcs3#11503]
## Quick summary
Latest build causes massive flickering in Rock Band 3.

## Details
Build 3 days ago has no flicker, updated and myself and another person experience the same thing

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.20-13263-90d368ae Alpha

#### 2. Please attach TWO logs:
[regression.log](https://github.com/RPCS3/rpcs3/files/8018628/regression.log)

[working.log](https://github.com/RPCS3/rpcs3/files/8018632/working.log)

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
https://youtu.be/46WIcwkEt2A

#### 4. Please attach screenshots of your problem.
https://youtu.be/46WIcwkEt2A

#### 5. Please provide comparison with real PS3.
c'mon. this is insane. It's flickering like mad.

#### 6. Please provide your system configuration:
* OS Windows 11
* CPU Intel Core i9-10900k
* GPU - RTX 3070 
* Driver version 511.23
* etc.

#### Please include.
* Anything else you deem to be important
https://youtu.be/46WIcwkEt2A

**Comment by AddyMills** [comment]
I've also noticed flickering when there weren't any before.

- Windows 10
- CPU: AMD 3700X
- GPU: Nvidia RTX 2080 Super
- Driver 511.65

**Comment by lebhleb** [comment]
Pretty much same thing, lots of flickering troughout. https://www.youtube.com/watch?v=LTa2BlfhBfw
Was fine days ago like in the issue.

**Comment by jnackmclain** [comment]
I do want to add an additional note. I am part of the mod team for Rock Band 2 Deluxe and Rock Band 3 Deluxe. I have booted these games so many times over the past couple months and never seen this issue until I updated RPCS3 today.

**Comment by AniLeo** [comment]
Potentially regressed by #11491, test the build prior to it in order to confirm

**Comment by jnackmclain** [comment]
confirmed. [#11494](https://github.com/RPCS3/rpcs3/pull/11494) caused the regression.
Build 0.0.20-13259-02cdf8ac does not have this issue

**Comment by hectaacdc** [comment]
Can confirm it's fixed as of latest master (v0.0.20-13214-f2ed50e6)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8044721/RPCS3.log.gz)
