### ISSUE TITLE
fail fetch submodule asmjit for build the sources

### ISSUE THREAD

**Issue by sl1pkn07** [RPCS3/rpcs3#11506]
## Quick summary
fail fech git submodules due point to non-existent commit (asmjit)

## Details

Please describe the problem as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
clean sources, build from zero

#### 1. Please attach RPCS3's log.
no program log due a build problem

#### 4. Please provide comparison with real PS3.
none

#### 5. Please provide your system configuration:
* OS archlinux 
* CPU dual Xeon E2650-v4
* GPU 1070Ti FE
* Driver version 510.47.03
* etc.

#### Please include.

git clone https://github.com/RPCS3/rpcs3.git
cd rpcs3
git submodule update --init
--snip--
fatal: git upload-pack: not our ref fc2a5d82f7434d7d03161275a764c051f970f41c
fatal: remote error: upload-pack: not our ref fc2a5d82f7434d7d03161275a764c051f970f41c
fatal: Fetched in submodule path '3rdparty/asmjit/asmjit', but it did not contain fc2a5d82f7434d7d03161275a764c051f970f41c. Direct fetching of that commit failed.
fatal: 

seems asmjit repo do a force-pushed and not update the submodule in rpcs3 repo. the commit is still cached in the github web
https://github.com/asmjit/asmjit/tree/fc2a5d82f7434d7d03161275a764c051f970f41c

**Comment by Megamouse** [comment]
I requested a fork for rpcs3.
I'll close the issue once it's available again.

**Comment by Megamouse** [comment]
Should be fixed

**Comment by sl1pkn07** [comment]
seems .gitmodules still points to upstream asmjit

https://github.com/RPCS3/rpcs3/blob/master/.gitmodules#L7

greetings
