### ISSUE TITLE
Heavy Rain Move edition status Nothing 0% now

### ISSUE THREAD

**Issue by windes14** [RPCS3/rpcs3#11500]
## Quick summary

Game can't start because seeks for camera infinitely. Changing camera, all types, not helps.

## Details

U cellCamera TODO: cellCameraGetType(dev_num=0, type=*0xd0020900) x756

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.

- SYS: RPCS3 v0.0.20-13263-90d368ae Alpha | HEAD
- SYS: Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz | 4 Threads | 23.42 GiB RAM | TSC: 3.500GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 5.13.0-28-generic, Version: #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GT 1030' running on driver 510.47.3.0
- RSX: Found vulkan-compatible GPU: 'llvmpipe (LLVM 12.0.0, 256 bits)' running on driver 0.0.1

**Comment by YuriNator557** [comment]
Log file is missing

**Comment by windes14** [comment]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/8016543/RPCS3.zip)

**Comment by Megamouse** [comment]
A: pirated
B: Not even a camera is selected

**Comment by windes14** [comment]
Thanks, acknowledged! Good luck and thanks for your work!
