### ISSUE TITLE
NCAA Football 14 (With College Football Revamped) Crashes when opening a game, Dynasty, or Road to Glory.

### ISSUE THREAD

**Issue by MichelTGM** [RPCS3/rpcs3#11508]
Title, Game crashes when opening a dynasty, road to glory, or exhibition game. Would love some help!

OS: Windows 10 Home
CPU: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
GPU: GTX GeForce 1650 SUPE
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8036704/RPCS3.log)

**Comment by AniLeo** [comment]
Duplicated of #9918
