### ISSUE TITLE
Screen going white after cutscene

### ISSUE THREAD

**Issue by FairyTheMintyDragon** [RPCS3/rpcs3#11509]
I'm super new to this and unsure where to put this//

After the beginning cutscene, it goes dark than white.

## Details

I recently updated the game (RPCs3 as well) as the game was crashing, and now after the cutscene (Where the narrator talks about imagination, etc.) It tries to load but then I'm faced with a white screen. The FPS drops down to 10-17 when the screen turns white.

I've tried messing with the settings, but nothing appears to help? (I don't know much about emulators, haha)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8037956/RPCS3.log.gz)

![886](https://user-images.githubusercontent.com/99378507/153335262-c1140b05-a40b-47d5-b927-f0e5a6c062b9.png)

Just the first bit of this, I'm unable to do it on my own ps3
https://www.youtube.com/watch?v=jqoZCqBP5-s

System:
Windows 10
AMD Ryzen 7 5800X 8-Core-Processor
NVIDIA GeForce GTX 1060 6GB

I honestly don't know what else to add, let me know if I forgot anything-

**Comment by RainbowCookie32** [comment]
Try changing zcull accuracy from Relaxed to Approximate. Some games don't like Relaxed and can crash or have various issues

**Comment by FairyTheMintyDragon** [comment]
> 

It worked! I thought I tried it before, but I guess not haha. tysm!

**Comment by Juzz0** [comment]
> Try changing zcull accuracy from Relaxed to Approximate. Some games don't like Relaxed and can crash or have various issues


Thanks alot, we hit a dead end on our yearly speedrun and you saved it. 🙏
