### ISSUE TITLE
Gran Turismo 5 InGame

### ISSUE THREAD

**Issue by Danke-Boi** [RPCS3/rpcs3#11505]
## Quick summary
I managed to load Gran Turismo 5 all the way into the menu, but on the same frame that the menu rendered, the game froze, with the music still playing.
## Details
RPCS3 says that it is running at .95 FPS (exact same behavior in other games that crash, just they say 20.78 or some other arbitrary number)
<img width="315" alt="Screen Shot 2022-02-07 at 8 26 46 PM" src="https://user-images.githubusercontent.com/72051710/152900410-ec97e020-8aac-4850-a25d-9ba90a03c8c8.png">
CPU utilization stays high, despite only playing music at this point, and if I am quick enough I can select an option or two before the game freezes.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8019915/RPCS3.log)

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 4. Please provide comparison with real PS3.
Erm, I can actually navigate menus on my PS3.
#### 5. Please provide your system configuration:
* MacOS Big Sur 11.6.3
* M1 (base 8 core 4 perf. 4 eff.)
* M1 7 core
* v0.0.20-13266-2d9f21a2
* 8gb LPDDR4
* 256GB SSD

#### Please include.
Should I test this game on other builds (currently on the Master, but def. an Alpha)? It seems like the game has never been playable, which is strange considering that the demos are. I couldn't find issues in which the game acted in the same way. Thought this might be a useful insight into what the problem could be.

**Comment by Danke-Boi** [comment]
Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of host memory (system RAM)
Looks like 8GB isn't enough, I will try again without chrome or Safari open just to make sure the maximum possible amount of RAM is available for the emulator.

**Comment by Danke-Boi** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8019985/RPCS3.log)
New log file, after restarting my Mac, quitting all applications, and giving the poor thing a chance to settle down before torturing it.

**Comment by Danke-Boi** [comment]
As previously stated, I do not know enough to tell you guys what the issue is or how it can be fixed, I acknowledge my lack of knowledge and apologise if my behavior has offended anyone. I am sorry if I have bothered you or if this counts as spam or whatever. I read the other post that goes in depth on GT5, and I can safely conclude that my problem at the very least rears its ugly head in a different way. For all I know this is the exact same issue.
Given my inability to understand just about anything going on, I decided that what you guys said in the quickstart remains accurate. I am going through my collection of about 30 games and I am planning on posting the errors in games that have unique errors. If you do not want me to do this let me know, and if this isn't the best place please let me know. The last thing I want to do is slow you down or stifle "real" problems.

**Comment by AniLeo** [comment]
Neither of these log files are about Gran Turismo 5

**Comment by Danke-Boi** [comment]
WTH? I took these from where it says to on the wiki, where should I look to find them?

**Comment by Danke-Boi** [comment]
<img width="733" alt="Screen Shot 2022-02-09 at 11 00 40 AM" src="https://user-images.githubusercontent.com/72051710/153239534-d266ad86-2413-4a56-af0d-19471eaf52fe.png">

**Comment by illusion0001** [comment]
Check `~/Library/Caches/rpcs3`.

**Comment by Danke-Boi** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8035329/RPCS3.log)
Here it is! thanks @illusion0001

**Comment by reece394** [comment]
This seems like a pirated copy. RPCS3 doesn’t support people who pirate games. Read [Here](https://rpcs3.net/quickstart) to dump your game correctly

**Comment by Danke-Boi** [comment]
I had trouble with my version, so I tried a different version found online to see if it would work. I saw the thread on the various different versions and which one worked best for different people.

**Comment by MSuih** [comment]
We do not support piracy or provide help with it. Any issues involving illegally obtained copies are not accepted.

Gran Turismo 5 and 6 are notorious for being extremely unstable on rpcs3 anyways.

**Comment by Danke-Boi** [comment]
How do make a copy of my game on MacOS? What Blu-Ray drives are supported on MacOS? Are those drives listed on the start page external or internal? Also, I was under the impression that if you had a copy of a game you were allowed to download the same copy online, like if I owned the original Super Mario Bros. for NES I can download a copy online legally. Is this not true?

**Comment by MSuih** [comment]
I don't think the tools that are required for PC dumping have been ported to mac yet. You'll have to use a Windows or Linux PC, or a PS3 console.

The details of what is and is not allowed depends on which country you live in and how do you interpret the laws. Our rules forbid use of game copies that you have not dumped yourself. This is both to protect the project from lawsuits and also to avoid wasting our time diagnosing issues caused by modified dumps.

Also, github issues is not a chat platform. If you have more questions, please join our discord to ask them.

**Comment by Darkhost1999** [comment]
You don't need to worry about external or internal if you get the sata to USB adapter. But yes the Quickstart guide does label external drives.
And they're only about $50-80. Meanwhile you can also use a jailbroken PS3 which PS3's are also $30-120 used on average. And an ftp server really only needs a web browser but there are ftp clients and servers for Mac
