### ISSUE TITLE
F.E.A.R. 2 - Project Origin (USA) game stop after play 15m and gun tranparent

### ISSUE THREAD

**Issue by tee4341** [RPCS3/rpcs3#11511]
![screenshot 12](https://user-images.githubusercontent.com/48321898/153468013-b584f732-6454-4c63-8035-7f63325816e3.jpg)

F.E.A.R. 2 - Project Origin (USA) game stop after play 15m and gun model tranparent
game stop after play 15m(after open the door)
![screenshot 11](https://user-images.githubusercontent.com/48321898/153467521-31eb72d4-2bca-45b9-b53a-971d53619021.jpg)

and all gun model tranparent
![screenshot 4](https://user-images.githubusercontent.com/48321898/153467700-cbb58108-a8af-47d8-b04f-135ac533f331.jpg)
![screenshot 5](https://user-images.githubusercontent.com/48321898/153467711-600dd7c5-9c21-4046-8984-e89b59ee4f9f.jpg)
![screenshot 6](https://user-images.githubusercontent.com/48321898/153467714-2bcc66be-179f-45fe-9265-74382c598b42.jpg)
![screenshot 7](https://user-images.githubusercontent.com/48321898/153467716-ea29156a-9337-4e43-ba4d-98ba27b68880.jpg)
![screenshot 8](https://user-images.githubusercontent.com/48321898/153467718-bc8b5ea1-7c5c-45df-899a-314b73a7e391.jpg)
![screenshot 9](https://user-images.githubusercontent.com/48321898/153467719-fefadfb3-fac0-427b-aa6a-7fc14120d2c2.jpg)
![screenshot 10](https://user-images.githubusercontent.com/48321898/153467720-c90ee3fe-cc54-4a07-9072-787302ca5c4a.jpg)

**Comment by kd-11** [comment]
Required information was not provided. No log files or relevant captures.
Please follow the template provided when opening issues.
