### ISSUE TITLE
F {PPU[0x1000000] Thread (main_thread) [0x0040b2e4]} VM: Access violation reading location 0x208f2c40 (unmapped memory)

### ISSUE THREAD

**Issue by 74M35** [RPCS3/rpcs3#11516]
F {PPU[0x1000000] Thread (main_thread) [0x0040b2e4]} VM: Access violation reading location 0x208f2c40 (unmapped memory)

Getting this error on Stuntman: Ignition [BLUS30073]. Seen a few things on what to change for this game to work properly and nothing works so far. crashes about 5 seconds into the first mission.

I have tried the patch on the website but doesn't work. Have tried enabling WCB, strict rendering mode, force CPU blit and enabling dfma.

I am using RPCS3 Version: 0.0.20-13271-d6597038 Alpha

**Comment by Darkhost1999** [comment]
https://github.com/RPCS3/rpcs3/issues/10954
