### ISSUE TITLE
[Regression] Debugger does not match with instruction breakpoint (PR #11315)

### ISSUE THREAD

**Issue by illusion0001** [RPCS3/rpcs3#11514]
Regression from some PR, need to bisect likely came from arm64.

**Comment by illusion0001** [comment]
Just to clarify, stepping is not affected, only breakpoint specifically ppu.

**Comment by illusion0001** [comment]
13177 Last working build
![image](https://user-images.githubusercontent.com/37698908/153735632-94659b71-ca2b-42c2-906c-1e5abf4bd184.png)

13178 [PR #11315](https://github.com/RPCS3/rpcs3/pull/11315)
![image](https://user-images.githubusercontent.com/37698908/153735636-722b3897-de13-468d-92b0-73d18424c1f1.png)

One upside is RIP of PPU is in RBX, this bug also applies to breakpoint set within the debugger itself, not just memory. Had to use static because fast is not usable in 13178

**Comment by illusion0001** [comment]
Tagging @Nekotekina in case it gets lost

**Comment by Nekotekina** [comment]
I'm not sure I understood the problem but give it a try anyway.
