### ISSUE TITLE
[Feature Request] Live Closed Captioning (Accessibility)

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11512]
## Quick summary

Automatically detect and add captions to any video or audio playing.

## Details

This feature should be independently scaled from any wide-screen, stretch to display, aspect ratio patch, mod, or hack.
The idea is that the closed captioning will have font size, color, and type adjustments to have bottom left bottom center bottom right, top left, top center, top right options.
I do not know if this will require a microphone or how the actual function will work and if it's even plausible to accomplish.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay

#### 2. Please tell us, why your feature is important to RPCS3.

Adds accessibility options for the visually impaired (let's not forget our hearing impaired friends) to have larger font, color blind options, etc.
Works around any stretch to display, aspect ratio, wide-screen hack, mod, or other, issues that may occur with games that do have subtitles built in. Adds subtitles to games that do not have built in support.

#### 3. Please attach screenshots of the feature implemented in other projects.

![Screenshot_20220210-161310_GitHub.png](https://user-images.githubusercontent.com/60384196/153505577-691f99e8-7fe0-4b21-96c0-739786cc8bc0.png)

#### 4. Please provide your system configuration:

N/A to the feature request. Intent is everyone on all hardware should receive this accessibility feature if possible and if such a feature is even considered.

#### Please include.

As I said I have no idea How this could be implemented.
But what I do know is it can be beneficial in assisting with the near sighted, colorblind, visually impaired, or simply be provided as a quality of life improvement feature for those that use CC in their daily lives.
If this feature request does not wish to be considered and/or is out of scope. I guess close the request.

**Comment by Megamouse** [comment]
I like the idea of adding more accessibility options.
But for this to work, you'd need some sophisticated AI.
To my knowledge, this is currently only achievable with paid services online.
Even the subtitles on YouTube and Microsoft teams are questionable at best.

**Comment by Darkhost1999** [comment]
Yeah, maybe longterm and discussion labels for research and discussion. I imagine this type of request is the modern day equivalent of PS3 on Arm64 request 8 years ago. Aka a request ahead of it's time but not entirely impossible. Figured get it out there see what stirs and what becomes of it.

**Comment by Asinin3** [comment]
I am all for accessibility, however this is something that is rather difficult to implement with limited usability as we won't be able to differentiate between game sounds, music and voices. Most games already have an option to enable subtitles as well.

There are already a number of third party tools that can do this as well.

**Comment by Darkhost1999** [comment]
For those who it may pertain to:
On Windows 11 you can open Settings -> Accessibility -> Captions and enable “Live Captions.” Once enabled, you can use Windows key + Ctrl + L to turn on/off the feature.

So now this feature is built into the Windows 11 OS. If someone knows of another option feel free to list them.
