### ISSUE TITLE
[Suggestion] Rename the RPCS3.log file

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#11517]
The current RPCS3.log file name causes issues with users who have file extensions turned off, especially if RPCS3 crashed and didn't create a .gz archive of the log. These people see the log named "RPCS3" which is indistinguishable from the RPCS3 executable (aside from the icon, and filetype if they have that column enabled).

This causes some frustrations when asking people in our support channels to upload their log file, making things take longer than they should for both parties. I suggest changing it to **Output.log** or **RPCS3 Output.log** but anything that uniquely identifies this file outside of file extensions will resolve the issue.

**Comment by Darkhost1999** [comment]
Suggestion change path to RPCS3/log/RPCS3.log
And if the log is successfully archived into an RPCS3.log.gz delete RPCS3.log
* Prevent "Why are there 2 logs?"
When asking to upload a log there is only ever 1 file in the RPCS3/log directory (unless user manually creates a zip/rar or renames the file). Even if it crashes and never archives the file RPCS3.log will still be there.

**Comment by Megamouse** [comment]
The name should be as similar to the old name as possible.

**Comment by Asinin3** [comment]
> And if the log is successfully archived into an RPCS3.log.gz delete RPCS3.log

This has happened since the beginning of time. Moving to a separate folder works though not as well imo..

**Comment by Nekotekina** [comment]
If the problem is not seeing file extensions, try to solve it by enabling file extensions first. I suspect a desktop.ini may be able to override "folder" behaviour.

**Comment by elad335** [comment]
In #11519 it's simply called LOG.log

**Comment by Asinin3** [comment]
Well, I still think a different name other than RPCS3.log would be a good idea but its not important, and we saw how the PR went.. Closing.
