### ISSUE TITLE
Vulkan Error on Amplitude

### ISSUE THREAD

**Issue by Mou-Ikkai** [RPCS3/rpcs3#11521]
## Quick summary
While playing Amplitude, I was chilling on the Results screen until Vulkan randomly encountered an error.

## Details

Please describe the problem as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### Please attach RPCS3's log.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/8054366/RPCS3.zip)

#### Please provide your system configuration:
* Windows 10 21H2
* Ryzen 9 3900X
* AMD 5700XT 8GB
* 22.2.1
* Dual Monitor.

#### Please include.
I don't know if this is an error due to prolonged duration of the app running at once? I fell asleep with the game running, it was still working after... 12 hours of me idling on it? Then I played a few songs before it crashed on the results screen with a Vulkan error.

**Comment by Mou-Ikkai** [comment]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/8054458/RPCS3.zip)
Crashed again, a lot faster at this point. (A single hour?)

**Comment by Mou-Ikkai** [comment]
> The error code relates to exclusive fullscreen, but you do not have exclusive fullscreen force-disabled, which means the extension is not even loaded by us. Are you using some kind of 3rd party injector? This includes some HUD/OSD tools, OBS, etc. Even if we add a hack to work around it, this is a bug that should be reported upstream.

Is it because I'm playing Valorant? I play Amplitude whenever I'm dead or waiting for a match, but... Valorant is it's own app.

**Comment by kd-11** [comment]
Download vkdiag from https://github.com/13xforever/vkdiag/releases/download/v1.1.13/VkDiag.exe
Run it, then grab a screenshot of the output and post it here.

**Comment by kd-11** [comment]
Looks like OBS and steam are forcefully loaded for all applications. Not sure which one is causing problems, but my guess would be OBS. I have the steam one installed and it is not causing issues as far as I can tell.
You can try disabling the extension or just uninstalling OBS to test if it is the cause.
