### ISSUE TITLE
Regression with GUI skins (top tabs style in settings window) 

### ISSUE THREAD

**Issue by Andryshik345** [RPCS3/rpcs3#11526]
## Quick summary
Noticed the bug with top tabs in settings window on yorha and nekotekina skins (and probably in other skins like skyfall, but im not sure how they looked before).

## Details
How it used to be before:
<details>
  <summary>Screenshot</summary>

![изображение](https://user-images.githubusercontent.com/24612088/153753337-b0ca37b8-5611-4e2d-b634-c0e37bcc8f46.png)

</details>

How it looks like now:
<details>
  <summary>Screenshot</summary>

![изображение](https://user-images.githubusercontent.com/24612088/153753394-2d083f8a-1e7b-4785-9e6f-d0663fafaf21.png)

</details>

The proper look can be return by re-applying the skin but after re-opening settings window it breaks again.

**Comment by Megamouse** [comment]
Lol. no idea what's wrong.
But the skyline theme doesn't have that issue.
Might be a qss issue. idk

**Comment by Andryshik345** [comment]
For skyline i meant this:

After applying:
<details>
  <summary>Spoiler</summary>
  
![изображение](https://user-images.githubusercontent.com/24612088/154133610-e83792a6-cd11-48f9-bb07-dd144996b987.png)
![изображение](https://user-images.githubusercontent.com/24612088/154133713-f2202df4-10ff-4eeb-a075-b9bf74b8789d.png)

</details>

After re-opening settings:
<details>
  <summary>Spoiler</summary>

![изображение](https://user-images.githubusercontent.com/24612088/154133667-8744cb3a-aad9-4262-9d0f-878625906de4.png)
![изображение](https://user-images.githubusercontent.com/24612088/154133748-084128c3-5df6-4897-b45e-6074a644a179.png)

</details>

but i really dont know if it was before, since im not using that skin. Almost the same thing is in light version of skyline.

**Comment by Megamouse** [comment]
I have no idea what's supposed to be different in those images

**Comment by Megamouse** [comment]
you mean the blue lines.
Yeah. weird
