### ISSUE TITLE
RPCS3 no longer compiles in linux

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#11528]
## Quick summary
RPCS3 no longer compiles in linux

## Details
Error thrown to terminal during compilation, as excerpted from logfile below:

`/usr/include/c++/11/bits/move.h:160:13: error: invalid conversion from ‘int’ to ‘VkSemaphore_T*’ [-fpermissive]`

## System configuration and test details
* OS: Linux Mint 20.3 / kernel 5.13
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070
* Driver version: 510.47
* Compiler: gcc-11.1.0
* Compile log: [here](https://pastebin.com/VRmdYPa3)
* Tested on commit: 2d5d5746d1578db95c10229df3e81f33d7f7a765
* Last known good commit: 987166f4da20e19d01777d0bfad64a811d8de1d1

Can provide a bisect if needed.

**Comment by kd-11** [comment]
Obviously if CI is working then we're missing the most important piece if the puzzle - the compiler version that is failing

**Comment by Shoegzer** [comment]
Is there something I can provide other than the compiler version I posted above?  Not sure if a bisect would help but I'm happy to do that too, if you give me some time.

**Comment by kd-11** [comment]
Thing is, I can build fine on arch with the same compiler version 11.1.0 which makes me wonder if ubuntu is using a different version of the compiler? Maybe some switches on by default?
![image](https://user-images.githubusercontent.com/15904127/153790992-79c509a4-e143-4979-8656-66122261761b.png)

**Comment by kd-11** [comment]
After looking at this closely, it does indeed seem to be a compiler issue. The failing line is:
`if (const auto wait_sema = std::exchange(m_dangling_semaphore_signal, VK_NULL_HANDLE))`
If your vulkan SDK is configured correctly, VkSemaphore should alias a pointer (`ObjectVkSemaphore_T*`) and VK_NULL_HANDLE is an alias for nullptr or (void*)0ull, not int. However, from the compile log:
`‘constexpr _Tp std::__exchange(_Tp&, _Up&&) [with _Tp = VkSemaphore_T*; _Up = int]’`
Why is your SDK having VK_NULL_HANDLE not of the same type as VkSemaphore? The headers make sure the NON_DISPATCHABLE_HANDLE type matches with the VK_NULL_HANDLE object type (pointers for 64-bit, integers for 32-bit build). Which SDK headers are you using for the build? Something is amiss here.

**Comment by Shoegzer** [comment]
Thanks for your help @kd-11.  After your reference to the vulkan sdk I took a closer look at the version was using.  It was 1.2.170.  When I upgraded to 1.2.198, rpcs3 now compiles successfully, so I'll close this ticket.  At least we know that more recent vulkan-sdk builds are necessary.
