### ISSUE TITLE
gl: Verification failed in memory_barrier (GLRenderTargets.cpp:512)

### ISSUE THREAD

**Issue by csando** [RPCS3/rpcs3#11522]
Hello

Processor/GPU: 
AMD 3600x
AMD 5700xt anniversary ed. - Driver ver: 21.30.23.01-211018a-373652C
16GB ram
Windows 11 pro, fully updated
RPCS3, latest version from auto update
RPCS3 settings for this game are default except for necessary changes outlined in the wiki.
I have enabled the unlock FPS patch, and also installed this one to fix missing geometry: https://www.nexusmods.com/demonssouls/mods/39?tab=description

So, I was hoping to use openGL while playing this game, as the sound issues in echoey areas seem to clear up with Vsync off. Using openGL, I would then use the Radeon software to force vsync outside RPCS3. That was the thought, anyways.

When I tried, I noticed OpenGL won't load the game. It gets past the title screen, and menu, but once you load the game it's... game over. 

I then reset the Radeon settings to default (no forced vsync or anything) and tried again with the same result.

Attached are screenshots of the error (after I CTRL ALT DEL out of the game). Also RPCS3 logs.

Thanks for any assistance!
![rpcs3error](https://user-images.githubusercontent.com/42008162/153741627-fcad1fed-7e92-4abc-93a7-c8194401f372.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8055063/RPCS3.log)

**Comment by AniLeo** [comment]
GL is unusable on Windows right now, sound issues have nothing to do with Render, the game can be played just fine with Vulkan - ask for support on one of the appropriate platforms

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by csando** [comment]
> GL is unusable on Windows right now, sound issues have nothing to do with Render, the game can be played just fine with Vulkan - ask for support on one of the appropriate platforms
> 
> **Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**
> 
> Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).
> 
> The issue has been marked as **Invalid** and closed.

Hi there
Ok, so OpenGl doesn't work.
Putting that aside in response to your second comment:
Can you comment on the accuracy of this RPCS3 forum post then?
https://forums.rpcs3.net/thread-202304.html
Because the issue the poster experienced is the exact one I am facing, and the solution of disabling vsync as posted by user Shadow Dancer does indeed fix the problem.

**Comment by AniLeo** [comment]
> ask for support on one of the appropriate platforms

What they tried may fix the issue for them, but nearly everyone that plays this game does so using Vulkan, with or without VS. VSync is merely a flag to request VSync from the driver, there's no
