### ISSUE TITLE
[BLES01419] Metal Gear Solid HD Collection: Strong FPS drops in MGS3

### ISSUE THREAD

**Issue by katze1123** [RPCS3/rpcs3#11536]
## Quick summary
The game is usually running at 60fps. But is some places (specially in the jungle, boss fights, or alarms with a a lot of enemies), the game drops to until 30fps (and it seems to be in slow motion).

It is weird, I think it is some kind of CPU bottleneck, even when my CPU usage doesn't go over 50% (as you can see in the attached video)

## Details

My Setup:

- RTX 3070
- Ryzen 7 5800x (even tried to make OC until 4.8GHz, not soling the issue)
- 32Gb Ram at 3600Mhz
- Also Game and RPCS3 in SSD

#### 1. Please attach RPCS3's log.
https://mega.nz/file/k5MlhYrR#i-C996pmx1GJKqFyJ7tmAE3IdaChfjOf-UdzFt3U2VU

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
In the video you can see the hardware usage in detail while a play for 1 minute:
https://mega.nz/file/UlNjzSYa#XYv6Y1eYZIGAzDNjy271Vplp2-E_QNuQ3FVmTJjW-yM

Note: The audio is fine, I just didn´t record the audio source in OBS when I made the video

![Captura](https://user-images.githubusercontent.com/99496898/153934357-44e364ae-1c8f-414d-8eca-0886663d7e9a.PNG)

#### 5. Please provide your system configuration:
- SYS: RPCS3 v0.0.20-13282-2d5d5746 Alpha | HEAD
- SYS: AMD Ryzen 7 5800X 8-Core Processor | 16 Threads | 31.93 GiB RAM | TSC: 3.800GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19042, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3070' running on driver 511.65.0.0
- SYS: Firmware version: 4.88

Let me know if you need more info.

Best Regards

**Comment by YuriNator557** [comment]
This log is empty.
This game is marked as Ingame due specifically to performance issues in MGS3, this is normal and can only be fixed with a better CPU at the moment.

**Comment by MSuih** [comment]
The FPS drop is related to amount of drawcalls afaik, many PS2 ports suffer from the same issue. The slowdown happens because the game uses fixed timesteps and it only runs properly at 60 fps.

I'm closing this because there's no specific bug with this game, it just needs faster RSX emulation to run well.

**Comment by katze1123** [comment]
Can not be optimized? CPU is below 50% usage. Which CPU do you recommend me for running at 60fps without drops¿

Thanks for the help

**Comment by YuriNator557** [comment]
> Can not be optimized? CPU is below 50% usage. Which CPU do you recommend me for running at 60fps without drops¿
> 
> Thanks for the help

The CPU is being used as best as it can
The only CPU I have seen to be able to play MGS3 properly is the 12900k

**Comment by MSuih** [comment]
A lot has already been done to optimize it and perhaps even more can be done in future. But it is not an easy thing to fix.

**Comment by katze1123** [comment]
@MSuih I know how to code in Python. I could learn some C++ and try to contribute to the project. If you give some hints about where I can start to fix the problem, I can give it a change and try to compile some "test builds"
