### ISSUE TITLE
WRC 2 [BLES01442] black textures on cars when starting second race

### ISSUE THREAD

**Issue by segbed** [RPCS3/rpcs3#11533]
Black textures on cars when starting second race. First race is perfect. When I selecting a car for next race it is also OK. But when level is loaded and we suggested to change car settings we see car 3d model with partially black textures. If we starting the race we see same picture - black textures.

Same as described in closed issue: https://github.com/RPCS3/rpcs3/issues/6725

[WRC2_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8062851/WRC2_RPCS3.log.gz)
![WRC2 2022-02-14 203526](https://user-images.githubusercontent.com/53876458/153917793-5d67094a-8baa-4e87-88d2-eaf15d16139d.png)

* OS  Win11
* CPU 10600k4800
* GPU 3070
* Driver version 511.65
* SSD/32GB...

Asynchronous texture streaming - on/off same result.
Strict mode - same result.
Def settings - same result + wrong colored textures on cars event on first race.

**Comment by kd-11** [comment]
The most important options to test for this one would be "read color buffers" and "write color buffers"

**Comment by segbed** [comment]
my settings were: write color buffers - enabled.
Other combinations do some glitches on car preview before first race.
Tested no - both enabled:
![WRC2 2022-02-14 214629](https://user-images.githubusercontent.com/53876458/153927004-998b7607-b6f1-4811-bc6f-37f37a4453b9.png)
RCB on wcb off:
![WRC2 2022-02-14 214901](https://user-images.githubusercontent.com/53876458/153927292-087c321f-eb1b-47b0-b924-7f43bd05a725.png)
Both off: 
![WRC2 2022-02-14 215056](https://user-images.githubusercontent.com/53876458/153927455-746f8463-8835-4ccd-afa8-1039d6aed839.png)

**Comment by kd-11** [comment]
I can't tell from the response if enabling the settings helped your issue or not.

**Comment by segbed** [comment]
nope, same or worser. E.g. when both enabled textures which were black become wrongly colored. So any combination of "read color buffers" and "write color buffers" didn't fix the issue.

**Comment by benderscruffy** [comment]
RPCS3 v0.0.26-14717-5bb89328 Alpha | master
this has been fixed
![BLES01442_screenshot_2023_02_16_16_29_57](https://user-images.githubusercontent.com/2696404/219310864-9c5a2f13-3212-4cdf-8c8a-24218bd1a703.png)
![BLES01442_screenshot_2023_02_16_16_31_29](https://user-images.githubusercontent.com/2696404/219310880-88fa55f0-f9b0-4257-8878-0a2aef1c553b.png)
![BLES01442_screenshot_2023_02_16_16_31_30](https://user-images.githubusercontent.com/2696404/219310889-6d2fabe1-7d88-4554-8f33-0149bcf25bd1.png)
can be closed

**Comment by Asinin3** [comment]
The person who said this was fixed deleted their comment... let us know if this needs to be re-opened.
