### ISSUE TITLE
MacOS: Fight Night Champion runs in SlowMotion

### ISSUE THREAD

**Issue by Crazzak** [RPCS3/rpcs3#11531]
Dear RPCS3 Devs, thanks for Porting that Emulator to MacOs.
A Few Games are working very fine but Fight Night Champion doesn't. 
At the first Start everything is fine. The Menu runs very smooth but when you are in the Fight you have a laggy Sound and a Slow-Motion Gameplay.

My Device is a Apple M1 Mini whit Monterey 12.0.1

**Comment by Geforce94** [comment]
Very Nice to close without an answer. That´s why here are many Mates very angry.

**Comment by YuriNator557** [comment]
> Very Nice to close without an answer. That´s why here are many Mates very angry.

Meta: Invalid tag was added, this means you did not follow the template required when filing an issue report.
The base M1 is most likely not strong enough to run this game at full speed.

**Comment by Geforce94** [comment]
I has nothing to follow. I was not the Creator of this Issue. 
Second: I know this Game and i played it 2 years ago on a i7 4790, the 4790 is much slower than the Base M1 so it's a compatibilty Problem whit the MacOS System or the ARM Platform. To Close a Issue without testing it, is not the smartest Way to solve an Issue or made the Emulator better.

**Comment by YuriNator557** [comment]
If the game does not run in slow motion when running at low FPS then it would be better to report it on #11414

**Comment by Darkhost1999** [comment]
> Report it on #11414 

That is exactly why this issue is invalid. MacOS has no official support or official release yet. So there has been made a specific thread for reporting issues.
If the issues aren't reported to that thread they are invalid because there is no official support for that build.

**Comment by Satan86** [comment]
Fight Night Champion running in slow motion is not exclusive to Mac. This is a very demanding game and slow motion is a known side effect of CPUs that can't handle EA games. Tweaking settings such as Preferred SPU Threads in the CPU tab iof settings might mitigate the issue, but no guarantees.

**Comment by AniLeo** [comment]
Locking due to off-topic, this is far from following issue guidelines as indicated above. Not only that, the used hardware is below recommended requirements, the OS is not fully supported yet (there are dedicated tickets for it) and that game is listed as ingame. Issues for performance issues with ingame titles also fall on the compatibility report category, which shouldn't be done through a GitHub ticket.
