### ISSUE TITLE
FF7 From this point(battle scene),game it cannot continue.

### ISSUE THREAD

**Issue by tee4341** [RPCS3/rpcs3#11530]
## Quick summary
FF7 From this point(battle scene),game it cannot continue.   (enemy animation is loop forever)

## Details

From this point, it cannot continue.

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
![ff7 bug](https://user-images.githubusercontent.com/48321898/153774825-f5a93eaa-5836-4143-a8bb-56754a789e9c.gif)

#### 5. Please provide your system configuration:
* OS win11
* CPU i7
* GPU gtx950m
* Driver version 8.1.962
* etc.

**Comment by illusion0001** [comment]
No save game, no log.

**Comment by tee4341** [comment]
please wait for log.
game not continue to save point

**Comment by tee4341** [comment]
i can t find psx save game

**Comment by Jonathan44062** [comment]
Also, why are you reporting the issue with a PS1 game?, this is an PS3 Emulator, that problem is irrelevant lol
Wait for a mod to give you an answer

**Comment by tee4341** [comment]
95% psx work fine .but final fantasy is main game for psx is bug
