### ISSUE TITLE
Regression: Gran Turismo 5 crashes when loading GT Mode events (#11541)

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#11549]
Gran Turismo 5 crashes when loading GT Mode events, regression introduced by #11541
Tested on a Ryzen 5 5600x, GTX 1050 Ti 511.79 driver And Windows 11. Volkano doesn't work, OpenGL works, as expected, since the PR changes Vulkan
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8091721/RPCS3.log.gz)

**Comment by kd-11** [comment]
Probably due to holes in the page range. VKDMA works with 16K page size.

**Comment by kd-11** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/11701

**Comment by Satan86** [comment]
Fixed by #11701
