### ISSUE TITLE
[Feature Request] is there any way to play guitar hero live with keyboard only? without the guitar.

### ISSUE THREAD

**Issue by reoffspark6** [RPCS3/rpcs3#11543]
is there any way to play guitar hero live with keyboard only? without the guitar.

**Comment by TheGuitarHeroNerd** [comment]
Have you tried to see if it worked with keyboard? i would try before asking lol.

But yes you can play with keyboard, it might require some remapping lol.

**Comment by shiami** [comment]
@TheGuitarHeroNerd Can't get it working. Could you kindly show me how. Thanks!

**Comment by MSuih** [comment]
[This article](https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories#Configuring_Instruments) is for binding instruments from different games but it lists what the guitar buttons bound to on what ps3 controller button. So for example if you bind X to F1, it should activate the green fret ingame. Remember to change the device class too.
