### ISSUE TITLE
Some info about music bug with LLVM Recompiler

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1154]
For information here is the LLVM bytecode dump that is responsible for the broken music in Sonic CD : 

https://gist.github.com/vlj/d046b3c6a3d6b845a078

I disabled ranges of compiled block to find the faulty one using a "bisect" like method. On my machine it's the 223th block. There's nothing special except the use of bswap32 and bswap64, and merge_all mechanism.

If it rings any bell it may help.

**Comment by vlj** [comment]
A wild guess is that llvm recompiler doesn't swap bytes for a load or a store operation.

**Comment by Nekotekina** [comment]
The whole gist is 223th block?

**Comment by vlj** [comment]
yes, it's quite big, I'm trying to find a way to reduce the bug area.

**Comment by vlj** [comment]
I updated gist with the output from ppu disasm.

**Comment by vlj** [comment]
Another gist that call interpreter function copy except for branch instruction:

https://gist.github.com/vlj/dd1ae47070206ce68c26

It doesn't work either, so if the argument are correctly passed there is a high probability the branch instructions are wrong, which is quite annoying since they are more difficult to debug.

**Comment by vlj** [comment]
Ok it was tedious but at last I found the bad instruction, it's MTOCRF. If I interpret it the sound is ok, so I have to find why it's not correctly translated.

**Comment by danilaml** [comment]
I can confirm this. And tests are wildly wrong with this instructions? Why didn't I see it before you ask? See here >_< : https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/Cell/PPULLVMRecompilerTests.cpp#L695

**Comment by danilaml** [comment]
Shoud be fixed in fd5fbab1153850a1cd2a778ccb61dcdd0e6d547c
