### ISSUE TITLE
God of War 3 buttons drifting in a hold state

### ISSUE THREAD

**Issue by khmyznikov** [RPCS3/rpcs3#11558]
### Quick summary
After 1-2 minutes of play, buttons can't be held in a held state. Every button in the hold state starts randomly be not pressed and pressed again. Same behavior on Xbox wired/wireless and DualSense wired.

[How it looks video](https://youtu.be/0Qor8HCZD9Y)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8104767/RPCS3.log)

#### System configuration:
* OS Windows 10 19043
* CPU i7-12700K
* GPU RTX 3070 Ti 511.65

**Comment by Megamouse** [comment]
does this also happen if you set the pad handler mode to single threaded?

**Comment by Darkhost1999** [comment]
Same my Xbox one controller randomly started having the Cross button when pressed and held in sprint for shadow of mordor causing me instead of sprinting doing dodge rolls (aka double tapping Cross). And I know for sure that I am holding down the input.
This should be a regression though. Can you test for the build that broke the inputs?

**Comment by khmyznikov** [comment]
> does this also happen if you set the pad handler mode to single-threaded?
Yes. In single is maybe just a bit not that crazy but ruin gameplay in the same way. Some places are just inaccessible.

**Comment by Megamouse** [comment]
reports with patches applied are not allowed

**Comment by khmyznikov** [comment]
> reports with patches applied are not allowed

Thanks for the hint. Looks like the "Disable Layered Fog" patch caused this behavior.

**Comment by RMPowser** [comment]
I have this behavior with no patches enabled. 

```
NVIDIA system information report created on: 03/10/2024 15:16:06
NVIDIA app version: 10.0.0.499/p
Operating system: Microsoft Windows 11 Pro, Version 10.0.22631
DirectX runtime version: DirectX 12

Graphics Card
GPU processor: NVIDIA GeForce RTX 4090
Direct3D feature level: 12_1
CUDA cores: 16384
Graphics clock: 2580 MHz
Resizable bar: No
Memory data rate: 21.00 Gbps
Memory interface: 384-bit
Memory bandwidth: 1.01 TB/s
Total available graphics memory: 57213 MB
Dedicated video memory: 24564 MB GDDR6X
System video memory: 0 MB
Shared system memory: 32649 MB
Video BIOS version: 95.02.18.80.e9
IRQ: Not used
Bus: PCI Express x16 Gen4
Device ID: 10DE 2684 467519DA
Part number: G139 0330

Driver: Game Ready Driver - 551.76 - Mar 4, 2024
Display: 2560x1440,360Hz
CPU: 13th Gen Intel(R) Core(TM) i9-13900K
RAM: 64.0 GB
Storage (4): SSD - 931.5 GB,SSD - 489.0 GB,+2 more
```

**Comment by KaueSabinoSRV17** [comment]
For anyone still having this problem

- locking on low FPS did not work for me
- In my case this happened using any MLAA patch (turning them off solved the problem)
- To use MLAA and still solve the problem, I updated the game from version 1.0 to 1.0.3

**Comment by Cactuxfrombrazil** [comment]
what fixed it for me (mostly) was settng the fps cap to ps3 native.

**Comment by navidesma** [comment]
> For anyone still having this problem
> 
> * locking on low FPS did not work for me
> * In my case this happened using any MLAA patch (turning them off solved the problem)
> * To use MLAA and still solve the problem, I updated the game from version 1.0 to 1.0.3

## disabling the MLAA patches also fixed my problem.

**Comment by GuilhermeRaposo** [comment]
> For anyone still having this problem
> 
>     * locking on low FPS did not work for me
> 
>     * In my case this happened using any MLAA patch (turning them off solved the problem)
> 
>     * To use MLAA and still solve the problem, I updated the game from version 1.0 to 1.0.3

Thanks, updating the game to 1.03 also seems to have fixed it for me.
