### ISSUE TITLE
Regression: James Cameron AVATAR - Foliage flickering #9613

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#11552]
PR that Broke it: https://github.com/RPCS3/rpcs3/pull/9613

**Comment by Xcedf** [comment]
There are 2 possible offending commits:
1st one 644aeaa3
and 3rd one 8d67a1a6
1st one doesn't work by itself, requires the 3rd to avoid Verification fail issue, my bets on 1st.

**Comment by kd-11** [comment]
It happens if you enable GPU-side copies, the other options don't matter. You can work around it by just setting `caps.supports_zero_copy` to false in VkTexture.cpp.
That said, I'm really not sure why it fails when using DMA layer vs loading directly from CELL. This requires some investigation.

**Comment by kd-11** [comment]
And of course its caused by something terrible. The game is streaming updates every few draw calls to some textures, causing clobbering when using the DMA layer which acts as a cache. It is possible to work around this to some extent but it will undoubtedly cause problems. A toggle to disable the caching is going to be the solution here.

**Comment by Xcedf** [comment]
@kd-11 did my investigation, placing caps.supports_zero_copy = false in TextureUtils.cpp do the trick, no more flickering:
![15](https://user-images.githubusercontent.com/7060586/154801717-a7509c63-c001-42e8-bc70-01a5a69cd364.jpg)
![14](https://user-images.githubusercontent.com/7060586/154801721-9efd6a2b-bbca-4e12-85cd-4f9b29e67160.jpg)

**Comment by kd-11** [comment]
I fixed it properly using GCM label handling on the GPU but performance is atrocious. It is behind an option, but I still think it can be improved a bit before PR. That fix should also fix some other strange bugs like flickering in toy story 3 without using strict mode.
