### ISSUE TITLE
Regression: inFAMOUS 2 [BCUS98125] audio broken (#9760)

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11553]
https://github.com/RPCS3/rpcs3/pull/9760 Broken audio
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8102817/RPCS3.log)
https://github.com/RPCS3/rpcs3/pull/11215 Works perfectly
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8102819/RPCS3.log)

**Comment by kd-11** [comment]
Can confirm. Very strange audio pop, seemingly from one ear.

**Comment by Darkhost1999** [comment]
Additional info that might help
I just now tested PPU Interpreter (static) works fine on the modern build.
I turned off my left channel speaker audio (no change) turned it back on.
Turn my right channel speaker off and the game was completely muted. With the left channel on full volume.
This is using the downmix to stereo audio and no settings were changed from my logs already provided.
If you'd like logs of the PPU Interpreter I can provide those from the modern build as working just fine.

**Comment by AniLeo** [comment]
Adding @Nekotekina since it broke on #9760

**Comment by Xcedf** [comment]
Retested this issue, not 9670 broke this, regression caused by github.com/RPCS3/rpcs3/pull/11379
this exact commit https://github.com/RPCS3/rpcs3/pull/11379/commits/df24cff0b19eaaaebe06b6037a97dbe9120e351e
reverted it for recent build - audio works

**Comment by Darkhost1999** [comment]
This is what I hear roaring rapids. The audio is bad I would not wear headphones for the video.
https://youtu.be/V_Iwzc-hNsg
There is no strange audio pop, seemingly from one ear.
I am in progress of cloning the repository in order to test those changes you mention locally and report if the fix also applies to me.
> Turn my right channel speaker off in windows settings and the game was completely muted. With the left channel on full volume.

As of my tests today this is outdated. Audio is not isolated to 1 channel anymore.

**Comment by Darkhost1999** [comment]
> this exact commit https://github.com/RPCS3/rpcs3/pull/11379/commits/df24cff0b19eaaaebe06b6037a97dbe9120e351e
> reverted it for recent build - audio works

Just finished testing reverting it locally on my PC. Still broken.

**Comment by Xcedf** [comment]
@Darkhost1999 did you remove PPU cache before testing it?

**Comment by Darkhost1999** [comment]
> @Darkhost1999 did you remove PPU cache before testing it?

No, I did not. The fix does work. :facepalm:

**Comment by Xcedf** [comment]
@Darkhost1999 It's annoying, but that's how it works, everytime smth changed in PPU LLVM - cache must be recompiled. Thanks for confirming.

**Comment by Nekotekina** [comment]
What PPU settings are enabled when the issue is reproducible on master? A bunch of them on Advanced tab.

**Comment by Xcedf** [comment]
I tried all that available, no difference

**Comment by Darkhost1999** [comment]
The issue shouldn't require any settings changed for it to immediately have sound issues as soon as you press start a new game

**Comment by Nekotekina** [comment]
That's weird that interpreter works since it uses the same logic in master.

**Comment by Darkhost1999** [comment]
Yea, it is weird. Interpreter works fine.
Llvm does not.
All ppu settings in advanced tab appear to have no effect.
Rolling back https://github.com/RPCS3/rpcs3/commit/df24cff0b19eaaaebe06b6037a97dbe9120e351e
And clearing the ppu cache. Works just fine too.

At first I thought because everyone seems to have a different experiences from just a crackle here to roaring rapids constantly that it was just a sign of an underpowered pc. /shrug

**Comment by Nekotekina** [comment]
Try #11916 (some wild guess) — don't forget to clear PPU cache.

**Comment by Darkhost1999** [comment]
Yep works just fine. To solve audio issues here

**Comment by Darkhost1999** [comment]
Fix for audio merged
