### ISSUE TITLE
Shortcut creation fails

### ISSUE THREAD

**Issue by Skynet19972029** [RPCS3/rpcs3#11562]
## Quick summary
The Shorcut creation fails.

## Details
Log:
E SYS: Failed to create shortcut: Saving file to desktop failed (The system cannot find the path specified. [-2147024893])
E GameList: Failed to create desktop shortcut for GAME NAME

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8105118/RPCS3.log)

* OS Windows 10 Pro x64 21H2
* Desktop path is D:\Users\USERNAME\Desktop (There is no path in C: which is why I belive it could be failing in my system)
* CPU R7 5800X
* GPU RX 5600XT

**Comment by Megamouse** [comment]
This might be a hint that your environment variable are outdated.
If you type %USERPROFILE% in your file explorer and press enter, it will usually point you to the correct folder.
So if it doesn't, your USERPROFILE environment variable might be wrong.

Before pressing enter:
![image](https://user-images.githubusercontent.com/23019877/154868534-49866355-5eb5-4faf-9bbe-1aecaf10d6cb.png)

Afterwards:
![image](https://user-images.githubusercontent.com/23019877/154868582-53bc83c8-1286-42b3-94f7-9e154a9b1f89.png)

**Comment by Skynet19972029** [comment]
It's a new windows installation.
As I said, I've moved my Desktop from C  to D
![Untitled](https://user-images.githubusercontent.com/72090667/154868661-59960f2e-c739-4ec7-a8c6-b9626911e104.png)

**Comment by Megamouse** [comment]
then you've done something wrong

**Comment by Skynet19972029** [comment]
I've just created a fake Desktop folder in C:\Users\SkyNET
 and it created the shortcut.
The problem is in how you are fetching the current desktop. I am no programmer, but, there is nothing wrong in my side.
Every installer I've installed creates the shortcuts on the D desktop path.

**Comment by Megamouse** [comment]
it means your environment variable is wrong, as mentioned before

**Comment by Skynet19972029** [comment]
How could it be wrong if I just showed you the the Desktop folder is shown using %USERPROFILE% variable?

**Comment by Megamouse** [comment]
well. because it's the same variable we use to get that folder

**Comment by Megamouse** [comment]
it's probably some weird windows shenanigans.
Maybe we have to increase the power level on the windows code branch.
There must be even more windows specific code to unravel its mysteries.
I'll probably take a look tomorrow

**Comment by Skynet19972029** [comment]
No problem, Megamouse.
I am in no rush. Just saw the new feature, tried it and wanted to report the issue.
Thank you for everything.

**Comment by Megamouse** [comment]
Thanks for finding this. I couldn't believe it until you insisted. Sorry.
Try #11563 once it's ready.
I used a different approach that at least still works for me and seems to be the proper way based on some more google fu.

**Comment by Skynet19972029** [comment]
Will test as soon as it's up.
Thank you and no need to be sorry!

**Comment by Megamouse** [comment]
The issue was closed because I merged the PR.
Feel free to reopen the issue if it still doesn't work afterwards.
