### ISSUE TITLE
[Linux] Game shortcut creation fails with "SYS: Failed to create .desktop file"  ( Appimage)

### ISSUE THREAD

**Issue by Leopard1907** [RPCS3/rpcs3#11565]
## Quick summary
Newly added shortcut feature doesn't seem to be working.

## Details

Trying to create a shortcut on desktop fails with `SYS: Failed to create .desktop file`. I use Appimage build.

## Log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8111536/RPCS3.log)

**Comment by Megamouse** [comment]
please try with #11567

**Comment by Megamouse** [comment]
It seems you don't have a Desktop folder?

**Comment by RipleyTom** [comment]
Like Mega asked do you have a $HOME/Desktop folder?
Which WM are you using?
What does `echo $XDG_DESKTOP_DIR` show?

**Comment by Leopard1907** [comment]
- Yes, i have.

`home/asus/Masaüstü` Masaüstü= Desktop

Also `.directory` in `/home/asus/Masaüstü` has this entry: 

```
[Desktop Entry]
Icon=user-desktop
Type=Directory
```
- `echo $XDG_DESKTOP_DIR` returns an empty line.

- Kwin is the WM i use

- Extra note: Other apps such as Steam and Heroic Launcher are able to create shortcuts with this setup.

**Comment by Leopard1907** [comment]
@Megamouse 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8115777/RPCS3.log)

Log from PR build. Issue persists.

**Comment by Megamouse** [comment]
What's the contents of this file?
~/.config/user-dirs.dirs

**Comment by Leopard1907** [comment]
```
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run.
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="$HOME/Masaüstü"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Şablonlar"
XDG_PUBLICSHARE_DIR="$HOME/Genel"
XDG_DOCUMENTS_DIR="$HOME/Belgeler"
XDG_MUSIC_DIR="$HOME/Müzik"
XDG_PICTURES_DIR="$HOME/Resimler"
XDG_VIDEOS_DIR="$HOME/Videolar"
```

**Comment by Megamouse** [comment]
Thanks. This confirms our suspicions.
I'll fix it later

**Comment by Megamouse** [comment]
I changed it. Can you test again please?

**Comment by Gvaz** [comment]
I'm having this issue on the Steam Deck, 

E SYS: Failed to create .desktop file: /home/deck/Desktop/gamename.desktop (read only)

**Comment by RipleyTom** [comment]
My guess is you're using the flatpak?
It is not supported and In all cases, as the error states, the file creation fails as the directory is be read only to Rpcs3.
ie not a RPCS3 issue.

**Comment by Gvaz** [comment]
Using the flatpack (or I guess emudeck) is the preferred way of installing apps for the Steam Deck, since the environment is somewhat locked down. The emulation itself works fine. I guess I just need to add rpsc3 manually do the permissions, how would you do that then?

**Comment by Leopard1907** [comment]
For permissions people use Flatseal on Flatpak apps. You can look into that.

**Comment by MakaiHanta** [comment]
> Я предполагаю, что вы используете flatpak? Он не поддерживается и Во всех случаях, как указано в ошибке, создание файла завершается ошибкой, так как каталог может быть прочитан только в Rpcs3. т.е. не проблема RPCS3.

No, this is the RPCS3 issue
