### ISSUE TITLE
[Feature Request] Move the resolution setting into the Advanced tab

### ISSUE THREAD

**Issue by KimiSha19** [RPCS3/rpcs3#11569]
The resolution setting is currently in the GPU tab and I believe it should be moved to the Advanced tab for the following reasons;

The setting is only useful in a select handful of games and causes most other games to crash or have broken graphics when used. A lot of new users see that setting and use it instead of Resolution Scaling not knowing that their game doesn't support it. 90-95% of games only work at the base resolution (1280x720) and need require Resolution Scaling to be used. A lot of issues reported on the Discord server are mainly because of people setting Resolution to 1920x1080 instead of using the scalar. 

I see no benefit of having this setting in the GPU tab and moving it would make upping the resolution for games a lot less confusing for newer users who aren't experienced enough.

**Comment by Augusto7743** [comment]
Your issue is about avoid users posting problems.
You are correct, but perhaps displaying a message to not change the resolution or an option to hidden menu options for each configuration tab is an better option.

**Comment by Megamouse** [comment]
This shouldn't be an issue anymore.
The setting is now much more foolproof
