### ISSUE TITLE
Dragon Ball Z: Battle of Z [BLES01941] Does not work when trying to join a lobby online

### ISSUE THREAD

**Issue by Junny4444** [RPCS3/rpcs3#11566]
## Quick summary
I am unable to connect to lobbys in this game
## Details

Please describe the problem as accurately as possible.
When my friends go into the co-op mode I am able to make a lobby just fine but when my friends see my room it says "failed to join room" after it hanging for around a minute.

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8111797/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.

![unknown](https://user-images.githubusercontent.com/76232378/155018719-27fae298-2e74-4f64-b661-515afbd0c05f.png)

#### 4. Please provide comparison with real PS3.
You are able to join the lobby on a real PS3
#### 5. Please provide your system configuration:
* Windows 10
* Intel Core I9-9900K 3.60 GHZ
* RTX 3090
* Version: 30.0.14.9729

**Comment by RipleyTom** [comment]
It should work now?

**Comment by RipleyTom** [comment]
Should be fixed, reopen if it is not.
