### ISSUE TITLE
Skate 3 running in "Slow-Motion"

### ISSUE THREAD

**Issue by gaiabun** [RPCS3/rpcs3#11561]
Hi, just today I got my dualshock 4 controller working with my pc so I decided to try out playing Skate 3, after about 3 hours playing around with settings and stuff I got the game from about 7-1 fps to running an almost constant (capped) 30 fps however I have two problems, the main thing I am concerned with is that the game seems to be running in basically slow-motion and in-game time is incredibly slowed down. The second problem is that the audio is constantly clipping and bugging to the point where I just don't play with sound.

Specs
I5-4460 (3.20 Ghz)
R9 280x (3gb)
16 GB DDR3 (1333 Mhz)

**Comment by RainbowCookie32** [comment]
Slow motion and bad audio happens when trying to run this game on an underpowered CPU, which is the case on a 4460. See the wiki for some settings suggestions, but it's not really something you can fix without a CPU upgrade. 4 threads is too low for demanding PS3 games
