### ISSUE TITLE
Everybody's Golf 2 (PSX) Drawing has a problem, I don't know what's going on

### ISSUE THREAD

**Issue by tee4341** [RPCS3/rpcs3#11572]
Everybody's Golf 2 (PSX) Drawing has a problem, I don't know what's going on
![ScreenRecorderProject1](https://user-images.githubusercontent.com/48321898/155398031-654cc50e-91eb-470b-8a4c-37edc764c56b.gif)
[motor toon.log](https://github.com/RPCS3/rpcs3/files/8135238/motor.toon.log)

**Comment by Megamouse** [comment]
Please attach a log file running the game

**Comment by tee4341** [comment]
[motor toon.log](https://github.com/RPCS3/rpcs3/files/8135240/motor.toon.log)

**Comment by AniLeo** [comment]
That isn't a log file, read the issue guidelines

**Comment by Megamouse** [comment]
that's not the log file

**Comment by Minacat1** [comment]
Someone make counting stars wow wow wubbzy plz by onerepublic
