### ISSUE TITLE
Resistance 2 (BCES00226) - No longer working

### ISSUE THREAD

**Issue by hockland** [RPCS3/rpcs3#11578]
## Please do not ask for help or report compatibility regressions here, use [RPCS3 Discord server](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/) instead.

**## Quick summary
Please briefly describe what has stopped working correctly.**

According to the latest compatibility listings, Resistance 2 is classed as "playable". Tested RPCS3 with it, and the game freezes at numerous spots.

**## Details
Please describe the regression as accurately as possible.**

Game boots perfectly fine, but on going in-game and starting up a new game your taken to the first level. In the level your tasked with shooting a rocket at a large tank/mech robot, then told to run out of the room and enter a small tunnel, requiring you to crouch. It is at that spot that the first freeze occurs, requiring you to close the game down.

If you boot it up and load a checkpoint save (as one happens right around the time of that first freeze) you can continue on for a few further minutes, taking on enemies, shortly after the game freezes again with error:

F {RSX [0x19f7a1c]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderTargets.h:81[:10], in function as_rtt)

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
* Please see [How to find the build that caused a regression](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression.3F) in our wiki.
* You can find [History of RPCS3 builds](https://rpcs3.net/compatibility?b) here.

I am not sure of which build introduced the issue, as the game has never worked on my computer.

#### 2. Please attach TWO logs:
* One for the build with regression.
* One for the build that works as expected.

##### How to obtain RPCS3's log:
* Run the game until you find the regression.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
[Log.gz](https://github.com/RPCS3/rpcs3/files/8138813/Log.gz)

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc.
	And drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 4. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

I'll do you one better. Got a Youtube video of it occurring.
https://www.youtube.com/watch?v=fYtByA4fkfk&feature=youtu.be

#### 5. Please provide comparison with real PS3.

On a real PS3 this does not happen

#### 6. Please provide your system configuration:
* OS
Windows 10
* CPU
Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz 3.79 GHz
* GPU
NVIDIA GeForce RTX 2060
* Driver version
511.79

#### Please include.
* Anything else you deem to be important

**Comment by Megamouse** [comment]
issues with patches applied are not allowed

**Comment by hockland** [comment]
Then I'll go get another log without patches enabled as it happens with or without them on

**Comment by RainbowCookie32** [comment]
Use default settings while you are at it. GPU Texture Scaling is known to cause issues, and I don't think Accurate xfloat or Strict rendering mode are needed

**Comment by Megamouse** [comment]
It may also help to update the game

**Comment by hockland** [comment]
That did the trick. Sorry, was told to make a PR about the issue on the forums.
