### ISSUE TITLE
Uncharted 2 [NPEA00365] After update to 13317 light in game broke down

### ISSUE THREAD

**Issue by paradise999** [RPCS3/rpcs3#11571]
## Quick summary
After update from 13312 to 13317 light in game broke down

## Details
Yesterday I finally found settings for stable work. Water in chapter 3 is still flickering, but it's only problem now. For me ok, I play farther.
Today, after update, light in menu and game broke down and water disappear.
Run it with default settings broke shadows, but back light to normal.
By brute force method I found that light broke because of Write Color Buffer.
More interesting that in RSX Capture no problems with light.
Update: I know, this not about problem, but now Allow Host GPU Labels fix problem with water flickering

Logs:
[RPCS3 v13312.log](https://github.com/RPCS3/rpcs3/files/8126844/RPCS3.v13312.log)
[RPCS v13317.log](https://github.com/RPCS3/rpcs3/files/8126841/RPCS.v13317.log)

RSX Capture:
https://www.dropbox.com/s/0sh9j72e3vbv4tf/RSXcaptures.7z?dl=0

Screenshots and videos:

13312:
Menu - https://www.dropbox.com/s/tuj8gr7qn9w7wkc/Start%20menu%2013312.mp4?dl=0
Water - https://www.dropbox.com/s/dfqfy351xvf47g1/Water%2013312.mp4?dl=0

13317:
Menu - https://www.dropbox.com/s/ljyqptkrsx8z4rr/Start%20menu%2013317.mp4?dl=0
Water - 
![Water 13317](https://user-images.githubusercontent.com/32838010/155383094-74f28c0f-95a3-4380-82b2-19e520a7a660.png)

Configuration:
* OS - Windows 11
* CPU - Ryzen 7 3700X
* GPU - RTX 3070 OC (ROG)
* Driver version - 511.79
* Audio Card - external Asus Soar
* RAM - G.Skill 32 Gb 3200 MHz

**Comment by Xcedf** [comment]
Water requires Accurate ZCull, but it will hurt performance a lot, also noticed you're using Multithreaded RSX, doesn't have shadow maps fail like yours, but lots of garbage in Chapter 3 with it, try it Off.

**Comment by kd-11** [comment]
I know what the cause is, there is a very small change in how MTRSX sync works around texture reads, I'll revert with the next PR. For now you can disable MTRSX if your performance is not too negatively impacted.

**Comment by paradise999** [comment]
Like I wrote in Update - now Allow Host GPU Labels fix problem with water flickering and FPS still avg 20-30. I just hope, current setting enough stable for full game ending without crash

**Comment by paradise999** [comment]
> Water requires Precise ZCull, but it will hurt performance a lot, also noticed you're using Multithreaded RSX, doesn't have shadow maps fail like yours, but lots of garbage in Chapter 3 with it, try it Off.

Like I wrote in Update - now Allow Host GPU Labels fix problem with water flickering and FPS still avg 20-30. I just hope, current setting enough stable for full game ending without crash

**Comment by Xcedf** [comment]
@paradise999 well maybe you had the lucky run, but for me  Allow Host GPU Labels doesn't affect water in any way, especially in chapter 3.
> I know what the cause is, there is a very small change in how MTRSX sync works around texture reads, I'll revert with the next PR. For now you can disable MTRSX if your performance is not too negatively impacted.
This game is better without MTRSX, it hurts performance a little

**Comment by paradise999** [comment]
@Xcedf Lucky...) ahaha. It again die when I go farther. I still trying find solution of it. I up driver wake up delay to 100 and now it run until I go to new location) Very strange problem, because i can't figure out what exactly crashed. It's like random. I can look at big location or at the wall, but, I think if, there start new script, not used yet, its crashed and i can't find error, what crashed

**Comment by Xcedf** [comment]
@paradise999 Strict Render Mode cuts almost half fps in this game, better not to use it, and if you want your game to be more stable use Wake-Up Delay at least 400.

**Comment by coolllman** [comment]
I have flickered issue with 13317 in uncharted 2, with 13312 all good

**Comment by kd-11** [comment]
Test https://github.com/RPCS3/rpcs3/pull/11576

**Comment by coolllman** [comment]
Not fix flickered graphics, i would open new issue.

**Comment by kd-11** [comment]
@coolllman Try with https://github.com/RPCS3/rpcs3/pull/11580

**Comment by paradise999** [comment]
@Xcedf Become stable only with 800 Wake-Up Delay

**Comment by coolllman** [comment]
All good now, issue fixed, thanks kd-11, you the best)
