### ISSUE TITLE
[Feature Request] RSX double the number of ROPs and fill rate

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#11579]
PS2 is very well known by speed of fill rate and number of ROPs comparing beng twice the PS3 speed.
Thus being the PS2 color quality is high.
PS3 color quality is average for some games and not is related about color saturation.
I not understand if is possible implement an feature to RSX emulation double the number of ROPs thus the colors will be much better helping to "fix" blurry colors for some games (Pro Evolution Soccer series and others sports games).
That feature break emulation or game code ?
Have an nice week.

**Comment by kd-11** [comment]
I do not understand what you're trying to say here. We do not emulate a fixed number of ROPs, because we do not have a software renderer, we use your GPU for rasterization without imposing any limits.

**Comment by Augusto7743** [comment]
Thanks very much for reply and all your work done emulating RSX.
I said PS2 creates colors with higher quality than PS3 because fill rate is more fast and have twice more ROPs than PS3.
In some PS3 games colors are blurry and in PS2 games colors are brilliant vivid.
PS3 graphics details are better than PS2, but about color vivid the PS2 is better.
I not understand if is possible implement an feature to get better color quality, but in any way originally PS3 have some games output strange color quality in TV.

See the screenshots below

![1](https://user-images.githubusercontent.com/21184987/155964161-3a9777a1-37db-48ef-9a22-024c78e77a29.png)

![2](https://user-images.githubusercontent.com/21184987/155964264-09effcaf-08e1-4941-b2c1-0a5e6ec74afd.png)

Colors are blurry


![3](https://user-images.githubusercontent.com/21184987/155964326-bbf913fe-dfd5-4f91-bc6b-50e30f428e2f.jpeg)


In PS3 side no exactly the dark filter above all the colors, but compare some details with the PS4 version.


![4](https://user-images.githubusercontent.com/21184987/155964353-ffb61645-54a9-446b-a814-042aec1aac4e.jpeg)


PS3 PES 2018 version.
See again blurry colors.


Have several PS3 sports games with blurry colors mainly soccer games.
I not understand if that was done by game developers to have more performance and thus avoiding coding SPUs.
Anyway an feature to have better colors is an good solution thus how RPCS3 hack the internal resolution for better graphics.

**Comment by YuriNator557** [comment]
You are comparing PS4 graphics to PS3, this is completely irrelevant

**Comment by Augusto7743** [comment]
Irrelevant ? No.
The compare between PS3 and PS4 was to show how PS3 colors not are vivid.
Closed because "irrelevant" reply ? I not had compared graphics between PS3 and PS4. Bad understand about my reply.
Really RPCS3 doing any feature to better colors is good to add thus how internal resolution.

**Comment by RainbowCookie32** [comment]
How "vivid" the colors are was up to the game's developers and how they decided to make their game. It has nothing to do with ROPs or fill rate. Compare to a PS3's footage and RPCS3's colors are probably the same.
Comparing to PS4 is useless, since the game is running completely different rendering code, and most likely with extra details and effects that the PS3 couldn't do.

**Comment by Augusto7743** [comment]
Oh not. I am not expressing myself correctly.
I will try to say in a simpler way.

The comparison between PS2-3-4 not was about graphics because is really irrelevant and not sense, but to say PS3 colors are less brilliant.
In other words my post was about if is possible RPCS3 have better colors output similar to that was the PS2 or even PS4.
In interview Polyphony said PS2 is twice more faster than PS3 to fill rate texture and having have others details better than PS3.
PS2 colors are very good and I not undestand if is because of faster fill rate.
I said that only to show how could be good RPCS3 having an better color output similar how PS2 does.

If you have played some PS3 you known how have games having low color quality output. Even Uncharted series not have high quality color at point that not look "vivid".
In other words is how if PS2 print graphics in an photographic paper and the PS3 in an simple paper or even yet comparing colors between LCD TFT panel and an IPS panel.
Maybe for some users my post look not sense, but in truth was correct.
Have games that in some moments you see how in video screen have areas with colors being strange blurry or low quality that even configuring anisotropic or using high internal resolution not will have better colors.
I believe that is possible to improve colors detail in RPCS3.
All above that I am trying say you see easily in PS3 soccer and racing games.

I not understand wich graphics terms to say if saturation or bright controls are an option to fix that problem that happen in several PS3 games.
See the video below how the PS2 was faster and how the colors are vivids, but please not is for compare graphics. That is about if is possible have an better color output. Even PCSX2 have options to have change the color quality and really works not changing game code.

https://www.youtube.com/watch?v=bRXrrscvfcQ&t=10068s
