### ISSUE TITLE
F {PPU[0x1000000] Thread (main_thread) [0x0034935c]} VM: Access violation reading location 0x50 (unmapped memory)

### ISSUE THREAD

**Issue by tony69084** [RPCS3/rpcs3#11577]
God of war: Ascensions isn't starting with this issue. Can somebody help with it.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8136707/RPCS3.log)

**Comment by RainbowCookie32** [comment]
Most likely bad settings, you have some library overrides enabled for some reason. Support is provided on our Discord server, not here.
