### ISSUE TITLE
Persona 4 Arena Ultimax [BLUS31469] cutscenes stutters in 11568 build onward

### ISSUE THREAD

**Issue by Abdulelah-99** [RPCS3/rpcs3#11573]
## Quick summary
Cutscenes stutters in 11568 and 11570 builds

## Details
Yesterday, I was playing the game normally and everything were ok, but after I downloaded the 11568 build the cutscenes are stuttering, I waited for the next update (11570) and thought it might solve the problem but it didn't.
There is another bug with the game which is after defeating the opponent, the loading screen flickers with the character I fought, and don't know after which update it brought this problem.

Logs:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8128041/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8128057/RPCS3.log)

Videos:
11567 build:

https://user-images.githubusercontent.com/100318554/155416206-9d9a2829-4812-48ff-a3bb-e161dd9de87c.mp4

11568 build onward:

https://user-images.githubusercontent.com/100318554/155416655-681d84b6-74c8-48a0-b1af-a9b77db70759.mp4

the extra problem that I mentioned above:

https://user-images.githubusercontent.com/100318554/155417112-4c6458bb-ea01-4687-b9e8-a70f8720af95.mp4

Configuration:

-OS - Windows 10
-CPU - Ryzen 5 3600
-GPU - RTX 3070 FTW3 ULTRA
-Driver version - 511.79
-Audio Card - Headset Earphone (Artics 5 Chat)
-RAM - G.Skill 16 GB 3200 MHz

**Comment by kd-11** [comment]
Try with https://github.com/RPCS3/rpcs3/pull/11576

**Comment by kd-11** [comment]
Closing as fixed.

**Comment by Abdulelah-99** [comment]
It didn't fixed it as for 11567 build sadly, but it is now less stuttering than the previous builds (11568 to 11220)

**Comment by kd-11** [comment]
@Abdulelah-99 Try with https://github.com/RPCS3/rpcs3/pull/11580

**Comment by Danhanado** [comment]
This issue seems to have returned, I'm not sure when it came back but on the latest version there's intense cutscene stuttering and some in-game stuttering too, I reverted my version back to the day I made a shortcut for the game (v0.0.28-15212-a6d8c434) and the cutscenes and the in-game performance is perfect

**Comment by AniLeo** [comment]
Not the same bug
