### ISSUE TITLE
Uncharted 1 Weird Broken Graphics - Regression

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#11574]
The game represents this small graphic bug

_Please attach TWO logs:_
The latest one working - 0.0.20-13312
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8128794/RPCS3.log.gz)
The broken (#11568) - 0.0.20-13317
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8128836/RPCS3.log.gz)

_If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it._
I don't think this RSX can help due to this weird issue
![image](https://user-images.githubusercontent.com/78843189/155436876-d15c99c9-6dad-4ff6-86a1-9b244a3b3a8c.png)

Here's the RSX capture just in case
https://www.mediafire.com/file/o3z045y20pmqh6a/BCUS98103_20220223185829_capture.rar/file

_Please attach screenshots of your problem._
Before:
![image](https://user-images.githubusercontent.com/78843189/155435846-0744e2af-0c0b-4ac9-a81a-f738272f0f3a.png)

After:
![image](https://user-images.githubusercontent.com/78843189/155436213-754514d3-14ef-451d-bff4-ddec2a103d07.png)

_Please provide your system configuration:_
OS - Windows 10 21H2 Build: 19044
CPU - i7 8700
GPU - GTX NIVIDIA 1070 Ti
Driver version - 511.23.0.0

**Comment by kd-11** [comment]
Closing as fixed, request to reopen otherwise. https://github.com/RPCS3/rpcs3/pull/11576

**Comment by Jonathan44062** [comment]
Sadly, the problem continues using 11576

**Comment by kd-11** [comment]
@Jonathan44062 It is fixed by https://github.com/RPCS3/rpcs3/pull/11580

**Comment by Jonathan44062** [comment]
Yes, it's fixed, I can confirm 
![image](https://user-images.githubusercontent.com/78843189/155799332-35a3b536-65d1-469c-b1a7-271c2f1e68aa.png)
