### ISSUE TITLE
Modnation Racers Missing Geometry

### ISSUE THREAD

**Issue by RinMaru** [RPCS3/rpcs3#11581]
seems the game has missing geometry on some tracks and the great wall error even if settings from wiki are set up WCB and Zcull settings dont fix it
![Screenshot 2022-02-25 193224](https://user-images.githubusercontent.com/15071652/155829070-cae66d6d-e407-465c-8315-ccd257c6abd0.png)

RPCS3 v0.0.20-13320-6db5d836 Alpha
Windows 11
Ryzen 5 5600X
RX 480 4GB
22.2.3
20GB DDR4 RAM

**Comment by RinMaru** [comment]
https://drive.google.com/file/d/1SBKAt7SAa2BeR1xBTVf_lXh_r4wxx7KN/view?usp=sharing RSX Capture here

**Comment by Darkhost1999** [comment]
The link isn't public? Just requires someone to request access to the file from the owner.

**Comment by RinMaru** [comment]
fixed the link

**Comment by Megamouse** [comment]
missing log

**Comment by RinMaru** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8148501/RPCS3.log)
https://drive.google.com/file/d/1M3t5g9fFWVDik61R4QM7zcdFMtwClUBt/view?usp=sharing
couldnt repro in this build but a new issue crept up. invisible geometry on the same track

**Comment by kd-11** [comment]
Then open a separate issue if this one is already fixed in master.

**Comment by RinMaru** [comment]
Ill reopen if i come across this again

**Comment by Sorriso337** [comment]
I'm having the same problem in the tutorial page, these have another solution?

**Comment by Sorriso337** [comment]
After reading another issues, i found the solution here 'https://github.com/RPCS3/rpcs3/issues/8695'
