### ISSUE TITLE
Linux Flatpak Xbox one controller not being recognized correctly. 

### ISSUE THREAD

**Issue by djhnsn** [RPCS3/rpcs3#11598]
## Quick summary
In the linux flatpak release, the xbox one controller is showing as connected but not working properly. 

## Details

The left stick is not centered, the right stick operates the triggers, the left trigger is "brake"

* OS Manjaro
* CPU Intel 8th generation
* GPU gtx1060 maxq

Dualshock 4 works fine.

**Comment by Darkhost1999** [comment]
Few things here.
1st the flatpak isn't maintained by RPCS3. Try the appimage on rpcs3.net instead of the flatpak.
2nd personally I use this
https://gitlab.com/xboxdrv/xboxdrv
With Linux. And has worked really well for me for xbox drivers. Idk which you use. But I would consider options.

**Comment by djhnsn** [comment]
Thanks, I was considering abandoning the flatpak, but I can't figure out where the game saves are located. They aren't in the directories mentioned in the quickstart guide. Any idea?

**Comment by Leopard1907** [comment]
@djhnsn https://twitter.com/rpcs3/status/1243708769835585536?t=UyUGMfceaGLMfjqcUIz7kw&s=19

Click view folder. Dolphin bar at top should show the full path when it is opened.

**Comment by djhnsn** [comment]
Thanks, Leopard. I ended up installing the rpcs3-bin package from the AUR and it is still doing the same thing. As far as what is handling my controller, I am not sure. Every controller I have connected to Manjaro has just worked out of the box. The xbox one controller works in all the windows native titles that it's supposed to via wine/proton.  

This is my output for pacman -Q | grep evedev

libevdev 1.12.0-1
python-evdev 1.4.0-3
xf86-input-evdev 2.10.6-3

**Comment by Minacat1** [comment]
�'Nz"@SEACREST:�!ZjG(FOOD �iNK'EWbJP"d�S%&2T*��0HUMPTYJ)D2SA�,ON%m WALL�G�IT� G TH��P�Z@MAGNOLIA�J(PLACE�C(SUBWA*�22�8BEEF%AN#�"@WILD%RIC3�?�0SSEROL:jJe�J""'6j�8BIUS%AS2(DANIE#:_�Ts�z�0WELCOM2&,H"PAR#������S�G�Z�0BEAR%I#F�D+��w2�WO/JU#},"�0PLANNET^z�(CHEESS�(NACHOSbJC�PEN;�"%#�gA\2�DOO#K���BPEACON%OF%%,- HOPE9%"Y%@
PHRASEz*(GOINGR8FORWARD�DTH*S�DCA� LINAB8HERRIES�DPON THE MAP�H�(UEBLORWWLRAD"��(IT%WA"l2&8MEANT%TB5BC�DPCLASSIC TV��HHAPPY%DAYZ��ԧ SIANR(COUNT3�H��L*�NOgO"7*CGD*B��US:��(BASELRg8WITZERL"^��#���CLOb|(PROXI]TY��K� LOOK[c FOR%�JD�8EEDLE%I:��@HAYSTACK"D� VENT�����"�"H,PVFL���(MOVIE+�'�(TURDA"0"(NIGHTR�Ft�^*D K�r�@PATHFIND">2�_E�0CUTIVE2JE:��C*q%,@SURGE%OF:W> CTRI}'Y"a%8
THING�C0ONLINEJ0COMMUN"B�C0PHRASE"&WOPE2&D&N'TJD@WAKE%YOU:jD0SONG TNL*HCA"8�_<"?o�UGH*�"C(R%LOV�"B�2�"HO�NT"GO�/'U:CGgj�8SATURDA�*�IGH2�"���  NAM*�Y%,�F8ZON.COM����z*�(UNNELJ�2ϲH�HN THE MAP/HICHIGAN'S**UP�R9gg�$ϧLA�Hz�8DIRECTO">"0FRANCIV:�DZ��wPPO*WI�O� � RINK��0TILAPIJ� FILL#���PCLASSIC TVN�O#�:*@MCKEON%A"�,JOjf��0IACZEKKk�(YRICSTHȏ3�,�WO#
*?W!�2 ,&S|
I3l8KITCHEN*�8SHALLOWB�BAK#ZB DISH��0OW BIZz*0FOREIG#�2_LM�FPERޚD@BEAUTIFUL%%,-B�Y9%"Y%@
PHRASEz"����IDB_R�D�(ONG TNL�H@WHEN%I'M:PSIXTY-FOUR�H� HYMEI'�HGREI BEAN�9�H(FOOD � RINK�, BLUE��Y2TAR�S�J�0V SHOW���@GTV'S%FU2�OGIʕPON THE MAP��@COAST%OF:g>wKA�H PEOP��QUȿ BACK"j�ORN:���(NJOY%�2RID
���8OPER NA�� DIETuK:IPLU#`�0BROWNI"�* POIN+��D(EVENT"8BUYING%52%W�WbRg�ROBJR��"� DOORJ5��N:g_5L�2@MYSELF%I 
TH}*[G ODIN"i2j_RON3�* ZINC�*Dz*�EN*�B�0AXOPHO"c��C#a%,-(MONEYR8LENDERSBQ%@
PHRASEz,��u7THE*O@ITUATION�D� HING�C@CONSUMER:@FEEDBACK�CLITNG �JE>(PHANT: SEALb�bJXFUN & GAMES�I�`� LONG�:��0SMOOTHJ%O~w'#_2KI#�C QUOTu�'��l�SE3]2HFORCE%LUK3oz��Ͽ8/AUTHOR""8GWD:sHBY%CORMAC2G?WoZ�bJ0SAME NKT&*)�WIMZ�� RUNK#2�G(EVENTHA#�752%SPI��"�"?_� CUSS+5�C0MOVIE *�*"�FOXBnAND*:O�U���� GETT"�:HPIGEONHOL��D0YOU%NEJ�8TO%KNOWBDSOMD":bC�Sz� MORN2�*0COMMUTJ�b�(FOOD � RINK"8PANCAKEC�#ZY� USAG"I*%�BREAKFAST%%
TV SHOW TNLE PBS'A%,׷w��RYBDE�0CTIVES*a%8
FOOD � RINK*0GINGER:; SNAPJY(COOKI"I�J� VENTz" PAIDZVA� TION�C PLAC"ЂC�Z�OF:G0MMERCE�CPSONG/ARTIS��HYELLOW%BYBIoDt
�η�G:HYOUR%HOUS�\BOX*�:;8ASSORTE+,CHO-LAT����s����@RL%SCOUT*70NIFORMJ�zC0E 80'SM:�*zAL"8�'?*G7G�g��F(PHRAS3�8MY%WORKB&ǯT'IKDON#��DHROPER NAM2I TENN*92+O�+:_oeELJNAU*b�GUTC�"&�(WHEEL3K��MO�s�Ka%* PARK2\*WAR*��K#�#`�D(DOMINE�:GE<�DK�2�!%%%,-8BEASTIE%2OYS1%*Q%@
PHRASE&@COULDN'T*&��0VE%DON:D�0WITHOU2YOUZD@SHOW BIZz]* GUES4B(CO-HO*��XAROUND THE h*��N� ATINZ HEET*ڊNIN*J8KITCHEN�L@BALSAMIC:8VINEGAR�LK$HI'M%GOING2& TO%B#!:5FAM�!�D�(LITTLC� GOESB5�w]WAY�D(FOOD � RINK�� CHIPK��27oobjJ(EVENT�C MEET*�2Oo0W%PEOP"���HROPER NAM*�8DIRECTO#A"?OBERS�ZEm�KI#��BAdJ PUDD2���LAC*�@RAILROAD:%(SLEEPR4C3��� ERSO#/8THE%CUT+�,#B;z"�LAS;R
](LAUGHR�oT%�JOK�]LIT NG T"/�J�RAZRJELK9%*q%@
PHRASE"DOI%"(WHATE�:@YOU%WANT:jDXSONG LYRICSz""E� BODY2?@ANCE%NOW�I(FOOD � RINK0SPICE-BJ��PASTED%RIBS8WITH%APu�G"J(GLAZEr��N�*�oo MEDA�:�g('LL%B"."0TOGETHJ�j�PPROPER NAM*Ir�8TAMPA%B*Y,GHUCCANEERS��`ICTIONAL CHAT'gER�Q8WARLOCK���Q*�0/AUTHO*J8PLAYINGB,HFOR%PIZZA28BY%JOHNB8GRISHAM�8CONTENT�*&W XTRE-L;�HO#����|��DRY� LL%&*0SHEETR����� BUTT+�20COOKIEB�J0PROTEI#2YA*V�J STARJO;I�"7:+gg
wDOBI_ QUEEB?� ISSA��(UNNELJJ CAKE3�*(POWDEtBhUGB��8HOW BIZ"KEV*�BF��TNS#"�/J� JFK%9%p
SONG/ARTIST*%XCRAZY%FOR%%"WG U%BY)%"8MADONNABY%@
PEOPLEz,0STREETJPER^ MERS�D HRAS*D0DOUBLEJy0COUPON32ǎ(RY%DA��DpIN THE KITCHEN��UNI>SAL28JAR%OPE:�jL(THING�C"�(MMANDB_wWU2��C@ROCK ON!"0FRANKIJ(8GOES%TOB@HOLLYWOOV�Fs�HBEST%OF%M3 LOVE[��b�g MOTI;<0
PLAC+a/ HARM�:} BED%�J�w��KFAg���� � RINKz"�FTEr2@CRAB%MEA�JS�jD�PCLEAN%BILL�0HEALTH�`# TN3{& CAN'+n" MAKE+�2+)���pCLASSIC MOVIES�� FLOW#%:(DRUM%"}��߿0ER NAM2�#�BICkW�"6J�OR+��I*�8/AUTHORGC+�B;g�ߏ�+�, VINCC�,��˵Y%,PTHREE-CHEEtPPASTA%BAKE*i%8
PLACEz"0ISLANDJ@REPUBLIC�C HRAS"DWI=NG�j,BW"t:D(CLEANZb�D�"G:& WITHZ5FLY22COLRS2DO�T�� TH���(EOPAR"�*MOjYb���HLE/AUTHOR"70GH%NOO�"BY
��B;O_�ERT*��J��8BLEACHE"�2@OND%HAIR�C���(E MAP�էF(RILLO: TEXA*��HPPROPER NAM��TO�'BIgAP"L�I(FOOD ��INK�J��ANG+�* JUIC*���OPL��CEL(BRITY:oWwN�br�G7C;*+�VERJ@JUAN%PAB#0,M"�Y+�*� RSON���8LATINUM:+���S�jDHDO%EXACTL2�OS%U/
�DK� BEAU#:%SAzRxWAI�*�,% AREA1%@
PLACE*q%*�0RIVATEB_oLL25z-P
SHOW BIZ"T[RF�6�MS:?�_�/�N:HHEARTLAND"FPON THE MAP?g0GLEWOO"*PCLIFFS%NEW*0JERSEYZ�b�PON�� FILMZDE��O.�D�"  NAM#W0LASTICB:_(URGEO"�*HDR.%ROBER�,7B�*I�@G LYRICS"e&0KNOW%M#K/�'L"�G�'��U:��wPP:L8
THING*Dr� LEGIlM+�,/(XPENSM���T�C��0JOYABL;�"C(RIENC2RrC(FOOD � RINK�J8SPINACHBHMANICOTTI� SUMM#�:% YOUT*B2� PORTR� CAMP�GS�2o0NDFATHe��(PHRAS�HWORKS%LIK3� CHAR3?�Ds�/F"�'R3O�W�G' MAYB2�XT'S%TIME%TO"ICOH"c�7INGwB%w36"�SK3��TNL��:ROUGH!%,-HTHE%YEARS2Y%@
PHRASE"&I%"HCERTAINLY28HOPE%SOB�DY%,x�'S*"0KICKERRbrDLAC�C�(NIMALJ@SANCTUAR:��HCOLD%HAND3PWARM%HEART�D��  NAM*I7(CTRES82+LORC&20UGHLIN
�0L%YOUR2 HEEL*`�D� VENTL�GMG:%HHOW%TO%TI3W��GCK*�C(FOOD � RINK*GGTZZog�(ASTEDB CHIP2��JTH��"0FANFICKoo"?J5 ZINE"�D�8ONG LYR>"& KNEW+y"��V��/U20BEFOREJMET2r�Y%,4��ZHINTENTION��*D�C BROA:�"@SPECTRUM�Ч0OVIE TNL����NEYRTRA+-w?(HL'S%#*+ YORKZX8ISLANDE��Z�I%,-@BURST%OF:@LAUGHTER:Y%`
ON THE MAPz"���(ITOBA:CA\UJjH@HUSBAND � WIFE"(JERRYRLHO'CONNELL2�_��O"g� MIJN:L�pLASSIC TV SONG 70HOW%MEBM�w8AT%SMIL,gW2<��PPROPER NAM*�gLA:�*+BOT�CA:�ww8DY%WASH�IFOO"� RINK*� LUFF*M*(BAKEDR�PZ��ER�z*0COMPAN"T2bwUND��� VENT�C@REVVING%;�MO<�C<;)rC�H*�C��SID3k2HFORMATION
CM�#T:W�RE%SS���HLE/AUTHOR*o_[���?BY* LEE%�gV28WOODRUF#�J(PHRAS+�z�DY�/�28THE%VIN"��HEI#�J�PP"�T�DB�&OG VEN':&DOt�g"�"�WH+��#�0LA%JOL20CALIFO0RNIA%%,i%8
THINGz,(COURTR0DEPOSI'NC���EST"FACBQ�C0SLOGAN(MAKESR&VE} TABL"*�DC*�D� VENT�� DRAW"�:�(CROWD���CPA�RC ROOM���(CCUPA#*�HEEL"�UAL@PROPERTYBH�N�gS3$�UǿPP"�:_OW��BC??(E%PHOd2%?W0AT%COM;T WITH*#2 FRAM*�CRE�*�*PONTROVERSY�����8G/ARTIS*I_8LORY%OF:�o7'B+"PE$�R�C"A�I/UNS�"�"RYOU*<�X"�;� 
LITNG �b0BOWHEA#$*gg_#p�b�(ROUNDJ�OOSE�N(BEDSP~O�lbNXFUN & GAMES�+�(TOMPI�27RAP;*�I��OPL��*!%ENGm'D%*0COUPLE!%*Q%`
ON THE MAPz,�HL%CAPITAN�9�HHTV SHOW TNLE�-ߧ8Y%PAULAK0PERSON�&0AMERIC"�*O_�ZE"�D HRAS"�YOU�N'T2&��D%IB5�0WAY%OF*@PROGRESSzD0MY%FEE"C2��+LB�ww ZING��pCLASSIC MOVIES"7@T%SHOULD2.W�PPħ�2"���0YAKIMAJ(RIVER�H��rL�@PELLBOUN:��K$r&(JUST%B"�;h BUZZ:��HCHURCHILL2*2�+�*A\U��LIT�GL��8BLACK-Ef2�S�+I�J(FOOD � RINK*�3
B,_V0-STICKB�GE%TJ�jJ+BIZ[�"(W@DOL%WINN���7g;W,3;��2�ww�GB+�TRY�K4�? LVE%C�0%TOUGH1%,-0RIDDLE)%8
FOOD ���NK"Y%"��8BE%BEEF2zY%8
THINGHPACKAGE%O24@UNSHARPED"	�ILS�C�0GARLICJHMAYONNAISˊJPCLASSIC TV��8MEDICALBWw NTER��8MOVIE TNLE"70AKE%THr*+��8NEY%AND2RUN�r� MADG"E:*BL"X#"GUNTZH0HARRIE*8
PHRAS*�r�(LIGHT"C�"FEA�*Ԓ��D&@LOVE%HIM*0DEARLY��0SAME N*0DOOR%&J)8BOWLINGBFR(��� OPER*IS0JANUAR2t*�BR*[, MARC;��8DON'T%G+@"DG0STARTE;�"CO#)g#�"GGg2�20SAMBER"�� CHIL;T"RE} PTIOc�D+P#HCELL%PHON3� ROAM3]*��w�gϻQL�M ARK*%8WORLD'S!%"8TALLESTB@MOUNTAIN:Y%@
PERSONz"0FAMILYJgw8TRIARCH�D���SE�D@TAKE%THA"�,FIR��P�D�G TNL�HB� Y%IT"�"_OUbjH(FOOD �RIN+zJCAT�OF:g_ E%DA*�	�`TUB-THUMPING�5�� AK%&B,PPORTOBELLO*@MUSHROOM:0ALFRED2J`ICTIONAL CHAT'g�'$"�Z}(SORCE|;)HAPPRENTIC%���V"W"�L"�C]�Z� FOREUAD��pCLASSIC MOVIES*(TWELV*�*�0'CLOCKB HIGH�*BE"j �AF2�# IC%T#*(Y%EARK��(F%COR#��& FEELJHVINDICATE݊DLIT#�H�J PRAY+42(MANTIJ�jJ+��(SUMME+r2 CHOO*��I���(W BIZb%,8ENDORSE5?T"g?ALA%,i%8
THINGz"@CREATIVE: DECI�ON�CPRHYME TIME�HHSLICE%AND:H"��0FAMILY*R1O/&B&_(ENNISJ5 QUAIP�D�hN THE KITCHEN��0AUCEPA�ɊLO2LMAP�*���:HCALIFORNI�HׯT�GL�j=\UJ GOOS3$�J(FOOD � RINK�JǿPPeB*�J�8HOW BIZ�F�8ROADWAY:oEV$3A�FBE���?TER*(MISER"<2. LOVE+�:�w�PANB[_w�IC*-�ܷ(HILLEK��0ASPBER*Z*_t/�K����RR7CH:O,_��HPROPER NA3�7(CTRESK�0GABRIE�2UN3Ir��@UTHOR%J.5"@SALINGER��I ROBI%,-(KENYA)%*Q%@
PHRASE"G/D&N'T2&(LIFT%R5gw�0GER%TO2 HELPJD��XCTIONAL CHAT'g�'S%POMIN2R_�?Y%&BR�w�CIE1%��0FAMILYz,`GRANDPARENTS�5�D OCCUt��*HLOGISTICS2MA"ߢHS"I'M;*&HBUNDLE%OF2gWRVEP�Dr�0FASCIN�G"gGORY���D0IMPROV"C*(WITH%΢D� VENT�C READ*@28TEA%LEA*��C0DESCRI�:w�G OISEC!YOU+N:R@MECHANIC2C0SONG TNL�ΧADc(MARMA
�ϊ�TH~�C@PHYSICAL:_WgENC+k�C(FOOD � RINK�J�LONR WEDG3�
�YOUb8TRICKEDY��z� EDUC+�2_�g�*��� INK*% BONESS%"8CHICKEN!%" WING":Y%@
PEOPLEz"NIE5S%&B_ PHEW*F�DTHa�C PRIC:�"@HEIRLOOM�CXSONG/ARTIST"O8LL%TIME:+8HIGH%BYBX RITAZg8COOLIDG"-0
QUOTuw'N"7G8'S%GOOD2)oG(BE%TH*"K�ZGj�F5 �R;az�[b*FAJ:�J���STE�:YoKIEC��JoG(GANICBJ8MINNEOL"�*�Go�wo�J��@ THE MAP��BR#L�ORT*COV'_�UT� ASPAGU:t WITHZY_POLLANDAISE"/GUC#��� BOWL;�"GRE3�28KENTUCK#��0AROUND*LOOS��GLA+*:(VOTIV*��zI�F�+�2�STO2��I0RHYME #�" LIAR*2*0PANTS%*;"FIRC�H PHRA*�&0LIKE%T HE%%,PWAY%THINGS*o(RE%GO%,i%@
PHRASEz"8DON'T%BR*HSO%MODEST�D��HNG/ARTISTLA% DANC2�BY"K:X�(UMMERRg��@WHO%WEAR2��_�oNT:IN*BD8FAMILY?2DON ��P��8GULFPOR�* MISSU���(FOOD � RINK*0TUSCANJ�_(HICKE"*�D��HROPER NAM�hHWATERFORD28CRYSTAL�I�ITNG��J(BEARDmJ� OLLI+&�J0AROUND+)OO�2mJHROOM%SOFA�NHTV SHOW TNL*K&8KNOW%MY2-g D'S%C�;�KJ�0ANCIEN#�*� REEKR40HISTOR`�C8BEFORE �(AFTER" PARK;t"BRO�#[*(GRIMM��EV� FEEL[G@OOD%ABOU3@YOURSELF�C�a JUST3*8CLICK%A�;4�jJHAHI%TUNA%%%,-SA=D1%"Y%8
EVENTz,HCHANGING%5" FLAT�RE�CXPROPER NAME"@CONSUMER:+�GIC"7:g�DEX��rI8COUNTRYB+PSTAR%KEITH*�gBANR�rI(FOOD � RINK8GNOCCHI:,W"C8SAUSAGE�;�� HRAS*�/8TRAIGHT:&8FROM%THCGo SE'SBD�wU"�2DOOING�i�0WO-PIE528SWIMSUIBaj�8AROUND pOO2�rNPCOLD%CREAM�?�, APPL"�:� UDEL�JON*�MAP�H�L�J0MEXICO
�(CIRCL#�2l(BLOCK#�@RIAL%SIZ3qw OILE��NK�&OGVE#*&XLOT%OF%WORK2D@CATCH%UP"oC�*D��SBA��WIF*�MIK;*r�w8CHOLS%&2 DIAN[*�oWY+F"LXCLASSIC MOV����#DZ(AMURAI%,i%P
SHOW BIZ/V GOEN!%,�W�,9%,_ AT'SE*8QUESTIO*-@
OCCUPA"za"HRIVERBOAT20CAPTAIBfr��(HRASE*"pRD�׷K*�*0VOLUME"����GA*�HMADE%FROM2&"�B�:5GG UFF%*�"� ARTHBD@LANDMARK���VGERR�(TADIUc��HROPER NAM2�zI WONDZI(BREADRbI� VENT//8JOYING%5"%0HOT%AI*B"(BALLO*�*����C���� HNICJ0FOOD%F*U��C�& DON'3�"��(VE%IT+K,MJv�DTH���0UNSPOK+|"(AGREEDw;3�
0ADJUSTO24#�#�#R"�CM��XFUN & GAMES��PLA+f:CA\STA�IK3B*�,�w��קC@YOURSELF��+�� WINNZ�O(UMBER��KWG(WO-CA|;9gVALJRH%%DIAMOND!%,- RING9%h
PROPER NAME"Y%"���� LEON:8COMPLEXBY%`
ON THE MAP�H@COLUMBUS:oHIOZjHTH��C"{ELL*�,??8TERVIEW�C0SLOGAN�DHRELAX%IT'�,FE*̢D(PHRAS#& KNOW62&?g� DE%A#O,�U"�@DIFFICUL;"0PROCES���k�W7W�_'L*+7O@TIST%URI*0GELLER�@YOU%COUL�"&��8VE%HEAR2��(PIN%Dv�D�ѧTEP8#V"0ON%TOE��8MOVIE TNL�I(CATCHK]#�r�I� VENT�C DANC"��O*70HE%BEA+��C QUOTuIO3+ HI%H3�* SILV3N*A�Y!�[XFUN & GAMES"� OUBL*�2�o"�JUM3Q#�0 DELI�Y:8CONFIRM*�%*%8INHALE%�
"OX*!%"Y%@
THINGSz*W�PB(SHOES�D� VENT�C@COMMENCET'�"7|W�WI*E�C(FOOD � RINK"GESHR�HCRANBERRY2?WLI:�JXPROPER NAME��HHONEY%NUT:XoRIO��T�HLE/AUTHOR"gg_ DINGBJ0WITH%M�BJ�'BJJAY1�O*J@RHYME TI*�&8BEFORE%"*/ XCEP�:90AFTER%}���0UN & G�+�8RED%ANDB+(BLACKR��wR��(PHRAS*�0'D%LIK+,TO�%FLY"oPN%THE%WALL"�T�h GOLFR~�-R�gA#�J PLAY�*IPCLASSIC TVz�,FA"rJ(KNOWS�;�j�3W �+D:�*�:. MORN3�*gw UTIN"��!&CANRD�g�DLK��(ONTAI" 2b�SE3jDj�PT#.B��BU+[�?HL'*)2+�TLABO"q0HERS%%,i%H
MOVIE TNLEz"@STARDUST:zI���J@CHILDREN�IP�ON�DW2FBDPHOd GRAPؒD*�8/AUTHOR77g"�ND2pBY�:�, KING���2�2@ACTUALLY�׷��"C@FAST%FOO:�RE�(URANT*�O@IVE-THRU*LANB`"C�@OPER NAM2�S��Bn0WYCLEFJJEA��XSONG/ARTISTW7|'7HIM"+��7ETH*?CE FEEL#5"IOw VOGU*���/�DEM"�"+_��w/'INN+��o/LEB�,TLI:�Sa%"�OR,�IC�0STUDIO��#T � RINK"@CHEDDAR-R;FFE#v:Yu��J� HRAS"�THET 'S%Ns,GUCH+/"�Gg�',�D��8MAKE%MI#�"� DOUB+�D*k�C ROOMZPTEMPERATUR#���K�E*q%* ITHA-JW OLLE-BQ%8
FOOD � RINK"0CREAMYJJo�0GATONI:WYZh BROC\"8
EVENTPGOING%OVER*%_oA\B4HFALLS%IN%m"0BARRELB��o ME N��PBUSINESS%&*@CUE%CARDJ�b�@SHOW BIZ"EMcK"�*(�"y�/=2CE"��F׿hOUND THE HOUS���0VET%AN�"0SHAM%ShzJ CORNZ(MUFFI*�J0PROPERK'S�Z�(CHRISZ�0AUGHTR#��I��;S��8EMPLOYE#/"HINCENTIVEW� FUZZ"~:NAV3���HRA�e&FE24*@REFRESHE;tjD�HONG LYRIC*��?'w�V�"o@AS%TAKEN:X_��"Z;M*�"I0BEFORE�(AFTER/wN:,�IT7;��FjLIN:
"LooT��nI APIN�_����I%,0HAN%SO=:XPERFORMANCE"a%X
TV SHOW TNLEz,�ߧMV'NT*O8F%TRUTH:rK(MOVIE�I DAREuVIL�:�I(PHRAS2DOGWDERJ&T"�I�2(LOOKS�D�N �MAP�nLOGGUTA��EV�PUNSCREWINGK(AP%ON*�BOT�:C_(F%WAT2�
S*p"ZMAK*#:i@YOURSELF:�(T%HOMBDr� SONGK[& DON'#"*XWANT%TO%LIV#�w7_ HOUT"]�H0LYRICS"$(MAY%Bu,���HT^:�B:(CRAZY� STUD+2n(COUNC#�2�>o�w#&��PER�z,WE"�LIF#A�"�0/ARTIS"�HIP#
*�,�8QUARE%B"�"o_O'(LEWIS*#�NEW 
LIT#c��u@YELLOWFI3� TUNA�kc'�M:��wVEB�" SWEE|/"*~�?'"�2D8NOT%WHA+�,0BARGAINED%,FORI%8
THINGa%,HAUTOMATIC2HHAND%DRYE;z-�C0PENCILJo

**Comment by CyberaxAnnon** [comment]
I thought I was the only one with this issue.
Updated to the lasted as of this comment (0.0.21-13344-16707691) and still no detection via USB even if it is recognized.
Using mint 20.03.

It is even detected via RPCS3, but it just doesn't work.

**Comment by Lctrs** [comment]
Hi. You probably need to setup some udev rules on the host system. See[ Steam Flatpak Wiki](https://github.com/flathub/com.valvesoftware.Steam/wiki#My_controller_isnt_being_detected) on this matter for more informations.

**Comment by CyberaxAnnon** [comment]
> Hi. You probably need to setup some udev rules on the host system. See[ Steam Flatpak Wiki](https://github.com/flathub/com.valvesoftware.Steam/wiki#My_controller_isnt_being_detected) on this matter for more informations.

Hi there, just to make sure my Xbox controller is detected and used for my steam games and even different emulators like Yuzu or PCSX2, but specifically RPCS3 does not detect it at all.

**Comment by kd-11** [comment]
Does the official appimage work or not?

**Comment by Megamouse** [comment]
we do not support the flatpak
