### ISSUE TITLE
Resistance 2 chapter 6 game breaking bug

### ISSUE THREAD

**Issue by Alfmaron** [RPCS3/rpcs3#11590]
## Quick summary
Soldier justa stand, nobody moves.

## Details
I'm on Chapter 6 right now and I just got to the part where you're waiting for the elevator to arrive with the big Chimera on it and for some reason after I kill him my crew just stands there waiting for me to get on the elevator but they never move. I tried many times and is always the same. Music is playing and soldiers not moving.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8151151/RPCS3.log.gz)

**Comment by nitroos-ai** [comment]
Try changing the PPU decoder to Static just to pass that specific level.

**Comment by Megamouse** [comment]
this log file is useless

**Comment by Alfmaron** [comment]
> Try changing the PPU decoder to Static just to pass that specific level.

Thanks, it worked.

**Comment by Jonathan44062** [comment]
The log can't detect the problem, is because PPU LLVM issues, I got black screen Using PPU Decoder Static
You can advance that part, but you only have luck using PPU LLVM, to be restarting over and over again.
