### ISSUE TITLE
Persona 5 upscale image bug

### ISSUE THREAD

**Issue by bolon667** [RPCS3/rpcs3#11591]
## Quick summary
When you increase the resolution of the game, artifacts appear on the faces of the characters.

## Details

Logs
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8153177/RPCS3.log.gz)
RenderCapture
[BLUS31604_20220228151519_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/8153241/BLUS31604_20220228151519_capture.rrc.gz)
Graphical Issue
![NVIDIA_Share_hG5ctlcTRH](https://user-images.githubusercontent.com/46919302/155982756-94602c49-7406-461b-b689-3ae950d5dcb9.jpg)
Settings
![NVIDIA_Share_UuVSJz4wWS](https://user-images.githubusercontent.com/46919302/155982886-5907d30b-9f1d-4338-ab92-ac32c090e143.png)

**Comment by kd-11** [comment]
This is a problem with the game itself.
