### ISSUE TITLE
Main window and game Window in gamescope

### ISSUE THREAD

**Issue by kyoukomelk** [RPCS3/rpcs3#11597]
On the Window manager gamescope on steam deck the main and game windows are fighting for dominance this results in lots of glitching between windows.

Most of the time this fixes itself in a few seconds but in drakengard 3 it takes some spamming right click with a mouse to fix itself and in Odinsphere  leifthrasir it doesn't fix itself at all

So a quick fix is an option to close the main window when a game is loaded.

**Comment by Darkhost1999** [comment]
Yes the quick fix / workaround is to use command arguments --no-gui "<Path/to/game>"
Adding the rpcs3.exe as a non-steam game as many times as for as many games that you have +1. The +1 having no command arguments so as you can configure settings there.

**Comment by kd-11** [comment]
We'll have to wait a bit until we get our hands on a unit. I'll try and run gamescope directly on arch and see if I can reproduce, but I don't expect it to be easy to repro without a unit.

**Comment by AniLeo** [comment]
Can repro on regular Manjaro Gnome with `gamescope ./rpcs3.AppImage`

**Comment by kd-11** [comment]
Surprisingly easy to reproduce with appimage.
It is a known issue with all multi-window programs. Gamescope cannot even handle menus and dropdowns, which is a problem.
External issue: https://github.com/Plagman/gamescope/issues/437
We'll devise some workarounds to allow steam deck operation.

**Comment by Megamouse** [comment]
Based on a comment in the linked issue, it is supposed to be resolved on steam os

**Comment by DanHolli123** [comment]
Please close as issue has been resolved by game scope adding window switching by pressing the steam button

**Comment by this-is-just-con-tribute** [comment]
> Yes the quick fix / workaround is to use command arguments --no-gui "<Path/to/game>" Adding the rpcs3.exe as a non-steam game as many times as for as many games that you have +1. The +1 having no command arguments so as you can configure settings there.

steam  rom manger from emudeck basically solves this automatically so you don't even need to add a launch argument.
