### ISSUE TITLE
[Bug Report] Kidou Senshi Gundam Extreme VS Full Boost [NPJB00512] Custom BGM Playback Does Not Resume Correctly When Paused, Restarts Instead

### ISSUE THREAD

**Issue by InquisitorDavid** [RPCS3/rpcs3#11604]
Very thankful for the recent update that implemented the Custom BGM Playback for this game.

While testing the feature recently, I had to pause a match for the first time while using a Custom BGM, and when I unpaused, the BGM started from the beginning instead of continuing from where it left off.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8192395/RPCS3.log.gz)

Here's a log of starting the game, entering a test match with a custom BGM, pausing the game, then continuing, repeated at least 3 times.

**Comment by InquisitorDavid** [comment]
Seems to fix it perfectly!

Wow, that was really fast!

**Comment by RockXImagine** [comment]
How do I add my own music as BGM? I've been searching for an answer to this for a year.
