### ISSUE TITLE
Case Sensitivity HDD game issue

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11602]
With my only HDD game that I have presently I am experiencing an issue where if the Case Sensitivity of the RPCS3 folder was changed. And you do not update your RPCS3 shortcut after making the change. All HDD game created desktop shortcuts will fail to boot with a fatal error invalid path.
In my example the RPCS3 shortcut I used was pinned to my taskbar:
* This log shows me booting RPCS3 from the old pin to taskbar shortcut and creating a desktop shortcut
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8191296/RPCS3.log)
It shows all the paths as rpcs3 although I have already changed in file explorer the path to RPCS3 instead.
* This log shows me booting the game from desktop shortcut created with the old taskbar shortcut
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8191294/RPCS3.log)
It shows most the paths with the correct case sensitivities: 
·! 0:00:00.049264 VFS: Mounted path "/dev_hdd0" to "H:/RPCS3/dev_hdd0/"
·! 0:00:00.049268 VFS: Mounted path "/dev_flash" to "H:/RPCS3//dev_flash/"
·! 0:00:00.049270 VFS: Mounted path "/dev_flash2" to "H:/RPCS3//dev_flash2/"
·! 0:00:00.049271 VFS: Mounted path "/dev_flash3" to "H:/RPCS3//dev_flash3/"
·! 0:00:00.049273 VFS: Mounted path "/dev_usb" to "H:/RPCS3/dev_usb000/"
·! 0:00:00.049275 VFS: Mounted path "/dev_usb000" to "H:/RPCS3/dev_usb000/"
·! 0:00:00.049276 VFS: Mounted path "/app_home" to "//"
·! 0:00:00.049295 SYS: Applying global config: H:/RPCS3//config.yml
·! 0:00:00.051042 SYS: Logged in as user '00000001' with the username 'Darkhost'
·A 0:00:00.051142 SYS: Firmware version: 4.88
·! 0:00:00.051428 SYS: New timer resolution: 500 us (old=1000 us, min=15625 us, max=500 us)
·! 0:00:00.051434 SYS: Option passed via command line: no-gui 
·! 0:00:00.051436 SYS: Booting application from command line: H:/`rpcs3`/dev_hdd0/game/NPUB30393
·! 0:00:00.051596 SYS: Selected config: mode=custom config, path=""
·! 0:00:00.051599 SYS: Path: H:/`rpcs3`/dev_hdd0/game/NPUB30393/USRDIR/EBOOT.BIN
·! 0:00:00.052421 VFS: Loading VFS config. Path: H:/RPCS3/config/vfs.yml

The only path for concern here is the `Path: H:/rpcs3/dev_hdd0/game/NPUB30393/USRDIR/EBOOT.BIN` because the booting from command line path is accurate to what was chosen.
* This log shows me booting rpcs3 from the new pin to taskbar shortcut and creating a desktop shortcut
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8191287/RPCS3.log)
This has the correct new case sensitivity because I made a new rpcs3 shortcut on my taskbar.
* This log shows me using the desktop shortcut created with the new taskbar shortcut
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8191288/RPCS3.log)
The game boots fine and has all the correct case sensitivities in every path.

#### Steps to reproduce
* Create an RPCS3.exe shortcut on desktop/Startup/Taskbar (you pick)
* Rename your RPCS3 folder to the same exact name but change the case sensitivity (Either uppercase or lowercase)
* Boot the shortcut made in step 1 without updating it to your new case sensitive path
* Inside RPCS3 create a desktop shortcut for a HDD game (aka a PSN game)
* Close RPCS3 and try to boot that desktop shortcut it should fail
* Delete all the shortcuts created in step 1 and in step 4
* Create a new shortcut for rpcs3.exe
* Boot that shortcut
* Inside RPCS3 create a desktop shortcut for a HDD game
* Close RPCS3 and try to boot that desktop shortcut it should work

As far as I understand the log should never report the wrong case sensitivity for your paths regardless of when the shortcut for RPCS3 was created.
Also Disc games boot just fine without any case sensitivity issues. But HDD games have case sensitivity issues.

Specs:
Windows 11
Ryzen 5 3600
Gtx 1660 Super

**Comment by Megamouse** [comment]
then don't change the foldername man

**Comment by Megamouse** [comment]
This is clearly user error.
You're changing the path of your application and then expect it to run as if nothing happened.
This is nearly as bad as if you had changed the name to something else entirely.
The log clearly states that the emulator detects a case issue and advises you to fix the paths.

**Comment by Darkhost1999** [comment]
Ok. No problem. Figured it's a Windows issue and not an RPCS3.
Disc games work fine though whereas HDD games do not.
But it's a simple fix to get it working again
