### ISSUE TITLE
GT HD concept text bugs, and weird granular static in Headlights and Taillights

### ISSUE THREAD

**Issue by Danke-Boi** [RPCS3/rpcs3#11611]
## Quick summary
In Gran Turismo HD Concept, when in a race, all of the text begins to bug out, going completely white with an opaque white box the size of the character covering it up. When exiting a race, and starting the next one, the cars do not change colors in the color selection screen, the text has the white boxes flashing on and off on individual letters, and the headlights and taillights have a weird static looking effect.

#### 0. Make sure you're running with settings as close to default as possible
Only thing different is ASMJIT, Multithreaded RSX, Async texture streaming

#### 1. Please attach RPCS3's log.
https://drive.google.com/file/d/1YvGj96yb3IMCAChiCdyqNvtk_M9uYewW/view?usp=sharing

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
Can't, just get footage at 11 fps that is of nothing.
#### 3. Please attach screenshots of your problem.
<img width="1169" alt="Screen Shot 2022-03-08 at 10 23 13 AM" src="https://user-images.githubusercontent.com/72051710/157269352-082b068e-fd34-4727-aa49-7a61abc9dad0.png">
<img width="503" alt="Screen Shot 2022-03-08 at 10 22 55 AM" src="https://user-images.githubusercontent.com/72051710/157269370-bbf1a210-c9a7-4da5-a2e3-280782b5e136.png">
<img width="360" alt="Screen Shot 2022-03-08 at 10 20 24 AM" src="https://user-images.githubusercontent.com/72051710/157269389-b632daf4-d382-46d7-aa58-dd81d78550ff.png">

#### 4. Please provide comparison with real PS3.
PS3 is also playable, just with fewer bugs
#### 5. Please provide your system configuration:
* MacOS 11.6.5
* M1
* 7-core
* Driver 0.2.892
* 8GB of RAM

#### Please include.
Also, Vibration doesn't work, despite there being options to enable it in the "pads" settings.

**Comment by kd-11** [comment]
MacOS support is not complete. MacOS does not support vulkan and uses an incomplete translation layer that has known issues.
Meta tracker https://github.com/RPCS3/rpcs3/issues/11414
Closing this as a duplicate in favor of the moltenvk tracker.
