### ISSUE TITLE
[Feature Request] PS4 Emulator

### ISSUE THREAD

**Issue by Minacat1** [RPCS3/rpcs3#11612]
## Quick summary
Please briefly describe what feature you would like RPCS3 to have.

## Details

Please describe the feature as accurately as possible.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.

#### 4. Please provide your system configuration:
* OS
* CPU
* GPU
* Driver version
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by Darkhost1999** [comment]
Out of scope of RPCS3

See here for in scope projects
https://emulation.gametechwiki.com/index.php/PlayStation_4_emulators
