### ISSUE TITLE
I cant open ANY game

### ISSUE THREAD

**Issue by hanataro1** [RPCS3/rpcs3#11610]
So i download demon soul and then the game already in the menu when i double click theres a error  it close my app instantly and then i reopen my app after that i click play it seems work but theres no game window

my device is macbook 
<img width="1440" alt="Screen Shot 2022-03-08 at 16 11 55" src="https://user-images.githubusercontent.com/101177209/157205877-c9a2ac6e-9280-4ec8-b6ac-7268db232e2c.png">
thats what happen when i click plat again when the game is running but no game window

**Comment by hanataro1** [comment]
i tried with super mario bros

**Comment by MSuih** [comment]
Github isn't the place for help requests. Read [this](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) to know how and where to ask for support.

**Comment by hanataro1** [comment]
hey MSuih am sorry to submit help at the wrong place but i cant use 3 of that cause my discord banned and i dont know how to use that 2 web
