### ISSUE TITLE
Silent Hill Homecoming(BLES00460) Extreme Audio Crackling/Issues

### ISSUE THREAD

**Issue by NOKTYAADOTI** [RPCS3/rpcs3#11639]
## Quick summary
The audio in the game is completely messed up, the audio starts to crackle non stop after booting up the game, in some cutscenes you can hear it less but its still there and after the cutscene ends, during gameplay it goes back to extreme crackling and no normal sound effects are played or heard.
Other than that visually the game looks fine even the framerate was normal (but I only checked the starting area, since the audio crackling was just too much), if the audio starts working I think this game could be considered playable, since there are YouTube playthroughs of the game with people finishing it on rpcs3, its just the audio that is completely messed up

I tried  the game at default settings and also tried messing with all sorts of options but nothing mitigated the issue other than just muting the game

Here is a video of someone's playthrough on rpcs3, relatively new video, this issue is still present in the **Build[0.0.21-13343]** that I tested too
https://www.youtube.com/watch?v=9hbgXtcfcDc

#### Please attach RPCS3's log.
Booted up the game, started a new game, watched the 1st cutscene and played till the first save point, then exited RPCS3 and copied the log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8224650/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8224652/RPCS3.log.gz)

#### Please provide your system configuration:
* OS: Windows 10
* CPU: i7 8700 stock
* GPU: Nvidia GTX 1060 6GB
* Driver version: 466.77 (Nvidia Driver)
* RAM: 16GB DDR4

**Comment by jokoputera** [comment]
i believe it is playable through the end, but the sound is crackling

**Comment by jokoputera** [comment]
nope, crackling sound still there, eventhough its better. after start press "New Game" wait after first the cinematic, the music is still cracking.

**Comment by nitroos-ai** [comment]
Please install latest Nvidia driver and in emulator under `Audio` tab try the option `Enable Time Stretching`.

**Comment by jokoputera** [comment]
i just tried it, and still crackling. tried 25%, 50%, 75%, 100%, and it doesnt make any differences. but, this PR get closer to solve this crackling sound, as the opening music and cutscene are working perfect. maybe a little tuning will help?

**Comment by TigiHof** [comment]
I can confirm this issue! The crackling sound is still present, not matter the settings.

**Comment by NOKTYAADOTI** [comment]
just tested again with the latest build **0.0.22-13595**  and it seems like the crackling is a lot less now, the game sound effects are playing fine in gameplay now but the the crackling/buzzing sound is still constant sadly, though its severity has been reduced by alot but still imo not in a state where it is bearable.

tested the game at default settings also with time stretching option.

new logs if needed with latest build:
same method as before, booted up the game, started a new game, watched the 1st cutscene and played till the first save point, then exited RPCS3 and copied the log


[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8690959/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8690958/RPCS3.log)

.

**Comment by jokoputera** [comment]
please open new issue

**Comment by NOKTYAADOTI** [comment]
Update:
With default settings all sound issues during gameplay seem to have been fixed as of **Build 0.0.24-14347**
