### ISSUE TITLE
(Linux) Unable to open due to missing shared library

### ISSUE THREAD

**Issue by Isma-117** [RPCS3/rpcs3#11635]
## Quick summary
At some point the emulator lost a shared library that it needed to run (libwolfssl.so.30).

## Details
The problem isn't solved even If I reinstall the emulator or the libraries altogether. I still get nothing when I try to open the emulator.
Although, when I try to open it through a command, I get the following error message:

"rpcs3: error while loading shared libraries: libwolfssl.so.30: cannot open shared object file: No such file ordirectory"

This is all having downloaded the rpcs3-git verison, the Appimage version seems to work just fine.

#### 5. Please provide your system configuration:
* Garuda Linux
* Ryzen 5 3600
* RTX 2060

**Comment by qurious-pixel** [comment]
Can be installed with `pacman -S wolfssl`

or from source: 

https://github.com/wolfSSL/wolfssl

Not seeing this error using `garuda-dr460nized-linux-zen-211028`

**Comment by Isma-117** [comment]
The wolfssl package is installed. It actually installs at the same time as rpcs3-git, and I still get the same error message? What could be causing this?

I attach an image of the command line with both the downlaod and an attempt to open RPCS3:
https://imgur.com/lbw6Es8

**Comment by Megamouse** [comment]
Since the appimage is working, i don't see a reason to keep this open.
You seem to be missing a submodule update or similar
