### ISSUE TITLE
MSAA Performance Regression

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11642]
Making a formal report per requested
> Could be affecting nvidia cards disproportionately, I'll have to check it. In the meantime open a ticket about the performance and I'll decide whether its worth investigating further.

* Build without regression #10579
![Working](https://user-images.githubusercontent.com/60384196/157767211-9d2082bb-7919-4ee6-abf9-0f07f1939123.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8235409/RPCS3.log)

* Build with regression #11607
![Regression](https://user-images.githubusercontent.com/60384196/157767477-0152de5d-0a4c-4428-90f2-aa8b97c2c6e3.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8235422/RPCS3.log)

In my honest thoughts I can continue playing with MSAA off and I would not be upset if the cause to this issue is a won't fix.

**Comment by Darkhost1999** [comment]
Status update with recent changes to RPCS3. If helpful.
![#11641](https://user-images.githubusercontent.com/60384196/157769663-73f19649-f0d3-4767-98db-4d8f87987a5a.png)
[#11641.log](https://github.com/RPCS3/rpcs3/files/8227682/11641.log)

**Comment by kd-11** [comment]
I forgot to mention. I tested my 1050ti. No performance impact was observed. Something else is going on specifically in your setup. Lets leave the ticket up to gather more data in case more people are affected.

**Comment by Yahfz** [comment]
Lots of people have tested this and nobody had a performance hit.. Pretty sure its an user error thing.

**Comment by Megamouse** [comment]
issues with patches applied are not allowed

**Comment by Darkhost1999** [comment]
> I would not be upset if the cause to this issue is a won't fix.

I tried clean install via GeForce experience, nvclean install, ddu safe mode clean install, Ddu in regular mode clean install, cleared my config file multiple times only changing the settings mentioned in the wiki except for the obvious leave Anti-aliasing on auto. I tried clearing cache, Validating game files, changing directory of the game to my hdd instead of my ssd. Changing emulator path. 
Disabling game patches..
Possibly more just having difficulty remembering all I tried.

Yet if I am the only one capable of experiencing this issue. Then I see no reason in leaving this issue open. There is strong evidence this is user error. I just wish I knew what I'm doing wrong.
I only tried all of that cause I care about me doing something wrong and what if it's effecting everything on my PC. I did not do any of that for RPCS3 or RDR alone.
The game works fine without AA. I'll just continue enjoying the game.

**Comment by Jonathan44062** [comment]
Yikes, this also happens to me lol
CPU: i7 8700
GPU: GTX NVIDIA 1070 Ti

MSAA (Anti-Aliasing) Disable:
![image](https://user-images.githubusercontent.com/78843189/157947313-86feb74c-914b-4c4c-9975-71cc6c3aaec3.png)

MSAA (Anti-Aliasing) Enable:
![image](https://user-images.githubusercontent.com/78843189/157946975-b99ceb8a-9afc-4a80-bcb8-80bf343dd1f6.png)

**Comment by MarioSonic2987** [comment]
0.0.21-13335 (Prior to #11607) - With AA: 
![image](https://user-images.githubusercontent.com/20027681/157950603-9fe1a16b-0655-4376-a18c-847edad60f62.png)

0.0.21-13335 - Without AA: 
![image](https://user-images.githubusercontent.com/20027681/157952281-5b7cba98-7041-4c33-aceb-ca1bcdd71819.png)

Latest build (with AA): 
![image](https://user-images.githubusercontent.com/20027681/157950887-8f97c38d-b4ea-4d0b-8356-c4cb5a8aa4c2.png)

Latest build (without AA): 
![image](https://user-images.githubusercontent.com/20027681/157951288-e776dca3-ca74-430d-ae04-5f683ab085e3.png)

**Comment by kunit1** [comment]
Can confirm the performance degradation when AA is enabled.

CPU: Core i5 12600K
GPU: GTX 1080

Latest Build:
AA Enabled: 10 FPS Avg
AA Disabled: 30 FPS

**Comment by Asinin3** [comment]
Please add log files to your posts

**Comment by JimScript** [comment]
I know this isn't RDR, but LittleBigPlanet is negatively affected by this too. With AA on I get sub 5 fps at 100% gpu utilization, wherein before I could have it on without any worry or notice. And unlike RDR, disabling AA introduces graphical issues:
![BCUS98208_screenshot_2022_03_12_11_33_44](https://user-images.githubusercontent.com/66685584/158032361-d0f993e3-8bb8-44b1-9c6a-689e935219c1.png)

Logs:
[RPCS3.LBP.before.gz](https://github.com/RPCS3/rpcs3/files/8238286/RPCS3.LBP.before.gz)
[RPCS3.LBP.after.gz](https://github.com/RPCS3/rpcs3/files/8238287/RPCS3.LBP.after.gz)

Specs:
- SYS: RPCS3 v0.0.21-13346-78b8bd80 Alpha | HEAD
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2022-03-12T11:36:44
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 511.23.0.0
- SYS: Firmware version: 4.88

**Comment by Xcedf** [comment]
3080 here
Noticed that for me MSAA regressed a lot in RDR too, but only on non-native resolutions
13343 1x IR, AA Disabled
![1](https://user-images.githubusercontent.com/7060586/158037496-41583ac1-e042-44a6-9e63-f74d58e6187d.jpg)
13343 1x IR, AA Enabled
![2](https://user-images.githubusercontent.com/7060586/158037509-ff41801a-26c7-4652-b7f8-cf9fd6f5ddb5.jpg)
13343 2x IR, AA Disabled
![13](https://user-images.githubusercontent.com/7060586/158037540-dc0015b9-5144-4917-8cc6-64dd4a3727c6.jpg)
13343 2x IR, AA Enabled
![3](https://user-images.githubusercontent.com/7060586/158037546-fc46b490-923e-47a3-923b-58a3f4a421a1.jpg)
Rre_PR 13335 2x IR, AA Enabled, but windows flickering
![14](https://user-images.githubusercontent.com/7060586/158037566-e713b983-0cb8-41df-b422-ce5c49bf94bc.jpg)
Logs for all cases:
[13343_1x_No_AA.gz](https://github.com/RPCS3/rpcs3/files/8238609/13343_1x_No_AA.gz)
[13343_1x_AA.gz](https://github.com/RPCS3/rpcs3/files/8238610/13343_1x_AA.gz)
[13343_2x_No_AA.gz](https://github.com/RPCS3/rpcs3/files/8238611/13343_2x_No_AA.gz)
[13343_2x_AA.gz](https://github.com/RPCS3/rpcs3/files/8238612/13343_2x_AA.gz)
[13335_2x_AA.gz](https://github.com/RPCS3/rpcs3/files/8238613/13335_2x_AA.gz)

**Comment by Yahfz** [comment]
Its not "only in native resolutions". It only manifests for you at higher resolutions because your GPU is faster. Your GPU is fast enough to handle MSAA at 1X IR, but it can't handle a higher resolution + MSAA.

**Comment by kd-11** [comment]
I'm working on a more radical solution. To be clear - the old way of MSAA is unacceptably bad, we cannot go back to using it. I'm trying a new approach altogether.

**Comment by Danke-Boi** [comment]
> I'm working on a more radical solution. To be clear - the old way of MSAA is unacceptably bad, we cannot go back to using it. I'm trying a new approach altogether.

![image](https://user-images.githubusercontent.com/72051710/158607954-00a453ed-fdb4-4106-985f-b03ce4a4874d.png)

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/11665 should resolve this once and for all. It has been tested with AMD (RDNA2) and NV (Maxwell, Pascall & Ampere) GPUs.
Test if anything breaks. It is a big change, its better to be careful.
