### ISSUE TITLE
[Feature Request] Bring DX12 comeback?

### ISSUE THREAD

**Issue by LuizSerapiao** [RPCS3/rpcs3#11646]
I know its a weird request, however, xbox series consoles are emulation beasts right now, and the only kind of emulators that can't run on then are emulators without DX11/12 support (or some compatibility layer). Don't know if anyone in the team has any interest in the xbox as a emulation platform, however, I do believe interest on it is rising and asking is free haha.

**Comment by MSuih** [comment]
We don't have enough graphics developers to even fully maintain the two current backends, adding a third one is simply not possible. The only way this would be possible is if we somehow managed to attact a talented and enthusiastic DX12 developer from somewhere but those are extremely rare.

I'm closing this issue as having it open doesn't do anything except cluttering the issue list.

**Comment by AniLeo** [comment]
I don't think we would want to add technical debt with a render just for one platform. The issue there is that Microsoft doesn't support proper open standards like GL (fully) or VK.
