### ISSUE TITLE
Stuttering in the audio! Grand Theft Auto 4 The Complete Edition [BLES01128]

### ISSUE THREAD

**Issue by momoids** [RPCS3/rpcs3#11644]
Grand Theft Auto 4 The Complete Edition [BLES01128]
There is a stutter in the audio after enabling xFloat accuracy (required for Fixes missing collision)
RPCS3 : RPCS3 v0.0.21-13346-78b8bd80 Alpha
Windows 11
AMD Ryzen 5 1600X
NVIDIA GeForce GTX 1060 6GB
32GB RAM
SSD: 120GB (OS) HDD: (3TB)
![GTA IV 01](https://user-images.githubusercontent.com/70231770/157775417-1abd8a16-3571-4abb-9d80-b6d8e90c7bb7.jpg)
![GTA IV 02](https://user-images.githubusercontent.com/70231770/157775421-3c3d4584-fdc0-47bd-b83f-4527d0504173.jpg)
![GTA IV 03](https://user-images.githubusercontent.com/70231770/157775425-8bcb9e64-ad7d-43a6-a306-391a26c1478b.jpg)
![GTA IV 04](https://user-images.githubusercontent.com/70231770/157775426-01ec8686-7e0c-4d58-98b7-4b1c56c0c6b0.jpg)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8227871/RPCS3.log)

**Comment by RainbowCookie32** [comment]
> There is a stutter in the audio after enabling xFloat accuracy

Looks like just low performance (likely considering you are running a 1600x), which isn't really worth opening an issue for.

**Comment by momoids** [comment]
> > There is a stutter in the audio after enabling xFloat accuracy
> 
> Looks like just low performance (likely considering you are running a 1600x), which isn't really worth opening an issue for.

When I disable xFloat accuracy, the audio is normal without stuttering.

**Comment by RainbowCookie32** [comment]
Which makes sense because Accurate Xfloat is slower than the default approximate option.

**Comment by viksmir** [comment]
Can confirm the same issue with BLE01128 on 0.0.25-14476 version of the game and recommended configuration. It happens during gameplay, not during cutscenes.

System specs include 5800X3D, RTX 3090 and 64 GB of ram. So it's not specs issue but rather optimization.

**Comment by berlingoqc** [comment]
I have the same audio stuttering issue on M1 pro. The opening car drive gameplay is running smoothly and audio is fine for cutscene.
