### ISSUE TITLE
Verification failed Red Dead Redemption [BLUS30418]

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11640]
Was testing if MSAA performance was restored out of curiosity when suddenly the game refused to go ingame
* Working build #11606
[13344.log](https://github.com/RPCS3/rpcs3/files/8226128/13344.log)
* Regressed build #11636
·F 0:00:56.949078 {RSX [0x00b9d44]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderTargets.cpp:782[:3], in function get_surface)
[13345.log](https://github.com/RPCS3/rpcs3/files/8226131/13345.log)

**Comment by Darkhost1999** [comment]
Same with GTAV.
[GTAV.log](https://github.com/RPCS3/rpcs3/files/8226265/GTAV.log)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/11641
For some reason my windows setup is immune to this bug but it crashes on linux with every test that has MSAA textures enabled.

**Comment by Darkhost1999** [comment]
Indeed fixed.
RDR and GTAV are back in game with that PR

**Comment by kd-11** [comment]
Is performance back to normal levels?

**Comment by Darkhost1999** [comment]
> Is performance back to normal levels?

Not on RDR. No.
