### ISSUE TITLE
RSX Desync [NPEB00401]

### ISSUE THREAD

**Issue by nitroos-ai** [RPCS3/rpcs3#11645]
## Quick summary

The game works fine in menu but as soon as the level start the fps drops from 60 to 3-5.
`Accurate reservation access` seems to help a little 7-9 fps.

## Details

Uncommon errors are:

`RSX: Vertex program block aborts prematurely. Expect glitches`
`RSX: Vertex program has no POS output, shader will be NOPed`
`RSX: Unknown/illegal instruction: 0x3f (forced unit 0)`
`RSX: Shader does not write to any output register and will be NOPed`
`RSX: Unknown/illegal instruction: 0x26 (forced unit 0)`
`RSX: Src type 3 used, opcode=0x27, dst=0xE7C9E7C9 s0=0xA907A907 s1=0x2650265 s2=0x19CC19CC`

#### 0. Make sure you're running with settings as close to default as possible

Changed settings are:
WCB to fix missing letters in pause menu.
RCB trigger more errors.

#### 1 & 2. Log and RSX capture

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/8228972/RPCS3.zip)

#### 3. Please attach screenshots of your problem.

![Puzzle](https://user-images.githubusercontent.com/68450737/157801206-cbf5c114-f461-4e03-831b-3dfbd316e51e.png)

#### 5. Please provide your system configuration:
* OS    Lubuntu 20.04.4
* CPU  i5-4590
* GPU  GTX 1070 ti
* Driver 510.47.3.0

**Comment by Megamouse** [comment]
As far as I can tell, the game only runs well if I use at least 8 cores..

**Comment by kd-11** [comment]
Graphics glitches and the sync issues are tracked in https://github.com/RPCS3/rpcs3/issues/9133
The rest are performance issues due to the CPU being below recommended spec.

**Comment by nitroos-ai** [comment]
When I make the ball jump with X the fps jumps to 60 fps in that momentum and when the ball lands it drops back 3 fps.
