### ISSUE TITLE
XInput pad handler causes hangs on boot (but resumes normal functionality when controller is unplugged)

### ISSUE THREAD

**Issue by Anubeia** [RPCS3/rpcs3#11668]
## Quick summary
Having a controller connected and using the XInput pad handler causes attempted boots to hang. Unplugging the controller at this point resumes normal function, and reconnecting it after the fact causes no other issues. This must be done 100% of the time when booting with these things in place.

#### 3. Please attach screenshots of your problem.
It's not a problem I can explain convincingly with stills, so please enjoy 14 seconds of me unplugging and reconnecting a controller to make things work again. 

https://www.youtube.com/watch?v=Ed9Rg1MqXMY

#### 4. Please provide comparison with real PS3.

If my PS3 did this, I'd pitch it into the nearest bin.

#### 5. Please provide your system configuration:
* OS: Windows 10
* CPU: Ryzen 5950X
* GPU: AMD 5700XT
* Driver version: Can't be bothered finding out, it's in my video.

#### Please include.
I'm not the only one plagued with this issue. I solved the same problem (albeit I was met with people questioning my intelligence initially) with some fanfare on Discord, as those present will vouch.

I also believe it is related to this issue: https://github.com/RPCS3/rpcs3/issues/11659

**Comment by Anubeia** [comment]
You can see the log in the video I've attached. Do I need to select a more verbose setting?

**Comment by Anubeia** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8295397/RPCS3.log)

**Comment by Megamouse** [comment]
1. Issues with patches applied are not allowed
2. There's not a single hint about Xinput in this file. You seem to be using the DS3 pad handler.

**Comment by Megamouse** [comment]
Closing. No xinput log present
