### ISSUE TITLE
macOS bugs and Fatel error

### ISSUE THREAD

**Issue by Red1860** [RPCS3/rpcs3#11660]
## Quick summary
God of war Collection Game Lags and crashes on macOS latest Build. 

## Details
I am trying to play God of War Collection but after playing for a while it starts to lag and sometimes crash also. 

#### 5. Please provide your system configuration:
MacBook Air M1 
8 Core Gpu and 8 Gigs Ram

<img width="1120" alt="1" src="https://user-images.githubusercontent.com/58611972/157985187-7a0e2d61-78cc-4c45-b914-6394d9f5020e.PNG">
<img width="1120" alt="2" src="https://user-images.githubusercontent.com/58611972/157985198-6a901bc1-479f-4b05-bc9a-54ccc9cb9353.PNG">

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8236329/RPCS3.log)

**Comment by Red1860** [comment]
Got the same fatal error message today on default settings- 

<img width="1120" alt="5" src="https://user-images.githubusercontent.com/58611972/158106553-922d25cc-50bf-4b30-b409-08c2420c9529.PNG">


[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8241761/RPCS3.log)

**Comment by Red1860** [comment]
I was playing today and a different fate error showed up. 
<img width="1120" alt="ss" src="https://user-images.githubusercontent.com/58611972/158918004-423df73f-f451-4b7f-9d67-5c1bd38e0d9f.PNG">

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8296703/RPCS3.log)

**Comment by elliott44k** [comment]
Likely can be included in #11414

**Comment by Megamouse** [comment]
This issue is 2 years old and the macOs version is not even supported anymore.
I'll close this in favor of more recent issues.
