### ISSUE TITLE
R&C issues with MSAA Enabled

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#11676]
Some Ratchet and Clank games have issues when MSAA is **ENABLED** (recent MSAA changes haven't fixed it)

![image](https://user-images.githubusercontent.com/17715080/159070161-0283bd7e-61b9-4cbe-a772-995b578af213.png)

RSX Captures:
https://drive.google.com/file/d/1YyCBnl0n8t5K4VWGGunnO638S-G3qH4-/vie

LOG:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8307073/RPCS3.log.gz)

**Comment by YuriNator557** [comment]
Specifically affected games are Tools of Destruction and Quest for Booty
![image](https://user-images.githubusercontent.com/76178650/159073474-39d259a2-1d6c-4bab-a68b-7a34fe9279c2.png)

**Comment by Asinin3** [comment]
Interestingly though, R&C A Crack in Time **used to** require MSAA in order to not look pixelated, now it works fine with MSAA on or off. See: https://youtu.be/kOBKXcn-yQg?t=33 Not sure when it changed but it was around 2019-2020

**Comment by Asinin3** [comment]
Confirmed issue is caused by https://github.com/RPCS3/rpcs3/pull/11665

**Comment by isJuhn** [comment]
It only got worse, even in the before pic it's not correct. This has been the behaviour since it went ingame, MSAA has always made the edges look terrible.

**Comment by Satan86** [comment]
Gran Turismo 5's MSAA also looks broken after the rewrite
