### ISSUE TITLE
Gran Turismo 5 X Access violation reading location (unmapped memory)

### ISSUE THREAD

**Issue by MidnightLocke** [RPCS3/rpcs3#11683]
I've been testing Gran Turismo 5 on my new PC. It's a 3080 i9 10900k. Keep getting the error F {RSX [0x11d3244]} VM: Access violation reading location 0x42ddffe0 (unmapped memory) whenever I attempt to select tracks and whatnot. It just freezes up. I tried a few settings but i'm not sure what works. Any fix for this?

**Comment by Jonathan44062** [comment]
Gran Turismo 5 is in regression, already reported by #11549
Wait for the fix
