### ISSUE TITLE
Demon's Souls [BLES00932] crashing after character creation on Steam Deck

### ISSUE THREAD

**Issue by Rinnegatamante** [RPCS3/rpcs3#11684]
## Quick summary
Demon's Souls (EU) apparently seems to crash if Vulkan renderer is used on Steam Deck (both in Desktop and Gaming mode).

## Details
The crash happens few seconds in game, even if the first cutscene is skipped right after the character creation. The crash seems to be related to Vulkan command buffer not being properly allocated (as shown in the video attached at the end, an assertion fails refering it). Note that the crash happens solely if Vulkan is used as backend. OpenGL backend works fine (but the shader compilation stuttering makes the game unplayable).

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
I didn't manage to find a proper log file in .cache folder (don't know if the fact that RPCS3 has being installed via flatpak makes it have a different filename and/or directory for logs) however the console reports as final error:
`std::array::reference std::array<vk::command_buffer_chunk, 256>::operator[](std::array::size_type) [_Tp = vk::command_buffer_chunk, _Nm = 256]: Assertion '__n < this->size()' failed.`

#### Please include.
Here's a small video showing off RPCS3 configuration, the exact moment of the crash and the error reported in the console:
https://www.youtube.com/watch?v=qdG96BIm5Ko

**Comment by AniLeo** [comment]
Cannot reproduce on Steam Deck using the latest RPCS3 build

You're not using an official RPCS3 build, download the latest Linux build from our website and try again

**Comment by kd-11** [comment]
The crash is really sus, the code there is called from one thread at a time and has a modulo operation applied on the result to make sure it can never be out of bounds. Likely a broken build of rpcs3. Try the official appimage, if it fails request to reopen.

**Comment by Rinnegatamante** [comment]
Can confirm that the bug doesn't happen with a fresh AppImage install. Didn't know the flatpak on flathub of RPCS3 wasn't official, my bad.
