### ISSUE TITLE
[Optimization] Leverage Vulkan dynamic rendering when supported

### ISSUE THREAD

**Issue by LifeIsStrange** [RPCS3/rpcs3#11697]
Vulkan dynamic rendering is a recent addition and is mandatory for Vulkan 1.3
Hence people that do update their drivers supports it since 3 months.

I am not  an expert but apparently dynamic rendering is already supported on directx 12 so vulkan is playing catch up here and it allows to significantly simplify code

> If you’re not using multiple subpasses or input attachments though, go ahead, rip those render pass objects right out! Dynamic rendering offers similar rendering performance to a single pass render pass object but with a much simpler interface on all implementations. Hopefully this extension will make writing future Vulkan renderers just a bit more enjoyable

However the impact on overall performance should be tested as it could improve or regress it, potentially depending on hardware vendor
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_dynamic_rendering.html#_description

It might enable new kinds of optimizations too?
E.g.
> VK_ATTACHMENT_STORE_OP_NONE_KHR from VK_QCOM_render_pass_store_ops, enabling applications to avoid unnecessary synchronization when an attachment is not written during a render pass

https://www.khronos.org/blog/streamlining-render-passes

> On tiling GPUs, subpasses provide optimisation opportunities that can translate to impressive performance and efficiency wins. However, for many developers, subpasses either remain too restrictive to use or simply don't provide any practical benefit. For developers not using subpasses, render pass objects largely just get in the way.

Humm it seems that if you use subpasses then you should not use dynamic rendering

**Comment by kd-11** [comment]
This is being tracked internally for several weeks now. There is no need for a feature request ticket.

**Comment by LifeIsStrange** [comment]
good to know !
