### ISSUE TITLE
Rpcs3 fullscreen does not respect windows monitor refresh rate setting

### ISSUE THREAD

**Issue by danaigus** [RPCS3/rpcs3#11696]
## Details

I use a 144hz screen and was trying to run a 30 fps locked game. To have a smoother experience with less judder, I setted the screen refresh rate on windows to 120hz. But rpcs3 always change the screen refresh rate to the maximum refresh rate of the screen when it enters fullscreen mode, it even changes the setting on windows too. 
Ideally, rpcs3 should have a setting that allows you to set the screen refresh rate when in fullscreen mode, and at least respect the setting set in windows.

* OS Windows 10
* CPU Ryzen 5 5600x
* GPU Radeon RX 6800 XT
* Driver version 22.3.1

**Comment by kd-11** [comment]
We do not have any refresh rate changing code. Also this doesn't happen on my monitor, but I'll leave it open in case someone else has this issue. It is more likely a 3rd party injected tool (afterburner, obs, rtss, etc) is causing it.

**Comment by danaigus** [comment]
Your comment made me wonder if the problem could be related to the monitor's aspect ratio, because I use an ultrawide. And after changing the desktop resolution from 3440x1440 (21:9) to 2560x1440 (16:9), the monitor's refresh rate does not change after entering full screen. I tested this after a reboot with no 3rd party injected tool running. Please consider looking into this.

**Comment by kd-11** [comment]
What is likely happening here is driver optimisations. NVIDIA notoriously hooks into the windowing queue and tries to make it so that large borderless windows are made fullscreen exclusive. You can disable this by editing the game's config.yml file and force disabling exclusive fullscreen. If that doesn't work, right click the exe and disable fullscreen optimizations there in case windows has a hand in this issue.

**Comment by danaigus** [comment]
I use an AMD Radeon GPU, and when I edit the game's config.yml to force disabling exclusive fullscreen, rpcs3 keeps crashing when starting the game. Disabling fullscreen optimization dind't help either.
After more testing I found that rpcs3 doesn't change the refresh rate to the maximum of the screen, instead it changes to the refresh rate that was defined at windows boot. If I change the refresh rate to 120hz and reboot, rpcs3 will always use 120hz when going fullscreen, no matter what refresh rate is setted on windows. The same happens with every refresh rate supported by the screen. I can use that as a workaround, but it would be nice if this was fixed somehow.

**Comment by kd-11** [comment]
Rpcs3 does not set a refresh rate at any point, we use the desktop resolution and refresh rate. If you have AMD, disable fresync for rpcs3 in control panel and see if that helps.

**Comment by Darkhost1999** [comment]
My smart TV with auto detect video enabled on the TV itself.
Will automatically detect SDR/HDR, Refresh rate, etc.
When watching the Harry Potter Movies my TV mode changes to 23.XX fps in fullscreen. Exit fullscreen and it'll restore 60fps as per my windows settings.
So make sure your hardware isn't effecting things too.

**Comment by danaigus** [comment]
Following @Darkhost1999 comment, I tested with a second ultrawide monitor and it stopped changing refresh rate, brought back the first one and it wasn't happening anymore either. So I think it was a hardware issue. I appreciate the help and sorry for the inconvenience.

**Comment by kd-11** [comment]
Closing.
