### ISSUE TITLE
[Optimization] Consider using VulkanMemoryAllocator

### ISSUE THREAD

**Issue by LifeIsStrange** [RPCS3/rpcs3#11693]
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator
This open source memory allocator, deveoopped by AMD could offer two significant kinds of improvements for RPCS3. 

1) A simplification of the Vulkan codebase regarding memory allocations/resource tracking.
Because the API is more ergonomic and higher level.
2) Improved performance and reduced VRAM usage.
This library has been highly optimized by experts for years, I don't know if it e.g do transparent bulk allocations but it leverage specific Vulkan extensions at runtime (e.g. VK_EXT_memory_priority extension and many others)
if supported for maximal performance and has also algorithmic optimizations. 
Hence I think this is worth exploring. 

See also https://gpuopen.com/learn/announcing-vma3-d3d12ma2/

**Comment by AniLeo** [comment]
We already use this.

**Comment by LifeIsStrange** [comment]
@AniLeo Great to hear! You should consider upgrading to the 3.0 version though (or even better use the master version as they recommend) https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/releases/tag/v3.0.0
