### ISSUE TITLE
(Killzone 3) Asynchronous Texture Streaming heavily impacting performance

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#11707]
I booted up Killzone 3 recently and noticed a massive 20fps loss compared to a year ago. Regression testing lead me to https://github.com/RPCS3/rpcs3/pull/11518 however, that Pull Request is simply when Async was first re-enabled on Nvidia GPU's. I've confirmed that performance goes back to normal on the latest master builds of RPCS3 if Asynchronous Texture Streaming is turned off.

Async Off:
![rpcs3_DC70fVav8R](https://user-images.githubusercontent.com/15137035/160951077-95d6afab-eca5-467a-a167-02993f81e261.jpg)
Async On:
![rpcs3_uXGq2l2HbA](https://user-images.githubusercontent.com/15137035/160951446-3625ebf6-090b-4708-a3ab-fb28af0f830c.jpg)
I haven't noticed any other games with a massive performance impact from async, and have been using it for most of the games I have.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8384929/RPCS3.log.gz)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/12389
Please retest.
