### ISSUE TITLE
Anisotropic filter option make the thread errors at the first start

### ISSUE THREAD

**Issue by Tarek2013** [RPCS3/rpcs3#11708]
Hi
I noticed that Anisotropic option (for any games) could make the threads error codes who stop the emulator (or close it up suddendly).
Indeed (I take God of War Ascension BCUS98232 for example) : if you start the game as 'fresh' (it means no cache at all) and you select Anisotropic X2,X4,X8 or X16, the game will crash when Kratos pass through the door of the prison to meet the Hecatonchire (there is a scrolling at this time) by closing the game.
[RPCS3.log-First Crash with Anisotropicx16.gz](https://github.com/RPCS3/rpcs3/files/8387137/RPCS3.log-First.Crash.with.Anisotropicx16.gz)

But,if you restart the game (without changing anything after the crash and keeping all previous caches), the game will run normally.
[RPCS3.log-Game run normally after crash.gz](https://github.com/RPCS3/rpcs3/files/8387174/RPCS3.log-Game.run.normally.after.crash.gz)

Now,if you to start a fresh game by selecting Anisotropic as Auto, the game will run normally and never crash at all.
[RPCS3.log-Game runs perfect with Anisotropic Auto.gz](https://github.com/RPCS3/rpcs3/files/8387212/RPCS3.log-Game.runs.perfect.with.Anisotropic.Auto.gz)

So, my meaning is : does the Anisotropic option could make some disorders into the threads operations during cache operation and/or during some SPU/PPU process ?

I used the last Master RPCS3 on Windows 10 with NVIDIA 3080TI lastest drivers and AMD 5950X.
And,before you bomb me,I tried different configs with and without patches : the results were same

**Comment by Asinin3** [comment]
God of War Ascension is pretty unstable please test this multiple times with AF enabled and no caches and see if you can reproduce this multiple times. Highly doubt it is related, and more likely a race condition.

**Comment by Tarek2013** [comment]
As I already said, with AF enabled, the game will crash exactly as the same point (and probably other later in game) but only at the first launch.When you restart it by keeping the same option enabled and without deleting any cashes, the game will show no crash at the crash-point he did before.
Only by putting AF as Auto as the first launch and without any cashes will make the game running proper.

**Comment by Asinin3** [comment]
I read what you said which is exactly why I asked you to delete your caches and relaunch the game so you can run into the same crash again. I'm basically asking you to keep running into the crash multiple times to confirm that it is reproduceable consistently and not something that just happened two or three times.

**Comment by Tarek2013** [comment]
Ok,I think I understood what you need : 
So, after some tests, if I delete SPU cashes and/or SHADERS cashes, the game will crash again.
But,if I delete PPU cashes, the emulator make a new compil of PPU cashes and it not affects the game (no crash at all).
Changing SPU cache size or any options in Shader compiling methods doesn't change anything

**Comment by Tarek2013** [comment]
NB : I also noticed that AF makes flickering on UNCHARTED 2 if you select it as X2,X4,X8 and X16 when the game is upscaled.
Put AF as AUTO brings not flickering at all,even at 300% upscaled fit.

**Comment by kd-11** [comment]
This game needs accurate RSX reservations enabled if you do not have TSX. From the logs it is pretty clear this is not the case:
`Accurate RSX reservation access: false`
AF override may introduce bugs in certain situations. This is a game enhancement, not a PS3 feature.
