### ISSUE TITLE
[Optimization] Reuse shaders on various gpu pipeline stages

### ISSUE THREAD

**Issue by LifeIsStrange** [RPCS3/rpcs3#11705]
Vulkan 1.3.210 introduces:

VK_EXT_graphics_pipeline_library - The VK_EXT_graphics_pipeline_library extension is to allow for separate compilation of four distinct parts of graphics pipelines. By allowing independent parts of the graphics pipeline to be compiled into a graphics pipeline library that is then linked together at the final stage to create the executable pipeline, it allows for greater re-use for pipelines having the same shaders or states across multiple pipelines. Basically it's about breaking things up in the graphics pipeline to allow for their modular re-use without having to compile a graphics pipeline in full for areas of overlap. This extension was worked on by the likes of AMD, NVIDIA, Google, Valve, Ubisoft, Roblox, and other major players.

source: https://www.phoronix.com/scan.php?page=news_item&px=Vulkan-1.3.210-Released
It might enable important optimizations for emulators ?

**Comment by sounddrill31** [comment]
Like shader cache on CEMU or YuZu emulators? So that weaker devices run it a bit better? That's an excellent idea

**Comment by Asinin3** [comment]
![image](https://user-images.githubusercontent.com/15137035/161230961-21fa8f96-627c-4e0a-b442-c0267ed54002.png)

**Comment by LifeIsStrange** [comment]
@sounddrill31 thus extension is knew, it's already possible to achieve a standard shader cache like Yuzu without this extension but yeah it's related and enable better caching.
Although according to @kd-11 it's not a bottleneck

**Comment by kd-11** [comment]
1. We already have a shader cache with IL caching. It basically already does what the extension makes official, but at a higher level.
2. The shader compilation from IL to SPIR-V or GLSL is very fast. In fact it happens during the "loading" phase which for most people takes a second or two if you have decent storage. Compiling these to native modules is also very quick.
3. The link step is what is slow. This extension would not help with linkage, that depends on the driver's shader compiler and native cache.
