### ISSUE TITLE
[Intel, ANV] Segfaults

### ISSUE THREAD

**Issue by A-w-x** [RPCS3/rpcs3#11704]
## Quick summary
every game segfault in a way or another with vulkan

3 of them
[rcafo.log.zip](https://github.com/RPCS3/rpcs3/files/8373155/rcafo.log.zip)
[rcffa.log.zip](https://github.com/RPCS3/rpcs3/files/8373157/rcffa.log.zip)
[rcTime.log.zip](https://github.com/RPCS3/rpcs3/files/8373159/rcTime.log.zip)

#### 5. Please provide your system configuration:
* Arch
* i7-1165g7
* xe
* mesa git (with ubo index disabled and dynamic fixes reverted due to regressions)
* rpcs3 master git

**Comment by kd-11** [comment]
Would be helpful to get some kind of stack trace with GDB. I do not own compatible hardware to test this one.

**Comment by A-w-x** [comment]
i tried to gen a backtrace but it was almost empty, maybe i did something wrong, but here is a full debug log

this is from rc acit, it is the easiest to reproduce
start a new game, after the video, as soon as it loads the first level it crashes

other games crash after a few minutes or bit more with the same error
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/8549742/RPCS3.log.zip)

**Comment by kd-11** [comment]
Maybe I should clarify. No crash happens on other hardware platforms and I do not have an intel igpu.

**Comment by kd-11** [comment]
Check if strict rendering fixes the crash.

**Comment by A-w-x** [comment]
no crash with strict rendering in acit, i ll test the others

should i close this if the other work?

**Comment by kd-11** [comment]
Yes. At least for now. When xe gpus are available we can re-evaluate intel hardware.

**Comment by A-w-x** [comment]
well, it seems segfaults are gone with strict but games are not playable due very low fps when enabled
oh well, closing this for now
