### ISSUE TITLE
Skyrim Red Start Screen.

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11718]
So it's come to my attention I've been commenting on an [issue](https://github.com/RPCS3/rpcs3/issues/9184) about a different issue thinking it is the same issue.
Let's move My issue here.

#### Prerequisites to reproduce
Dawnguard and Dragonborn installed. The game does not care if you have 1 of the dlc in French and the other in Spanish. You just need Dawnguard and Dragonborn installed. Use whatever language combo you feel like
#### Information
The PPU interpreter is a fix
![image](https://user-images.githubusercontent.com/60384196/161398297-a34fecaa-f65f-4b6f-91c9-db6f37cb9641.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8403371/RPCS3.log)
Meanwhile PPU LLVM is the issue.
![image](https://user-images.githubusercontent.com/60384196/161398346-6d12321c-196c-4b2f-bc49-682c43f8be04.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8403374/RPCS3.log)
* Keep in mind
This issue does not care what shader mode or what graphics renderer you are using. This issue is specifically caused by PPU LLVM.
* Specs
I am personally using a Ryzen 5 3600, GTX 1660 Super and Windows 11 Beta OS.
* Post Script
This issue is about specifically the red effect. If you have broken/missing sections of the dragon logo. Please see the [AMD specific issue](https://github.com/RPCS3/rpcs3/issues/9184)

**Comment by Nekotekina** [comment]
![image](https://user-images.githubusercontent.com/6028184/161401561-491fb533-99a5-44bc-b67f-89d48a61c97f.png)
Try some of these settings

**Comment by Darkhost1999** [comment]
Here are my tests while using the settings that are available while using LLVM. Tested with all on, All off, PPU vector on with default non-java mode, and PPU Saturation on with default non-java mode
<details>
<summary>Image spam testing</summary>

![image](https://user-images.githubusercontent.com/60384196/161402906-172aa29a-3a0c-4dae-9d87-a337ec621323.png)
![image](https://user-images.githubusercontent.com/60384196/161402848-1980ac0c-5c18-467a-8f8a-8218d99662a6.png)
![image](https://user-images.githubusercontent.com/60384196/161402928-7985e36b-f196-469c-a3a0-b4679309e8e9.png)
![image](https://user-images.githubusercontent.com/60384196/161403014-6263c9ca-c028-4602-9080-81b3d7b5a03b.png)
![image](https://user-images.githubusercontent.com/60384196/161403218-4f994792-3fe5-469c-a9d3-b343572e8160.png)
![image](https://user-images.githubusercontent.com/60384196/161403188-870d9832-ea0d-4aed-a51d-dc26f8017203.png)
![image](https://user-images.githubusercontent.com/60384196/161403241-fede8af8-6558-4007-9d51-d2f6cabfa241.png)
![image](https://user-images.githubusercontent.com/60384196/161403264-22d06691-b419-412e-a5ee-99023601d4af.png)

</details>
I'm getting ready to leave I can edit to add the combinations with non-java mode off later if desired as well.
All tests so far maintain the red screen as long as using LLVM and as long as those 2 specific DLC are installed at the same time.
Interpreter is not broken. Priority is low because Gameplay does not take place on the start menu.

**Comment by Megamouse** [comment]
This seems to be AMD specific. see: #9184

**Comment by Darkhost1999** [comment]
I see you didn't read my message.

The issue is about the red.

Nothing broken or missing

**Comment by Darkhost1999** [comment]
It does not help I've literally been commenting on that other issue for the past 4 months or so.
And whenever I realized I was discussing an entirely different issue I felt like an asshole and a dumbass.

**Comment by Nekotekina** [comment]
If AMD CPU is suspected, then another thing to try may be setting LLVM CPU to `haswell` or `nehalem`

**Comment by Darkhost1999** [comment]
![Screenshot_20220403-090905_GitHub.png](https://user-images.githubusercontent.com/60384196/161432029-c3af6a03-d4d5-410e-bfcb-4239751429c8.png)

I personally have not heard of an Intel 3080 CPU or an AMD 5700XT CPU.
No disrespect intended I just haven't heard of them.
I am gonna take the suggestion of the possibility it is AMD CPU specific and try my Intel laptop though. 

My issue requests seeing the differences between
This image
![Screenshot_20220403-081121_GitHub.png](https://user-images.githubusercontent.com/60384196/161432334-d31cb945-0c26-4630-8fc8-25dd7053f05f.png)
And this one
![161398346-6d12321c-196c-4b2f-bc49-682c43f8be04.png](https://user-images.githubusercontent.com/60384196/161432341-283263fe-6eff-4b88-b5dd-239ad75efa42.png)

When I realized my issue was different I came here, deleted my old messages over there, and expressly stated why they're not the same issue.
(My only aim is to provide clarity. An issue is about what is said not how it is said..)

**Comment by AphelionWasTaken** [comment]
I'm unable to reproduce on BLUS30778 v1.09, which is the most updated version of the original release. BLUS31202 is the Legendary Edition. I'm only seeing the issue described in the previous ticket.

Both DLCs are installed. Only non-default settings are 300% res scale and Write Color Buffers. Zcull is set to precise.

9900k/3080:
![image](https://user-images.githubusercontent.com/61633628/161436578-14a4f67b-596b-4c71-aa6e-96e8cfe18fb9.png)

3600/5700xt:
![image](https://user-images.githubusercontent.com/61633628/161436536-88684dd7-82c1-40f3-a1b7-0e6ea5ead9be.png)

This may not be AMD GPU related like I originally said - it could be the CPU, seeing as you have an Nvidia GPU and it isn't rendering properly. For some reason I recall us talking about it being a GPU-related issue on Discord.

**Comment by Darkhost1999** [comment]
My intel laptop is unaffected by this issue
![vkdiag](https://user-images.githubusercontent.com/60384196/161450305-ece7a53e-7bbc-4faf-bd9d-316e0e23de99.png)
![image](https://user-images.githubusercontent.com/60384196/161450310-7499be29-d0a9-4bec-9b63-9430832da5c4.png)

But again the dragon logo is not broken or missing so it is not the same issue as #9184
I do not know why BLUS30778 version 1.9 with DLC was not able to reproduce.
That 2nd screenshot above is how my screen looks using shader interpreter as the only one to experience a missing logo.
Async, Async + shader interpreter, Legacy worked. But again missing or broken dragon logo is offtopic.
We're only looking for if there is red or not.

The red seems to only exist on my AMD Ryzen 5 3600 and GTX 1660 Super. Not my laptop.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8405578/RPCS3.log)
I even used the same settings except for resolution scale I use on my Desktop.

**Comment by Darkhost1999** [comment]
@AphelionWasTaken are you able to swap GPUs in your PCs test AMD CPU with Nvidia GPU?
I feel the issue would be reproduced if you were able to render the dragon logo on your 3600

**Comment by Darkhost1999** [comment]
How can I prove this is a CPU issue?

While https://github.com/RPCS3/rpcs3/issues/9184 is a GPU issue.

You need to not be experiencing https://github.com/RPCS3/rpcs3/issues/9184 in order to see the dragon logo. In order to experience this issue. Making this issue in no way a duplicate issue.

It's possible this is an AMD CPU issue.
But that entirely separate issue is AMD GPU specific.

**Comment by Darkhost1999** [comment]
This has either been resurrected or is still an ongoing issue and was falsely closed as duplicate to an AMD GPU issue when I don't even have an AMD GPU.
LLVM CPU "skylake" doesn't work but my laptop with a skylake Intel Core i5-8250U Processor does not present this issue.
Aphelion's test was invalid to the conditions of reproducing this issue while https://github.com/RPCS3/rpcs3/issues/9184 was open and shows in screenshot no smoke or dragon logo to prove the issue wasn't present.

![image](https://github.com/RPCS3/rpcs3/assets/60384196/86fca605-8209-47e7-a304-fd7ca54d52dd)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11827552/RPCS3.log)
Fixed by ppu interpreter still
![image](https://github.com/RPCS3/rpcs3/assets/60384196/ca238b9b-fd43-4c9f-9dab-4fc0c2686031)
Requires Dawnguard and Dragonborn installed to create the issue. The order of installation and language combination does not matter. 1 installed but not the other will not create the issue it is only when both or even all 3 dlc are installed the issue is present
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11827614/RPCS3.log)
Here is a log of installing the dlc in case it's an error with the pkg installer.
This issue only exists with ppu LLVM and
> If AMD CPU is suspected, then another thing to try may be setting LLVM CPU to haswell or nehalem

Does not fix it
>Try some of these settings (ppu debug settings)

Results are same as https://github.com/RPCS3/rpcs3/issues/11718#issuecomment-1086735267
I don't know what to say besides this issue was closed wrongfully and prematurely. Even if this issue was created prematurely it's still present.
