### ISSUE TITLE
[Feature Request] add  game  pad   Y axis reverse

### ISSUE THREAD

**Issue by wanhshuibl** [RPCS3/rpcs3#11727]
## Quick summary
Add  a  button  to  Y axis reverse

## Details

Add a button to control whether to reverse the y-week input。When I push down the handle of the game pad, the input result is upward. Contrary to my expectation

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay

**Comment by illusion0001** [comment]
Yea, some games don't have an option to invert for whatever reason, silly

**Comment by Megamouse** [comment]
No

**Comment by Hasster1** [comment]
If you really need to do that, you can just...
https://user-images.githubusercontent.com/20757715/161500643-6cfc80f8-a5ed-408b-9bd1-48622086d1ff.mp4
