### ISSUE TITLE
The Last Of Us, crash before shader cashing (error=0x7e)

### ISSUE THREAD

**Issue by Martencel** [RPCS3/rpcs3#11723]
The game loads PUPs and SDUs etc etc, but when it should start creating shader cashes, it just freezes (or crashes, i honestly don't know how to describe this.)
I'm running it on custom settings but there's no difference between custom and default settings, the same error's showing up.

![Untitled](https://user-images.githubusercontent.com/58928395/161428455-967a1d71-d575-4eda-819f-9ed36e9063bb.png)

**Comment by Xcedf** [comment]
Where's the log file and what patches are enabled? feel like bad settings/patches

**Comment by Martencel** [comment]
> 
Yeah sorry, forgot the logs:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8404584/RPCS3.log)

Here's a picture of the patches:
![image_2022-04-03_152451](https://user-images.githubusercontent.com/58928395/161430278-a1cf08ff-ba3b-4a76-8878-0bd40af9d35d.png)

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed
