### ISSUE TITLE
[Feature Request] Upgrade to LLVM15

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#11721]
We're known to be the bleeding edge emulator, maybe this issue encourages updating to LLVM14 earlier.

**Comment by TotalCaesar659** [comment]
Does https://github.com/RPCS3/rpcs3/pull/13534 fix this?

**Comment by Darkhost1999** [comment]
Yes and no. This tracker was more or less a meme encouragement to stay up to date with the current official release of llvm.
There's a new current release, so this could just get updated to reflect that.

**Comment by AniLeo** [comment]
We're using LLVM 15 so this is completed
