### ISSUE TITLE
God of war ascension weird white lines on edges of wet surfaces

### ISSUE THREAD

**Issue by suyash691** [RPCS3/rpcs3#11729]
## Quick summary
White lines appear in god of war ascension in specific areas
![rpcs3 2022-04-05 00-42-40](https://user-images.githubusercontent.com/9547836/161615437-76e2cade-0590-4105-b9f3-c3ae00be097a.png)

## Details
I tried enabling WCB RCB RDB and even accurate xfloat and allow host GPU labels, alongside accurate rsx reservation but same issue

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8412530/RPCS3.log)

#### 2. RSX Capture
https://drive.google.com/file/d/1P0-xtxrD0u0XLTjpOO6urmFYzYLL2aVW/view?usp=sharing

#### 3. Please attach screenshots of your problem.
![rpcs3 2022-04-05 00-42-08](https://user-images.githubusercontent.com/9547836/161615449-14419dfd-c410-41ec-9aba-9fcdbe849451.png)

#### 4. Please provide comparison with real PS3.
The real ps3 doesn't exhibit the white lines as seen in the screenshot

#### 5. Please provide your system configuration:
* OS Windows 11
* CPU Ryzen 5900x
* GPU RTX 3080
* Driver version  512.15

#### Please include.
* Anything else you deem to be important

**Comment by Jonathan44062** [comment]
That's mesh trimming, it happen when a game can't go beyond to the resolution 720p
Besides, Resolution scaling is a hack (Not all games can support resolution scaling with the way they work), and we don't support people making issues about it on the issue tracker.

**Comment by kd-11** [comment]
For upscaling issues, ask on discord. There are game-specific patches to disable mesh trimming for example that allows such games to upscale correctly.
