### ISSUE TITLE
The Last Of Us, crash before shader cashing (error=0x7e)

### ISSUE THREAD

**Issue by Martencel** [RPCS3/rpcs3#11724]
The game loads PUPs and SDUs but when it should start creating shader cashes, it just freezes (or crashes, i honestly don't know how to describe this; it just cuts to black)
I'm running it on default settings with no patches enabled.

Here's an image:
![image](https://user-images.githubusercontent.com/58928395/161430781-7cda6b58-c5a1-4ad3-865c-373b6f683c9c.png)

Somehow GitHub can't process the log file, at least that's what it's saying when i try to upload it.

**Comment by Martencel** [comment]
I managed to upload the logs!
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8404632/RPCS3.log)

**Comment by Megamouse** [comment]
The log literally tells you a possible solution.
Have you tried that?

**Comment by Martencel** [comment]
> 

yea, I've just retried it and it still says the same exact thing.

**Comment by YuriNator557** [comment]
The log suggest that this game is a repackaged ISO, RPCS3 does not support these
