### ISSUE TITLE
In mgs 4 there is a controller problem.

### ISSUE THREAD

**Issue by DrAwooo** [RPCS3/rpcs3#11733]
yes yes this has been "answered" before but I can definitely say the answer before was incorrect. for some people the game unpacks the demo.dat files and i cant for the life of me figure out how to repack them. the issue the controller has is that during boot up everything seems fine until the menu. at that point, no matter what controller you are using you will not be able to navigate it or even start the game. again, the problem has been diagnosed but i cant figure out how to fix it.

**Comment by Megamouse** [comment]
Please seek help at our discord.
