### ISSUE TITLE
 PlayStation Home - OSK/VSK (keyboard) missing essential functions. (Required for Home online testing and release on RPCS3.)

### ISSUE THREAD

**Issue by PSHFigment** [RPCS3/rpcs3#11737]
### **Summary**
PlayStation Home's keyboard doesn't open when you press triangle (this should open up the on-screen keyboard osk.), this along with a few other issues that will be highlighted within other issue reports prevents a stable release of PlayStation Home online for RPCS3 at the moment.

### **Details of Issue**
Instead of opening the keyboard when pressing triangle (the osk button for chat.) it prevents your ability to press anything on the controller with the exception of your analogue sticks (player movement.) 

(RPCS3 log of the issue, this affects both the offline and online versions of PlayStation Home.)
https://cdn.discordapp.com/attachments/838553670831308820/961450965846863892/rpcs3.log

### **Notes**
Has been tested on hundreds of different types of computers (since we did a distribution of offline for PlayStation Home) the issue remained consistent regardless of specs. 
- But keyboard is fully operable on online and offline versions of PlayStation Home on original PS3 hardware.

### Specs for this specific test.
Processor    Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz
Installed RAM    32.0 GB
GPU NVIDIA GeForce RTX 2080 Ti
System type    64-bit operating system, x64-based processor
Edition    Windows 10 Home
Version    21H1
OS build    19043.1586

**Comment by Megamouse** [comment]
Can you provide a video of the same interactions on a  PS3?

**Comment by PSHFigment** [comment]
Sure, here's the pressing triangle in harbor studio from PS3 PlayStation Home (Retail NPIA00005) 

https://user-images.githubusercontent.com/74638626/162509566-b5e9e43a-7bf8-459a-ae93-7bee3defd792.mp4

**Comment by clienthax** [comment]
Seems to be due to us not handling the keyboard callbacks.

**Comment by Washong** [comment]
Delete the issue @a
@Megamouse @clienthax @PSHFigment @robxu9 @13xforever @octopoulos @Chocobo1 @osvcos @Plagman @Plagman @Whatcookie @Whatcookie @magiruuvelvet @jy95 @Yahfz @Niram7777 @ikki84
