### ISSUE TITLE
[Feature Request] Swap Disc

### ISSUE THREAD

**Issue by expected-ingot** [RPCS3/rpcs3#11739]
## Quick summary
Please briefly describe what feature you would like RPCS3 to have

Swap Disc; this feature would swap the disc in the emulated PS3's drive without exiting the game.

## Details

Please describe the feature as accurately as possible.

The feature would swap the disc while keeping the game running.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay: would let users playing games like SingStar use their song collection.

#### 2. Please tell us, why your feature is important to RPCS3.

I'm trying to get SingStar to work. I have SingStar Vol. 1 however it doesn't boot. The new version does boot though. So I thought that I can use the "Swap Disc" feature to insert the SingStar Vol. 1 disc. However RPCS3 does not have a Swap Disc option. This feature is would help users access their song collection on games like SingStar in the emulator.

#### 4. Please provide your system configuration:
* OS: Windows 10
* CPU: Intel Core i7
* GPU: NVIDIA GeForce RTX 2060 (laptop)
* Driver version
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by Megamouse** [comment]
Is this even possible with singstar on a PS3 ?

**Comment by Darkhost1999** [comment]
> Is this even possible with singstar on a PS3 ?

Yes see
https://blog.playstation.com/2008/08/21/how-it-works-singstar-ps2-ps3-compatibility/
For more info.
Appears to be a unique feature specific to SingStar. Idk if literally any other game ever used swap disc.
According to the blog it appears as if the swap disc feature is not required for normal gameplay. But as to only unlock and continue your ps2 progress on the ps3.

**Comment by expected-ingot** [comment]
Yes, the feature unlocks the songs from other games. It also works with the PS3 discs

(PS3 Singstar > SingStar Polskie Hity)

**Comment by Megamouse** [comment]
It should now also work for ps2 discs.
But it seems i'm missing some trustdata.xml, so I can't truly very

**Comment by Megamouse** [comment]
This should now work in master

**Comment by Megamouse** [comment]
I'll close this. Feel free to re-open the issue if it doesn't work.

**Comment by expected-ingot** [comment]
> > I'll close this. Feel free to re-open the issue if it doesn't work.
> 
> when I try to disc swap I can't click insert disc, what do I do to disc swap?
> 
Using a digital version of a game and then trying to insert a disc, it doesn't let you. I'll try to patch a way to do that in

**Comment by see-dos-run** [comment]
Not sure if anyone's still working on this, TIA if you can help!

I can confirm PS3 Singstar disc swapping works fine, am able to select "Swap Disc" within the game itself, then use the "Eject Disc" and "Insert Disc" commands in the main RPCS3 window to select the folders for the PS3 games (actually just realised don't even need to select "Swap Disc" within the game... just ejecting the disc and inserting another from the main window works fine).

When I try to select a folder for a PS2 game (file structured copied from an ISO taken from original disc), it doesn't seem to recognise it, the PS3 game continues to sit on the "Insert a Singstar disc" screen.

Is there any logging or anything I could provide that would assist getting the PS2 disc swap to function?

**Comment by crapbass** [comment]
> Not sure if anyone's still working on this, TIA if you can help!
> 
> I can confirm PS3 Singstar disc swapping works fine, am able to select "Swap Disc" within the game itself, then use the "Eject Disc" and "Insert Disc" commands in the main RPCS3 window to select the folders for the PS3 games (actually just realised don't even need to select "Swap Disc" within the game... just ejecting the disc and inserting another from the main window works fine).
> 
> When I try to select a folder for a PS2 game (file structured copied from an ISO taken from original disc), it doesn't seem to recognise it, the PS3 game continues to sit on the "Insert a Singstar disc" screen.
> 
> Is there any logging or anything I could provide that would assist getting the PS2 disc swap to function?
> 
> 
> 
I don't think PS2 discs work atm, this is a PS3 emulator after all so

**Comment by see-dos-run** [comment]
> > Not sure if anyone's still working on this, TIA if you can help!
> > I can confirm PS3 Singstar disc swapping works fine, am able to select "Swap Disc" within the game itself, then use the "Eject Disc" and "Insert Disc" commands in the main RPCS3 window to select the folders for the PS3 games (actually just realised don't even need to select "Swap Disc" within the game... just ejecting the disc and inserting another from the main window works fine).
> > When I try to select a folder for a PS2 game (file structured copied from an ISO taken from original disc), it doesn't seem to recognise it, the PS3 game continues to sit on the "Insert a Singstar disc" screen.
> > Is there any logging or anything I could provide that would assist getting the PS2 disc swap to function?
> 
> I don't think PS2 discs work atm, this is a PS3 emulator after all so

Thanks, yes I'm aware PS2 discs don't work directly in RPCS3, this is specifically for the "swap disc" functionality available in the SingStar series, as described in the posts above. This is done by starting a PS3 Singstar game, from within the game you can elect the PS3 disc once the game is running, insert a PS2 SingStar discs, and the running game will load the songs off the PS2 disc.
, 
Edited -> sorry @expected-ingot I only saw this reply on my phone, didn't realise this was your thread, can see you're well across how Singstar disc swap works. Thanks for replying. The reason I hoped the PS2 discs would work is a couple of posts above by MegaMouse mentioning that "It should also now work for PS2 discs".
