### ISSUE TITLE
LLVM Crash in Sonic CD with lower compilation threshold

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1174]
With a threshold of 10 Sonic CD always crash after the "press start" menu,
the faulty llvm code is this one :

https://gist.github.com/vlj/0a9047b60dacd04ce756

(block is is variable, around 500)
I will update the gist with ppu opcode later.

**Comment by vlj** [comment]
CMPLI is the faulty instruction

**Comment by vlj** [comment]
Actually no false positive.

**Comment by danilaml** [comment]
You could try looking at instructions that don't have tests implemented for them (as it was the case with MTOCRF). They are likely to be broken (if they are the cause). Also instructions that I marked(commented out tests) as "unhandled exception" might be interesting. I haven't teste if they were fixed by the most recent commits though.

**Comment by vlj** [comment]
It's apparently blt instruction (BC) not covered by test. It's the last instruction run before crash anyway.
I think it branches the wrong target. Since the branch has a load inst it triggers a segfault.

**Comment by danilaml** [comment]
@vlj what is relation to the threshold then?

**Comment by paulsapps** [comment]
Probably it didn't get compiled previously

**Comment by vlj** [comment]
Yes, lowering the threshold means that more block get compiled.
A threshold of 10 means that a block is compiled if the interpreter executes it at least 10 times.

By default the threshold value is 1000. A too low value is not really usefull but it can help spot compiler error.

**Comment by vlj** [comment]
Ok it was an error of mutex relocking in the same thread. Fixed with a recursive mutex instead.

**Comment by paulsapps** [comment]
So was actually crash not hang? ;)

**Comment by danilaml** [comment]
@paulsapps iirc it crashes when twi threads try to execute same block at the same time.

**Comment by vlj** [comment]
locking std::mutex with the same thread crashes, you have to use std::recursive_mutex (and it doesn't crash this way). However the latter is slower than the former, I'm looking at atomic based solution.
