### ISSUE TITLE
XMB does not work anymore

### ISSUE THREAD

**Issue by ArbestRi** [RPCS3/rpcs3#11747]
## Please do not ask for help or report compatibility regressions here, use [RPCS3 Discord server](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/) instead.

I tried booting the XMB but it will NEVER boot.

## Details
So this is what I get after booting the XMB:
"E sys_net: WSAPoll failed: 10038 x56331"
I tried many different firmwares, but I was able to boot a total of ZERO of them.
I tried them on the latest build.

#### Specs
* OS Windows 11 64-bit
* CPU Intel Core i7-10700F
* GPU nVIDIA GeForce RTX 2060 SUPER
* Driver version 512.15

* These issues must get fixed RIGHT NOW.

**Comment by Darkhost1999** [comment]
https://wiki.rpcs3.net/index.php?title=Help:Frequently_Asked_Questions

![Screenshot_20220409-121537_Firefox Beta.png](https://user-images.githubusercontent.com/60384196/162584507-1b8fc172-5174-4dda-96fa-8f6c47653dd9.png)

**Comment by ArbestRi** [comment]
Thanks! I also downgraded to 0.0.21-13411, which didn't give me issues last time.

**Comment by ArbestRi** [comment]
The latest build has an bug that bricks the XMB immeadtly, the last version had that bug absent.

**Comment by clienthax** [comment]
Prob fixed by #11746 11746

**Comment by Megamouse** [comment]
@ArbestRi can you please try again?
it might be fixed now.

**Comment by Darkhost1999** [comment]
![image](https://user-images.githubusercontent.com/60384196/162587730-57d3476f-5847-43c9-bb71-fd6f4aa1b2ec.png)
Works here.

**Comment by Darkhost1999** [comment]
#11740 indeed did cause regression but is fixed now

**Comment by MSuih** [comment]
Closing as fixed
