### ISSUE TITLE
[Feature Request] Patch for Destiny 1

### ISSUE THREAD

**Issue by ryanrox333** [RPCS3/rpcs3#11744]
## Quick summary
Please briefly describe what feature you would like RPCS3 to have.
Basically, I have a patch that adds support for Destiny by changing it's protocols inside the game.

## Details

Please describe the feature as accurately as possible.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.
It is a patch.

#### 2. Please tell us, why your feature is important to RPCS3.
This adds support to being able to create custom servers inside RPCS3 for Destiny.

#### 3. Please attach screenshots of the feature implemented in other projects.
I mean, the private servers for Destiny that are being created use this patch and it works for them...

#### 4. Please provide your system configuration:
* OS 
* CPU
* GPU
* Driver version
* etc.
Don't deem this stuff necessary.

#### Please include.
* Anything else you deem to be important

Code:
[Hastebin Link](https://www.toptal.com/developers/hastebin/sofebeqejo.yaml)

**Comment by ryanrox333** [comment]
I don't really know where else to put this (for it to be added) so I put it here.

**Comment by YuriNator557** [comment]
Patches are supposed to be added to the wiki page for the game:

https://wiki.rpcs3.net/index.php?title=Destiny
