### ISSUE TITLE
E SYS: 'sys_fs_opendir' failed with 0x80010006 and E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT though folder and files exist.

### ISSUE THREAD

**Issue by ryanrox333** [RPCS3/rpcs3#11759]
## Quick summary
So when downloading data for game (inside the game itself), it checks for a folder and returns this error.

`E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS31181/USRDIR/d00000bb/”`

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8459722/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
Not a graphical issue.

#### 3. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/44746268/162635704-15826b3d-e0aa-42fd-88e8-67391a38bc26.png)
![image](https://user-images.githubusercontent.com/44746268/162635716-5647b4e0-087d-4cbb-af3b-91bb45bf5fa8.png)

#### 4. Please provide comparison with real PS3.
Real PS3: Downloads files and moves to the next folder (batch of files).
RPCS3: Redownloads the same files/folders.

#### 5. Please provide your system configuration:
* OS Windows 11 Home
* CPU i7-9700F
* GPU Nvidia GTX 1660
* Driver version 30.0.14.9709

#### Please include.
* Anything else you deem to be important
This could be a bug with the game however, just wanting to make sure.

**Comment by ryanrox333** [comment]
Picture of both folders and files existing inside the USRDIR:
![image](https://user-images.githubusercontent.com/44746268/162635859-44c7c107-f843-42ef-8659-4510c710d941.png)
![image](https://user-images.githubusercontent.com/44746268/162635872-2bc3c4a4-9ad7-41ff-967e-8ab50198a4a3.png)

**Comment by RipleyTom** [comment]
Not a bug, the game deletes the directory:
```
·W 0:42:52.615022 {PPU[0x1000008] Thread (async_job #0/2) [0x01f71f14]} sys_fs: sys_fs_rmdir(path=“/dev_hdd0/game/BLUS31181/USRDIR/d00000bb/”)
·! 0:42:52.615289 {PPU[0x1000008] Thread (async_job #0/2) [0x01f71f14]} sys_fs: sys_fs_rmdir(): directory “/dev_hdd0/game/BLUS31181/USRDIR/d00000bb/” removed
```

And then once the directory has been deleted sys_fs_opendir on that path fails:
```
·W 0:43:40.099289 {PPU[0x1000008] Thread (async_job #0/2) [0x01f72000]} sys_fs: sys_fs_opendir(path=“/dev_hdd0/game/BLUS31181/USRDIR/d00000bb/”, fd=*0xd01ae880)
·E 0:43:40.099832 {PPU[0x1000008] Thread (async_job #0/2) [0x01f72000]} SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS31181/USRDIR/d00000bb/” [2]
```

And then it proceeds to create the directory again:
```
·W 0:43:40.099946 {PPU[0x1000008] Thread (async_job #0/2) [0x01f75fc8]} sys_fs: sys_fs_mkdir(path=“/dev_hdd0/game/BLUS31181/USRDIR/d00000bb/”, mode=0700)
```

Ie no bug there.

**Comment by mud01x** [comment]
how to fix this issue?

**Comment by Clumsy0420** [comment]
I'm currently experiencing the same issue any help?

**Comment by ryanrox333** [comment]
As what @RipleyTom said, there is no issue, it just deletes the directory. Not a bug/issue.

**Comment by reyesjl** [comment]
how can we make the game not freeze or crash to adjust for this, (no bug/issue/feature/intended functionality)?

**Comment by cohaereo** [comment]
> how can we make the game not freeze or crash to adjust for this, (no bug/issue/feature/intended functionality)?

The freeze can actually also happen on a real hw, so I wouldn't really consider it "fixable"

**Comment by reyesjl** [comment]
1.  Game freezes every time on HW?
  2.  Game is unplayable?

Online it says compatibility is okay – as well as default settings works fine. So strange there is still a freeze at the menu and even just loading before the menu. Haven’t managed to load at all.

**Comment by MilesTailsFan2005** [comment]
this happens also with Sonic Adventure (PSN) heads up to anyone!
