### ISSUE TITLE
(Regression) Framelimiter no-longer works with RPCS3's native interace

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#11753]
After https://github.com/RPCS3/rpcs3/pull/11607 merged, the frame limiter no-longer works for RPCS3's native interface.
Even if I set a 60fps frame limit for God of War 3, as soon as I open the load dialog my FPS skyrockets to 300-500fps. And often crashes with a fatal device lost error due to this high frame rate. I tried to get a validation log, but debug output slows the game down so much that it doesn't crash.

![image](https://user-images.githubusercontent.com/15137035/162612325-88e534fc-faf3-4d44-8147-584c60ee001d.png)
![image](https://user-images.githubusercontent.com/15137035/162612425-db94ab5d-e09f-4558-8c90-aa8f4b8c22ad.png)

**Comment by illusion0001** [comment]
Highjacking timers also breaks the framecap, doesn't happen in previous versions

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/163243119-19da48e7-349b-425c-8d69-09ca48cbc7ba.png)
Either the regressing PR is wrong, or this is always how it worked.

**Comment by kd-11** [comment]
Try with https://github.com/RPCS3/rpcs3/pull/11805
The fps cap works the same as previously using that PR as far as I can see, but for my games it was never locked to the limit before the PR. Or maybe it regressed further back.

**Comment by Asinin3** [comment]
Try 60fps limit instead of auto. When I use Auto it caps to 120fps in the load screen rather than 60.

**Comment by Asinin3** [comment]
Fixed in new PR, FPS now caps to 60 as expected. Auto capping the frame-rate higher than 60 was caused by me having vblank set. But the main regression was still there without it. I'll clean up my comments as that was an unrelated issue.

**Comment by kd-11** [comment]
Ok. I guess that fixes the capping when a dialog is opened synchronously, but for asynchronous dialogs it does not cap. I'll fix that as well.

**Comment by kd-11** [comment]
Fixed now for all overlays.
