### ISSUE TITLE
Regression: Divekick [NPUB31279] regressed from ingame to loadable (#6761)

### ISSUE THREAD

**Issue by digitaldude555** [RPCS3/rpcs3#11761]
## Quick summary
Divekick regressed to loadable last working build is 0.0.7-8878 and was broken in 0.0.7-8879 #6761

#### 2. Please attach TWO logs:
[RPCS3DiveKickWorking.zip](https://github.com/RPCS3/rpcs3/files/8459876/RPCS3DiveKickWorking.zip)
[RPCS3DiveKickBroken.zip](https://github.com/RPCS3/rpcs3/files/8459877/RPCS3DiveKickBroken.zip)
[RPCS3DivekickMaster.zip](https://github.com/RPCS3/rpcs3/files/8459878/RPCS3DivekickMaster.zip)

**Comment by Megamouse** [comment]
There is not a single thing in the log file that suggests that the PR was the culprit.
It simply stopped calling cellVdecGetPictureExt.

Maybe try my PR if it changes anything

**Comment by digitaldude555** [comment]
> There is not a single thing in the log file that suggests that the PR was the culprit. It simply stopped calling cellVdecGetPictureExt.
> 
> Maybe try my PR if it changes anything

[RPCS3DivekickAgain.zip](https://github.com/RPCS3/rpcs3/files/8462409/RPCS3DivekickAgain.zip)
Nope still just a black screen.

**Comment by AniLeo** [comment]
Adding @elad335 since it broke on #6761

**Comment by Megamouse** [comment]
I think I know what's wrong. I'll add a fix today

**Comment by Megamouse** [comment]
Hmm. It regressed because cellAudioQuit is not properly implemented.
Once the keys are cleared, the game stops working.
I'm assuming it's related to the event queue in cellAudio.
I'll pass on this one
