### ISSUE TITLE
Just Cause 2 crashes often with Device Lost errors

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#11768]
## Quick summary

Just Cause 2 repeatedly crashes with Device Lost errors,

## Details

Starting roughly 10 or so updates ago, Just Cause 2 would occasionally crash with no error message.  This was easily fixed by increasing Driver Wakeup Delay a bit, allowing me to play for days straight without any issues.  However, as of the 5 most recent updates, a new issue has arisen, making the game crash very often with a Device Lost error.  Once I get this error, going ingame again is impossible, even after fully restarting the emulator, as after loading a save file it'll immediately throw a Device Lost error after rendering the first frame of 3D graphics.  The only fix I've found is to delete the entire shader cache which will temporarily allow you to go ingame again before it happens again, usually after 5-10 minutes of gameplay.  This also deadlocks the emulator so I had to manually compress the log to .gz.  Also, the log can sometimes be almost 2 GB in size.

#### 1. Please attach RPCS3's log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8468443/RPCS3.log.gz)

#### 4. Please provide comparison with real PS3.

Never crashes.

#### 5. Please provide your system configuration:
* OS: Windows 10 Pro x64 Build 19043
* CPU: Intel Core i9-10900K
* GPU: NVIDIA RTX 2080 Super
* Driver version: 497.29

#### Please include.
Game runs at full gamespeed, never lags, and there's never any visual glitches, except when using MSAA but they're minor and the game looks better with MSAA disabled.

**Comment by AniLeo** [comment]
Missing what build regressed it, wrong issue template used

**Comment by SlyCooperReloadCoded** [comment]
PR 11717 is when it started I think, either that or 1-2 releases after that.  I remember both this game and RaC got MSAA issues at the same time and had them fixed at the same time, then shortly after they got fixed, this issue started.

**Comment by kd-11** [comment]
The fact that it crashes quickly is good.
1. Install the vulkan SDK here: https://vulkan.lunarg.com/sdk/home#windows
2. Enable 'Debug output' in the config.yml or debug tab. Also enable 'Renderdoc compatibility mode' while you're there.
3. Start the game until you get the crash.
4. Upload the log here.

**Comment by kd-11** [comment]
Actually I just noticed your driver version.
It's a problem with the nvidia driver. They fixed the crashes in 512.x series.

**Comment by SlyCooperReloadCoded** [comment]
I updated my driver to latest and now the issue seems to be gone.

**Comment by SlyCooperReloadCoded** [comment]
I'm still getting device lost errors frequently on latest GPU drivers.  Reinstalling drivers only temporarily solved the issue:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8558590/RPCS3.log.gz)

**Comment by SlyCooperReloadCoded** [comment]
Could this be re-opened?  It's still happening on a clean install of the latest drivers.
