### ISSUE TITLE
Regression: Left page of the book is not displayed anymore in Castlevania - Harmony of Despair (#11315)

### ISSUE THREAD

**Issue by Tarek2013** [RPCS3/rpcs3#11764]
Hi
Even if Write Buffer Color is Enabled, the game lost the display of the left page in Castlevania Harmony Of despair (NPUB30505 but same with Eur version). Modifying any graphic/processor options doesn't change anything

![IMG_9047](https://user-images.githubusercontent.com/65652256/162641876-273e02c1-1815-44c7-904d-0e3b72ebc9b3.JPG)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8460019/RPCS3.log.gz)

**Comment by kd-11** [comment]
It would help if you tried to find out when it broke. Did it work before? When did it stop working? It would really help to get started.

**Comment by Tarek2013** [comment]
@kd-11 
I know it works before, but I'm really sorry coz I really can't remember which version of RPCS3 was (I don't play often this game and I just tried it by hazard)
The only thing I can find that some peoples playing it on Youtube as perfect emulated graphics which different version of RPCS3...

**Comment by Darkhost1999** [comment]
You can find old builds here
https://rpcs3.net/compatibility?b
And test the version that works and find the version that does not.
I go page by page top result everytime. Then half a page, 1/4, 1/8 till there are only 2 results. 
1 that works. 1 that does not work.

This will help in diagnosing the issue and getting it solved.

**Comment by Tarek2013** [comment]
Ok,  I found it !
The game works until 0.0.20-13177 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8498786/RPCS3.log.gz)

But, when you try it with the 0.020-13178, the bug of graphic's page displaying is there !
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8498794/RPCS3.log.gz)

I've noticed that the PPU Interpreter (fast) is no more on the 0.0.20-13178 version. Maybe is the source of the issue ?

**Comment by Darkhost1999** [comment]
Possibly related then. I can test soon
<https://github.com/RPCS3/rpcs3/issues/11718>

**Comment by VelocityRa** [comment]
Sounds like #11315 broke it.

**Comment by AniLeo** [comment]
The log file linked on this issue is empty

**Comment by Tarek2013** [comment]
@AniLeo 
Yes,sorry.The first was empty but the 2 of the finding issue post was ok.

The bug is now fixed in 0.0.21-1351
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8500591/RPCS3.log.gz)

So, I close this topic
