### ISSUE TITLE
[Feature Request] Enable currently disabled PPU Dynamic Recompiler

### ISSUE THREAD

**Issue by thx4ever** [RPCS3/rpcs3#11799]
## Quick summary
Enable PPU Dinamic Recompiler that are currently disabled

## Details

In current version PPU recompiler dinamic are disabled, only static PPU static (slow) are enabled and LLVM

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* More speed in games that currently using PPU static recompiler(slow) until LLVM are fixed 
 etc.

#### 2. Please tell us, why your feature is important to RPCS3.
In some games like Pro Evolution Soccer 2018 crashes the emulator, so we need to use PPU static recompiler(slow), maybe we can get more speed using dinamic PPU recompiler until LLVM are fixed?
#### 4. Please provide your system configuration:
* OS Windows 11
* CPU Intel Xeon
* GPU GTX 1050 

Regards

**Comment by YuriNator557** [comment]
Intentionally disabled, I believe more work needs to be done before it is usable

**Comment by illusion0001** [comment]
Just use static if debugging

**Comment by Megamouse** [comment]
There's no reason to have a feature request for something so obvious
