### ISSUE TITLE
Can't open Sly Cooper Franchise games - Sly cooper Collection

### ISSUE THREAD

**Issue by LDgod** [RPCS3/rpcs3#11807]
## Quick summary
when I press to start the game, it even loads but does not start, some names appear in red on the emulator..

## Details
when I press to start the game, it even loads but does not start, some names appear in red on the emulator.
Attached are the screenshots of my situation.

#### 3. Please attach screenshots of your problem.

![1](https://user-images.githubusercontent.com/103600821/163250176-51bbc74f-07f4-4424-b33b-d85fdeacb269.png)
![2](https://user-images.githubusercontent.com/103600821/163250199-064613cb-f71b-4965-90c5-8a35e9530c0a.png)
![3](https://user-images.githubusercontent.com/103600821/163250224-ddb0d14a-2de3-4936-8dfd-076612453b32.png)

#### 5. Please provide your system configuration:
* OS - Windows 10
* CPU - FX8300 AMD
* GPU - RX 570 4GB
* Driver version - 4.88

**Comment by Jonathan44062** [comment]
You're testing with a PR Build, not the master build, try again with the latest build

**Comment by LDgod** [comment]
> Você está testando com um PR Build, não o master build, tente novamente com o build mais recente
desculpa, eu nao entendi... meu emulador esta desatualizado ?
