### ISSUE TITLE
Ratchet & Clank: A Crack in Time Crashes often with Device Lost errors

### ISSUE THREAD

**Issue by zeroking1998** [RPCS3/rpcs3#11813]
after about 20 minutes of game time i get this error

Spec
GTX 970
Ryzen 9 5900X
Windows 11
Treiber
512.15 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8490881/RPCS3.log)

**Comment by kd-11** [comment]
I haven't observed this problem - we use this title to stress test our memory balancer. This could be an NVIDIA driver issue, but the crashy drivers should have been fixed after version 511. Worth a shot to do a clean install.
I'll request testers to try and reproduce.

**Comment by YuriNator557** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8535124/RPCS3.log.gz)

Played for around an hour, could not reproduce.

**Comment by kd-11** [comment]
Could be a result of the 49x bug that causes some older nv drivers to crash randomly. This might require a clean install of the drivers.

**Comment by zeroking1998** [comment]
@kd-11  ok i'll try it and let you know if it worked

**Comment by Yahfz** [comment]
@zeroking1998 did it work?

**Comment by zeroking1998** [comment]
@Yahfz it helped a little, i can play a little longer now, but it still crashes with the same errors

**Comment by AniLeo** [comment]
Device Lost issues need to be retested with Vulkan SDK installed + Debug Tab > Debug Output enabled
When you get the crash, upload the log file here

**Comment by kd-11** [comment]
This was fixed by https://github.com/RPCS3/rpcs3/pull/13875. Request to reopen if you can reproduce in this title.
