### ISSUE TITLE
Street Fighter X Tekken[BLES01252]: Crashes when exiting fight. Error: "TODO: lv2_socket_raw::close"

### ISSUE THREAD

**Issue by Manya3084** [RPCS3/rpcs3#11838]
Details:
When exiting a fight, the game will hard lock with the error (TODO: lv2_socket_raw::close) displayed in the log feed.
Requires force closing RPCS3. 
This is with default settings and also the audio unbuffered to fix the sound in FMV. 
 
Log File:
[BLES01252.log](https://github.com/RPCS3/rpcs3/files/8521972/BLES01252.log)

Screenshots:

![Screenshot1](https://user-images.githubusercontent.com/104078862/164244048-bb300137-8860-44bf-aeda-4c3b806d9d34.png)

![Screenshot2](https://user-images.githubusercontent.com/104078862/164244085-7e042d4d-0235-4c7e-a888-4018dc4c501d.png)

PS3 Comparison:
I fired it up on my old PS3 and this doesn't happen. Fight ends and back to the start options as normal.

System Config:
OS: Windows 11
CPU: 12900K
GPU: 6900XT
GPU Driver version: 22.4.1
RPCS version: v0.0.21-13458-f1a37da9

Please advise if you require anymore info.

**Comment by RipleyTom** [comment]
This was fixed with https://github.com/RPCS3/rpcs3/pull/12073 .
