### ISSUE TITLE
45 fps bug

### ISSUE THREAD

**Issue by humam2104** [RPCS3/rpcs3#11840]
The 60 fps setting has a problem with the emulator, it actually runs at 45 fps. 
![image](https://user-images.githubusercontent.com/41898465/164363261-6ef9e153-a086-49d9-a6fe-8121273ee378.png)
I even updated RPCS3 with no avail. A fix is appreciated.

**Comment by illusion0001** [comment]
No log provided. Please upload rpcs3.log from emulator folder after running the affected game.

**Comment by humam2104** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8527408/RPCS3.log)
I don't know if this would make a difference. The idea is totally it's a typo in the settings, nothing more. (the 60 is above the 30 and under 50, which means that it's supposed to be 45). This was tested in the program.

**Comment by calvinvalerian** [comment]
@humam2104  Your GPU is not strong enough I have tested with no issue.

**Comment by calvinvalerian** [comment]
Buy better GPU

**Comment by YuriNator557** [comment]
> Buy better GPU

The 980ti is more than enough to run RPCS3

Unable to replicate
![image](https://user-images.githubusercontent.com/76178650/164489997-c4c01189-9e84-47fb-b311-3506efeb5960.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8532263/RPCS3.log.gz)

The log also suggests that the limit is set to 59.94, not 60fps anyway

**Comment by nastys** [comment]
Try framelimit Off and VSync On/Off.

**Comment by humam2104** [comment]
The comments after my OP don't reflect a good understanding of it. What I'm trying to say here is that the game runs at 45 fps when I select the "60 fps" option. However, when I select the 59.94 fps option it runs smoothly at 60 fps. The issue is not the hardware but a mistake in the naming of "60 fps". It should be 45 fps as it lies between the 30 fps and the 50 fps. And multiple tests while selecting this "60 fps" option show that it limits the fps only to 45 fps.

**Comment by YuriNator557** [comment]
It does not do this for me when I set the frame limiter to 60, it runs at 60fps

**Comment by humam2104** [comment]
do you set it to 60fps or 59.94 fps? which version of RPCS3 does it use?

**Comment by humam2104** [comment]
> Try framelimit Off and VSync On/Off.

I've already tried this, no luck.

**Comment by MSuih** [comment]
This is looking like a configuration issue or weak hardware instead of a bug. Head to our Discord's help channel instead.

**Comment by humam2104** [comment]
@MSuih Please read the following post:
https://github.com/RPCS3/rpcs3/issues/11840#issuecomment-1105477985

**Comment by nastys** [comment]
Setting that to 60 sets a double to 60., not 45.
https://github.com/RPCS3/rpcs3/blob/6783bcd273b5697e7a2283837891166abf8d96b7/rpcs3/Emu/RSX/RSXThread.cpp#L3178
The variable does this:
https://github.com/RPCS3/rpcs3/blob/6783bcd273b5697e7a2283837891166abf8d96b7/rpcs3/Emu/RSX/RSXThread.cpp#L3187

It could be a timing issue with your monitor's refresh rate, your OS (Windows doesn't have very good timer precision), that game specifically, or a combination of the three.

**Comment by MSuih** [comment]
Try the sample programs we have such as gs_gcm_basic_triangle or _cube. On windows those are in `dev_hdd0\game\TEST12345\USRDIR` directory in your main rpcs3 dir.
