### ISSUE TITLE
Anarchy Reigns close after Building SPU cache...

### ISSUE THREAD

**Issue by calvinvalerian** [RPCS3/rpcs3#11841]
https://youtu.be/_w32Dz1FGv0

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8530067/RPCS3.log)

**Comment by YuriNator557** [comment]
Log file missing, what you have posted is ripped from the GUI and does not contain all required information

**Comment by calvinvalerian** [comment]
Uploaded

**Comment by Tarek2013** [comment]
It also affects Little Big Planet 1,2 & 3 : emulator crashes during PPU compil, linking PPU or making SPU files
[RPCS3LBP1.log.gz](https://github.com/RPCS3/rpcs3/files/8542878/RPCS3LBP1.log.gz)
[RPCS3LBP2.log.gz](https://github.com/RPCS3/rpcs3/files/8542892/RPCS3LBP2.log.gz)
[RPCS3LBP3.log.gz](https://github.com/RPCS3/rpcs3/files/8542905/RPCS3LBP3.log.gz)

**Comment by MSuih** [comment]
LBP 1 and 2 work with #11850, so I assume it'll fix the other listed games as well. Ask for this to be reopened if the issues still persist.

**Comment by Megamouse** [comment]
The log doesn't have any reference to the offending function though

**Comment by MSuih** [comment]
Ah, I assumed this was about the recent regression. Anyways, the issue with Anarchy Reigns should be taken to #help channel in our Discord as we don't provide support in Github.
