### ISSUE TITLE
Unhandled exception when booting a game then opening Pad menu

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#11844]
## Quick summary

When opening the Pad menu after booting any game, it throws an Unhandled Exception error and the emulator crashes.

## Details

When opening the Pad menu, everything works.  However, if you boot any game and then try opening the Pad menu, an Unhandled Exception error box appears and the emulator crashes.

#### 1. Please attach RPCS3's log.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8535202/RPCS3.log)

#### 3. Please attach screenshots of your problem.

https://user-images.githubusercontent.com/58268914/164555421-aafdb47f-b895-4d36-81d3-9d201682d0a0.mp4

#### 5. Please provide your system configuration:
* OS: Windows 10 x64 Build 19043
* CPU: Intel Core i9-10900K
* GPU: NVIDIA RTX 2080 SUPER
* Driver version: 512.15

#### Please include.
* Anything else you deem to be important

The games themselves have no controller problems, it's only the Pad menu having this issue.  No other programs or emulators have any controller-related issues.  Downgrading to an older build before this issue started does not seem to fix it.

**Comment by Megamouse** [comment]
Thanks
