### ISSUE TITLE
Problem with compatible PS3 controller (SHANWAN PS3 CONTROLLER CECHZC2U)

### ISSUE THREAD

**Issue by justadevpassingby** [RPCS3/rpcs3#11848]
I found a problem with the configuration of the compatible ps3 controller Shanwan CECHZC2U,that happens only with RPCS3.Even if i correctly remap the controller, some buttons and analogs dont work as intended.At first i thinked about an hardware problem,tested on Linux Mint and Windows 10 with PCSX2 emulator and games on Steam,no problem at all and the analogs work as intended.When i switch to RPCS3 , only a few buttons works well....I think the main problem its the id of the controller its the same of PS3 original gamepad (0x054c , 0x0268 ) but the name of the analog axis are different: ABS_X , ABS_Y , ABS_Z , ABS_RX , ABS_RY,ABS_RZ this make the gamepad not responsive at all with analogs,only dpad work correctly and select - start.
![Error on config](https://user-images.githubusercontent.com/104204385/164710704-a105b54c-0f76-40c4-81e3-7fedb7f1bc32.png)

**Comment by Megamouse** [comment]
The Linux kernel has some special handling for Shanwan controllers that we never added because we didn't have anyone who could even test it

**Comment by Megamouse** [comment]
Someone-tm post the link to the positive axis thing please.

**Comment by justadevpassingby** [comment]
> The Linux kernel has some special handling for Shanwan controllers that we never added because we didn't have anyone who could even test it

If u need one tester,i could do it.i'm on Linux Mint (last release) and Windows 10. My PC its an Intel I7 3770 with Nvidia RTX 2060 and 16 GB Ram DDR3 (my main pc with Ryzen 5 2600x  and 32GB RAM DDR4 exploded like ,two days ago xD) still enjoy the emulator with some fine games,like Castlevania :)

**Comment by Megamouse** [comment]
Please try the positive axis thing first

**Comment by justadevpassingby** [comment]
Ok,i will search for that.Thanks :D

**Comment by Megamouse** [comment]
This was what I meant:

https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration#Analog_sticks_not_centered_with_evdev_pad_handler

**Comment by justadevpassingby** [comment]
> This was what I meant:
> 
> https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration#Analog_sticks_not_centered_with_evdev_pad_handler

Thank you very much,now the controlloer works fine!
