### ISSUE TITLE
Star Ocean 5 Integrity and Faithlessness black screen after Building SPU cache...

### ISSUE THREAD

**Issue by calvinvalerian** [RPCS3/rpcs3#11847]
https://youtu.be/EJ6Iol_CSqQ
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8539595/RPCS3.log)

**Comment by calvinvalerian** [comment]
Nevermind it is now working with the English patch

**Comment by calvinvalerian** [comment]
Once worked but returned the same error after applied the English patch

**Comment by AniLeo** [comment]
Issues with mods are not supported, either way it's likely affected by #6825
