### ISSUE TITLE
Infamous Fire Effects broken

### ISSUE THREAD

**Issue by kunit1** [RPCS3/rpcs3#11854]
## Quick summary
Fire and another effects either appear "pixelated" or give off an translucent effect that is incorrect. See screenshot below  

## Details

See Screenshot below

#### 1. Please attach RPCS3's log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8545952/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.
![Broken Effects Infamous](https://user-images.githubusercontent.com/22163077/164865845-ca4bf972-144b-4b86-a0f3-2c96fd87f10a.png)

#### 4. Please provide comparison with real PS3.
Will update issue once I capture footage from real PS3

#### 5. Please provide your system configuration:
* OS Win 11
* CPU intel Core i5 12600K
* GPU GTX 1080

**Comment by Darkhost1999** [comment]
This is a known issue. Mentioned
https://github.com/RPCS3/rpcs3/issues/11149

**Comment by kd-11** [comment]
It is the same issue, let's track it in that other ticket.

**Comment by Hichem47** [comment]
Hi they fix it ?

**Comment by MSuih** [comment]
The linked issue is still open so it is not fixed.

**Comment by Hichem47** [comment]
> The linked issue is still open so it is not fixed.

:(

ok thanks hope one day it will be fixed
