### ISSUE TITLE
Gran Turismo 6 freeze after intro movie

### ISSUE THREAD

**Issue by Devilke1233** [RPCS3/rpcs3#11853]
Right after starting up the game and skipping the intro cutscene/movie the game completely freezes.

I was reffered to make a report on the situation by some of the Discord server members and i can you tell the fact that in the conversations it was mentioned that the most probable cause of this could be the Vdec. I've also been told to mention that PR #11754 broke the game.

I'm currently using RPCS3 0.0.21-13478-8acb62f6Alpha | master (BAD)
The game worked as intended on build RPCS3 0.0.20-13284-abd8bd6f Alpha (GOOD)
Problem actually appeared just 2 or 3 days ago (today is apr/23/2022)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8544726/RPCS3.log) (GOOD LOG)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8544733/RPCS3.log) (BAD LOG)

![image](https://user-images.githubusercontent.com/104235896/164816210-0819ebce-1726-4460-b0df-3ed080035d7e.png) (Screenshot of the situation)

Sys config:
Windows 11 21H2
Intel Core i5-9600K | 6 Threads | 15.89 GiB RAM | TSC: 3.696GHz | AVX+ | FMA3 | TSX-FA disabled by default
GPU: NVIDIA GeForce GTX 1050 Ti (511.23)

**Comment by justadevpassingby** [comment]
GT 5 and 6 are currently unplayable,only GT5 Prologue its better,but still freeze after some minutes of gameplay.

**Comment by kd-11** [comment]
Tagging @Megamouse
