### ISSUE TITLE
Building SPU Cache BUG!

### ISSUE THREAD

**Issue by PariswIlfred** [RPCS3/rpcs3#11855]
Hello, I used RPCS3, Im facing a problem right here, im launching the game from RPCS3, When its building the SPU cache, it just keeps crashing! I did it again, i opened the app and launched the game, It just keeps crashing and increasing the number..
![Screenshot (266)](https://user-images.githubusercontent.com/104252753/164887751-8436b833-b90d-4791-8d3a-48f845dd0d8a.png)
Pls help me fix it!

**Comment by Washong** [comment]
@AniLeo @PariswIlfred @robxu9 @13xforever @xsacha @abbradar @octopoulos @B1ackDaemon @cjj19970505 @acmiyaguchi @isJuhn someone delete this issue.

**Comment by RainbowCookie32** [comment]
The issue is already closed and marked as invalid. Pinging a bunch of users (most of which can't even delete issues) is only annoying
