### ISSUE TITLE
Batman: Arkham City [NPUB30754]: Sudden severe audio pops

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#11871]
## Quick summary
Background audio effects (such as wind howling) suddenly play loudly, drowning out other sounds in the game such as dialog. Audio then remains in that state and further progress ingame is difficult without muting audio or dramatically reducing volume.

## Details
This only seems to occur after the main game is completed (after Joker dies).  I did not encounter the audio issue before that point in the game.

## Test Information:
* OS: Linux Mint 20.3 / kernel 5.13
* CPU: Intel i7-10870H
* GPU: Nvidia RTX 3070
* Driver version: 510.60
* Log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/8551165/RPCS3.log)
* Save game: [Batman_AC_Save.zip](https://github.com/RPCS3/rpcs3/files/8551176/Batman_AC_Save.zip)
 
## Additional Information:
Grand Theft Auto V is known to have this issue too - for example in [this](https://youtu.be/E9OyywPVmJc?t=72) video you can hear the audio sound right after the character says "get in there".

**Comment by git-tiger** [comment]
I have this too. Had to resort to using speakers, as the loud noise would deafen me.
Happens a lot when I reach high buildings, and the wind noise triggers.

**Comment by Xcedf** [comment]
The issue for GTA V was fixed, try to remove PPU Cache for your game and retest again

**Comment by Shoegzer** [comment]
Hey thanks @Xcedf.  I tested the game for a while and haven't experienced any more pops, though it happens so sporadically that I'm not sure.  Out of curiosity was there a specific commit that fixed this?  

@git-tiger if you can confirm it doesn't happen for you anymore either I'll close this, thanks.

**Comment by Xcedf** [comment]
@Shoegzer this one was the fix https://github.com/RPCS3/rpcs3/pull/11916

**Comment by git-tiger** [comment]
@Shoegzer thanks, the loud noise does not happen when I get to the top of the city now.
