### ISSUE TITLE
No More Heroes: Deseprate Struggle [BLUS30652] - Certain Textures have the wrong color

### ISSUE THREAD

**Issue by CptFoxer** [RPCS3/rpcs3#11879]
**## Quick summary**
Textures, but also lighting with colors that are shades of Yellow and Green have the wrong color: They are colored blue.

**## Details**

Textures have the wrong colour, textures that have a colour that is green or yellow will be colored blue, for textures used in foliage some of it is not affected, such as bushes, however trees have blue color bleeding, grass is completely colored blue. Yellow and shades of it (the same with Green) are also colored blue, textures with a yellow color can either be partially colored blue (see webm), or fully colored blue.

Issue is present with Vulkan & OpenGL Renderers on Windows 10. I do not have additional drive space to dualboot Linux, instead I used a LiveUSB and installed RPCS3 on the LiveUSB: Graphical issue is present in Vulkan renderer on Linux, but does not appear to be on the OpenGL Renderer (RPCS3 crashes because it's running on a LiveUSB for the test, I cannot test the issue further on Linux due to inability to dualboot) This makes me think that it's potentially a driver related issue. Someone with a Linux install and a copy of the game will need to do further testing.

**#### 1. Please attach RPCS3's log.**
 Log from the beginning of the game up to the final room before the first boss:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8565667/RPCS3.log.gz)
Additional Log during the freeroam section of the game:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8565737/RPCS3.log.gz)

**#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.**
First RSX Capture within the motel:
[BLUS30652_20220426205116_capture.zip](https://github.com/RPCS3/rpcs3/files/8565770/BLUS30652_20220426205116_capture.zip)
Additional RSX Capture outside the motel, near grass, grass sprite, and trees (Github would not upload it):
https://www.dropbox.com/s/gont3op7v0zzm7z/BLUS30652_20220426205429_capture.7z?dl=0

#### 3. Please attach screenshots of your problem.
![BLUS30652_screenshot_2022_04_26_20_22_24](https://user-images.githubusercontent.com/104455743/165364978-173e134e-788f-4ce5-934f-3d89bc4a78aa.jpg)
![BLUS30652_screenshot_2022_04_26_20_51_53](https://user-images.githubusercontent.com/104455743/165364990-f106034a-d5d6-4b79-a630-3df8d9453479.jpg)
![BLUS30652_screenshot_2022_04_26_20_53_29](https://user-images.githubusercontent.com/104455743/165365013-5b350242-e1c3-494d-a3ce-50179bd1775c.jpg)
https://user-images.githubusercontent.com/104455743/165365395-99da57ce-fd91-429e-b73d-80f6c4e36bba.mp4

**#### 5. Please provide your system configuration:**
OS: Windows 10
CPU: Ryzen 1500X
GPU: AMD Radeon 5700XT
Driver version: 22.3.1

**Comment by Triticum0** [comment]
Is this still an issue never encountered when testing the game a few days ago on Linux might be AMD specific.
![image](https://user-images.githubusercontent.com/71127352/214977535-c5ef48cc-7d3e-4f4b-845b-2def0c04ecd5.png)

**Comment by CptFoxer** [comment]
> Is this still an issue never encountered when testing the game a few days ago on Linux might be AMD specific. ![image](https://user-images.githubusercontent.com/71127352/214977535-c5ef48cc-7d3e-4f4b-845b-2def0c04ecd5.png)
I've noticed that the issue on Windows (With Vulkan Render Backend) disappeared around the time AMD updated their drivers around 6 months or so, I think the Driver version went by "22.7.1" 

I had my suspicions at the time that it was an issue with the Windows drivers, but I couldn't test the game on Linux because I don't have enough space to dualboot.

Screenshots from today running on the default RPCS3 config:

![BLUS30652_screenshot_2023_02_01_19_12_31](https://user-images.githubusercontent.com/104455743/216117371-d73a012d-e7e2-46f6-952f-e1697061bb9a.png)
![BLUS30652_screenshot_2023_02_01_19_22_56](https://user-images.githubusercontent.com/104455743/216117400-491bbd6d-9c20-4dab-bfea-f8fda2b2cd60.png)
![BLUS30652_screenshot_2022_07_30_17_44_45](https://user-images.githubusercontent.com/104455743/216120937-75ea1904-0722-43c2-997d-0eb6920cc870.png)

**System Information:**
OS: Windows 10 22H2
CPU: Ryzen 5600X
GPU: AMD Radeon 5700XT
Driver version: 22.11.2
**RPCS3 Log:**
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10559872/RPCS3.log.gz)
**RSX Capture:**
[BLUS30652_20230201194226_capture.zip](https://github.com/RPCS3/rpcs3/files/10559951/BLUS30652_20230201194226_capture.zip)

**Comment by Triticum0** [comment]
Can This be closed then?

**Comment by Triticum0** [comment]
Can This be closed then?
