### ISSUE TITLE
Just Cause 2 Video Capture - TODO cellRec and cellVideoExport

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#11874]
## Quick summary

Just Cause 2 can record your gameplay and export it to a video file, but cellVideoExport isn't implemented yet.

## Details

The game's pause menu has a Video Capture function which can record your gameplay then either upload it to YouTube or save it to the same place that the XMB saves videos.  However, it uses cellVideoExport which is marked as TODO in the log, meaning it isn't implemented yet.

#### 1. Please attach RPCS3's log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8558139/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.

![Capture](https://user-images.githubusercontent.com/58268914/165178109-289da945-543a-4fd3-9f60-8e37e022941c.PNG)

#### 4. Please provide comparison with real PS3.

Real console exports the recorded gameplay to a video file and places it in the same location as other video files.

#### 5. Please provide your system configuration:
* OS:  Windows 10 Pro x64 Build 19043
* CPU:  Intel Core i9-10900K
* GPU:  NVIDIA RTX 2080 SUPER
* Driver version:  512.15

#### Please include.
* Anything else you deem to be important

I was told to put this under Bug Report and not under Feature Suggestion.

**Comment by Megamouse** [comment]
Where do the exported movies end up on a real PS3 ?

**Comment by Darkhost1999** [comment]
Should be dev_hdd0/VIDEO

**Comment by marcoluc97** [comment]
U sure? From the logs seems HDD1 but I'm not an expert so don't mind me if I say something improper

**Comment by Megamouse** [comment]
the game records mp4 to cache (HDD1) and then exports it to the disk (HDD0)

**Comment by SlyCooperReloadCoded** [comment]
Just tried this out, when selecting Video Capture, instant crash with two fatal errors:

F {PPU[0x1000000] Thread (main_thread) [HLE:0x01b2438c, LR:0x00d0cfc4]} PPU: Function aborted: cellRecQueryMemSize
F {PPU[0x1000000] Thread (main_thread) [HLE:0x01b2438c, LR:0x00d0cfc4]} VM: Access violation reading location 0xc (unmapped memory)

It's a start!

**Comment by Megamouse** [comment]
It shouldn't crash anymore (but still not actually record)

**Comment by SlyCooperReloadCoded** [comment]
Can confirm, it also doesn't try to start the recording process anymore.

**Comment by SlyCooperReloadCoded** [comment]
Very interesting, it does!  However, drops the framerate down to 30 FPS (60 FPS patch installed) and only records in 480p.  It's clear the native recording function is starting to work but I've seen native catpures uploaded to YouTube that are 720p.  I don't see a resolution option though, so maybe it's looking for the console's max resolution, like how vsh needs to be switched to HDMI but this isn't doing that?  Cool to see it beginning to work, but it's far from done, and I wonder if the 60 FPS patch could be updated for this case too.

**Comment by Megamouse** [comment]
CellRec Recording only does 30fps, so the game probably lowers the frame rate to match the allowed speed somehow.

**Comment by SlyCooperReloadCoded** [comment]
Why the low resolution?  Is it possible to override either of these things?  Might need game patches, but things might change once audio works.

**Comment by Megamouse** [comment]
I wonder how you expect audio to change the resolution... 🤔 
The resolution is set by the game indirectly by selecting the quality.

If you want better resolution, you can just record with F11. (and change the recording.yml if you want)

**Comment by Megamouse** [comment]
This should have been closed by the linked PR.
