### ISSUE TITLE
[Feature Request] Improved Accessibility :)

### ISSUE THREAD

**Issue by TeamPuzel** [RPCS3/rpcs3#11886]
## Quick summary
<img width="683" alt="ac" src="https://user-images.githubusercontent.com/94306330/165526058-6d0ec50e-29b6-44c6-9800-874e87310058.png">

## Details

While I have no issues using RPCS3 in it's current state, I do have years of experience using emulators, and I remember that learning PCSX2 back in the day was not an easy task. Understanding how to configure the emulator takes technical knowledge that younger or less technically savvy people who simply want a way to play their PS3 games won't have.

Things like keyboard shortcuts/gestures are not implemented consistently either.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* UI
* Installation
* Accessibility

#### 2. Please tell us, why your feature is important to RPCS3.

Average users I showed RPCS3 to couldn't figure out how to even install and run a game

#### 3. Please attach screenshots of the feature implemented in other projects.
Here's some Sketch wireframes instead :)

![Welcome](https://user-images.githubusercontent.com/94306330/165527585-ef7dca87-1be6-49b9-a2bc-2cc105a11047.png)
![Main View](https://user-images.githubusercontent.com/94306330/165527601-517074ff-4ae3-4db1-9a83-39182ad1050e.png)
![Settings](https://user-images.githubusercontent.com/94306330/165527624-b0f46585-17ac-48cf-ba7b-cf3a648843b5.png)

#### 4. Please provide your system configuration:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/94306330/165521214-587290f3-5993-40b2-af70-c20a13c297b7.png">

**Comment by Asinin3** [comment]
I like how it looks, but this is actually a major downgrade to usability for people who have used the emulator before. I also don't see how changing the UI will make it any easier to install or run a game when it's always been as simple as it gets (put disc games in disc game folder) Or, drag and drop any disc games or pkg's onto rpcs3 and it will install them.

Simplifying everything in the UI might be less intimidating, but makes everything more convoluted to use when all the settings you need to access are hidden behind advanced toggles or even more tabs. Frankly, dumping games legally requires some computer knowledge and if the RPCS3 application is going to be designed in a way that a grandma can use it... they still need to dump their games. The mockup only has room for two options on the graphics tab, this is honestly a downgrade.

As far as usability improvements go, there is many other tasks that can be done that don't involve completely changing the interface which many hours were spent making. For instance having game settings downloaded from our wiki so users have all their games configured properly without doing anything.

**Comment by Darkhost1999** [comment]
I agree that I like the ideas.
* Add a link to a video tutorial on how to install PS3HEN on your PS3 and transfer the files to your PC.
-This is possible to do. Improving the wiki and the many different guides is an ongoing WIP.

* Automatically configure settings from the wiki to your Games
-This has been and is an ongoing discussion.

* Add to grid and list view a new modern grid view.
- Contributions are welcome

But the things like advanced mode to access additional settings will create unnecessary confusion.

It looks like to me these sketches were only made to communicate the thoughts and ideas in a visual way.

**Comment by TeamPuzel** [comment]
the issue is that the majority of settings are best left untouched, the resolution setting even says not to use it when hovering over it and says to use scaling instead. there's only a few settings that require changing often, and it's confusing for people who are not used to more advanced emulators like pcsx2 or rpcs3.

Yes the sketches are to visualise what I mean, rewriting everything for each platform would probably take too much time. I just know how to make macOS wireframes so I made that :D

I just think the advanced options should be automatically set per game based on a database and/or moved to a separate menu. It gives the impression of complexity, new users have no way of knowing which settings actually matter. not everyone can learn 80 different settings for every app they use.


on the other hand it wouldn't be that difficult. I don't know if you're developing for mac but ui like that is generally a few lines of code since it's relying on built in frameworks.


There's also platform specific inconsistencies, for example on macOS "command + ,"  is a keyboard shortcut to open settings, and RPCS3 does not recognise that. (other emulators such as Dolphin do)

**Comment by TeamPuzel** [comment]
> I also don't see how changing the UI will make it any easier to install or run a game when it's always been as simple as it gets (put disc games in disc game folder) Or, drag and drop any disc games or pkg's onto rpcs3 and it will install them.
> 
You have to know that first, adding a friendly welcome message that visually explains to you how to get the games off the ps3 is generally better than leaving the user to look it up on YouTube, potentially to find an outdated or malicious guide


> Simplifying everything in the UI might be less intimidating, but makes everything more convoluted to use when all the settings you need to access are hidden behind advanced toggles or even more tabs. Frankly, dumping games legally requires some computer knowledge and if the RPCS3 application is going to be designed in a way that a grandma can use it... they still need to dump their games. The mockup only has room for two options on the graphics tab, this is honestly a downgrade.
> 
I did a bit too much yes haha, too many buttons, it would be better like this:
![Main View Copy](https://user-images.githubusercontent.com/94306330/165552904-495c010e-f3cf-4a28-8068-4c24b65137bd.png)
the settings thing is unnecessary true

I am not asking anyone to waste time rewriting the UI, I could do it for macOS myself, just wanted to add the suggestion here first :)

**Comment by Megamouse** [comment]
As a feature request this fails to convey a solid message.
All i see here are random thoughts that are already discussed in several other tickets.
And I don't see how the ui presented provides any improvement over the current one.
There should be simple and clear suggestions.
Currently this looks more like a brainstorming

**Comment by TeamPuzel** [comment]
> As a feature request this fails to convey a solid message.

The app just looks out of place on macOS because the UI made with cross platform frameworks. It does not support accessibility features, keyboard shortcuts and has visual bugs. I would love to write a native UI using the latest SwiftUI framework, properly integrating all of the above, as well as toolbars, better multiple window support, a welcome screen, tooltips, drag and drop and probably some other cool stuff, making the app easier to use for both beginners and advanced users.

but I am unfamiliar with the way RPCS3 is written, I don't know how easy it would be to have a seamless integration between the emulator and SwiftUI, and because I wouldn't want to waste time I wanted to ask here if it's possible. 🙂

**Comment by AniLeo** [comment]
We obviously aren't going to have two different UIs on two different frameworks, same thing as not wanting the tech debt from a native render for a single-OS API like Metal when we already have cross-platform standard APIs

> keyboard shortcuts and has visual bugs

You don't need to change the entire framework to fix visual bugs or to add keyboard shortcuts for either of the OSes we already support

> as well as toolbars, better multiple window support, a welcome screen, tooltips, drag and drop

Same as above for most if not all of those

**Comment by TeamPuzel** [comment]
It's not even close to supporting multiple graphics APIs, SwiftUI is only a few lines of code, could be done in a day by someone experienced with it.

I'm not asking for anyone to spend their time on supporting that, I literally just said It's a fun and interesting challenge, and I'd like to create UI that looks and works like a Mac app, fully respecting the human interface guidelines of macOS. Doesn't have to be part of the official build, and you're all upset for whatever reason, as if I asked _you_ to do anything 🙂

ugh

and some things with using cross platform frameworks are difficult to fix, the preferences pane takes a few seconds to load for example.

I am a bit bored right now and I'd like to work on something for an open source project :(

**Comment by TeamPuzel** [comment]
I think it wouldn't be that difficult considering that it is possible to call C functions from Swift. it wouldn't require changes in RPCS3, it would just be built on top of existing code as an alternative faster interface for macOS

**Comment by kd-11** [comment]
Rpcs3 supports running in cli mode. You're free to implement any custom frontend you like of course, you do not have to use the one we ship.

**Comment by TeamPuzel** [comment]
> Rpcs3 supports running in cli mode. You're free to implement any custom frontend you like of course, you do not have to use the one we ship.

Thank you! that's even easier :)

**Comment by TeamPuzel** [comment]
I started working on the SwiftUI code, I don't have experience writing Swift apps that work in this way so it might take some time, but it's definitely going to be a fun project

**Comment by Yahfz** [comment]
>and you're all upset for whatever reason, as if I asked _you_ to do anything 🙂

Don't worry about them, lol. It just seems like that because dealt with the people that usually hate everything XD.  I don't have a mac machine but for what its worth I'd like to see how it turns out in the end, I think it looks nice but based on the initial design you showed it seems like you'll face issues soon.
