### ISSUE TITLE
[Regression] Resuming from paused state now freeze game

### ISSUE THREAD

**Issue by illusion0001** [RPCS3/rpcs3#11884]
Reuming from debugger or main pause button causes game to not resume properly.
The bot didn't build between the two PRs so can't test.
Reproduce steps:
- Boot game
- Pause game using one of the two pause buttons
- Resume and it won't do it properly

Last working build #11858:
[13479-2RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8567672/13479-2RPCS3.log.gz)
Broken build #11865:
[13487RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8567673/13487RPCS3.log.gz)

**Comment by RipleyTom** [comment]
Tested pausing/resuming on a few games on linux, could not reproduce.

**Comment by Megamouse** [comment]
can't reproduce either

**Comment by illusion0001** [comment]
I actually don't know what build started causing this, but it started going nuts recently, the offending builds are probably not the cause I can't tell for sure because it's a rare bug😩

**Comment by Megamouse** [comment]
I thought it was 100% reproducible on your end.
How is it rare then?

**Comment by illusion0001** [comment]
By rare I mean I'm the only one who can reproduce the bug, others can't.

**Comment by illusion0001** [comment]
I should probably get a video of it happening to make sure I'm not going insane

**Comment by illusion0001** [comment]
Can't reproduce now for whatever reason, now resuming works every time
