### ISSUE TITLE
USB whitelist request: "Power Gig: Rise of the Six String" guitar and drum peripherals

### ISSUE THREAD

**Issue by aWiseMoose** [RPCS3/rpcs3#11896]
I'm wondering if the Power Gig peripherals could get added to the USB whitelist. Power Gig is a Guitar Hero / Rock Band ripoff game with a few unique features and game modes that require their own first-party controllers instead of GH/RB controllers. There are also a handful of trophies that are locked behind the requirement of using these specific controllers.

Here are the hardware ID's

Power Gig Six String guitar controller:
HID\VID_12BA&PID_0200&REV_0200
HID\VID_12BA&PID_0200

Power Gig Airstrike drum controller:
HID\VID_12BA&PID_0210&REV_0200
HID\VID_12BA&PID_0210

**Comment by RipleyTom** [comment]
Please upload a log of the game(up to the point where the device is detected, probably the main menu).

**Comment by aWiseMoose** [comment]
Here's the log. To get to the screen that detects which instrument you're using, you first have to press start on the title screen. I had an Xbox 360 Rock Band guitar plugged in to do the menu navigating, if that matters. I also had the dongle of the Power Gig guitar plugged in.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8595513/RPCS3.log)

**Comment by RipleyTom** [comment]
Sorry I should have noticed before but both those devices are already whitelisted, they're just in the Harmonix range:
```
		check_device(0x12BA, 0x0200, 0x020F, "Harmonix Guitar");
		check_device(0x12BA, 0x0210, 0x021F, "Harmonix Drums");
```
Those are ranges, >= 0x200 and <= 0x20F for the Guitar and >= 0x210 and <= 0x21F for the Drums.

It may not be detected as a PowerGig one because of a bug that may be fixed by https://github.com/RPCS3/rpcs3/pull/11900 (waiting for people to test).

**Comment by RipleyTom** [comment]
Please test with latest master, a fix was made and the game may recognize the devices to be custom now.

**Comment by aWiseMoose** [comment]
Just tested both the guitar and drum controllers and can confirm they are properly recognized by the game and work perfectly! Thanks so much!
