### ISSUE TITLE
Wave effect cannot render correctly in PixelJunk Monsters and causing severely frame drop

### ISSUE THREAD

**Issue by justinlin099** [RPCS3/rpcs3#11899]
## Quick summary
When the cannon touches the ground and render wave effect, the game framerate will drop down to 1.xx fps

## Details

When the cannon touches the ground and render wave effect, the game framerate will drop down to 1.xx fps
And in the map selection screen, the frame rate will drop to 5 fps , and I think there is something wrong with it.

I have tried several version (from latest to the 0.0.5-7738 from 2019) and all of them have the same problem.(frame drop when cannon explode)

btw, I think there is something wrong with the new version openGL(vulcan works fine), in the old 2019 version, the frame rate is normal,but in the latest version, I can barely get 0.5 fps in the map selection screen.

#### 1. Please attach RPCS3's log.
the log of old version : [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8590103/RPCS3.log.gz)
the log of latest version: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8590111/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8590241/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.

map selection screen low framerate capture:[NPUA80108_20220429185125_capture.zip](https://github.com/RPCS3/rpcs3/files/8590225/NPUA80108_20220429185125_capture.zip)

wave effect frame drop capture:[NPUA80108_20220429185536_capture.zip](https://github.com/RPCS3/rpcs3/files/8590237/NPUA80108_20220429185536_capture.zip)

#### 3. Please attach screenshots of your problem.

![image](https://user-images.githubusercontent.com/61717681/165930272-d68c78b4-fbc4-477b-9e56-9c8ef83808bf.png)
low frame rate when in map selection screen(vulcan)

![image](https://user-images.githubusercontent.com/61717681/165930450-dd00594d-6ab3-4230-961c-e68be494f582.png)
normal game framerate

![image](https://user-images.githubusercontent.com/61717681/165930483-8e448231-fff2-4ce3-b23a-6f8a8ccdbb05.png)

![image](https://user-images.githubusercontent.com/61717681/165930519-77d20f0d-5cb3-48b7-81bb-49410293da6d.png)
wave effect frame drop

#### 4. Please provide comparison with real PS3.

My ps3 is dead so...

#### 5. Please provide your system configuration:
* OS :Windows 10 & Windows 11
* CPU : Ryzen 7 5700G &Ryzen 3 3100
* GPU : RTX 2080 Super & GTX780
* Driver version : 496.13
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by Asinin3** [comment]
Yeah as I tested/confirmed on discord. Issue is with game version 02.05. If you use base game version 01.00 performance is muuuch better. I'll close this off, devs can re-open if they deem fit.

**Comment by Laynee** [comment]
v2.0: problem still happening
v1.0: won't launch with default settings. SPU Decoder > Interpreter (static) makes the game playable but sound is sometimes distorded

Latest RPCS3 (Version: 0.0.41-19559-d87cf99b)
