### ISSUE TITLE
Multiplayer service collaboration (Aixen)

### ISSUE THREAD

**Issue by haneefmubarak** [RPCS3/rpcs3#119]
Someone mentioned over in haneefmubarak/aixen#10 that it would be nice for Aixen to support RPCS3.

Aixen aims to provide a networking service similar to LIVE/Steam, for Xenia and also new games developed in the future. Integration into future games and projects like Xenia will be done via the use of a C library.

However, to support projects such as Xenia, and in this case, RPCS3, certain changes must be made on the Aixen side of things, since both emulate specific functionalities and are also able to play a variety of games.

 So I wanted to ask if you guys would be interested in working with us to have Aixen support RPCS3. All that you would need to do is provide someone who is somewhat familiar with PSN who is available to do related work on Aixen and give a username for whomever is most familiar with this project; the former would actively work on Aixen while the latter would only need to answer the occasional question about RPCS3.

So would you guys be interested in working with us so RPCS3 could have something similar to PSN, just like Xenia will have something similar to XBL?

**Comment by twdarkeh** [comment]
@AniLeo Since you appear to be cleaning issues, this hasn't been updated in nearly a year and a half, and the project has been dead since April 2014. Could it be closed?
