### ISSUE TITLE
[BLES00995] WWE All Stars v. 01.00: Unknown surface antialiasing format

### ISSUE THREAD

**Issue by 15lollo15** [RPCS3/rpcs3#11905]
The emulator stops working during "PPU compilation" giving the error:
`·F 0:15:40.660246 {RSX [0x007dd6c]} SIG: Thread terminated due to fatal error: Unknown surface antialiasing format 0xa
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\gcm_enums.cpp:905[:22], in function to_surface_antialiasing)`
If it finishes this process it stops after few seconds giving the same error.

Computer specs:
CPU: AMD A8-7670K Radeon R7
GPU: Nvidia 1050 Ti
OS: Windows 10 x64 21H2

Log file:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/8597418/RPCS3.zip)

**Comment by AniLeo** [comment]
Insanely old GPU driver, needs to be retested on latest driver

**Comment by 15lollo15** [comment]
I updated the drivers to the latest version(512.59) but the error still present.

Log:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/8597468/RPCS3.zip)

**Comment by kd-11** [comment]
This is a desync event due to the CPU not being responsive enough. Increase the driver wakeup delay in the advanced tab to 200 and see if it helps.

**Comment by 15lollo15** [comment]
Thanks you, it worked

**Comment by Megamouse** [comment]
I guess this can be closed

**Comment by Sol1vaN** [comment]
> This is a desync event due to the CPU not being responsive enough. Increase the driver wakeup delay in the advanced tab to 200 and see if it helps.

it helps me for the same error with wipeout hd fury, thanks too much!
