### ISSUE TITLE
[Trace inside] Crash when going ingame in Demon's Souls (BLUS30443)

### ISSUE THREAD

**Issue by FinishedFragment** [RPCS3/rpcs3#11901]
## Quick summary

The entire emulator freezes and then crashes when going ingame (loading a save). Dark Souls Prepare to Die edition is also affected. Dark Souls II is not.
It may or may not be related to it compiling shaders because it crashes just as it is compiling those. I already cleared `~/.cache/rpcs3`.

## Details

Unfortunately gdb crashed after paging the output of `thread apply all bt full` but I hope the trace still works.

[gdb.txt](https://github.com/RPCS3/rpcs3/files/8592669/gdb.txt)

I just built RPCS3 from master (as of writing, 8316469cfcfb076d5a9772557b0de522f39616d2), but that regression happened earlier and only now I got around debugging it. I still have to make out the exact commit which broke it. Sorry.

#### 0. Make sure you're running with settings as close to default as possible

n/a

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.

Not sure yet.

#### 2. Please attach TWO logs:

* One for the build with regression: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8592681/RPCS3.log)
* One for the build that works as expected: not available yet.

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.

n/a

#### 4. Please attach screenshots of your problem.

n/a

#### 5. Please provide comparison with real PS3.

n/a

#### 6. Please provide your system configuration:

* OS: Arch Linux
* CPU: amd ryzen 1600af
* GPU: amd rx 570 OC version

#### Please include.
* Anything else you deem to be important

**Comment by FinishedFragment** [comment]
I am having trouble bisecting because of the submodules. I assume a change in one of them makes it impossible for me to build older versions of rpcs3 (if I just git checkout any older commit). Any tips?

**Comment by kd-11** [comment]
Download appimages from rpcs3.net. We have a historical archive with old builds. Use that to bisect to the PR that caused the bug.

**Comment by AniLeo** [comment]
Missing bisect to find the affected build if this is still even an issue

**Comment by FinishedFragment** [comment]
Still an issue, unable to bisect. For whatever reason I am unable to reproduce on the appimage, while my own build still crashes. I can not build older versions on my own due to the submodule hell.

One other thing I have noticed while reaffirming the issue still exists is the following output when it freezes:

```
/usr/include/c++/12.2.0/array:208: constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) [with _Tp = vk::command_buffer_chunk; long unsigned int _Nm = 512; reference = vk::command_buffer_chunk&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

**Comment by kd-11** [comment]
Probably a compiler bug. Try switching between gcc and clang depending on the one you're using.

**Comment by NetSysFire** [comment]
I have the same issue and tried compiling it in Clang but can not because of https://github.com/llvm/llvm-project/issues/58207

**Comment by Megamouse** [comment]
Since this doesn't happen on the appimage I really see no reason to keep this ticket open
