### ISSUE TITLE
Persona 5 - Audio does not work

### ISSUE THREAD

**Issue by nuclearflame11** [RPCS3/rpcs3#11908]
## Quick summary
There is simply no audio. I have checked the Windows 10 volume mixer, but to no avail. I disabled Persona 5 patches and received the same result.

#### RPCS3 Log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8598466/RPCS3.log.gz)

#### System Configuration:
* OS: Windows 10 Home 10.0.19044 Build 19044
* CPU: Ryzen 5 5600H, 3.3mhz, 6 Cores and12 Logical Processors
* GPU: NVIDIA RTX 3050
* NVIDIA Driver version: 512.15

#### Additional Information: 
* This happened about a month ago but I procrastinated on reporting it haha
* There is no audio, even in the cinematic intro (when it plays Wake Up, Get Up, Get Out There)
* Here is a screenshot of my audio and advanced settings if it would help (Note that not a single checkbox is checked under "Firmware Libraries" despite the screenshot showing little):
![image](https://user-images.githubusercontent.com/46734887/166137038-97336045-f42f-4480-96b6-774e14799bfb.png)
![image](https://user-images.githubusercontent.com/46734887/166137063-f7723888-5f17-4685-88df-f7de915bbcdb.png)

**Comment by illusion0001** [comment]
Audio is set to 0%

**Comment by MSuih** [comment]
Yes, you have a game-specific config which has audio at 0%. Fix that and audio should work.

**Comment by nuclearflame11** [comment]
sorry for the waste of time i didn't know this
