### ISSUE TITLE
[Feature Request] (Sub)Domain / Substring wildcard matching for IP/Host Switches

### ISSUE THREAD

**Issue by I-Knight-I** [RPCS3/rpcs3#11911]
## Quick summary
PlayStation Network (like many others) uses a lot of different domains that are otherwise very similar except for a minor difference. It'd be useful to be able to redirect these with a wildcard (*)

## Details
An example might be:

- `scea.playstation.net`
- `scee.playstation.net`
- `scej.playstation.net`

Which would be written as: `scea.playstation.net=0.0.0.0&&scee.playstation.net=0.0.0.0&&scej.playstation.net=0.0.0.0`

It'd be useful to be able to redirect each of these with a wildcard rather than having to swap each one. So those three switches will simply become: `*.playstation.net=0.0.0.0` -- which is much simpler and cleaner.

Whilst that covers subdomains, it'd also be useful to have - if possible - string-matching wildcards. For example, you might want to redirect every domain with any substring at a certain point but _not_ all subdomains:

- `test-one.playstation.net` <---- We **want** to reroute this
- `test-two.playstation.net` <---- We **want** to reroute this
- `scea.playstation.net` <---- We do **NOT** want to reroute this

So a valid wildcard for this could be:

- `test-*.playstation.net` 

Whereas a subdomain wildcard (`*.playstation.net`) would switch all three; including the one we don't want to reroute.
In the case of substring wildcards, subdomains are implicitly covered.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Networking

#### 2. Please tell us, why your feature is important to RPCS3.
- Ease of use
- Simpler than current implementation
- Cleaner than current implementation
- Should be relatively simple to implement

#### 3. Please attach screenshots of the feature implemented in other projects.
Wildcard matching is a very popular and accepted tool across the entire tech industry:
https://www.geeksforgeeks.org/wildcard-pattern-matching/ 

Don't think I need to attach an image of text 😉

**Comment by RipleyTom** [comment]
Implemented with https://github.com/RPCS3/rpcs3/pull/11934
