### ISSUE TITLE
[Feature Request] Apple Silicon native build

### ISSUE THREAD

**Issue by ptuchik** [RPCS3/rpcs3#11913]
Hi guys,

Are you going to make a native Apple Silicon build as well? I think it will increase the performance on M1 Macbooks

Regards,

**Comment by YuriNator557** [comment]
ARM support has some limited functionality on PPU interpreter already

**Comment by Asinin3** [comment]
M1 is always going to be pretty slow compared to other operating systems. Even if we were going to port RPCS3 to Metal (to avoid MoltenVK) there are limitations there for RPCS3 that would mean the performance gain compared to MoltenVK isn't even going to be that impressive.

More native support might come, but I don't see any need to have useless/discussion issues like this open as it isn't requesting anything that the devs aren't already aware of and our issue tracker is bloated enough as is.
