### ISSUE TITLE
Infamous 2: Continue your infamous 1 story

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11914]
* After unlocking all infamous 1 trophies and starting a new infamous 2 game I see
![image](https://user-images.githubusercontent.com/60384196/166291266-fa181d56-6bda-4bb7-a59a-93801029e7a0.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8604819/RPCS3.log.gz)
* What I'm supposed to see
![279370481_1057867094824095_3317533092166467737_n](https://user-images.githubusercontent.com/60384196/166291655-b54ca738-a883-4148-a293-0ce9011533ff.png)
followed by
![279372770_1138527386945401_615180759297489776_n](https://user-images.githubusercontent.com/60384196/166291692-5bd60eaf-e3d4-4473-8067-2835cf18ea6e.png)
These are not great bonuses but still is an RPCS3 issue.

Note: Save data is not required at all to unlock continue your story
Here is the infamous 1 trophy data for testing:
[NPWR00660_00.zip](https://github.com/RPCS3/rpcs3/files/8604837/NPWR00660_00.zip)

**Comment by Megamouse** [comment]
@Darkhost1999 can you try the mentioned PR ?

**Comment by Darkhost1999** [comment]
Sure thing.
![image](https://user-images.githubusercontent.com/60384196/166950176-8ca914bc-0761-4039-b377-0ebafd0bf48a.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8632227/RPCS3.log)

**Comment by Megamouse** [comment]
@Darkhost1999  Can you try the PR again?

**Comment by Darkhost1999** [comment]
Yea. Here is 8e402388
![image](https://user-images.githubusercontent.com/60384196/166984901-8af85c63-a60c-463b-ba10-a7258d4d0536.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8633561/RPCS3.log)

**Comment by Megamouse** [comment]
oops, I had a typo in there.
You'll need to wait until the next build is ready

**Comment by Darkhost1999** [comment]
If you mean wait for https://github.com/RPCS3/rpcs3/pull/11935/commits/d35fa6e0ccd583d849ad6a0ee1e46331eaa48c5b then it abruptly closes the emulator and the game after building spu cache screen.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8633739/RPCS3.log)
If you mean keep waiting. Then ignore this message.

**Comment by Megamouse** [comment]
yeah sorry. it was another typo.
Please wait until the next build.

**Comment by Megamouse** [comment]
@Darkhost1999 you can try again please

**Comment by Darkhost1999** [comment]
I'm mobile now. But fixed.
![Screenshot_20220505-140842_Messenger.png](https://user-images.githubusercontent.com/60384196/167006797-4293307a-9236-4699-b69a-cc743b0439c4.png)
![Screenshot_20220505-140525.png](https://user-images.githubusercontent.com/60384196/167006810-6f751be3-258c-4e24-93fb-3b118443e0e8.png)

**Comment by Megamouse** [comment]
Interesting. Thx
