### ISSUE TITLE
[Feature Request] Native Apple Silicon

### ISSUE THREAD

**Issue by iMonZ** [RPCS3/rpcs3#11922]
We already got this issue here: https://github.com/RPCS3/rpcs3/issues/11913

Unfortunately there was an misunderstanding

No one wanted a Native metal version.

MoltenVK is doing perfectly fine.
What is missing is a native ARM version instead of x86 to avoid using and installing the x86 emulator.

**Comment by AniLeo** [comment]
Duplicate of #715

**Comment by Asinin3** [comment]
Bold of you to assume i misunderstood just because i mentioned the metal api not happening as a side note

**Comment by Megamouse** [comment]
Duplicate and not helpful. Everyone knows what you are requesting.
