### ISSUE TITLE
Just Cause 2 no longer reaches the title screen

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#11921]
## Quick summary
Just Cause 2 no longer reaches the title screen.

## Details
Just Cause 2 no longer reaches the title screen, crashing with an unmapped memory error.  It's consistent, happening at the same time each time.  Emulator then deadlocks.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
v0.0.22-13542-f9a62667

#### 2. Please attach TWO logs:
Log from v0.0.22-13542-f9a62667:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8612978/RPCS3.log)

Log from v0.0.22-13539-0786a0a0:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8612980/RPCS3.log.gz)

#### 4. Please attach screenshots of your problem.
![Capture](https://user-images.githubusercontent.com/58268914/166523964-0a78bd4a-5998-498a-8d6b-b5afcafecf33.PNG)

#### 6. Please provide your system configuration:
* OS: Windows 10 Pro x64 Build 19043
* CPU: Intel Core i9-10900K
* GPU: NVIDIA RTX 2080 Super
* Driver version: 512.15

**Comment by elad335** [comment]
I need PathEngine.sprx.

**Comment by SlyCooperReloadCoded** [comment]
[PathEngine.zip](https://github.com/RPCS3/rpcs3/files/8617517/PathEngine.zip)

**Comment by elad335** [comment]
#11924

**Comment by SlyCooperReloadCoded** [comment]
Tested with that PR, game can get ingame again.
