### ISSUE TITLE
WipEout® HD Fury [BCES00664] Does not boot. 

### ISSUE THREAD

**Issue by fmaeseele** [RPCS3/rpcs3#11928]
## Quick summary
WipEout® HD Fury [BCES00664] Does not boot. 

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8626227/RPCS3.log.gz)

#### 5. Please provide your system configuration:
OS : Win 11 x64
CPU : intel core i7 12th Gen
GPU : Intel Iris Plus
RAM : 16GB

**Comment by Jonathan44062** [comment]
A lot of bad settings, I wonder why does not work...
![image](https://user-images.githubusercontent.com/78843189/166806323-dfa57628-d184-4c97-b5cd-22d6f359d3db.png)
Select Restore Default and boot the game with default settings
Ask for support in RPCS3 Discord

**Comment by YuriNator557** [comment]
This game is a repackaged ISO, RPCS3 does not support these

**Comment by fmaeseele** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8626376/RPCS3.log.gz)

Here is the new log with default configuration.

Regarding your comment on repackaged iso not supported by RPCS3, it used to work 1 or 2 years ago. Can't remember exactly. But since then, I constantly accept the upgrade and 'voila' :-)

Could you at least have a look at this issue as it seems that other issues of the same type has already been posted ?
Thank you

**Comment by AniLeo** [comment]
You need to be using a proper dump in order to ask for support, doesn't matter if it worked or not with a badly dumped game, closing as Invalid since the dump is not properly made

Furthermore, you're also using unsupported Intel drivers, which may or may not work
