### ISSUE TITLE
VSH regression: soft hang after Initial Setup

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#11930]
After completing the Initial Setup, VSH soft hangs with the loading indicator spinning seemingly indefinitely.

![image](https://user-images.githubusercontent.com/10439488/166848508-8e704a01-7a94-48f6-9b62-a820024db1b2.png)

Build is latest master (v0.0.22-13549-fcbeb2fa), this was on a Windows 8.1 Pro, firmware version 4.88.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8628204/RPCS3.log.gz)

Not sure when it regressed, nor am I going to go back and bisect. If that is not satisfactory, please close the ticket.

**Comment by Vestrel** [comment]
Broken since #11740
