### ISSUE TITLE
Game freezing/unresponsive after specific amount of time

### ISSUE THREAD

**Issue by Adam-Kay** [RPCS3/rpcs3#11937]
## Quick summary
After playing the game for a certain amount of time, it completely freezes up and I have to close it

## Details
I’m having some issues playing Ratchet & Clank: Quest for Booty through RPCS3, running with default configuration.
I'm having a weird bug where after pretty much a maximum of 3 minutes, the game will freeze and be completely unresponsive to any input.
I tried many times, and always it is the same bug for some reason.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues** ✅
* Only change settings that are required for the game to work ✅

#### 1. Please attach RPCS3's log.
Test 1: [rpcs3_logs_1.zip](https://github.com/RPCS3/rpcs3/files/8631003/rpcs3_logs_1.zip)
Test 2: [rpcs3_logs_2.zip](https://github.com/RPCS3/rpcs3/files/8631007/rpcs3_logs_2.zip)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
❌ Not a graphical issue

#### 3. Please attach screenshots of your problem.
❌ N/A

#### 4. Please provide comparison with real PS3.
❌ N/A

#### 5. Please provide your system configuration:
* OS: Windows 11 version 21H2 (Build `22000.613`)
* CPU: AMD Ryzen 9 3900X 12-Core
* GPU: NVIDIA GeForce RTX 2070
* Driver version: GPU: GeForce Game Ready Driver, version 512.15
* RPCS3 Version: `0.0.22-13551-4e40260f Alpha`

Any help would be appreciated.

**Comment by Darkhost1999** [comment]
There is an RPCS3 patch to workaround this issue listed in the canary patches section of the RPCS3 wiki.
https://wiki.rpcs3.net/index.php?title=Help:Game_Patches

It's interesting you bring up this error because a handful of us on the discord have been bragging that for over a month the freeze fix patch is unnecessary to play the game now and have been considering making a playable report for the game. When we saw activating a turbine drops to approximately 15-25fps on a Ryzen 5 3600 (gamespeed unaffected and during cutscene only) 
Where real PS3 doesn't go below 30.

**Comment by ZwipZwapZapony** [comment]
A friend of mine recently played Ratchet & Clank: Quest for Booty (NPEA00088), and had a lot of freezes for the first half of the game before I gave them the canary "freeze fix" patch (after which they still had a few, but not nearly as many; the freeze fix patch helped a lot).

Both with and without the patch, I (not my friend) consistently freeze shortly after the first "jump catapult" in the first level, too, when targeting and shooting at the next few enemies with the Predator Missiles weapon. I wouldn't call it "Playable" yet.
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/8632620/RPCS3.log.zip)

<details><summary>My system:</summary>

OS: Windows 10 version 21H1 (OS Build 19043.1645)
CPU: Intel Core i9-9900K (3.6GHz)
GPU: NVIDIA GeForce RTX 2080 Ti (driver v512.59, 11GB VRAM)
RPCS3 version: 0.0.22-13557-27064865</details>

**Comment by Adam-Kay** [comment]
> recently played Ratchet & Clank: Quest for Booty (NPEA00088)

That's strange, my serial registers as NPEA00106.
Either way, the [canary patch seems to](https://wiki.rpcs3.net/index.php?title=Help:Game_Patches/Canary#:~:text=Expand-,Ratchet%20%26%20Clank%20Future%3A%20Quest%20for%20Booty,-Collapse) only be for BCES00301.

Is that a problem or can I just replace the number in the patch and it'll work?

**Comment by RainbowCookie32** [comment]
> Is that a problem or can I just replace the number in the patch and it'll work?

Depends on the game. Some games have the same executable across different versions. But if the executable is different, you'll likely end up patching something different and either breaking stuff, or not changing anything.

**Comment by Darkhost1999** [comment]
That's probably why Juhn reacted smoothbrain to my comment earlier.
But I've changed that Serial to the PSN version before and it worked fine for users I have given it on discord. As rainbow says you can try but it isn't guaranteed.

Besides this issue remains valid even if the workaround is achieved because the patch should only be a temporary solution.

**Comment by Adam-Kay** [comment]
Thank you all! This is super helpful, and I'll see if the Canary patch makes the game more playable for me.

**Comment by ZwipZwapZapony** [comment]
Here's a log from the "verification failed" freeze/crash for me in Ratchet & Clank: Quest for Booty: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/8885487/RPCS3.log)

It's been discovered that this freeze can be worked around/avoided by changing `ensure` to `if` in this part of *rpcs3/Emu/RSX/Common/texture_cache.h*. That's probably not the "proper" fix, but is a good start for investigation. https://github.com/RPCS3/rpcs3/blob/f3fa7119ac04bb762084cea48b8932203626c607/rpcs3/Emu/RSX/Common/texture_cache.h#L3115-L3120

**Comment by kd-11** [comment]
Fixed a while ago by https://github.com/RPCS3/rpcs3/pull/14181

**Comment by mrTerryBogard** [comment]
Good day!

[15.6" Laptop Neobihier ZX-I7-10750H, Intel Core i7-10750H (2.6 GHz), RAM 16 GB, SSD 1024 GB Intel UHD Graphics 630, Windows 11 Pro, Russian keyboard]

Dead or Alive 5: Last Round with update 1.04 + DLC + fix 1.04 for launch on PS3 also freezes.

For example. I can complete the arcade game on some difficulty completely, but I may not complete it. At first I noticed that it was freezing when creating shaders, so I thought about it at this point. But even after creating the game, the game may freeze.
