### ISSUE TITLE
DiRT 3: Verification failed at rpcs3/util/atomic.cpp:604

### ISSUE THREAD

**Issue by RainbowCookie32** [RPCS3/rpcs3#11947]
## Quick summary
The game crashes semi-randomly with this verification failed error.
`F {SPU[0x0000100] Thread (CellSpursKernel0) [0x04020]} SIG: Thread terminated due to fatal error: Verification failed
(in file ../rpcs3/util/atomic.cpp:604, in function operator()) (errno=11=Resource temporarily unavailable)`

## Details
While it doesn't consistently crash, so far I've always been able to get it in 5 minutes or less. Staying on the main menu for a while, loading into a race, just running the game seems to eventually trigger it. Sometimes you don't even *get* to the menu

It's probably a regression, since the game is supposed to be Playable. I'll try to find the offending build.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8636339/RPCS3.log.gz)

* OS: Arch Linux (kernel 5.17.5-256-tkg-pds)
* CPU: Ryzen 7 1700
* GPU: RX 570

**Comment by Nekotekina** [comment]
I suppose it started with #11240 ? Only guess atm.

**Comment by Nekotekina** [comment]
Closing as fixed, please reopen if necessary.
