### ISSUE TITLE
Bug: Tekken Tag Tournament 2 Crash When Booting

### ISSUE THREAD

**Issue by kim-sama** [RPCS3/rpcs3#11948]
## Quick summary
Tekken Tag Tournament 2 does not work at all. I updated it to 1.03 and I'm on the newest version of RPCS3 and it won't work

## Details

When I run the game, it compiles the cores then closes

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8637101/RPCS3.log)

OS Windows 10
CPU Intel Core i7 10th Gen
GPU Nvidia Geforce RTX 2060

**Comment by Asinin3** [comment]
Github isn't for support. Validate game files, downgrade to 1.00 test defaults etc. I have tested TTT2 on latest and it works here.
Use https://discord.me/rpcs3 #HELP Channel

**Comment by Asinin3** [comment]
Checked your log, your GPU driver is 2 years old and not supported, update.
