### ISSUE TITLE
[Regression] Can no longer map keyboard input

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#11943]
On today's build, you can no longer map keyboard input. It does not respond when pressing keys while UI is waiting for input. It take mouse input fine.

![2022-05-05 11_56_47-Gamepad Settings](https://user-images.githubusercontent.com/20983844/167005056-ea91e04b-b5cb-4096-a4d5-3b9ba6830fd6.png)

**Comment by Megamouse** [comment]
That's because I forgot to disable the new dropdown at the bottom left.
So the dialog thinks you want to navigate on that dropdown.

**Comment by legend800** [comment]
I noticed it causes action in the box, but nothing else.

**Comment by legend800** [comment]
Also can't map mouse direction fyi, only mouse buttons
