### ISSUE TITLE
LLVM distorted sprites in Disgaea 3

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1194]
![Imgur](http://i.imgur.com/AUuiS4d.png)
The offending block is **263**

**UPD:** this block is HUGE https://gist.github.com/danilaml/220855362fd97d2aa0e3
**UPD2** check different revisions, some are smaller.

**Comment by vlj** [comment]
I have 2 potential block, not the same as yours.
https://gist.github.com/vlj/705c453623405874282a
https://gist.github.com/vlj/31b6306cf62ddb8cfff9

Game hanged before I could properly ensure this block wasn't used :
https://gist.github.com/vlj/133a1fe15b6baa595728

**Comment by vlj** [comment]
Confirmed, it's function at address 0x1cc4f0. If I run the game, let the bug happen, then find the block ID in PPULLVMRecompiler.log and use exclusion mechanism to blacklist the block, sprite are no more corrupted.

It's https://gist.github.com/vlj/31b6306cf62ddb8cfff9

**Comment by vlj** [comment]
It's subfic, I'm trying to find out why it doesn't work.

**Comment by tambry** [comment]
Has this been fixed?

**Comment by danilaml** [comment]
@tambry yes. Issue didn't close because of the they merged commits (sha changed and gh didn't detect the merge)
