### ISSUE TITLE
[Feature Request] Background Input option

### ISSUE THREAD

**Issue by Blackbird88** [RPCS3/rpcs3#11950]
## Quick summary
**Background Input** option

## Details

The ability for RPCS3 to ignore input if its window isn't in focus. 

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* UI

#### 2. Please tell us, why your feature is important to RPCS3.

- Allows you to use multiple programs with gamepad support at same time
- In turn this improves LaunchBox's Pause Menu feature as you can navigate it without unwanted input in RPCS3 itself.

#### 3. Please attach screenshots of the feature implemented in other projects.
Dolphin
![image](https://user-images.githubusercontent.com/4414625/167087038-d5030124-299e-47d9-b3c8-6ac8283ce2ec.png)
PCSX2
![image](https://user-images.githubusercontent.com/4414625/167086948-13f0f42c-1b5b-44be-bd9c-708f94d986c8.png)

Some emulators also accomplish this by **Pause on Focus Lost** feature such as yuzu/duckstation

#### 4. Please provide your system configuration:
Windows 10 21H2
Intel Core i7-10700K
Nvidia GeForce RTX 3070

**Comment by illusion0001** [comment]
Blame dio

**Comment by dio-gh** [comment]
@illusion0001 mind a refresher?

**Comment by Asinin3** [comment]
@dio-gh https://github.com/RPCS3/rpcs3/issues/10130 Was changed because of your issue request. I don't really like the new functionality either :/

**Comment by dio-gh** [comment]
I see, sorry that you feel that way.

**Comment by dio-gh** [comment]
Matter of fact, OP seems to want the _opposite_ of background input, he wants games to stop responding to inputs altogether when unfocused.

This has absolutely zero to do with that issue ticket I've made, nor the fix mega implemented. "Release all keys when leaving the game window" is not that kind of release...

**Comment by Blackbird88** [comment]
> Matter of fact, OP seems to want the _opposite_ of background input, he wants games to stop responding to inputs altogether when unfocused.

This is my bad for naming the title as such. I will rename it.

**Comment by Megamouse** [comment]
Hi @Blackbird88 , can you test this with https://github.com/RPCS3/rpcs3/pull/12308 please?
