### ISSUE TITLE
[Feature Request] Saving settings to a file and loading them in the UI.

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#11951]
## Quick summary
An ability to save current settings to an other file than game's config and load these settings from a file inside the rpcs3.

## Details

Even though we already have save files for different games, and we can do all of the things mentioned above manually, it might be helpful to quickly save current configuration to a file, and load it within the rpcs3's UI. 

If it's not needed at all, then you can just close the issue.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* UI

#### 2. Please tell us, why your feature is important to RPCS3.
It's not that important, it's just a little quality of life feature.

#### 3. Please attach screenshots of the feature implemented in other projects.
I'm not sure if any other emulators has this feature...

#### 4. Please provide your system configuration:
* OS - Win 10 1909
* CPU - I5-4210U
* GPU - GeForce 840m
* Driver version 512.59.0.0

**Comment by Darkhost1999** [comment]
You can right click a game -> boot with manually selected file and quite literally choose any config file created by RPCS3. From yourself or even from others with any filename i believe as long as the extension is .yml. It's possible it supports other filename extensions too but I've only tried .yml

I'm not so sure I understand what you're asking for.

**Comment by RainbowCookie32** [comment]
The only thing I see that's not doable by RPCS3 right now is being able to "save current settings to an other file than game's config".

I don't really see the use for that when you can just use the game's config file. Doesn't sound like a particularly useful feature

**Comment by Asinin3** [comment]
I have re-read the OP multiple times and don't understand what the use case for this would be. You can simply create a custom config file for any game and that file is separate than the main config.yml for the emulators global settings. If you want this re-opened, explain what the usecase is for this change and why people would want it and we can consider re-opening.

**Comment by Hasster1** [comment]
Originally, i have thought about adding 2 buttons to the configuration menu, that would allow to quickly save currently present configuration to a file, and other button to load previously saved configuration from a file. I just thought that it might be a bit faster than copying previously saved settings from folder to folder, but i didn't know that the 'boot with manually selected file' was already an implemented feature.
