### ISSUE TITLE
Setting incorrectly defaulting on custom configuration

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#11956]
How to reproduce:
- Having a custom configuration that has been created prior to a setting being added (for example, "Audio Provider");
- Setting your main configuration's "Audio Provider" to RSXAudio;
- When you open the custom configuration, it will default "Audio Provider" to "RSXAudio" instead of the emulator default "CellAudio". When you save some unrelated edit, it will remain as "RSXAudio", potentially without the user noticing it.

Expected behaviour would probably be to have the new setting fetch the default value that is preset on the emulator, not import what you have at the moment on main config.

This bug happened to me and I was bisecting for a bit only to realise the wrong setting value had leaked into my custom configurations.

Related note: I have RSXAudio on main config to test vsh.self, but I currently need to remind myself to change it to CellAudio before going around updating custom configs otherwise it will leak the wrong value into those.

Unrelated note: I think this setting should just be removed and it should be handled under the hood like in a real console, if it's vsh then use RSXAudio, for anything else use CellAudio.

**Comment by Megamouse** [comment]
This has been intentionally decided by all of us.
So it's not really an issue imo....

The vsh stuff is mitigated in #11964

**Comment by AniLeo** [comment]
Closing for the time being since the setting that caused this confusion has been fixed
