### ISSUE TITLE
Catherine [BLUS30428]:colored mosaics when game is running

### ISSUE THREAD

**Issue by macrosalt** [RPCS3/rpcs3#11955]
## Quick summary
Can run the game, but having colored mosaics on the animation

## Details

* locally built on newest commit of `master`: f7d08d33715e71250c8d3b35d6566a41fe41c378 for mac 10.15.7
*  following this [rpcs3 wiki](https://wiki.rpcs3.net/index.php?title=Help:Building_RPCS3), only changing the os version and the `lowPowerModeEnable` func(not exist in 10.15) in code

#### Make sure you're running with settings as close to default as possible
* running as default config
* having tried to disable anti-aliasing and enable write color buffer, the issue remains

#### RSX capture
[BLUS30428_20220507002340_capture.rrc.zip](https://github.com/RPCS3/rpcs3/files/8642338/BLUS30428_20220507002340_capture.rrc.zip)

#### screenshots of your problem.
![catherine_1](https://user-images.githubusercontent.com/8212479/167178575-f357218d-f4f4-41c0-8278-c1f36e46b112.jpg)
![catherine_2](https://user-images.githubusercontent.com/8212479/167178589-92c0ed4b-74b7-45b0-a008-8c1352473b67.jpg)
![catherine_3](https://user-images.githubusercontent.com/8212479/167178608-88585c38-47f0-4423-8064-69411cd8b255.jpg)

####  system configuration:
* OS mac OS 10.15.7
* CPU: I7-9750H
* GPU: AMD Radeon Pro 5300M
* Driver version: moltenVK 1.1.9

#### other concerns
* When compile the project, having this warning, is this related to this issue?
```
  MACOSX_RPATH is not specified for the following targets:

   SPIRV-Tools-shared
   ```

**Comment by YuriNator557** [comment]
custom builds are not supported

**Comment by MSuih** [comment]
If you can get someone to confirm that it also happens on official builds then please add it to https://github.com/RPCS3/rpcs3/issues/11414

For intel-based mac systems we strongly recommend that you use Windows or Linux instead of MacOS as both performance and Vulkan compatibility are better there.

**Comment by AniLeo** [comment]
It's also using an unsupported version of the OS, needs to be tested on 11.6 or newer even with the official build (which won't allow you to use older versions without modifying it)
