### ISSUE TITLE
Crash when there is no more disk space when creating cache

### ISSUE THREAD

**Issue by NetSysFire** [RPCS3/rpcs3#11962]
## Quick summary

Looks like an edge case. This affects the stage when PPU and SPU cache is being created. I still need to test what happens if I do this via the menu and not when booting the game.

## Details

I was chasing another bug and then I ran out of disk space.

Steps to reproduce:

- Make sure the file system the rpcs3 cache is on (`$XDG_CACHE_HOME`, default is `~/.cache`) is 100% full or close to full.
- Try to boot any game.
- Crash.

Expected behavior: An error message instead of a crash.

There are potentially several edge cases that need to be considered.

1. When creating the cache is successful but there is no more disk space after that. The game you booted will crash in the intro. At least this is what happened to me, I think.
2. When creating the cache via the menu (Create all PPU caches), I can imagine this is affected, too but I did not test that.

If you want to go the extra mile and make rpcs3 extra resilient, I would check other processes which write to disk (saving, when a game installs itself) and how they handle not being able to write.

#### 0. Make sure you're running with settings as close to default as possible

n/a

#### 1. Please attach RPCS3's log.

n/a, as there is no game being started.

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.

n/a

#### 3. Please attach screenshots of your problem.

n/a

#### 4. Please provide comparison with real PS3.

n/a

#### 5. Please provide your system configuration:

* OS: Arch Linux
* CPU: AMD Ryzen 1600af
* GPU: rx 570

**Comment by Megamouse** [comment]
I think a quick fix would be to check the available space when we boot a game and deny it if there's less then a couple of GB left

**Comment by NetSysFire** [comment]
Or just abort cache creation when it gets aborted with `ENOSPC`, the relevant kernel error when using the `write` syscall. This would also help when you run out of inodes instead of space.

One thing you would need to respect on linux though that depending on the configuration on the system, there is some space reserved for root. On ext4 this is a default of 5%.
