### ISSUE TITLE
[Feature Request] Binary decrypt CLI option

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#11969]
Having the equivalent of Utilities > Decrypt PS3 Binaries as `./rpcs3 --decrypt` with both the possibility of taking one `./rpcs3 --decrypt file_path1` or multiple files `./rpcs3 --decrypt file_path1 file_path2 file_path3 ...` as it does in the UI

**Comment by Megamouse** [comment]
implemented
