### ISSUE TITLE
Installing Firmware takes forever after #11907

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#11979]
PPU Modules simply keep increasing when installing firmware...
Any way to opt-out of rsxaudio stuff? Or is this the new normal?
Last build that works is 0.0.22-13555

Meanwhile, 0.0.22-13556 takes easily 5 times as long. In fact, I couldn't be bothered to complete the ppu module setup because it looked like it would be stuck at 50% forever.
So I looked for what build causes this issue right away.

OS: W10
GPU: Radeon RX 5700 (22.4.2 Drivers)
CPU: Ryzen 3900X

**Comment by SlyCooperReloadCoded** [comment]
I can confirm this.  I put all 20 threads of my i9-10900K to work and it eventually compiled 1141 modules, it took 10-15 minutes when it used to take not even a minute.

**Comment by elad335** [comment]
It's because #11907 added modules of VSH, I think VSH should compile it on its boot instead.

**Comment by lextra2** [comment]
> It's because #11907 added precompilatiom of VSH modules, I think they should be compiled on VSH boot instead.

Sounds like a good idea.
