### ISSUE TITLE
NieR rendering regression on Vulkan, displaying buggy polygons on Intel

### ISSUE THREAD

**Issue by linkmauve** [RPCS3/rpcs3#11973]
## Quick summary
Some polygons are rendered in a wrong colour.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
* Please see [How to find the build that caused a regression](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression.3F) in our wiki.
* You can find [History of RPCS3 builds](https://rpcs3.net/compatibility?b) here.
I will bisect if required, but my old builds where it worked don’t run any longer on my current OS. :(
This was circa late 2019, so quite long ago.

#### 2. Please attach TWO logs:
* One for the build with regression.
Will bisect if requested.
* One for the build that works as expected.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8646875/RPCS3.log.gz)

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
https://linkmauve.fr/files/BLES00826_20220508132158_capture.rrc.zst
https://linkmauve.fr/files/nier.rdc.zst
(github didn’t accept these files)

#### 4. Please attach screenshots of your problem.
![wayland-screenshot-2022-05-08_13-39-59](https://user-images.githubusercontent.com/7755816/167294606-bd3d1a52-be1e-4256-8806-cf3a8c025383.png)

#### 5. Please provide comparison with real PS3.
N/A

#### 6. Please provide your system configuration:
* OS: ArchLinux
* CPU: i5-8350U
* GPU: UHD620
* Driver version: Iris on Mesa master (commit 56070d3322)
* Game tested: NieR

#### Please include.
* Anything else you deem to be important

**Comment by AniLeo** [comment]
Duplicate of https://gitlab.freedesktop.org/mesa/mesa/-/issues/5526

**Comment by AniLeo** [comment]
> Driver version: Iris on Mesa master (commit 56070d3322)

The issue doesn't happen with iris, only with anv.

**Comment by linkmauve** [comment]
Err, of course I meant anv, and thanks for pointing me there. :)

**Comment by linkmauve** [comment]
I bisected to anv’s 710393b3aa4a99d446db0c41ef23eb44332332b4, enabling UBO indexing.

**Comment by kd-11** [comment]
Yes, we pointed this out to mesa driver team. It was not supported before, but after we pointed this out, they enabled it and it broke rpcs3. Unfortunately, the intel team is different, Jason left some time back and I don't know if the current anv maintainers care to fix the issue. I suppose as a workaround I can just disable this optimization path on ANV.
