### ISSUE TITLE
[Feature Request] High Sierra support

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [RPCS3/rpcs3#11986]
## Quick summary
Would it be possible to distribute rpcs3 compiled for macOS High Sierra?

## Details

Currently fails launching with error message "You have macOS 10.13.6. The application requires macOS 11.6 or later."

#### Please tell us, why your feature is important to RPCS3.

Lot of people using hackintoshes are stuck on High Sierra because upgrading means losing GPU support unless you own a specific set of AMD cards.

**Comment by nastys** [comment]
High Sierra does not support some C++17 features required by RPCS3, and Homebrew llvm has not been backported.
It also makes more sense to dual boot Linux or Windows, especially on a hackintosh, as it would probably perform a lot better anyway.

**Comment by 2V3EvG4LMJFdRe** [comment]
Alright, thanks for the answer.
