### ISSUE TITLE
Error when selecting "Turn off system" in VSH

### ISSUE THREAD

**Issue by andutrache** [RPCS3/rpcs3#11987]
## Quick summary
When selecting "Turn off system" in VSH RPCS3 shows an error in the console

## Details
The error "·F 0:01:32.683568 {PPU[0x1000000] Thread (main_thread) [0x0003f200]} SIG: Thread terminated due to fatal error: Attempting to dealloc rsx memory when the context is still being used
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\Cell\lv2\sys_rsx.cpp:147[:23], in function sys_rsx_memory_free) (error=0x2)" appears in the console

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8656247/RPCS3.log.gz)

#### 2. Please provide your system configuration:
* OS: Windows 10 Enterprise 21H1
* CPU AMD Ryzen 7 2700
* GPU Nvidia Geforce GTX 1060
* RPCS3 Version: 0.0.22-13575-2b325de6

#### 3. What I have tried:
* Rebuilt the PPU caches for everything
* Running RPCS3 as administrator
* The settings mentioned on the FAQ for VSH
* Reinstalled VSH from scratch

#### 4. Other things of maybe importance:
* Even if I select Turn off system in VSH the database still needs to be rebuilt on next launch but that might not matter for the issue at hand
* Tried rpcs3-v0.0.21-13418-8fb2d04c_win64 as per instructions i received from someone in the Discord Server and the error did not appear the database still needed to be rebuilt afterwards

If there is anything else I missed or forgot to provide ask and I will do my best to be of assistance.

**Comment by marcoluc97** [comment]
If I remember correctly is related to this #10580
Right @elad335 ?

**Comment by andutrache** [comment]
Retested with 0.0.26-14568 with firmware 4.89:
- The error message has stopped appearing;
- VSH still does Rebuild Database after closing it even if Turn Off was selected;

**Comment by Darkhost1999** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11447066/RPCS3.log)
Not an issue anymore as stated by the author as well
