### ISSUE TITLE
Modnation Racers crash when using PPU static interpreter

### ISSUE THREAD

**Issue by derole1** [RPCS3/rpcs3#11988]
When modnation racers is ran using the static PPU interpreter, the game crashes on the loading screen with the message
`F {PPU[0x1000000] Thread (main_thread) [0x001e41c4]} VM: Access violation reading location 0x3f800044 (unmapped memory)`
The game can be run just fine using the LLVM recompiler, however debugging is very difficult using this emulation mode.

Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8661403/RPCS3.log)

Screenshot:
![image](https://user-images.githubusercontent.com/38840902/167627660-7d6ac366-a81d-497a-bdb1-45f910482dc4.png)

Configuration:

OS: Windows 10 Home 20H2
CPU: Intel Core i7 7820X
GPU: Nvidia GeForce GTX 1080
GPU Driver: Game ready driver Version 511.23

Thank you

**Comment by Gael2433** [comment]
Can replicate the issue on ModNation™ Racers [BCES00701]

RPCS3 v0.0.22-13576-de988f6a Alpha | master
Microsoft Windows 10 Version 21H1
Intel(R) Core(TM) i7-3770
16Gb RAM
NVIDIA GeForce GTX 1070 running on driver 512.15.0.0

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8663647/RPCS3.log.gz)
The log contains 3 attempts, Initial boot with game data being installed, second after install and third with networking features disabled.

**Comment by JimScript** [comment]
Can this be retested or closed? Because I've been able to use the game fully(if much slower) with PPU static interpreter on both my Windows 10 computer and Steam Deck.

**Comment by Virjoinga** [comment]
Yes it can, it was a regression in v0.0.29-15463-edf4f7ea which now has been fixed.

**Comment by derole1** [comment]
Apologies for long silence, this now seems to work as of latest build so will close issue. Many thanks all :)
