### ISSUE TITLE
random crash with apple M1 pro chips

### ISSUE THREAD

**Issue by shiylqq** [RPCS3/rpcs3#11990]
## Quick summary
random crash at game switch maps

## Details

Please describe the problem as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
all settings are default

#### 1. Please attach RPCS3's log.
here is logs
[log.txt](https://github.com/RPCS3/rpcs3/files/8663567/log.txt)

#### 3. Please attach screenshots of your problem.
screen stuck never resume

#### 5. Please provide your system configuration:
* OS macOS, Version: 12.3.1
* CPU M1 pro
* GPU M1 pro
* Driver version
* etc.

#### Please include.
* game is Devil May Cry 4

**Comment by Jonathan44062** [comment]
On macOS it will be in ~/Library/Caches/rpcs3.

**Comment by shiylqq** [comment]
thanks for your reply，here is log file
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8667837/RPCS3.log.gz)

**Comment by shiylqq** [comment]
After restarting the computer, it can run for a long time for the first time, and then it will crash frequently

**Comment by Darkhost1999** [comment]
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8667837/RPCS3.log.gz)

Just me or the log is corrupt

![Screenshot.png](https://user-images.githubusercontent.com/60384196/167915385-9b48b6ab-91e1-4a01-8f81-968c46c4f998.png)

**Comment by Darkhost1999** [comment]
Ah so you're trying to get a pirated game to run.

**Comment by Megamouse** [comment]
whether or not this is pirated, there's a mac meta issue anyway.
