### ISSUE TITLE
Graphical Issue for Skylanders Trap Team

### ISSUE THREAD

**Issue by Awesoman360** [RPCS3/rpcs3#12008]
Skylanders Trap Team's colours are mainly red.

Booting Skylanders Trap Team in rpcs3 version 0.0.21 - 13531 or later has an issue where the entire game is missing certain colours and so replaces them with red. The game works perfectly otherwise.

Incorrect graphics log from rpcs3 version 0.0.21 - 13531 (and beyond): [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8692997/RPCS3.log.gz)
![image](https://user-images.githubusercontent.com/105549749/168427929-69d7c21f-58d0-41b1-a721-89a7f433fa3c.png)

Correct graphics log from rpcs3 version 0.0.21 - 13528: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8693000/RPCS3.log.gz)
![image](https://user-images.githubusercontent.com/105549749/168427600-2bd860a7-3d0b-4a22-b10d-7b40a9088cf7.png)

I would include an RSX capture and render doc of the incorrect graphics, but attempting to do so results in a freeze.

My system configuration:
11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz | 12 Threads | 7.77 GiB RAM | TSC: 2.688GHz | AVX-512+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
 vulkan-compatible GPU: 'GeForce RTX 3050 Ti Laptop GPU' running on driver 462.62.0.0
Found vulkan-compatible GPU: 'Intel(R) UHD Graphics' running on driver 0.402.199

**Comment by YuriNator557** [comment]
RSX captures only pause emulation, you can resume after taking one

**Comment by jantendog** [comment]
I found something. Disable native float16 support fixes it in my case.

**Comment by Jorforit** [comment]
I have the same issue with swap force, I don't understand how to use the log for correct settings. Can someone please help me?

**Comment by z0z0z** [comment]
> I found something. Disable native float16 support fixes it in my case.

I can confirm this worked for someone else. It should be added to the wiki (not me)

**Comment by chrisgamefuny** [comment]
> I found something. Disable native float16 support fixes it in my case.

where do you disable it?

**Comment by Darkhost1999** [comment]
You tick the box in the advanced tab next to `disable native float 16` and click save

**Comment by jantendog** [comment]
> You tick the box in the advanced tab next to `disable native float 16` and click save

Under advanced and GPU

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/12788
