### ISSUE TITLE
The guided fate paradox crash/hang after loading Celestia level

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1200]
In the guided Fate paradox, when starting a new game and skipping intro, with PPU Interpreter 2 :
- it hangs with error message "E {PPU[0x1] Thread (main_thread)[0x0039b884]} STD Exception: device or resource busy: device or resource busy" with revision 3468a7ebcfd1164c8feb8c16ba7e20dcdc39faaa
- It crashed with the following strack trace https://gist.github.com/vlj/0b7f1f0f00d587036b6c with commit c0b90d01bd50124b8b205f1dff1f7a0ebae8779f

**Comment by tambry** [comment]
@vlj Is this still an issue?

**Comment by vlj** [comment]
without LLE yes.

**Comment by tambry** [comment]
@vlj Which module is at fault here then?

**Comment by raven02** [comment]
I'm closing this as it is not even passing the intro now in 0.0.0.9.
