### ISSUE TITLE
Street Fighter X Tekken[BLES01252]: Stutters in character select screen. Multiple Error: "TODO: lv2_socket_raw::recvfrom"

### ISSUE THREAD

**Issue by Manya3084** [RPCS3/rpcs3#12016]
Details:
When selecting to start a new match, and selecting the match parameters, the game will begin to stutter and flood the log with the "TODO: lv2_socket_raw::recvfrom" error. 

This issue was not present last week so the issue has come out in the last 7 days worth of builds.

Log File(File grew to over 1GB in less than a minute):  https://drive.google.com/file/d/1Pyw1dXlIMMVkQcA31VKK2HdrCZpubDg4/view?usp=sharing 

Screenshots:
![Untitled](https://user-images.githubusercontent.com/104078862/168461441-c722f057-9274-469e-b900-7e00ce54f8b5.png)

PS3 Comparison:
I fired it up on my old PS3 and this doesn't happen.

System Config:
OS: Windows 11
CPU: 12900K
GPU: 3090 
GPU Driver version: 512.77
RPCS version: RPCS3 v0.0.22-13600-2ba437b6

Please advise if you require anymore info.

**Comment by castle024** [comment]
Same issue here, reverted game back to version 1.0, no dlc, and it worked fine. Not sure if problem is within update 1.08 or dlc. Will edit comment after further investigation.

**Comment by legolas119** [comment]
hi, i have same issue! how can i reverse to the 1.0 patch? with this patch, does the game recognize every DLC in any case?
thanks!

**Comment by RipleyTom** [comment]
This needs to be re-tested, should be fixed now.

**Comment by legolas119** [comment]
yes, it works again now!!!!!!!!!!! Many thanks!
