### ISSUE TITLE
Fails with flatbuffers-2.0.6: flatbuffers headers aren't forward-compatible

### ISSUE THREAD

**Issue by yurivict** [RPCS3/rpcs3#12011]
```
In file included from /wrkdirs/usr/ports/emulators/rpcs3/work/rpcs3-0.0.22-13592-g5ae9de4e3b/rpcs3/Emu/Cell/lv2/sys_net.cpp:34:
In file included from /wrkdirs/usr/ports/emulators/rpcs3/work/rpcs3-0.0.22-13592-g5ae9de4e3b/rpcs3/Emu/NP/np_handler.h:11:
In file included from /wrkdirs/usr/ports/emulators/rpcs3/work/rpcs3-0.0.22-13592-g5ae9de4e3b/rpcs3/Emu/NP/rpcn_client.h:29:
/wrkdirs/usr/ports/emulators/rpcs3/work/rpcs3-0.0.22-13592-g5ae9de4e3b/rpcs3/Emu/NP/generated/np2_structs_generated.h:128:12: error: no matching member function for call to 'VerifyField'
           VerifyField<uint16_t>(verifier, VT_ID) &&
           ^~~~~~~~~~~~~~~~~~~~~
/usr/local/include/flatbuffers/table.h:115:8: note: candidate function template not viable: requires 3 arguments, but 2 were provided
  bool VerifyField(const Verifier &verifier, voffset_t field,
       ^
In file included from /wrkdirs/usr/ports/emulators/rpcs3/work/rpcs3-0.0.22-13592-g5ae9de4e3b/rpcs3/Emu/Cell/lv2/sys_net.cpp:34:
In file included from /wrkdirs/usr/ports/emulators/rpcs3/work/rpcs3-0.0.22-13592-g5ae9de4e3b/rpcs3/Emu/NP/np_handler.h:11:
In file included from /wrkdirs/usr/ports/emulators/rpcs3/work/rpcs3-0.0.22-13592-g5ae9de4e3b/rpcs3/Emu/NP/rpcn_client.h:29:
/wrkdirs/usr/ports/emulators/rpcs3/work/rpcs3-0.0.22-13592-g5ae9de4e3b/rpcs3/Emu/NP/generated/np2_structs_generated.h:191:12: error: no matching member function for call to 'VerifyField'
           VerifyField<uint16_t>(verifier, VT_ID) &&
           ^~~~~~~~~~~~~~~~~~~~~
/usr/local/include/flatbuffers/table.h:115:8: note: candidate function template not viable: requires 3 arguments, but 2 were provided
  bool VerifyField(const Verifier &verifier, voffset_t field,
       ^
```

You need to keep the flatbuffers format definition in the repository and regenerate headers during build.

See this  [comment](https://github.com/google/flatbuffers/issues/7272#issuecomment-1124007622) as reference.

**Comment by RipleyTom** [comment]
The definition is in the repository(for documentation purposes) and the generated file works with the library version we're using.

**Comment by yurivict** [comment]
Revision 0.0.22-13597-g1e1b111678 that the FreeBSD port uses breaks with flatbuffers-2.0.6.

It uses the header generated by the previous version of flatbuffers.

**Comment by yurivict** [comment]
You should not put headers into the repository, instead you should regenerate them during build.
This would make the project forward-compatible. Now it will be breaking with every change to a new flatbuffers version due to a static assert there.

**Comment by RipleyTom** [comment]
```
$ ./flatc --version
flatc version 2.0.6
$ ./flatc --cpp np2_structs.fbs
...lots of warnings about snake case...
$ diff np2_structs_generated.h ~/Repos/rpcs3/rpcs3/Emu/NP/generated/np2_structs_generated.h
$
```

My guess is you're not on 2.0.6 but on latest flatbuffers commit?

**Comment by RipleyTom** [comment]
But yes it's not forward compatible and generating the header each time we compile is not a terrible idea.
I guess I can make it so it only happens when people are using system flatbuffers to avoid lengthening compilation time for nothing :thinking: .

**Comment by yurivict** [comment]
No, I definitely tried with flatbuffers-2.0.6.

**Comment by RipleyTom** [comment]
Look at which version the commit of 3rdparty/flatbuffers is pointing at.
That's what I build with locally, that's what the CIs build with and it's pointing at the tag v2.0.6...

**Comment by RipleyTom** [comment]
Can you test with https://github.com/RPCS3/rpcs3/pull/12014 ?
