### ISSUE TITLE
Red Dead Game of the Year [BLUS30758] will close itself after Install screen 

### ISSUE THREAD

**Issue by RigBonet** [RPCS3/rpcs3#12022]
Keeps giving me an error "E SYS: Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/rdr2_installed.sdat” [x4]" Ive been stuck on this for a day have no idea how to fix this

**Comment by RainbowCookie32** [comment]
This is not the place to ask for support, that's for our forums or the Discord server. You can find links for both on our website
