### ISSUE TITLE
VSH Regression

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12032]
I'm creating this issue from my phone having some issues with parsec and the issue got made too fast. But here we go.

VSH fails to compile SPU modules when booting using your just plain old global config settings. But works just fine on 12000 where #11999 is the broken build.
[Regression.log](https://github.com/RPCS3/rpcs3/files/8721151/Regression.log)

![Screenshot_20220518-162701.png](https://user-images.githubusercontent.com/60384196/169163568-da96a4d4-2ba9-4e36-a0fc-717e7e62c6fa.png)

[workking.gz](https://github.com/RPCS3/rpcs3/files/8721148/workking.gz)

![Screenshot_20220518-164156.png](https://user-images.githubusercontent.com/60384196/169163556-2415b357-dec5-4eb7-bb58-ee2521f84088.png)

**Comment by Darkhost1999** [comment]
Edited

**Comment by elad335** [comment]
#12019

**Comment by Darkhost1999** [comment]
Works
![image](https://user-images.githubusercontent.com/60384196/169285043-fd7670d4-3a30-48bf-a570-ab274468c146.png)

**Comment by Darkhost1999** [comment]
Fix was merged
