### ISSUE TITLE
Xmb won't boot when the update for audio and hdmi support dropped

### ISSUE THREAD

**Issue by KirbyFighter** [RPCS3/rpcs3#12033]
![image](https://user-images.githubusercontent.com/71234367/169171232-33c2e5c8-0ab0-4ff2-a9f9-e2bb6bda9670.png)
![image](https://user-images.githubusercontent.com/71234367/169171465-f239d24c-0b2f-475f-952b-109506c494a5.png)

Please tell me if there is anyway to fix this. If not then they the devs need to fix this. 
Thanks

**Comment by KirbyFighter** [comment]
![image](https://user-images.githubusercontent.com/71234367/169176629-d546b47a-a121-4174-bc11-b8da342a4271.png)
here

**Comment by Darkhost1999** [comment]
Yes duplicate.
