### ISSUE TITLE
God Of War III: Error some thread has probably deadlocked. Aborting

### ISSUE THREAD

**Issue by miotegui** [RPCS3/rpcs3#12031]
## Quick summary
Some thread has probably deadlocked. Aborting.

## Details

I'm playing God Of War 3, and it works quite fine, but when i die, this error appears on screen:

RPCS3: Fatal Error
Stopping emulator took too long.
Some thread has probably deadlocked. Aborting.
Thread id = 7144.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8719262/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc.
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 3. Please attach screenshots of your problem.

its freezes only when i die

![freeze](https://user-images.githubusercontent.com/12590752/169120296-15822039-8b3a-4f05-8c94-41315d12143c.png)

and then this appears:

![freeze 2](https://user-images.githubusercontent.com/12590752/169120313-a14d6708-6b42-47ae-8a73-2eedd3985fc1.png)

#### 5. Please provide your system configuration:
* OS: Windows 10, 64 bits
![1](https://user-images.githubusercontent.com/12590752/169118940-ece8dcd9-f157-4c9e-89ec-630bebc98f44.png)
![2](https://user-images.githubusercontent.com/12590752/169118952-42398790-c3a8-43e0-b24d-96853fa101a9.png)
![3](https://user-images.githubusercontent.com/12590752/169118959-ca8f634e-3ebe-42e6-9993-5a59cdaf1c2f.png)

#### Please include.
* Anything else you deem to be important
* 
![patch manager](https://user-images.githubusercontent.com/12590752/169139467-eddda6b2-bc7f-4d3e-8501-e81c550365f1.png)

**Comment by YuriNator557** [comment]
Issues with patches enabled are not valid

**Comment by Asinin3** [comment]
You have debug console mode on.... why? Also using game patches is not valid. Fix settings, copy wiki https://wiki.rpcs3.net/index.php?title=God_of_War_III and clear out unnecessary options that are only reducing your performance and making things worse (read color buffers too!)

GirHub isn't for support.
