### ISSUE TITLE
Resistance: Fall of Man [BCUS98107]: Foliage missing in game

### ISSUE THREAD

**Issue by homembarata** [RPCS3/rpcs3#12040]
Foliage in the game seems to be missing overall.

Most noticeably, on the first level of the game, a huge chunk of tall grass that is supposed to show up, is missing. Other minor patches of grass seem to be missing too too.

RPCS3's log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8734095/RPCS3.log.gz)
ease attach RPCS3's log.

RSX Capture:
https://www.dropbox.com/s/a803bmgxhhr9ryi/BCUS98107_20220519173303_capture.rar?dl=0

Tried capturing it with Renderdoc but my PC just can't handle it, game runs at 1fps with it on. Hopefully this is enough.

On RPCS3:
![BCUS98107_screenshot_2022_05_18_17_25_17](https://user-images.githubusercontent.com/13881636/169401581-f73e2946-e7eb-44fd-a8bb-d1f7acde8ad1.png)

Here's how it should look like (from Youtube as I can't capture it from a real PS3):
![Resistance_ Fall Of Man _ PS3 _ Full Game Playthrough Walkthrough _ No Commentary 5-34 screenshot](https://user-images.githubusercontent.com/13881636/169401818-a7cbdae6-90da-4894-a96f-9c436b6f58af.png)

#### 5. Please provide your system configuration:
Windows 10
CPU: Intel Core i7-7700HQ @ 2.80GHz 
GPU: NVIDIA Geforce GTX 1600 Max-Q
NVIDIA Driver 512.59
16GB RAM

RPCS3 version 0.0.22-13604-5a581f46

**Comment by digitaldude555** [comment]
#10754 already an issue for it.

**Comment by homembarata** [comment]
Well, more data for it them, hope this helps. It's very easy to test this as it's at the very beginning of the game.

**Comment by JimScript** [comment]
I've already given some much data about that, like how it also affects Tools of destruction. It's a very odd issue as it doesn't get rid of all the foliage, there is almost always only one mesh rendered at time and how it determines which one it is a mystery to me.

**Comment by Asinin3** [comment]
My mistake, didn't realize there was an issue for it already when I told you to make one on github.
