### ISSUE TITLE
Yakuza Kenzan [BLJM60064] Nvidia Regression after #11867

### ISSUE THREAD

**Issue by Chirrowho** [RPCS3/rpcs3#12049]
## Quick summary
In specific locations, game renders colours incorrectly.

## Details
The issue is very similar to the one reported for Dead Souls: https://github.com/RPCS3/rpcs3/issues/11027,
however ive confirmed that it can be fixed when disabling Float16 support
The first version to exhibit this problem is: https://github.com/RPCS3/rpcs3/pull/11867

#### 2. Please attach TWO logs:
[v0.0.21-13531: RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8743636/RPCS3.log.gz)
[v0.0.21-13528: RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8743640/RPCS3.log.gz)

#### 3. If you describe graphical regression, please provide a capture that demonstrate it.
[RenderDoc](https://drive.google.com/file/d/1kuT-GhfBvVvQz7VX2Jw8qx8stOQB0YBL/view?usp=sharing)

#### 4. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/105946118/169601832-23eba544-a7d0-442c-a8bc-152201d1b5a6.png)
![image](https://user-images.githubusercontent.com/105946118/169601904-d5863030-b49c-4d05-8123-e7822b45c2ac.png)

#### 5. Please provide comparison with real PS3.
![image](https://user-images.githubusercontent.com/105946118/169601059-c0f466ef-36b7-4651-966c-55e6213f081d.png)
![image](https://user-images.githubusercontent.com/105946118/169601778-f550a099-eb17-4a44-b9f8-8d1efd39d667.png)
(I dont have an easy way of getting screenshots so im using a youtube video)

#### 6. Please provide your system configuration:
* OS: Windows 10 Pro Build 19042
* CPU: Intel Core i5-9600KF @ 3.70GHz
* GPU: Nvidia GTX 1650
* Driver version: 512.25

**Comment by kd-11** [comment]
FTR, this is limited to turing-series GPUs.

**Comment by kd-11** [comment]
This was fixed with the addition of the "High" shader quality option.
