### ISSUE TITLE
inFamous[BCUS98119] Cole's hitboxes visible at certain angles

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#12043]
## Quick summary
When looking at certain angles, you can see boxes around Cole.

## Details
When you look around, at certain angles shadowy boxes will appear around Cole. They kinda look like hitboxes, but I don't know why they would ever be visible. Along with seeing these boxes, the ground cover's shading changes for some reason. The boxes are also rendered behind the water as well.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8736227/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
[BCUS98119_20220519050603_capture.zip](https://github.com/RPCS3/rpcs3/files/8736234/BCUS98119_20220519050603_capture.zip)

#### 3. Please attach screenshots of your problem.
Normal rendering:
![BCUS98119_screenshot_2022_05_19_05_11_27](https://user-images.githubusercontent.com/66685584/169459332-2e8abdc5-a227-49ca-a46e-0ae53d5189ba.png)

Boxes rendering:
![BCUS98119_screenshot_2022_05_19_05_11_46](https://user-images.githubusercontent.com/66685584/169459385-a64fad88-c8f5-479d-bfd1-7b1fecea2df2.png)

#### 5. Please provide your system configuration:
- SYS: RPCS3 v0.0.22-13604-5a581f46 Alpha | master
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 511.23.0.0
- SYS: Firmware version: 4.88

**Comment by JimScript** [comment]
Here is a video showing the effect in action:

https://user-images.githubusercontent.com/66685584/169640908-749dec4e-0393-45a2-a6cb-958c78e046bb.mp4

**Comment by Darkhost1999** [comment]
I've just never been able to catch that effect on Camera but can say that I've experienced that issue several times on my pc.
Ryzen 5 3600
GTX 1660S
Windows 11

I'm not sure as to what causes that "shadow cole" effect whether CPU or GPU. Is there a consistent spot you've been able to get this effect to reappear over and over? You're saying camera angle?

**Comment by JimScript** [comment]
This here is Zeke's rooftop that you jump off of at the start, right at the place of the "express elevator". Although the time of day could also affect it, in that case this is before the mysterious signals mission.

**Comment by JimScript** [comment]
I messed around with the renderdoc a bit and I found that the first image is incorrect too, the ground cover is suppose to have the shading of the second. In the first color pass where the foreground is rendered, I found that after cole gets drawn things start to diverge. In the first image it stops drawing to the scene's normal map, but in the second it doesn't stop drawing when it gets to cole's boxes, overriding the scene's normal map alpha with black boxes. Meaning that it stops to early in the first image, but too late in the second. There is this black splotch texture that doesn't have a normal map that seems to be the cause of the too early one.

**Comment by JimScript** [comment]
Here are the renderdocs I was talking about:

Boxes and Gravel
![infamousBoxNormal](https://user-images.githubusercontent.com/66685584/170181040-25cc8485-df47-4920-98b0-56369ad8f818.png)
Files:
[infamousBox.7z.001.zip](https://github.com/RPCS3/rpcs3/files/8767975/infamousBox.7z.001.zip)
[infamousBox.7z.002.zip](https://github.com/RPCS3/rpcs3/files/8767976/infamousBox.7z.002.zip)
[infamousBox.7z.003.zip](https://github.com/RPCS3/rpcs3/files/8767978/infamousBox.7z.003.zip)
[infamousBox.7z.004.zip](https://github.com/RPCS3/rpcs3/files/8767979/infamousBox.7z.004.zip)

No Boxes or Gravel
![infamousNoBoxNormal](https://user-images.githubusercontent.com/66685584/170181366-2afcd8a6-c9c2-40ea-8398-e819fc9d640f.png)
Files:
[infamousNobox.7z.001.zip](https://github.com/RPCS3/rpcs3/files/8767984/infamousNobox.7z.001.zip)
[infamousNobox.7z.002.zip](https://github.com/RPCS3/rpcs3/files/8767986/infamousNobox.7z.002.zip)
[infamousNobox.7z.003.zip](https://github.com/RPCS3/rpcs3/files/8767988/infamousNobox.7z.003.zip)
[infamousNobox.7z.004.zip](https://github.com/RPCS3/rpcs3/files/8767990/infamousNobox.7z.004.zip)

**Comment by JimScript** [comment]
Ok, so I did some more renderdoc and I think the gravel is causing the black boxes. In the renderdoc that doesn't have boxes, there is some decals without normal maps rendered in between Cole and the gravel, so the gravel is unnormalized. But in the one with the boxes there is nothing in between Cole and the gravel, so the boxes draw over the tonemap in the scene normal. So it seems that the gravel shader doesn't know when to start or stop rendering to the scene normal, it just keeps going with the last state until the end of the color pass. It also seems to shimmer(as seen in the video above), even in a RSX capture.

**Comment by YuriNator557** [comment]
![image](https://user-images.githubusercontent.com/76178650/173237778-4409f5e2-4f8d-4252-b773-24fa12689bba.png)
Can confirm, it's more visible under the bridge after the riot

**Comment by JimScript** [comment]
It's probably more visible because there are less decals there and more objects drawn in the foreground. In the 1st color pass, weather or not it continues to draw to the scene normal is determined by what draws after Cole. So when it draws a decal that has no normal map, it stops drawing to the scene normal for the rest of the pass. But when there is none, it continues to draw to the scene normal until the end of the color pass, zeroing out the tonemap with Cole's boxes(I am unsure what these boxes are really for). As for why the boxes only appear close up, the first color pass only draws foreground objects, so any mistakes are covered by the background.

**Comment by JimScript** [comment]
Well, I don't know where or when this issue was fixed, but it's fixed so I can close it.

**Comment by Darkhost1999** [comment]
This had to of been fixed in the past 72 hours. Cause it was still there for me. I'll do more testing later if I get the chance to and confirm it's all the way gone for me. Yuri's screenshot is what it looked like for me.
