### ISSUE TITLE
Dragon Ball Z: Battle of Z battle mode crashes the game when making a lobby

### ISSUE THREAD

**Issue by Junny4444** [RPCS3/rpcs3#12041]
## Quick summary
The game crashes when i create a room in the "Battle Mode" section of the main menu in the game.

Please describe the problem as accurately as possible.

#### 1. Please attach RPCS3's log.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8734473/RPCS3.log)

#### 3. Please attach a video of your problem.

https://user-images.githubusercontent.com/76232378/169412948-fd94b485-7b96-40cf-8f12-b25f4695c246.mp4

#### 4. Please provide comparison with real PS3.
It does not crash

#### 5. Please provide your system configuration:
Windows 10
Intel Core I9-9900K 3.60 GHZ
RTX 3090
Version: 30.0.14.9729

**Comment by RipleyTom** [comment]
Same, should be fixed.

**Comment by RipleyTom** [comment]
Should be fixed, reopen if it is not.
