### ISSUE TITLE
Ratchet & Clank: Quest For Booty (verification failed)

### ISSUE THREAD

**Issue by zeroking1998** [RPCS3/rpcs3#12053]
After Playing for 40 min i get this error:

SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\texture_cache.h:3118[:8], in function upload_scaled_image)

![Screenshot (6)](https://user-images.githubusercontent.com/97965119/169640103-28591414-f4ca-4e30-b2b9-1749b92f5315.png)

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8747130/RPCS3.log)

#### 5. Please provide your system configuration:
* OS windows 11
* CPU Ryzen 9 5900X
* GPU GTX 970
* Driver version 512.59

**Comment by Asinin3** [comment]
Quest for Booty is listed as ingame for a reason. It has stability issues like you experienced. If you can find a way to 100% reproduce this and can provide a save and steps to reproduce feel free to get the issue re-opened but for now these kinds of reports aren't helpful. You could also load the game with debug output enabled and if you hit the crash again provide a full log with vulkan sdk installed. But this is going to be closed as it doesn't help us.

**Comment by Darkhost1999** [comment]
I believe this issue is the same as
https://github.com/RPCS3/rpcs3/issues/11937 anyways.
