### ISSUE TITLE
[MGS4] Freeze in Middle of 3rd Cutscene

### ISSUE THREAD

**Issue by esot0** [RPCS3/rpcs3#12057]
While I can progress through the game with only minor graphical glitches, in the 3rd cutscene when in the helicopter with Colonel Campbell, the game abruptly freezes. I have attached my configuration and a log file below:

Any insight into what could be causing the issue is much appreciated. 
[config_NPUB31633.txt](https://github.com/RPCS3/rpcs3/files/8747883/config_NPUB31633.txt.txt)
[log.txt](https://github.com/RPCS3/rpcs3/files/8747884/log.txt)

EDIT: Skipping the cutscene and proceeding to the next gameplay section seems to function smoothly. It may be an issue with this specific cutscene.

**Comment by Asinin3** [comment]
GitHub is for reporting bugs with proper identification not asking for support. Use Discord for support. + follow settings on wiki https://wiki.rpcs3.net/index.php?title=Metal_Gear_Solid_4%3A_Guns_of_the_Patriots
Log file is not proper log and just a copy paste from UI.
