### ISSUE TITLE
[Regression] Reduced performance in various 60 FPS games since #12045 when rpcs3 frame limiter is enabled

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#12050]
## Quick summary
Games that natively run at 60 FPS (not capped to 30 FPS) on the PS3 exhibit reduced performance in terms of frame time consistency and frame rate after #12045, when the rpcs3 frame limiter is enabled.

## Details
On builds before 0.0.22-13627, when running a game that can go up to 60 FPS on the PS3, e.g. God of War Ascension and God of War 3, frame times were smoother and performance was better when using the rpcs3 frame limiter to cap it to 60 FPS. 

Builds after that exhibit significant performance drops especially if your system cannot sustain 60 FPS all the time, coupled with frame times that are more uneven and jump up and down between 16.6ms and 33.3ms.

## Reproduction steps
1. Boot up rpcs3 with default settings and make sure you have the rpcs3 frame limiter enabled.
2. Run a game with 60 FPS support (like GoW:A, GoW3, Metal Gear Rising etc).

E.g. God of War Ascension

Before #12045 (0.0.22-13626) - Average FPS 45 with smoother frame times.
![image](https://user-images.githubusercontent.com/4345150/169623709-d2516d02-f13b-4af4-a73b-51b9a4718c59.png)

After #12045 (0.0.22-13627) - Average FPS 41 with poorer frame times.
![image](https://user-images.githubusercontent.com/4345150/169624035-30f26e0f-625d-40ec-8fba-d52ad921c861.png)

## Logs
* One for the build with regression.
[RPCS3after.log.gz](https://github.com/RPCS3/rpcs3/files/8746112/RPCS3after.log.gz)

* One for the build that works as expected.
[RPCS3before.log.gz](https://github.com/RPCS3/rpcs3/files/8746113/RPCS3before.log.gz)

## Current workaround
Disable the built in rpcs3 framelimiter, and use an external one like RTSS or the NVIDIA Control Panel.

## System configuration
- SYS: 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.86 GiB RAM | TSC: 2.496GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1070 Ti' running on driver 511.79.0.0

**Comment by jokoputera** [comment]
mine isnt working since https://github.com/RPCS3/rpcs3/pull/12020. always deadlock after Santa Monica Logo

**Comment by Asinin3** [comment]
@jokoputera Unrelated to that PR and this issue. https://wiki.rpcs3.net/index.php?title=God_of_War_III see wiki for known fix for that issue.

**Comment by jokoputera** [comment]
Thanks @Asinin3, but im not asking for support as for support i should reach in Discord, thanks anyway.
So im reporting that my configuration is the same configuration as my previous configuration, so i believe its has something to do with this PR or previous PR. 
Strangly enough, its happen only in God of war ascension, although GOW3 also (ibelieve) share the same engine, but GOW3 is working just fine.

**Comment by elad335** [comment]
Test with #12052

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/12055

**Comment by jokoputera** [comment]
God Of War Ascension, Fixed
