### ISSUE TITLE
Error compiling - linux

### ISSUE THREAD

**Issue by latot** [RPCS3/rpcs3#1206]
Hi ppl, well i can't compile the project in linux here the log:

[  7%] Built target asmjit
[  7%] Generating something_that_never_exists
-- Found Git: /usr/bin/git (found version "2.5.1") 
[  7%] Built target GitVersion
[  7%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Emu/Cell/PPULLVMRecompilerCore.cpp.o
In file included from /home/pipe/Documentos/rpcs3/rpcs3/Emu/Cell/PPULLVMRecompilerCore.cpp:5:0:
/home/pipe/Documentos/rpcs3/rpcs3/Emu/Cell/PPULLVMRecompiler.h: In member function ‘virtual uint64_t ppu_recompiler_llvm::CustomSectionMemoryManager::getSymbolAddress(const string&)’:
/home/pipe/Documentos/rpcs3/rpcs3/Emu/Cell/PPULLVMRecompiler.h:967:41: error: ‘getSymbolAddressInProcess’ was not declared in this scope
    return getSymbolAddressInProcess(Name);
                                         ^
In file included from /home/pipe/Documentos/rpcs3/rpcs3/stdafx.h:170:0,
                 from /home/pipe/Documentos/rpcs3/rpcs3/cotire/rpcs3_CXX_prefix.cxx:4,
                 from /home/pipe/Documentos/rpcs3/rpcs3/cotire/rpcs3_CXX_prefix.hxx:4:
/home/pipe/Documentos/rpcs3/rpcs3/../Utilities/StrFmt.h: In instantiation of ‘std::string fmt::format(const char*, Args ...) [with Args = {}; std::string = std::basic_string<char>]’:
/home/pipe/Documentos/rpcs3/rpcs3/../Utilities/StrFmt.h:279:49:   required from ‘fmt::exception::exception(const char*, int, const char*, const char*, Args ...) [with Args = {}]’
/home/pipe/Documentos/rpcs3/rpcs3/Emu/Memory/vm.h:56:11:   required from here
/home/pipe/Documentos/rpcs3/rpcs3/../Utilities/StrFmt.h:255:85: warning: format not a string literal and no format arguments [-Wformat-security]
    const std::size_t len = std::snprintf(buf_addr, buf_size, fmt, do_unveil(args)...);
                                                                                     ^
/home/pipe/Documentos/rpcs3/rpcs3/../Utilities/StrFmt.h:255:85: warning: format not a string literal and no format arguments [-Wformat-security]
rpcs3/CMakeFiles/rpcs3.dir/build.make:6239: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/Emu/Cell/PPULLVMRecompilerCore.cpp.o' failed
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/Cell/PPULLVMRecompilerCore.cpp.o] Error 1
CMakeFiles/Makefile2:260: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

Thx.

**Comment by vlj** [comment]
Does it build without llvm support ?

**Comment by latot** [comment]
Hi, i'm building with llvm support, and my llvm is working, i'm using gentoo, if llvm in cmake fails i couldn't compile the system, and the cmake of rpcs3 recognize the llvm.

**Comment by danilaml** [comment]
@latot what is your llvm version? We require 3.6.x as of now.

**Comment by latot** [comment]
Hi, thx, that fix the issue, can some one add that info to the main page plis?

**Comment by tambry** [comment]
@latot "...don't forget to add -DLLVM_DIR=/usr/local/opt/llvm36/lib/llvm-3.6/share/llvm/cmake..." is already in the README,

**Comment by latot** [comment]
okis, i'll check it the next time :D

**Comment by danilaml** [comment]
@tambry well, it's mainly for osx. But yeah, the fact that we need specific version of llvm of linux is missing in the readme (though implied in some places).
