### ISSUE TITLE
Beyond: Two Souls [BCUS99134] Not showing game updates in the emulator

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#12069]
Not sure if it is the right place to report this little problem.

A small but curious issue, the version I have, is the LATAM edition, in the emulator saids there's no game updates available 
![image](https://user-images.githubusercontent.com/78843189/169743075-fe1ae9da-d073-4e18-b98f-17fe22b9ff2f.png)

But, doing the bot comand !psn check updates BCUS99134, updates are shown to be available
![rpcs3 bot command](https://user-images.githubusercontent.com/78843189/169743765-1d559f5f-e0dc-4205-8464-96bc8de9b628.jpg)

This could be confusing for some users.

If there is anything else to add, I will post more information.

**Comment by illusion0001** [comment]
Game update info is defined in `compat_database.dat` and seems missing for this title, other version exists but not this one

**Comment by MSuih** [comment]
This serial ID has not been reported for compatibility list, so the compatibility database has no entries for it and thus no update data has been queried for it either. It would be great if you could do a quick report for it by following [the guidelines in here](https://forums.rpcs3.net/thread-196671.html). The report doesn't need to be too exhaustive as the game has already reports from other serials.

I'm closing this as there's no emulator bug involved.

**Comment by Jonathan44062** [comment]
Yeah, I made the report in the rpcs3 forum, just waiting when Ani moves more games
https://forums.rpcs3.net/thread-203972.html
