### ISSUE TITLE
Loading screen freeze in Metal Gear Solid: Peace Walker HD edition (BLUS30847)

### ISSUE THREAD

**Issue by SteamBowl** [RPCS3/rpcs3#12079]
## Quick summary
Within Peace Walker in the Metal Gear Solid HD Collection (BLUS30847), certain loading screens have started to freeze indefinitely, such as when skipping cutscenes or trying to start missions. Everything within mother base works properly. 

## Details

Strangely, everything worked perfectly when I first played the game, but after loading my save from the main menu for the first time the issue emerged. It appears to be related to rcpn in some way, as the fatal error is "Failed to bind DGRAM socket to 3658 for P2P!". I have tried running with all default settings, as well as several different combinations of settings and previous builds, none of which have resolved the issue. In fact, the game freezes when starting a new file now, even on old builds, even though it worked fine when I first played. The issue happens both when disconnected and when connected and simulated, which is required for some missions in the game to work. The issue also doesn't affect any other games included in the collection. Testing both MGS2 and 3, they both work perfectly fine, even after the issue with peace walker emerged.

Here's my log:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8766178/RPCS3.log.gz)

Here's a screenshot of what the game looks like when it freezes loading into a mission. The screen begins to fade to black and the helicopter sound plays as normal before both abruptly cut off, and I am left with this.
![game freeze](https://user-images.githubusercontent.com/17225719/170131521-af94bd23-18fe-408a-8533-da07eef55251.PNG)

As for a comparison with a real PS3, my PS3 is buried in my basement somewhere so I can't run a comparison at the moment, but I know I never encountered this issue when running it on there.

#### 5. Please provide your system configuration:
OS: Windows 10
CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz, 3302 Mhz, 4 Core(s), 8 Logical Processor(s)
GPU: NVIDIA GeForce RTX 3070 Laptop GPU

**Comment by SteamBowl** [comment]
I forgot to mention that the issue doesn't affect any other games included in the collection. Testing both MGS2 and 3, they both work perfectly fine, even after the issue with peace walker emerged.

**Comment by SteamBowl** [comment]
May have found a fix for the issue, will comment again and close this if it works.

**Comment by RipleyTom** [comment]
The game uses P2P sockets which require us to bind the port 3658.
For some reason something is stopping the port to be bound on your computer(either an antivirus or some windows security feature?), that's what changed, nothing changed on RPCS3's side.
