### ISSUE TITLE
[Feature Request] Clarification on M1 native vs MacOS native

### ISSUE THREAD

**Issue by Danke-Boi** [RPCS3/rpcs3#12074]
## Quick summary
So, in Activity Monitor, RPCS3 (from the official download on RPCS3.net) runs in "Intel" mode (Rosetta 2). The wording of the website and the video released make it sound like RPCS3 runs natively on M1, not just on MacOS

## Details

<img width="1288" alt="Screen Shot 2022-05-23 at 3 43 50 PM" src="https://user-images.githubusercontent.com/72051710/169894459-9a845060-51f0-4ca0-bf35-432aabecc57d.png">

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
The website, UI, etc.

#### 2. Please tell us, why your feature is important to RPCS3.
RPCS3 is great, and I do not want people to be disappointed, including myself, when getting lackluster performance. Especially when compared to Windows equivalent PCs in terms of performance.
#### 3. Please attach screenshots of the feature implemented in other projects.
<img width="1294" alt="Screen Shot 2022-05-23 at 3 47 52 PM" src="https://user-images.githubusercontent.com/72051710/169894995-34861d11-e902-48bf-90a6-9a101e9b439a.png">

#### 4. Please provide your system configuration:
* MacOS 12.4
* M1
* M1 (7 core)
* 8GB

#### Please include.
* I understand that going from a complicated architecture, to x86, and then to ARM would have performance hits. As such RPCS3 on ARM would be cool, but that isn't what this is about. Specifically, this is to avoid "false claims" per se.

**Comment by RainbowCookie32** [comment]
ARM support on RPCS3 is pretty green for now, so only x86 builds are shipped for now. I don't see any place on the website that says we deliver M1 builds, it just says that they are builds that run on macOS natively. And the video description clearly says that M1 runs under Rosetta

![image](https://user-images.githubusercontent.com/16805474/169895928-88e3eaf8-0761-45cd-9c21-852258b94c82.png)

Not sure where the confusion is coming from here.

**Comment by Danke-Boi** [comment]
Example of people being confused:
<img width="960" alt="Screen Shot 2022-05-23 at 3 55 39 PM" src="https://user-images.githubusercontent.com/72051710/169895967-ccb1b403-98af-4578-b5c2-c650d573ca7f.png">

**Comment by RainbowCookie32** [comment]
First picture: User didn't read the description. From experience I can tell you that you can't workaround that.
Second picture: It says it's running natively on macOS, which is correct. Doesn't even mention M1, not sure where you are getting confused from that.

**Comment by Danke-Boi** [comment]
> ARM support on RPCS3 is pretty green at the moment, so only x86 builds are shipped for now. I don't see any place on the website that says we deliver M1 builds, it just says that they are builds that run on macOS natively. And the video description clearly says that M1 runs under Rosetta 
> Not sure where the confusion is coming from here.

The wording is a little confusing, I for one saw "natively on MacOS" and then "in 2018" and was confused. Also, the quickstart has no disclaimer. Simply states that the minimum OS for Mac is Big Sur 11.6 and the recommended is Monterey 12.0. Also, there is no reference whatsoever to ARM in the quickstart.

**Comment by RainbowCookie32** [comment]
> Simply states that the minimum OS for Mac is Big Sur 11.6 and the recommended is Monterey 12.0. And there is no reference whatsoever to ARM in the quickstart.

And that should give you the indication that ARM CPUs are not quite supported yet, on that same page you can see the minimum requirement for CPUs is any **Intel/AMD x64 CPU.**

**Comment by Danke-Boi** [comment]
> First picture: User didn't read the description. From experience I can tell you that you can't workaround that. Second picture: It says it's running natively on macOS, which is correct. Doesn't even mention M1, not sure where you are getting confused from that.

"Natively" more recently is seen in reference to M1, given that someone with an M1 based computer runs into "Native" vs Rosetta 2 execution often, especially with gaming related topics.


> And that should give you the indication that ARM CPUs are not quite supported yet, on that same page you can see the minimum requirement for CPUs is any **Intel/AMD x64 CPU.**

Understood, but I am saying that there should be a small comment or something along those lines that says "M1 support is not fully implemented yet." or something like that to make it very clear.

**Comment by Danke-Boi** [comment]
<img width="1184" alt="Screen Shot 2022-05-23 at 4 15 28 PM" src="https://user-images.githubusercontent.com/72051710/169898875-498206ef-48b1-4322-a017-d7e9cd2289dc.png">

Something like this.

**Comment by MSuih** [comment]
The Mac build is for x86-64, yes, but surprisingly it is more useful to M1 users as the Intel-based macs can run Windows or Linux for better performance. Also the gaming selection on Mac isn't all that great so many people will be overjoyed to play at least something even though it isn't the best possible way to do so.

>  along those lines that says "M1 support is not fully implemented yet." or something like that to make it very clear

It could cause a lot of confusion among people who aren't great with computers, they might get the impression that M1 isn't yet supported. What they really want to know is if the emulator runs on their system or not, they care very little about what's actually happening under the hood. We're not trying to disguise that the emulator is running on Rosetta, but we're also trying to make it clear that it runs on M1 CPUs.

And since you suggest mentioning Rosetta, should we also mention MoltenVK? It is an translation layer as well and hurting rpcs3 performance compared to native Metal version.

**Comment by Danke-Boi** [comment]
> It could cause a lot of confusion among people who aren't great with computers, they might get the impression that M1 isn't yet supported. What they really want to know is if the emulator runs on their system or not, they care very little about what's actually happening under the hood. We're not trying to disguise that the emulator is running on Rosetta, but we're also trying to make it clear that it runs on M1 CPUs.

Ok, makes sense, thanks for replying gracefully.
