### ISSUE TITLE
[Regression] Emulator crashes when installing PS1 games under linux

### ISSUE THREAD

**Issue by nitroos-ai** [RPCS3/rpcs3#12070]
## Quick summary
When trying to install PS1 classics under linux the emulator crashes.

## Details

The crashes began with #8040 where the emulator crashes with a segfault error [rpcs3-v0.0.9-10237.log](https://github.com/RPCS3/rpcs3/files/8756777/RPCS3.log).

And later in #10201 the emulator began crashing without leaving any trace in log file [rpcs3-v0.0.15-12167.log](https://github.com/RPCS3/rpcs3/files/8756785/RPCS3.log).

Install fine in [rpcs3-v0.0.9-10229.log](https://github.com/RPCS3/rpcs3/files/8756845/RPCS3.log).

## Please provide your system configuration:
* Lubuntu 20.04
* intel i5-4590
* Nvidia GTX 1070 ti
* GeForce 510.60

**Comment by whyman** [comment]
Confirm this still happens in the latest build.


- Gentoo Linux
- Intel i7-3770
- AMD Radeon VII (vega20, LLVM 14.0.3, DRM 3.44, 5.17.7-gentoo-dist) (0x66af)

`/rpcs3-v0.0.9-10212-bc3b70c3` installs fine

**Comment by Megamouse** [comment]
This is useless without a log of the latest master
