### ISSUE TITLE
[Feature Request] Drag-and-drop installation support for ZIP archives that contain both PKG and RAP files

### ISSUE THREAD

**Issue by retroNUC** [RPCS3/rpcs3#12081]
## Quick summary
Drag-and-drop installation support for ZIP files that contain both PKG and RAP files.

## Details
For those that organise their backed-up data according to No-Intro standards, the most common format seems to be a single ZIP file that contains both a PKG file as well as an (optional) corresponding paired RAP file. Installing these requires extra steps in RPCS3, as the user must first extract the PKG/RAP files, drag-and drop both to the RPCS3 window, then delete the extracted files themselves.

Suggesting that both drag-and-drop as well as the 'Install PKG' dialog box supports ZIP files to make it easier for users with data in this format. For each .pkg or .rap file within a ZIP archive, process each as we currently do with individual files.

This could also allow users to potentially bundle up all related packages for one title (game pkg, update pkgs, DLC pkgs, and all corresponding rap files) into a single ZIP archive for even further ease of installation.

**Comment by Megamouse** [comment]
It's not our job to handle your data storage.
Adding this would only bloat the codebase for no reason in my opinion.
