### ISSUE TITLE
Retro City Rampage doesn't start because of SPU recompilation error

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1208]
When starting Retro City Rampage, the games hang at autosave warning screen with the following error message, using LLVM recompiler and ASMJIT :

E {SPU[0x56] Thread (_Multistream SPU Thread)[0x0b3f0]} Exception: Compilation failed
(in file Emu\Cell\SPURecompiler.cpp:36, in function SPURecompilerDecoder::DecodeMemory)

I suspect commit 817fec9684b92005f133f3fa9d6e221b4160d740 ( https://github.com/RPCS3/rpcs3/commit/817fec9684b92005f133f3fa9d6e221b4160d740 ) to be the culprit here since it touches a lot of spu related code.

**Comment by vlj** [comment]
Here is SPUJIT.log content
https://gist.github.com/vlj/31860f88e768cf18944b

**Comment by tambry** [comment]
@vlj Does #1207 fix this problem? It has a lot of changes and improvements to SPU JIT.

**Comment by vlj** [comment]
Fixed with latest master
