### ISSUE TITLE
[Regression] God of War: Ascension only displays a black screen after Epilepsy Warning from #12075 onwards

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#12085]
## Quick summary
Issue as per title. First affected build is 0.0.22-13644. #12075 
![image](https://user-images.githubusercontent.com/4345150/170246065-a472bb41-a4d8-4c87-84b2-4f45aa15ddf7.png)

## Details
Last working build is 0.0.22-13643.
![image](https://user-images.githubusercontent.com/4345150/170246322-17b3c0d4-8b99-4a44-883a-a8515c9bd2a9.png)

## Logs

Not working
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8770395/RPCS3.log.gz)

Working
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8770399/RPCS3.log.gz)

## System configuration
- SYS: 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.86 GiB RAM | TSC: 2.496GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1070 Ti' running on driver 511.79.0.0
- SYS: Firmware version: 4.88

**Comment by solarmystic** [comment]
From discord, it seems like a few other games are also affected like:-

Everybody's Golf
Enchanted Arms (BLES00049)

**Comment by kochetov2000** [comment]
God Of War 3 has the same problem

**Comment by fuhuan416** [comment]
Tekken6 same.

**Comment by robotoboy30** [comment]
Katamari Forever also seems to have a similar issue in that it doesn't move past the second loading screen.

**Comment by elad335** [comment]
#12087

**Comment by solarmystic** [comment]
Closing, since #12087 fixed this
![image](https://user-images.githubusercontent.com/4345150/170298663-0ce239e5-83e9-4778-85cd-93faed66714f.png)
