### ISSUE TITLE
AC Revelations [BLUS30905] OpenGL crash in function scale_image

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12083]
## Quick summary
Sharing some OGL love
Game fails to go ingame with OpenGL

## Details
F {RSX [0x002be84]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\GL\GLHelpers.cpp:555[:3], in function scale_image) (error=0x7e)

		ensure(real_src->aspect() == real_dst->aspect());
#### 1. Please attach RPCS3's lo
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8767176/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
N/A

#### 3. Please attach screenshots of your problem.

https://user-images.githubusercontent.com/60384196/170158243-806345dd-d0f0-44a8-a772-7e0ef796e9a0.mp4

#### 4. Please provide comparison with real PS3.
Goes ingame

#### 5. Please provide your system configuration:
* Windows 11
* R5 3600
* GTX 1660S
* 512.77.0.0

**Comment by kd-11** [comment]
Thanks for testing OpenGL. We don't get many users on OpenGL which leads to many regressions going unnoticed.

**Comment by Darkhost1999** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8792363/RPCS3.log)
Highly unstable with crashes at different spots. Last thing in log commonly trophy interrupt thread. Can not get ingame with OpenGL to see if graphics are working. Vulkan still works fine.

**Comment by Darkhost1999** [comment]
Fixing
`	ensure(real_src->aspect() == real_dst->aspect());`
Exposes
 `W 0:05:08.065907 {PPU[0x1000015] Thread (Trophy Init Thread) [HLE:0x025900dc, LR:0x01c8b650]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x20b5c88, arg=*0x403f98c0, options=0x1)
·! 0:05:08.066091 {PPU[0x1000015] Thread (Trophy Init Thread) [HLE:0x025900dc, LR:0x01c8b650]} sceNpTrophy: sceNpTrophyRegisterContext(): Callback is being called (trp_status=3)`
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8801116/RPCS3.log)
As said before but retest on new OGL Commit

**Comment by Darkhost1999** [comment]
So open a different ticket?

**Comment by Darkhost1999** [comment]
Cause now the game does less than intro only using OpenGL.
Making it impossible to confirm or deny the PR fixes anything.

**Comment by kd-11** [comment]
> So open a different ticket?

For trophy issue? Yes. Unless you have the same error as before, it is a new ticket.

**Comment by kd-11** [comment]
Also we need new logs. The provided one does not show any errors at all, just multiple boots. Avoid starting a game more than once for any submitted logs.
