### ISSUE TITLE
Possible Wipeout HD/Fury Network Regression

### ISSUE THREAD

**Issue by Peduls** [RPCS3/rpcs3#12091]
I am unable to join or host multiplayer games in Wipeout HD/Fury. The wiki page states the multiplayer works by setting your IP/Hosts Switches to "wipeout2048.muis.online.scee.com=185.194.142.4&&wipeout2048.online.scee.com=185.194.142.4" After doing that I am able to connect to the private server and even see other player's records and best times but see no games being hosted in the lobby nor can I host my own.
![NPUA80105_screenshot_2022_05_25_17_55_19](https://user-images.githubusercontent.com/34750422/170419765-8a173c39-2dc3-4aab-8bb0-55787e70e7af.png)
![NPUA80105_screenshot_2022_05_25_18_41_42](https://user-images.githubusercontent.com/34750422/170419807-f3f9c592-42db-48be-838d-7922a9d19ea8.png)

**Comment by Peduls** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8776412/RPCS3.log.gz)

**Comment by RipleyTom** [comment]
From the log it's trying to bind on yourip:1900 and windows says the addr/port is already in use.
Unrelated to rpcs3 and not a regression.
