### ISSUE TITLE
Batman Arkham City stopping emulator took too long.

### ISSUE THREAD

**Issue by mraj143** [RPCS3/rpcs3#12098]
When closing a window an error message pop up referring Thread id = 20000

see this image:
![283734036_540453131078870_254187950296291982_n](https://user-images.githubusercontent.com/106333573/170553319-0950e9fe-6361-4d81-b74c-5f004d09e772.jpg)

same error but thread id different see the screenshot

![Screenshot (7)](https://user-images.githubusercontent.com/106333573/170557194-9306cae8-acae-4910-9d60-ea83b0d9168e.png)

please solve my error Please.

**Comment by YuriNator557** [comment]
Support should be asked for on the discord server or in the forums, this post does not fulfill the guidelines for an issue report
