### ISSUE TITLE
Prince of Persia: The Sands of Time HD [NPEB00341]: sound issues 

### ISSUE THREAD

**Issue by AdadG** [RPCS3/rpcs3#12093]
## Quick summary
The game runs perfectly except it has sound problems, as if the sound is echoing.

## Details
The issue has been known for a few years (judging by the reports, it also happens in the "Trilogy 3D" compilation):

https://forums.rpcs3.net/thread-181459-post-308090.html#pid308090
https://forums.rpcs3.net/thread-173729.html?highlight=Prince

however, it is not present here in GH as an issue, so I consider it would be good if it is not forgotten and if it is possible to find the cause of the problem.

That said, there isn't much to explain. 

#### 0. Make sure you're running with settings as close to default as possible
The game doesn't need any particular options that deviate from the default settings to work.

#### 1. Please attach RPCS3's log.
I consider that a log is not necessary due it is a known problem.

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
Is not a graphical issue.

#### 3. Please attach screenshots of your problem.
Not needed.

#### 4. Please provide comparison with real PS3.
Not needed, the problem is evident and known.

#### 5. Please provide your system configuration:
* OS Windows 10, 21H2, 19044.1706
* CPU Ryzen 5 5600X
* GPU GeForce GTX 1070
* Driver version 512.77
* RPCS3 0.0.22-13651
 
#### Please include.
* Anything else you deem to be important

**Comment by jokoputera** [comment]
Confirmes, audio almost sound inverted, or somekind using Cave / Hall effect

**Comment by jokoputera** [comment]
Please check using this build : https://github.com/RPCS3/rpcs3/pull/12164https://github.com/RPCS3/rpcs3/pull/12164

**Comment by marcoluc97** [comment]
@Megamouse need logs for this? Audio tag

**Comment by Megamouse** [comment]
please try again

**Comment by AdadG** [comment]
Unfortunately the problem persists, both in the PR suggested above and in the latest master version (0.0.22-13771), in all audio formats.
