### ISSUE TITLE
Sleeping and Waking the Steam Deck Terminates Emulation due to RsxAudio Timer Error

### ISSUE THREAD

**Issue by IBNobody** [RPCS3/rpcs3#12106]
## Quick summary
Putting the Steam Deck to sleep and waking it up freezes emulation without the ability to recover. The issue appears to stem from an audio error.

## Details

1. I start PERSONA 5 [BLUS31604].
2. I wait to get to the first in-game screen.
3. I put the Steam Deck to sleep via the power button.
4. I wake the Steam Deck via the power button.
5. Emulaton is frozen.

I have tried disabling audio, but this does not prevent the crash.

Log files show the following logs:

```
·F 0:15:58.467002 {RsxAudioData Thread} SIG: Thread terminated due to fatal error: rsxaudio_periodic_tmr::wait() failed
(in file /run/build/rpcs3/rpcs3/Emu/Cell/lv2/sys_rsxaudio.cpp:759[:4], in function operator()) (errno=4=Interrupted system call)
·W 0:15:58.467097 {RsxAudioData Thread} SYS: Emulation has been frozen! You can either use debugger tools to inspect current emulation state or terminate it.
·! 0:15:58.468343 {Performance Sensor} SYS: CPU Usage: Total: 0.0%, Cores: 27.2%, 0.0%, 0.0%, 0.0%, 0.0%, 0.0%, 0.0%, 0.0%
·! 0:15:58.521714 {RsxAudioData Thread} SIG: Thread time: 0.000991s (0.000000Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:11 unvol:0]; Wait:[0.000s, spur:0]
```

This is the location in the source code of the exception.

https://github.com/RPCS3/rpcs3/blob/608f823516f3e0fe90a06d37232d61ec6759cd77/rpcs3/Emu/Cell/lv2/sys_rsxaudio.cpp#L759

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8788084/RPCS3.log)

#### 5. Please provide your system configuration:
Steam Deck 512 GB

![image](https://user-images.githubusercontent.com/5863888/170741307-e6049dfd-edfc-49aa-9c36-ec24a3d7d9d8.png)

![image](https://user-images.githubusercontent.com/5863888/170741489-fcf38a47-5154-4d69-a59c-9abca28443f1.png)

![20220527112815_1](https://user-images.githubusercontent.com/5863888/170741604-99ebb403-51b4-4c6e-a7f5-a12c4640cde3.jpg)

![20220527112938_1](https://user-images.githubusercontent.com/5863888/170741619-d27c567e-cbe6-4b24-86c7-89b80eed5d50.jpg)

**Comment by IBNobody** [comment]
It should be noted that this isn't the only emulator that had issues with the SD audio. The SD may be disabling the audio device when it goes to sleep and re-adding it when it wakes up. Does RSXAudio handle changing audio devices?

**Comment by AniLeo** [comment]
RSXAudio is not supposed to be used for games, only VSH. Audio backend is automatically picked between games and VSH.

The build from the log file is not the official build, pending test with the official AppImage build or built from the rpcs3-git AUR.

**Comment by IBNobody** [comment]
I get the same error with the latest appimage. I'll post the log shortly.

>RSXAudio is not supposed to be used for games, only VSH. Audio backend is automatically picked between games and VSH.

Does this mean I have a choice in the options somewhere?

**Comment by AniLeo** [comment]
It was removed, it's supposed to be automatically toggled, should be a bug then if you can reproduce on the latest AppImage

**Comment by Vestrel** [comment]
Test with #12111

**Comment by IBNobody** [comment]
> Test with #12111

I'm attempting to build this right now on a HoloISO VM, as pacman is unavailable on a stock Steam Deck SteamOS install. Not sure if this will be successful. Is there an easier way to test this, such as getting an AppImage created?

**Comment by AniLeo** [comment]
PR CD builds an AppImage that you can use

**Comment by IBNobody** [comment]
Thanks. Got it.

This fixed the specific RsxAudio timer failure, but the emulation still freezes with a new error in the log.

`·E 0:00:50.905228 {RSX [0x0038cfc]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x403005A0`

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8791752/RPCS3.log)

**Comment by nitroos-ai** [comment]
Add the option `Log: {sys_rsx: Trace}` in config file than upload the new log file.

**Comment by IBNobody** [comment]
To confirm, I updated config.yml to modify the last line from `Log: {}` to `Log: {sys_rsx: Trace}`

Here is the updated log.

[RPCS3.trace.log](https://github.com/RPCS3/rpcs3/files/8792270/RPCS3.trace.log)

**Comment by IBNobody** [comment]
I'll open a separate issue for the semaphore timeout and reference this issue, as the behavior is still that the emulation is frozen and unrecoverable.
