### ISSUE TITLE
RPCS3 main site or github changelog history Pull Request link

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#12109]
When an RPCS3 new version is released some users open links from https://rpcs3.net/compatibility?b in section Pull Request thus opening an link to changes for an download release.
If user wish see all changes for previous versions need open an link for each Pull Request.

One address link showing all versions changelog is an good solution and is better to read.
Thanks for read.
Have an nice day.

**Comment by Darkhost1999** [comment]
Like this?
![image](https://user-images.githubusercontent.com/60384196/170776518-3f6542c4-f063-4cd1-9d8f-3a82663f589d.png)

**Comment by Darkhost1999** [comment]
I understand there's a language barrier with communicating. I'm thinking that you just want the Github APIs automatically generated list of every commit ever committed.

**Comment by AniLeo** [comment]
This is out of scope for this repo, it's for DAGINATSUKO/www-rpcs3, open it there and I'll check it

**Comment by Augusto7743** [comment]
@Darkhost1999
Exact.

@AniLeo
Thanks for analyzing.
