### ISSUE TITLE
Cubeb: LFE channel is broken in Wipeout HD [NPEA00057]

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#12113]
The LFE sound is broken in Cubeb.
It is fine in XAudio.

Steps to reproduce:
1. Use 7.1 or 5.1 audio downmix setting.
2. Choose Cubeb as audio backend
3. Boot the game, go to the sound options and start the sound test (Press X in the following screen)

![image](https://user-images.githubusercontent.com/23019877/170828697-d59d0e58-f355-4685-8c40-303d3b8beb13.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8791257/RPCS3.log)

**Comment by capriots** [comment]
Can't reproduce, both backends sound fine on my end.
With "broken", do you mean it's just noise? That's what the LFE test audio sounds like on normal speakers. Cubeb mixes the LFE channel into the stereo channels, XAudio doesn't.

**Comment by Megamouse** [comment]
hmm. I guess my speakers were on stereo for some reason.
I just tested with some bluetooth headsets and the LFE buzzes as it should.

You were right, it seems to be just noise on stereo speakers.
The question is: can we "fix" this somehow? (idk what would be more accurate)

Another thing I noticed is that the convert to s16 on Cubeb halfes the volume for some reason, which is not the case on XAudio.

**Comment by capriots** [comment]
I don't think we can do anything there. RPCS3 already has a good downmixer, that's just what happens if you turn it off and leave it to Cubeb. Maybe open an issue on their git as the LFE channel shouldn't be mixed into stereo channels normally.

**Comment by Megamouse** [comment]
Too much work. I'll just keep using XAudio xD
