### ISSUE TITLE
Language selecter is a little.. big.

### ISSUE THREAD

**Issue by Bitwolfies** [RPCS3/rpcs3#12128]
## Quick summary
I don't think the language top bar is meant to be this big.
## Details

![image](https://user-images.githubusercontent.com/65789901/170897176-38a2d6e3-c4df-4b56-ae6b-cb990e0ee10a.png)

System Info: "Arch" Linux, flatpak RPCS3 build version 0.022-1-8b6f68ab. KDE. Might be an issue with KDE's qt theming? RPCS3's theme is set to Skyline (Nightfall)

**Comment by YuriNator557** [comment]
Invalid issue, the flatpak is not an official release.
