### ISSUE TITLE
AppImage auto-updater does not respect portable directories on auto-reboot

### ISSUE THREAD

**Issue by AlfredoRodda** [RPCS3/rpcs3#12131]
## Summary

If there is a directory with the same name as the AppImage plus .home, then $HOME will automatically be set to it. For example, if the AppImage is called rpcs3.AppImage and there is a folder called rpcs3.AppImage.home, this folder would be the data directory. 

Since  #12119, after the auto-updater completes and reboots, it creates new folders at `/home/user/.cache/rpcs3` & `/home/user/.config/rpcs3/`. The original portable directory is ignored and you are presented with the initial "Welcome to RPCS3" setup. 

Closing and relaunching rpcs3.AppImage after the update loads the correct portable rpcs3.AppImage.home directory.

**Comment by Megamouse** [comment]
should be fixed in soon
