### ISSUE TITLE
CMake error when compiling

### ISSUE THREAD

**Issue by KraXarN** [RPCS3/rpcs3#1213]
Compiling on Kubuntu 15.04 x64 with CMake 3.0.2

-- cotire 1.7.3 loaded.
-- Initializing RPCS3_SRC_DIR=/home/kraxarn/Downloads/rpcs3/rpcs3
CMake Error at /usr/share/llvm-3.5/cmake/LLVMConfig.cmake:50 (include):
  include could not find load file:

    /usr/lib/llvm-3.5/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  CMakeLists.txt:87 (find_package)

CMake Error at /usr/share/llvm-3.5/cmake/LLVMConfig.cmake:53 (include):
  include could not find load file:

    /usr/lib/llvm-3.5/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  CMakeLists.txt:87 (find_package)

CMake Error at CMakeLists.txt:121 (llvm_map_components_to_libnames):
  Unknown CMake command "llvm_map_components_to_libnames".

**Comment by Syphurith** [comment]
@KraXarN I'm sorry for that, however please try a newer build of LLVM, or from source. Whenever trying to build rpcs3, I suggest you to read and follow the `.travis.yml` file that is perfect for Ubuntu.

**Comment by KraXarN** [comment]
I get the exact same error with LLVM 3.6, except that is says llvm-3.6 instead of 3.5

**Comment by Syphurith** [comment]
@KraXarN Travis uses the deb from `http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6`. For travis, it would execute `before_install`, `before_script` and `script` to generate the executable. Just start looking at the `before_install`. Every `-` means a seperate shell line. Those are Shell scripts at last.

**Comment by KraXarN** [comment]
That worked fine, thanks! It just had to download 200 mb of updates and then it started compiling, but now it fails with this error instead:

Linking CXX executable ../bin/rpcs3
/usr/bin/ld: cannot find -ledit
collect2: error: ld returned 1 exit status
rpcs3/CMakeFiles/rpcs3.dir/build.make:9315: recipe for target 'bin/rpcs3' failed
make[2]: *** [bin/rpcs3] Error 1
CMakeFiles/Makefile2:260: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Which seems to be related to libmagic and when I try to locate it:

/usr/lib/x86_64-linux-gnu/libmagic.so.1
/usr/lib/x86_64-linux-gnu/libmagic.so.1.0.0

I can open a new issue for this if needed, since it doesn't really have to do with this.

**Comment by Bigpet** [comment]
@KraXarN not sure what could try to link in "edit". Can you try to clean any cmake cache files?

**Comment by KraXarN** [comment]
As I edited in the first post, I googled and found the same, installed it and it compiled and ran.
Also tried running Sonic 2006 as someone else created an issue for which still seem to not work, if needed I can post a log to that one as well, since it seem to give the same error on this newer build in Linux.
Also tried different settings (recompiler etc.) with no luck. Gonna try some other stuff and simpler 2D games.

**Comment by ProfessorKaos64** [comment]
Anyone hitting this thead trying to use clang/llvm-3.8 for Debian, I've continued this in #1610. It appears there were upstream changes that broke the placement/configuration of LLVM. The 3rd revision in Debain Sid appears to have fixed this. Testing now.
