### ISSUE TITLE
Prince of Persia: The Forgotten Sands [BLES00839]: Crashes when attempting to load game

### ISSUE THREAD

**Issue by GOATS2K** [RPCS3/rpcs3#12149]
## Quick summary

I tried creating a new game save, the game starts loading, and RPCS3 freezes up.

## Details
I tested both the PSN version NPEB00774 and the disc version BLES00839 - both crashed with the same fault.

```
E RSX: ERROR: 0:44: 'f32_to_d24' : no matching overloaded function found 
ERROR: 0:44: 'assign' : cannot convert from ' const float' to ' temp highp uint'
ERROR: 0:44: '' : compilation terminated 
ERROR: 3 compilation errors. No code generated.


E RSX: 
F {RSX [0x003f5a4]} SIG: Thread terminated due to fatal error: Failed to compile compute shader
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\VKProgramPipeline.cpp:29[:25], in function compile)
```

#### Please attach screenshots of your problem.
This is where it freezes.

![image](https://user-images.githubusercontent.com/55696338/171683962-6df4280a-dc0d-42d2-87ed-8e36b9770dd3.png)

#### Please provide comparison with real PS3.
I don't have one at hand to compare with.

#### Please provide your system configuration:
* OS: Windows 10, build 19043
* CPU: i7 6950x
* GPU: Radeon RX 5600 XT
* Driver version: 30.0.15021.7000

I tested both build 0.0.22-13712 and the build before it, with firmware 4.86.

[logs.zip](https://github.com/RPCS3/rpcs3/files/8825992/logs.zip)

**Comment by Random-Chain** [comment]
Getting the same issue with God Of War Collection [BCUS98229].
I'm running the flatpak version on Pop!_OS 22.04, had to revert to 0.0.22-1-8b6f68ab Alpha where loading still works.

**Comment by kd-11** [comment]
Some functions were incorrectly deregistered during the first OGL PR. This should be fixed in https://github.com/RPCS3/rpcs3/pull/12151
