### ISSUE TITLE
WWE Smackdown vs RAW 2010 [BLES00651] Black screen

### ISSUE THREAD

**Issue by BlackShadow** [RPCS3/rpcs3#12147]
## Quick summary

It's been a long time since this game isn't working properly and the issue is always ignored. I've been testing the emulator since v0.006 version (i think since 2018) to play this game but no avail. I know you guys fix stuff by priority but please lend this game a hand and make it playable at least.

## Details

When you start a match games goes blank screen, audio plays in background and nothing happens after that. This issue also happens to few other WWE games, fixing this one could be a fix for others as well.

## Log

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8819383/RPCS3.log.gz)

## Please provide your system configuration:
* Win 11 x64 Build 22000
* i9-9900K
* RTX 2080Ti
* NVIDIA 512.95
* 32GB RAM

## Please include.
- Anything else you deem to be important

* Some WWE games having a problem with HUD if you scale screen resolution to 1080p.

* SvR2010 if you also scale screen res to 1080p this issue happens:

![image](https://user-images.githubusercontent.com/30868395/171519083-86ae0816-1af2-40c4-a5a6-0de1052012de.png)

**Comment by YuriNator557** [comment]
Duplicate of #6831, reopen it

**Comment by BlackShadow** [comment]
I think this is fixed.
