### ISSUE TITLE
OpenGl Regression: Jak & Daxter Collection- Gliched Character Texture

### ISSUE THREAD

**Issue by Redven2** [RPCS3/rpcs3#12148]
Main character texture issues after a recent update, 0.0.22-13691.
![unknown](https://user-images.githubusercontent.com/106716786/171530275-bdc7a6c1-a93e-4767-9952-d15f099cdbcb.png)
Previous build (before 0.0.22-13691)
![unknown](https://user-images.githubusercontent.com/106716786/171531683-c152e55e-d26c-4542-ad9f-fcfeb851ad52.png)

**Comment by JimScript** [comment]
What update in particular? It would be helpful to know.

**Comment by Redven2** [comment]
> 



> What update in particular? It would be helpful to know.

The issue first appears in version 0.0.22-13691

**Comment by JimScript** [comment]
Looks like #12114 , guess the fixes broke something.

**Comment by Megamouse** [comment]
missing log file
