### ISSUE TITLE
OpenGl Regression: Overlay icons are black

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#12145]
Master:
![image](https://user-images.githubusercontent.com/23019877/171511012-5de3b376-d13c-43b1-8e44-8f45f90695e1.png)
![image](https://user-images.githubusercontent.com/23019877/171511042-3f4e4f15-26c9-4f56-8a35-1c8e39fd3a1a.png)

Build before #12114:
![image](https://user-images.githubusercontent.com/23019877/171511056-0031e9cb-8c13-43f5-a467-d932f787586c.png)
![image](https://user-images.githubusercontent.com/23019877/171511129-c3731bc2-4f75-415b-a6c3-1a0a9f4d2982.png)

**Comment by kd-11** [comment]
Hmm, could be NV-specific. No issues on AMD from my last tests.

**Comment by RainbowCookie32** [comment]
Can also reproduce on radv, but they aren't black squares

Before that PR:
![image](https://user-images.githubusercontent.com/16805474/171517429-aa4ac3ec-96a4-45fc-b026-02cc602deabd.png)
![image](https://user-images.githubusercontent.com/16805474/171517450-6bb032f2-c09f-4255-a9ba-c427a294f316.png)

After:
![image](https://user-images.githubusercontent.com/16805474/171517218-3ce023be-925d-4946-bd90-ab3ccaf521c3.png)
![image](https://user-images.githubusercontent.com/16805474/171517230-541c0fb6-392e-408e-91ad-8e0c19419141.png)

**Comment by Megamouse** [comment]
yeah seems fixed
