### ISSUE TITLE
OpenGL ACR graphics

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12157]
## Quick summary
Keep in mind the game was intro only before OGL bringup PRs improving both times.
The game suffers from black screens or flickering videos. While the HUD remains normal the entire time.

## Details
9 out of 10 times I get a black screen.
1 out of 10 times I get.
![image](https://user-images.githubusercontent.com/60384196/171859836-c43fd4ad-f3f5-4594-939f-0ca26f30b663.png)
IDK what's worse it working in the menus or not working.
Because when it works in the menu. Ingame gets worse.
Caches only need cleared once but if you don't clear them the game gets progressively worse with each boot until Ezio is swallowed by the darkness.

#### 1. Please attach RPCS3's log.
Game was booted 1 time by me but log reflects multiple boots. IDK if multiple .elfs or what. (Likely not an issue, I believe)
L45 eboot.bin. L292 eboot.bin, actual start of game is like L552 eboot.bin L1675 scimitar_final.self, (I'm guessing that's my update file)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8832589/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
The captures look better than what I saw when I captured them
https://mega.nz/folder/ek4CBDgD#bedm6jONjKvNuZEmugIkRw

#### 3. Please attach screenshots of your problem.
![BLUS30905_screenshot_2022_06_03_07_47_15](https://user-images.githubusercontent.com/60384196/171857626-46b483d7-2c67-452f-9175-0eea76ad9b15.png)
![BLUS30905_screenshot_2022_06_03_07_47_20](https://user-images.githubusercontent.com/60384196/171857629-1d2b8882-0309-43fa-97a6-43ddab5723ce.png)

#### 4. Please provide comparison with real PS3.
I don't have a capture card yet but Vulkan works. So here is RPCS3 Vulkan.
![BLUS30905_screenshot_2022_06_03_09_53_26](https://user-images.githubusercontent.com/60384196/171878936-98a90c5e-9b05-43ad-b532-ca34e95fd138.png)
![BLUS30905_screenshot_2022_06_03_09_53_31](https://user-images.githubusercontent.com/60384196/171878943-81d20462-9d73-42eb-b640-3fe7040735fa.png)
![BLUS30905_screenshot_2022_06_03_09_53_37](https://user-images.githubusercontent.com/60384196/171878945-816c3a35-165a-4066-b49e-71b169671b7f.png)

#### 5. Please provide your system configuration:
* Win 11
* R5 3600
* GTX 1660S
* 512.95

<details>
<summary> Edit remove not an issue </summary>

When you boot ACR and play the game a little bit. 1st things first -> F Thread terminated due to fatal error: Memory mapping failed - blame Windows. So I clear my caches and boot the game to fix blame windows. (only required the first time after check for updates)
log spams
```
E {RSX [0x001e4c0]} RSX: FS exports depth component but depth test is disabled (INVALID_OPERATION)
```

</details>

**Comment by kd-11** [comment]
> E {RSX [0x001163c]} RSX: FS exports depth component but depth test is disabled (INVALID_OPERATION)
E {RSX [0x001d8bc]} RSX: FS exports depth component but depth test is disabled (INVALID_OPERATION)

This is a game bug, not an emulator bug. Nothing to fix there.

As for the other issues. Does vulkan work correctly with this game? I'm trying to determine whether its a backend issue (OpenGL) or a system issue with the emulator itself.

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/12162

**Comment by Darkhost1999** [comment]
https://user-images.githubusercontent.com/60384196/171979251-b403f051-1de6-4b08-b869-1925f8737d1e.mp4
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8836940/RPCS3.log)

**Comment by kd-11** [comment]
It's fixed now.

**Comment by Darkhost1999** [comment]
This issue is fixed by PR
![Screenshot 2022-06-04 051113](https://user-images.githubusercontent.com/60384196/171994873-5985be3a-f09d-4ade-98e3-8c9422bc74ac.png)
![Screenshot 2022-06-04 051131](https://user-images.githubusercontent.com/60384196/171994874-1caac5f2-fd5b-46aa-beb4-3ccd0d66ecb9.png)
Last thing is game freezes which is not this ticket. I do not feel like opening a new ticket without exploring settings first though and I am just going to play using vulkan after ACB.
![Screenshot 2022-06-04 051226](https://user-images.githubusercontent.com/60384196/171994893-117a6d41-4314-48db-ad0c-be5ab8b4a4e2.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8837455/RPCS3.log)

Thanks for all your work. As long as there are no regressions my entire library of games can be played with OpenGL. Compatibility list withstanding.
