### ISSUE TITLE
[Regression] Resident Evil Code Veronica. Problems with shadows on OpenGL

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#12154]
How it looks on Vulkan and PS3 and looked on OpenGL before #12114 
![NPUB30467_screenshot_2022_06_03_11_32_01](https://user-images.githubusercontent.com/22906342/171819014-6e9c894b-202e-4405-8d5f-c38f2e76efd8.png)

How it looks on OpenGL after #12114 
![NPUB30467_screenshot_2022_06_03_11_30_05](https://user-images.githubusercontent.com/22906342/171819005-2d4d6181-6a3f-475d-bc48-99cc635e4401.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8830887/RPCS3.log.gz)
[NPUB30467_20220603113025_capture.zip](https://github.com/RPCS3/rpcs3/files/8830888/NPUB30467_20220603113025_capture.zip)

[OpenGL RenderDoc capture](https://drive.google.com/file/d/1FygzwXA6xs1q81oi9-fjUiJLEL8VWSyI/view?usp=sharing)

[Vulkan RenderDoc capture](https://drive.google.com/file/d/1kyTmQgYWIgXSZ5izLScgkG9H988gBGcn/view?usp=sharing)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/12162

**Comment by Realmantik** [comment]
Fixed with part 3
