### ISSUE TITLE
[Regression] Skate 3 BLES00760 Black Flashing / Textures Flashing InGame

### ISSUE THREAD

**Issue by courentheprod** [RPCS3/rpcs3#12158]
## Quick summary
Weird black flashing in textures, causes major slowdown in fps also.

## Details
In 13604 the game played normally for me, as soon as 13626 came the game gained major graphical issues: black flashing in textures (making it unplayable) + my fps would usually be 40-60 (old version) then the update came and my frames dropped all the way to 10fps. (+ this happens everywhere for me ingame, no matter what map i play on)

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
The build that caused issues for me: https://github.com/RPCS3/rpcs3/pull/12020 (0.0.22-13626-ec2d5298 Alpha)

Logs: [RPCS3 2.log](https://github.com/RPCS3/rpcs3/files/8833262/RPCS3.2.log)
regression > [RPCS3.log](https://github.com/RPCS3/rpcs3/files/8833263/RPCS3.log) 

RSX Capture
[BLES00760_20220603095651_capture.rrc.zip](https://github.com/RPCS3/rpcs3/files/8833269/BLES00760_20220603095651_capture.rrc.zip)

Screenshots: 
<img width="1277" alt="Screen Shot 2022-06-03 at 10 11 24 AM" src="https://user-images.githubusercontent.com/96850799/171882035-e5378b25-5b5b-4ea4-a602-c903084c549c.png">
<img width=
<img width="1277" alt="Screen Shot 2022-06-03 at 10 11 24 AM" src="https://user-images.githubusercontent.com/96850799/171882241-51c5674f-ec63-4b1f-95f2-d7e6b215df43.png">
"1270" alt="Screen Shot 2022-06-03 at 10 11 24 AM 1" src="https://user-images.githubusercontent.com/96850799/1718
<img width="1267" alt="Screen Shot 2022-06-03 at 10 11 02 AM" src="https://user-images.githubusercontent.com/96850799/171882064-1fbe1494-4dc9-413c-9c07-fa8fc7c1d08d.png">

#### 5. 
![realps3](https://user-images.githubusercontent.com/96850799/171882579-0e95853b-32df-4b10-8ba2-082111cb3fef.jpeg)
+ im in the exact same area as this person (megapark in skate 3)

#### 6. Please provide your system configuration:
* OS: MacOs Monterey 12.4
* CPU Apple M1 Pro
* GPU M1 Pro 
* Driver version idk this
* etc.

####
* + the newest version has the same issues for me (even with default settings)
heres a video with comparing 13604 with the newest build : 
https://drive.google.com/file/d/1XNPkpj-BMg7HCnpQ9n0Sb46IhUnIeZ56/view?usp=sharing

**Comment by courentheprod** [comment]
is there anytime this issue will get fixed? or never?

**Comment by tamburro92** [comment]
Similar issue with MGS IV, last build v0.0.23-13876 have problem with texture, instead [0.0.22-13549] has no issue

**Comment by Sam-Belliveau** [comment]
I noticed that whether your in low power mode or not has a big effect on the look of the game. I have an M1, not an M1 Pro.

### Normal Mode:
![Normal Mode](https://user-images.githubusercontent.com/28713194/183265397-dd4e9afe-cfdd-438b-85e7-89eb517915cc.png)

### Low Power Mode:
![Low Power Mode](https://user-images.githubusercontent.com/28713194/183265410-dd4191ef-02df-4f2d-a1d1-c4cc80880a73.png)

Please ignore the resolution change I was trying to get the game to a playable state.

**Comment by courentheprod** [comment]
Wish it worked for me :(  tried it, it just ended up looking the same.

**Comment by tamburro92** [comment]
<img width="1281" alt="Schermata 2022-08-10 alle 12 21 24" src="https://user-images.githubusercontent.com/18575612/183878373-18c96ec5-3dd3-4e24-bcbd-3a7935453a15.png">
Same problem switching on lower power mode, same result on MGS IV

**Comment by tamburro92** [comment]
#12020

**Comment by dimavasilenco** [comment]
> I noticed that whether your in low power mode or not has a big effect on the look of the game. I have an M1, not an M1 Pro.
> 
> ### Normal Mode:
> ![Normal Mode](https://user-images.githubusercontent.com/28713194/183265397-dd4e9afe-cfdd-438b-85e7-89eb517915cc.png)
> 
> ### Low Power Mode:
> ![Low Power Mode](https://user-images.githubusercontent.com/28713194/183265410-dd4191ef-02df-4f2d-a1d1-c4cc80880a73.png)
> 
> Please ignore the resolution change I was trying to get the game to a playable state.

Hey - sorry, I only just got RPCS3, I have the same issue - how do you enter low-power mode? I tried googling it and still struggle a bit, thank you!

**Comment by ppamorim** [comment]
I have the same issue on my M1 Pro.

**Comment by Zahnstochermann** [comment]
Same here on Macbook Air M1

**Comment by kd-11** [comment]
Please check if this build fixes it https://cirrus-ci.com/task/6605616785915904

**Comment by LoKKeR96** [comment]
> Please check if this build fixes it https://cirrus-ci.com/task/6605616785915904

It fixed the graphic issue for me on MacBook Pro M2 Pro but the game freezes and then RCPS3 crashes at some point during gameplay.

**Comment by kd-11** [comment]
For some reason I remembered incorrectly and thought the fix branch did not work. I'll upstream the changes.

**Comment by kd-11** [comment]
Fixed by this PR: https://github.com/RPCS3/rpcs3/pull/13969 which upstreams the changes from the test build.
