### ISSUE TITLE
Macos downlod link

### ISSUE THREAD

**Issue by kofiho** [RPCS3/rpcs3#12156]
Hello there seems to be a problem with the downlod link on your website concerning macos dmg file. It says 0 MB as well as links to error gifhub page :/ is there some problem?

**Comment by ArbestRi** [comment]
I got my build on Appveryor so I can test LBP 1 on my low-end M1 processor.

**Comment by AniLeo** [comment]
Wrong repository, but I'll fix it as soon as possible
