### ISSUE TITLE
[Regression] Opengl black lines in Assassin's Creed IV: Black Flag

### ISSUE THREAD

**Issue by readywer** [RPCS3/rpcs3#12155]
The #12114 broke the the graphics and #12151 won't fixed it.

![Képernyőfelvétel (999)](https://user-images.githubusercontent.com/90259918/171832988-8c76d414-5e46-47c2-b37a-d4b1209692b9.png)
log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8831504/RPCS3.log.gz)

![Képernyőfelvétel (1000)](https://user-images.githubusercontent.com/90259918/171833006-e1ba4416-abba-4450-85dd-ab08eef13911.png)
log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8831512/RPCS3.log.gz)

![Képernyőfelvétel (998)](https://user-images.githubusercontent.com/90259918/171832973-332f3a28-4a47-4061-a062-1ab351b51e61.png)
log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8831516/RPCS3.log.gz)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/12162

**Comment by readywer** [comment]
> Retest with #12162

Fixed with part 3
