### ISSUE TITLE
Error while installing GTA V

### ISSUE THREAD

**Issue by leonardo5380** [RPCS3/rpcs3#12150]
While trying to install GTA V, the emulator crashes and gives the error:

`F {PPU[0x1000000] Thread (main_thread) [0x00015bf8]} VM: Access violation reading location 0x14 (unmapped memory)`

Can anyone help?

### System requirements

Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz 
NVIDIA GeForce MX110 (Has updated driver)
8 GB RAM
Windows 10

### Log

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8826407/RPCS3.log)

**Comment by Jonathan44062** [comment]
You again? No help with pirated games
Buy the game and dump the games files yourself
