### ISSUE TITLE
Earthworm Jim HD [NPEB00226] Fails to launch When Audio Format is Stereo

### ISSUE THREAD

**Issue by Razor221** [RPCS3/rpcs3#12168]
## Details
The game used to start and play quite well. However 0.0.22-13712 version onwards, the game fails to start. rpcs3 log states " E SYS: Stat: 'cellAudioOutConfigure' failed with 0x8002b241 : CELL_AUDIO_OUT_ERROR_ILLEGAL_CONFIGURATION [x43787663]" which i think has something to do with audio out.

I experimented with the "Audio Format" setting in the "Audio" part of the configuration and this game only starts when the "Audio Format" is set to "Surround 5.1" if set to any other option the game fails to start. ,

On version 0.0.22-13712 setting the "Audio Format" to "Surround 5.1" fixes the problem with no noticeable problems. 

However, with the "Surround 5.1" option, on version 0.0.22-13734 which is the latest version at the time I was writing this report the game starts but has no audio.

Version 0.0.22-13696 works properly I attached both the working latest version and broken first versions log files.
[RPCS3.log_working.gz](https://github.com/RPCS3/rpcs3/files/8838893/RPCS3.log_working.gz)
[RPCS3.log_broken_13712.gz](https://github.com/RPCS3/rpcs3/files/8838894/RPCS3.log_broken_13712.gz)

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.22-13712

#### 6. Please provide your system configuration:
* OS = Windows 11 Pro
* Intel i7 97000k
* Nvidia GTX 1080 Ti
* Driver version = 512.95

**Comment by capriots** [comment]
Should be fixed by #12164.
In the meantime, you can just use Surround 5.1. The game doesn't use any of the surround channels at all so you should be fine.

**Comment by Razor221** [comment]
@capriots nope even the latest 0.0.22-13735 version didn't fix the problem. Only Surround 5.1 option works at the moment. However, playing the game with the Surround 5.1 option has no noticeable problems so it's a proper workaround I guess. 

I also reported that in the 1st post the sound didn't work but the sound works correctly.

**Comment by capriots** [comment]
The PR isn't merged yet.

**Comment by Megamouse** [comment]
Please try again

**Comment by Razor221** [comment]
Version 0.0.22-13745 fixed the problem. Now all of the Audio Format options work correctly.
