### ISSUE TITLE
gran turismo 5 freezing at startup after updating from 1.00 to 2.17

### ISSUE THREAD

**Issue by swampfrickingfish** [RPCS3/rpcs3#12163]
hello, i wanted to play gran turismo 5 but after i was updating, it would freeze and then a error pops up. it says fatal error and the thread id is 30076.   my specs: 

AMD Ryzen 7 5700U

gtx 1650

16 gigs of ram

currently running windows 11

**Comment by B1ackDaemon** [comment]
Not a valid bug report. Please, properly fill template, provide detailed issue description and include log.
