### ISSUE TITLE
Emulator crashes

### ISSUE THREAD

**Issue by EvilPlayer1** [RPCS3/rpcs3#12176]
## Quick summary
Fatal error.
## Details
Emulator crashes, when you press "save" in settings menu.
#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8840307/RPCS3.log)
#### 3. Please attach screenshots of your problem.
![Screenshot 2022-06-05 19-04-14](https://user-images.githubusercontent.com/90133207/172059534-79892740-7166-4e42-bcda-65e50bacbd3c.png)

**Comment by Megamouse** [comment]
attach the config file that crashes please

**Comment by EvilPlayer1** [comment]
> attach the config file that crashes please

[config.txt](https://github.com/RPCS3/rpcs3/files/8845622/config.txt)

**Comment by Megamouse** [comment]
I added a fix in #12186 .
It crashes because your audio provider is set to rsx audio, which leads to an update of the rsx audio config even if the config data is not initialized.
The fix is to check for initialization and skip the update if necessary.
