### ISSUE TITLE
[BLUS30264] regression starting from #12114

### ISSUE THREAD

**Issue by raingart** [RPCS3/rpcs3#12171]
When starting the game AFRO SAMURAI [BLUS30264]
black screen appears

by iterating through versions, I found out that the latest working version is 0.0.22-13670

Unfortunately, there are too many changes ([#12114](https://github.com/RPCS3/rpcs3/pull/12114)) for me to be able to find out the reason:

![image](https://user-images.githubusercontent.com/13064767/172040963-9fe6ba9d-96c7-405e-b3d4-e88bb92e64ca.png)

os: win10(1809), rx488, xeon-2640v3(TSX-active)

p.s. Sorry for off topic. But I couldn't find any information other than [link](https://rpcs3.net/blog/2020/08/21/hardware-performance-scaling/). RSX is a soft analogue of TSX? And with TSX active, shouldn't it be used? Or maybe use in parallel?

**Comment by YuriNator557** [comment]
Missing log file

**Comment by raingart** [comment]
broken [log v0.0.22-13691.zip](https://github.com/RPCS3/rpcs3/files/8839535/log.v0.0.22-13691.zip)

working [log v0.0.22-13670.zip](https://github.com/RPCS3/rpcs3/files/8839538/log.v0.0.22-13670.zip)

**Comment by YuriNator557** [comment]
Have you tried on the latest release? That error should have been fixed by now

**Comment by raingart** [comment]
yep v0.0.22-13734
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8839568/RPCS3.log.gz)

**Comment by raingart** [comment]
[v0.0.22-13734 RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8839569/v0.0.22-13734.RPCS3.log.gz)

**Comment by raingart** [comment]
I can give access via anydesk if you want. Send email if needed

**Comment by sampletext32** [comment]
@raingart 
Answer to your offtopic is pretty simple, but for later questions please use discord server.
TSX is Intel's processor capability.
RSX is PS3's graphics adapter.
So there is like no connection between them.
For technical nuances you better ask in discord.

**Comment by kd-11** [comment]
This crash was fixed days ago by https://github.com/RPCS3/rpcs3/pull/12151

**Comment by kd-11** [comment]
No need to close this yet. The game still does not boot with access violation. It's just pointing to the wrong PR. Basically there have been 2 regressions here, one is fixed, the other is still there in master.

**Comment by kd-11** [comment]
Broken by https://github.com/RPCS3/rpcs3/pull/12112
This is testable by using OpenGL renderer instead of vulkan which had an unrelated regression between 0.0.22-13691 and 0.0.22-13727.
First actually broken build here is 0.0.22-13712.
Tagging @Megamouse

**Comment by raingart** [comment]
I'm sure the 0.0.22-13691 build was not working. I did a clean reinstall of the versions just to be sure. Starting with it ver, I lost the message about compiling shaders.You may be saying that the 2nd bug mentioned appeared in a later version.
