### ISSUE TITLE
Graphical issue with water in Dirt 2

### ISSUE THREAD

**Issue by ChwaraeTeg** [RPCS3/rpcs3#12189]
## Quick summary
There is an issue with water reflections appearing brightly colored in the Dirt 2 game. 

## Details
There is an issue with water reflections (e.g. puddles) appearing bright and multi-colored in the Dirt 2 game.  The expected behavior would for it to look more like water with reflected colours from the surrounding scenery. Attached examples are from the demo version, but compatiblity reports state it is an issue in the full game also.

#### 0. Make sure you're running with settings as close to default as possible
Issue occurs with all settings default - both screenshots and captures are with these settings. 

Tried turning on Write Color Buffers, however this causes the game to crash completely when loading the race (repeated multiple times with and without WCB, everytime it would load to the race fine with the setting off, and crash with it switched on). 

Also tried changing from Vulkan to OpenGL. This seems to cause a crash before going in-race both with and without WCB on.

#### 1. Please attach RPCS3's log.
Write Color Buffers Off
[wcboff.log.gz](https://github.com/RPCS3/rpcs3/files/8847759/wcboff.log.gz)

Write Color Buffers On (Emulator crashes)
[wcbon.log.gz](https://github.com/RPCS3/rpcs3/files/8847760/wcbon.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.

Pre-race intro
https://mega.nz/file/DUtEBYRb#l1qDWPY5rfYWI6lkG2aqDnYYZ9_JAS3-TYG-5XqXbjo

In-race
https://mega.nz/file/SF8hUCaC#3A45InRm5s1uUcWqaJ4NSU5VaxaAT_WP5RXz21fw4Hs

#### 3. Please attach screenshots of your problem.

Pre-race intro (bottom-right of screenshot)
![2022-06-06 20_44_06-FPS_ 30 01 _ Vulkan _ 0 0 22-13758 _ DiRT 2 Demo  NPUB90294](https://user-images.githubusercontent.com/104720038/172242803-2624518b-fe6f-44e9-9cbc-abc017399017.png)

In-race (left side of screenshot)
![rsxcap](https://user-images.githubusercontent.com/104720038/172242785-15c33f9e-a81b-4357-8957-4b71d8c95771.png)

#### 5. Please provide your system configuration:
System configuration:

    OS - Windows 10 21H2
    CPU Intel Xeon E3-1240 v5
    GPU NVIDIA GeForce GTX 1060 6GB
    Driver version 512.77.0.0

#### Please include.
* Anything else you deem to be important

**Comment by kd-11** [comment]
The graphical issue is indeed fixed when using WCB. I've made a small change to avoid the crash when it is enabled.
