### ISSUE TITLE
ps3 Dualshock3 not being read

### ISSUE THREAD

**Issue by demolitiondoge** [RPCS3/rpcs3#12199]
for the last week my DualShock three has been working completely fine but during the last rpc3 update it didn't work. I know my controller still works because mmjoystick is still reading it. The only problem with using mmjoystick is the y axis is inverted on both joysticks. 

i have a new 3080ti (only have had it for 3 months) on windows ten with a intel core i9 10850K cpu @ 3.60Ghz

**Comment by Darkhost1999** [comment]
No log, no steps to reproduce, just a statement saying my dualshock 3 stopped working.

- How is the controller connected? Wired or wireless?

- Are you using RPCS3 native dualshock 3 handler?

- Are you using Nefarious's dshidmini?
(If wireless) Do you have the latest BTHPS3 installed from the Nefarious DSHidmini installation guide?

- Are you using SCPToolkit?
This is Legacy software and advised by the developer(s) that made scptoolkit not to use this software.

I can assume you're using wired and RPCS3's Dualshock 3 handler. But there isn't anything to confirm that steam isn't eating the inputs or anything else is interfering with the communication of the drivers.

**Comment by MilkManEX** [comment]
Same issue, actually. Was working until 13745, update 13750 stopped it. Reverting to 13745 returns DS3 to normal function.

E DS3: check_add_device: hid_get_feature_report 0x0 failed! result=62, buf[0]=0x0, error=Success x3 when refreshing handler on any revision after 13745. Log file attached
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8864146/RPCS3.log)
