### ISSUE TITLE
Tales of Xillia （BLJS10120）PPU thread setting crash

### ISSUE THREAD

**Issue by HIRO0132** [RPCS3/rpcs3#12196]
## Quick summary
crashes Missing Audio FIX, recommended by WIKI
## Details
This game has a bug that the audio doesn't play frequently when playing.
The fix is ​​stated in WIKI that changing the PPU thread count from 2 to 1 will improve it.
However, with this setting, the current version of RPCS3 will always crash after compiling the PPU.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8858120/RPCS3.log)
#### 4. Please provide comparison with real PS3.
audio crash itself does not occur on the real PS3
#### 5. Please provide your system configuration:
Since it is written in the log file, it will be omitted.
#### Please include.
It seems that the same issue has been reported by multiple users
link:https://forums.rpcs3.net/thread-177361-page-16.html

There are reports that setting the PPU thread to 1 will reduce performance, so I hope that the audio crash bug itself will be fixed if possible.

**Comment by elad335** [comment]
Still an issue?

**Comment by HIRO0132** [comment]
Yes, the same as when I posted the issue.
With the default settings, the battle background music stops and crashes on loading at startup if the PPU thread is set to 1.
Version is 0.0.24-14112.
If you need a log, please contact me.

**Comment by elad335** [comment]
No I meant the missing audio with 2.

**Comment by HIRO0132** [comment]
Yes, same as when I posted the problem.
When I set the PPU thread to 1, it crashes at the load screen at startup. With the default settings, the battle BGM stops after 10 minutes of play. (but the music comes back after the battle is over)
The version is 0.0.24-14112.
Let me know if you need a log.

**Comment by elad335** [comment]
Test with #13917

**Comment by ElainaWanderer** [comment]
The comment was back in May 28, it is now 05-december 23
Just wanted to report that setting the PPU thread to 1 still doesn't load the startup sequence for BLJS10120

**Comment by elad335** [comment]
Ppu thread 1 is a hack, PS3 has 2.

**Comment by elad335** [comment]
I'd rather have an issue about the missing audio when set to 2.
