### ISSUE TITLE
Game freezing after intro cutscene

### ISSUE THREAD

**Issue by BrokenBastard** [RPCS3/rpcs3#12197]
I recently got a new PC, figured I'd do an old favorite to help unwind after a long day. Unfortunately the game, Dynasty Warriors Gundam, only gets as far as finishing the intro cutscene. Then it freezes regardless of if I have a recording program open or not.

According to the RPCS3 compatibility list it should work, everything says it's fully functional. And I certainly know my emulator goes through Heavenly Sword and Wolverine Origins with no problem. None of the setting changes I tried seemed to have any effect, Vulcan and Open GL are equally baffled by this game. At best Vulcan seems to record right side up while Open GL records upside down, and both hang up at the same point, just as the intro cutscene fades to black. I tried numerous custom openings but nothing made any progress after the cutscene, and I've seen nothing that shows Dynasty Warriors Gundam needs some special settings to run.

I have an NVIDA RTX 3070, AMD Ryzen 7 5800X 8-Core Processor 3.80 GHz, and 32.0 GB RAM. By all accounts this machine runs circles around what my previous six year old computer could do.  When I'm running the game itself I just see green messages that say everything's working. When I shut the game down I get these three messages.

E SYS: Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x318032]

E SYS: Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x39754]

E SYS: Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x158800]

Is this a regression or just something I can fix with a simple setting change that I don't know about yet?

**Comment by YuriNator557** [comment]
Log file is missing

**Comment by BrokenBastard** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8861678/RPCS3.log.gz)

I believe this is the most recent log of the most recent attempt.

**Comment by YuriNator557** [comment]
Multiple settings that deviate from defaults, reset your settings to default and re-test

**Comment by BrokenBastard** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8864265/RPCS3.log.gz)

Just tried it after setting it to defaults. It's running well enough to actually go through gameplay. Thanks, should have tried that first apparently, though there's some odd hiccups, especially whenever there's some dialogue for some reason. Nothing bad enough to crash it, but the game noticeably stops for a fraction of a section when the next line of dialogue triggers, continues smoothly, then stops as it processes the next bit of dialogue. I probably need to mess with the settings at least a little to get some better performance, but getting it running at all was the priority.
