### ISSUE TITLE
God of war 3 game stuck

### ISSUE THREAD

**Issue by Saleem39450** [RPCS3/rpcs3#12201]
## Details

The game God of War 3 starts correctly but stuck in matter of minutes just after the ending of cutscene. The game booted with the default settings except the frame limit is set to off and anti aliasing is disabled in the GPU tab and in CPU tab enable SPU loop detection has checked. rest of the settings are same. the game stuck and not start to continue so I have to close the emulation.

When I was using rpcs3-v0.0.22-13763-64616f14_win64 version the game starts correctly and also it was playable but my player falls down and dead whenever Gaia place her hand on the mountain again. Even somehow I crossed that but its frequently stuck.

In new version Build 0.0.22-13764 in this version also same problem but the graphics are delaying more here. the graphics produced are not completely shown for example when the game prompts to press the o key then the key box appears first then the letter (O/X/triangle/Square) in the box.

The Game God of War 3 (BCUS98111) is tested in both v1.00 and 1.03

Here I am attaching log file of rpcs3
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8871012/RPCS3.log)

Screenshots when the game stucks
![GOW 3](https://user-images.githubusercontent.com/107191847/172865037-27dde9ba-dfca-4d12-9b73-cd915a776a67.jpg)
![GOW 3 Full](https://user-images.githubusercontent.com/107191847/172865068-6abae93d-d025-4255-867d-70c10f907592.jpg)
![GOW 1](https://user-images.githubusercontent.com/107191847/172865111-53d896cf-9430-4b58-b1eb-0110c98ecf73.png)
![Gow 2](https://user-images.githubusercontent.com/107191847/172865157-e88824c9-4098-4b08-a5df-e4d30ea9f4e4.png)

#### 5. System configuration:
* OS - Windows 11 Home
* CPU - Intel i5 1135G7
* GPU - Intel iris Xe
* Driver version - Intel® Graphics Driver 30.0.101.1994 for Xe Dedicated, 6th-12th Gen Intel® Core™ Processor Graphics

**Comment by AniLeo** [comment]
Wrong settings being used, not the ones recommended in the wiki page for the game, closing as Invalid as this is normal with defaults
