### ISSUE TITLE
Dirt 3 freezes midgame

### ISSUE THREAD

**Issue by Jerett-franklin** [RPCS3/rpcs3#12210]
<img width="1436" alt="Captura de Pantalla 2022-06-10 a la(s) 1 15 43 p m" src="https://user-images.githubusercontent.com/18011722/173144563-1392a826-4c7c-408a-bbe2-4d023d8ed103.png">
<img width="1437" alt="Captura de Pantalla 2022-06-10 a la(s) 1 15 58 p m" src="https://user-images.githubusercontent.com/18011722/173144578-9feb2f05-5bbd-405e-a5a6-3229eae065a2.png">
<img width="1439" alt="Captura de Pantalla 2022-06-10 a la(s) 1 16 21 p m" src="https://user-images.githubusercontent.com/18011722/173144583-22bd2d64-bf5c-4f13-938a-e3153bbf3c4b.png">
<img width="1438" alt="Captura de Pantalla 2022-06-10 a la(s) 1 16 34 p m" src="https://user-images.githubusercontent.com/18011722/173144585-9c261892-bb70-4704-92ec-ee86d4c56b08.png">
<img width="1440" alt="Captura de Pantalla 2022-06-10 a la(s) 1 16 48 p m" src="https://user-images.githubusercontent.com/18011722/173144586-0bf755c3-24e5-450e-9394-59b193f7815e.png">
<img width="314" alt="Captura de Pantalla 2022-06-10 a la(s) 1 22 05 p m" src="https://user-images.githubusercontent.com/18011722/173145244-da4683eb-d975-4df6-bc30-dd21d75d47f4.png">

<img width="1437" alt="Captura de Pantalla 2022-06-10 a la(s) 1 16 59 p m" src="https://user-images.githubusercontent.com/18011722/173144588-80ef3644-bfaa-41ee-9dbc-a60bbc300984.png">
<img width="1440" alt="Captura de Pantalla 2022-06-10 a la(s) 1 17 07 p m" src="https://user-images.githubusercontent.com/18011722/173144590-c6e20955-48fb-4daf-a6aa-da43c5b40fcc.png">
<img width="1440" alt="Captura de Pantalla 2022-06-10 a la(s) 1 17 25 p m" src="https://user-images.githubusercontent.com/18011722/173144592-44ae7db0-ee1d-4d42-80d0-2cc06cdbfe0f.png">

**Comment by Jonathan44062** [comment]
Upload a log file instead of many screenshot of your settings please

**Comment by Jerett-franklin** [comment]
Why doesn't the guidelines specify that? I'm good, thanks I have enough trolls in my life

**Comment by Jerett-franklin** [comment]
Hmmm, now that's strange. I was able to actually get past the part that didn't wanna load. Soon after I left that comment someone in the library got up and left. I know I probably have the bare minimum specs but yeah it's a shame that even the macs themselves are open source. Thanks for your concern you all!

**Comment by Darkhost1999** [comment]
I think you deleted something when creating your issue report

https://github.com/RPCS3/rpcs3/blob/master/.github/ISSUE_TEMPLATE/2-bug-report.md

Nobody is trolling you. Just need to edit your issue with the information we can use.
If you're just trying to ask for help try the RPCS3 discord or official forums support page.

**Comment by Jerett-franklin** [comment]
Yeah, i'm not clicking on that link. Thanks! I was just trying to support y'alls resume efforts making this emulation being a beta tester but that doesn't appear to be the motive. I know for a fact I didn't delete anything. When I was taking the screenshots I had to leave one out because I didn't catch the whole configuration screen (if you needed to know)
