### ISSUE TITLE
Crash on Hitman The Collection

### ISSUE THREAD

**Issue by BentoAldo** [RPCS3/rpcs3#12214]
## Quick summary
On Hitman the collection, when a guard detected me early in the game, the game crashed.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
* Run the game until you find the issue.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](<img width="1683" alt="Captura de Pantalla 2022-06-12 a la(s) 01 16 01" src="https://user-images.githubusercontent.com/40668597/173217154-698c9550-40fa-4c90-b609-f2dfeec28155.png">)
	On Linux it will be in ```<img width="1683" alt="Captura de Pantalla 2022-06-12 a la(s) 01 16 01" src="https://user-images.githubusercontent.com/40668597/173217020-54c32d3b-f12c-4f70-b4fe-a4a0709b2be1.png">``.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc.
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 5. Please provide your system configuration:
- SYS: RPCS3 v0.0.22-13782-5c216026 Alpha | HEAD
- SYS: VirtualApple @ 2.50GHz | 10 Threads | 16.00 GiB RAM | TSC: 1.000GHz
- SYS: Operating system: macOS, Version: 12.4.0
- SYS: Current Time: 2022-06-12T01:17:25
- RSX: Found vulkan-compatible GPU: 'Apple M1 Pro' running on driver 0.2.894
- SYS: Firmware version: 4.89

#### Please include.
* Anything else you deem to be important

**Comment by AniLeo** [comment]
Invalid issue, report never completed, closing as Invalid
