### ISSUE TITLE
Uncharted 2 regression

### ISSUE THREAD

**Issue by coolllman** [RPCS3/rpcs3#12217]
Pr #12182 broke uncharted 2, freezes on load level, before this pr all work good
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8885738/RPCS3.log)

**Comment by YuriNator557** [comment]
Missing log on previous and broken versions

**Comment by coolllman** [comment]
Log before PR
13773
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8885769/RPCS3.log)
Log broken PR
13774
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8885776/RPCS3.log)

**Comment by jokoputera** [comment]
Also Uncharted 1, ingame freeze minute after load level

**Comment by YuriNator557** [comment]
try #12219

**Comment by coolllman** [comment]
Fixed, thank you!
