### ISSUE TITLE
nvidia Vulkan Queue Scheduler drop down menu

### ISSUE THREAD

**Issue by jokoputera** [RPCS3/rpcs3#12224]
## Quick summary
in Description Box, 'Fast' is internally disable for nvidia, why is it still be an option if it is an absolute for nvida user? 

## Details

Please describe the problem as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.
my log will be the screenshot 

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
no RSX

#### 3. Please attach screenshots of your problem.
https://drive.google.com/file/d/1Uo-lS-WfRtj7eKk1cHlQkS8XMePoMWvS/view?usp=sharing

#### 5. Please provide your system configuration:
* OS Windows 10
* CPU Ryzen 5 3600
* GPU nvidia 1660
* Driver version 512.xx
* etc.

#### Please include.
* can i also ask for scroll bar to be automatically adjust to the longest size of tab (Advance and Config Tab)
thanks

**Comment by Megamouse** [comment]
No

**Comment by Megamouse** [comment]
I don't understand the issue so I'll close it

**Comment by YuriNator557** [comment]
I think they are asking to remove Fast from the GUI if an Nvidia GPU is detected since it does nothing on those GPUs

**Comment by Darkhost1999** [comment]
> In the tooltip it says 'Fast' is internally disabled for Nvidia. Why is it still an option if it is an absolute for Nvida users?

It's still an option I believe so as one day it will work for Nvidia cards.

> Can I also ask for the scroll bar to be automatically adjusted to the longest size of tab (Advance and Config Tab)

I don't understand what this is asking. Yet I do believe if it's configurable you can edit the style sheet to your preferences.

**Comment by Darkhost1999** [comment]
Oops. Mobile doesn't update live :turtle:
