### ISSUE TITLE
NCAA '14 Revamped Freeze on 'Start' - Access violation reading location 0x44445320 (unmapped memory)

### ISSUE THREAD

**Issue by ryandecoster** [RPCS3/rpcs3#12221]
## Quick summary
Replaced the qkl_interface.ast file to add my own custom logo, game freezes and does not allow me to go past 'Start' after it has been pressed.

## Details
See above. The game runs fine with the default qkl_interface.ast file. Game freezes with the edited .ast file. I have edited other .ast files and game runs fine. Only freezes with the edited qkl_interface.ast file. 

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
RPCS3 v0.0.21-13459-d8bbec95

#### 2. Please attach TWO logs:
Regression - [RPCS3.log](https://github.com/RPCS3/rpcs3/files/8887023/RPCS3.log)
Good - [RPCS3.log](https://github.com/RPCS3/rpcs3/files/8887009/RPCS3.log)

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc.
	And drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 4. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/36908739/173258519-a3764af9-8d4d-4a1b-a4b4-f66dba49070a.png)

#### 6. Please provide your system configuration:
* OS Windows 10
* CPU Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
* GPU NVIDIA GeForce RTX 2070 Super

#### Please include.
* Anything else you deem to be important

**Comment by ryandecoster** [comment]
Screenshot of error as well:
![image](https://user-images.githubusercontent.com/36908739/173258834-ae0bb23b-f0fb-469b-a591-90aee740e6d4.png)

**Comment by illusion0001** [comment]
No support for modded games + old build + not a regression
