### ISSUE TITLE
F.E.A.R. BLUS30003 sound channels are swapped

### ISSUE THREAD

**Issue by xDShot** [RPCS3/rpcs3#12231]
Sounds from left are heard on right ear, from right side - at left ear.

Linux, latest.

**Comment by Darkhost1999** [comment]
Can you provide a log so we can take a look?

**Comment by xDShot** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8912485/RPCS3.log)

**Comment by capriots** [comment]
I looked at some videos on YouTube and it appears that this issue is actually also occurring on a PS3, so this wouldn't be an issue with RPCS3. Can you test the game on a PS3 to confirm?

**Comment by Satan86** [comment]
F.E.A.R. First Encounter Assault Recon does, in fact, have audio channels swapped on PS3, so the emulador is working the same way as the console

**Comment by xDShot** [comment]
Waiting for user patch then, heh.
