### ISSUE TITLE
Uncharted 2 Light flicker

### ISSUE THREAD

**Issue by BeefyBeast** [RPCS3/rpcs3#12233]
Hi, what wrong could it be?
In game flashlight is flikering and do some artifact on texture 
I tried to switch on\off different options, problem's still present
In title screen it looks like some filter is on
![light](https://user-images.githubusercontent.com/107585370/173929663-fbb2ca0e-4d28-4715-aed3-f3db1aa34296.png)
![light2](https://user-images.githubusercontent.com/107585370/173929674-971141c5-496c-4d96-bff3-ae8d5e941a44.png)
![settings](https://user-images.githubusercontent.com/107585370/173929676-c60951c1-2e49-4c0b-b981-9cedfef49e31.png)
![settings2](https://user-images.githubusercontent.com/107585370/173929679-c0a64b90-8213-4205-82cb-e1d5ba1e924d.png)
![title screen](https://user-images.githubusercontent.com/107585370/173930611-05b0f991-44bd-4370-9a95-575ac77e7156.png)

**Comment by Tarek2013** [comment]
Flickering textures are causing by Anisotropic Filter
Put it as 'Auto' and flickering will disappear

**Comment by AniLeo** [comment]
Closing due to non default settings

**Comment by BeefyBeast** [comment]
> Flickering textures are causing by Anisotropic Filter Put it as 'Auto' and flickering will disappear

This didnt help

**Comment by BeefyBeast** [comment]
> Closing due to non default settings

With default setting screen is green

**Comment by Xcedf** [comment]
Async texture streaming can also cause this issue, disable it.
