### ISSUE TITLE
MotorStorm [BCUS98137] (RPCSN) Online update problem

### ISSUE THREAD

**Issue by Wayne-DOOM** [RPCS3/rpcs3#12235]
![dns](https://user-images.githubusercontent.com/107612047/174025649-65b51cff-63cb-4084-8652-8cf3f3f99bfd.png)

![after_the_update](https://user-images.githubusercontent.com/107612047/174022761-73def8ae-3d2d-436c-b968-a41fb0dbf1e3.png)
![motor_storm_updating_again](https://user-images.githubusercontent.com/107612047/174022831-7c6cbab6-decc-4c1c-8082-cecf9f135d32.png)

MotorStorm [BCUS98137]
Base version, rpcs3 discord has no update for the game

Once I click online on rpcs3 with rpcsn with PSONE dns
it downloads an update for online.

it says reboot the game once downloaded, then rpcs3 states the game folder is corrupted, can't find boot.

[Update for Online](https://www.mediafire.com/file/pmiha3t7u7ou0kl/BCUS98137.7z/file)
The update is forced, even when white listed, you still must download this update.
Haven gotten the update, the game will no longer boot, until it's deleted from the game folder.

**Also note my rpcsn psn ID has been whitelisted.**

root:
dev_hdd0\game\BCUS98137:
USRDIR
ICON0
PARAM.SFO

Inside USRDIR:
EBOOT.BIN
patch_override_ps3.bin
patch_override_ps3.cnk
patch_override_ps3.dat

that's all the update gave me

My disk is as follows:
root:
PS3_GAME
PS3_UPDATE
PS3_DISC.SFB

I tried taking the update, over-writing it to my disk game dumped files, didn't work though, still asked to download the update.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8916908/RPCS3.log.gz)

I'm just wondering, if we can play Motor Storm Online with RPCSN with the PSONE - DNS
So far I can't figure out what's up with this update where this updating is really coming from, why we need it.

Would be great if someone could look deeper into this.

**Comment by JimScript** [comment]
Are you sure the update file you provided is The BCUS98137 version? Because when I put it into my game folder the patch manager thought I had BCES00006. So you are downloading this update through RPCSN right? Maybe the custom servers aren't providing the update for the BCUS98137 version?

**Comment by Wayne-DOOM** [comment]
> Are you sure the update file you provided is The BCUS98137 version? Because when I put it into my game folder the patch manager thought I had BCES00006. So you are downloading this update through RPCSN right? Maybe the custom servers aren't providing the update for the BCUS98137 version?

[Fix](https://www.mediafire.com/file/dik54h3kd6kg46b/PARAM.7z/file)

The PARAM.SFO was wrong, anyone with BCUS98137 just over-write the update .SFO file with the fix link.

**Comment by RipleyTom** [comment]
Not an issue with rpcs3/rpcn and seems to be fixed.
