### ISSUE TITLE
[Regression] Horrible audio distortion if a game configures downmixing

### ISSUE THREAD

**Issue by capriots** [RPCS3/rpcs3#12245]
PR that caused it: #12186, specifically commit 4beadb875363262388f4cdda0c92f285c27edcdf 
If you change any dynamic audio setting while a game is running that configures downmixing, audio becomes horribly distorted:
<Details><Summary>Warning: Loud!</Summary>

https://user-images.githubusercontent.com/29807355/174131243-ffb39e94-2158-47b5-89ae-7b9cc4782685.mp4

</Details>

It only manifests after changing a setting because of a different bug actually, I'm gonna open a separate issue about that.

I'm not entirely sure about this, but I think the changes in that commit might be unnecessary because games specify input channel count separately when opening a port in cellAudio, over here:
https://github.com/RPCS3/rpcs3/blob/11c52306282fcbe3099805c59c1ea841208ed6a1/rpcs3/Emu/Cell/Modules/cellAudio.cpp#L1055
https://github.com/RPCS3/rpcs3/blob/11c52306282fcbe3099805c59c1ea841208ed6a1/rpcs3/Emu/Cell/Modules/cellAudio.h#L85-L91

If I'm wrong, then to fix the issue, in these two lines:
https://github.com/RPCS3/rpcs3/blob/11c52306282fcbe3099805c59c1ea841208ed6a1/rpcs3/Emu/Cell/Modules/cellAudio.cpp#L70
https://github.com/RPCS3/rpcs3/blob/11c52306282fcbe3099805c59c1ea841208ed6a1/rpcs3/Emu/Cell/Modules/cellAudio.cpp#L73
```ch_cnt``` should be changed to ```downmix``` because previously ```ch_cnt``` represented output channel count, which is now ```downmix```.

**Comment by Willytor** [comment]
I am getting the audio distortion without changing any settings

**Comment by Willytor** [comment]
https://user-images.githubusercontent.com/94388697/174480013-1fac606d-7d10-46c9-be8b-cfdd6e3a8bd5.mp4
earlier today i went around and deleted some duplicate files i had but i don't think that caused it, because the audio still vaguely sounds like it should, save for the distortion. game is Tales of Graces f [BLUS30903]

**Comment by Willytor** [comment]
this wasn't happening yesterday btw and im pretty sure it was up to date then . also updated today and then it started happening

**Comment by Willytor** [comment]
the latest update fixed it 👍

**Comment by AniLeo** [comment]
No, it didn't. The broken build was simply reverted in the updater, but it's still broken in master.
