### ISSUE TITLE
[Feature Request] Rebind Motion Sensor To Any Other Input.

### ISSUE THREAD

**Issue by DanyaalMajid** [RPCS3/rpcs3#12241]
For people who do not have a motion sensor capable controller, they should be able to rebind the motion sensor to keyboard keys, mouse or any other joystick type device, games with mandatory Motion Controls can be played by everyone.

Basically i request that the sixaxis emulation becomes remappable to any input, so that we can emulate an accelerometer using keys, mouse or analog sticks.

Thanks

**Comment by Megamouse** [comment]
Duplicate
