### ISSUE TITLE
Freezes on 44 00 00 02: sc

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12240]
Assassin's Creed Brotherhood consistently freezes at this spot in the debugger.
Interpreters + Accurate PPU Non-Java Mode have proven most helpful in getting the farthest in the game. But still freezes.
![Screenshot 2022-06-17 105315](https://user-images.githubusercontent.com/60384196/174338553-165af6b7-4f12-4a5a-867d-d2a778cfddec.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8929179/RPCS3.log)

AC Revelations is the same exact way freezing at the same thing.
![image](https://user-images.githubusercontent.com/60384196/174340463-59eb4e9a-9693-4e1c-a8aa-63dc97663243.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8929235/RPCS3.log)
 
I have tested the advanced tab settings for PPU I still have no idea what they do or how they help. And I've tested my trusty ppu threads set to 3 or 1 and was not able to have any effect. In fact everything I did in testing had absolutely 0 effect on anything. Except for the  interpreters being slower.
All of the AC games appeare capable of users abusing the settings and the game remaining the exact same stability where the only difference would be how well it performs. AKA I cannot intentionally break AC or any of Ezio trilogy.

**Comment by readywer** [comment]
The same happens in AC4 too.
But i would say that first the picture freezes and just some secounds later the sound.
![Képernyőfelvétel (1022)](https://user-images.githubusercontent.com/90259918/174348768-cdb50dee-fd4a-4a2c-a5cd-25eab40789a4.png)
log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8929570/RPCS3.log.gz)

**Comment by Xcedf** [comment]
Those issues look like regular desyncs, did you try Atomic Fifo accuracy?

**Comment by Darkhost1999** [comment]
> Those issues look like regular desyncs, did you try Atomic Fifo accuracy?

Yea I thought about that looking at it more in depth. The only time this syscall is mentioned in the rsx code is nearby FIFO and vblank.
These things do not effect this freeze though.

**Comment by readywer** [comment]
> Those issues look like regular desyncs, did you try Atomic Fifo accuracy?

Yes no change in it. Atomic ordered won't help too.

**Comment by Darkhost1999** [comment]
I honestly think this is a cellspurs issue. But I've been testing settings and I'm not getting any good results.
Changing sleep timers accuracy advanced me by 1 or 2 checkpoints. But now I'm just getting immediate freezes upon continue savedata

**Comment by Darkhost1999** [comment]
Freezing on Oblivion 44 00 00 02: sc
https://github.com/RPCS3/rpcs3/issues/10812

**Comment by Darkhost1999** [comment]
It totally just said
GET JINXED

https://user-images.githubusercontent.com/60384196/175392477-0024bd81-d56a-4f22-a477-7b3f54d5caa5.mp4

**Comment by Darkhost1999** [comment]
Hulu is effected by freezing on 44 00 00 02.
When a proper no PSN patch is applied and the "a sign out has been detected, please sign in again" screen appears in which you can not progress past this in RPCS3 where you can on PS3. (I used webman mod PS3MAPI to test my patch live on my PS3.)
Due to the nature of the patch not requiring any login information to use Hulu the patch is kind of an "honor system" therefore I will not share the patch details here.

The main reason for this comment is to start a meta tracker of known effected games/apps:
* AC Brotherhood
* AC Revelations
* AC Black Flags
* Hulu
* Oblivion

And potentially more to be discovered.

**Comment by readywer** [comment]
I looked into this porblem and I think the 44 00 00 02: sc isn't a bug or any problamatic thing on the main thread because from my understanding is that it means that the main thread is waiting for answer from an other thread. Like when you start GT5 and the hdd popup shows up until you press x the main thread is at 44 00 00 02: sc, beacuse it waits for answer from an other thread. So all in all i consider this is a non issue, but i hope one of the devs will validate me.

**Comment by illusion0001** [comment]
Not an issue, main thread can always be stalled on syscall while work is being done on other threads.

**Comment by Darkhost1999** [comment]
![Screenshot 2022-06-28 144114](https://user-images.githubusercontent.com/60384196/176271155-0e8c84dd-abdb-41d3-bf31-31ac7895ba37.png)
All of these freeze on same thing not just main thread FYI.

**Comment by Darkhost1999** [comment]
Well there is 1 mildly interesting thread talking about semaphores
https://user-images.githubusercontent.com/60384196/176272594-f1c44095-27c0-4b23-b134-ebb9a6018276.mp4

**Comment by readywer** [comment]
> ![Screenshot 2022-06-28 144114](https://user-images.githubusercontent.com/60384196/176271155-0e8c84dd-abdb-41d3-bf31-31ac7895ba37.png) All of these freeze on same thing not just main thread FYI.

Because the issue likely be that a theard won't send or an information or a thread won't recieve some information which causes the other threads to wait too. The other tink that i can think that maybe can cause similar thing if a returned value incorrect, or bye some kind of overflow like if you skip track in GT5 in the licens races 5time the game will get a spu desync at a 100% rate. In my opinion the best thing to do is to search which syscall causes this so it is much easyer for the devs to fix it.

**Comment by Darkhost1999** [comment]
Well everytime I search the addresses in disassembled code the only thing I get is what Gael called the generic syscall name
Usleep. Which is in PPU, SPU and RSX code when searched on github.

**Comment by Darkhost1999** [comment]
So this issue needs some specifics but all I got for you is the common denominator.

**Comment by Darkhost1999** [comment]
Close until we find specifics I guess

**Comment by Darkhost1999** [comment]
If specifics are found then it'd be better to open separate tickets.
For documentation:
44 00 00 02 is a syscall that's called everytime a game is open and that thread is waiting. The syscall is harmless and not the cause of any issue. The issue would be whatever is causing these threads to wait not the waiting threads themselves.
Indeed the syscall is just generically syscall_usleep and nothing special.
