### ISSUE TITLE
RSX: Dubious query data pushed to cond render!, Please report to developers(q.pending=1)

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12253]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8934574/RPCS3.log.gz)
Was playing NFS MW 2012 and this is frequently in the log. I'm just following the instructions.
I don't know what the issue is. It says report it so here I am

**Comment by Darkhost1999** [comment]
I notice this https://github.com/RPCS3/rpcs3/issues/7896 and just want to preface with I don't want to cause concern over a harmless error if it's nothing to worry about.
There are many things wrong with the game but I don't even know what's related to this error at all.

**Comment by kd-11** [comment]
Yea, the error shouldn't be happening, which is why I self-assigned this.

**Comment by Darkhost1999** [comment]
Was able to observe this in Red Dead Redemption. Will continue testing and observing.
![image](https://user-images.githubusercontent.com/60384196/210274436-96bd4239-e92e-4cf8-afe9-af49ae840192.png)
[RPCS3 v0.0.25-14517-310fa712.log.gz](https://github.com/RPCS3/rpcs3/files/10333345/RPCS3.log.gz)
Is it believed that the new PR effects this at all?

**Comment by Darkhost1999** [comment]
Steps to reproduce. Boot game and grab a cup of coffee. Come back. Find dubious errors.
Game currently in question: Red Dead Redemption

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11165872/RPCS3.log)

**Comment by Darkhost1999** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12285392/RPCS3.log.gz)
Modern log same 1 used in RDR issue different issue

**Comment by kd-11** [comment]
I don't see this anymore in logs, let me know if there is a way to reproduce.
For now, closing.
