### ISSUE TITLE
Build issues on VS 2015 on Windows 10

### ISSUE THREAD

**Issue by therock247uk** [RPCS3/rpcs3#1225]
I get the following when trying to compile...

Severity	Code	Description	Project	File	Line
Error	C1083	Cannot open include file: 'corecrt.h': No such file or directory	emucore	C:\Program Files (x86)\VC\include\crtdefs.h	10
Severity	Code	Description	Project	File	Line
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory	rpcs3	C:\Users\therock247uk\Desktop\rpcs3\wxWidgets\include\wx\defs.h	713

Is this normal or it is a issue on my side?

**Comment by Zangetsu38** [comment]
just install sdk 10.240 with visual studio instalator

**Comment by Aaahh** [comment]
Yeah I've compiled on insider previews

**Comment by therock247uk** [comment]
I swear I have the Windows 10 SDK installed... specially since my VS 2015 is pro from MSDN... but ill reinstall it.

**Comment by Aaahh** [comment]
Far fetch but perhaps xxwidget isn't git cloned, fetch the git submodules

**Comment by therock247uk** [comment]
Yea I ran...

git submodule init
git submodule update

Will try again though.

**Comment by therock247uk** [comment]
SDK reinstall and compiling wxWidgets in the project then compiling rpcs3 got it compiled.

**Comment by paulsapps** [comment]
Looks like your SDK paths are screwed up

**Comment by therock247uk** [comment]
Well I got it compiled fine that way but anyway to fix them?

**Comment by tambry** [comment]
@therock247uk Is this still a problem?

**Comment by therock247uk** [comment]
Giving it a try will let you know.

**Comment by vlj** [comment]
Is it still an issue ?

**Comment by therock247uk** [comment]
is the current src compilable? ill give it a try if so.

**Comment by tambry** [comment]
@therock247uk The current source is compilable. Is this fixed?

**Comment by tambry** [comment]
Since there has been no followup from @therock247uk, I'll be closing this one. Let us know, if this is still an issue.
