### ISSUE TITLE
[Regression] Sly 3: Honour Among Thieves™ [NPEA00343] - 0x64 (unmapped memory)

### ISSUE THREAD

**Issue by MineSAT** [RPCS3/rpcs3#12257]
## Details
During the last mission of Episode 1, when carrying Bently to break the tar bombs, he disappears (invisible) and the game crashes afterwards. I do not know if this problem has happened in past versions, but asking in the #help channel they have told me that I am not the only one to whom it has happened recently.

I apologize in advance if I misread the report.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
RPCS3 v0.0.22-13800-42627946

#### 2. Please attach logs:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8936080/RPCS3.log.gz)
I do not know if this error has occurred in previous versions of the emulator. I just seriously started playing this game recently.

#### 4. Please attach screenshots of your problem.
(Video).: https://www.youtube.com/watch?v=QFtw3-xEYzE

#### 5. Please provide comparison with real PS3.
Does not occur.

#### 6. Please provide your system configuration:
* OS: Windows 11 Pro 21H2
* CPU: AMD RYZEN 7 5800X
* RAM: 32GB DDR4 Dual Channel  @3200Mhz
* GPU: NVIDIA RTX 3080 Ti 12GB 
* Driver version - 516.40 (latest)

**Comment by kd-11** [comment]
You need to identify when it stopped working. The builds immediately following 13549 do not touch anything that is shown in the crash logs there. You can find old versions of rpcs3 [here](https://rpcs3.net/compatibility?b)

**Comment by SlyCooperReloadCoded** [comment]
I see the problem, you don't have PPU LLVM Java Mode Fixup enabled.  Clear your PPU cache, enable the option, let it recompile, should never happen again.  Sly 2 and 3 need the option enabled.

**Comment by YuriNator557** [comment]
Java Mode Fixup is not needed, PPU LLVM Java Mode Handling still exists in RPCS3 and is not enabled in this log, if it is from an old custom configuration then just click Restore Defaults in the custom config and then just enable the frame limiter at 60fps again

**Comment by SlyCooperReloadCoded** [comment]
That's weird, because it doesn't appear as an option for me on latest master, and as soon as I disable PPU Non-Java Mode Fixup I start getting the issue above and the black screen issue in Sly 2 comes back.

**Comment by MineSAT** [comment]
Indeed @SlyCooperReloadCoded  was right! With the "PPU Non-Java Mode Fixup" option activated, the game works correctly and no longer crashes in said mission. But it's funny... in Sly 2 I didn't need this option to play it from start to finish without problems.

Fixed with PPU Non-Java Mode Fixup
