### ISSUE TITLE
Completely broken graphics in Sly Cooper: Thieves in Time (random)

### ISSUE THREAD

**Issue by EvilPlayer1** [RPCS3/rpcs3#12260]
## Details

Textures can be broken randomly at any time. They can fix themselves or if I exit fullscreen or press "windows" button in fullscreen.
#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8940284/RPCS3.log)
#### 3. Please attach screenshots of your problem.
![BCES01284_screenshot_2022_06_20_14_39_39](https://user-images.githubusercontent.com/90133207/174595085-9acfd920-4187-4f8f-9e54-54cf20f06a1d.png)
#### 5. Please provide your system configuration:
* OS - Windows 11
* CPU - i7-11700
* GPU - GTX 1660 SUPER
* Driver version - 516.40

**Comment by YuriNator557** [comment]
Patches and resolution scaling are being used, this issue is not valid

**Comment by EvilPlayer1** [comment]
> Patches and resolution scaling are being used, this issue is not valid

I never had this issue with upscaling and patches, before one of June update came out.

**Comment by YuriNator557** [comment]
Patches cannot be used when submitting error reports, turn them off and retest, if it still happens then provide an RSX capture of the issue

**Comment by EvilPlayer1** [comment]
> Patches cannot be used when submitting error reports, turn them off and retest, if it still happens then provide an RSX capture of the issue

Wait a minute. Patches are not necessary now? I read that they fix bugs and improve performance.

**Comment by TheGuitarHeroNerd** [comment]
I've had this issue with another game in full screen, seemed to happen after updating the Nvidia GPU drivers.

**Comment by EvilPlayer1** [comment]
Same even with default settings and without patches. I think I can't get RSX capture, because this issue only in fullscreen and when window is in focus. Even in fullscreen I can just unfocuse emulator window, then all bugs will disappear immediately.
Another bug is found, btw:
![BCES01284_screenshot_2022_06_20_15_54_13](https://user-images.githubusercontent.com/90133207/174607479-62095d24-aca9-4d39-8404-1e85594d59f2.png)

**Comment by Darkhost1999** [comment]
> Same even with default settings and without patches. I think I can't get RSX capture, because this issue only in fullscreen and when window is in focus. Even in fullscreen I can just unfocuse emulator window, then all bugs will disappear immediately.

Default settings and no patches are required for reporting issues. Because patches may cause unwanted behavior and random settings do random things.

However, you can capture an RSX capture with Alt + C and resume emulation with Alt + R if you need to without exitting fullscreen.

**Comment by EvilPlayer1** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8941274/RPCS3.log) - Log
[BCES01284_20220620170208_capture.zip](https://github.com/RPCS3/rpcs3/files/8941278/BCES01284_20220620170208_capture.zip) - RSX Capture
And is there any information about endless spam of errors like "E {RSX [0x0c27fb8]} RSX: Unsupported depth conversion (0x8B)"?

**Comment by EvilPlayer1** [comment]
The problem is in NVIDIA drivers. 512.95 is the latest version, which doesn't have issues. 516.40 and even newest 516.59 have this issue. Also, not only Sly Cooper: Thieves in Time has this issue. I tested all Sly and Ratchet games and noticed that some games don't have issues, some games have small issues, and some games have big troubles like in Sly 4.

**Comment by EvilPlayer1** [comment]
still appears even on 516.94
