### ISSUE TITLE
[OpenGL] Unhandled GL format 0x8058

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12268]
Still testing https://github.com/RPCS3/rpcs3/issues/11328 figured I'd report why I can't provide a comparison test from OGL vs VK.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8952962/RPCS3.log)

·F 0:00:33.776485 {RSX [0x0503d58]} SIG: Thread terminated due to fatal error: Unhandled GL format 0x8058
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\GL\glutils\image.cpp:104[:25], in function texture)

![image](https://user-images.githubusercontent.com/60384196/174905523-4c8cb107-6ab0-4d67-88e9-bf8e654f805b.png)

I was able to boot into the press cross to start screen and when I do it loads for a moment then just hangs.

**Comment by Darkhost1999** [comment]
#12284 Well the error is gone.

![image](https://user-images.githubusercontent.com/60384196/175993539-b816d398-fbeb-4f34-9db5-c0a45026be55.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8994127/RPCS3.log)
But the root issue persists. This is as far as I get  (before title screen). With Clockscale 101% or 99% I get past the title screen but never as far as choosing my car and hitting the road.
The clockscale trick is unrelated to this issue just a setting I use as it improves stability in this game even with Atomic RSX Accuracy and can mean the difference between getting ingame or not in either NFS Rivals or Battlefield 3.

**Comment by Darkhost1999** [comment]
Update after https://github.com/RPCS3/rpcs3/pull/12284
![image](https://user-images.githubusercontent.com/60384196/178613910-70f76eee-ddac-43f0-a455-21e74acb0070.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9097488/RPCS3.log)
·F 0:09:14.206434 SIG: Thread terminated due to fatal error: Unhandled Win32 exception 0xC0000005.

**Comment by Darkhost1999** [comment]
All I am experiencing now is the [44 00 00 02 ](https://github.com/RPCS3/rpcs3/issues/12240) error after resolving that win32 exception myself as it wasn't an RPCS3 issue.
[OGL.log](https://github.com/RPCS3/rpcs3/files/9097906/RPCS3.log)
Vulkan still works fine
![image](https://user-images.githubusercontent.com/60384196/178625206-51a86bf1-079d-4dd8-9abe-53bd4608c4cb.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9097914/RPCS3.log)
I can also see how 44 00 00 02 tells you nothing useful. So Open GL freezes compiling SPUs Vulkan does not.

**Comment by kd-11** [comment]
I don't see anything indicating something went wrong when using OpenGL. The game just locks up which is not unexpected because of how slow OGL is at emitting commands. I'll try to reproduce, but there is little chance to find anything meaningful.

**Comment by Darkhost1999** [comment]
Yea I'm not seeing anything myself which is so frustrating.

**Comment by Darkhost1999** [comment]
I was testing PR 12360 Open GL bringup 5.
I managed to get in game 1 time using OGL and RSX FIFO accuracy Atomic. It required me to start with a brand new cache. But has failed every time after that. I can tell you for sure that with RSX FIFO accuracy fast the game doesn't even get to the menu. With RSX FIFO accuracy atomic the game goes past the press start screen.
Ordered and atomic does the same as atomic with no perceived difference other than "possible desync event" in the log.

So I think this issue is safe to close as resolved from a previous PR.
