### ISSUE TITLE
batman arkham origins

### ISSUE THREAD

**Issue by cumin-men** [RPCS3/rpcs3#12274]
while trying to start Batman: Arkham Origins as i try to load the game, the compiling of PPU modules freezes and the game crashes. I have tried changing the PPU and SPU versions from interpreter and recompiler (both static and LLVM) and nothing works. i have tried resetting the PPU and SPU cahce but nothing changes. no other game i have tried has ahd this problem only this one.

please can you tell me how to fix this problem..

**Comment by YuriNator557** [comment]
Support goes in the discord server, not on GitHub
https://discord.com/invite/Af7H9yp
