### ISSUE TITLE
Rock Band Drums have issues in-game

### ISSUE THREAD

**Issue by Bakartridge** [RPCS3/rpcs3#12272]
I've been playing Drums in RPCS3 for a good amount of time now, but recently drums just don't work properly for me for whatever reason. In Rock Band 3 it acts like there's both drums AND a controller plugged in at the same time even though that isn't true, and in Rock Band 2 (both standard and Deluxe), it acts like there's TWO drums plugged in at the same time, even though again that isn't the case. If I can actually get into a song the drums work as intended, so I don't know why it thinks there's two plugged in. All the other controllers have nothing mapped and are listed as null, which makes this more baffling.
![image](https://user-images.githubusercontent.com/105967097/175177083-453858f9-0d57-4de7-b38f-8c4154bcd392.png)
And after that, upon closing the game, the emulator crashes and gives me an error box shown below, along with a fatal error message. 
![image](https://user-images.githubusercontent.com/105967097/175177901-138d57b7-36e5-41f7-8d86-f93cccab23dd.png)

I seem to be the only one with this issue which is really frustrating, I don't know if it's a problem with my computer or what, but I just don't know what the deal is.

Drums work on a real PS3 with no issue, so it's odd that this is happening.
I have the Rock Band 2 drum set with the appropriate dongle.

Current RPCS3 version is 0.0.22-13814-661b485b and the log file is attached below.
My computer's specs are as such:

    Windows 10 21H2
    Intel Core i7-8750H
    NVIDIA GeForce GTX 1050 Ti (512.77)
    8GB RAM

If anyone knows how to fix this, or if I'm just the only one getting this issue, please let me know.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8962484/RPCS3.log)

**Comment by Bakartridge** [comment]
Also to add, this happens on fresh install of RPCS3 too.

**Comment by khvostik** [comment]
Not only you. I have same issue in 007: Quantum of Solace even though the game is in "playable" section. When loading a new level the game just freezes and the same errors appear

**Comment by Megamouse** [comment]
The crash on exit should be fixed now

**Comment by Megamouse** [comment]
probably not

**Comment by Bakartridge** [comment]
> probably not

dang :/

**Comment by Megamouse** [comment]
Can you verify that the exit thing is fixed?

**Comment by Bakartridge** [comment]
> Can you verify that the exit thing is fixed?

Nope, and drums still don't work correctly

**Comment by MarcusRivet** [comment]
Did you make your rock band drums dongle use WinUSB drivers?

**Comment by MarcusRivet** [comment]
From a wild guess, I'm assuming that could potentially be the problem if you haven't done that since rockband sorta has the same type of peripherals as Buzz. I wrote a guide on how to set up buzz dongle to use WinUSB drivers, should be the same steps for rock band dongles. So since i'm going to bed ill just drop this here. I hope it fixes your issue, goodnight.



In order to use the Buzz controllers with RPCS3 read and follow the steps below:

After connecting the USB for your wireless or wired Buzz controllers, you need to make sure it uses WinUSB drivers, or else your game will crash instantly. For this you can use a software called Zadig. Step by step guide below:

1: Plug in the USB for your wireless or wired Buzz controllers into a USB-port on your PC.

2: Install Zadig on your Computer (https://github.com/pbatard/libwdi/releases/download/v1.4.1/zadig-2.7.exe).

3: Open Zadig, select 'Options', then select 'List all devices'. Then in the scroll window, you will now see a lot of devices, find which device is the USB to your Buzz controllers (most likely it is a device called 'Wbuzz'). once you've find the correct device, select it, then you need to click either of the up/down arrows next to the right window until it shows 'WinUSB' and click 'Replace driver'. Then it may give you a warning but just hit 'Yes' or 'Ok' on it to proceed with the install. Wait while it installs and applies the driver. Once finished you should be able to launch any of the Buzz games and play them with your Buzz controllers. NOTE: If you place the Buzz USB into another USB-port on your PC, you will have to re-do this process.

**Comment by Bakartridge** [comment]
> From a wild guess, I'm assuming that could potentially be the problem if you haven't done that since rockband sorta has the same type of peripherals as Buzz. I wrote a guide on how to set up buzz dongle to use WinUSB drivers, should be the same steps for rock band dongles. So since i'm going to bed ill just drop this here. I hope it fixes your issue, goodnight.
> 
> In order to use the Buzz controllers with RPCS3 read and follow the steps below:
> 
> After connecting the USB for your wireless or wired Buzz controllers, you need to make sure it uses WinUSB drivers, or else your game will crash instantly. For this you can use a software called Zadig. Step by step guide below:
> 
> 1: Plug in the USB for your wireless or wired Buzz controllers into a USB-port on your PC.
> 
> 2: Install Zadig on your Computer (https://github.com/pbatard/libwdi/releases/download/v1.4.1/zadig-2.7.exe).
> 
> 3: Open Zadig, select 'Options', then select 'List all devices'. Then in the scroll window, you will now see a lot of devices, find which device is the USB to your Buzz controllers (most likely it is a device called 'Wbuzz'). once you've find the correct device, select it, then you need to click either of the up/down arrows next to the right window until it shows 'WinUSB' and click 'Replace driver'. Then it may give you a warning but just hit 'Yes' or 'Ok' on it to proceed with the install. Wait while it installs and applies the driver. Once finished you should be able to launch any of the Buzz games and play them with your Buzz controllers. NOTE: If you place the Buzz USB into another USB-port on your PC, you will have to re-do this process.

I'll try that out when I get the chance then.

**Comment by Bakartridge** [comment]
> From a wild guess, I'm assuming that could potentially be the problem if you haven't done that since rockband sorta has the same type of peripherals as Buzz. I wrote a guide on how to set up buzz dongle to use WinUSB drivers, should be the same steps for rock band dongles. So since i'm going to bed ill just drop this here. I hope it fixes your issue, goodnight.
> 
> In order to use the Buzz controllers with RPCS3 read and follow the steps below:
> 
> After connecting the USB for your wireless or wired Buzz controllers, you need to make sure it uses WinUSB drivers, or else your game will crash instantly. For this you can use a software called Zadig. Step by step guide below:
> 
> 1: Plug in the USB for your wireless or wired Buzz controllers into a USB-port on your PC.
> 
> 2: Install Zadig on your Computer (https://github.com/pbatard/libwdi/releases/download/v1.4.1/zadig-2.7.exe).
> 
> 3: Open Zadig, select 'Options', then select 'List all devices'. Then in the scroll window, you will now see a lot of devices, find which device is the USB to your Buzz controllers (most likely it is a device called 'Wbuzz'). once you've find the correct device, select it, then you need to click either of the up/down arrows next to the right window until it shows 'WinUSB' and click 'Replace driver'. Then it may give you a warning but just hit 'Yes' or 'Ok' on it to proceed with the install. Wait while it installs and applies the driver. Once finished you should be able to launch any of the Buzz games and play them with your Buzz controllers. NOTE: If you place the Buzz USB into another USB-port on your PC, you will have to re-do this process.

Did that, but now it's saying there's no devices in gamepad settings.
![image](https://user-images.githubusercontent.com/105967097/175758293-3b76baad-df06-4093-b7d9-20ff6597346f.png)

**Comment by MarcusRivet** [comment]
Just try launching the game and see if it works. I know that Buzz peripherals doesn't show up in gamepad settings either, they just work automatically as they should in-game after the WinUSB setup. Make sure you paired the dongle to the drums if it's wireless

**Comment by Bakartridge** [comment]
> Just try launching the game and see if it works. I know that Buzz peripherals doesn't show up in gamepad settings either, they just work automatically as they should in-game after the WinUSB setup. Make sure you paired the dongle to the drums if it's wireless

**IT WORKED!** Thanks a million!
![image](https://user-images.githubusercontent.com/105967097/175784304-043a5166-a0e7-439f-b2a7-69958cfe42c3.png)

**Comment by Bakartridge** [comment]
The game also recognized how hard I was hitting the pad too now, which it previously didn't do.
Thanks a million!
![image](https://user-images.githubusercontent.com/105967097/175784480-48e510c6-ae7c-419f-82d2-47ff9ae56fdc.png)
