### ISSUE TITLE
Gran Turismo 5 fatal error on stopping the emulation.

### ISSUE THREAD

**Issue by readywer** [RPCS3/rpcs3#12279]
If you stop the GT5 emulation the emulator get a fatal error every time.
![Képernyőfelvétel (1056)](https://user-images.githubusercontent.com/90259918/175665241-3ee92d12-55dd-4c34-a103-22f613f1d33f.png)
Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8980616/RPCS3.log)

**Comment by Satan86** [comment]
Doesn't happen on my game anymore.

**Comment by MSuih** [comment]
Assuming that this has been fixed at some point. If the issue persists, this can be reopened

**Comment by readywer** [comment]
Yes the issue isn't appear anymore.
