### ISSUE TITLE
HLE: sys_fs_open error - device not mounted 

### ISSUE THREAD

**Issue by Zangetsu38** [RPCS3/rpcs3#1227]
I have this error after launch game 

> E {PPU[0x1] Thread (main_thread)[0x004700f0]} sys_fs: sys_fs_open('Assets/SaveIcon.png') failed: device not mounted
> E {PPU[0x1] Thread (main_thread)[0x004700f0]} sys_fs: sys_fs_open('GCM/duke_localization.bin') failed: device not mounted

Complette Log is here https://github.com/Zangetsu38/Log-Rpcs3/blob/master/PSN/EUR/NPEB01882-%5BDuke%20Nukem%203D%20Megaton%20Edition%5D.log

**Comment by AniLeo** [comment]
Is this still an issue?

**Comment by Zangetsu38** [comment]
no Allways problem here
caused by this Todo
>·W {PPU[0x1000000] Thread (main_thread) [0x004700f4]} cellFs: cellFsOpen(path=“Assets/SaveIcon.png”, flags=0, fd=*0xd000f5c4, arg=*0x0, size=0x0) -> sys_fs_open()
·W {PPU[0x1000000] Thread (main_thread) [0x004700f4]} sys_fs: sys_fs_open(path=“Assets/SaveIcon.png”, flags=0, fd=*0xd000f5c4, mode=0, arg=*0x0, size=0x0)
·W {PPU[0x1000000] Thread (main_thread) [0x004700f4]} vfs::get(): invalid input: Assets/SaveIcon.png
·E {PPU[0x1000000] Thread (main_thread) [0x004700f4]} sys_fs: sys_fs_open(“Assets/SaveIcon.png”) failed: device not mounted
·E {PPU[0x1000000] Thread (main_thread) [0x004700f4]} 'cellFsOpen' failed with 0x8001003a : CELL_ENOTMOUNTED
·W {PPU[0x1000000] Thread (main_thread) [0x004700f4]} cellFs: cellFsOpen(path=“/dev_hdd0/game/NPEB01882/USRDIR/Assets/SaveIcon.png”, flags=0, fd=*0xd000f5c4, arg=*0x0, size=0x0) -> sys_fs_open()
·W {PPU[0x1000000] Thread (main_thread) [0x004700f4]} sys_fs: sys_fs_open(path=“/dev_hdd0/game/NPEB01882/USRDIR/Assets/SaveIcon.png”, flags=0, fd=*0xd000f5c4, mode=0, arg=*0x0, size=0x0)
·W {PPU[0x1000000] Thread (main_thread) [0x00470194]} sys_fs: sys_fs_fstat(fd=3, sb=*0xd000f590)
·U {PPU[0x1000000] Thread (main_thread) [0x00470074]} cellFs TODO: cellFsStReadInit(fd=3, ringbuf=*0xd000f570)
·U {PPU[0x1000000] Thread (main_thread) [0x00470114]} cellFs TODO: cellFsStReadStart(fd=3, offset=0x0, size=0x1e1e0)
·U {PPU[0x1000000] Thread (main_thread) [0x00470094]} cellFs TODO: cellFsStRead(fd=3, buf=*0x21400250, size=0x10000, rsize=*0xd000f5f8)

Several Game have same error
Log
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/733049/RPCS3.txt)

**Comment by Nekotekina** [comment]
Only libfs.sprx

**Comment by Zangetsu38** [comment]
Yes, with libfs onlly have this
[RPCS3 (2).txt](https://github.com/RPCS3/rpcs3/files/733071/RPCS3.2.txt)

**Comment by AniLeo** [comment]
@Zangetsu38 please retest on latest build

**Comment by Zangetsu38** [comment]
no works fine :) 
![image](https://cloud.githubusercontent.com/assets/5261759/26735983/8eeda7dc-47c4-11e7-99bc-417997477aa7.png)
