### ISSUE TITLE
Jurassic: The Hunted has broken lighting on level 6

### ISSUE THREAD

**Issue by daninthemix** [RPCS3/rpcs3#12273]
On level 6 (The Lost Castaways) of Jurassic: The Hunted, here is what the lighting looks like:
![BLUS30435_screenshot_2022_06_23_17_50_31](https://user-images.githubusercontent.com/1974239/175352954-1cbe592f-cf88-49da-944b-d4fc678e8126.png)
For reference, here's a video showing what that level should look like:

https://youtu.be/ZAfVxeeN-sk?t=2624

EDIT: enabling Write Color Buffers fixes it.

**Comment by MSuih** [comment]
If enabling write color buffers fixes it then it is not an issue. WCB enabled is how PS3 works, having it disabled is sacrifices accuracy in order to improve performance. Same goes for all the other buffer options.
