### ISSUE TITLE
OpenGL broken on Intel (Windows) since 13691 - RSX: Compilation failed: ERROR: 0:9: 'std430' : syntax error syntax error

### ISSUE THREAD

**Issue by retroNUC** [RPCS3/rpcs3#12285]
## Quick summary
Many games that previously worked in OpenGL backend are now crashing after updating to RPCS3 Version 0.0.22-13691, which is the start of ongoing OpenGL rewrites. Using previous version before these changes (13670) works fine.

Noticed this happing in most games that I had Custom Configs for that were set to run with OpenGL rather than Vulkan video backend during to various compatibility errors. I have tried deleting caches of games, contents of hdd1, resetting RPCS3 config to defaults (except resetting OpenGL), etc.

## Log
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/8987422/RPCS3.zip)

````
·F 0:00:41.302676 {RSX [0x0106288]} RSX: Compilation failed: ERROR: 0:9: 'std430' : syntax error syntax error
source: 
#version 450

#define SSBO_BASE_LOCATION 10
#define SSBO(x) (SSBO_BASE_LOCATION + x)

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout(binding=SSBO(0), std430) buffer ssbo0{ uint data_in[]; };
layout(binding=SSBO(1), std430) buffer ssbo1{ uint data_out[]; };
layout(binding=12, std140) uniform parameters
{
	uint image_width;
	uint image_height;

	... (rest of shader dump)

·W 0:00:41.302866 {RSX [0x0106288]} SYS: Emulation has been frozen! You can either use debugger tools to inspect current emulation state or terminate it.
·F 0:00:41.303022 {RSX [0x0106288]} RSX: Linkage failed: Attached compute shader is not compiled.
````

## System Configuration
* OS - Windows 11 Pro 21H2
* CPU - 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
* GPU - Integrated Iris XE Graphics
* Driver - 30.0.101.1994 Retail / 30.0.101.3109 Beta

**Comment by retroNUC** [comment]
Working: v0.0.22-13600
Not Working: v0.0.22-13750

Will see if I can bisect further.

**Comment by kd-11** [comment]
There is little point. OpenGL is being rewritten.
That said, the problem here is intel's opengl driver. We'll have to see how bad things are when the rewrite is done.

**Comment by retroNUC** [comment]
Yeah, narrowed it down to 13691 as the first broken build, which was the first round of your rewrite changes - https://github.com/RPCS3/rpcs3/pull/12114.

Will stick with the build before this (13670) for now, and potentially bug more of the "Doesn't work on Vulkan, but works on OpenGL" issues so that I don't have to set certain games to OpenGL in the first place. Cheers.

**Comment by AniLeo** [comment]
Intel's GL driver on Windows was already not supposed to work since it's of very poor quality, see #6199

**Comment by retroNUC** [comment]
Hey kd, decided to compile the build and take a look myself. Comparing the dumped broken GLSL snippet with the source, there's something about the round brackets in the new #define macros that's not playing well with Intel, or maybe it's the order the macros are being processed in.

In any case, tested this locally, and it appears to fix the issue and get Intel working again:
https://github.com/RPCS3/rpcs3/commit/83fbd50fedd469a19072c26f9591aeedb875a5ac

**Comment by kd-11** [comment]
That's a compiler bug. Removing brackets breaks macro chaining since the expression is not contained. At that point it's better to use some other method to generate the replacements and assume intel does not support macros.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/12371 should fix this one.
After thinking about it, these problems are not going to stop, and I'm left with very few options. I'll be adding a spirv compiler to OpenGL which is only to be used for intel windows driver by default.
