### ISSUE TITLE
Several Problem on Disgaea 3 !

### ISSUE THREAD

**Issue by Zangetsu38** [RPCS3/rpcs3#1228]
First problem, Voice and Music Not Works on games, only effect sound works
Error probably for problem 
>{PPU[0x1] Thread (main_thread)[0x00228c2c]} cellGcmSys TODO: cellGcmSetZcull(index=0, offset=0x3a0000, width=1280, height=768, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x7, sRef=0x0, sMask=0x0)
E {PPU[0x1] Thread (main_thread)[0x002298ac]} cellPamf TODO: cellPamfReaderInitialize(): verification
E {PPU[0x1] Thread (main_thread)[0x002295ec]} cellAdec TODO: *** CellAdecParamAtracX: sr=0, ch_cfg=0(2), frame_size=0x0, extra=0x0, output=132, downmix=0, ats_header=1

And after, select Save and error this with Black screen.
>E {PPU[0x1] Thread (main_thread)[0x0022920c]} Exception: 
(in file Emu\SysCalls\Modules\cellL10n.cpp:431, in function SJISstoUTF8s)

Rpcs3 set a pause here

Other crash on second battle : 
>Le thread 0x1db8 s'est arrêté avec le code 0 (0x0).
Exception non gérée à 0x00007FFF80FF7F98 (KernelBase.dll) dans rpcs3D.exe : 0xC0000094: Integer division by zero.

Line 36 select on file CPUThread.cpp 
>task(); 

>Name : this	
Valor : 0x0000000002519310 {FPR=0x0000000002519408 {{_double=0.00000000000000000 _u64
=0 frac=0 ...}, {_double=...}, ...} ...}	
Type : CPUThread * {PPUThread}
![capture d ecran 2015-09-20 17 13 49](https://cloud.githubusercontent.com/assets/5261759/9981355/fcdf7034-5fba-11e5-8a6f-81d98f081ec2.png)

**Comment by AniLeo** [comment]
SJISstoUTF8s was implemented on 21 Dec 2015

This should probably be tested again

**Comment by tambry** [comment]
Well, we banned him from our organization, so he won't be able to post results himself anymore.
Probably safe to close this one.
