### ISSUE TITLE
The Tomb Raider Trilogy [BLES01195] - Loading Shaders issues???

### ISSUE THREAD

**Issue by RetroPCYT** [RPCS3/rpcs3#12286]
Compiling/Loading Shaders issues?

He noted that in the game "The Tomb Raider Trilogy"; **possibly** the loading of shaders does not work correctly since it loads them over and over again despite being loaded and having passed the level a lot of times with backtracking included.

Build used: RPCS3 Version: 0.0.22-13821-7842812e Alpha | master.
Default Config.

* OS: Windows 10 21H2 x64
* CPU: Core i7 4770k
* GPU: Geforce GTX970
* 512.77

**Comment by Megamouse** [comment]
Missing log file

**Comment by njmdietrich** [comment]
I think something just makes it so there is a bizarrely large number of shaders. Stutter is noticeably improved when going through an area a second time. But I do agree that this is a big issue and really reduces playability. After being about half way through the game (like 4 hours in), there are over 27000 pipeline objects. Even just compiling them at the beginning takes about 10 minutes on a 12400f.

**Comment by AniLeo** [comment]
Closing as invalid as issue report was never completed
