### ISSUE TITLE
Cannot compile rpcs3 with clang-cl

### ISSUE THREAD

**Issue by thx4ever** [RPCS3/rpcs3#12280]
lld-link : error : undefined symbol: _udiv128
20>>>> referenced by rpcs3_emu.lib(sys_time.obj):(class error_code __cdecl sys_time_get_current_time(class vm::_ptr_base<class stx::se_t<__int64, 1, 8>, unsigned int>, class vm::_ptr_base<class stx::se_t<__int64, 1, 8>, unsigned int>))
20>Done building project "rpcs3.vcxproj" -- FAILED.

The only problem i get when try to compile are undefined symbol _udiv128, i have tried add #include <immintrin.h> and still it trow this error, any workaround for this

My clang version are 14.0.5
Visual Studio 2019
 
Thanks

**Comment by vanc** [comment]
Based on stackoverflow, needs to link with compiler_rt's builtins-x86_64.lib.

https://stackoverflow.com/questions/68676184/clang-cl-error-lld-link-error-undefined-symbol-divti3

**Comment by AniLeo** [comment]
We have clang compilation working just fine at the moment, closing assumed solving, specially since that version of clang is very old by now

If you still have issues, please open a new issue with the latest version of clang and Visual Studio respectively
