### ISSUE TITLE
[macOS] DualShock 4 controller gets disconnected after 15 minutes resulting in game crash

### ISSUE THREAD

**Issue by rainerkohlberger** [RPCS3/rpcs3#12290]
Connecting my DualShock 4 game controller via Bluetooth works great with RPCS3 on macOS 12.4 on a MacBook Pro M1. However, after 15 minutes of using it during game play it suddenly disconnects (just like it would act if it's not used at all). This sometimes results in a paused game with a dialogue alerting that no controller is present (and I have to select it again in Pads settings). Almost every time it leads to a Thread termination causing the game to crash with this error though:

```
F {Pad Thread} SIG: Thread terminated due to fatal error: Segfault reading location 0000000000000020 at 00007ff814f485c3.
Emu Thread Name: 'Pad Thread'.
```

I've already tried to set Pan-Handler Mode to Multi-threaded with no success.

**Comment by darkuser89** [comment]
the same with a PS5 controller

**Comment by Frankiemagic13** [comment]
having same issues with dualshock 4 whats the easiest way to recconect without having to restart the app

**Comment by rainerkohlberger** [comment]
> having same issues with dualshock 4 whats the easiest way to recconect without having to restart the app

I recommend connecting the controller via USB until the bug is resolved.

**Comment by kytosai** [comment]
> > having same issues with dualshock 4 whats the easiest way to recconect without having to restart the app
> 
> I recommend connecting the controller via USB until the bug is resolved.

May I ask what version of rpcs3 you are currently using?

**Comment by rainerkohlberger** [comment]
RPCS3 Version: 0.0.22-13812-653a9e6e Alpha | master

**Comment by Frankiemagic13** [comment]
> > having same issues with dualshock 4 whats the easiest way to recconect without having to restart the app
> 
> I recommend connecting the controller via USB until the bug is resolved.

ill try that thanks

**Comment by Frankiemagic13** [comment]
> > having same issues with dualshock 4 whats the easiest way to recconect without having to restart the app
> 
> I recommend connecting the controller via USB until the bug is resolved.

when i connect USB it says dissconected

**Comment by MathiasKowoll** [comment]
yo need to open gamepads the first time yo open rpcs3 and then see if it gets connected.

**Comment by Behodar** [comment]
Similar (same?) issue here. I've found that going to Configuration/Pads and clicking Refresh gets it going again, but in action games it often happens at inappropriate times and I've yet to see a game get auto-paused when it occurs.

It doesn't usually crash RPCS3 for me, but it has a couple of times.

I'm  running 0.0.23-13926-07ebbb6c on OS 12.4 (Intel).

**Comment by Behodar** [comment]
I've done a little bit of experimentation with this. RPCS3 appears to use https://github.com/libusb/hidapi to talk to controllers. The most recent version, 0.12 from two months ago, added "macOS-specific function(s) to open device(s) in non-exclusive mode".

Testing hidapi outside of RPCS3, I was able to replicate the same behaviour. With hidapi in exclusive mode, the controller turns off after 15 minutes. But in non-exclusive mode, it doesn't.

I haven't attempted to build my own RPCS3, but I'm guessing that the fix may be as simple as calling `hid_darwin_set_open_exclusive(0);` after `hid_init()`. Is anyone able to test this?

**Comment by SergioGeeK7** [comment]
Hi team, great work here, the emulator works perfectly, and yes, I'm also dealing with this issue, controller goes to sleep probably after 15 minutes or so and game crashes and not been able to recover :(

**Comment by DazedNConfused-** [comment]
I am having this exact same issue as well with my Dualshock 4 controller.

**Comment by Behodar** [comment]
> I haven't attempted to build my own RPCS3, but I'm guessing that the fix may be as simple as calling `hid_darwin_set_open_exclusive(0);` after `hid_init()`. Is anyone able to test this?

I've now successfully built a copy with this fix, and can confirm that it works. 3rdparty/hidapi/hidapi/mac/hidapi_darwin.h needs to be #included, and I suspect that it'll need some sort of #if or similar around it to stop the build from breaking on other platforms. If someone with knowledge of how to do this could advise or submit a PR then it'd be appreciated :)

**Comment by shinra-electric** [comment]
@Behodar exactly what changes did you make?

**Comment by Behodar** [comment]
Very few :)

In rpcs3/Input/hid_pad_handler.cpp, I added `hid_darwin_set_open_exclusive(0);` after the `hid_init()` call and test (i.e. just before the for loop).

In rpcs3/Input/hid_pad_handler.h, I added `#include "hidapi_darwin.h"`.

I also copied 3rdparty/hidapi/hidapi/mac/hidapi_darwin.h into 3rdparty/hidapi/hidapi/hidapi but this was probably unnecessary.

**Comment by shinra-electric** [comment]
I did the same thing and am testing it now on an Arm build...

I surrounded the changes with 
```
#if defined(__APPLE__)
XXX
#endif```

I am not a dev on this project so I don't know if this is the preferred way to do it, but I can see they ifdef'd some win32 and linux code in the same way below.

**Comment by shinra-electric** [comment]
That seems to have fixed it. I played with a DS4 connected by bluetooth for 25 minutes with no issues. 

(Note I'm using an Arm build, not Rosetta).

**Comment by MSuih** [comment]
Adding an ifdef should be fine. Just open a pull request for the changes so that other people can use the CI build to test it too. You'll probably want to do the same change for dualsense as well

**Comment by Behodar** [comment]
Assuming you're talking about dualsense_pad_handler.cpp, it doesn't have a call to hid_init. That line is only in hid_pad_handler.cpp so I'm guessing that's the only place that needs to be updated.

**Comment by Behodar** [comment]
Thanks for making the PR. I go to sleep and miss all the fun :)

**Comment by shinra-electric** [comment]
No worries @Behodar . 
This is your PR, you worked it out. 
Good job!

**Comment by DazedNConfused-** [comment]
I have been using this build (which I picked straight from the CI's artifact) and I can attest that it works flawlessly. No more disconnects whatsoever. Impecable job diagnosing and putting the solution together, thanks a bunch @Behodar and @rainerkohlberger

**Comment by Behodar** [comment]
> thanks a bunch @Behodar and @rainerkohlberger

And don't forget @shinra-electric!

**Comment by CarlesLlobet** [comment]
Hey there 👋 

Sorry to refloat this closed issue. I'm not sure I'm following entirely the issue debugging and fix.

I have the same issue (without using rpcs3). I connect the Dualshock to my mack, and after 15min (idle time for Apple Bluetooth dualshock driver) it just dies.

Seems like you folks solved it for RPCS3... Would there be any way to solve it without the need of installing RPCS3? 
I mean.. I use my controller directly for Steam / EmulatorJS / ...

With the knowledge on how this issue worked @Behodar, do you think there would be a "generic" fix that could be applied to avoid the controller being disconnected?

Maybe a small program/script running on background that avoids the controller being detected as idle and disconnected ?

**Comment by CarlesLlobet** [comment]
@DazedNConfused- Oh, I see.. Thanks for the clarification! 
So I understand this fix was only to avoid the RPCS3 crash and the need of fully closing RPCS3 and losing progress to reconnect, not to fix the disconnect itself right?

> The controller getting disconnected after 15 minutes of idle time is just a standard battery-preserving feature in Mac. There is nothing to fix, nor it has anything to do with RPCS3.

That's such a pity... allegedly Mac trying to join the gaming scene and including nice GPUs with the new M1 chips... but no way to connect a Bluetooth controller for more than 15min 🤦 ...
At least I can play with cable, but its not ideal.

Well, thanks for the support anyway 🙏 
I was trying to look if something from here could be applied 👍

**Comment by DazedNConfused-** [comment]
@CarlesLlobet 

> So I understand this fix was only to avoid the RPCS3 crash and the need of fully closing RPCS3 and losing progress to reconnect, not to fix the disconnect itself right?

In this particular scenario, the controller would disconnect when it was _not_ idle (aka in the middle of gameplay); and *on top of that*, reconnecting would lead to RPCS3 crashing. So you could say we had two issues in one here.

Nowadays, the controller will still disconnect (as it always does, not only for RPCS3, but for all use-cases, even native gaming); but only after it has been _legit_ idle for 15 minutes. And reconnecting no longer requires closing and reopening RPCS3.
