### ISSUE TITLE
Severe performance regression when Driver Wake Up Delay is increased from #8485 onwards

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#12295]
## Quick summary
Games that require increased Driver Wake Up Delay to prevent freezes like God of War 3 and God of War Ascension exhibit severe performance regressions after #8485 https://github.com/RPCS3/rpcs3/commit/cf0fcf5a2adf74cd56186ea4416b3ebac0a587a6 was merged to master.

## Details
For example, in God of War III with wake up delay set to 50us:-

0.0.22-13827 - Locked 60 FPS at the title screen
![827](https://user-images.githubusercontent.com/4345150/176496157-e462520f-aa3a-42cc-a9a3-a508e974b50d.png)

0.0.22-13828 https://github.com/RPCS3/rpcs3/commit/cf0fcf5a2adf74cd56186ea4416b3ebac0a587a6 - Barely 20 FPS at the title screen
![828](https://user-images.githubusercontent.com/4345150/176496124-21f310f7-8793-431e-983a-e41cf8d0c145.png)

Current workaround is to revert Driver Wake Up Delay back to 1us and use Atomic Fifo. 

## Logs:-
0.0.22-13828 (first affected build)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9012693/RPCS3.log.gz)

0.0.22-13827 (last working build)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9012673/RPCS3.log.gz)

## System configuration:-

* OS Windows 10 21H1
* CPU i5 12400F
* GPU NVIDIA GTX 1070TI
* Driver version 511.79

**Comment by EvilPlayer1** [comment]
Sly Cooper: Thieves in Time is also broken. It works only in 3,33 FPS

**Comment by Nekotekina** [comment]
Try #12299

**Comment by solarmystic** [comment]
Seems to be fixed with #12299 
![image](https://user-images.githubusercontent.com/4345150/176657845-14fec084-d148-47cc-86f6-9e67ff020aa4.png)
