### ISSUE TITLE
Various games segfault rpcs3 upon boot from 0.0.23-13834 onwards

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#12304]
## Quick summary

As per title. 

## Details

After #10478 was merged to master (0.0.23-13834), booting up God of War Ascension causes a segfault with rpcs3 and crashes it. 

![Segfaults with 13834](https://user-images.githubusercontent.com/4345150/177174145-2875444d-ef8e-49f2-9ef8-1eb83ec6d54c.PNG)

The game boots just fine in the previous build (0.0.23-13833)
![GOWA 13833 boot okay](https://user-images.githubusercontent.com/4345150/177174206-a869f252-446f-489c-864a-3ec7cafa4b55.PNG)

## Logs:-
Last working build (0.0.23-13833)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9040232/RPCS3.log.gz)

First non working build (0.0.23-13834)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9040217/RPCS3.log)

## System configuration:

- SYS: RPCS3 v0.0.23-13834-fcd297ff Alpha | master
- SYS: 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.86 GiB RAM | TSC: 2.496GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1070 Ti' running on driver 511.79.0.0
- SYS: Firmware version: 4.88

**Comment by solarmystic** [comment]
From the rpcs3 discord, it seems like Metal Gear Solid HD Collection is also affected by the same segfault error introduced in the current master. https://discord.com/channels/272035812277878785/277227681836302338/993531454166401164

**Comment by dimaxdqwerty** [comment]
Same for Gran Turismo 6
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9040832/RPCS3.log)
