### ISSUE TITLE
Street Fighter X Tekken Can't join lobby

### ISSUE THREAD

**Issue by jh0nny2k** [RPCS3/rpcs3#12303]
## Quick summary
Please briefly describe what is not working correctly.

## Details

Please describe the problem as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.

Please find the log attached in my google drive.

https://drive.google.com/file/d/1o1UlE2asa9U0Ty2ilfBbvKaGZT4X9Ea-/view?usp=sharing

To make your life easier this is the log for when i try to connect with the other player 

·W 0:22:34.487191 {PPU[0x1000000] Thread (main_thread) [HLE:0x016a1914, LR:0x00a1d8dc]} sceNp: sceNpUtilCmpNpId(id1=*0xd00103a0(Shmenosan), id2=*0xd001034c(PsychoblueXWIRES))
·W 0:22:34.487049 {PPU[0x100001b] Thread (QoS Recv) [0x01a40afc]} sys_net: sys_net_bnet_recvfrom(s=27, buf=*0xd00e7e28, len=64, flags=0x0, addr=*0xd00e7e04, paddrlen=*0xd00e7e00)
·U 0:22:34.487302 {PPU[0x100001b] Thread (QoS Recv) [0x01a40afc]} sys_net TODO: lv2_socket_raw::recvfrom
·E 0:22:34.487240 {PPU[0x1000000] Thread (main_thread) [HLE:0x016a1914, LR:0x00a1d8dc]} SYS: 'sceNpUtilCmpNpId' failed with 0x8002ab0f : SCE_NP_UTIL_ERROR_NOT_MATCH [1]
·W 0:22:34.487374 {PPU[0x1000000] Thread (main_thread) [HLE:0x016a1924, LR:0x00a1d93c]} sceNp: sceNpUtilCmpOnlineId(id1=*0xd00103a0, id2=*0xd001034c)
·E 0:22:34.487411 {PPU[0x1000000] Thread (main_thread) [HLE:0x016a1924, LR:0x00a1d93c]} SYS: 'sceNpUtilCmpOnlineId' failed with 0x8002ab0f : SCE_NP_UTIL_ERROR_NOT_MATCH [1]

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
N/A

#### 3. Please attach screenshots of your problem.
![61F85CDF-5619-4F21-B76D-D55803806883](https://user-images.githubusercontent.com/21306966/177058539-8aef3586-feb1-48e8-82bf-92e73f87a760.jpg)
![EFEDC648-1F2F-490A-A267-405F800DE7A2](https://user-images.githubusercontent.com/21306966/177058541-338ef5cd-d1c4-4c66-901a-196aa5d36ff5.jpg)

#### 4. Please provide comparison with real PS3.

Lobbies work on PS3, everything works fine

#### 5. Please provide your system configuration:
* OS - WIN10
* CPU - 10400F
* GPU - 1660 SUPER
* Driver version  - 516.59
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by AniLeo** [comment]
Already listed as broken with RPCN.
