### ISSUE TITLE
Uncharted 2 - Chapter 25: You can't destroy the blue obstacle 

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#12307]
In the chapter 25 - Broken Paradise, there's a section you need to destroy the blue obstacle, but, in the emulator it has an bug, which does not allow you to destroy it

![image](https://user-images.githubusercontent.com/78843189/177233142-5ca7da03-395b-40b3-b26b-85b855999802.png)

A tried so many settings, PPU/SPU to Interpreter, Accuracy xfloat, etc, and doesn't work, the log file can't be useful, due to the issue can't detect in the log

The only workaround to avoid it, is to throw a grenade in this direction, even in the wiki an made an video tutorial about it
https://www.youtube.com/watch?v=yxGlk2qobxM

![image](https://user-images.githubusercontent.com/78843189/177233285-b855c4d2-61c2-48e2-abd5-11d1d2037853.png)

**Comment by Jonathan44062** [comment]
Closing as fixed, now sure what PR fixes the problem, but now you can destroy the blue obstacle
![image](https://user-images.githubusercontent.com/78843189/194808874-cef9d232-90e5-4355-bf5c-5e1e247cf649.png)

**Comment by Emogop** [comment]
Actually, it hasn't been fixed. At the newest build it's still an issue. But the Video above is helping to get though.
![Screenshot_261](https://user-images.githubusercontent.com/42875723/208301148-d394ec89-68a7-4826-90c6-f83b2ae66b33.png)
I'll leave the save file just before this moment. Just in case.

[save.zip](https://github.com/RPCS3/rpcs3/files/10253911/save.zip)

**Comment by Jonathan44062** [comment]
Updated the emulator to the latest, I have reset the same checkpoint 4 times and with me it works, I can destroy the sap.
![image](https://user-images.githubusercontent.com/78843189/208316569-37190ca5-b253-4da6-8cea-848fb4c6fe4b.png)

**Comment by ValeriaFom** [comment]
There is the same bug for me. Thank you @Jonathan44062 for sharing a workaround! It has helped me.

**Comment by ANoDE85** [comment]
The issue unfortunately still persists with `RPCS3 Version: 0.0.37-18022-9c93ec0b Alpha | master`

@Jonathan44062: Could you maybe be bothered to re-open the issue given that several people still experience it? Thanks.

**Comment by Ciceron14** [comment]
Experienced this issue as well on RPCS3 Version: `0.0.40-19375-08c92662 Alpha | master` using Uncharted 2 `BCES00509`
Workaround is also still usable at least
From previous and current comments, this seems to either be inconsistent or require specific steps/configs to happen. But it still happens and is not fixed.

**Comment by Pappapatu** [comment]
https://github.com/user-attachments/assets/7a3ff067-1539-40d2-88b2-6d430bcb65d7
cant repro on latest build (v0.0.40-19376-61a26048)
ofc, u can just use the ''workaround'' since thats how i do it anyway since its faster than doing that whole climbing part

**Comment by Pappapatu** [comment]
>From previous and current comments, this seems to either be inconsistent or require specific steps/configs to happen. But it still happens and is not fixed.

Works fine here with database (wiki) settings and recomended patches. If u r facing this issue, could u join in the discord server and send a log file while stating the issue in help channel? Thanks

**Comment by Ciceron14** [comment]
> Works fine here with database (wiki) settings and recomended patches. If u r facing this issue, could u join in the discord server and send a log file while stating the issue in help channel? Thanks

Hey thanks for getting back to this issue, you're right I should have tested with only the recommended settings. I have now tried it with pure default + wiki settings and I can confirm the issue does not occur! I'll keep in mind if I ever encounter a gameplay issue in another game it could be that my config differs from wiki I didn't think about that at all ngl

Now for some reason on my end with that config it is a flicker fest with ghostly artifacts though... but I won't be playing like that outside of testing this I will just ignore it lol
