### ISSUE TITLE
Razer Kishi support or bug.

### ISSUE THREAD

**Issue by RookTheRH** [RPCS3/rpcs3#12314]
From what I know razer kishi, a mobile controller commonly used for cloud streaming, should be an xniput controller, but when I use it through steam link remote play with rpcs3 the emulator won't pick it up as connected.

**Comment by Megamouse** [comment]
No logs provided.

**Comment by RookTheRH** [comment]
- SYS: RPCS3 v0.0.23-13857-3840015e Alpha | master
- SYS: AMD Ryzen 9 5900X 12-Core Processor | 24 Threads | 15.92 GiB RAM | TSC: 3.700GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2022-07- 7T10:37:58
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3080' running on driver 516.59.0.0
- SYS: Firmware version: 4.88
S UPDATER: RPCS3 is up to date!

is this the log? I'm new to this.

**Comment by RookTheRH** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9062424/RPCS3.log)
hope it´s it

**Comment by Megamouse** [comment]
This sounds more like something you have to fix through steam or windows...

**Comment by Megamouse** [comment]
Try with the SDL pad handler

**Comment by RookTheRH** [comment]
Already fixed it and kishi broke anyway :D

**Comment by Megamouse** [comment]
Thanks

**Comment by eKaos999** [comment]
@RookTheRH , I hope to get some help please, how did you fix it? I can't find any info online and the SDL still doesn't recognize my Kishi V2. Thanks.

**Comment by RookTheRH** [comment]
but my problem was with kishi v1, and I fixed it by buying gamesir x2 pro
and except for the form factor, the controller is so much better!


so 11. 3. 2023 v 9:30 odesílatel eKaos999 ***@***.***> napsal:
