### ISSUE TITLE
Williams Pinball Classics [BLES01051] crashes right after startup.

### ISSUE THREAD

**Issue by SinbadTheTailor** [RPCS3/rpcs3#12316]
## Quick summary
Williams Pinball Classics crashes after startup.

## Details

The game will display two messages, one about saving data, and the next about Playstation Network connectivity. After the second message, the game will crash every time.

System configuration:
* OS Windows 10 
* CPU AMD Ryzen 5 5600x
* GPU Nvidia 1070 TI
* Driver version 516.19

#### Log File.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9059161/RPCS3.log.gz)

**Comment by benderscruffy** [comment]
RPCS3 Version: 0.0.25-14495-8ac99680 Alpha | master
goes ingame with no crashes for me

**Comment by ScottNash042** [comment]
this doesnt crash anymore
can be closed
