### ISSUE TITLE
Significant performance regression with noticeably increased CPU utilization in games since 0.0.23-13834 (#10478)

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#12311]
## Details
In addition to the previously fixed segfault problem #12304  that came with 0.0.22-13834 #10478, another issue that crept up is a minor performance regression and increased CPU usage in games.

**EDIT:- Apparently this performance regression can be significant if on a core/thread starved scenario, see https://github.com/RPCS3/rpcs3/issues/12311#issuecomment-1185227965**

The segfault fix #12305 already merged into master does not resolve this issue. 

Last unaffected build is 0.0.23-13833. 

First affected build is 0.0.23-13834 and it persists to the current master.

## Examples

**Demon's Souls (Boletarian Palace - 1st Arcstone)**

0.0.23-13833 - **82** FPS/**59** 1% FPS/**52** 0.1% FPS - 33% CPU Usage
![DS 13833](https://user-images.githubusercontent.com/4345150/177508165-1be8b892-f783-4aeb-89df-c4f45a74f286.PNG)

0.0.23-13842 - **78** FPS/**55** 1% FPS/**51** 0.1% FPS - 42% CPU Usage
![DS 13842](https://user-images.githubusercontent.com/4345150/177508235-f4c85e84-da2e-44dd-8805-94f7a4425537.PNG)

**God of War III (3 Judges savepoint)**

0.0.23-13833 - **99** FPS/**73** 1% FPS/**59** 0.1% FPS - 52% CPU Usage
![GOW3 13833](https://user-images.githubusercontent.com/4345150/177508266-86ea2659-353e-499d-8b6b-43af96eabaf3.PNG)

0.0.23-13842 - **95** FPS/**70** 1% FPS/**57** 0.1% FPS - 63% CPU Usage
![GOW3 13842](https://user-images.githubusercontent.com/4345150/177508282-80cb1ddc-ed76-4c9c-bac0-4bac0f5777c4.PNG)

**Persona 5 (Classroom Building - 1F School Hallway)**

0.0.23-13833 - **81** FPS/**67** 1% FPS/**61** 0.1% FPS - 67% CPU Usage
![P5 13833](https://user-images.githubusercontent.com/4345150/177508443-d6008505-871d-46a2-ac04-9f3c8fdb64dc.PNG)

0.0.23-13842 - **79** FPS/**67** 1% FPS/**60** 0.1% FPS - 75% CPU Usage
![P5 13842](https://user-images.githubusercontent.com/4345150/177508499-fab8f077-0a18-446e-b6be-1afc39d2d858.PNG)

**The Last of Us (The Woods)**

0.0.23-13833 - **35** FPS/**32** 1% FPS/**32** 0.1% FPS - 60% CPU Usage
![TLOU 13833](https://user-images.githubusercontent.com/4345150/177508517-3570e70b-9edb-4ce0-a64b-49ee23142b80.PNG)

0.0.23-13842 - **33** FPS/**30** 1% FPS/**30** 0.1% FPS - 70% CPU Usage
![TLOU 13842](https://user-images.githubusercontent.com/4345150/177508576-f70fee33-44c0-42b5-bcc1-1fcc0124bb32.PNG)

## Logs:
* One for the build with regression.
[RPCS3 13842.log.gz](https://github.com/RPCS3/rpcs3/files/9053098/RPCS3.13842.log.gz)

* One for the build that works as expected.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9053099/RPCS3.log)

## System configuration:
- SYS: RPCS3 v0.0.23-13833-969b9eb8 Alpha | master
- SYS: 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.86 GiB RAM | TSC: 2.496GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1070 Ti' running on driver 511.79.0.0
- SYS: Firmware version: 4.88

**Comment by elad335** [comment]
Is the regression present with SPU ASMJIT decoder?

**Comment by solarmystic** [comment]
> Is the regression present with SPU ASMJIT decoder?

Yep. Using Persona 5:

**13833 with SPU ASMJIT Decoder** - 48 FPS/40 1% FPS/37 0.1% FPS - 65% CPU Usage
![P5 ASMJIT 13833](https://user-images.githubusercontent.com/4345150/177526573-0ec0f63a-8b11-4d35-b65f-61363d3d4eef.PNG)

**13842 with SPU ASMJIT Decoder** - 46 FPS/38 1% FPS/36 0.1% FPS - 72% CPU Usage
![P5 ASMJIT 13842](https://user-images.githubusercontent.com/4345150/177526835-64cd0217-5b53-4820-87e0-6c56c35d34c7.PNG)

**Comment by MarioTainaka** [comment]
I can confirm this regression is indeed real. I don't have the logs on hand, But it's felt across a number of games. Overall CPU is higher for sure. In games like Golden Eye 007 the same CPU instruction is repeated over and over "Get Camera" it causes the CPU usage to go up like crazy and stay there rendering the game almost unplayable.

**Comment by elad335** [comment]
#12317 Removes some mutex usage if you want to test.

**Comment by solarmystic** [comment]
Unfortunately performance degradation is still present with #12317. 

CPU utilization is 9% higher vs 13833 and Average FPS is still lower by 4.

![image](https://user-images.githubusercontent.com/4345150/177880250-c34ed274-ffd7-407f-ae47-cd11c9b767fd.png)

**Comment by MarioTainaka** [comment]
I think I managed to figure out what's causing the CPU usage increase. If you put SPU threads on auto it seems to cause higher CPU usage with the newer builds starting with 13834. Setting SPU Threads yourself to 1, 2 or slightly higher puts CPU usage on par with earlier builds. But using Auto with the newer builds increases CPU usage a ton!

**Comment by MarioTainaka** [comment]
> Unfortunately, performance degradation is still present with #12317.
> 
> CPU utilization is 9% higher vs 13833 and Average FPS is still lower by 4.
> 
> 0.0.23-13833 - 99 FPS/73 1% FPS/59 0.1% FPS - 52% CPU Usage
> 
> PR 12317 - 95 FPS/70 1% FPS/59 0.1% FPS - 61% CPU Usage
> 
> ![image](https://user-images.githubusercontent.com/4345150/177880250-c34ed274-ffd7-407f-ae47-cd11c9b767fd.png)

Try turning down the SPU threads.

**Comment by solarmystic** [comment]
> Try turning down the SPU threads.

Turning down SPU threads to lower CPU Utilization isn't a viable option when it lowers performance compared to Auto, especially when you have a CPU with ample cores and threads that could handle Auto previously. 

Using God of War 3 once again -

0.0.23-13860 with SPU Threads set to Auto - 95 FPS/69 1%/59 0.1% - 62% CPU Usage
![13860](https://user-images.githubusercontent.com/4345150/177972005-bf1a9c30-c271-4b89-b821-e04784e5bd77.PNG)

0.0.23-13860 with SPU Threads set to 3 - 92 FPS/61 1%/53 0.1% - 59% CPU Usage
![13860 SPU3](https://user-images.githubusercontent.com/4345150/177972630-59b38a25-8038-4965-8917-c5f9adda16dc.PNG)

Just a reminder of how 0.0.23-13833 performed with SPU Threads set to Auto - 99 FPS/73 1%/59 0.1%
![GOW3 13833](https://user-images.githubusercontent.com/4345150/177972813-e81d0ad6-0ded-429e-9163-5f4451cbd207.PNG)

**Comment by Kimex123** [comment]
Have the same issue in all games, although the performance regression for me is quite severe

0.0.23-13833 34 FPS
![Demon souls good](https://user-images.githubusercontent.com/89701010/179165474-da0b883e-a357-46b4-9844-ca9aeb1d5232.png)

0.0.23-13912 (current Master) 11 FPS
![demons souls bad](https://user-images.githubusercontent.com/89701010/179166038-570bd4eb-1300-40db-b21c-54cbe2ac27d2.png)

**Comment by solarmystic** [comment]
> Have the same issue in all games, although the performance regression for me is quite severe

This seems to hit CPUs that are completely saturated at 100% a lot harder compared to CPUs with resources (cores and threads) to spare. Very interesting indeed.

**Comment by kd-11** [comment]
Pinging @elad335 again. This issue is rather serious.

**Comment by elad335** [comment]
Test #12374 please.

**Comment by kd-11** [comment]
@Kimex123 It'd be nice to get your feedback as well, your PC was the most affected.

**Comment by Kimex123** [comment]
Update has fixed the performance for me aswell
0.0.23-13952 (current Master) 36 FPS (same FPS as before 0.0.23-13912)
![Screenshot (286)](https://user-images.githubusercontent.com/89701010/180027073-facbef45-0aa7-4099-8d4c-e0bfe2f4b851.png)
Thak you all so much

**Comment by MarioTainaka** [comment]
Happy to report the performance regression has been fixed across the board!

**Comment by elad335** [comment]
I'm curious of the effects #12378 has on performance.
