### ISSUE TITLE
[LLE] Libaudio.sprx fatal error

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12327]
When testing https://github.com/RPCS3/rpcs3/issues/12232 most likely just being an underpowered CPU issue I discovered LLE Libaudio.sprx halts my game without ever making noise. I've been sitting on this information for a while thinking to myself 
"Can we report firmware override issues?" Is that not allowed? Only HLE? Only LLE?
F {PPU[0x1000011] Thread (EAAudioCore Dac) [0x0076c080]} VM: Access violation reading location 0x0 (unmapped memory)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9075449/RPCS3.log)

I just figured nobody will be aware of the issue if not reported.

**Comment by elad335** [comment]
Because that's an invalid issue libaudio is not meant to be LLEd in the current state of the emulator.
