### ISSUE TITLE
Audio Regression

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12326]
https://github.com/RPCS3/rpcs3/pull/12300 - In app 5..1 surround sound audio works.
[Log that works](https://github.com/rpcs3/rpcs3/files/9075175/rpcs3.log.gz)
https://github.com/rpcs3/rpcs3/pull/12246 - In app 5..1 surround sound audio doesn't work.
[Log that doesn't work](https://github.com/RPCS3/rpcs3/files/9075195/RPCS3.log.gz)

https://user-images.githubusercontent.com/60384196/178074552-93e53bb4-9696-457c-80fc-49428a583f3f.mp4

Description:
In game surround sound irregardless of RPCS3 downmixer settings is hollow and distant. Sounds like a "Great Hall" equalizer at 35% volume of Normal.

**Comment by Darkhost1999** [comment]
Minor correction DTS 5.1 audio "works" but is just a horrible way to watch anything.
[Log testing each 5.1 audio format](https://github.com/RPCS3/rpcs3/files/9075239/RPCS3.log.gz)
Stereo audio format and 7.1 do not work

**Comment by Megamouse** [comment]
please test https://github.com/RPCS3/rpcs3/pull/12328

**Comment by Darkhost1999** [comment]
1st test RPCS3 became a background process that refused to close.
2nd test [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9076530/RPCS3.log) 
All good; audio sounds good and normal volume level.
