### ISSUE TITLE
[BLUS31426] Minecraft crashes after few minutes of play

### ISSUE THREAD

**Issue by Yoshimit** [RPCS3/rpcs3#12322]
## Quick summary
Minecraft crashes after few minutes of play

## Details

There's no much to say. After few minutes, the game stop responding.

#### 1. Please attach RPCS3's log.
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/9074203/rpcs3.zip)

#### 3. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/7319095/178044653-55f7de59-6bdb-4d60-9768-3980c8de5587.png)

#### 5. Please provide your system configuration:
* OS Windows 10 Home Single Language 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
* CPU Intel(R) Core(TM) i5-4460S CPU @ 2.90GHz   2.90 GHz
* GPU NVIDIA GeForce GTX 1070
* Driver version 31.0.15.1659

**Comment by n33k33** [comment]
Exact same here.

**Comment by Darkhost1999** [comment]
This issue is a couple of years old and no longer applicable.
I often play ~ 4 hours long sessions rarely longer.
