### ISSUE TITLE
[NPEB00563] Castlevania: Harmony of Despair has begun crashing/freezing when attempting to play online

### ISSUE THREAD

**Issue by chumpfighter** [RPCS3/rpcs3#12339]
When attempting to create or join a lobby using RPCN, the game will freeze in the loading menu just before the lobby screen. This issue happens starting with build 13410, while the lobbies are functioning fine in build 13401. Also tested in the current build and the issue is still present. Logs and screenshots are below.

- Windows 10 Pro Build 19042.1706
- 11th Gen Intel(R) Core(TM) i9-11900K
- Nvidia RTX 3090
- Driver  456.71
- 16GB RAM

Working in 13401:
![screenshot-13401](https://user-images.githubusercontent.com/74582243/178183352-8743bb3a-2a7b-40ea-868d-7fc11afc9963.png)
Log - [RPCS3-13401.zip](https://github.com/RPCS3/rpcs3/files/9080664/RPCS3-13401.zip)

Crashing in 13410 (game freezes during loading before screen seen in good screenshot):
![screenshot-13410](https://user-images.githubusercontent.com/74582243/178182620-b4aecb48-ed2f-4d13-9860-e354bb5eca71.png)
Log - [RPCS3-13410.zip](https://github.com/RPCS3/rpcs3/files/9080667/RPCS3-13410.zip)

**Comment by DebexeL** [comment]
From what I understand, this has been fixed by #12355, so I take it this issue could be closed?
