### ISSUE TITLE
Controller disconnects upon game boot, fixed by opening and closing pad menu

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#12331]
## Quick summary

Official Xbox One controller disconnects but reconnects after opening and then closing the pad menu.

## Details

After any game is booted and cache is loaded, the log will constantly spam:

E SYS: Stat: 'cellPadSetActDirect' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE

Most of the time it spams it 3-4 times, but sometimes thousands of times.  If I open the pad menu and then immediately close it without changing anything, it'll reconnect, and it'll continue to stay connected until I boot another game or load another savestate, in which it'll spam that error again and act as if I've unplugged my controller.

All other PC programs which can natively use this controller do not have this issue.  Windows 10's device manager shows that it's not actually getting unplugged.  I bought this controller new-in-box less than a month ago and there's zero signs of wear, so it's not a hardware issue.

#### 1. Please attach RPCS3's log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9075971/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.

https://user-images.githubusercontent.com/58268914/178094600-471e55fa-da80-44f0-b922-94677e27c31a.mp4

#### 4. Please provide comparison with real PS3.

Controller does not disconnect upon game boot.

#### 5. Please provide your system configuration:
* OS: Windows 10 Pro x64 Build 19043
* CPU: Intel Core i9-10900K
* GPU: NVIDIA RTX 2080 SUPER
* Driver version: 512.15

**Comment by Megamouse** [comment]
Is this a regression? I never had any issue like this before apart from 2 games. And there it's not the controller's fault.

**Comment by SlyCooperReloadCoded** [comment]
The last time I used the emulator with this controller, this never happened.  Every game in my library, whether it's Sly Cooper, Watch Dogs, Just Cause, they all do this.

**Comment by Megamouse** [comment]
Well then try to find the build that broke it

**Comment by TerrorVan** [comment]
Hi, I sorted through the latest updates on here and I can concur that RPCS3 now forces me to open/close the Pads menu before it recognizes my controller in-game; unfortunately I can't tell you which build "broke it" because I didn't use RPCS3 for over a year then updated before playing something where this issue now exists. Sometimes it takes one open/close, last night it told me Controller 0 connected *7* times before it worked.

**Comment by SlyCooperReloadCoded** [comment]
I can narrow it down to the last month, that much I know.  Less than a month ago I confirmed another issue was no longer happening and this wasn't happening then.

**Comment by Megamouse** [comment]
Well then try harder please

**Comment by SlyCooperReloadCoded** [comment]
I did some digging and while I haven't found the exact version, I've confirmed that switching from multithreaded pad handler to singlethreaded fixes the issue.  Still looking for the build that broke it.

**Comment by SlyCooperReloadCoded** [comment]
I've found the exact version, it's PR 10478, a.k.a. 0.0.23-13834, the first savestates build.  The release directly before it, PR 12302, does not have this issue.  Only affects multithreaded pad handling.

**Comment by TerrorVan** [comment]
> I did some digging and while I haven't found the exact version, I've confirmed that switching from multithreaded pad handler to singlethreaded fixes the issue. Still looking for the build that broke it.

I did not have multithreaded pad handler in the first place and I have this issue.

**Comment by TerrorVan** [comment]
> I've found the exact version, it's PR 10478, a.k.a. 0.0.23-13834, the first savestates build. The release directly before it, PR 12302, does not have this issue. Only affects multithreaded pad handling.

Issue persists with singlethreaded pad handling on my end with PR 12302.

**Comment by Megamouse** [comment]
I guess I have a suspicion what's the problem then.

**Comment by SlyCooperReloadCoded** [comment]
This is not only still an issue, but it now also affects single-threaded pad handling.  There's no workaround anymore.

**Comment by SlyCooperReloadCoded** [comment]
As of latest update, single-threaded pad handler no longer has the issue, but multi-threaded still does.  Or perhaps it's random and sometimes works regardless of the setting.

**Comment by SlyCooperReloadCoded** [comment]
Still an issue as of 0.0.23-13986-4c32c95b

**Comment by Megamouse** [comment]
Please try with #12467

**Comment by TerrorVan** [comment]
> Please try with #12467

I'm not sure how; the latest build on the site references 12464 and i'm unfamiliar with accessing the latest pulls outside this process.

**Comment by MSuih** [comment]
1. Open the PR page
2. Scroll to bottom and click on "Show all checks"
3. Click details for the operating system you have and then click on "View more details on Cirrus"
4. Click on Artifact and then download the larger file.

**Comment by TerrorVan** [comment]
I was able to download the build with the above instructions; The Godfather (and still only this game of the few games i've played) still prompts for a controller.

**Comment by Megamouse** [comment]
This issue is not about the godfather

**Comment by TerrorVan** [comment]
No, but that's the game where I have controller connection issues which is why I replied to this thread a while ago. I'm saying that this fix didn't fix that.

**Comment by SlyCooperReloadCoded** [comment]
From what I can tell it's fixed, nice.
