### ISSUE TITLE
[BCES01693] LittleBigPlanet 2 Cross Controller menu option (with DLC) causes a softlock

### ISSUE THREAD

**Issue by TorutheRedFox** [RPCS3/rpcs3#12341]
This may be caused by the game waiting for a response from the system as on PS3 the option brings up a system menu awaiting connection to a Vita console. RPCS3 should respond back with a cancellation when the menu is called, but as that doesn't happen, the game stays in a waiting state. The only (partial) way out of it is to reset your pod decoration through the pause menu, but that makes every option in the main menu not work.

**Comment by TorutheRedFox** [comment]
i.e. selecting "Connect" here will make the game bring the menu up on PS3, while on RPCS3 nothing happens, softlocking the game.
![image](https://user-images.githubusercontent.com/15708278/178309519-efc0ff79-3a92-4f0f-a100-510d0a8f3d69.png)

**Comment by Megamouse** [comment]
Missing log file 🤦

**Comment by TorutheRedFox** [comment]
I mean it doesn't need a log file if it's a missing feature causing a game to wait for something that doesn't happen on RPCS3's end.

The game is behaving as intended, the emulator itself isn't.

**Comment by TorutheRedFox** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9086109/RPCS3.log.gz)
as I was expecting, it's calling an init function related to cross controller that is unimplemented

a basic implementation of it to tell the game 'no' should do

**Comment by Megamouse** [comment]
Maybe this PR does something:

#12341

**Comment by TorutheRedFox** [comment]
yep that fixes it
