### ISSUE TITLE
Savestate regression in 0.0.23-13909

### ISSUE THREAD

**Issue by TigiHof** [RPCS3/rpcs3#12350]
Savestates worked fine for the 2009 Wolfenstein (BLUS30298) up until build 0.0.23-13908. Since 0.0.23-13909 I'm getting the following error message when trying to create a savestate:

![savestate_regression](https://user-images.githubusercontent.com/31275840/179123290-bf3596dd-fea9-4616-8ea5-6dce85a9ad50.jpg)

Logs:
[RPCS3_0.0.23-13908.zip](https://github.com/RPCS3/rpcs3/files/9116760/RPCS3_0.0.23-13908.zip)
[RPCS3_0.0.23-13909.zip](https://github.com/RPCS3/rpcs3/files/9116762/RPCS3_0.0.23-13909.zip)

Please note that despite build 0.0.23-13908 showing an error message in the log ("·E 0:01:35.028988 SYS: Restart failed: Savestate data is corrupted or it's not an RPCS3 savestate"), creating and loading savestates worked correctly. Only since 0.0.23-13909 it's not possible to create savestates anymore.

**Comment by elad335** [comment]
#12349

**Comment by TigiHof** [comment]
> #12349

Thanks! Technically, savestates are fixed now, but I have to say I'm not super happy with the way they work after the latest updates.

When I keep the new "Suspend Emulation Savestate Mode" config setting on the default ("false"), the game is automatically restarted after creating the savestate. Unfortunately it is completely frozen upon restart and, according to my measurement, it currently takes 74 seconds to "unfreeze".

On the other hand, when I set "Suspend Emulation Savestate Mode" to true, everything nearly works as before, except the savestate gets deleted automatically upon booting the game with it. This is a bad idea IMHO, because as a player you have to remember creating a new savestate every time.

I really liked the way savestates originally worked much better: You pressed CTRL+S, a savestate was created and the game got closed. You could reboot it anytime with the savestate, nothing got deleted and nothing needed to be configured. But that's just my opinion. Since the bug is fixed, this issue can be closed.

**Comment by elad335** [comment]
Actually it was this way because it was bugged, it must be deleted when the setting is on. Although I can revert the restart when the setting is off.

**Comment by elad335** [comment]
Fixed.
