### ISSUE TITLE
Soulcalibur V [BLUS30736] : Hangs after entering main Quick Battle screen from 0.0.23-13834 onwards.

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#12353]
## Details
This seems to be yet another regression that stems from 0.0.23-13834 #10478. 

After entering the main Quick Battle screen and repeatedly pressing the Triangle button to refresh opponents, the game will hang, and eventually cause rpcs3 to be non-responsive, which will then require the user to force quit the application.

Normal expected behavior is for new opponents to refresh ad infinitum without causing a freeze.

## Reproduction steps:-

1. Start the game.
2. Select Offline Play, then Quick Battle.
3. You will be sent to the Character Select Screen. Pick Patroklos and enter the main Quick Battle screen. 
4. Keep on pressing the Triangle Button to cycle through opponents, and after a short amount of time, the game will hang, and the rpcs3 window will be non-responsive.

First affected build is 0.0.23-13834 #10478 

https://user-images.githubusercontent.com/4345150/179301210-9b1c242f-56bb-4da2-980b-89fa30340026.mp4

Last working build is 0.0.23-13833 https://github.com/RPCS3/rpcs3/commit/969b9eb89dfd409cee5fa1279e730cbef8d5a5ba

https://user-images.githubusercontent.com/4345150/179301073-9a9e4ea1-6c59-4406-9fdd-a9a8370c54e6.mp4

Issue is still present in the latest master as of writing which is 0.0.23-13993.

## Logs:
* One for the build with regression.
[RPCS3 13834 (Not working).log](https://github.com/RPCS3/rpcs3/files/9123555/RPCS3.13834.Not.working.log)

* One for the build that works as expected.
[RPCS3 13833 (Working).log.gz](https://github.com/RPCS3/rpcs3/files/9123557/RPCS3.13833.Working.log.gz)

## System configuration:
- SYS: RPCS3 v0.0.23-13834-fcd297ff Alpha | master
- SYS: 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.86 GiB RAM | TSC: 2.496GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1070 Ti' running on driver 511.79.0.0
- SYS: Firmware version: 4.88

**Comment by kunit1** [comment]
@elad335

**Comment by DebexeL** [comment]
This should probably be tested again, since #12374 was merged.

**Comment by solarmystic** [comment]
> This should probably be tested again, since #12374 was merged.

Problem is still present even after #12374 was merged, in fact it's a lot faster to replicated it now after entering quick battle. 

New crash log with 13952 (master right after merge)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9154660/RPCS3.log)

**Comment by RipleyTom** [comment]
Tested, I wasn't able to reproduce, is this still an issue?

**Comment by solarmystic** [comment]
> Tested, I wasn't able to reproduce, is this still an issue?

It is not, but what happens instead is frame time spikes that continue to increase as you keep on refreshing your opponent list until the audio gets completely distorted after a certain point. 

I will close this particular issue report since it doesn't present in the original way anymore.

Here's a video of how the issue looks like in action now. Observe the frametime graph in the upper left corner closely as the video proceeds. 

https://www.youtube.com/watch?v=ti0A0qH-B2M
(youtube link due to mp4 size limit)
