### ISSUE TITLE
Tokyo Jungle [NPUA80523] looks very pixelated at higher resolution

### ISSUE THREAD

**Issue by Kimex123** [RPCS3/rpcs3#12354]
Ingame screenshot
![TJ Oatmeal](https://user-images.githubusercontent.com/89701010/179335648-a3f63bc8-6673-4d22-b1c2-f23e3b966e9a.png)

screenshot from someone on youtube whose game doesn't look pixelated
![TJ HD](https://user-images.githubusercontent.com/89701010/179335541-5b453d52-3a4a-4868-b0b9-0cfd08e26c89.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9125007/RPCS3.log)

**Comment by mfdsrax2** [comment]
You need to upload an RSX capture.

**Comment by Kimex123** [comment]
Here is the RSX capture
[NPUA80523_20220716230940_capture.zip](https://github.com/RPCS3/rpcs3/files/9126601/NPUA80523_20220716230940_capture.zip)

**Comment by Sunny10x32k** [comment]
> how do you upload an RSX capture?



> how do you upload an RSX capture?

**Comment by AniLeo** [comment]
Game uses MLAA. Cannot render at higher resolutions without using the patch that disables MLAA.
