### ISSUE TITLE
Master Volume Slider not working

### ISSUE THREAD

**Issue by victor-s-yip** [RPCS3/rpcs3#12352]
In version 0.0.23-13912-105781fa Alpha, the master volume slider does not appear to be working. When I try and adjust it, there is no change to the volume in game, despite restarting the game, or restarting RPCS3

**Comment by Darkhost1999** [comment]
Is this replicable?

https://user-images.githubusercontent.com/60384196/180620413-894bf049-0491-4697-940e-55181960ca32.mp4

**Comment by Darkhost1999** [comment]
If you don't hit save or apply then sure it does not work. But is there a specific game, any information you can provide to improve testing conditions?

**Comment by elad335** [comment]
Okay so if I understand correctly, the issue is that the user expects it to work like in other applications where you don't need to explicitly save for it to apply.

**Comment by Megamouse** [comment]
missing log anyway. useless issue
