### ISSUE TITLE
Rock Band 2 Online Stuck on Please Wait

### ISSUE THREAD

**Issue by stringbender1** [RPCS3/rpcs3#12351]
I was trying to connect to RB2 online. I actually got to connect but I got stuck with this. The log is provided for the game. Anyone help?

(https://user-images.githubusercontent.com/109321255/179124683-e10a744e-27dd-4b20-802e-d9819720f56c.png)
(https://github.com/RPCS3/rpcs3/files/9116798/RPCS3.log)

**Comment by RipleyTom** [comment]
Support for custom servers is outside the scope of rpcs3.

**Comment by stringbender1** [comment]
It isn't that

**Comment by stringbender1** [comment]
I already have a RB2 ip host switch

**Comment by stringbender1** [comment]
Damn, still not responded
