### ISSUE TITLE
JIT: Out of memory (size=0x9e2bb, align=0x10)

### ISSUE THREAD

**Issue by alexandremsouza1** [RPCS3/rpcs3#12363]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9128993/RPCS3.log)

Always when trying to play or pes 2018 it just closes.
my computer has 16 gb of memory and a 2 gb video card

![image](https://user-images.githubusercontent.com/38253342/179433501-395ae496-4169-4e17-b65d-e5a29f58eae9.png)

**Comment by AniLeo** [comment]
Pirated game, closing
