### ISSUE TITLE
[BCES00141/BCES00850/BCES01693] E SYS: 'sceNpUtilCmpNpId' failed with 0x8002ab0f : SCE_NP_UTIL_ERROR_NOT_MATCH [1]

### ISSUE THREAD

**Issue by TorutheRedFox** [RPCS3/rpcs3#12368]
I'm trying to connect to RPCN through LittleBigPlanet 1 and 2 (in order to connect to a private server), but it's failing.

I seem to be the only person who's having this problem and I don't know why. My friends are using the exact the same build as me and it's working for them.

Here's the log leading up to the game giving up on connecting

```
E sceNp: sceNpManagerGetTicket(buffer=*0x0, bufferSize=*0xd00649b0)
E sceNp: sceNpManagerGetTicket(buffer=*0x34287400, bufferSize=*0xd00649b0)
U sceNp TODO: sceNpManagerGetTicketParam(paramId=3, param=*0xd00649d8)
U sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd0063978)
U sys_net TODO: sys_net_abort(type=2, arg=0x1000002, flags=0x0)
U sys_net TODO: sys_net_infoctl(cmd=9, arg=*0xd00638f8)
U sys_net TODO: sys_net_infoctl(cmd=9, arg=*0xd00636c8)
U sys_net TODO: sys_net_infoctl(cmd=9, arg=*0xd00636a8)
U sys_net TODO: sys_net_infoctl(cmd=9, arg=*0xd00635e8)
U sys_net TODO: sys_net_infoctl(cmd=9, arg=*0xd0063528)
U sys_net TODO: sys_net_infoctl(cmd=9, arg=*0xd0063408)
U sys_net TODO: sys_net_infoctl(cmd=9, arg=*0xd0063388)
U sys_net TODO: sys_net_abort(type=2, arg=0x1000002, flags=0x0) x2
U sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd01541d8)
E SYS: 'sceNpUtilCmpNpId' failed with 0x8002ab0f : SCE_NP_UTIL_ERROR_NOT_MATCH [1]
E SYS: 'sceNpUtilCmpNpId' failed with 0x8002ab0f : SCE_NP_UTIL_ERROR_NOT_MATCH [2]
E SYS: 'sceNpUtilCmpNpId' failed with 0x8002ab0f : SCE_NP_UTIL_ERROR_NOT_MATCH [3]
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00850_USER1/USRDIR/littlefart365” [1]
```

**Comment by illusion0001** [comment]
No log file

**Comment by TorutheRedFox** [comment]
I've included the excerpt of the log file that's needed
the rest of it is log spam that the game's known for in current RPCS3 builds

**Comment by Megamouse** [comment]
Upload the full log

**Comment by YuriNator557** [comment]
The full file is always required

**Comment by TorutheRedFox** [comment]
stopped emulation after dismissing ingame error message

**Comment by RipleyTom** [comment]
Your IP/Host swap list is empty, you are connecting to official servers if any.
Also rpcs3 github issues isn't meant for private server support.

**Comment by TorutheRedFox** [comment]
my swap list is empty because I patched the EBOOT instead, and the problem is with RPCN connectivity and not the private server itself, as I'm hosting the server myself and no connection comes through

**Comment by TorutheRedFox** [comment]
I've been trying to debug this for the last week and have come to the conclusion that it's either the emulator or RPCN itself at fault
