### ISSUE TITLE
[Feature Request] Allow mapping of keyboard keys when gamepad is selected

### ISSUE THREAD

**Issue by jonasos3** [RPCS3/rpcs3#12362]
It would be useful to allow mapping of the keyboard keys even when another input device is selected as the handler in Pad settings.

**Comment by AniLeo** [comment]
What is the goal, you want hybrid kb+pad input?

**Comment by jonasos3** [comment]
I use reWASD as an input mapper for my DS4 (for many different emulators and applications). This makes the DS4 an XInput pad, meaning I have to use XInput as handler. When using XInput, the touchpad is not recognized as a button by RPCS3. Using reWASD I can map the touchpad to any random keyboard key, then IF keyboard keys were mappable in RPCS3 while in XInput mode I could use the touchpad for that purpose.
A bit long-winded of an explaination, but that is a specific example of the feature in use. Mostly a convenience, but I'm sure there are other things people would use it for as well :)

**Comment by jonasos3** [comment]
If you don't mind, what is this a duplicate of? I'd like to follow that Issue :)

**Comment by MSuih** [comment]
It's essentially the same request as https://github.com/RPCS3/rpcs3/issues/11278, yours is just limited to keyboard
