### ISSUE TITLE
Launching Skate 3 causes lots of errors

### ISSUE THREAD

**Issue by n-OlegS** [RPCS3/rpcs3#12372]
Whenever I try to launch Skate 3 I get lots of errors in the log, mostly CELL_ENOENT.  The game shows a black screen, and trying to quit the game causes the app to stop responding. Attaching the log file

[log.txt](https://github.com/RPCS3/rpcs3/files/9147061/log.txt)

**Comment by MSuih** [comment]
1. You pasted copy of the text in UI and not the log file that we want to see.
2. Github isn't a place for help requests, join our Discord instead for help and support.
3. You're not going to play Skate 3 on i5-5250U. The error seems to be related to some Vulkan issue (maybe antialiasing isn't supported on your system) but you will never get the game to run properly on such a weak CPU.
