### ISSUE TITLE
Wrong ELF file gets cached when booting an ELF that exists with an EBOOT.BIN in the same directory 

### ISSUE THREAD

**Issue by TorutheRedFox** [RPCS3/rpcs3#12380]
A few days ago I opened an issue about a very weird error that I was having and I've found the cause:

the patched ELF I was using wasn't being loaded, the original unpatched EBOOT.BIN that was present in the same directory (dev_hdd0/game/BCES01693/USRDIR) was being loaded and recompiled instead, despite me selecting the patched ELF through File > Boot (S)elf > Boot SELF/ELF.

Renaming EBOOT.BIN to something else allows the ELF to then be loaded.

log file can be found here in the old issue

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9142523/RPCS3.log.gz)

_Originally posted by @TorutheRedFox in https://github.com/RPCS3/rpcs3/issues/12368#issuecomment-1189199170_

**Comment by TorutheRedFox** [comment]
How to reproduce:
Take a game that installs its EBOOT to the HDD, decrypt said EBOOT, and patch it (i dunno, change a string that has obvious effects), saving it to a new file in the same location (dev_hdd0/game/{TITLE_ID}/USRDIR)
Booting it, those patches should be in effect, but they aren't.

**Comment by Nekotekina** [comment]
Is it fixed?

**Comment by TorutheRedFox** [comment]
I'll try now

**Comment by TorutheRedFox** [comment]
yep it works
