### ISSUE TITLE
FIFO error in Sly Cooper: Thieves in Time

### ISSUE THREAD

**Issue by EvilPlayer1** [RPCS3/rpcs3#12383]
### Quick summary

I noticed that in log became to appear FIFO errors, they didn't affect the game. But now emulator crashed with fatal error.

### Details

I played the game without troubles, but suddenly it crashed with fatal error of FIFO.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9172429/RPCS3.log)

### System configuration

OS - Windows 11
CPU - i7-11700
GPU - GTX 1660 SUPER
Driver version - 516.59

### Other details

![Screenshot 2022-07-23 01-07-49](https://user-images.githubusercontent.com/90133207/180575797-6b27a6ae-9806-4fe6-bf22-bd5a680bc6e1.png)

**Comment by Jonathan44062** [comment]
Github is not the place to ask support, join in rpcs3 discord
