### ISSUE TITLE
[BCES00141] cellPhotoImport2 missing causing Image Import Tool to not work

### ISSUE THREAD

**Issue by TorutheRedFox** [RPCS3/rpcs3#12386]
### Quick summary

This makes importing images impossible using the current build of RPCS3 as the game gets a seemingly empty image back.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9173562/RPCS3.log.gz)

**Comment by Megamouse** [comment]
please try again

**Comment by Megamouse** [comment]
how do you trigger the import?

**Comment by TorutheRedFox** [comment]
you need a tool that got finished but didn't actually get released to users

here's a level backup containing the tool
[BCES00141LEVEL62E1215C.zip](https://github.com/RPCS3/rpcs3/files/9198042/BCES00141LEVEL62E1215C.zip)
just collect the prize bubble and it'll show up in the functions category of your stickers in popit

**Comment by TorutheRedFox** [comment]
by the way, it does nothing now.

previously it instantly triggered a message saying that the imported image is too small (despite no menu being opened and therefore no image getting imported), but now it's doing absolutely nothing.

**Comment by Megamouse** [comment]
Well upload the log then ?

**Comment by TorutheRedFox** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9198130/RPCS3.log.gz)
it doesn't look like there's anything of use apart from the usual log spam that the game does
