### ISSUE TITLE
Mac M1 Full screen controls dont work since RPCS3 Version: 0.0.23-13960-246bf1df Alpha | master

### ISSUE THREAD

**Issue by slidenerd** [RPCS3/rpcs3#12392]
### Quick summary

**Problem**
Full screen does not work properly in-game

**How to reproduce**
- Install the problematic build
- Install game
- Update to 1.05 patch
- Create a custom keyboard mouse mapping profile under pad called grfs with the following settings

<img width="1905" alt="Screenshot 2022-07-25 at 5 50 21 PM" src="https://user-images.githubusercontent.com/5139030/180776161-e236a904-ad0a-4413-a6b7-051269f4e6b4.png">

- Here is a quick YAML file for player 1 with the same config as screenshot above

```

Player 1 Input:
  Handler: Keyboard
  Device: Keyboard
  Config:
    Left Stick Left: A
    Left Stick Down: S
    Left Stick Right: D
    Left Stick Up: W
    Right Stick Left: Mouse MLeft
    Right Stick Down: Mouse MDown
    Right Stick Right: Mouse MRight
    Right Stick Up: Mouse MUp
    Start: Return
    Select: Tab
    PS Button: F5
    Square: R
    Cross: Space
    Circle: C
    Triangle: 1
    Left: Wheel Down
    Down: V
    Right: Wheel Up
    Up: 3
    R1: Mouse Left
    R2: Q
    R3: Mouse Middle
    L1: Mouse Right
    L2: F
    L3: E
    Pressure Intensity Button: ""
    Pressure Intensity Percent: 50
    Left Stick Multiplier: 100
    Right Stick Multiplier: 200
    Left Stick Deadzone: 7849
    Right Stick Deadzone: 8689
    Left Trigger Threshold: 30
    Right Trigger Threshold: 30
    Left Pad Squircling Factor: 8000
    Right Pad Squircling Factor: 8000
    Color Value R: 0
    Color Value G: 0
    Color Value B: 0
    Blink LED when battery is below 20%: true
    Use LED as a battery indicator: false
    LED battery indicator brightness: 50
    Enable Large Vibration Motor: true
    Enable Small Vibration Motor: true
    Switch Vibration Motors: false
    Mouse Movement Mode: Relative
    Mouse Deadzone X Axis: 60
    Mouse Deadzone Y Axis: 60
    Mouse Acceleration X Axis: 1000
    Mouse Acceleration Y Axis: 1000
    Left Stick Lerp Factor: 100
    Right Stick Lerp Factor: 100
    Analog Button Lerp Factor: 100
    Trigger Lerp Factor: 100
    Device Class Type: 0
    Vendor ID: 1356
    Product ID: 616

```

### Details

**Expected Output**

When I select full screen, the game should not show the dock if I take my mouse to the bottom or the RPCS3 menu if I take my mouse to the top

**Observed Behavior**

The game opens the menu when the mouse is at the top and opens the dock when the mouse is at the bottom making it unplayable
![Uploading Screenshot 2022-07-25 at 5.30.48 PM.png…]()

### Build with regression

v0.0.23-13960-246bf1df

### Attach two log files

[TTY.log](https://github.com/RPCS3/rpcs3/files/9181028/TTY.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9181029/RPCS3.log.gz)

### Attach capture files for visual issues

<img width="1466" alt="Screenshot 2022-07-25 at 5 42 18 PM" src="https://user-images.githubusercontent.com/5139030/180775365-791e39ee-21cd-419a-8c0b-727bfd6db0ba.png">

<img width="1920" alt="Screenshot 2022-07-25 at 5 30 48 PM" src="https://user-images.githubusercontent.com/5139030/180774820-de6605d6-4036-45d7-b334-089d128a76c8.png">

<img width="1920" alt="Screenshot 2022-07-25 at 5 30 53 PM" src="https://user-images.githubusercontent.com/5139030/180774973-7e977270-378a-4739-9b49-dca7939e430b.png">

### System configuration

**Machine**

Apple M1 16GB Mac Os Monterey 12.5 (21G72)
8 core CPU
8 core GPU

**Game Tested**

Tom Clancy's Ghost Recon Future Soldier™ [BLUS30521]

### Other details

The previous version namely rpcs3-v0.0.23-13956-086afbba does not have this problem with the same game and all the successive builds after this MAY have this issue (tested the latest one rpcs3-v0.0.23-13964-0ba0f9d2_macos which still has the problem)

**Comment by kd-11** [comment]
No ideas, this one is odd. The PR in question https://github.com/RPCS3/rpcs3/pull/12371 makes most changes to OpenGL which is not even compiled for macos. Also the single change to vulkan only applies to the ANV driver and has nothing to do with windowing.
So, did the build environment maybe break this? Likely something in cirrus-ci changed.

**Comment by slidenerd** [comment]
The previous build doesnt have this issue, I will add screenshot from the previous build with the same configuration for this game and the exact same process I followed to install the game and update this issue

**Comment by ralph303** [comment]
I think this bug came with the latest MacOS-Update and is not related to RPCS3.
I have the same issue using fullscreen in Steam-Games like "Return to Monkey Island" for example.

**Comment by kd-11** [comment]
I'll close this. Combining the lack of updates from the OP and the report confirming a bug in macOS is enough evidence for me.
