### ISSUE TITLE
[BCES00294] Siren Blood Curse (Not working with Vulkan API)

### ISSUE THREAD

**Issue by dochankpin** [RPCS3/rpcs3#12391]
### Quick summary

Hello guys, greetings!
I'm reporting about the game: Siren Blood Curse.
A few months ago, the game worked perfectly with the OpenGL API.
However, I went a few months without playing RPCS3.
So I recently went back to playing RPCS3, and then updated the emulator.
I realized that Vulkan API was implemented, so I tested several games.
And the performance is extremely superior, very good indeed.

CONGRATULATIONS!

However, when I went to test the game: Siren Blood Curse [BCES00294] with the Vulkan API,
the game starts to compile the necessary files.
Then when it finishes compiling, the screen is completely black,
and it doesn't come out anymore, nor does the game start. Not anything.
I hope I helped the developers with this report.
Thank you all in advance for your help, attention and understanding.
See ya.
Bye.

### System configuration

* OS: Windows 10 Pro 64-bit.
* CPU: Intel Core i7 3770 @ 3.40GHz
* RAM: 16,0GB Dual-Channel DDR3 @ 798MHz
* MOTHERBOARD: ASUSTeK COMPUTER INC. H61M-A/BR (LGA1155)
* MONITOR: LG ULTRAWIDE (2560x1080@60Hz)
* GPU: 8192MB ATI Radeon RX 580 Series (XFX Pine Group)
* SSD O.S.: 111GB KINGSTON SHFS37A120G (SATA-3 (SSD))
* HDD: 465GB Seagate ST500DM002-1BD142 (SATA )
* HDD: 1863GB Seagate ST2000LM007-1R8174 (SATA )

**Comment by MSuih** [comment]
Include a log file

**Comment by MSuih** [comment]
Ask for help in our discord server instead of creating issues on github

**Comment by dochankpin** [comment]
Hi friend, thank you for your attention and reply.
Is there a regression in the emulator?
