### ISSUE TITLE
Namco System 357 Error 8

### ISSUE THREAD

**Issue by anxious132** [RPCS3/rpcs3#12401]
### Quick summary

![4e5e16_ab9f9c4a61f14d9d99b55f284f79c9c9_mv2](https://user-images.githubusercontent.com/110099202/181229175-8254e033-5f72-4ca8-bc1b-2645775c1e66.jpg)

### Details

Tekken 6.0 Vanilla, doesnt even ask for dongle just error 8 (there is no dongle error tho)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9197662/RPCS3.log)

**Comment by brian218** [comment]
Incorrect game id in the provided RPCS3.log: game path should be `/dev_hdd0/game/SCEEXE000` rather than `/dev_hdd0/game/SCEEXE0001` for System 357 games.
