### ISSUE TITLE
[Regression] E Compat: Database Error - No Results found

### ISSUE THREAD

**Issue by Mortus06** [RPCS3/rpcs3#12400]
### Quick summary

Up until 0.0.23-13972 RPCS3 showed the game compatibility, be it in the corresponding column on list mode or as a small dot on the top left of the game icon on grid mode.
When starting RPCS3 on 0.0.23-13974 the emulator prints the error E Compat: Database Error - No Results found, and doesn't display the game status.

### Details

Latest working master: ![RPCS3](https://user-images.githubusercontent.com/92671266/181184698-71ca9dc1-3723-4809-8fd5-fdd6f5a589ab.jpg)
Current master: ![image](https://user-images.githubusercontent.com/92671266/181184850-1911231f-ae7b-426f-893f-414dfa57688c.png)

In the second image you can see "Database Missing" in the "Compatibility" column.

### Build with regression

v.0.0.23-13974-8f7209f8

### Attach two log files

Latest working master: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9196004/RPCS3.log)
Current master: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9196013/RPCS3.log)
 

### System configuration

CPU: Intel i7-8700 - 6 cores, 12 threads, base clock speed 3.20 GHz
GPU: Zotac NVIDIA GeForce RTX 3070, running on driver version 516.59
RAM: 16GB DDR4
Motherboard: MSI Z370 Gaming Plus
OS: Windows 11 21H2 22000.795
DirectX version: DX12

**Comment by Megamouse** [comment]
Cannot reproduce.
Maybe the database was not available.

**Comment by dyno0** [comment]
Right click on any game -> Download Compatibility Database
but true, it didn't for me either after updating to 13974

**Comment by Mortus06** [comment]
Thank you, now it shows
