### ISSUE TITLE
[Feature request] Ps2 Controller Support

### ISSUE THREAD

**Issue by Scalerize** [RPCS3/rpcs3#12414]
### Quick summary

Here are the vid and pid of my ps2 usb adapter, sadly rpcs3 won't identify it as xinput, it works on pcsx2 but not on rpcs3 for some reason VID:0810 PID:0001

### Details
VID:0810 PID:0001

**Comment by AARP41298** [comment]
Use MMjoystick instead
Or if you really want to detect it as an xinput, use the program called xoutput, to emulate a 360 controller

PD In combination with hid hide you could use the ps2 controller in almost any game

**Comment by Scalerize** [comment]
Reason for closure: turns out my adapter is for psx controllers but still it Does enable ps2 controllers to work,  And now i'm realizing this feature is not really necessary, If anyone wishes to request this in the future that's your choice, for now i'll just use a Ps4 controller since it has more functionality like Sixaxis.
