### ISSUE TITLE
[Regression] GL: GTA IV broken graphics after #12284

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#12428]
### Quick summary

Graphics no longer render correctly using OpenGL on GTA IV after #12284.

### Details

Before: 
![image](https://user-images.githubusercontent.com/1712979/182002444-86949dcd-66f2-4cde-b579-083cd9c3fb44.png)
After: 
![image](https://user-images.githubusercontent.com/1712979/182002489-842ceb92-9c92-4187-9994-8038cf11cb26.png)

### Build with regression

v0.0.23-13907-cdef752a

### Attach two log files

Before: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9227687/RPCS3.log.gz)
After: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9227693/RPCS3.log.gz)

### Attach capture files for visual issues

[NPEB00882_20220731014335_capture.zip](https://github.com/RPCS3/rpcs3/files/9227699/NPEB00882_20220731014335_capture.zip)

### System configuration

Ryzen 7 2700
RX 580 4GB 22.7.1

**Comment by kd-11** [comment]
This was a driver bug (it works on all other GPUs) and was caused by GL_DEPTH_STENCIL_TEXTURE_MODE not working with the old driver. Now we have a completely new driver with new bugs so most of my old test cases don't even work anymore.

**Comment by xddxd** [comment]
![image](https://user-images.githubusercontent.com/1712979/182049461-7e6ec272-93d2-46dd-92f0-6d33f49fa6e2.png)
RADV is also affected.

**Comment by mfdsrax2** [comment]
it looks to me like the old version also has some graphic problems. What are those low-res things on the center of the road?

**Comment by kd-11** [comment]
Still an issue? I fixed the problems I encountered with mesa recently.

**Comment by kd-11** [comment]
Seems to be fixed (at least when tracing through the capture)
![image](https://user-images.githubusercontent.com/15904127/197065040-77a44a56-15fd-435b-8c7f-70ba84525979.png)
