### ISSUE TITLE
[BCES00141] Game crashes when requesting NP store information

### ISSUE THREAD

**Issue by TorutheRedFox** [RPCS3/rpcs3#12424]
### Quick summary

When the game is connected to a private server, it considers itself online and makes the assumption that it can also connect to the PlayStation Store, and attempts to do so. This results in a crash as the functions related to the store aren't implemented.

### Details

sceNpCommerce2GetProductInfoGetResult, sceNpCommerce2InitGetProductInfoResult and sceNpCommerce2GetGameProductInfo are called right before the game crashes when trying to hover over the ingame store button, which triggers a connection to the store.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9225871/RPCS3.log.gz)

**Comment by TorutheRedFox** [comment]
also affects LittleBigPlanet 2 to an extent

**Comment by TorutheRedFox** [comment]
here's footage of it affecting LBP1
https://youtu.be/dcfjbtH8eqU

and here's footage of it affecting LBP2 (Beta)
https://youtu.be/zLy3LTU4YPw

**Comment by ZippyZolton** [comment]
I get crashes on the whole trilogy, but there is apparently a patch that fixes this which I cannot find. I saw someone screensharing in the LBPU server and they nonchalantly clicked on the LittleBigStore as if it's supposed to work lol (yes they were connected to Beacon as well)

**Comment by TorutheRedFox** [comment]
interesting

**Comment by TorutheRedFox** [comment]
> I get crashes on the whole trilogy, but there is apparently a patch that fixes this which I cannot find. I saw someone screensharing in the LBPU server and they nonchalantly clicked on the LittleBigStore as if it's supposed to work lol (yes they were connected to Beacon as well)

LBP1 is the worst offender though as simply highlighting LittleBigStore (and/or bonus if you have GOTY) will crash the game

**Comment by IndustryStandrd** [comment]
Will chime in that I also have this on LB2 and LB3

In LB1 and 2 I can work around it but in LBP3 as far as I can tell I have no way of actually playing the DLC for it now because it has to load the playstation store.

**Comment by TorutheRedFox** [comment]
> Will chime in that I also have this on LB2 and LB3
> 
> In LB1 and 2 I can work around it but in LBP3 as far as I can tell I have no way of actually playing the DLC for it now because it has to load the playstation store.

can you not enter more stories?

**Comment by IndustryStandrd** [comment]
> > Will chime in that I also have this on LB2 and LB3
> > In LB1 and 2 I can work around it but in LBP3 as far as I can tell I have no way of actually playing the DLC for it now because it has to load the playstation store.
> 
> can you not enter more stories?

LBP 2 I can, in LBP 3 I am not able to load any of the DLC without it freezing up or crashing though.

Unless there's another section to play DLC from that I haven't seen yet.

**Comment by TorutheRedFox** [comment]
recent update fixed the issue
