### ISSUE TITLE
[NPUB30424] Prince of Persia White Screen issue

### ISSUE THREAD

**Issue by Kimex123** [RPCS3/rpcs3#12422]
### Quick summary

I have been trying to run prince of persia but when i press new game and get through the loading screen the screen turns white and the game stops working

### Details

After this loading screen the screen turns white
![Screenshot (295)](https://user-images.githubusercontent.com/89701010/181866390-99037dad-b2d8-4ede-9629-cd6dddc7acc1.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9224151/RPCS3.log)

**Comment by RainbowCookie32** [comment]
You have Approximate xfloat disabled, Relaxed Zcull enabled, and vblank rate at 120hz. Test again with Default settings

**Comment by Kimex123** [comment]
Setting zcull accuracy to precise fixed it, thank you so much.
