### ISSUE TITLE
[Regression] Headlights render incorrectly in Gran Turismo 5 (#11665).

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#12426]
### Quick summary

Car headlights are supposed to be transparent, but after the MSAA rework (#11665), they are black.

### Details

This is how it is meant to look:
![image](https://user-images.githubusercontent.com/61447828/181924815-1703ac92-9d62-4ac6-92a6-61a51351d5bb.png)

This is how it looks now:
![image](https://user-images.githubusercontent.com/61447828/181924905-1d4b7a66-9744-4b46-8773-335f1cd0a6e5.png)
Nice performance boost though! :)

### Build with regression

v0.0.21-13354-bc7ed8ea

### Attach two log files

Latest version Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9226839/RPCS3.log.gz)
Last working version Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9226844/RPCS3.log.gz)

### Attach capture files for visual issues

RSX Capture: [BCUS98114_20220730145530_capture.zip](https://github.com/RPCS3/rpcs3/files/9226846/BCUS98114_20220730145530_capture.zip)
Captura Renderdoc: https://drive.google.com/file/d/1D5NwK3fObAG5aU-9-1KS-7WaktqHsX4S/view?usp=sharing

### System configuration

Ryzen 5 5600x, GTX 1050 Ti Driver 516.59, Windows 11.

**Comment by gunther66** [comment]
Enabling Strict Rendering Mode seems to fix the issue for me, but probably more testing should be done to make sure it does the job. Using the latest version as of today **(0.0.27-14812)**

I'm also using the recommended config from the [wiki](https://wiki.rpcs3.net/index.php?title=Gran_Turismo_5):

- SPU block size = **Mega**
- Accurate RSX reservation access = **On**
- RSX FIFO accuracy = **Atomic**
- Driver Wake-up delay = **200 μs**

Plus Strict Rendering Mode = **On**, Default Resolution = **1920x1080** and the **Unlocked FPS** game patch.

**System config:**

- Ryzen 5 5600x
- 32 GB DDR4-3200 RAM
- RTX 3080 (driver ver. 531.18)
- Windows 11 22H2

![Untitled](https://user-images.githubusercontent.com/30203492/224553451-52a68dcf-646d-479f-a559-73b2e19dda5c.png)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/14130
