### ISSUE TITLE
Transparent Characters Bug In Dragon Ball Z: Ultimate Tenkaichi

### ISSUE THREAD

**Issue by DanielBlupi** [RPCS3/rpcs3#12421]
### Quick summary

the characters in the game have no color, they're just transparent, everything else works fine

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9223324/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1YD0faz-WJ6dGsWmVARKmfzo5KAjaPcGh/view?usp=sharing

### System configuration

CPU: Ryzen 7 5800X
GPU: RTX 3060
MB: ASUS PRIME X570-P
OS: WINDOWS 10

**Comment by DanielBlupi** [comment]
![unknown](https://user-images.githubusercontent.com/22030177/181845827-aa043eb8-1066-4149-8c35-1890fc8a0de6.png)

**Comment by SSBGod3225** [comment]
Yes that I have the same exact problem has you and I'm not sure how to fix that. I also have the same GPU has you.

**Comment by NevroseGame** [comment]
I had a GTX 1050 Ti no problem since I got the 3060 it does the same to me as you :/

**Comment by Asinin3** [comment]
This was possibly fixed by the new shader quality setting (set to high).
Retest please.

**Comment by Triticum0** [comment]
It seems to be fixed (https://forums.rpcs3.net/thread-205109.html) ask FlexBy if you want it retested before closing the issue. They pretty much both have very similar hardware specs. It is the picture right at the bottom for reference

**Comment by Triticum0** [comment]
Can This be closed then?
