### ISSUE TITLE
FIFA STREET Running like slow motion in bursts

### ISSUE THREAD

**Issue by YabrakProds** [RPCS3/rpcs3#12430]
### Quick summary

After a few minutes of gameplay the game starts running like it's on slow motion, 

### Details

Game starts looking like slow motion and has the sound distorted. the FPS drops down to like 40 fps and isn't choppy or anything, it just plays like slow motion and there's the sound distorting issue, monitoring the CPU and GPU usage didn't show any notable anomalies.
I've tried a few different fixes I saw and even tried to run default config but nothing worked, 
The real issue is that i know my laptop can handle it;
I'm running an ROG laptop with the Ryzen 7 6800H and RTX 3060 running at 140W, 16GB DDR5 and an SSD 
the kicker is that my friend's laptop ran the game no problem last week and he has worse specs than me, he has an HP laptop with a Ryzen 7 5800H and RTX 3050 Ti also with 16GB ram and running on the SSD
I guess i should also note that the only variable that is known to me is that on his laptop we started the game from scratch and so had a clean save but in my case i imported the save file from his computer to continue with my progress, but i don't think that would be the cause of such problem.
Hope someone can help.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9228601/RPCS3.log.gz)

**Comment by MSuih** [comment]
Github is not for help requests
