### ISSUE TITLE
Tales of Graces F (BLES01617)  freezes during operation.

### ISSUE THREAD

**Issue by LoneWolf31589** [RPCS3/rpcs3#12433]
### Quick summary

Chaotic emulator freezes during operation, regardless of the operating time. It can hang up after 20 minutes, it can work normally for several hours.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9228952/RPCS3.log)

### System configuration

i7 9700F
32 Gb DDR4
GTX970, 516.59 driver version
Windows 10

**Comment by LoneWolf31589** [comment]
Log/
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9328710/RPCS3.log)

**Comment by LoneWolf31589** [comment]
![image](https://user-images.githubusercontent.com/90130977/186241206-e7113849-a8a5-44d4-9068-f724a5435615.png)

**Comment by Asinin3** [comment]
No fatal error in log, no steps to reproduce. This issue report isnt very helpful for us so I have closed it. If it still happens and you can provide more info on how to get this to occur, raise a new issue with all the info.
