### ISSUE TITLE
Skylanders Swap force colours do not seem to work

### ISSUE THREAD

**Issue by CosmicGrog** [RPCS3/rpcs3#12437]
### Quick summary

the colours of skylander swap force are completely off

### Details

When playing skylanders Swap force the colours do not seem to work properly, they are completely off and have tried changing all graphical settings to fix, none worked.
![image_2022-08-01_140304839](https://user-images.githubusercontent.com/110400400/182153948-cea6ce14-fa83-492d-9426-e23262201923.png)
this is what colours are meant to look like on a ps3
![image](https://user-images.githubusercontent.com/110400400/182154892-afee7780-ed81-4ef8-b74e-db44d52cfa69.png)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9234143/RPCS3.log.gz)

### Attach capture files for visual issues

https://www.dropbox.com/s/9dsp6dobgld2yff/BLUS31076_20220801140314_capture.rrc?dl=0

### System configuration

CPU - i9-10900k
GPU - RTX 3070

**Comment by RipleyTom** [comment]
Same issue as https://github.com/RPCS3/rpcs3/issues/12437

**Comment by MSuih** [comment]
Closing as duplicate
