### ISSUE TITLE
Contrast issue on welcome message

### ISSUE THREAD

**Issue by Sandwich1699975** [RPCS3/rpcs3#12445]
### Quick summary

The contrast of blue and grey on mac systems makes the links unreadable

<img width="666" alt="image" src="https://user-images.githubusercontent.com/50229842/182358295-0c4e906d-b67c-4fd0-9cbc-de56f0b7ca9a.png">

### Attach a log file

N/A

### System configuration

MacBook Pro (14-inch, 2021)
System Version:	macOS 12.4 (21F79)

Dark mode activated

**Comment by Darkhost1999** [comment]
By -> dark mode activated. Do you mean that your Operating System is force changing the default theme against it's will?
Or are you using a dark mode theme in your global configs -> GUI tab?

I see this as an Operating System specific "enhancement" that should be configurable in your OS settings called "Force Dark mode on all Applications" or whatever apple named it.

**Comment by Sandwich1699975** [comment]
> By -> dark mode activated. Do you mean that your Operating System is force changing the default theme against it's will?

This is the system dark mode. Not the application. 

It overrides the Mac GUIs.

Happens on tkinter applications as well 

> I see this as an Operating System specific "enhancement" that should be configurable in your OS settings called "Force Dark mode on all Applications" or whatever apple named it.

It's not a "forced setting". It's just the theme selection

---

Should I close this issue?
