### ISSUE TITLE
[BLES00246] Ver. 2.0 MGS4 Crash in Act V anytime accessing / leaving in-game menu

### ISSUE THREAD

**Issue by Dysprosius** [RPCS3/rpcs3#12449]
### Quick summary

**Background**
After getting to Act V in the game with a few, but bearable problems, hang-ups, and crashes. I have encountered a game-ending bug for me, where you have to pick up and equip one of the dolls from Screaming Mantis. Anytime I access the menu while on Outer Haven ship - albeit to visit drebin's store, swap weapons, or items, the game will freeze / hang and crash on the menu exit. 

**Logs and Errors**

- - E {PPU[0x1000032] Thread (STGDEC) [0x000327c4]} SYS: 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
- S {SPU LLVM} SPU: New block compiled successfully x2400
- U {SPU LLVM} SPU TODO: [0x70f0] Const SHUFB mask: 0x80808003808080038080800380808003
- U {SPU LLVM} SPU TODO: [0x73a4] Const SHUFB mask: 0x80808003808080038080800380808003
- U {SPU LLVM} SPU TODO: [0x73b4] Const SHUFB mask: 0x80808007808080078080800780808007
- S {SPU LLVM} SPU: New block compiled successfully x9
- U {SPU LLVM} SPU TODO: [0x73a4] Const SHUFB mask: 0x80808003808080038080800380808003
- U {SPU LLVM} SPU TODO: [0x73b4] Const SHUFB mask: 0x80808007808080078080800780808007
- S {SPU LLVM} SPU: New block compiled successfully x28
- F {PPU[0x1000001] Thread (MGS4 MAIN) [0x308a3c8c]} VM: Access violation reading location 0xd4

**Settings**
Running RPCS3 0.08-9808-cab1766d Alpha
[BLES00246] with all the latest updates and stability fixes. 
Have compiled and implemented a number of configuration settings for optimal game play (and made it to act V, so it's been decent. Have had to only clear the PPU cache once - during a power outage while loading, and several SPU cache clears.
CPU
![image](https://user-images.githubusercontent.com/24706315/182440109-c176461d-973a-48f1-8c91-2137eaa362e1.png)
GPU
![image](https://user-images.githubusercontent.com/24706315/182440204-0b7684d4-4afe-478f-bd6e-f667e9afbb20.png)
Audio
![image](https://user-images.githubusercontent.com/24706315/182440268-f0e6c1f2-6e55-4cc8-8449-cb4dbf193633.png)
Advanced
![image](https://user-images.githubusercontent.com/24706315/182440366-b36f5e39-8e51-4dc4-8cac-b45264d7c685.png)

**System Info**
i5-9600k 
32GB Ram
Windows 10 64bit
RTX 3070ti with up to date drivers

Please let me know if my settings are goofed, or if this is a known issue. Thanks in advance!

### Details

Gameplay has been mostly good, audio hang-ups, and some frame tearing / glitching. Still almost completely playable with the settings posted above

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9244539/RPCS3.log)

### System configuration

i5-9600k 
32GB Ram
Windows 10 64bit
RTX 3070ti with up to date drivers

**Comment by elad335** [comment]
A prehistoric RPCS3  build.

**Comment by Dysprosius** [comment]
May have overwritten the latest build files with some of the older work arounds. I'll revert and report back.
