### ISSUE TITLE
Cannot compile RPCS3 using Visual Studio 2022

### ISSUE THREAD

**Issue by HarmeetHeer** [RPCS3/rpcs3#12446]
Hello.

Nice to meet you all. I am completely new here so forgive my ignorance.

I am currently trying to compile RPCS3 on Visual Studio, but it's stuck at: "Done building project "libcurl.vcxproj"., and will not proceed any further with the building of emulator. This has been going on for more than 3 hours. I am using the Intel i7-7500U CPU, which should be sufficient enough to compile RPCS3.

I have also went to this link: https://github.com/RPCS3/rpcs3/blob/master/BUILDING.md, and this link: [https://wiki.rpcs3.net/index.php?title=H...ding_RPCS3](https://wiki.rpcs3.net/index.php?title=Help:Building_RPCS3), and I can confirm that I have all the dependencies to compile RPCS3. 

Visual Studio 2022 (latest build) and the Visual C++ packages have been uninstalled, and reinstalled on my Windows 10 Device, but it's still encountering the same issue as before.

Please find screenshots attached. 

If anymore information is required, please let me know.

Many thanks

![Visual Studio 2](https://user-images.githubusercontent.com/22887239/182392069-98663076-6ef2-472d-8db8-8827af35f1ab.png)
![Visual Studio](https://user-images.githubusercontent.com/22887239/182392075-57643838-98a5-4436-ae3c-d7daa47716d6.png)
.

**Comment by MAGNIFI88** [comment]
Hello. Did you solved it? Im having the same problem
