### ISSUE TITLE
RPCS3 Freezing, then Crashing Randomly In-Game

### ISSUE THREAD

**Issue by TrueJoSephGD** [RPCS3/rpcs3#12448]
### Quick summary

RPCS3 has regularly been crashing with the "took too long to respond" error.

### Details

The game where these errors were occurring was Hamster Ball.  At seemingly random points, the game locks up and the CPU load is maxed out. When I go to reset the game, the emulator freezes up, then gives an error stating that it "took too long to stop the emulator".

### Attach a log file

[crash log.zip](https://github.com/RPCS3/rpcs3/files/9243193/crash.log.zip)

### System configuration

I'm playing this on a Lenovo Legion 5i with the following specifications:
CPU: Intel i7-10750H
GPU: NVIDIA GTX 1660-Ti Mobile
RAM: 16GB DDR4-2933
OS: Windows 11 Home
GPU Driver: GeForce Game Ready Driver version 516.59
Storage: Primary 512GB SSD and secondary 1TB HDD

### Other details

Settings were at their defaults.
The game was running in fullscreen at the time of the crash.
Laptop was plugged in at the time of the crash.
This only happens when the game is rendering 3D models.

**Comment by Triticum0** [comment]
@TrueJoSephGD Turn on SPU DMA to fix the issue.

**Comment by TrueJoSephGD** [comment]
This worked! Thanks!
