### ISSUE TITLE
[Feature request] Analog Limiter

### ISSUE THREAD

**Issue by AE605** [RPCS3/rpcs3#12453]
### Quick summary

Tying stick multipliers to a key for keyboard use.

### Details

**Version:** 0.0.23(Latest) Windows

**Request:** A feature that is present in PPSSPP which allows you to use half stick movement on keyboard.
Example: You can use Shift or any key to run so when you press Shift the multiplier value changes to 1 when you leave it, it changes to 0.5 or the other way around.
The other way around: Press Shift or any key to change the multipler to 0.5 so you walk and when you leave it, it changes back to 1.0.

**Comment by Megamouse** [comment]
We already have the button for pressure sensitivity.
Doesn't it also affect the sticks?

**Comment by Nydrogen** [comment]
> We already have the button for pressure sensitivity. Doesn't it also affect the sticks?

No, It doesn't work with the analog sticks.
I hope it will work with the sticks as well.
And an option to toggle it would be nice as well.
