### ISSUE TITLE
Text glitch in Ratchet & Clank Future: ToD and in Ratchet & Clank Future: QfB

### ISSUE THREAD

**Issue by EvilPlayer1** [RPCS3/rpcs3#12451]
### Quick summary

Big texts aren't "limited" by ingame interface. You'll always see full text on screen if it's bigger than interface.

### Details

RPCS3:
![BCUS98127_screenshot_2022_08_02_23_52_21](https://user-images.githubusercontent.com/90133207/182472159-ee56e235-110c-4524-9a83-4bbb063454ed.png)
PS3:
![Screenshot 2022-08-03 00-00-37](https://user-images.githubusercontent.com/90133207/182472515-1570a8c0-7a7b-4f07-bd9b-12be97328750.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9245626/RPCS3.log)

### System configuration

OS - Windows 11
CPU - i7-11700
GPU - GTX 1660 SUPER
Driver version - 516.59

**Comment by mfdsrax2** [comment]
You need to upload an RSX capture.

**Comment by EvilPlayer1** [comment]
[BCUS98127_20220803125543_capture.zip](https://github.com/RPCS3/rpcs3/files/9250288/BCUS98127_20220803125543_capture.zip)

**Comment by JimScript** [comment]
Apparently, this is only a problem on Vulkan.
OpenGL:

![BCUS98127_screenshot_2022_10_05_21_57_31](https://user-images.githubusercontent.com/66685584/194217967-6426c3b8-0d15-41e5-8a77-844aafb97cd5.png)

**Comment by Jonathan44062** [comment]
Ratchet & Clank: Quest for Booty
Vulkan
![image](https://user-images.githubusercontent.com/78843189/205778149-b94a7cdf-810d-4d5f-8755-dc3891fd498c.png)

OpenGL
![image](https://user-images.githubusercontent.com/78843189/205778858-c4d841de-628c-40b9-a6a6-ca61d7d5ec5d.png)

_______________________________________________________
RSX Captures:

RSX Vulkan
https://www.mediafire.com/file/ddrl1h2w8eyn25v/BCES00301_20221205184535_capture.rrc/file
RSX OpenGL
https://www.mediafire.com/file/xe9mbcr6uo0j24p/BCES00301_20221205185116_capture.rrc/file

**Comment by mathew2214** [comment]
Steam Deck, installed via emudeck. also having this issue.

**Comment by kd-11** [comment]
Ack. Forgot about this.

**Comment by Valtekken** [comment]
> Ack. Forgot about this.

I forgot to mention it in the other issue we were having with ToD (the DEVICE_LOST one) but yeah, can confirm this is still present and was present throughout testing of that issue

**Comment by Darkhost1999** [comment]
QFB Before
![image](https://github.com/RPCS3/rpcs3/assets/60384196/df498760-91e4-4dc5-a1ee-a60a134839f3)
After
![image](https://github.com/RPCS3/rpcs3/assets/60384196/9e3a274c-fd3f-43ed-a9e5-14e08fa357c6)
Confirming QFB fixed in PR. I don't have ToD.
