### ISSUE TITLE
Failed shader compilation on old Windows AMD drivers

### ISSUE THREAD

**Issue by jajackson67** [RPCS3/rpcs3#12452]
### Quick summary

Any game i try it rufesed to open

### Details

F {RSX [0x0009748]} RSX: swap_bytes not found.
F {RSX [0x0009748]} RSX: src_pitch not found.
F {RSX [0x0009748]} RSX: format not found.
F {RSX [0x0009748]} RSX: region_offset not found.
F {RSX [0x0009748]} RSX: region_size not found.
i get this everysingle time i try to launch a game then it crashes 

### Attach a log file

[rpcs3.log](https://github.com/RPCS3/rpcs3/files/9247354/rpcs3.log)

### Attach capture files for visual issues

[Help Me.zip](https://github.com/RPCS3/rpcs3/files/9247390/Help.Me.zip)

### System configuration

Dell XPS 8100
i7 2600 3.5Ghz Sandy Bridge

AMD Radeon 6670
Driver Version 15.201.1151.1008
12GB DDR3

**Comment by AniLeo** [comment]
```
F {RSX [0x0008d18]} RSX: Compilation failed: Compute shader failed to compile with the following errors:
ERROR: 0:8: error(#385) Binding point for: buffer block must be equal or greater than 0 and less than: GL_MAX_SHADER_STORAGE_BUFFER_OBJECT_BINDINGS
ERROR: 0:9: error(#385) Binding point for: buffer block must be equal or greater than 0 and less than: GL_MAX_SHADER_STORAGE_BUFFER_OBJECT_BINDINGS
ERROR: 0:125: error(#143) Undeclared identifier: data_in
ERROR: 0:125: error(#145) Left of "[" is not of type array, matrix, or vector: data_in
ERROR: 0:125: error(#160) Cannot convert from: "float" to: "highp unsigned int"
ERROR: 0:126: error(#143) Undeclared identifier: data_out
ERROR: 0:126: error(#145) Left of "[" is not of type array, matrix, or vector: data_out
ERROR: error(#273) 7 compilation errors. No code generated
```

I assume it's a bug with old AMD OpenGL drivers

**Comment by jajackson67** [comment]
RPCS Wont let me switch to vulkan
![RPCS3 0 0 23-14000-cd2adbad Alpha _ master 8_3_2022 8_58_51 AM](https://user-images.githubusercontent.com/35636904/182641069-84aded49-d4b6-43e9-80a3-f057fb5344e0.png)
n

**Comment by RainbowCookie32** [comment]
That's to be expected, your GPU doesn't support it

**Comment by jajackson67** [comment]
What about DirectX

**Comment by jajackson67** [comment]
Vulkan and DirectX works on stuff like Dolphin and ePSXe. PCSX2

**Comment by RainbowCookie32** [comment]
We don't have a Directx renderer anymore

**Comment by jajackson67** [comment]
But if my graphics card can do Vulkan on other Emus why dosent it work here

**Comment by jajackson67** [comment]
Okay then

**Comment by kd-11** [comment]
Let's leave it open until its fixed in master.

**Comment by jajackson67** [comment]
okay
