### ISSUE TITLE
Loading save state does not reflect custom config or patches.

### ISSUE THREAD

**Issue by jedinjapan** [RPCS3/rpcs3#12463]
### Quick summary

As it appears to be implemented, the save state feature is not loading a title with custom configurations or patches, and is loading with Global Defaults only.

### Details

If a user Boots using custom config, saves state, and resumes, the resumed state will be done under the global default config. This leads to obvious state de-sync issues in some titles, and for some titles requiring custom configuration settings being unable to resume a saved state.

This was tested on NPUB31633 - Metal Gear Solid 4. Under custom configuration the game runs semi-stable when using the recommended cell spur patch. For testing the game was played for 10 minutes before a save state was taken. Upon load, the game rendering resolution dropped drastically, and the title crashed within 20 seconds of gameplay. The test was repeated again, with the same results. The title appeared to have loaded under the global defaults.

The issue is also readily apparent if the Global Default rendering resolution is left at 720p defaults, while the custom resolution scaling is increased on a per-title bases. On load of the save state, the level of visual drop is readily apparent.

This was further verified by then adjusting the Global Rendering resolution and re-loading a backup of the same save state. This extended to all other global settings changed. Additionally, patches do not appear to be loading, and for this particular title this results in crashing due to the cellspurs urgent commands patch being absent when the save state is loaded.

It was suggested that this may be due to RPCS3 failing to identify the game ID upon loading the state, and thus failing to load the appropriate patches and associated custom profile, returning to global defaults.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9264359/RPCS3.log.gz)

### System configuration

- SYS: RPCS3 v0.0.23-14007-88b80ebd Alpha | master
- SYS: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz | 16 Threads | 31.92 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3 | TSX
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 22000, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 512.59.0.0
- SYS: Firmware version: 4.88

**Comment by elad335** [comment]
Test #12464

**Comment by jedinjapan** [comment]
> Test #12464

In testing, appears to resolve issue with Custom Config versus Global Config, and Custom Config parameters are loaded corrected now. (Resolution/ Performance Overlay/ etc)

Based on 30 minutes of mild stress testing in combat zone outside of Advent Palace in Act 1, cellspur patch appears to be loading correctly with the save state as well. In most cases this part of the zone will somewhat consistently crash within 1-2 minutes of combat due to a high frequency of explosions and physics objects otherwise if the patch is not active.

Amazing work and incredibly rapid response to this issue.

**Comment by elad335** [comment]
Don't close the issue until the pull request is merged.

**Comment by MasterChief747** [comment]
I don't understand. Please help! How does that linked article 12464 help in making patches work in save states? Does that file need to be edited? I can't find it. Is it in a different location in the updates of RPCS3 2 years later? Thank you!
