### ISSUE TITLE
Modnation Racers/Littlebigplanet Karting shadow maps broken with Linux Vulkan

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#12462]
### Quick summary

On Steam Deck, the shadow maps in these 2 games are broken, while my windows 10 PC is just fine.

### Details

Steam Deck:
![20220804141455_1](https://user-images.githubusercontent.com/66685584/182954684-d12734d0-62a7-4af3-ade5-6e3f35e969d3.jpg)

Windows 10/Ryzen 5 3600/RTX 2070 Super:
![BCUS98167_screenshot_2022_08_04_18_13_53](https://user-images.githubusercontent.com/66685584/182981297-b5d00015-4c90-4542-8a2d-ce74439c7487.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9263003/RPCS3.log)

### Attach capture files for visual issues

Steam Deck:
[BCUS98167_20220804130835_capture.rrc.zip](https://github.com/RPCS3/rpcs3/files/9263065/BCUS98167_20220804130835_capture.rrc.zip)

Windows 10:
[BCUS98167_20220804181040_capture.zip](https://github.com/RPCS3/rpcs3/files/9264445/BCUS98167_20220804181040_capture.zip)

### System configuration

- SYS: RPCS3 v0.0.23-14007-88b80ebd Alpha | master
- SYS: AMD Custom APU 0405� AmdCcxVhFf3PeiInit Entry
| 8 Threads | 14.49 GiB RAM | TSC: 2.800GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 5.13.0-valve21-1-neptune-02209-g2a5bdc1102a0, Version: #1 SMP PREEMPT Thu, 07 Jul 2022 23:29:00 +0000
- SYS: Current Time: 2022-08- 4T13:24:21
- RSX: Found vulkan-compatible GPU: 'AMD RADV VANGOGH' running on driver 22.1.99
- SYS: Firmware version: 4.85

### Other details

It isn't due to the low thread count because I lowered the max spurs threads on both systems and they acted the same.

**Comment by JimScript** [comment]
I just checked to see if OpenGL fixes it, and yes it does(but it introduces some UI glitching with the loading screen).

**Comment by kd-11** [comment]
Still an issue?

**Comment by JimScript** [comment]
![20230617051527_1](https://github.com/RPCS3/rpcs3/assets/66685584/3453856e-568d-421e-ad17-7986cd4cb8b0)
Yeah, this is still an issue.

**Comment by JimScript** [comment]
Huh, turns out this was fixed over a month ago by #14101, so I'm just going to close this issue(unless I need more data to so).
