### ISSUE TITLE
start the game after #12319 (0.0.23-13961), it ends without an error.

### ISSUE THREAD

**Issue by kyh96403** [RPCS3/rpcs3#12473]
### Quick summary

The game list looks normal, but when start the game, it just close without any error message.
Previous versions(#12371 (0.0.23-13960)) have no problem at all.

As a result of various tests, if there is a problem with non-alphabetic characters in the executable file path, the problem occurs.
If you specify the path for RPCS3 as "K:\PS3 애뮬", you will have a problem.

### Details

https://user-images.githubusercontent.com/21171837/183270272-1072c2ef-5250-46ae-998c-e2ba45657ba1.mp4

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9275965/RPCS3.log)

### System configuration

CPU: 12th Gen Intel(R) Core(TM) i9-12900K 3.20 GHz
32G memory
GPU: NVIDIA 1050, driver: 30.0.15.1295

**Comment by Nekotekina** [comment]
@Megamouse I can see possible misuse of std::filesystem in #12319

**Comment by elad335** [comment]
Test with #12474

**Comment by kyh96403** [comment]
@elad335
That is fixed !!.
Thanks^^

**Comment by Darkhost1999** [comment]
Don't close until PR is merged

**Comment by Darkhost1999** [comment]
oops k was merged 6 hours ago

**Comment by MSuih** [comment]
The pull request was merged so this can be closed.
