### ISSUE TITLE
build problems on llvm

### ISSUE THREAD

**Issue by 111111111111111111111111** [RPCS3/rpcs3#1247]
the project compiles good apart from one error when compiling rpcs3
It says fatal error can't find asmjit.lib

**Comment by sasukedotca** [comment]
already solved here : https://github.com/RPCS3/rpcs3/issues/1234

**Comment by 111111111111111111111111** [comment]
Thanks

**Comment by Zangetsu38** [comment]
@111111111111111111111111  @sasukedotca fixed here in My PR 
https://github.com/RPCS3/rpcs3/pull/1242

**Comment by Bigpet** [comment]
should be fixed, comment if the issue is still present
