### ISSUE TITLE
[Regression] Can't get past start streen in GT6

### ISSUE THREAD

**Issue by Boiiiiiiiiiiiiiiiiiiii** [RPCS3/rpcs3#12479]
### Quick summary

To start GT6, I have to press return aka the start button if I was using a keyboard. Now when I do that, nothing happens. This issue isn't present in any other game but this one. 

### Build with regression

After testing, I can confirm that v0.0.23-14027-2ec03936 is the one causing the issue

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9277725/RPCS3.log) v0.0.23-14014
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9282753/RPCS3.log) v0.0.23-14027

### System configuration

CPU: Ryzen 5 2600
GPU: GTX 1080 
RAM: 16GB 3200MHZ

### Other details

game usual runs at 23 to 30 fps, engine locks up sometimes because the game is unstable after all.

**Comment by Nerboruto** [comment]
try disabling "enable background input" in the i / o tab. I had a weird keyboard input bug getting disabled while playing GOW GOS and it fixed

**Comment by Boiiiiiiiiiiiiiiiiiiii** [comment]
> try disabling "enable background input" in i/o tab. I had a weird keyboard input bug getting disabled while playing GOW GOS and it fixed.

still doesn't work

**Comment by Boiiiiiiiiiiiiiiiiiiii** [comment]
I'm testing 0.0.23-14027 to see if this one might be the issue

**Comment by Darkhost1999** [comment]
Potential fix for your issue was merged to master. Please update RPCS3 and try again.

**Comment by Satan86** [comment]
Fixed.
