### ISSUE TITLE
Regression: Broken graphics in OpenGL on NieR Replicant (#12454)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#12476]
![image](https://user-images.githubusercontent.com/10283761/183305999-028e866e-fdd2-4b3f-b6d3-586689961255.png)

How to reproduce:
1. Boot NieR Replicant (Default Settings + Write Color Buffers)
2. Load into the village
3. Walk around for a few seconds

Tested with radeonsi with an RX 6700M on stable and git mesa:
- mesa-git 22.3.0_devel.157760.4148a525201a
- mesa-22.1.4-1

I can't upload the RSX capture because there's now a 25 MB limit on uploads, but kd-11 has this test case locally so it shouldn't be required.

**Comment by AniLeo** [comment]
I have bisected this to be a regression from #12454

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/12676
Unfortunately I also re-discovered the previously known https://github.com/RPCS3/rpcs3/issues/12675 which I had forgotten existed.
