### ISSUE TITLE
Compilation fails on MacOS Ventura

### ISSUE THREAD

**Issue by DarthNihilus1** [RPCS3/rpcs3#12477]
### Quick summary

Compiling is not working correctly.
It fails on 
ninja && codesign --force --deep --sign - bin/rpcs3.app/Contents/MacOS/rpcs3

### Attach a log file

[message.txt](https://github.com/RPCS3/rpcs3/files/9277345/message.txt)

### System configuration

Apple M1
8 GB ram
Ventura 13.0

**Comment by shinra-electric** [comment]
I had an issue that looks similar to this on Monterey, and I got past it by uninstalling qt@6.

Can you try that?

**Comment by DarthNihilus1** [comment]
Omg it worked thank you!
