### ISSUE TITLE
[Regression] Battle of Z 

### ISSUE THREAD

**Issue by Oldmanskills** [RPCS3/rpcs3#12484]
### Quick summary

The game gets into a black screen after initial loading

### Details

This bug doesnt occurs on old build 0.0.9-10005 but does on any latest builds.

### Build with regression

v0.0.23-14032-47f3740a Alpha

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9279718/RPCS3.log)
https://mega.nz/file/MD91DBSK#wp97SdKiW5uCO9q8hXvWaEXiVoYsycukxFMMbowJF90

### Attach capture files for visual issues

![Screenshot 2022-08-08 032257](https://user-images.githubusercontent.com/110811302/183362531-2d2766d7-e719-4c96-b9e4-696609c48a3b.jpg)
![Screenshot 2022-08-08 032257](https://user-images.githubusercontent.com/110811302/183362534-faeb4594-91fe-48bd-9fcf-41da27e6e923.jpg)

### System configuration

i9-9900k
rtx3080
32gb of ram 
win11

**Comment by AniLeo** [comment]
Invalid range for regression, not only is it bigger than 1 PR, it spans 14 different tags

**Comment by Oldmanskills** [comment]
What information do you need? im just trying to help. I understand that the old build is super old but that is still a regression maybe a regression nobody reported but still is. So i get your comment it means that still its too old you wont fix it? if that so alright.

**Comment by AniLeo** [comment]
Follow the regression template and perform a bisect, we need the build that introduced the issue, otherwise we can't know what broke it and who to assign to the regression.

**Comment by Oldmanskills** [comment]
Make a lot of sense. i guess i can try to figure this out for you guys and go from that working build and up

**Comment by RipleyTom** [comment]
I tested, seems to work, reopen if that's still an issue.
