### ISSUE TITLE
[Regression] GTAV Freezing

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12480]
GTAV is freezing within 15 seconds of starting the game. Possibly related to the swap character and view character stats feature because trying to look at that seemed to act as a trigger for me if at first it wouldn't freeze.

### Build with regression

v0.0.23-14027-2ec03936

### Attach two log files

[Broken.log.gz](https://github.com/RPCS3/rpcs3/files/9277868/RPCS3.log.gz)
[Working.log.gz](https://github.com/RPCS3/rpcs3/files/9277871/RPCS3.log.gz)

### System configuration

Ryzen 5 3600
GTX 1660 Super
Windows 11 Home

### Other details

I was playing as Trevor preparing for Merryweather heist outside Floyd's safehouse and the game wouldn't even let me move at all without freezing.

**Comment by elad335** [comment]
Try 4 PPU threads with both the pr and pr and upload logs, also log kernel explorer.

**Comment by Darkhost1999** [comment]
So use both cirrus builds for the working and non-working builds.
With 4 PPU threads. Log kernel explorer before and if possible after the issue?

**Comment by elad335** [comment]
Yes.

**Comment by Darkhost1999** [comment]
[4 PPU Threads 12378](https://github.com/RPCS3/rpcs3/files/9278254/RPCS3.log) working.
[2 PPU Threads 12378](https://github.com/RPCS3/rpcs3/files/9278268/RPCS3.log) not working. Didn't get a before log for kernel explorer.

[4 PPU Threads 12470](https://github.com/RPCS3/rpcs3/files/9278286/RPCS3.log) working.
[2 PPU Threads 12470](https://github.com/RPCS3/rpcs3/files/9278310/RPCS3.log) working.

The PS3 only has 2 PPU threads right? I'm fine with using 4 if I was confident I have the threads to spare. Why does 4 work but 2 doesn't?

**Comment by elad335** [comment]
#12482 may or may not affect this.

**Comment by Darkhost1999** [comment]
No change
[2 PPU Threads](https://github.com/RPCS3/rpcs3/files/9281267/RPCS3.log.gz) not working
[4 PPU threads](https://github.com/RPCS3/rpcs3/files/9281300/RPCS3.log.gz)  still working

**Comment by coolllman** [comment]
Same Infamous 2, 2 ppu not working, 4 ppu working

**Comment by Darkhost1999** [comment]
https://github.com/RPCS3/rpcs3/pull/12482/commits/e7e3094e28b9fd70751997d7d84a247017b72307
![image](https://user-images.githubusercontent.com/60384196/183422072-abeeb252-b794-45b4-9697-aba6cde9a8f1.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9281781/RPCS3.log)
Working

**Comment by Darkhost1999** [comment]
Freezing cb095def
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9285250/RPCS3.log.gz)

**Comment by Darkhost1999** [comment]
bf4791f5 back to working again
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9292174/RPCS3.log)
