### ISSUE TITLE
[Regression] GoW freezing (crash) frequently.

### ISSUE THREAD

**Issue by Plaer1** [RPCS3/rpcs3#12489]
### Quick summary

God of War 1 from the collection cd used to work fine but on builds after [#12378](https://github.com/RPCS3/rpcs3/pull/12378) it freezes so often sometimes I cannot make it past the main menu.

### Details

The game randomly completely locks up, almost always within minutes, sometimes much faster.

### Build with regression

#12378

### Attach two log files

[RPCS3.log (broken)](https://github.com/RPCS3/rpcs3/files/9286115/RPCS3.log)

[RPCS3.log (working)](https://github.com/RPCS3/rpcs3/files/9286149/RPCS3.log)

### System configuration

Operating System
	Windows 11 Pro Insider Preview 64-bit
CPU
	AMD Ryzen Threadripper 3960X
	Castle Peak 7nm Technology
RAM
	64.0GB Unknown @ 1177MHz (15-15-15-35)
Motherboard
	Gigabyte Technology Co. Ltd. TRX40 AORUS PRO WIFI (SP3r2)	
Graphics
	Acer CB281HK (3840x2160@60Hz)
	LG ULTRAWIDE (2560x1080@60Hz)
	Acer V223W (1680x1050@59Hz)
	3071MB NVIDIA GeForce GTX 1080 Ti (ZOTAC International)	
Storage
	223GB ZOTAC ZTSSD-A5P-240G-PE (SATA (SSD))	
	465GB SanDisk Ultra II 500GB (SATA (SSD))	
	931GB Western Digital WDC WD10EADS-00M2B0 (SATA )	
	2794GB TOSHIBA HDWD130 (SATA )	
	931GB Samsung SSD 970 EVO 1TB (Unknown (SSD))
	29GB Lexar USB Flash Drive USB Device (USB )
Audio
	Realtek USB Audio

### Other details

The freeze happens randomly but never takes more than like ~10min for the game to hang.

**Comment by Plaer1** [comment]
(I'm only pretty sure it was new to that build, but I'm sure that one has the bug)

**Comment by sampletext32** [comment]
damn, you have a lot of storage :)

**Comment by Plaer1** [comment]
>
