### ISSUE TITLE
[Regression] Atelier Shallie not working after update

### ISSUE THREAD

**Issue by luckyskyler12** [RPCS3/rpcs3#12483]
### Quick summary

Game freezes before menu after update v0.0.23-14032.

Game name/serial: Atelier Shallie ~Alchemists of the Dusk Sea~ [BLUS31525]

### Details

After updating to RPCS3 v0.0.23-14032, the game* would freeze as it's about to play the intro video, before the menu screen.

I rolled back incrementally to the previous versions (v0.0.23-14031 / v0.0.23-14030 / v0.0.23-14027), and none of them worked. The game does work once you roll back to v0.0.23-14014.

Oddly, after rolling back to v0.0.23-14014, I tried rolling forward incrementally to the three versions mentioned previously (v0.0.23-14031 / v0.0.23-14030 / v0.0.23-14027) and the game seemed to work just fine. But the game freezes again once you update to v0.0.23-14032.

Summary:
Game breaks at v0.0.23-14032
Game is stable at v0.0.23-14014

*Game: Atelier Shallie ~Alchemists of the Dusk Sea~ [BLUS31525]

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9279580/RPCS3.log.gz)

### System configuration

CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
GPU: NVIDIA GeForce GTX 1660 Ti

**Comment by elad335** [comment]
Test #12482

**Comment by Darkhost1999** [comment]
Potential fix for your issue was merged to master. Please update to the latest changes and try again.

**Comment by luckyskyler12** [comment]
Updated to v14045, confirmed fix works.

Able to get past the menu screen, save file, etc. Closing ticket.
