### ISSUE TITLE
[Regression] Black ops 1 zombies freezing

### ISSUE THREAD

**Issue by guy224444** [RPCS3/rpcs3#12487]
### Quick summary

The game froze and stopped working in the zombies mode on maps kino der toten and call of the dead around round 2 or 3 on the current build (0.0.23-14032).  This issue was not present in build version 0.0.23-14014 (I didn't have dlc or updates installed when playing bo1 on this version) and this regression started with build 0.0.23-14027.  DLC and update 01.13 of bo1 was installed when I played on versions 0.0.23-14032 and 0.0.23-14027.

### Details

Game plays fine up until it freezes around round 2 or 3, then I am unable to continue the game and have to stop it.  Game was played on all builds at default settings.  Game version tested is BLUS30591

### Build with regression

v0.0.23-14027

### Attach two log files

(not working: v0.0.23-14027)- [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9282995/RPCS3.log)
(working: v0.0.23-14014)- [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9283081/RPCS3.log)

### System configuration

Windows 10, 
AMD Ryzen 7 4800H Processor, 
NVIDIA GTX 1660Ti

**Comment by Darkhost1999** [comment]
Potential fix for your issue has been merged to master. Please update RPCS3 to the latest changes and try again.
