### ISSUE TITLE
Regression: Very low framerates, below 5 fps (#11607)

### ISSUE THREAD

**Issue by Xephobia** [RPCS3/rpcs3#12499]
### Quick summary

When testing a recent commit, I found that games are unplayable, I tracked the build that started this regression to https://github.com/RPCS3/rpcs3/pull/11607

### Details

metal gear solid 4
v0.0.21-13343 :
![image](https://user-images.githubusercontent.com/28755060/184119123-ab2314f4-f014-4006-9ac9-315089a464d4.png)

v0.0.21-13335 :
![image](https://user-images.githubusercontent.com/28755060/184119772-dd44c4f0-69d0-4cb9-80fd-c8d87336fac4.png)

### Build with regression

v0.0.21-13343

### Attach two log files

v0.0.21-13343 :
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9308081/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9308082/RPCS3.log)

v0.0.21-13335 :
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9308117/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9308118/RPCS3.log)

### System configuration

OS : Linux
uname -a : `Linux xephlap 5.19.0-267-tkg-pds #1 TKG SMP PREEMPT_DYNAMIC Tue, 02 Aug 2022 16:44:09 +0000 x86_64 GNU/Linux`
CPU : `AMD Ryzen 5 5600H with Radeon Graphics`
GPU: `NVIDIA GeForce RTX 3060 Mobile / Max-Q`
GPU driver version : `515.65.01`
RAM : 19GiB

**Comment by kd-11** [comment]
Does disabling msaa help?
This seems like some system-specific thing. This is the first report in several months which means something's not going well with your particular setup.

**Comment by Xephobia** [comment]
> 

disabling anti aliasing increase the fps to ~5 but the issue is still there

**Comment by kd-11** [comment]
I have no idea why then. Performance increased or remained the same on all my setups with the PR.
Can you capture a trace with perf and screenshot the analysis?

**Comment by Xephobia** [comment]
> I have no idea why then. Performance increased or remained the same on all my setups with the PR. Can you capture a trace with perf and screenshot the analysis?

Hi, sorry for the late reply, here is the perf data that I recorded : https://www.mediafire.com/file/n6d1i8vew2rn2gi/perf.data/file

**Comment by kd-11** [comment]
All that the perf data says here is that rsx is spending most of the time outside the application but inside the kernel.

**Comment by kd-11** [comment]
By the way, are you using a local build or appimage? If you're using appimage, consider building local.
If I had to guess, something about the custom kernel here is breaking rpcs3. You may want to also test with a stock upstream kernel.

**Comment by Xephobia** [comment]
Sorry for the late reply, can confirm this is still happening with the stock arch kernel

**Comment by Xephobia** [comment]
nevermind, i can get a smooth output but with freezes
https://drive.google.com/file/d/15tQ-n--2X1zM5hQwaI_io4Kd-hKb84yJ/view?usp=share_link

**Comment by Megamouse** [comment]
please try again

**Comment by Aadik1ng** [comment]
hey bro i have identical setup 3060 with fedora i am getting <50fps with lots of fluctuation
