### ISSUE TITLE
Tekken Tag Tournament 2 [BLES01702] - Intro FMV Fails to Load After Arbitrary Number of Cycles

### ISSUE THREAD

**Issue by Fukuzatsu** [RPCS3/rpcs3#12497]
### Quick summary

Tekken Tag Tournament 2 [ID BLES01702] cycles through a demo mode and intro FMV video; after somewhere between 15 and 30 cycles of the intro, it will eventually fail to load and crash, preventing the user from starting the game.

### Details

I've been testing a handful of Namco's PS3 titles for use on an arcade cabinet, and recently have found a number of issues that seem to only apply when/if one were running it as an actual arcade game (i.e. left on demo mode for multiple hours). I have no issues getting in-game or playing the game itself, but after leaving it on the title screen for a length of time, it will no longer be able to load the intro FMV, and require a restart of RPCS3.

Incidentally, aside from running the game on both full default settings and default settings with the recommended wiki changes (in this case only "Write Color Buffers"), here are the other troubleshooting steps I've tried just to see if they result in any different behaviour:
Toggling libvdec.sprx for LLE/HLE
Toggling libavcdec.sprx for LLE/HLE
Toggling Accurate RSX Preservation, setting RSX FIFO Accuracy to 'Atomic', Driver wakeup delay to 40

Each of the three above settings configurations were tested in isolation and all resulted in the same type of crash/hang.

I also attempted to run the game on an earlier iteration of RPCS3 (0.0.20.13245, to be specific) to see if perhaps this was a regression-related issue. At the very least on that version, the problem was still present in the same way.

Finally, I verified my copy of the game through PS3-ISO-Builder and found no file issues.

The log file attached below is for my test run of the game in demo mode on version 0.0.23.14014, with settings set to default aside from Write Color Buffers and Resolution Scale set to 200%.

I suspect the issue has something to do with the message produced by the log whenever it occurs, specifically this entry:
·E 0:18:22.392661 {PPU[0x1006020] HLE Video Decoder} cellVdec: Video au decode has been waiting for a consumer for 5 seconds. (handle=0xf0000b00, seq_id=1, cmd_id=66, queue_size=61)
·E 0:18:29.494872 {PPU[0x1006020] HLE Video Decoder} cellVdec: Video au decode has been waiting for a consumer for 5 seconds. (handle=0xf0000b00, seq_id=1, cmd_id=66, queue_size=61)

From looking at other issue logs it appears this has to do with the system waiting to decode a video file prior to playing it, but it does not appear to be working correctly to load the video after a certain number of cycles. It does not seem that this message appears in prior "demo cycles", only around the instance where the video fails to load.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9307919/RPCS3.log)

### System configuration

GPU: NVIDIA GeForce RTX 3050 8GB DDR6
11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz | 12 Threads | 15.84 GiB RAM | TSC: 2.592GHz | AVX-512+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22000, Service Pack: none, Compatibility mode: 0

**Comment by Fukuzatsu** [comment]
One other note while I was looking into potential solutions for this, but #11890 appears to have been a similar issue (or at least resulted in the same log message indicating a video would load but ultimately did not). Doesn't appear to have been resolved, but as mentioned in the main post I was able to reproduce this issue on an earlier build prior to the regression claimed in 11890.

**Comment by Megamouse** [comment]
Did you test this on a PS3?
If the issue is also present with LLE libvdec then it at least isn't a decode issue.
Could also be some unrelated deadlock.

**Comment by Fukuzatsu** [comment]
While I don't currently have the exact same version on-hand to test on real hardware at the moment, I do have a disc copy of the Japanese version (BLJS-50033), which I let run for approximately the same amount of time (the intro videos themselves are identical in content), and does not appear to have crashed/hung in the same way. I don't have any particular reason to believe this specific element with the FMV intro would operate differently between the two, though. One thing I did notice is that due to running on an SSD and better hardware and all that, RPCS3 loads the intro demo fights much faster than a real PS3. Perhaps the faster speed has some effect on timing?

As a note, the RPCS3 version crashed anywhere between 15 and 30 cycles of the intro in my testing (usually on the lower end of 20); on a real PS3 I couldn't get it to crash the same way even after more than 30 cycles.

**Comment by Fukuzatsu** [comment]
Given every Namco game has more or less the same setup for their intros (an FMV and/or a demo fight), I went ahead and tested all the ones I happen to have available (again under default or recommended settings); more of a contextual reference than anything.

**Tekken Tag Tournament 2 [BLES01702] - Crashes upon FMV load start at a random point in the intro cycle, but general gameplay runs correctly if intro is skipped.**
Tekken 5 Dark Resurrection [NPUB30009] - Crashes mid-FMV at a random point in the intro cycle, results in mid-game crashes dependent on returning to main menu.
Tekken 6 [BLES00635] - Runs correctly, does not seem to crash at all; I could not get it to crash after a full 24-hour test.
Tekken Tag Tournament HD [NPUB30590] - Runs correctly, both with FMV and demo battles. Tested cycling for over 2 hours.
SoulCalibur II HD [NPUB31366] - Similar to Tekken 6, seems to run correctly without crashing after a 24-hour test.
SoulCalibur IV [BLUS30160] - Runs correctly, though the "FMV" intro here appears to run in-engine rather than as a video file; also does not feature a demo battle. Presumably wouldn't have the same issue since it's not a video file being loaded, but figured I'd test it just in case.
SoulCalibur V [BLUS30736] - Runs correctly, though in this case there is only a video FMV and like SoulCalibur IV, no demo fights in the intro. No crashing after 2 hours of testing.
Mobile Suit Gundam Extreme Vs. Full Boost [NPJB00512] - Runs correctly, though lots of stuttering upon first load of content.

**Comment by Fukuzatsu** [comment]
Another update on this one, not sure which build specifically resolved the issue but after running the cab for a full 48 hours after a recent update (0.0.23-14088, to be specific) it appears this issue has been fixed. The matter of Tekken 5 DR in #12498 still remains, however.

**Comment by Jonok1990** [comment]
Hello my friend that is not tech heavy got the same problem we setted up everything like updated PS3 firmware, updating the game to 1.01, installed Characters DLC and than done the first boot

Specs:
RPCS 3 0.0.38-18258
Windows 11
Nvidia 2060
16 GB Ram
Intel CPU (not sure which model but can run Street Fighter 6 Steam just fine so is not a weak one)
