### ISSUE TITLE
RPCS3-SSE4 and RPCS3-AVX2

### ISSUE THREAD

**Issue by visious25** [RPCS3/rpcs3#12495]
### Quick summary

Hi, it would be good idea to split the package to RPCS3-SSE4 and RPCS3-AVX2.

**Comment by YuriNator557** [comment]
Gives literally no explanation why you think it is a good idea
A lot of modern CPUs support AVX2 instructions anyway, it's been supported since at least Haswell and any CPU older than Haswell is probably not good enough to run a lot of PS3 games anyway via RPCS3

**Comment by YuriNator557** [comment]
SSE4 only can also be used in RPCS3 already anyway by changing the LLVM CPU in the config files to a very old architecture like Westmere

**Comment by elad335** [comment]
LLVM compiles the the most suitable and supported instructions for your CPU, whether it's an AVX512 instruction or SSE4 instructio etc etc

**Comment by visious25** [comment]
My laptop is a little bit old. Pcsx2 team already did that step
![CPU-X](https://user-images.githubusercontent.com/81131095/184017317-ed7fbe56-b7a1-45d6-9fc4-b47ede05b165.png)
.

**Comment by YuriNator557** [comment]
And unlike PCSX2, that PC is below minimum requirements for RPCS3

**Comment by visious25** [comment]
Thank you for your time.
