### ISSUE TITLE
[Regression] Since build #10581, builds no longer "unlock" full mode for Castlevania Harmony of Despair

### ISSUE THREAD

**Issue by llorona467** [RPCS3/rpcs3#12505]
### Quick summary

As the title says, on build #10581 (September 16th, 2021), a line of code that read a specific file to unlock the full game was edited or deleted. The last working build is the build before it, labelled #10578. 

This file is a .rap file (I'm not sure if this works since uploading .rap files here is unsupported, so I zipped it below), and this file just sits alone in devhdd0 > home > 00000001 > exdata

[UP0101-NPUB30505_00-CVHDZDLCZUNLOCKZ.zip](https://github.com/RPCS3/rpcs3/files/9316701/UP0101-NPUB30505_00-CVHDZDLCZUNLOCKZ.zip)
 
I also have an issue with shaders appearing in the newer models (the game ran perfectly in 2018 ones). I'm not sure if the logs will show anything useful in that aspect, but if so, please inform me as I would like to fix this somehow in config.

### Build with regression

v0.0.18-12757-b30ac485

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9324436/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9324447/RPCS3.log)

### Attach capture files for visual issues

Broken version
![image](https://user-images.githubusercontent.com/100949737/184395110-e1140234-be8a-4c7b-a762-dda1575e333c.png)

Working version (previous)
![image](https://user-images.githubusercontent.com/100949737/184395339-dbd213bd-c597-47aa-8b50-6a1d0333f49c.png)

### System configuration

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Core i5 4690K @ 3.50GHz	
	Haswell 22nm Technology
RAM
	16.0GB Dual-Channel DDR3 @ 666MHz (9-9-9-24)
Motherboard
	ASRock H81M-ITX (CPUSocket)	
Graphics
	SAMSUNG (1920x1080@60Hz)
	LG QHD (2560x1440@144Hz)
	8192MB ATI Radeon RX 470 Graphics (MSI)	
Storage
	465GB Samsung SSD 860 EVO 500GB (SATA (SSD))
	931GB TOSHIBA MQ01ABD100 (SATA )

**Comment by Darkhost1999** [comment]
This issue looks like a failure to read and understand the PR you claim broke your game. Ask for help on 1 of the social platforms

**Comment by Darkhost1999** [comment]
Issue can be closed. Help was provided on discord and cause found
