### ISSUE TITLE
Evdev Analog Controller Not Work Properly

### ISSUE THREAD

**Issue by lovanto** [RPCS3/rpcs3#12500]
### Quick summary

![image](https://user-images.githubusercontent.com/57402405/184126911-9b41965d-b6be-48b8-9dd4-92af14d05497.png)

Today I tried install and play rpcs3 on my Linux laptop, for performance and else is going well, but for my analog controller on evdev is going crazy that makes my in game character not moving at all. I tried to trace it and I know that my right controller are using my left controller button, maybe because when mapping it RPCS3 not recognize it. Hope u can fix it... Thanks

### Attach a log file

[Uploading RPCS3.log…]()

### Attach capture files for visual issues

![Uploading image.png…]()

### System configuration

I5-8250U
12 gb ram
geforce 930mx
ssd sata samsung
controller fantech g12

**Comment by lovanto** [comment]
I'm using version 0.0.20-13273-7895d43a_linux64 and rpcs3-v0.0.23-14045-7ff45098_linux64
Both version got the same problem

**Comment by Darkhost1999** [comment]
Your log and capture never finished uploading. If you could edit your message and reupload those things. Wait for github to fully upload those files. It'd be appreciated.

**Comment by lovanto** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9308879/RPCS3.log)

![Screenshot from 2022-08-11 18-49-00](https://user-images.githubusercontent.com/57402405/184140220-ddc4fba5-3ed7-4a88-b9ec-f7bf9615b837.png)

I'm sorry about that, here's the log and image @Darkhost1999 
ty

**Comment by Jonathan44062** [comment]
No help with your obvious pirated P5 game
This issue should be closed
