### ISSUE TITLE
de-synchronization between audio and video on hatsune miku on steamdeck

### ISSUE THREAD

**Issue by minuteworld1** [RPCS3/rpcs3#12509]
### Quick summary

the button timing is wack on deck and its 5 seconds behind the video.

### Details

stated above

### Attach a log file

can't.

**Comment by YuriNator557** [comment]
Log file is missing. Why 'can't' it be uploaded?
The Steam Deck's CPU is not exactly cut out for RPCS3, audio desyncing could just be normal due to how weak the CPU is.

**Comment by minuteworld1** [comment]
the game runs perfectly and the cpu struggles to even be used 30% on vulkan. this is an easier game too run and i'm surprised the deck runs this at fullspeed with 15% less heat than ryujinx. id be happy too share the log if i knew how. just want to make you aware. BAD desync issues

**Comment by YuriNator557** [comment]
On steamOS it should be in ~/.cache/rpcs3/

**Comment by AniLeo** [comment]
Closing as it doesn't follow guidelines. If you want to do a compatibility report, you can do so in the forums.
