### ISSUE TITLE
Last of us freeze at elevator scene

### ISSUE THREAD

**Issue by guy224444** [RPCS3/rpcs3#12507]
### Quick summary

Last of us freezes/crashes at point where joel and ellie are on elevator in the hotel and the elevator is about to fall

### Details

Game plays as it usually does up until the point where joel gives ellie a boost on the elevator and the moment where the elevator is about to fall the game fails, happened to me 3 consecutive times.  Game version is BCUS98174.

### Attach a log file

https://mega.nz/file/6MpGUDAY#hq3KT9gY91BFcxEWn2WZ6okiIqlOyowJlY0WS6XFc1Q

**Comment by YuriNator557** [comment]
PPU LLVM Java Mode Handling: false

Set this to enabled, this should fix the problem

**Comment by MSuih** [comment]
Ask for help in our discord server, not on github
