### ISSUE TITLE
Ratchet and Clank: Tools of Destruction freeze in spaceship

### ISSUE THREAD

**Issue by Max4344** [RPCS3/rpcs3#12501]
### Quick summary

Ratchet and Clank: Tools of Destruction

### Details

Welcome.
I got problem with R&C:ToD. Everything was good until mission when i must flying with airship and shoot to pirates. In middle mission game always freeze. Can someone got idea how i can fix this? In New folder.zip i have RPCS3.log. Thanks for advance.

### Attach a log file

![Settings 8](https://user-images.githubusercontent.com/64207915/184155895-3526d5e9-4d3e-4d62-932d-470ffbd28e16.png)
![Freeze Screen](https://user-images.githubusercontent.com/64207915/184155900-d13c4e44-7bd2-4a6d-b25c-7fb9067622fc.png)
![He stopping here](https://user-images.githubusercontent.com/64207915/184155907-89351e16-28ec-4a77-b4f2-b49513b2da37.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9309431/RPCS3.log)
![Settings 1](https://user-images.githubusercontent.com/64207915/184155929-7a3f9456-ccec-4fb8-ac97-2592f4987d50.png)
![Settings 2](https://user-images.githubusercontent.com/64207915/184155934-6ad00960-8777-4e1e-a815-4471e96452cc.png)
![Settings 3](https://user-images.githubusercontent.com/64207915/184155938-1be40073-c85b-4527-ad9a-23866b549200.png)
![Settings 4](https://user-images.githubusercontent.com/64207915/184155939-5981d67d-6d2a-4ef1-a374-acd767b3c777.png)
![Settings 5](https://user-images.githubusercontent.com/64207915/184155940-fa8b5e82-5ff5-476d-a5a6-cc8305d6eb56.png)
![Settings 6](https://user-images.githubusercontent.com/64207915/184155942-d32f060c-f43e-4bad-a32e-6ca178637f8d.png)
![Settings 7](https://user-images.githubusercontent.com/64207915/184155945-e6c71d1c-7c10-41fe-ab9c-3a167e9f7b7f.png)

### Attach capture files for visual issues

[New folder.zip](https://github.com/RPCS3/rpcs3/files/9309462/New.folder.zip)

### System configuration

My Computer Acer Nitro 5 R7-5800H/16GB/512 RTX3060 144Hz Win 11 Pro

**Comment by Asinin3** [comment]
Rule 2, no piracy
