### ISSUE TITLE
RPCS3 crashes upon close to make sparse files on Windows 8.1

### ISSUE THREAD

**Issue by acrinym** [RPCS3/rpcs3#12508]
### Quick summary

When I load a backed up game or when I load firmware it alerts me that RPCS3 must close to "create sparse files". 
As soon as I say "ok" it crashes with this: 

### Details

Problem signature:
  Problem Event Name:	BEX64
  Application Name:	rpcs3.exe
  Application Version:	0.0.0.0
  Application Timestamp:	62f6489c
  Fault Module Name:	rpcs3.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	62f6489c
  Exception Offset:	0000000001e13215
  Exception Code:	c0000409
  Exception Data:	0000000000000007
  OS Version:	6.3.9600.2.0.0.256.89
  Locale ID:	1033
  Additional Information 1:	0a72
  Additional Information 2:	0a724b3e6582a9d599a66f94193e5097
  Additional Information 3:	fddd
  Additional Information 4:	fdddb780b05a5392391cad1af0449e4d

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9332170/RPCS3.log)

### System configuration

[DxDiag.txt](https://github.com/RPCS3/rpcs3/files/9332171/DxDiag.txt)

### Other details

I can't get it to do much of anything if it needs to create sparse files. This is always the result.

**Comment by Nekotekina** [comment]
Try #12510

**Comment by nomakewan** [comment]
While I am not the person who opened this issue, I experienced the same issue they did with the same public build, and can confirm that #12510 fixed the issue.

**Comment by DMaster2** [comment]
> While I am not the person who opened this issue, I experienced the same issue they did with the same public build, and can confirm that #12510 fixed the issue.

And i can confirm it didn't solved anything. Every time that i update rpcs3 i get that error when it tries to close and restart.

**Comment by nomakewan** [comment]
> > While I am not the person who opened this issue, I experienced the same issue they did with the same public build, and can confirm that #12510 fixed the issue.
> 
> And i can confirm it didn't solved anything. Every time that i update rpcs3 i get that error when it tries to close and restart.

You are commenting on a closed issue from August 2022. There have been hundreds, if not over a thousand updates to the code since now.

You should open a new issue, and reference this issue in the new issue if necessary.

**Comment by AniLeo** [comment]
We don't support Windows 8.1 anymore so the original report isn't relevant.

New issues need to be reported separatedly.
