### ISSUE TITLE
Diablo III error

### ISSUE THREAD

**Issue by hendrylim** [RPCS3/rpcs3#12511]
### Quick summary

I have no idea how to fix this. Please help

### Details

Illegal instruction at 00007ff81e2addc8 (0x0f0b554889e54156534881ecd0000000).
Thread id = 123145552130048.

HOW TO REPORT ERRORS:
https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support
Please, don't send incorrect reports. Thanks for understanding.

### Attach a log file

Illegal instruction at 00007ff81e2addc8 (0x0f0b554889e54156534881ecd0000000).
Thread id = 123145552130048.

HOW TO REPORT ERRORS:
https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support
Please, don't send incorrect reports. Thanks for understanding.

**Comment by AniLeo** [comment]
>  Please, don't send incorrect reports. Thanks for understanding.

The irony...
