### ISSUE TITLE
AC1 fails to launch

### ISSUE THREAD

**Issue by barfin** [RPCS3/rpcs3#12515]
### Quick summary

ac1 game is marked as playable in the database
https://rpcs3.net/compatibility?g=BLES00158#jump
but when i tried to launch it gave me errors related to "sys_mutex_lock" and "sys_ss_access_control_engine"

### Details

I used rpcs3-bin from aur, the official appimage and flathub version and they all gave same errors (flathub version is what i used to generate logs)
memlock is also set to unlimited in limits.conf

### Attach a log file

[ac1_log.txt](https://github.com/RPCS3/rpcs3/files/9336546/ac1_log.txt)
[ac1_trace_log.txt](https://github.com/RPCS3/rpcs3/files/9336547/ac1_trace_log.txt)

### System configuration

```
- SYS: Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz | 4 Threads | 11.63 GiB RAM | TSC: 3.492GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 5.19.1-zen1-1-zen, Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 11 Aug 2022 15:22:00 +0000
- SYS: Current Time: 2022-08-15T14:38:57
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 970' running on driver 515.65.1.0
- RSX: Found vulkan-compatible GPU: 'llvmpipe (LLVM 12.0.1, 256 bits)' running on driver 0.0.1
- SYS: Firmware version: 4.89
```

**Comment by Darkhost1999** [comment]
Just to rule out this being the issue: In your USRDIR folder is there an empty ASSASSIN_ISO folder. If not. Make one.
It's a case-sensitive empty folder all Assassin's Creed games should have in order to launch the game. Without it they don't get to the menus.

**Comment by barfin** [comment]
> Just to rule out this being the issue: In your USRDIR folder is there an empty ASSASSIN_ISO folder. If not. Make one. It's a case-sensitive empty folder all Assassin's Creed games should have in order to launch the game. Without it they don't get to the menus.

weird solution but it worked

**Comment by elad335** [comment]
Dunno why this got closed either.

**Comment by YuriNator557** [comment]
Missing game file caused issue, does it matter if it's just a blank folder?

**Comment by elad335** [comment]
It's not a missing file it's an issue listed on forums as well.

**Comment by elad335** [comment]
Ah it's a problem with multiman from some digging on forums, nvm.
