### ISSUE TITLE
Grav stream animation glitch in Ratchet & Clank: Into the Nexus

### ISSUE THREAD

**Issue by EvilPlayer1** [RPCS3/rpcs3#12518]
### Quick summary

When you jump in grav streams, there is graphical glitch, which looks familiar to glitches in "crack in time", which were described in #11205

### Details

RPCS3:
![BCES01908_screenshot_2022_08_16_14_21_50](https://user-images.githubusercontent.com/90133207/184867970-fea0db18-3248-404c-b0c5-594351c7f28d.png)
PS3:
![Screenshot 2022-08-16 14-18-48](https://user-images.githubusercontent.com/90133207/184868046-b9074b61-e46e-4e93-9478-ed4da33164e3.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9350441/RPCS3.log)

### Attach capture files for visual issues

https://drive.google.com/file/d/1khlkhH7u7kd1VHmb61MgoPi8hpwfoPkS/view?usp=sharing

### System configuration

OS - Windows 11
CPU - i7-11700
GPU - GTX 1660 SUPER
Driver version - 516.94

**Comment by JimScript** [comment]
I've been jumping in and out of the Grav-streams and I haven't noticed anything unusual about them. Before the update, they would sometimes produce white squares around ratchet, but they seem to be fixed now(also it feels like it runs better too).

**Comment by EvilPlayer1** [comment]
I still see these issues. Nether blades have this issue too. I noticed only disappearence of black squares around them after update.
![BCES01908_screenshot_2022_08_20_02_37_19](https://user-images.githubusercontent.com/90133207/185720386-a07d7d84-72d2-4f54-90ee-69abdddaff1e.png)
![BCES01908_screenshot_2022_08_20_02_38_34](https://user-images.githubusercontent.com/90133207/185720391-05b2d030-bc8c-4de8-8245-d266ba9179a6.png)

**Comment by JimScript** [comment]
Oh, I see now, it is the blooming rectangles rather than solid white. I'm sorry I can't replicate it, Maybe you need to clear your shader cache(if you haven't already):
![NPUA80908_screenshot_2022_08_19_19_30_58](https://user-images.githubusercontent.com/66685584/185725831-b3d116de-f3a0-4253-a645-953530e951e3.png)
![NPUA80908_screenshot_2022_08_19_19_33_21](https://user-images.githubusercontent.com/66685584/185725866-1cda0c35-ab09-4ab9-932d-dfff68b60ab5.png)

**Comment by EvilPlayer1** [comment]
Nothing helped(
![BCES01908_screenshot_2022_08_20_11_29_49](https://user-images.githubusercontent.com/90133207/185736525-619d8b40-1a6e-4aba-a3f6-1cdfdb157686.png)

**Comment by JimScript** [comment]
I am sorry, I just can't seem to break it like yours:
![NPUA80908_screenshot_2022_08_20_14_07_06](https://user-images.githubusercontent.com/66685584/185766127-51cd4b1e-540d-4972-9608-13995cc6cf4f.png)

I've noticed however that when many of these effects on screen, that the GPU usage will jump considerably. It's not a problem with my RTX 2070 Super, but it might cause issues with your GTX 1660 Super. Maybe the fix doesn't work so well on lower spec GPUs?

**Comment by Jonathan44062** [comment]
Maybe Read Color Buffers in Advanced tab should help, try if you didn't.

**Comment by EvilPlayer1** [comment]
> Maybe Read Color Buffers in Advanced tab should help, try if you didn't.

It works! No issues anymore. Thank you
