### ISSUE TITLE
NCAA Football14 Freezes immediately

### ISSUE THREAD

**Issue by ChrisRosa89** [RPCS3/rpcs3#12517]
### Quick summary

I hit "Boot" and the College Football Revamped page loads, but freezes immediately after it is done. It shows the graphic of EA sports but freezes before it moves.

### Details

I have tried pressing all buttons and got these error messages.

E Cubeb: Device with id={0.0.0.00000000}.{733fabeb-853c-40b7-ac13-5b3a4ca1a1db} not found
E cellAudio: Failed to open audio backend. Make sure that no other application is running that might block audio access (e.g. Netflix).
S PPU: LLVM: Loaded module v5-kusa-EdCH7Q57Fuzcspi7ocr35g-00001G-skylake.obj
S PPU: LLVM: Loaded module v5-kusa-kArjaxn37te140ZoiY8EFq-00001G-skylake.obj
S PPU: LLVM: Loaded module v5-kusa-sMnFN1f6zVuQeQxJeR8atQ-00001G-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libhttp.sprx” (id=0x23010900)
S PPU: LLVM: Loaded module v5-kusa-qAE5LW7t8xT9tNggSrSJhv-00001G-skylake.obj
S PPU: LLVM: Loaded module v5-kusa-1v8Qb7coSU1k54TtmJzrt4-00001G-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libpngdec.sprx” (id=0x23010c00)
U PPU TODO: Unimplemented syscall sys_ss_media_id -> CELL_OK (r3=0x10001, r4=0x1c71830, r5=0x1cd0000, r6=0x1, r7=0x1cd3b5b, r8=0x4e, r9=0x0, r10=0x1cd3c38)
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR//qkl_cache.ast” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR//qkl_cache.ast” [2]
E SYS: 'sceNpDrmIsAvailable' failed with 0x80010006 : CELL_ENOENT, /dev_hdd0/game/BLUS31159/ICON0.PNG.edat [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///indexedassets.txt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/indexedassets.txt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/ps3/indexedassets.txt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/ps3/speech/indexedassets.txt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/ps3/speech/pa/indexedassets.txt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/ps3/speech/pchat/indexedassets.txt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/ps3/speech/tv/indexedassets.txt” [1]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/Replays” [1]
E Cubeb: Device with id={0.0.0.00000000}.{733fabeb-853c-40b7-ac13-5b3a4ca1a1db} not found
E cellAudio: Failed to open audio backend. Make sure that no other application is running that might block audio access (e.g. Netflix).

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9339517/RPCS3.log.gz)

### System configuration

Windows 11
CPU: i9 10900k
GPU: NVIDIA GeForce RTX 3080
GPU Driver Version: 30.0.15.1179

**Comment by YuriNator557** [comment]
Modded game, invalid issue
