### ISSUE TITLE
The Ratchet & Clank Trilogy Oxygen/Suction bar does not disappear

### ISSUE THREAD

**Issue by JeroenMathon** [RPCS3/rpcs3#12525]
### Quick summary

In the game whenever you go under water or use the suction weapon the bar moves to the right of the screen but not completely disappear.

### Details

Very minor quality of life bug not game breaking but i thought i'd mention it.
In the game whenever you go under water or use the suction weapon the bar moves to the right of the screen but not completely disappears.. I made a screenshot that shows the bug in action.

It definite does not have high priority, but it would be visually appealing to have it fixed.

I am a hobbyist programmer so it definitely isn't my expertise but i guess the game moves the bar outside of the screen as and it does not unload the sprite correctly, since it isn't there if it isn't called.

It fixes itself on a level reload. could there be something going wrong on the deloading of that sprite/object?

It certainly is an interesting bug and i'd love to know what causes it out of curiosity.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9373692/RPCS3.log.gz)

### Attach capture files for visual issues

![Screenshot_20220818_140428](https://user-images.githubusercontent.com/49328943/185391559-dc214fdb-7f75-4749-b110-16e4a8182145.png)

### System configuration

 jeroen@EliteV2
 OS: openSUSE 20220814
 Kernel: x86_64 Linux 5.19.1-1-default
 Uptime: 1d 5h 34m
 Packages: 3927
 Shell: bash 5.1.16
 Resolution: 4480x1440
 DE: KDE 5.96.0 / Plasma 5.25.4
 WM: KWin
 GTK Theme: Breeze [GTK2/3]
 Icon Theme: Shiny-Color-Dark-Icons
 Disk: 83T / 102T (82%)
 CPU: AMD Ryzen 7 5800X 8-Core @ 16x 3.8GHz
 GPU: AMD Radeon RX 6700 XT (navy_flounder, LLVM 14.0.6, DRM 3.47, 5.19.1-1-default)
 RAM: 10240MiB / 32032MiB

**Comment by MSuih** [comment]
I'm pretty sure that this is a game bug an not an emulator bug. That bar is shown because PS3 remasters added widescreen support but the developers forgot to move the oxygen bar further to right to account for the increased screen area. The remasters were ported very sloppily and this is not the only bug in them.

If you can get footage from PS3 which shows this working correctly there then the issue can be reopened.

**Comment by JeroenMathon** [comment]
> I'm pretty sure that this is a game bug an not an emulator bug. That bar is shown because PS3 remasters added widescreen support but the developers forgot to move the oxygen bar further to right to account for the increased screen area. The remasters were ported very sloppily and this is not the only bug in them.
> 
> If you can get footage from PS3 which shows this working correctly there then the issue can be reopened.

You are right, its a game bug, thanks for the quick response, i hope this issue will prevent others from being made
