### ISSUE TITLE
Trophy sound

### ISSUE THREAD

**Issue by jacksauciboie** [RPCS3/rpcs3#12536]
### Quick summary

I WANT TROPHY SOUND

### Details

trophy sound

**Comment by Darkhost1999** [comment]
So put a .wav file in RPCS3\sounds named `snd_trophy.wav` this isn't an issue with RPCS3

**Comment by jjw410** [comment]
> So put a .wav file in RPCS3\sounds named `snd_trophy.wav` this isn't an issue with RPCS3

To be fair, that is a very reasonable request and no one would know that was an option.

**Comment by Darkhost1999** [comment]
> To be fair, that is a very reasonable request and no one would know that was an option.

All anyone has to do is ask on the discord, forums, or any of RPCS3's social platforms.
This isn't a social platform. It's an issue tracker.

**Comment by jjw410** [comment]
Well technically speaking, that is a feature request. Not a very eloquent feature request but one nonetheless. I would like to see it implemented as well but if that's easy to DIY maybe we can pop something on the wiki about it.

**Comment by jjw410** [comment]
> ### Quick summary
> I WANT TROPHY SOUND
> 
> ### Details
> trophy sound

@jacksauciboie  Ask and ye shall receive. Found some samples online, adjusted the lead-in silence so the sound matches when the trophy notification comes on-screen. And there all normalised to -12dB so it shouldn't be overly loud in-game :)

[Trophy sounds download.](https://drive.google.com/drive/folders/1HqZmZaXsaNwnDw4Fn1RiCjk43Hryy-DQ?usp=sharing)

It'd be nice to get higher quality in the future (the high-quality original will be in the PS3's BIOS I would think anyway). Just follow the directions @Darkhost1999 mentioned above. I'll be sure to get this on the wiki in the next couple of days.

**Comment by Darkhost1999** [comment]
Basically what I see is we don't know if it's illegal or not to extract the sounds from the .rco file. What I see it as is the .rco file is among the firmware we are legally allowed to download and is publicly distributed by Sony. Sony is accredited for all their tradmarks and copyrights. What's wrong with using the public firmware data to produce sound?
https://github.com/RPCS3/rpcs3/pull/11085#issuecomment-955607843
Anyways, if someone wants to make a legal sound library and make a PR we aren't stopping anyone.

**Comment by jacksauciboie** [comment]
> > ### Quick summary
> > I WANT TROPHY SOUND
> > ### Details
> > trophy sound
> 
> @jacksauciboie Ask and ye shall receive. Found some samples online, adjusted the lead-in silence so the sound matches when the trophy notification comes on-screen. And there all normalised to -12dB so it shouldn't be overly loud in-game :)
> 
> [Trophy sounds download.](https://drive.google.com/drive/folders/1HqZmZaXsaNwnDw4Fn1RiCjk43Hryy-DQ?usp=sharing)
> 
> It'd be nice to get higher quality in the future (the high-quality original will be in the PS3's BIOS I would think anyway). Just follow the directions @Darkhost1999 mentioned above. I'll be sure to get this on the wiki in the next couple of days.

THANK YOU MAN
much appreciated :)

**Comment by jacksauciboie** [comment]
btw there is no specific audio file for platinum no?

**Comment by jjw410** [comment]
> Basically what I see is we don't know if it's illegal or not to extract the sounds from the .rco file. What I see it as is the .rco file is among the firmware we are legally allowed to download and is publicly distributed by Sony. Sony is accredited for all their tradmarks and copyrights. What's wrong with using the public firmware data to produce sound? [#11085 (comment)](https://github.com/RPCS3/rpcs3/pull/11085#issuecomment-955607843) Anyways, if someone wants to make a legal sound library and make a PR we aren't stopping anyone.

Ah, I see, thank you! I didn't know about that. Understandable.

**Comment by jjw410** [comment]
> btw there is no specific audio file for platinum no?

I don't think there ever was but it would be a nice feature to get separate sounds depending on trophy rarity.

**Comment by jacksauciboie** [comment]
i tried naming it trophy.wav and still it doesnt work help??

**Comment by jjw410** [comment]
>> i tried naming it trophy.wav and still it doesnt work help??

Mate are you serious the first thing Darkhost said was 
> So put a .wav file in RPCS3\sounds named `snd_trophy.wav` this isn't an issue with RPCS3

**Comment by jacksauciboie** [comment]
i said "still" which means i tried naming it that too

**Comment by Darkhost1999** [comment]
Ask for help on 1 of our social platforms. Preferably discord
