### ISSUE TITLE
Red Dead Redemption Lights

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12531]
Lights are visible through walls
![rdr](https://user-images.githubusercontent.com/60384196/185645418-bf41cbdf-bfc5-48a9-bb83-00a0e079ae7b.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9383045/RPCS3.log.gz)
#### Attach capture

https://mega.nz/file/b5BzVTQC#SooH_xiUtjGp8pIvQIRj3vzqAMguKB966qZAxFQo0Vw

#### System configuration

R5 3600
GTX 1660S
Windows 11 Beta

**Comment by AniLeo** [comment]
Does not follow the guidelines, ZCull changed from the default value without explanation

Needs testing with precise ZCull

**Comment by Darkhost1999** [comment]
There is an explanation why it is changed
https://wiki.rpcs3.net/index.php?title=Red_Dead_Redemption
Follows the entire template and left nothing out.
I will test zcull precise when I get home. I already suspect this to just be an accuracy issue of some kind anyways.

**Comment by Darkhost1999** [comment]
![BLUS30418_screenshot_2022_08_19_13_28_43](https://user-images.githubusercontent.com/60384196/185683964-c39b9724-564f-4b96-b13f-241c3dbfea48.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9384595/RPCS3.log.gz)
With precise scull outside the movie house camera angle effects seeing both lanterns. Should be extremely difficult to miss seeing at least 1 lantern. I'm still running more accuracy tests. I'll let you know if I find the solution.

**Comment by AniLeo** [comment]
I know that's on the wiki but it's technically incorrect, it causes issues for me on RADV at least. Either way, if you still get the issue with Precise, then it's something else.

**Comment by kd-11** [comment]
Is this a regression?

**Comment by Darkhost1999** [comment]
This specific building has had the issue since I got the game. If ever fixed IDK for certainty. Which I am testing now.

**Comment by Darkhost1999** [comment]
I tested old builds 25 results per page tested as far back as #10579 before the MSAA performance stuff that was fixed.
I know I was actively playing the game then and it shows the same results for the movie theater house now vs then.

**Comment by Darkhost1999** [comment]
I'm running out of things to test. This is strict rendering mode.
![image](https://user-images.githubusercontent.com/60384196/185790294-5f57232d-eecd-4d6d-b9b6-46f6987d8a0d.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9389063/RPCS3.log.gz)
Here's OpenGL effected
![image](https://user-images.githubusercontent.com/60384196/185790564-bc4baa67-6351-4b67-9ee8-4b8f40d1f1df.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9389076/RPCS3.log.gz)

**Comment by Tarek2013** [comment]
I don't have kind of bug with my config...
I play it on Windows 10 with AMD 5950X,32go RAM and Nvidia 3080TI with lastest drivers.
Here my config : 

CPU : 
PPU Decoder : Recompiler LLVM
SPU Decoder : Recompiler LLVM
Approximate Xfloat
SPU Block Size : Auto
No TSX
Auto preferred SPU Threads
Thread Scheduler with Operating System

GPU :
Renderer : Vulkan
Frame Limit : Auto
Anisotropic Filter : x16
Anti-Aliasing : Auto
ZCULL Accuracy : Relaxed
Resolution Scale : 300%
Resolution Scale Threshold : 16x16
Shader Mode : Async (multi threaded)
Number Of Shader compiled threads : auto
Additional Settings : Write Color Buffer ON

AUDIO : 
Audio Out : Cubeb
Audio Format : Liner PCM 2 Ch. 48khz

I/O port : 
All on Null or None

ADVANCED : 
Accurate RSX reservation access
PPU LLVM Precompilation
Silence All Logs
Force disable exclusive Fullscreen mode
Vulkan Queue Scheduler : Safe
RSX FIFO Accuracy : Atomic
Driver Wake-up Delay : 1
Vblank frequency : 60 hz

Here's 2 pics taken at 2 different angles 👍 

![IMG_9401](https://user-images.githubusercontent.com/65652256/190516307-6a0b00d5-d8e7-4b91-baaf-3549bcd00c1c.JPG)


![IMG_9402](https://user-images.githubusercontent.com/65652256/190516333-5f24c952-2c2a-4d01-9a5c-211ca8c0a6e5.JPG)

As you can see, the light behind the wall is not a visible light

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9579297/RPCS3.log.gz)

Hope it will help

**Comment by Darkhost1999** [comment]
Well the only spot I've been able to trigger the issue on is the movie house backdoor. All other houses and places look fine or I haven't found them yet.

**Comment by Darkhost1999** [comment]
<img width="1280" alt="Screenshot 2023-08-07 164101" src="https://github.com/RPCS3/rpcs3/assets/60384196/4c6d1746-053d-4842-9b5e-b45b0546f11c">

**Comment by Darkhost1999** [comment]
I can reproduce this on my PS3

**Comment by Asinin3** [comment]
Your log shows using Relaxed Zcull anyway, which could be the cause..

**Comment by Darkhost1999** [comment]
> Your log shows using Relaxed Zcull anyway, which could be the cause..

It's all in the conversation
