### ISSUE TITLE
custom resolution 768p ???

### ISSUE THREAD

**Issue by jacksauciboie** [RPCS3/rpcs3#12540]
### Quick summary

like the title is saying i have 768p TV and i want to get sharpest resolution sooo is there 768p option?

### Details

768p custom resolution

**Comment by AniLeo** [comment]
Not possible, 106% = 763p, 107% = 770p.
Just use some resolution above and enjoy the SSAA.

**Comment by jacksauciboie** [comment]
aight i like your pfp btw
