### ISSUE TITLE
[Feature request] Time played should not count when emulation is paused

### ISSUE THREAD

**Issue by BladeMight** [RPCS3/rpcs3#12543]
### Quick summary

I've noticed that when emulation is paused, `Time played` is still counting after you resume then stop, so emulator ends up counting time you actually didn't play.

### Details

There is a pause start time:
https://github.com/RPCS3/rpcs3/blob/47f3740a7029fbaa879b35c2586151de109085cb/rpcs3/Emu/System.cpp#L2105
 and the code that adds time to statistics: https://github.com/RPCS3/rpcs3/blob/fcd297ffb243d54f07d3e0797bd61768ed4c3aa7/rpcs3/rpcs3qt/gui_application.cpp#L513

as much as I understand the `UpdatePlaytime()` is being called only from `m_timer` every 10 seconds:
https://github.com/RPCS3/rpcs3/blob/fcd297ffb243d54f07d3e0797bd61768ed4c3aa7/rpcs3/rpcs3qt/gui_application.cpp#L494

So maybe add pause time subtract from current playtime to `Emulator::Resume()`?

Something like this I guess:

```cpp
const u64 time = m_pause_start_time.exchange(0);
const quint64 playtime = m_persistent_settings->GetPlaytime(serial);
const sub_time = playtime - time;
m_persistent_settings->SetPlaytime(serial, sub_time);
```

**Comment by Megamouse** [comment]
I think this is already implemented

**Comment by Megamouse** [comment]
I just tested this and it seems to work fine
