### ISSUE TITLE
Some suggestions about frames and herts

### ISSUE THREAD

**Issue by weter11** [RPCS3/rpcs3#12546]
## Please do not ask for help or report compatibility regressions here, use [RPCS3 Discord server](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/) instead.

You're using the advanced template. You're expected to know what to write in order to fill in all the required information for proper report.

If you're unsure on what to do, please return back to the issue type selection and choose different category.

I test a bit 2 games `Folklore` and `LOLLIPOP CHAINSAW` for high frame rates.
So, Folklore really cant be played at 60+ fps, because cloth physics goes nuts at 60 FPS. But it is possible to set VBlank at 59Hz and framelimit set to auto (in this game setting framelimit to `PS3 native` causes 1core 100% load, but it also limit framerate to 59fps).
In a LOLLIPOP CHAINSAW most time game is playable at any framerate, but in FMVs it's impossible to beet boss level with chainsaw at 60+fps. I tried to set VBlank at 119Hz, but it working at as low as 116Hz, which corresponds to 58fps.
As I remember 50fps on 60Hz monitors and notebook screens looks bad, maybe it better play games with liitle tearing at 58/59fps on old hardware?
Also maybe some other games have similar problems, from my library only this 2 have such weird limitations.

**Comment by Darkhost1999** [comment]
I'm sure the applicable [forums](https://forums.rpcs3.net/) pages would find this more interesting.
I fail to see an issue here. Is there an issue?

**Comment by weter11** [comment]
On a wiki page https://wiki.rpcs3.net/index.php?title=Lollipop_Chainsaw absent info that you can't beat bosses if framerate is 60 or over 60fps. But, yes it more for forums, but if this issue affect more games, they need to be added to wiki.
