### ISSUE TITLE
F {PPU[0x1000000] Thread (main_thread) [0x0001353c]} VM: Access violation reading location 0x0 (unmapped memory)Enter a title here

### ISSUE THREAD

**Issue by KeroAutishima** [RPCS3/rpcs3#12547]
### Quick summary

Trying to play gta sa and it gives me this error F {PPU[0x1000000] Thread (main_thread) [0x0001353c]} VM: Access violation reading location 0x0 (unmapped memory)

### Details

Trying to play gta sa and it gives me this error F {PPU[0x1000000] Thread (main_thread) [0x0001353c]} VM: Access violation reading location 0x0 (unmapped memory)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9390370/RPCS3.log.gz)

### System configuration

macOS Monterey V12.5 Macbook Air M1,2020 8Gb Memory 500GB storage

**Comment by YuriNator557** [comment]
ℹ Disc game installed as a PKG

why is this?
