### ISSUE TITLE
Regression: Severe performance regression from 0.0.23-14079 onwards (#12523)

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#12541]
### Quick summary

Performance in Persona 5 (and possibly other games) takes a huge hit after #12523 was merged to master.

### Details

Performance drops to 32 FPS/29 1% FPS/26 0.1% FPS with the first affected build (0.0.23-14079)
![P514079](https://user-images.githubusercontent.com/4345150/185793468-2af4ea1d-0ec5-447f-9f81-8c6101a3e260.PNG)

In the last working build (0.0.23-14068), performance was 80 FPS/66 1% FPS/58 0.1% FPS
![P514068](https://user-images.githubusercontent.com/4345150/185793518-fcdd950c-7ffb-4086-9fe3-78ecfe211cf0.PNG)

### Build with regression

v0.0.23-14079

### Attach two log files

First affected build (0.0.23-14079)
[RPCS3 14079.log.gz](https://github.com/RPCS3/rpcs3/files/9389182/RPCS3.14079.log.gz)

Last working build (0.0.23-14068)
[RPCS3 14068.log.gz](https://github.com/RPCS3/rpcs3/files/9389183/RPCS3.14068.log.gz)

### System configuration

SYS: RPCS3 v0.0.23-14079-bf63a18c Alpha | master
SYS: 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.86 GiB RAM | TSC: 2.496GHz | AVX+ | FMA3
SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2080 Ti' running on driver 516.94.0.0
SYS: Firmware version: 4.88

**Comment by sylveonsylvia** [comment]
metal gear solid 4 also suffers from this regression.

**Comment by elad335** [comment]
Try to set "SPU Reservation Busy Waiting Percentage" to 50 and 100 in game config file.

**Comment by solarmystic** [comment]
> Try to set "SPU Reservation Busy Waiting Percentage" to 50 and 100 in game config file.

When set to 50 - 46 FPS/36 1% FPS/34 0.1% FPS
![P514079-50](https://user-images.githubusercontent.com/4345150/185794573-56214f14-01f9-4e9c-bd42-f17e2a8da994.PNG)

When set to 100 - 75 FPS, still noticeably reduced compared to the previous working master
![P514079-100](https://user-images.githubusercontent.com/4345150/185794734-44eee880-225e-4250-b911-3a9903c748e0.PNG)

Previous working master (14068) for comparison - 80 FPS
![P514068](https://user-images.githubusercontent.com/4345150/185794805-64637a54-23be-4a74-a150-52d5d93125db.PNG)

**Comment by elad335** [comment]
Is it possible to set "SPU Accurate Reservations" to false in this game? if so can you post results with previous settings combinations?

**Comment by solarmystic** [comment]
> Is it possible to set "SPU Accurate Reservations" to false in this game? if so can you post results with previous settings combinations?

With Accurate SPU Reservations set to false:-

1. SPU Reservation Busy Waiting Percentage" to 50 - 47 FPS (1 FPS bump compared to true)
![P514079-50ROFF](https://user-images.githubusercontent.com/4345150/185795422-4c5dc131-9857-457d-be24-19010cc3f378.PNG)

2. SPU Reservation Busy Waiting Percentage" to 100 - 75 FPS (unchanged from true)
![P514079-100ROFF](https://user-images.githubusercontent.com/4345150/185795425-eca028f6-e501-40c0-8a06-83f3256d6865.PNG)

**Comment by elad335** [comment]
Does #12544  affect it?

**Comment by solarmystic** [comment]
> Does #12544 affect it?

Makes it even slower.

1. SPU Reservation Busy Waiting Percentage to 0 - 29 FPS (vs 32 FPS on 14079)
![P5Test0](https://user-images.githubusercontent.com/4345150/185800297-97513f2f-cd20-418f-a2c4-ffa422d7fb04.PNG)

2. SPU Reservation Busy Waiting Percentage to 50 - 39 FPS (vs 47 FPS on 14079)
![P5Test50](https://user-images.githubusercontent.com/4345150/185800301-c4f3e673-94b3-4a5c-82dc-8df7da0104bc.PNG)

3. SPU Reservation Busy Waiting Percentage to 100  - 74 FPS (vs 75 FPS on 14079)
![P5Test100](https://user-images.githubusercontent.com/4345150/185800309-db0eef62-6519-4980-8d22-be4608aee699.PNG)

**Comment by elad335** [comment]
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/9389541/rpcs3.zip)
Test with it, last pr build to avoid waiting.

**Comment by solarmystic** [comment]
> [rpcs3.zip](https://github.com/RPCS3/rpcs3/files/9389541/rpcs3.zip) Test with it, last pr build to avoid waiting.

Performance improvements were noted for 0 and 50 percent but 100 percent remain unchanged at 74 FPS.

Still can't reach the previous master's level of performance (80 FPS):-

1. SPU Reservation Busy Waiting Percentage to 0 - 68 FPS
![P5T2 0](https://user-images.githubusercontent.com/4345150/185801376-e4330fda-10c1-4cf7-b305-613b56bde61e.PNG)

2. SPU Reservation Busy Waiting Percentage to 50 - 73 FPS
![P5T2 50](https://user-images.githubusercontent.com/4345150/185801394-fde2a990-116c-4eef-a47c-2f5f49df861b.PNG)

3. SPU Reservation Busy Waiting Percentage to 100 - 74 FPS
![P5T2 100](https://user-images.githubusercontent.com/4345150/185801403-8f062e7b-97e8-41e1-940e-94ad7d85d718.PNG)

**Comment by elad335** [comment]
100 is not completely how master behaved before the pr, it does something a little different now so it's not comparing apples to apples.

**Comment by elad335** [comment]
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/9389602/rpcs3.zip)
Latest build.

**Comment by solarmystic** [comment]
> [rpcs3.zip](https://github.com/RPCS3/rpcs3/files/9389602/rpcs3.zip) Latest build.

Results are unchanged:
 
1. SPU Reservation Busy Waiting Percentage to 0 - 68 FPS (unchanged)
2. SPU Reservation Busy Waiting Percentage to 50 - 73 FPS (unchanged)
3. SPU Reservation Busy Waiting Percentage to 100 - 74 FPS (unchanged)

**Comment by elad335** [comment]
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/9389636/rpcs3.zip)

**Comment by solarmystic** [comment]
> [rpcs3.zip](https://github.com/RPCS3/rpcs3/files/9389636/rpcs3.zip)

Minor improvement for 50%, unchanged for 0% and 100%.
 
1. SPU Reservation Busy Waiting Percentage to 0 - 68 FPS (unchanged)

2. SPU Reservation Busy Waiting Percentage to 50 - 74 FPS (improvement)

3. SPU Reservation Busy Waiting Percentage to 100 - 74 FPS (unchanged)

**Comment by elad335** [comment]
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/9389683/rpcs3.zip)

**Comment by elad335** [comment]
Made 50 the default.

**Comment by solarmystic** [comment]
> [rpcs3.zip](https://github.com/RPCS3/rpcs3/files/9389683/rpcs3.zip)

Unchanged for 0%, minor improvements for 50% and 100%.
 
1. SPU Reservation Busy Waiting Percentage to 0 - 68 FPS (unchanged)

2. SPU Reservation Busy Waiting Percentage to 50 - 75 FPS (improvement)

3. SPU Reservation Busy Waiting Percentage to 100 - 75 FPS (improvement)

**Comment by solarmystic** [comment]
Fixed with #12544 for Persona 5 and MGS4.
