### ISSUE TITLE
Regression: Ratchet & Clank: Tools of Destruction [BCES00052] freezes after loading save files since 0.0.23-14079 (#12523)

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#12548]
### Quick summary

In addition to the previously documented (#12541) and fixed severe performance regressions in games like Persona 5 and MGS4 caused by #12523, Ratchet & Clank :Tools of Destruction and other Insomniac R&C games freeze after loading their respective save files before reaching actual gameplay due to the same PR.

These freezes are not fixed by #12544 and persist to the current master. 

### Details

Reproduction steps:-

1. Boot up R&C:TOD using default settings with 0.0.23-14079 or later.

2. Load up a save file. 

3. After the recap FMV playback, the game will freeze with a white screen.

![unknown](https://user-images.githubusercontent.com/4345150/185913652-82ecc042-9412-4634-9d76-12bcc4be0a90.png)

Last working build is 0.0.23-14068:- 

![unknown1](https://user-images.githubusercontent.com/4345150/185913815-da04b4ee-0224-44bd-81fa-8430c7e74a73.png)

Save file for reproduction:-

[BCES00052_SAVE_2.zip](https://github.com/RPCS3/rpcs3/files/9393996/BCES00052_SAVE_2.zip)

### Build with regression

0.0.23-14079-bf63a18c

### Attach two log files

First faulty build (0.0.23-14079)
[RPCS3 14079.log.gz](https://github.com/RPCS3/rpcs3/files/9393980/RPCS3.14079.log.gz)

Last working build (0.0.23-14068)
[RPCS3 14068.log.gz](https://github.com/RPCS3/rpcs3/files/9393982/RPCS3.14068.log.gz)

### System configuration

SYS: RPCS3 v0.0.23-14079-bf63a18c Alpha | master
SYS: 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.86 GiB RAM | TSC: 2.496GHz | AVX+ | FMA3
SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2080 Ti' running on driver 516.94.0.0
SYS: Firmware version: 4.88

**Comment by elad335** [comment]
Fixed now.
