### ISSUE TITLE
[ogl] ratchet and clank full frontal assault glitches

### ISSUE THREAD

**Issue by A-w-x** [RPCS3/rpcs3#12561]
### Quick summary

after ogl bringup the game is now playable with ogl but:

main menu is not visible

![Screenshot_2022-08-25_15-21-33](https://user-images.githubusercontent.com/80461138/186706593-41b99e66-1d7b-4fb3-88b1-2f008e467122.png)

few things not renderring correctly
![Screenshot_2022-08-25_15-24-42](https://user-images.githubusercontent.com/80461138/186706789-e7a70d7b-d91f-4a68-82c3-2483c4784b5b.png)

there are glitches in game

https://user-images.githubusercontent.com/80461138/186707786-82a04028-fce9-402f-a741-ddad5c570a6c.mp4

### Attach a log file

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/9426209/RPCS3.log.zip)

### System configuration

archlinux
mesa git
i7-1165g7 (xe)
rpcs3 git

**Comment by YuriNator557** [comment]
Missing RSX/Renderdoc captures

**Comment by A-w-x** [comment]
[captures.7z.001.zip](https://github.com/RPCS3/rpcs3/files/9427097/captures.7z.001.zip)
[captures.7z.002.zip](https://github.com/RPCS3/rpcs3/files/9427102/captures.7z.002.zip)

remove .zip ext, stupid github

**Comment by kd-11** [comment]
Retest, a few large ogl PRs landed in the past month.

**Comment by A-w-x** [comment]
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/9654512/RPCS3.log.zip)

well, the game is no longer booting on master

**Comment by A-w-x** [comment]
retested now that is booting again
master as of now, mesa git

main menu is now visible
green flashes are gone


ratchet shadow from time to time becames a black rectangle for 1 second while moving


this is still not fixed
![](https://user-images.githubusercontent.com/80461138/186706789-e7a70d7b-d91f-4a68-82c3-2483c4784b5b.png)

**Comment by kd-11** [comment]
Flashing shadow happens with games in the series sometimes. It should be fixable using either read color or read depth in advanced settings, I cannot remember which.

**Comment by JimScript** [comment]
I have this weird flickering buffer on the left side of the screen on Steam Deck:
![NPUA80642_screenshot_2022_10_01_13_27_10](https://user-images.githubusercontent.com/66685584/193429245-2670f135-da46-4b66-822c-3965eb04c183.png)

**Comment by kd-11** [comment]
Hmm, I cannot tell from a still. Maybe a short screen recording will show it better.
That said, gamescope has known problems with rpcs3 that are to be fixed from their side, so that could be the issue if you're not running from desktop mode.

**Comment by JimScript** [comment]
Right, here is it in motion:

https://user-images.githubusercontent.com/66685584/193473830-42e7f4e9-fad5-46bf-9a72-872aa7e401c8.mp4

**Comment by kd-11** [comment]
Flashing should be fixed by https://github.com/RPCS3/rpcs3/pull/12856
