### ISSUE TITLE
Rock Band 3 freezes when loading Sydney venue

### ISSUE THREAD

**Issue by Readek** [RPCS3/rpcs3#12564]
### Quick summary

Rock Band 3 will consistently hang the emulator whenever trying to load the venue `Sydney, Australia`, which gets loaded on the last section of the last road challenge, and gets picked randomly when playing quickplay. Emulator displays `VM: Access violation reading location 0x8`.

### Details

Though the rest of the game is playable, this specific venue will crash whenever it gets loaded (usually on the difficulty select screen before a song). This crash happens 100% of the time, and while it makes it so you can't complete the last road challenge, it also makes playing quickplay scary because of the random chance this venue gets randomly selected.

The only way to consistently replicate this issue is to have a save just before this final challenge, or using RB3 Deluxe's venue select (this crash happens on vanilla either way). Most importantly, this crash happens both on Linux (where I primarily game) and on Windows, **but** most users I spoke to don't have this crash and able to load the venue with no problems. In fact, I tried to do the same on the Steam Deck and the crash doesn't happen there, so this suggest there may be a hardware or specific software issue. The same settings were tried between my desktop and my Steam Deck.

The full line that gets displayed once on the emulator's log is:

```F {PPU[0x1000000] Thread (main_thread) [0x0093faac]} VM: Access violation reading location 0x8 (unmapped memory)```

As an unrelated note, the game will have trashy/glitchy character textures when I play it on Linux (including with the setting "Write Color Buffers" activated), but not on Windows, and everything looks fine on my Steam Deck. I am unsure if this issue could be related somehow.

### Attach a log file

[logs.zip](https://github.com/RPCS3/rpcs3/files/9434257/logs.zip)

### System configuration

CPU: Rzyzen 5 3600
GPU: Radeon RX 5600XT (Mesa 22.1.6)
OS: Arch Linux / Windows 10

**Comment by YuriNator557** [comment]
Base resolution has been changed from 1280x720 which is not supported by this game, change it back and retest

**Comment by Readek** [comment]
It seems like the resolution set to 1080p was the issue all along, thanks for pointing that out. Played 100h of RB3 with the resolution like this so I never considered this would be the issue.
