### ISSUE TITLE
Regression: Build 0.0.23-14089 crashes on startup (#12557)

### ISSUE THREAD

**Issue by Niades** [RPCS3/rpcs3#12572]
### Quick summary

When I open the application it crashes immediately with the following error:
<img width="474" alt="Screenshot 2022-08-28 at 20 55 55" src="https://user-images.githubusercontent.com/966052/187086071-fd028a2b-a4c1-46b2-b7c0-9792a3719988.png">
I have downloaded the previous build - `0.0.23-14088` - it works just fine.

### Build with regression

0.0.23-14089

### Attach two log files

My `~/Library/Caches/rpcs3` is empty:
<img width="382" alt="Screenshot 2022-08-28 at 21 09 48" src="https://user-images.githubusercontent.com/966052/187086130-2231b667-1db4-48d9-b24b-72e425464a33.png">

### System configuration

<img width="589" alt="Screenshot 2022-08-28 at 20 57 49" src="https://user-images.githubusercontent.com/966052/187086112-a80491e2-5e17-4f8f-b478-63356f57b52c.png">

**Comment by AniLeo** [comment]
@Nekotekina regressed from #12557 on macOS platforms, Windows and Linux are unaffected

**Comment by eks28** [comment]
I have same issue is it going to be fixed soon ?

**Comment by Nekotekina** [comment]
Oops, I'll fix it soon.
