### ISSUE TITLE
constant crashing on ACER Nitro5 

### ISSUE THREAD

**Issue by strikersix23** [RPCS3/rpcs3#12571]
### Quick summary

crashing occurs on just about every launch

error that keeps occurring

SIG: Thread terminated due to fatal error: Unhandled Win32 exception 0xC0000005.
Segfault executing location 00007ffc0533a367 at 00007ffc0533a367.
Thread id = 7812.
Instruction address: 00007ffc0533a367.
RPCS3 image base: 0000000000010000.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9440104/RPCS3.log)

### System configuration

![System Information 8_28_2022 11_56_38 AM](https://user-images.githubusercontent.com/17087430/187085655-635a9615-00b7-4e7a-808f-238123ca5a1a.png)

### Other details

this has been going on for a while and what is 

rpcs3_vm_sparse.tmp

**Comment by AniLeo** [comment]
Support requests need to be filed into the appropriate platforms, not in the issue tracker
