### ISSUE TITLE
Okami HD: The Rejuvenation brush does not work on M1 Mac 

### ISSUE THREAD

**Issue by Candygoblen123** [RPCS3/rpcs3#12589]
### Quick summary

In Okami HD, the Rejuvenation brush simply does not work, when playing on my M1 MacBook Air. 

### Details

In Okami HD, the "Rejuvenation" brush simply does not work. I really don't know how to describe it. The game doesn't crash or anything, it just doesn't notice the fact that you did it correctly. The game even plays the "your ink strokes did nothing" animation. The issue even shows up in the cutscene where Issun shows you how to use the brush technique. Additionally, it seems that other brush strokes work correctly, such as where you can paint a dot on grass to grow a flower (can't find what it's called), and "sunrise". You can see me demonstrate both of those techniques registering with the game, and the "Rejuvenation" stroke not working in the cutscene where Issun demonstrates it, and when I try it out myself [in the video uploaded here](https://youtu.be/DoIvamTrnmw). (the log file is from the run in this video btw). I do not know if the issue persists on Intel Macs. 

### Attach a log file

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/9465072/RPCS3.log.zip)

### System configuration

2020 M1 MacBook Air
macOS 12.5.1

### Other details

I am going to have a friend of mine test the game out on their PC to ensure this is a macOS specific issue or not. In addition, I would appreciate if anyone could send me a save file for immediately after the river gets filled in, so I can do further testing.

**Comment by Xcedf** [comment]
Rejuvenation brush requires Write Color Buffer if I remeber correctly, was a long time since I played it.

**Comment by Candygoblen123** [comment]
God dang it that worked. I also confirmed that the setting is required to be enabled on windows as well. I am going to update the wiki with that. Thank you very much.
