### ISSUE TITLE
macOS Monterey: Camera permission missing

### ISSUE THREAD

**Issue by kasnder** [RPCS3/rpcs3#12584]
### Quick summary

I've been playing around with setting up the PS Eye with my MacBook Air M1 camera, but get the following error message:

`This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.`

This happens when I select Configuration -> Cameras from the main menu.

My settings are:

Camera Input: PS Eye

Camera Handlet: Qt

Camera: FaceTime HD Camera

It seems that the relevant permission `NSCameraUsageDescription` must be declared.

### Attach a log file

N/A

### System configuration

MacBook Air M1 (arm64)

macOS Monterey 12.5.1

RPCS3 Version: 0.0.23-14094-591159c4 Alpha | master

**Comment by marcoluc97** [comment]
Can you please retest latest version?

**Comment by kasnder** [comment]
Seems that this is fixed now!
