### ISSUE TITLE
[BCES01893] Gran Turismo 6 - Verification failed (in file ~\Emu\RSX\Program\program_state_cache2.hpp:14[:2], in function fill_fragment_constants_buffer)

### ISSUE THREAD

**Issue by DaishinSilviaGT** [RPCS3/rpcs3#12580]
### Quick summary

RPCS3 crashes while trying to load some tracks in Free Run

### Details

F {RSX [0x12d7e30]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Program\program_state_cache2.hpp:14[:2], in function fill_fragment_constants_buffer)
This purple string appears while loading Cape Ring (all tracks listed below are affected by #7765), Grand Valley Speedway, Fuji Speedway F and GT (there is probably other routes with this problem) at Free Run. At fisrt compiling of tracks they even load, but right after get this error
![image](https://user-images.githubusercontent.com/89948611/187297488-98140ff6-3380-4692-8e6a-f78d232f0ee0.png)

When trying to close this emulator, another error appears
![image](https://user-images.githubusercontent.com/89948611/187297902-1285a98e-338f-4138-97e2-bf475b6146ae.png)

Same tracks work fine at Arcade Mode (esp. at Single Race)

### Attach a log file

[RPCS3 GT6 Cape Ring.zip](https://github.com/RPCS3/rpcs3/files/9446907/RPCS3.GT6.Cape.Ring.zip)

### System configuration

OS: Windows 10 20H2
CPU: Intel Xeon E5-2689 (Sandy Bridge)
GPU: AMD Radeon RX 470 4 GB
Video driver version: 22.8.1

**Comment by kd-11** [comment]
Set RSX FIFO mode to atomic in the advanced tab and it should resolve your issue.

**Comment by DaishinSilviaGT** [comment]
Same result
[RPCS3 fuji crash.zip](https://github.com/RPCS3/rpcs3/files/9559741/RPCS3.fuji.crash.zip)

**Comment by DaishinSilviaGT** [comment]
#12762 didn't fix an issue, and it even added another one - the menu background is broken.
Also i just found another way how to reproduce this error: you can load any track, in pre-race menu go to the "Car Settings" and exit it (Tested on Daytona, Mount Panorama, Trial Mountain and Brands Hatch). 

[RPCS3 PR crash Fuji.zip](https://github.com/RPCS3/rpcs3/files/9729272/RPCS3.PR.crash.Fuji.zip)

https://cdn.discordapp.com/attachments/319224795785068545/1027724910925185024/unknown_2022.10.07-02.29.mp4

**Comment by DaishinSilviaGT** [comment]
Still crashes. As it turns out, the last way of reproduce i mentioned is kinda inconsistent, but loading Fuji Speedway at Free Run is the best way to get that problem
[RPCS3 inconsistent way.zip](https://github.com/RPCS3/rpcs3/files/9740495/RPCS3.inconsistent.way.zip)
https://cdn.discordapp.com/attachments/319224795785068545/1028454938679976017/unknown_2022.10.09-02.49.mp4

**Comment by kd-11** [comment]
Ok, so the previous PR was correct, but the game changes shaders in the middle of rendering which is not something I even thought was possible. I'll need to handle that.

**Comment by kd-11** [comment]
Please test https://github.com/RPCS3/rpcs3/pull/12795
It seems to be a game bug where the command stream contains some broken primitive commands.

**Comment by Realmantik** [comment]
The same bug for Condemned 2
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/9758932/RPCS3.zip)

**Comment by kd-11** [comment]
@Realmantik Try with the new PR. That log is for master.

**Comment by DaishinSilviaGT** [comment]
Fixed, nice work!
[RPCS3 GT6 fuji fixed.zip](https://github.com/RPCS3/rpcs3/files/9759409/RPCS3.GT6.fuji.fixed.zip)
