### ISSUE TITLE
Coverity: dead code in RSXThread

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1258]
Introduced by @DHrpcs3  in this commit:
https://github.com/RPCS3/rpcs3/commit/1e7ded2163a320498ac948a01b50bb2a19de0e88

Here: https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/RSXThread.cpp#L427
`in_bpp` can only be 2 or 4: https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/RSXThread.cpp#L403

**Comment by raven02** [comment]
@danilaml , still an issue from latest build?

**Comment by danilaml** [comment]
@raven02 hard to tell since coverity is broken for us, but it seems that the code is still more or less the same.

**Comment by raven02** [comment]
I see. Thanks @danilaml

**Comment by AniLeo** [comment]
Coverity is now working again, could someone check?

**Comment by scribam** [comment]
What is the current status of Coverity? It seems it has not run since the Jan 22, 2017 according to this page https://scan.coverity.com/projects/3960.

**Comment by scribam** [comment]
@AniLeo Coverity has been recently removed and since Oct 14, 2015, the file mentioned in the issue changed a lot. It would be probably better to open a new issue with updated information instead of keeping this old one.

**Comment by AniLeo** [comment]
Closing
