### ISSUE TITLE
Regression: Metal Gear Solid 3 and 2 performance regression (#12557)

### ISSUE THREAD

**Issue by RurouniDonut** [RPCS3/rpcs3#12582]
### Quick summary

Hello,
I updated to the latest version 0.23-14090-80f07411 and it seems to have absolutely murdered performance in MGS3. Instead of a smooth 60 frames, the game now slows down by a large margin. Reverting to 0.0.23-14057-b66908ad3, the version I had before fixed performance.

### Details

![Before](https://user-images.githubusercontent.com/2947985/187353963-c8610dd2-03e7-4424-a582-5c210a1d06b5.PNG)
![After](https://user-images.githubusercontent.com/2947985/187353965-dbaf5a60-f16b-442c-b3ed-95453138c86e.PNG)

### Build with regression

 0.23-14090-80f07411

### Attach two log files

 0.0.23-14057-b66908ad3

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9449754/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9449755/RPCS3.log.gz)

 0.23-14090-80f07411

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9449760/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9449761/RPCS3.log.gz)

**Comment by solarmystic** [comment]
There are quite a few builds between 14090 and 14057 that could be the culprit. 

If you could narrow it down further, the devs would be able to take direct action on the precise commit that caused the performance regression. 

As it is right now, they can't do anything until you do so.

**Comment by RurouniDonut** [comment]
Just went through it again. 0.0.23-14089 is the first build where it starts to lag.
0.0.23-14088 performed just fine.
![Before 2](https://user-images.githubusercontent.com/2947985/187560029-a58ee58d-04df-4f5c-a5a6-4b52d3813441.PNG)
![After 2](https://user-images.githubusercontent.com/2947985/187560030-e321513c-2a40-496b-8057-916a80c817c9.PNG)

0.0.23-14088  Logs:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9457139/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9457140/RPCS3.log)

0.0.23-14089 Logs:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9457144/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9457145/RPCS3.log)

**Comment by RainbowCookie32** [comment]
#12557 is the offending PR then

**Comment by Nekotekina** [comment]
Any other game regressed?

**Comment by MSuih** [comment]
We've gotten several reports of mgs3 and some from mgs2, but this regression doesn't seem to affect any other games.

**Comment by AniLeo** [comment]
More reports from MGS2 at least from several users

**Comment by Jonathan44062** [comment]
This also happen to R&C Collection, performance regression and broken graphics flickering
![image](https://user-images.githubusercontent.com/78843189/187809803-fb571360-abf3-435d-a080-5625955d9124.png)
![image](https://user-images.githubusercontent.com/78843189/187810071-2e5c5f57-24ea-4ccc-be2d-02e14a09aae2.png)
![image](https://user-images.githubusercontent.com/78843189/187810432-d1fc6430-a41e-4b5a-8381-2b4f91228709.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9465991/RPCS3.log.gz)

**Comment by kd-11** [comment]
Given the severity, my guess would be the horizontal min-max returning incorrect results in some titles causing excessive data transfer over pcie. I can't verify this at the moment though.

**Comment by MasterDarkseid** [comment]
Hello, i think the regression also affect Silent Hill HD Collection, Silent Hill 2 in particular the fog is flickering. Some major Frame drops, However the CPU usage has been lowered.

**Comment by solarmystic** [comment]
> This also happen to R&C Collection, performance regression and broken graphics flickering

I can verify these findings, and the flickering is severe and seizure inducing. 

(Seizure Trigger Warning)
https://user-images.githubusercontent.com/4345150/187812624-ec2b9aad-dbe3-44ac-aff5-74544107e271.mp4

**Comment by kd-11** [comment]
Please test with https://github.com/RPCS3/rpcs3/pull/12592

**Comment by kd-11** [comment]
@Buffdaddy123 The issue is fixed in the latest release on rpcs3.net.
@RurouniDonut If the issue persists, please request to reopen.

**Comment by Buffdaddy123** [comment]
Both MGS games working perfectly again, many thx.
