### ISSUE TITLE
[Regression] Radv

### ISSUE THREAD

**Issue by Jhackler** [RPCS3/rpcs3#12595]
### Quick summary

starting at rpcs3-v0.0.23-14063-a401a192_linux64 all games segfault when loading spu cache or right after building.

### Details

rpcs3-v0.0.23-14059-6e9df9e4_linux64 is the newest build that is working on my arch system starting at rpcs3-v0.0.23-14063-a401a192_linux64 all games segfault when loading spu cache or right after building.  this results in a soft lock requiring rpcs3 to be killed in the terminal. Log is from draken guard but I confirmed across 8 games. (which is all I own) 

### Build with regression

v0.0.23-14063-a401a192

### Attach two log files

[RPCS3-working.log](https://github.com/RPCS3/rpcs3/files/9473529/RPCS3-working.log)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9473536/RPCS3.log)

### System configuration

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 3700X 8-Core Processor             
    CPU Family:  0x17
    CPU Model:  0x71
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4426 Mhz
    16 logical processors
    8 physical processors
    
Operating System Version:
    "EndeavourOS Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.19.5-zen1-1-zen
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12201003
    X Window Manager:  GNOME Shell

Video Card:
    Driver:  AMD AMD Radeon RX 6700 XT (navy_flounder, LLVM 14.0.6, DRM 3.47, 5.19.5-zen1-1-zen)
    Driver Version:  4.6 (Compatibility Profile) Mesa 22.1.7
   
  Memory:
    RAM:  32019 MB

### Other details

may be related to this https://gitlab.freedesktop.org/mesa/mesa/-/commit/0bf2033e0d24d3ac542452ba28c1175d7c85853b extension not yet being in radv

**Comment by Jhackler** [comment]
> 

Since arch tends to get the stable mesa drivers pretty fast after they are actually release I don't use mesa git, someone in discord when I found the first version this occurred thought that might be related, and I checked the current non git mesa does not have it. As far as amdvlk I will try it later the fact it is slower and now the default if its installed has kept me from adding it lol.

**Comment by kd-11** [comment]
There is a environment variable that permanently tells AMDVLK to let RADV be the default.

**Comment by AniLeo** [comment]
![image](https://user-images.githubusercontent.com/10283761/188132895-e16d6d6f-8e69-4329-8bdb-aa41a1ea04a7.png)

I don't see the cube on latest mesa-git, there's something wrong

mesa-git-22.3.0_devel.159135.802fa57274bb.d41d8cd98f00b204e9800998ecf8427e-1-x86_64.pkg.tar.zst

**Comment by z0z0z** [comment]
Just built latest mesa-git and rpcs3-git on Arch

Cleared mesa shader caches and all RPCS3 caches.

Rendering is completely broken. Red Dead Redemption menu looks like this and uses 85% of my GPU.
![2022-09-02-173745_1282x722_scrot](https://user-images.githubusercontent.com/12925873/188239254-fb6f7d66-8c00-4e3a-9ff4-75d5ca9fba80.png)

OpenGL is fine by the way, this only effects RPCS3 Vulkan/RADV

**Comment by J045D3V** [comment]
It also happens to me that from the "rpcs3-v0.0.23-14063-a401a192_linux64" version there are problems with vulkan.
the previous version "rpcs3-v0.0.23-14059-6e9df9e4_linux64" works fine.
check the commits please.

OS: Manjaro Linux x86_64
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT
Kernel: 5.19.1-3-MANJARO

client glx vendor string: Mesa Project and SGI
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.1.6
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.1.6
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.1.6

**Comment by AniLeo** [comment]
There are two different issues here

a) One stability issue on mesa stable
b) One graphical issue on mesa-git

For the first one, neither me or kd can reproduce

For the second one:

I tested with an older version of mesa and latest version of RPCS3 and it's working fine
Any stable mesa up to this moment doesn't have VK_EXT_attachment_feedback_loop_layout

The regression is not on our side, I have bisected it to be within this range:
**PASS:** mesa-git-22.3.0_devel.158313.d6b61fcf60e2.d41d8cd98f00b204e9800998ecf8427e-1-x86_64.pkg.tar.zst
**FAIL:** mesa-git-22.3.0_devel.159135.802fa57274bb.d41d8cd98f00b204e9800998ecf8427e-1-x86_64.pkg.tar.zst

As such, a ticket needs to be opened in the mesa tracker, if it's still an on-going regression

**Comment by kd-11** [comment]
Some more details to consider:
- Only mesa-git has the attachment feedback loop layout extension. If this was what was broken, windows and NVIDIA users would also be affected.
- I used mesa-git to add support for the extension. I was able to run the emulator and play some games on it without problems after.

It seems that indeed there is a regression with RADV that needs reporting and some other issue with older mesa-stable. It may report some feature flags for the extension without actually supporting the implementation, though that shouldn't happen in stable branch.

**Comment by Jhackler** [comment]
Sorry I have not gotten to testing the amdvlk stuff yet I probably should have waited to report till I actually had time to follow up I have been very busy with work

**Comment by kd-11** [comment]
This should have been fixed. There were multiple regressions with other games as well due to some MRT changes.

**Comment by Jhackler** [comment]
> This should have been fixed. There were multiple regressions with other games as well due to some MRT changes.

it has indeed been fixed
