### ISSUE TITLE
[Regression] llvm/include/llvm/CodeGen/MachineOperand.h:538: int64_t llvm::MachineOperand::getImm() const: Assertion `isImm() && "Wrong MachineOperand accessor"' failed.

### ISSUE THREAD

**Issue by Tatsh** [RPCS3/rpcs3#12613]
### Quick summary

Games used to work fine. Now no game can boot.

### Details

```
rpcs3: /var/tmp/portage/games-emulation/rpcs3-0.0.24/work/rpcs3-0.0.24/llvm/include/llvm/CodeGen/MachineOperand.h:538: int64_t llvm::MachineOperand::getImm() const: Assertion `isImm() && "Wrong MachineOperand accessor"' failed.
Aborted (core dumped)
````

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9491724/RPCS3.log)

### System configuration

```
System:
  Host: limelight Kernel: 5.19.4-gentoo-limelight arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.25.4 Distro: Gentoo Base System release 2.8
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: ROG MAXIMUS XIII APEX v: Rev 1.xx
    serial: <superuser required> UEFI: American Megatrends v: 1402
    date: 01/27/2022
CPU:
  Info: 8-core model: 11th Gen Intel Core i9-11900K bits: 64 type: MT MCP
    cache: L2: 4 MiB
  Speed (MHz): avg: 5149 min/max: 800/5100:5300 cores: 1: 5100 2: 5100
    3: 5300 4: 5295 5: 5100 6: 5100 7: 5100 8: 5100 9: 5100 10: 5100 11: 5300
    12: 5300 13: 5100 14: 5100 15: 5100 16: 5100
Graphics:
  Device-1: NVIDIA GA102 [GeForce RTX 3080 Ti] driver: nvidia v: 515.65.01
  Display: x11 server: X.Org v: 21.1.4 with: Xwayland v: 22.1.3 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1: 3840x2160~60Hz
    2: 3840x2160~60Hz
  OpenGL: renderer: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA
    515.65.01
```

### Other details

This build is built with [this ebuild](https://github.com/Tatsh/tatsh-overlay/blob/master/games-emulation/rpcs3/rpcs3-0.0.24.ebuild) and [these patches](https://github.com/Tatsh/tatsh-overlay/tree/master/games-emulation/rpcs3/files). I do not suspect the patches to be causing this issue.

If this message is normal and I can disable the assertion, I would like to know how.

**Comment by hcorion** [comment]
Please test with the latest AppImage from https://rpcs3.net/download, does the issue still occur there?

**Comment by hcorion** [comment]
Also, can you properly do a regression test to see which build/commit the regression occured on?

**Comment by Florin9doi** [comment]
I had the same issue recently on windows when I built it myself. I found that Clean and Rebuild don't remove the cmake cache,  (a partal fix : https://github.com/Florin9doi/rpcs3/commit/2450021dfa2b592e485bc790ef75dd262c4701d6) but it still hasn't worked so I deleted the repo and cloned everything again.

**Comment by Tatsh** [comment]
> Please test with the latest AppImage from https://rpcs3.net/download, does the issue still occur there?

Does not happen with the build there.

> Also, can you properly do a regression test to see which build/commit the regression occured on?

The commit causing the issue is the same as 0.0.24 alpha, so https://github.com/RPCS3/rpcs3/commit/2cd7238e7696acf856946a3b77bc54b813c70e54

> I had the same issue recently on windows when I built it myself. I found that Clean and Rebuild don't remove the cmake cache (a partal fix : [Florin9doi@2450021](https://github.com/Florin9doi/rpcs3/commit/2450021dfa2b592e485bc790ef75dd262c4701d6)), but it still hasn't worked so I deleted the repo and cloned everything again.

Not sure that's my issue as Gentoo cleans the CMake data everytime before building.

**Comment by Tatsh** [comment]
@hcorion Surely those assertions aren't enabled in the build in the AppImage? So that may be why it works?

**Comment by hcorion** [comment]
Yes, though we don't specifically disable assertions in the AppImage build, you can see our build script here:
https://github.com/RPCS3/rpcs3/blob/master/.ci/build-linux.sh
It's likely that you've got a compilation flag or something going on in your build env that's causing this.

**Comment by Tatsh** [comment]
I think in one way or another, `NDEBUG` is not defined, so `assert` is defined to abort on fail.

**Comment by hcorion** [comment]
Are you perhaps building a debug build? I don't see a `-DCMAKE_BUILD_TYPE=Debug` in your linked build script, but maybe Gentoo sets CMake to use a debug build by default? Default CMake _Release_ configuration compiles with `-DNDEBUG`.
Does Gentoo have some modifications to the default CMake build flags perhaps? Either way I don't see this as an issue on our side.

**Comment by Tatsh** [comment]
I fixed it by adding `-DLLVM_COMPILE_DEFINITIONS=NDEBUG` to `cmake`.
