### ISSUE TITLE
GPU sit and spin timeout

### ISSUE THREAD

**Issue by StelioKantos** [RPCS3/rpcs3#12612]
### Quick summary

RPCS3 is crashing so badly that it locks all processes and PC to the point where the mouse, keyboard, nor anything else works and I have to physically press and hold the power button to reboot the PC. The log mentions a "GPU sit and spin timeout" but I am new to github so not sure where or how to post my log. 

### Details

Some games seem to work okay but I haven't played any long enough to know for sure. One of the games in question is BCES00226. This is happening on several others as well though. I am running Windows 11 with a Ryzen 5600G and built in graphics in the APU. I have tried the latest graphics drivers as well as several older versions, and several different versions of RPCS3. It doesn't seem to make any difference either way. The motherboard is an ASUS ROG B550i (itx). 
**EDIT** 
Figured out how to upload log. (Apologies)
### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9490583/RPCS3.log)

**Comment by YuriNator557** [comment]
The full log file must be uploaded instead of some irrelevant section
RPCS3 should not be able to crash your entire PC like that, this sounds more like overheating or an unstable OC

**Comment by StelioKantos** [comment]
Does this work?  I'm not overclocked so, could be overheating but doesn't seem likely. Hopefully this log upload works and someone wouldn't mind helping me figure it out. Thank you. 
-
https://icedrive.net/s/FWw2BSYTG78PG8RxDi4kPA2hW9ab

**Comment by RipleyTom** [comment]
You're using your iGPU with only 0.7GB of memory allocated and RPCS3 seems to hug it to death.
Chooses your 3060 in the GPU tab and not the Radeon.

**Comment by StelioKantos** [comment]
Thanks RipleyTom. I will try to figure out how/if I can allocate more memory. I'm trying to test the limits of the iGPU. Think I may have reached them if I can't give it more. I've got the 3060 disabled in device manager so it's odd that it's even trying it. I may have left the Nvidia control panel running. I will look again and see. This is the strangest thing I've ever seen with a Windows machine. The display even loses signal before it tries to default to a windows gpu driver then reboots! I then gave to reinstall the radeon driver all over again, every time.

**Comment by kd-11** [comment]
Yea, something else is causing the lockup. The game may hang due to running out of vram, but the OS should just kill rpcs3 and the driver in the worst scenario. My guess is something about having the 3060 present but disabled is tripping the OS or firmware up pretty badly when recovering from a gpu stall.
