### ISSUE TITLE
my skate 3 don't open!

### ISSUE THREAD

**Issue by rafztryhard** [RPCS3/rpcs3#12615]
### Quick summary

E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
E SYS: 'cellGameGetParamString' failed with 0x8002cb21 : id 101 is not supported in the current check mode: content_permission::check_mode::disc_game [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/fileserver.ini” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/content/textures/globaltextures.psg” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/content/textures/globaltextures.psg” [1]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/scene” [1]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/scene” [1]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/scene” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/scene/scene_000.bin” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/scene/scene_000.bin” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/audio/music/overlays.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/audio/music/overlays.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/big/fedata.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/big/fedata.big” [1]
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/httpcache/” [1]
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/httpcache” [1]
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/httpcache/restcache.ini” [1]
E RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x50300410
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/languages/english/LANGUAGE_English_Global_skate3ng.BIN” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/languages/english/LANGUAGE_English_Global_skate3ng.BIN” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/languages/english/LANGUAGE_English_HISTOGRAM_skate3ng.BIN” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/languages/english/LANGUAGE_English_HISTOGRAM_skate3ng.BIN” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/audio/grains.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/audio/grains.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/audio/ambience.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/audio/ambience.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/audio/wheels.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/audio/audiofiles.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/big/scene.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/content/worldmisc.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/content/worldmisc.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/big/miscload.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skater.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skater.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skater90.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skater90.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skaterN90.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skaterN90.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skater_air.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skater_air.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skater_fingerflip.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skater_fingerflip.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skaterls.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skaterls.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skaterstep.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skaterstep.pat” [1]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/scene” [2]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/scene” [2]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/scene” [2]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/scene/ice_000.bin” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/scene/ice_000.bin” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/scene/ICELite.bin” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/scene/ICELite.bin” [1]
E SYS: 'sceNpTrophyGetTrophyInfo' failed with 0x80022913 : SCE_NP_TROPHY_ERROR_HIDDEN [1]
E SYS: 'sceNpTrophyGetTrophyInfo' failed with 0x80022913 : SCE_NP_TROPHY_ERROR_HIDDEN [2]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/source/images/buttons/ps3/buttons.rps3” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/source/images/buttons/ps3/buttons.rps3” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/fe/source/images/buttons/ps3/buttons.rps3” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/fonts/futuraheavy.bmpFont” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/fonts/futuraheavy.bmpFont” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/fonts/futuraheavy.rps3” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/fonts/futuraheavy.rps3” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/source/screens/bootflow/esrb.apt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/source/screens/bootflow/esrb.apt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/fe/source/screens/bootflow/esrb.apt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/source/screens/bootflow/esrb.const” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/source/screens/bootflow/esrb.const” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/fe/source/screens/bootflow/esrb.const” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/source/screens/bootflow/esrb.geo” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/source/screens/bootflow/esrb.geo” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/fe/source/screens/bootflow/esrb.geo” [1]
F {PPU[0x1000004] Thread (themain_thread) [0x00b54c48]} VM: Access violation reading location 0x4 (unmapped memory)

### Details

🆘 !!!!!!!!!!!!! The game open and just give me a black screen with all these errors! I'm trying to solve this more than 5 months, and i don't find how to. !!!!!!!!!!!!!! 🆘

### Attach a log file

E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
E SYS: 'cellGameGetParamString' failed with 0x8002cb21 : id 101 is not supported in the current check mode: content_permission::check_mode::disc_game [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/fileserver.ini” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/content/textures/globaltextures.psg” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/content/textures/globaltextures.psg” [1]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/scene” [1]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/scene” [1]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/scene” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/scene/scene_000.bin” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/scene/scene_000.bin” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/audio/music/overlays.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/audio/music/overlays.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/big/fedata.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/big/fedata.big” [1]
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/httpcache/” [1]
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/httpcache” [1]
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/httpcache/restcache.ini” [1]
E RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x50300410
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/languages/english/LANGUAGE_English_Global_skate3ng.BIN” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/languages/english/LANGUAGE_English_Global_skate3ng.BIN” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/languages/english/LANGUAGE_English_HISTOGRAM_skate3ng.BIN” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/languages/english/LANGUAGE_English_HISTOGRAM_skate3ng.BIN” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/audio/grains.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/audio/grains.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/audio/ambience.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/audio/ambience.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/audio/wheels.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/audio/audiofiles.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/big/scene.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/content/worldmisc.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/content/worldmisc.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/big/miscload.big” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skater.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skater.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skater90.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skater90.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skaterN90.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skaterN90.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skater_air.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skater_air.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skater_fingerflip.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skater_fingerflip.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skaterls.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skaterls.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/joystick/skaterstep.pat” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/joystick/skaterstep.pat” [1]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/scene” [2]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/scene” [2]
E SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/scene” [2]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/scene/ice_000.bin” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/scene/ice_000.bin” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/scene/ICELite.bin” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/scene/ICELite.bin” [1]
E SYS: 'sceNpTrophyGetTrophyInfo' failed with 0x80022913 : SCE_NP_TROPHY_ERROR_HIDDEN [1]
E SYS: 'sceNpTrophyGetTrophyInfo' failed with 0x80022913 : SCE_NP_TROPHY_ERROR_HIDDEN [2]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/source/images/buttons/ps3/buttons.rps3” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/source/images/buttons/ps3/buttons.rps3” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/fe/source/images/buttons/ps3/buttons.rps3” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/fonts/futuraheavy.bmpFont” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/fonts/futuraheavy.bmpFont” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/fonts/futuraheavy.rps3” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/fonts/futuraheavy.rps3” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/source/screens/bootflow/esrb.apt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/source/screens/bootflow/esrb.apt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/fe/source/screens/bootflow/esrb.apt” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/source/screens/bootflow/esrb.const” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/source/screens/bootflow/esrb.const” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/fe/source/screens/bootflow/esrb.const” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/fe/source/screens/bootflow/esrb.geo” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/fe/source/screens/bootflow/esrb.geo” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/fe/source/screens/bootflow/esrb.geo” [1]
F {PPU[0x1000004] Thread (themain_thread) [0x00b54c48]} VM: Access violation reading location 0x4 (unmapped memory)

**Comment by RainbowCookie32** [comment]
![image](https://user-images.githubusercontent.com/16805474/188769901-9ad751b1-bf9b-437e-89a5-0cb02abfc6ce.png)
https://discord.me/rpcs3
