### ISSUE TITLE
Is possible disable performance monitor creating files ?

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#12616]
Hello.
In some previous versions when starting RPCS3 and loading games are created files in OS temp folder.
The files are named with 4 random numbers
perf-XXXX.map

The problem is when RPCS3 crash and using ramdriver tmpfs.
Here using Linux and tmpfs.
Have times is used more of 200 MB for perf-XXXX.map files and if the system is 4 GB RAM for some games need all time see if the tmpfs has several created perf-XXXX.map files and thus need remove all files to run some games.

If that feature is to collect data for reporting seems to be good, but not is all time that run an games with issues.
is possible disable the perf-XXXX.map files ? Sometimes does a lot of written in disk.

In config.yml have the details
Core:
Performance Report Threshold:
Enable Performance Report:

Please add an feature to RPCS3 no create performance monitor files if not has any option to disable that feature ...

Have an nice week.
Thanks for reply.

**Comment by Nekotekina** [comment]
I'll think what can be done about this.

**Comment by Augusto7743** [comment]
Thanks very much.
I not understand if that behavior happen in windows too.
Have some games the perf-xxxx.map file size increase for 50 MB in few minutes.
If that feature help when reporting bugs is good enable only when debugging.
