### ISSUE TITLE
[Regression] Some text in game being garbled after PR #12603

### ISSUE THREAD

**Issue by brian218** [RPCS3/rpcs3#12618]
### Quick summary

Some text in the game is garbled after PR #12603:
![2](https://user-images.githubusercontent.com/17809637/188914998-2a7e80dc-1d9a-4dde-acaa-cbec3f3f6932.png)

### Details

Before this PR got merged, it used to be:
![1](https://user-images.githubusercontent.com/17809637/188915149-6574cf03-eac1-4fc8-bde2-408bdea634c8.png)

### Build with regression

v0.0.24-14127-5985f0ee

### Attach two log files

Regression(v0.0.24-14127-5985f0ee): [regression.log](https://github.com/RPCS3/rpcs3/files/9507501/regression.log)

Normal(v0.0.24-14124-a0d48c58): [normal.log](https://github.com/RPCS3/rpcs3/files/9507526/normal.log)

### Attach capture files for visual issues

[SCEEXE000_20220907233025_capture.zip](https://github.com/RPCS3/rpcs3/files/9507575/SCEEXE000_20220907233025_capture.zip)

### System configuration

11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz | 8 Threads | 15.70 GiB RAM | TSC: 2.803GHz | AVX-512+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22000, Service Pack: none, Compatibility mode: 0
GPU: 'Intel(R) Iris(R) Xe Graphics' running on driver 0.402.713

**Comment by solarmystic** [comment]
Also affects MGS Peace Walker, according to a user on discord
https://discord.com/channels/272035812277878785/272035812277878785/1017132015218327663
(read the message and replies)

**Comment by Nekotekina** [comment]
Try #12624

**Comment by brian218** [comment]
> Try #12624

@Nekotekina The new PR does fix the regression.
