### ISSUE TITLE
NCAA 14 crashing at start screen after recent build. 

### ISSUE THREAD

**Issue by smilescart** [RPCS3/rpcs3#12627]
### Quick summary

Game worked perfectly-ish until the last 24 hours of updates. Now it crashes at the Loading screen before you enter the dashboard. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9528669/RPCS3.log)

**Comment by MSuih** [comment]
Could you figure out which version broke things? You can download older versions from https://rpcs3.net/compatibility?b, just extract the executable, rename it and drop it into your rpcs3 folder.

**Comment by smilescart** [comment]
I did this and went back to 6 days and 7 days ago’s build and the same
issue persists. So I’m not sure if going back further will fix the problem?
I know that I had 0.024-14132 a few days ago and it worked fine but now
when I go back to it is crashing at the same point.

**Comment by AniLeo** [comment]
Log file shows several bad settings being used, test is invalid, there's no known issues with the game so this is very likely user error, but besides all that the report is invalid as it doesn't list what version it regressed in plus it's using random settings without explanation as to why.

Closing as Invalid.
