### ISSUE TITLE
[Regression] Windows 11: Crash to desktop after installing firmware and LLE modules

### ISSUE THREAD

**Issue by EdHerdman** [RPCS3/rpcs3#12621]
### Quick summary

rpcs3-v0.0.24-14127-5985f0ee_win64, based on [#12603](https://github.com/RPCS3/rpcs3/pull/12603), installs firmware and LLE modules as normal, and then operates as normal including module compilation and going ingame. The newer builds rpcs3-v0.0.24-14129-274386a0_win64 https://github.com/RPCS3/rpcs3/pull/12551 and rpcs3-v0.0.24-14132-eb4131e1_win64 https://github.com/RPCS3/rpcs3/pull/12594 crash to desktop immediately after clicking through the "firmware and LLE modules installed" popup.

### Build with regression

v0.0.24-14129-274386a0

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9513423/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9513645/RPCS3.log)

**Comment by Darkhost1999** [comment]
Can confirm this is replicable
[Working-14127.log](https://github.com/RPCS3/rpcs3/files/9521983/14127.log)
[Broken-14129.log](https://github.com/RPCS3/rpcs3/files/9521981/14129.log)
Tested with clean folders

**Comment by EdHerdman** [comment]
Still happening occasionally: rpcs3-v0.0.25-14407-82a8d96f_win64
