### ISSUE TITLE
Movie intro doesn't play in Disgaea 3, 4, and the guided fate paradox

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1263]
Intro doesn't play in the aforementioned game since commit a974ee009ec6c14fd06c75d06772d4bd620ea49e and ec0005195dbf99f90cb0631e700b958bfd38f65d.
Commit 77bf86eaa5269a01cd148dcf5a5c93146fd366e7 didn't fix the issue.

**Comment by Zangetsu38** [comment]
No news for this problem ?

**Comment by danilaml** [comment]
@Nekotekina might know what caused this.

**Comment by Zangetsu38** [comment]
@danilaml Yes

**Comment by raven02** [comment]
Tried to revert ec00051 but didn't help

**Comment by SakataGintokiYT** [comment]
@raven02 
intro works in guided fate paradox you need to select modules:
- libsmvd2.sprx.elf
- libsmvd4.sprx.elf
- libdmux.sprx.elf
- libdmuxpamf.sprx.elf

**Comment by raven02** [comment]
Have you try it on build 0.0.0.9 ? seems not working

**Comment by SakataGintokiYT** [comment]
@raven02 
yes build 0.0.0.9 intro works in :
-the awakened fate ultimatum
-the guided fate paradox

 modules:
- libdmux.sprx.elf
- libdmuxpamf.sprx.elf
- libresc.sprx.elf
- librtc.sprx.elf
- libsmvd2.sprx.elf
- libsmvd4.sprx.elf
-libsre.sprx.elf

**Comment by raven02** [comment]
Thanks .Confirm it works for 'the guided fate paradox' though not Disgaea 3 .

![untitled](https://cloud.githubusercontent.com/assets/3000282/15631953/0214da2e-25b5-11e6-8228-3655432d4ea7.jpg)

**Comment by raven02** [comment]
Vulkan is broken by the way.

![untitled](https://cloud.githubusercontent.com/assets/3000282/15632010/be1feb68-25b6-11e6-88d5-a09e21a372e8.jpg)

**Comment by raven02** [comment]
@SakataGintokiYT , just wonder o you able to reach title menu in guided paradox?

**Comment by SakataGintokiYT** [comment]
@raven02 
Gra zawiesza się na wstępie:

{PPU[0x6e] Thread (fios mediathread 11) [0x0039cfc8]} PPU: Function 'cellFsRead' aborted

{PPU[0x6e] Thread (fios mediathread 11) [0x0039cfc8]} class fmt::exception thrown: Win32 error: 998.
(in file C:\rpcs3\Utilities\File.cpp:744)

**Comment by raven02** [comment]
Alright .So this game only show intro but not able to reach title screen anymore in latest builld

**Comment by SakataGintokiYT** [comment]
yes

**Comment by raven02** [comment]
Disgaea 4 intro also works with LLE modules 

![1](https://cloud.githubusercontent.com/assets/3000282/15859847/508b7492-2cf9-11e6-9fb9-d4755aba6697.jpg)
![2](https://cloud.githubusercontent.com/assets/3000282/15859856/58554be4-2cf9-11e6-80fb-dbb0084c3abc.jpg)

**Comment by raven02** [comment]
Probably this issue resolved though we need LLE to get the intro movie running

**Comment by danilaml** [comment]
@raven02 it's not resolved because the issue states clearly that intro videos worked fine without the need for LLE before some changes done in a974ee0 and ec00051.

**Comment by raven02** [comment]
Alright no problem let's keep this issue open

**Comment by zminhquanz** [comment]
![image](https://cloud.githubusercontent.com/assets/11285640/16290816/965f1b94-392a-11e6-8ba9-75edc2baa23f.png)

It's hang black screen , isn't resolve when i'm using LLE Modules to run intro movie
Test with all API : OpenGL , DX 12 , Vulkan
Disgaea 4

**Comment by zminhquanz** [comment]
and  it's crash when show intro video, with all API : OpenGL , DX 12 , Vulkan
![image](https://cloud.githubusercontent.com/assets/11285640/16291005/6f9c77de-392c-11e6-8711-34cf572f2f26.png)
this error dialog , similarly Project Diva F , when i'm going back to main menu
#1725

**Comment by raven02** [comment]
If LLE dmux works , that's mean HLE cellDmux is broken .I may be wrong.

**Comment by raven02** [comment]
It is working okay with dmux+dmuxpamf+adec+atx . This will be the new requirement to get the video playback working

**Comment by danilaml** [comment]
@raven02 I think it should be opened, but with clarification in the title that it's about LLE, since it was working with LLE long before, until it was broken.
