### ISSUE TITLE
[Regression] Broken Anti-Aliasing

### ISSUE THREAD

**Issue by Magiike** [RPCS3/rpcs3#12630]
### Quick summary

The Anti-Aliasing looks broken

### Build with regression

v0.0.24-14135-60fc90bb

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9531421/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9531422/RPCS3.log.gz)

### Attach capture files for visual issues

[NPUB31136_20220908174153_capture.zip](https://github.com/RPCS3/rpcs3/files/9531426/NPUB31136_20220908174153_capture.zip)

**Comment by Darkhost1999** [comment]
This doesn't look like a regression report. Just a bug report.

**Comment by Magiike** [comment]
![2022-09-08 (27)](https://user-images.githubusercontent.com/25310773/189250786-da47ee6b-b044-4333-bb0e-5888cdd2d714.png)

**Comment by AniLeo** [comment]
Invalid report, not only it is missing the build where it regressed as both log files are for the same build but the test itself is invalid as it's using 1080p as base resolution
