### ISSUE TITLE
Tekken 6.0 Vanilla

### ISSUE THREAD

**Issue by anxious132** [RPCS3/rpcs3#12633]
### Quick summary

since 357 emulation is here i tried my best to launch the most wanted tekken 6.0 since i own the dump on my own.
i was able to get in arcade menu system sadly i cant move anything thats the reason why its not launching.
two errors that are here
E {PPU[0x1000000] Thread (main_thread) [0x00431ee4]} SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/dev_usb000/TKBOOT.EELF” [1] 
when launching the game straight from emulator, from SELF files game is launching to the menu but for no reason i cant move anything that could be reason why its not working

![image](https://user-images.githubusercontent.com/110099202/189419440-357ae5f9-54ae-443e-ab9f-5c1c90cebab3.png)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9537929/RPCS3.log.gz)

### System configuration

i7 2600k 4,5ghz
xfx radeon rx 570 4gb
16 gb ram ddr3 1333mhz

**Comment by brian218** [comment]
Unable to reproduce the scenario.
Not sure about which IO board your game adopts. Jamma, JVS, or USIO?
RPCS3 is only compatible with USIO currently.

**Comment by anxious132** [comment]
try launching from SELF's
TEST_002.SELF <- Arcade Menu 
GAME_109.SELF <- game boot (usb key error : not found)
Tekken 6 use JVS like standard namco system 357 games
since test menu is literally bypassing Security i think we can go straight to game from Test Menu

**Comment by brian218** [comment]
Can you confirm from which System 357 model you dumped the game?
Only System 357C/359/369 use USIO, for which RPCS3 has emulation.
RPCS3 doesn't support JVS currently.
If you do have a physical JVS board, please let me know; maybe we can further work on this.

**Comment by anxious132** [comment]
its dump from 357 with update to 2.51 soft iirc, also System 357A/C/359 boot Tekken 6.0 // Bloodline Rebellion without any problem, i can share the dump since its really a holy grail and i want it to be emulated i know person who got 359/357 with JVS boards. the game actually recognize the USIO board cause the clock isnt in "freeze mode" its blinking but u really cant input anything
please add my discord so i can share more informations on that
Backyard Posse#0479

**Comment by anxious132** [comment]
got back with more news, System 357 will accept any JVS Board even sega we dont need to emulate namco JVS board i think there's a sega jvs board emulated

**Comment by brian218** [comment]
I was unable to find you on Discord.
Also, can you re-test your game with the latest RPCS3 build and let me know whether a file named "usiobackup.bin" is generated under \dev_hdd1\caches\?
The file is literally the memory

**Comment by brian218** [comment]
After looking into your log (at line 7767: ">>> USJPCB Timeout Error <<<"), I figured out that the game was unable to connect to any IO board after several attempts.
Do you have a real IO board which can work with the game? If so, could you help me check its VID&PID?
How to obtain VID&PID for a USB device: https://kb.synology.com/en-us/DSM/tutorial/How_do_I_check_the_PID_VID_of_my_USB_device

**Comment by anxious132** [comment]
Hey! ill try new update ASAP, teknoparrot use Sega JVS emulation if u could try on implementing that it would help, i asked my friend who own multiple systems to obtain VID/PID for me :) also try my discord again                   backyard posse#0479 like this idk if discord is sensitive.

**Comment by anxious132** [comment]
Usiobackup.bin is generated after launching the game.

**Comment by brian218** [comment]
> Hey! ill try new update ASAP, teknoparrot use Sega JVS emulation if u could try on implementing that it would help, i asked my friend who own multiple systems to obtain VID/PID for me :) also try my discord again backyard posse#0479 like this idk if discord is case sensitive.

Sent friend request.

**Comment by lorizzuoso** [comment]
Sorry but how exactly do you setup the 357 emulation?

**Comment by Asinin3** [comment]
Retest

**Comment by anxious132** [comment]
still the same error which is : dongle error not found. 

RPCS3 blasts it with > Error(-2147418090) which means that USB isnt propely detected by Tekken 6

**Comment by SonicdomXD** [comment]
I know this thread is pretty old, but I too am having issues with the arcade version of Tekken 6, both vanilla and bloodline rebellion. My last resort was to just delete them completely and get the console version. Could it either be that the copy I got was corrupted, or is it something else? Thanks

**Comment by lazenes** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13895349/RPCS3.log)
![image](https://github.com/RPCS3/rpcs3/assets/18098025/9b4baef9-2da5-4e4d-a4f0-566dba0afed3)
 What should I do to get out of this situation?

**Comment by lazenes** [comment]
> still the same error which is : dongle error not found.
> 
> RPCS3 blasts it with > Error(-2147418090) which means that USB isnt propely detected by Tekken 6

Project : Omed I subscribed but the discord invitation link is not working, can you help?

**Comment by jomarieann** [comment]
is this problem solved at all same mine and how do you solve this.... thanks if you help how to solve
