### ISSUE TITLE
[Regression] Demon's Souls - Sun shines through solid objects (Again?)

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#12635]
### Quick summary

From what I see, in the past, this used to happen with NVIDIA graphics cards, but I don't know if this is currently the case, we need someone with AMD GPU to see if that happen.

### Details

The build 0.0.24-14141 #12632 breaks the game
![image](https://user-images.githubusercontent.com/78843189/189504422-2e7fc047-ed8c-4ee3-8153-6fa79e1413f6.png)

Working
0.0.24-14135
![image](https://user-images.githubusercontent.com/78843189/189504568-8cda215f-f72f-472e-a012-30a043c32321.png)

### Build with regression

0.0.24-14141

### Attach two log files

Working
[Demons's Souls Working.log.gz](https://github.com/RPCS3/rpcs3/files/9541514/Demons.s.Souls.Working.log.gz)

Regression
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9541506/RPCS3.log.gz)

### Attach capture files for visual issues

RSX Capture
https://www.mediafire.com/file/2zm7ydec9poh542/BLUS30443_20220910175426_capture.rar/file

### System configuration

OS - Windows 10 21H2 Build: 19044
CPU - i7 8700
GPU - GTX NIVIDIA 1070 Ti
Driver version - 516.59

**Comment by Behodar** [comment]
> we need someone with AMD GPU to see if that happen

I'm seeing what I think is the same issue with build 14141. AMD 5700 XT on Mac OS 12.5.1.

**Comment by PootsUndead** [comment]
Can also confirm, the lens flair is back! Running on latest version 0.0.24-14141 as of this post.
Windows 10 Home 
CPU intel i7 7800
GPU GTX 1080
16 RAM
Using latest NVIDIA version 516.94

**Comment by kd-11** [comment]
Does this require standing in specific areas? Because it doesn't seem to be triggering in the spots I expected it to from previous experience with this issue.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/12645
It seems I forgot to account for a small corner case.

**Comment by Jonathan44062** [comment]
Sorry for the delay, I could not test the PR build at the right time, but I can confirm, it is fixed.
![image](https://user-images.githubusercontent.com/78843189/189721089-ac12af80-7ba5-4e04-a5b1-f44383153858.png)
![image](https://user-images.githubusercontent.com/78843189/189721129-02565bc8-a0f4-4e36-b17e-c3bf43a5e89c.png)

**Comment by Peduls** [comment]
I am seeing this issue on the latest build (v0.0.31-16236)
![BLUS30443_screenshot_2024_03_26_20_53_27](https://github.com/RPCS3/rpcs3/assets/34750422/5381cd91-ecc8-4017-b655-76e92eabf3c8)

**Comment by Peduls** [comment]
Seems I only encounter this when the Unlock FPS patch is active.

**Comment by Jonathan44062** [comment]
@Peduls I can't repro, works fine

**Comment by Peduls** [comment]
It doesn't happen every time. You need to position the camera with the sun in frame and then out of frame repeatedly until you can see the faint image of the sun visible through solid objects. As I mentioned before, this only happens with using the 60 FPS/Unlock FPS patch. Here's another image I just took and a log if it helps.
![BLUS30443_screenshot_2024_04_18_19_41_58](https://github.com/RPCS3/rpcs3/assets/34750422/fa83696a-1d24-4ebe-b4f0-71530da90dbd)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15032072/RPCS3.log.gz)

**Comment by Jonathan44062** [comment]
That's not an issue, is a reflection of sunlight

**Comment by Peduls** [comment]
No, that's not lens flare. I can provide more images if needed.

**Comment by Jonathan44062** [comment]
Anyway, this thread is closed, create a new one report

**Comment by Peduls** [comment]
I cannot open a new issue as this only occurs when using a mod/patch.
