### ISSUE TITLE
Vulkan API Call Failed (Device lost)

### ISSUE THREAD

**Issue by ReyhanCraft11** [RPCS3/rpcs3#12636]
### Quick summary

Issue: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)

### Details

I got an issue that crashes the emulator: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST). It happens when i try to load a game.

### Attach a log file

\
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9541752/RPCS3.log)

### System configuration

Device name	Reyhan-PC
Processor	Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz   1.99 GHz
Installed RAM	4.00 GB
Device ID	FE8F4290-5C86-4A71-B5F4-F42CAF3BB77A
Product ID	00327-35065-93075-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by YuriNator557** [comment]
No driver version is reported, very likely a broken driver install
Reinstall your GPU drivers, but clear them out with DDU first

**Comment by ReyhanCraft11** [comment]
But i have my software & drivers up to date.

**Comment by YuriNator557** [comment]
It doesn't matter if they're 'up to date' if the installation is broken

**Comment by MSuih** [comment]
Ask for support on our discord server.
