### ISSUE TITLE
[Regression] Big Sky Infinity: game crashes after 1/2 minutes

### ISSUE THREAD

**Issue by Enkak** [RPCS3/rpcs3#12634]
### Quick summary

Game crashes after one/two minutes with fatal error verification failed in log

### Details

Game was working normal before the specific 0.0.21 branch version mentioned below. Starting from that one the game freezes and crashes shortly after reaching main menu. Also happens ingame if I try to start a game quickly. 
Tried with latest 0.0.26-14637 and same result/crash.

Happens both in openGL and Vulkan

### Build with regression

0.0.21-13424

### Attach two log files

Log file from working build (0.0.21-13423): https://mega.nz/file/6UNAgIZS#zV7L98K1gryGHnOtZN0iQfS-562E46Akv2GyOYmRW3g

Log file from non working build (0.0.21-13424): https://mega.nz/file/nQEUgJqK#juW7cX2lTulr2TzAnGBCgvPZVDhyqbfI-S5J7-G5VuY

Log from non working build (0.0.26-14637): https://mega.nz/file/DNVU2SBC#0isSrFwEiIixzgthzEIkWtJHeKLCRyC86xGqpNpziFc

·F 0:01:13.355304 {PPU[0x1000015] Thread (Analytics) [0x00ac0fb8]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\Cell\lv2\sys_net\sys_net_helpers.cpp:133[:2], in function sys_net_addr_to_native_addr)

**Comment by AniLeo** [comment]
Missing log file from working build, missing log file from non working build

**Comment by Enkak** [comment]
> Missing log file from working build, missing log file from non working build

Hi and thanks for the reply. Edited the post with the links for the two logs. Will post here too just in case:

Log file from working build: https://mega.nz/file/HdUTlZTS#iLjGQWwAtrMlDhYesaF-i8ZaTa9rryORLYJDuySmWdo

Log file from non working build: https://mega.nz/file/DBMRwQoD#-Dw_QsRmNQonfEo4rCvf8IVO184FtSru9gi7dulkfUE

**Comment by AniLeo** [comment]
Both log files are more than one build apart, regression report is invalid as is. Need a log from the first broken build and the last working build.

**Comment by AniLeo** [comment]
For testers

Need Information: Build where the game regressed

**Comment by Enkak** [comment]
> 

Hi and sorry for the late reply.

Build where the game regressed is: 0.0.21-13424

If you launch it with 0.0.21-13423 the crash mentioned doesn't happen.

Edited the original post with the new logs. Hopefully the new info helps better. Sharing here too just in case.

Log file from working build (0.0.21-13423): https://mega.nz/file/6UNAgIZS#zV7L98K1gryGHnOtZN0iQfS-562E46Akv2GyOYmRW3g
Log file from non working build (0.0.21-13424): https://mega.nz/file/nQEUgJqK#juW7cX2lTulr2TzAnGBCgvPZVDhyqbfI-S5J7-G5VuY

**Comment by RipleyTom** [comment]
Can you please post a log with the latest version too?

**Comment by Enkak** [comment]
> Can you please post a log with the latest version of RPCS3 too?

Sure, here it is (0.0.26-14637): https://mega.nz/file/DNVU2SBC#0isSrFwEiIixzgthzEIkWtJHeKLCRyC86xGqpNpziFc
