### ISSUE TITLE
ZCULL statistics // This shouldn't happen

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12647]
### Quick summary

·E 0:14:06.264357 {RSX [0x00cb908]} RSX: Allocating a new ZCULL statistics slot 8187 overwrites previous data.
·E 0:14:06.264475 {RSX [0x00cc070]} RSX: Allocating a new ZCULL statistics slot 8188 overwrites previous data.
·E 0:14:06.264501 {RSX [0x00cc138]} RSX: Allocating a new ZCULL statistics slot 8189 overwrites previous data.
·E 0:14:06.264947 {RSX [0x00d9c20]} RSX: Allocating a new ZCULL statistics slot 8190 overwrites previous data.
·E 0:14:06.264990 {RSX [0x00d9cfc]} RSX: Allocating a new ZCULL statistics slot 8191 overwrites previous data.
```
// This shouldn't happen
rsx_log.error("Allocating a new ZCULL statistics slot %u overwrites previous data.", m_statistics_tag_id);
```

### Details

When just casually playing any part of Shadow of Mordor I've observed some issues replicable on latest Master build after making an observation that these errors as said in the code should not happen.
I haven't tested other zcull settings other than precise to see what happens although I am certain it should not happen on any of the options. Is that right?

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9549385/RPCS3.log.gz)

Message appears about 8 times. If you need debug info lmk.

### System configuration

Ryzen 5 3600
Gtx 1660 super
windows 11 beta

### Other details

Creating this after observations made #12645

**Comment by Darkhost1999** [comment]
The Last of us

![tlou](https://user-images.githubusercontent.com/60384196/190672470-5bf6f058-646f-4d62-a1eb-e138cf005b96.png)
![image](https://user-images.githubusercontent.com/60384196/190672245-2b08d0ef-f19a-42b4-8480-036e22386443.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9585255/RPCS3.log)
I didn't even have the game on for 5 minutes

**Comment by kd-11** [comment]
If its just one message then its not too bad (we can just bump the pool size) but if it is spamming then I am concerned.

**Comment by Darkhost1999** [comment]
Ok. Then yea this isn't spamming in the last of us. And it appears to be the same slot each time.

**Comment by Darkhost1999** [comment]
Far cry 3
```
·E 0:12:00.461996 {RSX [0x0038390]} RSX: Allocating a new ZCULL statistics slot 8178 overwrites previous data.
·E 0:12:00.462027 {RSX [0x0038554]} RSX: Allocating a new ZCULL statistics slot 8179 overwrites previous data.
·E 0:12:00.462037 {RSX [0x0038718]} RSX: Allocating a new ZCULL statistics slot 8180 overwrites previous data.
·E 0:12:00.462045 {RSX [0x00388dc]} RSX: Allocating a new ZCULL statistics slot 8181 overwrites previous data.
·E 0:12:00.462053 {RSX [0x0038aa0]} RSX: Allocating a new ZCULL statistics slot 8182 overwrites previous data.
·E 0:12:00.462060 {RSX [0x0038c64]} RSX: Allocating a new ZCULL statistics slot 8183 overwrites previous data.
·E 0:12:00.462067 {RSX [0x0038e28]} RSX: Allocating a new ZCULL statistics slot 8184 overwrites previous data.
·E 0:12:00.462075 {RSX [0x0038fec]} RSX: Allocating a new ZCULL statistics slot 8185 overwrites previous data.
·E 0:12:00.462083 {RSX [0x00391b0]} RSX: Allocating a new ZCULL statistics slot 8186 overwrites previous data.
·E 0:12:00.462091 {RSX [0x0039384]} RSX: Allocating a new ZCULL statistics slot 8187 overwrites previous data.
·E 0:12:00.462102 {RSX [0x0039548]} RSX: Allocating a new ZCULL statistics slot 8188 overwrites previous data.
·E 0:12:00.462109 {RSX [0x003970c]} RSX: Allocating a new ZCULL statistics slot 8189 overwrites previous data.
·E 0:12:00.462116 {RSX [0x00398d0]} RSX: Allocating a new ZCULL statistics slot 8190 overwrites previous data.
·E 0:12:00.462123 {RSX [0x0039a94]} RSX: Allocating a new ZCULL statistics slot 8191 overwrites previous data.
```
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9669612/RPCS3.log.gz)
Spammed twice Wcb fixes graphics, Host gpu labels fixes Bush flickering, wdb fixes surface textures flickering after new update (better than no textures. Still missing a lot), atomic Fifo needed for stability. accurate rsx reservation needed for stability.
Read depth buffers I bet is needed but fatal errors and can't be used

**Comment by Darkhost1999** [comment]
Shadow of Mordor
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9998521/RPCS3.log.gz)
No results found for Allocating a new ZCULL statistics. That's good

**Comment by kd-11** [comment]
Is it still spamming in FC3?
