### ISSUE TITLE
Dragon Age Origins [BLUS30415] - DLC Error Decrypting Data

### ISSUE THREAD

**Issue by Masamune3210** [RPCS3/rpcs3#12643]
### Quick summary

Trying to install any of the DLC other than Awakening, Stone Prisioner, Warden's Keep, Embri's Many Pockets, The Lucky Stone or the Blood Dragon Armor causes the game to declare them as corrupt and the log to spew out 

![image](https://user-images.githubusercontent.com/1053504/189548566-ee91d3ca-8316-4da8-92e5-47cd13138149.png)
![image](https://user-images.githubusercontent.com/1053504/189548185-f5802ca7-e96e-4e8b-b8da-a93d3cf7b06b.png)

### Details

DLC dumped from my ps3, works fine on there so I know that the pkg files and raps are fine

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/9543541/RPCS3.zip)

### System configuration

Ryzen 7 5700X
Radeon 5700XT Red Devil
Windows 11

**Comment by Darkhost1999** [comment]
So you got the .rap files and the .pkg files. 
Did you obtain the .edat files that are also inside your exdata folder where you got the .rif files?

**Comment by Masamune3210** [comment]
I didnt see any, there are some edats in the game's dlc folder though, thought the RAP would be all that was needed to decrypt them?

**Comment by Darkhost1999** [comment]
Not every single game would store the .edat files inside the exdata folder. My understanding is you probably got to install the game and boot it at least once for those files to be there if they will be stored there at all. I've never had to acquire them before myself so I don't have the knowledge from experience. I'm just trying to inform you to check in the event they are there. I'll let someone more experienced comment.

**Comment by aerisarn** [comment]
I can confirm I've installed and played all the DLCs

**Comment by Darkhost1999** [comment]
> I can confirm I've installed and played all the DLCs

Can confirm what? 
That there are .edat files?
That there are not .edat files?
That RPCS3 has this issue?
That RPCS3 does not have this issue? 
You've installed them where and played them where?
I can assume you most likely mean that DLC is working on RPCS3 just fine for you and that you didn't encounter this decryption issue. Can you perhaps upload a log file so we can compare and contrast data and see what the potential issue is?

**Comment by Masamune3210** [comment]
Also of worth to ask, are you sure its all of the dlc? DA:O handles DLC involving Awakening by having duplicates of most of them, one for Awakening and one for Base. It's very easy to not have ALL the dlc for this game

**Comment by elad335** [comment]
Retest.

**Comment by Asinin3** [comment]
No retests, closed
