### ISSUE TITLE
Disgaea 4 : cpu spend 55% of time in SPUDatabase::analyse

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1264]
Hi,
I profiled Disgaea 4 with the pause/resume trick to see what was bottlenecking the game at 30 fps (with dx12) with ppu and spu recompiler. After 4 min of execution (so that most of recompilation work is done) and for 10 s.
60% is spent in SPURecompilerDecoder::DecodeMemory, and 55% in SPUDatabase::analyse which is executed inside. Inside analyse 20% of sample are collected in lock_shared and another 20% in unlock_shared, and 10% in find. Basically the thread is spending most of it's time waiting...
Then 15% of samples are located in ppu_recompiler_llvm::RecompilationEngine::CompileBlock.
Then 7% in wrapped syscall (llvm wrapper around syscall, so it's basically sampling syscall cost).
And 7% in another thread which seems to be using spu interpreter (WRCH/RDCH).

**Comment by raven02** [comment]
It is partially resolved by using patch.yml from @Nekotekina 

https://gist.github.com/Nekotekina/14c6cc34b5c127950f982ffab87a43ec

**Comment by ELAD3356P** [comment]
Is it still an issue?

**Comment by kd-11** [comment]
Pretty sure I fixed the analyze issue a while back using an unlocked cache on SPU recompiler function entry. A patch for disgaea was also provided by neko.
