### ISSUE TITLE
Rock Band 3 (BLUS30463) ps3 keyboard with passthrough driver produce crash on exit

### ISSUE THREAD

**Issue by benclau** [RPCS3/rpcs3#12659]
### Quick summary

wireless PS3 keyboard with dongle produce a crash on exit. Passtrough with Zadig 2.7 driver used.

### Details

PS3 keyboard seems to work fine during the game but generate a crash when i exit the game.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9566071/RPCS3.log)

### Attach capture files for visual issues

![rpcs3 RB3 crash](https://user-images.githubusercontent.com/63458054/190148545-ab9994e9-999b-4dbc-bf46-bb27e10c220b.jpg)

### System configuration

Edition	Windows 10 Pro
Version	21H2
Installed on	‎2021-‎03-‎14
OS build	19044.1889
Experience	Windows Feature Experience Pack 120.2212.4180.0

Device name	TV-PC
Processor	Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   3.60 GHz
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points

Graphics
Geforce RTX 3070Ti
Driver 516.94

**Comment by Megamouse** [comment]
Please try again.
A crash regarding libusb was fixed earlier this year.

**Comment by benclau** [comment]
You can close this issue. No more crash on exit. Thank you.
