### ISSUE TITLE
MOTORSTORM®: PACIFIC RIFT [BCES00129] freezes 

### ISSUE THREAD

**Issue by raingart** [RPCS3/rpcs3#12651]
### Quick summary

Regularly freezes completely RPCS3 when changing car.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9557343/RPCS3.log)

### Attach capture files for visual issues
![Screenshot_1](https://user-images.githubusercontent.com/13064767/189909425-b5a570f6-c517-41d8-9b32-1c66aaf2d61f.png)

The error in the screenshot appears when try to close the frozen game window

_No response_

**Comment by YuriNator557** [comment]
Bad settings including silence all logs, issues with patches enabled are not valid either
Please ask the discord server or the forums for help

**Comment by raingart** [comment]
@MSuih thanks for closing issues. Whatever God forbid, I managed to send a valid log file.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9558973/RPCS3.log)

I forgot that you have a stupid system when global logging nitroks are ignored by local game settings

**Comment by AniLeo** [comment]
Several settings that are not defaults being used without any indication to why they're absolutely needed.
A preview driver is also being used instead of the latest one.

**Comment by AniLeo** [comment]
Missing log file with only the settings that are absolutely needed for the game to work, besides the defaults. Performance shortcuts must not be used.

**Comment by raingart** [comment]
Плевать на версию драйвера GPU. Я пробовал как last так и предыдущие (2020 года) которая содержит только Vulkan 1.1 .

Я не буду тестировать "со специальными" настройками. Поскольку "fatal error" не является приемлемым поведением приложение не в зависимости от выбранных из штатно доступных настроек. 

Поскольку я трачу свое время на проверку разных build и версий драйвера GPU. И при этом должен пробиватся и доносить о проблеме. Теперь сами разберетесь и оттестируете.
