### ISSUE TITLE
The Awakened Fate: Ultimatum graphics garbled

### ISSUE THREAD

**Issue by tambry** [RPCS3/rpcs3#1266]
NOTE: The Awakened Fate: Ultimatum requires the fix in #1265 to work.

Garbled graphics on OpenGL:
![](http://puu.sh/kQTju/175a9d6443.png)

Graphics on DirectX 12 are fine:
![](http://puu.sh/kQTmx/1c6819597d.jpg)

Issue might have been created by the RSX2 merge.

**Comment by vlj** [comment]
Btw does the game start? The guided fate paradox which likely share the same engine doesn't go past intro

**Comment by tambry** [comment]
@vlj In DirectX 12 it gets to "Mission 01" and then crashes in std::chrono_clock or something according to stack trace. I didn't check with OpenGL, because it's too slow.

**Comment by Zangetsu38** [comment]
hmm Game US not works for me 
>E {PPU[0x1ca] Thread (SaveLoadUtility check gamedata load)[0x001e85f0]} Exception: Access violation reading location 0x0
(in file ..\Utilities\Thread.cpp:1122, in function _se_translator)

**Comment by Zangetsu38** [comment]
@tambry Not works for me, just Black screen after intro

**Comment by tambry** [comment]
@Zangetsu38 Did you even read the first line of the issue description?

**Comment by Zangetsu38** [comment]
@tambry ? no, I have Game in menu, but show nothing, just sound

**Comment by tambry** [comment]
@Zangetsu38 You need to have write color buffers on.

**Comment by Zangetsu38** [comment]
@tambry Nop, allways Black Screen, press X game start but nothing show

**Comment by tambry** [comment]
@Zangetsu38 Could you provide the log?

**Comment by Zangetsu38** [comment]
@tambry I have the US version, so, surely there must be a difference with the JAP.

**Comment by vlj** [comment]
A wild guess would be an issue with texture upload in GL backend. Like wrong PACK parameter.

**Comment by tambry** [comment]
@Zangetsu38 Well, can you provide the log, so I can see the difference and maybe fix the problem with difference affecting the emulation?

**Comment by Zangetsu38** [comment]
@vlj @tambry Log https://github.com/Zangetsu38/Log-Rpcs3/blob/99a27737e1d67b7629d80cc9963025935476b2b7/BD/USA/BLUS31500-%5BThe%20Awakened%20Fate%20Ultimatum%5D.log

**Comment by tambry** [comment]
@Zangetsu38 Well, I trold you to enable "Write color buffers" for it to show stuff on the screen, which you according to the log, didn't.

**Comment by Zangetsu38** [comment]
@tambry Write color buffers on or off same thinks on DX12

**Comment by tambry** [comment]
@Zangetsu38 Could ypu try changing you D3D adapter from "WARP" to your graphics card, if possible?

**Comment by Zangetsu38** [comment]
@tambry  Not works, just crash

**Comment by tambry** [comment]
@Zangetsu38 Could you post the log of the crash? And also the call stack, if possible?

**Comment by Zangetsu38** [comment]
@tambry But I said I use the US version, you the JAP version is just for that, do not look further.

**Comment by tambry** [comment]
The game no longer seems to display anything in neither OpenGL or DirectX 12.

**Comment by vlj** [comment]
Can you bisect ?

**Comment by Zangetsu38** [comment]
for me this game allaw show black screen

**Comment by tambry** [comment]
@vlj Not really. I couldn't launch **any** games without crashes for almost a month until the old configuration manager was completely removed. So that means I wouldn't be able to bisect most of the time between now and then.

Though the problem could be related to the minor bugs mentioned by @O1L [here](https://github.com/RPCS3/rpcs3/pull/1318#issuecomment-160334348).

**Comment by raven02** [comment]
I'll put this in 0.0.0.9 regression .
