### ISSUE TITLE
0.0.24-14127 Huge slowdown and wrong memory allocation crashing OS

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#12661]
### Quick summary

Hello.
Thanks for reading my topic.
I seeing here huge slowdown for some games.
CPU AMD FX-6300 4 GB RAM Geforce GT 640 driver 470.129.06
Linux Ubuntu 20.04.5 64 bits.
An old cpu, but only reporting an huge slowdown since 0.0.24-14127.
Perhaps that issue is happening in other cpus too.

Testing using 0.0.24-14124 and 0.0.24-14127 games below are having 100 % gameplay speed, but are using almost 15 % more cpu usage.

Bionic Commando Rearmed [NPUB30022]
Bomberman ULTRA [NPUB30051]
Spelunker HD [NPUB30152]
TMNT: Turtles In Time Re-Shelled [NPUB30107]

Comparing RPCS3 current version and several previous versions now current version is less gpu usage and almost 15 % less VRAM usage too. Thanks very much !

0.0.24-14124 testing the games below have good speed improvements if comparing with several previous versions and use all cpu cores.

Burnout Paradise V1.9 [NPUB30040] average above 25 FPS
MOTORSTORM PACIFIC RIFT DEMO [NPUA70022] average 14 FPS.
LittleBigPlanet [NPUA80472] run above 25 FPS. Several previous versions was less of 10 FPS.

Now 0.0.24-14127 has an huge slowdown for games below, not using all cpus cores and crashing RPCS3.

Burnout Paradise V1.9 [NPUB30040] crash at title screen "press start button" using totally RAM memory and swap file in few seconds. Not is possible start the game.

LittleBigPlanet [NPUA80472] randomly crash loading in "video scenes" using totally RAM memory and swap file in few seconds. Gameplay is less of 4 FPS and not using all cpus cores.

MOTORSTORM PACIFIC RIFT DEMO [NPUA70022] less of 4 FPS with graphics issues and not using all cpus cores.

RPCS3 in few seconds from 2,46 GB RAM usage goes to use all RAM memory and swap file at point crashing the OS too.
Seeing in task manager RPCS3 not is using all 6 cores. Few cores are being used and only 1 core is totally used (possibly PPU) and others are less 50 % used.
0.0.24-14124 use all cpu cores and not does wrong memory allocation.

0.0.24-14127 randomly is crashing in "Building SPU Cache" screen closing RPCS3.
The problem is 0.0.24-14127 12603 simd_builder ver. 2
https://github.com/RPCS3/rpcs3/pull/12603

Logs are below.
Please if need any log or rsx capture reply.
Have an nice day.

### Attach a log file

[Burnout Paradise.zip](https://github.com/RPCS3/rpcs3/files/9573135/Burnout.Paradise.zip)
[Burnout Paradise ASMJIT.zip](https://github.com/RPCS3/rpcs3/files/9573138/Burnout.Paradise.ASMJIT.zip)
[LittleBigPlanet.zip](https://github.com/RPCS3/rpcs3/files/9573143/LittleBigPlanet.zip)
[LittleBigPlanet Disable Vulkan Memory Allocator.zip](https://github.com/RPCS3/rpcs3/files/9573147/LittleBigPlanet.Disable.Vulkan.Memory.Allocator.zip)
[MOTORSTORM PACIFIC RIFT DEMO.zip](https://github.com/RPCS3/rpcs3/files/9573150/MOTORSTORM.PACIFIC.RIFT.DEMO.zip)

**Comment by Nerboruto** [comment]
put more ram 4gb are too few.. 
motorstorm  runs at 25 / 30fps on one of my pc with 8gb ddr3 xeon e3-1230v3 quad core haswell 3.3ghz gtx 745 2gb ddr3..

**Comment by AniLeo** [comment]
I think we should go for setting minimum RAM requirement at 8 GB

**Comment by elad335** [comment]
Hi, does https://github.com/RPCS3/rpcs3/pull/12443 work for you?

**Comment by Augusto7743** [comment]
@Nerboruto
Here PES2018 is the only game requiring more of 3,5 GB RAM.
Motorstorm Pacific Rift use less of 3 GB in 0.0.24-14106.
All others run using less of 3,2 GB RAM.
For Linux 4 GB RAM still is the minimum requirement.
Games requiring more than 4 GB are with high number of vulkan shaders and PPUs.

@AniLeo and elad335
Firstly thanks very much for replying me and doing improvements in RPCS3 =)

Perhaps my topic not being understood.

Between 0.0.24-14106 and 0.0.24-14148 happening anything destroying the performance, not allowing cpus cores being used totally and allocating huge memory size crashing the OS.

Here 0.0.24-14106 run correctly all games only having bugs in GOWA graphics when using LLVM and Motorstorm Pacific Rift having in some moments an temporary freeze in emulation.
After upgrading to 0.0.24-14148 happening 3 types of bugs :
- Huge slowdown for some games if comparing with previous versions.
- CPU cores not being correctly used as was in previous versions.
- Games trying allocate huge memory size above 2 times as was in previous versions.

Comparing                     0.0.24-14106   0.0.24-14148
Little Big Planet             15 FPS                    now less of 5 FPS
Motorstorm Pacific Rift  9 to 12 FPS             now less of 5 FPS

Have an considerable slowdown in GOWA not being noticed by users ?
Users having old cpus see more easily that performance slowdowns.

RPCS3 versions before 2022-06 running in an FX-6300 the game GOWA had 25~30 FPS in game title and in gameplay between 8~14 FPS.
Now in game title is less of 14 FPS and in gameplay less of 5 FPS. CPU cores are being used almost 100 %.
Please not demanding performance optimization, but only saying anything is doing slowdown in GOWA.

The huge slowdown is happening as if for some games anything breaking the performance and using all cpu cores almost at 100 % and for others games having slowdown using few cpu cores less of 50 % in each cpu core as if have anything not managing correctly tasks for cpu cores.
Little Big Planet and Motorstorm Pacific Rift not are using correctly the cpu cores.

Have games trying allocate huge memory size crashing the OS in strange moments.
Burnout Paradise does that strange behavior in game title when pressing start thus trying load the next screen being an "loading screen".
Need for Speed Hot Pursuit crash when trying start the race.
Little Big Planet randomly try allocate huge memory size in "video scenes with humans" before starting the game. In other words wrong memory allocation when doing an video playback.
Both games in 0.0.24-14106 use less of 3 GB RAM and now is as if trying allocate more than 7 GB RAM =(

Seeing the recent code changes have much work done for performance ...
Is as recent changes are breaking the performance, not using correctly cpu cores and having wrong memory allocation.
The problem is between 0.0.24-14106 and 0.0.24-14148 and not seeing any changelog details about requiring more cpu power or more system memory.

@elad335

0.0.24-14106 use code from 12443 ?
That problem of memory allocation not happen in 0.0.24-14106.

**Comment by solarmystic** [comment]
> Between 0.0.24-14106 and 0.0.24-14148 happening anything destroying the performance, not allowing cpus cores being used totally and allocating huge memory size crashing the OS.

@Augusto7743 There are around 20 builds between 14106 and 14148, and anyone of these could have caused the issue. 

![pg2](https://user-images.githubusercontent.com/4345150/190941305-76f9bbef-7bbd-4469-bcb5-3273fd2fc3b8.PNG)

![pg1](https://user-images.githubusercontent.com/4345150/190941301-15c14bfe-f70a-42d8-aaad-b029f63ca1d9.PNG)

If you want a fix to this issue, you have to narrow down the exact build/PR that caused the huge slowdown/crashes for you. The developers cannot be expected to do this precise regression testing in order to determine the exact build that caused the issue.

**Comment by Augusto7743** [comment]
Thanks for reply.

All bugs are from
0.0.24-14127
[Test] simd_builder ver. 2 #12603
https://github.com/RPCS3/rpcs3/pull/12603

If need any log or other files (rsx capture) please reply me.

**Comment by Augusto7743** [comment]
Edited the summary with more correct information.

**Comment by Augusto7743** [comment]
> I think we should go for setting minimum RAM requirement at 8 GB

0.0.24-14123 RAM usage (OS + RPCS3 LLVM)

Burnout Paradise 2,94 GB
GOWA 2,76 GB only in first stages, but after the number of shaders will be high requiring more than 6 GB RAM.
LittleBigPlanet 2,35 GB
MOTORSTORM PACIFIC RIFT DEMO 2,74 GB

For Linux 4 GB RAM still is enough, but perhaps for others OS the requirement is more than 6 GB.

**Comment by solarmystic** [comment]
Just encountered another user who gets massive slowdown in Tekken 6 that can be traced back to the same build (0.0.24-14127) #12603 

The user has an i7 3770 which was running the game perfectly at 60 fps with no slowdowns in any stages in the build right before 14127 which is 0,0,24-14124. 

https://discord.com/channels/272035812277878785/277227681836302338/1023193718741807134

The common denominator between the author of this report's rig and that user's rig is that both are on CPUs that do not have AVX2 support and above, which is quite fascinating to say the least.

**Comment by Nekotekina** [comment]
I'll look into it.

**Comment by Augusto7743** [comment]
Tested 0.0.24-14183 with some games.
Not more huge slowdown and wrong memory allocation =)
Thanks very much =)

For others games the PR 11904 (vm locking refactoring) in current build continue breaking the GOWA performance having an huge slowdown.
PR 11904 date is 2022-05-02 and being from several previous builds has anyone analyzing it ?
https://github.com/RPCS3/rpcs3/pull/11904

**Comment by Mainak009** [comment]
> Just encountered another user who gets massive slowdown in Tekken 6 that can be traced back to the very same build (0.0.24-14127) #12603 
> 
> The user has an i7 3770/GTX 1060 machine which was running the game perfectly at 60 fps with no slowdowns in any stage using the build right before 14127 which is 0,0,24-14124. 
> 
> https://discord.com/channels/272035812277878785/277227681836302338/1023193718741807134
> 
> The common denominator between the author of this report's rig and that user's rig is that both are on CPUs that do not have AVX2 support, only AVX, which is quite fascinating to say the least.
> 
> Their logfile:- 
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9638644/RPCS3.log)
> 
> The massive slowdown persists on their rig until the current master and is not fixed by #12624 
> 
> ![unknown](https://user-images.githubusercontent.com/4345150/192096892-f0217bb1-e83f-4767-a264-913c91a44e0d.png)
> 

I faced this same slowdown too when using inside batocera.linux....tekken 6 loading, menu, intro video fine around 60 fps but when characters render it drops to around 10-15 FPS.....my hardware is i5-3550 3.7ghz, Nvidia GT710 2gb, Ram 4gb×2 ddr3 1333Mhz.
