### ISSUE TITLE
Test Drive Unlimited 2 does not work

### ISSUE THREAD

**Issue by Nikttaki77777YT** [RPCS3/rpcs3#12668]
### Quick summary

I tried to run TDU2 inside of RPCS3.
It came through the atari and Eden games intros, and then hanged for like 2 seconds and crashed the ENTIRE emulator.

### Details

I am opening the emulator (version 0.0.24-14162-9d9e18f6 Alpha) and selecting the game and after the two intros (atari & Eden Games) the emulator just crashes.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9586670/RPCS3.log)

### System configuration

OS: Windows 11
CPU: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
16 GB RAM
GPU: NVIDIA GeForce GTX 1070
GPU Driver: 496.13.0.0
PS3 Firmware version: 4.88

**Comment by Nikttaki77777YT** [comment]
On version 0.0.5-7345 this error shows after the intros:
![obraz](https://user-images.githubusercontent.com/75254052/190715337-ce5dc720-5b5a-492c-9a61-f9de04156ebb.png)

**Comment by Darkhost1999** [comment]
I see a few things.
1 you're running the game from onedrive which can cause an inconsistent state for emulation.
2 the forums already state this game requires write color buffers and read color buffers for the main menu and intro to render more than a black screen.
3 this is an issue tracker. Not where we report game compatibilities. Is there a defined issue here?

**Comment by Nikttaki77777YT** [comment]
Hello
I have read & write color buffers on.


Regards,
Nik Nikovsky
------------------------------------------------
Life haver
YT Premium Subscriber
Internet Archive helper
Macintosh Repository helper
Punch-out enjoyer
Not flexing nitro
Computer Clan Supporter
JavaScript learner
Good at micro:bit
Is respected on Slowly
Isn't a Slowly partner (yet)
Tries to have a YouTube channel
2% Sugar
________________________________

**Comment by AniLeo** [comment]
Falls as a support request / game compatibility report, not a issue report on the tracker
