### ISSUE TITLE
Civilization: Revolution [BLUS30130] [BLES00238] Insane log files and random crashes.

### ISSUE THREAD

**Issue by WalkerMx** [RPCS3/rpcs3#12673]
### Quick summary

In both the US and EU releases, the log file fills with an insane amount of errors.  Multiple gigabytes worth for an hourish session.

Find attached a log from the US version, from about 5 minutes of gameplay.  Be warned, uncompressed, it's ~110mb.

Additionally, after around the year 1950, the game becomes unplayable - freezing after every turn or two, typically during an attack, though it can freeze from just about anything, even just letting it sit doing nothing for too long.

Also find attached, a save game around the time crashes pop up - attacking Moscow for a few turns typically produces at least one freeze.

### Details

The log fills up with stuff like this:

```
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Shaders/PS3/CCon_NormalMap_Spec_Env_NoTeam_Clutter.NSB” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Shaders/PS3/CCon_NormalMap_Spec_Env_NoTeam_Clutter.NSB” [2]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Shaders/PS3/CCon_NormalMap_Spec_Env_NoTeam_No_ZWrite.NSB” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Shaders/PS3/CCon_NormalMap_Spec_Env_NoTeam_No_ZWrite.NSB” [2]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Shaders/PS3/CCon_NormalMap_Spec_Env_NoTeam_Shadow.NSB” [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Shaders/PS3/CCon_NormalMap_Spec_Env_NoTeam_Shadow.NSB” [2]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Shaders/PS3/CCon_NormalMap_Spec_Env_NoTeam_Shadow_Contour.NSB” [1]
```

Gigabytes and gigabytes of whatever that is.

Additionally, if freezes with no warning during gameplay - it is never very consistent, however attacking an army of Riflemen with an army of Tanks or Artillery triggers a freeze fairly commonly, perhaps 1/4 attacks generates a freeze.

On a normal PS3, these same situations might cause a framedrop or slowdown, but no freeze.

I cannot speak to the state of the logged errors on a normal PS3.

### Attach a log file

[BLUS30130 Log.zip](https://github.com/RPCS3/rpcs3/files/9592221/BLUS30130.Log.zip)

### System configuration

RPCS3 v0.0.23-14088-698c3415 Alpha | master
AMD Ryzen 7 5700G with Radeon Graphics | 16 Threads | 15.90 GiB RAM | TSC: 3.793GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22000, Service Pack: none, Compatibility mode: 0
Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 516.94.0.0
Firmware version: 4.89

### Other details

Here is the save file, also for the US release (BLUS30130).
[Save File.zip](https://github.com/RPCS3/rpcs3/files/9592222/Save.File.zip)

**Comment by WalkerMx** [comment]
Here is an example of the insanely sized logs, full of garbage.  I've had to split it, because compressed, it takes up ~75mb.  Uncompressed, it's about 1.9gb.

Also, because GitHub won't upload '.001' '.002' '.003' etc. files, I've flipped their names.  You'll have to flip it back (so that they end like log.gz.001, log.gz.002 etc.) to open the log.

[RPCS3.log.001.gz](https://github.com/RPCS3/rpcs3/files/9599813/RPCS3.log.001.gz)
[RPCS3.log.002.gz](https://github.com/RPCS3/rpcs3/files/9599814/RPCS3.log.002.gz)
[RPCS3.log.003.gz](https://github.com/RPCS3/rpcs3/files/9599817/RPCS3.log.003.gz)
[RPCS3.log.004.gz](https://github.com/RPCS3/rpcs3/files/9599818/RPCS3.log.004.gz)
[RPCS3.log.005.gz](https://github.com/RPCS3/rpcs3/files/9599821/RPCS3.log.005.gz)
[RPCS3.log.006.gz](https://github.com/RPCS3/rpcs3/files/9599822/RPCS3.log.006.gz)
[RPCS3.log.007.gz](https://github.com/RPCS3/rpcs3/files/9599825/RPCS3.log.007.gz)

**Comment by megashub** [comment]
+1 for this issue. On a Steam Deck, I don't experience runaway manic logging, but I definitely experience random freezing, as OP describes. I've regressed RPCS3 all the way back to v1.13, and the freezing never goes away, it just gets more frequent the further back you go (as one might expect). 

Log file attached:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9737549/RPCS3.log.gz)

**Comment by Viahduc** [comment]
I am having the same issue.

**Comment by Triticum0** [comment]
Retest with this pr it might fix the issue. https://github.com/RPCS3/rpcs3/pull/13631

**Comment by hunta12** [comment]
> Retest with this pr it might fix the issue. #13631

How do I use this?

**Comment by Asinin3** [comment]
Retest on latest build of RPCS3.

**Comment by megashub** [comment]
Initial testing using the latest build from ~24 hours ago is looking good (can't easily find the specific release ID right now because I'm on Github's web GUI and it doesn't let me sort Releases IDs chronologically). I'm no longer getting crashes or freezing on a late-game save and performance is overall noticeably improved (thank you so much!). 

Only non-critical issue I'm seeing is some discoloration in some places, especially in the cutaway scenes when your civ receives tribute gifts. But this is nowhere near a show-stopper.

**Comment by JoshRittenberry** [comment]
I know this is an old thread... but i'm curious if these tweaks are still the go-to for fixing the crashes. I'm currently trying to play with BLES00238 and (when playing LAN games) I'm having random crashes - most anoyingly in the late game. The only tweaks I haven't tried yet is setting the "Set Shader Mode to Legacy (single threaded)".

**Comment by Triticum0** [comment]
@JoshRittenberry create a new issue or ask the devs to reopen it, if your still having issues

**Comment by WalkerMx** [comment]
@JoshRittenberry - Just wanted to throw in, I always disabled networking when playing - the latest updates hugely improved the games stability offline.  I couldn't find a way to get local multiplayer going at all ages ago when I opened this issue, so getting to the late game on the emulator seems to be an achievement in and of itself.  Like the other user said, probably open a new issue if you can.
