### ISSUE TITLE
[Task] Uncharted 1 does not render quite right on AMD hardware when using the OpenGL renderer

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#12675]
I have a clue what causes this, but I want a tracker so I don't forget. I initially just thought it was something wrong with the new proprietary driver, but this is not the case. Radeonsi is also affected. My NVIDIA card and Vulkan work just fine so this is probably a software issue on our side.

**Comment by mfdsrax2** [comment]
Could you give us a hint on what's going on?
