### ISSUE TITLE
Prince of Persia HD Trilogy fps Issues

### ISSUE THREAD

**Issue by Alex-Mirov** [RPCS3/rpcs3#12672]
### Quick summary

Hello

The Sands of time is the only game that can work at 60fps,
warrior within and two thrones won't get behind 30fps!

Firmware: 4.89
RPCS3 Version: 0.0.24-14163-e7fd84e0 Alpha | master
O.S: Windows 11

Is that a known issue?
Can't find any info about this!

Thanks

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9591780/RPCS3.log)

**Comment by AniLeo** [comment]
Does not follow the guidelines, this is a compatibility report
