### ISSUE TITLE
God of war ascension will load caches but never launch

### ISSUE THREAD

**Issue by Alexrp02** [RPCS3/rpcs3#12688]
### Quick summary

Well, i'm trying to play god of war ascension and i can't make it work, as i said in the title.
Here i attach the log it generated, before launching the game i cleared all caches.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9611397/RPCS3.log)

**Comment by YuriNator557** [comment]
Pirated game, invalid issue
