### ISSUE TITLE
God Of War Ascension [BCES01742]

### ISSUE THREAD

**Issue by Naniboy007** [RPCS3/rpcs3#12696]
### Quick summary

Graphical glitches kratos is not visible after falling from prision at starting of game and Frame rate is very low on MacOS 12.6 M1 imac

### Details

Improve the game graphics and FPS

### Attach a log file

God of war ascension on M1 🖥️ 

### System configuration

M1 7 core GPU, 8 core CPU

**Comment by Augusto7743** [comment]
You need in topic title add information about "graphic glitch" and an image screenshot.

**Comment by MSuih** [comment]
MacOS (MoltenVK) specific issues should be reported in https://github.com/RPCS3/rpcs3/issues/11414. Include screenshots and a log file when reporting your issue.

Low performance is normal, the game is not considered playable because it needs a high-end desktop CPU.
