### ISSUE TITLE
[Regression] GOD OF WAR HD COLLECTION (GoW ll) [BCES00791] graphical glitches

### ISSUE THREAD

**Issue by Naniboy007** [RPCS3/rpcs3#12694]
### Quick summary

GoW ll crashes due to graphical issues on M1 iMac 
![060260FA-11F0-4515-8FAF-D61BC46BA2AB](https://user-images.githubusercontent.com/113497507/191684577-dc2a2c15-db18-4441-8281-2f6cb6118360.jpeg) 
Games audio also stutters frequently.

### Details

Exactly when turning the lever blue pink graphical glitches occur and RPCS3 crashes
 Please fix the issues

### Build with regression

v0.0.24-14175-23829f6 Alpha

### Attach two log files

Previous builds I don’t know whether it worked or not

### System configuration

M1 [8 core CPU, 7 core GPU]

**Comment by YuriNator557** [comment]
Missing RSX capture or Renderdoc capture

No log file either

**Comment by Naniboy007** [comment]
> Missing RSX capture or Renderdoc capture
> 
> No log file either

Where to find

**Comment by AniLeo** [comment]
Read the guidelines.

**Comment by YuriNator557** [comment]
Log files are in the RPCS3 folder, RSX captures can be generated by pressing Alt+C and they are found in the captures folder in your RPCS3 folder

**Comment by AniLeo** [comment]
Missing build where it regressed, otherwise it's an invalid regression report

**Comment by Naniboy007** [comment]
ResolvedSent from my iPhoneOn 25-Sep-2022, at 7:28 PM, Ani ***@***.***> wrote:﻿
Missing build where it regressed, otherwise it's an invalid regression report
