### ISSUE TITLE
Castlevania: Harmony of Despair

### ISSUE THREAD

**Issue by SonGokuuSSJ** [RPCS3/rpcs3#12691]
### Quick summary

In both versions (European and US) if you have the full game (after unlocking it) , the game is unplayable.
It runs. Ask for press start and gets frozen with a loading message.

The demo version indeed is playable instead.

### Attach a log file

[Log.zip](https://github.com/RPCS3/rpcs3/files/9618557/Log.zip)

### Attach capture files for visual issues

[Castlevania Harmony Of Despair PSN [NPEB-00563].zip](https://github.com/RPCS3/rpcs3/files/9618564/Castlevania.Harmony.Of.Despair.PSN.NPEB-00563.zip)
[Castlevania Harmony Of Despair PSN [NPEB-00563] - 2.zip](https://github.com/RPCS3/rpcs3/files/9619014/Castlevania.Harmony.Of.Despair.PSN.NPEB-00563.-.2.zip)

**Comment by Augusto7743** [comment]
Try ASMJIT and after PPU interpreter.

**Comment by AniLeo** [comment]
.rtf uploaded instead of a log file
.jpg uploaded instead of capture files (would not be needed in this case either way)

Closing as Invalid for completely ignoring the report guidelines
