### ISSUE TITLE
MacOS menu graphics corrupt

### ISSUE THREAD

**Issue by jamiet83** [RPCS3/rpcs3#12707]
### Quick summary

<img width="1148" alt="Screenshot 2022-09-26 at 10 26 56" src="https://user-images.githubusercontent.com/65954737/192243990-e11808df-e7a4-44e9-8ac0-cd67924d4249.png">

### Details

As per screenshot, menu graphics are corrupt

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9644982/RPCS3.log)

### System configuration

- SYS: RPCS3 v0.0.24-14188-2655255d Alpha | master
- SYS: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz | 4 Threads | 32.00 GiB RAM | TSC: 3.408GHz | AVX+ | FMA3 | TSX-FA disabled by default
- SYS: Operating system: macOS, Version: 12.6.0
- SYS: Current Time: 2022-09-26T10:37:00
- RSX: Found vulkan-compatible GPU: 'AMD Radeon Pro 570' running on driver 0.2.896
- SYS: Firmware version: 4.89

**Comment by MSuih** [comment]
This happens because our bight themes assume that the OS default colours are black on white. You can select a proper dark theme from settings to work around this.

**Comment by jamiet83** [comment]
please mark as closed, many thanks
