### ISSUE TITLE
Crash using Savestates

### ISSUE THREAD

**Issue by RollTide8569** [RPCS3/rpcs3#12703]
### Quick summary

Game crashes using savestates and quick load.

### Details

Ctrl s crashes my game. I right click the game and boot with savestate but when I use ctrl r to quick load the savestate it emulator crashes again.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9639974/RPCS3.log)

### System configuration

ryzen 7
gtx 1660

**Comment by AniLeo** [comment]
Needs to be retested with RPCS3 not inside OneDrive folder

**Comment by AniLeo** [comment]
Closing due to lack of requested retest
