### ISSUE TITLE
Goldeneye 007: Reloaded

### ISSUE THREAD

**Issue by JetSetter1984** [RPCS3/rpcs3#12712]
### Quick summary

Game used to work fine according to posts on the forum and the compatibility list. Now the game loads in assets fine and seems perfect, but frequently graphics will disappear for a few seconds and then reappear. Very odd as the game has already succesfully rendered the graphics and then decides to discard them and render again... This has also started happening to me on Gran Turismo 5, which now sees certain cars headlights render just a black texture (example, Jaguar XKS car available from Arcade single race menu from the start) and the road and some grass / scenery will disappear for a few moments and then pop back in / reappear.

### Details

Gran Turismo definitely used to render fine for me as it is one of my most commonly played titles. 007 I recently started but have seen footage on youtube without this issue using the same settings.

### Build with regression

I have no idea, first noticed 4 days ago

### Attach two log files

log file 74mb too large

### System configuration

12700k with avx-512
rtx 3090 
ddr4 3600c14
msi gaming edge z690
crucial p5 plus 2tb gen4 nvme
samsung 970 evo 1tb gen3 nvme

**Comment by JetSetter1984** [comment]
Just wanted to add I used DDU and reverted from latest NVIDIA drivers back to 512 driver and 007 now perfect. Close issue please, sorry.

**Comment by kd-11** [comment]
Then I'll close this. GT5 regression is being tracked in https://github.com/RPCS3/rpcs3/issues/12426
