### ISSUE TITLE
rpcs3_old folder gets created every time after updating and doesn't get deleted

### ISSUE THREAD

**Issue by Rex000** [RPCS3/rpcs3#12719]
### Quick summary

Title

Also, what's this "test" folder found in every recent build? I remember it wasn't there before.

### Details

Not needed

### Attach a log file

Not needed

**Comment by AniLeo** [comment]
Working as designed, use one of the discussion platforms if you have questions

**Comment by Rex000** [comment]
So both the "rpcs3_old" and the "test" folder was designed to be in there? What's their purpose?

If we download a fresh RPCS3 build, there is only the "test" folder inside it, which means "rpcs3_old" is a redundant folder that should not be there.

**Comment by AniLeo** [comment]
Locking to prevent further pings as the indication to move to a discussion platform was ignored, the issue tracker is not to ask how/why stuff works the way it does.
