### ISSUE TITLE
[Regression]Ratchet & Clank ITN/FFA crash after boot on Steam Deck/Linux after #12632

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#12729]
### Quick summary

Both Into the Nexus and Full Frontal Assault crash after boot with a black screen and the error:
SIG: Thread terminated due to fatal error: Segfault reading location 00000008038a02f4 at 0000000000c89e04.
Emu Thread Name: 'rsx::thread'.

### Details

Both of these games run fine on my Windows desktop, but the only way I can get into ITN is if I delete the shader cache and run with vulkan, then it later crashes with the same error. Maybe the RSX is misconstructing a shader causing the thread to crash.

### Attach a log file

[RPCS3 ITN.log](https://github.com/RPCS3/rpcs3/files/9678533/RPCS3.ITN.log)
[RPCS3 FFA.log](https://github.com/RPCS3/rpcs3/files/9678535/RPCS3.FFA.log)

### System configuration

- SYS: RPCS3 v0.0.24-14203-8170b91f Alpha | master
- SYS: AMD Custom APU 0405
| 8 Threads | 14.49 GiB RAM | TSC: 2.800GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 5.13.0-valve21.2-1-neptune, Version: #1 SMP PREEMPT Tue, 13 Sep 2022 16:23:48 +0000
- SYS: Current Time: 2022-09-29T12:26:29
- RSX: Found vulkan-compatible GPU: 'AMD RADV VANGOGH' running on driver 22.1.99
- SYS: Firmware version: 4.85

**Comment by JimScript** [comment]
I just checked, this is a regression after #12632

**Comment by kd-11** [comment]
Thanks. I am aware of this linux issue but I have not been able to reproduce it locally yet. I'll give ITN a try and hopefully it crashes :crossed_fingers:

**Comment by MsRiaCayde** [comment]
Ran into this issue roughly an hour ago with similar settings + using Steam Deck. I'll attempt to grab a log and the details.

**Comment by kd-11** [comment]
Fixed in https://github.com/RPCS3/rpcs3/pull/12735
