### ISSUE TITLE
Demon's Souls graphical 

### ISSUE THREAD

**Issue by cholerika** [RPCS3/rpcs3#12723]
### Quick summary

I've been playing Demon's Souls with the recommended setting tweaks and everything else as default + the 60fps patch. The game runs fine, but I have a strange texture issue that only happens when I'm playing on full screen, switching to windowed and back to FS fixes it temporarily but it always comes back. 

### Details

The in game textures while playing on full screen mode sometimes turn black or white, and the problem can only be fixed by swapping to windowed mode. If I stay in windowed mode the issue will not happen again, but if I go back to full screen it eventually happens again. 

All my settings are the default + the reccomended tweaks. Also using the 60fps patch.
I am also utilizing this mod https://www.nexusmods.com/demonssouls/mods/3?tab=files (BLOOM DISABLED file) and this mod https://www.nexusmods.com/demonssouls/mods/53?tab=files (DeS_ButtonGlyphs_XBO_1.00.zip file)

![demonsouls_Moment](https://user-images.githubusercontent.com/114591643/192794521-5e93bf8c-c923-4ef3-9193-1205dcb5290c.jpg)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9665561/RPCS3.log)

### Attach capture files for visual issues

I will be providing a youtube video demonstrating the issue https://www.youtube.com/watch?v=f503_5bWDYs

### System configuration

OS: Windows 10
CPU: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
GPU: Gigabyte RTX 3060
RAM: 16 GB

**Comment by Asinin3** [comment]
If you want to make a valid bug report, dont report bugs with patches and mods installed. Also i dont think that lens flare patch is even needed anymore.

**Comment by cholerika** [comment]
I see, didn't see that specified anywhere. Thank you.

**Comment by Asinin3** [comment]
You don't need to close the issue, just retest and see if it happens without patches and mods. If it does, then its a valid issue and can stay open.

**Comment by cholerika** [comment]
Nvm, I believe it was a bad dump or something. Really weird issue, it's fixed now
