### ISSUE TITLE
[Regression] LittleBigPlanet series crashes on RPCN v0.6

### ISSUE THREAD

**Issue by FluffaLuigi** [RPCS3/rpcs3#12720]
### Quick summary

LittleBigPlanet 1-3 crashes past the intro movie after connecting to custom servers through RPCN v0.6, Games function normally when offline.

### Build with regression

v0.0.24-14196-eea73dea

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9661013/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9661018/RPCS3.log.gz)

**Comment by TorutheRedFox** [comment]
can confirm
