### ISSUE TITLE
[Regression] JoJo Bizzare Adventures: All Star Battle online doesn't work

### ISSUE THREAD

**Issue by DenTerNG** [RPCS3/rpcs3#12724]
### Quick summary

After last update JoJo:ASB online stopped working. I connect successfully, but when I trying to create lobby it just stucks on a loading

### Build with regression

v0.0.24-14200-926496b5

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9667377/RPCS3.log.gz)

**Comment by AniLeo** [comment]
14200 didn't introduce this regression for sure since it only changes usio code, so that's not the right build.
Needs retesting with the latest version either way.

**Comment by RipleyTom** [comment]
I updated the server this morning(~7 hours ago), can you try again?

**Comment by DenTerNG** [comment]
Works great
