### ISSUE TITLE
qt5 Multimedia missing

### ISSUE THREAD

**Issue by red0bear** [RPCS3/rpcs3#12727]
### Quick summary

CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args`
  (WAYLAND_CLIENT) does not match the name of the calling package (Wayland).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  buildfiles/cmake/FindWayland.cmake:52 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  3rdparty/CMakeLists.txt:195 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args`
  (WAYLAND_SERVER) does not match the name of the calling package (Wayland).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  buildfiles/cmake/FindWayland.cmake:53 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  3rdparty/CMakeLists.txt:195 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args`
  (WAYLAND_EGL) does not match the name of the calling package (Wayland).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  buildfiles/cmake/FindWayland.cmake:54 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  3rdparty/CMakeLists.txt:195 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args`
  (WAYLAND_CURSOR) does not match the name of the calling package (Wayland).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  buildfiles/cmake/FindWayland.cmake:55 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  3rdparty/CMakeLists.txt:195 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (WAYLAND)
  does not match the name of the calling package (Wayland).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  buildfiles/cmake/FindWayland.cmake:56 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  3rdparty/CMakeLists.txt:195 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

** AsmJit Summary **
   ASMJIT_DIR=/mnt/bac6b1ca-a348-4e78-81be-7e3e96bb60d3/COMPILE/SOURCES/rpcs3/3rdparty/asmjit/asmjit
   ASMJIT_TEST=OFF
   ASMJIT_TARGET_TYPE=EMBED
   ASMJIT_DEPS=pthread;rt
   ASMJIT_LIBS=pthread;rt
   ASMJIT_CFLAGS=-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS=-Wall;-Wextra;-Wconversion;-fno-math-errno;-fno-threadsafe-statics;-fno-semantic-interposition;-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS_DBG=
   ASMJIT_PRIVATE_CFLAGS_REL=-O2;-fmerge-all-constants;-fno-enforce-eh-specs

CMake Error at 3rdparty/qt5.cmake:12 (target_link_libraries):
  The link interface of target "3rdparty_qt5" contains:

    Qt5::Multimedia

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:48 (include)

### Details

CMake Warning at 3rdparty/qt5.cmake:5 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake

  but it set Qt5_FOUND to FALSE so package "Qt5" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt5 component "Multimedia" config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt5Multimedia/Qt5MultimediaConfig.cmake"

  Failed to find Qt5 component "MultimediaWidgets" config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt5MultimediaWidgets/Qt5MultimediaWidgetsConfig.cmake"

  

Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:48 (include)

### Attach a log file

Dont have it cause i need compile it first.

**Comment by AniLeo** [comment]
Missing system information

**Comment by Megamouse** [comment]
obviously you have to install the qt5multimedia package.
unless you already did

**Comment by RipleyTom** [comment]
You need qttools5-dev package on Debian.

**Comment by RipleyTom** [comment]
https://debian.pkgs.org/11/debian-main-amd64/qtmultimedia5-dev_5.15.2-3_amd64.deb.html

clearly list /usr/lib/x86_64-linux-gnu/cmake/Qt5Multimedia/Qt5MultimediaConfig.cmake as a file in the package, if you have it installed and it doesn't find it, you need to force reinstallation of the package.
