### ISSUE TITLE
Uncharted 3 crash at the launch error 316

### ISSUE THREAD

**Issue by SnakeEaterWRT** [RPCS3/rpcs3#12733]
### Quick summary

hello, I have a bug with my emulateru when I launch uncharted 3, I have no idea how to fix it

I'm on MacBook Pro 2020 M1
the message is : 
F {RSX [0x006d588]} SIG: Thread terminated due to fatal error: Unknown register name: unk
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKCommonDecompiler.cpp:155[:3], in function get_varying_register_location) (errno=316=Unknown error: 316)

### Details

the game starts correctly at the beginning I see the loading with the ring and after black screen and the error message

### Attach a log file

<img width="1057" alt="Capture d’écran 2022-09-30 à 09 48 07" src="https://user-images.githubusercontent.com/114730033/193262618-a513ecd2-858e-4a4b-bfc7-14f9a96a573d.png">

**Comment by Darkhost1999** [comment]
Provide a log file that includes the issue you're reporting. 
The Log file will be ```RPCS3.log.gz``` (sometimes shown as RPCS3.log with a zip icon) or ```RPCS3.log``` (sometimes shown as RPCS3 wtih a notepad icon).  
         * On MacOS the log will be in ```~/Library/Caches/rpcs3```. If you're unable to locate the file copy & paste the path into Spotlight and hit enter.
You can upload a log by dragging the file into a active text box, edit your message, or you can upload to a cloud service like google, mega, pastebin, etc and provide a public link.

**Comment by kd-11** [comment]
This is because the shader is broken (desync) and not a problem with the compiler.
Use atomic fifo mode in advanced tab and enable accurate RSX reservations there as well.

**Comment by SnakeEaterWRT** [comment]
I changed to atomic as requested but I did not understand the rest sorry,
and a quick question:
I also have to do what Darkhost1999 told me or not need?
Sorry if I don't understand everything, I'm really new to this.

**Comment by Darkhost1999** [comment]
If you are still having issues after those 2 settings (atomic fifo accuracy and accurate RSX reservations) are enabled. 1st ask for help on our discord or forums. Then if it's actually an issue you need to provide a log for your issue to be valid. KD11 knows tons more than me. I'm just telling you you failed to read the bug report form.

**Comment by Filthy420** [comment]
You guys need to work on your customer service if your program has error codes that people cannot figure out. Error codes should be able to be traced back to resolvable issues or have a message attached that explains the problem.

**Comment by Valtekken** [comment]
> You guys need to work on your customer service if your program has error codes that people cannot figure out. Error codes should be able to be traced back to resolvable issues or have a message attached that explains the problem.

"Customer service"? Dude, the emulator is free. You're lucky there's even any volunteers to attempt to help ANYONE, considering nobody's paying for their time.

**Comment by AniLeo** [comment]
This is FOSS so you're not a customer, kindly fuck off. This is an issue tracker, not a forum or helpdesk system, clearly you're out of place.
