### ISSUE TITLE
"Thread terminated due to fatal error: Verification failed" Issue

### ISSUE THREAD

**Issue by ManharWii** [RPCS3/rpcs3#12732]
### Quick summary

So Basically I tried Running Cars Race o Rama (2009) and Pixar Cars 2 (2011) on RPCS3 after installing Vulkan. 
Cars 2 wasn't working.... i thought it was because it was because "Ingame" so it wouldn't work...
Cars Race O Rama on the other hand was actually Playable, however I go the same error in Cars 2, "Thread terminated due to fatal error: Verification failed"
I have seen other threads before signing up and they got their problem fixed, but it didn't work me though...

### Details

![The Issue](https://user-images.githubusercontent.com/114737443/193249908-67312f31-a000-45c6-b46e-86f62bf7000f.png)

### Attach a log file

![The Issue](https://user-images.githubusercontent.com/114737443/193250143-013debaa-3e22-40e1-a530-dbc744cc18d1.png)

### System configuration

My PC:
Intel Core i5 4440 (4 cores, 4 threads)
8 GB of Mixed RAM (2x2GB 1333mhz from Kingston sticks and 1x4 1600mhz stick from Samsung)
Intel HD Graphics 4600
128GB SSD from Crucial

**Comment by MSuih** [comment]
You're below minimum requirements, your integrated graphics do not support OpenGL 4.3.

**Comment by ManharWii** [comment]
Oh, thank you for telling me this.
My PC is technically a Potato, so understandable. Have a Good Day!
