### ISSUE TITLE
James Bond 007: Blood Stone - crash on beginning of the second chapter

### ISSUE THREAD

**Issue by kmetininan** [RPCS3/rpcs3#12740]
### Quick summary

James Bond 007: Blood Stone - crash on beginning of the second chapter

### Details

I finished the first chapter with no issues.however upon starting of the second chapter , emulations stops.see below for my custom config and log file for details.
[config_BLUS30289.yml.txt](https://github.com/RPCS3/rpcs3/files/9690638/config_BLUS30289.yml.txt)

### Attach a log file

[james bond 007 blood stone.txt](https://github.com/RPCS3/rpcs3/files/9690636/james.bond.007.blood.stone.txt)

**Comment by YuriNator557** [comment]
Not a valid log file, this is just some useless stuff copied from the GUI. You need to upload the one that RPCS3 generates inside the RPCS3 folder

**Comment by kmetininan** [comment]
> Not a valid log file, this is just some useless stuff copied from the GUI. You need to upload the one that RPCS3 generates inside the RPCS3 folder

here is the log file.
[Uploading RPCS3.zip…]()

**Comment by MSuih** [comment]
Did you try validating your dump to make sure everything's correct and no files are missing?

https://wiki.rpcs3.net/index.php?title=Help:Validating_PlayStation_3_game_dumps#Validating_Blu-ray_disc_games

**Comment by kmetininan** [comment]
> Did you try validating your dump to make sure everything's correct and no files are missing?
> 
> https://wiki.rpcs3.net/index.php?title=Help:Validating_PlayStation_3_game_dumps#Validating_Blu-ray_disc_games

Yes I checked. it shows only ps3updat.pup as missing.

**Comment by kmetininan** [comment]
seems like bad dump issue.closing the ticket.

**Comment by cloudslsw** [comment]
game launch crash on latest build
