### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by zelurker** [RPCS3/rpcs3#12748]
### Quick summary

A lot of games simply end up freezing with no error message if played long enough

### Details

After checking the status of a few games I had freezes in "the last of us", "sonic generations" and "tears of tiara 2 : heir of the overlord", in all the cases no message in the console (linux version), the game simply freezes and stops responding, but it happens after quite a while, it's not easy to reproduce.
The attached log is a session when I tried "tears of tiara 2" twice, it's probably the one where the bug is the most obvious because the fights are quite long, and it's currently impossible to finish a big fight without having this (I tried twice thinking I would have better luck the 2nd time since I would be faster, it didn't work, it froze the 2 times).

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9693587/RPCS3.log.gz)

### System configuration

arch linux, AMD Ryzen 7 2700 Eight-Core Processor, nvidia geforce gtx 1060

**Comment by AniLeo** [comment]
Pirated game being used, closed as Invalid.
