### ISSUE TITLE
regression in pacman museum

### ISSUE THREAD

**Issue by zelurker** [RPCS3/rpcs3#12749]
### Quick summary

the wiki here https://wiki.rpcs3.net/index.php?title=PAC-MAN_MUSEUM says the game works perfectly with default settings, well I get corrupted graphics over all the menus which makes using them quite difficult. Except that the games themselves seem to work perfectly if you can reach them blindly.

### Details

Leave the game running without touching anything, you'll reach this screen where you asked to press the start button with a very nice corrupted graphic 

Sorry I have only 1 log file to provide, I never saw the game working perfectly, it's actually the 1st time I try to run it with rpcs3 !

![pacman](https://user-images.githubusercontent.com/2865423/193476185-0c6feda7-dc82-4c3d-a84e-d5923d64b880.png)

### Build with regression

v0.0.24-14207-eff1e4bd

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9693598/RPCS3.log.gz)

### System configuration

arch linux, AMD Ryzen 7 2700 Eight-Core Processor, nvidia geforce gtx 1060

**Comment by AniLeo** [comment]
Why is GPU texture scaling forced on the Debug Tab? Why is host_root enabled for a commercial game? Needs retest without debug settings.

**Comment by zelurker** [comment]
This fixed it ! Actually I don't know where these settings are in the gui,
there is no debug tab, I fixed them by editing the config.yml file
directly, thanks !
