### ISSUE TITLE
[Regression] Silent Hill Downpour BLUS30565

### ISSUE THREAD

**Issue by Dictavios** [RPCS3/rpcs3#12744]
### Quick summary

Missing graphics, walls, characters, objects erased as camera pans.

### Details

Missing letters and effects such as water puddle at main menu. When the intro begins and Pendleton enters the elevator, the character disappears. Next, parts of the prison structures are not correctly displayed, as camera moves, graphics are bad drawn, erased and redrawn. I tried an old build, 22 junish  2021, as I knew the game was almost perfect when I tried the game before at that time, (same machine by the way), and now graphics are all messed up. Sound works okay as well as controls.  

### Build with regression

0.0.24-14210-50e1e659 Alpha | master

### Attach two log files

[Incorrect log spam, removed]

### System configuration

i5 10400f, 16gb ddr4 ram, Rx480 4gb Gigabyte brand.

**Comment by Dictavios** [comment]
[](url)
![mainmenu](https://user-images.githubusercontent.com/114858024/193450458-8cfdb0f3-6414-4757-98af-edd943021cae.jpg)
![main](https://user-images.githubusercontent.com/114858024/193450518-45eb6df6-4916-4c08-99ab-6662e56e0abf.jpg)

**Comment by Dictavios** [comment]
0.0.19-12987-88bb26af Alpha works just great for me
![mainm2](https://user-images.githubusercontent.com/114858024/193450767-647d780f-b491-4f8f-a6eb-24fbee9d54a4.jpg)
![manm2](https://user-images.githubusercontent.com/114858024/193450775-1a925d95-248f-472b-90c2-fb0b0d94894f.jpg)

**Comment by YuriNator557** [comment]
Log file is missing, what was posted is just some random stuff posted from the GUI
If you are reporting a graphical issue you should also be attaching an RSX capture at least

**Comment by solarmystic** [comment]
You also got to search for the precise build that caused the graphical regression, the range of builds between 0.0.19-12987 and the latest master (v0.0.24-14210) is over 1000+ builds and without the exact responsible commit/build, the developers will not be able to do anything to fix your issue.

**Comment by kd-11** [comment]
MSAA does not have issues on AMD before RX5000 series, and even then the glitch is just some superficial artifacting, not missing geometry.
The OP needs to attach their log for analysis before anything else, or this ticket will be closed as incomplete.

**Comment by Dictavios** [comment]
Thanks for the reply, here I share the log requested. First time posting something. By the way, The Amd driver Im using right now is 22.9.2, the previous 22.8.1 had the same issue.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9692946/RPCS3.log.gz)

**Comment by Dictavios** [comment]
Already tried putting off AA, AF various modes and checking Zcull options on rsx as well as SPU XFloat on cpu side. Also Tried various upscale options, Strict Rendering too. Same issue displayed.

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/193467414-e8819d6e-525b-4dff-8a04-87ab6816040a.png)
This is why we ask for logs.

You have developer debug options enabled that explicitly disable rendering.
Disable ZCULL occlusion = missing geometry.
Force CPU blit = bypass 2D operations unless WCB is enabled.

Closing as invalid.
