### ISSUE TITLE
[Regression] 14173-14174 Guitar Hero Live/GHTV - Framerate tanks from 144 to 25 when caching files making it unplayable.

### ISSUE THREAD

**Issue by TheGuitarHeroNerd** [RPCS3/rpcs3#12745]
### Quick summary

Framerate tanks from 144fps to below 30fps when caching streamed assets

### Details

The game caches streamed files to dev_hdd1\caches\BLES02180_BLES02180\StreamCache so it can reload assets without redownloading them, but since 14174 the framerate seems to completely tank as you can see from the videos below.

Pretty much making it unplayable with streamed assets, 14173 was the last working version before being unplayable.

I also noticed there seems to be a bit of a delay in the RPCS3 display log when it's creating the cached files compared to older versions, like it's taking 1 second per cached file which before was almost instant.

https://user-images.githubusercontent.com/73220666/193454850-ca0ccfca-2768-4fbb-8f19-e26a9d96279a.mp4

https://user-images.githubusercontent.com/73220666/193454852-102d5bf7-cd93-4490-b1ce-e5ca3350ac30.mp4

### Build with regression

0.0.24-14174
PR https://github.com/RPCS3/rpcs3/pull/12678

### Attach two log files

[0.0.24-14174.zip](https://github.com/RPCS3/rpcs3/files/9692538/0.0.24-14174.zip)
[0.0.24-14173.zip](https://github.com/RPCS3/rpcs3/files/9692539/0.0.24-14173.zip)

### System configuration

GPU - Nvidia GeForce RTX 2060 Super
CPU - Intel I7-9700F 3.00GHz
Ram - 16GB

**Comment by Nathan31973** [comment]
I Have the same issue, I experience framerate stutter and frame times going from 0.6ms to over 10.0ms I attach a click highlighting this issue on this high-end system.
My theory is, It looks like whenever the emulator downloads a file it pauses for a period of time waiting for the file to download then continues doing whatever it was doing before.

 Operating System: Windows 11 Pro 64-bit (10.0, Build 22000) (22000.co_release.210604-1628)
      System Manufacturer: ASUSTeK COMPUTER INC.
             System Model: ROG Zephyrus Duo 15 SE GX551QS_GX551QS
                     BIOS: GX551QS.405 (type: UEFI)
                Processor: AMD Ryzen 9 5980HX with Radeon Graphics
                   Memory: 32768MB RAM
           Card name: NVIDIA GeForce RTX 3080 Laptop GPU
        Manufacturer: NVIDIA
           Chip type: NVIDIA GeForce RTX 3080 Laptop GPU

https://user-images.githubusercontent.com/32977935/193611551-9224b298-9945-42cb-8217-6225dfc2da72.mp4

**Comment by GHCripto** [comment]
My problem is exactly the same. The game frequently freezes to the point of being unplayable at certain times. It's probably because as **Nathan3197** said, the emulator stops for a few moments when downloading and then checks until it continues where it left off.

My configuration is the following:
OS: Windows 11 Pro 64bit
Processor: AMD Ryzen 5 5600G with Radeon Graphics
Graphics: AMD Radeon Vega Graphics
Memory: 16GB (dual channel)

https://user-images.githubusercontent.com/64995694/194818667-a44378e0-5dc4-47d0-8f8e-46f76455c281.mp4

**Comment by elad335** [comment]
Try using 3 PPU threads, this is a setting in debug tab.

**Comment by TheGuitarHeroNerd** [comment]
> Try using 3 PPU threads, this is a setting in debug tab. And retest the pr build with 2.

Will give that a shot, on the latest RPCS3 build or the new wait flag build, or try this first on the latest build then the other one.

**Comment by elad335** [comment]
With 3 it doesn't matter which.

**Comment by TheGuitarHeroNerd** [comment]
Tested, don't seem to have any change with 3, i'll test out the next one as soon as it's built.

**Comment by TheGuitarHeroNerd** [comment]
> Try using 3 PPU threads, this is a setting in debug tab. And retest the pr build with 2.

Tested the PR with 2 and the unplayable lag is gone now

Tho i did get this error but might be unrelated to the issue, Here's the log just in case.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/9778527/RPCS3.zip)

![image](https://user-images.githubusercontent.com/73220666/195647323-cbff42ab-dc11-4ec4-92c9-1242adc09c72.png)
