### ISSUE TITLE
[Task] OpenGL glitchiness when using radeonsi

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#12752]
This seems like a regression, but it is hard to tell if it comes from our side or not because the ogl renderer was re-architected recently. I'll need to do a deep dive to figure out why it has such glitchy visuals under radeonsi and why this isn't observed under proprietary AMD and NVIDIA drivers. Performance is pretty good on radeonsi, though vulkan running on RADV now outpaces it which is good.
Relates to https://github.com/RPCS3/rpcs3/issues/10871

Example screenshot:
![image](https://user-images.githubusercontent.com/15904127/193581531-bdf40ed0-bb49-4069-8f75-258b77f14f17.png)

**Comment by MastaG** [comment]
I've seen these corruptions in this game before, but I was using Vulkan on NVidia graphics.
Playing with the settings eventually fixed it.
