### ISSUE TITLE
THE iDOLM@STER One For All [BLJS10260] upscaling issue

### ISSUE THREAD

**Issue by nini22P** [RPCS3/rpcs3#12754]
### Quick summary

When I changed the resolution scale, the screen appeared significantly jagged.

### Details

rpcs3 version: rpcs3-v0.0.24-14217-73784b9e_win64

**This is resolution scale 100%**
![100%](https://user-images.githubusercontent.com/60903333/193607572-d16b8474-fd45-4c59-8109-517f8ce613c9.png)

**resolution scale 150%**
![150%](https://user-images.githubusercontent.com/60903333/193608017-d08fc527-bf62-4927-95c5-33a825cdf885.png)

**resolution scale 200%**
![200%](https://user-images.githubusercontent.com/60903333/193608354-91b02fd2-1c57-4c36-8355-b2c9068bb5d5.png)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9698552/RPCS3.log.gz)

### System configuration

OS: Windows 10 Pro 21H2 19044.2006
CPU: i7-6700HQ
GPU: NVIDIA GeForce GTX 970M
GPU driver version:	31.0.15.1694

**Comment by kd-11** [comment]
This works as intended. The game's internal AA is not expecting fractional scaling which is why 150% looks bad, because there are no 1.5 pixels. Just stick to square integer scaling multiples (100%, 200%, 400%) with games like these.
