### ISSUE TITLE
Cannot re-dock / anchor game list to the main window

### ISSUE THREAD

**Issue by FridgeRacer** [RPCS3/rpcs3#12757]
### Quick summary

I accidentally removed the game list from RPCS3's main window, leaving it as a standalone floating window that is unable to be anchored within the main RPCS3 window again.

### Details

I cannot seem to be able to re-dock it, even when holding buttons like CTRL, Shift or ALT while dragging the game list window over to the main RPCS3 window.

Closing the game list window, then opening it through View -> Show Game List only spawns a standalone window again.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9708935/RPCS3.log)

### Attach capture files for visual issues

![bilde](https://user-images.githubusercontent.com/40672277/193874535-63561cbb-92d8-4069-9a5d-834a0ce8969f.png)

### System configuration

Arch Linux with KDE Plasma 5.25.90, Qt 5.15.6
RPCS3 0.0.24-14211-af8c8714 (build from source using AUR script)

### Other details

As a workaround, I renamed ~/.config/rpcs3/GuiConfigs/CurrentSettings.ini and generated a new one by launching RPCS3, then I compared the two files to see which lines I could safely remove from [GameList] and [main_window], now I have the Game List embedded within the main RPCS3 window again.

**Comment by RipleyTom** [comment]
It works fine here(KDE Plasma 5.25.5 & QT 5.15.5). It might be an issue with your theme maybe?.

**Comment by FridgeRacer** [comment]
Hey sorry, haven't had time to test on default Plasma settings yet, but thanks for getting back to me to confirm that it's just me.
I'm using the default Breeze theme, but I've adjusted a lot of system settings (as one does). Feel free to close this issue now, and I could maybe just reopen it when I do get time to test on default Plasma system settings, and find that it still won't work; whatever you think is best.

Cheers!

**Comment by udance4ever** [comment]
> As a workaround, I renamed ~/.config/rpcs3/GuiConfigs/CurrentSettings.ini and generated a new one by launching RPCS3, then I compared the two files to see which lines I could safely remove from [GameList] and [main_window], now I have the Game List embedded within the main RPCS3 window again.

did you ever figure out a more elegant way to redock the windows?  I just did a diff between the old and new inis and it's not clear to me what can be removed right away (but will tinker!)
