### ISSUE TITLE
Ratchet & Clank Future: A Crack in Time Needs MSAA in OpenGL to not be blurry in certain places

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#12760]
### Quick summary

When OpenGL is enabled, certain graphical effects(the ones that were invisible for a while) cause the depth of field to get really close to the camera.

### Details

Vulkan:
![BCUS98124_screenshot_2022_10_05_22_16_32](https://user-images.githubusercontent.com/66685584/194221093-302c3ca8-66d0-4843-85fe-fb5140f79e6f.png)

OpenGL:
![BCUS98124_screenshot_2022_10_05_22_16_05](https://user-images.githubusercontent.com/66685584/194221250-872c94e7-b677-439b-a2e3-5bee302640c6.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9721478/RPCS3.log)

### Attach capture files for visual issues

[BCUS98124_20221005221233_capture.zip](https://github.com/RPCS3/rpcs3/files/9721481/BCUS98124_20221005221233_capture.zip)

### System configuration

- SYS: RPCS3 v0.0.24-14226-87411da9 Alpha | master
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2022-10- 5T22:27:18
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 511.23.0.0
- SYS: Firmware version: 4.88

**Comment by kd-11** [comment]
Can you give an example scenario? Like go to place X and do action Y to trigger so I can repeat the steps locally. From the screenshot it doesn't look like DoF and I know OpenGL does not currently support MSAA on rpcs3 (still unimplemented) which this game needs for correct dynamic resolution scaling.

**Comment by JimScript** [comment]
It probably is just the Dynamic Resolution scaling, but here is a video demonstrating the effect:

https://user-images.githubusercontent.com/66685584/194538744-7c1a4ca0-f210-4393-811c-6171a827e02d.mp4

**Comment by kd-11** [comment]
I'll just close it, we already have several tickets tracking OpenGL feature support.
