### ISSUE TITLE
[Regression] inFamous far rendering Broken in Vulkan after #12762

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#12766]
### Quick summary

After #12762, the far rendering of buildings is broken in Vulkan.

### Details

Before:

![BCUS98119_screenshot_2022_10_07_03_17_55](https://user-images.githubusercontent.com/66685584/194532872-f4019e71-ea74-4983-9ff9-8ddbb5406bc2.png)

After:

![BCUS98119_screenshot_2022_10_07_03_15_56](https://user-images.githubusercontent.com/66685584/194532923-3bedb173-405a-4752-9f7d-664593892eb4.png)

### Build with regression

v0.0.24-14231-df46e513

### Attach two log files

[RPCS3inF_B.log](https://github.com/RPCS3/rpcs3/files/9733097/RPCS3inF_B.log)
[RPCS3inF_A.log](https://github.com/RPCS3/rpcs3/files/9733098/RPCS3inF_A.log)

### Attach capture files for visual issues

[BCUS98119_20221007033316_capture.zip](https://github.com/RPCS3/rpcs3/files/9733195/BCUS98119_20221007033316_capture.zip)

### System configuration

- SYS: RPCS3 v0.0.24-14231-df46e513 Alpha | master
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2022-10- 7T03:21:09
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 511.23.0.0
- SYS: Firmware version: 4.88

### Other details

I included an RSX capture, but you can't see the problem in it. You can definitely see the problem in gameplay though.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/12768
