### ISSUE TITLE
Rock Band 3 customs crashing game

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#12761]
### Quick summary

It seems like I cannot play customs in this game without it crashing randomly (usually in arena and festivals, but sometimes big clubs and music videos as well which is what happened here).

### Details

When I boot up a custom song, it will play just fine, yet there is always a chance of the game just crashing the emulator with the F {PPU[0x1000000] Thread (main_thread) [0x0093faac]} VM: Access violation reading location 0x8 (unmapped memory) error or some variation of it. I have the log file and a screenshot to show what I consistently get.

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/9724897/RPCS3.zip)

### Attach capture files for visual issues

![Sad](https://user-images.githubusercontent.com/114825943/194316775-00394333-46ef-4df7-a131-575e9a4a976c.PNG)

### System configuration

CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz, 3504 Mhz, 8 Core(s), 16 Logical Processors
GPU: NVIDIA GeForce RTX 3060 Ti
RAM: 64 GB

**Comment by hectaacdc** [comment]
If it's happening to you ONLY when playing customs, then it's not an RPCS3 issue. I know this, because I had this issue myself, some custom songs seem to have a different type of encryption in the MOGG (audio) file that the emulator has issues with, and crashes when you attempt to play them. You just have to decrypt them and the song will play with no issues.

**Comment by golive03** [comment]
Most of the time the songs play fine until the results screen unless it's a festival venue (which has a chance of crashing early into the song or before it even starts). Seems I have no issues in small clubs though.

But yeah I should look into that. Do you know if there is a way to decrypt MOGGs with C3 CON Tools? If so, where do I look?

**Comment by AARP41298** [comment]
FYI
Open a custom on [onyx](https://github.com/mtolly/onyxite-customs)
Clasify them in encrypted (the one that doesnt have sound on preview) and non-encrypted

For the non-encrypted, i suggest to make a pack:
onyx->quick convert->
![image](https://user-images.githubusercontent.com/33246631/204601671-a458180b-a5d3-4570-a7d6-c133be643c84.png)
->the name you want

For the encrypted:
Use C3CONTools
Open the `ps3/Merged Songs` folder
create a blank text `songs.dta`
Open C3CONTools/PS3 Converter
Make sure `Merge new songs with existing` is activated
Drag 1 file of the encrypted customs (it will import everything)
Begin
Open `(RPCS3 folder)\dev_hdd0\game\BLUS30463\USRDIR\HMX0756` and paste everything of `Merged Songs`

There will be some encrypted and buged songs:
For those, use C3CONTools/Phase Shift Converter and reconvert them with onyx

I recommend to install [RB3DX](https://github.com/hmxmilohax/rock-band-3-deluxe) too

**Comment by CaptnCH** [comment]
Someone please just close this. This isn't a RPCS3 issue at all and will occur on real hardware.
