### ISSUE TITLE
[Regression] Far Cry 3 Where did the room go?

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12765]
### Quick summary

I had a failure to communicate from my distracted and socially confused brain and GitHub decided my videos weren't good enough.
Inside far cry 3 the room has turned into the sky. OGL not effected. Turning the camera in circles shows this endless sky effect is only at certain camera angles. Or maybe I should say the room is visible at certain angles. It's 50/50 70/30

In this test I'm only using wcb which fixes so much it is impossible to test without.

### Details

![image](https://user-images.githubusercontent.com/60384196/194524880-f6f8bd20-83f6-4caa-8954-e4b590699d62.png)

![image](https://user-images.githubusercontent.com/60384196/194524930-a61f8c37-88df-42f1-88df-b013a9228ffb.png)

My words are autistic and I don't want to write a book. Just tell me if you can't see the pictures write 1,000 words.

### Build with regression

RPCS3 v0.0.24-14231-df46e513

### Attach two log files

[Working](https://github.com/RPCS3/rpcs3/files/9732753/RPCS3.zip)

[Broken](https://github.com/RPCS3/rpcs3/files/9732754/RPCS3.log)

### Attach capture files for visual issues

RSX capture from the broken build:
[Broken rsx capture](https://mega.nz/file/u0o1DYZB#lnUUfLCwR-_z55VX6DnSnykYRoIN1ZyYuEc1qUDb5pg)

RSX capture from the working build:
```
 F {RSX [0x00e07cc]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\surface_utils.h:116[:4], in function src_rect)
```
Tried multiple times

### System configuration

In the log
R5 3600
GTX 1660s
16 gigs ram
Windows 11 beta branch

### Other details

OpenGL works
Vulkan does not
Sometimes my brain doesn't say things to others. Like I forgot to think about the transmission **and** receiver.
Everything previews perfect here.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/12768
