### ISSUE TITLE
Metal Gear Solid HD Collection Peace Walker Co-Op stuck on loading

### ISSUE THREAD

**Issue by RurouniDonut** [RPCS3/rpcs3#12771]
### Quick summary

I'm trying to play Co-Op with a friend in Peace Walker but the game is stuck on connecting for him when I host and the same when he hosts. Sometimes his name will pop in the game lobby but he will never join fully. I try inviting him directly. We are connected to RPCN and have the game simulating RPCN

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9738204/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9738205/RPCS3.log)

**Comment by RipleyTom** [comment]
It should be fixed now?

**Comment by RipleyTom** [comment]
Should be fixed, reopen if it is not.

**Comment by xynxynxyn** [comment]
I can confirm that this works now, at least for the first few missions.

**Comment by EnterSandman47** [comment]
i still have this problem unfortunately
