### ISSUE TITLE
[Regression] God of War Ascension

### ISSUE THREAD

**Issue by Linear524** [RPCS3/rpcs3#12770]
### Quick summary

Shadows flickering. Shadow draw distance is broken. Inventory menu whole screen is flickering. Music timing broken.

### Details

This title was fully playable at RPCS3 14228 (October6 2022).
But recent update (October7 2022) have some serious shadow flickering and broken music timing. Also inventory screen is flickering every with every second frame greyed out. Maybe something was broken after pull/12768, but I don;t know for sure...

### Build with regression

0.0.24-14232

### Attach two log files

No logs

### System configuration

- SYS: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz | 14 Threads | 31.83 GiB RAM | TSC: 2.594GHz | AVX+ | FMA3 | TSX disabled by default
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2022-10- 7T23:45:19
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1080' running on driver 512.59.0.0
- SYS: Firmware version: 4.87

RCB is ON, Force CPU Blit is ON. Everything else is set by Default.

### Other details

Last working build for GoWA was 0.0.24-14228

**Comment by kd-11** [comment]
Everything works fine on my end as well, including when using RCB+WCB+Force CPU blit.

**Comment by solarmystic** [comment]
@Linear524 You mention flickering shadows and flickering inventory menu screen but do not provide gifs or videos to show them as such. Missing RSX Captures as well for a graphical issue report.

At least provide some visual proof in your report, please.

Also not seeing any issues on the latest master, inventory menu is fine and no flickering shadows here.

https://user-images.githubusercontent.com/4345150/194672665-7ef194b3-7558-43bd-9211-910a6a9c8e15.mp4

https://user-images.githubusercontent.com/4345150/194673075-54ab1d5d-b19f-4ff1-bc5f-48c1c9b35fab.mp4

**Comment by prfd** [comment]
https://user-images.githubusercontent.com/84674931/194683197-272cedf0-7c5a-4c97-9136-54e31cdd987c.mp4

**Comment by jobs-git** [comment]
> FPS_.59.99._.Vulkan._.0.0.24-14232._.God.of.War_.Ascension.EU.BCES01741.2022-10-07.23-15-35.mp4

I get this flickering too, did you solve it? @Linear524  The title should have been change instead of closing, or at least you could have shared how you were able to solve it before closing.
