### ISSUE TITLE
[Feature request] Wiki Shortcut to right-click context (over game.)

### ISSUE THREAD

**Issue by SnabbSpelare** [RPCS3/rpcs3#12776]
### Quick summary

> Button to access the wiki page for the select game so you can easily get it's config needed.
![image](https://user-images.githubusercontent.com/108371375/194716499-7e281c10-3bd1-44e8-8f1e-a126d705f16d.png)

### Details

How affects RPCS3:
- *UI*
- Important feature since many go to wiki when they experience a crash, so this may help that user find the right wiki page with proper config. But also a way to get the page for end user with wiki info about config.

Questions
- Where does it go?
> Somewhere between the spaces at.. "Check Game Compatibility." or "Create Custom Configuration"
Extra: "Check Config Compatibility With Wiki"?
- What else do it need?
> "Create and Download Wiki Config"?

Reasons why to add:
- It's quick and easy, painless to use.
- This would potentially reduce the need to keep a tab on the wiki and helps users spend less time on their browser and more time on program.

**Comment by AniLeo** [comment]
Check game compatibility opens the compatibility list on the game's compatibility entry. Clicking on the game's name on the list opens the respective wiki page. I don't see a point for another setting when this is already possible.

**Comment by SnabbSpelare** [comment]
Thanks for reply.
