### ISSUE TITLE
Illegal instruction (bddc)

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#12785]
### Quick summary

Illegal instruction at 00007ff809d4bddc (0x0f0b554889e54156534881ecd0000000).
Thread id = 123145445515264.

### Details

this error appears when i'm trying to lunch a game (for different game), in the "compiling shaders" process.
i'm using an Apple MacBook Air.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9742788/RPCS3.log)

**Comment by AniLeo** [comment]
Intel iGPU on macOS drivers an extremely weak CPU. Intel drivers are not supported.

**Comment by AnDrEaFo** [comment]
I can do somethings? i see a lot of people using macOS with no problems. thank you

**Comment by AniLeo** [comment]
Buy hardware that isn't a potato, the issue is already closed, locking to avoid further spam
