### ISSUE TITLE
Disagea 4 black screen issue

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1278]
![image](https://cloud.githubusercontent.com/assets/11285640/10821761/9c03c2ac-7e86-11e5-8990-2998bdbc2ff3.png)
please fix on the next builds

**Comment by tambry** [comment]
@zminhquanz Please attach the proper files needed for us to determine the problem
Please also see [FAQ](https://github.com/RPCS3/rpcs3/wiki/FAQ) and [Reporting issues](http://www.emunewz.net/forum/showthread.php?tid=171465).
