### ISSUE TITLE
Bug: Need For Speed Undercover smoke issue.

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#12784]
### Quick summary

Need For Speed Undercover's smoke, where you finish the race, renders with a line going through it that is NOT present on PS3. I tried accuracy settings to no avail.

### Details

RPCS3:
![BLES00450_screenshot_2022_10_09_23_15_42](https://user-images.githubusercontent.com/61447828/194782271-196ccca6-729d-4cfb-acb9-035c11d8dce0.png)
PS3:
![IMG_20221009_233428](https://user-images.githubusercontent.com/61447828/194782702-67642b47-57d0-4f93-9059-459ac0f5a6d9.jpg)
I know it's not the best image, but I can't take a good screenshot with this game on PS3.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9742700/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1xs623o5n7oUoN4I2Dy-HgepGw43cFYzr/view?usp=sharing

### System configuration

Ryzen 5 5600x, GTX 1050 Ti driver 517.48, Windows 11 22H2.

**Comment by Ordinary205** [comment]
The line bug seems to have been fixed.
![Need for Speed Undercover](https://github.com/RPCS3/rpcs3/assets/125112932/8799d579-9e76-481e-98bf-0f75ab7f48ba)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12560499/RPCS3.log.gz)
