### ISSUE TITLE
Resistance Fall of Man - No controller vibration

### ISSUE THREAD

**Issue by Ubernoodles** [RPCS3/rpcs3#12797]
### Quick summary

No controller vibration with Xbox One controller, Xinput, vibration does work in RPCS3 controller settings and in other games tested.
No controller vibration with DualShock4, Xinput, vibration does work in RPCS3 controller settings and in other games tested.
This is using latest RPCS3 build. Is this a known issue?

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9758981/RPCS3.log)

**Comment by Satan86** [comment]
This game did NOT have vibration on PS3. It was released in 2006 and received NO update via PSN to enable it. You can get the update only if you connect to the custom servers, which, if you want, can be discussed on the PSONE Discord: https://discord.gg/whMwWeMv.
