### ISSUE TITLE
Flickering textures in Silent Hills 3 HD

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1279]
In Silent Hills 3 HD the warning ("this game contains violent scene") and menu flickers. It seems that textures are corrupted on some frame, or that their info (width/height/...) is not properly stored.

Ingame the textures are also randomly swapped everywhere, I guess it's tied.

**Comment by vlj** [comment]
Apparently the NV4097_SET_SURFACE_COLOR_TARGET is not set on every frame.
Does PS3 sometimes understand which are the surface to draw implicitly ?

**Comment by vlj** [comment]
Disregard the color_target comment it was an error on my end.
It looks like rsx::get_address() is sometimes wrong with offset and dma of surface A.

**Comment by vlj** [comment]
Some investigations leads to think that rsx::method_registers[NV4097_SET_DEPTH_MASK] is not properly set. And it's probably not the single one register not properly set.

**Comment by vlj** [comment]
I found the issue, it's in cellResc.cpp.

The function SetupRsxRenderingStates is writing directly to rsx::method_register instead of populating the command queue. Since this function is likely called by some threads and not by the rsx thread, this leads to race condition, ie state is changed when rendering operation occurs.

I don't know the purpose of the function in cellResc (rescaling output ?) but removing all call to rsx::method_register fix the flickering in SH3.

**Comment by Zangetsu38** [comment]
@vlj What line exactly in cellResc.cpp ?

**Comment by tambry** [comment]
@Zangetsu38 He said all lines that reference rsx::method_register

**Comment by Zangetsu38** [comment]
@tambry oh sorry ^^

**Comment by vlj** [comment]
Something is strange, it looks like all depth write command are inverted ie if NV4097_SET_DEPTH_MASK is 0 then depth write should be enabled and if NV4097_SET_DEPTH_MASK is 1 then it should be disabled.

It's possible that some draw/clear command implicitly reset the NV4097_SET_DEPTH_MASK register, or it should be interpreted in combinaison with another register because I think some sample use the register in the expected way...

**Comment by vlj** [comment]
Closing, Silent Hill 3 HD now renders mostly correctly (except shadow and post processing/lens flare)
