### ISSUE TITLE
Infamous 1 distortion graphical error

### ISSUE THREAD

**Issue by Zulthar** [RPCS3/rpcs3#12809]
### Quick summary

The distortion effect does not look as it would on a regular ps3

### Details

The graphical distortion effect is not distorting the graphics properly, I believe it isn't interacting with another system property. This effect is seen in the fans on rooftops, the hover ability, and smokestacks

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9780093/RPCS3.log)

### Attach capture files for visual issues

Unfortunately attempting to capture this crashed my emulator, it should be plainly visible at any point the distortion effect occurs

**Comment by Darkhost1999** [comment]
Similar to https://github.com/RPCS3/rpcs3/issues/11149
Technically same issue different game. Tagging for reference.

**Comment by JimScript** [comment]
Well, I just edited issue #11149's title to include inFamous 1 as this isn't the first time this issue has popped up

**Comment by Asinin3** [comment]
Closing, no image, no rsx/renderdoc. And duplicated now that other has been edited (I would put Infamous issue in OP of that aswell)
