### ISSUE TITLE
[NPUB30610] MGS3 tunnel lighting graphical bug

### ISSUE THREAD

**Issue by Codex-** [RPCS3/rpcs3#12810]
### Quick summary

When proceeding towards the The Pain in the caves/tunnels in MGS3 (pretty early game) there is a sweet spot where there's just light at the end of the tunnel, but not _the_ light at the end of the tunnel:
Renders:
![image](https://user-images.githubusercontent.com/8297838/195726942-d63edcae-7545-41c2-bd8b-1ef4fd27afcc.png)

Normally looks like:
![image](https://user-images.githubusercontent.com/8297838/195726989-3e5e4343-c1db-4988-8588-db773872e7b1.png)

Leading up to:
![image](https://user-images.githubusercontent.com/8297838/195727024-8afcb9aa-fa0c-4836-9f4e-1ffb1244ea90.png)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9781170/RPCS3.log.gz)

### Attach capture files for visual issues

[mgs.webm](https://user-images.githubusercontent.com/8297838/195728192-8f389773-fdcb-40fe-b0d7-60958107ec6f.webm)

### System configuration

```
- SYS: RPCS3 v0.0.24-14266-cf86b6c1 Alpha | master
- SYS: AMD Ryzen 9 5900X 12-Core Processor | 24 Threads | 31.92 GiB RAM | TSC: 3.700GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 22623, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2022-10-14T12:06:05
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3070 Ti' running on driver 517.48.0.0
- SYS: Firmware version: 4.88
```

**Comment by kd-11** [comment]
You can see the same glitch here https://youtu.be/WH-GIiJRUGU?t=367
That is not on rpcs3. Seems to be a game issue?
