### ISSUE TITLE
[Feature request] Mac Launchpad Game Category

### ISSUE THREAD

**Issue by darkuser89** [RPCS3/rpcs3#12816]
### Quick summary

can you add this to the info.plist so that rpcs3 is recognized as a game in the launchpad? `<key>LSApplicationCategoryType</key> <string>public.app-category.games</string>`

**Comment by marcoluc97** [comment]
https://github.com/PCSX2/pcsx2/pull/7205

**Comment by Megamouse** [comment]
Fixed in #13200

**Comment by schm1dtmac** [comment]
This had to be retracted FYI as of #18576 due to Apple auto enabling Game Mode for apps identified by LaunchServices as being a game.
