### ISSUE TITLE
GOD OF WAR 3 [BCES00510]

### ISSUE THREAD

**Issue by Naniboy007** [RPCS3/rpcs3#12819]
### Quick summary

after pulling the lever water doesn't fill up
<img width="1273" alt="Screenshot 2022-10-16 at 1 04 40 PM" src="https://user-images.githubusercontent.com/113497507/196024054-20097f94-b714-4b72-8650-29acaf45ffde.png">

### Details

FPS is not stable goes upto 23fps only even all pathes applied

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9793847/RPCS3.log)

### Attach capture files for visual issues

![Uploading Screenshot 2022-10-16 at 1.04.40 PM.png…]()

### System configuration

M1 chip
8 core cpu
7 core GPU
8 GB RAM

**Comment by AniLeo** [comment]
Performance is too low for the game to function properly, it's normal that stuff breaks when the game is underperforming a lot
