### ISSUE TITLE
God of war ascension [BCES01741]

### ISSUE THREAD

**Issue by Naniboy007** [RPCS3/rpcs3#12823]
### Quick summary

Graphical glitches some areas character doesn’t proceed next

### Attach a log file

> 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/9795535/RPCS3.zip)

### Attach capture files for visual issues

![2BF99211-5579-4712-880F-EB2A92DCE2F1](https://user-images.githubusercontent.com/113497507/196054975-488a63f3-f514-478a-afa2-8ec58038c220.png)
At this place cant proceed next

### System configuration

Apple M1 
8GB ram
8 core CPU
7 core GPU

**Comment by YuriNator557** [comment]
Pirated game, no support
