### ISSUE TITLE
[Feature request] HLE Psarc decompression zlib & lzma

### ISSUE THREAD

**Issue by Nerboruto** [RPCS3/rpcs3#12825]
### Quick summary

I don't know if it has already been implemented and if it is possible to do,
several games are distributed inside psarc container.

### Details

I tried on motorstorm pacific rims, one with unzipped psarc and compressed iso the other with compressed psarc and normal iso, both defragmented on hard disk. in the test I got that the version with psarc has a latency when loading game assets, in practice you can see some popping.
tested on xeon haswell 4c8t e3-1230v3@3.7ghz tsx forced microcode 07

**Comment by AniLeo** [comment]
This is implemented in game code, not in the PS3 OS.

**Comment by Nerboruto** [comment]
pity that nothing can be done ... I had already noticed that the decompressed archives run better.
I had read fios in the log and thought there was something about disk cache management.
