### ISSUE TITLE
F {RSX [0x0372ca0]} SIG: Thread terminated due to fatal error: Verification failed LBP3 [BCUS98362]

### ISSUE THREAD

**Issue by deadmeme5** [RPCS3/rpcs3#12821]
### Quick summary

So basically i try to play LBP3 rec. settings mid ranged pc and the prologue in the game played fine but when i play the 2nd world 1st level the game just says Compiling shaders and puts audio in a loop. No other segment in the game does this so i guess its a bug with the shaders. here are logs : 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9794673/RPCS3.log)

### Attach capture files for visual issues

freezes on this cutscene, upon loading it.

![image](https://user-images.githubusercontent.com/46449091/196038863-b932efd3-2e10-4a14-8383-f023051dceec.png)
![image](https://user-images.githubusercontent.com/46449091/196038893-de8f626f-7707-4fe3-913e-0943c6e32cda.png)
![image](https://user-images.githubusercontent.com/46449091/196039036-c43fcbb7-1e14-4a76-8697-5e7477b2b4ef.png)
![image](https://user-images.githubusercontent.com/46449091/196039055-8225010d-c776-4c85-bc28-ed65046456b6.png)

### System configuration

OS:  Windows 11 
NVidia 3D settings: image settings: Performance
I dont think anything else is needed here, if so tell me to add.

**Comment by AniLeo** [comment]
Invalid settings, shader interpreter only being used which is a debug setting

**Comment by deadmeme5** [comment]
> Invalid settings, shader interpreter only being used which is a debug setting

could you elaborate?

**Comment by AniLeo** [comment]
If you want to ask for support, ask for support on one of the platforms for that purpose, such as Discord, the Forums or the Subreddit. The tracker is to report issues following the guidelines, which this issue does not meet.
