### ISSUE TITLE
Gran Turismo 6 does not load tracks and cars in RPCS3

### ISSUE THREAD

**Issue by lumospro** [RPCS3/rpcs3#12826]
### Quick summary

Игра начинается, но с некоторыми ошибками. Вы можете просмотреть их в прикрепленном файле

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9803011/RPCS3.log.gz)

### System configuration

CPU: Intel Xeon 1230v2
GPU: NVIDIA GTX 650

**Comment by AniLeo** [comment]
Bad settings, does not follow template, not even written in English. This is a support request, not an issue ticket.
