### ISSUE TITLE
Sixaxis controller not detected in Heavenly Sword

### ISSUE THREAD

**Issue by PZerua** [RPCS3/rpcs3#1283]
The game has some intro logos, but before main menu the game complains about "Sixaxis Wireless Controller not detected" and doesn't go further. Log does not provide any explicit info about the problem (as far as I can see), but I attach it since you will probably see more than me. 

Game boots in any PPU/SPU configuration, except with PPU Interpreter 2, where an exception occurs in instruction MFVSCR.

**EDIT:** To fix this issue the game has to be updated to version 1.10, this patch introduced DualShock 3 support. Anyway, seems that RPCS3 doesn't support Sixaxis, so I leave the issue open.

![heavenly1](https://cloud.githubusercontent.com/assets/8772233/10924779/7bbd5a10-8289-11e5-8828-c6ded539fdf1.PNG)
![heavenly2](https://cloud.githubusercontent.com/assets/8772233/10924780/7bbfbe72-8289-11e5-82a4-a2bc9f24b5aa.PNG)

I had to upload the log to mega due its size: https://mega.nz/#!Fdg2DLDK!1z4freANRHCsGEoOvd75-vyW6oIfInmHACsHd5ljI6E

**Comment by Zangetsu38** [comment]
@PZerua I d'ont Have this Screen, My rpcs3 Crash after 
![capture d ecran 2015-11-04 00 37 37](https://cloud.githubusercontent.com/assets/5261759/10925187/5273f850-828c-11e5-8bee-30e6e3757eaa.png)

**Comment by PZerua** [comment]
You seem to have the european version. In my case, after 2 min showing this screen goes to sixaxis complaining.

**Comment by Zangetsu38** [comment]
My Log https://github.com/Zangetsu38/Log-Rpcs3/blob/master/BD/EUR/BCES00078-%5BHeavenly%20Sword%E2%84%A2%5D.log
@PZerua hmm I see

**Comment by Zangetsu38** [comment]
@PZerua look that http://www.emunewz.net/forum/showthread.php?tid=173095 I have no probleme detect controller for me  :)

**Comment by Zangetsu38** [comment]
Closed Isue :)

**Comment by B1ackDaemon** [comment]
Same contoller issue with demo version (NPUA80103).

**Comment by raven02** [comment]
Wonder if https://github.com/RPCS3/rpcs3/pull/2733 helps this game on detecting the Sixaxis controller

**Comment by AniLeo** [comment]
Can you retest with latest build? Try with and without DualShock 4 input if possible.

**Comment by Xcedf** [comment]
No longer an issue on master if playing with DualShock 4

**Comment by vatomalo** [comment]
Still an issue with DS3, SCPtoolkit, and motion sensor patch. Not sure which one causes it, but same error message.

**Comment by AniLeo** [comment]
Yeah, Sixaxis is only implemented on DS4 handler AFAIK

**Comment by Megamouse** [comment]
Please retry with newest master build

**Comment by vatomalo** [comment]
@Megamouse 
I did try did not get the same issue, but this game has so many issues i was unable to properly test because of black screen after intro video. Thanks Megamouse

**Comment by AniLeo** [comment]
Closing as fixed on latest master
