### ISSUE TITLE
Skylanders Imaginators Bug

### ISSUE THREAD

**Issue by twelvegauge** [RPCS3/rpcs3#12834]
### Quick summary

Gamebreaking bug during the golden arcade

### Details

During Noob Testing, two of the ducks are unable to be knocked down, making the game impossible to finish.

### Attach a log file

[Uploading RPCS3.log.gz…]()

### Attach capture files for visual issues

![Screenshot_1](https://user-images.githubusercontent.com/116045986/196314172-08f83617-6d14-420b-a4bf-fb7a87d1b9da.png)

### System configuration

CPU - Intel i7-10700F
RAM - 16 GB
GPU - NVIDIA GeForce RTX 2070 Super
GPU Driver - 516.94

**Comment by Darkhost1999** [comment]
Your log didn't finish upload. Please reupload.
