### ISSUE TITLE
Ratchet and Clank A Crack in Time [BCUS98124] Rectangles everywhere 

### ISSUE THREAD

**Issue by PodcasterMike** [RPCS3/rpcs3#12838]
### Quick summary

Suddenly i have rectangles everywhere. i changed no settings and everything is looking crappy.

### Details

I played the first 2 hours totally fine. then the next day, every time i boot, or load a save state, i get rectangles everywhere. they seem to disappear when i take off Anti Aliasing, but it looks so blocky i honestly can't tell if its too bad to see them. i changed NO settings and yet the graphics got worse. so i have been changing settings in GPU as well as the Read Write buffers in advance, or even changing the resolution from 720 to 1080 but NOTHING removes the rectangles.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9813944/RPCS3.log.gz)

### Attach capture files for visual issues

[Ratchet Clank Crack in Time.zip](https://github.com/RPCS3/rpcs3/files/9813948/Ratchet.Clank.Crack.in.Time.zip)

### System configuration

Win 11 22H2 (latest)
Ryzen 5 3600 3.6Ghz
16 GB Ram
Radeon RX 6600 (22.8.2) 

### Other details

this is my first post if i need to add or change anything, please let me know where i can improve. thank you.

**Comment by MSuih** [comment]
This is a well-known issue with AMD drivers. Try to disable anti-aliasing from GPU settings.

**Comment by Darkhost1999** [comment]
Looks like they know the issue goes away with AA off as stated in their issue.
Yet it is an issue that AA doesn't work on AMD GPUs. Do we have an open ticket for that or is there a reason we don't if we don't?

**Comment by PodcasterMike** [comment]
> This is a well-known issue with AMD drivers. Try to disable anti-aliasing from GPU settings.

I can do that but everything looks like its trying to run on a SNES. I can't even tell IF its still got the rectangles with everything looking like that. So my choices are invasive rectangles or everything is animated with Legos?

**Comment by PodcasterMike** [comment]
So i just changed GPU Settings to Write Color Buffers, Strict Rendering Mode, VSync, and Async Texture Streaming (just randomly clicking, and now it loaded looking like it was yesterday! ONCE. then i save stated, and loaded that state and back to rectangle soup with frame drops. ARGH. so it might be nothing i touch matters and it just DECIDES on random loads to work or not. This is annoying. I havent encountered that on the few other games i played but the one time it looked this bad was another Ratchet and Clank Game, Quest for Booty. and it also just started working randomly.

**Comment by Darkhost1999** [comment]
Can you upload a log following these instructions
https://wiki.rpcs3.net/index.php?title=Help:Save_State#How_To_Report_Issues_Related_To_Save_State
For savestate issues

**Comment by Darkhost1999** [comment]
Sounds like when you load normal state the config loaded fine.
But when you loaded savestate your settings didn't apply or something. /shrug

**Comment by PodcasterMike** [comment]
> Can you upload a log following these instructions https://wiki.rpcs3.net/index.php?title=Help:Save_State#How_To_Report_Issues_Related_To_Save_State For savestate issues

it happens even on regular loading as well. so i am quite sure save states aren't the issue. but if i do have save state issues in the future i will gladly follow those instructions, but thank you anyway :)  

So it is a known issue thats being worked on, and i can just wait with other games that don't require AA in the first place. or just enjoy the lego machinima. well i certainly appreciate the quick answers from everyone. and theres a bit of comfort in knowing theres nothing i can do on my end... i will have to just put this game on hold in my rotation and check in randomly.  hopefully if this issue gets fixed i will get a heads up somewhere. much thanks.

**Comment by PodcasterMike** [comment]
OK well trying it without AA also have some black boxes that appear when i use a weapon that creates a pulsing wave (think like a sonic burst). however its too fast for me to get a screenshot. this is like a picture frame surrounding the centre of the screen when i fire it, rather than a single large black box covering everything. So i guess its having trouble texturing the sound wave the weapon generates.  so just settling for pixelation is not gonna work. ugh this game plays so well, and seems so fun.  why does it need to look awful.

**Comment by kd-11** [comment]
This has nothing to do with AA
Enable "Read color buffers" from the advanced tab. This is also stated in the wiki as a requirement for correct visuals in this game.

**Comment by PodcasterMike** [comment]
> 

I did that already. I was just hoping to circumvent the issue that checking AA causes. but it seems that isn't currently possible.

**Comment by kd-11** [comment]
I'm still confused where AA comes in to play. I have 20+ hours in this game on a 6700XT and I've not observed any AA-related corruption. AA corruption on RDNA2 manifests as glitchy horizontal lines persistent in screenspace, I'm not sure if this is what you're referring to. It certainly does not appear as rectangles on-screen, that is just surface cache noise when RCB is off.
I've been trying to reproduce the other RDNA2 AA bug for over a year at this point without success.

**Comment by PodcasterMike** [comment]
i provided a screenshot, in a zip file as the website requested, to show what i mean. but the way you describe it seems also accurate. see this is the real kicker. it's not ALL the time. some days i cant get it to NOT do it and its just unplayable. but other days i can load it a bunch of times and it seems fixed.

**Comment by MSuih** [comment]
You can upload png files to github and they'll be shown in comments directly.

Like so:
![Ratchet Clank Crack in Time](https://user-images.githubusercontent.com/19759300/196588326-459dbe6e-3443-4c28-b003-6f503225150e.png)

**Comment by AniLeo** [comment]
Please retest and update this issue with AMD drivers 23.2.1 or newer as recently there have been changes that positively impact RPCS3.

**Comment by PodcasterMike** [comment]
> Please retest and update this issue with AMD drivers 23.2.1 or newer as recently there have been changes that positively impact RPCS3.

i did, and its works great now!. that update did the trick. save states are touch and go with crashing half the time and NOT saving, but this matter of the lines is solved and i can finally finish this trilogy! thanks for the heads up. I haven't touched this app in months cause i was annoyed at this problem. now i can dig in and explore space with my handy wrench!

**Comment by r4r4rrr** [comment]
This is happening again with amd drivers 25.9.1 and 25.9.2
