### ISSUE TITLE
[Regression] Last of us freezes when opening up game

### ISSUE THREAD

**Issue by guy224444** [RPCS3/rpcs3#12859]
### Quick summary

When opening up the last of us with the most recent rpcs3 update, the game freezes at a white screen.

### Details

Game freezes at a white screen after loading is done

### Build with regression

v0.0.24-14293-bd9c876e

### Attach two log files

regression- [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9842043/RPCS3.log)
working- [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9842048/RPCS3.log)

### System configuration

AMD Ryzen 7 4800H Processor, 16GB DDR4, 512GB SSD, NVIDIA GTX 1660Ti, Windows 10

### Other details

I used all the recommended settings and game patches for the regression and working build.

**Comment by Darkhost1999** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9842148/RPCS3.log.gz)
Works on my machine.
And your game looks pirated

**Comment by solarmystic** [comment]
Second, works just fine here too on the latest master as of this post (0.0.24-14305). Log definitely looks suspect. 
![image](https://user-images.githubusercontent.com/4345150/197316632-bb17e4d4-70e4-4626-892c-a12fdfeabe7a.png)
Tested on a 12400F/2080TI rig on 522.25 drivers with Windows 10 21H1.

**Comment by MSuih** [comment]
You're trying to force the game into a resolution that it does not support and thus it crashes after not being able to find a valid video configuration.

In future, ask in discord for help.
