### ISSUE TITLE
[Regression] TTY log making new lines unnecessarily

### ISSUE THREAD

**Issue by ARandomGuy231** [RPCS3/rpcs3#12854]
### Quick summary

TTY log no longer prints correctly in Persona 5.

### Details

While playing Persona 5, I use a patch that makes the game print file access in the TTY log. I've never had any issues with this across any of the builds before this. The TTY log should not be printing so many gaps in the text like it is now. The TTY log file also doesn't show the issue, it only happens in the emulator log window. The game still plays completely normally, I have also tried this with and without the 60FPS patch and the issue still occurs. Not sure if this is specific to the game. I don't think it's a coincidence that the build that broke it had TTY changes (according to the PR)

Broken TTY:
![Screenshot: Broken TTY](https://user-images.githubusercontent.com/30189033/197174656-df342d29-4eb2-4e9a-be1d-aec8737ecd90.png)

Good TTY:
![Screenshot: Good TTY](https://user-images.githubusercontent.com/30189033/197178286-ff76d4db-1577-4341-ac0d-eb3913edfdd1.png)

### Build with regression

v0.0.24-14282-00340f33

### Attach two log files

[Good TTY](https://github.com/RPCS3/rpcs3/files/9836224/TTY.log)
[Broken TTY Log](https://github.com/RPCS3/rpcs3/files/9836132/TTY.log)

### System configuration

Windows 10
i7-4790
RTX 2060
32GB DDR3

**Comment by MSuih** [comment]
Maybe fixed by https://github.com/RPCS3/rpcs3/pull/12855
