### ISSUE TITLE
problem updating submodules

### ISSUE THREAD

**Issue by latot** [RPCS3/rpcs3#1287]
Hi all, well here a little problem, when i run:

git submodule update

i get this message:

```
fatal: reference is not a tree: 8dd84dc1ea8bc70da1a345109383f62974a9c2fc
Unable to checkout '8dd84dc1ea8bc70da1a345109383f62974a9c2fc' in submodule path 'ffmpeg'
```

D: Thx.

**Comment by Zangetsu38** [comment]
Test this before : git submodule sync

**Comment by latot** [comment]
Hi, thx for the answer, for some reazon then git show this thing:

https://gist.github.com/latot/56f70f4faddbd2301ed3

its like all the files are untracked !! D: well the solution was

git submodule sync
git submodule update --force

Thx.
