### ISSUE TITLE
Savestates of Dark Souls (BLES01765) are unusable

### ISSUE THREAD

**Issue by GitArUs** [RPCS3/rpcs3#12871]
### Quick summary

When booting the game with savestate, emulation freezes before anything is rendered, printing the following message in log:

E 0:00:13.749916 {PPU[0x1000016] SLSession} SYS: 'cellSaveDataAutoSave2' failed with 0x8002b404 (error 1) [1]

### Details

Tried with deafult config (+WCB) and with various random options, result is always the same.

### Attach a log file

[RPCS3-BLES01765.zip](https://github.com/RPCS3/rpcs3/files/9846037/RPCS3-BLES01765.zip)

**Comment by GitArUs** [comment]
Attaching log from normal boot for comparision. I see diferences in another line:

with savestate:
W 0:00:13.749901 {PPU[0x1000016] SLSession} cellSaveData: cellSaveDataAutoSave2(version=2516972288, dirName=«NULL», errDialog=807618484, setBuf=*0x0, funcStat=*0x33d57940, funcFile=*0x1b976c8, container=0x1840078, userdata=*0x19b1b40)

normal boot:
W 0:00:20.070992 {PPU[0x1000016] Thread (SLSession) [HLE:0x01be493c, LR:0x010c8330]} cellSaveData: cellSaveDataAutoLoad2(version=0, dirName=“BLES01396DRAKS005”, errDialog=0, setBuf=*0x36363050, funcStat=*0x19cb748, funcFile=*0x19cb730, container=0xffffffff, userdata=*0x36362ff0)

[RPCS3-BLES01765-normal-boot.zip](https://github.com/RPCS3/rpcs3/files/9846090/RPCS3-BLES01765-normal-boot.zip)

**Comment by GitArUs** [comment]
Just attaching log from normal boot for comparision if needed.
[RPCS3-BLES01765-normal-boot.zip](https://github.com/RPCS3/rpcs3/files/9846103/RPCS3-BLES01765-normal-boot.zip)

**Comment by elad335** [comment]
Unleashing a can of worms, this is about HLE savestates being unimplemented.

**Comment by GitArUs** [comment]
Ouch.
Then put in at the end of savestates development queue. For the time being I will have to play without cheating ;)
