### ISSUE TITLE
Fatal Error in Uncharted 3

### ISSUE THREAD

**Issue by Cositachester** [RPCS3/rpcs3#12884]
### Quick summary

Uncharted 3 won't open, crashes on startup

### Details

![Error](https://user-images.githubusercontent.com/93743479/198064455-7d69d416-613d-455b-9150-6dc88a3eec87.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9870859/RPCS3.log)

### System configuration

CPU: Intel i7 4770k
GPU: RTX 3060Ti

**Comment by YuriNator557** [comment]
Bad settings, reset to defaults and only use the settings from the wiki page

**Comment by readywer** [comment]
With that weak cpu expect sub 30fps in that game.

**Comment by solarmystic** [comment]
Game launches fine with the correct settings on the latest master. 

![image](https://user-images.githubusercontent.com/4345150/198234308-7c775f3a-119e-4da1-ba1e-bb704a61e7f0.png)

The rpcs3 github isn't for tech support, please forward such requests to our rpcs3 discord help channel in the future.

![image](https://user-images.githubusercontent.com/4345150/198234547-d0e32c41-befc-47e2-9544-b952af6e68c1.png)

**Comment by MSuih** [comment]
Use discord for help and support
