### ISSUE TITLE
Implement decryption, for when you don't have a klicensee

### ISSUE THREAD

**Issue by tambry** [RPCS3/rpcs3#1288]
This problem refers to this line, which's condition check will always be true: https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Crypto/unself.cpp#L893

Here is a conversation from IRC referring to a modified version of that line and why the bogus check was added.

> Oct 23 17:39:04 <hykem>   "(memcmp(klicensee_key, key_v.GetKlicenseeKey(), 0x10) != 0"
> Oct 23 17:39:08 <hykem> Yeahhh, that's wrong
> Oct 23 17:39:17 <hykem> I remember why I left that bogus check though
> Oct 23 17:39:41 <hykem> Due to the fact that I wanted to implement the other decryption method, for when you don't have a klicensee
> Oct 23 17:41:43 <Nekoteki>  what better to do with it?
> Oct 23 17:42:20 <Nekoteki>  I could try to implement it since I want to get rid of wx dep there as well
> Oct 23 17:46:01 <hykem> Well, you can either leave it as it is (giving the warning) or properly implement the check.
> Oct 23 17:46:52 <hykem> If you check the lines under, you can see that npdrm_key is overwritten
> Oct 23 17:47:06 <hykem> This is because I've only implemented the RAP method
> Oct 23 17:47:21 <hykem> E.g.: You supply a RAP file and the key is directly extracted from it
> Oct 23 17:47:31 <hykem> The other method is the ACT.DAT one
> Oct 23 17:48:40 <Nekoteki>  method defined by .license value?
> Oct 23 17:49:58 <hykem> In sum, if the license type is 1 (network) we throw an error (can't implement this, ever); if it's 2, we go look for a RAP file (the other solution is to use the klicensee directly); if it's 3, we just use the predefined NP_KLIC_FREE, which is the same for any application.
> Oct 23 17:50:19 <hykem> The problem is that some games try to set the klicensee themselves
> Oct 23 17:50:50 <hykem> This is why I left that check there and added the functions GetKlicenseeKey and SetKlicenseeKey (which aren't really being used)
> Oct 23 17:51:10 <hykem> Of course, comparing an array to NULL is nothing
> Oct 23 17:51:20 <hykem> It was just so I wouldn't forget what I had to do
> Oct 23 17:52:09 <hykem> The proper case would be to compare both arrays (memcmp is fine, but it should be EQUAL to 0, not different)
> Oct 23 17:52:37 <hykem> The npdrm_key would be overwritten IF klicensee_key contents are not empty
> Oct 23 17:52:54 <hykem> But since GetKlicenseeKey is not working yet, klicensee_key is always empty
> Oct 23 17:53:26 <hykem> Checking with memcmp(xxx) == 0 would work since both are equally empty
> Oct 23 17:53:33 <hykem> But it will always still be TRUE
> Oct 23 17:53:45 <Nekoteki>  klicensee is passed through HLE functions?
> Oct 23 17:53:54 <hykem> This will only change if something calls SetKlicenseeKey
> Oct 23 17:53:57 <hykem> I believe so
> Oct 23 17:56:48 <hykem> https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/SysCalls/Modules/sceNp.cpp
> Oct 23 17:56:53 <hykem> npDrmIsAvailable
> Oct 23 17:57:12 <hykem> You can see that we're passing a RAP file AND k_licensee
> Oct 23 17:57:28 <hykem> This shouldn't be necessary, but I never had the time to test this accross games
> Oct 23 17:57:56 <hykem> The correct behavior would be to let the game set the k_licensee and see if it's still able to decrypt
> Oct 23 17:58:15 <hykem> If not, then we must investigate what makes the game choose between a RAP license and it's own k_licensee
> Oct 23 17:58:29 <hykem> (Most likely, if a license file is present, it has priority)
> Oct 23 17:58:59 <hykem> Note that this is for EDAT, not SELF
> Oct 23 17:59:07 <hykem> It's unclear the role of k_licensee in SELF files
> Oct 23 17:59:23 <Nekoteki>  what about SDAT?
> Oct 23 17:59:28 \*   Yllodra has quit (Quit: Leaving)
> Oct 23 18:01:56 <hykem> https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Crypto/unedat.cpp
> Oct 23 18:01:59 <hykem> Check line 644
> Oct 23 18:02:34 <hykem> The function extract_data recieves the klicensee (named devklic here)
> Oct 23 18:02:45 <hykem> If it's SDAT, it's never used
> Oct 23 18:03:02 <hykem> The key is just a XOR with a hash and a fixed key
> Oct 23 18:03:24 <hykem> Only for EDAT with license type 3 this happens:
> Oct 23 18:03:25 <hykem> if ((NPD->license & 0x3) == 0x3)           // Type 3: Use supplied devklic.
> Oct 23 18:03:25 <hykem>             memcpy(key, devklic, 0x10);
> Oct 23 18:04:02 <hykem> It's still necessary to investigate what happens with SELF files
> Oct 23 18:04:34 <hykem> SCETOOL does this as well, allows you to specify a klicensee and attempts to decrypt using it
> Oct 23 18:05:03 <hykem> If it turns out to be useless, we can safely remove such feature from SELF decryption

**Comment by AniLeo** [comment]
Was this solved?

**Comment by twdarkeh** [comment]
According to #2720 yes.
