### ISSUE TITLE
[BLUS30847][v1.03][DISC] Metal Gear Solid HD Collection - Stuck in Building PPU Cache

### ISSUE THREAD

**Issue by phuongkirito** [RPCS3/rpcs3#12888]
### Quick summary

Metal Gear Solid HD Collection is stuck in Building SPU Cache part

### Details

When I start using RPCS3 for the first time, I boot the game and it's stuck in the building SPU Cache part, and I can't play the game. By the way, I use OpenGL instead of Vulkan because I don't have Vulkan in the options.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9875534/RPCS3.log)

### System configuration

CPU: Intel Pentium G3240
GPU: Intel HD Graphics

**Comment by RainbowCookie32** [comment]
Your system is below minimum requirements. Your log is empty, but you are probably failing to compile shaders, you'd need a GPU that meets minimum requirements to get past that. But with that CPU you are not really getting anywhere on RPCS3 anyways.

**Comment by phuongkirito** [comment]
So, I can't play any game with my CPU?

**Comment by RainbowCookie32** [comment]
Assuming you got a GPU to get past your current error, you technically could play games on your cpu, but they wouldn't run anywhere near well.

**Comment by phuongkirito** [comment]
So what games I can play with my current system config?

**Comment by RainbowCookie32** [comment]
None. This is not the place for discussion or tech support anyways, go to our forums or discord server for that
