### ISSUE TITLE
Jak face and hair "grainy" in Jak 2

### ISSUE THREAD

**Issue by NineKain** [RPCS3/rpcs3#12885]
### Quick summary

Jak face and hair look weird, other npcs look fine to me, happens on cutscenes and normal gameplay although less noticeable
![image](https://user-images.githubusercontent.com/72826232/198078178-30b12da5-b904-4983-93b9-3915c0cfc3a0.png)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9871314/RPCS3.log.gz)

### Attach capture files for visual issues

[BCUS98281_20221026181148_capture.zip](https://github.com/RPCS3/rpcs3/files/9871326/BCUS98281_20221026181148_capture.zip)

### System configuration

R5 5600x, 16gb ram, 3060ti (522.25 drivers), win 10

**Comment by Darkhost1999** [comment]
Does this occur without using any hacks?
Aka can you test again with resolution scale at 100%. Make sure you're running settings as close to default as possible.

This looks like an issue with upscaling.

**Comment by tylerjm917** [comment]
Setting the anisotropic filter to "Auto" under Configuration > GPU removed this effect for me and solves the issue. This also works at 200% upscaling (2k)

**Comment by MSuih** [comment]
Anisotropic filtering is an enhancement and is known to cause issues in some games. I guess we can add this one to the list.

Closing as this doesn't seem to be an issue with proper settings
