### ISSUE TITLE
Skylanders Trap Team emulated portal problem.

### ISSUE THREAD

**Issue by XDgameplay133** [RPCS3/rpcs3#12887]
### Quick summary

Skylanders Trap Team emulated portal is not working correctly when using traps.

### Details

When playing Skylanders Trap Team, There appears to be an issue when using traps. When you use traps in the emulated portal, you get stuck in an infinite loop of the portal reloading everything that is on the emulated portal.  This includes: Skylander(s), Trap, Magic items, Adventure Levels. This obviously prevents the player from using one of the game's intended features, Using villains! I haven't noticed any patterns during this bug whatsoever. I suspect it may be a coding problem with the emulated portal itself since using Skylander(s) during regular gameplay works perfectly fine. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9874350/RPCS3.log)

### System configuration

CPU: Ryzen 9 5950X
GPU: NVIDIA GeForce RTX 3070 Ti
GPU Driver version: 517.48

**Comment by blan44** [comment]
I'm also having that issue when playing Trap Team

**Comment by D1rk95** [comment]
I suspect that the problem comes because the sound that traps makes comes normally in the real life but with an emulated portal it can't be possible so it makes it lagging.

**Comment by D1rk95** [comment]
can someone fix this problem pls

**Comment by Ashuraman666** [comment]
Same here though for me it's not a constant thing. Sometimes I can play the villains a little bit but then the reload happens, then I can play some more. There isn't an accurate timing between reloads it's always random. Also when capturing a villain some work normally despite the loading being longer but most don't. Placing the villain in the trap at the academy always works but the reload issues still happen

**Comment by vico-back** [comment]
has anyone find a solution to this problem ?

**Comment by MSuih** [comment]
How about testing the pull request just above your message?

[See these instructions on how to test it](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_download_builds_from_a_pull_request_on_GitHub?)

**Comment by vico-back** [comment]
i didn't know how to test somone pull request thanks for putting th link how to do it

**Comment by vico-back** [comment]
i tested it and still bug and do the same than before

**Comment by Ashuraman666** [comment]
After doing some testing, here's what's happening now:
A)The game no longer constantly switches between Skylander and trapped villain. I was able to play as the villain I had trapped for the entirety of it's duration and there wasn't a constant switching
B)Capturing on the other hand is still tricky. I tested this with several villains and what happens is, after the cutscene of the villain being captured, the game no longer recognizes any trap or any skylander(It will constantly show a screen telling you to load back the skylander you had when you trapped the villain) for a while then it will load back into the game but the trap will not have the villain in it, as if you had never captured it in the first place.

**Comment by vico-back** [comment]
is the exact same for me

**Comment by vico-back** [comment]
so anyone find how to patch this ? pls

**Comment by Ashuraman666** [comment]
Build 0.0.27-14837 which is the latest master build of the emulator once again has the reset issue

**Comment by deReeperJosh** [comment]
Anyone available to test the PR linked above? Issues should be fixed now :)

**Comment by Ashuraman666** [comment]
> Anyone available to test the PR linked above? Issues should be fixed now :)

Do you mean the one you posted like 3 weeks ago? If so I tested it and it doesn't fully fix the issues. As I mentioned in a previous comment:
"A)The game no longer constantly reloads the items in the emulated portal. I was able to play as the villain I had trapped for the entirety of it's duration and there wasn't a constant reloading
B)Capturing on the other hand is still tricky. I tested this with several villains and what happens is, after the cutscene of the villain being captured, the game no longer recognizes any trap or any skylander(It will constantly show a screen telling you to load back the skylander you had when you trapped the villain) for a while then it will load back into the game but the trap will not have the villain in it, as if you had never captured it in the first place."
Was your fix never integrated in the main build? Because the current main build still has the bug

**Comment by deReeperJosh** [comment]
> > Anyone available to test the PR linked above? Issues should be fixed now :)
> 
> 
> 
> Do you mean the one you posted like 3 weeks ago? 

Yeah but I just updated it with some changes that should have it working now

**Comment by Ashuraman666** [comment]
> > > Anyone available to test the PR linked above? Issues should be fixed now :)
> > 
> > 
> > Do you mean the one you posted like 3 weeks ago?
> 
> Yeah but I just updated it with some changes that should have it working now

Ah then I'l test it asap

**Comment by Healthpotion133** [comment]
So it seems this issue has been resolved, but I do not know how to download this file, where to find it, and where to put the file. is there anyone who can explain to me what I need to do with this, to make my portal of power work?

or has this already been implemented into the emulator?
