### ISSUE TITLE
Motorstorm Pacific Rift Split Screen

### ISSUE THREAD

**Issue by Daniel4692** [RPCS3/rpcs3#12890]
### Quick summary

When trying to play splitscreen of Motorstorm Pacific Rift, the game freezes on loading screen and I have to quit RPCS3.
It worked before, then I closed RPCS3 and when I wanted to play it again it freezed everytime I want to play splitscreen.
It only happens when trying to play split screen.

### Attach a log file

https://easyupload.io/jxwbr1

### System configuration

Intel Core I7 8700
Nvidia Gigabyte RTX 2060 Super
16GB Ram
Windows 10

**Comment by Asinin3** [comment]
Closing, split screen works.
