### ISSUE TITLE
Bulletstorm visual artifcats

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#12899]
### Quick summary

The damage effect when you are hit with electricity causes graphical issues

### Details

Rpsc3

https://user-images.githubusercontent.com/71127352/198848613-d20b44fb-cb73-4eac-86a0-1bfa25e2e9ee.mp4

Hardware
https://youtu.be/gdMxq_g08hE?t=299

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/9894416/RPCS3.zip)

### Attach capture files for visual issues

https://www.dropbox.com/s/o6f32991zdecvt5/NPUB90501_20221029201527_capture.zip?dl=0

### System configuration

    SYS: RPCS3 v0.0.24-14339-c8620070 Alpha | master
    SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
    SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
    SYS: Current Time: 2022-10-28T21:53:46
    RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 526.47.0.0
    SYS: Firmware version: 4.89

**Comment by Linear524** [comment]
This issue is not the"mipmap issue". It is just broken MLAA shader function.

**Comment by Triticum0** [comment]
This is fixed when using Strict Rendering Mode
