### ISSUE TITLE
WolfSSL Error

### ISSUE THREAD

**Issue by AliviaSunner** [RPCS3/rpcs3#12896]
### Quick summary

I can't create an RPCN account, I don't know what could be causing this problem on my end

### Details

it dosen't send a token i've checked my emails

### Attach a log file

RPCS3 v0.0.24-14339-c8620070 Alpha | master
AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.93 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
Qt version: Compiled against Qt 5.15.2 | Run-time uses Qt 5.15.2
Current Time: 2022-10-29T05:22:31
Thread time: 0.000000s (0.001562Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.005039 SYS: Initialization times before main(): 0.103464Gc
·! 0:00:00.005048 SYS: argc: 1, argv: 'D:\Games\RPCS3\rpcs3.exe'
·! 0:00:00.014528 UUID: Installation ID: {bd2df5b4-6270-4d08-b28f-f103dd9ca7ce}
·A 0:00:02.912065 {Vulkan Device Enumeration Thread} RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1660' running on driver 522.25.0.0
·E 0:00:03.159689 SIG: Thread [Vulkan Device Enumeration Thread] is too sleepy. Waiting for it 247585.654µs already!
·E 0:00:03.404337 SIG: Thread [Vulkan Device Enumeration Thread] is too sleepy. Waiting for it 492235.104µs already!
·E 0:00:03.898200 SIG: Thread [Vulkan Device Enumeration Thread] is too sleepy. Waiting for it 986099.119µs already!
·! 0:00:04.399914 {Vulkan Device Enumeration Thread} SIG: Thread time: 0.171875s (0.599273Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:04.399964 CFG: Setting the default renderer to Vulkan. Default GPU: 'NVIDIA GeForce GTX 1660'
·! 0:00:04.399986 SYS: Setting user ID '00000001'
·! 0:00:04.403333 VFS: VFS config missing. Using default settings. Path: D:/Games/RPCS3/config/vfs.yml
·! 0:00:04.403401 SYS: Using VFS config:
$(EmulatorDir): ""
/dev_hdd0/: $(EmulatorDir)dev_hdd0/
/dev_hdd1/: $(EmulatorDir)dev_hdd1/
/dev_flash/: $(EmulatorDir)dev_flash/
/dev_flash2/: $(EmulatorDir)dev_flash2/
/dev_flash3/: $(EmulatorDir)dev_flash3/
/dev_bdvd/: $(EmulatorDir)dev_bdvd/
/app_home/: ""
/dev_usb***/:
  /dev_usb000:
    Path: $(EmulatorDir)dev_usb000/
    Serial: ""
    VID: ""
    PID: ""
·! 0:00:04.403417 VFS: Mounted path "/dev_hdd0" to "D:/Games/RPCS3/dev_hdd0//"
·! 0:00:04.403421 VFS: Mounted path "/dev_flash" to "D:/Games/RPCS3//dev_flash//"
·! 0:00:04.403423 VFS: Mounted path "/dev_flash2" to "D:/Games/RPCS3//dev_flash2//"
·! 0:00:04.403425 VFS: Mounted path "/dev_flash3" to "D:/Games/RPCS3//dev_flash3//"
·! 0:00:04.403427 VFS: Mounted path "/app_home" to "///"
·! 0:00:04.403430 VFS: Mounted path "/dev_usb000" to "D:/Games/RPCS3/dev_usb000//"
·! 0:00:04.403527 SYS: Applying global config: D:/Games/RPCS3//config.yml
·! 0:00:04.524174 SYS: Logged in as user '00000001' with the username 'User'
·! 0:00:04.524415 IPC: IPC config missing. Using default settings. Path: D:/Games/RPCS3/config/ipc.yml
·! 0:00:04.524433 SYS: Using IPC config:
IPC Server enabled: false
IPC Port: 28012
·A 0:00:04.524539 SYS: Firmware version: 4.89
·! 0:00:04.559399 GUI: Current language changed to English (en)
·! 0:00:04.688400 Compat: Finished reading database from file: D:/Games/RPCS3/GuiConfigs/compat_database.dat
·! 0:00:05.569661 NET: Starting download from URL: https://update.rpcs3.net/?api=v2&c=c8620070
·! 0:00:05.570600 SYS: New timer resolution: 499 us (old=999 us, min=15625 us, max=500 us)
·! 0:00:06.122052 NET: Download finished
·S 0:00:06.122101 UPDATER: RPCS3 is up to date!
·! 0:00:14.766022 rpcn: Loading RPCN config. Path: D:/Games/RPCS3/config/rpcn.yml
·W 0:00:14.766156 {TID: 14048} rpcn: connect: Attempting to connect
·! 0:00:15.118366 {TID: 14048} rpcn: connect: Connection successful
·! 0:00:15.118405 {TID: 14048} rpcn: Updated local address to 192.168.1.3
·E 0:00:15.123412 {TID: 14048} rpcn: connect: Handshake failed with RPCN Server: error state on socket
·! 0:00:18.192940 rpcn: Loading RPCN config. Path: D:/Games/RPCS3/config/rpcn.yml
·W 0:00:18.193053 {TID: 17168} rpcn: connect: Attempting to connect
·! 0:00:18.413130 {TID: 17168} rpcn: connect: Connection successful
·! 0:00:18.413150 {TID: 17168} rpcn: Updated local address to 192.168.1.3
·E 0:00:18.418176 {TID: 17168} rpcn: connect: Handshake failed with RPCN Server: error state on socket
·! 0:00:19.638845 rpcn: Loading RPCN config. Path: D:/Games/RPCS3/config/rpcn.yml
·W 0:00:19.638960 {TID: 1148} rpcn: connect: Attempting to connect
·! 0:00:19.853306 {TID: 1148} rpcn: connect: Connection successful
·! 0:00:19.853336 {TID: 1148} rpcn: Updated local address to 192.168.1.3
·E 0:00:19.858231 {TID: 1148} rpcn: connect: Handshake failed with RPCN Server: error state on socket

### Attach capture files for visual issues

![image](https://user-images.githubusercontent.com/57814711/198821832-c7687959-8c4c-4f7c-8fbc-1edfca7ef4da.png)

**Comment by RipleyTom** [comment]
This only happens to a few windows users.
I suspect this is linked to either some account rights/antivirus software/firewall software.

**Comment by necobrn** [comment]
There's any workaround to this? On linux works fine but on windows keeps giving me the same error

**Comment by AliviaSunner** [comment]
> 

Sadly no, also works fine for me in linux but in windows no luck
I guess best option is fresh installing windows
