### ISSUE TITLE
Native OSK doesn't accept non-letter inputs from real keyboard, works with controller

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#12897]
### Quick summary

When Keyboard Handler is set to Basic, games that use the keyboard and make RPCS3's native keyboard display appear don't accept inputs that aren't letters, numbers, or the spacebar.

### Details

When Keyboard Handler is set to Basic, games that use the keyboard and make RPCS3's native keyboard display appear don't accept inputs that aren't letters, numbers, or the spacebar, such as punctuation (commas, periods, colons) and symbols (plus, minus, backslash), but using a controller, you can select these characters and they input fine.  This seems to be an issue across all games that use an on-screen keyboard.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9893289/RPCS3.log.gz)

### System configuration

OS: Windows 10 Pro x64 build 19043
CPU: Intel Core i9-10900K
GPU: NVIDIA RTX 2080 SUPER
RAM: 64 GB DDR4

### Other details

In this example, I use Skate 3 with Keyboard Handler set to Basic.  When the OSK appears, I press every key on each row of my keyboard, then do the same with Shift held.  Only letters and numbers are accepted.  I then show I'm able to input these using the controller just fine:

https://user-images.githubusercontent.com/58268914/198822614-eb06616a-698e-414e-9b5f-7b1799b0d196.mp4

**Comment by Megamouse** [comment]
it only accepts letters that are presently visible in osk

**Comment by Megamouse** [comment]
please test

**Comment by SlyCooperReloadCoded** [comment]
If it only accepts characters currently on-screen, then comma, apostraphe, question mark, and period should work, but they don't.

**Comment by SlyCooperReloadCoded** [comment]
Nope, still does not work.

**Comment by Megamouse** [comment]
it's caused by the cellKb logic which currently only allows for certain input.
I'll add a fallback once I'm home to allow keytext passthrough which should fix most of these issues.

**Comment by Megamouse** [comment]
It should work now.
But specific keys may still not work properly depending on the game.
Also remember to choose the proper keyboard language in the settings dialog I/O tab
.

**Comment by Megamouse** [comment]
Hmm. I fixed some of the issues.
But the bug you're probably referring to is a bit different.
The reason why it doesn't work is because you are most likely in a different language panel.
You can toggle the panels with L2 and R2.
It's most likely on the english panel and you're on some other keyboard language

**Comment by Megamouse** [comment]
Well. it should be more intuitive now and this issue should be fixed.
It will now register many more keypresses and I also added functionality for delete and arrow keys.

Just keep in mind that most of it depends on the keyboard language in the system settings, as well as the current panel in the osk dialog.
What I mean by that is **not** the current character set, which you can switch with the buttons at the bottom left of the dialog, but the actual OSK panel (english panel vs german panel etc.) which you can change **very intuitively** by using L2 and R2.
