### ISSUE TITLE
Army of TWO™: The 40th Day Demo [NPUB90353] is not playable with SPU LLVM or ASMJIT

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#12903]
### Quick summary

Army of TWO™: The 40th Day Demo can't go in-game with LLVM or ASMJIT, as it gets stuck in loading after the intro sequence.

If I use an SPU interpreter (dynamic), the game goes in-game.

### Attach a log file

[RPCS3Interpreter .log](https://github.com/RPCS3/rpcs3/files/9894947/RPCS3.log)
[RPCS3LLVM.zip](https://github.com/RPCS3/rpcs3/files/9894951/RPCS3.zip)

### System configuration

RPCS3 v0.0.24-14339-c8620070 Alpha | master | FW 4.88 | Windows 10 21H2
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (526.47)

**Comment by benderscruffy** [comment]
RPCS3 Version: 0.0.25-14495-8ac99680 Alpha | master
this goes ingame now with SPU LLVM

**Comment by Triticum0** [comment]
@benderscruffy did you retest the demo?

**Comment by benderscruffy** [comment]
yes

**Comment by Triticum0** [comment]
@benderscruffy Yeah, I tested the Europe ver and seem to work fine so I think the .pkg file has some issue when it was dumped

by the by do you get either of these two screens when booting the demo?
![NPUB90353_screenshot_2023_01_14_23_45_00](https://user-images.githubusercontent.com/71127352/212502045-25dc5647-7104-4bfd-8e3d-f2e22798c8ef.png)
![NPUB90353_screenshot_2023_01_14_23_45_19](https://user-images.githubusercontent.com/71127352/212502046-0a41890f-635e-4ed3-965e-b00b3d17e1f6.png)

Once you reply back i close the issue

**Comment by benderscruffy** [comment]
![NPUB90353_screenshot_2023_01_15_12_58_30](https://user-images.githubusercontent.com/2696404/212523804-1e3e0f49-2af0-49ea-b735-dba22d0ff842.png)
![NPUB90353_screenshot_2023_01_15_13_01_46](https://user-images.githubusercontent.com/2696404/212523805-f4f6bd01-9dfe-4709-b8a2-1099f42ce62a.png)
the spinning coin i only get on the loading screen 
yours screen is black with the spinning coin

**Comment by Triticum0** [comment]
@benderscruffy Thank you. If you could create a post on the thread on the forum saying the game is playable that word is greatly appreciated https://forums.rpcs3.net/thread-204971.html. Also If you got time could you test Mercenaries 2: World in Flames Demo? I have been having issues getting it to boot a may also have to do with the dump. Thanks for the help! https://github.com/RPCS3/rpcs3/issues/13274
