### ISSUE TITLE
Prince of Persia [NPUB30424] Problems with scripts

### ISSUE THREAD

**Issue by Nenormatica** [RPCS3/rpcs3#12910]
### Quick summary

When it's time to clear the area and I stand in a circle and press "Y". The stripping video starts and it doesn't end. It looks like an endless loop.

I tried different settings and also another version of the game - BLES00390.

The problem remains.

I recorded a video with my settings and a moment in the game where there is a problem.

Can this be fixed?

### Details

https://www.dropbox.com/s/ut02v1cgcfshnp7/prince_lite.mp4?dl=0

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9901714/RPCS3.log.gz)

### Attach capture files for visual issues

https://www.dropbox.com/s/7ab7jwm3p6n26sx/NPUB30424_20221031171436_capture.zip?dl=0

### System configuration

 SYS: RPCS3 v0.0.24-14352-a1b4ffcf Alpha | master
- SYS: Genuine Intel(R) CPU 0000 @ 2.60GHz | 16 Threads | 15.93 GiB RAM | TSC: 2.592GHz | AVX+ | FMA3 | TSX-FA disabled by default
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2022-10-31T16:33:04
- RSX: Found vulkan-compatible GPU: 'Radeon RX 580 Series' running on driver 2.0.233
- SYS: Firmware version: 4.89

**Comment by eydeeee** [comment]
The game is from the QTE era, you're supposed to spam the button, not just press it. Can you confirm you're spamming the button until it's supposed to take control, and it's ignoring all but one button presses?

**Comment by Nenormatica** [comment]
You're right. I rarely play and just forgot. And there were no prompts on the screen. thank you.
