### ISSUE TITLE
[Feature request] Controller Overlay

### ISSUE THREAD

**Issue by JamesIsWack** [RPCS3/rpcs3#12918]
### Quick summary

Hello,
I would like to have a controller overlay for RPCS3, mostly for Guitar Hero controllers. This is mainly for when I want to stream, or to show people im actually playing in discord calls. 
Thanks,
James

### Details

a semi-transparent overlay for multiple supported controllers, including:
Guitar Hero Guitars
XBOX Controllers
PS3/4/5 Controllers

**Comment by Megamouse** [comment]
So you expect us to show an overlay for every single controller in the world. At least that's what it would end up being

**Comment by Megamouse** [comment]
Why not just film your controller and add it as a picture in picture?

**Comment by Darkhost1999** [comment]
Isn't there 3rd party software designed explicitly for this task and streamers?

**Comment by JamesIsWack** [comment]
@Darkhost1999 I do not know of this software, please send a link. And I was implying JUST supported controllers, not every controller in the world
@Megamouse same to you, I simply want a controller overlay. I do not have a camera.

**Comment by Darkhost1999** [comment]
https://gamepadviewer.com/#
You can add this as a scene for obs. Tutorials are very easy to find. Issues include browser can't be minimized at any time in order for it to remain fully functional. But this can work until if and when a controller overlay is implemented. Best people you can ask for better software's are streamers. So ask twitch or twitch discord groups as well

**Comment by JamesIsWack** [comment]
> https://gamepadviewer.com/# You can add this as a scene for obs. Tutorials are very easy to find. Issues include browser can't be minimized at any time in order for it to remain fully functional. But this can work until if and when a controller overlay is implemented. Best people you can ask for better software's are streamers. So ask twitch or twitch discord groups as well

Sadly this doesnt work. I asked Acai (GH streamer) for a program and found one.
Thanks for the help anyway,
James

**Comment by Darkhost1999** [comment]
This is still a good request if there's interest from a contributor or Dev to implement natively into RPCS3
