### ISSUE TITLE
NCAA Football 14 (BLUS31159) Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)

### ISSUE THREAD

**Issue by Blaze49** [RPCS3/rpcs3#12916]
### Quick summary

Game has run successfully on 0.0.21-12432 (4/12/22) at 300% resolution scale so until last week with crash listed. No settings were changed in the emulator config (other than 300% res of course, but that was changed in April) I stuck with that build as it proved to be running flawlessly. I'm attempting to run in OpenGL as well and had the same crash. 

I attempted using the most current version (0.0.25-14358-a00f9e42 Alpha | master and was met with the same crash. 

### Attach a log file

[RPCS3 Crash.txt](https://github.com/RPCS3/rpcs3/files/9922675/RPCS3.Crash.txt)

### System configuration

RPCS3 v0.0.24-14339-c8620070 Alpha | master Windows 10
Intel i9-12900KF | 24 Threads | 63.82 GiB Ram | TSC: 3.187GHz | AVX+ | FMA3
NVIDIA GeForce RTX 3090 (526.47.0.0)

### Other details

No new hardware

**Comment by solarmystic** [comment]
This is a problem with NVIDIA's latest 526,47 drivers, downgrade back to 522.25 and it will be fixed.

**Comment by Blaze49** [comment]
@solarmystic Installed 522.25 and back in action. Thank you for your kind and informative response, have a wonderful rest of your day!

**Comment by solarmystic** [comment]
Adding Fight Night Champion, Tales of Xillia 1 and 2 to this list as well for future reference.
