### ISSUE TITLE
Graphical issue in mass effect 1

### ISSUE THREAD

**Issue by Zulthar** [RPCS3/rpcs3#12922]
### Quick summary

Parts of the graphic look like a deep fried meme

### Details

Game was like that on startup, unclear what caused it.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9944428/RPCS3.log)

### Attach capture files for visual issues

[BLUS31139_20221105105701_capture.zip](https://github.com/RPCS3/rpcs3/files/9944435/BLUS31139_20221105105701_capture.zip)

### Other details

your selection for the capture doesn't take .7z files, if the capture doesn't work turn it back into a .7z file, as I just changed the extension to make the site accept it

**Comment by Satan86** [comment]
Your RSX capture only shows the developer's name at the start of the game, but it's probably the same issue as #8440.

**Comment by kd-11** [comment]
Closing as duplicate.
