### ISSUE TITLE
Invalid file or folder, path error - Chainsaw Lollipop 

### ISSUE THREAD

**Issue by PONTANYAK** [RPCS3/rpcs3#12939]
### Quick summary

This games has been working correctly before. but suddenly this message appears, I been tryng so many things but nothing could make it work...
![imagen_2022-11-11_044848448](https://user-images.githubusercontent.com/117898208/201291645-3fd7d857-149d-4acb-876c-c8e362d7202f.png)

E SYS: Invalid or unsupported file format: D:/PS3_GAME/USRDIR/EBOOT.BIN
E GUI: Boot failed: reason: Invalid file or folder, path: D:/PS3_GAME

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9988007/RPCS3.log)

**Comment by MSuih** [comment]
Ask for help in our Discord, not on github issues
