### ISSUE TITLE
[GUI] Windows UI focus Bug

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12931]
On Window focus any theme is correctly applied
![Focus](https://user-images.githubusercontent.com/60384196/200868725-2d06996f-e49a-4de2-8a2b-6b448c82fe7d.png)
On Window loss of focus we can see Font color is reverted to default for anything selected in a list. This occurs in settings firmware tree, manage savedata, manage trophies, list view, manage users, etc
![unfocus](https://user-images.githubusercontent.com/60384196/200868730-9a0b24f3-7d3f-4905-b65a-305ca19986f4.png)
As You can see here the focus theme I have set is as shown
![MyFocus](https://user-images.githubusercontent.com/60384196/200868758-15144cc8-da9c-4f07-93be-be6c3ae1957d.png)
The highlight remains applied for my theme but the Font color reverts to default and that makes it so as the text is black on black and illegible.
![MyUnfocus](https://user-images.githubusercontent.com/60384196/200868741-131dcd16-193c-4902-adbb-d232b2085dd7.png)
This has been tested not to occur on Linux for Ani. https://github.com/RPCS3/rpcs3/pull/11585#issuecomment-1221336283
 As well as I also booted Ubuntu up to check and validate on my machine this is not a Linux bug and I doubt Mac has this issue too.
This isn't a priority. But it is an annoyance and would like to see the font color I set to remain applied even on focus loss.

**Comment by Darkhost1999** [comment]
I don't want to get spammy and share every single theme being broken.
![185754905-b047e86a-fb0e-4f34-ba88-a1816e1ae826.png](https://user-images.githubusercontent.com/60384196/200896658-debdc432-9385-4bd3-b05b-6f44a51cdaf5.png)

**Comment by Darkhost1999** [comment]
They all revert the font color back to Black default and I think focus loss shouldn't lose any of the custom theme

**Comment by AniLeo** [comment]
The QSS :focus repaint with the white text is only happening when the QT element is in focus.
If the window is not in focus, the QT element isn't as well.
