### ISSUE TITLE
F {PPU[0x1000000] Thread (main_thread) [0x00913084]} VM: Access violation reading location 0x0 (unmapped memory)

### ISSUE THREAD

**Issue by PONTANYAK** [RPCS3/rpcs3#12935]
### Quick summary

I just downloaded the lastest rpcs3 version and now I been having this crash-error lately and I can't play anything now 

 :( I cant even enter to the game

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9978842/RPCS3.log) 

### Other details

https://user-images.githubusercontent.com/117898208/201040409-1da991f3-d120-4a92-89c6-cbe5cc26281c.mp4

**Comment by YuriNator557** [comment]
Log suggests broken game files
