### ISSUE TITLE
LOST PLANET: Extreme Condition title screen corruption 

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#12947]
### Quick summary

This game title screen option seems to render incorrectly when pressing start and then returning to the main menu.

### Details

rpcs3(First boot):
![NPUB90082_screenshot_2022_11_12_15_10_56](https://user-images.githubusercontent.com/71127352/201482663-9f5ead51-d995-4542-8857-58239d82f725.png)
rpcs3(Returning to title screen):
![NPUB90082_screenshot_2022_11_12_15_10_09](https://user-images.githubusercontent.com/71127352/201482667-7b9129a4-56f8-4306-a810-e0753ff0f7a9.png)
PS3:
https://youtu.be/us-t4tBrfaM?t=1

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9995335/RPCS3.log.gz)

### Attach capture files for visual issues

[NPUB90082_20221112171231_capture.zip](https://github.com/RPCS3/rpcs3/files/9995728/NPUB90082_20221112171231_capture.zip)

### System configuration

    SYS: RPCS3 v0.0.24-14339-c8620070 Alpha | master
    SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
    SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
    SYS: Current Time: 2022-10-28T21:53:46
    RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 526.47.0.0
    SYS: Firmware version: 4.89

### Other details

Note: The capture file seems to be rendering the visuals correctly. though this game gives a sys error on the emulator which is the most probable cause of the issue
E SYS: 'sys_rsx_context_attribute' failed with 0x80010002 : CELL_EINVAL [1]
E SYS: 'sys_rsx_context_attribute' failed with 0x80010002 : CELL_EINVAL [2]

**Comment by AniLeo** [comment]
Log file says "Battlefield 3 Open Beta" for game title, also, NVIDIA driver 526.47 is being used, which is a broken version known to cause memory corruption. Downgrade to before 526 and try again.

**Comment by Triticum0** [comment]
@AniLeo If you turn on write depth buffers, it seem to fix the issue. you can close the issue if you think that fix is a sufficient solution for you.
