### ISSUE TITLE
Tales of Graces F BLES01617

### ISSUE THREAD

**Issue by hyper92** [RPCS3/rpcs3#12949]
### Quick summary

The game worked 16 days ago.. but even with an old build it does not seem to run without freeze anymore. Around 5 minutes into the game it freezes even if you do nothing but standing around. But I can confirm it runs flawless on Steam Deck without crash...

Running on current nvidia driver 526.86, the one before also does not change anything. I already deleted all caches and even configured a completely fresh rpcs3 installation. Also did a update of the x570 chipset. No change. 
Game is crashing after a few minutes with:

S SPU: New block compiled successfully x40
F {RSX [0x0fea8e8]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\image.cpp:134[:4], in function create_impl)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error)

I am running config setting from wiki. PS3 native framerate and 4k resolution scaling. Tried already to disable vsync and to change audio output between xaudio and cubed.

Also attached a log, well it ran around 15 minutes in the background now after freezing. . in frozen state it seems

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/9997692/RPCS3.zip)

### System configuration

Windows 10 22H2 (might have changed, Seems like the last time I played on thje PC it was still 21H2)
Ryzen 5900x
RTX2080
32GB RAM

**Comment by YuriNator557** [comment]
This is known about and is a problem with the new NVIDIA drivers, 522.25 does not have this issue

**Comment by hyper92** [comment]
Ok thank you. Seems to be the case... It seems to work with 522.25.. so it was propably the driver update I did for Star Ocean two weeks ago :)
