### ISSUE TITLE
MMJoystick does not have vibration even if the driver the device supports it

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#12948]
### Quick summary

Using a generic gamepad with vibration support. However, its not working.

### Details

Driver: Speedlink Strike Gamepad
Gamepad device: Generic/Unknown Brand

**Comment by Megamouse** [comment]
There is no vibration in mmjoy

**Comment by jobs-git** [comment]
Start XOutput, configure controller and start driver, the xinput dpad should appear in settings

**Comment by MDAshcreator** [comment]
Mmjoystick is not working on rpcs3 emulator please help
