### ISSUE TITLE
settings for each game

### ISSUE THREAD

**Issue by Zulthar** [RPCS3/rpcs3#12941]
### Quick summary

Being able to save settings presets within the config menu

### Details

Within the UI being able to save config settings, this would cut down on menu usage for games someone has already found the best options for without having to write them down elsewhere, as well as less stable games that have very strict requirements that clash with most other games for what makes them run best.

**Comment by Darkhost1999** [comment]
You mean like right click your game -> create/change custom configuration?

**Comment by Megamouse** [comment]
What they mean is probably something like the database.
But yes. You can already save settings on a per game basis

**Comment by Darkhost1999** [comment]
There is this issue if they want to subscribe to it
<https://github.com/RPCS3/rpcs3/issues/4434>
