### ISSUE TITLE
Improve and implement more cellSpurs* functions

### ISSUE THREAD

**Issue by tambry** [RPCS3/rpcs3#1294]
cellSpurs is a library used by many games for managing SPU threads. Most games that use SPURS wont run without it being implemented or will lack the audio.

**Status:**
Currently the cellSpurs kernel is disabled [here](https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/SysCalls/Modules/cellSpursSpu.cpp#L531).

**Games:**
It is required by many games for audio. (ie. ARKEDO! Swap 02, FEZ, Dead Space Ignition, many more)
It is also used by tons of bigger games to manage their SPU threads. (ie. GTA V, **insert almost any AAA game here**)

**Comment by tambry** [comment]
Are we ever going to even bother implementing cellSpurs*? Since LLE is now the way to go for most stuff, it would seem.

**Comment by MoochMcGee** [comment]
Why is SPURS disabled?

**Comment by danilaml** [comment]
@tambry it sure would be a lot better if some code messiah came and implemented it HLE xD
@MoochMcGee HLE inplementations is too buggy and innacurate so it's disabled for now ( you can LLE modules if you got the libs.

**Comment by raven02** [comment]
I think we can close it at this moment and we mostly use the cellSpurs_jq LLE modules

**Comment by danilaml** [comment]
@raven02 why close? It's still an issue - there is still no working HLE for cellSpurs.

**Comment by orbea** [comment]
I also do not understand why this was closed. Games that were associated with this issues (Tales of Vesperia) still do not work. Should those issues be re-opened instead?
