### ISSUE TITLE
[Regression] 1942: Joint Strike Does'nt boot after the first run

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#12959]
### Quick summary

This game on the second boot makes a file called NPHB00043 making the game crash with an unmapped memory error

### Details

Seem to get stuck on F {PPU[0x1000000] Thread (main_thread) [0x00054cc8]} VM: Access violation reading location 0x414 (unmapped memory) on the first run it makes it in-game on another attempt it just hangs at the first frame.
The game seems to create a game date folder called NPHB00043 only on build after https://github.com/RPCS3/rpcs3/pull/8893 Which causes the game to crash, removing the folder allows the game to boot.

### Build with regression

v0.0.12-11068-27643cb7

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10026518/RPCS3.log)

### System configuration

RPCS3 v0.0.24-14339-c8620070 Alpha | master | FW 4.88 | Windows 10 21H2
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (526.47)

### Other details

v0.0.12-11055-f0fd7e2e also had an issue and mentioned NPHB00043 in the log so not sure it related

**Comment by Risusama** [comment]
On a side note, your RPCS3 installation seems to be located in a OneDrive folder (C:/Users/arthu/OneDrive/Desktop/Rpcs3).
I suggest moving it to another location, since things tend to break if it's in a OneDrive folder.

**Comment by Risusama** [comment]
And you are not using the latest build. Could you test on the latest build?
(Not that I see any commits touching cellGame code though, but just to be safe.)

I was not able to reproduce this at all, not on latest nor the build you're using, though I have the Europe version "NPEB00026".

**Comment by Triticum0** [comment]
my pkg was corrupted =( fix the issue
