### ISSUE TITLE
Madden NFL 10 and 11 Vulkan shader bug

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#12951]
### Quick summary

when loading onto the main menu with async shader mode the menus seem to have artefacts on the screen

### Details

when testing madden NFL 10 +11 demo I encountered so server artefact in the main menu of both the game which could be fixed by using a shader interpreter only or switching to Opengl.
Rpsc3 (madden NFL 10)
![NPUB90282_screenshot_2022_11_13_20_52_39](https://user-images.githubusercontent.com/71127352/201546863-a844237b-858d-494c-9c63-f2a74ca65ac6.png)

Rpsc3 (madden NFL 11)
![NPUB90387_screenshot_2022_11_13_21_17_13](https://user-images.githubusercontent.com/71127352/201546858-9e741bd3-abff-4e72-b21a-18807d4a116a.png)
Rpsc3 with Shader Interpreter only (madden NFL 10)
![NPUB90282_screenshot_2022_11_13_22_08_04](https://user-images.githubusercontent.com/71127352/201546985-ac84a1d9-5e84-4752-bef2-c6f10a6cae6b.png)
Rpsc3 with Shader Interpreter only (madden NFL 11)
![NPUB90387_screenshot_2022_11_13_22_06_30](https://user-images.githubusercontent.com/71127352/201546933-f4ce07d0-8395-4b85-bf07-8be9484ea41a.png)
Ps3 (madden NFL 10)
https://youtu.be/94b8wHDJQVg?t=105
Ps3 (madden NFL 11)
https://youtu.be/s4QBRh8hiyo?t=181

### Attach a log file

[RPCS3(1).log.gz](https://github.com/RPCS3/rpcs3/files/9998314/RPCS3.1.log.gz)
[RPCS3(Madden NFL 11).log.gz](https://github.com/RPCS3/rpcs3/files/9998327/RPCS3.Madden.NFL.11.log.gz)

### Attach capture files for visual issues

[NPUB90282_20221113205452_capture.zip](https://github.com/RPCS3/rpcs3/files/9998317/NPUB90282_20221113205452_capture.zip)
[NPUB90387_20221113221347_capture.zip](https://github.com/RPCS3/rpcs3/files/9998318/NPUB90387_20221113221347_capture.zip)

### System configuration

SYS: RPCS3 v0.0.24-14339-c8620070 Alpha | master
SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
SYS: Current Time: 2022-10-28T21:53:46
RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 526.47.0.0
SYS: Firmware version: 4.89

### Other details
Only seems to affect Vulkan, OpenGL does not seem to exhibit the same issue

**Comment by kd-11** [comment]
Verify what happens if the shader compiler is set to "legacy".

**Comment by Triticum0** [comment]
I does nothing already test before i did the report

**Comment by Triticum0** [comment]
Rpsc3 with legacy shader mode (madden NFL 11)
![NPUB90387_screenshot_2022_11_13_22_49_02](https://user-images.githubusercontent.com/71127352/201548632-0783242b-38ad-45a3-a942-fc59c8eb6047.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9998392/RPCS3.log.gz)
[NPUB90387_20221113224911_capture.zip](https://github.com/RPCS3/rpcs3/files/9998394/NPUB90387_20221113224911_capture.zip)

**Comment by Triticum0** [comment]
Nivida drivers are Scuffed or there some wrong with my graphic card

**Comment by AniLeo** [comment]
> 526.47

Known bad NVIDIA drivers. Downgrade to before 526 and try again.

**Comment by ChwaraeTeg** [comment]
Seems to be similar to the issue with Madden 12 reported in #12514

As with that issue, it seems to be a regression between v0.0.21-13393 and v0.0.21-13399):

![0 0 21-13393 _ Madden NFL 10 Demo  NPUB90282](https://user-images.githubusercontent.com/104720038/204093416-21fb52fa-4990-4383-a8f4-97c93ced954e.png)
![0 0 21-13399 _ Madden NFL 10 Demo  NPUB90282](https://user-images.githubusercontent.com/104720038/204093418-bf639789-62be-4bc0-914e-dc53106a921f.png)

**Comment by Triticum0** [comment]
closing dupe of  #12514 and #12968 tested madden 12 it affects all 3 of the games
