### ISSUE TITLE
[Regression] Trinity: Souls of Zill Ơll Invisible floor. 

### ISSUE THREAD

**Issue by VittoScaletta** [RPCS3/rpcs3#12956]
### Quick summary

The floor gets invisible on the newest builds. 

### Details

After the first area of the game, when you teleport to the part 2, the glitch starts.

### Build with regression

0.0.25-14374-3f842fc

### Attach two log files

Build that works [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10021951/RPCS3.log.gz)
Regression [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10021953/RPCS3.log.gz)

### Attach capture files for visual issues
https://mega.nz/file/r8JTgbQT#AiKm7UezdbvBzhzMWL84Qi3m-lWgtS4JDuEzF8H4H6w

### System configuration

12th Gen Intel(R) Core(TM) i5-12400 2.50 GHz | GTX 1660 Ti 1-Click OC 6GB, GDDR6 1080p

**Comment by AniLeo** [comment]
Interval between said builds is over 2000 (!) commits. You need to provide a log from the last good build and the first bad build. One of the log files is empty, for the other log file that is not empty, completely random settings are being used. 

Regression report is invalid, read the regression report guidelines when making a regression report.
