### ISSUE TITLE
RPCS3 Not launching

### ISSUE THREAD

**Issue by DhruvXIX** [RPCS3/rpcs3#12966]
### Quick summary

RPCS3 does not launch after a certain update.

### Details

A while ago I updated RPCS3 to the latest version at the time and I didn't open the emulator to play games for a bit and recently decided to play but RPCS3 did not launch. It doesn't provide an error message nor is it running on task manager. I tried to download the latest version and an older version to see if it would work and the result was the same where rpcs3.exe did not launch.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10049595/RPCS3.log)

### System configuration

AMD Ryzen 5 4600H
NVIDIA GTX 1650 Ti
GeForce Driver Version : 526.98

**Comment by AniLeo** [comment]
Nothing is logged in the log that can give any hints so we can't do anything with that, the "certain version" is not specified, this is a support request and not an issue report as it's working fine for other people
