### ISSUE TITLE
Transform Program's output and shader program's input doesn't always correctly map (SH3)

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1296]
I found why in SH3 HD there is neither shadow nor light, sometimes it looks like the data between transform and shader stage doesn't properly map.

For instance the shader program responsible of static geometry reads a "tc9" input while the corresponding transform program doesn't write to tc9. Instead, it writes to dst_reg6 (mapped to clip distance data) in a non traditionnal way, and if I manually change the shader program to read dst_reg6 instead of tc9 (which maps to tc16...) I have correct light and shadow. However there are still glitches if I mimic this behavior for all shader program, it looks like tc9 is not always mapped to the same reg.

On the other hand there is the NV4097_SET_VERTEX_ATTRIB_OUTPUT_MASK  command that we don't use, that might perhaps have the info but I don't know how.

**Comment by vlj** [comment]
Actually it's maybe not an issue with varying but rather in fragment shader decompilation, although I have no idea what is wrong.

**Comment by tambry** [comment]
@vlj Is this still an issue, or did you only fix it partly?

**Comment by vlj** [comment]
The visual issue (missing shadows in SH3 HD) is here but the diagnostic was apparently wrong.
I'm waiting for DH's new shader recompiler to see if it fixes the issue.

**Comment by raven02** [comment]
I'm closing this since has been years ago and no update.
