### ISSUE TITLE
playing NBA 2K11, and trying to upload custom PS3 draft classes found from Operation Sports. However, every time I go to load them, I get this as the game crashes every single time: “The ps3 application likely crashed, you can close it.” anybody know a fix for this?

### ISSUE THREAD

**Issue by JublesPlays** [RPCS3/rpcs3#12964]
### Quick summary

the game itself runs perfectly, yet when trying to import custom draft classes in, it freezes and crashes, spouting the error: “The PS3 application has likely crashed, you can close it”

### Attach a log file

https://www.dropbox.com/scl/fo/mx8l40wmhlu4zslvdyara/h?dl=0&rlkey=fgh57m5w21cdupki1iei4hwu4

### Attach capture files for visual issues

https://user-images.githubusercontent.com/118648574/202886093-5a22a31a-8df6-4036-b433-383985e7b284.MOV

### System configuration

Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz   3.00 GHz (8 cores)

32.0 GB Installed RAM (31.9 GB usable)

NVIDIA Geforce 1660 TI

x64-based PC

**Comment by AniLeo** [comment]
Issue happening when loading save data made for a PS3 console, it needs to be decrypted as any PS3 save data coming from a real console, not an emulator issue, closing
