### ISSUE TITLE
Incorrect emulation of parts of the skylanders portal

### ISSUE THREAD

**Issue by mandar1jn** [RPCS3/rpcs3#12965]
Hello. Over the past half a year, I have been doing a deep dive into the Skylanders portal. While doing this, I encountered this emulator with its Skylanders emulation feature. I don't own any ps3 games, so do with this report what you want. From what I can see, all the important emulated features are present and these mistakes are only cosmetic for the most part.

These mistakes are all found in the `usb_device_skylander::control_transfer` function. 

For the J command, your description is `Sync status from game?`. From my research, I have concluded that this command can control the lights on separate sides of the portal with a fade in effect although I'm not yet sure how the last 2 bytes influence the fade. I just know they do. My research on this command can be found [in my blog post](https://marijnkneppers.dev/posts/dissecting-the-skylanders-portal-part3/#the-command).

For the L command, the description is `Audio Download status?`. I honestly can't blame you for this one since this command is only ever used while playing portal audio. Until today, I thought it was related too. Today, I found out that it probably stands for Light. It controls the LED in the trap slot. For example, `{J, 0x01, 0xFF, 0xFF, 0xFF}` turns the LED on indefinitely as long as the trap is placed in the slot. When it's removed, the LED turns off until the trap is placed inside again.

For the S command, you simply added a question mark as a description. From what I can gather, this is just an explicit way for the game to ask for a status signal.

The V command is one I know is sent by the game on startup but I have no idea what it does yet.

My research is far from finished but I just wanted to alert you to the issues. As I said, feel free to do whatever you want with this information. I just wanted to let you guys know. If you want to read up on my research, it can be found [on my website](https://marijnkneppers.dev/posts/)

**Comment by Megamouse** [comment]
Since these commands seem to be abbreviations, I'd assume that 'V' returns a version, which is a common thing to query when initializing something.

**Comment by RipleyTom** [comment]
As interesting as it may be, most of those have no actual impact on emulation, not really an issue with emulator.
