### ISSUE TITLE
Slowdown in Sonic & Sega All Stars Racing

### ISSUE THREAD

**Issue by greeneyo** [RPCS3/rpcs3#12967]
### Quick summary

Game tends to run at 90%, the audio is suffering quite a bit. (see attached video at Other Details)
I have tried every possible fix and settings seen on YT but it's just not playable, at least for me.

### Details

Emulator version : latest -> 0.025-14358
Game ID : BLES00750 with update 01.01
Audio buffering is enabled at default value 100ms | Time stretching also enabled at 75%

Driver wake up delay set at 120us, RSX FIFO Accuracy set to Atomic
The 2 settings just above were set after a fatal error occured at the start of a race.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10049754/RPCS3.log.gz)

### System configuration

OS : Windows 11 version 22H2
CPU : Ryzen 5 3600 6 Cores
GPU : RTX 2060 Super
Driver version : 526.98
RAM installed : 32GB

### Other details

Video preview : (I compressed it but you can hear that the audio is suffering)

https://user-images.githubusercontent.com/80707855/202905151-b0567a76-2254-45cd-b20c-b4bdd7ae423b.mp4

**Comment by AniLeo** [comment]
Pirated game being used, issue closed as Invalid.
