### ISSUE TITLE
[Regression] NCAA 14 keeps crashing

### ISSUE THREAD

**Issue by ethanp772** [RPCS3/rpcs3#12979]
### Quick summary

I have accumulated around 12 hours with only crashing because my drivers were not updated. I was playing earlier today for a few hours and then when i got back on tonight i could only go into the recruiting menu in my dynasty and then when i go to leave it the game crashes

### Details

Game crashes whenever i try to leave the recruiting menu

### Build with regression

v0.0.25-14389-661be41c

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10088526/RPCS3.log.gz)    regression

cannot find working file 

### System configuration

geforce rtx 3070
12th gen intel i7-12700F
driver version 526.98

**Comment by AniLeo** [comment]
Invalid regression report as it doesn't include last good version and first broken version, known bad nvidia drivers version, log shows broken save data backup, not a regression report but a support request, closing as invalid
