### ISSUE TITLE
Inconsistency with Relaxed Zcull

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12972]
### Quick summary

I have  found that there are a handful of games that have some compatibility issues or performance issues when using Relaxed Zcull. In my quest to find a regression I actually discovered that the results are inconclusive all after the same time period as 13833 (bump to 23) But not caused by that build.
I wish I knew how to explain or better provide more details for a specific issues so I've listed my regression test results down below. It's not an exhaustive list as I didn't know I had to keep record but that is after I started keeping track.

### Details

The behavior is anywhere from games just not working at all with relaxed zcull and crashing. Or will run at 1-2 fps where they used to perform at about 20-30 fps with the same settings.
Relaxed zcull is not required for the following game to work at all and was never the preferred way to play Assassin's Creed games. But it illustrates the point really well being a "Zcull intense" game relying on zcull for just about everything in the entire game world.
I made this a bug report instead of a regression report because the regression results were inconclusive with same builds not working and same builds working. If there is any information I can provide. lmk

### Attach a log file

[A working log.gz](https://github.com/RPCS3/rpcs3/files/10057613/RPCS3.log.gz)
[A broken log.gz](https://github.com/RPCS3/rpcs3/files/10057627/RPCS3.log.gz)

### Show the issue

![Works](https://user-images.githubusercontent.com/60384196/203089087-ea00fe40-2c26-46a0-9c26-6f7e80c653ac.png)
![Broke](https://user-images.githubusercontent.com/60384196/203089107-9aa26970-1e76-4b60-93f6-eaa54bfdf9f9.png)

### System configuration

AMD Ryzen 5 3600
NVIDIA GeForce GTX 1660 SUPER driver 522.25.0.0
Windows 11 Beta

### Other details

I tried to regression test but the results were inconclusive
0.0.23-13987 is working.
0.0.23-13987 is not working.
0.0.23-13988 is working.
0.0.23-13988 is not working.
0.0.23-14005 is working.
0.0.23-14013 is working.
0.0.23-14013 is not working.
0.0.24-14105 is not working.
0.0.24-14105 is working.
0.0.25-14385 is not working. x5 and just doesn't return a working state.

**Comment by kd-11** [comment]
This is a known issue with some games. They will never work properly with relaxed zcull and that's why it is not the default.
Basically this comes down to the game engine - if the engine "peeks" at the timestamps, it will break if we use relaxed ZCULL. You can minimize this by getting a really fast GPU (e.g RTX 3090 or better) to minimize round-trip time, but the incompatibility will always be there.
