### ISSUE TITLE
[Regression] WCB causes inconsistent frametimes for MGS4 (#12746)

### ISSUE THREAD

**Issue by lucasmarotta** [RPCS3/rpcs3#12971]
### Quick summary

Since build 0.0.24-14217 (PR [#12746](https://github.com/RPCS3/rpcs3/pull/12746)) the frametimes are quite erratic when using the WCB (Write Color Buffers) resulting in worse performance when playing Metal Gear Solid 4 (BLUS30109 v2.00).

### Details

Since build 0.0.24-14217 (PR [#12746](https://github.com/RPCS3/rpcs3/pull/12746)) the frametimes are quite erratic when using the WCB (Write Color Buffers) resulting in worse performance when playing Metal Gear Solid 4 (BLUS30109 v2.00). I did tried the latest build (v0.0.25-14385) but shows the same behavior like in the screenshots below:

![RPCS3 MGS4 Build  0 0 24-14211 InGame OSD](https://user-images.githubusercontent.com/37968565/203013634-986c29ef-1f6f-4a3b-bd5d-c6832cd649a0.png)
_Build 0.0.24-14211 in game OSD_

![RPCS3 MGS4 Build  0 0 24-14211 RTSS OSD](https://user-images.githubusercontent.com/37968565/203014373-f88377d1-35cb-4960-b677-457d54326772.png)
_Build 0.0.24-14211 RTSS OSD_

![RPCS3 MGS4 Build 0 0 24-14217 InGame OSD](https://user-images.githubusercontent.com/37968565/203014510-2c7ced37-5672-43e0-9f26-b33649597513.png)
_Build 0.0.24-14217 in game OSD - Notice the frametimes_

![RPCS3 MGS4 Build 0 0 24-14217 RTSS OSD](https://user-images.githubusercontent.com/37968565/203014665-620ba9c2-f0cc-4f4d-9b9e-7ebfc1953551.png)
_Build 0.0.24-14217 RTSS OSD - Notice the frametimes_

Both have WCB on, but when I disabled the frametimes go back to normal. This issue is **mostly noticeable on the first level of the game**. The second one not so much but still does shows inferior performance. Both builds are using the exactly same configuration.

### Some settings:
- Firmware version 4.88
- Enable SPU Loop detection
- SPU Block Size: Mega
- ZCULL Accuracy: Relaxed
- Antialiased Disabled
- Write Color Buffers
- RSX Fifo Accuracy: Atomic
- Driver Wakeup Delay: 160ms

### Build with regression

v0.0.24-14217-73784b9e

### Attach two log files

[RPCS3 v0.0.24-14211.log](https://github.com/RPCS3/rpcs3/files/10055692/RPCS3.v0.0.24-14211.log) (Good one)
[RPCS3 v0.0.24-14217.log](https://github.com/RPCS3/rpcs3/files/10055695/RPCS3.v0.0.24-14217.log) (Bad one)

### System configuration

- OS: Windows 11 22H2 (22621.819)
- CPU: Ryzen 9 5900X
- GPU: Nvidia RTX 3070
- Nvidia Driver: 526.61

**Comment by Linear524** [comment]
I don't have any speed issues with MGS4 and latest builds... And I use Precise ZCull mode.
Also WCB+RCB and WDB+RDB (for proper MLAA and DoF effects)
The only issue MGS4 have now - is just odd polygon Z- offset on far distance, but KD-11 is aware about this.
My rig is:
- SYS: RPCS3 v0.0.25-14385-b639f3c8 Alpha | master
- SYS: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz | 14 Threads | 31.83 GiB RAM | TSC: 2.594GHz | AVX+ | FMA3 | TSX Forced
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2022-11-22T20:08:22
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1080' running on driver 512.59.0.0
- SYS: Firmware version: 4.87

P.S. - Win11 sucks, it is slower for all my emulation stuff (RPCS3, Ryujinx, Cemu). about 5~10% speed loss compared to win10 1909
P.P.S. - MGS4 on RPCS3 needs a lot of CPU cores (not threads).

**Comment by kd-11** [comment]
This issue can be improved trivially, so I'll move it to active backlog for now.

**Comment by kd-11** [comment]
@lucasmarotta Check if https://github.com/RPCS3/rpcs3/pull/13077 changes things.

**Comment by lucasmarotta** [comment]
@kd-11 First thanks guys for the dedication to this project, and this issue seems quite tricky. Well I made a quick test with 0.0.25-14488 and the update substantially improved the frametimes. There's still some instability in some spots, but I would say that it seems better than the previous good one, v0.0.24-14211. Good work! I can bring more tests later.
