### ISSUE TITLE
RPCS3 Freezing and not compiling PPU Modules

### ISSUE THREAD

**Issue by XDynaMit3** [RPCS3/rpcs3#12978]
### Quick summary

I tried to play several games on RPCS3 and none of them worked. I noticed that in every version of the emulator, when I try to install firmware, first it says "Successfully installed PS3 firmware and LLE Modules", then when I click OK, it just freezes. I left it for about 2 hours like this and it's doesn't even start compiling ppu modules. Same thing happens with games, when I click Play it freezes and never starts to compile ppu modules, meanwhile I see people doing it flawlessly. Do you guys have any idea on what I have to do? 

I've installed Microsoft Visual C++ 2019 Redistributable, and in one attempt I noticed that it said "PPU: PPU Cache location not initialized.", but that was with the version 0.19 (Log of the try:)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10086444/RPCS3.log)

### Build with regression

rpcs3-v0.0.25-14388-8be4ac68_win64

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10086434/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10086452/RPCS3.log)

### System configuration

Ryzen 5 5600
3060 Ti - Driver: 526.98
Gigabyte Aorus Elite b550
Windows 11
HDD 2tb Seagate
SSD 1tb m2 Crucial

**Comment by YuriNator557** [comment]
Something is interfering with RPCS3, likely a faulty Vulkan layer or Chromium
Go to the Discord server for support

**Comment by EdHerdman** [comment]
Sorry to butt in but I wonder if it's related to RPCS3 crashing on PPU compilation?
#12621

**Comment by Megamouse** [comment]
Please try again

**Comment by EdHerdman** [comment]
I think it's all good now.
