### ISSUE TITLE
D3D12 big performance regression in dice test

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1297]
Since https://github.com/RPCS3/rpcs3/commit/e76abf875f60585f622c0ff6ded239625d6b8f5a by @vlj  (found by git bisect, not sure how reliable) my fps in dice elf test took a hit. It totally destroys my iGPU (intel HD4600) performance (60 -> 3 fps) and my dGPU(r9 290) takes a noticeable hit (37 -> 27 fps).

**Comment by vlj** [comment]
I think it should be fixed on d3d12-wip branch, there was a small typo (!= instead of ==) thanks for pointing the commit !

**Comment by danilaml** [comment]
@vlj while I get better fps (close to before) I have artifacts (black shadows) with this branch and with my iGPU it crashes on `ThrowIfFailed(m_swap_chain->Present(rpcs3::state.config.rsx.vsync.value() ? 1 : 0, 0));` here: https://github.com/vlj/rpcs3/blob/d3d12-wip/rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp#L549

**Comment by danilaml** [comment]
Now I have same artifacts with current master (60dc4abc2bdadfb4c57a553efdb1e06d3809fc23)
![image](https://cloud.githubusercontent.com/assets/2046350/11182493/52a2003e-8c7c-11e5-85ef-1d57edfd4361.png)

**Comment by danilaml** [comment]
bad commit (found via git bisect) is : e9d9bad6439fd208a908797ce9725d04749fab02

**Comment by vlj** [comment]
hmm weird

**Comment by vlj** [comment]
with Intel gpu ?

**Comment by danilaml** [comment]
@vlj with amd. With intel it just crashes on `ThrowIfFailed(m_swap_chain->Present(rpcs3::state.config.rsx.vsync.value() ? 1 : 0, 0));` (see comment above) with access violation on nullptr.

**Comment by vlj** [comment]
with current master ???? I can't reproduce.
Does it do the same with d3d12 (not wip) branch ?

**Comment by danilaml** [comment]
Yes, with current master.

**Comment by danilaml** [comment]
Commenting out `rsx->reset();` fixes the issue so it's indeed the problem.

**Comment by danilaml** [comment]
WIth d3d-wip it just crashes on `case 2: current_group->entries[fmt::trim(name_value[0])]->string_value(fmt::trim(name_value[1])); break;` in config_context.cpp . Most likely it just needs rebase on top of master (with O1L changes)

**Comment by vlj** [comment]
Yes but commenting the line is breaking SH3 HD...

**Comment by danilaml** [comment]
@vlj I've found something you might be interested in: if I comment out `method_registers[NV4097_SET_SCISSOR_VERTICAL] = (4096 << 16) | 0;`
(and save it value before memzero to temp and restore) it works as before.
But If i have this line it crashes on intel.
Also It doesn't fix artifacts on radeon.

Btw, why it's ORed with 0 ?

**Comment by tambry** [comment]
@danilaml Make sure your Intel drivers are up-to-date. They are notorious for being bad.

**Comment by danilaml** [comment]
@vlj the problem is both on amd and intel (though on intel it just crashes) and wasn't occurring before this commit.

**Comment by vlj** [comment]
Which resolution do you use ? 

Resetting is used once per frame, the overhead isn't that big. What matters more is to know what exactly is resetted to which value.

**Comment by danilaml** [comment]
@vlj 720x480
(btw, If I try to enable debug output rpcs3 trigger a breakpoint, not sure it's expected behaviour)

**Comment by vlj** [comment]
with win 10586 you need to manually install "graphics tool" in Windows 10 features. It was included by default with 10240 but for some reasons it's missing when updating to the fall build.

**Comment by danilaml** [comment]
@vlj what do you mean? What graphic tool? Also, mu windows still hasn't updated to 586.

**Comment by danilaml** [comment]
@vlj any new ideas?

**Comment by vlj** [comment]
I'm trying to reproduce the issues but the sample works fine on my two machine, the one with radeon (and 15.11.1 drivers) and with Intel (HD 4600 with 15.40.10.64.4300 drivers).

Does it work with Microsoft Basic Render ? It should be the reference renderer.

**Comment by danilaml** [comment]
@vlj my intel drivers are `10.18.15.4279` (updated from the last time but through windows update so they are not the latest) and amd - `15.201.1151-150821a-188665E` (I believe it was the latest WHQL 15.8). Software render is fine. AMD:
![image](https://cloud.githubusercontent.com/assets/2046350/11259112/f7733cc8-8e6f-11e5-805a-80e7f7d3f535.png)

and with intel it just crashes on the line I posted before (with driver crash to apparently). And commenting those to SCISSOR reset fixes the problem for me. Is there something I can provide you with to help debug this?

**Comment by tambry** [comment]
@danilaml You can get new drivers [here](https://downloadcenter.intel.com/download/25484/Intel-Graphics-Driver-for-Windows-7-8-1-10-15-40-). Currently your Intel drivers are very old. Before reporting any problems with an Intel integrated graphics card, update your drivers, as their drivers are know for being quite bad compared to other vendors.

**Comment by danilaml** [comment]
Yep, faulty drivers. The problem is fixed (very strange one xD). Though perf on intel is still a little worse than before, but just a little. (And better than on amd since, If I understood correctly, there is no ram<->vram interop since there is no ram =) )
