### ISSUE TITLE
[Regression] Skipping shadows and water in Skyrim and possibly others

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#12987]
### Quick summary
Since experiencing this issue with Skyrim I have tried several combinations of settings and located the build that started it all.
I wish to give a special thanks to #12977 for allowing me to load my save file and escape from White Ridge Sanctum in order for me to test this by resolving a PPU VM access violation unmapped memory violation.

### Details
The issue is as shown where the regressing build has shadows and water skipping. Please inform me if the pictures aren't visible for whatever reason.
Issue not shown is that clouds, fog, dust, waterfalls are also effected.
Before and on 0.0.25-14380
![image](https://user-images.githubusercontent.com/60384196/204103748-a377982c-5285-4916-9628-724eddb508a1.png)

![image](https://user-images.githubusercontent.com/60384196/204103849-448c5763-91c4-49a8-ba5a-836b92b68b33.png)

After 0.0.25-14382 
![image](https://user-images.githubusercontent.com/60384196/204103573-e83738d2-17aa-4878-9dbe-4081c5d831c6.png)

![image](https://user-images.githubusercontent.com/60384196/204104007-176f54f8-0332-4647-9919-500ffc16e200.png)

### Build with regression

#12957

### Attach two log files

[Broke.log.gz](https://github.com/RPCS3/rpcs3/files/10096812/RPCS3.log.gz)
[Working.log.gz](https://github.com/RPCS3/rpcs3/files/10096821/RPCS3.log.gz)

### Attach capture files for visual issues

[BLUS31202_20221126122440_capture.zip](https://github.com/RPCS3/rpcs3/files/10096811/BLUS31202_20221126122440_capture.zip)

### System configuration

Ryzen 5 3600
GTX 1660 Super 522.25
Windows 11 beta insider

### Other details

Let me know if anything doesn't work or needs reuploaded. The rsx capture looked excessively bright but showcased the issue. The screenshots is more realistic to what I saw on screen.

https://user-images.githubusercontent.com/60384196/207897110-0adb1228-c74c-42fd-8b2c-4197630e355d.mp4

**Comment by Darkhost1999** [comment]
I'm noticing this regression only increased chances of encountering this issue not started this issue.
Testing further back the game stopped booting before finding an origin.
This is a still image not a video or a gif so it doesn't showcase the issue the same as before screenshots
![image](https://user-images.githubusercontent.com/60384196/204135126-c6a043ee-fd8d-44ec-a5f6-63c8dccd602e.png)
Red indicates areas experiencing this issue after  0.0.25-14382
Blue indicates areas experiencing this issue Before and on 0.0.25-14380

Steps to reproduce teleport to the Palace of Kings in Windhelm or hitch a carriage early in gameplay and then walk straight towards any direction generally towards the inn.

**Comment by EspeonScottie** [comment]
Here's the same issue occurring in Skylanders 1, it seems to be happening only in this level plus the one before it which both happen to have a lot of water.
![Capture](https://user-images.githubusercontent.com/77664800/205714625-0c06b3dd-995a-44de-bfad-5a943cb20f39.PNG)

### Log File

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10156927/RPCS3.log.gz)

### RSX Capture

[BLES01272_20221205132229_capture.zip](https://github.com/RPCS3/rpcs3/files/10156989/BLES01272_20221205132229_capture.zip)

### System Information

Intel Core i7-6700HQ
NVIDIA GeForce GTX 1060 (527.37)
Windows 10

**Comment by EspeonScottie** [comment]
So it seems the issue actually affects more than just those two levels, it also affects the Stonetown and Battlefield levels as well as portions of Creepy Citadel level. I decided to test #12960, which is the build right before #12957 and it stops occurring. So for Skylanders Spyro's Adventure at least, #12957 is the first build to cause this issue for this game. Wondering if maybe someone could a look into this and fix the rsx in the next build?

Stonetown in #12960 

![Stonetown (#12960)](https://user-images.githubusercontent.com/77664800/206876428-27ecbb94-1669-4a27-81a9-2eadcd51bb22.PNG)


Stonetown in #12957
 
![Stonetown (#12957)](https://user-images.githubusercontent.com/77664800/206876374-7209ad4a-aa0a-4808-849a-9e6be2760b26.PNG)


### Attach two log files
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10200996/RPCS3.log.gz) (#12960) 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10201011/RPCS3.log.gz) (#12957)


### Attach capture files for visual issues
[BLES01272_20221210162502_capture.zip](https://github.com/RPCS3/rpcs3/files/10200994/BLES01272_20221210162502_capture.zip) (#12960)
[BLES01272_20221210163852_capture.zip](https://github.com/RPCS3/rpcs3/files/10201009/BLES01272_20221210163852_capture.zip) (#12957)

### System Information
Intel Core i7-6700HQ
NVIDIA GeForce GTX 1060 (527.56)
Windows 10

**Comment by kd-11** [comment]
I forgot about this, it's a simple control flag issue.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/13097

**Comment by Darkhost1999** [comment]
Works fine with PR

**Comment by Darkhost1999** [comment]
Mostly
![Skyrim](https://user-images.githubusercontent.com/60384196/208509020-d40c271d-678a-4521-80b7-e04cfb950fd3.png)

**Comment by Darkhost1999** [comment]
An RSX capture is on the PR comment I didn't know until after hitting send that you had merged it that minute.
I'm pretty sure as you said it's a separate issue. It was also minor. I'll need to find more locations to test or a location I can actually travel to regularly.

**Comment by Darkhost1999** [comment]
Got around to confirming this is something else today
![Skyrim](https://user-images.githubusercontent.com/60384196/209448967-18bc2b5f-eed2-43b1-8434-fdc3a077ce4d.png)
I'll ignore unless I find it somewhere I can actually travel to. This place likely possibly was like this on the PS3.
