### ISSUE TITLE
[Feature request] Freeze Fix for NPUA80966 version of Ratchet & Clank ACiT

### ISSUE THREAD

**Issue by Gymyk** [RPCS3/rpcs3#12980]
### Quick summary

Basically the title. I can't really get the versions of the game that do have the patch, so I was wondering if a version of it could be made for this version of ACiT.

**Comment by MSuih** [comment]
Patches are not tracked on our issues as they are not part of the core emulator. You should join our Discord to talk about them.

As for the patch, it's maybe possible to port it over by just changing the PPU hash to match the one for your game copy.
