### ISSUE TITLE
Resistance: Fall Of Man - Crashing at the beginning of "Path of Least Resistance" mission

### ISSUE THREAD

**Issue by secretvengence23** [RPCS3/rpcs3#12984]
### Quick summary

rpsc3 v.0.0.25-14393
The game always freezes and crashes at the beginning of 7th level. Whatever I do, nothing changed.
Tried to continue this game using v.0.0.9-10000 - also freezes.
![Безымянный](https://user-images.githubusercontent.com/119105488/204083159-232be999-2fdb-4c26-953f-8beb03781288.png)

### Details

Tried to set PSN status to "Disconnected" as I found in some report - but thad didn't help
Tried to set Accurate DFMA to "False" but in my custom config .txt file for Resistance there is no grath for "Advanced" settings. Tried to write it manually - nothing changed
Tried to disable all game patches and set all GPU settings to minimum - also nothing changed.
I'll give you savestate of the game to try, if the issue can be on your PC:
https://www.dropbox.com/s/9r7b4ud84pqmdoc/savestat.zip?dl=0

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10096022/RPCS3.log.gz)

### System configuration

ASUS PRIME Z690-P D4
i7-12700K
32GB RAM
Sapphere AMD Radeon 5700xt 8GB
Windows 10
SSD Kingston 512GB

**Comment by secretvengence23** [comment]
Problem solved by replacing old game.psarc file with the new one. No need to consultate it already

**Comment by EmG07** [comment]
> Problem solved by replacing old game.psarc file with the new one. No need to consultate it already

What is psarc file and where do i get it? I have the same problem and cant continue the game
