### ISSUE TITLE
Ratatouille BLUS30043

### ISSUE THREAD

**Issue by ZHassanQ** [RPCS3/rpcs3#12981]
BLUS30043

I know this isn't the right place but I didn't find Ratatouille the NTSC Version I tried it and it works fine. Thanks

**Comment by redZONErare** [comment]
Go ahead and make a new report on the RPCS3 Forums then, this is not a place to report new gameids

**Comment by MSuih** [comment]
https://forums.rpcs3.net/thread-196671.html
