### ISSUE TITLE
BLUS30023 - The Godfather: The Don's Edition: Vulkan doesnt update ingame time

### ISSUE THREAD

**Issue by Osman1c** [RPCS3/rpcs3#12986]
### Quick summary

Opengl under 30fps and time working. Vulkan constant 60fps no time working.

### Details

When I use opengl the time works as it should, but no matter how strong ur pc is u wont get over 30fps and sometimes it will drop below 20. With vulkan my GPU fans dont even need to spin and i have constant 60fps, but the game time doesnt update and is stuck a random time(resets after missions). Its a important mechanic in the game. I love this game and i would appreciate ur help.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10096846/RPCS3.log)

### System configuration

Ryzen5800x, RTX 3080, 16GB RAM

**Comment by TarifaTheInsane** [comment]
Can confirm the ingame time doesn't work me either. Current workaround I'm using is to enable speedhack and set it to 500x speed in cheat engine, then I wait for a week to pass ingame time and disable it.

**Comment by kaioto-ARG** [comment]
The issue seems to be the 60fps. If you limit the fps to 30 the ingame time works as intended.

**Comment by Crockos** [comment]
Sadly zerox who create the patch never fix it. I try it to reach him but I only found his youtube channel where he's not responding, maybe abandoned his channel, his last upload was 1 year ago.
The title of this thread should be The 60fps patch slows down ingame time due to isn't a problem of vulkan.

**Comment by AniLeo** [comment]
This game is locked at 30fps so this issue is not valid in any case, as 60fps requires using a game patch and we don't take bugs caused by enabled game patches.
