### ISSUE TITLE
Tr

### ISSUE THREAD

**Issue by Sunlord330** [RPCS3/rpcs3#12997]
### Quick summary

I download rpcs3-v0.0.25-14399-630edde1_win64 and extract the file and click the .exe and this happens

<img width="355" alt="Screen Shot 2022-11-29 at 8 39 22 PM" src="https://user-images.githubusercontent.com/76407271/204687069-79386cba-e013-4057-ad6e-5d872721e4e9.png">

### Attach a log file

The log is blank

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10118657/RPCS3.log)

**Comment by Darkhost1999** [comment]
Works on my machine.
Check the [QuickStart Guide](https://rpcs3.net/quickstart)
Join our [Discord](https://discord.com/invite/Af7H9yp) or our [Forums](https://forums.rpcs3.net/) to ask for support.
Or you can even ask on the pinned [Reddit](https://discord.com/invite/Af7H9yp) support questions thread.

**Comment by Sunlord330** [comment]
any one have any ideas
