### ISSUE TITLE
Verification failed Thread id = 1248

### ISSUE THREAD

**Issue by Sunlord330** [RPCS3/rpcs3#12999]
### Quick summary

I just downloaded it and extraced the file with 7zip and pushed the .exe and then I get this error message. (I am also using windows on a virtual machine.)

### Attach a log file

There is nothing on the log file for some reason.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10125772/RPCS3.log)

**Comment by MSuih** [comment]
Ask for help on our Discord.
