### ISSUE TITLE
Metal Gear Solid Peace Walker Co-op multiplayer doesn't work

### ISSUE THREAD

**Issue by Geronculus** [RPCS3/rpcs3#12992]
### Quick summary

In the game: "Metal Gear Solid Peace Walker" in the "Metal Gear Solid HD Collection" the multiplayer for the campaign co-op missions only the first 2 missions work with restarting the game and emulator, but the other missions dont work.

### Details

Even if restarting the game and the emulator the other missions dont work.
Mostly when the joiner joins the mission then it says: "Now Connceting..." and after that it fails.
Sometimes the the joiner joins the mission for the host the joiner joined but the joiner it still says "Now Connecting..." and then it fails.

### Attach a log file

Host:
U cellSysutilAvc2 TODO: cellSysutilAvc2GetVoiceMuting(muting=*0xd0100590)
U cellSysutilAvc2 TODO: cellSysutilAvc2SetVoiceMuting(muting=0x0)

Joiner:
U sceNp TODO: sceNpBasicSetPresence(data=0x0, size=0)
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVX0000x.PDT” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVY0000x.PDT” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVZ0000x.PDT” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVW0000x.PDT” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVX0000x.PDT” [2]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVY0000x.PDT” [2]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVZ0000x.PDT” [2]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVW0000x.PDT” [2]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVX0000x.PDT” [3]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVY0000x.PDT” [3]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVZ0000x.PDT” [3]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/ms0/US/DLCVOICE/AVW0000x.PDT” [3]
E SYS: 'sceNpBasicRecvMessageCustom' failed with 0x8002a671 : SCE_NP_BASIC_ERROR_CANCEL [1]
E SYS: 'sceNpBasicRecvMessageCustom' failed with 0x8002a671 : SCE_NP_BASIC_ERROR_CANCEL [2]
U sceNp2 TODO: sceNpMatching2SetUserInfo(ctxId=1, reqParam=0xd0100220, optParam=0x0, assignedReqId=0xd0100210)
U sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd01008d8)
U sceNp2 TODO: sceNpMatching2ContextStop(ctxId=1)

### Attach capture files for visual issues

![Bild_2022-11-27_103154779](https://user-images.githubusercontent.com/119158067/204128300-3235dfb7-fa92-4dfc-8e65-100a445761f7.png)

**Comment by FlexBy420** [comment]
Not all games are expected to work properly with RPCN. GalCiv said it's a issue with scenpsignaling and needs to be reworked iirc, sometimes the game works sometimes it does not. This issue can be closed.

**Comment by MSuih** [comment]
We currently do not take "multiplayer does not work" issues.
