### ISSUE TITLE
BLUS30428 - Catherine Freezes after Passing the "Clock Tower" Level

### ISSUE THREAD

**Issue by Gimpy3887** [RPCS3/rpcs3#12990]
### Quick summary

After I pass the Clock Tower level with the baby that has a chainsaw, the game just freezes.

### Details

The game crashes after the Clock Tower level is passed, and it happens during a cutscene where time is moving forward. I thought about changing from windowed to fullscreen vice versa to see if that was the issue, but it wasn't. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10097361/RPCS3.log)

### System configuration

- SYS: RPCS3 v0.0.25-14394-8b934abc Alpha | master 
- SYS: VirtualApple @ 2.50GHz | 8 Threads | 16.00 GiB RAM | TSC: 1.000GHz 
- SYS: Operating system: macOS, Version: 13.0.1
-  SYS: Current Time: 2022-11-26T20:46:05 
- RSX: Found vulkan-compatible GPU: 'Apple M1' running on driver 0.2.984
-  SYS: Firmware version: 4.89

### Other details

If including the save state helps, I've uploaded it to a file sharing website that can be downloaded from here https://anonfiles.com/0dd8D5J6ya/BLUS30428_SAVESTAT

**Comment by AniLeo** [comment]
Bad dump being used, invalid report

**Comment by Gimpy3887** [comment]
> Bad dump being used, invalid report

Oh, thanks for the response; I wonder how I would identify if the dump is bad?

**Comment by AniLeo** [comment]
https://wiki.rpcs3.net/index.php?title=Help:Validating_PlayStation_3_game_dumps

Support requests are not for GitHub, but for the other discussion platforms we have
