### ISSUE TITLE
black skreen

### ISSUE THREAD

**Issue by nortonF64** [RPCS3/rpcs3#13003]
### Quick summary

E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game//USRDIR/data/system/nuccMaterial_ps3.nsh” [1]

### Details

when trying to log into jojo eyes of heaven, a black screen appears when exiting, the error E sys_fs appears: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game//USRDIR/data/system/nuccMaterial_ps3.nsh” [1]

### Attach a log file

https://mega.nz/file/4z4XlbSY#eaoTGi8VP8sVKX-dARoOVWmYpzTqO2rMJUcWGR9WFdk

**Comment by MSuih** [comment]
Ask for help with emulator on Discord, not in github
