### ISSUE TITLE
[Regression] [BLUS31006] Tales of Xillia gives DLC error with no DLC installed (#13002)

### ISSUE THREAD

**Issue by esutley** [RPCS3/rpcs3#13009]
### Quick summary

Game gives "An error occurred with the DLC. Please quit the game and try downloading it again" screen after logos, even though I have no dlc installed. Boots correctly in previous versions.

### Details

<img width="961" alt="ToX Error" src="https://user-images.githubusercontent.com/37878138/205443278-281ee0ce-f12e-40d9-ad38-696b2edaa0d7.PNG">

Just got RPCS3 set up on a new PC and dumped this game to test it. Got this error after the Bandai/Namco logos. I don't have any dlc installed (or even on my computer at all) so this error surprised me. 

I went back to an old version I had on an external drive (v0.0.15-11893-a3a4c0a9) to check if it was something on my PC causing the error and saw that it worked. Just found out from testing quite a few builds that it's v0.0.25-14405-8d9dd1d1 that breaks it. Haven't tested or dumped ToX2 yet though it wouldn't surprise me if it gives the same error since they seem to share these kinds of problems.

Not technically a part of this issue (and not as big of a deal) but the game also seems to softlock and hang on a white screen if the logos are skipped. This happens on all recent versions I tried (back to v0.0.23-14011-b2d84dce) but doesn't seem to occur on v0.0.15-11893-a3a4c0a9. I haven't found what version this starts on.

### Build with regression

v0.0.25-14405-8d9dd1d1

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10146447/RPCS3.log.gz)
Log from 14405 with error
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10146449/RPCS3.log.gz)
Log from 14404 that boots to game

### System configuration

OS: Windows 10
CPU: AMD Ryzen 7 5800x
GPU: Nvidia GTX 970
RAM: 32GB DDR4

**Comment by esutley** [comment]
Just wanted to confirm that this error also occurs on Tales of Xillia 2 [BLUS31397]
<img width="961" alt="ToX2 Error" src="https://user-images.githubusercontent.com/37878138/205445197-76356b14-2469-4815-9186-beb0287bbaa6.PNG">

Occurs with the same versions as the first game
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10146610/RPCS3.log.gz)
Log from 14405 with error
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10146614/RPCS3.log.gz)
Log from 14404 that boots to game

This game also hangs like the first after skipping logos too

**Comment by elad335** [comment]
Try with #13008

**Comment by brian218** [comment]
In #13002, only a few sys_fs syscalls **which only VSH/XMB (or apps having root privilege) is allowed to call**, so I doubt whether the mentioned PR is the actual cause.
Can you open your config.yml (in the same directory as rpcs3.exe), and put this `Log: { sys_fs: Trace }` in the last line, replacing existing one (if any), and re-test both versions and send the logs again?

**Comment by esutley** [comment]
Here's ToX on 14405 with the Trace
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10146711/RPCS3.log.gz)

And here's 14404
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10146698/RPCS3.log.gz)

**Comment by brian218** [comment]
Kindly try #13007 when the build process is completed.

**Comment by brian218** [comment]
> Kindly try #13007 when the build process is completed.

It's ready for download now.

**Comment by esutley** [comment]
> It's ready for download now.

Do I need to build this release on my end? Sorry for asking I'm just a bit lost

**Comment by brian218** [comment]
> > It's ready for download now.
> 
> Do I need to build this release on my end? Sorry for asking I'm just a bit lost

https://api.cirrus-ci.com/v1/artifact/task/6007063331995648/Artifact/rpcs3-v0.0.25-9fa1dfd1_win64.7z

**Comment by esutley** [comment]
That fixed it!
Here's the log file with the `Log: { sys_fs: Trace }`
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10146842/RPCS3.log.gz)

**Comment by brian218** [comment]
Great! Glad to hear that!

**Comment by Megamouse** [comment]
Test with #13010

**Comment by esutley** [comment]
Also working there
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10146881/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Closing as #13010 was merged
