### ISSUE TITLE
Error 9616 - NHL 14

### ISSUE THREAD

**Issue by LelouchviBritannia99** [RPCS3/rpcs3#13006]
### Quick summary

Game freezing during NHL 14 match repeatedly on latest RPCS3 version.

### Details

When playing NHL 14 while over halfway through a match, the game completely freezes, forcing me to close the game. I get the error code 9616 that says that the thread deadlocked. How do I fix this? I'm not very tech-savvy, so please give me a step by step.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10145199/RPCS3.log.gz)

### System configuration

CPU is an i7 9700K
GPU is an EVGA RTX 3060
16 GB Ram
1 TB M.2 NVME SSD

**Comment by AniLeo** [comment]
Not an issue report, it's a support request, closing

There's no such thing as error code 9616 and the log file isn't even for the same game

**Comment by ShaneGervais** [comment]
I was getting this a lot too, maybe try going on "Config" then "Advanced" then change "RSX FIFO Accuracy" to "Atomic".
