### ISSUE TITLE
[Feature request] Remove cache folder as well when removing all caches

### ISSUE THREAD

**Issue by Masamune3210** [RPCS3/rpcs3#13012]
### Quick summary

Remove TitleID named cache folder when asking the emulator to remove all caches

### Details

If possible, would like the emulator to also remove the top-level folder for the game if all caches are asked to be removed. Currently, when removing all caches, all files are removed, but folder structure remains as a skeleton, which clutters up things

**Comment by brian218** [comment]
I attempted to implement your feature request in the emulator. However, I figured out that there is no point doing this, as the caches folder gets created (in case it doesn't exist) automatically each time you start rpcs3.exe or the game.
