### ISSUE TITLE
[Feature request] Add a rollover option for logs

### ISSUE THREAD

**Issue by Masamune3210** [RPCS3/rpcs3#13029]
### Quick summary

If the emulator is ran for long periods without closing the application completely, the log can grow to gigantic (relatively speaking for a log) sizes. Possible to get an option or routine to roll over the log so it doesn't grow to such a large size? 

### Details

If a user doesn't close the app and instead just closes the game for long periods of time, the log will never get rolled and compressed into a archive, instead just growing larger and larger. I have a habit of just closing the game and leaving the emulator proper open so I can just start the game back up when I have a chance. Combining this with the fact that I regularly hibernate my computer rather than fully shutting it down caused the log file to be 2.9GB in size. I can imagine I'm probably not the only person that has a habit of leaving the game list open. Rolling the log at a certain file size might be a good idea, if nothing else just to make it easier for users to upload should a issue come up that needs reporting

**Comment by elad335** [comment]
Just disable logs in advanced tab.

**Comment by elad335** [comment]
There can be an option to ask the user if he wants to get rid of the log when closing the game in case no issue had occured.

**Comment by Masamune3210** [comment]
Disabling logs is a bad fix imo because if something later happens that needs the log to be reported correctly, it will be absent

**Comment by brian218** [comment]
Or maybe add an option "Log errors only" (only "error" and "fatal" will be logged)?

**Comment by kd-11** [comment]
> Disabling logs is a bad fix imo because if something later happens that needs the log to be reported correctly, it will be absent

We get a lot more info from the logs than just the last part before a crash. In fact I'd argue most of the information we need is usually in the first few megabytes of the log file. Module compilation info, settings, module imports, etc are critical information. Same goes for the other solutions such as "errors only".
The logs will be likely unusable anyway, might as well just disable the log output.

**Comment by Masamune3210** [comment]
Ok, will do. Thanks

**Comment by Megamouse** [comment]
I gather this is decided as won't fix
