### ISSUE TITLE
"vulkan-1.dll incorrectly installed" even when it is installed correctly.

### ISSUE THREAD

**Issue by spitfirex86** [RPCS3/rpcs3#13022]
### Quick summary

Just updated to 0.0.25-14413, RPCS3 now reports `vulkan-1.dll` as being incorrectly installed, despite installing it from the provided link and it being present in C:\Windows\System32.

![image](https://user-images.githubusercontent.com/33195187/206018091-a2e5f5ba-1152-4a49-a616-f4e19132bcbf.png)

The DLL is not present anywhere in the RPCS3 directory either.
![image](https://user-images.githubusercontent.com/33195187/206018221-1ca65f37-88b7-4e1a-9ba8-16f638af54ec.png)

My wild guess is that the system root check in `module_verifier.hpp`, line 53, is case-sensitive when it should not be and the string literal it's searching for in the path is defined as `C:\\WINDOWS\\`, all caps.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10170216/RPCS3.log)

### System configuration

RPCS3 0.0.25-14413 on Windows 10, 64-bit

**Comment by spitfirex86** [comment]
One more thing to add: I'd recommend using the [winapi GetWindowsDirectory function](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getwindowsdirectoryw) to retrieve the proper path, as there is no guarantee that the system drive will always use the letter C.

**Comment by Zulthar** [comment]
I got the exact same error message immediately after I updated RPCS3

**Comment by G8RPHD** [comment]
Confirmed same error message after RPCS3 update.

**Comment by Daxter4K** [comment]
Same here as well, I tried putting a vulkan-1.dll in the rpcs3 folder and still get the same error

**Comment by heisey3** [comment]
can confirm this issue as well

**Comment by solarmystic** [comment]
confirmed fixed with #13023 

![image](https://user-images.githubusercontent.com/4345150/206044079-541a353b-c881-4343-874f-da8a8d6b8a05.png)

**Comment by Daxter4K** [comment]
How do I get the new version that has the fix since the error does not let me get the auto-updater prompt?

**Comment by solarmystic** [comment]
> How do I get the new version that has the fix since the error does not let me get the auto-updater prompt?

All builds are provided here - 

https://rpcs3.net/compatibility?b

**Comment by KuwabaraHasegawaIkko** [comment]
I'm angered to you all developer again you triggered this issue 2023 JUNE all RPCS3 now canno
![Screenshot 2023-06-24 172336](https://github.com/RPCS3/rpcs3/assets/128128742/04b69f54-7bd4-4aae-a05c-7a7246351d58)
t launched
