### ISSUE TITLE
Resolution scale threshold precision

### ISSUE THREAD

**Issue by Zulthar** [RPCS3/rpcs3#13026]
### Quick summary

being able to type in the resolution for the titled setting in the GPU config menu

### Details

I figured since both values were identical it could just be typed in or use the slider

**Comment by Darkhost1999** [comment]
Did you know you can scroll your mouse wheel or use arrow keys on your keyboard for fine tuning resolution scale.
Although it's ill advised to use values other than 150%, 200%, 250%, and 300%.

So if you want precision and the slider is acceptable for that precision. Just use arrow keys. If you're trying to stretch to like a weird 17:9 or something screen just click -> stretch to display. You can also use stretch to display from 4:3 aspect ratio.

**Comment by Darkhost1999** [comment]
K. Then you can use keyboard keys or scroll your mouse wheel over the slider to set 512x512.
You can also open the config.yml file or right click your game -> open custom config path and type the values by hand.
The precision exists already.

**Comment by Megamouse** [comment]
I also don't think we need to change this. It would just add more bloat for something that is already possible.

**Comment by Asinin3** [comment]
I agree, and you basically never need to be exact with the threshold values people tell you to use. People just keep reiterating the same arbitrary number to use to fix problems but even if you are close it will work fine. People should just change the setting they tell people to use to one of the ones the slider actually snaps to.
