### ISSUE TITLE
MACOS | Textures flashing / not loading correctly

### ISSUE THREAD

**Issue by lewishooper7** [RPCS3/rpcs3#13031]
### Quick summary

When loading a game on my MacBook Pro 13inch M1 2020 games either don't render textures correctly or they just flash

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10184147/RPCS3.log.gz)

### Attach capture files for visual issues

<img width="1440" alt="Screenshot 2022-12-08 at 12 38 06 am" src="https://user-images.githubusercontent.com/60070595/206414062-ecc388c8-ba5a-4a1f-93df-d37bf779cfdb.png">

https://user-images.githubusercontent.com/60070595/206417791-481fe68b-85d4-4591-ab77-6257b320a5ce.mp4

### System configuration

macOS ventura 13.0.1
M1 Chip
16GB memory 

### Other details

same games work fine on my Windows 11 PC but doesn't work on my Mac

**Comment by bethgraybill** [comment]
Is there any update on whether this Is possible for the m2? I'm having the same issues in COD-Black ops

**Comment by kd-11** [comment]
> Is there any update on whether this Is possible for the m2? I'm having the same issues in COD-Black ops

No. It's practically the same GPU as M1 with the same problems.

**Comment by bethgraybill** [comment]
Is there not another way to potentially work around this problem?
