### ISSUE TITLE
NHL Legacy crash at goalie interference if RSX FIFO accuracy is default

### ISSUE THREAD

**Issue by saojoao** [RPCS3/rpcs3#13039]
### Quick summary

Game freezes dead when I get a goalie interference.
Other gameplay is smooth.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10198779/RPCS3.log)

### Attach capture files for visual issues

![2](https://user-images.githubusercontent.com/63754159/206813795-ea714f34-8db2-4262-9d46-5879ed4c7161.png)
![1](https://user-images.githubusercontent.com/63754159/206813797-d3443ced-21e6-46ae-9143-167465302c4f.png)

### System configuration

i5-12500H
RTX3060
16GB RAM

**Comment by Triticum0** [comment]
Set the RSX FIFO accuracy to atomic and order to see if it fixes the issue

**Comment by saojoao** [comment]
It fixed the issue but performance was slightly decreased.
New problems with some textures appeared.
Mismatch textures on gloves and faces sometimes.

**Comment by elad335** [comment]
If fixed by an accuracy option without major performamce hit than it should be closed.
