### ISSUE TITLE
AppImage: Cannot open system directories from the emulator

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#13044]
### How to reproduce

1. Launch RPCS3 AppImage from the command line
2. Manage -> Trophies
3. Right click a game -> Open Trophy Directory
4. No folder is opened, see the output on the command line

It is the same for any open directory functionality, such as "Open Install Folder", "Open Custom Config Folder"

### Command line output
```
xdg-mime: no method available for querying MIME type of '/home/ani/Dropbox/00000001/trophy/NPWR00537_00'
xdg-mime: mimetype argument missing
Try 'xdg-mime --help' for more information.
/usr/bin/xdg-open: line 880: x-www-browser: command not found
XPCOMGlueLoad error for file /usr/lib/firefox/libmozgtk.so:
/usr/lib/libgio-2.0.so.0: undefined symbol: g_source_set_static_name
Couldn't load XPCOM.
/usr/bin/xdg-open: line 880: iceweasel: command not found
/usr/bin/xdg-open: line 880: seamonkey: command not found
/usr/bin/xdg-open: line 880: mozilla: command not found
/usr/bin/xdg-open: line 880: epiphany: command not found
/usr/bin/xdg-open: line 880: konqueror: command not found
/usr/bin/xdg-open: line 880: chromium: command not found
/usr/bin/xdg-open: line 880: chromium-browser: command not found
/usr/bin/xdg-open: line 880: google-chrome: command not found
/usr/bin/xdg-open: line 880: www-browser: command not found
/usr/bin/xdg-open: line 880: links2: command not found
/usr/bin/xdg-open: line 880: elinks: command not found
/usr/bin/xdg-open: line 880: links: command not found
/usr/bin/xdg-open: line 880: lynx: command not found
/usr/bin/xdg-open: line 880: w3m: command not found
xdg-open: no method available for opening 'file:///home/ani/.config/rpcs3/dev_hdd0/home/00000001/trophy/NPWR00537_00/'
```

### System specifications
OS: Manjaro Linux x86_64 
Kernel: 6.0.11-1-MANJARO 
Shell: zsh 5.9 
DE: GNOME 43.1 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Papirus-Dark [GTK2/3] 
Terminal: gnome-terminal

**Comment by Megamouse** [comment]
Missing log file

**Comment by AniLeo** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10200356/RPCS3.log)

There's nothing logged, only stdout output, but here it is

**Comment by AniLeo** [comment]
Problem with the AppImage, local build works

**Comment by legluondunet** [comment]
Hello,
I can reproduce this bug on Linux Manjaro and rpcs3 AppImage.

Log joined.
[rpcs3.log](https://github.com/RPCS3/rpcs3/files/10328885/rpcs3.log)

**Comment by qurious-pixel** [comment]
The missing symbol `g_source_set_static_name` from the host `libgio-2.0.so.0` is in conflict with the bundled `libgmodule-2.0.so.0` and `libglib-2.0.so.0`.

Removing those from the AppImage, allows xdg-open to use file-manager instead of x-www-browser.
