### ISSUE TITLE
Regression: Application menu game shortcuts don't work anymore (#13008)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#13047]
Last good version: 0.0.25-14432
First broken version: 0.0.25-14437 (#13008)

### .desktop file on 0.0.25-14432
```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec="/home/ani/Downloads/rpcs3-v0.0.25-14432-b0e376ae_linux64.AppImage" --no-gui "/home/ani/Games/BLES01227 - Asura's Wrath/PS3_GAME"
Name=ASURA'S WRATH
Categories=Application;Game
Comment=ASURA'S WRATH
Icon=/home/ani/.config/rpcs3/Icons/game_icons/BLES01227/shortcut.png
```

### .desktop file afterwards
```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec="/home/ani/rpcs3.AppImage" --no-gui "%RPCS3_GAMEID%:BLES01227"
Name=ASURA'S WRATH
Categories=Application;Game
Comment=ASURA'S WRATH
Icon=/home/ani/.config/rpcs3/Icons/game_icons/BLES01227/shortcut.png
```

### When trying to open the icon:

![error](https://cdn.discordapp.com/attachments/303330503392755712/1051166199909728316/image.png)

### Log file from trying to boot the broken icon:

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10200434/RPCS3.log)

### System specifications

OS: Manjaro Linux x86_64
Kernel: 6.0.11-1-MANJARO
Shell: zsh 5.9
DE: GNOME 43.1
WM: Mutter
WM Theme: Adwaita
Theme: Adwaita-dark [GTK2/3]
Icons: Papirus-Dark [GTK2/3]
Terminal: gnome-terminal

**Comment by elad335** [comment]
what happens if you change the % into $ in the source code? or remove it completely?

**Comment by AniLeo** [comment]
If I run the command in the .desktop file directly from terminal, it doesn't weirdly escape anything, but I have this error instead:

```
"/home/ani/rpcs3.AppImage" --no-gui "%RPCS3_GAMEID%:BLES01227"
Debugger: 0
RPCS3: SYS: Game directory not found using GAMEID token. ('BLES01227')
RPCS3: Booting '%RPCS3_GAMEID%:BLES01227' failed!

Reason: Invalid file or folder
Found exec link: /tmp/.mount_rpcs3.pKsnhB/usr/bin/rpcs3
```

Removing the variable:

```
"/home/ani/rpcs3.AppImage" --no-gui "BLES01227"
Debugger: 0
RPCS3: Booting '/tmp/.mount_rpcs3.WQYyrM/usr/BLES01227' failed!

Reason: Invalid file or folder
```

Changing into $ doesn't work since that's for environment variables

The game is properly registered in games.yml, it shows up in the game list UI and can be ran properly from the emulator after all
