### ISSUE TITLE
No Games Will Start 

### ISSUE THREAD

**Issue by c6deso** [RPCS3/rpcs3#13055]
### Quick summary

Game wont start please help 

### Attach a log file

[RPCS3 (2).zip](https://github.com/RPCS3/rpcs3/files/10201925/RPCS3.2.zip)

### System configuration

Rx570
rzyen 5 2600
16gb ram 
windows 10

**Comment by YuriNator557** [comment]
This is a known regression caused by version 14452, but this report is a support request which is not valid

**Comment by AniLeo** [comment]
Already fixed
