### ISSUE TITLE
[Feature request] Side-By-Side 3D support

### ISSUE THREAD

**Issue by blan44** [RPCS3/rpcs3#13059]
### Quick summary

It's been over 2 years since PlayStation 3D support was added to RPCS3, yet the only supported viewing mode is still Anaglyph.
I would like to request that a Side-By-Side viewing mode be added for Playstation 3D content.

### Details

With Side-By-Side 3D, it would be possible to view the 3D image natively within a VR headset using an application like Bigscreen VR.

**Comment by kd-11** [comment]
I'll give it a shot sometime. Putting the images side by side is easy, making sure it works with actual VR stuff is the hard part.

**Comment by blan44** [comment]
>Putting the images side by side is easy, making sure it works with actual VR stuff is the hard part.

You mean like making sure the resolution still looks right when the images are combined?

**Comment by AARP41298** [comment]
I know, in the mean time i got an used 3D TV and play with tridef and 3D fix manager
The exclusive ones of ps3 are still waiting

**Comment by rekabffej** [comment]
This would be amazing!  Would love to play my old 3D exclusives such as child of Eden in VR

**Comment by blan44** [comment]
ok that's cool

**Comment by Megamouse** [comment]
Should be implemented now
