### ISSUE TITLE
WWE Smackdown vs RAW 2010 [BLUS30412] Graphical glitches

### ISSUE THREAD

**Issue by Joshking07** [RPCS3/rpcs3#13053]
### Quick summary

The game runs smoothly but has visual glitches.

### Details

There are visual glitches in the Practice arena. During entrances the first wrestler's entrance is fine but the second wrestler's entrance starts to get visually glitchy and it carries on to the match. After some testing, the visual glitches get worse as more wrestlers are in the match and so do the entrances. The game becomes a glitchy mess.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10201659/RPCS3.log.gz)

### Attach capture files for visual issues

https://mega.nz/file/5C1nmKyJ#9_5e495f2ZeE7bBx6KeHAII2qTGbLs_WguDL0xb-tcQ

### System configuration

System Specs:

OS: Windows 11 22H2
CPU: Ryzen 5 3600 
GPU: 1660 Ti
RAM: DDR4 16GB RAM 
RPCS3 Build: 0.0.25-14452-83995164 Alpha | master

### Other details

The glitches also occur in OpenGL

**Comment by mfdsrax2** [comment]
Could you post a screenshot of the issue and a comparison with real PS3?
