### ISSUE TITLE
Segfault when booting from savestate 2nd time

### ISSUE THREAD

**Issue by quickishfm** [RPCS3/rpcs3#13058]
### Quick summary

Playing MGS3 from the Metal Gear Solid HD Collection, booting from savestate a 2nd time results in a segfault

RPCS3: Network Thread: SIG: Thread terminated due to fatal error: Segfault reading location 0000000000000000 at 00000000008f2650.
Emu Thread Name: 'Network Thread'.

### Details

The first time booting normally or from a savestate works, but after closing it and booting again it segfaults.

### Attach a log file

https://controlc.com/f8e650db

### System configuration

Arch Linux
6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64 GNU/Linux

Ryzen 3800x
64GB DDR4 3200MHz RAM
Nvidia Geforce GTX 1080Ti

﻿RPCS3 v0.0.25-14454-ab3c8268 Alpha | master

**Comment by elad335** [comment]
Probably outdated & fixed, closing. Open a new issue if persists.
