### ISSUE TITLE
bleach soul resureccioon bug

### ISSUE THREAD

**Issue by jkl312** [RPCS3/rpcs3#13051]
### Quick summary

![Screenshot_1](https://user-images.githubusercontent.com/120283366/206877403-cb8e1c6f-bf3e-4a52-ad51-c2d1169b7af4.png)
i tried every single setting and i always get this,after some time of playing, i loose sound,and game freezes and i get soo much this error codes i need to close app and relaunch it for this error log to end,i downloaded much version of games,changed every setting i could and still nothing still game does this.. idk what to do..

### Attach a log file

[Uploading RPCS3.log.gz…]()

### System configuration

A8 7600 cpu
gpu: gt 730
ram: 12gb ddr3 - 8gb ddr3 1600mhz, 4gb 1866 mhz

**Comment by Darkhost1999** [comment]
That is some really old hardware.
Just wanted to let you know your log didn't finish uploading before you hit submit. If you want to edit that in.
Although I really recommend updating your hardware and trying again.

**Comment by AniLeo** [comment]
Support request, not an issue report

**Comment by jkl312** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10202377/RPCS3.log.gz)
here are logs sorry i thought it uploaded..

**Comment by AniLeo** [comment]
Log shows even further that this isn't a valid issue report, random settings being used without any explanation to why. This is a support request that needs to be submitted on a platform for that purpose, not on an issue tracker.
