### ISSUE TITLE
New macOS CI

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#13065]
Cirrus is going to remove x86-64 based instances on 1st January 2023

[We are sunsetting support for Intel-based macOS instances! Please migrate before January 1st 2023.](https://cirrus-ci.org/guide/macOS/)

We need a new CI operating before then, otherwise the macOS builds will not work and will be disabled until a new CI is up

**Comment by shinra-electric** [comment]
Clienthax had been doing some work for getting Arm64 CI working in #12602. 
May or may not be useful.
