### ISSUE TITLE
Check with PVS-Studio analyzer

### ISSUE THREAD

**Issue by KurenevAlexandr** [RPCS3/rpcs3#13068]
### Quick summary

Hello,
we checked GPCS3 (commit e98b07d) with static analyzer PVS-Studio and found some interesting bugs. Here is an [article](https://pvs-studio.com/en/blog/posts/cpp/1014/) about it. May be you will fix some problems.

### Attach a log file

https://pvs-studio.com/en/blog/posts/cpp/1014/

**Comment by oltolm** [comment]
This was fixed by #13569.
