### ISSUE TITLE
Call of Duty 3 -  Unknown blend eq 0xffff

### ISSUE THREAD

**Issue by Emogop** [RPCS3/rpcs3#13075]
### Quick summary

It's a duplicate of #3357 which had been closed but it's still an issue.

### Details

Changing the setting to atomic or "atomic and ordered" in the advanced tab doesn't help. I remember not long ago the game was playable, now it's not even going ingame. It hangs right after the unskippable mission FMV.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10228175/RPCS3.log)

### Attach capture files for visual issues

![Screenshot_251](https://user-images.githubusercontent.com/42875723/207608102-9178f775-a1cf-4a72-bd2f-ee1bbf1bb7c8.png)

### System configuration

My specs:
RPCS3 Version: 0.0.25-14476-7e35679e Alpha | master
i9 9980HK ES
16 gb RAM
GTX 1060
Driver 473.33

**Comment by elad335** [comment]
Reupload log with #13082, the exception was actually wrong.

**Comment by Emogop** [comment]
Here. The crash was fixed although during loading there occurs a fatal error but the game is still running fine.
![Screenshot_258](https://user-images.githubusercontent.com/42875723/208235905-84dce8bc-5fc2-43a9-8d77-a6743b886fa7.png)
 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10251414/RPCS3.log)

**Comment by Emogop** [comment]
So I played it about half an hour, no crashes. I guess I can close the issue.

**Comment by Blackbird88** [comment]
I get the same error but it freezes the game after cutscene

**Comment by Blackbird88** [comment]
Okay I finally figured out why this happens to me. This error always appears if you set **Resolution Scale** to 300% or more
![image](https://user-images.githubusercontent.com/4414625/210170697-727725d5-af29-4895-84a3-1752083636b7.png)
100-275% work fine, but anything more and this error happens.

@Emogop
Could you please test if this also happens to you?

**Comment by readywer** [comment]
@Blackbird88  Resolution Scale is a hack so if it isn't working is not a bug. There are many games which isn't support it.

**Comment by Blackbird88** [comment]
I never said it's a bug, but this is first time it caused a crash for me.
