### ISSUE TITLE
[Regression] Demon Souls black screen

### ISSUE THREAD

**Issue by CkNoSFeRaTU** [RPCS3/rpcs3#13087]
### Quick summary

When using vulkan renderer and have disabled `Asynchronous Texture Streaming` there is just black screen on normal boot. Otherwise game is working fine as you can interact with menus and can hear sound. Just can't see anything. RPCS3's overlay is displaying without issues.

![rpcs3_black_screen](https://user-images.githubusercontent.com/2136776/208222379-0e198c0d-1071-4438-878c-c57ff0353ded.png)

If you blindly go to in-game state, make save-state there and then load it there will be no issues.

### Details

It is due to `vkCmdFillBuffer` which is introduced in this [commit](https://github.com/RPCS3/rpcs3/commit/b39f4573634505ff167e39b9daac3d89bb10f140), You can change black to any other color by changing data value in it or make glitch only partial by changing zero_length to small values.
The problem goes away when removing `vkCmdFillBuffer` or adding additional `insert_buffer_memory_barrier` there.

### Build with regression

v0.0.25-14476-7e35679e

### Attach two log files

[RPCS3_14474.log.gz](https://github.com/RPCS3/rpcs3/files/10250707/RPCS3_14474.log.gz)
[RPCS3_14476.log.gz](https://github.com/RPCS3/rpcs3/files/10250708/RPCS3_14476.log.gz)

### Attach capture files for visual issues

Renderdoc captures which shows that game image is there on first render pass but disappear on second:
https://nosferatu.g0x.ru/rpcs3/rpcs_14474.zip
https://nosferatu.g0x.ru/rpcs3/rpcs_14476.zip

### System configuration

Windows 10 22H2, Ryzen 9 5950X, Radeon 6700XT with latest driver v.22.11.2

### Other details

Doesn't reproduce on the same hardware and rpcs3 configuration under Linux.

**Comment by solarmystic** [comment]
NVIDIA seems to be unaffected by the issue. Using a 2080ti, 527.56 drivers on Windows 21H2. Using Legacy Shader Mode (not Async)

![image](https://user-images.githubusercontent.com/4345150/208231751-10f6e4f5-23d5-4c7a-b003-d5f7b19ea23e.png)

**Comment by kd-11** [comment]
It's just a missing barrier on new resources.
NVIDIA is usually unaffected by things like these because their GPUs seem to work in a less parallel manner so you can mess up synchronization and it doesn't become apparent.
Fixed by https://github.com/RPCS3/rpcs3/pull/13090
