### ISSUE TITLE
[Regression] Armored Core 4 USA (BLUS-30027) Radar Markers no longer appear

### ISSUE THREAD

**Issue by noonoox** [RPCS3/rpcs3#13084]
### Quick summary

It appears that, for every build **_after_** v0.0.24-14124, radar markers no longer appear in the upper right corner.

### Details

The upper-right corner of the screen during missions has a radar window - which displays markers for enemies + elevation lines. From build v0.0.24-14127 onwards, the markers do not render - only the elevation lines, meaning many threats become invisible to the radar

### Build with regression

v0.0.24-14127

### Attach two log files

https://mega.nz/folder/fY1hHJIL#S8dAKd3Hl2bg-hK5LH1Rfw

### Attach capture files for visual issues

https://mega.nz/folder/fY1hHJIL#S8dAKd3Hl2bg-hK5LH1Rfw

### System configuration

CPU: Intel i9-12900K
GPU: GTX 3080 Ti
GPU Driver: 526.98

**Comment by Megamouse** [comment]
Duplicate
