### ISSUE TITLE
Armored Core 4 [BLUS30027] Radar icons don't show up, just the green lines indicating elevation.

### ISSUE THREAD

**Issue by LHDuarte** [RPCS3/rpcs3#13081]
### Quick summary

The radar icons for enemies don't show up, only the green lines and the red arrows indicating direction.
![image](https://user-images.githubusercontent.com/53906506/208033423-5141b55d-18a8-4ab2-8202-60ed29b13034.png)

### Details

Another two users reported this on this thread https://www.reddit.com/r/armoredcore/comments/xvq4fq/rpcs3_texture_bugs_fixed/

One pointed out that the latest build with the icons was v0.0.24-14123

I can report the icons are also missing on the Chapter 3 mission Barbe-Bleue, on the minimap in the lower left corner of the screen, making the mission harder to complete.(Only shows the map, not the player icon(green) nor the enemies(red)

Using various radar systems with increased range didn't change this, only icon that were showing were the red borders and the yellow cube representing the area/object to be defended.

### Attach a log file

[Uploading RPCS3.log…]()
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10243101/RPCS3.log.gz)

**Comment by noonoox** [comment]
Upon further testing, the correct build is actually 1 higher - v0.0.24-14124. Sorry for my incorrect initial statement on that reddit thread!

**Comment by Bismarkaroo** [comment]
I'm seeing this issue discussed a lot in Armored Core communities which are seeing a lot of activity with AC6's recent announcement.

This issue does significantly harm the playability of the game with some missions being nearly unplayable.

Is there any way I can put a bounty in getting this fixed or something?

**Comment by Cloud4Skies** [comment]
From my testing, v0.0.27-14876 and onward have fixed this radar bug. I believe this issue can be closed now.
![Screenshot from 2023-04-17 00-48-32](https://user-images.githubusercontent.com/7799933/232394117-cac9acb1-62ca-4798-935b-1ac3d80f50e1.png)
