### ISSUE TITLE
Dualshock 4 Controller LED not changing (Linux)

### ISSUE THREAD

**Issue by michaeljhkim** [RPCS3/rpcs3#13085]
### Quick summary

Dualshock 4 controller works on linux, but the LED options do not work. 

### Details

So I can connect everything just fine according to the instructions given, but when it comes time to change the LED (make it less bright, change color), I cannot do so. I find this to be very strange.

### Attach a log file

No error messages in the log files

**Comment by Megamouse** [comment]
Log file missing.
The description doesn't explain the issue well.
There are many ways to set the LEDs for a dualshock 4 and you don't give any information about how you are connecting the controller and which handler you're using.

**Comment by Megamouse** [comment]
closing as invalid
