### ISSUE TITLE
[Feature request] Rebindable PS Move face buttons

### ISSUE THREAD

**Issue by ElTioRata** [RPCS3/rpcs3#13093]
### Quick summary

I was **EXTREMELY HYPED UP** to play Umbrella Chronicles with mouse input **BUT** turns out the face buttons binds SUCKS, some buttons are bound to mouse buttons which generic mouses don't support (like those buttons at the left side of the mouse).
So I'm making this issue to track the future implementation of a proper GUI tab to rebind PS Move face buttons. Close this issue when such feature is implemented, cheers.

**Comment by dante3732** [comment]
Yes, the standard layout is very bad.
R+L button=circle R+MButton=triangle

**Comment by dante3732** [comment]
In the new versions of the emulator, buttons 4 and 5 do not work to press the circle, is there any way to return this?

**Comment by Megamouse** [comment]
This should be implemented

**Comment by PimpUigi** [comment]
I'm not sure how this was implemented, as I can't find anywhere in the GUI to bind these buttons, as was the request to track.
No guide out there seems to explain how to bind Mouse Button 4/5 successfully either.

Editing gem_mouse.yml I can get Mouse 1/2/3 to work, and Combo Mouses 1/2/3 to work, but that effectively leaves me binding T, Combo, Move, one face button like Circle/Triangle, and Start (which seems to be required for games to activate the PS Move pad).

This falls far short of the required buttons that the PS Move requires. So why not allow Mouse Wheel Up/Wheel Down and give proper Mouse Button 4 and Mouse Button 5 support? Then you don't even need a Combo button.

Mouse Button 1: T
Mouse Button 2: Move
Mouse Button 3: Start
Mouse Button 4: Square
Move Button 5: Circle
Wheel Up: Triangle
Wheel Down: Cross

I guess we're still missing Select. ;p
But the current release version of rpcs3 doesn't even let the mouse control the PS Move reticle anymore. So we're stuck reverting aways as it is. I still took the time to confirm the button limitations on the current release, and June 26th 2024 and June 27th 2024 releases to check and see if Mouse 4/5 ever worked. They don't.

It _would_ be really cool to play Umbrella/Darksideicka Chronicles HD with mouse aiming.
Thanks for taking the time to look into this stuff Megamouse, you have such a cool name! :D

This was my baby in 2008-2010, also named Mega Mouse:
![Image](https://github.com/user-attachments/assets/1d95dcf4-09fb-4baa-9e68-0de473890d6a)

**Comment by Felina-Lain** [comment]
Hi, joining in to say I also could not find where I'm supposed to be able to rebind the mouse buttons in the menus?
And editing the file is no good, because most mouses don't have that much buttons, so I tried to replace with keys, but they weren't detected when in-game either.
