### ISSUE TITLE
'Illegal Instruction' error on macOS (iMac 13,1)

### ISSUE THREAD

**Issue by Hyphingd** [RPCS3/rpcs3#13109]
### Quick summary

So, when I try and open Skate 3, I get this message:
Illegal instruction at 00007ff81bf34d5d (0x0f0b554889e54156534881ecd0000000).
Thread id = 123145641148416.

### Details

![image](https://user-images.githubusercontent.com/89696146/209216052-67f53a28-b105-4474-8b55-ffd2b7195313.png)

So, when I try and open Skate 3, I get this message:
Illegal instruction at 00007ff81bf34d5d (0x0f0b554889e54156534881ecd0000000).
Thread id = 123145641148416. I've seen the same exact error message happen to someone else, but they were using a MacBook Air, and I am using an iMac.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10290008/RPCS3.log)

### System configuration

Core i7-3770S
Nvidia Geforce GT 650M Mac Edition
16GB DDR3 1600Mhz
macOS Ventura 13.1
iMac 13,1 (Late 2012 21.5")

![Screenshot 2022-12-22 at 3 01 21 PM](https://user-images.githubusercontent.com/89696146/209216691-e5046244-f7b4-40a2-b89a-c717e03d8125.png)

### Other details

![image](https://user-images.githubusercontent.com/89696146/209216052-67f53a28-b105-4474-8b55-ffd2b7195313.png)

**Comment by AniLeo** [comment]
Below minimum requirements on the GPU side, NVIDIA 600 series doesn't support Vulkan and macOS doesn't support OpenGL 4.3.
