### ISSUE TITLE
Full Auto 2 Battlelines opengl graphical Issues

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13102]
### Quick summary

OpenGL cause graphical Issues on all fences and trees and some textures.

### Details

When testing this game on OpenGL I came arrow some graphical issues not present on Vulcan and the ps3
[First Issue]
OpenGL(above)
![NPUB90003_screenshot_2022_12_21_17_28_23](https://user-images.githubusercontent.com/71127352/208967302-5d50a58e-e628-4083-830a-cee2b0953db7.png)

Vulkan
![NPUB90003_screenshot_2022_12_21_17_20_29](https://user-images.githubusercontent.com/71127352/208967329-952f7f33-e479-4379-aec8-88eeadfd4c01.png)

PS3
https://youtu.be/zXH8fLlZTa0?t=7797

[Second Issue]
OpenGL(above metal beam)

https://user-images.githubusercontent.com/71127352/208979140-cb4580b9-57ba-46fe-8b05-bd24d148ad9e.mp4

Vulkan

https://user-images.githubusercontent.com/71127352/208974237-55effa15-b9fb-44cd-890e-54716df0933b.mp4

PS3
https://youtu.be/zXH8fLlZTa0?t=7795

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10280131/RPCS3.23.log.gz)

### Attach capture files for visual issues

https://www.dropbox.com/s/472aamod6ifne18/NPUB90003_20221221182227_capture.zip?dl=0

### System configuration

    SYS: RPCS3 v0.0.25-14478-812224f7 Alpha | master
    SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
    SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
    SYS: Current Time: 2022-10-28T21:53:46
    RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 526.47.0.0
    SYS: Firmware version: 4.89

**Comment by Satan86** [comment]
These issues happen due to the lack of MSAA on Open GL. It's also not exclusive to this game, most games that make use of MSAA display this issue on Open GL. Disabling Anti-Aliasing in the GPU Tab of settings on Vulkan causes the same bugs.

**Comment by Triticum0** [comment]
@Satan86 should I close the issue then?
