### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Altaiar** [RPCS3/rpcs3#1311]
when i read intel graphics driver release notes saw this
In the Intel® Iris™ and HD Graphics Control Panel (under Options > Options menu > Information Center), the ’Installed DirectX* version’ refers to the operating system’s DirectX version.   The Information Center’s ‘Supported DirectX* Version’ refers to the Intel Graphics Driver’s supported DirectX version.   The DirectX 12 API is supported but some optional features may not be available.  Applications using the DirectX 12 API should query for feature support before using specific hardware features.  Please note that DirectX12 is only supported on Windows 10 and DirectX11.3 support is also available on supported Microsoft* operating systems.  
AND This http://s3.picofile.com/file/8223998050/Capture.PNG
My Question is we can use DX12 with intel graphics?
In TechPowerUp GPU-Z : http://s6.picofile.com/file/8224000350/tech.PNG

**Comment by tambry** [comment]
@Altaiar It should run fine, as long as you have the latest drivers (from [here](https://downloadcenter.intel.com/)) and as long as your Intel HD graphics chip supports feature level 11_1 (might need @vlj to confirm the feature level required).

**Comment by Altaiar** [comment]
i have latest driver and when i run scogger HD With DX12 Crash in Metal slug3 in DX12 run correctly even before i have latest driver!

**Comment by tambry** [comment]
@Altaiar I'm sorry I can't understand you.

**Comment by Zangetsu38** [comment]
@Altaiar Normally, Scogger HD not works in DX12

**Comment by tambry** [comment]
@vlj @Zangetsu38 Might be then worth checking to see, what's wrong with Scogger HD.

**Comment by Zangetsu38** [comment]
@tambry vlj already see that

**Comment by vlj** [comment]
Min feature level is dx 11 so any gpu that express dx12 API support should work.

**Comment by tambry** [comment]
Closing this, as the question seems to have been solved.
