### ISSUE TITLE
[Feature request] Pre made cheat codes such as ones on PCSX2 and other emulators

### ISSUE THREAD

**Issue by mitch03** [RPCS3/rpcs3#13123]
### Quick summary

Pre made cheat codes that can be imported into RPCS3 

### Details

for example - Yu-Gi-Oh! Decade Duels Plus has a cheat code for all cards x3
[Have All Cards (x3)]
400020F0 00000006
4F3C0004 00000000

would be nice to have an option to be able to import this cheat code into RPCS3

PCSX2 uses a system like this!

![PCSX2 Cheat Codes](https://user-images.githubusercontent.com/83793249/209469683-2e6e6df6-0301-4e45-9467-b619fabb3d40.png)

**Comment by Margen67** [comment]
These already exist: https://wiki.rpcs3.net/index.php?title=Help:Game_Patches

**Comment by mitch03** [comment]
how would i put this code in? 
[Have All Cards (x3)]
400020F0 00000006
4F3C0004 00000000
