### ISSUE TITLE
Some random small fixes

### ISSUE THREAD

**Issue by vgturtle127** [RPCS3/rpcs3#1312]
I have found some random stuff that can be fixed quickly.

* [ ] First, the PAD settings should be changed to "Input settings". In the Pad settings dialog box, Left and Right "Shifts" should be called the L buttons and R buttons. "Left/Right Analog Stick" should be "Left/Right analog stick". "D-Pad" should be changed to "Directional pad". L3 and R3 should be moved to the "Analog stick" sections, since they are part of the analog stick.

* [ ] Under "System", "Send open system menu cmd" should be changed to "Press PlayStation button". Alternatively (and preferably), this should eventually be changed to a mappable button in the input settings. I'm not sure what the "Send exit command" option does, so hopefully I'm not assuming wrong about the system menu option.

* [ ] Auto pause options should be placed under tools, since that is what it is used for.

* [ ] In settings, change the PPU Decoder options from interpreter 1 and 2 to be more descriptive as to what the difference is between them. Change PPU Decoder and SPU Decoder to PPU/SPU decoder.

* [ ] Also in settings, under graphics, change "Render" to "Renderer". You could also change it to "Rendering API".

* [ ] Change "D3D Adaptater" to "DirectX 12 primary adapter".

* [ ] Organize resolution by size from lowest to highest.

* [ ] Change frame limit to match resolution by ordering them from lowest to highest.

* [ ] Change "Read/Write Color/Depth Buffers" to "Read/Write color/depth buffers". Don't use title case, is what I'm trying to say. So, also change "Debug Output" to "Debug output" and "3D Monitor" to 3D monitor".

* [ ] Under Audio, change "16 bit" to "16-bit".

* [ ] Under Input/Output, change "Pad handler" to "Controller handler". Change "Keyboard Handler" to "Keyboard handler". Change "Mouse Handler" to "Mouse handler".

* [ ] I'm not sure what the "Unknown" option is under "Camera type", but if it isn't needed we should remove it. EDIT: This is needed, and we should keep it!

* [ ] Under Miscellaneous, change "RSX Logging" to "RSX logging". Change "Auto Pause at System/Function Call" to "Automatically pause at system/function call".

* [ ] "Auto Pause Manager" should be changed to "Automatic pause settings".

* [ ] "Function Call" should be changed to "Function call" in the "Auto Pause Manager".

* [ ] "Restart of the game is required to apply" should be changed to "You mus restart your emulated game or application for changed settings to take effect". This should also be a separate paragraph from the rest of the text so that it stands out more.

* [ ] "Virtual File System Manager" should be changed to "Virtual file system manager".

* [ ] "Virtual HDD Manager" should be changed to "Virtual hard drive manager".

* [ ] "Save Data Utility" should be changed to "Save data manager".

* [ ] If you guys can, in the future, you should think about merging/updating the virtual file system and hard drive managers to be the same option, so you can manage everything from one place.

* [ ] "LLE Modules Manager" should be changed to "LLE module manager". The title of the window should be changed to "LLE module manager". It is currently "LLEModuleManagerFrame". EDIT: It has been changed from LLEModuleManagerFrame to LLE Module Manager Frame. I think Frame should be removed since it isn't relevant to the user, but I'm not sure...

* [ ] "ELF Compiler" should be changed to "ELF compiler", "Kernel Explorer" change to "Kernel explorer", "Memory Viewer" change to "Memory viewer", "RSX Debugger" change to "RSX debugger", "String Search" change to "String search", and "Cg Disasm" change to "Cg disassembler".

* [ ] Change "CompilerELF" to "ELF compiler". That is the title of the window for the ELF compiler.

* [ ] In the same window, change the singular "Code" menu option to "File". Switch "Compile" and "Load ELF" so Load ELF is on top.

* [ ] Add line numbers to the code window, so it is easier to find what line the error window is talking about.

* [ ] Change the "Cg Disasm" window title to "Cg disassembler". Change "open Cg binary program" to "Open Cg binary". Along with that, change the "Open" menu option to "File".

* [ ] Now for the main window. The "Game List" should be changed to "PS3 software" or "PS3 applications". The PS3 is capable of more than just games. :smile: 

* [ ] The "Icon" text can be removed, it is obvious what that section is for. "FW" should be changed to "Minimum firmware required". "App version" should be changed to "Software version". "Category" should be changed to "Software type".

* [ ] Under "Debugger", change "Go To Address" to "Go to address". Change "Go To PC" to "Go to PC".

* [ ] Under "Debugger", there is a drop down menu to the right of the pause button. If that is going to do something in the future, feel free to leave it in. But if you don't need it, remove it so we can claim that space for other things. It has always been empty for me.

* [ ] Under the log, the only thing I can think of is maybe remove some of the exclamation marks at the beginning of some console output lines? Unless that is for a purpose, in which case you can ignore that minor complaint.

* [ ] I think changing the "Boot" menu option to "File" would be a good idea, since technically nothing boots until you tell it, and also it is basically all the file operations that you need.

* [ ] On the "About" dialog box, you should replace "An early but promising PS3 emulator and debugger" with "A PlayStation 3 emulator and debugger". You should also arrange the bottom three buttons so that the website is first, then the forums, then our GitHub page. That is the most helpful arrangement. I would also recommend changing "OK" to "Close". Just for more clarity, I suppose.

* [ ] The last thing is probably to compile in additional information so that the "details" field in Windows is populated. You know, so that the name always appears correctly and it has version information and stuff. That will be useful when you guys start building an installer for it in the future. If you want to, that is.

Phew. :sleepy: 

That's all I have for now. Mostly cosmetic changes, but I think it will lead to a little less user confusion. In addition, it makes the application way easier to read and use as a result, even for developers.

Thanks for listening to my antics. :stuck_out_tongue_closed_eyes:

**Comment by tambry** [comment]
@vgturtle127 Wow. That's a lot of stuff!
Would you mind instead of the big wall, splitting it also into [task lists](https://help.github.com/articles/writing-on-github/#task-lists)?
That way we could more easily keep track of all the fixes made. You could probably split them into sub-categories by the area of the GUI/emulator.

**Comment by paulsapps** [comment]
@vgturtle127 you could probably make a PR with this fairly easily since its mainly just text changes :)

**Comment by tambry** [comment]
@vgturtle127 Forgot to say, but the camera thing is intentional - the function that returns the camera type, can sometimes return it as "Unknown".

**Comment by Zangetsu38** [comment]
I can take care of some stuff if you want.
Some changes are easy to make ^^

**Comment by Zangetsu38** [comment]
I complette change here https://github.com/RPCS3/rpcs3/pull/1314

**Comment by vgturtle127** [comment]
@tambry I can still split it into task lists if you would like, I actually just used task lists for a huge issue on Project64. :smile: 

@Zangetsu38 Thanks! Changes make it look so much better!

If you guys want me to break it into task lists I can, but I just need to know what hasn't been done yet. I am looking through the PR now, but I just want to make sure I get everything.

**Comment by vgturtle127** [comment]
I updated them as best I could. If you see any errors or anything let me know. :smile:

**Comment by Zangetsu38** [comment]
@vgturtle127 yes, most clear now :)

**Comment by Zangetsu38** [comment]
@vgturtle127 error, i d'ont touch resolution ^^

**Comment by vgturtle127** [comment]
I updated that, and also some other stuff.

**Comment by andre4688** [comment]
you can get create usb pad command as another commands? It was good

**Comment by tambry** [comment]
@andre4688 Please stop posting here. You can't speak English well enough for anyone to understand you.

**Comment by Zangetsu38** [comment]
updated, i have mistake change in ini

**Comment by vgturtle127** [comment]
@tambry I'm not sure that was the correct way to tell somebody that. Maybe tell them how to properly voice their thoughts and questions? We shouldn't cast out or demonize people for not speaking very good English. Telling them how they can improve their speech and/or writing is the only way to make the problem less of an issue. Just saying. Most of the users of my fighting game are Spaniards or are from Portugal. Just because they don't speak great English doesn't mean they can't help me immensely.

@Zangetsu38 Are you saying you made a mistake in an ini file? Or are you saying that there was a change I have on my list that isn't done yet?

**Comment by tambry** [comment]
@vgturtle127 I understand what you mean. He has already previously created useless issues and made pointless posts on forums, that were just later either closed or simply ignored, due to being absolutely useless, since we couldn't understand what he was saying (I mean, he couldn't even copy/write the games' names properly). I'm pretty sure we have told him numerous times before, to go and learn English. It has never improved.

**Comment by vgturtle127** [comment]
@tambry OK, that makes sense I suppose. I didn't know he was a repeat offender. That makes it a little different.

**Comment by Zangetsu38** [comment]
@vgturtle127 I meant the config.h that I had forgotten to change with the rest, but now it's good.

**Comment by vgturtle127** [comment]
@Zangetsu38 Oh, OK. :laughing:

**Comment by Zangetsu38** [comment]
Well, because it was me who did it, I think it will be never accepted the PR ...

**Comment by vgturtle127** [comment]
I can understand why they might not want to change function names, but text in the GUI seems irrelevant to anything, so why won't @Zangetsu38 's pull request be merged?

**Comment by Rukario** [comment]
1. I don't like lower-casing the secondary words. Dolphin Emulator don't do this.

2. Some terms were replaced with worse one. Please think of a better one or leave them alone. I've highlighted some below:

Drop "Directional pad"
Drop "DirectX 12 primary adapter" but fix "Adaptater" typo
A BIG NO to "You mus restart your emulated game or application for changed settings to take effect"
Drop "Virtual hard drive manager"
"LLE Module Manager Frame" is fine as it is

Better terms:
"Game List" -> "Title"

**Comment by vgturtle127** [comment]
I guess. I don't really understand why...

**Comment by tambry** [comment]
@Rukario For the LLE modules manager, there's no need to specify, that it's a window.
Also, why big no to "You must restart your emulated game or application for changed settings to take effect"?
I also think some terms were possibly replaced with worse ones.

**Comment by vgturtle127** [comment]
Which terms do you guys really hate?

I don't get why directional pad, virtual hard drive manager, and DirectX 12 primary adapter are being shunned out of all of them. I assumed this would bring more clarity to the UI.

I mean, it's your project and all, but I didn't expect as much resistance to this as opposed to some code changes I wanted to make. :smiley:

**Comment by paulsapps** [comment]
Lower-casing secondary words is more "correct" Having Everything Like This Is Kinda Strange.

**Comment by Zangetsu38** [comment]
Forget this issue, I have a banned.... for thy help project rpcs3...

**Comment by vgturtle127** [comment]
@Zangetsu38 What? I'm sorry, I'm not understanding what you are trying to say.

You were banned for something?

**Comment by tambry** [comment]
@vgturtle127 https://github.com/RPCS3/rpcs3/pull/1347#issuecomment-166130978

**Comment by vgturtle127** [comment]
Alright, I suppose this can be closed then.

**Comment by tambry** [comment]
@vgturtle127 I don't think there's any reason to close this, as someone may be able to properly implement these changes in the future.

**Comment by vgturtle127** [comment]
Well, I just wanted to change the text so the English was better and more understandable. Is that really a big contribution? I thought it would be a simple text change. I can do it, I just need to be told what is acceptable.

**Comment by raven02** [comment]
Probably we can have something similar to PPSSPP that customize language file , so everyone can have their own naming . i'm closing this for now as it has been over half year no update here.
