### ISSUE TITLE
[NPUB30554] Oddworld Strangers wrath stuck at black screen 

### ISSUE THREAD

**Issue by Scalerize** [RPCS3/rpcs3#13124]
### Quick summary

after the ppu compilation windows closes.  the screen turns black. after that rpcs3 gets stuck forever on a black screen with absolutely no signs of audio or video.

### Details

on a ps3 it would start without a black screen. also note that other regions seem to work fine.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10300682/RPCS3.log.gz)

### System configuration

Default settings with write color buffers being enabled

### Other details

![untitled](https://user-images.githubusercontent.com/98698811/209483116-aa12594c-57d1-4468-bab5-540f2e9e7cba.PNG)

**Comment by AniLeo** [comment]
No issue on my end with the EU version

**Comment by Scalerize** [comment]
> No issue on my end with the EU version

It's also very strange since every other game i have works perfectly and there are all backups from the same console so i honestly don't think it's an issue with data corruption

**Comment by benderscruffy** [comment]
goes ingame for myself
![Capture](https://user-images.githubusercontent.com/2696404/209545659-3afba047-c437-4a2e-9457-8670b8ed57a6.PNG)

**Comment by Scalerize** [comment]
> goes ingame for myself ![Capture](https://user-images.githubusercontent.com/2696404/209545659-3afba047-c437-4a2e-9457-8670b8ed57a6.PNG)

Can i ask what update you're using ?

**Comment by benderscruffy** [comment]
I'm using the standard v1.00

**Comment by Scalerize** [comment]
> I'm using the standard v1.00 don't think there is a v2.00 update just found the latest update is 1.02 and it still goes ingame for myself
![untitled](https://user-images.githubusercontent.com/98698811/209677610-7704e4af-2d4a-4265-8e41-2145c3734356.PNG)

then do explain this

**Comment by Darkhost1999** [comment]
It's quite easy to modify your game to show whatever you want it to show.
Just observations from a game update database made by aldostools only shows update 1.02 as that other person said.
![Screenshot_20221227-081042_Chrome.jpg](https://user-images.githubusercontent.com/60384196/209678652-6a229985-f96e-4f44-8e27-122b648719bf.jpg)

I would check your PKG file for your game using <https://wiki.rpcs3.net/index.php?title=Help:Validating_PlayStation_3_game_dumps#Validating_PSN_games> just to cross the T's and dot the I's that your game isn't the problem rather than RPCS3.

**Comment by Scalerize** [comment]
> It's quite easy to modify your game to show whatever you want it to show. Just observations from a game update database made by aldostools only shows update 1.02 as that other person said. ![Screenshot_20221227-081042_Chrome.jpg](https://user-images.githubusercontent.com/60384196/209678652-6a229985-f96e-4f44-8e27-122b648719bf.jpg)
> 
> I would check your PKG file for your game using https://wiki.rpcs3.net/index.php?title=Help:Validating_PlayStation_3_game_dumps#Validating_PSN_games just to cross the T's and dot the I's that your game isn't the problem rather than RPCS3.

then i'll close it as a data corruption issue.

**Comment by AniLeo** [comment]
Confirmed with update data, there's no v2.00, closing as invalid
