### ISSUE TITLE
[AMD RDNA 3 GPU] Uncharted 3 graphics errors (multiple small colorful areas)

### ISSUE THREAD

**Issue by lseurttyuu** [RPCS3/rpcs3#13130]
### Quick summary

Uncharted 3 [BCES01175 1.19, no community patches applied] shows multiple graphics errors when RDNA 3 GPU is installed. The issue is hardware-related or driver-related as it doesn't appear on Nvidia GPU (GTX 1660 Ti Mobile) or AMD RDNA 2 GPU (RX 6800 XT). A workaround may be needed.

### Details

The issues are :

1. In the main menu a "halo" - it appears a few times in every second (sort of flickering).

![halo](https://user-images.githubusercontent.com/56368375/209577714-93ef00a6-3537-4929-aeb6-43d7f2aaaacf.png)

2. During the game - multiple tiny colorful areas. They look very similar to these mentioned at https://github.com/RPCS3/rpcs3/issues/6999#issuecomment-651561689 (though the user used community patches there, so it's not the same situation).

![amd_game](https://user-images.githubusercontent.com/56368375/209577881-d959bf54-159f-418c-a27c-fea34e8fd886.png)

These artifacts are amplified when pausing the game:

![amd_menu](https://user-images.githubusercontent.com/56368375/209577933-816bdb87-12bb-4819-a683-60c050e5625f.png)

As a side note, when using patches, these artifacts evaluate into colorful RGB-like big squares (I know, community patches are not tracked here, but I believe it's directly connected to this issue - treat it just as an additional information):

![unknown_2022 12 17-22 19_1](https://user-images.githubusercontent.com/56368375/209578027-679e9c5f-b849-4588-bdc6-8a37648693e8.png)

I validated the issue using my second PC (with RX 6800 XT GPU) and my third PC (with GTX 1660 Ti Mobile GPU) and it's not there (the "halo" is not visible as well and community patches do not produce big square artifacts):

![nv_game](https://user-images.githubusercontent.com/56368375/209578123-f716c341-f04c-43e0-8366-683af46b5071.png)

![nv_menu](https://user-images.githubusercontent.com/56368375/209578130-43055039-8e99-4c57-8b85-118b12968a9b.png)

So, as a conclusion - the same game with the same RPCS3 with the same configuration on a different hardware produces different image, one of them being corrupted.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10304598/RPCS3.log.gz)

### Attach capture files for visual issues

[In order to unzip the capture, please remove ZIP extensions at the end of files]
[BCES01175_20221226195006_capture.zip.001.zip](https://github.com/RPCS3/rpcs3/files/10304627/BCES01175_20221226195006_capture.zip.001.zip)
[BCES01175_20221226195006_capture.zip.002.zip](https://github.com/RPCS3/rpcs3/files/10304629/BCES01175_20221226195006_capture.zip.002.zip)

### System configuration

CPU: Ryzen 9 5950X
RAM: 32 GB
GPU: AMD RX 7900 XTX (driver version 22.12.2)
Operating system: Windows 10, 21H2 (19044.2130)

### Other details

No community patches were used (unless specified). Recommended configuration was set up (Resolution scale: 100, Write color buffers: On, Accurate RSX reservation access: On, Read color buffers: On, RSX FIFO accuracy: Atomic).
I checked Uncharted 1 game as well [BCES00065] and the "halo" issue is present there as well while it's not present on the other hardware. That indicates RDNA 3 GPUs / drivers are partially broken or they need some kind of workarounds.

**Comment by kd-11** [comment]
Check if https://github.com/RPCS3/rpcs3/pull/13131 fixes this.

**Comment by kd-11** [comment]
For context, the artifacts are caused by DCC optimization during a self-referencing pass (aka fbo loops). There is an extension to fix this supported by Mesa and NVIDIA but not AMD proprietary yet.

**Comment by lseurttyuu** [comment]
> Check if #13131 fixes this.

I updated RPCS3 to version 0.0.25-14503-908d5246 Alpha.

The issue still persists, I did not notice any change. I checked it twice, before and after removing all caches. Interesting...

**Comment by kd-11** [comment]
I think AMD now uses compression for all resource modes with rdna3. You have to use strict rendering mode to get around the issue for now.

**Comment by solarmystic** [comment]
Also seems to affect other Naughty Dog games like The Last of Us, based on feedback from discord. 

User upgraded from a Vega 56 to a 7900XTX and using the same exact settings and patches, encountered similar graphical issues. 

https://discord.com/channels/272035812277878785/277227681836302338/1057129836449112154

**Comment by lseurttyuu** [comment]
I can confirm the issue is present in The Last Of Us as well [BCES01585]. On the contrary, the issue doesn't appear in Uncharted 2 at all. Uncharted 2 doesn't have in-built MLAA... maybe there's something about it?



> I think AMD now uses compression for all resource modes with rdna3. You have to use strict rendering mode to get around the issue for now.

I see. Are there any foreseeable viable solutions/fixes to this problem that could be implemented within RPCS3? Or is it a bit of a dead end for now (except for strict rendering mode, which - to my surprise, works pretty well, the biggest caveat being lack of resolution scaling)?

**Comment by kd-11** [comment]
Strict rendering mode implements the spec-compliant solution but scales very poorly. Essentially instead of introducing a resource loop we make extra copies every draw call that needs it. At 720p its fine, but with upscaling the cost increases exponentially.
To remedy this, a [vulkan extension](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_attachment_feedback_loop_layout.html) was proposed to allow the client application to request decompression using a layout enum. This is still new-ish so not available on the current vulkan driver from AMD. When support for it lands the problem should just go away.

**Comment by kd-11** [comment]
@lseurttyuu Could you grab a vulkaninfo dump on the latest available driver for the 7000 series cards? There isn't much information on the supported features with the launch drivers for this card. Also check if AMD have an updated beta driver for it.

**Comment by lseurttyuu** [comment]
Sure, here is vulkaninfo dump (txt and html) for AMD RX 7900 series:

[vulkaninfo.txt](https://github.com/RPCS3/rpcs3/files/10311173/vulkaninfo.txt)
[vulkaninfo.zip](https://github.com/RPCS3/rpcs3/files/10311174/vulkaninfo.zip)

Vulkaninfo produces 3 warnings (probably not relevant):
`WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)`
`WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)`
`WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)`

Used driver version: Adrenalin 22.12.2 for Radeon RX 7900 Series (WHQL) (release date: 20.12.2022)

For the time of writing this comment these are the latest drivers for RX 7900 series cards. There are no newer / beta / non-WHQL drivers. It's worth mentioning now RX 7900 drivers is a different branch of AMD drivers (separated from drivers for all older GPUs).

**Comment by kd-11** [comment]
Thanks. As I suspected, the extension is missing on this driver. I guess we just wait for this to merge with the main driver branch and we'll get the extension for free. It already is present in 6000 series branch.

**Comment by lseurttyuu** [comment]
They should do it sooner than later, I suppose in a month or two at most. I'll be revalidating the issue with every new AMD RX 7900 drivers release and report my findings here.

**Comment by AniLeo** [comment]
Can you retest on 23.1.1? Should be fixed

**Comment by lseurttyuu** [comment]
New driver released 24.01.2023 (Adrenalin Edition 23.1.2 for AMD Radeon RX 7900 Series Graphics) fixes the issue as the missing Vulkan extension has been added.
