### ISSUE TITLE
"Verification failed" error trying to boot from savestate for MGS4

### ISSUE THREAD

**Issue by quickishfm** [RPCS3/rpcs3#13135]
### Quick summary

In Metal Gear Solid 4 (BLUS30109) after saving the state and trying to boot from it, the following error occurs

Verification failed
(in file ../rpcs3/Emu/Cell/lv2/sys_overlay.cpp:84, in function load) (errno=2=No such file or directory

Once this happens the whole RPCS3 application is completely unresponsive and I have to kill it and relaunch. The savestate file itself does exist in .cache/rpcs3/savestates (without the file there isn't any option to boot the savestate anyway, as expected).

I'm using Arch Linux (6.1.1-arch1-1) with a Ryzen 3800x, Nvidia GTX 1080Ti GPU and Ryzen 3800x CPU.

### Attach a log file

https://controlc.com/754b13a4

**Comment by elad335** [comment]
I need a log of when saving as well.

**Comment by elad335** [comment]
Retry on latest master

**Comment by quickishfm** [comment]
Let me give it a go and I'll update back here shortly.

**Comment by quickishfm** [comment]
I'm now getting a segfault trying to boot from the savestate
```
RPCS3: Emu State Load Thread: '': SIG: Thread terminated due to fatal error: Verification failed
(in file /rpcs3/rpcs3/util/serialization_ext.cpp:376[:3], in function handle_file_op) (errno=12=Cannot allocate memory)
RPCS3: Emu State Load Thread: '': profiler: cpu_thread::flush_profilers() has been called incorrectly.
RPCS3: Emu State Load Thread: '': SYS: 
Segfault reading location 0000000000000000 at 0000000000f55d2c.
Thread: Main Thread.

RPCS3: Emu State Load Thread: '': SIG: Thread terminated due to fatal error: Segfault reading location 0000000000000000 at 0000000000f55d2c.
Thread: Main Thread.

RPCS3: Segfault reading location 0000000000000000 at 0000000000f55d2c.
Thread: Main Thread.

Title: "METAL GEAR SOLID 4 GUNS OF THE PATRIOTS [BLUS30109]" (emulation is running)
Build: "0.0.29-15898-4068423c Alpha | HEAD"
Date: "2024-01-01T17:19:19"
Debugger: 0
Aborted (core dumped)
```

but I don't see "Verification Failed" anymore.

**Comment by elad335** [comment]
Upload full log

**Comment by jedinjapan** [comment]
MGS4 - NPUB31633

New savestates made on each version and loaded in the same version, just save and loading on the main menu to test basic functionality.

0.0.27-14845 - Working Save States (uncompressed).
0.0.27-14853 - Working Save States (uncompressed).
**0.0.27-14854 - Last version with working save states in this title.**
0.0.27-14855 - Not working (uncompressed) - crashes attempting to save.
0.0.27-14857 - Does not boot - unrelated possibly
0.0.27-14873 - Does not boot - probably unrelated
0.0.27-14886 - Not working (uncompressed) - crashes attempting to save.
0.0.27-15090 - Not working (uncompressed) - crashes attempting to save.
0.0.28-15409 - Not working (uncompressed) - On load,  CellSpursKernel0 error
0.0.29-15661 -  Not working (uncompressed) On load - no error, program crash
0.0.29-15809 - Not working (compressed) On load - audio decoder error
0.0.30-15968 - Not working (compressed) On load - no error, program crash 

On latest build (0.0.30-15968), emulation hangs when attempting to save state (Ctrl+S) and no log is generated. 

Possibly related to this issue as well:
https://github.com/RPCS3/rpcs3/issues/13899

**Comment by jedinjapan** [comment]
Logfile for latest build crash-on-load.

rpcs3-v0.0.30-15968-e23db7ef

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13987728/RPCS3.log)
