### ISSUE TITLE
controls issue

### ISSUE THREAD

**Issue by Zulthar** [RPCS3/rpcs3#13142]
### Quick summary

can't press both L2 and R2 at the same time, it doesn't register

### Details

I did check with other emulators and with non-emulated games, my controller can definitely do both of those inputs simultaneously

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10320790/RPCS3.log)

**Comment by Megamouse** [comment]
Not a bug.
You're using the mmjoy handler which does put both triggers on the same axis
