### ISSUE TITLE
NCAA 14 keeps crashing after it reaches the start menu

### ISSUE THREAD

**Issue by jab314** [RPCS3/rpcs3#13144]
### Quick summary

RPCS3 is crashing whenever i load up NCAA 14. It worked when i first installed it but now it cant even reach the start menu. I dont know if its something I did thats fixable or what. 

### Details

This shows in the log on RPCS3 before I even load it up:

E GameList: Invalid disc path found in /Users/jab/Library/Application Support/rpcs3/dev_hdd0/disc/BLUS31159- [NCAA Football 14]

Then I get errors regarding my GPU after I do load it up that I wasn't getting previously so I don't think my graphics card is outdated.

### Attach a log file

https://www.dropbox.com/s/536krfw1j0nvmhm/RPCS3.log.gz?dl=0 

### System configuration

iMac, Retina 4k, 21.5 inch, 2019

3.6 GHz Quad-Core Intel Core i3
Radeon Pro 555x 2 GB
8 GB 2400 MHz DDR4
Macintosh HD
macOS 13.1 (22C65)

### Other details

I tried tweaking a lot of settings in the configuration panel when i first downloaded the game due to the audio being bad and it has not been the same since. Just thought that would be important to know. I read that my game folder needs to be in my dev_hdd0 folder but Im not able to move it when i try. Im thinking that might also have something to do with it. Am I just going about it wrong? I feel like this is a minor problem but I just cant figure it out have been at it for three days just trying to play this game again any help is appreciated.

**Comment by AniLeo** [comment]
Log file is empty but this is not a valid issue report, this is a support request, as such, this needs to be filed in one of the support platforms as indicated on the support guidelines.

https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support
