### ISSUE TITLE
SDL - only 1 controller displayed when using 2 controllers that have same DeviceName

### ISSUE THREAD

**Issue by Tartifless** [RPCS3/rpcs3#13140]
### Quick summary

When using 2 controllers that have the same SDL DeviceName, only 1 controller will be seen by rpcs3, as only the devicename is used as identifier.
DeviceIndex (SDL index) should be added after or before the DeviceName to be able to use multiple controllers of same name.

### Details

rpcs3 config file screenshot:
![image](https://user-images.githubusercontent.com/13442986/209887811-49000ba0-d5c9-42d9-b3fb-28a28ad9fd87.png)

In the rpcs3 gamepad config screen when using SDL handler:
![image](https://user-images.githubusercontent.com/13442986/209887848-02db2b9b-3572-4e7e-9d09-615b5ca2aa36.png)

In the rpcs3 gamepad config screen when using MM handler:
![image](https://user-images.githubusercontent.com/13442986/209887862-b25ec3ce-7828-47e9-ba84-a8829cf0710b.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10317036/RPCS3.log)

**Comment by jokoputera** [comment]
I think this is also affect my controller. As far as i know, this only affect 1 game so far that cant be use MMJoystick. But strangely enough, my previous RPCS3 (using my old harddrive, just run it without reinstall RPCS3) work.
If you need log files please let me know

**Comment by Megamouse** [comment]
This is a known behaviour and simply unimplemented

**Comment by Tartifless** [comment]
Hi Megamouse, was this answer for me or for jokoputera ?

**Comment by Tartifless** [comment]
Hello, 
Is there any plans to implement this or not yet ? Adding the sdlindex before the joystick name could be used.

**Comment by Megamouse** [comment]
I completely forgot about this.
Maybe I'll look into it over the weekend

**Comment by Megamouse** [comment]
try with #13999

**Comment by Tartifless** [comment]
Thanks, will test before tuesday

**Comment by Tartifless** [comment]
I just saw that the PR is not merged yet...

**Comment by MSuih** [comment]
If you want to test an open pr you have to download it separately.
[Follow the instructions in here](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_download_builds_from_a_pull_request_on_GitHub?).

**Comment by Tartifless** [comment]
Ok, back to tests:
- Configuration of pads: ==> OK
![image](https://github.com/RPCS3/rpcs3/assets/13442986/6f86e4e6-3075-4c92-875d-a7ec744e1e37)
Both pads work independently when set as player 1 and player 2

- In default.cfg file:
All is fine:
![image](https://github.com/RPCS3/rpcs3/assets/13442986/5a9347c4-e68e-4182-a249-aad50fdf2c7e)

- It works also in-game: both controllers work fine

**Comment by Megamouse** [comment]
Thanks for testing!

**Comment by ThunderWahi** [comment]
Hi I’m lost on how to access the config file and change the device names

**Comment by Tartifless** [comment]
> Hi I’m lost on how to access the config file and change the device names

I am sorry, i do not understand your question ... It's not possible to change the device name, as this is defined by the SDL library.

**Comment by ThunderWahi** [comment]
Then how do you use 2 Xbox controllers, how do you differentiate them so they have different names under the sdl.

**Comment by Tartifless** [comment]
They will have the same name if it's the same controllers but a different index number, the first will have index 1, the second index 2, and so on.

But for xbox controllers you should use xinput, not sdl.
