### ISSUE TITLE
Call of Duty 3 [BLES00016] - Invisible trees

### ISSUE THREAD

**Issue by Blackbird88** [RPCS3/rpcs3#13157]
### Quick summary

- The level is [The Forest](https://callofduty.fandom.com/wiki/The_Forest)
- Trees are only visible through a sniper scope from certain distances/angles
- I have tried all the options that I could (some crash the game for some reason)

### Details

https://user-images.githubusercontent.com/4414625/210175518-b9eab80c-9947-468f-9ed7-145f40bdfbb4.mp4

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10328984/RPCS3.log.gz)

### Attach capture files for visual issues

[BLES00016_20230101161336_capture.zip](https://github.com/RPCS3/rpcs3/files/10328980/BLES00016_20230101161336_capture.zip)
[BLES00016_20230412080250_capture.zip](https://mega.nz/file/F3oV0ChR#jts3lbzyWdX1OlBae_yTL1tdwwu4CI9OsOItSQzyE_g)

### System configuration

Windows 11 64-bit
Intel Core i7-10700K
Nvidia GeForce RTX 3070 (527.56)
32 GB RAM

### Other details

Savegame of the mission:
[BLES00021-AUTO-.zip](https://github.com/RPCS3/rpcs3/files/10328991/BLES00021-AUTO-.zip)

**Comment by kd-11** [comment]
Please retest, the issue appears to be fixed (looking at the replay in tracing tools).

**Comment by kd-11** [comment]
It's highly possible this is the same iw engine bug we recently fixed. I'll close proactively, if it's still broken, ask to reopen.

**Comment by Blackbird88** [comment]
Still happens to me with ![image](https://user-images.githubusercontent.com/4414625/231364558-4811db8c-84bd-4d9e-8fc0-153085bfb213.png)

**Comment by kd-11** [comment]
@Blackbird88 I'll need a save for this level.

**Comment by Blackbird88** [comment]
> @Blackbird88 I'll need a save for this level.

It's in OP under **Other details**

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/13665

**Comment by Blackbird88** [comment]
Works! Thank you for fixing it! :)
