### ISSUE TITLE
Installing a PKG file that overwrites lower case files with upper case files does not work. 

### ISSUE THREAD

**Issue by Splicewave** [RPCS3/rpcs3#13156]
Continuing on from Issue #13113, the implemented fix was a step in the right direction as it did fix one of the 2 problems but one problem still remained which I have discovered more about since before. So lets say inside a game there is a file called main.lua (located in USRDIR/MINIGAMES/guitarhero4/rockgod/main.lua) and then I install a PKG file that contains that file & folders but in CAPS like this:  USRDIR/MINIGAMES/GUITARHERO4/ROCKGOD/MAIN.LUA 
It will cause the PKG installation to cancel and say it is likely caused by antivirus software (I tested this with my anti virus including windows defender turned off)
Hopefully this can be fixed to allow PKG files to overwrite files & folders in lower case to upper case if this is how they are in the PKG file for the game. Thankyou.

**Comment by elad335** [comment]
Log please.

**Comment by elad335** [comment]
Also it's not overwriting, unix allows different files which only differ by case (as PS3 filesystem is based on). This is not the case Windows.

**Comment by Splicewave** [comment]
uploading log in a few minutes.

**Comment by Splicewave** [comment]
![image](https://user-images.githubusercontent.com/71703832/210168399-d72fdee1-9f06-47e2-b23f-0f3a3a5ed47c.png)

What it says in logs:
- SYS: RPCS3 v0.0.25-14517-310fa712 Alpha | master
- SYS: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz | 8 Threads | 15.97 GiB RAM | TSC: 4.008GHz | AVX+ | FMA3 | TSX-FA disabled by default
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-01- 1T10:59:49
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1080' running on driver 516.94.0.0
- SYS: Firmware version: 4.89
S UPDATER: RPCS3 is up to date!
E PKG: Failed to create file D:/PlayStation Home/dev_hdd0/game/NPIA00010/USRDIR/MINIGAMES/GUITARHERO4/ROCKGOD/MAIN.LUA
E PKG: Package installation failed: D:/PlayStation Home/dev_hdd0/game/NPIA00010/
E GUI: Failed to install PSH_OFFLINE_UPDATE_3_12.pkg.

RPCS3 log file:
[rpcs3.log](https://github.com/RPCS3/rpcs3/files/10328647/rpcs3.log)

**Comment by Splicewave** [comment]
I have tested this on the latest version of RPCS3 after seeing updates that PKG installation has been improved and it now works! Closing this now
