### ISSUE TITLE
[Regression] Trinity Souls of Zill O'll Graphical Issue

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13167]
### Quick summary

When moving to the second location in the demo the floor seems to be missing.

### Details
RPSC3(Before):
![NPEB90318_screenshot_2023_01_26_22_45_37](https://user-images.githubusercontent.com/71127352/214970696-7cb44a03-4020-4f5b-b3ce-a9f379cae1ad.png)

RPSC3(After):
![image](https://user-images.githubusercontent.com/71127352/210668274-9388ef09-7ab7-405a-aa61-b27b752c7fbf.png)

PS3:
https://youtu.be/dZO2nfK7UrY?t=754

### Build with regression
v0.0.24-14127-5985f0ee

### Attach two log files
[Trinity Souls of Zill O'll(Before).log.gz](https://github.com/RPCS3/rpcs3/files/10514161/Trinity.Souls.of.Zill.O.ll.Before.log.gz)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10524020/RPCS3.log.gz)

[Trinity Souls of Zill O'll(After).log.gz](https://github.com/RPCS3/rpcs3/files/10514162/Trinity.Souls.of.Zill.O.ll.After.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1OyLCnNzEYgFX6aEgakiP26M_VTCDzIFL/view?usp=share_link (renderdoc)

Before
https://drive.google.com/file/d/1iIfrimg_Y2SYhUkWt7DP9McV8yVj48LG/view?usp=share_link
After
https://drive.google.com/file/d/1IYVbmeq0i9a3YnFtvXYyMfb1_2VPQmfc/view?usp=share_link
### System configuration

    SYS: RPCS3 v0.0.25-14478-812224f7 Alpha | master
    SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
    SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
    SYS: Current Time: 2022-10-28T21:53:46
    RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 526.47.0.0
    SYS: Firmware version: 4.89

### Other details

Note 2023/01/26: Did'nt do my due diligence when filing the report and I now know this is a regression. Kd-11 I have added some rsx capture now. I would like to mention window seems to have an issue when creating capture causing the capture to crash the emulator so both the Rrc are made on Linux.

**Comment by VittoScaletta** [comment]
I tried asking for help once but apparently I had to search for the latest build, try using an older build, I did 100% that way

**Comment by kd-11** [comment]
RSX capture trace is needed @Triticum0 
From the main window go to Utilities -> Create RSX capture. A file will be generated in the captures folder, check the log windowd for the exact filename. RSX trace is device-agnostic unlike renderdoc so we can check how the scene behaves on other GPUs.

**Comment by Triticum0** [comment]
@kd-11 Like I mentioned #13165 when I create a rsx capture on this game when I open the RSX capture the file it crashes the emulator with F {RSX [0x100000b4]} SIG: Thread terminated due to fatal error: Unknown surface antialiasing format 0x6
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\gcm_enums.cpp:24[:23], in function throw_exception_if_emulating)

https://drive.google.com/file/d/1GUqbivdDpm722piRU1VBLqI_U-c0aN3k/view?usp=share_link

**Comment by Triticum0** [comment]
Fixed by #13665

**Comment by kd-11** [comment]
Thanks for verifying.
