### ISSUE TITLE
Fracture Graphical Issues

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13163]
### Quick summary

The gun effect when your terraform weapon, the entrencher, is shoot seems to have green artefacts coming out of the weapon this also affects other objects as well.

### Details

RPCS3:
![image](https://user-images.githubusercontent.com/71127352/210618179-fe9e23ef-425a-4219-8ff1-4b99a560359b.png)
![image](https://user-images.githubusercontent.com/71127352/210643554-a6ccc4a3-f746-4ada-851b-2e63c7541fd2.png)

PS3:
https://youtu.be/z7uGhmfaHT8?t=18

### Attach a log file

[RPCS3(1).log.gz](https://github.com/RPCS3/rpcs3/files/10346327/RPCS3.1.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1mHbX-9XJRJGGk_DLRV5bRcYR2UL2wIqr/view?usp=share_link

### System configuration

    SYS: RPCS3 v0.0.25-14478-812224f7 Alpha | master
    SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
    SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
    SYS: Current Time: 2022-10-28T21:53:46
    RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 526.47.0.0
    SYS: Firmware version: 4.89

**Comment by VittoScaletta** [comment]
It solved it for me after messing with it, I changed SPU Xfloat Accuracy to Approximate Xfloat and Zcull accuracy to Precise + Write Color Buffers!

**Comment by Asinin3** [comment]
Both Approximate Xfloat and Precise Zcull Accuracy are the default emulator settings. Closing as resolved regardless
