### ISSUE TITLE
Freeze Skyalnders Giants

### ISSUE THREAD

**Issue by McWalters00** [RPCS3/rpcs3#13169]
### Quick summary

when i launch skylanders giants all goes well then at one point of the game it freezes

### Details

the game freezes randomly there is no distinctive moment to know why it crashed and then the game page is removed and the software puts this
![Capture](https://user-images.githubusercontent.com/96343387/210771035-2db2b9b8-15a0-419c-96e3-3ca45a9895e2.PNG)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10351756/RPCS3.log)

### System configuration

CPU : Intel core I7 6800HQ
GPU : AMD Radeon pro 455
16gb ram

**Comment by RipleyTom** [comment]
Try setting RSX FIFO accuracy to `Atomic`, it's in Configuration=>Advanced=>On the right.

**Comment by McWalters00** [comment]
> Try setting RSX FIFO accuracy to `Atomic`, it's in Configuration=>Advanced=>On the right.

Thank you, I’ll try

**Comment by Asinin3** [comment]
Closing, no updates from OP
