### ISSUE TITLE
Support for non-sony PS4 controllers on Mac - wireless / bluetooth pads

### ISSUE THREAD

**Issue by ilovesafaristand** [RPCS3/rpcs3#13161]
### Quick summary

https://github.com/RPCS3/rpcs3/issues/11485 was closed but users reports it not working as I am.

EasySMX ESM-9110 USB wireless Bluetooth and cable not working on Intel Mac
Nothing detected under SDL

rpcs3-v0.0.25-14517-310fa712_macos

### Attach a log file

NA

### System configuration

iMac

### Other details

iMac

**Comment by AniLeo** [comment]
No log file no macOS version, no hardware specifications, missing everything

**Comment by Megamouse** [comment]
closing as invalid
