### ISSUE TITLE
[Feature request] Gamelist navigation and start/stop with controller

### ISSUE THREAD

**Issue by nativemad** [RPCS3/rpcs3#13173]
### Quick summary

Hi
It would be great, if it would be possible to navigate through the gamelist and start and stop games with the controller.

### Details

The experience when gaming from the couch would be hugely improved, if everything could be done via controller.
As of now, for selecting a game, starting and stopping it, the mouse or keyboard is required.
A hotkey for stopping the emulation like  select+start for 3 seconds or such would be awesome.

Thanks for the great work!

**Comment by RainbowCookie32** [comment]
There's #5444 and #12539

**Comment by nativemad** [comment]
Thank you! :-)
