### ISSUE TITLE
AppImage doesn't run on Wayland

### ISSUE THREAD

**Issue by krasmazov483** [RPCS3/rpcs3#13171]
### Quick summary

I was having a segfault with my Nvidia dGPU on the Flatpak of RPCS3 when running on Wayland, so I tried the official AppImage, which only starts through XWayland, with an error on the terminal followed by the whole application crashing. Everything works perfectly through XWayland here.

After that I decided to follow the recommendation to install RPCS3 from source by the flatpak's mantainers to see if those problems persisted, but I found yet another error, which is probably best to make another issue about.

### Details

On the Flatpak, my Intel iGPU was working fine, Nvidia only ran through XWayland where the only other issue is screen tearing, probably driver related. Demon's Souls and the PS3 Main menu were both crashing independently too.

On the AppImage I get this error on the terminal when trying to open in Wayland:
`qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""`

When building from source, this is the error I get when trying to start any game through Wayland:

![Screenshot_20230105_204925](https://user-images.githubusercontent.com/9277125/210902217-cfba179d-a037-432e-a46a-e22faa0ac798.png)

The text at the right side of the window translates to something like "no such file or directory". Through XWayland everything works as expected.

### Attach a log file

Built from source: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10356368/RPCS3.log)

### System configuration

Hybrid Intel/Nvidia Laptop:
CPU: i7 6700HQ
iGPU: Intel HD Graphics 530
dGPU: Nvidia GTX 960M
RAM: 12GB

**Comment by clienthax** [comment]
https://github.com/RPCS3/rpcs3/issues/12102#issuecomment-1139545751

**Comment by qurious-pixel** [comment]
@Khrona98 you are getting the error message from the AppImage because it is missing `libwayland-client.so` and the Qt Wayland plugins.

If you are building from source using your Nvidia GPU, ensure the vulkan drivers are fairly recent. Install the libwayland development package for your distro and the Qtwayland module. This will install the following files/folders in the relative directory.

```
plugins/platforms/
libqwayland-egl.so
libqwayland-generic.so
libqwayland-xcomposite-egl.so
libqwayland-xcomposite-glx.so

plugins/wayland-decoration-client/
*

plugins/wayland-shell-integration/
*

plugins/wayland-graphics-integration-client/
*

usr/lib/libwayland-client.so
```

**Comment by Khrona98** [comment]
> @Khrona98 you are getting the error message from the AppImage because it is missing `libwayland-client.so` and the Qt Wayland plugins.
> 
> If you are building from source using your Nvidia GPU, ensure the vulkan drivers are fairly recent. Install the libwayland development package for your distro and the Qtwayland module. This will install the following files/folders in the relative directory.
> 
I do seem to have all these packages already installed, so that can't be the problem unless the application just can't find them on my system for some reason, right?

**Comment by qurious-pixel** [comment]
`qt.conf` will set the paths to locate the plugins.

On the Appimage it is located in `usr/bin/qt.conf` with the plugins in `usr/plugins/`

**Comment by Khrona98** [comment]
I took a look on the extracted AppImage, the `qt.conf` file inside the AppImage points to the bunbled plugins, manually changing it to point to my installed ones makes no difference, still can't initialize natively on Wayland, this time with a different error: `qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.`

Does the AppImage simply not have Wayland support then? Building RPCS3 locally does but gives out the error I pointed in the OP, even when built on my main desktop which is full AMD, tho it is a different one: `Verification failed (in file /home/jojo/Documents/Local/rpcs3/rpcs3/Emu/Memory/vm.cpp:1264, in function ~block_t) (errno=11=Resource temporarily unavailable)`.

**Comment by qurious-pixel** [comment]
To use the appimage as a base, it has to be extracted, with the directories mentioned placed in the plugins path. I replaced the Qt5 libs in the lib directory as well. RPCS3 is built using Qt 5.15.2, so should have matching version, or you will receive a mismatch warning.

**Comment by Khrona98** [comment]
> To use the appimage as a base, it has to be extracted, with the directories mentioned placed in the plugins path. I replaced the Qt5 libs in the lib directory as well. RPCS3 is built using Qt 5.15.2, so should have matching version, or you will receive a mismatch warning.
> 
> I also repackaged the AppImage to test it worked.

For Qt5 I have 5.15.8 installed on my system, but I'm not receiving a version mismatch warning/error. But even after copying all the files and folders you mentioned I still have the same `qt.qpa.plugin` error.

Also, I believe it would be better for the end user if the AppImage came bundled with the needed files for proper Wayland support if possible, specially since I still can't get RPCS3 built from source to work with Wayland, even tho the Flatpak does, but with the issues I mentioned before, plus a few others like crashing every time I quit a game or make a savestate.

**Comment by qurious-pixel** [comment]
@Khrona98 Just an Update:
https://github.com/qurious-pixel/rpcs3/releases/tag/Qt6

AppImage packaged with Wayland Support

**Comment by kd-11** [comment]
Superceded by https://github.com/RPCS3/rpcs3/issues/14576. We moved to Qt6 in the interim.
