### ISSUE TITLE
Bioshock infinite crash during main menu with infinite fps (no pun intended)

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#13181]
### Quick summary

Bioshock infinite sometimes crashes during main menu if you wait a bit in this menu.
The errors may be different each time with infinite fps.

![image](https://user-images.githubusercontent.com/23019877/211170643-b65b12eb-c133-4c44-a45d-c967e179fc8f.png)

### Details

First log:
·F 0:01:20.344998 {RSX [0x05bf574]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Program\ProgramStateCache.cpp:57[:4], in function operator ())

Second log:
F {RSX [0x04aba44]} SIG: Thread terminated due to fatal error: rsx::get_address(offset=0x5b0de80, location=0xff): Invalid location!
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\texture_cache.h:2080[:30], in function upload_texture)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\RSXThread.cpp:246[:23], in function get_address)

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/10367197/RPCS3.zip)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/10367208/RPCS3.zip)

**Comment by Megamouse** [comment]
On second thought it may be some other option causing this. let me check

**Comment by Megamouse** [comment]
nah. it also crashes if i only change the fps to infinite (I'll also try complete default)

**Comment by Megamouse** [comment]
seems to be related to infinite fps

**Comment by kd-11** [comment]
Closing as it is triggered by a hacky setting.
