### ISSUE TITLE
Dualshock 4 led control not working

### ISSUE THREAD

**Issue by leosanvieira** [RPCS3/rpcs3#13185]
### Quick summary

Dualshock 4(Dualshock 4 handler) is working but the led does not change color.

### Details

Dualshock 4(Dualshock 4 handler) is working but the led does not change color. I have DS4Windows in my PC but i do not use it with rpcs3 but i use HidHide and added rpcs3 as an exception.

Dualshock 4 Model: CUH-ZCT2U

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10395192/RPCS3.log)

**Comment by Megamouse** [comment]
missing log file

**Comment by leosanvieira** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10387453/RPCS3.log)
New log file created with the latest rpcs3 update attached.

**Comment by RipleyTom** [comment]
Afaik DS4Windows always runs in the background as a service. Try uninstalling it completely and then if the issue persists reopen this issue. There is not much we can do for 3rd party interference.

**Comment by leosanvieira** [comment]
But DS4Windows can't be installed, it's just a .exe run from it's own folder, and the led control works using the SDL handler so i still think it's an issue with the Dualshock 4 handler.

**Comment by RipleyTom** [comment]
The led actually worked in-game but there was indeed a bug in the configuration window.
Megamouse fixed it and it should now work, sorry for closing it too fast.
