### ISSUE TITLE
Eternal Sonata

### ISSUE THREAD

**Issue by kenshinmokota** [RPCS3/rpcs3#13184]
### Quick summary

game boots to a blackscreen while hearing the games's start up tune
cant play ofcourse since its all black

### Attach a log file

- SYS: RPCS3 v0.0.26-14525-df718bcb Alpha | master
- SYS: AMD Ryzen 9 5900X 12-Core Processor | 24 Threads | 15.92 GiB RAM | TSC: 3.700GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-01- 8T12:39:30
- RSX: Found vulkan-compatible GPU: 'AMD Radeon RX 5700 XT' running on driver 2.0.233
- SYS: Firmware version: 4.89
S UPDATER: RPCS3 is up to date!
S PPU: Enabled: Non-Java Mode Fixup
- RSX: Found vulkan-compatible GPU: 'AMD Radeon RX 5700 XT' running on driver 2.0.233
E RSX: Your GPU does not support alpha-to-one for multisampling. Graphics may be inaccurate when MSAA is enabled.
S Input: The pad mode was changed to Single-threaded
S Input: XInput device 0 connected
S GUI: Boot successful.
S PPU: LLVM: Loaded module v5-kusa-hhgAGjQj2v5py1idtRaAu3-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-akoThJeeeZ5o0dnQ7NavCv-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-jrQUxUnnJ1e79sbCEfPbX3-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Afq027mpvJq2EaaVKJc64E-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-hkem83Ywdaoe2f0tQLK2EN-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Mv6P2okJc74Pv66U22xsTV-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-CCZYq3bn0zs2HKnTgjGdxp-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-dkSasunu5XgHUa3Tu9p5Ef-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-PMxALSh0m21aAV9Jx4bUnw-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-A4mx5rmxgUudu0urPV07ro-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-VfwxQ7HXdbXNbNfJcun5vm-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-MPd2FG1MN8S4Z6hPciXLQp-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-tRbzZxm9cKFmYWW0G1FEYJ-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-jJZJvsyoyN2Pk37x67w3sU-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-PwcuvpS1RR710zv79MrNhb-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-qUyie314ZhNLN0XzghQHPC-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-G4TgL6jAGnztfEkyP6skYC-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-NGq4uH9ojQEaZ9o6EjLFfA-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-gTXRujQuzcEswHtJFdcrLC-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-9TngEG2JkEgekPYzH5ohfx-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-1k925JZS5vhJ7xfjAYZK23-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-E3ooUf99JGW6385oLMViqF-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-nXLSCRx89EqLn6fphxcXYt-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-A1FtRUF5h1C3gCGVyHJmrU-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-qf940oNsGi5ojJvuCKWEHA-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-9KUSmwEhnz7GHJxXqvZXJX-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-j9KryKcsHTrVUerwm1RwMG-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-kfEgCrt2puyHn6xysP57Cz-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-ssEAyRhiVrNhacATYbZMZg-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-2S8c9azjmTqqSsy12xFnNM-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-htycV6wwdHiTsQPUN3xS2g-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-A2MwqEbcbf179Cfo0izzvY-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-knJx2GsSQr231RNeFpuFmM-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-2S9NG2T7xAtiPX7hvzWzeE-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-hqa9xm0NncWt9JCfXwEiXX-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Yvnaby9mHzWaMw7hV9TTLj-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-1Zgr4P89dixqoVitfqxeiK-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-tL0pw9jdg2cAvoMF6jhvbf-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-C2buPmbNtuymzTYC20ga2L-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-Ye4oqfZ2eqj0mFcjJy9SM3-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-YkWC6MT4EXPU7yyQ3AX1U7-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-JzeWEng62G75JsXVYp00mG-00001G-znver3.obj
S SPU: SPU Runtime: Built the interpreter.
S SPU: SPU Runtime: Built 346 functions.
U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0020ce0)
S PPU: LLVM: Loaded module v5-kusa-1z3Pyu8YVnnorJiQ2hfu1e-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0020a50)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0020a50, a3=0x0)
S PPU: LLVM: Loaded module v5-kusa-XCgQWMc1s99n1WTwrpWvw4-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S PPU: LLVM: Loaded module v5-kusa-GsbjiwC5Sm3exFcR5udHpE-00001G-znver3.obj
S PPU: LLVM: Loaded module v5-kusa-gRWSbPdZHFQq5essKqQVjk-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0020df0)
S PPU: LLVM: Loaded module v5-kusa-fLV79QqHgPi90UziTsWrHo-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23002a00)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) x2
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/title.bmd” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/appkeep.bmd” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/pcalg_v1.p3obj” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/pcplk_v1.p3obj” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/pcbet_v1.p3obj” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/appkeep2.bmd” [1]
E SYS: 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [3]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/p1.fnt” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/p1_g.fnt” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/cfdata/maptex/kts.p3tex” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/sound/mapse/kts01.csf” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/cfdata/e1141.e” [1]

### System configuration

Ryzen 5900x
AMD 5700XT

Adrenalin 22.11.2

**Comment by YuriNator557** [comment]
This is a support request, go to the discord server or post in the forums

**Comment by kenshinmokota** [comment]
thanks.
