### ISSUE TITLE
Enter a title here

### ISSUE THREAD

**Issue by HillCCC** [RPCS3/rpcs3#13199]
### Quick summary

戦国BASARA4 皇 [BLJM61248] Goto Crash

### Details

I already ignore those missing BGM since changing PPU thread count to 1 , No missing sound in-game
everything run smoothly untill i pick goto matabei (i can play the cutscene but it'll crash after it's done screencap provided)
at first i thought it was his model bugged so i start looking for Fix/patches but no luck so far
the only i found is pl035, already tried , didn't work at all , same problem

E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJM61248/USRDIR/nativePS3/sound/voice_pick/drama35/v4_s_035.sspr” [1]
F {PPU[0x1000017] Thread (decodeProc) [0x00a87b6c]} VM: Access violation reading location 0x14 (unmapped memory)

### Attach a log file

[log.zip](https://github.com/RPCS3/rpcs3/files/10377725/log.zip)

### Attach capture files for visual issues

![image](https://user-images.githubusercontent.com/122324163/211428701-5219d3f6-640a-453c-86cf-ace0df0eb44e.png)
![image](https://user-images.githubusercontent.com/122324163/211428732-375c33d8-4aff-4abc-a74a-54a49529f442.png)

**Comment by AniLeo** [comment]
Using invalid/debug settings, to be asked as a support request, not a valid issue report as is.

**Comment by HillCCC** [comment]
oh im so sorry, first timer haha
Thanks !
