### ISSUE TITLE
Move Handle "Don't See a new option : GUN"

### ISSUE THREAD

**Issue by Monky-Power** [RPCS3/rpcs3#13192]
### Quick summary

I don't see a new option (Submit on Nov 27, 2022) 
"gun" in move handler.

### Details

In  : https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/Cell/Modules/cellGem.cpp,
**Code precise option "gun"
ifdef HAVE_LIBEVDEV**

In : https://wiki.rpcs3.net/index.php?title=Help:Building_RPCS3
I don't know if I'm on the right track
I don't know how to enable or install this item
**-DUSE_LIBEVDEV= | ON | Build with libevdev-based joystick support.**

switch (g_cfg.io.move)
{
case move_handler::fake:
case move_handler::mouse : 
{
	connected_controllers = 1;
	break;
}
**#ifdef HAVE_LIBEVDEV
		case move_handler::gun :**
		{
			gun_thread& gun = g_fxo->get<gun_thread>();
			std::scoped_lock lock(gun.handler.mutex);
			connected_controllers = gun.handler.init() ? gun.handler.get_num_guns() : 0;
			gun.num_devices = connected_controllers;
			break;
		}
#endif
		case move_handler::null:
		default:
			break;
		}

<img width="432" alt="move handler" src="https://user-images.githubusercontent.com/110936040/211218059-22b287c2-13d1-41ec-ae15-d9dc141fa8db.png">

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10369457/RPCS3.log)

### System configuration

Windows 10
RPCS3 : 0.0.26-14525-df718bcb Alpha | Master

**Comment by Megamouse** [comment]
You're on windows. It's a Linux thing

**Comment by Monky-Power** [comment]
Ok.
Thanks for the quick response

No Issue for the moment for Windows ?
