### ISSUE TITLE
[DX12] Terraria odd green text and certain colours missing

### ISSUE THREAD

**Issue by tambry** [RPCS3/rpcs3#1319]
In Terraria - Trial [NPUB30943] some of the text is weird halloween looking green.
![image](https://cloud.githubusercontent.com/assets/1827708/11453651/9bfad14a-961b-11e5-8040-2a23097654b4.png)

Also in character creation menu, some of the items are missing or have weird colours, for example hair colours.
![image](https://cloud.githubusercontent.com/assets/1827708/11453656/d845e46e-961b-11e5-9250-5128ad349135.png)

**Comment by tambry** [comment]
@vlj Is the probably the right person to investigate this.

**Comment by vlj** [comment]
looks like a texture swizzle issue, the green is apparently replacing the alpha channel here.

**Comment by tambry** [comment]
Managed to fix the menu, but character creation is a bit of messed up now. Will look into it more tomorrow.

**Comment by tambry** [comment]
@vlj Like I said, I managed to fix buttons' colours in the main menu with https://github.com/tambry/rpcs3/commit/293d7720a9592655ad33ec6d30abb9aff48fba5a.
![image](https://cloud.githubusercontent.com/assets/1827708/11456457/4c9da880-9692-11e5-9b56-2d2b4aebf421.png)

But now the character creation has even weirder colours.
![image](https://cloud.githubusercontent.com/assets/1827708/11456470/af206ab0-9692-11e5-84d6-0fcebdf7d985.png)

Any idea, what I could have done wrong?

**Comment by tambry** [comment]
This has been fixed.
