### ISSUE TITLE
[Regression] Can't Update Bioshock 2 after #13147

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#13207]
### Quick summary

 A target app version is required (01.03), but no PARAM.SFO was found for BLUS30420
![photo](https://user-images.githubusercontent.com/60384196/211682426-b57898c1-cc52-41d9-9aca-052c06fc4ce8.png)

### Details

My SFO is present and accounted for
![image](https://user-images.githubusercontent.com/60384196/211682640-d8fa309f-343f-4ccc-8566-2937e63eeede.png)
There aren't any other update files.
I'm just confused and handing this off for investigation.

### Build with regression

#13147

### Attach two log files

[Working log](https://github.com/RPCS3/rpcs3/files/10387495/RPCS3.zip)

[Regressed log](https://github.com/RPCS3/rpcs3/files/10387499/RPCS3.log)

### Attach capture files for visual issues

N/A

### System configuration

Ryzen 5 3600

### Other details

Need a trace or anything lmk.
Tested PR 13205 just in case. Issue persists.

**Comment by Megamouse** [comment]
The PARAM.SFO should be in /dev_hdd0/game/BLUS30420/PARAM.SFO

**Comment by Megamouse** [comment]
Are you installing both at once?
There's not much information given here.

**Comment by Megamouse** [comment]
Ah. simple problem

**Comment by Darkhost1999** [comment]
> The PARAM.SFO should be in /dev_hdd0/game/BLUS30420/PARAM.SFO

Yea isn't it /dev_hdd0/game/BLUS30420/PARAM.SFO/PS3_GAME/PARAM.SFO

**Comment by Darkhost1999** [comment]
Both at the same time fails. One at a time works.

**Comment by Megamouse** [comment]
try #13205

**Comment by Darkhost1999** [comment]
Works great now
