### ISSUE TITLE
OpenGL needs fixes

### ISSUE THREAD

**Issue by Ekaseo** [RPCS3/rpcs3#1320]
OpenGL is broken right now, is someone going to disable it? its useless right now, even for debugging, most games work below 1 fps with broken graphics and scaling.

**Comment by tambry** [comment]
@Ekaseo My opinion is, that both renderers should be replaced by [Vulkan](https://www.khronos.org/vulkan) in the near future, once it's released and if it isn't absolutely horrible. As it should have benefits of both DX12 and OpenGL.

**Comment by kd-11** [comment]
Performance issues should have been resolved after https://github.com/RPCS3/rpcs3/pull/1502. There have also been numerous changes to tackle the neglected state of the backend

**Comment by kd-11** [comment]
@tambry I think this can be closed. Most issues with OpenGL have been fixed or atleast improved to the point where it is usable.
