### ISSUE TITLE
Savestate is not working

### ISSUE THREAD

**Issue by Basfet** [RPCS3/rpcs3#13204]
### Quick summary

Savestates is not working since build 0.0.26-14527. RPCS3 just crashed when booting with savestate. Last working build is 0.0.26-14526.

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/10386907/RPCS3.zip)

**Comment by devfox-se** [comment]
Can confirm this - my savestates are not booting on any build newer than 0.0.26-14526

**Comment by greatwolf** [comment]
Same here. I initially checked forum and discord but didn't see anyone mention it so I thought to try github and looks like this got reported.

In my case, FFX/X-2 save states don't work on RPCS3 0.0.26-14568. Doesn't matter if the saved states created from 14526 or 14568 -- both fail to load and ends up crashing the emulator. For the time being I just downgraded back to 14526 until this issues fixed.

**Comment by elad335** [comment]
Test with #13221

**Comment by NyxStele** [comment]
Same here, with NCAA Football 14.  Was nice to be able to save and quit during a game.  Hope this can be restored.
