### ISSUE TITLE
Boot Error

### ISSUE THREAD

**Issue by babytaikoer** [RPCS3/rpcs3#13215]
### Quick summary

E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/SCEEXE000/USRDIR/data/font/Font_.nut” [1]

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10404028/RPCS3.log)

**Comment by brian218** [comment]
Corrupted game dump. Invalid issue.
