### ISSUE TITLE
Gta IV The Complete Edition on RPCS3 under map issue

### ISSUE THREAD

**Issue by Nunu2000q** [RPCS3/rpcs3#13210]
### Quick summary

I have downloaded the Gta IV The Complete Edition and i have tried to play on rpcs3 emulator but everytime at first mission it puts me under map this happens in all three gta

### Details

It puts me under map when i start the first mission and can't do nothing..

### Attach a log file

[log.txt](https://github.com/RPCS3/rpcs3/files/10389749/log.txt)

### Attach capture files for visual issues

![Untitled2](https://user-images.githubusercontent.com/96658083/211743216-31b2759a-75f2-4837-883a-d7d2d68c3a80.jpg)
![Untitled1](https://user-images.githubusercontent.com/96658083/211743228-e069db06-0a43-424b-823c-dd1d9d2c1b62.jpg)
![Untitled4](https://user-images.githubusercontent.com/96658083/211743252-eb1be043-2c3f-496b-a507-18399d886fa1.jpg)
![Untitled3](https://user-images.githubusercontent.com/96658083/211743270-28abad2d-851b-4dd3-a65d-30ab329a6566.jpg)

### System configuration

Processor: Amd Ryzen 5 2400g
Ram: 16 gb ddr4
Motherboard: A320m-k
PSU: 1000W Corsair
GPU: Gigabyte Aorus GeForce RTX 2080 ti xtreme, 11GB

### Other details

All my RPCS3 settings are setted to default

**Comment by MSuih** [comment]
Github isn't a place for help requests, use Discord for that instead. Also, this issue is fixed if you use [the settings from our wiki](https://wiki.rpcs3.net/index.php?title=Grand_Theft_Auto_IV)
