### ISSUE TITLE
AVX512 not working with 11800h processor

### ISSUE THREAD

**Issue by IngenuoGamer** [RPCS3/rpcs3#13216]
### Quick summary

Check box for avx512 is available but there is zero performance change.

### Details

Im using v0.0.26-14568-1852b370 with an i7 11800h (tiger lake) but AVX512 seems to be bugged. 
Fps is exactly the same with and without it.
Cpu clock is locked. This is a notebook cpu in a desktop motherboard with very good cooling and power delivery.

There are two runs in the log file, first with avx512 ticked and second you without.

BRs

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10405107/RPCS3.log.gz)

### System configuration

i7 11800h
2x 8gb samsung b-die
RTX 3080
1tb nvme

**Comment by YuriNator557** [comment]
Enabling Full Width AVX-512 will not do anything if the game doesn't use it, and even if it does it won't always improve performance. There is no issue here

**Comment by IngenuoGamer** [comment]
Alright, did the LLVM CPU: alderlake and performance is about 15% worse. Maybe some rewording removing  the much faster part would make the help clearer.

Thanks for the lightning fast reply.
