### ISSUE TITLE
Borderlands 2 hangs at loading screen since #13172 (0.0.26-14527)

### ISSUE THREAD

**Issue by svensvond** [RPCS3/rpcs3#13213]
### Quick summary

Borderlands 2 BLES01684 hangs at loading screen. 

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10394272/RPCS3.log.gz)

### System configuration

Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz | 12 Threads | 15.92 GiB RAM | TSC: 2.208GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
vulkan-compatible GPU: 'NVIDIA GeForce RTX 2060' running on driver 528.2.0.0

**Comment by kd-11** [comment]
No problems noted in logs. Clear caches and retry.

**Comment by svensvond** [comment]
same after removing cache folder. 
waited 5 Minutes.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10410837/RPCS3.log.gz)
![image](https://user-images.githubusercontent.com/37634123/212304353-4e0bcd7e-b167-4da5-b3d7-d614c22a40e4.png)

**Comment by kd-11** [comment]
Retest, a fix went in for a similar issue.

**Comment by svensvond** [comment]
seems to be fixed.

**Comment by xcier** [comment]
I have this issues as well
![image](https://github.com/RPCS3/rpcs3/assets/36747898/eb00a723-7bd9-4159-8a23-aba581aff0c9)
![image](https://github.com/RPCS3/rpcs3/assets/36747898/c091b158-392b-4852-8067-5dc9c1281c46)
