### ISSUE TITLE
Unable to build on Ubuntu 15.04 CMake Error at /usr/share/llvm-3.6/cmake/LLVMConfig.cmake:52 (include):

### ISSUE THREAD

**Issue by steveunixson** [RPCS3/rpcs3#1321]
artem@artem-K52Jr:~$ git clone https://github.com/RPCS3/rpcs3.git
Cloning into 'rpcs3'...
remote: Counting objects: 43404, done.
remote: Total 43404 (delta 0), reused 0 (delta 0), pack-reused 43404
Receiving objects: 100% (43404/43404), 28.23 MiB | 2.26 MiB/s, done.
Resolving deltas: 100% (34379/34379), done.
Checking connectivity... done.
artem@artem-K52Jr:~$ git submodule update --init
artem@artem-K52Jr:~$ cmake CMakeLists.txt 
cmake: /home/artem/Documents/Code/build/src/linuxbrew/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
cmake: /home/artem/Documents/Code/build/src/linuxbrew/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
cmake: /home/artem/Documents/Code/build/src/linuxbrew/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
CMake Error: The source directory "/home/artem" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
artem@artem-K52Jr:~$ cd rpcs3/
artem@artem-K52Jr:~/rpcs3$ cmake CMakeLists.txt 
cmake: /home/artem/Documents/Code/build/src/linuxbrew/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
cmake: /home/artem/Documents/Code/build/src/linuxbrew/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
cmake: /home/artem/Documents/Code/build/src/linuxbrew/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- No build type selected, default to Release
CMake Error at CMakeLists.txt:14 (add_subdirectory):
  The source directory

    /home/artem/rpcs3/asmjit

  does not contain a CMakeLists.txt file.

-- cotire 1.7.3 loaded.
-- Initializing RPCS3_SRC_DIR=/home/artem/rpcs3/rpcs3
-- Found wxWidgets: TRUE  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
CMake Error at /usr/share/llvm-3.6/cmake/LLVMConfig.cmake:52 (include):
  include could not find load file:

    /usr/lib/llvm-3.6/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:91 (find_package)

CMake Error at /usr/share/llvm-3.6/cmake/LLVMConfig.cmake:55 (include):
  include could not find load file:

    /usr/lib/llvm-3.6/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:91 (find_package)

CMake Error at rpcs3/CMakeLists.txt:125 (llvm_map_components_to_libnames):
  Unknown CMake command "llvm_map_components_to_libnames".

-- Configuring incomplete, errors occurred!
See also "/home/artem/rpcs3/CMakeFiles/CMakeOutput.log".

**Comment by tambry** [comment]
@steveunixson Seems like you forgot to run "git submodule update --init"

**Comment by csdf** [comment]
ln -s /usr/share/llvm-3.6 /usr/lib/llvm-3.6/share/llvm

**Comment by steveunixson** [comment]
I`ve done "git submodule update --init" after cloning to git. Maybe this is the problem? 
Also I have this error despite that I have LLVM installed 
ln -s /usr/share/llvm-3.6 /usr/lib/llvm-3.6/share/llvm
ln: failed to create symbolic link ‘/usr/lib/llvm-3.6/share/llvm’: No such file or directory

**Comment by danilaml** [comment]
@steveunixson seems like faulty llvm3.6 package. Try to find and install/fix newer 3.6 version.

**Comment by tambry** [comment]
@steveunixson Is this still a problem?

**Comment by tambry** [comment]
As there has been no further discussion, I'm going to assume that the issue has been fixed.

**Comment by ProfessorKaos64** [comment]
I am using [llvm 3-8 ](https://packages.debian.org/stretch/llvm-3.8-dev) from Debian Stretch, and have the same issue.

**Comment by ProfessorKaos64** [comment]
Anyone hitting this thead trying to use clang/llvm-3.8 for Debian, I've continued this in #1610. It appears there were upstream changes that broke the placement/configuration of LLVM. The 3rd revision in Debain Sid appears to have fixed this. Testing now.

**Comment by cyian-1756** [comment]
@tambry Ran into the same issue on Ubuntu 16.04 with LLVM 3.8.0

**Comment by tambry** [comment]
I'm no longer a developer of RPCS3. Please ping someone else who is, if you want help.

**Comment by danilaml** [comment]
@cyian-1756 could be a bug in the packages (https://bugs.launchpad.net/ubuntu/+source/llvm-defaults/+bug/1655148 maybe?). Not the first time this happens.
