### ISSUE TITLE
APF 2k8 menu control glitch

### ISSUE THREAD

**Issue by SamTheMan1999** [RPCS3/rpcs3#13219]
### Quick summary

Whenever I try to browse in-game menus whether it's by selecting something or going up or down in a menu, it seems to activate twice. In other words, it skips over a option so I can't select certain things. I'm not sure how to fix this issue, and cannot find anything online about it. 

This happens when using the D-pad to select certain menu options or settings for the game, or when simply pressing A to try and go through to the next menu. It activates at least twice. It's like it's incredibly sensitive.

### Attach a log file

.

**Comment by Megamouse** [comment]
Missing log file
