### ISSUE TITLE
BCUS99086 - Uncharted 3 - DoF being incorrectly applied

### ISSUE THREAD

**Issue by dunestorm333** [RPCS3/rpcs3#13223]
### Quick summary

Throughout the later game, depth of field/blur seems to be applied seemingly at random in various different areas of the game. This happens much more frequently towards the later chapters, almost rendering the game unplayable.

Here is a video showcasing the issue: [https://www.youtube.com/watch?v=1AXXqo_14hs](https://www.youtube.com/watch?v=1AXXqo_14hs)

![image](https://user-images.githubusercontent.com/13191298/212404883-cd7ce3f9-d8f3-45de-9a18-d832d27f1993.png)
![image](https://user-images.githubusercontent.com/13191298/212404984-18d4a2f5-d894-419a-a4c7-c3789d53f381.png)

### Details

This issue happens regardless of which patches are applied, I have tried enabling and disabling the listed patches but they do not have any impact on this bug:

- Depth Border Fix
- Depth Buffer Viewport
- Disable Depth of Field
- Disable Motion Blur
- Enable GPU Lighting
- Performance (WCB)

![image](https://user-images.githubusercontent.com/13191298/212404430-fcc492e6-1ff0-4dde-88a5-f69c0e9c2e7e.png)

I am also using the suggested settings for Uncharted 3 shown [here](https://wiki.rpcs3.net/index.php?title=Uncharted_3%3A_Drake%27s_Deception).

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10414890/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1rOZhcoKwfSQWrQVbxJj4szQYYlPG-ehk/view?usp=sharing

### System configuration

-  Operating System: Windows 11 Pro 64-bit (10.0, Build 22621) (22621.ni_release.220506-1250)
-  Processor: AMD Ryzen 9 5900X 12-Core Processor             (24 CPUs), ~3.7GHz
-  Memory: 32768MB RAM
-  Card name: AMD Radeon RX 6800 XT
-  Dedicated Memory: 16337 MB
-  Current Mode: 2560 x 1440 (32 bit) (165Hz)
-  Driver Version: 31.0.12029.10015

**Comment by lseurttyuu** [comment]
Did you try to change ZCULL Accuracy to Relaxed as it is suggested on Wiki page?

**Comment by dunestorm333** [comment]
Thank you, that appears to have significantly improved the issue, I had completely missed this option!

**Comment by Darkhost1999** [comment]
Does using relaxed zcull mean this isn't an issue? Cause imo it is still an issue if relaxed zcull is required to be used to not have any blur.

**Comment by lseurttyuu** [comment]
I agree, the issue is still valid - relaxed zcull is a simple workaround. I can confirm this issue is present in a different version of the game (BCES01175).

**Comment by dunestorm333** [comment]
I also agree in that maybe this should remain open until the issue is addressed without hacks  :)

**Comment by Asinin3** [comment]
This needs to be tested without any patches. Patches are hacks, and not to be used during bug reports.

**Comment by lseurttyuu** [comment]
I validated the issue. It's caused by MLAA patch. When no patches are applied, the issue is not present. That means the issue described here in this thread is not valid as community patches / games with community patches are not tracked here.
All relevant issues are already mentioned in https://github.com/RPCS3/rpcs3/issues/12556 and @kd-11 said:
> Changes are being made to address this, but it will take some time

So it seems this issue should be closed.
