### ISSUE TITLE
RPCS3 Loading Save States Error

### ISSUE THREAD

**Issue by Dragonsarehax** [RPCS3/rpcs3#13234]
### Quick summary

Whenever I try to load a savestate, RPCS3 gives me a fatal error message and crashes.

### Details

My RPCS3  says the state was successfully saved, but whenever I try to load the state it gives me this fatal error message: "Serialized Object: struct id_manager::id_map<struct lv2_fs_object>" and then the emulator crashes.  Any idea what could be causing it?

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10423371/RPCS3.log)

**Comment by elad335** [comment]
All savestate reports must include 2 logs, one when saving and one when loading,

**Comment by elad335** [comment]
Probably outdated & fixed, closing. Open a new issue if persists.
