### ISSUE TITLE
Stranglehold Demo linux Crash.

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13230]
### Quick summary

When testing Stranglehold Demo on Linux I ran into an issue where the game would always crash on Linux even though the same pkg works fine on windows

### Details

The game  Stranglehold Demo crashes with the message when finishing compiling the PPU:
·F 0:00:40.774323 {PPU[0x1000000] Thread (main_thread) [liblv2: 0x01a56908]} SIG: Thread terminated due to fatal error: Verification failed
(in file ../rpcs3/util/vm_native.cpp:485, in function shm) (errno=24=Too many open files)
This doesn't happen on windows the game boots fine

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10419035/RPCS3.log)

### System configuration

- SYS: RPCS3 v0.0.26-14568-1852b370 Alpha | master
- SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.57 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 5.15.85-1-MANJARO, Version: # 1 SMP PREEMPT Wed Dec 21 21:15:06 UTC 2022
- SYS: Current Time: 2023-01-14T22:54:31
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 525.60.11.0
- SYS: Firmware version: 4.89

**Comment by RipleyTom** [comment]
You need to increase the number of files that can be opened on your system:
Adding something like
```
youruser           hard    nofile     524288
```
to `/etc/security/limits.conf` and rebooting, see https://wiki.archlinux.org/title/Limits.conf for more info.
Not a rpcs3 issue.

**Comment by MrGrosNounours** [comment]
I have the same problem with Oblivion, increasing the system limit doesn't change anything.

Using this command solved the issue:
`prlimit --pid <pid> --nofile=8192`

It seems that rpcs3 sets a limit of 4096 at startup, maybe that's too low for these games.
