### ISSUE TITLE
(Compat: Database Error - No Results found) v0.0.26-14569

### ISSUE THREAD

**Issue by PS3Tester** [RPCS3/rpcs3#13233]
### Quick summary

When loading RPCS3 Compatibility states: Database missing for all games.
With error:  

·! 0:00:00.513849 Compat: Finished reading database from file: D:/rpcs3/GuiConfigs/compat_database.dat
·E 0:00:00.513868 Compat: Database Error - No Results found

![error](https://user-images.githubusercontent.com/122757672/212585234-ec73bd27-a7e1-4d41-b964-45636a8bcb10.jpg)

I've re downloaded the emulator with the same error plus trying bar-bones on the desktop with no games.  Same error: E Compat: Database Error - No Results found
![error 2](https://user-images.githubusercontent.com/122757672/212585765-97e00556-43c4-43ca-b261-6d1a6349e53d.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10422043/RPCS3.log.gz)

### Details

RPCS3 isn't able to show Compatibility 

### Attach a log file

https://mega.nz/file/QnBkjaQD#KZdmaNcdtOuxR7dap7gO-9NBi5KBQTL1Kb-4dIC1e0U

### System configuration

Microsoft Windows 10 Pro
10.0.19045 Build 19045
AMD Ryzen 7 3700X
MSI NVIDIA RTX GeForce 2070
VENGEANCE® RGB PRO 32GB (4 x 8GB) DDR4 DRAM 3200MHz

**Comment by Darkhost1999** [comment]
Right click anything including that xmb there -> download latest compatibility database.

**Comment by PS3Tester** [comment]
> Right click anything including that xmb there -> download latest compatibility database.

Thank you
