### ISSUE TITLE
Enter a title here

### ISSUE THREAD

**Issue by legluondunet** [RPCS3/rpcs3#13241]
### Quick summary

Hello,
I own "Last of Us" game and I would like to play it on my PC.
But it is very unstable, it often crashes and when it passed main menu and I can finally launch a new game, I obtain only a black screen.
Even the main menu has only a black background.
When I look video on Youtube, I can see users that obtain better results, without black screen.

### Details

This is some screenshots:
click on start (background is all black, no window)
![Capture d’écran_2023-01-16_23-07-35](https://user-images.githubusercontent.com/325405/212777149-95c2e6e1-2368-4dda-a965-6bd0999bd0f2.png)
main menu (still no background)
![Capture d’écran_2023-01-16_23-48-27](https://user-images.githubusercontent.com/325405/212777143-4ea08488-a207-43a8-b02b-2a7a2b9c7654.png)
alarm clock rang and I see nothing, all is black
![Capture d’écran_2023-01-16_23-49-31](https://user-images.githubusercontent.com/325405/212777142-79ac866c-b59f-49d8-b5ba-1e63324c5570.png)

### Attach a log file

I joined you two logs, 

[LOU without crash.txt](https://github.com/RPCS3/rpcs3/files/10429851/LOU.without.crash.txt)
[LOU with crash.txt](https://github.com/RPCS3/rpcs3/files/10429852/LOU.with.crash.txt)

### System configuration

my config:
OS: Manjaro 22.0.0 Sikaris
Kernel: x86_64 Linux 6.1.1-1-MANJARO
Proc: AMD Ryzen 9 5900HX
GPU: AMD AMD Radeon RX 6600M (navi23, LLVM 14.0.6, DRM 3.49, 6.1.1-1-MANJARO)
Drivers: Mesa 22.3.1
32 Go RAM

### Other details

Thank you for your help

**Comment by YuriNator557** [comment]
This is a support request, please submit it through the official support channels in the forums or the Discord server instead of here

**Comment by legluondunet** [comment]
I don't understand, it is not a bug?
