### ISSUE TITLE
Skylanders portal theoretical figure limit is 16, not 8

### ISSUE THREAD

**Issue by mandar1jn** [RPCS3/rpcs3#13246]
The current emulation makes the assumption that the maximum amount of figures present on the portal is 8. This is correct for the physical portal. The data of figure presence is then stored in 2 consecutive bytes. 4 figures per byte. However, the games are actually capable of reading up to 16 characters at a time from a portal since the command actually uses 4 consecutive bytes for character presence. 

This is backed up by:
Dolphin in [this PR](https://github.com/dolphin-emu/dolphin/pull/11331)
And [my research](https://marijnkneppers.dev/posts/). Specifically, [this part](https://marijnkneppers.dev/posts/some-big-skylanders-discoveries/#status)

I would submit a pr myself but I don’t own anything ps3 related. I just wanted to point this out.

**Comment by RipleyTom** [comment]
It's known, doesn't really matter, it would make the UI ugly and you'd never be able to put more than 8 on a real portal anyway.

**Comment by SuperSamus** [comment]
If I'm not wrong, you could place a (Swap Force Skylander + vehicle) * 2 players + Magic Item + Adventure Pack + Trap.
While super specific, that's 9 figures.
