### ISSUE TITLE
Game starts to a black screen then a fatal error

### ISSUE THREAD

**Issue by tavotabotato** [RPCS3/rpcs3#13259]
### Quick summary

I'm trying to get LittleBigPlanet 2 to work on RPCS3, I have the latest PS3 firmware and configs suitable for my PC yet when I start up the game it loads the PPU and SPU modules then goes to a black screen and if I close it I get a fatal error (it's in the image listed) can someone tell me how to fix it cause it's getting frustrating.
![Screenshot (45)](https://user-images.githubusercontent.com/52452064/213575695-8efd3d34-38f4-4c33-b2c0-a55471a5f4d2.png)

### Attach a log file

It's not really letting me use the log file, whenever I try using I get an access denied.

**Comment by tavotabotato** [comment]
Wdym invalid? Can I get any help? Just like that It’s closed?

**Comment by Asinin3** [comment]
@tavotabotato The issue tracker is not for support. Its for reporting issues with information that is actually useful to developers. You didn't provide anything useful at all. No log, no steps to reproduce, no regression testing, and the error is generic and doesn't lead anywhere.

Use discord/forums for support, dont spam github which is supposed to help developers improve the software.
