### ISSUE TITLE
1942: Joint Strike Crash

### ISSUE THREAD

**Issue by systemcoding** [RPCS3/rpcs3#13251]
### Quick summary

I am trying to run **1942: Joint Strike** and it gets to the loading screen. There is no response after that. I try to close the game and force stop it from the emulator GUI.
It looks like it didn't stop and crashed completely. I thought that this is going to be fixed when i run this game again. But no, it happened about 3-4 times

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10442608/RPCS3.log)

### Attach capture files for visual issues
![image](https://user-images.githubusercontent.com/68456596/213095688-365e6b23-a971-4af6-933f-fe385011c2aa.png)

### System configuration
* System: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz 
* 8 Threads 
* RAM: 12 GiB RAM DDR4
* Operating system: Windows 10 Build 19045.2486
* GPU: Intel(R) Iris(R) Xe Graphics

**Comment by ScottNash042** [comment]
this is not crashing
can be closed
