### ISSUE TITLE
Scott Pilgrim vs. The World: The Game [NPUB30162] Netplay Not Functional

### ISSUE THREAD

**Issue by forever-and-a-day** [RPCS3/rpcs3#13263]
### Quick summary

Scott Pilgrim's online multiplayer functionality appears to be broken. Lobbies can be created and joined, but the game will not start - instead the host and the guest players return to the main menu after a long-ish period of time. 

### Details

The Host machine is able to create a lobby, and select a character and location, and the guest player can also join the lobby and select a character. However, the game cannot be started. When the Host presses X to start, a "connecting..." popup appears, and after a minute or so (longer that I'd expect, but then again I've never had this work before) the same popup appears on the guest machine. After waiting for another few minutes, both players leave the lobby and display different error messages. On the Host machine, the error reads "You have been returned to main menu because of the network error" and on the Guest machine, the error reads "You have been returned to main menu because the game session is no longer available". 
I have tried using public and private lobbies (all with only 2 player capacity), using different wifi networks for each machine (including a mobile hotspot), using different networks with both machines on the same network, switching which machine is the guest and which is the host, using ethernet, etc. Each machine has its own unique RPCN account, and saves are not copied or shared between the two. 

### Attach a log file

Most recent attempt:
Host: https://drive.google.com/file/d/1HwDvwDBx6wkpVYFWOlXJbvUZyKmgvETQ/view?usp=sharing 
Guest: https://drive.google.com/file/d/1uPm3DMxLK-SYV-V-tGi_eWpfCzIaKTnl/view?usp=sharing 

### System configuration

Linux Mint 21.1 x86_64, X11 Cinnamon DE (Host), AMD Ryzen 7 3700X, NVIDIA GeForce RTX 2070 SUPER. 
SteamOS Holo 3.4.4, Wayland Gamescope DE (Guest), AMD Custom APU 0405, AMD Custom GPU 0405 Vangogh - it's a [Steam Deck](https://www.steamdeck.com/en/tech)

Drivers:
NVIDIA 515.86.01
AMD 4.6 - Mesa 22.2.0

RPCS3 Version: 0.0.26-1-709305df Alpha

Using default RPCN Settings, Using graphics settings recommended by the game's wiki. I have also found a couple other players posting about this issue, so I'm pretty sure it's not unique to my setup: 
https://old.reddit.com/r/rpcs3/comments/psws84/how_to_join_friends/ 
https://old.reddit.com/r/rpcs3/comments/m9p471/playing_game_with_rpcn_giving_connection_error/

**Comment by RipleyTom** [comment]
Tested this recently and it works. If it fails it's purely a connectivity issue(ie enable UPNP on your router and in the game config and it should work).
