### ISSUE TITLE
the camera in the game look "cut"

### ISSUE THREAD

**Issue by angelitogoro** [RPCS3/rpcs3#13260]
### Quick summary

When playing any video game, moving the camera or moving the character "cuts" the screen and is annoying

### Details

In open places, the camera has a "cut" part in a part of the screen, but being in closed places it is fixed, I changed all the graphics and I did not change anything

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10463078/RPCS3.log.gz)

### Attach capture files for visual issues

https://user-images.githubusercontent.com/123140137/213615260-193fa386-58ad-479e-a4e2-382f603c4e3b.mp4

**Comment by kd-11** [comment]
Its called screen tearing and is the reason vsync exists. Enable vsync in the emulator or your graphics driver control panel.

**Comment by angelitogoro** [comment]
> Its called screen tearing and is the reason vsync exists. Enable vsync in the emulator or your graphics driver control panel.

activate vsync in the emulator and in my graphics driver and still the same

**Comment by angelitogoro** [comment]
https://user-images.githubusercontent.com/123140137/213845770-8817daea-618a-42c6-bf02-efcfb37e41cf.mp4



> Its called screen tearing and is the reason vsync exists. Enable vsync in the emulator or your graphics driver control panel.


https://user-images.githubusercontent.com/123140137/213845774-48f59cfb-607e-48cd-a19e-1a0ab0c3a40b.mp4

the game still looks like this

**Comment by kd-11** [comment]
If vsync isn't working on your card there is nothing we can do about it. It's a GPU setting, we simply ask it to enable the feature by selecting which mode we want and that's it.
In this case I see you're unfortunately on intel UHD graphics, check your control panel settings. If it doesn't work, you should report to intel's driver team to investigate.
