### ISSUE TITLE
Rock Revolution [BLUS30212] Won't go past initial intro screen 

### ISSUE THREAD

**Issue by CaptnCH** [RPCS3/rpcs3#13267]
### Quick summary

You are unable to play Rock Revolution on RPCS3

### Details

Rock Revolution does not get past the initial intro screen. It always seems to fail at cellGameDataCheckCreate2 which from what I've read seems to indicate that something is being overwritten.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10472724/RPCS3.log.gz)

**Comment by Megamouse** [comment]
update your game and try again

**Comment by CaptnCH** [comment]
Did that and stops at the same place still
Here's another log with it updated 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10472729/RPCS3.log.gz)

**Comment by CaptnCH** [comment]
fixed by #16372
