### ISSUE TITLE
Gran Turismo 5 won´t launch 

### ISSUE THREAD

**Issue by CornysCornflakes** [RPCS3/rpcs3#13271]
### Quick summary

Tried playing Gran Turismo today but it wont boot properly. It starts up but after telling me to not shut off the console when saving and me pressing ok, it just goes into blackscreen.

Maybe someone on here can help me. 

### Attach a log file

E SYS: 'sys_rsx_context_attribute' failed with 0x80010002 : CELL_EINVAL [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00569/USRDIR/PDIPFS/K/PM” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00569/USRDIR/PDIPFS/K/S1” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00569/USRDIR/PDIPFS/K/IE” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00569/USRDIR/PDIPFS/K/Q8” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00569/USRDIR/PDIPFS/K/MK” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/dev_usb/GB.rt2” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/dev_ms/GB.rt2” [1]
E SYS: 'cellSaveDataAutoLoad2' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
E SYS: '_sys_timer_start' failed with 0x8001000a : CELL_EBUSY [1] x2
U sceNpTrophy TODO: sceNpTrophySetSoundLevel(context=0x1, handle=0x1, level=100, options=0x0)
U cellSysutil TODO: cellAudioOutGetDeviceInfo(audioOut=0, deviceIndex=0, info=*0xd012533c) x2
U sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd01247a8)
E SYS: 'cellNetCtlGetInfo' failed with 0x80130108 : CELL_NET_CTL_ERROR_NOT_CONNECTED [1]
E SYS: '_sys_timer_start' failed with 0x8001000a : CELL_EBUSY [2]
E SYS: Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/game205.db-journal” [x230]

**Comment by solarmystic** [comment]
Boots just fine on the latest master here.
![image](https://user-images.githubusercontent.com/4345150/213916860-6beef0be-dd0f-4473-90f7-99846b411e55.png)

For tech support related issues, please post a log at our help channel on the rpcs3 discord. This github is not the place for it, thanks. https://discord.com/channels/272035812277878785/277227681836302338
