### ISSUE TITLE
[Regression] MotoGP08 Graphical issue

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13273]
### Quick summary

The game has graphical issues and crashes past a certain build

### Details

When testing this game I came across a shader cache issue which causes the game to have graphical issues and crash when decompiling shaders on the GPU.

The build that causes the graphical issue also crashes the game when first going ingame so not sure how I couldn't get an rsx file on the build that caused the issue. I should also mention that the crash also affects the latest build on both Vulkan and OpenGL.

Some build after v0.0.7-8619-7f99de36 do make it in-game without crashing but the graphical issue still persists. Was able to make it in-game twice with the latest build but didn't save the log there were two different graphical issues I got.

The first one was with default settings(This graphical issue does not appear on the original build with the regression)

![screenshot-2023_01_22_00_51_37](https://user-images.githubusercontent.com/71127352/213895717-a7d33f0f-8fec-4a3d-8dea-d6951d8959ea.png)

The second one was with RDB+WDB+RCB+WCB which gives a different result(matches the effect of the build with the regression graphical issue).

https://user-images.githubusercontent.com/71127352/213895630-7cf95311-7efa-4f22-bdf5-8629799a0a32.mp4

Crash log:·F 0:01:17.076559 {RSX [0x427b530]} SIG: Thread terminated due to fatal error: Unknown register name: unk
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\GL\GLCommonDecompiler.cpp:36[:23], in function get_varying_register_location)

Note: version 0.0.6-8608 regressed the game with a different issue causing the game to not display anything and was fixed on the regressed build so had to take a build before that build as a before log.

### Build with regression

v0.0.7-8619-7f99de36

### Attach two log files

[v0.0.7-8619-7f99de36.gz](https://github.com/RPCS3/rpcs3/files/10473436/v0.0.7-8619-7f99de36.gz)
[v0.0.6-8605-9672ad53.gz](https://github.com/RPCS3/rpcs3/files/10473441/v0.0.6-8605-9672ad53.gz)
[v0.0.26-14600-53cc067c.gz](https://github.com/RPCS3/rpcs3/files/10473444/v0.0.26-14600-53cc067c.gz)
[v0.0.14-11605-b96864c7 Ingame Log.gz](https://github.com/RPCS3/rpcs3/files/10473456/v0.0.14-11605-b96864c7.Ingame.Log.gz)

### Attach capture files for visual issues

https://www.dropbox.com/s/v47o71hk72qi4rg/NPUB90181_20230122004412_capture.rrc.gz?dl=0
https://www.dropbox.com/s/x32bamum96khq3u/NPUB90181_20230122005503_capture.rrc.gz?dl=0

Note this is from build v0.0.14-11605-b96864c7 where I could get in-game
1.=RDB+WDB+RCB+WCB
2.=Default settings
3.=Opengl

### System configuration

    SYS: RPCS3 v0.0.26-14568-1852b370 Alpha | master
    SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
    SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
    SYS: Current Time: 2022-10-28T21:53:46
    RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 526.47.0.0
    SYS: Firmware version: 4.89

### Other details
This is properly GPU specific

**Comment by kd-11** [comment]
Have you tried using atomic FIFO?

**Comment by Virtua64** [comment]
This is the demo version but has the same issue as full game. Got it to work with Atomic but it doesn't always work after reboot, even with the same exact settings. Trying to figure out why the inconsistency... video below is with Atomic enabled when it worked.

https://user-images.githubusercontent.com/94409254/213931751-57c8727d-4b95-4f09-931e-66219b7d1c05.mp4

**Comment by kd-11** [comment]
Fixing the crash is easy by just ignoring the bad shader. Are the graphical issues still present with atomic FIFO is the question.

**Comment by kd-11** [comment]
The crash should be fixed by https://github.com/RPCS3/rpcs3/pull/13361

**Comment by Triticum0** [comment]
@kd-11 The crashing has been fixed. You need to turn on the write depth buffer to fix the graphical issues. Turning on the Read Depth Buffer causes the blue screen and missing bikes. If you think the issue has been sufficiently fixed you can close the issue.
![NPUB90181_screenshot_2023_02_07_20_13_07](https://user-images.githubusercontent.com/71127352/217355041-09d4ad2b-0511-4554-a624-eb9c5a45e698.png)

**Comment by kd-11** [comment]
Thanks for the report. I'll close this and leave a comment in the buffer options ticket. Relates to https://github.com/RPCS3/rpcs3/issues/9133
