### ISSUE TITLE
Pro Evolution Soccer 2018 (BLUS31612) doesn't boot with LLVM PPU Decoder

### ISSUE THREAD

**Issue by DarthVady** [RPCS3/rpcs3#13272]
### Quick summary

when starting the game Pro Evolution Soccer 2018 (BLUS31612) when loading the PPU Decoder (LLVM) the emulator closes by itself 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10473454/RPCS3.log)

**Comment by dapid7** [comment]
Yes, same like me also. After want finish the emulator RPCS3 auto close from system.
Please help and give the solution.

**Comment by Asinin3** [comment]
Yeah this is an ongoing issue still.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12146985/RPCS3.log)

**Comment by Megamouse** [comment]
duplicate of #11469
