### ISSUE TITLE
Mercenaries 2: World in Flames demo can't boot

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13274]
### Quick summary

Mercenaries 2: World in Flames demo seems to get stuck building the SPU cache. 

### Details

When testing the Mercenaries 2: World in Flames demo I ran into an issue when the demo seemed to get stuck building the SPU cache. Test both ver of the demo a had the same issue using the PsnPkgCheck.exe and flagged no issues so not sure what the issue is. if anyone can retest and get back to me would be appreciated. 

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10473576/RPCS3.log.gz)

### System configuration

    SYS: RPCS3 v0.0.26-14568-1852b370 Alpha | master
    SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
    SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
    SYS: Current Time: 2022-10-28T21:53:46
    RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 526.47.0.0
    SYS: Firmware version: 4.89

**Comment by AniLeo** [comment]
I can reproduce, this is Loadable as is

![image](https://user-images.githubusercontent.com/10283761/215333742-489965f9-54e8-46c2-a55f-76127abf8513.png)

Interesting line from the log when stopping the emulation after the black screen
`·E 0:05:04.011740 {VBlank Thread} SYS: 'Unknown function' failed with 0x00000000 : 00 [1]`

It doesn't work with PPU/SPU interpreters as well

---

System configuration
```
RPCS3 v0.0.26-14637-c471120a Alpha | master
AMD Ryzen 9 5900HX with Radeon Graphics | 16 Threads | 15.02 GiB RAM | TSC: 3.294GHz | AVX+ | FMA3
Operating system: POSIX, Name: Linux, Release: 6.1.7-1-MANJARO, Version: #1 SMP PREEMPT_DYNAMIC Wed Jan 18 22:33:03 UTC 2023
Qt version: Compiled against Qt 5.15.2 | Run-time uses Qt 5.15.2
·A 0:00:01.159294 {Vulkan Device Enumeration Thread} RSX: Found vulkan-compatible GPU: 'AMD Radeon RX 6700M (RADV NAVI22)' running on driver 22.3.4
```

**Comment by AniLeo** [comment]
Still an issue on RPCS3 v0.0.28-15118-2e4bf9ef Alpha
