### ISSUE TITLE
rsx: Thread terminated due to fatal error: Verification failed [LBP-3]

### ISSUE THREAD

**Issue by NextdoorPsycho** [RPCS3/rpcs3#13277]
### Quick summary

This is in reference to:
https://github.com/RPCS3/rpcs3/issues/12066
More specifically:
https://github.com/RPCS3/rpcs3/issues/12066#issuecomment-1279710714

The game loads you in, and you can play for a moment but when you try and launch any gameplay you get Deadlocked.

Here is a Video: 
https://user-images.githubusercontent.com/29320316/213958614-5b5f2b5b-f1d3-43b6-a6a0-2cd024e113af.mp4
And here are the Logs that I have!
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10476395/RPCS3.log)
[TTY.log](https://github.com/RPCS3/rpcs3/files/10476396/TTY.log)

ANd Finally: https://discord.com/channels/272035812277878785/319224795785068545/1066913213985333338
That's the RPCS3 Discord link to a BotSpam Log scrape.

### Details

You are able to open the game and Get into the POD, and should you open an adventure / Story game you will deadlock!

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10476395/RPCS3.log)
[TTY.log](https://github.com/RPCS3/rpcs3/files/10476396/TTY.log)
https://discord.com/channels/272035812277878785/319224795785068545/1066913213985333338

### Attach capture files for visual issues

https://user-images.githubusercontent.com/29320316/213958614-5b5f2b5b-f1d3-43b6-a6a0-2cd024e113af.mp4

### System configuration

RPCS3 v0.0.26-14600-53cc067c Alpha | master | FW 4.89 | Windows 11 22H2
AMD Ryzen 9 5900X | 24 Threads | 63.92 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3080 (528.02)

**Comment by NextdoorPsycho** [comment]
Note: im able to replicate this by increasing the resolution scale to match my native. 
https://i.imgur.com/Q26BYlr.png

**Comment by NikkMann** [comment]
Same issue as Armored Core Verdict Day when upscaling #14184

**Comment by kd-11** [comment]
Tracked by https://github.com/RPCS3/rpcs3/issues/14410

**Comment by kd-11** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/14446
