### ISSUE TITLE
Resident Evil The Darkside Chronicles cannot be installed

### ISSUE THREAD

**Issue by BiohazardXD** [RPCS3/rpcs3#13280]
### Quick summary

I have tried to install Resident evil the darkside Chronicles in its pkg version, when it starts to show the progress bar a second passes and the emulator simply closes.

### Details

I tried to install the American and European versions with these game IDs: NPEB00816, NPUB30648.
When I try to install the corresponding PKG file, I get the confirmation message to continue with the installation, after clicking YES the progress bar appears and it only stays at 0% and the emulator closes, this happens with both versions .
This problem has not happened to me with other games that I have managed to install successfully.
I have noticed that in the installation folder dev_hdd0/game there are games that could not be installed but they only contain a tree of empty folders.
It is worth mentioning that I have a laptop with Windows 10 Pro operating system, AMD Ryzen 9 5900HX processor, NVIDIA GeForce RTX 3070 graphics card and 32 GB of RAM.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10477681/RPCS3.log)

### System configuration

CPU: AMD Ryzen 9 5900HX
GPU: NVIDIA GeForce RTX 3070
GPU Driver Version: 31.0.15.2802
OS: Windows 10 Pro
RAM: 32 GB DDR4 SODIMM
SSD: 4 TB NVMe M.2

**Comment by spectacularchungus** [comment]
Experiencing the exact same issue on both American and European versions. Please advise.

**Comment by Rex000** [comment]
Seems to be the same issue as #13327

**Comment by Megamouse** [comment]
please try with #13329
send a log after the installation even if it works.

**Comment by MagTheMercenary** [comment]
Hello there, I'm new here and am facing the same problem when installing The Darkside Chronicles PKG file. The Umbrella Chronicles and Code Veronica X HD both installs and plays fine. Does anyone know if this will ever get fixed??

**Comment by Megamouse** [comment]
Should be fixed in the next build

**Comment by Stupacabra** [comment]
Having this same issue with the latest version, 0.035-17646-f9a72e8d. Attached my log.

[RPCS3.log](https://github.com/user-attachments/files/19266804/RPCS3.log)
