### ISSUE TITLE
There are intermittent bursts of all input not working

### ISSUE THREAD

**Issue by JapanYoshi** [RPCS3/rpcs3#13282]
### Quick summary

Input stops working for little stretches of time, unpredictably.

### Details

I play Rock Band 3 and Dance Dance Revolution on RPCS3. And I don't know how to phrase it, but when I play, there are certain times when all the input stops working for anywhere between half a second to several seconds at a time. When I'm going for a perfect score, missing even one note ruins the experience, so I'd like this issue resolved ASAP.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10479712/RPCS3.log.gz)

### Attach capture files for visual issues

Not a visual issue.

### System configuration

OS: Microsoft Windows 10 Home 64-bit 10.0.19045 Build 19045

CPU: Intel Core i7-8750H CUP @ 2.20GHz, 2208 MHz, 6 Cores, 12 Logical Cores

GPU: NVIDIA GeForce GTX 1060 with Max-Q Design

**Comment by Megamouse** [comment]
Please try to update your game first

**Comment by JapanYoshi** [comment]
Both my games are updated.

Also, the issue seems to be prevalent when using a keyboard.

**Comment by Megamouse** [comment]
you're using spu asmjit. try spu llvm

**Comment by Asinin3** [comment]
@JapanYoshi Retest on latest with SPU LLVM like you were asked to please

**Comment by JapanYoshi** [comment]
This issue was replaced with a different but possibly related issue where gameplay stops suddenly for about 5 seconds, and the music rewinds for that much before the gameplay continues.
