### ISSUE TITLE
Bejeweled 2 [NPUA30002] - The game ends with an error

### ISSUE THREAD

**Issue by Unisocks** [RPCS3/rpcs3#13299]
### Quick summary

The game ends with an error 

on version rpcs3 0.0.11 the game works..

### Details

rpcs3 0.0.11
![game](https://user-images.githubusercontent.com/122775649/214957344-8a4b58fc-f400-4727-b28d-4c01d612f710.PNG)
rpcs3 0.0.26
![crash](https://user-images.githubusercontent.com/122775649/214957413-3b7ad283-9777-43bb-9eae-61aafb3c5dec.PNG)

### Attach a log file

[RPCS3.gz](https://github.com/RPCS3/rpcs3/files/10513633/RPCS3.gz)

**Comment by AniLeo** [comment]
Invalid regression report as is, the range you gave between broken and working is too big, we need to know what's the first build it stopped working on

To note that Windows 8.1 and really old NVIDIA drivers are being used, so it's worth testing on modern OS and drivers to double check if it's not specific to old stuff

**Comment by Unisocks** [comment]
this is not a driver other games work
![as](https://user-images.githubusercontent.com/122775649/215275104-2d2b1ce8-4991-45c7-962a-3d3e3cea1d53.PNG)
[RPCS3.gz](https://github.com/RPCS3/rpcs3/files/10527593/RPCS3.gz)
unmapped memory

**Comment by iplaysomegames101** [comment]
first, try checking if there is updates for your drivers, second, update to windows 10 or use linux

**Comment by Unisocks** [comment]
> first, try checking if there is updates for your drivers, second, update to windows 10 or use linux

this is not driver or windows and on modern systems people have problems with rpcs3 this is still beta
