### ISSUE TITLE
[Regression] Rugby World Cup 2011 Graphical Issue (#13236)

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13291]
### Quick summary

The game has a graphical issue.

### Details

After v0.0.26-14570-240cb2d6 This game has a graphical issue.
Before
![NPEB90344_screenshot_2023_01_26_02_04_58](https://user-images.githubusercontent.com/71127352/214744947-e0b138a3-35b4-4bd1-95c8-3d590d15e4c0.png)

After
![NPEB90344_screenshot_2023_01_26_01_55_37](https://user-images.githubusercontent.com/71127352/214744936-d798840d-f43d-45cc-9e49-5b5098ff2b99.png)

### Build with regression

v0.0.26-14570-240cb2d6

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10505766/RPCS3.log.gz)
[rpcs3-v0.0.26-14569-e6a75974.log.gz](https://github.com/RPCS3/rpcs3/files/10505780/rpcs3-v0.0.26-14569-e6a75974.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/15HdYlXAe88AmqYpVFI0qwl-w0yyUwRBd/view?usp=share_link

https://drive.google.com/file/d/1i7CSKqZ6d8RJQ26n6EhfeS947JmQqsE9/view?usp=share_link

### System configuration

    SYS: RPCS3 v0.0.26-14568-1852b370 Alpha | master
    SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
    SYS: Operating system: POSIX, Name: Linux, Release: 5.15.85-1-MANJARO, Version: #1 SMP PREEMPT Wed Dec 21 21:15:06 UTC 2022
    SYS: Current Time: 2022-10-28T21:53:46
    RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 526.47.0.0
    SYS: Firmware version: 4.89

**Comment by kd-11** [comment]
Relates to https://github.com/RPCS3/rpcs3/issues/13253

**Comment by kd-11** [comment]
This one may be more debuggable as it is not using CPU blit, so RSX does not self-interrupt so frequently.

**Comment by AniLeo** [comment]
PR is #13236

**Comment by Triticum0** [comment]
@kd-11 seems it fixed though the ground texture is still broken
![NPEB90344_screenshot_2024_01_04_02_41_57](https://github.com/RPCS3/rpcs3/assets/71127352/c5846792-62e1-4d3b-927a-58c7d63a50c0)

Do you want to know which build fixed it before I close the issue

**Comment by kd-11** [comment]
> @kd-11 seems it fixed though the ground texture is still broken ![NPEB90344_screenshot_2024_01_04_02_41_57](https://private-user-images.githubusercontent.com/71127352/294073151-c5846792-62e1-4d3b-927a-58c7d63a50c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTY2NjMsIm5iZiI6MTcwNDM1NjM2MywicGF0aCI6Ii83MTEyNzM1Mi8yOTQwNzMxNTEtYzU4NDY3OTItNjJlMS00ZDNiLTkyN2EtNThjN2Q2M2E1MGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA4MTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxOTZlZTMxZjAyYmE3MDdjZTY5NjhlZDAyMTk1YzJhNzdjNjAyNTA2ZWU4NzE3ZTEyODY5OWUzNDA4ZjFjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-rOc7GPgWT8tSiNpm0DTuCLdOoDw42Y3epJwHxuErcQ)
> 
> Do you want to know which build fixed it before I close the issue

Yes please if it's not too much trouble. We can then close this regression report.

**Comment by Triticum0** [comment]
It was fixed with [#14130](https://github.com/RPCS3/rpcs3/pull/14130) I close this issue and make another one about broken ground textures
