### ISSUE TITLE
Mortal Kombat vs. DC Universe (BLUS30246) "SIG: Thread terminated due to fatal error: Verification failed"

### ISSUE THREAD

**Issue by Manya3084** [RPCS3/rpcs3#13306]
### Quick summary

Whenever I try starting the game, I am presented with a "F {RSX [0x0004780]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\expected.hpp:80[:13], in function front_face)" Error

### Details

This happens on both my 12900K HTPC setup & my main 7950x PC.

It has been a while since I played the game but I remember months ago it was working.

I have attached the log file and a screenshot.

![image](https://user-images.githubusercontent.com/104078862/215262676-816eb631-c84c-4468-a093-6ca7f9506c90.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10527016/RPCS3.log)

**Comment by AniLeo** [comment]
Non-default settings being used without any explanation to why they're required for running the game, does not follow guidelines.

Closing due to bad settings.
