### ISSUE TITLE
Access violation reading location 0x4 (unmapped memory) while launching Lara Croft and the Guardian of Light

### ISSUE THREAD

**Issue by mskrzyniarz** [RPCS3/rpcs3#13316]
### Quick summary

Regardless of the game version (NPEB00311/NPUB30225) and configuration the game always crashes and only this error is displayed in the window: 
`The PS3 application has likely crashed, you can clsoe it.` 

Erros in the console:
```js
U cellGameExec TODO: cellGameGetBootGameInfo(type=*0x30181500, dirName=*0xd0010ac8, execdata=*0xd0010ab4)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) x2
E SYS: 'sys_event_queue_receive' failed with 0x80010005 : CELL_ESRCH [1]
S SPU: New block compiled successfully x15
F {PPU[0x1000007] Thread (Render Thread) [0x001b004c]} VM: Access violation reading location 0x4 (unmapped memory)
E SIG: Thread [cellAudio Thread] is too sleepy. Waiting for it 17548.010µs already!
E SIG: Thread [cellAudio Thread] is too sleepy. Waiting for it 34069.580µs already!
```

### Details

I didn't lunched the game on the older version of RPCS3 but based on compatybility list this game was running without any problems.

Tested on:
RPCS3 v0.0.26-14637-c471120a Alpha

May be related with the issues (which is alredy closed):
https://github.com/RPCS3/rpcs3/issues/10771

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10528734/RPCS3.log.gz)

### System configuration

CPU: AMD Ryzen 9 5950X 16-Core Processor | 32 Threads | TSC: 3.400GHz | AVX+ | FMA3
RAM: 64 GiB RAM 3600 MHz
OS: Windows Pro, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
GPU: AMD Radeon RX 6800 XT (driver 2.0.233)
PS3 FW: 4.89

**Comment by AniLeo** [comment]
Many random settings being used without any explanation as to why, does not follow guidelines as it's explained that only default settings must be used unless other values are required, whereas the forum thread and wiki page list none.

Need information: Report needs to be updated with only default emulator settings being used.

**Comment by mskrzyniarz** [comment]
@AniLeo Sorry, didn't know that.
As I already mentioned I tried to run it with different configuration settings (with default, too).
Here are the logs with default settings:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10538241/RPCS3.log.gz)

**Comment by Asinin3** [comment]
Retest with latest build.

**Comment by mskrzyniarz** [comment]
@Asinin3 Tested on RPCS3 v0.0.29-15426-d34287b2 Alpha | master
I confirm it works (with `Write Color Buffer` enabled).

**Comment by ggwpezggwpez** [comment]
Same problem as OP with RPCS3 V 0.0.32

**Comment by AniLeo** [comment]
Removing unrelated comments, closing as completed as confirmed by the OP.
