### ISSUE TITLE
Sky Force Anniversary [NPUB31813] - Error when closing game

### ISSUE THREAD

**Issue by Unisocks** [RPCS3/rpcs3#13314]
### Quick summary

Error when closing game

### Details

![xd](https://user-images.githubusercontent.com/122775649/215292960-16eec645-a54f-4b98-8d27-1a383155f389.PNG)

### Attach a log file

[RPCS3.gz](https://github.com/RPCS3/rpcs3/files/10528376/RPCS3.gz)

**Comment by AniLeo** [comment]
Need Information: Needs testing on modern OS / driver version to pinpoint if this is a general issue or specific to the older windows version or NVIDIA drivers.

**Comment by Unisocks** [comment]
> Need Information: Needs testing on modern OS / driver version to pinpoint if this is a general issue or specific to the older windows version or NVIDIA drivers.
NVIDIA GeForce GTX 780 running on driver 474.11.0.0 this is the latest available driver for this video card
other games don't have this problem.

**Comment by AniLeo** [comment]
It's the latest available driver because you're on old GPU hardware that no longer has driver updates, it's by far not the latest NVIDIA driver. 

Other games not having the issue still doesn't mean that this isn't an issue exclusive to old OS / drivers.

**Comment by Unisocks** [comment]
rpcs3-v0.0.19 no such error
If everything on the computer works 99% without problems and only a couple of games can't work properly, this is the problem of the rpcs3 emulator that it can't work properly

I have already passed this game on the PC version in 4k on my old GTX 780 ⭐

**Comment by AniLeo** [comment]
If you don't grasp the basic concepts of software testing, please refrain from submitting issues, as this is just insulting at this point.
