### ISSUE TITLE
The Simpsons™ Game Demo [NPUB90048]: Audio issues

### ISSUE THREAD

**Issue by Rex000** [RPCS3/rpcs3#13326]
### Quick summary

The game has audio desync, crackling and stutters mainly in movies.

### Details

In cinematics of the game, the audio is not synchronized and also has crackling and stutters(muting?).

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10539220/RPCS3.log.gz)

**Comment by Rex000** [comment]
Similar issue was reported here with the full game: https://github.com/RPCS3/rpcs3/issues/4238

**Comment by RipleyTom** [comment]
Like the issue you linked, your cpu is below the recommended requirements(see https://rpcs3.net/quickstart).
The emulator is just struggling to run the 6 spu + 2 ppu + rsx + audio threads on your 4 threads.
