### ISSUE TITLE
I keep getting a error message E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/db/skaterschema.vlt” [1]  -  and then  -  F {PPU[0x1000004] Thread (themain_thread) [0x0123da58]} VM: Access violation reading location 0x4 (unmapped memory). I don't understand what this all means and if someone can explain it in simple terms that would be nice

### ISSUE THREAD

**Issue by LoneSquare** [RPCS3/rpcs3#13325]
### Quick summary

When I try to boot up the game it loads the PPUs fine but when it tries to load the SPUs it says on a black screen (The PS3 application has likely crashed, you can close it) Ive tried multiple new saves and its still not working

![FPS_ 30 08 _ Vulkan _ 0 0 26-14637 _ Skate 3  BLES00760  1_30_2023 2_05_08 PM](https://user-images.githubusercontent.com/123988760/215570924-8451195c-3b45-4764-a1b7-9074ea9957c0.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10539023/RPCS3.log)

### System configuration

AMD Ryzen 5000
20gb Ram

**Comment by AniLeo** [comment]
User error, invalid issue report. Ask for support on one of the support platforms.
