### ISSUE TITLE
MAC OS: XBOX Series Controller not working on SOME GAMES

### ISSUE THREAD

**Issue by marus70** [RPCS3/rpcs3#13336]
### Quick summary

After https://github.com/RPCS3/rpcs3/issues/11458 SDL works fine on Mac OS except for some games such as Killzone HD, NBA Jam and Ghost of Sparta.

### Details

XBOX Series Controller works now for the majority of the games, few others detect only analog stick but no buttons pressure.
Attached logs about Killzone HD having this issue.
Same controller works perfectly on every other Mac emulator (just as further information).

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10577254/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10577255/RPCS3.log.gz)

### System configuration

iMac intel basedCore i5 quad-core a 3,2GHz
AMD Radeon R9 M380

**Comment by RipleyTom** [comment]
You seem to have 'Keyboard' selected for both those logs as your pad under SDL...
