### ISSUE TITLE
Braid is broken

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1334]
Braid doesnt work past loading screen anymore. The emu stops and hitting resume 2 times make it crashes.
A good commit is 6930cbc064d46b2475bc2dc0500efbcd7abc1906 and a bad one is be1c9100cc22a6a4220270283ce41d298245e3e7

**Comment by vlj** [comment]
it's caused by merge in 78bfd54ad4933dc50e8d8ef14d71a7c7ff2c083c

**Comment by vlj** [comment]
I suspect a bug in the way NV3089_IMAGE_IN_SIZE  has been rewritten in 178bcfc8df038fc7102f26be302696aefc4fc860

**Comment by vlj** [comment]
almost all textures in jet set radio are black now too.

**Comment by B1ackDaemon** [comment]
@vlj , for some reason this Braid crash is related to savedata (NPUB30133-SAVE) inside dev_hdd0\home\00000001\savedata. If save is present, game won't crash after pressing resume, if there is no save, it crashes, like in your case.

**Comment by PZerua** [comment]
Let's mention @jarveson to see if he can take a look.

**Comment by jarveson** [comment]
Thanks for the heads up! I think i got it fixed in my recent PR

**Comment by danilaml** [comment]
@vlj is it fixed now?

**Comment by Zangetsu38** [comment]
for me yes

**Comment by B1ackDaemon** [comment]
Let's close this, then :)
