### ISSUE TITLE
Jurassic The Hunted Load screen freeze

### ISSUE THREAD

**Issue by vvhoamark** [RPCS3/rpcs3#13359]
### Quick summary

Loading screen freezes on some levels, text keeps refreshing but the bar will freeze and wont load all the way

### Details

Some loading screens between levels and for the survivor mode freeze and do not load all the way through

### Attach a log file

N/A

**Comment by Darkhost1999** [comment]
You want to give us any details about anything here?

**Comment by vvhoamark** [comment]
Jurassic The Hinted Ps3 emulated game

**Comment by AniLeo** [comment]
Closed as it doesn't follow anything in the guidelines
