### ISSUE TITLE
[Regression] [Linux] Build fails due to FAudio/SDL

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#13351]
### Quick summary

Build fails due to an issue with FAudio, which is apparently triggered from an outdated SDL. 

### Details

Log excerpt below.  System libsdl2-dev is indeed older (see below config), however shouldn't the updated 3rdparty SDL2 version be used in this case?
```
[795/2399] Building C object 3rdparty/FAudio/CMakeFiles/FAudio.dir/src/FAudio_platform_sdl2.c.o
FAILED: 3rdparty/FAudio/CMakeFiles/FAudio.dir/src/FAudio_platform_sdl2.c.o 
ccache /usr/bin/cc -DFAUDIO_DISABLE_DEBUGCONFIGURATION -I/home/testing/Desktop/rpcs3/rpcs3/3rdparty/FAudio/src -I/home/testing/Desktop/rpcs3/rpcs3/3rdparty/FAudio/include -I/usr/include/SDL2 -w -O3 -DNDEBUG -std=c99 -MD -MT 3rdparty/FAudio/CMakeFiles/FAudio.dir/src/FAudio_platform_sdl2.c.o -MF 3rdparty/FAudio/CMakeFiles/FAudio.dir/src/FAudio_platform_sdl2.c.o.d -o 3rdparty/FAudio/CMakeFiles/FAudio.dir/src/FAudio_platform_sdl2.c.o -c /home/testing/Desktop/rpcs3/rpcs3/3rdparty/FAudio/src/FAudio_platform_sdl2.c
/home/testing/Desktop/rpcs3/rpcs3/3rdparty/FAudio/src/FAudio_platform_sdl2.c:34:2: error: #error "SDL version older than 2.24.0"
   34 | #error "SDL version older than 2.24.0"
      |  ^~~~~
[812/2399] Building CXX object 3rdparty/llvm_build/lib/MC/MCParser/CMakeFiles/LLVMMCParser.dir/AsmParser.cpp.o
ninja: build stopped: subcommand failed.
```

### Build with regression

Most likely stems from commit 04d9693b51fe8779d5f64bf14a6ccd678e70ad21

### Attach two log files

Logfile: [build.log](https://github.com/RPCS3/rpcs3/files/10609434/build.log)

### Attach capture files for visual issues

N/A

### System configuration

* OS: Linux Mint 21.1 / kernel 5.15
* CPU: Intel I7-10870H
* GPU: Nvidia GTX 3070 / driver 525.78
* libsdl version: `libsdl2-dev/jammy-updates,now 2.0.20+dfsg-2ubuntu1.22.04.1 amd64`
* Commit tested: c0243a92d05191285f20ef22c71fd209c9116a24
* Last known good commit: c5b25fa132d8e5d0b246dea43a769e7f176885a0

**Comment by Shoegzer** [comment]
Thanks @Megamouse.  Unfortuntely it still doesn't build (it will if you use `-DUSE_FAUDIO=OFF` but I think your intention was to permit compilation regardless of this flag?).

Log: [build.log](https://github.com/RPCS3/rpcs3/files/10670602/build.log)

**Comment by Megamouse** [comment]
Just try again with the latest commit.
Also you can just set the flag to USE_SYSTEM_FAUDIO

**Comment by Shoegzer** [comment]
Thanks @Megamouse, and for the tip on the system lib.  It builds with the latest commit, and also without `USE_SYSTEM_FAUDIO` for just cubeb.
