### ISSUE TITLE
Ultra Dimension NeptuneV causes graphical issues when using RCB.

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13358]
### Quick summary

When testing this game with RCB to fix the Player Icons I stubble across an issue

### Details

The game experiences extreme geometry explosions and artefacts in visual novel cutscenes when RCB is enabled 

RPCS3+RBC:
![NPJB90544_screenshot_2023_02_05_14_34_32](https://user-images.githubusercontent.com/71127352/216825802-90cdf390-fc52-4c21-a82c-c7d8ff8e1c76.png)
![NPJB90544_screenshot_2023_02_05_14_32_50](https://user-images.githubusercontent.com/71127352/216825808-9ad2326f-d208-474a-a6e3-2c96b0f0437e.png)
RPCS3-RBC:
![NPJB90544_screenshot_2023_02_05_14_34_43](https://user-images.githubusercontent.com/71127352/216825823-509816d1-a6fc-4f0f-b31a-b9bcf3ecf788.png)
![NPJB90544_screenshot_2023_02_05_14_34_58](https://user-images.githubusercontent.com/71127352/216825829-cdc38ffc-d15f-48f9-a1f3-6b0c733d7117.png)

PS3:
https://youtu.be/xOQtOtEFmJA?t=6
https://youtu.be/xOQtOtEFmJA?t=151

### Attach a log file

[Ultra Dimension NeptuneV+RCB.log.gz](https://github.com/RPCS3/rpcs3/files/10611278/Ultra.Dimension.NeptuneV%2BRCB.log.gz)
[Ultra Dimension NeptuneV.log.gz](https://github.com/RPCS3/rpcs3/files/10611284/Ultra.Dimension.NeptuneV.log.gz)

### Attach capture files for visual issues

[NPJB90544_visual novel_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/10611288/NPJB90544_visual.novel_capture.rrc.gz)
[NPJB90544_Ingame_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/10611290/NPJB90544_Ingame_capture.rrc.gz)
[NPJB90544_VisualNovel+RCB_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/10611293/NPJB90544_VisualNovel%2BRCB_capture.rrc.gz)
https://drive.google.com/file/d/1bkqcXYSQhQrXpmQtnkMsDQaxTucS7WYs/view?usp=share_link

### System configuration

```
  SYS: RPCS3 v0.0.26-14684-8652b7d3 Alpha | master
  SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.57 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
  SYS: Operating system: POSIX, Name: Linux, Release: 5.15.89-1-MANJARO, Version: #1 SMP PREEMPT Wed Jan 18  20:37:11 UTC 2023
  SYS: Current Time: 2023-02- 4T19:08:17
  RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 525.85.5.0
  SYS: Firmware version: 4.89
```

### Other details

This also affects Fairy Fencer F [NPJB90640] as well

**Comment by Triticum0** [comment]
@kd-11 Retested this game again and #14907 partially solves the issue seems to only work if wcb and rcb are both turned on. rcb only gives you the same behavior.

Note, that using buffers comes with a performance penalty and sometimes give strange behavior like the game just randomly ran a 6fps when wcb or rcb were enabled turning it off and on again resolved the behavior but odd nevertheless.
 
Also, Fairy Fencer F had similar behavior but was far more destructive looking like memory corruption and crashing but the latter seems to be fixed with #14907 might have to make a separate issue thought properly affects both games to some extent.

**Comment by Triticum0** [comment]
Here an image of masters now with WCB and RBC:
![NPJB90544_screenshot_2024_01_02_21_21_49](https://github.com/RPCS3/rpcs3/assets/71127352/568c5cf8-29ae-44f2-b8fc-a95ce421a29f)

![NPJB90544_screenshot_2024_01_02_21_21_56](https://github.com/RPCS3/rpcs3/assets/71127352/afd84285-af4b-4803-b783-0174f5a9ef18)

**Comment by kd-11** [comment]
> Here an image of masters now with WCB and RBC: ![NPJB90544_screenshot_2024_01_02_21_21_49](https://private-user-images.githubusercontent.com/71127352/293799370-568c5cf8-29ae-44f2-b8fc-a95ce421a29f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMzUwMjMsIm5iZiI6MTcwNDIzNDcyMywicGF0aCI6Ii83MTEyNzM1Mi8yOTM3OTkzNzAtNTY4YzVjZjgtMjlhZS00NGYyLWI4ZmMtYTk1Y2U0MjFhMjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDIyMzIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNDNhMGNiMjZjMGI3MzE3ZDA2NGY2NDMxOWM5ZmFiMjhkNzlhYjY3N2Q2OGU2MzdmMzE3NDAyZjg3MjdmYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iMNpHJ40xLWdR77aEPTRe8jNf1HsL68LzwhmgqvVue8)
> 
> ![NPJB90544_screenshot_2024_01_02_21_21_56](https://private-user-images.githubusercontent.com/71127352/293799392-afd84285-af4b-4803-b783-0174f5a9ef18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMzUwMjMsIm5iZiI6MTcwNDIzNDcyMywicGF0aCI6Ii83MTEyNzM1Mi8yOTM3OTkzOTItYWZkODQyODUtYWY0Yi00ODAzLWI3ODMtMDE3NGY1YTllZjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDIyMzIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNjU4ODlkM2M1NjdlNDFhZDBmYWU5OWVkZWQ4MDY2ZGZjYzA4OTY1YjQ1YzVlY2Q3Zjg3Nzk1OGQ0NGU2MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rnb6DYYfw0fgBIC3i8z2Uu502TAGKHdKo0gUUMwUtPI)

Any issues left when using RCB+WCB? If any standard combination (outside debug tab) fixes the problem, then it can be considered solved. As I noted in https://github.com/RPCS3/rpcs3/pull/14907, there is no way to avoid the leaks without both RCB+WCB (or RDB+WDB in some games) enabled at the same time.

**Comment by Triticum0** [comment]
I would need to test the game for longer. There is a performance hit that makes the visual novel + tutorial aspect close to unplayable (stutters to 6fps to under 1 fps for a few seconds. also happens with the default setting but it less severe stutters but drops to 20 fps) 

So even if it is been fixed I don't know if I can call it solved completely.

Also Fairy Fencer F has a weird issue with graphical issues the longer you play the game. so not sure if affect this game that uses the same engine.

Fairy Fencer F graphical issues
![NPJB90640_screenshot_2023_12_18_20_12_07](https://github.com/RPCS3/rpcs3/assets/71127352/a5448bb4-d0ad-4d29-bf93-49890f6194a3)
![NPJB90640_screenshot_2023_12_18_20_17_56](https://github.com/RPCS3/rpcs3/assets/71127352/d068b9d0-69c5-4a6b-8b71-c06feba86bdd)

**Comment by kd-11** [comment]
Do the FF bugs happen with a strict setup? (WCB+WDB+RCB+RDB+CPU blit)

**Comment by Triticum0** [comment]
Yes it does and looks different from other settings
![NPJB90640_screenshot_2024_01_02_23_08_33](https://github.com/RPCS3/rpcs3/assets/71127352/f6b81adc-b52d-4846-b87e-0f68b6939459)

**Comment by kd-11** [comment]
Ok, got it. If NeptuneV bugs are not present when using WCB+RCB, close this ticket and open one for FFF. There is nothing that can be done for performance at the moment without some other architectural problems getting sorted first which will take a long time.

**Comment by Triticum0** [comment]
Thank you for the help will reopen or create a new issue if I run it into any other issues when retesting Ultra Dimension Neptune later on.

Also with the performance issue I move the game ingame as it was previously mark as playable when WCB andn RCB where disabled

**Comment by Triticum0** [comment]
Do some more testing and didn't have any graphical issues will update the wiki now.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13824294/RPCS3.log.gz)
