### ISSUE TITLE
Metal Gear Solid 4: No Input Works in Main Menu

### ISSUE THREAD

**Issue by TheManiacHS** [RPCS3/rpcs3#13360]
### Quick summary

When Starting Metal Gear Solid 4 i am able to skip any starting stuff and even press start to go to the main Menu.
But when in the Main Menu No Input works anymore
Tested with:
- Keyboard
- Xbox One Gamepad
- Turtle Beach Xbox Gamepad

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10662287/RPCS3.log)

**Comment by AniLeo** [comment]
Duplicate of #11238
