### ISSUE TITLE
error 0x8002291 on Tekken 6

### ISSUE THREAD

**Issue by awsoiree** [RPCS3/rpcs3#13371]
### Quick summary

Trophies do not load for Tekken 6

### Details

When I boot up Tekken 6 on rpcs3, I get an error message titled error 0x8002291, saying that the trophies failed to lead and I needed to close the game. Any fix for this?

### Attach a log file

RPCS3.log.gz

**Comment by YuriNator557** [comment]
1. This is not the full error code, ps3 errors normally have 8 digits
2. The log file here did not upload
3. This reads more like a support request, please go to the official support channels in either the discord server or the forums
