### ISSUE TITLE
VK_ERROR_DEVICE_LOST starting any game on Intel ARC

### ISSUE THREAD

**Issue by jacob1218** [RPCS3/rpcs3#13373]
### Quick summary

Using an Intel ARC GPU with Vulkan causes a crash before the game window opens, every time, in any game.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10680308/RPCS3.log)

### System configuration

CPU: Ryzen 5 3600X
GPU: Intel ARC A770 16GB
RAM:32GB
GPU driver version: 31.0.101.4091

### Other details

I was told i needed to create a debug output log, but I don't know how to do that, Is there a special option i need?

**Comment by Darkhost1999** [comment]
A debug log is created after you install this installer
https://vulkan.lunarg.com/sdk/home
Then go to debug tab -> enable debug output and save.
Then it's just like any other log.

**Comment by jacob1218** [comment]
Updated log with debug output enabled
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10680403/RPCS3.log)

**Comment by jacob1218** [comment]
closed, Twitch Studio overlay was causing the crash
