### ISSUE TITLE
Random Audio Mute in SoulCalibur 5

### ISSUE THREAD

**Issue by itsLoneDevil** [RPCS3/rpcs3#13375]
### Quick summary

https://user-images.githubusercontent.com/22559210/217604315-6ba567db-2faf-4c2a-9a06-9a625350a38d.mp4

### Details

Audio crashes at random times in any match regardless of settings.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10688256/RPCS3.log)

**Comment by Risusama** [comment]
Pirated game.

**Comment by AniLeo** [comment]
Non default settings being used either way, it is invalid as is

**Comment by Rex000** [comment]
> Pirated game.

How do you know that?
