### ISSUE TITLE
Booting failed. Edat not converting trial to full game

### ISSUE THREAD

**Issue by Rex000** [RPCS3/rpcs3#13383]
### Quick summary

Game trial not being converted to full game by an edat.

### Details

I extracted the pkg of a game in folder form and copied the game's edat file to RPCS3's "exdata" folder. Then I added the game to RPCS3 using the "Add game" option. But when trying to run the game it shows "Booting failed: No bootable content was found" error.

This error doesn't seem to occur in games(in folder form) that don't have a trial.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10712912/RPCS3.log.gz)

**Comment by MSuih** [comment]
Hdd games should be installed to `dev_hdd0/game`, storing them in nonstandard locations is not officially supported. Does the error happen when the game is in proper location?

**Comment by Rex000** [comment]
No it doesn't. The thing is that I want to have one folder for each game containing the game files plus any updates all merged together instead of keeping pkg backups of every game which consumes double the space. It's way more organized for me this way. The games do work but trial games stay as trial. Copying the edats to edata folder brings up the error. It should be supported imo.

**Comment by Rex000** [comment]
No it doesn't. This should be supported IMO.

**Comment by Rex000** [comment]
No it doesn't. This should be supported IMO. The games do work in folder form but trial games stay as trials and copying edats to the edata folder brings up the said error.

**Comment by Rex000** [comment]
No it doesn't. The games do get added to RPCS3 in folder form though and seem to work fine. But the only issue right now is that trial games stay as trials and copying edats to the edata folder brings up the said error.

**Comment by Megamouse** [comment]
You should remove all entries that end with C00 from the games.yml and try again once the new build is available

**Comment by Rex000** [comment]
Unable to download the new build. Auto-updater isn't detecting it.

**Comment by MSuih** [comment]
The MacOs version failed to build due to connection issue and the auto updater can't offer different versions for different operating systems. You can download windows and linux versions from [the build history page](https://rpcs3.net/compatibility?b), for windows updating works by just overwriting the files from download over your current version.

**Comment by Rex000** [comment]
Games are working now, thanks!
