### ISSUE TITLE
Installation of firmware crash.

### ISSUE THREAD

**Issue by PiggyAncer** [RPCS3/rpcs3#13382]
### Quick summary

On the installation of the firmware or on trying to run anything with rpcs3 i get the error:
fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\device.cpp:646[:3], in function create) (error=0xcb)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error) (error=0xcb)

I have no clue what is going on. any possible help?
<img width="492" alt="image" src="https://user-images.githubusercontent.com/125102174/218228753-4748990c-0487-4252-9bc6-579b48c74af2.png">

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10712222/RPCS3.log)

### System configuration

Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor

### Other details

It happens on install of firmware and whenever i try to launch stuff from rpcs3

**Comment by Boiiiiiiiiiiiiiiiiiiii** [comment]
Don't put RPCS3 in your Onedrive. Onedrive will break RPCS3.
