### ISSUE TITLE
Tank Battles [NPUB30154] - Resolution scale doesn't seems to work in this game

### ISSUE THREAD

**Issue by metalslayer** [RPCS3/rpcs3#13393]
### Quick summary

Tank Battles [NPUB30154]
I don't know why. Maybe game using sprites. But if it's 3D game, resolution scale doesn't seems to work in this game.

### Attach a log file

https://discord.com/channels/272035812277878785/319224795785068545/1074467491293708390
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10717564/RPCS3.log.gz)

**Comment by FlexBy420** [comment]
Resolution scale is expected to not work with every game, its a hack after all
