### ISSUE TITLE
Dark Mist [NPHA80030] freezes when trying to save-state

### ISSUE THREAD

**Issue by Imaynotbehere4long** [RPCS3/rpcs3#13394]
### Quick summary

Trying to create a save-state in Dark Mist causes the emulator to freeze indefinitely. No save-state file is created.

### Details

At first, it happened to me in one of the 0.0.25 builds, so I updated to the latest one (0.0.26-14712-39760189), but it still happens, so the problem isn't build-exclusive or a regression. It also isn't area-specific: the first time I tried to save-state was in level 5, and all subsequent tests were done at the beginning of level 1 (except two: once in the How To Play section and once during the "auto-save" message at the beginning), all freezing the emulator in the same way. I also have Write Colour Buffer enabled, but that didn't help, either. I even tried enabling Force CPU Blit, as recommended by the Help:Save State page, but that only resulted in the player character becoming invisible; savestates still cause the emulator to freeze (and the program remains unresponsive even after waiting for several minutes). At no point was a save-state file ever created. Finally, I tried creating a save-state in a different game (Harmony of Despair NPEB00563) and it worked just fine, so it's definitely an issue with Dark Mist specifically, not a problem on my end.

The 1st log was when I had Force CPU Blit enabled; the 2nd log was when I remembered to click "Log All" under Kernel Explorer before attempting to save-state.

P.S. I never edited the config.yml file.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10720327/RPCS3.log)
[RPCS3 2nd.log](https://github.com/RPCS3/rpcs3/files/10720473/RPCS3.2nd.log)

### Other details

This is especially annoying because the 1.00 version doesn't save your progress on its own. You're told--in no uncertain terms--that "this game does not have a stage select or other feature that allows starting from the middle of the game."

**Comment by Imaynotbehere4long** [comment]
UPDATE: Save-states also freeze the 1.01 version of the game, as well as the version with the expansion pack (but at least those support regular saves). It *almost* worked during the auto-save message at the beginning when it didn't before, but loading the save-state resulted in a black screen.

**Comment by elad335** [comment]
Closing until reported to be not fixed because there were lots of related fixes recently.
