### ISSUE TITLE
verification error

### ISSUE THREAD

**Issue by migueola23** [RPCS3/rpcs3#13400]
### Quick summary

I was trying to run skate 3 on the emulator and it doesn´t work

### Details

F {RSX [0x00017d4]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\GL\glutils\sync.hpp:45[:4], in function check_signaled)

### Attach a log file

rpcs3.exe

### Attach capture files for visual issues

![image](https://user-images.githubusercontent.com/73402379/218792516-20125116-7af1-4ea6-8e33-6351607007ed.png)
![image](https://user-images.githubusercontent.com/73402379/218792607-e1afc033-1fe0-4693-ac8a-535edb8c36ba.png)
![image](https://user-images.githubusercontent.com/73402379/218793343-57737f4f-8dd3-454f-b918-a4b0100eb256.png)

### System configuration

idk my pc components, I just know it used to have windows 7 and it has a intel core i5

**Comment by MSuih** [comment]
Help requests should be submitted to our Discord, not on GitHub.
