### ISSUE TITLE
Vibration don't work in no-gui mode

### ISSUE THREAD

**Issue by coolllman** [RPCS3/rpcs3#13404]
### Quick summary

Vibration don't work in no-gui mode, but work great in gui mode, sdl with dualshock4

### Attach a log 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10756119/RPCS3.log)

### System configuration
Windows 10
I7 11700 rtx3060

**Comment by coolllman** [comment]
I play with ds4 and xbox controllera and sdl good choice for both, and its bug

**Comment by Megamouse** [comment]
works fine for me
