### ISSUE TITLE
GoW HD Won't get past loading screen

### ISSUE THREAD

**Issue by creeperbowling** [RPCS3/rpcs3#13401]
### Quick summary

GoW HD won't get past the initial loading screen

### Details

So I'm basically trying to launch GoW HD and it launches and compiles perfectly well, until it's just about to reach the main menu. Sometimes before the game freezes completely I hear the main menu sound for less then a second and then everything stops working completely, both game and launcher. I'm forced to shut down rpcs3 completely from task manager as it stops responding completely.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10745733/RPCS3.log)

### System configuration

OS: Windows 10 Pro Version 10.0.19044
CPU: AMD Ryzen 5 3600
GPU: GTX 1080
GPU Driver (System format): 31.0.15.2849 
GPU Driver (NVIDIA format) 528.49
RAM: 16GB DDR4

**Comment by MSuih** [comment]
The fatal error here is
```
Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\VKGSRender.cpp:1083[:2], in function on_vram_exhausted)
```

**Comment by kd-11** [comment]
Yea, something if broken with the GPU driver here. We're not able to allocate any VRAM. Is there a ramdisk stored on VRAM or something?

**Comment by creeperbowling** [comment]
Yeah, everything is standard so I guess I'll try with DDU and reinstall, I'll keep you updated

**Comment by creeperbowling** [comment]
It's now working fine and as intended, thank you guys, I really appreciate it.
