### ISSUE TITLE
Unknow stencil op

### ISSUE THREAD

**Issue by PZerua** [RPCS3/rpcs3#1340]
Using DX12 and recompilers in Shovel Knight, after some loading the game shows: 
"Unknow stencil op used 8507, please report this to a developer."

I have attached the log. It could be interesting to @vlj .

[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/60162/RPCS3.txt)

**Comment by Zangetsu38** [comment]
Fixed why my PR 
but now i have this 
>E {SPU[0x42] Thread (FMOD)[0x176c4]} Exception: HLE function not registered (PC=0x176c4)
(in file Emu\Cell\SPUThread.cpp:1193, in function SPUThread::stop_and_signal)

**Comment by danilaml** [comment]
@PZerua can you confirm that the issue is solved?

**Comment by PZerua** [comment]
@danilaml Ups, sorry. Yes It's fixed.

**Comment by yaaaaa** [comment]
Shovel Knight is fully playable?
