### ISSUE TITLE
[BLUS31201] Need for Speed Rivals: Black screen issue

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#13414]
### Quick summary

It sometimes shows me a black screen when im driving through different areas like near the mountains or buildings, and I'm not sure if its a regression or a bug.

### Details

![black screen](https://user-images.githubusercontent.com/125112932/219881310-6f44009d-4745-4658-a583-1a868d6dde4d.PNG)

It doesn't have this issue on a real PS3 but I'm sure it only happens on RPCS3 with NVIDIA GPUs. I dont think AMD GPUs has this issue, maybe someone can test it on a AMD GPU to see if it doesnt only happen on NVIDIA or not.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10774880/RPCS3.log.gz)

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 528.49.0.0 | Windows 10 Pro 22H2

### Other details

I'm pretty sure it has similar issues with "Need for Speed Most Wanted 2 prototype - black screen on NVidia under certain conditions"

Note: I am unable to send capture files because it gives me this weird error like "**F {RSX [0x1015de40]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\VKQueryPool.cpp:45[:4], in function poke_query)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error)**"

**Comment by Darkhost1999** [comment]
I got a gtx 1660 Super. Can confirm that this black screen has been a thing even since before the turing issues was fixed. But for me the black screen only occurs for approximate 0.5 seconds or less. It's just a quick flash and gone. It's annoying and capturable but also very infrequent.
My bigger concerns are with rapid response timers being illogical and wrong. But I don't have a fix for that.

How long does the black screen last for you? Is it for a longer period of time?

**Comment by Ordinary205** [comment]
It only lasts longer if i stopped the car at the exact moment, however when I turned the camera around the black screen is gone, very strange.

**Comment by Ordinary205** [comment]
Here are four screenshots when I turn the camera around:

Left:
![left side](https://user-images.githubusercontent.com/125112932/219884842-c36456b8-896b-4caa-8dbb-6f74ca5649a7.PNG)

Right:
![right side](https://user-images.githubusercontent.com/125112932/219884851-d93bcfe5-a36c-41af-820d-ca2d7c3d5c06.PNG)

Behind:
![behind side](https://user-images.githubusercontent.com/125112932/219884870-d48ead6b-6482-44c2-abc5-eade587fc1b2.PNG)

Forward:
![forward side](https://user-images.githubusercontent.com/125112932/219884884-aab90c9a-8787-4616-aa0c-1c52d7375ad0.PNG)

I can't send the clip because the file is too large.

**Comment by Ordinary205** [comment]
#7458

**Comment by Ordinary205** [comment]
The black screen seems to be fixed, and I dont know which PR actually fixes this bug.
