### ISSUE TITLE
[Feature request] Mouse to GunCon 3 cursor input

### ISSUE THREAD

**Issue by wilonwuff** [RPCS3/rpcs3#13411]
### Quick summary

[Input] Mouse handling for GunCon 3 input, similar to the current 'Mouse to PSMove input' features

### Details

PSMove mouse handling is usually a great solution for playing lightgun games, but not if the game doesn't support PSMove; such as in the case of Time Crisis 4.

I'd really like to play this game with a mouse or lightgun (because playing lightgun games with a controller is terrible), but that means having the mouse movements converted to Guncon 3 input. I'm hoping that this wouldn't be any more complex to implement than PSMove- Could I please request it be added?

**Comment by dudesh34** [comment]
### Hi, is there any progress on it? will be amazing to play the stand alone version of time crisis 4 without the annoying crosshair that drag on the screen when using sinden/gun4ir + it will fix the input lag that time crisis 4 has in the razing storm version.

**Comment by jamesgalllla** [comment]
uhh... Is this still being worked on? I love Time Crisis 4 and would love to play it without the annoying crosshair. Or maybe someone could make a patch to remove it? I dunno it seems like something simple but I guess must be difficult if no ones done it yet

**Comment by dudesh34** [comment]
> uhh... Is this still being worked on? I love Time Crisis 4 and would love to play it without the annoying crosshair. Or maybe someone could make a patch to remove it? I dunno it seems like something simple but I guess must be difficult if no ones done it yet

sadly no, seems no one knows how to emulate the guncon 3 for rpcs3.

**Comment by wilonwuff** [comment]
It's been added? :D Wooooooo! Ty~
