### ISSUE TITLE
[Regression] Some game using the Creat Engine seem to crash (#12544 or #12523)

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13422]
### Quick summary

Some games use the Creat Engine with a memory access violations.

### Details

When going through some of the missing demos I stumble across a bug with the Creat Engine game with causes them to crash with:
Access violation writing location 0x0 (unmapped memory)
or Access violation reading location 0x10 (unmapped memory)

There are 5 games I have tested with crashing issues due to this bug:

1. Mushroom Wars (#12772)
2. Hamsterball (#12448)
3. TerRover
4. Sky Fighter (#12642)
5. Labyrinth Legends

The untested game may be affected.

1. Magic Orbz (Pre MW)
2. Alien Havoc
3. Bubble Trubble (Post MW)
4. Wakeboarding HD
6. Panda Craze
7. Test Yourself

Tested games not affected.
1. Cuboid
2. Digger HD
3. Germinator
4. Smash Cars
5. Pinballistik (Thought suffers from the freezing like Sky Fighter)

I found out that turning on Accurate SPU DMA Fixes the issue in all cases.
Seem the regression started in Rpcs3-v0.0.23-14068-a74d3005 from what
Schroedingers-Cat said in #12642 but as of now have not tested all the games to test for sure if that correct

### Build with regression

v0.0.23-14068-a74d3005

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9543073/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9543164/RPCS3.log.gz)
[TerRoverMasters.log.gz](https://github.com/RPCS3/rpcs3/files/10828817/TerRoverMasters.log.gz)
[Labyrinth LegendsMasters.log.gz](https://github.com/RPCS3/rpcs3/files/10829257/Labyrinth.LegendsMasters.log.gz)

### System configuration

RPCS3 v0.0.26-14724-3922f76a Alpha | master | FW 4.88 | 5.15.85-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (526.47)

**Comment by Panzasiniestra** [comment]
Wakeboarding HD require Accurate SPU DMA: ON

**Comment by Triticum0** [comment]
@Megamouse Can I close this issue as Accurate SPU DMA has been added to the  Advanced core setting from Debug settings so can added to the playable category with it enabled?
