### ISSUE TITLE
Occasional hang in Sonic CD using llvm ppu recompiler.

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1342]
Other titles might be affected too. Haven't experienced it before.
If you run Sonic CD with ppu llvm and wait for some time and play a few levels (usually 5-7 minutes is enough) it will hang, but not completely. Sound will still be playing, although very distorted, and emu will be doing, what it seems like, some sysprx mutex stuff. But the picture will stop completely.

**Comment by vlj** [comment]
It's worse with Disgaea 4 it hangs in less than 5 sec. After Burner Climax hang quickly too, either in menu or in intro cutscene. The regression is likely not that old since I remember having tried After Burner with llvm properly a month ago.

**Comment by vlj** [comment]
Actually it only happens if I use Spurs lle lib. So it looks like LLE and LLVM doesn't work together.

**Comment by danilaml** [comment]
@vlj I experienced it before LLE (issue was created before official LLE announcement).
So if anything LLE only increases chances of hang.

**Comment by tambry** [comment]
@danilaml LLE has been functional for almost a year now. It simply wasn't "public". Anyone that figured it out though, could use it.

**Comment by danilaml** [comment]
@tambry I know. I just also now that I didn't use it when I created this issue =)

**Comment by vlj** [comment]
I'm using Disgaea 4 instead of Sonic CD since it's easier to spot the bug, it looks like 	ADDI instruction triggers the hang. If I interp it there is no hang within the first second of the game.

**Comment by vlj** [comment]
The faulting block in Disgaea 4 is :

https://gist.github.com/vlj/2920e12e460dbb64259f
