### ISSUE TITLE
rpcs3 hangs if you boot a game with save state a second time on Linux

### ISSUE THREAD

**Issue by hrzhu** [RPCS3/rpcs3#13437]
### Quick summary

Title is self-explanatory. This issue only happens on Linux not Windows.

### Details

Steps to reproduce:
1. Open RPCS3
2. Boot a game with save sate. After the game is completely loaded, stop the emulation.
3. Boot the game with save state a second time. RPCS3 hangs.

I've tried two different games, same behavior.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10813053/RPCS3.log)

RPCS3 hangs. RPCS3.log.gz is empty so I upload RPCS3.log. 

### System configuration

OS: Kubuntu 22.04.2 LTS x86_64 
Kernel: 5.19.0-1017-lowlatency 
DE: Plasma 5.24.7 
WM: KWin 
CPU: 11th Gen Intel i7-11700
GPU: AMD ATI Radeon RX 6700 XT

**Comment by MegPredator** [comment]
for me launching any game for the second time causes it to hang

**Comment by hrzhu** [comment]
This issue is no longer present on latest RPCS3.
