### ISSUE TITLE
PPU LLVM loading crash on Pro Evolution Soccer 2018 (BLUS31612)

### ISSUE THREAD

**Issue by DarthVady** [RPCS3/rpcs3#13433]
### Quick summary

the game Pro Evolution Soccer 2018 (BLUS31612) does not load

### Details

A problem with the startup of the game Pro Evolution Soccer 2018 (BLUS31612) does not start with the LLVM PPU decoder, the emulator closes by itself, but when I switch to STATIC PPU the game runs more with graphical errors

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10808769/RPCS3.log)

### System configuration

RPCS3 v0.0.26-14740-a9f399d6 Alpha | master
AMD Ryzen 5 5600G with Radeon Graphics | 12 Threads | 15.79 GiB RAM | TSC: 3.900GHz | AVX+ | FMA3
NVIDIA GeForce RTX 3080

**Comment by AniLeo** [comment]
Needs retest with latest build

**Comment by DarthVady** [comment]
Even with the most recent compilation it is not working the emulator closes by itself when using the PPU (LLVM) it only opens with the PPU (static) but with graphic errors

**Comment by Asinin3** [comment]
Rename issue to have "crashes with PPU LLVM" in the title.
