### ISSUE TITLE
BLES01039 FIGHT NIGHT CHAMPION -  Can't install patch

### ISSUE THREAD

**Issue by 2banditos** [RPCS3/rpcs3#13430]
### Quick summary

Can't install patch 1.02

Error Message:

U PKG TODO: Entry with unknown type or padding: type=0x80000101, pad=0x0, name='USRDIR/EBOOT.BIN'

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10803081/RPCS3.log)

**Comment by MSuih** [comment]
According to the log all folders and files were successfully created and no errors happened. The message you added is a TODO, it is not an error on it's own.

If you can't see or access the dlc, ask for help on the help channel of our Discord.
