### ISSUE TITLE
XInput issue with some games using DS4Windows

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1343]
Happens in games 4 Elements HD (NPUB30347), flOw (NPUA80001) and Terraria (NPUB30943). Another games, like Arkedo series works fine.

HLE: W {PPU Thread[0x1] (main_thread)[0x00464828]} sys_io: cellPadInit(max_connect=7)
HLE: W {PPU Thread[0x1] (main_thread)[0x004648c8]} sys_io: cellKbInit(max_connect=7)
HLE: S {PPU Thread[0x1] (main_thread)[0x004648c8]} Last function: cellKbInit (0x433f6ec0)
G: ! {PPU Thread[0x1] (main_thread)[0x004648c8]} Registers:
...
G: E {PPU Thread[0x1] (main_thread)[0x004648c8]} Exception: Invalid Keyboard Handler Mode 2
(in file rpcs3.cpp:98, in function Rpcs3App::OnInit::<lambda_9a318e9e5c43e5fa35a8c171964d1c61>::operator ())

full log: http://pastebin.com/szJtKcs3

**Comment by danilaml** [comment]
Just for the record.
```
<jakethesnake651> BlackDaemon i bet the xinput issue is from https://github.com/RPCS3/rpcs3/blob/master/rpcs3/rpcs3.cpp#L94
<jakethesnake651> if your talking about the issue you posted on github
<jakethesnake651> that should be config.io.keyboard_handler_mode
```

**Comment by B1ackDaemon** [comment]
Got it worked this way:

	callbacks.get_kb_handler = []() -> std::unique_ptr<KeyboardHandlerBase>
	{
		switch (auto mode = rpcs3::config.io.pad_handler_mode.value())
		{
		case io_handler_mode::null: return std::make_unique<NullKeyboardHandler>();
		case io_handler_mode::windows: return std::make_unique<WindowsKeyboardHandler>();
		case io_handler_mode::xinput: return std::make_unique<WindowsKeyboardHandler>();
		default: throw EXCEPTION("Invalid Keyboard Handler Mode %d", +(u32)mode);
		}
	};
