### ISSUE TITLE
"Show shader compilation hint" doesn't effect the visibility of shader compilation hints

### ISSUE THREAD

**Issue by Silquetoast** [RPCS3/rpcs3#13435]
### Quick summary

The setting "Show shader compilation hint" doesn't effect the visibility of shader compilation hints.

### Details

The setting "Show shader compilation hint" doesn't effect the visibility of shader compilation hints. Toggling the tickbox on ***or*** off will not hide the shader compilation hint. 

### Attach a log file

https://drive.google.com/file/d/1UoKuh35redVaVcCrGmCnpM2G-CWitthk/view?usp=share_link

### Attach capture files for visual issues

![Eshyy2DFBG](https://user-images.githubusercontent.com/6046602/220805379-66a63f41-0e3d-43bd-bfa6-090562c6104c.jpg)

### System configuration

CPU: AMD Ryzen 9 3900X 12-Core Processor (4.15 GHz)
RAM: 32.0 GB
Edition	Windows 10 Education
Version	22H2
Installed on	‎1/‎26/‎2022
OS build	19045.2604
Experience	Windows Feature Experience Pack 120.2212.4190.0
GPU: NVIDIA GeForce RTX 2070 SUPER

**Comment by solarmystic** [comment]
If a game already has its own custom settings profile, the option needs to be unticked at the custom profile. Doing it at the global rpcs3 config will not work. 
![image](https://user-images.githubusercontent.com/4345150/220811844-6539ab89-c339-45e4-908d-153e2803c704.png)

**Comment by Darkhost1999** [comment]
Works fine on my pc.
Global, custom and home menu configs tested.
Remember home menu will not be applied for consecutive boots. So if you configured there do not expect the next time you boot your game that that is your config. Make sure to check it.

**Comment by MSuih** [comment]
Closing as there doesn't seem to be any bug or regression involved.
