### ISSUE TITLE
[Regression] RPCS3 hangs when you try to stop emulation

### ISSUE THREAD

**Issue by hrzhu** [RPCS3/rpcs3#13447]
### Quick summary

regression introduced by https://github.com/RPCS3/rpcs3/pull/13398. Last working version 0.0.26-14743(commit 6b30cda).

### Details

Step to reproduce.
1. Start RPCS3. Boot a game.
2. Stop emulation. RPCS3 hangs.

I've tested 0.0.26-14758 on Windows and 0.0.26-14757 on Linux. Both version have this issue. Last working version is 0.0.26-14743 (commit 6b30cda).

### Build with regression

0.0.26-14757

### Attach two log files

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/10830848/RPCS3.zip)

### System configuration

Windows 10 22H2/Kubuntu 22.04.2
i7 11700
AMD 6700XT

**Comment by Sweetpotato-bop** [comment]
I have the same regression

**Comment by ISuckGood** [comment]
i have the same . and also if i try jak1 to boot it just hangs

**Comment by MineSAT** [comment]
Same regression, in my case the version that works without problem is: #14725
