### ISSUE TITLE
EnhanceDoubleSpinBox 'Texture LOD Bias Addend' was used with an invalid type

### ISSUE THREAD

**Issue by italoghost** [RPCS3/rpcs3#13440]
### Quick summary

After changing my configuration using the defaults specified at [Help:Default Settings](https://wiki.rpcs3.net/index.php?title=Help:Default_Settings) I am receiving the error of the title:

```
F EnhanceDoubleSpinBox 'Texture LOD Bias Addend' was used with an invalid type
```

### Details

After changing my configuration using the defaults specified at [Help:Default Settings](https://wiki.rpcs3.net/index.php?title=Help:Default_Settings) I am receiving the error of the title:

```
F EnhanceDoubleSpinBox 'Texture LOD Bias Addend' was used with an invalid type
```
This error appears after I enter the "Config" menu. If I try to launch a game, another error appears:

```
E CFG: cfg::try_to_float('0,000000'): invalid float
```

The value generated on the "config.yml" for the "Texture LOD Bias Addend" parameter is `0,000000`.

I tried to change to `0`, `0.000000`, `0.00`, `3`, `+3` without success.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10818586/RPCS3.log)

### System configuration

[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.1.12-zen1-1-zen
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 2700 Eight-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.5 GB
Swap:            4.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 570 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.12-zen1-1-zen)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.6
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.6
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.6
Vulkan:          Supported

**Comment by Megamouse** [comment]
We only support official builds

**Comment by italoghost** [comment]
I downloaded the AppImage, removed the ~/.config/rpcs3 folder and started again.

I changed the same options that I did before and the same errors appeared:

![image](https://user-images.githubusercontent.com/48540550/221043717-d7c12cd9-66e0-4343-b9c2-6dc2cdad00c1.png)

**Comment by Megamouse** [comment]
how did you change the config?

**Comment by italoghost** [comment]
Now I even deleted the ~/.cache/rpcs3 and deleted again the ~/.config/rpcs3 folder. Just by opening the "Config" button the error appears:

![image](https://user-images.githubusercontent.com/48540550/221045009-8052b202-2d66-4b51-b2b2-e52586da7a57.png)

I changed by the interface, by clicking the "Config" button.

**Comment by italoghost** [comment]
I wonder if it has something to do with my system being configured to Brazilian Portuguese, as the float indicator is a comma (`,`) not a dot (`.`).

**Comment by Megamouse** [comment]
most likely.
post your GuiConfigs/CurrentSettings.ini file as well ()

**Comment by italoghost** [comment]
Here
[CurrentSettings.zip](https://github.com/RPCS3/rpcs3/files/10819197/CurrentSettings.zip)

**Comment by italoghost** [comment]
Thanks! It worked!
