### ISSUE TITLE
Inconsistent behavior of game list

### ISSUE THREAD

**Issue by Rex000** [RPCS3/rpcs3#13441]
### Quick summary

Game list unable to consistently highlight the respective game when a letter key is pressed on the keyboard.

### Details

When you're on the game list and press a letter key on the keyboard, the highlight should jump on the first game that starts with that letter. Only some times it happens accurately but more often than not it fails to do the jump.

### Attach a log file

Not required

**Comment by Megamouse** [comment]
This is a Qt bug at best and shouldn't be part of our issue tracker.
Depending on how fast you type the internal search seems to have issues.
I don't see any way to fix this on our side without wasting a lot of time, only to confirm that it's a Qt bug anyway.
