### ISSUE TITLE
[Regression] Copies of players in LAN lobbies in Armored Core: For Answer

### ISSUE THREAD

**Issue by 1nveigh** [RPCS3/rpcs3#13445]
### Quick summary

When joining a LAN game of Armored Core: For Answer players on version v0.0.26-14743-6b30cdac of RPCS3 have a copy of themselves appear in the lobby. Players who have copies of themselves cannot host games or play with other players having the same issue.

### Details

When joining a LAN game of Armored Core: For Answer, players on version v0.0.26-14743-6b30cdac of RPCS3 have a copy of themselves appear in the lobby. 

Players with a copy cannot host or play with other players who are experiencing the same bug - they are able to play with players who do not have copies, but to be able to do so the host needs to have the copied player join the game first, then kick the copied player. Once the copied player has been kicked once, it will remove their copy from the lobby without removing the actual player. From that point on, other non-copied players are able to join the game.

If a game is started while two copied players are in the same lobby, or started before the copied player is kicked, the game will load infinitely and never start requiring all players to close and reopen the emulator.

![image](https://user-images.githubusercontent.com/122016349/221334759-a9431352-e3e1-441d-a0c4-92e010c1eb83.png)

### Build with regression

v0.0.26-14743-6b30cdac

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10830176/RPCS3.log.gz) - Broken

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10830184/RPCS3.log.gz) - Working

**Comment by RipleyTom** [comment]
For xlink kai and radmin and other lan tools it's highly recommended to set bind address to the IPv4 address of the interface for said tool in the custom config of the game that requires LAN use.

It will forces all interaction to be limited to that interface and forces local ip to be the address of that interface.
