### ISSUE TITLE
Freezes randomly during a game - International Cricket 2010

### ISSUE THREAD

**Issue by DanielRGregory** [RPCS3/rpcs3#13448]
### Quick summary

Game runs fine and then randomly freezes during a match 
Happens both on my Windows PC and Steam Deck

### Details

No pattern to the time the game crashes. Just seems like if I play for longer than 10 minutes it will eventually freeze at some point

### Attach a log file

![RPCS3 Cricket Log File](https://user-images.githubusercontent.com/126327104/221353936-3c743364-17c4-455c-aa01-870b1cd8bc52.JPG)

**Comment by Asinin3** [comment]
No log file, no steps to reproduce, no clear indication of how or why this happens.. why raise an issue without anything useful?

Closed
