### ISSUE TITLE
MotoGP 09/10 Crashes when making it into a race

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13443]
### Quick summary

The crashes when starting the race starts

### Details

When testing this game and making it into a race once the race starts, the game crashes with this message.
F {RSX [0x025382c]} SIG: Thread terminated due to fatal error: Verification failed
(in file ../rpcs3/Emu/RSX/Program/VertexProgramDecompiler.cpp:538, in function Decompile) (errno=110=Connection timed out)

### Attach a log file

[MotoGP 09.10.log.gz](https://github.com/RPCS3/rpcs3/files/10828361/MotoGP.09.10.log.gz)

### System configuration

RPCS3 v0.0.26-14743-6b30cdac Alpha | master | FW 4.88 | 5.15.85-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (526.47) 

### Other details

Changing Fifo Accuracy doesn't fix the issue.

**Comment by Asinin3** [comment]
Retest

**Comment by fuhuan416** [comment]
- SYS: RPCS3 v0.0.29-15674-d335d356 Alpha | master
- SYS: 12th Gen Intel(R) Core(TM) i9-12900H | 20 Threads | 15.71 GiB RAM | TSC: 2.918GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-10-05T19:10:52
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 3050 Ti Laptop GPU' running on driver 537.13.0.0
- RSX: Found Vulkan-compatible GPU: 'Intel(R) Iris(R) Xe Graphics' running on driver 0.404.286 x2
- SYS: Firmware version: 4.90

Still same issue,
(in file D:\a\1\s\rpcs3\Emu\RSX\Program\VertexProgramDecompiler.cpp:538[:4], in function Decompile)
But without  (errno=110=Connection timed out)

**Comment by kd-11** [comment]
Just before the crash, you can see the analyzer sees the broken shader:
`RSX: vp_analyser: Possible infinite loop detected`
The crash happens when we try to compile it. The jump table is fucked up. Normally PS3 seems to ignore malformed instructions, probably why this broken code still executes on real hardware.
