### ISSUE TITLE
Of orcs and Men is crashing after merging #1344

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#1345]
After merging https://github.com/RPCS3/rpcs3/pull/1344 game crashes before intro

[LOG](https://mega.nz/#!TAkURAgA!ppg8YJdt2atl6hPRC1yeC8uBaaMuNlssGU3eDvSnt6s)

**Comment by tambry** [comment]
Pinging @vlj, so he sees this-

**Comment by vlj** [comment]
What are the messages in "output" inside Visual Studio when debug output mode is enabled ?

**Comment by JohnGodgames** [comment]
I don't know what do you want from me exactly @vlj 

there is a screenshot from a VS :
![orc debug 1](https://cloud.githubusercontent.com/assets/11453507/11878706/aad85dd2-a4f7-11e5-80d8-78b2fc6f8b80.PNG)

**Comment by paulsapps** [comment]
"output" is the tab in the bottom right pane, you have selected "call stack" instead.

**Comment by JohnGodgames** [comment]
Yeah I saw that, but nothing useful right there...I'm doing something wrong.Is there any guide how to do that properly or @vlj can you help?

**Comment by tambry** [comment]
@JohnGodgames Did you enable debug output mode, as @vlj instructed?

**Comment by danilaml** [comment]
@JohnGodgames (debug output is located in graphics settings btw)

**Comment by JohnGodgames** [comment]
I don't see anything usefull...

Xaudio:
![debug 2](https://cloud.githubusercontent.com/assets/11453507/11885855/aaf00b2c-a523-11e5-9522-f3d926a0846b.PNG)

audio null:
![debug 3](https://cloud.githubusercontent.com/assets/11453507/11885859/b0811446-a523-11e5-9597-8a1c1f29422a.PNG)

**Comment by B1ackDaemon** [comment]
I also getting crash: http://pastie.org/private/wa4jhj9nmxhqpacphhdfsg

**Comment by vlj** [comment]
@B1ackDaemon thanks!

**Comment by Xcedf** [comment]
fixed by https://github.com/RPCS3/rpcs3/pull/1365

**Comment by tambry** [comment]
@Xcedf Have the graphics been improved by #1365?

**Comment by Xcedf** [comment]
Nope, in this game everything pretty much the same

**Comment by JohnGodgames** [comment]
fixed by #1365
