### ISSUE TITLE
TEKKEN TAG TOURNAMENT HD [NPUB30590] - Some stages have 35~45 FPS

### ISSUE THREAD

**Issue by Rex000** [RPCS3/rpcs3#13454]
### Quick summary

Title

### Details

I find it very weird because I can run much heavier titles just fine, including Tekken 5 DR.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10834151/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Individual performance problems are not valid issues.
Especially not on weak hardware.
