### ISSUE TITLE
[BLUS30442] Midnight Club Los Angeles - Complete Edition: FPS drop when driving

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#13452]
### Quick summary

When I'm driving through different areas I get heavy/small FPS drop.

For example when I'm driving this area the FPS went from 30 to 19:
![rpcs3 exe 2023 02 26 - 12 37 39 01 - frame at 1m6s (2)](https://user-images.githubusercontent.com/125112932/221401539-3223e41f-1b9b-40fc-a06b-b48d029bdcb2.jpg)

### Details

The real PS3 doesn't have this issue but only on RPCS3.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10833292/RPCS3.log.gz)

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 528.49.0.0 | Windows 10 Pro 22H2

### Other details

The weird thing is that during nighttime the game runs faster than daytime?

Nighttime: (almost at 30 FPS)
![rpcs3 exe 2023 02 26 - 12 42 38 02 - frame at 0m43s (2)](https://user-images.githubusercontent.com/125112932/221402330-25857273-194b-4fbb-bbfa-dc51651e2354.jpg)

Daytime: (around 21-27 FPS)
![rpcs3 exe 2023 02 26 - 12 42 38 02 - frame at 3m12s (2)](https://user-images.githubusercontent.com/125112932/221402357-dbed404f-998f-4d9d-b434-1660f833f286.jpg)

**Comment by dio-gh** [comment]
Can't repro on my 13600K + sounds like normal performance fluctuations.

I did notice a pretty big performance variation when using illusion's deltatime patch to make the game 60 fps capped, but it's always been a demanding title.

> The real PS3 doesn't have this issue but only on RPCS3.

RPCS3 doesn't emulate the realhw that precisely, the performance limitations of a real PS3 are not reproduced. If you encounter a drop, that's an honest to god drop, not an emulation mishap.

**Comment by MSuih** [comment]
Performance problems should be reported as compatibility reports on forums unless there's a regression from an update. We know that not all games run perfectly yet, no need to create an issue for each one of them.

**Comment by Ordinary205** [comment]
> Performance problems should be reported as compatibility reports on forums unless there's a regression from an update. We know that not all games run perfectly yet, no need to create an issue for each one of them.

I see

**Comment by Ordinary205** [comment]
> I did notice a pretty big performance variation when using illusion's deltatime patch to make the game 60 fps capped, but it's always been a demanding title.

Before it didn't used to have a patch named deltatime on "BLUS30442", but right now it does.
