### ISSUE TITLE
Insanely Long PPU Compile on High End CPUs with P-E Cores

### ISSUE THREAD

**Issue by Wontell** [RPCS3/rpcs3#13466]
### Quick summary

12900K >13900KF
MGS4 Compile over 9 hours
XMB compile over 2 hours

### Details

When i upgraded my CPU to 12900K i started to get super slow compiles, it continued to 13900KF that i own now.
It happens across all versions of the emulator [I use auto update like everybody else]

I have my emu folder on 18TB Seagate, so i assumed maybe its the slow HDD
So made fresh install on triple 4tb SATA SSD raid, same thing.
Then made fresh install on WD 850X 4TB [Gen 4 NVME] same thing
Compile from start to finish on WD 850x + 13900KF + 64GB RAM [custom loop, CPU never throttles, HWinfo shows 5.5Ghz, all cores loaded, including E-cores] took near 9 hours

I remember on my old, very old 9900K system taking under hour to compile MGS4

### Attach a log file

no needLog file from fresh install, PPU compile of VSH PS3 Menu, over 1 hour long
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10865974/RPCS3.log.gz)

### System configuration

13900KF
64GB  RAM
RTX4090

**Comment by Wontell** [comment]
I posted on discotd and was told that such long time is not normal.
also some other guy said it took him 40m, he never said whats his CPU

**Comment by Megamouse** [comment]
Missing logfile

**Comment by solarmystic** [comment]
Just did a fresh full PPU compilation of MGS4 myself on the latest rpcs3 master as of writing (0.0.26-14775) and it took only 44 minutes, 8.69 seconds on a stock 12700KF with e-cores enabled. All default settings, with means Max LLVM Compile Threads set to Auto (20).

There is something not quite right on your end if this is happening out of the box for you.

**Comment by Wontell** [comment]
> Just did a fresh full PPU compilation of MGS4 myself on the latest rpcs3 master as of writing (0.0.26-14775) and it took only 44 minutes, 8.69 seconds on a stock 12700KF with all 4 e-cores enabled. All default settings, which means Max LLVM Compile Threads set to Auto (20).
> 
> There is something not quite right on your end if this is happening out of the box for you.


I did a new test of the digital version of the game, this time I set the PPU compile threads to just 16 and it took like 4+ hours

**Comment by Wontell** [comment]
> Missing logfile

I dont have the original log file i loaded the emulator bunch of times since then, ill try to do a fresh install and get the log from there

**Comment by ISuckGood** [comment]
core i910850k . xmb compile took me 10 minutes lol

**Comment by Wontell** [comment]
> Missing logfile
Log file added, did fresh install latest version, only did PS3 Menu PPU compile, took over 1 hour

**Comment by Wontell** [comment]
> core i910850k . xmb compile took me 10 minutes lol

Thats good to know, i just did a fresh install, took over 1 hour, maybe near two

**Comment by Wontell** [comment]
> Just did a fresh full PPU compilation of MGS4 myself on the latest rpcs3 master as of writing (0.0.26-14775) and it took only 44 minutes, 8.69 seconds on a stock 12700KF with all 4 e-cores enabled. All default settings, which means Max LLVM Compile Threads set to Auto (20).
> 
> There is something not quite right on your end if this is happening out of the box for you.

Games run fine, i dont have any CPU nor GPU issues, playing atomic heart 4K/120hz
Just in case i excluded from Windows 11 antivirus the emulator folder, didn't help.

Im browsing the web while it compiles but it shouldn't have any effect, the GPU is not used for compilation and i have more then enough CPU

**Comment by RipleyTom** [comment]
Seeing how you're the only one with the issue in our user base, that we have staff with 13900KF on both Linux and Windows and they don't have the issue, I'm pretty confident in saying this is not a RPCS3 issue.
