### ISSUE TITLE
[Regression] LBP1 Image Import Tool now softlocks the entire game

### ISSUE THREAD

**Issue by SammyGoesHowdy** [RPCS3/rpcs3#13463]
### Quick summary

LBP1 Image Import Tool now softlocks the entire game, making the player have to reboot.

### Details

This used to work fine but when I updated to the build listed below (Newer builds also have this same problem), I can't seem to be able to import any image without having to reboot. (Log says I played on the EBOOT.elf I patched for Lighthouse (an LBP Private Server), but I tested and this happens on the original EBOOT.bin too.) 
 ![image](https://user-images.githubusercontent.com/105883916/221603898-587edce7-4829-4b49-a9f7-635a6a26eb15.png)

### Build with regression

v0.0.26-14743-6b30cdac

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10841238/RPCS3.log.gz)

### System configuration

CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz | 8 Threads | 15.95 GiB RAM | TSC: 3.500GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
GPU: AMD Radeon RX Vega 64

### Other details

The image that is selected to be imported is still imported into the game.

**Comment by Megamouse** [comment]
Try to find the exact build where it first stops working

**Comment by ActualMandM** [comment]
Not sure why this is closed, since it's still an issue.

@Megamouse The last known working build is 14743. The next one afterwards, 14757 (#13398), has this issue.

14743:

https://github.com/RPCS3/rpcs3/assets/15317421/34eadc15-8007-44e5-a5e2-dc6e5499b014

14757:

https://github.com/RPCS3/rpcs3/assets/15317421/c4219b2d-5396-4df9-9b76-654df12667e2

**Comment by Megamouse** [comment]
Fixed it.
Btw, fun fact, you can get out of the softlock by opening and closing the home menu xD
