### ISSUE TITLE
RPCS3 crashing when booting up game

### ISSUE THREAD

**Issue by JulieMeow3** [RPCS3/rpcs3#13469]
### Quick summary

When I boot up the game (Yakuza Kenzan) it freezes and refuses to work, completely freezing. I know specs aren't an issue on this so not sure why it refuses to work

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10852512/RPCS3.log)

**Comment by FlexBy420** [comment]
Cannot reproduce. Works fine on both 4.88 and 4.90 for me
![image](https://user-images.githubusercontent.com/68403300/221934813-eba602b8-4275-4639-939b-2c0f3f6d8ed8.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10853271/RPCS3.log.gz)

**Comment by MSuih** [comment]
As this doesn't appear to be a regression, ask for help on our Discord instead
