### ISSUE TITLE
[BLUS31324] Transformers: Rise of the Dark Spark - Infinite loading screen

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#13464]
### Quick summary

Even if I wait like 15 minutes, the game still doesn't get past the loading screen.

### Details

It doesn't have this issue on a real PS3, but only on RPCS3.

Heres the comparison between PS3 and RPCS3

PS3: (gets past the loading screen)
![real PS3](https://user-images.githubusercontent.com/125112932/221610002-1d7da8e6-39d5-4688-842c-f2ef67f7a1c0.PNG)

RPCS3: (doesn't get past the loading screen)
![Infinite loading screen](https://user-images.githubusercontent.com/125112932/221610147-8031f513-2276-4e9d-b849-9366c925ad56.PNG)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10841294/RPCS3.log.gz)

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 528.49.0.0 | Windows 10 Pro 22H2

**Comment by Asinin3** [comment]
The log isn't helpful here and we already know it doesn't go ingame look at the compatibility database.. its in intro status, going to close cause this isn't really helpful to devs.

**Comment by Ramiro142** [comment]
You can get past the infinite loading by LLE'ing libaudio.sprx, but it will just freeze instead when trying to load the file for campaign.

**Comment by Ordinary205** [comment]
When I enabled libaudio.sprx. it fixes the loading screen, but it does freezes the game when loading a file like you said, however when I tried to start the game again, it gives me an error said: "**F {PPU[0x1000000] Thread (main_thread) [0x007cc4a4]} VM: Access violation reading location 0x10 (unmapped memory)**"
