### ISSUE TITLE
Skate3 wont start

### ISSUE THREAD

**Issue by HannoMann12** [RPCS3/rpcs3#13476]
### Quick summary

As i wanted to start Skate 3, a window popped up and said that my Game folder was Invalid or Corrupted.
I did make a new Folder and Copied the Game in there but it still didnt work?

Can some one Explain this?

### Details

![Screenshot (15)](https://user-images.githubusercontent.com/126780538/222424429-8b811daa-5da1-4f82-baba-682b0e5275d0.png)

### Build with regression

I dont know what i am supposed to write here, my englisch is not that advanced

### Attach two log files

I dont know what im sopposed to do here either

**Comment by YuriNator557** [comment]
This is a support request, which is not what the GitHub page is for. Go to the official support channels either in the forums or the Discord server
