### ISSUE TITLE
Guitar Hero: Warriors of Rock (BLUS30487) Hard Crash After Intros

### ISSUE THREAD

**Issue by AddyMills** [RPCS3/rpcs3#13471]
### Quick summary

I'm on the latest update and when booting this game, it loads the splash screen and intro movie just fine, but when I get to the pre-main menu screen, the emulator hard crashes when I press X. No errors pop up on the emulator log before the exit.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10858032/RPCS3.log)

### System configuration

Device name	DESKTOP-58I463M
Processor	AMD Ryzen 7 3700X 8-Core Processor                3.59 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
GPU NVidia 2080 SUPER
Driver 531.18

Edition	Windows 10 Home
Version	21H2
Installed on	‎2020-‎11-‎28
OS build	19044.2604
Experience	Windows Feature Experience Pack 120.2212.4190.0

### Other details

I've tried enabling libvdec as suggested in another crash thread about a different game, but that didn't work.

**Comment by AddyMills** [comment]
So I downgraded my rpcs3 to one from about 2 months ago, and it works on there. I'm not able to test every release since then right now, but the game works on 0.0.25-14501. No crash after hitting X on the screen before the main menu

**Comment by MSuih** [comment]
If you're not going to figure out the version then nobody is. You at least seem to be a fan of the game and interested in seeing this issue fixed.

Start by testing a version somewhere in the middle of range. If it is broken then assume everything after it is broken, if it works then assume everything before it works too. Then again find the middle point of your new range of versions to test and repeat the same process. That way you'll cut down the number of comparisons down significantly and even two months of builds shouldn't take too long to go through.

**Comment by AddyMills** [comment]
I had it wrong. The crash is connected to the network settings. Even the build from 2 months ago crashes when the emulator is set to connected and using the "Simulated" PSN Status. Game can get to the main menu if either disconnected or set to RPCN

**Comment by MSuih** [comment]
Simulated should only be used with games that check for PSN connecttion but do not do anything with it.  As soon as the game tries to actually get data from psn it'll crash fast because simulated doesn't connect to anything.

Closing this as there's no bug, just incorrect settings.
