### ISSUE TITLE
Bomberman ULTRA - flashing and scaling issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#1348]
Warning this game produces flashing images and can cause a headache etc.!

maybe easy fix for you @vlj 

![bomb 1](https://cloud.githubusercontent.com/assets/11453507/11877503/f5db2a10-a4ef-11e5-916b-7c05ecc3d584.PNG)
![bomb 2](https://cloud.githubusercontent.com/assets/11453507/11877506/fcf7fa8a-a4ef-11e5-82a2-ca1e2fe1525d.PNG)
![bomb 3](https://cloud.githubusercontent.com/assets/11453507/11877512/0fd1a0c0-a4f0-11e5-9ed0-918d2f64a8fe.PNG)
![bomb 4](https://cloud.githubusercontent.com/assets/11453507/11877518/197c4788-a4f0-11e5-881f-f77c97e38267.PNG)
![bomb 5](https://cloud.githubusercontent.com/assets/11453507/11877532/2bc9ccee-a4f0-11e5-8cb7-99ab9b6517f1.PNG)
![bomb 6](https://cloud.githubusercontent.com/assets/11453507/11877544/392a47a6-a4f0-11e5-83d0-7fcec0790eed.PNG)
![bomb 7](https://cloud.githubusercontent.com/assets/11453507/11877560/5ca5702a-a4f0-11e5-9f3f-b3e589f79dc3.PNG)

**Comment by Zangetsu38** [comment]
ridge racer a same problem

**Comment by vlj** [comment]
Should be fixed in latest d3d12 branch

**Comment by JohnGodgames** [comment]
yeah fixed

**Comment by danilaml** [comment]
@JohnGodgames can you close it then?

**Comment by JohnGodgames** [comment]
@danilaml @vlj it's not merged in master I think?

**Comment by danilaml** [comment]
@JohnGodgames I see.

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/RPCS3/rpcs3/commit/324b2da3ec337383fc9bfc18ebdff92a9a4f9324
