### ISSUE TITLE
Kung Fu Panda: Showdown of Legendary Legends broken

### ISSUE THREAD

**Issue by fenix008** [RPCS3/rpcs3#1349]
G: E {rsx::thread} Exception: linkage failed: 'Fragment info
-------------
0(28) : error C7554: OpenGL requires sampler variables to be explicitly declared as uniform
0(110) : error C1115: unable to find compatible overloaded function "textureLod(samplerCube, vec2, float)"

Here's the log (OpenGL): http://rghost.ru/8NwWTCsDk
Original thread: http://www.emunewz.net/forum/showthread.php?tid=173713

**Comment by danilaml** [comment]
Do you know which @vlj commit exactly caused this?

**Comment by fenix008** [comment]
https://github.com/RPCS3/rpcs3/commit/14123d67e1b4ca9005d9137a70bc6596143eb183 - this.
i think it's something about "cube" commit....
maybe this - https://github.com/RPCS3/rpcs3/commit/6221fecf3bd584d1b036b2e9bd76ffd903192b5d
or this - https://github.com/RPCS3/rpcs3/commit/69b3828086d6338052a5a1eccec94ee489368ac4

**Comment by tambry** [comment]
@fenix008 Does it work with DX12?

**Comment by vlj** [comment]
I know what causes the crashes, I added support for texture cube only for texture and textureproj function but not textureLod.

**Comment by fenix008** [comment]
@tambry no, it doesn't work on DX12, it stuck on Menu.
Log DX12: http://rghost.ru/7zymjyzJk

**Comment by tambry** [comment]
@fenix008 I guess it might be due to support for texture cube not being supported for textureLod both on OGL and DX12.

**Comment by tambry** [comment]
@fenix008 Is this still an issue?

**Comment by fenix008** [comment]
@tambry yes, I still can't get it on OpenGL and DX12.

**Comment by raven02** [comment]
It is working further now though still hit the following error .Will open another one with more testing with other backends

·F {PPU[0x9b] Thread (veThread8) [0x006fe9ac]} class std::runtime_error thrown: Precondition failed: header.magic == "\0PSF"_u32
(in file C:\rpcs3\rpcs3\Loader\PSF.cpp:106)
