### ISSUE TITLE
[Regression] Metal Gear Solid 2 - Broken conference video

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#13495]
### Quick summary

When you get to the part of the conference where they talk about the new Metal Gear model, the video where it is projected looks bad.

### Details

Working
0.0.26-14722
![image](https://user-images.githubusercontent.com/78843189/222934543-22cafb9d-6307-498f-80e4-3b8c864766ad.png)

**Broken**
0.0.26-14723 [PR #13413](https://github.com/RPCS3/rpcs3/pull/13413)
![image](https://user-images.githubusercontent.com/78843189/222934190-3c055fb8-0d0c-4195-810b-565a80b42e36.png)

### Build with regression

0.0.26-14723 

### Attach two log files

Working
[Working.log.gz](https://github.com/RPCS3/rpcs3/files/10890462/Working.log.gz)

Broken
[Broken.log.gz](https://github.com/RPCS3/rpcs3/files/10890456/Broken.log.gz)

### System configuration

OS -  Windows 10 22H2
CPU - i7 8700
GPU - GTX NIVIDIA 1070 Ti
Driver version - 531.18

**Comment by Megamouse** [comment]
How long does it take to get there 😅

**Comment by illusion0001** [comment]
Post save

**Comment by Jonathan44062** [comment]
https://www.mediafire.com/file/8fg0ytnuzzmqwk2/BLUS30847_MGS2000G003.rar/file There

**Comment by digant73** [comment]
@Jonathan44062 when possible, please test if #17942 is not resuming this regression
