### ISSUE TITLE
GUI: DualShock 4: Various LED control issues

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#13509]
### Quick summary

- [ ] the `Use LED as a battery indicator` feature only works while the configuration window is open
- [ ] the `Blink LED when battery is low` doesn't work for me (even though the reported battery charge is 0%)

### Details

The aforementioned are as stated above and are the actual core issues. The rest below is not super important, whether they should be actioned on I give up for discussion.

Additional misgivings that are not per se broken:
- ~~it is unclear whether the `Use LED as a battery indicator` feature should affect the LED color or not (it does right now and it seems like it should?)~~ confirmed should, heads up about it would be still welcome though, see proposal down below
- ~~it is unclear what is meant by the battery being low (<20%?, <10%?)~~ "confirmed" device defined
- ~~it is unclear whether the entirety of the RGB color palette is available for picking as shown by the emulator, or only a few specific colors; it seems like only a limited number of colors are available, but even then, their brightness should be possible to control, which it is not~~ confirmed to be a device issue, though a heads up about it would be welcome
- there's no reset button (maybe I need to reset the entire device config? unclear)

Turbo nitpicks:
- the charging details are unclear:
  - at 0% it is impossible to tell whether the device is charging as expected or not
  - ~~it is unclear why there are only ~~10~~ 11 "levels" of charge~~ confirmed device detail
  - ~~it is unclear how long until it's charged up / loses charge completely~~ due to the previous point, confirmed not practical

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10902122/RPCS3.log)

**Comment by dio-gh** [comment]
Let's get the productive chatter out of the way first:

> We don't handle these settings outside of games. Therefore it is only active in the LED config window.

Why does the custom LED color feature behave differently? How am I supposed to know?

> The brightness works perfectly fine for me.

Tested it further, confirmed. Seems like it's a color reproduction issue as you're alluding to, and I just happened to pick the wrong color where changing the brightness wouldn't do anything observable. Taking this one off of the list too I 'spose.

> It also blinks. I guess you mean in the config window?

It didn't work neither in the config window, nor outside of it. By the time I got to play I had enough charge to be in the "orange" range, and it's unclear whether it should still blink then, If it should, it doesn't.

- - -
Now for the unproductive:

> Wrong.

Yes, bound to be when there are zero tooltips or other indicators / messages.

> One would assume that that's obvious. But i can add it to the text.

It is "obvious", I alluded to this where I said "it does right now and it seems like it should". But another (imo) perfectly reasonable to expect behavior is that it might modulate the brightness based on the charge level. So when you're expecting that and your selected color just disappears, that's quite the surprise.

Please consider setting the LED color image to grey and the `Select color` button to disabled instead when the `Use LED as a battery indicator` is ticked.

> The threshold is different for each controller. It simply tells you that it's gonna be empty soon.

I see, taking this off of the list then.

> Whether or not it can display them correctly is not our problem in my opinion.

That's unfortunate. Would be cool if this was noted in a label somewhere, but fair enough.

> Why is it important if there's 11 or 10 or 22 or 1000 levels?

Why is anything important ever? If you don't consider it important, that's the end of that - if it bothers me so much, I can go and implement it myself.

100% feel free to just ignore it, or say "it's not a device limitation but an implementation limitation, one that I'm personally fine with. Not fixing personally, and there are no other GUI guys, so ignoring/closing/adding it to the to-be-revisited pile."

> If you want to know the details of every aspect of the ds4

I do not.

> We're not gonna explain every detail of every controller to the user

Is this every detail?

> How are we supposed to know how long your battery charge lasts? Ask a Chrystal ball?

No, you estimate based on how fast it's dropping charge. Do phone manufacturers have crystal balls in your opinion?

> Btw, i didn't implement it. So I'm indifferent about the whole functionality of the battery LED indicators.

And that's fine, this is no blame game. I don't know if a triage policy has been implemented here since I left, if not, you may as well just leave the ticket here and ignore it completely. Such is FOSS, there are zero obligations in any direction.

**Comment by Megamouse** [comment]
You seem to have the impression that we choose the amount of battery level steps. We do not. The ds4 only has 11 levels or whatever, and it's not documented properly anywhere what these levels mean. So we do what any sane person does and simply assume it's 10% steps.
Therefore it also makes absolutely no sense to "estimate" the battery levels, as there are only 10 steps. This means we can only know how fast it drops after you played for an hour or whatever. I don't think this is worth implementing. Especially since some other controller types only have 4 states for example (empty, low, normal, full).
Also, we are not the "Phone manufacturer", so we don't have information about specific charge values and power draw... I don't know how you arrived at that comparison.
Also, the controllers mostly only report a "charging" state or even "plugged in" anyway and no specific power level during that state, so there's probably not much we can estimate anyway.

The LED obviously only blinks when it's almost empty, so if it was orange, that would mean it wasn't. (kinda obvious, idk).

**Comment by dio-gh** [comment]
> You seem to have the impression that we choose the amount of battery level steps. We do not.

This is one of the things I found unclear and was curious of, thank you. Taking it off of the list.

> Therefore it also makes absolutely no sense to "estimate" the battery levels

I was not talking about estimating battery levels, I was talking about estimating *time-to-full* and *time-to-empty*.

> This means we can only know how fast it drops after you played for an hour or whatever. I don't think this is worth implementing.

That's pretty fair. While *time-to-full* would not be impacted by this, I can see this being just an annoyance, so I'm taking both off the list.

> I don't know how you arrived at that comparison.

Because a simple back-of-the-envelope estimation doesn't need data that low-level. That being said, since the granularity of the data is indeed 11 levels, the estimation would probably not be super reliable, especially considering that Li-ion discharge rates are not linear and change with wear.

> Also, the controllers mostly only report a "charging" state or even "plugged in" anyway and no specific power level during that state, so there's probably not much we can estimate anyway.

The DS4 specifically seems to report charge level while plugged in, that's why I oriented the ticket around it. I'm not familiar with how general the implementation is under the hood.

> The LED obviously only blinks when it's almost empty, so if it was orange, that would mean it wasn't.

Does it always blink when red, or even within red, it only blinks when it's really at the end? I vaguely recall a couple blips when I was initially connecting the controller, but it was solid red afterwards for quite a bit for sure.

**Comment by Megamouse** [comment]
It blinks at 10%, so when it really is almost empty.
The colors are apparently from red to green:
{0xff0000, 0xff3300, 0xff6600, 0xff9900, 0xffcc00, 0xffff00, 0xccff00, 0x99ff00, 0x66ff00, 0x33ff00, 0x00ff00, 0x00ff00}
Since 0xff6600 is orange and 0xff3300 is almost full red, it should basically always blink when it's red.
If it's at 0xff0000 the controller should probably be empty any second anyway.

**Comment by dio-gh** [comment]
Checked how these colors look on my DS4, I'm pretty sure it was actual red (#FF0000) and not blinking. It was completely drained when I hooked it up, and didn't reach 10% until a bit longer. I was already mucking about with the settings for a while by then.

Can't easily recreate it experimentally though, would take quite a bit of use to drain it that far. If the code looks fine, we could just assume I was being inattentive and it's actually alright, then just wait for someone else to hit it, if ever.

Or if you throw together a hackbuild that blinks it no matter what, I can give that a whirl and see what happens.

**Comment by Megamouse** [comment]
That's how I tested it

**Comment by dio-gh** [comment]
Figured it out... it only blinks in wireless mode and I had it wired.

![image](https://user-images.githubusercontent.com/10439488/223532616-57989624-5305-4728-9423-1756b966e479.png)

I guess that's... sensible, kind of? Whatever.

I also figured out my brightness memes, turns out it was less a color reproduction issue and more that I sometimes wasn't clicking `Apply` on the LED config panel, only on the color picker, and this had me confused as to why my changes weren't taking effect. Might worth considering if this is a good flow, but it was also a legitimate pebkac on my side so I digress.

This leaves us with the first item, which from what I gathered is the intended behavior then and you're not really interested in changing, along with the tooltip requests for the rest. Closing the ticket as a result, but if you decide to implement some tooltips anyway, feel free to reopen.
