### ISSUE TITLE
[Regression] flOwer (NPEA00094) is broken since build 14723

### ISSUE THREAD

**Issue by 13xforever** [RPCS3/rpcs3#13501]
### Quick summary

Since #13413 build when you try to load a level in flOwer, the game immediately crashes.
Still reproducible as of 14800.

### Build with regression

v0.0.26-14723-bb2c9196

### Attach two log files

[RPCS3.14722.log.gz](https://github.com/RPCS3/rpcs3/files/10892882/RPCS3.14722.log.gz)
[RPCS3.14723.log.gz](https://github.com/RPCS3/rpcs3/files/10892883/RPCS3.14723.log.gz)

### System configuration

AMD 5950x, RTX 3080, Win11 22H2

### Other details

This is extremely annoying to test/bisect, because you have to sit through all the intro movies, and then use sixaxis to select a level, and then hold a button… Mega plz get the game yourself.

**Comment by digant73** [comment]
@13xforever when possible, please test if #17942 is not resuming this regression

**Comment by 13xforever** [comment]
flOwer does go ingame on the current build 

<img width="2091" height="1222" alt="Image" src="https://github.com/user-attachments/assets/52912ea9-35dc-4efc-a0da-20b1ea885b9d" />


It _does_ crash on PR build
<img width="2694" height="1559" alt="Image" src="https://github.com/user-attachments/assets/e7ac21ec-aff7-42cb-98a2-9f7df11d2662" />
[RPCS3.log.gz](https://github.com/user-attachments/files/24560852/RPCS3.log.gz)

**Comment by digant73** [comment]
thanks. so #17942 would resume the regression
