### ISSUE TITLE
"Assertion Failed! Vulkan API call failed with unrecoverable error:  Device lost" (Issue #13344 is the most similar to my issue)

### ISSUE THREAD

**Issue by elrod829** [RPCS3/rpcs3#13502]
![image](https://user-images.githubusercontent.com/37812157/222987911-bc615af1-160a-4640-82f6-b40bd896d51b.png)

Version: v0.0.27-14800-0d34b979 Alpha | master
CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz | 8 Threads | 15.70 GiB RAM | TSC: 2.803GHz | AVX-512+ | FMA3
GPU: Intel(R) Iris(R) Xe Graphics
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0
Qt version: Compiled against Qt 5.15.2 | Run-time uses Qt 5.15.2
Current Time: 2023-03- 5T16:38:23

Log File: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10893049/RPCS3.log)

_Originally posted by @elrod829 in https://github.com/RPCS3/rpcs3/issues/13344#issuecomment-1455215769_

**Comment by elrod829** [comment]
Attempting to use OpenGL to render gives a similar error, so I am S.O.L. at the moment.

**Comment by kd-11** [comment]
I suggest to DDU and reinstall the driver.

**Comment by Darkhost1999** [comment]
If anything can we fix the word wrap of that error dialogue?

**Comment by kd-11** [comment]
Closing for now. Ping if still having driver issues.
