### ISSUE TITLE
Frostbite Engines - Some bugs that needed to be fixed

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#13507]
### Quick summary

There are plenty of Frostbite engines that was used on RPCS3, one of them has tons of issues on RPCS3, and some of them doesn't have one. For those that never heard of Frostbite engine, click this website: https://en.wikipedia.org/wiki/Frostbite_(game_engine).

Here are the lists that needed to be fixed:

**Frostbite 1**:

No issues found.

**Frostbite 2**:  
- Rendering issues.
- Unstable Framerate timing (requiring clock scale under 100% to go ingame).
- Half-Screen/Ghosting bug.

**Frostbite 3**:

- Rendering issues.
- Unstable Framerate timing (requiring clock scale under 100% to go ingame). For example, Battlefield hardline.
- Half-Screen bug.

Note: If one of the bugs gets fixed. I'll cross out the texts, however if all the bugs that I listed totally gets fixed, I'll close this issue.

### Details

On a real PS3 it seemed totally fine, but unlike RPCS3 it has tons/minor of issues

### Attach a log file

I'm not gonna attach the log, because I just want to report a bug/missing functions on frostbite engine.

However, if you really want to know about the bugs on some games, click on this issues:

#8891
#13414
#7756
#8387
#13356
#13486

If you think one of the issues that are missing on this list, comment and then I'll add one.

### Other details

The weird thing is that some games like Need for Speed Rivals doesn't require clock scale under 100% to go ingame? But unlike Battlefield Hardline, it does require to go 30% clock scale.

Incase if anyone wants to know the total games that was used on Frostbite engines, heres the list:

There are 4 total PS3 games that was used on Frostbite 1 is:
Battlefield: Bad Company
Battlefield 1943
Battlefield: Bad Company 2
Medal of Honor

Another 4 total PS3 games that was used on Frostbite 2 is:
Battlefield 3
Need for Speed: The Run
Medal of Honor: Warfighter
Army of Two: The Devil's Cartel

And finally the 5 total PS3 games that was used on Frostbite 3 is:
Battlefield 4
Battlefield Hardline
Need for Speed: Rivals
Plants vs Zombies: Garden Warfare
Dragon Age: Inquisition

**Comment by Megamouse** [comment]
Why do you open an issue that lists other issues...
This is useless for any developer.
There needs to be a clear reproducable bug or anomaly that can be targeted.
