### ISSUE TITLE
DX12: Unimplemented color surface format used 5

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1351]
Discovered in game BIT.TRIP Presents... Runner2: Future Legend of Rhythm Alien Trial [NPUB30733]

log: http://pastebin.com/Ec0V5mg4

On old OGL builds this one was ingame
http://www.emunewz.net/forum/showthread.php?tid=160019

**Comment by tambry** [comment]
From what I can tell, #1352 doesn't look exactly right.
I have fixed it myself, hopefully properly here: https://github.com/tambry/rpcs3/commit/f6f935fc81441d3de7df0294fa88866a48a3668e.

**Comment by Zangetsu38** [comment]
hmm oups sorry, i have forget test for find other instruction missing ^^
I have allready fix this game with other commit

**Comment by Zangetsu38** [comment]
@tambry  now is good, 2 missing instruction 5 and 16, for second log indicate 10 but it is a 16, don't no why indicate inccorect value.
no first time artf

**Comment by O1L** [comment]
LOL, you use "%x" - it's numbers in a hex format. Use "%d" for decimal or "0x%x" for hex.

**Comment by tambry** [comment]
@B1ackDaemon Is this fixed?

**Comment by raven02** [comment]
Retested again and should be no more this error .DX12 works perfectly
