### ISSUE TITLE
Mortal Kombat vs. DC Universe [BLUS30246]

### ISSUE THREAD

**Issue by BRNpintor** [RPCS3/rpcs3#13512]
### Quick summary

Black screen only, was working in old builds.

shows error:
Access violation reading location 0xdaa5b7ea (unmapped memory)

### Details

Black screen only, was working in old builds.

shows error:
Access violation reading location 0xdaa5b7ea (unmapped memory)

### Build with regression

v0.0.27-14804-65eb6258 Alpha | master

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10911518/RPCS3.log.gz)

**Comment by kd-11** [comment]
You'll need to help us find when it broke. It must be quite recent too.
