### ISSUE TITLE
Discord Rich Presence not working on Linux

### ISSUE THREAD

**Issue by SideWayy** [RPCS3/rpcs3#13519]
### Quick summary

discord not displaying "playing on RPCS3" in your status when playing a game on RPCS3

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10931007/RPCS3.log.gz)

### System configuration

- OS: Arch Linux x86_64
- Kernel: 6.2.2-arch1-1
- CPU: Intel i5-9400F (6) @ 4.100GHz
- GPU: NVIDIA GeForce GTX 1070 Ti

### Other details

- discord installed from: pacman (no sandbox)
- RPCS3 installed from: AppImage

**Comment by AniLeo** [comment]
This was reported again on Discord and I still reproduce on my side
