### ISSUE TITLE
[Regression] RPCS3 Stop working correctly 

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#13526]
### Quick summary

There are reports on the discord server, that when you open the games, you get these exaggerated error windows

### Details

0.0.27-14810 https://github.com/RPCS3/rpcs3/pull/13500
![image](https://user-images.githubusercontent.com/78843189/224457704-d54e3ce2-16e0-4142-821a-68fc3886a64c.png)

### Build with regression

0.0.27-14810

### Attach two log files

Broken
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10947268/RPCS3.log)

Working
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10947283/RPCS3.log)

### System configuration

OS - Windows 10 22H2
CPU - i7 8700
GPU - GTX NIVIDIA 1070 Ti
Driver version - 531.18

**Comment by RipleyTom** [comment]
The games being Sonic Unleashed only apparently?
I tried a lot of games with no issue.

**Comment by solarmystic** [comment]
Can reproduce this on my 12700KF/2080ti machine with Sonic Unleashed. 

![image](https://user-images.githubusercontent.com/4345150/224490932-86556239-1524-42ff-b196-e622acbb8ed0.png)
