### ISSUE TITLE
[Feature request] Game list: Show game order and performance improvement

### ISSUE THREAD

**Issue by shangjun2x** [RPCS3/rpcs3#13538]
### Quick summary

I have handreds of games. 
Issue one:Need show order number  at the first column.  

Issue two: it takes a long time to scan games folder when open RPCS3. Can we save the information on the grid to disk so that it will not scan every time.

Issue three: Allow user rank the game.

Issue four: Add a tab to show user's favorite games.

**Comment by Darkhost1999** [comment]
Issue 2 for me is slowed down by this
https://github.com/RPCS3/rpcs3/issues/13357
Every single time I boot rpcs3 it logs all of my games in the games list into my log at the top of my log. And takes all that extra time to load the gameslist as it looks like it readds everything every single time

**Comment by Asinin3** [comment]
Mega greatly improved RPCS3 opening times a few months ago. With my hundreds of games i went from 1m50s to 17 seconds: https://github.com/RPCS3/rpcs3/pull/13712#issuecomment-1518578785 I think this can be closed.

I don't see a need for counting the number of titles or having a column for that, will just waste more space.
