### ISSUE TITLE
[BCAS20087] TORO ! Let's Party -- Bloom issues

### ISSUE THREAD

**Issue by user18081972** [RPCS3/rpcs3#13532]
### Quick summary

Lighting/bloom is not displaying correctly compared to real hardware. Things can become so bright you cant even see stuff anymore.

### Details

RPCS3 v0.0.27-14809-ec8cb166 Alpha | master
- Both Vulkan and OpenGL affected
- Default settings.

Emulated:
![image](https://user-images.githubusercontent.com/124319511/224488617-d9a699e4-cf23-4222-8741-ae1b4cd3a1f0.png)
![image](https://user-images.githubusercontent.com/124319511/224488121-e8ebee0a-2593-4330-ad63-45363c7873e2.png)

Real hardware:
![image](https://user-images.githubusercontent.com/124319511/224488669-b62ccd73-3719-47d1-bdfd-38d3780d545f.png)
![image](https://user-images.githubusercontent.com/124319511/224488144-4819cf26-cd8c-48c7-b567-3ea6b9a17de8.png)

The same behavior can be seen on this youtube video of someone i dont know using RPCS3 to play this game:
https://youtu.be/2KSakXVo620?t=16

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10948699/RPCS3.log.gz)

### Attach capture files for visual issues

RSX
[BCAS20087_20230311151815_capture.zip](https://github.com/RPCS3/rpcs3/files/10948720/BCAS20087_20230311151815_capture.zip)

RenderDoc
[rpcs3_2023.03.11_14.27.45_frame937.zip](https://github.com/RPCS3/rpcs3/files/10948719/rpcs3_2023.03.11_14.27.45_frame937.zip)

### System configuration

11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz | 16 Threads | 31.74 GiB RAM | TSC: 3.504GHz | AVX-512+ | FMA3
Nvidia RTX 3080 driver 527.56.0.0
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0

**Comment by user18081972** [comment]
**Settings that resolve the issue:**
    Write Color Buffers = True
    Strict Rendering mode = True

    When these settings are applied, it looks like the example of real hardware.

**Comment by RainbowCookie32** [comment]
If those settings fix it, then I don't think there's an issue here. They are disabled by default because a lot of games don't need it and they can reduce performance a lot, but they are more accurate.

**Comment by MSuih** [comment]
Yes, we keep these settings unselected by default to improve performance, but they're sometimes required to get the game to render accurately. Closing as this is resolved by settings changes.

**Comment by user18081972** [comment]
Does RPCS3 have a database with game-specific fixes that apply automatically based on the game ID? Kinda like some other emulators do?

**Comment by Asinin3** [comment]
> Does RPCS3 have a database with game-specific fixes that apply automatically based on the game ID? Kinda like some other emulators do?

Yes. https://wiki.rpcs3.net/index.php?title=Toro!_Let%27s_Party!

**Comment by Darkhost1999** [comment]
No because the settings don't automatically apply. It is a wanted feature but it is a big project.
I don't know if anyone is actively working on implementing it.
However as they showed you can manually configure recommended settings from that "database" aka the wiki.
