### ISSUE TITLE
Rock Band 3 [BLUS30463]: Networking thread maxes out a single core.

### ISSUE THREAD

**Issue by DarkRTA** [RPCS3/rpcs3#13539]
### Quick summary

Whenever networking is enabled in Rock Band 3 for online play, the CPU usage of what looks like the networking thread will pin a single core at 100%.

In order for online play to work, some additional configuration is needed as a private matchmaking server is used:

Set `Settings -> Network -> IP/Hosts Switches` to `rb3ps3live.hmxservices.com=45.33.48.123` and enable RPCN.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10950222/RPCS3.log)

### System configuration

OS: Arch Linux 
Kernel: 6.2.1
CPU: AMD Ryzen 5 3600 @ 3.6GHz 
GPU: AMD Radeon RX 5600 XT 
Memory: 16GB

**Comment by RipleyTom** [comment]
Sockets are checked with a delay of 1ms, if there is always something to read on a socket it will keep that thread busy.
As for the log you posted:
```
·! 0:00:49.905977 {Network Thread} SIG: Thread time: 0.100891s (0.000000Gc); Faults: 0 [rsx:0, spu:0]; [soft:4 hard:1]; Switches:[vol:44111 unvol:19]; Wait:[0.000s, spur:0]
```
So yeah...that is far from 100% usage of a core...

**Comment by DarkRTA** [comment]
Do I have to post my htop screenshot

Something with the networking is ineeded pinning one of my cores at 100% even if its not the networking thread itself.

**Comment by DarkRTA** [comment]
Regardless I am still seeing one of my cores get pinned when networking is enabled, so even if its not the networking thread it would be good to know if its just the emulator or the game's fault.

I don't think networking should incur a massive CPU usage penalty like it is on my machine.

**Comment by DarkRTA** [comment]
I decided to build from source and do some debugging on my own. Looks like its the thread running the RPCN client rather than the networking thread itself. There is indeed a bug here as the game hardly does anything with networking on the title screen.

**Comment by RipleyTom** [comment]
My bad, I thought you meant Network Thread but there was indeed a bug from recent change to NBIO for RPCN, fixed by https://github.com/RPCS3/rpcs3/pull/13543.

**Comment by DarkRTA** [comment]
> My bad, I thought you meant Network Thread

Nah I actually thought it was that at first until I dug into it. Thank you for looking into this though and I can confirm that the PR does indeed fix this.
