### ISSUE TITLE
Option to disable "Compiling PPU Modules" message

### ISSUE THREAD

**Issue by MicahLeed** [RPCS3/rpcs3#13548]
### Quick summary

I updated my RPCS3 about a week ago now and a new pop-up appeared whenever I was playing a game saying "Compiling PPU Modules"
It's similar to the "Compiling shaders..." pop-up and it's really taking the immersion out of playing the game
Does anyone know how to stop this? And if there isn't a way currently can there be an option added to disable it please?

### Details

![image](https://user-images.githubusercontent.com/127788379/224813589-03ea4190-4ac9-4d34-b125-05c740ffbd0c.png)
Here's an example of what I mean. When playing certain games it can pop up a lot.

**Comment by Isamiyuu** [comment]
> It pops a lot in every game I've played honestly, I don't know whose wise idea was this, is a useless feature, RPCS3 window already shows when it's compiling PPUs on logs.
> 
> We don't need the useless UI in game rendering window, the shaders one was already bad as is, thankfully there is an option to disable that one.

How to disable?
