### ISSUE TITLE
Enter a title here

### ISSUE THREAD

**Issue by Jop890** [RPCS3/rpcs3#13549]
### Quick summary

Rpcs3 freezing when I open up a game on latest version.

### Details

It happens when I boot up seemingly any game.

### Attach a log file

none obtainable.

**Comment by Darkhost1999** [comment]
Ask for help on 1 of our support platforms.

Discord:
https://discord.com/invite/Af7H9yp

Forums:
https://forums.rpcs3.net/

Reddit
https://www.reddit.com/r/rpcs3
On reddit make sure to ask in the sticky questions thread if you choose reddit.
