### ISSUE TITLE
Enter a title here

### ISSUE THREAD

**Issue by lehleh** [RPCS3/rpcs3#13541]
### Quick summary

AI either doesn't follow the checkpoints or just straight up stopping on the road.
Already using Enable Deltatime patch

![image](https://user-images.githubusercontent.com/24360964/224552595-e5c1d73f-110b-43a1-8efa-70215808de64.png)

![image](https://user-images.githubusercontent.com/24360964/224553012-dfc24a5d-99e7-4745-9007-54453bd01796.png)

Both image: Opponents are infront of me, but my position is still \#1 because they wouldn't follow the checkpoints

### Details

Settings:
![image](https://user-images.githubusercontent.com/24360964/224553323-2a326e94-5ea4-4c98-82a4-7b5bb0140062.png)
![image](https://user-images.githubusercontent.com/24360964/224553336-7c9e9fe1-e975-4b21-9f19-dea2194f9338.png)

VBlank Freq: 60hz

### Attach a log file

https://www.dropbox.com/s/488ybdurg75706t/RPCS3.log?dl=0

### System configuration

OS: Arch Linux 6.2.2-arch1-1
CPU: Ryzen 7 3800x
GPU: Radeon 6700 XT
GPU Driver: mesa 22.3.6-1

**Comment by lehleh** [comment]
Please let me know if there are more details I can attach

**Comment by qfoxb** [comment]
You should set a title to your issue

**Comment by Megamouse** [comment]
you're using game patches, you have like 10 specific options that deviate from any default settings. closing as not following guidelines
