### ISSUE TITLE
[BLUS31201] Need for Speed Rivals: Heavy FPS drop

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#13542]
### Quick summary

The performance drops heavily when using a nitrous, going through tunnels, or enabling police sirens.
Here are three examples that I took screenshots.

First example:
Without nitrous: (normal 30 FPS)
![rpcs3 exe 2023 03 12 - 12 54 39 02 - frame at 0m39s (2)](https://user-images.githubusercontent.com/125112932/224554124-c1dd3bf5-8147-43e2-9b82-a75b7f0f3b2a.jpg)

With nitrous: (14 FPS)
![rpcs3 exe 2023 03 12 - 12 54 39 02 - frame at 0m42s (2)](https://user-images.githubusercontent.com/125112932/224554412-5af328ad-d322-4b43-98ce-28dec5f84105.jpg)

Second example: 
Without police sirens: (normal 30 FPS)
![rpcs3 exe 2023 03 12 - 12 54 39 02 - frame at 1m16s (2)](https://user-images.githubusercontent.com/125112932/224554796-a9fecd9d-7543-4d58-8a47-d3e4a817f423.jpg)

With police sirens: (19 FPS)
![rpcs3 exe 2023 03 12 - 12 54 39 02 - frame at 1m13s (2)](https://user-images.githubusercontent.com/125112932/224554679-25e94c8a-fd3a-4b5b-b64b-00615d338475.jpg)

Third example:
Without going to tunnels: (almost 30 FPS)
![rpcs3 exe 2023 03 12 - 12 54 39 02 - frame at 1m25s (2)](https://user-images.githubusercontent.com/125112932/224555217-201627d9-2064-492c-8b2c-52cbfc56fc24.jpg)

Going to tunnels: (16 FPS)
![rpcs3 exe 2023 03 12 - 12 54 39 02 - frame at 1m29s (2)](https://user-images.githubusercontent.com/125112932/224555268-ff213728-d48c-424d-9756-dc3105483133.jpg)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10950379/RPCS3.log.gz)

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 531.18.0.0 | Windows 10 Pro 22H2

### Other details

I'm pretty sure it's because the half-screen bug causes the performance to drop heavily.

**Comment by Darkhost1999** [comment]
Performance drops in the same scenarios as a real PS3 maybe not the same frame rates but still it's nice to see that the game is working as intended with RPCS3's current compatibility.
Compatibility reports belong on the forums not the issue tracker.

**Comment by Ordinary205** [comment]
> Performance drops in the same scenarios as a real PS3 maybe not the same frame rates but still it's nice to see that the game is working as intended with RPCS3's current compatibility. Compatibility reports belong on the forums not the issue tracker.

I didn't know that the real PS3 has the same problem with RPCS3, at first I thought it was a bug on RPCS3 but I was wrong.

**Comment by Ordinary205** [comment]
> Compatibility reports belong on the forums not the issue tracker.

Well I thought it would be necessary to post it on github but nevermind.

**Comment by RainbowCookie32** [comment]
Unless it's a regression, "performance is bad" issues aren't really useful for devs and just clutter the tracker.

**Comment by Darkhost1999** [comment]
When using any other spu processor than LLVM the game will degrade and fall apart when using nitrous oxide, police sirens or going in a tunnel. The tunnel typically not even existing.
So I kinda blame this
https://github.com/RPCS3/rpcs3/pull/12962#issuecomment-1320936512
But that's not an RPCS3 issue per say it's just compatibility as the spu processor continues to be reverse engineered and improved on RPCS3.
This issue just serves as a reminder that RPCS3 is a work in progress with nothing to investigate.
