### ISSUE TITLE
Use wix to create user friendly Windows installer

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1354]
WiX is a Microsoft sponsored toolset that allows to create installers for Windows :
http://wixtoolset.org/
It supports virtually everything a msi installer can do, integrate seamlessly with the global windows uninstaller...
To use it we just need to add a WiX project inside Visual Studio solution and use an xml file to describe the installer. Then the installer is created by generating the new project which in turn can generate others project as dependencies.
With this tool we could make appveyor create proper Windows installer for every release.

This is a project that doesn't require knowledge in emulation or C++ yet I think it can help improve project perception.

**Comment by tambry** [comment]
"Installing" is literally downloading a build and then dropping the RPCS3 folder somewhere.
"Updating" is literally downloading a newer build and replacing the .exe.
But do we really need an installer? I see no reason for an installer.

**Comment by danilaml** [comment]
Could be longterm. Right now there isn't any need nor demand.

**Comment by paulsapps** [comment]
CMake/CPack has a WIX generator, so its actually really easy to make an msi/zip/deb/whatever installer

**Comment by vlj** [comment]
I looked at Build 2016 podcast about uwp app model and it looks like Microsoft is trying very hard to make uwp and appx the way to go for Windows application. They're working on a gui making sideloading (installing app not on Windows store)  easier and will provide a tool to embed win32 app in an appx package. 

The benefit of uwp/appx is that installation mechanism is strongly defined which should allow for clean un install. There is also fine grained device capability access (ie executable memory, Webcam recording...). 
TBH there's no benefit for rpcs3 performance or usability but on the long term I'm expecting users to prefer an uwp version over a wxwidget one.

**Comment by danilaml** [comment]
@vlj wxwidgets is ceoss-platform though. Currently even one GUI backend (wx) is barely maintained, it'd be unwise to have a GUI for every platform without dedicated maintainers.
AFAIK it doesn't stop us from using app model in the future though. But that future is rather distant.

**Comment by dio-gh** [comment]
I honestly don't think creating an installer would be a good idea. RPCS3 currently provides great portability between machines the way it currently, and I think that's much preferable and should be preserved. In fact, the way our current Linux binaries work (a single executable file) is where the Windows path should be heading towards too imo.

This is a very old feature request, so I'm not sure if the original poster is still around. But if you are @vlj, I'd ask you to reconsider, and if you agree, close this ticket. Same goes for the repo maintainers, of the OP fails to respond within a reasonable timeframe.
