### ISSUE TITLE
Drakengard 3 (NPUB31251) - Can't load savestate

### ISSUE THREAD

**Issue by KB1011** [RPCS3/rpcs3#13557]
### Quick summary

I have been trying to use the save/loadstate feature, but it doesn't seem to work in Drakengard 3.

### Details

Saving seems to work fine, but once I load, I get this error message, and RPCS3 crashes. This happens anywhere in the game, unrelated to a certain part/level.
![rpcs3_1hhisigZXD](https://user-images.githubusercontent.com/55064890/226077562-3c615423-9996-4afd-abe1-ae92a8456337.png)

### Attach a log file

[save.log](https://github.com/RPCS3/rpcs3/files/11007253/save.log)
[loadstate.log](https://github.com/RPCS3/rpcs3/files/11007259/loadstate.log)

### System configuration

OS: Windows 11
CPU: Ryzen 5 5600x
GPU: AMD Radeon 6600XT
RAM: 16GB

**Comment by Ohyah55** [comment]
Same issue here, however so far the BLUS31197 version seems to work. I don't think saving is working properly on NPUB31251 either. When I save on BLUS31197 I get these 2 lines:

"S SYS: Saved the contents of directory 'C:/Users/Nathan/Downloads/Compressed/Drakengard Emulate/rpcs3-v0.0.27-14812-cf5346c2_win64/dev_hdd1/caches/BLUS31197_BLUS31197/' (size=0x5be800)"
"S SYS: Saved savestate! path='C:/Users/Nathan/Downloads/Compressed/Drakengard Emulate/rpcs3-v0.0.27-14812-cf5346c2_win64//savestates/BLUS31197.SAVESTAT'"

but when I save on NPUB31251 I only get this line and rpcs3 itself also crashes:

"S SYS: Saved savestate! path='C:/Users/Nathan/Downloads/Compressed/Drakengard Emulate/rpcs3-v0.0.27-14812-cf5346c2_win64//savestates/NPUB31251.SAVESTAT'"

logs
[NPUB31251 RPCS3.log](https://github.com/RPCS3/rpcs3/files/11007751/RPCS3.log) - Not Working
[BLUS31197 RPCS3.log](https://github.com/RPCS3/rpcs3/files/11007756/RPCS3.log) - Working Fine

**Comment by elad335** [comment]
Closing until reported to be not fixed because there were lots of related fixes recently.
