### ISSUE TITLE
Problem with starting MGS4 

### ISSUE THREAD

**Issue by Staffle455** [RPCS3/rpcs3#13576]
### Quick summary

Just started playing the MGS saga and i can't play the game.

### Details

It all started with an know issue, having no response in the menu. I fixed it using PS3 merge, but now when I try to start a new game, it just freezes and there's nothing I can do.  

I am playing the BLES00246. I have the what the configuration that this video recommended :
 https://www.youtube.com/watch?v=b89MAO5J2tA&t=610s
I think I have a newer version of RPCS3 so I could not follow all steps.  I just started emulating games, so when searching for the fix, I don't understand much.  

### Attach a log file

E SYS: 'cellSaveDataListAutoLoad' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
U cellSysutil TODO: cellAudioOutGetDeviceInfo(audioOut=1, deviceIndex=0, info=*0xd0032960) x900
E RSX: Invalid NV4097_SET_INDEX_ARRAY_DMA value: 0x20a109c0
U cellSysutil TODO: cellAudioOutGetDeviceInfo(audioOut=1, deviceIndex=0, info=*0xd0032960) x108

### System configuration

Processor	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
Installed RAM	16,0 GB 
 NVIDIA GEFORCE RTX 3050 LAPTOP GPU
OS Windows 11 Home Single Language

**Comment by Ordinary205** [comment]
> I am playing the BLES00246. I have the what the configuration that this video recommended :
https://www.youtube.com/watch?v=b89MAO5J2tA&t=610s

The video that you watched is pretty much outdated.
I recommend watching this video https://www.youtube.com/watch?v=FvB8q2SEIFs

**Comment by Ordinary205** [comment]
Btw you should discuss this on RPCS3 forums, not on github.

**Comment by Asinin3** [comment]
Issue tracker is for reporting bugs, not for asking for support. But regardless your posts would get deleted for asking for help with pirated material which may be the reason it doesn't work....

**Comment by poudigne** [comment]
@Ordinary205 Spent 5hours trying to make the game works... took 20mins using your videos !! Big thanks for this !
