### ISSUE TITLE
Enabling RPCN causes Access Violation on Minecraft (Latest Update)

### ISSUE THREAD

**Issue by AtlasReunited** [RPCS3/rpcs3#13572]
### Quick summary

Opening Minecraft PS3 edition, Version 1.84 (Latest) with no DLC causes the following Error

F {PPU[0x1000014] Thread ((4J) SonyCommerce_PS3 tick) [0x00c8d0ec]} VM: Access violation reading location 0x0 (unmapped memory)

This doesn't occur with RPCN Off, exact same config

### Details

Tested with RPCN disconnected in the config and it works properly
The only difference I make is between turning this setting off. With the same settings enabled 
Config: 
LLVM Recompiler (PPU and SPU)
Approximate XFload
Enable SPU loop Detection
SPU Block Size - Safe
Preferred SPU Threads - Auto
Thread Scheduler - OS
GPU
Vulkan Renderer
Graphics Device - 2070 Super FE (Latest driver)
16:9
Framelimit off
ZCULL - Precise
Anti-Aliasing - Auto
Shader Quality - High
Resolution - 720p, 300% upscale 
Write Color Buffers
Multithread RSX Enable
Asyncronous Texture Streaming

### Attach a log file

[LOG WITHOUT RPCN ENABLED.log](https://github.com/RPCS3/rpcs3/files/11045430/LOG.WITHOUT.RPCN.ENABLED.log)

[WITH RPCN ENABLED.log](https://github.com/RPCS3/rpcs3/files/11045439/WITH.RPCN.ENABLED.log)

### System configuration

AMD Ryzen 5700X
ASUS TUF 570X PLUS WIFI
NVIDIA RTX 2070 SUPER Founders Edition
4x16 GB RAM
Accessed on 1TB SATA SSD

**Comment by MSuih** [comment]
Netplay compatibility is tracked in our wiki and not on github. We know that not everything works yet, there's no need to make issues for them. See [the page for Minecraft](https://wiki.rpcs3.net/index.php?title=Minecraft) for the currently reported status. For further discussion use the netplay channel in our Discord.
