### ISSUE TITLE
Function missing for Catherine

### ISSUE THREAD

**Issue by Zangetsu38** [RPCS3/rpcs3#1357]
Need implement this function in module cellFont for Catherine Game
>E {PPU Thread[0x1] (main_thread)[0x00c2fc1c]} Exception: 
(in file Emu\SysCalls\Modules\cellFont.cpp:623, in function cellFontGetScalePixel)
Please report this to the developers.

And other for show first loading screen 
>(in file Emu\SysCalls\Modules\cellFont.cpp:481, in function cellFontSetupRenderEffectWeight)
(in file Emu\SysCalls\Modules\cellFont.cpp:511, in function cellFontSetupRenderEffectSlant)

And for module cellAdec (in file Emu\SysCalls\Modules\CellAdec.cpp line 42, 487 and 626, need implement "CELL_ADEC_TYPE_AC3"
>E {PPU Thread[0x154f] (_libsail-control)[0x01a96758]} cellAdec TODO: Unimplemented audio codec type (2)

**Comment by tambry** [comment]
I'm pretty sure it's already well known, that cellFont is a pile of poop.
I likely will rewrite it, as per #1339.

**Comment by raven02** [comment]
As https://github.com/RPCS3/rpcs3/issues/1339 , closing this one.
