### ISSUE TITLE
Weird GLSL Error

### ISSUE THREAD

**Issue by anokidev** [RPCS3/rpcs3#13570]
### Quick summary

Hello there everyone, so I am having a problem here.

I am trying to run VSH software (PS3 UI / XMB) inside RPCS3 via OpenGL 4.3.

Yet it says that my GLSL version is incorrect, which is weird since my OpenGL version is correct (According to the requirement of RPCS). I tried to override it with MESA 3D for Windows, but it failed.

### Details

I am trying to run VSH software (PS3 UI / XMB) inside RPCS3 via OpenGL 4.3.

But I ended up having an error that says:

`F 0:00:06.600647 {RSX [0x0000000]} RSX: Compilation failed: 0:2(10): error: GLSL 4.20 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 4.00, 4.10, 1.00 ES, and 3.00 ES`

This error is weird, since my GPU (Intel HD Graphics) uses OpenGL 4.3 which uses GLSL 4.30. According to the official website, that is the requirement of RPCS3. RPCS3 then threw an error message window, and then crashed.

So I tried to override the configuration by using MESA3D drivers prebuilt for Windows (Link to repo: https://github.com/pal1000/mesa-dist-win), and then I tried to override the configuration of MESA:

- MESA_GL_VERSION_OVERRIDE=4.3
- MESA_GLSL_VERSION_OVERRIDE=430

Yet, It still doesn't work. The same error is thrown in the log, but this time, RPCS3 crashed immediately without any error window.

### Attach a log file

RPCS3 v0.0.27-14823-7e6cc02e Alpha | master
Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz | 4 Threads | 7.89 GiB RAM | TSC: 2.594GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
Qt version: Compiled against Qt 5.15.2 | Run-time uses Qt 5.15.2
Current Time: 2023-03-22T10:56:57
Thread time: 0.000000s (0.002186Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.009578 SYS: Initialization times before main(): 0.268318Gc
·! 0:00:00.009585 SYS: argc: 1, argv: 'rpcs3'
·! 0:00:00.027146 UUID: Installation ID: {dbe70ffe-7335-46f9-a198-1b66058c26b8}
·! 0:00:00.049035 {Vulkan Device Enumeration Thread} SIG: Thread time: 0.000000s (0.011781Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.049191 SYS: Setting user ID '00000001'
·! 0:00:00.054515 VFS: VFS config missing. Using default settings. Path: D:/Softwares/RPCS3/config/vfs.yml
·! 0:00:00.054599 SYS: Using VFS config:
$(EmulatorDir): ""
/dev_hdd0/: $(EmulatorDir)dev_hdd0/
/dev_hdd1/: $(EmulatorDir)dev_hdd1/
/dev_flash/: $(EmulatorDir)dev_flash/
/dev_flash2/: $(EmulatorDir)dev_flash2/
/dev_flash3/: $(EmulatorDir)dev_flash3/
/dev_bdvd/: $(EmulatorDir)dev_bdvd/
/games/: $(EmulatorDir)games/
/app_home/: ""
/dev_usb***/:
  /dev_usb000:
    Path: $(EmulatorDir)dev_usb000/
    Serial: ""
    VID: ""
    PID: ""
·! 0:00:00.054624 VFS: Mounted path "/dev_hdd0" to "D:/Softwares/RPCS3/dev_hdd0/"
·! 0:00:00.054631 VFS: Mounted path "/dev_flash" to "D:/Softwares/RPCS3//dev_flash/"
·! 0:00:00.054633 VFS: Mounted path "/dev_flash2" to "D:/Softwares/RPCS3//dev_flash2/"
·! 0:00:00.054635 VFS: Mounted path "/dev_flash3" to "D:/Softwares/RPCS3//dev_flash3/"
·! 0:00:00.054640 VFS: Mounted path "/app_home" to "//"
·! 0:00:00.054645 VFS: Mounted path "/dev_usb000" to "D:/Softwares/RPCS3/dev_usb000/"
·! 0:00:00.054697 SYS: Applying global config: D:/Softwares/RPCS3//config.yml
·! 0:00:00.060069 SYS: Logged in as user '00000001' with the username 'User'
·! 0:00:00.060251 IPC: IPC config missing. Using default settings. Path: D:/Softwares/RPCS3/config/ipc.yml
·! 0:00:00.060267 SYS: Using IPC config:
IPC Server enabled: false
IPC Port: 28012
·A 0:00:00.060361 SYS: Firmware version: 4.9
·! 0:00:00.102538 GUI: Current language changed to English (en)
·! 0:00:00.670004 Compat: Finished reading database from file: D:/Softwares/RPCS3/GuiConfigs/compat_database.dat
·! 0:00:01.228973 NET: Starting download from URL: https://update.rpcs3.net/?api=v2&c=7e6cc02e
·! 0:00:01.231245 SYS: New timer resolution: 500 us (old=1000 us, min=15625 us, max=500 us)
·! 0:00:01.944576 NET: Download finished
·S 0:00:01.944695 UPDATER: RPCS3 is up to date!
·! 0:00:05.602392 GUI: User triggered OnPlayOrPause
·! 0:00:05.602415 GUI: Booting from OnPlayOrPause...
·! 0:00:05.602995 SYS: Selected config: mode=custom config, path=""
·! 0:00:05.602999 SYS: Path: D:/Softwares/RPCS3//dev_flash/vsh/module/vsh.self
·! 0:00:05.604186 VFS: VFS config missing. Using default settings. Path: D:/Softwares/RPCS3/config/vfs.yml
·! 0:00:05.604280 SYS: Using VFS config:
$(EmulatorDir): ""
/dev_hdd0/: $(EmulatorDir)dev_hdd0/
/dev_hdd1/: $(EmulatorDir)dev_hdd1/
/dev_flash/: $(EmulatorDir)dev_flash/
/dev_flash2/: $(EmulatorDir)dev_flash2/
/dev_flash3/: $(EmulatorDir)dev_flash3/
/dev_bdvd/: $(EmulatorDir)dev_bdvd/
/games/: $(EmulatorDir)games/
/app_home/: ""
/dev_usb***/:
  /dev_usb000:
    Path: $(EmulatorDir)dev_usb000/
    Serial: ""
    VID: ""
    PID: ""
·! 0:00:05.604357 VFS: Mounted path "/dev_hdd0" to "D:/Softwares/RPCS3/dev_hdd0/"
·! 0:00:05.604407 VFS: Mounted path "/dev_flash" to "D:/Softwares/RPCS3/dev_flash/"
·! 0:00:05.604456 VFS: Mounted path "/dev_flash2" to "D:/Softwares/RPCS3/dev_flash2/"
·! 0:00:05.604503 VFS: Mounted path "/dev_flash3" to "D:/Softwares/RPCS3/dev_flash3/"
·! 0:00:05.604568 VFS: Mounted path "/app_home" to "D:/Softwares/RPCS3/dev_flash/vsh/module/"
·! 0:00:05.604615 VFS: Mounted path "/dev_usb000" to "D:/Softwares/RPCS3/dev_usb000/"
·! 0:00:05.604646 SYS: Applying global config: D:/Softwares/RPCS3//config.yml
·! 0:00:05.610309 SYS: Logged in as user '00000001' with the username 'User'
·! 0:00:05.610459 IPC: IPC config missing. Using default settings. Path: D:/Softwares/RPCS3/config/ipc.yml
·! 0:00:05.610478 SYS: Using IPC config:
IPC Server enabled: false
IPC Port: 28012
·! 0:00:05.610903 VFS: Mounted path "/app_home" to "D:/Softwares/RPCS3/dev_flash/vsh/module/"
·! 0:00:05.611106 SYS: Title: vsh.self
·! 0:00:05.611108 SYS: Serial: 
·! 0:00:05.611109 SYS: Category: 
·! 0:00:05.611110 SYS: Version: APP_VER=Unknown VERSION=Unknown
·! 0:00:05.614768 SYS: Used configuration:
Core:
  PPU Decoder: Interpreter (static)
  PPU Threads: 2
  PPU Debug: false
  PPU Calling History: false
  Save LLVM logs: false
  Use LLVM CPU: ""
  Max LLVM Compile Threads: 0
  PPU LLVM Greedy Mode: false
  PPU LLVM Precompilation: true
  Thread Scheduler Mode: Operating System
  Set DAZ and FTZ: false
  SPU Decoder: Recompiler (LLVM)
  SPU Reservation Busy Waiting Percentage: 0
  SPU GETLLAR Busy Waiting Percentage: 100
  SPU Debug: false
  MFC Debug: false
  Preferred SPU Threads: 0
  SPU delay penalty: 3
  SPU loop detection: false
  Max SPURS Threads: 6
  SPU Block Size: Safe
  Accurate GETLLAR: false
  Accurate SPU DMA: false
  Accurate SPU Reservations: true
  Accurate Cache Line Stores: false
  Accurate RSX reservation access: false
  RSX FIFO Accuracy: Fast
  SPU Verification: true
  SPU Cache: true
  SPU Profiler: false
  MFC Commands Shuffling Limit: 0
  MFC Commands Timeout: 0
  MFC Commands Shuffling In Steps: false
  Enable TSX: Disabled
  Accurate xfloat: false
  Approximate xfloat: true
  Relaxed xfloat: true
  Accurate PPU 128-byte Reservation Op Max Length: 0
  Stub PPU Traps: 0
  Full Width AVX-512: false
  PPU LLVM Java Mode Handling: true
  Use Accurate DFMA: true
  PPU Set Saturation Bit: false
  PPU Accurate Non-Java Mode: false
  PPU Fixup Vector NaN Values: false
  PPU Accurate Vector NaN Values: false
  PPU Set FPCC Bits: false
  Debug Console Mode: false
  Hook static functions: false
  Libraries Control:
    []
  HLE lwmutex: false
  SPU LLVM Lower Bound: 0
  SPU LLVM Upper Bound: 18446744073709551615
  TSX Transaction First Limit: 800
  TSX Transaction Second Limit: 2000
  Clocks scale: 100
  SPU Wake-Up Delay: 0
  SPU Wake-Up Delay Thread Mask: 63
  Max CPU Preempt Count: 43
  Allow RSX CPU Preemptions: true
  Sleep Timers Accuracy: Usleep Only
  Performance Report Threshold: 500
  Enable Performance Report: false
  Assume External Debugger: false
VFS:
  Enable /host_root/: false
  Initialize Directories: true
  Limit disk cache size: false
  Disk cache maximum size (MB): 5120
  Empty /dev_hdd0/tmp/: true
Video:
  Renderer: OpenGL
  Resolution: 1280x720
  Aspect ratio: 16:9
  Frame limit: Auto
  Second Frame Limit: 0
  MSAA: Auto
  Shader Mode: Async Shader Recompiler
  Shader Precision: Auto
  Write Color Buffers: true
  Write Depth Buffer: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Log shader programs: false
  VSync: true
  Debug output: false
  Debug overlay: false
  Renderdoc Compatibility Mode: false
  Use GPU texture scaling: false
  Stretch To Display Area: false
  Force High Precision Z buffer: false
  Strict Rendering Mode: false
  Disable ZCull Occlusion Queries: false
  Disable Video Output: false
  Disable Vertex Cache: false
  Disable FIFO Reordering: false
  Enable Frame Skip: false
  Force CPU Blit: true
  Disable On-Disk Shader Cache: false
  Disable Vulkan Memory Allocator: false
  Use full RGB output range: true
  Strict Texture Flushing: false
  Multithreaded RSX: true
  Relaxed ZCULL Sync: false
  Enable 3D: true
  Debug Program Analyser: false
  Accurate ZCULL stats: false
  Consecutive Frames To Draw: 1
  Consecutive Frames To Skip: 1
  Resolution Scale: 100
  Anisotropic Filter Override: 0
  Texture LOD Bias Addend: 0
  Minimum Scalable Dimension: 16
  Shader Compiler Threads: 0
  Driver Recovery Timeout: 1000000
  Driver Wake-Up Delay: 1
  Vblank Rate: 60
  Vblank NTSC Fixup: false
  DECR memory layout: false
  Allow Host GPU Labels: false
  Disable MSL Fast Math: false
  Output Scaling Mode: Bilinear
  Vulkan:
    Adapter: ""
    Force FIFO present mode: false
    Force primitive restart flag: false
    Exclusive Fullscreen Mode: Automatic
    Asynchronous Texture Streaming 2: false
    FidelityFX CAS Sharpening Intensity: 50
    Asynchronous Queue Scheduler: Safe
  Performance Overlay:
    Enabled: false
    Enable Framerate Graph: false
    Enable Frametime Graph: false
    Framerate datapoints: 50
    Frametime datapoints: 170
    Detail level: Medium
    Framerate graph detail level: All
    Frametime graph detail level: All
    Metrics update interval (ms): 350
    Font size (px): 10
    Position: Top Left
    Font: n023055ms.ttf
    Horizontal Margin (px): 50
    Vertical Margin (px): 50
    Center Horizontally: false
    Center Vertically: false
    Opacity (%): 70
    Body Color (hex): "#FFE138FF"
    Body Background (hex): "#002339FF"
    Title Color (hex): "#F26C24FF"
    Title Background (hex): "#00000000"
  Shader Loading Dialog:
    Allow custom background: true
    Darkening effect strength: 30
    Blur effect strength: 0
Audio:
  Renderer: Cubeb
  Audio Provider: RSXAudio
  RSXAudio Avport: HDMI 0
  Dump to file: false
  Convert to 16 bit: false
  Audio Format: Stereo
  Audio Formats: 0
  Audio Device: "@@@default@@@"
  Master Volume: 100
  Enable Buffering: true
  Desired Audio Buffer Duration: 100
  Enable Time Stretching: false
  Disable Sampling Skip: false
  Time Stretching Threshold: 75
  Microphone Type: "Null"
  Microphone Devices: "@@@@@@@@@@@@"
  Music Handler: Qt
Input/Output:
  Keyboard: "Null"
  Mouse: Basic
  Camera: "Null"
  Camera type: Unknown
  Camera flip: None
  Camera ID: Default
  Move: "Null"
  Buzz emulated controller: "Null"
  Turntable emulated controller: "Null"
  GHLtar emulated controller: "Null"
  Pad handler mode: Single-threaded
  Pad handler sleep (microseconds): 1000
  Background input enabled: true
  Show move cursor: false
System:
  License Area: SCEA
  Language: English (US)
  Keyboard Type: English keyboard (US standard)
  Enter button assignment: Enter with cross
  Console time offset (s): 0
  PSID high: 0
  PSID low: 0
Net:
  Internet enabled: Disconnected
  IP address: 0.0.0.0
  Bind address: 0.0.0.0
  DNS address: 8.8.8.8
  IP swap list: ""
  UPNP Enabled: false
  PSN status: Disconnected
Savestate:
  Start Paused: false
  Suspend Emulation Savestate Mode: false
  Inspection Mode Savestates: false
  Save Disc Game Data: false
Miscellaneous:
  Automatically start games after boot: true
  Exit RPCS3 when process finishes: false
  Start games in fullscreen mode: false
  Prevent display sleep while running games: true
  Show trophy popups: true
  Show shader compilation hint: true
  Use native user interface: true
  GDB Server: 127.0.0.1:2345
  Silence All Logs: false
  Window Title Format: "FPS: %F | %R | %V | %T [%t]"
  Pause Emulation During Home Menu: false
Log:
  {}

·! 0:00:05.614989 SYS: Ignoring empty vfs BDVD directory: 'D:/Softwares/RPCS3/dev_bdvd/'
·! 0:00:05.692155 VM: Guest memory bases address ranges:
vm::g_base_addr = 0000000300000000 - 00000003ffffffff
vm::g_sudo_addr = 0000000400000000 - 00000004ffffffff
vm::g_exec_addr = 0000000500000000 - 00000006ffffffff
vm::g_hook_addr = 0000000700000000 - 0000000effffffff
vm::g_stat_addr = 0000000f00000000 - 0000000fffffffff
vm::g_reservations = 0000000005bab000 - 0000000005bb2fff

·! 0:00:05.741244 SYS: Elf path: /dev_flash/vsh/module/vsh.self
·! 0:00:05.741286 ppu_loader: ** Segment: p_type=0x1, p_vaddr=0x10000, p_filesz=0x6abea8, p_memsz=0x6abea8, flags=0x400005
·! 0:00:05.797861 ppu_loader: ** Segment: p_type=0x1, p_vaddr=0x6c0000, p_filesz=0x48108, p_memsz=0x91398, flags=0x600006
·! 0:00:05.799795 ppu_loader: ** Segment: p_type=0x1, p_vaddr=0x0, p_filesz=0x0, p_memsz=0x0, flags=0x4
·! 0:00:05.799801 ppu_loader: ** Segment: p_type=0x1, p_vaddr=0x0, p_filesz=0x0, p_memsz=0x0, flags=0x6
·! 0:00:05.799803 ppu_loader: ** Segment: p_type=0x1, p_vaddr=0x0, p_filesz=0x0, p_memsz=0x0, flags=0x6600006
·! 0:00:05.799805 ppu_loader: ** Segment: p_type=0x7, p_vaddr=0x6f0bdc, p_filesz=0x8, p_memsz=0x18c, flags=0x4
·! 0:00:05.799807 ppu_loader: ** Segment: p_type=0x60000001, p_vaddr=0x6bbe80, p_filesz=0x28, p_memsz=0x28, flags=0x0
·! 0:00:05.799809 ppu_loader: ** Segment: p_type=0x60000002, p_vaddr=0x0, p_filesz=0x0, p_memsz=0x0, flags=0x0
·! 0:00:05.799817 ppu_loader: ** Section: sh_type=0x0, addr=0x0, size=0x0, flags=0x0
·! 0:00:05.799819 ppu_loader: ** Section: sh_type=0x1000000, addr=0x10200, size=0x2c, flags=0x6
·! 0:00:05.799821 ppu_loader: ** Section: sh_type=0x1000000, addr=0x10230, size=0x624f3c, flags=0x6
·! 0:00:05.799822 ppu_loader: ** Section: sh_type=0x1000000, addr=0x63516c, size=0x24, flags=0x6
·! 0:00:05.799824 ppu_loader: ** Section: sh_type=0x1000000, addr=0x635190, size=0x2a70, flags=0x6
·! 0:00:05.799826 ppu_loader: ** Section: sh_type=0x1000000, addr=0x637c00, size=0x9de4, flags=0x2
·! 0:00:05.799827 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6419e4, size=0x308, flags=0x2
·! 0:00:05.799828 ppu_loader: ** Section: sh_type=0x1000000, addr=0x641cec, size=0x4, flags=0x2
·! 0:00:05.799830 ppu_loader: ** Section: sh_type=0x1000000, addr=0x641cf0, size=0x310, flags=0x2
·! 0:00:05.799832 ppu_loader: ** Section: sh_type=0x1000000, addr=0x642000, size=0x4, flags=0x2
·! 0:00:05.799833 ppu_loader: ** Section: sh_type=0x1000000, addr=0x642004, size=0x4, flags=0x2
·! 0:00:05.799835 ppu_loader: ** Section: sh_type=0x1000000, addr=0x642008, size=0x420, flags=0x2
·! 0:00:05.799836 ppu_loader: ** Section: sh_type=0x1000000, addr=0x642428, size=0x4, flags=0x2
·! 0:00:05.799837 ppu_loader: ** Section: sh_type=0x1000000, addr=0x642430, size=0x77538, flags=0x2
·! 0:00:05.799839 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6b9980, size=0x2500, flags=0x2
·! 0:00:05.799843 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6bbe80, size=0x28, flags=0x3
·! 0:00:05.799844 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6c0000, size=0x2b8, flags=0x3
·! 0:00:05.799846 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6c02b8, size=0x244, flags=0x3
·! 0:00:05.799847 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6c04fc, size=0x4, flags=0x3
·! 0:00:05.799848 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6c0500, size=0x152b0, flags=0x3
·! 0:00:05.799849 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6d57b0, size=0x308, flags=0x3
·! 0:00:05.799852 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6d5ab8, size=0x17aa0, flags=0x3
·! 0:00:05.799853 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6ed558, size=0x3684, flags=0x3
·! 0:00:05.799854 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6f0bdc, size=0x8, flags=0x403
·! 0:00:05.799855 ppu_loader: ** Section: sh_type=0x8000000, addr=0x6f0be8, size=0x180, flags=0x403
·! 0:00:05.799857 ppu_loader: ** Section: sh_type=0x1000000, addr=0x6f0d68, size=0x173a0, flags=0x3
·! 0:00:05.799858 ppu_loader: ** Section: sh_type=0x8000000, addr=0x708110, size=0x49288, flags=0x3
·! 0:00:05.799859 ppu_loader: ** Section: sh_type=0x3000000, addr=0x0, size=0x106, flags=0x0
·W 0:00:05.799868 ppu_loader: PPU executable hash: PPU-a09ab580f4c6a934e9ce700b28c42eb123d6d4bb
·W 0:00:05.808934 ppu_loader: SPU executable hash: SPU-fbc876830c5dfbfbc374f48cbfe1d9f5fe22219c
	Segment: p_type=0x1, p_vaddr=0x80, p_filesz=0x720, p_memsz=0x720, p_offset=0x100
	Segment: p_type=0x1, p_vaddr=0x800, p_filesz=0x20, p_memsz=0x42e0, p_offset=0x880
	Segment: p_type=0x4, p_vaddr=0x0, p_filesz=0x34, p_memsz=0x34, p_offset=0x8a0
	SPUNAME: 'ps3-release/ps3/surf_spu.elf'
·! 0:00:05.809037 ppu_loader: SELF header information found: ctrl_flags1=0x40000000, authid=0x10700005ff000001
·! 0:00:05.809041 ppu_loader: TLS info segment found: tls-image=*0x6f0bdc, image-size=0x8, tls-size=0x18c
·! 0:00:05.809050 ppu_loader: *** sdk version: 0x490000
·! 0:00:05.809052 ppu_loader: *** primary prio: 900
·! 0:00:05.809053 ppu_loader: *** primary stacksize: 0x9000
·! 0:00:05.809054 ppu_loader: *** malloc pagesize: 0x10000
·! 0:00:05.809055 ppu_loader: *** ppc seg: 0x0
·! 0:00:05.819416 PPU: Reading OPD section at 0x6d5ab8...
·! 0:00:06.220497 PPU: Function analysis: 28324 functions (81912 enqueued)
·W 0:00:07.090518 PPU: Block 0x636c08 will be compiled on per-instruction basis (size=0x28)
·W 0:00:07.090549 PPU: Block 0x636c30 will be compiled on per-instruction basis (size=0x10)
·! 0:00:07.184932 PPU: Block analysis: 318775 blocks (1 enqueued)
·! 0:00:07.187081 SYS: Cache: D:/Softwares/RPCS3/cache/ppu-Zy3adtyhTaqpYYxUP6iTsA77c1e1-vsh.self/
·S 0:00:07.187381 PPU: Enabled: Non-Java Mode Fixup
·! 0:00:07.189092 {GDB Server} GDB: Started listening on '127.0.0.1:2345'.
·! 0:00:07.193931 {RsxAudio Backend Thread} Cubeb: Using backend wasapi
·! 0:00:07.193968 {RsxAudio Backend Thread} Cubeb: Trying to open default device
·! 0:00:07.193971 {RsxAudio Backend Thread} Cubeb: Searching for default device
·! 0:00:07.196101 cellSysutil: cellAudioOut: found support for Linear PCM 2 Ch.
·! 0:00:07.196136 cellSysutil: cellAudioOut: added primary mode: type=0, channel=2, fs=4, layout=1
·! 0:00:07.196141 cellSysutil: cellAudioOut: added secondary mode: type=0, channel=2, fs=4, layout=1
·! 0:00:07.196144 cellSysutil: cellAudioOut: initial primary output configuration: channels=2, encoder=0, downmixer=0
·! 0:00:07.196146 cellSysutil: cellAudioOut: initial secondary output configuration: channels=2, encoder=0, downmixer=0
·! 0:00:07.196345 {NP Handler Thread} SIG: Thread time: 0.000000s (0.000431Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:07.196454 {cellAudio Thread} SIG: Thread time: 0.000000s (0.000402Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:07.202986 {RsxAudio Backend Thread} Cubeb: Found 1 possible output devices
·! 0:00:07.203008 {RsxAudio Backend Thread} Cubeb: Found device '{0.0.0.00000000}.{21100605-d39b-4fdc-8a85-7fd931032629}' with 2 channels
·! 0:00:07.235429 {RsxAudio Backend Thread} Cubeb: Stream started
·! 0:00:07.339809 sys_usbd: Adding emulated skylander
·! 0:00:07.339819 sys_usbd: Adding emulated v406 usio
·! 0:00:07.339972 {Gem Thread} cellGem: Starting thread
·! 0:00:07.340085 Music: Constructing Qt music handler...
·! 0:00:07.376543 CFG: Loading recording config from 'D:/Softwares/RPCS3/config/recording.yml'
·! 0:00:07.401171 {Pad Thread} Input: Using pad profile: 'Default'
·! 0:00:07.401190 {Pad Thread} Input: Loading pad config (title_id='', profile='Default', strict=0)
·! 0:00:07.401640 {Pad Thread} Input: Loading pad profile: 'D:/Softwares/RPCS3/config/input_configs/global/Default.yml'
·! 0:00:07.409278 {Pad Thread} Input: Loading pad config (title_id='', profile='Default', strict=0)
·! 0:00:07.409550 {Pad Thread} Input: Loading pad profile: 'D:/Softwares/RPCS3/config/input_configs/global/Default.yml'
·! 0:00:07.419507 {Pad Thread} Input: Pad 0: device='Keyboard', handler=Keyboard, VID=0x54c, PID=0x268, class_type=0x0, class_profile=0x0
·! 0:00:07.419544 {Pad Thread} Input: Pad 1: device='Null', handler=Null, VID=0x0, PID=0x0, class_type=0x0, class_profile=0x0
·! 0:00:07.419571 {Pad Thread} Input: Pad 2: device='Null', handler=Null, VID=0x0, PID=0x0, class_type=0x0, class_profile=0x0
·! 0:00:07.419575 {Pad Thread} Input: Pad 3: device='Null', handler=Null, VID=0x0, PID=0x0, class_type=0x0, class_profile=0x0
·! 0:00:07.419578 {Pad Thread} Input: Pad 4: device='Null', handler=Null, VID=0x0, PID=0x0, class_type=0x0, class_profile=0x0
·! 0:00:07.419581 {Pad Thread} Input: Pad 5: device='Null', handler=Null, VID=0x0, PID=0x0, class_type=0x0, class_profile=0x0
·! 0:00:07.419587 {Pad Thread} Input: Pad 6: device='Null', handler=Null, VID=0x0, PID=0x0, class_type=0x0, class_profile=0x0
·! 0:00:07.419592 {Pad Thread} Input: Stopping pad threads...
·! 0:00:07.419594 {Pad Thread} Input: Pad threads stopped
·S 0:00:07.419595 {Pad Thread} Input: The pad mode was changed to Single-threaded
·S 0:00:07.424351 GUI: Boot successful.
·E 0:00:07.599648 {RSX [0x0000000]} RSX: OpenGL: initialization of glNamedFramebufferTextureEXT failed.
·E 0:00:07.599704 {RSX [0x0000000]} RSX: OpenGL: initialization of glDepthRangedNV failed.
·E 0:00:07.599709 {RSX [0x0000000]} RSX: OpenGL: initialization of glDepthBoundsdNV failed.
·E 0:00:07.599714 {RSX [0x0000000]} RSX: OpenGL: initialization of glInsertEventMarkerEXT failed.
·! 0:00:07.599725 {RSX [0x0000000]} RSX: GL RENDERER: D3D12 (Intel(R) HD Graphics 4600) (Microsoft Corporation)
·! 0:00:07.599733 {RSX [0x0000000]} RSX: GL VERSION: 4.3 (Core Profile) Mesa 23.0.0 (git-329da73d91)
·! 0:00:07.599736 {RSX [0x0000000]} RSX: GLSL VERSION: 4.30
·! 0:00:07.599767 {RSX [0x0000000]} RSX: Extension GL_ARB_buffer_storage is supported
·! 0:00:07.599774 {RSX [0x0000000]} RSX: Extension GL_ARB_depth_buffer_float is supported
·! 0:00:07.599777 {RSX [0x0000000]} RSX: Extension GL_ARB_direct_state_access is supported
·! 0:00:07.599806 {RSX [0x0000000]} RSX: Extension GL_ARB_shader_draw_parameters is supported
·! 0:00:07.599816 {RSX [0x0000000]} RSX: Extension GL_ARB_texture_buffer_object is supported
·W 0:00:07.599901 {RSX [0x0000000]} RSX: Texture barriers are not supported by your GPU. Feedback loops will have undefined results.
·! 0:00:07.599926 {RSX [0x0000000]} RSX: Supported texel buffer size reported: 65536 bytes
·E 0:00:07.599929 {RSX [0x0000000]} RSX: Max texture buffer size supported is less than 16M which is useless. Expect undefined behaviour.

### Attach capture files for visual issues

None, RPCS3 crashed before showing a game window.

### System configuration

PC Specification:

Processor	Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz   2.59 GHz
Installed RAM	8,00 GB (7,89 GB usable)
System type	64-bit operating system, x64-based processor

GPU Specification:

Model           Intel(R) HD Graphics 4600
OpenGL Version  4.3.0 - Build 20.19.15.5126
GLSL Version    4.30 - Build 20.19.15.5126

Softwares:      
RPCS3           0.0.27-14823-7e6cc02e Alpha | master
Mesa 3D         23.0.0
PS3 Firmware    4.90

### Other details

Nothing.

**Comment by AniLeo** [comment]
Below minimum requirements, 4th gen iGPU doesn't support OpenGL and in general no Intel GPU works properly with OpenGL on Windows drivers

**Comment by anokidev** [comment]
Thank you.
