### ISSUE TITLE
[Regression] Screen turns pitch black except for all lighting elements (#13236)

### ISSUE THREAD

**Issue by Ferrari458GT4** [RPCS3/rpcs3#13581]
### Quick summary

When the player looks in certain directions in game BLUS30072, the screen turns black and only lights are visible until the player changes their viewing direction. This issue is first present in version 0.0.26-14570.

### Details

![image](https://user-images.githubusercontent.com/128953201/227798172-08ebc047-364f-49ee-ba5a-46d673253e90.png)

### Build with regression

v0.0.26-14570

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11072795/RPCS3.log) - works, 14569
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11072810/RPCS3.log) - doesn't 14570

### Attach capture files for visual issues

https://drive.google.com/open?id=1XyFDCauxyQH6KAxH52y6qG7-ACh2m56o&usp=drive_copy

### System configuration

intel core i9 12th gen
nvidia gtx 3060
msi raider ge76
geforce game ready driver 528.24

**Comment by AniLeo** [comment]
Breaking PR is #13236, adding @kd-11

**Comment by kd-11** [comment]
I'll look into it. Moving to high priority regressions.

**Comment by kd-11** [comment]
@Ferrari458GT4 Could you attach the RSX capture? It's ok even if it plays back a blank screen, I'm more interested in the internal command sequence.

**Comment by Ferrari458GT4** [comment]
> @Ferrari458GT4 Could you attach the RSX capture? It's ok even if it plays back a blank screen, I'm more interested in the internal command sequence.

I will attach that soon. I'm a bit preoccupied right now, but I'll get that done by the end of the day.

**Comment by Ferrari458GT4** [comment]
> @Ferrari458GT4 Could you attach the RSX capture? It's ok even if it plays back a blank screen, I'm more interested in the internal command sequence.

Done.
