### ISSUE TITLE
[Feature request] Custom Configuration Profiles

### ISSUE THREAD

**Issue by CHOUAiB** [RPCS3/rpcs3#13585]
### Quick summary

Hi, is there any chance to add features to save multiple custom configuration for one game and select from context menu or boot from specific custom configuration profile.

**Comment by Darkhost1999** [comment]
You can create and rename as many configurations as you would like.
Right click and boot with manually selected file. They just need to follow the rules of your operating system and have unique names.

**Comment by MSuih** [comment]
You could also create shortcuts and use the command line parameter --config to specify a configuration file to run the game with.

**Comment by AniLeo** [comment]
Considered as already implemented since you can use "Boot with manually selected configuration" or the CLI argument
