### ISSUE TITLE
[Regression] Vocals no longer display on game Guitar Hero Live (#13484)

### ISSUE THREAD

**Issue by TheGuitarHeroNerd** [RPCS3/rpcs3#13588]
### Quick summary

as of #13484 vocals no longer display on the game Guitar Hero Live.

### Details

As of #13484, vocals no longer display in game.

Before you use to be able to set the mics here, one thing to note is i'm using a headset and not a microphone. 

![image](https://user-images.githubusercontent.com/73220666/228421736-602ab9dd-09d0-48e7-bfd7-f4d11f226cea.png)

But ever since the latest update vocals no longer display even if a headset is selected, I gotta be honest i'm not 100% sure if this is a bug in RPCS3 or if it's sadly how it's meant to be.

If it's not a bug then it sucks for me and a few others since we like to have vocals being displayed even if we ain't playing them since it's good to have while streaming or on YT videos and for testing custom content.

![image](https://user-images.githubusercontent.com/73220666/228421746-d2474516-ed56-46a2-9c63-fa42922bd661.png)

### Build with regression

v0.0.27-14833-a8ada492

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11096468/RPCS3.log.gz)

**Comment by TheGuitarHeroNerd** [comment]
So turns out it works for others it works, one thing to note my headset doesn't have any output.

![image](https://user-images.githubusercontent.com/73220666/228789527-b7ae9b9e-1da1-47fa-aab0-e1d707965830.png)

So unsure if an emulated mic option is required to fix this, as this is very important for all the work i do.

**Comment by AniLeo** [comment]
Adding @Megamouse

**Comment by Megamouse** [comment]
try with https://github.com/RPCS3/rpcs3/pull/13614

**Comment by TheGuitarHeroNerd** [comment]
Sadly no change for me.

**Comment by Megamouse** [comment]
When you say it works for others, that sounds like it's an issue with your system.
