### ISSUE TITLE
Catherine [BLUS-30428]: DX12, unimplemented mag filter CELL_GCM_TEXTURE_LINEAR_NEAREST 

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1358]
@vlj, take a look at this:
```
RSX: E {rsx::thread} file Emu\RSX\D3D12\D3D12Formats.cpp line 252 : Unimplemented mag filter used 4, please report this to a developer.
```
Used LLE of cellspurs, font and fiber to launch.

**Comment by Zangetsu38** [comment]
@danilaml  i have already fixed this, just waiting vlj confim ^^

**Comment by tambry** [comment]
@Zangetsu38 Since a word contains half of another word, doesn't mean they're same...

**Comment by tambry** [comment]
@danilaml Is this still an issue?

**Comment by danilaml** [comment]
@tambry. I think it should be fixed by https://github.com/RPCS3/rpcs3/pull/1415 (haven't tested yet)

**Comment by danilaml** [comment]
Yeah, it fixed now. Now game just "deadlocks" with frozen fps as before: http://pastebin.com/MBygtUVP. Maybe some libs need LLEing.
