### ISSUE TITLE
[Feature request] Filter grid mode categories

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#13580]
### Quick summary

Follow up improvements like this
https://github.com/RPCS3/rpcs3/pull/5382
But for grid mode too.

### Details

Enable view -> game categories for grid mode if possible allowing more personalization and better filtering of games and content people may have installed without necessarily "hiding" the content with right click -> hide.

**Comment by MSuih** [comment]
Game data would need an icon for this case, as without one it can be hard to tell which is which. Or it could be moved to separate menu like how PS3 handles it.

Also maybe this is just my use case but I liked having game data hidden in grid mode but then being able to be shown by just switching to list mode.

**Comment by Darkhost1999** [comment]
Yea I do like just swapping to list mode when I need game data.
It's the 1 thing I kind of don't want to show in grid mode.
But the rest of the categories don't filter either. And I'm not trying to isolate 1 option as "not good enough" for grid mode. Lol.
We can use a hdd icon. Like how we have custom configs and custom controller config indicators. We can add 1 for gamedata that is like a hdd icon if we need to. As an idea.
