### ISSUE TITLE
No Strict Rendering Mode makes Castlevania: Harmony of Despair crash on m1 MacBook Air

### ISSUE THREAD

**Issue by s-m-t** [RPCS3/rpcs3#13590]
### Quick summary

Without strict rendering mode enabled I'm getting consistent crashes on Castlevania: Harmony of Despair.

The m1 GPU or the moltenVK compatibility layer doesn't seem to like the unsafe method 'stretch_image_typeless_unsafe' used in the branches taken when 'use_unsafe_transport' is true. Every crash points to stack traces with texture operations.

https://github.com/RPCS3/rpcs3/blob/a3ededdcf148fcbb05ffa200ea74c762e64652ff/rpcs3/Emu/RSX/VK/VKTexture.cpp#L542

### Attach a log file

[maccrashreport.txt](https://github.com/RPCS3/rpcs3/files/11100962/maccrashreport.txt)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11100978/RPCS3.log)

### System configuration

Chip: Apple m1
Memory: 8GB
MacOS: 13.1 (22C65)

**Comment by kd-11** [comment]
MoltenVK is largely untested (same with intel Arc) so such per-vendor optimizations are likely to cause issues. A fix will be pushed shortly to block moltenvk from the optimistic path.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/13591
The main issue here is that we were not actually classifying the M1 GPU. It was just loaded as "unknown".
