### ISSUE TITLE
[Feature request] Optionally add flash & supervisor dump from an actual PS3

### ISSUE THREAD

**Issue by robokingscosmosps3** [RPCS3/rpcs3#13594]
### Quick summary

Hello as I'm new to RPCS3 I would see the benefits of needing lv2 and flash
You can dump those from xai plugin of CFW

### Details

It will ask you to select your LV2 and flash dumps with working on superslim dumps to play your games those would be required from PS3HEN and Evilnat

**Comment by RobokingsCosmos** [comment]
If superslim flash doesn't work make it optional for selecting flash dumps

**Comment by RobokingsCosmos** [comment]
Well you basically own a PS3, you can I guess forget the requirement you can use the default or use a Dump for ps3 emulation and be able to select hypervisor as well if have cfw or default

**Comment by RobokingsCosmos** [comment]
However the files can be selected from windows/linux/mac and copied to RPCS3 folder just like firmware

**Comment by RobokingsCosmos** [comment]
Full NAND and NOR support as well forgot to add

**Comment by robokingscosmosps3** [comment]
I hope the testing on NAND and NOR consoles goes well though because it may be incompatible but we can at least try right? all you need to do is test Hardware PS2 PS3 NAND and a Software PS2 and make sure they are testing on all GPUs

**Comment by robokingscosmosps3** [comment]
Also you might want to add a workaround for superslim flash because it has metldr2 on it, and not even sure if that can be included in the emulator without
also show the minver whenever a flash dump is selected and installed to RPCS3 directory

**Comment by RipleyTom** [comment]
You've failed to make any relevant point as to why this would be useful to have this feature in rpcs3.

**Comment by robokingscosmosps3** [comment]
Since everyone on Discord were being assholes why doesn't someone else claim my idea and clear out a better point then cause i give up
