### ISSUE TITLE
NPUA80662 - Crash when touching the ground. 

### ISSUE THREAD

**Issue by mikoprimebusiek** [RPCS3/rpcs3#13600]
### Quick summary

After entering the pod and Sackboy is touching the ground the game crashes. 

### Attach a log file

RPCS3 v0.0.27-14839-3e556c71 Alpha | master
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz | 8 Threads | 7.88 GiB RAM | TSC: 1.800GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
Qt version: Compiled against Qt 5.15.2 | Run-time uses Qt 5.15.2
Current Time: 2023-04- 1T20:51:54
Thread time: 0.000000s (0.000891Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.007768 SYS: Initialization times before main(): 0.065802Gc
·! 0:00:00.007783 SYS: argc: 1, argv: 'C:\Users\mikoprimeb\Desktop\Rcps3\rpcs3.exe'
·! 0:00:00.020797 UUID: Installation ID: {62120a68-b684-4cf8-93ca-ce78c16894eb}
·A 0:00:00.097638 {Vulkan Device Enumeration Thread} RSX: Found vulkan-compatible GPU: 'Intel(R) UHD Graphics 620' running on driver 0.402.537
·! 0:00:00.100561 {Vulkan Device Enumeration Thread} SIG: Thread time: 0.062500s (0.116819Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.100617 CFG: Setting the default renderer to Vulkan. Default GPU: 'Intel(R) UHD Graphics 620'
·! 0:00:00.100639 SYS: Setting user ID '00000001'
·! 0:00:00.107259 VFS: VFS config missing. Using default settings. Path: C:/Users/mikoprimeb/Desktop/Rcps3/config/vfs.yml
·! 0:00:00.107471 SYS: Using VFS config:
$(EmulatorDir): ""
/dev_hdd0/: $(EmulatorDir)dev_hdd0/
/dev_hdd1/: $(EmulatorDir)dev_hdd1/
/dev_flash/: $(EmulatorDir)dev_flash/
/dev_flash2/: $(EmulatorDir)dev_flash2/
/dev_flash3/: $(EmulatorDir)dev_flash3/
/dev_bdvd/: $(EmulatorDir)dev_bdvd/
/games/: $(EmulatorDir)games/
/app_home/: ""
/dev_usb***/:
  /dev_usb000:
    Path: $(EmulatorDir)dev_usb000/
    Serial: ""
    VID: ""
    PID: ""
·! 0:00:00.107502 VFS: Mounted path "/dev_hdd0" to "C:/Users/mikoprimeb/Desktop/Rcps3/dev_hdd0/"
·! 0:00:00.107508 VFS: Mounted path "/dev_flash" to "C:/Users/mikoprimeb/Desktop/Rcps3//dev_flash/"
·! 0:00:00.107514 VFS: Mounted path "/dev_flash2" to "C:/Users/mikoprimeb/Desktop/Rcps3//dev_flash2/"
·! 0:00:00.107518 VFS: Mounted path "/dev_flash3" to "C:/Users/mikoprimeb/Desktop/Rcps3//dev_flash3/"
·! 0:00:00.107522 VFS: Mounted path "/app_home" to "//"
·! 0:00:00.107528 VFS: Mounted path "/dev_usb000" to "C:/Users/mikoprimeb/Desktop/Rcps3/dev_usb000/"
·! 0:00:00.107606 SYS: Applying global config: C:/Users/mikoprimeb/Desktop/Rcps3//config.yml
·! 0:00:00.119756 SYS: Logged in as user '00000001' with the username 'User'
·! 0:00:00.120085 IPC: IPC config missing. Using default settings. Path: C:/Users/mikoprimeb/Desktop/Rcps3/config/ipc.yml
·! 0:00:00.120113 SYS: Using IPC config:
IPC Server enabled: false
IPC Port: 28012
·A 0:00:00.120242 SYS: Firmware version: 4.9
·! 0:00:00.160687 GUI: Current language changed to English (en)
·! 0:00:00.494155 Compat: Finished reading database from file: C:/Users/mikoprimeb/Desktop/Rcps3/GuiConfigs/compat_database.dat
·! 0:00:00.941992 NET: Starting download from URL: https://update.rpcs3.net/?api=v2&c=3e556c71
·! 0:00:00.943511 SYS: New timer resolution: 495 us (old=997 us, min=15625 us, max=500 us)
·! 0:00:01.808771 NET: Download finished
·S 0:00:01.808949 UPDATER: RPCS3 is up to date!
·! 0:00:04.142651 cubeb_dev_enum: Found device: id={0.0.0.00000000}.{064b595c-176d-481b-aef8-10b2f3044581}, name=Głośniki (2 — High Definition Audio Device), max_ch=2
·! 0:00:04.142667 cubeb_dev_enum: Found device: id={0.0.0.00000000}.{0b8ed812-6368-4502-bf1c-2de32bdbf865}, name=SteelSeries Sonar - Stream (SteelSeries Sonar Virtual Audio Device), max_ch=2
·! 0:00:04.142670 cubeb_dev_enum: Found device: id={0.0.0.00000000}.{0c675854-a8d8-4d9e-b885-9ddaa85bc2cd}, name=SteelSeries Sonar - Media (SteelSeries Sonar Virtual Audio Device), max_ch=8
·! 0:00:04.142672 cubeb_dev_enum: Found device: id={0.0.0.00000000}.{2a681931-7785-41d9-b2ae-1500283a1e58}, name=SteelSeries Sonar - Gaming (SteelSeries Sonar Virtual Audio Device), max_ch=8
·! 0:00:04.142673 cubeb_dev_enum: Found device: id={0.0.0.00000000}.{51f12160-2bc9-4682-b03e-5c8ae3bd1839}, name=SteelSeries Sonar - Aux (SteelSeries Sonar Virtual Audio Device), max_ch=8
·! 0:00:04.142675 cubeb_dev_enum: Found device: id={0.0.0.00000000}.{c10700a8-0750-4638-815a-454407fd1dc3}, name=SteelSeries Sonar - Microphone (SteelSeries Sonar Virtual Audio Device), max_ch=2
·! 0:00:04.142679 cubeb_dev_enum: Found device: id={0.0.0.00000000}.{f9205905-e62d-4e90-8e78-4819dc5f8d13}, name=SteelSeries Sonar - Chat (SteelSeries Sonar Virtual Audio Device), max_ch=2
·! 0:00:04.142680 cubeb_dev_enum: Found device: id={0.0.0.00000000}.{fc38ef85-790c-442c-b0fc-dfe308bcc020}, name=Słuchawki (2 — High Definition Audio Device), max_ch=2
·S 0:00:20.265193 SYS: Disabling logging! Do not create issues on GitHub or on the forums while logging is disabled.
·A 0:00:26.908361 RSX: Found vulkan-compatible GPU: 'Intel(R) UHD Graphics 620' running on driver 0.402.537

**Comment by mikoprimebusiek** [comment]
Why it is invalid

**Comment by AniLeo** [comment]
Because the issue template was completely ignored, besides that you're using Intel iGPU which we don't officially support
