### ISSUE TITLE
No Update: Tekken Dark Resurrection

### ISSUE THREAD

**Issue by JohnBillington** [RPCS3/rpcs3#13611]
### Quick summary

There is no update shown as available for Tekken Dark Resurrection, and rusty psn also comes up blank. However, there was an update for this game on PS3. It added rumble support and the pickup match mode. 

https://www.engadget.com/2008-04-17-tekken-5-dark-resurrection-patch-adds-rumble-pickup-match-mode.html

Left scratching my head

### Details

NA

### Attach a log file

NA

### Attach capture files for visual issues

NA

### System configuration

NA

### Other details

NA

**Comment by YuriNator557** [comment]
This is not an RPCS3 problem, nor is it a problem with rusty-psn, there just isn't an update on Sony's servers for it

**Comment by JohnBillington** [comment]
If it’s not on Sony’s servers, where do I obtain this update?

**Comment by Megamouse** [comment]
We can only show what's available in the database
