### ISSUE TITLE
Puss in Boots [BLUS30731]

### ISSUE THREAD

**Issue by Kurosaki77** [RPCS3/rpcs3#13616]
### Quick summary

after 5 to 10 minutes of gameplay , the game crashes along with the emulator itself

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/11166512/RPCS3.zip)

the file was over the 25 MB limit so I had to compress it in a zip

### System configuration

OS : Windows 10
CPU : AMD Ryzen 7 2700X
GPU : AMD Radeon RX 6800 XT
GPU Driver Version : AMD Software : Adrenalin Edition v23.3.1

**Comment by Asinin3** [comment]
No fatal error in log or steps to reproduce. Game is also listed as ingame. I don think this is helpful for developers... closing.
Also, review this:
![image](https://user-images.githubusercontent.com/15137035/232202398-91a596d8-5374-46d3-abf3-39802d74f313.png)
