### ISSUE TITLE
[BLES00142] The Simpsons Game - Certain Textures are black.

### ISSUE THREAD

**Issue by boofiboi** [RPCS3/rpcs3#13626]
### Quick summary

Some textures in The Simpsons Game are black, where they should normally have a texture.

### Details

This problem also occured in the start with the bottle caps being black, the cake being black.

Here you can see the floor of the house where you spawn after the first level is textured with a carpet, not on RPCS3.
Same happens outside of the house in Springfield.

Real PS3:
https://youtu.be/knWP4HCAys8?t=429
RPCS3:
https://cdn.horizon.pics/JWz34Xl1Wm.mp4

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11181151/RPCS3.log.gz)

### Attach capture files for visual issues

[BLES00142_20230407211448_capture.zip](https://github.com/RPCS3/rpcs3/files/11180969/BLES00142_20230407211448_capture.zip)

### System configuration

[CPU] Ryzen 5 1600
[GPU] RX 5500XT
[GPU DRIVERS] Latest adrenalin drivers

**Comment by boofiboi** [comment]
Small update:
The textures do appear at a distance, but upon coming closer they turn black.

**Comment by MarioSonic2987** [comment]
I can't reproduce this bug with a GTX 1060 (531.41). Default settings are used.
![image](https://user-images.githubusercontent.com/20027681/230672037-087df069-5fd0-4f72-9324-965a2b18571d.png)
![image](https://user-images.githubusercontent.com/20027681/230672346-270ced6a-6f3c-4cfb-820c-aa5eb2ba4d2a.png)

**Comment by Jonathan44062** [comment]
@boofiboi that issue is fixed by Shader Quality to Low in GPU Tab, it's a AMD issue exclusive, it doesn't happen with NVIDIA GPU's
![image](https://user-images.githubusercontent.com/78843189/230672632-52ca91f9-c51c-4a96-984c-c3e6d77fba02.png)

**Comment by boofiboi** [comment]
Yeah that was it.
