### ISSUE TITLE
SONIC UNLEASHED [BLUS30244]

### ISSUE THREAD

**Issue by Kurosaki77** [RPCS3/rpcs3#13624]
### Quick summary

game freezes a few moments after the 1st cinematic . according to the log , its because of this error :

F {RSX Offloader} VM: Access violation reading location 0x6faf53d0 (unmapped memory)
F {RSX [0x008fb38]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\VKVertexBuffers.cpp:335[:4], in function upload_vertex_data) (error=0x57)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11178321/RPCS3.log)

### System configuration

OS : Windows 10
CPU : AMD Ryzen 7 2700X
GPU : AMD Radeon RX 6800 XT
GPU Driver Version : AMD Software Adrenalin Edition v23.3.1

**Comment by Jonathan44062** [comment]
Your settings are weird, reset them to default, see the image 
![image](https://user-images.githubusercontent.com/78843189/230660180-968803d7-9cdf-46ae-b457-dcf79b20abf2.png)
Once you done, only apply the correct settings from the wiki
https://wiki.rpcs3.net/index.php?title=Sonic_Unleashed
Also, don't open tickets just for help, if you really need help, go to the rpcs3 discord server, not here
