### ISSUE TITLE
Formula 1 Championship Edition black screen in RPCS3

### ISSUE THREAD

**Issue by brGren** [RPCS3/rpcs3#13639]
### Quick summary

The game Formula 1 Championship Edition crashes and stays on a black screen when I start it and I have to close it because it won't let me do anything
![Captura de pantalla (25)](https://user-images.githubusercontent.com/130370980/230939588-6a095475-3843-4e6e-99b1-fa5aaa562c2a.png)
![Captura de pantalla (26)](https://user-images.githubusercontent.com/130370980/230939592-c2ea7b97-8cb0-4de5-bbaf-d35f514e998a.png)
![Captura de pantalla (27)](https://user-images.githubusercontent.com/130370980/230939599-15905784-8311-4e18-8791-0607f7436995.png)

### Details

The game Formula 1 Championship Edition crashes and stays on a black screen when I start it and I have to close it because it won't let me do anything. I have the latest version of the emulator possible.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11191809/RPCS3.log.gz)

### System configuration

![Captura de pantalla (28)](https://user-images.githubusercontent.com/130370980/230940302-c774fb78-d3bd-4fcf-ad15-ddb5441c0702.png)
![Captura de pantalla (29)](https://user-images.githubusercontent.com/130370980/230940306-07e7affd-70e7-4343-8766-e59e0a04234b.png)
![Captura de pantalla (30)](https://user-images.githubusercontent.com/130370980/230940337-f148b4b5-ae15-44af-bd92-1128a332ffc3.png)
![Captura de pantalla (31)](https://user-images.githubusercontent.com/130370980/230940340-66b76008-00fe-4e0a-8085-4b750900cd56.png)
![Captura de pantalla (32)](https://user-images.githubusercontent.com/130370980/230940342-d79f79b6-e844-4a74-98a6-f0822c3d6691.png)
![Captura de pantalla (33)](https://user-images.githubusercontent.com/130370980/230940344-d70b82ee-d2e3-4a0f-a9f3-b70c56e73e29.png)
![Captura de pantalla (34)](https://user-images.githubusercontent.com/130370980/230940364-a0cb69a2-af0f-487d-bc0e-f7333c946abd.png)
![Captura de pantalla (35)](https://user-images.githubusercontent.com/130370980/230940368-b6061465-0df6-4fb0-b554-23e72156ac79.png)
![Captura de pantalla (36)](https://user-images.githubusercontent.com/130370980/230940370-df814840-07ba-47d4-ae0f-09bc67dfb308.png)

### Other details

I looked for the f1 Championship Edition game on the emulator's website in the compatibility section and I have already put the game configuration that is recommended to put so that the game does not have visual errors or anything.
![Captura de pantalla (37)](https://user-images.githubusercontent.com/130370980/230941637-9c7f3afc-a44e-44e7-b481-1ac019b6bcd1.png)
![Captura de pantalla (38)](https://user-images.githubusercontent.com/130370980/230941647-7999ccc6-7786-4d60-be27-d309e71999a1.png)

**Comment by YuriNator557** [comment]
You are running a repackaged ISO which is not supported by RPCS3

**Comment by brGren** [comment]
How do you know that it is not compatible, and how can I solve it? The file is in pkg format and the other games are too, and the other games do work.
