### ISSUE TITLE
[Regression] [BLUS30463] Rock Band 3 crashes during the into splash screens.

### ISSUE THREAD

**Issue by DarkRTA** [RPCS3/rpcs3#13635]
### Quick summary

The update to LLVM 16 has broken Rock Band 3 as the game now no longer boots from a fresh PPU cache.

Using a stale PPU cache from LLVM 15 does allow the game to boot although practice mode will now softlock instead of working correctly.

### Build with regression

fb88e1c1c933a792f96600206ed03a07cd7c3661

### Attach two log files

[RPCS3.log from working build](https://github.com/RPCS3/rpcs3/files/11186332/RPCS3.log)
[RPCS3.log from broken build](https://github.com/RPCS3/rpcs3/files/11186335/RPCS3.log)

### System configuration

OS: Arch Linux
Kernel: 6.2.7
CPU: AMD Ryzen 5 3600 @ 3.6GHz
GPU: AMD Radeon RX 5600 XT
Memory: 16GB

**Comment by DarkRTA** [comment]
Starting from a fresh firmware cache allows the game to boot farther into the splash screens, but the game now softlocks during one of the intro videos.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11186389/RPCS3.log)

**Comment by Nekotekina** [comment]
Could be Linux-specific? Need confirmation.

**Comment by qfoxb** [comment]
> Could be Linux-specific? Need confirmation.

Can confirm crash happens on windows

**Comment by qfoxb** [comment]
#13651 fixes this issue, at least on windows

**Comment by Asinin3** [comment]
Closing as should be fixed on latest master 14872 according to above comment. Ask for re-open if there's any issues still.
