### ISSUE TITLE
RecompilationEngine is freed before all PPU Thread

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1364]
I think I found why PPU LLVM crashes at exit, it looks like RecompilationEngine (which stores all the ExecutionEngine and frees virtual memory at destruction) is destroyed before the other PPU Thread that relies on it.
If I store the ExecutionEngine in a static variable and comment out the virtual mem free operation it doesn't crash anymore when closing rpcs3.

**Comment by tambry** [comment]
@vlj Are you planning to fix this?

**Comment by vlj** [comment]
I don't know how to do, it's done at thread management level code in rpcs3.

**Comment by raven02** [comment]
This LLVM is no longer valid in latest build
