### ISSUE TITLE
[Regression] Latest AppImage causes RPCS3 to crash with "CommandLine Error: Option 'use-dbg-addr' registered more than once!"

### ISSUE THREAD

**Issue by EeveeEuphoria** [RPCS3/rpcs3#13641]
### Quick summary

The latest version of RPCS3 (at this time, commit 6fbca1ac) crashes on start-up with the following:
```
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
Debugger: 0
Failed to set RLIMIT_MEMLOCK size to 2 GiB. Try to update your system configuration.
: CommandLine Error: Option 'use-dbg-addr' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

### Details

This is in contrast to the last version of RPCS3 I've been using (0.0.27-14845-7081b89e) which has worked just fine, and did not crash like this. Of note `Failed to set RLIMIT_MEMLOCK size to 2 GiB. Try to update your system configuration.` also occurs on this old version, I tried to fix it using help from a different issue but it didn't do anything, since the file `/etc/security/limits.conf` didn't exist at all on my system, either way irrelevant to this issue I think.

From what I can gather this is a compiler issue, so this must affect more than just my system. I've also seen a different report (#13638) saying the latest LLVM has caused a regression in performance on Windows, not sure if this is related.

### Build with regression

v0.0.27-14854-6fbca1ac

### Attach two log files

[RPCS3.log for v0.0.27-14854-6fbca1ac, crash](https://github.com/RPCS3/rpcs3/files/11197996/RPCS3.log)
[RPCS3.log for v0.0.27-14845-7081b89e, successful load](https://github.com/RPCS3/rpcs3/files/11198070/RPCS3.log)

### System configuration

OS: openSUSE Tumbleweed (v. 20230407)
CPU: AMD Ryzen 5 5600G
GPU: AMD ATI Radeon RX 6600 XT
DE: Plasma 5.27.4 (xorg)
Mesa Version: 23.0.1

**Comment by EeveeEuphoria** [comment]
Went and did a test real quick, and literally the build made after the one I currently have (the build being 0.0.27-14846) is the one that crashes, being the #13534 LLVM 16 commit. That one exhibits the same issues as the latest version.

**Comment by thesourcehim** [comment]
I can add that for me this started to happen when I ugraded from Fedora 37 to 38. Llvm was upgraded to 16 during this process so I think it's related.

**Comment by AtlasSkyholder** [comment]
I just wanted to give my 2 cents, I started experiencing this about 2 weeks ago, more or less.

I don't have the same versions as @EeveeEuphoria , but, everything was working well in v0.0.27-14843, then it stopped working when I upgraded to v0.0.27-14863, and subsquently.

Versions I have in my Downloads directory:
v0.0.27-14843 - working
v0.0.27-14863 - crashes
v0.0.27-14887 - crashes
v0.0.27-14891 - crashes
v0.0.27-14893 - crashes
v0.0.27-14904 - crashes

This is what I get when I try to start it through CLI:

[crossfader@fedora RPCS3]$ ./rpcs3-v0.0.27-14904-2c71d08e_linux64.AppImage
Debugger: 0
Failed to set RLIMIT_MEMLOCK size to 2 GiB. Try to update your system configuration.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
: CommandLine Error: Option 'use-dbg-addr' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)

@thesourcehim I am also using Fedora 38, actually I have been using the beta for the past 3 weeks or so, updated to the 38 recently. I just built a new PC so I was distro hopping, trying to find something I liked and supported the new hardware, landed in Fedora 38 KDE Plasma and am pretty happy here.

System Configuration:

Fedora 38 , Linux Kernel 6.2.11-300 , Mesa 23.0.2
CPU: AMD 7950X3D
GPU: MSI AMD RX 7900XTX
RAM: 64 Gb 6000Mhz Corsair
Motherboard: Gigabyte X670E Xtreme

**Comment by EeveeEuphoria** [comment]
Yeah, that lines up to when the LLVM 16 commit was done, 14863 is a lot after the commit, so I think that commit is to blame. I went ahead and tested the latest version as of writing (v0.0.27-14919-6bf77166) and that still crashes.

**Comment by thesourcehim** [comment]
Searching through internet points to possible bug in spirv-llvm-translator. Current release version is 16.0.0, but issue was fixed in later commits, so maybe rpcs3 should rebase.

Discussion: https://foldingforum.org/viewtopic.php?t=39359

**Comment by hcorion** [comment]
Please test with the AppImage artifact from this PR https://github.com/RPCS3/rpcs3/pull/13786 and see if it fixes your issues.

**Comment by EeveeEuphoria** [comment]
Using the GCC build, I can confirm RPCS3 can launch... but it doesn't work with the Vulkan renderer, for some reason. I double-checked and used the build I reported last worked, and that still functions. Unsure if this has anything to do with the LLVM16 stuff, I'll provide logs anyways (despite saying "Boot successful", no window shows up):

```
- SYS: RPCS3 v0.0.27-14947-621dcd8e Alpha | HEAD
- SYS: AMD Ryzen 5 5600G with Radeon Graphics | 12 Threads | 23.33 GiB RAM | TSC: 3.893GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 6.2.10-1-default, Version: #1 SMP PREEMPT_DYNAMIC Thu Apr 6 10:36:55 UTC 2023 (ba7816e)
- SYS: Current Time: 2023-04-29T17:57:34
- RSX: Found vulkan-compatible GPU: 'AMD Radeon RX 6600 XT (RADV NAVI23)' running on driver 23.0.2
- SYS: Firmware version: 4.90
S PPU: Enabled: Non-Java Mode Fixup
E RSX: Could not find a supported Vulkan surface extension
F RSX: Could not find a vulkan compatible GPU driver. Your GPU(s) may not support Vulkan, or you need to install the vulkan runtime and drivers
F {RSX [0x0000000]} SIG: Thread terminated due to fatal error: No vulkan device was created
(in file ../rpcs3/Emu/RSX/VK/VKGSRender.cpp:1396, in function on_init_thread)
S Input: The pad mode was changed to Single-threaded
S Input: Evdev device 0 connected
S GUI: Boot successful.
```

**Comment by hcorion** [comment]
Are you using X11 or Wayland?

**Comment by EeveeEuphoria** [comment]
Currently using X11, I'll try it on Wayland in just a bit.

**Comment by EeveeEuphoria** [comment]
Tested on Wayland, and I get the exact same issue, though for some reason a window does appear, it just doesn't render anything.

**Comment by hcorion** [comment]
Can you run `strace` on the AppImage and pipe the output into a file, and upload the output here?

**Comment by EeveeEuphoria** [comment]
For some reason I'm unable to pipe the output, whenever I try I just get `Debugger: 0` in the text file.
I've instead used the strace output function, hopefully that'll still work.
[funny_moment.txt](https://github.com/RPCS3/rpcs3/files/11360186/funny_moment.txt)

**Comment by hcorion** [comment]
Ah that's fine. Hmm, did you start the Vulkan renderer with this log, or just booted the GUI?

**Comment by EeveeEuphoria** [comment]
I did start the vulkan renderer, and then when it failed to show anything, I closed it out right after.

**Comment by EeveeEuphoria** [comment]
Ah, running strace with appimages seems to... not work? I tried running strace without outputting, and it stops hammering the console the moment it outputs `Debugger: 0`,. So, that's not fun.

**Comment by hcorion** [comment]
Try extracting the appimage.
Go `./RPCS3*.AppImage --appimage-extract`
And then run `strace ./squashfs-root/AppRun`

**Comment by EeveeEuphoria** [comment]
Alright, so, for some weird reason this now crashes when I try to run Vulkan, but now there's mentions of vulkan within the text file itself, so hopefully this will work better?
[glooper.txt](https://github.com/RPCS3/rpcs3/files/11360208/glooper.txt)

**Comment by hcorion** [comment]
The vulkan issue is fixed by https://github.com/RPCS3/rpcs3/pull/13789
Should all be working!

**Comment by EeveeEuphoria** [comment]
Tested it myself, it all seems to check out!
