### ISSUE TITLE
Visual bugs using version 5.15.8 of Qt5

### ISSUE THREAD

**Issue by n00d13p00d13** [RPCS3/rpcs3#13647]
### Quick summary

Visual bugs using version 5.15.8 of Qt5

### Details

I'm currently running archlinux and I've tried both the appimage and the package from the AUR but both present the same issue.
Is there any solution i could try until the new release addresses the issue or gets compiled with the new version?

Here's a preview:
![image](https://user-images.githubusercontent.com/42703601/231329223-7e5dccba-acaf-44f1-bc09-0d3e65fcbd87.png)
![image](https://user-images.githubusercontent.com/42703601/231329343-331071f1-21b8-47f0-b781-00ca772782ef.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11206377/RPCS3.log)

**Comment by Megamouse** [comment]
I'm sorry but this is clearly an issue with your system.
You can try one of the command line options
