### ISSUE TITLE
Segfault on GUI: Boot failed: reason: Firmware is missing

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#13642]
### Quick summary

When testing functionality of QT dialogs I observed this issue and have observed it for a couple months.

### Details

When you close, select locate PS3UPDAT.PUP, or select cancel on this [see picture] dialog

![image](https://user-images.githubusercontent.com/60384196/231197510-2e31ed05-9708-40d0-8236-56c60b093611.png)

A fatal error occurs with this information

![image](https://user-images.githubusercontent.com/60384196/231197883-ad8d9f58-b637-40b4-a96c-b85f5edb5483.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11201666/RPCS3.log)

### Attach capture files for visual issues

N/A

### System configuration

Ryzen 5 3600
GTX 1660 S
Windows 11 22624.1546

### Other details

What is intended to occur is allowing the user to locate their firmware or ignore the message and use HLE instead without crashing RPCS3.

**Comment by Megamouse** [comment]
I can't reproduce this.
It's working as intended

**Comment by Darkhost1999** [comment]
With my environment variables I can make the error not occur by adding QT to path.
But can still reproduce by removing QT from path.

**Comment by Megamouse** [comment]
sounds like a problem with your system then

**Comment by Darkhost1999** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11614100/RPCS3.log)
Seems to be working. It's odd cause I have been able to create the segfault for almost a whole year.
Tried removing QT from path as I mentioned and everything was in order.
