### ISSUE TITLE
[Regression] Metal Gear Solid 4 [NPUB31633] freezes after PPU/SPU compilation since 0.0.27-14855 (LLVM16.01)

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#13653]
### Quick summary

**Issue Update:-** 

After 0.0.27-14872 #13651 got merged to master, game boots up fine the first time around after fresh PPU module compilation, but continues to freeze with a black screen after PPU/SPU compilation on subsequent boots. 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11230960/RPCS3.log)

**Original issue report:-**

Issue as per title.

![14855 not okay](https://user-images.githubusercontent.com/4345150/231749069-6241998b-9376-4ac4-9ab3-5f0978ae0311.PNG)

Last working build is **0.0.27-14854.**

![14854 okay](https://user-images.githubusercontent.com/4345150/231748921-d9138d82-a441-4280-9476-a555f78fc154.PNG)

### Details

**Reproduction steps:-**

1. Boot MGS4 on any build from 0.0.27-14855 onwards.
2. After PPU/SPU compilation, game will freeze. 
3. After freezing, closing the game will cause rpcs3 to crash with a thread deadlocked error. 

![14855 not okay2](https://user-images.githubusercontent.com/4345150/231749373-568a99c7-5987-4e6c-a2e5-3dfb1bf3237b.PNG)

### Build with regression

v0.0.27-14855-06b0e35f

### Attach two log files

Not working (14855)
[RPCS3 14855.log](https://github.com/RPCS3/rpcs3/files/11221786/RPCS3.14855.log)
 
Working (14854)
[RPCS3 14854.log.gz](https://github.com/RPCS3/rpcs3/files/11221788/RPCS3.14854.log.gz)

### System configuration

SYS: RPCS3 v0.0.27-14855-06b0e35f Alpha | master
SYS: 12th Gen Intel(R) Core(TM) i7-12700KF | 20 Threads | 31.86 GiB RAM | TSC: 3.610GHz | AVX+ | FMA3
SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2080 Ti' running on driver 527.56.0.0
SYS: Firmware version: 4.88

**Comment by Asinin3** [comment]
These are probably all caused by the same issue, do we really need to seperate it out into different issues for every game?

**Comment by ssharm02** [comment]
I am also getting the same issue started today once the emulator was updated (infamous is working fine)

**Comment by Nekotekina** [comment]
Try #13651 (clear PPU Cache)

**Comment by ssharm02** [comment]
Still crashing! ^ Tried the suggestion mentioned above

**Comment by Jmete** [comment]
> Try #13651 (clear PPU Cache)

I've tried clearing all caches, but doesn't seem to fix it. Doing so will allow it to boot, but it still crashes when trying to start a new game, and then subsequent boots it will just be a black screen again.

**Comment by solarmystic** [comment]
> > Try #13651 (clear PPU Cache)
> 
> I've tried clearing all caches, but doesn't seem to fix it. Doing so will allow it to boot, but it still crashes when trying to start a new game, and then subsequent boots it will just be a black screen again.

Which is what i've noted in my update to this issue report. Only the first time works, subsequent boots fail.

**Comment by Asinin3** [comment]
Test https://github.com/RPCS3/rpcs3/pull/13670

**Comment by solarmystic** [comment]
Fixed by #13670 confirmed, game does not freeze after subsequent boots after compiling PPU/SPU cache since the PR got merged to master with 0.0.27-14876. Closing.

![image](https://user-images.githubusercontent.com/4345150/232210222-9642f1a7-98a9-422b-b29e-0aed324b7bbb.png)
