### ISSUE TITLE
[Regression] LUMINES Supernova [NPEB00066] freezes after PPU cache build since 14863 (LLVM16)

### ISSUE THREAD

**Issue by Levine91** [RPCS3/rpcs3#13658]
### Quick summary

See title

### Details

Game was working perfectly until 14846 when LLVM16 was introduced.
Now it'll load the PPU cache and just freeze on a black screen.
Clearing the PPU cache and rebuilding results in the same issue.

Verified it runs perfectly in build 14845
Not working when testing latest build as well, 14870. Same issue occurs.

Build 14845 (Game works) - [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11227149/RPCS3.log.gz)
Build 14846 (Game does NOT work) - [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11227156/RPCS3.log.gz)
Build 14870 (Game does NOT work) - [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11227173/RPCS3.log.gz)

### Build with regression

v0.0.27-14846-fb88e1c1

### Attach two log files

Build 14845 (Game works) - [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11227149/RPCS3.log.gz)
Build 14846 (Game does NOT work) - [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11227156/RPCS3.log.gz)

### System configuration

CPU - Intel i9-10850K @ 3.60GHz
GPU - GeForce RTX 3080 12GB
GPU Drive - 531.61

**Comment by solarmystic** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/13651 and see whether that PR fixes it.
https://api.cirrus-ci.com/v1/artifact/task/5115896859983872/Artifact/rpcs3-v0.0.27-4188c52b_win64.7z

**Comment by Levine91** [comment]
> Test with #13651 and see whether that PR fixes it. https://api.cirrus-ci.com/v1/artifact/task/5115896859983872/Artifact/rpcs3-v0.0.27-4188c52b_win64.7z

Yup, this fixes the issue for both it and Tornado Outbreak.
