### ISSUE TITLE
[Regression] Castlevania: Harmony of Despair [NPUB30505] no audio on load after cache build, freeze on subsequent loads (LLVM) since 14863

### ISSUE THREAD

**Issue by Azure-Fang** [RPCS3/rpcs3#13655]
### Quick summary

Per title.

### Details

Since 14863, after rebuilding the PPU cache using LLVM for SPU, the game boots with no audio. Rebooting the game, however, leads to the game freezing before reaching the developer splash screen. Rebuilding the cache at boot allows access again (without audio), but again only for that single boot.

Still active in 14869.

**Reproduction**
1. Clear all caches for NPUB30505.
2. Launch the game with 14863 LLVM and allow caches to rebuild.
3. Game will launch to main menu with no sound.
4. Close game.
5. Relaunch and game will now freeze before reaching the first splash screen on this and all subsequent attempts until caches are cleared again.

**Workaround**
Switching to ASMJIT allows the game to launch and run normally with full audio.

### Build with regression

v0.0.27-14863-7bce99d7

### Attach two log files

[RPCS3 (no audio and freeze).log](https://github.com/RPCS3/rpcs3/files/11225829/RPCS3.no.audio.and.freeze.log)
[RPCS3 (working).log](https://github.com/RPCS3/rpcs3/files/11225854/RPCS3.working.log)

### System configuration

CPU: i7 4790K @4GHz
GPU: Geforce GTX 1060 6GB
GPU Driver: 531.29

**Comment by solarmystic** [comment]
What was the last build that worked properly for this game?

I'm assuming it's the one before the LLVM16 commit but please test that (14845), the one right after (14846) and include it in your issue report. 

0.0.27-14863 is not the one that introduced LLVM16 so is not the responsible one.

**Comment by Azure-Fang** [comment]
My apologies. I wasn't entirely sure which version I was on last night and was in a rush to get the initial report in.

14846 - Working [RPCS3 14846.log](https://github.com/RPCS3/rpcs3/files/11225984/RPCS3.14846.log)
14854 - Working [RPCS3 14854.log](https://github.com/RPCS3/rpcs3/files/11225998/RPCS3.14854.log)
14855 - Failing [RPCS3 14855.log](https://github.com/RPCS3/rpcs3/files/11226005/RPCS3.14855.log)

**Comment by solarmystic** [comment]
Thanks, so LLVM16.01 is confirmed to be the responsible one.

**Comment by Azure-Fang** [comment]
Test with old cache failed. [RPCS3.log](https://github.com/RPCS3/rpcs3/files/11226040/RPCS3.log)
Will rebuild and try again if needed.

**Comment by solarmystic** [comment]
Yes please, do rebuild all caches when testing that PR build.

**Comment by Azure-Fang** [comment]
Cleared, rebooted, rebuilt. Failed. [RPCS3.log](https://github.com/RPCS3/rpcs3/files/11226087/RPCS3.log)

**Comment by Asinin3** [comment]
Retest on latest master 14872 or later.

**Comment by Nekotekina** [comment]
Try #13659

**Comment by Azure-Fang** [comment]
> Retest on latest master 14872 or later.

Tested on 14874 and working. [RPCS3.log](https://github.com/RPCS3/rpcs3/files/11237594/RPCS3.log)
