### ISSUE TITLE
fatal error  RPCS3

### ISSUE THREAD

**Issue by JuanjoSevilla3** [RPCS3/rpcs3#13667]
### Quick summary

Good morning, I downloaded the RPCS3 emulator but it gives me a fatal error and I don't know how to fix it

### Details

The module msvcp140.dll was incorrectly installed at 'C:\Juan José\Desktop\rpcs3-v0.0.27-14874-98fc073f_win64\MSVCP140.dll'

This module is part of the Microsoft Visual C++ 2015-2019 Redistributable package. Install this package, then delete msvcp140.dll from rpcs3's installation directory.

You can install this package from URL:
https://aka.ms/vs/16/relase/VC redist.x64.exe

### Attach a log file

I don't have when I get the fatal error no log appears

### Attach capture files for visual issues

![RPCS3_ Fatal Error 15_04_2023 8_51_22](https://user-images.githubusercontent.com/130823254/232193598-639f1b82-13cd-4bd1-9e2e-883717783dda.png)

### System configuration

[DxDiag.txt](https://github.com/RPCS3/rpcs3/files/11238643/DxDiag.txt)

### Other details

and I don't know what to do since I have the complete package with all the microsoft visual c++ a pity :(

**Comment by JuanjoSevilla3** [comment]
sorry I was wrong this is the link :D https://aka.ms/vs/16/release/VC_redist.x64.exe

**Comment by Megamouse** [comment]
The message tells you what to do...

**Comment by JuanjoSevilla3** [comment]
> El mensaje te dice qué hacer...

I did what it says but it still gives a fatal error when opening rpcs3

**Comment by Asinin3** [comment]
Ask for help in our discord or Reddit. This is a problem on your end, no one else is reporting this.

**Comment by JuanjoSevilla3** [comment]
> Pide ayuda en nuestro discord o Reddit. Este es un problema de su parte, nadie más lo está informando.

OK thank you
