### ISSUE TITLE
[Regression] Nier replicant not working rpcs3-v0.0.27-14873-ba29f0cc_win64

### ISSUE THREAD

**Issue by muesqtk** [RPCS3/rpcs3#13668]
### Quick summary

After updating the build, disk games stopped working for some reason, except for those installed directly on the virtual disk.
It turns out, the screensaver passes, and an error falls out. After closing the game, the emulator crashes

### Build with regression

rpcs3-v0.0.27-14873-ba29f0cc_win64

### Attach two log files

https://cdn.discordapp.com/attachments/871006414091468831/1096500760142946334/RPCS3.log

### Attach capture files for visual issues

https://drive.google.com/file/d/1K0JGhRqHg9Md3lcESlWjB8q1eNEhC3rV/view?usp=sharing

### System configuration

CPU: i7-3770
GPU: RX6600
RAM: 16GB DDR3 1333Mhz

**Comment by Asinin3** [comment]
Please confirm which build caused the problem exactly. You only showed one log, and the build you listed as having a regression seems doubtful its the exact cause.

Try this build: https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-6fbca1acfd5ee7da782f93995cff99dd09cfe48d/rpcs3-v0.0.27-14854-6fbca1ac_win64.7z if its still broken try: https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-7081b89e976ad7f931c926022bd93ddd9778347c/rpcs3-v0.0.27-14845-7081b89e_win64.7z 

And let us know which one if any, fixed the problem.

**Comment by muesqtk** [comment]
Yes, on 14854 the game starts

Video: https://drive.google.com/file/d/1gTWm_manCXB20ezbJuBMdtDRvBir_DGk/view?usp=sharing
Log: https://drive.google.com/file/d/1_KPiPPRedYjY1cTYMUqm1GW_TdLi8oRt/view?usp=sharing

**Comment by Asinin3** [comment]
Try latest master, 14876 or later should fix it.

**Comment by 19manu91** [comment]
Hello, I confirm the same for MGS4

**Comment by Asinin3** [comment]
> Hello, I confirm the same for MGS4

This issue is for NieR, not MGS4... and MGS4 was already confirmed fixed.

**Comment by muesqtk** [comment]
Alas, I saw the current comments today. The new build began to launch Nier, and also a hack versus.
