### ISSUE TITLE
Linking problem on Ubuntu 15.10

### ISSUE THREAD

**Issue by piotr-szegda** [RPCS3/rpcs3#1367]
I am trying to build on Ubuntu 15.10. I have installed LLVM 3.6, 3.7 and 3.8. When I build without any parameters by default, it is used LLVM 3.7.

```
pszegda@pszegda-desktop:~/Apps/rpcs3$ cmake CMakeLists.txt
-- No build type selected, default to Release

== ====================================================
== [AsmJit Include|Static]
== ====================================================

-- Initializing ASMJIT_DIR=/home/pszegda/Apps/rpcs3/asmjit
-- Using GCC
-- cotire 1.7.3 loaded.
-- Initializing RPCS3_SRC_DIR=/home/pszegda/Apps/rpcs3/rpcs3
LLVM 3.7.0 is not supported! LLVM 3.6 is required. RPCS3 will be compiled without LLVM support.
-- dir='/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0'
-- dir='/usr/include/wx-3.0'
-- dir='/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0'
-- dir='/usr/include/wx-3.0'
-- dir='/usr/include/AL'
-- dir='/usr/lib/llvm-3.7/include'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/../ffmpeg/linux/x86_64/include'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/Loader'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/Crypto'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/..'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/../asmjit/src/asmjit'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/../glm'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/../rsx_program_decompiler/shader_code'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pszegda/Apps/rpcs3
```

So I try to specify 3.6 dir.

```
pszegda@pszegda-desktop:~/Apps/rpcs3$ cmake CMakeLists.txt -DLLVM_DIR=/usr/share/llvm-3.6/cmake
-- No build type selected, default to Release

== ====================================================
== [AsmJit Include|Static]
== ====================================================

-- Initializing ASMJIT_DIR=/home/pszegda/Apps/rpcs3/asmjit
-- Using GCC
-- cotire 1.7.3 loaded.
-- Initializing RPCS3_SRC_DIR=/home/pszegda/Apps/rpcs3/rpcs3
-- dir='/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0'
-- dir='/usr/include/wx-3.0'
-- dir='/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0'
-- dir='/usr/include/wx-3.0'
-- dir='/usr/include/AL'
-- dir='/usr/lib/llvm-3.6/include'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/../ffmpeg/linux/x86_64/include'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/Loader'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/Crypto'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/..'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/../asmjit/src/asmjit'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/../glm'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler'
-- dir='/home/pszegda/Apps/rpcs3/rpcs3/../rsx_program_decompiler/shader_code'
-- CXX target rpcs3 cotired excluding /home/pszegda/Apps/rpcs3/rpcs3/Emu/Cell/PPULLVMRecompiler.cpp.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pszegda/Apps/rpcs3
```

Compilation goes without problems, but when run whatever rpcs3 crash. Log from gdb.

```
Reading symbols from rpcs3...done.
(gdb) run
Starting program: /home/pszegda/Apps/rpcs3/bin/rpcs3 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
vm::g_base_addr = 0x7ffeec37d000
vm::g_priv_addr = 0x7ffdec37d000
[Log:Warning] fs::file::open('/home/pszegda/.config/rpcs3/rpcs3.new.ini', 0x1) failed: error 0x2
[New Thread 0x7ffdea553700 (LWP 8214)]
[New Thread 0x7ffde9d52700 (LWP 8215)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffbe153c0a7 in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1
```

I'm doing something wrong or is a linker error?

**Comment by tambry** [comment]
@piotr-szegda Not an expert on Linux, but it would seem, that it tries to use LLVM 3.8?
´´´´0x00007ffbe153c0a7 in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1

**Comment by piotr-szegda** [comment]
Yes you right but I don't know why. I'm sure I typed "cmake CMakeLists.txt -DLLVM_DIR=/usr/share/llvm-3.6/cmake". It seems that version 3.6 is compiled but linked is 3.8.

**Comment by hakusdream** [comment]
Run `ldd` on the generated executable, and post the output, @piotr-szegda.

**Comment by piotr-szegda** [comment]
linux-vdso.so.1 =>  (0x00007ffe472fa000)                                                                                                                            
        libwx_gtk2u_core-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0 (0x00007f8619e18000)                                                                      
        libwx_baseu-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 (0x00007f8619980000)                                                                                
        libwx_gtk2u_aui-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libwx_gtk2u_aui-3.0.so.0 (0x00007f86196e0000)                                                                        
        libwx_gtk2u_gl-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libwx_gtk2u_gl-3.0.so.0 (0x00007f86194c8000)                                                                          
        libwx_baseu_xml-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libwx_baseu_xml-3.0.so.0 (0x00007f86192b8000)                                                                        
        libopenal.so.1 => /usr/lib/x86_64-linux-gnu/libopenal.so.1 (0x00007f8619048000)                                                                                            
        libGLEW.so.1.10 => /usr/lib/x86_64-linux-gnu/libGLEW.so.1.10 (0x00007f8618db8000)                                                                                          
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f8618b20000)                                                                                                    
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8618900000)                                                                                                          
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f86186f8000)                                                                                                        
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f86183b8000)                                                                                                  
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8618198000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f8617f68000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8617d60000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f86179d8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f86176d0000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f86174b8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f86170e8000)
        libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f8616a98000)
        libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007f86167e0000)
        libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f86165d0000)
        libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f86162b8000)
        libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f8616090000)
        libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f8615e40000)
        libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f8615be8000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f86158d8000)
        libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f86156d0000)
        libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f86154c8000)
        libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f86152a0000)
        libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f8615048000)
        libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f8614dd0000)
        /lib64/ld-linux-x86-64.so.2 (0x000056187980d000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f8614ba0000)
        libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f8614970000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f8614758000)
        libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f8614550000)
        libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f8614348000)
        libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f8614140000)
        libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f8613f20000)
        libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f8613d18000)
        libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f8613b10000)
        libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f8613908000)
        libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f8613700000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f86134d8000)
        libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f86132d0000)
        libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f86130c0000)
        libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f8612eb8000)
        libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f8612c90000)
        libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f8612908000)
        libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f86126f0000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f86124b0000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f86122a0000)
        libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f8612098000)
        libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f8611e88000)
        libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f8611c78000)
        libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f8611a68000)
        libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f8611860000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f86115b8000)
        libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f8611308000)
        libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f8611100000)
        libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f8610ef0000)
        libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f8610ce0000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f8610ad8000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f8610868000)
        libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f8610648000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f8610440000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f8610218000)
        libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f8610008000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f860fe00000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f860fbf8000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f860f9d0000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f860f7b0000)
        libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f860f550000)
        libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f860f348000)
        libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f860f128000)

**Comment by tambry** [comment]
Is this still an issue?

**Comment by piotr-szegda** [comment]
On current git version I have other problem so I can't check.
(gdb) run
Starting program: /home/pszegda/Apps/rpcs3/bin/rpcs3 

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
vm::g_base_addr = 0x7ffeec97a000
vm::g_priv_addr = 0x7ffdec97a000

Program received signal SIGSEGV, Segmentation fault.
__opendirat (dfd=-100, name=0x0) at ../sysdeps/posix/opendir.c:91
91      ../sysdeps/posix/opendir.c: No such file or directory.
(gdb)

**Comment by piotr-szegda** [comment]
Now rpcs3 is starting but LLVM issues is still exist.

**Comment by tambry** [comment]
@piotr-szegda You were trying to use LLVM 3.8, correct? Will 16.04 include LLVM 3.8 by default? You could probably try compiling without LLVM. Also considering now that CMake should not compile with LLVM unless the specific version we use exists.

**Comment by piotr-szegda** [comment]
No, I am still trying to use LLVM 3.6 by cmake CMakeLists.txt -DLLVM_DIR=/usr/share/llvm-3.6/cmake.
When I don't specify dir with LLVM 3.6 RPCS3 is compiled without LLVM support.

**Comment by tambry** [comment]
@piotr-szegda What is the exact error/problem?

**Comment by piotr-szegda** [comment]
I'll explain everything from the beginning. I'd like to build RPCS3 on Ubuntu. First I tried on 15.10 but on it default LLVM is 3.7. So I install LLVM 3.6 and run in RPCS3 dir:
`cmake CMakeLists.txt -DLLVM_DIR=/usr/share/llvm-3.6/cmake`
Cmake don't report any problem. Compilation passed without a problem. But when I try run something in RPCS3 it's crash. So I used gdb to debug problem I have something like that:
`
Thread 1 "rpcs3" received signal SIGSEGV, Segmentation fault.
0x00007ffbe1b3b8f7 in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-3.7.so.1
`
It seems that cmake link the wrong version of the LLVM. Now I tried another machine with Ubuntu 16.04 and the problem also occurs.

**Comment by piotr-szegda** [comment]
My CMakeCache: http://pastebin.com/ZU0y2yv7

**Comment by tambry** [comment]
@piotr-szegda What CMake version are you using? We have [specific code](https://github.com/RPCS3/rpcs3/blob/master/rpcs3/CMakeLists.txt#L129) for allowing only LLVM 3.6 to be used.

**Comment by piotr-szegda** [comment]
3.2.2. It seems to me that is a problem with linking or even lack of it. RPCS3 always uses the same version of the LLVM as a mesa in the system.

**Comment by AniLeo** [comment]
You need to ignore the SIGSEV sinal
```
handle SIGSEGV nostop noprint
```
Try again with the latest master repo

**Comment by piotr-szegda** [comment]
Still crash but with handle SIGSEGV nostop noprint log is different:

```
Starting program: /home/piotr/Apps/rpcs3/bin/rpcs3 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
vm::g_base_addr = 0x7ffeec175000
vm::g_priv_addr = 0x7ffdec175000
[New Thread 0x7ffdebbf9700 (LWP 26285)]
[New Thread 0x7ffdeb3f8700 (LWP 26286)]
[New Thread 0x7ffdea9da700 (LWP 26287)]
[New Thread 0x7ffdea1d9700 (LWP 26288)]
[New Thread 0x7ffde99d8700 (LWP 26289)]
[Thread 0x7ffdea9da700 (LWP 26287) exited]
[Thread 0x7ffdea1d9700 (LWP 26288) exited]
[New Thread 0x7ffdea1d9700 (LWP 26290)]
[New Thread 0x7ffdea9da700 (LWP 26291)]

(rpcs3:26281): GdkPixbuf-WARNING **: Bug! loader 'png' didn't set an error on failure
[Thread 0x7ffdea1d9700 (LWP 26290) exited]
[Thread 0x7ffdea9da700 (LWP 26291) exited]
[New Thread 0x7ffdea9da700 (LWP 26293)]
[Thread 0x7ffdea9da700 (LWP 26293) exited]
[New Thread 0x7ffdea9da700 (LWP 26294)]
[Thread 0x7ffde99d8700 (LWP 26289) exited]
[New Thread 0x7ffde99d8700 (LWP 26295)]
[Thread 0x7ffdea9da700 (LWP 26294) exited]
[New Thread 0x7ffdea9da700 (LWP 26296)]
[New Thread 0x7ffdea1d9700 (LWP 26297)]
Fatal error: Access violation writing location 0x2367620 at 0x7ffbd0d678f7.
Please report this error to the developers.

Thread 1 "rpcs3" received signal SIGABRT, Aborted.
0x00007ffff46a9227 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 

```

**Comment by piotr-szegda** [comment]
I fixed this by changing find_package(LLVM CONFIG) to find_package(LLVM 3.6) in CMakeLists.txt.

**Comment by tambry** [comment]
Is this still an issue?

**Comment by piotr-szegda** [comment]
Now I got only "LLVM not found!". It's even worse then before because I can't compile with LLVM by doing only small edit.

**Comment by tambry** [comment]
@piotr-szegda LLVM is no longer used and it's the reason for that being commented. Is there anything other than that or is it fixed?

**Comment by piotr-szegda** [comment]
Cmake should not complain about the lack LLVM if it's not used now.
Docs should be fixed, correct command to compile is: cmake CMakeLists.txt && make. Compiling from rpcs3 dir break compilation process. I will try to make docs update pull request.

**Comment by axfelix** [comment]
You should probably remove the `cd rpcs3` from the build instructions in the readme as it's misleading -- a lot of people will be going into the rpcs3 subdirectory to try to build, since CMakeLists.txt also exists in there.

**Comment by tambry** [comment]
@axfelix But it also describes the process of cloning RPCS3. And RPCS3 is going to be cloned into rpcs3 directory. So one will need to cd into it.

**Comment by kristian15959** [comment]
czeszt

2016-05-30 7:56 GMT+02:00 Raul Tambre <notifications@github.com>:

**Comment by AniLeo** [comment]
Linux instructions were updated (We tested under them under Ubuntu 16.04), please reopen if still an issue.
