### ISSUE TITLE
Compiling shaders problem 

### ISSUE THREAD

**Issue by Nightraven1a** [RPCS3/rpcs3#13674]
### Quick summary

I'm using the current version of Linux Mint Cinnamon, and I just set up the RPCS3 for the first time, but the problem I have been having is the compiling shaders. I don't know how to fix it because this is my first time using the RPCS3. I don't know if it's the program or the games I downloaded from Vimm's Lair because I'm trying to play games like Spider-Man: Edge of Time and Shatter Dimensions. Also, I don't suppose you know any Playstation 3 rom websites that are safe to use. Because Vimm's Lair is super slow in downloading, and in RPCS3, the game is way too slow. So, I  wonder if anyone knows what safe websites to use for downloading any PS3 game. 

### Details

Spider-Man Edge of Time and Shatter Dimensions barely work and mainly involve compiling shaders,and they stop working. In Edge of Time, it was running slowly, and it gives me this error "Stopping emulator took too long.Some thread has probably deadlocked. Aborting. Thread id = 147150". In Shatter Dimensions, it was not only running slow, the graphics glitched, and it gives me this error "Verification failed (in file ../rpcs3/Emu/System.cpp:183, in function BlockingCallFromMainThread) (errno=2=No such file or directory) Thread id = 14206". 
![Screenshot from 2023-04-15 12-53-37](https://user-images.githubusercontent.com/65839617/232246236-c215fec8-5e3f-4519-96b9-bc571f212f9e.png)

### Build with regression

BLUS30499, and BLUS30760

### Attach two log files

Stopping emulator took too long.
Some thread has probably deadlocked. 
Aborting. Thread id = 147150

Verification failed
 (in file ../rpcs3/Emu/System.cpp:183, in function BlockingCallFromMainThread) (errno=2=No such file or directory) 
Thread id = 14206

**Comment by Asinin3** [comment]
GitHub is not the place to ask for support, its an issue tracker for reporting bugs with information that can actually be useful to a developer. Nor does RPCS3 support piracy.

I would point you in the right direction to ask for help but pirates do not get any assistance.

**Comment by Asinin3** [comment]
Not sure where you saw me insult you..? But since you asked:
> Build with regression - Serial BLUS30499 and BLUS30760
Bruh, these are game region serials and not even builds. Not to mention you didn't provide any logs or anything remotely useful.

Stop spamming GitHub
