### ISSUE TITLE
Compiling shaders

### ISSUE THREAD

**Issue by Nightraven1a** [RPCS3/rpcs3#13677]
### Quick summary

I'm using the current version of Linux Mint Cinnamon, and I just set up the RPCS3 for the first time, but the problem I have been having is the compiling shaders. I don't know how to fix it because this is my first time using the RPCS3. I don't know if it's the program or the games I played. 

### Details

In Spider-Man Edge of Time and Shatter Dimensions barely work and mainly involve compiling shaders,and they stop working. In Edge of Time, it was running slowly, and it gives me this error "Stopping emulator took too long.Some thread has probably deadlocked. Aborting. Thread id = 147150". In Shatter Dimensions, it was not only running slow, the graphics glitched, and it gives me this error "Verification failed (in file ../rpcs3/Emu/System.cpp:183, in function BlockingCallFromMainThread) (errno=2=No such file or directory) Thread id = 14206".

### Build with regression

Serial BLUS30499 and BLUS30760

### Attach two log files

Stopping emulator took too long.Some thread has probably deadlocked. Aborting. Thread id = 147150

Verification failed (in file ../rpcs3/Emu/System.cpp:183, in function BlockingCallFromMainThread) (errno=2=No such file or directory) Thread id = 14206".

**Comment by sansfann69** [comment]
#13674 do u really got no shame tryna do the same thing twice except for conveniently removing the fact that you pirated the game ? thats crazy

**Comment by kd-11** [comment]
Not a proper bug report. No log file provided, hardware not specified, etc - see the "no response" sections in the OP.
Also if the complaint is about performance, ask for help on discord.
