### ISSUE TITLE
[Regression] Destiny text is incorrectly rendered

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13682]
### Quick summary

as title says

### Details

when testing the Destiny demo I notice the text seemed to have artefacts around characters not present on hw. Seem have started happening when pr #13046 was merged
Masters:
![NPJA90286_screenshot_2023_04_16_22_32_41](https://user-images.githubusercontent.com/71127352/232344042-f5d44c39-bb31-4501-9521-6be6046da2fa.png)

25-14454:
![NPJA90286_screenshot_2023_04_17_14_34_21](https://user-images.githubusercontent.com/71127352/232501390-6ab103cf-af93-4527-a536-fc7dc9585304.png)

### Build with regression

0.0.25-14465

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11244688/RPCS3.log)
[RPCS3v0.0.25-14454-ab3c8268.log.gz](https://github.com/RPCS3/rpcs3/files/11250745/RPCS3v0.0.25-14454-ab3c8268.log.gz)

### Attach capture files for visual issues

[NPJA90286_20230416222525_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/11244695/NPJA90286_20230416222525_capture.rrc.gz)
[NPJA90286_working_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/11250828/NPJA90286_working_capture.rrc.gz)

### System configuration

RPCS3 v0.0.27-14878-b7066586 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by cohaereo** [comment]
This can be fixed/worked around by setting shader quality to low

**Comment by Triticum0** [comment]
It fixes the issue but not sure it counts as a proper fix. If the dev thinks the fix suffices then they can close the issue

**Comment by cohaereo** [comment]
Might be worth mentioning we first started observing this issue roughly around PR #13201 so it might actually be a regression

**Comment by Triticum0** [comment]
Seems to be present before that pr, so I need to know what pr broke the text.

**Comment by kd-11** [comment]
> This can be fixed/worked around by setting shader quality to low

So the problem only affects NVIDIA? NV has a different set of workarounds from AMD due to bad precision issues.
If it affects both, it would narrow down the scope a bit.

**Comment by cohaereo** [comment]
I have an AMD card, I'll test it

**Comment by cohaereo** [comment]
Confirmed, shader quality has no effect on AMD, text looks fine
![image](https://user-images.githubusercontent.com/25546261/232575019-e7df04e9-e0f0-4b6a-a996-411bc14d7cf8.png)

**Comment by syberphunk** [comment]
I have experienced the text incorrectly rendered problem on nvidia 3080 and 4080, I also have to set the shader to 'low' to not have this problem. Doesn't appear to matter what Vulkan settings are in place in nvidia control panel, vulkan runtime installed or which nvidia driver is installed.

**Comment by kd-11** [comment]
I've added a workaround to do the calculations in 64-bit. https://github.com/RPCS3/rpcs3/pull/13690
Seems to work well enough for destiny. There will be a perf hit on NV with larger shaders but I guess users can always turn down the shader quality. It's what the option is for afterall.
