### ISSUE TITLE
[Regression] Little Big Planet freezes upon opening

### ISSUE THREAD

**Issue by HeadCrabKing682** [RPCS3/rpcs3#13694]
### Quick summary

Little Big Planet 1 freezes upon loading into a level in the most recent updates of RCPS3

### Details

In update PR #13636 Little Big Planet 1 opens and runs as normal, but in PR #13672 and onwards, Little Big Planet freezes as soon as you load into a level. You can open the game, and access the main menu, but it stops working upon entering into a level, or loading a save that is already in a level

### Build with regression

PR #13672

### Attach two log files

https://drive.google.com/drive/folders/1TDGthbSTbBCanc6wZVZzF70PQznqMAk3?usp=share_link

**Comment by AniLeo** [comment]
Should have been fixed by #13702, we don't have any active regression on LBP for a long time, closing as completed
