### ISSUE TITLE
Fist of the North Star: Ken's Rage Graphical Issue

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13707]
### Quick summary

The game suffers from a serve graphical issue when compiling shaders

### Details

When testing this game I ran into an issue where most of the screen is completely black other than the outline of the characters and UI elements. This can be fixed by restarting the game but every time a new shader is compiled the issue repeats until all shaders are compiled. this means you need to restart the emulator 4 times to complete the demo.

The Issue occurs on the first boot into combat the subsequently when doing each time event attack to finish the mission

The first shader compile
![NPEB90285_screenshot_2023_04_19_14_54_10](https://user-images.githubusercontent.com/71127352/233099259-e6fe7f3d-3ec5-4187-9a94-a3ef96118866.png)

The second shader compile
![NPEB90285_screenshot_2023_04_19_14_59_11](https://user-images.githubusercontent.com/71127352/233099286-addd4ac8-8352-4e5e-9d9c-a99201de9f85.png)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11273933/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1kmEOA634L165vyEs6xXoJ3i6AWHmBcYe/view?usp=share_link

### System configuration

RPCS3 v0.0.27-14885-32bfb808 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by Triticum0** [comment]
Both shader modes seem to fix the issue. Shader interpreter + async seems to have worse frame spikes compared to legacy. I close the issue once I add the settings to the wiki. Thanks

**Comment by Triticum0** [comment]
Thank for the help Kd

**Comment by Darkhost1999** [comment]
This was worked around and not fixed right? Or does this one qualify as a fix? It's Legacy features.

**Comment by kd-11** [comment]
There is no true fix for shader compilation stutter. It's why the legacy compiler option still exists in the menus so its fine to close this issue.

**Comment by kd-11** [comment]
Accidental reopen. Github mobile UI sucks
