### ISSUE TITLE
Uncharted Drakes Fortune BCUS98103

### ISSUE THREAD

**Issue by Vlhss** [RPCS3/rpcs3#13705]
### Quick summary

Game keeps crashing after 5-10 minutes of gameplay.

### Details

While the game is averaging around 30fps and 15-20 when fighting, the random crashes make the game unplayable. It's not like I cannot access certain areas of the game, before and after the crash I can play flawlessly for about 5-10 minutes.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11272540/RPCS3.log)

On this attempt I played for a solid 30minutes-1hour and right after I entered chapter 5 and saved it immediatelly crashed

### System configuration

AMD Ryzen 5 1400 Quad-Core Processor 3.2 GHz
GTX 970 4GB OC (531.68)
24GB Ram
Windows 10 Pro 1909 64-bit (OS build 18363.1556)

### Other details

The game runs on Vulkan and I use the default settings but I have enabled SPU loop detection, frame limit set to 30, write color buffers is on (I am on chapter 4 thats why), vsync is on and stretch to display area is on. I have also changed the UI stylesheet to skyline nightfall but doubt that makes any difference. I have also installed the disable depth of field and disable motion blur patches.

I hope the emulator perfects the uncharted, gow and lof games before moving on as they are the most important games of the platform.

**Comment by aeseok** [comment]
What version of the game did you update to and if you don't mind sharing your settings, if they differ from the ones on the wiki
