### ISSUE TITLE
[Regression] Need for Speed: The Run unable to go further after LLVM optimization update

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#13704]
### Quick summary

The game can go further when using higher clocks scale on 14879, but after updating the RPCS3 (#13672), the game freezes when using higher clock scales.

### Details

14879 Build manage to reach the menu when using 65% clocks scale.
![Regression 3](https://user-images.githubusercontent.com/125112932/233046799-bf245a1f-1159-429f-af7f-4f4a95631461.PNG)

However on a 14881 Build, the game randomly freezes during the intro when using 65%.
![regression (2)](https://user-images.githubusercontent.com/125112932/233044482-3c88c707-a9da-4b18-978d-5fd672b15a62.PNG)

I can go ingame when using 50% clocks scale on a 14879 Build.
![Regression 2 (2)](https://user-images.githubusercontent.com/125112932/233044228-1d86f6ea-aee6-4d5e-bd8e-c0cb78aff959.jpg)

Sadly for 14881 Build, the game crashes when trying to exit the menus after using 50%.
![Regression 4](https://user-images.githubusercontent.com/125112932/233052718-fa74c8dc-19fb-4153-b60f-50717af328f0.PNG)

### Build with regression

v0.0.27-14881-39d17a94

### Attach two log files

14879:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11271969/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11271548/RPCS3.log.gz)

14881:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11271954/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11272144/RPCS3.log.gz)

### System configuration

AMD Ryzen 9 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 531.61.0.0 | Windows 10 Pro 22H2

**Comment by Ordinary205** [comment]
I'm closing the issue, because the regression is fixed on this PR #13702

**Comment by Nekotekina** [comment]
I suspect it's random or timing-dependent
