### ISSUE TITLE
[Regression] NHL Legacy - graphics glitches after SPU accuracy changes for PSN (#13608)

### ISSUE THREAD

**Issue by Jukphor** [RPCS3/rpcs3#13714]
### Quick summary

Player models have polygonal flickering/glitching in NHL Legacy during cut-scene parts of match

### Details

So far I have found that in NHL Legacy 1.01 (PSN version), during the cut scene parts of the match as well as the instant replay, the player models tend to have a polygonal sort of flickering all through their bodies. See video for example. https://streamable.com/h7lbao 

I have tried playing with render scale threshold and asynchronous texture streaming to no avail. The problems started in 14860. 

### Build with regression

0.0.27-14860

### Attach two log files

[RPCS3 14860.log.gz](https://github.com/RPCS3/rpcs3/files/11291023/RPCS3.14860.log.gz)
[RPCS3 14859.log.gz](https://github.com/RPCS3/rpcs3/files/11291036/RPCS3.14859.log.gz)

### Attach capture files for visual issues

https://mega.nz/file/RXx1UayY#CsqcRlaapBjFlJ0oXqtI_rgbaf64LC99qn7LrkOzgu8

### System configuration

AMD 5800X3D
Nvidia RTX 3070 (Gigabyte Aorus Master)
I've tried the 2 latest drivers for the GPU including 531.68
Monitor is 165hz, so the framerate is set to infinite etc

**Comment by kd-11** [comment]
Triggered by https://github.com/RPCS3/rpcs3/pull/13608
Tagging @RipleyTom

**Comment by XieTieqiang** [comment]
Set network settings to connect
God of War Ascension also has graphics issues

**Comment by Frenthor** [comment]
One of the RPCS3 testers from discord gave me this build as Diablo 3 was encountering this same issue when network status is connected. Graphics glitch disappeared when I used it, even when network status is connected and RPCN is turned on.
