### ISSUE TITLE
message when running tony hawk 5

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#1372]
![error tony hawk](https://cloud.githubusercontent.com/assets/16367065/11997104/f31087de-aa40-11e5-8e65-080217390eee.png)

**Comment by tambry** [comment]
I don't want to really throw out these issues, but as you've failed to provide the required information for the issue, I'm going to close this. Feel free to post the issue on the forum. Github issue tracker is more for known specific problems in a certain function, rendering issue and generally for keeping track of actual code issues.
