### ISSUE TITLE
Skate 3 square shadow issue on OpenGL

### ISSUE THREAD

**Issue by AdolfRoxler** [RPCS3/rpcs3#13724]
### Quick summary

Shadows

### Details

Roblox logo shaped shadow following your character

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11300812/RPCS3.log.gz)

### Attach capture files for visual issues

https://anonfiles.com/OaL8Oam2z4/BLUS30464_20230422110020_capture_tar_xz

### System configuration

![image](https://user-images.githubusercontent.com/91347019/233775024-29339ba4-01c6-4805-ba09-215bfd6c6ab6.png)

**Comment by AniLeo** [comment]
Cannot reproduce

---

**OpenGL**
![Screenshot from 2023-04-23 14-50-35](https://user-images.githubusercontent.com/10283761/233843665-02a3c607-01d3-49a7-9efe-daa3422bdba5.png)

**Vulkan**
![Screenshot from 2023-04-23 14-49-58](https://user-images.githubusercontent.com/10283761/233843672-f1b993ea-ac5d-4f79-929d-ebdf1a4a7960.png)

**Comment by AniLeo** [comment]
Verified as OpenGL specific and not vendor/driver/OS specific

**Comment by MSuih** [comment]
Tested that as well as enabling all 4 buffer options, it doesn't work. On Vulkan Skate 3 has never needed RDB, only WCB for some optional details

**Comment by kd-11** [comment]
Oh the screenshots are from replay. Nvm then.

**Comment by AdolfRoxler** [comment]
They're not from replay btw

**Comment by MSuih** [comment]
Ani's first two screenshots are from opening your capture and the third is a reference image he got from someone else. That's why the issue shows in Vulkan even though this bug happens only for opengl during normal gameplay.
