### ISSUE TITLE
[Regression] Booting a game heavily stutters at full 16 GB RAM

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#13720]
### Quick summary

Before 14897, everything seems totally fine, but after updating the RPCS3 (#13710), some games seems to be using full RAM usage when trying to boot the game like Midnight Club LA.

### Details

On a 14897 Build, the game seems to be working fine, with a normal RAM usage.
![Works fine](https://user-images.githubusercontent.com/125112932/233721470-5cfd366c-f36f-4c8c-8d03-8b771ea57dc9.PNG)

However for the 14898 Build, it causes a massive stutters when booting a game at full 16 GB RAM.
![Doesnt Work](https://user-images.githubusercontent.com/125112932/233721502-ed23b834-3f34-4eb9-b171-ddd5ab48620f.PNG)

### Build with regression

v0.0.27-14898-10412843

### Attach two log files

14897 Build:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11298775/RPCS3.log.gz)

14898 Build:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11298774/RPCS3.log.gz)

### System configuration

AMD Ryzen 9 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 531.68.0.0 | Windows 10 Pro 22H2

**Comment by Ordinary205** [comment]
Removing all the caches before booting the game doesn't solve the issue aswell.

**Comment by solarmystic** [comment]
I think my GT5 issue report is also linked to yours, it has the same responsible commit, and all 32+ GB RAM is being used towards the end of building SPU cache before the crash happens. 

![image](https://user-images.githubusercontent.com/4345150/233749298-30307d8c-2ba3-4581-9666-53ddb2c5028b.png)

**Comment by solarmystic** [comment]
should be fixed by #13722, retest with latest master @Ordinary205

**Comment by Ordinary205** [comment]
The game now works properly thanks to this PR #13722
![Works fine now](https://user-images.githubusercontent.com/125112932/233760290-1972614b-dadc-4455-97c3-6ac874985484.PNG)
