### ISSUE TITLE
[Feature request] Support for HEN? Plus full browser support.

### ISSUE THREAD

**Issue by robokingscosmosps3** [RPCS3/rpcs3#13730]
### Quick summary

Homebrew Enabler on RPCS3 HFW 4.90 without needing to copy the files you know like going to ps3xploit website from there? If you guys can achieve this with the emulator I want to see the browser fully implemented on vsh.

### Details

With HEN you get an icon on the vsh called * Enable HEN
When you enable HEN by hitting the x/o button on it, it should show Welcome to HEN 3.2.1 and enable syscalls.
It is important because I want to see the emulator support it even locally too especially the browser itself for the ps3 to access simple webpages like google without crashing

**Comment by Darkhost1999** [comment]
![image](https://user-images.githubusercontent.com/60384196/233807318-a251481d-0235-4b0c-90d8-c262b24116d2.png)
Why do you need HEN and nobody is stopping you from using vsh browser
![image](https://user-images.githubusercontent.com/60384196/233807374-342a1309-10a0-4e9a-ad7b-9e98ea7f26ee.png)
Even for a simple webpage like google without crashing

**Comment by robokingscosmosps3** [comment]
i'll try it out! ty
