### ISSUE TITLE
OpenEnter a title here

### ISSUE THREAD

**Issue by kraz63** [RPCS3/rpcs3#13734]
### Quick summary

One OpenGL error that makes the game not work

### Details

Spider-Man: Edge of Time is not working (at least for me)
my specs are provided in the log file part.
please tell me how I can run this
I do not have a dedicated GPU slot/card, nor do I want one
I don't have the "vulcan" option in the GPU section
plsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss help

### Attach a log file

- SYS: RPCS3 v0.0.27-14919-6bf77166 Alpha | master
- SYS: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz | 4 Threads | 15.70 GiB RAM | TSC: 3.300GHz | AVX
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-04-22T16:37:26
- SYS: Firmware version: 4.90
S UPDATER: RPCS3 is up to date!
S PPU: Enabled: Non-Java Mode Fixup
S Input: The pad mode was changed to Single-threaded
S GUI: Boot successful.
F {RSX [0x0000000]} SIG: Thread terminated due to fatal error: Could not bind OpenGL context
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\rpcs3qt\gl_gs_frame.cpp:77[:24], in function set_current) (error=0x7e)

### Attach capture files for visual issues

![image](https://user-images.githubusercontent.com/131562403/233812219-4b6c8a38-2856-4f9b-840a-700d2c9d86a4.png)

**Comment by FlexBy420** [comment]
You are below minimum requirements
