### ISSUE TITLE
openGL screen black dragon ball raging blast 2

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#1373]
once executed the game starts a black screen after logo
1: ![error 1 racing blash 2](https://cloud.githubusercontent.com/assets/16367065/11997197/263014b6-aa43-11e5-94d6-154c549e17e7.png)

2: ![error 2 racing blash 2](https://cloud.githubusercontent.com/assets/16367065/11997201/336730ba-aa43-11e5-9e6a-84094f411584.png)

**Comment by tambry** [comment]
@mkultimate Once again, no mention of the settings used or no log file.
This report is basically uselesss without the details.

**Comment by mkultimate** [comment]
ok and he puts the settings used

**Comment by mkultimate** [comment]
![config 1 racing blash 2](https://cloud.githubusercontent.com/assets/16367065/11998025/7fb716fc-aa5b-11e5-94a1-4b026c09b82b.png)
![config 2 racing blash 2](https://cloud.githubusercontent.com/assets/16367065/11998026/7fcb1f30-aa5b-11e5-87e1-c86f3f6a34f4.png)

LLEModules:

cellM2AACenc_Library v1.1
cellM2AACenc_Library_spurs v1.1
cellFiber_Library v.1.1
cellJpgdec_Library v.1.1
CELL_L10n_PRX_MODULE_NAME v1.1
cellPngEnd_Library v1.1
cellSpursjq_Library v.1.1
cellSre_Library v.1.1
sceNpTrophy_Library v.1.1

**Comment by tambry** [comment]
[Closing for the same reason as the #1372](https://github.com/RPCS3/rpcs3/issues/1372#issuecomment-167204523).

**Comment by El-Djazair92** [comment]
Bonjour ou est ce que vous avez telecharger le jeu j'ai beau cherchez partout je ne l'ai pas trouver Je sais que ce n'ai pas le sujet mais c que je ne l'ai trouver nul part Merci

**Comment by tambry** [comment]
Github issue tracker is English only. Please refrain from using other languages in the future.

**Comment by El-Djazair92** [comment]
Hello or have you download this game I can not find it (I c that is not the subject)                                                   Its Good ?

**Comment by tambry** [comment]
Piracy is not allowed and will not be tolerated. Don't ask help with piracy in the future.

**Comment by El-Djazair92** [comment]
pffffff

2016-04-15 12:07 GMT+02:00 Raul Tambre <notifications@github.com>:
