### ISSUE TITLE
my rpcs3 crashes when linking PPU modules

### ISSUE THREAD

**Issue by matxws** [RPCS3/rpcs3#13732]
### Quick summary

It crash when i try to start NPUB31864 (PES 2018),the linking ppu bar gets almost done and then rpcs3 crash

### Details

im new to this rpcs3 thing, sorry if im missing something

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11302032/RPCS3.log)

### Attach capture files for visual issues

https://user-images.githubusercontent.com/131550548/233801398-87320e3a-0095-4e63-acfd-406d15625e0f.mp4

**Comment by Darkhost1999** [comment]
The log does not contain the information in the video. Please reupload a log that contains your game boot and the error.

**Comment by matxws** [comment]
how i do it? i tried to do it like https://github.com/RPCS3/rpcs3/issues/10815

**Comment by Darkhost1999** [comment]
> how i do it? i tried to do it like https://github.com/RPCS3/rpcs3/issues/10815

Simply just don't restart rpcs3 after playing your game as every time you boot rpcs3 it'll wipe the log clean.
So boot your game
Get the error
Close rpcs3 (do not open it again) 
Upload log

**Comment by AniLeo** [comment]
This should be first submitted as a support request, as this is not a proper issue report

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by vpsaputra** [comment]
i have the same issue before. Solved with following config:
PPU decoder : Interpeter(static)
SPU decoder : Interpeter (static)
SPU block size : Giga
Thread Scheduler : RPCS3 Scheduler
