### ISSUE TITLE
[Regression] Non AVX2 CPU not starting any game (#13534)

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#13736]
### Quick summary

Hello.
Thanks for reading my topic.
AMD FX-6300 4 GB GeForce GT 640 driver 470 Linux Lubuntu 20.04.5 kernel 6.2

0.0.27-14845 games start and run correctly.
Since 0.0.27-14846 Update to LLVM 16 not is possible start any game if using SPU LLVM.
When finish the task loading PPU modules is done an crash in RPCS3 main and game windows being both closed.
From 0.0.27-14846 to current version not is possible start any game if using SPU LLVM.
The games only start if using SPU ASMJIT.
AMD FX have SSSE3, SSE4 and AVX and the games not are high requirement to play.
Strange not any user reporting about it and is as not happen that bug in AMD Zen and Intel.
LLVM 16 requires new cpu instructions or have any issue in some cpus ?

I have uploaded an "cache.zip" inside logs of Bomberman Ultra and Spelunker in PPU creation and trying start.
Please reply If need any other log or information.

Have an nice week.

### Attach a log file

[cache.zip](https://github.com/RPCS3/rpcs3/files/11302983/cache.zip)

**Comment by Nekotekina** [comment]
Try with #13738

**Comment by Augusto7743** [comment]
Tested ... now Bomberman Ultra and Spelunker HD are starting and running correctly =)
Need test with others games .... possibly was fixed.
Thanks very much !

**Comment by AniLeo** [comment]
Closing as verified as fixed
