### ISSUE TITLE
PlayStation Home 0.98 (Retail Client) - Missing characters and glitched sounds with SPU set as LLVM

### ISSUE THREAD

**Issue by githubalternate55** [RPCS3/rpcs3#13733]
### Quick summary

The retail client of "PlayStation Home", can go online , but RPCS3 is having a hard time with this specific version.

When the SPU co-processor is set to the LLVM option, the characters in the game don't render, and sounds are super glitchy, and networking is very unstable.

### Details

I will not go into much details at first, the issue seems pretty obvious with the screenshots provided, don't hesitate to ask me if more infos are needed.

### Attach a log file

[RPCS3 - log.zip](https://github.com/RPCS3/rpcs3/files/11302277/RPCS3.-.log.zip)

### Attach capture files for visual issues

With SPU set to LLVM : 

![character](https://user-images.githubusercontent.com/119062794/233806649-e0f6819a-b038-4d1a-a777-adc493f3f1d8.png)

With SPU set as interpreters : 

![image](https://user-images.githubusercontent.com/119062794/233806560-ff6dbc93-94bf-45ef-8fab-0f1c1d62f962.png)

One log of a network issue, very often triggered when in SPU LLVM : 

![networking](https://user-images.githubusercontent.com/119062794/233806630-c1dab567-eb96-40ce-a1ce-698a4fcca7cc.png)

### System configuration

Operating System - Windows 11

CPU - Intel Core I9 9900K

GPU - Nvidia RTX 3070 (driver - 526.47)

**Comment by githubalternate55** [comment]
Small update, SPU to asmjit also works fine : 

![image](https://user-images.githubusercontent.com/119062794/233807393-9097e8d7-04f0-4402-9a22-15b1f429c04f.png)

**Comment by AniLeo** [comment]
Is this a regression from any of the recent PRs or the LLVM 16 update, or has it always been an issue even before?

**Comment by githubalternate55** [comment]
This is a regression from one of the recent PRs. I will try to find the build that caused it.

**Comment by MSuih** [comment]
Does https://github.com/RPCS3/rpcs3/pull/13723 help?

**Comment by githubalternate55** [comment]
Yes it does! It also resolve the 0.41 version of the game.

![image](https://user-images.githubusercontent.com/119062794/233847459-64aa70a8-9478-4c18-82f8-adaa54fa5553.png)
