### ISSUE TITLE
Madagascar 3 almost black ingame - Unimplemented SCB / Unimplemented TEX_SRB instructions

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#1374]
I don't know exactly if unimplemented instructions below have an any impact to blacky ingame, but I want you to know @vlj .

##### Unimplemented TEX_SRB instruction: UPB RSX: W

[LOG](https://mega.nz/#!6E0TwABT!7eT5Nhtw5zrMfQFGIurBmJVGeXqNz7BBx-YkSuuBjjE)

##### rpcs3 settings:

![rpcs3 settings 1](https://cloud.githubusercontent.com/assets/11453507/12002883/61586998-ab0c-11e5-9b26-2c8d84ff729d.PNG)
![rpcs3 settings 2](https://cloud.githubusercontent.com/assets/11453507/12002884/64aa2ece-ab0c-11e5-9023-7678067dda32.PNG)

##### LLE modules:
cellFiber_Library v1.1
CELL_L10N_PRX_MODULE_NAME v1.1
cellPamf Library v1.1
cellSail Library v1.1
cellSpursJq_Library v1.1
cellSre_Library v1.1

Ben 10 games have a similar issues, but not found unimplemented instructions in the log.Game needs cellSail to be check to go further (videos) and sometimes fails on (hangs at opening videos): 

##### Please report this to the developers.

![madagascar 3 3](https://cloud.githubusercontent.com/assets/11453507/12002761/550826d6-ab09-11e5-872e-3cde12cfa13b.PNG)
![madagascar 3 4](https://cloud.githubusercontent.com/assets/11453507/12002763/59e71ed2-ab09-11e5-9d66-433c03ace645.PNG)
![madagascar 3 5](https://cloud.githubusercontent.com/assets/11453507/12002765/67462b36-ab09-11e5-89ea-898b9d546297.PNG)
![madagascar 3 6](https://cloud.githubusercontent.com/assets/11453507/12002766/6b22ae0a-ab09-11e5-884d-c06f593d76f4.PNG)

also

####  rpcs3

![madagascar 3 1](https://cloud.githubusercontent.com/assets/11453507/12002774/aa52a6a2-ab09-11e5-9e9e-7080ca087a4d.PNG)

### real ps3 ingame

![madagascar 3 2](https://cloud.githubusercontent.com/assets/11453507/12002776/b3dc0628-ab09-11e5-81b4-92180ecdf9b8.PNG)

**Comment by tambry** [comment]
@JohnGodgames I see you have reported several issues in one issue. Would you mind splitting it up for each problem? (The shader problems and the HLE problem)

**Comment by tambry** [comment]
While this issue does report some problems, I'm usnure whether this issue is too helpful, as it points out a larger problem. Github issues are mostly for small noticeable problems. Ie. unimplemented functions, some graphical problems, crashes, coding defect, etc.
Please split the issue into smaller issues, if you still deem the smaller issues being worth an issue.
