### ISSUE TITLE
PlayStation Home - Retail Branch : Unimplemented sceNpEulaCheckEulaStatus protocol.

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#13744]
### Quick summary

The retail clients of "PlayStation Home", can, for the vast majority of them, go online , but RPCS3 is having a blocking issue that prevent every retail versions released after 1.35 to be playable online in the emulator.

The blocking factor seems to come from the XMB based EULA, or rather, lack of it in RPCS3.

### Details

When finishing SVO login, the game will check for the EULA using Np. On a real PS3, the following will be printed : 

![image](https://user-images.githubusercontent.com/119062794/233865131-c3b6af3f-ed2f-466c-970a-26a2cc4e3bd5.png)

With then, the choice entered via XMB, which will get stored in the system : 

![image](https://user-images.githubusercontent.com/119062794/233865168-088040fb-b283-4267-bc8d-50edddbc278c.png)

The system is driven by an index.xml file which redirects to said HTML EULA webpage.

(Small example of the syntax)

<eula npcommid="NPWR00432_00">
  
  <file name="u_pshome-tosua_en.html" version="2" country="us"/>
  <file name="u_pshome-tosua_fr.html" version="2" country="ca" language="2" />
  <file name="u_pshome-tosua_en.html" version="2" country="ca"/>

On RPCS3, this log is printed when trying to display EULA : U cellSysutilNpEula TODO: sceNpEulaCheckEulaStatus(arg1=*0x10001e80, arg2=0x0, arg3=0x0, arg4=0xa93928, callback1=*0x0) , but as you can expect, the check never happens, so client is stuck in an infinite loop : 

https://user-images.githubusercontent.com/119062794/233865915-f3b52887-e842-43d9-a72d-2da3d52be2c5.mp4

As a small tease, fixing this on RPCS3 would allow all Home clients "almost" to go online, "almost", being  the 1.32 version which uses a "Np Title Small Storage", failing too on RPCS3 while working on real hardware.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11304928/RPCS3.log)

### System configuration

Operating System - Windows 11

CPU - Intel Core I9 9900K

GPU - Nvidia RTX 3070 (driver - 526.47)

### Other details

Edit : Don't hesitate to ask me if you need help on reversing this.

Module seems to be CELL_SYSMODULE_SYSUTIL_NP_EULA.

**Comment by Darkhost1999** [comment]
I read that you mentioned the check is stored on the PS3 once it is completed.
I got a question for that.
Is that check something you can transfer to RPCS3 from your PS3?
How does RPCS3 behave with that file transferred? Does it still fail or succeed?
Assuming cause you know that version 1.32 has an issue further down I believe it succeeds. Because that succeeds (from assumption) can we get a log from the emulator where the check was accepted from the PS3?

**Comment by githubalternate55** [comment]
Okay, let me explain more.

1.32 doesn't has this EULA check, this one is unrelated to this topic, this Np EULA was introduced with retail 1.35.

Unfortunately, this is something I don't know yet, and still searching where that is stored, clearly it is in the system and not the game itself.

By tweeking RPCS3 a bit, I got this button to appear with EULA : 
![image](https://user-images.githubusercontent.com/119062794/233867719-51610935-0288-4054-9e2a-e12097f13d85.png)

**Comment by githubalternate55** [comment]
The EULA expected by the game is this : 

<eula npcommid="NPWR00432_00">
  
  <file name="u_pshome-tosua_en.html" version="2" country="us"/>
  <file name="u_pshome-tosua_fr.html" version="2" country="ca" language="2" />
  <file name="u_pshome-tosua_en.html" version="2" country="ca"/>
  
  <file name="j_pshome-tosua_ja.html" version="3" country="jp"/>
  
  <file name="h_pshome-tosua_zhtw.html" version="3" country="hk" language="10" />
  <file name="h_pshome-tosua_zhcn.html" version="3" country="hk" language="11" />
  <file name="h_pshome-tosua_en.html" version="3" country="hk" />
  <file name="h_pshome-tosua_zhtw.html" version="3" country="tw" language="10" />
  <file name="h_pshome-tosua_en.html" version="3" country="tw" />
  <file name="h_pshome-tosua_ko.html" version="3" country="kr" />
  <file name="h_pshome-tosua_en.html" version="3" country="sg" />
  <file name="h_pshome-tosua_en.html" version="3" country="my" />
  <file name="h_pshome-tosua_en.html" version="3" country="id" />
  <file name="h_pshome-tosua_en.html" version="3" country="th" />
  
  <file name="e_pshome-tosua_en.html" version="2" country="gb"/>
  <file name="e_pshome-tosua_en.html" version="2" country="ie"/>
  <file name="e_pshome-tosua_fr.html" version="2" country="be" language="2" />
  <file name="e_pshome-tosua_en.html" version="2" country="be" />
  <file name="e_pshome-tosua_fr.html" version="2" country="lu" language="2" />
  <file name="e_pshome-tosua_de.html" version="2" country="lu" language="4" />
  <file name="e_pshome-tosua_en.html" version="2" country="nl" />
  <file name="e_pshome-tosua_fr.html" version="2" country="fr" />
  <file name="e_pshome-tosua_de.html" version="2" country="de" />
  <file name="e_pshome-tosua_de.html" version="2" country="at" />
  <file name="e_pshome-tosua_de.html" version="2" country="ch" language="4" />
  <file name="e_pshome-tosua_fr.html" version="2" country="ch" language="2" />
  <file name="e_pshome-tosua_it.html" version="2" country="ch" language="5" />
  <file name="e_pshome-tosua_it.html" version="2" country="it" />
  <file name="e_pshome-tosua_en.html" version="2" country="pt" />
  <file name="e_pshome-tosua_en.html" version="2" country="dk" />
  <file name="e_pshome-tosua_en.html" version="2" country="fi" />
  <file name="e_pshome-tosua_en.html" version="2" country="no" />
  <file name="e_pshome-tosua_en.html" version="2" country="se" />
  <file name="e_pshome-tosua_en.html" version="2" country="au" />
  <file name="e_pshome-tosua_en.html" version="2" country="nz" />
  <file name="e_pshome-tosua_es.html" version="2" country="es" />
  <file name="e_pshome-tosua_en.html" version="2" country="ru" />
  <file name="e_pshome-tosua_en.html" version="2" country="ae" />
  <file name="e_pshome-tosua_en.html" version="2" country="za" />
  <file name="e_pshome-tosua_en.html" version="2" country="cz" />
  <file name="e_pshome-tosua_en.html" version="2" country="sa" />
  <file name="e_pshome-tosua_en.html" version="2" country="pl" />
  <file name="e_pshome-tosua_en.html" version="2" country="gr" />
</eula>

**Comment by githubalternate55** [comment]
Some tests were done, and the game will always read the file at the host a1.ww.np.dl.playstation.net. the request is provided by the PS3's OS.

This demonstrate the MOTF (Home related message, tied to the game) layered with system EULA.

![image](https://user-images.githubusercontent.com/119062794/233869142-e2348402-61ab-49a7-8398-68ad601edcd1.png)

**Comment by githubalternate55** [comment]
Sorry to spam this post, but can I get assistance onto debugging RPCS3 using the provided debugger?

I try to do a step-by-step execution, without success.

I tried to put vblank to 1, still way too fast. Essentially, how can I make rpcs3 to go offset-per-offset using the ppu int and debugger?

Thanks in advance to anyone wanting to help me with this, dev builds (which has the EULA check skipped.... go figure why) are already working but retail would allow fast and secure public release.

**Comment by RedEye145** [comment]
I've taken a look at this, you claim that the file is always read from a1.ww.np.dl.playstation.net , Which just says 'Not a File' , Which could be a possible error that the file is deleted, and one of those files may be intefering with the game itself, 

What you could try is dig into the ps3 game's files and try to put that xml file inside, (If there's an "EULA" folder or something along those words try putting that inside)

**Comment by githubalternate55** [comment]
Okay, I went further into the problem, it turns out it's really a RPCS3 HLE and LLE implementation issue for sceNpEulaCheckEulaStatus.

I have done several things : 

- Redirected a1.ww.np.dl.playstation.net to a classic IIS server, which works on PS3 (as remember, we have the files, so not an issue fortunately).

On RPCS3, that URL is never requested. Rather it seems judging by RPCS3 code it is totally skipped, and wrong return value is sent via CELL_OK.

- Reverse engineered the game code to see what is going on, here is the verdict (with my limited knowledge I admit) : 

Game has an initial online booting procedure which is the same across all versions : 

We will call it 
![image](https://user-images.githubusercontent.com/119062794/235293542-d22a6664-2b0a-4136-86ad-162496d41494.png)

In this function,

there is a switch case with all the required steps of an online boot : 

-> medius MUIS -> medius SVO -> medius MLS/DME -> EULA -> Home ready to start.

Case 3 of the switch case is the EULA Check enter function : 

![image](https://user-images.githubusercontent.com/119062794/235293628-7a0198fe-e0a5-4466-9f00-af5dc0d4e238.png)

At this point, RPCS3 still continues until the EnterEULAcheck segment : 

![image](https://user-images.githubusercontent.com/119062794/235293657-587f778d-ea45-486e-9c24-c33f512b3cf9.png)

Once in EnterEULAcheck, it will call the sceNpEulaCheckEulaStatus syscall from PS3 firmware (which checks with game ID the matching EULA, all of this directly IN the firmware)

![image](https://user-images.githubusercontent.com/119062794/235293764-c6c008e2-f98c-4df0-97a8-6ddce92ba9cf.png)

At this point, the uvar1 = 0 on RPCS3. Which is an issue, it should be 2 (succeed command).

**Comment by githubalternate55** [comment]
Okay, this code should maybe fix RPCS3 judging by code: 

error_code sceNpEulaCheckEulaStatus(vm::ptr<sceNpEulaStructUnk0> arg1, u32 arg2, u64 arg3, u32 arg4, vm::ptr<CellSysutilCallback> callback1)
{
	cellSysutilNpEula.todo("sceNpEulaCheckEulaStatus(arg1=*0x%x, arg2=0x%x, arg3=0x%x, arg4=0x%x, callback1=*0x%x)", arg1, arg2, arg3, arg4, callback1);
        if (arg3 == 0)
		return 2;
	if (!arg1)
		return CELL_SYSUTIL_NP_EULA_INVALID_PARAM;
	if (arg4 == 0)
		return CELL_SYSUTIL_NP_EULA_INVALID_PARAM;

	return 2;
}

**Comment by githubalternate55** [comment]
I did an small fork with that func modified, seems like it has an effect, if that works I will pull request : 
![image](https://user-images.githubusercontent.com/119062794/235311389-94157a09-e75c-4932-8211-ba41ac577749.png)

**Comment by githubalternate55** [comment]
Well, it seems now the game gets less far, so maybe it's just after that eulacheck that it dies.

**Comment by githubalternate55** [comment]
Okay, I found out a way to skip the Eula Syscall by modifying the switch case function. Sony coded it in a really bad way that makes skipping part the switch case easy : 

![image](https://user-images.githubusercontent.com/119062794/236005925-39f8664a-ad06-487b-89b3-5968359ee4df.png)

The code is the same accros all Home revisions, perhaps a HLE patch would do the job? I would be happy to be guided onto how making one for a specific code snippet (like PCSX2 live-patching or PINE) so it fixes every Home versions.

And now, time for modern Home all the way up to 1.86 on RPCS3: 

![image](https://user-images.githubusercontent.com/119062794/236006286-b3e4e568-04d8-446f-9399-0c74f10f62f1.png)

Btw, a little bit of a chuck norris moment.

https://user-images.githubusercontent.com/119062794/236006684-ee664df2-4c9a-447e-99fa-b33e1266a44f.mp4

**Comment by Ninetime** [comment]
Does this PR fix the issue? #15011

**Comment by GitHubProUser67** [comment]
Sorry for the late response, but it totally does! 

![image](https://github.com/RPCS3/rpcs3/assets/127040195/aa38462d-3df4-4f23-814c-c20a7f7ce336)

**Comment by GitHubProUser67** [comment]
On an unrelated note, the game will need a MLAA patch tho:

![image](https://github.com/RPCS3/rpcs3/assets/127040195/ef3a5d23-b58e-4465-bb5e-4d76cb39d009)
