### ISSUE TITLE
Resident Evil 6  Graphical issue

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13750]
### Quick summary

I encountered a graphical issue while playing Resident Evil 6.

### Details

The game's graphics suffer from minor artifacting of neon lighting, signs and fire during the boss fight cutscene on jack mission.

Rpcs3
![NPJB90541_screenshot_2023_04_24_16_39_15](https://user-images.githubusercontent.com/71127352/234049639-c90c1bab-cba7-465d-9854-4d06cedc7d02.png)
![NPJB90541_screenshot_2023_02_01_21_12_59](https://user-images.githubusercontent.com/71127352/234049687-a6c6e46a-c6c6-49db-9b46-0a363d003a13.png)

PS3
https://youtu.be/TXRvW4PW8tk

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11312250/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/151F1jtAFWSdUCZfvAQoTlTSAMr4Z4TaJ/view?usp=share_link

### System configuration

RPCS3 v0.0.27-14924-5870dad6 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by Asinin3** [comment]
Did you test settings to see if anything fixes the issue? e.g using 100% res scale. using the buffer options like write color buffers, read color buffers. read depth buffers. And other settings?

**Comment by Triticum0** [comment]
I test most combinations of Buffers together and made no differences and never test above native rendering resolution.

**Comment by kd-11** [comment]
Looks like NaN values to me at a glance. I wonder if they also appear on AMD GPUs.

**Comment by Triticum0** [comment]
@kd-11 This looks like it is the same issue as #13751 It fixed with Strict Rendering mode.

https://github.com/RPCS3/rpcs3/issues/13751#issuecomment-1834630017

**Comment by kd-11** [comment]
Thanks for checking.
