### ISSUE TITLE
wxWidgets Degub alert

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#1375]
when running the game Naruto presents this alert

![error 1 naturo shippuden ultimate](https://cloud.githubusercontent.com/assets/16367065/12004388/e7e1e0dc-ab22-11e5-8d81-4f66cca392a0.png)
![config 1 naturo shippuden ultimate](https://cloud.githubusercontent.com/assets/16367065/12004386/e7c2aac8-ab22-11e5-97bc-f403df43b8cd.png)
![config 2 naturo shippuden ultimate](https://cloud.githubusercontent.com/assets/16367065/12004387/e7da41ba-ab22-11e5-8120-01cec5617e46.png)

LLE Modules:
cellFiber_Library v1.1
cellJpgEnc_Library v1.1
cellPngEnc_Library v1.1
cellSail_Library v1.1
cellSre_Library v1.1

log:
[log naruto.zip](https://github.com/RPCS3/rpcs3/files/72267/log.naruto.zip)

**Comment by AniLeo** [comment]
Could someone check if this is still an issue?

**Comment by Zangetsu38** [comment]
@AniLeo you can close :) fixed ^^
