### ISSUE TITLE
Graphical Issue in Resident Evil Revelations

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13751]
### Quick summary

I encountered a graphical issue while playing Resident Evil 6.

### Details

The game's graphics suffer from minor artefacts when damaged.

Rpcs3
![NPHB00545_screenshot_2023_02_24_21_28_46](https://user-images.githubusercontent.com/71127352/234033614-a664cecf-1d31-4108-b459-db2b53336fbb.png)
![NPHB00545_screenshot_2023_04_24_16_04_29](https://user-images.githubusercontent.com/71127352/234037658-e222d485-4e10-4910-9241-86c65118c00b.png)

Ps3
https://youtu.be/p_Qc9FEWgMc

### Attach a log file

Resident Evil Revelations
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11311782/RPCS3.log.gz)

### Attach capture files for visual issues
[NPHB00545_20230424160354_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/11312372/NPHB00545_20230424160354_capture.rrc.gz)

### System configuration

RPCS3 v0.0.27-14924-5870dad6 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by Asinin3** [comment]
Can you point out what the actual issue is here?

**Comment by FlexBy420** [comment]
I think they meant those squares
![obraz](https://github.com/RPCS3/rpcs3/assets/68403300/bb44ae0b-2c3f-4adf-abb5-b4eba5aeecf4)

**Comment by Triticum0** [comment]
It is the Squares

**Comment by kd-11** [comment]
I can't spot the squares (probably screen calibration issues).
If the squares are what I think they are, openGL should be unaffected. If this is true, attach a renderdoc capture as it means we have a missing barrier somewhere.

**Comment by Triticum0** [comment]
@kd-11 I tested the game on OpenGL and the game is very unstable it seems to freeze when trying to make it up the stairs so can't get a render capture
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12138812/RPCS3.log.gz)

**Comment by Triticum0** [comment]
Yeah, async shader mode causes the game to constantly freeze. using legacy seemed to fix the issue

**Comment by Triticum0** [comment]
I tested on OpenGL and it seems to look even more Severe compared to Vulkan. 
Vulkan

https://github.com/RPCS3/rpcs3/assets/71127352/1a212f79-9466-489d-8127-b18774ff7439

Opengl 

https://github.com/RPCS3/rpcs3/assets/71127352/af865a5d-f08a-46ef-b0e4-ab6c3dcfe69c


Hopefully, it bit more easy to see.

**Comment by Triticum0** [comment]
Here the renderdoc Kd https://drive.google.com/file/d/1yFjDDv03WY1hapfvyG7oPvkOqP2mHaFj/view?usp=sharing

**Comment by kd-11** [comment]
I'm unable to reproduce this one on both NVIDIA and AMD when using default settings.

**Comment by Triticum0** [comment]
@kd-11 I was still able to reproduce the issue.
[Resident Evil: Revelations default + non default setting.log.gz](https://github.com/RPCS3/rpcs3/files/13308582/Resident.Evil.Revelations.default.%2B.non.default.setting.log.gz)

Just make sure you are in an area with lots of light preferably the corridor past the first monster encounter As only really shows up in high-contrast areas or is very hard to see otherwise.
Also, make sure to be very low health so the bug will not appear.

Note: could only affect 30-series cards?

**Comment by kd-11** [comment]
I tested on a 3050. The only thing I did was open configuration settings and reset to defaults. I did make sure to be near death too. I'll attach some screenshots when I circle back to this just in case I'm in the wrong area.

**Comment by kd-11** [comment]
Screenshots from the 3050:
![image](https://github.com/RPCS3/rpcs3/assets/15904127/d53953e2-dbce-4f8f-9c56-e71f838e79d4)
![image](https://github.com/RPCS3/rpcs3/assets/15904127/027ebd3d-0397-4c29-af00-60eb0c238e50)

In truth I'm really bad at spotting small differences like these artifacts, so let me know if they're present. In the RSX capture the squares are there but they're just a screenshot from the affected PC, not an actual render from my GPU.

**Comment by kd-11** [comment]
@Triticum0 You seem to be using non-standard "core" settings which can affect the output. Can you try without relaxed xfloat?

**Comment by Triticum0** [comment]
@kd-11 I did some more testing on the full game option test and have found out that turning on Strict Rendering mode fixes the artifacts. Hopefully, that might shed some light on what the issue is.

All settings I tested seem to not do anything

1.00 and 1.01 don't have any graphical issues.

**Comment by Triticum0** [comment]
@kd-11 Do you want to send any more Captures for Renderdoc as that one above is a couple of months old

**Comment by Triticum0** [comment]
@kd-11 because Strict Rendering mode fixes the artifacts can I close this issue?

**Comment by kd-11** [comment]
> @kd-11 because Strict Rendering mode fixes the artifacts can I close this issue?

Yes. If strict mode fixes it, then we already know about the underlying cause and have a correct way to fix it, it is just too slow.

**Comment by Triticum0** [comment]
Thanks for your help Will ad to wiki now

**Comment by Triticum0** [comment]
Also Should I add anything that you said in your reply in the known issue or should just add the fix?
