### ISSUE TITLE
[Regression] LLVM: glitchy polygons (#10809)

### ISSUE THREAD

**Issue by Toff-kun** [RPCS3/rpcs3#13752]
### Quick summary

LLVM Relaxed or Approximate XFloat cause various models to have glitchy jumping or missing polygons or textures.

### Details

Using LLVM Relaxed or Approximate XFloat causes various models to have glitchy jumping or missing polygons or textures.
LLVM Accurate XFloat or ASMJIT do not cause this issue, no other settings affect this bug.

Observed in Uncharted 1, MGS4, probably other games as well.

In Uncharted 1, the pistol also looks out of place and rotates in a weird way:

![sshot-654](https://user-images.githubusercontent.com/10385850/234055806-b608217d-8b8d-433f-89e6-1fb3332e6eae.png)
![sshot-659](https://user-images.githubusercontent.com/10385850/234056020-5c3f87a9-44a7-4722-9645-51ccf3ada96d.png)

In MGS4 only character model seem to be affected:

![sshot-666](https://user-images.githubusercontent.com/10385850/234056170-ffb000a3-8f2e-406e-b498-5e1a14cf9082.png)

This issue appeared a long time ago, but now that MGS4 finally works with sound on AMD FX CPUs I hope it will be fixed as well.

### Build with regression

v0.0.18-12773-9e62ca56

### Attach two log files

[RPCS3.log.12757.gz](https://github.com/RPCS3/rpcs3/files/11312617/RPCS3.log.12757.gz)
[RPCS3.log.12773.gz](https://github.com/RPCS3/rpcs3/files/11312618/RPCS3.log.12773.gz)
[RPCS3.log.14924.gz](https://github.com/RPCS3/rpcs3/files/11312668/RPCS3.log.14924.gz)

### Attach capture files for visual issues

[https://1drv.ms/u/s!AtHR_Jk5FGg_nPU6cnsYHqk2cibX7Q?e=B4tvbM](url)

### System configuration

OS: Windows 11 Pro (22H2 22621.1555)
CPU: AMD FX-8350
GPU: Nvidia GeForce GTX 970
Driver ver.: 531.68
RAM: 16 GB DDR3

### Other details

Added RSX capture for 12773 build. I can provide it for the latest build if necessary.
Added logs for 12757 (latest working build), 12773 (build that introduced the regression) and the latest 14924 build.

Tell me if you need me to provide any additional information.

**Comment by AniLeo** [comment]
Linking to the PR that regressed it: #10809

**Comment by Toff-kun** [comment]
PR #13723 fixed this for both games when LLVM SPU XFloat Accuracy is set to Approximate XFloat. Relaxed XFloat still causes the same issue, not sure if this is an expected behavior.

**Comment by AniLeo** [comment]
Approximate is the default, even in the older builds, so the issue is fixed
