### ISSUE TITLE
[Task] Improve NVIDIA attribute interpolation

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#13755]
Some time ago, I added improved interpolation for NVIDIA where the third interpolation factor is derived from the other 2 and 1.0. However, this was still not accurate enough and some games like destiny still generated values like 0.99999999999 which failed some compare tests in the fragment shaders.
There is a better way, to just copy what AMD does in hardware, where instead of calculating the final value as a weighted sum, we start at the first attribute and 'walk' to the target using weighted relative vectors. This gets rid of the corner case where all 3 attributes are precisely equal by reducing the input to the fp32 multiply to 0.

External ref: https://github.com/xenia-project/xenia/issues/2012

**Comment by kd-11** [comment]
I already tested this and it seems to work. I'm creating the ticket so I don't forget.

**Comment by jgt11** [comment]
Any need for more testing?

**Comment by kd-11** [comment]
Soon

**Comment by Augusto7743** [comment]
I want help testing ...
That PR does improve attribute interpolation for all or some games ? If "some" which games ?
