### ISSUE TITLE
Graphical issues on MAC Vulkan (MGS4) [BLES00246]

### ISSUE THREAD

**Issue by anatblsv** [RPCS3/rpcs3#13763]
### Quick summary

Hello! Anyone know how fix graphic glitches in RPCS3 on MGS4?

<img width="1278" alt="mgs4-1" src="https://user-images.githubusercontent.com/124677461/234545132-4d034a61-0980-4bf9-af90-ffa1f0d68cd7.png">
<img width="1277" alt="mgs4-2" src="https://user-images.githubusercontent.com/124677461/234545144-cbab2b62-9190-4887-b54c-8598cd7dce59.png">

### Details

I tied different configs from wiki for this game, but still graphic glitches.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11331593/RPCS3.log)

### Attach capture files for visual issues

https://mega.nz/file/MRtGxKxR#eKeEhJNxVmxS2kiZRnX3JZMQwssBOn1qjXeDUPYEOCc

### System configuration

Macbook Pro 2022 16" M1 Max, 32 RAM

RPCS3 0.0.27-14896

**Comment by Mateus109** [comment]
I've got a similar setup to you, (16" M1 Mac 64 GB) and MGS4 runs between 5-45fps, so it's unplayable. Odd because other games run at a smooth locked 60fps.

**Comment by AniLeo** [comment]
This issue is not about performance, it's about graphics. It's expected that MGS4 runs very poorly performance-wise on M1/M2.

Needs retest on latest build because the graphical issue might be fixed by a recent PR.

**Comment by anatblsv** [comment]
> This issue is not about performance, it's about graphics. It's expected that MGS4 runs very poorly performance-wise on M1/M2.
> 
> Needs retest on latest build because the graphical issue might be fixed by a recent PR.

Yes, thanks, i tested now last mac os build and graphical issues fixed!

**Comment by anatblsv** [comment]
> I've got a similar setup to you, (16" M1 Max 64 GB) and MGS4 runs between 5-45fps, so it's unplayable. (Odd because other games run at a smooth locked 60fps.) So, there's various problems with MGS4 on Macs, not just with the graphics.

Hi, I can do something for good performance for this game on mac?

**Comment by AniLeo** [comment]
Closing as solved

If you want to have proper performance on this game you need a high end PC

**Comment by anatblsv** [comment]
> Closing as solved
> 
> If you want to have proper performance on this game you need a high end PC

thanks, but oddly, i have great performance for example silent gill downpour, but MGS4 get stable 4-7 FPS without graphic glitches. Thank you!

**Comment by Mateus109** [comment]
The M1 Max is roughy equivalent to an Intel i9 & RTX 3060, which can run MGS4 at 60fps.  So it's clear the macOS version of RPCS3 simply isn't optimised for Apple Silicon chips yet.  But we're going off topic.

**Comment by Gatsbyred** [comment]
Hello guys 'm trying to install this game but can't success, help please anyone ?
