### ISSUE TITLE
Crash after starting software or installing firmware

### ISSUE THREAD

**Issue by luis0088** [RPCS3/rpcs3#13769]
### Quick summary

Trying RPCS3 for the first time, installed the latest version, with firmware 4.90. I was able to run a game once until the start screen after that the program closed without showing any windows, after that the emulator freezes if I try to fun any software or after reinstalling the firmware.

So far I've tried: 
- Reinstalling everything from scratch
- Restart pc 
- Update drivers

At most I was able to replicate my first crash. Log file is from an attempt to run the PS3 interface.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11337601/RPCS3.log)

### System configuration

CPU: Ryzen 5800x
GPU: RTX 3070
RAM: 32 gb
Driver version: 531.68

**Comment by AniLeo** [comment]
Needs retest with latest RPCS3 version as some UI and CPU regressions were fixed

**Comment by luis0088** [comment]
Tried running again, the issue is still present

**Comment by Asinin3** [comment]
Ask for help in Discord, no other users have reported this so it looks more like an issue on your system rather than with the emulator. I would also checksum check the firmware file to make sure it didn't get corrupted, and use a brand-new RPCS3 folder.

Closing.
