### ISSUE TITLE
[Regression] Rpcs3 displays only PS3 Interface XMV in game lista frer i boot software on  0.0.27-14930

### ISSUE THREAD

**Issue by kotenok2000** [RPCS3/rpcs3#13767]
### Quick summary

 Rpcs3 displays only PS3 Interface XMB in game list when i boot software on 0.0.27-14930
It doesn't happen on 14845

### Details

![image](https://user-images.githubusercontent.com/8822292/234680099-2a454911-183c-4e0c-b066-e14ffb297bc2.png)
![image](https://user-images.githubusercontent.com/8822292/234680778-66747f44-d9f2-4120-8129-82232737f8d4.png)

### Build with regression

0.0.27-14930

### Attach two log files

broken
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11336547/RPCS3.log)
working
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11336554/RPCS3.log)

**Comment by FlexBy420** [comment]
Can reproduce
![obraz](https://user-images.githubusercontent.com/68403300/234685366-f0fcd07f-922a-45e1-af03-11067f3fc7ae.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11336678/RPCS3.log.gz)

**Comment by kotenok2000** [comment]
Probably https://github.com/RPCS3/rpcs3/commit/3f066cca4af5c5fdc38f9364a045331d8aea045f
or https://github.com/RPCS3/rpcs3/commit/a639772dfeabb46abce6a3e7b2bd0d315f532842

**Comment by Megamouse** [comment]
As a quick workaround you can just click the refresh button at the top left.
