### ISSUE TITLE
error skate will install game data to the HDD

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#1376]
when running the game Skate 3 presents this alert

![error 1 skate 3](https://cloud.githubusercontent.com/assets/16367065/12012365/b48f69aa-acbe-11e5-8f12-265970dcde21.png)
![error 2 skate 3](https://cloud.githubusercontent.com/assets/16367065/12012367/c32688c2-acbe-11e5-9ab0-4156791d6864.png)

Config:
![config 1 skate 3](https://cloud.githubusercontent.com/assets/16367065/12012373/03bef13a-acbf-11e5-8a9f-6b7572ce06b6.png)
![config 2 naturo shippuden ultimate](https://cloud.githubusercontent.com/assets/16367065/12012375/08d6a87a-acbf-11e5-9473-22924658992e.png)
LLE MODULES:
cellSpursJq_Library v1.1
cellSre_Library v1.1

**Comment by tambry** [comment]
@mkultimate Please provide the log file. There should also be no need for posting the screenshots of settings, if you give us the log.

**Comment by AniLeo** [comment]
Can someone retest in latest build? 

Also, don't place the disc game inside dev_hdd0/game, specially if the game installs contents to the hard drive, as it may overwrite itself if the path is the same

**Comment by darkredflame** [comment]
@AniLeo  This game still gives the same dialog prompt. If you try to install the gamedata it will error out.

![rpcs3_2017-03-19_12-42-10](https://cloud.githubusercontent.com/assets/12888227/24083687/920c7e7e-0ca1-11e7-8174-c4e95a075a39.png)
![rpcs3_2017-03-19_12-42-00](https://cloud.githubusercontent.com/assets/12888227/24083688/920da9ac-0ca1-11e7-9de3-2eef589871a9.png)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/853446/RPCS3.zip)

**Comment by scribam** [comment]
@mkultimate @darkredflame According to http://www.emunewz.net/forum/showthread.php?tid=192174, this game should now be able to go ingame. Would you mind checking if it is also your case?

**Comment by mchtt** [comment]
yes it goes ingame, me and several other players were able to play it, logs included on the emunews thread.

**Comment by scribam** [comment]
@AniLeo What do you think? Can we close this issue?
