### ISSUE TITLE
PvZ : I can't even play XD

### ISSUE THREAD

**Issue by JoaquinClarosGaming** [RPCS3/rpcs3#13779]
### Quick summary

when i try to play PvZ brings me this error : F {RSX [0x0000000]} SIG: Thread terminated due to fatal error: Could not bind OpenGL context
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\rpcs3qt\gl_gs_frame.cpp:77[:24], in function set_current) (error=0x7e), i'm new in this and i don't know what to do

### Details

its only that

### Attach a log file

![image](https://user-images.githubusercontent.com/102455395/235242361-9915f9fe-ccf7-4f25-88fb-32e556bf5b7c.png)

**Comment by FlexBy420** [comment]
That's because you are below minimum requirements
