### ISSUE TITLE
[Regression] Ratchet and clank ToD

### ISSUE THREAD

**Issue by kyotakuu** [RPCS3/rpcs3#13772]
### Quick summary

Since the new version of march, ratchet and clank tools of destruction crash after the first cutseen. tested with canary patch and on 2 device (steamdeck and windows 11 device) same problem on both device. but work fine on the rpcs3 version of january 2023

### Build with regression

0.0.27-14931

### Attach two log files

send in the discord. alredy delete the new version

**Comment by solarmystic** [comment]
Cannot reproduce this on the latest master (14931) using Windows on a 12700KF/2080TI system. Anyway, please fill up the rest of your issue report, this is incomplete until you do. 

![image](https://user-images.githubusercontent.com/4345150/234730223-f211f664-e2de-489a-a5db-7f1cac4ac69f.png)
