### ISSUE TITLE
[Regression] Resistance: Fall of Man BCUS98107 (#9760)

### ISSUE THREAD

**Issue by Zanot32** [RPCS3/rpcs3#13775]
### Quick summary

When on the loading screen for the mission with the mission name, the star rotates twice in the chevron and CTDs instead of loading the game

### Build with regression

v0.0.19-13082-e3e39e8d

### Attach two log files

Broken:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11338753/RPCS3.log)
Working:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11338783/RPCS3.log)

### System configuration

OS: Win10
CPU: Ryzen 5-3600
GPU: Sapphire RX470 8GB
All drivers updated

**Comment by AniLeo** [comment]
If the build is the one flagged it would make it introduced by #9760

**Comment by Zanot32** [comment]
That is correct, yes, sorry for late reply, I was at work

**Comment by AniLeo** [comment]
@jeremybris Do you confirm that this issue was fixed when you tested PR 13807? You mentioned the PR in your comment but I'm not sure if it meant that it was still affected by this issue or if it was now fixed

**Comment by AniLeo** [comment]
Still needs a retest

**Comment by jeremybris** [comment]
Randomly stumbled on this. Never got pinged. Can confirm this issue is fixed, for me, with Resistance 1 (rebuilt caches). I went back and tested the regression from v0.0.27-14846, to make sure.

**Comment by AniLeo** [comment]
Closing as fixed, thanks for verifying
