### ISSUE TITLE
Ps3 Porting issues

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13781]
### Quick summary

Some porting or hardware issues cause different presentation of graphics compared to Xbox and pc

### Details

When testing lots of games I ran some issues which are present on the hardware but are missing or less serve on other consoles(Xbox and pc). post them here for now if you want the issue moved then I can move them to the wiki.
Game | Issue | Behaviour  | Other ports
-- | -- | -- | -- 
Blacksite: Area 51 | The game exhibits graphical flickering on some rock faces shadow in mission topside | [Ps3](https://youtu.be/qLnRkBtNsLk?t=8790) | [Xbox](https://youtu.be/cIuJdU6WHIA?t=10461) [PC ](https://youtu.be/nPsfgp82y-I?t=7119)
Kane & Lynch: Dead Men | The game has banding lines on the top corner of the roof which only happens on the ps3 | [Ps3](https://youtu.be/absB6XvDnKk?t=183) | [Xbox ](https://youtu.be/-owPBdSUPdE?list=PLY0FyX0DOM7eO6a-KZWrZ9ZSPMmLo1ycg&t=229) [PC](https://youtu.be/ihMrn8UYpYs?t=173)

**Comment by Darkhost1999** [comment]
So this isn't an rpcs3 issue but just graphics comparisons noting issues that are normal on ps3?

**Comment by AniLeo** [comment]
Please open a RPCS3 Wiki page for these instead

**Comment by Triticum0** [comment]
@AniLeo Do you want me to post the issues in their respective wiki pages under special notes or do you want me to make a new page only about platform differences?

**Comment by Asinin3** [comment]
Just do it under the special notes page for the games if you want to.

**Comment by Triticum0** [comment]
Does the wiki have the ability to embed videos?
