### ISSUE TITLE
Audio crackles before breaking completely GTA San Andreas

### ISSUE THREAD

**Issue by IJustGonnaGo** [RPCS3/rpcs3#13787]
### Quick summary

Whenever I go into the garage or a pay n spray in the ps3 version of San Andreas, the audio crackles before cutting out, it sounds like it has stopped completely, but shows as a really loud audio in sound mixer in windows. Any idea as to how to fix it?

### Details

No matter at what point or or things that are going on will the garage/paynspray audio work. They can fail as soon as you load in and go to the garage, or they can fail as soon during a mission. Audio fails once you enter too far in, but works fine if the vehicle was already there (you put it in, audio fails, save game and then come back). This only happens when entering with a vehicle.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11360183/RPCS3.log)

### System configuration

Nvidia GTX 1050, Intel i7-7700, 16 gb ram, geforce game ready driver version 531.68, windows 10

**Comment by Asinin3** [comment]
>it sounds like it has stopped completely, but shows as a really loud audio in sound mixer in windows.

Are you sure this isn't an issue with your speakers/headset? If audio is still showing in windows mixer, then it should still be being output. I'm closing this as it doesn't seem like a RPCS3 issue. Re-open if needed.

**Comment by FlexBy420** [comment]
It's a game bug, not emulation issue.

**Comment by Margen67** [comment]
#7129

**Comment by skibidi9908** [comment]
Why has this been closed it is still an issue with the actual game
