### ISSUE TITLE
The XMB interface gets stuck when "Compiling PPU modules"

### ISSUE THREAD

**Issue by ahmedhakim786** [RPCS3/rpcs3#13780]
### Quick summary

The XMB interface gets stuck when "Compiling PPU modules"

### Details

MacBook Air 2017
- SYS: RPCS3 v0.0.27-14944-7bec3b30 Alpha | master
- SYS: Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz | 4 Threads | 8.00 GiB RAM | TSC: 1.800GHz | AVX+ | FMA3 | TSX disabled by default
- SYS: Operating system: macOS, Version: 12.6.3
- SYS: Current Time: 2023-04-28T21:10:03
- RSX: Found vulkan-compatible GPU: 'Intel(R) Iris(TM) Graphics 6000' running on driver 0.2.987
- SYS: Firmware version: 4.90

F {RSX [0x040204c]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Requested feature not available (VK_ERROR_FEATURE_NOT_PRESENT)
(in file /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/image.cpp:392[:67], in function create_impl) (errno=316=Unknown error: 316)
(in file /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107[:4], in function die_with_error) (errno=22=Invalid argument)

Frozen screenshot
![Screenshot 2023-04-28 at 9 09 07 pm](https://user-images.githubusercontent.com/99324733/235244004-98e6ceb6-948b-434b-8af0-1ef845d87eb5.png)

The app refuses to respond making me force quit the app. If anyone could help me with this, it would be greatly appreciated.

### Attach a log file

cannot find log file?

**Comment by YuriNator557** [comment]
Below minimum specs, invalid issue

**Comment by Filthy420** [comment]
The support on this app is pretty bad. I've searched dozens of these entries and the lead devs need to be less rude. Honestly Idk what makes them so mad. But almost every error is responded to by "below specs" go get a new computer, which is a pretty pathetic way to respond. I have gotten alot of software to work on older computers and this should work if they implemented everything correctly. I think it had more to do with their bloated code and unintelligible error messages. 
Its a nice program if it worked

**Comment by elad335** [comment]
You GPU does not support the needed features for RPCS3, it may work with OpenGL buy I can't promise that

**Comment by AniLeo** [comment]
The issue tracker is not for support.
