### ISSUE TITLE
Creating save states for some games crashes RPCS3

### ISSUE THREAD

**Issue by Jillificent** [RPCS3/rpcs3#13785]
### Quick summary

I tried to create a save state with five games, and only one was able to create/load save states successfully.

### Details

At first I thought creating any save states crashed RPCS3 for me, but I tried Nier and it sucessfully created and loaded a save state. I have never tried to use save states with any other version of RPCS3 so I don't know if this was working on a different version. Of the five games I tested, three of them were HDD games, and two were disc games. Nier, the only game that created/loaded save states successfully, is a disc game.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11359688/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11359699/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11359708/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11359735/RPCS3.log)

Game that created/loaded save states sucessfully:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11359750/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11359767/RPCS3.log)
(although it did crash when I tried to exit the emulator)

**Comment by Jillificent** [comment]
I thought that maybe using network/hdd games might be the issue, so I tried the disc version of Drakengard 3 but it still crashed on savestate creation.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11359796/RPCS3.log)

**Comment by Mrlinkwii** [comment]
can this be rechecked on the latest release

**Comment by elad335** [comment]
Probably outdated & fixed, closing. Open a new issue if persists.

**Comment by vampiregoat699** [comment]
it still persists with latest version

**Comment by Darkhost1999** [comment]
Create a new regression report. This issue was initially created 2 years ago and the problem that was creating the issue 2 years ago was solved and is still solved.
The current issue has a different causation.
