### ISSUE TITLE
Ratchet and clank: crack in future problem

### ISSUE THREAD

**Issue by elmisterio26** [RPCS3/rpcs3#13783]
### Quick summary

hi! when i am playing the game crashed 

### Details

It happens sometimes, but here is a planet (axion city ) where it always happens at all times, every few minutes the game pauses and I see the next error ( there are 3 errors) 
1:(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\sync.cpp:220[:5], in function wait_for_event)
2:F {RSX [0x1f5165c]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
3:(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error)
i want to play full game but is imposible if can be solved i will want it
My pc : 
GTX 1050, 8GB ram, 2 TB space, intel i5-8400

### Attach a log file

![image](https://user-images.githubusercontent.com/132131155/235294407-9f6b67fa-f06c-4543-aebd-2efb20f6ac46.png)

**Comment by YuriNator557** [comment]
This reads like a support request instead of a bug report, ask in the appropriate support channels i.e. the Discord server or the forums

**Comment by elmisterio26** [comment]
> This reads like a support request instead of a bug report, ask in the appropriate support channels i.e. the Discord server or the forums

what is the discord chanel for suport?

**Comment by Asinin3** [comment]
Obviously the channel labelled # help
