### ISSUE TITLE
Terraria [BLUS31537] Freeze

### ISSUE THREAD

**Issue by Tstringer05** [RPCS3/rpcs3#13793]
### Quick summary

The game loads fine and gets through character and world creation, but then the audio cuts out and a few seconds later the entire game freezes. It used to be playable but now this is what comes up:
E cellSaveData: cellSaveDataUserAutoLoad(version=1, userId=1, dirName=“NPUB30943-AUTO12345678901234567”, errDialog=0, setBuf=*0xd024bb90, funcStat=*0x8e6208, funcFile=*0x8e61b0, container=0xffffffff, userdata=*0x39650e30)
E cellSaveData: cellSaveDataUserAutoSave(version=1, userId=1, dirName=“NPUB30943-AUTO12345678901234567”, errDialog=0, setBuf=*0xd024bcc0, funcStat=*0x8e6168, funcFile=*0x8e6140, container=0xffffffff, userdata=*0x3676e640)
E cellSaveData: cellSaveDataUserAutoLoad(version=1, userId=1, dirName=“NPUB30943-AUTO12345678901234567”, errDialog=0, setBuf=*0xd024bc50, funcStat=*0x8e61a8, funcFile=*0x8e61b8, container=0xffffffff, userdata=*0x3676e7d0)

### Details

![Screenshot 2023-04-30 154515](https://user-images.githubusercontent.com/132226829/235373060-1144b41a-78ab-4b4d-9af2-3a5b470cd7c6.png)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11362178/RPCS3.log)

### System configuration

Device name	LAPTOP-1KK2I3O0
Processor	11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz   2.69 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	10282832-2038-4E39-AC93-B02BE1B2C220
Product ID	00325-97263-82378-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by AniLeo** [comment]
Invalid report as the emulator is placed in special permissions directory "Program Files (x86)" which is known to cause these types of fs issues

Need information: Needs retest with the emulator placed in a normal directory

**Comment by Tstringer05** [comment]
I did not have it in 86 but in my downloads. I will fix the folder and try again soon.

**Comment by Asinin3** [comment]
Your Nvidia Driver is ancient, update it immediately if you haven't already. And yes your emulator IS in your program files folder:
`C:\Program Files (x86)\Razer Chroma SDK\logs\EM2\rpcs3-0.0.27-14783-win64\rpcs3.exe`

Closing, user didn't update, and bad setup/file permissions.
