### ISSUE TITLE
Linux version appimage not being mounted ... RPCS3 not start

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#13795]
### Quick summary

Hello.
Ubuntu 20.04.6
When trying load rpcs3-v0.0.27-14954-0524f4a5_linux64.AppImage not start RPCS3.
Seeing in /tmp the appimage not being mounted.
Here others softwares in format appimage load correctly and are mounted in /tmp.
How is being an bug report require an log file, but no any log was created.
I have uploaded an empty log file.
Have an nice week.

### Attach a log file

[1.log](https://github.com/RPCS3/rpcs3/files/11366533/1.log)

**Comment by qurious-pixel** [comment]
need to install `g++-11`

**Comment by Augusto7743** [comment]
@qurious-pixel

Thanks for replying with that information fixing the issue.
Installed g++-11 in Ubuntu 20.04.6 LTS.
Now starting RPCS3.

Linux users using LTS need information about requirement g++-11.

Have an nice week.

**Comment by Augusto7743** [comment]
Thanks Megamouse
