### ISSUE TITLE
Question about RSX Fragment program : is dst.end really the end of a program ?

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1380]
Some of my testing seems to hint that fragment program data may extends past the last instruction.

In DBZ: Burst Limits there's frequently pair of vertex and fragment shaders with missing diffuse_color varying. The output attrib mask is also no set in such case.
Of course using a 0 value for diffuse color only produce a black screen for the concerned draw call. But using a 1 value seems not to work everywhere (and break SH3).

An interesting discovery is that the command queue is issuing some 2D commands in the vicinity of the fragment shaders memory location.

In DBZ select stage screen there is this kind of pattern :

CELL_GCM_NV3062_SET_OFFSET_DESTIN : 0x00740240
CELL_GCM_NV3062_SET_COLOR_FORMAT : 0x0000000b
CELL_GCM_NV3062_SET_PITCH : 0x10001000
CELL_GCM_NV308A_POINT : 0x00000008
CELL_GCM_NV308A_SIZE_OUT : 0x00010004
CELL_GCM_NV308A_SIZE_IN : 0x00010004
CELL_GCM_NV308A_COLOR : 0x00004100
unknown/illegal method [0x00002901] : 0x00000000
unknown/illegal method [0x00002902] : 0x00000000
unknown/illegal method [0x00002903] : 0x00003f80

[Some sequences of CELL_GCM_NV4097_SET_TRANSFORM_PROGRAM_LOAD/ CELL_GCM_NV4097_SET_TRANSFORM_PROGRAM calls]...

Transform program enabled inputs:in_pos in_tc0 
CELL_GCM_NV4097_SET_TRANSFORM_TIMEOUT : 0x0020ffff
CELL_GCM_NV4097_SET_SHADER_PROGRAM : 0x00740241
Transform program outputs:point_size tc0 
CELL_GCM_NV4097_SET_TEX_COORD_CONTROL : 0x00000000

That is, a fragment shader is located at 0x00740241 but just before being set, there's a write at 0x00740240 + 8 * 4. Given the fact that the fragment is 2 instructions bigs (ie 8 bytes length) it means that the command writes 3 bytes after the end of the fragment which is maybe no coincidence (btw 0x00003f80 is the float value 1.0f).
I suspect that the data after fragment shader may hold some input tables. Unfortunatly they are quite opaque for me now.

Can someone have a look at this ?

**Comment by DHrpcs3** [comment]
dst.end is end of program, but last instruction can use constant argument (that should be stored in the next slot)

**Comment by vlj** [comment]
Thanks ! I found what's happening. The command queue was indeed writing to the fragment constant of the last instruction.

The issue is that FragmentDecompiler didn't consider last instruction input as a fragment constant but as a fragment input. The reg_type was 1 and not 2, but the vertex corresponding output was disabled by output mask.
Actually it looks like if a vertex output/fragment input is disabled then rsx fallbacks to a constant fetch. And indeed with this fix I have correct intro color in DBZ. Even better in SH3 the depth of field effect is now available !

**Comment by danilaml** [comment]
@vlj could this issue be closed?

**Comment by vlj** [comment]
yes

**Comment by vlj** [comment]
Reopening, in Super Puzzle Fight super puzzle fighter ii turbo hd fragment shader #4 is missing some instructions. A workaround to ignore dst.end the first time it appears makes the sprite correct.

**Comment by tambry** [comment]
@vlj Seems like you didn't actually reopen the issue. Reopening for you.

**Comment by DHrpcs3** [comment]
Check first instruction with dst.end, that can be a constant. Probably prev instruction use constant argument, but emulator does not handle it.

**Comment by vlj** [comment]
Closing since it was not good diagnostic for SPFIITH
