### ISSUE TITLE
AVX512 Windows 8.1

### ISSUE THREAD

**Issue by TeamVista8** [RPCS3/rpcs3#13809]
### Quick summary

AVX512 setting greyed out rpcs3 windows 8.1.

### Details

Windows 8.1 fully updated, Rpcs3 fully updated, cpu fully supports AVX512, AVX512 setting is greyed out in windows 8.1 but not in windows 10.

### Attach a log file

N/A

**Comment by AniLeo** [comment]
Full Width checkbox uses utils::has_avx512() as the condition for being enabled or not, and there's no code specific to any windows version

https://github.com/RPCS3/rpcs3/blob/b86ecf7441ae356d45c5124ecafc46c751b727d1/rpcs3/util/sysinfo.cpp#L147

Either way, not only is the issue incomplete, but also support for these older versions of Windows will go away soon, so there's no use in keeping track of this if it's working properly in Windows 10 and Linux distros.

**Comment by TeamVista8** [comment]
Do i have to change it in cpp file then recompile rpcs3 or is there a way to change it without recompile?On May 5, 2023, at 14:45, Ani ***@***.***> wrote:﻿
Full Width checkbox uses utils::has_avx512() as the condition for being enabled or not, and there's no code specific to any windows version
https://github.com/RPCS3/rpcs3/blob/b86ecf7441ae356d45c5124ecafc46c751b727d1/rpcs3/util/sysinfo.cpp#L147
Either way, not only is the issue incomplete, but also support for these older versions of Windows will go away soon, so there's no use in keeping track of this if it's working properly in Windows 10 and Linux distros.

**Comment by AniLeo** [comment]
There's nothing to change, it's not our bug

**Comment by Nekotekina** [comment]
Windows 8.1 doesn't enable AVX-512.
