### ISSUE TITLE
Gray screen

### ISSUE THREAD

**Issue by Dualchaos** [RPCS3/rpcs3#13806]
### Quick summary

I am trying to play the original little big planet but when I start the game all I see is a gray screen but I can hear the audio playing.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11401906/RPCS3.log)

### System configuration

I have Vulcan off since it doesn't work on my Mac

**Comment by RainbowCookie32** [comment]
You are using Null renderer, and I'm pretty sure you are under minimum requirements anyways.

**Comment by MSuih** [comment]
If you disable Vulkan on Mac then there's no way to render anything on the screen. There's no bug involved with this, we don't support other renderers on that platform.
