### ISSUE TITLE
Ratchet and Clank Quest for Booty crash on rpcs3

### ISSUE THREAD

**Issue by benzoahoj** [RPCS3/rpcs3#13803]
### Quick summary

Game and emulator crashes before going ingame (menu in game is working).

### Attach a log file

[NPEA00088-RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11383720/NPEA00088-RPCS3.log.gz)

**Comment by FlexBy420** [comment]
From the log you are using a 3 years old build. Update rpcs3 first

**Comment by MSuih** [comment]
We do not give support for builds this old
