### ISSUE TITLE
Ratchet & Clank Tools of Destruction black screen

### ISSUE THREAD

**Issue by benzoahoj** [RPCS3/rpcs3#13814]
### Quick summary

Ratchet & Clank Tools of Destruction black screen after loadnig; can't load even main menu. 

### Attach a log file

[RPCS3_log.zip](https://github.com/RPCS3/rpcs3/files/11412758/RPCS3_log.zip)

**Comment by YuriNator557** [comment]
This reads as a support request, also this log file is empty
Ask this in the correct support channels, i.e. in the Discord server or on the forums
