### ISSUE TITLE
Graphic bugs in Super Frog [NPEB01316] 

### ISSUE THREAD

**Issue by Altaiar** [RPCS3/rpcs3#1381]
First time 
show menu and intro all buttons work and graphic is glitches
log:  https://www.mediafire.com/?b7grulua2v2959l
Second time
it just show a logo and hang(my mean is emulator work but do`nt go further)
and when i remove save data and start again show menu and intro..... like first time
i think there is a problem with save data 
Second time log : https://www.mediafire.com/?9j6s8edhcg7u7bc
pic from graphic : 
![git](https://cloud.githubusercontent.com/assets/12981994/12025160/0ee2df10-adc1-11e5-9008-3eff4ffb5b75.PNG)

**Comment by tambry** [comment]
@Altaiar Have the graphics improved?

**Comment by Altaiar** [comment]
Dx12 Hang after show logos or in menu when press button and graphic is glitches
OPENGL like before graphic is glitches
and still i must remove save data for go in game after first time
DX12 log 
https://www.mediafire.com/?mmo55vgxweovdv9

**Comment by Altaiar** [comment]
In OGL i Get 60fps in this build rpcs3-ReleaseLLVM-7c1ab472
but still graphic is glitches log 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/211347/RPCS3.zip)
in Dx12 i get 7-8 fps and freeze after pressing X Log:
[DX12RPCS3.zip](https://github.com/RPCS3/rpcs3/files/211350/DX12RPCS3.zip)

**Comment by AniLeo** [comment]
Can someone check if this is still an issue?

**Comment by SakataGintokiYT** [comment]
@AniLeo 

**'sysnet issue'**

```
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_net.cpp:196)
E {PPU[0x1000004] Thread (JoystickThread) [0x00381a58]} libnet: recvfrom(): error 0
```

```
Fatal error
Unhandled Win32 exception 0xC0000005.
Segfault writing location 00000000075d6040 at 00000000004e10c0.
Instruction address: 00000000004e10c0.
Function address: 00000000004e1079 (base+0x4d1079).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

```

[Log:](https://gist.github.com/SakataGintokiYT/6c2613f2762f7b098f10185347896f38)

<img src="http://www.fotoszok.pl/upload/49c14187.png" alt="Fotoszok.pl" />

**Comment by AniLeo** [comment]
Can someone retest? Make sure to check SPU Precise as well

**Comment by twdarkeh** [comment]
http://puu.sh/vlwuL.jpg SPU Recompiler

http://puu.sh/vlwGT.jpg SPU Precise
