### ISSUE TITLE
[Regression] cars 2 green,red or blue error in 0.027-14979-5c0113ce Alpha

### ISSUE THREAD

**Issue by awexstudio** [RPCS3/rpcs3#13818]
### Quick summary

green,red or blue squares around cars in cars 2

### Details

i updated today as i wanted to play cars 2, i updated to 0.027-14979-5c0113ce Alpha and the cars has this green error on it i restarted the game and got blue and red squares to, before this i remember changing the shader mode from Async to Async wth shader interpreter
![U
![BLES01242_screenshot_2023_05_06_20_27_30](https://user-images.githubusercontent.com/132783218/236643621-038181d7-ec9f-4d05-9a55-fc9fdf8c090b.png)
ploading BLES01242_screenshot_2023_05_06_20_27_17.png…]()
![BLES01242_screenshot_2023_05_06_20_27_57](https://user-images.githubusercontent.com/132783218/236643622-b2864ec9-e2bc-4eff-870d-6d1cd489191a.png)
![BLES01242_screenshot_2023_05_06_20_27_37](https://user-images.githubusercontent.com/132783218/236643623-6e457317-460b-4d04-88a3-dbb9b7ce8c36.png)
![BLES01242_screenshot_2023_05_06_16_56_17](https://user-images.githubusercontent.com/132783218/236643624-cc45e00f-8e0f-4193-975a-6096eb6366d2.png)
![BLES01242_screenshot_2023_05_06_16_58_26](https://user-images.githubusercontent.com/132783218/236643627-e9e3efb2-523a-4898-8065-3c085f3fc613.png)
![BLES01242_screenshot_2023_05_06_20_27_45](https://user-images.githubusercontent.com/132783218/236643628-5c2405e0-9a67-4901-b2a2-aa78fefa3007.png)
![BLES01242_screenshot_2023_05_06_20_27_48](https://user-images.githubusercontent.com/132783218/236643629-ad02d75d-6749-4313-aca0-d18f432a9beb.png)
![BLES01242_screenshot_2023_05_06_20_44_11](https://user-images.githubusercontent.com/132783218/236643831-4d52c69f-51e0-45c3-8994-aee6655ed9f6.png)
![Uploading B
![BLES01242_screenshot_2023_05_06_20_42_58](https://user-images.githubusercontent.com/132783218/236643833-76e9f2fa-ddcb-4212-baa4-50f245b70a1c.png)
![BLES01242_screenshot_2023_05_06_20_44_19](https://user-images.githubusercontent.com/132783218/236643834-ddd20a76-0723-499a-ba2b-5e87600a4ea9.png)
![BLES01242_screenshot_2023_05_06_20_44_21](https://user-images.githubusercontent.com/132783218/236643835-0a449ae2-bc73-4e46-be8a-17facbb361ee.png)
![BLES01242_screenshot_2023_05_06_20_44_23](https://user-images.githubusercontent.com/132783218/236643836-d66e6d7a-69a5-4873-9413-1d6a2427b120.png)
![BLES01242_screenshot_2023_05_06_20_43_08](https://user-images.githubusercontent.com/132783218/236643837-e4f56329-0748-4e60-9627-5aab48e3bb83.png)
![BLES01242_screenshot_2023_05_06_20_43_10](https://user-images.githubusercontent.com/132783218/236643838-1c409770-2a34-4067-adcc-078c1cdcac4e.png)
![BLES01242_screenshot_2023_05_06_20_43_12](https://user-images.githubusercontent.com/132783218/236643840-2534f666-3e48-4c0b-9762-9b51950cddbc.png)
![BLES01242_screenshot_2023_05_06_20_44_06](https://user-images.githubusercontent.com/132783218/236643841-fcc84d82-7d66-433b-be55-b8c8aea3ebd7.png)
LES01242_screenshot_2023_05_06_20_44_17.png…]()

### Build with regression

v0.027-14979-5c0113ce Alpha

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11413267/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11413268/RPCS3.log)

### System configuration

![image](https://user-images.githubusercontent.com/132783218/236643958-0064543b-b5e5-414a-96ec-8f2e50ff1828.png)
![image](https://user-images.githubusercontent.com/132783218/236643962-462aeedb-3ac5-4da8-90dd-1f26a4397577.png)
![image](https://user-images.githubusercontent.com/132783218/236643970-2a073ee9-b0d3-402e-8b36-22feb504a5e3.png)
![image](https://user-images.githubusercontent.com/132783218/236643975-c94886fc-55a9-4b80-ad9e-305995234fec.png)

### Other details

it stopped after i closed and open the game 3 times in a row

**Comment by awexstudio** [comment]
![BLES01242_screenshot_2023_05_06_20_44_23](https://user-images.githubusercontent.com/132783218/236644604-a8e068ed-8250-4995-8fd5-d60f8dfd8caa.png)
![BLES01242_screenshot_2023_05_06_20_44_17](https://user-images.githubusercontent.com/132783
![BLES01242_screenshot_2023_05_06_20_42_58](https://user-images.githubusercontent.com/132783218/236644624-459a99c0-0bcf-4a73-a8f7-60d4184ddd97.png)
![BLES01242_screenshot_2023_05_06_20_44_06](https://user-images.githubusercontent.com/132783218/236644621-71b63510-cda3-422c-bbef-30609a4fb09d.png)
218/236644606-bdb85561-73fc-4ed3-984d-bfcb577fde7c.png)
![BLES01242_screenshot_2023_05_06_20_44_19](htt
![BLES01242_screenshot_2023_05_06_20_44_11](https://user-images.githubusercontent.com/132783218/236644615-6332ee47-27a3-47a6-ae09-2d5a2bb3670a.png)
![BLES01242_screenshot_2023_05_06_20_43_08](https://user-images.githubusercontent.com/132783218/236644617-c4b3c1f4-c10c-4bb0-ab5d-4a99df533196.png)
![BLES01242_screenshot_2023_05_06_20_43_10](https://user-images.githubusercontent.com/132783218/236644618-a402f2b5-5f8f-4fd9-8fe8-87a145d7f3e4.png)
![BLES01242_screenshot_2023_05_06_20_43_12](https://user-images.githubusercontent.com/132783218/236644620-014f7535-ef43-4b8e-810f-bf6a5e1e0d88.png)
ps://user-images.githubusercontent.com/132783218/236644609-d5789b40-d690-4031-8512-0df83c276b7a.png)
![BLES01242_screenshot_2023_05_06_20_44_21](https://user-images.githubusercontent.com/132783218/236644611-6c440924-7763-4a44-a1a0-7fdc46933235.png)

**Comment by kd-11** [comment]
This is not actionable in the current state.
1. The title says it is a regression, but there is no mention of when things stopped working.
2. The description says "it stopped after i closed and open the game 3 times in a row" - what does this mean? The bug went away after restarting 3 times and it started working correctly?
3. There is mention of changing the shader mode, but no concrete statements made. Did changing the options make things better or worse? What happens if you use the legacy shader compiler? etc.
4. There are a ton of screenshots but 0 context given. I don't even know if they came from rpcs3 or a ps3. Build numbers are not visible or otherwise stated along with the images.

**Comment by awexstudio** [comment]
I’m sorry, I followed what someone said and Thay said to list it as a regression
The bug did fix after I opened and reclosed 3 time in a row yes then started working correctly 
Changeing the setting after I changed it to Async shader interpreter no setting fixed it
The images came from RPCS3 and Thay are just images of the glitch I got
I’m sorry if I didn’t add enough detail I have just started emulating like a week ago and this is my first report

**Comment by kd-11** [comment]
If the bug is not there with the "legacy/single-threaded" shader compiler, then the ticket can be closed. async shader interpreter and async recompiler both are expected to introduce some visual issues in some games. The fact that it went away after a few reboots means its likely a caching issue which the legacy recompiler does not suffer from.

**Comment by emirberksavlik-lab** [comment]
#/ # @awexstudio
