### ISSUE TITLE
[BLUS30412] Smackdown vs Raw 2010 Shadows not rendering correctly during entrances

### ISSUE THREAD

**Issue by Joshking07** [RPCS3/rpcs3#13820]
### Quick summary

During entrances shadows are not displayed correctly both on Vulkan and OpenGL

### Details

**Real PS3**
![Real PS3](https://user-images.githubusercontent.com/119447132/236647819-8dd4eb19-eb8f-48bd-960c-c609b95cb7b9.png)

**RPCS3**
![RPCS3](https://user-images.githubusercontent.com/119447132/236648239-62a51ec5-8e96-4565-a7dc-efea07239408.png)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11413459/RPCS3.log.gz)

### Attach capture files for visual issues

**RSX Capture**
https://mega.nz/file/oLc2EaLI#5aH5z8lSwoA3M4elLZj30plClFoNf_hcMVdSDBPzV9I

### System configuration

RPCS3 v0.0.27-14980-195de818 Alpha | master

OS - Windows 11

CPU - AMD Ryzen 5 5600X 6-Core Processor  3.70 GHz

GPU - Nvidia RTX 3070

**Comment by Asinin3** [comment]
Bad settings:
CPU BLIT is disabled, THIS IS A DEBUG SETTING
Vertex Cache is disabled - This can cause issues
Anti-Aliasing is disabled - some games require it to render certain things properly, dont raise issues with it off.
Resolution Scaling was increased - This setting is technically a hack and can cause issues, we don't support raising visual issues with it enabled.

Also.. Use Vulkan, not OpenGL. OpenGL runs much worse.

Retest.

**Comment by Joshking07** [comment]
Retested. The issue still occurs on Vulkan with RPCS3 on default settings. So it's not the settings. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12157744/RPCS3.log.gz)
