### ISSUE TITLE
[Regression] Watch Dogs - Invisible graphics after the update (#13723)

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#13824]
### Quick summary

Before the update, everything seems totally fine, but for some reason, one of the graphics goes invisible when updating the RPCS3 PR #13723.

### Details

14978 Build: Before
![Before](https://user-images.githubusercontent.com/125112932/236686236-54c72c57-b9ef-4a2b-a88a-a4b6f4b5ba91.PNG)

14979 Build: After
![After](https://user-images.githubusercontent.com/125112932/236686468-6b78d206-2920-4153-86e2-e05f41c4df1b.PNG)

### Build with regression

v0.0.27-14979-5c0113ce

### Attach two log files

Working (14978 Build):
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11415321/RPCS3.log.gz)

Not working (14979 Build):
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11415332/RPCS3.log.gz)

### Attach capture files for visual issues

14978: https://mega.nz/folder/xS5mEbzY#e0ZeXO5arNLceAdYrxwU-g
14979: https://mega.nz/folder/wbZkja7a#CCbsPCHSGZfGtsqu9kMOmg

### System configuration

AMD Ryzen 9 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 531.79.0.0 | Windows 10 Pro 22H2

**Comment by kd-11** [comment]
Pinging @RipleyTom

**Comment by Frenthor** [comment]
When does this glitch happen? Can this be replicated near the beginning of the game?

**Comment by Ordinary205** [comment]
> When does this glitch happen? Can this be replicated near the beginning of the game?

The glitch usually happens when I'm not using Accurate XFloat after the 14979 Build.
And yes, it does replicate the issue at the beginning of the game.

**Comment by Ordinary205** [comment]
I'm closing the issue, because this PR #13843 fixes the regression.

**Comment by RipleyTom** [comment]
Do not close the issue until the PR is merged.

**Comment by MSuih** [comment]
Keep the issue open until the linked pr has been merged

**Comment by Ordinary205** [comment]
Got it.
