### ISSUE TITLE
steam deck open rpcs3 new version crashed

### ISSUE THREAD

**Issue by chengguang804** [RPCS3/rpcs3#13826]
### Quick summary

I updated the rpcs3 for my steam deck today. When I try to excute it after finished update it crashed in a second. Then I try to uninstall/reinstall, however, I cannot play it anymore. Report this bug here is only what I can do now. Anyone can help me?

### Attach a log file

There is no log generated.

**Comment by AlexOboleshew** [comment]
I've got the same problem. Trying to launch - emulator icon appears for a second an then disappears. Reinstalling/updating throught Emudeck didn't helped.

**Comment by chengguang804** [comment]
It seems I'm not alone. Look forward to the bugfix version coming asap.

**Comment by YuriNator557** [comment]
The log is always generated, if you got RPCS3 from Emudeck or anywhere that isn't the RPCS3 website then you are not using an official release and this issue is invalid.

**Comment by MSuih** [comment]
Does the v0.0.27-14982-7740cac6 update do anything about this?

**Comment by AlexOboleshew** [comment]
> The log is always generated, if you got RPCS3 from Emudeck or anywhere that isn't the RPCS3 website then you are not using an official release and this issue is invalid.

Installing separate from Emudeck have the same result. buid 14981 just won't load.

**Comment by AlexOboleshew** [comment]
> 

build 14982 is working.

**Comment by chengguang804** [comment]
> The log is always generated, if you got RPCS3 from Emudeck or anywhere that isn't the RPCS3 website then you are not using an official release and this issue is invalid.

I think you are right if it is in a normal situation. But this case looks a little bit strange. When the crash happen I tried to uninstall and reinstall it. To be sure all the file related could be remove clean I found out them delete one by one by myself. So... cache log path clean included in my operation steps. At last, I reinstall it from emudeck and it continue repeating crash, however, log did not generated into cache path anymore. That is the whole story.  I think you can easily reproduce it once you update the new version on steam deck if you do not mind the inconvenience.

**Comment by MSuih** [comment]
If emulator fails to start at very early steps then it could be that the log generating code doesn't have a chance to run. This is normal and the log wouldn't probably have anything important anyways.

Since there's a report that 14982 works, I'm closing the issue. Please update to that version and test again. If the issue persist then this can be reopened.
