### ISSUE TITLE
Jet Set Radio missing geometry Mac mini M2 pro 

### ISSUE THREAD

**Issue by Isamoth** [RPCS3/rpcs3#13827]
### Quick summary

Game runs full speed, but is missing textures for some grind rails and vehicles making it nearly impossible to play.

### Details

While playing the game even during the title screen gameplay reel you can see that there is missing textures.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11418598/RPCS3.log)

**Comment by Isamoth** [comment]
![NPUB30829_screenshot_2023_05_08_00_52_29](https://user-images.githubusercontent.com/89888649/236755232-a31a3997-f411-4cbe-a841-4f060fb500e6.png)
![NPUB30829_screenshot_2023_05_08_00_52_53](https://user-images.githubusercontent.com/89888649/236755268-3e712ee2-6fd6-4280-ae7c-6d3b4801413b.png)

**Comment by Megamouse** [comment]
needs to be tested with default settings

**Comment by Isamoth** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11458485/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11458486/RPCS3.log)
Here is the game loading up on default settings

**Comment by AniLeo** [comment]
Needs to be retested since #13969 fixed a rendering bug on these GPU models

**Comment by kd-11** [comment]
I forgot this was a thing. I can test in a day or so and close if needed.

**Comment by kd-11** [comment]
Closing pre-emptively. This should be fixed now. If not, ask to reopen.
