### ISSUE TITLE
[Regression] Pressing enter key to launch games no longer works

### ISSUE THREAD

**Issue by Kooldude93** [RPCS3/rpcs3#13828]
### Quick summary

Pressing enter key to launch games no longer works in List View but does in Grid View.

### Details

Regression began in 0.0.27-14969 probably by https://github.com/RPCS3/rpcs3/pull/13801

### Build with regression

0.0.27-14969

### Attach two log files

none

**Comment by AniLeo** [comment]
Can reproduce

**Comment by Megamouse** [comment]
Just for the sake of documentation:
The regression also affects resizing the icons with Ctrl+MouseWheel.
