### ISSUE TITLE
[Regression] XMB regressed after PR #13662

### ISSUE THREAD

**Issue by FlexBy420** [RPCS3/rpcs3#13821]
### Quick summary

As in title XMB now crashes before it can load fully

### Build with regression

v0.0.27-14976-6a41b22a

### Attach two log files

[Regressed LOG](https://github.com/RPCS3/rpcs3/files/11413642/RPCS3.log.gz)
[Working LOG](https://github.com/RPCS3/rpcs3/files/11413645/RPCS3.log.gz)

**Comment by brian218** [comment]
Not a valid regression report.
Kindly clear the caches, and everything should continue to work.

**Comment by elad335** [comment]
It renders old cache as invalid (vsh takes ridiciulous amount of time to compile), I don't understand why changing the syscall name in the first place.

**Comment by brian218** [comment]
> It renders old cache as invalid (vsh takes ridiciulous amount of time to compile), I don't understand why changing the syscall name in the first place. Or just link both names I guess.

@elad335 They are so as per your instruction in https://github.com/RPCS3/rpcs3/pull/12597#discussion_r962124379
and the `reinterpret_cast<u64>(ppu_execute_syscall)` stuff in PPUThread.cpp for backwards compatibilty was removed in #13534.

I think both sys_game.cpp in `Emu/Cell/lv2/` and sys_game_.cpp in `Emu/Cell/Modules/` should really be refactored for future development of other unimplemented sys_game syscalls (just in case).

**Comment by elad335** [comment]
No version bump, that is the reason then.

**Comment by brian218** [comment]
Why can't we add the underscore to the names of functions in `sys_game_.cpp` instead of `sys_game.cpp`?
For example:
sys_game.cpp: `sys_game_set_system_sw_version()`
sys_game_.cpp: `_sys_game_set_system_sw_version()`

**Comment by elad335** [comment]
You can.

**Comment by brian218** [comment]
> You can. (you need to register them with the correct name though)

so that the `reinterpret_cast<u64>(ppu_execute_syscall)` stuff for syscalls in lv2/sys_game.cpp would no longer be required?

**Comment by elad335** [comment]
Well now its a late because there are people with both types of caches. Anyway you can see an example of module function under different name in sys_net I think.

**Comment by brian218** [comment]
Okay, maybe wait until LLVM17.

**Comment by elad335** [comment]
What I mean is a bump of *rpcs3* (not actually related to llvm) llvm cache was not done yet the backwards compat patches were removed.

**Comment by brian218** [comment]
Solved by #13823. Issue can be closed.
