### ISSUE TITLE
openGL Unsupported surface color format (0x10)

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#1384]
when running the game Midnight Club Los Angeles.
![error 1 midnight club los angeles](https://cloud.githubusercontent.com/assets/16367065/12044402/790295aa-ae5e-11e5-8c30-c5f60b5a604e.png)

Modules LLE:
cellSpursJq_Library v1.1
cellSre_Library v1.1
 
log:
[RPCS3 Midnight Club Los Angeles.zip](https://github.com/RPCS3/rpcs3/files/74490/RPCS3.Midnight.Club.Los.Angeles.zip)

**Comment by raven02** [comment]
Should be no longer happened .Closed
