### ISSUE TITLE
Monster Madness Grave Danger Audio Issue

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13846]
### Quick summary

This Game has an audio stutter when testing on window and Linux

### Details

When testing this game I ran across an issue where the audio of the game would stutter while in menus and in-game.

Rpcs3  
https://github.com/RPCS3/rpcs3/assets/71127352/8bdfcab6-e167-4d66-95f7-2a04a98b9d35

Ps3
https://youtu.be/4NMP0Vtjb5U?t=55

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11464951/RPCS3.log.gz)

### System configuration

RPCS3 v0.0.27-14986-db7f84f9 Alpha | master | FW 4.88 | Windows 10 22H2
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by MSuih** [comment]
This reads more like a compatibility report to me. Audio is often the first thing to break for weaker systems, and ryzen 2600 is barely considered a recommended cpu.  

Compatibility reports should be submitted on our forums, not on github

**Comment by Triticum0** [comment]
someone with better specs will need to retest this game as it was last tested back in 2017
