### ISSUE TITLE
[Regression] Metal Gear Solid 4 - Low Framerate and Broken Sound on OpenGL (and Some Other Oddities)

### ISSUE THREAD

**Issue by BakerIsHungry** [RPCS3/rpcs3#13860]
### Quick summary

Game used to work well on Vulkan, then Vulkan became laggy and OpenGL became the better one, now both lag but Vulkan is a lot worse. Lag begins at the title screen.

### Details

I'm not sure if this was documented recently, but for a while MGS4 seemed to run at mostly 60FPS when played on Vulkan. I used to play it on that because OpenGL was broken and laggy at the time, then something got turned around and Vulkan became the troubled one while OpenGL became the good option. Then somewhere within the last month or so, both ended up being troublesome, with Vulkan being more laggy, while OpenGL is tolerable when the camera is angled away from anything intense on-screen, even if it's just an enemy truck. 

I wish I remembered when this started, but I figured somebody else probably reported the same thing in the Discord or forums before I reported it here. I only mention it now because it's been going on for a while and was unsure if anybody else was experiencing the same issues or not.

### Build with regression

I can't remember.

### Attach two log files

Unfortunately, this is the only log I can give since I don't remember what build this regression started at. This is the game with my usual settings minus the patches.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11473358/RPCS3.log)

### Attach capture files for visual issues

An example of the graveyard bug. [LoadingGraveyardExample.zip](https://github.com/RPCS3/rpcs3/files/11473402/LoadingGraveyardExample.zip)

### System configuration

OS:        Microsoft Windows 10 Home
CPU:	Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 4001 Mhz, 4 Core(s), 8 Logical Processor(s)
GPU:	NVIDIA GeForce GTX TITAN X
RAM:	16.0 GB

### Other details

[CPU] (Usual Setup)
SPU XFloat Accuracy is set to Relaxed XFloat. (I normally have it set to Approximate, but it runs worse on that.)

[GPU] (Usual Setup)
ZCULL Accuracy is set to Relaxed (Fastest).
Framelimit is set to 60.

[Advanced] (Usual Setup)
Accurate RSX Reservation Access is enabled.
Libvdev is enabled for TV sequence. 
RSX FIFO Accuracy is set to Atomic.

[Game Patches] (Usual Setup)
cellSpurs urgent commands hack - 4.89 is enabled.
Unlock FPS is enabled.

I only stated my current setup to show what it's normally set to. Playing the game at full default settings and with patches disabled gets me through the FMVs without lag, but causes the menu to show a brief unfinished graveyard being loaded in. This happens on Vulkan with my usual setup as well. Unlike Vulkan however, once the TV sequence ends, the game crashes as soon as it loads up the first gameplay segment and using my usual setup minus the patches has the game crash after starting a game. I once tested it with libaudio on, but that broke the game for me.

On another note, the audio fix doesn't seem to work for me. Not sure if it's because I'm playing MGS4 v2.0 or if it's because the emulator's not ready for emulating MGS4 on my system yet.

**Comment by solarmystic** [comment]
> I wish I remembered when this started, but I figured somebody else probably reported the same thing in the Discord or forums before I reported it here. I only mention it now because it's been going on for a while and was unsure if anybody else was experiencing the same issues or not.
> ### Build with regression
> 
> I can't remember.

Without this critical bit of information, the devs can't fix your issue and your issue report is invalid.

Do proper regression testing to figure out which is the build that started this issue:-

1. Go to [Builds History](https://rpcs3.net/compatibility?b), download an old build of RPCS3 that's in-between the build where you ran into the issue and a build where it was working.
2. Extract the RPCS3.exe file, rename it to e.g RPCS3-<version>.exe then place it in your rpcs3 folder.
3. Test the version you downloaded to see if it has the issue or not.
  * If it does, assume all versions after it are broken.
  * If it doesn't, assume all versions before it are working.
4. Go back to step 1 using the new version range until you have figured out which exact version caused the issue.
5. Once you've identified the build that caused the issue, [file a regression report](https://github.com/RPCS3/rpcs3/issues/new/choose) which follows the template, and make sure you note the exact build number/pull request where it started happening.

**Comment by BakerIsHungry** [comment]
I was gonna check into it, but the issues I've mentioned have been mostly rectified by RipleyTom's fix. Much appreciated! Game runs a lot smoother now. Other than some very minor performance dips (probably just my hardware for the time being), some minor sound imperfections, some shadows not loading in right all the time and some knocked out enemies looking weird in the Virtual Range at specific angles, this has been a major improvement. I can play with default settings now and it feels great in comparison. 

If you leave the game paused for too long (I'm gonna say about ten minutes), it freezes because of unmapped memory, though I've experienced that long before anything else. No longer does libvdec need to be turned on for the TV segment, it seems. As for the speed of the game, well... I have two logs here to give you an idea of what I'm normally dealing with. Might just be that I need to get more RAM or something.
[MGS4 (FPS Patch Disabled) RPCS3.log](https://github.com/RPCS3/rpcs3/files/11482437/MGS4.FPS.Patch.Disabled.RPCS3.log)
[MGS4 (FPS Patch Enabled) RPCS3.log](https://github.com/RPCS3/rpcs3/files/11482438/MGS4.FPS.Patch.Enabled.RPCS3.log)

**Comment by AniLeo** [comment]
Considering as fixed and closing then, if you have any regression remaining please follow the template to follow a correct regression report
