### ISSUE TITLE
Opengl initialization failure

### ISSUE THREAD

**Issue by krb7h** [RPCS3/rpcs3#13868]
### Quick summary

When I try to start up demon souls, the log reports opengl failing to initialize on multiple fronts then it hangs after

### Details

I start up demon souls, opengl fails to initialize, it compiles the ppu modules then it hangs and produces a black screen. 

I checked to make sure my gpu supports opengl 4.3 and opencl 2.0 and it does.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11482288/RPCS3.log)

### Attach capture files for visual issues

![IMG-1626](https://github.com/RPCS3/rpcs3/assets/99760505/f533055d-55be-4571-a674-90422293ae91)

### System configuration

CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz   2.70 GHz
GPU:  Intel(R) Iris(TM) Graphics 6100
OS: Microsoft Windows 10 Home
RAM: 8gbs

**Comment by YuriNator557** [comment]
Your PC is below minimum specs on Windows, if you want to use it with RPCS3 then you must use Linux, but be warned that performance will be utter garbage
