### ISSUE TITLE
[Regression] Huge gap between compiling ppu modules and spu modules (#13534)

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#13877]
For some time now we have a weird gap between compiling ppu modules and spu modules.
It's ~7 seconds for Fear. And nothing is logged in between.

![image](https://github.com/RPCS3/rpcs3/assets/23019877/22d262b5-11cf-4756-9ede-77c33985cdc0)

**Comment by JuanjoSevilla3** [comment]
What scares me a lot is the bsod error and the errape :D

**Comment by solarmystic** [comment]
> For some time now we have a weird gap between compiling ppu modules and spu modules. It's ~7 seconds for Fear. And nothing is logged in between.
> 
> ![image](https://user-images.githubusercontent.com/23019877/239052676-22d262b5-11cf-4756-9ede-77c33985cdc0.png)

This can be definitively traced back to #13534

**Comment by Darkhost1999** [comment]
At least it's not 65+ seconds like the less fortunate games. I really can't complain if it was only ~7

https://github.com/RPCS3/rpcs3/assets/60384196/ddcb9ee7-9a4f-447f-82a5-a999af78a131

**Comment by AniLeo** [comment]
Worth retesting with #14090

**Comment by solarmystic** [comment]
#14090 doesn't fix this particular issue unfortunately, there's still an abnormally long pause between the end of Linking PPU modules and the start of building SPU cache.

**Comment by AniLeo** [comment]
Very likely fixed by #14848, please ask to reopen if it's not fixed on your side
