### ISSUE TITLE
[Feature request] Option to hide or show columns in Trophy Manager

### ISSUE THREAD

**Issue by ArbestRiAgain** [RPCS3/rpcs3#13873]
### Quick summary

There should be an option in Trophy Manager to hide or show columns just like in the list view game list.
I have made this image to show what I mean:
![Screenshot 2023-05-16 205611](https://github.com/RPCS3/rpcs3/assets/132712354/aba78f95-e962-410a-a26a-62522c724975)

### Details

I wouldn't want to see some information such as platinum relevance and the trophy ID, and this option would make the trophy manager look a bit more clean. This would also be affected by UI. I'm also using the normal feature request template here, so it may look somewhat empty.

**Comment by JuanjoSevilla3** [comment]
Well, you're right! if you want them to respect your privacy :D
