### ISSUE TITLE
[Termux] Errors when building

### ISSUE THREAD

**Issue by IntinteDAO** [RPCS3/rpcs3#13871]
### Quick summary

Termux is a Terminal emulator and tools compiled on the Android environment. In short, you could say it's like Cygwin, but for Android.

The main 'problem' is that not everything is like in Linux, there is a different libc, different paths and so on. On the other hand, probably an experienced developer would be able to prepare RPCS3 to build on Termux.

I managed to start the build process of the project, but unfortunately there are errors during compilation. I don't know if this is fixable, but that's why I'm asking for expert opinions.

### Attach a log file

https://0bin.net/paste/7Gfi70-j#TWMxu64t2P9FnslWNqKcIFKH4Il1Z+9NYFjLwKyFTmi

### System configuration

Termux on Android 12

**Comment by RipleyTom** [comment]
std::convertible_to is part of C++ 20 standard which seemingly Termux doesn't support(probably outdated gcc along with outdated everything).
Beyond that I very much doubt it'd support a lot of what rpcs3 needs so closing as not an issue.

**Comment by IntinteDAO** [comment]
Termux rather has up-to-date stuff. On the other hand, I will still try with Clang and let you know.
