### ISSUE TITLE
[Feature request] support for 21:9 UltraWide Aspect Ratio

### ISSUE THREAD

**Issue by dev1981** [RPCS3/rpcs3#13886]
### Quick summary

Is it possible to have 21:9 UW aspect ratio support for RPCS3?

**Comment by MSuih** [comment]
Playstation 3 does not support 21:9 output mode. You can hack around by modifying camera FoV with a patch and using stretch to display, but the aspect ratio will still be 16:9 internally.

There already is such patches for many popular games, check the patch manager for more information. But it's common that some aspects of the game remain stretched.
