### ISSUE TITLE
[Regression] [macOS] Freezes on launch, does not load the game list

### ISSUE THREAD

**Issue by shinra-electric** [RPCS3/rpcs3#13884]
### Quick summary

Freezes on launch, does not load the game list.

This affects both Intel and Arm builds. 

Edit: Last known working build: #13851

Regression caused by #13632

### Details

- Main window freezes on launch
- Does not load the games list
- Need to force-quit

<img width="1425" alt="Screenshot 2023-05-18 at 19 48 28" src="https://github.com/RPCS3/rpcs3/assets/50119606/9fc004ec-0432-46cc-bfdb-1110aa5e3c13">

### Build with regression

#13632

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11510529/RPCS3.log)

### System configuration

M1 Pro
Ventura 13.3.1
16GB

**Comment by Megamouse** [comment]
missing log file

**Comment by shinra-electric** [comment]
Added

**Comment by Megamouse** [comment]
can you test with the submodule change in this #13885 ?

**Comment by Megamouse** [comment]
can you compile and run the tests in the submodule?
if they hang as well, then this is an upstream issue

**Comment by shinra-electric** [comment]
I was able to compile the tests, but to run them properly I need to have some midi input. 

Here is the terminal output: 
[rtmidi test output.txt](https://github.com/RPCS3/rpcs3/files/11510895/rtmidi.test.output.txt)
