### ISSUE TITLE
RPCS3 crash when savestate

### ISSUE THREAD

**Issue by Tyrwenn** [RPCS3/rpcs3#13899]
### Quick summary

The software instantly " stop responding " when I try a savestate, and don't come back to normal until it crash.

### Details

The log don't seem to save what happened. Tried on several games, several places, always the same problem. The save is not even created, I can't load it from right click on the game. I also tried to move the RPCS3 folder.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11522733/RPCS3.log)

### System configuration

Laptop
Windows 11
RTX 3070ti
I7-12700H
Last Nvidia driver

Other details

**Comment by HellInfernal** [comment]
I have the same issue. Ctrl+S make RPCS3 crash on all games I tried. The only exception is the Siren Blood Curse (BCES00294) which works properly with making savestates.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11532122/RPCS3.log)

**Comment by ynhhoJ** [comment]
One more here. Happened for me during The GodFather.

Logs:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/11761063/RPCS3.zip) 

Windows 11 Pro
GPU: 6950 XT
CPU: 5800 X
Ram: 16 GB
All drivers & updates are up to date

I used 60 FPS patch for the game.

**Comment by Fuzzybane** [comment]
same here with lollipop chainsaw, am at zombie baseball section and wanted a state before putting Nicks head on the body so I don't have to keep being told how to play and crashes RPCS3 on latest build

**Comment by Zaannaah** [comment]
same issue for me when i tried to save state while playing the first game of the ratchet and clank collection. havent tested other games yet. Windows 10 pro version 10.0.19045 build 19045. ryzen 7 5800x.  rx6700 xt.  36 gb of 3600 ram. amd adrenaline version 23.5.1
as soon as i hit control s it froze up stopped responding and never recovered. Log file attatched.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/11804580/RPCS3.zip)

**Comment by gir489returns** [comment]
Same issue here. Usually when saving or loading it crashes.

**Comment by Gregware-p** [comment]
Same here

**Comment by jelledv49** [comment]
Same here

**Comment by DAOWAce** [comment]
Just happened to me for the first time after loading savestates about 5 times, crashed on first save.  Did actually save the data though, was able to load it.

[Imgur](https://i.imgur.com/87MtB5W.png)

Forgot to get log before restarting the emu, so it wiped it.

**Comment by aarelovich** [comment]
Hi. Newbie here. Installed RPCS3 yesterday for the first time in my life in order to play Dai-2-Ji Super Robot Taiser OGs because I don't wan to use my PS3 anymore. I have been able to do everything including saves. BUT When I use a save state the game crashes. HOWEVER the save state is successfully created and I can load from it. Using Build 0.0.29-15715 downloaded on November 9, 2023 (in case it changed since yesterday). Other than that as far as I can tell the game plays perfectly (Only did 2 stages though).

**Comment by ReLyf47** [comment]
> Hi. Newbie here. Installed RPCS3 yesterday for the first time in my life in order to play Dai-2-Ji Super Robot Taiser OGs because I don't wan to use my PS3 anymore. I have been able to do everything including saves. BUT When I use a save state the game crashes. HOWEVER the save state is successfully created and I can load from it. Using Build 0.0.29-15715 downloaded on November 9, 2023 (in case it changed since yesterday). Other than that as far as I can tell the game plays perfectly (Only did 2 stages though).

That is normal behavior
RPCS3 save state is not like other emu
RPCS3 save state is more like a "Hibernate/Sleep" option than a proper savestate

**Comment by aarelovich** [comment]
> > Hi. Newbie here. Installed RPCS3 yesterday for the first time in my life in order to play Dai-2-Ji Super Robot Taiser OGs because I don't wan to use my PS3 anymore. I have been able to do everything including saves. BUT When I use a save state the game crashes. HOWEVER the save state is successfully created and I can load from it. Using Build 0.0.29-15715 downloaded on November 9, 2023 (in case it changed since yesterday). Other than that as far as I can tell the game plays perfectly (Only did 2 stages though).
> 
> That is normal behavior RPCS3 save state is not like other emu RPCS3 save state is more like a "Hibernate/Sleep" option than a proper savestate

Thank you for that. So If I want to use it like save and reload, save and reload to get a desired outcome, this is impossible to do?

**Comment by bigboss97lnt** [comment]
+1

**Comment by elad335** [comment]
Closing until reported to be not fixed because there were lots of related fixes recently.

**Comment by jedinjapan** [comment]
> Closing until reported to be not fixed because there were lots of related fixes recently.

Still experiencing this with MGS4 on the latest builds.

**Comment by PhyoMyanmarKyaw** [comment]
The crash is still occurring, although loading the save is working. It would be great if we could fix this issue in the future.

<img width="553" alt="Screenshot 2025-01-08 at 3 36 30 AM" src="https://github.com/user-attachments/assets/cc879765-c8b0-468b-a666-a5ac83ab54e9" />

Apple M4 Pro 16 inch
RAM : 24 GB
MacOS : Sequoia 15.2
