### ISSUE TITLE
savedata BLES00599-CNT considered broken Bayonneta

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#1389]
![error 1 bayonneta](https://cloud.githubusercontent.com/assets/16367065/12065205/f5ae16fe-afa0-11e5-956a-0ef37ad6f228.png)

when you press start and presents this message when you select yes and the game continues
![error 2 bayonneta](https://cloud.githubusercontent.com/assets/16367065/12065212/06dcd3ca-afa1-11e5-955c-02b491c515fe.png)

savedata BLES00599-CNT considered broken
![error 3 bayonneta](https://cloud.githubusercontent.com/assets/16367065/12065240/853eec3a-afa1-11e5-8cbf-5804dbf84d17.png)

LLE Modules:
cellFiber_Library v1.1
cellSpursJq_Library v1.1
cellSre_Library v1.1

Log:
https://mega.nz/#!mUBRSaCI!-CHCmQSUpPS8xfM921qaEHEQYwmhB8cpPuEHw7f_qsE

**Comment by tambry** [comment]
@mkultimate The game specified to us that it considers the savedata file broken. Nothing we can really "fix".

**Comment by mangames** [comment]
Just wait for it to load are you trying to load a real game it a .pkg with a .rap need to load the .pkg file but if it a real size game it could take 3H to 5H to load and you can make a .pkg out of a real game which takes a long time to load. just wait?.

**Comment by AniLeo** [comment]
What? Also note this issue has been closed two years ago

**Comment by mangames** [comment]
2 year but can still fix! 👍  I was just working on the same thing, do you like the modded rpcs3 60fps?
