### ISSUE TITLE
[Feature request] RPCS3 on PowerPC architecture

### ISSUE THREAD

**Issue by pc297** [RPCS3/rpcs3#13906]
### Quick summary

Hi, I'm wondering if it would at all be possible and how much work it would be to completely remove the PPU ppc64 ->x86 translation layer altogether to have RPCS3 run almost natively ppc64 Linux, (e.g. G5 or ≥POWER4), i.e. near-native PPU ppc code execution while maintaining  SPU emulation?

I.e, how much of the PPU translation layers would need to be kept? What exactly would need to be kept and removed from the PPU* and CPU* sources at first for near-native execution of ppc64 PPU code apart from all the ppc64 -> x86 translation methods) and endianness switching methods, and what would need to be modified, apart from SPU control instruction translation, as well as memory map (which I take it it would still require some instructions to be translated since PS3 memory maps are obviously different) and thus some instruction translation layers that would need to be kept but modified for ppc64? And what would need to be added instead, apart from low-level self-virtualization (for CPUs that support it, i.e. not the G5)? 

As for the SPUs, emulation of the 8 DSP cores would obviously need to maintained, but how different is the ISA from ppc/ppc64 ("Power Efficient ISA" as per IBM's redbooks)? Is it big endian? How efficient would Cell SPU emulation be on ppc64, would it even be worth it, and how much would need to be dropped (if there is some similarity between the two ISAs, the Cell SPU ISA is RISC and wasn't it originally meant to use VMX at first instead of the new SIMD extensions that it ended up using?) or modified to translate all SPE code -> ppc64 if this is required?

Obviously if running on Cell (e.g. a number of IBM workstations/servers) or Xenon (e.g. Linux on the 360) all PPU and SPU emulation as well as translation layers can be removed! (but with added VMX ->VMX128 layers for Xenon for unsupported VMX instructions as VMX128 isn't fully backwards compatible with VMX due to removed instructions to add another 96 registers)

Cheers,

**Comment by elad335** [comment]
That's not how it works, if at least instruction isn't supported you had still have to emulate all instructions (see CELL vector SIMD extension instructions).

**Comment by AniLeo** [comment]
Closing as wontfix as explained by elad
