### ISSUE TITLE
White Knight Chronicles™ II(BCES-01085) [BCES01085] Freezes on videos

### ISSUE THREAD

**Issue by hayguneys** [RPCS3/rpcs3#13926]
### Quick summary

Hi, i've been trying play White Knight Chronicles II for the last two days and the title keeps freezing on cutscenes (logo intro, ingame cutscenes too). I can only ever get to the main-menu if I span skip furiously. I posted my log below, but the freeze is usually accompanied by: 

E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [1]
E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [2]
E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [3]

or:

E SYS: 'cellVdecGetPicItem' failed with 0x80610104 frame=0, sequence_id=1, seq_id=0 [1]

I tried both US and EU versions, with and without the latest patch, any help is deeply apreciated

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/11589282/RPCS3.zip)

### System configuration

AMD Ryzen 5 5600 (12) @ 4.400GHz 
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
Memory: 16gb
OS: Archlinux with gnome 44.1

**Comment by ChwaraeTeg** [comment]
Does switching libvdec to LLE make any difference? (To do this, right-click on the title in the list, select Create/Change Custom Configuration > Advanced > Check the box next to _libvdec.sprx_ under Firmware Libraries > Save custom configuration)

**Comment by hayguneys** [comment]
Tried it now and I got this error now:

```
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [3]
```

**Comment by Belouarrak** [comment]
Same issue for me. I have tried looking on the internet for fixes for this specific game that recommend setting up driver wake up delay to 200, but no dice. 
For what it's worth, it seems that actual gameplay is smooth and solid, but anything that is a cutscene will inevitably crash and the only solution is to furiously skip every cutscene.
Ticking libvdec has not worked either for me.

**Comment by Belouarrak** [comment]
> Yeah I tried with the sleep mode set to Usleep + driver delay to 200 + a bunch accuracy/compatibility options on and it managed to pull through the logo cutscenes but it still crashes on the main story intro cutscene and sometimes it crashes instantly.
> 
> As you said, gameplay is pretty smooth, no hitches, sound is fine. Although, I have to add, I saw some ppl playing the game on an older build without these freezes, so I think there's a regression at play here.

Can you try again on the latest build and tell me if the issue persists? Preferably booting on default config first and then whatever custom config you use?

I am very puzzled by the fact that it works now despite still having CELL_VDEC_ERROR_BUSY calls

```
E SYS: 'cellMsgDialogProgressBarInc' failed with 0x8002b302 : CELL_MSGDIALOG_ERROR_DIALOG_NOT_OPENED [1]
E SYS: 'cellMsgDialogProgressBarInc' failed with 0x8002b302 : CELL_MSGDIALOG_ERROR_DIALOG_NOT_OPENED [2]
E SYS: 'cellMsgDialogProgressBarInc' failed with 0x8002b302 : CELL_MSGDIALOG_ERROR_DIALOG_NOT_OPENED [3]
E SYS: 'cellMsgDialogAbort' failed with 0x8002b302 : CELL_MSGDIALOG_ERROR_DIALOG_NOT_OPENED [1]
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) x3
E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [1]
E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [2]
E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [3]
E SYS: 'cellVdecGetPicItem' failed with 0x80610104 frame=0, sequence_id=1, seq_id=0 [1]
E SYS: Stat: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [x26]
E SYS: 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) x3
E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [1]
E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [2]
E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [3]
E SYS: 'cellVdecGetPicItem' failed with 0x80610104 frame=0, sequence_id=1, seq_id=0 [1]
E SYS: Stat: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [x38]
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) x3
E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [1]
E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [2]
E SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [3]
S SPU: New block compiled successfully x4
```

Wish I could tell you what changed, I have a second controller plugged in, that's all. Maybe the fixes they did for Gran Turismo saved this game too?

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11645613/RPCS3.log.gz)

**Comment by hayguneys** [comment]
Ok, ran with default config on the latest version (0.0.28-1-2e4bf9ef Alpha) and it's all working (with some audio crackling since defaults turn time stretch off). Great stuff! Ok all is working, thanks for the help!

I'm closing the issue for now, I'll reopen if the freeze happens again.
