### ISSUE TITLE
Gran Turismo 5 [BCUS98114] - Blinking white dots arranged in lines appear across a corner of the screen.

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#13922]
### Quick summary

Issue as per title.

https://github.com/RPCS3/rpcs3/assets/4345150/b166e4ca-5b48-4e32-bdef-9d36c17afbca

### Details

This issue has been present ever since GT5 became in-game many years ago. 

Blinking white dots that are arranged in vertical lines are present across a corner of the screen. 

These only appear when selecting the 1920x1080 resolution from the default resolution drop down menu. 

1280x720 resolution is not affected.

These do not appear during actual races and thus visibility is not affected.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11579351/RPCS3.log.gz)

### Attach capture files for visual issues

Rename .zip to .7z and extract using 7zip.

[BCUS98114_20230527034324_capture.zip](https://github.com/RPCS3/rpcs3/files/11579319/BCUS98114_20230527034324_capture.zip)

### System configuration

SYS: RPCS3 v0.0.27-15080-9f5e3ecb Alpha | master
SYS: 12th Gen Intel(R) Core(TM) i7-12700KF | 20 Threads | 31.86 GiB RAM | TSC: 3.610GHz | AVX+ | FMA3
SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2080 Ti' running on driver 527.56.0.0
SYS: Firmware version: 4.88

**Comment by Satan86** [comment]
This is fixed by Strict Rendering Mode. This does not mean the issue should be closed, however, as far as I know.

**Comment by Satan86** [comment]
Hello.
I felt like helping to fix this issue. My contributions may not be massive, but I hope they provide further clarity on what is going on.
This issue presents itself differently with different GPUs. My 1050 Ti is different from our friend's 2080 Ti up there, and same goes for others.
<details>
<summary>Here is how it looks on my GPU.</summary>

![image](https://github.com/RPCS3/rpcs3/assets/61447828/18003a29-982f-47f8-944e-9f3b40fa37c8)

</details>

<details>
<summary>And on a GTX 1070.</summary>

![image (1)](https://github.com/RPCS3/rpcs3/assets/61447828/da48c87d-432e-4335-b1df-6e09dc1987e8)


</details>

I have also seen people with two or three big triangle shaped artefacts across the screen, also with differente GPUs. All the same issue, just showing up differently.

Also worth noting is that, on my squares, it "copies" what the main screen is doing, and stretched, similar to how #14176 looks, but inside those artefacts only. A video is worth more than A Thousand Words, [so here it is.](https://www.youtube.com/watch?v=HYsRiP_oX2U) In this aptly titled video, you can see what I mean, as the 4x F1 Driver's World Champion Sebastian Vettel moves his arm and hand around in the "main" image and, simultaneously, inside the artefacts.

Furthermore, in an attempt to help even further, I took the liberty to generate some RSX Capturas myself, as well as some Renderdoc Capturas.
I took a LOT of RSX capturas, they all show the same issue. Many of them crashed with
```
 ·F 0:00:36.796571 {RSX [0x100abc94]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Program\VertexProgramDecompiler.cpp:79[:4], in function GetDST)
```
when trying to Play, but [this one](https://drive.google.com/file/d/1zwqORIx2sgM4w0LogDNBd_bF8Tmcbx9X/view?usp=sharing) worked, so I believe it should also work for anyone else.

[Here](https://drive.google.com/file/d/1Wr0PqpVWSlyHF23B4b8t_yHehgiEZNFb/view?usp=sharing) are the Renderdoc Capturas, featuring 4x Nascar Cup Series winner Jeff Gordon, also showing the bug.

I am already massively thankful to all the recent Gran Turismo improvements, and fixing this bug would be another step towards making the best selling PlayStation:registered: 3 exclusive Playable on the Emulador.

Good luck to all the talented developers of this emulador, and God Bless.

The most kind regards,
Erik.

**Comment by kd-11** [comment]
If you can, please retest this one. We've come a long way with GT games support. Also remember to check whether "strict mode" fixes the problem.

**Comment by MrWalshy** [comment]
> If you can, please retest this one. We've come a long way with GT games support. Also remember to check whether "strict mode" fixes the problem.

I'm not having this issue on build v0.0.32-16864-be0ef0cc Alpha on a 7840HS/4070 laptop when using the 4070 as the GPU, but I do get it when using the 780M iGPU. Settings are those recommended on the wiki, alongside accurate xfloat for SPU accuracy, FSR for upscaling, and 1080p as the default resolution. No strict mode required.

780M:


If you would like me to try any particular combination of settings, provide logs, or try hardware combos I have (i5 7300HQ/1050 laptop, 5900HX/6800M laptop, 3600/1050ti desktop, 5900x/4070ti desktop, ROG Ally Z1E), let me know.

**Comment by kd-11** [comment]
Closed due to inactivity.

**Comment by Jonathan44062** [comment]
Still an issue 
https://drive.google.com/file/d/1c0edI09BjTcJ4on2Tuk__VjpyB-rO1VQ/view?usp=sharing

[RPCS3.log.gz](https://github.com/user-attachments/files/21132364/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Need information: Please retest

**Comment by MrWalshy** [comment]
> Need information: Please retest

Had this issue a few years ago, I can give this a check sometime in the next few days...

Is there any preference(s) on test rig(s)? Can check on any of my currently available machines: 

- 13980HX/4080M win laptop, 
- 7840u w/ 9070xt eGPU linux laptop, 
- 5900x/9070xt win desktop,
- 9800x3d/5070ti win desktop,
- LeGo 2, Z2E linux.

**Comment by Satan86** [comment]
it still happens and strict rendering mode fixes it

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2f3c570e-58a8-47fc-87a3-3cde8645e034" />

**Comment by kd-11** [comment]
Closing if strict mode fixes it.
