### ISSUE TITLE
Follow CppCoreGuidelines and add Microsoft GSL lib ?

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1392]
With Visual Studio 2015 Update 1 added tools supporting "C++ Core Guidelines" :+1: http://blogs.msdn.com/b/vcblog/archive/2015/12/03/c-core-guidelines-checkers-available-for-vs-2015-update-1.aspx

Basically these Guidelines were presented in october in CppCon. It's a set of "good practice" rules that can be enforced by tools (like no uninitialized ptr, no array by pointer passing and so on...) and a library, GSL, that defines a couple of types that provides replacement for some constructs based on pointers.

The goal of these guidelines is to help compiler and static analysis tools discover code error by using a well defined subset. It should provide type and bound checking for 99% case without adding overhead and avoid dandling pointer, double deletion and so on.

RPCS3 already follow some of the guidelines. Most pointers are wrapped in shared_ptr or unique_ptr, big endian and little endian type are covered by templates.
However it lacks bound checking. A lot of code uses pointers casts and pointers arithmetic. I think using the GSL lib from https://github.com/Microsoft/GSL and the "span" template in there may be really useful to improve our codebase in the longterm.

**Comment by vlj** [comment]
Note that clang-tidy (clang static analyser) already support some of the rules :
http://clang.llvm.org/extra/clang-tidy/checks/list.html

**Comment by tambry** [comment]
Can this be closed?
