### ISSUE TITLE
Ratchet and Clank: Tools of Destruction crashes on gameplay load

### ISSUE THREAD

**Issue by AgentSEPTEMBER** [RPCS3/rpcs3#13938]
### Quick summary

When running on vanilla/ default config, the game will load and run as far as the into cutscene, but then freeze and then crash immediately.

### Details

N/A

### Attach a log file

- SYS: RPCS3 v0.0.27-15111-c37fc73a Alpha | master
- SYS: AMD FX(tm)-8300 Eight-Core Processor | 8 Threads | 23.98 GiB RAM | TSC: 3.315GHz | AVXx | FMA3+4
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-06- 2T11:35:41
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060' running on driver 516.94.0.0
- SYS: Firmware version: 4.90
S UPDATER: RPCS3 is up to date!
S PPU: Enabled: Non-Java Mode Fixup
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060' running on driver 516.94.0.0
S HID: DualSense Controllers found: 1
S Input: The pad mode was changed to Single-threaded
S Input: DualSense device 0 connected
S GUI: Boot successful.
S PPU: [0x5ac968] Instruction repetition: 0xf8860009
S PPU: [0x5ac96c] Instruction repetition: 0xf8860009
S PPU: [0x5ac970] Instruction repetition: 0xf8860009
S PPU: [0x5ac974] Instruction repetition: 0xf8860009
S PPU: [0x5ac978] Instruction repetition: 0xf8860009
S PPU: [0x5ac97c] Instruction repetition: 0xf8860009
S PPU: [0x5ac980] Instruction repetition: 0xf8860009
S PPU: LLVM: Loaded module v6-kusa-9GzfE4qpzhng3PfnJ24V2c-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-JeQbQM8XZy4p61Jt5GpATa-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-QXbAJJMz3bRZwV9KYbRyww-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-aaJyfAsp0cFa2FLQhyhHEt-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-aiik91WrhutjfmCQr5q7nu-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-Rmce2pCAGXvsVHd7dt961o-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-VcPhhTqPyVv4ec63Q7tx0K-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-6TVcfZW7RMyKrQ5Rq8aST6-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-nQ4XwdtxNGjP3H747uKWrs-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-E7NdpnCjR1qMvZVAsXunmQ-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-80mRcvjRAVyNpMd4ahua4q-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-pq7Z4X0AVmKkMqqfRSNRRn-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-i73CQxYcEayNmFzyuz2X6C-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-73AKKpnKx1k3WWcVkc1uM0-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-mKWrsoHnMh3Q9aVYjf8WUt-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-3nuv3UWLxWZejowvwJ599u-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-Gu3pGfWvPwjc8rbwFReKas-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-6thLAfm0sq5gNWn5L97aqb-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-GvjeA5dZXbQq0MTNAMNJ2m-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-p9hTLv0HwEEm95rm654FiL-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-WPRhjrLkvaLSYVGEUbeToE-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-UtjauqG7yF06jq6eQZgUvz-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-H2GVR5E7NLQ9iNyedQGV1Z-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-9Vovds4Kho25u49CsJ6Scx-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-Tp7YSsE6YwNp9U53mxMvWt-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-pwzLLKgRujhnxd73Z7gnPP-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-QtwFVtm6iLehpuUsrFHNqP-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-9qXhnNnrSa6dS2HQjgS0xo-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-tKyQEVgepHXrNEWssNvQUE-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-MPHQiik9wyVT9eTGJ0cfN7-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-cgWMQwnN3UCddt3NRoX2dY-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-cEYHMMPNQ93999mqySz7uL-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-G7igfS7jupeAKQTonKFGQ0-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-jM6r0d3Mup0HhCqNUp5MdA-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-37e8UqfYN3CMerbN77wtZi-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-njFHnApcZkjcm4tit7TfW2-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-RYXg480FvzaKn376eug8JR-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-aF9iydtwru98X7MvXqpoFL-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-tJeudpUPev0ru6Zr0a8WMe-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-gASfnFyXbzKCqddEM1rKCP-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-ZEG8TZER2TgkmoToUNc77n-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-sgoJbx5QvLAqUbPfCjT4zL-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-08fyznuifg7UsSH0saqcTG-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-65jYEfhgQLTYyxKy6nPpjY-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-pVzp3HLbdanq57L5jF9dHh-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-LcvYdNSUC8MpHCp6a7xhye-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-GR46VMHekc1tUM6bHiaxQg-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-tguNzjUk3KhaRwm0UYQuLc-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-TGbp1GtbuWgijPwvvojuy6-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-mZwESpco1LrRen8L6CZ0Nv-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-aakKN3aGK4F1QKfo0ha8vC-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-4s6GoL9wfCfaeyP923e30i-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-4zR9Wfu6WcgjHtjEK6rnmZ-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-PijwkkaGq1ofZoE3zC9WiY-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-F9JdQ9gNinpG0GrGuxsjia-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-36EzzxX4KYaa9nQwRfwci6-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-K49gsFX8SnoA6LcK564Evy-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-TLEJRf6SG704dbZVZMR8HG-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-Su3bs6kLzWXadhbP3Rye3f-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-PMxt0jw96KXJ1zWkcdEu8X-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-XQo2Ynkaj3JQc87036cTJX-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-WfAhZ56GEYpQKtnysHGnT9-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-TAVdq85XfRSrNMNiRb3QRy-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-tRwsCGR4321o3TLVccJyE1-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-ft4caUcw6G76bVPGNK2NwX-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-a7pxaRqKMTR6soZy8kTfLi-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-KVjnnLSFG8wGJUkm087WeT-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-EJe2EYVZqNg0XZ9wx8ELPG-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-8ARycvhJj9M3jvqoto8K6m-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-L9PmjPJ2SyqREjmym9ZUoR-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-qQeNNx29kWrgdvFkQERM9T-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-dfoufxhFdHP63U2oX72HGm-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-bujkVfhAGnCg43jQ0V9qhn-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-iSqqUTKi0RjG1RY7Yn0Y7P-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-psiaiurimp5VKw1yuV1TJc-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-bhRmvgsctsstnHtw7uoM88-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-AV7t0SMQnkynPWpShb109Z-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-Zn3gvuaCUgdmfCXwMaVcGd-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-UXCiobxXqeAmxAQiM4Vaso-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-W87QtEzuuifH9ay4fKtaxV-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-RpJcMUvMooAVAF3ZHeUpwW-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-MqrykpsYuREo7ejw1AnkAu-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-juejU3tn8YNUoJtnKYuV9d-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-YwAM7JMGru6q1eYtHCHAV3-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-JzeWEng62G75JsXVYp00mG-00001G-bdver2.obj
S SPU: SPU Runtime: Built the interpreter.
S SPU: SPU Runtime: Built 707 functions.
U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0010ce0)
S PPU: LLVM: Loaded module v6-kusa-1z3Pyu8YVnnorJiQ2hfu1e-00001G-bdver2.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0010a50)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0010a50, a3=0x0)
S PPU: LLVM: Loaded module v6-kusa-XCgQWMc1s99n1WTwrpWvw4-00001G-bdver2.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S PPU: LLVM: Loaded module v6-kusa-1Au1tg93M0j9aPxhbpVJAC-00001G-bdver2.obj
S PPU: LLVM: Loaded module v6-kusa-5MR5UPWcNoRKHsUNJqHbKV-00001G-bdver2.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0010df0)
S PPU: LLVM: Loaded module v6-kusa-fLV79QqHgPi90UziTsWrHo-00001G-bdver2.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23002200)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) x2
E cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BCUS98127”, errDialog=0x0, funcStat=*0x870d28, container=1056964608)
S cellSysutil: Mounted existing cache at C:/Users/Rick/Desktop/RPCS3 Folder/dev_hdd1//caches/BCUS98127_BCUS98127/
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/game.psarc” [1]
E SYS: 'cellSaveDataListAutoLoad' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
E SYS: 'sys_ppu_thread_get_priority' failed with 0x80010005 : CELL_ESRCH [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.jp.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.fr.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.es.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.de.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.it.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.nl.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.pt.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.kr.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.cn.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.cn.dat” [2]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.fi.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.se.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.dk.dat” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/processed/audio/global/streaming_dialogue.no.dat” [1]
E SYS: 'cellPadGetData' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [1]
E SYS: 'cellPadSetActDirect' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [1]
E SYS: 'cellPadGetData' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [2]
E SYS: 'cellPadSetActDirect' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [2]
E SYS: 'cellPadGetData' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [3]
E SYS: 'cellPadSetActDirect' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [3]
E SYS: 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY [1]
E SYS: 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY [2]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/packed/levels/metropolis/level_uncached.psarc” [1]
E SYS: 'sys_ppu_thread_get_priority' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY [3]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/packed/levels/metropolis/level_cached.psarc” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/packed/levels/metropolis/level_uncached.psarc” [2]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/packed/levels/metropolis/level_textures.psarc” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98127/USRDIR/built/movies/l01_s01_ntro_fmv/l01_s01_ntro_fmv.us.pkg” [1]

### Attach capture files for visual issues

N/A

### System configuration

Latest as of 02/06/2023 (UK)

### Other details

N/A

**Comment by AgentSEPTEMBER** [comment]
I should also mention I'm unfamiliar with RPCS3 and it's technical details so please explain in relatively simple terms ha ha

**Comment by AniLeo** [comment]
Does not follow the issue template at all, if it's a regression then the template is another, and even for bug report template this is completely wrong

**Comment by AgentSEPTEMBER** [comment]
Hey mate, I tried my best with what I had, can you help me out with this,
please? Or at least tell me how to format my problem properly?

**Comment by AniLeo** [comment]
The templates explain what you need to fill if you're reporting an issue if you read them.

Locking as explained above, since this is a support request, it's for one of our support platforms as indicated in the How to Ask for Support guide, not for the bug tracker.
