### ISSUE TITLE
[Regression] Random input freezing (#13917)

### ISSUE THREAD

**Issue by LunarMagma** [RPCS3/rpcs3#13937]
### Quick summary

The in-game inputs (besides the home button) stop working at random.

### Details

When I start a game, there is a completely random chance that my in-game inputs will freeze up and simply stop responding to what I do. They freeze, which means they don't disappear; an example of this is when I hold right, and it freezes, the game will continue to keep holding right without me doing anything. The only way to fix this is to reboot the game entirely, where it will happen again after a few minutes of play. This is a problem with the latest version, 15111.

### Build with regression

0.0.27-15111

### Attach two log files

Broken: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11634250/RPCS3.log.gz)

Fixed: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11634310/RPCS3.log.gz)

**Comment by elad335** [comment]
You need to enable logging when posting logs.

**Comment by ItsALH** [comment]
Can reproduce, here are the logs (the report is for LittleBigPlanet):

[Working master 15096](https://github.com/RPCS3/rpcs3/files/11637011/RPCS3.log.gz)
[Broken latest 15111](https://github.com/RPCS3/rpcs3/files/11637019/RPCS3.log)

As explained by OP, the input will completely freeze randomly and will repeat the last action or none if at the time of the input freezing nothing was pressed. Tt doesn't matter if you turn on and off the controller, you have to reboot the game. Also happens in LittleBigPlanet 2.

**Comment by AniLeo** [comment]
Thanks for the logs, triaged and tagged as Regression
@elad335

**Comment by elad335** [comment]
Retest with #13945

**Comment by ItsALH** [comment]
Works 👍
