### ISSUE TITLE
Demon's Souls fails to load in nonstandard EmulationDir

### ISSUE THREAD

**Issue by flavionm** [RPCS3/rpcs3#13936]
### Quick summary

Using the PSN version of the game, NPUB30910. It works fine when dev_hdd0 points to the default directory inside ~/.config/rpcs3, but moving it to a secondary HDD causes a bunch of `E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR` errors. I don't really have any other games to test.

### Details

RPCS3 version: 0.0.27-14783-0178b209 Alpha

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11630582/RPCS3.log.gz)

### System configuration

Arch Linux
Ryzen 5 5600X / RX 6600 XT
BTRFS file system

**Comment by Mrlinkwii** [comment]
Is this still an issue?
