### ISSUE TITLE
[Regression] Uncharted 3 [BCE01175] cutscene videos play at half speed in 15112 onwards

### ISSUE THREAD

**Issue by davewuk** [RPCS3/rpcs3#13943]
### Quick summary

Uncharted 3 has a mixture of in-engine and video cutscenes. In version 15096 video cutscenes play normally but version 15112 they play at half speed. The other Uncharted games don't seem to be affected.

The offending PR appears to be #13917

To reproduce simply start a new game and watch the opening cutscene.

### Details

Video of the issue:-

https://github.com/RPCS3/rpcs3/assets/55807111/8a66eb30-4132-4217-a504-eb492c76c38c

### Build with regression

v0.0.28-15112-33558d14

### Attach two log files

[RPCS3-15096.zip](https://github.com/RPCS3/rpcs3/files/11642668/RPCS3-15096.zip)
[RPCS3-15112.zip](https://github.com/RPCS3/rpcs3/files/11642669/RPCS3-15112.zip)

### System configuration

i7 12700k
16gb 3200mhz DDR 4
RTX 2060 Super 8gb

**Comment by davewuk** [comment]
Just to add - I normally use the "skip intro" patch but with it disabled the "naughty dog" intro video also plays in slow motion.

**Comment by FlexBy420** [comment]
Did you try disabling vsync?

**Comment by davewuk** [comment]
> Did you try disabling vsync?

Yes, it makes no differences. I tried with the frame rate limiter off and on auto as well.

**Comment by elad335** [comment]
Retest with #13945

**Comment by davewuk** [comment]
> Retest with https://github.com/RPCS3/rpcs3/pull/13945

That seems to have done the trick
