### ISSUE TITLE
[Regression] R&C Collection audio disappears

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#13942]
### Quick summary

This problem was seen with a discord user, when testing, I also have this, it seems to me that the build https://github.com/RPCS3/rpcs3/pull/13917 is the responsable

### Details

You play any game of the trilogy, a period of time passes and then, the audio goes away, so that later, the game freezes.

### Build with regression

0.0.27-15111

### Attach two log files

Working -> 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11641756/RPCS3.log.gz)

Broken ->
[R&C3 Missing audio and freeze.log.gz](https://github.com/RPCS3/rpcs3/files/11641764/R.C3.Missing.audio.and.freeze.log.gz)

### Attach capture files for visual issues

None

### System configuration

Windows 10 21H2
Intel Core i7-8700
15.93 GiB RAM
GPU: NVIDIA GeForce GTX 1070 Ti (535.98)

**Comment by AniLeo** [comment]
I also got the audio disappearing when testing God of War: Ascension but it was also present on the master build prior to that PR, so it's worth verifying if it was already present before for R&C as well.

**Comment by elad335** [comment]
Does it happen with 3 ppu threads?

**Comment by elad335** [comment]
Retest with #13945

**Comment by Jonathan44062** [comment]
the PR fixes the audio problem and stability is back to normal
