### ISSUE TITLE
Lighting issue in Gran Turismo 5

### ISSUE THREAD

**Issue by readywer** [RPCS3/rpcs3#13941]
### Quick summary

There is a weird lighting issue in GT5 at various points during a race the tracks. It makes everything appear to be shadowed sometimes. It affects the the frontview and the rear-view mirror, sometimes both. I have tried strict rendering, wcb,rcb,wdb,rdb and non of them fixed it.
Reference that who should it look like:
![Képernyőfelvétel (213)](https://github.com/RPCS3/rpcs3/assets/90259918/ed6b1480-af0c-43ff-a3fd-bc490ffa53f9)
When effects the front view:
![Képernyőfelvétel (214)](https://github.com/RPCS3/rpcs3/assets/90259918/c6dda15d-bfae-4cd0-82af-8bc44551bd82)
Rear mirror working:
![Képernyőfelvétel (210)](https://github.com/RPCS3/rpcs3/assets/90259918/38cc4f33-a842-462e-b31b-ddd209fd4c2e)
Rear mirror broken:
![Képernyőfelvétel (211)](https://github.com/RPCS3/rpcs3/assets/90259918/9c17f9ca-77d0-448a-84bf-d1a4548fb79f)

### Attach a log file

Log1:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11639119/RPCS3.log)
Log2:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11639120/RPCS3.log.gz)

### Attach capture files for visual issues

Link for the two rsx captures:
https://drive.google.com/drive/folders/1_Wj7EWrRAgwF5YTXCXecC8gwO00TkxfP?usp=drive_link

### System configuration

Config:
intel i513600k
32gb ram
rtx 3070

**Comment by solarmystic** [comment]
related to #11912

**Comment by Satan86** [comment]
This one should be closed in favour of #11912, just need to mention GT5 also being affected on there.

**Comment by kd-11** [comment]
Closing as duplicate.
