### ISSUE TITLE
Ratchet And Clank Tools of destruction Shard Reaper unusable.

### ISSUE THREAD

**Issue by mathew2214** [RPCS3/rpcs3#13940]
### Quick summary

firing the weapon "Shard Reaper" while in-game causes ratchet to despawn, making the game unplayable.

### Details

Ractchet will despawn, and the audio becomes very bugged. the game is unplayable until a new level is loaded. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11638644/RPCS3.log)

### System configuration

Steam Deck

**Comment by AniLeo** [comment]
Non-official build being used + incorrect settings that go against wiki documentation.

Closing as Invalid.
