### ISSUE TITLE
Xillia DLC Limit

### ISSUE THREAD

**Issue by Tzerinas** [RPCS3/rpcs3#13951]
### Quick summary

Tales of Xillia doesn't allow me to use a larger amount of DLC. Instead printing out an error message.

### Details

I don't know if this is a regression or a new bug or user error on my part so I decided to fill this as a regular bug report rather than as an regression. Long story short if I use too many DLC, Xillia will refuse to boot the game. After some short research I've noticed that this has been an issue in the past that was fixed.  #4091 

**HOWEVER**, all these reports mention crashing. My game doesn't crash. Instead I get this error message:

![Screenshot 2023-06-05 130947](https://github.com/RPCS3/rpcs3/assets/98034944/d30f6df9-e94e-4ed8-9221-11e96893538d)

So, yeah. Can't say anything about Xillia 2 as I don't have the game.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11651941/RPCS3.log)

**Comment by AniLeo** [comment]
Log file shows that one of the DLC licences is missing

**Comment by Tzerinas** [comment]
Thanks, I'm an idiot. Works perfectly. Sorry for the inconvenience and  have a nice day.
