### ISSUE TITLE
[Feature request] Pressure sensitivity toggle hotkey

### ISSUE THREAD

**Issue by Reki1994** [RPCS3/rpcs3#13956]
### Quick summary

Some games like Metal Gear Solid 4 where you can hold the enemy as a human shield, if you just hold down R1 without using a key to lower the pressure sensitivity to 15%, you will choke out the enemy even though you only mean to hold them. It would be a great feature to allow for the pressure sensitivity to be enabled or disabled using just one hotkey, instead of having to hold it.

### Details

It could be one hotkey meant for holding the button to enable pressure sensitivity and another hotkey for toggling the pressure sensitivity on or off. It would allow for easier control of the player character in some games like Metal Gear Solid 4.

**Comment by Megamouse** [comment]
Would it be ok if it's just a checkbox instead of a second button?

**Comment by Reki1994** [comment]
> Would it be ok if it's just a checkbox instead of a second button?

As long as you can toggle it with a hotkey while in the game, preferably on the controller.
