### ISSUE TITLE
[Regression] rpcs3 Verification failed

### ISSUE THREAD

**Issue by ccartola** [RPCS3/rpcs3#13957]
### Quick summary

Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\CPU\CPUThread.cpp:1315[:2], in function cleanup)

### Details

God of War Collection. Choose God of War, and doesn't start.

### Build with regression

v0.0.28-15129-e75c0dba Alpha

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11655371/RPCS3.log)

### Attach capture files for visual issues

![RPCS3](https://github.com/RPCS3/rpcs3/assets/36537078/9b64bd7a-1543-4755-a0f8-92d7c42f9fe2)

### System configuration

AMD Ryzen 9 7900X 12-Core Processor | 24 Threads | 31.14 GiB RAM | TSC: 4.691GHz | AVX-512+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0

**Comment by AniLeo** [comment]
Log is empty, missing full log

Do you use a third party antivirus software than not the one built into Windows? If yes, which one

**Comment by ccartola** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11655421/RPCS3.log)

**Comment by ccartola** [comment]
No, just Defender.

**Comment by ccartola** [comment]
It was fine with rpcs3-v.0.0.27-15082-5a365506_win64

**Comment by AniLeo** [comment]
The range is more than one build, the regression report must specify the last good build and the first bad build

**Comment by ccartola** [comment]
v.0.0.27-15082-5a365506 --> GOOD
v0.0.28-15129-e75c0dba --> LAST: BAD

with the update something went wrong.

**Comment by ccartola** [comment]
Bug report perhaps? Sorry for all the inconveniences.

**Comment by AniLeo** [comment]
There's 13 builds in the range you provided. Either way, it might be fixed with the next build, otherwise you'll need to provide the correct range of 1 build.

Also, don't send multiple comments/pings in a row, you can use the edit button if you need to add more information.

**Comment by ccartola** [comment]
Of course, sorry for all.
