### ISSUE TITLE
Can't build RPCS3 with VS 2019

### ISSUE THREAD

**Issue by Reki1994** [RPCS3/rpcs3#13953]
I want to add a feature to the pad settings but for some reason I can't build RPCS3 as it gives out the following error.

![ac68646f-ac8d-4815-9496-81f8cb4c9f10](https://github.com/RPCS3/rpcs3/assets/58955412/68a0f27e-1328-4d73-a1a2-0c5d8e2f07c0)

I have tried using the precompiled libraries and building them myself with no success... Is the building.MD still up to date?
Everything else builds, 21 of 22. It's just this linker error "cannot open input file "LLVMAggressiveInstCombine.lib" that fails.

**Comment by Megamouse** [comment]
no problems here with VS 2022

**Comment by Reki1994** [comment]
Thanks to kd-11 for helping me fix it. 

If you get this error : 
build spirv, glslang and llvm_build_clang_cl and then do git submodule sync.
