### ISSUE TITLE
[CLI] --pad-profile not working when the game has its own pad profile

### ISSUE THREAD

**Issue by JPZV** [RPCS3/rpcs3#13950]
### Quick summary

On my Windows machine I have installed RPCS3 with backups from my games (in this case, Guitar Hero Warriors of Rock) and [Sunshine](https://github.com/LizardByte/Sunshine).

In order to play with my DS4 on Guitar Hero, I had to create my own mapping (it's a mess, but let's say R1 is Green while Circle is Red). It works perfectly while I game on my computer locally (i.e. with the DS4 connected by USB)

The problem begins when I try to config my Sushine setup: In order to have full control with Sunshine over RPCS3, I have to run it as CLI with the following command: `G:\GamesLibrary\RPCS3\rpcs3.exe --no-gui --game-screen 0 "%RPCS3_GAMEID%:[GAME_SERIAL]"`. In any game with no custom pad profile it works nice, but in Guitar Hero, the buttons are completely everywhere. The Green, which should be R1, is now X, and Red is now Triangle. This seems to be because of how XInput works or because when I play with my GH Guitar, I have to set as "MMJoystick" with its own mapping.

The thing is, there is a --pad-profile option for CLI, which I tried with many many many different ways, like using full path, backslash instead of slash, using just the name, using the name with the extension, moving the .yml file to everywhere, but it doesn't seems to work.

Looking at the log, it seems that RPCS3 always uses the game's pad config instead of the override, even if the latter loads first.

If I'm correct, the hierarchy should be:

1) First, load the override if exists
2) If it doesn't, load the game's pad profile if exists
3) If it doesn't, load the global pad profile.

Here are my pad profiles: 
[input_configs.zip](https://github.com/RPCS3/rpcs3/files/11646469/input_configs.zip)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11646477/RPCS3.log.gz)

The important part is here:

```
·! 0:00:00.352392 CFG: Loading recording config from 'G:/GamesLibrary/RPCS3/config/recording.yml'
·! 0:00:00.397501 {Pad Thread} Input: Using pad profile: 'G:/GamesLibrary/RPCS3/config/input_configs/global/BLUS30487_Sunshine.yml'
·! 0:00:00.397506 {Pad Thread} Input: Loading pad config (title_id='BLUS30487', profile='G:/GamesLibrary/RPCS3/config/input_configs/global/BLUS30487_Sunshine.yml', strict=0)
·! 0:00:00.397627 {Pad Thread} Input: Loading pad profile: 'G:/GamesLibrary/RPCS3/config/input_configs/BLUS30487/Default.yml'
·! 0:00:00.400497 {Pad Thread} Input: Loading pad config (title_id='BLUS30487', profile='G:/GamesLibrary/RPCS3/config/input_configs/global/BLUS30487_Sunshine.yml', strict=0)
·! 0:00:00.400576 {Pad Thread} Input: Loading pad profile: 'G:/GamesLibrary/RPCS3/config/input_configs/BLUS30487/Default.yml'
·! 0:00:00.403805 {Pad Thread} Input: mmjoy: Driver supports 16 joysticks
·E 0:00:00.461814 {Pad Thread} Input: PadHandlerBase::bindPadToDevice: no PadDevice found for device 'Joystick #1'
·E 0:00:00.461820 {Pad Thread} Input: Failed to bind device 'Joystick #1' to handler MMJoystick. Falling back to NullPadHandler.
·! 0:00:00.461822 {Pad Thread} Input: Pad 0: device='Joystick #1', handler=MMJoystick, VID=0x0, PID=0x0, class_type=0x0, class_profile=0x0
```

At the last line, the Joystick #1 should have been loaded with XInput handler, not with MMJoystick

### System configuration

OS: Windows 11 x64 22H2 (22621.1702)
CPU: AMD Ryzen 7 5800X
GPU: Nvidia RTX 3080

Gamepads:
- Locally: Dualshock 4 (CUH-ZCT2U) acting as DS4 and Guitar Hero Warriors Of Rock Wireless Guitar Controller (Running with MMJoystick)
- Remote: Dualshock4 acting as XInput

**Comment by Megamouse** [comment]
Looking at your log file, you are using:
`rpcs3.exe --no-gui --game-screen=0 %RPCS3_GAMEID%:BLUS30487 --pad-profile="some/path/BLUS30487_Sunshine.yml"`
Whereas you should be using:
`rpcs3.exe --no-gui --game-screen=0 %RPCS3_GAMEID%:BLUS30487 --pad-profile=BLUS30487_Sunshine`

**Comment by Megamouse** [comment]
Ah, now I see what you mean.

**Comment by JPZV** [comment]
As I stated before, I've already tried that, with the same result and with a similar 
[log](https://github.com/RPCS3/rpcs3/files/11658944/RPCS3.log.gz) (using `G:\GamesLibrary\RPCS3\rpcs3.exe --no-gui --game-screen 0 "%RPCS3_GAMEID%:BLUS30487" --pad-profile "BLUS30487_Sunshine"`)
