### ISSUE TITLE
[Regression] Gran Turismo 6 crashing after PR 13840

### ISSUE THREAD

**Issue by Hadrianneue** [RPCS3/rpcs3#13960]
### Quick summary

Gran Turismo 6 [BCES01893] crashes after updating from build 0.0.28-15120 to newer ones.

### Details

Gran Turismo 6 crash with message dialog "RPCS3 has abnormally terminated."

### Build with regression

0.0.28-15124

### Attach two log files

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/11657268/RPCS3.zip)

### System configuration

Operating system: EndeavourOS  6.3.5-arch1-1
Processor: AMD Ryzen 5 5600 6-Core Processor 
GPU: AMD Radeon RX 6500 XT (RADV NAVI24)' Mesa 23.1.99

**Comment by brian218** [comment]
Please test #13961

**Comment by Hadrianneue** [comment]
> Please test #13961

tested artifact rpcs3-v0.0.28-15132-1528de9d_linux64, fixed

**Comment by brian218** [comment]
@AniLeo I think versions after (including) #13961 can be marked as not affected/regressed.

**Comment by AniLeo** [comment]
There's a different regression that is fixed by #13964, that's why they're marked as broken
