### ISSUE TITLE
[Regression] God of War Collection [BCUS98229] - GOW1 fails to boot with Verification error from v0.0.28-15129 onwards #13948

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#13962]
### Quick summary

After launching God of War from the collection's game selector menu, rpcs3 crashes randomly with a Verification error. 

### Details

First responsible build is v0.0.28-15129-e75c0dba ⁪ ⁪#13948 

![image](https://github.com/RPCS3/rpcs3/assets/4345150/936ebd3c-3911-4433-92b2-db5877024150)

Last working build is v0.0.28-15124-c8577592 ⁪ ⁪ ⁪

![image](https://github.com/RPCS3/rpcs3/assets/4345150/1ab816fd-bfc5-454b-8f83-d4ab8255e416)

### Build with regression

v0.0.28-15129-e75c0dba ⁪ ⁪ ⁪

### Attach two log files

Not working (15129)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11657656/RPCS3.log)

Working (15124)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11657662/RPCS3.log.gz)

### System configuration

SYS: RPCS3 v0.0.28-15124-c8577592 Alpha | master
SYS: 12th Gen Intel(R) Core(TM) i7-12700KF | 20 Threads | 31.86 GiB RAM | TSC: 3.610GHz | AVX+ | FMA3
SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2080 Ti' running on driver 527.56.0.0
SYS: Firmware version: 4.88

**Comment by elad335** [comment]
Test with #13964
