### ISSUE TITLE
Cars 2- Grems glitchy texture

### ISSUE THREAD

**Issue by awexstudio** [RPCS3/rpcs3#13976]
### Quick summary

Grem from cars 2 has a glichy texture on his bumpers and the other npc grems (purple, red and rammer) all have a back glitchy texture all over them these glictch texture dont apper from farr away
![BLES01242_screenshot_2023_04_28_21_03_34](https://github.com/RPCS3/rpcs3/assets/132783218/0814fadc-befc-4b77-82d4-cc0873e3a2ea)
![BLES01242_screenshot_2023_04_28_22_48_25
![BLES01242_screenshot_2023_04_28_22_48_45](https://github.com/RPCS3/rpcs3/assets/132783218/c98fc77f-ac83-4632-ac75-8061aee46e5d)
](https://github.com/RPCS3/rpcs3/assets/132783218/5b1370be-0a49-4730-8db1-accf14516dc1)
![BLES01242_screenshot_2023_04_28_22_48_35](https://github.com/RPCS3/rpcs3/assets/132783218/df37313b-ccbd-4199-8cd1-c2ef08117804)
![BLES01242_screenshot_2023_04_29_15_15_31](https://github.com/RPCS3/rpcs3/assets/132783218/2117186c-01f4-4081-9ec7-f58dfd91f4b4)

### Details

i downgraded to 0.0.26-14780 and it was fixed and now i cant recreate as the shaders got cached
![BLES01242_screenshot_2023_06_07_17_46_13](https://github.com/RPCS3/rpcs3/assets/132783218/fb6615df-d710-4ea2-b87c-b53d2416af46)
![BLES01242_screenshot_2023_06_07_17_46_20](https://github.com/RPCS3/rpcs3/assets/132783218/f8a6913c-0b38-415e-b824-d3b3b8b35ced)
![BLES01242_screenshot_2023_06_07_17_46_28](https://github.com/RPCS3/rpcs3/assets/132783218/10492654-d074-4ff7-8691-8e34a2877c56)
![BLES01242_screenshot_2023_06_07_17_48_10](https://github.com/RPCS3/rpcs3/assets/132783218/0a778111-0a41-4381-b1e1-e39daf6c165a)
![BLES01242_screenshot_2023_06_07_17_48_29](https://github.com/RPCS3/rpcs3/assets/132783218/efac476e-87ff-4219-9b45-4ee032efb48d)

### Attach a log file

as said above since playin old ver cant get glitch anymore

### System configuration

![image](https://github.com/RPCS3/rpcs3/assets/132783218/a89cdfd5-6f28-4edd-a36c-09cb4bc6e46f)
![image](https://github.com/RPCS3/rpcs3/assets/132783218/83086df2-8e8e-4a82-a28e-85d9042dba68)
![image](https://github.com/RPCS3/rpcs3/assets/132783218/148c40ac-c778-4cc8-b9f9-a7a914d07b8b)
![image](https://github.com/RPCS3/rpcs3/assets/132783218/cddc3ed6-7e9a-4f0e-974c-7413b1c0a0c9)

### Other details

will update if i can get glitch again

**Comment by Asinin3** [comment]
>As said above since playin old ver cant get glitch anymore

This issue report is useless unless you actually tell us what build of RPCS3 started to have this issue.
Start by testing the latest build of RPCS3: If it's fixed now, close this issue. If it's not fixed, try a build in-between 0.0.26-14780 and a build from a month or two after that. Use the process of elimination to work out where the game broke, we need to know the exact build that started to have this issue.

You only need to replace the RPCS3.exe file when swapping between builds. Changing versions is easy.

**Comment by Asinin3** [comment]
Also, post a damn log file next time.

**Comment by Megamouse** [comment]
Closing since it's not following issue guidelines
