### ISSUE TITLE
 Dynasty Warriors jp games names are mislabed on the website

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13978]
There is an issue with the compatibility report where Dynasty Warriors game secondary label is incorrect and is separated from the jp counterpart due to name differences.

The games:
Dynasty Warriors 6 (Shin Sangoku Musou 5) Game IDs (BLES00540, BLUS30306, BLJM60041)
Dynasty Warriors 6 Empires (Shin Sangoku Musou 5)
Dynasty Warriors 7 (Shin Sangoku Musou 6)
Dynasty Warriors 7 Empires (Shin Sangoku Musou 6 Empires) Game IDs (NPEB90479, NPJB90549, NPUB90937, BLES01795)
Dynasty Warriors 8  Game IDs (BLJM60586, BLUS31185, BLES01865)
Dynasty Warriors 8: Empires (Shin Sangoku Musou 7 Empires) Game IDs (BLJM61225)
Dynasty Warriors 8: Xtreme Legends(Shin Sangoku Musou 7 with Moushouden) Game IDs (BLUS31402, BLJM61129)

This mislabeling for the jp versions is because the first dynasty warriors were called Sangoku Musou and the second one was called shin Sangoku Musou and after shin Sangoku Musou they were numbered. so the jp version of the game is always one behind the USA and EU counterparts.

Sourecs: https://koei.fandom.com/wiki/Dynasty_Warriors_7
[https://ricedigital.co.uk/isnt-it-weird-...er-behind/](https://ricedigital.co.uk/isnt-it-weird-that-dynasty-warriors-9-is-called-dynasty-warriors-8-in-japan-theyre-always-one-number-behind/)

Note: this is a repost from January from the forum as no one responded to fix the issue. Also, Note The ids are for games that should be renamed or moved to one grouping.

**Comment by Megamouse** [comment]
wrong repository:
https://github.com/AniLeo/rpcs3-compatibility

**Comment by AniLeo** [comment]
My repo has issues disabled due to spam so you can add on daginatsuko/rpcs3-www

I'll fix these titles when I can though
