### ISSUE TITLE
Unable to install Bluray versions of Tom Clancy's Endwar

### ISSUE THREAD

**Issue by ChwaraeTeg** [RPCS3/rpcs3#13977]
### Quick summary

The emulator is unable to get past the (required) installation of Tom Clancy's Endwar on the disc version

### Details

The BluRay versions of Tom Clancy's Endwar require game data to be installed to the hard drive to play. In RPCS3, the initial prompt informing of this is displayed correctly but after pressing X to continue, the display goes blank. It doesn't seem to have frozen as the framerate keeps changing, and the log file is repeatedly spammed with "·W 0:01:01.000000 {PPU[0x1000000] Thread (main_thread) [HLE:0x01cc025c, LR:0x00362878]} cellSysutil: cellMsgDialogAbort()" thousands of times a second. 

Tried leaving it running for several hours (with logs silenced to avoid running out of disk space) to see if it would install anyway, but no files appeared to get copied.

Here's the initial prompt and blank screen from RPCS3:
![emulator1](https://github.com/RPCS3/rpcs3/assets/104720038/f240e280-3b42-45a4-b045-7bca40553bec)
![emulator2](https://github.com/RPCS3/rpcs3/assets/104720038/06a23575-8bac-4bfd-8162-92f1f3f7e001)

This is the initial prompt and subsequent install screen from console:

![console1](https://github.com/RPCS3/rpcs3/assets/104720038/7202640a-a192-4147-81b0-520cd1b76e8c)
![console2](https://github.com/RPCS3/rpcs3/assets/104720038/4061272f-cf20-4921-8e96-3b20907d5460)

### Attach a log file

[TomClancysEndwarBLUS.log.gz](https://github.com/RPCS3/rpcs3/files/11680793/TomClancysEndwarBLUS.log.gz)

### System configuration

Intel Xeon CPU E3-1240 v5 @ 3.50GHz | 16 GiB RAM | Operating system: Windows, Major: 10, Minor: 0, Build: 19045 | NVIDIA GeForce GTX 1060 6GB running on driver 531.79.0.0

**Comment by Megamouse** [comment]
Does it work if you disable the native UI in the emulator settings ?
If it does, then this might be a regression from some overlay changes.

![image](https://github.com/RPCS3/rpcs3/assets/23019877/c4b56eb6-25b1-4f52-aceb-fc4df58cf7ec)

**Comment by jeremys18** [comment]
I can confirm this. Though I don't even get as far as it showing a copy files screen.

I do get the hit x to accept but then my screen just goes black.
![image](https://github.com/RPCS3/rpcs3/assets/2172410/a099cba9-bc9d-4940-b1b7-62803a20e07a)
![image](https://github.com/RPCS3/rpcs3/assets/2172410/dbd94843-b151-4625-9e60-6ad4299b222b)


It does however create files when the game gets to that screen but only a few and never actually copies anything after hitting x. To be clear, the only files it makes is before the user hits x.

![image](https://github.com/RPCS3/rpcs3/assets/2172410/2eb349f7-53f8-4361-92f5-482b2c1b6d44)


I get the same result if I do the above suggestion or not. And while I don't get a crash I do get errors in the console log.
![image](https://github.com/RPCS3/rpcs3/assets/2172410/59256dfe-3ae7-4644-8d25-a0a9c7d4e9d6)
