### ISSUE TITLE
DOOM: Classic Complete is unplayable

### ISSUE THREAD

**Issue by ViperAcidZX** [RPCS3/rpcs3#13970]
### Quick summary

DOOM: Classic Complete does not work on RPCS3.

### Details

I was wanting to try out this compilation of Doom games out of curiosity but the emulator does not work for this game since all I get is a black screen and none of my inputs are being registered outside of the PS button. I've tried various settings that I can think of, different renders, updating the PS3 firmware, even some settings that was reported in [this forum post from 2021](https://forums.rpcs3.net/showthread.php?tid=169932&page=2) (which also reported the same problems), nothing worked. I don't see why this is considered playable on the compatibility listings when it can't even be played at all.

![rpcs3-2023_06_06_11-25-57](https://github.com/RPCS3/rpcs3/assets/19318128/b7dec7b6-395b-48d9-aa85-70128fbdb4a4)

This is how it is supposed to look like it when actually works:

https://www.youtube.com/watch?v=N0pRmdmoEjU

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11666641/RPCS3.log.gz)

### System configuration

**OS:** Windows 10 Home, 64-bit, Version 22H2
**RAM:** 8 GB DDR3 RAM @ 1600 MHz
**GPU:** Nvidia GeForce GTX 1080, 6 GB VRAM, Driver Version: 531.41
**CPU:** AMD FX-4350

**Comment by MSuih** [comment]
Possibly caused by the incorrect resolution selection, or maybe aome other issue. Ask for support on our support channels instead of opening an issue on github

**Comment by ViperAcidZX** [comment]
> Works just fine for me ![obraz](https://user-images.githubusercontent.com/68403300/243758307-df1fa344-bfe9-4d56-ba24-d85fe61fe2aa.png) [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11666814/RPCS3.log.gz)

Can you please explain how or what you did get it to work? I'm trying everything I can think and looking through the log doesn't give me anything to help.

**Comment by ViperAcidZX** [comment]
> Possibly caused by the incorrect resolution selection, or maybe some other issue. Ask for support on our support channels instead of opening an issue on github

I did, and no one was willing to help based on my CPU's age.
