### ISSUE TITLE
Issue with DX12 in Raiden IV: Overkill (NPUB31371)

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1398]
Tested on recent master build. Freezes at "press start button" screen.
Log: http://rghost.ru/6tnDkMZR9

```
D3D12 ERROR: ID3D12Device::CreateCommittedResource: Textures created with certain Formats must align the resource dimensions properly.
D3D12_RESOURCE_DESC::Format is BC3_UNORM. D3D12_RESOURCE_DESC::Width is 671, and must be a multiple of 4.
D3D12_RESOURCE_DESC::Height is 50, and must be a multiple of 4. [ STATE_CREATION ERROR #597: CREATERESOURCE_INVALIDDIMENSIONS]
```

**Comment by tambry** [comment]
@B1ackDaemon Still an issue?

**Comment by B1ackDaemon** [comment]
@tambry , yep, still occurs on recent master build (PR #1447).

**Comment by AniLeo** [comment]
I can't test this, the emulator keeps freezing for me before the menu part at different stages of the loading menus and I have to force terminate the process

**Comment by raven02** [comment]
Just tested it and it is no more freezing .
