### ISSUE TITLE
"Segfault Reading Location" Error

### ISSUE THREAD

**Issue by deusnovus** [RPCS3/rpcs3#13982]
### Quick summary

RPCS3 crashes upon launching any PS3 game

### Details

Upon launching any game, the app crashes right after this error:

Segfault reading location 0000000000000140 at 00007ff81a0a2796.
Thread: Main Thread.

![Screenshot from 2023-06-08 14-36-48](https://github.com/RPCS3/rpcs3/assets/32219080/9a377a09-105d-4235-ad4e-667a0bcd17e2)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11688371/RPCS3.log)

### System configuration

Dell Inspiron 16 Plus 7610
CPU: 11th Gen Intel® Core™ i7-11800H
GPU1: NVIDIA GeForce RTX™ 3050 Ti Laptop GPU
GPU2: Intel® UHD Graphics (TGL GT1)
OS: Fedora 38
App version: RPCS3 Version: 0.0.28-1-6f834e99 Alpha | master | local_build (via Flathub)

**Comment by Megamouse** [comment]
Flatpaks are not supported
