### ISSUE TITLE
1912: Joint Strike (NPUB90104) no longer works in DX12

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1399]
Last PR, in which was possible to boot game was #1336. Some other games also could be affected.
In #1344 and #1350 attempt to load game crashes rpcs3.
```
Unhandled exception at 0x00007FFC61A498FE (ucrtbase.dll) in rpcs3.exe: Fatal program exit requested.
```
In #1347 and later it just hangs, Output log in VS shows this
```
Exception thrown at 0x00007FFC63241F08 in rpcs3.exe: Microsoft C++ exception: fmt::exception at memory location 0x000000005726F960.
```

Logs: http://rghost.ru/7FHqlcsNb

**Comment by vlj** [comment]
A filter enum was accidently removed I will fix this in next d3d12 pr

**Comment by B1ackDaemon** [comment]
@vlj, thanks, waiting for your next PR ;)

**Comment by tambry** [comment]
@B1ackDaemon Fixed?

**Comment by B1ackDaemon** [comment]
@tambry , yep, works fine on recent master build (PR #1447).
