### ISSUE TITLE
MGS4 crashes after "completing" the MGS1 segment in Act 4

### ISSUE THREAD

**Issue by ZenigataBloch** [RPCS3/rpcs3#13996]
### Quick summary

Good evening,

I'm currently running RPCS3 version 0.0.28-15170-b2842dcd and I'm encountering the attached error, in the image below, after Snake enters the vent in Shadow Moses during the MGS1 segment in Act 4, that fades to black leading to the main game.

![immagine](https://github.com/RPCS3/rpcs3/assets/43986930/eb811c99-ed8e-4729-8a97-f11d38ae53bb)

Please also find attached the RPCS3.log file, captured after the emulator crashes because of the error.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11713043/RPCS3.log)

### System configuration

Win10 | Ryzen 5 3600 3.5Ghz | 32Gb RAM | AMD 5700XT 8Gb

**Comment by ItsALH** [comment]
Can't reproduce, also post that log in the discord.

**Comment by AniLeo** [comment]
Crashing on third party hook, not our bug.

**Comment by ZenigataBloch** [comment]
> Can't reproduce, also post that log in the discord. It looks like the emulator crashed due to issues with overwolf overlay, you should run vkdiag to fix it or uninstall Overwolf

And not it works. God, fucking Overwolf.
