### ISSUE TITLE
RPCS3 Emulator Crash After ~1-2 mins of gameplay

### ISSUE THREAD

**Issue by Ryzoluca** [RPCS3/rpcs3#13997]
### Quick summary

Just updated to the most recent version of RPCS3 and haven't had crash issues this bad. Crashing happens about a minute or two into any game I play, and the whole emulator becomes unresponsive, and I have to manually stop it in my task manager. I updated my drivers to the most recent updates, as well as my laptop. Error code did not bring me anywhere online.

### Details

Specific Error Code Returned:

F {RSX [0x02f3430]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Unknown Code (C462C118h, -1000161000)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\descriptors.cpp:241[:4], in function next_subpool)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\descriptors.cpp:241[:4], in function next_subpool)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:111[:24], in function die_with_error)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11717512/RPCS3.log)

### System configuration

Device name	LAPTOP-7970S35T
Processor	Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
Installed RAM	8.00 GB (7.78 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by AniLeo** [comment]
gzipped archive is corrupted as it cannot be extracted, needs log file that can be opened

```
gunzip RPCS3.log.gz
gzip: RPCS3.log.gz: not in gzip format
```

**Comment by Ryzoluca** [comment]
> gzipped archive is corrupted as it cannot be extracted, needs log file that can be opened
> 
> ```
> gunzip RPCS3.log.gz
> gzip: RPCS3.log.gz: not in gzip format
> ```
> 
> Also missing system configuration part of the template

Weird, sorry about the corrupted file, I updated it within the original post and added the sys configs.

**Comment by AniLeo** [comment]
The uploaded file is not a log file, it's a copy paste from the emulator UI, need RPCS3.log generated by the emulator

**Comment by Ryzoluca** [comment]
Log file being generated gets corrupted and has nothing in it. Behaves similarly to the first log file, don't know why this is happening either.

**Comment by AniLeo** [comment]
Only the compressed log file can get corrupted after a crash, not the uncompressed one

**Comment by kd-11** [comment]
The returned error is VK_ERROR_FRAGMENTATION_EXT. Happens when the system has an error creating descriptors with the update-after-bind model.
This makes me very curious what hardware/driver combo is in use here. A fix is to just disable indexing capabilities on the device at the cost of much worse performance.

**Comment by kd-11** [comment]
From spec:
```
maxUpdateAfterBindDescriptorsInAllPools is the maximum number of descriptors (summed over all descriptor types) that can be created across all pools that are created with the VK_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT bit set. Pool creation may fail when this limit is exceeded, or when the space this limit represents is unable to satisfy a pool creation due to fragmentation.
```

Currently we let the system just allocate as much as it can, but it is possible that some drivers have the limit set to a very low value. In that scenario, we have to introduce a spill pool that disables the fast path temporarily until resources become available.

**Comment by kd-11** [comment]
Looking at the driver limits, it is also likely that the system is just running low on memory since integrated graphics share system RAM. A workaround will be provided.

**Comment by Ryzoluca** [comment]
> Looking at the driver limits, it is also likely that the system is just running low on memory since integrated graphics share system RAM. A workaround will be provided.

Thank you. I have been also trying to attempt to get the correct log file, but it has no information within it upon crash (displays 0 bytes, extraction software says the file is empty) even after trying to extract it with several different types of extraction software. Is the log being flushed out upon crash?

**Comment by MSuih** [comment]
The compressed log file might get corrupted if the emulator can't properly close it when crashing.  The uncompressed log (RPCS3.log or RPCS3 with text file icon) should always remain readable.

**Comment by Ryzoluca** [comment]
> The returned error is VK_ERROR_FRAGMENTATION_EXT. Happens when the system has an error creating descriptors with the update-after-bind model. This makes me very curious what hardware/driver combo is in use here. A fix is to just disable indexing capabilities on the device at the cost of much worse performance.



> The compressed log file might get corrupted if the emulator can't properly close it when crashing. The uncompressed log (RPCS3.log or RPCS3 with text file icon) should always remain readable.



> The compressed log file might get corrupted if the emulator can't properly close it when crashing. The uncompressed log (RPCS3.log or RPCS3 with text file icon) should always remain readable.

Ran the crash again and got it, updating now.

**Comment by kd-11** [comment]
@Ryzoluca Test with a build from this PR: https://github.com/RPCS3/rpcs3/pull/14012

**Comment by Ryzoluca** [comment]
> @Ryzoluca Test with a build from this PR: #14012

Will test this now, thank you.

**Comment by Ryzoluca** [comment]
> @Ryzoluca Test with a build from this PR: #14012

Everything works now, thanks!
