### ISSUE TITLE
FP: src type 3 used 

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1400]
Discovered in game Astro Tripper (NPUB30062)
See screenshots and log:
http://www.emunewz.net/forum/showthread.php?tid=158807&pid=228722#pid228722

**Comment by danilaml** [comment]
@vlj ?
from thread:
```
RSX: E {rsx::thread} Src type 3 used, please report this to a developer.
RSX: E {rsx::thread} Src type 3 used, please report this to a developer.
RSX: E {rsx::thread} Src type 3 used, please report this to a developer.
RSX: E {rsx::thread} FS build failed:D:\rpcs3\FragmentProgram.hlsl(96,75): error X3000: syntax error: unexpected token '.'
D:\rpcs3\FragmentProgram.hlsl(96,71-80): error X3013: 'abs': no matching 0 parameter intrinsic function
D:\rpcs3\FragmentProgram.hlsl(96,71-80): error X3013: Possible intrinsic functions are:
D:\rpcs3\FragmentProgram.hlsl(96,71-80): error X3013:     abs(float|half|double|min10float|min16float|int|uint|min12int|min16int|min16uint​)
```

**Comment by tambry** [comment]
@B1ackDaemon Could you attach all the fragment program files generated when running the game? (Delete the old ones before, so you only see the ones made by that one game)

**Comment by B1ackDaemon** [comment]
@tambry , done. 
http://rghost.ru/7QBkYRC7F

**Comment by vlj** [comment]
Did you delete the fragment shader before ? Did you use a hack to get past compilation error ?
I don't see any error in the fragment shader 10 :/

**Comment by tambry** [comment]
@vlj 99th line:
```
h47 = saturate(float4((-abs(.wwww) < r0.xxxx)));
```

I think you need a source before that .wwww, but I'm no shader expert.

**Comment by B1ackDaemon** [comment]
@vlj , yes, i did. Just tried with vanilla PR #1355 
Log: http://rghost.ru/6R2MnQlSR

**Comment by vlj** [comment]
@tambry yes you're right I didn't saw it at first.

it looks like a memory corruption, h47 register is not used before and after, and .www hints that the register type is unknow. I guess the last shader program opcode is overwritten by something else in rpcs3 which makes it invalid.

**Comment by AniLeo** [comment]
```
{rsx::thread} RSX: Src type 3 used, please report this to a developer.
{rsx::thread} RSX: Failed to compile shader: Fragment shader failed to compile with the following errors:
ERROR: 0:111: error(#132) Syntax error: "." parse error
ERROR: error(#273) 1 compilation errors.  No code generated
...
{rsx::thread} Exception: linkage failed: 'Fragment shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 
```

NPEA00004 - Lemmings
OpenGL

[NPEA00004 (Lemmings) OpenGL.zip](https://github.com/RPCS3/rpcs3/files/186357/NPEA00004.Lemmings.OpenGL.zip)

PARAM.SFO of the game needs to be changed in order for it to boot. Using RESOGUN's PARAM.SFO

**Comment by raven02** [comment]
@AniLeo/ @B1ackDaemon  , do you still able to boot up Lemmings ? as well as Astro Tripper

**Comment by scribam** [comment]
Is it still an issue?

**Comment by kd-11** [comment]
type3 has been stubbed for some time now.
