### ISSUE TITLE
[Regression] Savestates

### ISSUE THREAD

**Issue by readywer** [RPCS3/rpcs3#14007]
### Quick summary

Savestates have several regressions.
First creating it isn't possible after: RPCS3/rpcs3/pull/13672
After this pr loading old savestates is imposible: RPCS3/rpcs3/pull/13558
It show this message eaven on the newest build.
![image](https://github.com/RPCS3/rpcs3/assets/90259918/7ff9eb46-1aff-4ba7-9dad-fe14281f0752)
Games tried: Gran Turismo 5, Ratchet & Clank Future: Tools of Destruction

### Build with regression

v0.0.27-14881

### Attach two log files

Logs will be provided if needed as of this regression includes several builds.

**Comment by AniLeo** [comment]
Can you retest on latest? There have been a couple of fixes already to savestates
