### ISSUE TITLE
SILENT HILL HOMECOMING 60 fps [BLUS30169]

### ISSUE THREAD

**Issue by SONIC0798** [RPCS3/rpcs3#14000]
### Quick summary

hello, I have a question silent hill homecoming [BLES300460] has a patch with support for 60 fps, but in this version there is censorship in some scenes, and I wanted to know if you plan to add a patch with support for 60 fps to the version [BLUS30169]?

**Comment by AniLeo** [comment]
Out of scope. Patches are made by the community.
