### ISSUE TITLE
[Regression] FSR/Output Scaling is no longer a Dynamic option

### ISSUE THREAD

**Issue by MsDarkLow** [RPCS3/rpcs3#14014]
### Quick summary

Enabling/Disabling FSR was a dynamic option that could apply and change the game's visuals while it was still running. You can no longer do that unless you restart the game.

### Details

Fairly simple and straight forward, when using the master build or 0.26-14571, you can no longer enable/disable FSR while ingame.
1. Open the regression build or master build
2. Open a game
3. Try to swap between the various "Output Scalings" (FSR/Bilinear/Nearest) and set Apply
4. ???
5. Nothing happens anymore.

Resizing RPCS3's window does not help either.

With the regression #13217, now it only applies after restarting the game.

Previously it was possible to Enable and Disable FSR while ingame, being able to see the changes in real time. (There was no Bilinear/Nearest option).

Video example of it working:
https://github.com/RPCS3/rpcs3/assets/9060436/8c85852b-0fc1-405f-930c-ddcc8aa02820

Video example of it not working:
https://github.com/RPCS3/rpcs3/assets/9060436/3dc68205-3c08-419e-8f30-122d3edaef33

### Build with regression

rpcs3-v0.0.26-14571-240cb2d6_win64

### Attach two log files

[RPCS3 - Regression - 14571.log.gz](https://github.com/RPCS3/rpcs3/files/11729602/RPCS3.-.Regression.-.14571.log.gz)
[RPCS3 - Working - 14570.log.gz](https://github.com/RPCS3/rpcs3/files/11729611/RPCS3.-.Working.-.14570.log.gz)

### System configuration

Windows 11 | i9-13900K Stock | 24 Threads (HT Disabled) | 32 GB RAM 
NVIDIA GeForce RTX 3080 running on driver 531.29

**Comment by Calinou** [comment]
This is addressed by https://github.com/RPCS3/rpcs3/pull/14005 according to its description :slightly_smiling_face:
