### ISSUE TITLE
Bulletstorm

### ISSUE THREAD

**Issue by MiguelTavaresSergio** [RPCS3/rpcs3#14025]
### Quick summary

When you finish the prologue and begin load chapter 1, appear a message saying "The disc has been ejected" and don't load chapter 1. Great work with the emulator. Thanks.

### Attach a log file

U cellVoice TODO: cellVoiceReadFromOPort(ops=258, data=*0x1f79690, size=*0xd00402f0) x1623
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30651/USRDIR/FIOS-UNREALENGINE3/STORMGAME/MOVIES/LOADINGMOVIE11.TXT” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30651/USRDIR/FIOS-UNREALENGINE3/STORMGAME/MOVIES/LOADINGMOVIE11.BIK” [1]
U cellVoice TODO: cellVoiceReadFromOPort(ops=258, data=*0x1f79690, size=*0xd00402f0) x6
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30651/USRDIR/FIOS-UNREALENGINE3/STORMGAME/COOKEDPS3/SP_D_WRECK_2_P_LOC_INT.XXX” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30651/USRDIR/FIOS-UNREALENGINE3/STORMGAME/COOKEDPS3/SP_D_WRECK_2_P.XXX” [1]
E SYS: 'cellOskDialogAbort' failed with 0x8002b302 : CELL_MSGDIALOG_ERROR_DIALOG_NOT_OPENED [1]
E SYS: 'cellMsgDialogAbort' failed with 0x8002b302 : CELL_MSGDIALOG_ERROR_DIALOG_NOT_OPENED [1]

### Attach capture files for visual issues

![Error Bullestorm](https://github.com/RPCS3/rpcs3/assets/136655286/988726bb-1071-4482-a938-034e7b3f3a3f)

**Comment by AniLeo** [comment]
Missing log file

**Comment by AniLeo** [comment]
Closing due to the lack of information
