### ISSUE TITLE
RPCS3 can not start

### ISSUE THREAD

**Issue by PJ79-3** [RPCS3/rpcs3#14021]
### Quick summary

RPCS3 can not start

### Details

I downloaded build 0.0.28-15184 and double clicked rpcs3.exe in the folder but PRCS3 does not start.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11746526/RPCS3.log)

### System configuration

OS Windows11
Processor AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 2.10 GHz
Installed RAM 8.00 GB (5.94 GB usable)

**Comment by AniLeo** [comment]
Needs to be a support request in Forums or Discord instead, not a bug ticket, issue with drivers or third party layers.
