### ISSUE TITLE
Modnation Racers - Random Crash After Leaving A Race

### ISSUE THREAD

**Issue by Virjoinga** [RPCS3/rpcs3#14020]
### Quick summary

Sometimes after loading back into the Modspot the game will hang

### Details

I was playing on a track and then tried loading back into the Modspot and the game hanged/ froze. It said something about trying to create a new texture in the log. Also log file is too big so I'll paste a portion of it (when the error occurred).

### Attach a log file

[log.txt](https://github.com/RPCS3/rpcs3/files/11744227/log.txt)

### System configuration

CPU - Ryzen 9 7950X
GPU - RTX 3080
RAM - 32GB 6000MHz

**Comment by AniLeo** [comment]
Missing log file
Can, and should, be compressed

**Comment by Virjoinga** [comment]
> Missing log file Can, and should, be compressed

I did? It's that text file called log.txt... I have compressed the same file here :/
[log.zip](https://github.com/RPCS3/rpcs3/files/11755724/log.zip)

**Comment by Asinin3** [comment]
@Virjoinga What you posted isn't a log, its a copy paste of a few errors you saw in the RPCS3 window. We need the entire log file which shows everything from your settings to all the log output that you did not give us.

**Comment by Virjoinga** [comment]
Yeah sorry about that. If I can reproduce I'll send a log.

**Comment by Asinin3** [comment]
No, we don't need a log. Zcull Precise is the default setting, and you changed it to relaxed which literally says in the description of the setting (when you put mouse on it) that it can be unstable. We already know it has issues, its only there to be used with games that work well with it.

Approximate is generally fine to use, but can cause some visual issues in some games, but its generally faster.

**Comment by AniLeo** [comment]
Closing as it's still incomplete after half a year, since the log file for the issue was never uploaded
