### ISSUE TITLE
[Regression] "Create PPU Cache" doesn't work ever since #13630

### ISSUE THREAD

**Issue by FlexBy420** [RPCS3/rpcs3#14024]
### Quick summary

Create PPU Cache option immediately stops and closes the compilation window without compiling any modules.

### Details

https://github.com/RPCS3/rpcs3/assets/68403300/a4b54cf3-c335-46bc-b3dc-b3d3b1aaa5eb

### Build with regression

v0.0.27-14859-0e388639 (#13630)

### Attach two log files

[Working](https://github.com/RPCS3/rpcs3/files/11750552/RPCS3.log.gz)
[Broken](https://github.com/RPCS3/rpcs3/files/11750559/RPCS3.log.gz)

**Comment by elad335** [comment]
Fixed by #14034
