### ISSUE TITLE
Spider-Man Shattered Dimensions

### ISSUE THREAD

**Issue by PolStoica** [RPCS3/rpcs3#14027]
### Quick summary

The Graphics don't work 

### Attach a log file

U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) x2
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: 'sceNpInit' failed with 0x8002aa02 : SCE_NP_ERROR_ALREADY_INITIALIZED [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/Main.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/Legal.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/Common.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/WebOfSkills.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/FrontScreen.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/Common.pak” [2]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/FrontScreenEnvAmazing.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/BaseGameplay.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/BaseHero.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/BaseEnemies.pak” [1]
E SYS: 'sys_ppu_thread_detach' failed with 0x8001000a : CELL_EBUSY [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/FrontScreenEnvNoir.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/FrontScreenEnvUltimate.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/FrontScreenEnv2099.pak” [1]
S SPU: New block compiled successfully x3
E SYS: 'sys_ppu_thread_detach' failed with 0x8001000a : CELL_EBUSY [1] x2
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/BaseAmazing.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/BaseUltimate.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/Base2099.pak” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31779/USRDIR/Data/BaseNoir.pak” [1]

### Attach capture files for visual issues

<img width="1441" alt="Screenshot 2023-06-15 at 12 28 13" src="https://github.com/RPCS3/rpcs3/assets/120595978/7526dc3c-64c2-4b09-b432-551a353eef36">

### System configuration

Macbook Pro 2021 M1 PRO 16GB

**Comment by AniLeo** [comment]
Missing log file, missing capture file

**Comment by PolStoica** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11756622/RPCS3.log)

**Comment by YuriNator557** [comment]
This should be reported on #11414, it's a macOS exclusive issue

**Comment by Asinin3** [comment]
Closing, OP posted on the meta macOS issue.
