### ISSUE TITLE
Problem launching game

### ISSUE THREAD

**Issue by SUckZz** [RPCS3/rpcs3#1403]
Hello.

I just downloaded rpcs3 and wanted to play a game. When i launch the game then it wont do anything than just throw an error

full log is "E {PPU Thread[0x1] (main_thread)[0x0012ed48]} Exception: Invalid or unimplemented flags (010000): '/dev_bdvd/PS3_GAME/USRDIR/Launcher/Launcher.mself'
(in file C:\rpcs3\rpcs3\Emu\SysCalls\lv2\sys_fs.cpp:100, in function sys_fs_open)
"

Game I'm trying to play is Kingdom Hearts 2.5 HD Remix

-SUckZz

**Comment by tambry** [comment]
@SUckZz
Please read the [FAQ](https://github.com/RPCS3/rpcs3/wiki/FAQ).
Commercial games, that are fully playable are listed [here](http://www.emunewz.net/forum/forumdisplay.php?fid=195).

As you already probably learned from reading the FAQ, most commercial games wont work and only very few are fully playable. Github is more for development-related issues, as explained by the FAQ.
