### ISSUE TITLE
[Regression] RPCS3 fails to launch with Japanese OS locale

### ISSUE THREAD

**Issue by FabulousCupcake** [RPCS3/rpcs3#14031]
### Quick summary

Upon running `rpcs3.exe`:
• nothing happens; it does not spawn any window
• process just dies within several seconds
• it does prints log, but nothing useful in it

### Details

I was able to narrow it down to these changes between `15124` and `15120`: https://github.com/RPCS3/rpcs3/compare/5e6aa45658ef1482679bfe3cfdbd344c0dfdcd42...c85775922e4c6af34ad8c9f002d06e52f20ad2fc

I have no idea about rpcs3 internals though, so I'll leave this section empty.  

### Build with regression

`v0.0.28-15124-c8577592`

### Attach two log files

`0.0.28-15124-c8577592` (broken):
```
RPCS3 v0.0.28-15124-c8577592 Alpha | master
AMD Ryzen 5 5600X 6-Core Processor | 12 Threads | 15.91 GiB RAM | TSC: 3.693GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
Qt version: Compiled against Qt 5.15.2 | Run-time uses Qt 5.15.2
Current Time: 2023-06-16T01:23:06
Thread time: 0.000000s (0.001554Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.004075 SYS: Initialization times before main(): 0.113855Gc
·! 0:00:00.004081 SYS: argc: 1, argv: 'C:\Users\fbcpck\Downloads\rpcs3-v0.0.28-15124-c8577592_win64\rpcs3.exe'
·! 0:00:00.012357 UUID: File does not exist: C:/Users/fbcpck/Downloads/rpcs3-v0.0.28-15124-c8577592_win64/config/uuid (Not found)
·! 0:00:00.012619 UUID: Wrote to file: C:/Users/fbcpck/Downloads/rpcs3-v0.0.28-15124-c8577592_win64/config/uuid
·! 0:00:00.012622 UUID: Installation ID: {dca0ad87-9e08-4df1-93c5-970ef40b3f40}
```

`v0.0.28-15120-5e6aa456` (working):
```
RPCS3 v0.0.28-15120-5e6aa456 Alpha | master
AMD Ryzen 5 5600X 6-Core Processor | 12 Threads | 15.91 GiB RAM | TSC: 3.693GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
Qt version: Compiled against Qt 5.15.2 | Run-time uses Qt 5.15.2
Current Time: 2023-06-16T01:24:58
Thread time: 0.000000s (0.001791Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.003929 SYS: Initialization times before main(): 0.104133Gc
·! 0:00:00.003941 SYS: argc: 1, argv: 'C:\Users\fbcpck\Downloads\Apps\RPCS3\rpcs3.exe'
·! 0:00:00.012139 UUID: File does not exist: C:/Users/fbcpck/Downloads/Apps/RPCS3/config/uuid (Not found)
·! 0:00:00.012383 UUID: Wrote to file: C:/Users/fbcpck/Downloads/Apps/RPCS3/config/uuid
·! 0:00:00.012387 UUID: Installation ID: {46d06664-bd08-4c9f-8710-98f22258c1b9}
·A 0:00:00.037385 {Vulkan Device Enumeration Thread} RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3070' running on driver 528.2.0.0
·! 0:00:00.038494 {Vulkan Device Enumeration Thread} SIG: Thread time: 0.015625s (0.073820Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.038513 CFG: Setting the default renderer to Vulkan. Default GPU: 'NVIDIA GeForce RTX 3070'
·! 0:00:00.038533 SYS: Setting user ID '00000001'
·! 0:00:00.040793 VFS: VFS config missing. Using default settings. Path: C:/Users/fbcpck/Downloads/Apps/RPCS3/config/vfs.yml
·! 0:00:00.040847 SYS: Using VFS config:
$(EmulatorDir): ""
/dev_hdd0/: $(EmulatorDir)dev_hdd0/
/dev_hdd1/: $(EmulatorDir)dev_hdd1/
/dev_flash/: $(EmulatorDir)dev_flash/
/dev_flash2/: $(EmulatorDir)dev_flash2/
/dev_flash3/: $(EmulatorDir)dev_flash3/
/dev_bdvd/: $(EmulatorDir)dev_bdvd/
/games/: $(EmulatorDir)games/
/app_home/: ""
/dev_usb***/:
  /dev_usb000:
    Path: $(EmulatorDir)dev_usb000/
    Serial: ""
    VID: ""
    PID: ""
·! 0:00:00.040866 VFS: Mounted path "/dev_hdd0" to "C:/Users/fbcpck/Downloads/Apps/RPCS3/dev_hdd0/"
·! 0:00:00.040872 VFS: Mounted path "/dev_flash" to "C:/Users/fbcpck/Downloads/Apps/RPCS3//dev_flash/"
·! 0:00:00.040874 VFS: Mounted path "/dev_flash2" to "C:/Users/fbcpck/Downloads/Apps/RPCS3//dev_flash2/"
·! 0:00:00.040875 VFS: Mounted path "/dev_flash3" to "C:/Users/fbcpck/Downloads/Apps/RPCS3//dev_flash3/"
·! 0:00:00.040876 VFS: Mounted path "/app_home" to "//"
·! 0:00:00.040998 SYS: Applying global config: C:/Users/fbcpck/Downloads/Apps/RPCS3//config.yml
·! 0:00:00.047303 SYS: Logged in as user '00000001' with the username 'User'
·! 0:00:00.047437 IPC: IPC config missing. Using default settings. Path: C:/Users/fbcpck/Downloads/Apps/RPCS3/config/ipc.yml
·! 0:00:00.047448 SYS: Using IPC config:
IPC Server enabled: false
IPC Port: 28012
·A 0:00:00.047481 SYS: Missing Firmware
·! 0:00:00.087411 GUI: Current language changed to English (en)
·! 0:00:07.155275 Compat: Finished reading database from file: C:/Users/fbcpck/Downloads/Apps/RPCS3/GuiConfigs/compat_database.dat
·! 0:00:07.278875 NET: Starting download from URL: https://update.rpcs3.net/?api=v2&c=5e6aa456
·! 0:00:07.318069 SYS: New timer resolution: 498 us (old=998 us, min=15625 us, max=500 us)
·! 0:00:07.588280 NET: Download finished
·! 0:00:07.588464 UPDATER: Current: 2023-06-04 21:11:24, latest: 2023-06-15 20:39:30, difference: 948486000 ms
·! 0:00:07.588501 UPDATER: Update found: https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-924692bf1c975479b1dae3b85f46fea95ffb5048/rpcs3-v0.0.28-15208-924692bf_win64.7z
```

### System configuration

**CPU:** 5600x
**GPU:** 3070  
**GPU** Driver: `528.02`, `536.23` (tested with both)  
**OS:** Windows 10 22H2 19045.3086

**Comment by MSuih** [comment]
Can you download https://github.com/13xforever/vkdiag/releases/latest and show what it finds? The log output ends before device enumeration which suggests that it could be vulkan-related issue.

**Comment by FabulousCupcake** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/25855364/c23a765f-3476-489b-bf6a-b8606043cdb0)

**Comment by readywer** [comment]
I have the same issue on my laptop didn't played rpcs3 on it for several months and now it didn't start i tryed to disable win11 security but it didn't helped and i tryed to launch a the newest version on it but it didn't worked either.
Specs:
Win 11 
Ryzen 7 5700U
16gb ram
GTX 1650

**Comment by AniLeo** [comment]
Adding @brian218 looking at the provided range

**Comment by brian218** [comment]
The mentioned commits didn't touch the `rpcs3qt` or main window stuff, and no any LV2 syscall that was touched by the mentioned commits seemed to be involved in the logs you provided.
Comparing the two provided logs, `Vulkan Device Enumeration Thread` seems to be the break point.

**Comment by readywer** [comment]
Finally i fixed it by reinstalling the amd gpu driver. I don't know who it fixed it, but it did. Btw for me eaven the older versions of rpcs3 didn't worked too.(like i tried 0.0.19-13010(oldest version that i had downloaded) and i had the same issue)

**Comment by brian218** [comment]
> Finally i fixed it by reinstalling the amd gpu driver. I don't know how it fixed it, but it did. Btw for me eaven the older versions of rpcs3 didn't worked too.(like i tried 0.0.19-13010(oldest version that i had downloaded) and i had the same issue)

Glad to hear that you clarified the issue.

**Comment by AniLeo** [comment]
vkdiag from OP doesn't show any known broken layers, so I don't know why it doesn't work for them, specially since both builds were tested at the same time and if vulkan layers were broken both builds wouldn't have worked

**Comment by AniLeo** [comment]
According to forum reports, this seems to be related to the windows locale setting, for affected users, which locale are you using?

**Comment by readywer** [comment]
I am using Hungarian.

**Comment by FabulousCupcake** [comment]
@readywer I don't think we have the same issue

@AniLeo I am not sure — default installation was English (United States) but I had to install Japanese locale to run some applications in the past:  
![image](https://github.com/RPCS3/rpcs3/assets/25855364/46918399-a5f7-400f-bcfe-828874806097)

**Comment by FabulousCupcake** [comment]
Changing system locale to English (United States) fixed the issues for both versions.  
Looks like it happens if system locale is non-english (or specifically Japanese?)

**Comment by FabulousCupcake** [comment]
I can confirm the issue is now fixed tested with build `15240`, thank you!
