### ISSUE TITLE
[Feature request] Dark Mode for Linux

### ISSUE THREAD

**Issue by 995qa** [RPCS3/rpcs3#14037]
### Quick summary

Dark mode for Linux Desktops

### Details

Dark mode in RPCS3 is very broken, Some things show as dark whilst some things do not, Text is white for Dark Mode but in a white background.

Tested with Debian 12, KDE Plasma 5

**Comment by Megamouse** [comment]
no. this is because linux and macOs force the dark mode on all your apps for no reason.

**Comment by kokkermanz** [comment]
this is just a conflict between RPCS3 and Qt? ~~and btw, its for a reason they apply dark mode everywhere with dark themes.. its because Qt apps read the Qt theme..~~

**Comment by 995qa** [comment]
Maybe

**Comment by Asinin3** [comment]
Not sure why this was left open, closing
