### ISSUE TITLE
[Feature request] Please turn on the AVX512 option for some AMD laptop Ryzen processor

### ISSUE THREAD

**Issue by QiuWeimengChan** [RPCS3/rpcs3#14047]
### Quick summary

Recently, AMD has released some Zen4 notebook processors which have the same AVX512 features as the desktop platform. Will it be possible for users to experience this feature in the next version of RPCS3?

[AMD Zen4 laptop soc specifications list](https://www.amd.com/en/processors/ryzen-processors-laptop-business)
*The penultimate digit of the SoC name is 4, which is the Zen4 processor

### Details

- Any game that benefits from the AVX512 boost
- AVX512 has been proven to improve the frame rate of some games
- This has been implemented on the AMD Zen4 desktop version

**Comment by MSuih** [comment]
AVX512 should be supported on these platforms as long as LLVM recognizes the architecture correctly. Is it not working right now? Can you share a log file with a game/test boot that shows how LLVM sees these CPUs?

**Comment by QiuWeimengChan** [comment]
> AVX512 should be supported on these platforms as long as LLVM recognizes the architecture correctly. Is it not working right now? Can you share a log file with a game/test boot that shows how LLVM sees these CPUs?

Thanks for the reply, I don't see AVX512 related options in the CPU settings. y-cruncher and CPU-Z both recognize that it has AVX512 functionality and the system is turned on.
`y-cruncher v0.7.10 Build 9513

Detecting Environment...

CPU Vendor:
    AMD         = Yes
    Intel       = No

OS Features:
  * 64-bit      = Yes
  * OS AVX      = Yes
  * OS AVX512   = Yes

Hardware Features:
    MMX         = Yes
  * x64         = Yes
  * ABM         = Yes
    RDRAND      = Yes
    RDSEED      = Yes
    BMI1        = Yes
  * BMI2        = Yes
  * ADX         = Yes
    MPX         = No
    PREFETCHW   = Yes
    PREFETCHWT1 = No
    RDPID       = Yes
    GFNI        = Yes
    VAES        = Yes

SIMD: 128-bit
  * SSE         = Yes
  * SSE2        = Yes
  * SSE3        = Yes
  * SSSE3       = Yes
    SSE4a       = Yes
  * SSE4.1      = Yes
  * SSE4.2      = Yes
    AES-NI      = Yes
    SHA         = Yes

SIMD: 256-bit
  * AVX         = Yes
    XOP         = No
  * FMA3        = Yes
  * FMA4        = No
  * AVX2        = Yes

SIMD: 512-bit
  * AVX512-F         = Yes
    AVX512-CD        = Yes
    AVX512-PF        = No
    AVX512-ER        = No
  * AVX512-VL        = Yes
  * AVX512-BW        = Yes
  * AVX512-DQ        = Yes
  * AVX512-IFMA      = Yes
  * AVX512-VBMI      = Yes

Alright Intel, how many drinks have you had tonight?
    AVX512-VPOPCNTDQ        = Yes
    AVX512-4FMAPS           = No
    AVX512-4VNNIW           = No
    AVX512-VBMI2            = Yes
    AVX512-VPCLMUL          = Yes
    AVX512-VNNI             = Yes
    AVX512-BITALG           = Yes
    AVX512-BF16             = Yes
  * AVX512-GFNI             = Yes
    AVX512-VAES             = Yes
    AVX512-VP2INTERSECT     = No
    AVX512-FP16             = No`

And wait a moment, I am testing a game and will share the log with you

**Comment by Asinin3** [comment]
There is no cpu-setting for avx-512 it just gets enabled by default. If you want to see if avx-512 is recognized you just open RPCS3, and look at the top line in the log next to your CPU. It lists the supported extensions. AVX-512 will be used as long as its listed there.

**Comment by QiuWeimengChan** [comment]
> There is no cpu-setting for avx-512 it just gets enabled by default. If you want to see if avx-512 is recognized you just open RPCS3, and look at the top line in the log next to your CPU. It lists the supported extensions. AVX-512 will be used as long as its listed there.

Thank you so much @Asinin3  and @MSuih , I saw it in the log!
`AMD Ryzen 7 7840H w/Radeon 780M Graphics | 16 Threads | 15.21 GiB RAM | TSC: 3.793GHz | AVX-512+ | FMA3`
`Full Width AVX-512: true`
