### ISSUE TITLE
GranTurismo5 and GranTurismo6 go down in the middle of running.

### ISSUE THREAD

**Issue by fieldwest** [RPCS3/rpcs3#14043]
### Quick summary

GranTurismo5 and GranTurismo6 go down in the middle of running.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11779263/RPCS3.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11779268/RPCS3.log)

**Comment by AniLeo** [comment]
Does not follow any of the wiki settings

**Comment by fieldwest** [comment]
I set it according to WiKi and it worked. Thank you very much.

https://wiki.rpcs3.net/index.php?title=Gran_Turismo_5
