### ISSUE TITLE
mw2 closing at the start

### ISSUE THREAD

**Issue by Jaze999** [RPCS3/rpcs3#14044]
### Quick summary

When i try to open mw2 it closes when you see the starting animation

### Details

When I open mw2 it closes when you see the infinity ward animation. Most of the time it wont pop up with an error message, it just keeps opening and it says "compiling ppu modules" then it closes and tries to do it again then after a few tries it pops up with a fatal error message.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11780010/RPCS3.log)

### System configuration

I have a core i7-12700H 16 gb of ram and a 3060 and the drivers 535.98

**Comment by AniLeo** [comment]
Log doesn't show any game boot, missing log file with boot attempt

**Comment by AniLeo** [comment]
Closing due to the lack of information
