### ISSUE TITLE
Version 0.0.28 fails to boot. 

### ISSUE THREAD

**Issue by fieldwest** [RPCS3/rpcs3#14042]
### Quick summary

Hi

Version 0.0.28 fails to boot. 
It is a combination of intel i7 2600K and GTX970. The OS is Windows 10.

v0.0.28-15212 and v0.0.28-15143 both use "·! 0:00:00.102180 SYS: Setting user ID '00000001'" and then shuts down.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11779236/RPCS3.log)

**Comment by AniLeo** [comment]
Does not follow regression template at all
