### ISSUE TITLE
UI Sort by 'Space on Disk' Doesn't Persist

### ISSUE THREAD

**Issue by JWatersMeet** [RPCS3/rpcs3#14059]
### Quick summary

When sorting by 'Space on Disk' on the Game List in Grid Mode, the sort order isn't preserved across application restarts. When the application is restarted, the column header indicator notes that the games are sorted by 'Space on Disk' but are in fact sorted in what appears to be a Name order, alphabetically.

### Details

1. Sort Titles by 'Space on Disk' Column
2. Notice Titles are correctly sorted
3. Restart RPCS3
4. Note the sorting order isn't preserved.

### Attach a log file

Attached.

**Comment by JWatersMeet** [comment]
Just seen this was merged - no luck unfortunately. See the video below.

https://github.com/RPCS3/rpcs3/assets/136824455/d0fac551-191f-4918-a83d-c3779d636425

**Comment by Megamouse** [comment]
The size on disk is being computed when the element is first shown due to performance reasons.
It doesn't really make sense to sort the list by that value, since whenever you scroll and new values are computed you will have to press the sort button again anyway.

**Comment by JWatersMeet** [comment]
Oh OK sure, that makes sense. I'll close the ticket out.
