### ISSUE TITLE
[NPUB31633] MGS4 GUNS OF THE PATRIOTS - Trophy error makes game unable to start. RPCS3 0.0.28-15216-441fbd63 Alpha

### ISSUE THREAD

**Issue by fange26** [RPCS3/rpcs3#14061]
### Quick summary

After the This game saves data automatically at certain points screen. User is brought to an error screen that says Error during trophy registration! The game will now be terminated. 

This did not happen until I updated to the latest version of RPCS3. I tried downgrading and setting up new installation and still the issue replicates itself. 

### Attach a log file

`S sys_overlay: Loaded overlay: “/dev_hdd0/game/NPUB31633/USRDIR/mgs/self/init.self” (id=0x25018b00)
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31633/USRDIR/mgs/mgs4.mself” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31633/USRDIR/mgs/o/online/mgof.sav” [1]
E SYS: 'cellSaveDataAutoLoad2' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
U cellAudio TODO: cellAudioMiscSetAccessoryVolume(devNum=65535, volume=0.500000)
E SYS: 'cellSaveDataListAutoLoad' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31633/USRDIR/mgs/bgm.dat” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31633/USRDIR/mgs/speech.dat” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31633/USRDIR/mgs/sdpack.dat” [1]
E SYS: 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E ppu_loader: Unknown phdr type (0x00000007)
S PPU: LLVM: Loaded module v6-kusa-X1GqLPX0n9s2Rj086vvZn2-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-6XaMWW8g5Z54WSPa17R3ZY-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-N1Xm4Z1ejgSp72dHERuu21-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-bsKxSVcy2cb8x2EXS3nwkq-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-sVLsYXgKAA1YWk5ESN3io5-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-00yRNe1hYdgVVSzk6cMczf-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-0Ezf3cex4166bFbf4n0Thu-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Kc9cjWFWvfG6WQTdWxg1YY-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-rNnT5Kqhu9gPkroG1MXTeZ-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-RoCrdmYzS2ZdKGRX21yV5j-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-TysSe7VHvGYefWiy6fjgrx-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-J1XUZgcVW4VJi9AtTbydMJ-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-1U5Gubpr5TXCSfmXpiozcq-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-2YaRNu1gh75hgSxAi6cRxo-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-taQ0TQQKtPapNWzCSsLAu8-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-0g9AgcdwGNAryGdaStU1ve-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-UxjujA9XGZYTeHXJsPjn3h-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-kAoGVihZ6kNSTEStwkroii-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-hgJQqkQKpo7fPzJLsJThXf-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Jf6FnrFz93bSpSEyGaUPiJ-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-mQmkN9a5Sd1jJAgU5kcp0p-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-8yZ4MkTgoWRLfwhT9kdE6V-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-7eiu5GeqkvtkjsNnsPU0sW-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-r2quge5a2zhNpyGmp9Sq1J-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-SdqqPrmEL4sj3Ssjh6dScn-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Y22HVLMod4LirGSKSzGCRA-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-eQwcYyXVNwqrrJC708GxCK-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-1eSQndeGWggQpsjPTFptZV-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Rc34bvwex9z3cStHtJFHRi-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Kgcwns9WAgg9qSJt9CaSSS-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-aXiCr0J73jXm86vLnPjr2P-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-0ciq7JsAUmm5FvFp9Z8evx-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Yfats843j3C5pJPNQeKHLk-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-gbjyTwSYo9yYYVeJhU7vGt-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-QEKN4kK5nJVcA9JskQy6XW-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-YEPGdytywbU6Atv3dZ94UC-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Muvsuwt7cHV7W4RyNUHE0q-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-tThc1Q0hiPGp6mbZpRHEsk-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-nM91oPywXaA30UxEcJeP9Y-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-8L3hLQKFAxtUVZt4bhPrR5-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-tftbRbpPqjchQXo7iPybxH-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-NjQjaouSN3GbQRhjwdJVyP-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-KC9fok8HzYY4JtujxCsSri-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-3EuT4f4ZqfEWbPmbPiWhLx-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-PcneGHXd4YCgv3vjM7Wy00-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-hKvnxhydGxSqig81w13Wes-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Ge4gCsusPnFhdrRJexp3md-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-TU2rS8hpMeTS3G3oWGcPT5-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Enr5F6mYuL7UtPsTYHPZzX-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Hch20X4KPad1HuZi6rvRnC-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-24FXHcA6aHGd2XEMvpwXWn-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-priSzMsUnkcr4maN2Zs7H9-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-0EHXELUvmoEANNfFXR7c7n-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-6PsVZfk44HYJ21b2tiEmYu-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-dTV8i2b7kq0MjyzcYeMskU-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-jcowEWoonudNHs77rTRuY6-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-YYNWKTc7arbX1ee4mSQqKK-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-rPFLGF7g4W4oq7TA8VKxHp-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-21YLWGJ0Ks2cK6j3PGzNMv-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-mXJM1r4KEe9Mceh7vjkGqt-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-daY0hbM2JxAoCP1jeQX0G4-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-G9ArhiUxSiPeZ3YiGKaawb-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-7k85A2vRdajKnUkdC2XQ1d-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-RKdF9awspWtj2YgnUX6w3R-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-kZq4gQtzAZx32cW7W7i93e-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-r9YmpStqn3dHEcJoWiQzev-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-ds66FrTu61SPH9j7cpHenC-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-WsScs3cn0wKqc7m8q127F7-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-SUWPM7YtKhshn4WcxJ0jk3-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Tycn580Z56cP5qfms5Cmne-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-1futQ1V0EtkVw2MPTUiXMz-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-cR784puJrvhEyg8sjbCChf-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-WTwmUoK2Z7Qm59u1s3oM02-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-b4g7FrkpKyj7eTeuqwikv9-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-RSnvjuexE8F18xycyChMwF-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-68bu3tYwTzLf8tJ4HnPrtn-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-fi6nNwyUyLU7jryRdKkta1-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-6JxiPiw1wawky0oH7soNky-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-CwMvcojN7j9cjFgwQjawYR-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-V5TGgKvGzggkEvA3tPzMSV-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-k6Crj5ZPLv5VNcUjhZx5E4-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-rhHf86dHuJjS22VC2mNxXu-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-HEghLGRX63EdCuKESht0cC-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-33gnxN1H1tmtH9SJrSxLN1-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-0qGtu2NxSZhQQxnX59UFot-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-q0zcnFR9yVZnJaWoc7s5cc-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-FxRW4LhpVfaEC4FFNnUSrb-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-jT4ww6vuk6br9n9wMx0RhC-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-famRRSWK4g7Qre3gaZcSAE-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-kZKn4f35ms7h0TYfJsyiNK-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-erVtcWhTfCdJbvYvJXrd5N-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-NKCWdHcocZ75fX35GNCRM2-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-KMQvKrUK3e0otvhcX2GJ9C-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-jFU0PrAGA15LWjVFNP2MXi-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-55Kqw1zeE3qAGsdA4YQN52-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-YLRGASysycwbWiwXpFn5hh-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-ri71MRfF5SGAh9xW3nQymX-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-pMxXyjiMS7yqPRPvWAjCUC-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-XTqbMmyqCuWfJCEtCMWK7r-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-4fYAuub99PFMyFFrNKhwTA-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-QKgLNgtQhVeduzjHc8tU8g-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-U6c1jQh2H44Qjuc19d1043-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-4xCaiqhsPh8U9yzPAC3wUs-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-aCk8CzpmC0YFJQqPbo9eW8-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-0ZymULLHwRCHjxzde8V38k-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-H9nLGXzCELHCFuavnC2UNz-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-e8YpZzhL526fxnuqpZ8w1g-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-YPSZXLSWvaQe8e6LuTqs31-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-Wh8X8eAGkJPZHMdbCk5a3Z-00001G-znver2.obj
S PPU: LLVM: Loaded module v6-kusa-gFvRoetV90Xe0S5icL0vgY-00001G-znver2.obj
S sys_overlay: Loaded overlay: “/dev_hdd0/game/NPUB31633/USRDIR/mgs/self/title.self” (id=0x2501a200)
E SYS: 'cellSaveDataListAutoLoad' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
E sceNpTrophy: sceNpTrophyGetRequiredDiskSpace(): Failed to load trophy header! (trp_name=NPWR03485_00)
E sceNpTrophy: sceNpTrophyRegisterContext(): Failed to load trophy config header`

**Comment by AniLeo** [comment]
Missing log file

**Comment by fange26** [comment]
Sorry. I figured out the issue. Using the upgrade wizard deleted all of my trophies. Deleting the empty trophy file fixed the issue.

**Comment by fange26** [comment]
Sorry. I figured out the issue. Using the upgrade wizard deleted all of my trophies. Deleting the empty trophy file fixed the issue.
