### ISSUE TITLE
UFC 2009 Undisputed ring girl crash.

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#14068]
### Quick summary

The game seems to crash when the ring girl starts round 1 this can be skipped. If you don't do so it will crash with an error.

### Details

Screenshot:
![Screenshot 2023-06-22 15-40-21 (2)](https://github.com/RPCS3/rpcs3/assets/71127352/5b68c301-1cc9-44bd-a3a8-412ddbf380ca)

Error: E RSX: FIFO: RET found without corresponding CALL (last cmd = 0x20000) x21
F {RSX [0x000098c]} SIG: Thread terminated due to fatal error: Dead FIFO commands queue state has been detected!
Try increasing "Driver Wake-Up Delay" setting or setting "RSX FIFO Accuracy" to "Ordered & Atomic", both in Advanced settings. Called from 
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\RSXFIFO.cpp:700[:6], in function run_FIFO)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\RSXThread.cpp:3066[:24], in function recover_fifo)

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/11835198/RPCS3.zip)

### System configuration

RPCS3 v0.0.28-15225-715e3856 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

### Other details

Changing the Rsx accuracy makes no diffrences

**Comment by Asinin3** [comment]
You didn't increase wake-up driver delay on advanced tab like the error you posted literally told you to. Try setting it to 100 or 200. Crashes like this aren't veryuseful as github issues. Closing.

**Comment by Triticum0** [comment]
Silly me. All ready tested all wake-up when I tested it back in November and forgot to mention it in the issue https://forums.rpcs3.net/showthread.php?tid=205074&highlight=ufc+2009 my mistake sorry about that. I didn't fix the issue.
