### ISSUE TITLE
Resistance: Fall Of Man Texture cache Crash

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#14075]
### Quick summary

While testing this game it crash with an assertion

### Details

`SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\texture_cache.h:3116[:8], in function upload_scaled_image)
·W 0:06:35.417689 {RSX [0x1e07a88]} SYS: Emulation has been frozen! You can either use debugger tools to inspect current emulation state or terminate it.
·! 0:06:35.417950 {rsx::thread} SIG: Thread time: 262.781250s (887.337320Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[79.313s, spur:0]
·W 0:06:35.418209 SYS: CPU Thread 'rsx::thread' terminated abnormally!`

seems to also have some graphical issues with shadows and mipmap of the sky box which wasn't there previously.

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/11841066/RPCS3.zip)

### System configuration

RPCS3 v0.0.28-15225-715e3856 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by Asinin3** [comment]
>graphical issues with shadows and mipmap of the sky box which wasn't there previously.

If its a regression, go to https://rpcs3.net/compatibility?b and find where it last worked (go back months/weeks at a time, not build by build). Then when you find the working build go in-between and find the **exact**build that caused the issue and report it so we can find the issue and fix it. Remember you don't need to create a whole new RPCS3 folder each time, just replace the executable file, you can even have multiple RPCS3 versions in the same folder if you rename the executable (but can only run one at a time).

**Comment by Triticum0** [comment]
Can't seem to reproduce the issue seem to be be fixed
