### ISSUE TITLE
dress vol.1 save data picture garbage

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#14074]
### Quick summary

When creating clothes the icon save data picture seems to be garbage data

### Details

![Screenshot 2023-06-22 23-20-31 (2)](https://github.com/RPCS3/rpcs3/assets/71127352/c2206e1e-d29e-4a87-92cb-0b05f653561e)

Save:
[a2ftp000001.zip](https://github.com/RPCS3/rpcs3/files/11840835/a2ftp000001.zip)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11840855/RPCS3.log.gz)

### System configuration

RPCS3 v0.0.28-15225-715e3856 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by RipleyTom** [comment]
If it uses framebuffer to create the save data icon, enabling `Write Color Buffers` might fix this.

**Comment by Triticum0** [comment]
Using `Write Color Buffers` fixes the issue.
