### ISSUE TITLE
Kingdoms of Amalur: Reckoning lod doesn't work properly on first boot

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#14089]
### Quick summary

When retesting this game I came across an issue where the high-quality lod shader doesn't actually ever get rendered when getting close to the object on the first boot when shaders are compiled.

### Details

Rpcs3
![NPEB90385_screenshot_2023_06_24_12_52_04](https://github.com/RPCS3/rpcs3/assets/71127352/4411022c-8248-4e37-bb45-58a15e0b922a)

Ps3: https://youtu.be/vDtvFEj8IBM?t=2767

Also, seem the Specular highlight on the floor seems to be missing as well.

Rpcs3
![NPEB90385_screenshot_2023_06_24_13_04_00](https://github.com/RPCS3/rpcs3/assets/71127352/1f8216cd-516d-4554-9e2f-ad341e326be3)

Ps3:https://youtu.be/vDtvFEj8IBM?t=3479

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11856875/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1mWVRT4vjJdsSt7n4HA1M9Bjc6Yp2R3AL/view?usp=sharing

https://drive.google.com/file/d/1oahmX7Gubiu8onZgUjtpPer1h1Gz7n1g/view?usp=sharing

### System configuration

RPCS3 v0.0.28-15225-715e3856 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by kd-11** [comment]
Retest with the legacy compiler. The asynchronous compiler is known to have some issues and that is expected behavior.

**Comment by Triticum0** [comment]
@kd-11 Using legacy shaders on the first boot didn't fix the issue.

**Comment by Triticum0** [comment]
Using legacy compiler fixes the issue
