### ISSUE TITLE
Could not boot game

### ISSUE THREAD

**Issue by lightfirst** [RPCS3/rpcs3#14082]
### Quick summary

Some of my dick games could not boot, it can boot by using older rpcs3 version. 
0.0.28-15120 is the last working build I can get from rpcs3.net.
The first broken commit may be 6a570ae57e2bf64074a1099ea33bda7385aadca1

### Details

If I change folder name to a simple one, It can boot again.
For example:
disc game with folder name 偶像大师：灰姑娘女孩 为你写真！ VOL.7 could not boot
change to 偶像大师：灰姑娘女孩 为你写真！VOL.7 can boot (delete one space)
or change to 偶像大师：灰姑娘女孩 为你写真 ！VOL.7

### Attach a log file

rps3 crash, not get any log

**Comment by AniLeo** [comment]
Needs retest with latest build, potential duplicate of #14031

**Comment by lightfirst** [comment]
OK, now all disc game can boot

**Comment by Skoczek777** [comment]
I'd advise you to correct dick to disc
