### ISSUE TITLE
[Regression] GOW3 - rendering error

### ISSUE THREAD

**Issue by JohnLoveJoy** [RPCS3/rpcs3#14083]
### Quick summary

After the last modifications in the vk code, GOW3(Demo) started to show rendering errors, overlapping objects and smoke as if there was incorrect transparency.

### Details

When standing still without moving the rendering issues go up for an instant.
![GOW3_PS](https://github.com/RPCS3/rpcs3/assets/31490343/6c132214-93bd-46ed-ad28-c1aa4999ab77)
![GOW3_BUG](https://github.com/RPCS3/rpcs3/assets/31490343/d8eb7fb1-f224-4d9b-9c8d-6398951b6a92)

I used the recommended settings from the compatibility guide. 

### Build with regression

v.0.0.28-15227-Alpha

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11853806/RPCS3.log.gz)

### System configuration

Specs 5500U @ Vega 7 + 12GB ram

**Comment by AniLeo** [comment]
Incomplete regression report 

The build you mention just includes compilation fixes, missing build that regressed it and last good build

**Comment by kd-11** [comment]
It seems vega doesn't support KHR_synchronization2 so we need to restore the workaround path because default vulkan events were really broken on AMD.

**Comment by JohnLoveJoy** [comment]
> I don't know how efficient GPU-Z is at detecting GPU extensions, but here mentions the one you mentioned:

![PSGPUZ0](https://github.com/RPCS3/rpcs3/assets/31490343/dca1bc22-99db-4d4b-a24d-eb6d477ca951)

**Comment by kd-11** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/14101
If its still broken, attach log.
