### ISSUE TITLE
[Feature request] Parental controls

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#14095]
### Quick summary

Person who presses Home button controls the home menu.

### Details

Currently RPCS3 functions as any connected PADs controls the home menu simultaneously. This can create complications as a parent playing a game with their child in splitscreen and just wants to take a quick screenshot, Disable/enable an overlay or perform quick fixes.
While this is true, there are probably other scenarios where an option to allow an Admin mode of PAD 1 always has control over home menu might also be needed maybe through Parsec or something.
So I have sorta 2 requests.
1: Only person who presses Home uses the Home menu.
2: If admin mode = on. Only person who presses home + admin uses the home menu simultaneously.

How I currently have things setup is I play Minecraft with my child removing their ability to press Start, select, and the home buttons.
I have my home button enabled.
When I press home my kid can control my home menu because the home menu isn't exclusive to the one who opened the menu.

**Comment by Megamouse** [comment]
There's no way in knowing whether the second player opened some ingame dialog for example.
I can add a mode that only allows player 1 to enter stuff, which probably fixes your problem.

Idk if it's worth adding the "the home menu can only be controller by the player that opened it"
