### ISSUE TITLE
[Feature request] Add Linux arm64 to CI 

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#14091]
Same as #12599 for macOS arm64 on CI

Currently we're building x64 for Linux but not arm64

We should have CI build the arm64 version just to ensure we don't break compilation on new commits, even though the arm64 builds are still unusable

**Comment by kd-11** [comment]
arm64 linux is not in too rough shape from my previous testing. It should just work at least on devices with 4k page support. On 16k cpus (M1/M2) it runs fine in some games but hangs in others.

**Comment by shinra-electric** [comment]
Does Linux also require the prebuilt ffmpeg from Vita3K's [ffmpeg-core](https://github.com/Vita3K/ffmpeg-core)?

I made a PR over there adding the macOS Arm builds, so I'll be able to add Linux Arm builds fairly easily...

**Comment by kd-11** [comment]
I just use system ffmpeg when doing things locally. For CI it probably could use vita3k's ffmpeg.

**Comment by Megamouse** [comment]
We already have macos arm64 libs on the ffmpeg PR.
So adding this would be trivial.

**Comment by RoiArthurB** [comment]
Hi guys, any progress on that ? :)

**Comment by AniLeo** [comment]
This is just to have CI to ensure it compiles, it's not to distribute any working builds.

**Comment by nsklaus** [comment]
@AniLeo 
thanks for pointing the difference. 
well, any step toward having linux arm64 builds in the end is good to take. i understand now this feature request is just a preliminary step. for what it's worth, my attempt at compiling rpcs3 on linux arm64 failed at building `Cell/PPUInterpreter.cpp`. (i edited  CMakeLists.txt to enable building llvm as submodule). 

```
[ 71%] Building CXX object 3rdparty/llvm/llvm_build/lib/Target/X86/Disassembler/CMakeFiles/LLVMX86Disassembler.dir/X86Disassembler.cpp.o
[ 71%] Linking CXX static library ../../../libLLVMX86Disassembler.a
[ 71%] Built target LLVMX86Disassembler
[ 71%] Linking C static library libwolfssl.a
[ 72%] Built target wolfssl
[ 72%] Linking C static library libminiupnpc.a
[ 74%] Built target libminiupnpc-static
[ 74%] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/Cell/PPUInterpreter.cpp.o
In file included from /home/klaus/Sources/rpcs3/rpcs3/util/simd.hpp:21,
                 from /home/klaus/Sources/rpcs3/rpcs3/Emu/Cell/PPUInterpreter.cpp:19:
/usr/lib/gcc/aarch64-redhat-linux/13/include/arm_neon.h: In function ‘v128 gv_rmuladds_hds16(const v128&, const v128&, const v128&)’:
/usr/lib/gcc/aarch64-redhat-linux/13/include/arm_neon.h:7261:1: error: inlining failed in call to ‘always_inline’ ‘int16x8_t vqrdmlahq_s16(int16x8_t, int16x8_t, int16x8_t)’: target specific option mismatch
 7261 | vqrdmlahq_s16 (int16x8_t __a, int16x8_t __b, int16x8_t __c)
      | ^~~~~~~~~~~~~
/home/klaus/Sources/rpcs3/rpcs3/util/simd.hpp:1876:29: note: called from here
 1876 |         return vqrdmlahq_s16(c, a, b);
      |                ~~~~~~~~~~~~~^~~~~~~~~
/usr/lib/gcc/aarch64-redhat-linux/13/include/arm_neon.h:7261:1: error: inlining failed in call to ‘always_inline’ ‘int16x8_t vqrdmlahq_s16(int16x8_t, int16x8_t, int16x8_t)’: target specific option mismatch
 7261 | vqrdmlahq_s16 (int16x8_t __a, int16x8_t __b, int16x8_t __c)
      | ^~~~~~~~~~~~~
/home/klaus/Sources/rpcs3/rpcs3/util/simd.hpp:1876:29: note: called from here
 1876 |         return vqrdmlahq_s16(c, a, b);
      |                ~~~~~~~~~~~~~^~~~~~~~~
/usr/lib/gcc/aarch64-redhat-linux/13/include/arm_neon.h:7261:1: error: inlining failed in call to ‘always_inline’ ‘int16x8_t vqrdmlahq_s16(int16x8_t, int16x8_t, int16x8_t)’: target specific option mismatch
 7261 | vqrdmlahq_s16 (int16x8_t __a, int16x8_t __b, int16x8_t __c)
      | ^~~~~~~~~~~~~
/home/klaus/Sources/rpcs3/rpcs3/util/simd.hpp:1876:29: note: called from here
 1876 |         return vqrdmlahq_s16(c, a, b);
      |                ~~~~~~~~~~~~~^~~~~~~~~
make[2]: *** [rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/build.make:1126: rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/Cell/PPUInterpreter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:22377: rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
klaus@kanzume:~/Sources/rpcs3_build$ 

```

**Comment by kd-11** [comment]
Don't use gcc for arm64. I've been using clang to build rpcs3 on arm linux for a long time now, no major issues.
As for the "inlining failed .. options mismatch" error, you must call cmake with -DUSE_NATIVE_INSTRUCTIONS=OFF. Cmake will fall back to armv8.1a which works fine. Arm64 compilers are still a little finicky so using native instructions (-march=native) breaks things.

**Comment by lacamar** [comment]
I built on aarch64 Fedora (M1 Asahi) today using this process:

```
sudo dnf install alsa-lib-devel cmake glew glew-devel libatomic libevdev-devel libudev-devel openal-devel qt6-qtbase-devel qt6-qtbase-private-devel vulkan-devel qt6-qtmultimedia-devel qt6-qtsvg-devel vulkan-validation-layers-devel vulkan-tools mesa-vulkan-drivers 

mkdir rpcs3-files
cd rpcs3-files
git clone https://github.com/RPCS3/rpcs3.git
cd rpcs3
git submodule update --init
cd ..
mkdir --parents rpcs3_build
cd rpcs3_build

BAD_FLAG="-Wp,-D_GLIBCXX_ASSERTIONS"
CXXFLAGS="${CXXFLAGS//$BAD_FLAG/}"

CC=clang CXX=clang++ cmake -S ../rpcs3 -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_SKIP_RPATH=ON \
    -DUSE_NATIVE_INSTRUCTIONS=OFF \
    -DUSE_SYSTEM_FFMPEG=ON \
    -DUSE_SYSTEM_LIBPNG=ON \
    -DUSE_SYSTEM_ZLIB=ON \
    -DUSE_SYSTEM_CURL=ON \
    -DUSE_SYSTEM_FLATBUFFERS=OFF \
    -DUSE_SYSTEM_PUGIXML=OFF \
    -DBUILD_LLVM=ON \
    -DUSE_SYSTEM_WOLFSSL=OFF
make -C build -j8

sudo make -C build install
```

**Comment by nsklaus** [comment]
thank you both @kd-11 and @lacamar 
for explanation and build instructions.
i was able to build and run rpcs3, but game loading kind of hang at building spu cache, toward the end. it doesn't crash or anything but just seem to stay idle on that task, unable to finish it. i don't see any particular error message beside a lot of those:
```
S SPU: SPU Runtime: Built the interpreter.
U SPU TODO: [__spu-0x1bd48-FYkeV228coXRn9s7qW5deq3XVjfq:0x1be3c] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x1bd48-FYkeV228coXRn9s7qW5deq3XVjfq:0x1bff8] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x1bb98-d5HgfdnsEP420F8s1UhJckjYpQu9:0x1bc4c] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x1b580-95Cu2651z5MFcA0C6wzEbQcfRpPt:0x1ba3c] Unmatched spu_re(b) found in FMA
[...]
S SPU: SPU Runtime: Built 2150 functions.
```
is this normal in the current state of rpcs3 or am i missing something ?
also, if in the config UI i choose opengl, rpcs3 say it cannot bind opengl context like so:
```
 S GUI: Boot successful.
F {RSX [0x0000000]} SIG: Thread terminated due to fatal error: Could not bind OpenGL context
(in file /home/klaus/Sources/rpcs3-files/rpcs3/rpcs3/rpcs3qt/gl_gs_frame.cpp:89[:4], in function set_current) (errno=110=Connection timed out)
```
but if i set vulkan instead, graphic device gets set to llvm pipe and i get to see splash screen and build ppu and spu cache and such.. just it hangs toward the end

**Comment by lacamar** [comment]
If you set the PPU decoder to Interpreter (static) and SPU Decoder to Interpreter (Dynamic), you should be able to boot certain games into their start menu with Vulkan and llvmpipe.

**Comment by kd-11** [comment]
Llvm doesn't work on arm64 yet. I'm working on this slowly behind the scenes. No ETA though.

**Comment by FantasyGmm** [comment]
> Llvm doesn't work on arm64 yet. I'm working on this slowly behind the scenes. No ETA though.

Can LLVM not be used on both ppu and spu? I have compiled rpcs3 on 8gen2 Linux, and I can boot it to enter the system for decoding, but I cannot enter the game. The game either crashes or gets stuck in the SPU cache during startup

**Comment by retropele** [comment]
I'm a complete amateur, but I can't for the life of me compile for aarch64 or find a general aarch64 release? Is this possible?

**Comment by G4VSVSVSSV1** [comment]
are you going to make rpcs3 for arm64? because if you do i have an arm device if you want any testers

**Comment by AniLeo** [comment]
Locally I only have to pass `-DUSE_SYSTEM_LLVM=ON` and `-DUSE_SYSTEM_FFMPEG=ON` to be able to compile rpcs3. However, video decoding does not work with system ffmpeg 7, requiring LLE libvdec in general to be used.

RPCS3 will not compile with the submodule ffmpeg due to missing arm64 paths.

**Comment by lacamar** [comment]
I can't get it to compile anymore on aarch64 Linux with the flags I was using before or trying to use those flags you just mentioned. What do I need to run exactly to get it to compile now?

**Comment by pstef** [comment]
What I do is:
`cmake -Wno-dev ../rpcs3-src -DCMAKE_BUILD_TYPE=Release -DBUILD_LLVM=OFF -DLLVM_DIR=~/builder/llvm_build -DUSE_NATIVE_INSTRUCTIONS=OFF -DLLVM_TARGETS_TO_BUILD=AArch64 -DUSE_SYSTEM_CURL=ON -DUSE_SYSTEM_FFMPEG=ON`

**Comment by lacamar** [comment]
This gets me to the very end of the compilation but it fails with this glew error. I have glew-devel installed so I'm not sure what's going wrong.

```
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Input/skateboard_pad_handler.cpp.o
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Input/xinput_pad_handler.cpp.o
[100%] Linking CXX executable ../bin/rpcs3
/usr/bin/ld: Emu/librpcs3_emu.a(OpenGL.cpp.o): in function `gl::init()':
OpenGL.cpp:(.text+0x1c): undefined reference to `glxewInit'
/usr/bin/ld: Emu/librpcs3_emu.a(OpenGL.cpp.o): in function `gl::set_swapinterval(int)':
OpenGL.cpp:(.text+0x2c): undefined reference to `__glewXSwapIntervalEXT'
/usr/bin/ld: OpenGL.cpp:(.text+0x38): undefined reference to `__glewXSwapIntervalEXT'
/usr/bin/ld: OpenGL.cpp:(.text+0x94): undefined reference to `__glewXGetCurrentDisplay'
/usr/bin/ld: OpenGL.cpp:(.text+0x98): undefined reference to `__glewXSwapIntervalEXT'
/usr/bin/ld: OpenGL.cpp:(.text+0x9c): undefined reference to `__glewXGetCurrentDisplay'
collect2: error: ld returned 1 exit status
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/build.make:577: bin/rpcs3] Error 1
make[1]: *** [CMakeFiles/Makefile2:2801: rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/home/snow/software/builds/rpcs3-files/rpcs3_build/build'
```

**Comment by pdapanda** [comment]
I stuck at 86%. 
`[ 37%] Built target libminiupnpc-static
[ 85%] Built target rpcs3_emu
[ 85%] Built target rpcs3_ui_autogen_timestamp_deps
[ 85%] Built target rpcs3_ui_autogen
[ 86%] Built target hidapi_hidraw
[ 86%] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/rpcs3_ui_autogen/mocs_compilation.cpp.o
In file included from /media/pda/545e1341-df1f-4aaa-8c7b-b61fd06d0301/rpcs3-files/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/../../../../../rpcs3/rpcs3/rpcs3qt/tooltips.h:3,
                 from /media/pda/545e1341-df1f-4aaa-8c7b-b61fd06d0301/rpcs3-files/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/moc_tooltips.cpp:10,
                 from /media/pda/545e1341-df1f-4aaa-8c7b-b61fd06d0301/rpcs3-files/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/mocs_compilation.cpp:77:
/media/pda/545e1341-df1f-4aaa-8c7b-b61fd06d0301/rpcs3-files/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/../../../../../rpcs3/rpcs3/rpcs3qt/qt_utils.h:151:35: error: ‘ColorScheme’ in namespace ‘Qt’ does not name a type
  151 |                 static inline Qt::ColorScheme color_scheme()
      |                                   ^~~~~~~~~~~
/media/pda/545e1341-df1f-4aaa-8c7b-b61fd06d0301/rpcs3-files/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/../../../../../rpcs3/rpcs3/rpcs3qt/qt_utils.h: In function ‘bool gui::utils::dark_mode_active()’:
/media/pda/545e1341-df1f-4aaa-8c7b-b61fd06d0301/rpcs3-files/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/../../../../../rpcs3/rpcs3/rpcs3qt/qt_utils.h:158:32: error: ‘color_scheme’ was not declared in this scope
  158 |                         return color_scheme() == Qt::ColorScheme::Dark;
      |                                ^~~~~~~~~~~~
/media/pda/545e1341-df1f-4aaa-8c7b-b61fd06d0301/rpcs3-files/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/../../../../../rpcs3/rpcs3/rpcs3qt/qt_utils.h:158:54: error: ‘Qt::ColorScheme’ has not been declared
  158 |                         return color_scheme() == Qt::ColorScheme::Dark;
      |                                                      ^~~~~~~~~~~
make[2]: *** [rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/build.make:107：rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/rpcs3_ui_autogen/mocs_compilation.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:3002：rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/all] 错误 2
make: *** [Makefile:156：all] 错误 2
`

**Comment by AniLeo** [comment]
Without a full build log can't guess, but probably outdated dependencies.

**Comment by pdapanda** [comment]
> Without a full build log can't guess, but probably outdated dependencies.

I switched qtchooser to qt 6.7.2, but met the same error. Is the dependency have to be the exactly the qt 6.6.3？

**Comment by lacamar** [comment]
> This gets me to the very end of the compilation but it fails with this glew error. I have glew-devel installed so I'm not sure what's going wrong.
> 
> ```
> [100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Input/skateboard_pad_handler.cpp.o
> [100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Input/xinput_pad_handler.cpp.o
> [100%] Linking CXX executable ../bin/rpcs3
> /usr/bin/ld: Emu/librpcs3_emu.a(OpenGL.cpp.o): in function `gl::init()':
> OpenGL.cpp:(.text+0x1c): undefined reference to `glxewInit'
> /usr/bin/ld: Emu/librpcs3_emu.a(OpenGL.cpp.o): in function `gl::set_swapinterval(int)':
> OpenGL.cpp:(.text+0x2c): undefined reference to `__glewXSwapIntervalEXT'
> /usr/bin/ld: OpenGL.cpp:(.text+0x38): undefined reference to `__glewXSwapIntervalEXT'
> /usr/bin/ld: OpenGL.cpp:(.text+0x94): undefined reference to `__glewXGetCurrentDisplay'
> /usr/bin/ld: OpenGL.cpp:(.text+0x98): undefined reference to `__glewXSwapIntervalEXT'
> /usr/bin/ld: OpenGL.cpp:(.text+0x9c): undefined reference to `__glewXGetCurrentDisplay'
> collect2: error: ld returned 1 exit status
> make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/build.make:577: bin/rpcs3] Error 1
> make[1]: *** [CMakeFiles/Makefile2:2801: rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
> make: *** [Makefile:156: all] Error 2
> make: Leaving directory '/home/snow/software/builds/rpcs3-files/rpcs3_build/build'
> ```

I found out the source of the GLEW error. I had a local build of glew installed that was built for wayland. Once I removed it the RPCS3 build succeeded.

**Comment by kd-11** [comment]
Done.
