### ISSUE TITLE
Serial Dupe issue

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#14097]
When going through the missing ps3 demo catalogue, I ran into an issue: two games with different Title IDs had the same serial number on the rpcs3 interface. The actual decrypted package file has the correct serial number, but rpcs3 recognises them as having the same serial even though the size and name* are not the same.

Titles affected
Formula One Championship Edition* NPEA90003
Formula One™ Championship Edition* NPEA90014
MotorStorm NPEA80017
MotorStorm NPEA90006

The pkg is fine using the psn pkg validator so not sure why it does that. I leave where I got Title IDs below. Once this issue is sorted I will add the missing game to the compatibility report  

[www.gametdb.com](http://www.gametdb.com/) and https://www.serialstation.com/
https://www.serialstation.com/titles/NPEA/90003
https://www.serialstation.com/titles/NPEA/90014
https://www.serialstation.com/titles/NPEA/90006

Note: MotorStorm NPEA80017 Does'nt seem to exist on either website so it is missing on both websites or pkg never existed in the first place.

Update: A USA version of MotorStorm NPEU80017 exists

### Log
[Formula One™ Championship Edition NPEA90014](https://github.com/RPCS3/rpcs3/files/11875062/RPCS3.log.gz)
[MotorStorm NPEA90006](https://github.com/RPCS3/rpcs3/files/11875086/RPCS3.log.gz)

**Comment by Megamouse** [comment]
missing log file

**Comment by Triticum0** [comment]
Added

**Comment by Megamouse** [comment]
I don't see any issue here.
The packages contain demos for the same game which happen to have the same ID.

**Comment by Triticum0** [comment]
But the Files are not the same size one missing all the movie folder as well as some audio files

**Comment by Megamouse** [comment]
One could contain the entire universe. It would still have the same ID.
We don't decide the ID. It's part of the package content.

**Comment by Triticum0** [comment]
but why is the pkg file different? If it is a non issue just close the issue. thank you for the help.

**Comment by Megamouse** [comment]
I don't know. Maybe ask the Studio that packaged the demos :)
