### ISSUE TITLE
[Regression] Several FIFAs crash on boot (#14088)

### ISSUE THREAD

**Issue by Skoczek777** [RPCS3/rpcs3#14094]
### Quick summary

Since version v0.0.28-15229, some FIFA games just started to crash immediately.
I confirm this for FIFA 09, FIFA 10, FIFA 11 and 2010 World Cup.
Later ones also may have this issue

### Details

Something definitely had happened between versions 0.0.28-15229 and 0.0.28-15231, that causes them to crash.

### Build with regression

v0.0.28-15231-70ce7ee1

### Attach two log files

[RPCS315229.zip](https://github.com/RPCS3/rpcs3/files/11859595/RPCS315229.zip)
[RPCS315231.zip](https://github.com/RPCS3/rpcs3/files/11859597/RPCS315231.zip)

**Comment by AniLeo** [comment]
Needs retest because there was already a followup fix to the mentioned PR

**Comment by Skoczek777** [comment]
It's already fixed. It can be closed
