### ISSUE TITLE
Once the discrete graphics card is selected to run the game, RPCS3 will crash.

### ISSUE THREAD

**Issue by AAlieZZ** [RPCS3/rpcs3#14098]
### Quick summary

If choose the integrated graphics card, everything will work fine.
 
Once the discrete graphics card is selected to run the game, RPCS3 will crash.

### Details

```
RPCS3: SIG: Thread terminated due to fatal error: Segfault reading location 0000000000000148 at 00007fbba6b43f76.
Thread: Main Thread.
```

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11870860/RPCS3.log)

### System configuration

OS：Arch Linux
CPU：AMD Ryzen 7 5800H
GPU：NVIDIA GeForce RTX 3060 Laptop
```
~  pacman -Qs nvidia-dkms
local/nvidia-dkms 535.54.03-1
    NVIDIA drivers - module sources
 
~  uname -a
Linux archlinux 6.3.8-arch1-1-g14 #1 SMP PREEMPT_DYNAMIC Sat, 17 Jun 2023 17:25:15 +0000 x86_64 GNU/Linux
```

### Other details

```
~  flatpak info net.rpcs3.RPCS3

RPCS3 - Open-source Sony PlayStation 3 Emulator

  标识： net.rpcs3.RPCS3
  引用： app/net.rpcs3.RPCS3/x86_64/stable
  架构： x86_64
  分支： stable
  版本： 0.0.28-1-aff871f1
    许可证： GPL-2.0-only
  来源： flathub
  集合： org.flathub.Stable
  安装： system
    已安装： 113.7 MB
    运行时： org.kde.Platform/x86_64/5.15-22.08
 SDK： org.kde.Sdk/x86_64/5.15-22.08

  交付： 9794ab2ac53758149148bcbc125867e215073541fba506f10530144725c31544
  上级： 1daf2c9eae6ee2ba66b9f9753e268aa05175ce30caa6f73c7bd9e24eb48db90a
  主题： Update rpcs3.git (267e212f)
  日期： 2023-06-26 03:03:33 +0000
```

**Comment by AAlieZZ** [comment]
The [AUR version](https://aur.archlinux.org/packages/rpcs3-bin)  also has the same problem.

**Comment by Valtekken** [comment]
> The [AUR version](https://aur.archlinux.org/packages/rpcs3-bin) also has the same problem.

The AUR version isn't maintained by RPCS3 directly either, so you have to use the AppImage

**Comment by utku-helvaci** [comment]
> > The [AUR version](https://aur.archlinux.org/packages/rpcs3-bin) also has the same problem.
> 
> The AUR version isn't maintained by RPCS3 directly either, so you have to use the AppImage
the aur package downloads the appimage from this repo
