### ISSUE TITLE
DX12: Final Fight: Double Impact - broken in-game graphics

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1410]
Ingame graphics broken since PR #1276. In previous PR #1271 it shows ingame graphics fine.

Logs from both builds:
http://rghost.ru/6LpZCXxwQ

**Comment by raven02** [comment]
@B1ackDaemon , how about right now in latest build?

**Comment by MarioSonic2987** [comment]
Is it still an issue?

**Comment by digitaldude555** [comment]
Yes.
