### ISSUE TITLE
Fatal error in Ratchet & Clank Future: Quest for booty

### ISSUE THREAD

**Issue by EvilPlayer1** [RPCS3/rpcs3#14103]
### Quick summary

When I use the turret in prologue, I always get fatal error. The game just stops with error.
![Screenshot 2023-06-27 16-24-32](https://github.com/RPCS3/rpcs3/assets/90133207/8bfd57b9-c2ff-4d06-b7ea-ee1334cc8d4b)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11882771/RPCS3.log)

### System configuration

OS - Windows 11
CPU - i7-11700
GPU - GTX 1660 SUPER
Driver version - 536.23

**Comment by kd-11** [comment]
Please attach the save file.

**Comment by Darkhost1999** [comment]
A new game will put you equally as far away as a savedata will. Maybe skipping 1 short cutscene.
I can test now to see if I can reproduce.

**Comment by Darkhost1999** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/60384196/494efd3c-2dd0-4e28-bc95-dc3857716eec)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11885434/RPCS3.log)
As far as I can tell I used the exact same config settings. I just have the disc version of the game and no crash.
I am using same GPU as author.

**Comment by kd-11** [comment]
I also cannot reproduce if it's this turret
![image](https://github.com/RPCS3/rpcs3/assets/15904127/a979f7ae-4458-48e4-a64b-1408f10a18be)

**Comment by EvilPlayer1** [comment]
Wow, I discovered another mysterious bug, which cannot be obtained with a 100% chance. I also can run through prologue without issues, but next time it will necessarily crash on turret or nearby it.

**Comment by kd-11** [comment]
I was able to reproduce the original crash after replaying the turret a bunch of times. This normally means the issue may not be fixable (you need to see it crashing to debug and it needs to happen the same way many times) but in this case it's just an assert. I'llo lower to warning message and move on.

**Comment by RinMaru** [comment]
are you using unlocked fps patchj by any chance? turning that off fixed all crashes for me/

**Comment by EvilPlayer1** [comment]
No, I'm using only freeze fix
