### ISSUE TITLE
[Regression] Some games stopped working

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#14110]
### Quick summary

In GOW Collection, when you try to open one of the 2 titles, instead of loading the PPU modules, the game shuts down for no reason.

List of affected games:
Red Dead Redemption
MGS Collection
ICO and Shadow of the Colossus Collection

### Details

The build 0.0.28-15259 (https://github.com/RPCS3/rpcs3/pull/14090) is the responsable

### Build with regression

0.0.28-15259

### Attach two log files

Working
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11900375/RPCS3.log)

Broken
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11900329/RPCS3.log)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11900385/RPCS3.log) <- RDR log

### Attach capture files for visual issues

None

### System configuration

OS - Windows 10 22H2
CPU - i7 8700
GPU - GTX NIVIDIA 1070 Ti
Driver version - 535.98

**Comment by Boiiiiiiiiiiiiiiiiiiii** [comment]
For more info, I tried the EU version of RDR GOTY and when the compilation finishes, the emulator crashes all together with no error message.

**Comment by solarmystic** [comment]
Confirmed, GOW2 crashes rpcs3 upon boot after selecting it at the launcher menu.

**Comment by Jonathan44062** [comment]
The PR https://github.com/RPCS3/rpcs3/pull/14112 Fixes the RDR issue and the other games
![image](https://github.com/RPCS3/rpcs3/assets/78843189/db602b26-f1b9-4bd4-9514-d3d0819a7632)
![image](https://github.com/RPCS3/rpcs3/assets/78843189/168f8337-45b8-40a7-9a84-aa88ba813e7e)
![image](https://github.com/RPCS3/rpcs3/assets/78843189/6449ec1d-621c-442b-a02e-9c58c2ca308d)
