### ISSUE TITLE
[Regression] Doubled/trippled controller inputs when Steam Input is enabled on Steam Deck/Linux

### ISSUE THREAD

**Issue by k6storama** [RPCS3/rpcs3#14119]
### Quick summary

Doubled/trippled controller inputs when Steam Input is enabled on Steam Deck/Linux.

### Details

As of pull #13999, the controller inputs are doubled/trippled when Steam Input is enabled, which affects gameplay, as well as rpcs3 in-game menus like selecting a save file.
It does happen in Gaming mode and Desktop mode for Steam Deck controller and the external ones.
Switching input APIs between Evdev and SDL doesn't make any difference.

### Build with regression

rpcs3-v0.0.28-15177-b436d2a7

### Attach two log files

[Regression.RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11928465/Regression.RPCS3.log.gz)
[Working.RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11928466/Working.RPCS3.log.gz)

### Attach capture files for visual issues

https://cdn.discordapp.com/attachments/277227681836302338/1124853517446828092/VID_20230702_015641.mp4

### System configuration

OS: SteamOS Holo x86_64 
Host: Jupiter 1 
Kernel: 5.13.0-valve36-1-neptune 
Uptime: 2 days, 21 hours, 26 mins 
Packages: 1131 (pacman), 22 (flatpak) 
Shell: fish 3.5.1 
Resolution: 1280x800 
DE: Plasma 5.26.1 
WM: KWin 
WM Theme: Breeze 
Theme: Vapor [Plasma], Vapor [GTK2/3] 
Icons: Papirus-Dark [Plasma], Papirus-Dark [GTK2/3] 
Terminal: konsole 
CPU: AMD Custom APU 0405 (8) @ 2.800GHz 
GPU: AMD ATI AMD Custom GPU 0405 
Memory: 5706MiB / 11794MiB 

### Other details

The issue doesn't happen when the Steam is turned off or Steam Input is disabled, though it can't be done for the Steam Deck controller in Gaming Mode.

**Comment by Megamouse** [comment]
Sounds like a steam bug...

**Comment by k6storama** [comment]
> Sounds like a steam bug...

It could be, but it doesn't happen on any previous build I've tested yesterday e.g. rpcs3-v0.0.28-15176-84d2ad70

**Comment by KMDEV99** [comment]
It is a bug with steam input. Many people are struggling with this. I've had had it few times on SD while using docked mode with Bluetooth controller.

**Comment by Yoghourrt** [comment]
I also had the same problem. My solution was to rearrange the Steam controller and move it to the number 1. What happened is that I was using 2 external controllers connected to the Steam deck. After disconnecting both of them, for whatever reasons, the Steam controller was still at the third order, which caused the tripled input.

**Comment by Megamouse** [comment]
I'll close this, since the user mentioned the same issue with evdev, but the PR only touched SDL.
This looks like a steam/driver issue.
