### ISSUE TITLE
I get an error when it seems to be working

### ISSUE THREAD

**Issue by JoaquinClarosGaming** [RPCS3/rpcs3#14122]
### Quick summary

I was wanting to play PvZ but when it appears the "Compiling Modules" message down-left it freezes and in the log appears this
![image](https://github.com/RPCS3/rpcs3/assets/102455395/70746881-71b1-48c3-a163-300515d1d79c)
and when i close the game appears this error
![image](https://github.com/RPCS3/rpcs3/assets/102455395/ff4e3cb6-6eda-4e68-84b9-cf13cd968603)

### Attach a log file

![image](https://github.com/RPCS3/rpcs3/assets/102455395/70746881-71b1-48c3-a163-300515d1d79c)

**Comment by AniLeo** [comment]
Thanks for ignoring both the support link in the error dialog and the issue guidelines
