### ISSUE TITLE
Gran Turismo 5 Black Screen

### ISSUE THREAD

**Issue by L3GIT123** [RPCS3/rpcs3#14127]
### Quick summary

I don't know why but i have a black screen every time when i start Gran Turismo 5 

### Details

I always has this, but game status show "ingame"
game is BCES00569

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11937568/RPCS3.log)

**Comment by FlexBy420** [comment]
Support request goes to discord or forums

**Comment by YuriNator557** [comment]
Log suggests broken game files
