### ISSUE TITLE
[BLES00392] Async crashes the Nvidia driver

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#14121]
Nvidia driver crashes when async is enabled in Spider-Man Web of Shadows.

> F {RSX [0x001021c]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
> (in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\VKQueryPool.cpp:45[:4], in function poke_query)
> (in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:114[:24], in function die_with_error)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11929979/RPCS3.log)

**Comment by Yuuyatails** [comment]
What graphics driver version you have?

**Comment by Asinin3** [comment]
Can't reproduce, same GPU same driver :/
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11990727/RPCS3.log)

**Comment by kd-11** [comment]
I'm able to reproduce. Happens instantly on going ingame.
