### ISSUE TITLE
[Feature request] Proper save icons without Write Color Buffers

### ISSUE THREAD

**Issue by gir489returns** [RPCS3/rpcs3#14132]
### Quick summary

When saving games that use some kind of in-game generated screenshot of what the player was looking at, the image gets corrupted when not using Write Color Buffers.

![Base Profile Screenshot 2023 07 04 - 11 22 40 79](https://github.com/RPCS3/rpcs3/assets/100792176/d1345aa4-dcb9-4244-b0db-15b5f5f03711)
![Base Profile Screenshot 2023 07 04 - 11 22 48 72](https://github.com/RPCS3/rpcs3/assets/100792176/2c681c8e-69a6-42b1-8d7d-86675c40ae0f)

### Details

What part of RPCS3 would be affected by your feature? UI
Why your feature is important to RPCS3: Completeness

**Comment by MSuih** [comment]
Having Write Color Buffers enabled is how PS3 operates. We allow disabling it for performance reasons but as you can see this will break some games that rely on this buffer data. There is nothing to do in this issue, the correct solution has already been implemented and you even know which setting to change.

**Comment by FlexBy420** [comment]
All bethesda games need WCB to render save icon properly btw

**Comment by gir489returns** [comment]
> Having Write Color Buffers enabled is how PS3 operates. We allow disabling it for performance reasons but as you can see this will break some games that rely on this buffer data. There is nothing to do in this issue, the correct solution has already been implemented and you even know which setting to change.

When I enabled Write Color Buffers, a lot of the game started to break. I got access violations and various other crashes that I didn't get with it disabled.

**Comment by AniLeo** [comment]
Then you can report these issues separately - this ticket is a non-issue by itself as is.
