### ISSUE TITLE
Uncharted 2 possible bug

### ISSUE THREAD

**Issue by NeuroRabbit** [RPCS3/rpcs3#14139]
### Quick summary
bug or problem, not sure

### Details

I'm not sure if it's a bug or an issue with the game. in chapter 2 of the game, when nate, and flynn arrive at the tower, flynn runs without leaving the place. and I can't get past that point, because he won't open the door

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11960644/RPCS3.log)

**Comment by MSuih** [comment]
1. If you are unsure whether this happens to others, ask around in our Discord.
2. This reads more like an compatibility report to me.
3. You're severely below minimum requirements and are playing a game which is known to be very difficult to emulate.
