### ISSUE TITLE
GL backend is broken

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1413]
With master if I tries to run any sample (primitives) or games (Sonic CD) there's nothing on screen with openGL.

There's a curious message, "RSX: E {rsx::thread} OpenGL: initialization of glDepthBoundsEXT failed."

**Comment by tambry** [comment]
@vlj Does your graphics card support the depth bounds extension (or whatever it is exactly called)?
That error message should only occur, when the graphics card doesn't support the given extension.

**Comment by vlj** [comment]
nvm the wrong adaptater (intel igpu) was being used, I fixed that and now everything is back to normal. sorry.
