### ISSUE TITLE
RPCS3 ERROR WHILE PLAY GOD OF WAR 3

### ISSUE THREAD

**Issue by AC0Kratos0** [RPCS3/rpcs3#14141]
### Quick summary

Hello Guys, 
I'm trying to play God Of War 3 in RPCS3 but the emulator is always show some errors in linking PPU Modules. I tried most of the ways to assess it but that error always remain same. So, anybody have any idea or solution about it please help me to resolve this issue 😥 
Files or Pics Related to the error are given below:-

### Details

![Uploading IMG20230630125316.jpg…]()
![Uploading IMG20230630125521.jpg…]()
![Uploading IMG20230630125534.jpg…]()
![Uploading IMG20230630125511.jpg…]()
![Uploading IMG20230630125159.jpg…]()
![Uploading IMG20230630125145.jpg…]()

### Attach a log file

K

### Attach capture files for visual issues

K

### System configuration

Core 2 Quad 9550 2.8GHz 4Cores Processor 

### Other details

K

**Comment by MSuih** [comment]
None of your images work and you didn't attach a log file either. And that CPU is far too slow to play God of War 3 anyways. I'd ask for you to message in our Discord but I think you can just forget about rpcs3 until you get modern hardware
