### ISSUE TITLE
[Regression] segmentation fault when opening settings

### ISSUE THREAD

**Issue by eyeonus** [RPCS3/rpcs3#14157]
### Quick summary

segfault when trying to open GPU, CPU, Audio, Input/Output, System, Advanced, Emulator, and GUI menus, and pressing on the config button in the top bar. Have already installed firmware 4.90, have not altered any settings (because I can't, it crashes).

latest revision which does not segfault as described: 15005
logfile = [RPCS3-r15005.log.gz](https://github.com/RPCS3/rpcs3/files/11994093/RPCS3-r15005.log.gz)

revisions 15006 - 15028 segfault at launch, does not get to main window, unable to test this issue
"·F 0:00:00.186614 SIG: Thread terminated due to fatal error: Segfault reading location 0000000000000008 at 0000000002ceba67."
logfile = [RPCS3-r15015.tar.gz](https://github.com/RPCS3/rpcs3/files/11994111/RPCS3-r15015.tar.gz)

revisions 15030+ segfault as described
"·F 0:00:05.546039 SIG: Thread terminated due to fatal error: Segfault reading location 0000000000000008 at 0000000002cee6e7."
"·F 0:00:03.515192 SIG: Thread terminated due to fatal error: Segfault reading location 0000000000000008 at 0000000002dc9397."
logfile = [RPCS3-r15030.tar.gz](https://github.com/RPCS3/rpcs3/files/11994113/RPCS3-r15030.tar.gz), [RPCS3-r15324.log.tar.gz](https://github.com/RPCS3/rpcs3/files/11994108/RPCS3-r15324.log.tar.gz)

### Build with regression

0.0.27-15006

### Attach two log files

working: [RPCS3-r15005.log.gz](https://github.com/RPCS3/rpcs3/files/11994093/RPCS3-r15005.log.gz)
not working at all (unable to test issue): [RPCS3-r15015.tar.gz](https://github.com/RPCS3/rpcs3/files/11994111/RPCS3-r15015.tar.gz)
problem as described: [RPCS3-r15030.tar.gz](https://github.com/RPCS3/rpcs3/files/11994113/RPCS3-r15030.tar.gz)

### System configuration

![image](https://github.com/RPCS3/rpcs3/assets/1733600/7cb014df-cc6d-426b-a49b-207e16031da3)

**Comment by oltolm** [comment]
So it started with 15006, which was this PR #13632.

**Comment by eyeonus** [comment]
Possibly. As I noted in the OP, I was unable to test if 15006 through 15028 had this particular issue, because they all crashed at launch.

**Comment by Mrlinkwii** [comment]
no issues here on  v0.0.29-15827- 8b6fa32d  on ubuntu 22.04 with the appimage  , @eyeonus  can you  recheck if possible

**Comment by eyeonus** [comment]
I have 0.0.29-15812 installed via Flatpak on my machine, and am not getting this issue with that version.
I tried to update using the in-app update checker, but it failed with a read-only error message.

I downloaded the appimage from the website and tested with that as well, and I am not having the issue with it, either.
