### ISSUE TITLE
Horrible Gas isn't visible

### ISSUE THREAD

**Issue by ZippyZolton** [RPCS3/rpcs3#14150]
### Quick summary

Horrible Gas seems to not render at all, which isn't very good when it's stuff that kills you a lot.

### Details

Can't do PS3 comparisons because mine isn't plugged in right now, sorry.

![image](https://github.com/RPCS3/rpcs3/assets/28773304/6566e6cf-3307-4e0b-b04c-d501fd9207c2)
Hovering over the Gas with my Popit

![image](https://github.com/RPCS3/rpcs3/assets/28773304/78e15ea0-01da-48a9-bb8e-3f5ceb65d482)
Horrible Gas in "Skate to Victory" (it should be where the water is)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11988323/RPCS3.log)

### Attach capture files for visual issues

[NPUA80472_20230707233054_capture.zip](https://github.com/RPCS3/rpcs3/files/11988399/NPUA80472_20230707233054_capture.zip)

### System configuration

i9-9900K
RTX 2060S
NVIDIA Driver Version 532.03

**Comment by MSuih** [comment]
As mentioned in [wiki](https://wiki.rpcs3.net/index.php?title=LittleBigPlanet) you need to enable Write Color Buffers for this effect to render.

![BCES00141_screenshot_2023_07_08_08_24_03](https://github.com/RPCS3/rpcs3/assets/19759300/576d9428-8bc4-488f-a5b2-5756a449e39d)
