### ISSUE TITLE
Segfaulting on title launch with Nvidia Optimus on Fedora Silverblue

### ISSUE THREAD

**Issue by threedope** [RPCS3/rpcs3#14158]
### Quick summary

Using current Flatpak. Doesn't segfault when using Intel iGPU. Always segfaults when using Nvidia dGPU. Happens on every title launch regardless of other settings.

Error:
Segfault reading location 0000000000000148 at 00007fa93f343f76.
Thread: Main Thread.

RPCS3 Version: 0.0.28-1-1219e5c2 Alpha | master | local_build

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11994437/RPCS3.log)

### System configuration

![Screenshot from 2023-07-08 23-49-37](https://github.com/RPCS3/rpcs3/assets/55446805/caf5b7e7-441c-4be4-8abd-815fecb5d287)

**Comment by Darkhost1999** [comment]
The flatpak isn't maintained by us making this report being reported on the wrong github issue tracker. If you can retest with binaries distributed by us, we can confirm that this issue is occurring from this repository.

**Comment by threedope** [comment]
Ok, wasn't sure if you guys maintained the Flatpak. I'll try the AppImage.
