### ISSUE TITLE
GUI: Patch creator does not escape control characters

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#14168]
1. Open Patch Creator
2. In the notes field, write something with double quotes
3. Notice the double quotes are added as-is to the final YAML without being escaped like `\"`, this causes the following error when exporting the patch due to broken YAML syntax
![image](https://github.com/RPCS3/rpcs3/assets/10283761/633d8150-73bc-425c-a0b8-105f6e0cd185)

**Comment by Megamouse** [comment]
Can't reproduce

![image](https://github.com/RPCS3/rpcs3/assets/23019877/e02c8bea-04ec-42fb-95a3-215f8efb1bc4)

**Comment by Megamouse** [comment]
oh. the "notes", not the comments

**Comment by Megamouse** [comment]
This is user error at best.
You can even see that it isn't valid in the preview
