### ISSUE TITLE
NHL 12 & NHL 13 (Access violation reading location)

### ISSUE THREAD

**Issue by dennyyyyyy** [RPCS3/rpcs3#14171]
### Quick summary

Hello everyone, I have a problem that I can not solve for a long time, because I did not find anything suitable in other topics. I mean "VM: Access violation reading location 0x310 (unmapped memory)". The problem occurs in newer versions of the emulator (probably after version 0.0.18-12817). Next, I will describe everything

### Details

In general, I initially tried to play NHL 12 on the latest build. With basic settings, I got the error "VM: Access violation reading location 0x310 (unmapped memory)". The error occurred at the beginning of the match, everything in the menu worked fine. It was the same with NHL 13 (but it was 0x248 in the log). I tried disabling "Accurate DFMA" and it didn't work. Next, I tried to install an older version of the emulator and both games began to work fully on version 0.0.18-12817 with the original settings. Next, I decided to try running both games on the latest build using ASMJIT Recompiler. And both games worked just as fully as on build 0.0.18-12817 (but of course worse than they could work on LLVM Recompiler). I tried to tell as much as possible, but I will try to provide all the necessary information if necessary. All logs for each case have been attached.

### Build with regression

0.0.28-15353

### Attach two log files

[NHL 12 LLVM Recompiler 0.0.28-15353.zip](https://github.com/RPCS3/rpcs3/files/12038032/NHL.12.LLVM.Recompiler.0.0.28-15353.zip)

[NHL 13 LLVM Recompiler 0.0.28-15353.zip](https://github.com/RPCS3/rpcs3/files/12038236/NHL.13.LLVM.Recompiler.0.0.28-15353.zip)

[NHL 12 LLVM Recompiler 0.0.18-12817.zip](https://github.com/RPCS3/rpcs3/files/11996453/NHL.12.LLVM.Recompiler.0.0.18-12817.zip)

[NHL 13 LLVM Recompiler 0.0.18-12817.zip](https://github.com/RPCS3/rpcs3/files/11996454/NHL.13.LLVM.Recompiler.0.0.18-12817.zip)

[NHL 12 ASMJIT Recompiler 0.0.28-15353.zip](https://github.com/RPCS3/rpcs3/files/12038246/NHL.12.ASMJIT.Recompiler.0.0.28-15353.zip)

[NHL 13 ASMJIT Recopiler 0.0.28-15353.zip](https://github.com/RPCS3/rpcs3/files/12038249/NHL.13.ASMJIT.Recopiler.0.0.28-15353.zip)

### System configuration

CPU: AMD Ryzen 7 3750H Mobile
GPU: NVIDIA GeForce GTX 1650
RAM: 16 GB

**Comment by dennyyyyyy** [comment]
added a number of version with problem

serial numbers of games
NHL 12 - BLUS30791
NHL 13 - BLUS31003

**Comment by ChwaraeTeg** [comment]
The information the developers will be looking for is the exact version number where the regression occurs - they'll need the newest version where the game works fully on the default settings and the oldest version where the error starts to occur.

**Comment by dennyyyyyy** [comment]
Ok, i realized that a problem not in regression, because i got a normal gameplay at default settings on both games

and i found a setting that gives a crash, because of access violation reading location

so, after switching in "SPU XFloat Accuracy" setting from "Approximate XFloat" to "Relaxed XFloat", it causes a crash with access violation reading location

here is the logs on each case

NHL 12 on default settings with Approximate XFloat
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12051392/RPCS3.log.gz)

NHL 13 on default settings with Approximate XFloat
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12051540/RPCS3.log.gz)

NHL 12 with Relaxed XFloat
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12051580/RPCS3.log.gz)

NHL 13 with Relaxed XFloat
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12051615/RPCS3.log.gz)

**Comment by ChwaraeTeg** [comment]
So it works okay in the current version of RPCS with default settings? And only breaks when one of the accuracy settings is changed to make the emulator less similar to real console behavior? If so, this doesn't sound like a valid issue.

**Comment by dennyyyyyy** [comment]
So far, I've managed to find out what causes the crash at the beginning of the gameplay. I need to understand if there will be crashes with long gameplay.

In addition, it would be interesting to know what is the reason for such a reaction of the emulator to Relaxed XFloat in these games. Because it hasn't been seen in other games.

**Comment by AniLeo** [comment]
Closing as it's not an issue: Lowering XFloat accuracy is a hack, if it works with Accurate XFloat then that's all that matters, the other settings are just trading accuracy for performance so it is normal that it causes issues on some games
