### ISSUE TITLE
BLES01898 Thread Verification Failed Crash When Upscaled

### ISSUE THREAD

**Issue by NikkMann** [RPCS3/rpcs3#14184]
### Quick summary

On Armored Core Verdict Day, after entering and then leaving AC Test in the workshop, when you try to leave that menu, if you are using upscaling, RPCS3 itself will entirely freeze, including the game, and you have to force close rpcs3.exe in task manager.
F {RSX [0x0021690]} SIG: Thread terminated due to fatal error: Verification failed
This happens on every region version for the game, and this is after already using the listed fix on the last post from this issue to fix a VM Thread crash in the same area (upscaled or not) https://github.com/RPCS3/rpcs3/issues/13546
There are no crashes on native res when using this fix, only upscaled.

This exact same crash happens in several other menus of the game as well, again only when upscaled.

### Details

![image](https://github.com/RPCS3/rpcs3/assets/90150509/69fff47c-0fe6-49ad-9320-3fcddf89781a)

The red CELL errors before the VM error in the pic happened several minutes before and I played fine with those errors. They pop up when loading into a level but it loads fine.

You'll see a few weird settings for the game in my log to increase cpu performance, but the issue happens on default settings as well as long as you're upscaled

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12018099/RPCS3.log)

**Comment by kd-11** [comment]
To get any meaningful debugging, you'll need to also provide a save file and a series of steps to reproduce the crash.

**Comment by NikkMann** [comment]
Sure, my save:
[BLES01898GAME20C8.zip](https://github.com/RPCS3/rpcs3/files/12018463/BLES01898GAME20C8.zip)

You also need to put the attached se_weapon.fsb file in your dev_hdd0/game/BLES01898_DLC (or other region ID folder)/USDIR/sound folder to fix the other crash that happens in this area listed in the issue I linked.
[se_weapon.zip](https://github.com/RPCS3/rpcs3/files/12018522/se_weapon.zip)

Steps:
- Set the game to upscale in the settings (I play on 3840x2160)
- Launch the game
- on the Main menu, choose workshop
- In workshop, choose AC Test
- Choose Start Test
- After you've loaded into the level, pause by pressing Select on the controller and choose Retire. This will take you back to AC Test menu
- Try to leaving the AC Test and go back to the workshop menu by pressing B/Circle. 
- Crash

The same crash also happens if you do the following when upscaled (this one works fine not-upscaled without the se_weapon.fsb fix):
- In workshop again, choose Workshop Cust.
- Use the bumpers to choose a different workshop option
- Try to leave the customization menu using B/Circle, and when it asks you to "use elected workshop", hit "no"
- Crash

**Comment by NikkMann** [comment]
I installed the vulkan sdk and got logs for both crashes with debug output enabled. Performance was terrible lol.
[AC Test Crash Debug.log](https://github.com/RPCS3/rpcs3/files/12022074/AC.Test.Crash.Debug.log)
[Workshop Customization Crash Debug.log](https://github.com/RPCS3/rpcs3/files/12022075/Workshop.Customization.Crash.Debug.log)

**Comment by NikkMann** [comment]
Not sure if it's related but performance in the game is generally poor due to being extrremely cpu limited. With a ryzen 5900x I barely get above 30 fps in-match. In menus I get around 90 fps because it's not cpu limited anymore (RTX 3090).
Others have the same issue.

**Comment by kd-11** [comment]
Actual ticket: https://github.com/RPCS3/rpcs3/issues/14410
The good news is I know why it crashes. The bad news is that it's a lot of work that'll need a few days to finish.

**Comment by kd-11** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/14446
