### ISSUE TITLE
[MRTC00003]  FINAL FANTASY XIII: SPU Seems Stuck In A Loop

### ISSUE THREAD

**Issue by Darkness13393** [RPCS3/rpcs3#14189]
### Quick summary

I cant say if this is a regression because i have only started playing with the emulator this week.

FFXIII doesn't advance past the square enix screen, it freezes, no black screen or anything straight up freezes.
Config: All defaults except for PPU Interpreter (static), and SPU  Interpreter (Dynamic), because the game doesn't like LLVM (didn't work)

One line that is repeated over and over in the RPCS3.log is
`{SPU[0x0000200] Thread (SystemSpursCellSpursKernel0) [0x0a898]} SPU: sys_spu_thread_send_event(spup=1, data0=0x0, data1=0x1fa80): error (CELL_ENOTCONN)`

OS: FreeBSD 13.2
CPU: i7-11700
RAM: 32Gb
Build: 0.0.28.15307

### Details

Expected Behavior: Continues the game to the main screen and after
Actual Behavior: freezes on square enix screen

### Attach a log file

I"ve tried to upload it here but it doesn't work, nor Mega and Dropbox.
Sorry

But this line repeats for 15000 times
`{SPU[0x0000200] Thread (SystemSpursCellSpursKernel0) [0x0a898]} SPU: sys_spu_thread_send_event(spup=1, data0=0x0, data1=0x1fa80): error (CELL_ENOTCONN)`

### Attach capture files for visual issues

N/A

### System configuration

Above

### Other details

N/A

**Comment by elad335** [comment]
Simply drag and droop the log file onto the issue edit text box 🤔

**Comment by MSuih** [comment]
Make sure you've closed the emulator first before trying to upload the log.

**Comment by Darkness13393** [comment]
file:///usr/home/larry/.cache/rpcs3/RPCS3.log.gz

**Comment by Darkness13393** [comment]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12034077/RPCS3.zip)

Sorry for the wait, i had to remove the .log after trial and error

**Comment by Darkness13393** [comment]
oops closed this accidentally

**Comment by Darkness13393** [comment]
Hmm, playing with this further.
The (program) log says this

`- SYS: RPCS3 v0.0.28-15307-g8f178b2c29 Alpha | master
- SYS: 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 16 Threads | 39.74 GiB RAM | TSC: 2.496GHz | AVX-512+ | FMA3
- SYS: Operating system: POSIX, Name: FreeBSD, Release: 13.2-RELEASE-p1, Version: FreeBSD 13.2-RELEASE-p1 GENERIC
- SYS: Current Time: 2023-07-15T00:12:22
- RSX: Found vulkan-compatible GPU: 'Intel(R) Graphics (RKL GT1)' running on driver 23.1.99
- RSX: Found vulkan-compatible GPU: 'llvmpipe (LLVM 15.0.7, 256 bits)' running on driver 0.0.1
- SYS: Firmware version: 4.90
E cellAudio: Audio backend Null does not support buffering, this option will be ignored.
- RSX: Found vulkan-compatible GPU: 'Intel(R) Graphics (RKL GT1)' running on driver 23.1.99
- RSX: Found vulkan-compatible GPU: 'llvmpipe (LLVM 15.0.7, 256 bits)' running on driver 0.0.1
E RSX: Your GPU driver does not support some required MSAA features. MSAA will be disabled.
E RSX: Your GPU does not support double precision floats in shaders. Graphics may not render correctly.
E RSX: Robust buffer access is broken when enabled with EXT_descriptor_indexing on ANV
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/fade_top.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/fade_bottom.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/select.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/start.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/cross.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/circle.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/triangle.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/square.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/L1.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/R1.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/L2.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/R2.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/save.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/new.png' could not be opened (Not found)
E RSX: Image resource file `/home/jason/.config/rpcs3/Icons/ui/spinner-24.png' could not be opened (Not found)
E RSX: AMDGPU kernel driver on linux and INTEL driver on some platforms cannot support passthrough DMA buffers.
S Input: The pad mode was changed to Single-threaded
S GUI: Boot successful.
U sys_prx TODO: _sys_prx_register_module(name=?cellProcessElf?, opt=*0xd0020ce0)
S sys_prx: Loaded module: ?/dev_flash/sys/external/libsysmodule.sprx? (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0020a50)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0020a50, a3=0x0)
S sys_prx: Loaded module: ?/dev_flash/sys/external/libgcm_sys.sprx? (id=0x23000e00)
S sys_prx: Loaded module: ?/dev_flash/sys/external/libio.sprx? (id=0x23001000)
S sys_prx: Loaded module: ?/dev_flash/sys/external/libsre.sprx? (id=0x23001100)
U sys_prx TODO: _sys_prx_register_module(name=?_sysProcessElf?, opt=*0xd0020df0)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=?cellLibprof?, flags=0, pOpt=*0x0) x2
E cellAudio: Audio backend Null does not support buffering, this option will be ignored.
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
S sys_prx: Loaded module: ?/dev_flash/sys/external/libfiber.sprx? (id=0x2301c100)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=?cellLibprof?, flags=0, pOpt=*0x0)z
S sys_prx: _sys_prx_unload_module(id=0x2301c100, flags=0x0, pOpt=*0x0): name='libfiber.sprx'
S sys_prx: Loaded module: ?/dev_flash/sys/external/libfiber.sprx? (id=0x2301ce00)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=?cellLibprof?, flags=0, pOpt=*0x0)
E sys_fs: 'cellFsOpen' failed with 0x80010006 : CELL_ENOENT, ?/dev_bdvd/PS3_GAME/USRDIR/white_data/sys/filelist.ps3.bin? [1]
E sys_fs: 'cellFsOpen' failed with 0x80010006 : CELL_ENOENT, ?/dev_bdvd/PS3_GAME/USRDIR/white_data/sys/patchlistu.ps3.bin? [1]
E sys_fs: 'cellFsOpen' failed with 0x80010006 : CELL_ENOENT, ?/dev_bdvd/PS3_GAME/USRDIR/white_data/sys/patchlist_scru.ps3.bin? [1]`

**Comment by Darkness13393** [comment]
Maybe a bad dump??
Or the game doesn't work??

**Comment by thezphynx** [comment]
Can confirm the game was working successfully before the recent update. I dumped about 40 hours into it. I dont have a build number, but it was running it on steam os, & the last time i ran updates was on 06/01/2023. Everything was working up until I ran updates yesterday.

Not it locks up shortly after  boot, when Linking PPU modules

**Comment by thezphynx** [comment]
Some addt'l info - i went back and tried launching the game with linux builds released in jun/may/april.

successfully launched with build #13534 from 04-06-2023. Builds released early may and june both were problematic.

**Comment by Darkness13393** [comment]
Interestingly this is the log with SPU Debug enabled
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12139975/RPCS3.zip)

**Comment by thezphynx** [comment]
Confirming that the game did work before a recent update. I just tested some builds released over the past few months. Those from early May and June were problematic. A build releases in April successfully launched the game:

rpcs3-v0.0.27-14843-8a509afc_win64

**Comment by thezphynx** [comment]
Resolved for me by tweaking some settings:

CPU
PPU Decoder: Interpreter (static)
SPU Decoder: Recompiler (LLVM)
Enable SPU loop detection 

Audio
Enable time stretching (to prevent audio crackle)

**Comment by Darkness13393** [comment]
With the euro version it now works, usa version didn't work (idk why)
Build: 0.0.28-15391
But i still have performance problens due to llvm not working (SPU and PPU) but that has its own issue.
I can close this issue now.

**Comment by Darkhost1999** [comment]
SPU LLVM should work.
PPU LLVM is another issue that you mentioned. So, performance should be from the perspective of a Ryzen 5 3600 in the high 20 fps when trying to play with PPU Interpreter.

**Comment by Darkness13393** [comment]
> SPU LLVM should work.

> should
Yes it should but here it locks because of an SPU error, maybe just my configuration as everything gpu is cranked to the highest

**Comment by Darkhost1999** [comment]
This is the same issue that was closed.
Works with all defaults + accurate SPU DMA in the advanced tab of the configuration.

**Comment by joshuacox** [comment]
I hate necro-bump posts, but I saw a similar issue today where I could see it looking for spinner-24.png in `/home/user1/.config/rpcs3//Icons/ui/spinner-24.png`  to fix this, I merely symlinked that directory from /usr

`ln -s /usr/share/rpcs3/Icons /home/user1/.config/rpcs3/`  typing from memory so please excuse any typos.  The double slash in front of the path it Icons was like that in the log output ( which indicates to me there might be some env var issue when this was generated, which might be a genuine bug ).  Now all is well for me.

**Comment by bigol83** [comment]
> I hate to necro-bump posts, but I saw a similar issue today where I could see it looking for spinner-24.png in `/home/user1/.config/rpcs3//Icons/ui/spinner-24.png` to fix this, I merely symlinked that directory from /usr
> 
> `ln -s /usr/share/rpcs3/Icons /home/user1/.config/rpcs3/` typing from memory so please excuse any typos. The double slash in front of the path to `//Icons` was like that in the log output ( which indicates to me there might be some env var issue when this was generated, which might be a genuine bug ).
> 
> Now all is well for me.
> 
> EDIT: of note, I might've inadvertently broke some things when I moved that rpcs3 directory to it's own partition and then symlinked it back to that .config directory as I did not want giant games going into my encrypted home directory, which looks like this:
> 
> ```
> ls -alh ~/.config |grep rpcs3
> lrwxrwxrwx     - user1  3 Apr 21:29  rpcs3 -> /mnt/ps3/rpcs3
> ```
> 
> Possibly rpcs3 borked on creating that `~/.config/rpcs3/Icons` directory? Because it was a symlink and not a directory?

How do you manage to even go past the compiling preboot phase? It crashes for me, every time i try.
