### ISSUE TITLE
DX12 Performance regression in dice test

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1418]
Caused by https://github.com/RPCS3/rpcs3/pull/1344 by @vlj (haven't bisected particular commit)
Fps went down by 10-15.

**Comment by tambry** [comment]
@danilaml What GPU, CPU, etc?
Also would be nice to have a log, so we can see the rest of the used options.

**Comment by danilaml** [comment]
@tambry both on intel hd4600 iGPU and amd r9 290. DX12, with interp 2 or recompiler, doesn't matter.

**Comment by vlj** [comment]
there should be more perf with latest master

**Comment by danilaml** [comment]
@vlj didn't change much. Still ~21-22 fps on both amd and intel (while before it was 37 for amd and ~59-60 for intel).

**Comment by vlj** [comment]
If you profile cpu usage is there any function that peaks between 1344 and master ?

**Comment by danilaml** [comment]
@vlj can't test 1344 right now but here's what I have on master:
```
Function Name	Total CPU (%)	Self CPU (%)	Total CPU (ms)	Self CPU (ms)	Module
 - D3D12GSRender::end	74.43 %	0.50 %	30484	204	rpcs3.exe
```
Of that the largest % is:
```
Function Name	Total CPU (%)	Self CPU (%)	Total CPU (ms)	Self CPU (ms)	Module
 + D3D12GSRender::upload_vertex_attributes	28.83 %	0.56 %	11808	229	rpcs3.exe
```
followed by 12% in external code (driver)
(PPUThread::on_task is 18%)

**Comment by danilaml** [comment]
@vlj by bisecting I found that with the first PR commit https://github.com/vlj/rpcs3/commit/6fae5863cfb4337e20620a9ebf29b425f3e9f22b I already had slow down but not that drastic (I had only 27-29 fps with it while with latest 1344 commit I had 23-24 max and with current master it's 21-22).
Profiling it it's 29/19 for rsx/ppu % of usage.
```
Function Name	Total CPU (%)	Self CPU (%)	Total CPU (ms)	Self CPU (ms)	Module
 + D3D12GSRender::end	70.34 %	0.35 %	10527	52	rpcs3.exe
```
```
Function Name	Total CPU (%)	Self CPU (%)	Total CPU (ms)	Self CPU (ms)	Module
 + D3D12GSRender::upload_vertex_attributes	21.44 %	0.45 %	3209	67	rpcs3.exe
```

**Comment by danilaml** [comment]
@vlj correction. Tested today with #1500 and #1496 merged and fps is 26-28 so it came back to early #1344 performance but still not as good as pre-1344.

**Comment by raven02** [comment]
If performance is back , i'm closing it .Feel free to open if has this performance issue on latest build
