### ISSUE TITLE
Little Big Planet 2 [BCES00850]: Video freezes

### ISSUE THREAD

**Issue by Eli4207** [RPCS3/rpcs3#14193]
### Quick summary

Random freezing of the video occurs on Steam Deck

### Details

After running fine for a while (a few minutes) on my Steam Deck, the video of the game suddenly completely freezes (the audio continues to run in the background)

The game runs just fine with the latest RPCS3 Versions on my main pc.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12038301/RPCS3.log.gz)

### System configuration

Processor: AMD APU | CPU: Zen 2 4c/8t, 2.4-3.5GHz (up to 448 GFlops FP32)
GPU: 8 RDNA 2 CUs, 1.0-1.6GHz (up to 1.6 TFlops FP32)
RAM: 16 GB LPDDR5 on-board RAM (5500 MT/s quad 32-bit channels)
Vulkan: Driver 23.0.99
--> Steam Deck

### Other details

**Config:**
CPU: Enabled SPU loop detection, Preferred SPU Threads: 3
GPU: Renderer: Vulkan, ZCULL Accuracy: Relaxed
Audio: Enabled Buffering: 70ms, Enabled Time Stretching: 25%

Patches: Disable SPU MLAA

I also tried ZCULL Accuracy: Approximate and Precise, but with these two I get the same issue.

**Comment by Asinin3** [comment]
Does it still happen with the SPU MLAA Patch disabled?
The issue says its only video freezes, do you mean actual cutscene/title screen videos? If so, try going to Settings > Advanced > search for the "libvdec" library and tick it. See if that helps.
