### ISSUE TITLE
Tales of Xillia "an error occurred with the DLC" on launch. Cannot start game.

### ISSUE THREAD

**Issue by Monkeor** [RPCS3/rpcs3#14191]
### Quick summary

When launched, after the initial logo splash screens, the screen goes black as says "An error occurred with the DLC. Please quit the game and try downloading again."

### Details

This is happening on the current build, 0.0.28-15346-c0280b43
Running Windows 10

### Attach a log file

https://www.dropbox.com/s/7n29ma4616ijee2/RPCS3.log?dl=0

**Comment by YuriNator557** [comment]
Log indicates a missing license file

**Comment by elad335** [comment]
Closing then.

**Comment by Monkeor** [comment]
Reinstalling the DLC doesn't fix the issue. What is a license file, and why would it not be included in the DLC packages I installed?

This is a new issue as of updating off v0.0.8 to 0.0.29

**Comment by Monkeor** [comment]
Nevermind, I had to move .RAP files into dev_hdd0\home\00000001\exdata, then the error stopped showing up. I apologize for being stupid.
