### ISSUE TITLE
Emulator crashes if games try to open privileged ports on Linux

### ISSUE THREAD

**Issue by valters-tomsons** [RPCS3/rpcs3#14210]
### Quick summary

Trying to host a local multiplayer server via dev menu in Battlefield 1943 & Bad Company crashes the emulator with: 
```Access violation reading location 0x0 (unmapped memory)```

### Details

* Battlefield 1943 (NPEB00092) (attached log)
* Battlefield Bad Company (BLES00261)

By default game does not allow to start a server, but this can be achieved via dev menu after modding said games. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12065445/RPCS3.log)

### System configuration

OS: Linux 6.4.2
CPU: AMD Ryzen 5 3600XT
GPU: AMD ATI Radeon RX 6700 (vulkan-radeon 23.1.3-2)

### Other details

By default, neither game allows hosting a game, but it's possible to do via dev menu. For BFBC1, just enable the `Dev Menu` game patch.

For other games:

```
Enabling dev menu in frostbite 1 games:
* open mainmenu-00.fbrb file using BFBC2Toolkit
* load up "main_nav.swfmovie" using hex editor, change enableDevOpts into canPause
```

**Comment by valters-tomsons** [comment]
This can be tagged as regression, since there are screenshots on the discord server that show this working on `0.0.27.14839`

<details> 
  <summary>Screenshots here </summary>

![image](https://github.com/RPCS3/rpcs3/assets/4209639/2fed160b-c82a-414a-ba60-4e2bb80024a3)
![image](https://github.com/RPCS3/rpcs3/assets/4209639/647bcbf6-bbb2-4376-bb7e-f458957298e9)
![image](https://github.com/RPCS3/rpcs3/assets/4209639/5f37074e-cfad-4454-b6ed-78f94091e2ce)
</details>

**Comment by Boiiiiiiiiiiiiiiiiiiii** [comment]
If you go on [Battlefield 1943](https://wiki.rpcs3.net/index.php?title=Battlefield_1943) or [Battlefield: Bad Company](https://wiki.rpcs3.net/index.php?title=Battlefield:_Bad_Company), they both say that they require a custom server, but what you could do is go to an older version of RPCS3 and try again until you find a working version.

**Comment by valters-tomsons** [comment]
I tested a few more versions, this always crashes on linux, works just fine on windows.

**Comment by valters-tomsons** [comment]
Managed to also replicate on Windows, but it's much more rare. Perhaps even another issue, because it crashed a little later than it does on Linux. (it started loading the map, instead of instantly crashing)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12612947/RPCS3.log.gz)

**Comment by valters-tomsons** [comment]
Game tries to open ports `1001` and `1003`, adding binding capabilities to RPCS3 allows starting the server like on windows.

```
sudo setcap 'cap_net_bind_service=+ep' /usr/bin/rpcs3
```

**Comment by RipleyTom** [comment]
Added a warning for when that happens, there isn't much more we can do from rpcs3's side.
