### ISSUE TITLE
Vulkan Renderer White screens

### ISSUE THREAD

**Issue by Killo500** [RPCS3/rpcs3#14219]
### Quick summary

Using the Vulkan renderer, starting a game leads to a temporary white screen before RCPS3 exits entirely without an error.

### Details

Having Installed a fresh instance of RPCS3 and importing a valid pak (tested). Clicking play will bring up the game window after a few seconds where it's just a white screen and will promptly close after 3-5 seconds without any error in the logs or post crash window to tell where the problem may lay, leaving to me having to reopen the app. Swapping to the OpenGL renderer, however, will open the game perfectly fine and run it as intended just with heavy framerate loss. I've tried swapping around the settings with the discretion of myself, a close knowledgeable friend and the mods on discord with no prevail (wiki settings do not work either).

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12076429/RPCS3.log)

### System configuration

OS: Windows 10 (up to date as of writing)
GPU: RTX 4070 [536.40] (also up to date with several attempted drivers)
CPU: Ryzen 7 2700
RAM: 32G DDR4 2400Mhz

**Comment by MSuih** [comment]
This is probably another issue with incompatible vulkan layers or somesuch nonsense. The [Vulkan diagnosis tool](https://github.com/13xforever/vkdiag/releases/latest) can help diagnose such cases.

As this doesn't seem to be a common issue but rather something in your PC configuration I think you should head to our Discord for tech support.
