### ISSUE TITLE
DX12: undeclared identifier 'packSnorm2x16'

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1422]
Discovered in game Prince of Persia Trilogy 3D (BLES01092)
http://www.emunewz.net/forum/showthread.php?tid=173729

**Comment by raven02** [comment]
i think packSnorm2x16 is for GLSL only.

**Comment by raven02** [comment]
@B1ackDaemon , if change the packSnorm2x16($0) to round(clamp($0, -1.0, 1.0) * 32767.0) , did it look better?

**Comment by B1ackDaemon** [comment]
@raven02, it goes further, but now asking for 'unpackSnorm2x16'.

**Comment by PZerua** [comment]
Also happens in God of War 3 DEMO.

**Comment by raven02** [comment]
@B1ackDaemon , then how about change unpackSnorm2x16 to clamp($0 / 32767.0, -1, +1) ?

**Comment by vlj** [comment]
Pack should convert vec 2 to a single uint, I think there's a l shift missing somewhere.

**Comment by B1ackDaemon** [comment]
@raven02 , now it goes to menus and ingame. Unfortunately, it's still very broken, and there is almost no graphics output, in log i noticed
```
E {rsx::thread} Unimplemented TEX_SRB instruction: UPB
E {rsx::thread} NV3089_IMAGE_IN_SIZE: unknown origin (1)
E {rsx::thread} Unimplemented SCB instruction: PKB
```

Comparing to earlier attempts, now it at least displays something, like balcony with light, and prince
http://rghost.ru/88qfBvCWb/image.png

**Comment by B1ackDaemon** [comment]
I discovered something odd here. With original code OGL render fails to compile shader:

```
{rsx::thread} RSX: Unimplemented TEX_SRB instruction: UPB
{rsx::thread} RSX: Failed to compile shader: 0(73) : error C7011: implicit cast from "vec4" to "vec2"
```

but works with suggested changes by @raven02

**Comment by kd-11** [comment]
@B1ackDaemon The algorithm given is correct, but i think is incomplete. If i understand the spec correctly, round(float2) should return a int2 vector, not a single u32. As @vlj pointed out, the function converts a vec2 to a u32, and the y component occupies bits 16-31, the x bits 0-15, so a bitshift is missing somewhere. For opengl, could you share the glsl outputs? (vertexprogram.txt and fragmentprogram.txt).

**Comment by B1ackDaemon** [comment]
@kd-11 done:
http://rghost.ru/8BnVRLsB2

**Comment by kd-11** [comment]
@B1ackDaemon the shader is malformed: the instruction packsnorm2x16 takes a vec2, not a vec4. Also, it makes no sense to pack a two component vector where all components are equal to the first value (.xxxx) should be packsnorm2x16(vec.xy).x.

**Comment by danilaml** [comment]
@B1ackDaemon can you test if https://github.com/RPCS3/rpcs3/pull/1700 indeed fixed the issue?

**Comment by kd-11** [comment]
Its unlikely that the fix was correct. the implemented section is only part of the solution and not a functional equivalent unless I'm misunderstanding the glsl spec.

https://www.opengl.org/registry/specs/ARB/shading_language_packing.txt

The functions packUnorm2x16(), packSnorm2x16(), packUnorm4x8(), and
    packSnorm4x8() first convert each component of a two- or four-component
    vector of normalized floating-point values into 8- or 16-bit integer
    values.  Then, the results are packed into a 32-bit unsigned integer.

This means that to emulate a pack you need to use that round() algorithm on the individual components and then bitshift and mask the results together. The opposite is true for the unpack.

As for prince of persia, the black screen persists in dx12.
