### ISSUE TITLE
[Regression] Cannot build with system LLVM anymore

### ISSUE THREAD

**Issue by guoyunhe** [RPCS3/rpcs3#14227]
### Quick summary

RPCS3 used to work with system LLVM. Since [this commit](https://github.com/RPCS3/rpcs3/commit/0c94606fcfc96a5e8044f9079541ce4cc8673614) it doesn't be built anymore (making the build process much slower).

### Build with regression

https://github.com/RPCS3/rpcs3/commit/0c94606fcfc96a5e8044f9079541ce4cc8673614

### Attach two log files

111

**Comment by Nekotekina** [comment]
What is BUILD_LLVM set to?

**Comment by guoyunhe** [comment]
@Nekotekina I didn't set BUILD_LLVM. It used to find system LLVM automatically.

**Comment by guoyunhe** [comment]
@Nekotekina I searched the repo. BUILD_LLVM is defined but not used...

![image](https://github.com/RPCS3/rpcs3/assets/5836790/bb88a8f1-2650-46a5-b111-9b6980375e79)

**Comment by MSuih** [comment]
@guoyunhe It is used.

https://github.com/RPCS3/rpcs3/blob/568e7481d87f7bb2cac68eb24be967b1da75619f/3rdparty/llvm/CMakeLists.txt#L5

**Comment by guoyunhe** [comment]
@MSuih then you must clone llvm even if you don't need to build it... There used to have a `3rdparty/llvm.cmake` file that conditionally include `llvm` sub directory. But now it disappeared.

**Comment by MSuih** [comment]
Folder structures for most 3rdparty modules was changed so that `3rdparty/<module>` contains build and configuration files and `3rdparty/<module>/<module>` contains the actual git submodule. In this case the llvm submodule is now in `3rdparty/llvm/llvm` and I don't think you're required to fetch that.
