### ISSUE TITLE
god of war and kill zone

### ISSUE THREAD

**Issue by mahmoudseilem** [RPCS3/rpcs3#14228]
### Quick summary

i try everything to fix its not working for god of war 3 

1. the log 

### Details

U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0010df0)
S PPU: LLVM: Loaded module v6-kusa-fLV79QqHgPi90UziTsWrHo-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23001d00)
S PPU: LLVM: Loaded module v6-kusa-ttuWcrR8vkrZXRoK2sr771-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsmvd2.sprx” (id=0x23003700)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) x2
S cellSysutil: Mounted existing cache at C:/Users/mmaas/OneDrive/Desktop/rpcs3-v0.0.25-14404-337ee77a_win64/dev_hdd1//caches/BCES00799_BCES00799/
U sys_prx TODO: _sys_prx_stop_module(): cmd is 8 (stop function = *0x9f0100)
U sys_prx TODO: _sys_prx_stop_module(): cmd is 8 (stop function = *0x9904d8)
U sys_prx TODO: _sys_prx_stop_module(): cmd is 8 (stop function = *0x930814)
S sys_process: Process finished

### Attach a log file

``

### Attach capture files for visual issues

 @**__**

### System configuration

AMD Ryzen 5 5600H with Radeon Graphics            3.30 GHz
rtx 3050 4g laptop

### Other details

. @

**Comment by mahmoudseilem** [comment]
i need help

**Comment by FlexBy420** [comment]
Support request goes into our discord or forums.
Do not open issues for that.

**Comment by mahmoudseilem** [comment]
ok
