### ISSUE TITLE
Game "WET" crashed after returning from upgrade menu

### ISSUE THREAD

**Issue by Virjoinga** [RPCS3/rpcs3#14225]
### Quick summary

When I left the upgrades menu, the game crashed.

### Details

I finished the "training area" and after leaving the upgrades menu, the game crashed. Also I had to force close the emulator for the game to close.

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12091813/RPCS3.zip)

### System configuration

Windows 10 x64
Ryzen 9 7950X
RTX 3080

### Other details

I was using a patch I am working on for configurable aspect ratios but I don't think that would matter in this instance.

**Comment by Virjoinga** [comment]
Turns out that it happens in gameplay too.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12092197/RPCS3.zip)

**Comment by Asinin3** [comment]
From your log:
Don't use SPU Loop Detection, its absolutely pointless on your CPU.
Relaxed Zcull can sometimes cause instability, does it happen with approximate?

Fatal Error (that should have been in OP post):
```Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\sync.cpp:580[:6], in function wait_for_fence)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:114[:24], in function die_with_error)```

**Comment by Virjoinga** [comment]
Ah okay why is SPU Loop Detection not needed? Also I haven't had a crash so far with those changes.

**Comment by Virjoinga** [comment]
Okay it seems that changing ZCULL accuracy to Relaxed fixes the game crashes. I was able to finish the rest of the game without any crashes and I even retested older levels. I'll make a video about it soon.

**Comment by Asinin3** [comment]
Big doubt, probably just a random crash/race condition like many other things in the emulator.

**Comment by Virjoinga** [comment]
Eh perhaps, all you gotta know is that for me I haven't had a crash since your recommendation. Maybe test it yourself with that setting changed to relaxed.

**Comment by Asinin3** [comment]
Are you sure you don't mean approximate? Relaxed zcull is the one that you said you were using which can be unstable which is why I said not to use it. Precise is default and would be fine too, its just a bit slower.

**Comment by Virjoinga** [comment]
oh sorry I meant Approximate. With approximate it doesn't crash.

**Comment by Asinin3** [comment]
And this is why you read setting descriptions. We tell people that Relaxed can break some games:
![image](https://github.com/RPCS3/rpcs3/assets/15137035/e7ed590e-16c8-402d-8db3-4f5342ba75bb)
Precise is default because it has the most accurate visuals, but using approximate works fine in 95% of games and runs faster.

**Comment by Virjoinga** [comment]
I do read them but I just heard that relaxed gives better performance so I used it because it didn't cause many issues in a majority of games I've played.

**Comment by Virjoinga** [comment]
Alright here is a video of the first level being beaten with no crashes.
https://youtu.be/jj-xAcfogBU

**Comment by Asinin3** [comment]
@Virjoinga If the game is running well and playable from start to finish, please read https://forums.rpcs3.net/thread-196671.html then create a forum account, and then post on this thread: https://forums.rpcs3.net/showthread.php?tid=187784&page=2 with your report (must include RPCS3 version, log file and 3 screenshots or a video of the game running).

Please only do a report once you have thoroughly tested the game. This will allow us to move it to the Playable status if it is running well. If it runs poorly you can just post about that on the thread. Thanks.

**Comment by Virjoinga** [comment]
Hmm okay I'll attempt to do a full play-through and record it tomorrow.

**Comment by Asinin3** [comment]
Don't need to record the entire thing. 10-20mins of mid-late game is fine.

**Comment by Virjoinga** [comment]
Done, any other talk will be on that thread.
