### ISSUE TITLE
OpenGL/WxWidgets: How to create a debug context ?

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1423]
I'd like to have ARB_DEBUG_OUTPUT enabled in OpenGL. It's an extension that makes the driver prints a message when an error is met which is much, much, much better than the traditionnal glError(); mechanism. It's pretty close to DX debug layer, except that the message are accessible outside of Visual Studio (and thus can be printed to RPCS3.log).

It requires an OpenGL Debug context to be created but unfortunatly wxWidgets doesn't seem to allow creation of such context. Is there any though on how to achieve that ? I know that the issue was discussed long times ago, possibly on wxWidget mailing list.

**Comment by DHrpcs3** [comment]
just call glEnable(GL_DEBUG_OUTPUT)

**Comment by vlj** [comment]
Core context and debug output implemented.
