### ISSUE TITLE
[Feature request] Force exiting of RSX threads that are too sleepy.

### ISSUE THREAD

**Issue by Faint0002** [RPCS3/rpcs3#14234]
### Quick summary

I should not have to task kill RPCS3 in the event of a fatal crash just because a rsx thread is too sleepy.

### Details

In the emulation tab, I would like a button to just kill all rsx threads past a certain threshold. See attached ss for why this is required.
https://vali.is-a-fed.lol/jtdQOvHoSMeg/rpcs3_78l7KB3WX7
I had to task kill via task manager, forcefully closing made the application inf. hang

**Comment by Megamouse** [comment]
Missing log file

**Comment by Faint0002** [comment]
It is a feature request, not a bug...
There is no need for a log file. This just occasionally happens for me, regardless of the game and I would like the ability to force exit regardless of the state of the threads.

**Comment by MSuih** [comment]
The correct solution is to figure out where and how the threads get stuck and then fix that so that everything cleans up nicely even on a fatal crash.

**Comment by Faint0002** [comment]
I just did it myself, as I attempted to have someone else reproduce and they couldn't so I guess this only happens to me. It is what it is. Should I close?

**Comment by Faint0002** [comment]
If someone else has the same issue, this can be re-opened
