### ISSUE TITLE
[Feature request] Ability to change RPCN account region

### ISSUE THREAD

**Issue by Splicewave** [RPCS3/rpcs3#14232]
### Quick summary

Ability to change RPCN Account region or make one in a region other than en-US
Such as from en-US to en-GB 

### Details

Some games have region specific content and some things do not exist or have different serial numbers in other regions. And its not just limited to games. Sometimes in-game item purchases are region specific and will not work on a region you did not buy them from. So having the ability to either change my RPCN account to en-GB region or make an RPCSN account in a different region would be a huge bonus. If you want to have en-US be the account region by default, thats fine but the option to change would for some games, be game changing.

**Comment by Splicewave** [comment]
Credit to JumpsuitAscended for finding this but here's a bit of the RPCS3 code of where regions are set. Hopefully this helps implent a region change feature
 https://github.com/RPCS3/rpcs3/blob/aee97e414fb78aedd396b04b296f5d54361220b4/rpcs3/Emu/Cell/Modules/sceNp.cpp#L3225

**Comment by Vaflat** [comment]
Is this solved? I'm interested in this too (since I play GT 6 and I want to show my country's flag).

**Comment by Splicewave** [comment]
> Is this solved? I'm interested in this too (since I play GT 6 and I want to show my country's flag).

I just tried it by going to a games custom configuration - system and changing the console language to English (UK) and console region to Europe but it did not do it. The game still served me the en-US tss file instead of the en-GB tss file
