### ISSUE TITLE
[BLAS50672]The game crashes when entering a stage

### ISSUE THREAD

**Issue by QJYEAH** [RPCS3/rpcs3#14244]
### Quick summary

The game crashes when entering a stage, always within the first few seconds. I can get through a few minutes of the tutorial before the same happens.

{RSX [0x02ce260]} VM: Access violation reading location 0xcf900000 (unmapped memory)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12136481/RPCS3.log)

### System configuration

CPU：R7 5800X
GPU：RTX 2080 8G
OS：Win10

**Comment by bader418** [comment]
Maybe it's a problem with mlaa

**Comment by Asinin3** [comment]
**Bad settings:**
SPU Loop Detection - Completely Unnecessary on your 8core CPU.
Vertex Cache Disabled - .. Why?
Write Color Buffers & Read Color Buffers - Why? Is it even needed for this game? Its lowering performance.


Github is for reporting issues that are useful to developers, random crashes with no specific error or steps to reproduce or anything like that aren't very helpful for us. This game is not listed as playable on our database either, so you should know to expect issues. If it was a specific bug that you could pin-point I would keep this open. But as it stands its not helpful so I have closed this ticket.

**Comment by bader418** [comment]
The default settings for the emulator are the same. I suspect there was an error in graphics rendering, mlaa? I don't know

**Comment by bader418** [comment]
This is an issue that has never been resolved, I'm attaching a link to feedback from the same game in 2020
https://github.com/RPCS3/rpcs3/issues/9055

**Comment by bader418** [comment]
and 
https://github.com/RPCS3/rpcs3/issues/13748
