### ISSUE TITLE
[BLJM60006] Sonic The Hedgehog - Doesn't create save data making it impossible to get past title screen

### ISSUE THREAD

**Issue by FlexBy420** [RPCS3/rpcs3#14245]
### Quick summary

After pressing start in title screen, game asks you to create save data, both yes and no results in going back to title screen.

https://github.com/RPCS3/rpcs3/assets/68403300/1b26894e-7bb8-483c-9311-588604cdab1e

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12137443/RPCS3.log.gz)

**Comment by Asinin3** [comment]
Have you tried making a folder for the savedata without actually putting anything in it? I have seen some games fail at making the folder, but can create the data once one exists.

**Comment by FlexBy420** [comment]
Same thing happens. I will try save data made by PS3.

**Comment by FlexBy420** [comment]
It does get past with PS3 made save. Leaving the save here for other users.
[BLJM60006-0000.zip](https://github.com/RPCS3/rpcs3/files/12137512/BLJM60006-0000.zip)

**Comment by TailsGuy** [comment]
I'll load it up on RPCS3 as well

**Comment by TailsGuy** [comment]
Ah, very strange thing, see, I loaded up the game, and I got to the title screen, 
I pressed start, it asked me to make a new save.
It looks like nothing's really wrong but then it just loops the title screen again.

**Comment by TailsGuy** [comment]
[SONIC THE HEDGEHOG [BLJM60006].log.gz](https://github.com/RPCS3/rpcs3/files/12141443/SONIC.THE.HEDGEHOG.BLJM60006.log.gz)

https://github.com/RPCS3/rpcs3/assets/70661792/1e41a9b2-b54e-4a23-9956-8b5cd822a7a0

**Comment by TailsGuy** [comment]
I used the save, and it got past the title screen, and like the over versions of 06, it's broken.
Though, I made a version of the "Graphics Fix" patch for the Japanese ver, it doesn't solve anything.

```
PPU-c1be5dc25994c9b4006295882516c829f8c63707:
  "Graphics Fix":
    Games:
      "SONIC THE HEDGEHOG":
        BLJM60006: [ 01.01 ]
    Author: "elad335"
    Notes: "Fixes missing graphics ingame."
    Patch Version: 1.0
    Patch:
    - [ calloc, 0x00f07714, 0x4 ]
    - [ be32, 0x00000000, 0x38800003 ] # li r4, 3
    - [ jumpf, 0x00000000, "RPCS3_HLE_LIBRARY:WaitForSPUsToEmptySNRs" ] # Args: (SPU ID, 3)
    - [ be32, 0x00000000, 0x38800000 ] # li r4, 0
    - [ be32, 0x00000000, 0x44000002 ] # sc
```

Damn shame. Now, all I really did was just change the PPU, and also change the region so IDK if there was any more I should've done, I'm not the author of the patch.

**Comment by FlexBy420** [comment]
Graphics fix patch in every region is broken anyway. I ported them myself to other regions but have 0 idea why they don't work. Maybe @elad335 will figure it out sooner or later

**Comment by TailsGuy** [comment]
> Graphics fix patch in every region is broken anyway. I ported them myself to other regions but have 0 idea why they don't work. Maybe @elad335 will figure it out sooner or later

If he's got access to Japanese 06 anyway. It's **very** hard to find on amazon, ebay, dubious means, hell it's not even digital.

**Comment by elad335** [comment]
Is that a regression?

**Comment by FlexBy420** [comment]
Game still doesn't create save data so issue should be re-open.
And the EU/JP canary patch still doesn't work.

**Comment by TailsGuy** [comment]
I'll try it out.

**Comment by TailsGuy** [comment]
[SONIC THE HEDGEHOG [BLJM60006].log.gz](https://github.com/RPCS3/rpcs3/files/12149127/SONIC.THE.HEDGEHOG.BLJM60006.log.gz)
Nope, no change.

https://github.com/RPCS3/rpcs3/assets/70661792/a35d7e32-efa2-476f-bcd1-9edca60bfec7
