### ISSUE TITLE
SOCOM: Confrontation bug graphics

### ISSUE THREAD

**Issue by Sapelain** [RPCS3/rpcs3#14242]
### Quick summary

The problem is because they do not load the textures well, which causes a fall of fps.
Setting up this game to work has its difficulty. So I will put what I have done.

1. Move the backup to RPCS3 v0.0.28 Alpha\dev_hdd0\disc\SCC [BCES00173] **(He says that if not the game is corrupt)**
2. Install RPCS3 v0.0.28 Alpha\PS3_GAME\PKGDIR\PKG00\INSTALL.PKG **(Because otherwise it gives error by not installing itself just like other games)**
3. Install Updates
4. Set up an online saw that works.

### Details

Texture load errors the important part that I don't see how to solve and some textures blink on the maps. And the fps go up and down, the graph is almost at rest like the cpu.
![1](https://github.com/RPCS3/rpcs3/assets/126752527/b108f2f1-35ce-4d72-bb3c-e8816c8b481f)

The normal:
![2](https://github.com/RPCS3/rpcs3/assets/126752527/e9f38828-a22c-4e5e-8873-2a277f4638ee)
)
And at times it looks perfect

### Attach a log file

https://mega.nz/file/ffwlkSQY#Hwu_fc7oJZPKGP9RwP3fwDvy1WdsUYkEcE8p_3_XcnE

### System configuration

I leave the settings:
![cpu](https://github.com/RPCS3/rpcs3/assets/126752527/ea23204a-28a4-4254-bdfa-57d3852c5e50)
![gpu](https://github.com/RPCS3/rpcs3/assets/126752527/d3c83490-985d-46d7-a7d9-f71c4523b3d8)
![advan](https://github.com/RPCS3/rpcs3/assets/126752527/11feda0f-d5fd-48c2-8d58-2de141ef9146)

**Comment by Asinin3** [comment]
**The settings in your screenshots are not the ones you are using, you need to right-click the game and click "change custom config"**

**Your settings are BAD**
Don't disable Vertex cache - it can cause issues.
Don't use Relaxed Xfloat - it causes issues in 99% of games
Don't use write color buffers (it shouldn't be needed for this game)
Don't use strict rendering mode (it shouldn't be needed for this game)

Re-test with proper settings/defaults. If issue persists:

Re-word the OP Post to it makes sense, currently it makes no sense at all.
`Move the backup to RPCS3 v0.0.28 Alpha\dev_hdd0\disc\SCC [BCES00173] (He says that if not the game is corrupt)` What backup? You mean the game? Why even list that? Who is "He"? 
Attach a capture renderdoc/rsx capture.

I'm closing this issue, if you follow above steps properly and edit the OP then we can re-open.

**Comment by Sapelain** [comment]
If the game is not set there is data corruption:
Install RPCS3 v0.0.28 Alpha\PS3_GAME\PKGDIR\PKG00\INSTALL.PKG (Because otherwise it gives error by not installing itself just like other games)
![install](https://github.com/RPCS3/rpcs3/assets/126752527/144609f6-6827-4759-ab10-2b39cfcaca6e)


A fixed image is generated.That does not advance there. Now I don't get the corrupt data error.

![error](https://github.com/RPCS3/rpcs3/assets/126752527/cff1d71a-8da9-487b-b32d-7cb38707677e)

Because you need to install that file. Because you need to install that file and then updates


When I was talking about backup it was this

![1](https://github.com/RPCS3/rpcs3/assets/126752527/d67ef076-0869-43a7-9cdb-3894c4c2b931)

With this configuration I see the clearest game and shader loading is faster

![CPU](https://github.com/RPCS3/rpcs3/assets/126752527/add696b5-abcf-436a-9c6d-91c9ac63d81d)
![GPU](https://github.com/RPCS3/rpcs3/assets/126752527/9e574752-6eda-451a-8d2f-d6996a7bf665)
![adv](https://github.com/RPCS3/rpcs3/assets/126752527/49597cf2-7814-4cac-aba6-96430e31779f)

But now pink colors come out in the textures

![Ahora 2](https://github.com/RPCS3/rpcs3/assets/126752527/2ffe3af9-8727-4eef-b1d9-c1af6db05301)

**Comment by Sapelain** [comment]
Thank you very much for the help. 
That with the event there are people who have considered it impossible to play. Since RPCS3 Wiki says nothing about the configuration.

**Comment by Asinin3** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/15137035/c78ab867-46f4-4235-9155-a8147be7f622)
Use "Approximate Xfloat". Either way, sounds like the only issue you are having now is the pink colors on textures. Might be able to fix that with "Write Color Buffers" or some other setting like "Read Color Buffers" "Write Depth Buffers" or something... Anyway if you want to raise a sepate issue for the pink color bug make sure you test the right settings and then open new issue with renderdoc file or RSX Capture. If your not sure how then just leave it for someone else.

**Comment by Sapelain** [comment]
The game works perfectly already, two hours in a row and some error but little. 
So I leave the configuration that works already:
![1](https://github.com/RPCS3/rpcs3/assets/126752527/9c4832fd-63b3-4867-9a3e-3ac4ff470151)
![2](https://github.com/RPCS3/rpcs3/assets/126752527/e9b3b310-131c-43e9-aa83-295599d3531c)
![3](https://github.com/RPCS3/rpcs3/assets/126752527/543d2015-e025-4143-918b-c7b320567843)

Por lo visto en el juego todos los problemas vienen por shaders hay es donde hay que mejorar.
Thank you very much for the help.
