### ISSUE TITLE
[BLAS50130]After you finished 3 stages，when someone say something，the game will stutter（FPSdrop and graphic stutter）

### ISSUE THREAD

**Issue by QJYEAH** [RPCS3/rpcs3#14257]
### Quick summary

After i finished 3 stages，when someone say something，the game will stutter（FPS drop and graphic stutter）.Even i re-run the game，the problem is still there.But if i update RPCS3 or use the same vision to cover RPCS3，the problem wii disappear.But if i play 3 stages again，the problem wii appear.

### Details

the same problem game：
Shin Sangokumusou 5（BLAS50068）
Shin Sangokumusou 5 Empires（BLAS50115）

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12141977/RPCS3.log)

### Attach capture files for visual issues

the video：https://www.youtube.com/watch?v=Ttp_v0nBwWI

### System configuration

CPU：R7 5800X
GPU：RTX 2080 8G
OS：Win10

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed

**Comment by QJYEAH** [comment]
> 不允许出现应用补丁的问题

but the same problem on Shin Sangokumusou 5（BLAS50068）and Shin Sangokumusou 5 Empires（BLAS50115）,these 2 games with no patches can be played,i think maybe koei use something on audio,but rpcs3 can not run it perfectly.
