### ISSUE TITLE
Vulkan : Jet Set Radio alpha texture issue

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#1426]
Last working for me https://github.com/RPCS3/rpcs3/pull/1395
I'm sure that problem started here somewhere https://github.com/RPCS3/rpcs3/pull/1402

![jet set broken](https://cloud.githubusercontent.com/assets/11453507/12264486/702e6268-b937-11e5-8e69-624bbe73baa7.PNG)

![jet set broken 2](https://cloud.githubusercontent.com/assets/11453507/12264489/75423144-b937-11e5-9b88-7836eeb440ae.PNG)

[LOG](https://mega.nz/#!XMEnlZrZ!MkphqKtvB2FgvH49par1OVjarNyITPYPLAB5xo9VCLk)

**Comment by Xcedf** [comment]
Confirm

**Comment by vlj** [comment]
Rather texture issue that alpha issue, they're all white.

**Comment by JohnGodgames** [comment]
True...updated thx @vlj

**Comment by tambry** [comment]
@JohnGodgames Still an issue?

**Comment by JohnGodgames** [comment]
@tambry yeah still

**Comment by raven02** [comment]
@JohnGodgames , did the texture issue fix in latest build ?

**Comment by MarioSonic2987** [comment]
Is it still a issue?

**Comment by Zangetsu38** [comment]
actually, this game show black screen

**Comment by JohnGodgames** [comment]
I'm confirming that all is black now on OGL/VULKAN

**Comment by raven02** [comment]
Thanks for testing it .Does it mean DX12 good then?

**Comment by Zangetsu38** [comment]
no, same problem

**Comment by digitaldude555** [comment]
![screenshot 851](https://cloud.githubusercontent.com/assets/26138653/23555025/fa22999a-002f-11e7-9f2b-35d3718ad196.png)
![screenshot 856](https://cloud.githubusercontent.com/assets/26138653/23555027/fcfa649a-002f-11e7-9423-e255040cfdfd.png)

With write color it seems improved a lot in openGL but it looks kinda dark though doesn't it. Vulkan is black screen no matter what. 

DX12
![screenshot 857](https://cloud.githubusercontent.com/assets/26138653/23555154/7b94234a-0030-11e7-9185-1e9be8d4c62b.png)

**Comment by digitaldude555** [comment]
![screenshot 1488](https://cloud.githubusercontent.com/assets/26138653/24837967/1e28c9ec-1d48-11e7-9a83-7f14117b762e.png)

Opengl doesn't have issue anymore, vulkan still black screen.

**Comment by kd-11** [comment]
This issue was fixed. Only write buffers support for DX12 is missing, but thats a different issue.
