### ISSUE TITLE
Naruto Shippuden: Ultimate Ninja Storm 2 [NPJB90253]-[Graphic glitches]

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1427]
Rpcs3.D3D12.11-01-16 -  https://github.com/Zangetsu38/rpcs3/releases

*Movie : https://www.youtube.com/watch?v=BhBdQC2RQGA

*Log : https://gist.github.com/SakataGintokiYT/807b4b5765c83cbcba4c

*Image :
<img src="http://www.fotoszok.pl/upload/306b9a7f.jpg" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">

LLE:
cellFiber_Library v1.1
cellPngDec_Library v1.1
cellSpursJq_Library v1.1
cellSre_Library v1.1
cellSsl_Library v1.1
cellSail_Library v1.1
 
Settings:
PPU - Interpreter 2
SPU - Interpreter ASMJIT
DX12 
1280x720 
VSync
XAudio

**Comment by tambry** [comment]
@SakataGintokiYT Please try with a more official release from [here](https://github.com/Bigpet/rpcs3/releases).

**Comment by SakataGintokiYT** [comment]
v0.0.0.6-362-g9d1208b: Merge pull request #1394 from vlj/build
Cell\PPUInterpreter.cpp:1699, in function ppu_interpreter::TW)

**Comment by tambry** [comment]
@SakataGintokiYT Could you also compile master and test with that?
Zangetsu's builds are full on nasty and completely wrong hacks.
If it fails with a trap instruction, then something has gone very wrong, and indicates that the game must abort processing immediately.

**Comment by SakataGintokiYT** [comment]
I'm not a programmer  : )

**Comment by tambry** [comment]
@SakataGintokiYT See the edit.

**Comment by SakataGintokiYT** [comment]
*rpcs3-ReleaseLLVM-5029dff7
*rpcs3-ReleaseLLVM-bed28bfe

{PPU Thread[0x1] (main_thread)[0x00480a4c]} Exception: 
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:1699, in function ppu_interpreter::TW)
Please report this to the developers.

**Comment by tambry** [comment]
@SakataGintokiYT
We don't intend on supporting builds with numerous hacks, that got the game into a state, where it shouldn't be. There's a reason why a trap instruction does exactly what it would on a real PS3.
