### ISSUE TITLE
DX12: Hyperdimension Neptunia (BLUS30701) crash regression

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1429]
Crashes, when choose new game, and it opens window with settings. Probably caused by changes in PR #1419

See:
http://www.emunewz.net/forum/showthread.php?tid=165037&pid=229076#pid229076

**Comment by vlj** [comment]
Did you test with private 1419 only?

**Comment by vlj** [comment]
If several texture shares the same base 4096 address one will overwrite the other even if it's used later in the pipeline, likely causing the heap corruption.

**Comment by tambry** [comment]
@vlj What do you exactly mean by private 1419?

**Comment by vlj** [comment]
with PR*

**Comment by B1ackDaemon** [comment]
@vlj, i tried to undo 1419 changes in latest master build, and crash in menu gone.

**Comment by raven02** [comment]
@B1ackDaemon , i think it didn't happen in latest build now ?

**Comment by digitaldude555** [comment]
![screenshot 837](https://cloud.githubusercontent.com/assets/26138653/23526486/e3c26026-ff9a-11e6-9289-1e77efad365c.png)

It doesn't crash on DX12 anymore when starting new game.

**Comment by raven02** [comment]
Thanks then we close it.
