### ISSUE TITLE
DX12: Regression in some games after PR #1415 changes

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1430]
Affected games - Bayonetta (BLES00599) and Hyperdimension Neptunia (BLUS30701). Before PR #1415 changes there was appears assertion failures (line 108 in D3D12Texture.cpp, and line 103 in D3D12MemoryHelpers.h), but it was possible to skip them and get further. Now renderer window just silently hangs without any messages, and both games got regressions. In Bayonetta it's no longer possible to get into menu (and ingame using save from PS3), Hyperdimension Neptunia hangs in the middle of dialog scene.

**Comment by raven02** [comment]
@B1ackDaemon , is it okay now?

**Comment by raven02** [comment]
It is different issue now .Will close it and open a new issue.
