### ISSUE TITLE
VS 2015 build broken

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1432]
Since commits 38531459df73a3f6ea57d43815d6f496991b50e0 and b3e3c68f15335cda4a7e4173abaf9c3df396c37e it's not possible to build using VS2015.

There's 2 errors :
"rpcs3.rc(4): fatal error RC1015: cannot open include file 'wx/msw/wx.rc'."
and if I remove the include :
"LINK : fatal error LNK1104: cannot open file 'asmjit.lib'"

**Comment by Nekotekina** [comment]
Sorry, will fix tomorrow.

**Comment by Nekotekina** [comment]
Should be fixed now.

**Comment by tambry** [comment]
@vlj Is it fixed?
