### ISSUE TITLE
Unknown/illegal channel (ch=1 [$SPU_WrEventMask], value=0x2) motorstorm apocalyse DX12

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#1434]
When finished loading is interrupted by stopping the emulation

Note: compilation used
rpcs3.D3D12.11-01-16 Zangetsu38

![error 1 motorstorm apocalyse](https://cloud.githubusercontent.com/assets/16367065/12311521/8cb491fc-ba25-11e5-95d6-f258449eb8ab.png)

log:
https://mega.nz/#!WRIjVagZ!8hWk3T7BbL27nfQm45y2fT574owq-ELpWPDvZ_OB-Ts

Modules LLE
cellSpursJq_Library v1.1
cellSre_Library v1.1

**Comment by tambry** [comment]
Oh, you used Zangetsu's "build". I guess #1479 will be the main one for this issue then.
