### ISSUE TITLE
Unable to download Compatibility Database

### ISSUE THREAD

**Issue by evanpaul14** [RPCS3/rpcs3#14376]
### Quick summary

Downloading the compatibility database on MacOS does not work.

### Details

![Screenshot 2023-07-26 at 12 19 59 PM](https://github.com/RPCS3/rpcs3/assets/120766197/7da1bbac-099e-4403-a232-c42edde5a810)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12176513/RPCS3.log)

### System configuration

M1 Mac Mini

**Comment by mavethee** [comment]
This shouldn't be an issue anymore 🤔 
![CleanShot 2024-09-01 at 09 48 21@2x](https://github.com/user-attachments/assets/2bf99949-05e4-44d1-b151-c7243a6a857f)
At least works on my end 🤷🏻
