### ISSUE TITLE
Weird video glitch when playing Persona 5 (BLUS31604)

### ISSUE THREAD

**Issue by fiestajr** [RPCS3/rpcs3#14373]
### Quick summary

Odd glitches during cutscenes/main menu/in-game
### Details

There's this really weird model/visual bug when I play Persona 5. The cutscenes have these weird tiny squares flickering everywhere. and some of the models in the main menu and in-game are bugged out man

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12174796/RPCS3.log.gz)

### Attach capture files for visual issues

https://www.dropbox.com/scl/fo/m7wva4oc4295x8fhk3ewa/h?rlkey=sacnaitglb8wwxc1j15htoihi&dl=0

### System configuration

CPU: Intel Core i7-11700k
GPU: RTX 3080 Ti
GPU Driver Version: 31.0.15.3667

**Comment by MSuih** [comment]
We don't accept issues from ancient RPCS3 versions, you need to update to latest version on rpcs3.net first. Also, according to your log you have some weird settings enabled, you should ask our Discord's help section to get those sorted out too,

**Comment by fiestajr** [comment]
alright
