### ISSUE TITLE
Sega Rally Online Arcade freezing at Loading screen on first boot

### ISSUE THREAD

**Issue by GaussTek** [RPCS3/rpcs3#14375]
### Quick summary

The game (NPUB30375) freezes at the Loading screen on the first boot, only way to progress further is to close the game and restart. 

However, if you close rpcs3 completely, you need to repeat the above steps again: load, wait to freeze, and restart. Sometimes it just freezes before the SEGA logo even shows up, and you need to repeat the same steps.

This is the only game showing this strange behavior. Using all the default settings for the emulator.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12176236/RPCS3.log.gz)

### Attach capture files for visual issues

![NPUB30375_screenshot_2023_07_26_12_31_22](https://github.com/RPCS3/rpcs3/assets/43524067/d453beea-380c-4ac4-a0bf-fc340cd7bcb9)

### System configuration

CPU: AMD Ryzen 4600H
GPU: NVIDIA GTX 1650
SO: Windows 11
Driver: Nvidia v536.67

**Comment by Asinin3** [comment]
Ani has this issue and I tested it a week ago but couldn't reproduce, this is a weird one.

**Comment by tij77** [comment]
I can confirm this was happening before.

Now on latest build 0.0.29-15470, its always get stuck on "loading..." screen. Restarting the game does not help anymore - it still stuck on "loading..."

I tested older builds here are my findings (retested with default settings)

0.0.22-13780-cb2c0733 - working with restart
0.0.28-15417-9b3a878c - working with restart
0.0.29-15421-70e127b2 - working with restart
0.0.29-15422-bb2d7063 - working  with restart (seems like latest version were it still work)

0.0.29-15427-39a0ff99 - hangs on compiling or load
0.0.29-15429-804665df - hangs on compiling or load
0.0.29-15431-9f625de5 - hangs on compiling or load
0.0.29-15440-aee97e41 - hangs on compiling or load
0.0.29-15468-58e9e54b - hangs on compiling or load

"working with restart" - to reproduce it, Sega Rally Online Arcade must be the first game to start after RPCS3 starts. If thats the case, game hangs on "loading..." screen. Stopping the game and restarting it, runs game correctly. If after RPCS3 start, some other game was run first, then Sega Rally Online Arcade will start without problem. Very weird.

please see following thread for more details: https://forums.rpcs3.net/showthread.php?tid=206465

System configuration
CPU: 12900K with AVX512 enable
GPU: 2080ti
OS: Windows 11 22H2 build 22621.2070
NVidia Driver: 536.67

Log file for  0.0.29-15470: 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12318029/RPCS3.zip)

**Comment by GaussTek** [comment]
I can confirm that on lastest version, the restart method doesn't work, and the game gets stuck on the loading screen no matter what. 

Rolling back to the previous versions mentioned above and the restart method works, gets stuck and works again on a restart.

Can someone check this out? The game is currently broken as it is :(

**Comment by tij77** [comment]
Just tested 0.0.29-15472 same issue.

Also, it seems to affect God of War Origins Collection (BCUS98289). The game get stuck on black screen after selecting any of the game. The reason i think they might be related is cause 0.0.29-15422 does not have this issue.

Log for God of War Origins Collection getting stuck on 0.0.29-15472 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12322711/RPCS3.zip)

Might be similar problem to https://github.com/RPCS3/rpcs3/issues/12118

**Comment by GaussTek** [comment]
I made two little videos showcasing the issue.

The first is the behavior from latest build 0.0.29-15472 (ALWAYS happening, stuck in this screen), and on previous builds mentioned above after a first boot.

https://github.com/RPCS3/rpcs3/assets/43524067/fadd03eb-912b-4613-b7d0-07dbe170d485

The second one is from previous builds (0.0.29-15422 and before, as mentioned in previous posts), AFTER a restart (not closing the emu). As you can see the title screen shows up very quickly:

https://github.com/RPCS3/rpcs3/assets/43524067/99b5b9da-9ea3-408b-b984-812bb46b5d67

**Comment by tij77** [comment]
0.0.29-15473 and 0.0.29-15474 same behavior.

But starting from 0.0.29-15473, God of War Origins Collection (BCUS98289) is working. Guess the problem was unrelated.

Strangely, I just noticed that Metal Gear 4 get stuck on autosave notification at beginning. Strangely last working version is 0.0.29-15422 too. Not sure if its the same problem as Sega Rally Online ...

**Comment by GaussTek** [comment]
Latest version, same issue, game is broken at the moment. Any idea on what could be the cause of this? It's the only game showing this behavior for me.

**Comment by Special-Niewbie** [comment]
Here I wrote the solution:  https://github.com/RPCS3/rpcs3/issues/14663 .

**Comment by tij77** [comment]
Just tested on  0.0.30-16090 ... can confirm - no more stucking at loading screen

**Comment by GaussTek** [comment]
Sadly, not working yet for me with latest version and a clean install, not even PPU decoder to "Interpreter (static)" works

**Comment by tij77** [comment]
For me (Intel CPU) it works with Recompiler (LLVM) ... its much faster than my previous work around with "Interpreter (static)"

**Comment by Benji7010** [comment]
This issue is still present on my system, but only with the recompiler. It also happens to be facing the first launch hanging issue.
