### ISSUE TITLE
Various visual bugs in LittleBigPlanet 2 (BCUS98245)

### ISSUE THREAD

**Issue by WorldDstroyer** [RPCS3/rpcs3#14377]
### Quick summary

As of the past several builds (including the current build in the log), smoke particles cause visual artifacts, and the "Color Correction" global lighting setting does not function.

### Details

When there is a presence of smoke particles in a level, either in Create Mode or in Play Mode, particularly ones that originate from smoke emitters, they cause visual artifacts to appear on-screen. These artifacts appear as black-looking static. The other visual bug occurs when you change the "Color Correction" global lighting setting, which, doing so simply does nothing. The intended function is to, normally, allow the user to cycle through a range of post-processing effects. I've linked some recorded footage of the above-mentioned information.

[https://youtu.be/hV2wpS-mXNA](url)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12178994/RPCS3.log.gz)

### Attach capture files for visual issues

[BCUS98245_20230726231608_capture.zip](https://github.com/RPCS3/rpcs3/files/12178990/BCUS98245_20230726231608_capture.zip)

### System configuration

OS: Windows 10 Pro, Build 19045.3208, 22H2
CPU: AMD Ryzen 7 2700X
GPU: NVIDIA RTX 3070
GPU Driver: 536.67
RAM: 32 GB

### Other details

I have ReShade installed, however, these artifacts are newer than my install of ReShade, and the same circumstances were previously unable to produce these results.

**Comment by WorldDstroyer** [comment]
I wanted to add an addendum to this report, as I have since discovered an additional bug that is replicable under the same aforementioned conditions. The "foggyness" setting of light objects does not work as of the current build, as well as the build used to create this report.

RPCS3 Version: 0.0.29-15422-bb2d7063 Alpha | master

In-game footage of said issue:
https://youtu.be/HsCGXp9A2qI

**Comment by WorldDstroyer** [comment]
This can be solved by not enabling any of the three "Disable MLAA" patches in the "All" section of the patch manager. This appears to fix volumetric lighting, color correction, and probably more.

**Comment by slice-the-idiot** [comment]
doesn't solve the problem for me
