### ISSUE TITLE
FP : depth replace mode and half float register

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1438]
My testing on Naturo Shippuden Ultimate Ninja Storm 2 reveals that the depth output register doesn't follow the "output_from_h0" flag for color register.

The fragment shader #6 has indeed the "output from h0" and "depth replace" flag but looking at the shader it's obvious that depth doesn't come from h2.z, or any other channel of h2 since h2 is only storing a texture sample operation with a "classic" texture as parameters.

r1.z is written several time however and at some point it can hold value of a texture sample operation but with a texture that hold depth data. And if I force shader to use r1.z instead of h2.z the rendering in Naruto is indeed correct.

I don't know what to think here. r1.z and h2.zw overlaps but I don't think writting a float will automagically generate 2 meaninful half float (exponent size doesn't match). 2 other possibilities come to my mind : either there is another separate flag saying "output from h1" which is independent from "output from h0" one, or the shader will select register source according to depth buffer format, ie h2.z if currently bound buffer is Z16 and r1.z if Z24S8.

Was there some reverse engineering on a real PS3 done on the subject ?

**Comment by tambry** [comment]
Has this been resolved?

**Comment by raven02** [comment]
@kd-11 , do you know if we handle this already ?

**Comment by kd-11** [comment]
No, this requires deeper investigation into RSX behaviour. There's a workaround of sorts for this, but the register aliasing (if it exists at all) is not at all addressed.

**Comment by kd-11** [comment]
Haven't encountered a single title that does depth replace and sources from a half register so closing. Depth write seems to always be from r1.z
