### ISSUE TITLE
Legend of Kay Anniversary - Access violation reading (unmapped memory)

### ISSUE THREAD

**Issue by jy95** [RPCS3/rpcs3#14385]
### Quick summary

Game crashes after cutscenes of a chapter are finished

### Details

I noticed it happens more frequently after a boss fight

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12206791/RPCS3.log)

**Comment by Asinin3** [comment]
These errors aren't indicitive of what the actual issue is. Without a way to reproduce the error these kinds of issue reports aren't very useful.

**Comment by jy95** [comment]
@Asinin3 Like I said, it seems to happen after boss fight. 
For whatever reason, it happen a way more after the "The Dreaded Chei Ni" boss fight from my experience
