### ISSUE TITLE
Uncharted 3 Freezes On Certain Multiplayer Maps When Using "Disable In Built MLAA" 

### ISSUE THREAD

**Issue by familyguy14374** [RPCS3/rpcs3#14389]
### Quick summary

The game freezes on those specific multiplayer maps when enabling the "Disable In Built MLAA" patch:
Borneo (Coop Adventure Map), Museum, Facility and Molten Ruins.

When i disable the "Disable In Built MLAA" patch and enable "Read Color Buffers" Option in Advanced Tab it does not crash/freeze.

Tested on builds 14404 and latest master build 15409 with rpcs3 wiki settings.
Here is a video that describes the problem:

[Video - dropbox](https://www.dropbox.com/scl/fi/fv8q5tbe66muj5aa3cwdz/Unchrted-3-freezing-video.mp4?rlkey=715wdrvcud8jc2wsv0816mpzd&dl=0)

### Details

Those specific maps will freeze/crash no matter the game mode (deathmatch/coop) when using "Disable In Built MLAA" patch.
as said above, when the patch is disabled and "read color buffers" is enabled everything works and does not freeze but there is a big impact on performance due to that.
Tested it with few other friends who encountered the same exact problem.

 

### Attach a log file

[Log 15409 - dropbox](https://www.dropbox.com/scl/fi/uo3ww9n78z6jiqy07zkci/RPCS3.log?rlkey=uxor3d2ggsyxybmwvwbwicctt&dl=0)

### System configuration

PC SPECS:
- SYS: RPCS3 v0.0.28-15409-fd6829f7 Alpha | master
- SYS: 12th Gen Intel(R) Core(TM) i7-12700K | 16 Threads | 31.80 GiB RAM | TSC: 3.610GHz | AVX-512+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-07-30T08:54:18
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 3080' running on driver 536.67.0.0
- RSX: Found Vulkan-compatible GPU: 'Intel(R) UHD Graphics 770' running on driver 0.405.242
- SYS: Firmware version: 4.90

### Other details

When playing at 30 fps for example it will freeze after a longer period of time.
when using the debug function and flying to a diferrent spot the game will not crash even with the disable mlaa patch enabled from my testing.

**Comment by Asinin3** [comment]
Patches are hacks, they change how a game runs. Don't raise github issues for them. If you want to add a note about it to wiki feel free to though.
