### ISSUE TITLE
[Regression] Skate 3 freezing seemingly at random (#12598)

### ISSUE THREAD

**Issue by Totally-Not-a-Skeleton** [RPCS3/rpcs3#14392]
### Quick summary

Skate 3 will freeze at random. Audio keeps playing, video freezes.

### Details

After a variable amount of time (usually between 5 to 20 minutes) Skate 3 will lock up. The audio will continue in the background, however the video will be frozen and inputs no longer work. There doesn't seem to be any errors being logged either. I've tried every fix I could find for these kinds of issues online to no success.
The random nature of the freeze and lack of errors makes it hard for me to know for certain which build caused the regression (since I could simply get lucky and not get a freeze on a certain build). I *think* I've pinpointed it down to #12598.

### Build with regression

v0.0.28-15404

### Attach two log files

v0.0.28-15404 - Log with regression (played until it froze and then exited the emulator): [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12209948/RPCS3.log.gz)
v0.0.28-15401 - Log without regression (didn't freeze, so played for a around 15 minutes and then exited the emulator): 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12209991/RPCS3.zip)

### System configuration

OS: Windows 10
CPU: AMD Ryzen 5 3600
RAM: 48GB
GPU: NVIDIA GeForce RTX 3060
GPU Driver Version: 531.14

### Other details

I have also experienced similar freezes with Skate 2, however I haven't done any testing with it yet.

**Comment by Jeliman359** [comment]
for me that happenes on the newest version of RPCS3, but reverting to a 20 day old version seems to fix it for the meantime
for anyone whos gonna be checking this here are my specs:
OS: Windows 10
CPU: i7-12700KF
RAM: 32GB
GPU: GeForce RTX 3060 16GB
GPU Driver Version: 536.67

**Comment by elad335** [comment]
Retest on master.

**Comment by Totally-Not-a-Skeleton** [comment]
Tested for about 20 minutes on the latest release and didn't see any crashes. If any pop up in the future I'll go ahead reopen this.
