### ISSUE TITLE
[Feature request] Microsoft Xbox Elite Wireless Controller Series 2 support

### ISSUE THREAD

**Issue by davidhedlund** [RPCS3/rpcs3#14406]
### Quick summary

Underside of Microsoft Bluetooth Elite Series 2 Controller, with paddles installed:
![image](https://github.com/libretro/retroarch-joypad-autoconfig/assets/6416073/11e34a36-56f7-4ed6-a5f0-385b802bf9b5)

To avoid confusion: Microsoft Bluetooth Elite Series 2 Core is the gamepad without the paddles installed. This feature request includes paddle buttons support in retroarch as well.

### Details

Requires upstream support for Linux: https://github.com/libsdl-org/SDL/issues/7211

**Comment by davidhedlund** [comment]
Requires upstream support for Linux: https://github.com/libsdl-org/SDL/issues/7211

**Comment by DrLegitamate** [comment]
Does the controller output the paddles as extra inputs? i thought they only replicate existing inputs on the controller? (Which you would configure in the controller software)

**Comment by Megamouse** [comment]
This is supposed to be fixed in our SDL version.
