### ISSUE TITLE
[macOS] Regression: Mac builds crash on launch since #14414

### ISSUE THREAD

**Issue by shinra-electric** [RPCS3/rpcs3#14419]
### Quick summary

macOS builds will crash on launch since #14414

### Details

I didn't want to report this initially since I'm on the Sonoma Beta, but looking at discord there are several other users on Ventura reporting the same issue. 

I don't think it was actually #14414 that changed anything, I suspect it was a 3rdParty update, probably FAudio. (FAudio did update two days ago, but I don't see anything in the update that would affect this). 

Edit 2: I see that SDL and FAudio were updated in #14400. This might be the cause.

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @loader_path/../../../../opt/sdl2/lib/libSDL2-2.0.0.dylib
Referenced from: <9A7F704F-BC3B-3406-B9A4-DB720D0B7141> /Users/USER/Downloads/RPCS3.app/Contents/Frameworks/libFAudio.0.dylib
Reason: tried: '/Users/user/Downloads/RPCS3.app/Contents/Frameworks/../../../../opt/sdl2/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/local/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.0.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)
```

From the report it looks like the FAudio.dylib is looking for the SDL2 dylib in the wrong place. It should be looking in `@loader_path/../Frameworks/libSDL2-2.0.0.dylib`

Edit: Just to confirm, the SDL2 library is present in the Frameworks directory. 

### Build with regression

0.0.29-15427

### Attach two log files

[System crash log.txt](https://github.com/RPCS3/rpcs3/files/12254760/System.crash.log.txt)

### System configuration

M1 Pro
16GB Ram
Sonoma Beta 4

**Comment by oaktowner** [comment]
I'm just grabbing the latest disk image from cirrus-ci (rpcs3-v0.0.29-15536-08d9cbfe_macos.dmg) and still getting this error. It  _seems_ as if this should have made it into a build by then (merged 3 weeks ago, and it looks like CI makes a build with every merge)...so I'm not sure if it's something new.

Are there any known workarounds in the meantime?

**Comment by AniLeo** [comment]
That's not the build with the fix. It still didn't build.

**Comment by AniLeo** [comment]
Is it still the same error? What macOS version and CPU?

**Comment by oaktowner** [comment]
Hi, thanks for the response. 
M2, Ventura 13.5.1
Error: 
```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @loader_path/../../../../opt/libvpx/lib/libvpx.8.dylib
Referenced from: <0E60638F-B9DA-3CB7-ABCC-E8B0B55FCD0D> /Applications/[RPCS3.app/Contents/Frameworks/libavcodec.60.dylib](http://rpcs3.app/Contents/Frameworks/libavcodec.60.dylib)
Reason: tried: '/Applications/[RPCS3.app/Contents/Frameworks/../../../../opt/libvpx/lib/libvpx.8.dylib](http://rpcs3.app/opt/libvpx/lib/libvpx.8.dylib)' (no such file), '/usr/local/lib/libvpx.8.dylib' (no such file), '/usr/lib/libvpx.8.dylib' (no such file, not in dyld cache)
Library not loaded: @loader_path/../../../../opt/libbluray/lib/libbluray.2.dylib`
```

**Comment by shinra-electric** [comment]
It’s not exactly the same error, but it’s likely related. 
a new issue was opened in #14532.

**Comment by shinra-electric** [comment]
To clarify, we just avoided this specific issue by turning off FAudio. 

But the underlying problem of improper rpaths and/or linking issues is still there, and has started affecting other dylibs.
