### ISSUE TITLE
Build fails on Linux because the struct futex_waitv in Utilites/sync.h is redefined in linux/futex.h

### ISSUE THREAD

**Issue by yann-boyer** [RPCS3/rpcs3#14417]
### Quick summary

If you try to build RPCS3 on Linux you'll be prompted by an error, a redefined struct.

### Details

The redefined struct is futex_waitv in the Utilities/sync.h file, it's already defined in linux/futex.h but it's redefined in the file, if you comment this struct in the sync.h file RPCS3 compiles and links correctly, and even works fine(tested) !

### Attach a log file

Log file cannot be provied because the issue is on the build process not the emulator itself.

**Comment by kd-11** [comment]
Odd, I develop and use rpcs3 mainly on linux and it compiles just fine on my end.

**Comment by kd-11** [comment]
Oh, I just noticed https://github.com/RPCS3/rpcs3/pull/14403 got merged. Probably why.
