### ISSUE TITLE
Fatal error: Verification failed in Ni No Kuni: Wrath of the White Witch

### ISSUE THREAD

**Issue by JL2210** [RPCS3/rpcs3#14415]
### Quick summary

After several hours of gameplay, the emulator appears to freeze.
This has happened to me a few times but this is the first I've gotten a proper log and screenshot of the issue. It always seems to happen after a few hours of playtime. Past that I can't seem to find a consistent way to reproduce the issue.

### Details

Error in log:
```
F {RSX [0x0bc85e4]} SIG: Thread terminated due to fatal error: Verification failed (in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\expected.hpp:80[:13], in function texture_magnify_filter) (error=0xcb)
```

Screenshot of error after closing emulator window:
![Screenshot 2023-08-03 011352](https://github.com/RPCS3/rpcs3/assets/38843657/279dc114-065f-4338-8c13-e544f90e6b39)

### Attach a log file

I have no idea why it's almost a gigabyte in size. Sorry, even compressed it's still huge.

https://drive.google.com/file/d/13r6YiGEKBWXTtlOBDJ_0piVyR-gK5PRP/view?usp=sharing

### System configuration

OS Microsoft Windows 11 Pro Build 22621

Processor Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz, 2901 Mhz, 6 Core(s), 6 Logical Processor(s)

GPU NVIDIA GeForce GTX 1650

GPU drivers: 536.67

### Other details

Might have something to do with my config?
[config_NPUB30932.txt](https://github.com/RPCS3/rpcs3/files/12247161/config_NPUB30932.txt)

**Comment by kd-11** [comment]
Set RSX FIFO accuracy to "atomic" in the advanced tab.

**Comment by JL2210** [comment]
> Set RSX FIFO accuracy to "atomic" in the advanced tab.

Thanks. After making this change, I haven't crashed again. Not sure if it's just a coincidence or if it fixed the issue.

Maybe this config should be put in the wiki?

**Comment by Asinin3** [comment]
Yes just make a wiki account, edit the page and we will approve it.
