### ISSUE TITLE
ratchet and clank tools of destruction: futex_waitv: bad param

### ISSUE THREAD

**Issue by A-w-x** [RPCS3/rpcs3#14425]
### Quick summary

game random crash with the message futex_waitv: bad param

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12262572/RPCS3.zip)

### System configuration

ryzen 6800u
32gb ram
archlinux
mesa git
latest appimage

**Comment by Nekotekina** [comment]
@A-w-x Please test the PR linked

**Comment by MastaG** [comment]
Is it hard to trigger this?
I'd like to try and reproduce it on Fedora.

**Comment by A-w-x** [comment]
just play, happened after 1hr last time
