### ISSUE TITLE
[Regression] Games fails to boot on Linux

### ISSUE THREAD

**Issue by pumpkinhi11** [RPCS3/rpcs3#14422]
### Quick summary

Self explanatory, emulator launches fine however when trying to launch a game the log reads "S GUI: Boot successful." and just stops.

Noticed issue from about 2 days ago #14409 however with the key difference that I singled the regression to rpcs3-v0.0.29-15426, with 15422 launching without issue, while #14409 has it's regression marked at 15420.

### Details

Video sample showing v0.0.29-15422-bb2d7063 [WORKING]:

https://github.com/RPCS3/rpcs3/assets/81897205/3a4b916c-3e0b-4fe1-a8fb-6cbb5d682d81

Video sample showing v0.0.29-15426-d34287b2 [REGRESSION]:

https://github.com/RPCS3/rpcs3/assets/81897205/6ba41291-a122-4663-ba32-0af3277964c5

Things to note, I don't get any pop up window regarding any fatal error.
When I stop the game a window briefly shows up before game closes, then I am free to start the game again.

### Build with regression

v0.0.29-15426-d34287b2

### Attach two log files

Note, these log files do not correspond with the video's from above.

Working:
[v0.0.29-15422-bb2d7063[GOOD].log](https://github.com/RPCS3/rpcs3/files/12257047/v0.0.29-15422-bb2d7063.GOOD.log)

Regression:
[v0.0.29-15426-d34287b2[REGRESSION].log](https://github.com/RPCS3/rpcs3/files/12257049/v0.0.29-15426-d34287b2.REGRESSION.log)

### System configuration

CPU: Ryzen 5 1600
RAM: 16GB
OS: Debian 11 Bullseye
Desktop: GNOME (X11)

**Comment by AniLeo** [comment]
The fact you pinpoint it as a futex regression makes me almost sure it's due to your outdated kernel. [futev_waitv() was added on Linux 5.16](https://www.collabora.com/news-and-blog/blog/2022/02/08/landing-a-new-syscall-part-what-is-futex/), and you're using 5.10

Please update your OS, your kernel and mesa versions are insanely outdated, let us know if it works with the newer kernel

@Nekotekina for visibility

**Comment by Nekotekina** [comment]
Oh, yes, it says so in purple logs

**Comment by pumpkinhi11** [comment]
Okay, due to the nature of my PC I can't update my kernel, since my system is used for other tasks and requires the older kernel. So I'm fine with closing the issue since my kernel is outside recommended specifications.

**Comment by Nekotekina** [comment]
Should be fixed on master
