### ISSUE TITLE
Skate 3 (VK_ERROR_DEVICE_LOST)

### ISSUE THREAD

**Issue by shoqcounter** [RPCS3/rpcs3#14433]
### Quick summary

Hi, recently i downloaded rpcs3 to play skate i installed skate 3 rom from REDACTED, basicly my game crashes all the time ive tried many fixes in custom game config like changing SPU threads, SPU decoder, Changing graphs settings etc the most basic things and i need help to fix it pls!! (my english is bad so could you explain it to me really exactly)

### Attach a log file

F {RSX [0x0134af0]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)

### System configuration

CPU Ryzen 5 5600
GPU msi gtx 970 4gb 
RAM 16 GB DDR4 3200HZ

**Comment by AniLeo** [comment]
Closing as spam, using pirated game
