### ISSUE TITLE
I can't run any games in RPCS3

### ISSUE THREAD

**Issue by NicoP2011** [RPCS3/rpcs3#14430]
### Quick summary

if I try to play any game, including XMB, then i get this error followed by a black screen:
```
F {PPU[0x1000000] Thread (main_thread) [0x0034b830]} VM: Access violation reading location 0xa00 (unmapped memory)
``` 

### Details

i am using ps3 firmware version 4.88 and RPCS3 version 0.0.29-15436-26ecd880 Alpha

### Attach a log file

Here is the [RPCS3 log file](https://github.com/RPCS3/rpcs3/files/12264687/RPCS3.log)

### Attach capture files for visual issues

This is a screenshot of RPCS3 when I boot vsh.self
![Screenshot 2023-08-04 221259](https://github.com/RPCS3/rpcs3/assets/100567074/2d2ecaa4-a718-438e-b7ff-5bd4be57c8d7)

### System configuration

OS: Windows 11 Pro
CPU: Intel Core i5-6500 @ 3.20GHz | 4 Threads
GPU: NVIDIA Geforce GTX 1060 3GB
GPU driver ver: 536.67.0.0
RAM: 16GB

**Comment by MSuih** [comment]
XMB is known to not work right now, there's a separate issue for it.

Can you try launching one of the test applications? `File > Boot (S)Elf > Boot test` then select either `gs_gcm_cube.elf` or `gs_gcm_basic_triangle.elf`.

**Comment by Skates1616** [comment]
@MSuih: I am having the same issue, its impacting every game I try to load.  Attached is a log trying to boot NHL Legacy.

I then did a boot test with gs_gcm_cube.elf and it executed without issue under the same emulator instance.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12412242/RPCS3.log.gz)

**Comment by Skates1616** [comment]
Same issue is occurring with Burnout Paradise:

`F {PPU[0x1000000] Thread (main_thread) [0x00702704]} VM: Access violation writing location 0x78337298 (unmapped memory)`

Attached is a log.
[Uploading RPCS3.log.gz…]()

**Comment by AniLeo** [comment]
The issue described by OP which prevented VSH from working has been fixed a while ago, so I'm closing this issue. New, unrelated issues should go on their own tickets.
