### ISSUE TITLE
[Regression] Two titles from my library crash RPCS3 to desktop after linking/creating PPU cache

### ISSUE THREAD

**Issue by mrtnptrs** [RPCS3/rpcs3#14445]
### Quick summary

Multiple games in my library just crash RPCS3 to desktop right after/during linking PPU cache, resulting in being unable to boot the game.

### Details

In my library The Godfather: The Don's Edition (BLUS30023) and The Simpsons Game (BLUS30065) suffer from this issue. All games mentioned are using dumps verified with the IRD-database. The Simsons Game I had played months ago and then it worked fine. Other games like Ratchet and Clank games, Twisted Metal, Dante's Inferno, God of War games, inFAMOUS games, Jak and Dexter Collection, Killzone games etc. work just fine. Deleting all caches and forcing RPCS3 to recreate them did not solve the issue. You also sometimes have to btw kill RPCS3 through the task manager afterwards as even when closing all RPCS3 windows, sometimes the process will stay intact.

Edit: also tested Skate 3, Metal Gear Solid HD Collection, Midnight Club Los Angeles - Complete Edition, Motostorm games and Resistance 3 to be working correctly and thus not suffer from this issue.
Edit 2: SSX and Uncharted 2 & 3 also boot.

### Build with regression

v0.0.29-15463-edf4f7e Alpha

### Attach two log files

Log-file while attempting to boot:
-The Simpsons Game:  [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12283360/RPCS3.log)
-The Godfather The Don's Edition: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12283364/RPCS3.log)

### System configuration

CPU: Intel i7 13700KF
GPU: Nvidia RTX 4090
GPU-driver: 536.67
RAM: 64 GB 5600 MHz DDR5
Settings: default

**Comment by elad335** [comment]
does it happen in the build before?

**Comment by mrtnptrs** [comment]
Can confirm the issue with The Simpsons Game and The Godfather: The Don's Edition now indeed has been fully fixed and the games boot fine. Amazing work. And as said in the Discord message to elad, sorry that I didn't do regression analysis, but kinda reported this issue on advice of some Discord members and after testing which games were and weren't affected, I had little time yesterday to test where the regression came from. Wanted to do it in a few hours actually haha, but good to see elad having it solved so quickly.

**Comment by matias935** [comment]
I wanted to ask where did you download killzone 3? because I'm looking for it and I can't find it, thank you.

**Comment by mrtnptrs** [comment]
> I wanted to ask where did you download killzone 3? because I'm looking for it and I can't find it, thank you.

https://rpcs3.net/disclaimer: "We do not promote piracy nor do we allow it under any circumstances. Any users conversing about piracy upon joining the Discord server, forums or GitHub community will receive administrative action."
