### ISSUE TITLE
[Regression] LittleBigPlanet 3 Protos often hang

### ISSUE THREAD

**Issue by LBPHaxMods** [RPCS3/rpcs3#14448]
### Quick summary

In various LittleBigPlanet 3 prototypes, including the Private Beta, the game will often hang/freeze, it doesn't appear to be random, as it always happens on specific levels, like Meet Sackbird/Hot Air Kaboom will always freeze after a few seconds on the LBP3 Private Beta. 

https://github.com/RPCS3/rpcs3/assets/92583355/58ce460a-457f-41de-ac07-84ef18d8cae4

### Build with regression

v0.0.19-12976-69f321a4

### Attach two log files

v0.0.19-12976-69f321a4
https://drive.google.com/file/d/1EOQ29gxk7d1rz1JD3LOscaL5Tp_J8hkz/view?usp=sharing
Working build
https://drive.google.com/file/d/1nVvV9hSVjz_E-p1iJ5b7pH8u9UaY5qCa/view?usp=sharing

**Comment by Graubek** [comment]
Why are you using such an outdated version of RPCS3?

**Comment by LBPHaxMods** [comment]
The video example is recorded on latest, the build with regression and log file are there to show that it broke on that build specifically.

**Comment by LBPHaxMods** [comment]
Not sure which specific commit fixed it, but it doesn't seem to happen anymore
