### ISSUE TITLE
Sonic the Hedgehog [BLJM60006] No audio of any sort beyond the title screen.

### ISSUE THREAD

**Issue by TailsGuy** [RPCS3/rpcs3#14447]
### Quick summary

There's no sound beyond the title screen.

### Details

Well, there's no audio anywhere after the title screen, the main theme plays like normal, the sound effect plays when you press start, so on and so on, but when you get into the actual main menu, and play the game there's no audio. This is with and without the canary patch that recently fixed graphics.

### Attach a log file

[SONIC THE HEDGEHOG [BLJM60006].log.gz](https://github.com/RPCS3/rpcs3/files/12285643/SONIC.THE.HEDGEHOG.BLJM60006.log.gz)

### Attach capture files for visual issues

https://github.com/RPCS3/rpcs3/assets/70661792/f2017d6f-6591-4d65-a9de-b53eea374baa

### System configuration

AMD Ryzen 7 5700X
NVIDIA GeForce RTX 3070
32GB Crucial Ballistix 3600Mhz CL16

### Other details

I had my language set to Japanese and the console region to Japanese via custom configuration.

**Comment by FlexBy420** [comment]
Try with the save data made by RPCS3 not PS3

**Comment by TailsGuy** [comment]
That fixed it. Strange how it the PS3 save didn't work though, they're the same structure wise. Maybe it's some audio setting in the PS3 save?
