### ISSUE TITLE
Tom Clancy's EndWar [BLUS30180] - White screen with errors

### ISSUE THREAD

**Issue by jeremys18** [RPCS3/rpcs3#14442]
### Quick summary

The game Tom Clancy's EndWar [BLUS30180] loads but the console throws hundreds of errors. It goes to in game fine but after loading mission the background is gone (white),

### Details

The game didn't load past the first back screen but now installs with the latest update. However, there's hundreds of errors shown when it installs. I've attached the log.

A video of the issue can be seen here: https://youtu.be/gAp4MKvjFOg

But even with the errors it seems to install and load. The menus load and I can select a game mission. But when the mission starts, the screen is white with icons. The entire background is missing. See below:

![image](https://github.com/RPCS3/rpcs3/assets/2172410/496fb4d4-4da1-4cec-b465-8e251f6f80c9)

It seems to only be the actual mission and failure screen affected as the rest shows fine
![image](https://github.com/RPCS3/rpcs3/assets/2172410/01dc6642-d858-4d08-b54e-7b84c5e4cdcf)

So does the select mission screen. I can hear the audio perfectly as well. 
![image](https://github.com/RPCS3/rpcs3/assets/2172410/ad89af86-619d-46ac-a705-f78090feae0f)

Not sure why there are so many errors or why the actual mission is missing the backgrounds. The game is ripped straight from my disc using PS3 Disc Dumper 3.36R2
now installs with the latest update

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12272778/RPCS3.log)

**Comment by FlexBy420** [comment]
This is fixed by enabling Write Color Buffers. According to your log you didn't enable it.

**Comment by jeremys18** [comment]
Thanks. That fixed it. Apparently that setting is a must for this game.
