### ISSUE TITLE
The Simpsons Game - Fails to boot after building SPU cache

### ISSUE THREAD

**Issue by Mick666** [RPCS3/rpcs3#14456]
### Quick summary

I'm having issues getting the Simpsons Game to boot.

I've verified the files using this link: https://wiki.rpcs3.net/index.php?title=Help:Validating_PlayStation_3_game_dumps#Validating_Blu-ray_disc_games and all of the files validated correctly.

I've tried rolling back to an earlier build as someone recommended (v0.0.29-15444-6672499d) and still got the same error.

I get the same errors after scanning the PPU modules:
E SYS: 'sys_rsx_context_attribute' failed with 0x80010002 : CELL_EINVAL [1]
E sys_fs: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00142/USRDIR” [1]
E SYS: 'sys_fs_closedir' failed with 0x8001002a : CELL_EBADF [1]
E sys_fs: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00142/USRDIR” [1]
E SYS: 'sys_fs_closedir' failed with 0x8001002a : CELL_EBADF [1]

And I see this error before them, I'm not sure if that's the root cause:
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]

I get for a moment the Itchy & Scratchy loading icon in the bottom left, then it goes to the black screen and refuses to load.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12297358/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12297359/RPCS3.log.gz)

### System configuration

[DxDiag.txt](https://github.com/RPCS3/rpcs3/files/12297375/DxDiag.txt)

**Comment by Jonathan44062** [comment]
the log said you're using PPU decoder static, set back to PPU LLVM and try again

**Comment by Mick666** [comment]
Same problem with PPU LLVM. I was originally using that (I reset to default settings too) and then tried PPU decoder static.


[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12297879/RPCS3.log.gz)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12297878/RPCS3.log)

**Comment by Jonathan44062** [comment]
I can't repro, works fine on my own, try to remove cache, right click on the game > remove > remove all cache 
![image](https://github.com/RPCS3/rpcs3/assets/78843189/311ad591-f2e6-47c7-bf08-ba22f4a60bcb)

**Comment by Mick666** [comment]
No luck, I did that and then installed the latest NVidia driver and still got the same error.

Any other ideas I should try?

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12298163/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12298164/RPCS3.log.gz)

**Comment by Jonathan44062** [comment]
Better ask for support in rpcs3 discord server

**Comment by Mick666** [comment]
I tried something different- I copied the USRDIR folder from the folder RPSC3 was looking at and into /dev_hdd0/game/BLES00142. This was on a hunch because of the errors I saw that it was looking in that directory for files and not finding them.

I now have a different error, I don't know if this progress or not:
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00142/USRDIR/ears_godfather.self” [1]

It's almost like RPSC3 is looking in the wrong directory, when I've pointed it to the folder with PS3_GAME and PS3_DISC.SFB.

Logs attached. I'll ask in discord for some help too.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12298483/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12298485/RPCS3.log.gz)

**Comment by Mick666** [comment]
I was able to solve this by copying in the config from someone else who had this problem.

Attached is the config I copied. No idea why this suddenly worked.
[config_copy.txt](https://github.com/RPCS3/rpcs3/files/12303411/config_copy.txt)
