### ISSUE TITLE
[Regression] echochrome no longer playable

### ISSUE THREAD

**Issue by michaelandersonb** [RPCS3/rpcs3#14466]
### Quick summary

echochrome used to be playable but is now crashing when pressing a button after level load 

### Details

I was able to get it working on versions before https://github.com/RPCS3/rpcs3/pull/12894 but it new versions crash when pressing buttons after a level has loaded 

### Build with regression

v0.0.25-14432-b0e376ae

### Attach two log files

[broken RPCS3.log.gz v0.0.25-14432-b0e376ae](https://github.com/RPCS3/rpcs3/files/12324501/RPCS3.log.gz)
[working RPCS3.log.gz v0.0.25-14425-1811dd67](https://github.com/RPCS3/rpcs3/files/12324552/RPCS3.log.gz)

### System configuration

Windows 10 Build: 19044
Intel 8700k
Nvidia GTX 1070 (driver 536.67.0.0)

### Other details

seems to be related to the video encoder

**Comment by Megamouse** [comment]
Thanks. Good work finding the culprit.
