### ISSUE TITLE
[Regression] Call of Duty: Modern Warfare 3 Cannot Go In-Game after #14461

### ISSUE THREAD

**Issue by jeremybris** [RPCS3/rpcs3#14464]
### Quick summary

After PR #14461 (v0.0.29-15471 and after) Modern Warfare 3 can not go in-game.

### Details

I recieve the following error when selecting any mission, single-player, survival, or anything. ([RPCS3.log](https://github.com/RPCS3/rpcs3/files/12323900/RPCS3.log)):

![Screenshot 2023-08-11 133507](https://github.com/RPCS3/rpcs3/assets/11889359/e336b908-7e6a-41ff-a7e3-b8f04dc763c4)

### Build with regression

0.0.29-15471, PR #14461

### Attach two log files

v0.0.29-15470 (working) - [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12324007/RPCS3.log)
v0.0.29-15471 (not working) - [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12323918/RPCS3.log)

### System configuration

**Settings**:
- Default settings of the emulator, with "Vulkan".

**Specs**:
- CPU - AMD 7900 (non-x)
- GPU - AMD 6900x
- Motherboard - Asus 670 Wifi

**Comment by elad335** [comment]
Test with #14465

**Comment by jeremybris** [comment]
> Test with #14465

Fixed by #14465 . Thank you. :)

![Screenshot 2023-08-11 150015](https://github.com/RPCS3/rpcs3/assets/11889359/e0cd3556-631f-4a82-854d-fe32a090791b)
