### ISSUE TITLE
Blur - Sound disappears and the game freezes

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#14463]
### Quick summary

The game audio goes silent as soon as the race starts, and sometimes it freezes during races.

### Details

Heres an example of when the sound disappears.

https://github.com/RPCS3/rpcs3/assets/125112932/a6adb264-7d0a-4261-a5d0-d8a39e570371

Then the game freezes with this error.
**{PPU[0x1000011] Thread (Audio) [0x002d027c]} VM: Access violation writing location 0x3ddef25b (unmapped memory)**

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12319828/RPCS3.log.gz)

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 536.99.0.0 | Windows 10 Pro 22H2

**Comment by cas-1092** [comment]
Can you give this a shot with accurate xfloat? Just tried it and managed to complete a race with audio and no freezes.

**Comment by Ordinary205** [comment]
Can confirm that this fixes an issue when using Accurate XFloat, this also needs to be updated on the RPCS3 wiki after this.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12475167/RPCS3.log.gz)
