### ISSUE TITLE
[Regression] Black Screens with several games such as MGS Peace Walker

### ISSUE THREAD

**Issue by Menergy1984** [RPCS3/rpcs3#14468]
### Quick summary

Several of my games are getting blackscreens such as Metal gear Solid HD Collection Peace Walker and God of War 3 after updating to v0.0.29-15472-c6dcf3f1. I had to revert to build v0.0.29-15468-58e9e54b for everything to work fine again.

### Build with regression

v0.0.29-15472-c6dcf3f1

### Attach two log files

Older Build Working Log - [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12325819/RPCS3.log)
Regression Build Log - [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12325820/RPCS3.log)

### Attach capture files for visual issues

![Regression](https://github.com/RPCS3/rpcs3/assets/141283078/6bf62fba-ea35-49f4-98e7-cf2b4849fe38)

### System configuration

CPU: Intel i9 12900KS
RAM: 32GB DDR5 5600Mhz CL32
GPU: RTX 4090 Driver Version 536.67
OS: Windows 11 Pro 22H2 22621.2134

**Comment by elad335** [comment]
Actually, this is probably fixed in the new build, it would be available on the website in a few minutes.

**Comment by FlexBy420** [comment]
Works again.
![obraz](https://github.com/RPCS3/rpcs3/assets/68403300/cadd6d3e-80a1-4402-9265-a6cb70cb2449)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12330136/RPCS3.log.gz)

**Comment by Menergy1984** [comment]
Glad to hear it fixed!
