### ISSUE TITLE
Ratchet & Clank: Tools of Destruction™ [BCES00052] - Character voices are muted during cinematic cutscenes

### ISSUE THREAD

**Issue by mavethee** [RPCS3/rpcs3#14471]
### Quick summary

Speeches of characters during cinematic cutscenes are muted.

### Details

Not sure how to use right wording on this issue, I will also include disc dump validation maybe that helps, not sure if it's my dump or OS issue, haven't got a chance to test on proper Windows / Linux hardware.

![CleanShot 2023-08-12 at 13 05 49@2x](https://github.com/RPCS3/rpcs3/assets/47083527/5f42671b-4320-4010-8458-169744f5a4b6)

Every time launching cinematic cutscene, whatever during game progressing or booting it from `START -> EXTRAS -> CINEMATICS`, every background noise is present but characters voices are not present and log spams with this:

`E SYS: Stat: 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY`

I know I don't wanna be that guy to paste random things from log file.

This seems to be only an issue with cinematics but not in-game cutscenes.

Not sure if it always been like that, or it's regression, couldn't really track the version that would have proper cinematics working.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12327210/RPCS3.log.gz)

### System configuration

- SYS: RPCS3 v0.0.29-15472-c6dcf3f1 Alpha | master
- SYS: VirtualApple @ 2.50GHz | 8 Threads | 16.00 GiB RAM | TSC: 1.000GHz
- SYS: Operating system: macOS, Version: 14.0.0
- SYS: Current Time: 2023-08-12T13:12:01
- RSX: Found Vulkan-compatible GPU: 'Apple M1' running on driver 0.2.988
- SYS: Firmware version: 4.90

**Comment by mavethee** [comment]
This can be closed, not sure if it was added when I already opened this issue but according to Wiki just needs `English (US)` in System language.
https://wiki.rpcs3.net/index.php?title=Ratchet_%26_Clank_Future:_Tools_of_Destruction
Which is weird as it's like European region of the game (?)

**Comment by Darkhost1999** [comment]
> Which is weird as it's like European region of the game?

What languages work on your physical PS3 console? Cause the issue can remain open if your game supports the language you're trying to use.
