### ISSUE TITLE
[Regression] Need for Speed: The Run - Unable to press the start button (#14458)

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#14470]
### Quick summary

After updating the RPCS3, I am unable to press the start button.

### Details

On version 15468, everything used to be working fine.
![NFS THE RUN works](https://github.com/RPCS3/rpcs3/assets/125112932/0f6bb5ad-30c2-42de-b863-066f205ab1a9)

But for some reason on version 15470. I am unable to press the start button with my xinput controller, and the only way to fix this is by reconnecting the controller.
![NFS THE RUN doesnt work](https://github.com/RPCS3/rpcs3/assets/125112932/8b682203-ff5d-4fdf-a053-de84b9c4a657)

### Build with regression

v0.0.29-15470-4bbe885f

### Attach two log files

15468 (Working):
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12326972/RPCS3.log.gz)

15470 (Not working):
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12326971/RPCS3.log.gz)

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 536.99.0.0 | Windows 10 Pro 22H2

**Comment by elad335** [comment]
What if you set PPU tgread count to 3 or 4? (not a dynamic setting)

**Comment by Ordinary205** [comment]
Sadly nothing changes. Reconnecting the controller is still mandatory.

PPU Thread count 3: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12326988/RPCS3.log.gz)
PPU Thread count 4:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12326991/RPCS3.log.gz)

**Comment by Ordinary205** [comment]
Fixed on this PR #14480
