### ISSUE TITLE
Ultimate Action Triple Pack BLUS-31551 only detects one game (Tomb Raider)

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#14478]
### Quick summary

Ultimate Action Triple Pack BLUS-31551 only detects one game
there is 3 games on the disc 
Tomb Raider
Just Cause 2 
Sleeping Dogs
it just detects Tomb Raider

### Attach a log file

nothing in the log

### System configuration

- SYS: RPCS3 v0.0.29-15479-39bbf17c Alpha | master
- SYS: AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 31.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-08-13T09:49:09
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060' running on driver 536.99.0.0
- SYS: Firmware version: 4.90

**Comment by Megamouse** [comment]
Missing log file

**Comment by benderscruffy** [comment]
how do i get a log
RPCS3 detects it as tomb raider  BLUS31036 as in the picture and when you click on it tomb raider loads 
![Screenshot 2023-08-13 171221](https://github.com/RPCS3/rpcs3/assets/2696404/bea06511-0840-43ad-9ab1-0511d512334b)

**Comment by ReLyf47** [comment]
![Screenshot 2023-08-13 190337](https://github.com/RPCS3/rpcs3/assets/133575967/703e968b-e453-4008-87ba-71c643952f03)

not to be that guy but uh
i believe this is the screenshot you attached to this post
and all 3 games you listed is on your game list

**Comment by benderscruffy** [comment]
Already had those 2 games in before I put in ultimate action triple pack
Then show me in the list where blus 31551 is then

**Comment by FlexBy420** [comment]
BLUS31551 is a collection ID. Every game has it's own ID and they are showing up as intended.
http://redump.info/disc/39434/
