### ISSUE TITLE
[Regression] Silent Hill Downpour crashes on launch 

### ISSUE THREAD

**Issue by SolomonGrundyThanksForTheTurkey** [RPCS3/rpcs3#14488]
### Quick summary

Hi all

recently tried to play silent Hill Downpour and the game crashes after hanging on PPU compiling for a minute. 

### Build with regression

v0.0.29-15482-968762c1

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12346082/RPCS3.log)

**Comment by AniLeo** [comment]
Invalid regression report, missing log file from last good build

**Comment by AniLeo** [comment]
Closing as the report is incomplete, if it gets completed we can reopen it
