### ISSUE TITLE
[Regression] RPCS3 isn't functioning at all (LINUX) 

### ISSUE THREAD

**Issue by Ung1ue** [RPCS3/rpcs3#14494]
### Quick summary

Stops functioning at v0.0.29-15443-dea24c90. Im on Linux Mint Cinnamon 21.2 then this error occurs when starting any game (After v0.0.29-15443-dea24c90) error: F {Pause Message Thread} SIG: Thread terminated due to fatal error: futex_waitv is not supported (Linux kernel is too old) (in file /tmp/cirrus-ci-build/rpcs3/util/atomic.cpp:883, in function wait) (errno=38=Function not implemented)

I would appreciate it if you could find a fix so I could use the newer versions. Another reminder it occurs in every single game I test not just the game in the log (Marvel VS Capcom 3) 

### Build with regression

v0.0.29-15443-dea24c90

### Attach two log files

Heres the log it was to long to enter here just click on the document button on mega no need to even download it: https://mega.nz/file/qFt0EBjD#ap1gXjhO9HAtqZjGWyg70bzblJofliNvCoVkTIZXNb8

### System configuration

In log 

### Other details

Extra info im on a Lenovo Legion Y540

**Comment by Ung1ue** [comment]
wow such epic report

**Comment by raphipod** [comment]
Frankly, your kernel is too "old".

RPCS3 tries to call futex_waitv, which was first implemented in Kernel 5.16 - you are probably running 5.15 if you're on Mint 21.2

1.  You could update your kernel with the inbuilt kernel updater in Mint to get to => 5.16 (if that's even possible), or use a PPA to install a custom kernel such as XanMod or (which is not recommended with an NVIDIA GPU, even worse with a Hybrid/PRIME laptop as yours)

2. Just straight up use another distro that is a little more up-to-date. It doesn't have to be Arch - just some distro that has a higher kernel than 5.15. If you like the Desktop you have, you might want to give the [Cinnamon Spin of Fedora](https://fedoraproject.org/spins/cinnamon/) a try.

**Comment by Nekotekina** [comment]
Try the latest version.

**Comment by raphipod** [comment]
> Try the latest version.

Sorry, saw that too late. Glad you could sort it out.

**Comment by Parotaku** [comment]
> Try the latest version.

That's the problem I had too... can confirm it's now working.
Thanks for the fix (and sorry for posting in that other Linux thread).
