### ISSUE TITLE
[Regression] Sonic Unleashed stopped working (#14491)

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#14497]
### Quick summary

The game gives me black screen, I tested other games, but Sonic Unleashed is the only game that give me the problem 
![image](https://github.com/RPCS3/rpcs3/assets/78843189/ce7f0a0e-8891-4b41-9ee6-2b8a38224644)

### Details

The build 0.0.29-15849 (https://github.com/RPCS3/rpcs3/pull/14491) breaks the game

### Build with regression

0.0.29-15849

### Attach two log files

[SU_Works.log.gz](https://github.com/RPCS3/rpcs3/files/12366628/SU_Works.log.gz)

[SU_Broken.log.gz](https://github.com/RPCS3/rpcs3/files/12366630/SU_Broken.log.gz)

### Attach capture files for visual issues

None

### System configuration

Windows 10 22H2
Intel Core i7-8700
15.93 GiB RAM
GPU: NVIDIA GeForce GTX 1070 Ti (536.99)

**Comment by elad335** [comment]
Ah yes, because `Accurate SPU Reservations: false`

**Comment by Darkhost1999** [comment]
<img width="1280" alt="Screenshot 2023-08-17 042157" src="https://github.com/RPCS3/rpcs3/assets/60384196/c9923343-31af-4441-abb2-f34c05222e4f">

[SONIC UNLEASHED [BLUS30244].log.gz](https://github.com/RPCS3/rpcs3/files/12367583/SONIC.UNLEASHED.BLUS30244.log.gz)

Ryzen 5 3600
Windows 11
GTX 1660 Super
I am using Accurate SPU Reservations: false without black screen or when does the screen turn black.

**Comment by elad335** [comment]
I pushed a fix to #14498
