### ISSUE TITLE
[Regression] Game window doesn't rescale to client window

### ISSUE THREAD

**Issue by raphipod** [RPCS3/rpcs3#14492]
### Quick summary

(Alt+Enter) enters Fullscreen as it should. 
But the in-game window doesn't scale with the client window and doesn't render any frames. See video (This only happens on Vulkan and two of my games in the library - OpenGL is unaffected)

### Details

https://github.com/RPCS3/rpcs3/assets/56308821/cce1905f-ba2d-4073-92c1-aae947ea1f6d

At 0:08 I fullscreened RPCS3 with Alt+Enter and escaped it to get rendered frames again (look at the loading bar)
This also happens in-game, not only in the loading screen.

### Build with regression

v0.0.29-15486-01a05502 (Qt 6.5.0)

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12361400/RPCS3.log)

**Two or three versions beforehand of the official Linux AppImages also had the problem. I had used the Flatpak version before, so I can't say for sure.**

### Attach capture files for visual issues

[NPEB01283_20230816194014_capture.rrc.tar.gz](https://github.com/RPCS3/rpcs3/files/12362112/NPEB01283_20230816194014_capture.rrc.tar.gz) (don't know if it helps...)

As you can see in the debug window of RPCS3 while running the game and entering fullscreen:

`E RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max= 1280, 720, Requested = 2560, 1440` (my main monitor's native resolution)

### System configuration

AMD Ryzen 7 5700G with Radeon Integrated Graphics
AMD Radeon RX 6650 XT 8 GB (<- this is used for Vulkan Renderer)
32 GB RAM

Nobara Linux 38
KDE Plasma / Wayland
Kernel 6.4.10-201
Mesa 23.1.5

Monitor 1: 2560 x 1440
Monitor 2: 1920 x 1080

**Comment by raphipod** [comment]
Probably also related to this:

https://github.com/RPCS3/rpcs3/issues/14255#issuecomment-1657626751

**Comment by raphipod** [comment]
I traced back the versions:

0.0.27-14800 errors out while loading GTAV from my library.
Every version afterwards (Qt 5.15.2) loads it fine, but won't scale to client window as described in the newest version with Qt 6.5.0 ....
So it can't really be a Qt regression as I first suspected.

All newer builds of 0.0.28 and 0.0.29 are also affected, of course.

**Comment by AniLeo** [comment]
Does it work with X11? Could be a Wayland-specific issue

**Comment by raphipod** [comment]
> Does it work with X11? Could be a Wayland-specific issue

That would've been my next step, I'll get back if it's Wayland specific.

**Comment by raphipod** [comment]
Weirdly enough, the Flatpak version of RPCS3 (currently at 0.0.29-1-f1d9e894) has no such issue.

**Comment by Mrlinkwii** [comment]
@raphipod can this be rechecked  on latest release

**Comment by raphipod** [comment]
Seems to be fixed! What was the culprit if I might ask?
