### ISSUE TITLE
[Regression] DJ Hero 2 no longer responding to turntables as of 0.0.29-15470 (#14458)

### ISSUE THREAD

**Issue by shockdude** [RPCS3/rpcs3#14493]
### Quick summary

As of 0.0.29-15470 (#14458), DJ Hero 2 (BLUS30526) no longer responds to DJ Hero turntable input, for both real & emulated turntables.

### Details

- Configure a real turntable, or enable an emulated turntable
  - Config > I/O > DJ Hero Emulated turntable, set to 1 controller
  - Pads > Device Class, set to DJ
- Boot DJ Hero 2 and press buttons to try to skip the intro movies
  - Movies skipped and game playable in 0.0.29-15468, movies unskippable and game unplayable in 0.0.29-15470.

### Build with regression

v0.0.29-15470-4bbe885f

### Attach two log files

[RPCS3-15468.log.gz](https://github.com/RPCS3/rpcs3/files/12362258/RPCS3-15468.log.gz)
[RPCS3-15470.log.gz](https://github.com/RPCS3/rpcs3/files/12362259/RPCS3-15470.log.gz)

### System configuration

Windows 10 22H2
Intel i7-4720HQ
Nvidia GTX 860M, driver 531.41

**Comment by elad335** [comment]
Test with #14509

**Comment by elad335** [comment]
Retest.

**Comment by shockdude** [comment]
Sorry for the late reply, was unable to test in the past few days.
Issue is not resolved in 0.0.29-15502 (#14509) nor in 0.0.29-15525 (latest)
[RPCS3-15502.log.gz](https://github.com/RPCS3/rpcs3/files/12434835/RPCS3-15502.log.gz)
[RPCS3-15525.log.gz](https://github.com/RPCS3/rpcs3/files/12434844/RPCS3-15525.log.gz)

**Comment by Megamouse** [comment]
Please test with https://github.com/RPCS3/rpcs3/pull/14553

**Comment by shockdude** [comment]
Issue is not fixed as of 0.0.29-15540 (#14553). Tested with an emulated turntable.
Requesting this issue be reopened.
[RPCS3-15540.log.gz](https://github.com/RPCS3/rpcs3/files/12449082/RPCS3-15540.log.gz)

**Comment by shockdude** [comment]
Just in case, this issue can be reproduced in all games that use DJ Hero Turntables, i.e. DJ Hero 1 (BLUS30368) and the DJ Hero 2 PSN Demo (NPUB90438).
DJ Hero 1: [RPCS3-15540-DJH1.log.gz](https://github.com/RPCS3/rpcs3/files/12465456/RPCS3-15540-DJH1.log.gz)
DJ Hero 2 Demo: [RPCS3-15540-DJH2demo.log.gz](https://github.com/RPCS3/rpcs3/files/12465464/RPCS3-15540-DJH2demo.log.gz)

**Comment by AniLeo** [comment]
@elad335 could you check this one again? Regression still active

**Comment by shockdude** [comment]
Regression still active. Testing using a real turntable, since most of the recent logs have been with emulated turntables.
[RPCS3-15723.log.gz](https://github.com/RPCS3/rpcs3/files/13359172/RPCS3-15723.log.gz)

**Comment by qfoxb** [comment]
This is still not working.

**Comment by qfoxb** [comment]
Could any more progress be made on this?? Please? It's impossible to play this game online now that y'all have locked the fucking RPCN protocol to the latest builds only.

**Comment by AniLeo** [comment]
Likely the same root cause as #14969

**Comment by elad335** [comment]
Retry with https://github.com/RPCS3/rpcs3/pull/14959

**Comment by SCOTT0852** [comment]
Just tested #14959 and very briefly and my turntable did seem to work in the menus, looking promising. Very glad this looks to be fixed after so long!

**Comment by kamild1996** [comment]
I'd like to test this, do we need to build it ourselves to test #14959 ?

**Comment by Megamouse** [comment]
No. You have to simply update to the latest version

**Comment by kamild1996** [comment]
Tested on build 0.0.29-15896, not working. Same as before, no response to PS3 turntable input.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13804327/RPCS3.log.gz)

**Comment by elad335** [comment]
Test wirh #14988

**Comment by kamild1996** [comment]
> Test wirh #14988

Works! Tested in menu and in-game, works great, thank you <3

https://streamable.com/2n3ynw

**Comment by SkullMan140** [comment]
Hello, i found this thread as i tried to use Mouse and Keyboard and a controller for both DJ Hero 1 and DJ Hero 2, but none of my inputs are working if the pad is set as "DJ Hero Turntable"
