### ISSUE TITLE
Accessing "Config" causing an instant crash with certain audio input devices

### ISSUE THREAD

**Issue by Aran8276** [RPCS3/rpcs3#14502]
### Quick summary

Accessing "Config" causing an instant crash on a certain device/hardware.
![](https://im.ezgif.com/tmp/ezgif-1-932c0bfe6a.gif)

### Details

This is issue was happening on my ASUS TUF FX506HC Gaming Laptop, but on my secondary PC (AMD A10 9700-K, No GPU since it wasn't intended for gaming) works flawlessly when accessing the config option, I suspect this issue occurring due to a some sort of conflict when the program is trying to access the PC's information

[Original Video + Working Example](https://github.com/RPCS3/rpcs3/files/12376668/Videos.zip)

### Attach a log file

[(WORKING)RPCS3.log](https://github.com/RPCS3/rpcs3/files/12376657/WORKING.RPCS3.log)
[(CRASH) RPCS3.log](https://github.com/RPCS3/rpcs3/files/12376659/CRASH.RPCS3.log)

### System configuration

[(WORKING) DxDiag.txt](https://github.com/RPCS3/rpcs3/files/12376732/WORKING.DxDiag.txt)
[(CRASH) DxDiag.txt](https://github.com/RPCS3/rpcs3/files/12376733/CRASH.DxDiag.txt)

**Comment by AniLeo** [comment]
Try disabling AI related ASUS audio devices both for Input/Output and try again
