### ISSUE TITLE
[Regression] rpcs3 keeps crashing after installing firmware, troubleshooting or launching a game

### ISSUE THREAD

**Issue by Meoud** [RPCS3/rpcs3#14500]
### Quick summary

when i try to launch a game it does nothing and eventualy doesnt response anymore this is odd because i played my game on the emulator this morning and it worked fine

### Details

ive tried a lot of trouble shooting steps like restarting emulator, restarting pc, removing caches, redownloading the emulator etcetera notihing works witch is weird because i used it yesterday and this mornig and it worked fine. i have also tried other builds but nothing works.

### Build with regression

v0.0.29-15487-384c807d

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12372544/RPCS3.log.gz)

### System configuration

Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz | 6 Threads | 15.94 GiB RAM | TSC: 2.904GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
Qt version: Compiled against Qt 6.5.2 | Run-time uses Qt 6.5.2
RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce GTX 1660' running on driver 536.23.0.0

**Comment by AniLeo** [comment]
Incomplete regression report, missing second log file from last known good build

**Comment by Meoud** [comment]
thats the problem its on the same build

**Comment by AniLeo** [comment]
I don't follow, if you had it working with the same build in the past it's not a regression, it's a bug report

**Comment by Meoud** [comment]
Oh sorry I'm new to this stuff but it's kinda weird if it's a bug In the build because when I downgrade the same issues are present.

**Comment by AniLeo** [comment]
Closing as it's not a regression but a local issue, needs to be a support request in Discord/Forums instead if it still persists
