### ISSUE TITLE
[Feature request] Support for Tony Hawk Ride Board

### ISSUE THREAD

**Issue by 552eden** [RPCS3/rpcs3#14507]
### Quick summary

Hi!
I want to add support for the Tony Hawk ride board which supports the game tony hawk ride and tony hawk shred.

### Details

while trying to add support for the tony hawk ride board 
already tried adding this to usbd:

check_device(0x12BA, 0x0400, 0x0400, "Skateboard Controller");

but it didnt help.  game still dosent see the board and gets stuck at "Please connect board"

the wii version acts as a gamecube controller. maybe here its tricking the system to think theres a ps2 usb adapter?

will continue to try!

attaching log here
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12385398/RPCS3.log)

**Comment by kxshy-png** [comment]
the tony hawk ride board for some reason ceases to function even with the right handler and device class, it will connect and the button inputs work, but the game doesnt pick it up as the "ride skateboard"
even when i set the board to player 2, the board thinks it's player 1
the board functions fine on a real ps3

[RPCS3.log.gz](https://github.com/user-attachments/files/23691785/RPCS3.log.gz)
