### ISSUE TITLE
Need for Speed: The Run - Ground/mountains randomly goes invisible

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#14511]
### Quick summary

The ground/mountains sometimes goes missing during stages, and enabling write color buffers partially fixes this issue.

### Details

This commonly happens at the beginning of stage 1.
![Invisible ground](https://github.com/RPCS3/rpcs3/assets/125112932/544bdfd7-bc5a-4749-9362-326232cc86c3)

But if I quit the event and restart stage 1, the ground appears.
![ground is fixed](https://github.com/RPCS3/rpcs3/assets/125112932/7389d18c-547c-4326-ba5b-8d4fb3c64fc2)

Apologies if the screenshots is very dark to tell the differences.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12385439/RPCS3.log.gz)

### Attach capture files for visual issues

The capture is ridiculously huge, so I had to use mega instead.
https://mega.nz/folder/QG401AIA#c2_OX9B_Gyn9X22DpdtUcQ

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 536.99.0.0 | Windows 10 Pro 22H2

**Comment by kikojap** [comment]
hola buenos dias, juegas con volante o mando

**Comment by Ordinary205** [comment]
Enabling Read Color Buffers fixes missing ground or mountains.
![Need for Speed The Run](https://github.com/RPCS3/rpcs3/assets/125112932/b00f2168-e28e-470b-b3c6-451a61564425)
