### ISSUE TITLE
[Regression] Qt6 breaks one CPU thread

### ISSUE THREAD

**Issue by DaishinSilviaGT** [RPCS3/rpcs3#14517]
### Quick summary

One CPU thread stops working after opening the emulator, which causes huge performance drops

### Details

Before:
![before](https://github.com/RPCS3/rpcs3/assets/89948611/2260faa7-9873-428a-843f-96fe42772d08)
After:
![after](https://github.com/RPCS3/rpcs3/assets/89948611/e20e13fe-cce3-44c6-843c-b7097006ef11)
All following builds have the same issue

### Build with regression

v0.0.29-15419-6cd5a7ea

### Attach two log files

Before (0.0.28-15417):
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12386937/RPCS3.log)

After (0.0.29-15419):
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12386936/RPCS3.log)

### System configuration

CPU: AMD Athlon 3000G
GPU: AMD Radeon Vega 3
GPU Driver: 23.7.2

**Comment by qurious-pixel** [comment]
Minimum requirement for AMD is 4 Core, 8 Threads.
If it runs, it will be very badly.

https://rpcs3.net/quickstart

**Comment by DaishinSilviaGT** [comment]
Minimum requirement for AMD is **Any** x64 CPU, and this Athlon even has AVX2 instructions. I've got some screenshots for comparing
On pre-Qt6 build it's possible to drive around in Time trial mode of Gran Turismo 5
![at least somewhat](https://github.com/RPCS3/rpcs3/assets/89948611/37dca261-bac3-400e-b792-01c2f0d5d0c4)
But on Qt6 build the emu barely loads to the main menu, then freezes without an error or with dead FIFO commands
![barely loads](https://github.com/RPCS3/rpcs3/assets/89948611/c3a3e23c-b405-43d7-9eaf-fac908af961b)

**Comment by Pipi86** [comment]
> @qurious-pixel Minimum requirement for AMD is **Any** x64 CPU, and this Athlon even has AVX2 instructions. I've got some screenshots for comparing On pre-Qt6 build it's possible to drive around in Time trial mode of Gran Turismo 5 ![at least somewhat](https://user-images.githubusercontent.com/89948611/261870072-37dca261-bac3-400e-b792-01c2f0d5d0c4.PNG) But on Qt6 build the emu barely loads to the main menu, then freezes without an error or with dead FIFO commands ![barely loads](https://user-images.githubusercontent.com/89948611/261870446-c3a3e23c-b405-43d7-9eaf-fac908af961b.PNG)

Minimum Requirements
For being able to run any games at all, no performance or stability guarantees
CPU

AMD - Any x64 CPU
CPUs without AVX2 and with less than 4 cores and 8 threads are expected to run very badly overall
CPUs with only 2 cores per CCX cluster are expected to run very badly overall

You are using a 2 core cpu, so don't expect the emulator doing miracles. Also, if you're using some weird launch parameters for rpcs3.exe (like setting custom cpu affinity and/or priority), remove them and try again. The same goes for the game, remove all the game's caches and custom config, and try again.

**Comment by DaishinSilviaGT** [comment]
@Pipi86
I have 2 fresh emu setups, for both versions. All caches were new, using settings from the wiki (no difference if tested without any config). Don't have any launch parameters, and that one thread stops working with any other app on the background - sometimes even after closing the emulator, until reboot

**Comment by jenci8888** [comment]
I can confirm this problem. Caused by QT6 regression for any 4c/4t CPUs.

The last QT5 build:
![image](https://github.com/RPCS3/rpcs3/assets/40495799/52758a7e-5cc3-460d-9f7d-8037aec9c0de)
The current QT6 build:
![image](https://github.com/RPCS3/rpcs3/assets/40495799/82eb1d26-cc0f-46e4-b986-b7286c3ef515)

**Comment by elad335** [comment]
This may be a Windows bug, RPCS3 itself certainaly cannot prevent access to a real CPU thread.

**Comment by elad335** [comment]
This may be a Windows bug, RPCS3 itself certainaly cannot prevent access to a real CPU thread.

**Comment by ReLyf47** [comment]
this might not be relevant but it does seem to only affect 4Threaded system
![image](https://github.com/RPCS3/rpcs3/assets/133575967/ba11e9c6-32e1-4915-808c-b9790faad491)
tried running RPCS3 on a VM with 4Thread CPU and yes one of the 4Thread instantly drops to very low usage (it doesnt stop for me)

**Comment by elad335** [comment]
I mean, this problem should be reported to Microsoft. Only the operating system controls the effective use of CPU threads.

**Comment by MSuih** [comment]
Is this just a task manager bug or does it actually affect performance?

But yeah there's no way rpcs3 could be at 90%  CPU usage when only using 75% of the CPU. This problem needs to be handled by Microsoft.

**Comment by ReLyf47** [comment]
> Is this just a task manager bug or does it actually affect performance?
> 
> But yeah there's no way rpcs3 could be at 90% CPU usage when only using 75% of the CPU. This problem needs to be handled by Microsoft.

looking at the last 2 people who reported seems like it actually kills performance
i myself cant test due to how my vm is set up (it doesnt have vulkan drive to run the game)

**Comment by DaishinSilviaGT** [comment]
Fixed after installing the latest audio driver for my motherboard, as was suggested in #14648 

![image](https://github.com/RPCS3/rpcs3/assets/89948611/1b1965ea-5e61-4484-b211-e7632959fe25)
