### ISSUE TITLE
[BLUS30065] The Simpsons Game Player Teleportation

### ISSUE THREAD

**Issue by huntyboy102** [RPCS3/rpcs3#14529]
### Quick summary

The player object slightly teleports around othering game objects or the world.

### Details

While playing the levels, Lisa The Tree Hugger, and Shadow of the Colossal Donut, I experienced a bug where the player object will begin teleporting around a local area. In Lisa the tree hugger I was unable to get a screenshot or video but the teleportation was near the beginning of the level next to the big swing saw. While playing the shadow of the colossal donut teleportation is around lard lad himself, attached is a video of the teleporting player object.

### Attach a log file

Attached is a link to the only log file I can find on the steam deck

https://drive.google.com/file/d/1VrQfx0-0U94o4SXqzFAie0aS5SqYRmnY/view?usp=drivesdk

### Attach capture files for visual issues

I was only able to get one short video of the problem and it is attached here. Upon request I can try to gather more footage.

https://drive.google.com/file/d/1VZnkFrK_-FjmilSuF3Yg40qPOIFHwE5L/view?usp=drivesdk

### System configuration

OS: Arch Linux - Steam Deck Beta (3.4.8)
Cpu: Zen 2 4C/8T
GPU: 8 RDNA 2CUs
16GB LPDDR5

### Other details

N/A

**Comment by Jonathan44062** [comment]
That's because of the 60 FPS patch, very broken, disable it and just play the game at 30 FPS

**Comment by huntyboy102** [comment]
> That's because of the 60 FPS patch, very broken, disable it and just play the game at 30 FPS

Ok thank you
