### ISSUE TITLE
Macross 30 [BLJS10184] game goes black screen after finished game loading screen

### ISSUE THREAD

**Issue by muhammadwibisonojanuar** [RPCS3/rpcs3#14520]
### Quick summary

I just got frozen after loading. Even if it works, I just got 15 fps. 

### Details

Specs:
-20gb ram
-GTX 950M
Intel 6700hq
![image](https://github.com/RPCS3/rpcs3/assets/48948762/f3ff3a14-267f-43b3-9ad8-97949abbd2f7)
![image](https://github.com/RPCS3/rpcs3/assets/48948762/792fc865-4ddd-4cc2-952a-a79e1d20cd3e)
problem:
u sys_prx todo: _sys_prx_get_module_id_by_name(name=“celllibprof”, flags=0, popt=*0x0)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12388351/RPCS3.log)

**Comment by AniLeo** [comment]
Bad dump, bad issue report, closing as invalid
