### ISSUE TITLE
I am Banned From the Discord, I need Help with PS3 .pkg's

### ISSUE THREAD

**Issue by NickDeBeenSAE** [RPCS3/rpcs3#14539]
### Quick summary

The RPCS3 Emulator has failed 4 times now to detect my copy of Need for Speed Undercover.pkg

I do in fact have a 2007 model 80gb PS3 which I'll upload a photo of in another comment.

I am requesting to be unbanned from your Discord server on the grounds of now owning a PS3, which is jailbroken on Evilnat 4.90.2

### Details

I do apologies for using another persons game for testing purposes to check if the Emulator would work on my system back in 2016.

As far as I was aware, I was under the impression that for testing purposes only, you could use yours or a friends game to check if the successfully compiled and built emulator would read the .iso disk image.

I was banned for piracy, as using a friends game at the time was not allowed.

So, back on subject of this report:

I own a physical PS3, and a copy of Need for Speed Undercover, but, via merging with the PS3 Merger, RPCS3 failed to read the games .pkg file as it found it to be corrupt.

It works just fine via .iso on my PS3, so I have no idea what I am doing wrong.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12418716/RPCS3.log.gz)

### Attach capture files for visual issues

I have no screenshots available, so my apologies.

### System configuration

I have a full AMD System.

CPU: AMD Ryzen 9 5950X

GPU: Asus Dual (AMD Radeon) RX 6700 XT 12gb

GPU Driver: AMD Radeon Pro Software Version Q3.23

Main Board: Asus TUF Gaming x570-Plus (WiFi)

RAM: Corsair Vengeance LPX 2933MT/s.

Operating System: Windows 11 Pro.

**Comment by NickDeBeenSAE** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12418829/RPCS3.log)

This is a lie as I have my actual .iso of Need for Speed Undercover in the games directory.

**Comment by AniLeo** [comment]
GitHub is for not support, if you want to appeal a Discord ban you can make a thread in the forums
