### ISSUE TITLE
GL: Resogun has vertex transformation problems

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#1454]
Resogun works up until the menu in OpenGL. However, there are transformation problems with the vertex positions causing graphics to be skewed and twisted (confirmed by patching a shader at runtime). Text however displays okay.

![resogun_ogl](https://cloud.githubusercontent.com/assets/15904127/12574329/02ced148-c414-11e5-8eb0-4e9ebf8e28d6.PNG)
![resogun_autosave](https://cloud.githubusercontent.com/assets/15904127/12574360/5bed36d4-c414-11e5-8ba4-6eb4da7638ec.PNG)

**Comment by vlj** [comment]
Out of curiosity which tool do you use for patching shader? 

Resogun uses instancing which is not supported by gl backend. Since rsx instancing is more flexible that gl/d3d instancing I had to use texture buffer and SV_VertexID on d3d12  branch.

**Comment by kd-11** [comment]
@vlj I patched the shader manually once I figured out what the program was sending to the gpu. basically I did a simple override if the shader matched the one I wanted to replace. I might take a look at implementing some sort of instancing for this. I'm still getting familiar with the rsx though so I wont commit to anything just yet. I'll take a look at how its done on dx12 and try to work something out.

**Comment by kd-11** [comment]
@vlj I reworked OGL to use VertexID and made some changes in the way inputs are passed to the shaders. Resogun now works. However, I now have the same scaling issues I saw on the dx12 branch a while back. It would save some work to know how that was fixed. (see splash screenshot)

![resogun_good1](https://cloud.githubusercontent.com/assets/15904127/12627381/94fd4460-c54e-11e5-9a35-8fae359d8020.PNG)
![resogun_good1](https://cloud.githubusercontent.com/assets/15904127/12627386/9cf1a81e-c54e-11e5-9eae-3ebbd018ac0f.PNG)

**Comment by vlj** [comment]
I don't know where the green hue comes from.

For splashscreen it's an issue with vertex attribute components. Vertex attributes from vertex shader point of view are always float4/vec4 but from command buffer point of view they can have between 1 and 4 components.
In the splashscreen case the position attribute is a float2/vec2 if I remember correctly so there are 2 components (z and w) missing.
RSX behavior in such case is to fill missing component y or z component with 0. and w with 1. while GL/D3D assumes that missing component are always 0.

For D3D12 I relied on the texture buffer ability to remap texture component so that I don't have to modify vertex shader or add extra component to vertex buffer.

**Comment by kd-11** [comment]
I'm using texture buffers for GL; the spec states that missing components are 0 except w which is 1 by default so I think that should be okay.

**Comment by vlj** [comment]
Is this mentionned here ? https://www.opengl.org/registry/specs/ARB/texture_buffer_object.txt

**Comment by kd-11** [comment]
https://www.opengl.org/wiki/Buffer_Texture shows undefined components as zeros. However, the problem with rpcs3 is not even related to that. Buffer reads are aligned to 8, so 3-component 16-bit entries are expanded to 4-component 16-bit entries in bufferutils. However, in the case of the half-float, the value set for the extra channel is 0.5 and not 1. Changing this value to expand to 1 fixes the scaling issues.

**Comment by kd-11** [comment]
@vlj https://github.com/RPCS3/rpcs3/commit/d153575e59d8e5a72068d75e7248b25e38f2eeb3#diff-c749b2137d171010e40efb7281deb412R66
Did you intend to initialize the fourth component to 0.5 or 1?
0x3800 is .5, 0x3c00 is 1. Setting to 1 fixed the scaling issues

**Comment by vlj** [comment]
Ho yes sorry, it was intended to be 1. I removed the 4 trailing 0 of 0x3f8000000 for some testing on Cubixx but forgot to fix the exponent/mantissa for 16 bits later.

**Comment by kd-11** [comment]
![resogun_menu](https://cloud.githubusercontent.com/assets/15904127/12688373/e6e6e544-c6e6-11e5-9191-09cdb0d1c0de.PNG)

Menu with #1441 and #1461 in action

**Comment by tambry** [comment]
Is this still an issue?

**Comment by kd-11** [comment]
Fixed after merging https://github.com/RPCS3/rpcs3/pull/1461
