### ISSUE TITLE
[BCJS30042]Whiteknight2 JPN crash

### ISSUE THREAD

**Issue by Solidsnake9058** [RPCS3/rpcs3#14549]
### Quick summary

Game stop sometimes when compiling shaders.

![螢幕擷取畫面 2023-08-25 223354](https://github.com/RPCS3/rpcs3/assets/30305049/2b4873d7-8a50-4f2c-9533-a98ff46a8a40)

### Attach a log file

Log:
![螢幕擷取畫面 2023-08-25 223334](https://github.com/RPCS3/rpcs3/assets/30305049/9122d187-c90a-4696-91a8-55a93b562a19)

Error Message:
![螢幕擷取畫面 2023-08-25 222443](https://github.com/RPCS3/rpcs3/assets/30305049/829318b0-6eff-4e10-a652-7732f540ab86)

**Comment by AniLeo** [comment]
Does not follow issue guidelines, missing log file and system information
