### ISSUE TITLE
[Regression] Jak and Daxter Collection crash with PPU LLVM after #14547

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#14555]
### Quick summary

Every individual Jak game crashes on the first loading screen when using the PPU recompiler. 

### Details

Ever since #14547 this effect happens all the time, although I would hesitate to call it a regression because this error happened before when you load the games in a savestate, it's just that that pull somewhat melded the problem into the regular launching cycle so now it happens all the time. Windows 10 crashes to desktop but Steam Deck just gets caught in a loop, saying something about PPU thread GOAL(the proprietary scripting language for the Jak games).

### Attach a log file

[RPCS3Win10JakInter.log](https://github.com/RPCS3/rpcs3/files/12444449/RPCS3Win10JakInter.log)
[RPCS3Win10JakLLVM.log](https://github.com/RPCS3/rpcs3/files/12444450/RPCS3Win10JakLLVM.log)
[RPCS3Win10JakLLVMWorking.log](https://github.com/RPCS3/rpcs3/files/12444455/RPCS3Win10JakLLVMWorking.log)
[RPCS3Win10JakLLVMSavestate.log](https://github.com/RPCS3/rpcs3/files/12444457/RPCS3Win10JakLLVMSavestate.log)

### System configuration

- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-08-25T19:46:42
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 522.25.0.0
- SYS: Firmware version: 4.88

**Comment by Tony-C1** [comment]
I am also having the same issue

**Comment by stesproject** [comment]
Same issue

**Comment by elad335** [comment]
Test #14616
