### ISSUE TITLE
[BLUS30073] Stuntman ignition (Forever Loading)

### ISSUE THREAD

**Issue by SlipKnotSic** [RPCS3/rpcs3#14568]
### Quick summary

after selecting a level they appear to infinite load (not start all no matter how much you select it) (endless load) or work & other times infinite load, No purple code to report as none show, maybe it'll help if I copy the last 2 red messages in red

### Details

never ending load
last red text in 
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30073/USRDIR/DCManifest.txt” [1],
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30073/USRDIR\shell.ini” [1]

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12451500/RPCS3.log)

### System configuration

x64 windows 10, Rog Crosshair VIII Dark Hero, NVIDIA GeForce RTX 4080, AMD Ryzen 9 3950X, Mastercooler Rm1000x Cpu Cooler,
1000W power supply (Forgot Model)

**Comment by elad335** [comment]
Is this a regression? maybe try a build a few months old?

**Comment by SlipKnotSic** [comment]
> Invalid report as is, random settings being used without explanation as to why, including settings that can break the game, plus 2 weeks old build

ive tried diffrent configs & settings please let this stay open & not closed as its a bug

**Comment by elad335** [comment]
Add a log with default cobfiguration on the latest master.
