### ISSUE TITLE
[Regression] Since 15521, some games' loading times are too long (#14537)

### ISSUE THREAD

**Issue by QJYEAH** [RPCS3/rpcs3#14571]
### Quick summary

Since 15521,some games loading time is too long.Games like 《Dynasty Warriors 7：Empires》《Dynasty warriors 8》,before the movies,“now loading”is too long.
When the games loading,the time is also too long.

### Details

![QQ图片20230828215713](https://github.com/RPCS3/rpcs3/assets/15781690/a242e27a-c71d-4af6-9618-964ec6786412)
![QQ图片20230828215822](https://github.com/RPCS3/rpcs3/assets/15781690/a3073a1c-e667-4f06-be92-e77fe696c32b)

### Build with regression

0.0.29-15518-e2d4d400

### Attach two log files

[RPCS3 15518.log](https://github.com/RPCS3/rpcs3/files/12455225/RPCS3.15518.log)
[RPCS3 15544.log](https://github.com/RPCS3/rpcs3/files/12455227/RPCS3.15544.log)

### System configuration

CPU：R7 5800X
GPU：RTX 2080 8G
OS：Win10

**Comment by elad335** [comment]
1. How much time it actually takes?
2. How much time it takes on PS?

**Comment by capriots** [comment]
RPCS3 is indeed slower than PS3 currently. Here are a few comparison videos:
<details>
<summary>Tales of Graces f</summary>
PS3:

https://github.com/RPCS3/rpcs3/assets/29807355/81c7d3ec-8343-4ad1-a5e6-dee7c0aafd68

RPCS3:

https://github.com/RPCS3/rpcs3/assets/29807355/979f6be8-fc29-4c1b-a058-fb90a8e1c9bd

</details>
<details>
<summary>Tales of Xillia 2</summary>
PS3:

https://github.com/RPCS3/rpcs3/assets/29807355/fc50a10b-269c-463a-9de8-3082bc003576

RPCS3:

https://github.com/RPCS3/rpcs3/assets/29807355/63a43727-4e74-4000-a8e1-93ae14854519

</details>
<details>
<summary>Persona 4 Arena Ultimax</summary>
PS3:

https://github.com/RPCS3/rpcs3/assets/29807355/f012e483-89fc-4aec-a3f8-816337645740

RPCS3:

https://github.com/RPCS3/rpcs3/assets/29807355/e5e6a62b-4d52-45e3-8b7a-268003c6c582

</details>
<details>
<summary>Soulcalibur V</summary>
PS3:

https://github.com/RPCS3/rpcs3/assets/29807355/845daf15-dd19-4fe9-b480-6f2160787b42

RPCS3:

https://github.com/RPCS3/rpcs3/assets/29807355/a648d6f9-2249-474e-a3d5-a7417f00d487

</details>

[Logs](https://github.com/RPCS3/rpcs3/files/12749686/Logs.zip)

**Comment by elad335** [comment]
How about now?

**Comment by capriots** [comment]
Tales of Xillia 2's first DLC check, right after the logo, is faster now. The second one, after selecting "New Game," and the ones in the other games I tested are still noticeably slower. Dunno about @QJYEAH's games.
Setting the sleep timer to 30'000 gives almost identical performance, but I don't know if that is too low for the SingStar games you mentioned in your original PR.

**Comment by jeremybris** [comment]
SSX, digital version, is also effected.

**Comment by QJYEAH** [comment]
> How about now?

this problem is still exist.

**Comment by QJYEAH** [comment]
i tested the latest version（0.0.32-16626）,the problem is still exist
