### ISSUE TITLE
BCUS98152: SOCOM U.S. Navy SEALs Confrontation

### ISSUE THREAD

**Issue by oGeechie** [RPCS3/rpcs3#14581]
### Quick summary

Upon the loading up of my custom configuration of SOCOM U.S. Navy SEALs Confrontation, I noticed almost instantly there are numerous of system failures that take place in my log, some of which come from both "DLC1" and "USRDIR". Most of these system failures are described to be character & weapon textures, along with audio expansion packs. This is all before pressing the start button at the beginning of the start menu.

### Details

Just to reiterate, this failure occurred upon loading up my custom configuration of SOCOM U.S. Navy SEALs Confrontation, when I noticed almost instantly that there were numerous of system failures that took place in my log, some of which come from both "DLC1" and "USRDIR". Most of these system failures are described to be character & weapon textures, along with audio expansion packs. This is all before pressing the start button at the beginning of the start menu. I am quite unsure if this has any relation into some of the rendering and graphical pop-ins I notice during game-play as there are times where my character won't have any form of texture on his player model, and or certain audio tracks not playing or skipping until it ultimately the game loses sound.   

Examples of the failures located in the log are listed below: 
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98152/USRDIR/audio/vo/unloc_dialog.csv” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98152/USRDIR/expansion/pack1/audio/vo/unloc_dialog.csv” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUA80007_DLC1/USRDIR/expansion/pack1/audio/vo/unloc_dialog.csv” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98152/USRDIR/audio/vo/pack1_unloc_dialog.vob” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98152/USRDIR/expansion/pack1/audio/vo/pack1_unloc_dialog.vob” [1]

E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98152/USRDIR/.z” [1]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98152/USRDIR/characters/weapons/textures/c4_panel.c3.hi.gtf.z” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98152/USRDIR/characters/weapons/textures/c4_panel.c3.hi.gtf” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98152/USRDIR/characters/textures/black.c1.hi.gtf.z” [1]

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12475519/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12475522/RPCS3.log.gz)

### Attach capture files for visual issues

N/A

### System configuration

Processor: AMD Ryzen 5 5600G with Radeon Graphics | 12 Threads | 7.59 GiB RAM | TSC: 3.893GHz | AVX+ | FMA3 | 3.90 GHz
Installed RAM: 8.00 GB (7.59 GB usable)
System type: 64-bit operating system, x64-based processor
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0
Vulkan-compatible GPU: 'NVIDIA GeForce GTX 1660 SUPER' running on driver 537.13.0.0

### Other details

Nothing at this time, I will be uploading my full experience and what I noticed on a day to day basis with the emulator during my time span with the game. 

Thank you.

**Comment by AniLeo** [comment]
There's no bug here, it's normal for the game to check for files that might not be present, either because they're DLCs or because they're debug files that didn't end up in the final release.

Game reports are to be reported on our forums, the bug tracker is to report specific bugs.

**Comment by oGeechie** [comment]
thank you clearing this up for me, was a bit unsure so I wanted to add this in-case it could have been linked to some of the issues I was experiencing.
