### ISSUE TITLE
[BLUS30109]: Freezing before start the game

### ISSUE THREAD

**Issue by visious25** [RPCS3/rpcs3#14594]
### Quick summary

Hi, the game freezing in menu.

### Details

Metal Gear Solid 4 - Guns of The Patriots (USA)

### Attach a log file

[Termilal - Output.txt](https://github.com/RPCS3/rpcs3/files/12485640/Termilal.-.Output.txt)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12486592/RPCS3.log)

### System configuration

OS: Arch Linux x86_64
Host: Dell G3 3779
Kernel: 6.4.12-zen1-1-zen
Shell: bash 5.1.16
Resolution: 1920x1080
CPU: Intel i7-8750H (12) @ 4.100GHz
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630]
GPU: NVIDIA GeForce GTX 1050 Ti Mobile
NVIDIA Driver: 535.104.05
Memory: 3062MiB / 31829MiB

**Comment by FlexBy420** [comment]
Not using proper settings + canary patch. MGS4 is already known to be freezing a lot

**Comment by visious25** [comment]
I have the default settings.

**Comment by FlexBy420** [comment]
And MGS4 doesn't run properly on default settings. If you need support go to discord, github is not a place for support.

**Comment by visious25** [comment]
okay

**Comment by visious25** [comment]
MGS4 using custom settings + canary patch is not working for firmware 4.90. Canary patch is working for  firmware 4.89, 4.88, 4.87.
