### ISSUE TITLE
no puedo jugar con volante

### ISSUE THREAD

**Issue by kikojap** [RPCS3/rpcs3#14593]
### Quick summary

hola no consigo configurar ningun volante 

### Details

#

### Attach a log file

#

**Comment by MSuih** [comment]
1. We only accept issues in English.
2. RPCS3 doesn't support generic wheels, but if you have usb wheel that is compatible with the game (on ps3) you can pass it to game by [following these instructions](https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories).
3. If you can write in english and need further help or support, join our Discord.
