### ISSUE TITLE
Cannot launch RPCS3 on iMac 12.6.1 Monterrey

### ISSUE THREAD

**Issue by AudreyGwen** [RPCS3/rpcs3#14609]
### Quick summary

Hello, I've just updated my iMac from Catalina to Monterey but it said the message : rpscs3 quit unexpectedly. The problem details as followed:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               rpcs3 [3081]
Path:                  /Applications/RPCS3.app/Contents/MacOS/rpcs3
Identifier:            net.rpcs3.rpcs3
Version:                ()
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-09-03 03:40:27.0332 +0700
OS Version:            macOS 12.6.1 (21G217)
Report Version:        12
Anonymous UUID:        50F03ADD-EA1F-4204-2CD5-B9917D9B300D

Time Awake Since Boot: 4800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@loader_path/../../../../opt/libpng/lib/libpng16.16.dylib'
Referenced from: '/Applications/RPCS3.app/Contents/Frameworks/libfreetype.6.dylib'
Reason: tried: '' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	         0x5a9198e __abort_with_payload + 10
1   dyld                          	         0x5aa7a72 abort_with_payload_wrapper_internal + 80
2   dyld                          	         0x5aa7aa4 abort_with_payload + 9
3   dyld                          	         0x5a55699 dyld4::halt(char const*) + 615
4   dyld                          	         0x5a515b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
5   dyld                          	         0x5a504e4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7bfefdbd8  rdx: 0x00007ff7bfefe040
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7bfefdc20  rsp: 0x00007ff7bfefdbd8
   r8: 0x00007ff7bfefdc40   r9: 0x0000000000000000  r10: 0x000000000000008e  r11: 0x0000000000000246
  r12: 0x000000000000008e  r13: 0x00007ff7bfefe040  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x0000000005a9198e  rfl: 0x0000000000000246  cr2: 0x0000000005c55000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
         0x5a4b000 -          0x5ab6fff dyld (*) <7b87a986-a153-33c4-8470-d56410b7f9d5> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=82.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=82.5M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
ObjC additional data                15K        1 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                            91.8M      323 
__DATA_CONST                      21.2M      231 
__DATA_DIRTY                       485K       85 
__FONT_DATA                          4K        1 
__LINKEDIT                       667.4M       86 
__TEXT                           416.7M      343 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                              1.2G     1077 

-----------
Full Report
-----------

{"app_name":"rpcs3","timestamp":"2023-09-03 03:40:27.00 +0700","app_version":"","slice_uuid":"bcd37d93-ad10-3ff5-abec-267e523336da","build_version":"","platform":1,"bundleID":"net.rpcs3.rpcs3","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.1 (21G217)","incident_id":"F37AA891-1EC1-482D-8783-C25DC25107A1","name":"rpcs3"}
{
  "uptime" : 4800,
  "procLaunch" : "2023-09-03 03:40:26.9702 +0700",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac18,3",
  "procStartAbsTime" : 4864031035146,
  "coalitionID" : 3424,
  "osVersion" : {
    "train" : "macOS 12.6.1",
    "build" : "21G217",
    "releaseType" : "User"
  },
  "captureTime" : "2023-09-03 03:40:27.0332 +0700",
  "incident" : "F37AA891-1EC1-482D-8783-C25DC25107A1",
  "bug_type" : "309",
  "pid" : 3081,
  "procExitAbsTime" : 4864093722797,
  "cpuType" : "X86-64",
  "procName" : "rpcs3",
  "procPath" : "\/Applications\/RPCS3.app\/Contents\/MacOS\/rpcs3",
  "bundleInfo" : {"CFBundleShortVersionString":"","CFBundleVersion":"","CFBundleIdentifier":"net.rpcs3.rpcs3"},
  "storeInfo" : {"deviceIdentifierForVendor":"30F60B85-F55B-517A-A4F9-214DFD744886","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "net.rpcs3.rpcs3",
  "crashReporterKey" : "50F03ADD-EA1F-4204-2CD5-B9917D9B300D",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '@loader_path\/..\/..\/..\/..\/opt\/libpng\/lib\/libpng16.16.dylib'","Referenced from: '\/Applications\/RPCS3.app\/Contents\/Frameworks\/libfreetype.6.dylib'","Reason: tried: '' (no such file), '' (no such file), '' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":54685,"threadState":{"r13":{"value":140702053818432},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140702053817408},"cr2":{"value":96817152},"rdx":{"value":140702053818432},"r10":{"value":142},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":94968206,"matchesCrashFrame":1},"rbp":{"value":140702053817376},"rsp":{"value":140702053817304},"r12":{"value":142},"rcx":{"value":140702053817304},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":289166,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":379506,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":379556,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":0},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":0},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 94679040,
    "size" : 442368,
    "uuid" : "7b87a986-a153-33c4-8470-d56410b7f9d5",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703321899008,
  "size" : 19331678208,
  "uuid" : "57de9b7b-39b3-3557-8aed-37ac450fa1f3"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=82.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=82.5M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nObjC additional data                15K        1 \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                            91.8M      323 \n__DATA_CONST                      21.2M      231 \n__DATA_DIRTY                       485K       85 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       667.4M       86 \n__TEXT                           416.7M      343 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                              1.2G     1077 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000062
    },
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "634710168e8be655c1316aaa"
      },
      "deploymentId" : 240000231
    }
  ],
  "experiments" : [

  ]
}
}

Model: iMac18,3, BootROM 499.40.2.0.0, 4 processors, Quad-Core Intel Core i5, 3,8 GHz, 8 GB, SMC 2.41f2
Graphics: Radeon Pro 580, Radeon Pro 580, PCIe, 8 GB
Display: iMac, Retina 5K (5120 x 2880), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 4 GB, DDR4 SO-DIMM, 2400 MHz, 0x80AD, 0x484D413835315336414652364E2D554820202020
Memory Module: BANK 1/DIMM0, 4 GB, DDR4 SO-DIMM, 2400 MHz, 0x80AD, 0x484D413835315336414652364E2D554820202020
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x16F), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD ST2000DM001, 2 TB
USB Device: USB30Bus
USB Device: USB2.0 Hub
USB Device: USB 10/100 LAN
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Cintiq 16 HUB
USB Device: Single RS232-HS
USB Device: USB Receiver
USB Device: USB3.0 Hub
Thunderbolt Bus: iMac, Apple Inc., 41.5

I'm not sure why it doesn't work. Can anyone help me solve this? Thank you.

### Attach a log file

none yet.

**Comment by shangjun2x** [comment]
me too

**Comment by nastys** [comment]
Please try this build #14612 
https://api.cirrus-ci.com/v1/artifact/task/5350710179528704/Artifact/artifacts/rpcs3-v0.0.29-15588-8408bf27_macos.dmg

**Comment by padic-dev** [comment]
I was able to fix this issue for latest official release by updating libpng16.16.dylib

$ brew update
$ brew reinstall libpng

** On my system I had to fix a permission issue to allow brew to update the package:
 $ sudo chown -R $(whoami) /usr/local/lib/pkgconfig
