### ISSUE TITLE
[Regression] Unchated 3 - Crashes in Chapter 15

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#14613]
### Quick summary

Once you complete the chapter 14, the emulator itself closes, and if you're gonna to load the save, it crashes and the emulator closes 

### Details

Working 0.0.29-15526
![image](https://github.com/RPCS3/rpcs3/assets/78843189/539c5802-8a94-4f66-9bb3-9eb25129d3f7)

Broken 0.0.29-15528 (https://github.com/RPCS3/rpcs3/pull/14547)
https://github.com/RPCS3/rpcs3/assets/78843189/e1ebd4c6-2240-422c-9a57-221f2a324834

### Build with regression

0.0.29-15528

### Attach two log files

[UC3_Working.log.gz](https://github.com/RPCS3/rpcs3/files/12508438/UC3_Working.log.gz)

UC3 Broken -> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12508446/RPCS3.log)

### System configuration

Windows 10 22H2
Intel Core i7-8700
15.93 GiB RAM
GPU: NVIDIA GeForce GTX 1070 Ti (537.13)

**Comment by elad335** [comment]
Test #14616
