### ISSUE TITLE
[Regression] Test Drive Unlimited 2 crashes after the two intro sequences.

### ISSUE THREAD

**Issue by cas-1092** [RPCS3/rpcs3#14614]
### Quick summary

When loading up, after both the Atari and Eden Games intros, the game crashes the emulator completely.
This seems to have gone unnoticed for quite some time.

### Details

v0.0.24-14135-60fc90bb works.
![Screenshot 2023-09-04 092130](https://github.com/RPCS3/rpcs3/assets/137835937/ad5cff88-c8c2-4f5e-8539-deadbc76cc01)

v0.0.24-14141-d686b48f crashes.

https://github.com/RPCS3/rpcs3/assets/137835937/63b73918-6e4e-41a1-a266-2948028819e3

Every other build afterwards behaves the same.

### Build with regression

v0.0.24-14141-d686b48f

### Attach two log files

14135 (Working) - [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12514272/RPCS3.log.gz)

14141 (Broken) - [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12514223/RPCS3.log)

### System configuration

Intel Core i5 11400F | NVIDIA GTX 1660 SUPER (driver 536.67.0.0) | 15.86 GB of RAM | Windows 11 Home Version 22H2

### Other details

Both of the logs were following the wiki settings.

**Comment by cas-1092** [comment]
Sorry, was told to make this issue in the discord, will close now.

**Comment by elad335** [comment]
But the referenced issue says Intel only and your GPU is GTX 1660.
