### ISSUE TITLE
Grand Theft Auto IV - Audio stutters during gameplay

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#14615]
### Quick summary

The audio stutter commonly occurs during gameplay, sometimes it even happens during cutscenes aswell.

### Details

Heres a comparison between RPCS3 and the Real PS3.
I tried lowering the audio buffer duration atleast 20ms just to try reducing the stutter, but nothing worked.

RPCS3:

https://github.com/RPCS3/rpcs3/assets/125112932/724e11d6-3c4d-409f-8815-e6baf9ecc261

Real PS3:
https://www.youtube.com/watch?v=pOnjepaT400
Play the video at 4:23.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12514610/RPCS3.log.gz)

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 537.13.0.0 | Windows 10 Pro 22H2

**Comment by FlexBy420** [comment]
You have a lot of non-default settings, also GTA 4 needs accurate xfloat which kills performance so the stuttering audio may be caused by that

**Comment by Ordinary205** [comment]
Using approximate xfloat does remove the stutter, even though it is still mandatory.
