### ISSUE TITLE
Metal Gear Solid V: Ground Zeroes - Flickering Shadow Textures

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#14611]
### Quick summary

The shadow textures starts to flicker at the beginning of the mission.

### Details

I tried enabling AccurateXFloat+WCB+RDB+WDB+RCB+AllowHostGPU+ForceCPUBlitEmulation, but nothing solves the issue.
Heres a comparison between RPCS3 and the Real PS3.

RPCS3:

https://github.com/RPCS3/rpcs3/assets/125112932/67ded11c-85cd-4f2c-a29f-b6f24ba748bf

Real PS3:
https://www.youtube.com/watch?v=UZfTpEb2Fvg&list=PLJKEKeMcejOxGQrnbRpbHi-sG4fwuI6S3

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12505655/RPCS3.log.gz)

### Attach capture files for visual issues

https://mega.nz/folder/waBSFTrb#65Xt8mB-QzdQbikE6VqMjA

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 537.13.0.0 | Windows 10 Pro 22H2

**Comment by FlexBy420** [comment]
0.0.29-15724
Tried with Handle RSX memory tiling, still nothing.

**Comment by FlexBy420** [comment]
Setting the shader quality to low fixes this issue.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13400446/RPCS3.log.gz)

https://github.com/RPCS3/rpcs3/assets/68403300/b07db050-ca6e-45a8-818f-595ec03d3039
