### ISSUE TITLE
 Vulkan API call failed with unrecoverable error: requested extension not available

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#14628]
### Quick summary

I am using a ROG Ally on Nobara (Steam Deck edition): 

* ROG Ally specs: https://rog.asus.com/us/gaming-handhelds/rog-ally/rog-ally-2023/spec/
* Nobara:  https://nobaraproject.org/

Nobara (Steam Deck edition) comes with Valve's gamescope, which allows you to play in a "Game Mode" similar to the Steam Deck. 

When I launch a game through RPCS3 (AppImage) using gamescope, I get: ` Vulkan API call failed with unrecoverable error: requested extension not available`

Image:

![image](https://github.com/RPCS3/rpcs3/assets/108900299/5dd91eb5-e09e-499a-903e-19ca69dc0064)

When I launch a game through RPCS3 (AppImage) outside of gamescope, it launches fine. 

I am not sure if this is an RPCS3 bug or a gamescope bug so I apologize if this is not RPCS3 related at all. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12528295/RPCS3.log)

### System configuration

https://rog.asus.com/us/gaming-handhelds/rog-ally/rog-ally-2023/spec/

**Comment by AniLeo** [comment]
Seems like an issue trying to call https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateXlibSurfaceKHR.html

Why is it not available through gamescope I wonder? Are you using X11 or Wayland in your OS?

**Comment by AniLeo** [comment]
Now the million dollar question is why does it enter HAVE_X11 code when running under gamescope if you're running Wayland, that doesn't make sense

Steam Deck is also Wayland and you don't have this issue there when trying to run RPCS3 on gamescope

**Comment by Xipher-Zero** [comment]
Gamescope-session just updated recently and now I am getting this same error. Worked prior to the gamescope-session and gamescope update. I believe that the session changed to solely wayland from XWayland, but not clear.

**Comment by kd-11** [comment]
This is a problem with 3rd party integration, so I'll close this ticket. There is a ticket tracking the bundled appimages not launching under wayland here: https://github.com/RPCS3/rpcs3/issues/14576. That issue should only affect appimages however.
