### ISSUE TITLE
can't launch ps3 interface bios

### ISSUE THREAD

**Issue by mehdi047** [RPCS3/rpcs3#14634]
### Quick summary

app stuck when launching ps3 interface bios

### Details

when trying to launch the ps3 interface bios (and sometimes games either) the app is always stuck at linking ppu modules file 119 of 119 and module 64 of 366 and the log just saying this: "S SPU: SPU Runtime: Built the interpreter." I'm currently using the latest version of the app release till now
the log file is attached

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12563635/RPCS3.log)

### System configuration

windows 11 ver. 22h2 (OS build 22621.2215)
ASUS laptop g733zw

**Comment by Darkhost1999** [comment]
Can you make this a regression report instead of a bug report?
As in working here
https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-1c8f1b2c27d578acee3020d2caba542dc1dc50df/rpcs3-v0.0.29-15587-1c8f1b2c_win64.7z
Not working here
https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-6dcdf6ec7607458dde1d8ae2db820fd3ac01a703/rpcs3-v0.0.29-15598-6dcdf6ec_win64.7z
But which specific 1?
The not working I mentioned is when I started seeing the issue myself but I went to do regression testing with clean folders and got it to work.
So is the issue consistent or only occurs sometimes?

**Comment by woj1993** [comment]
Hi I also have this problem. I didn't try to launch bios but I was trying to launch games. All that I tested hang on SPU Runtime: Built the interpreter.
AMD Ryzen 7 5800X 8-Core Processor 
32Gb of ram
Nvidia 3060 Ti
Also Windows 11 (same version as medhi have)

**Comment by Darkhost1999** [comment]
Which games? Can you provide logs for those too? It'll help in diagnosing and resolving the issue.

**Comment by ItsALH** [comment]
> Can you make this a regression report instead of a bug report? As in working here https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-1c8f1b2c27d578acee3020d2caba542dc1dc50df/rpcs3-v0.0.29-15587-1c8f1b2c_win64.7z Not working here https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-6dcdf6ec7607458dde1d8ae2db820fd3ac01a703/rpcs3-v0.0.29-15598-6dcdf6ec_win64.7z But which specific 1? The not working I mentioned is when I started seeing the issue myself but I went to do regression testing with clean folders and got it to work. So is the issue consistent or only occurs sometimes?

I'm on 15608 and 100% I can reproduce what the OP says. However, disabling PPU/SPU Precompilation allows me to boot the vsh.

**Comment by woj1993** [comment]
@Darkhost1999 I always start from clean cache. Tested these games and they all failed to boot. What is funny it seems that compilation is processing to all_modules - 2 and then hangs.
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12565402/RPCS3.log.gz) Game: BAYONETTA First Climax Demo [NPEB90193]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565412/RPCS3.zip) Game: Dead Space™ Dismemberment Demo [NPUB90187]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565427/RPCS3.zip) Game: Dragon Ball Z: Battle of Z DEMO [NPEB90517]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565438/RPCS3.zip) Game: DRAGON BALL Z: BURST LIMIT [NPEB90074]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565455/RPCS3.zip) Game: Dragon Ball: Raging Blast 2 Demo [NPEB90287]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565466/RPCS3.zip) Game: GOW3 E3 DEMO 2009 [NPUA70080]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565474/RPCS3.zip) Game: Heavenly Sword™ Demo [NPUA80103]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565486/RPCS3.zip) Game: NARUTO SHIPPUDEN: Ultimate Ninja STORM 3 DEMO [NPEB90474]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565488/RPCS3.zip) Game: NARUTO SHIPPUDEN: Ultimate Ninja STORM Revolution - Demo [NPEB90541]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565495/RPCS3.zip) Game: NARUTO™: Ultimate Ninja® STORM Demo [NPEB90080]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565497/RPCS3.zip) Game: ＮＡＲＵＴＯ－ナルト－ 疾風伝 ナルティメットストーム２ 体験版 [NPJB90253]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565502/RPCS3.zip) Game: Ni no Kuni: Wrath of the White Witch – Journey to Another World [NPEB90452]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565508/RPCS3.zip) Game: Ratchet and Clank® Future: Tools of Destruction™ - Demo Version [NPUA98153]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565513/RPCS3.zip) Game: Sly Cooper: Thieves in Time™ Demo [NPUA70250]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565542/RPCS3.zip) Game :) : The PS3 Interface (XMB, or VSH) [vsh.self]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565561/RPCS3.zip) Game: Uncharted: Drake's Fortune™ - Demo [NPUA98103]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12565583/RPCS3.zip) Game: Zuma [NPUA30003]
**My config file:** [config.zip](https://github.com/RPCS3/rpcs3/files/12565585/config.zip)
**This are games that started for me:**
LittleBigPlanet™ Demo [NPEA00147]
Scogger HD [SCOG00001]

**Comment by woj1993** [comment]
So I found workaround.
It seems that if I load a game and allow it to compile till it hangs on compilation and then close emulator and load the same game it will start to boot up. Also after doing workaround once all other games start to work. It seems like there is a problem with compilation of common modules?

**Comment by Darkhost1999** [comment]
Retest on latest master

**Comment by woj1993** [comment]
It seems to help. Tomorrow I will test it for every game but right now it started 1 problematic game from clean cache.

**Comment by Megamouse** [comment]
Assuming fixed, based on the last commit
