### ISSUE TITLE
socom confrontation 

### ISSUE THREAD

**Issue by MrTr1x** [RPCS3/rpcs3#14638]
### Quick summary

game froze while playing kasbah was spectating 

### Details

link fixed

### Attach a log file

https://drive.google.com/file/d/1grv6T-adQiEv1zJA1d4IKp5cAWI-EAkT/view?usp=drive_link

### System configuration

ryzen 5800x 3080ti

**Comment by Darkhost1999** [comment]
1 The error message gives you the solution.
2 Using desktop to store RPCS3 where onedrive if installed can create file system instability.
3 Using a known broken copy of the game and needs to read the Quickstart guide to learn how to obtain a working copy.
