### ISSUE TITLE
socom confrontation BCUS98152

### ISSUE THREAD

**Issue by MrTr1x** [RPCS3/rpcs3#14637]
### Quick summary

game froze and crashed along with the emulator 

### Attach a log file

https://drive.google.com/file/d/1grv6T-adQiEv1zJA1d4IKp5cAWI-EAkT/view?usp=drive_link

### System configuration

ryzen 5800x 3080ti

**Comment by AniLeo** [comment]
Log file link doesn't work, no details in the issue at all on what happened exactly besides saying it crashed, closing as Invalid
