### ISSUE TITLE
夏色ハイスクル青春白書 | Natsuiro High School Seishun Hakusho [BLJS10273] Darker brightness

### ISSUE THREAD

**Issue by reyjkw** [RPCS3/rpcs3#14645]
### Quick summary

everything is darker than usual except UI and menus

![image](https://github.com/RPCS3/rpcs3/assets/71224766/88be804d-8f0d-47e0-88e2-62bbfa3b874f)
![image](https://github.com/RPCS3/rpcs3/assets/71224766/e721c873-5dcc-41b3-8f5f-192255f752f0)
![image](https://github.com/RPCS3/rpcs3/assets/71224766/1267d9e0-9d88-4459-bd3b-3ff19a269c8d)
![image](https://github.com/RPCS3/rpcs3/assets/71224766/c60da8b4-d67d-4e6b-8890-502c6ea5feca)
![image](https://github.com/RPCS3/rpcs3/assets/71224766/dafe3e22-3ff1-4024-8661-ea8089ab2226)

### Details

as a refference heres gameplay
https://youtu.be/DTwa63YG4KQ
i know its ps4 but im pretty sure thats not the problem

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12602072/RPCS3.log)

**Comment by Asinin3** [comment]
And have you tried write color buffers and or wcb + other depth options on advanced tab?

**Comment by FlexBy420** [comment]
WCB is in gpu tab
