### ISSUE TITLE
Grand Theft Auto V - VK_ERROR_DEVICE_LOST during prologue mission

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#14652]
### Quick summary

This crash happens to me all the time when playing at the beginning of prologue mission.

### Details

Heres an example of when the game crashes.
![Grand Theft Auto V](https://github.com/RPCS3/rpcs3/assets/125112932/1d63d609-f626-412c-a816-d2c4f9cb6473)

Fatal error:
![GTA 5 Fatal error](https://github.com/RPCS3/rpcs3/assets/125112932/b15fda36-febb-41c7-aaed-b3a41bfbf652)

Error:
F {RSX [0x02023fc]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKQueryPool.cpp:45[:4], in function poke_query)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:114[:24], in function die_with_error)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12642240/RPCS3.log.gz)

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 537.34.0.0 | Windows 10 Pro 22H2

**Comment by ynhhoJ** [comment]
If this specific error happens to you at the same moment, can you try to do this: https://github.com/RPCS3/rpcs3/issues/12244#issuecomment-1188251468 ? 

Full issue: https://github.com/RPCS3/rpcs3/issues/12244

**Comment by Ordinary205** [comment]
I manage to get it to work with below 10 FPS, I will update soon if I got the crash.
![GTA 5 Low FPS](https://github.com/RPCS3/rpcs3/assets/125112932/3145b131-37ae-4ae3-8f96-e6d33e602d7d)

**Comment by Ordinary205** [comment]
Still happens at the exact moment when installing the vulkan SDK.
![GTA 5 vulkan crash](https://github.com/RPCS3/rpcs3/assets/125112932/77925840-20d4-434e-8930-c86c6180dfa6)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12647460/RPCS3.log.gz)

**Comment by ynhhoJ** [comment]
I think we should tag @kd-11

**Comment by kd-11** [comment]
This is a known RSX bug that I've never been able to reproduce. I'll try to repro, failing which I'll link a special build with breadcrumbs enabled. Hopefully I can reproduce this time.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/14657
