### ISSUE TITLE
[Regression] SSX Green/Blue Smoke Graphical Bug On/After v0.0.21-13531 (#11867)

### ISSUE THREAD

**Issue by jeremybris** [RPCS3/rpcs3#14659]
### Quick summary

On/after [v0.0.21-13531](https://rpcs3.net/compatibility?b&p=42) (PR [#11867](https://github.com/RPCS3/rpcs3/pull/11867)) Smoke is green, should be white/grey, specifically, on the level **_"Explore" > "Alaska" > "Foraker" > "Invincible: Race it"_**. Later, it regressed again, from green to blue smoke.

My save game, if needed to replicate: 

- [BLUS308490000A.zip](https://github.com/RPCS3/rpcs3/files/12668732/BLUS308490000A.zip)

### Details

| RPCS3 Version | RPCS3 Commit | RSX Capture | Screenshot |
| ------------- | ------------- | ------------- | ------------- |
| Before v0.0.21-13531 | ------------- | [Before RSX Capture](https://drive.google.com/file/d/16TV32VHE2AO607ULpt099FE63VHVvDgp/view?usp=sharing) | ![Before](https://github.com/RPCS3/rpcs3/assets/11889359/e35078cc-da33-48b0-9a6d-eb9403c9987c) |
| After v0.0.21-13531 | PR [#11867](https://github.com/RPCS3/rpcs3/pull/11867)| [After RSX Capture](https://drive.google.com/file/d/1f3upbhJgtIJAAQhaDykcBbMCOQVZbFQZ/view?usp=sharing) | ![After](https://github.com/RPCS3/rpcs3/assets/11889359/66b4fb08-8165-47fc-a422-71042ab40449) |

### System configuration

**Settings**:
- Default settings of the emulator, with "Vulkan".

**Specs**:
- CPU - AMD 7900 (non-x)
- GPU - AMD 6900x
- Motherboard - Asus 670 Wifi

### Other details

The smoke regressed again from green to blue. I can not find the build that regressed it because SSX stopped going in-game briefly. I found it's between [build 15184 - 15312](https://rpcs3.net/compatibility?b&p=9), probably one of kd-11's PRs:

| RPCS3 Version | RPCS3 Commit | RSX Capture | Screenshot |
| ------------- | ------------- | ------------- | ------------- |
| Before v0.0.28-15183 | ------------- | ------------- | ![After](https://github.com/RPCS3/rpcs3/assets/11889359/72d91631-3576-45a5-80b3-9236e57cec02) |
| After v0.0.28-15312 | (Maybe PR #14104 ?? Explanation below.) | [Blue Smoke RSX Capture](https://drive.google.com/file/d/1cA2qGxtr3fqlALEtjimmBq0h9FV2LRic/view?usp=sharing) | ![Screenshot 2023-09-19 213517](https://github.com/RPCS3/rpcs3/assets/11889359/1919ec46-19b7-4eac-8749-e137cdf4ba84) |

In addition, a different smoke effect is now missing (probably related, went missing at the same time:

| RPCS3 Version | Screenshot |
| ------------- | ------------- |
| Before v0.0.28-15183 | ![Screenshot 2023-09-19 214022](https://github.com/RPCS3/rpcs3/assets/11889359/8b8ead9a-ee87-4d65-95b7-7463b0e074bf) |
| After v0.0.28-15312 | ![Screenshot 2023-09-19 213123](https://github.com/RPCS3/rpcs3/assets/11889359/d9033299-da67-45ec-98df-9e8ec9d4b664) |

**Edit**: Tried to find the second regression. Of kd-11's ~7 PR's during this time period, only [this PR](https://github.com/RPCS3/rpcs3/pull/14104/files) changes similar files to PR #11867 (green smoke). They both have changes to "rpcs3/Emu/RSX/Program/GLSLCommon.cpp", lines 23-500.

**Comment by ItsALH** [comment]
Cannot reproduce on latest master on my savefile. The save you provided is the ghost data, not your profile, so I couldn't try that. I also don't know how you're playing a daytime stage at night 🤔 

Log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12668571/RPCS3.log)

![image](https://github.com/RPCS3/rpcs3/assets/108736840/c969f31a-f5d3-4bc7-93c5-781c2b3afe53)
![image2](https://github.com/RPCS3/rpcs3/assets/108736840/0257ac03-1cb3-4dbb-9ded-1af233230c3a)

**Comment by jeremybris** [comment]
> Cannot reproduce on latest master on my savefile. The save you provided is the ghost data, not your profile, so I couldn't try that. I also don't know how you're playing a daytime stage at night 🤔
> 

Ah, thanks for the comment. Maybe an AMD GPU bug. To play at night, you click on "Exploration" in the main menu. It's a level in Alaska. I re-uploaded the correct save data.

**Comment by ItsALH** [comment]
> To play at night, you click on "Exploration" in the main menu. It's a level in Alaska. I re-uploaded the correct save data.

Just started a new save and it's night time too, so my only guess is that maybe times changed because of the Online mode? Since my save is from back when I played in PS3 guess I'm stuck with these 😄 

Also still can't reproduce even with your save, so maybe it's only on AMD GPUs like you said 😕

**Comment by jeremybris** [comment]
This appears to be fixed for me on my 6900 xt, so closing.
