### ISSUE TITLE
Linux Dualshock 3 motion sensor y not centered

### ISSUE THREAD

**Issue by anonyme-x22** [RPCS3/rpcs3#14656]
### Quick summary

Hello,

I'm trying to use a dualshock 3 on latest rpcs3.
The motion sensors does not react correctly.

Thanks in advance,
Have a good day,
Rgds,

### Details

Put udev rules.
Controller recognized all is ok even the motion sensor except G axis which is grayed.
They works but the axis are not centered, so for example on little big planet the head of the sackbot is pointing uppright?
Moving the joystick does move the head but with always this uppright offset?
This issue is there till one years.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12651130/RPCS3.log)

### Attach capture files for visual issues

![image](https://github.com/RPCS3/rpcs3/assets/55886693/56b478e6-89b8-4f25-954f-b7c5a454844d)

### System configuration

Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz | 8 Threads | 7.21 GiB RAM | TSC: 3.637GHz | AVX
AMD Radeon R9 200 / HD 7900 Series (RADV TAHITI)

**Comment by Megamouse** [comment]
This sounds like an issue with your controller or driver.
Post a screenshot with the motion sensor window when the controller is flat on the table.

**Comment by ItsALH** [comment]
Just tried and same thing for me, also tried with DS4 out of curiosity and it's fine with that one despite reporting similar values (except for G ofc):

| DS3 | DS4 |
|--------|--------|
| ![image](https://github.com/RPCS3/rpcs3/assets/108736840/918cb796-a8d0-4e5c-87c3-2cc075685702) | ![image](https://github.com/RPCS3/rpcs3/assets/108736840/1c5549fe-7e71-4de4-8bcf-a512a1ae4250) |

**Comment by Megamouse** [comment]
No issue here on windows:
| DS3  |
|--------|
|![image](https://github.com/RPCS3/rpcs3/assets/23019877/b9acd7e5-5c8f-4267-861a-2e18a96be71b)|

**Comment by ItsALH** [comment]
Looks like the G Axis isn't implemented in dshidmini, this is with the official Sony drivers:
![image](https://github.com/RPCS3/rpcs3/assets/108736840/47623f68-3e3d-42d3-b018-052a7e642e20)

**Comment by mirh** [comment]
Gyro should be [coming](https://github.com/nefarius/DsHidMini/issues/217)
As for your drift issues.. Did you try [calibration](https://old.reddit.com/r/DS4Windows/comments/r18j69/how_do_i_use_the_gyro_calibration/)?

**Comment by anonyme-x22** [comment]
No issue with the joystick , everything is fine on windows, i haven't installed anydriver on linux , only the rules as requested on rpcs3 motion faq.

**Comment by Megamouse** [comment]
I'm closing this since there is no issue with the DS3 handler.

**Comment by anonyme-x22** [comment]
How do we fix DSHidMini ?

**Comment by SiriusVI87** [comment]
The reason for this problem seems to be that there are certain Dual Shock 3 variants that work and some that don't. I have bought 7 used Dual Shock 3 controllers. 3 of them have a working g axis with DsHidMini, 4 don't.

All of them work perfectly with the original Sony drivrs. The problem with those drivers is that to use them on Windows 11, you must disable the core isolation security feature, and also they don't support wireles over bluetooth.

**Comment by SiriusVI87** [comment]
> Well, if you say so, I'm probably guessing they are fakes? If you are nice (and especially explain that sixaxis.sys is fine) maybe nefarius may be available to take a look at them.

Tell me what I have to do. I'm glad to help and get this problem fixed. I am on Windows 11, though, not Linux.

I do not believe the controllers I bought are fake. I checked for all the typical signs and even opened up the controllers. They all seem to be legit DS3 controllers.

Plus, as I said, with the original Sony drivers, all of them have a working g axis.

**Comment by mirh** [comment]
Uh, lol. Apparently he isn't accepting issues from external people. 
Apparently the only venue left is [his discord](https://discord.nefarius.at/).

**Comment by anonyme-x22** [comment]
The issue is in the linux driver Hid Sony which does not report the ABS_G!

Input device ID: bus 0x3 vendor 0x54c product 0x268 version 0x8111
Input device name: "Sony PLAYSTATION(R)3 Controller Motion Sensors"
Supported events:
  Event type 0 (EV_SYN)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value     -5
      Min     -512
      Max      511
      Fuzz       4
      Resolution     113
    Event code 1 (ABS_Y)
      Value    116
      Min     -512
      Max      511
      Fuzz       4
      Resolution     113
    Event code 2 (ABS_Z)
      Value     18
      Min     -512
      Max      511
      Fuzz       4
      Resolution     113
Properties:
  Property type 6 (INPUT_PROP_ACCELEROMETER)
Testing ... (interrupt to exit)

So, actually no one is capable of having motion censor with a DS3 on linux including G Axis!

**Comment by nefarius** [comment]
> Uh, lol. Apparently he isn't accepting issues from external people. Apparently the only venue left is [his discord](https://discord.nefarius.at/).

Correct, I've had enough of the spam. Thank Githubs still lousy permission system for that, I can't make it any better with the tools given.

**Comment by SiriusVI87** [comment]
> The issue is in the linux driver Hid Sony which does not report the ABS_G!
> 
> Input device ID: bus 0x3 vendor 0x54c product 0x268 version 0x8111 Input device name: "Sony PLAYSTATION(R)3 Controller Motion Sensors" Supported events: Event type 0 (EV_SYN) Event type 3 (EV_ABS) Event code 0 (ABS_X) Value -5 Min -512 Max 511 Fuzz 4 Resolution 113 Event code 1 (ABS_Y) Value 116 Min -512 Max 511 Fuzz 4 Resolution 113 Event code 2 (ABS_Z) Value 18 Min -512 Max 511 Fuzz 4 Resolution 113 Properties: Property type 6 (INPUT_PROP_ACCELEROMETER) Testing ... (interrupt to exit)
> 
> So, actually no one is capable of having motion censor with a DS3 on linux including G Axis!
> 
> I've seen on nefarius discord a topic about it which is still open. Apparently The G axis has to be calculated!
> 
> https://discord.com/channels/346756263763378176/1268631663018250300
> 
> On the sony drivers it's calculated which explain why no issue on windows!
> 
> This said as the sony drivers do it, it seems that it's on the side of the Hid_sony drivers!
> 
> Rgds,

Not quite.

There seem to be different kinds of DS3 controllers that behave differently.

I have bought a total of 12 DS3 used controllers, and 5 of them work with DSHidMini, including G Axis on windows. 7 have the G Axis issue.

But all 12 work with the original Sony drivers.

**Comment by nefarius** [comment]
> There seem to be different kinds of DS3 controllers that behave differently.
> 
> I have bought a total of 12 DS3 used controllers, and 5 of them work with DSHidMini, including G Axis on windows. 7 have the G Axis issue.
> 
> But all 12 work with the original Sony drivers.

That's correct, not every DS3 is designed equal, starting with certain revisions they changed the chips they used and/or their positions on the PCB so each controller power up/connection the motion exchange needs to be calibrated so the data reported is actually in correct relation to the DS3 resting position. The Sony sixaxis.sys Windows driver has the logic in it to query the type of motion revision, the HID feature requests to perform calibration against the volatile EEPROM ish memory in the controller and calculate the usable axis information using the accelerometer X, Y and Z G values and the Gyro for Yaw IIRC. This logic is not present in DsHidMini (details about this can also be found in the DsHidMini issue tracker).

If we know how
- to identify the various DS3 revisions reliably
- perform calibration
- calculate the missing axis
and ultimately turn that into C for DsHidMini, we can have that fun feature also on Windows 😛

**Comment by nefarius** [comment]
> I have bought a total of 12 DS3 used controllers, and 5 of them work with DSHidMini, including G Axis on windows. 7 have the G Axis issue.
> 
> But all 12 work with the original Sony drivers.

If you feel bored @SiriusVI87 since you have a clean stock of different revisions you could take packet captures of all of them so we can at least preserve research material for whatever brave soul in the future can decipher them. Feel free to hop on my Discord for aid in how to do that.

Cheers
