### ISSUE TITLE
Illegal instruction & Segfault reading location

### ISSUE THREAD

**Issue by dekleva** [RPCS3/rpcs3#14653]
### Quick summary

HI, Im trying to game on my mac m1 max  since my ps3 is long dead. Im trying to run call of duty 3 which sould be fully supported, but i get this error:

```
Illegal instruction at 00007ff804658c5e (0x0f0b9090488d0558de1800488905e8df).
Thread: Main Thread.
```

Should be simple enough.. Am i doing somethig wrong?

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12642961/RPCS3.log)

Edit:
But after re-running it few times i now get comletely different error:

```
Segfault reading location 5f5f0079787a67e7 at 00007ff804096769.
Thread: Main Thread.
```

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12642971/RPCS3.log)

**Comment by AniLeo** [comment]
Invalid report, 2 weeks old build with non default settings without any explanation as to why they need to be changed
