### ISSUE TITLE
[Regression] SSX (Digital Only) Longer Load Times On/After 0.0.29-15521

### ISSUE THREAD

**Issue by jeremybris** [RPCS3/rpcs3#14658]
### Quick summary

~After PR [#14537](https://github.com/RPCS3/rpcs3/pull/14537) (v0.0.29-15521 and after) SSX, digital version only, can not go in-game.~ 

Load times are longer on the digital version, only.

### Details

| RPCS3 Version | RPCS3 Commit | RPCS3 Log | Screenshot |
| ------------- | ------------- | ------------- | ------------- |
| Before v0.0.29-15521 | ------------- | [RPCS3 Working.log](https://github.com/RPCS3/rpcs3/files/12667246/RPCS3.Working.log) | ![Before](https://github.com/RPCS3/rpcs3/assets/11889359/1fb42243-d14d-4f71-8de7-391cb73f656b) |
| After v0.0.29-15521 | PR [#14537](https://github.com/RPCS3/rpcs3/pull/14537) | [RPCS3 Not Working.log](https://github.com/RPCS3/rpcs3/files/12667247/RPCS3.Not.Working.log) | ![After](https://github.com/RPCS3/rpcs3/assets/11889359/daa99aca-215f-453a-9d69-3a5133ff1028) |

### System configuration

**Settings**:
- Default settings of the emulator, with "Vulkan".

**Specs**:
- CPU - AMD 7900 (non-x)
- GPU - AMD 6900x
- Motherboard - Asus 670 Wifi

### Other details

Disk version is good, only effects the NPUB, digital, version.

**Comment by elad335** [comment]
Maybebit just takes a long time?

**Comment by jeremybris** [comment]
> Maybe it just takes a long time? can you try waiting 20 minutes?

After 25 minutes, still nothing. Also, an intro movie used to play, but doesn't anymore.

**Comment by Shoegzer** [comment]
Seeing this here too.

Specs:
* OS: Linux Mint 21.2 / kernel 6.2
* CPU: Intel i7-10870
* GPU: Nvidia GTX 3070 / driver 535.104
* Commit: 2381e3323694d4f2b3dca713d3288d7e9cf6eeab

**Comment by jeremybris** [comment]
The original issue got fixed for me... but load times, only on the digital version, are longer now than they should be.

**Comment by elad335** [comment]
how much longer are they from PS3?

**Comment by jeremybris** [comment]
> how much longer are they from PS3?

### 1st load screen (from main menu to sub-menu)

- PS3 - **_N/A_**
- Non-Digital RPCS3 Version - **_10 seconds_**
- Digital RPCS3 Version - **_19 seconds_**

### 2nd load screen (from sub-menu to in-game)

- PS3 - **_29 seconds_**
- Non-Digital RPCS3 Version - **_6 seconds_** (-79.3% vs. PS3!)
- Digital RPCS3 Version - **_38 seconds_** (+23.6% vs. PS3!)

So, maybe the times are closer to PS3, but slower than they potentially could be? (I compared PS3 times from [this video](https://www.youtube.com/watch?v=BSF-WlX5-Ps)).

**Comment by elad335** [comment]
Can you provide lof of disc version?

**Comment by jeremybris** [comment]
> Can you provide a log of disc version?

[Digital Version RPCS3.log](https://github.com/RPCS3/rpcs3/files/13063900/Digital.Version.RPCS3.log) (38 seconds load screen)
vs.
[Disc Version RPCS3.log](https://github.com/RPCS3/rpcs3/files/13063901/Disc.Version.RPCS3.log) (6 seconds load screen)

**Comment by Shoegzer** [comment]
@jeremybris I can confirm as you have, that the main regression of not going ingame has been resolved.

I also experience longer load times than earlier builds, similar to what you've encountered.  A few questions:

1. Are your PS3-native tests for the digital or disc version?  Assuming digital, then it's possible RPCS3 is actually exhibiting *more* accurate behavior than earlier, and longer load times can be expected.  More accurate emulation and longer load times is of course better than less accurate emulation and shorter load times.  
2. Are the levels seleIected / assets loaded the same between your RPCS3 and PS3 tests? I wonder whether the difference between RPCS3/38 vs. PS3/29 seconds can be explained by this.
3. Are the tests from the same region?

**Comment by jeremybris** [comment]
I just used [this video](https://www.youtube.com/watch?v=BSF-WlX5-Ps) for testing. The levels are the same. Same region. 

The more interesting and reproducible part is the comparison between the digital and disc version of the game on RPCS3.
