### ISSUE TITLE
DX12: Chaos;Child (BLJM61269) black screen crash.

### ISSUE THREAD

**Issue by AndrewMisko** [RPCS3/rpcs3#1465]
rpcs3 version - v0.0.0.6-4092-ffb014c
Settings:

PPU Interpreter 2
SPU Interpreter fast

Video - DirectX 12
Audio - Xaudio2

LLE Modules:
cellAudio v1.1
cellFiber v1.1
cellSpursJq v1.1
cellSre v1.1

On DirectX 12 it doesn't go past black screen with FPS. On OpenGL it plays normally (5-10FPS though) I am including logs from both OpenGL and DirectX 12 runs. I had RSX logging turned on, because on first glance there is no difference in logs. But this line after stopping the emulator is suspicious:

```
F {rsx::thread} Exception: HRESULT = 0x80070057
(in file Emu\RSX\D3D12\D3D12Texture.cpp:90, in function `anonymous namespace'::upload_single_texture)
```

I guess it's something texture related. Can't say for sure, don't have much experience with DX or OpenGL.

Here are the logs (sorry for using GDrive, couldn't get GitHub to accept the file for some reason)
https://drive.google.com/file/d/0BxVvT3yrE2-bOERXVnlLV3Z6RVU/view?usp=sharing

**Comment by raven02** [comment]
@AndrewMisko , please retest with latest build using DX12 again.

**Comment by AndrewMisko** [comment]
@raven02 No go even on OpenGL now. Same settings. It does launch if libresc.prx is enabled though. Here is the log.

[chaoschild.zip](https://github.com/RPCS3/rpcs3/files/311954/chaoschild.zip)

**Comment by raven02** [comment]
Do you mean both DX12 and OGL are black screen now with FPS running ?

**Comment by AndrewMisko** [comment]
Not even black screen, just gray screen and the log stops at:
`·U {PPU[0x5] Thread (main_thread) [0x0017dd54]} cellResc TODO: cellRescGcmSurface2RescSrc(gcmSurface=*0x22a53c0, rescSrc=*0xd000fb00)
·U {PPU[0x5] Thread (main_thread) [0x0017de74]} cellResc TODO: cellRescSetSrc(idx=0x0, src=*0xd000fb00)
·U {PPU[0x5] Thread (main_thread) [0x0017ddf4]} cellResc TODO: cellRescSetConvertAndFlip(cntxt=*0x24f6000, idx=0x0)
·U {PPU[0x5] Thread (main_thread) [0x0017dd74]} cellResc TODO: cellRescSetWaitFlip()`

**Comment by Nezarn** [comment]
@AndrewMisko HLE Resc was removed in #1521 , if a game needs it then you need to LLE it.

**Comment by AndrewMisko** [comment]
Ah, well that's the problem then. With libresc there's no change. It's still black screen with fps meter.

**Comment by AniLeo** [comment]
Game has been reported working on DX12 now, therefore I'll be closing the issue.
If you have further issues please open a new issue.
