### ISSUE TITLE
[Regression] Recent builds failing on linux

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#14666]
### Quick summary

As the title implies, recent builds are failing on linux systems.

### Details

This is likely due to the PR #14650 merge as builds prior to that were fine, and due to the nature of the error in the log:
```
[2572/2600] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/welcome_dialog.cpp.o
FAILED: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/welcome_dialog.cpp.o
```

### Build with regression

8e4945ab28c75654924ffdde42855458a4c668ef

### Attach two log files

[build.log](https://github.com/RPCS3/rpcs3/files/12703853/build.log)

### System configuration

* OS: Linux Mint 21.2 / kernel 6.2
* CPU: Intel i7-10860h
* Compiler: gcc 12.3.0

**Comment by Megamouse** [comment]
You're on Qt 6.4, we are on Qt 6.5.2

**Comment by 3vi1** [comment]
Thx to @Megamouse for clearing up the confusion.  I just ran into this while trying to build with the Ubuntu 23.10 beta. 
 Looks like it will build fine with Qt6.6 as well.

CMAKE_PREFIX_PATH=/opt/Qt/6.6.0/gcc_64 cmake ../rpcs3/ && make -j16

**Comment by Shoegzer** [comment]
Indeed.  Compiles here too without issue using Qt 6.5.2 as expected.
