### ISSUE TITLE
 Yakuza Games - AMD specific issues

### ISSUE THREAD

**Issue by marinm99** [RPCS3/rpcs3#14668]
### Quick summary

[ Yakuza Games - AMD specific issues #6254 ](https://github.com/RPCS3/rpcs3/issues/6254)
Hi graphical bug on AMD cards is still happening.
I am using a RX 6700 XT

### Details

![NPUB31509_screenshot_2023_09_22_22_23_58](https://github.com/RPCS3/rpcs3/assets/126363791/40642c87-b436-4c33-aa92-632469d4f47b)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12704370/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12704371/RPCS3.log)

### System configuration

Windows 11, i7 9700K, RX 6700 XT newest drivers 23.9.2

**Comment by AniLeo** [comment]
Missing RSX capture file

**Comment by kd-11** [comment]
Closing as incomplete.
