### ISSUE TITLE
[Regression] Sega Rally (BLES00107) not working anymore with disc read error (#11015)

### ISSUE THREAD

**Issue by fabricecaruso** [RPCS3/rpcs3#14679]
### Quick summary

Can't launch the game anymore. 
It shows the error "Disc read error, attempting to read data".

It happens since #11015

0.0.18-12920 is OK
0.0.18-12921 is not OK

### Details

After testing old builds from https://github.com/RPCS3/rpcs3-binaries-win/releases : 
Build 0.0.18-12920 is running the game correctly.
It's not launching with ( and since ) 0.0.18-12921 build.

### Build with regression

v0.0.18-12921

### Attach two log files

[RPCS3-0.18.log](https://github.com/RPCS3/rpcs3/files/12729414/RPCS3-0.18.log)
[RPCS3-0.29.log](https://github.com/RPCS3/rpcs3/files/12729415/RPCS3-0.29.log)

**Comment by elad335** [comment]
Do you have a file called PS3_DISC.SFB ? in should be in the main game directory for disc games.

**Comment by fabricecaruso** [comment]
Yes. Here's the file list. The structure looks correct.
[folder.txt](https://github.com/RPCS3/rpcs3/files/13806211/folder.txt)

**Comment by elad335** [comment]
Retest with #14992 when it compiles

**Comment by fabricecaruso** [comment]
Working again ! Thanks.
