### ISSUE TITLE
Super Puzzle Fighter II Turbo HD Remix [NPUB90041]  invalid map<K, T> key error

### ISSUE THREAD

**Issue by ikki84** [RPCS3/rpcs3#1468]
The game doesn´t launch and shows an error message since this branch: v0.0.0.6-433-gb77666c

https://github.com/Bigpet/rpcs3/releases/download/v0.0.0.6-433-gb77666c/rpcs3-v0.0.0.6-433-gb77666c-win_x64.zip
https://github.com/Bigpet/rpcs3/releases/tag/v0.0.0.6-433-gb77666c

The error message: 
```
{PPU Thread[0x1] (main_thread)[0x002f2178]} cellGame: cellHddGameCheck(version=0, dirName=*0x10009d88, errDialog=0, funcStat=*0x306728, container=13)
{PPU Thread[0x1] (main_thread)[0x002f2178]} Exception: invalid map<K, T> key
Please report this to the developers.
```

Other informations that could help:

-The game in rpcs3 gamelist shows the App. Version as: unknown

-After it I did a test: I deleted the param.sfo of the Super Puzzle Figther II Turbo HD Remix game folder [of course the game doesn´t appear anymore in the rpcs3 menu gamelist]

-So I replaced the file with the Sonic CD param.sfo:
The game shows in the rpcs3 menu gamelist with the Sonic CD name but the Super Puzzle Fighter II Turbo HD Remix icon and when you click it launch the game and it runs perfectly as in the previous versions.

So i think it´s something related to the param.sfo file. 

![super puzzle](https://cloud.githubusercontent.com/assets/16824659/12702664/153da042-c816-11e5-8e11-8a61611c6be8.png)
![super puzzle2](https://cloud.githubusercontent.com/assets/16824659/12702666/169f0426-c816-11e5-90f6-ddd9f8d9bbf8.png)

**Comment by tambry** [comment]
@ikki84 Both links are broken. I also put the log snippet in code formatting and shortened the title to be more readable.

**Comment by ikki84** [comment]
Thanks, I fixed the links.

**Comment by ikki84** [comment]
@tambry Thanks, I fixed the links

**Comment by andre4688** [comment]
can correct this error ,opengl  To play
                       
E {rsx::thread} write_vertex_array_data_to_buffer: frequency is not null (4, index=3)
E {rsx::thread} write_vertex_array_data_to_buffer: frequency is not null (4, index=8)

**Comment by tambry** [comment]
@andre4688 Not relevant. You have also proven yourself before to be incapable of providing useful information.

**Comment by O1L** [comment]
Caused be throwing std::out_of_range exception in std::map here https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/SysCalls/Modules/cellGame.cpp#L83
Wrap std::map::at functions in try - catch, or write own function with returning default value for non-existent parameters.

**Comment by tambry** [comment]
cellGame functions are overall "poorly" implemented. I mean the it has almost **30** TODOs.

**Comment by vlj** [comment]
Is there a hack to get the game working ? I need it to test MSAA implementation.

**Comment by tambry** [comment]
@vlj Just try disabling [this](https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/SysCalls/Modules/cellGame.cpp#L78) else section.
It might need it to run though.

**Comment by O1L** [comment]
Or like this:
```
try
{
	get->getParam.parentalLevel = psf.at("PARENTAL_LEVEL").as_integer();
	get->getParam.attribute = psf.at("ATTRIBUTE").as_integer();
	get->getParam.resolution = psf.at("RESOLUTION").as_integer();
	get->getParam.soundFormat = psf.at("SOUND_FORMAT").as_integer();
	strcpy_trunc(get->getParam.title, psf.at("TITLE").as_string());
	strcpy_trunc(get->getParam.dataVersion, psf.at("APP_VER").as_string());
	strcpy_trunc(get->getParam.titleId, psf.at("TITLE_ID").as_string());
}

catch (std::out_of_range ex)
{
	cellGame.error("%s", ex.what());
}
```

**Comment by annahana** [comment]
just for  record in BLES01555-[Ni no Kuni - Der Fluch der weissen Königin] 

{PPU Thread[0x58] (GameContentAccess)[0x017891e4]} cellGame: cellGameGetParamString(): Unimplemented parameter (105)
{PPU Thread[0x58] (GameContentAccess)[0x017891e4]} HLE: Last function: cellGameGetParamString (0x3a5d726a)
{PPU Thread[0x58] (GameContentAccess)[0x017891e4]} Exception: invalid map<K, T> key
Please report this to the developers.

**Comment by tambry** [comment]
@annahana Okey, I added that exception there just in case a while ago. I'll be sure to take a look at it during the weekend, if not earlier.

**Comment by tambry** [comment]
Okey, that section shouldn't be there. According to documentation, such information in get is not set, and later the PARAM.SFO is rewritten/modified with values passed from set. I'll try to fix this function up.
I have NPUB30017 of the game. The intro is a huge flashing mess with disappearing and resizing objects along with flashing colours. @vlj Mind taking a look at that? [This](https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/SysCalls/Modules/cellGame.cpp#L78-L95) should be safe uncomment, if you want to test it.

**Comment by vlj** [comment]
Which intro? I can't replicate here.

**Comment by tambry** [comment]
I'm not sure if it's the intro. Maybe it's the main menu or something. After booting the game, I have a black screen for a minute or so, and then blocks, explosions and text starts flashing on the screen randomly.

Something like this:
![](http://puu.sh/mZcW1/7a6b342c77.png)
![](http://puu.sh/mZd09/d88f2ec0ee.png)

Probably shader related:
`{rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 0)
`

**Comment by MyaniPT** [comment]
This exception: invalid map<K, T> key in cellGame happens to me in a few other games while trying to load them. Should I report on which titles or is it already being fixed?

**Comment by vlj** [comment]
Which revision do you use ?

**Comment by tambry** [comment]
@vlj The latest master
@MyaniPT [I already fixed it](https://github.com/tambry/rpcs3/commit/ca16b1c5b1004e96b59be3ac8d8880d4523d9de4). Will probably make a PR soon.

**Comment by vlj** [comment]
I still can't reproduce it :/ 
Which LLE Module do you enable ?

**Comment by tambry** [comment]
**LLE modules:**
- cellFiber
- cellSail
- cellSailAvi
- cellSre
- cellSpursJq

Those modules seem to reproduce the issue very well. And right now I'm getting about ~10-60 fps. Pressing starts takes you to a working menu.

**Comment by tambry** [comment]
Currently don't have the time to write a test for testing the behaviour on a real PS3, since after further reading of the documentation my fix is not the actual behaviour of it on a PS3.

**Comment by ikki84** [comment]
Working (!)
Thanks raven02, also thanks to nekotekina, tambry, kd-11, dhrpcs3, vlj, and all the developers!,
