### ISSUE TITLE
[Regression] [BLES01857] Destiny locks up if a controller is connected (#14458)

### ISSUE THREAD

**Issue by cohaereo** [RPCS3/rpcs3#14695]
### Quick summary

After #14458, Destiny gets stuck while booting with a controller attached. Setting all controllers to `null` allows the game to boot. Reconnecting the controller does not lock the game up again, but input from the controller does not work

### Build with regression

rpcs3-v0.0.29-15470-4bbe885f

### Attach two log files

Working build: [RPCS3-15468.log](https://github.com/RPCS3/rpcs3/files/12777367/RPCS3-15468.log)
Regressed build: [RPCS3-15470.log](https://github.com/RPCS3/rpcs3/files/12777369/RPCS3-15470.log)

**Comment by jarmbi** [comment]
+1

**Comment by ImKevinTbh** [comment]
+1

**Comment by AniLeo** [comment]
Closing as fixed by #14988 as it fixes the controller regressions from that PR

Please ask to reopen if this is still an issue on your side

**Comment by cohaereo** [comment]
Issue is definitely not fixed, same results as before on v0.0.29-15898-4068423c 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13805155/RPCS3.log)

**Comment by nblockbuster** [comment]
Still not fixed on 065a64371ee274d4e957501274ae045a0caa5ff1.
[RPCS3.log](https://github.com/user-attachments/files/16228962/RPCS3.log)

**Comment by jarmbi** [comment]
still not fixed on 0.0.32-16811-4d5897d5
[RPCS3.log](https://github.com/user-attachments/files/16608363/RPCS3.log)

**Comment by elad335** [comment]
Wait until the build 16812 is released.

**Comment by elad335** [comment]
Wait until the build 16812 is released.

**Comment by jarmbi** [comment]
understood  my apologies

**Comment by cohaereo** [comment]
Can confirm the issue has been fixed 👍
