### ISSUE TITLE
Savestates fatal error

### ISSUE THREAD

**Issue by CorpseSlayer** [RPCS3/rpcs3#14701]
### Quick summary

Savestates has gone from a simple Error to a Fatal Error
![image_2023-10-02_211651918](https://github.com/RPCS3/rpcs3/assets/126618918/140183d8-5e02-4618-b875-0d05b9644e3b)

### Details

While playing a game  try to use savestate but RPCS3 just plain crashes with and error...
![image_2023-10-02_211758221](https://github.com/RPCS3/rpcs3/assets/126618918/4dc76ff9-c83c-4638-81a5-6ef8630e0899)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12787581/RPCS3.log)
[TTY.log](https://github.com/RPCS3/rpcs3/files/12787582/TTY.log)
[update_history.log](https://github.com/RPCS3/rpcs3/files/12787583/update_history.log)

no idea witch one it is so here are all the logs i could fine in the RPCS3 folder....

### System configuration

Win 11
RTX 2060
16gb Ram

**Comment by elad335** [comment]
Find the RPCS3 build it regressed.

**Comment by Darkhost1999** [comment]
Wasn't the Compatible Savestate Mode setting that they are not using designed to fix exactly this issue?
So just enable compatible mode and try again.

**Comment by elad335** [comment]
Probably fixed.

**Comment by CorpseSlayer** [comment]
> Probably fixed.

Not sure what going on: 

Advance compatibility option is Enable
i erase the old savestate from castlevania lords of shadows
i start the game and manage to do a "savestate" but once you load
the savestate it loads the game but as soon as you resume gameplay
RCPS3 crashes with unhandled Error...
![Screenshot 2023-10-05 160343](https://github.com/RPCS3/rpcs3/assets/126618918/e5d0895a-e8f5-4d1b-8496-1842f2c6cd13)
i am doing savestates from the RPCS3 menu
![image_2023-10-05_162226812](https://github.com/RPCS3/rpcs3/assets/126618918/ab5503aa-5b85-4d11-9e0e-f536625393a6)

**Comment by elad335** [comment]
Well, the original issue is fixed so you may open a new issue.

**Comment by elad335** [comment]
Also, it's not RPCS3 that crashes it is the literal message from the game.

**Comment by CorpseSlayer** [comment]
> Also, it's not RPCS3 that crashes it is the literal message from the game.

in other games it wont have the unhandle error it will load the game but it only shows black screen...not reloading PPU maybe?

**Comment by elad335** [comment]
I can't know anything without log and a fresh new issue, new issue helps me regain think. Some say opening a new issue instead of posting in old one increases brain capacity and attention by 800%.
