### ISSUE TITLE
AutoSave Not working and VERY VERY POOR PERFORMANCE

### ISSUE THREAD

**Issue by tonytheflyingtiger** [RPCS3/rpcs3#14707]
### Quick summary

I've heard RPCS3 is the best PS3 emulator there there. Is it?? Perhaps having a several updates per day is not the best approach to bug fixing lol. Your testers can not possibly perform proper regression testing at that rate. How many updates has it been now that AutoSave has been busted? Also, The poor video performance is astonishing. As far as I know, most people can not afford a $10000 computer. I am a computer programmer with a high end computer and literaly been trying to get a game to run properly for about a week now. This emulator has some serious issues!

### Details

Just as i finally think I have the game running normally, cutscenes literally crawl and then stop completely lol.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12805303/RPCS3.log)

**Comment by AniLeo** [comment]
Closed obvious troll issue, log file from build from 6 months ago on a toaster laptop with settings purposely sabotaged.
