### ISSUE TITLE
Unknown Win32 error: 0xb7.

### ISSUE THREAD

**Issue by annahana** [RPCS3/rpcs3#1470]
From: C:/Users/admin/Desktop/rpcs3-ReleaseLLVM-a9b961a5/dev_hdd1/game/BLES01426
To: C:/Users/admin/Desktop/rpcs3-ReleaseLLVM-a9b961a5/dev_hdd0/game/BLES01426
(in file C:\rpcs3\Utilities\File.cpp:342, in function fs::rename)

in game BLES01426-[Rage]

**Comment by tambry** [comment]
0xB7: ERROR_ALREADY_EXISTS
Seems like an oversight.

**Comment by tambry** [comment]
@annahana Please provide the full log.

**Comment by annahana** [comment]
log attached change png to log

![rpcs3](https://cloud.githubusercontent.com/assets/13276505/12874217/c9321196-cdcf-11e5-9ea0-6509be661404.png)
![tty](https://cloud.githubusercontent.com/assets/13276505/12874218/c93342aa-cdcf-11e5-86c6-d59c256f593a.png)

**Comment by MyaniPT** [comment]
This is happening to me as well with:
- Flight Control HD **[NPJB00010]**
- Wakeboarding HD **[NPEB00122]**

```
{PPU Thread[0x68] (ContentAccessPermissionsGet)[0x00629750]} Exception: Unknown Win32 error: 0xb7.
From: C:/Users/Annie/Desktop/rpcs3/dev_hdd1/game/NPEB00122
To: C:/Users/Annie/Desktop/rpcs3/dev_hdd0/game/NPEB00122
(in file ..\Utilities\File.cpp:342, in function fs::rename)
Please report this to the developers.
```

Log from NPEB00122: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/120886/RPCS3.zip)

TTY: "np::Trophy required space: 1476752" (Seems irrelevant)

**Comment by MyaniPT** [comment]
```
 {PPU Thread[0x1] (main_thread)[0x008db948]} Exception: Unknown Win32 error: 0x7b (C:/Users/Annie/Desktop/rpcs3_480/dev_hdd0/game/NPEA00287/USRDIR/e:/dev_hdd0/game/NPEA00287/USRDIR/Data/Main.pssg).
(in file ..\Utilities\File.cpp:252, in function fs::is_dir)
```
**NPEA00287** - Eat Them!™
[rpcs3_480_npea00287.zip](https://github.com/RPCS3/rpcs3/files/138366/rpcs3_480_npea00287.zip)

Before the crash, some related outputs:
```
 {PPU Thread[0x1] (main_thread)[0x008db948]} sys_fs: sys_fs_open('/usr/share/fonts/default/TrueType//dev_hdd0/game/NPEA00287/USRDIR/Data/Main.pssg') failed: device not mounted
{PPU Thread[0x1] (main_thread)[0x008db948]} sys_fs: sys_fs_open('/host_root/usr/share/fonts/default/TrueType//dev_hdd0/game/NPEA00287/USRDIR/Data/Main.pssg'): failed to open file (flags=0, mode=0)
````

**Comment by MyaniPT** [comment]
**NPUB31364** - Contrast
```
{PPU Thread[0x99] (fios mediathread 2)[0x00e07890]} Exception: Unknown Win32 error: 0x7b (C:/Users/Annie/Desktop/rpcs3/dev_hdd0/game/NPUB31364/USRDIR/*.PSARC).
(in file C:\rpcs3\Utilities\File.cpp:150, in function fs::stat)
```

**Comment by AniLeo** [comment]
This issue appears to be solved therefore I'm closing it.

**Comment by thefallentoast** [comment]
> This issue appears to be solved therefore I'm closing it.

How is it solved? I'm having the same error on Xenia, thought that since the PS3 is from the same generation it would help.

**Comment by dcon03** [comment]
> > This issue appears to be solved therefore I'm closing it.
> 
> How is it solved? I'm having the same error on Xenia, thought that since the PS3 is from the same generation it would help.

They are two completely different architectures, cant make that comparison. If you are having issues with it on Xenia, you need to go to the Xenia discord or github and report the issue to them there.
