### ISSUE TITLE
[NPUB31154] Crashing Grand Theft Auto 5 on mbp m1 pro

### ISSUE THREAD

**Issue by cherepavel** [RPCS3/rpcs3#14712]
### Quick summary

The game crashes at a random time later without any errors in the log

### Details

For some reason, the time after which the game begins to crash increased with each restart. Initially, the game crashed when Trevor opened the door and went outside. Then (as in the video) the crash occurred after the shooting of the last policemen

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12822765/RPCS3.log)

### Attach capture files for visual issues

crash at time 6:11 https://www.youtube.com/watch?v=c9z4Gdv48Wo

### System configuration

mbp pro 14 m1 pro, mac os sonoma 14.0

**Comment by FlexBy420** [comment]
Non wiki settings, week old build and you are also using a patch
