### ISSUE TITLE
gl: validate shader is called right after linking

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#1471]
In the openGL backend, glValidateProgram is called right after glLinkProgram which is problematic if a the texture samplers are not all the same type. Until now, only sampler2D was used, so no problems, but when attempting to use more than one sampler type we get failures during validation. Validation should be done when a draw call would be successful and therefore requires that the samplers first be initialized using the glUniform* methods first. AMD fails the validation test but Nvidia passes.

**Comment by kd-11** [comment]
Moving the validate call right before drawing is correct, but wastes resources if called every draw call. Adding flags to the programs to check if it's first time use and only validate then is also another solution. Those who worked on this before may be able to assist in deciding the best approach.

**Comment by danilaml** [comment]
Can you prepare PR in the meantime since #1461 was merged? It's better to have slow and correct solution which can later be improved instead of not properly working one.

**Comment by kd-11** [comment]
PR https://github.com/RPCS3/rpcs3/pull/1474 is a fix for this, albeit a bit brutish. We should probably include a way to force/disable shader imo.

**Comment by tambry** [comment]
Is this fixed?

**Comment by kd-11** [comment]
#1474 was merged
