### ISSUE TITLE
[Regression] God Of War 3 PPU trap

### ISSUE THREAD

**Issue by OlegVolgin** [RPCS3/rpcs3#14721]
### Quick summary

God Of War 3 gives out "SIG: Thread terminated due to fatal error: PPU Trap!" upon start up and just an eternal black screen

### Details

So I tried to start God Of War 3 on 0.0.29-15680 (BCES00510) build, got "SIG: Thread terminated due to fatal error: PPU Trap! Sometimes tweaking the setting "Stub PPU Traps" can be a workaround to this crash.
Best values depend on game code, if unsure try 1." error. If I do what error message tells me, I get this: "F {PPU[0x1000000] Thread (main_thread) [0x001f0f98]} VM: Access violation writing location 0x10000000 (unmapped memory)". Both ways I have just a black screen. 

Using 0.0.25-14517 build though, game starts and runs well at 30-45fps (except for video au decoding error in some cutscenes). 

No overclocking, only CPU autoboosting. Tried both on disabled/enabled patches, different cofigs, it's all the same

### Build with regression

v0.0.29-15680-8bd05871

### Attach two log files

W/O Stub PPU traps: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12841780/RPCS3.log)
With Stub PPU traps: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12841789/RPCS3.log)
0.0.25-14517 version that works: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12841805/RPCS3.log)

### System configuration

- GTX1060 3GB
- Ryzen 5 5600X
- B450M S2H
- 16GB RAM
- Windows 10 22H2

**Comment by AniLeo** [comment]
Incorrect report, flagged build with regression just changes one line in a build file, it's impossible that it introduced this regression.

Furthermore, builds for the two log files are more than one version apart.

Need information: Correct build that introduced the regression.

**Comment by OlegVolgin** [comment]
Does that mean that I have to check all the versions down to the regressed one?..

**Comment by AniLeo** [comment]
On a regression report you need to flag the build that introduced the regression, not a random one.

You don't need to test every single build, that's unfeasible, just apply binary search between the two builds you currently have as boundaries until you're down to the build that broke it.

**Comment by OlegVolgin** [comment]
After conducting binary search, I came to concliusion that error was not related to RPCS3 version, but caused by liblv2 library. Sorry for the inconvenience
