### ISSUE TITLE
[Regression] Debian: Fatal Error either on executing RPCS3 or when opening config menus in superseding versions (#13632)

### ISSUE THREAD

**Issue by Avsynthe** [RPCS3/rpcs3#14745]
### Quick summary

Hi there,

I've run into an issue on Debian with all builds including and following v0.0.27-15006-24dde5d4_linux64. Depending on the build, I get this fatal error and force close either when simply executing the application (this build does this) or on builds where it executes fine, it will throw when opening a config menu, CPU or GPU for example. I've attached a screenshot of this case.

Fatal Error: Segfault reading location 0000000000000008 at 0000000002ceb267.
Thread: Main Thread.

I have checked with others running the same OS and they are experiencing replicable results and has been somewhat of a known issue. All versions prior to this execute fine and configuration menus are fully functional without crashing RCPS3.

Logs for both regressed and working builds attached

![Screenshot 2023-10-19 213326](https://github.com/RPCS3/rpcs3/assets/102600593/944c21e6-fba3-490f-b769-a38618b92164)

### Build with regression

v0.0.27-15006-24dde5d4_linux64

### Attach two log files

[regressed-RPCS3.log](https://github.com/RPCS3/rpcs3/files/13042184/regressed-RPCS3.log)
[working-RPCS3.log](https://github.com/RPCS3/rpcs3/files/13042198/working-RPCS3.log)

### System configuration

unRAID OS Host
Steam-Headless docker container (Debian)
i9 9900kf
Asrock z390m Pro4
RTX 3070
128GB RAM

**Comment by AniLeo** [comment]
Linking PR that introduced the regression: #13632

**Comment by Megamouse** [comment]
probably fixed by #14802

**Comment by Megamouse** [comment]
reopen if it still happens
