### ISSUE TITLE
Git error in Flatpak build due to yaml-cpp having unknown remote commit

### ISSUE THREAD

**Issue by j8r** [RPCS3/rpcs3#14740]
After the update of yaml-cpp included in this [commit](https://github.com/RPCS3/rpcs3/commit/ec916d1f5f30234fcef05a4d3794ba704a373c1f), the [flatpak build](https://buildbot.flathub.org/#/builders/35/builds/9138) has started to fail:
```
fatal: git upload-pack: not our ref 456c68f452da09d8ca84b375faa2b1397713eaba
fatal: remote error: upload-pack: not our ref 456c68f452da09d8ca84b375faa2b1397713eaba
fatal: Fetched in submodule path '3rdparty/yaml-cpp/yaml-cpp', but it did not contain 456c68f452da09d8ca84b375faa2b1397713eaba. Direct fetching of that commit failed.
```
I don't know all the underlying git commands executed, thus haven't been able to reproduce outside the flatpak build, however the commit pointed by the error is indeed not existing on the remote repository: https://github.com/jbeder/yaml-cpp/commit/456c68f452da09d8ca84b375faa2b1397713eaba.

If yaml-cpp 0.8.0 is supposed to be used, shouldn't the commit be https://github.com/jbeder/yaml-cpp/commit/f7320141120f720aecc4c32be25586e7da9eb978?
If not possible to contribute to the upstream package, a fork should perhaps be used (or subtree?).

Thanks in advance.

**Comment by Megamouse** [comment]
All relevant commits exist on either rpcs3 or my branch.
That being said, it's not our problem if the flatpak doesn't work

**Comment by MSuih** [comment]
The commit exists in https://github.com/RPCS3/yaml-cpp/commit/0b67821f307e8c6bf0eba9b6d3250e3cf1441450

Flatpak is trying to look up a commit from the wrong repository.

**Comment by j8r** [comment]
Thanks to have found the root cause!

This issue was not present before, is using the fork new?

**Comment by MSuih** [comment]
The fork has been in use for years, but the commit that it points towards was updated recently in this commit: https://github.com/RPCS3/rpcs3/commit/ec916d1f5f30234fcef05a4d3794ba704a373c1f

**Comment by j8r** [comment]
Thanks to have found the root cause! Sorry to have bother you, I'll figure out myself on how to fix that.

**Comment by j8r** [comment]
True, I was not sure if the fork was a new thing, until I look on the modules with `url = ../../RPCS3/` in https://github.com/RPCS3/rpcs3/blob/master/.gitmodules

**Comment by j8r** [comment]
I tested locally, I can also have the issue so that's more related to flatkapk than the Flathub builder.
When looking at https://github.com/RPCS3/yaml-cpp/commit/456c68f452da09d8ca84b375faa2b1397713eaba, I see "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.".


The real commit should be https://github.com/gentoo-mirror/voyageur/commit/f4a15dd0d0aa374235537386ba0564f055581d69, because `456c68f452da09d8ca84b375faa2b1397713eaba` is only present in the @Megamouse fork: https://github.com/Megamouse/yaml-cpp/commit/456c68f452da09d8ca84b375faa2b1397713eaba

**Comment by j8r** [comment]
I tested locally, I can also have the issue so that's more related to flatkapk than the Flathub builder.
When looking at https://github.com/RPCS3/yaml-cpp/commit/456c68f452da09d8ca84b375faa2b1397713eaba, I see "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.".


The real commit should be `0b67821f307e8c6bf0eba9b6d3250e3cf1441450` https://github.com/RPCS3/yaml-cpp/commit/0b67821f307e8c6bf0eba9b6d3250e3cf1441450, because `456c68f452da09d8ca84b375faa2b1397713eaba` is only present in the @Megamouse fork: https://github.com/Megamouse/yaml-cpp/commit/456c68f452da09d8ca84b375faa2b1397713eaba
