### ISSUE TITLE
Hyperdimension Neptunia cellPhotoDecode error when importing custom photo

### ISSUE THREAD

**Issue by slunycau** [RPCS3/rpcs3#14744]
### Quick summary

Custom images for the "R/W Disc" attack cannot be loaded; game claims "file is too large," log claims `cellPhotoDecode` cannot write outside of hdd0.

### Details

Hyperdimension Neptunia allows you to import custom images from the PS3 gallery, which will then show up during the attack animation of the "R/W Disc" item. The "import photo" dialog can see any image files placed under `$(EMUDIR)/dev_hdd0/photo`, but trying to import one of them results in the game claiming that the "Loaded image is too large."

![BLUS30701_screenshot_2023_10_18_10_57_47](https://github.com/RPCS3/rpcs3/assets/148146368/241d7ea5-4892-4fa5-a0dc-6c57350e2d2e)

The emulator logs show the game is trying to write the decoded photo to `/dev_hdd1/temp`, but `cellPhotoDecode` cannot write output outside of `/dev_hdd0`.

Relevant lines from the log:
```
U PhotoImport TODO: cellPhotoImport2(version=0x0, dstHddPath=“/dev_hdd1/temp”, param=*0xd0010640, funcFinish=*0x579508, userdata=*0x7)
U RSX TODO: show_media_list_dialog(type=4, path='G:/Games/RPCS3/dev_hdd0/photo', title='Select photo to import', on_finished=1)
E RSX: Left media list dialog: return_code=0, type=4, path=833223496
E cellPhotoDecode: Destination '“/dev_hdd1/temp”' is not inside dev_hdd0
E SYS: 'cellPhotoDecodeFromFile' failed with 0x8002c904 : CELL_PHOTO_DECODE_ERROR_ACCESS_ERROR [1]
```

How to reproduce:
1. Place a relatively small (~600x600) png or jpg image in `$(EMUDIR)/dev_hdd0/photo`.
2. Start a new game, skip dialogue until you enter the tutorial dungeon.
3. Go through the tutorial dungeon, until you encounter the first enemy.
4. Defeat the enemy; it should drop a "R/W Disc" item.
5. From the pause menu, navigate to: "Neptune" -> "Combo Skills" -> any entry in the 3rd or 4th column -> "R/W Disc"
6. Press square to edit the attack -> "Image Edit" -> press square to open the image select dialog
7. You should be able to see the image you placed in step 1. Select it.
8. Game warns that "Loaded image is too large."

### Attach a log file

[Hyperdimension Neptunia [BLUS30701].log.gz](https://github.com/RPCS3/rpcs3/files/13033606/Hyperdimension.Neptunia.BLUS30701.log.gz)

### System configuration

* OS: Windows 10 build 19044
* CPU: AMD Ryzen 5 2600X
* GPU: Radeon RX 580, driver version 2.0.258

### Other details

`cellPhotoImport` [explicitly checks that the destination directory is under `/dev_hdd0` or `/dev_hdd1`](https://github.com/RPCS3/rpcs3/blob/b3864f2d10cfeee2bd775fb577b149a0930fa465/rpcs3/Emu/Cell/Modules/cellPhotoImport.cpp#L124). Hyperdimension Neptunia calls `cellPhotoImport2`, which in turn calls `cellPhotoDecode`, [which makes the same check, but only for `/dev_hdd0`](https://github.com/RPCS3/rpcs3/blob/b3864f2d10cfeee2bd775fb577b149a0930fa465/rpcs3/Emu/Cell/Modules/cellPhotoDecode.cpp#L147). Is there a reason for this?

Modifying the check in `cellPhotoDecode` to accept `/dev_hdd1` allows the photo to import correctly, and seems to cause no other adverse effects (but I haven't tested it extensively, nor tested any other games with it).

![BLUS30701_screenshot_2023_10_18_13_23_53](https://github.com/RPCS3/rpcs3/assets/148146368/23db18e5-34b1-4718-9663-556cc28f434e)

[Emulator log from the custom build](https://github.com/RPCS3/rpcs3/files/13033675/Hyperdimension.Neptunia.BLUS30701.log.gz)

**Comment by Megamouse** [comment]
dev_hdd1 was whitelisted in cellPhotoImport after cellPhotoDecode was implemented.
So I probably just didn't see the logical connection between the two functions at that time.
