### ISSUE TITLE
[Regression] No audio with the audio buffering enabled (default) for most games (#14727)

### ISSUE THREAD

**Issue by davidhedlund** [RPCS3/rpcs3#14741]
### Quick summary

rpcs3-v0.0.29-15688-e3613e7d_linux64.AppImage and earlier: Audio works
rpcs3-v0.0.29-15689-ec916d1f_linux64.AppImage and later: Audio does not work

### Details
"Enable Buffering" is enabled by default:

![image](https://github.com/RPCS3/rpcs3/assets/6416073/aa5474ca-6b4e-48be-bd01-80589ee572b9)

As pointed out by JimScript, the "Enable Buffering" setting must be disabled for audio to work for most games ([see exceptions](#issuecomment-1767045475)).

### Build with regression

v0.0.29-15688-e3613e7d

### Attach two log files

* [v0.0.29-15688-e3613e7d-RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12941953/v0.0.29-15688-e3613e7d-RPCS3.log.gz)
* [v0.0.29-15689-ec916d1f-RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12941498/v0.0.29-15689-ec916d1f-RPCS3.log.gz)

### System configuration

Intel i7700k, using the inbuilt processor GPU graphics.

**Comment by JimScript** [comment]
I found that this has something to do with the audio buffering on linux, as turning it off solves the issue. Strangely some games and all FMV's still have audio with buffering, here's a list of games I found to still work:

- Modnation Racers
- The Jak and Daxter Collection(but not in the game selector menu)
- The Legend of Spyro: Dawn of the Dragon
- Beyond Good & Evil HD

**Comment by davidhedlund** [comment]
> I found that this has something to do with the audio buffering on linux, as turning it off solves the issue. Strangely some games and all FMV's still have audio with buffering, here's a list of games I found to still work:
> 
>     * Modnation Racers
> 
>     * The Jak and Daxter Collection(but not in the game selector menu)
> 
>     * The Legend of Spyro: Dawn of the Dragon
> 
>     * Beyond Good & Evil HD

I updated the top post. Thank you very much!

**Comment by Yar4e** [comment]
Can confirm the issue for Odin Sphere: Leifthrasir in Linux Mint 21.2. rpcs3-v0.0.29-15688-e3613e7d_linux64.AppImage - Audio is great, rpcs3-v0.0.29-15689-ec916d1f_linux64.AppImage - it cut off after few seconds of playing. Disabling audio buffering solves the problem.

**Comment by JimScript** [comment]
Pure(the ATV game from Disney) is very interesting in how that this problem comes up, the starting FMV has sound and the main menu has no sound, but then certain things can bring the sound back to the UI. Like selecting a character will bring back the sound for as long as they're talking then it goes back to silence, and if you start a race the sound will be back for the whole session, but the qualification will only bring it back partially and the main menu will still be silent.

**Comment by SeongGino** [comment]
For what it's worth, I found building it from source (on Arch) has the sound buffering working. So no idea what that's about.

**Comment by Isaiahmag** [comment]
Had the same issue and had to disable audio buffering as well and I'm using EndeavourOS.

**Comment by RipleyTom** [comment]
The issues seems to be caused by a bug in GCC 13.1 which is the only GCC 13 package available on the Ubuntu image we use(hence why we're switching to clang).

**Comment by davidhedlund** [comment]
Works for me now with "Enable Buffering" enabled (default setting). Thank you very much!

**Comment by davidhedlund** [comment]
> Works for me now with "Enable Buffering" enabled (default setting). Thank you very much!

I have to disable "Enable buffering" (again) so please reopen this issue.

AppImage: 0.0.40-19415-ecf77ece

**Comment by davidhedlund** [comment]
> > Works for me now with "Enable Buffering" enabled (default setting). Thank you very much!
> 
> I have to disable "Enable buffering" (again) so please reopen this issue.

Never mind, no need to reopen this issue. It turns out my problem was related to a different bug, which I managed to fix just by clicking 'Save' in the Config menu (originally while trying to disable 'Enable buffering', though that turned out to be unnecessary):
* https://github.com/RPCS3/rpcs3/issues/18821
