### ISSUE TITLE
Emulator completely crashes when saving or exiting in Minecraft: PlayStation® 3 Edition

### ISSUE THREAD

**Issue by TheAwesome98-Real** [RPCS3/rpcs3#14759]
### Quick summary

when clicking "Save Game", or anything other than "Cancel" under "Exit Game", the entire emulator will crash. the final line in stdout is `free(): invalid next size (normal)`, i'm not sure if that has anything to do with it since i don't really use c-like languages.

### Details

creating a level, and selecting either "Save Game", "Exit Without Saving" or "Exit and Save" will crash the entire emulator. i would imagine this has to do with saving the level (since i think exit without saving still saves an entry to the list, just with no world data), but changing and saving configuration settings doesn't crash the emulator, so it may have to do with creating a new save file, as opposed to updating an existing one. of course, on a real PS3, this doesn't happen.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13064435/RPCS3.log)

### System configuration

OS: Ubuntu GNU/Linux 22.04.3 LTS x86_64
Kernel version: Linux 6.2.0-35-generic
Processor: AMD Ryzen 5 2600X Six-Core Processor (12 cores, 3.600GHz)
Graphics: Advanced Micro Devices, Inc. (AMD/ATI) Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
Graphics driver: amdgpu-pro 1:5.5.50502-1607507.22.04
Memory: 16GB 2666MHz (N/A, 8GB 2666MHz, N/A, 8GB 2666MHz)

### Other details

:3

**Comment by FlexBy420** [comment]
Unable to reproduce.

**Comment by TheAwesome98-Real** [comment]
> Unable to reproduce.

are you using BLES01974 1.84?

**Comment by FlexBy420** [comment]
It shouldn't matter which region is used but I am on the latest game version.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13064521/RPCS3.log.gz)

**Comment by TheAwesome98-Real** [comment]
that's odd, i'm going to back up my configuration file and reset them, and see if that fixes the problem

**Comment by TheAwesome98-Real** [comment]
yes, it was my configuration. i'm not sure whether to report that as an issue (depending on what the configuration option causing it is), or to just close it with "do not have this option set"

**Comment by TheAwesome98-Real** [comment]
the issue appears to be "force cpu blit". i have no idea why i had it turned on, but turning it off fixed the issue.

**Comment by Darkhost1999** [comment]
I believe the option was enabled to prevent slow down when placing a bunch of items in a chest, or swinging your ax repetitively at trees, shovels at dirt, pick axes at rocks, swords at everything, etc.
The idea of force cpu blit to be used came from Roxas slow down when swinging his sword from kingdom hearts 2.
When tested in Minecraft it did reduce/help resolve this problem. But has never been confirmed to even be an issue on better CPUs than a Ryzen 5 3600.
Such at a Ryzen 5 3600 managed to close the issue for Roxas slow down in kingdom hearts 2 and should be virtually impossible to recreate the issue on any cpu that is better than that cpu.
