### ISSUE TITLE
[BCES00129] Motorstorm Pacific Rift: Split screen graphics messed up

### ISSUE THREAD

**Issue by marph43** [RPCS3/rpcs3#14758]
### Quick summary

When playing Motorstorm Pacific Rift in split screen mode, the second split screen's graphics are messed up. It looks like the graphics are totally stretched in horizontal direction, so there is only a pattern of horizontal lines to be seen.
![motorstorm pacific rift split screen](https://github.com/RPCS3/rpcs3/assets/56201105/ffa01257-9a12-445f-8ce0-87f12e2fc596)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13063277/RPCS3.log.gz)

### Attach capture files for visual issues

https://mega.nz/file/UWlzgZrL#-DPwOoXwrkZKFxuKlW5dNEXgDV3gwNmSQr8Ae5fnoec

### System configuration

Operating System: Windows 10 Build 19045
CPU: Intel Core i7-6700K
GPU: Nvidia GeForce GTX 980, Driver: 31.0.15.4584

**Comment by kd-11** [comment]
Looks like you need to enable write colour buffers

**Comment by marph43** [comment]
It is enabled:
![motorstorm pacific gpu settings](https://github.com/RPCS3/rpcs3/assets/56201105/7d777145-359d-4f9f-9bc5-d666cf3b6087)

**Comment by laughlinb327** [comment]
I was able to fix this by restoring the anisotropic filter and antialiasing settings to default instead of the values recommended on the compatibility wiki.

**Comment by marph43** [comment]
Worked! Thanks so much!
