### ISSUE TITLE
[Feature request] Add "Exit Emulator" to the home menu

### ISSUE THREAD

**Issue by Kupo91** [RPCS3/rpcs3#14751]
### Quick summary

I was surprised that nobody requested this so far. But maybe I just missed it. My apologies if so.

I'd love to see a button to exit the emulator via home menu. Maybe you could place this button below "Exit Game".

The reason is that I do couch gaming and launch my games through an external launcher. Starting games via command line works good, but I can't come back to the launcher without using a mouse or a keyboard. So an exit button in the home menu to exit the emulator via controller would be much appreciated

**Comment by Megamouse** [comment]
There's an option to close the emulator on game exit.
I don't think we need yet another menu entry.

**Comment by Darkhost1999** [comment]
Was just looking at this and agree -> emulator -> exit RPCS3 when process finishes is sufficient and should work when choosing Exit game from the home menu.

**Comment by Kupo91** [comment]
Oh, haven't seen this before. Well, that's good enough for me, thanks a lot :)
