### ISSUE TITLE
App Crash when choosing SDL handler

### ISSUE THREAD

**Issue by FahmiChaar** [RPCS3/rpcs3#14753]
### Quick summary

Open Pads window then choose SDL from handlers selectbox and select controller from Devices then app will be Crashed

### Details

Open Pads window then choose SDL from handlers selectbox and select controller from Devices then app will be Crashed

i use USB (PC) Controller which work well with other emulators such (ryujinix and openEmu)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13060622/RPCS3.log)

[apple-crash-report.txt](https://github.com/RPCS3/rpcs3/files/13060565/rpcs3-crash-log.txt)

### Attach capture files for visual issues

![Screenshot 2023-10-21 at 11 55 24](https://github.com/RPCS3/rpcs3/assets/8315828/6c3eef6c-5d8e-428c-aec4-d56838ec902c)

### System configuration

Mac Mini with macos ventura 13.3.1 (a) and Apple M1 chip

RPCS3 Version: 0.0.29-15693-b3864f2d Alpha | HEAD

### Other details

Thanks for your good work.

**Comment by Megamouse** [comment]
Missing log file of the crash

**Comment by FahmiChaar** [comment]
Oh i'm sorry

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13060622/RPCS3.log)

**Comment by FahmiChaar** [comment]
Hello,
So what I've done so far
I notice this error in the log file `SDL: Could not add mappings from file '/Users/fahmi/Library/Application Support/rpcs3/input_configs/gamecontrollerdb.txt'! File does not exist!` 
so I downloaded the `gamecontrollerdb.txt` file from the github repository `SDL_GameControllerDB` then placed it in the `input_configs` folder, but the application crashed
then I download `gamepad-tool` from the same `SDL_GameControllerDB` repository and copy my gamepad mapping and paste it into `gamecontrollerdb.txt` and get the same result, application crash

this is the log file after adding `gamecontrollerdb.txt` file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13062690/RPCS3.log)

**Comment by Megamouse** [comment]
gamecontrollerdb.txt is purely optional and shouldn't cause or fix any crashes, whether it's there or not.

**Comment by Megamouse** [comment]
Does this happen with any controller or only if that specific controller is connected?

**Comment by FahmiChaar** [comment]
I only have one controller so I haven't tested it with other controllers

**Comment by FahmiChaar** [comment]
Ok, i try the same controller with rpcs3 on windows and it work very well

**Comment by uwemneku** [comment]
@FahmiChaar I just had this same issue on my mac, what worked for me was going into
`Settings>Game Controllers` and erasing the controller settings. After that, the app stopped crashing when I select SDL

**Comment by Zubius** [comment]
Still happening.

Segfault reading location 000007fc005a1ba0 at 00007ff8013e2a1d.
Thread: Main Thread.
Title: "METAL GEAR SOLID 4 GUNS OF THE PATRIOTS [BLUS30109]" (emulation is stopping)
Build: "0.0.32-16553-67893fb8 Alpha | HEAD"
Date: "2024-06-01T19:53:13"

macOS 14.5
Nintendo Switch Pro Controller

**Comment by w-e-g** [comment]
At first glance looks fixed. :)

**Comment by Megamouse** [comment]
It may still crash when you close rpcs3 after having used the SDL handlers. But I hope not.

**Comment by w-e-g** [comment]
No problem, I'll test it more.

**Comment by MajmunX** [comment]
I tried with Xbox series X controller and works fine, the emulations stops normally with no error when SDL is selected and controller is connected. 

Collection games (GOW, etc...) used to shut down after choosing because It felt like the emulation stops and rpcs3 reopens the chosen game after closure of the choice screen. That stopped too. Works fine now

**Comment by GregoireLD** [comment]
> It may still crash when you close rpcs3 after having used the SDL handlers. But I hope not.

I do get that indeed, but I can confirm it doesn't crash anymore when exiting a game, thanks ! 😊
