### ISSUE TITLE
[BLES01751] Skylanders Spyro's Adventure has messed up colors during upscaling

### ISSUE THREAD

**Issue by Graubek** [RPCS3/rpcs3#14763]
### Quick summary

When playing Skylanders Spyro's Adventure, graphic errors are present all the time during upscaling
![sky](https://github.com/RPCS3/rpcs3/assets/58905125/6702c7d9-4d11-46c3-8d6f-5b86800c5032)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13072480/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1p0VzJkj69WYgsZvXUzliAiC42YtUtc94/view?usp=share_link

### System configuration

Operating System: Windows 11 10.0.22621
CPU: Intel Core i7-13700k
GPU: Nvidia GeForce RTX 4080, Driver: 537.42

**Comment by Graubek** [comment]
Footage without upscaling
![withoutupscaling](https://github.com/RPCS3/rpcs3/assets/58905125/7445eeb0-54a1-4c12-b2fc-1e918d6ff578)

PS3 footage
![ps3r](https://github.com/RPCS3/rpcs3/assets/58905125/86e540d4-6e41-45fb-b422-b957297d1ade)

**Comment by Graubek** [comment]
I tried all the settings, but the result is the same.

**Comment by kd-11** [comment]
If upscaling doesn't work in a game it is not a bug unless it used to work before. Not every game will scale up cleanly. Truly adjusting the resolution scale threshold value and see if it helps.
