### ISSUE TITLE
Use fusion QT style instead of legacy windowsvista style when not applying custom theme

### ISSUE THREAD

**Issue by 13xforever** [RPCS3/rpcs3#14762]
### Quick summary

QT 6.5 has native dynamic light/dark theme support on Windows using fusion style, but it's an opt-in feature. By default it's using legacy `windowsvista` style that only supports light theme. [More info](https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5).

### Details

You can force new fusion style via command line option like so: `rpcs3.exe -style fusion` and making sure `None` is selected in Settings > GUI > UI Stylesheets.

In RPCS3 it's not perfect currently (dynamic switching doesn't update most UI elements, so it only fully applies when restarting the app), but it's still a better option than always using one specific style (and it looks nicer).

![windowsvista](https://github.com/RPCS3/rpcs3/assets/36445/3d0e2851-7654-4a8e-b5b6-0fe9e030fb2b)
![light fusion](https://github.com/RPCS3/rpcs3/assets/36445/3acc1d12-16a8-4dcd-80d9-6fe574ab9ead)
![dark fusion](https://github.com/RPCS3/rpcs3/assets/36445/d35c0bf1-72e4-42bf-9b87-0e4efa75013b)

**Comment by Megamouse** [comment]
Wouldn't it make more sense to allow setting two stylesheets and add a toggle for light/dark/auto ?

**Comment by Megamouse** [comment]
I can't set the default to fusion, since it will break custom stylesheets during dark mode, and it would be platform specific anyway.
Instead I implemented a way to simply select all the native styles in the stylesheet dropdown.
I think that's the better solution as well.
