### ISSUE TITLE
high brightness in nier 

### ISSUE THREAD

**Issue by alexou2** [RPCS3/rpcs3#14771]
### Quick summary

the brightness in-game is too high

### Details

the screen is almost entirely white and the details aren't visible, however the cutscenes are completely fine

### Attach a log file

I can't find the log file

### Attach capture files for visual issues

![Screenshot from 2023-10-26 00-57-53](https://github.com/RPCS3/rpcs3/assets/92472779/422f68bf-9f47-4c15-9207-6682c25b249e)
![Screenshot from 2023-10-26 00-57-23](https://github.com/RPCS3/rpcs3/assets/92472779/2701d744-30ec-4eca-bda0-823e3ea1efb6)
![Screenshot from 2023-10-26 00-58-11](https://github.com/RPCS3/rpcs3/assets/92472779/15fda4e5-c5db-4717-967a-f3b4d920e4a8)
![image](https://github.com/RPCS3/rpcs3/assets/92472779/3c32f4af-f111-407f-992f-9cf752e74672)

### System configuration

ubuntu 23.04 laptop, r7 pro 6850u w/ igpu (rx 680m)

### Other details

the first screenshots were taken in a cutscene and the last ones were taken in actual gameplay

**Comment by Jonathan44062** [comment]
Use Write Color Buffers in GPU Tab, next time, check the wiki settings
