### ISSUE TITLE
Black Squares in flames  (Ratchet & Clank Future: A Crack in Time)

### ISSUE THREAD

**Issue by RetroAmuzed** [RPCS3/rpcs3#14775]
### Quick summary

Game: Ratchet & Clank Future: A Crack in Time
Game ID: BCUS98124
RCPS3 Ver: 0.0.29-15710
Problem: Black Squares in flames

### Details

Problem: Black Squares in flames

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13188524/RPCS3.log.gz)

### Attach capture files for visual issues

![BCUS98124_screenshot_2023_10_27_19_24_35](https://github.com/RPCS3/rpcs3/assets/78337187/aea9247c-8ffb-4066-b642-a229a3973246)
![BCUS98124_screenshot_2023_10_27_19_19_30](https://github.com/RPCS3/rpcs3/assets/78337187/385d052f-bf6a-4f94-b022-1b086add8bf8)
![BCUS98124_screenshot_2023_10_27_19_20_00](https://github.com/RPCS3/rpcs3/assets/78337187/946e7923-c7e9-4a9f-8d75-2c3c87e04513)

### System configuration

AMD Ryzen 7 5800X3D
NVIDIA GeForce RTX 3070 Ti (Galax 1-Click OC dual fan black)
GeForce Game Ready Driver Version: 545.92 

### Other details

How do I fix this little problem? If anyone knew also please do share.

**Comment by FlexBy420** [comment]
This is fixed by enabling Read color buffers. Please first check the wiki for right settings for the game and don't open useless issues.
