### ISSUE TITLE
Custom gamepad configuration resets after changing handler

### ISSUE THREAD

**Issue by ElTioRata** [RPCS3/rpcs3#14773]
### Quick summary

I had a key mapping configured for a game, then I decided to try it with a controller today so I switched the handler from Keyboard to XInput but then when I was done and I changed the handler back to Keyboard I saw that it didn't save my previous key mapping.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13184459/RPCS3.log)

**Comment by Megamouse** [comment]
Yes. Because that's how it works.

**Comment by ElTioRata** [comment]
That's terrible for the users since they'd expect the bindings to be saved, and if they aren't aware of that and don't backup the bindings before changing the handler, they'd have to re-configure everything again and that could take either a couple of minutes to an entire session of in-game mechanics testing to do re-configure everything again. I'm making a separate issue as a feature request since this is not an issue on most emulators.
