### ISSUE TITLE
No sound in game/menus but intro sound is ok

### ISSUE THREAD

**Issue by inferrna** [RPCS3/rpcs3#14780]
### Quick summary

No sound in menus and game in appimage version and in locally built version.
But sound is present in flatpak version. Config file was the same for flatpak version.

Same time sound is present in intro video in all versions.

### Attach a log file

[Demon s Souls [BLUS30443]_appimage_no_sound.log.gz](https://github.com/RPCS3/rpcs3/files/13195053/Demon.s.Souls.BLUS30443._appimage_no_sound.log.gz)
[Demon s Souls [BLUS30443]_flatpak.log.gz](https://github.com/RPCS3/rpcs3/files/13195054/Demon.s.Souls.BLUS30443._flatpack.log.gz)
[Demon s Souls [BLUS30443]_no_sound.log.gz](https://github.com/RPCS3/rpcs3/files/13195055/Demon.s.Souls.BLUS30443._no_sound.log.gz)
[config.yml.gz](https://github.com/RPCS3/rpcs3/files/13195057/config.yml.gz)

### System configuration

CPU: 2680v2
GPU: AMD RX560
System: Clear Linux, mesa + wayland + Gnome session

**Comment by JimScript** [comment]
I think this is the same issue as #14741

**Comment by inferrna** [comment]
Yes, without buffering, sound works. May close as a duplicate.
