### ISSUE TITLE
MGS HD Collection text being messed up when upscaling

### ISSUE THREAD

**Issue by 19Aidan** [RPCS3/rpcs3#14788]
### Quick summary

Hello. as you may remember this issue was fixed 3 months ago. well. not fully. it was only fixed on NVIDIA cards. not AMD cards. so this went under the radar again until now. 

![BLUS30847_screenshot_2023_10_29_23_35_43](https://github.com/RPCS3/rpcs3/assets/90439269/8b303a12-11a3-4d84-baa6-f07079f5fc0b)
![BLUS30847_screenshot_2023_10_29_23_35_47](https://github.com/RPCS3/rpcs3/assets/90439269/6c12a08a-b743-4987-8f74-5f4902f68196)
![BLUS30847_screenshot_2023_10_29_23_35_29](https://github.com/RPCS3/rpcs3/assets/90439269/3836c30c-7394-4337-9016-6c0c5b3c5080)
![BLUS30847_screenshot_2023_10_29_23_35_38](https://github.com/RPCS3/rpcs3/assets/90439269/6ad1c5b9-a73c-4b7e-8d93-951dbdfd5d20)

### Details

1. a copy of the game,
2. AMD GPU 
3. run it with an upscale above 100%

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13201564/RPCS3.log)

### System configuration

AMD Radeon RX 5700 XT running on driver 2.0.283
AMD Ryzen 7 3800X

**Comment by Megamouse** [comment]
This was never an upscaling issue.
Also, artefacts during upscaling are not considered an issue.

**Comment by 19Aidan** [comment]
> This was never an upscaling issue. Also, artefacts during upscaling are not considered an issue.

well it started when I started the game without any upscales. at 100% the main menu was fine however I quit to upscale the game.
![BLUS30847_screenshot_2023_10_30_20_35_43](https://github.com/RPCS3/rpcs3/assets/90439269/057b8c3f-9617-48fa-85ae-03094a4cd904)
![BLUS30847_screenshot_2023_10_30_20_36_07](https://github.com/RPCS3/rpcs3/assets/90439269/c0d28fa4-1f92-4929-8d5d-271efd3847e3)
![BLUS30847_screenshot_2023_10_30_20_36_13](https://github.com/RPCS3/rpcs3/assets/90439269/cb6c3316-a88b-4d29-888d-97d9d3114f18)
![BLUS30847_screenshot_2023_10_30_20_36_03](https://github.com/RPCS3/rpcs3/assets/90439269/fa89d821-3f21-4a9b-9bd5-2819fcd5fe11)

I reverted to 100% and found out that the backgrounds was always messed up oddly idk what's causing it. however the text was fine at 100% but messed up when upscaled. I will be changing the title.

**Comment by kd-11** [comment]
Do we have confirmation that NVIDIA is actually unaffected when upscaling? This game does something really stupid with the transparency effects in the screen there, so it's not unexpected that things break when upscaling is applied.

**Comment by kd-11** [comment]
Which reminds me - there are output precision differences between different generations of AMD cards. The OP has RDNA1, which may be relevant in this case.

**Comment by Megamouse** [comment]
> Do we have confirmation that NVIDIA is actually unaffected when upscaling? This game does something really stupid with the transparency effects in the screen there, so it's not unexpected that things break when upscaling is applied.

I tested it on my 3070 on both renderers before I added the amd label.

**Comment by Megamouse** [comment]
> Do we have confirmation that NVIDIA is actually unaffected when upscaling? This game does something really stupid with the transparency effects in the screen there, so it's not unexpected that things break when upscaling is applied.

The author said it happens without upscaling.

**Comment by Jonathan44062** [comment]
I can't repro on NVIDIA, is a issue with AMD
Works fine by upscaling
![image](https://github.com/RPCS3/rpcs3/assets/78843189/91c30338-1a6f-4a83-98c1-9f14b109a030)
![image](https://github.com/RPCS3/rpcs3/assets/78843189/b2f69b39-d197-444b-84e7-95c929db61f8)
![image](https://github.com/RPCS3/rpcs3/assets/78843189/ab436df7-f1c8-43e0-9ad0-f20370ddc484)
![image](https://github.com/RPCS3/rpcs3/assets/78843189/0ca4bc70-96f9-406c-8bcc-5e35f41c15bb)

200% resolution -> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13258983/RPCS3.log.gz)

100% resolution -> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13258987/RPCS3.log.gz)

**Comment by kd-11** [comment]
We have a special fixup in place for NVIDIA which we don't use for AMD. I hoped to avoid using it generally for performance reasons, but we may not have a choice. Well, I guess shader quality "low" exists anyway.

**Comment by 19Aidan** [comment]
> We have a special fixup in place for NVIDIA which we don't use for AMD. I hoped to avoid using it generally for performance reasons, but we may not have a choice. Well, I guess shader quality "low" exists anyway.

![BLUS30847_screenshot_2023_11_12_02_31_44](https://github.com/RPCS3/rpcs3/assets/90439269/67ca9d2a-0fca-4393-9149-7cd4244f6310)
![BLUS30847_screenshot_2023_11_12_02_31_47](https://github.com/RPCS3/rpcs3/assets/90439269/74a9fcbb-b938-497b-bf25-7bb59300f9ee)
![BLUS30847_screenshot_2023_11_12_02_31_51](https://github.com/RPCS3/rpcs3/assets/90439269/51d970b2-a670-43e7-990f-a752d19ee414)
![BLUS30847_screenshot_2023_11_12_02_31_40](https://github.com/RPCS3/rpcs3/assets/90439269/36af71ce-74d9-41c7-93e2-a95fdac96445)

with 200% upscale and shader quality on low

**Comment by kd-11** [comment]
I need a fresh RSX capture. The old one from the previous ticket doesn't load anymore.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/14834

**Comment by 19Aidan** [comment]
> Fixed by #14834
![BLUS30847_screenshot_2023_11_20_18_26_07](https://github.com/RPCS3/rpcs3/assets/90439269/c41050a5-95e7-4446-b8c6-a70ea7f84b89)
![BLUS30847_screenshot_2023_11_20_18_26_03](https://github.com/RPCS3/rpcs3/assets/90439269/a69c4739-09a1-442e-95b2-6b1c43b76cd7)
![BLUS30847_screenshot_2023_11_20_18_25_59](https://github.com/RPCS3/rpcs3/assets/90439269/d2aba77b-2264-4d8d-8ff7-65aa186646ed)
![BLUS30847_screenshot_2023_11_20_18_25_38](https://github.com/RPCS3/rpcs3/assets/90439269/cd589ab0-e3a3-45df-a980-42a3c8cb60e8)
can confirm. will close once it has been merged.
