### ISSUE TITLE
OpenAL32.dll is missing

### ISSUE THREAD

**Issue by Kilowog01** [RPCS3/rpcs3#1478]
I already tried to install:
 Visual Studio 2015
 Vcredist_x86
 Vcredist_x64

I'm using Windows 10 Pro Insider Preview

**Comment by Kilowog01** [comment]
https://www.openal.org/downloads/oalinst.zip

OK
I followed the logic that should have followed since the beginning of trying to find the site that such OpenAL, I was the link, downloaded, installed and automatically worked.
This is very stupid, because they do not deliver download it all together and make it clear that you need to install it to use rpcs3?

**Comment by danilaml** [comment]
@Kilowog01 where did you get the build from? Appveyor and emunewz builds should have this dll included: https://github.com/RPCS3/rpcs3/tree/master/bin

**Comment by tambry** [comment]
Get an [official build](https://github.com/Bigpet/rpcs3/releases).
