### ISSUE TITLE
website: Replace "M1" with "Apple Silicon" (macOS download description)

### ISSUE THREAD

**Issue by rxhfcy** [RPCS3/rpcs3#14791]
### Quick summary

On the download website (https://rpcs3.net/download), the macOS description text only talks about "M1" (launched in 2020), no mention of M2 (launched in 2022) or M3 (2023) etc.

### Details

https://rpcs3.net/download: "M1" (launched in 2020) should probably be replaced by "**Apple Silicon**" which is Apple's general marketing name for **all** of their new ARM processors (M1, M2, M3 etc).

So basically replace "M1" with "**Apple Silicon**" on [line 136 of inc-download-platform.php](https://github.com/DAGINATSUKO/www-rpcs3/blob/master/public_html/lib/module/download/inc-download-platform.php#L136C86-L136C86)

![Screenshot](https://github.com/RPCS3/rpcs3/assets/42669366/231bf33e-c737-4817-8353-b330fb8d78b7)

PS. I first tried to report this in @DAGINATSUKO's [www-rpcs3 repository](https://github.com/DAGINATSUKO/www-rpcs3/issues/new) but was unable to do so:

>An owner of this repository has limited the ability to open an issue to users that have contributed to this repository in the past.

### Attach a log file

No log file, this is a website issue.

**Comment by DAGINATSUKO** [comment]
For future reference, website issues should be opened here: [https://github.com/DAGINATSUKO/www-rpcs3](https://github.com/DAGINATSUKO/www-rpcs3)

No need to open one though, I will go ahead and make this correction.
