### ISSUE TITLE
Black Screen on Demon Souls

### ISSUE THREAD

**Issue by Wario3493** [RPCS3/rpcs3#14796]
### Quick summary

RPCS3 isn't working correctly, as I am getting a black screen on Demon Souls.

### Details

When I first loaded up RPCS3, it was working fine, but now I have a black screen on Demon Souls and I don't know what the issue is.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13255579/RPCS3.log)

### Attach capture files for visual issues

<img width="875" alt="01" src="https://github.com/RPCS3/rpcs3/assets/130720837/a7880d84-49ee-4e11-b7d7-974a24fc1b36">

### System configuration

16GB RAM, Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz 
GeForce GTX 950

### Other details

All games are having an issue with RPCS3.

**Comment by Jonathan44062** [comment]
Enable Write Color Buffers in GPU Tab of the settings, next time, use the wiki settings

**Comment by AniLeo** [comment]
User error, closing as invalid.
