### ISSUE TITLE
Incorrect Rosetta CPU translation after macOS 14 Sonoma Update in arm64 Mac hardware

### ISSUE THREAD

**Issue by hiakki** [RPCS3/rpcs3#14794]
### Quick summary

Glitchy Characters after Sonoma Update in Mac M1
Games Tested - 
1. Batman: Arkham City
2. Tekken 6
3. The Amazing Spider-Man
4. The Amazing Spider-Man 2

### Details

Batman and Tekken were running fine in Ventura but after upgrading to Sonoma, both games are not playable.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13241202/RPCS3.log)

### Attach capture files for visual issues

<img width="1496" alt="Screenshot 2023-11-02 at 8 24 05 PM" src="https://github.com/RPCS3/rpcs3/assets/24492384/d6ec6494-07a3-470f-ade6-06993ea3fba2">
<img width="1496" alt="Screenshot 2023-11-02 at 8 23 57 PM" src="https://github.com/RPCS3/rpcs3/assets/24492384/40d6c334-c12e-44e0-9845-fdaf08cfb679">

### System configuration

Mac OS - Sonoma
Chip - M1
RAM - 16 GB
RPCS3 - 0.29 Alpha

**Comment by shinra-electric** [comment]
Can you test with version [0.0.29-15703](https://github.com/RPCS3/rpcs3-binaries-mac/releases/download/build-dfa83314df3869d2bb8c3784a666b25e5d6140c7/rpcs3-v0.0.29-15703-dfa83314_macos.dmg) to test whether the MoltenVK bump to 1.2.6 in #14766 was responsible?

**Comment by hiakki** [comment]
1. Tried with the provided version.
2. Removed previous caches.
3. Reset all configs (global and custom game based).

Still facing same issue. Attaching logs for better understanding.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13242703/RPCS3.log)

**Comment by hiakki** [comment]
@shinra-electric  Please let me know if I can perform any action item to contribute on this, maybe testing MoltenVK library in local and provide you logs.

**Comment by shinra-electric** [comment]
I've already tested, MoltenVK is not the issue here. It's something else.

**Comment by kd-11** [comment]
Looks like a CPU instruction emulation bug in rossetta to me. Try setting llvm cpu model to "haswell" in the config file and see if it helps.

**Comment by kd-11** [comment]
> That didn't work for me (for Tekken 6), the game wouldn't boot.
> 
> Incidentally, the intro scene in MGS4 is now hilarious...
> 
>  MGS4.mp4 
> I noticed another issue with MGS4. When installing data, the game shows several "TV channels" that you can switch between. But RPCS3 plays the audio from all the channels at once.

I think that's my mistake. M1 has a very outdated feature-set x86-wise. Maybe try "nehalem' instead. Haswell actually has most modern features present and may be too new. Basically, we want to make sure no AVX code is generated.

**Comment by shinra-electric** [comment]
Same vertex issues with Tekken 6 when using nehalem...
<img width="1624" alt="Screenshot 2023-11-15 at 19 23 12" src="https://github.com/RPCS3/rpcs3/assets/50119606/66638f72-66e6-4274-a332-2e3c9b300efd">

**Comment by soops** [comment]
Any update on this? Friend of mine is seeing similar issues in Rock Band 2 and Skate 3 on M1 Pro (macOS Sonoma)

<img width="1282" alt="34062D86-5988-4E43-959B-531272A28E62" src="https://github.com/RPCS3/rpcs3/assets/8540373/70c8514e-ac8a-45a0-b7dd-1f50af1a4544">
![9AA22BBC-DD16-4BE4-A9F9-480F0961761C](https://github.com/RPCS3/rpcs3/assets/8540373/101eccd4-b095-4206-bdeb-0a1e53808ace)

**Comment by kd-11** [comment]
Not sure if there's anything we can do unless apple decides to explain to us what they changed in the new version. They clearly broke something in rossetta.

**Comment by kd-11** [comment]
I just remembered we have CPU accuracy tests already here: https://github.com/RPCS3/ps3autotests/tree/master/tests/cpu
It would be enlightening to get sonoma output and compare to a normal x86 cpu.

**Comment by soops** [comment]
I will do that

**Comment by soops** [comment]
@kd-11, I am wondering what the process for building and running these tests is like. Could someone point me to tools? Should I simply use GCC? I’m somewhat knowledgeable about building so it’s really just a matter of giving me some basic pointers. I’d like to do my part to give you something to take a look at, but this is my first time messing around with anything for the PS3 platform. Thanks

**Comment by kd-11** [comment]
> @kd-11, I am wondering what the process for building and running these tests is like. Could someone point me to tools? Should I simply use GCC? I’m somewhat knowledgeable about building so it’s really just a matter of giving me some basic pointers. I’d like to do my part to give you something to take a look at, but this is my first time messing around with anything for the PS3 platform. Thanks

Autotests are already compiled. Just run the self files from the emulator menu.

**Comment by shinra-electric** [comment]
> Autotests are already compiled. Just run the self files from the emulator menu.

I presume we just run `Boot Test` 
<img width="387" alt="Screenshot 2023-12-13 at 19 32 55" src="https://github.com/RPCS3/rpcs3/assets/50119606/9b871d76-8bb5-416a-880d-37f45fdf465f">

And we get the TTY.log from `Application Support/Caches/rpcs3` like this help world one: 
[TTY.log](https://github.com/RPCS3/rpcs3/files/13664391/TTY.log)

Should we run the `self` or `elf` files?

I got the TTY log above for the hello world example, but the next one `ppu_branch.ppu.elf` didn't output anything... 

Is there any shortcut for running them

**Comment by soops** [comment]
As @kd-11 stated, run the self files.

**Comment by shinra-electric** [comment]
Here are the CPU tests, with just the `output.txt` file and the expected (I removed the cpp files and the elf/self files). 

[cpu.zip](https://github.com/RPCS3/rpcs3/files/13664618/cpu.zip)

Some of the tests did not have self files, so there is no `output.txt` file enclosed.

**Comment by shinra-electric** [comment]
I ran a couple of RSX tests, but I guess you don't need them for this issue. (FYI, I did notice that some of them did not match the expected output png files, and one of them just crashes)

**Comment by soops** [comment]
Thanks for doing this, @shinra-electric

**Comment by kd-11** [comment]
> I ran a couple of RSX tests, but I guess you don't need them for this issue. (FYI, I did notice that some of them did not match the expected output png files, and one of them just crashes)

Yea, we don't need them. I don't know of any broken tests on proper platforms, so the crashes or bugs may be macos-specific.

**Comment by kd-11** [comment]
> Here are the CPU tests, with just the `output.txt` file and the expected (I removed the cpp files and the elf/self files).
> 
> [cpu.zip](https://github.com/RPCS3/rpcs3/files/13664618/cpu.zip)
> 
> Some of the tests did not have self files, so there is no `output.txt` file enclosed.
> 
> Edit: Just to confirm, I'm on Sonoma 14.2 with an M1 Pro. RPCS3 version 0.0.29-15786

I checked the output for the ppu arithmetic test. It looks like handling of NaN has changed. Rosetta is now emitting a different NaN encoding than normal CPUs (compared to my own ryzen). The sign flag is now always set for all NaN values on M1.
e.g +NaN + 0 = -NaN, +NaN * 0 = -NaN, etc

**Comment by Xiseous** [comment]
> > Autotests are already compiled. Just run the self files from the emulator menu.
> 
> I presume we just run `Boot Test` <img alt="Screenshot 2023-12-13 at 19 32 55" width="387" src="https://private-user-images.githubusercontent.com/50119606/290292944-9b871d76-8bb5-416a-880d-37f45fdf465f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTk4NzAsIm5iZiI6MTcwMjY1OTU3MCwicGF0aCI6Ii81MDExOTYwNi8yOTAyOTI5NDQtOWI4NzFkNzYtOGJiNS00MTZhLTg4MGQtMzdmNDVmZGY0NjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE2NTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ODk1Njk0M2MzZDg0ZTkyMzcyY2YxZmE3MzQ5NThmOTVhZjgxODc4ZmFhMzY5OGUyNmQ1ZTU3MmI5YzkzYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OlfKI14ctwQGfwUoN7hlVe3-tkID9JrF0LdxvUcwbNQ">
> 
> ~And we get the TTY.log from `Application Support/Caches/rpcs3` like this hello world one:~ [TTY.log](https://github.com/RPCS3/rpcs3/files/13664391/TTY.log)
> 
> ~Should we run the `self` or `elf` files?~
> 
> ~I got the TTY log above for the hello world example, but the next one `ppu_branch.ppu.elf` didn't output anything...~
> 
> Is there any shortcut for running them all at once? Or do we just run them one by one?
> 
> Edit: Oh, I just noticed there is an `output.txt` file in the folder after it was run. I'll run through them all and post here soon.

Could you link me where these files are?

When I click Boot Test it just opens a finder window on my main HDD.

**Comment by Xiseous** [comment]
I've ran all the tests from that link mentioned above,

Only running .elfs unless the file name different for the .self file in that same folder.

I've ran all the tests since I'm on the M3 Max (14-CPU, 30-GPU) so the issue may be a little different, wanted to also note that on the RSX test, primitives were incosistant to the references as well as many missing sections in the texture_formats compared to the reference.

As someone else stated, some didn't produce any output.txt and some didn't exit either and stayed open for a prolonged period of time such as;

- spu_fpu.ppu.elf
- spu_test.ppu.elf
- methods_sce_driver.ppu.self = Produces empty output.txt, stuck on black screen (0fps)

RSX:
Dynamics - Loaded Fine, 1 = Flashing Red, 2 = Fine, 3 = Smooth compared to reference which can be called "crispy"
All Static loaded fine, no artifacting.

[tests.zip](https://github.com/RPCS3/rpcs3/files/13688983/tests.zip)

I've also been getting the following errors after each test with RPCS3 crashing to desktop,
<img width="680" alt="Screenshot 2023-12-13 at 19 22 45" src="https://github.com/RPCS3/rpcs3/assets/64169979/0555b599-ffea-49c1-a7cb-3def1a7e043e">
<img width="686" alt="Screenshot 2023-12-15 at 19 31 11" src="https://github.com/RPCS3/rpcs3/assets/64169979/61857eb3-2197-4748-bb21-0870b0f8c756">
<img width="678" alt="Screenshot 2023-12-15 at 19 34 04" src="https://github.com/RPCS3/rpcs3/assets/64169979/87b5d879-11ab-447f-8822-ec6fed19c97f">
<img width="680" alt="Screenshot 2023-12-15 at 19 36 33" src="https://github.com/RPCS3/rpcs3/assets/64169979/19b7e3a4-577d-4a18-b688-3f63e3571ab2">
<img width="681" alt="Screenshot 2023-12-15 at 19 37 55" src="https://github.com/RPCS3/rpcs3/assets/64169979/1b6aaa36-34de-47e5-a170-3a450bd9f217">
<img width="688" alt="Screenshot 2023-12-15 at 19 38 20" src="https://github.com/RPCS3/rpcs3/assets/64169979/69c905fb-97d0-40da-b04d-3831c496b2ca">

Let me know if anything else could help

**Comment by shinra-electric** [comment]
FYI this issue is fixed in Sonoma 14.3 beta. 

14.2: 
<img width="1624" alt="Screenshot_2023-12-03_at_14 29 30" src="https://github.com/RPCS3/rpcs3/assets/50119606/1a3a40dc-96ea-43d4-ab2e-e84798ec5fc2">
14.3 beta:
<img width="1624" alt="Screenshot 2023-12-20 at 20 31 28" src="https://github.com/RPCS3/rpcs3/assets/50119606/d127cce6-375b-485d-85c4-695ecd46548d">

**Comment by hiakki** [comment]
Thanks for informing @shinra-electric 

Tekken 6 - Verified - Working
<img width="1368" alt="image" src="https://github.com/RPCS3/rpcs3/assets/24492384/f788436a-9406-4b8e-bf27-a74a538ffaf7">

Batman Arkham City - Verified - Working (Previously both characters were invisible and even in mirror no shadows were there)
<img width="1483" alt="image" src="https://github.com/RPCS3/rpcs3/assets/24492384/426b6f1f-447e-405b-bc63-4a5c58088628">

**Comment by cmcchai** [comment]
I had this issue, where characters look like thin paper.
And it's fixed after updating from sonoma 14.2.0 to sonoma 14.3 beta.

Before (screenshot and log):
![before](https://github.com/RPCS3/rpcs3/assets/76714924/5dfb0871-2f39-4cac-8793-5210ac372baf)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13764330/RPCS3.log.gz)

After (screenshot and log):
![after](https://github.com/RPCS3/rpcs3/assets/76714924/cfb0680b-51c1-4a32-9906-d4c903a2a400)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13764298/RPCS3.log.gz)

ps: thanks for the discord help by ALH.

**Comment by Prakash4844** [comment]
Having similar issue is Batman Arkham Origins: 

Missing Character model for Batman and Thugs:

![image](https://github.com/RPCS3/rpcs3/assets/81550376/3f86ab2c-4d3c-43ee-8503-20844529c8e5)
![image](https://github.com/RPCS3/rpcs3/assets/81550376/8f6075fa-18b8-486c-ac51-a2263232c972)
![image](https://github.com/RPCS3/rpcs3/assets/81550376/095aafc9-41dc-4f18-bcef-193224959338)
![image](https://github.com/RPCS3/rpcs3/assets/81550376/7c22891e-b18a-40e6-a5bf-b4c3645769b3)


1D Batman:
![image](https://github.com/RPCS3/rpcs3/assets/81550376/b1a835a3-0dcf-47a8-ac08-68b0dcfc928d)
![image](https://github.com/RPCS3/rpcs3/assets/81550376/6b3495d1-7728-466a-b729-79e3c663a853)
![image](https://github.com/RPCS3/rpcs3/assets/81550376/e4b70f71-3a95-4824-bb56-a42459e22c97)

**Comment by AniLeo** [comment]
This is fixed on macOS 14.3, so I'm going to close the issue, it's not even our bug.

**Comment by AniLeo** [comment]
Is anyone experiencing this bug again on macOS 14.3 stable, or is it really fixed now like in the beta?

**Comment by shinra-electric** [comment]
Still fixed for me: 
<img width="1476" alt="Screenshot 2024-01-27 at 17 14 45" src="https://github.com/RPCS3/rpcs3/assets/50119606/3baf8b1a-cd1f-455c-bbd2-278cfe0588b5">
