### ISSUE TITLE
Cameras Not Working

### ISSUE THREAD

**Issue by sirj0k3r** [RPCS3/rpcs3#14795]
### Quick summary

Despite the selected camera and resolution, the system always displays a black screen.

### Issue Description

When entering the Config > Cameras menu entry, despite the selected device or resolution nothing will show up.

This might be related to the fact that RPCS3 is not an entry on Privacy > Camera on System Settings
![image](https://github.com/RPCS3/rpcs3/assets/31699976/b9cb8ef6-a810-4649-852a-fe0e7a5cbf2b)

Looking into this I checked Info.plist, which in fact does have what I believe is the correct key to use the camera (line 33):
![image](https://github.com/RPCS3/rpcs3/assets/31699976/e797e079-2a02-4c2d-9399-3514de189a79)

However, there's no prompt to grant camera permissions and the following error can be seen on Terminal when accessing Configuration > Cameras and changing between devices or resolutions:
> qt.permissions: Could not find permission plugin for QCameraPermission. Please make sure you have included the required usage description in your Info.plist
Access to camera not granted

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13247932/RPCS3.log.gz)

### System and Software Details

**System**
- macOS 14.0
- Apple Silicon

**Software**
- **RPCS3** 0.0.29-15711-e26d4e17 Alpha | HEAD
- **Qt** 6.6.0

**Comment by Megamouse** [comment]
Can you test this build?
https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzg3OTgvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitNYWM1/content?format=zip

**Comment by sirj0k3r** [comment]
> Can you test this build? https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzg3OTgvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitNYWM1/content?format=zip

Got the warning but no request. Not even when I first started the application (I'm sorry that is lacking from the video but it's already 9MB and I could only upload 10MB).

https://github.com/RPCS3/rpcs3/assets/31699976/42e39ccd-4a14-40b2-a89d-a50f2fb5ca81

**Comment by Megamouse** [comment]
Upload the related log file

**Comment by sirj0k3r** [comment]
> Upload the related log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13288581/RPCS3.log)
