### ISSUE TITLE
[Feature request] Native ARM64 support for Windows/Mac

### ISSUE THREAD

**Issue by Jacoby1218** [RPCS3/rpcs3#14819]
### Quick summary

Native ARM64 builds for both Windows and Mac

### Details

Given that both Apple and Qualcomm have announced/produced ARM64 chips, this is probably at least worth considering. Apple's M-series processors are quite fast, and the new Qualcomm CPUs should at least be competitive. The big question mark, though, is if the Adreno GPU drivers on Windows are going to be any good (probably not, but we can hope).

**Comment by Darkhost1999** [comment]
Guess we should slap an in-progress label on this and backdate it. Initial progress has already started and there are attempts to get everything successfully running and shipping.

**Comment by kd-11** [comment]
Mac arm64 is pretty hopeless right now due to page size constraints. There are some ways around it to allow 4k pages on macOS but who knows how long they'll support that. That said, you can already compile an arm64 build yourself if you have the know how. And technically they work, just not very compatible with many games.

**Comment by shinra-electric** [comment]
Unfortunately I haven't been able to compile an arm64 build since Sonoma/Xcode 15. @nastys had made a PR (#14452) regarding this, but he doesn't seem to have finished it...

**Comment by kd-11** [comment]
Page size is still an issue for AAA but smaller games will work fine. Older games and the smaller-scale PSN titles already run ok on linux arm64 just with serious graphical glitches that I'm looking into. Unlike the apple M-series chips, I believe the snapdragon ones should support 4k pages out of the box which should make the windows builds more viable.

**Comment by ddscentral** [comment]
Any news on this ?
My Windows ARM64 (X Elite) tablet will arrive soon, would be willing to test when Windows ARM support arrives.

**Comment by AniLeo** [comment]
Can be closed as completed. No plans to distribute Windows builds for now, but you can compile it yourself.

**Comment by ddscentral** [comment]
Thanks for the information.
