### ISSUE TITLE
[Feature request] Internet connection support in XMB/VSH

### ISSUE THREAD

**Issue by Gorilli09** [RPCS3/rpcs3#14816]
### Quick summary

I wanted to set up internet connectivity for XMB/VSH during first boot.

**Comment by ReLyf47** [comment]
No

In the not so distant future RPCS3 will not even need PS3 firmware to use
So adding this feature would be useless

**Comment by Darkhost1999** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/60384196/38d3d1c7-a689-413c-bb71-71b65a3e4b9a)
I'm sure you mean low-level implementation so the vsh knows the internet is connected. But HLE already works and the Internet works

**Comment by Darkhost1999** [comment]
What is shown not working is the PS3's inability to render modern websites correctly and that's very unlikely to change.

**Comment by Gael2433** [comment]
For what reason do you need network connectivity passed on to vsh anyway? rpcs3 will never connect to PSN.

**Comment by Gorilli09** [comment]
> For what reason do you need network connectivity passed on to vsh anyway? rpcs3 will never connect to PSN.

Internet Browser

**Comment by FlexBy420** [comment]
Web browser already works in XMB, just set network status to connected in config
