### ISSUE TITLE
Gran Turismo 6 stuck at loading screen

### ISSUE THREAD

**Issue by alexou2** [RPCS3/rpcs3#14810]
### Quick summary

Gran Turismo 6 is stuck at the loading sceen or at the disclaimer screen. I was able to play, but i had to change some settings because of glitches. I just disabled audio buffering and enabled write color buffer. this broke the game.

### Details

the game can't get past the loading screen or disclaimer screen

### Attach a log file

I can't find the log files
this is the content of the log window in the app

E SYS: 'cellSaveDataAutoLoad2' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
U sys_net TODO: sys_net_infoctl(cmd=53, arg=*0x425bc548)
E SYS: 'cellNetCtlGetInfo' failed with 0x80130108 : CELL_NET_CTL_ERROR_NOT_CONNECTED [1]
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, database/gt6 [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/database” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES01893/USRDIR/PDIPFS/K/96” [1] x2
U sceNpTrophy TODO: sceNpTrophySetSoundLevel(context=0x1, handle=0x1, level=50, options=0x0)
U cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=250, func=*0x14d54c0, userData=*0x4ffe2000)

### Attach capture files for visual issues

![image](https://github.com/RPCS3/rpcs3/assets/92472779/c013c4c4-294c-4600-b625-eb6ed8013207)

### System configuration

distro: kubuntu 23.04
cpu: R5 5600
gpu: rx 6700xt
kernel: 6.2.0-36-generic

### Other details

I tried uninstalling rpcs3
I installed another release of the game and I still had the same issue
I cleared all the caches and reset the configurations

**Comment by AniLeo** [comment]
This is a support request and should go in one of the support platforms. No log file and you're not even using the official build.
