### ISSUE TITLE
RSX Exception (HRESULT = 0x80070057 in D3D12GSRender::flip) - Family Feud [NPUB30188]

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1482]
```
{PPU Thread[0x58] (MyUserInterface)[0x00a7d80c]} cellPngDec: pngDecodeData: stbi_load_from_memory failed

{PPU Thread[0x58] (MyUserInterface)[0x00a7c36c]} cellSysutil: cellSaveDataUserListAutoLoad(version=0, userId=0, errDialog=0, setList=*0xd009f224, setBuf=*0xd009f234, funcFixed=*0xc4a090, funcStat=*0xc4a0b8, funcFile=*0xc4a0a0, container=0xffffffff, userdata=*0x2eb35ed8)

{PPU Thread[0x58] (MyUserInterface)[0x00a7c42c]} cellSysutil: The game saves data automatically at certain points. Do not switch off the power or press the PS button when the HDD access indicator is flashing.

{rsx::thread} Exception: HRESULT = 0x80070057
(in file Emu\RSX\D3D12\D3D12GSRender.cpp:431, in function D3D12GSRender::flip)
Please report this to the developers.
```

Complete log attached @ [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/120790/RPCS3.zip)

This also happens:
![screenshot_19](https://cloud.githubusercontent.com/assets/10283761/12873803/db11b2a6-cdbe-11e5-994e-cd70b840c419.png)
After that, I stop the game and the above output happens

**LLE'd**
cellFiber
cellSpursJq
cellSre
cellSync

**Comment by tambry** [comment]
@MyaniPT Try setting frame limiter to Auto. I've heard that it may fix the DX12 flip exception. The message box is also known. Png decoding error is likely currently irrelevant due to #1359.

**Comment by MyaniPT** [comment]
I tried, the same issue persists.
VSync is off, Frame limiter is set to Auto.

**Comment by MyaniPT** [comment]
Also happens in:
- Sword Art Online - Lost Song **[BLAS50970]**

With DirectX12

**Comment by MyaniPT** [comment]
Also happens in:
- Auditorium HD **[NPUB30245]**

```
{rsx::thread} Exception: HRESULT = 0x80070057
(in file Emu\RSX\D3D12\D3D12RenderTargetSets.cpp:405, in function D3D12GSRender::copy_render_target_to_dma_location)
Please report this to the developers.
```

Log @ [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/121500/RPCS3.zip)

**Comment by tambry** [comment]
You're more or less posting about **different** errors. For example one as you demonstrated happens in _copy_render_target_to_dma_location_ and the on in the original post in _flip_. It would possibly be better to have seperate threads for seprate problems, as _0x80070057_ is a generic DirectX error, AFAIK.

**Comment by MyaniPT** [comment]
Sorry, I noticed it happened in a different function but I didn't know it was a generic DX error, thought it would fit in this issue.
Should I open a separate issue then?

**Comment by tambry** [comment]
@MyaniPT I think a seperate issue would be fitting.

**Comment by MyaniPT** [comment]
```
{rsx::thread} Exception: HRESULT = 0x80070057
(in file Emu\RSX\D3D12\D3D12GSRender.cpp:431, in function D3D12GSRender::flip)
Please report this to the developers.
```

PPU2
SPU2

Beat Hazard Ultra **[NPEB00620]** - 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/121533/RPCS3.zip)

**Comment by MyaniPT** [comment]
May be irrelevant because It's probably not related to the W/R buffers, but tested with W/R buffers off and the error persists.

**Comment by tambry** [comment]
I doubt it's related to R/W buffers. Those aren't really needed on DX12 right now. They may be required for some AAA games that do rendering on SPUs. (Last of Us, God of War, etc)

**Comment by MyaniPT** [comment]
As of latest master:
```
{rsx::thread} Exception: HRESULT = The parameter is incorrect.
(in file Emu\RSX\D3D12\D3D12GSRender.cpp:469, in function D3D12GSRender::flip)
```
[BLAS50970] SAO Lost Song

**Comment by raven02** [comment]
I'm closing this one . The above HRESULT error should be fixed from https://github.com/RPCS3/rpcs3/issues/1565
