### ISSUE TITLE
[Feature Request] Minimize Batch Creation

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#14825]
### Quick Summary

Add the ability to minimize LLVM cache batch creation

### Details

Several things here
![image](https://github.com/RPCS3/rpcs3/assets/60384196/a64e71c7-83dc-4bea-a1eb-6a5ed94f7704)
- If we compile both PPU and SPU cache now together during this batch creator shouldn't this just say creating LLVM cache again? Like how it did originally.
- Can we please have control over the interface to adjust any config, from pads to rpcn to custom configs that aren't used during batch creation, to enable navigation between what we're able to while cache compiles or is it safer to allow minimizing the batch creator so we can continue interacting with our desktop and other not RPCS3 applications.
- Can we resize the window's default size to allow it to look like the ... is there on purpose and not to cut off words that don't fit inside the Q message box? Just about 1.5x bigger of a window or 1.25x bigger resize.

Some of these things I'm capable of. But minimizing the Qmessage box is something I haven't seen yet and am interested in learning how to do. I can resize the window and replace Qstrings easily enough.

**Comment by Megamouse** [comment]
It's a modal dialog because most interactions can potentially create issues and it's just not worth adding checks everywhere for this one case.
