### ISSUE TITLE
Assasin's Creed [BLES00158] game data corrupted

### ISSUE THREAD

**Issue by koenegamer** [RPCS3/rpcs3#14823]
### Quick summary

I loaded this game and when I do that it says that my game data has corrupted but I deleted it and then loaded it again and it still happened. What am I doing wrong here?

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13369924/RPCS3.log.gz)

**Comment by Darkhost1999** [comment]
2 things

- This is a support request that belongs on the discord or the forums.

- We don't provide support for pirated games. You must use your own disc to create a copy from your PS3 or compatible bluray drive. Please refer to the Quickstart guide to get started.
