### ISSUE TITLE
LittleBigPlanet Karting showing a black screen

### ISSUE THREAD

**Issue by JalvinGaming** [RPCS3/rpcs3#14824]
### Quick summary

I tried following guides on how to run LBPK properly, yet when I run the game, the screen is still black. How do I fix this?
![image](https://github.com/RPCS3/rpcs3/assets/65038023/9ecd77bb-d039-4bf0-be5a-c9d8b8959743)

### Details

After I boot up the game, it recompiles using ASMJIT, the screen turns completely black. Color buffers are enabled and ZCULL accuracy is Precise.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13382197/RPCS3.log)

### System configuration

CPU: Intel i-5 9600K
GPU: NVIDIA RTX 3070 Ti

**Comment by FlexBy420** [comment]
You are using very wrong settings that this game doesnt need. Support request goes on discord or forums, not github.

**Comment by AniLeo** [comment]
Closing incorrect report.
