### ISSUE TITLE
Rock Band 3 - BLUS30463 "VM: Access violation reading location 0x626653c"

### ISSUE THREAD

**Issue by technetiumhat** [RPCS3/rpcs3#14829]
### Quick summary

I decided recently to start playing Rock Band 3 Deluxe via RPCS3 after resetting my laptop, only to be met with this error every time I open the game.
Set up using the Definitive guide from the RB3DX website

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13399635/RPCS3.log.gz)

### System configuration

Acer Nitro 5 AN515-57
GeForce RTX 3050ti 4GB
i7-11800H
16GB RAM

**Comment by YuriNator557** [comment]
Invalid issue, modded game

**Comment by AniLeo** [comment]
Log shows user error, this is a support request so it should go on Discord or Forums, not an issue report
