### ISSUE TITLE
[Feature request] Official verified flatpak on Flathub

### ISSUE THREAD

**Issue by mak448a** [RPCS3/rpcs3#14831]
### Quick summary

Please make an official package for RPCS3 on Flathub. Thank you!

### Details

There is already an unofficial app at https://flathub.org/apps/net.rpcs3.RPCS3, but could you add an official package?

**Comment by MSuih** [comment]
There's a dozen or so different packaging methods on Linux, maintaining them all would be too much work for us.. We've decided to stick with AppImage and our [AUR package](https://aur.archlinux.org/packages/rpcs3-git) and aren't interested in officially supporting anything else.

Besides, you're not giving any arguments about why we shold support flatpak specifically.

**Comment by pollux78** [comment]
I recently noticed that the rpcs3 on flathub is unverified, so i was looking to open a issue about rpcs3 supporting flathub officially, in my opinion flatpak is the best option for distributing software across all linux distro's, why you may ask? 

1. Well the biggest one linux users do not go to the web to grab software as the first option
2. There is gui stores on every major linux distro or terminal that people go through, appimage is fine but it doesn't appear on those gui stores like gnome-software, discover, bazaar that only support flatpak and some supporting system packages depending on the distro
3. Appimage is a file that you launch through the file manager, this is not the same as a .exe on windows where it creates a desktop shortcut after it gets installed, yes you can use apps like gear lever to create a shortcut for the appimage but that's not the default behavior for appimage, flatpak on the other hand creates that shortcut in the app launcher/library
4. You get free advertising on flathub.org and not just that on every gui software store like discover, gnome-software, bazaar promote apps when you do updates for the package 
5. Flatpak is containerized meaning you wont need to worry about supporting every distro, you can focus on fixing problems within flatpak which is similar to appimage
6. The user doesn't need to go and grab a new appimage everytime for updates, they can just update the app through the gui software store that is already installed on their linux install
7. Problems tho is developers would need to learn how flatpak works and using xdg-desktop-portal to get some of the functionality back like the file picker or things like rich presence and if the user wants to add games from other locations that flatpak cant see by default would need to be figured out, good thing tho is every major linux distro has xdg-desktop-portal installed, if you want to read more about desktop portal you can find its documentation here https://flatpak.github.io/xdg-desktop-portal/


## Apps being advertised on flathub.org

<img width="1872" height="913" alt="Image" src="https://github.com/user-attachments/assets/509fc15f-9c85-47c0-9729-2647ff7946b6" />

## Bazzar gui store promoting applications

<img width="1250" height="719" alt="Image" src="https://github.com/user-attachments/assets/d827b345-1b21-409c-9bd2-4c9994383125" />

## Discover showing updated and most popular applications on flathub

<img width="1081" height="710" alt="Image" src="https://github.com/user-attachments/assets/e0c851a8-172e-4571-855c-ae3b7f67f394" />
