### ISSUE TITLE
Ratchet & Clank Tools of Destruction graphical corruption on RDNA3

### ISSUE THREAD

**Issue by LasagnaPie** [RPCS3/rpcs3#14838]
### Quick summary

Black squares covers half the screen when using the Weapon Shop or Armor shop./ 

### Details

Black squares covers half the screen when using the Weapon Shop or Armor shop, the larger the window the more it covers the screen.  I tried deleting the cache and using the default configurations 

![R C](https://github.com/RPCS3/rpcs3/assets/7449866/c3a88a50-f5d4-4933-ab2d-f544c1bc72ea)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13460339/RPCS3.log.gz)

### System configuration

Ryzen 7800X3D
Radeon 7900 XTX
Windows 11

**Comment by LasagnaPie** [comment]
This problem is worst in Ratchet & Clank Crack in Time, half the screen is covered in black transparent squares. 

![R CCC](https://github.com/RPCS3/rpcs3/assets/7449866/4dd96b42-23fd-4401-8761-270e243af643)

**Comment by Jonathan44062** [comment]
Your settings are bad, reset them back to default and test again
![image](https://github.com/RPCS3/rpcs3/assets/78843189/5b736af1-1282-48c6-a8fa-53e1a396aac9)

**Comment by LasagnaPie** [comment]
> Your settings are bad, reset them back to default and test again ![image](https://private-user-images.githubusercontent.com/78843189/285520853-5b736af1-1282-48c6-a8fa-53e1a396aac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NTU1MTcsIm5iZiI6MTcwMDg1NTIxNywicGF0aCI6Ii83ODg0MzE4OS8yODU1MjA4NTMtNWI3MzZhZjEtMTI4Mi00OGM2LWE4ZmEtNTNlMWEzOTZhYWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDE5NDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YTc5OTI4ZDA5MzIzMjFiZjIxMTc5MmIzYmY1ZDVkZjJhMmVhNTZmMzJjYzZkYTlhOTE3N2M0MzY5N2JmNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p2k7-nj4Mntp4GifTfle_tQCkbtiut4E2oEGC3y50Jo)

Makes no difference

**Comment by AniLeo** [comment]
Need new log and screenshot with the default settings

**Comment by kd-11** [comment]
Definitely RDNA3 specific. In case of hw-specific problems the first thing to try is actually strict rendering mode. However, knowing this engine I would also recommend to try default settings + MSAA disabled to rule out insomniac upscaling problems if present.

**Comment by LasagnaPie** [comment]
![fff](https://github.com/RPCS3/rpcs3/assets/7449866/5be23caa-ef25-4c23-b173-2921893237f3)

**Comment by AniLeo** [comment]
Can you upload a log using the latest RPCS3 version for either a Vulkan or OpenGL run, as well as a screenshot from the bug in OpenGL?

Using only the default settings + settings listed in the wiki page for the game

Also, in case someone out there has RDNA3 and Linux, it would be helpful to know if this bug also happens in RADV (I'm guessing not)

**Comment by LasagnaPie** [comment]
[Ratchet and Clank Future Tools of Destruction [BCUS98127].log.gz](https://github.com/RPCS3/rpcs3/files/13826747/Ratchet.and.Clank.Future.Tools.of.Destruction.BCUS98127.log.gz)

https://www.youtube.com/watch?v=4Qh6YBay9jQ

**Comment by AniLeo** [comment]
As suggested in the other RDNA3 issue, can you try the "high precision Z buffer" option with OpenGL?

Right now we need:

- Screenshot of the OpenGL output for the same issue, to see how it looks like
- We're also looking for a RenderDoc capture of the issue, if anyone is able to provide one.

**Comment by Wolver32** [comment]
I noticed the same issue in Gran Turismo 6, but only when the game in windowed mode (like the screenshots above). Running the game in fullscreen doesn't show any artifacts on my 7800 XT. 
Can confirm that, at least on GT6, it doesn't happen in RADV on Linux (even in windowed mode).

**Comment by asp0909** [comment]
hello! I just wanted to say that I haven't been able to replicate the problem...I don't know if they've already fixed it? I have rx 7900 xtx, but my cpu is an intel 9900k

![Captura de pantalla (2)](https://github.com/RPCS3/rpcs3/assets/29218473/fc4ec876-3189-4553-82d0-bdb5dd51fcb1)

**Comment by AniLeo** [comment]
Can you upload a log file to see more system details? Also need confirmation from original reporter

**Comment by asp0909** [comment]
> Can you upload a log file to see more system details? Also need confirmation from original reporter

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14090840/RPCS3.log.gz)

**Comment by LasagnaPie** [comment]
The latest RPCS3 and AMD Drivers  (Resolution Scale @ 300% 3840x2160) 

Vulkan
![RC-VL](https://github.com/RPCS3/rpcs3/assets/7449866/bdf4fdeb-c0a8-43e5-b58f-d474bb8f79cb)

OpenGL
![RC-GL](https://github.com/RPCS3/rpcs3/assets/7449866/1b5f8d53-d65a-4ba4-87c8-92db82efa80e)

**Comment by asp0909** [comment]
There is a similar problem in metal gear 4 that I mentioned above kd 11... that solution must be from amd drivers?

**Comment by LasagnaPie** [comment]
Ratchet & Clank Future : A Crack in Time (Resolution Scale @ 300% 3840x2160)

Vulkan
![RCF_VL](https://github.com/RPCS3/rpcs3/assets/7449866/9093afe7-5acc-44c2-96f2-4c7483b6c320)

OpenGL
![RCF_GL](https://github.com/RPCS3/rpcs3/assets/7449866/b0010f9d-3df3-4ac3-92a8-7f0721c5c31e)

**Comment by LasagnaPie** [comment]
This might be worth noting, but this corruption at the bottom here starts in Crack in time on pixel 1920th pixel, exactly in the middle, even at the normal resolution scale.  

Ratchet & Clank Future : A Crack in Time (Resolution Scale @ 100% 1280x720)
![RCF_VL](https://github.com/RPCS3/rpcs3/assets/7449866/151c37b6-afa6-484b-b8c2-b1b1c8c66de9)

begins her on the 640th pixel.

**Comment by LasagnaPie** [comment]
Ratchet & Clank Future : A Crack in Time (Resolution Scale @ 800% 10240x5760)
![maxx](https://github.com/RPCS3/rpcs3/assets/7449866/1bc70dd6-e125-4db7-b98e-b3bef07f2ea6)

are black squares a visualization of the stencil buffer?

**Comment by kd-11** [comment]
AMD is aware of the RDNA3 driver issue. Use OpenGL for now if you can until they release a fix.

**Comment by Wolver32** [comment]
After seeing LasagnaPie's reports, I went back into GT6 to investigate a bit the problem I noticed. In a race menu, this is what I'm getting with Vulkan while in windowed mode:
![Untitled1](https://github.com/RPCS3/rpcs3/assets/130566900/9acfb8e1-3396-471c-ae45-dbe51d9cd960)

And this is how it looks in OpenGL:
![Untitled2](https://github.com/RPCS3/rpcs3/assets/130566900/f3f3a011-189f-4858-997f-9c4917b043b2)

Pressing Alt + Enter to go in fullscreen mode in my case makes the graphical artifact to go away. I took 2 RSX captures, one when the game was in fullscreen and the other when in windowed. Remove the final .zip extension before extracting the archives, I had to add it to upload files directly to Github.

GT6 Fullscreen (normal):
[Fullscreen_BCES01893_20240206224543_capture.rrc.zip.001.zip](https://github.com/RPCS3/rpcs3/files/14186474/Fullscreen_BCES01893_20240206224543_capture.rrc.zip.001.zip)
[Fullscreen_BCES01893_20240206224543_capture.rrc.zip.002.zip](https://github.com/RPCS3/rpcs3/files/14186487/Fullscreen_BCES01893_20240206224543_capture.rrc.zip.002.zip)

GT6 Windowed (graphical artifacts):
[Windowed_BCES01893_20240206224841_capture.rrc.zip.001.zip](https://github.com/RPCS3/rpcs3/files/14186519/Windowed_BCES01893_20240206224841_capture.rrc.zip.001.zip)
[Windowed_BCES01893_20240206224841_capture.rrc.zip.002.zip](https://github.com/RPCS3/rpcs3/files/14186551/Windowed_BCES01893_20240206224841_capture.rrc.zip.002.zip)

I have a RX 7800 XT, GT6 was running with 300% resolution scale (from 720p). This only happens in Windows as I don't remember seeing anything similar in Linux. I'm also getting driver timeouts with PCSX2 with the Windows + Vulkan combo that seem to be RDNA3 specific... Guess there's something weird going on with the AMD Windows driver on the RX 7000 series.

**Comment by LasagnaPie** [comment]
The latest AMD Driver 24.2.1 fixes this issue. 
https://www.amd.com/en/support/kb/release-notes/rn-rad-win-24-2-1

**Comment by Wolver32** [comment]
> The latest AMD Driver 24.2.1 fixes this issue. https://www.amd.com/en/support/kb/release-notes/rn-rad-win-24-2-1

Yup, can confirm also in GT6.

**Comment by AniLeo** [comment]
Closing as fixed by AMD.

Added this to the documentation at https://github.com/RPCS3/rpcs3/wiki/Graphics-Driver-Issues for historical purposes.
