### ISSUE TITLE
Enter a title here

### ISSUE THREAD

**Issue by TCFproject** [RPCS3/rpcs3#14832]
### Quick summary

At the first mission of against the first child, when you have to fight against the giant enemy. Once I kill it, my game freeze

Can you tell me why ?

### Attach a log file

(That enemy)
![Capture d'écran 2023-11-19 234507](https://github.com/RPCS3/rpcs3/assets/81683083/904338bb-f2dc-497d-9c90-f86ba07ef728)

**Comment by AniLeo** [comment]
The issue tracker is for bug reports, not support requests, ask on Discord or Forums
