### ISSUE TITLE
[Feature request] Icon for HDD Access Indicator

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#14841]
### Quick summary

Display a hint whenever hdd is being accessed to prevent shutting down the emulator during hdd access events or when saving the game.

### Details

- Not all games feature an autosave icon or methods to communicate to the users when to not shutdown their game because it might corrupt their game
- Savestates request not to be used while the game is saving and if there's no icon or hint then sometimes Auto save events might not be known about.
- Sometimes users on the discord ask "How do I save my game" and if there was a hint saying "saving..." or whatever it may need to. Then this could just help communicate things to all users improving interaction with RPCS3.

![LOGO_Autosave](https://github.com/RPCS3/rpcs3/assets/60384196/d994b751-04a2-4e5c-ba7b-5015e07525d6)

I imagine this will effect RSX/Overlays

**Comment by elad335** [comment]
It's not relevant for RPCS3 because it does saving differently than PS3, the savedata is not damaged at any point even if a power outage iccurs in the middle of saving. Although we fool the games that the saving takes half a second so it csn display their original icons and it slso helps some games to run properly.

**Comment by elad335** [comment]
So, saving is atomic. You can learn more about this here - https://en.wikipedia.org/wiki/Atomicity_(database_systems)

**Comment by Jack54guythecoder** [comment]
But will there be an Icon tho?

**Comment by Megamouse** [comment]
IF we add an icon everytime something is written to a file you are the first person to demand it to be removed.

**Comment by Jack54guythecoder** [comment]
Is that something bad?
Most games dont have an Icon when saving.
They just tell you the HDD Indicator is flashing.

**Comment by Megamouse** [comment]
Unless you kill the power of your pc we already use the ps3 internal functions to request the game to terminate itself properly.
So there isn't really an issue with writing to the "HDD" unless you forcefully kill the process or you have a sudden blackout.

**Comment by Darkhost1999** [comment]
Is this "graceful shutdown" procedure also used with savestates or something similar to never save the state when the game is saving?
The feedback to users might not even be necessary if the precautions for all the points are already there.

**Comment by elad335** [comment]
I guess the savestates thingie need treatment from our side, it should not behave this way.

**Comment by Darkhost1999** [comment]
Some bulletins relate to https://github.com/RPCS3/rpcs3/issues/15118
But was requesting messages to show globally rather than game-specific.
Although that game specifically calls for and requests those messages.

**Comment by Darkhost1999** [comment]
This saving the state progress indicator was implemented. Is this safe to close cause all concerns have been answered/met?

**Comment by Megamouse** [comment]
It's your issue, why are you asking us? :)

**Comment by Darkhost1999** [comment]
> I guess the savestates thingie need treatment from our side, it should not behave like this.

I don't understand this message. So not sure what treatment was being said was still needed or desired. So I left open for a reminder.

**Comment by elad335** [comment]
As of #15364 introducing savedata operation protection while creating save-state, there is nothing meaningful to address here IMO.
