### ISSUE TITLE
[Regression] Many titles: Crackling audio

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#14850]
### Quick summary

Audio has started "crackling" in many titles.

### Details

The crackling seems more apparent ingame than in e.g. title screens, but it's still there in either case.

### Build with regression

70c35642a4c9748cbd7dbc90c41267a04aa4d7a1 (confirmed with git bisect)

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13495723/RPCS3.log)

### Attach capture files for visual issues

N/A

### System configuration

* OS: Linux Mint 21.2 / kernel 6.2
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070 / driver 535.129

**Comment by Megamouse** [comment]
Please find the exact build that doesn't work

**Comment by Shoegzer** [comment]
Done
