### ISSUE TITLE
SPU: unknown STOP code 0x0 (Out_MBox is empty)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1485]
```
{SPU[0x53] Thread (TGS_CellSpursKernel0)[0x25988]} Exception: Unknown STOP code: 0x0 (Out_MBox is empty)
(in file Emu\Cell\SPUThread.cpp:1382, in function SPUThread::stop_and_signal)
Please report this to the developers.
```

PPU Interpreter 1
SPU Interpreter 1

**LLE'd modules:**
cellSre

Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/120878/RPCS3.zip)

**Comment by tambry** [comment]
Likely caused by SPU emulation problems, but I'm not sure.

**Comment by elfogames** [comment]
I have the same error on CSI: Fatal Conspiracy
PPU Interpreter 2
SPU Interpreter (fast)

LLE'd modules:
cellSre

`{SPU[0x3f] Thread (CellSpursKernel4)[0x1a168]} Exception: Unknown STOP code: 0x0 (Out_MBox is empty)
(in file Emu\Cell\SPUThread.cpp:1382, in function SPUThread::stop_and_signal)
Please report this to the developers.`

**Comment by Altaiar** [comment]
**Super frog 
PPU interpreter 2
SPU interpreter fast**
{SPU[0x6a] Thread (_Multistream SPU Thread)[0x00000]} Exception: Unknown STOP code: 0x0 (Out_MBox is empty)
(in file Emu\Cell\SPUThread.cpp:1382, in function SPUThread::stop_and_signal)
Please report this to the developers.

**Comment by MyaniPT** [comment]
Yeah, I got this error in another game too which I can't recall atm.
If I get it in any more games I'll post.

Also, don't forget your Game IDs and Logs, they're helpful.

**Comment by MyaniPT** [comment]
```
{SPU[0x2a] Thread (FMOD)[0x21d48]} Exception: Unknown STOP code: 0x0 (Out_MBox is empty)
(in file Emu\Cell\SPUThread.cpp:1382, in function SPUThread::stop_and_signal)
```

**NPEA00154** - Gravity Crash (Demo)

**Comment by Altaiar** [comment]
Super frog NPEB01316
PPU interpreter 2
SPU interpreter fast
when i put this files in (dev_flash\sys\external) flashATRAC.pic and libjpgdec.sprx
game have sound and this message is disappear
 {SPU[0x6a] Thread (_Multistream SPU Thread)[0x00000]} Exception: Unknown STOP code: 0x0 (Out_MBox is empty)
(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1382, in function SPUThread::stop_and_signal)

**Comment by sirdanielk** [comment]
I found this error also in two games, but when i enable libaudio.prx as module, the error disappear, and games advance. So, the stop error may be in common with not fully emulation of console, and not error in spu interpreter/recompiler itself

**Comment by AniLeo** [comment]
NPUB31415
```
{SPU[0x4a] Thread (FMOD) [0x1b898]} class fmt::exception thrown: SPUThread::stop_and_signal(): Unknown STOP code: 0x0 (Out_MBox is empty)
(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1390)
```

**Comment by SakataGintokiYT** [comment]
[d2ddb988]
@Nekotekina 
Can you look at this error ^_^
```
F {SPU[0x2000000] Thread (FMOD)} class std::runtime_error thrown: Unknown STOP code: 0x0 (Out_MBox is empty)
(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1290)

```

**Comment by JohnGodgames** [comment]
Yeah this is quite often error.Libaudio.prx helps only with minimum games (Iron man 2).

List of some affected:
```
50 Cent: Blood on the Sand
Adventure Time: Explore the Dungeon Because I Don't Know!
Brütal Legend
Crash Time 4: The Syndicate
Crash Time 5
Fracture
Generator Rex: Agent of Providence
Hannah Montana: The Movie
Legend of the Guardians: The Owls of Ga'Hoole (video game)
Madagascar: Escape 2 Africa
Marvel Super Hero Squad: Comic Combat
MX vs. ATV Reflex
Stormrise
Way of the Samurai 4
Wheelman
Where the Wild Things Are
WWE SmackDown vs. Raw 2010

and more
```

if you need a logs just let me know

**Comment by Nekotekina** [comment]
You most likely forgot to enable some audio decoder LLE libraries.

**Comment by scribam** [comment]
- Mutant Mudds Deluxe [NPUB31415]: can't reproduce the issue
- Shovel Knight [NPUB31682]: can't reproduce the issue
- Superfrog HD [NPEB01316]: can't reproduce the issue
- Gravity Crash [NPEA00154]: can't reproduce the issue
- Tetris [NPUB30226]: can't reproduce the issue
- CSI: Fatal Conspiracy [NPUB30806]: can't reproduce the issue

liblv2.sprx is generally recommended to go further

@JohnGodgames Do you still have the issue with the games you mentioned above?

**Comment by AniLeo** [comment]
I'm closing this since it doesn't seem to be an issue anymore, at least we can't reproduce
