### ISSUE TITLE
[Regression] Pod bubbles broken on LittleBigPlanet

### ISSUE THREAD

**Issue by indianaliam1** [RPCS3/rpcs3#14859]
### Quick summary

on strict rendering mode the bubbles are strangely too transparent and on not strict rendering mode they have strange artifacts

### Details

i can't really describe it much better than a picture does but man, this game never gets a break does it?
![image](https://github.com/RPCS3/rpcs3/assets/70659988/d1226cda-5a5b-4f05-bcff-e30c86bdf6d2)
(strict rendering)
![image](https://github.com/RPCS3/rpcs3/assets/70659988/aaebce31-6f8d-480b-a235-39533186dbe3)
(... unstrict rendering? normal rendering?)

### Build with regression

v0.0.29-15780-c245637c Alpha

### Attach two log files

i don't need to do it for both, do i? ugh.
https://mega.nz/file/zapzCTBQ#grYTbE9dEjvFIZUuMYBC8RzQ_qBNXYH6Ss7abfAV0fM (this is it with strict rendering OFF)
https://mega.nz/file/6fx0GDBT#xbHN_OGRRDnpGtaZBCNV-g2px9XYzpDcnvlQ3qUQU0c (strict rendering ON)

### Attach capture files for visual issues

(i couldn't get the capture to work in either case? obviously i know how to do it seeing as i've done one of these things before.)

### System configuration

os - windows 10
cpu - i5-10400f
gpu - amd rx 580
gpu driver version - 23.11.1

### Other details

why is it always this game that gets dicked over, anyway? i never got that. must have been made with an engine tied together by thoughts and prayers lol

**Comment by Megamouse** [comment]
Issues with patches applied are invalid.

**Comment by indianaliam1** [comment]
yeah keep in mind said patch does nothing but change the server url, doesn't take a genius to figure that out but whatever, wait for someone else to write the same fucking graphical issue up

**Comment by AniLeo** [comment]
This report is invalid nevertheless as you blamed a build that has a 0% chance of being able to introduce the issue you're describing as it doesn't even touch emulator core code. Missing actual build that introduced the regression.
