### ISSUE TITLE
Gets this error while booting a game (ultimate marvel VS Capcom)

### ISSUE THREAD

**Issue by serbesaboy** [RPCS3/rpcs3#14853]
### Quick summary

shows this error

E SYS: 'cellSaveDataAutoLoad2' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
S SPU: New block compiled successfully x394
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contentsico.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents00.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents01.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents02.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents03.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents04.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents05.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents06.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents07.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents08.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents09.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents10.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents11.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents12.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/contents13.bin” [1]
E SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/PS3ContentFile/GDataInstall.dat” [1]

### Attach a log file

[ULTIMATE MARVEL VS CAPCOM 3 [BLUS30787].log.gz](https://github.com/RPCS3/rpcs3/files/13503146/ULTIMATE.MARVEL.VS.CAPCOM.3.BLUS30787.log.gz)

### System configuration

Rog ally z1 extreme

**Comment by Megamouse** [comment]
logging errors like this is normal

**Comment by MSuih** [comment]
Ask for support on our discord, not in github
