### ISSUE TITLE
Some Foundation 9 Entertainment games suffer from crashing

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#14860]
### Quick summary

When testing some [Foundation 9 Entertainment games](https://www.mobygames.com/company/6240/foundation-9-entertainment-inc/) (Digital Eclipse Software, Inc + Backbone Entertainment)

I came across an issue where It tends to crash when trying to make it to the menu.

### Details

Games affected(All use the same engine):
- Championship Sprint
- Gauntlet II
- Joust
- Mortal Kombat II
- Rampage World Tour
- Rampart

### Attach a log file

[Gauntlet II Demo.gz](https://github.com/RPCS3/rpcs3/files/13528272/Gauntlet.II.Demo.gz)

### System configuration

```
SYS: RPCS3 v0.0.29-15780-c245637c Alpha | master
SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.93 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
SYS: Current Time: 2023-12-01T15:22:59
RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 536.23.0.0
SYS: Firmware version: 4.89
```

### Other details

This date back to  2017 but was never fixed https://forums.rpcs3.net/showthread.php?tid=163792&pid=289977#pid289977

**Comment by Asinin3** [comment]
How did you even get ingame in MK2? It just crashes for me.

**Comment by ChwaraeTeg** [comment]
If you've got a cache.dat and cache.idx file in the \dev_hdd0\ folder, try deleting those and relaunching MK2. These files don't get created on real hardware, and seem to be the cause of the crashing/instability in these games.
