### ISSUE TITLE
GL: Sword Art Online - Lost Song invalid location

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1487]
```
{rsx::thread} Exception: Invalid location (offset=0x50, location=0x66626660)
(in file Emu\RSX\RSXThread.cpp:118, in function rsx::get_address)
Please report this to the developers.
```

OpenGL
PPU Interpreter 1
SPU Interpreter 1

**LLE:**
cellFiber
cellSre
cellSpursJq

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/121471/RPCS3.zip)

It shows a few pixels:
![screenshot_27](https://cloud.githubusercontent.com/assets/10283761/12884262/fdc18362-ce54-11e5-88bb-c0d597fff7e0.png)

If trying to boot the game with DX12 it produces the same exception as in #1482

**Comment by Nezarn** [comment]
With latest master DX12 has the same error, so rsx label should be re-added.
log: https://gist.github.com/Nezarn/01c69e0ed90674703025738e12e9d270

> ·F {rsx::thread} class fmt::exception thrown: rsx::get_address(): Invalid location (offset=0x50, location=0x66626660)
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:134)

**Comment by Nezarn** [comment]
@raven02 if you or someone else would be able to backport (+ complete it? since it says WIP) this https://github.com/DHrpcs3/rpcs3/commit/0fcacca64350b41f754cc3e109df3d9686b4f45d game could reach dev logos + loading screen

![rpcs3_2016-10-19_17-57-15](https://cloud.githubusercontent.com/assets/3817985/19526689/84e78c72-9625-11e6-9d97-321279955b11.png)

**Comment by AniLeo** [comment]
Damn good news here, I'd love to boot into that one

**Comment by kd-11** [comment]
Interesting find, I must say. Looks like a rewrite of the dma subsystem.

**Comment by Nezarn** [comment]
@kd-11 well @SakataGintokiYT was the one who posted this in another issue since another game has the same issue as this. #1723

**Comment by Zangetsu38** [comment]
Actually have this 
>E {PPU[0x1000000] Thread (main_thread) [0x01119ba8]} 'cellVideoOutConfigure' failed with 0x8002b221 : CELL_VIDEO_OUT_ERROR_ILLEGAL_CONFIGURATION
F {PPU[0x1000000] Thread (main_thread) [0x01099900]} struct vm::access_violation thrown: Access violation reading address 0x0
