### ISSUE TITLE
Mouse inputs

### ISSUE THREAD

**Issue by RafTube** [RPCS3/rpcs3#14878]
### Quick summary

I got GT5 on the emulator. I wanted to set up my game pad so mouse movements are responsible for the right stick but it wont budge

### Details

Ok in detail heres how things went down. I just installed the emulator for ps3 and I also got Gran Turismo 5 up and running.

 But i run to a couple of issues. I wanted to be able to steer using my mouse and mouse buttons to be responsible for the acceleration and brake.

 The second one i got but steering is a big issue. I tried everything. 

That includes changing the ingame settings to match the emulator's controller, changing mouse handler to NULL, upping the sensitivity to 30 on X and 37.5 on Y which i read was the safest and smoothest ratio and the last thing i tried destroyed the game completely and i cant undo it.

That was maxing out the dead zone on the emulated stick. Now even key steering snaps at the max value.

My system specs are:

CPU: I5 10TH GEN

GPU: NVIDIA RTX3050

RAM: 32 GB @ 3600

### Attach a log file

I dont have one at the moment cause im on my phone but i will provide one as soon as i can

In the mean time here is a like of the youtube video i used to set my mouse steering `up:`

https://youtu.be/LQawjpk76TA?si=-mvrv19n7qO9TakO

**Comment by Megamouse** [comment]
Please go to the rpcs3 discord for help. This is not a support forum.
