### ISSUE TITLE
Just Cause 2 (NPUB30606) - cellRec Verification Failed when using Video Capture feature

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#14871]
### Quick summary

The game's built-in Video Capture feature was recently properly implemented, but now it crashes completely.

### Details

As of #14817, Just Cause 2's Video Capture feature should be functional, however on my machine it immediately crashes with a cellRec-specific Verification Failed error.  The linked video was a first boot on latest master with no prior cache:

https://www.youtube.com/watch?v=GOQmiH2I56s

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13553162/RPCS3.log.gz)

**Comment by Megamouse** [comment]
I think it's because you are using resolution scaling.

**Comment by SlyCooperReloadCoded** [comment]
Back before audio recording was implemented, I used resolution scaling, same options as I used this time, and it worked.  However, I did try without resolution scaling and it works.  I pray this is only temporary.

**Comment by Megamouse** [comment]
I'm 100% sure that this check has been present since my first PR, so resolution scaling was never supported.
But it doesn't matter since it was never really needed.

**Comment by SlyCooperReloadCoded** [comment]
Maybe it working previously was a bug.  Anyways, good to see this getting fixed.  I didn't want to have to go back to 720p on my 4K monitor, especially since it seems to record in 480p anyways.
