### ISSUE TITLE
[NPUB90003] Full Auto 2 Battlelines Demo - Crashes on boot - Probably since #14584

### ISSUE THREAD

**Issue by FlexBy420** [RPCS3/rpcs3#14882]
### Quick summary

The build that most likely broke it didn't compile. kekw

Whenever you launch the game it will crash with
`F {PPU[0x1000000] Thread (main_thread) [HLE:0x008d16f4, LR:0x00103cd0]} PPU: Function aborted: sceNpDrmIsAvailable`
`F {PPU[0x1000000] Thread (main_thread) [HLE:0x008d16f4, LR:0x00103cd0]} VM: Access violation reading location 0xd0081000 (unmapped memory)`

### Build with regression

0.0.29-15561 Probably

### Attach two log files

[Working](https://github.com/RPCS3/rpcs3/files/13625858/RPCS3.log.gz)
[Broken](https://github.com/RPCS3/rpcs3/files/13625867/RPCS3.log.gz)

**Comment by elad335** [comment]
Nah its not a regression but I know the cause already, probably random due to different stack configuration on different boots.
