### ISSUE TITLE
God of War Ghost of Sparta has a glitch also present on ppsspp version

### ISSUE THREAD

**Issue by badasahog** [RPCS3/rpcs3#14890]
### Quick summary

when entering the Vortex (ship level) enemies keep spawning and the level never times out.

This same bug has been reported on ppsspp: https://github.com/hrydgard/ppsspp/issues/8299

The issue resolves itself when vsync is turned on

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13651061/RPCS3.log)

**Comment by MSuih** [comment]
Does it work without vsync if you set framerate limit to PS3 native?

**Comment by badasahog** [comment]
> Does it work without vsync if you set framerate limit to PS3 native?

The game autosaved when I got past the vortex and I have no way to go back and check

**Comment by badasahog** [comment]
> Just load the save file from there

Is there a save file database I can download it from?

I'm not sure I understand what you're asking me to do

**Comment by Jonathan44062** [comment]
Don't you have the save file from that point that I'm showing you? Didn't you save the game before making the report?

**Comment by badasahog** [comment]
> Don't you have the save file from that point that I'm showing you? Didn't you save the game before making the report?

no, but I definitely should have. I've just been using autosaves the entire game, and the game autosaved after the ship ride.

To make matters worse, the ship is like 5+ hours in

**Comment by kd-11** [comment]
> Does it work without vsync if you set framerate limit to PS3 native?

Even "Auto" would work in this case as it caps to 60. Since the reporter cannot reproduce the issue, I see no point in keeping this open, especially since it is seemingly fixed by frame cap options.

**Comment by madman-asunder** [comment]
I am testing ps3 native. but framerate of auto does not work (and the game is correctly capped at 60). I also have vsync on.

**Comment by SpontanCombust** [comment]
Faced the same issue. Caping the framerate to PS3 native and turning Vsync on allowed me to progress passed it. If anyone wants to try and test it themselves I'm providing savedata for the last save point before the Vortex stage.
[BCES01277-GOS0000.zip](https://github.com/user-attachments/files/25160516/BCES01277-GOS0000.zip)

I think it would be fair to mention this issue on [Origins Collection](https://wiki.rpcs3.net/index.php?title=God_of_War:_Origins_Collection)'s page.

**Comment by madman-asunder** [comment]
it also worked for me with ps3 native and vsync on. I know generally ps3 native is not recommended but it's honestly the first thing I try when I see weird behavior in games and it works a surprising amount of the time.
