### ISSUE TITLE
RSX Exception in D3D12GSRender::copy_render_target_to_dma_location

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1489]
```
{rsx::thread} Exception: HRESULT = 0x80070057
(in file Emu\RSX\D3D12\D3D12RenderTargetSets.cpp:405, in function D3D12GSRender::copy_render_target_to_dma_location)
Please report this to the developers.
```

PPU Interpreter 2
SPU Interpreter 2
Nothing is LLE'd

Auditorium HD **[NPUB30245]**

Log @ [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/121500/RPCS3.zip)

As discussed in the similar issue #1482

**Comment by vlj** [comment]
Did you enabled read/write buffer?

**Comment by MyaniPT** [comment]
@vlj 
[rsx/opengl]
Write Color Buffers=true
Write Depth Buffer=true
Read Color Buffers=true
Read Depth Buffer=true

_(Taken from the log because I didn't remember)_
I'm (almost) always running with the W/R buffers on.

**Comment by vlj** [comment]
You should disable them with dx12 these options don't improve accuracy atm and are not well supported

**Comment by MyaniPT** [comment]
Crashed the whole emulator with an Unknown Exception, this time without the output showed above.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/121685/RPCS3.zip)

```
·E {rsx::thread} RSX: FS build failed:C:\Users\Annie\Desktop\rpcs3\FragmentProgram.hlsl(67,57-90): error X3037: constructors only defined for numeric base types
```

Will test again with #1482 too

**Comment by vlj** [comment]
Sounds like memory corruption, what is the last FragmentProgram.hlsl dumped in your bin folder?

**Comment by MyaniPT** [comment]
FragmentProgram1.hlsl
FragmentProgram2.hlsl
FragmentProgram3.hlsl
VertexProgram0.hlsl

[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/121714/rpcs3.zip)

**Comment by fenix008** [comment]
I have similiar problem "·**E {rsx::thread} RSX: VS build failedBig C:\Rpcs3\trunk\bin\VertexProgram.hlsl(84,11-38): error X3037: constructors only defined for numeric base types** " in "Virtua Fighter 5"

Thread and log here - http://www.emunewz.net/forum/showthread.php?tid=158744

**Comment by raven02** [comment]
@AniLeo  Retest this game and should be another error .Please close this one.
