### ISSUE TITLE
SPURecompiler compilation fails on inFamous 2

### ISSUE THREAD

**Issue by solari21** [RPCS3/rpcs3#14904]
### Quick summary

Always it's freezing on building the SPU cache.

### Details

Infamous 2 (BCUS98125 & BCES01143) is freezing in "Building SPU cache".

It's not depending on custom configuration of the game because it's happening all times althouthg I change it.
I've trying removing All Caches, changing the renderer in config, etc

Nowadays it's only happen to me at this game.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13696195/RPCS3.log)

### System configuration

OS: Arch Linux (Steam OS 3.5.7)
CPU: AMD Custom APU 0405
GPU: AMD Radeon Graphics (RADV VANGOGH)

**Comment by AniLeo** [comment]
```
Compilation failed
(in file /run/build/rpcs3/rpcs3/Emu/Cell/SPURecompiler.cpp:6397[:4], in function compile)
```

Can you retest on the latest build?

**Comment by solari21** [comment]
Hi Annie! I've just tried with latest build and SPU Decoder with Recompiler ASMJIT and it's working right now!

Thank you for your valuable advice ;)

**Comment by AniLeo** [comment]
Do you confirm it still fails with LLVM? Can you upload a new log?

**Comment by solari21** [comment]
> Do you confirm it still fails with LLVM? Can you upload a new log if it's the case?

Yes it still fails with LLVM. It's freezing loading the last module... Later i'll upload a new log if it's necessary.

**Comment by strodown** [comment]
hi have a same issue in Red Dead Redemption BLES00179
stuck on last building spu cache
[Red Dead Redemption [BLES01179].log.gz](https://github.com/RPCS3/rpcs3/files/14309694/Red.Dead.Redemption.BLES01179.log.gz)

**Comment by AniLeo** [comment]
Not the same issue as OP, hidden as off-topic, you need to open a new issue

**Comment by RipleyTom** [comment]
Local build, please try with the official build, if it's not present in the official build it's not a valid issue.

**Comment by RipleyTom** [comment]
Assuming the issue was with the build since there was no further comment.
