### ISSUE TITLE
make rcps3 work on intel integrated gpus [Feature request] 

### ISSUE THREAD

**Issue by zeeboi9** [RPCS3/rpcs3#14906]
### Quick summary

Can you guys please make rcps3 work with intel integrated GPUs I have ran yuzu and it works fine so due to the ps3 being less powerful than the switch I was wondering if it is possible  to get rcps3 working for intel integrated GPUs (and if there is an unofficial work around could you please tell me)

### Details

games I ran on yuzu: breath of the wild, tears of the kingdom, arkham city and Mario kart 8 deluxe. all of then were working at around 30 fps

here are my specs:
12 GB ram
CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
IGPU: Intel(R) Iris(R) Plus Graphics
1 TB storage
OS: windows 10 pro

**Comment by FlexBy420** [comment]
Make intel fix their drivers first.
