### ISSUE TITLE
Trinity Universe won't load SPU Cache

### ISSUE THREAD

**Issue by geostarr** [RPCS3/rpcs3#14914]
### Quick summary

Game gets stuck trying to load SPU cache.

### Details

Game gets stuck trying to load SPU cache.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13720047/RPCS3.log)

### System configuration

Windows 10 x64

Nvidia GTX 1660TI
AMD Ryzen 5 3600x 6-core processor 3.8ghz
32GB Ram

**Comment by Manfred282** [comment]
...same problem here.

**Comment by Dominator0808** [comment]
...same problem here

**Comment by KurofukouHakusen** [comment]
Most likely the same issue I was having: [Regression: Trinity Universe](https://github.com/RPCS3/rpcs3/issues/14672)

I was able to fully 100% the game from version 0.0.29-15518 without issues, if you just want to play it.

**Comment by Megamouse** [comment]
duplicate of #14672

**Comment by CruxisMithos** [comment]
Same here. Tried it on my ROG Ally and my 3080Ti PC and it gets stuck on SPU
