### ISSUE TITLE
FreeBSD builds failing

### ISSUE THREAD

**Issue by RipleyTom** [RPCS3/rpcs3#14922]
```
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'qt6-multimedia' have been found in the repositories
pkg: No packages available to install matching 'ffmpeg' have been found in the repositories
```

Tagging our favourite FreeBSD expert @jbeich .
As far as I can tell something changed on FreeBSD's side rather than in rpcs3.

**Comment by jbeich** [comment]
`qt6-multimedia` depends on `ffmpeg` while `ffmpeg` depends on `x265` which [failed](https://pkg-status.freebsd.org/beefy16/data/132amd64-default/997912672fbe/logs/errors/x265-3.5.log) in [the recent build](https://pkg-status.freebsd.org/beefy16/build.html?mastername=132amd64-default&build=997912672fbe) after [an ABI-breaking update](https://github.com/freebsd/freebsd-ports/commit/645419c8e465) (.so.192 -> .so.200). It was later [fixed](https://github.com/freebsd/freebsd-ports/commit/0d7941b011fb) but [the next package build](https://pkg-status.freebsd.org/beefy16/build.html?mastername=132amd64-default&build=1129bbfc327e) hasn't finished yet. The missing packages should reapper in a few days, around 2023-12-25.

**Comment by jbeich** [comment]
To work aronud remove the folliwng lines. `/quarterly` is less susceptible to short-lived bustage.
https://github.com/RPCS3/rpcs3/blob/40604f6076561e84af078f2f1dcc68a00a57f8e9/.ci/install-freebsd.sh#L5-L7

**Comment by RipleyTom** [comment]
I think latest is fine, I don't remember any breakage before now.
Thanks for the explanation, I'll close as soon as I notice the CI working again.

**Comment by RipleyTom** [comment]
Working again!
