### ISSUE TITLE
[BLJM60055] Initial D EXTREME STAGE - Verification failed

### ISSUE THREAD

**Issue by Manfred282** [RPCS3/rpcs3#14921]
### Quick summary

rpcs3 does crash once the game is closed.

### Details

the game starts and runs fine but everytime the game is closed it crashes the program with this error message.

![Screenshot 2023-12-21 161307](https://github.com/RPCS3/rpcs3/assets/78433230/e5ebcabf-9212-4a17-9afc-c141fc37d219)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13743306/RPCS3.log)

### System configuration

Intel(R) Core(TM) i5-11600
NVIDIA GeForce RTX 2070 SUPER (546.33)
32 GB RAM
Windows 10 22H2

**Comment by jenci8888** [comment]
I'm having an exact same issue even I tested with other games, not one game.
Possible culprit build is #14896, last known good `0.0.29-15817-a4bcba89` master build.

**Comment by QuaiGoner** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/41058180/b582cd36-3fac-41db-af7c-28852daedd85)
Same when trying to create cache for Firmware

**Comment by RGB00255** [comment]
I would like to put it on record that this happens for me on every title including homebrew such as Apollo Save Tool.

**Comment by elad335** [comment]
Still an issue?

**Comment by Manfred282** [comment]
as of **0.0.29-15842-45c865ed** the issue is solved for me ;)
