### ISSUE TITLE
RSX: RSXIO memory not mapped

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1492]
**rpcs3-v0.0.0.6-460-g303a109**

```
{rsx::thread} Exception: rsx::thread::ReadIO32(addr=0x1fffffff): RSXIO memory not mapped
(in file Emu\RSX\RSXThread.cpp:842, in function rsx::thread::ReadIO32)
Please report this to the developers.
```

Game fails to Load in both OpenGL and DirectX 12

Log @ [rpcs3.zip](https://github.com/RPCS3/rpcs3/files/123714/rpcs3.zip)

libavcdec
cellFiber
cellSpursJq
cellSre
libvdec

Only happens in Steins;Gate, doesn't happen in Steins;Gate 0
![screenshot_38](https://cloud.githubusercontent.com/assets/10283761/12929393/4a2168a6-cf6a-11e5-9a8a-84db3cc5f829.png)

Found a similar old issue just for reference: #880

**Comment by tambry** [comment]
Is this still an issue?

**Comment by AniLeo** [comment]
Yes, the same thing is still happening

```
{rsx::thread} class fmt::exception thrown: rsx::thread::ReadIO32(): rsx::thread::ReadIO32(addr=0x1fffffff): RSXIO memory not mapped
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:888)
```

Log @ [RPCS3_SG.zip](https://github.com/RPCS3/rpcs3/files/250362/RPCS3_SG.zip)

**Comment by AniLeo** [comment]
·! LDR: Title: From Dust - DEMO
·! LDR: Serial: NPUB30418
```
{rsx::thread} class fmt::exception thrown: rsx::thread::ReadIO32(): rsx::thread::ReadIO32(addr=0xeeeeeee): RSXIO memory not mapped
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:916)
```

**Comment by raven02** [comment]
@AniLeo , still happening in latest build

**Comment by AniLeo** [comment]
Will check in two days or so, currently in vacation and I don't have BLES02142 on my laptop.

**Comment by AniLeo** [comment]
Still happening on the latest build

**Comment by raven02** [comment]
Thanks .

**Comment by sirdanielk** [comment]
RSXIO32error happened from time tiime on various games and dissapeared. i also have this in Comet Crash NPEB90210
```
U {PPU[0x13] Thread (main_thread) [0x001be9bc]} cellGcmSys TODO: cellGcmSetGraphicsHandler
F {rsx::thread} class fmt::exception thrown: rsx::thread::ReadIO32(): rsx::thread::ReadIO32(addr=0x30a7379): RSXIO memory not mapped
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:929)
```

**Comment by supergatto** [comment]
@tambry i have same issue 
[BCUS-98164] Heavy Rain
Log:
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/813696/RPCS3.txt)

**Comment by tambry** [comment]
Do not ever ping me again. I'm no longer a developer of RPCS3 nor will I ever be again.

**Comment by AniLeo** [comment]
This is a general error. Also, please don't ping people who don't want to be pinged.

**Comment by AniLeo** [comment]
This is not an issue anymore, the fix was likely lle-gcm

**Comment by Jolty95** [comment]
@AniLeo I'm getting 
```
F {rsx::thread} class std::runtime_error thrown: GetAddress(offset=0x8275e600, location=0x1): RSXIO memory not mapped
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:52)
```
when trying to launch Ratchet and Clank Tools of destruction with latest commit, I'm don't know if related, but since is getting `RSXIO memory not mapped` I though it's worth it asking here.
PS: Sorry if I bother ping-ing you but you were the person who close this :p

**Comment by AniLeo** [comment]
It's not the same issue no. If you can reproduce open a separate issue with steps
