### ISSUE TITLE
NCAA Football 14 won't download

### ISSUE THREAD

**Issue by Dominator0808** [RPCS3/rpcs3#14928]
### Quick summary

I am running on macOS 14, tried uploading NCAA 14 onto the dock but keep running into problems. 

### Attach a log file

- SYS: RPCS3 v0.0.29-15838-732d9b83 Alpha | HEAD
- SYS: VirtualApple @ 2.50GHz | 8 Threads | 8.00 GiB RAM | TSC: 1.000GHz
- SYS: Operating system: macOS, Version: 14.1.1
- SYS: Current Time: 2023-12-22T18:09:06
- RSX: Found Vulkan-compatible GPU: 'Apple M1' running on driver 0.2.990
- SYS: Firmware version: 4.90
E GameList: Invalid disc path found in /Users/dominick/Library/Application Support/rpcs3/dev_hdd0/disc/BLUS31159-[NCAA Football 14] x2
E SYS: Failed to write icon file: /Users/dominick/Applications/RPCS3/NCAA® Football 14.app/Contents//Resources/shortcut.icns
E GameList: Failed to create application menu shortcut for NCAA® Football 14
E GameList: Invalid disc path found in /Users/dominick/Library/Application Support/rpcs3/dev_hdd0/disc/BLUS31159-[NCAA Football 14]
E SYS: Failed to write icon file: /Users/dominick/Applications/RPCS3/NCAA® Football 14.app/Contents//Resources/shortcut.icns
E GameList: Failed to create application menu shortcut for NCAA® Football 14
E GameList: Invalid disc path found in /Users/dominick/Library/Application Support/rpcs3/dev_hdd0/disc/BLUS31159-[NCAA Football 14]
E GameList: Failed to create shortcuts for NCAA® Football 14. No locations selected.
E GameList: Invalid disc path found in /Users/dominick/Library/Application Support/rpcs3/dev_hdd0/disc/BLUS31159-[NCAA Football 14] x2
E SYS: Failed to write icon file: /Users/dominick/Applications/RPCS3/NCAA® Football 14.app/Contents//Resources/shortcut.icns
E GameList: Failed to create application menu shortcut for NCAA® Football 14

**Comment by Darkhost1999** [comment]
RPCS3 doesn't distribute game data at all.
So this isn't an RPCS3 issue and this is a support request on how to obtain games legally.
Please read our wiki and quickstart guide.
Ask for help on the discord, reddit, or forums.

**Comment by Dominator0808** [comment]
Is NCAA Football 14 still supported by Rpcs3?

**Comment by Dominator0808** [comment]
What are some supported sites to download games?

**Comment by ReLyf47** [comment]
> What are some supported sites to download games?

Your mom
