### ISSUE TITLE
{PPU[0x1000013] Thread (CommerceManagerThread) [0x00519248]} VM: Access violation reading location 0x3c (unmapped memory) in ModNation™ Racers [BCUS98167]

### ISSUE THREAD

**Issue by CMAE2** [RPCS3/rpcs3#14935]
### Quick summary

whenever the Mod spot is being loaded on the latest version of the game it throws this error, version from disk worked fine until updated.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13763342/RPCS3.log.gz)

### System configuration

- SYS: RPCS3 v0.0.29-15840-69238bfc Alpha | master
- SYS: AMD Ryzen 5 5500 | 12 Threads | 31.90 GiB RAM | TSC: 3.593GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-12-24T20:44:57
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce GTX 1060 6GB' running on driver 546.33.0.0
- SYS: Firmware version: 4.90
S UPDATER: RPCS3 is up to date!

**Comment by AniLeo** [comment]
Need Information: The issue is invalid as is as RPCS3 is placed in a special permissions directory (Program Files), which is not supported. Needs retesting with RPCS3 on a normal directory.

**Comment by ChwaraeTeg** [comment]
Couldn't reproduce this issue in RPCS3 v0.0.30-15948-f7fa5aab Alpha - game updated to version 01.11, WCB on as per wiki and all other settings left default. The ModSpot area loaded okay and I could drive around without any issue
[ModnationRacers.log.gz](https://github.com/RPCS3/rpcs3/files/13931715/ModnationRacers.log.gz)

I also tested with Network: Connected and PSN: RPCN as in the original logfile, but again couldn't reproduce the issue.
