### ISSUE TITLE
Keybinding for numerical row keys overlap with numpad numerical keys

### ISSUE THREAD

**Issue by kusanagiryuu** [RPCS3/rpcs3#14936]
### Quick summary

Lets say I bind "D-Pad Left" to the numerical row "1" key.
I also bind "Select" to the numpad "1" key. 
When I press the numpad "1" key to call "Select", I get a duplicate "D-Pad Left" as well and vice-versa. 

The numerical row "1" and numpad "1" are distinct and separate keys on the keyboard. They should not overlap. 

### Attach a log file

[Log.txt](https://github.com/RPCS3/rpcs3/files/13763701/Log.txt)

### Attach capture files for visual issues

![SC](https://github.com/RPCS3/rpcs3/assets/131541131/23e0860a-d9f9-4b4e-ac81-f3454fa7213d)

**Comment by Megamouse** [comment]
This is not as simple as it looks like, due to the way Qt keys work.
But I'll try to fix it after the holidays.
