### ISSUE TITLE
[BLES00668 - TOP SPIN 4] Regression with GPU Vulkan mode enabled

### ISSUE THREAD

**Issue by sennastien** [RPCS3/rpcs3#14933]
Game won't boot with the latest release, in OpenGL Mode, meaning it displays a black screen after compiling shaders / spu
No game intro screen (HAVOK...) could be seen.

System configuration

AMD Ryzen Z1 EXTREME
AMD Radeon Navi3, 2 Go
16 GB RAM
Windows 11 22H2

Other details

No response

**Comment by Darkhost1999** [comment]
We can't begin to troubleshoot this issue without the build version that started the issue and 2 logs.
1 from the working build. 1 from the broken build.

**Comment by sennastien** [comment]
Yes, sorry bout that.
So the latest build (v0.0.29-15840-69238bfc Alpha | master)) won't allow to run the game properly: I'm hearing the music but it displays only a black screen.
The previous release was ok running in OpenGl mode

**Comment by sennastien** [comment]
Fixed with the last release
