### ISSUE TITLE
[Regression] Missing stickers in LittleBigPlanet games

### ISSUE THREAD

**Issue by ItsALH** [RPCS3/rpcs3#14940]
### Quick summary

Stickers won't render after #14934
Last working build: 0.0.29-15842

| Game | Before (15842)  | After (15844) |
| ------------- | ------------- | ------------- |
| LittleBigPlanet  | ![170363131625254044](https://github.com/RPCS3/rpcs3/assets/108736840/ba84148d-d824-4b53-af0d-d00f0539565f)  | ![170363200425942029](https://github.com/RPCS3/rpcs3/assets/108736840/3e731a38-91ee-45f6-a731-e845a06b1ecb) |
| LittleBigPlanet 2  | ![170363147625413814](https://github.com/RPCS3/rpcs3/assets/108736840/c4db4fc6-8126-4cda-803a-bcbcd6f2d2f0)  | ![170363213026067514](https://github.com/RPCS3/rpcs3/assets/108736840/f0ec7c7e-d506-4250-a59b-432afd871cb0) |
| LittleBigPlanet 3  | ![170363175925696514](https://github.com/RPCS3/rpcs3/assets/108736840/ac5b415f-4432-43c0-86fd-cc2a63ffe2a9)  | ![170363274726684670](https://github.com/RPCS3/rpcs3/assets/108736840/94fab449-4004-4fb5-b1e2-9cd4c94b1b98) |

### Build with regression

v0.0.29-15844

### Attach two log files

[LBP 15842.log](https://github.com/RPCS3/rpcs3/files/13774093/LBP.15842.log)
[LBP 15844.log](https://github.com/RPCS3/rpcs3/files/13774094/LBP.15844.log)
[LBP2 15842.log](https://github.com/RPCS3/rpcs3/files/13774095/LBP2.15842.log)
[LBP2 15844.log](https://github.com/RPCS3/rpcs3/files/13774096/LBP2.15844.log)
[LBP3 15842.log](https://github.com/RPCS3/rpcs3/files/13774174/LBP3.15842.log)
[LBP3 15844.log](https://github.com/RPCS3/rpcs3/files/13774176/LBP3.15844.log)

### System configuration

- OS: Windows 10 Pro
- CPU: Ryzen 7 5800X
- RAM: 32 GB
- GPU: Nvidia RTX 2060
- Driver version: 546.17.0.0

**Comment by kd-11** [comment]
Oops. Pushing a fix.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/14943

**Comment by ItsALH** [comment]
Yeah, it's working again 🙂👍
