### ISSUE TITLE
RPCS3 murders my computer after a couple minutes.

### ISSUE THREAD

**Issue by TheeStickmahn** [RPCS3/rpcs3#14947]
### Quick summary

RPCS3 crashes my computer and then kicks me back to the Pop!_OS login screen after a couple minutes of it being on.

### Details

The crashes happen after a few minutes, seemingly randomly.
Once it happened while looking around the settings.
Once it happened while setting up a controller.
A couple times it just... decided to murk my computer.

I am running Flatpak, RPCS3 version is ***Build 0.0.29-15844***.
CPU: Ryzen 5 5600G
GPU: AMD Radeon 6700XT
RAM: 32 GB
OS: Pop!_OS 22.04 LTS _(non-nvidia version)_
Kernel Version: 6.6.6-76060606-generic
DE: Pop On Wayland
HW Probe: https://linux-hardware.org/?probe=61116b6285
![image](https://github.com/RPCS3/rpcs3/assets/105667019/6eaeee17-7ad2-4ff8-a2cd-ddf9f24592b2)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13781505/RPCS3.log.gz)
here you go pookie

**Comment by Mrlinkwii** [comment]
the Flatpak isnt supported  use teh appimage

**Comment by TheeStickmahn** [comment]
im stupid
