### ISSUE TITLE
[Regression] Daytona USA no longer recognizes wheel - 0.0.29-15470 (#14458)

### ISSUE THREAD

**Issue by vacuumman** [RPCS3/rpcs3#14969]
### Quick summary

Racing wheel is unresponsive in Daytona USA. Regression occurred in 0.0.29-15470. Wheel does not work in the latest build either.

### Details

Installed winUSB drivers for the Logitech G27 wheel using Zadig. Booted Daytona USA in v0.0.29-15470, and the game does not respond to any input from the wheel. After reverting to v0.0.29-15468, the wheel functions as intended. Wheel is also unresponsive in the latest build as of writing (0.0.29-15869).

### Build with regression

v0.0.29-15470-4bbe885f

### Attach two log files

[RPCS3-15470.log.gz](https://github.com/RPCS3/rpcs3/files/13798890/RPCS3-15470.log.gz)
[RPCS3-15468.log.gz](https://github.com/RPCS3/rpcs3/files/13798891/RPCS3-15468.log.gz)

### System configuration

Windows 10 Home 64-bit
Intel i5 12600K
RTX 3080

**Comment by AniLeo** [comment]
Adding @elad335 since it's regressed from #14458

**Comment by elad335** [comment]
Retry with #14959

**Comment by vacuumman** [comment]
> Retry with #14959

It works! Thank you very much
