### ISSUE TITLE
DEF JAM: ICON (demo) [NPEB90001] only boots if DEF JAM: ICON (demo) [NPUB90004] is istalled

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#14962]
### Quick summary

This will crash with an error
F {PPU[0x1000000] Thread (main_thread) [0x00378b5c]} VM: Access violation reading location 0x4 (unmapped memory)

### Details

This game will fault with a memory violation when Serial NPUB90004 is not installed. The game works as intended when both games are in the hdd1 folder.

I checked the iso where I got the game from and it matches the MD5 hash so not sure what going on.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13796080/RPCS3.log.gz)

### System configuration

RPCS3 RPCS3 v0.0.29-15857-03761c5d Alpha | master | FW 4.88 | Windows 10
AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 15.55 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (535.104)

### Other details

Note: This game was only ever released on the Official PlayStation Magazine Issue 18: May 2008 demo disk, and I have not tested it on hardware so unsure what the intended behavior is.

**Comment by Megamouse** [comment]
This may be a similar issue to some Uncharted demo which was region locked and also broken on official consoles.
Try to change the region in the settings.

**Comment by Megamouse** [comment]
https://www.avforums.com/threads/def-jam-icons-demo-not-working.497069

**Comment by Triticum0** [comment]
Yes it region locked. It works if i change my region
