### ISSUE TITLE
WipEout HD - Custom Music, some songs fail to play

### ISSUE THREAD

**Issue by JonathanLorikon** [RPCS3/rpcs3#14972]
### Quick summary

Songs converted to MP3 do not play inside WipEout HD's custom music playlist player and are instead skipped instantly to a song that is playable.

### Details

I've converted a few of my CDs to MP3s to play inside WipEout HD. All songs show up as intended with the correct metadata but a portion fails to play inside the game and are instead skipped over to play the next (working) track.

Have tried removing metadata, changing the ID3 tags to older versions, re-converting said songs, shortening titles, no dice.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13799320/RPCS3.log)

### System configuration

OS: Windows 10 Pro
CPU: AMD Ryzen 7 3700X
GPU: NVIDIA RTX 3070 - Driver ver. 546.17
RAM: 16GB

**Comment by Megamouse** [comment]
I think this related to long filenames.

**Comment by JonathanLorikon** [comment]
The one thing I didn't try was shortening the file names... It worked, thank you. 😅

**Comment by Megamouse** [comment]
This is a bug in the emulator. I'm fixing it right now.
