### ISSUE TITLE
Turok black screen.

### ISSUE THREAD

**Issue by willianholtz** [RPCS3/rpcs3#14978]
### Quick summary

Black Screen!

### Details

Game just won't start. The screen goes black. According to the wiki, there is nothing to be done to make the game run, everything works in the default configuration. However, I tried the default and other settings but nothing worked.

### Attach a log file

[Turok [BLUS30104].log.gz](https://github.com/RPCS3/rpcs3/files/13801477/Turok.BLUS30104.log.gz)

### System configuration

OS: Arch LInux
GPU: RTX 2060 12GB
CPU: R 5700x
RAM: 64GB

**Comment by AniLeo** [comment]
Could be a corrupted dump from looking at the log, validate your disc dump
https://wiki.rpcs3.net/index.php?title=Help:Validating_PlayStation_3_game_dumps

**Comment by willianholtz** [comment]
Exactly what you said, the game was broken. However, it took me some time to realize that the American isos were damaged, so the European version worked normally.

**Comment by AniLeo** [comment]
Invalid issue due to usage of pirated copy, locked.
