### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by 80-svg** [RPCS3/rpcs3#14979]
### Quick summary

Just a typo nothing really but the people that are working on the website should fix it because it is literally just a typo

### Details

the typo is in the quickstart guide under "PS3 system software and windows redistributable" more specifically (the image below
![Screenshot_15](https://github.com/RPCS3/rpcs3/assets/77842228/6cbdca7f-beb3-4163-a294-6936d36046b8)
)

### Attach a log file

no log

**Comment by GregoireLD** [comment]
And I just noticed in your screenshot, there is a "FreeBS" instead of a "FreeBSD" too

**Comment by MSuih** [comment]
We have summoned Daginatsuko to fix the issue, it should now be resolved if you refresh the page.

In future please open issues about the webpage in one of the following repositories:
https://github.com/DAGINATSUKO/www-rpcs3/
https://github.com/AniLeo/rpcs3-compatibility/
