### ISSUE TITLE
[Regression] macOS: Crashes on launch, missing libjxl_cms dylib, starting from v0.0.29-15858

### ISSUE THREAD

**Issue by GregoireLD** [RPCS3/rpcs3#14977]
### Quick summary

The macOS version crashes at startup, seemingly because of failing to load the libjxl_cms dylib

### Build with regression

rpcs3-v0.0.29-15858-a96f9d9b

### Attach two log files

crashes before generating one

### System configuration

macOS Sonoma 14.3, MacBook Pro w/ M1 Max CPU

### Other details

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               rpcs3 [79651]
Path:                  /Applications/RPCS3.app/Contents/MacOS/rpcs3
Identifier:            net.rpcs3.rpcs3
Version:                ()
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-31 14:57:01.8646 +0100
OS Version:            macOS 14.3 (23D5033f)
Report Version:        12
Anonymous UUID:        6E1F5815-3DE8-053C-B1B4-5DD6267BA283

Sleep/Wake UUID:       594F346A-3B6A-4FA7-93AD-0736DE6DD93F

Time Awake Since Boot: 400000 seconds
Time Since Wake:       59955 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x105C66A78)

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/libjxl_cms.0.9.dylib
Referenced from: <77E8A704-167C-394F-9F22-8554C1CEA74F> /Applications/RPCS3.app/Contents/Frameworks/libjxl.0.9.dylib
Reason: tried: '/Applications/RPCS3.app/Contents/Frameworks/../lib/libjxl_cms.0.9.dylib' (no such file), '/usr/local/lib/libjxl_cms.0.9.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libjxl_cms.0.9.dylib' (no such file), '/usr/local/Cellar/sdl2/2.28.5/lib/libjxl_cms.0.9.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/sdl2/2.28.5/lib/libjxl_cms.0.9.dylib' (no such file), '/usr/local/opt/llvm@16/lib/libjxl_cms.0.9.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/llvm@16/lib/libjxl_cms.0.9.dylib' (no such file), '/Applications/RPCS3.app/Contents/Frameworks/libjxl_cms.0.9.dylib' (no such file), '/usr/local/lib/libjxl_cms.0.9.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libjxl_cms.0.9.dylib' (no such file), '/usr/local/Cellar/sdl2/2.28

**Comment by AniLeo** [comment]
The flagged PR (#14963) did not change anything that could have caused this issue, so it's likely a change on CI side and/or macOS repositories

**Comment by GregoireLD** [comment]
Yeah I realized that right after posting, that's why I tried to remove reference to it.
Thanks a lot for your swift response and the fix :-)

**Comment by GregoireLD** [comment]
Just checked the new build and the error has indeed changed, but now it seems there is some other problem regarding a lib : it tries to load liblcms2.2.dylib from /usr/local/opt/little-cms2/lib/liblcms2.2.dylib (path problem ? or missing lib)

I will open another separate issue since this first problem was indeed solved and marked as such.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               rpcs3 [89734]
Path:                  /private/var/folders/*/RPCS3.app/Contents/MacOS/rpcs3
Identifier:            net.rpcs3.rpcs3
Version:                ()
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-31 21:26:17.9446 +0100
OS Version:            macOS 14.3 (23D5033f)
Report Version:        12
Anonymous UUID:        6E1F5815-3DE8-053C-B1B4-5DD6267BA283

Sleep/Wake UUID:       594F346A-3B6A-4FA7-93AD-0736DE6DD93F

Time Awake Since Boot: 430000 seconds
Time Since Wake:       83311 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x105BE2A78)

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/little-cms2/lib/liblcms2.2.dylib
Referenced from: <4755C952-26D5-3A0D-AC9B-32B76F81983C> /private/var/folders/*/RPCS3.app/Contents/lib/libjxl_cms.0.9.dylib
Reason: tried: '/usr/local/opt/little-cms2/lib/liblcms2.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/little-cms2/lib/liblcms2.2.dylib' (no such file), '/usr/local/opt/little-cms2/lib/liblcms2.2.dylib' (no such file), '/usr/local/lib/liblcms2.2.dylib' (no such file), '/usr/lib/liblcms2.2.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)
