### ISSUE TITLE
[Windows] First command line argument is ignored?

### ISSUE THREAD

**Issue by Aemony** [RPCS3/rpcs3#14986]
### Quick summary

RPCS3 seems to ignore the first given command line argument on Windows.

### Details

Regard this scenario:
```
·! 0:00:00.006780 SYS: argc: 2, argv: '--no-gui' '%RPCS3_GAMEID%:BLES01294'
```
In this case, `--no-gui` is ignored and has no effect.

Regard this scenario:
```
·! 0:00:00.006101 SYS: argc: 3, argv: 'derp' '--no-gui' '%RPCS3_GAMEID%:BLES01294'
```
In this case, `derp` is ignored and has no effect, while `--no-gui` is recognized and respected.

### Attach a log file

[RPCS3_no-gui_working.log](https://github.com/RPCS3/rpcs3/files/13802357/RPCS3_no-gui_working.log)
[RPCS3_no-gui_not_working.log](https://github.com/RPCS3/rpcs3/files/13802358/RPCS3_no-gui_not_working.log)

### Other details

I am unsure if this is intended behaviour because depending on how an executable is launched on Windows, the path to the executable may actually be used as the first command line argument as well (ShellExecute for example seems to work this way).

In my case, I'm using [CreateProcessW](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) with `lpApplicationName` set to the PCSX3 executable, and `lpCommandLine` set to `--no-gui "%RPCS3_GAMEID%:BLES01294"` which runs into the bug. The only "special" thing (not really special) is that the RPCS3 executable is not provided as the first parameter of command line used to start the application.

If I however set `lpCommandLine` to `"<path-to-RPCS3>" --no-gui "%RPCS3_GAMEID%:BLES01294"` I successfully circumvent the bug, same as if I set it to `derp --no-gui "%RPCS3_GAMEID%:BLES01294"`.

See the following screenshot from Process Explorer illustrating the details of the bug:
- Left works; first argument `<path-to-RPCS3>` is ignored.
- Right does not work; first argument `--no-gui` is ignored.

![process_explorer_left_working_right_not_working](https://github.com/RPCS3/rpcs3/assets/10578344/3309c06e-53b0-4c20-a89c-372b74f3a4d7)

**Comment by Megamouse** [comment]
You obviously need the first argument to be the path to the executable

**Comment by Aemony** [comment]
It's not actually required when spawning a process with CreateProcess, as `lpApplicationName` and `lpCommandLine` are two separate parameters given to it, and so does not need to share any kind of data, where `lpApplicationName` would hold the actual module to execute. However using the first argument as the path to the executable is so commonly done that I expect most apps won't handle a non-module as the first argument properly.

Microsoft touches upon it in their docs as well:
```
If both lpApplicationName and lpCommandLine are non-NULL, the null-terminated string pointed to by lpApplicationName specifies the module to execute, and the null-terminated string pointed to by lpCommandLine specifies the command line. The new process can use [GetCommandLine](https://learn.microsoft.com/en-us/windows/desktop/api/processenv/nf-processenv-getcommandlinea) to retrieve the entire command line. Console processes written in C can use the argc and argv arguments to parse the command line. **Because argv[0] is the module name, C programmers generally repeat the module name as the first token in the command line.**
```

Anyway, I'll work around this on my end, and just repeat the executable path as the first command-line argument as well since I'm sure this project isn't the only one that are unable to handle arguments where the first argument isn't the executable path.

**Comment by Megamouse** [comment]
It's not even really us who strictly expect this, it's Qt.

**Comment by Megamouse** [comment]
Anyway, it's best practice to set argv0 to executable path.
