### ISSUE TITLE
[Regression] macOS: Crashes on launch followup, missing liblcms dylib, starting from v0.0.29-15858

### ISSUE THREAD

**Issue by GregoireLD** [RPCS3/rpcs3#14983]
### Quick summary

This is a follow up to issue #14977, with fixed the previous missing lib

I just checked the new build and the error has indeed changed, but now it seems there is some other problem regarding a lib : liblcms2.2.dylib

I just also noticed that in the crash report, the the path isn't looking the same as the previous error I reported : It says
"Library not loaded: /usr/local/opt/little-cms2/lib/liblcms2.2.dylib"
where the previous missing lib error message was of the like of "Library not loaded: @rpath/libjxl_cms.0.9.dylib"
(but I don't know if it's somewhat relevant)

### Build with regression

v0.0.29-15878-feca7412

### Attach two log files

crashes before generating one

### Other details

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               rpcs3 [89734]
Path:                  /private/var/folders/*/RPCS3.app/Contents/MacOS/rpcs3
Identifier:            net.rpcs3.rpcs3
Version:                ()
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-31 21:26:17.9446 +0100
OS Version:            macOS 14.3 (23D5033f)
Report Version:        12
Anonymous UUID:        6E1F5815-3DE8-053C-B1B4-5DD6267BA283

Sleep/Wake UUID:       594F346A-3B6A-4FA7-93AD-0736DE6DD93F

Time Awake Since Boot: 430000 seconds
Time Since Wake:       83311 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x105BE2A78)

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/little-cms2/lib/liblcms2.2.dylib
Referenced from: <4755C952-26D5-3A0D-AC9B-32B76F81983C> /private/var/folders/*/RPCS3.app/Contents/lib/libjxl_cms.0.9.dylib
Reason: tried: '/usr/local/opt/little-cms2/lib/liblcms2.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/little-cms2/lib/liblcms2.2.dylib' (no such file), '/usr/local/opt/little-cms2/lib/liblcms2.2.dylib' (no such file), '/usr/local/lib/liblcms2.2.dylib' (no such file), '/usr/lib/liblcms2.2.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

**Comment by nastys** [comment]
Does the #14987 build fix it?

**Comment by AniLeo** [comment]
@r0g3r you can see if this build fixes it

https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzkzNjgvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitNYWM1/content?format=zip

**Comment by w-e-g** [comment]
@AniLeo, thanks! RPCS runs on this build. :)

**Comment by GregoireLD** [comment]
> Does the #14987 build fix it?

I tried the build #14987 and yes it works 😊

**Comment by w-e-g** [comment]
But now I have another problem.. :)

**Comment by w-e-g** [comment]
[rpcs.log](https://github.com/RPCS3/rpcs3/files/13804913/rpcs.log)

**Comment by w-e-g** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13804930/RPCS3.log)

App log after trying to run any game on this build.

**Comment by AniLeo** [comment]
Does it work with 0.0.29-15857?
https://rpcs3.net/builds

**Comment by GregoireLD** [comment]
Unfortunately no, same issue on 0.0.29-15857, only solved with non-merged yet pr #14987
