### ISSUE TITLE
rpcs3-ReleaseLLVM-f7f4c049 build

### ISSUE THREAD

**Issue by woody2014** [RPCS3/rpcs3#1498]
after placing libpng16.dll in folder getting error

**Comment by MyaniPT** [comment]
You should only post issues while using the latest master build
Also, you need to attach a log and or screenshot of the error

**Comment by woody2014** [comment]
i have found the problem, 64 bit version of dlls are needed issue can be closed

**Comment by tambry** [comment]
@MyaniPT It is probably using latest master build, but the usual build bots haven't built it yet. Probably forgot to re-do _git submodule update --init_, which is needed due to new libpng dependency.
