### ISSUE TITLE
[Regression] inFAMOUS™ 2 (Digital) [NPUA80638] stopped booting up starting with 0.0.29-15856

### ISSUE THREAD

**Issue by Zorklis** [RPCS3/rpcs3#14994]
### Quick summary

Regression started with [0.0.29-15856](https://github.com/RPCS3/rpcs3/pull/14956), works on 0.0.29-15855 and before.

### Build with regression

v0.0.29-15856-d3298c42

**Comment by Megamouse** [comment]
E:/Games/Infamous 2 NPUA80638/USRDIR/EBOOT.BIN

Why kind of path is that?

**Comment by Megamouse** [comment]
This is not a bug.
The game expects the dir name and original install dir name to be identical.
Also hdd games are not meant to be located in the games dir, but installed with the emulator.

**Comment by Megamouse** [comment]
It's a bug after all.

**Comment by Megamouse** [comment]
The bugfix is not helping in this case though, as the game still tries to load the wrong directory. So I assume it is hardcoded, since there is no indication that it uses a function that still passes the title id to the game.
