### ISSUE TITLE
[Feature request] Auto detect built in controls for gaming handhelds

### ISSUE THREAD

**Issue by Bobble80** [RPCS3/rpcs3#14996]
### Quick summary

I’m wondering will it be possible to add the feature in RPCS3 to auto detect the built in controls on current handheld gaming devices like the ROG Ally and Legion Go so you can navigate through the UI this way? Right now it doesn’t seem to be an option.

I know with Yuzu emulator, it’ll automatically detect the built in controls of the device and I can use the d-pad to scroll through my game list and then press the A button and the game starts right up. 

Can this feature be added to RPCS3?

### Details

It would really add to the ease of use. Just open the emulator and use the d pad or joystick to be able to scroll through your game list and then press the A button to jump straight into the selected game. 

As it works right now, I have to switch the device controls into mouse mode and select my game from the list that way. 

This feature Is already natively supported in Yuzu emulator. There’s no need to change any settings, the emulator automatically detects the built in gamepad controls on the ROG Ally.

**Comment by AniLeo** [comment]
There are two different requests here which should be separated tickets:

- Implementing gamepad navigation for the Qt GUI
- Automatically detect a connected gamepad and prefer it over keyboard handler which is already discussed on #14003

**Comment by Megamouse** [comment]
Part one is implemented, part two is already another task/issue.
