### ISSUE TITLE
God of War 3 Freezing Bug

### ISSUE THREAD

**Issue by klepto123** [RPCS3/rpcs3#14998]
### Quick summary

God of War 3 freezes at random parts of the game causing me to have to close the game.

### Details

God of War 3, at random points of the game, freezes. It doesn't necessarily freeze after a certain action or point of the game. It just freezes.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13810676/RPCS3.log.gz)

### System configuration

OS: Windows 10 Pro
CPU: 12th Gen Intel(R) Core(TM) i5-12400   2.50 GHz
GPU: NVIDIA GeForce RTX 3060
GPU Current Driver: 546.17
RAM: 16 GB

**Comment by MSuih** [comment]
Ask for help on our Discord's help channel
