### ISSUE TITLE
Guitar Hero SG PS2 Controller - Strum Bar not working in GH Games.

### ISSUE THREAD

**Issue by cas-1092** [RPCS3/rpcs3#14993]
### Quick summary

The strum bar is not recognized in menus.

### Details

I own and use a GH SG PS2 Guitar, When I tried out Rock Band 1, the controller works perfectly, however when I loaded up Guitar Hero 5, The controller's strum bar would not work in the menus, if I were to load into a song, the strum bar works fine. The same happens on Guitar Hero 3.

### Attach a log file

 [Guitar Hero 5 [BLUS30292].log.gz](https://github.com/RPCS3/rpcs3/files/13805578/Guitar.Hero.5.BLUS30292.log.gz)

### System configuration

Windows 11 22H2 | Intel Core i5-11400F | 23.86 GiB RAM | NVIDIA GeForce GTX 1660 SUPER (546.33)

### Other details

If anymore info is needed, please let me know.

**Comment by Megamouse** [comment]
does it work on a real ps3 ?

**Comment by cas-1092** [comment]
> does it work on a real ps3 ?

The current adapter I use (PS2 to USB) does not work for any game on a real ps3, (RB1, GH3, GH5).

**Comment by Megamouse** [comment]
Since this is usb passthrough, there's not really anything we can do about it.

**Comment by cas-1092** [comment]
> Since this is usb passthrough, there's not really anything we can do about it.

Ah, that sucks, What's weird is it only happens in the menus for the GH games, they work fine once you start playing songs.

**Comment by Megamouse** [comment]
Yeah it sucks, but maybe you can find a better adapter or just ignore it :)

**Comment by cas-1092** [comment]
Just tried a completely different guitar and that works fine, so i guess ill just use that.
Thanks for responding.
