### ISSUE TITLE
Red Dead Redemption: Game of the Year Edition [BLES01294] fails while building SPU Cache

### ISSUE THREAD

**Issue by tervor** [RPCS3/rpcs3#14991]
### Quick summary

When trying to launch Red Dead Redemption: Game of the Year Edition [BLES01294] i get stuck while building the SPU cache. The log reports `Thread terminated due to fatal error: Compilation failed`.

### Details

When starting Red Dead Redemption: Game of the Year Edition [BLES01294] it initially generates some caches but fails to finish because the process gets aborted during SPU cache generation with the following message in the log:
```
F {SPU Worker 14} SIG: Thread terminated due to fatal error: Compilation failed
(in file /run/build/rpcs3/rpcs3/Emu/Cell/SPURecompiler.cpp:6426[:4], in function compile)
```
The game window meanwhile stays almost static with the following image (only the time remaining seems to change from time to time):
![RDR SPU Cache](https://github.com/RPCS3/rpcs3/assets/1598708/0dc46e33-ffd3-41a5-b7d9-9ea0de784552)

The same also happens, after closing and reopening the game as well as after removing the caches and try to relaunch.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13805463/RPCS3.log.gz)

### System configuration

OS: Debian GNU/Linux 11 (bullseye)
Kernel: 5.10.0-26-amd64 (Debian 5.10.197-1 (2023-09-29))
CPU: AMD® Ryzen 7 2700x
Memory: 32GB
Graphics: AMD® Radeon rx 5700
Other (from glxinfo):
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon RX 5700 (NAVI10, DRM 3.40.0, 5.10.0-26-amd64, LLVM 11.0.1) (0x731f)
    Version: 20.3.5
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
```

**Comment by FlexBy420** [comment]
Not official build was used.

**Comment by FlexBy420** [comment]
It works fine on windows, latest build and new cache.
![obraz](https://github.com/RPCS3/rpcs3/assets/68403300/41f54600-2fe9-424c-bfe2-67675cdb7e2a)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13805484/RPCS3.log.gz)

**Comment by tervor** [comment]
> Non official build was used. Use appimage instead of flatpak

Thanks for the hint. Using the appimage worked for me. @FlexBy420 Sorry for wasting your time.
