### ISSUE TITLE
GTA V Broke due to latest update

### ISSUE THREAD

**Issue by Lethality5001** [RPCS3/rpcs3#15013]
### Quick summary

The entire game

### Details

GTAV broke due to latest update, giving the error "Thread terminated due to fatal error: Verification failed" 
it was working fine before this update now it broke. Also someone else said it might be PPU issue. Pls fix
It gives this error at the first loading menu screens.

### Build with regression

v0.0.30-15912-bc141831

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13842778/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13842782/RPCS3.log.gz)

### System configuration

i7 8700
rtx 2070 super
16gb ram

### Other details

Pls fix game not working at all

**Comment by ImagineThisGuy2** [comment]
same issue

**Comment by Lethality5001** [comment]
![Screenshot 2024-01-05 155541](https://github.com/RPCS3/rpcs3/assets/145836476/d311fa29-5d83-4779-8f87-e6db5aa4d917)

**Comment by ImagineThisGuy2** [comment]
same thing

**Comment by kd-11** [comment]
Summoning @RipleyTom

**Comment by ImagineThisGuy2** [comment]
it seems that when u reset and apply wiki options it works but then changing xfloat or zcull accuracy makes the game not work and when changing it back it still dosent work

**Comment by Lethality5001** [comment]
yeah for me nothing worked after this update, completely bricked it

**Comment by ImagineThisGuy2** [comment]
now everything started working so weird

**Comment by Darkhost1999** [comment]
The fatal error is for online play guys.
It starts when network is connected and psn is set to RPCN.
If you test an older version you get the RPCN error for version stuff therefore you can't adequately test a "working" build because there isn't 1 anymore.

**Comment by Darkhost1999** [comment]
If you leave your settings to offline disconnected from the network everything works.
Playing with any other settings doesn't make sense the error is literally SCENP
Sony Computer Entertainment Network protocol.

**Comment by ImagineThisGuy2** [comment]
didnt notice that

**Comment by Lethality5001** [comment]
> The fatal error is for online play guys. It starts when network is connected and psn is set to RPCN. If you test an older version you get the RPCN error for version stuff therefore you can't adequately test a "working" build because there isn't 1 anymore.

But before this update everything was working fine, so what happened now? All it needed tho was matchmaking to work. Could maybe the devs do some cooperation with gtaog guys?

**Comment by Darkhost1999** [comment]
> But before this update everything was working fine, so what happened now? All it needed tho was matchmaking to work. Could maybe the devs do some cooperation with gtaog guys?

All you had to do was test the PR to test for issues before merge. Now you wait for a fix because you didn't test.

**Comment by Lethality5001** [comment]
so the issue is now related to the rpcn of the emulator itself right? I guess we wait for fix...

**Comment by ImagineThisGuy2** [comment]
this seems to be only for gta V as LittleBigPlanet with a custom server works
