### ISSUE TITLE
MLB 10: The Show

### ISSUE THREAD

**Issue by Arachno67** [RPCS3/rpcs3#15039]
### Quick summary

HIGHLIGHT REEL SAVE screen crash

### Details

Hi!

After updating RPCS3 from 0.0.30.15931 to 0.0.30.15946 (or 47) MLB 10: The Show consistently (=every time) crashes at the HIGHLIGHT REEL SAVE screen after pressing "NO".

The game has been completely stable for me during about 35 hours of gameplay before with only minor graphical issues like a few corrupted textures (first base coach of the NY Yankees has a black face), missing eyeballs most likely due to upscaling and some flickering (e.g. Coors Field).

The (shortened) log below:

RPCS3 v0.0.30-15947-17aeefe1 Alpha | master
13th Gen Intel(R) Core(TM) i9-13900KS | 32 Threads | 63.75 GiB RAM | TSC: 3.187GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22631, Service Pack: none, Compatibility mode: 0
Qt version: Compiled against Qt 6.6.1 | Run-time uses Qt 6.6.1
Current Time: 2024-01-12T14:18:21
Thread time: 0.000000s (0.001111Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.005164 SYS: Initialization times before main(): 0.057148Gc
·! 0:00:00.005168 SYS: argc: 1, argv: 'D:\Emu\Sony Playstation 3\RPCS3\rpcs3.exe'
·! 0:00:00.025764 UUID: Installation ID: {430bdba6-6c79-4b93-90a7-a04169fddc3b}
·A 0:00:00.063301 {Vulkan Device Enumeration Thread} RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 4090' running on driver 537.58.0.0
·! 0:00:00.066213 {Vulkan Device Enumeration Thread} SIG: Thread time: 0.000000s (0.118146Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.066452 CFG: Setting the default renderer to Vulkan. Default GPU: 'NVIDIA GeForce RTX 4090'
·! 0:00:00.066469 SYS: Setting user ID '00000001'
·! 0:00:00.071712 VFS: VFS config missing. Using default settings. Path: D:/Emu/Sony Playstation 3/RPCS3/config/vfs.yml
·! 0:00:00.071748 SYS: Using VFS config:
$(EmulatorDir): ""
/dev_hdd0/: $(EmulatorDir)dev_hdd0/
/dev_hdd1/: $(EmulatorDir)dev_hdd1/
/dev_flash/: $(EmulatorDir)dev_flash/
/dev_flash2/: $(EmulatorDir)dev_flash2/
/dev_flash3/: $(EmulatorDir)dev_flash3/
/dev_bdvd/: $(EmulatorDir)dev_bdvd/
/games/: $(EmulatorDir)games/
/app_home/: ""
/dev_usb***/:
  /dev_usb000:
    Path: $(EmulatorDir)dev_usb000/
    Serial: ""
    VID: ""
    PID: ""
·! 0:00:00.071759 VFS: Mounted path "/dev_hdd0" to "D:/Emu/Sony Playstation 3/RPCS3/dev_hdd0/"
·! 0:00:00.071762 VFS: Mounted path "/dev_flash" to "D:/Emu/Sony Playstation 3/RPCS3//dev_flash/"
·! 0:00:00.071763 VFS: Mounted path "/dev_flash2" to "D:/Emu/Sony Playstation 3/RPCS3//dev_flash2/"
·! 0:00:00.071764 VFS: Mounted path "/dev_flash3" to "D:/Emu/Sony Playstation 3/RPCS3//dev_flash3/"
·! 0:00:00.071766 VFS: Mounted path "/app_home" to "//"
·! 0:00:00.071780 VFS: Mounted path "/dev_usb000" to "D:/Emu/Sony Playstation 3/RPCS3/dev_usb000/"
·! 0:00:00.071795 SYS: Applying global config: D:/Emu/Sony Playstation 3/RPCS3//config.yml
·! 0:00:00.074424 SYS: Logged in as user '00000001' with the username 'User'
·! 0:00:00.074494 IPC: IPC config missing. Using default settings. Path: D:/Emu/Sony Playstation 3/RPCS3/config/ipc.yml
·! 0:00:00.074503 SYS: Using IPC config:
IPC Server enabled: false
IPC Port: 28012
·A 0:00:00.074533 SYS: Firmware version: 4.90
·! 0:00:00.089121 GUI: Current language changed to English (en)
·! 0:00:00.093022 Compat: Finished reading database from file: D:/Emu/Sony Playstation 3/RPCS3/GuiConfigs/compat_database.dat
·! 0:00:00.136868 GUI: Determined 'windowsvista' as default style
·! 0:00:00.139385 GUI: Changing stylesheet to 'default'
·! 0:00:00.139390 GUI: Using default stylesheet
·! 0:00:00.227001 NET: Starting download from URL: https://update.rpcs3.net/?api=v2&c=17aeefe1
·! 0:00:00.247855 SYS: New timer resolution: 500 us (old=1000 us, min=15625 us, max=500 us)
·! 0:00:00.683014 NET: Download finished
·S 0:00:00.683049 UPDATER: RPCS3 is up to date!

...

·! 0:20:25.578156 {Performance Sensor} PERF: CPU Usage: Total: 3.1%, Cores: 12.5%, 0.0%, 0.0%, 6.3%, 0.0%, 11.0%, 9.4%, 0.0%, 11.0%, 0.0%, 14.1%, 1.6%, 0.0%, 11.0%, 0.0%, 9.4%, 3.2%, 0.0%, 3.2%, 0.0%, 1.6%, 0.0%, 3.2%, 0.0%, 0.0%, 0.0%, 1.6%, 1.6%, 3.2%, 3.2%, 0.0%, 1.6%
·! 0:20:25.667482 {PPU Syscall Usage Thread} PPU: PPU Syscall Usage Stats:
	⁂ sys_timer_usleep [48188204]
	⁂ sys_event_queue_receive [144385]
	⁂ sys_rsx_context_attribute [143438]
	⁂ sys_mutex_lock [131110]
	⁂ sys_mutex_unlock [96874]
	⁂ sys_fs_read [56557]
	⁂ _sys_lwmutex_lock [41649]
	⁂ _sys_lwmutex_unlock [23341]
	⁂ _sys_lwcond_queue_wait [15073]
·U 0:20:30.145323 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d4734, LR:0x0065400c]} cellRec TODO: cellRecStart()
·! 0:20:30.162448 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d05ec, LR:0x001691f8]} Media: video_encoder: Resuming video encoder
·S 0:20:30.162607 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d05ec, LR:0x001691f8]} Media: video_encoder: resuming recording of 'D:/Emu/Sony Playstation 3/RPCS3/dev_hdd0/game/BCUS98207/USRDIR/VideoData/BOSatRIC_HLREEL_112024135753.mp4'
·! 0:20:30.162638 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d05ec, LR:0x001691f8]} Media: video_provider: setting new video sink. sink=1, type=cell
·! 0:20:30.162665 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d05ec, LR:0x001691f8]} cellRec: Resuming video provider.
·! 0:20:30.162691 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d05ec, LR:0x001691f8]} cellRec: Resuming video sink
·U 0:20:30.162763 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d472c, LR:0x00653f30]} cellRec TODO: cellRecStop()
·! 0:20:30.172699 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d05ec, LR:0x001691f8]} cellRec: Pausing video provider.
·! 0:20:30.172864 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d05ec, LR:0x001691f8]} cellRec: Pausing video sink. flush=1
·U 0:20:30.174122 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d471c, LR:0x00653e1c]} cellRec TODO: cellRecClose(isDiscard=0x1)
·! 0:20:30.194857 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d05ec, LR:0x001691f8]} cellRec: Stopping video provider.
·! 0:20:30.195049 {cellRec video provider} SIG: Thread time: 0.000000s (0.229200Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[49.207s, spur:0]
·! 0:20:30.195298 {PPU[0x1000000] Thread (main_thread) [HLE:0x032d05ec, LR:0x001691f8]} Media: video_encoder: Stopping video encoder. flush=0

Thanks for your great work, I hope this input helps to fix the issue!

### Build with regression

0.0.30.15946

### Attach two log files

Please refer to Details

### Attach capture files for visual issues

![MLB 10 - Highlight Reel_Crash ](https://github.com/RPCS3/rpcs3/assets/35375383/15ae3a6c-9305-47de-b70a-87bf65dc8d07)

**Comment by ChwaraeTeg** [comment]
Can you test build 0.0.30-15945 and see if it crashes there too? If so, then it'll need the full log files to be uploaded from both versions 0.0.30.15931 and 0.0.30.15945. Older versions of RPCS3 are available to download here: https://rpcs3.net/compatibility?b

If it's working in 15945, you'll need to attach a full log file from both 0.0.30.15945 and 0.0.30.15946.

**Comment by Arachno67** [comment]
Thanks for responding so quickly, 0.0.30-15945 is indeed the first build after 0.0.30.15931 with the crashing issue.

In 15931 I pressed "NO" at the Highlight Reel Save screen, exited fullscreen, paused and stopped emulation, then exited.
In 15945 I pressed "NO" at the Highlight Reel Save screen and the emulator crashed.

Clearing the cache files in dev_hdd1 did not make any difference.

I attached the full log for the crash in 15947 as well:

[RPCS3_15931_stable.log](https://github.com/RPCS3/rpcs3/files/13922182/RPCS3_15931_stable.log)
[RPCS3_15945_crash.log](https://github.com/RPCS3/rpcs3/files/13922184/RPCS3_15945_crash.log)
[RPCS3_15947_crash.log](https://github.com/RPCS3/rpcs3/files/13922186/RPCS3_15947_crash.log)

**Comment by Arachno67** [comment]
Tried build 0.0.30-15948, no longer crashing at the Highlight Reel Save screen, much appreciated!
