### ISSUE TITLE
Madden 25 showing up as early access

### ISSUE THREAD

**Issue by UnforgivableStone** [RPCS3/rpcs3#15030]
### Quick summary

No matter how much i reinstall it keeps showing as early access. Ive put the update file in, and its not doing anything. What gives?

### Attach a log file

None

**Comment by FlexBy420** [comment]
You need to dump the license from your PS3.

**Comment by MSuih** [comment]
This indeed appears to be one of the games where not having a valid license will give you a restricted copy. Add a valid license file to access the full game.
