### ISSUE TITLE
[Regression] Need for Speed: The Run - Slight performance regression (#14985)

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#15038]
### Quick summary

NFS The Run performance got regressed after this PR #14985.

### Details

Before: (22.1/24/24.7 FPS)
![NFS The Run Before](https://github.com/RPCS3/rpcs3/assets/125112932/7d04dcb2-6eba-44be-a4d1-b4c185e58f30)

After: (19.9/22/23.1 FPS)
![NFS The Run After](https://github.com/RPCS3/rpcs3/assets/125112932/94b3199e-b1de-42fe-aa8e-44f2935a32f7)

### Build with regression

v0.0.29-15899-6c33c38c

### Attach two log files

15898:
[Before.gz](https://github.com/RPCS3/rpcs3/files/13916262/Before.gz)
15899:
[After.gz](https://github.com/RPCS3/rpcs3/files/13916263/After.gz)

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 546.33.0.0 | Windows 10 Pro 22H2

### Other details

Still happens on the latest build.

**Comment by kd-11** [comment]
Before that fix tiling on linear sections was skipped hence the performance difference.

**Comment by kd-11** [comment]
> > Before that fix tiling on linear sections was skipped hence the performance difference.
> 
> If the new RSX tiling update slightly fixes other games, doesnt that count as a performance regression after this PR which doesnt fixes any graphical bugs for NFS The Run? I thought reporting this issue was necessary because of the regression that lowers the performance and has no affects on visuals for this game.

Just because it has no visual impact doesn't mean it's not working. RSX tiled addressing is a memory subsystem switch and applies to all memory access within some defined boundaries. Even if it is something invisible, if it accesses that area, we have to apply the shuffling.

**Comment by Asinin3** [comment]
I don't see any reason to leave this open, improving accuracy will impact performance, but there are optimisations that can help bring perf back. Ofc another option could be added to go back to the less accurate method but that adds complexity and RPCS3 already has a million options. This is fine as is.
