### ISSUE TITLE
[Feature request] bind two host keys to one emulated system controller key

### ISSUE THREAD

**Issue by reza-souri** [RPCS3/rpcs3#15042]
### Quick summary

i think adding this option is not very hard but its extremely important and very helpful to finishing games. 

bind two host keys to one emulated system controller key for example both *E & Q* on the pc keyboard trigger *R1* on the emulator controller

### Details

i recently finish all God of war games without a controller. i refuse to kill enemies that require rotating left stick but in some part and some boos fight you  have to there is no other way, so every time i have to rotate the left stick i have to pause the game remap the moving keys to *mouse* do the thing and pause again and remap them again to (W A S D) so my character could move.
so if you add an option so people can bind two key from keyboard to one controller key (or in my case keys from key board and mouse) it would be grate. their might be other situations that other players could benefit from this 
pcsx2 (and old ps2 emulator that i use to play GOW 1 & 2 on it) has this future and you can bind as many key as you want to one controller key i will upload a screenshot that i bind mouse and (W A S D) to left stick.

![Screenshot 2024-01-13 040943](https://github.com/RPCS3/rpcs3/assets/42869456/b72eafb8-69ca-4805-b116-94792a46e6c6)

i also think you should make my keyboard lay out your default lay out 
and i also found the perfect setting for doing the rotating left stick with mouse (at least its work perfectly fine with all the GOW games)

![Screenshot 2024-01-13 044508](https://github.com/RPCS3/rpcs3/assets/42869456/365c37d8-a0f4-4f87-af6e-6bc4d20a9c5c)

**Comment by Megamouse** [comment]
You can already append keys by pressing shift while clicking on the button (or maybe it was ctrl)
