### ISSUE TITLE
Aquapazza with monotone characters e.e

### ISSUE THREAD

**Issue by Yagami-kun** [RPCS3/rpcs3#15047]
### Quick summary

Thats happens on both digital & physical versions u.u

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13933677/RPCS3.log.gz)

### Attach capture files for visual issues

![Captura de tela 2024-01-12 06 28 31](https://github.com/RPCS3/rpcs3/assets/16977288/adc87a0f-9e24-4956-a4f3-cc6cdf6ba1dc)
![Captura de tela 2024-01-14 21 37 30](https://github.com/RPCS3/rpcs3/assets/16977288/63f89033-c5d7-4eda-97c4-5b09058aff60)

**Comment by Aurez** [comment]
Confirmed: same here using very last builds
I tried to change some options but I still always got the same result.

**Comment by Yagami-kun** [comment]
> Confirmed: same here using very last builds I tried to change some options but I still always got the same result.

Yeah,thats a shame who this dont till fixed & devs finding this insignificant...
https://forums.rpcs3.net/showthread.php?tid=197772&pid=298355#pid298355

**Comment by Ninetime** [comment]
@Yagami-kun 
Do you encounter this issue with ```Write Color Buffers``` set?
![NPUB31336_screenshot_2024_04_09_07_37_14](https://github.com/RPCS3/rpcs3/assets/6248582/5213391b-ddf3-48c4-93b6-126ee72b203a)
![NPUB31336_screenshot_2024_04_09_07_38_27](https://github.com/RPCS3/rpcs3/assets/6248582/e66b1c94-ee2b-4338-9eb8-d999a960814a)

**Comment by Yagami-kun** [comment]
> @Yagami-kun Do you encounter this issue with `Write Color Buffers` set? ![NPUB31336_screenshot_2024_04_09_07_37_14](https://private-user-images.githubusercontent.com/6248582/320833269-5213391b-ddf3-48c4-93b6-126ee72b203a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTMwOTgsIm5iZiI6MTcxMjY5Mjc5OCwicGF0aCI6Ii82MjQ4NTgyLzMyMDgzMzI2OS01MjEzMzkxYi1kZGYzLTQ4YzQtOTNiNi0xMjZlZTcyYjIwM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTk1OTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc2YzA1Njg3N2I0N2VhYmEyM2I5NTM5YmU4YThiYzQwN2RiYjAwNmFkNzUxYmI1NTA2ZTZkNzEzNWJmZDNjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Cw_VLsorEmbYJbyeBM1iHF6LkE-tG5s28czQwuIPT14) ![NPUB31336_screenshot_2024_04_09_07_38_27](https://private-user-images.githubusercontent.com/6248582/320833293-e66b1c94-ee2b-4338-9eb8-d999a960814a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTMwOTgsIm5iZiI6MTcxMjY5Mjc5OCwicGF0aCI6Ii82MjQ4NTgyLzMyMDgzMzI5My1lNjZiMWM5NC1lZTJiLTQzMzgtOWViOC1kOTk5YTk2MDgxNGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTk1OTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDAwZTVkZWMzOThhOGVmMWU1ZmM5ZmJmZTk3NDNmYWUyNzlmMzBlMGNjMWIyZDIwMTc5ZjRjN2RiYWY3NDc0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SEZoOQ3ugfZSpW_yAxY-LxZSsvKoOm3sDbq1JCv8axA)

Something already told me that this could be it,I just dont know how to fix it ._.

**Comment by Aurez** [comment]
> @Yagami-kun Do you encounter this issue with `Write Color Buffers` set?

Nope it doesn't work, even with "Write Color Buffers"
How did you get these screenshots?

**Comment by Ninetime** [comment]
I loaded the game and replicated the screenshots.
Log for reference

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14924128/RPCS3.log.gz)

**Comment by Yagami-kun** [comment]
> I loaded the game and replicated the screenshots. Log for reference
> 
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14924128/RPCS3.log.gz)

I tried with some of your settings on the log but thats remains the same thing x.x
My log after this...
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14928461/RPCS3.log)

**Comment by Ninetime** [comment]
> > I loaded the game and replicated the screenshots. Log for reference
> > [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14924128/RPCS3.log.gz)
> 
> I tried with some of your settings on the log but thats remains the same thing x.x My log after this... [RPCS3.log](https://github.com/RPCS3/rpcs3/files/14928461/RPCS3.log)

It may be an NVIDIA issue as i can replicate the bug on my machine with a 2060
[RPCS3-ninejp.log.gz](https://github.com/RPCS3/rpcs3/files/14932174/RPCS3-ninejp.log.gz)

**Comment by Yagami-kun** [comment]
> > > I loaded the game and replicated the screenshots. Log for reference
> > > [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14924128/RPCS3.log.gz)
> > 
> > 
> > I tried with some of your settings on the log but thats remains the same thing x.x My log after this... [RPCS3.log](https://github.com/RPCS3/rpcs3/files/14928461/RPCS3.log)
> 
> It may be an NVIDIA issue as i can replicate the bug on my machine with a 2060 [RPCS3-ninejp.log.gz](https://github.com/RPCS3/rpcs3/files/14932174/RPCS3-ninejp.log.gz)

So weird,normally NVIDIA cards dont have issues ._.
& plx,talk about this in the RPCS3 forums because the majority do not have free speech due to the censorship there,my posts always go for approval in that forum & are never approved ¬¬

**Comment by Yagami-kun** [comment]
I sent a PM to the adm on the RPCS3 forums with a link to your post here & he didnt even see,how can these people not care about something so simple to solve ¬¬

**Comment by AniLeo** [comment]
If it's that simple to solve for you then go ahead and solve it, this is a community based project. If you want something done, do it yourself. Now stop spamming the ticket.

**Comment by Yagami-kun** [comment]
> If it's that simple to solve for you then go ahead and solve it, this is a community based project. If you want something done, do it yourself. Now stop spamming the ticket.

Dude stop being so arrogant & toxic,none of this justifies u being so ridiculous & authoritarian to the point of accusing of SPAM,thats just how u deal with those who want to help the emulator to improves??????

**Comment by AniLeo** [comment]
Closing this as the OP shows zero capacity to maintain a serious ticket without spamming it.

@Ninetime as you reproduce the issue, if you can open a new ticket it would be appreciated
