### ISSUE TITLE
Unable to click "config" or "pad" menu items on new install.

### ISSUE THREAD

**Issue by D-elias** [RPCS3/rpcs3#15048]
### Quick summary

When I click on "Config" it crashes with this error on a new install. I deleted the "Config.yml file with no success.

Segfault writing location 00007ff80eed0f34 at 000000000de23f6b.
Thread: Main Thread.
Title: "™ (emulation is stopped)
Build: "0.0.30-15949-4c36b803 Alpha | HEAD"
Date: "2024-01-1418:51:29"
HOW TO REPORT ERRORS:
https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support
Please, don't send incorrect reports. Thanks for understanding.

MacBook Pro
16-inch, 2023
Apple M2 Pro
32 GB
14.2.1 (23C71

https://imgur.com/a/O2EEQPY

### Details

https://imgur.com/a/O2EEQPY

### Attach a log file

https://www.mediafire.com/file/l1s1oy6ozyjhpx1/RPCS3.log/file

### System configuration

MacBook Pro
16-inch, 2023
Apple M2 Pro
32 GB
14.2.1 (23C71

**Comment by ReLyf47** [comment]
Website clearly states starting from MacOS 14.3 is supported
So 14.0-14.2 is not

Also these type of error is to be asked on the discord server not here
