### ISSUE TITLE
Lighting effects broken on LittleBigPlanet 3

### ISSUE THREAD

**Issue by Arcadius2006** [RPCS3/rpcs3#15056]
### Quick summary

Most light-emitting sources in the game don't work with the explicit exception of Spotlights with High Beam Mode enabled

### Details

Point Lights, Spotlights, and emissive materials do not emit anything

The only exceptions to this are spotlights with the High Beam Mode tweak set to on, but even they don't work exactly right

Below is a screenshot comparison between RPCS3 (left) and PS3 (right) (also, sorry for the quality on the PS3 screenshot)
![image](https://github.com/RPCS3/rpcs3/assets/93880348/af8b76e1-2754-465a-af01-550ea3890187) 
![20240117_114203](https://github.com/RPCS3/rpcs3/assets/93880348/e9f0f5c5-a0d7-4dac-8d5e-dee2cec35b3e)
I am terrible at describing, so the screenshot should tell most of the story 

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13962076/RPCS3.log.gz)

### Attach capture files for visual issues

[NPEA00515_20240117115302_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/13962115/NPEA00515_20240117115302_capture.rrc.gz)

### System configuration

CPU: Intel Core i5 10400F @ 2.90GHz
GPU: Nvidia Geforce GTX 1650 Super
RAM: 16GB

### Other details

LittleBigPlanet 2 may also have this issue, but i'd have to check that later, as the reporting process itself is quite tedious

**Comment by FlexBy420** [comment]
Issues with patches enabled are not allowed. Disabling MLAA is known to break some effects in lbp games

**Comment by Arcadius2006** [comment]
oi

that explains quite a lot

let me try it without that patch then

**Comment by Arcadius2006** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/93880348/70004e60-446f-4393-8cc6-255dd0178839)
[NPEA00515_20240117121925_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/13962345/NPEA00515_20240117121925_capture.rrc.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13962354/RPCS3.log.gz)

Fogginess got fixed, but the lighting itself is still fucked still fucked
i can atleast confirm that LBP2 does *not* have this issue

**Comment by FlexBy420** [comment]
Wiki mentions to use Read color buffers to fix some missing visuals, looking at your log you don't have that enabled, so try that.

**Comment by Arcadius2006** [comment]
i'll try that, but for now have a screenshot of everything working just fine on LBP2 despite it not working on 3
![image](https://github.com/RPCS3/rpcs3/assets/93880348/b5f81582-bf9f-44f8-857c-2a0554598a0b)

**Comment by Arcadius2006** [comment]
huh, that DOES help

i must also add that LBP3 doesn't lag as much as 2

i assume they did some optimisation between the two games

nice

**Comment by Arcadius2006** [comment]
i'd like to add something onto this

in debug builds of LBP games, there IS an option to turn off MLAA, which doesn't appear to break anything when used

maybe somebody could try monitoring the changes made when that's turned on in that game and try making a patch out of that instead?

**Comment by Arcadius2006** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/93880348/de91df8f-3a79-4415-b1a7-78c6521be97e) 
![image](https://github.com/RPCS3/rpcs3/assets/93880348/cec24162-11be-49c2-9b58-8f8baf2fae98)
really makes you think.

anyway, thanks for helping!
