### ISSUE TITLE
BUG: in Resistance 3 if using both fps unlock patch and zcull accuracy set to relaxed when aiming fps drops to 1.

### ISSUE THREAD

**Issue by Roman13456** [RPCS3/rpcs3#15051]
### Quick summary

So if i play resistance 3 with zcull set to relaxed game runs well right untill i added fps unlock path: if i aim from any rifle (like bullseye) fps drops to 1 untill i stop aiming. Without the patch all seems fine and this issue is not existent

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13943200/RPCS3.log.gz)

### System configuration

ryzen 5 5600x
rtx 3070
Windows 10
gpu driver: 31.0.15.3713

### Other details

![lag](https://github.com/RPCS3/rpcs3/assets/99034241/41be9868-c399-4bbd-abc8-7130ec996e09)
![no lag](https://github.com/RPCS3/rpcs3/assets/99034241/75bf0f7a-1b92-4d9a-a715-c7f86f370668)

**Comment by Megamouse** [comment]
issues with patches applied are not allowed
