### ISSUE TITLE
Fixed alpha not specified for padding (cellPngDec)

### ISSUE THREAD

**Issue by MyaniPT** [RPCS3/rpcs3#1505]
```
{PPU Thread[0x1] (main_thread)[0x0035b84c]} Exception: Fixed alpha not specified for padding.
(in file Emu\SysCalls\Modules\cellPngDec.cpp:597, in function pngDecodeData)
Please report this to the developers.
```

Happens in PAC-MAN Championship Edition DX Trial **[NPUB30304]**
Log @ [rpcs3_476.zip](https://github.com/RPCS3/rpcs3/files/133103/rpcs3_476.zip)
Probably started happening after #1359

**Comment by tambry** [comment]
No idea why the game wants the output to be in 4 components, when no fixed alpha padding value isn't specified. There's probably a default value (255?), but that would require testing on a PS3.

**Comment by tambry** [comment]
Sadly I can't work investigate/work on these problems, due to _UTF8stoUTF16s_ not being implemented along with:
`Unknown/illegal instruction: 0x17 (forced unit 0)`

**Comment by tambry** [comment]
Okey, I have made a temporary fix. Sadly the games have other problems, which I'm not sure if they're caused by cellPngDec implementation.
I'd like to be able to test a final fix on more games, that encounter the problem. Let me know, if you find any.

**Comment by MyaniPT** [comment]
I'm closing it since the issue was resolved, unless you want to keep it open. (This to help prevent unnecessary issues open)
