### ISSUE TITLE
[Regression] Enter a title here

### ISSUE THREAD

**Issue by lexthedev** [RPCS3/rpcs3#15057]
### Quick summary

immediate crash upon opening pads ui.
running on macOS 14.2.1.

### Details

![Screenshot 2024-01-17 at 23 52 40](https://github.com/RPCS3/rpcs3/assets/44236172/2b121190-c0ea-4355-ac4d-eb9d392aa8e5)

the popup shows this:
Segfault reading location 0000000000000034 at 000000000de72f6b.
Thread: Main Thread.
Title: "" (emulation is stopped)
Build: "0.0.30-15968-e23db7ef Alpha | HEAD"
Date: "2024-01-17T23:52:15"

### Build with regression

v0.0.30-15968-e23db7ef Alpha

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13968736/RPCS3.log)

### Attach capture files for visual issues

![Screenshot 2024-01-17 at 23 52 40](https://github.com/RPCS3/rpcs3/assets/44236172/2b121190-c0ea-4355-ac4d-eb9d392aa8e5)

### System configuration

macbookPro m1 pro macOS 14.2.1

**Comment by Darkhost1999** [comment]
Similar if not the same issue is found
https://github.com/RPCS3/rpcs3/issues/14997
