### ISSUE TITLE
[Feature request] Add more options for fake PSMove (multiple ps move)

### ISSUE THREAD

**Issue by nixxou** [RPCS3/rpcs3#15059]
### Quick summary

It would be nice to have some extra options in the Configuration windows for the fake PS Move.
First, be able to set the number of ps move, in the code, it's simple, it's just the variable connected_controllers to change, with this to 2, i was able to play 2 player on Time Crisis 4 (the one within Time Crisis Razing Storm )

### Details

It would be nice to add an extra option for the fake PS Move :  the ability to change the value of connected_controllers in void reset_controller(u32 gem_num).
If i set this to 2, i can actually play with two ps move using my gamepad in Time Crisis Razing Storm !

https://streamable.com/hicyqg

I don't know for other lightgun, but the sinden one, on their newest firmware can emulate joysticks, so with the fake PSMove, i'm able to play 2 players on those game with lightgun.

**Comment by Megamouse** [comment]
Please try with #15130 
Make sure to read the description.
