### ISSUE TITLE
[MoltenVK] [macOS] Can't update to MVK 1.2.7 as vkSetMoltenVKConfigurationMVK is deprecated

### ISSUE THREAD

**Issue by shinra-electric** [RPCS3/rpcs3#15050]
### Quick summary

I tried updating to MVK 1.2.7 ([Vulkan SDK 1.3.275](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.7)) but building fails because `vkSetMoltenVKConfigurationMVK`  is deprecated. 

### Details

According to the docs in `mvk_deprecated_api.h`:

```
To set configuration values, use one of the following mechansims:
 - The standard Vulkan VK_EXT_layer_settings extension.
 - Application runtime environment variables.
 - Build settings at MoltenVK build time.
```

RPCS3 uses it [in this section of the code](https://github.com/RPCS3/rpcs3/blob/fa7ef870ddfed8e85157798b0531a542c3193f52/rpcs3/Emu/RSX/VK/vkutils/device.cpp#L159-L184)

**Comment by Megamouse** [comment]
We're on Vulkan SDK 1.3.268. So It's to be expected.

**Comment by Megamouse** [comment]
you could either
```
#include <MoltenVK/mvk_deprecated_api.h>
```
or replace the call.

**Comment by shinra-electric** [comment]
Adding `#include <MoltenVK/mvk_deprecated_api.h>` to `device.cpp` does allow the build to complete successfully. However, I think replacing the call would be the preferred fix. 

Unfortunately that's beyond my abilities. Maybe @nastys might be able to have a look, as they wrote the original code..?

**Comment by Megamouse** [comment]
try with #15052
