### ISSUE TITLE
[Regression] PlayStation Home QT Platform Plugin causing RPCS3 not to update 

### ISSUE THREAD

**Issue by Splicewave** [RPCS3/rpcs3#15076]
### Quick summary

![image](https://github.com/RPCS3/rpcs3/assets/71703832/955b2c30-b7ef-4968-b4b0-3c1e6c5611ba)

This image appears whenever I try to update RPCS3 with my PS Home build. But the truth is that I do not need a QT platform plugin for PS Home as what that does is inside the custom PKG I use. 

### Details

In the PS Home space, theres 3 groups that have a playable server  on RPCS3 and theres 2 ways that is handled. 

1 way is to have a premade custom RPCS3 build thats modified to have such a QT platform plugin which comes with the custom PKG for PS Home.

The 2nd way to do it is to use a regular RPCS3 build and have what that QT Platform plugin does (which is disable MLAA and bypass EULA) built into the games EBOOT.BIN file inside the custom PKG that you install which is the approach that I do. 

Essentially, what that QT Plugin does, my custom PKGs eboot.bin file does so I don't need it. Also I know about the recent update that fixes EULA for PS Home which is good but I plan to make a new PKG for PS Home on RPCS3 once MLAA is disabled in RPCS3 for PS Home since that's the last issue it has on RPCS3 regarding booting. 

This issue can be replicated on a regular RPCS3 build and the current PKG I use for RPCS3 is this one: 
https://mega.nz/file/PBsnFaYS#GaSnFeEUoYnZemIyajIAc0adV11KF95_nUCfZjtJFSM

### Build with regression

v0.0.30-15987

### Attach two log files

[rpcs3.log](https://github.com/RPCS3/rpcs3/files/14000925/rpcs3.log)
rpcs3.log.gz does not exist. only rpcs3.log exists when it closed after the error screen. 

### Attach capture files for visual issues

https://github.com/RPCS3/rpcs3/assets/71703832/070fc467-1034-4499-ad48-aacd02c32f75

### Other details

![image](https://github.com/RPCS3/rpcs3/assets/71703832/fa3e08e7-1118-4d2a-aacc-2f556c8c3aec)

Also before the update, this never happened. Everything I have highlighted should only be inside "PlayStation Home R" folder

**Comment by Megamouse** [comment]
Rebase to the latest commit.
Anyways, custom builds are not allowed in the issue tracker.

**Comment by Splicewave** [comment]
I don't use a custom build. Mine is a regular RPCS3 build.

**Comment by JWatersMeet** [comment]
Same issue here on Windows 11 - using a regular build. Seems like a '\' is missing in the updater somewhere, as the existing folder name has the subdirectories pre-pended to it. Maybe an issue with the recent portable build changes?

**Comment by Splicewave** [comment]
> Same issue here on Windows 11 - using a regular build. Seems like a backslash is missing in the updater somewhere as the existing folder name has the subdirectories pre-pended to it. Maybe an issue with the recent portable build changes? or the executable directory path?

https://github.com/RPCS3/rpcs3/assets/71703832/484ffa80-b57e-4d16-acb2-ca25b2af0c39


I was shown this fix. Just a manual RPCS3 install over your existing RPCS3 and it works again
