### ISSUE TITLE
[Feature request] usb passthrough doesn't work for guitar hero guitars

### ISSUE THREAD

**Issue by sanjay900** [RPCS3/rpcs3#15073]
### Quick summary

I've noted that passthrough works perfectly fine for rock band instruments, but not guitar hero instruments. 

I tested both Rock Band 2, Guitar Hero 3 and DJ Hero, and I noted that none of the games pick up passed through guitar hero guitars, but Rock Band 2 picks up a passed through Rock Band guitar and DJ Hero picks up a passed through DJ Hero Turntable.

### Details

One thing i noted was that `sys_usbd_register_extra_ldd` was never registering extra ldds for the guitar hero instruments. DJ Hero only calls this for the turntable, and rock band only calls this for RB Instruments.

**Comment by Megamouse** [comment]
That depends if the games support the guitar hero guitar on a real console.
It's also depends what exact device you are trying to connect (name, VID, PID).
And lastly it depends how you configured it in rpcs3.
Some devices are not used per passthrough but are merely glorified controllers that you have to assign and configure in the pad window

**Comment by sanjay900** [comment]
It definitely works on console, and it does work if I bind it via pad input, I was just hoping passthrough would work too since then I wouldn't have to get users of my firmware to manually bind things via pad config

**Comment by Megamouse** [comment]
Well. the Guitar Hero 4 controller was specifically supported by the pad api, so unless you can prove that the game uses libusb to directly talk to that specific device, you're stuck with the official pad input bindings.
I don't see any other reason why it shouldn't work, as that device is whitelisted for passthrough.
If that's the case, this issue can be closed.

**Comment by sanjay900** [comment]
Ah i see that makes sense, ill close this issue
