### ISSUE TITLE
File path error causing broken updates on Windows

### ISSUE THREAD

**Issue by Koopa777** [RPCS3/rpcs3#15077]
### Quick summary

Auto updates causing broken update on Windows due to not including the trailing backslash in the Emulator directory path

### Details

My Emulator directory is D:\Emulators\RPCS3\ , however when updating from 0.0.30-15970 the Updater instead used D:\Emulators\RPCS3 which named all the new files as RPCS3* and placed them in D:\Emulators\ instead, which required me to manually rename all the folders/files and place them back in the directory to fully update my installation. I presume this only affects those already on 0.0.30-15970, -15979 or -15987, but the auto-updater will presumably not work indefinitely on those builds without manually manipulating the files. Not sure if this is an issue stemming from the 15970 build, or the fix implemented in 15989, as I was attempting to update from 15970 -> 15994.

### Attach a log file

[RPCS3 - Copy.log](https://github.com/RPCS3/rpcs3/files/14002083/RPCS3.-.Copy.log)
![Screenshot 2024-01-21 113939](https://github.com/RPCS3/rpcs3/assets/6834374/d135a128-14e7-44dc-896c-421cb249ffc3)

### System configuration

Windows 11 22H2 22621.3007

**Comment by AniLeo** [comment]
Already fixed, if you're on one of the affected builds you have to update manually
