### ISSUE TITLE
Seeing "Segfault reading location" errors

### ISSUE THREAD

**Issue by eisnerguy1** [RPCS3/rpcs3#15080]
### Quick summary

Seeing a few games with a "Segfault reading location" error message.

### Details

I've come across some games that display an almost identical error messages when game prompts to create a save file or warn to not exit the game while is saving:
"Segfault reading location 0000000000000000 at 0000000000d8da2e.
Thread: Main Thread."

Or this one:
"Segfault reading location 0000000000000000 at 0000000000d8d98e.
Thread: Main Thread."

RPCS3 Build: "0.0.30-15969-96d88083 Alpha | HEAD"

I've noticed the issue in these games so far:
* [Mega Man 9](https://wiki.rpcs3.net/index.php?title=Mega_Man_9)
* [Mega Man 10](https://wiki.rpcs3.net/index.php?title=Mega_Man_10)
* [Sonic 4 Episode 1](https://wiki.rpcs3.net/index.php?title=Sonic_the_Hedgehog_4_-_Episode_I)
* [Sonic 4 Episode 2](https://wiki.rpcs3.net/index.php?title=Sonic_the_Hedgehog_4_-_Episode_II)
* [Sonic The Fighters](https://wiki.rpcs3.net/index.php?title=Sonic_the_Fighters)
* [Sonic Generations](https://wiki.rpcs3.net/index.php?title=Sonic_Generations)

None of the compatibility wiki pages mention this error message. Is this a macOS specific bug?

Hopefully my attached log files can be useful.

Any help at all would be greatly appreciated.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14006650/RPCS3.log)
[RPCS3_2.log](https://github.com/RPCS3/rpcs3/files/14006564/RPCS3_2.log)

### System configuration
CPU: Apple M3 Max
GPU: Apple M3 Max
RAM: 128 GB
OS: macOS Sonoma 14.2

**Comment by AniLeo** [comment]
As indicated on the requirements, macOS 14 is currently not supported. 14.3 or newer will be required once that's released.

**Comment by eisnerguy1** [comment]
Ah, I'm not sure how I missed that. 🤔  Thanks for the information 😄👍🏻
