### ISSUE TITLE
Mic not working | Socom Confrontation

### ISSUE THREAD

**Issue by Awatatah** [RPCS3/rpcs3#15085]
### Quick summary

For Socom: US Navy SEALs Confrontation (BCUS98152) the mic does not work.
Confirmed mic is working and input is detected in windows.

RPCS3 Version: 0.0.30-15996-93f51544 Alpha | master

### Details

Mic not working. Attempted mic input in game right before closing application to get logs.
RCPS3 detects device for Mic 1
The game shows a headset is detected
I can hear others talking (must be on actual PS3 console)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14017961/RPCS3.log.gz)

### System configuration

OS: Windows 10 Pro 64bit (build 19045)
System model: Z590 AORUS Master
Processor: i7-10700K
RAM: 32GB
GPU: NVIDIA GeForce RTX 4070

### Other details

Tried both bluetooth and wired headsets

**Comment by Darkhost1999** [comment]
Socom Confrontation is an online-only game.
Mic isn't implemented for online content at all.
I believe it's a low priority because how would any type of online vocals be moderated? It can be moderated by people having the sense to choose whether or not to play online with certain people. But beyond that, if implemented will not feasibly be maintained by anyone.
Shouting at clerks in GTAV is something strongly desired rather than shooting all the merchandise. But because shooting the merchandise is an alternative this doesn't raise any priority on the demand.
I'm just saying a feature request like this might get a longterm label.

**Comment by RipleyTom** [comment]
That game actually uses cellMic and I assume does its own capture and sends the data to the private server/other players. cellMic should work, the issue may be with the private server?

**Comment by cipherxof** [comment]
> That game actually uses cellMic and I assume does its own capture and sends the data to the private server/other players. cellMic should work, the issue may be with the private server?

Metal Gear Online's mic functionality also doesn't work in RPCS3. This has nothing to do with our server either, as the mic works for PS3 players.

**Comment by Awatatah** [comment]
> > That game actually uses cellMic and I assume does its own capture and sends the data to the private server/other players. cellMic should work, the issue may be with the private server?
> 
> Metal Gear Online's mic functionality also doesn't work in RPCS3. This has nothing to do with our server either, as the mic works for PS3 players.

Yes. Same for SOCOM Confrontation. Mic works for PS3 players but not RPSC3

**Comment by snnaakee** [comment]
> That game actually uses cellMic and I assume does its own capture and sends the data to the private server/other players. cellMic should work, the issue may be with the private server?

That's correct. It uses cellMic, the client send the data to the server which will broadcast it to the clients.

cellMicRead warning log can be seen in the logs:
`W cellMic: cellMicRead(dev_num=0, data=0xd011cb18, maxBytes=0x400) x5`

**Comment by Awatatah** [comment]
> That game actually uses cellMic and I assume does its own capture and sends the data to the private server/other players. cellMic should work, the issue may be with the private server?
Any ideas on this? The servers seem to be fine.

**Comment by Awatatah** [comment]
Adding more info:
Windows shows the emulator is using my microphone

![image](https://github.com/RPCS3/rpcs3/assets/17914534/6391d481-e24b-45c7-88fa-24751e34825f)

![image](https://github.com/RPCS3/rpcs3/assets/17914534/8575c86a-d561-4bdf-b5b0-129e9a2ba2c7)

**Comment by Awatatah** [comment]
Adding a little more info: I spoke to about 10 other players using the emulator also are not able to use mic.
It seems for this title, the mic doesn't work for anyone using the emulator.

**Comment by shankly1985** [comment]
I am experiencing the same problem.

**Comment by Awatatah** [comment]
Any update? :eyes:

**Comment by cipherxof** [comment]
I did some digging into Metal Gear Online and there seems to be multiple issues.

First of all, MGO's mic handling code looks *something* like this:

```cpp
cellMicGetSignalState(0, CELLMIC_SIGSTATE_MICENG, &result);

if (result > micThreshold) {
    playerIsTalking = true;
}

size_t len = cellMicRead(0, buffer, 0x4000);
memcpy(dest, buffer, len);
```

The first issue is that the game expects `CELLMIC_SIGSTATE_MICENG`'s value to be anywhere from 45.0f and 72.0f, depending on the user's settings. In order for this functionality to properly work, the actual value will likely need to be determined from the latest samples in `update_audio`.

The second issue is that even when hardcoding the decibels to a value within that range, you still can't hear the mic from PC players, despite the in-game notification popping up that the player is speaking.

I noticed `cellMicRead` is always returning buffers of size 0x00, 0xa0, and 0x1a0. I'm not entirely sure if those values are correct, but I thought it was worth noting.

**Comment by Awatatah** [comment]
👀

**Comment by Awatatah** [comment]
Man, anything gonna move on this issue? Would be great to have voice chat working

**Comment by snnaakee** [comment]
@Megamouse 

I spent the week debugging the PS3 and RPCS3 to determine why the microphone isn't working in SOCOM on RPCS3.

**I finally discovered all the issues :**

### ISSUES

1. Audio Format:
   * Socom is using cellMicRead and gets audio data from the DSP stream
   * On rpcs3, the DSP stream is the same as the RAW stream (Digital signal processing isn't implemented, no surprise)
   * DSP stream : 32-bit
   * RAW stream : 16-bit

2. Audio Data Polling Frequency:
   * On the PS3, cellMicRead is called every 16ms, whereas on RPCS3, it's called every 5ms (hardcoded in cellMic.cpp)

### FIXES

1. Audio Format:
   * **RPCS3 currently records microphone audio data in 16-bit using OpenAL, which is not intended for this purpose. To capture audio data in 32-bit float as required for the DSP stream, we would need a different framework, such as PortAudio**

1. Audio Data Polling Frequency:
   * Regarding syncing cellMicRead calls, this is beyond my skills

### CONCLUSION

Now, on RPCS3 I can read WAV files and inject the audio data to be processed by cellMicRead, hardcoding a 16ms timestep. This approach allows me to hear the audio correctly on RPCS3, but it won't work if the audio is in 16-bit format

I'm unable to contribute at this level as my C++ skills are too weak. 
However, I will do my best to answer any questions and hope to eventually resolve this issue, allowing players to use their microphones.

### DETAILS

Audio tests I have done using the sdk sample project "capture". Which record and save microphone audio data from DSP/RAW/AUX stream in wav format.
cellMicRead must be polled every 16ms and a sample rate of 8000 (like socom), in order for this to work

- Playing DSP audio on from PS3 on RPCS3 : it works
- Playing the same audio on rpcs3, but from RAW stream : doesn't work
- Playing any audio on rpcs3 that have the same format as a DSP stream would have on PS3 : it works

I can provide the WAV files used for the test or assist anyone in reproducing my steps.

**Comment by Awatatah** [comment]
@Megamouse when will the official release of this be? Or is it already out since it was merged?

**Comment by Megamouse** [comment]
give it about an hour
