### ISSUE TITLE
game crashes upon loading trophies

### ISSUE THREAD

**Issue by AndrewACEGaming** [RPCS3/rpcs3#15081]
### Quick summary

as the title says, my sonic the fighters game crashes whenever it loads trophies, the only solution i have found so far is deleting the trophies. is there any way to fix this or disable trophies all together?

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14012647/RPCS3.log.gz)

### Attach capture files for visual issues

![image](https://github.com/RPCS3/rpcs3/assets/92270905/d2224eb9-ce84-4377-b47f-0f79739a3282)

**Comment by RipleyTom** [comment]
As the message indicates it failed to remove the trophy directory, which is most likely because of either access rights or something like OneDrive interfering. Move rpcs3_emulator folder to C:/rpcs3/ or somewhere similar.
If you require further help use Discord.
