### ISSUE TITLE
in portable mode UI icons are not copied into the portable folder

### ISSUE THREAD

**Issue by Sky-Poem** [RPCS3/rpcs3#15108]
### Quick summary

if you start a game when in portable mode the log gives some errors that it cannot find UI icons like this 

```
`E RSX: Image resource file `E:\Emulation\PS3\RPCS3//portable/Icons/ui/fade_top.png' could not be opened (Not found)
E RSX: Image resource file `Icons/ui/fade_top.png' could not be opened (Not found)` 
```

as you can see it looks for the icons in the portable folder when they are in the root directory.  i do not know if it can creats any problems in games but i just wanted to report it just in case

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14072120/RPCS3.log.gz)

**Comment by AniLeo** [comment]
I think we should just remove this portable stuff from Windows, because it was already portable even without it.

**Comment by Sky-Poem** [comment]
just my opinion but i actually like it since it keeps it really clean, but if it creates more work maintainers its understandable.

**Comment by AniLeo** [comment]
There's really no difference. You can already create a shortcut to rpcs3.exe and have it on the parent folder of where the emulator is, if that's the intention.

**Comment by Megamouse** [comment]
If you created a portable directory, why didn't you move the files there? this is user error at best

**Comment by Sky-Poem** [comment]
@Megamouse  it happens even when you start with a fresh install, after creating the portable folder and opening the rpcs3 for the first time, it does not move the Ui icon folder into it

**Comment by Megamouse** [comment]
Why should it? you're assuming the existence of a portable dir somehow magically copies your data around.
The creator of this feature never intended this.

It's like wondering why your steak isn't cooking when you put it in sink next to pan.

**Comment by Sky-Poem** [comment]
can you do a test yourself? it does not move the icon folder into it it, and i can manually copy them but the fact that it does not move them automatically is a bug, not an user error.

**Comment by MSuih** [comment]
Portable mode is an advanced feature. If you're using it you're expected to know what you're doing, it doesn't hold your hand.

We can remove it at least from Windows if it causes too much confusion.

**Comment by Sky-Poem** [comment]
i am sorry but this is not an advance feature, i am not playing with the code or some binaries. it is basically making a folder so i can move the user data faster. now there is a bug and i am trying to report it but i don't understand why the conversation needs to move in a way that i am making a mistake

**Comment by AniLeo** [comment]
Nothing is supposed to be automatically moved to the portable folder, that's not a bug.

Regardless, I still think that this should be removed on Windows as it's completely redundant.
