### ISSUE TITLE
Enter a title here

### ISSUE THREAD

**Issue by naron23vrn** [RPCS3/rpcs3#15104]
### Quick summary

Tell me, I'm playing God of War 3 and this error is happening, what should I do?

### Details

please tell me what to do I recently updated my hardware and have been wanting to play good of war 3 for a long time

### Attach a log file

![Screenshot 2024-01-27 000357](https://github.com/RPCS3/rpcs3/assets/54803761/2bcefaa6-c249-4217-95cb-412aa09b9520)

**Comment by FlexBy420** [comment]
Support request goes either on discord or forums, not github.
