### ISSUE TITLE
game fails to open if the name of the folder is not the serial number

### ISSUE THREAD

**Issue by Sky-Poem** [RPCS3/rpcs3#15101]
### Quick summary

after installing littlebigplanet 1 (PSN version) with a package file, i moved the folder to another place to keep it clean but i found out that if the name of folder is changed it will just crash after building SPU catch.

changing the name to the serial number fixes it, and gets into the games.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14066069/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Yes. That's how it is

**Comment by Megamouse** [comment]
You can put it in a subdirectory but the original folder name has to be preserved
