### ISSUE TITLE
Broken graphics in Uncharted 3

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#15103]
### Quick summary

There are several graphical issues in Uncharted 3 that I've seen in this game years ago and still haven't been fixed

### Details

1 - Showing light in the wrong place
2 - Messing up and breaking the faces of the characters
3- There is flashlight light on the left side of the image but not on the right side of the image

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14067014/RPCS3.log.gz)

### Attach capture files for visual issues

![uncharted 3 bugs](https://github.com/RPCS3/rpcs3/assets/25039098/9b416f36-01ae-44fc-a553-33499c0c3402)
![00](https://github.com/RPCS3/rpcs3/assets/25039098/b44fbcd4-f791-405e-9175-bd081289284c)

### System configuration

amd ryzen 3900x
nvidia 3070 RTX
ram 32 GB
windows 11 version 21H2

**Comment by RipleyTom** [comment]
Piracy + patches enabled
