### ISSUE TITLE
[Feature request] Support more anaglyph colors

### ISSUE THREAD

**Issue by SupernaviX** [RPCS3/rpcs3#15119]
### Quick summary

RPCS3 supports "anaglyph" 3d, but only using red/cyan colors. It'd be nice to use different colors, to support more 3d glasses.

### Details

Anaglyph 3d is a 3d rendering technique where the view for the left eye is drawn using one color, and the view for the right eye is drawn using another. Red/cyan (using red for the left eye and cyan for the right eye) is the most iconic and popular set of anaglyph colors, but there are [several options](https://en.wikipedia.org/wiki/Anaglyph_3D#Anaglyphic_color_channels). In particular, trioscopic (green/magenta) and ColorCode-3D (amber/blue) are great alternatives.

RPCS3 has an "Anaglyph" 3d rendering option, but it only uses red/cyan and there's no way to choose any other set of color. It'd be nice if we could change the color scheme to support more 3d glasses. Either by supporting other hard-coded color pairs, or with some kind of color picker.
![rpcs3_G0OpHMjf5Y](https://github.com/RPCS3/rpcs3/assets/1137435/6ae9561d-d34c-4011-a469-831c7eaafdf5)

**Comment by Megamouse** [comment]
Please test with #15125

**Comment by SupernaviX** [comment]
Thank you so much! I'll test once I've got it building

**Comment by MSuih** [comment]
You can just download from our ci, [see instructions here](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_download_builds_from_a_pull_request_on_GitHub?)

**Comment by SupernaviX** [comment]
Whoops I wish I saw that before getting it all set up. Oh well, I figured it out in the end

![rpcs3_qDlNY82rMf](https://github.com/RPCS3/rpcs3/assets/1137435/7c005a79-8b9f-4ed3-921a-d7fc0fe2ada4)
