### ISSUE TITLE
WipEout HD Fury [BCES00664] | Main menu aircraft graphics partially missing

### ISSUE THREAD

**Issue by f00tf00t** [RPCS3/rpcs3#15110]
### Quick summary

This issue has been present even since its 'in-game' status; the particle of the racing vehciles are partially missing, tested with default settings and custom settings (https://wiki.rpcs3.net/index.php?title=WipEout_HD) but still the same issue

### Details

From my PS3
![ps3_crop](https://github.com/RPCS3/rpcs3/assets/71181157/3a472172-0c15-4f11-b56f-08bb4c5bb0e4)

From RPSC3
![rpcs3_crop](https://github.com/RPCS3/rpcs3/assets/71181157/44a69172-fb35-4dc1-9715-e999e554dde7)

### Attach a log file

[WipEout HD Fury [BCES00664].log.gz](https://github.com/RPCS3/rpcs3/files/14072389/WipEout.HD.Fury.BCES00664.log.gz)

### Attach capture files for visual issues

[BCES00664_20240127132816_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/14072410/BCES00664_20240127132816_capture.rrc.gz)

**Comment by ChwaraeTeg** [comment]
Same issue as #12160?

**Comment by Satan86** [comment]
Yes, this is a duplicate.
