### ISSUE TITLE
[Regression] LittleBigPlanet 2 (NPEA00324) fails to connect to any custom servers

### ISSUE THREAD

**Issue by uhwot** [RPCS3/rpcs3#15113]
### Quick summary

Ever since PR #15105, LittleBigPlanet 2 refuses to connect to any custom servers (such as Beacon, Refresh, Infinite) with the error message "A problem occurred when attempting to connect to the LittleBigPlanet servers".

### Details

Regression (v0.0.30-16011-3dbde04d):
![NPEA00324_screenshot_2024_01_28_02_33_25](https://github.com/RPCS3/rpcs3/assets/54753080/31b6e73a-f4b8-47f1-bd29-2732153d3419)

Working (v0.0.30-16009-93c72822):
![NPEA00324_screenshot_2024_01_28_02_35_31](https://github.com/RPCS3/rpcs3/assets/54753080/6fcc301a-abf4-4cd3-b56b-f12b2c769a52)

LittleBigPlanet 1 is not affected.

### Build with regression

v0.0.30-16011-3dbde04d

### Attach two log files

Regression (v0.0.30-16011-3dbde04d):
[RPCS3.regression.log](https://github.com/RPCS3/rpcs3/files/14074590/RPCS3.regression.log)

Working (v0.0.30-16009-93c72822):
[RPCS3.working.log](https://github.com/RPCS3/rpcs3/files/14074591/RPCS3.working.log)

### System configuration

OS: Windows 11 Pro 23H2
APU: AMD Ryzen 7 5825U with Radeon Graphics, 2000 Mhz, 8 Core(s), 16 Logical Processor(s)

### Other details

I think this regression is caused by the variable "is_NP_Com2_init" never being set to true, so almost every sceNpCommerce2 call ends up returning the error SCE_NP_COMMERCE2_ERROR_NOT_INITIALIZED.

**Comment by Walid3810** [comment]
I got this Too
