### ISSUE TITLE
RPCS3 with original Dualshock 3 Controllers - Motion Controls not working correctly (G axis)

### ISSUE THREAD

**Issue by SiriusVI87** [RPCS3/rpcs3#15129]
### Quick summary

I want to use Dualshock 3 Controllers on RPCS3, but the motion controlls don't work on all but one of my original DS3 controllers in conjunction with DSHidMini.

### Details

​Hello everyone,

over the last few years, I've been on a quest of collecting original controllers for various consoles to be able to play emulated games with them.

Currently I am facing a problem using RPCS3 with original Dualshock 3 Controllers. So here is what I initially did / tried with the first two DS3 controllers I bought:

1. I tried DSHidMini, which is almost perfect, but there seems to be a bug with the motion controlls. Here is a video showcasing what I am experiencing:

https://youtu.be/dGOt_ZNfiWU

* Apparently, the "G axis" does not work with original DS3 controllers (DS4 and DualSense or even Switch Pro Controllers work perfectly, by the way). I originally tried 2 original DS3 controlers with it and both have the same issue / bug with the G axis.

* However, **I recently bought a third DS3 controller and IT actually works with DsHidMini** .

2. I tried original Sony Drivers for Windows:

* On these drivers, **ALL controllers I tried have perfectly functioning Motion Controlls** ( **that's how I know that my controllers aren't broken, by the way** ).
* However, these drivers do NOT support Wireless functionality over Bluetooth
* Also, These drivers are incompatible with certain Windows 11 security settings. I'd have to permanently disable the "Core Isolation" feature, which I don't really want to do.

I've have since bought a fourth DS3 controller and it also has the issue with the broken G axis. That tells me that at least this is not an isolated issue. A lot of controllers seem to have this problem. I wonder if there is some way to figure out how to tell what controller will or won't work

Just to make sure that my PC config is not at fault, I tried all controllers on a separate PC and they show the exact same behavior. So it's not my config that's at fault, either.

All devices show in DSHidMini as: USB\VID_054C&PID_0268\7&E523A19&0&3

There is no difference.

Thx for all your input!

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14116797/RPCS3.log)

### System configuration

OS Windows 11 Pro
Processor	13th Gen Intel(R) Core(TM) i7-13700K   3.40 GHz
Installed RAM	32,0 GB (31,8 GB usable)
GPU NVIDIA GeForce RTX 4070 Ti
System type	64-bit operating system, x64-based processor

**Comment by Megamouse** [comment]
I'm really sorry, but it's not our job to implement or fix either windows' or nefarius' drivers.

**Comment by SiriusVI87** [comment]
I know this is not strictly speaking a RPCS3 issue. However, I thought someone would be able to give me some kind of direction of what I could try to solve the issue. I cannot post anything on nefarius' Github page. And the guy in the other thread had the same exact problem on Linux, so it's not a windows related issue, either.

I have 4 original DS3 controllers. Three of them have the G axis problem in RPCS3 and one of them works. I've exhausted all my (limited) knowlege and just don't know what to try next.

Can you point me to another place where I could ask someoe about this issue?

**Comment by Megamouse** [comment]
I'm pretty sure nefarius is in our discord server. So maybe you can try get in contact  there.

**Comment by SiriusVI87** [comment]
That's a good idea. I will post the issue there and see what happens. thx!
