### ISSUE TITLE
Bioshock Infinite VM: Access violation writing location 0x3 (unmapped memory)

### ISSUE THREAD

**Issue by lambos11** [RPCS3/rpcs3#15122]
### Quick summary

Game opens and immediately freezes at logo on macos, there is a closed discussion about it here #13011 and apparently a fix here #13115 but on macos the problem seems to still exists, perhaps i am missing something, pls help 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14088292/RPCS3.log)

### Attach capture files for visual issues

![Screenshot 2024-01-29 at 15 44 13](https://github.com/RPCS3/rpcs3/assets/154713112/6a5b1bbb-06fb-4374-91c2-70a5445b51e3)

### System configuration

Macbook m1 air 2020
Sonoma 14.2.1

**Comment by AniLeo** [comment]
macOS 14.2 is not supported.
