### ISSUE TITLE
Build Dynamic Recompiler ( Dynarec JIT ) for PPU similarly PPSSPP , PCSX2 , Dolphin

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1513]
Because using LLVM to compile is inaccurate and incompatibility than using JIT , using Dynarec is more accurate and compatibility more CPU instruction

**Comment by tambry** [comment]
LLVM is a dynamic recompiler. We're not focusin on speed yet, that will probably come in a few years, if even then.
