### ISSUE TITLE
Sly Cooper: Thieves in Time - 60 FPS cap does not fix flickering lights, dropped inputs, or infinite loading screens

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#15144]
### Quick summary

The compatibility page recommends setting framrate limiter to 60 FPS to avoid several issues, such as flickering lights, dropped inputs, and infinite loading screens, however this has never fixed the issue.

### Details

The compatibility page recommends setting framrate limiter to 60 FPS to avoid several issues, such as flickering lights, dropped inputs, and infinite loading screens, however this has never fixed the issue.  This has been an issue starting all the way back when the game entered the Playable category and is still ongoing.  My settings are 1:1 what the compatibility page says yet I constantly get infinite loading screens, the game constantly has issues with inputs, and lights constantly flicker.  I've also tried other framerate options such as Auto, PS3 Native, and even 30 FPS, yet none of them have ever fixed any of these issues.  Just to be sure, I did a fresh dump from my disc copy, and the issues do persist.  Framerate really doesn't seem the be the cause and these issues never happen on real hardware.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14154192/RPCS3.log.gz)

### System configuration

Windows 10 Pro x64 Build 19045.3803

Intel Core i9-10900K

NVIDIA RTX 2080 SUPER

64 GB DDR4 Memory

Samsung EVO 2 TB SSD

**Comment by SlyCooperReloadCoded** [comment]
10 minutes of play later with the same settings, and I got another infinite loading screen, which means another log to look at:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14154254/RPCS3.log.gz)

**Comment by Asinin3** [comment]
If the wiki is wrong... simply edit it? The wiki is written by random people in the community, and shouldn't be taken as always being accurate.

**Comment by SlyCooperReloadCoded** [comment]
The problem isn't that those settings don't fix the issues, but rather that no settings fix these issues.  I'll get infinite loading screens and dropped inputs regardless of settings, that's why I opened this.  I believe these settings should the fix these issues for me, but aren't.  I should've been more clear in my post.

**Comment by Jonathan44062** [comment]
Your dump is broken according to your log, redump it

**Comment by SlyCooperReloadCoded** [comment]
Huh, that's odd.  I just redumped it from disc today.  How is it broken?  I'll redump it a second time.  I deleted PKGDIR if that's what you see, that just contains the digital instruction manual application that installs to the XMB seperately from the game.  Other than that it should've been fine.

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed
