### ISSUE TITLE
[Feature request] PlayStation Plus Support 

### ISSUE THREAD

**Issue by 19Aidan** [RPCS3/rpcs3#15149]
### Quick summary

Why would I want this? well. Playstation Home has exclusive PlayStation Plus perks. this can be considered useful for both Destination Home and Home Headquarters if this feature and if not a feature hopefully a patch so theses perks can be used at anytime for free. https://www.youtube.com/watch?v=GnQKenPtqN0

**Comment by Splicewave** [comment]
I just tested this in the new update. The PS Plus features are not working. 
![image](https://github.com/RPCS3/rpcs3/assets/71703832/8a7fc4e4-d208-482f-a3ec-778f3866b254)

**Comment by RipleyTom** [comment]
Reopening until we figure it out.
