### ISSUE TITLE
“Stranglehold” issues…

### ISSUE THREAD

**Issue by TryingToLove** [RPCS3/rpcs3#15145]
### Quick summary

Stranglehold has severe frame rate/slowdowns throughout, especially during gunplay sequences. Sound is distorted during these sequences also. 

Game has no reported issues in its Wiki.

Playing via RPCS3 on Steam Deck

### Attach a log file

N/A

### Attach capture files for visual issues

N/A

### System configuration

N/A

**Comment by RipleyTom** [comment]
Steam deck does not meet the recommended settings for rpcs3 and thus things like slowdowns are expected in demanding playable games. Not an issue.

**Comment by TryingToLove** [comment]
Thank you for the response. Just FYI, have played dozens of very demanding RPCS3 titles like “Shadows of the Damned” on my Steam Deck, with virtually no slowdowns at all. This is the first title that’s deemed “playable” that’s given me any issues with frame rate on Steam Deck.David M.Sent from my iPhoneOn Feb 3, 2024, at 7:29 PM, RipleyTom ***@***.***> wrote:﻿
Steam deck does not meet the recommended settings for rpcs3 and thus things like slowdowns are expected in demanding playable games. Not an issue.
