### ISSUE TITLE
Trinity Universe [BLES00971] Fail's to build SPU Cache

### ISSUE THREAD

**Issue by benbassist** [RPCS3/rpcs3#15151]
### Quick summary

Won't launch Fail's to build SPU Cache

### Details

When I try and launch Trinity Universe on my M1 Mac Latest RPCS3 build. 

It gets stuck on 361 of 362 building SPU Cache.

I get the following error message from the log.
E SYS: 'cellNetCtlGetInfo' failed with 0x80130101 : CELL_NET_CTL_ERROR_NOT_INITIALIZED [1]

### Attach a log file

- SYS: RPCS3 v0.0.30-16054-dda0b8af Alpha | HEAD
- SYS: VirtualApple @ 2.50GHz | 8 Threads | 16.00 GiB RAM | TSC: 1.000GHz
- SYS: Operating system: macOS, Version: 14.4.0
- SYS: Current Time: 2024-02-04T14:26:09
- RSX: Found Vulkan-compatible GPU: 'Apple M1' running on driver 0.2.991
- SYS: Firmware version: 4.90
S UPDATER: RPCS3 is up to date!
S PPU: Found SPURS GUID Pattern at 0x498480
S PPU: Found SPURS GUID Pattern for terminator at 0x498e10
S PPU: Found valid roaming SPU code at 0x498480..0x498e10 (guessed_ls_addr=0x0)
S PPU: Enabled: Non-Java Mode Fixup
E PPU: Can't build instruction VSL
E PPU: Can't build instruction VSR
- RSX: Found Vulkan-compatible GPU: 'Apple M1' running on driver 0.2.991
E RSX: Your GPU driver does not support some required MSAA features. MSAA will be disabled.
E RSX: Your GPU does not support double precision floats in shaders. Graphics may not render correctly.
E RSX: Your GPU does not support depth bounds testing. Graphics may not render correctly.
E RSX: Your GPU does not support wide lines. Graphics may not render correctly.
E RSX: Your GPU does not support framebuffer logical operations. Graphics may not render correctly.
E RSX: Apple GPUs are incompatible with the current implementation of asynchronous texture decoding.
E Input: FindKeyCode for [name = IR Nose] returned with [def_code = 0] for [def = ]
E Input: FindKeyCode for [name = IR Tail] returned with [def_code = 0] for [def = ]
E Input: FindKeyCode for [name = IR Left] returned with [def_code = 0] for [def = ]
E Input: FindKeyCode for [name = IR Right] returned with [def_code = 0] for [def = ]
E Input: FindKeyCode for [name = Tilt Left] returned with [def_code = 0] for [def = ]
E Input: FindKeyCode for [name = Tilt Right] returned with [def_code = 0] for [def = ]
S Input: The pad mode was changed to Single-threaded
S GUI: Boot successful.
S PPU: LLVM: Loaded module v6-kusa-3Q7wxsis4UMi14FHKixp8G-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-SGXN3k2tHXg4ikw3tiHHvH-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-P815XUP5XWkXiqMhj2znaH-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-Q9tf8iyHWpqA7AthmL2T82-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-3qtZRiisQn0RkKo2yEEkAX-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-hC4PspHdYCuPGdtwFLJjYs-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-PVVQaa3vg4VF9xpxn7rGPQ-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-MqaySKYymvFb1RqQWZcfWZ-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-VkzbEA9xVReqmeTFR7fFud-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-FELZm5y6EzwFvju9Qo4pb6-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-6Kr9q2tetCyfgi7s3j78Zz-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-M8PG7JQcCAQez0gJJnwJ4a-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-c2iYamrWp8Ek34o4ii9QmE-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-ScMnozmo6epLmTA09jXKwh-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-ZeKyx65ggWe6rrYKTtsm7W-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-8rodCUYJCoC46QmTevPPL7-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-W9yfA4m531g71R5764uLTE-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-0uLS0LcfSYgCTZG2zcCkVb-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-S46Cmx9EkRCH1oaY4XdgrJ-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-2QRzjeVQn3QdL74LV7RERW-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-iG9yL9LSQ6EmLvVyxLPRQx-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-LCTNMLSV0547nkyVgjmuzC-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-gseX2Wozv2xg50yy0qQhQV-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-F2zKkH5baZ5Xff3rd0QhxQ-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-idw3u1j2JNPHakK4CNz9CA-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-KsMPu1kZasL1PdqYyMZPoP-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-FgUXESUKbmA1T23TzJa6vL-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-NZTjm6A7mrXnVgHFKVaWyz-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-5VhzoY6z5Y42phq67iwvKq-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-2auQ3G892j4jaQw2SQz3x1-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-7WCZWsMaCMwTKRq9vwxJfG-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-MzZSEXxFkEsb268bZfSHFQ-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-nYmU5qsPAsC48yUu80hsop-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-pgTb4sh4Mu33c6ojYNRG9S-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-kYcX6o6NmAqK6AGvePSJb6-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-9FgUHKyaSdG09u5tFn5S0z-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-4PwZSELCkKNSHT4Rco7WAb-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-r1pizjJzRCwKa3FFKzuRKY-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-MCuaTtVTCXS0oWGi3rXF1b-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-eqGsKRFd6JgNtzN2F1PnrT-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-by10woibwTjc4NRJ9cv7RZ-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-QKACXdmnmUZqCcid0oLSFW-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-NCumiiinNJwHLVFv5GCFSX-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-EzYoV7ibN3u8mcHkp1HwuY-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-F4Gqwqz03CHWysPaK2KpvX-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-UAxtfWCozPHiv30yoG2Ucd-00001G-westmere.obj
S SPU: SPU Runtime: Built the interpreter.
E SPU: Trampoline simplified at ??? (level=1)
S SPU: SPU Runtime: Built 362 functions.
U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0010c90)
S PPU: LLVM: Loaded module v6-kusa-7LHmPKQURuTbHwAhSpWFH6-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0010a00)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0010a00, a3=0x0)
S PPU: LLVM: Loaded module v6-kusa-XCgQWMc1s99n1WTwrpWvw4-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S PPU: Found SPURS GUID Pattern at 0x12a1380
S PPU: Found SPURS GUID Pattern for terminator at 0x12a3580
S PPU: Found valid roaming SPU code at 0x12a1380..0x12a3580 (guessed_ls_addr=0x0)
S PPU: Found SPURS GUID Pattern at 0x12a5400
S PPU: Found SPURS GUID Pattern for terminator at 0x12a5a80
S PPU: Found valid roaming SPU code at 0x12a5400..0x12a5a80 (guessed_ls_addr=0x0)
S PPU: Found SPURS GUID Pattern at 0x12a5a80
S PPU: Found SPURS GUID Pattern for terminator at 0x12a6200
S PPU: Found valid roaming SPU code at 0x12a5a80..0x12a6200 (guessed_ls_addr=0x0)
S PPU: Found SPURS GUID Pattern at 0x12a6200
S PPU: Found SPURS GUID Pattern for terminator at 0x12aa080
S PPU: Found valid roaming SPU code at 0x12a6200..0x12aa080 (guessed_ls_addr=0x0)
S PPU: Found SPURS GUID Pattern at 0x12aa080
S PPU: Found valid roaming SPU code at 0x12aa080..0x12ade00 (guessed_ls_addr=0x0)
S PPU: LLVM: Loaded module v6-kusa-1Au1tg93M0j9aPxhbpVJAC-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-5MR5UPWcNoRKHsUNJqHbKV-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0010da0)
S PPU: LLVM: Loaded module v6-kusa-GidnR56pzgun0Z5aqipN0L-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libusbd.sprx” (id=0x23002b00)
S PPU: LLVM: Loaded module v6-kusa-t1xTtC1PVoW6Jh636RxJVQ-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-2wS6UCQGvL8KpqZwEg6HX7-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libnet.sprx” (id=0x23002d00)
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/app_home/sampleArg.txt” [1]
S PPU: LLVM: Loaded module v6-kusa-e6Ztz5quEuXfyACR7GqJvc-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libresc.sprx” (id=0x23003200)
S PPU: LLVM: Loaded module v6-kusa-fLV79QqHgPi90UziTsWrHo-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23003300)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E SYS: 'cellNetCtlGetInfo' failed with 0x80130101 : CELL_NET_CTL_ERROR_NOT_INITIALIZED [1]
S PPU: LLVM: Loaded module v6-kusa-VZ8vHUnQEv336P5APhX7dn-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfont.sprx” (id=0x23008900)
S PPU: LLVM: Loaded module v6-kusa-dyjKJgH39QG5UT98tYnhxc-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-N27aiXWLsymm1Fhh3VNaPp-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-Kxat5e8jWQxkXsN3yKwQgP-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-9dTZYHk2pAmCzmkcGWK1fq-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfreetype.sprx” (id=0x23008a00)
S PPU: LLVM: Loaded module v6-kusa-NLUqWhCCTzbkfiPfWTp1J1-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfontFT.sprx” (id=0x23008b00)
E SYS: 'cellNetCtlGetInfo' failed with 0x80130101 : CELL_NET_CTL_ERROR_NOT_INITIALIZED [2]
S cellSysutil: Mounted existing cache at /Users/---/Library/Application Support/rpcs3/dev_hdd1//caches/BLES00971_BLES00971/

### System configuration

Mac M1

**Comment by RipleyTom** [comment]
There is extensive explanations on how to provide the log file when you click to make a bug report.

**Comment by benbassist** [comment]
Sorry for not providing the log file In the correct manner. I will try again at a later date.
