### ISSUE TITLE
God of War - Ascension USA freeze after logo santa monica

### ISSUE THREAD

**Issue by bullghost** [RPCS3/rpcs3#15150]
### Quick summary
God of War - Ascension  BCUS98232
freeze after logo santa monica with or without patch skip intro

### Details

freeze after logo santa monica with or without patch skip intro
runing on Archlinux chimeraOS
i can play without issue with other games like uncharted 1, ninja gaiden sigma 2, RDR
hardware 
GPU Ryzen 780U
memory 16 GB share 8/8

### Attach a log file

here is log file 
[error-gow-asc.log](https://github.com/RPCS3/rpcs3/files/14157090/error-gow-asc.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14157092/RPCS3.log)

**Comment by AniLeo** [comment]
Known issue, you're not using the required settings listed on the game's wiki page.

**Comment by GuilhermeRaposo** [comment]
> Known issue, you're not using the required settings listed on the game's wiki page.

I'm facing the same exact issue using the required settings and up to date version.
