### ISSUE TITLE
Doesn't see Dualsense controller via bluetooth

### ISSUE THREAD

**Issue by O-DESTAN-O** [RPCS3/rpcs3#15154]
### Quick summary

Doesn't see Dualsense controller via bluetooth. It detects via cable but not via bluetooth.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14158485/RPCS3.log)

**Comment by AniLeo** [comment]
Closing due to zero effort to provide details, either way it's not an RPCS3 issue
