### ISSUE TITLE
gl: Outrun online displays black geometry

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#1515]
Outrun online arcade displays geometry as black under openGL. When debugging, its clear that the cars and environments are properly rendered, but some post-processing step causes the black output. Object outlines are still visible.

![outrun_ingame](https://cloud.githubusercontent.com/assets/15904127/13279905/d36b24da-daeb-11e5-924c-accd106603e8.PNG)

**Comment by raven02** [comment]
Similar issue happened in other games as well like Dragon Ball Z Burst limit

**Comment by kd-11** [comment]
I'll need testers to identify more games where this happens. It should be helpful especially if it happens during light scenes without alot of geometry. Debugging outrun online crashes amd gpu perfstudio that i use to debug frames, so i cant tackle this just yet. I've reported the issue to AMD and they are working on it.

**Comment by vlj** [comment]
You can use "capture frame" and then look command draw call in rsx debugger with dx12 to see what is happening too and compare with gl. 

The capture frame button can be hidden if rpcs3 Windows is not big enough BTW.

**Comment by MyaniPT** [comment]
@kd-11 I think Scarygirl [NPUB30699] produces similar outputs, if not the same.
I've made a video: http://www.youtube.com/watch?v=pmf8_QQ5aVE

**Comment by kd-11** [comment]
Issue is because of invalid surface usage. Should be fixed by PR https://github.com/RPCS3/rpcs3/pull/1530. After almost re-inventing the wheel writing a proper fbo surface cache, I realized vlj had already done it before, and it worked properly.

![outrun-ogl-fixed](https://cloud.githubusercontent.com/assets/15904127/13467508/949deaf2-e0af-11e5-9c7e-dcdb759f04e7.PNG)

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/1530 was merged which should resolve this issue. @raven02 could you check dragon ballz?

**Comment by SakataGintokiYT** [comment]
@kd-11 
Dragon Ball Z: Burst Limit // Outrun [ Black textures on Nvidia Gpu -- fixed by commit #1540]
<img src="http://www.fotoszok.pl/upload/cf8ee0e6.jpg" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">
<img src="http://www.fotoszok.pl/upload/330b8406.jpg" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">

**Comment by tambry** [comment]
Still an issue?

**Comment by SakataGintokiYT** [comment]
Fixed issue
