### ISSUE TITLE
[Feature request] Two LightGun in windows - cellGem.cpp add-in : rawinput.cpp

### ISSUE THREAD

**Issue by Monky-Power** [RPCS3/rpcs3#15158]
### Quick summary

I saw an advance on CellGem.cpp (Thanks Megamouse) allowing you to map the input of a controller as a reference for a PlayStation Move.
An option in the controllers could be rawinput type management.
This would allow you to manage 2 mice (AIMTRACK, SINDEN LIGHTGUN...) towards an emulation of the PlayStation Move

### Details

The Linux version of RPCS3 uses the "LIBEVDEV" library to manage 2 guns.
For Windows, the Raw Input equivalent could be used...
This was done in the Flycast emulator to simulate two guns
Here are the accessible sources allowing you to know which library was used
https://github.com/flyinghead/flycast/blob/master/core/windows/rawinput.cpp

I remain available to carry out the research or additional information necessary so that the request is as clear as possible

Thank you for your time

**Comment by Megamouse** [comment]
Yes, I can certainly try. It doesn't look too complicated.

**Comment by Monky-Power** [comment]
Thanks a lot.
You were very fast.

If I understand, at this moment this update is not yet distributed,
(I see the modifications in the ticket but not yet in the main branch).

To test once updated, simply choose "raw mouse" in the new options.

In : rpcs3/Input/raw_mouse_config.h
I'm not sure I understood this line (24) :
	players.at(i) = std::make_shared<raw_mouse_config>(this, fmt::format("Player %d", i + 1));

The configuration of the keys is carried out directly from the controller interfaces ?

I will test as soon as the update is available and I will give you user feedback.


TODO 3 : Configurable mice for each index :
And for your part you are looking to improve to choose which "raw mouse" would go on which index : 
 I confirm that this option will be useful (even if I am already in a hurry to test), example, player 1 red and the index 1 by default would be the blue gun

**Comment by Megamouse** [comment]
It automatically uses the first index for the first ps move and so on.
The TODO is more like: which raw mouse device shall go to which player/move index.
Currently, if you have 3 mice in your system, it will just take them in the order they come.

**Comment by Megamouse** [comment]
So it's probably best to test right now if you detach your normal mouse and boot the game with a shortcut for example via terminal

**Comment by Megamouse** [comment]
I only tested if the events reach the handler with my normal mouse.
But not the ps move stuff.

**Comment by Megamouse** [comment]
Obviously the driver you use for the guns should send absolute mouse position events. But assuming you are using the same driver in flycast this should just work as is.

**Comment by Monky-Power** [comment]
Thank you for all the details.

- 1) Config RPCS3 in "raw input"
- 2) STOP RPCS3
- 3) Remove my standard mouse
- 4) Start Game
- 5) Test a game where the calibration part is simple

In my case the test will validate the operation with 2 AIMTRACK.
After verification it will not be hard to find volunteers with other types of guns.

I won't have long to wait to test, the commit to RPCS3:master is in progress
