### ISSUE TITLE
[Regression] Kingdom hearts 1.5 & 2.5 Remix black screen on boot (#15139)

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#15163]
### Quick summary

Both Kingdom Hearts games that use launchers do not like these recent crypto changes as they present a black screen before showing any intro videos. It just says configuring trophy data then black screen.

### Details

Other games that use launchers like Devil May Cry HD Collection are still working.
The regression appears to be just both the Kingdom Hearts games as currently observed.

### Build with regression

RPCS3 v0.0.30-16060-40c51a1f

### Attach two log files

[Working.log](https://github.com/RPCS3/rpcs3/files/14182863/RPCS3.log)
[Broken.log](https://github.com/RPCS3/rpcs3/files/14182891/RPCS3.log)

### System configuration

WIndows 11
Ryzen 5 3600
Gtx 1660 Super

### Other details

I found this issue while testing what some people on the discord were discussing.
Confirmed that it wasn't just my PC experiencing this and confirmed fix for the others as well by using the older build before regression.

**Comment by elad335** [comment]
Test with #15138

**Comment by Darkhost1999** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14272795/RPCS3.log)
No change

**Comment by Darkhost1999** [comment]
Confirming fix
![Screenshot 2024-02-14 072634](https://github.com/RPCS3/rpcs3/assets/60384196/810fe81d-ac72-4038-9c95-84499ff20fe9)
![Screenshot 2024-02-14 072737](https://github.com/RPCS3/rpcs3/assets/60384196/9e7c7960-aae0-4ff1-9da7-46dab92c7628)
Nice work
