### ISSUE TITLE
Instruments do not pass button presses to Native Interface

### ISSUE THREAD

**Issue by carlmylo** [RPCS3/rpcs3#15164]
### Quick summary

Anything that's not a "standard controller" has issues passing button presses when RPCS3's Native Interface is up. 

### Details

When the player brings up UI that requires the Native Interface, any button presses on "non-standard" controllers will simply not work. If the player does not have an alternative input method that works, they will be soft locked.

I have personally tested:
* MIDI to USB Rock Band 3 Mustang Guitar (Emulated MIDI Device)
* USB MIDI Keyboard (Emulated MIDI Device) [not logged]
* Rock Band 3 Keyboard (Zadig/USB Passthrough)

Other users in Milohax report this issue now and then. I will forward any messages from them here.

Current workaround is to disable the Native Interface for those that don't have an alternative input method set up.

PS3 hardware does not have this issue.

### Attach a log file

[Mustang - RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14187493/Mustang.-.RPCS3.log.gz)
[RB3 Keyboard Passthrough - RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14187494/RB3.Keyboard.Passthrough.-.RPCS3.log.gz)

### System configuration

Tested on a couple of Windows machines.

### Other details

Example of this happening on a Rock Band 3 Mustang Guitar connected via MIDI to USB and set up through the Emulated MIDI Device section in I/O.
https://youtu.be/x3bIaiRE7fY

**Comment by Megamouse** [comment]
I don't really understand how you're supposed to control a UI with an instrument.
What do you do on a PS3 with your instrument in these cases?

**Comment by LinosM** [comment]
The actual ps3 buttons on them
![image](https://i.imgur.com/anevfPC.png)

**Comment by carlmylo** [comment]
The guitar in the video also has PS3 buttons. I've heard similarly that some instruments mapped through MMJoystick have issues interacting with the Native Interface enabled but I haven't been able to replicate it so will ask around for anyone else with this issue.
![image](https://github.com/RPCS3/rpcs3/assets/56451149/ab0f2575-3b48-491a-b6db-af4eacb2046c)

**Comment by DarkRTA** [comment]
The instruments themselves also show up as HID devices to the PS3 rather than an actual midi instrument.

**Comment by Megamouse** [comment]
Please try with https://github.com/RPCS3/rpcs3/pull/15180

And also try to open the home menu with the ps button on the instrument.

**Comment by carlmylo** [comment]
This was marked as closed but the problem persists on USB Passthrough instruments.

**Comment by Megamouse** [comment]
Does it work on PS3?
The game is supposed to call cellPadLddDataInsert, which it doesn't.

**Comment by Megamouse** [comment]
it's set to trace. Can you put it to notice and create a new log?

**Comment by carlmylo** [comment]
Would this be on the right click menu for RPCS3's log or somewhere else?
Also could this be caused by emulation pausing when the RPCN friend list menu is up?

**Comment by Megamouse** [comment]
I think you have to manually edit the config.yml and set
Log: {}
to
Log: {cellPad: Trace}

**Comment by carlmylo** [comment]
Hopefully I did it right.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15443846/RPCS3.log.gz)

**Comment by Megamouse** [comment]
ah... it's
Log: {sys_io: Trace}

**Comment by carlmylo** [comment]
Here it is.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15443936/RPCS3.log.gz)

**Comment by Megamouse** [comment]
I added some more logging to this one:
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/15444094/rpcs3.zip)

**Comment by carlmylo** [comment]
Getting this error on starting that RPCS3 exe.
---------------------------
rpcs3.exe - Entry Point Not Found
---------------------------
The procedure entry point ?fromString@QDateTime@@SA?AV1@AEBVQString@@0H@Z could not be located in the dynamic link library C:\Games\RPCS3\rpcs3.exe. 
---------------------------
OK   
---------------------------

![image](https://github.com/RPCS3/rpcs3/assets/56451149/c5430c5e-13e5-4e77-b013-ac12745c3a1d)

**Comment by Megamouse** [comment]
uhm, right, I'm already on a newer Qt version.
You could try with the dlls and qt6 folder from #15473.

**Comment by carlmylo** [comment]
Here it is.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15444208/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Based on the log, it seems to call cellPadLddDataInsert periodically, but doesn't set the length field, so it never really sets any data.
Also, it doesn't seem to do anything while the dialog is open.
I've made another one that logs the buttons even if the length is 0.
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/15444267/rpcs3.zip)

**Comment by carlmylo** [comment]
New log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15444301/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Did you press up/down/cross on the guitar a couple of times?

**Comment by Megamouse** [comment]
I've changed a couple of things.
I doubt that the friend list works, but maybe the home menu does now.

[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/15444440/rpcs3.zip)

**Comment by carlmylo** [comment]
> Did you press up/down/cross on the guitar a couple of times?

Yep!
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15444460/RPCS3.log.gz)

Just as you said, home menu and interacting with it works. When the menu is pulled up, the emulation persists in the background like on real hardware. The RPCN friend menu seems to pause emulation entirely while it's up and it does not respond until dismissed by using an alternative input method (like a keyboard) is used. On hardware, the game behaves like how the Home Menu behaves at the moment.

**Comment by Megamouse** [comment]
Maybe open a separate issue with this specific dialog in this game.
I think we've proven that it works for all other dialogs.
I'll open a PR with the home menu changes for this one.
