### ISSUE TITLE
Tokyo Jungle - Crashes asking you the Rap File when you update it

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#15177]
### Quick summary

The copy Best of Playstation Network Vol. 1 includes 4 games, Tokyo Jungle boots normally in the game base (1.00), but, if you're trying to update it, it crashes

### Details

Like this
![image](https://github.com/RPCS3/rpcs3/assets/78843189/f42f9aa7-3200-4240-b5cc-ce789fa8b72d)

### Attach a log file

Works
[Tokyo Jungle Works.log.gz](https://github.com/RPCS3/rpcs3/files/14227768/Tokyo.Jungle.Works.log.gz)
Broken
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14227769/RPCS3.log)

**Comment by Jonathan44062** [comment]
Closing this, since you need the Update DRM to make it work

**Comment by Darkhost1999** [comment]
https://github.com/AphelionWasTaken/PySN/issues/11
There were some games released on discs that came with DRM free updates
NPUA80523 Tokyo Jungle is on that list of drm free updates
http://ps3.aldostools.org/updates.html
