### ISSUE TITLE
[Regression] NPEA00324 LittleBigPlanet 2, Gas doesn't disappear (#13897)

### ISSUE THREAD

**Issue by Didtruo** [RPCS3/rpcs3#15178]
### Quick summary

In the level Brainy Cakes *Second area, victoria's labolatory*, Gas that should dissapear no longer dissapears 
* i came back after a year to replay this game so i reinstalled rpcs3 and updated to the newest version, i as well updated the game to the newest version which is 01.33 *
RPCS3 version that is present for now: 0.0.30-16067-9b387485 Alpha
EDIT: ISSUE DOESNT EXIST ON VERSION 0.0.29-15617-c7c81ed9 Alpha, i knew it wasnt in older ones !
still to play using Lnfinite and online levels i need newer rpcs3 version.

I don't remember if i was having this issue year ago but i completed the game in 2023 flawlessly.
My settings are default with enabled Write Color Buffer, VSync in GPU section and Read Color Buffers in advanced, issue still appears with these turned off.

### Details

This is how it should be
![image](https://github.com/RPCS3/rpcs3/assets/146891537/31ef0765-0257-4a99-9a2c-419ef59286cc)
And this is how it is in RPCS3
![image](https://github.com/RPCS3/rpcs3/assets/146891537/ed1977b4-8993-46cf-8b5f-e96b92685d2b)

because the gas doesnt dissapear i cant pass the level which makes the game unbeatable by normal way.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14229275/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14229276/RPCS3.log)

### System configuration

Windows 11
CPU: Ryzen 7 5800x
GPU: Geforce RTX 3060 12 gb vram
GPU Driver Version: 551.23

**Comment by Didtruo** [comment]
Edit: Game doesnt even launch now thanks to new update 
RPCS3 0.0.30-16074-4746ef09 Alpha

**Comment by uhwot** [comment]
I tested some RPCS3 versions and found out that this is a regression from version v0.0.30-16063-65d93c97 (PR #13897).

Here are some logs :3

Regression (v0.0.30-16063-65d93c97):
[RPCS3.regression.log](https://github.com/RPCS3/rpcs3/files/14234408/RPCS3.regression.log)
Working (v0.0.30-16061-85f4c38b):
[RPCS3.working.log](https://github.com/RPCS3/rpcs3/files/14234410/RPCS3.working.log)

**Comment by AniLeo** [comment]
Use Accurate XFloat

**Comment by uhwot** [comment]
@AniLeo Using Accurate XFloat causes other physics issues which don't happen on Approximate (like stiff springs not working properly), so the same level is still unbeatable

**Comment by RipleyTom** [comment]
Is it still an issue?

**Comment by uhwot** [comment]
@RipleyTom I just checked on latest (v0.0.30-16110-e3d4c067), yeah this is still an issue

**Comment by atmospho** [comment]
So we're just unable to play this level until it's resolved? I ran into a similar issue in LBP 1

**Comment by BillQuain** [comment]
I did a little testing of that level as I am having the same problem. And what I found out after looking at old footage of the game and what was happening in my emulated game is that none of the gas effects in the level are working correctly, (score bubbles, gas vents on the train at the start of the level) also the monsters explode in a much more violent fashion compared to ps3 footage.  I don't know what setting would effect this.

**Comment by Adeladen** [comment]
Tried with every XFloat setting, none of them fix it. Is there a way to cheat past that segment or is the only option to wait until it's fixed?

**Comment by Pixel3000nerd** [comment]
@Adeladen As far as I know there's no way to cheat past the segment. Have to either wait until is fixed, or downgrade RPCS3 to the last working version (v0.0.30-16061-85f4c38b as reported by @uhwot )

**Comment by uhwot** [comment]
Still an issue on 0.0.31-16215-3393d13b

**Comment by GalaxyGaming2000** [comment]
> Still an issue on 0.0.31-16215-3393d13b

for now just downgrade to rpcs3 v0.0.30-16060 for this level only

**Comment by lectrichair** [comment]
> @Adeladen As far as I know there's no way to cheat past the segment. Have to either wait until is fixed, or downgrade RPCS3 to the last working version (v0.0.30-16061-85f4c38b as reported by @uhwot )


yeah this worked for me, the guide to using older versions didnt work though i had to copy my new version files into the older version's folder and it saved my progress then and worked through the entire game in old build

**Comment by AniLeo** [comment]
Still an issue

**Comment by RipleyTom** [comment]
Please provide a savefile.

**Comment by uhwot** [comment]
@RipleyTom 
[BCUS98245PROFILE4F050660.zip](https://github.com/RPCS3/rpcs3/files/15140604/BCUS98245PROFILE4F050660.zip)
Import this from pause menu > Settings > Profile > Import profile

**Comment by AniLeo** [comment]
Needs retesting with #15523 to see if the behaviour changed

**Comment by ItsLaguna** [comment]
Issue is still present
