### ISSUE TITLE
[Regression] RPCS3 now failing to build in linux

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#15187]
### Quick summary

RPCS3 fails to build on linux.

### Details

The following was discovered in the build log:

```
tutorial.3;libcurl-url.3;libcurl-ws.3;libcurl.3,PREPEND,/home/testing/Desktop/rpcs3/rpcs3/build/3rdparty/curl/curl/docs/libcurl/>

  Expression did not evaluate to a known generator expression

CMake Error:
  Error evaluating generator expression:

    $<LIST:TRANSFORM,CURLINFO_ACTIVESOCKET.3;CURLINFO_APPCONNECT_TIME.3;CURLINFO_APPCONNECT_TIME_T
```

### Build with regression

Could not bisect (see Other Details section below)

### Attach two log files

[build.log](https://github.com/RPCS3/rpcs3/files/14231141/build.log)

### System configuration

* OS: Linux Mint 21.3 / kernel 6.5
* CPU: Intel I7-10870h
* GPU: Nvidia GTX 3070 / driver 535.154
* gcc: 12.3.0
* CMake:  3.24.0

### Other details

This is a recent regression.  The last known good build was bb22afb7f121feed0aa913b2a9e578acb72fd184.  All attempts to bisect fail with: 

```
CMake Error at 3rdparty/libpng/CMakeLists.txt:11 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "png_static".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * 3rdparty/libpng/libpng/CMakeLists.txt:684 (target_link_libraries)
```

**Comment by RipleyTom** [comment]
Are you sure you updated your submodules?
git submodule sync && git submodule update --init

**Comment by RipleyTom** [comment]
Sorry meant for the error at the end.
For the curl error, try updating CMake.

**Comment by Shoegzer** [comment]
Thanks.  What's the minimum CMake?  I thought it was 3.16.9 as shown [here](https://github.com/RPCS3/rpcs3/blob/master/BUILDING.md).  Mine's at 3.24.0.

**Comment by RipleyTom** [comment]
No idea, I'm on 3.28.2 and I have no issue building on Linux.

**Comment by Shoegzer** [comment]
Fair enough, I updated to 3.28.3 and it builds for me too now, so I'll close this. Thanks for your help.

**Comment by RipleyTom** [comment]
Looked into it, curl forgot to update their minimum requirements in the version we have as a submodule, updated the BUILDING.md to reflect the change.

**Comment by Shoegzer** [comment]
Thanks, that should help others.  I did notice that at least [here](https://github.com/RPCS3/rpcs3/blob/master/BUILDING.md) it's still showing 3.16.9?
