### ISSUE TITLE
[Regression] Misoriented effects with Xfloat Approximate in Ratchet & Clank: Into the Nexus after #13897

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#15186]
### Quick summary

Some effects are on the wrong axis with Xfloat approximate only after #13897, Accrurate and Relaxed(for this at least) are still fine.

### Details

So far the only effects effected are the Nether/Prog blades spinning and the Jetpack exhaust:
![NPUA80908_screenshot_2024_02_10_17_05_20](https://github.com/RPCS3/rpcs3/assets/66685584/d78baf12-20e1-4390-a11c-8f1fc99d66a4)
![NPUA80908_screenshot_2024_02_10_16_54_28](https://github.com/RPCS3/rpcs3/assets/66685584/4027fa02-1e1e-4bb6-a394-9be4875ccea3)

### Build with regression

v0.0.30-16063

### Attach two log files

[RPCS3_ITN_misoriented_effects_before.log](https://github.com/RPCS3/rpcs3/files/14230961/RPCS3_ITN_misoriented_effects_before.log)
[RPCS3_ITN_misoriented_effects_after.log](https://github.com/RPCS3/rpcs3/files/14230963/RPCS3_ITN_misoriented_effects_after.log)

### System configuration

- SYS: RPCS3 v0.0.30-16074-4746ef09 Alpha | master
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2024-02-10T17:11:36
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 546.33.0.0
- SYS: Firmware version: 4.88

**Comment by AniLeo** [comment]
IMO this is not an issue since it works fine with Accurate, but adding @RipleyTom to decide

**Comment by RipleyTom** [comment]
I'll look into it, it's weird.

**Comment by RipleyTom** [comment]
Can you provide a save?

**Comment by JimScript** [comment]
Sure:
[NPUA80908_SAVE_0.zip](https://github.com/RPCS3/rpcs3/files/14238361/NPUA80908_SAVE_0.zip)
