### ISSUE TITLE
[Regression] Massive performance degradation (#15175)

### ISSUE THREAD

**Issue by Ninetime** [RPCS3/rpcs3#15193]
### Quick summary

After #15175 was applied FPS within Marvel vs Capcom 2 dropped from 60 FPS to 15-20 FPS.

### Details

After applying the update and starting MVC2, FPS immediately dropped from its original 60 FPS to 15-20 FPS.
The following did not resolve the isssue:
Removing custom config
Create custom config with default settings

Version 0.0.30-16083
![image](https://github.com/RPCS3/rpcs3/assets/6248582/6ee91550-de0f-42a5-aa55-cd3024e32c8b)

Version 0.0.30-16085
![image](https://github.com/RPCS3/rpcs3/assets/6248582/94971c53-d884-4d0c-83ca-0c1188c8cf73)

### Build with regression

v0.0.30-16085-148edc00

### Attach two log files

[RPCS3-16083.log](https://github.com/RPCS3/rpcs3/files/14233792/RPCS3-16083.log)
[RPCS3-16085.log](https://github.com/RPCS3/rpcs3/files/14233793/RPCS3-16085.log)

### System configuration

AMD Ryzen 7 5800X 8-Core Processor | 16 Threads | 31.93 GiB RAM | TSC: 3.800GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
GPU: 'AMD Radeon RX 6800 XT'

**Comment by AniLeo** [comment]
Not specific to one game, also found in Demon's Souls and MGS: PW, likely most games if not all
