### ISSUE TITLE
Ncaa 13 

### ISSUE THREAD

**Issue by rasaannn** [RPCS3/rpcs3#15202]
### Quick summary

when I play the gameplay is fine. However halfway through the game the screen crashes but the audio and game continues. 

### Details

here are my specs 

Processor 12th Gen Intel(R) Core(TM) i5-12500H   3.10 GHz
Installed RAM	8.00 GB (7.71 GB usable)
Device ID	7EE1BB17-7CB2-478C-B291-8A9DBB4D3792
System type	64-bit operating system, x64-based processor

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14261714/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Closing as this is not a support helpdesk, it's an issue tracker
