### ISSUE TITLE
RPCS3 0.0.30 Crashes when I try to install firmware or boot a game

### ISSUE THREAD

**Issue by Abzull** [RPCS3/rpcs3#15216]
### Quick summary

RPCS3 0.0.30 Crashes when I try to install firmware or boot a game

### Details

Hello everyone, I have this issue when I try to install the firmware, It appears the typical message that the firmware was installed and then the emulator crashes, I've been trying everything I see on internet since yesterday
I renamed the folder and sent it to D:\RPCS
I reinstalled from scratch
I installed an older version (Here the firmware installed on 0.0.22 but then when I tried o open a game like Demon's Souls or Dante's Inferno it crashes)
Also tried an older firmware, same issue
I downloaded the ROM from other side instead of the first option
I deactivated the Anti-Aliasing
Tried  SPU Decoder with ASMJIT instead of LLVM
I tried debug mode,
I ran the program as admin
I restarted the computer several times

And nothing seems to work, any idea of how to fix it?

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14311872/RPCS3.log)

### System configuration

OS: Windows 10 (Up to date)
CPU: Ryzen 7 4800H
GPU: RX5600M (Up to date)
RAM: 16 GB

**Comment by AniLeo** [comment]
Pirated game mentioned, invalid issue.
