### ISSUE TITLE
strings untranslatable

### ISSUE THREAD

**Issue by xujibbs** [RPCS3/rpcs3#15218]
### Quick summary

strings untranslatable

### Details

stings untranslatable
1. configuration-I/O-Emulated Midi device 1-string "None"
2. configuration-Pads-Devices-string "Default Null Device", "Keyboard", "DS3 Pad #",Etc.
3. configuration-configuration Files-string "Default"

### Attach a log file

N/A

**Comment by Megamouse** [comment]
I think I fixed most issues in #15224
The string for the "Default" config does not really make sense to tranlate, since it's literally the filename.
You'd end up having different files for different languages, which is kinda weird to be honest and also just overcomplicates the rest of the code.
