### ISSUE TITLE
Enter a title here

### ISSUE THREAD

**Issue by strodown** [RPCS3/rpcs3#15215]
### Quick summary

Some games don't launch anymore and block at the last element of the SPU blocks compilation.

### Details

Some games don't launch anymore and block at the last element of the SPU blocks compilation.

I build rpcs3 myself from a buildroot project: 'https://gitlab.com/pixl-os/pixl'.
I have the problem on the following games :
- Red Dead redemption (BLES01179 - BLES00680)
- In Famous 2 (BCUS98125 - BCES01143)

### Attach a log file

[Uploading Red.Dead.Red
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14311231/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14311232/RPCS3.log.gz)
[Red.Dead.Redemption.BLES01179.log.gz](https://github.com/RPCS3/rpcs3/files/14311241/Red.Dead.Redemption.BLES01179.log.gz)

### Attach capture files for visual issues

![screenshot-2024-02-16T10-47-32-112Z](https://github.com/RPCS3/rpcs3/assets/14039957/7a13dd33-8479-4845-86d8-1e1043180792)

### System configuration

Nvidia Getforce 1080
Ryzen 5 5600x
16Go ram

### Other details

build localy for project : https://gitlab.com/pixl-os/pixl/-/blob/add-rpcs3-emulator-ps3/package/rpcs3/rpcs3.mk?ref_type=heads

**Comment by AniLeo** [comment]
Cannot reproduce both on Linux and Windows. 

This ticket is invalid as it mentions a regression yet it doesn't follow the regression template.

Missing first build where the issue started, and log file from last good build and first bad build.

**Comment by RipleyTom** [comment]
Also local build, please try with the official build, if it's not present in the official build it's not a valid issue.

**Comment by MSuih** [comment]
I suspect it might be caused by the custom llvm version, you should try building rpcs3 with llvm from our submodule

**Comment by RipleyTom** [comment]
Assuming the issue was caused by the custom build since there was no further communication.
