### ISSUE TITLE
RPCS3 Disabling the “Screenshot Saved” overlay

### ISSUE THREAD

**Issue by nakiri-nekoman** [RPCS3/rpcs3#15223]
### Quick summary

Is there a way to disable the "Screenshot Saved" overlay display?
I'm asking for an option to disable this.

**Comment by RipleyTom** [comment]
Please at least justify why you want this.

**Comment by RipleyTom** [comment]
We don't really need an option for every single thing. If you can't justify why you want this I guess it is not that needed.
