### ISSUE TITLE
[Feature request] Is it possible to implement xbyak?

### ISSUE THREAD

**Issue by boludoz** [RPCS3/rpcs3#15229]
### Quick summary

I wonder if it would be possible to implement the following JIT assembler, xbyak, as it supports all types of instructions, including the most modern ones like AVX10, AVX512. It could really leverage the capabilities of the most modern processors. 

https://github.com/herumi/xbyak/tree/master

### Details

It’s used in other high-performance emulators like Yuzu with good results, and in fact, it has broken several performance records.

**Comment by RipleyTom** [comment]
LLVM automatically generates avx512 if your processor supports it.

**Comment by AniLeo** [comment]
What's the point of adding another JIT decoder when we're already using LLVM as the main decoder for both PPU and SPU? Sounds like a waste of time

**Comment by boludoz** [comment]
> What's the point of adding another JIT decoder when we're already using LLVM as the main decoder for both PPU and SPU? Sounds like a waste of time

Optimization

**Comment by boludoz** [comment]
> LLVM automatically generates avx512 if your processor supports it.

Sorry, I thought xbyak was the fastest JIT in the world.

**Comment by boludoz** [comment]
> What's the point of adding another JIT decoder when we're already using LLVM as the main decoder for both PPU and SPU? Sounds like a waste of time

https://github.com/PCSX2/pcsx2/tree/master/3rdparty/xbyak/xbyak 
I noticed that pcsx2 also uses xbyak
