### ISSUE TITLE
Ninja Gaiden Sigma 2 [BLUS30380] sometime crash at same place with error ·F 0:36:42.590618 {PPU[0x1005008] Thread () [HLE:0x02ce48f4, LR:0x008cb894]} SIG: Thread terminated due to fatal error: Segfault reading location 0000000000000000 at 00007f520ddbbbc0. Emu Thread Name: 'PPU[0x1005008]'

### ISSUE THREAD

**Issue by bullghost** [RPCS3/rpcs3#15221]
### Quick summary

Ninja Gaiden Sigma 2 [BLUS30380] sometime crash at same place either about to go load save and after finish the stage about to go to save screen

### Details

Ninja Gaiden Sigma 2 [BLUS30380] sometime crash at same place either about to go load save game and after finish the stage about to go to save screen, if i try to load the game and fight the boss its can pas finish the stage and show up save screen and continue normally

playing using same patch on windows and arch linux
item not decreasing
infinite magic
infinite blue orb

os arch linux steam deck 
on windows os on same device its work fine, i able to play the game until finish without any crash

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14323247/RPCS3.log.gz)

### System configuration

AMD Ryzen Z1 Extreme | 16 Threads | 11.38 GiB RAM | TSC: 3.294GHz | AVX-512+ | FMA3

**Comment by FlexBy420** [comment]
Issues with patches enabled are not valid

**Comment by elad335** [comment]
Someone broke the world record of issue title length.

**Comment by bullghost** [comment]
hi @Megamouse @elad335 , update  ..
rpcs3-v0.0.30-16055-26d406fe to rpcs3-v0.0.30-16162-df4fc947 still broken ,
and rpcs3-v0.0.31-16202-397c2698 was fix my issue, i can start the game , load, reload, go to main screen and load , without any issue.
thank you.
