### ISSUE TITLE
Shortcut issues macOS

### ISSUE THREAD

**Issue by Kurtjwest** [RPCS3/rpcs3#15228]
### Quick summary

When attempting to create shortcut on macOS sonoma 14.3.1, an error window appears stating "Failed to create shortcut(s)!"

An app is created in the rpcs3 folder of the user applications folder, but has no icon. It only runs if RPCS3 is not itself running. The shortcut.icns file in the resources folder of the app is completely empty.

Obviously this is not a pressing issue, but a fix would be greatly appreciated.

On a side note, I want to thank the developers. This project is absolutely amazing! Keep up the great work!

### Details

"E SYS: Failed to write icon file: /Users/kjw/Applications/RPCS3/Demon's Souls.app/Contents//Resources/shortcut.icns"

Maybe the double slash there is the issue

### Attach a log file

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/14361292/RPCS3.log.zip)

### System configuration

macOS sonoma 14.3.1
RPCS3 0.0.30-16122-7abc5f3e Alpha

**Comment by AniLeo** [comment]
macOS 14.2 is not supported as indicated on the requirements. The issue might remain on 14.3, but it needs to be retested there as it's the minimum supported version for Sonoma.

**Comment by MSuih** [comment]
A log file would tell how far it got into the shortcut creation process before that error popped up.

**Comment by Kurtjwest** [comment]
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/14361292/RPCS3.log.zip)

**Comment by Kurtjwest** [comment]
> A log file would tell how far it got into the shortcut creation process before that error popped up.



> [RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/14361292/RPCS3.log.zip)
> 
> Sorry for not including it earlier, was unaware the log captured info outside of gameplay. From what I can see it doesn't reveal much other than saying: "E SYS: Failed to write icon file: /Users/kjw/Applications/RPCS3/Demon's Souls.app/Contents//Resources/shortcut.icns"
> 
> Maybe the double slash there is the issue
> 
> Also, can confirm issue persists on macOS 14.3.1
