### ISSUE TITLE
Savestates are not being detected that are form a different rpcs3 

### ISSUE THREAD

**Issue by Wiredcheetah828** [RPCS3/rpcs3#15231]
### Quick summary

can not load a savestates form another rpcs3 app was on Linux Mint flatpack to a version of fedora using the flatpack

### Details

I'm on Nobara Linux using the flatpack
if it helps I'm trying to play demon's souls
it won't even open the file and it does show up in a filter list with only (Savestate files)

### Attach a log file

![Screenshot_20240222_131619](https://github.com/RPCS3/rpcs3/assets/121316075/19c7be70-8599-42bb-8c9e-f967b1dce0df)
![Screenshot_20240222_131720](https://github.com/RPCS3/rpcs3/assets/121316075/be3c9c80-f22b-427d-83f1-030ddf773bab)

**Comment by Megamouse** [comment]
flatpack is not supported
