### ISSUE TITLE
Keyboard mapping shown in Pad settings while controller is connected

### ISSUE THREAD

**Issue by mavethee** [RPCS3/rpcs3#15232]
### Quick summary

Despite connected controller it still shows keyboard mapping

### Details

Default settings in case of DualShock are mapped correctly, but still weird

![CleanShot 2024-02-22 at 19 43 04@2x](https://github.com/RPCS3/rpcs3/assets/47083527/a90b66b8-6733-4632-af89-ab6be9896856)

I think it should look like this, similar as e.g. PCSX2 shows controller button mapped by default.

![CleanShot 2024-02-22 at 19 48 04@2x](https://github.com/RPCS3/rpcs3/assets/47083527/0db4931a-d82c-44dd-b099-7cc8cf3fc53a)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14378167/RPCS3.log.gz)

### System configuration

- SYS: RPCS3 v0.0.30-16125-3acd442c Alpha | HEAD
- SYS: VirtualApple @ 2.50GHz | 8 Threads | 16.00 GiB RAM | TSC: 1.000GHz
- SYS: Operating system: macOS, Version: 14.3.1
- SYS: Current Time: 2024-02-22T19:50:41
- RSX: Found Vulkan-compatible GPU: 'Apple M1' running on driver 0.2.991
- SYS: Firmware version: 4.90

**Comment by Megamouse** [comment]
Reproduce it and then upload /rpcs3/input_configs/global/Default.yml

**Comment by mavethee** [comment]
> Reproduce it and then upload /rpcs3/input_configs/global/Default.yml

Removed and re-generated Default.yml a few times, can't reproduce it anymore, so far seems to be fixed, I guess my yml was broken?
![CleanShot 2024-02-22 at 20 33 39@2x](https://github.com/RPCS3/rpcs3/assets/47083527/549deb8f-97a3-422a-914e-a1e0528e9ebf)

**Comment by Megamouse** [comment]
It could also be some weird Qt signal/slot thing that happens on MacOs maybe if you're unlucky.

**Comment by Megamouse** [comment]
closing until it appears to be a pattern
