### ISSUE TITLE
Infamous 2

### ISSUE THREAD

**Issue by Tumatutuma** [RPCS3/rpcs3#15234]
### Quick summary

In-game image is covered with blue-colored artifacts as shown in the attacked screenshot.
Settings are default with minor changes made in accordance with recommendations on this page: https://wiki.rpcs3.net/index.php?title=InFamous_2.
![InfamousGlitch](https://github.com/RPCS3/rpcs3/assets/160958841/c5fb2a29-d8f6-417f-84d0-bfbd91dd36f0)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14379131/RPCS3.log.gz)

### System configuration

Windows 10 Pro 64-bit
12th Gen Intel(R) Core(TM) i5-12400F
GeForce RTX 3060 Ti (Game Ready Driver 551.61)
16 GB of RAM

### Other details

RPCS3 Version: 0.0.30-16132-3067c86d Alpha | master

**Comment by Megamouse** [comment]
Closing due to pirated content
