### ISSUE TITLE
[Feature request] Intel Graphic Support.

### ISSUE THREAD

**Issue by GAMEvs** [RPCS3/rpcs3#15238]
### Quick summary

INTEL GRAPHIC (ARC A... ) Support

### Details

There can play in some game by Use Intel graphics card.
I see a problem with in-game graphics on opengl setting have: glitch picture , broken color and lighting.
![p1](https://github.com/RPCS3/rpcs3/assets/89569919/5e6fd9dd-f18e-4d78-9f1f-d22bb9940b8e)
![p2](https://github.com/RPCS3/rpcs3/assets/89569919/09144b2f-bcf0-43ab-b2f5-c10f3c169588)
![p3](https://github.com/RPCS3/rpcs3/assets/89569919/8fdbdefe-5ec1-45bf-a327-b2e7ee735cf7)
with Vulkan setting
![p4](https://github.com/RPCS3/rpcs3/assets/89569919/7d55122b-8a3d-4f4f-b6b7-b2d4112fb4bb)

**Comment by FlexBy420** [comment]
It's not up to RPCS3 devs but intel itself, until they will fix their drivers, their gpus will

**Comment by AniLeo** [comment]
Vulkan issue mentioned is a local issue on your PC, OpenGL issues are due to their broken drivers, #6199.

Closing as invalid and duplicate.
