### ISSUE TITLE
Motorstorm: Pacific Rift - FATAL Monster Truck / Big Rig Crash

### ISSUE THREAD

**Issue by SatansFavSuccubus** [RPCS3/rpcs3#15243]
### Quick summary

Selecting all Monster Trucks / Big Rigs on Motorstorm: Pacific Rift now causes the EMU to crash reliably 100%.

### Details

If you select all Monster Trucks OR Big Rigs, and select either a Monster truck OR a Big Rig yourself, the emulator will immediately crash upon selecting your vehicle.

### Crash Log

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14396431/RPCS3.log)

### Other details

This used to happen once before a year or two ago and was once fixed.

**Comment by AniLeo** [comment]
Log file shows corrupted dump

**Comment by SatansFavSuccubus** [comment]
> Log file shows corrupted game dump, not a valid issue

Missing files are not the issue. Game is running in loose-file format, and has been for years without issue. Game is perfectly fine.
