### ISSUE TITLE
Motorstorm: Pacific Rift - FATAL Monster Truck / Big Rig Crash

### ISSUE THREAD

**Issue by SatansFavSuccubus** [RPCS3/rpcs3#15245]
### Quick summary

Selecting all Monster Trucks / Big Rigs on Motorstorm: Pacific Rift now causes the EMU to crash reliably 100%.

### Details

If you select all Monster Trucks OR Big Rigs, and select either a Monster truck OR a Big Rig yourself, the emulator will immediately crash upon selecting your vehicle.

### Crash Log

**[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14397181/RPCS3.log)**

### Other details

This used to happen once before a year or two ago and was once fixed. The game is NOT missing files, and is running in a loose file format, and has been without error for years. This is an issue with the emulator, nothing more. The corrupted dump is a false-positive and to be ignored.

**Resubmitted bug report due to _AniLeo_ being ill-informed and mistakenly closing a valid ticket. Do not do it again.**

A word of advice _AniLeo_ and others who stalk this forum: Wait until the OP replies before you mistakenly close a bug report because you failed to understand the entire issue, and jumped the gun to 'do your job' here on GitHub. _Just because you think you are right, doesn't mean you know anything about the problem._

**Comment by AniLeo** [comment]
Closed due to personal threats, you can keep the issue to yourself.
