### ISSUE TITLE
Demons souls crashing after beating a boss

### ISSUE THREAD

**Issue by MatkoKardum** [RPCS3/rpcs3#15241]
![20240224_200359.jpg](https://github.com/RPCS3/rpcs3/assets/94291440/8bdb2f96-ad9c-4222-ac3a-d041776fc51b)

Every time after beating a boss in Demons Souls my game crashes and everything freezes. When I beat the boss again, that doesn't happen. Is this my pc error or rpcs3 bug?

**Comment by AniLeo** [comment]
Closed for obviously ignoring the error message.
