### ISSUE TITLE
Custom Frame limit (feature request)

### ISSUE THREAD

**Issue by LasagnaPie** [RPCS3/rpcs3#15257]
### Quick summary

Custom FPS limit 

### Details

I been playing the Ratchet & Clank games on my OLED which supports 120hz and 144hz and these games run very fast and I am unable to limit the FPS to say 120fps or 144fps.  VSYNC and Enhance Sync does not help here.  

The problem is when there is a loading screen the FPS will jump to 600fps+ and it will freeze up the emulator.
![hig](https://github.com/RPCS3/rpcs3/assets/7449866/f5d19db2-1845-4123-bc39-3feedbcc85dc)

Maybe a "Framerate Scale" slider, similar to the Resolution scale, if that is even possible.

**Comment by elad335** [comment]
I think we have "Frame Limit 2" config entry, but this is exclusive to the config so users cannot misuse it as it allows for any value.

**Comment by elad335** [comment]
Although we can add the specific values you mentioned to the main setting
