### ISSUE TITLE
God of War III - White highlights

### ISSUE THREAD

**Issue by ElTioRata** [RPCS3/rpcs3#15262]
### Quick summary

My guess is that it is a regression because I don't remember experiencing this issue a few months ago. Using configuration from wiki article.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14450882/RPCS3.log)

### Attach capture files for visual issues

![white](https://github.com/RPCS3/rpcs3/assets/19964653/046b2f9d-3171-4119-aaf8-1c311a161f52)
[RSX Capture](https://drive.google.com/file/d/1DCEpr4HSb_LyGXazn1NBTxxjP_jKqdnX/view?usp=drive_link)

### System configuration

AMD Ryzen 5 5600 paired with an NVIDIA GeForce GTX 1060 3GB, using Windows 10

**Comment by FlexBy420** [comment]
Wiki has been updated recently, now you are not using the correct settings.
Settings SPU xfloat back to approxminate fixes it.
