### ISSUE TITLE
(Game name) - F{PPU[0x1000000] Thread (main_thread) [0x003c9b8c]} VM: Access violation reading location 0x2639fffc (unmapped memory) LEGO® DIMENSIONS™ [BLES02105]

### ISSUE THREAD

**Issue by Lor33** [RPCS3/rpcs3#15268]
### Quick summary

when i start the game, after the program finish loading, I have 3 different errors: 

### Details

1) E PERF: Failed to add processor time counter for per core cpu usage: impossible to find specificate object in the computer. (0xc0000bb8)

2) E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]

3) E SYS: 'sys_memory_allocate' failed with 0x80010004 : CELL_ENOMEM [1]

and then 

F{PPU[0x1000000] Thread (main_thread) [0x003c9b8c]} VM: Access violation reading location 0x2639fffc (unmapped memory)

then the Log finish and there is the message "The PS3 application has likely crashed, you can close it.

the game is Lego Dimensions.
please help me i search everywhere but i can't find anything

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14472733/RPCS3.log)

### System configuration

OS: Widows 10.
RAM : 8GB 
CPU: Intel(R) Core(TM) i7-6700HQ 
GPU: NVIDIA GeForce GTX 950M

**Comment by elad335** [comment]
Follow the ussue guidelines and I will reopem

**Comment by Lor33** [comment]
you mean i have to attach the log files and my system configurations?

**Comment by elad335** [comment]
yeah, and rename the issue title

**Comment by mavethee** [comment]
- Name it properly:
`(Game name) - F{PPU[0x1000000] Thread (main_thread) [0x003c9b8c]} VM: Access violation reading location 0x2639fffc (unmapped memory)`
At least, guessing by the stuff u randomly pasted. 
To get game name, in emulator - right click on the game in game list -> Copy Info -> Name & Serial.

- Upload a log:
Run the game, 
Reach the point when it crashes, 
Close emulator.
Upload generated log here, it's whenever you have RPCS3.exe if you are on Windows.

- Provide a specs as it's crucial to know what hardware you have.

Eventually, just ask for help on Discord server.

**Comment by Lor33** [comment]
tell me if it is ok

**Comment by AniLeo** [comment]
Still invalid, GPU drivers very outdated, settings that are not default and no explanation to why they need to be changed at all.

**Comment by Lor33** [comment]
soo wait, i'm not such an expert and i don't understand english very well😅

i changed my settings on the NVIDIA control panel for performance and i changed other settings in RPCS3 too, for the same reason.

there is something that i can do for those errors or i can't do nothing? i have only that game and one other, but with it i've never had problems

**Comment by AniLeo** [comment]
Ask for support in one of the support platforms then as previously mentioned, this is for submitting bug reports once you know what you're doing, not for asking for support
