### ISSUE TITLE
Linux: disgaea 4 intro video not working 

### ISSUE THREAD

**Issue by butzsan** [RPCS3/rpcs3#1526]
rpcs3 is not displaying the video of the intro in OGL (Linux) everything else seems to be working fine, even the sound of the intro is working (just white screen)

**LOG**
[REDACTED CONSOLE SPAM]

**Comment by MyaniPT** [comment]
That is not the log, that's the console output.
Your log is RPCS3.log in the main folder of RPCS3 (aka bin folder)

You can zip that and upload directly into github.
Also, you should always test first with PPU 1/2 and SPU 1/2, only after that use the recompilers.

**Comment by butzsan** [comment]
Here is the log, but it's on windows, in linux doesn't give me any log files (the problem also happens in windows using OGL)
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/152337/RPCS3.log.zip)

**Comment by tambry** [comment]
@butzsan Please provide the info for the CPU and GPU. Try using DX12 renderer instead (also make sure you select the right D3D adapater). Try turning off the audio, as there seems to be a lot of log spam related to some unimplemented audio decoding stuff.

**Comment by MyaniPT** [comment]
@tambry basic info about hardware and drivers should be logged too to prevent this imo #suggestion

**Comment by tambry** [comment]
@MyaniPT You could make an issue for it so if anyone developer is looking for something to do, they can do that. Also he seems to be on Linux according to title, so my note about DX12 can be ignored.

**Comment by MyaniPT** [comment]
@butzsan did you try to LLE libvdec? Your log seems so have some libvdec related outputs.
Also, you're using an outdated build (v0.0.0.6-4029-fef0b1d)

**Comment by butzsan** [comment]
@MyaniPT  the log is for windows as I said before, but I coudn't create any logs on my linux build, I'll try the last build on windows as well but my problem is on linux, is there a way to create a log there? rpcs3 doesn't generate any logs at all on linux. (Yes, I have (LLE libs)), but it is the same with or without them

**Comment by raven02** [comment]
Disgaea 4 should be working in latest build.

**Comment by raven02** [comment]
It is working okay with dmux+dmuxpamf+adec+atx . This will be the new requirement to get the video playback working
