### ISSUE TITLE
Sly Cooper Thieves in Time Frame drops

### ISSUE THREAD

**Issue by MaxConz** [RPCS3/rpcs3#15269]
### Quick summary

rpcs3-v0.0.30-16162-df4fc947_linux64.AppImage.

Frame drops then running the game.

### Details

Using recommend config.

then launching appimage i get 

these errors

Debugger: 0
Failed to set RLIMIT_MEMLOCK size to 2 GiB. Try to update your system configuration.
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile

are these related to frame drops?

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14474363/RPCS3.log)

### Attach capture files for visual issues

![Screenshot from 2024-03-03 21-52-47](https://github.com/RPCS3/rpcs3/assets/41126784/68b57101-b45a-46a5-a342-a38f8d74088d)

### System configuration

OS: Fedora release 39 (Thirty Nine) x86_64
Kernel: 6.7.5-200.fc39.x86_64
CPU: AMD Ryzen 7 5800H
GPU: NVIDIA GeForce RTX 3060 Mobile driver 545.29.06

**Comment by Jonathan44062** [comment]
Ask for support in Discord server, not here
