### ISSUE TITLE
[Feature request] Drop down list for per game saves in Save Manager

### ISSUE THREAD

**Issue by mavethee** [RPCS3/rpcs3#15266]
### Quick summary

Drop down list for per game saves

### Details

This is very misc, but could be really useful for games that create a lot of save data (e.g Alien: Isolation), making the list more clean.

![CleanShot 2024-03-02 at 18 08 11@2x](https://github.com/RPCS3/rpcs3/assets/47083527/3b88a04d-cb37-4f7b-986c-75a39bf9ed4d)

**Comment by Megamouse** [comment]
Sorry but this makes no sense and is a horrible idea. Why would you want a dropdown with 100s of entries.

**Comment by Darkhost1999** [comment]
This does sound pretty good. A lot of games even games like Far Cry Classic will create a save file for pretty much every single checkpoint or chapter and consume all of manage -> savedata for row after row of savedata.
By adding a drop down arrow but not changing the design of the save manager it can really clean things up and make finding the game you're looking for + the data you're looking for easier.
It's not like trying to have a context menu.
It's just trying to filter or hide duplicate information for the games that have spamming behaviors.

**Comment by mavethee** [comment]
Totally agree with @Darkhost1999, this would look nicer imo :)
