### ISSUE TITLE
[Linux] Xbox Series S|X Controller is not correctly mapped when connected via Bluetooth

### ISSUE THREAD

**Issue by guoyunhe** [RPCS3/rpcs3#15270]
### Quick summary

I have a Xbox Series S|X Controller.

When connected via UBS cable, RPCS3 can recognize and map controller correctly. Everything works output of box without manual configuration.

However, when connected via Bluetooth, both left and right joy sticks are mapped wrongly. And here is no way to configure it in gamepad settings (some axis are not recognized at all). Other emulators, like yuzu, has no such problem.

### Attach a log file

No

**Comment by guoyunhe** [comment]
> Not an RPCS3 issue.

Can you explain a bit more?

**Comment by Megamouse** [comment]
Neither did you upload a log nor did you specify which handler you're using.
And since you didn't we have to assume you tried both and it's either a driver issue or something else wrong with your setup.

**Comment by guoyunhe** [comment]
Issue solved. To connect Xbox Series controller via Bluetooth on Linux, you need to install this kernel driver: https://github.com/atar-axis/xpadneo
