### ISSUE TITLE
[Regression] PlayStation Home immediately crashes in new update 0.0.31-16164

### ISSUE THREAD

**Issue by Splicewave** [RPCS3/rpcs3#15274]
### Quick summary

In the previous update (16163) it did not crash but on the new update (16164) it immediately crashes the game once it launches. 

### Details

Immediately after booting the game, this appears 
![image](https://github.com/RPCS3/rpcs3/assets/71703832/086b109d-f6c3-4076-92a0-9572069b7db3)

### Build with regression

v0.0.30-16164

### Attach two log files

Log from broken build (16164)
[rpcs3.log](https://github.com/RPCS3/rpcs3/files/14509338/rpcs3.log)

Log from working build (16163)
[rpcs3.log](https://github.com/RPCS3/rpcs3/files/14509374/rpcs3.log)

### Other details

Seems that a lot of other people are reporting other games not working too so not just PS Home.

**Comment by Anya-Thoughtmane** [comment]
Can confirm, sames appening to me now. all my Disc games are bricked and come up with :
E SYS: 'sceNpManagerGetCachedInfo' failed with 0x8002aa01 : SCE_NP_ERROR_NOT_INITIALIZED [1]
E SYS: 'cellGameContentPermit' failed with 0x8002cb22 : CELL_GAME_ERROR_FAILURE [1]
E cellSysutil: Opening error message dialog with message: “Filesystem mounting failed.
(8001002b)”

**Comment by WarpZephyr** [comment]
Armored Core Verdict Day (BLUS31194) is also having issues since the latest commit 16164.

**Comment by elad335** [comment]
Retest.

**Comment by Anya-Thoughtmane** [comment]
> Retest after the update finishes.

fixed now though several dlcs still read as errors, not sure which out of 200 odd objects but about 65% i think from memory

**Comment by elad335** [comment]
Maybe you need to remove Game Data.
In RPCS3 toolbar, go to View -> Game Categories -> enable 'Game Data' catgeory, then, use the searchbar to search the game ID of it. Select the PS3 Game Data entry(ies), make sure they are of category 'PS3 Game Data' before removal.

**Comment by GTziolas** [comment]
I can report the same issue is occurring for me (RPCS3 crash to desktop) after build 0.0.31-16166 for all installed games (God of war: Ascention, God of War III, Uncharted 1, Uncharted 3, Red Dead Redemption: Game of the Year Edition). Build 0.0.30-16162 boots normally for all the above games

**Comment by elad335** [comment]
Upload log from the latest build

**Comment by GTziolas** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14513152/RPCS3.log)

**Comment by elad335** [comment]
> Maybe you need to remove Game Data.
In RPCS3 toolbar, go to View -> Game Categories -> enable 'Game Data' catgeory, then, use the searchbar to search the game ID of it. Select the PS3 Game Data entry(ies), make sure they are of category 'PS3 Game Data' before removal. Backup these folders somewhere else just in-case,

Maybe also remove game data, see how to do it here

**Comment by GTziolas** [comment]
Deleted Game Data for Uncharted: Drake's Fortune and tried to boot again to no avail. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14513246/RPCS3.log)

**Comment by willianholtz** [comment]
It also started working again in Okami and Street Fighter!

**Comment by GTziolas** [comment]
I believe https://github.com/RPCS3/rpcs3/pull/15279 fixes the issue posted here. I no longer have any issues running the titles I posted above. Thanks @elad335 for the quick responses and fix

**Comment by AniLeo** [comment]
Any remaining issues?

**Comment by Jack54guythecoder** [comment]
In RDR GOTY, it crashed on me, log as follows.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/14516500/RPCS3.zip)

**Comment by AniLeo** [comment]
That log shows 0.0.31-16163, that's not the latest build

**Comment by Jack54guythecoder** [comment]
> That log shows 0.0.31-16163, that's not the latest build

Ok, thanks for letting me know.

**Comment by willianholtz** [comment]
Ultra Street Fighter

LOG:
[ULTRA STREET FIGHTER IV [BLUS31218].log.gz](https://github.com/RPCS3/rpcs3/files/14517113/ULTRA.STREET.FIGHTER.IV.BLUS31218.log.gz)

**Comment by AniLeo** [comment]
Also log from broken build instead of latest, again, not valid.

**Comment by Splicewave** [comment]
Looks to be fine now for PS Home.
