### ISSUE TITLE
Harmony of despair freezes at loading

### ISSUE THREAD

**Issue by forutepiano** [RPCS3/rpcs3#15299]
### Quick summary

castlevania harmony of despair is freezing  while loading help me

### Details

i have gtx 1660 ti and intel core i5 dammit i can play in alice madness returns  flawlessly unlike castlevania harmony of despair (i know what its where solution already but give me answer please
![FPS_ 30 65 _ Vulkan _ 0 0 31-16190 _ Castlevania_ Harmony of Despair  NPUB30505  10 03 2024 16_58_14](https://github.com/RPCS3/rpcs3/assets/117379079/2135dde5-6642-4eb8-9805-046b9d172f0e)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14550427/RPCS3.log)

**Comment by Megamouse** [comment]
It's not freezing. it's compiling ppu modules as can be seen in the screenshot you posted
