### ISSUE TITLE
Graphical glitches after updating Mesa Intel Vulkan drivers

### ISSUE THREAD

**Issue by birthtothunder** [RPCS3/rpcs3#15302]
### Quick summary

After updating to 24.0.2 of the vulkan-intel package on Arch, I experience significant graphical glitches. Downgrading to 23.5.5 seemingly fixes it. I have no issues with other software that make use of Vulkan.

### Details
Also happens with Skate 3.
![Screenshot_20240310_152901](https://github.com/RPCS3/rpcs3/assets/121361374/4c41d61a-c24e-41b7-b10c-7f750acdc6e7)
![Screenshot_20240310_153144](https://github.com/RPCS3/rpcs3/assets/121361374/ef93b759-6ae1-4dca-9790-4c1da8628131)
![Screenshot_20240310_153221](https://github.com/RPCS3/rpcs3/assets/121361374/924f7bcf-00b4-4e1c-a6d2-88aaf2f68aa0)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14551512/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1acM7PjVGGheW7EsVj2b9tSgQpqdt_A3I/view

### System configuration

OS: EndeavourOS
CPU: Ryzen 5 1600
GPU: Arc A580

**Comment by kd-11** [comment]
You need to report this upstream to mesa. Just remember to try with strict mode enabled first.
