### ISSUE TITLE
Need for Speed: Rivals - Stuck in Loading Screen

### ISSUE THREAD

**Issue by Kupo91** [RPCS3/rpcs3#15303]
### Quick summary

After deciding, if I want to play Cop or Racer, it opens the loading screen and starts freezing

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14551747/RPCS3.log.gz)

### System configuration

Ubuntu 22.04
i7-11700B
GTX 1050

**Comment by ChwaraeTeg** [comment]
Looks like you're running default settings rather than the recommended config on the Wiki

**Comment by Kupo91** [comment]
> Looks like you're running default settings rather than the recommended config on the Wiki

Damn you are right. I thought, I did that already. So with the recommended config I made it into the game now, but it probably should not look like this:

![NPEB01412_screenshot_2024_03_24_20_23_33](https://github.com/RPCS3/rpcs3/assets/41426906/c5723270-84e1-421d-95ba-7d28835da82b)

**Comment by Asinin3** [comment]
Looks like you didn't enable "Handle RSX memory tiling" on Advanced tab. But the game is known to have issues and this isnt for support.

**Comment by Kupo91** [comment]
It is enabled.
