### ISSUE TITLE
Gran Turismo 5 - some objects have a pattern of dots on them

### ISSUE THREAD

**Issue by Resident007** [RPCS3/rpcs3#15310]
### Quick summary

In Gran Turismo 5, some of the objects (like flags in some menu scenes or fences on most of the tracks) have something that looks like a pattern of dots on them. The Internal resolution is set at 1280x720, and Resolution Scale is at 200% (2560x1440). All the other settings are as per game's page on RPCS3 Wiki.

### Details

The interesting thing is that the pattern seems to be static (even if you drive along the fence, the pattern stays the same and does not change as the vehicle moves). For example, here is one in the main menu:
![Screenshot 2024-03-11 201914](https://github.com/RPCS3/rpcs3/assets/25570319/9842df2c-6155-4cc1-945c-f2e02549d478)
And here is one in the race:
![Screenshot 2024-03-11 202110](https://github.com/RPCS3/rpcs3/assets/25570319/fe009853-7bf7-4d12-bc14-532dd4878616)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14562489/RPCS3.log.gz)

### Attach capture files for visual issues

The RSX capture is too big to upload it directly, so here's the Google Drive link: https://drive.google.com/file/d/1wL4KU1kj10GOlpJAcGW00PPUExvV1TVV/view?usp=sharing

### System configuration

AMD Ryzen 7 5800X3D
Nvidia GeForce RTX 3070 Ti
32GB DDR4-3200 RAM

**Comment by AniLeo** [comment]
Debug setting "Disable ZCull Occlusion Queries" is enabled, did you verify that the issue persists even without that setting?

**Comment by MSuih** [comment]
You also have antialiasing disabled which is very likely the actual cause of this issue

**Comment by AniLeo** [comment]
Closing due to incorrect settings that can cause this issue, if this can be reproduced with proper settings then the issue can be reopened with new log+capture

**Comment by Resident007** [comment]
> Debug setting "Disable ZCull Occlusion Queries" is enabled, did you verify that the issue persists even without that setting?

Disabling that setting didn't fix the issue, however turning antialiasing back on did. Of course it impacted performance, but the problem was indeed with antialiasing. Thank you both for helping out.
