### ISSUE TITLE
[Regression] Audio: Surround output is broken; RPCS3 always outputs in stereo

### ISSUE THREAD

**Issue by JosephM101** [RPCS3/rpcs3#15329]
### Quick summary

In RPCS3 v0.0.31 (16206-77485747), selecting Surround 5.1 or Surround 7.1 as the desired audio format doesn't change the output audio format (it stays in stereo). However, internally, surround-sound audio is handled correctly (see details). This is an issue on Windows and Linux.

### Details

With RPCS3 v0.0.22-13728-0e551400, audio options that were previously present were changed and/or removed, such as the "Downmix to 5.1" option. After doing some debugging in the latest version of RPCS3, I figured out that, in the virtual PS3, the games _are_ running in 5.1/7.1 surround, and I was able to verify this by enabling the "Dump to File" option in the Audio panel (requires debug options to be enabled) and examining/playing back the output WAV file in Adobe Audition, where I observed that all enabled channels were present and had audio.
The issue appears to be that the RPCS3 audio backend/application is outputting in stereo regardless of the audio configuration. Internally, it seems that the audio is being handled correctly, but the application itself is running in stereo. I observed this as an issue on both Windows and Linux.

### Build with regression

v0.0.22-13728-0e551400

### Attach two log files

Broken build log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14629071/RPCS3.log.gz)

Working build log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14629077/RPCS3.log.gz)

**Comment by Megamouse** [comment]
I think your default output device only supports 4 channels.
It's not really a backend issue.
Either change your default device in windows (or unplug the current one) or select a different device in RPCS3.
The default can also be changed per application in windows if I recall correctly

**Comment by JosephM101** [comment]
> I think your default output device only supports 4 channels.
You are correct. It is a quadriphonic setup. But I don't understand why that would be an issue since it wasn't with the older builds of RPCS3.

**Comment by Megamouse** [comment]
Well. Because it changed to the correct ps3 behavior.
In the past we just forced the output to 5.1 even if the game doesn't support it.
Now we present the game a list of available settings based on your device capabilities and basically choose the one that best matches the maximum channel count etc 
The auto setting chooses the "best" setting based on your device's channel count.
So if you need surround settings you probably need to select 5.1 instead of auto or whatever

**Comment by JosephM101** [comment]
> ...if you need surround settings you probably need to select 5.1 instead of auto or whatever

That's what I did. I tried 5.1, 7.1 --- I even set it to manual and selected the LPCM 5.1 and 7.1 formats myself. Nothing worked.
I do have an old PC with surround sound outputs that can be set in 5.1 or 7.1 mode, but I'll need to find time to set it up and test with RPCS3. I don't own a real AV receiver, so that's out of the question.

In all honesty, I wish that as a fallback, the down sampling options were still included in the Audio tab.

**Comment by Megamouse** [comment]
Looks like the backend reports 2 channels. I'll add some logging to see if it's true

**Comment by Megamouse** [comment]
It may be better to use a quadriphonic layout and conversion by default if 4 channels are detected.
It seems like even if we output to 4 channels you would simply get the first 4 channels of the 5.1 or 7.1 config.

**Comment by JosephM101** [comment]
Update: I tried it on my other PC which has a built-in 5.1/7.1 output, and RPCS3 worked just fine in surround mode. The only time it didn't work was when the sound card was configured in quadrophonic (4-channel) mode.

From what I can tell, RPCS3 needs at least 6 channels (5.1) before it switches into surround mode.

Probably a meaningless issue in the grand scheme of things, but I still would have liked to have my quadriphonic sound system work properly with RPCS3 without having to switch to another machine that doesn't have all my games, saves and other stuff. Regardless, thank you for looking into this at all.

**Comment by JosephM101** [comment]
> It may be better to use a quadriphonic layout and conversion by default if 4 channels are detected. It seems like even if we output to 4 channels you would simply get the first 4 channels of the 5.1 or 7.1 config.


That would stand true, but the first four channels in 5.1 are front left + right, front center, and the low frequency effects (LFE) channel. Maybe if RPCS3 had some way of mapping the rear channels from 5.1 or 7.1 to 4.0?

**Comment by Megamouse** [comment]
@JosephM101 you can try this build later: #15359

**Comment by JosephM101** [comment]
Excellent, thank you so much for the work you've done! I will test it as soon as I can!

**Comment by JosephM101** [comment]
I'm having an issue compiling the build. I followed the instructions on the RPCS3 build README, but no dice. Visual Studio 2022 throws a single error whose message is a string of every ui file. The error is some code that has to do with custom build routines.

**Comment by Megamouse** [comment]
It's already in the official builds

**Comment by JosephM101** [comment]
> It's already in the official builds

I see. Thank you for clarifying.
