### ISSUE TITLE
mgs4 rpcs3 crash error

### ISSUE THREAD

**Issue by asdasdadsadsasdsd** [RPCS3/rpcs3#15328]
### Quick summary

im trying to play mgs4 in the emulator but everytime it crashes as soon as i walk, and this is always what the log says, but i dont understand it.

E SYS: Stat: 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/s/stage/mg_setup1” [x5]
E SYS: Stat: 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/s/stage” [x11]
E SYS: Stat: 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/s/stage/init” [x5]
E SYS: Stat: 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/s/slotdat” [x14]
E SIG: Thread [SPUW.3] is too sleepy. Waiting for it 17390.245µs already!
E SYS: Stat: 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/s/stage” [x22]
E SYS: Stat: 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/s/stage/init” [x9]
E SYS: Stat: 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/s/stage/mg_setup” [x6]
E SYS: Stat: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00246/USRDIR/sdpack_e/wpn021_deserteagle.ssp.ctmp” [x4]
E SYS: Stat: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00246/USRDIR/photo” [x4]

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14628649/RPCS3.log.gz)

### Attach capture files for visual issues

![Captura de tela 2024-03-17 162839](https://github.com/RPCS3/rpcs3/assets/112904643/5f60ec56-578d-486e-93de-aa1f829387bb)

### System configuration

cpu:  amd ryzen 5 5600x 6-core processor
gpu: NVIDIA Geforce dtx 1650
16gb Ram

**Comment by AniLeo** [comment]
Invalid bug report, this is not the place for support requests
