### ISSUE TITLE
Unsupported color space (9) in pngDecodeData

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1532]
**Using 2f89d150**
Log @ [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/155454/RPCS3.zip)
```
·! LDR: Title: Closure
·! LDR: Serial: NPUB30722
·F {PPU Thread[0x1] (main_thread)[0x0025c99c]} Exception: Unsupported color space (9)
(in file C:\rpcs3\rpcs3\Emu\SysCalls\Modules\cellPngDec.cpp:691, in function pngDecodeData)
```
![screenshot_106](https://cloud.githubusercontent.com/assets/10283761/13472278/0d1534e4-e0ac-11e5-86ac-d884819026cc.png)

**Using an older build (before cellPngDec rewrite)**
![screenshot_104](https://cloud.githubusercontent.com/assets/10283761/13472294/1c57c9c6-e0ac-11e5-9f47-442a027dd9cf.png)
![screenshot_105](https://cloud.githubusercontent.com/assets/10283761/13472296/1ef4e7ae-e0ac-11e5-8f24-443f010cf12e.png)
![screenshot_103](https://cloud.githubusercontent.com/assets/10283761/13472297/2042ff9c-e0ac-11e5-8790-b98f0a99b0a9.png)
(As seen on http://www.emunewz.net/forum/showthread.php?tid=173873)
LLE: cellPngDec
[RPCS3_old.zip](https://github.com/RPCS3/rpcs3/files/155461/RPCS3_old.zip)

**Comment by tambry** [comment]
Hmmm. It's using CELL_PNGDEC_GRAYSCALE_ALPHA. No idea why would a game really use it, but I guess I have something to fix during the weekend.

**Comment by tambry** [comment]
Looking into it.

**Comment by tambry** [comment]
@vlj @kd-11 Using cellPngDec LLE (cellSre and cellSpursJq may also be needed):
* [On Vulkan the colours are very messed up](http://i.imgur.com/xaUAHvK.png
* [On DX12 there also seem to be some issues with colours, but it's better](http://i.imgur.com/jiAMAsH.png)
* On OpenGL it's just a black screen.

**Comment by kd-11** [comment]
Might be an issue selecting the proper internal format, at least for vulkan. Not sure about OpenGL though.

**Comment by tambry** [comment]
Well, this is not nice at all. The texture(s) the game provides are RGBA, but it wants them output as GA (Greyscale Alpha). Thankfully, it's quite easy to tell libpng to simply convert such images to grayscale. The HLE implementation as of https://github.com/tambry/rpcs3/commit/74dbabef4e6b29423577ccb82702c4b6d08e4d35 should now be on par with LLE.
Might also be worth noting that the HLE implementation is about 11x faster than LLE!

Albeit that there's quite many graphical glitches in the menu (and intros):
![](https://i.imgur.com/KJ8MSn8.png)

**Comment by SakataGintokiYT** [comment]
Minecraft 
Before cellPngDec.cpp:641

{PPU Thread[0x1] (main_thread)[0x0081ada4]} Exception: RGB colour format.
(in file Emu\SysCalls\Modules\cellPngDec.cpp:653, in function pngDecodeData)

**Comment by tambry** [comment]
Probably makes sense to unify the copy to the buffer for different formats.
[New build](https://mega.co.nz/#!xYomHaBB!XP-94AcQ013IZNB-CatzrSE5QPtjgXn2QP-9Ldsz3yg)

**Comment by tambry** [comment]
On latest master, the logo and text now have a waving animation, as they do on a real PS3. The color issues persist along with OGL not displaying anything.

**Comment by SakataGintokiYT** [comment]
{PPU Thread[0x1] (main_thread)[0x000af470]} Exception: Partial image decoding is not supported.
(in file Emu\SysCalls\Modules\cellPngDec.cpp:288, in function pngDecOpen)

**Comment by tambry** [comment]
It's basically useless without telling me what game that occurs in. I do know that one of the Date A Live games uses partial image decoding.

**Comment by SakataGintokiYT** [comment]
The Family Planning re Spin Yarn [NPJB90656]

**Comment by tambry** [comment]
Probably worth a separate issue. This is probably something that may take a while to implement.

**Comment by tambry** [comment]
Been working on fixing up colour formats for DX12.
Seems like the logo is now visible.

![](https://i.imgur.com/2eOqim9.png)

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/1661 might fix the OGL black screen. I'll take a look at the remapping issues later.

**Comment by tambry** [comment]
Should be fixed.
