### ISSUE TITLE
Some of cars cockpit are dark and no detail.

### ISSUE THREAD

**Issue by samuellaitw** [RPCS3/rpcs3#15337]
### Quick summary

![1564651561](https://github.com/RPCS3/rpcs3/assets/18376818/34254563-bbd2-4488-a1e2-b2ec4b595614)
I can't fix this probrem by changing setting.

### Attach a log file

S RSX: Program compiled successfully x47
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98296/USRDIR/PDIPFS/55/BU” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98296/USRDIR/PDIPFS/55/BU” [2]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98296/USRDIR/PDIPFS/55/BU” [3]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98296/USRDIR/PDIPFS/5I/BH” [1]
S RSX: Program compiled successfully x2

**Comment by FlexBy420** [comment]
This is not an issue, standard cars don't have an interior only premium ones do.

**Comment by MSuih** [comment]
Yes, the game developers made this decision and rpcs3 is emulating it accurately

**Comment by samuellaitw** [comment]
> This is not an issue, standard cars don't have an interior only premium ones do.
I found out this video's r33 have interior and mine isn't https://www.youtube.com/watch?v=G9fzeX2tL_c&t=27s

**Comment by FlexBy420** [comment]
That's because you are using a car with simplified interior, not detailed one. Theres 7 models of R33 that have simplified interior the one shown in the video you linked is the only model with detailed interior.

**Comment by samuellaitw** [comment]
Oh i got it, its my bad. Thanks for your reply.

> That's because you are using a car with simplified interior, not detailed one. Theres 7 models of R33 that have simplified interior the one shown in the video you linked is the only model with detailed interior.
