### ISSUE TITLE
Call of duty black ops usa 

### ISSUE THREAD

**Issue by blake8936** [RPCS3/rpcs3#15334]
### Quick summary

Call of duty black ops wont boot after compiling shaders and preboot if system is offline 

### Details

Game will not boot unless theres an active internet connection.

### Attach a log file

No log

**Comment by blake8936** [comment]
Ill provide whatever you need but all you need to do is boot cod blackops and rpcs3 offline. Black ops is at the most recent update provided from your discord channel

**Comment by AniLeo** [comment]
Does not follow the issue template
