### ISSUE TITLE
[Feature request] Map motion inputs to fake move handler

### ISSUE THREAD

**Issue by Suegrini** [RPCS3/rpcs3#15344]
### Quick summary

Map the dualshock 3 gyro and accelerometer inputs to the ps move fake handler to make move games that use motion inputs playable with a gamepad.

### Details

The ps move fake currently only maps the axis position and buttons to a ps move instance, the functionality of some games like HOTD4 would be greatly improved if it would also map the dualshock 3's gyro and accelerometer inputs to a ps move.

**Comment by Megamouse** [comment]
Duplicate of #8452
