### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#15340]
### Quick summary

Thanks for reading my topic.
OS Linux Ubuntu 20.04.6 and RPCS3 current version.
In Shortcuts menu configuring toggle and exit full screen for use an keyboard key not work.
Config is toggle full screen = ]
and
exit full screen = /

Not is an report about gameplay issues. Thus the log is zero byte only to report.
Need an full log or an copy of config files ?
Have an nice day.

### Attach a log file

[log.log](https://github.com/RPCS3/rpcs3/files/14707620/log.log)

**Comment by Megamouse** [comment]
The shortcut is just for the main window, not the game window.
And it works fine as far as I can tell.

**Comment by Augusto7743** [comment]
You are correct.
I not understand if is possible implement that shortcut for game window too.
If is possible will be very good =)
Have an nice day.
