### ISSUE TITLE
Emulator crashes when changing virtual filesystem settings

### ISSUE THREAD

**Issue by JoseLgamer** [RPCS3/rpcs3#15358]
### Quick summary

I have my virtual ps3's hdd data onto a secondary drive, but when I try to add the paths to the various partitions and locations of the ps3 so RPCS3 can use them, it just errors out and crashes and nothing has been saved.

### Details

To reproduce the issue, I go to the manage tab, virtual file system, and try to add a path in any of the tabs that come up in the virtual file system manager window (except dev_usb, that one works as expected), add the desired path and hit save, when I do that last step, It just complains about a fatal error and closes. Screen shot included in the RSX capture section.  

### Attach a log file

Unable to run games, since I can't map the directories that ps3 hdd data is stored, here is the bit on the bottom of the emulator's home screen:

- SYS: RPCS3 v0.0.31-1-adedc7c6 Alpha | master | local_build
- SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.53 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 6.7.9-200.fc39.x86_64, Version: #1 SMP PREEMPT_DYNAMIC Wed Mar 6 19:35:04 UTC 2024
- SYS: Current Time: 2024-03-26T16:01:43
- RSX: Found Vulkan-compatible GPU: 'AMD Radeon RX 5500 XT (RADV NAVI14)' running on driver 24.0.3
- RSX: Found Vulkan-compatible GPU: 'llvmpipe (LLVM 17.0.6, 256 bits)' running on driver 0.0.1
- SYS: Missing Firmware

### Attach capture files for visual issues

![Screenshot_20240326_155554](https://github.com/RPCS3/rpcs3/assets/60066218/cbe73c27-195f-49f6-99be-69f4a743f319)

### System configuration

AMD Ryzen 5 2600
16gb 3200MHz RAM
MSI B450M MORTAR MAX
AMD RX 5500XT (ASUS DUAL model)
KIOXIA EXCERIA 500GB NVMe SSD
1TB Seagate 2.5" HDD
Fedora KDE 39
RPCS3 Flatpak version

**Comment by FlexBy420** [comment]
Flatpak is not official and not maintained by RPCS3 devs, use appimage.
