### ISSUE TITLE
Framerate capped at 15 in Cars 2

### ISSUE THREAD

**Issue by Sixteen60** [RPCS3/rpcs3#15379]
### Quick summary

I started up Cars 2 via PCRS3, only to be stuck at 15 FPS when I was easily getting 60 FPS in Mortal Kombat 9.

### Details

![Screenshot 2024-03-30 214204](https://github.com/RPCS3/rpcs3/assets/99849136/19735956-2a3c-46df-a712-407aa5ce53ba)
In Cars 2, I was stuck with 15 FPS upon getting to the title screen.

![image](https://github.com/RPCS3/rpcs3/assets/99849136/33884c8d-7a8b-48f4-b9f8-72a03b0c6f71)
Meanwhile in MK9, I was getting a constant 60 FPS.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14814149/RPCS3.log.gz)

### System configuration

16 GB Ram
Intel-I5 10400
RTX 3060 12G
Windows 11
DualShock 4

**Comment by AniLeo** [comment]
Non default settings being used without any explanation as to why.

**Comment by Sixteen60** [comment]
These were all the settings I had for the game. @AniLeo 
![Screenshot 2024-03-31 100136](https://github.com/RPCS3/rpcs3/assets/99849136/a82e362e-2392-4a88-9aab-1e65bdbd9b93)
![Screenshot 2024-03-31 100138](https://github.com/RPCS3/rpcs3/assets/99849136/3ee184c9-3b89-4312-b137-3f00a14a2a0a)
![Screenshot 2024-03-31 100143](https://github.com/RPCS3/rpcs3/assets/99849136/2fb86a35-53f7-4b7f-95dd-20a04339cb1e)
![Screenshot 2024-03-31 100145](https://github.com/RPCS3/rpcs3/assets/99849136/901628c2-9d11-4559-87cb-094efdbf48b7)
![Screenshot 2024-03-31 100147](https://github.com/RPCS3/rpcs3/assets/99849136/165767dd-6b95-42a6-b69a-d33c1cbbddc3)
![Screenshot 2024-03-31 100149](https://github.com/RPCS3/rpcs3/assets/99849136/1638cbad-b2a7-4e39-9074-b85551541f83)
![Screenshot 2024-03-31 100151](https://github.com/RPCS3/rpcs3/assets/99849136/237216f9-a0c1-4ed2-8fb7-4c9c3ba86a23)
![Screenshot 2024-03-31 100153](https://github.com/RPCS3/rpcs3/assets/99849136/0772dc7f-9825-4459-9515-799986ba2cc1)

**Comment by AniLeo** [comment]
Not the point, we can see the settings in the log. If different settings from default are required you need to explain why, otherwise you need to use defaults.

**Comment by Ordinary205** [comment]
The reason why you're experiencing 15 FPS on Cars 2, is because you've enabled Preferred SPU Threads as 1. Which can cause issues for some games.

Preferred SPU Threads 1:
![1](https://github.com/RPCS3/rpcs3/assets/125112932/2404de01-4978-426e-8c5f-29b33f0fbef7)

Preferred SPU Threads Auto:
![Auto](https://github.com/RPCS3/rpcs3/assets/125112932/d5e44ea5-8835-452a-af40-6261844daf79)

So please be a bit cautious about non default settings before opening a new issue.

**Comment by AniLeo** [comment]
Closing as Invalid.

**Comment by Sixteen60** [comment]
> The reason why you're experiencing 15 FPS on Cars 2, is because you've enabled Preferred SPU Threads as 1. Which can cause issues for some games.
> 
> Preferred SPU Threads 1: ![1](https://private-user-images.githubusercontent.com/125112932/318291865-2404de01-4978-426e-8c5f-29b33f0fbef7.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MTA5NzEsIm5iZiI6MTcxMTkxMDY3MSwicGF0aCI6Ii8xMjUxMTI5MzIvMzE4MjkxODY1LTI0MDRkZTAxLTQ5NzgtNDI2ZS04YzVmLTI5YjMzZjBmYmVmNy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxODQ0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjdkZTYwYzQ4YTY4NmFlODY4OGY2MmNjNzk1MjMxYTRlYTE4NDFmNGUyN2JjN2U0NjEyYmM4MGMyYWE2NGFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RN7xRkaziV9BF-f8H6CTAwToiRQCP2NHK8YJVtTASs8)
> 
> Preferred SPU Threads Auto: ![Auto](https://private-user-images.githubusercontent.com/125112932/318291889-d5e44ea5-8835-452a-af40-6261844daf79.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MTA5NzEsIm5iZiI6MTcxMTkxMDY3MSwicGF0aCI6Ii8xMjUxMTI5MzIvMzE4MjkxODg5LWQ1ZTQ0ZWE1LTg4MzUtNDUyYS1hZjQwLTYyNjE4NDRkYWY3OS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxODQ0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjllZmYwN2VjZmFhMzYzYTgzZGVkNGEyNzc3NThiZDdhNGI2ZTQzNDQ2NGE0MzM5NjU0MWRlMDFjNTc0NjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mNUzvqbceFzYUmHmWo6njw0l-DQQ0DFwC1O7xEX5Lao)
> 
> So please be a bit cautious about non default settings before opening a new issue.

Works, but I'm still only getting 25 FPS.
