### ISSUE TITLE
RPCS3 leaks memory on PPU compilation

### ISSUE THREAD

**Issue by mguinhos** [RPCS3/rpcs3#15376]
Compiling with 16 llvm threads eats the whole RAM and Swap. Even when the game is closed, the memory isnt freed.

Tested on i5-13450HX (PS3UPDATE.PUP)

![20240330_052351.jpg](https://github.com/RPCS3/rpcs3/assets/43307018/7d5b7a6f-caad-4e58-8dac-81f3daf66e32)

Its only when we exit RPCS3 that the memory is freed.

**Comment by elad335** [comment]
even after the compilation finishes?

**Comment by mguinhos** [comment]
> Try to set LLVM threads to 8 on Emulator tab and compile again with Firmware cache removed.

Thanks, i guess i solved. My swap was too small. Increased to 4GB, and it was sufficient.

Reducing to 8 threads only also worked.

**Comment by elad335** [comment]
But with 8 threads, the leak itself is not resolved, just lowered the memory usage, correct?

**Comment by mguinhos** [comment]
Not a memory leak, just a misconfiguration on my operating system.

**Comment by elad335** [comment]
Nah, its a bug of RPCS3, we do compile concurremtly up to the amount of CPU threads you have without considering real world memory restrictions.

**Comment by elad335** [comment]
Actually it was not the thread count after all, but I'll provide a tentative fix for that too.
