### ISSUE TITLE
[Regression] VSH crashes after launch (#15377)

### ISSUE THREAD

**Issue by GreemDev** [RPCS3/rpcs3#15382]
### Quick summary

VSH crashes the emulation window and the main RPCS3 window a few seconds after the precompilation screen is gone.

### Details

When booting VSH/XMB with v0.0.31-16272 (commit [d62e90f](https://github.com/RPCS3/rpcs3/commit/d62e90f5b45955f70bd74042b3b5ce002c2cbf51)) or older, it launches just fine.
When launching with v0.0.31-16276 however, VSH seems to be fine for a second, PPU compilation hint shows up. Then a significant drop in framerate, then freeze, then a crash entirely.

### Build with regression

V0.0.31-16276

### Attach two log files

[before-regression.gz](https://github.com/RPCS3/rpcs3/files/14817244/before-regression.gz)
[with-regression.log](https://github.com/RPCS3/rpcs3/files/14817245/with-regression.log)

### System configuration

Windows 11
i7-13700F
RTX 4070Ti (driver version 551.61.0.0)

### Other details

I am not the only one with this issue, I'm just filing a regression report as [Ani asked of me in the Discord](https://canary.discord.com/channels/272035812277878785/272083901277667342/1224057642733932747).

**Comment by autofire372** [comment]
I also experienced this crash on Windows 10. On EndeavourOS, the latest rpcs3 AppImage had the XMB crash, but not rpcs3 itself.

Just like on Windows, an older source build of rpcs3 on Linux runs the XMB fine.
