### ISSUE TITLE
Segfaults when changing game folder on steamdeck

### ISSUE THREAD

**Issue by lonelycare** [RPCS3/rpcs3#15391]
### Quick summary

1. go to manage -> virtual file system
2. click save
3. segfaults and crashes

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14841332/RPCS3.log)

### System configuration

SteamDeck LED

**Comment by AniLeo** [comment]
Non-official build being used, invalid issue.
