### ISSUE TITLE
DX12/GL/Vulkan : TNT Racers missing in-game textures

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1539]
Video demonstrating the issue
http://www.youtube.com/watch?v=U8DJJl4HyvY
(Jump to 00:28)

DirectX 12
OpenAL
PPU 2 / SPU 2
Requires **cell_Sre** LLE'd
**NPEB00221** - TNT Racers

Post @ EmuNewz 
http://www.emunewz.net/forum/showthread.php?tid=163808&pid=230461#pid230461

If it isn't something you can fix at this stage, this could probably be closed.

**Comment by MyaniPT** [comment]
Seems to be working for NVidia GPUs as showed here
http://www.emunewz.net/forum/showthread.php?tid=163808&pid=230466#pid230466

**Comment by tambry** [comment]
Does #1537 fix it?

**Comment by MyaniPT** [comment]
@tambry Nope

**Comment by raven02** [comment]
Yep, just tested on my GT 650 , it looks fine and no flickering in menu .

**Comment by MyaniPT** [comment]
Still an issue in latest master (dd233c9 commit)

**Comment by tambry** [comment]
So does it now work with DX12, but still doesn't with OpenGL?

**Comment by SakataGintokiYT** [comment]
@tambry 
Yes still the same problem 
<img src="http://www.fotoszok.pl/upload/123230e5.jpg" alt="Fotoszok.pl" />

**Comment by AniLeo** [comment]
@SakataGintokiYT The problem I wanted to show here is actually the menu flickering. The ingame will take more implementations and time to be displayed properly.
I haven't had the time to test yet, but I will as soon as I can

**Comment by AniLeo** [comment]
@tambry It's not fixed. It actually got way worse in latest master.
![screenshot_141](https://cloud.githubusercontent.com/assets/10283761/14153284/1c99d492-f6af-11e5-8cea-67fa8622c91e.png)
![screenshot_142](https://cloud.githubusercontent.com/assets/10283761/14153283/1c99d032-f6af-11e5-8859-e230afd4a5ec.png)

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/1766 fixes opengl and vulkan.  DX12 still stutters for AMD cards. I'll look into it.

**Comment by AniLeo** [comment]
Tested today on Vulkan, it blinks really fast with black and white frames, doesn't show any video. 
Same goes for OpenGL. Weird

**Comment by kd-11** [comment]
That fix was for menu only. Ingame is still broken for all.

**Comment by AniLeo** [comment]
I can't get to the menu, it's completely broken, it just flashes white and black

**Comment by kd-11** [comment]
@AniLeo See https://github.com/RPCS3/rpcs3/issues/1853
