### ISSUE TITLE
RPCS3 Crashes When Checking for Updates

### ISSUE THREAD

**Issue by Zeromus24** [RPCS3/rpcs3#15409]
### Quick summary

RPCS3 crashes when it checks for updates. The issue is 100% reproducible on my computer. I've tried doing a clean install.
 See the attached screenshot:
![image](https://github.com/RPCS3/rpcs3/assets/49614982/d92a5d7c-1428-497d-b720-efe355fd66c6)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14892590/RPCS3.log)

**Comment by AniLeo** [comment]
Already fixed, you're using an old build.

**Comment by Zeromus24** [comment]
Updated to v0.0.31-16295-517f0e1b from rpcs3-v0.0.31-16282-2a89d87f. Will report if issue still persists.
