### ISSUE TITLE
Kung Fu Panda 2 - The whole screen is a big artifact

### ISSUE THREAD

**Issue by vandersdg** [RPCS3/rpcs3#15403]
### Quick summary

There are purple and blue artifacts everywhere
![Captura de tela de 2024-04-04 21-08-14](https://github.com/RPCS3/rpcs3/assets/90361836/3649c299-7cf4-4c7d-8ea4-e8451ab9da71)

### Attach a log file
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14878545/RPCS3.log)

**Comment by Jonathan44062** [comment]
Post the actual log file, not copy and paste random section

**Comment by vandersdg** [comment]
Done!

**Comment by Jonathan44062** [comment]
According to your log, your game files are broken, redump it again

**Comment by vandersdg** [comment]
> According to your log, your game files are broken, redump it again

How can you be sure it is broken?

**Comment by Jonathan44062** [comment]
Because I have seen it

**Comment by vandersdg** [comment]
> Because I have seen it

But what error specifically tells that the game files are broken? I would like to be able to diagnose myself in the future

**Comment by Jonathan44062** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/78843189/3b5880fb-f258-4a83-8ed9-4aa10ad64775)
Better ask for support on the Discord RPCS3 server instead of here

**Comment by vandersdg** [comment]
Alright! Thank you so much for your time!!!
