### ISSUE TITLE
[Regression] God of War® III [BCES00510] stutter on new builds

### ISSUE THREAD

**Issue by 13Raven92** [RPCS3/rpcs3#15419]
### Quick summary

Hello

God of War® III [BCES00510] only plays without stutters (shaders build on the first playthrough) on this build: RPCS3 v0.0.24-14192-80d20340.

### Details

no newer builds play the game without stutters. currently on build: RPCS3 v0.0.31-16264-ac034040 I tested a few older builds from last year but they all perform the same way, all stutter with prebuild shaders/spu cache.

I tested with a completely new install with the latest build (RPCS3 v0.0.31-16264-ac034040), everything started from scratch and ran the game but weirdly the game still stutters!
I used all recommended settings from the games wiki page and default RPCS3 settings and had no luck.

- SYS: RPCS3 v0.0.31-16264-ac034040 Alpha | master
- SYS: Intel® Core™ i5-9400F CPU @ 2.90GHz | 6 Threads | 15.92 GiB RAM | TSC: 2.904GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 4070 Ti' running on driver 551.23.0.0
- SYS: Firmware version: 4.89

### Build with regression

v0.0.31-16264-ac034040

### Attach two log files

[Old Build v0.0.24-14192-80d20340 log file.gz](https://github.com/RPCS3/rpcs3/files/14919763/Old.Build.v0.0.24-14192-80d20340.log.file.gz)
[New Build v0.0.31-16264-ac034040 log file.log.gz](https://github.com/RPCS3/rpcs3/files/14919766/New.Build.v0.0.31-16264-ac034040.log.file.log.gz)

### System configuration

- SYS: Intel® Core™ i5-9400F CPU @ 2.90GHz | 6 Threads | 15.92 GiB RAM | TSC: 2.904GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 4070 Ti' running on driver 551.23.0.0
- SYS: Firmware version: 4.89

**Comment by elad335** [comment]
Huge gap between the 2 builds, closing until the correct build is found.

**Comment by 13Raven92** [comment]
> Huge gap between the 2 builds, closing until the correct build is found.

Hello again

don't know if I should open a new issue.

I finally found the time to dig in quite a few builds and found the faulty one.
this is the last version that runs the game smoothly:
v0.0.28-15401-5d98f386_win64
and this is the version that stuttering started:
v0.0.28-15404-75ad5633_win64

**Comment by TigiHof** [comment]
> don't know if I should open a new issue.
> 
> I finally found the time to explore several builds and discovered the faulty one. this is the last version that runs the game smoothly: v0.0.28-15401-5d98f386_win64 and this is the version that stuttering started: v0.0.28-15404-75ad5633_win64

I'd definitely recommend opening a new issue, providing logs for the last working release and for the one causing the problem. In my experience closed issues rarely get reopened - and certainly not without log info.

**Comment by 13Raven92** [comment]
oh ok then brb
