### ISSUE TITLE
[Regression] Tales of Xillia screen goes red, then is blocked by something

### ISSUE THREAD

**Issue by Daniel-Katz** [RPCS3/rpcs3#15412]
### Quick summary

Tales of Xillia screen goes red and black (it alternates based on the status of the game, like the menu), but according to the audio it appears to be technically running, even if I can't see anything

### Details

Tales of Xillia HAD an issue where the game would just shut off during the startup, and THAT part was fixed, but either something as part of the fix messed it up, or something that happened since the version that introduced the crash messed it up, so I don't know exactly when this problem was introduced. I just know that as of approx a week ago when it was fixed, I've had this problem instead of the crashing when I try to use the most up to date version, instead of the 2/24/24 version.

### Build with regression

0.0.30-16146 (unsure, as per details)

### Attach two log files

[RPCS3 - Bad.log](https://github.com/RPCS3/rpcs3/files/14895328/RPCS3.-.Bad.log)
[RPCS3 - Still Bad.log](https://github.com/RPCS3/rpcs3/files/14895329/RPCS3.-.Still.Bad.log)
[RPCS3 - Good.log](https://github.com/RPCS3/rpcs3/files/14895330/RPCS3.-.Good.log)
****

### Attach capture files for visual issues

[Image Issues.zip](https://github.com/RPCS3/rpcs3/files/14895332/Image.Issues.zip)

### Other details

The logs are as follows:
RPCS3.-.Good.log is the log file that worked properly, from 2/24/24
RPCS3.-.Bad.log is the log file that crashed from 2/26/24
RPCS3.-.Still.Bad.log is the file with the visual problems, which I tried from today. I could try the one from a week ago, if it would help, but I don't know which specific version introduced the fix to the 2/26/24 issue

In case it helps:
the link to the original "issue" I created - https://github.com/RPCS3/rpcs3/issues/15361
the link to the created "issue" that addressed it - https://github.com/RPCS3/rpcs3/pull/15363

**Comment by Daniel-Katz** [comment]
In case it helps:
the link to the original "issue" I created - https://github.com/RPCS3/rpcs3/issues/15361
the link to the created issue that addressed it - https://github.com/RPCS3/rpcs3/pull/15363

**Comment by Megamouse** [comment]
I think this worked fine when I fixed it. Maybe it's a driver issue?
