### ISSUE TITLE
[Regression] Marvel Super Hero Squad: Comic Combat (BLES01379) broken visuals since #15003

### ISSUE THREAD

**Issue by YuriNator557** [RPCS3/rpcs3#15411]
### Quick summary

From PR #15003 the graphics in this game are severely broken, not even video files are rendered properly and the title screen is a mess.

### Details

Last working version - 0.0.30-15910
![image](https://github.com/RPCS3/rpcs3/assets/76178650/e70dbda2-c2af-44fc-a089-0b1609c2eb14)

First broken version - 0.0.30-15912
![image](https://github.com/RPCS3/rpcs3/assets/76178650/ff3ceaf5-eaae-4238-834f-fd918aedc8c2)

I added some more in my report for this game on the forums: https://forums.rpcs3.net/showthread.php?tid=207254&pid=325618#pid325618

### Build with regression

RPCS3 v0.0.30-15912-bc141831 

### Attach two log files

[comiccombatbroke.gz](https://github.com/RPCS3/rpcs3/files/14895049/comiccombatbroke.gz)
[comiccombatworking.gz](https://github.com/RPCS3/rpcs3/files/14895050/comiccombatworking.gz)

### Attach capture files for visual issues

[BLES01379_20240406223959_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/14895054/BLES01379_20240406223959_capture.rrc.gz)
[comiccombat.rdc.gz](https://github.com/RPCS3/rpcs3/files/14895059/comiccombat.rdc.gz)

### System configuration

i9-12900k
RTX 4090 driver 551.61
Windows 10 23H2

### Other details

The log also spams the hell out of E RSX: Unhandled video output format 0x2 while the game is running. I can see someone reported that The Penguins of Madagascar was also broken by this build but I don't have that one to test.

**Comment by YuriNator557** [comment]
Apparently Kung Fu Panda 2 is also affected by this issue.

**Comment by FlexBy420** [comment]
Marvel Super Hero Squad: The Infinity Gauntlet [BLUS30525] is also affected by this.

**Comment by Triticum0** [comment]
Affects DreamWorks The Penguins of Madagascar - Dr. Blowhole Returns - Again!

**Comment by SerpicoSal** [comment]
Capture to show what "DreamWorks The Penguins of Madagascar - Dr. Blowhole Returns - Again!" currently looks like on a steam deck:
![image](https://github.com/RPCS3/rpcs3/assets/164986935/130d0f82-e3f4-49de-9a4a-e3422c67fb99)
(seen while running v0.0.31-16299-412db758)

Info from @YuriNator557 first post had me try version 0.0.30-15910 which resolved this specific graphics issue.

**Comment by Florin9doi** [comment]
Fixed by #15431
