### ISSUE TITLE
DX12: Grand Theft Auto IV and Episodes of Liberty City broken graphic

### ISSUE THREAD

**Issue by annahana** [RPCS3/rpcs3#1541]
system: windows 10 pro
Processor: Intel(R) Core(TM) i3-2120 CPU
Memory: 4096MB RAM
AMD Radeon HD 6450

in GrandTtheaft Auto IV and Episods of Liberty City boot screan the menu flikers and image is in wrong place

in dx12
![gtadx12](https://cloud.githubusercontent.com/assets/13276505/13548376/39332f96-e2ef-11e5-9691-709aa06015c7.PNG)

in opengl
![gtaopengl](https://cloud.githubusercontent.com/assets/13276505/13548380/52faea22-e2ef-11e5-93ff-2899a49660c7.PNG)

**Comment by tambry** [comment]
Please post the log.

**Comment by annahana** [comment]
logis attached, change .png zu .7z

![gta4](https://cloud.githubusercontent.com/assets/13276505/13549016/7b08a668-e2fd-11e5-989a-f9df9407f9cd.png)

**Comment by tambry** [comment]
Still an issue?

**Comment by annahana** [comment]
testet with RPCS3 v0.0.0.6-6-56ac7f2 and is the same as before

[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/209296/RPCS3.txt)

**Comment by elfogames** [comment]
anything changed on v0.0.0.9?

**Comment by elfogames** [comment]
hd 6460 doesnt not support dx12

**Comment by AniLeo** [comment]
Oh it really doesn't. Such a trivial mistake though.
