### ISSUE TITLE
Uncharted: Drakes Fortune [BCES00065]: Texture glitch in Chapter 15

### ISSUE THREAD

**Issue by Flori98** [RPCS3/rpcs3#15423]
### Quick summary

In the beginning of Chapter 15, textures of two walls are not loaded correctly. 

### Details

I know that shaders are constantly compiling so that there are graphical glitches and textures are loading over and over again. But with time, the glitches are gone and textures are loaded. But in the beginning of Chapter 15, textures of two walls aren't loaded correctly.
![BCES00065_screenshot_2024_04_10_17_58_15](https://github.com/RPCS3/rpcs3/assets/166349235/4eddf38f-0891-4cdc-b7ac-549e3f71888f)

This issue is reproductive.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14934851/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14934853/RPCS3.log)

### Attach capture files for visual issues

[Uncharted Drakes Fortune Renderdoc Capture Chapter 15.zip](https://github.com/RPCS3/rpcs3/files/14934792/Uncharted.Drakes.Fortune.Renderdoc.Capture.Chapter.15.zip)

### System configuration

GPU: NVIDIA RTX 2060 6GB
CPU: AMD Ryzen 5600X
16 GB RAM
OS: Windows 10

NVIDIA Driver Version: 552.12

**Comment by Jonathan44062** [comment]
You're very late to make these reports. It's already reported by https://github.com/RPCS3/rpcs3/issues/11259
Next time and I recommend that you check if the problem has already been reported, if there is nothing in Github, do it
