### ISSUE TITLE
Skate 3

### ISSUE THREAD

**Issue by Laggamer2005** [RPCS3/rpcs3#15420]
### Quick summary

I have major glitches. Randomly, the game enters a glitched state where my avatar corrupts, falls through the map randomly, and the camera goes wrong. I have a asus ROG ally.

### Details

So. I fire up the game, and randomly, the game glitches out like this: My avatar’s body flies off in a direction. It falls through the map. Also, the camera is wonky. This happens until I quit the game. 

### Attach a log file

[https://docs.google.com/document/d/1F_6zg8xMIAsWcvgT8-HV8MElPpLJQ-VducM_oQxL504/edit] (url)

### Attach capture files for visual issues

[https://drive.google.com/file/d/11BlDRaAtkhgITNgTrFX3aQr13DQI2Emx/view?usp=drivesdk](url)

### System configuration

Asus rog ally

**Comment by Laggamer2005** [comment]
It seems to trigger when you hall of meat bail. Also, objects begin falling through the floor.

**Comment by FlexBy420** [comment]
You didn't post a correct log, you have to upload the log file from your RPCS3 folder.

**Comment by FlexBy420** [comment]
A lot of settings been changed, try default settings. I assume it's spu xfloat relaxed causing your issue.

**Comment by RipleyTom** [comment]
100% is, closing.
