### ISSUE TITLE
[Feature request] Support for third-party controllers with motion controls

### ISSUE THREAD

**Issue by segevfiner** [RPCS3/rpcs3#15433]
### Quick summary

I'm not sure if there is some support now... But it would be nice to support third-party controller that have motion controls, rather than only official PS controllers. For example, using a Nintendo Switch Pro Controller. It doesn't have pressure sensitive buttons, but it does have a gyro which can likely by used. SDL2 has support for using such controllers and could be an option.

**Comment by Megamouse** [comment]
This is already implemented
