### ISSUE TITLE
Tekken Tag Tournament 2 crashes on default settings

### ISSUE THREAD

**Issue by PCUser2021** [RPCS3/rpcs3#15437]
### Quick summary

The game doesn't even run and crashes on start. (this time everything is default and the emu and the game update are the latest)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14961790/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Stop opening low effort tickets. Settings are not default. This is not a support platform. If you do it again you'll get banned from our repository.
