### ISSUE TITLE
Tekken Tag Tournament 2 (USA) crashed!

### ISSUE THREAD

**Issue by PCUser2021** [RPCS3/rpcs3#15436]
### Quick summary

Everything is updated to the latest version (Win 11).

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14961695/RPCS3.log)

**Comment by FlexBy420** [comment]
Invalid issue, plenty of bad settings. Github is not a place for support request, ask on our discord or forum.
