### ISSUE TITLE
kamen rider battride war genesis

### ISSUE THREAD

**Issue by capzxzo** [RPCS3/rpcs3#15449]
### Quick summary

normally, to make a "in game" RPCS3 game playable for me, I ALWAYS GO on youtube and type: "certain game RPCS3 BEST SETTINGS", THIS is how i managed to play kamen rider battride war genesis so far for 3 whole years, until this afternoon, i identified a  few bugs, glitches and issues that didn't manifested back then.

### Details

The Riders In The Stage Selection Screen DON'T APPEAR

Elements On the Stage Selection Screen Don't Appear

The Denliner, Who Should appear, is glitched up

when picking a rider, his brief stage intro won't appear

enemies in game don't appear

the in game playable character becomes an amalgamation of the two riders selected, a box and the enemies

in game character will play A LOT of random sound effects when walking

the game will crash sometimes after picking a rider and choosing a state

### Build with regression

v.0.0.31-16332-78338623.7

### Attach two log files

E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/title/Title/TitleWord.ssa” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/title/Logo/Logo.spl” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/title/Logo/textures/starting_LogoBNG_CO.dds” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/title/Logo/textures/starting_8ing_logo_CO.dds” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/title/Logo/textures/starting_LogoBANDAI_CO.dds” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/title/Logo/textures/starting_Chuuikanki_CO.dds” [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/common/ConfirmDialog/ConfirmDialog.spl” [2]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/texture/menu/Figureseat01_CO.dds” [2]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/texture/menu/Figureseat02_CO.dds” [2]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/texture/menu/Figureseat03_CO.dds” [2]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/common/MenuHelp/MenuHelp.spl” [2]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/common/NowLoading/Saving.spl” [2]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/common/ConfirmDialog/ConfirmDialog.spl” [3]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/texture/menu/Figureseat01_CO.dds” [3]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/texture/menu/Figureseat02_CO.dds” [3]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/texture/menu/Figureseat03_CO.dds” [3]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/common/MenuHelp/MenuHelp.spl” [3]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJS10324/USRDIR/nativePS/ui/common/NowLoading/Saving.spl” [3]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E SYS: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [2]
E SYS: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [3]

### Attach capture files for visual issues

![img1](https://github.com/RPCS3/rpcs3/assets/166958470/e7d8c476-6b7f-4758-a623-a928060fd358)

![img2](https://github.com/RPCS3/rpcs3/assets/166958470/f3fd2338-ef68-4291-97b9-9def450ea40e)

![img3](https://github.com/RPCS3/rpcs3/assets/166958470/48ffbf5b-b710-4305-8a26-6b6fd162741d)

![img4](https://github.com/RPCS3/rpcs3/assets/166958470/f15306bb-f41c-473e-8886-38d789ef73a4)

**Comment by AniLeo** [comment]
The guidelines were completely ignored here, there are so many wrong things. Closing as Invalid.
