### ISSUE TITLE
[NPUA70080] God of War 3 E3 Demo - Crashes if default resolution is set to 720p

### ISSUE THREAD

**Issue by floppyD** [RPCS3/rpcs3#15459]
### Quick summary

The game crashes if you launch with default settings. Took me a while to figure out it was due to "Default Resolution". It seems like it's expecting 1080p.

If this isn't a bug then I guess the description should be changed, since clearly not "every" game supports 720p.

### Details

RPCS3 v0.0.31-16338-e48ec758 Alpha | master

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14973263/RPCS3.log)

### Attach capture files for visual issues

[output.webm](https://github.com/RPCS3/rpcs3/assets/29208110/b01af847-ccd4-4a9a-9464-1f9a75499384)

**Comment by AniLeo** [comment]
PARAM.SFO for the game declares support for 720p so it's supported.

Note that your report is invalid as is as you're injecting ReShade into the renderer, 3rd party injections can not be used in bug reports as they can easily cause issues like this.

**Comment by floppyD** [comment]
Yep, it was ReShade. Weird one since it worked for all the other games, even at 720p.
I wish there was native SMAA/FXAA support.
