### ISSUE TITLE
[Regression] Geometry bug in Resident Evil Code: Veronica HD

### ISSUE THREAD

**Issue by DMoguri** [RPCS3/rpcs3#15452]
### Quick summary

Background geometry remains static after camera changes

### Details

Background geometry remains completely static even after camera changes while dynamic objects (characters, enemies, NPCs, items) work normally. It's quite trippy and hard to describe, the only way to see it would be in a video.
Seems to be caused by #15421, tested the next build previous to that one and everything worked fine. Everything with default configuration. Seems to be related to #15445 aswell

![image](https://github.com/RPCS3/rpcs3/assets/44389337/33024177-5768-4377-99de-e41b183378e3)
![image](https://github.com/RPCS3/rpcs3/assets/44389337/d9819156-c0e9-4d00-9c42-850081264cc1)

https://github.com/RPCS3/rpcs3/assets/44389337/97b66044-5e72-43b4-95cf-924a0d1adc40

### Build with regression

v0.0.31-16323-d6f6752a

### Attach two log files

[RPCS3-v0.0.31-16323-d6f6752a-(BAD).log.gz](https://github.com/RPCS3/rpcs3/files/14971478/RPCS3.log.gz)
[RPCS3-v0.0.31-16319-0231902a-(GOOD).log.gz](https://github.com/RPCS3/rpcs3/files/14971491/RPCS3.log.gz)

### Attach capture files for visual issues

[NPJB00135_20240414184746_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/14971470/NPJB00135_20240414184746_capture.rrc.gz)

### System configuration

OS: Windows 11 build 22631.3447
CPU: i7-10700K
GPU: RTX 3060Ti - driver version 551.61

### Other details

Issue happens in all 3 game versions (EU, US, JP)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/15453
