### ISSUE TITLE
NPEB01363-[soul calibur 5]

### ISSUE THREAD

**Issue by Soul1399** [RPCS3/rpcs3#1545]
Hello.
I've tried Soul Calibur 5. It might have some bad configuring.

Anyway, this message is just **FYI**

[REDACTED LOG SPAM]

**Comment by tambry** [comment]
Bad configuring? You're trying to run Soul Calibur 5.
Such useless reports are more fit for [the forum](http://www.emunewz.net/forum/forumdisplay.php?fid=162).
You should probably grab the module files from /dev_flash/sys/external/ from your PS3 and then decrypt them and place them in the same folder for RPCS3 and then enable cellSre and cellSpursJq from LLE modules manager.

**Comment by Soul1399** [comment]
... first time I use it.
I saw many TODO so I thought it wouldn't be "useless".

Anyway thanks for your useful reply

**Comment by tambry** [comment]
There's literally **thousands** of TODOs. You can start up any random game and see a whole slew of them.

**Comment by SrPacman** [comment]
Hey did u fix the problem? I'm trying the same and can't play, only a black window and only this Error: "E {PPU[0x1c] Thread (mainThread)[0x00b4d3f8]} sceNp: sceNpBasicRegisterContextSensitiveHandler" @Soul1399 @tambry
