### ISSUE TITLE
inFamous 1 texture massive bug

### ISSUE THREAD

**Issue by CrimsonCarl** [RPCS3/rpcs3#15458]
### Quick summary

So when I booted up inFamous and configured it, it worked fine, few audio stutters here and there but I wasn't too worried about it. Then when I booted it up the next day, the game goes buck-wild on me. Still fairly new to this emu so any help with this would be highly appreciated.

### Details

![BCUS98119_screenshot_2024_04_14_17_03_08](https://github.com/RPCS3/rpcs3/assets/106453897/70aea0d7-a411-416a-bff8-321f98ced16f)

### Build with regression

v0.0.3.1-16338-e48ec758 Alpha

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14972903/RPCS3.log)

**Comment by JimScript** [comment]
This is a duplicate issue of #15445, which was supposed to be fixed recently but wasn't somehow.
