### ISSUE TITLE
Build problem on Linux Ubuntu 15.10

### ISSUE THREAD

**Issue by rcaridade145** [RPCS3/rpcs3#1547]
CMake Error at CMakeLists.txt:18 (add_subdirectory):
  The source directory

    /home/rui/Programacao/rpcs3/asmjit

  does not contain a CMakeLists.txt file.

`CMake Error at CMakeLists.txt:19 (add_subdirectory):
  The source directory

    /home/rui/Programacao/rpcs3/libpng

  does not contain a CMakeLists.txt file.

CMake Error at Vulkan/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    /home/rui/Programacao/rpcs3/Vulkan/glslang

  does not contain a CMakeLists.txt file.

CMake Error at Vulkan/CMakeLists.txt:8 (add_subdirectory):
  The source directory

    /home/rui/Programacao/rpcs3/Vulkan/Vulkan-LoaderAndValidationLayers

  does not contain a CMakeLists.txt file.`

**Comment by tambry** [comment]
Please read the [README](https://github.com/RPCS3/rpcs3/blob/master/README.md).
You need to initialize the submodules.

**Comment by rcaridade145** [comment]
I did. I got mistaken by the rpcs3 folder git clone created. I cd'ed into rpcs3 folder created by git clone not the rpcs3 inside the rpcs3 folder.
Sorry for the noise :) And thank you for answer
