### ISSUE TITLE
Ratchet & Clank Crack in time visual issues

### ISSUE THREAD

**Issue by RinMaru** [RPCS3/rpcs3#15472]
### Quick summary

Light sources and explosens cause texture issues such as shown. 

![Screenshot 2024-04-16 183217](https://github.com/RPCS3/rpcs3/assets/15071652/3e3476aa-111c-41bd-b765-dbf7888aa214)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15015983/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1OxiUGgqpxPoNO_oID1g2M027zz2pTwC0/view?usp=sharing

### System configuration

win11 
GPU rx6700xt 
CPY Ryzen5 5600X

**Comment by kd-11** [comment]
This is definitely a recent regression after the restructuring.

**Comment by segevfiner** [comment]
https://github.com/RPCS3/rpcs3/pull/15589 might have fixed this one as well, needs a test.

**Comment by kd-11** [comment]
I forgot to close this one. It should be fixed.
