### ISSUE TITLE
[Regression] Home overlay uses trophy notification sound instead of "cursor" sound after you get a trophy ingame

### ISSUE THREAD

**Issue by FlexBy420** [RPCS3/rpcs3#15478]
### Quick summary

https://github.com/RPCS3/rpcs3/assets/68403300/43f3d392-70a6-4b53-8420-eb728d452173

### Details

Should probably be reported on Qt since it's very likely their bug than RPCS3.

### Build with regression

v0.0.31-16237 (#15351)

### Attach two log files

[Broken](https://github.com/RPCS3/rpcs3/files/15027099/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Try with the qt 6.7.0 PR

**Comment by FlexBy420** [comment]
Issue still persist.

**Comment by FlexBy420** [comment]
Confirmed to be fixed by #15482
