### ISSUE TITLE
Can't get my local build working

### ISSUE THREAD

**Issue by PawelGribov** [RPCS3/rpcs3#15489]
### Quick summary

Local windows build throws exception on XMB launch.

### Details

Windows 11 23H2, just following guide https://github.com/RPCS3/rpcs3/blob/master/BUILDING.md,
all dependencies are here:
- cmake 3.29.2
- Python 3.9.1
- Qt 6.6.3
- VS 2022 (17.9.6)
- Vulkan SDK 1.3.268.0.

Same behavior both for Debug and Release build (rpcs3 is at https://github.com/RPCS3/rpcs3/commit/14e9c8954c051c583a33f54ecf1e997c8c03db35):

I install firmware 4.91, it starts XMB, compiles all modules and when it asks to press X first time, rpcs3 throws
"exception at address 0x00007FFA93D0F96C (vcruntime140d.dll) in rpcs3d.exe: 0xC0000005: Write access violation at address 0x00000003C3EE0050"
rpcs3\rpcs3\Emu\RSX\NV47\HW\nv308a.cpp : 103

![screenshot_2024-04-20 173611](https://github.com/RPCS3/rpcs3/assets/22625282/91947fc8-2264-4fa9-a5b9-4c33ea8de0e0)

But this build is working normally https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-14e9c8954c051c583a33f54ecf1e997c8c03db35/rpcs3-v0.0.31-16365-14e9c895_win64.7z

Just trying to understand where the issue can be (probably some other dependencies are incompatible), maybe missing some information.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15048618/RPCS3.log)

### System configuration

Windows 11 23H2
CPU: Ryzen 7 5800x3d
RAM: 32GB
GPU: RTX 4090 (driver 552.22)

**Comment by elad335** [comment]
When it happens, uncheck this checkbox and press the sentence that says "continue" or "ignore this". No idea which is which in russian.
![image](https://github.com/RPCS3/rpcs3/assets/18193363/308cc14a-908b-4a6a-9723-a7d9cbe4ed86)

**Comment by PawelGribov** [comment]
Thanks! For some reason i had instant crash in Release build, but after ignoring exception in Debug build it also pass in Release.
