### ISSUE TITLE
In RPCS3 games are not working for me

### ISSUE THREAD

**Issue by chandradeepn** [RPCS3/rpcs3#15504]
### Quick summary

So i installed rpcs30.03-16736-b8165af0 in my personal computer and downloaded ps3update.pup 4.19v and i installed devil may cry game mount it and copy the game mount data and paste into game folder then opened the game in rpcs3 then after loading and compiling ppu modules it is giving me like i cant play the game

### Details

U SPU TODO: [__spu-0x0ab20-juw7dGAu3AFRjvKzv9XkGaWV8Rwv:0x0abd0] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x0ab20-juw7dGAu3AFRjvKzv9XkGaWV8Rwv:0x0afc8] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x0ab20-juw7dGAu3AFRjvKzv9XkGaWV8Rwv:0x0b0cc] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x03ed0-k8zrL0QGXhbSeaVzRpMwMrt6wXe1:0x04268] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x03ed0-k8zrL0QGXhbSeaVzRpMwMrt6wXe1:0x045e8] Unmatched spu_re(b) found in FMA

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15119215/RPCS3.log.gz)

### System configuration

Device name	NAGDEEP
Processor	AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx     2.10 GHz
Installed RAM	8.00 GB (7.44 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
windows
Edition	Windows 11 Home Single Language
Version	23H2
Installed on	‎15-‎07-‎2023
OS build	22631.3527

**Comment by AniLeo** [comment]
Closed blatantly invalid ticket, this is not a support platform, this is for bug reports
