### ISSUE TITLE
[Regression] LBP games freezing when connected online

### ISSUE THREAD

**Issue by ItsLaguna** [RPCS3/rpcs3#15510]
### Quick summary

Since build v0.0.31-16377-08c3a38b ( #15497 ) all the LittleBigPlanet games eventually crash/freeze while connected to custom servers.

Simply being connected to RPCN eventually freezes the game and can lead to the emulator getting locked. 
The timing for this to happen seems to be random if the player plays normally, but I've personally found staying AFK in the Pod the best way to trigger this issue.

It's worth mentioning that if RPCN is disabled (and by extension any access to online features) the issue doesn't happen.

### Build with regression

RPCS3 v0.0.31-16377-08c3a38b

### Attach two log files

[LBPLogs.zip](https://github.com/RPCS3/rpcs3/files/15135897/LBPLogs.zip)

### System configuration

- OS: Windows 10 Pro
- CPU: Ryzen 7 5800X
- RAM: 32 GB
- GPU: Nvidia RTX 2060
- Driver version: 546.17.0.0

**Comment by RipleyTom** [comment]
Reverted in https://github.com/RPCS3/rpcs3/pull/15511
