### ISSUE TITLE
[Bug] Wrong key behaviour while typing on keyboard

### ISSUE THREAD

**Issue by ItsLaguna** [RPCS3/rpcs3#15516]
### Quick summary

Some keys don't work / don't work as intended.

### Details

With the recent changes to the keyboard ( #15506 ), Caps Lock (sort of) and Backspace now work as they should, however some issues were also introduced. Tested while playing Metal Gear Online but might affect other games.

**Keys that aren't working (at all or properly):**

Tab (used to switch between /all and /team chat)
Arrows (in MGO Arrow Key Up / Down go through a history of sent messages by the player, Up going to older ones and Down to the most recent, including the current one being typed. Left and Right work as intended)
Caps Lock works but also acts as Shift while enabled
F1 to F12 (used as text macros)
` requires the user to press twice, while realhw requires one press
' (") same as above

**While Caps Lock is disabled:**

; types ; and acts as F2
= types = and acts as F4

**While Caps Lock is enabled (acts as Shift too as pointed out before, makes other keys act differently):** 

Shift + 0 deletes the whole message
2 types @ and acts as F7 
= types + and acts as Tab on each press
E types E and acts as F12
R on each press goes back to other typed messages (it's acting as one of the arrow keys)
A types A and acts as F8
D types D and acts as F11
; types : and acts as F1
C types C and acts as F10
B types B and acts as F9
, types < and acts as F3
. types > and acts as F5
/ types ? and acts as F6

There's also another issue where Caps Lock keeps the last state it received if changed outside of the emulator, e.g:
You enable Caps Lock, go outside RPCS3, disable Caps Lock and type, you'll still type in uppercase.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15139608/RPCS3.log)

### System configuration

- OS: Windows 10 Pro
- CPU: Ryzen 7 5800X
- RAM: 32 GB
- GPU: Nvidia RTX 2060
- Driver version: 546.17.0.0

**Comment by Megamouse** [comment]
Yes, I've also noticed some nonsense.
I'll try to look at it soon
