### ISSUE TITLE
[Feature request] export software manual

### ISSUE THREAD

**Issue by xenyou** [RPCS3/rpcs3#15520]
### Quick summary

It would be nice if I could export software manual as pdf or some image files.

PS3 builtin viewer sucks to use.

![Screenshot 2024-04-28 at 14 21 18](https://github.com/RPCS3/rpcs3/assets/832358/b1d6d829-ffed-4ef7-acbf-d23807452362)

**Comment by Megamouse** [comment]
It's called the explorer and you can do that yourself.

**Comment by xenyou** [comment]
> It's called the explorer and you can do that yourself.

Does rcps3 have the function called explorer to convert DOCUMENT.DAT to images or PDF?
Or it just mean that I should analysis the DOCUMENT.DAT myself?

**Comment by MSuih** [comment]
This really should be done as an external tool and not implemented into rpcs3 directly

**Comment by xenyou** [comment]
@MSuih 

Thank you. I understood.
