### ISSUE TITLE
Cannot boot Unity games with PPU LLVM

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#15524]
### Quick summary

Unity engine games such as `Lost in the Rain` currently cannot be booted with PPU LLVM. Booting the game with PPU Interpreter allows it to be Playable.

### Details

The emulator hangs on a black screen during the game boot. Previously it crashed on boot, but #15477 solved the crash.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15143245/RPCS3.log.gz)

### System configuration

```
﻿RPCS3 v0.0.31-16389-430b5783 Alpha | HEAD
AMD Ryzen 9 5900HX with Radeon Graphics | 16 Threads | 15.01 GiB RAM | TSC: 3.294GHz | AVX+ | FMA3
Operating system: POSIX, Name: Linux, Release: 6.8.5-1-MANJARO, Version: #1 SMP PREEMPT_DYNAMIC Wed Apr 10 20:15:45 UTC 2024
Qt version: Compiled against Qt 6.6.3 | Run-time uses Qt 6.6.3
```

**Comment by Xeolix** [comment]
Games: Back to Bed [NPUB31732], CounterSpy™ [NPUA80870]
The same bug, build RPCS3 v0.0.32-16430-04d6ff27 Alpha | master

**Comment by KushiAsHimself** [comment]
same goes for NPEA00394 (rain). changing the PPU Decoder to static and SPU Decoder to ASMJIT does fix the problem.

**Comment by AniLeo** [comment]
Confirmed as fixed

![image](https://github.com/RPCS3/rpcs3/assets/10283761/45a5ac66-1450-435d-b7c9-fb16bfb3744e)
