### ISSUE TITLE
Way Of The Samurai 3 - BLES00712 - Missing Text In Menu And Gameplay 

### ISSUE THREAD

**Issue by Anomalous01** [RPCS3/rpcs3#15536]
### Quick summary

Game loads fine and plays fine but looking through the options and there is missing text and during gameplay speaking to npcs shows that a lot of the dialogue is missing, everything else works, so I have no idea what could be causing the issue

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15157698/RPCS3.log)

### Attach capture files for visual issues

![BLES00712_screenshot_2024_04_29_21_54_44](https://github.com/RPCS3/rpcs3/assets/164743750/a5bccbe7-72a0-4e1e-a674-cec96e238b55)
![BLES00712_screenshot_2024_04_29_21_53_15](https://github.com/RPCS3/rpcs3/assets/164743750/3e53f285-7b4f-4e5a-a7bf-04ac4a824a18)

**Comment by mysteria25** [comment]
It seems enabling "Disable vertex cache" in the Advanced menu fixes it


![BBB](https://github.com/RPCS3/rpcs3/assets/80365365/7d965f78-ea5f-4901-87ba-a99359348d15)


![BB](https://github.com/RPCS3/rpcs3/assets/80365365/e561f63e-0082-4e0e-941c-288b5aab492a)

**Comment by Anomalous01** [comment]
Thanks a lot for the help, I was really looking forward to playing this game but without the text dialogue, It felt pointless so thanks you saved my playthrough of the game
