### ISSUE TITLE
[Feature request] [RPCN] Change email address

### ISSUE THREAD

**Issue by user21944** [RPCS3/rpcs3#15537]
### Quick summary

Provide a means of changing the email address to which tokens will be sent (and remove the old address for privacy reasons)

### Details

There is currently no way to edit the email address associated with a given username.
I need to change my email address as I will not be able to access my current one in the future.

Alternatively, there should be a method to permanently delete your account and/or disassociate it from any email address.

**Comment by RipleyTom** [comment]
You technically don't need your email once you've created your account, just backup your rpcn.cfg or save your login/password and you'll never need your email address again. As for the email it's mainly there to make it annoying to create accounts and dodge bans.
So, no, not going to happen.

**Comment by Jeliciousz** [comment]
This makes it very annoying to completely switch from an old email to a new one if you need to keep the old email around just in case you lose that rpcn.cfg file and need to reset your RPCN password or resend your token.  You should do the bare minimum any other service does, and at least allow users to delete their RPCN account; for, like OP said, privacy reasons (many people don't want current or past emails or usernames permanently on file for services they don't use anymore), and so people can use their usernames for a new RPCN account with a new email.  Beyond the bare minimum, make it so people can change their username and their email (as long as they are already signed in and have their password, I assume the token could also be used for authentication purposes).

**Comment by UuBroot** [comment]
Same problem here. Back in the day i used a Gmail Email to register for RPCN and since then have switched to another Provider. Now, every time i want to login, i need to go back to Gmail, where i really do want to delete my account, just to get the access token when buying a new pc and reinstalling rpcs3. I don't think this is the way to go for RPCN in the long term since this is a common feature in most account systems.
