### ISSUE TITLE
PS Move remap changes seem to have no effect

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#15543]
### Quick summary

I'm using a real mouse to emulate PS move input in-game. Works fine using the hard-coded input below when enabling the feature via I/O tab:

o	Left click: T (shoot)
o	Right click: ~/Move button
o	Left + Right click: Select
o	Left + Middle click: Start 
o	Back: Circle
o	Middle + Right click: Triangle
o	Middle click: X 
o	Forward: Square

I see there's a new UI to remap:
<img width="272" alt="2024-05-01 11_29_08-RPCS3 0 0 32-16395-c16e176f Alpha _ master" src="https://github.com/RPCS3/rpcs3/assets/20983844/c32d7a76-0efd-44c0-a027-7f9d70240742">

But no matter what I do, I don't see any change in-game.  I would expect the following using the input above:

System Mouse     |     PS3 default   |   PS3  remap  
Left + Right click |        Select         |    Select > X

So now middle click, which executes PS3 X, should be Select for the in-game output but it's still Left+Right click. 

I tried going to Pad but neither pad or sys mouse respect the remapped button either. I tried various things but no matter what I try the 'system mouse' input mapping to ps3 buttons doesn't change. 

@Megamouse How is this supposed to work exactly? Seems like something is off.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15180188/RPCS3.log.gz)

### System configuration

Config:
Windows 10 64-bit
GeForce GTX 3070
AMD Ryzen 5900x
32GB RAM

**Comment by Megamouse** [comment]
Well. You're using the mouse move handler.
The dialog is for the fake move handler
