### ISSUE TITLE
[Regression] LittleBigPlanet games constantly crashing

### ISSUE THREAD

**Issue by TorutheRedFox** [RPCS3/rpcs3#15542]
### Quick summary

As of a few updates ago (not sure which, I haven't used RPCS3 in a while, I'm just going off other people's reports about it), LittleBigPlanet games crash constantly, most of the time before the game manages to even load.

### Build with regression

Unsure, need to investigate (was released around April 27th though)

### Attach two log files

current: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15179019/RPCS3.log.gz)
working: yet to isolate last working build

**Comment by TorutheRedFox** [comment]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00141/USRDIR/gamedata/audio/cries_in_the_wind.fsb” [2]
the game seems to be struggling to find files that do in fact exist

**Comment by AniLeo** [comment]
Many settings that are not defaults being used for no reason, modified elf too, invalid report as is.
Use base game with no modifications and only defaults and wiki settings when reporting these issues.

**Comment by TorutheRedFox** [comment]
I've looked further into the issue and something very odd is happening

the game doesn't crash, it just pauses at random, and pause cycling fixes it

**Comment by RedstoneGithub** [comment]
For me the same thing is happening, but pause cycling doesn't fix it. It just freezes indefinitely with music still playing, requiring a force shutdown of RPCS3. LBP2 runs fine on older builds (I am using ver 0.0.31-16371 for testing) and seems to be crashing on latest build (0.0.32-16407). The error I get was:
`E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98245_USER1/USRDIR/littlefart127” [1]`

**Comment by mickaelxd** [comment]
@RedstoneGithub did you figure it out? I'm having the same issue.
