### ISSUE TITLE
No window after editing custom game config, fixed by deleting CurrentSettings.ini

### ISSUE THREAD

**Issue by iamthehorker** [RPCS3/rpcs3#15559]
### Quick summary

RPCS3 will open to an invisible window after editing an existing custom game config. For example:

Right click on LBP2 > Change Custom Configuration > GPU > ZCULL Accuracy > Change to Precise from Approximate
Close and reopen RPCS3.
See the following.

![Screenshot from 2024-05-05 17-33-26](https://github.com/RPCS3/rpcs3/assets/29103770/2d81961a-cb68-48f5-a8a1-beb9f3e19226)

Issue does not occur consistently. Sometimes changing these settings causes no issue. When the issue occurs deleting CurrentSettings.ini fixes it. I have attached the contents of RPCS3.log as well as the contents of CurrentSettings.ini.

### Attach a log file

﻿RPCS3 v0.0.32-1-0fcb0b7d Alpha | master | local_build
AMD Ryzen 9 5950X 16-Core Processor | 32 Threads | 62.69 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
Operating system: POSIX, Name: Linux, Release: 6.8.8-1-default, Version: #1 SMP PREEMPT_DYNAMIC Mon Apr 29 05:24:46 UTC 2024 (5cd3298)
Qt version: Compiled against Qt 6.7.0 | Run-time uses Qt 6.7.0
Current Time: 2024-05-05T17:33:11
Initialization times before main(): 0.028134s
·! 0:00:00.000003 SYS: argc: 1, argv: 'rpcs3'
·! 0:00:00.000008 SYS: Maximum open file descriptors: 4096
·! 0:00:00.042605 UUID: Installation ID: {63a3b6ce-54d1-4469-beff-7521f694b06c}
·A 0:00:00.074511 {Vulkan Device Enumeration Thread} RSX: Found Vulkan-compatible GPU: 'AMD Radeon RX 7900 XTX (RADV NAVI31)' running on driver 24.0.6
·A 0:00:00.074530 {Vulkan Device Enumeration Thread} RSX: Found Vulkan-compatible GPU: 'llvmpipe (LLVM 17.0.6, 256 bits)' running on driver 0.0.1
·! 0:00:00.075681 CFG: Setting the default renderer to Vulkan. Default GPU: 'AMD Radeon RX 7900 XTX (RADV NAVI31)'
·! 0:00:00.075699 SYS: Setting user ID '00000001'
·! 0:00:00.079725 VFS: VFS config missing. Using default settings. Path: /home/hunter/.var/app/net.rpcs3.RPCS3/config/rpcs3/vfs.yml
·! 0:00:00.079773 SYS: Using VFS config:
$(EmulatorDir): ""
/dev_hdd0/: $(EmulatorDir)dev_hdd0/
/dev_hdd1/: $(EmulatorDir)dev_hdd1/
/dev_flash/: $(EmulatorDir)dev_flash/
/dev_flash2/: $(EmulatorDir)dev_flash2/
/dev_flash3/: $(EmulatorDir)dev_flash3/
/dev_bdvd/: $(EmulatorDir)dev_bdvd/
/games/: $(EmulatorDir)games/
/app_home/: ""
/dev_usb***/:
  /dev_usb000:
    Path: $(EmulatorDir)dev_usb000/
    Serial: ""
    VID: ""
    PID: ""
·! 0:00:00.079779 VFS: Mounted path "/dev_hdd0" to "/home/hunter/.var/app/net.rpcs3.RPCS3/config/rpcs3/dev_hdd0/"
·! 0:00:00.079780 VFS: Mounted path "/dev_flash" to "/home/hunter/.var/app/net.rpcs3.RPCS3/config/rpcs3//dev_flash/"
·! 0:00:00.079781 VFS: Mounted path "/dev_flash2" to "/home/hunter/.var/app/net.rpcs3.RPCS3/config/rpcs3//dev_flash2/"
·! 0:00:00.079782 VFS: Mounted path "/dev_flash3" to "/home/hunter/.var/app/net.rpcs3.RPCS3/config/rpcs3//dev_flash3/"
·! 0:00:00.079783 VFS: Mounted path "/app_home" to "//"
·! 0:00:00.079786 VFS: Mounted path "/dev_usb000" to "/home/hunter/.var/app/net.rpcs3.RPCS3/config/rpcs3/dev_usb000/"
·! 0:00:00.079790 SYS: Applying global config: /home/hunter/.var/app/net.rpcs3.RPCS3/config/rpcs3//config.yml
·! 0:00:00.082345 SYS: Logged in as user '00000001' with the username 'User'
·! 0:00:00.082641 IPC: IPC config missing. Using default settings. Path: /home/hunter/.var/app/net.rpcs3.RPCS3/config/rpcs3/ipc.yml
·! 0:00:00.082649 SYS: Using IPC config:
IPC Server enabled: false
IPC Port: 28012
·A 0:00:00.082656 SYS: Firmware version: 4.90
·! 0:00:00.112673 GUI: Current language changed to English (en)
·! 0:00:00.115969 Compat: Finished reading database from file: /home/hunter/.var/app/net.rpcs3.RPCS3/config/rpcs3/GuiConfigs/compat_database.dat
·! 0:00:00.163742 GUI: Determined 'fusion' as default style
·! 0:00:00.167535 GUI: Changing stylesheet to 'default'
·! 0:00:00.167539 GUI: Using default stylesheet
·! 0:00:00.288655 {TID: 49} SYS: Found EDAT file UP0005-NPUB30331_00-TRINE2LICENSE000.edat for trial game NPUB30331
·! 0:00:00.288652 {TID: 29} SYS: verify_c00_unlock_edat(): '/home/hunter/.var/app/net.rpcs3.RPCS3/config/rpcs3/dev_hdd0/home/00000001/exdata/UP2015-NPUB30181_00-CASTLECRASHERS02.edat' not found

### System configuration
Running latest flatpak on openSUSE Tumbleweed.

- SYS: RPCS3 v0.0.32-1-0fcb0b7d Alpha | master | local_build
- SYS: AMD Ryzen 9 5950X 16-Core Processor | 32 Threads | 62.69 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 6.8.8-1-default, Version: #1 SMP PREEMPT_DYNAMIC Mon Apr 29 05:24:46 UTC 2024 (5cd3298)
- SYS: Current Time: 2024-05-05T17:40:17
- RSX: Found Vulkan-compatible GPU: 'AMD Radeon RX 7900 XTX (RADV NAVI31)' running on driver 24.0.6
- RSX: Found Vulkan-compatible GPU: 'llvmpipe (LLVM 17.0.6, 256 bits)' running on driver 0.0.1
- SYS: Firmware version: 4.90

### CurrentSettings.ini

[Config]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\xff\xff\xff\xf5\xff\xff\xff\xcf\0\0\x4I\0\0\x3\xd9\0\0\0\0\0\0\0\0\0\0\x4>\0\0\x3\xce\0\0\0\x1\0\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x4>\0\0\x3\xce)

[Debugger]
splitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\xff\xff\xff\xff\xff\xff\xff\xff\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)

[GSFrame]
geometry=@Rect(0 0 2560 1440)
screen=1
visibility=5

[GameList]
hidden_list=@Invalid()
iconColor=@Variant(\0\0\0\x43\x1\xff\xff\xf0\xf0\xf0\xf0\xf0\xf0\0\0)
marginFactor=0.09
sortAsc=true
sortCol=13
state=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\r\x1\0\0\0\0\0\0\0\0\0\0\0\xfH\x6\0\0\0\x4\0\0\0\t\0\0\0\x96\0\0\0\x3\0\0\0\x96\0\0\0\n\0\0\0\x96\0\0\0\x6\0\0\0\x96\0\0\t\xf2\0\0\0\xf\0\x1\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\x96\xff\xff\xff\xff\0\0\0\x1\0\0\0\0\0\0\0\xf\0\0\0]\0\0\0\x1\0\0\0\x2\0\0\x1\x8c\0\0\0\x1\0\0\0\0\0\0\0x\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0y\0\0\0\x1\0\0\0\0\0\0\0\x9a\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\xbc\0\0\0\x1\0\0\0\0\0\0\x1&\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x9a\0\0\0\x1\0\0\0\0\0\0\0\x98\0\0\0\x1\0\0\0\0\0\0\0\xd0\0\0\0\x1\0\0\0\0\0\0\x2\x9a\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1\0\0\0\x93\0\0\0\0)
textFactor=2
visibility_column_category=true
visibility_column_compat=true
visibility_column_dir_size=true
visibility_column_firmware=false
visibility_column_icon=true
visibility_column_last_play=true
visibility_column_move=true
visibility_column_name=true
visibility_column_parental=false
visibility_column_path=false
visibility_column_playtime=true
visibility_column_resolution=true
visibility_column_serial=true
visibility_column_sound=false
visibility_column_version=true

[Localization]
language=en

[Logger]
ANSI_code=true
ERR_stack=true
level=4
stack=true

[Meta]
attachCommandLine=false
discordState=
showDebugTab=false
useRichPresence=true

[Patches]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\xc0\0\0\0]\0\0\b\xd5\0\0\x4\x88\0\0\x1\xcb\0\0\0\x8e\0\0\b\xca\0\0\x4}\0\0\0\x1\0\0\0\0\n\0\0\0\x1\xcb\0\0\0\x8e\0\0\b\xca\0\0\x4})
splitter_state=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x4\xd7\0\0\x2\x13\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)

[main_window]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\n\0\xff\xff\xff\xda\0\0\x13\xff\0\0\x5y\0\0\n\x1\0\0\0\x19\0\0\x11\0\0\0\x4\b\0\0\0\0\x2\0\0\0\n\0\0\0\n\0\0\0\0\0\0\0\x13\xff\0\0\x5y)
infoBoxEnabledWelcome=false
mwState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x2\0\0\0\0\0\0\n\0\0\0\x5$\xfc\x2\0\0\0\x2\xfb\0\0\0\x10\0g\0\x61\0m\0\x65\0l\0i\0s\0t\x1\0\0\0\0\0\0\x4.\0\0\0`\0\xff\xff\xff\xfb\0\0\0\f\0l\0o\0g\0g\0\x65\0r\x1\0\0\x4\x34\0\0\0\xf0\0\0\0\xa2\0\xff\xff\xff\0\0\0\x1\0\0\0\0\0\0\0\0\xfc\x2\0\0\0\x1\xfb\0\0\0\x10\0\x64\0\x65\0\x62\0u\0g\0g\0\x65\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\xd4\0\xff\xff\xff\0\0\0\0\0\0\x5$\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)
recentGamesNames=@ByteArray(\0\0\0\x2\0\0\0\xb6\0/\0h\0o\0m\0\x65\0/\0h\0u\0n\0t\0\x65\0r\0/\0.\0v\0\x61\0r\0/\0\x61\0p\0p\0/\0n\0\x65\0t\0.\0r\0p\0\x63\0s\0\x33\0.\0R\0P\0\x43\0S\0\x33\0/\0\x63\0o\0n\0\x66\0i\0g\0/\0r\0p\0\x63\0s\0\x33\0/\0\x64\0\x65\0v\0_\0h\0\x64\0\x64\0\x30\0/\0g\0\x61\0m\0\x65\0/\0\x42\0\x43\0U\0S\0\x39\0\x38\0\x31\0\x35\0\x35\0/\0U\0S\0R\0\x44\0I\0R\0/\0\x45\0\x42\0O\0O\0T\0.\0\x42\0I\0N\0\0\0J\0M\0O\0T\0O\0R\0S\0T\0O\0R\0M\0\xae\0:\0 \0P\0\x41\0\x43\0I\0\x46\0I\0\x43\0 \0R\0I\0\x46\0T\0 \0[\0\x42\0\x43\0U\0S\0\x39\0\x38\0\x31\0\x35\0\x35\0]\0\0\0\x90\0/\0r\0u\0n\0/\0m\0\x65\0\x64\0i\0\x61\0/\0h\0u\0n\0t\0\x65\0r\0/\0S\0S\0\x44\0\x32\0/\0p\0s\0\x33\0/\0\x44\0\x65\0m\0o\0n\0'\0s\0 \0S\0o\0u\0l\0s\0 \0(\0U\0S\0\x41\0)\0/\0P\0S\0\x33\0_\0G\0\x41\0M\0\x45\0/\0U\0S\0R\0\x44\0I\0R\0/\0\x45\0\x42\0O\0O\0T\0.\0\x42\0I\0N\0\0\0\x32\0\x44\0\x65\0m\0o\0n\0'\0s\0 \0S\0o\0u\0l\0s\0 \0[\0\x42\0L\0U\0S\0\x33\0\x30\0\x34\0\x34\0\x33\0])
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\n\0\0\0\x5$\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x14\0m\0w\0_\0t\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

**Comment by Megamouse** [comment]
Not using an official build
