### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by thx3ever** [RPCS3/rpcs3#1555]
How can i remove asmjit and llvm from project? I want to buiild the source on Windows 10 with Intel C++ Compiler, i need only spu with not asmjit and ppu with no asmjit llvm build
I want only interpreter ppu 1 and 2 and spu interpreter 1 and fast

**Comment by tambry** [comment]
You can choose not to compile LLVM by simply selecting a non-LLVM configuration. Asmjit is required for now.
Why would you want to build without asmjit?

**Comment by thx3ever** [comment]
To see what perfomance i get compiling the source with Intel C++ Compiler and IPP Librarys

**Comment by thx3ever** [comment]
can i compile asmjit without LLVM?

**Comment by tambry** [comment]
@thx3ever Asmjit is completely different from LLVM. There's no reason you shouldn't be able to compile it without LLVM.

**Comment by thx3ever** [comment]
Ok
