### ISSUE TITLE
[Feature request] Editable timestamps for unlocked trophies

### ISSUE THREAD

**Issue by mavethee** [RPCS3/rpcs3#15551]
### Quick summary

Editable timestamps for unlocked trophies.

### Details

Allow users to edit timestamps of earned trophies in Trophy Manager.

**Comment by Megamouse** [comment]
But why?

**Comment by mavethee** [comment]
As we can already unlock and lock back trophies in Trophy Manager it would be nice thing to see as well.

**Comment by Megamouse** [comment]
But why?

**Comment by elad335** [comment]
I don't agree with this feature eitger.

**Comment by Jack54guythecoder** [comment]
But maybe you can pretend you unlocked a trophy and edit the info there.

**Comment by mavethee** [comment]
Yeah, well I came with that idea after although I've met criteria for a trophy it wasn't poping up, even trying from scratch so I've unlocked it in Trophy Manager but timestamps thing bothers me as it isn't much chronological now, I swear paying attention to minor things will kill me someday.
