### ISSUE TITLE
Call of Duty Classic crashes when shellshocked

### ISSUE THREAD

**Issue by lvl1337** [RPCS3/rpcs3#15550]
### Quick summary

It seems that the moment the "motion blur" effect triggers, RPCS3 entirely crashes. Log file mentions something about a cache miss.
https://youtu.be/ijHO9gVOzks

### Details

Reproduce Bugs
=============
1
==
1. Load up burnville level. (Level 2)
2. Walk in a straight line as seen in video until you get hit by artillery.
3. Try again if you don't get hit.

Emulator Version
==============
0.0.32-16396-f1ef3bdc Alpha | master
Firmware: 4.91

System
======
AMD Ryzen 7 7840HS @ 3.8 GHz
16 GB (8x2) DDR5 Memory @ 5600 MHz
NVIDIA GeForce RTX 4060 Laptop GPU @ 8 GB Memory
1 TB NVME SSD
Windows 11 IoT Enterprise @ amd64 (64-bit) @ 22631.3447 (23H2)

Emulator Settings
==============
(Bugs in video also happen under default settings)

GPU Tab
=======
Resolution Scale: 150% (1920x1080)
Asynchronous Texture Streaming: Enabled
Write Color Buffers: Enabled

Advanced Tab
===========
Accurate RSX reservation access: Enabled
RSX FIFO Accuracy: Atomic

Everything else was left at the defaults.

Game Information
==============
Name: Call of Duty Classic
ID: NPEB00101
Version: 01.00
Category: HDD Game

note: log file is attached after an update but the issue remains the same.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15209699/RPCS3.log)

### System configuration

System
======
AMD Ryzen 7 7840HS @ 3.8 GHz
16 GB (8x2) DDR5 Memory @ 5600 MHz
NVIDIA GeForce RTX 4060 Laptop GPU @ 8 GB Memory
1 TB NVME SSD
Windows 11 IoT Enterprise @ amd64 (64-bit) @ 22631.3447 (23H2)

**Comment by RipleyTom** [comment]
Duplicated of https://github.com/RPCS3/rpcs3/issues/14170
