### ISSUE TITLE
Skydive: Proximity Flight [NPUB30618] - graphics

### ISSUE THREAD

**Issue by seanarim0** [RPCS3/rpcs3#15563]
### Quick summary

Trouble rendering environment graphics. Using RPCS3 default settings.

### Details

Game mode: Freestyle, Daytime: Day, Weather: Clear.
Reloading the game can slightly improve rendering quality but only on the first loaded level (see last 2 screenshots, compared with first 2 screenshots).

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15233038/RPCS3.log)

### Attach capture files for visual issues

![NPUB30618_screenshot_2024_05_07_09_33_18](https://github.com/RPCS3/rpcs3/assets/167751307/e5d86903-94bf-4def-b9ae-53cc8d6ca5bb)
![NPUB30618_screenshot_2024_05_07_09_33_09](https://github.com/RPCS3/rpcs3/assets/167751307/a02d1ae6-7043-4550-b1fa-e6c44bf77f3e)
![NPUB30618_screenshot_2024_05_07_09_32_33](https://github.com/RPCS3/rpcs3/assets/167751307/0c56582a-c1f1-44bb-9c82-d829ee1574ce)
![NPUB30618_screenshot_2024_05_07_09_32_25](https://github.com/RPCS3/rpcs3/assets/167751307/cd2a82cd-78b7-4bfc-925d-f9b2f2b421b6)
![NPUB30618_screenshot_2024_05_07_09_32_06](https://github.com/RPCS3/rpcs3/assets/167751307/2f714e4f-87aa-475e-8fb2-5036e6d73e58)
![NPUB30618_screenshot_2024_05_07_09_31_58](https://github.com/RPCS3/rpcs3/assets/167751307/4f95ce24-f3cf-4a7e-8c90-3a6afa1029ef)
![NPUB30618_screenshot_2024_05_07_09_34_47](https://github.com/RPCS3/rpcs3/assets/167751307/01b523cc-9f82-4719-9195-fbfdc009b8f3)
![NPUB30618_screenshot_2024_05_07_09_34_39](https://github.com/RPCS3/rpcs3/assets/167751307/493d239e-763a-442e-81bd-a5ff12ee5eec)

### System configuration

RPCS3 Version: 0.0.32-16430-04d6ff27 Alpha | master

CPU:          Intel(R) Core(TM) i5-10400F CPU
OS Platform:  Windows 10
GPU Model:    NVIDIA GeForce RTX 3050/PCIe/SSE2
Driver:       4.0.0 NVIDIA 551.76

**Comment by mysteria25** [comment]
Requires Write Color Buffers-

https://github.com/RPCS3/rpcs3/assets/80365365/3c8fdcc7-bb8d-444f-b88c-8a4340df1e2e

**Comment by Triticum0** [comment]
Even with Wcb the broken textures still occur but is less frequent so the issue has been fixed
