### ISSUE TITLE
Guncon3 Emulation Mapping

### ISSUE THREAD

**Issue by magicray1028** [RPCS3/rpcs3#15573]
### Quick summary

Need a device class for Guncon3 Emulation to map mouse clicks to bypass calibration screens

### Details

Currently there is no way to bypass the calibration screens on Razing storm or time crisis 4 using guncon3 emulation with a gun4ir with 3 mouse buttons. Would it be possible to add a device class for Guncon3 so we can map it without interfering with pad controls?

**Comment by Florin9doi** [comment]
Please test with #15585

**Comment by Megamouse** [comment]
The real fix for mapping would be to add a config like most other emulated devices already have.

**Comment by Florin9doi** [comment]
The current solution should be enough for a single guncon3, which I udestand is the case here.
A config like other emulated devices would only add proper button labels (C1,C2), but I don't think it has support to map raw mouse buttons for multiple emulated devices.

**Comment by Megamouse** [comment]
The issue is that no one understands what is mapped anyway.
So adding at least the pad buttons would probably be a good compromise.

**Comment by Megamouse** [comment]
This is already implemented
