### ISSUE TITLE
Does not compile on Arch Linux with GCC 14.1

### ISSUE THREAD

**Issue by wantija** [RPCS3/rpcs3#15577]
### Quick summary

RPCS3 does not compile anymore from latest git using GCC 14.1

### Attach a log file

[rpcs3_build.log](https://github.com/RPCS3/rpcs3/files/15277069/rpcs3_build.log)

**Comment by Megamouse** [comment]
Please try the linked branch

**Comment by wantija** [comment]
yep that seems to have fixed it, thanks!
