### ISSUE TITLE
[Regression] LittleBigPlanet freezes / hangs (#15562)



### ISSUE THREAD

**Issue by EngineMachiner** [RPCS3/rpcs3#15575]
### Quick summary

The game freezes or hangs after playing or creating for a while. Audio can be heard after the freeze and the game doesn't crash.

No patches and just the default settings.

### Build with regression

Probably a build of this year? From January to March?

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15268667/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15268668/RPCS3.log)

**Comment by EngineMachiner** [comment]
I got it on LBP2 as well.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15268823/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15268824/RPCS3.log)

**Comment by EngineMachiner** [comment]
This happens frequently on LBP1 water levels as well.

**Comment by RedstoneGithub** [comment]
I have the same issue on LBP1 and LBP2

**Comment by GalaxyGaming2000** [comment]
Same issue

**Comment by Jupiter956** [comment]
Happening to me too.

**Comment by ikzoid** [comment]
Also having this happen.

**Comment by GalaxyGaming2000** [comment]
Still Testing but i think the regression is somehow caused by[ #15569](https://github.com/RPCS3/rpcs3/pull/15569) since i have no isuses playing on rpcs3 builds before it but i will have to see since it wouldnt make much sense for it to be this causing it

**Comment by RipleyTom** [comment]
The LBP2 logs above are set to Disconnected though.

**Comment by GalaxyGaming2000** [comment]
> The LBP2 logs above are set to Disconnected though.

oh yeah i didnt see that so either the crash i got while using that version coincidentally didn't happen while i was offline but it did while i was online sorry about that lol

**Comment by TorutheRedFox** [comment]
test the game while offline as a lot of private servers don't implement DEFLATE which causes large responses to corrupt the game's memory as the game expects a hard limit on uncompressed responses before the server compresses them

**Comment by jvyden** [comment]
> test the game while offline as a lot of private servers don't implement DEFLATE which causes large responses to corrupt the game's memory as the game expects a hard limit on uncompressed responses before the server compresses them

Note that this doesn't affect the major private servers; Refresh and Lighthouse both have DEFLATE implemented.

**Comment by GalaxyGaming2000** [comment]
yeah but the logs said it was disconnected and it happened while i was offline too

**Comment by devil-may-c0de** [comment]
I have not encountered this frequency of crashing on 0.0.31's build. After updating to 0.0.32, I've run into these problems. Not sure if this helps much, but it appears to be this most recent release

**Comment by GalaxyGaming2000** [comment]
i have been playing for like a week on version 0.0.32.16430 and i don't seem to be having the issue so it could be something after this one

**Comment by TorutheRedFox** [comment]
running a debug build of the game, every time it crashes, this is the last thing in the TTY log:
`delay acquiring mutex 'ShComms' 95003e00 retval = 8001000b`

**Comment by Arimotor** [comment]
Issue is still present

**Comment by Arimotor** [comment]
I have not encountered this issue in LBP3 in 0.0.32-16430, but did in 0.0.32-16431

**Comment by AniLeo** [comment]
PR is #15562, @RipleyTom

**Comment by TorutheRedFox** [comment]
the ShComms crash still seems to occur, but the game overall seems to crash less frequently

**Comment by elad335** [comment]
Test with #15692

**Comment by Arimotor** [comment]
Issue is now present in #15776

**Comment by AniLeo** [comment]
I highly doubt that PR caused such issue. And this ticket was already closed. You need to open a new regression report with the new relevant information.

**Comment by Mert5666** [comment]
it just happend for me on lbp2 liken a minute ago
