### ISSUE TITLE
(Question) Why the XMB compilation takes so long?

### ISSUE THREAD

**Issue by hardBSDk** [RPCS3/rpcs3#15580]
On my computer the XMB compilation takes much more time to finish than the games (maybe hours), while the games just take 1-5 minutes.

**Comment by AniLeo** [comment]
Missing details / log file, it's not normal for XMB to take more than an hour unless you have a really slow CPU as XMB has many more executables and libraries than games, which usually only have the main EBOOT and one extra self file at times, rarely more than that.

**Comment by hardBSDk** [comment]
@AniLeo My CPU is mid-end in a laptop (Intel i5 Skylake), the quantity of executables and libraries explain the long time to build, thanks.

**Comment by AniLeo** [comment]
That's a very low end CPU for RPCS3, it either has 2c/4t or 4c/4t, so the long compilation time is well expected. It is far below the recommended requirements.

**Comment by hardBSDk** [comment]
@AniLeo It has 4C/8T, I ran the God Of War Collection at 50fps years ago.

Something happened and the system requirements increased.
