### ISSUE TITLE
gs_gcm_cube.elf not rendering properly

### ISSUE THREAD

**Issue by MyaniPT** [RPCS3/rpcs3#1560]
Not rendering properly on my laptop, works normally on my desktop.
![screenshot_6](https://cloud.githubusercontent.com/assets/10283761/13652973/06f84cd6-e647-11e5-8172-fcdac46b07a8.png)
PPU Interpreter 1
SPU Interpreter 1
OpenGL (GPU doesn't support DX12)
1280x720
Microsoft Basic Render Driver / NVIDIA GeForce GT 330M

CPU: Intel Core i7 Q 740 (http://ark.intel.com/products/49024/Intel-Core-i7-740QM-Processor-6M-cache-1_73-GHz)
![screenshot_7](https://cloud.githubusercontent.com/assets/10283761/13653035/55927ae2-e647-11e5-8c7f-f6ee618d8a4a.png)

**Comment by MyaniPT** [comment]
Couldn't upload the .zip, so renamed the .log to .txt
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/166234/RPCS3.txt)
[TTY.txt](https://github.com/RPCS3/rpcs3/files/166235/TTY.txt)

**Comment by MyaniPT** [comment]
So I've been testing with all the bigpet builds to try and find which commit broke it.

**v0.0.0.6-448-g1e1c200** is the last bigpet build on which it renders correctly.
![screenshot_8](https://cloud.githubusercontent.com/assets/10283761/13654359/cc4d777e-e64f-11e5-9bf8-a1e796d0ef35.png)

**v0.0.0.6-454-gf66468f** is the following build on which this breaks.
![screenshot_9](https://cloud.githubusercontent.com/assets/10283761/13654360/cc4e9988-e64f-11e5-9a98-60ad12de9e10.png)

**Comment by vlj** [comment]
Your gpu is not supported, rpcs3 requires opengl 4.2 now. I think. 
Actually opengl requirement is a bit fuzzy atm so it might work sometimes with gl 3.3 but it's not guaranted. 

You can use dx12 software mode though.

**Comment by MyaniPT** [comment]
![screenshot_10](https://cloud.githubusercontent.com/assets/10283761/13654902/54919824-e653-11e5-933f-b154cf3b2e29.png)

Gotcha. Since it used to work in an older build, I thought it wasn't a dependencies issue.
It was only now that I noticed that this GPU only fully supports OpenGL 3.3 and doesn't fully support OpenGL 4.2+
