### ISSUE TITLE
Rock Band 3 Detecting additional user

### ISSUE THREAD

**Issue by Lazer-Khat** [RPCS3/rpcs3#15610]
### Quick summary

I am trying to play Rock Band 3 with my drums connected via USB. When I launch into the game, it says my drums are player 2 (connected via USB) and for some reason it is saying there is a vocalist as player one. I have no other controller connected and all the pads other than player 1 is null. When I launch the game, the controls for the drums enable both players and I cannot load a song with just drums.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15370511/RPCS3.log)

### System configuration

Aurora R7
Windows 11
Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz | 12 Threads | 63.82 GiB RAM | TSC: 3.192GHz | AVX+ | FMA3 | TSX-FA disabled by default
NVIDIA GeForce RTX 3060 running on driver 552.44.0.0

**Comment by Megamouse** [comment]
You have a controller for player 1 as mmjoy configured.

**Comment by Lazer-Khat** [comment]
> You have a controller for player 1 as mmjoy configured.

What should it be configured as?

**Comment by MSuih** [comment]
Set it to Null so that the player 1 slot is free and game can assign drums to it

**Comment by Lazer-Khat** [comment]
That solved it! Thanks
