### ISSUE TITLE
[Bug] ICON1.PAM not playing for certain games

### ISSUE THREAD

**Issue by Ninetime** [RPCS3/rpcs3#15614]
### Quick summary

Added ICON1.PAM is not working for some games.

### Details

Renamed an .mp4 to a ICON1.PAM file and added it to the dev_hdd0 for 2 games SOULCALIBUR Ⅱ HD ONLINE [NPEB01828] & SF3: Online Edition [NPUB30301]. After adding it to the SoulCalibur II folder, it plays correctly. For the SF3, it fails to play.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15393768/RPCS3.log.gz)

### Attach capture files for visual issues

File in question:
[ICON1.zip](https://github.com/RPCS3/rpcs3/files/15393786/ICON1.zip)
Example video
https://www.dropbox.com/scl/fi/mj107jvj56cm9emgao6cl/2024-05-21-13-56-25.mp4?rlkey=pjjeyz8qqs7h8qs9qmho1rrj9&dl=0

### System configuration

Windows 10 22H2
AMD Ryzen 7 5800X | 16 Threads | 31.92 GiB RAM | AVX+ | FMA3
GPU: AMD Radeon RX 6800 XT (24.3.1)

**Comment by FlexBy420** [comment]
That's not exactly a bug .PAM files are not just mp4 files
There's an entire guide on how to create ICON1.PAM files
https://consolemods.org/wiki/PS3:ICON1.PAM
also RPCS3 has custom image support
