### ISSUE TITLE
[Regression] God of War: Ascension RSX crashes (#15429)

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#15617]
### Quick summary

Starting the game, when you meet the first Fury, the game crashes

### Details

0.0.32-16500 - Works

0.0.32-16505 - Broken (crashes) https://github.com/RPCS3/rpcs3/pull/15429

### Build with regression

0.0.32-16505

### Attach two log files

Working
[GOW Ascension working.log](https://github.com/RPCS3/rpcs3/files/15408140/GOW.Ascension.working.log)

Broken
[GOW Ascension Crash.log](https://github.com/RPCS3/rpcs3/files/15407887/GOW.Ascension.Crash.log)

**Comment by solarmystic** [comment]
Confirmed, it freezes right during the first Fury encounter when she tortures Kratos 

![image](https://github.com/RPCS3/rpcs3/assets/4345150/66860389-41e7-49c7-9c9a-6dd2d228861b)

**Comment by elad335** [comment]
Retest with #15618

**Comment by elad335** [comment]
Closing, you can turn on RSX avcurate reservations and it should fix that as of #15618 ,Im interested if its also fixed withput it on latest build.
