### ISSUE TITLE
Struggling with Minecraft

### ISSUE THREAD

**Issue by Mer08** [RPCS3/rpcs3#15620]
### Quick summary

I've tried the Disc versions of the game, and it all seems to work fine until you try to load up a world. It gets stuck on initializing and doesn't work.
HDD version refuses to get unlocked. I have downloaded the .pkgs (Game + unlock DLC) from NoPayStation.
I have tried all regions of HDD and Disc except JP.
I have tried connecting to RPCN and pressing unlock but it says "There are no downloadable content offers of this type available for this title at the moment."

### Attach a log file

https://mega.nz/file/4XhRlbDQ#H1HFuNz_UCk8QKeTpTg7UfBgLh_9gCM3LcXh4UtBA1g

**Comment by AniLeo** [comment]
Removed pirated game support request.
