### ISSUE TITLE
[Regression] Puppeteer freezes at the start (#15429)

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#15635]
### Quick summary

Booting Puppeteer causes the game freezes and you can't pass the logos 

### Details

0.0.32-16500 - Working

0.0.32-16505 - Broken https://github.com/RPCS3/rpcs3/pull/15429

### Build with regression

0.0.32-16505

### Attach two log files

[Puppeteer Working.log](https://github.com/RPCS3/rpcs3/files/15462049/Puppeteer.Working.log)

[Puppeteer Broken.log](https://github.com/RPCS3/rpcs3/files/15462056/Puppeteer.Broken.log)

**Comment by gamrXerus** [comment]
I can confirm this regression also affects Call of Duty Black Ops 2. rpcs3-v0.0.32-16500 works but after PR #15429 it wont boot. If i compile modules from scratch it wont finish compile. I have i already had modules compiled from a previous build it wont get past the intro 
[BO2 Working.log](https://github.com/RPCS3/rpcs3/files/15504960/BO2.Working.log)
[BO2 Broken.log](https://github.com/RPCS3/rpcs3/files/15505015/BO2.Broken.log)
[BO2 Broken 2.log](https://github.com/RPCS3/rpcs3/files/15505016/BO2.Broken.2.log)

**Comment by Jonathan44062** [comment]
I can close now, since now is fixed
![image](https://github.com/RPCS3/rpcs3/assets/78843189/abc7667f-dccf-4d76-96c0-9157f82e75a4)
