### ISSUE TITLE
Weird log spam while playing Resistance 3

### ISSUE THREAD

**Issue by dougDuarte** [RPCS3/rpcs3#15630]
### Quick summary

When i'm playing Resistance 3 (version 01.05, wich is the latest for now), i keep getting logs every tick in the rpcs3 log tab. I don't know why and if it hurts the performance of the game, but it's weird.

### Details

Spam logs while playing:

U cellGem TODO: cellGemGetStatusFlags(gem_num=0, flags=*0x1313098)
U sys_net TODO: sys_net_bnet_recvmsg(s=26, msg=*0xd012bb40, flags=0x0) x3
U cellGem TODO: cellGemGetStatusFlags(gem_num=0, flags=*0x1313098)
U sys_net TODO: sys_net_bnet_recvmsg(s=26, msg=*0xd012bb40, flags=0x0) x3
U cellGem TODO: cellGemGetStatusFlags(gem_num=0, flags=*0x1313098)
U sys_net TODO: sys_net_bnet_recvmsg(s=26, msg=*0xd012bb40, flags=0x0) x4
U cellGem TODO: cellGemGetStatusFlags(gem_num=0, flags=*0x1313098)
U sys_net TODO: sys_net_bnet_recvmsg(s=26, msg=*0xd012bb40, flags=0x0) x3
U cellGem TODO: cellGemGetStatusFlags(gem_num=0, flags=*0x1313098)
U sys_net TODO: sys_net_bnet_recvmsg(s=26, msg=*0xd012bb40, flags=0x0) x4
U cellGem TODO: cellGemGetStatusFlags(gem_num=0, flags=*0x1313098)
U sys_net TODO: sys_net_bnet_recvmsg(s=26, msg=*0xd012bb40, flags=0x0) x2431

And so on...

### Attach a log file

No log file.

### System configuration

rtx 3060 12gb
i5 12400f
16gb ram ddr4
ssd m.2 2tb

**Comment by Jonathan44062** [comment]
This is not the place to ask for help, join the rpcs3 discord server

**Comment by dougDuarte** [comment]
> This is not the place to ask for help, join the rpcs3 discord server

This is not the place to report bugs? oO

**Comment by AniLeo** [comment]
Since when is a game calling a function inside a loop a bug? The log is doing exactly what it was added for. 

You didn't even follow the issue template, not that this is a valid bug nevertheless. The only way there could be a bug out of this is if there was a non negligible performance impact, but you'd have to provide some valid comparisons for that.
