### ISSUE TITLE
macOS Shortcut creation error: unable to add icon to bundle (probable easy fix)

### ISSUE THREAD

**Issue by Kurtjwest** [RPCS3/rpcs3#15631]
### Quick summary

Shortcuts on mac fail to be created successfully, encountering an error when attempting to add an icon to the shortcut bundle. App otherwise runs fine after creation as far as I am aware.

### Details

Log shows this error:
"E SYS: Failed to write icon file: /Users/user/Applications/RPCS3/Demon's Souls.app/Contents//Resources/shortcut.icns"

Maybe the double slash between Contents and Resources is the issue

### Attach a log file

https://github.com/RPCS3/rpcs3/files/14361292/RPCS3.log.zip
Log is from older version, but same error persists on most recent version.

### Attach capture files for visual issues

<img width="299" alt="Screenshot 2024-05-26 at 1 12 21 PM" src="https://github.com/RPCS3/rpcs3/assets/34839176/19209fc3-4458-4863-9c4a-a4db98ef8226">

<img width="101" alt="Screenshot 2024-05-26 at 1 15 32 PM" src="https://github.com/RPCS3/rpcs3/assets/34839176/8476424f-144b-4963-94fb-9bb223e47911">

### System configuration

macOS 14.5
MacBook Pro M2
RPCS3 Version: 0.0.32-16541-a3457c29 Alpha | HEAD
Qt version 6.6.3

**Comment by mavethee** [comment]
No longer an issue:

![CleanShot 2024-09-01 at 09 57 03@2x](https://github.com/user-attachments/assets/71f90eb2-9071-48de-9a97-5253839720ed)

```sh
- SYS: RPCS3 v0.0.33-16885-e56164f1 Alpha | master | local_build
- SYS: Apple M1 (4P+4E) | 8 Threads | 16.00 GiB RAM | TSC: 0.024GHz | FMA3
- SYS: Operating system: macOS, Version: 15.1.0
- SYS: Current Time: 2024-09-01T09:44:24
- RSX: Found Vulkan-compatible GPU: 'Apple M1' running on driver 0.2.994
- SYS: Firmware version: 4.91
S GameList: Created application menu shortcut for The Last of Us™
```
