### ISSUE TITLE
[Regression] [macOS] [Arm] Build: Compilation fails after (#15618)

### ISSUE THREAD

**Issue by shinra-electric** [RPCS3/rpcs3#15637]
### Quick summary

Compilation with Apple Clang on Arm fails after #15618 

### Details

Reverting [d3ab62c](https://github.com/RPCS3/rpcs3/commit/d3ab62c4b144b5b2ced7b6720fcef19bb7b9fa30) will allow it to build again

File affected is `RSX/RSXThread.cpp`

### Build with regression

[d3ab62c](https://github.com/RPCS3/rpcs3/commit/d3ab62c4b144b5b2ced7b6720fcef19bb7b9fa30) 

### Attach two log files

[Terminal Saved Output.txt](https://github.com/RPCS3/rpcs3/files/15469645/Terminal.Saved.Output.txt)

**Comment by elad335** [comment]
still an issue? I merged a potential fix for this.

**Comment by shinra-electric** [comment]
Yep, it's fixed, thanks.

Sorry, I didn't notice the fix being merged.
