### ISSUE TITLE
[Regression] Resistance Fall of Man Graphics corruption

### ISSUE THREAD

**Issue by kunit1** [RPCS3/rpcs3#15632]
### Quick summary

On a level with lots of foliage the foliage appears through walls and on top of the gun. See Screenshot blow
![image](https://github.com/RPCS3/rpcs3/assets/22163077/529c23bc-509d-44be-b3c2-3745dda097a8)
See save file below. It should take you straight to the level where the issue can be observed: 
[BCES00001_PROFILE.zip](https://github.com/RPCS3/rpcs3/files/15448703/BCES00001_PROFILE.zip)

### Details

Edit: turns out this is a regression caused by this PR: [15483](https://github.com/RPCS3/rpcs3/pull/15483)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15448679/RPCS3.log.gz)

### System configuration

CPU: Intel Core i5 12600K
GPU: Intel Arc A750
RAM: 16 GB

**Comment by JimScript** [comment]
Must be an Intel ARC issue, when I get a lot of foliage on my RTX 2070 Super it just shoots up the GPU usage and slows down the game(I test it by going on Somerset blue base in CTF). The PR you mentioned implemented the foliage properly so you can see more than just one/a couple instances at once, but it might have missed implementing it properly on Intel ARC.

**Comment by kd-11** [comment]
Yea this is an arc issue. The best I can do is disable the speedhack we added on intel drivers and hope for the best.

**Comment by kunit1** [comment]
I'd be happy to do any testing if you want to try that.

**Comment by kd-11** [comment]
> I'd be happy to do any testing if you want to try that.

Try the build from https://github.com/RPCS3/rpcs3/pull/15636 whenever it's ready.

**Comment by kunit1** [comment]
Thank you the issue looks fixed to me in the PR. Performance is still at 30 FPS, for this game anyway.
