### ISSUE TITLE
Minecraft: PlayStation 3 Edition (NPUB31419) crashes on startup

### ISSUE THREAD

**Issue by fancythedeveloper** [RPCS3/rpcs3#15643]
### Quick summary

Sorry if I'm missing something, since I don't have much experience with RPCS3. Anyways, the game crashes after loading PPU modules with the error `F {PPU[0x1000000] Thread (main_thread) [0x00908fd4]} VM: Access violation reading location 0x10340000 (unmapped memory)`. I should mention that I'm using `0.0.32-16546-c47212ff Alpha`.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15493229/RPCS3.log.gz)

**Comment by FlexBy420** [comment]
Support requests go on discord or forums, not github. You should validate your PKG just in case.

**Comment by neiguerra1** [comment]
Use any version below 0.0.3-6350. You must preload all skins in the "Help & Options" menu.

link video: https://i.imgur.com/wJWi7Au.mp4
rpsc3 version link that I use to fix this error: https://files02.tchspt.com/down/rpcs3-v0.0.34-17173-68b7e597_win64.7z
