### ISSUE TITLE
Godzilla (2014) PS3 game not running

### ISSUE THREAD

**Issue by jackrose2020** [RPCS3/rpcs3#15641]
### Quick summary

When I Boot it always freezes. When I close the window this error pops up: 

### Attach a log file

Log

### Attach capture files for visual issues

![Capture](https://github.com/RPCS3/rpcs3/assets/66915667/ebeedfb2-7ad7-483f-8d4b-f20edb9de487)

**Comment by FlexBy420** [comment]
Support requests go on discord or forum, not github

**Comment by jackrose2020** [comment]
My fault, I saw a "If something doesn't work correctly in RPCS3." issue tag and though this where the support is supposed to go.
