### ISSUE TITLE
[Regression] Gran Turismo 5 and 6 freeze (#15618)

### ISSUE THREAD

**Issue by ameenross** [RPCS3/rpcs3#15645]
### Quick summary

The games worked nearly perfectly with a few non-default settings. Now GT5 freezes right after the intro video on the main menu, GT6 freezes anywhere between loading the home menu and starting a race.

### Details

The attached zip file with logs is for GT5 (BCUS98114, v2.17), as that freeze happens at (almost?) the exact same time every time.

### Build with regression

v0.0.32-16521-e9492831

### Attach two log files

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/15499015/RPCS3.zip)

### System configuration

- Ubuntu 22.04.4 LTS
- AMD® Ryzen 5 7600
- RAPHAEL_MENDOCINO (raphael_mendocino, LLVM 15.0.7, DRM 3.54, 6.5.0-35-generic)
- No discrete graphics

**Comment by AniLeo** [comment]
Regressed by: #15618

**Comment by elad335** [comment]
This issue is from 3 days ago before the revert, I doubt its still an issue. You can probably experience the issue already on an older build but due to the randomess nature of it you did not until 16521.

**Comment by AniLeo** [comment]
Needs retesting with latest build

**Comment by ameenross** [comment]
I tested GT5 2 days ago, not sure which build that was... but it still froze, albeit at a later stage (while starting a race). However, with the most recent build (16574) it freezes at the same point as before. GT6 also freezes while starting a race with build 16574.

**Comment by eZfoRjK** [comment]
I have this problem... Somebody fix it?

**Comment by m33ts4k0z** [comment]
Hello.

Just wanted to add that the issue described here still orccurs with the latest nightly and the SPU fix.
