### ISSUE TITLE
Black screen on The Last Of Us

### ISSUE THREAD

**Issue by hardBSDk** [RPCS3/rpcs3#15647]
### Quick summary

After the PPU compilation and SPU cache building the game show a broken logo in the bottom right corner and stuck in a black screen.

### Details

- Serial number - BCUS98174
- Game version - 01.11
- Using the recommended options of the RPCS3 wiki
- Using most game patches
- The game don't load

![Screenshot from 2024-05-31 05-38-29](https://github.com/RPCS3/rpcs3/assets/55782009/0d353bc9-2fc4-4874-a0bf-9d9b97ade5c7)

![Screenshot from 2024-05-31 05-38-36](https://github.com/RPCS3/rpcs3/assets/55782009/832f2b33-5c4f-430f-874b-f266870f4f8b)

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/15510691/RPCS3.log.gz)

### Attach capture files for visual issues

[BCUS98174_20240531053214_capture.rrc.gz](https://github.com/user-attachments/files/15510727/BCUS98174_20240531053214_capture.rrc.gz)

### System configuration

- CPU - AMD Ryzen 7 4800HS
- GPU - Integrated on CPU
- RAM - 16GB single-channel DDR4
- OS - PopOS 22.04
- GPU Driver - RADV RENOIR (Mesa3D 24.0.3)

**Comment by mavethee** [comment]
@hardBSDk Nah, it still works.

Don't use SPU Block size on `Mega` that's probably the crashing so its already not like on wiki. Stick to the wiki's settings.

![CleanShot 2024-05-31 at 10 57 18@2x](https://github.com/RPCS3/rpcs3/assets/47083527/2047781c-d81c-422e-ba1f-028bbffd1fed)

Here's crappy Mac booting it, played till chapter 3, then was bored of crashes xD

![CleanShot 2024-05-31 at 10 53 27@2x](https://github.com/RPCS3/rpcs3/assets/47083527/c1fa0f80-a951-46ef-bc0f-7cd19455a5d8)
![CleanShot 2024-05-31 at 10 53 31@2x](https://github.com/RPCS3/rpcs3/assets/47083527/5ecd7103-860d-4dbb-adf7-4ef5f14f1ce7)
![CleanShot 2024-05-31 at 10 53 53@2x](https://github.com/RPCS3/rpcs3/assets/47083527/dfb8c41d-48b8-41d7-ab02-4f785496b6e8)

Log for the record:
[TLOU.log.gz](https://github.com/user-attachments/files/15511013/TLOU.log.gz)

**Comment by hardBSDk** [comment]
@mavethee I tested all options that you suggested, don't work.

**Comment by mavethee** [comment]
Idk, what you tested, but your log is not matching the wiki settings 🐈‍⬛

**Comment by hardBSDk** [comment]
@mavethee I'm using the recommended options from [here](https://wiki.rpcs3.net/index.php?title=The_Last_of_Us).

It was updated recently, thus I doubt that the Discord bot is more up-to-date.

**Comment by mavethee** [comment]
Then again, check wiki and check the log you've uploaded.
Settings don't much, even bot complains on your weird config.
I'm using wiki settings and you aren't.
Mobile Ryzen might be a hassle here as well.

**Comment by AniLeo** [comment]
GitHub is not for support, ask on Discord or Forums.
