### ISSUE TITLE
[DX12 ] HRESULT = The parameter is incorrect

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1565]
@kd-11 
@raven02 

Tested on build : [af79affa]
[DX12]
Game list :
-Castle Crashers
-Dragon Ball: Raging Blast
-Dragon Ball: Raging Blast 2
-J-Stars Victory VS+
-Dark Mist 
-Dragon Ball: Xenoverse
-Majin and the Forsaken Kingdom 
-Mad Riders
-Battle Fantasia
-UFC 2009 Undisputed 
-Meikyuu Touro Legasista JPN

* Probably more

{rsx::thread} class fmt::exception thrown: D3D12GSRender::flip(): The parameter is incorrect.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12GSRender.cpp:522)

**Comment by SakataGintokiYT** [comment]
{rsx::thread} Exception: HRESULT =The parameter is incorrect.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12GSRender.cpp:490, in function D3D12GSRender::flip)

**Comment by SakataGintokiYT** [comment]
[8413cd7b]
*Game : 
Daytona USA [NPJB00161]

{rsx::thread} Exception: HRESULT = The parameter is incorrect.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12GSRender.cpp:590, in function D3D12GSRender::flip)

**Comment by tambry** [comment]
It's simply and indication that driver is unable to render that frame, because something was done wrong. This is rather a symptom than the actual problem. It should probably reported separately for every game with the proper debug output enabled.

**Comment by SakataGintokiYT** [comment]
with debug output enabled
<img src="http://www.fotoszok.pl/upload/a9ae996e.jpg" alt="Fotoszok.pl" />

**Comment by tambry** [comment]
Well, debug output expects you to actually be running in Visual Studio. It reports to the Visual Studio debug output.

**Comment by SakataGintokiYT** [comment]
{rsx::thread} class fmt::exception thrown: D3D12GSRender::flip(): HRESULT = The parameter is incorrect.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12GSRender.cpp:522)

**Comment by SakataGintokiYT** [comment]
<img src="http://www.fotoszok.pl/upload/53a0f80b.jpg" alt="Fotoszok.pl" />

**Comment by SakataGintokiYT** [comment]
@kd-11 

Do you know how to fix it ?

**Comment by kd-11** [comment]
@SakataGintokiYT the fix is actually there in the code, but disabled (and set to always fail because of this). I don't know why vlj disabled the fallback path, but trying to create a resource with dimensions of zero causes this error since the initialization block is never run. If you want to test, change the if (false) clause on line 494 in D3D12GSRender to if (true) and it should work. If it works consistently enough, we can enable it by default and add a message instead of proceeding to the buggy section.

**Comment by SakataGintokiYT** [comment]
@kd-11 It works ^___^

**Comment by kd-11** [comment]
That path when a flip is issued without a surface target being set. on vulkan and gl, we simply ignore blitting anything to screen and clear to black. I could set up a workaround that does the same for DX12

**Comment by SakataGintokiYT** [comment]
@kd-11 
Looking forward to your update.

**Comment by kd-11** [comment]
Fix added with https://github.com/RPCS3/rpcs3/pull/1766
