### ISSUE TITLE
Skate3 freezing on startup

### ISSUE THREAD

**Issue by themoyboy** [RPCS3/rpcs3#15657]
### Quick summary

Skate3 freezing at start screen on RPCS3 - Manjaro

### Details

Im trying to emulate skate 3.

The game loads into the "press > to start" screen - but as soon as i press to start, the game completely crashes and throws these errors:

E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30464_INSTALL/USRDIR/data/big/fetexture.big” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30464_INSTALL/USRDIR/data/big/fetexture.big” [2]
F {RSX [0x007f434]} SYS: 
Segfault reading location 0000000000000000 at 0000000001108397.
Emu Thread Name: 'rsx::thread'.

F {RSX [0x007f434]} SIG: Thread terminated due to fatal error: Segfault reading location 0000000000000000 at 0000000001108397.
Emu Thread Name: 'rsx::thread'.

there are also a bunch of errors before that that occur when the game is launching from RPCS3.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/15539455/RPCS3.log)

### System configuration

Manjaro Linux 24.0.1 (Wynsdey)
RTX 3060 Ti
32GB RAM
AMD Ryzen 7 7700X

![image](https://github.com/RPCS3/rpcs3/assets/80650866/4ce66b28-ac02-4f5f-9559-98514b2e1423)

**Comment by AniLeo** [comment]
Bad non default settings, invalid report.

Ask for support on Discord or Forums, not here.
