### ISSUE TITLE
Dualshock 4 LED brightness

### ISSUE THREAD

**Issue by S4r4h-O** [RPCS3/rpcs3#15656]
### Quick summary

Hi. Is it possible to implement lightbar brightness level control just like DS4 Windows?

![image](https://github.com/RPCS3/rpcs3/assets/128503216/a6512ea6-7b54-4fb3-a812-84ea9257db72)

### Details

> What part of RPCS3 would be affected by your feature? (Gameplay, Debugging, UI, Patches, Installation, CI etc.)

**A:** PAD settings.

> Why your feature is important to RPCS3.

**A:** This feature improves the controller battery consumption and light brightness.

> If the feature is implemented in other projects, attach screenshots.

**A:** Attached in Quick Summary.

**Comment by Megamouse** [comment]
This is already implemented

**Comment by S4r4h-O** [comment]
> This is already implemented

I went back to the app and that's true. Buuut, the reason I thought it wasn't implemented is because the feature only worked while I was in this window:

![image](https://github.com/RPCS3/rpcs3/assets/128503216/a5a6aee6-3647-4be7-8ead-dc9bd3a472e4)

Once I click "OK", the brightness level goes back to 100%, but it fixes when i start a game. Thank you. Problem solved, my mistake :)
