### ISSUE TITLE
New NVIDIA driver locks RPCS3 at 30 fps

### ISSUE THREAD

**Issue by EvilPlayer1** [RPCS3/rpcs3#15666]
### Quick summary

I discovered one strange thing after updating my drivers. All games on RPCS3 are locked at 30 fps. Other games and even PCSX2 work at 60 fps as usual. Speaking about "framerate settings", framelimit is off for all my games and VSync is on. If I disable VSync, I get 60 fps again, but with tearing. Driver 552.44 was the last driver without issues. After updating to 555.85 all my monitor was locked at 30 fps and I couldn't do anything with this. On the newest 555.99 only RPCS3 suffers from 30 fps lock.

### Attach a log file

Maybe it'll help
[RPCS3.log](https://github.com/user-attachments/files/15616484/RPCS3.log)

### System configuration

Windows 11, i7-11700, GTX 1660 SUPER, driver 555.99

**Comment by MsDarkLow** [comment]
This issue **does not** occur on my system and already tested various different games.
Win 11 (23H2 - 22631.3593) - RTX 3080, Driver 555.99 - i9-13900K

**Comment by Darkhost1999** [comment]
I have a GTX 1660 super on the same driver version as the person reporting this issue. I use vsync in the Nvidia control panel instead of inside RPCS3. I don't have this issue. The last time I was getting half the fps I expected in a game it turned out to be RTX HDR.
I recommend just resetting the Nvidia control panel to default settings, then setting Vsync there.

**Comment by Jonathan44062** [comment]
I just played a few games with 60 fps or with the patch and I don't feel like 30 (latest GPU NVIDIA Drivers)
GPU - GTX 1070 Ti (555.99)

**Comment by EvilPlayer1** [comment]
I've found what causes this. It's a "max frame rate" option in the control panel, but it's still interesting why it gives 30 fps on new driver if it's set to 60.

**Comment by Darkhost1999** [comment]
That's fairly common for framelimiters + vsync to produce half the limit. This was a better discussion for discord or the forums.

**Comment by EvilPlayer1** [comment]
After another research I've found that 30 fps are caused by "low latency mode" set to "ultra" in the control panel. If it's disabled or just "enabled", frame counter shows 60.00 as before without jumps. Maybe NVIDIA broke something in new drivers
