### ISSUE TITLE
PS Move games no longer recognizing raw mouse devices (#15615)

### ISSUE THREAD

**Issue by Ginsonic66** [RPCS3/rpcs3#15665]
### Quick summary

Since #15615 (build 0.0.32-16534) PS Move games like Deadstorm Pirates are no longer recognizng raw mouse devices. PS Move cursor and calibration screen never appears and controllers are always detected as Wireless Controllers (Pads) only.
One build before (0.0.32-16523) everything works flawlessly.

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/15612250/RPCS3.log.gz)

**Comment by Megamouse** [comment]
you have to configure it in the raw mouse config dialog first

**Comment by Ginsonic66** [comment]
Thanks for your answer! I think, configured both correctly under Configuration/Mice/Raw Mouse, HID device info is selected, button assignment is valid. Or do you mean something else to configure?
