### ISSUE TITLE
[Regression] [macOS] [Arm] Building fails on Apple Clang 

### ISSUE THREAD

**Issue by shinra-electric** [RPCS3/rpcs3#15672]
### Quick summary

Building fails on Apple Clang under Arm

### Details

Building on Arm was fixed just a few days ago with #15650. 
If I use git to checkout `64127b5` it builds successfully.

However, building directly from master will now fail. 

I have tried reverting several of the recent commits, but I was not able to identify which is causing the issue. 

Clang complains about `rpcs3/emu/System.cpp` and `rpcs3/emu/system_progress.cpp`, but these have not been modified in the last few days...

### Build with regression

Unknown (but after #15650)

### Attach two log files

[Terminal Saved Output.txt](https://github.com/user-attachments/files/15739109/Terminal.Saved.Output.txt)

**Comment by Megamouse** [comment]
Are you sure you didn't forget to update the submodules?

**Comment by shinra-electric** [comment]
Yes, my build script downloads everything fresh…

**Comment by shinra-electric** [comment]
Ah, sorry! It was an error with my script. It wasn't updating `stblib` 🤦🏻‍♂️
