### ISSUE TITLE
gl: Possible framebuffer issue after wxwidgets update (blank output)

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#1567]
After updating wxwidgets source on my pc, builds do not blit contents to the framebuffer correctly under opengl; specifically, if the internal rendering resolution does not match the window dimensions. glBlitFramebuffer fails with invalid_operation. wxWidgets glcanvas creation has undergone some rewrites that may cause this. Appveyor builds do not suffer from this issue for some reason, so it might just be my local branches affected. Noted on AMD hardware.

**Comment by kd-11** [comment]
For anyone willing to test, try running retro city rumpage under ogl.

**Comment by SakataGintokiYT** [comment]
<img src="http://www.fotoszok.pl/upload/9becbb85.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
@SakataGintokiYT Is this an appveyor build or your local build? Also, is your wxwidgets updated properly? (delete the wxwidgets folder && git submodule update --init). If its an issue with my setup i'll just delete it all and start afresh

**Comment by SakataGintokiYT** [comment]
Appveyor Build .

**Comment by Altaiar** [comment]
i don`t know Which commits make this but this games on OPENGL show only black screen
Super Frog NPEB01316 : 
[Super Frog.zip](https://github.com/RPCS3/rpcs3/files/170467/Super.Frog.zip)
Scogger HD : 
[Scogger.zip](https://github.com/RPCS3/rpcs3/files/170468/Scogger.zip)
Hero City 2:
[Hero City 2.zip](https://github.com/RPCS3/rpcs3/files/170469/Hero.City.2.zip)
DX12 Work on Hero city and SuperFrog but graphics is glitches
Metal slug 3 work on opengl
before i use write color buffers in opengl for show Graphics but in latest build this option is usless
in this build (rpcs3-ReleaseLLVM-06cbe4a0) black screen 
in appvoyer Build (rpcs3-ReleaseLLVM-4bfd019c) black screen 
GPU i Use Intel Hd 4600 
the logs in above is from appvoyer build
sry for my bad english

**Comment by tambry** [comment]
@Altaiar How is this relevant to the wxWidgets update causing it to not properly blit pixels?

**Comment by Altaiar** [comment]
i don`t think thats problems i say in above Because of wxwidgets
sry if i wrong post them here

**Comment by kd-11** [comment]
Check if builds before the wxwidgets upgrade causes the black screen (i.e it worked ok before). The default framebuffer created by wxwidgets is not very friendly to raw fbo blits. A quick workaround would be a fullscreen quad like dx12, but i dont think that'll be necessary. I'll investigate further when i can.

**Comment by kd-11** [comment]
I checked out a fresh environment and realized that wxwidgets now creates a canvas with 4x msaa by default. This is the root of all evil.

**Comment by kd-11** [comment]
I submitted a fix for this a while back. Resolved.
