### ISSUE TITLE
Multiple build errors on windows 11

### ISSUE THREAD

**Issue by Iridule** [RPCS3/rpcs3#15676]
I have tried over and over with various settings by going through the building.md file and following it yet various errors occur and solution build continues to fail. I seem to be able to build glslang, llvm and spirv, yet when final solution is built there are many errors.
 
![Screenshot 2024-06-07 192224](https://github.com/RPCS3/rpcs3/assets/135180769/c3c7adb6-0d4f-4fd9-994a-fbc5fb1e2af5)

**Comment by Megamouse** [comment]
I think you didn't build glslang and llvm first.
Anyway, this isn't a support channel.

**Comment by Iridule** [comment]
@Megamouse 
I got the current version to build finally. I was trying to get [cipherxof] fork to build and It does not. Where to go for support?

**Comment by AniLeo** [comment]
No support with custom builds.
