### ISSUE TITLE
Cars 2 Framerate 15fps and below

### ISSUE THREAD

**Issue by JonathanVeg0521** [RPCS3/rpcs3#15677]
### Quick summary

Cars 2 runs at 15fps average and can dip to 10fps.

### Details

I tried playing Cars 2 on default settings and the framerate is average 15fps and can dip down to 10fps. 
During gameplay it is still slow.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/15746207/RPCS3.log)

### Attach capture files for visual issues

![Screenshot 2024-06-07 191317](https://github.com/RPCS3/rpcs3/assets/150976150/24a18b8d-6d3c-4ec7-b4d9-d4054435ce73)

### System configuration

Operating System - Windows 11
CPU - Intel Core i5 - 4690 Quad Core 3.50 ghz
GPU - Nvidia GTX 1070 8GB GDDR5 Driver Version 555.85

**Comment by AniLeo** [comment]
As written on the minimum requirements, CPUs with 4 threads are expected to run badly.
