### ISSUE TITLE
Toy Story 3 - Red Screen using OpenGL

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#15682]
### Quick summary

When you trying to play Toy Story 3 with the rendered OpenGL, this graphical error issue happen, but with Vulkan works fine

### Details

Vulkan
![image](https://github.com/RPCS3/rpcs3/assets/78843189/4ac4cc2f-d572-48bb-9463-68aaf90b02f3)

OpenGL
![image](https://github.com/RPCS3/rpcs3/assets/78843189/3978803e-ff77-480c-93f3-2eb84c7699a0)

### Attach a log file

[Toy Story 3 Vulkan.log](https://github.com/user-attachments/files/15750681/Toy.Story.3.Vulkan.log)

[Toy Story 3 OpenGL.log](https://github.com/user-attachments/files/15750686/Toy.Story.3.OpenGL.log)

### Attach capture files for visual issues

Maybe this can help
[BLUS30480_20240608234542_capture.rrc.gz](https://github.com/user-attachments/files/15750691/BLUS30480_20240608234542_capture.rrc.gz)

**Comment by Darkhost1999** [comment]
Shows a red screen but fixed crashing
[RPCS3 v0.0.31-16240-afcfd814.log.gz](https://github.com/user-attachments/files/15766387/RPCS3.log.gz)
Last build crashing
[RPCS3 v0.0.31-16239-aa06aaab.log](https://github.com/user-attachments/files/15766425/RPCS3.log)
First build crashing
[RPCS3.log](https://github.com/user-attachments/files/15766486/RPCS3.log)
Working
[RPCS3.log.gz](https://github.com/user-attachments/files/15766575/RPCS3.log.gz)
So the regression is locked behind the game not booting
