### ISSUE TITLE
OGL: texture glitches/broken and shadow issue

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1568]
[4bfd019c]
@kd-11 
___________________________________________________________________________
#Open-GL
##### Video : https://www.youtube.com/watch?v=mWgFEnQqZYY&feature=youtu.be
Game Test :
1.Legend Of Kay Anniversary 
2.Dragon Ball: Raging Blast 
3.Ice Age: Dawn of the Dinosaurs
4.Bomberman Ultra
5.Marvel vs. Capcom 2
6.G-Force
___________________________________________________________________________
Logs:
1. https://gist.github.com/SakataGintokiYT/a00562d86351228dc280
2. https://gist.github.com/SakataGintokiYT/500ede20df376d2289a5
3. https://gist.github.com/SakataGintokiYT/4bf3f2f96bd1aae1caa3
4. https://gist.github.com/SakataGintokiYT/5cd8dbe60837d7c0f459
5. https://gist.github.com/SakataGintokiYT/6f2f32e4039980262eac
6. https://gist.github.com/SakataGintokiYT/1fb3c660e10f23e88e35
___________________________________________________________________________
Issues:
-Texture problem
-Multiple Shadow
-Glitches 

[44341895]
fixed CELL_GCM_TEXTURE_R5G6B5 & CELL_GCM_TEXTURE_R6G5B5 formats decoding
<a href="http://www.fotoszok.pl/show.php/2647487_11.jpg.html" target="_blank"><img src="http://www.fotoszok.pl/out.php/t2647487_11.jpg" alt="Fotoszok.pl" /></a>

**Comment by kd-11** [comment]
The shadow issue is easily seen in hitman 2 also, so i at least know where to start. Shadow maps should always clamp to border and not repeat. I think thats a starting point at least. Will look into it when i can.

**Comment by vlj** [comment]
The shadow issue in Hitman2 is because the sampler wrap mode is set to GL_REPEAT.
When a rtt or ds texture is sampled the sampling parameter are not properly set.

**Comment by kd-11** [comment]
oh yes. I did notice that earlier but I forgot to fix this. I'll push a fix soon

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/commit/cf402c8954cbf9212472596e53a9419f075be9c8 was merged. Retest.

**Comment by SakataGintokiYT** [comment]
@kd-11 
*Shadow issue fixed 
<img src="http://www.fotoszok.pl/upload/ca49fe9e.jpg" alt="Fotoszok.pl" />

**Comment by tambry** [comment]
What about the block textures in that other game?

**Comment by kd-11** [comment]
OpenGL backend has had some bugfixes commited recently. Need new tests to confirm current status of this issue report.

**Comment by SakataGintokiYT** [comment]
Dragon Ball Raging Blast -[FragmentProgram / VertexProgram / Log ] http://www94.zippyshare.com/v/tBt1g4H4/file.html

Legend Of Kay Anniversary- [FragmentProgram / VertexProgram / Log ] http://www81.zippyshare.com/v/TWtLYfbM/file.html

Ice Age Dawn of the Dinosaurs- [FragmentProgram / VertexProgram / Log ] http://www19.zippyshare.com/v/6sf7hXNY/file.html

Bomberman Ultra- [FragmentProgram / VertexProgram / Log ] http://www112.zippyshare.com/v/Z281deak/file.html

Marvel vs. Capcom 2- [FragmentProgram / VertexProgram / Log ] http://www22.zippyshare.com/v/m4sHYSys/file.html

G-Force- [FragmentProgram / VertexProgram / Log ] http://www53.zippyshare.com/v/96MIdyrT/file.html

<img src="http://www.fotoszok.pl/upload/2caf182f.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/312b6400.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/851d0884.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/8c8f16ed.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/537dee48.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/0d474607.jpg" alt="Fotoszok.pl" />

**Comment by tambry** [comment]
The cats from the Legend of Kay look a little too bright.

**Comment by kd-11** [comment]
@SakataGintokiYT Check current status of some of the games. I can see a few bugs that i've already fixed.

**Comment by SakataGintokiYT** [comment]
<img src="http://www.fotoszok.pl/upload/b14a30f5.png" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/72be9afc.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
any updates on this? most bugs have been fixed I think

**Comment by SakataGintokiYT** [comment]
@kd-11 
[63b30cce]

**Marvel vs. Capcom 2**
<img src="http://www.fotoszok.pl/upload/01ba0e4d.jpg" alt="Fotoszok.pl" />

**G-Force**
<img src="http://www.fotoszok.pl/upload/e1c4726c.jpg" alt="Fotoszok.pl" />

**Ice Age: Dawn of the Dinosaurs**
<img src="http://www.fotoszok.pl/upload/f35d3db5.jpg" alt="Fotoszok.pl" />

**Legend Of Kay Anniversary** 
<img src="http://www.fotoszok.pl/upload/3b4293f3.jpg" alt="Fotoszok.pl" />

**Dragon Ball: Raging Blast** 
<img src="http://www.fotoszok.pl/upload/cdd35d2f.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
Raging blast issue is also reported here: https://github.com/RPCS3/rpcs3/issues/1769
Since the other problems seems to have been fixed, maybe we can close this?

**Comment by SakataGintokiYT** [comment]
@kd-11 
**[Dragon Ball Z: Burst Limit]**
Very old regression by Vlj in openGL
<img src="http://www.fotoszok.pl/upload/0c34c225.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
My suggestion is to close this ticket and follow up dragon ballz issues separately. There's already an issue open for it. Also, from the picture; you mean it used to work and then stopped?

**Comment by SakataGintokiYT** [comment]
blurred map is all time 
Okay, i close this thread
