### ISSUE TITLE
Enter a title here

### ISSUE THREAD

**Issue by gllxflr** [RPCS3/rpcs3#15694]
### Quick summary

At random points during gameplay, it will freeze up.

### Details

While playing through any level of the game, or the hub, there is a random chance that the game will crash. I've tried both OpenGL and Vulkan, it does not matter which. The game will just randomly crash. The game window stays open but completely freezes.
Settings are as follows:
![image](https://github.com/RPCS3/rpcs3/assets/149011830/ba1ff685-429e-4973-b613-149dcd5ec703)
![image](https://github.com/RPCS3/rpcs3/assets/149011830/48da65d4-66e7-47c0-884b-04f71342f491)

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/15792242/RPCS3.log)

### System configuration

Linux Mint 21.3 Cinnamon (based on Ubuntu 22.04)
GPU: NVIDIA GTX 1060 6GB, driver 535.171.04
CPU: AMD Ryzen 5 3600
32GB RAM

### Other details

The main launcher window is still responsive during and after the crash.

**Comment by AniLeo** [comment]
Invalid report, not even using wiki settings for the game. This is not the place for the support requests, use the Forums or the Discord help channel.
