### ISSUE TITLE
Child of Eden - Screen is stuck on "Loading Trophies" throughout gameplay

### ISSUE THREAD

**Issue by cantoryakov** [RPCS3/rpcs3#15696]
### Quick summary

"Loading Trophies" screen is stuck while the game plays on.

### Details

While playing _Child of Eden_ on Steam Deck, shortly after starting the game the screen partially fades out and "Loading Trophies" appears superimposed over gameplay. This loading screen never goes away the whole time I play the game. _Child of Eden_ plays very well, but only behind this permanent "Loading Trophies" screen.

Is there a solution to this problem?

(I did ask in Discord first btw)

### Attach a log file

[RPCS3 log.log](https://github.com/user-attachments/files/15793891/RPCS3.log.log)

### System configuration

Steam Deck / Linux
6 nm AMD APU
CPU: Zen 2 4c/8t, 2.4-3.5GHz (up to 448 GFlops FP32)
GPU: 8 RDNA 2 CUs, 1.6GHz (1.6 TFlops FP32)

### Other details

I attempted the same thing on Windows and it worked perfectly, the trophies took only a second to load and the loading screen disappeared. So it's a Linux problem?

Thank you so much

**Comment by Megamouse** [comment]
You're missing a file. Your game dump is incomplete.
