### ISSUE TITLE
Linking error on Ubuntu. Cannot find -ledit dependency 

### ISSUE THREAD

**Issue by rcaridade145** [RPCS3/rpcs3#1570]
`[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/rsx_program_decompiler/shader_code/clike_language.cpp.o
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/rsx_program_decompiler/shader_code/builder.cpp.o
Linking CXX executable ../bin/rpcs3
/usr/bin/ld: não foi possível encontrar -ledit
collect2: error: ld returned 1 exit status
rpcs3/CMakeFiles/rpcs3.dir/build.make:9131: r`

To solve this on my machine i had to do export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/

**Comment by tambry** [comment]
Could you clarify why you opened the issue? Judging by the description you already solved it.

**Comment by rcaridade145** [comment]
Mainly because i saw on the forums someone complaining about linking problems on Ubuntu and because this dependency is not stated on the readme. My approach was simply a hack. If this only affects Ubuntu i'll report this upstream, however because i wasn't sure i opened this bug report.

**Comment by tambry** [comment]
Looks like an issue of a custom library location on the system, and CMake probably doesn't check there. I'm not sure though, as my knowledge of UNIX systems is severely limited.

**Comment by rcaridade145** [comment]
Checking on another Linux distro - ArchLinux - it seems that there should not be any problem. Either this is a problem of my configuration (Multiarch Ubuntu) or general Ubuntu. I'll report this upstream.  That being said i would be better to add both bison and libedit as dependencies.

**Comment by axfelix** [comment]
I just hit something similar:

`[100%] Building CXX object CMakeFiles/rpcs3.dir/home/axfelix/Desktop/rpcs3/rsx_program_decompiler/shader_code/builder.cpp.o
[100%] Building CXX object CMakeFiles/rpcs3.dir/home/axfelix/Desktop/rpcs3/rsx_program_decompiler/shader_code/clike_language.cpp.o
Linking CXX executable rpcs3
/usr/bin/ld: cannot find -lasmjit
/usr/bin/ld: cannot find -lpng16_static
/usr/bin/ld: cannot find -lvulkan
/usr/bin/ld: cannot find -lglslang
/usr/bin/ld: cannot find -lOSDependent
/usr/bin/ld: cannot find -lOGLCompiler
/usr/bin/ld: cannot find -lSPIRV
collect2: error: ld returned 1 exit status
CMakeFiles/rpcs3.dir/build.make:9364: recipe for target 'rpcs3' failed
make[2]: *** [rpcs3] Error 1
CMakeFiles/Makefile2:188: recipe for target 'CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [CMakeFiles/rpcs3.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
axfelix@shoebox:~/Desktop/rpcs3/rpcs3$`

**Comment by tambry** [comment]
@axfelix What commands did you run? And did you clone all the submodules?

**Comment by axfelix** [comment]
Yup, cloned all the submodules and built following the readme. This is a Ubuntu 16.04 environment; looks like I have gcc 5.3.1 and llvm 3.5 and 3.6 installed. I'd try on my arch machine instead but it doesn't have a GPU :)

**Comment by AniLeo** [comment]
Same happened to me in Ubuntu 15.10

![screenshot_15](https://cloud.githubusercontent.com/assets/10283761/14067021/3da9ea6e-f452-11e5-92c8-367dab8aef36.png)

**Comment by AniLeo** [comment]
@axfelix That's because you run the command inside the rpcs3 folder. You have to run it at the parent directory. 
Still, it still won't work:
![screenshot_16](https://cloud.githubusercontent.com/assets/10283761/14067230/eb996f8c-f457-11e5-96ea-287d6cad5325.png)

**Comment by tambry** [comment]
I think someone had the same problem about the _edit_ page (whatever that is) in some other issue. It should probably be added to the readme, as we try to link with it somehow and for some unknown reason.

**Comment by tambry** [comment]
I think someone had the same problem about the _edit_ page (whatever that is) in some other issue. It should probably be added to the readme, as we try to link with it somehow and for some unknown reason.

**Comment by AniLeo** [comment]
@tambry Submitted a change for the README 

![screenshot_16](https://cloud.githubusercontent.com/assets/10283761/14067313/53ebcd80-f45a-11e5-99b2-55dfdc23267c.png)

**Comment by axfelix** [comment]
Thanks for the quick work on this.

**Comment by AniLeo** [comment]
This can be closed as of #1629
