### ISSUE TITLE
Build 16610 does not launch while 16609 does

### ISSUE THREAD

**Issue by Cr4shMyCar** [RPCS3/rpcs3#15703]
### Quick summary

Build 16610 will not launch and gives a "Windows cannot access the specified device, path, or file." error, while 16609 works as intended

### Details

I have downloaded and extracted build 16610 as usual, but upon launching it, Windows gives me an error. I have run RPCS3 fine on this computer before, and the older build 16609 works. 

### Attach a log file

Build 16610 does not generate a log file. Attached is a picture of the install folder and the error given by Windows.
![image](https://github.com/RPCS3/rpcs3/assets/93006953/4eef9b57-3ea1-4d29-abf1-7a9f87930e7a)
![image](https://github.com/RPCS3/rpcs3/assets/93006953/6dbc17de-dc62-4579-af2b-53f3ca1aba9d)

Build 16609 log file:
[RPCS3.log.gz](https://github.com/user-attachments/files/15826175/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Local issue, the build is fine.

Try basic troubleshooting steps such as a fresh folder, reboots, checking if the anti-virus is blocking the process, etc. 

If you need support, use Discord or Forums.

**Comment by AniLeo** [comment]
Seems like you already tried this as I've been told, my next hint is to try uninstalling any anti-cheats you might have installed. 

Something in your PC is blocking the build, just need to find out what. If it's indeed an anti-cheat, we will another ticket to list defective anti-whatever shit software.
