### ISSUE TITLE
NeverDead Glitch Top Screen Green line

### ISSUE THREAD

**Issue by ketaro121** [RPCS3/rpcs3#15701]
### Quick summary

- SYS: RPCS3 v0.0.32-16610-caf81f13 Alpha | master
- SYS: 13th Gen Intel(R) Core(TM) i9-13900K | 32 Threads | 63.80 GiB RAM | TSC: 2.995GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 22631, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2024-06-12T21:18:31
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 4090' running on driver 555.99.0.0
- SYS: Firmware version: 4.85

![rpcs3_BAod7xO8Xk](https://github.com/RPCS3/rpcs3/assets/67107145/17e92684-a6fb-4977-a35e-334d3403b4cd)
![rpcs3_huUoSdK1cP](https://github.com/RPCS3/rpcs3/assets/67107145/46e8fba0-f0f0-4307-8cb0-ea114fae8126)

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/15806586/RPCS3.log)
[NeverDead [BLUS30654].log.gz](https://github.com/user-attachments/files/15806590/NeverDead.BLUS30654.log.gz)

**Comment by Triticum0** [comment]
Needs a capture file which is missing

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed
