### ISSUE TITLE
[Feature request] Android port

### ISSUE THREAD

**Issue by Riot20058** [RPCS3/rpcs3#15706]
### Quick summary

Belived finally get rpcs3 on android working do understand ps3 different to emulate people are stress get running app like Horizon Pc Emulator and Winlator

### Details

Rpcs3 needed alot chaged work will on android system do belived high end cpu like snapdragon 8 gen 2 barely system spec needed get 2nd indie games work out proof run will on android 
![20240613_172646](https://github.com/RPCS3/rpcs3/assets/128275823/6bba1fb1-8302-4c53-93e1-cb850bad34db)

Keep mind image running rpcs3 thier emulator know with winlator also belived rpcs3 probably easy keep update vita3k see most port run batter on ps3 do ps vita ver.

**Comment by Riot20058** [comment]
Asking know long team thing take like 3 to 5 year at least see possible idea at this possible think snapdragon point emulated ps3 itself maybe not perfection enough run alot 3rd party games itself

**Comment by Riot20058** [comment]
Here quote wall if run wall

No. But some games run with 20-50 fps keep mind with winlator itself and add way more different to emulate ps3 games whould with native android port code will.

**Comment by Dormant-Hero** [comment]
I would also like to request support for my kindle. Not sure if I should open another issue or 2.

**Comment by Valtekken** [comment]
Sorry to tell you this but literally NOTHING of what you said is understandable. Get ChatGPT to rewrite it in understandable English at least if you can't do that.

That being said, RPCS3 on any kind of Arm architecture (that isn't Apple's, and even then it's a maybe) isn't coming for a very long time.

**Comment by AniLeo** [comment]
Refused. Do not open more tickets about it.

**Comment by Riot20058** [comment]
> Refused. Do not open more tickets about it.

Saying someone do port with sorce code make Aethersx3 like project maybe learned about it of course make sure whole app open srouce don't case last time it happen. Again biggest main in ass not do the ps3 system make sure auto update disable and not break app itself probably needed skill programmer maybe learned do it make font of rpcs3 know as Aethersx3.

Again most people don't used fonk open srouce most Ethical thing must people never make work and used offical ver thierself.

**Comment by Riot20058** [comment]
Not about rpcs3 team just 3rd party doing it like myself maybe good project learned code it first

**Comment by AniLeo** [comment]
Locked.
