### ISSUE TITLE
[Regression] Grand Theft Auto V: Freezes after loading (#15686)

### ISSUE THREAD

**Issue by eternights** [RPCS3/rpcs3#15710]
### Quick summary

GTA V now starts to freeze.

### Details

A few seconds after the loading screen, GTA V starts to freeze. This doesn't happen in RPCS3 version 0.0.32-16583 and below.

### Build with regression

v0.0.32-16584

### Attach two log files

[Grand Theft Auto V [NPEB01283] - 16584.log.gz](https://github.com/user-attachments/files/15862257/Grand.Theft.Auto.V.NPEB01283.-.16584.log.gz)
[Grand Theft Auto V [NPEB01283] - 16583.log.gz](https://github.com/user-attachments/files/15862289/Grand.Theft.Auto.V.NPEB01283.-.16583.log.gz)

### System configuration

OS: Windows 11 Pro
CPU: Intel(R) Core(TM) i7-9750HF CPU @ 2.60GHz   2.59 GHz
GPU: Nvidia GeForce GTX 1650
GPU driver: 32.0.15.5599
RAM: 16 GB
Storage: 500GB SSD

### Other details

Tested with NPEB01283 with all game updates.

**Comment by minerfromhell** [comment]
Experiecing the same in version 0.0.32-16614, game NPEB01283 or NPUB31154 upd. 1.27. But freezing doesn't happen if Preferred SPU threads is set to 1 or Recompiler (ASMJIT) is selected instead of Recompiler (LLVM). Windows 10 LTSC 21H2, Ryzen 7800X3D, RTX 4070.

**Comment by F121Live** [comment]
+1, same issue, same logs.

**Comment by minerfromhell** [comment]
Build 16676 seems to resolve the issue. At least the game doesn't deadly freeze, but there is some hangs for a second.
