### ISSUE TITLE
PPUInterpreter:Line3742

### ISSUE THREAD

**Issue by nulcearc** [RPCS3/rpcs3#1572]
Recompiler with DX12\Vulkan\GL

![image](https://cloud.githubusercontent.com/assets/8341270/13754664/405f3eec-ea31-11e5-96ac-e05069453081.png)

Log: https://gist.github.com/nulcearc/ab86835890264bb22da9

Config: https://gist.github.com/nulcearc/47e1556d2db91fffd8e8

**Comment by vlj** [comment]
You need to run rpcs3 outside of VS.
If you want to run rpcs3 inside of VS you need to disable access violation in the exception settings (under win32).

**Comment by tambry** [comment]
Not really something we can "fix" per se.
