### ISSUE TITLE
Demon's Souls [BLES00932] - Broken sound 

### ISSUE THREAD

**Issue by rika09** [RPCS3/rpcs3#15724]
### Quick summary

Sound is totaly broken.

### Attach a log file

[RPCS3.zip](https://github.com/user-attachments/files/15943946/RPCS3.zip)

### Attach capture files for visual issues

https://youtu.be/k2LPjeh156Q

### System configuration

Windows 10, i5 8250u, 8gb ram, GFmx150 with 555.99 drivers

**Comment by YuriNator557** [comment]
Your PC is far below recommended requirements, this would be normal.
