### ISSUE TITLE
When using a mouse as a PS MOVE, the square and circle are no longer assigned to mouse buttons 4 and 5.

### ISSUE THREAD

**Issue by dante3732** [RPCS3/rpcs3#15735]
### Quick summary

In the new versions of the emulator, the square and circle are no longer assigned to mouse buttons 4 and 5.

### Build with regression

RPCS3 0.0.32-16627

### Attach two log files

[RPCS3.log](https://github.com/user-attachments/files/15969535/RPCS3.log)
[RPCS3.log](https://github.com/user-attachments/files/15969518/RPCS3.log)

**Comment by dante3732** [comment]
I have checked several builds, the buttons work fine in version 16506 but stop working in 16518

**Comment by Megamouse** [comment]
I'll try to implement hot swap for those config files
