### ISSUE TITLE
[BLE00926] Batman Arkham City, Black Spots appear in certain areas.

### ISSUE THREAD

**Issue by Nuke10** [RPCS3/rpcs3#15730]
### Quick summary

Certain Dark Spots appear during gameplay
there are Dark spots that appears on certain area of the game

OS: Windows 10 Home edition 64bit
RPCS3 version:rpcs3-v0.0.32-16614

https://youtu.be/aYdYn165obM

### Details

Certain Areas of the game appear to have dark spots,
didn't checked to much into it but from the little i did seem to always happen in the same place

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/15958722/RPCS3.log.gz)

**Comment by Jonathan44062** [comment]
Duplicated of https://github.com/RPCS3/rpcs3/issues/14113
