### ISSUE TITLE
[Regression] Pull request #15743 crashes/exits RPCS3 for several games (build v0.0.32-16646-ef136acb)

### ISSUE THREAD

**Issue by 5kft** [RPCS3/rpcs3#15751]
### Quick summary

Pull request https://github.com/RPCS3/rpcs3/pull/15743 (rsx: Fix wrapped/clamped MSAA sampling behavior with dynamic flags) crashes RPCS3 for several games.  Everything works great when reverting to the previous RPCS3 build prior to this change.

### Details

I've provided details of this issue in the original pull request - please see https://github.com/RPCS3/rpcs3/pull/15743#issuecomment-2196032879 and https://github.com/RPCS3/rpcs3/pull/15743#issuecomment-2196064010 - relevant log excerpts are provided there.  Happy to provide additional information if necessary.

### Build with regression

v0.0.32-16646-ef136acb

### Attach two log files

(Relevant log excerpts attached to the comments in the pull request - see Details section above)

**Comment by ReLyf47** [comment]
Heres a tiny compilation from complaining discord user of the game that is affected:

LittleBigPlanet 1-3
Metal Gear Solid 4
Heavy Rain
God of War HD Collection
Uncharted: Drake's Fortune
Gran Turismo 5
Dark Souls
Skate 3

Latest known good build is 16644

**Comment by ReLyf47** [comment]
[GoWC.log](https://github.com/user-attachments/files/16024256/GoWC.log)
[GT5.log](https://github.com/user-attachments/files/16024257/GT5.log)
[Uncharted.log](https://github.com/user-attachments/files/16024259/Uncharted.log)
[MGS4.log.gz](https://github.com/user-attachments/files/16024260/MGS4.log.gz)
[Skate3.log](https://github.com/user-attachments/files/16024261/Skate3.log)

I have also compiled the log that was sent in the "#help" from discord

error seems to be the same and about

```
Failed to compile fragment shader
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKProgramPipeline.cpp:30[:25], in function struct VkShaderModule_T *__cdecl vk::glsl::shader::compile(void))
```
