### ISSUE TITLE
DS3: Inaccurate Motion Input Values

### ISSUE THREAD

**Issue by yunes-0840** [RPCS3/rpcs3#15750]
### Quick summary

Motion values for the DualShock 3 don't vary much and the G value is stuck to 2

### Details

Motion values for the DualShock 3 don't vary much ,about 200 unis for X and Z, and 400 units for Y. While the G value is stuck to 2
![Screenshot 2024-06-27 195231](https://github.com/RPCS3/rpcs3/assets/68710005/02f49092-fece-4dd5-a87f-0fa9ede4c2c7)

Motion controls work fine in a real PS3 so I don't know what's up

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16022121/RPCS3.log)

### System configuration

Windows 11
CPU: Intel I5 10400F
GPU: RX 6750 XT
16GB DDR4 RAM
Lexar NM620 M.2 NVMe SSD
Genuine DualShock 3 (Wired)

### Other details

Motion works fine on a real PS3, but not in RPCS3

**Comment by Megamouse** [comment]
Try with SDL.
This is a known issue and happens with some controllers probably due to their firmware version or calibration.

**Comment by yunes-0840** [comment]
Changing to SDL puts them all to 0
![image](https://github.com/RPCS3/rpcs3/assets/68710005/adee0c86-4fa8-4d2d-8384-f9f1b0ae85b8)

**Comment by yunes-0840** [comment]
Issue is fixed upon using Sony's official driver, meaning it isn't a problem within RPCS3 and actually with Nefarius' DsHidMini.

A guide to uninstall the faulty driver can be found here: https://docs.nefarius.at/projects/DsHidMini/How-to-Install/
A guide to installing Sony's driver can be found here: https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration#Using_the_official_Sony_Driver

To mention, the issue has nothing to do with the gamepad handler.
