### ISSUE TITLE
Killzone 3 - patch to disable aim assist

### ISSUE THREAD

**Issue by digant73** [RPCS3/rpcs3#15753]
### Quick summary

One of the most annoying feature present only on the single player campaign in killzone 3 is the aim assist. The aim assist consists on:
1) automatically slow down the camera movement speed when the crosshair is close to an enemy. This is extremely annoying when you have a lot of enemies on screen and you move the camera on the environment (continuous camera slow down)
2) automatically center the the camera on the enemy when shooting the enemy close to the crosshair

The game does not provide any option to disable the aim assist. So, a patch to disable this annoying feature is welcome

**Comment by MSuih** [comment]
We dont consider individual patches to be a part of the main emulator project and thus issues related to them aren't accepted on this issue tracker. You can talk about them on our Discord if you want to.

**Comment by digant73** [comment]
> We dont consider individual patches to be a part of the main emulator project and thus issues related to them aren't accepted on this issue tracker. You can talk about them on our Discord if you want to.

ok, thanks for the clarification. Is the **development** discussion in discord the proper target for such kind of requests?

**Comment by MSuih** [comment]
The rpcs3 channel might be better place since you're not actually developing anything. And also don't get your hopes up, things like these don't usually progress unless you're willing to implement them yourself.
