### ISSUE TITLE
The Godfather Don's edition vulkan crash Strikes again

### ISSUE THREAD

**Issue by Atarashi-Daten-Shi** [RPCS3/rpcs3#15755]
### Quick summary

Was playing Godfather the Dons Edition on RPCS3 cause I heard the Vulkan Crash has been potentially fixed... No I still got it to crash It was during the 3rd mission in the game 

### Attach a log file

Sadly the Log File is too big to post

**Comment by Megamouse** [comment]
Since you're not posting a log file, this issue is invalid
