### ISSUE TITLE
[Regression] Gran Turismo 5 black screen

### ISSUE THREAD

**Issue by Pangorin** [RPCS3/rpcs3#15767]
### Quick summary

Played this game 3 months ago and it worked perfectly. But now I updated the RPCS3 and the game stopped working. Game version is 02.17 and I double-checked every setting on Gran Turismo 5's RPCS3 page.

### Details

F {PPU[0x1000010] Thread (ksF3) [0x00a75a5c]} VM: Access violation reading location 0xc (unmapped memory)
![image](https://github.com/RPCS3/rpcs3/assets/68218885/6b5d2e34-edd5-4b19-8201-469fb6c798f4)

### Build with regression

v0.0.32-16659-33851d51

### Attach two log files

[RPCS3.log.gz](https://github.com/user-attachments/files/16096561/RPCS3.log.gz)
[RPCS3.log](https://github.com/user-attachments/files/16096562/RPCS3.log)

### System configuration

Operating system: Windows 10 Pro 22H2
CPU: AMD Ryzen 7 2700 OC'ed
GPU: RTX 2060
RAM: 16GB

**Comment by AniLeo** [comment]
Invalid regression report, closing as Invalid.

Incorrectly blames the wrong build, uploads both log files from the same build.
