### ISSUE TITLE
[Regression] God of War Ascension always crashes for 5 minutes gameplay

### ISSUE THREAD

**Issue by WolfSpirit1999** [RPCS3/rpcs3#15766]
### Quick summary

the game always crashes on my PC

### Details

F {RSX [0x08c0f88]} VM: Access violation reading location 0x38500000 (unmapped memory)

### Build with regression

Build 0.0.32-16659

### Attach two log files

[God of War Ascension [BCUS98232].log.gz](https://github.com/user-attachments/files/16092861/God.of.War.Ascension.BCUS98232.log.gz)
[RPCS3.log](https://github.com/user-attachments/files/16092863/RPCS3.log)

### System configuration

Device name	WIN-FSKO3EHQ090
Processor	Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.70 GHz
Installed RAM	16,0 GB (15,9 GB usable)
Device ID	12D00CEF-463E-402C-BF1A-23C8B152C6AA
Product ID	00331-10000-00001-AA897
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Pro
Version	24H2
Installed on	‎16/‎06/‎2024
OS build	26100.712
Experience	Windows Feature Experience Pack 1000.26100.6.0

**Comment by AniLeo** [comment]
Invalid regression report, closing as Invalid

Blames the wrong build and uploaded both logs from the same build.

I don't even think this is a regression and if it is, it's not recent at all, as I had the same issue last time I tested the game.
