### ISSUE TITLE
[Regression] LittleBigPlanet freezes / hangs

### ISSUE THREAD

**Issue by EngineMachiner** [RPCS3/rpcs3#15777]
### Quick summary

It's still happening.

The game freezes or hangs after playing or creating for a while. Audio can be heard after the freeze and the game doesn't crash.

No patches and just the default settings.

### Build with regression

v0.0.32-16670-a1d2a72a

### Attach two log files

[RPCS3.log](https://github.com/user-attachments/files/16121559/RPCS3.log)
[RPCS3.log.gz](https://github.com/user-attachments/files/16121560/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Invalid regression report

- The flagged build is wrong as it certainly did not introduce this regression

- Both log files are for the same build
