### ISSUE TITLE
[Feature request] Would it be possible to use the iso format?

### ISSUE THREAD

**Issue by carlosgamer23** [RPCS3/rpcs3#15782]
### Quick summary

It's more practical for those who have the original game on CD, to convert it to iso, it would be nice to be able to leave it in iso to play, if that's not possible "ok"...

### Details

It's more practical for those who have the original game on CD, to convert it to iso, it would be nice to be able to leave it in iso to play, if that's not possible "ok"...

**Comment by AniLeo** [comment]
PS3 games don't come in CDs, they come in blu-rays. It is literally not easier to dump your game as ISO versus using the provided dumping methods as you will need to manually handle decryption afterwards.

Closing as a duplicate of #4021
