### ISSUE TITLE
[Feature request] display proper game update even with no contiguous update pkg files

### ISSUE THREAD

**Issue by digant73** [RPCS3/rpcs3#15784]
### Quick summary

There are some games for which the released updates pkg files are not contiguous in version such as in Resistance 3 where updates start from v102 to v105 (v101 does not exist). For such games, RPCS3 always displays (on the Version column) v01.00 as current version even when all the available patches have been installed (see Resistance 3 in the attached image).
It should be less confusing if the proper version is displayed, that means, in case of Resistance 3, v01.05.

![resistance_3](https://github.com/RPCS3/rpcs3/assets/64427768/167d9626-7ae5-441e-a295-bc988d7b61d0)

**Comment by MSuih** [comment]
Gaps in the version history are not the reason. Seems to me that RPCS3 can't find a connection between installed update and a disc game so it ends up showing the base version on the disc.

Can you show a screenshot with game data visible? View -> Game categories -> enable Game data

**Comment by digant73** [comment]
forget it. it was one of the few bought used but received a blus version while I checked updates for the bles version
