### ISSUE TITLE
[Feature request] Associate rap files with registered RPCS3 users on RPCN online

### ISSUE THREAD

**Issue by RobokingsCosmos** [RPCS3/rpcs3#15780]
### Quick summary

So users who own their game via rap license can use the download games listing however read the details please

### Details

Download games is grayed out by default for unregistered users but upon opening it says it will need your own RAPs
It's important so that we can obtain said pkg via the emulator and pretend the emulator's user agent as PS3 from our own purchased games you need a pkg database that is coded in a way no one will be able to read it.
All raps must be legit purchases. Automatically download the raps to your hdd0/exdata in the RPCS3 dir so that you can re-obtain your own games without losing them just like PlayStation Network. Benefits of using RPCN.

**Comment by Megamouse** [comment]
We already decided not to allow downloading pkg files withing the emulator.
And rpcn has nothing to do with pkg downloads.
So sorry but I'll have to close this.

**Comment by RobokingsCosmos** [comment]
Ok
