### ISSUE TITLE
can't run God of War® III

### ISSUE THREAD

**Issue by omidfk** [RPCS3/rpcs3#15786]
### Quick summary

can't run God of War® III
would you please check that?

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16158662/RPCS3.log.gz)
[RPCS3.log](https://github.com/user-attachments/files/16158671/RPCS3.log)

### System configuration

RPCS3 v0.0.32-16682-99b44cf3 Alpha | master
AMD Ryzen 9 6900HX with Radeon Graphics | 16 Threads | 15.26 GiB RAM | TSC: 3.294GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22631, Service Pack: none, Compatibility mode: 0
Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Laptop GPU' running on driver 556.12.0.0
Found Vulkan-compatible GPU: 'AMD Radeon(TM) Graphics' running on driver 2.0.262
Firmware version: 4.91

**Comment by FlexBy420** [comment]
Support requests go to either our forum or discord not github.

**Comment by MSuih** [comment]
It's a broken pirated copy, we don't give help with those. Get a properly dumped game first.
