### ISSUE TITLE
[Feature request] Preload shaders

### ISSUE THREAD

**Issue by INCENDIOCODM** [RPCS3/rpcs3#15785]
### Quick summary

i feel like if there could be preload shaders then it could help a lot of pc to play on the simulator

### Details

preload shaders by this i mean, preloading all the parts of the game before starting and then while playing maintaining stable fps like 30 or even 60,  it would be very appreciated if it is possible to add it in the emulator 

i also got a crash here is it
<img width="369" alt="image" src="https://github.com/RPCS3/rpcs3/assets/106219962/172a2d6a-ba13-426b-a3e6-85417150f9cd">

**Comment by FlexBy420** [comment]
Precompiling shaders is not possible, if it was it would already be a thing.
