### ISSUE TITLE
Documentation: Controller_Config links to vigem.org, but the site has changed

### ISSUE THREAD

**Issue by nroach44** [RPCS3/rpcs3#15798]
Under https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration#Using_Nefarius'_DsHidMini step 3, the link "DsHidMini Control UI" links to vigem.org.

Loading the page presents a certificate error (issued to vigem.de, not .org) and then loads to something that's not related to a PS3 controller.

**Comment by AniLeo** [comment]
Fixed
