### ISSUE TITLE
[Feature request] manage game/update removal from GUI + game patches applicability only for current game version

### ISSUE THREAD

**Issue by digant73** [RPCS3/rpcs3#15790]
### Quick summary

Just two improvements that should be supported/provided by the RPCS3's GUI:
* removal of a game or its updates from the GUI. Currently, the removal must be manually performed removing folders here and there and editing configuration files (e.g. **games.yml**) manually
* applicability of game patches allowed only on current game version (e.g. v1.5). Currently, the GUI allows to enable/disable all the available patches for both the base game (e.g. v1.0) and its game update (e.g. v1.5), if any installed, giving the user the false feeling that enabled patches are applied even for the base game while they are instead not taken into account at all in case the game is updated to a most recent version (e.g. v1.5). Game patches that cannot be applied should be at least greyed out on the GUI's **Patch Manager** window

**Comment by FlexBy420** [comment]
1. You already can remove game update, you just need to enable to show game data category.
2. Just check the "Only show owned games" checkbox.

**Comment by digant73** [comment]
> 1. You already can remove game update, you just need to enable to show game data category. View>Game Categories>Game data (for digital games you have to reinstall the game)
> 2. Just check the "Only show owned games" checkbox.

ok, but it makes more sense IMO to manage game + updates with a context menu, selecting the game from the list, right click, select something like "remove game" and "remove game patches"

**Comment by RipleyTom** [comment]
Have you seen the context menu, it's already bloated. The actions you're asking for are somethings most users will never do, it makes no sense to have them in the main context menu.
Request denied.

**Comment by FlexBy420** [comment]
You can put disc games wherever you want though?
And theres also VFS (Virtual file system) if you want to have for example digital games somewhere else, and also symlinks exist.
