### ISSUE TITLE
Resistance 3 crashing (often requiring RPCS3 to be manually killed) even with default settings

### ISSUE THREAD

**Issue by digant73** [RPCS3/rpcs3#15792]
### Quick summary

Just bought even the BCES01118 (EU version) of Resistance 3, installed its updates (up to 01.05) and verified that the game freezes (even with no patches applied) and I need to close the game window. Often, as it happened with the attached log file (zip file not available due to RPCS3 crashed or required to be killed), RPCS3 crashes or freezes and a manual kill of the process is required.

Tested on Windows 11 (with latest updates) with:
* CPU 7800X3D, 32 GB, 2 + 4 GB nvme
* GTX 970 (with latest drivers) and also RTX 4060

### Attach a log file

[RPCS3.zip](https://github.com/user-attachments/files/16198710/RPCS3.zip)

**Comment by Hamof1** [comment]
Sounds like the same issue as this: https://github.com/RPCS3/rpcs3/issues/14809, which is still happening no the current build for me.

**Comment by digant73** [comment]
in this game, from the log file and the console (before I close the frozen game window) I see:

F {RSX [0x39eff50]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKQueryPool.cpp:45[:4], in function bool __cdecl vk::query_pool_manager::poke_query(struct vk::query_pool_manager::query_slot_info &,unsigned int,unsigned int)) (error=0x578)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:110[:24], in function void __cdecl vk::die_with_error(enum VkResult,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::source_location)) (error=0x578)

**Comment by Jonathan44062** [comment]
That error message is related to this: https://github.com/RPCS3/rpcs3/issues/15289
So please report your issue there

**Comment by digant73** [comment]
closing because covered by #15289
