### ISSUE TITLE
Shaders Compiling causing stuttering...

### ISSUE THREAD

**Issue by Svxy** [RPCS3/rpcs3#15800]
### Quick summary

NBA 2K11 and most other games stuttering and hitching when compiling shaders, even if they're precompiled.

### Details

When playing NBA 2K11 and several other games, I've noticed persistent issues with stuttering and hitching, particularly during shader compilation processes, even when shaders are precompiled. This problem seems to affect the smoothness of gameplay, causing disruptions that impact the overall gaming experience. It's frustrating because these interruptions occur despite efforts to optimize shader performance beforehand. This issue not only detracts from the immersion and enjoyment of playing these games but also raises concerns about the underlying performance optimizations or potential compatibility issues with hardware configurations. Addressing these shader-related hiccups could significantly enhance gameplay fluidity and user satisfaction, making it a critical area for improvement in future updates or troubleshooting efforts.

### Attach a log file

log file too large 

### System configuration

NVIDIA GeForce GTX 1060 3gb +
![sys](https://github.com/user-attachments/assets/41a72ffe-74b8-4f0d-952d-941dbc207bdf)

**Comment by MSuih** [comment]
You are below our recommended specs so performance issues are to be expected. i7 3770 is 12 years old by now, it isnt very good in CPU-intensive tasks anymore.
