### ISSUE TITLE
God of War: Origins Collection 3D option not working

### ISSUE THREAD

**Issue by revenpl** [RPCS3/rpcs3#15809]
### Quick summary

God of War Collection Vol 2 3D option not working.

### Details

God of War Collection Vol 2 supports 3D TVs:
https://wiki.rpcs3.net/index.php?title=God_of_War%3A_Origins_Collection
https://blog.playstation.com/2011/07/01/stereoscopic-3d-on-ps3-updated-list-of-all-3d-games-and-movies/
Despite setting 3D option in custom configuration it renders in 2D. There is no in game option to change rendering mode, as the game should automatically turn on 3D mode on 3D compatible TVs. 

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16314576/RPCS3.log)

### Attach capture files for visual issues

<img width="1322" alt="Zrzut ekranu 2024-07-19 o 18 24 00" src="https://github.com/user-attachments/assets/8abd0947-b7eb-4e5a-9531-dd2ad0cdfb2a">
<img width="1840" alt="Zrzut ekranu 2024-07-19 o 18 26 20" src="https://github.com/user-attachments/assets/cb157191-37aa-4b50-805d-0f267d9ddf32">

### System configuration

MacOS Sonoma 14.5 
M1 Max

Windows 11
AMD 7950X3D
Radeon 7900XTX

On both systems there is the same bug.

**Comment by Megamouse** [comment]
I think the issue is that you have 1080p selected.
We only support 3D for 720p.
I've made a change to disable the dropdown if 720p is not selected.
I've also decided to make this dropdown only available in custom configurations, since very few games support it.

**Comment by revenpl** [comment]
I changed the resolution to 720p and still no luck, 3D does not work. I even tried changing VBlank Frequency to 120Hz to mimic high refresh rate TV but this does not work either.

**Comment by Megamouse** [comment]
works fine in the demo:
![image](https://github.com/user-attachments/assets/4d2d746a-8b8b-4c8b-a559-ce12de51efdd)

**Comment by revenpl** [comment]
Yes, you are right, there is new option in game setting now. Fixed.

**Comment by ChrisFratz** [comment]
> I've also decided to make this dropdown only available in custom configurations, since very few games support it.

Sorry for reviving this thread after so long but I must ask, since so few games support it would it make more sense for the stereoscopic option be available globally? Since theoretically it shouldn't effect games that don't support 3D anyway, and every 3D compatible game that I know of has a built in on/off toggle. I feel it's pointless to make it only available in the custom config menu. And as an anecdote, this change confused me so bad that I thought the setting was straight up broken on my end for months.
