### ISSUE TITLE
The gui of the emulator is too large

### ISSUE THREAD

**Issue by GatoGamer7DCP** [RPCS3/rpcs3#15806]
### Quick summary

the rpcs3 interface is very big, and I can't use it like that, it's impossible to see the buttons on the screen, and the top bar is extremely long in height, the window is bigger than my two monitors and it's impossible to change its height

### Details

it's not a problem with a game, but with the program's interface, when I click on any of the top buttons, my left screen goes black, (so I press esc) and press the button again, and there's a GIANT bar on the my screen on the right where it is impossible to see all the options (since the buttons are almost the size of the screen)

### Attach a log file

i dont have any log file

### Attach capture files for visual issues

(https://github.com/user-attachments/assets/700bf37a-0374-4513-bcbf-731442bee0f6)
(https://github.com/user-attachments/assets/df5396a9-80e2-4e9d-98a2-817ea5bf73f8)
(https://github.com/user-attachments/assets/3a2f494c-741d-4fc0-8e63-f6fb8f0d18ef)
(https://github.com/user-attachments/assets/873b61c6-de86-45a6-b699-b1b5a938842f)

### System configuration

windows 10
intel hd graphics

**Comment by Megamouse** [comment]
That's caused by your shit windows theme
