### ISSUE TITLE
(Website sponsor link broken) Alipay is 404 (file not found)

### ISSUE THREAD

**Issue by casualkitten1** [RPCS3/rpcs3#15805]
### Quick summary
(I don't know if this is the right place to post this, but I guess it's a bug?)
Hello, on the right side of the github page, people can sponsor the project using Alipay, sadly, the website redirects to a "file not found" page

https://rpcs3.net/alipay
![image](https://github.com/user-attachments/assets/b787e554-0dcd-4238-93ae-d76a077cc37d)

### Attach a log file

none

### Other details

none

**Comment by Megamouse** [comment]
This is not an issue of the emulator
