### ISSUE TITLE
[Feature request] Add 640x480 to the Default Resolution list

### ISSUE THREAD

**Issue by JS299990** [RPCS3/rpcs3#15808]
### Quick summary

It's for compatibility reasons. 640x480 is usually the default resolution for the vast majority of games that support 4:3 display. The other 4:3 resolutions option already in the list always brakes something in every game I tried them on regardless of what settings or monitor I'm using.

**Comment by Megamouse** [comment]
720x480 is the same as 640x480 if you select 4:3
