### ISSUE TITLE
pine ipc port does not open on nixos

### ISSUE THREAD

**Issue by TheAwesome98-Real** [RPCS3/rpcs3#15811]
### Quick summary

if you enable pine ipc on nixos, no port is opened

### Details

1. open rpcs3
2. click configuration
3. click ipc
4. enable it
5. launch a game
6. `netstat -lntu | grep 28012`
7. `$? -eq 1`

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16315878/RPCS3.log)
the gzipped one wouldn't upload so i did the not gzipped one
i was just fucking around so there's a lot of irrelevant lines in here like random programs opening

### System configuration

```
lily@dawn
---------
OS: NixOS 24.05.2933.c716603a63ac (Uakari) x86_64
Kernel: 6.1.87
Uptime: 10 hours, 46 mins
Packages: 4 (cargo), 1 (steam), 2069 (nix-system)
Shell: bash 5.2.26
Editor: GNU nano 8.0
Resolution: 2560x1440 @ 75.00Hz, 1920x1080 @ 60.00Hz
DE: LXQt 2.0.0 (x11)
WM: Xfwm4
Theme: Darklooks [Qt/GTK2/3]
Icons: mate [Qt/GTK2/3]
Cursor: mate [Qt], mate-black [GTK2/3]
Terminal: alacritty
Terminal Font: JetBrainsMono Nerd Font
CPU: AMD Ryzen 5 2600X (12) @ 3.6GHz
Memory: 10.94 GiB / 15.55 GiB (70%)
Network: WiFi
BIOS: American Megatrends Inc. 5.13 (06/17/2020)
```

### Other details

:3

**Comment by leo60228** [comment]
PINE only uses TCP on Windows, per both the [documentation](https://projects.govanify.com/govanify/pine/-/blob/master/standard/draft.dtd) and source code. The Nixpkgs RPCS3 package appears to listen on a Unix socket at `/run/user/1000/rpcs3.sock.28012` as expected.

**Comment by TheAwesome98-Real** [comment]
yeah the gui made this less clear, i expected tcp due to it saying port

will close this issue tomorrow after testing

**Comment by leo60228** [comment]
Based on the source code, I believe this issue also affects macOS.

**Comment by TheAwesome98-Real** [comment]
yeah, it does create the socket. i think there's a mistake in the library i'm using
