### ISSUE TITLE
[Keyboard Config] Modifier Key Combos Ignored

### ISSUE THREAD

**Issue by lzardy** [RPCS3/rpcs3#15817]
### Quick summary

Shift, Ctrl, and other modifier keys are ignored when combined with other keys, ex: `Shift + [key]`.

### Details

Simply modify the default keyboard configuration buttons to use some combination of a modifier key and another normal key, i.e `Shift + [key]`. God of War HD was the game I used to test. The specific buttons configured were for the Right Stick on a Standard (Pad) PS3 Controller.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16323924/RPCS3.log)

### System configuration

Windows 10, i5-10600k, 4060 Ti driver 555.99, PS3 firmware 4.91. rpcs3 version 0.0.32-16699-3ab89221 Alpha | master.

**Comment by Megamouse** [comment]
I don't think we ever supported this.
It's also impossible to configure it this way unless you intentionally keep shift pressed before even pressing the button in the UI.
