### ISSUE TITLE
Vulkan The guided fate paradox issue NPUB31320

### ISSUE THREAD

**Issue by Ekaseo** [RPCS3/rpcs3#1581]
here are some rendering problems on vulkan api with this game:
First loading screen
![tgfp1](https://cloud.githubusercontent.com/assets/5016194/13811250/dd75c1da-eb74-11e5-80bd-a32e95763936.png)
Main menu
![tgfp2](https://cloud.githubusercontent.com/assets/5016194/13811252/dfe343d4-eb74-11e5-9eb2-a739893cbef6.png)
First screen when starting the game:
![tgfp3](https://cloud.githubusercontent.com/assets/5016194/13811255/e25bba42-eb74-11e5-947b-d54b28d5ccfa.png)
First conversation
![tgfp4](https://cloud.githubusercontent.com/assets/5016194/13811256/e44f8ee6-eb74-11e5-8833-64ffb977ffca.png)
Ingame:
![tgfp5](https://cloud.githubusercontent.com/assets/5016194/13811259/e8f94ba8-eb74-11e5-8a19-0de41c9fc0fb.png)
Log:
https://www.sendspace.com/file/7de8bq

**Comment by kd-11** [comment]
Nvidia, I assume?

**Comment by Ekaseo** [comment]
yes

**Comment by kd-11** [comment]
I dont have a copy of this game, but vulkan has some texturing issues right now with channel remapping which i haven't implemented yet. vlj is making some changes to make it work on nvidia, so maybe that'll help.

**Comment by Ekaseo** [comment]
is the standard log enough or do you also need rsx logging to locate the root of this? just so i know for future posts concerning the vulkan renderer

**Comment by kd-11** [comment]
Usually the RSX log is important for a few frames where a bug manifests, but in this case the issue is visible from the images. An RSX log wouldn't hurt though.

**Comment by vlj** [comment]
Same here in some cases. I suspect that the dotted pattern happens when a depth stencil is attached but I don't know why. 
I will investigate once I get mipmapped texture working.

**Comment by vlj** [comment]
I think I have a fix

**Comment by Ekaseo** [comment]
its not perfect, but its a lot better now
![tgfp1](https://cloud.githubusercontent.com/assets/5016194/13864311/b09c1bf0-eca0-11e5-8b41-8b7768c66c2e.png)
![tgfp2](https://cloud.githubusercontent.com/assets/5016194/13864313/b5bbcc7a-eca0-11e5-90d5-585f9d5fee40.png)
![tgfp3](https://cloud.githubusercontent.com/assets/5016194/13864320/c0b5b03c-eca0-11e5-8a47-a87ae2f278bd.png)
![tgfp4](https://cloud.githubusercontent.com/assets/5016194/13864324/c9698ea6-eca0-11e5-8144-acc4bbf09435.png)
LOG:
https://www.sendspace.com/file/aff9mo

**Comment by kd-11** [comment]
Nice.

**Comment by Ekaseo** [comment]
looks like the game is working correctly now, so im closing this issue
