### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by KingOtaku** [RPCS3/rpcs3#1582]
help me 
![screenshot 3](https://cloud.githubusercontent.com/assets/17879797/13813253/c98590ce-eb3d-11e5-8c67-68787566f5c7.png)

**Comment by DPersonalized** [comment]
Seriously?
https://github.com/RPCS3/rpcs3/wiki/FAQ

**Comment by MyaniPT** [comment]
Please post your log and give a further description of your issue

**Comment by KingOtaku** [comment]
{PPU Thread[0x1] (main_thread)[0x0050dbb4]} cellSysmodule TODO: cellSysmoduleSetMemcontainer(ct_id=0x19)
{PPU Thread[0x1] (main_thread)[0x003377f8]} sys_vm: sys_vm_memory_map(vsize=0xe000000, psize=0x800000, cid=0xffffffff, flags=0x200, policy=0x1, addr=*0xb52044)
{PPU Thread[0x1] (main_thread)[0x0050d894]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU Thread[0x1] (main_thread)[0x0050da74]} cellSpursJq TODO: cellSpursJobQueueAttributeInitialize
{PPU Thread[0x1] (main_thread)[0x0050daf4]} cellSpursJq TODO: cellSpursJobQueueAttributeSetGrabParameters
{PPU Thread[0x1] (main_thread)[0x0050da54]} cellSpursJq TODO: cellSpursJobQueueAttributeSetMaxSizeJobDescriptor
{PPU Thread[0x1] (main_thread)[0x0050da34]} cellSpursJq TODO: cellSpursJobQueueAttributeSetSubmitWithEntryLock
{PPU Thread[0x1] (main_thread)[0x0050da14]} cellSpursJq TODO: cellSpursJobQueueAttributeSetDoBusyWaiting
{PPU Thread[0x1] (main_thread)[0x0050db34]} cellSpursJq TODO: cellSpursJobQueueAttributeSetIsHaltOnError
{PPU Thread[0x1] (main_thread)[0x0050da94]} cellSpursJq TODO: cellSpursJobQueueAttributeSetIsJobTypeMemoryCheck
{PPU Thread[0x1] (main_thread)[0x0050db14]} cellSpursJq TODO: _cellSpursCreateJobQueue
{PPU Thread[0x1] (main_thread)[0x0050c894]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
{PPU Thread[0x1] (main_thread)[0x0050d894]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU Thread[0x1] (main_thread)[0x0050d894]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU Thread[0x1] (main_thread)[0x0050d894]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU Thread[0x1] (main_thread)[0x0050d894]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU Thread[0x1] (main_thread)[0x0050e634]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0xa8, handle=0xa9, reqspace=*0xd000f780, options=0x0)
{PPU Thread[0x1] (main_thread)[0x0050ded4]} cellJpgEnc TODO: cellJpgEncQueryAttr
{PPU Thread[0x1] (main_thread)[0x0050dcd4]} cellSysutil TODO: cellSysCacheClear()
{PPU Thread[0x1] (main_thread)[0x0050e594]} cellScreenshot TODO: cellScreenShotSetOverlayImage

**Comment by Altaiar** [comment]
this is not the log that log file after start a game will create in your rpcs3 folder

**Comment by KingOtaku** [comment]
i don't understand

**Comment by MyaniPT** [comment]
@KingOtaku
http://www.emunewz.net/forum/showthread.php?tid=174352

**Comment by KingOtaku** [comment]
thx

**Comment by KingOtaku** [comment]
now this
![screenshot 4](https://cloud.githubusercontent.com/assets/17879797/13821699/ea571094-eb5f-11e5-8d61-ae9714f0d750.png)

**Comment by tambry** [comment]
@KingOtaku Did you even read the guide? RPCS3 is in early stage of development and very few games work. Most games either crash early on (this one), don't boot at all (most) or are slightly playable (very very few).
[Check out the list of playable games](http://www.emunewz.net/forum/forumdisplay.php?fid=195).

**Comment by KingOtaku** [comment]
how to download OpenGL 4.5 ?

**Comment by MoochMcGee** [comment]
It's not something you download, dumbass. Your hardware just has to support
it.

**Comment by KingOtaku** [comment]
the game not open :(

**Comment by tambry** [comment]
@KingOtaku It has already been explained to you, that most games don't run.

**Comment by KingOtaku** [comment]
aha
