### ISSUE TITLE
Pro Evolution Soccer 2009 Enter a title here

### ISSUE THREAD

**Issue by DubaiShark** [RPCS3/rpcs3#15820]
### Quick summary

Graphic glich glitch

### Details

Just run the game to start the match all players are in black color 

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16335799/RPCS3.log)

### Attach capture files for visual issues

![Screenshot 2024-07-22 185224](https://github.com/user-attachments/assets/3e621907-0d4c-4403-b6bc-d63b8e0759b8)

### System configuration

no config has been changed

**Comment by Mrlinkwii** [comment]
as per the wiki , the game needs Write color buffers  on 

https://wiki.rpcs3.net/index.php?title=Pro_Evolution_Soccer_2009

**Comment by DubaiShark** [comment]
Hi 

Sorry I forgot to check Wiki before submitting the issue 

Thanks
