### ISSUE TITLE
Random crashes in LBP2

### ISSUE THREAD

**Issue by ninphobic** [RPCS3/rpcs3#15836]
### Quick summary

LBP2 crashes very often, from either 5 minutes after launch or 3 hours after, and for seemingly no reason whatsoever. Normally I'd be alright with this but I lose progress on costumes and creations because of this and it's very annoying. I play on the Beacon server patch, if that matters.

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16373918/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed
