### ISSUE TITLE
[Feature request] Gamepad Settings: "PS Move" as Device Class

### ISSUE THREAD

**Issue by HeyItsLollie** [RPCS3/rpcs3#15835]
### Quick summary

I would like to see the PS Move (the motion controller, not the Navigator controller) added as a Device Class in the Gamepad Settings window.

### Details

Configuration for PS Move motion controllers is currently split across different regions of RPCS3, and its implementation feels incomplete and neglected as a result.

- The "PS Move Navigator" is present in the Gamepad Settings window as a Device Class, but not the PS Move itself.
- The "Fake" Move Handler has a separate barebones settings window under Configuration > USB Devices > PS Move (Fake). It's unclear which controller the "Fake" handler is mapped to, if at all.
- The "Mouse" Move Handler does not appear to have a configuration window at all, and so its inputs cannot be configured within RPCS3.

Given that the PS Move is a distinct input device, it seems sensible to give the controller its own Device Class option — and maybe even remove the need for separate "Fake" and "Mouse" Move Handlers altogether. Ideally, this would allow for more detailed configuration of the PS Move controller, for example:
- Face button configuration, particularly useful for mouse control.
- X/Y absolute positional control via a specific controller's joystick axis position.
  - This is a feature in [DuckStation](https://github.com/stenzek/duckstation) for "lightgun" controller profiles. It was specifically implemented for lightguns like the Sinden Lightgun, which can return positional data as a virtual joystick X/Y axis position.
  - It can also be used to control lightgun games with standard dual-stick analog controllers, where the lightgun cursor's position on the screen reflects the stick's absolute position. ie: Using the stick to point at a specific position on the screen, instead of slowly pushing the cursor around the screen.

**Comment by Megamouse** [comment]
That's not how it works and it's also not how it will ever be implemented.
