### ISSUE TITLE
[Feature request] A simple "Press CTRL+F1 for help" in the debugger

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#15839]
### Quick summary

I was looking for info about the debugger in its code (literally no info is present in the debugger itself), only to find that it already has an inbuild small help page with shortcuts.
Seriously?
Also, even in that little help window it says that to bring it up, you need to press F1, but you actually need to press ctrl+F1.

**Comment by elad335** [comment]
It was actually a bug, F1 was also used in another place.
