### ISSUE TITLE
Emulator crashing for seemingly no reason

### ISSUE THREAD

**Issue by vizthex123** [RPCS3/rpcs3#15847]
### Quick summary

I'm trying to play Ratchet & Clank Future: Tools of Destruction and it keeps crashing near the start of the opening cutscene (about 3 - 5 seconds in).

### Details

As the summary says, it crashes shortly after the opening cutscene starts. I've tried the default configs and custom ones, but nothing fixes it.

### Attach a log file

- [RPCS3.log](https://github.com/user-attachments/files/16401748/RPCS3.log)

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed
