### ISSUE TITLE
[Feature request] Custom Settings follow Global Settings

### ISSUE THREAD

**Issue by ReLyf47** [RPCS3/rpcs3#15849]
### Quick summary

basically like how Duckstation/PCSX2 has "Follow Global Settings" option on custom settings

### Details

although this might be hard for rpcs3 due to it using tick settings instead of dropdown
but i suppose there could be another tick under/over all the settings that only appear on custom settings that says "Follow Global" 

might make the settings more convoluted but it also could be a QoL improvement idk

**Comment by RipleyTom** [comment]
When you create a custom configuration it copies your global settings already.
I don't think adding an option to follow global settings has any real use and would add clutter to an already very charged interface in addition to giving out support even worse(as people may change global settings without realizing it will affect games with custom configuration and wonder why suddenly their game doesn't work).
