### ISSUE TITLE
RPCS3 doesn’t fully utilize my GPU

### ISSUE THREAD

**Issue by CreeperofDoom** [RPCS3/rpcs3#15854]
### Quick summary

The RPCS3 Emulator does not fully Utilize my GPU leading to heavily degraded performance

This persists across my Main Powerful Computer and Steam Deck
(Steam Deck has an option to Force the GPU clock) but on my main computer i am out of luck because performance is wobbly and bad due to this, i have no clue why this occurs.

### Details

Performance in RPCS3 titles seem to be heavily degraded and my GPU is hardly being used for RPCS3.

This persists across 3 Titles i tested: Scott Pilgrim vs The World: The Game, God of War HD and Beyond Good and Evil HD.

These three games target 60fps on real PS3 hardware but run at 30 - 40 FPS on my Main Machine and Steam Deck due to underutilization of the GPU

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16432053/RPCS3.log)

### System configuration

Steam Deck Log File Used, RPCS3 Appimage Used

**Comment by FlexBy420** [comment]
PS3 emulation is CPU demanding, not GPU. Your GPU is being fully utilized by RPCS3.

**Comment by CreeperofDoom** [comment]
> PS3 emulation is CPU demanding, not GPU. Your GPU is being fully utilized by RPCS3.
> And if you want to see higher % usage of your GPU just increase resolution scale.
> Also steam deck CPU is pretty weak.

Doesn’t seem to be the case here. on Steam Deck forcing the GPU Clock does fix performance for these titles.

If i force it to 600mhz in Scott Pilgrim it runs at locked 60, i have not tried God of War HD on that yet. Beyond Good and Evil HD runs at 60 if the GPU is set to 1000mhz.

My Main Computer doesn’t have a GPU Limit feature so that one has more degraded performance despite it being significantly more powerful…

**Comment by FlexBy420** [comment]
Makes sense, steam deck is underpowered, it's only 15W so it makes sense you are both gpu and cpu bottlenecked lol

**Comment by AniLeo** [comment]
Non-issue, low GPU usage is not an issue by itself and very normal for most games.

Performance issues on specs that match or exceed our recommended specifications need to be properly investigated to determine the root cause, just guessing won't help as we can already see the game is slow and try to guess ourselves.
