### ISSUE TITLE
Immediate crash upon transition between laoding screen to in-game in Ratchet and Clank: A Crack in Time (BCUS98124, v1.2)

### ISSUE THREAD

**Issue by CoolPenguin42** [RPCS3/rpcs3#15879]
### Quick summary

When loading into the game environment (after selecting and beginning save file load), RPCS3 crashes and closes immediately.

### Details

Basically, I can get into the first screen and create a new game. It gets through the entire cutscene intro, but right before you get into the game and start playing as clank, the game hangs up and closes, and closes rpcs3 along with it. I have tried it with previous test save files (which were made when the game worked), but as of yesterday I can no longer get in-game. Only thing that was changed was that the game was updated from v1 -> v1.2. This could have caused the issue, I am not sure how to determine that though. I have attached the log file for viewing. 

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16475453/RPCS3.log)

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed
