### ISSUE TITLE
[Regression] Little big planet 2 froze 20 minutes into playing it 

### ISSUE THREAD

**Issue by Mert5666** [RPCS3/rpcs3#15870]
### Quick summary

so I was playing random community levels and when I in the middle of playing a re upload of the ao oni by crimson fang and the game froze halfway through 

### Build with regression

v0.0.32-16724-7884bcc2

### Attach two log files

[RPCS3.log.gz](https://github.com/user-attachments/files/16448872/RPCS3.log.gz)
[RPCS3.log](https://github.com/user-attachments/files/16448875/RPCS3.log)

### System configuration

![Screenshot 2024-06-05 170321](https://github.com/user-attachments/assets/3ebce5d7-7300-4e76-ad57-3d51ebbd2b1a)
![Screenshot 2024-06-05 165509](https://github.com/user-attachments/assets/2031223f-23fc-4a6c-8f6d-48ad0a80479a)
![image](https://github.com/user-attachments/assets/8c9038f7-458e-4b42-a807-4dad0b0070b8)
![image](https://github.com/user-attachments/assets/b5e01366-fe03-4f25-9929-ae0310bb0cd7)
![image](https://github.com/user-attachments/assets/3684e5ed-7120-4840-b631-b1bef6e430c2)
![image](https://github.com/user-attachments/assets/5ca81cd4-9369-4e45-8c27-daeb4b2ae573)
![image](https://github.com/user-attachments/assets/fc33bdc2-7849-45fe-85f0-a7740077ca38)
![image](https://github.com/user-attachments/assets/bd03dad5-98d9-464c-b133-cf84761897ae)
![image](https://github.com/user-attachments/assets/e44406e3-e77a-4dfb-82d3-92bbdd3dbe57)
![image](https://github.com/user-attachments/assets/16d69b17-fc1c-4505-b3da-5140f35e1479)

**Comment by Jonathan44062** [comment]
Invalid report, you do not meet the requirements.
You have to point out WHICH Build broke the game, not the last one as you put it.
Also, both logs you send are empty.
