### ISSUE TITLE
[Feature request] RPCS3 Option to Disable the “Screenshot Saved” overlay 

### ISSUE THREAD

**Issue by kortul** [RPCS3/rpcs3#15877]
### Quick summary

Because if you play RPCS3 via Steam and want screenshots in your Steam recordings manager instead of the RPCS3 folder, the following screenshot after the one you take will have the annoying overlay message with the path to folder. Thats a problem especially when you want to catch a brief moment and need to make multiple screenshots fast - the overlay message will ruin screenshots.

Plus the overlay message is distracting in general and breaks immersion for some. Sound notification Steam makes is enough to confirm the screenshot was made. An option to hide "screenshot saved" overlay would be much appreciated.

### Details

[Feature request] RPCS3 Option to Disable the “Screenshot Saved” overlay

**Comment by Megamouse** [comment]
What does steam have to do with our screenshot utility?

**Comment by kortul** [comment]
As you probably know you can add non-Steam application like RPCS3 into your Steam Library - this way you get Steam overlay with all its awesome features. So as mentioned above when you take screenshots while playing via Steam, overlay notification from RCPS3 is visible in Steam screenshots. I'm sure lots of people are using Steam overlay with RPCS3, especially with the Steam Deck.

**Comment by Megamouse** [comment]
Why would you get an RPCS3 notification if you take a screenshot with steam?

**Comment by kortul** [comment]
Lol you are right - the problem was because Steamdefault screenshot shortcut is also F12. Changing it to F9 in Steam solved this for me as now only Steam takes the screenshot🤪

**Comment by Megamouse** [comment]
Well, I guess this is not needed anymore then

**Comment by mrsalminator** [comment]
> Well, I guess this is not needed anymore then

I still need it. I don't want to change Steam settings. I want to change RPCS3 settings. I want to take screenshots in RPCS3 with F9 instead of F12, or get rid of that annoying message about where the screenshot was saved. It's annoying.
