### ISSUE TITLE
Ridge Racer 7 video gets stuck at random times, audio and controls continue

### ISSUE THREAD

**Issue by juicepoggers** [RPCS3/rpcs3#15880]
### Quick summary

Ridge Racer 7 (NPEB00513) gets stuck at random times. The video freezes but everything else seems to continue. 

### Details

Video freezes, game continues to run. No special settings enabled. No idea what's causing this so please see the attached log file.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16476864/RPCS3.log)

### System configuration

Intel 13700K
NVIDIA RTX 4070Ti

**Comment by AniLeo** [comment]
Duplicate of #9380
