### ISSUE TITLE
Dimensions Manager Connection Loop

### ISSUE THREAD

**Issue by sentrywasbored** [RPCS3/rpcs3#15888]
### Quick summary

Dimensions Manager disconnects/reconnects during gameplay. Reproducible

### Details

When entering the level Paranormal Beginnings(ghostbusters 2016 1st level) and interacting with the Rip Keystone, they ToyPad goes into a disconnect/reconnect loop, rendering the game unplayable from that point forward. 

Log file, save, and character bin have been provided for convenience.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16484364/RPCS3.log)

### Other details

[BLES02105000.zip](https://github.com/user-attachments/files/16484367/BLES02105000.zip)
[71242 - Ghostbusters (2016) Story Pack.zip](https://github.com/user-attachments/files/16484368/71242.-.Ghostbusters.2016.Story.Pack.zip)

**Comment by sentrywasbored** [comment]
Log indicates loop is caused by unimplemented requests in the fake device.

E dimensions: Unimplemented LD Function: 0xc8
E dimensions: Request: 55 0E C8 05 01 FF 6E 18 01 FF 6E 00 01 80 00 0C
B1 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E dimensions: Unimplemented LD Function: 0xc8
E dimensions: Request: 55 0E C8 06 01 FF 6E 18 01 FF 6E 00 01 80 00 0C
B2 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E dimensions: Unimplemented LD Function: 0xc8
E dimensions: Request: 55 0E C8 07 01 FF 6E 18 01 FF 6E 00 01 80 00 0C
B3 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by sentrywasbored** [comment]
After Further testing, this problem seems to extend to the Lockpicking puzzles in the Fantastic Beasts story missions.

**Comment by deReeperJosh** [comment]
I will try to spend a bit of time with the berny23 toypad just to investigate expected responses. Is the log the same in terms of the unimplemented LD function for the fantastic beasts levels too? Or is it a different LD function than the C8 seen in the Ghostbusters log?

**Comment by sentrywasbored** [comment]
I think it's the same log, but I'll have another look. That C8 unimplemented function seems to pop up a lot though in the logs, best guess is it's trying to display those colors on the pad LEDs
