### ISSUE TITLE
[Regression] [macOS] Updater fails after recent bump to Curl version

### ISSUE THREAD

**Issue by shinra-electric** [RPCS3/rpcs3#15891]
### Quick summary

Updater on macOS will fail when checking for available updates after #15876

Working in 16730, not working in 16733

### Details

Error message: 
```
E NET: curl_easy_perform(): Curl error (77): Problem with the SSL CA cert (path? access rights?)
Details: error setting certificate verify locations: CAfile: none CApath: none
```

### Build with regression

v0.0.32-16733

### Attach two log files

N/A

**Comment by Azzhoe** [comment]
Yup, can confirm I am having the exact same problems here too.

**Comment by kd-11** [comment]
Same issue observed in asahi linux with arm native builds.

**Comment by gh0sti** [comment]
Is it due to homebrew updating curl or something else that RPCS3 doesn't support? Will we need to download from the site a new build to continue getting new builds?

**Comment by shinra-electric** [comment]
Not sure what fixed it, but this is no longer an issue with latest version (0.0.32-16856)

**Comment by gh0sti** [comment]
> Not sure what fixed it, but this is no longer an issue with latest version (0.0.32-16856)

you have to manually update to that version then check for updates and shouldn't error out anymore.
