### ISSUE TITLE
[BLJM60350] Street Fighter X Tekken (Japan, Asia) (En,Ja,Zh,Ko) black screen

### ISSUE THREAD

**Issue by 411752230** [RPCS3/rpcs3#15892]
### Quick summary

Tried to run [BLJM60350] Street Fighter X Tekken (Japan, Asia) (Disc game) with Asian languages support. 
Not working with black screen.
Game has already been updated to 1.08.
[BLUS30722] Street Fighter X Tekken (US) (Disc game) runs perfectly for me.

### Details

![微信截图_20240804134124](https://github.com/user-attachments/assets/01244fd5-79ae-4c27-a7cb-8d121a67bafe)

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16486942/RPCS3.log.gz)
[RPCS3.log](https://github.com/user-attachments/files/16486943/RPCS3.log)

### System configuration

CPU	13th Gen Intel(R) Core(TM) i9-13900HX   2.20 GHz
GPU Nvidia 4070 8G Laptop
RAM 32.0 GB
RPCS3 Build: v0.0.32-16743-f6b55115 Alpha | master

**Comment by 411752230** [comment]
Hello. Any response here? By 0.0.32-16785-3ef8046f Alpha | master, the black screen problem persists.

**Comment by AniLeo** [comment]
Our issue tracker is not for support requests neither for game compatibility reports. Use the appropriate platforms as indicated in the how to ask for support guide under the wiki tab in the repository.
