### ISSUE TITLE
[Regression] [BLUS30528] Can't pass the calibration by using mouse as a light gun

### ISSUE THREAD

**Issue by scju** [RPCS3/rpcs3#15902]
### Quick summary

I can't finish the calibration by pressing the middle button and the right button of the mouse. I remember it was fine before. 

### Details

![2024-08-06_205229](https://github.com/user-attachments/assets/032de1e3-d24c-430a-926e-fed8ed459d2c)

I think it might be related to this change:  https://github.com/RPCS3/rpcs3/pull/15860

### Build with regression

0.0.32-16754

### Attach two log files

0.0.32-16754 [not working]
[RPCS3.log](https://github.com/user-attachments/files/16510876/RPCS3.log)
[RPCS3.log.gz](https://github.com/user-attachments/files/16510880/RPCS3.log.gz)

0.0.32-16737 [working]
[RPCS3.log.gz](https://github.com/user-attachments/files/16510942/RPCS3.log.gz)
[RPCS3.log](https://github.com/user-attachments/files/16510946/RPCS3.log)

### System configuration

Windows 10
7800X3D
RTX 3060ti
32GB RAM

**Comment by Megamouse** [comment]
Someone changed the combos.

**Comment by scju** [comment]
> Someone changed the combos.
Oh, I’ve got it. We have to go to configuration > mice > basic mouse in RPCS3, and map buttons on Button 4 and 5.

I understand that the changes from that PR can have some benefits, but what if some people only have three buttons on their mice or if they have mapped the side buttons as other functions instead of the default settings (forward and back buttons), like I do? 

In these cases the changes might cause some trouble, so I’d suggest that sticking with the original settings would be better.

**Comment by FRANCKYNO** [comment]
> [scju](/scju)

I have the same problem, impossible to finish the calibration by pressing the middle button and the right button of the mouse. Please can you show me how to map buttons 4 and 5 ? (screenshots are welcome)
I have tried Mice->Basic Mouse and Mice->Raw Mouse but with no success.
Thank you very much

**Comment by scju** [comment]
> > [scju](/scju)
> 
> Please can you show me how to map buttons 4 and 5 ? (screenshots are welcome) 

![image](https://github.com/user-attachments/assets/39a9e90f-f17d-4ab6-a761-bf88e03da90d)

**Comment by Jayinem** [comment]
Seems the devs would at least make it where we can enter a combo like right click + middle click? I was stuck all day yesterday trying to figure out thinking it was my scripts but it was a regression. Oh well I'll get an older version of RPCS3.
