### ISSUE TITLE
[BLUS30528] Can't pass the calibration by using mouse as a light gun

### ISSUE THREAD

**Issue by scju** [RPCS3/rpcs3#15908]
### Quick summary

I know that since this Pull Request https://github.com/RPCS3/rpcs3/pull/15860
the PSMove mouse button bindings have been changed, so I've followed the new bindings, but it seems like I still can't confirm the calibration in Time Crisis: Razing Storm.

### Details

I have a five-button mouse (three buttons + two side buttons). I used to map the two side buttons as the middle button to perform a "middle mouse click" function. This is more convenient for me because I find it easier to use my thumb on the side buttons rather than my index finger on the original middle button.

However, due to the recent pull request, I had to reset the two side buttons to their original functions (moving backward and forward) to make them available as Button 4 and Button 5 in "Configuration - Mice - Basic mouse" in RPCS3.

Despite this adjustment, I still can't confirm the calibration in Time Crisis: Razing Storm. For some reason, it always seems to follow pattern (1), even when I press Mouse3.

Pattern (1): Mapping with Mouse3 not pressed:

Mouse1 = Trigger
Mouse2 = Move
Mouse4 = Circle
Mouse5 = Cross

Pattern (2): Mapping with Mouse3 pressed:

Mouse1 = Select
Mouse2 = Start
Mouse4 = Triangle
Mouse5 = Square

(From https://github.com/RPCS3/rpcs3/pull/15860#issue-2439053027)

I understand that the changes from that PR can offer some benefits, but what if some people only have three buttons on their mice, or if they have mapped the side buttons to other functions instead of the default settings (moving backward and forward), like I did?

In these cases, the changes might cause some trouble, so I would personally suggest sticking with the original settings.

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16536778/RPCS3.log.gz)
[RPCS3.log](https://github.com/user-attachments/files/16536780/RPCS3.log)

### Attach capture files for visual issues

![image](https://github.com/user-attachments/assets/e40e0485-8ac7-45c1-96e3-164e40302cce)

### System configuration

Windows 10
7800X3D
RTX 3060ti
32GB RAM

**Comment by Megamouse** [comment]
Mybe try with #15909

**Comment by scju** [comment]
> Maybe try with #15909

Tried. Still not working for me.

Recorded video: https://youtu.be/Sd5vm4kg37k

**Comment by Megamouse** [comment]
Attach the log file of that run (with my build)

**Comment by scju** [comment]
> Attach the log file of that run (with my build)

[RPCS3.log.gz](https://github.com/user-attachments/files/16539009/RPCS3.log.gz)
[RPCS3.log](https://github.com/user-attachments/files/16539010/RPCS3.log)

**Comment by scju** [comment]
> Attach the log file of that run (with my build)

If you still plan to keep the new mouse button bindings, could we have an option or something in RPCS3 to switch between the new bindings and the old ones?

That way, we can have the benefits of the new bindings while still allowing users with three-button mice to play Time Crisis: Razing Storm. 

Also, that would make it more convenient for users with five-button mice, who have mapped the side buttons to other functions instead of the default settings (moving backward and forward). They wouldn't have to change their mapping to play this game.

I hope my explanation makes sense.

I hope my explanation is helpful.

**Comment by Megamouse** [comment]
Seems to be working fine now for me. I also added that you can only use each button for one action.
So you won't accidentally use MB3 + MB1 and do T + Select at the same time.

It's kinda useless to "complain" about the mapping though, since you can just remap all the buttons anyway.
So no one forces anyone to use MB3 as middle mouse button.

**Comment by scju** [comment]
> It's kinda useless to "complain" about the mapping though, since you can just remap all the buttons anyway.
> So no one forces anyone to use MB3 as middle mouse button.

We can just remap all the buttons and no one forces anyone to use MB3 as middle mouse button. So:

I have a three button mouse (Logitech M525) with my notebook. Could you please tell me how I can use this mouse to pass the calibration in Time Crisis: Razing Storm with the new mouse button bindings? (which I could pass with the old mouse button bindings.)

Also, I use a five button mouse (Logitech M546) with my desktop computer and I'm used to mapping the side buttons as the middle middle mouse button for working and browsing. Could you please tell me how I can pass the calibration in this game without having to bother getting the side buttons back to their the default settings (backward and forward)? (which I didn't need to with the old mouse button bindings.)

Anyway, the new mouse button bindings seems to be working fine now.

**Comment by Megamouse** [comment]
Don't use a 3 button mouse. It's that simple.

**Comment by scju** [comment]
> Don't use a 3 button mouse. It's that simple.

For those of you who have three button mice, just don't use this PR and stick with [that one](https://github.com/RPCS3/rpcs3/pull/15853) for this game - it's even simpler and solves this problem once and for all.
:)

**Comment by TeteDampoule** [comment]
Hello,

I have exactly the same problem with a 5 button mouse. Pressing mouse 3 seems to have no effect.
I get Mouse4 = Circle only and it retry...
I guess i a m missing something

**Comment by TeteDampoule** [comment]
Thanks for the answer.
Still not working on my side.
I have a preconfigured drive from integrum retro for lightgun only. I will try to check this with him.
There might be some scripts that override all of this.
For my information, what does "gem" stand for ?
How to select this configuration instead of basic mouse yml file ?

**Comment by PoloniumRain** [comment]
I also have this issue, with both with Time Crisis: Razing Storm and Deadstorm Pirates. 

Can't get passed the calibration screens because the middle mouse button does not work.

From a quick search, many other people have this issue as well. For example, in the comments on [this video](https://www.youtube.com/watch?v=1IJCgECzQeM). There's at least 3 comments mentioning the middle mouse button problem, and they each have multiple likes. All the comments started around the time of pull request https://github.com/RPCS3/rpcs3/pull/15860.

I've tried two mice and a light gun, with both `basic` and `raw` handlers, and editing the `gem_mouse.yml` file as suggested in a comment above. Also tried going to: Configuration > Mice > Basic/Raw and remapping each button. Nothing works. This is on both Win10 and 11, with the latest update for RPCS3. These games (and probably many more) are no longer playable with a mouse or light gun because of this issue.

If this can't be properly fixed for a while, then can that pull request at least be reverted for the time being? This is a bigger issue than the issue in that pull request.

**Comment by SentinelSquadOne** [comment]
I was able to find a solution. I've made a post on reddit. Let me know if this works for you. This is using the latest version of RPCS3 as well. https://www.reddit.com/r/lightgunshooters/comments/1oa172v/time_crisis_razing_storm_calibration_using_mouse/

**Comment by scju** [comment]
> I was able to find a solution. I've made a post on reddit. Let me know if this works for you. This is using the latest version of RPCS3 as well. 

Thanks for the helpful reply. I also have some new findings regarding the latest version [0.0.42-19748 as of 2026-08-14].

In this build, we don't need to bother with the I/O tab at all. You can just leave it as is.

<img width="660" height="506" alt="Image" src="https://github.com/user-attachments/assets/723c32f7-d7fa-4d20-8879-f8c9f4c9d4b1" />

First, navigate to Configuration --> Devices --> Mice --> Basic Mouse.

<img width="558" height="561" alt="Image" src="https://github.com/user-attachments/assets/410e5960-b5a3-4c12-b25d-ee2b2a288ea9" />

As you can see, I'm only using two mouse buttons alongside three keyboard keys. This means this layout will work with practically any mouse on the market. We don't necessarily need one with side buttons. (By the way, you can clear a binding by right-clicking it.)

Next, go to Configuration --> Emulated Devices --> PS Move (Mouse).

<img width="326" height="1021" alt="Image" src="https://github.com/user-attachments/assets/991730a3-b5f1-40fb-99da-0cc54772bd49" />

Here, you can map out your buttons. In my layout, for example:

Mouse 6 (Button 6) [Start] is mapped to the Return key.
Mouse 8 (Button 8) [Triangle] is mapped to the Space key.

Once you're in-game and reach the calibration screen, you'll need to press Ctrl + F11 to switch to emulated devices.

<img width="430" height="103" alt="Image" src="https://github.com/user-attachments/assets/aa3be37a-c81f-42f5-94d5-6bdcd2ec04e3" />

<img width="1280" height="859" alt="Image" src="https://github.com/user-attachments/assets/887de8f3-88e2-4209-9a1f-04dd312b3084" />

Now you can start calibrating (I recommend switching to windowed mode so you can see the mouse cursor).

After finishing the calibration, press the Triangle button (Button 8) to confirm, and then press the Circle (O) button (Button 4) to exit.

When you are sent back to the title screen, press Ctrl + F11 again to switch back to regular pad mode.

<img width="363" height="103" alt="Image" src="https://github.com/user-attachments/assets/a90e0ae1-bab0-4774-afb9-0b9609c1cff2" />

<img width="1222" height="889" alt="Image" src="https://github.com/user-attachments/assets/028eab10-bed1-4d1e-9a55-f2eec64c3181" />

You can now use your keyboard to navigate the menu.

After actual gameplay starts, you'll have to toggle back to emulated devices one last time to play with the mouse.

<img width="430" height="103" alt="Image" src="https://github.com/user-attachments/assets/49d343b9-bdfe-4f81-b06d-61f584c2d975" />

<img width="1280" height="949" alt="Image" src="https://github.com/user-attachments/assets/b2bca23d-d2a8-4ad0-9ac4-8de1db576ce0" />

<img width="1280" height="944" alt="Image" src="https://github.com/user-attachments/assets/25647b8d-820f-4c0d-9dd9-a5eb0d49e074" />

Honestly, it’s a bit tedious, but at least we can now play the game using just a standard two-button mouse.
