### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by seth-aung** [RPCS3/rpcs3#15919]
### Quick summary

[Image of the error message](https://imgur.com/9vJxfI9)
Just reporting the error message that automatically freeze and crashed on home screen of god of war III after opened for a while.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16569197/RPCS3.log)

### System configuration

CPU - Ryzen 3 3600
GPU - RX 590 GME with latest AMD Adrenalin driver
RAM - Colorful Battle-AX 3200*8

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed

**Comment by FlexBy420** [comment]
You are not using wiki settings.
GitHub is not for support request, please ask in our discord of forum next time.
