### ISSUE TITLE
Remove rImage?

### ISSUE THREAD

**Issue by mpm11011** [RPCS3/rpcs3#1591]
rImage defines methods that wraps / casts wxImage objects in **Utilities/rPlatform.h**. As far as I can tell, nothing uses them, even the various renderers who include it "//only for rImage".

The only thing I can find that uses rPlatform.h is **/rpcs3/gui/RSXDebugger.cpp** and it only uses it for its definition of RSXDebuggerProgram.

Pursuant to removing wx dependencies from emucore, and unless we need rImage in the future, I suggest removing rImage references wherever possible. I can make a pull request if need be.

**Comment by MyaniPT** [comment]
rPlatform is removed in #1521

**Comment by mpm11011** [comment]
Crap. Should have checked there first. Thanks.
