### ISSUE TITLE
aarch64/llvm - Cannot run SPU binary more than once without rebooting the emulator

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#15912]
Running a SPU binary once is fine, but when attempting to re-run the same application (e.g the SPURS test binary) the emulator will hang.

**Comment by kd-11** [comment]
Oddly, the issue disappeared after a clean build. I'll keep it open in case I can reproduce.

**Comment by kd-11** [comment]
The issue vanished. Closing since it was already very low priority.

**Comment by Darkhost1999** [comment]
I believe this issue already has another ticket open and isn't limited to aarch64.
You can quickly trigger it by booting triangle test, cube test, spurs test, triangle, cube, spurs. It's rare to get the issue to trigger on booting the same .elf but you can trigger it with everything in your entire games library. You just gotta boot different things.
You increase the odds of encountering the error by opening file explorer and selecting the program/game/app you're going to boot. Rpcs3 will say Not Responding. Then will just stay like that until you force close the app.
