### ISSUE TITLE
Dynasty Warriors 8: Xtreme Legends、Dynasty Warriors 8: Empires、Warriors Orochi 3 Ultimate can play coop online

### ISSUE THREAD

**Issue by QJYEAH** [RPCS3/rpcs3#15922]
### Quick summary

Dynasty Warriors 8: Xtreme Legends（BLAS50672）
Dynasty Warriors 8: Empires（BLAS50778）
Warriors Orochi 3 Ultimate（BLAS50676）
can play coop online
RPCN server test success

### Details

![13987327608170217472_20240810203941_1](https://github.com/user-attachments/assets/859dafa1-f5a0-48ab-b238-0f8da29bab9e)
![13987327608170217472_20240810210637_1](https://github.com/user-attachments/assets/cf399547-4fdd-4d97-9be3-e77ff71c5b47)
![13987327608170217472_20240810214702_1](https://github.com/user-attachments/assets/d0501621-bce0-42d6-a512-9f9e7389bc3c)

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16570448/RPCS3.log)

### System configuration

4070Ti+5700X3D

**Comment by AniLeo** [comment]
The ticket does not state any issue whatsoever. Closing as non actionable.
