### ISSUE TITLE
[Feature request] Change user before entering the game/emulator

### ISSUE THREAD

**Issue by Hordbrok** [RPCS3/rpcs3#15920]
### Quick summary

An more direct way to change the user profile

### Details

Hi! Thank you for reading this
I would want another way to change the user profile you start a Game with Instead of manually go to the menu and change the profile 

Like in yuzu or cemu. You can add a launch command in the shortcut ("-u 1") to start with one user or another

With the implementation of a game in steam (like a shortcut) that would make things easier. Specially when the game is added in a Steam Deck

**Comment by Megamouse** [comment]
Already implemented.
It's called --user-id 
Thanks for the effort
