### ISSUE TITLE
Tekken 6

### ISSUE THREAD

**Issue by Michal1988555** [RPCS3/rpcs3#15935]
### Quick summary

There are graphical glitches in Manji Valley stage in Vulkan renderer. Some background textures are blurry, some of them do not even showing properly, for example rocks. Opengl renderer works fine.

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16603303/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Does not follow the template, no screenshot comparison between renders, no RSX capture
