### ISSUE TITLE
Vulkan  Koihime Enbu [BLJM61274] Issue

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1594]
@vlj 

[f99e4f84]
GPU Nvidia [GTX 650TI]
Forum : http://www.emunewz.net/forum/showthread.php?tid=174272
Log : https://gist.github.com/SakataGintokiYT/998957a1c09222c15e7f

<img src="http://www.fotoszok.pl/upload/25af482b.jpg" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">
<img src="http://www.fotoszok.pl/upload/fd4e2ddd.jpg" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">
<img src="http://www.fotoszok.pl/upload/335e8f6e.png" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">

**Comment by SakataGintokiYT** [comment]
[b748a71c]
Better :)
<img src="http://www.fotoszok.pl/upload/7f643dff.png" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">
<img src="http://www.fotoszok.pl/upload/a82b2373.png" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">
<img src="http://www.fotoszok.pl/upload/177536e8.png" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">

**Comment by SakataGintokiYT** [comment]
@vlj 
[a0444bf1] :) :+1: 
<img src="http://www.fotoszok.pl/upload/d7129486.jpg" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">
<img src="http://www.fotoszok.pl/upload/6f7d75c8.jpg" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">

**Comment by SakataGintokiYT** [comment]
@tambry 
[edc8b77d]
#1653 
*Vulkan
<img src="http://www.fotoszok.pl/upload/5e77b376.jpg" alt="Fotoszok.pl" />

**Comment by tambry** [comment]
@SakataGintokiYT Is it supposed to look so blue?

**Comment by danilaml** [comment]
@tambry maybe it's those two texture types in upper right corner with R and B channels swapped.

**Comment by SakataGintokiYT** [comment]
@tambry 
http://www.presstartoplay.com/wp-content/uploads/2016/03/ke_3-e1457259473724.png
http://www.presstartoplay.com/wp-content/uploads/2016/03/ke_2-e1457259438579.png

**Comment by tambry** [comment]
@danilaml  @SakataGintokiYT  Seems like it. I already spent an hour trying to get them switched properly. Can't figure it out for the life of me :(
@danilaml  I also think you mean the bottom middle one?

**Comment by SakataGintokiYT** [comment]
@tambry  Blue color is only on gui
<img src="http://www.fotoszok.pl/upload/0d79ce5c.jpg" alt="Fotoszok.pl" />

**Comment by danilaml** [comment]
@tambry you can ping @vlj and see if he can help.

**Comment by tambry** [comment]
@SakataGintokiYT Could you check again, once https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.2092 finishes building?

**Comment by SakataGintokiYT** [comment]
@tambry :+1: 
*Vulkan
<img src="http://www.fotoszok.pl/upload/85a2004e.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/4755d90c.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/277e0bde.jpg" alt="Fotoszok.pl" />

**Comment by danilaml** [comment]
@SakataGintokiYT nice! What about dx12?

**Comment by SakataGintokiYT** [comment]
@danilaml  No change ;/ http://www.fotoszok.pl/upload/f907c96a.jpg

**Comment by danilaml** [comment]
@vlj can you look at why dx12 is failing while Vulkan does not?

**Comment by vlj** [comment]
I'm investigating

**Comment by SakataGintokiYT** [comment]
Fix on dx12 by commit 1709

**Comment by danilaml** [comment]
Is it still an issue?

**Comment by SakataGintokiYT** [comment]
Fixed
