### ISSUE TITLE
[Regression] Metro Last Light: Black screen on menu and screen freeze on game after #15201

### ISSUE THREAD

**Issue by digant73** [RPCS3/rpcs3#15954]
### Quick summary

With #15201, applying the default settings on wiki page the game shows a black screen for the game menu although the game is not frozen and you can load (pressing on pad's X button) the last game save but then the screen is frozen while audio is ok.

In order to fix the issue I had to switch **SPU XFloat Accuracy** to **Accurate XFloat** on the CPU tab.

### Build with regression

rpcs3-v0.0.30-16093-50b1402d_win64

### Attach two log files

[RPCS3.log.gz](https://github.com/user-attachments/files/16639893/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Not a valid regression, if the game works with accurate xfloat then everything is fine.

**Comment by digant73** [comment]
> Not a valid regression, if the game works with accurate xfloat then everything is fine.

ok, but the wiki should be updated (the game is reported as playable).
Also, setting a high resolution (e.g. 1080, 1440 etc.) the foliage/trees are horrific (it appears as not rendered with the right resolution or with no antialiasing). To fix this issue you have to apply the following settings:
* Force CPU Blit Emulation on Debug tag (this tab is not even available by default)
* Write Color Buffers on GPU tab

Also, for each game's wiki page it should be reported the RPCS3 release where the game was certified for the reported settings. It will help the people testing and providing feedback on this repo.
If a user is not interested to waste his time using the latest RPCS3 release helping the project with bug report etc., he will simply have a look to the certified date reported for the game on the **Compatibility** column present on RPCS3 main menu and he will download and use one of the versions close to that data.
IMO, the missing release version on games's wiki page encourages more the people to not waste their time on providing support to the project

**Comment by AniLeo** [comment]
You can already see the tested build on the compatibility list entry, no need to duplicate said data on the wiki.

For the edit on the wiki page, I can't add it at the moment, anyone can edit the wiki page and add the required settings there.

**Comment by digant73** [comment]
> You can already see the tested build on the compatibility list entry, no need to duplicate said data on the wiki.
> 
> For the edit on the wiki page, I can't add it at the moment, anyone can edit the wiki page and add the required settings there.

ok, thanks for the info
