### ISSUE TITLE
DS3 pad vibration not properly disengaged

### ISSUE THREAD

**Issue by digant73** [RPCS3/rpcs3#15955]
### Quick summary

Just experiencing on two of my three DS3 pads an issue present on all the games frequently providing vibration (such as shooting games) like killzone 3, resistance 3 etc. It happens frequently that when vibration is engaged then it is not properly disengaged; the pad remains on vibration and I typically need (sometimes it works other times it doesn't) press on pad's buttons/stick to disengage the vibration.
The issue is present either the pad is connected via cable or wireless.

I tested the pads on my PS3 and the issue is completely absent (all my 3 pads perfectly work).

The issue is present since about 1 month ago when I started to use RPCS3 (so I have no history if the issue was not present in the past).

Attached a log file for the issue on killzone 3 but, as I said, the issue is present also on other games (e.g. resistance 3 etc.).

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16640670/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Can you try with #15957 and post a log when it happens please?

**Comment by digant73** [comment]
> Can you try with #15957 and post a log when it happens please?

ok

**Comment by Megamouse** [comment]
I've added a minimum update interval of 100ms to the rumble output.
Maybe it helps...
Can you try the new build please?

**Comment by digant73** [comment]
> I've added a minimum update interval of 100ms to the rumble output. Maybe it helps... Can you try the new build please?

it fixed the vibration issue and even more important it is now hugely more smooth and reactive as the feeling I have on PS3. Now the camera movement (e.g. 360 rotation), aim etc. is also faster and comparable with the PS3 (of course using the same game settings), also tested on other games (e.g. Resistance 3 etc.) with the same improvements. 
I see that 100ms seems to be too much because on a single shot there is no small vibration, I have to use a long press (continuous shot) before the vibration is engaged.
I will make some testing changing the delay just to have the same feeling I have on PS3 and let you know.
I currently tested DS3 only but I will also make some testing with dualsense (maybe it is not affected by the issue at all).
If this delay could be made configurable on GUI it should be probably the best solution.
Thank you very much for the quick fix

attached the log file with your fix

[RPCS3.log.gz](https://github.com/user-attachments/files/16645118/RPCS3.log.gz)

**Comment by Megamouse** [comment]
It's not a delay. It's just making sure the vibration is sent continuously.
The delay does usually not exist at all, so I think you're just having either some really bad controllers or some really bad usb hub or interference or whatever.

This PR also doesn't change anything regarding the input, so I think you're just experiencing a placebo.
Unless you're using a shitty driver that has an input delay unless you send data continuously to it.

**Comment by digant73** [comment]
> It's not a delay. It's just making sure the vibration is sent continuously. The delay does usually not exist at all, so I think you're just having either some really bad controllers or some really bad usb hub or interference or whatever.
> 
> This PR also doesn't change anything regarding the input, so I think you're just experiencing a placebo. Unless you're using a shitty driver that has an input delay unless you send data continuously to it.

As drivers on Win 11 I'm using dshidmini_v2.2.282.0 and BthPS3 as suggested for RPCS3. I also have original PS3 controllers.
Pretty much sure I had also bad responsiveness but not reproduced retesting the current RPCS3 version and your PR. So yes I agree, forget my previous statement about a better feeling (maybe Win 11 needed a restart after some RPCS3 crashes).
I usually restart win 11 after RPCS3 crashes etc. just to start from scratch.
With dualsense I have no issue.

Anyway, I confirm that with your PR I have no more wrong vibration while it is present on current RPCS3 version. I also confirm that all the 3 DS3 controllers properly work on PS3.

thanks again for the support

**Comment by Megamouse** [comment]
Thanks for confirming 👍
