### ISSUE TITLE
[Regression] ONE PIECE PIRATE WARRIORS 1 & 2

### ISSUE THREAD

**Issue by JohnSmithSor** [RPCS3/rpcs3#15958]
### Quick summary

One Piece Pirate Warriors 1 & 2, used to work three or four versions ago from today 

Now the clothes and faces, and even the sea don't appear. 
Gameplay also lags 

### Details

Pirate Warriors 2 the 
![FailedOnePiece](https://github.com/user-attachments/assets/9ef88d76-a448-4159-96bf-cf28237db16a)

### Build with regression

v0.0.32-16834-b2877365 Alpha | master

### Attach two log files

I can't drag and drop
It won't let me

### Attach capture files for visual issues

j

### System configuration

Win 10, i7, intel 630. 

### Other details

It used to work 3 or 4 versions ago, but the newest version 
- SYS: RPCS3 v0.0.32-16834-b2877365 Alpha | master
- refuses to render, faces, sea, sandels are pink, etc. 
- gameplay lags,

**Comment by AniLeo** [comment]
Invalid regression report, closing as Invalid. Blames the wrong build, one that only changed GUI input code, didn't upload the two required log files.

**Comment by JohnSmithSor** [comment]
> Invalid regression report, closing as Invalid. Blames the wrong build, one that only changed GUI input code, didn't upload the two required log files.

Bruh, How am I supposed to do this
1. the log file doesn't upload
2. Idk how to check the previous version or when it did used to work 

The issue isn't invalid because I can't meet your strict criteria

**Comment by AniLeo** [comment]
This is the most basic criteria possible for a regression report. If you need support, GitHub is not the place, Discord or Forums are.
