### ISSUE TITLE
vk: Support v3dv driver

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#15969]
Currently, v3dv will fail to boot due to reported missing feature textureCompressionBC. As pointed out on [v3dv: dxvk not working](https://gitlab.freedesktop.org/mesa/mesa/-/issues/4792), the feature is partially supported for BC1-BC3.

Ignoring this check in rpcs3 allows the Vulkan render to work with the v3dv driver, even though the driver is quite unstable at the moment as of Mesa 24.1.6 compared to the v3d OpenGL driver, which works quite well.

**Comment by kd-11** [comment]
We only use BC1-BC3 in rpcs3, so this is sufficient.
