### ISSUE TITLE
Vulkan Bomberman Ultra [NPUB30051] Issue

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1596]
@vlj 
@kd-11 
[f99e4f8]
GPU Nvidia [GTX 650TI]
Log : https://gist.github.com/SakataGintokiYT/e36f99ce8c7a6322c98c
Freezing after pressing X

<img src="http://www.fotoszok.pl/upload/7e878d0c.jpg" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">
<img src="http://www.fotoszok.pl/upload/dcfe0cc0.png" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">

**Comment by tambry** [comment]
Could you check with #1653, once it finishes building?

**Comment by SakataGintokiYT** [comment]
@tambry 
<img src="http://www.fotoszok.pl/upload/eb33932e.jpg" alt="Fotoszok.pl" />

**Comment by raven02** [comment]
@SakataGintokiYT , please close this one . It is duplicate of Vulkan scaling issue #1655
