### ISSUE TITLE
《DYNASTY WARRIORS 8: Xtreme Legends》.this game still crashed and Explosive sound

### ISSUE THREAD

**Issue by QJYEAH** [RPCS3/rpcs3#15967]
### Quick summary

《DYNASTY WARRIORS 8: Xtreme Legends》（BLAS50672）
This game still crashed and Explosive sound
![爆音](https://github.com/user-attachments/assets/01891d84-5ad7-47b5-bcba-d0536dac5cdc)

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16656337/RPCS3.log.gz)

### System configuration

4070Ti + 5700X3D

**Comment by AniLeo** [comment]
Non actionable ticket, no steps to reproduce the crash, the uploaded log file is empty, no video recording of the issue as there's a sound problem, no proper information in the system configuration. Closing as Invalid.
