### ISSUE TITLE
Vulkan Dragon Ball Z: Burst Limit [NPUB90106] Issue

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1597]
@vlj 
[f99e4f84]
GPU Nvidia [GTX 650TI]
Log : https://gist.github.com/SakataGintokiYT/67bac28c38d0fd01ae48

<img src="http://www.fotoszok.pl/upload/dc3e55ec.jpg" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">

{rsx::thread} RSX: Primitive restart enabled!
_______________________________________________________________________
{rsx::thread} Exception: Assertion failed! Result is C4650338h
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKTexture.cpp:160, in function vk::texture::create)

**Comment by vlj** [comment]
Does any other game work ?

**Comment by Ekaseo** [comment]
this game goes into main menu for me and even into character select, but it stops rendering once you start selecting your partners abilities. (fps and music continues, but the image is frozen)

**Comment by SakataGintokiYT** [comment]
Arkedo Series Pixel / Swap  works perfect

**Comment by vlj** [comment]
What about other 3d game ?

**Comment by SakataGintokiYT** [comment]
_________________________________________________________________________
G-Force
Loadable FPS and freezing on black screen
{rsx::thread} RSX: Program destructor invoked!
_________________________________________________________________________
Ice Age: Dawn of the Dinosaurs
Loadable FPS and freezing on black screen
{rsx::thread} RSX: Program destructor invoked!
_________________________________________________________________________

Dragon Quest Builders :
Freezing after loading screen
{rsx::thread} RSX: Program destructor invoked!
_____________________________________________________________________
Legend of kay anniversary
Freezing after logo ' Nordic Games '
RSX: Program destructor invoked!

_________________________________________________________________________
Dragon Ball: Xenoverse
{rsx::thread} RSX: Program destructor invoked!
{rsx::thread} RSX: Warning, version 450 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:80: '' :  syntax error
ERROR: 1 compilation errors.  No code generated.
{rsx::thread} RSX:

**Comment by kd-11** [comment]
@SakataGintokiYT The error about program destructor is not really an error. I really should remove it since it seems to confuse people. Look for fatal exceptions, largely related to "bad texture alignment computation" or such. Does the fps counter continue after freezing?

**Comment by kd-11** [comment]
I've finally seen some games with black textures on radeon. I'm not sure whether to wait for vlj to submit his fix, but i'll work on it as well.

**Comment by SakataGintokiYT** [comment]
@kd-11 
FPS / Freeze

**Comment by vlj** [comment]
I have a fix for the freeze with nvidia pre GM 204 (ie kepler, GM200) but I still need to work on it.

**Comment by SakataGintokiYT** [comment]
GTX 650 Ti  [NVIDIA Kepler GK106]

**Comment by vlj** [comment]
This PR is not a fix for this bug. The fix is on vulkan-wip

**Comment by SakataGintokiYT** [comment]
[a0444bf1] :+1: 
Now Works 
G-Force
Legend of kay anniversary
Ice Age: Dawn of the Dinosaurs
Dragon Ball Z: Burst Limit \
Dragon Ball: Raging Blast 1
