### ISSUE TITLE
arm64: Implement CPU name detection

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#15972]
Currently we're returning a stubbed "Unidentified CPU" for the CPU name on arm64 builds. This is a TODO to implement.

**Comment by kd-11** [comment]
This one is actually quite trivial on linux. Not sure about BSD though.

**Comment by kd-11** [comment]
Someone collected the cpuinfo details here: https://github.com/hrw/arm-socs-table/tree/main/cpuinfo-data
The normal way to read the data on ARM is somewhat like vulkan. You read a register that has a bunch of IDs and it is up to you to tie them to CPU names. Annoying to maintain, but not really difficult.

**Comment by kd-11** [comment]
Easier to parse list of part numbers: https://github.com/gcc-mirror/gcc/blob/master/gcc/config/arm/arm-cpus.in
