### ISSUE TITLE
Add button polling rate to GUI

### ISSUE THREAD

**Issue by iamthehorker** [RPCS3/rpcs3#15984]
### Quick summary

The recent [commit 72cccb6](https://github.com/RPCS3/rpcs3/commit/72cccb691c7bd32bdccea2617b703cb0ceb8d026) reduced button polling from 1000 Hz to 100 Hz. While this is good to reduce overhead, it can potentially increase latency given that some pc peripherals may have polling rates of up to 1000 Hz.

Could this value be exposed in the GUI so that users may set the polling rate higher (i.e., 1000 Hz) if desired?

**Comment by elad335** [comment]
This is only affecting the pad settings dialog (the commit you mentioned)

**Comment by iamthehorker** [comment]
If that's the case then I'll close this (oops)

**Comment by iamthehorker** [comment]
If that's the case then I'll close this (oops)
