### ISSUE TITLE
[Regression] [macOS] [Arm] Apple Clang build fails after PR 15974 (Rework aarch64 signal handling)

### ISSUE THREAD

**Issue by shinra-electric** [RPCS3/rpcs3#15980]
### Quick summary

RPCS3 no longer builds for an Arm target with Apple Clang after #15974 

### Details

 `FAILED: rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/CPU/Backends/AArch64/AArch64Signal.cpp.o ` 

### Build with regression

PR #15974

### Attach two log files

[Terminal Saved Output.txt](https://github.com/user-attachments/files/16709241/Terminal.Saved.Output.txt)

**Comment by kd-11** [comment]
Oops. I forgot about other OSes.
I think the darwin kernel is source-available since I remember looking through it's code years ago. I'd have to figure out where they're hiding their ESR context if at all.
I'll push a PR to null that out and force it to use the instruction decoder fallback which is buggy. At least until I start onboarding macos.

**Comment by shinra-electric** [comment]
> I think the darwin kernel is source-available since I remember looking through it's code years ago.

I don’t think they publish Darwin anymore, but the source for many components are still available [here](https://opensource.apple.com/releases/).

The [PureDarwin](https://github.com/PureDarwin/PureDarwin) project might also be a useful reference.

**Comment by kd-11** [comment]
Thanks guys. Both the apple xnu sources as well as pure-darwin contain what I need. I'll push a PR for this soon.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/15987 should support darwin, though I haven't tested. I'll try and build rpcs3 arm on macos though from memory it was a painful experience. If you can get it to build, let me know.

**Comment by shinra-electric** [comment]
PR 15987 is building fine for me. 

If it will save you some time, I have my arm build script on GitHub [here](https://github.com/shinra-electric/RPCS3-Arm-Build-Script). It includes a few workarounds for cubeb and ffmpeg to help it build, and it makes changes to the info.plist and icon so the app bundle is different to the x86 build.
