### ISSUE TITLE
[Feature request] BLUS30528 Time Crisis 4 -  coop mode doesnt fill the screen - scaling issue?

### ISSUE THREAD

**Issue by bro007-eng** [RPCS3/rpcs3#15989]
### Quick summary

When playing single player the playing area fills the entire screen playing Time Crisis 4 via BLUS30528

However, when in coop mode, 4/5's of the screen is only filled and won't fill the screen entirely.

### Details

Would be great to allow the game to be scaled to fill the entire screen rather than just 4/5's of it?  Example attached in coop mode.  Not trying to compare, however this for Time Crisis 2 or 3 via PCSX2 doesnt exist :(

![image](https://github.com/user-attachments/assets/11808688-490a-4435-9bba-a4fc06f706bf)

**Comment by Megamouse** [comment]
I don't think this is a bug.
The game is probably just programmed to show each player in a 4:3 window

**Comment by bro007-eng** [comment]
Thanks for the consideration. So was wanting to understand if there is a current way to scale it to fill the screen now or could be considered as a feature into the future.  Thank you.
