### ISSUE TITLE
[Feature request] Some minor changes on game's contextual menu

### ISSUE THREAD

**Issue by digant73** [RPCS3/rpcs3#15994]
### Quick summary

Some items on the game's contextual menu such as:
- `Rename In Game List`
- `Hide in Game List`
- `Open Install Folder`
- `Open Custom Config Folder`
- `Open Cache Folder`

are quite rarely used compared to `Change Custom Configuration`, `Manage Game Patches` etc. and could be organized in the following new sub menus:
- `Manage Game`:
  - `Rename In Game List`
  - `Hide in Game List`
  - `Download Updates`: a new item to propose all the available updates for the game (as in the bot-spam) allowing to install them one after another instead of using the general **Install Packages/Raps/Edats** present on the **File** menu and spending a lot of time when many updates are available (e.g. about 20 updates for GT6)
  - `Remove Updates`: a new item allowing to remove all or the latest updates on top of the base game
  - `Remove Game`: a new item allowing a clean removal of the game and its related contents (game data, game save, trophy etc.) instead of doing it manually (removing folder, files here and there) to much prone to mistakes (e.g. accidentally remove wrong files etc.)
  - and so on
- `Open Folder`:
  - `Open Install Folder`
  - `Open Custom Config Folder`
  - `Open Cache Folder`

making them similar to other already existing sub menus such as:
- `Create Shortcut`
- `Remove`
- `Custom Images`
- `Copy Info`

This will make the context menu light, more readable and organized for future additions

**Comment by Megamouse** [comment]
The stuff you mention in "Manage Game" doesn't make much sense.
First of all, RPCS3 is never going to allow you to download game content.
Next, game updates can not be distinguished from HDD games, so this point is not possible.
For disk games you can just delete the game data in the list, so there is no real point in adding this extra menu item just for disk games.
The new "Remove Game" option doesn't make much sense either.
There already is a remove game option that asks if you want to delete all the caches and configs.
Usually you wouldn't want to remove trophies or savegames, so I don't think adding this here for people to trip over is a good idea either.

So there's really only the two gamelist options and those "open folder" options that may end up saving like 3 lines in the menu at most.

**Comment by kd-11** [comment]
We do need to restructure the menu somehow. I've ended up clicking the wrong button many times while most of the time I just need to create custom config based on default settings or run the game.

**Comment by digant73** [comment]
I provided just a list of possible enhancements if possible.

For the game updates I thought to something similar on bot-spam where you provide the game ID and a list of all the available updates are provided and possibly you could simply press on a button to install all of them one after another without the need to browse, confirm etc. as it is now from the `File` menu, For checking regression PRs I have more than 30 RPCS3 releases at the moment and for each of them I have to manually add the games and updates. That should give you the idea of how many times is spent.

For the game remove, I meant at least to allow (via an easy dialog menu) to delete the entry from Games.yml and the installed data (it's ok if data + updates are seen as a unique installed data and so removed together). Installed data for some games could be several GB so a clean removal is not bad. As optional, the dialog menu could give also the possibility to select to remove trophies, save games etc.

Yes, at least (without the above mentioned possible features) The `Manage Game` and `Open Folder` menus will contains 5 items. It seems to me more organized as made with other sub menus (e.g, Remove etc.).

No problem if there is no interest on that FR. You can close it at any moment.

**Comment by digant73** [comment]
> We do need to restructure the menu somehow. I've ended up clicking the wrong button many times while most of the time I just need to create custom config based on default settings or run the game.

that is what I also do all the time repeated in about 30 RPCS3 releases for a total of about 1 TB at the moment and the installation of the games' updates is a pain (too much manual)

**Comment by Megamouse** [comment]
As I said, there won't be links or direct downloads to game content.

You don't have to install the games 30 times.
You can just rename the exe and put it in the same folder, unless there's a reason that it's related to game files.

**Comment by digant73** [comment]
> As I said, there won't be links or direct downloads to game content.
> 
> You don't have to install the games 30 times. You can just rename the RPCS3.exe and put it in the same folder, unless there's a reason that it's related to game files.

ah ok, I was supposing there was no particular problem to allow download of games updates from the application.
Yes, I prefer to uses different releases with the related game files (more easy to jump from one release to another, use proper game's conf file, collect rsx capture, log etc.)

**Comment by Megamouse** [comment]
You can also use the vfs to share the games between separate builds.

**Comment by digant73** [comment]
all the dumps of my games are on a dedicated HDD and of course all the RPCS3 releases share only one copy of the same game. Installed data, game save etc. are clearly duplicated by each RPCS3 release
