### ISSUE TITLE
RPCS3 Not working after PC restart

### ISSUE THREAD

**Issue by Ryster06** [RPCS3/rpcs3#15997]
### Quick summary

when i reinstall my drivers, my rpcs3 wont open after restarting my pc

### Details

after using DDU and reinstalling drivers (and installed vulkanSDK) my RPCS3 worked, BUT after i restart or shutdown my pc in anyway it refuses to start again! i cant see the full error of when it breaks, but i will send the window it shows when i spam it..

### Attach a log file

![image_2024-08-25_132321841](https://github.com/user-attachments/assets/b3fa13e5-ee15-4d15-9621-6ee1cf613080)
[RPCS3.log](https://github.com/user-attachments/files/16741549/RPCS3.log)

**Comment by Ryster06** [comment]
also, ive done the ddu and reinstall twice now and both times it works UNTIL i restart my pc, thank you in advance! :)

**Comment by Refragg** [comment]
Hello, from the error message, it seems that your RPCS3 install is in a temporary directory that probably gets cleaned up on reboot. You should try moving / extracting RPCS3 to another folder.

**Comment by RipleyTom** [comment]
The bug tracker is for bug reports, not for support.

**Comment by ReLyf47** [comment]
Should be reopened IMO
Looked at the log and the "temp" is actually just an error from RPCS3 pointing out a .cpp from cirrus-ci build path (not a user thing)

**Comment by AniLeo** [comment]
The paths from compile time are completely irrelevant for anything, not sure why even mentioning them. Locking as already answered.
