### ISSUE TITLE
Open RSX Capture fails to open any compressed file (with extension rrc.gz)

### ISSUE THREAD

**Issue by digant73** [RPCS3/rpcs3#16000]
### Quick summary

If the `Open RSX Capture` function available on `Utilities` menu was meant to open also compressed files (.gz) without the need to manually uncompress them then it is currently not working.
Below an example of the error reported when trying to open a .rrc.gz file:

E SYS: Invalid rsx capture file!
E GUI: Capture Boot Failed. path: E:/PS3/programs/rpcs3-v0.0.32-16614-5b973448_win64/captures/BCES01118_20240826124519_capture.rrc.gz

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16748757/RPCS3.log.gz)

**Comment by kd-11** [comment]
It is not meant to open compressed files.

**Comment by digant73** [comment]
> It is not meant to open compressed files.

ok thanks for the reply, I suspected that, but shouldn't it be better to remove the `rrc.gz` and `RCC.GZ` filters so you will see only the file format that the application is able to load?

**Comment by elad335** [comment]
it supposed to.

**Comment by digant73** [comment]
> it supposed to.

I originally thought that one of the updates on 3rd party libs (7zip for that possible issue) was possibly the cause for that issue and so opened this bug report

**Comment by digant73** [comment]
Regression identified in #15587.
Regression traced by #16003.
