### ISSUE TITLE
[Bug] [macOS arm64] Creating launchpad shortcuts is broken in numerous ways

### ISSUE THREAD

**Issue by schm1dtxbox** [RPCS3/rpcs3#16017]
### Quick summary

Here's a quick list of the issues:
1-It tries to create the shortcut in the per-user ~/Applications folder, one that doesn't exist on fresh macOS installs since only the global system-wide /Applications folder is present, but doesn't attempt to create said folder and bails.
2-The shortcut fails to create an icon on the game I tested, God of War: Ghost of Sparta PSN.
3-The shortcut demands Rosetta to be installed despite being a simple launch script, due to errors in the generated Info.plist file.

### Details

Point 1 (issues with per-user Applications directory) was well described as before, I needn't elaborate further beyond saying that installing in the global Applications folder may make more sense by default, and to only install to the per-user Applications folder if, say, RPCS3 is launched from there and not the global folder most people will place it in.

Point 2 (icon creation failure) I am unsure about the cause of, but log complains that the image format is unsupported so I assume it's some weird issue relating to that.

Point 3 (prompts for Rosetta 2 wrongly) is simple enough to resolve, Info.plist lacks these entries, adding them will ensure native execution on arm64 without unnecessarily prompting for Rosetta 2 installation purely to launch what is merely a shell script:
```   
        <key>CFBundleIdentifier</key>
    	<string>net.rpcs3.GAMEID</string>
    	<key>LSArchitecturePriority</key>
    	<array>
        	<string>arm64</string>
    	</array>
    	<key>LSRequiresNativeExecution</key>
    	<true/>
```
GAMEID should be filled out appropriately per game, e.g. NPEA00309 and whatnot, so each shortcut app bundle remains unique per-game. A bundle identifier is necessary for macOS to view the bundle as 'valid' enough to launch without prompting for Rosetta 2, so there's no skipping it. 

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16804831/RPCS3.log)

Log above is in plaintext since it's small enough, contains an attempted shortcut creation with ~/Applications (the per user one) not present, and an attempted one with it present (latter demonstrates icon creation failure, but the shortcut bundle still creates successfully otherwise despite what log says).

### System configuration

OS: macOS Sequoia 15.0
Hardware: MacBook Air M2
RPCS3 version: Local compile of latest master as of issue creation, commit [4d193ec](https://github.com/RPCS3/rpcs3/commit/4d193ecb6aa24a747848f87238bd60c363fa106a).
Compiled using a relatively modified fork of shinra-electric's build script, I just tweaked it to work with GH Actions, be more consistent with how x86-64 is currently built on CI and ensure the resultant bundle is portable and independent of Homebrew. Link to said edited script is here: https://github.com/schm1dtxbox/RPCS3-Arm-Build-Script/blob/main/build_rpcs3.sh

**Comment by kd-11** [comment]
No idea who implemented the macos shortcuts. Maybe @nastys ?

**Comment by Megamouse** [comment]
Maybe try with #16125
