### ISSUE TITLE
[SCEEXE000]Regarding the "System Error 19-2" that occurs when starting "Taiko no Tatsujin"

### ISSUE THREAD

**Issue by akiaki102102** [RPCS3/rpcs3#16012]
### Quick summary

![Screen_shot1](https://github.com/user-attachments/assets/f97f053b-b7d6-4496-801a-5abb0ddef15c)
![Screen_shot2](https://github.com/user-attachments/assets/7b00bd8c-c83a-444e-a2bf-d31c79ad26d3)
When I start Taiko no Tatsujin, the message "19-2 System Error" appears and I cannot play the game.

### Details

After looking into it, I found that it seems to be related to "SECURITY CHECK 2" which has been flagged as NG, but I don't know the details.

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16783882/RPCS3.log.gz)

**Comment by clienthax** [comment]
Iirc check 2 was the usb Auth check, have you put the dongle vid/pid in?

**Comment by clienthax** [comment]
It also might be related to sys_game_board

**Comment by akiaki102102** [comment]
Thank you for your reply!
I checked the VID, PID and serial in the device manager and entered them again in RPCS3, but the error still occurs.
I also looked up "sys_game_board" but couldn't find any information. If you don't mind, I would appreciate it if you could let me know.
