### ISSUE TITLE
Demon Souls shows black screen in Ubuntu 22.04 and RX Vega 56

### ISSUE THREAD

**Issue by nioroso-x3** [RPCS3/rpcs3#16027]
### Quick summary

Demon Souls is not working on Linux using the default open source drivers in ubuntu 22.04 for an AMD RX Vega 56.

### Details

It just shows a black screen in both opengl and vulkan. Other games like Armored Core 4 work. The game logic seems to be running as it responds to controller inputs and I can hear the menu sounds. On Windows everything works correctly. Write Color Buffers is enabled.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16827477/RPCS3.log)

### Attach capture files for visual issues

[BLUS30443_20240901013718_capture.rrc.gz](https://github.com/user-attachments/files/16827490/BLUS30443_20240901013718_capture.rrc.gz)

### System configuration

Core i7 6700, AMD RX Vega 56, 16 GB 3200mhz

**Comment by Jonathan44062** [comment]
Bad settings and old firmware, next time, ask for support in RPCS3 Discord Server, not here
