### ISSUE TITLE
[Feature request] Expanded Rich Presence 

### ISSUE THREAD

**Issue by 19Aidan** [RPCS3/rpcs3#16029]
### Quick summary

Discord since added activities (in beta) and emulators like PCSX2 and Duckstation have expanded. why not RPCS3?

![image](https://github.com/user-attachments/assets/a7ef4261-c5d7-4a44-9be7-25cb887fd3ab)

RPCS3 has Rich Presence but its just the emulators logo and the game title. What I have in mind is action/location and changing that logo to the cover or at least part of the cover. Let me know what you all think on the idea.

**Comment by Megamouse** [comment]
I'll close this as a duplicate of #14937
