### ISSUE TITLE
[Bug] Debugger stops working when closing it and reopening it after rebooting a game.

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#16042]
### Quick summary

1 - Boot a game.
2 - When it's fully loaded, open the debugger.
3 - select a thread and close the debugger.
4 - close the game.
5 - reboot the game.
6 - Open the debugger when it's fully loaded.
Now it thinks that no thread is selected, and refuses to select any other thread, untill you'll restart the game.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16872492/RPCS3.log)

### Attach capture files for visual issues

https://github.com/user-attachments/assets/819bac07-d33f-429f-ac98-71fbe15f1be9

### System configuration

doesn't matter

**Comment by Megamouse** [comment]
You know all of your mp4s don't work, right?

**Comment by Hasster1** [comment]
> You know all of your mp4s don't work in github, right?

I... I thought it was an issue on my end.... Thanks for telling me XD
