### ISSUE TITLE
[Feature request] Force-stopping all threads

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#16045]
### Quick summary

Force-stop every thread when holding the stop-button for a certain period of time, to get around "busy" threads.

### Details

Every time i mess around with game's memory in a wrong way, or when a video driver crashes, one of the threads gets "busy", and rpcs3 can't do anything about it.
Trying to close rpcs3 with an x button only closes the GUI, the rpcs3 process is still going to keep working.
The only way to stop it - is to kill the process through the task manager, which is kinda annoying.

What i suggest, is an ability to hold the stop button for around 5 seconds to force-stop every thread (if that is even possible from within rpcs3).

Sorry if another issue was created about that, couldn't find anything.

**Comment by Megamouse** [comment]
This is extremely dangerous and I'm against it.
Data or progress may be lost if a user does this by accident.

**Comment by Hasster1** [comment]
In that case just add a pop-up window with a warning. Other emulators do the same thing.

**Comment by elad335** [comment]
It's implemented I'm pretty sure, but not after a 5 seconds delay, iirc its longer. If you wait enough you would see the dialog.

**Comment by elad335** [comment]
#14038

**Comment by Hasster1** [comment]
> #14038
Can not see it when the tread is "sleepy".
![image](https://github.com/user-attachments/assets/06e9a424-45ba-4cf0-a9dc-eb2ea2ad80bf)

**Comment by Hasster1** [comment]
Here's a log if you need it - 
[RPCS3.log](https://github.com/user-attachments/files/17085534/RPCS3.log)

(I didn't respond immediately because i couldn't re-trigger the thread sleepiness, but now i did it.)
