### ISSUE TITLE
White Screen when i try to load up Sonic Unleashed

### ISSUE THREAD

**Issue by SonicUn** [RPCS3/rpcs3#16040]
### Quick summary

I need help. When i try to Boot up sonic unleashed it just gives me a white screen. The game and audio can be heard but the screen is just white. My specs and settings will be listed below.
Ram-4.00GB
GPU-Intel HD Graphics 4600
CPU-Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz, 3201 MHz, 4 Core(s), 4 Logical Processor(s)
Please Help it been doing this since yesterday!

### Attach a log file

JHHJLK

**Comment by MSuih** [comment]
Your GPU is below minimum requirements
