### ISSUE TITLE
[Bug] Closing patch manager or saving patch settings while it's checking for updates freezes rpcs3 until it'll finish checking for updates.

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#16052]
### Quick summary

Just open and close patch manager by either cancelling or saving while it's still checking for updates.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16912728/RPCS3.log)

**Comment by Megamouse** [comment]
The main issue here is your internet connection.
I can't even reproduce this because it is done checking before I can close the dialog.

**Comment by Megamouse** [comment]
Yeah closing this. The download is already aborted when you close the dialog.
This depends on how often curl sends updates, which is at least ~1/s.
