### ISSUE TITLE
MMJoystick: Mapping Guitar not working

### ISSUE THREAD

**Issue by Magnetuz** [RPCS3/rpcs3#16053]
### Quick summary

I am trying to map a guitar from Rock back, but the red fret press is not identified on the MMJoystick. On the game itself the button also does not work. The same guitar works fine on the Clone Hero and I can see all the buttons working fine on a Joystick calibration app.

### Details

OS:
`Linux pop-os 6.9.3-76060903-generic #202405300957~1721174657~22.04~abb7c06 SMP PREEMPT_DYNAMIC Wed J x86_64 x86_64 x86_64 GNU/Linux`

Guitar identification (dmesg):
```
[ 4053.550086] hub 1-1:1.0: USB hub found
[ 4053.550382] hub 1-1:1.0: 1 port detected
[ 4053.822257] usb 1-1.1: new full-speed USB device number 11 using xhci_hcd
[ 4053.902838] usb 1-1.1: New USB device found, idVendor=12ba, idProduct=0200, bcdDevice= 3.13
[ 4053.902854] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4053.902860] usb 1-1.1: Product: Harmonix Guitar for PlayStation®3
[ 4053.902864] usb 1-1.1: Manufacturer: Licensed by Sony Computer Entertainment America
[ 4053.907288] input: Licensed by Sony Computer Entertainment America Harmonix Guitar for PlayStation®3 as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.1/1-1.1:1.0/0003:12BA:0200.0006/input/input24
[ 4053.959766] hid-generic 0003:12BA:0200.0006: input,hidraw3: USB HID v1.01 Gamepad [Licensed by Sony Computer Entertainment America Harmonix Guitar for PlayStation®3] on usb-0000:00:14.0-1.1/input0
```

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16912789/RPCS3.log.gz)

**Comment by Megamouse** [comment]
We are not responsible for the buttons that work in mmjoy.
Try with SDL

**Comment by Magnetuz** [comment]
> We are not responsible for the buttons that work in mmjoy. Try with SDL

@Megamouse, thank you for your response.

I set up the SDL on the Pads configuration. It does not work just as described. 

Could you give me some suggestions how could I investigate/debug this? Is the SDL from some third party lib used in the RPCS3?

**Comment by Megamouse** [comment]
It's a third party lib. If it doesn't work there, you can still try evdev in Linux.
I doubt it's an issue on our end.

**Comment by ubuntu-pedido** [comment]
Have the same problem, can't map the red fret on SDL
