### ISSUE TITLE
Drakengard 3 [BLUS31197] has lighting issues

### ISSUE THREAD

**Issue by Qriist** [RPCS3/rpcs3#16059]
### Quick summary

This is a subtle bug that isn't obvious at first glance but gradually becomes apparent as you play.

Basically, everything that creates some kind of glow effect (fires, waypoints, transformations, skybox, etc) seems sorta "overexposed", to the point where detail in the object is lost to the glow itself. This gives the gameplay a very washed out feel without regard to the enviornment. I've tried fiddling with the ingame brightness/gamma settings without success. 

### Details

One of the cinematics in Chapter 2: Verse 1: Part 2 is a good example of how pervasive the effect is.

First, a control still from a random Youtube video:
![image](https://github.com/user-attachments/assets/769409df-a756-41fe-90d3-41df7e2dfedf)

Then this is what I see in RPCS3:
<img width="1164" alt="rpcs3_ihiWxVzUOG" src="https://github.com/user-attachments/assets/84cab87f-5b4a-436f-829a-2d34a300d235">

Compared to the first picture, my screenshot is very obviously displaying the "overexposed" effect. The skybox is hyperwhite, the dragon's fireball in the center is neon orange, the shields on the right cliff are more reflective, and the mist below the cliffside is virtually nonexistent. The gold box is a little different in my shot because I've already played through this level; you're looking at the lid of the box... still, it's too bright.

I've attached a log and RSX capture. If there's something in the settings that I should flip I'd be happy try that, too. Thanks in advance!

### Attach a log file

[Drakengard 3 [BLUS31197].log.gz](https://github.com/user-attachments/files/16921227/Drakengard.3.BLUS31197.log.gz)

### Attach capture files for visual issues

[BLUS31197_20240908031342_capture.7z.gz](https://github.com/user-attachments/files/16921234/BLUS31197_20240908031342_capture.7z.gz)

**Comment by Jonathan44062** [comment]
Bad settings, next time, use the wiki settings, reset them to default
https://wiki.rpcs3.net/index.php?title=Drakengard_3
![imagen](https://github.com/user-attachments/assets/a6dd5ede-ca39-4318-9699-f5f973d373cc)

**Comment by Qriist** [comment]
> Bad settings, next time, use the wiki settings, reset them to default https://wiki.rpcs3.net/index.php?title=Drakengard_3

That did the trick!
![image](https://github.com/user-attachments/assets/2615440d-0bc9-4ad4-97cc-e93147436557)

Thank you for letting me know about the wiki. I'll make sure to consult there before making any more bug reports. :)
