### ISSUE TITLE
Unhandled exception when trying to start a game (Vulkan)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1606]
```
·! LDR: Title: flOw
·! LDR: Serial: NPEA00021

vm::g_base_addr = 000000007FFF0000
vm::g_priv_addr = 000000017FFF0000
```

```
·! LDR: Title: PIYOTAMA™
·! LDR: Serial: NPEA00065

vm::g_base_addr = 000000007FFF0000
vm::g_priv_addr = 000000017FFF0000
```

Both these games' render windows open with OpenGL.
Trying to start them (and I believe it happens with a lot more games) with Vulkan crashes RPCS3 with an Unhandled exception.
I wasn't able to catch any stack trace.

**Comment by AniLeo** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/10283761/13917960/0990e9bc-ef5c-11e5-9212-7c4ddb0b5eaf.png)

This is what I got
Every game I tried to start with Vulkan gave me an unhandled exception

**Comment by tambry** [comment]
What card and what drivers version did you test with?

**Comment by AniLeo** [comment]
Radeon Crimson 16.3
MSI R9 280X

![screenshot_4](https://cloud.githubusercontent.com/assets/10283761/13921258/f13ad950-ef6e-11e5-9701-c8686851220b.png)

**Comment by vlj** [comment]
Do you enable debug output ? Try launching RPCS 3 without it.

**Comment by AniLeo** [comment]
It works without Debug Output enabled.

**Comment by tambry** [comment]
Then it's **very very** likely either due to missing, improper or old Vulkan (LunarG) SDK installation, since debug output enables validation layers, and if driver can't find them it crashes.

**Comment by vlj** [comment]
You need SDK 1.0.3.1 to enable debug layers. The 1.0.5.0 version doesn't work (the vulkan submodule needs to be updated)

**Comment by AniLeo** [comment]
I have 1.0.3.1 installed at C:\Program Files (x86)\VulkanRT\1.0.3.1 (however vulkinfo shows 1.0.3)
That's the version that comes along with the latest Radeon Crimson Beta drivers for Vulkan

**Comment by tambry** [comment]
That's not the SDK. That's the Runtime, as the RT indicates (Vulkan**RT**). Shipping code examples, validation layers and documentation with every driver isn't probably very smart, so developers need to download the SDK separately from the [LunarG's website](https://vulkan.lunarg.com).

**Comment by AniLeo** [comment]
My bad, I didn't realize the SDK wasn't there
I'm downloading 1.0.3.1 now
(Probably should be noted somewhere that the 1.0.3.1 of the SDK is needed to use Debug Output on Vulkan)

@vlj Could you update the submodule?

**Comment by tambry** [comment]
Can this be closed for now? Or can we change the title and original issue to reflect the need for the updated submodule?

**Comment by AniLeo** [comment]
I guess the latter should be more fit. I was gonna close it when the submodule got updated

**Comment by raven02** [comment]
@AniLeo , feel free to close it .

**Comment by AniLeo** [comment]
Is the submodule still on the 1.0.3.1? VK 1.0.11.0 is out already
