### ISSUE TITLE
GoldenEye 007: Reloaded - Can't aim or look at diagonal direction (up-left)

### ISSUE THREAD

**Issue by ElTioRata** [RPCS3/rpcs3#16064]
### Quick summary

This is likely a regression since I don't recall having this issue a few years ago.
Here's a [video](https://streamable.com/jhd15z) that describes the issue better than the title, watch how I'm trying to do a circle with the stick and it stops responding when I reach the "up-left zone" of the stick. This isn't an issue with my controller, it also happens with the keyboard (the player 2 in the video is the one using it).

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16922784/RPCS3.log)

**Comment by Megamouse** [comment]
Try the mentioned pull request and create a new pad configuration (change the keyboard to some other handler, save and then go back to keyboard and save again).

Alternatively you can set the Squircling values in the input config file to 8000 if you know where to look.

**Comment by ElTioRata** [comment]
The fix didn't solve it for me

**Comment by Megamouse** [comment]
Ah. I forgot to implement the feature for the keyboard.
Anyway, you can just set the stick multipliers to 0.99 to fix this issue.

**Comment by ElTioRata** [comment]
It didn't fix the issue for my controller or keyboard

**Comment by Megamouse** [comment]
Try again with #16067 and a keyboard

**Comment by ElTioRata** [comment]
[RPCS3.log](https://github.com/user-attachments/files/16948721/RPCS3.log)

**Comment by Megamouse** [comment]
I updated the squircle function to clamp the values that would previously exceed the expected squircle.
Please try again with keyboard and controller once the Pull Request build has built.

**Comment by ElTioRata** [comment]
Works for controller input now
