### ISSUE TITLE
constant crashing of Armored core for answer

### ISSUE THREAD

**Issue by Andyxxcd** [RPCS3/rpcs3#16063]
### Quick summary

After the latest update, my Acfa game keep crashing within a few minutes, almost all in the menus, which is a rare occurrence until I updated

### Attach a log file

After the latest update, my Acfa game kept crashing within a few minutes, almost all in the menus, which is a rare occurrence until I updated.

**Comment by Megamouse** [comment]
Closing as invalid bug report
