### ISSUE TITLE
Skate 3 Crashes On Load

### ISSUE THREAD

**Issue by exBuys** [RPCS3/rpcs3#16072]
### Quick summary

skate 3 crashes on load; error message: 
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/db/skaterschema.vlt” [1]

E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/db/skatercollections.vlt” [1]

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16971503/RPCS3.log.gz)

### System configuration

Processor	AMD Ryzen 5 4500 6-Core Processor                 3.60 GHz
Installed RAM	16.0 GB (15.9 GB usable)3
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Pro
Version	23H2
Installed on	‎1/‎29/‎2024
OS build	22631.4037
Experience	Windows Feature Experience Pack 1000.22700.1027.0

**Comment by FlexBy420** [comment]
Pirated game.

**Comment by exBuys** [comment]
> Pirated game.

Do you know of how I could get a legit copy?

**Comment by Hamof1** [comment]
Try Ebay, or your local equivalent.
