### ISSUE TITLE
My pc has detected a rpcs3 virus

### ISSUE THREAD

**Issue by Pop7362** [RPCS3/rpcs3#16089]
### Quick summary

My pc detected a virus from rpcs3 and a false positive I can trust
![Captura de tela 2024-09-17 132112](https://github.com/user-attachments/assets/68ba4a38-6bba-4963-878d-6d33d62570a4)

### Attach a log file

![Captura de tela 2024-09-17 132112](https://github.com/user-attachments/assets/419b0e6f-10c1-4fa8-ba4d-943974ccbf40)

**Comment by AniLeo** [comment]
Not our problem, we already reported rpcs3.exe as a false positive too. Add to exclusions and complain to Microsoft.
