### ISSUE TITLE
Crash every time I stop emulation with the PS3 controller connected

### ISSUE THREAD

**Issue by rebelcode-xr** [RPCS3/rpcs3#16085]
### Quick summary

After playing a game (even for hours), when I close the game, the emulator crashes **every single time**. 

### Details

Since I tested only SKATE3, I thought that the problem was caused by the game or some specific setting, but it happens also after closing "The PS3 Interface".  I just discovered that the problem doesn't show up if the PS3 controller is disconnected and I use the keyboard, so the problem has to do with the USB interface. I don't have any other compatible controller to test.

### Attach a log file

[RPCS3.log.zip](https://github.com/user-attachments/files/17045717/RPCS3.log.zip)

### Attach capture files for visual issues

<img width="800" alt="image" src="https://github.com/user-attachments/assets/d2d0e515-d788-43b5-ae13-e7ef0763a1b5">

### System configuration

- SYS: RPCS3 v0.0.33-16930-d1648dd7 Alpha | HEAD
- SYS: VirtualApple @ 2.50GHz | 10 Threads | 16.00 GiB RAM | TSC: 1.000GHz
- SYS: Operating system: macOS, Version: 14.6.1
- SYS: Current Time: 2024-09-16T20:50:24
- RSX: Found Vulkan-compatible GPU: 'Apple M1 Pro' running on driver 0.2.994
- SYS: Firmware version: 4.91

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed

**Comment by rebelcode-xr** [comment]
I was playing with Skate3 with the 60 fps patch, I didn't know it was a problem. anyway the patch cannot have nothing to do with the controller bug. **disabling the patch I get the same error**. also, @Megamouse, I specified that the bug happens also with "The PS3 Interface", it seems that you ignored that.

Important discovery: if I disconnect the controller before stopping emulation I get no error/crash.

Please **reopen the issue**, it was a bit rude to close it like that: your time is valuable but also mine.
Please tell me what you need me to test or provide you. Thank you for your patience 🙏

**Comment by rebelcode-xr** [comment]
The situation improved: now RPCS3 doesn't crash **when I stop the emulation**.
However, sadly it crashes when I **close the app** or if I **restart the game**.

After playing the game this is the situation:
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/ba1298bb-3eb0-4c78-a4f7-fe8a146a1fee">

When I close the emulator:
<img width="800" alt="image" src="https://github.com/user-attachments/assets/777e85f0-9755-4408-88c9-3d790da1c275">

Sometimes I get a second error:
<img width="697" alt="image" src="https://github.com/user-attachments/assets/ef2ce9da-8b54-49e7-8d0d-25799e066bd7">

If I press "Restart game", it crashes soon after the game starts:
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/9946d56a-5d74-4c7c-a597-5c1180062a9f">
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/9877ba99-28ee-4e1e-9cd7-241ae2a5877d">

Notes:
If I disconnect the controller before close the app, I still get the crash.
All tests were made without game patches.

**Comment by Megamouse** [comment]
I think this is just hidapi on macOs being buggy.
I doubt it's an issue with our code
