### ISSUE TITLE
[Feature request] Remapping of motion controls

### ISSUE THREAD

**Issue by sYnapZiX** [RPCS3/rpcs3#16096]
### Quick summary

Please allow the remapping of DS3's motion controls to any other device available. 

### Details

Games like Killzone 2 are not finishable (or even properly startable (if that even is a proper term)) because the requirement for either a Dualshock 3 or 4 controller, or the installation of third-party software which is questionable in nature, only works half of the time and interferes with other games that rely on a proper non third-party driver/applications.

If there is any way to do this without the requirement for additional software or special hardware please let me know and consider my issue as closed, but for me the "Motion Controls" tab in the Pad-Settings is greyed out and i can't remap them.

I have a latest gen Xbox Controller (Original) which obviously lacks motion controls and some of my games are not finishable or playable at all because i can't use motion controls at all.

Other emulators like Cemu, Yuzu (Suyu) or Ryujinx offer that option in the Emulator without the requirement of special hard- and/or software. Just let me remap the motion controls to my mouse or even my keyboard so that those games can at least be played properly.

In Killzone 2 for example, i can play the first 20 minutes of the game perfectly fine  at 4k/~60fps until the very first valve you reach in the game which you need to physically turn it with motion controls.

Sorry if this text is hard to read but i'm not a native english speaker.

Other than that, the emulator is (at least for me) almost perfect. Please keep up your amazing work!

**Comment by Valtekken** [comment]
I think there's already a similar issue on this repository. It was opened a while ago.

**Comment by Valtekken** [comment]
#13883

**Comment by sYnapZiX** [comment]
I'm very sorry for double posting then, i've just tried some of my games (after quite some time) today and i've noticed that all of them had a hard road-block because of motion controls even though those games work perfectly fine otherwise.
________________________________
Von: Valtekken ***@***.***>
Gesendet: Donnerstag, 19. September 2024 21:11
An: RPCS3/rpcs3 ***@***.***>
Cc: sYnapZiX ***@***.***>; Author ***@***.***>
Betreff: Re: [RPCS3/rpcs3] [Feature request] Remapping of motion controls (Issue #16096)


#13883<https://github.com/RPCS3/rpcs3/issues/13883>
