### ISSUE TITLE
Updater on Mac doesn't apply update

### ISSUE THREAD

**Issue by Swagdude7** [RPCS3/rpcs3#16095]
### Quick summary

Whenever I start up rpcs3 or manually check for an update it finds a new available build, as expected. If I hit yes to update, it loads for a few moments, before closing and re-opening itself. Despite this, the new build is not applied and It is still running the outdated build.

### Details

I am on a 2021 Macbook Pro with an M1 Max chip. Using the macOS build from the website, which is marked as experimental. I have added the following to the info.plist file to make the UI more readable:

	<key>NSRequiresAquaSystemAppearance</key>
	<true/>

Since the updater hasn't been working, I have been manually downloading new builds and overwriting my application, but I feel that is more of a band-aid solution.

Currently running build 0.0.33-16931

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17064141/RPCS3.log.gz)

### System configuration

OS: MacOS  Sonoma 14.6.1
CPU/GPU: M1 Max
Build: RPCS3 v0.0.33-16931

**Comment by Megamouse** [comment]
Please upload a logfile trying to update from the second latest to the latest build.

**Comment by Swagdude7** [comment]
> Please upload a logfile trying to update from the second latest to the latest build.

[RPCS3.log.gz](https://github.com/user-attachments/files/17138506/RPCS3.log.gz)

Whatever was changed appeared to have worked. When I clicked yes to the update it took much longer to load before rpcs3 closed itself. The new build appears to have been applied, and I am no longer prompted to update.

I tested build 0.33.16954 -> 0.33.16956
