### ISSUE TITLE
[Feature request] Time interval option when checking for updates

### ISSUE THREAD

**Issue by auwsmit** [RPCS3/rpcs3#16105]
### Quick summary

Add an option to only check for updates (at startup) at timed intervals

### Details

This is mostly a minor quality-of-life/convenience suggestion for the User Interface. With this option, the emulator could only check for updates *(at startup)* every week, rather than every single time it's opened, which I personally find can be annoying given the frequency of updates for this project.

I imagine it would be an addition to the current dropdown menu, which then enables a selection for the time interval in **X** days (as depicted below):

![image](https://github.com/user-attachments/assets/0414d893-1ecb-4d98-8ab2-ff921c540c20)

**Comment by Megamouse** [comment]
You can just check it manually once a week then...
I don't see why we should add this.

**Comment by AniLeo** [comment]
This is potentially problematic if we rollback a broken build, as it wouldn't ping to check for it. Unless it kept checking in the background but not prompting on the UI side, but in that case, there's already the "background" check for update settings.

**Comment by Megamouse** [comment]
Also, you can use the background checks to have it tell you there's an update in the corner.
What hinders you from doing that and updating when you feel like ?
