### ISSUE TITLE
Error building on Debian 8 with clang - "cotire: error 1 precompiling"

### ISSUE THREAD

**Issue by mdeguzis** [RPCS3/rpcs3#1610]
Getting this when compiling:

```
build/rpcs3-0.0.0.6+20160322git+bsos/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: does not match expected signature 'gsl::span<const wchar_t, -1l>& gsl::span<const wchar_t, -1l>::operator=(const gsl::span<const wchar_t, -1l>&)'
CMake Error at cmake_modules/cotire.cmake:1703 (message):
  cotire: error 1 precompiling
  /build/rpcs3-0.0.0.6+20160322git+bsos/obj-x86_64-linux-gnu/rpcs3/cotire/rpcs3_CXX_prefix.hxx.
Call Stack (most recent call first):
  cmake_modules/cotire.cmake:3233 (cotire_precompile_prefix_header)


rpcs3/CMakeFiles/rpcs3.dir/build.make:57: recipe for target 'rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch' failed
make[3]: *** [rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch] Error 1
```

**Links:**
- [debian files](https://github.com/ProfessorKaos64/LibreGeek-Packaging/tree/brewmaster/rpcs3/debian)
- [build log (full)](https://gist.github.com/ProfessorKaos64/4388f3d844d4cecacf70)

**Comment by ProfessorKaos64** [comment]
I guess this is due to my LLVM version? Clang uses LLVM as a backend, and Debian Jessie has llvm-runtime 3.5.x. Does this mean (since gcc is also too old on Jessie) this can't be compiled on Debian Jessie 8.x?

**Comment by tambry** [comment]
We use GSL, which seems to require Clang/LLVM3.6. I'm not sure what version that equates to, but README probably should be updated accordingly.

**Comment by ProfessorKaos64** [comment]
Clang/LLVM versions are "tied," so clang 3.5, uses LLVM 3.5.x. I'd probably update the readme, yes. I am guess that the submodule llvm directory can't be utilized for some sort of "in-pace" build of llvm for compile-time only?

**Comment by tambry** [comment]
Maybe. I have very limited knowledge of CMake and Unix systems, so this will be up to someone else.

**Comment by ProfessorKaos64** [comment]
I'll try the route of backporting clang from Stretch (which is 3.6) and keep in in my testing distribution pool. If there is other word of this being possible on Debian Jessie, I hope another can comment, if other project members deem this not possible, please confirm and close.

**Comment by danilaml** [comment]
@ProfessorKaos64 can't you install packages from here https://packages.debian.org/source/sid/llvm-toolchain-3.6 ?

**Comment by ProfessorKaos64** [comment]
@danilaml , maybe, have to check the dependencies. What I may do is keep a few of those packages in my testing repo only, for builds (I use a pbuilder hook to enable my test repo at build time). However, I also tried building this with a Debian Stretch pbuilder chroot, which also had Clang 3.6/LLVM 3.6 and GCC 5.3. Perhaps my rules were wrong, but pretty basic stuff. I did [declare](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/rpcs3/debian/rules) the compilers when I tried gcc/g++ or clang/clang++.

**Comment by ProfessorKaos64** [comment]
I backported llvm-toolkit / clang etc. from Debian Stretch, which is clang 3.6.x

Still get the error: http://slexy.org/view/s2KG7yxsZG

hmmm.

**Comment by ProfessorKaos64** [comment]
My bad, I did not have clang/clang++ defined in debian/rules. Trying now.

**Comment by ProfessorKaos64** [comment]
LLVM 3.8 fixes this, but only the latest revision (3) from Debian Sid. If I fixes things, I'll note in the closed similar threads in case folks Google search it.

See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819072

>Basically upstream LLVM made changes during 3.8 development to make their
CMake packaging files relocatable by computing locations relative to one
another.  However, Debian's packaging changes these relative locations by
moving things around after installation.  Therefore the wrong locations
are computed.

>Debian packaging must be taught to patch LLVMConfig.cmake to specify
absolute locations of LLVM_INSTALL_PREFIX, LLVM_CMAKE_DIR, etc. based
on where Debian puts them.

>Note that the 'castxml' package requires LLVM/Clang CMake packaging files
to build.  Therefore building that package against a llvm-*-dev package
(and libclang-*-dev) will reveal such problems.


Rebuilding the 3rd revision now to confirm...

**Comment by AniLeo** [comment]
Linux instructions have been updated, also, RPCS3 requires LLVM 3.8 specifically. 
Please reopen if still an issue.
