### ISSUE TITLE
[Bug] [macOS] RPCS3 uses non-native stylesheets on macOS by default

### ISSUE THREAD

**Issue by schm1dtxbox** [RPCS3/rpcs3#16107]
### Quick summary

The default stylesheets that are presumably intended for Windows use are being used wrongly on macOS, making the entire UI look non-native by default and even unreadable in some cases.

### Details

macOS Qt in RPCS3 shouldn't even need stylesheets at all, since when using the "None" or "Native (macOS" options in Settings you get perfect native UI controls and styling that automatically syncs with the system-wide Light/Dark Aqua appearance setting. 

By default however RPCS3 carries over the Windows-optimised defaults for styling and offers a non-functional 'option' to use Dark Mode (aka change stylesheets, something Windows may need due to the awful state of system-wide dark mode there, or lack thereof). Both result in broken UI, especially if you have macOS set to be Dark, which results in completely unreadable light+dark UI that can only be fixed by switching to native styling.

The solution here is simple: RPCS3 should default to no stylesheet at all or to "Native (macOS)" as they're the same thing, and should hide the broken non-functional "Enable Dark Mode" option in the initial setup to avoid user confusion when macOS/Qt will handle dark mode automatically when using native controls. (Controversially, stylesheets should be hidden completely on macOS as none of them look good on this OS, most are clearly designed for Windows and I imagine most macOS users generally prefer native-only as a whole. However I acknowledge that may be a bit extreme so just fixing the defaults should be enough).

### Attach a log file
[RPCS3.log](https://github.com/user-attachments/files/17085649/RPCS3.log)
Doesn't seem to be much in this of relevance except the final 3 lines.

### System configuration

System: 2022 MacBook Air
SOC: Apple M2
OS: macOS 15 Sequoia
RPCS3 version: Latest arm64 artifact from the CI PR, affects any compile of RPCS3 for macOS currently though (arm64 or x86)

### Other details

Image of RPCS3 using default styling on first boot irrespective of whether the Dark toggle is enabled or not, with macOS set to Dark Mode system-wide:
<img width="898" alt="image" src="https://github.com/user-attachments/assets/116692d6-19c6-4a34-ab9f-d481938d77c6">

How RPCS3 should look, when set to use None/Native(macOS) stylesheets:
<img width="899" alt="image" src="https://github.com/user-attachments/assets/8971323a-4f1f-49f1-bc42-c8920d3eb325">

**Comment by Megamouse** [comment]
Missing logfile
