### ISSUE TITLE
aarch64/gl: Texture cache crash while trying to go in-game with Sonic Unleashed (OOM)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#16111]
The game will crash on the intros while trying to go in-game with the following stack trace

![image](https://github.com/user-attachments/assets/3d732a44-0bfa-4887-82b9-f43ba340783f)

### Settings 
Render: OpenGL
Resolution Scale: 38%
Shader Quality: Low
Upscaling: Nearest
Everything else is as per the game's wiki page.
Tested without and with existing patches.

Tested with both the Sonic Unleashed Demo and Full Game
The same test on x64 with OpenGL (radeonsi) does not trigger this crash

### System information
Compiled with gcc 14.1.1 on Arch Linux ARM
Tested with both mesa 24.1.6 and with mesa-git, using driver V3D 7.1.7

**Comment by kd-11** [comment]
This looks like OOM to me. For whatever reason all available memory got used up. It could be a driver memory leak, but double-check memory usage using "free -h" during execution to figure out what's going on.
Or maybe GL is keeping too many textures around? Check texture stats using the debug overlay and we may be able to fine-tune the cache limits to evict some items when under pressure.

**Comment by AniLeo** [comment]
Caused by the workaround for #15986
