### ISSUE TITLE
[macOS] Updater: Updating the Arm app will replace it with the x64 build

### ISSUE THREAD

**Issue by shinra-electric** [RPCS3/rpcs3#16118]
### Quick summary

When using the auto-updater, the x64 build is downloaded even if the original app bundle is Arm. 

### Attach a log file

N/A

**Comment by AniLeo** [comment]
This is expected, since the website backend and frontend is still being updated for this. When we officially announce it, everything will be working as expected.

**Comment by shinra-electric** [comment]
Fair enough

**Comment by AniLeo** [comment]
This is not a clientside issue, so I'll close the ticket. The remaining stuff is purely on web side.

**Comment by AniLeo** [comment]
As a temporary measure, I've disabled the updater for the arm64 build. It will be better than updating you to the wrong version until this is implemented.
