### ISSUE TITLE
How to Compile RPCS3 to aarch64

### ISSUE THREAD

**Issue by ahmedbarakat2007** [RPCS3/rpcs3#16110]
So i want to compile rpcs3 to aarch64 linux but the issue is that even though i made a toolchain to specify all aarch64 compilers and even i did it manually with export it still compiles to x86_64 

The command i used
cmake -DCMAKE_TOOLCHAIN_FILE=../rpcs3/ && make

Btw also tried to make "make" direct to use aarch64-gnu-linux compilers but it still compiles to x86

What compiler should i use?

**Comment by AniLeo** [comment]
GitHub is not for support.
