### ISSUE TITLE
[Feature request] [macOS] Elastic touchpad scrolling across the RPCS3 GUI

### ISSUE THREAD

**Issue by schm1dtmac** [RPCS3/rpcs3#16114]
### Quick summary

Might be the least important thing imaginable but I guess it's worth a shot at requesting: Elastic scrolling for touchpads would be nice to have across the RPCS3 GUI on platforms that would be suitable for it, so mainly macOS (maybe also for Precision Touchpads on Windows?). 

### Details

RPCS3 on Mac currently just has generic handling of scrolling that Qt provides, so touchpad inputs get translated to high precision mouse wheel deltas and whatnot, which provides some degree of kinetic scrolling that  lacks elasticity. Hence when you reach the end of a scroll view, it abruptly stops in RPCS3 unlike most other scrollable views in macOS, which instead let you scroll a bit further until they snap back when you let go of the scroll. 

Adding elastic scrolling would just help make RPCS3 look more consistent with other native macOS apps, although as noted in the summary it's not exactly essential either. Qt kinda supports this via the QScroller class but that's meant more for touchscreens, and with touchpads it produced flaky results when I had a play with it. Other Qt apps that have functional elastic scrolling on Mac using touchpads seem to be entirely QML based instead.

**Comment by Megamouse** [comment]
If this isn't part of Qt, then there is no point implementing it, since it would just add a ton of custom bloat to the software, which is hardly maintainable or smart to do.

**Comment by Megamouse** [comment]
What I'm trying to say is:
This nonsense should be built-in with Qt and not something we have to implement for every widget we use.
