### ISSUE TITLE
[Regression] SPURS thread limiting less effective for Sly Cooper: Thieves in Time after #16124

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#16128]
### Quick summary

After #16124 SPURS thread limiting isn't as effective at lower CPU usage for Sly Cooper: Thieves in Time.

### Details

I set the SPURS threads to 3 and the FPS to 30 to be able to run the game on Steam Deck, and it worked pretty good until the update. Here's a comparison:
Before:
![20240926090649_1](https://github.com/user-attachments/assets/f295308d-8673-461b-8ba9-0cafbd421940)
After:
![20240926090040_1](https://github.com/user-attachments/assets/8c9c72a1-3168-4c05-8a98-2f9481c19a35)

### Build with regression

v0.0.33-16959-60b5adab

### Attach two log files

[RPCS3 Sly stutter.log](https://github.com/user-attachments/files/17152394/RPCS3.Sly.stutter.log)
[RPCS3 Sly smooth.log](https://github.com/user-attachments/files/17152398/RPCS3.Sly.smooth.log)

### System configuration

- SYS: RPCS3 v0.0.33-16959-60b5adab Alpha | HEAD
- SYS: AMD Custom APU 0405 AmdCcxVhFf3PeiInit Entry
| 8 Threads | 14.47 GiB RAM | TSC: 2.800GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 6.1.52-valve16-1-neptune-61, Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
- SYS: Current Time: 2024-09-26T09:22:15
- RSX: Found Vulkan-compatible GPU: 'AMD Custom GPU 0405 (RADV VANGOGH)' running on driver 23.2.99
- SYS: Firmware version: 4.85

**Comment by elad335** [comment]
test #16129

**Comment by Anuskuss** [comment]
This setting is useless now for *Call of Duty: Modern Warfare 3*. I can get it from 40 FPS at 90% CPU to 50 FPS at 50% CPU with `Max SPURS Threads: 3` while with the new version it's stuck at 40 FPS at 90% CPU.

**Comment by elad335** [comment]
Update at #16155

**Comment by JimScript** [comment]
I think #16182 resolved this issue as well, as the game is back to having silky smooth 30fps at a low wattage again, so I think this issue can be closed. I'll just close it for now, but I'll reopen it if I need to do anything else.
