### ISSUE TITLE
[Regression] Some Insomniac games crash to desktop after #16124

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#16127]
### Quick summary

After #16124 some Insomniac games crash to desktop every time it tries to display 3D, even when the SPURS thread is set to "Unlimited"

### Details

The broken games being:

- Resistance: Fall of Man
- Resistance 2
- Ratchet & Clank Future: Tools of Destruction
- Ratchet & Clank Future: Quest for Booty

### Build with regression

v0.0.33-16959-60b5adab

### Attach two log files

[RPCS3_RFOM_working.log](https://github.com/user-attachments/files/17151002/RPCS3_RFOM_working.log)
[RPCS3_RFOM_crash.log](https://github.com/user-attachments/files/17151004/RPCS3_RFOM_crash.log)

### System configuration

- SYS: RPCS3 v0.0.33-16959-60b5adab Alpha | master
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2024-09-26T08:13:10
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 551.86.0.0
- SYS: Firmware version: 4.88

**Comment by elad335** [comment]
Test #16129

**Comment by Darkhost1999** [comment]
> Test #16129
[RPCS3.log](https://github.com/user-attachments/files/17165231/RPCS3.log)
Can be reopened

**Comment by elad335** [comment]
This is actually fixed by #16140 (99% sure)
