### ISSUE TITLE
[Regression] Uncharted: Drake's fortune - Broken water effect after #13901 with Vulkan renderer

### ISSUE THREAD

**Issue by digant73** [RPCS3/rpcs3#16126]
### Quick summary

It seems that PR #13901 (build 0.0.27-15047) is responsible for broken water effect in `Uncharted Drake's Fortune` with Vulkan renderer.
It is properly working in OpenGL.

If I disable the custom border color commenting out the line 35 in `vkutils/sampler.cpp`:

```
//if (!g_render_device->get_custom_border_color_support())                    // <-- line 35
{
	value = get_closest_border_color_enum(color_value);
	return;
}

```
the issue is no more present.

I also verified that the broken water effect in Killzone 3 reported in ##15949 is also fixed by the above change in the code.
Below some screenshots of the issue and the temporary fix.

### `OpenGL - working:`

![BCES00065_screenshot_2024_09_25_22_37_45](https://github.com/user-attachments/assets/8c886c53-9887-4f6e-bc2f-d44ea3ecb525)

### `Vulkan - broken - custom border color enabled since #13901:`

![BCES00065_screenshot_2024_09_25_22_29_52](https://github.com/user-attachments/assets/cd68b894-86ba-4f38-8ef2-7ef92732e955)

### `Vulkan - working - custom border color disabled by temporary fix:`

![BCES00065_screenshot_2024_09_25_22_50_27](https://github.com/user-attachments/assets/5256ff53-77f2-4aff-8e89-1950343750c3)

### Build with regression

0.0.27-15047

### Attach two log files

[RPCS3.log.gz](https://github.com/user-attachments/files/17139206/RPCS3.log.gz)

**Comment by FlexBy420** [comment]
The log is for Killzone 3, not UC1

**Comment by Jonathan44062** [comment]
Duplicated by https://github.com/RPCS3/rpcs3/issues/15422

**Comment by digant73** [comment]
> The log is for Killzone 3, not UC1

there were both but the log is useless in that case
