### ISSUE TITLE
Resistance 2™ [BCES00226]: RPCS3 is crashed when running this game

### ISSUE THREAD

**Issue by trantien1997** [RPCS3/rpcs3#16135]
### Quick summary

RPCS3 is crashed when running this game

### Details

RPCS3 is crashed when running this game

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17157725/RPCS3.log)

**Comment by Darkhost1999** [comment]
There's already an open regression report for this https://github.com/RPCS3/rpcs3/issues/16127
