### ISSUE TITLE
aarch64-libs

### ISSUE THREAD

**Issue by xoureldeen** [RPCS3/rpcs3#16132]
i have built rpcs3on aarch64 archlinux using:
cmake .. -DCMAKE_CXX_FLAGS="-march=armv8-a+simd -mfpu=neon"

i can't find libs dir only bin and make build files, i need lib dir to share this build and use it on other distro.

~/rpcs3 $ ldd rpcs3
        linux-vdso.so.1 (0x00000075838bb000)
        libX11.so.6 => not found
        libevdev.so.2 => not found
        libudev.so.1 => not found
        libSDL2-2.0.so.0 => not found
        libopenal.so.1 => not found
        libLLVM.so.18.1 => not found
        libGLU.so.1 => not found
        libGLX.so.0 => not found
        libOpenGL.so.0 => not found
        libvulkan.so.1 => not found
        libGLEW.so.2.2 => not found
        libEGL.so.1 => not found
        libQt6DBus.so.6 => not found
        libQt6Concurrent.so.6 => not found
        libQt6MultimediaWidgets.so.6 => not found
        libQt6Multimedia.so.6 => not found
        libQt6Network.so.6 => not found
        libQt6SvgWidgets.so.6 => not found
        libQt6Svg.so.6 => not found
        libQt6Widgets.so.6 => not found
        libQt6Gui.so.6 => not found
        libQt6Core.so.6 => not found

**Comment by AniLeo** [comment]
GitHub issue tracker is not for support
