### ISSUE TITLE
[BCUS98174] Ghosting/Double screen with "Disable in-game MLAA" enabled

### ISSUE THREAD

**Issue by CinosMatoi** [RPCS3/rpcs3#16149]
### Quick summary

When i run the game with the "Disable in-game MLAA" patch enabled, for some reason there's like a double screen across half the screen 

### Details

This problem only occurs when the "Disable in-game MLAA" patch is enabled. When it's not, the secrond screen or transparent screen won't appear, but the frames will drop significantly (From 25-35 to 15-20). I would like to know if this issue has been reported yet or if there's any solution, since it's happening in the latest version i have (16977)

Here's a comparisson between the patch on and off:

"Disable in-game MLAA" on:
![BCUS98174_screenshot_2024_09_28_21_04_33](https://github.com/user-attachments/assets/4a73aaf4-ead6-42b2-a165-62de24c7ce65)
![BCUS98174_screenshot_2024_09_28_21_45_41](https://github.com/user-attachments/assets/58308e31-9e63-4d70-9437-ccb46e0905d2)

"Disable in-game MLAA" off:
![BCUS98174_screenshot_2024_09_28_21_36_39](https://github.com/user-attachments/assets/4b1c6dcc-e45c-42e4-a7fb-bb50a31aca82)
![BCUS98174_screenshot_2024_09_28_21_39_39](https://github.com/user-attachments/assets/48afa8c6-26f1-4320-b65c-6419d646ede3)

Also might be good to mention that the higher the resolution, the "sharper" it gets.

Resolution scale at 200%
![BCUS98174_screenshot_2024_09_28_20_53_58](https://github.com/user-attachments/assets/e42dfc52-b1c0-4cd4-840d-f72766ef2f22)

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17177326/RPCS3.log.gz)

### System configuration

OS: Windows 10 Pro 22h2
CPU: AMD Ryzen 5 4500 6-Core Processor 3.60 GHz
GPU: ASUS Radeon RX 570 Series 4GB Vram
GPU Driver: 24.3.1
RAM: 16 Gb
Game located in: SSD KINGSTON SA400S377240G

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ReLyf47** [comment]
PSA: the link above is a virus (obviously)

**Comment by RipleyTom** [comment]
Invalid settings used. Please refer to the wiki for the proper settings for the game.
