### ISSUE TITLE
Rpcs3 v0.0.33 crash on archlinux 

### ISSUE THREAD

**Issue by xoureldeen** [RPCS3/rpcs3#16143]
[root@localhost ~]# gdb rpcs3
GC Warning: Could not open /proc/stat
GNU gdb (GDB) 15.1
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rpcs3...
(gdb) r
Starting program: /usr/local/bin/rpcs3
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
No AppImage path found, checking for executable
Found exec path: /usr/local/bin/rpcs3
Debugger: 1

Program received signal SIGTRAP, Trace/breakpoint trap.
0x0000000000774ab0 in thread_ctrl::emergency_exit(std::basic_string_view<char, std::char_traits<char> >) ()
(gdb) backtrace
#0  0x0000000000774ab0 in thread_ctrl::emergency_exit(std::basic_string_view<char, std::char_traits<char> >) ()
#1  0x00000000007713b0 in fmt::raw_throw_exception(std::source_location, char const*, fmt_type_info const*, unsigned long const*) ()
#2  0x000000000075d6ec in fs::xnull(std::source_location) ()
#3  0x000000000072e0e8 in utils::shm::shm(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#4  0x0000000000503490 in __static_initialization_and_destruction_0() ()
#5  0x0000007fed1783f4 in __libc_start_main ()
   from /usr/lib/libc.so.6
#6  0x00000000005fdaf0 in _start ()
(gdb) r

**Comment by AniLeo** [comment]
Not our bug or invalid. I've been running rpcs3 on aarch64 in ALARM for over a month.
