### ISSUE TITLE
[Regression] [Guitar hero live] Fps is no longer stable

### ISSUE THREAD

**Issue by JR2703** [RPCS3/rpcs3#16145]
### Quick summary

After version 0.0.33-16975 the game seems to run worse. The Fps is stable until you start hitting the in game notes on the guitar controller thats when the fps jumps around

### Details

Here's screenshots between the last version with no issues 0.0.33-16933 This version is very stable at 160 fps
![0 0 33-16933](https://github.com/user-attachments/assets/bf22fde6-4a0a-42ac-bd44-31b011e053b0)

Here's the exact same section of the game but on version 0.0.33-16975 The fps is unstable between 60-80 during gameplay.
![0 0 33-16975](https://github.com/user-attachments/assets/00359a60-510f-4f14-b76b-c96a8b61537a)

### Build with regression

0.0.33-16975

### Attach two log files

[0.0.33-16975 RPCS3.log.gz](https://github.com/user-attachments/files/17173581/0.0.33-16975.RPCS3.log.gz)
[0.0.33-16933 RPCS3.log.gz](https://github.com/user-attachments/files/17173583/0.0.33-16933.RPCS3.log.gz)

### System configuration

- SYS: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz | 4 Threads | 7.90 GiB RAM | TSC: 3.000GHz | AVX+ | FMA3
- Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- Vulkan-compatible GPU: 'NVIDIA GeForce GTX 1060 3GB' running on driver 556.12.0.0

**Comment by AniLeo** [comment]
Invalid regression report. 16975 only changes .qss code so it is literally impossible that it introduced such regression.
