### ISSUE TITLE
rXML: replacement for wxWidgets

### ISSUE THREAD

**Issue by mpm11011** [RPCS3/rpcs3#1614]
Right now, rXML acts as a wrapper for the wxWidgets XML library for use in the trophy system. It would not be too difficult to remove the wx dependency here, but we would probably need a replacement library for handling and parsing XML files. Should we use something like RapidXML or pugixml, or continue using wx/xml?

**Comment by danilaml** [comment]
Other possibility could be TinyXML-2.
And there is no question whether we should continue using wx/xml or not. Wx dependencies should be eliminated in the future..

**Comment by mpm11011** [comment]
I ended up using pugixml, but I'm running into a problem building the project. I'm getting LNK2001 errors in VS2015, and they all have to do with pugi functions.

Here's an example:

`5>emucore.lib(rXml.obj) : error LNK2001: unresolved external symbol "public: __cdecl pugi::xml_document::xml_document(void)" (??0xml_document@pugi@@QEAA@XZ)`

- I added `"${RPCS3_SRC_DIR}/../3rdparty/pugixml/src"` to rpcs3/CMakeLists.txt.
- I added `..\3rdparty\pugixml\src` to the IncludePath in emucore.vcxproj.

These did not resolve the errors. There must be something I'm missing, some way to get the VS project to include pugixml as a library or dependency.

**Comment by danilaml** [comment]
@mpm11011 you added include paths but you didn't add it to dependencies (you didn't tell it to link it).

**Comment by mpm11011** [comment]
@danilaml You mean by going to Project > Project Dependencies? Pugixml is not listed there.

**Comment by danilaml** [comment]
@mpm11011 I'm not sure if pugi is supposed to be compiled as a lib. You probably should know better.
Have you added it in "Configuration Properties" --> "C/C++“ --> "General" --> "Additional Include Directories" ?

**Comment by mpm11011** [comment]
I did do that. But I'm not sure if it's supposed to be compiled as a library.

**Comment by tambry** [comment]
Can this be closed, as it's been merged?

**Comment by tambry** [comment]
Closing, as it's merged.
