### ISSUE TITLE
[BLUS30034] Tom Clancy's Ghost Recon Advanced Warfighter 2 - Graphical Issues

### ISSUE THREAD

**Issue by kholgate** [RPCS3/rpcs3#16153]
### Quick summary

Squadmate camera in top left corner of the HUD will not display correctly without **Wrute Color Buffers** enabled. 

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17179299/RPCS3.log.gz)

### System configuration

Intel 12700k
RTX 3080

**Comment by FlexBy420** [comment]
So it's fixed by enabling WCB? If so then theres no need for github issue
