### ISSUE TITLE
[Mega Issue] Tracker of "Max SPURS Threads" regressions

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#16155]
Here you should comment all the recent regressions you can find with "Max SPURs Threads" setting until I'll be able to solve them.

**Comment by Anuskuss** [comment]
This setting is useless now for *Call of Duty: Modern Warfare 3*. I can get it from 40 FPS at 90% CPU to 50 FPS at 50% CPU with `Max SPURS Threads: 3` while with the new version it's stuck at 40 FPS at 90% CPU.

**Comment by smbhax** [comment]
Demon's Souls [BLUS30443]

In issue 16157, I describe the related problem in Demon's Souls starting in build 16964 when using the SPURS Threads setting of "3" that is still recommended on the Wiki ( https://wiki.rpcs3.net/index.php?title=Demon%27s_Souls ): with SPURS Threads set to "3" now, the game fails to advance past the initial loading screens.

With SPURS Threads set to "Default (Unlimited)," the game is able to load normally.

**Comment by elad335** [comment]
#16182 targets to solve this

**Comment by smbhax** [comment]
As of build 17020, which incorporates https://github.com/RPCS3/rpcs3/pull/16182 , the performance problem described in issue #16157 no longer occurs. : )

**Comment by Anuskuss** [comment]
I tested #16182 just in case but no difference.

**Comment by elad335** [comment]
@Anuskuss any update with #16185 ?

**Comment by Anuskuss** [comment]
@elad335 Nothing changed.

**Comment by Anuskuss** [comment]
Can you reopen this or should I create a new issue? My https://github.com/RPCS3/rpcs3/issues/16155#issuecomment-2381587212 has not been fixed.
