### ISSUE TITLE
[Documentation] Demon's Souls [BLUS30443] - Wiki recommends SPURS Threads = 3, this is incompatible since build 16964

### ISSUE THREAD

**Issue by smbhax** [RPCS3/rpcs3#16157]
### Quick summary

In recent builds of RPCS3, if SPURS Threads is set to "3" as recommended on the RPCS3 Wiki, Demon's Souls is very slow to start up, and eventually hangs on a load screen.

If SPURS Threads is set to "Unlimited (Default)," the game runs correctly. Possibly the Wiki's documentation on that setting for Demon's Souls is out of date.

### Details

If RPCS3's "Configuration - Advanced - Maximum Number of SPURS Threads" setting is set to "3", as recommended on https://wiki.rpcs3.net/index.php?title=Demon%27s_Souls , the following problem occurs:

~ ~ ~

Starting with build 16964 and continuing through the latest available build, 16982, Demon's Souls [BLUS30443] fails to start correctly: it is very slow going through the start-up screens, with a long pause on a black screen, and jerky loading icon animation. Sometimes, including with the attached log, that initial black screen is as far as it gets. On the times it's got past that, it is even slow on the title screen--the animation in which "Demon's Souls" materializes is noticeably slow--and on the load game menu after selecting LOAD GAME from the title screen. After selecting a saved game, I could not get it to advance past the next loading screen and into the world; it stayed on the loading screen indefinitely.

Works fine if I go back to build 16963.

I am playing on the Archstones server, with RPCS3 network settings configured per https://thearchstones.com/serverinfo.html

Tested with patches disabled and Write Color Buffers enabled.

~ ~ ~

If "Configuration - Advanced - Maximum Number of SPURS Threads" is instead set to "Unlimited (Default)," no problem is encountered and the game runs correctly.

The Wiki's recommendation for the SPURS Threads settings may be out of date.

### Build with regression

v0.0.33-16964-10dece1c_win64

### Attach two log files

[RPCS3_16963.log.gz](https://github.com/user-attachments/files/17184196/RPCS3_16963.log.gz)

[RPCS3_16964.log.gz](https://github.com/user-attachments/files/17184199/RPCS3_16964.log.gz)

### System configuration

Operating System:
Windows 11

CPU:
i7-10750H

GPU:
GTX 1660 Ti
Driver version 560.94

Other:
16 GB RAM
S271HL NVIDIA High Definition Audio

**Comment by smbhax** [comment]
The slow performance no longer occurs in 0.0.33-17020-d51d5ce8 , possibly due to its incorporation of https://github.com/RPCS3/rpcs3/pull/16182

**Comment by elad335** [comment]
Fixed by #16182

**Comment by jojoharry16** [comment]
In build 0.0.34-17288-0bb2f72e Alpha setting SPURS to 3 still causes the infinite loading screen. I'm... not sure how to check if [#16182](https://github.com/RPCS3/rpcs3/pull/16182) been merged into the master branch yet

**Comment by smbhax** [comment]
#16182 was merged by build 17020, months ago, and the SPURS problem was definitely fixed at that point for Demon's Souls. If SPURS=3 is causing problems for Demon's Souls in the current build, I'd suggest opening a new bug for it; you could refer to this one in the description if you want.
