### ISSUE TITLE
[Regression] AppImage does not boot on latest stable Steam OS 3.5.19 (#16148)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#16158]
Since #16148, the AppImage no longer boots on latest stable Steam OS 3.5.19

`/usr/lib/libstdc++.so.6: version 'GLIBCXX_3.4.32' not found`

The same version works fine on up-to-date archlinux on both x64 and arm64

**Comment by kd-11** [comment]
This is now fixed.

**Comment by AniLeo** [comment]
Still broken, reopening

**Comment by kd-11** [comment]
I restored the old appimage builder in a legacy script that we can use for now. Glibc issues are going to continuously hurt so we need a proper linux support window for OSes (e.g OS must be released within last 2 years) otherwise compatibility becomes dodgy.
