### ISSUE TITLE
DX12/Vulkan  : vertex program missing feature and syntax error

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1615]
[a0444bf1]

{rsx::thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 0)
{rsx::thread} RSX: Unknown/illegal instruction: 0x30 (forced unit 0)
{rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:77: '' :  syntax error
ERROR: 1 compilation errors.  No code generated.

{rsx::thread} RSX: 

---

{rsx::thread} Exception: Failed to compile fragment shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:280, in function VKFragmentProgram::Compile)

---

This error appears in few games  ^_^ e.g 
-Castle Crashers
-Swords & Soldiers 
-Dragon Ball: Xenoverse

Castle Crashers Log :  https://gist.github.com/SakataGintokiYT/7a38dde56e52919a99d1

[a0444bf1]
1. Video : https://www.youtube.com/watch?v=pn0dlskVaV4

[cf28c7e9]
2. Video : https://www.youtube.com/watch?v=yxlRp_ZIqUE

**Comment by kd-11** [comment]
You should attach the vertexprogram.txt and fragmentprogram.txt when the shader compilation fails on openGL. I have a few shader fixes for glsl and i plan to submit them when i find some time. Hopefully soon.

**Comment by SakataGintokiYT** [comment]
@kd-11 
[a0444bf]
http://www33.zippyshare.com/v/11MHkQNA/file.html

**Comment by raven02** [comment]
@SakataGintokiYT , does it look okay now in latest build?

**Comment by raven02** [comment]
btw did same stop happen in OGL and DX12?

**Comment by SakataGintokiYT** [comment]
@raven02 

Build {8c327d4c}

{rsx::thread} class fmt::exception thrown: VKVertexProgram::Compile(): Failed to compile vertex shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKVertexProgram.cpp:281)

*Dragon Ball: Xenoverse
{rsx::thread} RSX: Warning, version 450 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:82: '' :  syntax error
ERROR: 1 compilation errors.  No code generated.

{rsx::thread} RSX: 

LOG : https://gist.github.com/SakataGintokiYT/3284ac605787ec0dedbe10c74c63973f

**Comment by SakataGintokiYT** [comment]
Build [ ]

*Swords and Soldiers

**Comment by raven02** [comment]
**Dai-3-Ji Super Robot Taisen Z Jigoku-hen**

Vulkan backend . Hit at the end of intro movie

{rsx::thread} RSX: Src type 3 used, please report this to a developer.
{rsx::thread} RSX: Src type 3 used, please report this to a developer.
{rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:153: '' :  syntax error
ERROR: 1 compilation errors.  No code generated.

**Comment by AniLeo** [comment]
Are any of those still an issue?
