### ISSUE TITLE
Latest update crashes on EmuDeck

### ISSUE THREAD

**Issue by iloukine** [RPCS3/rpcs3#16163]
### Quick summary

After using EmuDeck to update, latest version crashes.

### Details

I have been using the shortcut to run RPCS3 on the Deck for the last couple days when messing with settings and everything was running good. Today I ran EmuDeck to update the rest of my emulators and after, I cannot run RPCS3 through the shortcut on desktop mode or through gaming mode. Immediate crash.

### Attach a log file

Cannot find a log as the application doesn't launch to the point a log is created. I'm new to the Deck so if anyone knows where else I'm forgetting to look, let me know and I'll upload it. Everything emulation related is running on SD.

### System configuration

Steam Deck OLED.

**Comment by iloukine** [comment]
Forgot to add, I updated yesterday using the application itself and it ran fine.

**Comment by iloukine** [comment]
Update: This is the error I get running through Konsole:

Launching: /home/deck/Applications/rpcs3.AppImage 
ROM not found. Launching rpcs3 directly
/tmp/.mount_rpcs3.TWzjxd/AppRun.wrapped: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /tmp/.mount_rpcs3.TWzjxd/AppRun.wrapped)

**Comment by MSuih** [comment]
Steam deck users reported a crash in version v0.0.33-16992 that was fixed in version v0.0.33-16994. If you're on one of the affected versions then you need to update to latest appimage manually since emulator doesn't get far enough to run the updater

**Comment by MSuih** [comment]
Oh yes, your issue is exact same as in #16158. Closing this as a duplicate on same ticket, communicate on the other one if issue persists after updating.
