### ISSUE TITLE
[Linux] OpenGL Renderer not working

### ISSUE THREAD

**Issue by Lukypie** [RPCS3/rpcs3#1616]
I got this error.

MESA-LOADER: could not create udev device for fd 16
libGL error: unable to load driver: amdgpu_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: amdgpu
Fatal error: Access violation writing location 0x2363620 at 0x7fb00db3b8f7.
Please report this error to the developers.
Annullato (core dump creato)

Yes I am using an R9 380 with the amdgpu driver. I can't start anything unless I use the null renderer.

**Comment by vlj** [comment]
Are you able to run any opengl app ?

**Comment by Lukypie** [comment]
yes I am, steam games etc

**Comment by kd-11** [comment]
Dump of glxinfo and glxgears -info? Also, this seems to happen alot on amdgpu for some users according to a quick google search. Bug might be from the mesa side of things.

**Comment by hcorion** [comment]
This bug is old and the necessary information hasn't been provided. Can we get this closed?
