### ISSUE TITLE
PS4 Controller Support Problem

### ISSUE THREAD

**Issue by Alex-Mirov** [RPCS3/rpcs3#16168]
### Quick summary

WipEout HD Fury cannot be played with ps4 controller on rpcs3.

### Details

RPCS3 emulator can see the controller and works
when dualshock 4 setting is enabled.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17230741/RPCS3.log)

### Attach capture files for visual issues

![4](https://github.com/user-attachments/assets/7a355280-9677-494d-9015-a32ddc7434b8)

### System configuration

OS: Windows 11 Enterprise 23H2 (latest updates)
CPU: i9 13900k
GPU 1: RTX 4080 (565.90 Driver)  
GPU 2: RX 6400  (24.9.1 Driver)    
GPU 3: Intel UHD 770 ( 32.0.101.6079 Driver)
                                                            
         

All system drivers are up to date.

Its a bug or does it require some setting?

**Comment by Megamouse** [comment]
you're using a custom pad config with xinput for this game
