### ISSUE TITLE
RSX Failed to compile shader (syntax error, parse error)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1617]
```
{rsx::thread} RSX: Src type 3 used, please report this to a developer.
{rsx::thread} RSX: Failed to compile shader: Fragment shader failed to compile with the following errors:
ERROR: 0:111: error(#132) Syntax error: "." parse error
ERROR: error(#273) 1 compilation errors.  No code generated
...
{rsx::thread} Exception: linkage failed: 'Fragment shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 
```

NPEA00004 - Lemmings
OpenGL

[NPEA00004 (Lemmings) OpenGL.zip](https://github.com/RPCS3/rpcs3/files/186357/NPEA00004.Lemmings.OpenGL.zip)

PARAM.SFO of the game needs to be changed in order for it to boot. Using RESOGUN's PARAM.SFO

**Comment by kd-11** [comment]
if (greaterThanEqual(cc0.xwyw, vec4(0., 0., 0., 0.)).x) r0.xy.x = (divsq_legacy(abs(r0.wxzw), -.wxyw) * 8.0).xy.x;

There is a swizzle on a non-existent value there. Should it have been zero (unlikely)? Is it an unimplemented function or register maybe?

**Comment by tambry** [comment]
> Src type 3 used, please report this to a developer.

Probably the reason.

**Comment by AniLeo** [comment]
The other games where the Src type 3 log appears do not crash like this I believe, I think this is partially unrelated to that

**Comment by tambry** [comment]
@AniLeo It's likely that the missing value should be the one from the unimplemented register type 3. It seems exactly like the problem in #1400. You should probably post a note about this game also there.
