### ISSUE TITLE
RPCS3 crushes on anything other than static interpeter

### ISSUE THREAD

**Issue by TheAndreiM** [RPCS3/rpcs3#16180]
### Quick summary

RPCS3 crashes on A8-3870 processor on LLVM. If I switch SPU and PPU to static interpreter, games work fine (albeit slow)

### Details

RPCS3 crahes for every game unless I run it on static interpeter. I do realize that I have an older CPU (A8- APU). However, after PPU modules get compiled and cached and after SPU gets cached, the RPCS3 just exits without any errors. I do realize that it could be due to some assembly instructions set. However, when I switch to interpeter (static) for both SPU and PPU, the games work fine (albeit a bit slow).  Is there any way I can reconpile LLVM to work on my processor with my instruction set (the CPU should have another power to run games OK (at least for my uses)

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17268283/RPCS3.log)

**Comment by Valtekken** [comment]
This is a 2011 4c/4t APU that has a 2300 score in multithreading on PassMark. It's not gonna work decently in any scenario when it comes to RPCS3, and the RPCS3 CPU tier list puts its CPU counterparts in the F tier.

Most you can do is save up for a new build with components that are supported.

**Comment by AniLeo** [comment]
It still must not crash since we support all x64 CPUs.

**Comment by kd-11** [comment]
For whatver reasons llvm is detecting the cpu as znver3 😬 
Set "llvm cpu" field in config file to nehalem instead.
