### ISSUE TITLE
[BLUS30109]MGS4 (metal gear solid 4) freeze in the first cutscene

### ISSUE THREAD

**Issue by bassamgamer0** [RPCS3/rpcs3#16187]
### Quick summary

the game couldn't pass the first cutscene it just freezes after minutes of starting a new game

### Details

i have watched a lot of videos and none of hem work i've used patches and still nothing solved my problem
i just get the same error
 E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30109/USRDIR/mgs/stage/s01a00l/data.cnf” [1]
E SYS: 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E sys_fs: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30109/USRDIR/photo” [2]

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17300115/RPCS3.log.gz)

### System configuration

i5 10400f
rtx 3060 ti driver : 565.90 (lateset one)
16GB rams

**Comment by AniLeo** [comment]
Log shows corrupted files, invalid issue. This is a support request and needs to be asked in the platforms made for that purpose.
