### ISSUE TITLE
(Arch Linux) Add game button not working while Open button does

### ISSUE THREAD

**Issue by JJoeDev** [RPCS3/rpcs3#16192]
### Quick summary

When using the "Add Game" button and selecting the correct directory it will display the message box with "Could not find any new software". But when I open the exact same directory using the "Open" button the game starts with no problems

### Details

Once the game has been extracted using the following command on Arch Linux "7z x Game.7z", and I try to add the game to the game list using the "Add Game" button from the File tab I will always get the message "Could not find any new software". This message gets displayed when I open an incorrect directory as well as with a correct directory. 

If I then decide to use the Open button the game will start with no issues at all, and play as expected. 

![structure](https://github.com/user-attachments/assets/b7c7b66b-b311-41df-bfa0-0585e77e0488)
![message](https://github.com/user-attachments/assets/7d908f08-d094-4c4d-b930-9cfc6921fdc0)

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17312637/RPCS3.log.gz)

### System configuration

os: Arch Linux
kernel: Linux 6.11.2-arch1-1
WM: bspwm(X11)
CPU: AMD Ryzen 5 3600
GPU: NVIDIA GeForce RTX 3070
GPU DRIVERS: 560.35.03
OpenGL: 4.6.0
Vulkan: 1.3.280
RAM: 16GB

**Comment by JJoeDev** [comment]
Because I had to transfer it from my Windows laptop to my primary linux desktop, and I was lazy

**Comment by Megamouse** [comment]
You can't put games into nested subdirectories. They have to be one folder per game in the games dir.
