### ISSUE TITLE
[Regression] Splinter cell chaos theory HD: Verification failed (object: 0x0)

### ISSUE THREAD

**Issue by Fabxx** [RPCS3/rpcs3#16195]
### Quick summary

Instant crash after linking all PPU Modules. It was working fine a couple of days ago. Tried older builds but the issue remains.

### Details

The error specifies a timeout for a game check on boot:
 
```
Verification failed (object: 0x0)
(in file /rpcs3/rpcs3/Emu/Cell/Modules/cellGame.cpp:800[:3], 
in function error_code cellGameBootCheck(vm::ptr<u32>, 
vm::ptr<u32>, vm::ptr<CellGameContentSize>, vm::ptr<char[32]>)) 
(errno=110=Connection timed out) (PPU: cellGameBootCheck)
```

Weird thing is that this issue is now replicating on older builds too (like a week old or less).

The PKG file was installed and the files were moved from the home partition. I made a symlink so the folder could be detected anyways to save space on the SSD. I could launch the game from steam via a sh script just fine, the location change does not affect this error.

### Build with regression

v0.0.33-17020-d51d5ce8 Alpha | HEAD

### Attach two log files

[RPCS3.log](https://github.com/user-attachments/files/17318515/RPCS3.log)

### System configuration

Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz | 16 Threads | 15.47 GiB RAM | TSC: 2.904GHz | AVX+ | FMA3

Operating system: POSIX, Name: Linux, Release: 6.1.0-25-amd64, Version: 1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 

GPU: 'NVIDIA GeForce RTX 3060' running on driver 550.78.0.0
GPU: 'llvmpipe (LLVM 15.0.6, 256 bits)' running on driver 0.0.1

Default GPU: 'NVIDIA GeForce RTX 3060'

(2024-08-26)

Qt version: Compiled against Qt 6.7.3 | Run-time uses Qt 6.7.3

**Comment by Megamouse** [comment]
I don't think you installed the game correctly.
Your VFS HDD dir points to `"...../Giochi/emulatori/rpcs3/rpcs3/dev_hdd0/"`,
but the HDD game you boot is in `"...../Giochi/PS3/Games/Tom Clancys Splinter Cell - Chaos Theory HD" `

**Comment by Fabxx** [comment]
> I don't think you installed the game correctly.
> Your VFS HDD dir points to `"...../Giochi/emulatori/rpcs3/rpcs3/dev_hdd0/"`,
> but the HDD game you boot is in `"...../Giochi/PS3/Games/Tom Clancys Splinter Cell - Chaos Theory HD" `

That's intentional. 

I moved the game so that i could parse the eboot.bin to run through a sh script, the other two scs work fine

**Comment by Megamouse** [comment]
Well then I'm not particularly interested in helping you :)
Can't debug this properly if you don't stick to the intended usage

**Comment by Fabxx** [comment]
> Well then I'm not particularly interested in helping you :)
> Can't debug this properly if you don't stick to the intended usage

I can retest with default path, but the result didn't change before.
