### ISSUE TITLE
Strange graphics problems

### ISSUE THREAD

**Issue by TitleChanQWERTY** [RPCS3/rpcs3#16194]
### Quick summary

Opengl rendering works very strangely. There are traces after transitions. Lots of dark parts, etc. Write Color Buffers does not help.

### Details

Very strange artifacts appear. Like traces of transitions. In general, the whole graphic looks strange. Lots of blackouts, no textures, etc.

![image](https://github.com/user-attachments/assets/5793590e-e2e8-4dd1-aaa4-2b3b89569fdc)
![image](https://github.com/user-attachments/assets/f0cd42ba-ad9b-45c1-8393-de8fce9169c1)
![image](https://github.com/user-attachments/assets/fc6837bb-9639-4498-a0a9-1d6a996c8723)

The interesting thing is that Sonic Unleashed had the same problem about a month ago. 
Of course, I can point to the problem of my own video card, but if possible, it would be great to improve the situation.
Emulators I used to play on: Cemu (WiiU emulator. No graphical artifacts) PCSX2 (PS2 emulator. Works great).
I also work in unity, and there the graphics work without any problems in the editor.

### Attach a log file

[logs.zip](https://github.com/user-attachments/files/17317691/logs.zip)

### System configuration

CPU: Intel Core i5-2400s
GPU: AMD Radeon HD 6750M
RAM: 8GB
OS: Windows
PC: iMac 2011 21.5

**Comment by YuriNator557** [comment]
The logs attached are empty.

**Comment by AniLeo** [comment]
Old AMD Windows drivers. This is a won't fix because the old AMD GL driver on Windows is unusable.
Use Linux to have working drivers with mesa.
