### ISSUE TITLE
Diagonally tilling effect and mirroring effect - RSPC3 running The Last of Us™ [BCUS98174] version 01.11

### ISSUE THREAD

**Issue by lakhwir** [RPCS3/rpcs3#16219]
### Quick summary

Diagonally tilling effect and mirroring effect in game - RSPC3 running The Last of Us™ [BCUS98174] version 01.11

### Details

I have the latest version of RSPC3 running The Last of Us™ [BCUS98174] version 01.11 with the latest patch and setting from RPCS3 Wiki. The first capture show the start screen and a diagonally tilling effect and the second capture is during to prologue again  diagonally tilling effect but it mirror what's happening. Like you can see the girls arm moving in the top of the screen diagonally magnified?

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17384763/RPCS3.log.gz)

### Attach capture files for visual issues

![The Last of Us 1](https://github.com/user-attachments/assets/507828d4-bcc1-43b5-83b4-3fa3396d4743)
![The Last of Us 2](https://github.com/user-attachments/assets/c0082c5f-61bc-4b7d-85ff-ef7c360adbde)

### System configuration

Windows 10 Pro 22H2 Version 10.0.19045 Build 19045
Motherboard Biostar System X370GTN ITX 
BIOS Version/Date	American Megatrends Inc. 5.14, 20/07/2020
AMD Ryzen 7 1700 Eight-Core Processor 3.00 GHz  8 cores 16 Threads (Not overclocked)
16GB RAM 3200MHz
AMD Radeon RX 480 8GB Driver Version 24.9.1
C: 256 SSD
D: 512 SSD
RPCS3 Version: 0.0.33-17042-18c01f71 Alpha | master

**Comment by FlexBy420** [comment]
Empty log

**Comment by kd-11** [comment]
Requires Strict Rendering Mode for older GPUs without the feedback loop extensions. See https://github.com/RPCS3/rpcs3/issues/16226

**Comment by lakhwir** [comment]
Thanks that fixed the issue.

**Comment by lastavenger2004** [comment]
The only valid solution without Strict Rendering Mode is to set resolution scaling up to 300
