### ISSUE TITLE
RSX sometimes uses high mipmap level

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1621]
In Silent Hill 3 RSX uses some 1280x720 texture with 12 mipmaps. log2(1280) is 11 so there is a mipmap level that shouldn't be here.

It looks like DX12 doesn't mind, I'm not sure about Vulkan. However in GL this leads to invalid texture. Capping mipmap level fixes the issue.

All backend are affected since they use rsx::texture::mipmap() to get mipmap count.

**Comment by kd-11** [comment]
In that case, maybe we could check the value returned from the registers and correct it if it is invalid to emulate RSX behaviour. Capping the levels is a good idea.

**Comment by vlj** [comment]
Fixed in master
