### ISSUE TITLE
The Last of Us [BCUS98174] Broken Lighting

### ISSUE THREAD

**Issue by lastavenger2004** [RPCS3/rpcs3#16226]
### Quick summary

There are blocks of lightings at the corner of the screen. 

Intel i5-11400
AMD RX 580
16GB RAM

Driver: AMD Adrenalin 24.3.1

![Screenshot 2024-10-18 233837](https://github.com/user-attachments/assets/2aaf1e48-ac2f-4052-b67d-267588e713d6)

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17440328/RPCS3.log.gz)

**Comment by Virtua64** [comment]
#16219

**Comment by kd-11** [comment]
This is clearly a driver issue (unsupported feedback loops most likely). Try using strict rendering mode which forces strict adherence to khronos specifications.

**Comment by lastavenger2004** [comment]
> This is clearly a driver issue (unsupported feedback loops most likely). Try using strict rendering mode which forces strict adherence to khronos specifications.

Thank you very much. As you suggested, it worked. If there was anything else, I will post another issue 🙏

**Comment by lastavenger2004** [comment]
The only valid solution without Strict Rendering Mode is to set resolution scaling up to 300
