### ISSUE TITLE
Uncharted 2: Among Thieves - Crash to desktop when loading cutscene after disabling alarm in Chapter 2

### ISSUE THREAD

**Issue by EveryGameGuru** [RPCS3/rpcs3#16229]
### Quick summary

RPCS3 crashes to desktop after freezing

### Details

In Chapter 2 of "Uncharted 2: Among Thieves" after disabling the alarm and walking through the door, a cutscene starts to load (The first few frames of the cutscene load) then freezes, then crashes to desktop with no error. I have tried with the CD version of the game and the PSN version. I have also tried starting a new game from Chapter 2, restarting at checkpoint, I've tried disabling patches, removing all "speedups", setting all emulation to most accurate. It still occurs.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17451362/RPCS3.log)

### Attach capture files for visual issues

https://file.io/IjTYspJBrTB0

### System configuration

13900K
RTX 4090
Nvidia Drivers: 565.90

**Comment by FlexBy420** [comment]
Unable to reproduce.
[RPCS3.log.gz](https://github.com/user-attachments/files/17451452/RPCS3.log.gz)

**Comment by EveryGameGuru** [comment]
I have now tested with US version DISC+PSN and European DISC versions, and the issue is present in all

**Comment by EveryGameGuru** [comment]
It is RESHADE causing the crash. My apologies
