### ISSUE TITLE
Motorstorm: Pacific Rift - MacOS (Vulkan) - Graphical tearing bug with volcanic environments

### ISSUE THREAD

**Issue by l0wd0ct0r** [RPCS3/rpcs3#16225]
### Quick summary

Any environments that have volcanic elements, there is a purple-backed tearing to the heat effects. This seems only present in the MacOS RPCS3 version, I have not noticed the issue in the Windows version.

### Details

![iScreen Shoter - RPCS3 - 241018171536](https://github.com/user-attachments/assets/88a17186-9347-4334-acae-cb131617c2fe)

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17438337/RPCS3.log)

### System configuration

MacBook Pro M3 Max

**Comment by FlexBy420** [comment]
Empty log, also missing rsx capture

**Comment by l0wd0ct0r** [comment]
Sure.. let me try and get those

**Comment by l0wd0ct0r** [comment]
[RPCS3.log](https://github.com/user-attachments/files/17438585/RPCS3.log)
[
](https://www.dropbox.com/scl/fi/w7m506q01ai4y3eks6fgq/BCES00129_20241018175944_capture.rrc.gz?rlkey=xtwc58jrbla124xjuw6yfeg9e&st=eir2n9c5&dl=0)

**Comment by l0wd0ct0r** [comment]
RSX Capture:
[
](https://www.dropbox.com/scl/fi/w7m506q01ai4y3eks6fgq/BCES00129_20241018175944_capture.rrc.gz?rlkey=xtwc58jrbla124xjuw6yfeg9e&st=37jix7pg&dl=0)

**Comment by l0wd0ct0r** [comment]
Just to update - these artifacts are not present under Strict Rendering Mode, but are not seemingly tied to resolution scaling alone because they are seen at 720p without SRM. I usually set RS at 200% (1440p) and RST at 256x256.

**Comment by l0wd0ct0r** [comment]
This issue also affects water environments, a similar purple effect is seen.

**Comment by Virtua64** [comment]
set Anisotropic Filtering to Auto and see if that changes anything

**Comment by l0wd0ct0r** [comment]
Thanks - yep, same with AF set to Auto. In fact with RS 100% RST 16x16 and AF Auto, the artifacting is present, but when SRM is selected, the issue is not present. Is SRM basically that setting or is there some other stuff it controls?

**Comment by kd-11** [comment]
SRM makes significant changes to how the renderer works behind the scenes. It is not just a toggle for the other options.

**Comment by l0wd0ct0r** [comment]
OK, sure - I appreciate the confirmation. Unfortunately running under SRM slows things down in this title on MacOS as well, so I almost assumed that it was more than a resolution scale default thing. 

I'll leave this issue open in case anyone wants to pick up :)

**Comment by kd-11** [comment]
I think you can set MSL to strict in MacOS somewhere in settings.
If that doesn't fix it, then you have decompression artifacts because MVK does not support this extension: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_attachment_feedback_loop_layout.html
The spec-compliant workaround includes making fullscreen copies of render targets before drawing which is one of the reasons why strict mode is so slow.

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed.
I'll leave it to kd-11 to close or to investigate.

**Comment by kd-11** [comment]
If it's fixed by strict mode then we should close it.
