### ISSUE TITLE
The Last of Us [BCUS98174] Missing Voice

### ISSUE THREAD

**Issue by lastavenger2004** [RPCS3/rpcs3#16228]
### Quick summary

Character's mouth is moving, subtitle is going on, but their voice get disappeared, cut in the middle of their talking, or suddenly start talking mid-sentence.

Intel i5-11400
AMD RX 580
16GB RAM

Driver: AMD Adrenalin 24.3.1

https://github.com/user-attachments/assets/2c7b306d-da1b-42e6-ab54-d2f5c1205050

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17447368/RPCS3.log.gz)

**Comment by Pipi86** [comment]
I've experienced the same issue, and doesn`t get fixed by trying every possible combination of the ingame audio settings. The only thing i noted was that you can hear tommy and joel's voices again if you get the camera position closer to them by rotating it (making the girl look behind the car).

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed
