### ISSUE TITLE
Qt::ColorScheme color_scheme()

### ISSUE THREAD

**Issue by 007fred50** [RPCS3/rpcs3#16222]
### Quick summary

I got error in Qt::ColorScheme

### Details

Hello, i trying to compile rpcs3, but then i hit 83% i got error in Qt::ColorSchame.

Can someone help me with this?

### Attach a log file

[ 83%] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/rpcs3_ui_autogen/mocs_compilation.cpp.o
In file included from /home/console/Downloads/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/../../../../../rpcs3/rpcs3/rpcs3qt/tooltips.h:3,
                 from /home/console/Downloads/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/moc_tooltips.cpp:10,
                 from /home/console/Downloads/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/mocs_compilation.cpp:77:
/home/console/Downloads/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/../../../../../rpcs3/rpcs3/rpcs3qt/qt_utils.h:151:35: error: ‘ColorScheme’ in namespace ‘Qt’ does not name a type
  151 |                 static inline Qt::ColorScheme color_scheme()
      |                                   ^~~~~~~~~~~
/home/console/Downloads/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/../../../../../rpcs3/rpcs3/rpcs3qt/qt_utils.h: In function ‘bool gui::utils::dark_mode_active()’:
/home/console/Downloads/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/../../../../../rpcs3/rpcs3/rpcs3qt/qt_utils.h:158:32: error: ‘color_scheme’ was not declared in this scope
  158 |                         return color_scheme() == Qt::ColorScheme::Dark;
      |                                ^~~~~~~~~~~~
/home/console/Downloads/rpcs3_build/rpcs3/rpcs3qt/rpcs3_ui_autogen/EWIEGA46WW/../../../../../rpcs3/rpcs3/rpcs3qt/qt_utils.h:158:54: error: ‘Qt::ColorScheme’ has not been declared
  158 |                         return color_scheme() == Qt::ColorScheme::Dark;
      |                                                      ^~~~~~~~~~~
make[2]: *** [rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/build.make:106: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/rpcs3_ui_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2936: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

### System configuration

Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

**Comment by kd-11** [comment]
You need a newer version of qt6 than ships with ubuntu.
