### ISSUE TITLE
Sonic Unleashed [BLES00425]: 'sy_ss_access_control_engine' failed error

### ISSUE THREAD

**Issue by hypersonic9000** [RPCS3/rpcs3#16223]
### Quick summary

I AM USING THE MACOS ARM BUILD!!!

Sonic Unleashed crashes immediately on launch, as soon as caches are compiled

### Details

Crashes immediately on launch, application has likely crashed notification 

Running build 0.0.33-17042

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17401793/RPCS3.log)

### Attach capture files for visual issues

![unleashed_crash](https://github.com/user-attachments/assets/7c31dd2e-04e4-41d5-84c3-cb6c7f0a644c)

### System configuration

2020 M1 MacBook Air 8GB RAM
MacOS 15.1 Beta 7

**Comment by FlexBy420** [comment]
You used quite weird settings, reset your config and try wiki settings.

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed
