### ISSUE TITLE
CPU not fully utilised? MGS4

### ISSUE THREAD

**Issue by cleggorz** [RPCS3/rpcs3#16230]
### Quick summary

CPU is not fully utilised in MGS4.  I have not tried any other game so far.

### Details

So this is my first time I've used RPCS3 in a long while. I have been waiting for the longest time to play MGS4 properly.

I have noticed the CPU is not being fully utilised maxing around 80% average on a 9700k 

Don't get me wrong the game so far has been fully playable with an average of 45fps ish, 60 in some cases like cutscenes. 

Is there any way to get my CPU closer to maxing and unlocking more FPS without overclocking? 

I have done all the correct configurations mentioned on the wiki. 

I have even turned shadows off too. Used canary patches etc. Am I missing something or is this just where things are at right now? 

Either way I'm am so happy I can play this game as is. I just wanted to know if I missed something. 

Thank you for all the work you have done. This is really programming genius!

Thank you for all your hard work. I'm just a small fish in the grand scheme but this means the world to me. 

### Attach a log file

No log the game runs.

### Attach capture files for visual issues

.

### System configuration

9700k, ddr4 16gb, 3070 fe. Average.

### Other details

.

**Comment by cleggorz** [comment]
.

**Comment by FlexBy420** [comment]
Its impossible to use 100% of available cpu time, RPCS3 already is using your cpu the most efficient way it can.
https://www.brendangregg.com/blog/2017-05-09/cpu-utilization-is-wrong.html

**Comment by cleggorz** [comment]
Thank you for the reply. My plan is to upgrade soon. I just thought I was going crazy!

**Comment by cleggorz** [comment]
The game is more than playable right now (where I'm at in the game). I played this game on PS3 back in the day (Multiple times) and I'm definitely getting better performance with RPCS3. I really can not complain. 

This really is a marvel of programming genius!
