### ISSUE TITLE
Sonic Unleashed (BLUS30244) - Game freeze 

### ISSUE THREAD

**Issue by LasagnaPie** [RPCS3/rpcs3#16232]
### Quick summary

Sonic Unleashed randomly freezes when playing

### Details

Sonic Unleashed randomly freezes when playing the game, , RPCS3 itself will freeze but "RPCS3.log.gz" file gets deleted so can't upload it and get access violation when copying when crashed RPCS3 is running

```
E RSX: [attrib buffer] Pool limit was reached. Will attempt to swap out the current heap.
> F {RSX [0x00faf64]} SIG: Thread terminated due to fatal error: Verification failed (object: 0x0)
> (in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKVertexBuffers.cpp:339[:4], in function struct vk::vertex_upload_info __cdecl VKGSRender::upload_vertex_data(void))
> F {RSX Offloader} VM: Access violation reading location 0xb1671ce8 (unmapped memory)
```

![crashhh](https://github.com/user-attachments/assets/cfc4f4b0-bd22-45f0-9afb-54defdce5823)

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17452274/RPCS3.log)

### System configuration

Ryzen 7800X3D
Radeon 7900XTX

**Comment by Jonathan44062** [comment]
Not using RPCS3 Wiki settings, next time, join the server discord for support, not here
https://wiki.rpcs3.net/index.php?title=Sonic_Unleashed

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed
