### ISSUE TITLE
Can we get MGS4 labeled as fully playable. I just completed it.

### ISSUE THREAD

**Issue by cleggorz** [RPCS3/rpcs3#16239]
### Quick summary

MGS4 is fully playable with using the wiki settings.  I crashed once. 

### Details

What details do I have to share? 

THANK YOU!

Thank you for bringing my adolescent dreams to life.

The game ran great at 1440p on a 9700k and a 3070 FE.

I could have probably pushed 4k . I had the display resolution set to 1080p with upscale to 1440p. 

45 FPS average. 60 FPS in many areas. 

The only single area I struggled was leaving Shadow Moses in REX 20-30 FPS with everything happening.

I send my love to the dev team for making my dreams a reality.

**Comment by FlexBy420** [comment]
Github is not a place for compatibility reports. And no MGS4 is not playable due to bad performance and freezes/crashes.
