### ISSUE TITLE
weird glitch on watch dogs rpcs3

### ISSUE THREAD

**Issue by iamthebestatash** [RPCS3/rpcs3#16235]
### Quick summary

so i was trying to play watch dogs on rpcs3 and this weird texture glitch keeps apearring i thoght it was lights glitching so i turned write color buffers on but it made it worse can someone help me

### Attach a log file

[logz.txt](https://github.com/user-attachments/files/17476718/logz.txt)

### Attach capture files for visual issues

![Screenshot 2024-10-21 210119](https://github.com/user-attachments/assets/2346e4be-9c46-4ff0-aa95-c904c77b2a0a)
![Screenshot 2024-10-21 130924](https://github.com/user-attachments/assets/e66acf58-c729-461d-9e46-8378bca5654c)
![Screenshot 2024-10-19 195028](https://github.com/user-attachments/assets/e98859f7-0ee0-4b7e-8196-bc1fc1552160)
![Screenshot 2024-10-19 175951](https://github.com/user-attachments/assets/15b798ec-274b-4075-a324-7110173754ed)

**Comment by FlexBy420** [comment]
Log is from UI, post a full log from RPCS3 folder.
But since you have intel igpu I assume its another shitty intel drivers memery.

**Comment by AniLeo** [comment]
No valid log file
No capture files for visual issues
No system information

Closing as Invalid

**Comment by iamthebestatash** [comment]
mb here is the log 
[RPCS3.log](https://github.com/user-attachments/files/17525474/RPCS3.log)

**Comment by iamthebestatash** [comment]
> Log is from UI, post a full log from RPCS3 folder. But since you have intel igpu I assume its another shitty intel drivers m
