### ISSUE TITLE
[Regression] After the latest commit for amd video cards, the emulator crashes after launching the game.

### ISSUE THREAD

**Issue by TitleChanQWERTY** [RPCS3/rpcs3#16237]
### Quick summary

Today I updated as I always do. I thought I would launch the game and check the emulator's performance. But after compiling ppu and spu, the emulator just crashes

### Details

After https://github.com/RPCS3/rpcs3/pull/16234 I decided to run the emulator, update, and run the games to check the work and see the changes (I was focused on checking the performance). But after all the compilations, the emulator just crashed.
And it happens all the time. The most interesting thing is that previous builds worked fine, and without such problems.
The games I tested on: Persona 4 arena ultimax and Persona 5

### Build with regression

v0.0.33-17054

### Attach two log files

[RPCS3.log](https://github.com/user-attachments/files/17494139/RPCS3.log)
[RPCS3.log.gz](https://github.com/user-attachments/files/17495261/RPCS3.log.gz)

### System configuration

CPU: Intel Core i5-2400s
GPU: AMD Radeon HD 6750M
RAM: 8GB
OS: Windows
PC: iMac 2011 21.5

**Comment by Mejker10** [comment]
I can confirm the same with Ryu ga Gotoku Kenzan. Game and Emulator simply crashes right before showing usual title screen. Everything works fine once i rolled back to the previous build.

**Comment by kitrodian** [comment]
I'm using an Nvidia card and this is still happening. As soon as it's done compiling the entire thing crashes.

**Comment by stelsosmac** [comment]
r5 5600 rtx3070 тоже самое, не запускается даже XMB

**Comment by TitleChanQWERTY** [comment]
> r5 5600 rtx3070 тоже самое, не запускается даже XMB

Виходить, проблема і не в залізи

**Comment by TitleChanQWERTY** [comment]
> r5 5600 rtx3070 тоже самое, не запускается даже XMB

Схоже, проблема також і не в залізі

**Comment by AniLeo** [comment]
The ticket is missing the second log file, but the build has been marked as broken in the updater
