### ISSUE TITLE
Crash in Demon's Souls 

### ISSUE THREAD

**Issue by Zerocoolsem** [RPCS3/rpcs3#16246]
### Quick summary

Alguém realmente sabe como arrumar isso?

Já desliguei o DFMA

Erro RPCS3

Segui vários vídeos no YouTube dicas, deixei original com MOD e sempre o mesmo com overclock sem overclock, não para esse maldito erro (unmapped memory)

E pior ja mexi no defender limpei tudo que pode imaginar, troquei de ISO nada adianta.

F {PPU[0x1000005] Thread (HighGraphics) [0x01479a98]} VM: Access violation reading location 0xe0 (unmapped memory)

Does anyone really know how to fix this?

I have already turned off DFMA

RPCS3 error

I followed several videos on YouTube with tips, I left it original with MOD and always the same with overclocking without overclocking, not for this damn error (unmapped memory)

And what's worse, I've already changed the defender, I've cleaned everything you can imagine, I've changed the ISO, it doesn't help.

### Details

Alguém realmente sabe como arrumar isso?

Já desliguei o DFMA

Erro RPCS3

Segui vários vídeos no YouTube dicas, deixei original com MOD e sempre o mesmo com overclock sem overclock, não para esse maldito erro (unmapped memory)

E pior ja mexi no defender limpei tudo que pode imaginar, troquei de ISO nada adianta.

F {PPU[0x1000005] Thread (HighGraphics) [0x01479a98]} VM: Access violation reading location 0xe0 (unmapped memory)

Does anyone really know how to fix this?

I have already turned off DFMA

RPCS3 error

I followed several videos on YouTube with tips, I left it original with MOD and always the same with overclocking without overclocking, not for this damn error (unmapped memory)

And what's worse, I've already changed the defender, I've cleaned everything you can imagine, I've changed the ISO, it doesn't help.
![Captura de tela 2024-10-24 230745](https://github.com/user-attachments/assets/445748d4-3412-4177-9d2f-d91caf4c37b7)
![Captura de tela 2024-10-24 230816](https://github.com/user-attachments/assets/aa1019c2-05eb-4585-a2b5-572350e0ebad)

### Attach a log file

Alguém realmente sabe como arrumar isso?

Já desliguei o DFMA

Erro RPCS3

Segui vários vídeos no YouTube dicas, deixei original com MOD e sempre o mesmo com overclock sem overclock, não para esse maldito erro (unmapped memory)

E pior ja mexi no defender limpei tudo que pode imaginar, troquei de ISO nada adianta.

F {PPU[0x1000005] Thread (HighGraphics) [0x01479a98]} VM: Access violation reading location 0xe0 (unmapped memory)

Does anyone really know how to fix this?

I have already turned off DFMA

RPCS3 error

I followed several videos on YouTube with tips, I left it original with MOD and always the same with overclocking without overclocking, not for this damn error (unmapped memory)

And what's worse, I've already changed the defender, I've cleaned everything you can imagine, I've changed the ISO, it doesn't help.

### Attach capture files for visual issues

Alguém realmente sabe como arrumar isso?

Já desliguei o DFMA

Erro RPCS3

Segui vários vídeos no YouTube dicas, deixei original com MOD e sempre o mesmo com overclock sem overclock, não para esse maldito erro (unmapped memory)

E pior ja mexi no defender limpei tudo que pode imaginar, troquei de ISO nada adianta.

F {PPU[0x1000005] Thread (HighGraphics) [0x01479a98]} VM: Access violation reading location 0xe0 (unmapped memory)

Does anyone really know how to fix this?

I have already turned off DFMA

RPCS3 error

I followed several videos on YouTube with tips, I left it original with MOD and always the same with overclocking without overclocking, not for this damn error (unmapped memory)

And what's worse, I've already changed the defender, I've cleaned everything you can imagine, I've changed the ISO, it doesn't help.

### System configuration

RYZEN 5600
RTX 3060 12 GB
32 GB 3200MHz
B550M AORUS ELITE MOTHER BOARD.

### Other details

Alguém realmente sabe como arrumar isso?

Já desliguei o DFMA

Erro RPCS3

Segui vários vídeos no YouTube dicas, deixei original com MOD e sempre o mesmo com overclock sem overclock, não para esse maldito erro (unmapped memory)

E pior ja mexi no defender limpei tudo que pode imaginar, troquei de ISO nada adianta.

F {PPU[0x1000005] Thread (HighGraphics) [0x01479a98]} VM: Access violation reading location 0xe0 (unmapped memory)

Does anyone really know how to fix this?

I have already turned off DFMA

RPCS3 error

I followed several videos on YouTube with tips, I left it original with MOD and always the same with overclocking without overclocking, not for this damn error (unmapped memory)

And what's worse, I've already changed the defender, I've cleaned everything you can imagine, I've changed the ISO, it doesn't help.

**Comment by AniLeo** [comment]
Closed obvious spam issue + pirated copy as invalid
