### ISSUE TITLE
weird texture glitch on watch dogs rpcs3

### ISSUE THREAD

**Issue by iamthebestatash** [RPCS3/rpcs3#16249]
### Quick summary

this is my second time posting this issue the first got closed bcs i didnt give logs  and very sorry to the developers anyways  so i was trying to emulate watch dogs on rpcs3 and this weird texture glitch keeps appearing i tired changing the firmware and the app version as well

### Details

all the texture are just invisible nothing is appearing except the object and the characters outlines

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17525674/RPCS3.log)

### Attach capture files for visual issues

![Screenshot 2024-10-19 175951](https://github.com/user-attachments/assets/cfba545a-4642-4171-a08c-7aaeb89681f2)
![Screenshot 2024-10-21 210119](https://github.com/user-attachments/assets/a5146bf4-5777-4f33-8120-20afeb7689f0)
![Screenshot 2024-10-21 130924](https://github.com/user-attachments/assets/ca30c008-ea0d-441f-8896-c456e3a550ea)
![Screenshot 2024-10-19 195028](https://github.com/user-attachments/assets/0cb4ee38-b8f4-487b-9a64-a5c115889cac)

### System configuration

processer: intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
Ram:8.00 GB (7.85 GB usable)
system: 64-bit operating system, x64-based processor
its also windows 11 idk if it helps

**Comment by iamthebestatash** [comment]
sorry for not giving enough information the first time again

**Comment by AniLeo** [comment]
Ancient firmware version which is invalid as RPCS3 is not meant to be compatible with those, still no rsx capture files, and also using unsupported gpu/driver.

Closed as Invalid.
