### ISSUE TITLE
Some of the audio of Demon's Souls seems to rapidly repeat at seemingly random intervals. Might be a hardware specific issue.

### ISSUE THREAD

**Issue by slandercore** [RPCS3/rpcs3#16242]
### Quick summary

Some of the audio of Demon's Souls seems to rapidly repeat at seemingly random intervals. Some but not all sounds repeat regardless of fps or frametiming. Might be a hardware specific issue.

### Details

It's quite a simple bug, the background soundscape sfx and the reverb sfx rapidly repeat in some places but specially noticeable in closed spaces when reverb is can be easily heard. It loops at seemingly random intervals.

This has been an issue I've been experiencing for years with RPCS3 and Demon's Souls. At first I thought it was just that my PC couldn't handle the game and at the time it really couldn't, so I didn't pursue it further but now that it does run well in the current build, I have decided to write this issue.

I have tried numerous solutions from similar-ish issues others have written. Like messing with audio settings, cpu settings, gpu settings, advanced settings but have not been able to fix this. The fact that I couldn't find anyone else having this precise issue makes me think that it might be a hardware specific bug but I don't really know enough to say so. Although maybe I just missed one.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17511262/RPCS3.log)

### Attach capture files for visual issues

I will now provide footage of it for you to listen to, it's pretty obvious but not too loud. (sorry if it's in the wrong place):

https://github.com/user-attachments/assets/321dde77-8ead-44dc-a896-d73d723ffc4e

### System configuration

OS: Windows 10 64-bit | Build 19045
CPU: AMD FX-6300 | OC at 4.4GHz
GPU: NVIDIA GeForce 970 | Driver version 566.03 (up to date at the time of writing)
RAM: 16GB 800GHz | mixed with 933GHz
Storage: 2 ssds, RPCS3 installed at disk 0, Demon's Souls files at disk 1

### Other details

My current game configurations are just the recommended ones in the wiki for this game:
-SPU block size | safe
-Resolution Scale | 1920 x 1080
-Resolution Scale Threshold | 640x640
-Write color buffers | On
-Maximum SPURS threads | 3

Will try to be helpful and understandable.

**Comment by Megamouse** [comment]
Issues with patches applied are not allowed

**Comment by kd-11** [comment]
FX-6300 is the culprit here. It has 3 cores.
