### ISSUE TITLE
Support resizing the screen on Vulkan [PPSSPP / RPCS3 ]

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1624]
@kd-11 
@vlj 
Fixed resizing the screen on Vulcan by unknownbrackets
Will it be useful in Rpcs3 ?
https://github.com/hrydgard/ppsspp/pull/8657

**Comment by tambry** [comment]
PPSSPP != RPCS3
You simply have to [re-create the swapchain when the window is resized](https://sourceforge.net/projects/symbiandump/files/documentation/) and there isn't a lot else to that.
You have to also make sure that the swapchain isn't created with width = 0 or height = 0.

**Comment by kd-11** [comment]
Resizing support is not difficult, its just that the vulkan backend has bigger issues that have taken all the attention. Thanks for opening this as an issue though. It'll help to keep track.

**Comment by paulsapps** [comment]
@tambry not sure that URL is related..

**Comment by tambry** [comment]
@paulsapps Seems like I pasted the wrong link. Fixed.

**Comment by zminhquanz** [comment]
PPSSPP has fixed resize screen on Vulkan API , you can fix this on RPCS3

**Comment by tambry** [comment]
@zminhquanz RPCS3 is not PPSSPP. Though one man jumped from some roof and didn't die, doesn't mean another one should.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/1718

**Comment by raven02** [comment]
Fix by https://github.com/RPCS3/rpcs3/pull/1787
