### ISSUE TITLE
Emulator completely froze just before shader compilation on match end screen in Pro Evolution Soccer 2008

### ISSUE THREAD

**Issue by SSUPII** [RPCS3/rpcs3#16254]
### Quick summary

During the match end cinematic in Pro Evolution Soccer 2008, the game froze and didn't unlock itsself. The emulator was completely locked.

### Details

As said in the summary, the game froze during the match end cinematic (multiple matches took place before this happened, the emulator was running the same game for more than 2 hours).

If you tried to stop the game, it will not get stopped. Using the Reboot action in the emulator didn't do anything. Clicking the Close action on my window manager would have no effect, but the emulator interface was fully usable still.

You could close the emulator window by using the File > Exit option, but reopening the emulator it would complain about another instance still running and a valid buffer file still being present. In fact, using a tasks monitor, the emulator was not visible but stuck operating.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17533555/RPCS3.log)

### System configuration

System:
  Host: debian Kernel: 6.1.0-23-amd64 arch: x86_64 bits: 64 Desktop: Xfce
    v: 4.18.1 Distro: Debian GNU/Linux 12 (bookworm)
  Mobo: ASUSTeK model: X580GD v: 1.0 serial: <superuser required>
    UEFI: American Megatrends v: X580GD.324 date: 01/27/2021
CPU:
  Info: 6-core Intel Core i7-8750H [MT MCP] speed (MHz): avg: 800
    min/max: 800/4100
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] driver: nvidia
    v: 550.120
  Device-3: IMC Networks USB2.0 HD UVC WebCam type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa dri: iris gpu: i915
    resolution: 1920x1080~60Hz
Info:
  Processes: 319 Uptime: 2h 47m Memory: 31.2 GiB used: 5.95 GiB (19.1%)
  Shell: Bash
  inxi: 3.3.26

### Other details

The match end background cinematic cycles between multiple camera angles of the soccer field. The second used is always a close up of the fans in the stands that uses many dedicated models just for this (and they are not always the same used every match). For this reason the scrolling of the camera angles will prompt the compiling of new shaders for their models. Enough time passed on the match end data where the background would have switched camera to the fans one.

Only this time the emulator froze on this situation, the other times it just continued and compiled the appropriate shaders for the current game state.

**Comment by Tamalero** [comment]
Having a similar issue. 

Right after updating to the latest versions. All Ratchet and Clank no longer go beyond the SPU compilation. Always freezes in the lasts ones with different errors.

Operating System: Nobara Linux 40
KDE Plasma Version: 6.2.2
KDE Frameworks Version: 6.7.0
Qt Version: 6.7.2
Kernel Version: 6.11.5-200.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 32 × Intel® Core™ i9-14900K
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4090/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: Z690 AORUS PRO
System Version: -CF


Version 0.0.33-17074 Seesm to be affected.
While version 0.0.33-17046 is the latest one with no issue.

Last parts of the LOG before the freeze are similar:


S PPU: LLVM: Loaded module v6-kusa-EdCH7Q57Fuzcspi7ocr35g-00001t-alderlake.obj
S PPU: LLVM: Loaded module v6-kusa-oV37GWP2sbqAg9WWyHYKsF-00001t-alderlake.obj
S PPU: LLVM: Loaded module v6-kusa-sMnFN1f6zVuQeQxJeR8atQ-0004YN-alderlake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libhttp.sprx” (id=0x23004000)
E SYS: 'cellGameGetParamString' failed with 0x8002cb21 : id 10 is not supported in the current check mode: content_permission::check_mode::hdd_game [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUA80908/USRDIR/parameters.txt” [1]
E SYS: 'sys_mmapper_free_address' failed with 0x80010002 : CELL_EINVAL, 00 [1]
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) x2


This freezes the whole RPCS3 and needs to be killed via PROCESSES monitor.


The latest Successfull Log:


U cellNetCtl TODO: cellGameUpdateInit()
E RSX: Image resource file `/home/cesarin/.var/app/net.rpcs3.RPCS3/config/rpcs3//Icons/ui/spinner-24.png' could not be opened (Not found)
S PPU: LLVM: Loaded module v6-kusa-Auatw4Ww50V891sLYtpwEc-00001t-alderlake.obj
S PPU: LLVM: Loaded module v6-kusa-pENMLjkGtKhNRHEp3bjZsg-0004YN-alderlake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/librudp.sprx” (id=0x23023300)
U sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd0010298)
U sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd00f9a98)
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUA80908/USRDIR/ui/screens/legal.gfx” [1]
E sys_fs: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUA80908/USRDIR/ui/screens/Legal_I20.tga” [1]
E RSX: Image resource file `/home/cesarin/.var/app/net.rpcs3.RPCS3/config/rpcs3//Icons/ui/spinner-24.png' could not be opened (Not found)
S RSX: Program compiled successfully x4
E SYS: 'cellSaveDataListAutoLoad' failed with 0x8002b404 : CELL_SAVEDATA_ERROR_PARAM, 26 [1]
E SYS: 'sys_ppu_thread_get_priority' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sceNpDrmIsAvailable2' failed with 0x80010006 : CELL_ENOENT, /dev_hdd0/game/NPUA80908/USRDIR/psnpass.edat [1]
E SYS: 'sceNpDrmIsAvailable2' failed with 0x80010006 : CELL_ENOENT, /dev_hdd0/game/NPUA80908/USRDIR/pyroarmor.edat [1]
S RSX: Program compiled successfully x4

[2024-10-31-3317074rpcs3crashlog.txt](https://github.com/user-attachments/files/17594157/2024-10-31-3317074rpcs3crashlog.txt)

**Comment by elad335** [comment]
Fixed by #16269
