### ISSUE TITLE
Mac mini 2023 / Dead Space "Select" not functioning as expected

### ISSUE THREAD

**Issue by steeler-fanatic** [RPCS3/rpcs3#16251]
### Quick summary

In Dead Space, "Select" is used to bring up the map and in combination with R2 bring up the current objective.  Despite various attempts to ensure mapping is correct, it brings up an application selector window instead.  Game runs great otherwise.  Forgive me if this is a stupid question - I'll gladly take the heat for the solution!

### Details

System: Mac mini 2023  / Mac OS: Sequoia 15.0.1
RPCS3 Version  0.0.33-17065-431221f1 Alpha
Original Sony PS3 Controller connected via USB, configuration:
![Screenshot 2024-10-25 at 7 55 18 PM](https://github.com/user-attachments/assets/38c47924-48f3-4c5f-a6c5-b6b6afffe4ee)
Also attached is a screenshot of what is displayed when "Select" is used:
![Screenshot 2024-10-25 at 7 59 25 PM](https://github.com/user-attachments/assets/3bae11fc-92e5-4392-b715-924e77b441b2)

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17528365/RPCS3.log)

**Comment by darkuser89** [comment]
Press Home button to open Launchpad = OFF 
<img width="827" alt="Screenshot 2024-10-26 at 03 18 40" src="https://github.com/user-attachments/assets/cb10b5ee-03a3-40ee-9664-07d0d57e2fd4">
