### ISSUE TITLE
0.0.34 alpha has abnormally terminated in macos 14.6.1 after installing firmware

### ISSUE THREAD

**Issue by dennisans2** [RPCS3/rpcs3#16279]
### Quick summary

RPCS3 0.0.34 alpha has abnormally terminated in macos 14.6.1 after installing firmware. No matter which app I try to run, it crashes after showing up abnormally terminated message.

### Details

It didn't happed on previous versions. I tried other things like changing firmware versions into 4.90 or lower, but didn't work.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17606984/RPCS3.log)

### Attach capture files for visual issues

![스크린샷 2024-11-02 오후 9 44 05](https://github.com/user-attachments/assets/e1f50d2c-fb53-4e0e-aefe-ec13c36b24f9)

### System configuration

Macos 14.6.1
Intel Core i5 1.8GHZ dual core
Intel HD Graphics 6000 1536 MB
8GB 1600 MHz DDR3

### Other details

none

**Comment by AniLeo** [comment]
Invalid regression report, does not follow the template

Furthermore, you're below minimum requirements, macOS with Intel iGPU is not supported, you need an AMD dedicated GPU

**Comment by TitleChanQWERTY** [comment]
@dennisans2 try openGL
