### ISSUE TITLE
[Regression] The Last of Us [BCUS98174] Lighting and Effects Glitch

### ISSUE THREAD

**Issue by lastavenger2004** [RPCS3/rpcs3#16296]
### Quick summary

I've tested the last of us in both versions "v0.0.34-17098-2262ac16" and "v0.0.22-13821-7842812e" 

Default settings in both build, "Read color buffers" and "Accurate RSX reservation access" are enabled and RSX FIFO accuracy is set to Atomic

Attention: Ignore the white light overlay at the bottom half of the intro screen. I acknowledge that it's easily fixable via patches (specifically Enable GPU Lighting patch)

### Build with regression

v0.0.34-17098-2262ac16

### Attach two log files

Build that works (0.0.22)

[RPCS3.log (build that works).gz](https://github.com/user-attachments/files/17651679/RPCS3.log.build.that.works.gz)

Build with regression (0.0.34)

[RPCS3.log (build with regression).gz](https://github.com/user-attachments/files/17651681/RPCS3.log.build.with.regression.gz)

### Attach capture files for visual issues

Build that works (0.0.22)

https://github.com/user-attachments/assets/c887274b-810e-4a38-8d03-8a2427649eeb

Build with regression (0.0.34)

https://github.com/user-attachments/assets/cb355d4b-3d16-4d1f-988e-43e351125784

### System configuration

CPU (Processor): Intel i5 11400
GPU (Graphics Card): AMD RX 580 8GB
OS (Operating System): Windows 11 24H2 (Latest Version)
MB (Motherboard): ASUS H-510K

Graphics Driver: AMD Adrenalin 24.9.1

**Comment by kd-11** [comment]
You also need read depth, rsx detiling and strict rendering mode.

**Comment by lastavenger2004** [comment]
> You also need read depth, rsx detiling and strict rendering mode.

I tried Strict Rendering Mode in v0.0.34-17098-2262ac16. Doesn't work. Maybe it'll work with patches but I'm not using any patches. (Strict Rendering Mode worked for me in 0.0.34-17086, but I was also using patches)

Still, everything works just fine in v0.0.22-13821-7842812e (with Enable GPU Lighting since the rsx detiling option hadn't come out yet). Without strict rendering mode and using FSR.

This log is for v0.0.34-17098-2262ac16
[RPCS3.log.gz](https://github.com/user-attachments/files/17669684/RPCS3.log.gz)
[TTY.log](https://github.com/user-attachments/files/17669685/TTY.log)

Please check it out

**Comment by lastavenger2004** [comment]
The only solution I found is to set the resolution scale to 300.

If some folks don't want to use Disable In-built MLAA patch or Strict Rendering Mode setting, then apply Relaxed ZCULL Accuracy and Allow Host GPU Labels (Experimental).

There. I fixed my own problem.

Please state that with some folks have the same problem as mine, set the resolution scale to 300.

**Comment by AhayriSG** [comment]
Can confirm. I'm on a Pascal GPU, and the default [ZCULL Accuracy: Precise](https://wiki.rpcs3.net/index.php?title=Help:Default_Settings#GPU_configuration) setting causes the same graphical issues for me.

Switching ZCULL Accuracy to "Relaxed" fixes almost all of them. I still run into minor glitches occasionally. Also, when booting Uncharted 2 (PSN digital version), there's about a 10% chance it launches with the heavy graphical corruption shown in the main post (with terrible FPS), though the other 90% of the time it boots perfectly fine with "Relaxed".

For comparison, setting it to Strict makes the graphical bugs happen 100% of the time, even though performance stays normal.
