### ISSUE TITLE
Tomb Raider [BLUS31036] Hair Glitch

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#16298]
### Quick summary

This bug also occurs to stone and trees, but I found out after recording.

https://github.com/user-attachments/assets/7fd64112-6bb6-4a8e-a91e-8e505ff4effd

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17653267/RPCS3.log.gz)

**Comment by lastavenger2004** [comment]
I've seen a forum which indicates that opening and closing the game will fix this issue. Unfortunately, I deleted my Tomb Raider ISO. After I redownloaded and tested it again, I will come back.
