### ISSUE TITLE
Mortal Kombat Komplete Edition [BLUS30902] Green Blood

### ISSUE THREAD

**Issue by lastavenger2004** [RPCS3/rpcs3#16297]
### Quick summary

The game works great. It's just green blood.

![BLUS30902_screenshot_2024_11_06_23_38_44](https://github.com/user-attachments/assets/81576289-d3bb-46cc-9632-4d52254ce3d7)

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17652499/RPCS3.log.gz)

**Comment by lastavenger2004** [comment]
Maybe I'm mistaken and by happens, this version of the game happens to have green blood. Either way, please help. I didn't find any relative settings about changing the color of blood.

**Comment by Megamouse** [comment]
I'm pretty sure the blood is just green in. Certain regions.
Anyway. This is a duplicate

**Comment by lastavenger2004** [comment]
I tried with a different region, the problem still persists

![BLES01508_screenshot_2024_11_09_19_30_46](https://github.com/user-attachments/assets/352a82c6-3c7b-4199-84e8-6de9e4eb268e)


I also tried "create savestate", rebooted the game with savestate and faced this bug

![BLES01508_screenshot_2024_11_09_19_29_06](https://github.com/user-attachments/assets/a95f8920-fe8f-44a4-a9dd-90f7b06fa13a)


Here. The new logs (latest version v0.0.34-17098-2262ac16)
[RPCS3.log.gz](https://github.com/user-attachments/files/17688550/RPCS3.log.gz)
[TTY.log](https://github.com/user-attachments/files/17688552/TTY.log)


I've also tested it with version v0.0.26-14704-2f7a2d51 and v0.0.27-14790-2de4c03f. The results were similar. the blood is not green, but there are green particles flickering around the blood area.

The video capture is for v0.0.26-14704-2f7a2d51. As you can see, the blood is not green, but it's glitching into green blood. 

https://github.com/user-attachments/assets/aa89ec4b-028d-4c94-aff1-2b048a853919


Log for v0.0.26-14704-2f7a2d51 (more reliable log since the build got more tested on)
[RPCS3.log.gz](https://github.com/user-attachments/files/17688645/RPCS3.log.gz)

Log for v0.0.27-14790-2de4c03f
[RPCS3.log.gz](https://github.com/user-attachments/files/17688646/RPCS3.log.gz)


Please help. I've checked YouTube videos testing the game, and the blood was almost fine in those videos.

**Comment by VincentJones82** [comment]
https://github.com/RPCS3/rpcs3/issues/15571
