### ISSUE TITLE
[Regression] Toy Story 3 [BLUS30480] Used to work without Strict Rendering Mode

### ISSUE THREAD

**Issue by lastavenger2004** [RPCS3/rpcs3#16302]
### Quick summary

The first RPCS3 build where the game was playable is v0.0.5-7195-23b52e1b and It had no issue. There was no need of Strict Rendering Mode because there was no graphics flickering.

The version where the flickering graphics started was v0.0.8-9665-171e6c6e

Things started from v0.0.6-8536-b0d0f51d, but since v0.0.8-9665-171e6c6e, it got worsened

### Build with regression

v0.0.8-9665-171e6c6e

### Attach two log files

build that works (v0.0.5-7195-23b52e1b)
[RPCS3.log.gz](https://github.com/user-attachments/files/17681740/RPCS3.log.gz)

build with regression (v0.0.8-9665-171e6c6e)
[RPCS3.log.gz](https://github.com/user-attachments/files/17681737/RPCS3.log.gz)

### Attach capture files for visual issues

build that works (v0.0.5-7195-23b52e1b)
![Screenshot 2024-11-08 202127](https://github.com/user-attachments/assets/65ef57f6-54cb-4791-8750-af7b23bba823)

build with regression (v0.0.8-9665-171e6c6e)
![screenshot-2024_11_08_20_23_03](https://github.com/user-attachments/assets/4e9ec059-928c-40ca-a432-a4c416bb3fe8)

**Comment by mysteria25** [comment]
#7302

**Comment by lastavenger2004** [comment]
> This is an intentional change. I'm not sure what the ticket is about. Doing a full GPU sync on every texture barrier is extremely slow on most AAA games.

I didn't know it was intentional. I just read what @mysteria25 has sent. If there's no other choice, then there's no point in me pointing anything else out.
