### ISSUE TITLE
When I click on "Config" it just “ No response

### ISSUE THREAD

**Issue by onestep1987** [RPCS3/rpcs3#16309]
### Quick summary

Everything is the newest version,When I click on "Config", it just  “ No response”,the only thing i can do is kill it in taskmanger.

### Attach a log file

![image](https://github.com/user-attachments/assets/743aafb1-f74c-428e-b503-11892e6238c4)

**Comment by onestep1987** [comment]
PS：I run it on windows 11 24H2 with amd 7945HX，everything is the newest version.

**Comment by Megamouse** [comment]
Not a valid ticket
