### ISSUE TITLE
Sleeping Dogs™ [BLUS30927] Game crashes

### ISSUE THREAD

**Issue by lastavenger2004** [RPCS3/rpcs3#16307]
### Quick summary

Game crashes on this specific point. Couldn't even create RSX capture

![Screenshot 2024-11-10 000755](https://github.com/user-attachments/assets/05753b5a-93de-46da-ac4d-116b3dec6110)

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17689293/RPCS3.log.gz)

**Comment by Shoegzer** [comment]
This title freezes for me too.  I was able to get through the opening sequence thanks to your suggestions, however it still freezes at random intervals ingame, usually between 10-30 minutes of play.  What is your wake-up delay set to?  I've tried between 2000-5000 but nothing really seems to work.  If you encounter freezing ingame as well, then you should probably reopen this issue.

Specs:
* OS: Linux Mint 22 / kernel 6.8
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070 / driver 550.120
