### ISSUE TITLE
[Regression] RPCS3-17099 Significant Performance Impact

### ISSUE THREAD

**Issue by alexconsole04** [RPCS3/rpcs3#16310]
### Quick summary

Latest RPCS3 update causes a mass dip in performance for various titles, rendering games unplayable.

### Details

17099 causes games to not only load very slow, but framerates to also plumet, as well as broken audio. This was not an issue on 17098. 
Tested with Ratchet and Clank Future - A Crack in Time [NPUA80966].
Video for reference: https://youtu.be/QkJn2PxkN0A

### Build with regression

v0.0.34-17099-2b0f786b Alpha

### Attach two log files

Log with Regression: [RPCS3.log.gz](https://github.com/user-attachments/files/17708469/RPCS3.log.gz)

Log on Previous Working Build: [RPCS3.log.gz](https://github.com/user-attachments/files/17708444/RPCS3.log.gz)

### System configuration

Intel Core i5-11400F | 12 Threads | 15.86 GiB RAM | AVX-512+ | FMA3
GPU: NVIDIA GeForce RTX 2060 (560.94)

### Other details

Various other games are affected such as Skate 3 and LittleBigPlanet.

**Comment by TheGhostOfInky** [comment]
Same thing is happening here, tested 17099 in a Ryzen 5 5500U running Fedora Linux 41 and an i3-13100 running Windows 11 23H2, in both the Simpsons game went from playable at 1080p with the 60 fps patch to a state so studdery the EA logo hangs for a solid minute and the audio is choppy even at the lowest settings with no 60fps patch, easily the worst regression I've seen in RPCS3.

**Comment by Saccboi** [comment]
this update was a mistake

**Comment by elad335** [comment]
Test #16312 please

**Comment by elad335** [comment]
Test the latest build

**Comment by TheGhostOfInky** [comment]
Tested 17100, it's marginally better than 17099 but still choppy and slow compared to 17098 and keeps pegging the CPU to 100%.

**Comment by soiloui** [comment]
Same here after last update. Ratchet and clank tod became unplayable (15 frames per minute + broken audio)

**Comment by Asinin3** [comment]
Test on latest again, 17101

**Comment by snnaakee** [comment]
> Test on latest again, 17101

Just tried again, 1 frame per second in socom's main menu

**Comment by elad335** [comment]
Fixed by #16315
