### ISSUE TITLE
[Issue] The application “RPCS3.app” can’t be opened

### ISSUE THREAD

**Issue by dralism** [RPCS3/rpcs3#16329]
### Quick summary

RPCS3 0.0.34-17118 on Macbook Air M1 won't work at all as if it is not native to ARM 

### Details

Hi 
Thanks for your effort of development 
RPCS3 0.0.34-17118 on Macbook Air M1 won't work at all as if it is not native to ARM 
The application “RPCS3.app” can’t be opened
![image](https://github.com/user-attachments/assets/3353649e-bb0e-45fe-940f-4376ccccfda7)

Please note that all .dmg version work fine ... but non of the .7z version works since 0.0.30 across to current version nothing work for me .... any idea please 

Regards 

### Attach a log file

NA

### System configuration

Macbook Air 2020 M1 
RAM 8GB
SSD 512 GB

**Comment by dralism** [comment]
Thanks a lot .... unfortunately same issue "The application “RPCS3.app” can’t be opened"

**Comment by dralism** [comment]
Thanks Shinra actually I am aware of this .... them problem is macOS can even excute the app as if yo are trying an x86_64 app on arm64 system .... or trying an arm64 or x86_64 system 
I am pretty sure that I am using the latest 0.0.34 build of RPCS3 for arm64 and my system is arm64 given Apple M1 chip ... and yes I am on Sequoia
Regards

**Comment by shinra-electric** [comment]
> Thanks Shinra actually I am aware of this .... the problem is macOS can not even execute the app as if you are trying an x86_64 app on an arm64 system .... or trying an arm64 or x86_64 system I am pretty sure that I am using the latest 0.0.34 build of RPCS3 for arm64 and my system is arm64 given Apple M1 chip ... and yes I am on Sequoia Regards

As schm1dtmac mentioned, make sure you are getting the Arm build, which hasn't been officially announced yet. 
The official builds from the website are still x86. 

The Arm builds can be downloaded from [here](https://github.com/RPCS3/rpcs3-binaries-mac-arm64).
These build works fine for me.

**Comment by dralism** [comment]
Thanks 
Yep I am using the exact same built that  schm1dtmac mentioned
https://github.com/RPCS3/rpcs3-binaries-mac-arm64/releases/tag/build-cc86e01df98ca84276f6cec97e1fb37fda1eb568

Still no luck I am greated by double error messages, see below 

![image](https://github.com/user-attachments/assets/7303f0ab-252a-4069-a072-109a98639e17)

Regards

**Comment by shinra-electric** [comment]
Hmm, that's bizarre. Do you get the same thing when trying the x86 build?

**Comment by shinra-electric** [comment]
Ah! I think I was able to replicate something similar...
<img width="370" alt="Screenshot 2024-11-18 at 23 37 05" src="https://github.com/user-attachments/assets/08d38517-746c-412d-b089-1f20158f2dc1">

I normally use [The Unarchiver](https://theunarchiver.com) instead of the macOS built-in Archive Utility.

I just tried decompressing the 7z file with Archive Utility, and it didn't work.

Can you give The Unarchiver a go?

**Comment by dralism** [comment]
Yep really strange .... yes I got the same with the x86 builds since the 0.0.30 when moved to .7z package 
Older builds like 0.0.29 as dmg package works fine 
Thanks

**Comment by dralism** [comment]
Thanks a lot .... it works like a charm .... I was using WinZIP seems not very accurate to unzip .7z ... I followed your advice and it works..... many thanks indeed
