### ISSUE TITLE
RPCS3 crashes when any game is launched on Wayland

### ISSUE THREAD

**Issue by bravemenrun** [RPCS3/rpcs3#16336]
### Quick summary

RPCS3 will crash when launching any game. 

### Details

This issue occurs with both the appimage and the rpcs3-git package in the AUR.
```
rpcs3
No AppImage path found, checking for executable
Found exec path: /usr/bin/rpcs3
Debugger: 0
Failed to set RLIMIT_MEMLOCK size to 2 GiB. Try to update your system configuration.
RPCS3: Vulkan Device Enumeration Thread: RSX: Found Vulkan-compatible GPU: 'AMD Radeon RX 6700 XT' running on driver 2.0.321
RPCS3: SYS: Firmware version: 4.90
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
RPCS3: RSX: Found Vulkan-compatible GPU: 'AMD Radeon RX 6700 XT' running on driver 2.0.321
wl_drm#68: error 0: wl_drm.create_prime_buffer is not implemented
The Wayland connection experienced a fatal error: Protokol-eraro
```

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17853718/RPCS3.log)

### System configuration

OS: EndeavourOS x86_64
Kernel: Linux 6.11.9-zen
CPU: AMD Ryzen 7 5800X
GPU: AMD Radeon RX 6700 XT
GPU driver version: 2.0.321

**Comment by ItsLaguna** [comment]
Works fine on my end using Bazzite, latest master (0.0.34-17138)
Not sure from where is your build, but it says ``local_build", did you build it yourself?

**Comment by kd-11** [comment]
You can clearly see the error from the wayland server says it crashed due to unimplemented features. Install a more complete implementation or just use X11:
```
QT_QPA_PLATFORM=xcb ./rpcs3
```

**Comment by bravemenrun** [comment]
Upon further troubleshooting and research, this does not appear to be an issue with RPCS3 at least that I can see. It looks to be an issue with amdvlk. If I'm not mistaken, [this](https://github.com/GPUOpen-Drivers/AMDVLK/issues/351) issue seems identical to mine. I'll close this issue.
