### ISSUE TITLE
[Regression] Performance is worse 

### ISSUE THREAD

**Issue by Dino0005** [RPCS3/rpcs3#16339]
### Quick summary

On rpcs3-v0.0.34-17142 performance is worse on MAC with M3 Pro (CPU 12 core, CPU 18 Core, RAM 18 GB). 
Afterwards, out of curiosity, I also tried with v0.0.34-17141 and I have the same issues.
I reverted to the rpcs3-v0.0.34-17138 version which worked better, without this issue.

### Details

When loading a game everything is slower and heavier.

### Build with regression

v0.0.34-17142 

### Attach two log files

[RPCS3.log.gz](https://github.com/user-attachments/files/17876589/RPCS3.log.gz)

### System configuration

MacBook Pro, M3 Pro (CPU 12 core, CPU 18 Core, RAM 18 GB).

**Comment by AniLeo** [comment]
Invalid regression report, blames an incorrect build.

> Build with regression v0.0.34-17142 

>  I also tried with v0.0.34-17141 and I have the same issues

No second log file added as well, no screenshots with performance overlay showing what is the performance drop, no steps to reproduce, no list of tested pool of games and what is the performance difference between them.

Closing as Invalid.
