### ISSUE TITLE
Texture dumping

### ISSUE THREAD

**Issue by Bryciekai** [RPCS3/rpcs3#1633]
A texture dumping option should be available in the video settings of the emulator

**Comment by tambry** [comment]
And why you'd need that? The emulator is in a barely usable state anyways.

**Comment by AniLeo** [comment]
Well, there's RSX debugger but it doesn't dump the results anywhere

**Comment by paulsapps** [comment]
@Bryciekai why not just send a PR to add it to RSX debugger
