### ISSUE TITLE
[Regression] Virtua Fighter 5 FS rays of light rendered as big red boxes

### ISSUE THREAD

**Issue by osanmial** [RPCS3/rpcs3#16345]
### Quick summary

Visual bug that produces big red transparent boxes in some stages.

### Details

Since version 0.0.33-17011-48322673 these big red boxes appear in some stages. They seem to happen on daytime stages so they might be incorrectly rendered beams of lights or something. The brighter the stage, more opaque they seem to be. 

Between versions 16999 and 17011 exists also 17006 and 17010, but builds for those were not available, so I couldn't test them. 

![Screenshot_20241123_203319](https://github.com/user-attachments/assets/798ee52f-ed88-44d8-a442-905cf906b781)
![Screenshot_20241123_203624](https://github.com/user-attachments/assets/386118cb-5374-4d6a-997f-ed6b1e46dd17)

### Build with regression

v0.0.33-17011-48322673

### Attach two log files

[RPCS3-16999.log](https://github.com/user-attachments/files/17882272/RPCS3-16999.log)
[RPCS3-17011.log](https://github.com/user-attachments/files/17882274/RPCS3-17011.log)

### Attach capture files for visual issues

[NPUB30625_20241123210916_capture.rrc.gz](https://github.com/user-attachments/files/17882269/NPUB30625_20241123210916_capture.rrc.gz)

### System configuration

CPU: AMD Ryzen 9 7900X
GPU: AMD Radeon RX 6800
RAM: 30.48 GiB
Operating system: 6.6.54-2-MANJARO,

### Other details

The issue has been observed with at least one other user.

**Comment by digant73** [comment]
between 0.0.33-16999 (working) and 0.0.33-17011 (not working) the only PR that made changes on graphics is PR #16169

**Comment by scgehin** [comment]
This problem has also been reported for following GPUs:
AMD Radeon RX 6600
AMD Radeon RX 6650 XT
AMD Radeon RX 6800 XT

**Comment by kuroifgc** [comment]
Also on Steam Deck

**Comment by kuroifgc** [comment]
@kd-11 will you please tell us if you fix it?

**Comment by kd-11** [comment]
How does it look with OpenGL?

**Comment by kuroifgc** [comment]
> How does it look with OpenGL?

on steam deck i'm on rpcs3 latest current version and setting the gpu to openGL won't even run the fight. it runs the game but when i select chars/stage it will stuck on loading screen

**Comment by osanmial** [comment]
> How does it look with OpenGL?

Imanaged to load to the training mode on OpenGL, but the stage is darker than it should be and most grabs crash the game.

**Comment by crashGG** [comment]
This problem also been reported for my GPU:
AMD 780m (rdna3)

**Comment by crashGG** [comment]
another stage:
![NPUB30625_screenshot_2024_12_18_09_55_16](https://github.com/user-attachments/assets/ed0f2098-d3fd-42ac-94ec-dc40f82ede68)

**Comment by kd-11** [comment]
AMD follows OpenGL swizzle convention when sampling borders. NVIDIA just ignores swizzles for border sampling.
I don't think either one is right, but I'll just add a workaround to normalize based on real-world testing. Does anyone have an arc card we can use to test this? I'll assume it behaves like NVIDIA in this one and move on if not.

**Comment by kd-11** [comment]
Looks like we can define the rules using an extension: https://registry.khronos.org/vulkan/specs/latest/man/html/VK_EXT_border_color_swizzle.html
