### ISSUE TITLE
[Regression] Firmware installer

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#16356]
### Quick summary

Installing firmware is giving a new fatal error

### Details

I am receiving the following error at the end of installing firmware after clicking the ok button on the installation dialog at the end of compiling sys [] cache
·F 0:01:06.560957 {PPU Exec Worker} SIG: Thread terminated due to fatal error: Verification failed (object: 0x0)
(in file D:\a\1\s\rpcs3\Emu\Cell\PPUModule.cpp:1101[:3], in function void __cdecl init_ppu_functions(struct utils::serial *,bool))

### Build with regression

rpcs3-v0.0.34-17161-9a2bcd25

### Attach two log files

[rpcs3-v0.0.34-17161-9a2bcd25_win64.log](https://github.com/user-attachments/files/17938438/RPCS3.log)
[rpcs3-v0.0.34-17155-fce07bbe_win64.log](https://github.com/user-attachments/files/17938456/RPCS3.log)

### Attach capture files for visual issues

N/A

### System configuration

win 11
gtx 1660s
ryzen 7 7700x

### Other details

I tested hotfix pr to no current solution
[RPCS3.log](https://github.com/user-attachments/files/17938510/RPCS3.log)
·F 0:00:47.749803 {PPU Exec Worker} SIG: Thread terminated due to fatal error: Verification failed (object: 0x0)
(in file D:\a\1\s\rpcs3\Emu\Cell\PPUModule.cpp:1101[:3], in function void __cdecl init_ppu_functions(struct utils::serial *,bool))

**Comment by elad335** [comment]
Should be fixed by #16355

**Comment by Darkhost1999** [comment]
> Should be fixed by #16355 

Just got a successful compilation and indeed, it is fixed.
I see by removing the ensure right?

**Comment by elad335** [comment]
Yes, the intention was good, maybe it should get refactored
