### ISSUE TITLE
Enter a title hereDoes anyone know how to fix this?

### ISSUE THREAD

**Issue by LeeYcb04** [RPCS3/rpcs3#16358]
### Quick summary

i was working fine beore and works standalone but now retrobat throws up this error 

### Details

does anyone know how to fix this error that just came up today

### Attach a log file

i dont have one 

### Attach capture files for visual issues

![image](https://github.com/user-attachments/assets/78e7130b-681b-45f1-9ab1-376288bf1b95)

**Comment by AniLeo** [comment]
No support with third party frontends, not that this is a valid ticket either way as there would be no info to go off from
