### ISSUE TITLE
Non-root memory mapping support

### ISSUE THREAD

**Issue by daviDarthemis** [RPCS3/rpcs3#16364]
### Quick summary

Alternative for reading cpu information

### Details

In Linux a lot of CPU information is in /proc some of it is called by rpcs3 as /proc/stat /proc/cpuinfo and other in vm for memory mapping 

This works however on Linux where we do not have access to these files the emulation breaks. 

Benefits of implementing this, rpcs3 emulation in Android proot environment, when doing a debug I noticed that rpcs3 calls 3 files in /proc and asks for access to one in / I made some changes to the code to It works around this condition and the result was that the games opened normally after one or two seconds they crashed. Probably because I'm targeting sta
![Screenshot_2024-11-30-14-42-21-926_com termux x11](https://github.com/user-attachments/assets/22a122a7-92c4-4781-ae4a-e6781890cef3)
![Screenshot_2024-11-30-14-10-33-911_com termux x11](https://github.com/user-attachments/assets/ae5e0dc0-a9e6-4ef9-bc9c-8e6781726554)
![Screenshot_2024-11-30-14-50-42-611_com termux x11](https://github.com/user-attachments/assets/b4a9df2f-0a3d-4401-9aa0-367a21e2fec8)
tic files

**Comment by daviDarthemis** [comment]
Note: when you give access to the proc with root, it works normally, but it cannot allocate the 5 gigabytes of memory in RAM, generating a warning, but it works. On my 8gen3 I got great results.

**Comment by RipleyTom** [comment]
You seem to be describing an issue with your emulation layer, not an issue with rpcs3. We have no interest in supporting android in any way.
