### ISSUE TITLE
[Feature request] DLL injection into PS3 games

### ISSUE THREAD

**Issue by mrmaller1905** [RPCS3/rpcs3#16369]
### Quick summary

Can you add support for DLL injection into PS3 games instead of writing patches in text format?

### Details

DLL injection allows it to log filenames and hashes from PS3 game archives (e.g. Far Cry 2)

**Comment by RipleyTom** [comment]
Request makes no sense. There is some support for external executable interaction through IPC server if needed.

**Comment by elad335** [comment]
We can.
