### ISSUE TITLE
[Regression] Qt 6.8.0: Crash on startup on Win10

### ISSUE THREAD

**Issue by kloon15** [RPCS3/rpcs3#16375]
### Quick summary

Won't start at all.

### Details

Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000000 at 00007ffa9a74d0f6.
Thread: Main Thread.
Instruction address: 00007ffa9a74d0f6.
Function address: 00007ffa9a74c990 (base+0x5c990).
Module name: 'qwindows.dll'.
Module base: 00007ffa9a6f0000.
RPCS3 image base: 0000000000010000.

### Build with regression

v0.0.34-17141

### Attach two log files

[RPCS3-crash.txt](https://github.com/user-attachments/files/18037713/RPCS3-crash.txt)
[RPCS3-working.txt](https://github.com/user-attachments/files/18037725/RPCS3-working.txt)

**Comment by Mrlinkwii** [comment]
Qt 6.8 should work on win 10 , are you using a custom version of win 10? and have you made sure to update win10 to the latest available update ?

**Comment by kloon15** [comment]
> Qt 6.8 should work on win 10 , are you using a custom version of win 10? and have you made sure to update win10 to the latest available update ?

Yea well it doesnt and its latest official stable build.

**Comment by Megamouse** [comment]
Qt 6.8.0 was built with VS 2022. Maybe that's the issue ?

**Comment by kloon15** [comment]
I have all the vcredists installed and up to date:
```
PS C:\Users\Kloon> winget list | Select-String -Pattern "vcredist"

Microsoft Visual C++ 2010  x64 RedistributableΓÇª Microsoft.VCRedist.2010.x64                      10.0.40219     winge
t
Microsoft Visual C++ 2008 Redistributable - x6ΓÇª Microsoft.VCRedist.2008.x64                      9.0.30729.6161 winge
t
Microsoft Visual C++ 2013 Redistributable (x64ΓÇª Microsoft.VCRedist.2013.x64                      12.0.40664.0   winge
t
Microsoft Visual C++ 2012 Redistributable (x86ΓÇª Microsoft.VCRedist.2012.x86                      11.0.61030.0   winge
t
Microsoft Visual C++ 2005 Redistributable       Microsoft.VCRedist.2005.x86                      8.0.61001      winget
Microsoft Visual C++ 2015-2022 RedistributableΓÇª Microsoft.VCRedist.2015+.x64                     14.42.34433.0  winge
t
Microsoft Visual C++ 2008 Redistributable - x8ΓÇª Microsoft.VCRedist.2008.x86                      9.0.30729.6161 winge
t
Microsoft Visual C++ 2008 Redistributable - x8ΓÇª Microsoft.VCRedist.2008.x86                      9.0.30729.6161 winge
t
Microsoft Visual C++ 2013 Redistributable (x86ΓÇª Microsoft.VCRedist.2013.x86                      12.0.40664.0   winge
t
Microsoft Visual C++ 2010  x86 RedistributableΓÇª Microsoft.VCRedist.2010.x86                      10.0.40219     winge
t
Microsoft Visual C++ 2012 Redistributable (x64ΓÇª Microsoft.VCRedist.2012.x64                      11.0.61030.0   winge
t
Microsoft Visual C++ 2015-2022 RedistributableΓÇª Microsoft.VCRedist.2015+.x86                     14.42.34433.0  winge
t
```

**Comment by kloon15** [comment]
Same thing w 6.8.1. Am i the only one experiencing this issue?

**Comment by kloon15** [comment]
I'll go ahead and close this, its def an issue with Qt, i opened https://bugreports.qt.io/browse/QTBUG-132470
