### ISSUE TITLE
Add rpcs3 to android

### ISSUE THREAD

**Issue by Coryxkenshin-pixel** [RPCS3/rpcs3#16389]
### Quick summary

I would like that rpcs3 be on android

### Details

I dont think that it would affect it and I dont think my feature is not to important but I think that the people that have only a android and not a pc it would make it more easier there is other projects that do this like pojavlouncher 
![Screenshot_20241209_202921_Google Play Store](https://github.com/user-attachments/assets/7cdf98b3-add0-4b4b-aaaf-a9883b0242ea)
also this feature is not a thing that a game needs

**Comment by Coryxkenshin-pixel** [comment]
I would just like rpcs3

**Comment by vicegold** [comment]
From the latest blog post

> For these reasons, we are disallowing Android and iOS discussion in our communities. We have no intention of porting RPCS3 to these platforms at this time, so no discussion on these topics is needed. Unfortunately, this blanket decision is ultimately needed due to the high toxicity of several individuals in the Android community, who refuse to take no for an answer, some of which have already been banned from our communities.

https://rpcs3.net/blog/2024/12/09/introducing-rpcs3-for-arm64/

**Comment by klaxons1** [comment]
If the devs refer to the aethersx2 case or due toxic android users, why they cant just ban/ignore them? Yeah, the most of android community are children, but there are also decent people. Also, it could increase the amount of donuts

**Comment by AniLeo** [comment]
Closing spam issue, already answered many times.
