### ISSUE TITLE
SPU Memory violation [ARM64]

### ISSUE THREAD

**Issue by daviDarthemis** [RPCS3/rpcs3#16388]
### Quick summary

game THE LAST OF US 

SPU: llvm

Aarch64inux gnu Ubuntu 

RPCS3: SPU[0x4000100] Thread (highCellSpursKernel4) [0x049bc]: VM: [SPU[0x4000100] highCellSpursKernel4] Access violation reading location 0x0 (unmapped memory)

### Details

Crash loading shader after intro

### Attach a log file

.

### Attach capture files for visual issues

.

### System configuration

.

### Other details

.

**Comment by Jorde5212** [comment]
I believe I'm having a similar crash with the Last of Us. On Windows 10.
This is the exact line with the error:
F {PPU[0x1000000] Thread (main_thread) [0x00a55684]} VM: Access violation reading location 0x0 (unmapped memory)
