### ISSUE TITLE
Linux-arm64: `Illegal instruction (core dumped)` error when trying to launch appimage

### ISSUE THREAD

**Issue by VenomousSteam81** [RPCS3/rpcs3#16387]
### Quick summary

When I run `./rpcs3-v0.0.34-17173-68b7e597_linux_aarch64.AppImage`, I get `Illegal instruction (core dumped)`.

### Attach a log file

Illegal instruction (core dumped)

### System configuration

Debian in crostini (ChromeOS linux subsystem)
CPU: Mediatek MT8173
GPU: PowerVR Rogue GX6250
GPU driver is using Mesa

**Comment by AniLeo** [comment]
Below minimum requirements. You need at least ARMv8.2-a.

**Comment by VenomousSteam81** [comment]
Dang. Ok, ty!
