### ISSUE TITLE
[Feature request] Load shaders when first needed, not load thousands on every game boot

### ISSUE THREAD

**Issue by fireYtail** [RPCS3/rpcs3#16398]
### Quick summary

Much like the LLVM recompilers (although they don't suffer as much from this issue) can load their modules whenever they're needed, implement the same but with shaders, rather than being load at all once before every boot. Pre-loading 30,000 or more shaders every single time is such a huge (several minutes) wait. Having to wait several minutes is greatly discouraging to the user. It would be much better to load the shaders as needed. Using the shader interpreter or removing the entire shader cache before boot aren't realistic alternative options.

**Comment by Megamouse** [comment]
![image](https://github.com/user-attachments/assets/12a2bc7f-dcb4-4966-8dd9-901eb760b9ca)
