### ISSUE TITLE
![image](https://github.com/user-attachments/assets/12a2bc7f-dcb4-4966-8dd9-901eb760b9ca)

### ISSUE THREAD

**Issue by fireYtail** [RPCS3/rpcs3#16399]
![image](https://github.com/user-attachments/assets/12a2bc7f-dcb4-4966-8dd9-901eb760b9ca)

_Originally posted by @Megamouse in https://github.com/RPCS3/rpcs3/issues/16398#issuecomment-2540916652_
            
No, just telling me to not use the shader cache at all (be deleting it or disabling it) isn't realistic, as it has to recompile every shader again, making for stuttery gameplay and popping-in graphics. Also, closing my issue without giving me a chance to say anything is really disrespectful. But you cannot have it loading in the background, that's such an impossible feature to add. Just close me with an unrealistic solution... Your loss

**Comment by AniLeo** [comment]
You do not understand how shader recompilation works. What you want is impossible. Stop spamming our tracker with useless tickets.
