### ISSUE TITLE
[Regression] New builds of RPCS3 fail to launch on Windows 10

### ISSUE THREAD

**Issue by Rhaston** [RPCS3/rpcs3#16396]
### Quick summary

RPCS3 has been working on my system flawlessly for a very long time but starting with build v0.0.34-17118-4df58494 it no longer launches at all, instead I get a system error "The application was unable to start correctly (0xc0000142)". I tried more recent builds that were released since but the issue persists. This is a Windows 10 setup with Nvidia GPU and Intel CPU. 

### Details

![explorer_LhRtPOiwYd](https://github.com/user-attachments/assets/c997d54a-234e-4866-bb19-f55bf4f22a7e)
"The application was unable to start correctly (0xc0000142)"

Rolling back to any build before this release makes everything work again.

### Build with regression

v0.0.34-17118-4df58494

### Attach two log files

No log files available for this error (RPCS3 fails to launch).

### System configuration

Windows 10 with latest updates, GTX 970m, i7-4720HQ

**Comment by FlexBy420** [comment]
Reinstall windows redistrutable

**Comment by Rhaston** [comment]
> Reinstall windows redistributable, listed on quickstart guide.

This solved the issue, thank you!
