### ISSUE TITLE
[Feature request] Add setting to limit maximum size of RPCS3.log and TTY.log (no automatic trim or delete, really?)

### ISSUE THREAD

**Issue by fireYtail** [RPCS3/rpcs3#16397]
### Quick summary

Add a simple setting within the emulator to set a maximum size for the log files, instead of having them grow endlessly wasting many GB from storage and forcing users to stop emulation, then manually find/browse and delete the files.

### Details

**What part of RPCS3 would be affected by your feature? (Gameplay, Debugging, UI, Patches, Installation, CI etc.)**
None, it's not that RPCS3 is affected directly by this, rather, that RPCS3 is wasting insane amounts of storage for no good reason.

**Why your feature is important to RPCS3.**
Because storage is already likely to be filled with PS3 games and their respective RPCS3 caches to begin with. And because a rookie programmer can do better than this. There is no benefit to keeping it as it is now. It's inefficient for no reason.

**If the feature is implemented in other projects, attach screenshots.**
[Take screenshots of any random software that keeps logs in plain text and never ever flushes them, aside from RPCS3 and security software, paste the screenshots here. Good luck.]

**If this feature is something that a game is trying to use, upload a log file for it.**
I'm not uploading several GBs, thank you. Not that you need them anyway.

**RPCS3's Log file will be RPCS3.log.gz (sometimes shows as RPCS3.log with zip icon) or RPCS3.log (sometimes shows as RPCS3 wtih notepad icon). On Windows it will be in the RPCS3 directory near the executable**
You don't say!? Thanks for pointing out where the huge trash can is. Time to fully exit RPCS3, browse there and empty it myself. Same as the previous 50+ times before I opened this issue.

**Comment by Megamouse** [comment]
1. You can just disable logging in the settings.
2. Limiting the log size renders the log useless for developers

**Comment by Megamouse** [comment]
Very funny:
![image](https://github.com/user-attachments/assets/e7542e88-a752-458d-9a8e-a12765a48c1f)
