### ISSUE TITLE
Tekken 6 (BLES00635) doesn't get past initial auto-save warning

### ISSUE THREAD

**Issue by fireYtail** [RPCS3/rpcs3#16400]
### Quick summary

Tekken 6 (BLES00635) doesn't get past initial auto-save warning -- not frozen, but not doing anything, basically dead.

### Details

From the log it would seem as if the compatibility problem has to do with how the game is trying to read its own files. It would seem as if game files are unencrypted somewhere else first, but this unencryption fails, thus making the game unable to continue at all. That's my best guess.

### Attach a log file

Recompiler-LLVM / Recompiler-LLVM
[RPCS3.log](https://github.com/user-attachments/files/18124142/RPCS3.log)

Interpreter-static / Interpreter-static
[RPCS3.log](https://github.com/user-attachments/files/18124549/RPCS3.log)

### Attach capture files for visual issues

Black screen after auto save warning.

### System configuration

The log already includes it very well explained by design so no need to repeat it.

### Other details

This happens on both version 1.00 and version 1.03 of Tekken 6. It seems to be the exact same for both, although log is from 1.00. I'm running the game first time or "clean" (no save data etc, since I can't get past here)

The game is listed as "playable" and [the wiki doesn't list any known issues](https://wiki.rpcs3.net/index.php?title=Tekken_6), but my computer says otherwise.

**Comment by ddmdareal** [comment]
Cannot reproduce, game works fine on my end on latest build. I will note you have wild setting changes, and possibly bad game files.
![Screenshot_20241213_120418](https://github.com/user-attachments
[RPCS3.log](https://github.com/user-attachments/files/18125463/RPCS3.log)
/assets/9535dd12-dfa3-4af7-8a15-43463d25e134)
