### ISSUE TITLE
[SCEEXE000] Camera working and then automatically disconnects "Taiko no Tatsujin"

### ISSUE THREAD

**Issue by Getze56901** [RPCS3/rpcs3#16404]
### Quick summary

When setting up a camera for "Taiko no Tatsujin" it works, however after finishing the attract screen or exiting the Camera Test, RPCS3 automatically disconnects the camera and it will not work again until you reset your game.

### Details

![Test_Camera_Menu](https://github.com/user-attachments/assets/2eca4e50-f300-4aba-82fe-304137ff2d4c)
https://file.garden/Z1zf2rN5fz08IlfK/Test_Camera_Menu.mp4
![Test_Camera_Attract](https://github.com/user-attachments/assets/faeecda1-bc38-41b4-824e-25b229370fd5)
https://file.garden/Z1zf2rN5fz08IlfK/Test_Camera_Attract.mp4

According to the log I read, it seems that the emulator cannot find the used camera again after attract mode or after exiting Camera Test and gives errors in the log (It was tested with 5 different cameras and drivers, all give the same error)

### Build with regression

v0.0.34-17184 (2024-12-13 23:01:18)

### Attach two log files

[RPCS3.log](https://github.com/user-attachments/files/18133888/RPCS3.log)

**Comment by Megamouse** [comment]
Please upload the complete log

**Comment by Getze56901** [comment]
> Please upload the complete log

[RPCS3.log.gz](https://github.com/user-attachments/files/18170270/RPCS3.log.gz)

**Comment by Megamouse** [comment]
#16420 adds some more logging. Can you please run it once it's built and upload a log with that?

**Comment by Megamouse** [comment]
I added a potential fix to that PR

**Comment by Getze56901** [comment]
> I added a potential fix to that PR

 I can't build rpcs3 at the moment, I don't have my main device to be able to do the build procedure, I can only limit myself to having binaries

**Comment by Megamouse** [comment]
You can just download it from the PR:
https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzEzMDY4L2FydGlmYWN0TmFtZS9SUENTMytmb3IrV2luZG93cw2/content?format=zip

**Comment by Getze56901** [comment]
> You can just download it from the PR: https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzEzMDY4L2FydGlmYWN0TmFtZS9SUENTMytmb3IrV2luZG93cw2/content?format=zip
[RPCS3.log.gz](https://github.com/user-attachments/files/18173408/RPCS3.log.gz)
The main problem has be resolved successfully, I haven't noticed any other errors for the moment.
