### ISSUE TITLE
Feature Request: Android version of RPCS3 Emulator

### ISSUE THREAD

**Issue by RedWilly** [RPCS3/rpcs3#16408]
### Quick summary

I’d love to see an Android version of RPCS3 so I can run PS3 games on my Odin 2 Pro. The device has enough power with its Snapdragon 8 Gen 2 and 12GB RAM to handle it, and an Android build would make it perfect for gaming on the go.

### Details

I’m using the Odin 2 Pro, and it’s a beast of a handheld with a Snapdragon 8 Gen 2 processor, 12GB RAM, and a 120Hz AMOLED display and a GPU of  Adreno 740. This thing runs Android 13, and with its power, I know it could easily handle something like RPCS3 if there was an Android version.  

Right now, it feels like a missed opportunity not having this emulator on devices like mine, especially with so many handhelds running Android getting more popular. An Android build of RPCS3 would be a game-changer for people like me who want to play PS3 games on the go without needing a PC.  

I’m not a developer( not with knowledge c++), but I know the device has the specs to make this work. If possible, I’d love to see support for Android so I can make the most out of my handheld. Thanks!

**Comment by FlexBy420** [comment]
Been already said multiple times that are no intentions of creating android/ios build.

**Comment by klaxons1** [comment]
Yeah, so the issue will be locked as a spam in a blink of an eye

**Comment by RedWilly** [comment]
Well that disappointing. Thanks for the feedback
