### ISSUE TITLE
Rpcs3 crashes when switching between list view and grid view

### ISSUE THREAD

**Issue by bigol83** [RPCS3/rpcs3#16427]
### Quick summary

As per title while switching between list and grid view the emulator crashes. To reproduce go to grid view then try to go back to list view, you can see the emulator crashes.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/18196837/RPCS3.log)

### Other details

RPCS3 Version: 0.0.34-17206-9d4ff13c Alpha | master

**Comment by digant73** [comment]
I also see that bug
