### ISSUE TITLE
[Feature request] Please add OpenGL support to make it possible to play RPCS3 on any GNU/Linux distro

### ISSUE THREAD

**Issue by davidhedlund** [RPCS3/rpcs3#16423]
### Quick summary

* `flatpak install --user net.rpcs3.RPCS3`
* Install the firmware
* Copy a game to ~/.var/app/net.rpcs3.RPCS3/config/rpcs3/games/
* Change Renderer from "Vulkan" to "OpenGL"

![image](https://github.com/user-attachments/assets/4d66f7c7-8fef-4da5-a070-e8fb13b5414b)

* Try to open the game in RPCS3.
* RPCS3 crashes in distros that do not support Vulkan. For example in [Trisquel](https://trisquel.info/) GNU/Linux

**Comment by Megamouse** [comment]
flatpak is not supported

**Comment by davidhedlund** [comment]
> flatpak is not supported

Merged to https://github.com/flathub/net.rpcs3.RPCS3/issues/1765
