### ISSUE TITLE
[Regression] ModNation Racers closing on loading screen

### ISSUE THREAD

**Issue by derole1** [RPCS3/rpcs3#16447]
### Quick summary

When loading ModNation Racers, the game crashes during initial loading, occasionally causing an RPCS3 error and crashing the emulator entirely.

### Details

Since version 0.0.34-17230, PR 16403, modnation racers now closes during the loading screen with no exception/error messages. The emulator menu continues running.

Works on 0.0.34-17229. In both cases it happens with default settings, and all patches disabled. Same error is present when "Write Colour Buffer" is enabled which is required to prevent graphical issues.

Please refer to below error, which only appears occasionally and when it does the entire emulator is crashed:
![image](https://github.com/user-attachments/assets/80c4334b-3243-4f17-a708-d8e7f4ec4d0c)

### Build with regression

0.0.34-17230

### Attach two log files

Broken build
[ModNation Racers [NPUA80535].log.gz](https://github.com/user-attachments/files/18223290/ModNation.Racers.NPUA80535.log.gz)

Working build
[ModNation Racers [NPUA80535].log.gz](https://github.com/user-attachments/files/18223298/ModNation.Racers.NPUA80535.log.gz)

### System configuration

Intel Core i7 7820X
Nvidia Geforece GTX 1080
Nvidia Game Ready Driver 555.99

**Comment by Darkhost1999** [comment]
[RPCS3.log](https://github.com/user-attachments/files/18223336/RPCS3.log)
Same error message with vsh and other titles still compiling a list. Although vsh is the universal method to replicate this issue with it appears to be libspurs.sprx

**Comment by Megamouse** [comment]
closing as fixed
