### ISSUE TITLE
[Feature request] "Skip this version" option when notified of update.

### ISSUE THREAD

**Issue by AnubyteCode** [RPCS3/rpcs3#16441]
### Quick summary

"New update! (nothing relevant to my system, security, or performance/stability)"
_Hmm, no thanks._
"New update! (same update)"
_Bruh._

### Details

Sometimes an update has nothing of value to an individual, not that they are moot but sometimes I don't need a GUI or language fix nor the ability to build correctly on Mac or ARM64 for example.

For these cases, a checkbox or button that lets you skip a given version would rock, as otherwise I have to deal with an update pop-up every time I reload the app (testing configs and resultant crashes/hangs, reading logs, etc).

_The ability to delay updates for a period of time would also be nice, as sometimes several builds happen in a day, but the single version skip is most important to me as I like to see what is changing. Also figure it's easier to code than something time based._

**Comment by FlexBy420** [comment]
![obraz](https://github.com/user-attachments/assets/0a55b66d-efea-4870-9fdb-4d3023ac6d40)

**Comment by Hamof1** [comment]
While that would work, it seems like they still want to be notified of new updates whenever they show up just wants the option to skip an update until a new one comes along if they're not interested.

**Comment by FlexBy420** [comment]
You already are notified if theres a new update 
![obraz](https://github.com/user-attachments/assets/90f7410a-b805-429c-b9d9-8587a5fa2c11)

**Comment by Hamof1** [comment]
I guess. Just doesn't seem like it'd be too much work to make pressing "no" cause it to not show the pop-up until a new version comes out.

**Comment by AnubyteCode** [comment]
Awesome. The little things in life, you know? Thanks much!
