### ISSUE TITLE
Folklore [BCUS98147] (Autocomplete motion control sequences patch) partially broken

### ISSUE THREAD

**Issue by Chaoswizard98** [RPCS3/rpcs3#16459]
### Quick summary

Upon entering the second realm, Warcadia, the Degasser does not get auto captured and the bar slowly fills beyond it's limit when using the "Autocomplete motion control sequences" patch. 

I do not currently own a controller, so I'm not sure if the patch is bugged or if the game itself is bugged.

![image](https://github.com/user-attachments/assets/27b5c700-a300-4185-9a1c-d0fad33883e4)
![image](https://github.com/user-attachments/assets/8e2bbb06-ad81-4fc8-a6b3-be358c8d31ad)

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/18247258/RPCS3.log.gz)

### System configuration

OS: Windows 11
Processor: 12th Gen Intel(R) Core(TM) i7-12700K   3.60 GHz
RAM: 64.0 GB
GPU: Nvidia GeForce RTX 3080 Ti

**Comment by FlexBy420** [comment]
Thats not RPCS3 issue, patches are made by community if theres something wrong with the patch, contact its creator.
