### ISSUE TITLE
Project Diva F 2nd hang black screen after logo intro

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1645]
you can see log and screenshot below
![image](https://cloud.githubusercontent.com/assets/11285640/14163581/04958a72-f721-11e5-9e90-27b2235ef8c9.png)

**Comment by tambry** [comment]
You have opened other issues in the past and didn't provide any necessary information. Same goes for this time. Closing until you can provide the necessary information.

**Comment by zminhquanz** [comment]
i used interpreter 2 , SPU Recompiler , Xaudio 2 , DirectX 12

**Comment by tambry** [comment]
http://www.emunewz.net/forum/showthread.php?tid=171465

Same applies here.

**Comment by Nezarn** [comment]
thats not Project Diva F 2nd, thats the first game Project Diva F (the 2nd game doesn't hang with that error, it just showes black screen + missing shader instruction)

Also http://www.emunewz.net/forum/showthread.php?tid=162348&pid=230695#pid230695
(note:doesn't need any LLE modules)
