### ISSUE TITLE
Borderland2 (BLES01684) crash when connected to rpcn

### ISSUE THREAD

**Issue by SimonCardaire** [RPCS3/rpcs3#16457]
### Quick summary

The game work well if there is no connection to internet. When connected to rpcn, it crash after searching for user profile informations online. 

### Details

Step to reproduce : 
Launch the game BLES01684 with all dlc installed, the update 1.15 and connection to rpcn and a valid account. Let the logo display, then press start button and it crash when searching informations online.

### Attach a log file

![Capture](https://github.com/user-attachments/assets/a58cd990-8e56-4adf-bee1-0091ad996b20)

### System configuration

Intel(R) Core(TM) i5-10300H CPU
8 gb RAM
Nvidia geforce GTX 1650

### Other details

Sorry for the quality of the ticket, I'm not at home and I can't install the version of rpcs3 I want. I found this bug on a bootable hard drive with a custom batocera and I can't get the log file for now. The Rpcs3 version is 0.0.34-17253. It worked perfectly last week with an older version. When I have time I will investigate to find wich one exactly introduce the bug.

**Comment by rafael-57** [comment]
Similar issue with Tekken 5 DR, NPEA00019, but the entire emulator crashes.

Ryzen R7 5800X3D
32GB RAM
RTX 3080

[RPCS3.log](https://github.com/user-attachments/files/18267177/RPCS3.log)
