### ISSUE TITLE
Nothing happens when i open app.

### ISSUE THREAD

**Issue by RukoBlood** [RPCS3/rpcs3#16467]
### Quick summary

When i open rpcs3.exe nothing happens. Tried on version 0.0.20 and 0.0.34.

### Details

In logs also nothing. My laptop meets minimal requirements.

### Attach a log file
Comically small log file
[RPCS3.log](https://github.com/user-attachments/files/18266296/RPCS3.log)

### System configuration

OS: Windows 10 Latest Official 
CPU: I5-3230M (2C/4T, i know about bad performance)
GPU: GT 720M (2GB DDR3, Not GDDR3, 388.73 Latest Driver, OGL 4.6, Vulkan isn't Supported because IDK, DX11)
RAM: 8GB Dual Channel
HDD: 500GB Sata2 slow aah Seagate

Waffle Maker: ASUS X550VC

### Other details

Cemu runs fine, even runs Minecraft.

**Comment by Hasster1** [comment]
1 - Support is provided in the official discord server - https://discord.gg/RPCS3, Github is for already established problems.
2 - Looks like your windows' User name consists of non-english letters, try moving your rpcs3 folder somewhere else, where the path to the folder doesn't contain any non-english symbols.

**Comment by Megamouse** [comment]
What's the username?

**Comment by Hasster1** [comment]
> What's the username?

Looks like it's the cyrilic letter Я - ya, but for some reason it's in the ANSI encoding, i found that by using notepad++.

**Comment by Hasster1** [comment]
I've renamed my rpcs3 folder into "тест" (Russian Test) and opened rpcs3, it opened as usual without any problems. The log file had the same ANSI-encoded characters, which means that it's not the problem.

**Comment by Hasster1** [comment]
Wait, maybe it's an issue with a Temp folder instead...

**Comment by RukoBlood** [comment]
Uuh, looks like an another cyrillic incompatibility...
Well, i will try to reinstall my OS soon and i change a user folder name in new installation.
Понятно... (Understandable)

**Comment by Nekotekina** [comment]
On Windows plain argv is cursed because it's literally impossible to make it UTF-8, it forses you to use _wmain or something. Absolutely cursed.

**Comment by oltolm** [comment]
We have this code in `main.cpp`.

```c++
	int n_args = 0;
	if (LPWSTR* arg_list = CommandLineToArgvW(GetCommandLineW(), &n_args))
	{
		std::string utf8_args;
		for (int i = 0; i < n_args; i++)
		{
			if (i > 0) utf8_args += " ";
			utf8_args += '\'' + wchar_to_utf8(arg_list[i]) + '\'';
		}
		sys_log.notice("argv_utf8: %s", utf8_args);
	}
```
Why would it not work?

**Comment by Nekotekina** [comment]
I suspect wchar_t needs to be in main after all.

**Comment by Megamouse** [comment]
> I suspect wchar_t needs to be in main after all.

I already tried that. it's not the issue anyway.
RPCS3 also works fine for me with the foldername

**Comment by RukoBlood** [comment]
> 1 - Support is provided in the official discord server - https://discord.gg/RPCS3, Github is for already established problems. 2 - Looks like your windows' User name consists of non-english letters, try moving your rpcs3 folder somewhere else, where the path to the folder doesn't contain any non-english symbols.

Thanks. After i bought a new laptop and installed windows 11 with english username problem solved
![image](https://github.com/user-attachments/assets/dcea02e9-d482-492c-ab0e-85709cc3cb55)
