### ISSUE TITLE
Beyond Two Souls

### ISSUE THREAD

**Issue by ELAD3356P** [RPCS3/rpcs3#1647]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0x80000003.
Exception address: 00007FFDF961B72C.
ExceptionInformation[0x0]: 0000000000000000.
Instruction address: 00007FFDF961B72C.
Image base: 00007FF764070000.

An unknown internal exception has occured. Please report this to the developers.

**Comment by tambry** [comment]
Outdated build. Also Github issues is more for development related issues or very specific issues with games.

**Comment by ELAD3356P** [comment]
i have the latest :d5bb951

**Comment by ELAD3356P** [comment]
it showes me the game window but it's all white and then the emulator crases.

**Comment by tambry** [comment]
http://www.emunewz.net/forum/showthread.php?tid=174352
