### ISSUE TITLE
Exception: Unknown register name: ssa [Vulkan]

### ISSUE THREAD

**Issue by fenix008** [RPCS3/rpcs3#1651]
·F {rsx::thread} Exception: Unknown register name: ssa
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKCommonDecompiler.cpp:252, in function vk::get_varying_register)

This error shows in game "Kung Fu Panda: Showdown of Legendary Legends", when I click "Press X to start" and after it shows the black screen and this error.
LOG here: http://rghost.ru/8BFt5LKCL
- if need it:

Fragment Program: http://rghost.ru/6jrvxlHF9
Vertex Program: http://rghost.ru/6JDzC5556

Original Thread: http://www.emunewz.net/forum/showthread.php?tid=173713

**Comment by kd-11** [comment]
The declaration for ssa varying register is missing from the lookup table is all.

**Comment by kd-11** [comment]
@fenix008 Check if https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.84/artifacts fixes the issue

**Comment by fenix008** [comment]
thanks. I will do it soon!

**Comment by fenix008** [comment]
alright, now it works and moves on.
http://puu.sh/o3Hx1/24c544acb3.jpg (Now is only general problem...in-game graphics, but I write it in my thread)

Thanks ;)

**Comment by kd-11** [comment]
@fenix008 Check this once it finishes building: https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.88/artifacts
My last commit was somewhat incorrect, but should be fixed now

**Comment by fenix008** [comment]
yeah, it works.
