### ISSUE TITLE
BIT.TRIP Runner 2: Future Legend of Rhythm Alien Trial [NPUB30733] no output on DX12

### ISSUE THREAD

**Issue by tambry** [RPCS3/rpcs3#1652]
Settings:
PPU Interpreter 2
SPU Interpreter (fast)
DX12 renderer
1280x720

No LLE needed.

No output. Sounds for it progressing further can be heard. [Vulkan goes in-game](https://i.imgur.com/o2vVF6A.png) and is actually quite playable despite dozens of graphical issues.

**Comment by raven02** [comment]
I will push the fix shortly 

![1](https://cloud.githubusercontent.com/assets/3000282/15508642/dc379e00-2202-11e6-97ef-80de30b0eb19.jpg)
