### ISSUE TITLE
Vulkan: Hatsune Miku Project Diva F scaling issue (NV specific)

### ISSUE THREAD

**Issue by Nezarn** [RPCS3/rpcs3#1655]
Vulkan:
![rpcs3_2016-04-02_21-41-32](https://cloud.githubusercontent.com/assets/3817985/14228667/74cc4f36-f91c-11e5-9c29-b0ac29c970f4.png)

OpenGL:
![rpcs3_2016-04-02_22-11-39](https://cloud.githubusercontent.com/assets/3817985/14228776/ed35636a-f91f-11e5-9275-5a4f11ba8f42.png)

On DX12 and OGL it works fine. (also the other game i have vulkan works fine so i guess its not a driver\graphics card issue (i have a gtx 970))

Hatsune Miku Project Diva F 2nd demo has the same issue with vulkan.

Shaders and logs (vulkan + opengl)
https://gist.github.com/Nezarn/9df63f3ee8c0a5f2ae6c18fa0a4bc15f

**Comment by SakataGintokiYT** [comment]
[Vulkan] - Try on 1920x1080

**Comment by Nezarn** [comment]
Its still bad, Screen is still cut off a bit and its not centered.

**Comment by kd-11** [comment]
Might be a viewport or blitting region issue during flip. I'll take a look.

**Comment by kd-11** [comment]
Seems to be Geforce specific. Plays fine on Radeon with res set to 1280x720. With AMD, the only scaling issue is that the image is not centered after correcting for aspect ratio. This is however not the same as the bug shown here. A developer on NV hardware will have to take a look.

**Comment by raven02** [comment]
And looks like it is also game specific .For example , Ardkeo Series looks fine on my nvidia card.

**Comment by raven02** [comment]
@kd-11 how about in 720x480 ? as i found vulkan distortion mostly on 720x480

**Comment by kd-11** [comment]
@raven02 720x480 isnt 16:9 hence the distortion. I'll try to set up centered scaling once I finish the fullscreen issue.

**Comment by Bryceless** [comment]
I have noticed that using DSR on an Nvidia Graphics card can help, but it's not exactly perfect either.
From what I've seen, a higher screen resolution makes it so less of the image is scaled out, but when I use my 1600x900 screen resolution, the image looks almost like Nezarn's.

**Comment by raven02** [comment]
@kd-11 , hopefully this scaling issue on Vulkan can be fixed .This unfortunately affects NV users only ...

**Comment by kd-11** [comment]
Unfortunately, I dont have access to NV+vulkan gpu. The driver seems to not like the texture format being scaled here though. The vulkan spec has something about this, but I'll have to check again since its been a while. If I'm right, i'll have to emulate hardware texture scaling for NV.

**Comment by raven02** [comment]
Vulkan on NV is trouble . I remember we also have difficulty to get Vulkan work on NV .

**Comment by kd-11** [comment]
@raven02 Can you check if using Nearest filtering fixes this bug? You can find the function copy_scaled_image in VkTexture.cpp and change VK_FILTER_LINEAR to VK_FILTER_NEAREST

**Comment by raven02** [comment]
No luck .Just tested.

vkCmdBlitImage(cmd, src, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, dst, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &rgn, VK_FILTER_NEAREST);

**Comment by raven02** [comment]
One notice . The scaling will be correct when switch to full screen.

**Comment by Bryceless** [comment]
Raven02, with the latest build, the scaling is still incorrect even when in fullscreen.

**Comment by raven02** [comment]
@kd-11 No luck .Just tested , still scale wrong .

 vkCmdBlitImage(cmd, src, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, dst, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &rgn, VK_FILTER_NEAREST);

**Comment by raven02** [comment]
Yes , full screen scaling is also incorrect as well

**Comment by raven02** [comment]
Issue resolved .Closed

**Comment by kd-11** [comment]
Just to clarify for future reference, the bug was in the renderArea declaration of the render pass.
