### ISSUE TITLE
OpenGL- black screen with fps and sound issue

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1658]
@kd-11 
@vlj 

[TNT Racers]
Log : https://gist.github.com/SakataGintokiYT/ccfb09e3504c87299456838febb48660

{rsx::thread} RSX: Texture params are invalid for block starting 0xC058B600!
{rsx::thread} RSX: Params passed w=256, h=256, mip=1, found w=1024, h=1024, mip=1
_____________________________________________________________________________
[Castle Crashers]
Log : https://gist.github.com/SakataGintokiYT/ecb80303df813cc962e7652c660f5907

{rsx::thread} RSX: Texture params are invalid for block starting 0xC1CF3480!
{rsx::thread} RSX: Params passed w=128, h=512, mip=1, found w=256, h=256, mip=1

{rsx::thread} RSX: Texture params are invalid for block starting 0xC1B3F480!
{rsx::thread} RSX: Params passed w=256, h=256, mip=1, found w=512, h=128, mip=1

{rsx::thread} RSX: Texture params are invalid for block starting 0xC2157480!
{rsx::thread} RSX: Params passed w=512, h=128, mip=1, found w=256, h=256, mip=1

{rsx::thread} RSX: Texture params are invalid for block starting 0xC282DF80!
{rsx::thread} RSX: Params passed w=512, h=256, mip=1, found w=256, h=512, mip=1

{rsx::thread} RSX: Texture params are invalid for block starting 0xC1C4F480!
{rsx::thread} RSX: Params passed w=512, h=64, mip=1, found w=128, h=256, mip=1
_____________________________________________________________________________
[Tennis in the Face]
Log : https://gist.github.com/SakataGintokiYT/c77ffcaee05692e200166ff676e474ca

{rsx::thread} RSX: Texture params are invalid for block starting 0xC2A3E500!
{rsx::thread} RSX: Params passed w=120, h=126, mip=1, found w=255, h=83, mip=1

RSX: Texture params are invalid for block starting 0xC0004480!
{rsx::thread} RSX: Params passed w=1569, h=999, mip=1, found w=1622, h=1267, mip=1

**Comment by kd-11** [comment]
That error happens whenever the cached texture was saved using different dimensions than the requested texture. I'm not sure if thats the issue though since it ought to reupload the texture anyway.

**Comment by kd-11** [comment]
Ok. I actually found the problem. It happens in many games with OpenGL. I'll submit a fix ASAP.

**Comment by kd-11** [comment]
@SakataGintokiYT  This has been resolved. Please retest.

**Comment by Altaiar** [comment]
HI in this Build rpcs3-ReleaseLLVM-d846eac0
this Games i try to run (with OGL) emulator crash
Game list: Scogger HD & Metal Slug 3 & SuperFrog & Shovel Knight 
shovel knight Log :
http://www.mediafire.com/download/0sgc3jsg5327gu8/RPCS3.log

**Comment by kd-11** [comment]
@Altaiar  A fix for openGL crashing was commited. Check if it fixed the crashing.

**Comment by Altaiar** [comment]
@kd-11 Fixed now!

**Comment by kd-11** [comment]
@SakataGintokiYT Please close this bug report if it is fixed

**Comment by SakataGintokiYT** [comment]
Fixed

**Comment by RenanZX** [comment]
I still have this problem with OpenGL in the latest build
