### ISSUE TITLE
OGL: Jurassic: The Hunted broken in-game texture

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#1660]
**LLE Used:**
cellFiber_Library
CELL_L10N_PRX_MODULE_NAME
cellSail_Library
cellSre_Library

**OGL** [LOG](https://mega.nz/#!yYNjkDqa!dJK8LLH1OALLVygmtFrDbeq5vYf0ACVQqvgEbNpBVP4)

![jurassic rpcs3](https://cloud.githubusercontent.com/assets/11453507/14254563/90b0423c-fa90-11e5-85dd-40503258e21b.jpg)

Buggy ingame [video](https://www.youtube.com/watch?v=qCZtazOmscM)

**DX 12** [LOG](https://mega.nz/#!TE1AnDYJ!n0k-ZE7g-9zMiR3ol53mJot9oqEG12ONKulBqo7iNJw)

Hangs at title screen

```
{rsx::thread} Exception: Working buffer not big enough
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12MemoryHelpers.h:78, in function data_heap::alloc)

```

**Vulkan** [LOG](https://mega.nz/#!DM8UjaxD!fVO6puUaRHGpzNQ9mMgsr8H41EDdPWG2l_bOiCU1iIM)

Very broken ingame

**Comment by tambry** [comment]
Still an issue? There was some refactoring of rendering code between backends recently.

**Comment by raven02** [comment]
I have left message to @JohnGodgames to retest this game and post comment here.

**Comment by JohnGodgames** [comment]
@tambry sorry I've forgot about this issue.Yeah it looks a lot better 

![jurassic the hunted rpcs3](https://cloud.githubusercontent.com/assets/11453507/15994011/21ef9c50-30f8-11e6-9957-908d95a74435.PNG)
