### ISSUE TITLE
[OpenGL] Hatsune Miku Project Diva F Demo crashes with latest master

### ISSUE THREAD

**Issue by Nezarn** [RPCS3/rpcs3#1666]
FragmentProgram: http://pastebin.com/sUqbFNVg
VertexProgram: http://pastebin.com/S9460bGd
Log: http://pastebin.com/fv323yMH

**Comment by tambry** [comment]
At least give on some info how it crashes, the stack trace, the usual stuff.

**Comment by Nezarn** [comment]
Just "RPCS3 stopped working"

**Comment by tambry** [comment]
So like another 100 games? Like I said, at minimum a stack trace should be given for such reports. Closing this for now, until you're able to provide such information.

**Comment by Nezarn** [comment]
I didn't know other 100 games were fully playable before with very minor graphics glitches... can you get off your high horse? Why do you need to look at every other humans as retards by default?

This was my last issue report, i won't give a f*** about this project anymore. (HINT: you can see from the log why\when it crashes, clearly something is wrong at vertex shader since it crashes as soon as first texture should be seen (which is the SEGA logo))

` 	ucrtbase.dll!00007fffbd0998fe()	Unknown
 	ucrtbase.dll!00007fffbd099036()	Unknown
>	rpcs3.exe!write_vertex_array_data_to_buffer(gsl::span<enum gsl::byte,-1> raw_dst_span, const gsl::byte * src_ptr, unsigned int first, unsigned int count, rsx::vertex_base_type type, unsigned int vector_element_count, unsigned int attribute_src_stride, unsigned char dst_stride) Line 73	C++
 	rpcs3.exe!GLGSRender::set_vertex_buffer() Line 323	C++
 	rpcs3.exe!GLGSRender::end() Line 301	C++
 	rpcs3.exe!rsx::__rsx_methods_t::wrapper<1538,void (__cdecl*)(rsx::thread * __ptr64,unsigned int),&rsx::nv4097::set_begin_end>(rsx::thread * rsx, unsigned int arg) Line 736	C++
 	rpcs3.exe!rsx::thread::on_task() Line 455	C++
 	rpcs3.exe!named_thread_t::start::__l2::<lambda>() Line 1375	C++
 	rpcs3.exe!thread_ctrl::spawn::__l2::<lambda>(std::promise<void> promise) Line 83	C++
`

**Comment by tambry** [comment]
I don't think I ever said that (another) 100 games were fully playable. That definitely isn't the case. I've got a speculative fix, thanks to the stack trace and the commit that broke it.
