### ISSUE TITLE
Settings window: DX12 showing on a non-W10 system

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1671]
I'm on a Windows 7 OS and DX12 shows up in the Render list

![screenshot_20](https://cloud.githubusercontent.com/assets/10283761/14580808/171b4aca-03d2-11e6-8ddb-dac8f7552666.png)

I don't know if this is intended, because in v0.0.0.6 it had a check to see if DX12 was there and if it wasn't then it wouldn't append the DX12 value to the Render dropdown

It doesn't crash the emulator though when trying to start a game, it just outputs
```
LDR: class std::runtime_error thrown: Assertion failed: D3D12Module = LoadLibrary(L"d3d12.dll")
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12GSRender.cpp:46)
```

**Comment by DPersonalized** [comment]
Perhaps this is just me, but I think "DirectX 12" would look cleaner than "DX12."

**Comment by Nekotekina** [comment]
It's not a bug.
