### ISSUE TITLE
DX12: Disgaea 3 black screen

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1672]
{rsx::thread} class std::runtime_error thrown: get_compare_func(): Invalid or unsupported compare func (0x0)
(in file Emu\RSX\D3D12\D3D12Formats.cpp:134)

Only with dx12, after 0.0.0.9.
Log: http://pastebin.com/AGJxAAz2

**Comment by raven02** [comment]
it works previously with dx12?

**Comment by danilaml** [comment]
@raven02  yes. It started after 0.0.0.9 or so.

**Comment by raven02** [comment]
It hits CELL_GCM_ZERO .Let's try this in D3D12Formats.cpp

**Comment by paulsapps** [comment]
case CELL_GCM_ZERO: return D3D12_COMPARISON_FUNC_NEVER; // Treat it as NEVER
        break; << why? this can never happen

**Comment by danilaml** [comment]
@raven02 it wasn't appearing before so it's not games fault. I guess 0.0.0.9 introduced some changes that a responsible for appearance of bogus 0 commands.

**Comment by raven02** [comment]
Disgaea 3 did also pass garbage before for front face so i am not sure if this is real bogus command

**Comment by danilaml** [comment]
@raven02 but it works fine on https://github.com/RPCS3/rpcs3/commit/7c1ab4726262420f3ed1a0fc58d833d2744df23a and is broken  in https://github.com/RPCS3/rpcs3/commit/fe1e7a1bdbf4bdd71ead4c74164d7cfa5abc53fa though with a little different error:
```
{rsx::thread} class std::runtime_error thrown: data_heap::alloc(): Working buffer not big enough
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:64)
```

**Comment by raven02** [comment]
Just tested it as well . All backend work okay before 0.0.0.9 .After 0.0.0.9 , only OpenGL and Vulkan still work but not DX12 which has the compare function error. So i agreed it is bogus command.

**Comment by raven02** [comment]
I put it to version 0.0.0.9 since it works well in 0.0.06 . Therefore , closing this .

**Comment by danilaml** [comment]
@raven02 what? Why did you close?
