### ISSUE TITLE
cellSysutilRegisterCallbackDispatcher unimplemented but before it was working fine

### ISSUE THREAD

**Issue by supergatto** [RPCS3/rpcs3#1674]
On RPCS3 v0.0.0.6-5-4eb1267 
This function was working but now it says that it's unimplemented.
Here is my old log and new log.
[skate3new.zip](https://github.com/RPCS3/rpcs3/files/222771/skate3new.zip)

[skate3.zip](https://github.com/RPCS3/rpcs3/files/222770/skate3.zip)

**Comment by tambry** [comment]
Well it has never been implemented. But as I said in my answer to your PM, why are you LLE'ing sceNpTrophy? Does this not occur without LLE'ing sceNpTrophy?
And as I mentioned in my PM, you shouldn't really report unimplemented functions here, as there are so so many of them, and they're often better suited to the forum thread.

> If you encounter problems with HLE implementation (excluding unimplemented functions, like this), then report them here.

**Comment by supergatto** [comment]
I am not a developer but it says ! LDR: Imported function 'cellSysutilRegisterCallbackDispatcher' (0x16fece4). Anyway if i am wrong close this.

**Comment by tambry** [comment]
Well it does import it, because it wants to use it. We in most cases simply abort emulation, when we encounter an unimplemented function ([such as this function](https://github.com/RPCS3/rpcs3/blob/fe1e7a1bdbf4bdd71ead4c74164d7cfa5abc53fa/rpcs3/Emu/Cell/Modules/cellSysutil.cpp#L330)).
But before closing, I'd still like to know the following:
> Why are you LLE'ing sceNpTrophy? Does this not occur without LLE'ing sceNpTrophy?

**Comment by SakataGintokiYT** [comment]
@tambry 
[a1122f07]
Without modules 
LDR: Unknown module 'sys_libstdcxx'
LDR: Unknown function '0x4210C462' in module 'sceNp' (index 2972)

**Comment by tambry** [comment]
@SakataGintokiYT Could you provide the full log?

**Comment by SakataGintokiYT** [comment]
*Log : https://gist.github.com/SakataGintokiYT/70e6686956f950e4ab494db7756279bd

libfiber.prx - cellFiber_Library
libl10n.prx - CELL_L10N_PRX_MODULE_NAME
libspurs_jq.prx - cellSpursJq_Library
libsre.prx - cellSre_Library
libssl.prx - cellSsl_Library
libvdec.prx - libvdec_Library
____________________________________________________________________________
*Without modules :
*Log : https://gist.github.com/SakataGintokiYT/bdef6567dd2f135e23a94bf1541a15d3

**Comment by tambry** [comment]
@SakataGintokiYT Looks like a normal game that simply doesn't work. Could you also try with SPU interpreter 1 (or 2) and post the log for it?

**Comment by SakataGintokiYT** [comment]
SPU interpreter 1 : https://gist.github.com/SakataGintokiYT/1250cc06f2e38276c8bb381cee0e0cef
SPU interpreter 2:  https://gist.github.com/SakataGintokiYT/3b197b09ebc539e09f16e43caf10ec10

**Comment by tambry** [comment]
Is there any TTY output?

**Comment by SakataGintokiYT** [comment]
TTY file is empty

**Comment by tambry** [comment]
I'm afraid there's nothing really to fix. There should really be no need to LLE sceNpTrophy.
