### ISSUE TITLE
Unsupported SPU Thread

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1677]
@Nekotekina 
@tambry 

[efc87792]
### 1.
_______________________________________________________________________________
{SPU[0x2df] Thread (_libsailCellSpursKernel2) [0x08530]} SPU: [0x08534] Branch-to-next with $LR
{SPU[0x2df] Thread (_libsailCellSpursKernel2) [0x25c40]} SPU: [0x25c44] Branch-to-next with $LR
{SPU[0x2df] Thread (_libsailCellSpursKernel2) [0x14d58]} SPU: [0x14d5c] Branch-to-next with $LR
{SPU[0x2e0] Thread (_libsailCellSpursKernel3) [0x08d78]} SPU: [0x08d7c] Branch-to-next with $LR
________________________________________________________________________________
{SPU[0x2de] Thread (_libsailCellSpursKernel1) [0x01614]} MEM: Invalid or unsupported instruction (op=0, reg=24, d_size=0, a_size=0x0, i_size=0)

{SPU[0x2de] Thread (_libsailCellSpursKernel1) [0x01614]} MEM: decode_x64_reg_op(00007ffc470fca44h): unsupported opcode found (0F2941F04C3B0DB95500007617E9C200)
________________________________________________________________________________
{PPU[0x2ca] Thread (_libsail-control) [0x00e1fd80]} sys_spu: Unsupported SPU Thread options (0x2)
________________________________________________________________________________
{PPU[0x2ca] Thread (_libsail-control) [0x00e35a3c]} sys_prx TODO: sys_prx_get_module_id_by_name(name=cellLibprof, flags=0, pOpt=*0x0)

NARUTO: Ultimate Ninja STORM [BLES00371]
Log :https://gist.github.com/SakataGintokiYT/bc8125c34b74102ec901f90292deec24
SPUJIT : https://mega.nz/#!BRRhwCoQ!t_jLpq_a42IHuHXcWDfdI9-XPf-4Acdm1UpU0UoBuyI

### 2.

{PPU[0x6cf] Thread (_libsail-control) [0x00bf2a3c]} sys_prx TODO: sys_prx_get_module_id_by_name(name=cellLibprof, flags=0, pOpt=*0x0)
___________________________________________________________________________
{SPU[0x6e2] Thread (_libsailCellSpursKernel0) [0x08d78]} SPU: [0x08d7c] Branch-to-next with $LR
{PPU[0x719] Thread (_libsail-control) [0x00bdcd80]} sys_spu: Unsupported SPU Thread options (0x2)
___________________________________________________________________________

{SPU[0x6a] Thread (NuccSpursCellSpursKernel1) [0x04c00]} SPU: 0x04c20: Unknown/Illegal opcode (0xa5a5a5a5)
{SPU[0x6a] Thread (NuccSpursCellSpursKernel1) [0x04c00]} SPU: 0x04c30: Unknown/Illegal opcode (0x4a4f4243)
{SPU[0x6a] Thread (NuccSpursCellSpursKernel1) [0x04c00]} SPU: 0x04c34: Unknown/Illegal opcode (0x52542056)
{SPU[0x6a] Thread (NuccSpursCellSpursKernel1) [0x04c00]} SPU: 0x04c38: Unknown/Illegal opcode (0x65723133)

Naruto Shippuden: Ultimate Ninja Storm 2
Log ::  https://mega.nz/#!8AgHnCyR!2xyE4R525BtKhnX8PjABhKT_Gih_pl-omtrQh0XKNO4
SPUJIT : https://mega.nz/#!0ZBCEZjB!t5yXGbxE4JyjsKDZnYzE85F_eCy6ikgizfWMDovKbKU

**Comment by raven02** [comment]
Those are common SPU errors . i'm going to consolidate as one issue instead of duplicate everywhere.
