### ISSUE TITLE
Vulkan:  freezes/crashes (Nvidia Specific)

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1679]
4 Elements HD [NPUB30347] - freezes ingame, when tutorial dialog appears.
http://rghost.ru/7JpXZHY22/image.png
Bayonetta [BLES00599] and Bayonetta: First Climax demo [NPEB90193] - always freezes after you trying to pass "Press Start Button" screen.
http://rghost.ru/6CysPvx6M/image.png
Disgaea 3 [BLES00452] - freezes after intro skip, when you start new game.
The Guided Fate Paradox [NPUB31320] - got ingame freeze, when try attempt to equip items.

Those freezes doesn't occur, when using OpenGL renderer. Also noticed, that VSync option doesn't work. Tested on GeForce GTX 970 with 364.91 drivers (Vulkan API 1.0.8).

Edit: added logs from recent master build 75fe95eeb1, PR #1676 
http://rghost.ru/7SSVCm8j5

**Comment by vlj** [comment]
Nvidia drivers don't support VSync with Vulkan atm. They expose Mailbox/FIFO/... present mode but for some reasons they're not vsynced.

**Comment by kd-11** [comment]
Seems vkAllocateDescriptorSets fails at least for the first two.

**Comment by kd-11** [comment]
@B1ackDaemon You could try and increase the descriptor pool sizes. They currently top out at 1000 draw calls per frame. They were increased before, but it seems they need to be increased some more. I've seen games with > 1000 calls in some situations.

**Comment by SakataGintokiYT** [comment]
@kd-11 
VkDescriptorPoolSize uniform_buffer_pool ?
infos.maxSets = 1000; ?

**Comment by kd-11** [comment]
@SakataGintokiYT  you need to change that as well as in the VKGSRender intitialization code. There are some values there like 3000 and 16000 which are calculated using 100 * num_descriptors; i.e there are 3 uniform buffer descriptors, 16 texture descriptors and 16 vertex texture descriptors giving 3000, 1600 and 16000 respectively. You'll need to recalculate those values as well. We'll need to automatically balance the draw call load by flushing the command queues when we run out of descriptors, but increasing the sets should be ok for now.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/1766 will fix most of the descriptor set issues.

**Comment by raven02** [comment]
Vsync option is working with Vulkan at least in 368.81

**Comment by raven02** [comment]
Just before crashing using Vulkan with debug output enabled , i got the following error

·E {rsx::thread} RSX: ERROR: [DS] Code 7 : Cannot submit cmd buffer using deleted image 0xb528c.

**Comment by raven02** [comment]
@kd-11 .Thanks for fix the memory type crash . The above one from 1942 Joint Strike  is a different crash that startup ok but everytime crash with the following error only

·E {rsx::thread} RSX: ERROR: [DS] Code 7 : Cannot submit cmd buffer using deleted image 0xca23.
·E {rsx::thread} RSX: ERROR: [MEM] Code 12 : vkCmdBeginRenderPass(): Cannot read invalid memory 0xca1d, please fill the memory before using.

**Comment by kd-11** [comment]
About 1942; on radeon it detects that we are issuing commands without an open commandbuffer, but as far as I can tell, that is not the case. I'm suspecting a bug in the validation layers somewhere that caused the commandbuffer to detect as closed. Maybe its because of the deleted image stuff. I'll look into it separately.

**Comment by kd-11** [comment]
@raven02; Just a hunch, could you check if commenting out the `if(m_rtts_dirty) return` block in prepare_rtts fixes the crash with 1942? I suspect we are doing something shady with the framebuffers like deleting them after every frame.

**Comment by raven02** [comment]
Just tried to comment out that block but it still crashes with the same error.

**Comment by raven02** [comment]
Meanwhile , I'll test it out in another game  that random crash out of the emulator

**Comment by raven02** [comment]
Just tried out 4 elements HD , it boots up then hit this error .

F {rsx::thread} class fmt::exception thrown: vk::image::image(): Assertion failed! Result is C4650B07h
(in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:368)

**Comment by kd-11** [comment]
@raven02 Thats a failed VkCreateImage call. You'll need to check the specifics of the failed image configuration in that case. NV uses their own internal error codes so there's no way to know what that error code means.

**Comment by raven02** [comment]
I see this error code before when we check the resize/full screen issue previously.

**Comment by raven02** [comment]
Get more detail when enabled debug output

 {rsx::thread} RSX: ERROR: [Image] Code 13 : CreateImage extents is 0 for at least one required dimension for image of type 1: Width = 0 Height = 47104 Depth = 1.
E {rsx::thread} RSX: ERROR: [Image] Code 13 : CreateImage extents exceed allowable limits for format: Width = 0 Height = 47104 Depth = 1:  Limits for Width = 16384 Height = 16384 Depth = 1 for format VK_FORMAT_B8G8R8A8_UNORM.
E {rsx::thread} RSX: ERROR: [Driver] Code 0 : vkCreateImage: image creation failed due to invalid parameter

**Comment by raven02** [comment]
Interesting . I tried a build few days ago, it can show few screen though hit the same error once reach the title screen.

**Comment by kd-11** [comment]
@raven02 Can you obtain a callstack using visual studio? If we can find the function responsible for creating an image with bogus dimensions, we can probably find the broken register decode. That height value of 47104 is also bogus. Just add a check and throw in the image constructor for width 0 and break, then get the callstack.

**Comment by raven02** [comment]
Sure . let me check this out.

**Comment by raven02** [comment]
I set a breakpoint at

CHECK_RESULT(vkCreateImage(m_device, &info, nullptr, &value));

![untitled](https://cloud.githubusercontent.com/assets/3000282/17295763/59bc0f56-5830-11e6-9ce6-3e4b182b4030.jpg)

**Comment by raven02** [comment]
![1](https://cloud.githubusercontent.com/assets/3000282/17296066/e659f378-5831-11e6-83dd-dfa5ba6c7cfc.jpg)
![2](https://cloud.githubusercontent.com/assets/3000282/17296069/e8eb627a-5831-11e6-90cc-898b48ffc9bc.jpg)

**Comment by raven02** [comment]
Probably is NV3089_IMAGE_IN_SIZE or NV3089_IMAGE_OUT_SIZE

**Comment by kd-11** [comment]
@raven02 
I'm almost certain you stumbled upon a 3d texture. Very interesting. The texture upload algorithm is broken in case we have texture_dimension_3d since height is never set, hence the bogus value. However, width is still computed using tex.width() so that might be another bug.

**Comment by raven02** [comment]
Yep, this is the 1st texture/image show when bootup

![untitled](https://cloud.githubusercontent.com/assets/3000282/17314689/b845cea0-5898-11e6-8010-91be8be490e5.jpg)

**Comment by raven02** [comment]
I put in the following in VKtexturecache.h and looks like width zero is 2D texture

			if (tex.width() == 0)
				throw EXCEPTION ("width is zero, teture type : %x", tex.get_extended_texture_dimension());

**Comment by Nezarn** [comment]
@raven02 also since you're there, you could fix that typo lol (teture type should be texture type, no?)

**Comment by raven02** [comment]
@Nezarn. Yep, it is only for testing purpose .

**Comment by kd-11** [comment]
@raven02 https://github.com/RPCS3/rpcs3/pull/2018

**Comment by raven02** [comment]
@kd-11 . no more insertion but loop with the following errors

E {rsx::thread} RSX: Texture upload requested but invalid texture dimensions passed
E {rsx::thread} RSX: Texture upload failed to texture index 0. Binding null sampler.

**Comment by kd-11** [comment]
Well, yea, 0 dimensions will give a blank output. I'm surprised that DX12 is getting a different texture dimension than vulkan here: I'm probably missing something thats broken elsewhere. Can you check what dimensions DX12 gets for this texture upload request?

**Comment by raven02** [comment]
Sure will check this out on DX12

**Comment by raven02** [comment]
@kd-11 , not really , DX12 also failed at zero width as well .

E {rsx::thread} RSX: width = 0 , height = f800
F {rsx::thread} class fmt::exception thrown: `anonymous-namespace'::upload_single_texture(): HRESULT = The parameter is incorrect.
(in file Emu\RSX\D3D12\D3D12Texture.cpp:138)

**Comment by raven02** [comment]
It affects all backends indeed
