### ISSUE TITLE
Dragon Ball Z: Ultimate Tenkaichi [BLUS30823]

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1685]
[e30e5045]

@Nekotekina 
@tambry 

Video : https://www.youtube.com/watch?v=9iK4kRvbcQ8

Settings:
-PPU - Interpreter 2
-SPU - Interpreter ASMJIT
-Open-GL / Vulkan
-1280x720 
-VSync
-XAudio

LLE:
-libfiber
-libl10n 
-libpamf
-libresc 
-librtc
-libsmvd2
-libsre 

- Log : https://gist.github.com/SakataGintokiYT/64e4d695ac2abbb30b80dbc7cba58706

________________________________________________________________________________

- {PPU[0x9b] Thread (sp_sound_font_synthesis_thread) [0x0060bd80]} struct vm::access_violation thrown: Access violation reading address 0x1004998

- {PPU[0x90] Thread (sp_file_server_load_thread) [0x006b307c]} MEM: Invalid d_size (0x4)

- {PPU[0x90] Thread (sp_file_server_load_thread) [0x006b307c]} struct vm::access_violation thrown: Access violation writing address 0xffffffff

- {PPU[0x8] Thread (main_thread) [0x00619d04]} struct vm::access_violation thrown: Access violation reading address 0x8

- {PPU[0x3d] Thread (cri_adxm_vv_proc) [0x00628de0]} struct vm::access_violation thrown: Access violation reading address 0xa8dda7d5

_____________________________________________________________________________

- DX12 : 
{rsx::thread} class fmt::exception thrown: D3D12GSRender::flip(): HRESULT = The parameter is incorrect.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12GSRender.cpp:522)

**Comment by MoochMcGee** [comment]
I don't think the SPU recompiler works, does it?

**Comment by tambry** [comment]
I think that SPU recompiler isn't really recommended, as it has some stuff that isn't implemented on it.

**Comment by raven02** [comment]
@SakataGintokiYT , did you still see the DX12 error above ? and this game bootup okay and in-game ?

**Comment by SakataGintokiYT** [comment]
@raven02 
Works on DX12  but freezes after while  by this issue  

{PPU[0xc] Thread (main_thread) [0x005fc884]} struct vm::access_violation thrown: Access violation reading address 0xabd36560

**Comment by SakataGintokiYT** [comment]
@raven02 
Do you know how to fix it ?

Log : https://gist.github.com/SakataGintokiYT/8f0aa3eaf3102ea4bbdd1162d9ccc22c

{PPU[0x3] Thread (main_thread) [0x005fc818]} struct vm::access_violation thrown: Access violation reading address 0x4b30
