### ISSUE TITLE
HLE: Virtua Fighter 5 

### ISSUE THREAD

**Issue by fenix008** [RPCS3/rpcs3#1686]
·F {PPU[0x5] Thread (main_thread) [0x005cc5b8]} class std::runtime_error thrown: cellMsgDialogOpen(): 
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellMsgDialog.cpp:15)

Log: http://rghost.ru/6ryvNL45v

Original thread here: http://www.emunewz.net/forum/showthread.php?tid=174494

**Comment by AniLeo** [comment]
Just checked and shouldn't be an issue anymore. If it is, please reopen.

**Comment by fenix008** [comment]
ooh, after some months this game don't show me this error, but not It stuck on greyscreen.....so
