### ISSUE TITLE
Link fail on latest git, build Ubuntu LTS 16.04 Xenial

### ISSUE THREAD

**Issue by thx3ever** [RPCS3/rpcs3#1688]
[  7%] Linking CXX executable rpcs3
CMakeFiles/rpcs3.dir/rpcs3.cpp.o: na função `main':
rpcs3.cpp:(.text+0x2ab): múltipla definição de`main'
CMakeFiles/rpcs3.dir/CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:CMakeCXXCompilerId.cpp:(.text+0x0): definido primeiramente aqui
/usr/bin/ld: não foi possível encontrar -lpng16_static
/usr/bin/ld: não foi possível encontrar -lvulkan
/usr/bin/ld: não foi possível encontrar -lglslang
/usr/bin/ld: não foi possível encontrar -lOSDependent
/usr/bin/ld: não foi possível encontrar -lOGLCompiler
/usr/bin/ld: não foi possível encontrar -lSPIRV
collect2: error: ld returned 1 exit status
CMakeFiles/rpcs3.dir/build.make:10535: recipe for target 'rpcs3' failed
make[2]: **\* [rpcs3] Error 1
CMakeFiles/Makefile2:200: recipe for target 'CMakeFiles/rpcs3.dir/all' failed
make[1]: **\* [CMakeFiles/rpcs3.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by tambry** [comment]
Please follow the build instructions. Seems like you either forgot to install appropriate packages for linking. You can more or less follow the travis.yml for packages that you'll need.

**Comment by thx4ever** [comment]
I have all dependency installed, the error come from rpcs3.cpp multiple definitions of main

**Comment by tambry** [comment]
Would you be able to provide the full log in English?

**Comment by AniLeo** [comment]
@tambry Rough translation of what wasn't in English:

CMakeFiles/rpcs3.dir/rpcs3.cpp.o: on function main': rpcs3.cpp:(.text+0x2ab): multiple definition of main'
CMakeFiles/rpcs3.dir/CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:CMakeCXXCompilerId.cpp:(.text+0x0): defined primarily here
/usr/bin/ld: wasn't possible to find -lpng16_static
/usr/bin/ld: wasn't possible to find -lvulkan
/usr/bin/ld: wasn't possible to find -lglslang
/usr/bin/ld: wasn't possible to find -lOSDependent
/usr/bin/ld: wasn't possible to find -lOGLCompiler
/usr/bin/ld: wasn't possible to find -lSPIRV

**Comment by thx4ever** [comment]
thanks, my system are portuguese brazilian, so i try to compile again

**Comment by AniLeo** [comment]
Tested on Ubuntu 15.10

```
annie@ucrystal:~$ cd rpcs3
annie@ucrystal:~/rpcs3$ git pull
Already up-to-date.
annie@ucrystal:~/rpcs3$ cd ..
annie@ucrystal:~$ cd rpcs3 && cmake CMakeLists.txt && make && cd ../
-- No build type selected, default to Release
CMake Warning (dev) at 3rdparty/libpng/CMakeLists.txt:317 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "png16_static".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- cotire 1.7.3 loaded.
-- Initializing RPCS3_SRC_DIR=/home/annie/rpcs3/rpcs3
LLVM not found! LLVM 3.6 is required. RPCS3 will be compiled without LLVM support.
-- dir='/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0'
-- dir='/usr/include/wx-3.0'
-- dir='/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0'
-- dir='/usr/include/wx-3.0'
-- dir='/usr/include'
-- dir='/usr/include/AL'
-- dir='/home/annie/rpcs3/rpcs3/../3rdparty/pugixml/src'
-- dir='/home/annie/rpcs3/rpcs3/../3rdparty/ffmpeg/linux/x86_64/include'
-- dir='/home/annie/rpcs3/rpcs3'
-- dir='/home/annie/rpcs3/rpcs3/Loader'
-- dir='/home/annie/rpcs3/rpcs3/Crypto'
-- dir='/home/annie/rpcs3/rpcs3/..'
-- dir='/home/annie/rpcs3/rpcs3/../Utilities/yaml-cpp/include'
-- dir='/home/annie/rpcs3/rpcs3/../asmjit/src/asmjit'
-- dir='/home/annie/rpcs3/rpcs3/../3rdparty/libpng'
-- dir='/home/annie/rpcs3/rpcs3/../3rdparty/GSL/include'
-- dir='/home/annie/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler'
-- dir='/home/annie/rpcs3/rpcs3/../rsx_program_decompiler/shader_code'
-- dir='/home/annie/rpcs3/rpcs3/../Vulkan/Vulkan-LoaderAndValidationLayers/include'
-- dir='/home/annie/rpcs3/rpcs3/../Vulkan/glslang/glslang/Public'
-- dir='/home/annie/rpcs3/rpcs3/../3rdparty/GL'
-- dir='/home/annie/rpcs3/rpcs3/../3rdparty/stblib'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/annie/rpcs3
[  4%] Built target png16_static
[ 10%] Built target glslang
[ 10%] Built target OSDependent
[ 10%] Built target OGLCompiler
[ 12%] Built target SPIRV
[ 12%] Built target glslangValidator
[ 12%] Built target spirv-remap
[ 14%] Built target vulkan
[ 14%] Generating something_that_never_exists
-- Found Git: /usr/bin/git (found version "2.5.0") 
-- GIT_VERSION: 4413-aafcf44
[ 14%] Built target GitVersion
make[2]: *** No rule to make target 'rpcs3/../Utilities/GNU.h', needed by 'rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch'.  Stop.
CMakeFiles/Makefile2:667: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by tambry** [comment]
Is that a fresh clone? Doesn't seem right.

**Comment by AniLeo** [comment]
It isn't a fresh clone, but I forced a pull from origin (github.com/rpcs3/rpcs3.git) before doing that.

**Comment by tambry** [comment]
Not quite sure what's wrong here. Someone with more Linux knowledge will need to take a look. Also created a new label - "linux".

**Comment by thx4ever** [comment]
Now i got another error, it seems make dont generate git version.h 
[ 15%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Gui/MainFrame.cpp.o
/home/thx4ever/rpcs3/rpcs3/Gui/MainFrame.cpp:5:25: fatal error: git-version.h:

**Comment by thx4ever** [comment]
[ 98%] Linking CXX executable ../bin/rpcs3
CMakeFiles/rpcs3.dir/rpcs3.cpp.o: In function `main':
rpcs3.cpp:(.text.startup+0x0): multiple definition of `main'
CMakeFiles/rpcs3.dir/CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:CMakeCXXCompilerId.cpp:(.text.startup+0x0): first defined here
collect2: error: ld returned 1 exit status
rpcs3/CMakeFiles/rpcs3.dir/build.make:10542: recipe for target 'bin/rpcs3' failed
make[2]: *** [bin/rpcs3] Error 1
CMakeFiles/Makefile2:664: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tambry** [comment]
Please provide the **full log** in English.

**Comment by piotr-szegda** [comment]
Don't enter rpcs3 dir in rpcs3 dir. Just enter cmake CMakeLists.txt and make. Build instruction for Linux is wrong.

**Comment by AniLeo** [comment]
I made a fresh clone and tried to build current master, and it worked.

**Comment by tambry** [comment]
@AniLeo Could you clarify exactly what commands you used?

**Comment by thx4ever** [comment]
I dont know how to apply patch after clone from git repository, can someone show me what to do?

**Comment by tambry** [comment]
What patch? There should be absolutely no need to apply a patch.

**Comment by thx4ever** [comment]
the pull request for linux fix

**Comment by AniLeo** [comment]
git clone https://github.com/rpcs3/rpcs3.git
cd rpcs3
git submodule update --init
cmake CMakeLists && make

**Comment by thx4ever** [comment]
OK fresh clone copy, same error: multiple definition of main
full log: http://pastebin.com/3eaXZY5N

**Comment by jypem** [comment]
CMake is trying to compile both rpcs3.cpp and CMakeCXXCompilerId.cpp into the same executable, so it's also adding CMakeCXXCompilerId.cpp to the build.
I'm guessing the problem is in how source files are added in rpcs3/CMakeLists.txt.
You can try building out of source (into a separate directory), but you'll need to clean the source directory.

Someone having the same problem: http://stackoverflow.com/a/22177285

**Comment by rcaridade145** [comment]
I was able to fix this by telling cmake to ignore  CMakeFiles directory

`set (EXCLUDE_DIR "/CMakeFiles/")
	foreach (TMP_PATH ${RPCS3_SRC})
		string (FIND ${TMP_PATH} ${EXCLUDE_DIR} EXCLUDE_DIR_FOUND)
		if (NOT ${EXCLUDE_DIR_FOUND} EQUAL -1)
			list (REMOVE_ITEM RPCS3_SRC ${TMP_PATH})
		endif ()
	endforeach(TMP_PATH)`

on  rpcs3/CMakeLists.txt

**Comment by rcaridade145** [comment]
I made a commit to my branch of rpcs3 to fix the issue - https://github.com/rcaridade145/rpcs3/commit/c8acc1f5737cc9e06802b972153a8bee0ddadbac . It fixes it for me but i am not sure it is the correct way.

**Comment by TotalCaesar659** [comment]
Lubuntu 16.10 x64, same situation.

[ 98%] Building CXX object CMakeFiles/rpcs3.dir/home/caesar/1/rpcs3/asmjit/src/asmjit/x86/x86inst.cpp.o
[ 98%] Building CXX object CMakeFiles/rpcs3.dir/home/caesar/1/rpcs3/asmjit/src/asmjit/x86/x86operand.cpp.o
[ 98%] Building CXX object CMakeFiles/rpcs3.dir/home/caesar/1/rpcs3/asmjit/src/asmjit/x86/x86operand_regs.cpp.o
[ 98%] Building CXX object CMakeFiles/rpcs3.dir/home/caesar/1/rpcs3/asmjit/src/asmjit/x86/x86scheduler.cpp.o
[100%] Linking CXX executable rpcs3
CMakeFiles/rpcs3.dir/rpcs3.cpp.o: In function `main':
rpcs3.cpp:(.text+0x552): multiple definition of `main'
CMakeFiles/rpcs3.dir/CMakeFiles/3.5.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:CMakeCXXCompilerId.cpp:(.text+0x0): first defined here
/usr/bin/ld: cannot find -lpng16_static
/usr/bin/ld: cannot find -lrsx_decompiler
/usr/bin/ld: cannot find -lshader_code
collect2: error: ld returned 1 exit status
CMakeFiles/rpcs3.dir/build.make:10562: recipe for target 'rpcs3' failed
make[2]: *** [rpcs3] Error 1
CMakeFiles/Makefile2:200: recipe for target 'CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [CMakeFiles/rpcs3.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rcaridade145** [comment]
I was able to overcome that problem by adding 

`set (EXCLUDE_DIR "/CMakeFiles/3.5.2/CompilerIdCXX/")
	foreach (TMP_PATH ${RPCS3_SRC})
		string (FIND ${TMP_PATH} ${EXCLUDE_DIR} EXCLUDE_DIR_FOUND)
		if (NOT ${EXCLUDE_DIR_FOUND} EQUAL -1)
			list (REMOVE_ITEM RPCS3_SRC ${TMP_PATH})
		endif ()
	endforeach(TMP_PATH)
`
to rpcs3/CMakeLists.txt .  This removes CMakeCXXCompilerId.cpp from the path.

**Comment by Nezarn** [comment]
@TotalCaesar659 @rcaridade145 

IDK, what the hell are you guys doing, i've just installed Ubuntu LTS in virtual machine, and build worked. (after manually creating git-version.h, for some reason for me when i used lubuntu\ubuntu it never generated it)
![vmware_2016-10-14_19-35-10](https://cloud.githubusercontent.com/assets/3817985/19396866/61de6040-9245-11e6-86d6-8111b4672bf1.png)

**Comment by TotalCaesar659** [comment]
@rcaridade145, I tried to add it and compile, but unfortunately, there is the same result.

[ 98%] Building CXX object CMakeFiles/rpcs3.dir/home/caesar/1/rpcs3/asmjit/src/asmjit/x86/x86inst.cpp.o
[ 98%] Building CXX object CMakeFiles/rpcs3.dir/home/caesar/1/rpcs3/asmjit/src/asmjit/x86/x86operand.cpp.o
[ 98%] Building CXX object CMakeFiles/rpcs3.dir/home/caesar/1/rpcs3/asmjit/src/asmjit/x86/x86operand_regs.cpp.o
[ 98%] Building CXX object CMakeFiles/rpcs3.dir/home/caesar/1/rpcs3/asmjit/src/asmjit/x86/x86scheduler.cpp.o
[100%] Linking CXX executable rpcs3
CMakeFiles/rpcs3.dir/rpcs3.cpp.o: In function `main':
rpcs3.cpp:(.text+0x552): multiple definition of `main'
CMakeFiles/rpcs3.dir/CMakeFiles/3.5.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:CMakeCXXCompilerId.cpp:(.text+0x0): first defined here
/usr/bin/ld: cannot find -lpng16_static
/usr/bin/ld: cannot find -lrsx_decompiler
/usr/bin/ld: cannot find -lshader_code
collect2: error: ld returned 1 exit status
CMakeFiles/rpcs3.dir/build.make:10562: recipe for target 'rpcs3' failed
make[2]: *** [rpcs3] Error 1
CMakeFiles/Makefile2:200: recipe for target 'CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [CMakeFiles/rpcs3.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Nezarn** [comment]
@TotalCaesar659 

either you didn't do git submodule update --init or git didn't download png, rsx_decompiler and shader_code

**Comment by TotalCaesar659** [comment]
I made git submodule update --init. Maybe it's all because of git. Should I download some libraries by myself?

**Comment by Nezarn** [comment]
Nope, if you have any submodule directory that are empty, just delete them and run git submodule update --init

**Comment by TotalCaesar659** [comment]
Finally, I compiled it :-)
![2016-11-12-135835_900x600_scrot](https://cloud.githubusercontent.com/assets/14265316/20233946/62312846-a886-11e6-941e-123502290c67.png)
If somebody wants to do it, use this instruction https://github.com/RPCS3/rpcs3/pull/1692/files#r62711509 (NOT readme) and before "cmake CMakeLists.txt" create git-version.h in /rpcs3 with this content:
```
#ifndef version_h
#define version_h

#define RPCS3_GIT_VERSION "LOCAL_VERSION"
#define RPCS3_GIT_VERSION_NO_UPDATE 0

#endif // version_h
```
But I've got 2 problems:
1) OpenGL: when I tried to run some .elf like tetris, I've got no graphics
![2016-11-12-140121_1282x708_scrot](https://cloud.githubusercontent.com/assets/14265316/20233953/6e36b160-a886-11e6-82ff-ef6f6942c477.png)
![2016-11-12-140140_1366x708_scrot](https://cloud.githubusercontent.com/assets/14265316/20233955/71cdf3ba-a886-11e6-9afe-ae15827440c2.png)
2) Vulkan: there was no Vulkan in options, but it was initialized by git submodule update --init. This is strange, cause my GPU has support of it.
![screenshot from 2016-11-12 14-06-39](https://cloud.githubusercontent.com/assets/14265316/20233965/8436bd98-a886-11e6-8aed-1f968cf44f32.png)

**Comment by Nezarn** [comment]
@TotalCaesar659 You need to use system's libpng and ffmpeg (you can see in the readme how), and vulkan isn't available in linux version yet.

**Comment by TotalCaesar659** [comment]
> You need to use system's libpng and ffmpeg (you can see in the readme how)

RPCS3 compiled normally only with -DUSE_SYSTEM_LIBPNG=ON.
It shows next with -DUSE_SYSTEM_LIBPNG=ON -DUSE_SYSTEM_FFMPEG=ON:

```
[ 98%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/asmjit/src/asmjit/x86/x86cpuinfo.cpp.o
[ 98%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/asmjit/src/asmjit/x86/x86inst.cpp.o
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/asmjit/src/asmjit/x86/x86operand.cpp.o
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/asmjit/src/asmjit/x86/x86operand_regs.cpp.o
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/asmjit/src/asmjit/x86/x86scheduler.cpp.o
[100%] Linking CXX executable ../bin/rpcs3
/usr/bin/ld: CMakeFiles/rpcs3.dir/__/Utilities/dynamic_library.cpp.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
rpcs3/CMakeFiles/rpcs3.dir/build.make:10540: recipe for target 'bin/rpcs3' failed
make[2]: *** [bin/rpcs3] Error 1
CMakeFiles/Makefile2:244: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

> vulkan isn't available in linux version yet.

New Mesa 13.0 with Vulkan support was recently released, maybe it'll help with it.

> Also be sure to use proprietary drivers.

Unfortunately, I have notebook with AMD Radeon R5 M335, that isn't supported by new AMDGPU-PRO driver. I tried to install it and system didn't launch. That's good that I'm ready to these experiments :-)
So I'll have to wait a progress with open drivers.

**Comment by Nezarn** [comment]
@TotalCaesar659 as i said Vulkan isn't available in rpcs3 linux version (so it doesn't matter if you have vulkan drivers),

**Comment by TotalCaesar659** [comment]
@Nezarn I understood, I meant it will help "in further development", not "right now".
