### ISSUE TITLE
LV2: Unimplemented syscall 988

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1693]
**Games List :** 
* Fist of the North Star: Ken's Rage 
* Fist of the North Star: Ken's Rage 2
* BlazeRush
* Dengeki Bunko: Fighting Climax
* Tales of Graces F
* UNDER NIGHT IN-BIRTH Exe:Late
* The Legend of Korra
* Ni No Kuni: Wrath of the White Witch
* Probably more

`U {PPU[0x1000000] Thread (main_thread) [0x005da3d4]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK
`
**[Log:](https://gist.github.com/SakataGintokiYT/6efa7a878915502b24ac2e8b28513070)**

**Comment by raven02** [comment]
That one is a LV2 syscall .How about if enable 'Load liblv2.sprx only' ?

**Comment by SakataGintokiYT** [comment]
[sys_dbg.cpp]
http://www.psdevwiki.com/ps3/LV2_Functions_and_Syscalls

**Comment by MarioSonic2987** [comment]
Also happens in Saints Row IV [NPEB-01404]

**Comment by MarioSonic2987** [comment]
Adventure Time: Finn and Jake Investigations [NPEB02234] with lle audio, sre, rtc and l10n.

**Comment by Nekotekina** [comment]
Currently it doesn't need implementation. We'll see later.

**Comment by SakataGintokiYT** [comment]
@Nekotekina 
[Updated with current known list of affected games]
Can you try add this syscall ? It would be nice .

**Comment by al0xf** [comment]
A wild guess but sys_dbg_ppu_exception_handler would only get called _after_ something has already gone wrong. That is the game want's to handle some exception that should probably never happen. Therefore it's not important.

**Comment by aakh1361** [comment]
The Tomb Raider Trilogy [BLES01195]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/918743/RPCS3.zip)

**Comment by Ankris** [comment]
Still happening with BLES01976.
