### ISSUE TITLE
D3D Adapter not showing up!

### ISSUE THREAD

**Issue by thvardhan** [RPCS3/rpcs3#1694]
I am on windows 7 64bit with 8Gb ram and a gtx450 card and quad core processor i also have installed Visual c++ needed for emulator
but it seems it cant detect my Graphics card what should i do?

here is a screenshot
http://i.imgur.com/bukkldv.jpg

**Comment by Blaypeg** [comment]
DX12 isnt supported on Windows 7.

**Comment by thvardhan** [comment]
oh! thanks for information! :D

**Comment by samthorin** [comment]
I have the same issue but in the render options i have openGL and Vulkan and none of them show my GPU

**Comment by AniLeo** [comment]
D3D adapter is only for D3D12.
If you're not on Windows 10 then that's not an option.

**Comment by samthorin** [comment]
But then i can play without chosing an d3d adapter? But in loading the game it crashes at the same point of the game

**Comment by AniLeo** [comment]
Again, if you aren't using D3D12 which is only available on Windows 10 you don't need to touch D3D12 adapter, that's why it's disabled. Other renders don't use it.

**Comment by samthorin** [comment]
Thanks. Then i should select null.

**Comment by AniLeo** [comment]
Null on what? You need to either select OpenGL or Vulkan

**Comment by testiosss** [comment]
i have gthe same issue my amd m230 radeon graphic card is not detected. in the render option i got just null and the openGL. I choose the OpenGL and when i launch the game it remain blank

**Comment by testiosss** [comment]
any help?

**Comment by LBPPlayer7** [comment]
What OpenGL version do you have?
(I'm stuck with a GPU that supports neither the version of OpenGL that RPCS3 requires nor Vulkan and I'm on Windows 7)

**Comment by AniLeo** [comment]
Don't revive dead issues, use the forums for discussion

**Comment by LBPPlayer7** [comment]
ok

**Comment by tehranbarco** [comment]
very good
