### ISSUE TITLE
GL/Vulkan: Dai-3-Ji Super Robot Taisen Z Jigoku-hen black screen

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1699]
It works in DX12 backend but Vulkan and OpenGL black screen

![a](https://cloud.githubusercontent.com/assets/3000282/15632128/0e7f8b96-25bb-11e6-8bbf-74f6161d774c.jpg)
![b](https://cloud.githubusercontent.com/assets/3000282/15632129/0ea7214c-25bb-11e6-9316-1ca31cfc4bf9.jpg)

**Comment by raven02** [comment]
The text  in 2nd pic should be white.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/1722 should fix this

**Comment by raven02** [comment]
I just checked out but looks like it  still black screen .

**Comment by kd-11** [comment]
@raven02 Could you please retest with vulkan and the updated pull request? There are some other changes included.

**Comment by raven02** [comment]
Sure @kd-11  .Will check it out right now.

**Comment by raven02** [comment]
Humm still black screen for this game and i can hear the background music is running

**Comment by raven02** [comment]
And i also tested other games and looks like a blue color applied on top .

**Comment by raven02** [comment]
@kd-11 , this is the spriv log generated that i reached the title screen and black screen.

[FragmentProgram.txt](https://github.com/RPCS3/rpcs3/files/291018/FragmentProgram.txt)
[VertexProgram.txt](https://github.com/RPCS3/rpcs3/files/291019/VertexProgram.txt)

**Comment by kd-11** [comment]
@raven02  Your log names are strange; didnt you push a commit to rename the files to .spirv and .glsl?

**Comment by raven02** [comment]
@kd-11 yep i rename it so i can upload here

**Comment by kd-11** [comment]
Doesnt seem to be an issue in the shaders. I'll have to take a deeper look.

**Comment by raven02** [comment]
This game is pretty strange .It boots and FPS shows but black screen however if press L1+R1+SELECT+START at the same time , title screen shows above .LLE i used for booting up this game

l10n
sre
spurs
ssl

**Comment by raven02** [comment]
Wondering would it be flipping issue

**Comment by kd-11** [comment]
I'll need to find a frame debugger that actually works. The amd one crashes. I'll try nsight on my older geforce card.

**Comment by raven02** [comment]
Thanks @kd-11 . From YouTube , i can see when it boots up , it shows the Bandi logo ,CRIWARE logo then a opening movie then title screen.

**Comment by kd-11** [comment]
The input textures during startup are plain black for some reason.

**Comment by kd-11** [comment]
Textures are black because they are never set up or requested at all. I'm not sure if this means they are being written by cell directly to the framebuffers, but that would mean Read/Write buffers has to be properly implemented. This is especially because the first draw call references a render target.

**Comment by raven02** [comment]
Then how about DX12 ? read and write buffers should be implemented somehow.

**Comment by kd-11** [comment]
DX12 crashes if you try to enable read/write buffers with this game. The menu/intro should still work with opengl and vulkan though so that is a valid issue that i'll look into since it is a more straight-forward render.

**Comment by raven02** [comment]
Do you mean opengl with read/write buffer enabled , intro/menu shows up ?

**Comment by kd-11** [comment]
no. I mean that even on dx12, the intro logos do not show up because of that. As for the missing intros on opengl & vulkan, that is a different problem. I'll get to it soon

**Comment by raven02** [comment]
I see. looking forward to your update.

**Comment by kd-11** [comment]
This error is due to vertex attribute issues with ub256 type. I'll submit a fix soon.

**Comment by raven02** [comment]
cool

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pulls/1757 should address this. Please confirm that it works on nvidia driver properly. The text is still green on vulkan but renders correctly with opengl.

**Comment by raven02** [comment]
My one is Nvidia . OpenGL is working now. 

![1](https://cloud.githubusercontent.com/assets/3000282/15879109/9b1eca90-2d53-11e6-9963-1d51a055f7cf.jpg)

**Comment by raven02** [comment]
@kd-11 , btw , do you able to see the Bandi logo ? and also did you able to press L1+R1+Select+Start  everytime successful to get into title screen?

**Comment by kd-11** [comment]
Those wont show up on any renderer due to their r/w buffers behaviour. Its possible that reading fbo contents when creating a new surface may fix this since it seems to place the texture data on the surface targets themselves then start rendering. I'll look into it and update this ticket.

**Comment by kd-11** [comment]
Also, yes, I had to press the button combo to get to main screen.

**Comment by raven02** [comment]
Just wondering u ALWAYS succeed to reach title screen when pressing combo keys as I have 2 or 3 times out of 10 succeed .

**Comment by kd-11** [comment]
I actually press L1+R1+L2+R2+select+start (requires some dexterity at first). Goes to intro every time. I'm not sure what's happening, but then remember that japanese games are sometimes weird, requiring pressing O to select and X to go back instead of the other way round.

**Comment by raven02** [comment]
hmm thanks .I'll try it again . Meanwhile , press 'START' in the following screen (right after press any key at title screen', it is also black screen , probably it is the same issue affected by r/w buffers behavior.
![title](https://cloud.githubusercontent.com/assets/3000282/15889855/72889d08-2d9f-11e6-844d-097fb8803df4.jpg)
