### ISSUE TITLE
PPU interpreter less accurate compared to old builds

### ISSUE THREAD

**Issue by masterkni666** [RPCS3/rpcs3#1713]
I tried comparing the output of 
https://github.com/RPCS3/ps3autotests/tree/master/tests/cpu/ppu_vpu
with  it's excepted output, there seemed to be a huge regression.

Version 0.0.0.6 differed about 15% while the latest build differed by more than 60%.

I tried to use pastebin by their outputs where too big.

The problem doesn't seem to be with the interpreter itself but how data is stored in the VR register.
This is a guess though.

**Comment by Nekotekina** [comment]
This test is broken. It seems that some *integer* values are passed through floating point instructions and getting damaged.
