### ISSUE TITLE
DX12: Hatsune Miku: Project DIVA F color issue

### ISSUE THREAD

**Issue by BlackRocksShooter** [RPCS3/rpcs3#1715]
![dx12 problem](https://cloud.githubusercontent.com/assets/19566893/15532431/19c576d6-2260-11e6-961f-e32fe546bb5d.png)
![dx12 problem 2](https://cloud.githubusercontent.com/assets/19566893/15532488/5fc92556-2260-11e6-99b2-078d0d938132.png)
Since I downloaded RPCS3 using DX12 Render always gives me this problem when I play "always red screen with some blue spots, with exception of the menu section or in some game written"

**Comment by raven02** [comment]
Probably change to title to " DX12: Hatsune Miku: Project DIVA F color issue"

**Comment by Nezarn** [comment]
This is caused by #1653

**Comment by BlackRocksShooter** [comment]
there is a way to solve it? I wanted to ask also if there is a way to save the game Hatsune Miku Project Diva F and then subsequently charge the rescue, so at least when crashes do not have to start all over again

**Comment by raven02** [comment]
@Nezarn , does it mean the red color issue happen right after #1653 ?

**Comment by SakataGintokiYT** [comment]
Fix by Zangetsu38
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp
<img src="http://www.fotoszok.pl/upload/76ced545.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/ef092276.jpg" alt="Fotoszok.pl" />

**Comment by Nezarn** [comment]
@raven02 yep. (reverting only DX12 related stuff in that pr fixes the game)

**Comment by raven02** [comment]
However , ABGR format should be correct . @kd-11 , any insight ?

**Comment by SakataGintokiYT** [comment]
@raven02 
<img src="http://www.fotoszok.pl/upload/6bdedef6.png" alt="Fotoszok.pl" />

**Comment by raven02** [comment]
Alright . @kd-11 , looks good to you if we change to use 0/2/1/0 ? if yes, i can pull a PR for it .

**Comment by tambry** [comment]
3/2/1/0 should be technically correct and probably only needs to be swizzled correctly. There are plenty of other swizzled formats, so you should be able to take a look at them.

**Comment by BlackRocksShooter** [comment]
I do not understand anything about these things xD, more than anything I feel a lot of games, programs (almost a guinea pig for the Test xD) 1-What should I do to what fixare red that torments me? "spegatelo easily, Thanks" 2-i see that some people use the "Load Libraries", which should enable the best place to play this game?

**Comment by SakataGintokiYT** [comment]
>   case CELL_GCM_TEXTURE_W16_Z16_Y16_X16_FLOAT:
>       shared_resource_view_desc.Shader4ComponentMapping = D3D12_ENCODE_SHADER_4_COMPONENT_MAPPING(
>           D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_3,
>           D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_0,
>           D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_1,
>           D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_2);
>       break;

<img src="http://www.fotoszok.pl/upload/58d8404f.png" alt="Fotoszok.pl" />

**Comment by BlackRocksShooter** [comment]
how do I correct colors? I have to use visual studio 2015? and what I have to file open / edit?

**Comment by raven02** [comment]
Try to remap color component depends on RTT or RSX memory then should render the scene correct.

![1](https://cloud.githubusercontent.com/assets/3000282/15580031/aeef6c3c-2399-11e6-95aa-e3b2502c4b14.jpg)

**Comment by BlackRocksShooter** [comment]
excuse me are handicapped as I change, and what I have to open to remap "if someone can help me through chat or Skype I really would like (so I learn something new)"

**Comment by SakataGintokiYT** [comment]
@BlackRocksShooter https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.2306/artifacts

**Comment by BlackRocksShooter** [comment]
I crashed when I tried to access the game menu, but there are the colors right now xD, you can also save the game and reload it?
`{PPU[0x1] Thread (main_thread) [0x009cb00c]} sysPrxForUser TODO: _sys_process_atexitspawn()
{PPU[0x1] Thread (main_thread) [0x009cb12c]} sysPrxForUser TODO: _sys_process_at_Exitspawn
{PPU[0x1] Thread (main_thread) [0x00575ab8]} HLE TODO: Unimplemented syscall sys_ss_get_open_psid -> CELL_OK
{PPU[0x1] Thread (main_thread) [0x009ca42c]} PPU: Function 'cellGameContentPermit' failed with 0x8002cb22 : CELL_GAME_ERROR_FAILURE
{PPU[0x1] Thread (main_thread) [0x009caecc]} cellScreenshot TODO: cellScreenShotSetParameter
{PPU[0x1] Thread (main_thread) [0x009cae8c]} cellScreenshot TODO: cellScreenShotSetOverlayImage
{PPU[0x1] Thread (main_thread) [0x009c9d8c]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
{PPU[0x1] Thread (main_thread) [0x009c9d8c]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
{PPU[0x1] Thread (main_thread) [0x009c9d8c]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
{PPU[0x1] Thread (main_thread) [0x009c9d8c]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
{PPU[0x1] Thread (main_thread) [0x009c9d8c]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
{PPU[0x1] Thread (main_thread) [0x009c9c0c]} cellGcmSys TODO: cellGcmSetQueueHandler
{PPU[0x1] Thread (main_thread) [0x009c9d8c]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
{PPU[0x1] Thread (main_thread) [0x009c9d8c]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
{PPU[0x1] Thread (main_thread) [0x009c9d8c]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
{PPU[0x1] Thread (main_thread) [0x009c952c]} cellUsbd TODO: cellUsbdRegisterExtraLdd
{PPU[0x1] Thread (main_thread) [0x006c9bdc]} sys_fs: sys_fs_open('./dev_ram/user.properties') failed: device not mounted
{SPU[0x11d] Thread (_synth2 Thread) [0x000f0]} SPU: SPU Database initialized...
{SPU[0x11d] Thread (_synth2 Thread) [0x000f0]} SPU: Function detected [0x000f0-0x00178] (size=0x88)
{SPU[0x11d] Thread (_synth2 Thread) [0x000f0]} SPU: SPU Recompiler (ASMJIT) created...
{SPU[0x11d] Thread (_synth2 Thread) [0x00090]} SPU: Function detected [0x00090-0x000e0] (size=0x50)
{SPU[0x11d] Thread (_synth2 Thread) [0x06e20]} SPU: Function detected [0x06e20-0x06e30] (size=0x10)
{SPU[0x11d] Thread (_synth2 Thread) [0x06d28]} SPU: Function detected [0x06d28-0x06e10] (size=0xe8)
{SPU[0x11d] Thread (_synth2 Thread) [0x06580]} SPU: Function detected [0x06580-0x06644] (size=0xc4)
{SPU[0x11d] Thread (_synth2 Thread) [0x05e68]} SPU: Function detected [0x05e68-0x05fa8] (size=0x140)
{SPU[0x11d] Thread (_synth2 Thread) [0x00ab0]} SPU: Function detected [0x00ab0-0x00b5c] (size=0xac)
{SPU[0x11d] Thread (_synth2 Thread) [0x017b8]} SPU: Function detected [0x017b8-0x017ec] (size=0x34)
{SPU[0x11d] Thread (_synth2 Thread) [0x015f0]} SPU: Function detected [0x015f0-0x0164c] (size=0x5c)
{SPU[0x11d] Thread (_synth2 Thread) [0x01660]} SPU: Function detected [0x01660-0x01704] (size=0xa4)
{SPU[0x11d] Thread (_synth2 Thread) [0x04c70]} SPU: Function detected [0x04c70-0x04e90] (size=0x220)
{SPU[0x11d] Thread (_synth2 Thread) [0x02e78]} SPU: Function detected [0x02e78-0x02eb0] (size=0x38)
{SPU[0x11d] Thread (_synth2 Thread) [0x06988]} SPU: Function detected [0x06988-0x069c4] (size=0x3c)
{SPU[0x11d] Thread (_synth2 Thread) [0x06a18]} SPU: Function detected [0x06a18-0x06a30] (size=0x18)
{SPU[0x11d] Thread (_synth2 Thread) [0x089e0]} SPU: Function detected [0x089e0-0x08c20] (size=0x240)
{SPU[0x11d] Thread (_synth2 Thread) [0x069e8]} SPU: Function detected [0x069e8-0x069fc] (size=0x14)
{SPU[0x11d] Thread (_synth2 Thread) [0x06a78]} SPU: Function detected [0x06a78-0x06ab4] (size=0x3c)
{SPU[0x11d] Thread (_synth2 Thread) [0x092f0]} SPU: Function detected [0x092f0-0x09368] (size=0x78)
{SPU[0x11d] Thread (_synth2 Thread) [0x06b20]} SPU: Function detected [0x06b20-0x06ba0] (size=0x80)
{SPU[0x11d] Thread (_synth2 Thread) [0x06a38]} SPU: Function detected [0x06a38-0x06a78] (size=0x40)
{SPU[0x11d] Thread (_synth2 Thread) [0x09298]} SPU: Function detected [0x09298-0x092f0] (size=0x58)
{SPU[0x11d] Thread (_synth2 Thread) [0x072c8]} SPU: Function detected [0x072c8-0x089e0] (size=0x1718)
{SPU[0x11d] Thread (_synth2 Thread) [0x06e30]} SPU: Function detected [0x06e30-0x07038] (size=0x208)
{SPU[0x11d] Thread (_synth2 Thread) [0x05b98]} SPU: Function detected [0x05b98-0x05c3c] (size=0xa4)
{SPU[0x11d] Thread (_synth2 Thread) [0x022b0]} SPU: Function detected [0x022b0-0x023fc] (size=0x14c)
{SPU[0x11d] Thread (_synth2 Thread) [0x002e8]} SPU: Function detected [0x002e8-0x00318] (size=0x30)
{SPU[0x11d] Thread (_synth2 Thread) [0x05788]} SPU: Function detected [0x05788-0x058cc] (size=0x144)
{SPU[0x11d] Thread (_synth2 Thread) [0x07038]} SPU: Function detected [0x07038-0x072c4] (size=0x28c)
{SPU[0x11d] Thread (_synth2 Thread) [0x06710]} SPU: Function detected [0x06710-0x06944] (size=0x234)
{SPU[0x11d] Thread (_synth2 Thread) [0x060e8]} SPU: Function detected [0x060e8-0x0633c] (size=0x254)
{SPU[0x11d] Thread (_synth2 Thread) [0x01d28]} SPU: Function detected [0x01d28-0x022b0] (size=0x588)
{SPU[0x11d] Thread (_synth2 Thread) [0x00d00]} SPU: Function detected [0x00d00-0x0158c] (size=0x88c)
{SPU[0x11d] Thread (_synth2 Thread) [0x024b8]} SPU: Function detected [0x024b8-0x02e78] (size=0x9c0)
{PPU[0x1] Thread (main_thread) [0x009c9dac]} cellGcmSys TODO: cellGcmSetZcull(index=0, offset=0x4480000, width=2048, height=1152, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x207, sRef=0x0, sMask=0xff)
{SPU[0x11d] Thread (_synth2 Thread) [0x05958]} SPU: Function detected [0x05958-0x05988] (size=0x30)
{SPU[0x11d] Thread (_synth2 Thread) [0x00348]} SPU: Function detected [0x00348-0x00380] (size=0x38)
{SPU[0x11d] Thread (_synth2 Thread) [0x01720]} SPU: Function detected [0x01720-0x01768] (size=0x48)
{SPU[0x11d] Thread (_synth2 Thread) [0x06ce8]} SPU: Function detected [0x06ce8-0x06d24] (size=0x3c)
{SPU[0x11d] Thread (_synth2 Thread) [0x06c78]} SPU: Function detected [0x06c78-0x06ce4] (size=0x6c)
{PPU[0x1] Thread (main_thread) [0x009caf6c]} cellRtc TODO: cellRtcGetCurrentTick(pTick=*0xd0057a80)
{PPU[0x1] Thread (main_thread) [0x009caf6c]} cellRtc TODO: cellRtcGetCurrentTick(pTick=*0xd0057a80)
{PPU[0x1] Thread (main_thread) [0x009caf6c]} cellRtc TODO: cellRtcGetCurrentTick(pTick=*0xd0057a80)
{PPU[0x1e3] Thread (thr_bootcheck) [0x009ca4ec]} cellGame TODO: cellGameGetSizeKB
{PPU[0x1e3] Thread (thr_bootcheck) [0x009ca42c]} PPU: Function 'cellGameContentPermit' failed with 0x8002cb22 : CELL_GAME_ERROR_FAILURE
{PPU[0x1e3] Thread (thr_bootcheck) [0x009ca4ec]} cellGame TODO: cellGameGetSizeKB
{PPU[0x1e3] Thread (thr_bootcheck) [0x009ca42c]} PPU: Function 'cellGameContentPermit' failed with 0x8002cb22 : CELL_GAME_ERROR_FAILURE
{PPU[0x1e3] Thread (thr_bootcheck) [0x009ca4ec]} cellGame TODO: cellGameGetSizeKB
{PPU[0x1e3] Thread (thr_bootcheck) [0x009ca42c]} PPU: Function 'cellGameContentPermit' failed with 0x8002cb22 : CELL_GAME_ERROR_FAILURE
{PPU[0x1e4] Thread (thr_install) [0x009cab0c]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0xfe, handle=0xff, reqspace=*0xd0083dd0, options=0x0)
{PPU[0x1e4] Thread (thr_install) [0x009caacc]} sceNpTrophy: sceNpTrophyRegisterContext(context=0xfe, handle=0xff, statusCb=*0xbe3928, arg=*0xef56f8, options=0x1)
{PPU[0x1e4] Thread (thr_install) [0x009cabcc]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0xfe, handle=0xff, flags=*0xef5704, count=*0xef5714)
{PPU[0x1] Thread (main_thread) [0x009caeac]} cellScreenshot TODO: cellScreenShotEnable
{SPU[0x11d] Thread (_synth2 Thread) [0x05750]} SPU: Function detected [0x05750-0x05788] (size=0x38)
{SPU[0x11d] Thread (_synth2 Thread) [0x05c98]} SPU: Function detected [0x05c98-0x05cc0] (size=0x28)
{SPU[0x11d] Thread (_synth2 Thread) [0x01800]} SPU: Function detected [0x01800-0x019d4] (size=0x1d4)
{SPU[0x11d] Thread (_synth2 Thread) [0x059d0]} SPU: Function detected [0x059d0-0x05b98] (size=0x1c8)
{SPU[0x11d] Thread (_synth2 Thread) [0x08d18]} SPU: Function detected [0x08d18-0x08dbc] (size=0xa4)
{SPU[0x11d] Thread (_synth2 Thread) [0x08e90]} SPU: Function detected [0x08e90-0x09098] (size=0x208)
{SPU[0x11d] Thread (_synth2 Thread) [0x09098]} SPU: Function detected [0x09098-0x09204] (size=0x16c)
{SPU[0x11d] Thread (_synth2 Thread) [0x00c78]} SPU: Function detected [0x00c78-0x00cfc] (size=0x84)
{SPU[0x11d] Thread (_synth2 Thread) [0x00398]} SPU: Function detected [0x00398-0x00a9c] (size=0x704)
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/movie/adv.pam') failed: not found
{PPU[0x1] Thread (main_thread) [0x006c9bdc]} sys_fs: sys_fs_open('rom/movie/adv.pam') failed: device not mounted
{PPU[0x1] Thread (main_thread) [0x009c95ac]} cellSysmodule: cellSysmoduleUnloadModule() failed: unknown module 0xFFFF
{PPU[0x1] Thread (main_thread) [0x009c95ac]} cellSysmodule: cellSysmoduleUnloadModule() failed: unknown module 0xFFFF
{PPU[0x1] Thread (main_thread) [0x009c95ac]} cellSysmodule: cellSysmoduleUnloadModule() failed: unknown module 0xFFFF
{PPU[0x1] Thread (main_thread) [0x009c95ac]} cellSysmodule: cellSysmoduleUnloadModule() failed: unknown module 0xFFFF
{PPU[0x1] Thread (main_thread) [0x009ca36c]} cellSaveData: cellSaveDataEnableOverlay(enable=1)
{PPU[0x1] Thread (main_thread) [0x009ca36c]} cellSaveData: cellSaveDataEnableOverlay(enable=0)
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/objset/stgpv/stgpv600hrc.farc') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/objset/stgpv/stgpv600.farc') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/light_param/wind_pv600s01.txt') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/light_param/wind_pv600s02.txt') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/objset/stgpv/stgpv600s01.farc') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/light_param/wind_pv600s03.txt') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/light_param/wind_pv600s04.txt') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/objset/stgpv/stgpv600s02.farc') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/light_param/fog_aetback.txt') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/light_param/glow_aetback.txt') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/light_param/wind_aetback.txt') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/objset/stgpv/stgpv600s03.farc') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/objset/stgpv/stgpv600s04.farc') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/./rom/mothead/mothead_MIK.bin') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/objset/itmpv/itmpv600.farc') failed: not found
{PPU[0x1] Thread (main_thread) [0x009ca36c]} cellSaveData: cellSaveDataEnableOverlay(enable=1)
{PPU[0x1] Thread (main_thread) [0x009ca36c]} cellSaveData: cellSaveDataEnableOverlay(enable=0)
{PPU[0x1] Thread (main_thread) [0x009ca36c]} cellSaveData: cellSaveDataEnableOverlay(enable=1)
{PPU[0x1] Thread (main_thread) [0x009ca36c]} cellSaveData: cellSaveDataEnableOverlay(enable=0)
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/light_param/fog_aetback.txt') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/light_param/glow_aetback.txt') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/light_param/wind_aetback.txt') failed: not found
{PPU[0x1] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/./rom/mothead/mothead_MIK.bin') failed: not found
{PPU[0x102] Thread (200baad0) [0x009c964c]} PPU: Function 'cellFsRead' aborted
{PPU[0x102] Thread (200baad0) [0x009c964c]} class fmt::exception thrown: Win32 error: 998.
(in file C:\rpcs3\Utilities\File.cpp:744)
`

**Comment by kd-11** [comment]
@raven02 @SakataGintokiYT I noticed the fix was to remap WZYX into ARGB in the PR. Is there any other game using this texture format? I'm honestly unsure, i'd have thought that ABGR (3-2-1-0) would be correct. By the way, since the X-Y-Z-W formats appear elsewhere in the rsx code I wonder if they should be re-evaluated as well.

**Comment by raven02** [comment]
i will check out other title to see if this format is also using .

**Comment by danilaml** [comment]
Is this still an issue?
