### ISSUE TITLE
DX12/OGL/Vulkan: Ice Age: Continental Drift - Arctic Games -Invalid location RSX

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1723]
@kd-11 
@raven02 

{rsx::thread} class fmt::exception thrown: rsx::get_address(): Invalid location (offset=0x0, location=0xffffffff)
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:132)

Log : https://gist.github.com/SakataGintokiYT/8ad6f903a73b314d8b07bae8b55a59a0

**Comment by kd-11** [comment]
Is the same exception thrown for DX12 and OGL or just vulkan?

**Comment by SakataGintokiYT** [comment]
@kd-11 The same issue on all API  [ogl/dx12/vulkan]

**Comment by raven02** [comment]
@SakataGintokiYT , does it work in 0.0.0.6? probably regression.

**Comment by SakataGintokiYT** [comment]
@raven02 Nope :P

**Comment by raven02** [comment]
It works very well now in latest build .

![1](https://cloud.githubusercontent.com/assets/3000282/16714722/9e7b866e-46fe-11e6-89ab-0e6cf01e638c.jpg)

**Comment by SakataGintokiYT** [comment]
```
F {rsx::thread} class std::runtime_error thrown: Invalid location (offset=0x0, location=0xffffffff)
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:134)

```
@raven02 
Try port this pull request 
**Major gcm emulation improvements:**
https://github.com/DHrpcs3/rpcs3/commit/0fcacca64350b41f754cc3e109df3d9686b4f45d

**Comment by SakataGintokiYT** [comment]
```
F {rsx::thread} class std::runtime_error thrown: Invalid location (offset=0x0, location=0xffffffff)
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:134)

```

@itmo153277 
Try port this pull request 
**Major gcm emulation improvements:**
https://github.com/DHrpcs3/rpcs3/commit/0fcacca64350b41f754cc3e109df3d9686b4f45d

**Comment by SakataGintokiYT** [comment]
```
F {rsx::thread} class std::runtime_error thrown: Invalid location (offset=0x0, location=0xffffffff)
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:135)

```

**[Log:](https://gist.github.com/SakataGintokiYT/0b07b86a233f785bd40b7b4a390b636a)**

*Same issue: 
#1808
#1487

Can you check this PR :)
**Major gcm emulation improvements:**
https://github.com/DHrpcs3/rpcs3/commit/0fcacca64350b41f754cc3e109df3d9686b4f45d
