### ISSUE TITLE
Regression : version 0.0.0.9

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1725]
Bootup/video intro showup or freeze/hang regression:
- Castlevania : Lords of shadow
- Shoot Many Robots

**Comment by raven02** [comment]
Castlevania : Lords of shadow 2 , it is no longer bootup in 0.0.0.9

{PPU[0x3] Thread (main_thread) [0x00cd9d60]} class std::runtime_error thrown: Verification failed: vm::dealloc(img->segs.addr(), vm::main)
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_spu_.cpp:62)

**Comment by raven02** [comment]
Bomberman ULTRA , also no longer bootup in 0.0.0.9

**Comment by elfogames** [comment]
Bomberman Ultra OpenGL Error

> {PPU[0x4] Thread (main_thread) [0x00163060]} PPU: Function 'sys_net::setsockopt' aborted
{PPU[0x4] Thread (main_thread) [0x00163060]} class fmt::exception thrown: sys_net::setsockopt(): Unknown socket option for Win32: 0x1000
(in file Emu\Cell\Modules\sys_net.cpp:519)

**Comment by mob41** [comment]
@elfogames What I can see with the log you provided, is about the network connectivity, not OpenGL Error.

On the other hand, rpcs3 currently does not support PSN, or network functions.

**Comment by raven02** [comment]
This error is triggered with this PR https://github.com/RPCS3/rpcs3/pull/1670 merged . It also affect other games like DBZ Burst Limit.

**Comment by zminhquanz** [comment]
Disgaea 4 can not booting
{PPU[0x1] Thread (main_thread) [0x0039af28]} cellResc TODO: cellRescSetConvertAndFlip(cntxt=*0x15f4000, idx=0x0)
{PPU[0x1] Thread (main_thread) [0x0039aec8]} cellResc TODO: cellRescSetWaitFlip()

**Comment by raven02** [comment]
Thanks @zminhquanz . Just added to the list.

**Comment by Nezarn** [comment]
@zminhquanz @raven02 it works fine, resc and rtc hle was removed, just enable lle modules.
![2016-06-20_10-56-21](https://cloud.githubusercontent.com/assets/3817985/16188627/c27b9bfe-36d6-11e6-8bcb-8a9626ce1553.png)
![2016-06-20_11-08-07](https://cloud.githubusercontent.com/assets/3817985/16188721/4e974c64-36d7-11e6-8e1d-2bfdfe909251.png)

i used libdmux,libdmuxpamf,libl10n,libresc,librtc,libspurs_jq,libsre.

**Comment by raven02** [comment]
Yep , however it need to use LLE as v0.0.0.6 can boot straight

**Comment by Nezarn** [comment]
@raven02 then you will list every game that uses resc\rtc? lol

**Comment by raven02** [comment]
i mean this game specifically need libdumx+dumxpamf+vdec to bootup but in 0.0.0.6 it can boot up straight with them

**Comment by zminhquanz** [comment]
i'm using LLE module like @Nezarn 
but , it's crash when show intro video, with all API : OpenGL , DX 12 , Vulkan
![image](https://cloud.githubusercontent.com/assets/11285640/16291005/6f9c77de-392c-11e6-8711-34cf572f2f26.png)

**Comment by raven02** [comment]
Updated to exclude Disgaea 3 , 4 and The guided fate paradox as regression and it will be requirement to load up dmux+dmuxpamf+atx+adec

**Comment by SakataGintokiYT** [comment]
**0.0.0.6** 
<img src="http://www.fotoszok.pl/upload/c5dd97ee.jpg" alt="Fotoszok.pl" />

Arcana Heart 3 black screen in latest emulator

**Comment by raven02** [comment]
Both Arkedo 01 and BIT.TRIP Presents... Runner2 are not freezing anymore . fixed by https://github.com/RPCS3/rpcs3/pull/2351

**Comment by raven02** [comment]
Now, Castlevania : Lords of shadow hits sys_spu_image_close abort as below

> E {PPU[0x1000000] Thread (main_thread) [0x00cd9d60]} PPU: 'sys_spu_image_close' aborted
> F {PPU[0x1000000] Thread (main_thread) [0x00cd9d60]} class std::runtime_error thrown: Verification failed (e=0x3): 
> (in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_spu_.cpp:62)

**Comment by digitaldude555** [comment]
![screenshot 816](https://cloud.githubusercontent.com/assets/26138653/23632175/8a95c074-02c9-11e7-9035-af035f9cf9fd.png)

arcana hearts is not black screen anymore.

**Comment by raven02** [comment]
I'm closing this and will open one more specific toward the game itself.

**Comment by kjmn1999** [comment]
hi!
Along with another person.
i had an issue with Jojo's Bizarre Adventure All Star Battle
in which it froze on the loading screens for level select without any errors in the actual game.
If someone could give me a fix then that would be very good.
I'm not really good at analyzing the problem myself as I just started using RPCS3
Thank you

**Comment by AniLeo** [comment]
Is that a regression introduced by version 0.0.0.9?

**Comment by SakataGintokiYT** [comment]
Nope

**Comment by namelyz** [comment]
Hi, I and a few others have the same problem-JoJo's Bizarre Adventure-All Star Battle freezes upon trying to load a level. The menu and character select work fine, but once you attempt to load a level, the screen freezes and does not move. Is there anyway I can fix this? A setting or update? 
Thanks

**Comment by AniLeo** [comment]
Don't spam issues with unrelated discussion

**Comment by namelyz** [comment]
No it was previously mentioned as resolved above but the resolution was unclear or ineffective for me

**Comment by AniLeo** [comment]
Unless it works properly in last 0.0.0.6 build, then it's not related to this issue at all
