### ISSUE TITLE
can it play uncharted series now?

### ISSUE THREAD

**Issue by send2siyad** [RPCS3/rpcs3#1726]
How much should I wait for it 
(Sorry for being childish it's because I desperately want to play that . but unfortunately I lack money for a ps3/ps4). anyways  GREAT WORK GUYS KEEP GOING...

**Comment by AniLeo** [comment]
Read the https://github.com/RPCS3/rpcs3/wiki/FAQ.
Don't open issues like these, use the forums to see the games' current states.

**Comment by send2siyad** [comment]
Sorry for inconvenience 
Can u sent me forum link

**Comment by Altaiar** [comment]
http://www.emunewz.net/forum/forumdisplay.php?fid=162

**Comment by send2siyad** [comment]
Guys I have seen a video by visual redfield in YouTube .In that video he is playing uncharted using rpcs3

**Comment by send2siyad** [comment]
Is it true

**Comment by send2siyad** [comment]
https://m.youtube.com/watch?v=6UgWMCXkvkQ
Check this he is playing it . He made more videos of playing god of war and other games using rpcs3. Is this true

**Comment by SakataGintokiYT** [comment]
Fake

**Comment by raven02** [comment]
Please discuss it in http://www.emunewz.net/forum/forumdisplay.php?fid=162

**Comment by send2siyad** [comment]
www.worldofpcgames.net.....................................guys is the emulator in this websie is legible........it seems to be.....the site claims to be this emulator as a custom rpcs3. they say it works fine....pls check it and reply
the link is http://www.worldofpcgames.net/playstation-3-emulator-free-download-apk/

**Comment by AniLeo** [comment]
@send2siyad Next comment with malware you make you're getting banned from this repository.

**Comment by MoochMcGee** [comment]
@send2siyad Are you stupid?

**Comment by send2siyad** [comment]
@AniLeo if you wanna ban me then go ahead? i ask these questions coz nobody else get cheated........... I DON'T GIVE A SHIT IF YOU BAN ME.

**Comment by AniLeo** [comment]
User was banned from the repository
