### ISSUE TITLE
Hatsune Miku: Project DIVA F -Load Libraries

### ISSUE THREAD

**Issue by BlackRocksShooter** [RPCS3/rpcs3#1730]
I wanted to know what it was for the Load libraries and even if I had to activate these quancuno like to run better for the game Hatsune Miku: Project DIVA F [BLUS31319]

**Comment by Nezarn** [comment]
Game runs fine without LLE, and won't run better if you use any of the LLE libraries. (and maybe it will even run slower, since HLE is faster than LLE.)
