### ISSUE TITLE
DX12/OGL/Vulkan: Hatsune Miku: Project DIVA F missing video intro

### ISSUE THREAD

**Issue by mob41** [RPCS3/rpcs3#1734]
Hi,

I am currently trying to debug/emulate the game ```Hatsune MikuL Project DIVA F (BLUS31319)``` on ```rpc3``` emulator/debugger, using OpenGL.

It boot the credits ```SEGA``` successfully. But after the credits, a blank screen was shown. And the title screen wasn't boot.

I looked up with the logs:

```
{PPU[0x1ee] Thread (Demuxer[0x1ed] Thread)} class fmt::exception thrown: dmuxOpen::<lambda_c5d9be3d6cae12ed21adb310b6b1ef04>::operator ()(): dmuxEnableEs: unknown filter (0xe0, 0x0, 0x0, 0x0)
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellDmux.cpp:678)
```

But from this issue https://github.com/RPCS3/rpcs3/issues/1715 , the game was successfully boot and the player could access to the songs inside.

I thought I am missing something like libraries.

**Comment by mob41** [comment]
Opps, something that I forgot to mention. I tried to resume the emulator/debugger, but the logger just log out a ```TODO```:

```
{PPU[0x1] Thread (main_thread) [0x009c98ec]} cellAdec TODO: *** CellAdecParamAtracX: sr=0, ch_cfg=0(2), frame_size=0x0, extra=0x0, output=132, downmix=0, ats_header=1
```

And the FPS counter keeps flowing.

**Comment by Nezarn** [comment]
It throws exception since certain filter\codec isn't implemented yet, you can work around it by deleting BLUS31319\USRDIR\rom\movie\adv.pam (or just simple rename the whole movie folder.)

**Comment by raven02** [comment]
or use dmux and dmux_pamf.sprx.elf

**Comment by Nezarn** [comment]
@raven02 that just skips the movie and sometimes causing other error msg.

**Comment by mob41** [comment]
Yup it works, is some of the movies will cause a exception again, as the files are "lost"?

**Comment by mob41** [comment]
I think this should be reopened for labeling

**Comment by raven02** [comment]
Any outstanding issue we need to keep it open ? If not , please close it .thanks.

**Comment by Nezarn** [comment]
Intro video isn't playing. So it doesn't work.

**Comment by raven02** [comment]
It did play but requires few more LLE modules

**Comment by Nezarn** [comment]
For me it doesn't play intro even with LLE modules. https://github.com/RPCS3/rpcs3/issues/1734#issuecomment-222520030
