### ISSUE TITLE
[BLUS31319][Hatsune Miku: Project DIVA F] Miku is totally broken and the BGM sound is disgusting

### ISSUE THREAD

**Issue by mob41** [RPCS3/rpcs3#1736]
The log was throwing me some errors like this... seems this errors is caused by the rendering of Miku
```
{rsx::thread} RSX: Texture params are invalid for block starting 0xC8420700!
{rsx::thread} RSX: Params passed w=1024, h=256, mip=1, found w=1024, h=1024, mip=1
{rsx::thread} RSX: Texture params are invalid for block starting 0xC8420700!
{rsx::thread} RSX: Params passed w=1024, h=256, mip=1, found w=1024, h=1024, mip=1
....looping very fast... and luckily I copied these logs successfully
```

:cold_sweat: Miku was just like a ghost....
![broken_miku](https://cloud.githubusercontent.com/assets/12967084/15668575/ac8200fa-274e-11e6-8eb4-29305ec23a46.PNG)

The sound is also broken. Luckily, I can still hear the melody of the BGM. I tried to load ```libsound.sprx.elf``` library, but it doesn't work.

**Comment by mob41** [comment]
== The error is still looping through the logger... even I stop the emulation.

**Comment by Nezarn** [comment]
Sound isn't broken, you just aren't running the game at full speed.

Also its interesting that someone has working 3D models in menu with opengl and dx12 (they are invisible on my 970, for me they are only visible in vulkan (and in vulkan they render correctly))

**Comment by kd-11** [comment]
@mob41 try xaudio2 instead of openal for audio. its usually smoother

**Comment by mob41** [comment]
I tried to use xaudio2, it throws me a unhandled exception

**Comment by mob41** [comment]
*(crashed)

**Comment by kd-11** [comment]
The models in the menu are invisible on opengl for some reason. vulkan should be ok though, especially after https://github.com/RPCS3/rpcs3/pull/1722 gets merged

**Comment by mob41** [comment]
@kd-11 Just tried to install DirectX end-user runtime. The sound is smoother than before a lot, but still have some laggs on the sound.

**Comment by mob41** [comment]
@kd-11 I cannot use Vulkan cause I am using a AMD Graphics card. I tried to use DirectX 12. But my DirectX version is 11.2. Is there a way to update DirectX? Or just wait for Windows Update look after it? (As I ask Google)

**Comment by Nezarn** [comment]
@kd-11 does that fix the scaling? otherwise it works fine on vulkan even now.

@mob41 DX12 is only available on windows 10, and also which AMD card do you have? Most modern AMD cards should work on vulkan

**Comment by mob41** [comment]
*I am on Windows 10.

Lenovo AMD Radeon HD 7450 DVI+DP Graphics Card

**Comment by mob41** [comment]
[Here](https://support.microsoft.com/zh-hk/kb/179113) said that Windows 10 includes DX 11.3 and 12. However, if I need to update DX, I had to wait for Windows Update...

My dxdiag:
![dxdiag](https://cloud.githubusercontent.com/assets/12967084/15670031/d5f8d790-2755-11e6-8390-61fc41709a93.PNG)

**Comment by mob41** [comment]
Looks like my graphics card does not support higher version of DirectX

**Comment by mob41** [comment]
When I tried to use Vulkan:
```
LDR: class fmt::exception thrown: vk::context::createInstance(): Undefined trap
(in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:1055)
```

**Comment by Nezarn** [comment]
your graphics card doesn't support vulkan.

**Comment by mob41** [comment]
Has joystick support implemented yet? Looks like it is impossible to hook joystick inputs into the PAD settings...

**Comment by Nezarn** [comment]
btw this isn't a support forum, so go here and post your questions here

http://www.emunewz.net/forum/forumdisplay.php?fid=163

**Comment by mob41** [comment]
Thanks for your help!
