### ISSUE TITLE
Both slashes (\ and /) being used in Paths

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1739]
```
·! LDR: Path: C:\Users\Studart 2\Downloads\rpcs3-ReleaseLLVM-214d3d0f\dev_hdd0\game\B660IA3\BLES00522/PS3_GAME/USRDIR/BOOT.BIN
·! LDR: Elf path: /host_root/C:\Users\Studart 2\Downloads\rpcs3-ReleaseLLVM-214d3d0f\dev_hdd0\game\B660IA3\BLES00522/PS3_GAME/USRDIR/BOOT.BIN
```
**dev_hdd0\game\B660IA3\BLES00522/PS3_GAME/USRDIR/BOOT.BIN**

As seen here http://www.emunewz.net/forum/showthread.php?tid=174556&pid=231551#pid231551

**Comment by AniLeo** [comment]
```
 ·! LDR: /app_home/ -> C:\Users\Shulk\Desktop\Ps3-Backups\Puyo Puyo Tetris - [BLJM61097]\Puyo Puyo Tetris - [BLJM61097]\PS3_GAME\USRDIR/
```
Also seen here http://www.emunewz.net/forum/showthread.php?tid=173703&pid=231613#pid231613

**Comment by Nekotekina** [comment]
Not really a bug, some parts of path may remain unmodified on Windows. It shouldn't cause any problem.
