### ISSUE TITLE
Unhandled Win32 exception - Xaudio2

### ISSUE THREAD

**Issue by elfogames** [RPCS3/rpcs3#1746]
Any game i try with Xaudio2 i get a Win32 Error,With OpenAL i don't have this problem
![shit](https://cloud.githubusercontent.com/assets/16784631/15803211/08cc7734-2aa9-11e6-8885-0a01fdc50fbb.jpg)

Visual studio stack trace:
> XAudio2_7.dll!00007ffc761ab72c()	Unknown
 XAudio2_7.dll!00007ffc761aadf3()	Unknown
rpcs3.exe!XAudio2Thread::AddData(const void * src, int size) Line 141	C++
 rpcs3.exe!audio_config::on_task() Line 265	C++
 rpcs3.exe!named_thread::start::__l2::<lambda>() Line 1568	C++
 rpcs3.exe!task_stack::task_type<void <lambda>(void) >::exec() Line 44	C++
 rpcs3.exe!thread_ctrl::start::__l2::<lambda>() Line 1311	C++
 [External Code]

**Comment by mob41** [comment]
Install the [DirectX End-User runtime](https://www.microsoft.com/en-us/download/details.aspx?id=7087).

The runtime installer will install "libraries" that you are missing in the computer.

**Comment by mob41** [comment]
See this issue(comment): https://github.com/RPCS3/rpcs3/issues/1736#issuecomment-222634370

And this comment: https://github.com/RPCS3/rpcs3/issues/1736#issuecomment-222636947

**Comment by elfogames** [comment]
Any Other Ideas?

**Comment by Nezarn** [comment]
Have you tried installing\updating your sound"card" driver? Also try updating directx with this https://www.microsoft.com/en-us/download/confirmation.aspx%3Fid%3D35

**Comment by elfogames** [comment]
it's working now,i unistalled the driver,and now im using the microsoft driver
it was a problem with realtek driver

**Comment by elfogames** [comment]
it's back,its a pro

**Comment by elfogames** [comment]
it was a problem with MaxxAudio 4 After all
