### ISSUE TITLE
OGL Core Context

### ISSUE THREAD

**Issue by John-Gee** [RPCS3/rpcs3#1748]
Hello,

Finally my Mesa driver has set OGL as 4.3 and GLSL at 4.30, but without using the override RPCS3 still fails with:
{rsx::thread} RSX: Failed to compile vertex shader: 0:1(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

relevant glxinfo:
OpenGL core profile version string: 4.3 (Core Profile) Mesa 12.1.0-devel (git-d5491a8)
OpenGL core profile shading language version string: 4.30
OpenGL version string: 3.0 Mesa 12.1.0-devel (git-d5491a8)
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 12.1.0-devel (git-d5491a8)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

My understanding is that Mesa only supports more that 3.0 OGL and 1.30 GLSL on a Core Context not a Compatibility one, which may be the issue here. The override seems to bypass that, but I am not sure what other issue it may bring.

This seems related to https://github.com/RPCS3/rpcs3/issues/1028#issuecomment-145299062

Thanks!

**Comment by kd-11** [comment]
Thats interesting, we do request a GL 3.3 core profile, just not a foward compatible one.
If you add a legacy call in the rpcs3 code and enable debug output, you should see the drivers complaining about use of a feature removed from core, even with proprietary drivers.

**Comment by John-Gee** [comment]
I see.
Why not request a 4.3 core profile since it needs 4.30 GLSL anyway?

**Comment by kd-11** [comment]
It seems that mesa ties the glsl and core profile versions rather strictly. Note how the corresponding glsl version 330 is missing from the list of supported glsl versions yet we request a 3.3 profile. Proprietary drivers are fine, but mesa might need some investigating to determine how profile versions are handled. For now, just stick to the override env var.

**Comment by John-Gee** [comment]
I am not sure if it is that strict as I have one override for OGL and one for GLSL and I don't believe one is a superset of the other.
The reason I believe so is at some point one app would crash with the 2 overrides so I played with it, and found that the GLSL was the issue, overriding only the OGL version worked fine.

As for GLSL 3.30, I would have guessed the request was for a compatibility profile, but since you said it is not, I have no clue.

**Comment by John-Gee** [comment]
Well I've just done a little test.
I've checked for GL_ARB_compatibility presence in glGetStringi(GL_EXTENSIONS, n) in GLSLRender.cpp::on_init_thread and I do find it, which should mean that the app requested a compatibility profile.

Other info in the same function:
glGetString(GL_VERSION) => 3.0
glGetString(GL_SHADING_LANGUAGE_VERSION) => 1.30
(glGetString(GL_VENDOR) => X.Org, well this one probably doesn't matter).
which again makes me thing of compatibility profile.

Now I don't know what would happen if the request was for 3.3 compat, if we get 3.0 compat or 3.3 core... I'd guess 3.0 compat but I don't know.

**Comment by kd-11** [comment]
This can happen if your wxwidgets version is below 3.1.0. See https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Gui/GLGSFrame.cpp#L18-Lundefined

It is also possible (but unlikely) that the driver being at 4.3 core fails to support lesser core profiles, in which case we should check the core profile supported before requesting it on mesa. On windows, we do get a proper 3.3 core profile.

**Comment by John-Gee** [comment]
oh damn yes, I went back to 3.0.
I'll go back to 3.1 and report, hopefully sorry about the false alert!

**Comment by John-Gee** [comment]
So yes wx3.1 fixed it.
OGL => 4.3
GLSL => 4.30
Though I still find the GL_ARB_compatibility extension, but since it works fine, I don't need to worry about it.
