### ISSUE TITLE
DX12: LIMBO fragment program compilation failure

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1753]
Build [c4102f3b]

-DX12 : 
-Log : https://gist.github.com/SakataGintokiYT/659a585a740c4713d223d2ea8b319c3f

{rsx::thread} class fmt::exception thrown: D3D12Traits::build_pipeline(): fragment program compilation failure
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)

---

Settings:
-PPU - Interpreter (Fast)
-SPU - Interpreter ASMJIT
-Vulkan / OGL / DX12
-1280x720 
-Xaudio2
-Frame limit OFF

LLE:
-libsre 
-libresc
-librtc

<img src="http://www.fotoszok.pl/upload/c170cbd0.jpg" alt="Fotoszok.pl" />

-Vulkan Log : https://gist.github.com/SakataGintokiYT/dfb4b5b15eca99ceafdac300493bf568
-OGL Log : https://gist.github.com/SakataGintokiYT/78d469bbed21fcc0e73f051f8d122a3f

**Comment by kd-11** [comment]
@SakataGintokiYT In this case, the FragmentProgramXX.hlsl would be of more use than the full log since its only compilation that fails. Just upload a zip archive with the hlsl programs.

**Comment by SakataGintokiYT** [comment]
@kd-11 
Vulkan: http://www57.zippyshare.com/v/w4NSWc1y/file.html
OGL : http://www46.zippyshare.com/v/qXAZs83Y/file.html

**Comment by raven02** [comment]
DX12 reachs title screen then throw exception below

{rsx::thread} RSX: FS build failed:D:\rpcs3\FragmentProgram.hlsl(149,10-35): error X3037: constructors only defined for numeric base types

**Comment by kd-11** [comment]
I have a fix for OpenGL and some of vulkan's issues. Unfortunately it requires that I refactor some of the shared RSX code to make it work. Will push with my next pull request.

**Comment by raven02** [comment]
Looks like this game failed to startup now due to ppu thread create since #1758 - Nevermerge AOT

{PPU[0x4] Thread (main_thread) [0x0031ad24]} HLE: Function 'sys_ppu_thread_create' aborted
{PPU[0x4] Thread (main_thread) [0x0031ad24]} struct vm::access_violation thrown: Access violation reading address 0x0

@Nekotekina .FYI

**Comment by raven02** [comment]
Note: OGL is currently broken while DX12 and Vulkan still fine.

**Comment by raven02** [comment]
Just tested with latest build .It is currently broken using Vulkan backend

{rsx::thread} class fmt::exception thrown: rsx::to_surface_depth_format(): Unknow surface depth format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:991)

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/issues/2155 fixes ogl and vulkan.

**Comment by raven02** [comment]
GL and Vulkan are working prefect now . DX12 issue remain with shader error

E {rsx::thread} RSX: FS build failed:0000000005095eb0
F {rsx::thread} class std::runtime_error thrown: fragment program compilation failure
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)
