### ISSUE TITLE
DX12: Dragon Ball: Raging blast bootup black screen

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1768]
OGL and Vulkan work fine using latest build

- PPU interpreter (fast)
- SPU interpreter (ASMJIT)
- 1280X720
- XAudio2

LLE
- fiber
- sre
- spruqs_jq
- resc
- l10n
- vdec
- smvd2

**Comment by SakataGintokiYT** [comment]
fixed #1766

**Comment by raven02** [comment]
Nice .It also need l10n.sprx.elf after title screen.
