### ISSUE TITLE
DX12/GL/Vulkan: Dragon Ball: Raging blast broken in-game texture

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1769]
All backends should be able to in-game using latest build however in-game texture is heavily broken in all backends

![1](https://cloud.githubusercontent.com/assets/3000282/15985474/e58e0666-3020-11e6-9538-e948605f5d65.jpg)
- PPU interpreter (fast)
- SPU interpreter (ASMJIT)
- 1280X720
- XAudio2

LLE
- fiber
- sre
- spruqs_jq
- resc
- l10n
- vdec
- smvd2

**Comment by kd-11** [comment]
Seems like broken vertex attributes to me. On AMD, the characters are not even visible.

**Comment by MarioSonic2987** [comment]
In https://github.com/RPCS3/rpcs3/commit/e04de77f821be1fcce6a1b01fffab5088c8ef8d9, gives:

DX12/OGL/VK
```
{rsx::thread} class std::runtime_error thrown: Invalid RSX method 0xac00 (arg=0x10800140)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:34)
```
[](http://i.imgur.com/MMK5n77.jpg)
It stop on this part.

**Comment by raven02** [comment]
It work before this commit or regression ?

**Comment by MarioSonic2987** [comment]
Regression.

**Comment by raven02** [comment]
Last working version is ?

**Comment by MarioSonic2987** [comment]
The July builds.

**Comment by raven02** [comment]
Humm it works for me .Not too sure if i'm using another version

![untitled](https://cloud.githubusercontent.com/assets/3000282/17862093/60cca08e-68c6-11e6-8c93-b53955afedf4.jpg)

**Comment by raven02** [comment]
Alright .I also hit it .

```
F {rsx::thread} class std::runtime_error thrown: Invalid RSX method 0xac00 (arg=0x10800140)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:34)
```

**Comment by MarioSonic2987** [comment]
In https://github.com/RPCS3/rpcs3/commit/42835a26d8e069b62f1fe56a41c251a59b999450, it's the same as now. (August 4th).

But in https://github.com/RPCS3/rpcs3/commit/b401bb382acd7c7c2884267ace43522eb9ff86b2, the characters are rendered. (July 26th).
![](http://i.imgur.com/pG6v7mM.jpg)
[LOG DX12 26-7-16](http://www.mediafire.com/download/58y51nqb7uo9isf/LOG_DBRB_26-7-16.rar)

**Comment by raven02** [comment]
@MarioSonic2987 .Those commit links didn't exist (404 erro) . Nevermind .I'll have a quick checkout which commit regressed shortly.

**Comment by AniLeo** [comment]
Can someone please check again?

**Comment by scribam** [comment]
@AniLeo This issue seems to be fixed:
- https://www.youtube.com/watch?v=sI5D5cV6-6g
- https://www.youtube.com/watch?v=m9wHH6NoUXA
- https://www.youtube.com/watch?v=MxepmnOwsxY

**Comment by raven02** [comment]
Justed ,it work very well. Closed
