### ISSUE TITLE
DX12: shader (VS/FS) failed - constructors only defined for numeric base types

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1771]
It looks like happen in few games below with same error from either FS or VS

**Auditorium HD**

> {rsx::thread} RSX: FS build failed:D:\rpcs3\FragmentProgram.hlsl(138,11-44): error X3037: constructors only defined for numeric base types

**Virtual Fighter 5**

> E {rsx::thread} RSX: VS build failedBig C:\Rpcs3\trunk\bin\VertexProgram.hlsl(84,11-38): error X3037: constructors only defined for numeric base types

**Limbo**

> {rsx::thread} RSX: FS build failed:D:\rpcs3\FragmentProgram.hlsl(149,10-35): error X3037: constructors only defined for numeric base types

**Comment by kd-11** [comment]
I'll need a sample hlsl shader that fails to compile. I'm guessing a bad cast is responsible for this, or a decompiler method returning an empty string.

**Comment by raven02** [comment]
@kd-11 , here you are .It is from Auditorium HD

[fragment_shader_log.zip](https://github.com/RPCS3/rpcs3/files/310633/fragment_shader_log.zip)
