### ISSUE TITLE
DX12: Project Diva F title screen crash

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1773]
when i'm back to main menu , it's show the error
![image](https://cloud.githubusercontent.com/assets/11285640/15999285/c073a30a-316e-11e6-98d7-fbc67cb02f52.png)

**Comment by raven02** [comment]
Can it always reproduce eveytime when you reach that menu ? or just occasional

**Comment by zminhquanz** [comment]
Vulkan API is black screen , not display graphic , but i hear the sound

**Comment by zminhquanz** [comment]
i'm using PPU Interpreter 2 , SPU Recompiler ASMJIT , using HLE ( not LLE modules )

**Comment by Nezarn** [comment]
@zminhquanz in vulkan change resolution to 1920x1080, it will be not perfect but you will see most of the stuff. Also post your system info (cpu, ram, gpu).

@raven02 i tried reproducing this issue, but i can't get this error.

**Comment by zminhquanz** [comment]
yeah , i'm using OpenGL , it's lower FPS but there is not error dialog in above

**Comment by zminhquanz** [comment]
i'm forget to talk to you , i'm using monitor 18.5 inch , it's show resolution 1366x768 , so i'm not going to using Vulkan API in this case

**Comment by raven02** [comment]
I also tested with DX12 and it looks okay to me .There is no crash.

**Comment by zminhquanz** [comment]
@raven02 but in my picture , i'm using DX 12 , not Vulkan

**Comment by raven02** [comment]
You said Vulkan black screen .It is becasue of the scaling issue thus you cannot see the texture.

**Comment by zminhquanz** [comment]
i see

**Comment by kd-11** [comment]
@zminhquanz Delete your save data. Loading saves causes games to crash. Savedata can be found at /dev_hdd0/home/savedata/GAME_ID

**Comment by Nezarn** [comment]
@kd-11 in this game saving doesn't even work.(it can't be loaded.) But idk if that would help in his case. I guess his pc simply isn't good enough (getting 4 fps with dx12? wtf?) also he still didn't posted his cpu,gpu, etc.)

**Comment by mob41** [comment]
@raven02 Try to leave the game to run 10-30 minutes or to several hours. The game will crash occasionally. :)

**Comment by AniLeo** [comment]
Post your RPCS3.log file, it should be better that way

**Comment by kd-11** [comment]
@Nezarn @zminhquanz  It is recommended to refuse saving any progress using the emu as of now as it will possibly crash the game during startup. However 4 fps using any backend is just insane. I get 30fps menus in this game using opengl and i'm using an i3 haswell.

**Comment by Nezarn** [comment]
@kd-11 on my PC if i don't save, theres a higher chance getting #1466.

**Comment by zminhquanz** [comment]
@Nezarn you are wrong , when i'm screenshot it's droping FPS , but actually FPS running is 15-20 FPS in menu

**Comment by zminhquanz** [comment]
@Nezarn my CPU
![image](https://cloud.githubusercontent.com/assets/11285640/16028181/eb67c17a-3206-11e6-95c5-c083091350cb.png)

**Comment by zminhquanz** [comment]
@kd-11 i deleted my save , but it's still crash , i have played game before , back to main menu it's crash ( New game not load game )

**Comment by zminhquanz** [comment]
Sometimes , i have this error , going to hang
{PPU[0x102] Thread (200baad0) [0x009c964c]} class fmt::exception thrown: Win32 error: 998.
(in file C:\rpcs3\Utilities\File.cpp:744)
![image](https://cloud.githubusercontent.com/assets/11285640/16028491/0f34e404-320a-11e6-9f76-d0f1bd051733.png)

**Comment by mob41** [comment]
@zminhquanz Please provide the system information (msinfo32.exe > File > Export) and the RPCS3 log file (in the RPCS3 working directory.

**Comment by mob41** [comment]
@zminhquanz You said that that error comes out whenever you got to the menu. But it seems not with the last screenshot you got.

**Comment by zminhquanz** [comment]
@mob41 sometimes it's happen error in last screenshot , but main problem , it's in above begin topic

**Comment by zminhquanz** [comment]
when i get back to main menu it's show error dialog

**Comment by mob41** [comment]
Sorry is last last screenshot to the menu

**Comment by zminhquanz** [comment]
https://gist.github.com/zminhquanz/1a333a0fede291a06365d3aae2121652
My log

**Comment by raven02** [comment]
cellfsread error is a known one which already mentioned here https://github.com/RPCS3/rpcs3/issues/1466
