### ISSUE TITLE
DX12: render to texture wrong color

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1776]
OGL and Vulkan both correct , DX12 got wrong color

[fw_render_to_texture.ppu.zip](https://github.com/RPCS3/rpcs3/files/312064/fw_render_to_texture.ppu.zip)

![1](https://cloud.githubusercontent.com/assets/3000282/16011870/aedb2bcc-31b9-11e6-8c15-73b6a6b279ea.jpg)
![2](https://cloud.githubusercontent.com/assets/3000282/16011871/aedcbb22-31b9-11e6-83aa-b7e57797004f.jpg)
![3](https://cloud.githubusercontent.com/assets/3000282/16011872/aee82836-31b9-11e6-92bb-bc55a0ed2ca5.jpg)

**Comment by kd-11** [comment]
Your title is a little misleading. I think you meant that dx12 is the one with the wrong color not ogl (unless i misunderstood the screenshots)

**Comment by raven02** [comment]
yes sorry typo
