### ISSUE TITLE
DX12: texture format W16_Z16_Y16_X16_FLOAT fix #1777 

### ISSUE THREAD

**Issue by woody2014** [RPCS3/rpcs3#1778]
DX12: texture format W16_Z16_Y16_X16_FLOAT fix #1777 breaks NPEB-01387 How To survive

**Comment by raven02** [comment]
What is NPEB-01387 ?

**Comment by raven02** [comment]
What do you mean by break? color issue or bootup

**Comment by woody2014** [comment]
![screenshot 14](https://cloud.githubusercontent.com/assets/6561856/16046064/030cf05c-3243-11e6-912d-fb3eb515f92d.png)

game stuck on this screen

**Comment by raven02** [comment]
Do you mean master build okay to pass this ?

**Comment by woody2014** [comment]
Downloaded Appveyor build 1.0.2504 DX12: texture format W16_Z16_Y16_X16_FLOAT fix #1777  not booting just frozen on the above point in the picture

**Comment by raven02** [comment]
I just got this trial version to test with the master build .It is the same case that frozen in that scene.

**Comment by woody2014** [comment]
Also Bayonetta

**Comment by woody2014** [comment]
issue still persists on latest appveyor build.

**Comment by raven02** [comment]
latest appveyor build means 
rpcs3-ReleaseLLVM-9d8b0bd7.zip

**Comment by woody2014** [comment]
Also on master build

**Comment by woody2014** [comment]
Found problem shader folder was not transferred over thanks for you help
