### ISSUE TITLE
DX12: Project Diva F hang when pause game

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1780]
![image](https://cloud.githubusercontent.com/assets/11285640/16048608/f15e30c8-327e-11e6-8786-60c6b6b36aa7.png)
![image](https://cloud.githubusercontent.com/assets/11285640/16048657/193daf42-327f-11e6-8893-f4608741a34a.png)

You can see this screenshot

**Comment by raven02** [comment]
same question , this hang can always reproduce ?

**Comment by zminhquanz** [comment]
@raven02 yes , that's it

**Comment by raven02** [comment]
How about OGL ?

**Comment by mob41** [comment]
@zminhquanz I think that you are not running on full speed. This depends on your CPU and graphics card. It also happens on me. Pausing then resume will cause hang for a moment.

**Comment by mob41** [comment]
And can you post system information? Including graphics card. If you are lazy, you can simply dump the info from msinfo32.exe

**Comment by zminhquanz** [comment]
@mob41 i say i'm using Core 2 Quad Q6600 in another topic , can you follow that ?

**Comment by mob41** [comment]
I mean 顯示卡graphics card information. If you couldn't provide those information, it would be difficult to help you.

If your graphics card is not "modern" enough, it would be a bit slow to render and FPS will drops too.

**Comment by zminhquanz** [comment]
@mob41 ok , i will post it

**Comment by zminhquanz** [comment]
@mob41 
https://gist.github.com/zminhquanz/1cd0f9d98220bebcd9ec24af765d74fb
my system infomation

**Comment by Wassaaaa** [comment]
I had the same problem using DX12, solved with Vulkan

**Comment by zminhquanz** [comment]
oh , when i'm using PPU Recompiler on this latest build , the hang was disappeared , so I'm closing it
