### ISSUE TITLE
SPU: unknown command GETLLAR

### ISSUE THREAD

**Issue by supergatto** [RPCS3/rpcs3#1781]
Hi all
There is still this issue on Heavy Rain [BCUS98164] and Grand Theft Auto V [BLES01807]
Logs:
[gta5.zip](https://github.com/RPCS3/rpcs3/files/314590/gta5.zip)
[heavyrain.zip](https://github.com/RPCS3/rpcs3/files/314592/heavyrain.zip)
Thanks.
@raven02

**Comment by raven02** [comment]
Did you get this error if using SPU interpreter (fast) or (ASMJIT) ?

**Comment by supergatto** [comment]
Same error.
Here logs:
[heavyrainASMJIT.zip](https://github.com/RPCS3/rpcs3/files/315884/heavyrainASMJIT.zip)
[heavyrainfast.zip](https://github.com/RPCS3/rpcs3/files/315885/heavyrainfast.zip)
[gta5fast.zip](https://github.com/RPCS3/rpcs3/files/315886/gta5fast.zip)
[gta5ASMJIT.zip](https://github.com/RPCS3/rpcs3/files/315887/gta5ASMJIT.zip)

**Comment by raven02** [comment]
thanks @supergatto

**Comment by supergatto** [comment]
No problem ^^. Thanks for fixing it for free.

**Comment by AniLeo** [comment]
#2360
