### ISSUE TITLE
Arch: cmake not detecting LLVM 3.6

### ISSUE THREAD

**Issue by EIREXE** [RPCS3/rpcs3#1782]
I'm trying to compile the program on Arch however it does not detect LLVM, I manually installed 3.6 from the arch archives.

```
-- cotire 1.7.3 loaded.
-- Initializing RPCS3_SRC_DIR=/home/eirexe/rpcs3/rpcs3
LLVM not found! LLVM 3.6 is required. RPCS3 will be compiled without LLVM support.
-- dir='/usr/lib/wx/include/gtk2-unicode-3.0'
-- dir='/usr/include/wx-3.0'
-- dir='/usr/lib/wx/include/gtk2-unicode-3.0'
-- dir='/usr/include/wx-3.0'
-- dir='/usr/include'
-- dir='/usr/include/AL'
-- dir='/home/eirexe/rpcs3/rpcs3/../3rdparty/pugixml/src'
-- dir='/home/eirexe/rpcs3/rpcs3/../3rdparty/ffmpeg/linux/x86_64/include'
-- dir='/home/eirexe/rpcs3/rpcs3'
-- dir='/home/eirexe/rpcs3/rpcs3/Loader'
-- dir='/home/eirexe/rpcs3/rpcs3/Crypto'
-- dir='/home/eirexe/rpcs3/rpcs3/..'
-- dir='/home/eirexe/rpcs3/rpcs3/../Utilities/yaml-cpp/include'
-- dir='/home/eirexe/rpcs3/rpcs3/../asmjit/src/asmjit'
-- dir='/home/eirexe/rpcs3/rpcs3/../3rdparty/libpng'
-- dir='/home/eirexe/rpcs3/rpcs3/../3rdparty/GSL/include'
-- dir='/home/eirexe/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler'
-- dir='/home/eirexe/rpcs3/rpcs3/../rsx_program_decompiler/shader_code'
-- dir='/home/eirexe/rpcs3/rpcs3/../Vulkan/Vulkan-LoaderAndValidationLayers/include'
-- dir='/home/eirexe/rpcs3/rpcs3/../Vulkan/glslang/glslang/Public'
-- dir='/home/eirexe/rpcs3/rpcs3/../3rdparty/GL'
-- dir='/home/eirexe/rpcs3/rpcs3/../3rdparty/stblib'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eirexe/rpcs3/rpcs3
```

**Comment by tilarids** [comment]
It seems that the LLVM configuration was commented out in CMakeLists.txt in this commit: https://github.com/RPCS3/rpcs3/commit/da7472fe81fadbd4a0188fc238f01204fa884da5

You can fix it manually before building the code (this doesn't guarantee it will compile :) ):

```
diff --git a/rpcs3/CMakeLists.txt b/rpcs3/CMakeLists.txt
index d4416d6..7f3ef07 100644
--- a/rpcs3/CMakeLists.txt
+++ b/rpcs3/CMakeLists.txt
@@ -94,7 +94,7 @@ if(NOT MSVC)
 endif()
 find_package(OpenGL REQUIRED)
 find_package(OpenAL REQUIRED)
-#find_package(LLVM CONFIG) # TODO
+find_package(LLVM CONFIG) # TODO

 include("${wxWidgets_USE_FILE}")
```

**Comment by GhettoGirl** [comment]
I'm also on Arch, and I have LLVM 3.8 installed as system default and 3.6.2 (which is the max supported version by RPCS3) in ```/opt/llvm```. Simple uncommenting the
```cmake
find_package(LLVM CONFIG)
```
isn't enough in this case. It is also required to add the following line before the ```find_package``` line like so:
```cmake
include(/opt/llvm/3.6.2-git~19ade09/share/llvm/cmake/LLVMConfig.cmake)
find_package(LLVM CONFIG)
```

For some reason the ```LLVM_DIR``` variable is ignored.


A other way would be to tell cmake to also look in other directories for cmake files using [CMAKE_MODULE_PATH](https://cmake.org/cmake/help/v3.5/variable/CMAKE_MODULE_PATH.html)

```bash
cmake -DCMAKE_MODULE_PATH="/path/to/llvm-3.6/share/llvm/cmake" .
```

As far as I know LLVM isn't used at the moment anyways, so you can skip it for now ;)

Regards

**Comment by Nekotekina** [comment]
LLVM 3.8 will be used soon, I hope so.

**Comment by EIREXE** [comment]
Alright, i'll try what you posted, thanks!.

**Comment by GhettoGirl** [comment]
@EIREXE LLVM 3.8 is now used as of #1758 got merged into the master branch. You can close this issue now. If it still fails to detect LLVM (in this case 3.8) open another issue.
