### ISSUE TITLE
{rsx::thread} class std::logic_error thrown: fs::file is null

### ISSUE THREAD

**Issue by Ekaseo** [RPCS3/rpcs3#1784]
almost all games show this error:
{rsx::thread} class std::logic_error thrown: fs::file is null

here is a log file from the guided fate paradox with both vulkan and dx12 (every game shows me this error in every backend)

https://www.sendspace.com/file/df58l4

**Comment by SakataGintokiYT** [comment]
@Ekaseo 
<img src="http://www.fotoszok.pl/upload/f910c38f.jpg" alt="Fotoszok.pl" />

**Comment by Ekaseo** [comment]
oh, thnx, it works now

**Comment by AshThatBurns** [comment]
Sorry to necro this post, but I'm really trying to make this run...
I'm using Vulkan and I'm getting this error when I run Persona 5
I have the shaderlog folder in my install dir and it has a bunch of files called FragmentProgram
Help much appreciated ^^

**Comment by SakataGintokiYT** [comment]
@AshThatBurns 
Right click on the game icon / Delete Shaders Cache

**Comment by AshThatBurns** [comment]
Yes, it works! Thanks so much!! ^^

**Comment by Schoenenrek** [comment]
i have this error to but i can't delete shaders cache
![can't click](https://user-images.githubusercontent.com/48533749/54315033-7be1df00-45dd-11e9-8204-e24346a0710d.jpg)
