### ISSUE TITLE
DX12/OGL/Vulkan: Ethan: Meteor Hunter missing textures

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#1785]
Afaik this game goes ingame with same blacky enviroment.It's the same at all of backends.Mostly only text or HUD is visible.

**PS3:**

![ethan 3](https://cloud.githubusercontent.com/assets/11453507/16085513/99480546-331c-11e6-9ca2-2c52e007d46e.PNG)

**RPCS3 OGL:**

![ethan 1](https://cloud.githubusercontent.com/assets/11453507/16085491/8b937f48-331c-11e6-8204-3aaacf27788b.PNG)

![ethan 2](https://cloud.githubusercontent.com/assets/11453507/16085524/a1bb18b2-331c-11e6-9fae-8b47d23f8273.PNG)

[LOG](https://mega.nz/#!GVtGRbRS!rYsbuzdlE8FF2jBdbqFlCdC-0Au4ZAP8uuTPAaXfIk0)

**Comment by raven02** [comment]
How about Vulkan?

**Comment by SakataGintokiYT** [comment]
@raven02 
same

**Comment by raven02** [comment]
thanks

**Comment by raven02** [comment]
I just tested it . It looks all the same broken in all backends.

**Comment by raven02** [comment]
This is the 'Press start' screen from PS3

![1](https://cloud.githubusercontent.com/assets/3000282/16106853/d05e8af6-33ca-11e6-961b-4542297e2a1a.jpg)
