### ISSUE TITLE
Linux/OGL: nvidia optimus (bumblebee) not working with ppsspp-ffmpeg, but with system ffmpeg

### ISSUE THREAD

**Issue by magiruuvelvet** [RPCS3/rpcs3#1794]
I'm curious if the OpenGL backend even supports NVIDIA optimus using the Bumblebee Project. It seems that the OGL backend never initializes; it's just an empty (buggy?) window. None of the games which are playable/half-playable/intro I tried are ever rendering something on screen. The games doesn't even start. When I set the graphic backend to _Null_ the games more or less works to the point they are working (sound, etc.)

``` bash
optirun -b virtualgl ./rpcs3
optirun -b primus ./rpcs3
primusrun ./rpcs3
```

None of these above works, the results are always the same

![screenshot_20160618_143206](https://cloud.githubusercontent.com/assets/13280758/16170885/dee10138-3561-11e6-94c3-3835900cf9a8.png)
As you can see in the screenshot, the content of the window is frozen and shows a snippet of the desktop.

![screenshot_20160618_145152](https://cloud.githubusercontent.com/assets/13280758/16170972/474c3b50-3564-11e6-94d1-eca74b85d08b.png)
With the "Null" backend games start and I can hear sound.

I can't use the Intel card, because it uses OpenGL 3.0 which isn't supported according to the tons of shader compiler errors RPCS3 gives me.

```
glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.2.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

optirun glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 980M/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 367.27
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.0 NVIDIA 367.27
OpenGL shading language version string: 4.50 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
```

My actual question now: Does RPCS3's OpenGL implementation doesn't support NVIDIA optimus or is this a "bug"?

**Comment by GhettoGirl** [comment]
I did some more tests using a plain standalone X11 server (without Window Manager or Compositor).

The **[primus](https://github.com/amonakov/primus) backend** ```primusrun | optirun -b primus``` never ever creates a new window and emulator freezes, game never starts, etc.
SIGKILL to the rescue

The **[VirtualGL](http://virtualgl.org/) backend** ```optirun | optirun -b virtualgl``` is able to create a white window. But this window never updates (missing GL flushes??). Games start and act normal, sound is playing and probably input too (I didn't tested input).

My best guess is that the OGL backend of RPCS3 doesn't like how frames are transfered from one X server to another using frame compression.

Two questions:

**Does RPCS3 use some kind of acceleration (DRM)?**
**[Bumblebee](https://github.com/Bumblebee-Project/Bumblebee)** doesn't support this: [1](https://github.com/Bumblebee-Project/Bumblebee/issues/735) [2](https://github.com/amonakov/primus/issues/23)

**Is this behaviour fixable? aka. Will RPCS3 ever be able to run on optimus laptops?**

---

from the Bumblebee wiki
> How it works?
> The Bumblebee server disables the discrete video card if no client is detected (if power management is enabled which is the default setting). This is done by keeping track of programs that request Bumblebee to run themselves on the discrete nvidia card. On such requests, a X server is started which makes use of the nvidia card. Because the frames cannot directly be displayed on the display due to the Optimus design, VirtualGL was used to copy frames to the visible display which runs on the integrated Intel GPU. It has now been replaced by a more adapted solutions, primus.

---

I don't have a PC or another laptop to play around with RPCS3. Maybe mark this issue as long "longterm" or "enhancement" or both?
Anyways, I'm looking forward to this project, it's still in early stage and improves with the time :) Keep up this great work developers.

Regards

**Comment by GhettoGirl** [comment]
**Even more testing!**

I'm currently trying out different configurations for wxWidgets (submodule) and I have indeed some interesting results.

First I found out that ArchLinux comes with a version of wxWidgets which uses Gtk2.0 and with OpenGL *disabled*.

With a build of wxWidgets with OpenGL and SDL and Gtk3.0 the window at least is not frozen, but the games still does not start. But Gtk3.0 indroduces a lot of other problems, like SEGFAULT when attempting to use ```libpng16.so.16```. The linker mixed up something and the static and shared libpng are in conflict.

I'm now trying other configurations of wxWidgets with Qt and Gtk2.0 with shared and static linking.

May I ask what GUI backend you are using on Windows for wxWidgets?

**Comment by paulsapps** [comment]
That libpng stuff has been mentioned before, the real fix is to use static libpng for the HLE stuff and let WxWidgets use the dynamic version for its stuff

**Comment by GhettoGirl** [comment]
**RPCS3 bumblebee fix**

---
**[rpcs3-system-libs.patch](https://aur.archlinux.org/cgit/aur.git/tree/rpcs3-system-libs.patch?h=rpcs3-git)** old version

---
**new version**
```diff
--- CMakeLists.txt	2016-06-22 09:36:03.000000000 +0200
+++ CMakeLists.txt	2016-06-24 16:42:11.296053368 +0200
@@ -17,7 +17,6 @@
 
 add_definitions(-DCMAKE_BUILD)
 
-add_subdirectory( 3rdparty/libpng )
 # TODO: do real installation, including copying directory structure
 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${PROJECT_BINARY_DIR}/bin")
 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${PROJECT_BINARY_DIR}/bin")

--- rpcs3/CMakeLists.txt	2016-06-22 09:36:03.000000000 +0200
+++ rpcs3/CMakeLists.txt	2016-06-24 16:41:46.986052976 +0200
@@ -112,14 +112,13 @@
 ${OPENAL_INCLUDE_DIR}
 ${LLVM_INCLUDE_DIRS}
 "${RPCS3_SRC_DIR}/../3rdparty/pugixml/src"
-"${RPCS3_SRC_DIR}/../3rdparty/ffmpeg/${PLATFORM_ARCH}/include"
+"/usr/include"
 "${RPCS3_SRC_DIR}"
 "${RPCS3_SRC_DIR}/Loader"
 "${RPCS3_SRC_DIR}/Crypto"
 "${RPCS3_SRC_DIR}/.."
 "${RPCS3_SRC_DIR}/../Utilities/yaml-cpp/include"
 "${RPCS3_SRC_DIR}/../asmjit/src/asmjit"
-"${RPCS3_SRC_DIR}/../3rdparty/libpng"
 "${RPCS3_SRC_DIR}/../3rdparty/GSL/include"
 "${RPCS3_SRC_DIR}/../rsx_program_decompiler/rsx_decompiler"
 "${RPCS3_SRC_DIR}/../rsx_program_decompiler/shader_code"
@@ -152,10 +151,6 @@
 "${RPCS3_SRC_DIR}/../3rdparty/minidx12/"
 )
 
-if(MSVC OR NOT WIN32)
-	link_directories("${RPCS3_SRC_DIR}/../3rdparty/ffmpeg/${PLATFORM_ARCH}/lib")
-endif()
-
 get_property(dirs DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY INCLUDE_DIRECTORIES)
 foreach(dir ${dirs})
   message(STATUS "dir='${dir}'")
@@ -198,7 +193,7 @@
 	target_link_libraries(rpcs3  avformat.lib avcodec.lib avutil.lib swresample.lib swscale.lib png16_static ${wxWidgets_LIBRARIES} ${OPENAL_LIBRARY} ${ADDITIONAL_LIBS})
 else()
 	target_link_libraries(rpcs3  ${wxWidgets_LIBRARIES} ${OPENAL_LIBRARY} ${GLEW_LIBRARY} ${OPENGL_LIBRARIES})
-	target_link_libraries(rpcs3  libavformat.a libavcodec.a libavutil.a libswresample.a libswscale.a -ldl png16_static ${ZLIB_LIBRARIES} ${ADDITIONAL_LIBS})
+	target_link_libraries(rpcs3  libavformat.so libavcodec.so libavutil.so libswresample.so libswscale.so libpng16.so ${ZLIB_LIBRARIES} ${ADDITIONAL_LIBS} ${vulkan} ${glslang})
 	if (NOT APPLE)
 		target_link_libraries(rpcs3  vulkan glslang OSDependent OGLCompiler SPIRV)
 	endif()

```

**Problem:** [this](https://github.com/hrydgard/ppsspp-ffmpeg) ffmpeg static build in particular! it works for PPSSPP (for me it works with bumblebee), but not for RPCS3 on Linux.
This fix is so simple as replacing *ppsspp-ffmpeg* with the system ffmpeg and also removing the *libpng* dependency on ArchLinux since it uses the latest version anyway.

Now the developers can investigate in the **future** why this ffmpeg static build fails so hard on the linux build of RPCS3.

I'm leaving the issue open, aswell I'm changing the title to reflect the real problem here.

Regards

PS: now I can play some PS3 games on my nvidia optimus laptop, no more a frozen GLFrame
PSS: developing on linux is very different from developing on windows. I know that, since I'm a developer by myself :)

**Comment by GhettoGirl** [comment]
proof :)

![screenshot_20160624_171106](https://cloud.githubusercontent.com/assets/13280758/16341700/c6570cb2-3a2e-11e6-8714-4c54fe1e3c7a.png)
![screenshot_20160624_171120](https://cloud.githubusercontent.com/assets/13280758/16341704/c870b55c-3a2e-11e6-8c80-0d74098256c4.png)
![screenshot_20160624_171144](https://cloud.githubusercontent.com/assets/13280758/16341705/c9e01f04-3a2e-11e6-9c7e-d2d1686f7f9a.png)

**Comment by raven02** [comment]
@GhettoGirl , can the intro video above from beginning to end?

**Comment by GhettoGirl** [comment]
@raven02 no, it only plays the first 5 seconds than freezes, but i can skip it (btw input works) and enter the main menu and also create a new savegame
logs can be found here #1821

**Comment by raven02** [comment]
Alright .same here.

**Comment by paulsapps** [comment]
Erm isn't this just because of it wanted 2 dynamic versions of libpng? So the real fix is to statically link the one the emu uses and not the one wxwidgets wants?

**Comment by GhettoGirl** [comment]
@paulsapps The linker did linked against the static **AND** the dynamic libpng at the same time. But the actual problem here is ppsspp-ffmpeg which causes breakage for bumblebee. When using the system ffmpeg by modifying the ```CMakeLists.txt``` solves this problem. The strange is that ppsspp-ffmpeg is working in PPSSPP with bumblebee. Maybe the modified ffmpeg is used "wrong". Anyway PPSSPP != RPCS3 so it could be a totaly different problem which causes the OpenGL backend to never initialize/freeze.

**Comment by paulsapps** [comment]
Is ppsspp-ffmpeg a so or a static lib? if its a so then it probably depends on something else which is another version conflict.

**Comment by GhettoGirl** [comment]
> Is ppsspp-ffmpeg a so or a static lib? if its a so then it probably depends on something else which is another version conflict.

It is a static lib.

**Comment by paulsapps** [comment]
eee - well that's pretty strange then

**Comment by magiruuvelvet** [comment]
Qt magically fixed all bumblebee and nvidia optimus issues (could also be something else maybe). Really weird but the emu works again for me after a very long time. Really like the Qt port :+1: 
I personally dislike wxWidgets tbh
