### ISSUE TITLE
Fedora: unable to find wxWidgets 3.0 when trying to build 

### ISSUE THREAD

**Issue by 7oxicshadow** [RPCS3/rpcs3#1797]
Currently trying to build this on Fedora 23 and have run into a bit of a stumbling block.

On Fedora it does not successfully find Wxwidgets 3.0 even though wxGTK3-devel is installed correctly. Digging deeper it seems that FindwxWidgets.cmake file is looking for wx-config but on Fedora wx-config is for wxwidgets2.8 and there is a second file called wx-config-3.0 for wxwidgets3.0.

If i install wxGTK-devel the CMake passes fine and the build gets to about 68% and falls over because of some conversion issues between char[] and wxwidgets types. The cmake shows that it is pointing to the 2.8 directory and not the 3.0 directory for wxwidgets.

Is there a command to force the build script to look elsewhere for wxwidgets?

**Comment by 7oxicshadow** [comment]
update.

I uninstalled wxgtk-devel and created a symlink called wx-config that points to wx-config-3.0 and rpcs3 emulator built successfully.

This seems to validate my theory

**Comment by AniLeo** [comment]
RPCS3 uses wxWidgets 3.1 though, not sure if it compiles with 3.0

**Comment by AniLeo** [comment]
This is no longer an issue since we switched from wxWidgets to QT. 
If you have any new issues compiling with QT, please open an issue.
