### ISSUE TITLE
Save /Auto Save  Issue 

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1804]
*Games freezes by write error :

##### BIT.TRIP Presents... Runner2: Future Legend of Rhythm Alien
-{PPU[0xd1] Thread (save) [0x0028c9b8]} cellSaveData: Savedata NPEB00947-RUNNER2 considered broken
LOG : https://gist.github.com/SakataGintokiYT/690a806bfe935805dc09f10fb05ebf86
_______________________________________________________________________________

##### Legend of Kay Anniversary
-{PPU[0x76] Thread (svdatmgr) [0x0036fa70]} cellSaveData: cellSaveDataUserListAutoLoad(version=1, userId=1, errDialog=0, setList=*0xd0074afc, setBuf=*0x22878284, funcFixed=*0x43f820, funcStat=*0x43f828, funcFile=*0x43f830, container=0xffffffff, userdata=*0xd0074af0)
-{PPU[0x76] Thread (svdatmgr) [0x0036fab0]} cellSaveData: cellSaveDataUserAutoSave(version=1, userId=1, dirName=*0xd0074c62, errDialog=1, setBuf=*0x22878284, funcStat=*0x43f840, funcFile=*0x43f848, container=0xffffffff, userdata=*0xd0074ccc)
-{PPU[0x76] Thread (svdatmgr) [0x0036fab0]} cellSaveData: Savedata NPEB02143_00_00 considered broken
-{PPU[0x76] Thread (svdatmgr) [0x0036fab0]} cellSaveData: cellSaveDataUserAutoSave(version=1, userId=1, dirName=*0xd0074b10, errDialog=2, setBuf=*0x22878284, funcStat=*0x43f850, funcFile=*0x43f858, container=0xffffffff, userdata=*0xd0074b40)

*LOG : https://gist.github.com/SakataGintokiYT/9d713ec8f605a28475b78c9b837878a5

**Comment by raven02** [comment]
Any specific lines of error related to save/load that trigger the freeze ?

**Comment by raven02** [comment]
Can this be easily reproduce ? .i.e . always freeze when trigger game save

**Comment by SakataGintokiYT** [comment]
@raven02 
Runner 2 not freezes for you ?

**Comment by raven02** [comment]
Let me test it tonight for Runner 2

**Comment by raven02** [comment]
Yes , it also freeze for me for every render backends and PPU/SPU options

**Comment by raven02** [comment]
@SakataGintokiYT  can you help this test version again to see if any freeze ? which is the last commit before 0.0.0.9 

https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.2134/artifacts

**Comment by SakataGintokiYT** [comment]
@raven02  
@Nekotekina 

Not problem with save data 
On 0.0.0.6 works good and not freeze   ;/
Runner2 
Legend of Kay Anniversary  [ i can continue game]

**Comment by raven02** [comment]
I see. so it is a 0.0.0.9 regression.

**Comment by SakataGintokiYT** [comment]
@DHrpcs3  Try to fix it :)  /cellSaveData

**Comment by SakataGintokiYT** [comment]
*[ update ]

**Comment by raven02** [comment]
I will put this in the regression list and closing it .
