### ISSUE TITLE
DX12: Way of the Samurai 3 freeze/crash

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1805]
<img src="http://www.fotoszok.pl/upload/043fa3c5.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/196f3151.jpg" alt="Fotoszok.pl" />

Settings:
-PPU - Interpreter 2
-SPU - Interpreter ASMJIT
-DX12 / OGL / Vulkan
-1280x720 
-VSync
-XAudio

LLE:
-libresc 
-librtc
-libsre
-libsail
-libpamf

LOG : https://gist.github.com/SakataGintokiYT/c9879ca07cbaa22a4a44a1214380b183

**Comment by raven02** [comment]
Just wonder what is the exact problem here?  hang/freeze

**Comment by SakataGintokiYT** [comment]
Freeze and crash

**Comment by raven02** [comment]
Alright . so it happen in all backends, right?

**Comment by SakataGintokiYT** [comment]
<img src="http://www.fotoszok.pl/upload/64d3ff7e.jpg" alt="Fotoszok.pl" />

**Comment by MoochMcGee** [comment]
@SakataGintokiYT Please use SPU Interpreter 2 instead of ASMJIT, as others have told you in the past. The suggested backend is more accurate and more likely to work.

**Comment by MarioSonic2987** [comment]
Is this still an issue?

**Comment by digitaldude555** [comment]
Yes.
