### ISSUE TITLE
GL/Vulkan: Worms Ultimate Mayhem

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#1808]
Graphical issues:

- [x] Missing shadows - Probably fixed in September 2018.
- [x] Missing/flickering particles (smoke) - Fixed in #5860
- [x] Broken models

<details>
 <summary>Original comment</summary>

Tested on (https://github.com/RPCS3/rpcs3/commit/02760149c94413f57136b9945c7315716ddc6465)
**Core:**
- PPU: Interpreter (precise)
- SPU: Interpreter (precise)
- LLE: CellRtc

**Graphics:**
- Vulkan (In DX12, worm's polygons are flashing. In OpenGL, black screen in menu.)
- 1280x720
- 16:9
- Auto
- VSync

**Graphic card: NVIDIA GeForce GTX 970**

**Audio:**
- XAudio2 (There is no sound).

[Log Vulkan](http://www.mediafire.com/download/jfb33fwig9p6b1f/LOG+WUM+PS3.rar) (I uploaded it in MediaFire)

![](http://i.imgur.com/X7ArJ0r.png)
![](http://i.imgur.com/XAOIhHg.jpg)
</details>

**Comment by raven02** [comment]
So texture flashing in both DX12 and Vulkan , right?  How about OpenGL

**Comment by MarioSonic2987** [comment]
In OpenGL, black screen in the menu. In DX12, the models are messed up. In Vulkan and DX12, the particles are flashing.

**Comment by MarioSonic2987** [comment]
About the models in Vulkan, occurs the same as DX12, but some specific models (the book in Story).

**Comment by raven02** [comment]
Alright . Thanks for the update .

**Comment by MarioSonic2987** [comment]
In 0.0.0.6:

- DX12: Same as now. [Log DX12 0.0.0.6](http://www.mediafire.com/download/t4ez6ggjdy6bc5v/LOG+WUM+DX12+0.0.0.6.rar)

- OpenGL: Same as Vulkan (in the latest build), but with a darker sky and a alpha problem in particles (An invisible square around the texture). [Log OpenGL 0.0.0.6](http://www.mediafire.com/download/jcxqp82fgla7i8p/LOG+WUM+OGL+0.0.0.6.rar)

- Vulkan: Same as OpenGL, without the darker sky. [Log Vulkan 0.0.0.6](http://www.mediafire.com/download/h7gdi2hukhsdhz7/LOG+WUM+Vulkan+0.0.0.6.rar)

**Comment by MarioSonic2987** [comment]
A picture of PC version as reference.
![](http://i.imgur.com/HKjYl0l.jpg)

**Comment by MarioSonic2987** [comment]
# Update

- In OpenGL, the black screen bug is fixed, but there are darker shadows in water. And the models are flashing even worse than DX12. [Log OpenGL](http://www.mediafire.com/download/dc1yxj60at0771v/LOG+WUM+OGL+24-6-16.rar)
![](http://i.imgur.com/ulHfg8T.jpg)
![](http://i.imgur.com/5Bjx8hG.jpg)
- In DX12 and Vulkan, it's the same, respectively. [Log DX12](http://www.mediafire.com/download/pb9czpnql8koivk/LOG+WUM+DX12+24-6-16.rar)
[Log Vulkan](http://www.mediafire.com/download/ksd2kp0095dogh2/LOG+WUM+Vulkan+24-6-16.rar)

**Comment by MarioSonic2987** [comment]
# Update (17-7-16)
In (https://github.com/RPCS3/rpcs3/commit/4c69bfa8d3baefe3d07be80287b4cb78c0a85f05), it goes ingame in Vulkan with the same issues and there's no shadow. Save works perfectly.
[Log Vulkan 17-7-16](http://www.mediafire.com/download/nd9w24v2amm9b99/Log+WUM+17-7-16.rar)
![](http://i.imgur.com/nWvODzZ.jpg)

**Comment by MarioSonic2987** [comment]
In https://github.com/RPCS3/rpcs3/commit/bb66b972517761044e8401c1c0871c15ec08b749, this game no longer goes ingame. It outputs:
```
{SPU[0x2a] Thread (CellSpursKernel1) [0x1a918]} class std::runtime_error thrown: Unknown STOP code: 0x0 (Out_MBox is empty)
(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1387)
```
![](http://i.imgur.com/OSp4jq7.png)
It stops in loading screen,

**Comment by raven02** [comment]
Can you please check which commit is the last working one?

**Comment by MarioSonic2987** [comment]
In https://github.com/RPCS3/rpcs3/commit/ae634bb87ed9dcadb0cbc9fc79f254a66cab5a6a.

**Comment by raven02** [comment]
Thanks .Will check it out .It is Vblank change.

**Comment by MarioSonic2987** [comment]
Before, it spamed:
```
·E {PPU[0x70000000] Thread (main_thread) [0x00bc6150]} sys_memory: sys_memory_get_page_attribute(addr=0xd001f158, attr=*0xd001f090)
·E {PPU[0x70000000] Thread (main_thread) [0x00bc619c]} sys_memory: sys_memory_get_page_attribute(addr=0xd001f150, attr=*0xd001f090)
·E {PPU[0x70000000] Thread (main_thread) [0x00bc9874]} sys_memory: sys_memory_get_page_attribute(addr=0xd001ee90, attr=*0xd001edf0)
```

**Comment by MarioSonic2987** [comment]
Selecting LLE module Audio, it works again to menu.
![](http://i.imgur.com/eXHC78N.jpg)

**Comment by raven02** [comment]
Nice .

**Comment by MarioSonic2987** [comment]
I cannot get ingame. But in GL, the models aren't flashing.

**Comment by raven02** [comment]
i see

**Comment by MarioSonic2987** [comment]
Should I upload the shader log?

**Comment by MarioSonic2987** [comment]
@raven02 
[Shader log Vulkan](http://www.mediafire.com/download/ma2hm3xc9cu17h8/Shader_Log_WUM_25-9-16.rar)
Tested in https://github.com/RPCS3/rpcs3/commit/fcb853792d5f535271bce638f8ea47fa3a6b8c1c

**Comment by MarioSonic2987** [comment]
In the latest master, OGL/DX12/VK are almost the sale.

**Comment by MarioSonic2987** [comment]
@kd-11 @raven02 
[RenderDoc Vulkan](http://www.mediafire.com/file/m9xoxd6fa3i4anr/Renderdoc_WUM_VK.rar)

**Comment by MarioSonic2987** [comment]
Texture format of the problematic particle is B8G8R8A8
![](http://i.imgur.com/KUN4Ond.png)

**Comment by kd-11** [comment]
Its kinda difficult to debug this one since I have no idea what it looks like when running. Link to a video perhaps? or screenshots showing the corruption.

**Comment by MarioSonic2987** [comment]
https://www.youtube.com/watch?v=7AuJl4dK_NA - Video

**Comment by kd-11** [comment]
Thanks. Looks like transform issues, maybe has to do with draw topology. Does it flash like that on opengl?

**Comment by MarioSonic2987** [comment]
Yes. In DX12, it does the same thing.

**Comment by MarioSonic2987** [comment]
```
{rsx::thread} class std::runtime_error thrown: Invalid location (offset=0x0, location=0xffffffff)
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:134)
```
Critical error when you try to go ingame.

**Comment by MarioSonic2987** [comment]
This issue remains OpenGL label.

**Comment by MarioSonic2987** [comment]
Tested in https://github.com/RPCS3/rpcs3/commit/1f45f05f8d376bf0c273f3ad6b7e70bbd20cb968.

**DX12**:
![](http://i.imgur.com/Fka3aOx.png)
**GL**:
![](http://i.imgur.com/bythRWk.png)
**Vulkan**:
![](http://i.imgur.com/Y29v0Vc.png)

[Shaderlog DX12](https://drive.google.com/open?id=0B9LymxJkpT48eXBjVFNSZnFTcGc)
[Shaderlog GL](https://drive.google.com/open?id=0B9LymxJkpT48cFFzSFl3MVhGckk)
[Shaderlog Vulkan](https://drive.google.com/open?id=0B9LymxJkpT48amxjQ1oyYUtlTU0)
[RenderDoc Vulkan](https://drive.google.com/open?id=0B9LymxJkpT48bjNVNlA1bW1wb28)

**Comment by raven02** [comment]
@MarioSonic2987 , just wonder what are the issues left for this game?

**Comment by MarioSonic2987** [comment]
Flickering particles (smoke) and the previous one (polygons going crazy).

**Comment by raven02** [comment]
I see. so only happen for GL only

**Comment by MarioSonic2987** [comment]
@raven02 Yes, it happens in al backends.

**Comment by MarioSonic2987** [comment]
Appears this when I enter to Wormpot:
```
·F 0:00:51.679398 {rsx::thread} struct vm::access_violation thrown: Access violation reading address 0xa289ae48
```

![](http://i.imgur.com/9Jewttj.png)
[Log](https://gist.github.com/MarioSonic2987/c31bc85c29db936b9c69425f70b00398#file-log-wum-6-3-17-gl)
![](http://i.imgur.com/JsXS1tW.png)
Heavy glitches with the book in Story Mode.
![]()

**Comment by MarioSonic2987** [comment]
![](http://i.imgur.com/Cw6XszL.jpg)
This is what looks in PC version.

**Comment by MarioSonic2987** [comment]
**DX12**: 
![image](https://user-images.githubusercontent.com/20027681/27506354-2cdbd1ba-58b6-11e7-9bc2-11cb2a4aa172.png)
![image](https://user-images.githubusercontent.com/20027681/27506347-21604b04-58b6-11e7-8f8f-d1580139e8c4.png)

**GL**:
![image](https://user-images.githubusercontent.com/20027681/27506309-dea67a0e-58b5-11e7-810b-03691beb826f.png)
![image](https://user-images.githubusercontent.com/20027681/27506307-c48c9ebe-58b5-11e7-8d58-1507cb11e0ac.png)

**Vulkan**:
![image](https://user-images.githubusercontent.com/20027681/27506365-59438d24-58b6-11e7-8398-cd3869e17af3.png)
![image](https://user-images.githubusercontent.com/20027681/27506371-7631d2ec-58b6-11e7-800f-5a28c779d76a.png)



```
F {rsx::thread} class std::runtime_error thrown: Invalid location (offset=0x0, location=0xffffffff)
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:83)
```
Appears when trying to get ingame.

**Comment by MarioSonic2987** [comment]
Tested with https://github.com/RPCS3/rpcs3/commit/6d14583f287c5b19ebb06636b9c6ecd1541436d2:

OpenGL:
![wum-1](https://user-images.githubusercontent.com/20027681/29350678-cd31403c-825f-11e7-9265-583750bc5024.png)
Vulkan:
![wum-2](https://user-images.githubusercontent.com/20027681/29350688-d6107d62-825f-11e7-9c06-1788bdf93711.png)

**Comment by MarioSonic2987** [comment]
PC version:
![20170816085351_1](https://user-images.githubusercontent.com/20027681/29350856-7b91a482-8260-11e7-8999-b53415b0ba62.jpg)

**Comment by kd-11** [comment]
Still an issue?

**Comment by Asinin3** [comment]
@kd-11 
OGL:
![rpcs3_2017-09-07_07-50-22](https://user-images.githubusercontent.com/15137035/30137164-412a5be8-93a1-11e7-96a4-21b0b6fbcfc8.png)

VK:
![rpcs3_2017-09-07_07-46-08](https://user-images.githubusercontent.com/15137035/30137068-d39c2278-93a0-11e7-8ee1-a3e51345f45e.png)


Also I get this spammed in my log:
E {rsx::thread} RSX: No valid program bound to pipeline. Skipping draw x64106

**Comment by MarioSonic2987** [comment]
Tested in https://github.com/RPCS3/rpcs3/commit/06fc4233d298f40bcc72696164b3055435e217c3:

![](https://i.imgur.com/qufmp2C.png)
![](https://i.imgur.com/RWj4RcJ.jpg)

[Log OpenGL](https://github.com/RPCS3/rpcs3/files/1696468/Log.WUM.5-2-18.GL.gz)
[Shaderlog OpenGL](https://drive.google.com/open?id=1gl868GWkLYFb3YeIT511903xfLO4SEY3)
[RenderDoc OpenGL](https://drive.google.com/open?id=1X1Z4YJBho5ciwVAQA59ZP7MnScqahvfS)

**Comment by MarioSonic2987** [comment]
With https://github.com/RPCS3/rpcs3/commit/98b715d8c89f3c57b5e0e9f0a541a53d13e96617:
![image](https://user-images.githubusercontent.com/20027681/39376046-9f95aaf0-4a50-11e8-9e14-8cfe20ad9298.png)

I used [a very old build](https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.2924/artifacts) and shadows were rendered (badly, but it renders)
![](https://cdn.discordapp.com/attachments/272875751773306881/439473396493844480/unknown.png)

[RenderDoc OpenGL (Master and old master)](https://drive.google.com/open?id=1oUfVjnWBQWKeUfua-Ec_G8Mc6JTFA7--)

**Comment by MarioSonic2987** [comment]
Missing shadows are now fixed.
![image](https://user-images.githubusercontent.com/20027681/45387378-333d6f00-b616-11e8-85b8-ff2e471458a9.png)
![image](https://user-images.githubusercontent.com/20027681/45387275-e22d7b00-b615-11e8-93a8-543e73797fce.png)

**Comment by MarioSonic2987** [comment]
With enabling LLE module libvdec, fixes broken pictures in videos.

**HLE libvdec**:
![image](https://user-images.githubusercontent.com/20027681/50839619-fc2b6000-1360-11e9-9d5a-204aee713c37.png)
**LLE libvdec**:
![image](https://user-images.githubusercontent.com/20027681/50839588-e9b12680-1360-11e9-83c6-9bd51ac87396.png)

**Comment by uaqlover** [comment]
now game is playable 

https://forums.rpcs3.net/thread-174586-page-2.html

**Comment by MarioSonic2987** [comment]
It seems particle effects are now fixed. But character and objects models are still broken:
![image](https://user-images.githubusercontent.com/20027681/57523248-c3a68d80-7324-11e9-81f5-beb1b277e537.png)
![image](https://user-images.githubusercontent.com/20027681/57523195-9d80ed80-7324-11e9-94d9-9a838816919a.png)
![image](https://user-images.githubusercontent.com/20027681/57523309-f05aa500-7324-11e9-9fc3-18562b327cfd.png)


[RSX Capture (Broken model)](https://github.com/RPCS3/rpcs3/files/3166217/NPEB00505_20190510131243_capture.zip)

**Comment by uaqlover** [comment]
ture

**Comment by uaqlover** [comment]
any changes with this pr 

https://github.com/RPCS3/rpcs3/pull/5937 ?

**Comment by MarioSonic2987** [comment]
No. Models are still broken with #5937.

**Comment by MarioSonic2987** [comment]
Broken models are now fixed:
![image](https://user-images.githubusercontent.com/20027681/64421686-79e76d00-d0a2-11e9-8255-8a9a2f1d5024.png)

There's still corrupted image in videos. It can be fixed by enabling LLE libvdec.sprx.

Now all reported graphical issues are fixed. Closing this ancient issue.
