### ISSUE TITLE
sysnet: Unknown/illegal socket error: 10048

### ISSUE THREAD

**Issue by supergatto** [RPCS3/rpcs3#1814]
This bug happen after RPCS3 v0.0.0.9-3-aafcf44
Here log:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/327722/RPCS3.zip)
The game is: Beyond: Two Soul [BCES01122]
LLe Modules loaded:
-CellJpgDec
-CellSre
-CellSpursJq

**Comment by Nezarn** [comment]
1. that game doesn't work yet http://www.emunewz.net/forum/showthread.php?tid=174392
2. as it was stated in that thread, this socket error is a side effect of #1670

**Comment by raven02** [comment]
Is press resume work ok?

**Comment by danilaml** [comment]
I get 
```
{PPU[0x134] Thread (NpMatching_udpp2p) [0x00374d44]} class fmt::exception thrown: sys_net::setsockopt(): Unknown socket option for Win32: 0x1000
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_net.cpp:554)
```
after #1670 in DBZ:Burst Limit (as mentioned there).
It works fine after resume though.
But not in  PPU AoT recompiler. It seems that it doesn't catch the exception properly.
```
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0x80000003.
Exception address: 00007FFACA8BB72C.
ExceptionInformation[0x0]: 0000000000000000.
Instruction address: 00007FFACA8BB72C.
Image base: 0000000000010000.

HOW TO REPORT ERRORS:
1) Check the FAQ, readme, other sources. Please ensure that your hardware and software configuration is compliant.
2) You must provide FULL information: how to reproduce the error (your actions), RPCS3.log file, other *.log files whenever requested.
3) Please ensure that your software (game) is 'Playable' or close. Please note that 'Non-playable' games will be ignored.
4) If the software (game) is not 'Playable', please ensure that this error is unexpected, i.e. it didn't happen before or similar.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
ОК   
---------------------------
```
@Nekotekina ?

**Comment by raven02** [comment]
Unfortunately , i have no idea what is 0x1000 .

**Comment by danilaml** [comment]
@raven02 it could be bug in the code somewhere.

**Comment by Nekotekina** [comment]
Logs? I doubt it even tries to throw, could crash absolutely differently.

**Comment by danilaml** [comment]
@Nekotekina Well, it's the last thing in the log before this error. And I can even try to press Resume.
Anyway, [logs](http://rgho.st/8Njtl5wCp).

**Comment by Nekotekina** [comment]
OK, can you confirm it's the same thread?

**Comment by raven02** [comment]
@Nekotekina , it is the same thread.

**Comment by hamza195** [comment]
I'm getting the same error , can someone please help us ? I really want to play this game

**Comment by AniLeo** [comment]
Bomberman ULTRA - **NPUB30051**
```
·W {PPU[0x2] Thread (main_thread) [0x00164b20]} libnet: setsockopt(s=0, level=65535, optname=4096, optval=*0xd001fa00, optlen=4)
·E {PPU[0x2] Thread (main_thread) [0x00164b20]} PPU: 'sys_net::setsockopt' aborted
·F {PPU[0x2] Thread (main_thread) [0x00164b20]} class fmt::exception thrown: sys_net::setsockopt(): Unknown socket option for Win32: 0x1000
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_net.cpp:554)
```

**Comment by raven02** [comment]
SHould be working better now .I'm closing this one.
