### ISSUE TITLE
Failed to Launch Kingdom Hearts HD 2.5 ReMIX

### ISSUE THREAD

**Issue by JackONeill12** [RPCS3/rpcs3#1817]
{PPU[0x1] Thread (main_thread) [0x0012fde8]} sysPrxForUser TODO: _sys_process_atexitspawn()
{PPU[0x1] Thread (main_thread) [0x00130088]} sysPrxForUser TODO: _sys_process_at_Exitspawn
{PPU[0x1] Thread (main_thread) [0x0012ed48]} HLE: Function 'cellFsOpen' aborted
{PPU[0x1] Thread (main_thread) [0x0012ed48]} class fmt::exception thrown: sys_fs_open(): Invalid or unimplemented flags (010000): '/dev_bdvd/PS3_GAME/USRDIR/Launcher/Launcher.mself'
(in file C:\rpcs3\rpcs3\Emu\Cell\lv2\sys_fs.cpp:95)

**Comment by raven02** [comment]
Please provide detail like PPU/SPU and Renderer backend setting

**Comment by JackONeill12** [comment]
PPU is Interpreter (fast)
SPU is Recompiler (ASMJIT)
Renderer is OpenGL

Everything else is standart settings

**Comment by elfogames** [comment]
i guess Condmned 2 has the same problem

**Comment by Nezarn** [comment]
Maybe mself isn't implemented yet?

http://www.emunewz.net/forum/showthread.php?tid=151659&pid=216814#pid216814

@JackONeill12 Its highly recommended to check forum, there you can find which games can run, and which games doesn't work.

**Comment by GhettoGirl** [comment]
I googled ```.mself``` and found out that this are encrypted archive files with the ```Sony sdata 4.0.0.W Encryption```. What I understood so far is that you can only decrypt these on a real PS3. Should be very challenging and time consuming to implement support for this format. If even possible :question: 

I also found some keys, but I'm not sharing these because of legal issues.

This a decryption program I found
```
# Square Enix - Kingdom Hearts HD 1.5 ReMix *.mself
# by Falo
# script for QuickBMS http://quickbms.aluigi.org
# Note: All files are encrypted with sdata V4

endian big

idstring "MSF"

goto 0x10
get numFiles long
get ofsTable long
goto ofsTable

for x = 0 < numFiles

GetDString Name 0x20
get Offset LONGLONG
get Size LONGLONG
get empty LONGLONG
get empty LONGLONG

log Name Offset Size

next x
```

**Comment by raven02** [comment]
Thanks @JackONeill12 

@B1ackDaemon , do you have any insight here?

**Comment by kiralolo** [comment]
So guys is kh1.5 or 2.5 working on rpcs3 or not because i don't understand nothing in scripting and this stuff u r talking about but i want to play the game.

**Comment by GhettoGirl** [comment]
@kiralolo In short NO

RPCS3 doesn't support SDAT encryption at the moment, don't suspect this game to run in the near future.

**Comment by JackONeill12** [comment]
@GhettoGirl I found a working tool on this site. https://forum.xentax.com/viewtopic.php?f=10&t=10231&start=45 
It is able to unpack and decrypt the files from KH 2.5.
The only problem here is the tool uses an index file to name the extracted data and for some of the files naming dosnt work.
But other than that extraction and decryption workes.

**Comment by raven02** [comment]
@JackONeill12 Try this tool to see if you can decrypt the file and put it back to the game to run it.

http://tieba.baidu.com/p/4475890472

**Comment by JackONeill12** [comment]
@raven02 I already have atool to decrypt. Thats not the problem. The problem is that you need to extract and rename the files contained in the .mself first. So with the tool i linked earkier in this post this is possible but it uses a hash file to rename the files after extraction. And this file isnt complete. 

So it looks something like this:
http://imgur.com/a/xU1KY

And the noname folder containes the files with no filename found in the hash file:
http://imgur.com/a/dI2ul

But i tryed to copy the decrypted files back into the gamefolder and removed the index file and the .mself file.

Result:

RSX: Cache file '.gitignore' ignored
{PPU[0x1] Thread (main_thread) [0x0012fde8]} sysPrxForUser TODO: _sys_process_atexitspawn()
{PPU[0x1] Thread (main_thread) [0x00130088]} sysPrxForUser TODO: _sys_process_at_Exitspawn
{PPU[0x1] Thread (main_thread) [0x0012ed48]} sys_fs: sys_fs_open('/dev_bdvd/PS3_GAME/USRDIR/Launcher/index.dat'): failed to open file (flags=0, mode=0)
{PPU[0x1] Thread (main_thread) [0x001007ac]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK
{PPU[0x1] Thread (main_thread) [0x00104594]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK
{PPU[0x1] Thread (main_thread) [0x001302b8]} sys_process: Process finished

So the game looks for the index file.

And if i put the index file back:

RSX: Cache file '.gitignore' ignored
{PPU[0x1] Thread (main_thread) [0x0012fde8]} sysPrxForUser TODO: _sys_process_atexitspawn()
{PPU[0x1] Thread (main_thread) [0x00130088]} sysPrxForUser TODO: _sys_process_at_Exitspawn
{PPU[0x1] Thread (main_thread) [0x0012ed48]} PPU: 'cellFsOpen' aborted
{PPU[0x1] Thread (main_thread) [0x0012ed48]} class fmt::exception thrown: sys_fs_open(): Invalid or unimplemented flags (010000): '/dev_bdvd/PS3_GAME/USRDIR/Launcher/Launcher.mself'
(in file C:\rpcs3\rpcs3\Emu\Cell\lv2\sys_fs.cpp:95)

It thorws the old exeption although the Launcher.mself isnt even there.

**Comment by FerrazaDazzle** [comment]
Do you think the team has progressed enough to implement the decryption yet because this would be 1 major step forward to ps3 emulation. Do you think that LLE Modules are required for this?

**Comment by raven02** [comment]
It would be better discuss in http://www.emunewz.net/forum/forumdisplay.php?fid=162

**Comment by Bak840** [comment]
Hi, I have a problem, I'm trying to run KH 1.5 Remix or KH 2.5 Remix on RCPS3, I included the libfs.prx and the libfs_155.prx libraries but I hace the following error:
F LDR: class std::out_of_range thrown: invalid vector<T> subscript
Does anybody have an idea of how I can fix it?

**Comment by Zangetsu38** [comment]
libfs_155.prx not compatible with rpcs3

**Comment by Bak840** [comment]
but if I don't include libfs_155.prx, there are even more errors so I thougt this game need libs_155.prx
There are the following errors:
E LDR: Unknown module 'sys_fs_ps2disc'
U {PPU[0x70000000] Thread (main_thread) [0x00116dc0]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x70000000] Thread (main_thread) [0x00117060]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x70000001] Thread (SysCacheInit) [0x00115930]} cellSysutil TODO: cellSysCacheClear()
U {PPU[0x70000000] Thread (main_thread) [0x001f7ec0]} sys_fs TODO: sys_fs_fcntl(): Unknown operation 0xc0000006 (fd=4294967295, arg=*0xd000e878, size=0x20)
E {PPU[0x70000000] Thread (main_thread) [0x001f9090]} PPU: 'sys_fs_open' aborted
F {PPU[0x70000000] Thread (main_thread) [0x001f9090]} class std::runtime_error thrown: sys_fs_open(“/dev_bdvd/PS3_GAME/USRDIR/KHLauncher/Launcher.mself”): Invalid or unimplemented flags: 010000
(in file C:\rpcs3\rpcs3\Emu\Cell\lv2\sys_fs.cpp:129)

**Comment by JackONeill12** [comment]
That's because rpcs3 currently can't handle .mself files.

**Comment by al0xf** [comment]
This game will not run regardless of settings until .mself decryption is implemented. It is on the roadmap and will perhaps be implemented in a few weeks or months. Any further questions can be asked on the forum or discord channel as github is only for developers.

**Comment by Bak840** [comment]
Thanks for the answers, I will wait until they add the decryption functionnality
