### ISSUE TITLE
DX12/GL: Tekken 6 black screen

### ISSUE THREAD

**Issue by Exmach** [RPCS3/rpcs3#1819]
White flashes on dx12 and ogl always error
{rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: unknown origin (1) then
{PPU[0x106] Thread (Demuxer[0x105] Thread)} class fmt::exception thrown: dmuxOpen::<lambda_c5d9be3d6cae12ed21adb310b6b1ef04>::operator ()(): dmuxEnableEs: unknown filter (0xe0, 0x0, 0x0, 0x0)
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellDmux.cpp:678)
resume button works but always first error.

**Comment by Nezarn** [comment]
`{PPU[0x106] Thread (Demuxer[0x105] Thread)} class fmt::exception thrown: dmuxOpen::::operator ()(): dmuxEnableEs: unknown filter (0xe0, 0x0, 0x0, 0x0)`

check the game's directory if it has any movies and try to move them out of there to workaround this error

**Comment by Exmach** [comment]
Found some DATA.BIN files and this error dissapeared but its still black screen and spam NV3089_IMAGE_IN_SIZE

**Comment by zminhquanz** [comment]
you can using LLE module dmux and dmuxpamf

**Comment by DHrpcs3** [comment]
Interesting, origin is CELL_GCM_TRANSFER_ORIGIN_CENTER. I will take a look.

**Comment by Exmach** [comment]
dmux,dmuxpamf,sre=no changes.

**Comment by raven02** [comment]
This game is already working .

https://www.youtube.com/watch?v=wheqxCiOZTo
