### ISSUE TITLE
Vulkan : Outrun arcade wrong road color

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1826]
@kd-11 Regressed at https://github.com/RPCS3/rpcs3/pull/1722

![untitled](https://cloud.githubusercontent.com/assets/3000282/16357872/3691a594-3b35-11e6-98e4-263b5d874008.jpg)

**Comment by kd-11** [comment]
It was always that way for me. If you drive around for a while, the color becomes "normal".

**Comment by raven02** [comment]
It affected the border color change .I'm trying to push back the textures[i].border_color() into the sampler however no idea how to match with the VKBorderColor

**Comment by raven02** [comment]
By #1830 , the road color looks good again.

![1](https://cloud.githubusercontent.com/assets/3000282/16360906/1378116a-3bad-11e6-873a-0da3d0a75a93.jpg)

**Comment by raven02** [comment]
Should be fixed in latest build by set default border color to opaque white.
