### ISSUE TITLE
Tales of Xillia 2 [BLES-01962]: fails? to install game data -> system error 20

### ISSUE THREAD

**Issue by magiruuvelvet** [RPCS3/rpcs3#1827]
**RPCS3 Version:** 4a08e8cd0b9bb952b81e7d5753efb46506107001
**Game:** Tales of Xillia 2 [BLES-01962]
**PPU:** Interpreter (fast) and (precise)
**SPU:** ASMJIT
**Log:** https://mega.nz/#F!Tx5mnRpZ!svHzgHgCCt7xOzzgoaXZpw

---

```
{PPU[0x62] Thread (CThread) [0x00ca270c]} cellGame: cellGameCreateGameData(): temporary gamedata directory created ('/dev_hdd1/game/BLES01962')
{PPU[0x1] Thread (main_thread) [0x00ca272c]} HLE: Function 'cellGameContentPermit' aborted
{PPU[0x1] Thread (main_thread) [0x00ca272c]} N3fmt9exceptionE thrown: Unknown system error: 20.
```

**NOTES:** PPU LLVM segmentation fault after 6 minutes of blackscreen

---

The actual installation process seems to work, data is created in `/dev_hdd1/game/BLES01962` without problems. Maybe this has nothing todo with the installation process but happens at boot time and dies because of unimplemented modules/functions. I'm not sure, so I report this.

What does `system error: 20` mean. Maybe it is too early to even give this game a try.

---

Interesting is that the game deletes itself after this error happens. I had to redump the disc :confused: I should keep a backup somewhere else.

**Comment by raven02** [comment]
Did u try it in older version 0.0.0.6?

**Comment by GhettoGirl** [comment]
> Did u try it in older version 0.0.0.6? 

No, just the latest commit. I could try it in an older version if it helps. Do you know whats the latest commit hash of 0.0.0.6 so I checkout and compile it?

**Comment by raven02** [comment]
Should be this one https://github.com/RPCS3/rpcs3/commit/7c1ab4726262420f3ed1a0fc58d833d2744df23a

**Comment by GhettoGirl** [comment]
![screenshot_20160626_133909](https://cloud.githubusercontent.com/assets/13280758/16362034/6891792a-3ba3-11e6-86b7-a5acb6f5cbb8.png)
The commit says tag 0.0.0.9 but nevermind I also jut realized that there are tags so I'm trying both - this commit and [tag 0.0.0.6](https://github.com/RPCS3/rpcs3/releases/tag/v0.0.0.6)

Anyway, I still need to redump the game. Didn't bother anymore yesterday with this problem.

**Comment by GhettoGirl** [comment]
0.0.0.6 says
```
{PPU Thread[0x62] (CThread)[0x00ca2248]} sys_fs: sys_fs_open('/dev_bdvd/PS3_GAME/USRDIR/TLFILE.TLDAT') failed: device not mounted
{PPU Thread[0x62] (CThread)[0x007dd230]} Exception: Trap! (tw 0x1f, r0, r0)
(in file /build/rpcs3-regression-test/rpcs3/Emu/Cell/PPUInterpreter.h:2580, in function TW)
```
I guess there was not support  for TLDAT archives? Game doesn't install game data btw and just freezes.
**Logs:** https://mega.nz/#F!egBVxQQC!w5a3OJmpbc0nDHnIkd_sLg

---

0.0.1-4502- 4a08e8c says
```
{PPU[0x65] Thread (CThread) [0x00ca270c]} cellGame: cellGameCreateGameData(): temporary gamedata directory created ('/dev_hdd1/game/BLES01962')
{PPU[0x4] Thread (main_thread) [0x00ca272c]} HLE: Function 'cellGameContentPermit' aborted
{PPU[0x4] Thread (main_thread) [0x00ca272c]} N3fmt9exceptionE thrown: Unknown system error: 20.
```
After I stop the emulation the game deletes itself, this time I keep a backup outside of the ```dev_hdd0``` folder to safe myself a lot of time. Do you have any idea why the hell the game deletes itself. Is there some kind of security check by Namco Bandai causing the game to delete itself. :confused:

**Comment by Nezarn** [comment]
@GhettoGirl what happens if you "manually install" the game? (ie. copy game files into dev_hdd0\BLES01962 without having PS3_GAME dir and PS3_DISC.SFB , so inside BLES01962 you would have USRDIR, PARAM.SFO, etc. (note: game icon will be black))

and\or

according to log this game uses spurs+spursjobqueue so try enabling libspurs_jq + libsre and librtc (seen rtc stuff in log)

**Comment by GhettoGirl** [comment]
Manually installing didn't help, same behavior ─ game tried to install and ignored the fact that it was already installed and deleted itself after the ```system error: 20``` message.

**Updated Logs:** https://mega.nz/#F!X0glAA7A!8Avgl8ZKZ8pBbdoNusKV0w

The only difference I noticed with the 3 LLE modules enabled, that the SPU emulation is working and the emulator created a ```SPUJIT.log``` file.

```
{PPU[0x78] Thread (CThread) [0x00ca270c]} cellGame: cellGameCreateGameData(): temporary gamedata directory created ('/dev_hdd1/game/BLES01962')
{PPU[0x4] Thread (main_thread) [0x00ca272c]} HLE: Function 'cellGameContentPermit' aborted
{PPU[0x4] Thread (main_thread) [0x00ca272c]} N3fmt9exceptionE thrown: Unknown system error: 20.
```

```yaml
  Load libraries:
    - libsre.sprx
    - librtc.sprx
    - libspurs_jq.sprx
```

I guess that there is some kind of protection by Namco. I mean it wouldn't be impossible, right?

**Comment by GhettoGirl** [comment]
Exactly the same problem happens for **Tales of Xillia [BLES-01962]** too.

**Comment by Nezarn** [comment]
@GhettoGirl i think someone posted on the forum once that using LLE modules from newer firmware is better. (or at least it should be newer\same as the game) btw i've added you on steam (please accept :D )

**Comment by GhettoGirl** [comment]
@Nezarn Yes I share the same opinion using the same LLE module versions or higher as the game requires. I googled how I could extract the ```sys_flash``` directory from official firmware files (```PS3UPDAT.PUP```) downloaded from the Sony website, but could find anything that works on Linux :(
I've downloaded the latest firmware yesterday, but thats off topic here.

**Comment by emmauss** [comment]
i can install game data with the latest build. i think the recent gamedata created commit fixed it.

**Comment by GhettoGirl** [comment]
Yeah, there were some improvements in the game data install code. I didn't tried it yet. Really busy with real life work and other things right now.

**Comment by AniLeo** [comment]
Can you please check if this is still an issue?

**Comment by magiruuvelvet** [comment]
@AniLeo There were to many changes the last months and once again OpenGL freezes again on NVIDIA optimus (bumblebee) :(
I can't run any game at all.

**Comment by AniLeo** [comment]
Someone please retry, this should be fixed

**Comment by Zangetsu38** [comment]
yes, fixed, install works

**Comment by raven02** [comment]
Thanks @Zangetsu38 .I'm closing it then.
