### ISSUE TITLE
Trouble running Densha de Go n64 on OpenEmu - Black Screen, No Sound -CLOSED 

### ISSUE THREAD

**Issue by bauhausfanatic** [RPCS3/rpcs3#1829]
Thanks for stopping by.

I am trying to run Densha de Go on OpenEmu, but I am unable to get past a black screen without any sound. I am running an updated Mac, and just downloaded the application today so it should be up to date. 
Any suggestions?

**Comment by bauhausfanatic** [comment]
OpenEmu 2.0.1 is currently the newest version available.
OSX EL CAPITIAN. Version 10.11.15

**Comment by MoochMcGee** [comment]
RPCS3 DOES NOT RUN N64 GAMES, YOU COLOSSAL TOOL

**Comment by bauhausfanatic** [comment]
hahaha

**Comment by GhettoGirl** [comment]
> Thanks for stopping by.

> I am trying to run Densha de Go on OpenEmu, but I am unable to get past a black screen without any sound. I am running an updated Mac, and just downloaded the application today so it should be up to date.
Any suggestions?

LOL :laughing: 
You are in the wrong place here. RPCS3 is a PS3 emulator.

[OpenEmu issues can be found here](https://github.com/OpenEmu/OpenEmu/issues)

**Comment by bauhausfanatic** [comment]
Thanks GhettoGirl. Cheers.
