### ISSUE TITLE
RPCS3 [Soul Calibur V] Can't play

### ISSUE THREAD

**Issue by SrPacman** [RPCS3/rpcs3#1836]
I don't know how to do to play, I'm so new in this and I stayed all the night looking for help or some videos to configure it and, of course I didn't make it, this is what it says when I run it:

E Unknown function '0x9FB6228E' (0x135f984)
E Unknown module 'cellLibprof' in 'cellSre_Library' library
E Unknown function 'cellUserTraceRegister' (0x1386718)
E Unknown function 'cellUserTraceUnregister' (0x1386738)
E {PPU[0x1c] Thread (mainThread)[0x01370d80]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x1c] Thread (mainThread)[0x01370d80]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x1c] Thread (mainThread)[0x01370d80]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x1c] Thread (mainThread)[0x01370d80]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x1c] Thread (mainThread)[0x01370d80]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x1c] Thread (mainThread)[0x01386a38]} sys_prx TODO: sys_prx_get_module_id_by_name(name=cellLibprof, flags=0, pOpt=0x0)
S {PPU[0x4e] Thread (SpursHdlr0)[0x01372470]} SPU Database initialized...
S {PPU[0x4e] Thread (SpursHdlr0)[0x01372470]} SPU Recompiler (ASMJIT) created...
S {SPU[0x45] Thread (CellSpursKernel1)[0x00848]} Function detected 0x00848-0x0087c
S {SPU[0x45] Thread (CellSpursKernel1)[0x006e8]} Function detected 0x006e8-0x00848
S {SPU[0x45] Thread (CellSpursKernel1)[0x00a00]} Function detected 0x00a00-0x01230
S {SPU[0x46] Thread (CellSpursKernel2)[0x01230]} Function detected 0x01230-0x01470
S {SPU[0x47] Thread (CellSpursKernel3)[0x01d88]} Function detected 0x01d88-0x0215c
S {SPU[0x48] Thread (CellSpursKernel4)[0x01c00]} Function detected 0x01c00-0x01d88
S {SPU[0x48] Thread (CellSpursKernel4)[0x02630]} Function detected 0x02630-0x0284c
S {SPU[0x48] Thread (CellSpursKernel4)[0x028d0]} Function detected 0x028d0-0x029ac
S {SPU[0x48] Thread (CellSpursKernel4)[0x01470]} Function detected 0x01470-0x01600
S {SPU[0x47] Thread (CellSpursKernel3)[0x02868]} Function detected 0x02868-0x028cc
S {SPU[0x47] Thread (CellSpursKernel3)[0x00290]} Function detected 0x00290-0x006e4
S {SPU[0x47] Thread (CellSpursKernel3)[0x00cc8]} Function detected 0x00cc8-0x01230
S {SPU[0x46] Thread (CellSpursKernel2)[0x01600]} Function detected 0x01600-0x01984
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
S {SPU[0x46] Thread (CellSpursKernel2)[0x02850]} Function detected 0x02850-0x02868
S {SPU[0x46] Thread (CellSpursKernel2)[0x00838]} Function detected 0x00838-0x00848
S {SPU[0x46] Thread (CellSpursKernel2)[0x00a00]} Function detected 0x00a00-0x00b00
S {SPU[0x46] Thread (CellSpursKernel2)[0x02ae0]} Function detected 0x02ae0-0x02cb0
S {SPU[0x46] Thread (CellSpursKernel2)[0x04478]} Function detected 0x04478-0x04538
S {SPU[0x46] Thread (CellSpursKernel2)[0x04610]} Function detected 0x04610-0x0461c
S {SPU[0x46] Thread (CellSpursKernel2)[0x03d40]} Function detected 0x03d40-0x03d78
S {SPU[0x46] Thread (CellSpursKernel2)[0x03bf8]} Function detected 0x03bf8-0x03c28
E {PPU[0x1c] Thread (mainThread)[0x01359560]} sys_memory: sys_memory_get_page_attribute(addr=0x24769e80, attr=0xd0059450)
S {SPU[0x46] Thread (CellSpursKernel2)[0x03e18]} Function detected 0x03e18-0x03ecc
S {SPU[0x46] Thread (CellSpursKernel2)[0x01450]} Function detected 0x01450-0x02ae0
S {SPU[0x46] Thread (CellSpursKernel2)[0x04538]} Function detected 0x04538-0x04610
S {SPU[0x46] Thread (CellSpursKernel2)[0x035b8]} Function detected 0x035b8-0x03b68
S {SPU[0x46] Thread (CellSpursKernel2)[0x00a30]} Function detected 0x00a30-0x00b00
S {SPU[0x46] Thread (CellSpursKernel2)[0x03418]} Function detected 0x03418-0x035b4
S {SPU[0x46] Thread (CellSpursKernel2)[0x02d80]} Function detected 0x02d80-0x03418
S {SPU[0x46] Thread (CellSpursKernel2)[0x00b00]} Function detected 0x00b00-0x00c68
S {SPU[0x46] Thread (CellSpursKernel2)[0x04638]} Function detected 0x04638-0x0469c
S {SPU[0x46] Thread (CellSpursKernel2)[0x01430]} Function detected 0x01430-0x01450
S {SPU[0x46] Thread (CellSpursKernel2)[0x04620]} Function detected 0x04620-0x04638
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb98]} cellGcmSys TODO: cellGcmSetZcull(index=0, offset=0x680000, width=1280, height=768, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x5, sRef=0x0, sMask=0xff)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb98]} cellGcmSys TODO: cellGcmSetZcull(index=1, offset=0x1330000, width=640, height=384, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x5, sRef=0x0, sMask=0xff)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb98]} cellGcmSys TODO: cellGcmSetZcull(index=2, offset=0x1b60000, width=1280, height=768, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x5, sRef=0x0, sMask=0xff)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb98]} cellGcmSys TODO: cellGcmSetZcull(index=3, offset=0x2af0000, width=384, height=384, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x5, sRef=0x0, sMask=0xff)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb58]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1c] Thread (mainThread)[0x00b4eb98]} cellGcmSys TODO: cellGcmSetZcull(index=4, offset=0x2c44000, width=192, height=256, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x5, sRef=0x0, sMask=0xff)
E {PPU[0x1c] Thread (mainThread)[0x00b4ecd8]} sys_io: cellKbSetLEDStatus
E {PPU[0xbf] Thread (any_workerThread_0)[0x00b4c858]} cellSysutil TODO: cellSysCacheClear()
E {PPU[0x1c] Thread (mainThread)[0x00b4da78]} sceNp: sceNpManagerGetNpId
E {PPU[0x1c] Thread (mainThread)[0x00b4d9f8]} sceNp: sceNpManagerGetOnlineName
E {PPU[0x1c] Thread (mainThread)[0x00b4d798]} sceNp: sceNpManagerGetAccountRegion
E {PPU[0x1c] Thread (mainThread)[0x00b4d278]} sceNp: sceNpManagerGetAccountAge
E {PPU[0x1c] Thread (mainThread)[0x00b4d958]} sceNp: sceNpManagerGetChatRestrictionFlag
S {SPU[0x46] Thread (CellSpursKernel2)[0x04128]} Function detected 0x04128-0x04474
S {SPU[0x46] Thread (CellSpursKernel2)[0x03c28]} Function detected 0x03c28-0x03d40
S {SPU[0x46] Thread (CellSpursKernel2)[0x00ef8]} Function detected 0x00ef8-0x01370
S {SPU[0x46] Thread (CellSpursKernel2)[0x04c00]} Function detected 0x04c00-0x050b0
S {SPU[0x46] Thread (CellSpursKernel2)[0x05410]} Function detected 0x05410-0x0545c
S {SPU[0x46] Thread (CellSpursKernel2)[0x03ed0]} Function detected 0x03ed0-0x03fe4
S {SPU[0x46] Thread (CellSpursKernel2)[0x03b88]} Function detected 0x03b88-0x03bf4
E {PPU[0x1c] Thread (mainThread)[0x01359560]} sys_memory: sys_memory_get_page_attribute(addr=0x25761080, attr=*0xd0059000)
S {SPU[0x47] Thread (CellSpursKernel3)[0x00a00]} Function detected 0x00a00-0x00ae4
S {SPU[0x47] Thread (CellSpursKernel3)[0x08398]} Function detected 0x08398-0x08494
S {SPU[0x47] Thread (CellSpursKernel3)[0x080f0]} Function detected 0x080f0-0x08398
S {SPU[0x47] Thread (CellSpursKernel3)[0x08080]} Function detected 0x08080-0x080f0
S {SPU[0x47] Thread (CellSpursKernel3)[0x08000]} Function detected 0x08000-0x0807c
S {SPU[0x47] Thread (CellSpursKernel3)[0x05f98]} Function detected 0x05f98-0x06074
S {SPU[0x47] Thread (CellSpursKernel3)[0x01998]} Function detected 0x01998-0x0566c
S {SPU[0x47] Thread (CellSpursKernel3)[0x05f30]} Function detected 0x05f30-0x05f94
S {SPU[0x47] Thread (CellSpursKernel3)[0x01600]} Function detected 0x01600-0x01784
S {SPU[0x47] Thread (CellSpursKernel3)[0x05c90]} Function detected 0x05c90-0x05d48
S {SPU[0x47] Thread (CellSpursKernel3)[0x01788]} Function detected 0x01788-0x01914
S {SPU[0x47] Thread (CellSpursKernel3)[0x05870]} Function detected 0x05870-0x05a44
S {SPU[0x47] Thread (CellSpursKernel3)[0x05a50]} Function detected 0x05a50-0x05a68
S {SPU[0x47] Thread (CellSpursKernel3)[0x05670]} Function detected 0x05670-0x05870
S {SPU[0x47] Thread (CellSpursKernel3)[0x07c00]} Function detected 0x07c00-0x07c20
S {SPU[0x47] Thread (CellSpursKernel3)[0x07ce0]} Function detected 0x07ce0-0x08380
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d848]} Function detected 0x0d848-0x0dd5c
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d8cc]} Function detected 0x0d8cc-0x0dd5c
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d8c0]} Function detected 0x0d8c0-0x0d8cc
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d710]} Function detected 0x0d710-0x0d74c
S {SPU[0x47] Thread (CellSpursKernel3)[0x07c60]} Function detected 0x07c60-0x07ce0
S {SPU[0x47] Thread (CellSpursKernel3)[0x0c218]} Function detected 0x0c218-0x0c2a4
S {SPU[0x47] Thread (CellSpursKernel3)[0x0c2a8]} Function detected 0x0c2a8-0x0c558
S {SPU[0x47] Thread (CellSpursKernel3)[0x08f98]} Function detected 0x08f98-0x092f8
S {SPU[0x47] Thread (CellSpursKernel3)[0x0cc68]} Function detected 0x0cc68-0x0ccdc
S {SPU[0x47] Thread (CellSpursKernel3)[0x0cce0]} Function detected 0x0cce0-0x0ce60
S {SPU[0x47] Thread (CellSpursKernel3)[0x088c0]} Function detected 0x088c0-0x08960
S {SPU[0x47] Thread (CellSpursKernel3)[0x0cbb0]} Function detected 0x0cbb0-0x0cc68
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d100]} Function detected 0x0d100-0x0d250
S {SPU[0x47] Thread (CellSpursKernel3)[0x0cf00]} Function detected 0x0cf00-0x0cf5c
S {SPU[0x47] Thread (CellSpursKernel3)[0x0cb40]} Function detected 0x0cb40-0x0cbb0
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d028]} Function detected 0x0d028-0x0d0fc
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d278]} Function detected 0x0d278-0x0d43c
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d250]} Function detected 0x0d250-0x0d268
S {SPU[0x47] Thread (CellSpursKernel3)[0x0caf0]} Function detected 0x0caf0-0x0cb40
S {SPU[0x47] Thread (CellSpursKernel3)[0x0a090]} Function detected 0x0a090-0x0a4b4
S {SPU[0x47] Thread (CellSpursKernel3)[0x0c708]} Function detected 0x0c708-0x0c7c0
S {SPU[0x47] Thread (CellSpursKernel3)[0x097f0]} Function detected 0x097f0-0x0a08c
S {SPU[0x47] Thread (CellSpursKernel3)[0x09440]} Function detected 0x09440-0x097f0
S {SPU[0x47] Thread (CellSpursKernel3)[0x0ca78]} Function detected 0x0ca78-0x0caf0
S {SPU[0x47] Thread (CellSpursKernel3)[0x0ca68]} Function detected 0x0ca68-0x0ca74
S {SPU[0x47] Thread (CellSpursKernel3)[0x0c7c0]} Function detected 0x0c7c0-0x0c8b8
S {SPU[0x47] Thread (CellSpursKernel3)[0x0bec0]} Function detected 0x0bec0-0x0beec
S {SPU[0x47] Thread (CellSpursKernel3)[0x092f8]} Function detected 0x092f8-0x0943c
S {SPU[0x47] Thread (CellSpursKernel3)[0x0ce60]} Function detected 0x0ce60-0x0cefc
S {SPU[0x47] Thread (CellSpursKernel3)[0x08760]} Function detected 0x08760-0x088bc
S {SPU[0x47] Thread (CellSpursKernel3)[0x08380]} Function detected 0x08380-0x0875c
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d4d8]} Function detected 0x0d4d8-0x0d5d0
S {SPU[0x47] Thread (CellSpursKernel3)[0x08ea8]} Function detected 0x08ea8-0x08ef0
S {SPU[0x47] Thread (CellSpursKernel3)[0x08bd8]} Function detected 0x08bd8-0x08ea4
S {SPU[0x47] Thread (CellSpursKernel3)[0x0c028]} Function detected 0x0c028-0x0c09c
S {SPU[0x47] Thread (CellSpursKernel3)[0x0ca80]} Function detected 0x0ca80-0x0caf0
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d268]} Function detected 0x0d268-0x0d278
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d0d4]} Function detected 0x0d0d4-0x0d0fc
S {SPU[0x47] Thread (CellSpursKernel3)[0x0cb8c]} Function detected 0x0cb8c-0x0cbb0
S {SPU[0x47] Thread (CellSpursKernel3)[0x091e0]} Function detected 0x091e0-0x092f8
S {SPU[0x47] Thread (CellSpursKernel3)[0x091ec]} Function detected 0x091ec-0x092f8
S {SPU[0x47] Thread (CellSpursKernel3)[0x08ef0]} Function detected 0x08ef0-0x08f94
S {SPU[0x47] Thread (CellSpursKernel3)[0x08968]} Function detected 0x08968-0x08bd8
S {SPU[0x47] Thread (CellSpursKernel3)[0x0c8b8]} Function detected 0x0c8b8-0x0c970
S {SPU[0x47] Thread (CellSpursKernel3)[0x0bef0]} Function detected 0x0bef0-0x0bf44
S {SPU[0x47] Thread (CellSpursKernel3)[0x08960]} Function detected 0x08960-0x08964
S {SPU[0x47] Thread (CellSpursKernel3)[0x0ca60]} Function detected 0x0ca60-0x0ca64
S {SPU[0x47] Thread (CellSpursKernel3)[0x0dd60]} Function detected 0x0dd60-0x0e0ec
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d650]} Function detected 0x0d650-0x0d700
S {SPU[0x47] Thread (CellSpursKernel3)[0x0c24c]} Function detected 0x0c24c-0x0c2a4
S {SPU[0x47] Thread (CellSpursKernel3)[0x07d10]} Function detected 0x07d10-0x08380
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d440]} Function detected 0x0d440-0x0d4d4
S {SPU[0x47] Thread (CellSpursKernel3)[0x0e0f0]} Function detected 0x0e0f0-0x0e120
S {SPU[0x47] Thread (CellSpursKernel3)[0x0d750]} Function detected 0x0d750-0x0d844
S {SPU[0x47] Thread (CellSpursKernel3)[0x05838]} Function detected 0x05838-0x05870
S {SPU[0x47] Thread (CellSpursKernel3)[0x05bd8]} Function detected 0x05bd8-0x05c90
S {SPU[0x47] Thread (CellSpursKernel3)[0x05000]} Function detected 0x05000-0x055d0
S {SPU[0x47] Thread (CellSpursKernel3)[0x019b8]} Function detected 0x019b8-0x05000
S {SPU[0x47] Thread (CellSpursKernel3)[0x05650]} Function detected 0x05650-0x05658
S {SPU[0x47] Thread (CellSpursKernel3)[0x02594]} Function detected 0x02594-0x05000
S {SPU[0x47] Thread (CellSpursKernel3)[0x05420]} Function detected 0x05420-0x055d0
S {SPU[0x47] Thread (CellSpursKernel3)[0x00b28]} Function detected 0x00b28-0x00f24
S {SPU[0x47] Thread (CellSpursKernel3)[0x06348]} Function detected 0x06348-0x06384
S {SPU[0x47] Thread (CellSpursKernel3)[0x00aa0]} Function detected 0x00aa0-0x00ae4
S {SPU[0x47] Thread (CellSpursKernel3)[0x05f18]} Function detected 0x05f18-0x05f30
S {SPU[0x48] Thread (CellSpursKernel4)[0x07c00]} Function detected 0x07c00-0x07c20
S {SPU[0x48] Thread (CellSpursKernel4)[0x07ce0]} Function detected 0x07ce0-0x07fa0
S {SPU[0x48] Thread (CellSpursKernel4)[0x0c9f8]} Function detected 0x0c9f8-0x0cf0c
S {SPU[0x48] Thread (CellSpursKernel4)[0x0ca8c]} Function detected 0x0ca8c-0x0cf0c
S {SPU[0x48] Thread (CellSpursKernel4)[0x0ca70]} Function detected 0x0ca70-0x0ca8c
S {SPU[0x48] Thread (CellSpursKernel4)[0x0c8c0]} Function detected 0x0c8c0-0x0c8fc
S {SPU[0x48] Thread (CellSpursKernel4)[0x07c60]} Function detected 0x07c60-0x07ce0
S {SPU[0x48] Thread (CellSpursKernel4)[0x0c140]} Function detected 0x0c140-0x0c1cc
S {SPU[0x48] Thread (CellSpursKernel4)[0x0c1d0]} Function detected 0x0c1d0-0x0c480
E {PPU[0x1c] Thread (mainThread)[0x00b4d3f8]} sceNp: sceNpBasicRegisterContextSensitiveHandler
S {SPU[0x48] Thread (CellSpursKernel4)[0x0ab68]} Function detected 0x0ab68-0x0b454
S {SPU[0x48] Thread (CellSpursKernel4)[0x0c640]} Function detected 0x0c640-0x0c6f8
S {SPU[0x48] Thread (CellSpursKernel4)[0x0a318]} Function detected 0x0a318-0x0ab64
S {SPU[0x48] Thread (CellSpursKernel4)[0x0c798]} Function detected 0x0c798-0x0c82c
S {SPU[0x48] Thread (CellSpursKernel4)[0x0cf10]} Function detected 0x0cf10-0x0cf40
S {SPU[0x48] Thread (CellSpursKernel4)[0x0c900]} Function detected 0x0c900-0x0c9f4
S {SPU[0x45] Thread (CellSpursKernel1)[0x019cc]} Function detected 0x019cc-0x02594
S {SPU[0x45] Thread (CellSpursKernel1)[0x02698]} Function detected 0x02698-0x05000
S {SPU[0x45] Thread (CellSpursKernel1)[0x02068]} Function detected 0x02068-0x02594
S {SPU[0x45] Thread (CellSpursKernel1)[0x022a8]} Function detected 0x022a8-0x02594
S {SPU[0x45] Thread (CellSpursKernel1)[0x05660]} Function detected 0x05660-0x0566c
S {SPU[0x45] Thread (CellSpursKernel1)[0x02588]} Function detected 0x02588-0x02594
S {SPU[0x45] Thread (CellSpursKernel1)[0x055fc]} Function detected 0x055fc-0x05650
S {SPU[0x45] Thread (CellSpursKernel1)[0x0449c]} Function detected 0x0449c-0x05000
S {SPU[0x45] Thread (CellSpursKernel1)[0x01138]} Function detected 0x01138-0x014fc

Please if u are going to say "chech the forum", at least tell me were because I can't find it...

**Comment by raven02** [comment]
You can search the forum .If you cannot find it , that mean it is not working yet .

**Comment by raven02** [comment]
Checked out this one - https://www.youtube.com/watch?v=EABOTGQWfJA

**Comment by SrPacman** [comment]
@raven02 I did exactly what the guy does in that video and I can't play. And I didn't put it as attachment because I don't know how to do it, sorry.

**Comment by raven02** [comment]
Then probably it is broken in our latest build and we have few other titleS got similar regression .

**Comment by SrPacman** [comment]
Oh, okay, then I must wait then or something... Thanks for support @raven02

**Comment by raven02** [comment]
No problem . I'm closing this then.
