### ISSUE TITLE
Project Diva F [BLUS-31319] :  Access violation reading address 0x1a0

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1838]
When i'm loading to play ingame, it's going to hang
![image](https://cloud.githubusercontent.com/assets/11285640/16400511/56370e98-3d06-11e6-8e7c-f79243792738.png)

**Comment by raven02** [comment]
Can you please give more information here ? like PPU/SPU setting and LLE modules loaded

**Comment by zminhquanz** [comment]
@raven02 PPU Recompiler , SPU Recompiler , LLE Module loaded : libdmux vs libdmuxpamf

**Comment by raven02** [comment]
Did u add resc and rtc modules ?

**Comment by zminhquanz** [comment]
I'm using PPU Interpreter 2 , SPU Recompiler , LLE Modules : dmux , dmuxpamf , rtc , resc
Have this error : {PPU[0x5] Thread (main_thread) [0x006cc1b0]} struct vm::access_violation thrown: Access violation reading address 0x746c5ffc
![image](https://cloud.githubusercontent.com/assets/11285640/16406180/c89a1ad6-3d36-11e6-91cb-093672447131.png)

**Comment by raven02** [comment]
Probably you can check out this thread to see if it helps you.

http://www.emunewz.net/forum/showthread.php?tid=174467

**Comment by zminhquanz** [comment]
sometimes , it appear this error

**Comment by raven02** [comment]
Yes , it is known issue that some games may have random freeze or crash or hang . We can only wait until it is fixed.
