### ISSUE TITLE
DX12: vertex texture unimplmented

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1842]
[fw_vertex_texture.ppu.zip](https://github.com/RPCS3/rpcs3/files/337105/fw_vertex_texture.ppu.zip)

![1](https://cloud.githubusercontent.com/assets/3000282/16417748/a9938f8a-3d79-11e6-90a0-1467c9f3840f.jpg)

**-Vulkan**

> {rsx::thread} RSX: Custom primitive restart index 0x7FFFFFFF. Should rewrite index buffer with proper value!
> {rsx::thread} RSX: Warning, version 450 is not yet complete; most version-specific features are present, but some are missing.
> ERROR: 0:63: 'vtex0' : undeclared identifier 
> ERROR: 0:63: 'texture' : no matching overloaded function found 
> ERROR: 0:63: 'assign' :  cannot convert from 'const float' to 'temp 4-component vector of float'
> ERROR: 3 compilation errors.  No code generated.

**-DX12**

> {rsx::thread} RSX: VS build failed:D:\rpcs3\VertexProgram.hlsl(131,9-36): error X3037: constructors only defined for numeric base types

**\- OGL**

It start working in latest build though it is quite broken

**Comment by kd-11** [comment]
I'll implement vertex texture for vulkan and hopefully fix the opengl issues soon

**Comment by raven02** [comment]
GL and backend has implemeneted vertex texture support . DX12 remains
