### ISSUE TITLE
DX12 : alpha kill unimplemented

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1843]
[alphakill.ppu.zip](https://github.com/RPCS3/rpcs3/files/337157/alphakill.ppu.zip)

**-GL** (correct)
![4](https://cloud.githubusercontent.com/assets/3000282/16418056/d61894fa-3d7a-11e6-9a11-e70d3d23af85.jpg)

**-Vulkan** (correct)
![untitled](https://cloud.githubusercontent.com/assets/3000282/18814893/a94edf6a-8352-11e6-8e61-9503ecdb27de.jpg)

**-DX12**
![3](https://cloud.githubusercontent.com/assets/3000282/16418069/e2f9ff2e-3d7a-11e6-9a93-ee7213752510.jpg)

**Comment by kd-11** [comment]
Vulkan is fixed here https://github.com/RPCS3/rpcs3/pull/2146

**Comment by raven02** [comment]
DX12 is fixed by https://github.com/RPCS3/rpcs3/pull/2158
