### ISSUE TITLE
Vulkan :Hatsune Miku Project Diva F 2nd Vertex Shader error

### ISSUE THREAD

**Issue by Nezarn** [RPCS3/rpcs3#1846]
> `·E {rsx::thread} RSX: Warning, version 450 is not yet complete; most version-specific features are present, but some are missing.
> ERROR: 0:108: 'dot' : ambiguous function signature match: multiple signatures match under implicit type conversion 
> ERROR: 0:118: 'dot' : ambiguous function signature match: multiple signatures match under implicit type conversion 
> ERROR: 0:120: 'dot' : ambiguous function signature match: multiple signatures match under implicit type conversion 
> ERROR: 3 compilation errors.  No code generated.`

FragmentProgram.spirv: http://pastebin.com/vNEZvjGs
VertexProgram.spirv: http://pastebin.com/69nJDHK2
Log: https://gist.github.com/Nezarn/f2718d101326f0a19924f29fc4cfda8e

**Comment by raven02** [comment]
Should be these 3 sets .

>     tmp3.x = vec4(dot(tmp1.xyzx.xyz, in_normal.xyzx.xyz)).x;
>     tmp3.z = vec4(dot(tmp0.xyzx.xyz, in_normal.xyzx.xyz)).z;
>     tmp3.y = vec4(dot(tmp1.xyzx.xyz, in_normal.xyzx.xyz)).y;
>

**Comment by raven02** [comment]
@kd-11 , any insight?

**Comment by raven02** [comment]
@kd-11 , any insight? It is from DP3 function

**Comment by kd-11** [comment]
```
tmp3.x = vec4(dot(tmp1.xyzx.xyz, in_normal.xyzx.xyz)).x;
```
This is wrong (implicit expansion of vec3 to vec4)
Should be something like `tmp3.x = vec4(dot(tmp1.xyzx.xyz, in_normal.xyzx.xyz).xxxx).x` or even better, no expansion `tmp3.x = dot(tmp1.xyzx.xyz, in_normal.xyzx.xyz)`

**Comment by kd-11** [comment]
@raven02 Since I've noticed that the old glsl decompiler expands all dot operations to vec4, i'll swizzle the result and that will fix the bugs in the interim, until the new shader decompiler is up to speed. Shaders generated by that new decompiler are alot better and cleaner than what we have for dx12 and vulkan at the moment.

**Comment by raven02** [comment]
Thanks @kd-11

**Comment by raven02** [comment]
@Nezarn , i swizzled the DP3 function .Can you check out this build to see if issue fixed?

https://ci.appveyor.com/api/buildjobs/pm3tn90p0u69kttl/artifacts/rpcs3-ReleaseLLVM-f916af0b.zip

**Comment by Nezarn** [comment]
@raven02 sorry but i can't, i sold my 970 and on Haswell HD4600 theres no support for Vulkan in windows :( (and im still waiting for custom RX480 cards to launch)

**Comment by raven02** [comment]
Nevermind . I can try to test it tonight when i back home .

**Comment by raven02** [comment]
Sorry i need some guy who own AMD to test it since Vulkan keep crashing on my NV card.

**Comment by AniLeo** [comment]
@raven02 I'm trying to boot the game here but having a few issues with cellGame

**Comment by raven02** [comment]
@AniLeo , what is the issue?

**Comment by kd-11** [comment]
@raven02 The error is actually on this line:
```  tmp2.x = vec4(dot(vec4(in_pos.xyzx.xyz, 1.0), tmp1)).x; ```

where we have a dot(vec3, float)

**Comment by kd-11** [comment]
@raven02 The lines reported in the log as having an error are off by one. Could you check the DX12 output?

**Comment by raven02** [comment]
I think it is the one in DX12

	tmp5.x = dot(float4(in_pos.xyzx.xyz, 1.0), tmp1).xxxx.x;

**Comment by kd-11** [comment]
Well, if tmp1 is also vec4 then there is no error in that line either. I'll have to look deeper into this issue.

**Comment by Nezarn** [comment]
@raven02 i think this can be closed since it doesn't have this issue anymore (at least it doesn't happen on AMD, can you check on nvidia?)
