### ISSUE TITLE
DX12: Hatsune Miku Project DIVA Dreamy Theater 2nd Vertex Shader Issue

### ISSUE THREAD

**Issue by Nezarn** [RPCS3/rpcs3#1850]
Shaders+Logs: https://www.dropbox.com/s/cgmbuymbmid1mf9/dreamy%20theater.zip?dl=0

Note: Game can boot with Null renderer (i hear the SEGA logo), also opengl doesn't work either but since that is WIP and i guess still missing some stuff ~~(so i didn't upload logs regarding OGL)~~

OGL shader and logs: https://www.dropbox.com/s/wfl3mrv2a5mh88e/rpcs3.zip?dl=0

**Comment by Nezarn** [comment]
Dreamy Theater 1 is the same https://www.dropbox.com/s/40biumwof99lgfl/dreamy%20theater1.zip?dl=0

**Comment by raven02** [comment]
It should be the same missing vertex texture support (the log shows same error)

**Comment by raven02** [comment]
In summary, 

DX12

> {rsx::thread} RSX: VS build failed:D:\rpcs3\VertexProgram.hlsl(136,11-38): error X3037: constructors only defined for numeric base types


GL
{rsx::thread} class gl::glsl::compilation_exception thrown: compilation failed: '0(48) : error C7623: implicit narrowing of type from "vec4" to "float"


Vulkan

{rsx::thread} RSX: Warning, version 450 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:71: 'vtex0' : undeclared identifier 
ERROR: 0:71: 'texture' : no matching overloaded function found 
ERROR: 2 compilation errors.  No code generated.

**Comment by kd-11** [comment]
OGL vtexture fetch swizzle issue has been reported here: https://github.com/RPCS3/rpcs3/issues/1899.

**Comment by Bryceless** [comment]
I would test out Dreamy Theater and report on the bug, but whenever I try to launch it, it gives me an std_trap error.

**Comment by Nezarn** [comment]
@Bryceless you need to use libresc + librtc + libspurs_jq + libsre. Also theres nothing else to report, since its still not working.

**Comment by Bryceless** [comment]
Thanks for the info Nezarn!
I tried it out, and it remedied the std_trap error, but there is a CELL_GAME_ERROR_FAILURE.
As of right now, the game is unplayable and won't boot up completely.

**Comment by Nezarn** [comment]
@Bryceless if you use NULL renderer, it will. (if you read my opening comment, you would've know.) If its still not booting up, then your backup copy is bad.

**Comment by Bryceless** [comment]
@Nezarn I managed to download DT 2nd (Instead of Extend), and it is throwing me the "Failed to compile Shader" error.

**Comment by Nezarn** [comment]
@Bryceless rpcs3 doesn't support piracy. (also its the same with all 3 game)

**Comment by Nezarn** [comment]
log+shaders with reverted ogl renderer: https://www.dropbox.com/s/otstfa0qq35qljf/rpcs3_DT_oldogl.zip?dl=0

**Comment by Bryceless** [comment]
@Nezarn What I meant to say is that I used PSX Download Helper to download a legitimate copy from my PSN account.

Anyways, you are correct that the NULL renderer make the game boot.

**Comment by kd-11** [comment]
Common decompiler is missing some minor fixes to enable vertex textures. Its not implemented atm for any backend.

**Comment by kd-11** [comment]
Now that GL and vulkan share decompiler, I think I can start work on vertex textures. Hopefully i'll be done with this soon.

**Comment by Bryceless** [comment]
I managed to get to the title screen, but other than that, I have nothing to report on.
![image](https://cloud.githubusercontent.com/assets/5755974/18453459/69279fca-790d-11e6-8d79-8a313563bf94.png)

The logo and title runs at nearly full speed using an AMD Athlon X4 860K and a GTX 750ti, but dips down to 25 - 45FPS when at the main menu. It could just be my CPU that is causing the framerate issues, so I plan on upgrading to an Intel i5 or i7 pretty soon.

**Comment by Nezarn** [comment]
@raven02 can you remove ogl and vulkan label? (since this only true for DX12 only, since theres no vertex texture support there yet)

**Comment by kd-11** [comment]
https://github.com/kd-11/rpcs3/commit/7f4a20e8e4cb9f229529b44d63353a429fa92c2c implements vertex textures partially, but I kept messing up the resource binding due to the way the backend has been optimized, so no texture is actually bound to the vertex shader. This means the game still wont run. Hopefully someone will reimplement it or finish it.

**Comment by Bryceless** [comment]
I've noticed that on the latest build, when trying to load up a PV in Dreamy Theater 2nd, it throws the Vertex Issue, but when at the main menu it works perfectly fine.

**Comment by Nezarn** [comment]
Both 2nd and Extend are working fine on latest master.

**Comment by AniLeo** [comment]
Seems like the issue here was fixed, the games are going ingame, will now close the issue
