### ISSUE TITLE
TNT Racers [NPEB00221] has regressed since merging PR #1828

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#1853]
TNT racers now shows black screen on all backends since https://github.com/RPCS3/rpcs3/pull/1828 was merged. I know that RSX is currently wip, but this should help track the issue.

**Comment by raven02** [comment]
@DHrpcs3 . FYI

Looks like it is the changes of rsx_method , i revert some code there and it works again.

**Comment by kd-11** [comment]
For inlined arrays, the number of vertices to draw is determined by checking the length of the array and the stride, not first_count_commands. My guess is those are the draw calls that get skipped

**Comment by raven02** [comment]
I think it is rsxthr->vertex_draw_count

**Comment by raven02** [comment]
TNT racers should be working again in latest build

**Comment by raven02** [comment]
Looks like it works in DX12 only .Vulkan and GL are flashing.

**Comment by raven02** [comment]
Boot up okay now for all backends.
