### ISSUE TITLE
GL: Outrun Arcade broken in-game texture

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1855]
Vulkan (correct)
![3](https://cloud.githubusercontent.com/assets/3000282/16521935/f0032c96-3fcc-11e6-9610-5b0e7c282404.jpg)

DX12 (correct)
![untitled](https://cloud.githubusercontent.com/assets/3000282/16901669/bc5ac7ac-4c7c-11e6-859f-8a2b5a2119e8.jpg)

GL (road color issue)
![untitled](https://cloud.githubusercontent.com/assets/3000282/18028546/4404d3d0-6cb4-11e6-88be-81659db5ce62.jpg)

**Comment by raven02** [comment]
Another issue would be the missing front/back diffuse and specular color for Vulkan and GL

**Comment by raven02** [comment]
DX12 that one without HUD and sky probably a regression as i remember it works well before just like Vulkan

**Comment by kd-11** [comment]
GL was okay before, but is undergoing rewrites by DH so thats expected. As for Dx12, well, remember my comments about constant color blend hacks and missing visuals? Thats the result. Constant color and alpha blend is used to mostly fade stuff in and out or add color glow effects.

**Comment by kd-11** [comment]
By the way, GL bug looks like bad face culling. Check if your culling update fixed it. If so, then culling in dx12 and vulkan is correct.

**Comment by raven02** [comment]
Alright . Will check out the culling in GL as well.

**Comment by raven02** [comment]
> EDIT: By the way, the sky was never correct on dx12. Some hud elements were also missing although some were visible.

In this thread , DX12 looks okay with HUD and sky in-game (though with his hack on constant color)

![capture d ecran 2016-02-01 20 10 27](https://cloud.githubusercontent.com/assets/3000282/16541794/a854a286-40c0-11e6-8c08-0e62f9fcf095.png)

**Comment by kd-11** [comment]
Hmm. I tested it a bit after that and the sky was wrong by then. By the way this is not necessarily a sign of regression. Remember we have fixed the render target formats to be more accurate. My guess is that that is what "broke" this game. Remember that zangetsu's hack uses alpha from the render target to apply blending. More accurate emulation will always break blind hacks.

**Comment by raven02** [comment]
Yep , i'll take some time today to checkout as well to see if can fix it for DX12.

**Comment by raven02** [comment]
Just tried out to build older branch on my own and apply the blending hack .However , it seems to always hit the build_pipeline . Will try few more build to see if can get away this error and in-game

{rsx::thread} Exception: HRESULT = 0x80070057
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:185, in function D3D12Traits::build_pipeline)

**Comment by raven02** [comment]
OGL seems to be broken in latest build now in the car selection screen. 

{rsx::thread} class gl::glsl::compilation_exception thrown: compilation failed: 'ERROR: 0:17: 'r8' : syntax error syntax error

**Comment by kd-11** [comment]
I have some fixes for some of the GL bugs, although graphics still flash alot. Will submit soon after further testing

**Comment by kd-11** [comment]
The GL issue is part of https://github.com/RPCS3/rpcs3/issues/1906
With a workaround, the game is back to normal, with the exception of minor lighting bugs on cars.

**Comment by raven02** [comment]
Cool . @kd-11

**Comment by raven02** [comment]
With your PR , it looks good on GL

![untitled](https://cloud.githubusercontent.com/assets/3000282/16847076/ba71d5f0-4a21-11e6-90fe-4790de506ffc.jpg)

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/issues/1907 has been reworked and fixes this game in opengl

**Comment by raven02** [comment]
DX12 and Vulkan all looks good . Only GL issue remains

**Comment by kd-11** [comment]
GL lighting is also dimmed. I'm guessing its something to do with front and back lighting.

**Comment by raven02** [comment]
Updated GL screenshot .It is now road color issue .

**Comment by kd-11** [comment]
Road color is probably tied to border color. If not, there could be an issue with different texture creation vs sampling parameters. Hopefully the first, since the second case is much harder to fix.

**Comment by raven02** [comment]
Road color and two side lighting fixed by https://github.com/RPCS3/rpcs3/pull/2155

![untitled](https://cloud.githubusercontent.com/assets/3000282/18819419/56e39f2e-83c3-11e6-8de9-b1e3713fab67.jpg)
