### ISSUE TITLE
Supporting SSE3 or SSE4.1a?

### ISSUE THREAD

**Issue by ChrisLeOtaku** [RPCS3/rpcs3#1859]
My processor is a Quad Core 2.5GHz AMD A8-3820 (Side information, its running at 3.0 with some tweaks and overclocking.) When ever I try to initialize a game, or try installing a .pkg I always get an error with my processor not supporting SSSE3... I realize that my processor may be older, but is it possible to get those instruction sets to run the emulator, or allow it to function properly?

**Comment by AniLeo** [comment]
SSE3 and SSSE3 are two different things. Your CPU supports SSE3 but not SSSE3.
SSE4.1a isn't needed anymore as of the latest month, but SSSE3 is still a must.

**Comment by ChrisLeOtaku** [comment]
So in other words the best thing I can do is wait till I get enough for a new PC? My motherboard is pretty sad, and the best thing I can upgrade to CPU wise is only a difference in clock speed with actual overclocking support. I'm pretty sure they support the same thing, and that means that SSSE3 isn't supported.

**Comment by AniLeo** [comment]
That's a FM1 socket, which is **really old**. I wouldn't do a CPU upgrade only, it's not worth.
When you upgrade you'll need to move on to a new socket which means new board, ram and cpu.

**Comment by ChrisLeOtaku** [comment]
I'm thinking about custom building a PC but the only problem is getting the money. If i'm going to build it my self I going all in. (Bringing the big guns.)

**Comment by Nekotekina** [comment]
It's possible that rpcs3 will not require SSSE3 in future after some refactoring. I don't think it's so important to support old CPUs, but an attempt to compile rpcs3 against ARM (64 bit), PowerPC or some other arch may trigger such portability relaxation.

**Comment by prodrigestivill** [comment]
Meanwhile one can use Intel SDE Emulator to emulate SSSE3 & SSE4.1a extensions:
http://www.intel.com/software/sde

If your CPU is that old, better only emulate Intel Nehalem CPU using this flag: -nhm

**Comment by AniLeo** [comment]
RPCS3 now supports CPUs without SSSE3 like the mentioned A8-3820, and PPU LLVM Recompiler picks the best instructions depending on your CPU, so this issue is now solved.

Feel free to open a new issue if new issues arise, but remember, older CPUs without SSSE3 do **not** have performance to properly run RPCS3, there's no magic.
