### ISSUE TITLE
DX12: Lego the hobbit user handler not set

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1860]
-Lego the hobbit
-LEGO Star Wars III: The Clone Wars

{rsx::thread} class std::runtime_error thrown: Precondition failed: rsx::method_registers[NV4097_SET_VERTEX_DATA_BASE_INDEX] == 0
(in file C:\rpcs3\rpcs3\Emu\RSX\Common\BufferUtils.cpp:356)

<a href='http://www69.zippyshare.com/v/fN7i0Tls/file.html'><img src='http://www69.zippyshare.com/thumb/fN7i0Tls/file.html' border='0' /></a>
<a href='http://www69.zippyshare.com/v/xdCMrVfd/file.html'><img src='http://www69.zippyshare.com/thumb/xdCMrVfd/file.html' border='0' /></a>

**Comment by raven02** [comment]
Just wonder which LLE modules you used ? i got the following when boot

{rsx::thread} class fmt::exception thrown: rsx::user_command(): User handler not set
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:781)

**Comment by SakataGintokiYT** [comment]
@raven02 I edited the line 781 in rsx_methods  :P

**Comment by raven02** [comment]
I remember this user_command got added in rsx_method in commit https://github.com/RPCS3/rpcs3/commit/ec0005195dbf99f90cb0631e700b958bfd38f65d
