### ISSUE TITLE
PPU Recompiler : Project Diva F crash 

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1863]
![image](https://cloud.githubusercontent.com/assets/11285640/16543861/d997d140-4117-11e6-9435-6aa8a79fcbe1.png)
{PPU[0x388] Thread (2598e5c0)} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK
{PPU[0x388] Thread (2598e5c0)} sys_process: Process finished
PPU Recompiler , SPU Recompiler , using dmux , dmuxpamf LLE modules

**Comment by raven02** [comment]
what do you mean by out of windows?

**Comment by zminhquanz** [comment]
when i'm playing finish that game , it's going to closing automatic , and appear the log error

**Comment by raven02** [comment]
I think it would be better to use the interpreter for PPU . Recompiler may not work for this game.

**Comment by zminhquanz** [comment]
@raven02 oh , before i'm using PPU Interpreter 2 and it's not appear this error

**Comment by raven02** [comment]
Close this one and consolidate all these new PPU LLVM in another single thread.
