### ISSUE TITLE
PPU: LLVM recompiler issue

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1870]
All PPU LLVM issues will be consolidated here .

Please report if any and i will update the above list (make sure tested with interpreter and works okay before checkout the recompiler)

Fixed

- The Awakened Fate: Ultimatum 

Not fixed yet

- Silent Hill: Homecoming - **Null function**
- Initial D - **Null function**
- DBZ - Burst Limit -  **black screen**
- Dragon Ball Raging Blast - **access violation writing location 0x0**
- J-STARS Victory VS+ - **access violation writing location 0x0**
- Daytona USA -  **in-game flickering**
- House of Dead 3 - **stuck at 642/2000 on loading LLVM 19D058**
- Naruto: Ultimate Ninja Storm
- Naruto Shippuden: Ultimate Ninja Storm 2
- Naruto Shippuden: Ultimate Ninja Storm 3
- Naruto Shippuden: Ultimate Ninja Storm Generations

**Comment by raven02** [comment]
All PPU LLVM issues will be consolidated here .Please report if any

**Comment by zminhquanz** [comment]
on Project Diva F , sometime it will get this error

{PPU[0x388] Thread (2598e5c0)} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK
{PPU[0x388] Thread (2598e5c0)} sys_process: Process finished

 and

 {PPU[0x5] Thread (main_thread) [0x006cc1b0]} struct vm::access_violation thrown: Access violation reading address 0x746c5ffc
 {PPU[0x5] Thread (main_thread) [0x006cc1b0]} struct vm::access_violation thrown: Access violation reading address 0x1a0

**Comment by SakataGintokiYT** [comment]
@raven02 
@Nekotekina 

*All this games works in PPU Interpreter [Fast]

Naruto: Ultimate Ninja Storm  [Black screen]
LLVM: Symbol requested __chkstk -> 0x00007ff96a7c9a00

Log: https://gist.github.com/SakataGintokiYT/c3265816cea410c0b0365b12c7da8f52
LLVM.Log : https://mega.nz/#!4AwAzaoa!hBlmGYRX1OtI6_Lj20Hiybq4h3Dap9MkLqltnXLDJHg
______________________________________________________________________________

Naruto Shippuden: Ultimate Ninja Storm 2  [Black screen]
LLVM: Symbol requested __chkstk -> 0x00007ff96a7c9a00

Log: https://gist.github.com/SakataGintokiYT/57d4d0e32f4e8c4f35fac4f7757301f0
LLVM.Log : https://mega.nz/#!sF40AIbD!gT3IX0Sx_0s9yjoriaeV3D15QbpJcoXG5oP0trwfHNA
______________________________________________________________________________

Naruto Shippuden: Ultimate Ninja Storm 3  [Black screen]
LLVM: Symbol requested __chkstk -> 0x00007ff96a7c9a00

Log: https://gist.github.com/SakataGintokiYT/f98d7d22dcc7be3e9c7e6d4ca6ae0a4b
LLVM.Log : https://mega.nz/#!4QIyCLoS!nQ7Oo5WfOS7wOD9wtVjps7BrYUnXgqyxSNLRVOJcpjM

______________________________________________________________________________

Naruto Shippuden: Ultimate Ninja Storm Generations [Black screen]
LLVM: Linkage failed for __lswi
LLVM: Linkage failed for __stswi
LLVM: Symbol requested __chkstk -> 0x00007ff96a7c9a00

Log: https://gist.github.com/SakataGintokiYT/52ff96d10c04400e4128648f91ffc788
LLVM.Log : https://mega.nz/#!EZgyRKBT!nYxS294eFQ6xxrk5le8aCTCREBepK1Cyjqub7-_rCco

______________________________________________________________________________

**Comment by Nekotekina** [comment]
Thanks.
@SakataGintokiYT RPCS3.log is enough atm, LLVM.log is unnecessary

**Comment by Ekaseo** [comment]
King of Fighters XIII has the same issues as the other games mentioned above

**Comment by zminhquanz** [comment]
{PPU[0x104] Thread (200baad0)} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK
{PPU[0x104] Thread (200baad0)} sys_process: Process finished

Project Diva F

**Comment by Nekotekina** [comment]
Some old homebrews are pure mess, it's hard to analyse them. For example, Free Heroes 2 or Freedroid Classic.

**Comment by Nekotekina** [comment]
Update: added support for them in #1918

**Comment by raven02** [comment]
@Nekotekina .I have updated the list and up to now only DBZ burst limit is not working with LLVM PPU , iit boots up but black screen ,

**Comment by Nezarn** [comment]
@Nekotekina Are these implemented? (i get this in the log with LLVM)
>·E PPU: [0x0062e734] 0x0062e764: Error: MTFSF
>·E PPU: [0x0062e770] 0x0062e770: Error: MFFS

I get them as warning with interpreter:
>·W {PPU[0x5] Thread (main_thread) [0x0062e770]} PPU: MFFS
>·W {PPU[0x5] Thread (main_thread) [0x0062e764]} PPU: MTFSF

**Comment by PZerua** [comment]
All games crash for me after loading with this error:

![b96a0a664843f2a81f83565e3ea86c68](https://cloud.githubusercontent.com/assets/8772233/17051616/e0ccf9ae-4ff9-11e6-857e-c5cfa0b592fd.png)

I tried with ARKEDO 01 (seems to work for everybody) and many other games. My CPU is Intel i7-6700HQ (I think all i7s support SSSE3).

Here is the log for ARKEDO 01:
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/377844/RPCS3.txt)

**Comment by Kristiqn5** [comment]
@PZerua same thing happens, every game that I run with LLVM shows this fatal error :/ and then the emulator crashes ( stopped working )

**Comment by Kristiqn5** [comment]
@PZerua your CPU does support SSSE3 , so does mine ( Celeron G1820 ) but still getting same error, I can use LLVM on earlier builds where rpcs3 doesn't compile before launch

**Comment by raven02** [comment]
Title : House of dead 3

Interpreter works fine , LLVM PPU hits the following error specifically .

F {PPU[0x4] Thread (main_thread)} class fmt::exception thrown: Unreachable! (0x2c8cb4)

**Comment by raven02** [comment]
![image](https://cloud.githubusercontent.com/assets/11285640/17508621/0acca00c-5e40-11e6-895e-0dcc03855554.png)
Problem can't solve in the latest build , PPU LLVM Recompiler is having issue ( sometimes) , but PPU Interpreter 2 is normally , no issue

**Comment by Two-Tone** [comment]
Running latest build ( 5f15c66 ) on win7 x64

When trying to boot Katamari Forever (BLUS30336), PPU LLVM Recompiler stalls rpcs3 for several minutes. When trying to close the window, rpcs3 then stalls indefinitely and proceeds to very quickly consume all of my RAM (I have 18 gigs). This does not happen with the two interpreter options.

**Comment by SakataGintokiYT** [comment]
@Nekotekina 
LLVM 3.9 ready to merge ? 
https://github.com/Zangetsu38/rpcs3/tree/llvm39

**Comment by Nekotekina** [comment]
Last time I tested LLVM 3.9 it had absolutely terrible memory consumption or even a leak, an order of magnitude worse than current 3.8. Need to test.

**Comment by SakataGintokiYT** [comment]
@Nekotekina 
You send me build with  llvm 3.9 for test  ?  ;3

**Comment by SakataGintokiYT** [comment]
@vlj 
@daniel-dressler    
Do you know how to fix it ?

[ 22b14000 ]
```
E PPU: [0x007556ac] 0x007556dc: Error: MTFSF
E PPU: [0x00755bf0] 0x00755bf0: Error: MFFS
E LLVM: Symbol requested __chkstk -> 0x00007ffb6a1a99f0
S LLVM: UNWIND_INFO registered (0000000011144000, size=0x94fc8)
```
**Naruto Shippuden: Ultimate Ninja Storm Generations** [Black screen]
**Console output:** https://gist.github.com/SakataGintokiYT/6185cd1bb73eaf5f80f4f308fd5ace94
**Log :** https://gist.github.com/SakataGintokiYT/df5f58fa7c7e2599617cfe88bb42a0ef

**Comment by SakataGintokiYT** [comment]
@vlj 
@danilaml   
Do you know how to fix it ?

[ 22b14000 ]
```
E PPU: [0x007556ac] 0x007556dc: Error: MTFSF
E PPU: [0x00755bf0] 0x00755bf0: Error: MFFS

E LLVM: Symbol requested __chkstk -> 0x00007ffb6a1a99f0
S LLVM: UNWIND_INFO registered (0000000011144000, size=0x94fc8)
```
**Naruto Shippuden: Ultimate Ninja Storm Generations** [Black screen]

**[*Console output](https://gist.github.com/SakataGintokiYT/6185cd1bb73eaf5f80f4f308fd5ace94)**
**[*Log](https://gist.github.com/SakataGintokiYT/df5f58fa7c7e2599617cfe88bb42a0ef)**

**Comment by SakataGintokiYT** [comment]
[Allow UE3 games to startup]-- [ b167b708 ]

@Nekotekina 

*Screenshots from Rpcs3
<img src="http://www.fotoszok.pl/upload/bf4c5be9.jpg" alt="Fotoszok.pl" />

```
.E PPU: [0x0039b978] 0x0039b9a8: Error: MTFSF
·E PPU: [0x0039bc08] 0x0039bc08: Error: MFFS
·E LLVM: Linkage failed for __stswi
·E LLVM: Symbol requested __chkstk -> 0x00007ffc68719a00
·E LLVM: Linkage failed for __lswi

·F {PPU[0x70000000] Thread (main_thread) [0x00010230]} class std::runtime_error thrown: Null function
(in file C:\rpcs3\Utilities\JIT.cpp:86)]
```
**[*Log](https://gist.github.com/SakataGintokiYT/99d4ae3b550bb6fb8da611b72700ed85)**

**Comment by Nekotekina** [comment]
Test

**Comment by SakataGintokiYT** [comment]
**[Daytona USA]**
**-Glitch and flickering textures on LLVM**
<img src="http://www.fotoszok.pl/upload/d71dca05.jpg" alt="Fotoszok.pl" />
**[PPU-Fast:](https://gist.github.com/SakataGintokiYT/59165f6e84372aba83ed3c84d2d539b2)**
**[PPU-LLVM:](https://gist.github.com/SakataGintokiYT/b389a5b3bc2b2c4815e8c0c98654f554)**

**Comment by raven02** [comment]
The LLVM loading is much more informative in latest build . 

![1](https://cloud.githubusercontent.com/assets/3000282/22194251/1586c878-e17c-11e6-9e7e-350986f24ff2.jpg)

**Comment by SakataGintokiYT** [comment]
[78ecb115]

**Naruto: Ultimate Ninja Storm**
[Log:](https://gist.github.com/SakataGintokiYT/dd2468cecc6e54bc7b0db5795a42a242)

**Naruto Shippuden: Ultimate Ninja Storm Generations**
[Log:](https://gist.github.com/SakataGintokiYT/732b967273a031a229cecf837ebb7680)

**Dragon Ball Z: Burst limit**
[Log:](https://gist.github.com/SakataGintokiYT/c5af9a571aed330cfd30496d0d460ed2)

**Comment by raven02** [comment]
House of Dead 3 cannot boot up in LLVM 

`F {PPU[0x1000000] Thread (main_thread) [0x003b64e4]} class std::runtime_error thrown: Unreachable! (0x2c8cb4)`

**Comment by raven02** [comment]
Dragon Ball Raging Blast fail to boot up in LLVM

`F {PPU[0x100000c] Thread (sp_job_server thread) [0x0051a110]} struct vm::access_violation thrown: Access violation writing address 0x0`

**Comment by raven02** [comment]
Outrun Arcade fail to boot up in LLVM (Interpreter fast is ok)

F {PPU[0x1000000] Thread (main_thread)} class std::out_of_range thrown: invalid unordered_map<K, T> key

**Comment by raven02** [comment]
The Awakened Fate: Ultimatum hangs before 'Now Loading" and cannot proceed using LLVM while interpreter fast can proceed in-game.

**Comment by raven02** [comment]
Re-test with The Awakened Fate: Ultimatum and it is now fully working in LLVM .

**Comment by raven02** [comment]
Re-test the following games in LLVM with https://github.com/RPCS3/rpcs3/pull/2576

DBZ - Burst Limit - still black screen
Dragon Ball Raging Blast - still access violation 0x0

**Comment by raven02** [comment]
For House of Dead 3 , it is specially stuck at this point everything load using LLVM
![untitled](https://cloud.githubusercontent.com/assets/3000282/24283178/3cb7b5d6-109f-11e7-8f72-d08b4bc8075a.png)

**Comment by darkredflame** [comment]
Don't know if this helps, but when I used LLVM on House of the Dead 3, it froze at the same point as above, RPCS3 also consumed a lot of RAM in the process, approximately 9.5GB total before other programs on my computer started crashing.

**Comment by Megamouse** [comment]
Malicious [NPUA80797] gets to the adjust screen with interpreter as known.
In LLVM it does not get this far. Instead I get this:

`F {PPU[0x1000000] Thread (main_thread) [0x00054c88]} class std::runtime_error thrown: Unregistered PPU function [0x00054c88]`

**Comment by Zangetsu38** [comment]
LLVM DQB
>F {PPU[0x1000000] Thread (main_thread) [0x004b9bcc]} MEM: Access violation writing location 0xe329f6a8

**Comment by aakh1361** [comment]
Silent Hill: Homecoming

same old result

> E {PPU[0x1000000] Thread (main_thread)} PPU: [0x00030a60] 0x00030a64: Error: Unknown/illegal opcode 0x00000000
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __stswi
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __lswi

> E {PPU[0x1000000] Thread (main_thread)} PPU: [0x0039b978] 0x0039b9a8: Error: MTFSF
E {PPU[0x1000000] Thread (main_thread)} PPU: [0x0039bc08] 0x0039bc08: Error: MFFS

> E {PPU[0x1000000] Thread (main_thread) [0x00010230]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH
E {PPU[0x1000000] Thread (main_thread) [0x00010230]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH
F {PPU[0x1000000] Thread (main_thread) [0x00010230]} class std::runtime_error thrown: Null function
(in file C:\rpcs3\Utilities\JIT.cpp:77)

**Comment by Zangetsu38** [comment]
Dragon ball Raging Blast
>RPCS3 v0.0.2-5089-cea663a3 Alpha
E LDR: Unknown module 'cellLibprof'
E LDR: Unknown function '0x05893E7C' in module 'cellLibprof'
E LDR: Unknown function '0x6D045C2E' in module 'cellLibprof'
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: JIT initialized (znver1)
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-10200-CAF4E8008C584705.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-CEFC8-4CE1D9D82A609BFA.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-137520-D17C278F1C2A5445.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-1C3460-0C45F3D6CE8004FE.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-242C00-8BADF7B7D8856008.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-2C81D8-B02484BEBFAD70CE.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-360DB8-EFD87E88D5816DAB.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-3E9658-5697C1A8883586BC.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-4554C0-5FF9A99ACBDCEE15.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-4CD088-7656756BBC7D2C28.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-523330-2A71E053C49CF008.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-58B180-3889F5899A2504BE.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-libfiber.sprx-620E30D3DCB3CDA1.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-libl10n.sprx-4FE68991EAFCB1B9.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-librtc.sprx-CF7E15E891D42AE3.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-libsre.sprx-B9A49A56961D104A.obj
U {PPU[0x1000000] Thread (main_thread) [0x00010230]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x00010230]} sysPrxForUser TODO: _sys_process_at_Exitspawn
S {Audio Thread} XAudio 2.9 initialized
U {PPU[0x1000000] Thread (main_thread) [0x00010230]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00010230]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00010230]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00010230]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00010230]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00010230]} sys_prx TODO: sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x00010230]} sys_prx TODO: sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
F {PPU[0x100000c] Thread (sp_job_server thread) [0x0051a848]} MEM: Access violation writing location 0x0
S {SPU[0x2000000] Thread (SP_LIB CellSpursKernel0)} SPU: SPU Database initialized...
S {SPU[0x2000000] Thread (SP_LIB CellSpursKernel0)} SPU: Function detected [0x00818-0x0084c] (size=0x34)
S {SPU[0x2000000] Thread (SP_LIB CellSpursKernel0)} SPU: SPU Recompiler (ASMJIT) created...
S {SPU[0x2000000] Thread (SP_LIB CellSpursKernel0)} SPU: Function detected [0x006c0-0x00818] (size=0x158)
S {SPU[0x2000000] Thread (SP_LIB CellSpursKernel0)} SPU: Function detected [0x00a00-0x01230] (size=0x830)
S {SPU[0x2000002] Thread (SP_LIB CellSpursKernel2)} SPU: Function detected [0x01230-0x01470] (size=0x240)

**Comment by Zangetsu38** [comment]
Iniutial D 
>F {PPU[0x1000000] Thread (main_thread) [0x00010230]} class std::runtime_error thrown: Null function
(in file ..\Utilities\JIT.cpp:77)

**Comment by Megamouse** [comment]
Ninja Gaiden 3 [BLUS31175]
> `F {PPU[0x1000000] Thread (main_thread) [0x0001022c]} class std::runtime_error thrown: Unregistered PPU function [0x0001022c]`

**Comment by Zangetsu38** [comment]
resistance Fall of man 
F {PPU[0x1000000] Thread (main_thread) [0x00010280]} class std::runtime_error thrown: Unregistered PPU function [0x00010280]

**Comment by woody2014** [comment]
[NPUB30849]Zombie Tycoon 2
[NPEB00414]Putty Squad
[NPUB30523]Far Cry 2

**Comment by Nekotekina** [comment]
Need to update issue

**Comment by Megamouse** [comment]
Ninja Gaiden 3 [BLUS31175] now throws:
F {PPU[0x1000000] Thread (main_thread) [0x0001022c]} MEM: Access violation reading location 0x0

**Comment by twdarkeh** [comment]
Lost Dimension [BLUS31554]:

F {PPU[0x1000000] Thread (main_thread) [0x0026d76c]} MEM: Access violation reading location 0xc

**Comment by digitaldude555** [comment]
@raven02 
@Nekotekina 
Retesting games.

Initial D Extreme Stage - [BLJM60055]

`F {PPU[0x1000000] Thread (main_thread) [0x00010230]} class std::runtime_error thrown: Null function
(in file C:\rpcs3\Utilities\JIT.cpp:77)
`

Persona 5 [NPEB02436]

`F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: libfiber.sprx is not compatible with PPU LLVM Recompiler.`

Dragon Ball Z Burst Limit [BLUS30117]

Black screen with sound.

Dragon Ball Raging Blast [BLUS30431]

`F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: libfiber.sprx is not compatible with PPU LLVM Recompiler.`

GUILTY GEAR XX Λ CORE PLUS [NPUB30957]

`F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: libfiber.sprx is not compatible with PPU LLVM Recompiler.
`

J-Stars Victory VS Plus [BLES02136]
`F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: libfiber.sprx is not compatible with PPU LLVM Recompiler.`

Silent Hill Homecoming [BLES00460]
`F {PPU[0x1000000] Thread (main_thread) [0x00010230]} class std::runtime_error thrown: Null function
(in file C:\rpcs3\Utilities\JIT.cpp:77)
`

Malicious [NPUA80797]
`F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: libfiber.sprx is not compatible with PPU LLVM Recompiler.`

**Comment by raven02** [comment]
Retested Daytona USA and House of Dead 3 , still the same issue .

Daytona USA - in-game flickering
House of Dead 3 .- stuck at 642/2000 on loading LLVM 19D058

**Comment by raven02** [comment]
Demon's Souls [BLES00932] freezes 100% when exiting to main menu.

**Comment by isshininu** [comment]
> Demon's Souls [BLES00932] freezes 100% when exiting to main menu.
A-ah, finally find a consolidated thread.
It's not only freezes when exiting to main menu, but also it'll do it when trying fast travel to/from Nexus, and also after any in-game video (I mean, opening cinematic and intro video before tutorial level works just fine, but it was impossible to watch/skip normally video that runs after activating gates of Boletarian Palace, level 1-1).

**Comment by Xcedf** [comment]
Metal Gear Risisng and Bayonetta
both rquire fiber to run even with interpreter
F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: libfiber.sprx is not compatible with PPU LLVM Recompiler.

**Comment by M9k** [comment]
Same with Persona 5 NPUB31848 with LLVM
F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: libfiber.sprx is not compatible with PPU LLVM Recompiler.

**Comment by davoodinator** [comment]
Dragon's crown
BLUS30767
RPCS3 v0.0.2-3-f0f8f50 Alpha
S Successfully installed PS3 firmware.
F PPU: libfiber.sprx is not compatible with PPU LLVM Recompiler. Use PPU Interpreter.

**Comment by aakh1361** [comment]
Resident Evil 5 [BLUS30491]
> F PPU: libfiber.sprx is not compatible with PPU LLVM Recompiler. Use PPU Interpreter.

**Comment by deadair3210** [comment]
Oden Spear has the libfiber issue as well

**Comment by isshininu** [comment]
F {PPU[0x1000005] Thread (HighGraphics) [0x00d51fc0]} PPU: libfiber.sprx is not compatible with PPU LLVM Recompiler. Use PPU Interpreter.

Dark Souls I [BLES01765] now goes ingame! But have the same issue with LLVM recompiler.

**Comment by davoodinator** [comment]
Same problem with the npub version of dragon's crown

NPUB31235

**Comment by aakh1361** [comment]
RPCS3 v0.0.2-5182-2845617 Alpha
NASCAR '15 [NPUB91029]
> Thread (main_thread) [0x01a10000]} class std::runtime_error thrown: Unregistered PPU function
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/969830/RPCS3.zip)

**Comment by Grima04** [comment]
RPCS3 v0.0.2-6-184ab65 Alpha

Red Dead Redemption [BLES00680]
F {PPU[0x1000000] Thread (main_thread) [0x00db5418]} MEM: Access violation reading location 0x0
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/971130/RPCS3.zip)

Red Dead Redemption [BLES01294]
F {PPU[0x1000000] Thread (main_thread) [0x00d2ec64]} MEM: Access violation reading location 0x0
[RPCS3_2.zip](https://github.com/RPCS3/rpcs3/files/971148/RPCS3_2.zip)

**Comment by aakh1361** [comment]
RPCS3 v0.0.2-5211-d24ba0d Alpha

DEAD OR ALIVE 5 Ultimate [NPEB01786]

> F {PPU[0x1000000] Thread (main_thread) [0x026e5000]} class std::runtime_error thrown: Unregistered PPU function
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/998858/RPCS3.zip)

**Comment by mikzoul** [comment]
RPCS3 v0.0.2-3-b9ebf59

sword art online lost song [BLAS50790]

F {PPU[0x1000034] Thread (LoadResidentData) [0x009024a4]} MEM: Access violation writing location 0x78

stuck in loading screen. can you help me?

**Comment by AniLeo** [comment]
That's not a PPU LLVM issue, it happens on Interpreter as well.
Gets stuck on a libnet/sys_net loop when on loading screen.

**Comment by aakh1361** [comment]
Kamen Rider Battride War 2 Premium TV and Movie Sound Edition [BLJS10263]

> F PPU: libfiber.sprx is not compatible with PPU LLVM Recompiler. Use PPU Interpreter.

**Comment by Zangetsu38** [comment]
No more heros paradise Demo, i think is same for complette game
>F {PPU[0x1000000] Thread (main_thread) [0x004deb90]} MEM: Access violation reading location 0x5c

**Comment by LeOsmos** [comment]
JoJo's Bizzare Adventure All Star Battle (BLUS 31405) has no video (black screen) but audio works fine. If i try to load into a battle it crashes with:

F {PPU[0x1000000] Thread (main_thread) [0x0084ddf8]} MEM: Access violation writing location 0x2c0
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1031986/RPCS3.zip)

**Comment by Zangetsu38** [comment]
Dead Nation
>F {PPU[0x1000000] Thread (main_thread) [0x0018a180]} class std::runtime_error thrown: Unregistered PPU function

**Comment by ahmeedalabdy** [comment]
S sys_process: Process finished
please some one fix this issue

**Comment by raveskirza** [comment]
In Soul Calibur 4 with PPU LLVM, there is only a black screen, while the FPS counter and audio works properly
In Soul Calibur II HD online get the below message
F PPU: libfiber.sprx is not compatible with PPU LLVM Recompiler. Use PPU Interpreter.

**Comment by Grima04** [comment]
Grand Theft Auto IV BLUS30127

E {PPU[0x1000000] Thread (main_thread) [0x00988bf0]} PPU: Unregistered function called (LR=0xa15f78)
F {PPU[0x1000000] Thread (main_thread) [0x00988bf0]} MEM: Access violation writing location 0x402

LOG:
[RPCS3_GTAIV_22-06-2017.zip](https://github.com/RPCS3/rpcs3/files/1094709/RPCS3_GTAIV_22-06-2017.zip)

**Comment by AniLeo** [comment]
PPU Recompiler got a major overhaul, closing this because most games got fixed and we still haven't found a game that's still broken on it.

For issues with the updated Recompiler, open a new issue.

**Comment by arpioer** [comment]
F {PPU[0x1000017] Thread (RenderThread) [0x00159228]} MEM: Access violation writing location 0x30482d
fifa street error rpcs3. Can anyone help me?

**Comment by kroaton** [comment]
F {PPU[0x1000010] Thread (LoopSimulation) [0x000853e4]} MEM: Access violation reading location 0xa6a97e64 - Fight Night Round 4

**Comment by ElTioRata** [comment]
F {PPU[0x1000000] Thread (main_thread) [0x005a7bc0]} MEM: Access violation reading location 0xc4
Tony Hawk's Proving Ground

**Comment by AniLeo** [comment]
Golden shovel award x2...
