### ISSUE TITLE
HLE : pngDecOpen(): Partial image decoding is not supported

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1871]
```
·F {PPU[0x56] Thread (MyUserInterface) [0x00a7d7b0]} class fmt::exception thrown: pngDecOpen(): Partial image decoding is not supported.
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellPngDec.cpp:297)
```

NPUB30188 - Family Feud
**LLE**: libresc

Log @ [RPCS3.txt](https://github.com/RPCS3/rpcs3/files/354548/RPCS3.txt) (it's not letting me upload .zip files)

It crashes the emulator with an C0000005 access violation

If pngDec is LLE loaded it crashes with

```
·F {PPU[0x70] Thread (MyUserInterface) [0x0089c860]} class std::runtime_error thrown: Trap!
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:2161)
```

**Comment by raven02** [comment]
Same trap for PPU LLVM as well.

{PPU[0x4] Thread (main_thread)} class fmt::exception thrown: Trap! (0x89c860)

**Comment by AniLeo** [comment]
Still an issue
```
F {PPU[0x1000008] Thread (MyUserInterface) [0x00a7d7b0]} class std::runtime_error thrown: Partial image decoding is not supported.
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellPngDec.cpp:297)
```

Doesn't seem to throw Trap exception anymore
