### ISSUE TITLE
Vulkan: 1942 Join Strike unsupported compare op: 0x5

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1875]
This game works fine with DX12 using sre+spuqs (GL is black screen)

{rsx::thread} class fmt::exception thrown: vk::compare_op(): Unsupported compare op: 0x5

**Comment by raven02** [comment]
Note , with the compare op fix .Vulkan boots up okay but still black screen that same as GL backend

**Comment by kd-11** [comment]
Black screen should have been fixed now. Check if graphical bugs persist.
