### ISSUE TITLE
File access error: スーパーロボット大戦OG INFINITE BATTLE

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1886]
It boots up okay and perform sort of installation with dialog then pop up the error dialog.

{PPU[0x6] Thread (main_thread) [0x004a2568]} cellSysutil: ファイルアクセスで致命的なエラーが発生しました。
このままゲームを進行することはできません。
PS ボタンでゲームを終了してください。

エラーコード：2011022805

**Comment by raven02** [comment]
Translated 

A fatal error occurred in the file access.
It is not possible to proceed in this state game.
Please exit the game with the PS button.

Error code: 2011022805

**Comment by MarioSonic2987** [comment]
Is it still an issue?

**Comment by raven02** [comment]
Yes , still has this error prompted.

**Comment by AniLeo** [comment]
This issue is **Invalid** without further information actually.
Is this still an issue? If yes, we need **at least** a full log attached.

**Comment by AniLeo** [comment]
Reminder that we need more information, otherwise it will be closed and assumed fixed

**Comment by AniLeo** [comment]
Assuming fixed, Super Robot Taisen OG Infinite Battle is Ingame as of December 2017.
