### ISSUE TITLE
RSX: Super Street Fighter 2 Turbo HD unknown surface depth format.

### ISSUE THREAD

**Issue by ikki84** [RPCS3/rpcs3#1889]
{rsx::thread} class fmt::exception thrown: rsx::to_surface_depth_format(): Unknow surface depth format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:991)

**Comment by raven02** [comment]
@ikki84 , just wonder did u set any frame limit for the backend?

**Comment by raven02** [comment]
This title right ? 

![untitled](https://cloud.githubusercontent.com/assets/3000282/16733391/f981a542-47b3-11e6-9715-fddb52498692.jpg)

**Comment by raven02** [comment]
Sorry . I tested the commit right before the rsx code refactorize one that why it works .

**Comment by ikki84** [comment]
Yes, that title. It was working some builds ago. I dont remember when it stopped working but is recent.
Probably this month.
Frame Limit is off.

I think it works with the DHrpcs3 (WIP) build.

**Comment by raven02** [comment]
Is this help ? https://github.com/RPCS3/rpcs3/pull/1898

**Comment by raven02** [comment]
Should be fixed now in latest build
