### ISSUE TITLE
GL: Virtua Fighter 5: Final Showdown

### ISSUE THREAD

**Issue by fenix008** [RPCS3/rpcs3#1890]
After this commit (https://github.com/RPCS3/rpcs3/commit/6705a6ecc9a15191628ecd6f5a078b011c440f72) it doesn't work anymore. before it was showing black screen with fps and sounds and music at background.

·F {rsx::thread} class gl::glsl::compilation_exception thrown: compilation failed: '0(48) : error C7623: implicit narrowing of type from "vec4" to "float"

**Comment by kd-11** [comment]
That's because it now tries to draw to the screen. Clean up your shaderlog folder and run the game again, then attach the generated shaders (There should be several *.glsl files generated)

**Comment by fenix008** [comment]
alright, here it is.
http://rgho.st/85Qznyyzp

**Comment by kd-11** [comment]
@DHrpcs3 Vertex texture fetch here:
```
r0.x = texture_lod_fetch(0, in_pos, in_pos.w);
```

**Comment by DHrpcs3** [comment]
@kd-11, thanks!

Can anybody open issue with rsx_decompiler regression list?

**Comment by kd-11** [comment]
Will compile a list of issues related to the decompiler and open a combined issue.

**Comment by raven02** [comment]
D3D12 also hit similar error

{rsx::thread} RSX: VS build failed:D:\rpcs3\VertexProgram.hlsl(136,11-38): error X3037: constructors only defined for numeric base types

**Comment by fenix008** [comment]
Yes, you're right.

**Comment by kd-11** [comment]
Vertex textures have been implemented for opengl and vulkan. Please retest

**Comment by fenix008** [comment]
If u talking about last commit... http://www.emunewz.net/forum/showthread.php?tid=158744

**Comment by kd-11** [comment]
Then this issue about the regression after reverting the decompiler should be closed. The graphical bugs should have another ticket. Makes it easier for me to keep track of what's broken.
