### ISSUE TITLE
{PPU[0x1d0] Thread (PNG Decode Thread) [0x00472d80]} Date A Live: Rine Utopia [BLJM61048] 

### ISSUE THREAD

**Issue by lightfirst** [RPCS3/rpcs3#1891]
Testing Date A Live: Rine Utopia [BLJM61048] 
After  decrypt 4 sdat file and rename Movie folder I finally make this game loading and bgm appear but still blackscreen.
It's PNG not decode?
{PPU[0x1d0] Thread (PNG Decode Thread) [0x00472d80]} sys_spu: Unsupported SPU Thread options (0x2)
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/356969/RPCS3.log.zip)

**Comment by lightfirst** [comment]
[SPUJIT.log.7z.zip](https://github.com/RPCS3/rpcs3/files/357034/SPUJIT.log.7z.zip)

**Comment by raven02** [comment]
You can try load up the libpngdec LLE module

**Comment by lightfirst** [comment]
@raven02 load libpngdec still blackscreen
  Load libraries:
    - libat3dec.sprx.elf
    - libat3multidec.sprx.elf
    - libatrac3multi.sprx.elf
    - libatrac3plus.sprx.elf
    - libl10n.sprx.elf
    - libpngdec.sprx.elf
    - libpngenc.sprx.elf
    - libresc.sprx.elf
    - librtc.sprx.elf
    - libsail.sprx.elf
    - libsail_avi.sprx.elf
    - libsail_rec.sprx.elf
    - libspurs_jq.sprx.elf
    - libsre.sprx.elf
    - libssl.sprx.elf

**Comment by AniLeo** [comment]
#1677

**Comment by raven02** [comment]
Those are common SPU errors . i'm going to consolidate as one single issue instead of duplicate everywhere.

**Comment by lightfirst** [comment]
It will not blackscreen when using Opengl, the game is running but can't control it. no matter how I push Keyboard or PAD, noting happend.
![294a942bd40735fa4bdcd2c896510fb30f240861](https://cloud.githubusercontent.com/assets/4612168/16895447/ff2a665c-4ba8-11e6-8ea5-0500b02e0cc0.png)

I will open a new issue

**Comment by Sudoku45** [comment]
I got the same problem the game start i see the video and he stop working only black screen, i already tryed with the OpenGL and these libraries

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/967147/RPCS3.zip)
