### ISSUE TITLE
GL/rsx decompiler: Swizzle on trancedental function

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#1894]
@DHrpcs3
Prince of persia no longer goes ingame due to decompiled glsl shader bugs:
```
if (cc0.x >= 0.0) r2.xyz = fc384.xyz / sqrt(r1.y).xyz;
```
sqrt returns a scalar float and the vector access causes a compilation error. Full shader attached
[FragmentProgram.zip](https://github.com/RPCS3/rpcs3/files/357406/FragmentProgram.zip)

**Comment by DHrpcs3** [comment]
Is that error present on the latest rsx_decompiler commit?

**Comment by kd-11** [comment]
Still happens with updated rsx_decompiler

**Comment by kd-11** [comment]
With updated recompiler the output is

```
if (cc0.x >= 0.0) r2.xyz = fc384.xyz / sqrt(max(abs(r1.y), 1e-15) * sign(r1.y)).xyz;
```

**Comment by kd-11** [comment]
By the way, divsq sets the disable_swizzle_as_dst flag which I thought was supposed to disable the swizzle after the sqrt. Is it not working correctly or did I misunderstand its purpose?
