### ISSUE TITLE
Vulkan:  backend is no longer work with error

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1896]
It pop up the following error after the vulkan module update https://github.com/RPCS3/rpcs3/commit/11f7b167aece9ba34d78fda0e2278c334d7c8d36

```
{rsx::thread} RSX: ERROR: [Driver] Code 2 : Vertex info
-----------
(0) : fatal error C9999: Can't convert to expr: texelFetch
```

**Comment by Nekotekina** [comment]
It works for me. What do you test?

**Comment by raven02** [comment]
I tested on usual title like Arkedo on my NV system . @kd-11 and @ SakataGintokiYT  , did it work for you?

**Comment by SakataGintokiYT** [comment]
@raven02 
It's not working for me after vulkan modules update  , I have the same error 

[NV-368.69]
GTX 960M
{rsx::thread} RSX: ERROR: [Driver] Code 2 : Vertex info
-----------
(0) : fatal error C9999: Can't convert to expr: texelFetch

**Comment by raven02** [comment]
Thanks @SakataGintokiYT 

@Nekotekina , you one is AMD ?

**Comment by Nekotekina** [comment]
Yes, AMD. Someone could try different submodule Vulkan/glslang, for example, af3674d831cb1cc8508eba70248a87d3aa7431d5, or maybe the newest one.

**Comment by raven02** [comment]
Thanks will test it out to see which one work for NV then AMD

**Comment by dsyo2008** [comment]
I 368.69, run the same problem

**Comment by raven02** [comment]
I tried few combination from Vulkan/glslang , still not yet getting it to work on my system.

May be we can stuck to the original one at this moment?

**Comment by vlj** [comment]
What is the vertex shader content ?
There was a change with glslang afaik that now forbids texelFetch on texture without sampler.

**Comment by kd-11** [comment]
Unless something else is going on, i'm not sure why this would happen. The shaders are compiled to spir-v (on the cpu presumably) and the gpu is only fed the spir-v ouput. It works fine on my AMD but I have to wonder what is going on with the affected systems.

**Comment by paulsapps** [comment]
I've seen this error too, I think it only happens with newer NV driver - something about it used to be allowed but now isn't be because its not defined by the spec.

**Comment by kd-11** [comment]
I'll look at the generated spir-v and see if there is a difference

**Comment by kd-11** [comment]
There's almost no difference in the human-readable output, except for a declaration for capability sampledbuffer required. Anyway, this seems to be an issue with NV drivers and has been reported by others. See https://devtalk.nvidia.com/default/topic/948891/vulkan/fatal-error-c9999-with-spir-v-shader-doing-texelfetch-from-usampler2d-using-newer-glslangvalidator-/

**Comment by raven02** [comment]
I have done the bisect on glslang and found the one which breaks 

https://github.com/KhronosGroup/glslang/tree/a5c33d6ffb34ccede5b233bc724c907166b6e479

**Comment by raven02** [comment]
The last working commit from glslang is 

This is the rpcs3 build . Please test this on AMD system. (NV system is okay)

**Comment by raven02** [comment]
Issue on glslang opened here - https://github.com/KhronosGroup/glslang/issues/386

**Comment by kd-11** [comment]
@raven02 The issue is with NV driver and its up to them to fix it. The commit that broke vulkan on nvidia is probably the one to fix glslang issue https://github.com/KhronosGroup/glslang/issues/320. On devtalk nvidia claims to be investigating the issue, but we can go back to the last working version for now.

**Comment by raven02** [comment]
@kd-11 .I see .I will keep tracking on this issue when new NV driver came out.
