### ISSUE TITLE
nv3089::image_in is broken after "RSX refactoring"

### ISSUE THREAD

**Issue by Nekotekina** [RPCS3/rpcs3#1901]
It crashes in clip_image (BLES00971, BLJM60247, BLUS30701...)

**Comment by raven02** [comment]
The only changes i can see difference from before should be the following (but i feel it makes sense that also check the height and clip_y

```
 			bool need_clip =
 -				method_registers[NV3089_CLIP_SIZE] != method_registers[NV3089_IMAGE_IN_SIZE] ||
 -				method_registers[NV3089_CLIP_POINT] || convert_w != out_w || convert_h != out_h;
 +				method_registers.blit_engine_clip_width() != method_registers.blit_engine_input_width() ||
 +				method_registers.blit_engine_clip_height() != method_registers.blit_engine_input_height() ||
 +				method_registers.blit_engine_clip_x() > 0 ||
 +				method_registers.blit_engine_clip_y() > 0 ||
 +				convert_w != out_w || convert_h != out_h;
```

**Comment by Nekotekina** [comment]
Hey, it has changed almost every line there.

**Comment by raven02** [comment]
All the others line just refactor  but this one got removed without any substitution.

**Comment by vlj** [comment]
Does it throw an exception? Maybe there is a typo. 
Is it possible to have a stack trace with the values of the related width, height, x, y...  variables please?

**Comment by Nekotekina** [comment]
This is buffer overrun in temp1 variable (after line 544), I also fixed typo at line 364 but it didn't help.

Buffer size = 0x100 * 0x1400
clip_x, clip_y = 0, 0
clip_w, clip_h = 0x200, 0x200
bpp = 4
pitch = 0x1400 (both)

**Comment by vlj** [comment]
looking at the code it looks like temp1 is never created. Maybe need_clip and need_convert were both false before. 
The typo line 364 is likely to make  need_clip true but maybe there is another typo in the method_registers.* function, I'm looking at it.

**Comment by Nekotekina** [comment]
temp1 is reset in convert_scale_image but it's too small

**Comment by raven02** [comment]
line 368 typo as well

**Comment by raven02** [comment]
@Nekotekina , does it work okay now with typo fix ?

**Comment by raven02** [comment]
Just tested it and it looks okay .

**Comment by raven02** [comment]
@Nekotekina , does it work okay for you as well?

**Comment by Nekotekina** [comment]
Forgot to close!
