### ISSUE TITLE
Sengoku Basara 4 Sumeragi 

### ISSUE THREAD

**Issue by JCSkyCraft** [RPCS3/rpcs3#1904]
I Had Sengoku Basara 4 Sumeragi , 17GB+ w/ DLC Which is my problem , Its not working properly
or maybe RPCS3 is not support yet in few games , please help me to solve this problem 
Log:
LDR: Failed to inject code at address 0x1147a64
LDR: Failed to inject code at address 0x1147ad4
LDR: Unknown function '0x8C760B52' in 'sceNp' module (0x114812c)
LDR: Unknown function '0x1E0870D1' in 'sceNpTus' module (0x1149194)
{PPU Thread[0x1] (main_thread)[0x00a0a338]} sys_vm: sys_vm_memory_map(vsize=0x10000000, psize=0x6900000, cid=0xffffffff, flags=0x200, policy=0x1, addr=*0xd0015520)
{PPU Thread[0x1] (main_thread)[0x00a0a34c]} sys_vm TODO: sys_vm_touch(addr=0x60000000, size=0x6900000)
{PPU Thread[0x1] (main_thread)[0x00a0a35c]} sys_vm TODO: sys_vm_sync(addr=0x60000000, size=0x6900000)
{PPU Thread[0x1] (main_thread)[0x0114d36c]} Exception: LLE function not set: _cellFiberPpuInitialize (0x3833303855870804)
(in file Emu\SysCalls\Modules.cpp:139, in function execute_ppu_func_by_index)
Screenshot: 
![screenshot 87](https://cloud.githubusercontent.com/assets/20434448/16795504/4b893e4e-48e6-11e6-825c-0a1bd399ca51.png)

**Comment by SakataGintokiYT** [comment]
Try on latest emulator 0.0.1
https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.2847/artifacts

**Comment by JCSkyCraft** [comment]
Ok then

**Comment by JCSkyCraft** [comment]
LDR: Unknown function '0x9FB6228E' in module 'sysPrxForUser' (index 2972)
LDR: Unknown function '0x1E0870D1' in module 'sceNpTus' (index 2973)
LDR: Failed to inject code for function 'cellSslEnd' in module 'cellSsl' (0x1147a64)
LDR: Failed to inject code for function 'cellSslInit' in module 'cellSsl' (0x1147ad4)
LDR: Unknown function '0x8C760B52' in module 'sceNp' (index 2974)
{PPU[0x2] Thread (main_thread) [0x011471dc]} sysPrxForUser TODO: _sys_process_atexitspawn()
{PPU[0x2] Thread (main_thread) [0x01147364]} sysPrxForUser TODO: _sys_process_at_Exitspawn
{PPU[0x2] Thread (main_thread) [0x00a0a338]} sys_vm: sys_vm_memory_map(vsize=0x10000000, psize=0x6900000, cid=0xffffffff, flags=0x200, policy=0x1, addr=*0xd0015520)
{PPU[0x2] Thread (main_thread) [0x00a0a34c]} sys_vm TODO: sys_vm_touch(addr=0x60000000, size=0x6900000)
{PPU[0x2] Thread (main_thread) [0x00a0a35c]} sys_vm TODO: sys_vm_sync(addr=0x60000000, size=0x6900000)
{PPU[0x2] Thread (main_thread) [0x0114d36c]} cellFiber TODO: _cellFiberPpuInitialize
{PPU[0x2] Thread (main_thread) [0x01146e94]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU[0x2] Thread (main_thread) [0x01146e94]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU[0x2] Thread (main_thread) [0x01146e94]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU[0x2] Thread (main_thread) [0x01146e94]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU[0x2] Thread (main_thread) [0x01146e94]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU[0x2] Thread (main_thread) [0x01146e94]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU[0x2] Thread (main_thread) [0x01146e94]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU[0x2] Thread (main_thread) [0x01146e94]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU[0x2] Thread (main_thread) [0x01146e94]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU[0x2] Thread (main_thread) [0x01149664]} cellSpurs TODO: _cellSpursJobChainAttributeInitialize
{PPU[0x2] Thread (main_thread) [0x01149ac4]} cellSpurs TODO: cellSpursJobChainAttributeSetName
{PPU[0x2] Thread (main_thread) [0x0114962c]} cellSpurs TODO: cellSpursCreateJobChainWithAttribute
{PPU[0x2] Thread (main_thread) [0x01149974]} cellSpurs TODO: cellSpursGetJobChainId
{PPU[0x2] Thread (main_thread) [0x0114970c]} cellSpurs TODO: cellSpursJobChainGetSpursAddress
{PPU[0x2] Thread (main_thread) [0x01149664]} cellSpurs TODO: _cellSpursJobChainAttributeInitialize
{PPU[0x2] Thread (main_thread) [0x01149ac4]} cellSpurs TODO: cellSpursJobChainAttributeSetName
{PPU[0x2] Thread (main_thread) [0x0114962c]} cellSpurs TODO: cellSpursCreateJobChainWithAttribute
{PPU[0x2] Thread (main_thread) [0x01149974]} cellSpurs TODO: cellSpursGetJobChainId
{PPU[0x2] Thread (main_thread) [0x0114970c]} cellSpurs TODO: cellSpursJobChainGetSpursAddress
{PPU[0x2] Thread (main_thread) [0x01149664]} cellSpurs TODO: _cellSpursJobChainAttributeInitialize
{PPU[0x2] Thread (main_thread) [0x01149ac4]} cellSpurs TODO: cellSpursJobChainAttributeSetName
{PPU[0x2] Thread (main_thread) [0x0114962c]} cellSpurs TODO: cellSpursCreateJobChainWithAttribute
{PPU[0x2] Thread (main_thread) [0x01149974]} cellSpurs TODO: cellSpursGetJobChainId
{PPU[0x2] Thread (main_thread) [0x0114970c]} cellSpurs TODO: cellSpursJobChainGetSpursAddress
{PPU[0x2] Thread (main_thread) [0x01149664]} cellSpurs TODO: _cellSpursJobChainAttributeInitialize
{PPU[0x2] Thread (main_thread) [0x01149ac4]} cellSpurs TODO: cellSpursJobChainAttributeSetName
{PPU[0x2] Thread (main_thread) [0x0114962c]} cellSpurs TODO: cellSpursCreateJobChainWithAttribute
{PPU[0x2] Thread (main_thread) [0x01149974]} cellSpurs TODO: cellSpursGetJobChainId
{PPU[0x2] Thread (main_thread) [0x0114970c]} cellSpurs TODO: cellSpursJobChainGetSpursAddress
{PPU[0x2] Thread (main_thread) [0x01149664]} cellSpurs TODO: _cellSpursJobChainAttributeInitialize
{PPU[0x2] Thread (main_thread) [0x01149ac4]} cellSpurs TODO: cellSpursJobChainAttributeSetName
{PPU[0x2] Thread (main_thread) [0x0114962c]} cellSpurs TODO: cellSpursCreateJobChainWithAttribute
{PPU[0x2] Thread (main_thread) [0x01149974]} cellSpurs TODO: cellSpursGetJobChainId
{PPU[0x2] Thread (main_thread) [0x0114970c]} cellSpurs TODO: cellSpursJobChainGetSpursAddress
{PPU[0x2] Thread (main_thread) [0x01149664]} cellSpurs TODO: _cellSpursJobChainAttributeInitialize
{PPU[0x2] Thread (main_thread) [0x01149ac4]} cellSpurs TODO: cellSpursJobChainAttributeSetName
{PPU[0x2] Thread (main_thread) [0x0114962c]} cellSpurs TODO: cellSpursCreateJobChainWithAttribute
{PPU[0x2] Thread (main_thread) [0x01149974]} cellSpurs TODO: cellSpursGetJobChainId
{PPU[0x2] Thread (main_thread) [0x0114970c]} cellSpurs TODO: cellSpursJobChainGetSpursAddress
{PPU[0x2] Thread (main_thread) [0x01149664]} cellSpurs TODO: _cellSpursJobChainAttributeInitialize
{PPU[0x2] Thread (main_thread) [0x01149ac4]} cellSpurs TODO: cellSpursJobChainAttributeSetName
{PPU[0x2] Thread (main_thread) [0x0114962c]} cellSpurs TODO: cellSpursCreateJobChainWithAttribute
{PPU[0x2] Thread (main_thread) [0x01149974]} cellSpurs TODO: cellSpursGetJobChainId
{PPU[0x2] Thread (main_thread) [0x0114970c]} cellSpurs TODO: cellSpursJobChainGetSpursAddress
{PPU[0x2] Thread (main_thread) [0x0114cd14]} PPU: 'cellGameBootCheck' aborted
{PPU[0x2] Thread (main_thread) [0x0114cd14]} class fmt::exception thrown: cellGameBootCheck(): Unknown CATEGORY: 




:/

**Comment by Nezarn** [comment]
post your rpcs3.log to pastebin, also from this log snippet, you should try load spurs_jq, sre, and fiber LLE modules.

**Comment by JCSkyCraft** [comment]
I cant post it in pastebin because its lagging
Here's the link
https://mega.nz/#fm/J4F2RRTD

**Comment by Nezarn** [comment]
@JCSkyCraft  that mega link doesn't work.

**Comment by AniLeo** [comment]
You should post this kind of stuff in the forums, Github Issues are for reporting bugs in the emu.
See: http://www.emunewz.net/forum/showthread.php?tid=174352

**Comment by JCSkyCraft** [comment]
Ok <3

**Comment by raven02** [comment]
@JCSkyCraft . Having the mega link with log attached , I removed the long log paste above .
