### ISSUE TITLE
DX12 : re-accesses the same texture address with different dimensions.

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1912]
When testing one of the game below , same scene and same PPU/SPU settings .  It yields a very big difference in performance .This scene in DX12 ever received the "Working buffer not enough" by this change that adjust the buffer size based on VRAM where my GT650 only has 512M VRAM ( https://github.com/RPCS3/rpcs3/pull/1786) then i need to set back to 896M for this scene to work in DX12 however it slow to hell (but conversely GL runs well with high FPS)

@vlj / @kd-11 , any insight or improvement we can make ?

DX12 (1-2 FPS)
![dx12](https://cloud.githubusercontent.com/assets/3000282/16848536/d1d9ad56-4a28-11e6-92bf-e14219543813.jpg)

GL(15-16FPS)

![gl](https://cloud.githubusercontent.com/assets/3000282/16848541/d5479aca-4a28-11e6-8f9e-a96688a1b6bf.jpg)

**Comment by kd-11** [comment]
Test vulkan as well to eliminate other factors. GL is using a different shader backend now which generates more effecient shaders.

**Comment by raven02** [comment]
Unfortunately Vulkan is keep crashing for me on my NV system that i am even able to get to main menu :(

**Comment by kd-11** [comment]
Will test on AMD and update soon as I finish rewriting https://github.com/RPCS3/rpcs3/pull/1907

**Comment by raven02** [comment]
Got one chance to reach this scene using savedata then crash.....

![vulkan](https://cloud.githubusercontent.com/assets/3000282/16849044/3695d5ba-4a2b-11e6-8fc9-0143a1be5068.jpg)

**Comment by kd-11** [comment]
Well, looking at the framerate, I'd say only DX12 is affected then. I'll run on my 2G AMD card and see what happens

**Comment by raven02** [comment]
This is the savedata - 
[savedata.zip](https://github.com/RPCS3/rpcs3/files/364465/savedata.zip)

**Comment by kd-11** [comment]
Is this ingame or the intro?

**Comment by raven02** [comment]
It is in-game . Title menu select "Continue"

**Comment by kd-11** [comment]
ok. i'll need to decrypt some sdats I assume. Will update soon.

**Comment by raven02** [comment]
Try this STAGE.7z - https://drive.google.com/file/d/0BwWxlmOqZ56kM2tsN0MyRkt5RlE/view?usp=sharing

**Comment by kd-11** [comment]
Thanks. I'd already decrypted the stage folder. DX12 with 2G AMD card is still very slow at ~9fps while vk and ogl are in the 28fps range. Doesn't seem to be VRAM related as far as I can tell.

**Comment by kd-11** [comment]
Seems related to texture upload. I'm seeing upto 60ms spikes in texture upload functions from the debug overlay. It is probably referring to the same texture using different dimensions. Gl and VK use a std::vector to parse the cache and an address key can have multiple textures of different sizes stored. DX12 will re-upload if the size does not match. This is the only reason I can think of off the top of my head anyway. I'll confirm this behaviour (It used to spam ogl and vulkan logs with a cache error of different sizes, but I removed it at some point)

**Comment by raven02** [comment]
Looking forward to your fix

**Comment by kd-11** [comment]
I'll leave this one to @vlj for now. It requires reworking the DX12 textures cache, probably by adding a hasher to the unordered map that considers dimensions as well.

**Comment by raven02** [comment]
Alright .Thanks @kd-11

**Comment by raven02** [comment]
Bit sidetrack , the text colour is green for both DX12 and Vulkan , sort of alpha testing issue?

**Comment by kd-11** [comment]
It's not alpa testing (vulkan and ogl shared the same shaders before). Probably texture formats and channel swizzles, but i'd have to confirm it. By the way, you should update the title

**Comment by raven02** [comment]
i captured the frame . Check out this section right?

Texture 0: Offset @0x01df9100
Texture 0: location = 0x00000000 border type = 1 dimension = 2 format = CELL_GCM_TEXTURE_A8R8G8B8 swizzled mipmap levels = 1
Texture 0: width = 256 height = 512
Texture 0 depth = 1 pitch = 0
Texture 0 Component 0 = A Component 1 = R Component 2 = G Component 3 = B
Texture 0: Offset @0x01df9100
Texture 0: location = 0x00000000 border type = 1 dimension = 2 format = CELL_GCM_TEXTURE_A8R8G8B8 swizzled mipmap levels = 1
Texture 0: wrap_s = CLAMP_TO_EDGE wrap_t = CLAMP_TO_EDGE wrap_r = WRAP unsigned remap = 0 zfunc = GreaterOrEqual gamma = 0 aniso bias = 0 signed remap = 0
Texture 0 min lod = 0 max lod = 0 max aniso = 4 alpha kill = false
Texture 0 Component 0 = A Component 1 = R Component 2 = G Component 3 = B
Texture 0 bias = 8126 min_filter = 2 mag_filter = 2 convolution_filter = 1 a_signed = 0 r_signed = 0 g_signed = 0 b_signed = 0
Texture 0: width = 256 height = 512
Texture 0 border color = 0
Texture 0 depth = 1 pitch = 0

**Comment by raven02** [comment]
I remember once upon a time , the text color is

1. GL (white)
2. DX12 (Red)
3. Vulkan (Green)


I'll debug it to see which commit make the DX12 color change from previous red to green now.

**Comment by raven02** [comment]
With some debug , the text color is from CELL_GCM_TEXTURE_G8B8

**Comment by raven02** [comment]
However , this breaks other games .(Probably the swizzle depends on input byte format and sample format  as mentioned by @kd-11

**Comment by raven02** [comment]
@kd-11 , is it somehow related to the  upload_texture_subresource() in textureUtils?

**Comment by kd-11** [comment]
No. Its the Dx12 texture cache that's too eager to purge cached textures that dont match requested parameters causing heavy cache misses. I can rewrite the cache objects themselves to hold several slices of the same texture, but I don't know if I'll be able to find time for that. My list of todos for rpcs3 is rather long at the moment.

**Comment by raven02** [comment]
Sorry to make you confused. I mean the texture format CELL_GCM_TEXTURE_G8B8  that i found that trigger the wrong  text color in Dai-3-Ji Super Robot Taisen Z Jigoku-hen  (DX12 and Vulkan is green)

if i change the shader components from 1 2 1 2  to 2 1 2 1 , color fixed but breaks other game

**Comment by kd-11** [comment]
ahh. ok. in that case the swizzle components are the problem, not the upload function since that just copies data to ram. I had noticed other cases where G8B8 was misbehaving on vulkan e.g limbo loading screen.

**Comment by raven02** [comment]
Yes Limbo and also BIT Runner 2 and Marvel VS Capcom 2 , they all use this G8B8

**Comment by kd-11** [comment]
@raven02 Maybe the G8B8 swizzle respects the texture swizzle register. Check other formats e.g A4R4G4B4 where you have to remap the components.

**Comment by raven02** [comment]
Alright let me check it out

**Comment by raven02** [comment]
Just checked out with this but looks like it didn't help.

	case CELL_GCM_TEXTURE_G8B8:
	{
		VkComponentSwizzle map_table[] = { VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G };
		return{ map_table[remap_r], map_table[remap_g], map_table[remap_r], map_table[remap_g] };
	}

**Comment by raven02** [comment]
GL handle G8B8 all correct in all tested games , not too sure if it is the use of new shader compiler.

**Comment by raven02** [comment]
For D3D12 , swizzle based on render target then all games tested good with G8B8

**Comment by raven02** [comment]
For Vulkan ,it will be fixed in https://github.com/RPCS3/rpcs3/pull/1931 as well

**Comment by raven02** [comment]
@vlj, i will leave out swizzle issue discussion over here since it is fixed now and please check out the upload texture cache issue when you have time .

**Comment by vlj** [comment]
ok

**Comment by raven02** [comment]
The DX12
