### ISSUE TITLE
rsx_decompiler: G-Force (and other games) animation regression (T-Pose character models/Broken skeletal animation)

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#1913]
With the new shader decompiler, G-Force on OpenGL has regressed. Characters are stuck in T-pose with only the vertex deformation animation bits moving. Might be a vertex weight attribute or vertex shader constants issue since it seems skeletal animation is done on the gpu, though I might be wrong.

**Comment by kd-11** [comment]
Finally found it. In a vertex shader, the line ```a0 = ivec4(r0)``` is replaced with ```a0.x =int(r0.x)```. This is an issue with the rsx decompiler.

**Comment by kd-11** [comment]
Confirmed as incorrect handling of ARL opcode with new decompiler. Should affect any games using address registers for transform constant offsets (e. silent hills 3, g-force)

Proof using a patched version of rsx_decompiler:
![g-force](https://cloud.githubusercontent.com/assets/15904127/16896809/26493120-4ba7-11e6-8086-7300270f6bf3.png)

**Comment by SakataGintokiYT** [comment]
ooo Nice :P

**Comment by kd-11** [comment]
Submitted a pull request to decompiler subproject here: https://github.com/RPCS3/rsx_program_decompiler/pull/4

**Comment by kd-11** [comment]
Also affects ice age 3, etc.

**Comment by raven02** [comment]
@Nekotekina may require  rsx_program_decompiler submodule update  .

**Comment by raven02** [comment]
@danilaml , could you help to update the rsx_program_decompiler submodule ?

**Comment by danilaml** [comment]
@raven02 What are you asking me exactly?

**Comment by kd-11** [comment]
The ref to the rsx_decompiler submodule should be updated to current head.

**Comment by raven02** [comment]
@danilaml i seen you help out update the rsx_program_recompiler last time so would like to see if you can help as we have updated that  submodule with ARL opcode fix

BTW , what is the correct way to update this sub module as i always in vain

**Comment by danilaml** [comment]
@raven02 it shoudl be easy (assuming that new commits to the submodule doesn't introduce conflicts to the project) - you just cd into submodule dir, and update it like you would any other repo.

**Comment by raven02** [comment]
i see . I will try again next time thanks
