### ISSUE TITLE
Project Diva F error couldn't solve

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1919]
![image](https://cloud.githubusercontent.com/assets/11285640/16871843/5a65e704-4ab3-11e6-904d-7b3a7231ad8c.png)
PPU Interpreter 2 and Recompiler , SPU Recompiler
DirectX 12
My Spec
Intel Core 2 Quad Q6600 , NVIDIA Geforce GT 730 GDDR5
when i'm play 2 songs in game or back to main menu , it's have an error and drop FPS

**Comment by zminhquanz** [comment]
Switch to OpenGL , there is no error dialog below , but lower framerate

**Comment by raven02** [comment]
What NV driver you are using ? try to use 368.81 as i found previous version like .69 .39 or .22 will trigger the fatal error .

**Comment by zminhquanz** [comment]
@raven02  I used driver 368.69

**Comment by raven02** [comment]
Try to upgrade to 368.81 to see if the problem presists

**Comment by zminhquanz** [comment]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0x80000003.
Exception address: 00007FFFB7B2B72C.
ExceptionInformation[0x0]: 0000000000000000.
Instruction address: 00007FFFB7B2B72C.
Image base: 0000000000010000.

HOW TO REPORT ERRORS:
1) Check the FAQ, readme, other sources. Please ensure that your hardware and software configuration is compliant.
2) You must provide FULL information: how to reproduce the error (your actions), RPCS3.log file, other *.log files whenever requested.
3) Please ensure that your software (game) is 'Playable' or close. Please note that 'Non-playable' games will be ignored.
4) If the software (game) is not 'Playable', please ensure that this error is unexpected, i.e. it didn't happen before or similar.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------
![image](https://cloud.githubusercontent.com/assets/11285640/16907885/6e481324-4cf1-11e6-8211-287bb895ed17.png)
The error is still there , i was updated the latest driver 368.81

**Comment by raven02** [comment]
I suppose you are using PPU interpreter (fast) + SPU interprerter (fast) , right?

**Comment by raven02** [comment]
Alright i just tried out to play a song and back to menu again , it looks okay and no hang up .

This is my setting

PPU interperter (fast)
SPU ASMJIT
DX12 1280x720
XAudio2

sre+spurqs+resc+rtc+l10n

**Comment by Nezarn** [comment]
@raven02 for me it never crashed like that. (also resc+rtc is enough for LLE), the only issue with the game is that it has some kinda memory leak in DX12, if you play for a while it will start stuttering and the sound will get muted.

**Comment by zminhquanz** [comment]
@Nezarn like for me , play for a while it's dropping FPS and stuttering the sound and appear this error above

**Comment by raven02** [comment]
If it is memory leak FPS that leads to FPS dropping is known and also mentioned in another issue already. i closing thi
