### ISSUE TITLE
Vulkan: Nvidia specific crash @368.69

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1922]
It simply crash at bootup for every titles .Having bisected , and found regression at https://github.com/RPCS3/rpcs3/pull/1800

@kd-11 Looks like that pull works okay on AMD but not on NV system.

**Comment by raven02** [comment]
@SakataGintokiYT , is this build Vulkan work for you?

https://ci.appveyor.com/api/buildjobs/uc4rxauj3xquomc7/artifacts/rpcs3-ReleaseLLVM-1e627104.zip

**Comment by SakataGintokiYT** [comment]
@raven02  
Yes it works for me :P

**Comment by kd-11** [comment]
@raven02 Unless nvidia vram configuration has changed, that pr would have been crashing nvidia for quite some time now. Is this the case?

**Comment by raven02** [comment]
yes @kd-11

**Comment by kd-11** [comment]
When I initially created that pull request, it was tested on nvidia and there was no bootup crash. When did the bootup crash actually start to happen? You confirmed no crash in the original PR for that changeset https://github.com/RPCS3/rpcs3/pull/1788

**Comment by raven02** [comment]
Probably i upgraded the Nvidia driver.

**Comment by kd-11** [comment]
In case the vram config has been changed on nvidia, I'll need to get more info about the heap layout. I'll create a debugging branch to dump heap tables to log so we can see what happens then. What is the crash message? Or is it a windows app crash?

**Comment by raven02** [comment]
It is a windows app crash 
![untitled](https://cloud.githubusercontent.com/assets/3000282/16893831/7d318c20-4b76-11e6-9eed-6ee5cf7ae155.jpg)

**Comment by kd-11** [comment]
Ok. Could be an issue with NV driver then. Anyway, i'll notify you when the debugging patch is ready.

**Comment by raven02** [comment]
Thanks . @kd-11

**Comment by raven02** [comment]
It crashes at this part

			if (is_device_local)
			{
				if (device_local_vram_size < heap.size)
				{
					result.device_local = i;
					device_local_vram_size = heap.size;
				}
			}

**Comment by kd-11** [comment]
That makes it even more likely that the nv driver is misbehaving. probably has a heap entry that is out of bounds.

**Comment by raven02** [comment]
I see. 2nd type of crash mentioned above can be alwasy reproduce from 1942 Joint Strike as it always crash when see the first graphic

**Comment by kd-11** [comment]
Well, the driver really shouldn't crash to desktop, i'd have expected a failure returning an error code instead. Anyway, try this build and post the log https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.206. You dont have to even run the game, just double click and it should dump to log.

**Comment by raven02** [comment]
Done . here is the log

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/367363/RPCS3.zip)

**Comment by kd-11** [comment]
Well, it clearly did not crash in that section since it reaches the end of the block. The algorithm has done its part already and the crash did not happen. To really find the location of the crash, you need to compile VKGSRender with disabled code optimization and attach the debugger. The crash is probably happening elsewhere and the debugger is confused by the optimized code.

**Comment by raven02** [comment]
The debug build attached is indeed crashed once i run Arkedo 01

**Comment by kd-11** [comment]
is there anything in the log about that?

**Comment by kd-11** [comment]
There's only 2 heaps on NV, there's no way the selection code is faulty (there aren't any options to mess up since its either heap 0 or 1).

**Comment by raven02** [comment]
i run it in VS2015 debugger and breaks out at

		CHECK_RESULT(m_swap_chain->queuePresentKHR(m_swap_chain->get_present_queue(), &present));

**Comment by kd-11** [comment]
And if you revert https://github.com/RPCS3/rpcs3/pull/1800 it works? Not just running the build at that point, i mean using a git revert to undo that single commit while keeping all the other code.

If so, modify the code in the memory types code to just return a result with device_local index 7 and host_visible index 9 and see if it works.

**Comment by raven02** [comment]
Yes , i revert only that commit using the latest build code from master.

**Comment by kd-11** [comment]
What are the results of the old algorithm? I'm guessing 8 and 10?

**Comment by raven02** [comment]
It didn't work

Modify code as

		result.device_local = 7;
		result.host_visible_coherent = 10;
		return result;

**Comment by raven02** [comment]
If i set it to 8 and 10 , it works.

**Comment by kd-11** [comment]
There is no difference between types 7 and 8. They refer to the same heap. This implies a bug in the driver.

**Comment by raven02** [comment]
Yes , i think so .How we can workaround it at this moment?

**Comment by kd-11** [comment]
A workaround is easy, but we first need to confirm the issue to report to nv. If this is the recent doom driver you are using they may have tried to add hacks in there. I'll upload a sample that you can run to confirm the issue (based off of the lunarg cube demo). Also, first make sure you are running the latest nv driver before we go off making accusations. They update beta drivers often.

**Comment by raven02** [comment]
Sure .

**Comment by kd-11** [comment]
Can you confirm the attached cube demo works without crashing?
[cube.zip](https://github.com/RPCS3/rpcs3/files/367398/cube.zip)

**Comment by raven02** [comment]
I run it .Pop up a while then close itself.

**Comment by kd-11** [comment]
sorry. bad packaging. let me resend the correct zip.

**Comment by kd-11** [comment]
[cube.zip](https://github.com/RPCS3/rpcs3/files/367400/cube.zip)
Proper executable and required files (shaders + texture). I've modified it to use the same memory mechanism we use.

**Comment by kd-11** [comment]
overwrite the previous exe

**Comment by raven02** [comment]
It crashed.

**Comment by kd-11** [comment]
Good. That is a clear and reproducible example. That driver is broken. I'm going to open a ticket on nv forums. For now, I'd suggest downgrading your driver to the last working version since this is a rather serious bug. It seems the memory type list is bogus since it fails to run a vulkan demo from lunarg when using staging textures. Adding a fix for this will be really messy and is unnecessary. We should not work around someone else's broken code. If I may ask, what driver version are you running? I'll need it for the report.

**Comment by raven02** [comment]
i see. It is their latest driver 368.81

**Comment by kd-11** [comment]
So the one before that works, right? 368.69 I think.

**Comment by raven02** [comment]
Probably older .I have to check it out .

**Comment by kd-11** [comment]
Graphics card model?

**Comment by raven02** [comment]
GT 650M (iMac)

**Comment by kd-11** [comment]
Any other models affected? Pascal or maxwell? A 900 series perhaps?
CC @SakataGintokiYT

**Comment by raven02** [comment]
OK. Here is the list

368.22 OK
368.39 OK
368.69 crash
368.81 crash

**Comment by vlj** [comment]
Memory type is changing with driver revision.
For instance on 368.81.0.0 : http://vulkan.gpuinfo.org/displayreport.php?id=547#memory
and 	368.22.0.0: on http://vulkan.gpuinfo.org/displayreport.php?id=430#memory

One has to parse memory type and flag to assign device local and main memory index type.

**Comment by kd-11** [comment]
@vlj Its a problem with the parsed memory types. The test case I'm using is not hardcoded otherwise it wouldnt work on amd which has only like 3 memory types. To see this error, get the lunarg cube sample and force the texture function to use a staging texture with the current driver. It will attempt to get a device local heap (which it does successfully as index 7 in the case presented here) and quickly crash.

**Comment by raven02** [comment]
Fall back to older version like 368.39 , Vulkan backend works again however seems to be more likely to crash in-game. Probably something fixed from 368.39 to 368.81

**Comment by kd-11** [comment]
Can anyone else confirm that https://github.com/RPCS3/rpcs3/files/367400/cube.zip crashes on nvidia?

**Comment by raven02** [comment]
@kd-11 , i'll test it it out shortly

**Comment by raven02** [comment]
it crashed on my 368.81 GT650M

**Comment by kd-11** [comment]
Well, we know the 650M has a problem. Anyone on maxwell? On devtalk I was informed that it would work on maxwell and I need to confirm.

**Comment by Blaypeg** [comment]
Crashed for me too.

GTX 750 v368.39

**Comment by kd-11** [comment]
750 (non-ti) and 650M are both kepler. Need someone on different GPU arch. NV issue report is here: https://devtalk.nvidia.com/default/topic/950850/vulkan/memory-type-index-selection-table-is-broken/

**Comment by AniLeo** [comment]
I have a 960M, just a second, I'll test

**Comment by AniLeo** [comment]
@kd-11 cube.exe stopped working. 960M with VulkanRT 1.0.11.1 and 368.69

**Comment by kd-11** [comment]
By the way, here's the source for the test http://pastebin.com/p17rLYKt. I just added a `if (0 && ...` to keep linear upload from working. @AniLeo Does it ever work on the 960m, maybe on an older driver? Coz I just checked again by downloading the zip and AMD is ok

**Comment by AniLeo** [comment]
@kd-11 It works on my 280X with VulkanRT 1.0.17.0.
It doesn't work on 960M with 368.22 and VulkanRT 1.0.11.0 (I can't update the latter).

**Comment by kd-11** [comment]
Apparently, that cube sample has a bug caught by the updated validation layers. I'll update validation layers and try to catch an error. If that fails, I'll have to write a test case that passes validation layers and fails on nv or something.

**Comment by kd-11** [comment]
I am unable to use vulkan validation layers since the vulkan submodules were updated. Can anyone else reproduce? Its making debugging rather difficult.

**Comment by SakataGintokiYT** [comment]
@raven02  Dolphin Vulkan backend works good on Nvidia GPU and not crash 
https://github.com/dolphin-emu/dolphin/pull/3935

**Comment by raven02** [comment]
@kd-11 , let me know if i can help on something here. (like reproduce something else?)

**Comment by kd-11** [comment]
@raven02 Can you get debug output to work? If so, you should run vulkan with it enabled. As I mentioned earlier, it broke since the vulkan submodules update by neko. I dont know if it gets compiled correctly

**Comment by raven02** [comment]
I think you mean the Graphic backend -> debug output , right? If yes , i can try to run it with Vulkan  and this option enabled.

**Comment by raven02** [comment]
Here your are - [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/380192/RPCS3.zip)

Hightlight before crash

```
·E {rsx::thread} RSX: ERROR: [MT] Code 14 : vkBindImageMemory(): MemoryRequirements->memoryTypeBits (0x102) for this object type are not compatible with the memory type (0x7) of this memory object 0x9c.
·E {rsx::thread} RSX: ERROR: [IMAGE] Code 16 : vkCmdClearColorImage called with image created without VK_IMAGE_USAGE_TRANSFER_DST_BIT.
·E {rsx::thread} RSX: ERROR: [MT] Code 14 : vkBindImageMemory(): MemoryRequirements->memoryTypeBits (0x100) for this object type are not compatible with the memory type (0x7) of this memory object 0x9e.
·E {rsx::thread} RSX: ERROR: [IMAGE] Code 16 : vkCmdClearColorImage called with image created without VK_IMAGE_USAGE_TRANSFER_DST_BIT.
·E {rsx::thread} RSX: ERROR: [MT] Code 14 : vkBindImageMemory(): MemoryRequirements->memoryTypeBits (0x102) for this object type are not compatible with the memory type (0x7) of this memory object 0xa4.
·E {rsx::thread} RSX: ERROR: [IMAGE] Code 16 : vkCmdClearColorImage called with image created without VK_IMAGE_USAGE_TRANSFER_DST_BIT.
·E {rsx::thread} RSX: ERROR: [DS] Code 50 : DS 0xa2 encountered the following validation error at draw time: Descriptor in binding #7 at global descriptor index 4 is being used in draw but has not been updated
```

**Comment by kd-11** [comment]
@raven02 Thanks!
The error is here:
```
·E {rsx::thread} RSX: ERROR: [MT] Code 14 : vkBindImageMemory(): MemoryRequirements->memoryTypeBits (0x102) for this object type are not compatible with the memory type (0x7) of this memory object 0x9c.
```

How did you get validation working? Does it just work for you? Beacause for me it crashes with newer builds. Maybe I need to upgrade vulkan runtime or something, although I thought we compiled statically

**Comment by raven02** [comment]
i'm using latest build and it just work for me

**Comment by kd-11** [comment]
@raven02 What does the log look like if you set the type to 8 instead of the default 7? Because from vulkan sdk type bits 0x102 is impossible. Maybe its just an issue with the image creation

**Comment by kd-11** [comment]
Well, try this build as soon as it is done building: https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.226/

**Comment by kd-11** [comment]
Ok. Upgrading my sdk fixed the validation. The spec has surely undergone some revisions. We have a large number of API violations now. Will update when I have them sorted out.

**Comment by raven02** [comment]
Cool . I will test out the build when back homeboy

**Comment by raven02** [comment]
This is the log when type is 8 instead of 7 . There is no memory type 0x102 error and run the cube.ppu.elf successfully

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/380306/RPCS3.zip)

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/1981

**Comment by raven02** [comment]
Issue resolved .Closed
