### ISSUE TITLE
Input: Date A Live: Rine Utopia Keyboard and Xinput not working

### ISSUE THREAD

**Issue by lightfirst** [RPCS3/rpcs3#1923]
Testing Date A Live: Rine Utopia [BLJM61048]
After decrypt 4 sdat file and rename Movie folder and using opengl render (d3d12 blackscreen)
I finally make this game running. Unfortunately no matter how I push Keyboard or PAD, noting happend.
totally ignore controler Input
![BLJM61048](https://cloud.githubusercontent.com/assets/4612168/16895447/ff2a665c-4ba8-11e6-8ea5-0500b02e0cc0.png)

**Comment by lightfirst** [comment]
[log.zip](https://github.com/RPCS3/rpcs3/files/367336/log.zip)

**Comment by raven02** [comment]
Same as Bomber man Ultra that input is not working when reach the following scene

![untitled](https://cloud.githubusercontent.com/assets/3000282/16901532/4b1a5a74-4c79-11e6-92fe-5c3753214152.jpg)

**Comment by Nezarn** [comment]
@raven02 i just tested bomberman ultra, works fine here. (same titleid as what you have)

**Comment by raven02** [comment]
@Nezarn yep , i can scroll up and down but somehow circle/cross etc not working .

**Comment by Nezarn** [comment]
@raven02 download this savegame and it will work https://www.dropbox.com/s/lvrz4v1ionaieic/NPEB00076-BMANULTRA-AUTO-%20EU.rar?dl=0

**Comment by raven02** [comment]
Thanks @Nezarn .Will try this out . However , it is interesting that a savegame can get pass it.

**Comment by lightfirst** [comment]
Well, I try using savedata to make Date A Live: Rine Utopia input working, not successful.

**Comment by raven02** [comment]
For bomberman , it is becasue cellSaveDataUserAutoLoad aborted and failed to create 4 files under NPEB00076-BMANULTRA-AUTO- thus the game stuck at title menu.

E {PPU[0x7000000e] Thread (ReadProfileSettings) [0x00162960]} cellSaveData: cellSaveDataUserAutoLoad(version=0, userId=0, dirName=“NPEB00076-BMANULTRA-AUTO-”, errDialog=0, setBuf=*0xd007bd90, funcStat=*0x1b2180, funcFile=*0x1b21a0, container=0xffffffff, userdata=*0x0)
E {PPU[0x7000000e] Thread (ReadProfileSettings) [0x00162960]} PPU: 'cellSaveDataUserAutoLoad' aborted
F {PPU[0x7000000e] Thread (ReadProfileSettings) [0x00162960]} class std::logic_error thrown: fs::file is null

**Comment by lightfirst** [comment]
@raven02 maby Date A Live also has SaveData problem, I get a Normal dialog “systemdata not found” when systemdata exist.  On the contrary, an Error dialog "Loading systemdata, Do not turn off the host power or quit the game " show when system data not exist.

**Comment by raven02** [comment]
I'm closing it .The input is working now in latest build .

**Comment by Zangetsu38** [comment]
@raven02 reopen, Date a live and other several game have allays this issue

**Comment by Zangetsu38** [comment]
Log indicate 
>U {PPU[0x1000000] Thread (main_thread) [0x0062f1c4]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK

Control engine is a rapport with Input ?

**Comment by georgemoralis** [comment]
my latest pull request fixed bomberman issue. Can you test the other games relative to this issue as well?

**Comment by Zangetsu38** [comment]
no, don't fix this problem for this game :/

**Comment by B1ackDaemon** [comment]
One more game with controls issue
http://www.emunewz.net/forum/showthread.php?tid=177495

**Comment by B1ackDaemon** [comment]
White Album also stuck on "Press Start" screen
http://www.emunewz.net/forum/showthread.php?tid=177244&pid=241957#pid241957

**Comment by Terrails** [comment]
@lightfirst did you manage to fix it? I'm having the same problem with the game... Keyboard is on input and I just can't do anything, I'm just stuck in the main menu.

**Comment by Zangetsu38** [comment]
now fixed

**Comment by AniLeo** [comment]
Will close after #2720 is merged

**Comment by darkredflame** [comment]
Figured I should chime in and say that #2720 fixed the issue with analog sticks not being detected in Tony Hawk Project 8 [BLUS30011]. Movement still feels off such as having to press up on the analog stick multiple times for the skater to start moving, but I'm going to chalk that up to low FPS for now.
