### ISSUE TITLE
PPU: struct vm::access_violation thrown: Access violation reading

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1926]
@Nekotekina 
.
##### Dragon Ball Z: Ultimate Tenkaichi

`{PPU[0x7] Thread (main_thread) [0x005fc818]} struct vm::access_violation thrown: Access violation reading address 0x377`
Log : https://gist.github.com/SakataGintokiYT/5d42c30612813af5335e838f706a32f7

---
##### Dragon Ball Z Budokai HD Collection

```
{PPU[0x7] Thread (main_thread) [0x000cd880]} PPU: 'sys_spu_thread_group_start' aborted
{PPU[0x7] Thread (main_thread) [0x000cd880]} struct vm::access_violation thrown: Access violation reading address 0x0
```

Log : https://gist.github.com/SakataGintokiYT/ea5fd6c509165548371348fd9db2b454

---
##### Dragon Ball: Raging Blast 2

`{PPU[0x7] Thread (main_thread) [0x00543d80]} struct vm::access_violation thrown: Access violation reading address 0x4c5`
Log : https://gist.github.com/SakataGintokiYT/68e2f16d065280487d1bc26737090e01

---
##### 魁!!男塾 ～日本よ、これが男である！～ [BLJS10254]

`{PPU[0x7] Thread (main_thread) [0x000a65c8]} struct vm::access_violation thrown: Access violation reading address 0x68`
Log : https://gist.github.com/SakataGintokiYT/b8ae23b8c28ee12adf5d6d9ec3b1566d

---
##### One Piece: Unlimited World Red

```
{PPU[0xa] Thread (main_thread) [0x001b65b8]} sys_vm: sys_vm_memory_map(vsize=0x8000000, psize=0x7600000, cid=0xffffffff, flags=0x200, policy=0x1, addr=*0x96ea04)
{PPU[0xa] Thread (main_thread) [0x001b65e8]} PPU: 'sys_memory_allocate' failed with 0x80010002 : CELL_EINVAL
{PPU[0xa] Thread (main_thread) [0x006faa54]} struct vm::access_violation thrown: Access violation reading address 0xc
```

Log : https://gist.github.com/SakataGintokiYT/9d8b44a5a36e2d73e306457ea02cc13e

**Comment by zminhquanz** [comment]
Project Diva F sometimes get this error , when using PPU Recompiler

**Comment by SakataGintokiYT** [comment]
ggg

**Comment by MarioSonic2987** [comment]
Tested in https://github.com/RPCS3/rpcs3/commit/74fec275c71eaa4118bdca3eee3068c31f99c8be
- Saints Row 2 [NPEB-00637]
```
{PPU[0x2] Thread (main_thread) [0x00011680]} struct vm::access_violation thrown: Access violation reading address 0xa

```

**Comment by zminhquanz** [comment]
![image](https://cloud.githubusercontent.com/assets/11285640/17508621/0acca00c-5e40-11e6-895e-0dcc03855554.png)
Problem can't solve in the latest build , PPU LLVM Recompiler is having issue , but PPU Interpreter 2 is normally , no issue

**Comment by raven02** [comment]
@zminhquanz . i moved your issue to "PPU: LLVM recompiler issue"

**Comment by raven02** [comment]
Gran turismo 6

F {PPU[0x80000000] Thread (main_thread) [0x00a4fe38]} struct vm::access_violation thrown: Access violation writing address 0x6ffd0000

**Comment by Nezarn** [comment]
Atelier Rorona The Alchemist of Arland

With libsail LLE:
> F {PPU[0x8000003b] Thread (_libsail-control) [0x39800000]} struct vm::access_violation thrown: Access violation reading address 0x39800000

Without:
> F {PPU[0x80000000] Thread (main_thread) [0x009e77f0]} struct vm::access_violation thrown: Access violation writing address 0x7c4e0033

**Comment by MarioSonic2987** [comment]
The Simpsons Game Demo [NPEB-90029]

```
{PPU[0x80000000] Thread (main_thread) [0x00486710]} struct vm::access_violation thrown: Access violation writing address 0xcfffe540
```

**Comment by Nezarn** [comment]
Journey
> F {PPU[0x80000000] Thread (main_thread) [0x001cd408]} struct vm::access_violation thrown: Access violation reading address 0x7c0802bb

**Comment by MarioSonic2987** [comment]
Ratchet & Clank 3 [NPEA-00387]
```
{PPU[0x80000000] Thread (main_thread) [0x00aee0c8]} struct vm::access_violation thrown: Access violation writing address 0x15c3c60
```

**Comment by kd-11** [comment]
Demon's souls seems to dereference a nullptr. Maybe the preceding sys_memory error is related?
```
E {PPU[0x70000005] Thread (HighGraphics) [0x009f6d9c]} sys_memory: sys_memory_get_page_attribute(addr=0x29f00000, attr=*0xd0133ba0)
F {PPU[0x70000005] Thread (HighGraphics) [0x009f7578]} struct vm::access_violation thrown: Access violation reading address 0xc
```

**Comment by Exmach** [comment]
BlazBlue Centralfiction:
F {PPU[0x70000000] Thread (main_thread) [0x006fb260]} struct vm::access_violation thrown: Access violation reading address 0x0

**Comment by diegobh** [comment]
RPCS3 v0.0.1-3-973bf5a Pre-Alpha

Game: Rune Factory Tides of Destiny

`S {SPU[0xfa] Thread (cri_cftps3spu: 0)} SPU: SPU Database initialized...
S {SPU[0xfa] Thread (cri_cftps3spu: 0)} SPU: Function detected [0x000d0-0x00158] (size=0x88)
S {SPU[0xfa] Thread (cri_cftps3spu: 0)} SPU: SPU Recompiler (ASMJIT) created...
S {SPU[0xfa] Thread (cri_cftps3spu: 0)} SPU: Function detected [0x00090-0x000c0] (size=0x30)
S {SPU[0xfa] Thread (cri_cftps3spu: 0)} SPU: Function detected [0x00d20-0x00f80] (size=0x260)
S {SPU[0xfa] Thread (cri_cftps3spu: 0)} SPU: Function detected [0x06250-0x0630c] (size=0xbc)
S {SPU[0xfa] Thread (cri_cftps3spu: 0)} SPU: Function detected [0x00f80-0x00f84] (size=0x4)
S {SPU[0xfa] Thread (cri_cftps3spu: 0)} SPU: Function detected [0x060c8-0x0618c] (size=0xc4)
U {PPU[0x7000000f] Thread (_cellsurMixerMain) [0x006ca460]} cellSpurs TODO: cellSpursQueuePopBody
U {PPU[0x7000000f] Thread (_cellsurMixerMain) [0x006ca460]} cellSpurs TODO: cellSpursQueuePopBody
U {PPU[0x7000000f] Thread (_cellsurMixerMain) [0x006ca460]} cellSpurs TODO: cellSpursQueuePopBody
U {PPU[0x7000000f] Thread (_cellsurMixerMain) [0x006ca460]} cellSpurs TODO: cellSpursQueuePopBody
U {PPU[0x7000000f] Thread (_cellsurMixerMain) [0x006ca460]} cellSpurs TODO: cellSpursQueuePopBody
U {PPU[0x7000000f] Thread (_cellsurMixerMain) [0x006ca460]} cellSpurs TODO: cellSpursQueuePopBody
E {PPU[0x70000000] Thread (main_thread) [0x00617160]} PPU: 'sys_spu_thread_group_start' aborted
U {PPU[0x7000000f] Thread (_cellsurMixerMain) [0x006ca460]} cellSpurs TODO: cellSpursQueuePopBody
F {PPU[0x70000000] Thread (main_thread) [0x00617160]} struct vm::access_violation thrown: Access violation reading address 0x0`

**Comment by An1meBlyad** [comment]
hi can u halp me to fix my Err 
![err](https://cloud.githubusercontent.com/assets/24534967/21123207/6fec0b02-c0e8-11e6-9432-e4180706143c.PNG)

**Comment by MarioSonic2987** [comment]
@An1meBlyad Game?

**Comment by An1meBlyad** [comment]
@MarioSonic2987 Demon’s Souls.

**Comment by vinifr** [comment]
sorry guys, i'm a noob. What is means this error you are talking about? 'struct vm::access_violation thrown: Access violation reading address x'

**Comment by ssshadowww** [comment]
Commercial games are not supported because the emulator is in a early state of development, not finished in other words. Demon's Souls or any other real game will not work no matter what you do. Please go to the forum for further questions and do not use Github.

This access violation error probably means nothing in and of itself, it's likely a symptom of several _different_ emulation issues.

**Comment by TheKevinP** [comment]
@MarioSonic2987 NBA 2K17
Is Game

**Comment by pipes80** [comment]
this is a log file when try to launch gran turismo 6, come out only one windows white, I have use:
 ppu interpreter (fast) spu interpreter (fast) gpu: opengl; vSinc 1920x1080

[RPCS3.log1.gz](https://github.com/RPCS3/rpcs3/files/1306443/RPCS3.log1.gz)

**Comment by ValtteriBottas** [comment]
![gt5](https://user-images.githubusercontent.com/32315932/30891062-be54394a-a328-11e7-8c14-694d0911e556.png)

Hello, im new here and i need help with this error.
Is this enough to show?
Thanks.
