### ISSUE TITLE
Vulkan: Broken menu in Hitman 2

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#1935]
This seems to have happened some time ago and went unnoticed. Only noticed it because it caused me problems trying to figure out vulkan face culling. I will continue bisecting, but I can confirm that a build from ~3 weeks ago works.

**Comment by kd-11** [comment]
Breaks here https://github.com/RPCS3/rpcs3/commit/6ae54ae27b048ce260d9067b09d08bcbbfdf1a68

**Comment by raven02** [comment]
@kd-11 , did u try to revert those rsx changes in that commit ? however it seems to be still  not working

**Comment by kd-11** [comment]
well, bisect led me to that commit. I kinda forgot about this bug. I'll inspect a little deeper since ogl is not affected.

**Comment by raven02** [comment]
Looks like the menu come back again in latest build now but somehow corrupted 

![untitled](https://cloud.githubusercontent.com/assets/3000282/17862398/a2c415a2-68c7-11e6-89b9-7d75c1bbdb34.jpg)

**Comment by kd-11** [comment]
Looks like broken emulated primitives, but I could be wrong here (every complementary triangle is degenerate)

**Comment by raven02** [comment]
DX12 looks good . Looks like it is Vulkan specific.

![hit1](https://cloud.githubusercontent.com/assets/3000282/17887643/f362654e-6959-11e6-9030-19c10ebdd58f.jpg)

**Comment by kd-11** [comment]
Actually DX12 on radeon was broken for a long time for this menu (and several other games) but I'll have to retest as soon as I can. Also, supported primitive types differ slightly per backend, with only quads, quad_strips and polygons being truly unsupported. I do have a copy of this game though, so I'll look into this as soon as I am able to.

**Comment by kd-11** [comment]
Looks like (on vulkan) the quads are properly emulated, but when filling submitting the draw call, it is submitted as a regular draw command instead of falling back to indexed draw. This is just a simple glitch that occured during the refactoring effort. Fix incoming

**Comment by raven02** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/2092
