### ISSUE TITLE
DX12: Cell's R6G5B5 texture format returns B5G6R5

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#1938]
In D3DFormats.cpp, I think there's a error which is:

	case CELL_GCM_TEXTURE_R6G5B5: return DXGI_FORMAT_B5G6R5_UNORM;

Shouldn't it be...?

	case CELL_GCM_TEXTURE_R6G5B5: return DXGI_FORMAT_B5G5R6_UNORM;

**Comment by raven02** [comment]
There is no such format DXGI_FORMAT_B5G5R6_UNORM

**Comment by MarioSonic2987** [comment]
Ok. Thanks for the reply.
