### ISSUE TITLE
GL: Puyo Puyo Tetris character wrong color 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1947]
Vulkan
![untitled](https://cloud.githubusercontent.com/assets/3000282/17367890/6154dc30-59c4-11e6-8f49-e25be8b00db2.jpg)

DX12
![dx_1](https://cloud.githubusercontent.com/assets/3000282/16949396/27b2a530-4ded-11e6-8d12-721f15083556.jpg)

GL
![gl_1](https://cloud.githubusercontent.com/assets/3000282/16949400/327a699e-4ded-11e6-9478-28959ddd3053.jpg)

**Comment by raven02** [comment]
If anyone can run it for Vulkan , please post here.

**Comment by raven02** [comment]
It is affected by CELL_GCM_TEXTURE_A4R4G4B4

**Comment by djdv** [comment]
Commit: 7ac9d3b

Vulkan:
![puyo vulkan](https://cloud.githubusercontent.com/assets/13862850/16994501/95957612-4e75-11e6-90ed-87762fc82884.png)

GL:
![puyo gl](https://cloud.githubusercontent.com/assets/13862850/16994504/99148f8a-4e75-11e6-9759-33a77acd2248.png)

I tried playing this game previously on commit f81a02e, I later pulled a build from appveyor with this https://github.com/RPCS3/rpcs3/pull/1653 in it and it resolved a similar issue, below is f81a02e running Vulkan:
![puyo old vulkan](https://cloud.githubusercontent.com/assets/13862850/16995032/15e85580-4e78-11e6-82b3-ad65e23a476c.png)

**Comment by raven02** [comment]
Sorry , i'm digesting . So which commit is the correct one display color in Vulkan?

**Comment by djdv** [comment]
7ac9d3b displays things correctly in Vulkan, f81a02e displays them incorrectly, if I recall correctly after trying pull #1653 it looked fine in Vulkan, I didn't try anything between those 2 so maybe it's unrelated but I felt it was worth mentioning.

**Comment by kd-11** [comment]
@raven02 Another texture format in need of a swizzle fix.

**Comment by raven02** [comment]
@kd-11 . Yep , however it looks like it already swizzled but still not able to correct result .

		case CELL_GCM_TEXTURE_A4R4G4B4: 
			return { GL_BLUE, GL_ALPHA, GL_RED, GL_GREEN

**Comment by raven02** [comment]
Included Vulkan snapshot capture.

**Comment by kd-11** [comment]
@raven02 I'll at least need a command dump if possible. If that isn't enough you could generate a frame dump using renderdoc that I can replay.

**Comment by raven02** [comment]
@kd-11 . This is command dump - [command_dum.zip](https://github.com/RPCS3/rpcs3/files/400201/command_dum.zip)

**Comment by raven02** [comment]
@kd-11 , i captured the frame and please find the attached .

[rpcs3_2016.09.22_21.28.14_frame2775.zip](https://github.com/RPCS3/rpcs3/files/487391/rpcs3_2016.09.22_21.28.14_frame2775.zip)

**Comment by raven02** [comment]
From the rdc , looks like the texture format is RGBA4, so i think it is 

		case CELL_GCM_TEXTURE_A4R4G4B4: 
			return { GL_BLUE, GL_ALPHA, GL_RED, GL_GREEN };

**Comment by kd-11** [comment]
You're right. It should be standard A-R-G-B like the others from the look of things. I think a lot of confusion with texture formats results from the time before we had surface and texture cache: render targets ignore the channel remapping, but the older backend did not differentiate between the two types of texture resources.

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.265/artifacts

**Comment by raven02** [comment]
@kd-11 . Thanks .Issue fixed.

![untitled](https://cloud.githubusercontent.com/assets/3000282/18782895/54ff219c-81bb-11e6-9d84-d24081d3a13e.jpg)

**Comment by raven02** [comment]
However , using this build with The Guided Fate Paradox and Disgaea 3 seem to be broken. (black rendering)

**Comment by raven02** [comment]
Using https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.269/artifacts , The Guided Fate Paradox and Disgaea 3 looks okay now.
