### ISSUE TITLE
LLVM PPU: freezes on After Burner Climax with all backends

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1951]
It freezes when going into the game after selecting an aircraft and sometimes in the menu. IIRC, it sometimes freezes on interpreter too (and in Sonic CD), but much less frequent. No error is reported and I can restart or stop the game just fine.
[Log](http://rgho.st/6hQ5fKdXg)

**Comment by Nezarn** [comment]
@danilaml maybe its like Project Diva F 2nd (that goes infinite loading), since i found this in log, i asked here that if this is implemented, but didn't get any answer....

> ·E PPU: [0x001fcae8] 0x001fcb18: Error: MTFSF
·E PPU: [0x001fd100] 0x001fd100: Error: MFFS

**Comment by raven02** [comment]
Did it freeze in 0.0.0.6 ? as we have a freeze bug identified in Arkedo 01 and Bit runner 2 .It can easily reproduce.

**Comment by kd-11** [comment]
I've seen this on all backends. Started with the 0.0.0.9 update. Some games take forever to load, with hangs ranging upto +5 minutes. Sometimes afterburner climax will continue after hanging for like 10 minutes.

**Comment by raven02** [comment]
Yes , Neko also aware this issue and found some games simply freeze after running for a while however we still cannot find the bug yet.

**Comment by Nekotekina** [comment]
I'd like to implement an option to disable RSX cache, its current implementation is incredibly dangerous.

**Comment by raven02** [comment]
that would like nice as there are quite bunch of games suffer from the freeze or hang issue.

**Comment by vlj** [comment]
what can be done to improve rsx cache implementation ? It's possible to provide an option to disable it however you'll get below 1fps performance.

**Comment by Nekotekina** [comment]
vm::page_protect is completely "selfish" and doesn't care about current vm state. It was supposed to change nearly-permanent memory protection, not to set volatile memory guards. In order to make safe RSX cache, one needs quite different interface for managing temporary memory protection changes. It's similar to reservation which currently supports only one access at a time.

**Comment by danilaml** [comment]
@vlj also, it freezes almost immediately in `Sonic CD`. Btw, it now need pngdec LLEd, without it 
```
F {rsx::thread} struct gsl::fail_fast thrown: GSL: Precondition failure at c:\rpcs3\3rdparty\gsl\include\span.h: 1432
```
 is thrown on all back-ends.

**Comment by raven02** [comment]
i see the old post https://github.com/RPCS3/rpcs3/issues/1628 , it happened before with this error.

**Comment by raven02** [comment]
Try removing this line in span.h and Sonic CD works 

        Expects((offset >= 0 && offset <= this->size()) &&
                (count == dynamic_range || (count <= this->size() - offset)));

**Comment by raven02** [comment]
it is gal::pan<ValueType, dynamic_range> . i think it commonly used in rsx/common

**Comment by raven02** [comment]
texture pitch issue ?

**Comment by raven02** [comment]
Tested with GL and Vulkan as well using LLVM PPU, it also freeze as well.

**Comment by AniLeo** [comment]
I have tested ABC on latest master with OpenGL and doesn't freeze anymore. Can you confirm?

**Comment by danilaml** [comment]
It doesn't seem to freeze with oGL, but it still is broken with other renderers and oGL has some graphical and performance issues: https://github.com/RPCS3/rpcs3/issues/2407
But it's not related to PPU/LLVM, so closing this issue.
