### ISSUE TITLE
DX12: Project Diva F missing character in title screen

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1954]
Vulkan
![untitled](https://cloud.githubusercontent.com/assets/3000282/17084974/ed2f87b4-51fe-11e6-86b0-e1d72176da8f.jpg)

D3D12
![dx12](https://cloud.githubusercontent.com/assets/3000282/16991473/424a72f6-4ece-11e6-9f2e-95e5d381e7da.jpg)

GL
![untitled](https://cloud.githubusercontent.com/assets/3000282/17043230/2d881926-4fe7-11e6-804b-dc2e18aa3ffc.jpg)

**Comment by GhettoGirl** [comment]
On Linux with OpenGL (on older builds)

![](https://cloud.githubusercontent.com/assets/13280758/16379972/89877d6a-3c74-11e6-8a95-8124a4cdd4d4.png)

--

Latest master has a regression ```{rsx::thread} St11logic_error thrown: fs::file is null``` so I can't check.

**Comment by raven02** [comment]
The GL backend in master build is WIP so missing feature is expected

Vulkan one also got fixed recently here https://github.com/RPCS3/rpcs3/pull/1927

**Comment by Nezarn** [comment]
@raven02 for me (when i had GTX970) in Vulkan the 3D modell always showed up, meanwhile in GL\DX12 never (there are some posts on the forum where it did work for some folks, it didn't worked for me), and btw on Intel HD, models are rendering, but flickering. (gonna try post a video in a bit.)

**Comment by kd-11** [comment]
The character is drawn "behind" the screen. Its a framebuffer or depth test issue.

**Comment by kd-11** [comment]
Will sumbit a fix with next PR. That it kinda works with intel means they dont wipe ram when allocating new textures which is rather interesting.

**Comment by zminhquanz** [comment]
DX 12 is missing texture and waste vram to drop FPS when play game for a while

**Comment by raven02** [comment]
GL fixed .D3D12 remains

**Comment by AniLeo** [comment]
@raven02 Can you check again

**Comment by raven02** [comment]
Still missing and we don;t have any code change on the DX12 recently.
