### ISSUE TITLE
RSX: std:: range_error thrown: bad conversion

### ISSUE THREAD

**Issue by Kristiqn5** [RPCS3/rpcs3#1967]
F {rsx: thread} class std:: range_error thrown: bad conversion
Windows 10 14.393 RTM anniversary Update which is going to be available on 02 August causes this problem )
Nvidia drivers 368.95 used
Games which had this message ( may be more ) : 
-After Burner Climax
-Bayonetta
-Initial D
-Ultimate Marvel VS. Capcom 3
 -Ben 10 Galactic Racing

**Comment by raven02** [comment]
Please more specific for example which game hit this error

**Comment by Kristiqn5** [comment]
Bayonetta ( after the loading screen after selecting chapter, sometimes shows cutscene on Epilogue (which is a video and not real time ) but after Its skipped or it finishes it throws that message ) , Ultimate Marvel VS. Capcom 3....
Bleach , How to Train Your Dragon 1/2 doesn't show

**Comment by Kristiqn5** [comment]
why did you change the title, this only occurs on GTX 1080

**Comment by raven02** [comment]
We've seen this error on some other titles and on other Nvidia card.

**Comment by Kristiqn5** [comment]
Well, Zangetsu wanted me to post this issue for him, he said that this happens on Pascal cards , I have a GTX 750 Ti, he has a GTX 980 too and they don't have the problem 
here's a log he sent me from Bayonetta on latest master build using his GTX 1080
http://www.mediafire.com/download/0xf70b61pxvrws5

**Comment by Kristiqn5** [comment]
No longer occurs after he updated to latest Windows 10 build, so its not a problem with GPU but Windows

**Comment by raven02** [comment]
Thanks .Then we will close it .
