### ISSUE TITLE
GL: Braid shader error 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1970]
GL (Passing loading screen then hit the following error)

```
F {rsx::thread} class gl::glsl::compilation_exception thrown: compilation failed: 
0(78) : error C1008: undefined variable "tex0"
0(79) : error C1008: undefined variable "tex0"
0(80) : error C1008: undefined variable "tex0"
0(81) : error C1008: undefined variable "tex0"
```

DX12

![untitled](https://cloud.githubusercontent.com/assets/3000282/17076209/446e094a-50df-11e6-99f6-e2dc1b32444e.jpg)

Vulkan

![untitled](https://cloud.githubusercontent.com/assets/3000282/17876283/8631b130-690b-11e6-9197-87c3458502c8.jpg)

**Comment by PZerua** [comment]
The black texture is an expected behaviour at the beginning of the game (an artistic choice from the author). Just walk to the right and the right texture will be shown.

**Comment by raven02** [comment]
The black texture i mean the whole screen , not the character

**Comment by kd-11** [comment]
@raven02  need the shaderlog for ogl

**Comment by raven02** [comment]
@kd-11  . Here you are - [shaderlog.zip](https://github.com/RPCS3/rpcs3/files/379815/shaderlog.zip)

**Comment by raven02** [comment]
DX12 seems to be broken in latest build now .Will check out regression .

**Comment by raven02** [comment]
For vulkan , here is errors

E {rsx::thread} RSX: ERROR: [SC] Code 3 : fragment shader consumes input location 11.0 which is not written by vertex shader
E {rsx::thread} RSX: ERROR: [SC] Code 5 : SPIR-V module not valid: Operand 4 of MemberDecorate requires one of these capabilities: CullDistance 
E {rsx::thread} RSX: ERROR: [SC] Code 15 : Shader requires VkPhysicalDeviceFeatures::shaderClipDistance but is not enabled on the device
E {rsx::thread} RSX: ERROR: [SC] Code 3 : fragment shader consumes input location 12.0 which is not written by vertex shader
E {rsx::thread} RSX: ERROR: [DS] Code 45 : Render pass subpass 0 mismatch with blending state defined and blend state attachment count 1 while subpass color attachment count 2 in Pipeline (0x15a1)!  These must be the same at draw-time.

**Comment by raven02** [comment]
Vulkan fixed by #2083

**Comment by raven02** [comment]
Further checking , it is from texture_fetch()

	if (cc0.w != 0.0) r1.w = texture_fetch(0, tex0 * ftexture0_cm).w;
	if (cc0.x != 0.0) r1.x = texture_fetch(0, tex0 * ftexture0_cm).x;
	if (cc0.y != 0.0) r1.y = texture_fetch(0, tex0 * ftexture0_cm).y;
	if (cc0.z != 0.0) r1.z = texture_fetch(0, tex0 * ftexture0_cm).z;

**Comment by kd-11** [comment]
Actually wpos is always exported from the vs and always declared as an fs input in the rsx_decompiler. Whats missing is the declaration for tex0, tex1, tex2 and tex3. tex1-3 are unused in this shader but tex0 isn't. I'm guessing some algorithm somewhere decided it was an unused var and ignored it (since the corresponding attrib flag would have been set, I'm assuming it was intentionally left out).
I'll look around and see how the decision is made on which inputs to declare.

**Comment by raven02** [comment]
BTW, I've chat with DH and will try to revert back to our common decompiler shortly since he will no longer work on the new decompiler . That should make our life easier to fix one bug in common decompiler for all backends.

**Comment by kd-11** [comment]
It seems the import control flag used is supposed to be the same as the vs export control flag (and even references the same table). I'm confused why for this game the values fail to line up. The decompiled shader does infact have a separate input mask control flag, but that seems to be unused. Maybe we ought to check against an ORed (combined) mask? I'll have to look for conditions where the algorithm is incorrect.

**Comment by kd-11** [comment]
Hmm. If we're reverting back to the common decompiler this bug should fix itself then. The old decompiler needs some work to output cleaner code though (stuff like.xyzw.xy is ugly)

**Comment by raven02** [comment]
@kd-11 , yep , this game works well with the common decompiler.

**Comment by raven02** [comment]
fixed by https://github.com/RPCS3/rpcs3/pull/2098
