### ISSUE TITLE
LLE: Resogun function not registered (index 2973)

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1971]
It regressed in 0.0.0.9 .When loaded with libsail_avi , it shows the error

F {PPU[0x8eb] Thread (_libsail-control) [0x00fc1a48]} class fmt::exception thrown: Function not registered (index 2973)
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUModule.cpp:157)

**Comment by raven02** [comment]
Then , i try to comment out the throw exception to see how's it is going , it reach title menu again so looks like the 6 cellsailavi<xxxx> function can be loaded from libsail_avi

![untitled](https://cloud.githubusercontent.com/assets/3000282/17076718/11ffc2c0-50ec-11e6-9d5f-930cb61151b9.jpg)

**Comment by kd-11** [comment]
Index 2975 also not registered. https://github.com/RPCS3/rpcs3/issues/1963

Other games are affected as well e.g pixeljunk monsters, but I cant remember which index it is

**Comment by raven02** [comment]
Humm does it mean we have two missing functions unregistered yet for libsail_avi ?

**Comment by raven02** [comment]
@Nekotekina .Any other way we can find the missing functions here? or another way round .

**Comment by Nekotekina** [comment]
See index in logs. Remember about other dependencies (libsail requires a lot of other LLE stuff).

**Comment by raven02** [comment]
Alright found there below .Then how to do next step to get it register?

·E LDR: Unknown function '0xD9B8C0EE' in module 'cellSysmodule' (index 2973)

**Comment by raven02** [comment]
Then i think something like REG_FUNC(cellSysmodule, 0xD9B8C0EE) ?

**Comment by raven02** [comment]
Just register it and looks ok

REG_FNID(cellSysmodule, 0xD9B8C0EE, cellSysmodule_unknown1);

**Comment by Nekotekina** [comment]
Index is not attached to any function in absolute way. It has only temporary meaning.

**Comment by Nekotekina** [comment]
Also I don't remember this issue with libsail, I tested it several times.

**Comment by raven02** [comment]
Can #1976 be a temporary solution for this moment and get merged?

**Comment by Nekotekina** [comment]
Can I see list of LLE modules loaded?

**Comment by raven02** [comment]
Sure .here is the log - [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/379888/RPCS3.zip)

**Comment by SakataGintokiYT** [comment]
@raven02  Index 2975   
Bakugan Battle Brawlers
```
U {PPU[0x1a5] Thread (_libsail-control) [0x00833a48]} cellSysmodule TODO: cellSysmodule_unknown2
F {PPU[0x1a5] Thread (_libsail-control) [0x39800000]} struct vm::access_violation thrown: Access violation reading address 0x39800000
```

**Comment by Nekotekina** [comment]
libsail.sprx requires loading libsail_avi.sprx, libapostsrc_mini.sprx, libmp4.sprx, and optionally everything libadec/libvdec related.

**Comment by kd-11** [comment]
With Pixeljunk Eden and only sre, spurs_jq and resc and I get
```
F {PPU[0x5] Thread (main_thread) [0x003765a8]} class fmt::exception thrown: Function not registered (index 2972)
(in file Emu\Cell\PPUModule.cpp:157)
```

**Comment by raven02** [comment]
Index 2975 is somehow in another module , cellLibprof but not cellSysmodule where i have no idea where to add this missing functions. Totally there are 4 missing functions in the log.

·E LDR: Unknown function '0xB498BF77' in module 'cellSysmodule' (index 2972)
·E LDR: Unknown function '0xD9B8C0EE' in module 'cellSysmodule' (index 2973)
·E LDR: Unknown function '0x05893E7C' in module 'cellLibprof' (index 2974)
·E LDR: Unknown function '0x6D045C2E' in module 'cellLibprof' (index 2975)

**Comment by Nekotekina** [comment]
@raven02 Did you try modules I mentioned?

**Comment by raven02** [comment]
I just tried add those mentioned modules .It yields different index error (2975)

·E LDR: Unknown function '0x6D045C2E' in module 'cellLibprof' (index 2975)
