### ISSUE TITLE
HLE syscall_988

### ISSUE THREAD

**Issue by LordLoras** [RPCS3/rpcs3#1974]
The game i've been trying to run is TRANSFORMERS Devastation.It closes instantly when i try to boot with any settings and any renderer
 {PPU[0xa] Thread (main_thread) [0x0082e308]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK

[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/379504/RPCS3.txt)

**Comment by SakataGintokiYT** [comment]
Duplicate of  #1693

**Comment by raven02** [comment]
Please search for existing issue before open new one.
