### ISSUE TITLE
Vulkan: Unknow Error, this program need to be closed

### ISSUE THREAD

**Issue by thx4ever** [RPCS3/rpcs3#1977]
![captura de tela 1](https://cloud.githubusercontent.com/assets/7145630/17079607/a921f638-50eb-11e6-9dda-be65b1313e81.png)
I'm using Windows 10 with latest nvidia drivers  368.81-desktop-win10-64bit-international-whql
PC Specs: Intel Core i5 4570
Nvidia  Geforce GTX 750
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/379934/RPCS3.zip)
I can't start any game in Vulkan Backend :(

**Comment by Nezarn** [comment]
#1922
