### ISSUE TITLE
Deleted shaderlog dir doesn't get recreated in OGL

### ISSUE THREAD

**Issue by Nezarn** [RPCS3/rpcs3#1984]
DX12 recreates the directory if you delete it, while OGL just throws this error:

> F {rsx::thread} class std::logic_error thrown: fs::file is null

PS: idk how Vulkan behaves, i can't test it.

**Comment by GhettoGirl** [comment]
Can you try #1986 after build is finished.

**Comment by Nezarn** [comment]
works, thanks :p

**Comment by raven02** [comment]
@Nezarn .Which game you tested with fs::file is null ?

**Comment by Nezarn** [comment]
@raven02 Project Diva F for example, but it should be like that with every game if you delete shaderlog dir.

**Comment by raven02** [comment]
I see. thanks
