### ISSUE TITLE
GL/Vulkan : Resogun broken in-game graphic

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1989]
LLE: resc+sre+sail+sail_avi+fiber

**GL**
![untitled](https://cloud.githubusercontent.com/assets/3000282/18952463/4655f09c-867c-11e6-8916-8035237673d1.jpg)

**DX12**
![dx12](https://cloud.githubusercontent.com/assets/3000282/17100821/867b5df4-52a3-11e6-9c1f-428946fd4dab.jpg)

**Vulkan**
![vk](https://cloud.githubusercontent.com/assets/3000282/17100845/a77f45b0-52a3-11e6-8143-006c8b59f311.jpg)

**Comment by raven02** [comment]
Shader log will upload shortly.

**Comment by raven02** [comment]
Regarding the missing base_index fix in #1990 . 

Do we need the base_index for copy_whole_attribute_array() as well ?

void copy_whole_attribute_array(gsl::span<T> dst, const gsl::byte* src_ptr, u8 attribute_size, u8 dst_stride, u32 src_stride, u32 first, u32 vertex_count)
{
    for (u32 vertex = 0; vertex < vertex_count; ++vertex)
    {
        const U* src = reinterpret_cast<const U*>(src_ptr + src_stride * (first + vertex));
        for (u32 i = 0; i < attribute_size; ++i)
        {
            dst[vertex * dst_stride / sizeof(T) + i] = src[i];
        }
    }
}

**Comment by raven02** [comment]
Here is the shader log - [shaderlog.zip](https://github.com/RPCS3/rpcs3/files/386206/shaderlog.zip)

**Comment by kd-11** [comment]
Lighting effects are missing on vulkan. The rather harsh edges on the fog effect in the foreground may be due to several reasons; I'll investigate further.

**Comment by raven02** [comment]
Thanks @kd-11

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/2018 should allow resogun to progress further albeit with some annoying graphical glitches. Doesn't go ingame due to a shader swizzle bug reported elsewhere

**Comment by raven02** [comment]
Thanks @kd-11.

**Comment by kd-11** [comment]
This game no longer works with any backend. Ingame is black (due to failure to upload tc1 vertex attribute). Regression testing needed.

**Comment by raven02** [comment]
i'll will test it shortly to find out the regression

**Comment by raven02** [comment]
Tested with Vulkan backend , it breaks at https://github.com/RPCS3/rpcs3/pull/2146

**Comment by kd-11** [comment]
That PR shouldn't have broken anything on ogl. it only makes generated shaders more sensible syntatically. Also, dx12 doesn't work anymore and I did not touch dx12. I suspect something else has changed. I will however look into why that PR would change anything.

**Comment by raven02** [comment]
Humm DX12 works for me on my system using latest build ,only GL and Vulkan broken for me .Probably we are having different issues?

**Comment by kd-11** [comment]
Okay. I'll investigate.

**Comment by raven02** [comment]
For GL regression , it is first broken at the porting of alpha kill implementation https://github.com/RPCS3/rpcs3/pull/2137

**Comment by raven02** [comment]
The offending statement is 

			if (compare_func == rsx::comparison_function::never) return " discard;\n";

The case is we have no return case for NEVER and ALWAYS but now we discard the fragment when hits NEVER .

**Comment by kd-11** [comment]
never should actually discard if it behaves the same as opengl meaning; i.e always = fragment always passes the test, never = fragment never passes the test.
the comparison function is correct, but i suspect something else is amiss. This means the problem is probably with the z_compare func.

**Comment by kd-11** [comment]
After thinking about it, I think we can remove the never case. It is probably handled differently for texture compare mode.

**Comment by raven02** [comment]
GL backend looks better now though some vertex corruptions

![1](https://cloud.githubusercontent.com/assets/3000282/18875372/191d5f3c-84f8-11e6-9ebe-cafdb86d0d2c.jpg)
![untitled](https://cloud.githubusercontent.com/assets/3000282/18875373/19246214-84f8-11e6-87ec-315e3015a7ff.jpg)

**Comment by kd-11** [comment]
GL issue is an overflow error. We are using u16 to count to 68553.

**Comment by kd-11** [comment]
Issue is actually a bug during refactoring. I'll submit a fix soon.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/issues/2174 fixes this
By the way, on AMD, the cubes are all black for some reason on all backends, including DX12 which suffers from flickering and disappearing visuals if you let the menu go on for a few minutes without interacting with it.

**Comment by raven02** [comment]
Interesting , the green small being in the cubes got disappeared in GL backend.

**Comment by AniLeo** [comment]
#2861
