### ISSUE TITLE
Extremely complex templates (GCM.cpp, rsx_methods.cpp)

### ISSUE THREAD

**Issue by Nekotekina** [RPCS3/rpcs3#1996]
Needs to be fixed in more clever way.
Old implementation with recursion is bad too, as I remember it.
I believe it must be translated to simple for-loop which fills internal method table or something.
Currently it just causes problems for various compilers. For example, rsx_method.cpp took about 3 mins to compile and ate about 3 Gbs of memory.

**Comment by Nekotekina** [comment]
@vlj @DHrpcs3 Possible solution:
1) Change `rsx_method_t` type: add `index` (or `opcode`) additional argument.
2) Accordingly, remove template argument `index`. This will remove lots of almost useless, nearly identical template instantiations. It won't affect the performance because index calculation is trivial.
3) Remove std::integer_sequence in GCM.cpp, fill the table in simple "classic" way in `create_printing_table` function. Reduce associated template complexity accordingly.

Seriously, this is ridiculous. Leave these "cool" techniques where they are really required.

**Comment by Nekotekina** [comment]
Partially fixed in #2005 , at least it compiles normally.
Template simplification is still worth doing though, it may reduce amount of randomly accessed code.

**Comment by scribam** [comment]
Is there still something to do with this issue considering all the code changes since the last update?

**Comment by kd-11** [comment]
Having profiled rpcs3 many times, I can say that the template decoders and their callers never even register on the performance counters, so probably not.

**Comment by elad335** [comment]
Can this be closed?
