### ISSUE TITLE
Vulkan : After Burner Climax vertex fragment error at title screen

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1997]
It stops at title screen with the following error

```
E {rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:162: 'diff_color' : undeclared identifier 
ERROR: 0:162: 'xyz' : vector field selection out of range 
ERROR: 0:162: 'assign' :  cannot convert from 'temp float' to 'temp 3-component vector of float'
ERROR: 3 compilation errors.  No code generated.

F {rsx::thread} class fmt::exception thrown: VKFragmentProgram::Compile(): Failed to compile fragment shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:379)

```

**Comment by kd-11** [comment]
Require vertex & fragment shaders. A command dump would also be helpful (to determine if its related to changes with 2 sided lighting). Also, is it truly consistent or does it only happens some times? I've seen some games where sporadic shader bugs appear; usually in such cases the bug is elsewhere, not the shader compiler.

**Comment by raven02** [comment]
Yes, i can always reproduce it . Here is the shader log - [shaderlog.zip](https://github.com/RPCS3/rpcs3/files/391599/shaderlog.zip)

(somehow i am not able to get command dump )

**Comment by raven02** [comment]
Confirm DX12 works fine and can pass title screen

**Comment by raven02** [comment]
I spot a small typo in PR #1927 

			if (i.name == "front_spec_color")
 				insert_front_diffuse = false;

**Comment by raven02** [comment]
In DX12 , I can see the diffuse_color declare but not in Vulkan one

i.e vec4 diff_color = gl_FrontFacing ? front_diff_color : back_diff_color

**Comment by raven02** [comment]
It should be continue instead of return that skip all the other declare when passes fogc

			if (PI.name == "fogc")
			{
				vk::insert_fog_declaration(OS, m_prog.fog_equation);
				return;
			}

**Comment by kd-11** [comment]
It is indeed a typo. The return statement was pre-existing and I failed to notice it. Thanks
