### ISSUE TITLE
Dragon Ball Z: Burst Limit is broken

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#2001]
Shows black screen with changing fps without sound now (before it went in game).
It looks like https://github.com/RPCS3/rpcs3/pull/1995 is the cause, (works correctly on 33c59fa51b15565dfe67d01fadff882a8ac2e815).
Last errors in log:
```
·E {PPU[0x13b] Thread (NpMatching_udpp2p) [0x00374d44]} libnet: Unknown/illegal socket error: 0
(in file Emu\Cell\Modules\sys_net.cpp:197)
·E {PPU[0x13b] Thread (NpMatching_udpp2p) [0x00374d44]} libnet: setsockopt(): error 23
```

**Comment by raven02** [comment]
@Nekotekina , wondering we need extra LLE to get it running?

**Comment by danilaml** [comment]
@raven02 it works on 33c59fa with only `libsre` LLEd and doesn't on current master even with a lot of things LLEd.

**Comment by raven02** [comment]
Yep , just want to double confirm as Disgaea 3 can show the intro movie without using adec+atx before the PPU refactoring build .

**Comment by Nezarn** [comment]
@danilaml btw theres a typo in the title

**Comment by raven02** [comment]
@danilaml / @Nezarn works okay with pull fix?

**Comment by Nezarn** [comment]
@raven02 i have only the demo, and it only semi-fixes it. (boots only on every 2nd or 3rd try, otherwise its still black screen with fps.)

**Comment by raven02** [comment]
Alright .Thanks.

**Comment by danilaml** [comment]
@raven02 It's some thread synchronization issue, so your fix is more like a hack (it probably was a coincidence that it worked before).
@Nekotekina maybe could solve this properly in a future.

**Comment by paulsapps** [comment]
Sleeps to fix synchronization bugs are always hacks
