### ISSUE TITLE
Regression : Project Diva F intro movie stop playback (sound stop as well at title screen)

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2004]
It start regressed at https://github.com/RPCS3/rpcs3/pull/1995

Last wroking version that can play full intro movie without problem is #1998

**Comment by zminhquanz** [comment]
me too , i don't hear a sound audio when i'm playing project diva f

**Comment by Nekotekina** [comment]
Can't reproduce. What LLE modules?

**Comment by raven02** [comment]
Here it is 

![untitled](https://cloud.githubusercontent.com/assets/3000282/17274965/d6a0a722-572a-11e6-9298-9f745f9bffff.jpg)

**Comment by raven02** [comment]
This time ran it , stop here (FPS is still running)

![untitled](https://cloud.githubusercontent.com/assets/3000282/17275007/ddfcb834-572b-11e6-9af6-a31b1af4c462.jpg)

**Comment by Nezarn** [comment]
@Nekotekina I can reproduce it too. (btw before your thread commit, DX12 had a similiar issue but that only happened after playing for some time.)

**Comment by zminhquanz** [comment]
I switch to DX 12 and it will playing a sound audio , but i switch back to Vulkan and there is no sound audio

**Comment by raven02** [comment]
@Nezarn .Can you help to check again with latest appveyor  build  ? it looks okay to me.

**Comment by zminhquanz** [comment]
let me check that again

**Comment by raven02** [comment]
Thanks @zminhquanz

**Comment by zminhquanz** [comment]
oh , it's worked , using DX 12 , Vulkan , it hear a sound normally again

**Comment by raven02** [comment]
Thanks .Then i'm closing it.
