### ISSUE TITLE
Recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/Gui/SettingsDialog.cpp.o' failed

### ISSUE THREAD

**Issue by teo6389** [RPCS3/rpcs3#2006]
Hello, I am unable to compile rpcs3 under ubuntu.
I am on kubuntu 16.04, 
kernel 4.6.4-040604-generic
cpu i7-6700K
gpu 	Intel® HD Graphics 530
gpu driver i915
cmake version 2.8.12.2
git version 2.7.4

I have removed the yaml-cpp folder from the utilities 
and downloaded the upstream rpcs3/Vulkan/glslang/

I am using the following commands 

git clone https://github.com/RPCS3/rpcs3
cd rpcs3
git submodule update --init
mkdir build
cd build
cmake ..
make

and I receive 

```
/home/teo6389/rpcs3/rpcs3/Gui/SettingsDialog.cpp: In constructor ‘SettingsDialog::SettingsDialog(wxWindow*)’:
/home/teo6389/rpcs3/rpcs3/Gui/SettingsDialog.cpp:325:26: error: no match for call to ‘(const SettingsDialog::SettingsDialog(wxWindow*)::<lambda(std::vector<std::__cxx11::basic_string<char> >&)>) (const std::vector<std::__cxx11::basic_string<char> >&)’
   sort_string_vector(data);
                          ^
/home/teo6389/rpcs3/rpcs3/Gui/SettingsDialog.cpp:325:26: note: candidate: void (*)(std::vector<std::__cxx11::basic_string<char> >&) <conversion>
/home/teo6389/rpcs3/rpcs3/Gui/SettingsDialog.cpp:325:26: note:   conversion of argument 2 would be ill-formed:
/home/teo6389/rpcs3/rpcs3/Gui/SettingsDialog.cpp:325:26: error: binding ‘const std::vector<std::__cxx11::basic_string<char> >’ to reference of type ‘std::vector<std::__cxx11::basic_string<char> >&’ discards qualifiers
/home/teo6389/rpcs3/rpcs3/Gui/SettingsDialog.cpp:319:74: note: candidate: SettingsDialog::SettingsDialog(wxWindow*)::<lambda(std::vector<std::__cxx11::basic_string<char> >&)> <near match>
   static const auto sort_string_vector = [](std::vector<std::string>& vec)
                                                                          ^
/home/teo6389/rpcs3/rpcs3/Gui/SettingsDialog.cpp:319:74: note:   conversion of argument 1 would be ill-formed:
/home/teo6389/rpcs3/rpcs3/Gui/SettingsDialog.cpp:325:26: error: binding ‘const std::vector<std::__cxx11::basic_string<char> >’ to reference of type ‘std::vector<std::__cxx11::basic_string<char> >&’ discards qualifiers
   sort_string_vector(data);
                          ^
rpcs3/CMakeFiles/rpcs3.dir/build.make:6911: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/Gui/SettingsDialog.cpp.o' failed
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Gui/SettingsDialog.cpp.o] Error 1
CMakeFiles/Makefile2:277: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jobs-git** [comment]
Shouldn't you do

````git clone --recursive -j8 git://github.com/foo/bar.git````

**Comment by teo6389** [comment]
I dont know... I just did what butzsan did in this [post](https://github.com/RPCS3/rpcs3/issues/1646).
So instead  of doing "git clone https://github.com/RPCS3/rpcs3" I need to do "git clone --recursive -j8 https://github.com/RPCS3/rpcs3" ?

**Comment by GhettoGirl** [comment]
@teo6389 Please don't remove the bundled yaml-cpp, the upstream may not be compatible anymore - use the builtin one. And forget about Vulkan, there is no X11 support at the moment.
If you are interested in Vulkan use this repo instead-> https://github.com/rcaridade145/rpcs3.git

**Comment by teo6389** [comment]
hello everyone. I dont know how it worked, i did a fresh install of my system, I didnt remove the yaml-cpp, I used the same commands and it compiled!!! @GhettoGirl I used gcc (Ubuntu 5.4.0-6ubuntu1~16.04.1) 5.4.0 20160609
