### ISSUE TITLE
Regression : Disgeae 3 intro movie no longer working

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2007]
Start regressed at https://github.com/RPCS3/rpcs3/pull/1995

PPU interpreter fast + SPU ASMJIT
LLE: dmux+dmuxpamf+sre+resc+rtc
Renderer : Vulkan

**Comment by Nekotekina** [comment]
Not supposed to work without libadec

**Comment by raven02** [comment]
Thanks .Looks like it need both adec+atx that simialr to project diva F

**Comment by raven02** [comment]
Aright .Then i will no longer mark this as regression but requirement like resc+rtc and closing the other related issue.
