### ISSUE TITLE
Unknown command GETLLAR in SSX

### ISSUE THREAD

**Issue by maurocolella** [RPCS3/rpcs3#2009]
Hello, and thank you for this amazing effort.

On Windows 10, With two Geforce in SLI (GTX 970), I get this error when using DX12, OpenGL, or even when attempting Vulkan. 

I tested it today with the latest release rpcs3-ReleaseLLVM-0578430f. 

A window opens up (encouraging), but I get a blank screen with this error message.

**Comment by raven02** [comment]
Duplicate of https://github.com/RPCS3/rpcs3/issues/1781
