### ISSUE TITLE
GL/Vulkan : Infinite Stratos 2: Ignition Hearts graphical glitches

### ISSUE THREAD

**Issue by guohuaXX** [RPCS3/rpcs3#2017]
If using OGL, serious graphic glitches and no sub displayed.
wtih Vulkan, same glitches but able to render subtitle, and always display driver stop responding at certain area.
For audio , no bgm and voice .

By ticking below LLE, music starts playing but can't bypass start screen as well,always hang.
- libat3dec.sprx.elf
- libat3multidec.sprx.elf
- libatrac3multi.sprx.elf
- libatrac3plus.sprx.elf
  
  still no voice though, does anyone have any idea how to get voice working? or any LLE i should give it a try?

**Comment by AniLeo** [comment]
Use the forums for those kind of questions, and provide your RPCS3.log so we can see what can be LLEd

**Comment by kd-11** [comment]
@guohuaXX Please attach screenshots for the visual glitches you experienced along with the zipped contents of the shaderlog folder. You'll have to delete existing files there first to avoid cluttering the shader dump.

**Comment by guohuaXX** [comment]
![01](https://cloud.githubusercontent.com/assets/20795132/17365068/a9224bd2-59b6-11e6-90e3-21f318a6e15d.JPG)
![02](https://cloud.githubusercontent.com/assets/20795132/17365074/a9d5b316-59b6-11e6-85dd-52e13b21d3c2.JPG)

Vulkan will mostly crash at certain place,for example whenever you choose "skip turtorial"




![03](https://cloud.githubusercontent.com/assets/20795132/17365073/a9769516-59b6-11e6-8ff7-0d8ff835aebd.JPG)
![04](https://cloud.githubusercontent.com/assets/20795132/17365072/a926abc8-59b6-11e6-9420-6ece179e0306.JPG)

and it is more than that




![05](https://cloud.githubusercontent.com/assets/20795132/17365071/a925a0e8-59b6-11e6-80fa-1a798e9b491c.JPG)
![06](https://cloud.githubusercontent.com/assets/20795132/17365069/a92390c8-59b6-11e6-98c8-78414533f0f4.jpg)
![07](https://cloud.githubusercontent.com/assets/20795132/17365067/a9200bec-59b6-11e6-990e-19904f914305.jpg)

OGL is running better with just small issue subtitle not showing



![08](https://cloud.githubusercontent.com/assets/20795132/17365070/a925a82c-59b6-11e6-8f3c-933a955645d0.jpg)

bgm starts playing when at3 and atrac3 LLE is ticked, but simply crash right after press start

**Comment by raven02** [comment]
For vulkan , can you enable the debug output ? (under graphic tab) and run it until crash.

**Comment by kd-11** [comment]
@guohuaXX Well, I'm seeing an RSX error about a bad non-array format. That might explain the missing text on opengl. As for vulkan, you'll have to run it with the debugger as requested by raven02.

**Comment by guohuaXX** [comment]
- [ ] 
RPCS3 v0.0.1-5-2b6f8a0 Pre-Alpha
E LDR: Unknown module 'cellDmuxPamf'
E LDR: Unknown module 'cellLibprof'
E LDR: Unknown function '0x05893E7C' in module 'cellLibprof' (index 2974)
E LDR: Unknown function '0x6D045C2E' in module 'cellLibprof' (index 2975)
E LDR: Unknown module 'cellM4vEnc'
E LDR: Unknown function '0x95D2B8F2' in module 'cellM4vEnc' (index 2976)
E LDR: Unknown function '0x4DE475D7' in module 'cellM4vEnc' (index 2977)
E LDR: Unknown function '0x3124A0E0' in module 'cellM4vEnc' (index 2978)
E LDR: Unknown function '0x612F79B0' in module 'cellM4vEnc' (index 2979)
E LDR: Unknown function '0x88902AC0' in module 'cellM4vEnc' (index 2980)
E LDR: Unknown function '0xB82E6F27' in module 'cellM4vEnc' (index 2981)
E LDR: Unknown function '0x8B31F735' in module 'cellM4vEnc' (index 2982)
E LDR: Unknown function '0xA314D362' in module 'cellM4vEnc' (index 2983)
E LDR: Unknown function '0xC85CD08D' in module 'cellM4vEnc' (index 2984)
E LDR: Unknown function '0xBDB1E067' in module 'cellM4vEnc' (index 2985)
E LDR: Unknown function '0xEA99BEC1' in module 'cellM4vEnc' (index 2986)
E LDR: Unknown function '0xC289D964' in module 'cellM4vEnc' (index 2987)
E LDR: Unknown function '0xC708618A' in module 'cellM4vEnc' (index 2988)
E LDR: Unknown function '0xD8C9C9A3' in module 'cellM4vEnc' (index 2989)
E LDR: Unknown function '0xDF3E7FDB' in module 'cellM4vEnc' (index 2990)
E LDR: Unknown function '0xF8292A94' in module 'cellM4vEnc' (index 2991)
E LDR: Unknown function '0x9FB6228E' in module 'sysPrxForUser' (index 2992)
E LDR: Unknown module 'cellMp4'
E LDR: Unknown function '0x390BFF1F' in module 'cellMp4' (index 2993)
E LDR: Unknown function '0x0B1E4B8F' in module 'cellMp4' (index 2994)
E LDR: Unknown module 'cellSailAvi'
E LDR: Unknown module 'cellApostSrcMini'
E LDR: Unknown function '0x736513CA' in module 'cellApostSrcMini' (index 2995)
E LDR: Unknown function '0x24F4ECD3' in module 'cellApostSrcMini' (index 2996)
E LDR: Unknown function '0x9AAA0039' in module 'cellApostSrcMini' (index 2997)
E LDR: Unknown function '0xC4248C51' in module 'cellApostSrcMini' (index 2998)
E LDR: Unknown function '0x752E10C4' in module 'cellApostSrcMini' (index 2999)
E LDR: Unknown function '0x8A6D4227' in module 'cellApostSrcMini' (index 3000)
E LDR: Unknown function '0x35506005' in module 'cellApostSrcMini' (index 3001)
E LDR: Unknown function '0xCF350A4C' in module 'cellApostSrcMini' (index 3002)
E LDR: Unknown function '0x7156446D' in module 'cellApostSrcMini' (index 3003)
E LDR: Unknown module 'cellAvcEnc'
E LDR: Unknown function '0xEC6AE3E8' in module 'cellAvcEnc' (index 3004)
E LDR: Unknown function '0x62526063' in module 'cellAvcEnc' (index 3005)
E LDR: Unknown function '0x0A10C8D1' in module 'cellAvcEnc' (index 3006)
E LDR: Unknown function '0x58AA86CD' in module 'cellAvcEnc' (index 3007)
E LDR: Unknown function '0x19F7C8D1' in module 'cellAvcEnc' (index 3008)
E LDR: Unknown function '0x35D6B9CC' in module 'cellAvcEnc' (index 3009)
E LDR: Unknown function '0x9412E394' in module 'cellAvcEnc' (index 3010)
E LDR: Unknown function '0x42D04FC8' in module 'cellAvcEnc' (index 3011)
E LDR: Unknown function '0x501FE972' in module 'cellAvcEnc' (index 3012)
E LDR: Unknown function '0xE25F7DDA' in module 'cellAvcEnc' (index 3013)
E LDR: Unknown function '0x5E06172D' in module 'cellAvcEnc' (index 3014)
E LDR: Unknown function '0xA93E4417' in module 'cellAvcEnc' (index 3015)
E LDR: Unknown function '0xB68CCFE8' in module 'cellAvcEnc' (index 3016)
E LDR: Unknown function '0xE792E34A' in module 'cellAvcEnc' (index 3017)
E LDR: Unknown function '0xFDCC4831' in module 'cellAvcEnc' (index 3018)
E LDR: Unknown function '0xFF14D87E' in module 'cellAvcEnc' (index 3019)
E LDR: Unknown module 'cellAvchatJpgDec'
E LDR: Unknown function '0x0E520B15' in module 'cellAvchatJpgDec' (index 3020)
E LDR: Unknown function '0x943A6675' in module 'cellAvchatJpgDec' (index 3021)
E LDR: Unknown function '0x4644B39A' in module 'cellAvchatJpgDec' (index 3022)
E LDR: Unknown function '0x4D99E6DF' in module 'cellAvchatJpgDec' (index 3023)
E LDR: Unknown function '0xFD51609E' in module 'cellAvchatJpgDec' (index 3024)
E LDR: Unknown function '0xEF9E83D2' in module 'cellAvchatJpgDec' (index 3025)
E LDR: Unknown module 'cellVpost2'
E LDR: Unknown function '0x4EF16A92' in module 'cellVpost2' (index 3026)
E LDR: Unknown function '0x78FD9E05' in module 'cellVpost2' (index 3027)
E LDR: Unknown function '0x7BC6E690' in module 'cellVpost2' (index 3028)
E LDR: Unknown function '0xAB609749' in module 'cellVpost2' (index 3029)
E LDR: Unknown function '0xCA3CB5B5' in module 'cellVpost2' (index 3030)
E LDR: Unknown module 'cellM4hdEnc'
E LDR: Unknown function '0xB7F4D418' in module 'cellM4hdEnc' (index 3031)
E LDR: Unknown function '0x2A6F33B5' in module 'cellM4hdEnc' (index 3032)
E LDR: Unknown function '0xC1566DAE' in module 'cellM4hdEnc' (index 3033)
E LDR: Unknown function '0x3D32ADD6' in module 'cellM4hdEnc' (index 3034)
E LDR: Unknown function '0x9CA05AEC' in module 'cellM4hdEnc' (index 3035)
E LDR: Unknown function '0x91A0D079' in module 'cellM4hdEnc' (index 3036)
E LDR: Unknown function '0xE394A3BD' in module 'cellM4hdEnc' (index 3037)
F LDR: class fmt::exception thrown: vk::context::createInstance(): Assertion failed! Result is FFFFFFFAh
(in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:1087)

- [ ]

**Comment by raven02** [comment]
@guohuaXX , have you tried to turn on the "debug output " option ?

**Comment by guohuaXX** [comment]
![qq 20160804224217](https://cloud.githubusercontent.com/assets/20795132/17406109/c0a72dac-5a94-11e6-8f76-9a5bb58216c7.jpg)
no dice, it won't even launced if i turn on"debug option"

**Comment by kd-11** [comment]
@guohuaXX You either don't have the vulkan sdk or it is out of date. I had similar issues that were solved by updating vulkan sdk to latest version. Download from lunarg.

**Comment by raven02** [comment]
Yep , download link - https://vulkan.lunarg.com/app/download (need sign in)

**Comment by AniLeo** [comment]
Game is Playable, shouldn't be happening anymore - I'm closing the issue.
