### ISSUE TITLE
HLE: cellpngdec decodes wrong dimension 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2028]
During workaround the span error found in Sonic CD , we found wrong dimension got decoded from HLE Cellpngdec for the following frame that trigger the span error.

(Actually it happened long time ago before the rewrite of pngdec library that have this texture distored)

HLE
![2](https://cloud.githubusercontent.com/assets/3000282/17422847/6c4136aa-5ae8-11e6-8e2a-b9ad27fa923a.jpg)

LLE
![1](https://cloud.githubusercontent.com/assets/3000282/17422846/69de528a-5ae8-11e6-81cc-77c9216e477d.jpg)

**Comment by Zangetsu38** [comment]
last build have allawys problem :/ 
![capture d ecran 2017-01-31 01 48 01](https://cloud.githubusercontent.com/assets/5261759/22448150/8b0cd372-e757-11e6-96c4-85ddf8561c37.png)
