### ISSUE TITLE
GL: Project Diva F fail to boot with primitive_mode error

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2029]
It affect GL only .DX12 and Vulkan are working fine.

F {rsx::thread} class std::runtime_error thrown: Precondition failed: gl::is_primitive_native(primitive_mode)
(in file C:\rpcs3\rpcs3\Emu\RSX\GL\vertex_buffer.cpp:134)

**Comment by Nekotekina** [comment]
Oops.
