### ISSUE TITLE
RAP FILE FOR GAMES

### ISSUE THREAD

**Issue by JCSkyCraft** [RPCS3/rpcs3#2031]
**HOW CAN I KNOW IF MY GAME NEEDS A RAP FILE? PLEASE HELP ME =) , I WILL GREATLY APPRECIATE IT  IF YOU HELP ME**

I TRY SEVERAL THINGS TO GET RAP FILES OF MY GAME BUT IT DIDN'T WORK :(

-I TRY PSNSTUFF BUT I CAN'T FIND SENGOKU BASARA 4 SUMERAGI , ONLY SENGOKU BASARA 4

-I TRY SEARCHED ON GOOGLE BUT NOTHING SHOW UP :/

**I KNOW THAT RPCS3 IS IN EARLY STAGE DEVELOPMENT BUT I STILL TRY MY BEST TO HELP :/**

> RPCS3 is da best?

**Comment by SakataGintokiYT** [comment]
XD  ( ͡° ͜ʖ ͡°)

**Comment by raven02** [comment]
Please post at http://www.emunewz.net/forum/forumdisplay.php?fid=162

**Comment by Nezarn** [comment]
@raven02 he already did http://www.emunewz.net/forum/showthread.php?tid=174696&pid=232134#pid232134

**Comment by JCSkyCraft** [comment]
uhmm i dont understand?
