### ISSUE TITLE
Regression : 1942 Joint Strike no longer working

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2039]
It regressed since https://github.com/RPCS3/rpcs3/pull/2033

**Comment by vlj** [comment]
what is the error ?

**Comment by raven02** [comment]
There is no error and just simply no FPS running .

**Comment by vlj** [comment]
With DX12 backend main menu works. Howeverthere is a crash in data_cache when loading a new game but it occurs at d646fbb94fcc81a1e642b9e6792ef3bac1ec8bf3 too (which predates 2033)

**Comment by sirdanielk** [comment]
It doesnt look like rsx problem. Game goes into first capcom screen with interpreters and stops rendering without reason. With PPU interpreter and SPU asmjit it stops just at begining after loading flashatrac.pic

**Comment by sirdanielk** [comment]
Ups the behaviour is inconsistent. Now it magically got to the title screen and freezed

**Comment by vlj** [comment]
I use spu and ppu interpreter maybe that's why I can go to the menu

**Comment by ikki84** [comment]
Super Street Fighter 2 Turbo HD [NPUB30034] , also stopped working recently using SPU Decoder (Recompiler ASMJIT), when using Interpreter (fast) it can reach the menu.

**Comment by raven02** [comment]
Confirm Super Street Fighter 2 Turbo HD also broken in latest build as well .

**Comment by vlj** [comment]
I dont really know why 2033 would mess with asmjit.

**Comment by raven02** [comment]
Strange .If i compile myself in VS 2015 using latest source , it works but apprevor didn't

**Comment by raven02** [comment]
I tested the own compiled build with Project Diva F , the movie playback is okay without freeze .

This is my own compiled build (non-LLVM) from VS 2015 
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/405600/rpcs3.zip)

**Comment by ikki84** [comment]
Confirmed. 
Super Street Fighter 2 Turbo HD works with raven02 build (SPU ASMJIT)
Last appveyor build, freezes when run.

**Comment by sirdanielk** [comment]
Yep, works ok, with spu jit and interpreter 1942 Joint Strike works too. So, automatic compiler problem?

**Comment by vlj** [comment]
Same here, 0 fps. I don't know why appveyor and VS build differs.
Does it happen with newer appveyor build ?

**Comment by Nekotekina** [comment]
Could be random + different VS update versions affect the chances.

**Comment by ikki84** [comment]
A was checking which build started to Freeze the Super Street Fighter 2 HD in:
https://ci.appveyor.com/project/rpcs3/rpcs3/history

The lastest working build was this one:
Pull request #2021 - rsx: Move index pointer generation in rsx::thread
https://ci.appveyor.com/api/buildjobs/eloe082ejpmdsjlq/artifacts/rpcs3-ReleaseLLVM-7fc429cf.zip

After this one the game got freezing:
Pull request #2032 - Fmt/Log fixes
https://ci.appveyor.com/api/buildjobs/7ojys4480mfvpsn2/artifacts/rpcs3-ReleaseLLVM-88ba135e.zip

both builds from 2 days ago.

**Comment by raven02** [comment]
Latest build looks like working okay again :) Anyone can test and double confirm?

**Comment by ikki84** [comment]
Tested with Super Street Fighter 2 HD, its working. :)

**Comment by raven02** [comment]
Thanks .I'm closing it.
