### ISSUE TITLE
MSVCP140.dll error

### ISSUE THREAD

**Issue by shivangchopra22** [RPCS3/rpcs3#2041]
Whenever I try to start the program, it shows it cannot start as MSVCP140.dll is missing. Please tell me how can I fix this.

**Comment by GhettoGirl** [comment]
Install [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by shivangchopra22** [comment]
Yeah thanks I fixed that but now it says that it's missing openall32.dll

**Comment by GhettoGirl** [comment]
This DLL comes with the build artifacts. It should be there.

**Comment by shivangchopra22** [comment]
Thanks. I did not download the latest build. Now it's working

**Comment by GhettoGirl** [comment]
Would you mind closing this issue then?
Thanks

**Comment by Nekotekina** [comment]
I'll close it then
