### ISSUE TITLE
Longterm log improvements

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#2044]
Maybe something to implement (longterm?) would be outputting logs into a separate log folder per game and timestamp. 

Instead of having a log that contains everything and resets each time the emulator is reopened, once the emulation is started create a log file on a logs folder with the timestamp of the run (formatted with, for example, yyyy-MM-dd-HH-mm-ss) and the GameID and log to it, stopping when the emulation is ended or it crashes and starting another file when another emulation process is started\* [edited, see below].

The end filename would be something like BLJM00000_2016-08-08-17-17-30 or BLJM00000_20160808-171730.

**Comment by Nekotekina** [comment]
Although seems easy to implement, some logs may be really big and trash the disc quite easily. But as a longterm improvement, yes.

**Comment by AniLeo** [comment]
I see a few approaches to that, not sure if the most ideal ones:
- While logging check if the current line is equal to the previous one, if yes then don't append it to the log file. (This would reduce big logs that are spammed by the same thing in a loop);
- After the emulation is stopped, compress the log file (to .zip or .7z) to save disc space;
- Limit the log files folder's maximum size as a configurable setting OR limit the log file's maximum size as a configurable setting (not ideal, seems more like a workaround, users can manually delete logs).

**Comment by paulsapps** [comment]
It would be hard to do that in crash cases :)

**Comment by AniLeo** [comment]
The last two points above, yes. 
Correcting what I've said above (I forgot about the crash scenarios), once the emulation is started create the log file with the start timestamp and start appending to it until it crashes, just like the way it works now.
Zipping logs would be ideal because it saves up a pretty good amount of space, even if only in cases where there isn't a crash.

**Comment by Megamouse** [comment]
this might need an update

**Comment by AniLeo** [comment]
I checked recently, but the log doesn't work per timestamps as would be ideal and it's more bugged now

**Comment by dio-gh** [comment]
The modifications asked in the third comment has been fulfilled, but overall the ticket is still valid. I'd also welcome this addition, though I think separating each run/session of RPCS3 into folders would be needed, if the logfiles are going to be split based on the ran game.

**Comment by Darkhost1999** [comment]
I feel like this is a given but don't see a comment about it.
Storing stuff on disk even old log files should always be user choice.

# So if/when implemented there should be a boolean available for the end user.

Also how many logs? Are they one for each and every game you own so you have a log per GameID or would it be the past X amount of times RPCS3 ran?

**Comment by Asinin3** [comment]
I would like RPCS3 to archive the current log and create a new file whenever someone decides to boot another game with a different gameID than what they previously ran. This way people wouldn't need to close and re-open RPCS3 to get a clean log, and with the changes from #11519 naming the logs with the name of the game you ran last in your log this would make a lot more sense too.

> Storing stuff on disk even old log files should always be user choice.
You can already turn them off... Advanced > Silence all Logs

**Comment by ScottieD** [comment]
So log retention with a user defined log rotation policy?
