### ISSUE TITLE
DX12: Gradient Post Process not blending on screen on Bayonetta

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2046]
![i894 cimgpsh_orig](https://cloud.githubusercontent.com/assets/13494982/16932583/cd632a98-4d4f-11e6-99e9-792252e3a027.png)
In the demo theres no post process used in the first cutscene so you could see, the background rendered perfectly ( with some vertex corruptions here and there ) and models kinda did not
![bayonet 2](https://cloud.githubusercontent.com/assets/13494982/16932616/248db432-4d50-11e6-97a4-ecb6381610e1.png)
![bayonet 3](https://cloud.githubusercontent.com/assets/13494982/16932636/4c895b08-4d50-11e6-91ea-155a889dccfb.png)
I used PR #1931

**Comment by raven02** [comment]
@Kristiqn5 , can you check out Vulkan backend to see hows' the blending ?

**Comment by Kristiqn5** [comment]
Still the same sadly :/
![i1805 cimgpsh_orig](https://cloud.githubusercontent.com/assets/13494982/17512451/8b6435fa-5e30-11e6-9ad7-1955f7de02d6.png)

**Comment by raven02** [comment]
Thanks @Kristiqn5 .

**Comment by Kristiqn5** [comment]
yea same error

**Comment by raven02** [comment]
Thanks . This is line 415 but nothing special . Just wonder which GPU you are using ? 

https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/GL/GLGSRender.cpp#L415

**Comment by Kristiqn5** [comment]
GTX 750 Ti
