### ISSUE TITLE
DX12: Blade Arcus From Shining EX malformed texture

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2051]
DX12 specific issue . Vulkan and GL both okay

![a1](https://cloud.githubusercontent.com/assets/3000282/17510108/18ec4b1e-5e50-11e6-92bb-dec2479b6895.jpg)

![a2](https://cloud.githubusercontent.com/assets/3000282/17510117/27404c74-5e50-11e6-83e7-df6a9683bf2b.jpg)

![a3](https://cloud.githubusercontent.com/assets/3000282/17510120/2a5a8dc0-5e50-11e6-818b-62a14b1c405c.jpg)

**Comment by MarioSonic2987** [comment]
Is it still an issue?

**Comment by raven02** [comment]
I cannot get it to boot now in DX12 using latest build .It hits the following error. GL and Vulkan still looks fine.
