### ISSUE TITLE
DX12/GL/Vulkan : TNT Racers missing in-game textures

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2053]
This applied to all backends that missing in-game textures as shown below.

![b1](https://cloud.githubusercontent.com/assets/3000282/17510578/208e776e-5e52-11e6-93f3-9d9e755b373c.jpg)

![b2](https://cloud.githubusercontent.com/assets/3000282/17510584/268da612-5e52-11e6-953c-3defdd4fd524.jpg)

**Comment by kd-11** [comment]
We're missing vertex_draw_count for those draw calls; it is set to zero for some reason. I'm suspecting its an issue on the rsx draw call preparation code. I'm looking into a viable fix/workaround that wont affect other games.

**Comment by kd-11** [comment]
The vertex_draw_count issue I have tracked down, but that only affected opengl. The game seems to be rendering the cars outside the viewable area, I'm suspecting its the same bug as virtua fighter 5 where the offset are not properly computed

**Comment by raven02** [comment]
Thanks for E.T. to discover the long awaited missing in-game graphics here . It is related to SPU .
The in-game graphic got displayed correctly using SPU precise (not fast or ASMJIT)
![tnt](https://cloud.githubusercontent.com/assets/3000282/24852305/909f4e6c-1e09-11e7-941e-fb1be367c991.jpg)

**Comment by kd-11** [comment]
Seems like alot of broken computation bugs are due to spu issues
