### ISSUE TITLE
Feature request : hide cursor in full screen mode

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2054]
It would be good if anyone familiar with wxWidgets can implement it .

**Comment by Zangetsu38** [comment]
Is better if you implement this only for full screen, like requested, actually you have set this for all time

**Comment by raven02** [comment]
Yes , it would be better in full screen only.

**Comment by isshininu** [comment]
I noticed that too. Cursor disappears in window mode too.
There could be a way for improvement.
