### ISSUE TITLE
Regression :  1942 Joint Strike boot up with black screen (Vulkan Specific)

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2057]
Only affects Vulkan . DX12 and GL work fine.

Regressed at https://github.com/RPCS3/rpcs3/pull/1982 (rsx: Use bitfield template to decode values)

**Comment by raven02** [comment]
This one is a rsx-wide changes and should affect all backends but only Vulkan .Strange.

**Comment by raven02** [comment]
@vlj , any insight?

**Comment by vlj** [comment]
Maybe it's because of the way that Vulkan manages buffer/index.
Does https://github.com/RPCS3/rpcs3/pull/2037 change it ? Vulkan and dx12 index code are closer with this PR.

**Comment by raven02** [comment]
Just tried out #2037 , still the same (black screen with running FPS and working sound)

**Comment by raven02** [comment]
Blade Arcus From Shining EX also regressed at this commit .

**Comment by vlj** [comment]
It looks like an instance of #2061.

What happens is that vertex shader writes color to location 10 while fragment reads color in location 11.
If I force m_prog.front_back_color_enabled to false Joint Strike is fixed.

Not sure if there is an elegant solution to this. The behavior of 2 sided color is a bit obscur(I did a lot of trial and error on Outrun Arcade to get it right to DX12) and having an API agnostic code to support it would be nice however the fragment compiler code for glsl and hlsl are rather divergent atm.

**Comment by raven02** [comment]
Yep , Blade Arcus From Shining EX and Castle Crashers also working again if force m_prog.front_back_color_enabled to false

**Comment by raven02** [comment]
Marvel Vs Capcom 2 and Super Street Fighter II HD Remix also got fixed with disabled 2 side lighting .
