### ISSUE TITLE
Vulkan memory leak

### ISSUE THREAD

**Issue by Nekotekina** [RPCS3/rpcs3#2058]
@kd-11 
Looks like it's easy to reproduce, restart the simplest triangle sample several times and it will increase rpcs3 memory consumption each time (~250-300 MB). OGL doesn't.

**Comment by kd-11** [comment]
Will look into it. The renderer does a really poor job of cleanup during exit.

**Comment by kd-11** [comment]
This has been fixed

**Comment by raven02** [comment]
Thanks @kd-11 .I'm closing it then.
