### ISSUE TITLE
Segmentation Fault when trying to start BOOT.BIN

### ISSUE THREAD

**Issue by orbea** [RPCS3/rpcs3#2059]
OS: `Slackware64-current`
`rpcs3-2016.08.09_bdeccd8_master-x86_64-1_git`

```
Thread 1 "rpcs3" received signal SIGSEGV, Segmentation fault.
0x000000000150fea0 in operator&<unsigned int, unsigned int> (left=..., right=...) at /tmp/SBo/rpcs3/rpcs3/../Utilities/BEType.h:810
810             return{ left.raw_data() & right.raw_data(), se_raw };
```

Full gdb log: http://pastebin.com/Fpc14XQA

**Comment by Nekotekina** [comment]
Interesting, what compiler used?

**Comment by orbea** [comment]
`gcc-5.3.0`

Could this issue https://github.com/RPCS3/rpcs3/issues/1818 be relevant? The severity and quantity of warnings has since increased...

**Comment by al0xf** [comment]
This issue is confirmed and is on the new todo list under short term goals.

**Comment by orbea** [comment]
@al0xf Can you still reproduce this issue? I tried again and while elf files still do not start here, rpcs3 is not segfaulting anymore. Was this fixed or did I manage to work around it unintentionally?

**Comment by al0xf** [comment]
I think this particular issue is fixed, but the Linux builds are still busted for other reasons, for example broken shader cache. Leave this one open for now, Neko knows more.

**Comment by orbea** [comment]
Alright, I'll leave it open for further discussion. Thanks. :)

**Comment by AniLeo** [comment]
This was fixed, plus the other Linux bugs that didn't allow for games to work were also fixed. 
There are a couple of unrelated Linux bugs still, but those are reported on other issues.
I'll be closing this.
