### ISSUE TITLE
Regression : Castle Crashers  boot up with black screen  (Vulkan Specific)

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2061]
1st Regressed at https://github.com/RPCS3/rpcs3/pull/1927 (vk/dx12: Enable/fix separate back and front lighting)

Last working version - https://github.com/RPCS3/rpcs3/pull/1916

**Comment by raven02** [comment]
@kd-11 FYI

**Comment by kd-11** [comment]
What happens with the crash? Is it a shader compilation issue? If so, will need logged shaders

**Comment by SakataGintokiYT** [comment]
@kd-11 
State  : Black screen 
Shaders log:
https://mega.nz/#!FUhmWLCA!-7PNUHGVKt3zf2PNCxs2jUCNtwTJhUdPY_fGkA4MO8c

**Comment by raven02** [comment]
@kd-11 . Looks like it is 2 sided color issue . vlj tried to force m_prog.front_back_color_enabled to false and fixed this game as well as 1942 Joint Strike.

**Comment by kd-11** [comment]
Hmm. I'll look into the shader generation with 2 sided lighting enabled. But 1942 joint strike was working until recently even with 2 sided lighting enabled. Something else changed.

**Comment by raven02** [comment]
Yes , i also remember 1942 works okay when 2 sided lighting enabled that time .
