### ISSUE TITLE
Regression : Dai-3-Ji Super Robot Taisen Z Jigoku-hen

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2067]
Regressed and failed to reach title screen at https://github.com/RPCS3/rpcs3/pull/2056

**Comment by raven02** [comment]
@kd-11 , i remember you have this title . can you help to confirm if it works for you or not?

**Comment by raven02** [comment]
Looks like it threading issue . Previous build i can see 0xb6 and 0xb7 thread but after this commit didn't

**Comment by raven02** [comment]
It looks like stuck at

> U {PPU[0x8000009c] Thread (trophy_get_disk_space_thread) [0x00617e00]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0xa2, handle=0xa4, reqspace=*0x22899e70, options=0x0)

**Comment by raven02** [comment]
@Nekotekina , any insight in the change that may trigger this behaviour?

**Comment by kd-11** [comment]
@raven02 I haven't checked just yet, but this game already had cpu side issues before and even probably heap corruption. The problem may have just been hidden before.

**Comment by raven02** [comment]
Yes , this game is specially need to press combination keys (select+start+R1+R2) in order to get into title menu instead of bootup propertly as the other games.

**Comment by raven02** [comment]
Tried out with latest build with cellGameDataCheck fixed . It now bootup with data installation then terminated. 

![untitled](https://cloud.githubusercontent.com/assets/3000282/17758312/c97a137c-6520-11e6-8f54-17008ca5f7f5.jpg)

![1](https://cloud.githubusercontent.com/assets/3000282/17758315/d2e5d270-6520-11e6-96ec-2615b2c6ac92.jpg)

**Comment by raven02** [comment]
This has double // strike 

E {PPU[0x80000010] Thread (GameDataInstallThread) [0x00617020]} sys_fs: sys_fs_opendir(“/dev_hdd1/game/BLJS10256_DATA/USRDIR//INSCO/”): failed to open directory

**Comment by Nekotekina** [comment]
Could be fixed in last PR, at least it installs successfully.

**Comment by raven02** [comment]
Yes, the installation confirmed successfully now without crash and moved back to /dev_hdd1/game/ as original PS3 .

Having said that , the game is still not working yet due to threading/ sync bug
