### ISSUE TITLE
Project Diva F 2nd PPU+SPU emulation bugs ?

### ISSUE THREAD

**Issue by Nezarn** [RPCS3/rpcs3#2075]
The only way to go ingame gameplay is to go to the tutorial, but even that "freeze", after a random time the sound gets muted and the 3D model stops, but pause menu is still accessable.

Video: https://www.youtube.com/watch?v=zJFvqOV9LBI

Log: https://gist.github.com/Nezarn/7cc9fa1febd62049944ed74db8f76117

> ·W {PPU[0x80000000] Thread (main_thread) [0x00673f68]} PPU: MFFS
> ·W {PPU[0x80000000] Thread (main_thread) [0x00673f5c]} PPU: MTFSF

(these 2 comes up with LLVM too, but with error instead of warning)

Before someone comments that "don't use ASMJIT SPU":

With Interpreter SPU (fast), game gets stuck as soon sound would play (at SEGA logo, fps freeze)

Video: https://www.youtube.com/watch?v=BeBVlAlVaPs

Log: https://gist.github.com/Nezarn/179a2bfe6fed50687b5f1f4ff09abc19

With Interpreter SPU (precise), game has the same problem as with ASMJIT, but has no sound from the beginning (not even at SEGA logo)

Video: https://www.youtube.com/watch?v=j5qU4tHlO0U (at the long loading bug (this randomly occurs with every PPU\SPU settings) jump to 6:34, also you can see spinning miku which i think is a cpu emulation bug too)

Log: https://gist.github.com/Nezarn/7a247a7a70c6f5e7a16cc2a0fec125ba

PS.: With the settings that can reach to the Tutorial ingame gameplay, if i go and select a real song, game just goes on infinite loading (once i waited 8 hours and it still was at now loading screen, with loading animation and the fps was moving too so not froze.)

edit: just noticed that i didn't tested with master (but with the new pull request), but just tried it quickly with master build too, its the same, before someone tells me to try on master.

**Comment by zminhquanz** [comment]
PPU and SPU isn't completely yet , and not emulate accurately , so game has the bugs

**Comment by Nezarn** [comment]
@zminhquanz Thanks captain obvious

**Comment by Nekotekina** [comment]
Test

**Comment by AniLeo** [comment]
F 2nd works now and it's Playable. Only has a few minor graphical glitches
