### ISSUE TITLE
Help, which Libraries to load

### ISSUE THREAD

**Issue by AhmedTawab** [RPCS3/rpcs3#2076]
U {PPU[0x80000000] Thread (main_thread) [0x0001bab4]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x80000000] Thread (main_thread) [0x0001bc3c]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x80000000] Thread (main_thread) [0x0001b9d4]} cellGame TODO: cellGameGetSizeKB
E {PPU[0x80000000] Thread (main_thread) [0x0001b8bc]} PPU: 'sceNpDrmProcessExitSpawn2' aborted
F {PPU[0x80000000] Thread (main_thread) [0x0001b8bc]} struct vm::access_violation thrown: Access violation reading address 0x2f686f73

I keep getting these results while trying to start Fifa street 2012 on RPCS3 with no loaded libraries.

Can any one tell me what are the libraries that need to be loaded ?

**Comment by raven02** [comment]
Please check and ask this here - http://www.emunewz.net/forum/forumdisplay.php?fid=162
