### ISSUE TITLE
Demon's Souls  Unsupported SPU Thread options

### ISSUE THREAD

**Issue by G33ko** [RPCS3/rpcs3#2077]
Game: boot done.
{PPU Thread[0x1] (main_thread)[0x016bb9bc]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU Thread[0x1] (main_thread)[0x016bb9bc]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU Thread[0x1] (main_thread)[0x016bb9bc]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU Thread[0x1] (main_thread)[0x016bb9bc]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU Thread[0x1] (main_thread)[0x016bb9bc]} sys_spu: Unsupported SPU Thread options (0x2)
{PPU Thread[0x4a7] (HighGraphics)[0x009f8814]} sys_memory: sys_memory_get_page_attribute(addr=0x29f00000, attr=*0xd0143ba0)
{PPU Thread[0x4a7] (HighGraphics)[0x009f8ff0]} Exception: Access violation reading location 0x0000000c
(in file ..\Utilities\Thread.cpp:1133, in function throw_access_violation)
Please report this to the developers.

Any fix for this?

Version 0.0.0.6-4125-2ead9b1

**Comment by raven02** [comment]
Please check this game here http://www.emunewz.net/forum/forumdisplay.php?fid=162 and report there.
