### ISSUE TITLE
DX12/Vulkan: The Awakened Fate: Ultimatum shader error

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2085]
GL (In-game and can control the character)

![untitled](https://cloud.githubusercontent.com/assets/3000282/17903710/0d3fdbd2-699f-11e6-8515-3cab7a8ce499.jpg)

DX12 (Almost in-game but stuck at this dialog before we can control the character)

![1](https://cloud.githubusercontent.com/assets/3000282/17903728/18163ca4-699f-11e6-824a-841b979ce4c9.jpg)

F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:64)

Vulkan (Stuck after see the Mission 01)

```
E {rsx::thread} RSX: Warning, version 450 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:70: 'floor' : ambiguous function signature match: multiple signatures match under implicit type conversion 
ERROR: 0:70: 'assign' :  cannot convert from 'global 4-component vector of double' to 'temp 4-component vector of float'
ERROR: 0:73: 'floor' : ambiguous function signature match: multiple signatures match under implicit type conversion 
ERROR: 0:73: 'assign' :  cannot convert from 'global 4-component vector of double' to 'temp 4-component vector of float'
ERROR: 4 compilation errors.  No code generated.
E {rsx::thread} RSX: 
F {rsx::thread} class std::runtime_error thrown: Failed to compile vertex shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKVertexProgram.cpp:318)
```

**Comment by kd-11** [comment]
please attach the buggy vertex shader

**Comment by raven02** [comment]
Sure . Here it is [shaderlog.zip](https://github.com/RPCS3/rpcs3/files/433205/shaderlog.zip)

**Comment by kd-11** [comment]
looks like floor() is broken. Fix incoming.

**Comment by kd-11** [comment]
@raven02 check if https://github.com/RPCS3/rpcs3/pull/2092 fixes the vulkan issues casting the double vec4 to a float vec4

**Comment by raven02** [comment]
It comes with the following shader error now

```
E {rsx::thread} RSX: Warning, version 450 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:70: 'floor' : ambiguous function signature match: multiple signatures match under implicit type conversion 
ERROR: 0:73: 'floor' : ambiguous function signature match: multiple signatures match under implicit type conversion 
ERROR: 2 compilation errors.  No code generated.


E {rsx::thread} RSX: 
F {rsx::thread} class std::runtime_error thrown: Failed to compile vertex shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKVertexProgram.cpp:318)
```

**Comment by kd-11** [comment]
Seems the glsl to spirv compiler does not like it when floor is called with an integer (instead of a float) and gets confused. The glsl spec is way too vague on this. I'll have to find a better workaround

**Comment by raven02** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/2092
