### ISSUE TITLE
DX12/GL/Vulkan: Bit Trip Presents Runner 2

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2089]
@raven02 
[d7a899f9]
```
F {rsx::thread} class std::runtime_error thrown: Unknown texture dimension 0
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:139)
```
Log : https://gist.github.com/SakataGintokiYT/a6d3dd255742ea541d3466f10dd0bc9b

**Comment by raven02** [comment]
I tested but i didn't encounter this error .Wonder which scene you hit this error?

**Comment by SakataGintokiYT** [comment]
@raven02 
<img src="http://www.fotoszok.pl/upload/7e5f45b1.jpg" alt="Fotoszok.pl" />

**Comment by raven02** [comment]
Humm it only freeze for me but didn't see this error .Did you get this error in GL and Vulkan backend?

**Comment by SakataGintokiYT** [comment]
@raven02 
Yes

**Comment by kd-11** [comment]
The texture_dimension var is used to choose between 1D, 2D, CUBE and 3D textures. Maybe 0 is a special type of one of the other 4 or an error in which case we should pick a default instead of crashing like a real ps3.

**Comment by raven02** [comment]
It triggered from rsx::to_texture_dimension() and should be calling either from the following texture function 

	rsx::texture_dimension texture::dimension() const
	{
		return rsx::to_texture_dimension((registers[NV4097_SET_TEXTURE_FORMAT + (m_index * 8)] >> 4) & 0xf);
	}

**Comment by raven02** [comment]
@SakataGintokiYT , can you try out latest master build to see if the issue persists?

**Comment by SakataGintokiYT** [comment]
[b159d7e9] Log : https://mega.nz/#!QMQgyZoC!A5J_fAroRBEYvRkM2BZybIUdJUOHSP6XwidLV02BMYk
[92c85a87] Log :  https://mega.nz/#!5ZR0gaZR!QhuXQBauPzVjTQonxshHTxpTnqA7fO2ZUrah_5jHFkI

**Comment by raven02** [comment]
Can you try this one to see if you see any fragment texture = 0 ?

https://mega.nz/#!MVo3iCTT!8_g_ExZnLWTYsvwQC_R-wzXbectXJgB9WWrP9ByhHgg

**Comment by SakataGintokiYT** [comment]
@raven02 Still ;/
```
F {rsx::thread} class std::runtime_error thrown: Unknown texture dimension 0
(in file Emu\RSX\gcm_enums.cpp:139)
```

**Comment by raven02** [comment]
Yes, but did you see log console display fragment texture = 0 or something else?

**Comment by SakataGintokiYT** [comment]
@raven02  i don't see

**Comment by raven02** [comment]
ok thanks

**Comment by raven02** [comment]
@SakataGintokiYT , just wonder did you still hit this issue using latest build?

**Comment by SakataGintokiYT** [comment]
@raven02 
I re-install the game and this error no longer appears.
