### ISSUE TITLE
GL/Vulkan : The Guided Fate Paradox rendering issue

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2093]
Vulkan one is bit different in rendering the title screen (eg. sky outline) than DX12 and GL is highly broken.

Vulkan 
![3](https://cloud.githubusercontent.com/assets/3000282/17904582/7c740980-69a2-11e6-9e62-80db70139bbf.jpg)

DX12
![1](https://cloud.githubusercontent.com/assets/3000282/17904538/49699e38-69a2-11e6-8486-fa054d18363b.jpg)

GL
![2](https://cloud.githubusercontent.com/assets/3000282/17904535/46d7cdc0-69a2-11e6-9e5a-3c5a8fe02e7b.jpg)

**Comment by kd-11** [comment]
Alpha is messed up. Since DX12 and vulkan share shader generation, vulkan issue will likely be a texture format issue. GL could be anything from texture issues to shader clamping.

**Comment by Nekotekina** [comment]
Test

**Comment by raven02** [comment]
Alright .i will take a command dump at the title screen .

**Comment by kd-11** [comment]
Has the GL output changed with the revert to the old decompiler?

**Comment by raven02** [comment]
No , it is the same

**Comment by kd-11** [comment]
Probably not a shader issue then. This makes me suspect texture format even more.

**Comment by raven02** [comment]
The title screen used two texture only - B8 and A8R8G8B8 and GL backends didn't do any remap for A8R8G8B8 yet.

**Comment by kd-11** [comment]
While debugging https://github.com/RPCS3/rpcs3/issues/2178 I realized, that this has nothing to do with texture swizzles. The texture used is B8 and some shader magic is used to generate that color output.
I'm investigating what is broken.

**Comment by kd-11** [comment]
This is a simple case of decoding a pallete texture using the GPU. Replacing their decoding algorithm with my own shader gives correct results:

![image](https://cloud.githubusercontent.com/assets/15904127/19069415/90ade33c-8a2f-11e6-8d1d-be0c44e703f7.png)

**Comment by kd-11** [comment]
Figured out what the problem is, but it requires somewhat of an architectural change. @raven02 Could you attach a command dump of this scene?

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.307 should dump some important info to the log file. You should run that and upload your log file.

**Comment by raven02** [comment]
Log here - [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/508284/RPCS3.zip)

**Comment by kd-11** [comment]
```
·W {rsx::thread} RSX: Texture 89, target 0xde1, requesting mipmap filtering without any mipmaps set!
```

**Comment by kd-11** [comment]
Incomplete texture. By the way, is it still broken using that build? There's a hack in there to force max_level value to zero. If its still broken, I'll upload a different workaround and we can see if it works.

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.308 respects sampling parameters even when using a fallback path and sets the renderer to ignore LOD parameters.

**Comment by raven02** [comment]
1.0.307 still broken . Will test 1.0.308 .

**Comment by raven02** [comment]
Appveyor crashed

**Comment by kd-11** [comment]
Restarted https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.309

**Comment by raven02** [comment]
It worked prefectly with GL backend .

**Comment by kd-11** [comment]
OK. Will create a pull request for this and https://github.com/RPCS3/rpcs3/issues/2178

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/issues/2188 should hopefully fix this for both.
