### ISSUE TITLE
Vulkan : The Awakened Fate: Ultimatum black character issue

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2095]
DX12 (hit working buffer not enough)`

![untitled](https://cloud.githubusercontent.com/assets/3000282/18026316/e4c9c0e0-6c74-11e6-9221-91ad0dc8357c.jpg)

```
F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough
(in file c:\users\jacky\documents\github\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:64)
```

GL

![0d3fdbd2-699f-11e6-8515-3cab7a8ce499](https://cloud.githubusercontent.com/assets/3000282/17915067/0b4478ca-69da-11e6-9706-7f2f4da05329.jpg)

Vulkan

![untitled](https://cloud.githubusercontent.com/assets/3000282/17915055/f25fed08-69d9-11e6-881d-70eeff0607b1.jpg)

**Comment by raven02** [comment]
@kd-11 ,  I think it is unimplemented lighting in Vulkan , isn't ?

**Comment by kd-11** [comment]
Probably just a shader error here, or broken linking of vars from vs stage to fs stage. Resogun behaves the same way as well as several games where some shader effects are inexplicably missing. I'd need to analyze the frame in depth to determine what the problem really is. rpcs3 needs a frame capture and replay feature.

**Comment by raven02** [comment]
i'll take a command dump from this scene from both Vulkan and dx12 so you can compare them

**Comment by raven02** [comment]
Here is the command dump 

Vulkan - [vk_command_dump.zip](https://github.com/RPCS3/rpcs3/files/440600/vk_command_dump.zip)


GL -

**Comment by raven02** [comment]
I can see vulkan backend declare back_diffuse_color and back_specular_color

**Comment by raven02** [comment]
It turns out to be cull face issue .
