### ISSUE TITLE
Save AOT compiled code cache

### ISSUE THREAD

**Issue by emmauss** [RPCS3/rpcs3#2099]
The AOT recompiler is great, but it will recompile the same game every time you start it.that takes about 15min for large games to start. cant the already compiled code be cached and used multiole times until there is a significant change in the compiler.

**Comment by Nekotekina** [comment]
This has been in TODO list from the start.
There are still other intermediate problems, however.

**Comment by emmauss** [comment]
read from the progress report that rpcs3 now save the LLVM compiled code. I have also confirmed that the cache persists between sessions. Can this be closed?
