### ISSUE TITLE
Memory address space

### ISSUE THREAD

**Issue by unknownbrackets** [RPCS3/rpcs3#210]
Is the memory address space 32 or 64 bit?

The current memory system assumes it's 64 bit.  IsMyAddress, GetStartAddr, SetRange, etc. are all 64 bit values.

However, all valid addresses are within 32 bits afaiu.

So, my question is - what is `sizeof(int *)` on a ps3?  Can `sys_vm_memory_map()` be used to map into the normally unsused space?  It seems like not, if this is correct: `typedef u32 sys_addr_t;`.

If I load a register with `X | 0x1234567800000000ULL` and read from that address, should it access X or segfault?

-[Unknown]

**Comment by tambry** [comment]
Is this still relevant or can it be closed?

**Comment by unknownbrackets** [comment]
Well, I've lost interest for the time being, although I think #211 still ought to be fixed.

Will close this for now.

-[Unknown]
