### ISSUE TITLE
GL: Hatsune Miku Project Diva F Blue Tint

### ISSUE THREAD

**Issue by Nezarn** [RPCS3/rpcs3#2102]
log+shaders: https://www.dropbox.com/s/g6xboqfftfupla1/rpcs3_pdf_blue.zip?dl=0

After #2100 
http://i.imgur.com/CnPRYHI.png

Before we had new decompiler (so in theory the same ogl renderer as we have now, screenshot is from 860926d)
http://i.imgur.com/4cCPIx0.png

**Comment by raven02** [comment]
Same issue as Outrun Arcade

**Comment by raven02** [comment]
Will pull a fix shortly

![untitled](https://cloud.githubusercontent.com/assets/3000282/18013527/014061fe-6bf1-11e6-860e-ce333e2ed5e7.jpg)
