### ISSUE TITLE
DX12/GL/Vulkan: Project Diva F 2nd black background in main menu

### ISSUE THREAD

**Issue by Nezarn** [RPCS3/rpcs3#2104]
Caused by #2100 

With #2100:
http://i.imgur.com/aoMDCqR.png
http://i.imgur.com/L2e6pdF.png

Without:
http://i.imgur.com/oMRy2yR.png
http://i.imgur.com/8xLK9Ps.png

log+shaders: https://www.dropbox.com/s/jhrifcnj09z6o3l/rpcs3_pdf2_black.zip?dl=0

**Comment by raven02** [comment]
same issue as The Awakened Fate: Ultimatum that missing background

**Comment by raven02** [comment]
Probably you can checkout old version that with common recompiler has this background .If no , then may be new features added to the new decompiler .

**Comment by Nezarn** [comment]
@raven02 yep its black on old versions too (before the new decompiler got merged, also its similiar on DX12 too, but there its not completely black, just dark and blurry (it was always like this with DX12), DX12 screenshots: http://i.imgur.com/MRZDfOn.png http://i.imgur.com/3hqciOl.png )

**Comment by raven02** [comment]
Not too sure if it is smilar issue as Outrun . GL and Vulkan is bit darker when compared with DX12.

**Comment by raven02** [comment]
The background got rendered but very dark so we didn't see it.

**Comment by Nezarn** [comment]
Looks like its a shader issue(?):
OGL renderdoc:https://www.dropbox.com/s/o63izmzmiqpy8wa/pdf2ogl.zip?dl=0
shader:https://www.dropbox.com/s/td8wsfqyisvo0gd/shaderlogogl.zip?dl=0
![renderdocui_2016-09-30_22-58-35](https://cloud.githubusercontent.com/assets/3817985/19006746/79b0cad0-8761-11e6-8dba-1b0ec54ecd5f.png)

Vulkan renderdoc: https://www.dropbox.com/s/v81u6y23v4usypp/pdf2vulkan.zip?dl=0
shader: https://www.dropbox.com/s/xirwr4ggebafu2p/shaderlogvulkan.zip?dl=0
This looks weird in renderdoc lol (also don't mind the AMD bug):
![renderdocui_2016-09-30_23-07-43](https://cloud.githubusercontent.com/assets/3817985/19006987/bf653556-8762-11e6-8a0b-b59705ab6294.png)

**Comment by Waelwindows** [comment]
What the game is attempting to do is the emissive glow, this effect also happens in pdf but it isn't as noticeable. it's weird why it's failing in pdf2nd

**Comment by AniLeo** [comment]
![image](https://cloud.githubusercontent.com/assets/10283761/25307838/4eded2fe-27a0-11e7-8de5-87cea8ccce71.png)

![image](https://cloud.githubusercontent.com/assets/10283761/25307841/68d047ec-27a0-11e7-90de-ced98d78ffb6.png)

In the meantime, this was fixed, displays correctly on latest master.
