### ISSUE TITLE
Question about header file's license

### ISSUE THREAD

**Issue by d3m3vilurr** [RPCS3/rpcs3#2106]
I hope to merge https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/PSP2/Modules/sceVideodec.h file to  [vita-header](https://github.com/vitasdk/vita-headers) project.

RPCS3 project use GPLv2 and vita-headers not use GPL (they headers applied MIT or MPL)
So, can allow headers in PSP2/Modules to change license to MIT or MPL?

afaik, in many cases, just header files [not make derivative result](http://elinux.org/Legal_Issues#Use_of_kernel_header_files_in_user-space).
but I'm not lawyer, so I need confirmation before make new patch for vita-headers.

**Comment by Nekotekina** [comment]
I think RPCS3 headers are not very useful for vitasdk. They are too different, emulation-oriented, C++ only and very incomplete. Some structs were added rather for experimental purpose. Trying different source of information must be easier.

**Comment by d3m3vilurr** [comment]
in this case, specially `sceVideodec.h`
structures of this file are compatible on actual psvita;
https://github.com/xyzz/vita-moonlight/blob/vita/src/video/vita.c#L46-L137

anyway if headers can use for vitasdk, they can select part of file for use or not. i think problem is just license...

**Comment by AniLeo** [comment]
You can add the file along with its license (as the licenses are different, I believe you have to add a copy of the GPLv2 license along the header you want to include).

GPLv2 states that:

> But if you release the modified version to the public in some way, the GPL requires you to make the modified source code available to the program's users, under the GPL.
Thus, the GPL gives permission to release the modified program in certain ways, and not in other ways; but the decision of whether to release it is up to you."

See here: https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#GPLRequireSourcePostedPublic

I'm not any lawyer, but I believe you can use the header without any problems as long as a copy of GPLv2 is available somewhere (and again, as referred above, the source code is public).

**Comment by raven02** [comment]
Comment and advice have been given. Closed

**Comment by joshdekock** [comment]
I just want to reiterate, that It would be really useful if we could use those structs under a more permissive license (BSD/MIT/etc). The issue is that when the struct gets included in a file, the binary becomes a derivative work and must also follow the GPL license (this is undesirable for some, and we'd rather not restrict developers to open-source only).

**Comment by d3m3vilurr** [comment]
@Nekotekina @raven02 can you reopen this issue?
IMO, @AniLeo answer is wrong point :\

**Comment by joshdekock** [comment]
Note that only @Nekotekina can license that file (since they're the contributor). So it'd be nice if we could get a clear cut, "yes you may have that file under mit/bsd/etc", or "no that file is under gpl/whatever".

**Comment by d3m3vilurr** [comment]
@Nekotekina any update?

**Comment by enoposix** [comment]
@Nekotekina this file really would be useful for us.

**Comment by Nekotekina** [comment]
Ok, I'll do something. Sorry for the long waiting. Is only sceVideodec.h required? Maybe I could commit it to the vitasdk, because changing the license seems troublesome (however I'm not against it).

**Comment by devnoname120** [comment]
I think that a lot of files and headers are useful for the Vitasdk. I think that you can just give us the authorization to modify and relicense your work in https://github.com/RPCS3/rpcs3/tree/master/rpcs3/Emu/PSP2/Modules, and then we will be able to use and adapt headers as we need them.

**Comment by enoposix** [comment]
I also agree, most of it would be very useful. @Nekotekina The only thing you need to do is to state something like 'The files under `Emu/PSP2/Modules` are free to be relicensed as you wish/under a compatible license'. (note: IANAL, but it should be ok)

**Comment by Nekotekina** [comment]
Current progress: #2231

**Comment by scribam** [comment]
@d3m3vilurr Do you need anything else to fulfill your request?

**Comment by d3m3vilurr** [comment]
@scribam vitasdk/vita-headers#91 is a similar issue. and @devnoname120 already asked about relicense other headers :)
