### ISSUE TITLE
RPCS3 v0.0.1-5-7f3cb4d : Tales of Berseria black screen on booting

### ISSUE THREAD

**Issue by amakuramio** [RPCS3/rpcs3#2107]
Tales of Berseria installs, then shows fluctuating FPS on first install, with a black screen
On subsequent boots nothing happens.

https://postimg.org/image/95onm4k95/         < install data
https://postimg.org/image/t1fbvu6x5/            < second boot, 0 fps, black screen

error log: 
`RPCS3 v0.0.1-5-7f3cb4d Pre-Alpha
E LDR: Failed to boot /dev_hdd0/game/BLJS10330_INSTALL
E LDR: Unknown function '0x56D3A5AB' in module 'sceNpTus' (index 2974)
U {PPU[0x70000000] Thread (main_thread) [0x015116f8]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x70000000] Thread (main_thread) [0x015117d8]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x70000000] Thread (main_thread) [0x01511db8]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
E {PPU[0x70000000] Thread (main_thread) [0x01511db8]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x70000000] Thread (main_thread) [0x01511db8]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x70000000] Thread (main_thread) [0x01511db8]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x70000000] Thread (main_thread) [0x01511db8]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x70000000] Thread (main_thread) [0x01511db8]} sys_spu: Unsupported SPU Thread options (0x2)
U {PPU[0x70000000] Thread (main_thread) [0x015119d8]} cellRtc TODO: cellRtcGetCurrentTick(pTick=*0xd001e3c0)
U {PPU[0x70000000] Thread (main_thread) [0x01511a18]} cellRtc TODO: cellRtcConvertUtcToLocalTime(pUtc=*0xd001e3c0, pLocalTime=*0xd001e3c8)
E {rsx::thread} RSX: OpenGL: initialization of glDepthBoundsEXT failed.
U {PPU[0x70000000] Thread (main_thread) [0x01511f58]} cellSpurs TODO: _cellSpursLFQueueInitialize(pTasksetOrSpurs=*0x1ad7481, pQueue=*0x20201a00, buffer=*0x20201a80, size=0x20, depth=0xa, direction=3)
U {PPU[0x70000000] Thread (main_thread) [0x01511f78]} cellSpurs TODO: cellSpursLFQueueAttachLv2EventQueue
U {PPU[0x70000000] Thread (main_thread) [0x01512658]} cellSpurs TODO: _cellSpursQueueInitialize
U {PPU[0x70000000] Thread (main_thread) [0x015127b8]} cellSpurs TODO: cellSpursQueueAttachLv2EventQueue
U {PPU[0x70000000] Thread (main_thread) [0x015127f8]} cellSpurs TODO: cellSpursTaskGetContextSaveAreaSize
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512658]} cellSpurs TODO: _cellSpursQueueInitialize
U {PPU[0x70000000] Thread (main_thread) [0x015127b8]} cellSpurs TODO: cellSpursQueueAttachLv2EventQueue
U {PPU[0x70000000] Thread (main_thread) [0x015127f8]} cellSpurs TODO: cellSpursTaskGetContextSaveAreaSize
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512658]} cellSpurs TODO: _cellSpursQueueInitialize
U {PPU[0x70000000] Thread (main_thread) [0x015127b8]} cellSpurs TODO: cellSpursQueueAttachLv2EventQueue
U {PPU[0x70000000] Thread (main_thread) [0x015127f8]} cellSpurs TODO: cellSpursTaskGetContextSaveAreaSize
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
U {PPU[0x70000000] Thread (main_thread) [0x01512018]} cellSpurs TODO: cellSpursCreateTask2
E {PPU[0x70000000] Thread (main_thread) [0x015129f8]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (9)
E {PPU[0x70000000] Thread (main_thread) [0x01512a78]} sys_fs: sys_fs_opendir(“/dev_bdvd/PS3_GAME/USRDIR/GAMEDATA/PATCH”): failed to open directory
E {PPU[0x70000000] Thread (main_thread) [0x01512a78]} 'cellFsOpendir' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x70000000] Thread (main_thread) [0x00917950]} sys_fs: sys_fs_open(“/dev_hdd0/game/BLJS10330_INSTALL/USRDIR/GAMEDATA/BASE/CHUNK0/GENERAL/COMMON/FILEDATABASE.TLFDBX”): failed to open file (flags=0, mode=0)
E {PPU[0x70000000] Thread (main_thread) [0x00917950]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x70000000] Thread (main_thread) [0x00917950]} sys_fs: sys_fs_open(“/dev_hdd0/game/BLJS10330_INSTALL/USRDIR/GAMEDATA/BASE/CHUNK0/GENERAL/LOCALIZE/JPN/FILEDATABASE.TLFDBX”): failed to open file (flags=0, mode=0)
E {PPU[0x70000000] Thread (main_thread) [0x00917950]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x70000000] Thread (main_thread) [0x00917950]} sys_fs: sys_fs_open(“/dev_hdd0/game/BLJS10330_INSTALL/USRDIR/GAMEDATA/BASE/CHUNK0/SOUND/COMMON/FILEDATABASE.TLFDBX”): failed to open file (flags=0, mode=0)
E {PPU[0x70000000] Thread (main_thread) [0x00917950]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x70000000] Thread (main_thread) [0x00917950]} sys_fs: sys_fs_open(“/dev_hdd0/game/BLJS10330_INSTALL/USRDIR/GAMEDATA/BASE/CHUNK0/SOUND/LOCALIZE/JPN/FILEDATABASE.TLFDBX”): failed to open file (flags=0, mode=0)
E {PPU[0x70000000] Thread (main_thread) [0x00917950]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x70000000] Thread (main_thread) [0x01512a78]} sys_fs: sys_fs_opendir(“/dev_hdd0/game/BLJS10330_INSTALL/USRDIR/GAMEDATA/PATCH”): failed to open directory
E {PPU[0x70000000] Thread (main_thread) [0x01512a78]} 'cellFsOpendir' failed with 0x80010006 : CELL_ENOENT
U {PPU[0x70000005] Thread (TL_ExtractThread) [0x01511fb8]} cellSpurs TODO: _cellSpursLFQueuePushBody
U {PPU[0x70000005] Thread (TL_ExtractThread) [0x01511fb8]} cellSpurs TODO: _cellSpursLFQueuePushBody
`

**Comment by raven02** [comment]
Please discuss it in http://www.emunewz.net/forum/forumdisplay.php?fid=162
