### ISSUE TITLE
Virtual methods in memory access and instruction decode

### ISSUE THREAD

**Issue by unknownbrackets** [RPCS3/rpcs3#211]
C++ is a great language and has many powerful features.  However, some of them should not imho be misused within tight code.

PPSSPP does all instruction encoding in a fairly tight loop, and it can be fairly fast.  It spends about 25% of its time in the interpreter decoding instructions, compared to about 50% in rpcs3.

Memory access of course is similarly bad, but has other solutions, like directly mapping into address space.

Is speed a goal in rpcs3 (I would think it'd have to be to ever make ps3 emulation bareable), or is using strong class design patterns a higher goal?

-[Unknown]

**Comment by Nekotekina** [comment]
Fixed, no more virtual methods for memory access.
