### ISSUE TITLE
SSE3 CPU Error compiling

### ISSUE THREAD

**Issue by juanmahl15** [RPCS3/rpcs3#2111]
<img src="http://i68.tinypic.com/zwdes9.png" alt="Error" style="width:304px;height:228px;">
My cpu G3258 supports SSE3/4 and 4.1. I have vcredist and direct x installed. I have this error with LLVM and all the games.

**Comment by Q3CPMA** [comment]
SSSE3, not SSE3.

**Comment by Nezarn** [comment]
@Q3CPMA he just made a typo, SSSE3 is supported on G3258 (since its haswell based)

https://en.wikipedia.org/wiki/List_of_Intel_Pentium_microprocessors#.22Haswell-DT.22_.2822_nm.29

**Comment by AniLeo** [comment]
That's because you're using the LLVM Recompiler. Don't. Use the interpreters.

**Comment by Nekotekina** [comment]
It's absolutely useless information what your CPU is and what extension it supports.
