### ISSUE TITLE
[Regression]F {PPU[0x70000002] Thread (FS AIO Thread)} struct vm::access_violation thrown: Access violation writing address 0x0 

### ISSUE THREAD

**Issue by emmauss** [RPCS3/rpcs3#2113]
tried out disgaea 3 after a long time of not playing it, and it no longer goes beyond the now loading screen.the same error with disgaea 4.
log = http://pastebin.com/UnZKXwL4

LLE
 - libdmux.prx
    - libdmuxpamf.prx
    - libfiber.prx
    - libl10n.prx
    - libresc.prx
    - librtc.prx
    - libsre.prx

last build among the one i downloaded long ago that works was 5d6aecc5 from 16/07/16. i dont know which build started the regression

**Comment by Nezarn** [comment]
@emmauss have you tried LLE libfs ? (since some stuff was removed because they were a buggy mess?)

**Comment by emmauss** [comment]
@Nezarn  i tried libfs, but it is spamming a lot of todos and no image shows at all. same thing with libadec and libatxdec. with libfs disabled, it now works with libadec and libatxdec. thanks.

**Comment by raven02** [comment]
Please discuss this in http://www.emunewz.net/forum/forumdisplay.php?fid=162
