### ISSUE TITLE
Psx3 Game not Working

### ISSUE THREAD

**Issue by CyberPhy** [RPCS3/rpcs3#2114]
I don't know why it's doing this but this is what I get when starting a game

E {PPU[0x70000000] Thread (main_thread) [0x007ff04c]} sys_fs: sys_fs_open(“/dev_hdd0/game/BLES02152_INSTALL/USRDIR/ENG\FILEDATABASE.TLFDBX”): failed to open file (flags=0, mode=0)
E {PPU[0x70000000] Thread (main_thread) [0x007ff04c]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT

**Comment by CyberPhy** [comment]
How Do I Fix this?

**Comment by GhettoGirl** [comment]
please discuss such things in the [forum](http://www.emunewz.net/forum/forumdisplay.php?fid=162)
also take a look at this thread in the forum: [170805](http://www.emunewz.net/forum/showthread.php?tid=170805)

**Comment by CyberPhy** [comment]
Thanks For the help I will go there :)
