### ISSUE TITLE
RSX: Invalid RSX method 0xad00 (arg=0x0)

### ISSUE THREAD

**Issue by lightsteam** [RPCS3/rpcs3#2115]
Title : 3D Dot Game Heroes

F {rsx::thread} class std::runtime_error thrown: Invalid RSX method 0xad00 (arg=0x0)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:34)

**Comment by lightsteam** [comment]
Sorry for typing it wrong

**Comment by MoochMcGee** [comment]
Try it with this PR: https://github.com/RPCS3/rpcs3/pull/2179

**Comment by sirdanielk** [comment]
Another two games with this error 
Scogger F {rsx::thread} class std::runtime_error thrown: Invalid RSX method 0x2c8 (arg=0x4ff0000)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:34)
And Metal gear solid 4
W {PPU[0x70000019] Thread (DLPFS DIR INIT) [0x00323860]} sys_ppu_thread: _sys_ppu_thread_exit(errorcode=0x0)
W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 1
W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 1
F {rsx::thread} class std::runtime_error thrown: Invalid RSX method 0x1484 (arg=0x0)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:34)
Lets Help MGS4 Go on!!!

**Comment by kd-11** [comment]
This issue is usually caused memory corruption. A tracker exists here https://github.com/RPCS3/rpcs3/issues/2359
