### ISSUE TITLE
J-Stars Victory VS+ stuck at title screen

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2119]
All backends stuck at title screen after load savegame data.

GL 
![untitled](https://cloud.githubusercontent.com/assets/3000282/24834710/f68ddecc-1d1f-11e7-8ad7-244a27f8eded.jpg)

DX12
![dx12](https://cloud.githubusercontent.com/assets/3000282/18229183/30a889ba-72a1-11e6-9b01-0be2933c2aea.jpg)

Vulkan
![vk](https://cloud.githubusercontent.com/assets/3000282/18229182/253da22c-72a1-11e6-97ba-85abc00b652b.jpg)

**Comment by raven02** [comment]
GL missing logo issue fixed in master build .

**Comment by AniLeo** [comment]
This doesn't seem like a graphical issue

**Comment by iyenal** [comment]
Can the intro freeze be fixed please ?
No 3D model can be rendered yet in this game.

**Comment by AniLeo** [comment]
We know that, it's been like that for a long time, it softlocks after pressing start game, feel free to look into it to find what's the issue, I don't think anyone looked into it enough to find out yet.

**Comment by iyenal** [comment]
I don't know very much how works the emulator debugger to look the issue, but I will try.

**Comment by AniLeo** [comment]
I'm closing this one since this is a simple game report, which is done over the forums and not here as per the guidelines.

There's no useful information in this issue at all for us, this needs further debugging and information on what's causing the hang to be useful from a technical standpoint.
