### ISSUE TITLE
gcm_enums.cpp optimization

### ISSUE THREAD

**Issue by Nekotekina** [RPCS3/rpcs3#2123]
I'm not going to do it right now so I open this for a discussion.

In my opinion, gcm_enums.cpp conversion functions should ideally not exist at all. As I remember, their implementation was poorly motivated by the idea of avoiding unscoped enums with GCM constants in favor of C++11 scoped enums. I suggest the following compromise:

``` C++
namespace rsx
{
    enum class vertex_base_type : u32
    {
        s1    = 1, //! Signed byte
        f     = 2, //! Float
        sf    = 3, //! Half float
        ub    = 4, //! Unsigned byte interpreted as 0.f and 1.f
        s32k  = 5, //! Signed 32bits int
        cmp   = 6, //! Compressed aka X11G11Z10 and always 1. W.
        ub256 = 7, //! Unsigned byte interpreted as between 0 and 255.
    };

//..............
        rsx::vertex_base_type type() const
        {
            return static_cast<rsx::vertex_base_type>(m_data.type); // Usage
        }
}
```

Another problem is the selection of u8 type for enum base type. I could just ignore this, but 8 and 16-bit types must be generally avoided in favor of 32 bit types, if it doesn't come to describing exact data representation.

Third problem is defining GCM constants. I think they should be mentioned in comments to enum class sub values, when they don't have to be defined as separate enums.

**Comment by Nekotekina** [comment]
#2116.
@vlj @raven02 @kd-11

**Comment by kd-11** [comment]
I'm all for simplifying the code personally, although some backend specific functions would have to perform error checking themselves instead of relying on conversion to catch undefined/unexpected values.

**Comment by SakataGintokiYT** [comment]
@vlj

**Comment by scribam** [comment]
Is there something to do for this issue? It seems parts of Nekotekina's proposal are in master:

https://github.com/RPCS3/rpcs3/blob/ed21bb309f65eaa3bd072c3fe0ac656b3d544c83/rpcs3/Emu/RSX/gcm_enums.h#L6-L15

https://github.com/RPCS3/rpcs3/blob/ed21bb309f65eaa3bd072c3fe0ac656b3d544c83/rpcs3/Emu/RSX/rsx_decode.h#L4452-L4455

**Comment by kd-11** [comment]
The proposal was to make the enums match the CELL_GCM_* constants or native value from the FIFO queue which they do not do so its still an issue. It should not change the code outside of gcm_enums.cpp and gcm_enums.h though.
Neko's suggestion is that there should be no such method as `rsx::to_vertex_base_type`, rather `(rsx::vertex_base_type)value` should give the same result as `rsx::to_vertex_base_type(value)`. Currently the value is passed through a switch block and enums returned that are logically unrelated to the original input.

**Comment by dio-gh** [comment]
Still seems to be an issue.
