### ISSUE TITLE
DX12: Digimon AllStar Rumble unable to reach in-game

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2126]
DX12
No beating black frames appear screenshot purple word after loading the game
![qq 20160905132214](https://cloud.githubusercontent.com/assets/20301499/18238215/4ea37764-736d-11e6-8cdb-d56849c25ac4.png)
vullkan
![qq 20160905132254](https://cloud.githubusercontent.com/assets/20301499/18238219/5e8509a4-736d-11e6-902c-3b6bf1b6e575.png)
video
https://youtu.be/e7thRhBnsvE
OpenGL
![qq 20160905132329](https://cloud.githubusercontent.com/assets/20301499/18238228/78ff29ae-736d-11e6-9576-936c6665a104.png)
log：https://drive.google.com/file/d/0B4z-S0oOZ2FgamQzX21vcEc0WUU/view?usp=sharing

**Comment by raven02** [comment]
Do you mean DX12 not able to reach title screen ?

**Comment by RainKikyou** [comment]
@raven02 载入游戏后黑屏无帧数跳动出现图里的紫字

**Comment by raven02** [comment]
Thanks (BTW , please keep it in english if possible)

**Comment by raven02** [comment]
Looks like this check only exists for DX12 backend but not GL and Vulkan . @vlj , do we need to do this check ?

verify(HERE), rsx::method_registers.vertex_data_base_index() == 0;

**Comment by raven02** [comment]
Looks like 2nd attempt to boot up the game failed unless remove the BLUS31441_GAMEDATA
