### ISSUE TITLE
Project Diva F Read movie folder playback speed is too slow

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2130]
lle Load Settings
![qq 20160910161049](https://cloud.githubusercontent.com/assets/20301499/18409410/ecdce438-7778-11e6-9c70-e803a438968b.png)
Reading effect
![qq 20160910161414](https://cloud.githubusercontent.com/assets/20301499/18409416/00554bae-7779-11e6-8ab2-e36de1d40840.jpg)
![qq 20160910163659](https://cloud.githubusercontent.com/assets/20301499/18409417/0c02820a-7779-11e6-8246-7ece5aff6d7d.png)
Loading LLE: None OP but normal background movie characters within the game is also normal
Temporary anchorage and wave pattern of the original model because there is no reason to read the movie folder
Although able to read movie folder, but there are problems still can not read the creative part 2d, and video playback speed issue does not affect the number of frames
![qq 20160910163850](https://cloud.githubusercontent.com/assets/20301499/18409435/6cc496aa-7779-11e6-94e6-f57011cf7419.png)
Playback speed is too slow, resulting in creative time to play not finished
ogl slowest
![qq 20160910171300](https://cloud.githubusercontent.com/assets/20301499/18409448/e7813614-7779-11e6-8d17-8ccbefa5ae44.jpg)

![qq 20160910164651](https://cloud.githubusercontent.com/assets/20301499/18409438/89468c3e-7779-11e6-8d5c-583a1e1e3c39.png)
video：https://youtu.be/BCMdodwHGeU

**Comment by Nekotekina** [comment]
Recommended library list:
    - libadec.sprx
    - libatxdec.sprx
    - libdmux.sprx
    - libdmuxpamf.sprx
    - libpamf.sprx
    - libresc.sprx
    - librtc.sprx
    - libsre.sprx

libvdec is slow.

**Comment by RainKikyou** [comment]
@Nekotekina Thanks, playback speed have been resolved but some still can not read the material 2d

**Comment by raven02** [comment]
Playback speed resolved and closed
