### ISSUE TITLE
DX12: SoulCalibur II HD Online

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2131]
In https://github.com/RPCS3/rpcs3/commit/b4e3d3dbfdbfacdbbeadf447ebe8f8ebc8b45f32, it outpus in DX12:

```
{rsx::thread} class std::runtime_error thrown: HRESULT = La instancia de dispositivo de GPU se ha suspendido. Use GetDeviceRemovedReason para averiguar cuál es la acción adecuada.
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12MemoryHelpers.h:39)
```

Translated: 
The device instance GPU has been suspended. Use GetDeviceRemovedReason to find out what appropriate action is.
![](http://i.imgur.com/utBMNZT.jpg)
It sometimes stops in this screen.

**Comment by Nekotekina** [comment]
Thanks, will add printing actual HRESULT error codes in TODO list. And enforce English, maybe. Regarding the game itself, I don't care, sorry.

**Comment by MarioSonic2987** [comment]
In DX12, Midnight Club: Los Angeles [NPUB30471] also hits that error. Tested in https://github.com/RPCS3/rpcs3/commit/8454949eea9d0fc9da55b719e9a02f5a022fd5f5.
