### ISSUE TITLE
Linux: dev_flash location

### ISSUE THREAD

**Issue by Enverex** [RPCS3/rpcs3#2132]
A commit a long time ago created the dev_flash data/font folders for Windows setups (https://github.com/RPCS3/rpcs3/pull/296), but these appear to be missing on the Linux side. ~/.config/rpcs3 is created, but no folder relating to dev_flash is created at any point.

Probably also worth adding to the documentation where dev_flash should actually exist on Linux systems.

**Comment by Nekotekina** [comment]
TODO list:
1) Delete fs::get_executable_dir
2) Create dev_flash/dev_hdd0/... automatically in config folder

**Comment by hcorion** [comment]
Can this bug be closed? dev_flash seems to now be auto creating itself.
