### ISSUE TITLE
Jojo All Star Battle Freeze (Not Playable)

### ISSUE THREAD

**Issue by MarbySpnol** [RPCS3/rpcs3#2133]
The game freeze every time in cinematics and load screens every time, it doesn´t give error, just freeze http://prntscr.com/cgwarc

**Comment by raven02** [comment]
Updated in the https://github.com/RPCS3/rpcs3/issues/1725

**Comment by Some1kl** [comment]
wich lle's did you use on it?

**Comment by Some1kl** [comment]
@MarbySpnol

**Comment by MarbySpnol** [comment]
CellAtrac_Library v1.1
libsmvd2_Library v1.1
CellSre_Library v1.1
CellSpursJq_Library v1.1

**Comment by kjmn1999** [comment]
So has anyone found a fix to this issue yet?
I'm not really good at analyzing the problems myself based on Raven02's comment.
If someone could tell me how the freezing issue (it only happens after I select a stage) could be fixed that would really help me.
Thank you

**Comment by namelyz** [comment]
Hi, this has happened to me too, I really want to play this game but it crashes everytime I try and load a level. I am aware this was supposedly fixed in a RPCS update but it seems not to have affected me, is there some way I can force an update or what should I do? Thanks
