### ISSUE TITLE
Error linking to libdl

### ISSUE THREAD

**Issue by John-Gee** [RPCS3/rpcs3#2151]
cmake options:
    -DUSE_SYSand TEM_FFMPEG='On' \
    -DUSE_SYSTEM_LIBPNG='On' \
    -DCMAKE_BUILD_TYPE='Release' \
    -DCMAKE_INSTALL_PREFIX='/usr' \
    -DCMAKE_SKIP_RPATH='TRUE' \
    -DCMAKE_CXX_FLAGS='-fno-pie -fno-lto'

standard make.
gcc-multilib 6.2.1
glibc 2.24

This leads eventually to:
/usr/bin/ld: CMakeFiles/rpcs3.dir/__/Utilities/dynamic_library.cpp.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/libdl.so.2: error adding symbols: DSO missing from command line

Adding -ldl in rpcs3/rpcs3/CMakeLists.txt in the if (USE_SYSTEM_FFMPEG)  target_link_librairies works.
As it is in the else, it feels like it was forgotten in the other one, but I don't think this is the proper place for the flag. Moving both to the above target_link_librairies seem a better place.

Thank you!

**Comment by Enverex** [comment]
Still an issue.

```
[100%] Linking CXX executable ../bin/rpcs3
/usr/bin/ld: CMakeFiles/rpcs3.dir/__/Utilities/dynamic_library.cpp.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by Nezarn** [comment]
@Enverex which linux distro? I've tested ubuntu, fedora and arch and they work fine.

**Comment by Enverex** [comment]
Arch Linux. GCC 6.2.1 20160830, Kernel 4.8.11, FFMPEG 3.2-1, GLibC 2.24-2.

**Comment by Nezarn** [comment]
@Enverex or you can just use clang (since clang doesn't have this issue)

**Comment by John-Gee** [comment]
What's wrong with fixing the CMake file?

I'm also on Arch Linux by the way.

**Comment by magiruuvelvet** [comment]
a fix has been commited regarding the libdl issue. i think we can close this

**Comment by juliusv2018** [comment]
I have a problem with libdl.
I used Eclipse IDE in Ubuntu, and I added -libdl option to linker setting. However, there occurs another problems that the program cannot use json library in /usr/include/json and /usr/include/jsonrcpcpp.
