### ISSUE TITLE
DX12/Vulkan : user clip planes unimplemented

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2152]
Vulkan
![vk](https://cloud.githubusercontent.com/assets/3000282/18807893/d6fd1396-8285-11e6-8fa2-98a5ad3cd88b.jpg)

GL
![gl](https://cloud.githubusercontent.com/assets/3000282/18807898/df5b34c8-8285-11e6-8005-0e63e91bbfa9.jpg)

DX12
![dx12](https://cloud.githubusercontent.com/assets/3000282/18807895/dbc97432-8285-11e6-958f-1d52214f342a.jpg)

**Comment by raven02** [comment]
DX12 is not yet implemetned while Vulkan and GL seems to be clipped in different direction . I may be wrong.

**Comment by raven02** [comment]
GL one should be the correct one . Looks like Vulkan reversed the greather_or_equal and less than op.

**Comment by SakataGintokiYT** [comment]
@kd-11 
Issue is fixed on OpenGL #2278 

Can you implemented user clip in DX12/VK ?

**Comment by kd-11** [comment]
I'll look into it this weekend.
