### ISSUE TITLE
sys_fs_fcntl(): Unknown operation 0xc0000006

### ISSUE THREAD

**Issue by fenix008** [RPCS3/rpcs3#2154]
And might I understood why it's loading too long between levels or between anything...
Quote:
·U {PPU[0x70000013] Thread (thr_bootcheck) [0x010f8ec0]} sys_fs TODO: sys_fs_fcntl(): Unknown operation 0xc0000006 (fd=4294967295, arg=_0xd00a78c8, size=0x20)
·W {PPU[0x70000013] Thread (thr_bootcheck) [0x010fa090]} sys_fs: sys_fs_open(path=“/dev_hdd0/game/NPEB00913/USRDIR/chkboot.edat”, flags=0, fd=_0xd00a7970, mode=0, arg=*0xd00a7ac8, size=0x8)
I think "sys_fs_fcntl" somehow responsible for loading file, and files can't loading "on fly" because this function is not implemented yet.
Maybe I'm not right, but it's my opinion.

From this thread: http://www.emunewz.net/forum/showthread.php?tid=158744&pid=233341#pid233341

**Comment by fenix008** [comment]
solved ?

**Comment by AniLeo** [comment]
Yes
