### ISSUE TITLE
`clockid_t` conflict on macOS

### ISSUE THREAD

**Issue by liyishuai** [RPCS3/rpcs3#2157]
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/Cell/lv2/sys_time.cpp#L52

```
<repo>/rpcs3/Emu/Cell/lv2/sys_time.cpp:52:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')
typedef int clockid_t;
            ^
/usr/include/time.h:171:3: note: previous definition is here
} clockid_t;
  ^
```

**Comment by thedevleon** [comment]
Getting the same error. Is there a workaround?

**Comment by kd-11** [comment]
you could just wrap the def with a
```
#ifndef _SYS_TYPES_H
typedef int clockid_t;
#endif
```
to define clockid_t when it is not defined externally.
But then again it may just raise another error down the road anyway
