### ISSUE TITLE
GL: Dai-3-Ji Super Robot Taisen Z Jigoku-hen logo effect 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2159]
DX12 and Vulkan render both correct the logo effect but not GL 

![untitled](https://cloud.githubusercontent.com/assets/3000282/18826622/f2d92560-8400-11e6-81fe-17c9ff1f0035.jpg)

**Comment by raven02** [comment]
This is from DX12 where the fire effect inside in the Z logo.

![untitled](https://cloud.githubusercontent.com/assets/3000282/18826691/4f5f60e2-8401-11e6-9cf9-38d1aff603ac.jpg)

**Comment by kd-11** [comment]
You're right. Even on vulkan it is only visible within the logo; the flames should not extend outside.

**Comment by raven02** [comment]
GL renders wrong on the map selection . DX12 and Vulkan are both good.
![untitled](https://cloud.githubusercontent.com/assets/3000282/23340135/ff1fbab2-fc6b-11e6-8e44-77cd07bb200f.jpg)

**Comment by raven02** [comment]
Map selection fixed in latest build.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/2582

**Comment by raven02** [comment]
Thanks @kd-11

**Comment by kd-11** [comment]
Fixed
