### ISSUE TITLE
Regression : 1942 Joint Strike corrupt main menu

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2160]
This is GL specific . 

Regressed at the porting of user clip plane implementation https://github.com/RPCS3/rpcs3/pull/2139

**Comment by kd-11** [comment]
That means the implementation is still missing something.

**Comment by raven02** [comment]
Interesting . It happen on the intel platform only but cannot reproduce on my Nvidia system

**Comment by kd-11** [comment]
I'll test on AMD.

**Comment by Nezarn** [comment]
looks fine here (if you're talking about this main menu)

![rpcs3_2016-09-26_14-52-13](https://cloud.githubusercontent.com/assets/3817985/18834905/db03c092-83f8-11e6-97d2-49e121e5b572.png)

**Comment by kd-11** [comment]
Looks okay to me as well

**Comment by raven02** [comment]
Then problem false alarm :). I'm closing it then
