### ISSUE TITLE
Vulkan: human gcm sample 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2162]
Both GL and DX12 render correct while Vulkan not.

GL/DX12
![gl](https://cloud.githubusercontent.com/assets/3000282/18838217/418eec2a-8439-11e6-8d68-4efac1e24d42.jpg)

Vulkan
![vk](https://cloud.githubusercontent.com/assets/3000282/18838226/47cfd63a-8439-11e6-865e-2b13fbf0c034.jpg)

**Comment by raven02** [comment]
[sample_data.zip](https://github.com/RPCS3/rpcs3/files/493313/sample_data.zip) - put in same level as rpcs3.exe

[human.ppu.zip](https://github.com/RPCS3/rpcs3/files/493315/human.ppu.zip)

**Comment by digitaldude555** [comment]
![screenshot 907](https://cloud.githubusercontent.com/assets/26138653/23633242/991e0a12-02cd-11e7-9769-1a52a79e71ff.png)

kd-11 new build seems to have fixed this issue. @raven02.
