### ISSUE TITLE
D3D12: stencil reflect gcm sample

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2164]
DX12
![dx12](https://cloud.githubusercontent.com/assets/3000282/18839153/8a7dc4d0-843c-11e6-8e6d-b9ea4a5500f3.jpg)

Vulkan
![vk](https://cloud.githubusercontent.com/assets/3000282/18839146/8883f208-843c-11e6-9efe-29ab509fc12f.jpg)

GL
![gl](https://cloud.githubusercontent.com/assets/3000282/18839142/84385df6-843c-11e6-8ac2-e0f52573c197.jpg)

**Comment by raven02** [comment]
[fw_stencil_reflect.ppu.zip](https://github.com/RPCS3/rpcs3/files/493353/fw_stencil_reflect.ppu.zip)

**Comment by AniLeo** [comment]
VK
![image](https://cloud.githubusercontent.com/assets/10283761/25307875/0efe6acc-27a1-11e7-9408-733bf077e579.png)

OGL
![image](https://cloud.githubusercontent.com/assets/10283761/25307879/1f759f7e-27a1-11e7-94fc-ba0e9a471ad6.png)

**Comment by raven02** [comment]
GL renders correct while DX12 and Vulkan are still wrong .

**Comment by AniLeo** [comment]
![image](https://user-images.githubusercontent.com/10283761/27240986-c647b5b4-52ce-11e7-9e08-9dd9c8bc99f6.png)

Vulkan is fixed
