### ISSUE TITLE
DX12/GL/Vulkan: environment mapping support

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2165]
![env](https://cloud.githubusercontent.com/assets/3000282/18839684/6b06a390-843e-11e6-9b33-f9aa509fa139.jpg)

GL/Vulkan/DX12

![env1](https://cloud.githubusercontent.com/assets/3000282/18839692/72f01a82-843e-11e6-8330-de1a98c7babb.jpg)

**Comment by raven02** [comment]
[gfxSample.zip](https://github.com/RPCS3/rpcs3/files/493390/gfxSample.zip)

**Comment by kd-11** [comment]
shader bugs it seems since the cubemap seems properly applied

**Comment by kd-11** [comment]
Two problems here:
1. The cube map is actually not even bound to the pipeline.
2. The shader is broken. This is an issue with the common fragment program decompiler.

issue 1 might be the driver optimizing away the cubemap. However, the shader code just makes no sense.

```
r0 = texture(tex1, tc0.xy * tex1_coord_scale);
r1 = texture(tex0, tc1.xyz);
r1 = (-r0 + r1);
r1 = texture(tex0, tc1.xyz);
r1 = (-r0 + r1);

ocol0 = r0
```

**Comment by raven02** [comment]
Probaby this is related to BEM instruction

**Comment by kd-11** [comment]
When running this, I only see this error:
```
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x40 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x58 (forced unit 0)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x6a (forced unit 0)
```

**Comment by kd-11** [comment]
There's some unimplemented RSX stuff that affects alot of games actually. BEM, UPG, src type 3, VTF texture index, etc

**Comment by kd-11** [comment]
@raven02 This is because of the TEXBEM instruction being badly implemented. I'll work on this together with the BEM instruction. Any sample that uses the bare BEM instruction? It usually prints an error.

**Comment by raven02** [comment]
I think it is Rayman 3 HD Trial which has the BEM instructions logged.

https://github.com/RPCS3/rpcs3/issues/2194

**Comment by kd-11** [comment]
actually samples are using texbem, it does not show an error, unless you look at the broken shader code. This particular sample for example uses it. I'll debug this soon.

**Comment by kd-11** [comment]
image_in fix fixes some of the issues in this report

**Comment by raven02** [comment]
Yep , it looks bit better
![untitled](https://cloud.githubusercontent.com/assets/3000282/23351905/1d65960c-fcff-11e6-9740-528ba1f2ac1f.jpg)

**Comment by jarveson** [comment]
Heres what it looks like w/ 2240
![untitled](https://cloud.githubusercontent.com/assets/536093/23393780/cea0540c-fd4a-11e6-960f-04ec63e9660b.png)
