### ISSUE TITLE
DX12/GL/Vulkan : reflect and refract support

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2166]
[gfxSample.zip](https://github.com/RPCS3/rpcs3/files/493529/gfxSample.zip)

![untitled](https://cloud.githubusercontent.com/assets/3000282/18841909/e2ab76c6-8445-11e6-9501-3129414bfd06.jpg)

**Comment by raven02** [comment]
GL/Vulkan/DX12 render the same as below.

![dx12](https://cloud.githubusercontent.com/assets/3000282/18841986/1d0286fc-8446-11e6-83a3-deda62ceb51d.jpg)

**Comment by kd-11** [comment]
I get an immediate exit. Which lle modules are required?

**Comment by raven02** [comment]
Try put this 
[sample_data.zip](https://github.com/RPCS3/rpcs3/files/500710/sample_data.zip)
 as same level as rpcs3

**Comment by MarioSonic2987** [comment]
By the picture, refract is working but reflect isn't.

**Comment by jarveson** [comment]
Updated picture with dx12
![untitled](https://cloud.githubusercontent.com/assets/536093/23088225/0b3beace-f540-11e6-91a5-11ef0b227ce3.png)

**Comment by jarveson** [comment]
Should be all set now
![untitled](https://cloud.githubusercontent.com/assets/536093/23393830/2483b7e2-fd4b-11e6-8025-8651dadf1b88.png)

**Comment by raven02** [comment]
Thanks @jarveson
