### ISSUE TITLE
GL/Vulkan : BitTrip Runner 2 in-game rendering issue

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2167]
DX12 should be the correct one to render the in-game scene.

DX12
![dx12](https://cloud.githubusercontent.com/assets/3000282/18855970/9d487568-8489-11e6-908b-746c6eaa6177.jpg)

GL
![gl](https://cloud.githubusercontent.com/assets/3000282/18855973/a0337e26-8489-11e6-92c9-31603e415fce.jpg)

Vulkan
![42835a9c-87ce-11e6-87be-48cfdae55876](https://cloud.githubusercontent.com/assets/3000282/19077183/249b3ce0-8a7e-11e6-993a-a6ec6db55fa0.jpg)

**Comment by kd-11** [comment]
looks like broken lighting. Check if its still an issue since the wpos fix was merged

**Comment by raven02** [comment]
Yes , Vulkan broken lighting issue fixed .

![untitled](https://cloud.githubusercontent.com/assets/3000282/19011606/42835a9c-87ce-11e6-87be-48cfdae55876.jpg)

**Comment by SakataGintokiYT** [comment]
@raven02 
**OpenGL**
<img src="http://www.fotoszok.pl/upload/3b481c21.jpg" alt="Fotoszok.pl" />

**Vulkan**
<img src="http://www.fotoszok.pl/upload/100f49b7.jpg" alt="Fotoszok.pl" />

**Comment by raven02** [comment]
Cool .Closing it then.

**Comment by AniLeo** [comment]
It's still broken, notice the excess of yellow in the second screenshot
