### ISSUE TITLE
Publish RPCS3 on the Xbox Store. (read full post)

### ISSUE THREAD

**Issue by XeClutch** [RPCS3/rpcs3#2168]
Yes, I know, title is wtf but just hear me out. Would it not be absolutely hilarious to get a PS3 emulator on the Xbox 360? Reason this came to mind is.. well.. just look: https://www.microsoft.com/en-us/store/p/win64e10/9nblggh4r9nw

Yes. An N64 emulator got published on the Microsoft store and has Xbox support. Similar case happened with a NES emulator "NESBox" however because the name had "NES" in it and the way it's ROM search engine functioned it was removed. Win64e10 gets to stay because you have to upload your "legally purchased backups" to OneDrive and link it to your Xbox account. From there you can play them on your Xbox One (provided you have the app installed on your console).

Even if this isn't to be taken as a serious consideration (porting the emu to Xbox One) it still would be a good laugh. Hope I don't get banned for posting this lel.

**Comment by Nezarn** [comment]
Not sure if you're a troll, or just plain stupid, even if rpcs3 would be ported to xbox, it would never run at good speeds, Xbone can't even emulate every N64 game at fullspeed.

What will be the next similiar issue? PLS PORT RPCS3 TO MY VACUUM CLEANER? Or to your fridge? Or port rpcs3 to your NES?

**Comment by bea452a** [comment]
I don't know you are not stupid or deliberately send this to arouse people's idea，If Microsoft know this thing，May cooperate with SONY，wii Upgrade the SOST hardware and system,That would make the emulator development team increased the difficulty.
双语对照

**Comment by raven02** [comment]
Closed
