### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Xetzar** [RPCS3/rpcs3#2176]
So I tried playing Disgaea 4, this showed up.
Checked "cellSysmodule_Library v1.1":
E start func found in 'cellSysmodule_Library' library (0x2adcb68)
E stop func found in 'cellSysmodule_Library' library (0x2add798)
E {PPU[0x1] Thread (main_thread)[0x02addd0c]} Unimplemented syscall 871: sys_ss_access_control_engine -> CELL_OK
E {PPU[0x1] Thread (main_thread)[0x02ae0710]} Exception: 
(in file Emu\SysCalls\Modules\sys_libc.cpp:358, in function _sys_sprintf)
E {PPU[0x14] Thread (Check game data thread)[0x02ae0710]} Exception: 
(in file Emu\SysCalls\Modules\sys_libc.cpp:358, in function _sys_sprintf)

Unchecked "cellSysmodule_Library v1.1":
E {PPU[0x1] Thread (main_thread)[0x0042a45c]} cellSysmodule: cellSysmoduleIsLoaded() failed: module not loaded (id=0x0000)
E {PPU[0x1] Thread (main_thread)[0x0042a45c]} cellSysmodule: cellSysmoduleIsLoaded() failed: module not loaded (id=0x0016)
E {PPU[0x1] Thread (main_thread)[0x0042b65c]} sceNp: sceNpManagerRegisterCallback
E {PPU[0x1] Thread (main_thread)[0x0042a3dc]} cellSysutil: cellSaveDataEnableOverlay(enable=1)
E {PPU[0x1] Thread (main_thread)[0x0042b75c]} sceNp: sceNpManagerGetNpId
E {PPU[0x1] Thread (main_thread)[0x0042b2fc]} sceNp: sceNpBasicRegisterContextSensitiveHandler
E {PPU[0x1] Thread (main_thread)[0x0042af9c]} cellPamf TODO: cellPamfReaderInitialize(): verification
E {PPU[0x1] Thread (main_thread)[0x0042acdc]} cellAdec TODO: *** CellAdecParamAtracX: sr=0, ch_cfg=0(2), frame_size=0x0, extra=0x0, output=132, downmix=0, ats_header=1
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002
E {Internal Audio Thread} alBufferData: OpenAL error 0xa002

What am I supposed to do?

**Comment by Nekotekina** [comment]
Nothing.

**Comment by Xetzar** [comment]
So I give up and just uninstall?

**Comment by Nezarn** [comment]
@Xetzar for stuff like this you go to the forum http://www.emunewz.net/forum/showthread.php?tid=172391 and also read this first http://www.emunewz.net/forum/showthread.php?tid=174352
