### ISSUE TITLE
Regression : Disgaea 3 grey color issue

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2178]
This affects all backends .Regressed at https://github.com/RPCS3/rpcs3/pull/2173

![1](https://cloud.githubusercontent.com/assets/3000282/19010882/d944059e-87ba-11e6-83d7-59e548a7c09b.jpg)
![untitled](https://cloud.githubusercontent.com/assets/3000282/19010881/d93d8e1c-87ba-11e6-9c97-94d5e562ec54.jpg)

**Comment by raven02** [comment]
case rsx::texture_dimension_extended::texture_dimension_2d:
			if (m_prog.redirected_textures & (1 << dst.tex_num))
				SetDst(getFunction(FUNCTION::FUNCTION_TEXTURE_SAMPLE2D_DEPTH_RGBA));
			else
				SetDst(getFunction(FUNCTION::FUNCTION_TEXTURE_SAMPLE2D));
			return true;

**Comment by kd-11** [comment]
Thats rather odd: the depth read does not alter color.r but only changes color.g and color.b to be tiny non-zero values (so that the combination yields back the original value). I'll need to analyze a trace of this, although I remember texture swizzle problems with this title.
Attach an opengl renderdoc trace and I'll take a look when I can.

**Comment by raven02** [comment]
Here it is 
[rpcs3_the_gate_paradox.zip](https://github.com/RPCS3/rpcs3/files/504863/rpcs3_the_gate_paradox.zip)

**Comment by kd-11** [comment]
Seems that an RGBA8 RTV is returned as being bound to the depth buffer which should not be possible. Either the game is just being crazy, or there's a bug in our rtt cache code. Redirection should only occur for native depth textures of D24_X8.

**Comment by ssshadowww** [comment]
This also happens in Atelier Ayesha (and other Atelier games).

renderdock trace: https://mega.nz/#!A5VzRJpB!gfrqI2jl7la_ccKJS4NEOsqpDNENLuk0GkAmqd-cebs 

Example:
![2016-10-03 21_16_10-fps_ 28 57 _ opengl _ atelier ayesha_ the alchemist of dusk _ bles01793](https://cloud.githubusercontent.com/assets/3323620/19050390/a9c22f3a-89ae-11e6-82e4-a3563c7f9ea5.png)

**Comment by kd-11** [comment]
Thanks. The bug is our rsx surface cache returning color textures as depth_stencil textures. This can easily be worked around for ogl, but vulkan and dx12 do not attach an internal format to image data, so I'll need to debug this with a sample that is affected to find the real cause.
I'll look through to see if any samples or games that I have are affected by this, since it should be an easy fix.

**Comment by kd-11** [comment]
@ssshadowww @raven02 Could you run with this build https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.303 and attach the rpcs3.log for opengl? It'll spam the log with alot of information, but it should help narrow down possible culprits.

**Comment by kd-11** [comment]
I've updated the link to the appveyor build since it failed to compile the first time

**Comment by ssshadowww** [comment]
Here is the log for Atelier Ayesha:
https://mega.nz/#!5g9lwLxR!vlnwdMLGFnONUCDQRHXxyv4wWy3AtrYb8K5xM3iXSVQ

**Comment by raven02** [comment]
Here is the log from debug build on Disgaea 3 


http://www.filedropper.com/rpcs3

**Comment by kd-11** [comment]
The only way these logs are even possible is if we can somehow have a DSV and RTV at the same address! I'm posting a build that should debug this case, and give RTVs priority as that is what the texture cache does.

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.305 should get this one. Please confirm. If it doesnt work, post the new log here.

**Comment by kd-11** [comment]
Appveyor crashed. New build https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.306

**Comment by raven02** [comment]
Disgaea 3 looks okay again .

**Comment by kd-11** [comment]
If it works it means I was right. Well, now on to https://github.com/RPCS3/rpcs3/issues/2093

**Comment by raven02** [comment]
I run the latest build on Disgaes 3 as well . Log here - 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/508282/RPCS3.zip)
