### ISSUE TITLE
Open gl working or not

### ISSUE THREAD

**Issue by jaskarandeep** [RPCS3/rpcs3#2182]
Hey bro when i try to play naruto storm 1 on open gl it worls and show title and popup for installation. installation dialog does not go ahead and when i saw emulator iwas on a text pink coloured says "class std runtime error thrown  unimplemented ( in file c\rpcs3\emu\cell\modules\cellfs.cpp 843)" plese help me

**Comment by Nezarn** [comment]
stop spamming issues here on github, go to the forum, and also read this first http://www.emunewz.net/forum/showthread.php?tid=174352

**Comment by raven02** [comment]
Please discuss here http://www.emunewz.net/forum/forumdisplay.php?fid=162 
thanks
