### ISSUE TITLE
Open gl 

### ISSUE THREAD

**Issue by jaskarandeep** [RPCS3/rpcs3#2183]
In old version 0.0.0.6 4186-bfed7cb opengl open data installs and when open game blank screen apears a tone of storm 1 start red text says " rsx failed to compile  shader eror 067 syntax error syntax error " and next error"exeption linkage failed attached fragment shader is not compiled"  it should work please help if dx 12 . It says not capitable on your pc level

**Comment by raven02** [comment]
Please discuss here http://www.emunewz.net/forum/forumdisplay.php?fid=162 
thanks
