### ISSUE TITLE
DX12: Doesn't keep aspect ratio (16:9) after resizing window

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2187]
Tested in https://github.com/RPCS3/rpcs3/commit/22b14000184c2a78b29e1b3478cfd9993b37535c

**DX12** (Doesn't keep 16:9 aspect ratio)
![](http://i.imgur.com/JjB5yLT.png)
**OGL** (Keeps 16:9 aspect ratio) - Looks a bit pixelated.
![](http://i.imgur.com/zsxmAye.png)
**Vulkan** (Keeps 16:9 aspect ratio)
![](http://i.imgur.com/UFqnARo.png)

Settings are 1280x720 and 16:9 aspect ratio.

**Comment by kd-11** [comment]
The ogl blockiness/pixelation is easy to fix; i'll do that in a future PR. The DX12 stuff is a bit more complicated than that.

**Comment by raven02** [comment]
I think it is 720x480 resolution . 1280x720 should be fine . DX12 always scale to full size.

**Comment by MarioSonic2987** [comment]
No, it's 1280x720 streched.

**Comment by MarioSonic2987** [comment]
Normally, it's fine.

**Comment by kd-11** [comment]
DX12 doesn't have a texture blit function. To get around this we use a renderpass that draws a fullscreen quad with the output texture. The passthrough shaders used can be modified to account for aspect ratio of course, but that takes a little more work. An easy approach is to generate a scale+offset texture matrix and use it to modify the texture coords during sampling. I could work on this, but it may take a few days before I find time for it.

**Comment by MarioSonic2987** [comment]
With #2647, pixelation in OpenGL is fixed.
![image](https://cloud.githubusercontent.com/assets/20027681/24835494/0d3226e0-1d04-11e7-8f19-f67a7f717817.png)

Remains the DX12 issue.
