### ISSUE TITLE
Open gl rsx thread

### ISSUE THREAD

**Issue by jaskarandeep** [RPCS3/rpcs3#2189]
When i try to boot  naruto storm 1 it starts afeter the 2 bandia namco logo it starting in black . Console log says exeption linkage failed attached fragment shader in compiled please report this to developersb

**Comment by SakataGintokiYT** [comment]
Why you not use latest build ?
https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.3472/artifacts

*Select these modules:
-libadec
-libatxdec
-libdmux.prx 
-libdmuxpamf.prx
-libfiber
-libresc
-librtc
-libsail
-libsmvd2
-libsre
-libspurs_jq
-libvdec

**Comment by raven02** [comment]
Please discuss in http://www.emunewz.net/forum/forumdisplay.php?fid=162 . thanks.
