### ISSUE TITLE
GL/Vulkan:  The Walking Dead: Michonne  

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2190]
@kd-11 
@raven02 

<img src="http://www.fotoszok.pl/upload/5bccf875.jpg" alt="Fotoszok.pl" />

**RenderDoc [OGL]**

**[Title screen](https://mega.nz/#!MARjVBhT!YmRntlB1MmGiDh3PfOdwqghMaefuww27NowLaPHrIMg)**
**[Menu](https://mega.nz/#!pBpzyKZb!vM7trrWai52yjdpTaOSVmyszjrDfmsuL3-M0Qk07udM)**
**[In Game](https://mega.nz/#!RIoQECpB!saWoSIJixuokr-xy5ANitBDtd5yFZuToaszszwVosEk)**
**[Shaderlog-OGL](https://mega.nz/#!cYBWFaga!DHpHbtTtjqyB0Cagtvwnf9y2TtEcXh6sUd4LsMSTp54)**
**[Shaderlog-VK](https://mega.nz/#!kAgWiCyC!gOe9D-jvRUuS1CqgsVRB699lm2HzWYcR9b1bsMxcT-w)**

**LLE:**
<img src="http://www.fotoszok.pl/upload/d396441f.jpg" alt="Fotoszok.pl" />

**DX12 / crash at the title screen** 

**[video]:** https://www.youtube.com/watch?v=P2njcB_L92k

**Comment by kd-11** [comment]
Texture swizzle problem with DXT5

**Comment by kd-11** [comment]
Or poorly supported vertex attribute format. The problem seems to be the passed texture coordinates to me. They're too closely clustered to make any sense. Even from the texture viewer its obvious something is very wrong: The texture coordinates for all vertices is the same.

**Comment by SakataGintokiYT** [comment]
DX12
<img src="http://www.fotoszok.pl/upload/59eefb09.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
another title that differs. Can you check if builds from say, 3 weeks ago worked? Before I touched the texture settings on vulkan. Might be a regression (on vulkan)

**Comment by SakataGintokiYT** [comment]
@kd-11 
I tested build before gl/vk: Enable vertex texture fetch (#2127) and looks like the same

**Comment by SakataGintokiYT** [comment]
**TTY: OpenGL/ Vulkan/DX12** 
```
PSGL console initialized

OpenGL_ES-CM_1.0-optrsx_SCE_DDD_MMM_dd_hh:mm:ss_TMZ_yyyy
Filtering mode GL_LINEAR not supported for FP32 textures, using GL_NEAREST instead
Filtering mode GL_LINEAR not supported for FP32 textures, using GL_NEAREST instead
Filtering mode GL_LINEAR not supported for FP32 textures, using GL_NEAREST instead
Filtering mode GL_LINEAR not supported for FP32 textures, using GL_NEAREST instead
```

**Comment by kd-11** [comment]
Thats not the problem with this one. Filtering FP32 textures was not supported back in the SM 3 days.

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.340 Should fix most of these problems. From youtube videos however, it seems we still have a transform issue with this title, but atleast graphics should work now.

P.S Dont try to attach renderdoc to that build. It uses persistent mapped buffers which are very unfrendly to tracing. You'll get something like 1 frame every 10 seconds with it which is why I'm working on a debug option to disable buffer optimization.

**Comment by kd-11** [comment]
Try https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.341 since the previous build has crashed appveyor

**Comment by SakataGintokiYT** [comment]
@kd-11 
```
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x2f (forced unit 2)
```
**[Vulkan]**
<img src="http://www.fotoszok.pl/upload/52db293f.jpg" alt="Fotoszok.pl" />
**[OpenGL]**
<img src="http://www.fotoszok.pl/upload/362f7252.jpg" alt="Fotoszok.pl" />

**[shaderlog-vulkan](https://mega.nz/#!AR5XWKDZ!RmpF1zHBSTHHlyi4jOXGDHfNvllZt0CfcmcuxoYiAc0)**

**Comment by kd-11** [comment]
My opengl actually resembles your vulkan, so I'm unsure if his is an nvidia driver bug.
Vertex format RG16_SNORM is part of GL 3.1 so why nvidia is buggy with it I have no Idea.

**Comment by kd-11** [comment]
Enable debug output with opengl and check to see if we are violating an alignment check.

**Comment by kd-11** [comment]
![image](https://cloud.githubusercontent.com/assets/15904127/19410597/d384069c-92f8-11e6-9ec2-c7ba7e3441c0.png)
AMD

Did you build yourself or download the compiled binaries?

**Comment by SakataGintokiYT** [comment]
OpenGL with enable debug output not show anything

**Comment by kd-11** [comment]
Send me a trace of your opengl. If it looks fine on my system, the NV driver is doing something wrong.

**Comment by SakataGintokiYT** [comment]
@kd-11 
renderdoc  ?

**Comment by kd-11** [comment]
Use this build: https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.343 It removes the persistent buffers for testing.

**Comment by SakataGintokiYT** [comment]
[master with your fix]
**[OGL-RenderDoc](https://mega.nz/#!xZhVnRDI!vRLDLGYUJ6thPvN1GJF8eaXjWdwR6flvdBaIl-3D5jQ)**

**Comment by kd-11** [comment]
![image](https://cloud.githubusercontent.com/assets/15904127/19411607/c1183df6-930d-11e6-97bb-55a84dc6e422.png)

The trace plays back fine on my graphics card which means NV driver is broken. Will need confirmation from other Nvidia and AMD users. Working around lack of EXT_texture_snorm support would be a nightmare. Its possible Nvidia does not support access of type RG16_SNORM with texelFetch or it may just be a bug worth reporting.

**Comment by kd-11** [comment]
Looking at the 4.3 spec https://www.opengl.org/registry/doc/glspec43.core.20120806.pdf page 206, Nvidia does not have to implement signed normalized textures in order to claim compatibility. I guess they didnt (and likely wont) add this in. I could emulate signed normalized access however either in the shader or software side using float arrays.

**Comment by SakataGintokiYT** [comment]
**[Driver 372.90]**
I have the same issue on GTX 960M

**Comment by kd-11** [comment]
Nvidia does not support signed normalized textures in their buffers. It might be a hardware limitation. I've been working on a solution to emulate this in the vertex shader.

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.345 Adds support for vertex attribute emulation and enables any backend to do this without much hassle. Also adds an option in the graphics tab to disable persistent mapped buffers and use slower legacy buffers which allow debugging using tracing tools such as renderdoc

**Comment by kd-11** [comment]
That build has reduced buffer size to help with debug. Let me upload one with a larger heap size. That one is using a 10MB buffer which is way too small as I needed to test collision behaviour.

**Comment by SakataGintokiYT** [comment]
**[OpenGL]**
<img src="http://www.fotoszok.pl/upload/6f563708.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.346 has much better buffer sizes improving performance and eliminating flicker. There's a bug with the legacy buffers implementation that can cause crashing that I need to work out before I can submit that work.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/2206 fixes this issue

**Comment by SakataGintokiYT** [comment]
@kd-11 
[Vulkan/OGL] #2206 
<img src="http://www.fotoszok.pl/upload/46bbe824.jpg" alt="Fotoszok.pl" />

**Comment by SakataGintokiYT** [comment]
@kd-11 
<img src="http://www.fotoszok.pl/upload/e0614480.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
could you add opengl images as well? It should be better and the differences with vulkan will give clues.

**Comment by SakataGintokiYT** [comment]
**[In game Vulkan / OpenGL looks like the same in this scene]**
<img src="http://www.fotoszok.pl/upload/46bbe824.jpg" alt="Fotoszok.pl" />

**[OpenGL]**
<img src="http://www.fotoszok.pl/upload/f50768d7.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/459dfda9.jpg" alt="Fotoszok.pl" />

**Comment by SakataGintokiYT** [comment]
@kd-11 

**OpenGL RenderDoc:** 
**[Menu](https://mega.nz/#!5ZBnCBiA!5Za290zJyx1e8Eg6Bs9-g0_Nn__0AJftrJIuFUCe4GU)**
**[In game](https://mega.nz/#!gcBwUZYL!o6kKwcsimdC3mldg_MHaJpwd9cr8QRJiOa81d_e7YwU)**

**Comment by MarioSonic2987** [comment]
Can you test with latest build?

**Comment by MarioSonic2987** [comment]
With #2482, some glitches are "fixed". @SakataGintokiYT, reopen this issue, please.
![](http://i.imgur.com/r7iY99V.png)
![](http://i.imgur.com/oWHGBng.jpg)
![](http://i.imgur.com/ZF6smh3.png)

**Comment by kd-11** [comment]
If this is a regression, please do some regression testing

**Comment by SakataGintokiYT** [comment]
@kd-11 
[dbb67659]
<img src="http://www.fotoszok.pl/upload/0cea3ecd.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
I mean which commit introduces that bug? Is it with all backends?
I cannot get the game to boot with and without auto LLE.

**Comment by SakataGintokiYT** [comment]
@kd-11 
With-Legacy OpenGL Buffers
<img src="http://www.fotoszok.pl/upload/70ac7419.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
ok. so its a sync bug
I keep getting the stop mbox is empty bug endlessly. I'll try again tomorrow

**Comment by kd-11** [comment]
I tried with the build from this PR https://github.com/RPCS3/rpcs3/pull/2482 and was unable to reproduce. Confirm it works for your driver setup as well.

**Comment by MarioSonic2987** [comment]
@kd-11 Some glitches are fixed.

Tested in https://github.com/RPCS3/rpcs3/commit/73893b5b041e2fe1cf7913f3e1bf8fa581ba6c88.
![image](https://cloud.githubusercontent.com/assets/20027681/25988363/f8e7407c-36f7-11e7-945e-14594ccb3623.png)
![image](https://cloud.githubusercontent.com/assets/20027681/25988505/80408f56-36f8-11e7-8128-494dfb3319d0.png)
![image](https://cloud.githubusercontent.com/assets/20027681/25988589/db6e9968-36f8-11e7-8287-14216efebe0a.png)
