### ISSUE TITLE
DX12/GL/Vulkan: Rayman 3 HD

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2191]
Tested in https://github.com/RPCS3/rpcs3/commit/7a9841bb2a1d703fd9269adda9e02f6ac4686de3.

**DX12** - Can reach ingame.
![](http://i.imgur.com/0vXK39k.jpg)
This image is in title screen.

**Vulkan** - Stops after Ubisoft's logo with:

```
·! {rsx::thread} RSX: FP not found in buffer!
·E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
·E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
·E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
·E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
·E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
·E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
·E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
·E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
·E {rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:75: '' :  syntax error
ERROR: 1 compilation errors.  No code generated.
```

**OGL** - Stops after Ubisoft's logo.

[Shader log DX12](http://www.mediafire.com/file/250ujsrx731bmww/Shaderlog_DX12_R3.rar)
[Shader log Vulkan](http://www.mediafire.com/file/wx15k4bnwwzre5i/Shaderlog_VK_R3.rar)
[Shader log OGL](http://www.mediafire.com/file/m06q8ylvm8m882h/Shaderlog_OGL_R3.rar)
[Log OpenGL](http://www.mediafire.com/file/3j5x08p3giikqpq/Log_R3_9-10-16_OGL.rar)
LLE: resc, sre, rtc.

**Comment by andre4688** [comment]
see my video run game Rayman https://www.youtube.com/watch?v=-Zdgx8Ineaw

**Comment by MarioSonic2987** [comment]
Tested with: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-4299.

**DX12/GL/Vulkan**: Shader issue is solved, but it seems very unstable (freezes between Ubisoft's intro and main menu).
![](http://i.imgur.com/8mQm8CM.png)
![](http://i.imgur.com/FZLPCk4.png)
[Log Vulkan](https://gist.github.com/MarioSonic2987/9b932d71a9a70135d8fd76dfaf8ffaa9#file-log-rayman-3-6-4-17-vk-log)
