### ISSUE TITLE
Vulkan: Worms 2: Armageddon/Worms Crazy Golf

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2192]
Tested in https://github.com/RPCS3/rpcs3/commit/7a9841bb2a1d703fd9269adda9e02f6ac4686de3.

**DX12/Vulkan/OGL** - All stuck in title screen.
![](http://i.imgur.com/7qs9ntA.png)

[Shaderlog DX12](http://www.mediafire.com/file/j8y6vtoo46mjhma/Shaderlog_DX12_W2A.rar)
[Shaderlog OGL](http://www.mediafire.com/file/73bri6e346hecu6/Shaderlog_OGL_W2A.rar)
[Shaderlog Vulkan](http://www.mediafire.com/file/a023616hi6rq2o2/Shaderlog_VK_W2A.rar)
[RenderDoc Vulkan](http://www.mediafire.com/file/94s051uqsq21ixx/Renderdoc_W2A_VK.rar)

LLE: rtc, sre.

**Comment by MarioSonic2987** [comment]
# Update (22-12-16)
Tested in https://github.com/RPCS3/rpcs3/commit/9e84804eb0ce1fca9860e289e35bb0bb5f0ce8cb

![](http://i.imgur.com/IqcQR3N.png)
![](http://i.imgur.com/3QVbJEL.png)
![](http://i.imgur.com/140VZZL.png)
[Shaderlog DX12](https://drive.google.com/open?id=0B9LymxJkpT48MEdIUkttVE1sY1k)
[Shaderlog OGL](https://drive.google.com/open?id=0B9LymxJkpT48anB1MGhFR3FidTg)
[Shaderlog Vulkan](https://drive.google.com/open?id=0B9LymxJkpT48V0VONk9kaEFvbHc)

**Comment by MarioSonic2987** [comment]
Fixed in https://github.com/RPCS3/rpcs3/commit/d86d65568dc38b334c13c0241cda02643ea855fa!
![](http://i.imgur.com/wWOr92U.png)
![](http://i.imgur.com/AfJPReJ.png)
![](http://i.imgur.com/gn6XL78.png)

**Comment by MarioSonic2987** [comment]
But still can't get ingame.

**Comment by MarioSonic2987** [comment]
With #2647, goes ingame in OpenGL, at least (GPU scaling on).
![asvcxszxz](https://cloud.githubusercontent.com/assets/20027681/24836987/0ecd01a2-1d2a-11e7-9dff-958b667a731e.png)

**Comment by raven02** [comment]
@MarioSonic2987  , Vulkan and DX12 can in-game or only GL did ?

**Comment by MarioSonic2987** [comment]
Only GL can get ingame.

**Comment by AniLeo** [comment]
Well there's only HW scaling on GL yet

**Comment by AniLeo** [comment]
@MarioSonic2987 Can you retest on latest master? Ignore D3D12

**Comment by MarioSonic2987** [comment]
With https://github.com/RPCS3/rpcs3/commit/3499d089e74439192ab1cb52c88072e1d44020f9, freezes at this point:

![image](https://user-images.githubusercontent.com/20027681/30701780-6f28460e-9eeb-11e7-84bd-e0419720bd34.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1321623/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Oh rip, it's spamming way too many mutexes, any idea when it regressed? Doesn't seem anything from kd's latest PR.

**Comment by MarioSonic2987** [comment]
Could be in #3454.

**Comment by MarioSonic2987** [comment]
With https://github.com/RPCS3/rpcs3/commit/a1fa10ac70446ff5f4e0ba77068752bdbd0549f8, works again and goes ingame with GPU texture scaling disabled, but it has corrupted GUI textures.
![w2a](https://user-images.githubusercontent.com/20027681/33852875-501d59be-debc-11e7-810c-6a7bbbdbd910.png)

I decided to include Worms Crazy Golf in this issue because it suffers the same glitches as W2A:
![wcg-1](https://user-images.githubusercontent.com/20027681/33852902-68dc66ca-debc-11e7-99c8-873c3df96726.png)
![wcg-2](https://user-images.githubusercontent.com/20027681/33852905-6b818680-debc-11e7-9db2-f9df19728563.png)
[Log W2A OpenGL](https://github.com/RPCS3/rpcs3/files/1549334/Log.W2A.11-12-17.GL.gz)
[Log WCG OpenGL](https://github.com/RPCS3/rpcs3/files/1549339/Log.WCG.11-12-17.GL.gz)

[Shaderlog W2A OpenGL](https://drive.google.com/open?id=1BB3rAUGXbz8FdB370SRTRlOf2dx7OkfF)
[Shaderlog WCG OpenGL](https://drive.google.com/open?id=1rqh1ZA0rEIGcWnTDysiNh9aHXex32vY8)

[RenderDoc OpenGL](https://drive.google.com/open?id=1bDgbhJJYWsj9WLW-l_z31dyKdbukeC8u)

**Comment by MarioSonic2987** [comment]
With https://github.com/RPCS3/rpcs3/commit/13aa88c3c4d66ea8799e987f7d762d90943ab17b, HUD is fixed in Worms 2: Armageddon:

![image](https://user-images.githubusercontent.com/20027681/35994504-e9b751ec-0d10-11e8-99f2-c048269273f4.png)

![image](https://user-images.githubusercontent.com/20027681/35994202-0109bf84-0d10-11e8-88f5-57103a4ad944.png)
In Worms Crazy Golf, HUD is fixed, but the display is narrow in Vulkan only:

![image](https://user-images.githubusercontent.com/20027681/35994547-08dab4ce-0d11-11e8-8dab-5d0c29a18df9.png)
![image](https://user-images.githubusercontent.com/20027681/35994277-3742741a-0d10-11e8-99d1-584bc1a4f0ea.png)

The glitched titlescreen in WCG remains the same:
![image](https://user-images.githubusercontent.com/20027681/35994621-48f5b9e6-0d11-11e8-889a-bbe5793d9fb2.png)

[Log Vulkan (WCG)](https://github.com/RPCS3/rpcs3/files/1708542/Log.WCG.8-2-18.VK.gz)

**Comment by kd-11** [comment]
Pretty sure this is fixed, update and close if necessary.

**Comment by MarioSonic2987** [comment]
With 0.0.6-7886, still has these minor graphical issues:

<details>
 <summary>Bugged title screen (OGL/Vulkan and only in WCG)</summary>

![image](https://user-images.githubusercontent.com/20027681/54645563-b1367300-4a9c-11e9-9428-4a704c4c8950.png)
</details>

<details>
 <summary>Blurred worms and missing hats (Vulkan only in WCG and W2A)</summary>

![image](https://user-images.githubusercontent.com/20027681/54645946-e1324600-4a9d-11e9-8f73-23ee7c40fe9f.png)
![image](https://user-images.githubusercontent.com/20027681/54645832-83056300-4a9d-11e9-9707-efbc392fba45.png)
![image](https://user-images.githubusercontent.com/20027681/54645649-eb077980-4a9c-11e9-81be-095f9d5266a4.png)
![image](https://user-images.githubusercontent.com/20027681/54645586-be536200-4a9c-11e9-8ef5-5764edfbf24e.png)
</details>

[RSX Captures (WCG Title screen and ingame)](https://github.com/RPCS3/rpcs3/files/2985798/Captures.WCG.TT.and.Ingame.zip)

**Comment by MarioSonic2987** [comment]
Bugged title screen in Worms Crazy Golf is now fixed. But it now hangs with OpenGL:
![image](https://user-images.githubusercontent.com/20027681/57524552-6dd3e480-7328-11e9-959a-4bc13f09bf8e.png)

Missing hats and blurred worms are still there.

[Log OpenGL (WCG)](https://github.com/RPCS3/rpcs3/files/3166280/log.WCG.10-5-19.zip)

**Comment by MarioSonic2987** [comment]
It no longer hangs with OpenGL.
![image](https://user-images.githubusercontent.com/20027681/63461197-65776380-c458-11e9-8c63-55eb6f8b8263.png)
But with Vulkan, it still has blurred worms and missing hats. There's a workaround for this. You need to set Resolution Scale to 200% (1440p).

**720p (100%)**:
![image](https://user-images.githubusercontent.com/20027681/63461281-935ca800-c458-11e9-9df2-ef404a7248ca.png)
**1440p (200%)**:
![image](https://user-images.githubusercontent.com/20027681/63461352-bb4c0b80-c458-11e9-9d9e-07a507537b2e.png)

**Comment by kd-11** [comment]
Please update. Is this still broken?

**Comment by MarioSonic2987** [comment]
They crash after booting with:
```
F {RSX [0x010199c]} SIG: Thread terminated due to fatal error: VirtualProtect failed (00000003cf180000, 0xa00000, addr=0x3cf900000, error=0x1e7)

```
[Log WCG](https://github.com/RPCS3/rpcs3/files/4600387/RPCS3.zip)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/8215

**Comment by MarioSonic2987** [comment]
Crashes are fixed and there's no blurred textures and missing hats with Vulkan.

**Comment by kd-11** [comment]
Closing as fixed.
