### ISSUE TITLE
RSX: Unimplemented TEX instructions BEM and TEXBEM

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2194]
`E {rsx::thread} RSX: Unimplemented TEX_SRB instruction: BEM`
 NPEB00879 - Rayman 3 HD Trial
**[LOG](https://gist.github.com/SakataGintokiYT/f260a804b32ded74c972c457439d671e)**
**[shaderlog-Vulkan](https://mega.nz/#!odJG0axb!V3XcBOJh6-gCy7ARilTv3149uIVOYdZLwobsjQ2wVAc)**
**[shaderlog-GL](https://mega.nz/#!hJwViQSI!l8kM57cCOx-_D5nAuwHpTSEaNzzVwVgoPhy9uJqohXU)**

**Comment by kd-11** [comment]
TEXBEM is implemented by https://github.com/kd-11/rpcs3/commit/f641960cbb3de7f226ad5f67a7be433d2374ff5b and BEM is implemented by https://github.com/kd-11/rpcs3/commit/06876a285bfffb41bfaa3ff9ac03e77d6880109f. Check if anything changed for the game. TEXBEM is untested, but I have not heard of a game that is using it.

**Comment by SakataGintokiYT** [comment]
@kd-11 
Dragon Ball: Raging Blast 2 use TEXBEM opcode.

**Comment by kd-11** [comment]
Cool. Then hopefully it doesnt crash. We can track both BEM and TEXBEM which are closely related here

**Comment by SakataGintokiYT** [comment]
@kd-11 
Dragon Ball: Raging Blast 2 
requires this opcode too:
`E {rsx::thread} RSX: Unimplemented SIP instruction: CAL`

**Comment by kd-11** [comment]
That one is alot more complicated and requires a redesign of the decompiler framework to support generic subroutines.

**Comment by Zangetsu38** [comment]
render is very perfect for men abd log say nothing, compared gbefore, same for first game GG 
![image](https://user-images.githubusercontent.com/5261759/33810915-c5a549dc-de0b-11e7-86f6-f1b7bcd07673.png)

**Comment by SakataGintokiYT** [comment]
@Zangetsu38 
![bez tytulu](https://user-images.githubusercontent.com/13681488/33811017-24a169e2-de0d-11e7-804a-7a0b78c9f246.png)

**Comment by Zangetsu38** [comment]
i using last commit KD, maybe depending scene also

**Comment by SakataGintokiYT** [comment]
Only some characters have broken textures.

**Comment by kd-11** [comment]
Fixed a while ago
