### ISSUE TITLE
Find bottleneck in OpenGL / Vulkan 

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2195]
@kd-11 
[97cd87eb]

**Naruto Shippuden: Ultimate Ninja Storm 3**
[OpenGL]
<img src="http://www.fotoszok.pl/upload/8d5ff0a7.jpg" alt="Fotoszok.pl" />
[Vulkan]
<img src="http://www.fotoszok.pl/upload/1996e897.jpg" alt="Fotoszok.pl" />
**[Log-GL](https://mega.nz/#!JAAA1ZhL!4ZxdHCAx57CFZucNvuW4va-voZJyv-TskyGl-rFXLvE)**
**[Log-Vulkan](https://mega.nz/#!8UQXVQ5C!BgY_D3lRI5DhqO0AapAV6cn5nSfkBT_QqmGdaWEteZo)**

**Blade Arcus From Shining EX**
[OpenGL]
<img src="http://www.fotoszok.pl/upload/cb6545f4.jpg" alt="Fotoszok.pl" />
[Vulkan]
<img src="http://www.fotoszok.pl/upload/1ab87383.jpg" alt="Fotoszok.pl" />
**[Log-GL](https://mega.nz/#!FUo0XJaR!HGaUQmBXWRCSyygu38wQFwAQBIp-eE86KFXQe_1Wfqk)**
**[Log-Vulkan](https://mega.nz/#!tERlQAQY!QtHpPMadMm5AIhm-ibErwQ1D0B8QDk38bkRe4cm-HP0)**

**Comment by kd-11** [comment]
Problem is cellside, especially for blade arcus. I can run this game at 60fps using llvm. The scene posted from blade arcus (ogl) has the renderer thread running at a theoretical max of almost 100fps
