### ISSUE TITLE
Project Diva F 2nd stuck forever on load scree

### ISSUE THREAD

**Issue by Waelwindows** [RPCS3/rpcs3#2197]
Game is stuck on load screen forever after choosing a song. 
https://puu.sh/rEkHq/6ba9ae34fa.png

My Log: http://pastebin.com/4WNnhR2P

My settings: PPU : fast SPU : ASMJIT

LLE : libresc, librtc, libspurs_jq, libsre

**Comment by raven02** [comment]
Please discuss in http://www.emunewz.net/forum/forumdisplay.php?fid=162
