### ISSUE TITLE
GL/Vulkan: Castlevania: Lords of Shadow - Mirror of Fate HD

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2198]
Tested in https://github.com/RPCS3/rpcs3/commit/8454949eea9d0fc9da55b719e9a02f5a022fd5f5.
DX12:

```
{rsx::thread} RSX: Src type 3 used, please report this to a developer.
{rsx::thread} RSX: Src type 3 used, please report this to a developer.
{rsx::thread} RSX: FS build failed:0000000004ff7e80
{rsx::thread} class std::runtime_error thrown: fragment program compilation failure
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)
```

GL:

```
{rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
-------------
0(92) : error C0000: syntax error, unexpected '.', expecting ')' at token "."
(0) : error C2003: incompatible options for link
'
```

Vulkan:

```
E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
E {rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:91: '' :  syntax error
ERROR: 1 compilation errors.  No code generated.


E {rsx::thread} RSX: 
F {rsx::thread} class std::runtime_error thrown: Failed to compile fragment shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:475)
```

All stuck at a black screen.
[Shader log DX12](http://www.mediafire.com/file/qay2nl4t1enskq5/ShaderLog_DX12_CLoS_MoF.rar)
[Shader log OGL](http://www.mediafire.com/file/ubv0hlq0hrevux5/ShaderLog_OGL_CLoS_MoF.rar)
[Shader log Vulkan](http://www.mediafire.com/file/3c43pqyje756ucz/ShaderLog_VK_CLoS_MoF.rar)

**Comment by MarioSonic2987** [comment]
In Vulkan, with PR #2405, reaches to title screen (heavily broken).
![](http://i.imgur.com/SsLR1yP.png)

**Comment by MarioSonic2987** [comment]
Fixed in #2440.
![](http://i.imgur.com/UCzmBsD.jpg)
![](http://i.imgur.com/W45zNeJ.jpg)
![](http://i.imgur.com/Nyu3MC9.jpg)

**Comment by raven02** [comment]
So can this be close ? or only reach title but not in-game

**Comment by MarioSonic2987** [comment]
No. This game can't get ingame and have a string load error.

**Comment by georgemoralis** [comment]
what kind of error can you post it?

**Comment by MarioSonic2987** [comment]
[Log](https://gist.github.com/MarioSonic2987/819fee2cf7175e2378ac3ce6cb1a4a15#file-log-castlevania-mirror-log)

And have a polygon issue.
![](http://i.imgur.com/K9CPJVJ.png)

**Comment by AniLeo** [comment]
Please retest

**Comment by MarioSonic2987** [comment]
Tested with https://github.com/RPCS3/rpcs3/commit/6d14583f287c5b19ebb06636b9c6ecd1541436d2:

Reaches ingame with broken models (in Vulkan):
![image](https://user-images.githubusercontent.com/20027681/29353049-323ad8ae-8269-11e7-9749-541b7a413b7c.png)

**Comment by MarioSonic2987** [comment]
Tested in https://github.com/RPCS3/rpcs3/commit/da3f3fd1fb1682d2b4f7c30600b6174942b71813:
![image](https://user-images.githubusercontent.com/20027681/29938427-f797143e-8e88-11e7-9176-bb1f14b87090.png)

**Comment by AniLeo** [comment]
Needs retesting, attach a full log as it may contain useful information

**Comment by MarioSonic2987** [comment]
With https://github.com/RPCS3/rpcs3/commit/3499d089e74439192ab1cb52c88072e1d44020f9:

![image](https://user-images.githubusercontent.com/20027681/30701364-60945714-9eea-11e7-9d23-1dc2d0aa271f.png)
[RPCS3.log.gz (GL)](https://github.com/RPCS3/rpcs3/files/1321592/RPCS3.log.gz)

**Comment by MarioSonic2987** [comment]
With https://github.com/RPCS3/rpcs3/commit/bfb3144f3476d1367da0fd9012e6475a0e6b9603:

![image](https://user-images.githubusercontent.com/20027681/33560026-e5f09da6-d90e-11e7-86db-f861b92d3573.png)
[Log CLOSMOF 4-12-17 GL.gz](https://github.com/RPCS3/rpcs3/files/1527635/Log.CLOSMOF.4-12-17.GL.gz)
[Shaderlog OpenGL](https://drive.google.com/open?id=1F1jozB5LCAn1D0jR332oP7ij9BGYCmzW)
[RenderDoc OpenGL](https://drive.google.com/open?id=11mvpUFwWSVW3uvG6LrhCPZkKZZe39rn2)

**Comment by Omaranwa** [comment]
Can You retest

**Comment by MarioSonic2987** [comment]
@Omaranwa Still the same.
![image](https://user-images.githubusercontent.com/20027681/42514784-7f9fbdfa-845a-11e8-8a5d-54ca01d87e0b.png)
[RSX Capture](https://github.com/RPCS3/rpcs3/files/2180656/capture.CLOSMOF.10-7-18.zip)

**Comment by MarioSonic2987** [comment]
Broken models are now fixed:
![](https://cdn.discordapp.com/attachments/272875751773306881/619486759616774145/unknown.png)

Broken texts are still there (The text id appears instead of actual text).
![image](https://user-images.githubusercontent.com/20027681/64423553-190e6380-d0a7-11e9-9392-e9d23eddf2d9.png)
 Sometimes they show correctly (race condition?).
![image](https://user-images.githubusercontent.com/20027681/64423440-d5b3f500-d0a6-11e9-83ad-a8a935827f26.png)

**Comment by kd-11** [comment]
I would suggest to open a separate issue for that as it is not actually a rendering issue.

**Comment by MarioSonic2987** [comment]
Right. Closing this issue.
