### ISSUE TITLE
OpenGL Initialization error on Intel HD + Nvidia GPUs

### ISSUE THREAD

**Issue by andre4688** [RPCS3/rpcs3#22]
**Error:**

> [E : RSXThread]: OpenGL: initialization of glProgramUniform1i failed.
> [E : RSXThread]: OpenGL: initialization of glProgramUniform1f failed.
> [E : RSXThread]: OpenGL: initialization of glProgramUniform4f failed.
> [E : RSXThread]: OpenGL: initialization of glDepthBoundsEXT failed.

**What version of the product are you using? On what operating system?**
rpcs3-git-20131117 on Windows 8 64 bit and with two GPUs (an integrated Intel HD Graphics 4000 and a Nvidia GT 635M with updated drivers).

**Configuration:**
GS: Render: _OpenGL_
IO: Pad handler: _Windows_
IO: Keyboard handler: _Windows_
IO: Mouse handler: _Windows_

EDIT: Issue edited by _AlexAltea_ on 24.11.2013.

**Comment by birdsnbones** [comment]
> I assume _obrigado_ means "_Issue fixed_", so I'm going to close this.
> 
> PS: **Write in english**. If you can't, at least use the goddamned Google Translator. I'm going to edit your issue's title and description, in order to make other people understand what this error really is in case they have this problem.

orrr here's an idea: stop being a fucking racist, and use the translate feature yourself. you don't have to be rude :/

**Comment by Valtekken** [comment]
> > I assume _obrigado_ means "_Issue fixed_", so I'm going to close this.
> > PS: **Write in english**. If you can't, at least use the goddamned Google Translator. I'm going to edit your issue's title and description, in order to make other people understand what this error really is in case they have this problem.
> 
> orrr here's an idea: stop being a fucking racist, and use the translate feature yourself. you don't have to be rude :/

Language has nothing to do with race. If you gotta call someone names, call them the correct name. You're also necroposting on an issue from ELEVEN years ago. Get a damn grip.

**Comment by AlexAltea** [comment]
> orrr here's an idea: stop being a fucking racist, and use the translate feature yourself. you don't have to be rude :/

Admiro tu empatía con otros usuarios, y siento que un comentario mío de hace 11 años dirigido a otro usuario te haya ofendido tanto. Afortunadamente, hoy en día soy bastante más educado, y he editado mi mensaje para que quede constancia. Un saludo y disfruta del día! :slightly_smiling_face:
