### ISSUE TITLE
GL/Vulkan: God of War 1+2 HD collection video playback issue

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2202]
dx12
video：https://youtu.be/FnVe3QKCWEY
![qq 20161012160745](https://cloud.githubusercontent.com/assets/20301499/19302499/f7c926e0-9096-11e6-8280-59cd9f607df5.png)
vullkan
![qq 20161012162131](https://cloud.githubusercontent.com/assets/20301499/19302900/f42829e4-9098-11e6-899d-c8f674a6db35.png)
OpenGL
![qq 20161012122116](https://cloud.githubusercontent.com/assets/20301499/19297538/7c942b78-9078-11e6-988e-62dad2765134.png)
Load for a long time，crash is still here
![qq 20161012160921](https://cloud.githubusercontent.com/assets/20301499/19302458/cd0d5610-9096-11e6-95fe-59ca85b71bab.png)
log：https://drive.google.com/open?id=0B4z-S0oOZ2FgZUlkWDVTSU9ueVk

**Comment by raven02** [comment]
I think it is coloring issue in Vulkan backend . Correct me if i'm wrong.

**Comment by kd-11** [comment]
Vulkan is swizzle with a red-blue mimatch. look at the circle button at the bottom. OGL and vulkan also have broken lighting although this is the case with other games as well.

**Comment by RainKikyou** [comment]
well done！The model has been fixed in [973bf5ab](https://ci.appveyor.com/project/rpcs3/rpcs3/branch/master/artifacts)
but, there are still some problems，I try to capture the scene information of the graph
ogl
![ogl](https://cloud.githubusercontent.com/assets/20301499/19634339/b714ed50-99ec-11e6-9cd7-2eab03681630.png)
rdc：https://drive.google.com/open?id=0B4z-S0oOZ2FgcEM4WmlHMi1vLVU
vullkan
![qq 20161024131108](https://cloud.githubusercontent.com/assets/20301499/19634364/d1d9edf2-99ec-11e6-911d-745eae1973b4.png)
rdc：https://drive.google.com/open?id=0B4z-S0oOZ2FgTl82WlVTTkR6Y0E

**Comment by kd-11** [comment]
By the way
```
·F {SPU[0x3c] Thread (BP_MiscCellSpursKernel0)} class std::runtime_error thrown: Unimplemented instruction
(in file Emu\Cell\SPUASMJITRecompiler.cpp:920)
```
Does it still crash when not using ASMJIT recompiler? I know the SPU interpreter is slow, but its worth giving it a shot.

**Comment by RainKikyou** [comment]
Yes, fast and precise with ASMJIT the same

**Comment by RainKikyou** [comment]
I load savadata intro game
![qq 20161114074339](https://cloud.githubusercontent.com/assets/20301499/20249895/67799a2c-aa3e-11e6-8f50-df44b1b37777.jpg)

**Comment by RainKikyou** [comment]
@raven02 I tried video playback in the game , the emulator will not crash but automatically skip.I remember in the old building is a shadow，please watch this video http://www.bilibili.com/video/av4576697/index_6.html
![qq 20161118135316](https://cloud.githubusercontent.com/assets/20301499/20420295/aaeaca4a-ad97-11e6-9ee5-2ca3f2b1515c.jpg)
![qq 20161118135131](https://cloud.githubusercontent.com/assets/20301499/20420305/c2a27020-ad97-11e6-9ef1-54fade35c06e.jpg)
![qq 20161118135853](https://cloud.githubusercontent.com/assets/20301499/20420310/c61d54fe-ad97-11e6-8915-50af46bb70c1.jpg)

**Comment by kd-11** [comment]
Retest ingame with https://github.com/RPCS3/rpcs3/pull/2582

**Comment by RainKikyou** [comment]
OpenGL still
![og1](https://cloud.githubusercontent.com/assets/20301499/24292132/eb5265a6-10c6-11e7-90a3-ad35b7d09362.jpg)

vullkan fixed same with dx12
![vk1](https://cloud.githubusercontent.com/assets/20301499/24292333/df0dfbec-10c7-11e7-94a6-afab43079dc3.jpg)

**Comment by kd-11** [comment]
This has been fixed for a while now. Video playback is still broken but that's a different issue.
