### ISSUE TITLE
Vulkan: TLoS: Dawn of the Dragon failed to boot up

### ISSUE THREAD

**Issue by ScorchEmber256** [RPCS3/rpcs3#2203]
Only fails to boot on vulkan in latest build.
PPU: Interpreter
SPU: Interpreter 

Vulkan:
State: Doesn't boot, playable ingame on previous versions
F LDR: class std::runtime_error thrown: Assertion failed! Result is FFFFFFFAh

OpenGL:
State: Ingame
U {PPU[0x70000000] Thread (main_thread) [0x00a3dab0]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x70000000] Thread (main_thread) [0x00a3db70]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x70000000] Thread (main_thread) [0x00a3d1f0]} cellGcmSys TODO: cellGcmSetGraphicsHandler
E {PPU[0x70000000] Thread (main_thread) [0x00a3d1d0]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
S {Audio Thread} XAudio 2.9 initialized
E {PPU[0x70000001] Thread (CKLoadRequestQueue 0) [0x00a3d710]} 'cellFsOpen' failed with 0x8001002c : CELL_EMFILE
E {PPU[0x70000001] Thread (CKLoadRequestQueue 0) [0x00a3d710]} 'cellFsOpen' failed with 0x8001002c : CELL_EMFILE
E {PPU[0x70000001] Thread (CKLoadRequestQueue 0) [0x00a3d710]} 'cellFsOpen' failed with 0x8001002c : CELL_EMFILE
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 0)

**Comment by raven02** [comment]
Which previous version work for you using Vulkan backend then ?

**Comment by ScorchEmber256** [comment]
Turning off Hook Static Functions seemed to fix the issue. I thought it was used as a debugging option. This issue is invalid. xD

**Comment by raven02** [comment]
Alright. i'm closing it then.
