### ISSUE TITLE
GL/Vulkan: TLoS: Dawn of the Dragon texture Problem

### ISSUE THREAD

**Issue by ScorchEmber256** [RPCS3/rpcs3#2204]
Build: Latest Master 8454949e
OpenGL: Some Textures render completely black, including loading screen. Ingame footage shows that textures change from their normal colour to black. Happens also when a new effect is loaded into the scene. 
Frame-rate drops immensely when texture glitches out too.

Log: 
U {PPU[0x70000000] Thread (main_thread) [0x00a3dab0]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x70000000] Thread (main_thread) [0x00a3db70]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x70000000] Thread (main_thread) [0x00a3d1f0]} cellGcmSys TODO: cellGcmSetGraphicsHandler
E {PPU[0x70000000] Thread (main_thread) [0x00a3d1d0]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
S {Audio Thread} XAudio 2.9 initialized
E {PPU[0x70000001] Thread (CKLoadRequestQueue 0) [0x00a3d710]} 'cellFsOpen' failed with 0x8001002c : CELL_EMFILE
E {PPU[0x70000001] Thread (CKLoadRequestQueue 0) [0x00a3d710]} 'cellFsOpen' failed with 0x8001002c : CELL_EMFILE
E {PPU[0x70000001] Thread (CKLoadRequestQueue 0) [0x00a3d710]} 'cellFsOpen' failed with 0x8001002c : CELL_EMFILE
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 0)
E {PPU[0x70000000] Thread (main_thread) [0x00a3d1d0]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {PPU[0x70000000] Thread (main_thread) [0x00a3d1d0]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 0)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 0)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 0)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 0)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 0)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x39 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x39 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)

<img width="960" alt="spyro texture flush" src="https://cloud.githubusercontent.com/assets/13728013/19308147/752c2572-90c1-11e6-8baa-56fc076df473.PNG">
<img width="960" alt="spyro texture normal" src="https://cloud.githubusercontent.com/assets/13728013/19308148/752e6a76-90c1-11e6-8965-abe2e7818719.PNG">

**Comment by kd-11** [comment]
Related to missing RSX shader decompiler instructions. I'm working on them.
https://github.com/RPCS3/rpcs3/issues/2194
https://github.com/RPCS3/rpcs3/issues/2193

**Comment by kd-11** [comment]
If you were experiencing flickering, recent commit may have fixed it

**Comment by raven02** [comment]
@ScorchEmber256 , can you check again to see if it is fixed?

**Comment by raven02** [comment]
@JohnGodgames , just wonder do you have this title from your inventory ? and can help to test with latest build .

**Comment by ScorchEmber256** [comment]
Nothing has been changed since recent commits

**Comment by JohnGodgames** [comment]
I think that we can close this issue https://www.youtube.com/watch?v=kR3bLZbzyOg

**Comment by B1ackDaemon** [comment]
Let's close this, then :)
