### ISSUE TITLE
DX12/GL/Vulkan: Worms Crazy Golf

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2205]
Tested in https://github.com/RPCS3/rpcs3/commit/8454949eea9d0fc9da55b719e9a02f5a022fd5f5.

**DX12/OGL/Vulkan:** Can reach main menu.
![](http://i.imgur.com/jj3WREJ.png)
[Shaderlog DX12](http://www.mediafire.com/file/6gp1e9xcm8gv5bg/Shaderlog_WCG_15-10-16_DX12.rar)
[Shaderlog OGL](http://www.mediafire.com/file/w2q1ckbtwd1hfyv/Shaderlog_WCG_15-10-16_OGL.rar)
[Shaderlog Vulkan](http://www.mediafire.com/file/s66l6et2sbcz6sr/Shaderlog_WCG_15-10-16_VK.rar)
[Renderdoc Vulkan](http://www.mediafire.com/file/w5v5j6a56t70283/Renderdoc_WCG_VK.rar)

**Comment by sirdanielk** [comment]
Why do you post things like that. Isn't the forum for posting games progress? You didn't write here any particular error, that might be interesting or curious for developers. This board is for resolving issues and not for blogging. Here is the nice place http://www.emunewz.net/forum/forumdisplay.php?fid=162  where you can show the emulation state of your games.

**Comment by raven02** [comment]
Closed

**Comment by MarioSonic2987** [comment]
Updated with error.
