### ISSUE TITLE
GL:  Dragon Ball Z: Burst Limit 

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2208]
@kd-11 
@raven02 

Very old regression by Vlj in openGL and still not fixed yet.
<img src="http://www.fotoszok.pl/upload/0c34c225.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/9e25256c.jpg" alt="Fotoszok.pl" />

**[Shaderlog-GL](https://mega.nz/#!1ZxSXQab!ddar1JaeIaDJUSIjzSZm0W3ILdD0zhtL5VYTeW1AD8c)**
**[RenderDoc-GL](https://mega.nz/#!MRZFhL6A!Qp3khmMVxPBSkRflxbah4IxVoCMYQHIIS1tBjgWm9Pw)**

**Comment by kd-11** [comment]
Can you retest with current master? This bug reminds me of the ones that I've just fixed.

**Comment by SakataGintokiYT** [comment]
**[2c803dbe]**
Still broken

**Comment by kd-11** [comment]
The game is uploading broken mipmaps. The output is fine if mipmapping is disabled by always referencing level 0. This might be a quirk specific to this game, attempting to upload broken dxt5 miplevels. I'll need a more generic test case for this. Does it render correctly on vulkan?

**Comment by kd-11** [comment]
I suspect texel block alignment is broken here. Ignoring lesser miplevels gives correct result:
![image](https://cloud.githubusercontent.com/assets/15904127/19598082/75d77efe-97a1-11e6-9b25-acc2e5eef9ff.png)

Is there any other regression caused by that commit?

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.365
Also, if it works, confirm it doesnt break other games. I might optionally tweak it a bit to only use the double copy is the pitch does not match the width, which should make uploads a bit faster.

**Comment by raven02** [comment]
It looks good though it is not correct as Vulkan and DX12 backend .

**Comment by SakataGintokiYT** [comment]
@kd-11 
Not works effect of energy 
<img src="http://www.fotoszok.pl/upload/fea4a232.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
Is the depth effect correct on vulkan?

**Comment by kd-11** [comment]
Something seems off with computation of the blur kernel offsets. Maybe another broken attribute?

**Comment by kd-11** [comment]
Does https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.371 change anything?

**Comment by raven02** [comment]
Just checked .It is the same .

**Comment by SakataGintokiYT** [comment]
Fixed by #2861

**Comment by hcorion** [comment]
FYI @SakataGintokiYT you only close issues after the PR has been merged.
