### ISSUE TITLE
GL : GL_ARB_shader_draw_parameters' is not supported (Intel Specific)

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2209]
It only affects intel platform where GL_ARB_shader_draw_parameters is not supported . 

```
F {rsx::thread} class gl::glsl::compilation_exception thrown: compilation failed: 
'WARNING: 0:3: '#extension' :  'GL_ARB_shader_draw_parameters' is not supported
ERROR: 0:? : 'gl_DrawIDARB' : variable is not available in current GLSL version 
ERROR: 0:9: 'GL_ARB_shader_draw_parameters' :  extension is disabled or not available
```

**Comment by kd-11** [comment]
Wow, there are modern cards without this extension! I'll add an option to not initialize the text output subsystem is debug overlay is not selected as well as check for the extension manually at initialization

**Comment by raven02** [comment]
I also just found out on another PC which use Intel GPU .Indeed , it didn't support lots of other extension.s

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/2212
