### ISSUE TITLE
rpcs3 Fatal Error

### ISSUE THREAD

**Issue by ikhalief14** [RPCS3/rpcs3#2210]
I get this error every time i start to boot the game.
My PC spec:
Intel core 2 duo 6420 2.13 ghz
Ati radeon HD 5450 2gb
4gb ram

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000038 at 0000000077f85590.
Instruction address: 0000000077f85590.
Module name: 'atio6axx.dll'.
Module base: 0000000076160000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

**Comment by AniLeo** [comment]
These kind of reports are useless without a stack trace / log, please use the forums
http://www.emunewz.net/forum/forumdisplay.php?fid=162
