### ISSUE TITLE
Renderer Null using GLSL vertex compiler

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#2211]
Just noticed the following on a log that was posted on the forums

``Renderer: Null
``

``·F {rsx::thread} class gl::glsl::compilation_exception thrown: compilation failed: 'Vertex shader failed to compile with the following errors:``
``ERROR: 0:9: error(#143) Undeclared identifier: gl_DrawIDARB``
``ERROR: 0:9: error(#166) Integer expression required: []``
``ERROR: error(#273) 2 compilation errors.  No code generated``

It crashes with an unhandled Win32 exception 0xC0000005.
Thread: http://www.emunewz.net/forum/showthread.php?tid=175581

Is this supposed to happen?

**Comment by kd-11** [comment]
Kinda. That GPU does not support ARB_shader_draw_parameters and is most likely and ancient (pre-fermi or pre 7000 series AMD or and intel iGPU). I'll submit a fix disabling initialization debug overlays if the extension is not available or the option is not checked.

**Comment by kd-11** [comment]
See https://github.com/RPCS3/rpcs3/issues/2209

**Comment by sirdanielk** [comment]
@kd-11 Yes please do it. Old crads are still useful for some degree.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/2212
