### ISSUE TITLE
DX12/GL/Vulkan：Catherine graphical issue

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2214]
OpenGL
![qq 20161019223822](https://cloud.githubusercontent.com/assets/20301499/19540607/3b1fcd3e-9693-11e6-8b74-24fb85106989.jpg)
vullkan
![qq 20161019223815](https://cloud.githubusercontent.com/assets/20301499/19540625/57c8bf22-9693-11e6-8eaa-152675ff78c8.jpg)
dx12
![qq 20161019223827](https://cloud.githubusercontent.com/assets/20301499/19540631/607d142e-9693-11e6-9620-96075be2feb2.jpg)
version：
RPCS3 v0.0.1-4779-9b72ff9 Pre-Alpha
(Zangetsu38 18-10-16)
 OpenGL video： https://youtu.be/AYdvP78lyg0
log：https://drive.google.com/open?id=0B4z-S0oOZ2FgYnVDX2hyT1RiRDQ

**Comment by raven02** [comment]
I suppose GL one is correct . Correct me if i'm wrong

**Comment by RainKikyou** [comment]
log：https://drive.google.com/open?id=0B4z-S0oOZ2FgYnVDX2hyT1RiRDQ
intro game
![qq 20161020185010](https://cloud.githubusercontent.com/assets/20301499/19557744/b5d40098-96f9-11e6-85b1-b2319ec0690a.jpg)

**Comment by SakataGintokiYT** [comment]
This game working on master build ? 
Can you try

**Comment by RainKikyou** [comment]
master build can  not  work

**Comment by Nezarn** [comment]
@RainKikyou @raven02 then why even bother reporting it, maybe it happens because the hacks in that build. (and i thought we should only report issues from master builds?)

**Comment by raven02** [comment]
I will close this thread since it is not working in master build and no way we can debug it .

**Comment by RainKikyou** [comment]
I should not do that, But naruto from the hack build can work to today's master build still exists the same graphics problem.Later, the master build can work but may appear with the hack build of the same graphics problem, may have no problem, I hope the latter.
Ps: This game can be loaded in the master build

**Comment by ssshadowww** [comment]
The game does work on the master build, you just need different settings and some... finesse to run it. Let me make a new bug report with more details and a renderdoc trace.

**Comment by RainKikyou** [comment]
@raven02 
can It has been determined that mast build can work，it's here：http://www.emunewz.net/forum/showthread.php?tid=175609
We need to re-open，In the video  can see a more detailed graphics problem
hack build-vullkan video：https://youtu.be/H8GIDgzB4ek
master build-opengl video：https://youtu.be/P6sAsONNoXU

**Comment by ssshadowww** [comment]
Long story short, the game works on master too: http://www.emunewz.net/forum/showthread.php?tid=175609
It seems completely playable. On Vulkan and DX12 it looks fine except that 3D is squeezed to half the screen. (OpenGL has a few more visual bugs).
Now I can't get a renderdoc trace because the game slows down to 0 fps. In fact every single game just looks like garbage when I capture. Here is just one example (from another game, but same principle). What am I doing wrong?
![2016-10-21 20_26_58-fps_ 1 70 _ opengl _ atelier ayesha_ the alchemist of dusk _ bles01793](https://cloud.githubusercontent.com/assets/3323620/19612733/9416c8c4-97e8-11e6-822d-1c3d694c5de7.png)

**Comment by Nezarn** [comment]
@ssshadowww i think in ogl you need to turn on the new legacy option for capturing (if i remember right)

**Comment by ssshadowww** [comment]
Yes, that was the problem. Here is the renderdoc trace from the main menu. You can clearly see that the scene looks fine during most of the drawing but somewhere near the end it's squished together. 
https://mega.nz/#!UxkwhBjZ!AQaG7LiRJbFlOJj7ek2MSiugzt62fAkMKLCAp8CshzY

**Comment by kd-11** [comment]
This bug seems to be due to our handling of unnormalized texture sampling or how we present available buffer sizes to applications. The app passes coords in the 0-2560 range for x and 0-720 for y while we only have a 1280x720 texture, making 2560 double width, and therefore half the sceen is blank.

**Comment by RainKikyou** [comment]
This game can not use the handle，use only the keyboard，If  use the handle will crash in this interface
![qq 20161025074258](https://cloud.githubusercontent.com/assets/20301499/19667986/02c62544-9a87-11e6-8cbb-666cdbfc3dd4.png)

**Comment by raulpetru** [comment]
@kd-11 Any progress with this issue? Please re-open it and have a look at it when you have time. Keeping it closed just cuts our hope :(

**Comment by Nezarn** [comment]
@raulpetru in case you didn't noticed, rpcs3 is basically dead. (last commit was at Oct. 20, core devs are long gone, 2 of them are making their own ps3 emulator, 1 just stopped working on stuff)

Aside from RSX and renderer stuff, there wasn't any work on rpcs3 since august.

PS: and I guess kd-11 is busy with real life or can't figure out whats broken. (you you're better off playing on your real PS3)

**Comment by raulpetru** [comment]
@Nezarn yeah I noticed but hoped it was something else but not dead :/
Is there anything public about that other ps3 emulator that you just mentioned?

It's quite sad because rpcs3 got pretty far. Hopefully ps3 emulators will exist in the future.

**Comment by B1ackDaemon** [comment]
@Nezarn to clarify a bit something here:
AlexAltea - not heard from him about Nucleus for a while.
DH - atm started researching/reversing ps4-related stuff.
Hykem - completely quit from any IT-related stuff after legal troubles.

**Comment by kd-11** [comment]
For clarification: I haven't had time to work on anything the past few months due to work, but things will lighten up eventually. Hopefully, I'll be back working on this before the year ends.

**Comment by Nekotekina** [comment]
I started one "big" task in August, it's effectively suspended atm.

**Comment by kd-11** [comment]
#2357 has been merged.
