### ISSUE TITLE
Feature: Multiplayer input support (NOT Netplay)

### ISSUE THREAD

**Issue by min050820** [RPCS3/rpcs3#2215]
Is it possible to add multiplayer input support, like keyboard as 1p and X-input joypad as 2p?

Though I'm not expecting you to make this right away, this feature is being important as the number of playable game is increasing.

**Comment by lightfirst** [comment]
well, it's possible. As 2 x-input working now, if you want multiplayer you just need anotehr x-input joypad.

**Comment by min050820** [comment]
@lightfirst Yes, I know that. But that requires TWO gamepads. It should be possible to use keyboard and gamepad at the same time!

EDIT: https://github.com/mob41/rpcs3/commits/master
This guy seems to have implemented such thing. But I have no idea if it's working or something. If it's working and passed code review, can it be merged to here?

**Comment by scribam** [comment]
@min050820 I think your request has been implemented in #3283 which is now in master. Can you check if it is what you have expected?

**Comment by Zangetsu38** [comment]
yes, but you have any idea for maybe play with friend in only with this ? so send screen game and can emulate controller friend in pc, same like Share play with PS4 :D

**Comment by Sora3100** [comment]
If you have an nvidia card you can use nvidia share's beta feature, or gamestream @Zangetsu38

**Comment by AniLeo** [comment]
This has indeed been implemented in #3283 , closing
