### ISSUE TITLE
Feature: Cheats Option

### ISSUE THREAD

**Issue by BesuBaru** [RPCS3/rpcs3#2216]
Will it be possible for a future build of RPCS3 to have the option to load cheats from a text file, simillar to how Dolphin, PPSSPP, and PCSX2 does the job?

It would be pretty nice to have a cheat option for things like framerate hacks, and other cool things like trainers.

**Comment by HexyFify** [comment]
i would say it won't be necessary at this point since we already have a universal cheat tool.
though i don't think the idea is out of the question since cheat engine doesn't support Linux
https://www.cheatengine.org/

**Comment by isshininu** [comment]
ugh

**Comment by MSuih** [comment]
Isn't this already implemented with the patch.yml system?

**Comment by Margen67** [comment]
@MSuih Unless patches can freeze values, no.

**Comment by kd-11** [comment]
Pretty sure things like 'freezing values' are doable with patches (just NOP the modifying instruction). The patch system gives the power to do so.

**Comment by awsdert** [comment]
But NOP doesn't allow us to find the values to begin with, at least a basic search interface with a memory editor would be appreciated, would make it so much easier to identify stuff since rpcs3 would already know whether things were left in BigEndian mode or changed to LittleEndian mode
