### ISSUE TITLE
Can Anyone Help With This Log?

### ISSUE THREAD

**Issue by ScorpionPatch** [RPCS3/rpcs3#2217]
I Recently Downloaded RPCS3, and I'm Still trying to understand and learn that LLE Module Thing, but when i try to play one of my games, it says that in the log, o try i couple of tutorials but none of then Works for me, can anyone help to proceed? Wich ones LLE's should i pick to try to run not only my WWE Smackdown Vs. Raw 2008, but Other's like the PSN Classic Golden Axe that i was trying to test on that emulator.

The log of Smackdown Vs. Raw 08

E {PPU[0x1] Thread (main_thread)[0x009687bc]} cellSysmodule TODO: cellSysmoduleSetMemcontainer(ct_id=0xd)
E {PPU[0x1] Thread (main_thread)[0x001f7540]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0x40f, alignment=0x0, alloc_addr=*0xd007f850)
E {PPU[0x1] Thread (main_thread)[0x0096a15c]} sys_mmapper: sys_mmapper_map_memory(addr=0x8000000, mem_id=0xf, flags=0x40000)
E {PPU[0x1] Thread (main_thread)[0x0096a15c]} sys_mmapper: sys_mmapper_map_memory(addr=0x9600000, mem_id=0x10, flags=0x40000)
E {PPU[0x1] Thread (main_thread)[0x002000d8]} Exception: Access violation writing location 0x9600000
(in file ..\Utilities\Thread.cpp:1122, in function _se_translator)

**Comment by Nezarn** [comment]
For issues like this use forum http://www.emunewz.net/forum/forumdisplay.php?fid=163
