### ISSUE TITLE
rsx: Broken vertex shader in atelier games

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#2218]
http://www.emunewz.net/forum/showthread.php?tid=174851
The game seems to generate a somewhat broken broken vertex shader (attached)
[mureru_vs.txt](https://github.com/RPCS3/rpcs3/files/547522/mureru_vs.txt)

**Comment by ssshadowww** [comment]
Here is a renderdoc capture of a scene with a correct looking character in it. As with the scene outside all geometry around him seems to have taken the form of a thin vertical line. 
https://mega.nz/#!Ns8yFaAL!k8kGLOJl4jdBw6tOZ9GMEhvFc1cBFqi-oY3OHSovANU

**Comment by kd-11** [comment]
Well, this supports my hypothesis about being off-by-one instruction on some conditional instructions.
![image](https://cloud.githubusercontent.com/assets/15904127/19644007/17d670ec-99f6-11e6-89f4-b33208efd826.png)
The game uploads part of the transform matrix as an attribute and rebuilds it in the VS.

**Comment by ssshadowww** [comment]
Well I have nothing to add to that, good job, you figured that out very quickly. If you want to look at the other Atelier games just tell me. They all have some graphical bugs here and there (and they all get stuck in endless loops at random which means you have to restart several times to get anywhere). 

Also don't know if you saw it but Catherine (in the master build contrary to other comments) has a similar looking issue to this game where geometry is squished down, no idea if it's the same bug or not. https://github.com/RPCS3/rpcs3/issues/2214#issuecomment-255478134

**Comment by RainKikyou** [comment]
Yes, look at the video under the totori of the same get stuck in endless loops at random
https://youtu.be/mmt95Yxgs88

**Comment by kd-11** [comment]
@ssshadowww @RainKikyou Retry with https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.372/artifacts
If its still broken, attach the opengl shader logs.

**Comment by al0xf** [comment]
The game works as usual right up to the point where it will first display some 3D graphics, then my graphics driver (and rpcs3) crashes.
Log: https://mega.nz/#!Nx1EiT4a!3Jls1FRiavleSslKuWQ_28xNwMHtI77013utawad01Y
![2016-12-15 11_11_41-greenshot](https://cloud.githubusercontent.com/assets/11020872/21220082/a8207a00-c2b7-11e6-9846-28d58442e59c.png)

**Comment by ssshadowww** [comment]
The game works as usual right up to the point where it will first display some 3D graphics, then my graphics driver (and rpcs3) crashes.
Log: https://mega.nz/#!Nx1EiT4a!3Jls1FRiavleSslKuWQ_28xNwMHtI77013utawad01Y
![2016-12-15 11_11_41-greenshot](https://cloud.githubusercontent.com/assets/3323620/21220183/06e8e4c8-c2b8-11e6-842e-174f0cd3d93f.png)

**Comment by kd-11** [comment]
Lol. Thats was my mistake. I overcomplicated a simple matter.
Try https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.373/artifacts

**Comment by ssshadowww** [comment]
That works!
Log file if you need it: https://mega.nz/#!A1Vw1DzT!TkvOA3UiPX8oKlV7v1VmdHLsM9_BJNW6_XglQl-nPFg
There are of course some other issues with lighting/shadows (in all Atelier games) and they of course hang at random fairly quickly, but this bug is fixed now.

**Comment by kd-11** [comment]
Fixed via https://github.com/RPCS3/rpcs3/issues/2237
