### ISSUE TITLE
Feature : per game configuration  

### ISSUE THREAD

**Issue by SSV-Normandy** [RPCS3/rpcs3#2219]
could the simulator save and auto change LLE settings when start different games

**Comment by AniLeo** [comment]
That was a thing (individual config for each game) but hasn't been reimplemented yet since of 0.0.0.9

**Comment by RainKikyou** [comment]
OMG！This requires collecting the correct selection of lle settings for each game, such as pcsx2 widescreen patch, one can imagine the workload is huge

**Comment by SSV-Normandy** [comment]
I mean the simulator saves the users' config for different game, the config is still set by users, not collected by simulator.

**Comment by RainKikyou** [comment]
This is the way, did not look at the wrong understanding. Then you said it should not be difficult to achieve，now has a lle search feature
ps: I said above is what I expect, maybe in the future can be achieved

**Comment by Nekotekina** [comment]
This "feature" exists right now. You just cannot access it via GUI. And you can just enable most of the usable LLE modules and it will work for most cases.
I can only remember libfs which may require specific on/off.
> simulator
We usually call it "emulator".

**Comment by MarioSonic2987** [comment]
Can this issue be closed since it has been implemented?
