### ISSUE TITLE
RSX Driver Error 

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2220]
@kd-11 
@raven02 
-Teenage Mutant Ninja Turtles: Out of the Shadows [NPUB31217]-->[Log](https://mega.nz/#!QNYCFTwB!abcZ9ctgr0gIixjpZnWWy_gZOWsVLgGRSae6HihewBE)
-Mortal Kombat [NPEB90327]-->[Log](https://mega.nz/#!NNIn1bRA!jZmgIYKVUAuCBPDV5lbgzTvd4oiRGIzlekTUbQc0QYY)
-Magus [BLUS41042]-->[Log](https://mega.nz/#!oNBnQDID!O87F1U8LLXwtKmbAZvSUITs9rV_SPzqBkenYQmyipx8)
-Marvel Super Hero Squad Comic Combat [BLUS30813]-->[Log](https://mega.nz/#!BIhUBAyS!q2TQjD1cQs5HM76rg-OZd73mrOdm19BSS1ARFqZWhWE)
-WARP [NPEB00636]-->[Log](https://mega.nz/#!8RIQRBCS!PWlV2yWcjwzMZOhy7PtUrSfSJuljemiUrhQ41ZITEQI)
-Rock of Ages [NPEB00669]-->[Log](https://mega.nz/#!QcI0QDBS!1iiFBTfunu_2alxG0LJ7P9ViiBKdXViPSyZTTQvkkVc)
-Flashback [NPUB31265]-->[Log](https://mega.nz/#!FJ5yFDqI!LbNpWGjRrlwDdgKtT9u3ERQX2QMJlHuwcAADEdCkkfU)
-Dead Block [NPEB00461]-->[Log](https://mega.nz/#!xBJkyaYA!bvqSi4_S0NGP5ho_s0zpGIjZgFTWLWBRSOSLDQwAd8w)
-Choplifter HD NPUB30619-->[Log](https://mega.nz/#!Ich1gQKK!S_nwbRTiRYclbTu3ZK1wrCXggYj9sRulsLF-VHpF7A8)
-Brothers [NPEB01201]-->[Log](https://mega.nz/#!9UxTgQrJ!ItLdF6XDI6exBLodLTNkboaOZ11QQOz47AtqbQF6z84)
-Master Robot [NPUB31462]-->[Log](https://mega.nz/#!oZhBCaJD!i6Oam9jDn3Et42UvEnl3ah7FvVNFvgqOv_Cu2QLYT3Y)

```
[Vulkan]
E {rsx::thread} RSX: ERROR: [Driver] Code 0 : vkCreateImage: image creation failed due to invalid parameter
F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is C4650B07h
```

```
[OpenGL]
F {rsx::thread} class std::logic_error thrown: 0x8cd6
```

```
[DX12]
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000000 at 0000000000410793.
Instruction address: 0000000000410793.
Function address: 0000000000410600 (base+0x400600).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

```

**Comment by kd-11** [comment]
This requires deeper investigation. When I get to this bug, I'll update with a build that dumps image creation debug info so we can take a deeper look.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/issues/2234 May have fixed this. I suspect illegal resolutions were being set resulting in framebuffers with invalid dimensions. Please retest.

**Comment by SakataGintokiYT** [comment]
@kd-11 Yep this issue is fixed

**Comment by OverlordCW** [comment]
I just got this in RDR with Vulkan.

E {rsx::thread} RSX: ERROR: [Driver] Code 0 : vkCreateImage: image creation failed due to invalid parameter
F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is C4650B07h

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/981591/RPCS3.zip)
