### ISSUE TITLE
Rendering problems with Project DIVA - Dreamy Theater 2nd / extend, Virtua Fighter 5 and maybe other Sega games.

### ISSUE THREAD

**Issue by RaulDJ** [RPCS3/rpcs3#2221]
So, these games can now render almost 100% correctly, but there're still some problems that seem to be related to lightning.

For comparison, here's the same scene on:

The PS3: http://i.imgur.com/qgBHwNG.png
and on the emulator: http://i.imgur.com/H7V8lrl.png

We also have some more strange looking problems like this one, with glowing yellow things on the character clothes: http://i.imgur.com/TV8r8Yg.jpg 

This last one is explained here https://github.com/RPCS3/rpcs3/issues/2221#issuecomment-259701915 by @Waelwindows .

Recent Renderdoc: https://my.mixtape.moe/lmlcpk.7z

**Comment by RainKikyou** [comment]
This should be the same lightning problem?
![2a81fe1f4134970a8d0d49e29dcad1c8a6865d57](https://cloud.githubusercontent.com/assets/20301499/20121407/32ef0f30-a64c-11e6-8ab6-cb2a503bd395.jpg)

**Comment by RaulDJ** [comment]
That I'm not sure. What we know is that all the games that run with the same Sega engine are affected.

By the way @kd-11, are you still alive...?

**Comment by RainKikyou** [comment]
Well, then I should open a new post

**Comment by Waelwindows** [comment]
The glowing glitch is just a problem with the shader not able to swizzle the alpha channel correctly
for example, here i have the skirt's glow texture:
https://puu.sh/sdjeC/ba64dc2f11.png
what shader attempts to do is to get the alpha channel, but instead it gets 1 (fully opaque)
which makes the texture look like this (not entirely correct as i had to re-create it in photoshop)
https://puu.sh/sdjEi/447f195a76.png

**Comment by RaulDJ** [comment]
@Waelwindows 

So the yellow glowing things don't have anything in common with the general "lightning" problem?

**Comment by Waelwindows** [comment]
@RaulDJ in short yes

**Comment by RaulDJ** [comment]
@Waelwindows Thank you, I will correct my post now.

**Comment by kd-11** [comment]
Given the example produced by @Waelwindows we have some image formats that have incorrect interpretation. I'll return to rpcs3 contributions as soon as work lightens up. By the way, can someone post a trace of that glow error? I've seen similar bugs on some other titles where post-process bloom is overbright.

**Comment by RaulDJ** [comment]
Thank you very much, @kd-11 

Here's a Renderdoc of that in case it helps: https://aww.moe/rryiac.7z

**Comment by RaulDJ** [comment]
I would like to give this one some visibility again.

Recently, these games run at almost perfect 60 FPS with no sync issues anymore, so these graphical bugs are the last thing remaining.

**Comment by AniLeo** [comment]
Retest with master.
If it's still an issue, you need to update the issue with recent RenderDoc or log if there's useful information in it.

**Comment by RaulDJ** [comment]
@AniLeo Yes, every single graphic-related problem with these two games are happening right now exactly as they happened more than a year ago , nothing changed whatsoever. Logs apparently are useless in this case.

Here's a recent Renderdoc:

**Comment by tominfhl** [comment]
So new to this but how can I help provide info on this issue. If this is fixed would it fix the shading issues in Virtue Fighter 5 Final Showdown?

**Comment by RaulDJ** [comment]
@tominfhl I think so, as they apparently use the same engine.

**Comment by tominfhl** [comment]
@RaulDJ  Man ... these games are solo close to perfect ... just this one last thing.

**Comment by RaulDJ** [comment]
@tominfhl Yeah, tell me about it. I've been waiting for more than a year for some fixes but all the developers did in that period fixed nothing in these games except performance.

**Comment by RaulDJ** [comment]
@AniLeo could you please add the tags "Vulkan" and "OpenGL" as it happens on both renderers?
Here's a log on Vulkan that goes from game boot until a song finishes loading: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1400203/RPCS3.zip)

Finally, please tell me what else to do in order to drop the "needinfo" tag, I'll give any information needed.

**Comment by tominfhl** [comment]
@kd-11, @AniLeo,  @Waelwindows ...Very keen on this too ... let me know what I can do to help.

**Comment by RaulDJ** [comment]
Here's a Renderdoc of 2nd on a stage where even the backrgound has broken shit (some plants): https://my.mixtape.moe/rgzprq.7z

Aside from lighting, the character has some weird textures too, similar to @Waelwindows commented last year.

**Comment by tominfhl** [comment]
Congrats on the new rpcs3 announcements! You guys are doing a great job. Interesting that  none of the recent enhancements touched these issue. Is it some obscure use of the RSX chip by Sega that is not general enough to be resolved with other improvements?

**Comment by RaulDJ** [comment]
@tominfhl Well, not a single update in this past year changed anything related to these problems so I don't think that these latest improvements doing nothing about theme is strange whatsoever, lol. Clearly is something particular to these games' engine that has to be specifically adressed, and that never happened, sadly.

**Comment by cal321** [comment]
I want to contribute by describing my experience with Virtua Fighter 5 Final Showdown.
The colors aren't displayed correctly. Running Vulkan, a lot of stuff that is supposed to be white is displayed as red:

https://imgur.com/a/Z3yOg

With OpenGL, the floor of the stage seems better, but the character's skin is still too orange.
Speed and FPS-wise Vulkan runs smoothly, OpenGL is slow motion mode.

Here is some red text that I ran into when I compiled the game and ran it in Vulkan afterwards:

https://imgur.com/a/4UviP

my PC: i5-6500, GTX 1050 Ti, Win 10, 12GB Ram

**Comment by tominfhl** [comment]
Gents/ladies ... it looks like there had been some progress .... https://youtu.be/UKTiohYXgeA

**Comment by RaulDJ** [comment]
OH MY FUCKING GOD EVERYTHING IT'S FUCKING FINALLY FIXED AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHH!!!!

**Comment by tominfhl** [comment]
I know right! Finally some love.

**Comment by RaulDJ** [comment]
Yeeeeeah, here's my obligatory celebration video: https://youtu.be/GAM9Z0vCYR4

**Comment by AniLeo** [comment]
Is it fixed on master? If yes, close issue

**Comment by RaulDJ** [comment]
@AniLeo Both Mikus are certainly fixed in this matter, but I don't know about the other games. Do I close the issue anyway?

**Comment by kd-11** [comment]
I'm closing it since its very likely they are all fixed. At least vf5 and the miku games are, the rest should have their own ticket since the bug is likely not related.

**Comment by RaulDJ** [comment]
@kd-11 Do we have to open another one for that issue?
