### ISSUE TITLE
Need soem help

### ISSUE THREAD

**Issue by JeffHorinzon** [RPCS3/rpcs3#2222]
Heres a log of the issue when I try to load a game called Hatsune Miku: Project Diva - extend.
Log: 
U {PPU[0x70000000] Thread (main_thread) [0x006fc748]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x70000000] Thread (main_thread) [0x006fc868]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x70000000] Thread (main_thread) [0x003afdcc]} HLE TODO: Unimplemented syscall sys_ss_get_open_psid -> CELL_OK
U {PPU[0x70000000] Thread (main_thread) [0x006fbf08]} cellUserInfo TODO: cellUserInfoGetList(listNum=*0x54b7dd0, listBuf=*0x54b7dd4, currentUserId=*0x54b7e14)
E {PPU[0x70000000] Thread (main_thread) [0x006fbae8]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x70000000] Thread (main_thread) [0x006fbae8]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x70000000] Thread (main_thread) [0x006fbae8]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x70000000] Thread (main_thread) [0x006fbae8]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {PPU[0x70000000] Thread (main_thread) [0x006fbae8]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {PPU[0x70000000] Thread (main_thread) [0x006fbae8]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
U {PPU[0x70000000] Thread (main_thread) [0x006fb988]} cellGcmSys TODO: cellGcmSetQueueHandler
U {PPU[0x70000000] Thread (main_thread) [0x006fbc48]} cellResc TODO: cellRescInit(initConfig=*0xd0057a88)
U {PPU[0x70000000] Thread (main_thread) [0x006fbcc8]} cellResc TODO: cellRescVideoOutResolutionId2RescBufferMode(resolutionId=1, bufferMode=*0xd0057a68)
U {PPU[0x70000000] Thread (main_thread) [0x006fbba8]} cellResc TODO: cellRescSetDsts(dstsMode=0, dsts=*0xd0057a6c)
U {PPU[0x70000000] Thread (main_thread) [0x006fbbc8]} cellResc TODO: cellRescSetDisplayMode(displayMode=0)
U {PPU[0x70000000] Thread (main_thread) [0x006fbc68]} cellResc TODO: cellRescGetBufferSize(colorBuffers=*0xd0057a68, vertexArray=*0xd0057a64, fragmentShader=*0xd0057a54)
E {PPU[0x70000000] Thread (main_thread) [0x006fbae8]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
F {PPU[0x70000000] Thread (main_thread) [0x003bf598]} class std::runtime_error thrown: Trap!
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:1837)

My backend is Vulkan and yes it is supported because I tested on other games,  Just this particular game I have issue with.  Pardon me if I'm dumb :)

**Comment by raven02** [comment]
Please check this out in http://www.emunewz.net/forum/forumdisplay.php?fid=162

**Comment by JeffHorinzon** [comment]
Thanks :)
