### ISSUE TITLE
VK/GL: Tales Of Xillia 1/2 graphics issue

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2223]
As this picture
In the video, we can see more clearly the graphics problem
https://www.youtube.com/watch?v=CYUc2Ofhv8k
If  need to caputure, I will upload
![32ef0f30-a64c-11e6-8ab6-cb2a503bd395](https://cloud.githubusercontent.com/assets/20301499/20162864/ecd0452c-a732-11e6-9c2e-bedc2d94cc9c.jpg)

**Comment by kd-11** [comment]
@RainKikyou Yes, please provide a capture.

**Comment by RainKikyou** [comment]
OK.
https://drive.google.com/open?id=0B4z-S0oOZ2FgT1F6eVZpTXhjNEE
![qq 20161111114325](https://cloud.githubusercontent.com/assets/20301499/20203681/5b995774-a804-11e6-95c6-883fd8f93e0e.png)

**Comment by RainKikyou** [comment]
@Nekotekina good job，FPS to upgrade a lot, but the graphics a little bad graphics flash
![qq 20161203035816](https://cloud.githubusercontent.com/assets/20301499/20848488/4ee88968-b90d-11e6-862a-6f923c4579a2.png)
![qq 20161203035904](https://cloud.githubusercontent.com/assets/20301499/20848489/4f19836a-b90d-11e6-9172-ad39f87b572a.png)

**Comment by Nezarn** [comment]
@RainKikyou wtf are you high? The latest commit just added licence to a file, it doesn't affect performance in any way.

**Comment by RainKikyou** [comment]
FPS upgrade looks like only the game, in the old building can only get 20FPS use llvm, in the latest build can not use llvm can reach 30fps (as the above picture)

**Comment by RainKikyou** [comment]
@kd-11 
good job！we can use vullkan in [6f6d0dca](https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.378)
![qq 20161229150926](https://cloud.githubusercontent.com/assets/20301499/21538803/aeb26caa-cddb-11e6-9ccf-f75043750cc6.jpg)
![qq 20161229150931](https://cloud.githubusercontent.com/assets/20301499/21538810/bdc0d4d4-cddb-11e6-889d-90f3d7338f36.jpg)
![qq 20161229151008](https://cloud.githubusercontent.com/assets/20301499/21538812/c6aeb7f0-cddb-11e6-9049-eac1a2b9ab9b.jpg)

**Comment by SakataGintokiYT** [comment]
@RainKikyou  
Can you retest at latest build ? Fix nv3089_image_in [d86d6556]  --> **[Link](https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-3891)**

**Comment by RainKikyou** [comment]
I'm really sorry, I don't have my PC now, I can test the fastest a week later

**Comment by RainKikyou** [comment]
@JohnGodgames
You can try to test

**Comment by AniLeo** [comment]
Someone please retest this

**Comment by RainKikyou** [comment]
The character model does not seem to broken, but there is still the first picture of the skin light problem
video https://www.youtube.com/watch?v=CLw4Yi8FUwo

**Comment by kd-11** [comment]
Still an issue?

**Comment by AniLeo** [comment]
Needs up-to-date information.

**Comment by GeniusMage** [comment]
Graphical issues in those games are fixed.
Only problem left is the text not working, which is a common issue with Vesperia.

![bandicam 2017-09-21 16-40-16-609](https://user-images.githubusercontent.com/27543170/30701990-00a358bc-9eec-11e7-8954-7210854f3ec2.png)
![bandicam 2017-09-21 16-37-27-388](https://user-images.githubusercontent.com/27543170/30702001-08ae91ac-9eec-11e7-9052-3c74e6810e02.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1321630/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Closing as graphical issues related here have been fixed, text is a separate issue

**Comment by marcussacana** [comment]
@AniLeo Already have a issue? what title?
