### ISSUE TITLE
SSE3 instructions on AMD Phenom II X4 945

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#2224]
I've tried to test last build of RPCS3 (https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.3488/artifacts) and when I opened tetris (/dev_hdd0/game/TEST12345/USRDIR/gs_gcm_tetris.elf), RPCS3 showed this:
![1](https://cloud.githubusercontent.com/assets/14265316/20229955/49bd099a-a86a-11e6-8d33-acc57e72defa.png)
This is strange, cause CPU-Z shows that AMD Phenom II X4 945 has the support of SSE3:
![2](https://cloud.githubusercontent.com/assets/14265316/20229987/88c52cee-a86a-11e6-96b2-f6edc92f0c20.png)
But I remember that I'd launched tetris about a year ago and it worked!
OK, I found the build that was made then (https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.955/artifacts). And tetris works on it!
![3](https://cloud.githubusercontent.com/assets/14265316/20230091/14165ef8-a86b-11e6-8805-9e1579ace93c.png)
Can somebody tell me what is this? A bug, downgrade or something else?

**Comment by janisozaur** [comment]
SSE3 != SSSE3

**Comment by TotalCaesar659** [comment]
Damit, I didn't see S. This issue can be closed.
