### ISSUE TITLE
AMD Vulkan bug

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#2225]
I tried to test .elf files (cube, tetris etc) on notebook with AMD Radeon R5 M335, Windows 7 x64, last AMD drivers Crimson Edition 16.11.3.
They are playing in OpenGL normally, but not on Vulkan (graphics may be corrrupted at once or after some time). AMD Radeon R5 M335 has the support of Vulkan.
### Cube (OpenGL)
![cube-opengl](https://cloud.githubusercontent.com/assets/14265316/20239482/ef427e16-a911-11e6-907f-678ee3556634.png)
### Cube (Vulkan)
![cube-vulkan1](https://cloud.githubusercontent.com/assets/14265316/20239484/f5dff4a6-a911-11e6-8e71-a396a51b96d9.png)
![cube-vulkan3](https://cloud.githubusercontent.com/assets/14265316/20239490/2171a5e2-a912-11e6-89a7-2775e774b892.png)
![cube-vulkan2](https://cloud.githubusercontent.com/assets/14265316/20239487/1c40dd22-a912-11e6-8de6-9ae7e01e1ab1.png)
### Tetris (OpenGL)
![tetris-opengl](https://cloud.githubusercontent.com/assets/14265316/20239492/27c40156-a912-11e6-8215-6a5688e2438b.png)
### Tetris (Vulkan)
![tetris-vulkan](https://cloud.githubusercontent.com/assets/14265316/20239502/46a779d6-a912-11e6-8787-777e866e4996.png)
![tetris-vulkan2](https://cloud.githubusercontent.com/assets/14265316/20239504/490f66ca-a912-11e6-89cd-d5407ce4cbe3.png)
And this happens with other .elf's. Is this a bug?

**Comment by kd-11** [comment]
Tetris on vulkan highlights broken line loop rendering; I might fix it if time allows. The other issue in the screenshots seems to be related to windowing. This is expected if you have dwm disabled and is a limitation of the old window manager in windows before win8

**Comment by TotalCaesar659** [comment]
Thanks for the answer.
I've installed Windows 10 on a separate partition and tried it again.
Cube works great, but after some time it stands and the picture gets broken too, if I drag it (maybe it's because of opening another windows).
![2](https://cloud.githubusercontent.com/assets/14265316/21283823/4872c15c-c41b-11e6-99da-ae4f9579293d.png)
Tetris has the same result, but without broken picture.
![1](https://cloud.githubusercontent.com/assets/14265316/21283768/bba623be-c419-11e6-8ad7-8d33399dea63.png)
I hope you'll fix it on both systems, cause I don't know a reason to test some bigger games. Maybe this bug affects on them too.

**Comment by AniLeo** [comment]
Can you retest this? @TotalCaesar659

**Comment by TotalCaesar659** [comment]
This bug is gone, it may be closed now, I guess.

**Comment by mirh** [comment]
Emulator's improvements or new drivers merits?

**Comment by AniLeo** [comment]
I'm almost certain it's an improvement since there were some big improvements on Vulkan, but if you want to be sure go to build history on rpcs3.net, grab a build close to the date of the issue and test both that build and latest with la.. up-to-date drivers

**Comment by TotalCaesar659** [comment]
For the record: I've tested it on Windows 10 x64, AMD drivers Crimson Edition 17.4.4, RPCS3 build https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-4717
