### ISSUE TITLE
It's interrupting build as wx/wx.h isn't found

### ISSUE THREAD

**Issue by Kacppian** [RPCS3/rpcs3#2228]
-- No build type selected, default to Release
CMake Warning (dev) at 3rdparty/libpng/CMakeLists.txt:317 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
 
  The LOCATION property should not be read from target "png16_static".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.
 
This warning is for project developers.  Use -Wno-dev to suppress it.
 
-- cotire 1.7.3 loaded.
-- Initializing RPCS3_SRC_DIR=/home/kaushikasp/ps3emu/rpcs3/rpcs3
CMake Warning at rpcs3/CMakeLists.txt:83 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 3.8) with any of the following names:
 
    LLVMConfig.cmake
    llvm-config.cmake
 
  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
 
 
-- RPCS3: using builtin libpng
-- RPCS3: using builtin ffmpeg
LLVM not found! LLVM 3.8 is required. RPCS3 will be compiled without LLVM support.
-- dir='/home/vagrant/pisi/tmp/wxPython-3.0.2.0-3/usr/lib/wx/include/gtk2-unicode-3.0'
-- dir='/home/vagrant/pisi/tmp/wxPython-3.0.2.0-3/usr/include/wx-3.0'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../3rdparty/libpng'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../3rdparty/ffmpeg/linux/x86_64/include'
-- dir='/home/vagrant/pisi/tmp/wxPython-3.0.2.0-3/usr/lib/wx/include/gtk2-unicode-3.0'
-- dir='/home/vagrant/pisi/tmp/wxPython-3.0.2.0-3/usr/include/wx-3.0'
-- dir='/usr/include'
-- dir='/usr/include/AL'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../3rdparty/pugixml/src'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/Loader'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/Crypto'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/..'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../Utilities/yaml-cpp/include'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../asmjit/src/asmjit'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../3rdparty/GSL/include'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../rsx_program_decompiler/shader_code'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../Vulkan/Vulkan-LoaderAndValidationLayers/include'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../Vulkan/glslang/glslang/Public'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../3rdparty/GL'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../3rdparty/stblib'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../rsx_program_decompiler/shader_code'
-- dir='/home/kaushikasp/ps3emu/rpcs3/rpcs3/../3rdparty/cereal/include'
-- Initializing SOURCE_DIR=/home/kaushikasp/ps3emu/rpcs3/rsx_program_decompiler/shader_code
-- Initializing SOURCE_DIR=/home/kaushikasp/ps3emu/rpcs3/rsx_program_decompiler/rsx_decompiler
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kaushikasp/ps3emu/rpcs3
kaushikasp@IntelliHack:~/ps3emu/rpcs3$ make
[  4%] Built target png16_static
[  6%] Built target rsx_decompiler
[  7%] Built target shader_code
Scanning dependencies of target rpcs3
[  8%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/rpcs3qt/glviewer.cpp.o
[  8%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/rpcs3qt/main.cpp.o
[  8%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/XInputPadHandler.cpp.o
In file included from /home/kaushikasp/ps3emu/rpcs3/rpcs3/XInputPadHandler.cpp:2:0:
/home/kaushikasp/ps3emu/rpcs3/rpcs3/stdafx_gui.h:10:19: fatal error: wx/wx.h: No such file or directory
compilation terminated.
rpcs3/CMakeFiles/rpcs3.dir/build.make:126: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/XInputPadHandler.cpp.o' failed
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/XInputPadHandler.cpp.o] Error 1
CMakeFiles/Makefile2:233: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kirbyfan64** [comment]
Do you have the development files for wxWidgets installed?

**Comment by Kacppian** [comment]
I have that directory and I built it, then ran the make and still shows the same error. Pardon my ignorance If I am doing something wrong

**Comment by Nezarn** [comment]
@Kacppian theres 99% chance you're doing something wrong, i've tested 3 different linux distros, they are working fine. (i've tried archlinux, fedora, ubuntu)

So you're either didn't get the dependencies, or didn't get the submodules (or git bugged out and didn't download the submodules correctly)

**Comment by Kacppian** [comment]
If it won't be a burden would you help me identifying the problem in my steps? 

1. cloned the repo
2. executed git submodule update --init
3. cd wxWidgets && ./configure && make
4. cmake ./
5. make

I'm running Ubuntu 16.04 64 bit.

**Comment by Nezarn** [comment]
@Kacppian You're clearly doing it wrong then.

1. clone the repo
2. go into cloned repo folder, git submodule update --init
3. cmake CMakeLists.txt
4. make
(5. if you get missing git-version.h error just make a git-version.h file with this:)

>// This is a generated file. 
 #define RPCS3_GIT_VERSION "unknown" 
 // If you don't want this file to update/recompile, change to 1. 
#define RPCS3_GIT_VERSION_NO_UPDATE 1

**Comment by jobs-git** [comment]
Isnt this as simple as

    sudo apt-get install *wx*dev*
    sudo apt-get install *wx*header*

Just fill the gaps that suites your distribution

**Comment by Nezarn** [comment]
@jobs-git just following the readme is enough. (since he said he is on ubuntu)

**Comment by Nekotekina** [comment]
`git submodule update --init` is not recommended outside of Visual Studio build because many things are available from the packages. Probably need to fix readme.

**Comment by Nezarn** [comment]
@Nekotekina then how come any time i tried it worked just fine? Magic?

**Comment by Nekotekina** [comment]
They work, but it's a waste of space and time.

**Comment by Kacppian** [comment]
I tried both of your suggestions, I'm still getting the same error.  Any other plausible workarounds that might work?

**Comment by Nekotekina** [comment]
Did you install `libwxgtk3.0-dev` as mentioned in readme?

**Comment by AniLeo** [comment]
Is this still an issue?

**Comment by thirdeyefunction** [comment]
Yes, it's still an issue on Gentoo at least. The problem is that wxwidgets include files are installed in a non-standard location. You can workaround it by setting the environment variable CMAKE_CXX_FLAGS to:
$(wx-config --cflags), assuming the use of Bash.

Or add this to the end of CMakeLists.txt:

add_compile_options($(wx-config --cflags))

**Comment by AniLeo** [comment]
This is no longer an issue since we switched from wxWidgets to QT. 
If you have any new issues compiling with QT, please open an issue.

**Comment by hilga007** [comment]
> Isnt this as simple as
> 
> ```
> sudo apt-get install *wx*dev*
> sudo apt-get install *wx*header*
> ```
> 
> Just fill the gaps that suites your distribution

Commenting just so like... I have this in my history as a resolution for multiple issues related to pre-QT wxWidgets on legacy systems. Thank you!!!
