### ISSUE TITLE
AfterBurner Climax crashes when pressing start with the latest build

### ISSUE THREAD

**Issue by godzil21** [RPCS3/rpcs3#2233]
Ok guys!

Here I'm with this fantastic emulator trying to launch  the game  AfterBurner Climax,  and it keeps crashing in the first screen , just after pressing start. 

This is the log. http://pastebin.com/S9YRAR4r

 ... The log is saying it can't read an adx file I already have in their directory!!! The package is correctly installed, that's not the issue.

I launch the game in win10(64) with D3D12 , 1280x720 .  

PPU : Interpreter fast
SPU : Interpreter fast

LLE modules I pick:
rtc
resc
fiber
spurs_jq
sre

I have an nvidia GTX1070 with the latest drivers. 

Any idea?

Thanks a lot!

**Comment by AniLeo** [comment]
Sorry for the late reply.
Please use the forums for those kind of reports. Also, that's not the full log file (RPCS3.log is)
