### ISSUE TITLE
RSX: class std::range_error thrown: bad conversion 

### ISSUE THREAD

**Issue by zerr10** [RPCS3/rpcs3#2235]
F {rsx::thread} class std::range_error thrown: bad conversion

**Comment by zerr10** [comment]
I changed the system for windows 10 versions in 1607 and now this error in DX12

vulcan - works

**Comment by Zangetsu38** [comment]
This issue caused by build anniversery, and last insider build don't fixed this

**Comment by zerr10** [comment]
yes is anniversery, windows last bulding this bug will by fix in future ?

**Comment by Zangetsu38** [comment]
i don't think problem really caused by Windows, just Dx12 need more works

**Comment by raven02** [comment]
Duplicate of https://github.com/RPCS3/rpcs3/issues/2371
