### ISSUE TITLE
RSX: Sonic & SEGA All-Stars Racing 

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2239]
[9e84804e]

@kd-11 
@raven02 
<img src="http://www.fotoszok.pl/upload/c110f991.jpg" alt="Fotoszok.pl" />

**[Log:](https://gist.github.com/SakataGintokiYT/4fd1176f0f7917faf2256679e10898f1)**
**[ShaderLog:](https://mega.nz/#!EQx22YpA!PdTytk_eRa8zfC07fVTZxUZny76ZnY6LB_IWhnDvJTQ)**

**[*OpenGL-RenderDoc-In game](https://mega.nz/#!YMxXjDyK!AyVOMwCANevV8fKtBquaRLJkP5iPHFwxMZ2RmDUTnRQ)**
**[*OpenGL-RenderDoc-Menu:](https://mega.nz/#!NVwjxLhb!aU4vCMc3FGg7qxE3kSrjWgTxosTGzdoYdeBtIp9-VeE)**

**Comment by AniLeo** [comment]
Please check again, I've seen better results somewhere a while ago

**Comment by SakataGintokiYT** [comment]
@AniLeo 
<img src="http://www.fotoszok.pl/upload/5271870b.jpg" alt="Fotoszok.pl" />

**Comment by SakataGintokiYT** [comment]
@AniLeo 
**[OpenGL]**
<img src="http://www.fotoszok.pl/upload/5271870b.jpg" alt="Fotoszok.pl" />

[Vulkan]
<img src="http://www.fotoszok.pl/upload/7b4c39e8.jpg" alt="Fotoszok.pl" />

**Comment by AniLeo** [comment]
@SakataGintokiYT Still an issue?

**Comment by AniLeo** [comment]
@SakataGintokiYT Need you to update the issue please

**Comment by SakataGintokiYT** [comment]
![1](https://user-images.githubusercontent.com/13681488/30702696-e6d3f9c6-9eed-11e7-871e-91e00b7da033.jpg)
This game is unplayable by random rsx and fifo errors.
```
Frame limit: OFF / 59.94 / 60 / 30 

E {rsx::thread} RSX: Invalid RSX method 0x38c (arg=0xbe62d997)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)
E {rsx::thread} HLE: Getting the real address failed. (addr=0x1f800000)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1F800000, put=0x610FC8
E {rsx::thread} RSX: Invalid RSX method 0x4 (arg=0x8181c)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)
E {rsx::thread} RSX: Invalid RSX method 0x40 (arg=0x0)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)
E {rsx::thread} RSX: Invalid RSX method 0x800 (arg=0xff000900)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)
E {rsx::thread} RSX: Invalid RSX method 0x80 (arg=0x60411ffc)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)
E {rsx::thread} RSX: Invalid RSX method 0x9c6c (arg=0xdd3800)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)
E {rsx::thread} RSX: Invalid RSX method 0xe340 (arg=0x41760)
E {rsx::thread} RSX: Invalid RSX method 0x800c (arg=0x68600c3)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)
E {rsx::thread} HLE: Getting the real address failed. (addr=0x1f800000)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1F800000, put=0x4C0484
```

**Comment by toccata10** [comment]
On Ultimate Marvel vs Capcom, it freezes after a while with
E {rsx::thread} HLE: Getting the real address failed. (addr=0x2932410)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x2932410, put=0xEE564
I suppose it's a similar bug
[RPCS3.log-UMV3.gz](https://github.com/RPCS3/rpcs3/files/1325836/RPCS3.log-UMV3.gz)

**Comment by MarioSonic2987** [comment]
With #5436, fixes broken menus and HUD.
![image](https://user-images.githubusercontent.com/20027681/50394523-70111a00-075e-11e9-96b0-0915baff06c8.png)

**Comment by AniLeo** [comment]
Original issues were fixed, if there are remaining issues with this game please open a new issue for them.
