### ISSUE TITLE
GL : Catherine - polygon line

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2241]
@kd-11 
@raven02 

[9e84804]

<img src="http://www.fotoszok.pl/upload/2fb77f5f.jpg" alt="Fotoszok.pl" />

**[*Log:](https://gist.github.com/SakataGintokiYT/69ef2eb923db7eda1a3893d1c9318da9)**
**[*ShaderLog:](https://mega.nz/#!oVxnUIiR!evhSZWBlIdtGdo_8MaGAoPIO9KQkVIMqlES2MGUZ594)**

**[*OpenGL-RenderDoc-Title screen:](https://mega.nz/#!cMJm0aJK!-yTpzarnY1gmnIXT6sK7NdSNz_EGauDbLtkSUpzDr54)**
**[*OpenGL-RenderDoc-Menu:](https://mega.nz/#!8BIVzDxL!5BTqf0c-u4l-aHbbNp3jIHRvX8rSKLHowni-OarOiIg)**
**[*OpenGL-RenderDoc-In game:](https://mega.nz/#!hVxwzCYR!Mutrd6dI41rwqiuD2F7qHMvDY1kDTdh6kQJb02o5M_w)**

**Comment by danilaml** [comment]
Wow! Finally some graphics. Before it was stuck at loading with music and black screen.

**Comment by ssshadowww** [comment]
@danilaml no, it has worked for at least 2 months and possibly much longer than that. http://www.emunewz.net/forum/showthread.php?tid=175609

**Comment by danilaml** [comment]
@ssshadowww well, I stopped testing it about September, so yeah, I guess I've just missed the moment when it started working!

**Comment by RainKikyou** [comment]
@danilaml you see here [#2214](https://github.com/RPCS3/rpcs3/issues/2214)，May be helpful

**Comment by kd-11** [comment]
@SakataGintokiYT Try https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-409. Hopefully, my hunch is correct and RSX uses pitch to determine render target size and downscaling to fit the window.

**Comment by Zangetsu38** [comment]
@kd-11 i have this, not works, broken :/
E {rsx::thread} RSX: Failed to compile shader: 0(10) : error C0000: syntax error, unexpected '}', expecting ',' or ';' at token "}"

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
-----------
0(11) : error C0000: syntax error, unexpected '}', expecting ',' or ';' at token "}"
(0) : error C2003: incompatible options for link

Fragment info
-------------
0(10) : error C0000: syntax error, unexpected '}', expecting ',' or ';' at token "}"
(0) : error C2003: incompatible options for link

**Comment by kd-11** [comment]
Sorry about that. https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-410 should fix the shader compilation issues.

**Comment by Zangetsu38** [comment]
@kd-11 Great, fixed :) 
![capture d ecran 2017-02-10 11 06 17](https://cloud.githubusercontent.com/assets/5261759/22822744/f1e908e6-ef80-11e6-9e4e-c5da0b2e2394.png)

![capture d ecran 2017-02-10 11 05 43](https://cloud.githubusercontent.com/assets/5261759/22822732/dfa306aa-ef80-11e6-82aa-71d03f4c74a0.png)

Strange line polygon red on charactere lol

**Comment by kd-11** [comment]
Will update them as well soon, at least this should land before the read/write buffers work which may take more time. I'm opening a pull request to merge this and continue the discussion there.

**Comment by Zangetsu38** [comment]
@kd-11 ok :) and Do you have an idea for the polygon line? ^^

**Comment by kd-11** [comment]
I have not looked at the traces yet, but I'm guessing its some unimplemented feature such as edge flag support. I would need to investigate further to be honest, but I'm pressed for time at the moment. I only realized what caused the scaling problem when working on the read/write buffers support and decided to push this before the other changes were done.

**Comment by Zangetsu38** [comment]
@kd-11  hm ok i see, i send you tracelog later :)

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/issues/2357 has been merged. Only the lines remain (OpenGL only)

**Comment by raven02** [comment]
By #2660 
![untitled](https://cloud.githubusercontent.com/assets/3000282/24838696/b1f48e90-1d7f-11e7-85ff-71f5dfc77e09.jpg)
