### ISSUE TITLE
RSX: class std::runtime_error thrown: Unknown context (Formula One: Championship Edition)

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#2243]
[Log (DirectX 12)](https://github.com/RPCS3/rpcs3/files/662272/RPCS3_.DirectX12.txt)
[Log (OpenGL)](https://github.com/RPCS3/rpcs3/files/662266/RPCS3_.OpenGL.txt)
[Log (Vulkan)](https://github.com/RPCS3/rpcs3/files/662274/RPCS3_.Vulkan.txt)

**Comment by AniLeo** [comment]
`` ·F {rsx::thread} class std::runtime_error thrown: Unknown context dma 0xfeed0001
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:972) ``

Interesting. Could you load libraries sre, spurs_jq, resc, rtc and test again?

**Comment by TotalCaesar659** [comment]
Version https://github.com/RPCS3/rpcs3/commit/5db0f477106f1d07bd446b8fcb56c732cfe2a80a. Libraries loaded.
![1](https://cloud.githubusercontent.com/assets/14265316/22341184/fb80348c-e400-11e6-98fa-4205943b8ca0.png)
Same result. [Log (OpenGL).txt](https://github.com/RPCS3/rpcs3/files/732919/Log.OpenGL.txt)

**Comment by Zangetsu38** [comment]
@kd-11 I need you aprove for my commit to fix this issue :)

**Comment by kd-11** [comment]
@TotalCaesar659 Check if https://github.com/RPCS3/rpcs3/issues/2312 fixes this crash

**Comment by TotalCaesar659** [comment]
Here is the other bug:
>·F {rsx::thread} struct gsl::fail_fast thrown: GSL: Precondition failure at c:\rpcs3\3rdparty\gsl\include\span.h: 1432

[Formula_One_Championship_Edition.txt](https://github.com/RPCS3/rpcs3/files/743781/Formula_One_Championship_Edition.txt)

**Comment by AniLeo** [comment]
@TotalCaesar659 You may open a different issue for that one. Closing this since the error has been fixed.

**Comment by TotalCaesar659** [comment]
Thank you, I made https://github.com/RPCS3/rpcs3/issues/2340 for it.
