### ISSUE TITLE
Hatsune Miku:Project Diva F version RPCS3

### ISSUE THREAD

**Issue by BlackRocksShooter** [RPCS3/rpcs3#2244]
where can I find this version of rpcs3?
v0.0.1α-ReleaseLLVM-fc3179b6 with even his library
to this video: https://www.youtube.com/watch?v=dE_uQ_DHdrA
I wanted to ask if you can even save your games of this game. because in the video you see him charging ul rescue and rpcs3, I who have a previous version of rpcs3 does not allow me to upload game saves

**Comment by TotalCaesar659** [comment]
> where can I find this version of rpcs3?
v0.0.1α-ReleaseLLVM-fc3179b6

Here https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.3372/artifacts

**Comment by BlackRocksShooter** [comment]
and what I have to download from all folders that are there? (Excuse me, but are not as practitioner of these things xD I already came here about one year ago because the textures were all purple in the game)
