### ISSUE TITLE
DX12/GL: Hellboy: The Science of Evil-(unimplemented sca_opcode BRB)

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2249]
@kd-11 
@raven02 

[6f6d0dca]

<img src="http://www.fotoszok.pl/upload/ffd16b28.jpg" alt="Fotoszok.pl" />

```
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x1C6C, d1=0x8840000D, d2=0x8106C083, d3=0x27C1FFFC
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x19C6C, d1=0x8840050C, d2=0x106C089, d3=0x87C1DFFC
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x29C6C, d1=0x8840040C, d2=0x106C089, d3=0x67C1DFFC
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x29C6C, d1=0x8840040C, d2=0x106C089, d3=0x67C1DFFC
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x29C6C, d1=0x8840040C, d2=0x106C089, d3=0x67C1DFFC
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x29C6C, d1=0x8840040C, d2=0x106C089, d3=0x67C1DFFC
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x29C6C, d1=0x8840040C, d2=0x106C089, d3=0x67C1DFFC
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x29C6C, d1=0x8840040C, d2=0x106C089, d3=0x67C1DFFC
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x1C6C, d1=0x8840000D, d2=0x8106C083, d3=0x27C1FFFC
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x1C6C, d1=0x8840000D, d2=0x8106C083, d3=0x27C1FFFC
E {rsx::thread} RSX: Unknown/illegal instruction: 0x18 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x18 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x18 (forced unit 2)
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x29C6C, d1=0x8840040C, d2=0x106C089, d3=0x67C1DFFC
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x29C6C, d1=0x8840040C, d2=0x106C089, d3=0x67C1DFFC
E {rsx::thread} RSX: Unimplemented sca_opcode BRB, d0=0x29C6C, d1=0x8840040C, d2=0x106C089, d3=0x67C1DFFC
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x18 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x18 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x18 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x18 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x18 (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x18 (forced unit 2)
```

**[Log:](https://gist.github.com/SakataGintokiYT/602a7aeacb81bb56806a174313a4c370)**
**[ShaderLog:](https://mega.nz/#!FFJCgLJJ!JnVhmxxqlmMZqTf1Q_-ZeesNEWGJKKgDUR5UneQtI74)**
**[OpenGL-RenderDoc-in game:](https://mega.nz/#!UVJUWJhL!IdfsCieE4U-YwRcHwi2W2-Q5O1A3HlmPL96tHr1E9dU)**

**Comment by zminhquanz** [comment]
Because emulation at present don't support this opcode this game and inaccurate . You can wait that in the future when the hardware/firmware emulation is accurate enough to run them

**Comment by kd-11** [comment]
A few sca branching ops are unimplemented at the moment. Lack of documentation makes progress on these quite slow as I'm not very sure what they're supposed to be doing in the first place.

**Comment by MarioSonic2987** [comment]
@SakataGintokiYT, can you test this game with kd-11's latest build?

**Comment by SakataGintokiYT** [comment]
@kd-11 
@MarioSonic2987 

<img src="http://www.fotoszok.pl/upload/6ecac695.png" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/7f3a175c.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/1ddae474.png" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/36e7b01d.jpg" alt="Fotoszok.pl" />

**Comment by MarioSonic2987** [comment]
In last screenshot, does the character appear in console or not?

**Comment by kd-11** [comment]
Interesting. Are there any more bugs introduced by my WIP code? I'd love to see the renderdoc trace with my WIP code.
More info:
Hellboy seems to have bits 24,25 and 26 set on the opcode's d3, while saint seiya only sets bit 24 which is what I'm using to determine whether to branch or not. Would be interesting to see why hellboy turned invisible.

**Comment by SakataGintokiYT** [comment]
@kd-11 
[7a758f4a]
**[Shaderlog:](https://mega.nz/#!tZIWyL5S!DKRfrtX8myBrICTVKAPjzBHWEtj6r57VIBAbwq2OOkM)**
**[RenderDoc:](https://mega.nz/#!NUJTXIiJ!3TpjlEPPi_CKdpnjK__RJ93I7HQxyfpcLuGw1yArHms)**

**Comment by kd-11** [comment]
The black screen is another issue altogether; we're getting texture uploads filled with zeros (black) used for post-processing (read/write buffers maybe?). As for missing render of hellboy, it would be easier to compare two traces, one with master and one with my branch so I can tell the changes easily. From the look of things, the shaders should work just fine.

**Comment by SakataGintokiYT** [comment]
@kd-11 
**[Master:](https://mega.nz/#!tQwyhI5T!WBFJIfSXR4wn_3LjDTDbCHXhCz4ZgfyykMh3zgO937U)**
<img src="http://www.fotoszok.pl/upload/faff8529.jpg" alt="Fotoszok.pl" />

-----------------------------------------------------------------------------------------------------

**[BRB-WIP:](https://mega.nz/#!0EITRQTK!wqyeH2EaCjos_Waseb0oWznJ0PvEXrByVeJvABPI2NE)**
<img src="http://www.fotoszok.pl/upload/e1dd6094.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
Please retest with https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.390
Seems BRB is ignored when a vector opcode is also in use. Either that or the flag is somewhere else since superimposing a vector op causes bit 25 to be used for address computation, invalidating the check. I've set it to only branch if we have no vec op issued together with the BRB.

**Comment by SakataGintokiYT** [comment]
@kd-11 
Now looks like master build
- hellboy is visible.
- Black screen in menu and at the loading screen

**Comment by kd-11** [comment]
@SakataGintokiYT Attach trace of the balckscreen menu for comparison; both the old BRB which works and the new one with black screen. We're narrowing down the possibilities on how the value should be implemented.

**Comment by SakataGintokiYT** [comment]
@kd-11 

**[7a758f4a]**
**[RenderDoc](https://mega.nz/#!gExGzYxZ!g6x8xJinU74HMmRoUk_0nUeig8DjItuTgZIIzNwAVgc)**

---------------------------------------------------------------------------------------------------------

**[247fe3d5]**
**[RenderDoc](https://mega.nz/#!kBBWXaaR!dNdPRKJxDEIEBJrj8kBdXc8kxc-hSeU6DWc7q40uYBY)**

**Comment by kd-11** [comment]
After examining the different ways the opcode data changes, I have determined that the branch toggle information must come from an external source. I suspect NV4097_SET_TRANSFORM_BRANCH_BITS method call here which is unimplemented at the moment. Stay tuned.

**Comment by kd-11** [comment]
Run with this commit https://github.com/kd-11/rpcs3/commit/ff5d3514a7a2d2f7c41b70218f25b3452cb0e150
Appveyor build: https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.393

It still uses the broken code with the black screen, but will dump information to the log about which branches are active and which program is in use. Attach rpcs3.log here.

**Comment by SakataGintokiYT** [comment]
@kd-11 
**[rpcs3.log](https://mega.nz/#!cAhABDYB!X6Bf-B8xs_XJwRmwdp-z6Ur7JAzdXKx4JeHrNdN2ipE)**

**Comment by kd-11** [comment]
Odd, its kinda hard to nail down the pattern. Maybe a log also running saint seiya's menu would help.

**Comment by MarioSonic2987** [comment]
Test with this build: https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.394.

**Comment by MarioSonic2987** [comment]
One Piece: Pirate Warriors 2 also have this issue with BRB opcode.

**Comment by MarioSonic2987** [comment]
Sly Cooper: Thieves in Time Demo [NPEA90120] have this issue with BRB opcode.

**Comment by kd-11** [comment]
Please retest with https://github.com/RPCS3/rpcs3/pull/2426

**Comment by SakataGintokiYT** [comment]
@kd-11 

**DX12**
```
Unhandled Win32 exception 0xC0000005.
Segfault reading location ffffffffffffffff at 00000000003bd400.
Instruction address: 00000000003bd400.
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.
```
**[Log:](https://gist.github.com/SakataGintokiYT/68374510ad49040e6671a3446b94b1b5)**
**[Shaderlog:](https://mega.nz/#!sJZnkZRZ!cMImFs5uvLKDTb8wAFYFWEmHPkEiWxfNstM4IRbN320)**

-----------------------------------------------------------------------------------------------------------------

**OpenGL**
<img src="http://www.fotoszok.pl/upload/0b908715.jpg" alt="Fotoszok.pl" />

**Comment by raven02** [comment]
@SakataGintokiYT , how about Vulkan ?

**Comment by SakataGintokiYT** [comment]
@raven02 
Vulkan crashes at startup but not by this commit
**[Log:](https://gist.github.com/SakataGintokiYT/45380d0b26d11a4eb9e91f891cc60bac)**

**Comment by kd-11** [comment]
I know about the heap management issues.
Will be fixed later .

**Comment by SakataGintokiYT** [comment]
@kd-11 
<img src="http://www.fotoszok.pl/upload/8a7acf22.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment]
BRB issue is fixed
