### ISSUE TITLE
Error compiling on Ubuntu 16.04 (the same without using git and cloning manually)

### ISSUE THREAD

**Issue by opensrx** [RPCS3/rpcs3#2251]
After doing:

2001 sudo apt-get install cmake build-essential libopenal-dev libwxgtk3.0-dev libglew-dev zlib1g-dev libedit-dev libvulkan-dev
2002 cd /tmp/
2004 git clone https://github.com/RPCS3/rpcs3
2005 cd rpcs3/
2006 git submodule update --init
2009 cmake CMakeLists.txt && make && cd ../

This is what I get:

This warning is for project developers.  Use -Wno-dev to suppress it.

-- cotire 1.7.3 loaded.
-- Initializing RPCS3_SRC_DIR=/tmp/rpcs3/rpcs3
-- Found wxWidgets: TRUE  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:178 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:83 (find_package)

CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:181 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:83 (find_package)

-- RPCS3: using builtin libpng
-- RPCS3: using builtin ffmpeg
CMake Error at rpcs3/CMakeLists.txt:151 (llvm_map_components_to_libnames):
  Unknown CMake command "llvm_map_components_to_libnames".

-- Configuring incomplete, errors occurred!
See also "/tmp/rpcs3/CMakeFiles/CMakeOutput.log".

**Comment by legluondunet** [comment]
try to install this package: llvm-3.8-dev

**Comment by opensrx** [comment]
already installed

**Comment by legluondunet** [comment]
On my Ubuntu install (17.04),
this files:
/usr/lib/llvm-3.8/share/llvm/cmake/LLVMExports.cmake
and
/usr/share/llvm/cmake/LLVM-Config.cmake
are in the llvm-3.8-dev package.

Could you post the result of this command:

$ locate LLVMExports.cmake
$ locate LLVM-Config.cmake
$ dpkg -l llvm-3.8-dev

and to be sure:
sudo apt-get install --reinstall llvm-3.8-dev

**Comment by AniLeo** [comment]
Could you please test with the updated instructions?

**Comment by opensrx** [comment]
Here is what shell return me with new installation instruction

srx@srx-desktop:~/rpcs3/rpcs3$ cmake CMakeLists.txt && make GitVersion && make
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Release
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
CMake Warning (dev) at 3rdparty/libpng/CMakeLists.txt:317 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "png16_static".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- cotire 1.7.3 loaded.
-- Initializing RPCS3_SRC_DIR=/home/srx/rpcs3/rpcs3/rpcs3
-- Found wxWidgets: TRUE  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:178 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:91 (find_package)


CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:181 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:91 (find_package)


-- RPCS3: using builtin libpng
-- RPCS3: using builtin ffmpeg
CMake Error at rpcs3/CMakeLists.txt:159 (llvm_map_components_to_libnames):
  Unknown CMake command "llvm_map_components_to_libnames".


-- Configuring incomplete, errors occurred!
See also "/home/srx/rpcs3/rpcs3/CMakeFiles/CMakeOutput.log".
srx@srx-desktop:~/rpcs3/rpcs3$

**Comment by kirbyfan64** [comment]
Did you install LLVM first?

**Comment by opensrx** [comment]
Yes

**Comment by kirbyfan64** [comment]
What's the output of `llvm-config --version` and `llvm-config --prefix`?

**Comment by opensrx** [comment]
llvm 3.8.0
srx@srx-desktop:~$ llvm-config --prefix
/usr/lib/llvm-3.8

**Comment by kirbyfan64** [comment]
Is there anything in the directories `/usr/lib/llvm-3.8` and `/usr/lib/llvm-3.8/cmake`? I think you may have fallen victim to [this](http://stackoverflow.com/a/39686233/2097780)...

**Comment by opensrx** [comment]
I do not have the /usr/lib/llvm-3.8/cmake file

**Comment by opensrx** [comment]
I'll try the fix described in the link you sent to me.

**Comment by opensrx** [comment]
srx@srx-desktop:~/rpcs3$ set(_IMPORT_PREFIX "/usr/lib/llvm-3.8")
bash: erreur de syntaxe près du symbole inattendu « _IMPORT_PREFIX »
(in approx english: syntax error close to unexpected symbol....)

**Comment by cyian-1756** [comment]
I've also run into this issue (Running Ubuntu 16.04 with llvm 3.8.0)

**Comment by HammiSaif** [comment]
I installed llvm-3.8 on ubuntu 16.04.2 LTS using sudo apt-get install llvm command from terminal. When I used Cmake to build LLVM pass as described in https://www.cs.cornell.edu/~asampson/blog/llvm.html I got the same error:

CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:178 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)

CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:181 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)

Please tell me if you have fixed this issue ?

**Comment by AniLeo** [comment]
Can you please retest? This should be building now.
Also, you **must** use LLVM 4.0
