### ISSUE TITLE
I can't run that game!

### ISSUE THREAD

**Issue by SMBX2011** [RPCS3/rpcs3#2252]
When i try to run the Game in RPCS3. It gave any error:
LDR: Unknown module 'cellLibprof'
LDR: Unknown function '0x05893E7C' in module 'cellLibprof' (index 2972)
LDR: Unknown function '0x6D045C2E' in module 'cellLibprof' (index 2973)
LDR: Unknown function '0xB498BF77' in module 'cellSysmodule' (index 2974)
LDR: Unknown function '0xD9B8C0EE' in module 'cellSysmodule' (index 2975)
LDR: Unknown function '0x9FB6228E' in module 'sysPrxForUser' (index 2976)
LDR: Unknown function '0x3EF17F8C' in module 'sysPrxForUser' (index 2977)
LDR: Unknown module 'cellMp4'
LDR: Unknown function '0x390BFF1F' in module 'cellMp4' (index 2978)
LDR: Unknown module 'cellSailAvi'
LDR: Unknown function '0x9B02DB99' in module 'cellSailAvi' (index 2979)
LDR: Unknown module 'cellApostSrcMini'
LDR: Unknown function '0x24F4ECD3' in module 'cellApostSrcMini' (index 2980)
LDR: Unknown function '0x9AAA0039' in module 'cellApostSrcMini' (index 2981)
LDR: Unknown function '0x752E10C4' in module 'cellApostSrcMini' (index 2982)
LDR: Unknown function '0x8A6D4227' in module 'cellApostSrcMini' (index 2983)
LDR: Unknown function '0xCF350A4C' in module 'cellApostSrcMini' (index 2984)
LDR: Unknown function '0x7608719D' in module 'sys_net' (index 2985)
LDR: class fmt::exception thrown: D3D12GSRender::D3D12GSRender(): HRESULT = A interface de recurso especificado ntema.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12GSRender.cpp:179)

And it will can't run any games forever! Help me plz!

**Comment by AniLeo** [comment]
Use the forums for those kind of reports, RPCS3 is not meant to play games yet, it only runs a few.
