### ISSUE TITLE
-bash: cd: rpcs3: No such file or directory (Mac)

### ISSUE THREAD

**Issue by hallowedTwilight** [RPCS3/rpcs3#2253]
I got stuck on this part and I don't know if there is a workaround on this.

**Comment by GreenEye4250** [comment]
You should learn how terminal works first. 
If basic stuff like this is like black magic to you - you are not going to accomplish much.

**Comment by AniLeo** [comment]
MacOS isn't supported at the moment because it does not meet system requirements (OpenGL 4.3)
