### ISSUE TITLE
DX12/GL/Vulkan：Attack on Titan graphics issue

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2254]
vullkan
![qq 20161230192229](https://cloud.githubusercontent.com/assets/20301499/21564173/551f0ffa-cec5-11e6-9248-ed3a6053f18d.jpg)
OpenGL
![qq 20161230193113](https://cloud.githubusercontent.com/assets/20301499/21564273/9d80d8c2-cec6-11e6-8502-2d9285d37849.jpg)
dx12 can not work
![qq 20161230193025](https://cloud.githubusercontent.com/assets/20301499/21564285/afe5acd6-cec6-11e6-81a2-87e40bace99f.jpg)
vullkan video：https://youtu.be/wHoCl9vK6OY
build：[6f6d0dca](https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.378)
log：https://drive.google.com/open?id=0B4z-S0oOZ2FgRmxLOEQ4dk15ZkE
rdc
vullkan ：https://drive.google.com/open?id=0Bx3kiWoCcNv0MzlJNXBJOENXSWM
OpenGL：https://drive.google.com/open?id=0Bx3kiWoCcNv0QkxWYXJUNnN1RFU

**Comment by MarioSonic2987** [comment]
@RainKikyou Could you test with latest build?

**Comment by Zangetsu38** [comment]
no change

**Comment by Zangetsu38** [comment]
dev already informed for actuel render

**Comment by kd-11** [comment]
This issue was fixed a while back. Some texture problems remain, but I feel the original reported issue (missing graphics) was resolved. Open a new issue for the texture color bug.
