### ISSUE TITLE
OGL/VK：Ragnarok Odyssey ACE - Graphical Issues

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2258]
![dx12](https://cloud.githubusercontent.com/assets/20301499/21602403/73307ae0-d1ce-11e6-9a31-8ae600cd0d37.jpg)
![ogl](https://cloud.githubusercontent.com/assets/20301499/21602401/732df626-d1ce-11e6-868c-3a2111b4c9ea.jpg)
![vk](https://cloud.githubusercontent.com/assets/20301499/21602402/732ea88c-d1ce-11e6-93f8-a21ae178bb18.jpg)
The graphics problem is the same
video：https://youtu.be/T0TlMpyEe8M
log：https://drive.google.com/open?id=0B4z-S0oOZ2FgMVRlTXB4YnlyNk0
rdc：https://mega.nz/#F!TZckHJYY!D7Ft7U2Fw0Fh7A8tLkUjOg

**Comment by JohnGodgames** [comment]
Tested by https://github.com/RPCS3/rpcs3/commit/48b05838666cc1670ea10d83fe303c3cf1d104d6

**GL/VK** - the same
**DX12** - bad conversion

**PS3**
<img width="640" alt="ragnarok 6" src="https://cloud.githubusercontent.com/assets/11453507/23549658/889506d6-000d-11e7-9cdf-92a3632c7cf7.PNG">
<img width="634" alt="ragnarok 4" src="https://cloud.githubusercontent.com/assets/11453507/23549587/3ba2ccd2-000d-11e7-81b8-6cc4d3911d4f.PNG">
<img width="634" alt="ragnarok 5" src="https://cloud.githubusercontent.com/assets/11453507/23549615/5a3ba47a-000d-11e7-9da1-992fcbae34e7.PNG">



**RPCS3**
<img width="641" alt="ragnarok 1" src="https://cloud.githubusercontent.com/assets/11453507/23549466/bad0e4f4-000c-11e7-80ed-f3433f629998.PNG">
<img width="641" alt="ragnarok 2" src="https://cloud.githubusercontent.com/assets/11453507/23549472/c07d75ac-000c-11e7-98b1-3cb23930c65f.PNG">
<img width="641" alt="ragnarok 3" src="https://cloud.githubusercontent.com/assets/11453507/23549491/cdcca05c-000c-11e7-894e-ad5785b019ff.PNG">



[RenderDoc title screen OGL](https://mega.nz/#!yU03FCSK!Nx6w5gseGEneuoU9e-4PLSRgCVLgxeRhfVF1fBkVXzQ)
[RenderDoc ingame OGL](https://mega.nz/#!7UMDzDpA!P1H2BWSuR40QREDH4NfQty2M0gxWi2VW7gZvsllKEp4)
[LOG](https://mega.nz/#!qFMlxYyI!ihw_CxeVvw-XOCBBHvyhRztIKf_d8pYPFytRyXVW66M)

**Comment by RainKikyou** [comment]
You try, newgame and then return here can be normal
![img_1580](https://cloud.githubusercontent.com/assets/20301499/23551878/d1d33cf0-0053-11e7-83b2-0a06b25e81bc.jpg)

**Comment by JohnGodgames** [comment]
@kd-11 Yep title screen fixed after that, but ingame is still broken...shadows, geometry shaders?

**Comment by kd-11** [comment]
Renderdoc comparison between the broken screen and the fixed one should give more information.
Its not shaders, probably gemoetry related.

**Comment by JohnGodgames** [comment]
<img width="641" alt="ragnarok 7" src="https://cloud.githubusercontent.com/assets/11453507/23553247/49bd9d66-0020-11e7-8038-7ca55e10ec09.PNG">


[RenderDoc title screen fixed OGL](https://mega.nz/#!iQkl1IQI!Sc-I0O4r1qVSU7QCZeeOS8yQjbcO3-F9039HaVSnHAw)

**Comment by kd-11** [comment]
Is this still an issue?

**Comment by JohnGodgames** [comment]
https://github.com/RPCS3/rpcs3/commit/7c897d5019e4706ef51205140114249f9fb251ea Can't test, because game doesn't boot anymore.

```
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000004 at 0000000000621389.
Instruction address: 0000000000621389.
Function address: 0000000000621250 (base+0x611250).
Module name: 'rpcs3 7c897d5.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.
```

[RPCS3.log1.gz](https://github.com/RPCS3/rpcs3/files/1284655/RPCS3.log1.gz)

**Comment by AniLeo** [comment]
@JohnGodgames That log is empty, retest and upload an actual log please

**Comment by Nithraniel** [comment]
I've got a log of me going through the first quest and finishing it, maybe it can help you. I got the same graphical issues, here's the link : 
https://mega.nz/#!QUABiLwD!Xb90WmV4SGSzZ2PN-QzqmgRMO3Jd4KTb_1iuPEP6ANc

**Comment by Emulator-Team-2** [comment]
@AniLeo 
v0.0.5-7658 Alpha [2019-01-05]  Vulkan / OpenGL
*Settings: Default 

![r1](https://user-images.githubusercontent.com/38318848/50729868-c2c8d980-1141-11e9-9e47-b72f8e337519.png)

![r2](https://user-images.githubusercontent.com/38318848/50729871-d70cd680-1141-11e9-9a72-0c25e5794c3d.png)

![r3](https://user-images.githubusercontent.com/38318848/50729875-e429c580-1141-11e9-88a2-d69366633b82.png)

**Comment by Emulator-Team-2** [comment]
@kd-11 
This issue can be closed.
Forum thread:
https://forums.rpcs3.net/thread-188634.html
