### ISSUE TITLE
Rpcs3 error

### ISSUE THREAD

**Issue by LenKYY** [RPCS3/rpcs3#2261]
I already made a bios and I installed it, I did everything else it continues happening this:

E Loading 'C:/Users/Len Kagamine/Documents/rpcs3-master/rpcs3-master/bin/dev_hdd0/game/BLUS31431/PS3_GAME/USRDIR/BOOT.BIN' failed

**Comment by AniLeo** [comment]
You should use the forums for those kind of issues. Where's the full log? 
(BIOS ?)

**Comment by AniLeo** [comment]
Close request here as well
