### ISSUE TITLE
Feature: Support for DirectInput Controllers (Such as Dualshock 4 controllers without an XInput Wrapper)

### ISSUE THREAD

**Issue by Bryceless** [RPCS3/rpcs3#2266]
Seeing Support for DirectInput Controllers would be a great idea to be implemented into the emulator for people who don't own an Xbox or XInput-based controller, or don't want to fiddle around with third party drivers like InputMapper or DS4Windows when Steam has built in support for DS4s without needing to install any third party drivers.

Another suggestion would to have some sort of keyboard and/or controller option where you can map certain keys, buttons, or even the DS4's gyroscope to the PS3 Controller's Gyroscope.

**Comment by Kilowog01** [comment]
I do not believe this is a priority for them but I think this would make testing much easier.

**Comment by AniLeo** [comment]
Oh, this may be coming sooner than you think

**Comment by georgemoralis** [comment]
it's on works and coming shortly :)

**Comment by Bryceless** [comment]
Is there any plans on a controller remapping menu (Similar to the Keyboard remapping menu but for MMJoystick), and deadzones for analog sticks?

When using a DS4, X and O are reversed (Same goes for Square and Triangle), and the Start and Select buttons are in reverse (It uses the Share and Options button on the DS4).

**Comment by Bryceless** [comment]
Never mind about the controller buttons being in reverse for DS4s, there is already a fix for it by using a custom config, due to a controller remapping menu not being available at the moment.

For anybody who has a Dualshock 4 with the official adapter that Sony released, here is a config file based on the one that georgemoralis uploaded that should work with a proper control layout.

I'm not sure if it will work with Dualshock 4 controllers via USB or Bluetooth, but if somebody is having issues, I can only make a USB version of it, due to me not having a Bluetooth adapter atm.

https://github.com/RPCS3/rpcs3/files/778182/config_mmjoystick.DS4.zip

**Comment by Bryceless** [comment]
For anybody who wants to use a Dualshock 4 controller with RPCS3, here's a config file that will give you proper controller mapping for DS4 controllers.

This is config is designed for when using the official adapter that Sony released, and I have no clue if it works properly when connected to USB or through Bluetooth. If you find any problems, make sure to PM me, and i'll figure out any problems you may have.

[config_dualshock4.zip](https://github.com/RPCS3/rpcs3/files/778231/config_dualshock4.zip)

**Comment by raven02** [comment]
Supported by https://github.com/RPCS3/rpcs3/pull/2733

**Comment by mirh** [comment]
OP use-case should be indeed covered by that, but I'm not sure to have seen the lack of DirectInput  being addressed there.

**Comment by Chemlo** [comment]
This page is the first result on Google for "RPCS3 DualShock 4", so I just want to confirm that [the configuration](https://github.com/RPCS3/rpcs3/issues/2266#issuecomment-280121272) from @Bryceless works with the Sony adapter, USB, and Bluetooth. Download the zip and extract the config_mmjoystick.yml file into the RPCS3 folder.

This information will be outdated when #2733 or similar is merged. Limitations of the "MMJoystick" implementation described here are lack of rumble, gyroscope, and accelerometer. Pressure sensitive buttons are absent on the DualShock 4.

**Comment by mirh** [comment]
After seeing how #2733's proceeding, I'm really wondering if there couldn't be some spare rpcs3 dev (:s) to help with https://github.com/nefarius/FireShock/issues/5
Seriously, anything default from both microsoft and/or sony seems to be somehow someway shortcome.

**Comment by C0rn3j** [comment]
How would I go about making my Steam Controller work with RPCS3? I've read that RPCS3 now uses evdev but I have no idea how to actually get it working.

**Comment by Needled** [comment]
@C0rn3j That's pretty easy, you register RPCS3 as a "Non-steam game" through steam and then open it from there. Steam controller naturally works for all applications since it binds its keys to whatever keyboard keys you want. But you will have to configure either your steam controller inputs or the RPCS3 controller configuration to match each other.

**Comment by C0rn3j** [comment]
I'm aware that Steam has this capability, and so does [sc-controller](https://github.com/kozec/sc-controller), which is open source. My point is that I don't want to configure each key, I'd just like plug and play. Even if I'll have to emulate X360 controller somehow.

Should've made that clearer, sorry.

**Comment by C0rn3j** [comment]
For those with Steam Controllers - there is a PR that fixes them on Linux with sc-controller.

https://github.com/RPCS3/rpcs3/pull/3244

**Comment by fredistehboss** [comment]
Hello, I am currently using InputMapper to connect my DS4 controller (coupled with the offical sony dongle). I can't seem to get RPCS3 to recognize input, I tried all the handlers in the pad options. Any help/advise would be greatly appreciated.

**Comment by Asinin3** [comment]
@fredistehboss This isn't the place to ask for support, join the RPCS3 discord channel here: https://discord.me/RPCS3

**Comment by fredistehboss** [comment]
It says I "don't have permission to send messages in this channel"...

**Comment by zebranco** [comment]
ds4 cuh-zct2g model v2 windows 10 native driver plugged via usb now works correctly on rpcs3 rpcs3-v0.0.5-6639-90e0bade_win64
![sem titulo](https://user-images.githubusercontent.com/31833329/38397675-5f13c526-3915-11e8-98ae-eadf1b59fdd1.png)

**Comment by mirh** [comment]
Rpcs3 should support sony [official DS3 driver](http://www.playstationlifestyle.net/2016/09/23/playstation-now-pc-app-supports-dualshock-3-controller/), first of all.

**Comment by Megamouse** [comment]
I showed this to Jarves a while ago. But there are other things to finish up first before we can add new stuff

**Comment by Bryceless** [comment]
Oh yeah, sorry about that. I never got around to closing this issue.
