### ISSUE TITLE
a error

### ISSUE THREAD

**Issue by holoto** [RPCS3/rpcs3#2271]
# llvm3.8 with osx10.11.6
`➜  rpcs3-master cd rpcs3 && cmake CMakeLists.txt && make && cd ../
-- cotire 1.7.3 loaded.
-- Initializing RPCS3_SRC_DIR=/Users/holoto/Downloads/test/rpcs3-master/rpcs3
-- RPCS3: using builtin libpng
-- RPCS3: using builtin ffmpeg
-- dir='/usr/local/lib/wx/include/osx_cocoa-unicode-3.0'
-- dir='/usr/local/include/wx-3.0'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../3rdparty/libpng'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../3rdparty/ffmpeg/macosx/x86_64/include'
-- dir='/usr/local/include'
-- dir='/usr/local/lib/wx/include/osx_cocoa-unicode-3.0'
-- dir='/usr/local/include/wx-3.0'
-- dir='/usr/include'
-- dir='/System/Library/Frameworks/OpenAL.framework/Headers'
-- dir='/usr/local/opt/llvm@3.8/lib/llvm-3.8/include'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../3rdparty/pugixml/src'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/Loader'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/Crypto'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/..'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../Utilities/yaml-cpp/include'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../asmjit/src/asmjit'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../3rdparty/GSL/include'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../rsx_program_decompiler/rsx_decompiler'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../rsx_program_decompiler/shader_code'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../Vulkan/Vulkan-LoaderAndValidationLayers/include'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../Vulkan/glslang/glslang/Public'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../3rdparty/GL'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../3rdparty/stblib'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../rsx_program_decompiler/rsx_decompiler'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../rsx_program_decompiler/shader_code'
-- dir='/Users/holoto/Downloads/test/rpcs3-master/rpcs3/../3rdparty/cereal/include'
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/holoto/Downloads/test/rpcs3-master/rpcs3
[  0%] Building CXX object CMakeFiles/rpcs3.dir/BasicKeyboardHandler.cpp.o
clang: error: no such file or directory: '@LLVM_DEFINITIONS@'
make[2]: *** [CMakeFiles/rpcs3.dir/BasicKeyboardHandler.cpp.o] Error 1
make[1]: *** [CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2`

# how to fix it ? please help me! ths!!

**Comment by al0xf** [comment]
Regardless osx does not support modern versions of OpenGL (see https://support.apple.com/en-us/HT202823) so rpcs3 will not run anything even if you get it to compile. For more questions please go to the forums: http://www.emunewz.net/forum/showthread.php?tid=174352

**Comment by holoto** [comment]
@al0xf ths!
