### ISSUE TITLE
no work on sklake i7 6700 3.4Ghz LLVM

### ISSUE THREAD

**Issue by zerr10** [RPCS3/rpcs3#2272]
no work on sklake i7 6700 3.4Ghz LLVM all game same...

E {PPU[0x70000035] Thread (_libsail-control) [0x00ccda78]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x70000035] Thread (_libsail-control) [0x00ccda78]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x70000035] Thread (_libsail-control) [0x00ccda78]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x70000035] Thread (_libsail-control) [0x00ccda78]} sys_spu: Unsupported SPU Thread options (0x2)
U {PPU[0x70000035] Thread (_libsail-control) [0x00ccda78]} sys_prx TODO: sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
U {PPU[0x7000003a] Thread (_libsail-source_fs) [0x00cd0d38]} sys_fs TODO: sys_fs_fcntl(): Unknown operation 0xc0000006 (fd=4294967295, arg=*0xd007f808, size=0x20)
U {PPU[0x70000009] Thread (NU::File::RequestManager) [0x005d8778]} sys_fs TODO: sys_fs_fcntl(): Unknown operation 0xc0000006 (fd=4294967295, arg=*0xd0053888, size=0x20)
U {PPU[0x70000009] Thread (NU::File::RequestManager) [0x005d8778]} sys_fs TODO: sys_fs_fcntl(): Unknown operation 0xc0000006 (fd=4294967295, arg=*0xd00538b8, size=0x20)
E {PPU[0x7000003d] Thread (_libsail-control) [0x00ccda78]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x7000003d] Thread (_libsail-control) [0x00ccda78]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x7000003d] Thread (_libsail-control) [0x00ccda78]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x7000003d] Thread (_libsail-control) [0x00ccda78]} sys_spu: Unsupported SPU Thread options (0x2)
U {PPU[0x7000003d] Thread (_libsail-control) [0x00ccda78]} sys_prx TODO: sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
U {PPU[0x70000009] Thread (NU::File::RequestManager) [0x005d8778]} sys_fs TODO: sys_fs_fcntl(): Unknown operation 0xc0000006 (fd=4294967295, arg=*0xd0053888, size=0x20)
U {PPU[0x70000009] Thread (NU::File::RequestManager) [0x005d8778]} sys_fs TODO: sys_fs_fcntl(): Unknown operation 0xc0000006 (fd=4294967295, arg=*0xd00538b8, size=0x20)
U {PPU[0x70000042] Thread (_libsail-source_fs) [0x00cd0d38]} sys_fs TODO: sys_fs_fcntl(): Unknown operation 0xc0000006 (fd=4294967295, arg=*0xd007f808, size=0x20)

**Comment by AniLeo** [comment]
Please read [this](http://www.emunewz.net/forum/showthread.php?tid=174352) and use the forums for those kind of non-specific reports

**Comment by Nekotekina** [comment]
Skylake CPU won't help to run games if they don't work.
