### ISSUE TITLE
Regression: Naruto Ultimate Ninja Storm [BLES00371] , no audio.

### ISSUE THREAD

**Issue by ikki84** [RPCS3/rpcs3#2274]
Basically, the audio was working until #2034 , and investigating exactly when it  stopped working, and after some hours testing if found that this commit (https://github.com/RPCS3/rpcs3/commit/a7e808b35bca478e3bbb848ae440a46b8b302fb2) made the game stop the audio output for some reason that I don´t know, and also In the Free Battle mode (Com vs COM) , the cutscene before the fight begins became in a infinite loop.

If it´s possible to revert it or review and change the part that is causing the problem, this game will run properly.

Tested with Vulkan / PPU Interpreter / SPU Recompiler.

**Comment by raven02** [comment]
Can you try to revert the commit #2034 ? to see if it is fully working again

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/2034 only affects counting verts/indices to draw so I'm certain it wont fix audio. The OP does mention https://github.com/RPCS3/rpcs3/commit/a7e808b35bca478e3bbb848ae440a46b8b302fb2 which is a more intrusive commit though.

**Comment by raven02** [comment]
I will test it out as i tested few more games that also no audio as well

**Comment by Zangetsu38** [comment]
this bug caused by appveyor, i have comile master and sound works, i don't know why

**Comment by raven02** [comment]
Do you mind sharing your compiled build ?

**Comment by Zangetsu38** [comment]
yes here 
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/736664/rpcs3.zip)

**Comment by raven02** [comment]
Thanks. Probably @ikki84  can test it out as well with Naruto Ultimate Ninja Storm as well.

**Comment by Zangetsu38** [comment]
@ikki84 have already tester this on discord, and it works ^^

**Comment by ikki84** [comment]
@raven02 Sorry for the late reply, in fact the build that Zangetsu sent me is working with audio. 
Anyway if you take a look, until #2034 the master build was also working with audio. 
I don´t know why it started to fail but as kd-11 said, that commit had nothing that could do it apparently.
So i guess it´s probably an appveyor fault. 
Anyway, the regression persists in the latest appveyor build, So I wish to keep this issue opened until it become solved.

**Comment by ikki84** [comment]
Naruto became to run with audio again in this pull.
https://github.com/RPCS3/rpcs3/pull/2300
https://ci.appveyor.com/api/buildjobs/3mberwa11s7ljq50/artifacts/rpcs3-ReleaseLLVM-3d75bb22.zip

**Comment by ikki84** [comment]
Solved.
