### ISSUE TITLE
Feature : adding buttons "Mark all" and "Unmark all" for loading libraries

### ISSUE THREAD

**Issue by SauronfromMordor** [RPCS3/rpcs3#2277]
Hello! Could you add buttons "Mark all" and "Unmark all" into "Load libraries" menu?
It's very hard to do it manually one by one.
![755](https://cloud.githubusercontent.com/assets/24421310/22218416/a689498c-e1b7-11e6-9bb4-0fade006a288.png)

**Comment by Nekotekina** [comment]
There are some hotkeys to do it. Click first + Shift+End to select all, for example.

**Comment by SauronfromMordor** [comment]
Did it, but they all can't be marked even when they all are selected, only one by one.
![423](https://cloud.githubusercontent.com/assets/24421310/22218855/a4bcf80e-e1b9-11e6-9aae-539ec5f2dce8.png)

**Comment by Nekotekina** [comment]
Try Num++, also Space inverts the selection.

**Comment by SauronfromMordor** [comment]
Space works, thanks. But these buttons (like in uTorrent) should be more comfortable and remove these questions like mine.
Of course, if you will not make them, you can close this issue.

**Comment by Nekotekina** [comment]
I hope I'll make it less necessary for end users to select modules. However, if someone wants to implement buttons, I won't argue.

**Comment by flash-fire** [comment]
I'll see if I can add a "Toggle All Libraries" button this weekend when I have free time. I don't think it'll be that difficult.

**Comment by al0xf** [comment]
It would encourage people to select every LLE modules which is very wrong as nothing would run with such an configuration. Just wait for automatic LLE selection to be implemented and this shouldn't be an issue anymore.

**Comment by Blaypeg** [comment]
Is there a log anywhere of which LLE works for which game?

If so we could start to look at per game settings if that is needed. That is a bit clunky but until a day in the future where a game will start without manual intervention it would help.

**Comment by al0xf** [comment]
The game binary contains information on which modules it will load, so no need to make a list. Right now you can scroll through rpcs3.log and see which would be needed, and then check on the forums to figure out which work and which don't, but all of this will be automated in the future. Right now there are only a very small handful of playable games so the forum settings are sufficient for now I think.

**Comment by MarioSonic2987** [comment]
Can this issue be closed? Automatic LLE is implemented.

**Comment by Megamouse** [comment]
We need to know if we're supposed to implement the buttons in Qt branch or not. So is this issue still valid or can it be closed? 
if valid I could make a quick PR for current GUI as well

**Comment by al0xf** [comment]
Like I have said this is a bad idea. There is no reason whatsoever to under any circumstances select all modules. And you should never give a user the option to do something stupid like that. I can already see the support questions on the forums along the lines of "halp I selected all modules and now rpcs3 crashes in 0 seconds". 

What you should do is to disable the list entirely when auto LLE is on and move the auto LLE button to above the list to clearly indicated that it overrides any selection. Same with "load liblv2.sprx only" but make it easier to understand that it together with auto acts as manual activation of additional modules. 

To reiterate: do *not* add a button to select all modules. It has *zero* use cases.

**Comment by Megamouse** [comment]
So maybe just add a radiobutton for manual or automatic LLE and disable or grey out the list if auto is checked. I could put the buttons on top above the list (into the load libraries box)

**Comment by AniLeo** [comment]
I'll be closing this one since we decided not to add Check/Uncheck all buttons
