### ISSUE TITLE
HLE  : Call of duty classic not enough space 

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2280]
Hi
I Have Problem whit message box Error
it say you no have enough space in drive but i have X Gigabyte space free

I have See This Error In Other Games

For Example Call Of Duty Classic

![call of duty classic](https://cloud.githubusercontent.com/assets/25039098/22245945/bbf83d7e-e247-11e6-9b64-7d3b2f8bdd7f.jpg)

[Call of duty Classic.zip](https://github.com/RPCS3/rpcs3/files/726517/Call.of.duty.Classic.zip)

Sorry For My Bad English

**Comment by raven02** [comment]
It came from cellHddGameCheck 

E {PPU[0x70000000] Thread (main_thread) [0x003e4b98]} cellGame: cellHddGameCheck(version=0, dirName=“NPUB30065”, errDialog=1, funcStat=*0x42c680, container=4294967295)
E {PPU[0x70000000] Thread (main_thread) [0x003e4b58]} cellSysutil: Call of Duty Classic needs a total of 9 MB of free space to run. Please exit the game and obtain the necessary space to play.

**Comment by twdarkeh** [comment]
This may sound stupid, but in cellHddGameCheck, there are TODO mentions of getting the disc space from the drive where rpcs3 is located. I noticed someone working on a Qt GUI replacement for wxwidgets, and was wondering if the QtStorageInfo class would work for that purpose? It's supposed to be cross-platform, and seems relatively simple to use. I doubt it would help with this error, as there are multiple other TODOs that I don't really understand, but just thought I'd mention it.

**Comment by georgemoralis** [comment]
i have debugged that function doesn't seem to have an error , the problem is probably somewhere else.
The QT port is still ages behind. Once it done it will be probably consider to use QtStorage

**Comment by Nekotekina** [comment]
Please no, emucore shall not use GUI-related features.

**Comment by aakh1361** [comment]
Maybe This one Help
![0](https://cloud.githubusercontent.com/assets/25039098/23176390/f5cffd52-f877-11e6-8a18-194c24e3a70a.jpg)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/790902/RPCS3.zip)

**Comment by AniLeo** [comment]
I believe this was fixed in #2722 
@aakh1361 Please confirm, so it can be closed

**Comment by aakh1361** [comment]
Yes Fix it
