### ISSUE TITLE
Feature: custom resolution

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2282]
Hi
Can you Add Support Internal change resolution just like Pcsx2 or dolphin emu or Other Emulators ?
custom resoltion 
for Example ------>>   any*any or X*X

![resoltion](https://cloud.githubusercontent.com/assets/25039098/22270403/a18c9770-e2a4-11e6-954f-ef2642f63e04.jpg)

**Comment by Bryceless** [comment]
I would like this to happen aswell, so I'm gonna give this a thumbs up!

**Comment by danilaml** [comment]
It'll definitely happen sometime in the future, but it usually introduces a lot of complexity to the renderers (new bugs to fix, new possible scenarios to test), so I'm guessing this not yet a priority. Especially that not many games can run at full speed with their current internal resolution (or just run), which is not even that bad.

**Comment by kd-11** [comment]
Upscaling has been implemented for a while now, so I'll close this one.
