### ISSUE TITLE
NPEB01786 - Dead or alive 5 ultimate - Failed to compile fragment shader

### ISSUE THREAD

**Issue by clienthax** [RPCS3/rpcs3#2284]
After choosing a character on the selection screen.
```
E {rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:92: 'assign' :  cannot convert from 'temp float' to 'inout 4-component vector of float'
ERROR: 1 compilation errors.  No code generated.


E {rsx::thread} RSX: 
F {rsx::thread} class std::runtime_error thrown: Failed to compile fragment shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:475)
```

Log
https://mega.nz/#!bdMBmAzb!9L6o81Rto0MJJ8GeMptLjl-MenKrw7Gbr3Ewvfc3zAU

**Comment by kd-11** [comment]
Need contents of the shaderlog folder. Delete everything in it before running the game and then after the crash attach the contents of the folder. Also, it is usually best to test other backends as well (OGL, DX12) in case we have a bug affecting all of them.

**Comment by clienthax** [comment]
Both set to interpreter, actually got the same error on the main menu this time when selecting fight
vulkan
https://mega.nz/#!vAEwmR7a!GobslOTfPjaJarlOWMkO7c7169AA9EA7SzHKgC350wI

dx (ppu fast, spu asmjit)
right as the main menu is about to show
F {rsx::thread} class std::runtime_error thrown: HRESULT = The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12MemoryHelpers.h:39)
https://mega.nz/#!yQUkDTga!tKqO1iTDmpPQacDT0N8HdqY4CyphHOZ29rmntslF51A

opengl (ppu fast, spu asmjit)
Same behaviour as vulkan
E {rsx::thread} RSX: Failed to compile shader: Fragment shader failed to compile with the following errors:
ERROR: 0:104: error(#160) Cannot convert from: "highp float" to: "inout highp 4-component vector of vec4"
ERROR: error(#273) 1 compilation errors.  No code generated
F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 
https://mega.nz/#!bFUB3IaA!rifXdDD-LwXylAPTPc3k02ePkcRojTJwoUAtPxLNi54

**Comment by darkredflame** [comment]
I'm also having this issue when I try to run Sega Rally Revo Demo [NPUB90055] 

using OGL. Doesn't go to any intros or anything, just crashes on the black screen.

```
E {rsx::thread} RSX: Failed to compile shader: Fragment shader failed to compile with the following errors:
ERROR: 0:43: error(#132) Syntax error: "." parse error
ERROR: error(#273) 1 compilation errors.  No code generated
F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 
```

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/854951/RPCS3.zip)
[shaderlog.zip](https://github.com/RPCS3/rpcs3/files/854952/shaderlog.zip)

**Comment by darkredflame** [comment]
Split/Second Velocity also crashes with a failed to compile fragment shader error message when using OGL. Crashes on black screen. 
[RPCS3-OGL.zip](https://github.com/RPCS3/rpcs3/files/861963/RPCS3-OGL.zip)
[shaderlog.zip](https://github.com/RPCS3/rpcs3/files/861966/shaderlog.zip)

```
E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
E {rsx::thread} RSX: Failed to compile shader: Fragment shader failed to compile with the following errors:
ERROR: 0:44: error(#132) Syntax error: "." parse error
ERROR: error(#273) 1 compilation errors.  No code generated
F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 
```

Vulkan
[RPCS3-Vulkan.zip](https://github.com/RPCS3/rpcs3/files/861974/RPCS3-Vulkan.zip)

```
E {rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:54: '' :  syntax error
ERROR: 1 compilation errors.  No code generated.
E {rsx::thread} RSX: 
F {rsx::thread} class std::runtime_error thrown: Failed to compile fragment shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:472)
```

DX12
[RPCS3-DX12.zip](https://github.com/RPCS3/rpcs3/files/861977/RPCS3-DX12.zip)

```
E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
E {rsx::thread} RSX: FS build failed:D:\RPCS3\FragmentProgram.hlsl(120,53): error X3000: syntax error: unexpected token '.'
D:\RPCS3\FragmentProgram.hlsl(120,49-58): error X3013: 'abs': no matching 0 parameter intrinsic function
D:\RPCS3\FragmentProgram.hlsl(120,49-58): error X3013: Possible intrinsic functions are:
D:\RPCS3\FragmentProgram.hlsl(120,49-58): error X3013:     abs(float|half|double|min10float|min16float|int|uint|min12int|min16int|min16uint)
F {rsx::thread} class std::runtime_error thrown: fragment program compilation failure
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)
```

**Comment by darkredflame** [comment]
Build #2567 bypasses the error messages I submitted above for Sega Rally Revo Demo [NPUB90055] & Split/Second Velocity. Split/Second Velocity goes to the intro screens now before crashing. Sega Rally Revo Demo just spams a bunch of RSX: Src type 3 used error messages.
 
[RPCS3 - SplitSecond.zip](https://github.com/RPCS3/rpcs3/files/863352/RPCS3.-.SplitSecond.zip)
[RPCS3 - Sega Rally.zip](https://github.com/RPCS3/rpcs3/files/863353/RPCS3.-.Sega.Rally.zip)
