### ISSUE TITLE
PS Move controller support/emulation

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#2297]
Today we got first working game, which needs it :P
http://www.emunewz.net/forum/showthread.php?tid=173914&pid=240811#pid240811

**Comment by clienthax** [comment]
Mhm, I did come across what this needs doing the other day, but I'm lacking the equipment to implement it right now

**Comment by kd-11** [comment]
@clienthax You can just set up a debugging tree and ask users to run builds that gather information for you. Its a little slow, but it should get us somewhere since I dont see anyone taking on this one for a while

**Comment by hcorion** [comment]
Initial work for this was done in 504e3112ddc440f1d4eb4f236d4d39ab0f016513 by @VelocityRa

**Comment by dio-gh** [comment]
Referencing #6596 here, it will add a decent amount of improvements to this area. Maybe a checklist could be compiled in the original post to track the support status for each affected game? I don't think there are more than 20-30.

**Comment by marcoluc97** [comment]
#12315
