### ISSUE TITLE
RPCS3 black render on mesa with amdgpu

### ISSUE THREAD

**Issue by giovannilaura** [RPCS3/rpcs3#2311]
Hi folks on amdgpu and Radeonsi setting MESA_GLSL_VERSION_OVERRIDE=430 on latest mesa git  and latest RPCS3 git allows RPCS to start but doesnt render anything (OPENGL) in the log the shader is displayed and sound works without the mesagl override rpcs3 throws an error in glhelper.h and breaks almost istantly on NVIDIA proprietary driver it works fine, any clue?

**Comment by kd-11** [comment]
What error is displayed? We'll need more info to fix the bug.
Attach rpcs3.log

**Comment by Areiser** [comment]
Same here.
btw the error I get on mesa is that the verification fails (with legacy opengl buffers it works). Maybe mesa does not show the OpenGL version it complies to (now 4.5 compliant I think)? Just an idea.
I usually get segementation faults very soon anyways, fixing the linux version is on the roadmap though.

**Comment by giovannilaura** [comment]
Sorry what you mean by with legacy opengl buffers it works?


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Areiser <notifications@github.com> Data: 31/01/17  07:11  (GMT+01:00) A: RPCS3/rpcs3 <rpcs3@noreply.github.com> Cc: giovannilaura <giovanni.nicola@ticino.com>, Author <author@noreply.github.com> Oggetto: Re: [RPCS3/rpcs3] RPCS3 black render on mesa with amdgpu (#2311) 
Same here.

btw the error I get on mesa is that the verification fails (with legacy opengl buffers it works). Maybe mesa does not show the OpenGL version it complies to (now 4.5 compliant I think)? Just an idea.

I usually get segementation faults very soon anyways, fixing the linux version is on the roadmap though.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/RPCS3/rpcs3","title":"RPCS3/rpcs3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/RPCS3/rpcs3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Areiser in #2311: Same here.\r\nbtw the error I get on mesa is that the verification fails (with legacy opengl buffers it works). Maybe mesa does not show the OpenGL version it complies to (now 4.5 compliant I think)? Just an idea.\r\nI usually get segementation faults very soon anyways, fixing the linux version is on the roadmap though."}],"action":{"name":"View Issue","url":"https://github.com/RPCS3/rpcs3/issues/2311#issuecomment-276283576"}}}

**Comment by Areiser** [comment]
Sorry, that was a bit unclear.
I also get an error in glhelper, that the verification fails. If I enable the option "use legacy openGL buffers" (or something like that) in the graphics options, it passes the verification. I got segfaults anyways so I didn't really try to figure out how to solve this yet.

**Comment by kd-11** [comment]
Log file still needed to determine which checks are failing. My guess is that a buffer somewhere is not being initialized. Try running with debug output enabled as well and attach the log.

**Comment by giovannilaura** [comment]
Will do tomorrow thank you veri much


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: kd-11 <notifications@github.com> Data: 31/01/17  11:00  (GMT+01:00) A: RPCS3/rpcs3 <rpcs3@noreply.github.com> Cc: giovannilaura <giovanni.nicola@ticino.com>, Author <author@noreply.github.com> Oggetto: Re: [RPCS3/rpcs3] RPCS3 black render on mesa with amdgpu (#2311) 
Log file still needed to determine which checks are failing. My guess is that a buffer somewhere is not being initialized. Try running with debug output enabled as well and attach the log.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/RPCS3/rpcs3","title":"RPCS3/rpcs3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/RPCS3/rpcs3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kd-11 in #2311: Log file still needed to determine which checks are failing. My guess is that a buffer somewhere is not being initialized. Try running with debug output enabled as well and attach the log."}],"action":{"name":"View Issue","url":"https://github.com/RPCS3/rpcs3/issues/2311#issuecomment-276321960"}}}

**Comment by giovannilaura** [comment]
Here i have added the log with debug output enabled and MESA_GLSL_VERSION_OVERRIDE=450 MESA_GL_VERSION_OVERRIDE=4.5 i have added a print of the gl error at the place where without the override the "verification error" 
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/746091/RPCS3.txt)
 is displayed, i would suggest is it not a shader compiling error?

**Comment by giovannilaura** [comment]
My guess is that mesa supports GLSL up to 330 and the program requires 430 for the shaders, by the way tryiing to compile the shader that is displayed on the log winth mesa GLSL compiler gives error #version must appear on first line

**Comment by giovannilaura** [comment]
My Guess was  wrong here is the shader and the errors generated by mesa glsl compiler maybe this can help? would be nice to get rpcs3 runninf on ati on mesa
[rpcs3shader_iguessvert.txt](https://github.com/RPCS3/rpcs3/files/747072/rpcs3shader_iguessvert.txt)
[shader_error.txt](https://github.com/RPCS3/rpcs3/files/747073/shader_error.txt)

**Comment by kd-11** [comment]
The opengl/glsl version does not matter much if the required extensions are supported.
For rpcs3 you need support for:
GL_ARB_uniform_buffer_object (or GL 3.1)
GL_ARB_explicit_uniform_location (or GL 4.3)
GL_ARB_shading_language_420pack (or GL 4.2)

My guess is that 420pack is not supported by your drivers. Can I take a look at your glxinfo?

**Comment by kd-11** [comment]
By the way GL_ARB_buffer_storage / GL 4.3 is also required for modern persistent mapped buffers

**Comment by kd-11** [comment]
Also, would be better to look at the rpcs3 log with a master build (unmodified). I cannot find the failed verification in the log file and I cannot tell which part failed.

**Comment by giovannilaura** [comment]
You are right advertising this extension makes the errror go away still black rendering though


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: kd-11 <notifications@github.com> Data: 02/02/17  09:36  (GMT+01:00) A: RPCS3/rpcs3 <rpcs3@noreply.github.com> Cc: giovannilaura <giovanni.nicola@ticino.com>, Author <author@noreply.github.com> Oggetto: Re: [RPCS3/rpcs3] RPCS3 black render on mesa with amdgpu (#2311) 
By the way GL_ARB_buffer_storage / GL 4.3 is also required for modern persistent mapped buffers

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/RPCS3/rpcs3","title":"RPCS3/rpcs3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/RPCS3/rpcs3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kd-11 in #2311: By the way GL_ARB_buffer_storage / GL 4.3 is also required for modern persistent mapped buffers"}],"action":{"name":"View Issue","url":"https://github.com/RPCS3/rpcs3/issues/2311#issuecomment-276897618"}}}

**Comment by kd-11** [comment]
Seems to be a mesa bug then. Is the black screen still there when executing the simple test programs like gs_basic_triangle and cube? (found in /dev_hdd0/game/TEST12345/)

**Comment by kd-11** [comment]
Also, radeonsi is supposed to have all the extensions implemented upto GL 4.5 so I don't understand why you're getting bugs unless you advertise a core extension. You seem to be on mesa git too so I'd have expected better compatibility.

**Comment by giovannilaura** [comment]
Also by tring to compile the shader generatd by rpcs3 with the mesa glsl compiler i get vertex streams to 0 so mesa thinks there are no vertex streams strange


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: kd-11 <notifications@github.com> Data: 02/02/17  10:08  (GMT+01:00) A: RPCS3/rpcs3 <rpcs3@noreply.github.com> Cc: giovannilaura <giovanni.nicola@ticino.com>, Author <author@noreply.github.com> Oggetto: Re: [RPCS3/rpcs3] RPCS3 black render on mesa with amdgpu (#2311) 
Seems to be a mesa bug then. Is the black screen still there when executing the simple test programs like gs_basic_triangle and cube? (found in /dev_hdd0/game/TEST12345/)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/RPCS3/rpcs3","title":"RPCS3/rpcs3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/RPCS3/rpcs3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kd-11 in #2311: Seems to be a mesa bug then. Is the black screen still there when executing the simple test programs like gs_basic_triangle and cube? (found in /dev_hdd0/game/TEST12345/)"}],"action":{"name":"View Issue","url":"https://github.com/RPCS3/rpcs3/issues/2311#issuecomment-276903758"}}}

**Comment by giovannilaura** [comment]
And yes no rendering with test prog


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: kd-11 <notifications@github.com> Data: 02/02/17  10:08  (GMT+01:00) A: RPCS3/rpcs3 <rpcs3@noreply.github.com> Cc: giovannilaura <giovanni.nicola@ticino.com>, Author <author@noreply.github.com> Oggetto: Re: [RPCS3/rpcs3] RPCS3 black render on mesa with amdgpu (#2311) 
Seems to be a mesa bug then. Is the black screen still there when executing the simple test programs like gs_basic_triangle and cube? (found in /dev_hdd0/game/TEST12345/)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/RPCS3/rpcs3","title":"RPCS3/rpcs3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/RPCS3/rpcs3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kd-11 in #2311: Seems to be a mesa bug then. Is the black screen still there when executing the simple test programs like gs_basic_triangle and cube? (found in /dev_hdd0/game/TEST12345/)"}],"action":{"name":"View Issue","url":"https://github.com/RPCS3/rpcs3/issues/2311#issuecomment-276903758"}}}

**Comment by kd-11** [comment]
From a quick glance at mesa source that error is supposed to show when you compile as a geometry shader.  Check the compilation flags/switches you are using since it seems the compiler thinks you are compiling a GS.

https://github.com/boombatower/mesa/blob/master/src/glsl/ast_type.cpp#L193-Lundefined

**Comment by giovannilaura** [comment]
Latest update, on mesa 17.0.0 by setting MESA_GL_OVERRIDE=4.5 MESA_GLSL_OVERRIDE=450 and MESA_DEBUG=1 in fllods continuately stdout with the message GL_INVALID_OPERATION unsupported extension or deprecated function and the rendering is black

**Comment by giovannilaura** [comment]
I have a question do you use geometry shaders, if so with the GL_ARB_geometry_shader4 or GL_EXT_geometry_shader4?

**Comment by Gamedev1909** [comment]
i have the same issue im going to try 13.0.5 as 17.0.0 doesnt work

**Comment by giovannilaura** [comment]
I have seen one of the last commits for linux does this fix this bug?

**Comment by Gamedev1909** [comment]
Its not fixed no mesa 13.0.5 and mesa 17 and 17.1 still have the issue

**Comment by kd-11** [comment]
You need this patch https://github.com/kd-11/rpcs3/commit/4e7d22f3a98e18dac5ff890949197b76bb02b407
Mesa is missing GL_EXT_direct_state_access
Also note that you need to enable 4.3 features with MESA_GLSL_VERSION_OVERRIDE=430 and MESA_GL_VERSION_OVERRIDE=4.3
Need to clean up EXT_direct_state_access integration before its part of master though.

**Comment by kd-11** [comment]
![screenshot from 2017-03-04 08-05-13](https://cloud.githubusercontent.com/assets/15904127/23576254/6c3f15d6-00b1-11e7-96aa-0045e8c0ceb4.png)

**Comment by giovannilaura** [comment]
I can confirm it works on mesa 17.0 great work thank!

**Comment by hcorion** [comment]
Bug can be closed, issue was fixed.

**Comment by kd-11** [comment]
Not yet merged upstream

**Comment by hcorion** [comment]
Ah, sorry, assumed it was on upstream.

**Comment by AniLeo** [comment]
This was fixed by #2657 , closing
