### ISSUE TITLE
Verification failed in Thread.cpp

### ISSUE THREAD

**Issue by Areiser** [RPCS3/rpcs3#2314]
Hello, when booting a game in rpcs3 (latest commit 16d15777), I get this error:

RPCS3 v0.0.1-4838-16d15777 Pre-Alpha
F LDR: St13runtime_error thrown: Verification failed (e2): thread_ctrl::start
(in file rpcs3/Utilities/Thread.cpp:1941)

System details: Arch Linux, kernel 4.9.6-1.
Intel i5 4460, Amd R9 270, 8gb ram
Btw in the wiki it says to add "rpcs3.log" to the issue - however, I cannot find this file.

**Comment by Nekotekina** [comment]
Thanks for the report. Will be fixed soon.

**Comment by Areiser** [comment]
Thanks for the fast response and all the work. I will test the new commits/pull requests to check if it is still happening.

**Comment by Areiser** [comment]
Fixed.
