### ISSUE TITLE
Issue for Lone Survivor and other

### ISSUE THREAD

**Issue by Zangetsu38** [RPCS3/rpcs3#2319]
This game works, but have several Issue fatal error and problem.
First issue, error caused violation fatal, Probably caused by "cellGameDataCheck".
>E {PPU[0x1000000] Thread (main_thread) [0x001cad74]} 'cellGameDataCheck' failed with 0x8002cb23 : CELL_GAME_ERROR_BUSY
U {PPU[0x1000000] Thread (main_thread) [0x001cb8f4]} sceNp TODO: sceNpManagerRegisterCallback
U {PPU[0x1000002] Thread (2e200030) [0x001cbb14]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0x291a38, options=0x0)
E {PPU[0x1000002] Thread (2e200030) [0x001cbad4]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x2235f0, arg=*0x0, options=0x1)
F {PPU[0x1000002] Thread (2e200030) [0x0011f46c]} struct vm::access_violation thrown: Access violation reading address 0x28

Second Issue caused by error cellSaveDataAutoSave2
>E {PPU[0x1000008] Thread (2e200030) [0x000857d0]} PPU: 'cellSaveDataAutoSave2' aborted
F {PPU[0x1000008] Thread (2e200030) [0x000857d0]} struct vm::access_violation thrown: Access violation writing address 0x0

And with Savedata exist i have 
>E {PPU[0x1000003] Thread (2e200030) [0x00085fdc]} PPU: 'cellSaveDataAutoLoad2' aborted
F {PPU[0x1000003] Thread (2e200030) [0x00085fdc]} struct vm::access_violation thrown: Access violation writing address 0x0

Third issue caused by RSX, Game Works after press resume two time, but game show color very green
![capture d ecran 2017-02-01 18 34 13](https://cloud.githubusercontent.com/assets/5261759/22518705/e1db2b66-e8ad-11e6-8573-b80332cc7c2b.png)
![capture d ecran 2017-02-01 18 34 24](https://cloud.githubusercontent.com/assets/5261759/22518726/f3d95842-e8ad-11e6-9ce0-d76aeaaf0727.png)

Similar in DMC 4 demo show Blue color
![capture d ecran 2017-01-31 12 29 06](https://cloud.githubusercontent.com/assets/5261759/22518761/14b1ce50-e8ae-11e6-83cc-7f94006eeb59.png)

And last problem have found, sound Ony works in OpenAl, Xaudio 2 have no sound and log have a loop infiny
>W {Audio Thread} XAudio2Thread : too many buffers enqueued (33, pos=0)

Log
[Lone Survivor.txt](https://github.com/RPCS3/rpcs3/files/745626/Lone.Survivor.txt)

**Comment by paulsapps** [comment]
Looks like the blend modes have gone crazy :)

**Comment by Zangetsu38** [comment]
@kd-11 You have any Idea for the screen Green ?

**Comment by kd-11** [comment]
Need traces and logs to debug. I've not experienced it in any title I own.

**Comment by Zangetsu38** [comment]
trace ? and log is already here ^^

**Comment by kd-11** [comment]
Renderdoc trace (opengl, using legacy buffers)

**Comment by Zangetsu38** [comment]
Ah ok i don' have render doc and ok i try this later and after say you :)

**Comment by Zangetsu38** [comment]
[Lone.zip](https://github.com/RPCS3/rpcs3/files/748801/Lone.zip)
@kd-11  First time i do this ^^, it is a good ? :)

**Comment by kd-11** [comment]
Its fine. Looks like we have some blank RTVs, probably the same surface cache problem as Akiba #2325.

**Comment by Zangetsu38** [comment]
@kd-11 Oh ok, you have any idea for fix that ? :)

**Comment by Zangetsu38** [comment]
@kd-11 Please you can look that for Personna 4 arena
Thjis game works before, but now have black screen and only sound
[persona4.zip](https://github.com/RPCS3/rpcs3/files/751148/persona4.zip)

**Comment by kd-11** [comment]
No fixes yet; I'm still quite busy at the moment with other work.

**Comment by Zangetsu38** [comment]
@kd-11 oh ok

**Comment by Zangetsu38** [comment]
@kd-11 I have use you commit for create news renderdoc and log with Personna 4, and i think interstly, log indicate several time texture upload etc...
https://mega.nz/#!QUoSgaqC!MqYOSzi3JrmDjLATksoEQKH2u_ZaupFd9RFnBEr-PuI

**Comment by Zangetsu38** [comment]
@kd-11 I have make same think with Giana Sisters, render ingame this
![capture d ecran 2017-02-04 00 45 33](https://cloud.githubusercontent.com/assets/5261759/22612966/a39c5014-ea74-11e6-8ef7-5af7aceee5c6.png)
And i think very interesting, this game already playable, but very slow, and with you see texture environment missing, but file rdc just big.
https://mega.nz/#!cdwUEYyK!4qe0_2CnsPViA79PmRbS_cQa0ADzeZ06J7ZDDcSfX1s

**Comment by Zangetsu38** [comment]
@kd-11 you have a news for all issue ? :)

**Comment by kd-11** [comment]
Not yet. Still working on the read/write buffers problem at the moment. I'll look at this one once that is resolved.

**Comment by Zangetsu38** [comment]
@kd-11 oh ok but you have a look news renderdoc and log for other game ? ^^ 
For me beach have same problèm with akiba, and persona 4 hve black screen strange, but Rdc, show menu etc. So mabye Orly wrong value return in gcm or other, because before working ^^

**Comment by kd-11** [comment]
The game thinks it can access rsx memory and copies data to cpu and re-uploads. Since we dont write framebuffers to cell visible memory, the game copies blank data and overwrites the stuff we had already properly drawn, so you get black textures. Not sure how many games are actually affected by this, but we can retest once its working.

**Comment by Zangetsu38** [comment]
@kd-11 ok :), I have creatte news log for lone survivor ans bleach, Lone survivor crash in show ingame
[lone1.txt](https://github.com/RPCS3/rpcs3/files/752915/lone1.txt)
[Bleach1.txt](https://github.com/RPCS3/rpcs3/files/752917/Bleach1.txt)
I have selected Debug Uotput :)

**Comment by Zangetsu38** [comment]
bleach have a little progress, now in menu and loading, i see model 3d charachtere (polygone see). but no change view in ingame.
Lone survovr have a crash with this
E {PPU[0x1000000] Thread (main_thread) [0x0007fd90]} RSX: gl::fence sync returned unknown error 0x0
![capture d ecran 2017-02-06 13 19 20](https://cloud.githubusercontent.com/assets/5261759/22646914/135e3bc8-ec6f-11e6-9a1b-502e26e50067.png)

And persona 4 same crash 
![capture d ecran 2017-02-06 13 21 35](https://cloud.githubusercontent.com/assets/5261759/22646959/3b3b45b4-ec6f-11e6-9888-2d4328312016.png)
![capture d ecran 2017-02-06 13 21 39](https://cloud.githubusercontent.com/assets/5261759/22646961/3cc870c8-ec6f-11e6-857d-23eacb3cf334.png)

**Comment by Zangetsu38** [comment]
@kd-11 I have tested in Bakugan Battl, and have good think now :) 
![capture d ecran 2017-02-07 12 18 32](https://cloud.githubusercontent.com/assets/5261759/22689107/c580d2d2-ed2f-11e6-9bf5-6f1f39e59d89.png)
Not perfect but progress, before have just black screen

**Comment by kd-11** [comment]
gl::fence sync crash means the driver is misbehaving. The segfault reading 0x000000 means that the pbo map call failed. I'd like to see the log with debug output (Lone survivor). The crash for persona 4 means we attempted to map more than we allocated which should never happen. I have an idea how that might happen and will work on it some more.

The misaligned tiles (partially white) I suspect are due to downloading data in the wrong format. That also causes a performance hit by the way, so optimizing this is crucial. Overall, alot more work will be needed before this is ready for merging, not to mention integration with vulkan and possibly DX12

**Comment by Zangetsu38** [comment]
[LoneDebug](https://github.com/RPCS3/rpcs3/files/757612/LoneDebug.txt)

**Comment by Zangetsu38** [comment]
@kd-11 with last build i have this on Lone Survivor
>E {PPU[0x1000000] Thread (main_thread) [0x0007fd90]} RSX: gl::fence sync returned unknown error 0x0
F {PPU[0x1000000] Thread (main_thread) [0x0007fd90]} class std::runtime_error thrown: Verification failed: 
(in file g:\git\rpcs3-dante\rpcs3\emu\rsx\gl\GLTextureCache.h:441)

For persona 4
>E {PPU[0x1000000] Thread (main_thread) [0x00a2a73c]} RSX: gl::fence sync returned unknown error 0x0
E {PPU[0x1000000] Thread (main_thread) [0x00a2a73c]} PPU: 'cellGcmGetReport' aborted
F {PPU[0x1000000] Thread (main_thread) [0x00a2a73c]} class std::runtime_error thrown: Verification failed: 
(in file g:\git\rpcs3-dante\rpcs3\emu\rsx\gl\GLTextureCache.h:441)

**Comment by Zangetsu38** [comment]
@kd-11 SplatterHouse have a green screen also, but not in DX12, only OGL
![capture d ecran 2017-02-10 17 10 03](https://cloud.githubusercontent.com/assets/5261759/22834014/1ef6f874-efb4-11e6-8dd0-984c7f71bcfb.png)

**Comment by Zangetsu38** [comment]
@kd-11 I have this with Auditorium HD in  DX12 ans have this error with several game 
E {rsx::thread} RSX: FS build failed:0000000006480c40
F {rsx::thread} class std::runtime_error thrown: fragment program compilation failure
(in file g:\git\rpcs3-dante\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)

**Comment by ikki84** [comment]
@Zangetsu38 If it helps you, There is some logs about F {rsx::thread} D3D12PipelineState.h:162 in
https://github.com/RPCS3/rpcs3/issues/2198
https://github.com/RPCS3/rpcs3/issues/2170

**Comment by Zangetsu38** [comment]
@kd-11  Echochrome woking and playing is a long time, but have a probleme graphical, screen cut.
[echochrome.zip](https://github.com/RPCS3/rpcs3/files/769028/echochrome.zip)
![capture d ecran 2017-02-12 02 35 30](https://cloud.githubusercontent.com/assets/5261759/22858910/054fc432-f0cc-11e6-8862-bcce5cd9dc6e.png)

**Comment by Zangetsu38** [comment]
@kd-11 you have a news for all problem ? :) particular for  Persona 4 and Echochrome possible move playable after fix

**Comment by Zangetsu38** [comment]
@kd-11 with last build, persona 4 and Lone survivor have exactly saqme error
>E {PPU[0x1000000] Thread (main_thread) [0x0007fd90]} RSX: gl::fence sync returned unknown error 0x0
F {PPU[0x1000000] Thread (main_thread) [0x0007fd90]} class std::runtime_error thrown: Verification failed: 
(in file g:\git\rpcs3-dante\rpcs3\emu\rsx\gl\GLTextureCache.h:441)

**Comment by kd-11** [comment]
Retry with PR https://github.com/RPCS3/rpcs3/pull/2391

**Comment by Zangetsu38** [comment]
@kd-11 Retry with Game ? ^^

**Comment by Zangetsu38** [comment]
lone survivor No change, allawys green screen, and with Write color buffers says fatal
>E {PPU[0x1000000] Thread (main_thread) [0x0007fd90]} RSX: gl::fence sync returned unknown error 0x0
F {PPU[0x1000000] Thread (main_thread) [0x0007fd90]} class std::runtime_error thrown: Verification failed: 
(in file g:\git\rpcs3-dante\rpcs3\emu\rsx\gl\GLTextureCache.h:487)

echochrome same also, just no change.

Bakugan with color bufer, Without just black screen again
F {rsx::thread} class std::system_error thrown: device or resource busy: device or resource busy

Persona 4 same
E {rsx::thread} RSX: GL_INVALID_OPERATION error generated. Function glPushAttrib is deprecated and not available in preview contexts.
E {rsx::thread} RSX: GL_INVALID_OPERATION error generated. Function glPopAttrib is deprecated and not available in preview contexts.
E {PPU[0x1000000] Thread (main_thread) [0x00a2a73c]} RSX: gl::fence sync returned unknown error 0x0
F {PPU[0x1000000] Thread (main_thread) [0x00a2a73c]} class std::runtime_error thrown: Verification failed: 
(in file g:\git\rpcs3-dante\rpcs3\emu\rsx\gl\GLTextureCache.h:487)

**Comment by kd-11** [comment]
1. Lone Survivor: glClientWaitSync should never return 0 so the driver is faulty here; I'm assuming Nvidia. glMapBufferRange is also failing and returning 0. However, since the game is attempting to download a texture from GPU memory, I am confident the game will be fixed when issues are ironed out.
2. Bakugan: The error is not specific enough. Will add some debugging information and hopefully we can figure it out.
3. Persona 4: Same as no. 1, misbehaving driver.

In the case of Lone Survivor and Persona 4, enable "Debug Output" so that the driver can give us more information as to why it is failing.

**Comment by Zangetsu38** [comment]
Need Select Legacy also ?

**Comment by kd-11** [comment]
No.. Legacy is only to be used when capturing or for GPU drivers without buffer storage support.
If you were getting the RSXThread crash, it was my fault and has been fixed now.

**Comment by Zangetsu38** [comment]
ok, i compiled and testing all game :) but you branch actually very old, need rebase ^^

**Comment by kd-11** [comment]
Its not a big deal since I expect other commits will be submitted while still in development. I rebase from time to time when a major milestone has been reached to make my work easier.

**Comment by Zangetsu38** [comment]
First, i have test LBP abut no change, graphic have a problem, Sackboy not here in screen, just have a square., but i can jump ^^
![capture d ecran 2017-02-15 18 27 14](https://cloud.githubusercontent.com/assets/5261759/22986671/9b9ca4c2-f3ac-11e6-8536-856dd73e1325.png)
[LBP.txt](https://github.com/RPCS3/rpcs3/files/777855/LBP.txt)

After Tested Infamous and have error RSX method but with hack have this
![capture d ecran 2017-02-15 18 30 38](https://cloud.githubusercontent.com/assets/5261759/22986846/17aad1d8-f3ad-11e6-9782-d1cc06b3a05b.png)
But before logo video playing, video bik, but just black screen, have only sound
[Infamous.txt](https://github.com/RPCS3/rpcs3/files/777864/Infamous.txt)

After for Persona 4 have a crash with this 
![capture d ecran 2017-02-15 18 33 51](https://cloud.githubusercontent.com/assets/5261759/22986930/6bd74c32-f3ad-11e6-8d07-7ce9b12e72c7.png)
[persona 4.txt](https://github.com/RPCS3/rpcs3/files/777875/persona.4.txt)

Killzone HD tested and have menu and posible ingame, i see model 3d but very buged and glitched.
And i have Crash with last you commit ogl, and error in vulkan.
Screen yesterday
![capture d ecran 2017-02-14 23 23 12](https://cloud.githubusercontent.com/assets/5261759/22987177/360fbc64-f3ae-11e6-983d-8d6dc4720832.png)
![capture d ecran 2017-02-14 23 33 31](https://cloud.githubusercontent.com/assets/5261759/22987178/396dcb6c-f3ae-11e6-9557-9d3d5805c265.png)

Screen here now
![capture d ecran 2017-02-15 18 37 04](https://cloud.githubusercontent.com/assets/5261759/22987120/0a4f0b84-f3ae-11e6-84b6-1a0898a0c490.png)
![capture d ecran 2017-02-15 18 37 07](https://cloud.githubusercontent.com/assets/5261759/22987117/0710ced0-f3ae-11e6-9f51-c9d05b459530.png)

For Lone survivor have this, a crash
[Lone.txt](https://github.com/RPCS3/rpcs3/files/777910/Lone.txt)
![capture d ecran 2017-02-15 18 42 27](https://cloud.githubusercontent.com/assets/5261759/22987291/8f008330-f3ae-11e6-926f-4e91a6a04cf8.png)

Akiba no have any change, need character nothing
[akiba.txt](https://github.com/RPCS3/rpcs3/files/777928/akiba.txt)

Bleach same, and with libfont menu freeze in moment show character and other text
[Bleach.txt](https://github.com/RPCS3/rpcs3/files/777940/Bleach.txt)

**Comment by Zangetsu38** [comment]
Midnight Club have this error with GL and Vulkan have same also, same other game 
>E {rsx::thread} RSX: Failed to compile shader: 0(261) : error C1115: unable to find compatible overloaded function "textureGrad(sampler2D, vec3, float, float)"
0(262) : error C1115: unable to find compatible overloaded function "textureGrad(sampler2D, vec3, float, float)"
F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
0(261) : error C1115: unable to find compatible overloaded function "textureGrad(sampler2D, vec3, float, float)"
0(262) : error C1115: unable to find compatible overloaded function "textureGrad(sampler2D, vec3, float, float)"
(0) : error C2003: incompatible options for link

**Comment by Zangetsu38** [comment]
@kd-11 Update Persona 4
[Persona4Log.zip](https://github.com/RPCS3/rpcs3/files/781218/Persona4.zip)
First logo and intro it is a cuted, after in menu, no correct proportion
![capture d ecran 2017-02-16 19 44 58](https://cloud.githubusercontent.com/assets/5261759/23036130/e7552e40-f481-11e6-9995-680463126cd3.png)
![capture d ecran 2017-02-16 19 45 06](https://cloud.githubusercontent.com/assets/5261759/23036132/e859e4d4-f481-11e6-9c00-4fbfceaa8692.png)
![capture d ecran 2017-02-16 19 47 07](https://cloud.githubusercontent.com/assets/5261759/23036158/027ae9da-f482-11e6-830f-5e94716b72d3.png)

![capture d ecran 2017-02-16 19 49 20](https://cloud.githubusercontent.com/assets/5261759/23036173/0dc04fd8-f482-11e6-90db-d76b9c9e8cb5.png)
![capture d ecran 2017-02-16 19 52 52](https://cloud.githubusercontent.com/assets/5261759/23036174/0fcd70d0-f482-11e6-9769-82f4331a4c45.png)

**Comment by Zangetsu38** [comment]
@kd-11 Jet set radio fixed also 
[JetSet.txt](https://github.com/RPCS3/rpcs3/files/781250/JetSet.txt)
![capture d ecran 2017-02-16 20 00 01](https://cloud.githubusercontent.com/assets/5261759/23036374/de892c5c-f482-11e6-891c-7cf93ff3632a.png)
![capture d ecran 2017-02-16 20 01 47](https://cloud.githubusercontent.com/assets/5261759/23036376/e0b7c3da-f482-11e6-8985-081af5fee01b.png)

**Comment by Zangetsu38** [comment]
@kd-11 Good news, with last commit nv, black screen echochrome fixed, but have a glitch graphical
All render have same thinks 
[EchoOGL.txt](https://github.com/RPCS3/rpcs3/files/785212/EchoOGL.txt)
[EchoVK.txt](https://github.com/RPCS3/rpcs3/files/785214/EchoVK.txt)
![capture d ecran 2017-02-18 18 50 48](https://cloud.githubusercontent.com/assets/5261759/23095550/fbd1f5fc-f60b-11e6-85d1-1e0f03170957.png)
![capture d ecran 2017-02-18 18 51 19](https://cloud.githubusercontent.com/assets/5261759/23095552/fe49b18a-f60b-11e6-91de-71254a77877d.png)
![capture d ecran 2017-02-18 18 51 32](https://cloud.githubusercontent.com/assets/5261759/23095553/01672690-f60c-11e6-9af7-2e1f0a9f8253.png)

**Comment by kd-11** [comment]
Looks like nv3089::image_in aka nv30_scaled_image_from_memory still needs a little more work judging by echochrome output.

**Comment by SakataGintokiYT** [comment]
@Zangetsu38 
Nekotekina WIP + KD-11 WIP 
Write color buffer is required
<img src="http://www.fotoszok.pl/upload/25f6cabd.jpg" alt="Fotoszok.pl" />

**Comment by raven02** [comment]
@Zangetsu38 , is there still any issue for the title - Lone Survivor  ? if no , please close it as this thread messed up with lots of other game testing .

**Comment by digitaldude555** [comment]
![screenshot 824](https://cloud.githubusercontent.com/assets/26138653/23504787/a1f1eb86-ff49-11e6-8473-db440fc6f740.png)

Still Green.

**Comment by raven02** [comment]
How about DX12 and Vulkan ?

**Comment by digitaldude555** [comment]
![screenshot 825](https://cloud.githubusercontent.com/assets/26138653/23505902/4f67f220-ff4e-11e6-82fd-252164bd313e.png)
![screenshot 826](https://cloud.githubusercontent.com/assets/26138653/23505907/52b7e2d2-ff4e-11e6-8349-09b06c789706.png)

all green.

**Comment by raven02** [comment]
Thanks for testing it out.

**Comment by MarioSonic2987** [comment]
Is it still an issue?

**Comment by Zangetsu38** [comment]
Lone surviror have fatal error, and now with commit reservation, it is imposible press resume, so regression for this game

**Comment by AniLeo** [comment]
@Zangetsu38 can you test again?

**Comment by Zangetsu38** [comment]
Lone Survivor fixed only in PR https://github.com/RPCS3/rpcs3/pull/3294

**Comment by SakataGintokiYT** [comment]
@Zangetsu38 
Can you retest with latest master.

**Comment by Zangetsu38** [comment]
already tested and works
