### ISSUE TITLE
Bug On Screen Keyboard (OSK)

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2321]
Hi
After insert Name in dialog box and ok 
My Write String no Show in game and game wait

![2](https://cloud.githubusercontent.com/assets/25039098/22523545/05a8dd00-e8d5-11e6-9f72-029897d52a64.jpg)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/745967/RPCS3.zip)

**Comment by al0xf** [comment]
I can confirm the issue, and also notice the TTY message "system notification: unknown status". The error occurs even when canceling input without writing anything.

**Comment by georgemoralis** [comment]
i am looking at it

**Comment by MarioSonic2987** [comment]
In Worms Ultimate Mayhem occurs a strange bug with OSK: https://youtu.be/CLbkkxlvkV0

**Comment by al0xf** [comment]
I don't understand what the problem is. From the video it just looks like
the game doesn't like input over a certain length? Please explain clearly
what "a strange bug means" and please run the game in English so anyone can
understand what it says.


And of course attach the log file.

**Comment by MarioSonic2987** [comment]
@al0xf 
I put S key as the circle button and if I write words which have an **S**, input is detected and I can't create a team with that name

**Comment by MarioSonic2987** [comment]
Ok, the workaround that I made is copying that letter somewhere and the game doesn't detect that I press circle button.

**Comment by MarioSonic2987** [comment]
Here's my key config:
![](http://i.imgur.com/OtYYku0.png)

**Comment by MarioSonic2987** [comment]
https://gist.github.com/MarioSonic2987/5c24dfab49cbbe444d65d03a1bf9a30a#file-log-wum-4-3-17

**Comment by aakh1361** [comment]
Now fix and go to ingame
![0](https://cloud.githubusercontent.com/assets/25039098/23911561/7436be76-08f2-11e7-9130-c0fe1fffc717.jpg)

![1](https://cloud.githubusercontent.com/assets/25039098/23911848/48d35fae-08f3-11e7-8eef-b310f7c03761.jpg)
