### ISSUE TITLE
Regression: Significant performance drop on recent builds

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#2322]
While investigating performance bottlenecks in RsxThread I noticed that recent builds are rather slow compared to older builds from last year. I haven't bisected to find the commit that introduces this yet.
This is very noticeable on the car selection screen in outrun: online arcade where previously we got about 45 fps (opengl) but now only can manage 15 fps (12 with vulkan). I also noticed this slowdown on some youtube videos of hitman 2. Can any testers confirm this isnt an issue with my build?

@SakataGintokiYT 
@Zangetsu38

**Comment by aakh1361** [comment]
Hi
I don't use of old build and unknown speed is low
but it is my test game 
I hope that will help you

cpu xeon e5450 quad
ram 16 gig
video 780 ti oc

http://www.emunewz.net/forum/showthread.php?tid=163866&pid=241520#pid241520

**Comment by SakataGintokiYT** [comment]
@kd-11 
Performance drop after merge this commit : https://github.com/RPCS3/rpcs3/commit/1c14d872a852ae7cd5c9281dc14de8077b4d65a9

**Comment by Nekotekina** [comment]
Try to replace shared_mutex with

```C++
#include <shared_mutex>
using std::shared_mutex;
using reader_lock = std::shared_lock<std::shared_mutex>;
using writer_lock = std::lock_guard<std::shared_mutex>;
```
Possibly, only in some places. I recommend the latest commit.
I don't have a good material to test.

**Comment by SakataGintokiYT** [comment]
@Nekotekina 
Can you make test build

**Comment by raven02** [comment]
I tested the latest build and the car selection scene seems to be back to normal speed . I got 36-37 using Vulkan renderer . 

Dragon Ball Z : Burst Limit also get much better speed when compared to the old build

**Comment by Zangetsu38** [comment]
@raven02 no change for me 19 22 fps , same before ^^

**Comment by kd-11** [comment]
I will retest with latest master later.

**Comment by raven02** [comment]
Here it is from the car selection scene

![untitled](https://cloud.githubusercontent.com/assets/3000282/22626967/96ee844c-ebf3-11e6-8613-e72656f949d2.jpg)

**Comment by kd-11** [comment]
@raven02  This isn't fixed. Its improved a bit, but not fixed. If you let the car sit on the selection screen for a few seconds, performance tanks significantly. When testing on my main PC, performance is now stable around 25-35 fps while before it was 50-60. Its getting there, but not quite yet.

**Comment by raven02** [comment]
how about the one with ppl fix in latest build now ? it seems to be better

**Comment by kd-11** [comment]
That's the one I'm saying is better. Tested with build from https://github.com/RPCS3/rpcs3/pull/2351

**Comment by raven02** [comment]
I just retested it and i don't have any frame drop in the car selection scene . @kd-11 , how's your ?

**Comment by raven02** [comment]
@kd-11 , does it work good from you side ?

**Comment by kd-11** [comment]
Performance looks to be better than before on games that I can test at the moment. Will re-open if any issues persist.
