### ISSUE TITLE
GL: Eat Lead: The Return of Matt Hazard - Almost black rendering ingame

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2324]
Tested on: https://github.com/RPCS3/rpcs3/commit/9eba0ac58ce92140b3e24d2e6fa489ef3d69e480

@kd-11 if you need more info tell me

![eat lead 1](https://cloud.githubusercontent.com/assets/11453507/22557481/f6128e36-e96a-11e6-89d0-bf7d01d9851d.PNG)

[Renderdoc ingame captured frame 1 OGL](https://mega.nz/#!6IdxQD4S!FZpltDpKqwMqBtBqXX2sNXNGSNzePojzwx4YqVFVdFs)
[Renderdoc ingame captured frame 2 OGL](https://mega.nz/#!TZVxxb7Q!FF_0CLigATOkeVQJsF6ZJ_s43_9mtht6E8AHPNH9hdg)

[LOG](https://mega.nz/#!PYV2mSIa!CuigBT1CCuaWFQfRkaeDW08VSKDy9VtjaztESo8LOxA)

**Comment by kd-11** [comment]
Problem might be similar to #2325, where we have black post-process layers due to broken texture upload/surface creation routines. I have some ideas, but it'll be a few days before I have anything usable.

**Comment by kd-11** [comment]
Actually upon further investigation, this may be unrelated.

**Comment by kd-11** [comment]
Broken 1D texture used as a lookup for post-processing. Will look into it.

**Comment by JohnGodgames** [comment]
With [gl: Manage RTV subviews as temporary resources](https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-437/artifacts)

![eatl1](https://cloud.githubusercontent.com/assets/11453507/23122836/2c81fafc-f766-11e6-9d40-59da6e4d0457.PNG)

![eatl2](https://cloud.githubusercontent.com/assets/11453507/23122838/30ae89c4-f766-11e6-805c-3db66a52d44f.PNG)

[LOG](https://mega.nz/#!LF8ShDxR!8_cKnKKIB-uSUzHKWPaVPXJxhzthmjhQipgNof21PHo)

**Comment by kd-11** [comment]
Looks like a texture format mismatch occured somewhere.

**Comment by raven02** [comment]
And for Vulkan , it even cannot reach the title screen with vertex buffer error.

> F {rsx::thread} class std::runtime_error thrown: vertex buffer not found
> (in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKProgramPipeline.cpp:104)
>

**Comment by raven02** [comment]
This title screen composed of CELL_GCM_TEXTURE_B8 and CELL_GCM_TEXTURE_A8R8G8B8

**Comment by digitaldude555** [comment]
Using build b7f87206
![screenshot 908](https://cloud.githubusercontent.com/assets/26138653/23634523/48db7426-02d3-11e7-8822-12cb1ace4573.png)

![screenshot 910](https://cloud.githubusercontent.com/assets/26138653/23634526/4eec1910-02d3-11e7-9a88-17955629c75e.png)

improvement?

**Comment by kd-11** [comment]
Still an issue?

**Comment by Asinin3** [comment]
@kd-11 Yes, no change with Strict Rendering Mode or Write Color Buffers.

OGL:
![rpcs3_2017-09-07_20-40-05](https://user-images.githubusercontent.com/15137035/30160724-e5ea5b4a-940c-11e7-9180-5de278a7c895.png)

VK:
![rpcs3_2017-09-07_20-37-58](https://user-images.githubusercontent.com/15137035/30160721-e21f5f60-940c-11e7-8486-cf74fe828f27.png)

**Comment by SakataGintokiYT** [comment]
**Build: v0.0.5-6541 (5f04703) Alpha [2018-03-13]**

 **VK:**
![bez tytulu](https://user-images.githubusercontent.com/13681488/37478752-644f95b0-287b-11e8-855b-96e8934c56d8.png)
________________________________________________________________________________________________________________
**OGL:**
![2](https://user-images.githubusercontent.com/13681488/37478756-668bc54c-287b-11e8-966f-5da6de790219.png)

**Comment by AniLeo** [comment]
Reported fixed, closing
