### ISSUE TITLE
DX12/GL/VK: Akiba's Trip: Undead & Undressed - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2325]
Tested on: https://github.com/RPCS3/rpcs3/commit/9eba0ac58ce92140b3e24d2e6fa489ef3d69e480

@kd-11 if you need more info tell me

**PS3:**
![akiba 1](https://cloud.githubusercontent.com/assets/11453507/22558739/14ca040e-e96f-11e6-8dd2-71c58edd89ab.PNG)

**RPCS3 OGL/VK/DX12:**
![akiba 1_2](https://cloud.githubusercontent.com/assets/11453507/22558741/14cbe530-e96f-11e6-9d55-f8e1aa63ae6c.PNG)

**PS3:**
![akiba 2_1](https://cloud.githubusercontent.com/assets/11453507/22558738/14c89100-e96f-11e6-946b-6b570303dee7.PNG)

**RPCS3 OGL/VK/DX12:**
![akiba 2_2](https://cloud.githubusercontent.com/assets/11453507/22558740/14ca91e4-e96f-11e6-9163-e5457c2ec3a0.PNG)

[Renderdoc menu captured frame OGL](https://mega.nz/#!6I9klZgA!67ZgeeOPOiR5H8cMMj1sdS3QRLSu_8cGmGGTGSuOaFs)
[Renderdoc ingame captured frame OGL](https://mega.nz/#!TFtj0SrZ!yJQSQR3SOQEOye1tTHsImW5Bp_FdsBN-UfG7Y8Wj-P8)

[LOG](https://mega.nz/#!mRsVAZYT!kqVSSeEz-4dCLnFJHqpU3hTR044sF_SG1emPjr49EjY)

**Comment by kd-11** [comment]
The problem here is easily visible @ EID 9451 on the menu.
The game tries to upload a texture from render target that was supposed to have been cached, but instead uploads garbage (all zeros) implying we missed the surface in the cache. This might be an interesting corner-case for our surface cache. I'll have to review the code and write a few tests for this.

**Comment by Zangetsu38** [comment]
Bleach have same issue, black screen and show only HUD and other little effect but not texture model 3d character and other

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-395
Should dump alot of info to the log file at error notification level. Also forces read_buffer behaviour upon surface creation which will slow things down alot, but I'm more interested in the data collected. A renderdoc trace of this game's menu with this build would also be of great help. Cheers.

**Comment by JohnGodgames** [comment]
More info from https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-395

[Menu capture](https://mega.nz/#!3VMRmDKB!eQZy5Fsfc6F4bHp1Vq3yA268PduVY_GohF_VTW37Bh8)
[LOG](https://mega.nz/#!qF1RGSpR!av9WlE_kFpEZbP7VkGvylpIu4JgHfNo3_jVMymSAGz8)

**Comment by kd-11** [comment]
Looks like my hunch was correct; this game relies on read/write buffers behaviour. It seems after the first color pass to draw the background, the game copied the framebuffer to another memory location, altered the image using the cpu and attempted to upload the result and use it in a render. The test case writes recognizable pattern to the framebuffer location in cell memory space so I could detect attempts to re-upload. This is actually good since it will give a good test case for properly implementing this feature.

**Comment by kd-11** [comment]
First attempt at fixing this https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-396
I'm not able to properly test the behavior of attempted read access on framebuffers, but I hope this does not crash anything. This particular build forces write_color_buffers behaviour and hopefully does something for this game. If the game does not crash, a trace of the menu would be of great help.

**Comment by kd-11** [comment]
Second attempt https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-398

**Comment by JohnGodgames** [comment]
Both of attempts crash for me:
```
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000000 at 00007ffb4e8ac387.
Instruction address: 00007ffb4e8ac387.
Function address: 00007ffb4e8ac330 (base+0xc330).
Module name: 'VCRUNTIME140.dll'.
Module base: 00007ffb4e8a0000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------
```

**Comment by kd-11** [comment]
I'm looking into it

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-402
Rough testing build, with hacky texture pitch implementation. Should technically resolve the blank outputs. Needs alot of work and optimization before it'll be ready for prime time though. Leave all the read/write buffer options disabled since it enforces buffer synchronization forcefully.

**Comment by Zangetsu38** [comment]
works better, charactere show, not correctly but it is a progress, and after rpcs3 freeze ^^

**Comment by kd-11** [comment]
@Zangetsu38 https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-403
You have to enable "write color buffers" to get the framebuffer sync working. Its still very unfinished, but I'd like to hope it solves this problem.
The freezing may be because that branch is based on old version of master, so just the menu is fine.
Also, please show screenshots of any graphical problems.

**Comment by Zangetsu38** [comment]
I have nothing in select character, same before

**Comment by kd-11** [comment]
@Zangetsu38 enable "write color buffers" with the new build to force synchronization. If that does not work, I'll have to work on it some more if it does not work.
You mentioned that https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-402 showed character with glitches, so It'd be helpful if you attach screenshots from that build

**Comment by Zangetsu38** [comment]
no, i have last commit, not worry ^^, and sorry, i have need selected whrite color before launch game, strange ^^
![capture d ecran 2017-02-06 13 05 12](https://cloud.githubusercontent.com/assets/5261759/22646599/7dac6376-ec6d-11e6-9fa0-7bf2b78f8799.png)
![capture d ecran 2017-02-06 13 07 23](https://cloud.githubusercontent.com/assets/5261759/22646602/7f49e6e0-ec6d-11e6-9361-410eb026e33c.png)

**Comment by kd-11** [comment]
This is actually pretty good. The white color is intentional. I set it to the buffer because I could not properly calculate the expected image size. The extra regions are white, but obviously I need to do more work when fetching images.

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-408
Hopefully affects the alignment of the background. Should also reduce flickering, but probably won't completely eliminate it since its still a bit hacky.

**Comment by kd-11** [comment]
Retry with PR https://github.com/RPCS3/rpcs3/pull/2391

**Comment by Zangetsu38** [comment]
ok, i try and you need rebase ^^

**Comment by Zangetsu38** [comment]
No change, show nothing texture or charachtere.

**Comment by Zangetsu38** [comment]
Need select Color buffer or not ?

**Comment by kd-11** [comment]
Yes, Needs "Write Color Buffers" set

**Comment by Zangetsu38** [comment]
No change for it, pervious commit show character, but actually nothing
![capture d ecran 2017-02-16 14 21 21](https://cloud.githubusercontent.com/assets/5261759/23023121/480d9502-f454-11e6-9b14-01a66d176c14.png)
![capture d ecran 2017-02-16 14 21 32](https://cloud.githubusercontent.com/assets/5261759/23023122/49e1e216-f454-11e6-913e-8fb8ae102357.png)
![capture d ecran 2017-02-16 14 25 41](https://cloud.githubusercontent.com/assets/5261759/23023127/4ceb7d96-f454-11e6-96f8-b2c278f46456.png)
[akiba.txt](https://github.com/RPCS3/rpcs3/files/780213/akiba.txt)

**Comment by kd-11** [comment]
Akiba should show graphics with current master. Probably still some minor glitches but something should still show.

**Comment by JohnGodgames** [comment]
https://github.com/RPCS3/rpcs3/commit/40a84dd477a9e53c354def845f239f34b9601a29

with write color buffers enabled

![akiba trip 1](https://cloud.githubusercontent.com/assets/11453507/23823559/46200414-0665-11e7-8c66-dc7f5b7ee8e0.PNG)
![akiba trip 2](https://cloud.githubusercontent.com/assets/11453507/23823560/4620d40c-0665-11e7-82b2-0430e4b8f4ab.PNG)

**Comment by Zangetsu38** [comment]
yes, little better, but what have this slow fps for this game ? no compliqued render 3d strange, catherine have 20 fps in 3d game

**Comment by kd-11** [comment]
Maybe uses the blit engine alot. It can make 2d games drop from 100fps to 3fps.
I'll start work on it when the current PR is ready.

**Comment by kd-11** [comment]
This is fixed in current master
