### ISSUE TITLE
GL: Bakugan: Defenders of the Core - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2327]
Tested on: https://github.com/RPCS3/rpcs3/commit/9eba0ac58ce92140b3e24d2e6fa489ef3d69e480

![bakugan defenders 1](https://cloud.githubusercontent.com/assets/11453507/22565160/7e4c97d0-e987-11e6-893f-ae8ba253370f.PNG)
![bakugan defenders 2](https://cloud.githubusercontent.com/assets/11453507/22565162/7e55ece0-e987-11e6-801e-639c203d316c.PNG)
![bakugan defenders 3](https://cloud.githubusercontent.com/assets/11453507/22565161/7e54abf0-e987-11e6-900b-6ecd42934e0d.PNG)

[Renderdoc ingame captured frame OGL](https://mega.nz/#!6U8xFR6C!TWqyvI1H4Mo6hC-eCmMR3xj4i_W9lU-Clw2Ax8LRrTg)

[LOG](https://mega.nz/#!mcEhRSiB!Op1emk9w8kCdfGIZSNs2mIAimzSYqU4T5XwZWp96cAo)

**Comment by AniLeo** [comment]
@JohnGodgames Is this still an issue?

**Comment by Zangetsu38** [comment]
no now works

**Comment by Zangetsu38** [comment]
hmm last time teste is good, but now have problem, game crashed and freezed randomly :/

**Comment by AniLeo** [comment]
But are the graphics still broken or not?

**Comment by Zangetsu38** [comment]
i have only see choice charachtere, after rpcs3 crached
