### ISSUE TITLE
Killzone 2 - PPU: 'cellSaveDataUserAutoLoad' aborted

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2329]
Tested on: https://github.com/RPCS3/rpcs3/commit/9eba0ac58ce92140b3e24d2e6fa489ef3d69e480

```
E {PPU[0x1000010] Thread (SaveData Engine Thread) [0x00bb67a4]} cellSaveData: cellSaveDataUserAutoLoad(version=0, userId=0, dirName=“BCAS20066-KILLZONE2”, errDialog=0, setBuf=*0xd00e3d40, funcStat=*0xe84330, funcFile=*0xe84338, container=0xffffffff, userdata=*0xfae4a8)
E {PPU[0x1000010] Thread (SaveData Engine Thread) [0x00bb67a4]} PPU: 'cellSaveDataUserAutoLoad' aborted
F {PPU[0x1000010] Thread (SaveData Engine Thread) [0x00bb67a4]} class std::logic_error thrown: fs::file is null
```

[LOG](https://mega.nz/#!icMwXBRJ!Suz1PL9Hvf58IXVYEcVnOZ32LMlBWw5phaMLTRgRzwg)

**Comment by georgemoralis** [comment]
will check it

**Comment by AniLeo** [comment]
Can someone retest this?

**Comment by scribam** [comment]
Tested on 9747ab6.
The game can process further, the error above is not here anymore. However, there is still an issue as the screen stays black.

[BCES00081.txt](https://github.com/RPCS3/rpcs3/files/1166756/BCES00081.txt)

**Comment by AniLeo** [comment]
Closing then since this issue got fixed.
