### ISSUE TITLE
GL: Bodycount - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2331]
Tested on: https://github.com/RPCS3/rpcs3/commit/9eba0ac58ce92140b3e24d2e6fa489ef3d69e480

Sometimes is throwing:
```
F {rsx::thread} class std::runtime_error thrown: Unknown index array type 104
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:26)
```

**PS3:**

![bodycount 2](https://cloud.githubusercontent.com/assets/11453507/22568098/c27456a4-e992-11e6-9c47-236da831d099.PNG)

**RPCS3 OGL:**

![bodycount 1](https://cloud.githubusercontent.com/assets/11453507/22568102/caac5ff6-e992-11e6-9713-bb6d434154e8.PNG)

![bodycount 3](https://cloud.githubusercontent.com/assets/11453507/22568304/9bf8ccb6-e993-11e6-8841-c7ab1744ed2c.PNG)

[Renderdoc ingame captured frame OGL](https://mega.nz/#!TFtj0SrZ!yJQSQR3SOQEOye1tTHsImW5Bp_FdsBN-UfG7Y8Wj-P8)

[LOG](https://mega.nz/#!qc1XDBDQ!bDZ8Rh46ytOoDPLdDko6aZtbpMufySjqWk-sgKitrKs)

**Comment by kd-11** [comment]
The unaccounted for index format is most likely responsible for the missing geometry. The rest is broken postfx.

**Comment by Xcedf** [comment]
Some of issues are fixed 
![33](https://user-images.githubusercontent.com/7060586/28049900-1b6f8548-6603-11e7-8446-51f2f0ce0577.jpg)
![34](https://user-images.githubusercontent.com/7060586/28049903-1e5ae87e-6603-11e7-8dd1-93407bb5ecc7.jpg)

on the latest mster

**Comment by JohnGodgames** [comment]
Yeah it's a lot of better.

https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-5320/artifacts

[![bionic commando](https://img.youtube.com/vi/wdw6ypd3lFE/0.jpg)](https://www.youtube.com/watch?v=wdw6ypd3lFE)

**Comment by Xcedf** [comment]
flickering textures are also fixed now by https://github.com/RPCS3/rpcs3/pull/3057, only green overlay left
![34](https://user-images.githubusercontent.com/7060586/28489295-787d4120-6ec9-11e7-934f-132c30429b4a.jpg)

**Comment by kd-11** [comment]
Green overlay tracked here https://github.com/RPCS3/rpcs3/issues/3031
