### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2334]
Give Me Fatal Error in Game "Tennis in the Face"
![11](https://cloud.githubusercontent.com/assets/25039098/22602634/45038e52-ea59-11e6-8077-3d731cea009a.jpg)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/751218/RPCS3.zip)

Link Intel My Prossesor
http://ark.intel.com/products/33083/Intel-Xeon-Processor-E5450-12M-Cache-3_00-GHz-1333-MHz-FSB

**Comment by SakataGintokiYT** [comment]
This is a problem with SaveData 

@gmoralis  Can you check this .

**Comment by aakh1361** [comment]
what i am doing ?
is  SaveData  Lib*.PRX ?

**Comment by aakh1361** [comment]
I Have Same Error in Other Game "Girl Fight"
![00](https://cloud.githubusercontent.com/assets/25039098/22605162/e16dd28e-ea63-11e6-95f0-85a0b7fc0be9.jpg)

**Comment by georgemoralis** [comment]
will look at

**Comment by AniLeo** [comment]
Well, you're missing cellFont LLE there being the last entry on your log console.
That probably needs a stacktrace, the error doesn't mean much by itself

**Comment by aakh1361** [comment]
I Add cellFont But same Error show me

**Comment by elfogames** [comment]
are you using xaudio2?

**Comment by aakh1361** [comment]
Yes

**Comment by PZerua** [comment]
What is the last time you downloaded RPCS3? Are you using latest build?

**Comment by aakh1361** [comment]
I Every Day Download Last RPCS3
I Have This Problem Just This Two Games And Other Games not Problem

**Comment by aakh1361** [comment]
PAC-MAN Championship Edition DX Have This Error

![er](https://cloud.githubusercontent.com/assets/25039098/22635532/5747363a-ec49-11e6-9000-473663b5b2d3.jpg)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/753686/RPCS3.zip)

**Comment by aakh1361** [comment]
Galaga Legions DX Trial
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/753736/rpcs3.zip)
![1](https://cloud.githubusercontent.com/assets/25039098/22636184/b112dd90-ec4e-11e6-98cf-835536df4b67.jpg)

**Comment by raven02** [comment]
i'm closing this .Please discuss in http://www.emunewz.net/forum/forumdisplay.php?fid=162
