### ISSUE TITLE
heavenly sword cant run on GL FRAME render on interpeter fast

### ISSUE THREAD

**Issue by DarkSt1ar** [RPCS3/rpcs3#2335]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault writing location 0000000000000000 at 0000000000000000.
Instruction address: 0000000000000000.
RPCS3 image base: 0000000000010000.

---------------------------
i searched alot and found that i can run heavenly sword at any specs becoase its 2007 old game i am trying to make it work on OPENGL RENDER but it gives me error i checked the LLS MODELS before but
didnt work then i didnt check them it didnt work also and gave me the same error i putted the game 
in dev_hdd0 file as i saw in some videos online and i run the game on icore 3 2.10ghz 4gb ram intel core 3000 toshiba laptop model 2013 and here are screen shots
![untitle1d](https://cloud.githubusercontent.com/assets/25539272/22612705/1534ea8c-ea7b-11e6-818c-9693eb53e187.png)
![untitle2d](https://cloud.githubusercontent.com/assets/25539272/22612710/1e28ab88-ea7b-11e6-9798-634ad28f8e44.png)
![untitled](https://cloud.githubusercontent.com/assets/25539272/22612717/26d9b268-ea7b-11e6-87f2-14721268dfb1.png)

and here is the full error
RPCS3 v0.0.1-3-3762f1e Pre-Alpha
U LDR TODO: 'Hook static functions' option deactivated
E {PPU[0x1000000] Thread (main_thread) [0x00a3fee8]} sys_mutex: sys_mutex_create(): unknown attributes (recursive=0x10, pshared=0x200, adaptive=0x2000, ipc_key=0xf44304, flags=0x0)
U {PPU[0x1000000] Thread (main_thread) [0x00e6f2e0]} sysPrxForUser TODO: _sys_process_atexitspawn()
E {PPU[0x1000000] Thread (main_thread) [0x00e6e200]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x1000000] Thread (main_thread) [0x00e6e200]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x1000000] Thread (main_thread) [0x00e6e200]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x1000000] Thread (main_thread) [0x00e6e200]} sys_spu: Unsupported SPU Thread options (0x2)
E {PPU[0x1000000] Thread (main_thread) [0x00e6e200]} sys_spu: Unsupported SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00e6eb80]} cellSpurs TODO: cellSpursGetInfo
U {PPU[0x1000000] Thread (main_thread) [0x00e6eb60]} cellSpurs TODO: cellSpursRequestIdleSpu
U {PPU[0x1000000] Thread (main_thread) [0x00e6ed80]} cellSpurs TODO: cellSpursSetExceptionEventHandler
E {PPU[0x1000000] Thread (main_thread) [0x00a3fee8]} sys_mutex: sys_mutex_create(): unknown attributes (recursive=0x10, pshared=0x200, adaptive=0x2000, ipc_key=0x1025f784, flags=0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00e6e820]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x00e6e820]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x00e6e820]} cellGcmSys: cellGcmSetTile: bad compression mode! (9)
U {PPU[0x1000000] Thread (main_thread) [0x00e6e840]} cellGcmSys TODO: cellGcmSetZcull(index=0, offset=0xbb0000, width=1280, height=768, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x201, sRef=0x80, sMask=0xff)
E {PPU[0x1000000] Thread (main_thread) [0x00e6e820]} cellGcmSys: cellGcmSetTile: bad compression mode! (8)
E {PPU[0x1000000] Thread (main_thread) [0x00e6e820]} cellGcmSys: cellGcmSetTile: bad compression mode! (12)
U {PPU[0x1000000] Thread (main_thread) [0x00e6e840]} cellGcmSys TODO: cellGcmSetZcull(index=1, offset=0x29b0000, width=1280, height=768, cullStart=0xf0000, zFormat=0x2, aaFormat=0x5, zCullDir=0x0, zCullFormat=0x1, sFunc=0x201, sRef=0x80, sMask=0xff)
E {rsx::thread} RSX: OpenGL: initialization of glGenBuffers failed.
E {rsx::thread} RSX: OpenGL: initialization of glDeleteBuffers failed.
E {rsx::thread} RSX: OpenGL: initialization of glBindBuffer failed.
E {rsx::thread} RSX: OpenGL: initialization of glIsBuffer failed.
E {rsx::thread} RSX: OpenGL: initialization of glBufferData failed.
E {rsx::thread} RSX: OpenGL: initialization of glBufferSubData failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetBufferSubData failed.
E {rsx::thread} RSX: OpenGL: initialization of glMapBuffer failed.
E {rsx::thread} RSX: OpenGL: initialization of glUnmapBuffer failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetBufferParameteriv failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetBufferPointerv failed.
E {rsx::thread} RSX: OpenGL: initialization of glBlendFuncSeparate failed.
E {rsx::thread} RSX: OpenGL: initialization of glBlendEquationSeparate failed.
E {rsx::thread} RSX: OpenGL: initialization of glCreateShader failed.
E {rsx::thread} RSX: OpenGL: initialization of glDeleteShader failed.
E {rsx::thread} RSX: OpenGL: initialization of glCompileShader failed.
E {rsx::thread} RSX: OpenGL: initialization of glShaderSource failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetShaderiv failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetShaderInfoLog failed.
E {rsx::thread} RSX: OpenGL: initialization of glCreateProgram failed.
E {rsx::thread} RSX: OpenGL: initialization of glDeleteProgram failed.
E {rsx::thread} RSX: OpenGL: initialization of glAttachShader failed.
E {rsx::thread} RSX: OpenGL: initialization of glDetachShader failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetAttribLocation failed.
E {rsx::thread} RSX: OpenGL: initialization of glLinkProgram failed.
E {rsx::thread} RSX: OpenGL: initialization of glValidateProgram failed.
E {rsx::thread} RSX: OpenGL: initialization of glBindFragDataLocation failed.
E {rsx::thread} RSX: OpenGL: initialization of glBindAttribLocation failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetUniformLocation failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetProgramiv failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetProgramInfoLog failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttribPointer failed.
E {rsx::thread} RSX: OpenGL: initialization of glEnableVertexAttribArray failed.
E {rsx::thread} RSX: OpenGL: initialization of glDisableVertexAttribArray failed.
E {rsx::thread} RSX: OpenGL: initialization of glGenVertexArrays failed.
E {rsx::thread} RSX: OpenGL: initialization of glBindVertexArray failed.
E {rsx::thread} RSX: OpenGL: initialization of glDeleteVertexArrays failed.
E {rsx::thread} RSX: OpenGL: initialization of glDepthRangef failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib1f failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib1d failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib1fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib1dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib2f failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib2d failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib2fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib2dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib3f failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib3d failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib3fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib3dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib4f failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib4d failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib4iv failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib4fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib4dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glVertexAttrib4uiv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform1i failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform1f failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform1d failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform1ui failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform1iv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform1fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform1dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform1uiv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform2i failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform2f failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform2d failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform2ui failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform2iv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform2fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform2dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform2uiv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform3i failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform3f failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform3d failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform3ui failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform3iv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform3fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform3dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform3uiv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform4i failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform4f failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform4d failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform4ui failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform4iv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform4fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform4dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniform4uiv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniformMatrix2fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniformMatrix2dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniformMatrix3fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniformMatrix3dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniformMatrix4fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUniformMatrix4dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform1i failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform1f failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform1d failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform1ui failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform1iv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform1fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform1dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform1uiv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform2i failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform2f failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform2d failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform2ui failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform2iv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform2fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform2dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform2uiv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform3i failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform3f failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform3d failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform3ui failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform3iv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform3fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform3dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform3uiv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform4i failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform4f failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform4d failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform4ui failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform4iv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform4fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform4dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniform4uiv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniformMatrix2fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniformMatrix2dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniformMatrix3fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniformMatrix3dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniformMatrix4fv failed.
E {rsx::thread} RSX: OpenGL: initialization of glProgramUniformMatrix4dv failed.
E {rsx::thread} RSX: OpenGL: initialization of glUseProgram failed.
E {rsx::thread} RSX: OpenGL: initialization of glDepthBoundsEXT failed.
E {rsx::thread} RSX: OpenGL: initialization of glStencilOpSeparate failed.
E {rsx::thread} RSX: OpenGL: initialization of glStencilFuncSeparate failed.
E {rsx::thread} RSX: OpenGL: initialization of glStencilMaskSeparate failed.
E {rsx::thread} RSX: OpenGL: initialization of glGenerateMipmap failed.
E {rsx::thread} RSX: OpenGL: initialization of glBindRenderbuffer failed.
E {rsx::thread} RSX: OpenGL: initialization of glDeleteRenderbuffers failed.
E {rsx::thread} RSX: OpenGL: initialization of glGenRenderbuffers failed.
E {rsx::thread} RSX: OpenGL: initialization of glRenderbufferStorage failed.
E {rsx::thread} RSX: OpenGL: initialization of glBindFramebuffer failed.
E {rsx::thread} RSX: OpenGL: initialization of glDeleteFramebuffers failed.
E {rsx::thread} RSX: OpenGL: initialization of glGenFramebuffers failed.
E {rsx::thread} RSX: OpenGL: initialization of glFramebufferTexture1D failed.
E {rsx::thread} RSX: OpenGL: initialization of glFramebufferTexture2D failed.
E {rsx::thread} RSX: OpenGL: initialization of glFramebufferTexture3D failed.
E {rsx::thread} RSX: OpenGL: initialization of glFramebufferRenderbuffer failed.
E {rsx::thread} RSX: OpenGL: initialization of glBlitFramebuffer failed.
E {rsx::thread} RSX: OpenGL: initialization of glDrawBuffers failed.
E {rsx::thread} RSX: OpenGL: initialization of glEnablei failed.
E {rsx::thread} RSX: OpenGL: initialization of glDisablei failed.
E {rsx::thread} RSX: OpenGL: initialization of glPrimitiveRestartIndex failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetInteger64v failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetStringi failed.
E {rsx::thread} RSX: OpenGL: initialization of glCheckFramebufferStatus failed.
E {rsx::thread} RSX: OpenGL: initialization of glMapBufferRange failed.
E {rsx::thread} RSX: OpenGL: initialization of glBindBufferRange failed.
E {rsx::thread} RSX: OpenGL: initialization of glBindBufferBase failed.
E {rsx::thread} RSX: OpenGL: initialization of glMultiDrawArrays failed.
E {rsx::thread} RSX: OpenGL: initialization of glTexBuffer failed.
E {rsx::thread} RSX: OpenGL: initialization of glTextureBufferRangeEXT failed.
E {rsx::thread} RSX: OpenGL: initialization of glCopyImageSubData failed.
E {rsx::thread} RSX: OpenGL: initialization of glBufferStorage failed.
E {rsx::thread} RSX: OpenGL: initialization of glFenceSync failed.
E {rsx::thread} RSX: OpenGL: initialization of glClientWaitSync failed.
E {rsx::thread} RSX: OpenGL: initialization of glDeleteSync failed.
E {rsx::thread} RSX: OpenGL: initialization of glDebugMessageCallback failed.
E {rsx::thread} RSX: OpenGL: initialization of glTexStorage1D failed.
E {rsx::thread} RSX: OpenGL: initialization of glTexStorage2D failed.
E {rsx::thread} RSX: OpenGL: initialization of glTexStorage3D failed.
E {rsx::thread} RSX: OpenGL: initialization of glTexSubImage3D failed.
E {rsx::thread} RSX: OpenGL: initialization of glBlendColor failed.
E {rsx::thread} RSX: OpenGL: initialization of glBlendEquation failed.
E {rsx::thread} RSX: OpenGL: initialization of glCompressedTexImage2D failed.
E {rsx::thread} RSX: OpenGL: initialization of glCompressedTexSubImage1D failed.
E {rsx::thread} RSX: OpenGL: initialization of glCompressedTexSubImage2D failed.
E {rsx::thread} RSX: OpenGL: initialization of glCompressedTexSubImage3D failed.
E {rsx::thread} RSX: OpenGL: initialization of glActiveTexture failed.
E {PPU[0x1000000] Thread (main_thread) [0x00e5495c]} sys_fs: sys_fs_open(“/app_home/content_ps3/gpuhang.bin”): failed to open file (flags=01101, mode=0666)
E {PPU[0x1000000] Thread (main_thread) [0x00e5495c]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
F {PPU[0x1000000] Thread (main_thread) [0x00b3a4c8]} class std::runtime_error thrown: Trap!
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:2190)

**Comment by AniLeo** [comment]
Please use the forums for those kind of questions. 
Also, that's not a full log, when reporting issues in the forums please attach RPCS3.log.

**Comment by DarkSt1ar** [comment]
ok
