### ISSUE TITLE
 Regression : God of War III 

### ISSUE THREAD

**Issue by Kilowog01** [RPCS3/rpcs3#2339]
The game used to show these two images below until build  [1.0.1659,](https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.1659) and I tried to figure out when exactly it stopped working and after some days testing found that this commit (https://github.com/RPCS3/rpcs3/pull/1537) made the game stop showing these scenes to show only a black screen in their place. 
rpcs3-ReleaseLLVM-5911b3c1.zip - WORKS! (v1.0.1659)
![1](https://cloud.githubusercontent.com/assets/16064499/22620312/5b8859b8-eaf0-11e6-8fcc-9bb2112ce366.png)
![2](https://cloud.githubusercontent.com/assets/16064499/22620316/61a28af8-eaf0-11e6-9018-641e06e20033.png)
Log: https://mega.nz/#!vVkBHbqQ!7E2Ui0dYflRGLqUJkLGWnDlffOEnuExM_MOQMFp0mKI

rpcs3-ReleaseLLVM-dc0366a3.zip - FAIL! (v1.0.1660)
![3](https://cloud.githubusercontent.com/assets/16064499/22620319/6c8eeaba-eaf0-11e6-8825-58c03c0e55b6.png)
Log: https://mega.nz/#!yQdHCQRY!5VMfJSdxLluYuC5l8sDNJUHPSFLfAQh-RLHONWLnz8E

It would be nice if you guys could fix this...
EDIT:
Since you created the commit, can you take a look and see if you can fix it, @vlj ?

**Comment by zminhquanz** [comment]
oh , i hope it's boot into the menu and playable

**Comment by aakh1361** [comment]
I Can't Wait for Playable this game :-)

**Comment by raven02** [comment]
@Kilowog01 , i can see this testing using the build year ago .Can you test the latest build here ?

https://ci.appveyor.com/project/rpcs3/rpcs3/branch/master/artifacts

**Comment by Kilowog01** [comment]
@raven02 
https://mega.nz/#!zVkgAIzT!tmRo_YTIAA2ja-VVO8NiBuRbW49TkKZL65oobuW5O9Q

**Comment by jobs-git** [comment]
Hi, I also experience the same thing, v1.0.1659 works, but the latest build as of this week does not work.

**Comment by Zangetsu38** [comment]
For me i have a flashing screen Yellow in OGL

**Comment by Kilowog01** [comment]
@Zangetsu38 Please post your .log, say which build used and the specs of your pc. I think you may have done something wrong. I just tested the newest build in OGL and got only black screen, no flashing yellow screen. It would be nice to watch a video too if possible.

**Comment by Zangetsu38** [comment]
i think a bug, actually hack bleack screen lol

**Comment by jobs-git** [comment]
There was no flashing screen here, but I am impressed by DX12 Performance, I got about ~600 frames per seconds, though I know there is nothing being rendered visible, I tried other emulators before and could not get that much performance for non-visible output.

**Comment by al0xf** [comment]
Does reverting #1537 actually fix it in the current master?

**Comment by Kilowog01** [comment]
@al0xf 
Nezarn made only a partial reversal that didn't work. Someone needs to create a full reverse build, if I knew how to do it myself I would.

**Comment by aakh1361** [comment]
@Kilowog01
I Can back change to old source and make new build
can you try ? 
If relate to #1537 must work whit back change
if don't work so must find problem in older

**Comment by Kilowog01** [comment]
@aakh1361 
Of course, just send the build to me and I'll test it right away. If you prefer, you can send it at Discord too since I'm always there.

**Comment by aakh1361** [comment]
I return changed (#1537) GLFragmentProgram.cpp and RSXThread.cpp to Old source
[Old Fullrpcs3.zip](https://github.com/RPCS3/rpcs3/files/819703/Old.Fullrpcs3.zip)

**Comment by Kilowog01** [comment]
@aakh1361 
Unfortunately nothing appeared on the screen. But this time also doesn't appear a fatal error.
log: https://mega.nz/#!rRNB2KrS!hVOrp3a0RxAyKhBVeG5LGkIQwtDSf4o6bkadFf2Dd7Q
I don't know why github doesn't accept my .zip files

**Comment by aakh1361** [comment]
so maybe don't relate to #1537 change
you look in "https://github.com/RPCS3/rpcs3/network" can find diagram change

**Comment by aakh1361** [comment]
Problem must relate whit there
between builds v1.0.1659 and v1.0.1660 create this change
1- https://github.com/vlj/rpcs3/commit/5911b3c1f10eceda9f4d3749deb35cd13ea979a4

2- https://github.com/vlj/rpcs3/commit/4966d50e52b2484c95ff6d19d41d9b095c69a015

3- https://github.com/vlj/rpcs3/commit/a196ee195790649514b5e81977c80c9c436531c0

4- https://github.com/vlj/rpcs3/commit/d74e031d4e06bcab059103c48b15de6b1877c9b4

5- https://github.com/vlj/rpcs3/commit/05f2aaf2b9c319c4ff0cc9f1477d14afa7c33e05

I returen change 5 to old and don't work so between 1-4

**Comment by JohnGodgames** [comment]
I confirm (last working build) https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.1665/artifacts works

![gow3](https://cloud.githubusercontent.com/assets/11453507/23631210/06f72dd0-02be-11e7-9cf8-53f07e4323bd.PNG)


Seems related to https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.1666/artifacts


https://github.com/RPCS3/rpcs3/pull/1530/files

**Comment by sirdanielk** [comment]
@Kilowog01 
I looked at your log, you still didnt check all required libraries

**Comment by aakh1361** [comment]
@JohnGodgames  
last working build is 1665 or 1659 ?

**Comment by Kilowog01** [comment]
@sirdanielk 
I don't know what you're talking about but it does not matter at all. GowIII just needs sre and spurs to show those screens.

My guess is 3 too @aakh1361

**Comment by raven02** [comment]
Did Vulkan and DX12 work in here? or only GL regressed

**Comment by JohnGodgames** [comment]
@raven02 all backends are regressed

**Comment by aakh1361** [comment]
i look this option 3
and big change and regressed source relate to "GLGSRender::init_buffers"
add something of old source

@Kilowog01 
test 1 and 2 and 3 build
small different between there

[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/823048/rpcs3.zip)
[2.zip](https://github.com/RPCS3/rpcs3/files/823064/2.zip)
[3.zip](https://github.com/RPCS3/rpcs3/files/823069/3.zip)

**Comment by raven02** [comment]
That strange then as that commit is GL related change only.

**Comment by raven02** [comment]
No problem .Thanks @JohnGodgames

**Comment by JohnGodgames** [comment]
@raven02 not requires checked buffers to display

**Comment by raven02** [comment]
I see. thanks.

**Comment by Kilowog01** [comment]
@raven02 
The problem continues in all builds.
Logs:
https://mega.nz/#F!HYtgkIqL!FVGYyeu--WhhaeMN_vbAlQ

**Comment by aakh1361** [comment]
I Find Problem !  :-)

![0](https://cloud.githubusercontent.com/assets/25039098/24113025/a0e9f5a6-0db0-11e7-8f25-d5f0224dd570.jpg)
![1](https://cloud.githubusercontent.com/assets/25039098/24113032/a585c694-0db0-11e7-99bc-06a37db55efa.jpg)

**Comment by MarioSonic2987** [comment]
![](http://i.imgur.com/9iUU4AK.png)
With aakh1361's build, fixes God of War Ascension Demo.

**Comment by kd-11** [comment]
@aakh1361 Any more info on your fix? Is it a proper fix or a hack/workaround?
I'd like to see a diff with what you changed to get output.
Texture cache is actually still WIP though https://github.com/kd-11/rpcs3/tree/hw_accelerated_sw_scale

**Comment by Kilowog01** [comment]
![121212](https://cloud.githubusercontent.com/assets/16064499/24138721/19795b96-0df8-11e7-8f12-5d52fa6c3aec.png)
Problem solved, thank you for the time and effort @aakh1361 :)

**Comment by RainKikyou** [comment]
God of War Ascension
![qq 20170321165514](https://cloud.githubusercontent.com/assets/20301499/24139489/38c69b9e-0e57-11e7-837a-2a325680c124.jpg)

**Comment by aakh1361** [comment]
@kd-11 
Problem Is in Line 156 in File GlRenderTragets.CPP

`if (draw_fbo && !m_rtts_dirty)`
Covert To 
`if (draw_fbo || !m_rtts_dirty)`

i test more 30-40 games and don't see problem
in some games screen is now smooth

except "BIOHAZARD REVELATIONS Unveiled Edition" screen now  is black but have FPS

thank team RPCS3 for geart work

**Comment by kd-11** [comment]
By changing that line to be an OR you essentially keep the engine from swapping framebuffer locations which is going to break alot of games. Some (most AAA) games resample old framebuffers; The condition will only be false once (the first time you run the game). Something else is going on here. Will have to find the real cause as soon as the game goes past intro.

**Comment by kd-11** [comment]
Retry with https://github.com/RPCS3/rpcs3/pull/2582

**Comment by Kilowog01** [comment]
@kd-11 
Nothing here
https://mega.nz/#!fU8ThRyL!a6_DMIQ89huq2P3Mw5IusOLHUV6byaLUkox1hOeEMGY

**Comment by aakh1361** [comment]
noting show for me
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/867477/RPCS3.zip)

**Comment by Zangetsu38** [comment]
no change, allays flashing yellow for me

**Comment by aakh1361** [comment]
@kd-11 
Have You any plan for this in near the future ؟

**Comment by kd-11** [comment]
Its on a todo list

**Comment by shahabs2** [comment]
guys how can i fix my black screen in gow3 ?

**Comment by ROHIT1004** [comment]
God of war 3 work on pc by RPCS3

**Comment by AniLeo** [comment]
No it doesn't. At max it shows some Intros»

**Comment by Zangetsu38** [comment]
no, show nothing, black screen, not works

**Comment by MarioSonic2987** [comment]
https://ci.appveyor.com/project/jarveson/rpcs3/build/0.0.2-101/artifacts - Could you test the game with this build? Select Automatic+Manual LLE and check libgcm_sys.sprx.

**Comment by JackONeill12** [comment]
@MarioSonic2987 With this Build the game shows the first intro screen and the Sony presents screen. Then it's black screen.

**Comment by Zangetsu38** [comment]
show logo yes, but don't need auto + manuel, just auto for me, or lv2

**Comment by AniLeo** [comment]
Still an issue on master?

**Comment by aakh1361** [comment]
@AniLeo 
Yes And We Have Regression 
Now on Master And Build Hack don't Show anything

**Comment by aakh1361** [comment]
Someone knows the latest master build of the game that works on it ?
I did not find anything

**Comment by themitosan** [comment]
@aakh1361 still black screen (current master: 8fc9862)

**Comment by MarioSonic2987** [comment]
Can this issue be closed? God of War III is working now.

**Comment by jobs-git** [comment]
upto which point is it working?

**Comment by eyalzek** [comment]
It's not really playable, but it boots and runs.

**Comment by shivamdhagat** [comment]
I have downloaded gow 3 of 40.1 gb ... Also installed firmware in RCPS3 ...ITS SHOWS TWO ERROR ... 
1.  ELDR: Disc game BCES00510 found at invalid location /dev_hdd0/game/
2.  ELDR: Failed to move disc game BCES00510 to /dev_hdd0/disc/(Access violation)

**Comment by tehranbarco** [comment]
please not run on black screen

**Comment by Naveenpeter** [comment]
God of war 3 is working but with less than 4 frame per sec anyone know how to change it to 60frs

**Comment by marcussacana** [comment]
Sell your soul to the devil, maybe will run with 900fps
