### ISSUE TITLE
GSL: Precondition failure at c:\rpcs3\3rdparty\gsl\include\span.h (Formula One: Championship Edition)

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#2340]
Version https://github.com/RPCS3/rpcs3/commit/a809f33418ec41edccae0bc7a5bb93bbbe452a84.
>·F {rsx::thread} struct gsl::fail_fast thrown: GSL: Precondition failure at c:\rpcs3\3rdparty\gsl\include\span.h: 1432

[Formula_One_Champioship_Edition.txt](https://github.com/RPCS3/rpcs3/files/752609/Formula_One_Champioship_Edition.txt)

**Comment by TotalCaesar659** [comment]
This bug is disappeared, but there is another one:
![1](https://cloud.githubusercontent.com/assets/14265316/26284583/8af8bdbe-3e47-11e7-962f-ac21eb5194c5.png)
[Formula_One_Championship_Edition.txt](https://github.com/RPCS3/rpcs3/files/1017051/Formula_One_Championship_Edition.txt)

**Comment by Zangetsu38** [comment]
error not changed, you have this error because rpcs3 don't found file for this game

**Comment by AniLeo** [comment]
Disable host_root

**Comment by TotalCaesar659** [comment]
There is black screen only.
[Host_root_enabled.txt](https://github.com/RPCS3/rpcs3/files/1017110/Host_root_enabled.txt)

**Comment by AniLeo** [comment]
Please retest

**Comment by TotalCaesar659** [comment]
[Formula_One_Championship_Edition.txt](https://github.com/RPCS3/rpcs3/files/1149914/Formula_One_Championship_Edition.txt)
The bug is gone, it may be closed.
P.S. Keeping hope for further work for this game :)
