### ISSUE TITLE
I Can't Play Macross Macross 30 Ginga o Tsunagu Utagoe

### ISSUE THREAD

**Issue by poteen** [RPCS3/rpcs3#2347]
RPCS3 v0.0.1-6-83e629d Pre-Alpha
F LDR: Already linked function 'cellGcmGetTiledPitchSize' in module 'cellGcmSys'
F LDR: Already linked function '0x05A1377A' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetUserHandler' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetQueueHandler' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetPrepareFlip' in module 'cellGcmSys'
F LDR: Already linked function '0x0E5FE585' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetDisplayInfo' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmInitCursor' in module 'cellGcmSys'
F LDR: Already linked function '_cellGcmInitBody' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetDefaultCommandBufferAndSegmentWordSize' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetCursorPosition' in module 'cellGcmSys'
F LDR: Already linked function '0x1A65F1CF' in module 'cellGcmSys'
F LDR: Already linked function '_cellGcmFunc3' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmDumpGraphicsError' in module 'cellGcmSys'
F LDR: Already linked function '_cellGcmSetFlipCommand' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmAddressToOffset' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetNotifyDataAddress' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetLastSecondVTime' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSortRemapEaIoAddress' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetOffsetTable' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmIoOffsetToAddress' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetTimeStampLocation' in module 'cellGcmSys'
F LDR: Already linked function '0x32D3AA9F' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetDisplayBufferByFlipIndex' in module 'cellGcmSys'
F LDR: Already linked function '_cellGcmFunc15' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmUnreserveIoMapSize' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmBindTile' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetFlipMode' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetSecondVFrequency' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetDebugOutputLevel' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmTerminate' in module 'cellGcmSys'
F LDR: Already linked function '0x55B4350B' in module 'cellGcmSys'
F LDR: Already linked function '0x5868A9F7' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetTimeStamp' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetDefaultCommandWordSize' in module 'cellGcmSys'
F LDR: Already linked function '_cellGcmFunc1' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmMapEaIoAddressWithFlags' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetLastFlipTime' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmMapEaIoAddress' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetTileInfo' in module 'cellGcmSys'
F LDR: Already linked function '_cellGcmFunc12' in module 'cellGcmSys'
F LDR: Already linked function '_cellGcmFunc38' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetCursorDisable' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetVBlankCount' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetFlipStatus' in module 'cellGcmSys'
F LDR: Already linked function '0x7A077DCC' in module 'cellGcmSys'
F LDR: Already linked function '_cellGcmFunc4' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetReportDataAddressLocation' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetUserCommand' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetDefaultSegmentWordSize' in module 'cellGcmSys'
F LDR: Already linked function '_cellGcmFunc2' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetCurrentDisplayBufferId' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetWaitFlip' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetReport' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetReportDataAddress' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetDefaultFifoSize' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmBindZcull' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmMapMainMemory' in module 'cellGcmSys'
F LDR: Already linked function '0xA22F34AE' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetFlipHandler' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetFlipStatus' in module 'cellGcmSys'
F LDR: Already linked function '0xA5151B13' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetDisplayBuffer' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetControlRegister' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetReportDataLocation' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmUnbindZcull' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmReserveIoMapSize' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetVBlankHandler' in module 'cellGcmSys'
F LDR: Already linked function '0xAA076302' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetFlipImmediate' in module 'cellGcmSys'
F LDR: Already linked function '0xB22FF041' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmResetFlipStatus' in module 'cellGcmSys'
F LDR: Already linked function '0xB70B4AD3' in module 'cellGcmSys'
F LDR: Already linked function '0xB96BFD78' in module 'cellGcmSys'
F LDR: Already linked function '_cellGcmFunc13' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetDefaultCommandBuffer' in module 'cellGcmSys'
F LDR: Already linked function '0xBCFECDAE' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetTileInfo' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmUpdateCursor' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetInvalidateTile' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetCursorEnable' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetCurrentField' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmInitDefaultFifoMode' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetGraphicsHandler' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetTile' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetZcull' in module 'cellGcmSys'
F LDR: Already linked function '_cellGcmSetFlipCommandWithWaitLabel' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetZcullInfo' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmUnbindTile' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmUnmapIoAddress' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmMapLocalMemory' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetFlip' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetSecondVHandler' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetWaitFlipUnsafe' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetConfiguration' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSysGetLastVBlankTime' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmUnmapEaIoAddress' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetLabelAddress' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetCursorImageOffset' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmGetMaxIoMapSize' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmInitSystemMode' in module 'cellGcmSys'
F LDR: Already linked function 'cellGcmSetVBlankFrequency' in module 'cellGcmSys'
E LDR: Unknown module 'cellLibprof'
E LDR: Unknown function '0x05893E7C' in module 'cellLibprof' (index 2992)
E LDR: Unknown function '0x6D045C2E' in module 'cellLibprof' (index 2993)
E LDR: Unknown function '0x9FB6228E' in module 'sysPrxForUser' (index 2994)
U {PPU[0x1000000] Thread (main_thread) [0x008ddc70]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x008ddd90]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x1000000] Thread (main_thread) [0x00d97690]} sys_rsx TODO: sys_rsx_device_map(addr=*0xd001f7d0, a2=0xd001f7c8, dev_id=0x8)
U {PPU[0x1000000] Thread (main_thread) [0x00d97878]} sys_rsx TODO: sys_rsx_memory_allocate(mem_handle=*0xd001f780, mem_addr=*0xd001f788, size=0xf900000, flags=0x80000, a5=0x300000, a6=0xf, a7=0x8)
U {PPU[0x1000000] Thread (main_thread) [0x00d97838]} sys_rsx TODO: sys_rsx_context_allocate(context_id=*0xd001f784, lpar_dma_control=*0xd001f790, lpar_driver_info=*0xd001f798, lpar_reports=*0xd001f7a0, mem_ctx=0x0, system_mode=0x820)
F {PPU[0x1000000] Thread (main_thread) [0x00d97894]} struct vm::access_violation thrown: Access violation reading address 0x0

[rpcs3.txt](https://github.com/RPCS3/rpcs3/files/754216/rpcs3.txt)

**Comment by AniLeo** [comment]
Please note its natural for most games not to work. 
Please use the forums for those kind of reports.
