### ISSUE TITLE
F {rsx::thread} class std::range_error thrown: bad conversion

### ISSUE THREAD

**Issue by zerr10** [RPCS3/rpcs3#2348]
Naruto Ultimate Ninja Storm DX12

this bug what is ?

F {rsx::thread} class std::range_error thrown: bad conversion 

game work good in vulcan this bug i get only in DX12 and only in this game

**Comment by Zangetsu38** [comment]
you have duplicate post issue 
https://github.com/RPCS3/rpcs3/issues/2235
