### ISSUE TITLE
PPU: Unregistered functions in several games

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2366]
Tested with a https://github.com/RPCS3/rpcs3/commit/3356a76c9b256d23d699bdbcbab5a1ab846a4c05

### Blazing Angels: Squadrons of WWII
```
F {PPU[0x1000000] Thread (main_thread) [0x006170a4]} class std::runtime_error thrown: Function not registered (index 2994)
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUModule.cpp:158)
```
[LOG](https://mega.nz/#!qUNizZzJ!f0DiHVsVeMJVvuVXJX2Y-3OAeLggKiG1aR9ll55MoKk)

### Fight Night Round 3
```
F {PPU[0x1000000] Thread (main_thread) [0x00aac0a4]} class std::runtime_error thrown: Function not registered (index 2996)
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUModule.cpp:158)
```
[LOG](https://mega.nz/#!DNUWmQ7R!SfL-AJEH_GdEApjhSRGLwnm2pBYg7QS3qi-oB_QqQlw)

### Full Auto 2
```
F {PPU[0x1000000] Thread (main_thread) [0x009af0a4]} class std::runtime_error thrown: Function not registered (index 2998)
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUModule.cpp:158)
```
[LOG](https://mega.nz/#!HVc0yCJa!uHVvRT5wJaVQ2WeUqqMJuyb66WnToKTR3ihfOb9t9Jk)

### Genji: Days of the Blade
```
F {PPU[0x1000000] Thread (main_thread) [0x0072e0a4]} class std::runtime_error thrown: Function not registered (index 2998)
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUModule.cpp:158)
```
[LOG](https://mega.nz/#!7I8QQDwB!TOCxPTteMUk0oFMXixjZLytA6dZpV2eOQ5zhIUQk34c)

### Mobile Suit Gundam: Crossfire	
```
F {PPU[0x1000000] Thread (main_thread) [0x009db0a4]} class std::runtime_error thrown: Function not registered (index 2995)
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUModule.cpp:158)
```
[LOG](https://mega.nz/#!zQsHlSIZ!ci8NCAl48BpNNHoQXMeocu5e0Z9fIJpGLmiUS9QBP54)

### Sonic the Hedgehog
```
F {PPU[0x1000000] Thread (main_thread) [0x017aa0a4]} class std::runtime_error thrown: Function not registered (index 2996)
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUModule.cpp:158)
```
[LOG](https://mega.nz/#!bNFVHRIY!5KnRUZMpOoObpzY4tSCQk1MDEVf-tmAIAFw6EnQDbwc)

**Comment by AniLeo** [comment]
When those happen you need to see in the beginning of the log what's the index 2996 function. It should probably be something in cellSysmodule.

**Comment by Zangetsu38** [comment]
@AniLeo no, all log pointing only one function in cellSysutil ^^, i have already set this in my commit, but probably added this in master, needed after enter other.

**Comment by AniLeo** [comment]
Yeah when I commented there weren't any full logs, function is 0xE1EC7B6A indeed in cellSysutil

**Comment by JohnGodgames** [comment]
0xE1EC7B6A was implemented

**Comment by Mondmorder** [comment]
I can not get GT6 to load, is there something I need to do?

S LDR: Boot successful.
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Recompiler Runtime (ASMJIT) initialized...
U {PPU[0x1000000] Thread (main_thread) [0x0008fe64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x000900bc]} sys_prx TODO: _sys_prx_register_library(library=*0x926a0)
S {PPU[0x1000000] Thread (main_thread) [0x000909ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x000d3d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x000914d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x000914d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x000914d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0009061c]} sys_prx TODO: _sys_prx_register_module()
E {PPU[0x1000000] Thread (main_thread) [0x0001ef4c]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0x1020a, alignment=0x10000000, alloc_addr=*0xd0010920)
F {PPU[0x1000000] Thread (main_thread) [0x0001ef50]} class std::runtime_error thrown: Unregistered PPU function
