### ISSUE TITLE
DX12 - Bad conversion issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2371]
Tested with a https://github.com/RPCS3/rpcs3/commit/aff0484ea22db7e9857d5f218cbfcf2cadf65ffe

There are some affected games:

**Atelier Ayesha The Alchemist of Dusk**
[LOG](https://mega.nz/#!7FEFxaAL!H9ImDFKGODfES9UV2I_zVwxDi0q3vDJJ96ubiaPQ4wU)

**Bodycount**
[LOG](https://mega.nz/#!2QkDkSxQ!6PDCDhmtXTy1YIRW_aKitS1e-oQgp1uViFCauS6-v9s)

**Deadly Premonition DC**
[LOG](https://mega.nz/#!SAdDABwY!a_X9TIpAATE6pHNTcIdIwPu1U7uFGZMtKi2ElGcHM9s)

**Deception IV Blood Ties**
[LOG](https://mega.nz/#!idVEDQLL!8Gz_KDay-yphU7OxJJDsZ2OFtQZJl_0ACRJF2OjKedQ)

**Eternal Sonata**
[LOG](https://mega.nz/#!6Y1xmIyD!Cxnx0VMQbmsL3Ie8FdfCKQQ3jao5AYCodn_FRYIBYVE)

**Earth Defense Force Insect Armageddon**
[LOG](https://mega.nz/#!uIFjUK5K!N7fkz8mcbndKzjzkRvSE-_UX2XHPNLUkF4GJnPlkk7M)

**Eat Lead The Return of Matt Hazard**
[LOG](https://mega.nz/#!rBswBCLC!iwlRhjZ8GKwGLUzEE_AcZ9TwpQ-Qg__rJkqEPJ_uwww)

**Fist of the North Star Ken's Rage**
[LOG](https://mega.nz/#!rBswBCLC!iwlRhjZ8GKwGLUzEE_AcZ9TwpQ-Qg__rJkqEPJ_uwww)

**Hellboy The Science of Evil**
[LOG](https://mega.nz/#!yJ1AkQrL!91Ckzb-OTc8slGFiJXEFV7L3e70zknrBkpYxjnRPMpM)

**Tekken 6**
[LOG](https://mega.nz/#!GA0C3Qgb!r_472dU5LlftwO0uuOpItHdYOg3BEZMQZvKR51CHrQc)

**Comment by raven02** [comment]
Atelier Totori : Alchemist of Arland 2

Log 
https://mega.nz/#!yQVgQL4Y!B5Hr5GOCyumsP8ulZJgaJOL_TDImImU3tvz-ssbXEKo
