### ISSUE TITLE
GL: Ultimate Marvel vs. Capcom 3 - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2372]
Tested on: https://github.com/RPCS3/rpcs3/commit/aff0484ea22db7e9857d5f218cbfcf2cadf65ffe

![ultimate marvel vs capcom 3_1](https://cloud.githubusercontent.com/assets/11453507/22864499/efb7840c-f152-11e6-8f62-02b5696ef730.PNG)

[RenderDoc OGL](https://mega.nz/#!TBMAnABJ!Qukjtd17PyNEW3_dvSQUJECHNA0tBEq1pZ8J6IIAd3U)
[LOG](https://mega.nz/#!2IU3XIha!pwX_ZdZYYTdhkWc0Z9Rtm07zW1BZEPlDGxpGPgPllFE)

**Comment by kd-11** [comment]
Is this still an issue?

**Comment by JohnGodgames** [comment]
https://github.com/RPCS3/rpcs3/commit/7c897d5019e4706ef51205140114249f9fb251ea Minor issues left

![marver 1](https://user-images.githubusercontent.com/11453507/30163547-aabb960c-93d9-11e7-9203-7e02e6de3e79.PNG)
![marver 2](https://user-images.githubusercontent.com/11453507/30163548-aabce9c6-93d9-11e7-9601-ecc5fd72d987.PNG)
