### ISSUE TITLE
GL: Iron Man 2 - Rendering Issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2373]
Tested on: https://github.com/RPCS3/rpcs3/commit/aff0484ea22db7e9857d5f218cbfcf2cadf65ffe

Menu: Missing button pics
Ingame: Only HUD visible

![iron man 2](https://cloud.githubusercontent.com/assets/11453507/22864586/6433bac0-f154-11e6-9d01-fa49a27bdea8.PNG)

![iron man 2 2](https://cloud.githubusercontent.com/assets/11453507/22864605/eb105a3a-f154-11e6-87e7-7832c3833510.PNG)

[RenderDoc menu OGL](https://mega.nz/#!jJ8mUI7I!qkotOJRLA71KoPNYsm-7flNYEHwWw8WThrVi_Pfpl-U)
[RenderDoc ingame OGL](https://mega.nz/#!ndcXgKyI!gocqhn3UWVnPsvz1DkWyR7j3pFhLkRppcQLboKDIWcA)
[LOG](https://mega.nz/#!bZVmFKQA!Gl42ELerFCKFtjzyFnCGpEikT9kSixiXq9NEQBTYaW8)

**Comment by kd-11** [comment]
Still an issue?

**Comment by JohnGodgames** [comment]
https://github.com/RPCS3/rpcs3/commit/7c897d5019e4706ef51205140114249f9fb251ea I can't recheck due to fatal error at intro 

```
F {SPU[0x2000001] Thread (CellSpursKernel1) [0x00f00]} class std::runtime_error thrown: Halt
(in file Emu\Cell\SPUThread.cpp:1796)
```

**Comment by scribam** [comment]
You can use the following GPU settings: WCB + SRM + Force CPU blit emulation.
These settings are also required for Iron Man and Golden Axe: Beast Rider to go ingame and to render something correctly even if the camera does not look like to be at the right place.
I suspect these three games, developed by Sega Studios San Francisco, to use the same game engine so resolving this issue will probably help for #3361, #3362 and vice versa.

**Comment by digitaldude555** [comment]
![screenshot 1644](https://user-images.githubusercontent.com/26138653/51079699-35066480-16d4-11e9-955a-5f3fc38c7909.png)
Doesn't need CPU blit anymore. Just WCB and SRM. 
F {RSX [0x01bf1b4]} RSX: class std::runtime_error thrown: Unreachable
(in file c:\projects\rpcs3\rpcs3\emu\rsx\common\texture_cache.h:1758) crashes with this. So still an issue or can close it?
