### ISSUE TITLE
GL/VK/DX12: How to Train Your Dragon - Rendering Issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2374]
Tested on: https://github.com/RPCS3/rpcs3/commit/aff0484ea22db7e9857d5f218cbfcf2cadf65ffe

![httyd 1](https://cloud.githubusercontent.com/assets/11453507/22864840/f7a48d44-f158-11e6-8077-33d6191b6d53.PNG)

[Video](https://www.youtube.com/watch?v=K0yplVzyerw)

[RenderDoc ingame OGL](https://mega.nz/#!XUNHmS6C!ecZwlX4mKUgsn0utH29AtDNOB24FItMlGqxaKdFDE3M)
[LOG](https://mega.nz/#!vQUCFaAQ!DQlFHkNtMAalSrxtIRGoIR5PWe4BLBIOiECITwUBVSw)

**Comment by Zangetsu38** [comment]
DX12 and wulkan have same issue

**Comment by JohnGodgames** [comment]
Fixed by https://github.com/RPCS3/rpcs3/commit/a886e28f87505f3ff8c738301d813fa60daf2cef
 
https://www.youtube.com/watch?v=ELZF3-rYsYw

**Comment by Zangetsu38** [comment]
Good :D

**Comment by Zangetsu38** [comment]
Very good, but not totaly fixed ^^ 
![capture d ecran 2017-02-20 15 13 20](https://cloud.githubusercontent.com/assets/5261759/23128430/2f8cce5c-f77f-11e6-86d1-2aab3b7af6f1.png)
