### ISSUE TITLE
GL/VK: The Legend of Heroes: Trails of Cold Steel - Rendering Issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2376]
Tested on: https://github.com/RPCS3/rpcs3/commit/aff0484ea22db7e9857d5f218cbfcf2cadf65ffe

GL/VK backends have the same issue and DX12 is throwing a bad conversion https://github.com/RPCS3/rpcs3/issues/2371

![trails](https://cloud.githubusercontent.com/assets/11453507/22865470/b1c8dd0e-f165-11e6-9c7f-d70963846e3b.PNG)

![trails 2](https://cloud.githubusercontent.com/assets/11453507/22865471/b5847250-f165-11e6-94fa-01ae28ecc76b.PNG)

[RenderDoc ingame OGL](https://mega.nz/#!mQ1kwbBb!PUBdZDo7RfaOkltVVjOlU8lCZjq436onN9_JbrZt9cc)
[LOG](https://mega.nz/#!6BtHVQTS!Oz0irRYj7SlZd1m19x7XMi7xw-KKxtMxA2aWtgeSU9U)

**Comment by flash-fire** [comment]
I looked at your log. While, it probably isn't relevant to this issue... RPCS3 not finding the file: "efobj305.inf" happens a TON in that log.   If you count the number of instances efobj305.inf occurs, it's over a thousand. The game really wants that file badly!

**Comment by AniLeo** [comment]
Try making a stub empty file with that name. I did that before on some game with an inf file to make it game go a little further and it worked.

**Comment by JohnGodgames** [comment]
Tested by https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-439/artifacts

You must check write color buffers to get some output.

![trails 1](https://cloud.githubusercontent.com/assets/11453507/23135847/7228d9c0-f79a-11e6-8642-d9b201e80f6e.PNG)
![trails 02](https://cloud.githubusercontent.com/assets/11453507/23135855/7970a03c-f79a-11e6-9542-f89f3985cc91.PNG)

**Comment by victor00123q** [comment]
Weird, I tested this game with the 7dd5d9e7 build and Write Color Buffers and the same LLE Modules on and I couldn't get past the intro , PC specs: 
-8 GB DDR 1600 Mhz Cl9 ram
-AMD HD6970 2gb GDDR5 
-AMD FX 6300 3.5 Ghz
Am I missing something here?

**Comment by victor00123q** [comment]
What LLE modules did you use?

**Comment by JohnGodgames** [comment]
works with master now
