### ISSUE TITLE
PPU: [std::runtime_error thrown: Trap!]

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2377]
***Games list:**
- NPJA90063
- NPEA90055
- NPUA70257

```
F {PPU[0x1000000] Thread (main_thread) [0x00042380]} class std::runtime_error thrown: Trap!
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:2190)

```

**[Log:](https://gist.github.com/SakataGintokiYT/9b7565689c590f9833699fc67a8d949a)**

**Comment by Nekotekina** [comment]
Traps only indicate other problems which may be individual. It doesn't make sense to create a single issue for Trap. Traps will never disappear from the emulator codebase, unlike many other kinds of exceptions.
