### ISSUE TITLE
PPU: sceNpTrophyRegisterContext / GetTrophyInfo

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2378]
***Game list:**
- BLJS10295
- NPEA00271
- NPHB00126

```
**[NPHB00126]**
W {PPU[0x1000000] Thread (main_thread) [0x00114490]} PPU: 'sceNpTrophyRegisterContext' aborted (0.022692s)
E {PPU[0x1000000] Thread (main_thread) [0x003c5800]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x45e5b8, arg=*0x0, options=0x0)
F {PPU[0x1000000] Thread (main_thread) [0x00114490]} struct vm::access_violation thrown: Access violation reading address 0x4e9
```
**[Log: ](https://gist.github.com/SakataGintokiYT/5532cf434820bb903e609b9f9b7d40bc)**

```
**[NPEA00271]**
W {PPU[0x1000000] Thread (main_thread) [0x003c5008]} PPU: 'sceNpTrophyRegisterContext' aborted (0.022210s)
U {PPU[0x1000000] Thread (main_thread) [0x006f2b80]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0xd004fa60, options=0x0)
E {PPU[0x1000000] Thread (main_thread) [0x006f2b40]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x82d700, arg=*0x0, options=0x0)
F {PPU[0x1000000] Thread (main_thread) [0x003c5008]} struct vm::access_violation thrown: Access violation reading address 0x4e9
```
**[Log:](https://gist.github.com/SakataGintokiYT/b87628ddd34de4e672a3025afc8eb5f8)**
```
**[BLJS10295]**
W {PPU[0x1000039] Thread (CHECK_TROPHY) [0x00b8e228]} PPU: 'sceNpTrophyGetTrophyInfo' aborted (9584.762560s)
U {PPU[0x1000000] Thread (main_thread) [0x00b8e148]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0x200ee980, options=0x0)
E {PPU[0x1000038] Thread (LOAD_TROPHY) [0x00b8e108]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0xde2420, arg=*0x0, options=0x0)
F {PPU[0x100003a] Thread (CHECK_TROPHY) [0x00b8e228]} struct vm::access_violation thrown: Access violation writing address 0x8
```
**[Log:](https://gist.github.com/SakataGintokiYT/cd9b508ee319c6304109ced18c84d8c9)**

**Comment by Zangetsu38** [comment]
Splatterhouse also same error
>·W {PPU[0x1000012] Thread (20036100) [0x010ab580]} sceNpTrophy: sceNpTrophyGetTrophyInfo(context=0x1, handle=0x1, trophyId=1, details=*0x0, data=*0xd00ebac0)
·W {PPU[0x1000012] Thread (20036100) [0x010ab580]} PPU: 'sceNpTrophyGetTrophyInfo' aborted (358123.332356s)

**Comment by SakataGintokiYT** [comment]
@georgemoralis 
Can you try to fix this issues ?  sceNpTrophyRegisterContext / GetTrophyInfo

**Comment by georgemoralis** [comment]
can you retest with my latest pull request ? #2382  It might behaves better

**Comment by AniLeo** [comment]
sceNpTrophyRegisterContext: NPUB31243

**Comment by SakataGintokiYT** [comment]
@georgemoralis 
[789dd631] 

```
E {PPU[0x1000000] Thread (main_thread) [0x003c5800]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x45e5b8, arg=*0x0, options=0x0)
F {PPU[0x1000000] Thread (main_thread) [0x00114490]} struct vm::access_violation thrown: Access violation reading address 0x4e9
```
**[Log](https://gist.github.com/SakataGintokiYT/a6d7f5e738b35657101c30b531a95a38)**
__________________________________________________________________________________________________________

```
U {PPU[0x1000000] Thread (main_thread) [0x006f2b80]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0xd004fa60, options=0x0)
E {PPU[0x1000000] Thread (main_thread) [0x006f2b40]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x82d700, arg=*0x0, options=0x0)
F {PPU[0x1000000] Thread (main_thread) [0x003c5008]} struct vm::access_violation thrown: Access violation reading address 0x4e9
```
**[Log:](https://gist.github.com/SakataGintokiYT/f68e42d24f9f09793061f856e87c38b9)**
__________________________________________________________________________________________________________

```
U {PPU[0x1000000] Thread (main_thread) [0x00b8e148]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0x200ee980, options=0x0)
E {PPU[0x1000037] Thread (LOAD_TROPHY) [0x00b8e108]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0xde2420, arg=*0x0, options=0x0)
F {PPU[0x1000039] Thread (CHECK_TROPHY) [0x00b8e228]} struct vm::access_violation thrown: Access violation writing address 0x8
```
**[Log:
](https://gist.github.com/SakataGintokiYT/1bfdd7d85d7d73454889179cb8b67a41)**

**Comment by Zangetsu38** [comment]
SplatterHouse no change
·W {PPU[0x1000011] Thread (20036060) [0x010ab580]} sceNpTrophy: sceNpTrophyGetTrophyInfo(context=0x1, handle=0x1, trophyId=1, details=*0x0, data=*0xd00dbac0)
·W {PPU[0x1000011] Thread (20036060) [0x010ab580]} PPU: 'sceNpTrophyGetTrophyInfo' aborted (12198.686541s)
·F {PPU[0x1000011] Thread (20036060) [0x010ab580]} struct vm::access_violation thrown: Access violation writing address 0x8

**Comment by SakataGintokiYT** [comment]
Dragon Ball Z: Ultimate Tenkaichi

```
U {PPU[0x1000014] Thread (DbPrize thread) [0x006b2edc]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0x2cfc4058, options=0x0)
E {PPU[0x1000014] Thread (DbPrize thread) [0x006b2e9c]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x770160, arg=*0x2cfc3ca0, options=0x1)
E {PPU[0x1000014] Thread (DbPrize thread) [0x006b2fbc]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0x2cfc401c, count=*0xd0177d20)
F {PPU[0x1000000] Thread (main_thread) [0x005fc884]} struct vm::access_violation thrown: Access violation reading address 0x6f5ec538
```

**Comment by georgemoralis** [comment]
it's next on my TODO list

**Comment by JacobAL** [comment]
E {PPU[0x1000011] Thread (FiberFunc) [0x005b7c18]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0x2824190c, count=*0x2824191c)
BLUS30767 Dragon's Crown. LLVM/ASMJIT

**Comment by KurtGuns** [comment]
E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: unknown origin (0)
U {PPU[0x1000000] Thread (main_thread) [0x0001c068]} cellHttp TODO: cellHttpInit
U {PPU[0x1000000] Thread (main_thread) [0x0001c068]} cellSsl TODO: cellSslInit
U {PPU[0x1000000] Thread (main_thread) [0x0001c068]} cellSsl TODO: cellSslCertificateLoader
U {PPU[0x1000000] Thread (main_thread) [0x0001c068]} cellSsl TODO: cellSslCertificateLoader
U {PPU[0x1000000] Thread (main_thread) [0x0001fb1c]} cellHttp TODO: cellHttpsInit
U {PPU[0x1000000] Thread (main_thread) [0x0001c068]} cellHttp TODO: cellHttpInitCookie
U {PPU[0x1000000] Thread (main_thread) [0x011bad80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x011bad80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x011bad80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x011bad80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x011bad80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x011c0e58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x011c0e58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000000] Thread (main_thread) [0x00023fc0]} cellBGDL TODO: cellBGDLSetMode(mode=1)
S {SPU[0x2000000] Thread (CellSpursKernel0)} SPU: SPU Database initialized...
S {SPU[0x2000002] Thread (CellSpursKernel2)} SPU: SPU Recompiler (ASMJIT) created...
U {PPU[0x1000000] Thread (main_thread) [0x0001c068]} sceNp TODO: sceNpManagerGetOnlineId(onlineId=*0xd0040300)
E {PPU[0x100000d] Thread (Store::CheckTrial) [0x011e9ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB02294/USRDIR/MCSM102.EDAT” [1]
E {PPU[0x100000d] Thread (Store::CheckTrial) [0x011e9ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB02294/USRDIR/MCSM102.edat” [1]
E {PPU[0x100000d] Thread (Store::CheckTrial) [0x011e9ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB02294/USRDIR/MCSM103.EDAT” [1]
E {PPU[0x100000d] Thread (Store::CheckTrial) [0x011e9ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB02294/USRDIR/MCSM103.edat” [1]
E {PPU[0x100000d] Thread (Store::CheckTrial) [0x011e9ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB02294/USRDIR/MCSM104.EDAT” [1]
E {PPU[0x100000d] Thread (Store::CheckTrial) [0x011e9ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB02294/USRDIR/MCSM104.edat” [1]
E {PPU[0x100000d] Thread (Store::CheckTrial) [0x011e9ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB02294/USRDIR/MCSM105.EDAT” [1]
E {PPU[0x100000d] Thread (Store::CheckTrial) [0x011e9ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB02294/USRDIR/MCSM105.edat” [1]
U {PPU[0x100000f] Thread (Trophy::Register) [0x0001c044]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0xd013ade0, options=0x0)
E {PPU[0x1000010] Thread (Trophy::Register) [0x0001c044]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x1042378, arg=*0x21cc9870, options=0x0)
E {PPU[0x1000000] Thread (main_thread) [0x011edfc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/” [1]
E {PPU[0x1000000] Thread (main_thread) [0x011edfc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/” [1]
E {PPU[0x1000000] Thread (main_thread) [0x011edfc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/NPEB02294/” [1]
E {PPU[0x1000000] Thread (main_thread) [0x011edfc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/NPEB02294//user/” [1]
E {PPU[0x1000000] Thread (main_thread) [0x011edfc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/” [2]
E {PPU[0x1000000] Thread (main_thread) [0x011edfc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/” [2]
E {PPU[0x1000000] Thread (main_thread) [0x011edfc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/NPEB02294/” [2]
E {PPU[0x1000000] Thread (main_thread) [0x011edfc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/NPEB02294//Temp/” [1]
E {PPU[0x1000010] Thread (Trophy::Register) [0x0001c044]} sceNpTrophy: sceNpTrophyGetGameInfo(context=0x1, handle=0x1, details=*0x21cc98a0, data=*0x21cc9d38)
