### ISSUE TITLE
i probably am just doing this wrong

### ISSUE THREAD

**Issue by thasolidjake** [RPCS3/rpcs3#2389]
i get this no matter what game i try to boot dont know what do
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault writing location 0000000084677000 at 0000000000269230.
Instruction address: 0000000000269230.
Function address: 0000000000269180 (base+0x259180).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

**Comment by raven02** [comment]
Please post it in http://www.emunewz.net/forum/forumdisplay.php?fid=172
