### ISSUE TITLE
Crash (Access Violation) on do_dma_transfer

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#2393]
Aquatopia [NPUA80127] crashes immediately after booting on do_dma_transfer
According to Nekotekina flOw also suffers from the same issue

Call Stack:
>	rpcs3.exe!SPUThread::process_mfc_cmd(unsigned int cmd) Line 405	C++
 	rpcs3.exe!SPUThread::set_ch_value(unsigned int ch, unsigned int value) Line 962	C++
 	rpcs3.exe!spu_interpreter::WRCH(SPUThread & spu, spu_opcode_t op) Line 312	C++
 	rpcs3.exe!SPUThread::cpu_task() Line 229	C++
 	rpcs3.exe!cpu_thread::on_task() Line 53	C++
 	rpcs3.exe!named_thread::start_thread::__l2::<lambda>() Line 2214	C++
 	rpcs3.exe!task_stack::task_type<void <lambda>(void) >::invoke() Line 47	C++
 	rpcs3.exe!thread_ctrl::start::__l2::<lambda>(void * arg) Line 1903	C++

Autos: 
```
MFC_GETB_CMD	MFC_GETB_CMD (65)	<unnamed-enum-MFC_PUT_CMD>
MFC_GETF_CMD	MFC_GETF_CMD (66)	<unnamed-enum-MFC_PUT_CMD>
ch_mfc_args	{ea=4 eal=4 eah=0 ...}	spu_mfc_arg_t
ea	4	unsigned __int64
eal	4	unsigned int
eah	0	unsigned int
lsa	226432	unsigned int
tag	31	unsigned short
size	1792	unsigned short
size_tag	117440543	unsigned int
cmd	32	unsigned int
```

**Comment by scribam** [comment]
Is it still an issue? I tried this game and it stopped with a popup saying "Sixaxis Wireless Controller not detected". I didn't see any issue which seems related to the one described here.

**Comment by scribam** [comment]
@AniLeo Any update on this issue?

**Comment by AniLeo** [comment]
No idea, I can't retest for now

**Comment by scribam** [comment]
New test, no changes. This issue doesn't not appear anymore.

**Comment by AniLeo** [comment]
I'll close since you couldn't reproduce and I can't find it to test
