### ISSUE TITLE
Feature: start in full screen mode

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2396]
It would be good if anyone familiar with wxWidgets can implement it .

**Comment by Megamouse** [comment]
you mean the games or rpcs3?
At the moment with Qt build rpcs3 will start in the same position you left it.
The fullscreen option is WIP in Qt and should be fixed in a few days max.

**Comment by flash-fire** [comment]
Implemented in Qt!

https://github.com/RPCS3/rpcs3/pull/2645

**Comment by AniLeo** [comment]
Solved by #2645
