### ISSUE TITLE
Regression: breaks decryption of eboot.bin

### ISSUE THREAD

**Issue by al0xf** [RPCS3/rpcs3#2397]
@cornytrace https://github.com/RPCS3/rpcs3/pull/2386

For example when booting a new game for the first time. Only a 0 byte boot.bin is created,

**Comment by Zangetsu38** [comment]
Yes, log inbdicate this 
>E LDR: SELF: Failed to decrypt metadata info!
E LDR: SELF: Failed to load SELF file metadata!
F LDR: class std::logic_error thrown: fs::file is null

**Comment by al0xf** [comment]
Raven02, why would you make the title less informative? It _is_ pull request 2386 aka firmware installer that causes the problem.

**Comment by cornytrace** [comment]
I'm looking into it, can you give an example of a game that fails to boot? The two games I tested it on (MGS4, infamous) both worked.

**Comment by Zangetsu38** [comment]
Tested with infamous 2 not works

**Comment by cornytrace** [comment]
@Nekotekina That commit probably fixes the problem, but it's not a very elegant solution. No need to fix my mistakes. If you give me ~2.5 hrs I can probably have a solution that does not seperate SCE and SELFDecrypter.

**Comment by Nekotekina** [comment]
Copypasta is better than failfactoring.

**Comment by Nekotekina** [comment]
I only restored SELFDecrypter, there is no way it could fail this way. It's not "probably", it's definitive.

**Comment by cornytrace** [comment]
I only said probably because I hadn't tested your commit, I was just being truthful...
Anyways, with your permission I will still try to find the original problem with the refactor, and make sure to test it on a lot more games before submitting it.

**Comment by Nekotekina** [comment]
Then take a look at the commit, it's composed from old version + SCEDecryptor. I don't think it's worthwile to refactor it now. I would start from completely rewriting crypto stuff, but I don't want to do it now, and I don't really think someone should touch it.
