### ISSUE TITLE
Nvidia Optimus: iGPU defaulted instead of dGPU

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#2399]
Currently Nvidia Optimus systems run the RPCS3 executable with the iGPU as default. 
However, one can follow certain practices to make Nvidia Optimus default the dedicated GPU for a program instead of the iGPU, without needing any user-input.

## **Static Library Bindings**

> For any application without an existing application profile, there is a set of libraries which, when statically linked to a given application executable, will direct the Optimus driver to render the application using High Performance Graphics. 
As of Release 302, the current list of libraries are:
vcamp110.dll 
vcamp110d.dll
nvapi.dll
nvapi64.dll
opencl.dll
nvcuda.dll
cudart*.*

## **Global Variable NvOptimusEnablement (Driver Release 302+)**
> Starting with the Release 302 drivers, application developers can direct the Optimus driver at runtime to use the High Performance Graphics to render any application–even those applications for which there is no existing application profile. They can do this by exporting a global variable named NvOptimusEnablement. 
The Optimus driver looks for the existence and value of the export. Only the LSB of the DWORD matters at this time. 
A value of 0x00000001 indicates that rendering should be performed using High Performance Graphics. 
A value of 0x00000000 indicates that this method should be ignored. 

**Example usage:**
```
extern "C" { 
 _declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
}
```

_From nVidia Developer Docs at http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf_

**Comment by kd-11** [comment]
Obviously the second method is the only viable one here. Linking against static libraries provided by a 3rd party GPU vendor is not a good idea imo. The dword export is convenient however, and easy to use. Should only be relevant for OGL though, so just tuck it in somewhere in the #ifdef WIN32 block at the top of OpenGL.h with an appropriate comment.

**Comment by AniLeo** [comment]
Thanks for the insight, will test now

**Comment by AniLeo** [comment]
It didn't work when in OpenGL.h but it works if placed on OpenGL.cpp
Also added the equivalent for AMD
