### ISSUE TITLE
libgcm_sys module- Access violation

### ISSUE THREAD

**Issue by ScorchEmber256** [RPCS3/rpcs3#2401]
When booting a particular game, the log reports
log:  
U {PPU[0x1000000] Thread (main_thread) [0x00a3d1f0]} cellGcmSys TODO: cellGcmSetGraphicsHandler
E {PPU[0x1000000] Thread (main_thread) [0x00a3d1d0]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x00a3da50]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH
E {PPU[0x1000000] Thread (main_thread) [0x00a3da50]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH
E {PPU[0x1000000] Thread (main_thread) [0x00a3da50]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH

After dumping the modules and firmware from the game, i ran libgcm_sys and the log came out differently.
U {PPU[0x1000000] Thread (main_thread) [0x00dc1508]} sys_rsx TODO: sys_rsx_device_map(addr=*0xd003ed50, a2=0xd003ed48, dev_id=0x8)
U {PPU[0x1000000] Thread (main_thread) [0x00dc1648]} sys_rsx TODO: sys_rsx_memory_allocate(mem_handle=*0xd003ed00, mem_addr=*0xd003ed08, size=0xf900000, flags=0x80000, a5=0x300000, a6=0xf, a7=0x8)
U {PPU[0x1000000] Thread (main_thread) [0x00dc16b0]} sys_rsx TODO: sys_rsx_context_allocate(context_id=*0xd003ed04, lpar_dma_control=*0xd003ed10, lpar_driver_info=*0xd003ed18, lpar_reports=*0xd003ed20, mem_ctx=0x0, system_mode=0x20)
F {PPU[0x1000000] Thread (main_thread) [0x00dc16c8]} struct vm::access_violation thrown: Access violation reading address 0x0

Is this an error in syntax, or unimplimented fuctionality?

**Comment by B1ackDaemon** [comment]
I guess, that it's related to unimplimented fuctionality. Also, LLEing libgcm_sys module not working yet.

**Comment by AniLeo** [comment]
Did you LLE it? You can't do that as referred above. What if you don't?

**Comment by AniLeo** [comment]
Closing since no relevant information was provided. 
First errors on output are common at this stage, and seems that user attempted LLE libgcm_sys, which can't be done now.
