### ISSUE TITLE
RSX Error Shader

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2402]
Hi after run Pixel monter show Me Error RSX and told to me report problem to Developers

> > 
> E {rsx::thread} RSX: Unimplemented TEX_SRB instruction: UPG
> E {rsx::thread} RSX: Unimplemented SCB instruction: PKG
> E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
> E {rsx::thread} RSX: Src type 3 used, please report this to a developer.
> E {rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
> ERROR: 0:65: '' :  syntax error
> ERROR: 1 compilation errors.  No code generated.
> 
> 
> E {rsx::thread} RSX: 
> F {rsx::thread} class std::runtime_error thrown: Failed to compile fragment shader
> (in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:461)
> 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/782917/RPCS3.zip)

**Comment by aakh1361** [comment]
problem this solved ?

**Comment by blueskype9x** [comment]
How do you solve the problem, I also like you but not overcome.
Can you just fix it?
