### ISSUE TITLE
HLE: cellFont 

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2409]
Games which requires a font module
**Games list:**
- NPEB00598
- NPEB90253
- NPJA00014
- NPUB30903
- NPHB00120
- NPJB90710
- NPJA90172
- NPUB90645
- NPEB01814
- BLES02181
- NPUB30674

**Comment by raven02** [comment]
Another one would be Arkedo 01 . It need the font and freetype modules

**Comment by elad335** [comment]
can this be closed? cellFont is currently lled iirc, problems are likely solved as well.
