### ISSUE TITLE
GLTextureCache.h:587 - Verification failed (e=0xb7)

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2412]
ALIEN CRUSH
NPUF30008
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/791554/RPCS3.zip)
> F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0xb7): 
(in file c:\rpcs3\rpcs3\emu\rsx\gl\GLTextureCache.h:587)

BONK'S ADVENTURE
NPUF30012
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/791561/RPCS3.zip)
> F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0xb7): 
(in file c:\rpcs3\rpcs3\emu\rsx\gl\GLTextureCache.h:587)

LANGRISSER HIKARI NO MATSUEI
NPJJ30048
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/791568/RPCS3.zip)
> F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0xb7): 
(in file c:\rpcs3\rpcs3\emu\rsx\gl\GLTextureCache.h:587)

NEW ADVENTURE ISLAND
NPUF30014
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/791582/RPCS3.zip)
> F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0xb7): 
(in file c:\rpcs3\rpcs3\emu\rsx\gl\GLTextureCache.h:587)

SUPER STAR SOLDIER
NPUF30010
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/791588/RPCS3.zip)
> E {rsx::thread} RSX: Requested dimensions: 32x1 surface: 720x480
F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0xb7): 
(in file c:\rpcs3\rpcs3\emu\rsx\gl\GLTextureCache.h:587)

VICTORY RUN
NPUF30015
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/791591/RPCS3.zip)
> E {rsx::thread} RSX: Requested dimensions: 32x1 surface: 720x480
F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0xb7): 
(in file c:\rpcs3\rpcs3\emu\rsx\gl\GLTextureCache.h:587)

**Comment by kd-11** [comment]
Probably from WIP branch. Work is still ongoing.

**Comment by kd-11** [comment]
Fixed with latest commit on WIP branch.
