### ISSUE TITLE
DX12 ring_buffer_helper.h:64  -  Working buffer not big enough

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2413]
If Need I Can Add Log Files

ALIEN CRUSH
NPUF30008
> F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:64)

BONK'S ADVENTURE
NPUF30012
> F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:64)

SUPER STAR SOLDIER
NPUF30010
> F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:64)

VICTORY RUN
NPUF30015
> F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:64)

**Comment by kd-11** [comment]
Games are using too much VRAM is all.

**Comment by aakh1361** [comment]
I have 16 gigabyte ram

**Comment by kd-11** [comment]
We only allocate about 1G of VRAM. We needn't have to since the ps3 has 256M VRAM anyway. Points to a possible problem with resource management.

**Comment by aakh1361** [comment]
Oh vram !
I have gtx 780 to and have 3 gigabyte vram

**Comment by aakh1361** [comment]
This games is very simple and size each is under 50 megabyte 
Why need to much vram ?
For example : BONK'S ADVENTURE
http://www.emunewz.net/forum/showthread.php?tid=179266

**Comment by kd-11** [comment]
Probably a memory leak.

**Comment by darkskygit** [comment]
BLJM60348
Meruru no Atelier: Arland no Renkinjutsushi 3 (unofficial translation version)
has the same problem at game start ui when i press any button
![](https://cloud.githubusercontent.com/assets/25152247/25545264/909faa2a-2c90-11e7-8b45-de65d81851a0.jpg)
![](https://cloud.githubusercontent.com/assets/25152247/25545294/ae9f2104-2c90-11e7-955b-f622d49509c6.jpg)

**Comment by OverlordCW** [comment]
Also happens with Vulkan in RDR.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/981587/RPCS3.zip)

**Comment by kd-11** [comment]
Its a common issue. I already know why and how it happens, just need to make our allocator a little smarter.

**Comment by JustCallMeAlec** [comment]
This crash also happens on Digimon All Star Rumble on version 0.0.2-4739 at the third area in Story Mode. 
F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:64)
