### ISSUE TITLE
GL/VK Baja: Edge of control - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2415]
Tested by https://github.com/RPCS3/rpcs3/commit/47fdaf69027c1a4138f445a24ada9539a025f08e

```
·W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 2
·W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 3
·W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 4
·W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 5
·W {rsx::thread} RSX: TODO: NV4097_CLEAR_REPORT_VALUE: ZCULL_STATS
·W {PPU[0x1000003] Thread (2XL Render Thread) [0x00a0fc48]} cellGcmSys: cellGcmGetReport(type=2, index=791)
·W {PPU[0x1000003] Thread (2XL Render Thread) [0x00a0fc48]} cellGcmSys: cellGcmGetReport(type=3, index=792)
·W {PPU[0x1000003] Thread (2XL Render Thread) [0x00a0fc48]} cellGcmSys: cellGcmGetReport(type=4, index=793)
·W {PPU[0x1000003] Thread (2XL Render Thread) [0x00a0fc48]} cellGcmSys: cellGcmGetReport(type=5, index=794)
```

**PS3:**
![bajaedgeps31](https://cloud.githubusercontent.com/assets/11453507/23210536/4aa1ead0-f8fe-11e6-8c24-509809795afa.PNG)
![bajaedgeps32](https://cloud.githubusercontent.com/assets/11453507/23210540/4f086ec8-f8fe-11e6-9d60-52739437e0ef.PNG)
![bajaedgeps33](https://cloud.githubusercontent.com/assets/11453507/23210543/51a4e4ae-f8fe-11e6-9abb-c6089758d32f.PNG)

**RPCS3:**
![bajaedge1](https://cloud.githubusercontent.com/assets/11453507/23210345/77d0d4ea-f8fd-11e6-98da-8e5abf70a0e9.PNG)
![bajaedge2](https://cloud.githubusercontent.com/assets/11453507/23210349/7dc374ac-f8fd-11e6-8d46-46aa90b33930.PNG)
![bajaedge3](https://cloud.githubusercontent.com/assets/11453507/23211311/c30d5682-f901-11e6-9dd6-0640ec80cb8e.PNG)

![bajadoc1](https://cloud.githubusercontent.com/assets/11453507/23211746/d2e4309c-f903-11e6-8922-af8cae085849.PNG)
![bajadoc2](https://cloud.githubusercontent.com/assets/11453507/23211748/d64ca052-f903-11e6-8d20-d1eafcce05f5.PNG)

[Video (VULKAN)](https://www.youtube.com/watch?v=iCaLNCILexk)

[RenderDoc OGL Title screen](https://mega.nz/#!vN0QXKLR!1SdJyGjO7Mua5cF4BwT3D2oPbb13rgOYwPxvrnHbU4A)
[RenderDoc OGL Car Selection](https://mega.nz/#!OMVz2ZhA!NEkndKT7nx5tYAF0zXa2EPjKJcCkn94aH5KSk7cUlvI)
[RenderDoc OGL Ingame](https://mega.nz/#!ScNmgRgJ!JBJLq5SHgAcAI330pngijvUCZdAcfC4iKwmLu0sYNCg)
[LOG](https://mega.nz/#!2A8XnLjQ!PRRGeMrjWRTkCbs790PdM1HfJbmtszAW7QEotHOijR4)

**Comment by kd-11** [comment]
NV4097 reports are unimplemented:
```
·W {PPU[0x1000003] Thread (2XL Render Thread) [0x00a0fc48]} cellGcmSys: cellGcmGetReport(type=2, index=791)
·W {PPU[0x1000003] Thread (2XL Render Thread) [0x00a0fc48]} cellGcmSys: cellGcmGetReport(type=3, index=792)
·W {PPU[0x1000003] Thread (2XL Render Thread) [0x00a0fc48]} cellGcmSys: cellGcmGetReport(type=4, index=793)
·W {PPU[0x1000003] Thread (2XL Render Thread) [0x00a0fc48]} cellGcmSys: cellGcmGetReport(type=5, index=794)
·W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 2
·W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 3
·W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 4
·W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 5
·W {rsx::thread} RSX: TODO: NV4097_CLEAR_REPORT_VALUE: ZCULL_STATS
```

**Comment by kd-11** [comment]
You may retest the blue/green screen games with current master. Should have been fixed

**Comment by JohnGodgames** [comment]
Tested with https://github.com/RPCS3/rpcs3/commit/1f45f05f8d376bf0c273f3ad6b7e70bbd20cb968

**write color buffers enabled**
![baja write color 1](https://cloud.githubusercontent.com/assets/11453507/23478474/cbce70b0-fec1-11e6-9dbc-733b016ce635.PNG)
![baja write color 2](https://cloud.githubusercontent.com/assets/11453507/23478480/cf07121e-fec1-11e6-930f-873771443bda.PNG)

**write color buffers disabled**
![baja no write color 3](https://cloud.githubusercontent.com/assets/11453507/23478496/d709d94c-fec1-11e6-8f30-d4d5f4ef1fd9.PNG)
![baja no write color 4](https://cloud.githubusercontent.com/assets/11453507/23478501/d9ed4464-fec1-11e6-97fa-12e9df39062f.PNG)


**Game also tells:**
```
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=4096 src_pitch=128
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=4096 src_pitch=64
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=4096 src_pitch=32
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=4096 src_pitch=16
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=4096 src_pitch=8
```

**Comment by kd-11** [comment]
ouch! that scaling ratio explains the unbearable ingame pixelation.
With more research, this should be fixed

**Comment by MarioSonic2987** [comment]
@JohnGodgames Has it been improved in latest master?

**Comment by JohnGodgames** [comment]
Retested with https://github.com/RPCS3/rpcs3/commit/da3f3fd1fb1682d2b4f7c30600b6174942b71813

- **still needs a libaudio to get ingame**
- **With write color enable gets** 
```
F {rsx::thread} class std::runtime_error thrown: unsupported pixel size 16
(in file Emu\RSX\rsx_utils.cpp:256)
```

**GL**
![baja ogl](https://user-images.githubusercontent.com/11453507/29933935-af79e6d6-8e79-11e7-9ebc-8f8e41eadf69.PNG)
![baja ogl 2](https://user-images.githubusercontent.com/11453507/29933934-af7656b0-8e79-11e7-9f6d-eab49426bd2e.PNG)


**GL LLVM**
![baja ogl llvm 1](https://user-images.githubusercontent.com/11453507/29933943-b461899c-8e79-11e7-8dab-4d22951ad228.PNG)
![baja ogl llvm 2](https://user-images.githubusercontent.com/11453507/29933942-b45e830a-8e79-11e7-9d14-7582c1d2f6c2.PNG)


**VK**
![baja vk 1](https://user-images.githubusercontent.com/11453507/29933950-b995fdd0-8e79-11e7-8725-2c45935cb322.PNG)
![baja vk 2](https://user-images.githubusercontent.com/11453507/29933949-b993964e-8e79-11e7-95ce-bb30598d2ac9.PNG)

**Comment by scribam** [comment]
@JohnGodgames Any progress with the latest build?

**Comment by Xcedf** [comment]
Render now is much more fixed, game itself is slow due to PPU LLVM crash issue and 

F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\users\zero\desktop\kd11\rpcs3\emu\rsx\rsx_cache.h:47)
it could be fixed by hack or turning CPU Blit On, also requres WCB to fix blackness
![31](https://user-images.githubusercontent.com/7060586/39659773-e15cb9e0-5038-11e8-9953-f666689ac386.jpg)

**Comment by digitaldude555** [comment]
Vulkan works now. ![Screenshot (482)](https://user-images.githubusercontent.com/26138653/63448088-e8db8980-c445-11e9-9939-ece801a392f7.png)

OpenGL also works.
![Screenshot (488)](https://user-images.githubusercontent.com/26138653/63448773-550abd00-c447-11e9-8d5b-abf3a87b5d22.png)
