### ISSUE TITLE
Verification failed in GLHelpers.h (AMD, Linux, Mesa)

### ISSUE THREAD

**Issue by Areiser** [RPCS3/rpcs3#2419]
St13runtime_error thrown: Verification failed: 
(in file rpcs3/Emu/RSX/GL/GLHelpers.h:641)

Workaround: Start rpcs3 with 
MESA_GL_VERSION_OVERRIDE=4.3 MESA_GLSL_VERSION_OVERRIDE=430
(4.5 also works). This still only leads to a black screen as described in another issue.

System information:
AMD R9 270
Intel i5 4460
Mesa 17.0
Arch Linux

Log: [RPCS3_log.txt](https://github.com/RPCS3/rpcs3/files/797144/RPCS3_log.txt)

Any clues on what causes this/how to fix this?

**Comment by al0xf** [comment]
What is the output of `glxinfo | grep 'version'`?

**Comment by Areiser** [comment]
$ glxinfo | grep 'version'
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.0.0
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.0 Mesa 17.0.0
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.0.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

**Comment by kd-11** [comment]
Problems with mesa are two-fold:
1. KHR_debug is only enabled for windows at the moment
2. It seems that some critical functions are failing; in this case glMapBufferRange

The first issue is largely unnoticed since most devs work on windows.
The second issue can be worked around by using Legacy OpenGL buffers from the graphics options.

The black screen is most likely going to be caused by an openGL error that we do not notice due to issue no 1 above. The first step would therefore be to enable debug support on linux so we can get more information on what is happening in the driver.

**Comment by Areiser** [comment]
Thanks for the explanation. You are correct in that Legacy Buffers fix the problem as well.

From what I understand this means that the correct OpenGL extension needs to be loaded on linux to even provide the error output?
So the MESA_DEBUG option won't help you at all, right?
 
Otherwise if you need testing I can provide logs for this.

**Comment by kd-11** [comment]
Actually, running the emu with MESA_DEBUG=1 will provide the required information about the crash and/or black screen. You can use that for now.

**Comment by Areiser** [comment]
OK. I'll test and post the logs in a week when I have access to my desktop pc again

**Comment by Areiser** [comment]
I retested this on latest commit (48b0583):

Mesa output from the debug option:
Mesa: User error: GL_INVALID_ENUM in glGetIntegerv(pname=GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT)
Mesa: User error: GL_INVALID_ENUM in glBindTexture(target)
Mesa: 15 similar GL_INVALID_ENUM errors
Mesa: User error: GL_INVALID_ENUM in glBindBufferARB(target GL_TEXTURE_BUFFER_BINDING)
Mesa: User error: GL_INVALID_ENUM in glBufferStorage(target)

Log: 
[RPCS3log.txt](https://github.com/RPCS3/rpcs3/files/817990/RPCS3log.txt)

**Comment by kd-11** [comment]
Looks like missing EXT/ARB_Texture_Buffer as well as ARB_buffer_storage and probably EXT_texture_buffer_range. Most of these are in core now, so they should not be throwing errors.
Attach full glxinfo so I can see supported extensions. I might be able to work around some of the issues if enough extensions are supported.

**Comment by kd-11** [comment]
Apply https://github.com/kd-11/rpcs3/commit/4e7d22f3a98e18dac5ff890949197b76bb02b407 and retest. Fixes black screen on radeonsi for me

**Comment by kd-11** [comment]
Also, force MESA_GL_VERSION_OVERRIDE=4.3 and MESA_GLSL_VERSION_OVERRIDE=430 to bypass the other issues

**Comment by Areiser** [comment]
Retested with your commit:
![rpcs3_mesa](https://cloud.githubusercontent.com/assets/14922864/23577216/b4dd2d8e-00b9-11e7-8f18-c35226db6d7e.png)

Awesome stuff :)
Without the overrides, I still hit the same mesa errors.
Glxinfo: 
[glxinfo.txt](https://github.com/RPCS3/rpcs3/files/818484/glxinfo.txt)

**Comment by kd-11** [comment]
There's no way around the overrides, those features are needed and mesa refuses to expose the functionality unless you override. I'll have to write proper capability-based code paths since mesa does not seem to implement EXT versions of extensions. Not much work to be honest; will wrap it up when work lightens up.

**Comment by Areiser** [comment]
Ok, thanks so much for your help! I really appreciate it.
Yeah, no need to rush. Just do it when you find the time and I'll retest it then.

**Comment by kd-11** [comment]
Newer mesa branch https://github.com/kd-11/rpcs3/tree/mesagl
Needs minor updates to get travis to compile properly, but should work for now. Includes the freezing fixes.
Note that you still need the overrides so that mesa starts in GL4 mode.

Known issues:
- Some games fail to link shaders due to input/output mismatch; I'll have to polish that up before submission.

**Comment by MonokelPinguin** [comment]
@kd-11 
I also can't compile your branch. I think GetTextureImage should be GetTexImage and TextureBufferRange should be TexBufferRange.

**Comment by kd-11** [comment]
No, those are different functions with different parameters. One is truly direct state access while the shorter versions use the binding state, which is undesirable in some cases.
You should update libglew-dev to get these new function definitions.
BTW I do test these builds myself on an actual linux machine, so I know its working fine.

**Comment by MonokelPinguin** [comment]
Yeah, you're right, sorry about that. Had to upgrade to at least glew 1.11 and I was still on 1.10.
Also thanks for your work, that fixes most of the graphical issues I had.

**Comment by MonokelPinguin** [comment]
You need to compile with wxWidgets >= 3.1 if you don't want to force the mesa version, as only wxWidgets >= 3.1 allow for modern opengl core context creation. (see: [https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.1.0/docs/changes.txt](https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.1.0/docs/changes.txt) and [rpcs3/Gui/GLGSFrame.cpp](https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Gui/GLGSFrame.cpp#L18))

**Comment by kd-11** [comment]
Most issues here have been fixed. You can use envvar overrides or compile with wx >= 3.1 to access core profile. Or wait for the Qt port.
