### ISSUE TITLE
spu_interpreter::STOPD-Unimplemented instruction

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2420]
@Nekotekina 

**Game list:**
- NPUA70080
- NPEA90101
- NPHA80188

```
F {SPU[0x2000005] Thread (LittleCellSpursKernel0)} class std::runtime_error thrown: Unimplemented instruction
(in file C:\rpcs3\rpcs3\Emu\Cell\SPUInterpreter.cpp:356)
```

**[Log:](https://gist.github.com/SakataGintokiYT/b9db46b4f95378552670e614f968f5b2)**

**Comment by Xcedf** [comment]
Far Cry 2 had it but it was fixed for it by https://github.com/RPCS3/rpcs3/pull/3026

**Comment by scribam** [comment]
I can't reproduce the issue with NPUA70080 and NPHA80188 so far.
@SakataGintokiYT Can you check on your side if this is still an issue?

**Comment by Zangetsu38** [comment]
normal, it is fixed for few game

**Comment by elad335** [comment]
try #3722 PR build and see if it fixed.

**Comment by scribam** [comment]
NPEA90101 is ingame: https://forums.rpcs3.net/thread-198266.html
So this issue can probably be closed now
