### ISSUE TITLE
cellAudio and cellGcmSys

### ISSUE THREAD

**Issue by ewlkkf** [RPCS3/rpcs3#2421]
`·W {rsx::thread} RSX: TODO: NV4097_CLEAR_REPORT_VALUE: ZCULL_STATS
·W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 2
·W {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 3
·W {PPU[0x1000000] Thread (main_thread) [0x00b47ae0]} cellGcmSys: cellGcmGetReportDataLocation(index=0, location=1)
·W {PPU[0x1000000] Thread (main_thread) [0x00b47ae0]} cellGcmSys: cellGcmGetReportDataAddressLocation(index=0, location=1)
·W {PPU[0x1000000] Thread (main_thread) [0x00b47ae0]} cellGcmSys: cellGcmGetReportDataLocation(index=1, location=1)
·W {PPU[0x1000000] Thread (main_thread) [0x00b47ae0]} cellGcmSys: cellGcmGetReportDataAddressLocation(index=1, location=1)
·W {PPU[0x100000e] Thread (CRI Server Manager) [0x00b46d20]} cellAudio: cellAudioGetPortConfig(portNum=0, portConfig=*0xd0096810)
·W {PPU[0x100000e] Thread (CRI Server Manager) [0x00b46d20]} cellAudio: cellAudioGetPortConfig(portNum=0, portConfig=*0xd0096810)
·W {PPU[0x100000e] Thread (CRI Server Manager) [0x00b46d20]} cellAudio: cellAudioGetPortConfig(portNum=0, portConfig=*0xd0096810)
`

![image](https://cloud.githubusercontent.com/assets/4454062/23289666/a20bc78c-fa8e-11e6-984e-275fdd086c12.png)

repeat this warnings log endlessly.
cellAudio and cellGcmSys required, but when you do, unknown error happened. (and just crash.)

**Comment by ewlkkf** [comment]
![image](https://cloud.githubusercontent.com/assets/4454062/23289703/f75f4b14-fa8e-11e6-9cc8-6ba296d700f5.png)
![image](https://cloud.githubusercontent.com/assets/4454062/23290345/6a8393e4-fa93-11e6-9b61-21530f8ef70f.png)
yup, same place, same glitch!




![image](https://cloud.githubusercontent.com/assets/4454062/23290380/a97fcb80-fa93-11e6-902f-b8bef1796279.png)
![image](https://cloud.githubusercontent.com/assets/4454062/23290419/e4dc045a-fa93-11e6-97b5-2caf60ca0342.png)
everything is goin crazy 0_o

**Comment by raven02** [comment]
This is known issue and we already discussed here https://github.com/RPCS3/rpcs3/issues/1867

**Comment by al0xf** [comment]
I think he is talking about the going out of bounds bug in the screenshots. But that is likely a game bug from running at 1 fps (and therefore lagging _hard_).
