### ISSUE TITLE
Vulkan : Saint Seiya Brave Soldiers - wrong logo color rendering

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2429]
GL and DX12 render correct the logo color.

![687474703a2f2f692e696d6775722e636f6d2f48704f736849622e706e67](https://cloud.githubusercontent.com/assets/3000282/23338287/5a60face-fc41-11e6-99e8-5826d76568e7.png)

**Comment by Zangetsu38** [comment]
Several game bave this old issus

**Comment by raven02** [comment]
Will check out the texture format shortly. Looks like it is a remap issue.

**Comment by raven02** [comment]
Issue fixed
