### ISSUE TITLE
Per game configs do not work on disc games copied into the dev_hdd0\game folder

### ISSUE THREAD

**Issue by clienthax** [RPCS3/rpcs3#2433]
Title.

**Comment by Zangetsu38** [comment]
i have a found why, BD game used diferent folder, so rpcs3 create config in folder same name BD game, and after xwant load setting in config in folder different but config not here, caused by this

**Comment by AniLeo** [comment]
@clienthax Retest

**Comment by Zangetsu38** [comment]
yes fixed
