### ISSUE TITLE
Device not mounted error?

### ISSUE THREAD

**Issue by snuffysam** [RPCS3/rpcs3#2437]
Hi,

Had this error when I was trying to (never succeeded) start a game up:

```
E {PPU[0x1000009] Thread (CRI FS File Access 2) [0x01da8c74]} sys_fs: sys_fs_open(“/dev_bdvd/PS3_GAME/USRDIR/data/system/nuccMaterial_ps3.nsh”) failed: device not mounted
E {PPU[0x1000009] Thread (CRI FS File Access 2) [0x01da8c74]} 'cellFsOpen' failed with 0x8001003a : CELL_ENOTMOUNTED
```

Is this the sort of error that can be fixed by activating/deactivating libs, or is it something more egregious?

My log file is (hopefully) attached. Change from .png to .log.
![rpcs3](https://cloud.githubusercontent.com/assets/5252368/23345553/0e79f03a-fc5e-11e6-8584-7734cf893866.png)

**Comment by clienthax** [comment]
What game..?

**Comment by Renusek** [comment]
@clienthax read the log BLJS10318-[ジョジョの奇妙な冒険　アイズオブヘブン] which is the japanese version of JoJo's Bizarre Adventure - Eyes of Heaven

**Comment by snuffysam** [comment]
@Renusek correct - apologies for not specifying in my post.
I've seen it on lists of games that work with RPCS3, so I don't think the game is the problem- unless I have corrupted files or something.

**Comment by al0xf** [comment]
Ask for technical support on Discord or the forums, not on github which is for development related topics. This is not a bug in any case.

**Comment by raven02** [comment]
Issue closed .Please discuss in discord or forums as suggested
