### ISSUE TITLE
Can't play J-Stars Victory+ ( No Audio, etc. )

### ISSUE THREAD

**Issue by zBombard** [RPCS3/rpcs3#2438]
I get this error ( Sorry for the english ) + When game says "Click a button" I click some of these and nothing happens

> E LDR: Unknown module 'sysPs2Disc'
E LDR: Unknown module 'sysBdMediaId'
U {PPU[0x1000000] Thread (main_thread) [0x009790e4]} HLE TODO: Unimplemented syscall syscall_462 -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00988a00]} sys_prx TODO: sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x00988c58]} sys_prx TODO: sys_prx_register_library(library=*0x98b230)
U {PPU[0x1000000] Thread (main_thread) [0x00990d0c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
F {PPU[0x1000000] Thread (main_thread) [0x0098a06c]} struct vm::access_violation thrown: Access violation reading address 0x0
E LDR: Unknown module 'cellLibprof'
E LDR: Unknown function '0x05893E7C' in module 'cellLibprof' (index 3003)
E LDR: Unknown function '0x6D045C2E' in module 'cellLibprof' (index 3004)
E LDR: Unknown function '0x9FB6228E' in module 'sysPrxForUser' (index 3005)
U {PPU[0x1000000] Thread (main_thread) [0x0073432c]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x0073440c]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x1000000] Thread (main_thread) [0x00733a2c]} cellGcmSys TODO: cellGcmSetVBlankFrequency
U {PPU[0x1000000] Thread (main_thread) [0x005781bc]} HLE TODO: Unimplemented syscall sys_spu_thread_group_log -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00a53c94]} sys_spu TODO: Unsupported SPU Thread Group type (0x20)
U {PPU[0x1000000] Thread (main_thread) [0x00a53d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00a53d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00a53d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00a53d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00a53d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00a53d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00a69904]} sys_prx TODO: sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x00a5c514]} HLE TODO: Unimplemented syscall sys_spu_thread_group_set_cooperative_victims -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x009a8d8c]} sys_prx TODO: sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x100000f] Thread (CRI FS File Access 1) [0x00733e0c]} sys_fs: sys_fs_stat(“/dev_hdd0/game/BLES02136-INSTALL/USRDIR/data/PS3/partition_op_patch_ps3.cpk”) failed: not found
E {PPU[0x100000f] Thread (CRI FS File Access 1) [0x00733e0c]} 'cellFsStat' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x100000f] Thread (CRI FS File Access 1) [0x00733e0c]} sys_fs: sys_fs_stat(“/dev_hdd0/game/BLES02136-INSTALL/USRDIR/data/PS3/partition_op_game_ps3.cpk”) failed: not found
E {PPU[0x100000f] Thread (CRI FS File Access 1) [0x00733e0c]} 'cellFsStat' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x00a3a560]} sys_memory: sys_memory_get_page_attribute(addr=0x290bc080, attr=*0xd00feb40)
E {PPU[0x1000000] Thread (main_thread) [0x009fc874]} sys_memory: sys_memory_get_page_attribute(addr=0xd00ff7f0, attr=*0xd00ff750)
E {PPU[0x1000010] Thread (CRI FS File Access 2) [0x00733e0c]} sys_fs: sys_fs_stat(“/dev_bdvd/PS3_GAME/USRDIR/data/PS3/limited/JP/BGM_LTD_JP.awb”) failed: not found
E {PPU[0x1000010] Thread (CRI FS File Access 2) [0x00733e0c]} 'cellFsStat' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x009fcdc4]} sys_memory: sys_memory_get_page_attribute(addr=0xd00ff950, attr=*0xd00ff890)
E {PPU[0x1000000] Thread (main_thread) [0x009fce3c]} sys_memory: sys_memory_get_page_attribute(addr=0xd00ff950, attr=*0xd00ff890)
E {PPU[0x1000000] Thread (main_thread) [0x009fce60]} sys_memory: sys_memory_get_page_attribute(addr=0xd00ff888, attr=*0xd00ff890)
E {PPU[0x1000000] Thread (main_thread) [0x009f96e8]} sys_memory: sys_memory_get_page_attribute(addr=0xd00ff888, attr=*0xd00ff7b0)
E {PPU[0x1000000] Thread (main_thread) [0x009f9734]} sys_memory: sys_memory_get_page_attribute(addr=0xd00ff888, attr=*0xd00ff7b0)
E {PPU[0x1000000] Thread (main_thread) [0x009f9edc]} sys_memory: sys_memory_get_page_attribute(addr=0xd00ff950, attr=*0xd00ff7c0)
E {PPU[0x1000000] Thread (main_thread) [0x009f9f24]} sys_memory: sys_memory_get_page_attribute(addr=0xd00ff888, attr=*0xd00ff7c0)
E {PPU[0x1000000] Thread (main_thread) [0x00731f4c]} cellSaveData: cellSaveDataEnableOverlay(enable=1)
S {Audio Thread} XAudio 2.9 initialized
U {PPU[0x1000000] Thread (main_thread) [0x00732d8c]} sceNp2 TODO: sceNpMatching2Init2(poolsize=0x0, priority=0, param=*0xd00ff7ac)
U {PPU[0x1000000] Thread (main_thread) [0x0073276c]} sceNp TODO: sceNpManagerRegisterCallback
U {PPU[0x1000000] Thread (main_thread) [0x0073246c]} sceNp TODO: sceNpBasicRegisterContextSensitiveHandler
E {PPU[0x1000000] Thread (main_thread) [0x009fc874]} sys_memory: sys_memory_get_page_attribute(addr=0xd00ff840, attr=*0xd00ff7a0)
E {PPU[0x1000000] Thread (main_thread) [0x007339ac]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (9)
E {PPU[0x1000000] Thread (main_thread) [0x007339ac]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (9)
E {PPU[0x1000000] Thread (main_thread) [0x007339ac]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (9)
E {PPU[0x1000000] Thread (main_thread) [0x007339ac]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (9)
E {PPU[0x1000000] Thread (main_thread) [0x007339ac]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (9)
U {PPU[0x100000b] Thread (sp_job_cpu_thread_low) [0x0073300c]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0x2ce8ce30, options=0x0)
E {PPU[0x100000f] Thread (CRI FS File Access 1) [0x00733e0c]} sys_fs: sys_fs_stat(“/dev_hdd0/game/BLES02136-INSTALL/USRDIR/data/PS3/partition_op_patch_ps3.cpk”) failed: not found
E {PPU[0x100000f] Thread (CRI FS File Access 1) [0x00733e0c]} 'cellFsStat' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x100000f] Thread (CRI FS File Access 1) [0x00733e0c]} sys_fs: sys_fs_stat(“/dev_hdd0/game/BLES02136-INSTALL/USRDIR/data/PS3/partition_op_game_ps3.cpk”) failed: not found
E {PPU[0x100000f] Thread (CRI FS File Access 1) [0x00733e0c]} 'cellFsStat' failed with 0x80010006 : CELL_ENOENT
U {PPU[0x100000c] Thread (sp_job_cpu_thread_low) [0x0073300c]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0x2ce8ce30, options=0x0)
E {PPU[0x100000b] Thread (sp_job_cpu_thread_low) [0x00732fcc]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x8ae898, arg=*0x2ce8ce00, options=0x1)
E {PPU[0x100000c] Thread (sp_job_cpu_thread_low) [0x007330cc]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0x2ce8ce0c, count=*0xd01dfc20)

**Comment by AniLeo** [comment]
Please use the forums (http://www.emunewz.net/forum/forumdisplay.php?fid=172) for those kind of reports.
Read [How to report issues and ask for support](http://www.emunewz.net/forum/showthread.php?tid=171465)
