### ISSUE TITLE
Regression : LLVM only - invalid unordered_map<K, T> key

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2442]
Regressed at #2425 

Not fixed

- Resonance of Fate
- Fez
- Flower

Fixed

- The Legend of Spyro 
- Outrun Arcade 
- MotorStorm: Pacific Rift
- Bomberman Ultra
- Hail to the Chimp 

`F {PPU[0x1000000] Thread (main_thread)} class std::out_of_range thrown: invalid unordered_map<K, T> key`

**Comment by raven02** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/2443

**Comment by raven02** [comment]
Bomberman Ultra still hit this error in LLVM mode

**Comment by Nekotekina** [comment]
"Offending" line is actually correct. Could be more helpful to find the line which throws (it's a method called `at`)

**Comment by raven02** [comment]
Alright .Will check this out .

**Comment by raven02** [comment]
@ScorchEmber256 . is The Legend of Spyro work in LLVM mode in latest build?

**Comment by SakataGintokiYT** [comment]
@raven02  
The Legend of Spyro: Dawn of the Dragon works on LLVM  in the latest build.

**Comment by Zangetsu38** [comment]
Motorostorm Same
>S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: JIT initialized (bdver1)
F {PPU[0x1000000] Thread (main_thread)} class std::out_of_range thrown: invalid unordered_map<K, T> key

**Comment by Keksus1** [comment]
Resonance of Fate NPEB01348 same with version rpcs3-v0.0.2-2017-03-14-f73adf0d_win64

> F {PPU[0x1000005] Thread () [0x00691050]} class std::out_of_range thrown: invalid unordered_map<K, T> key

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/849084/RPCS3.zip)


`

**Comment by darkredflame** [comment]
Hail to the Chimp [BLUS30153] also has this issue when you try to run the PPU in LLVM recompiler mode.
`F {PPU[0x1000000] Thread (main_thread)} class std::out_of_range thrown: invalid unordered_map<K, T> key`
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/852223/RPCS3.zip)

**Comment by Zangetsu38** [comment]
Fez
F {PPU[0x1000000] Thread (main_thread)} class std::out_of_range thrown: invalid unordered_map<K, T> key

**Comment by raven02** [comment]
@Zangetsu38 , did https://github.com/RPCS3/rpcs3/pull/2576 fix Fez and Motorstorm: PR  ?

**Comment by raven02** [comment]
Bomberman Ultra fixed by #2576

**Comment by Zangetsu38** [comment]
Also fixed MS PR

**Comment by raven02** [comment]
Thanks @Zangetsu38

**Comment by raven02** [comment]
@Keksus1  , please retest #2576 w/ Resonance of Fate
@darkredflame  , please retest #2576 w/ Hail to the Chimp

**Comment by darkredflame** [comment]
@raven02 The error message I mentioned above no longer occurs for Hail to the Chimp.

**Comment by raven02** [comment]
Thanks @darkredflame

**Comment by darkredflame** [comment]
Tested the US version [BLUS30299] of Resonance of Fate, also getting one of these error messages.

`F {PPU[0x1000005] Thread () [0x00303970]} class std::out_of_range thrown: invalid unordered_map<K, T> key`

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/867074/RPCS3.zip)

**Comment by Keksus1** [comment]
@raven02

NPEB01348 also still throws the error:

> F {PPU[0x1000005] Thread () [0x002de1f0]} class std::out_of_range thrown: invalid unordered_map<K, T> key

**Comment by raven02** [comment]
Thanks for testing out .

**Comment by Zangetsu38** [comment]
Fez not fixed
>S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: JIT initialized (znver1)
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Created executable: v1-10200-0660C80FE437D532.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Created executable: v1-11DDC0-DB9EDCB9DEFCA7B6.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Created executable: v1-1D4A0C-ACB9B6D471AA84C5.obj
F {PPU[0x1000000] Thread (main_thread)} class std::out_of_range thrown: invalid unordered_map<K, T> key

F {PPU[0x1000000] Thread (main_thread)} class std::out_of_range thrown: invalid unordered_map<K, T> key

**Comment by Zangetsu38** [comment]
Flower LLVM
F {PPU[0x1000000] Thread (main_thread) [0x006e7cf4]} class std::out_of_range thrown: invalid unordered_map<K, T> key

**Comment by raven02** [comment]
Thanks . List updated in 1st post.

**Comment by MonokelPinguin** [comment]
> "Offending" line is actually correct. Could be more helpful to find the line which throws (it's a method called at)

I'm guessing the exception is thrown in the access to [m_blocks in PPUTranslator.h](https://github.com/RPCS3/rpcs3/blob/f0f8f50e129e13c0c4f0ed42ae43966bd39732cf/rpcs3/Emu/Cell/PPUTranslator.h#L141). At least that's the only unordered_map access with at I found in relation to LLVM.

I can't test it, because I don't have any game that exhibits the same error, but if someone could wrap every access to m_blocks with something like this:

    try {
        // access here, something with m_blocks.at
    }
    catch (std::out_of_range&) {
        LOG_ERROR(PPU, "Range error at line %d", __LINE__);
        throw;
    }

And test one of those games, that should show us in which line the exception occurs.

**Comment by Nekotekina** [comment]
Just set to break on std::out_of_range in Visual Studio Exception Settings. I'll continue investigation.

**Comment by AniLeo** [comment]
This shouldn't be an issue anymore, closing now since I know at least two of the three games listed don't hit that problem with the Recompiler update.
