### ISSUE TITLE
OGL/VK: Clash of the Titans Render Crash

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2445]
Tested by https://github.com/RPCS3/rpcs3/commit/bd85f23ed94a1b252e531dae8c3a4d6f30f5e6bf

![clash 1](https://cloud.githubusercontent.com/assets/11453507/23415705/5d61f868-fde0-11e6-96c7-9c446ac8fb6f.PNG)
![clash 2](https://cloud.githubusercontent.com/assets/11453507/23415720/676e9a3c-fde0-11e6-8601-e23a74f0f711.PNG)
![clash 3](https://cloud.githubusercontent.com/assets/11453507/23415736/71facb42-fde0-11e6-985e-cfe99a95fadd.PNG)

[LOG](https://mega.nz/#!ic9TgYyb!LNiysJTp0Be5u5073eea_-UlFlb326J1tA2jUK0M6Fk)

**Comment by kd-11** [comment]
Any info if Debug Output is enabled?

**Comment by JohnGodgames** [comment]
Updated log with debug output enabled [LOG](https://mega.nz/#!fVU23ToT!9yH1lH8kdxQmwgNXRj7Y79PCDO6gxdJZTM2ZiANHlEY)

**Comment by kd-11** [comment]
No hint why the driver crashed in the log. How does it fare with other backends?

**Comment by JohnGodgames** [comment]
**Vulkan** 
- won't boot while debug output is enabled
- without debug output it crashed same as OGL (text is buggy)

![clash vk 1](https://cloud.githubusercontent.com/assets/11453507/23480075/e3714940-fec6-11e6-88a6-b09cb837b835.PNG)
![clash vk 2](https://cloud.githubusercontent.com/assets/11453507/23480081/e821b754-fec6-11e6-8a80-dfb5fbed8769.PNG)

**DX12** seems to go ingame without any output from intro to ingame [LOG](https://mega.nz/#!DNVyUKgL!9GRK-KeUPJ6JQsHwATrm7JiItKhrxM06u_2dj0og_lY)

**Comment by AniLeo** [comment]
@JohnGodgames Is this still an issue?

**Comment by AniLeo** [comment]
@JohnGodgames Is this still an issue?

**Comment by JohnGodgames** [comment]
https://github.com/RPCS3/rpcs3/commit/7c897d5019e4706ef51205140114249f9fb251ea

**VK crashes while to attempt ingame**
![clash error](https://user-images.githubusercontent.com/11453507/30164931-6f613fc6-93de-11e7-9433-3bf704050ab5.PNG)
[RPCS3.log1.gz](https://github.com/RPCS3/rpcs3/files/1284743/RPCS3.log1.gz)

**GL doesn't show anything and crashes while ingame too**

**Comment by JohnGodgames** [comment]
Ingame [video](https://youtu.be/ZEsz5gZfjVU)
