### ISSUE TITLE
Deadly Premonition: Director's Cut - Rendering Issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2446]
Tested by https://github.com/RPCS3/rpcs3/commit/bd85f23ed94a1b252e531dae8c3a4d6f30f5e6bf

![deadly 1](https://cloud.githubusercontent.com/assets/11453507/23416393/f78ad80e-fde2-11e6-9e6b-fa4f7f6aa376.PNG)

[VIDEO](https://www.youtube.com/watch?v=2CmWtIWzsn8)

[RenderDoc ingame](https://mega.nz/#!zQ81mSjJ!loMNhA0NH1IZVrJpa7lb6akj67HV0Uz_plib5fs5cfM)
[LOG](https://mega.nz/#!CAdUlCJJ!uHATDGgNWatNj12VnZ2YkL3O6lgTS4wCt_SmNwLJPk8)

**Comment by JohnGodgames** [comment]
Tested with https://github.com/RPCS3/rpcs3/commit/1f45f05f8d376bf0c273f3ad6b7e70bbd20cb968

All bugs are still there.

**Wrong alpha on textures example:**
![deadly 2](https://cloud.githubusercontent.com/assets/11453507/23474984/25514236-feb6-11e6-9dc9-1691f74c5478.PNG)
![deadly 3](https://cloud.githubusercontent.com/assets/11453507/23474987/2bcd1702-feb6-11e6-9f7d-4b9242c9ecfe.PNG)

**Comment by JohnGodgames** [comment]
One of rendering issue fixed by https://github.com/RPCS3/rpcs3/pull/2482

master - https://github.com/RPCS3/rpcs3/commit/a168aa2df30a7b42be163dafbfd1247d8f1a9c41

![deadlypre3](https://cloud.githubusercontent.com/assets/11453507/23675550/03428fb0-037a-11e7-91d4-b286e4ef641e.PNG)


rsx: Fix some shader decompiler bugs - https://github.com/RPCS3/rpcs3/pull/2482

![deadlypre1](https://cloud.githubusercontent.com/assets/11453507/23675563/0adcbf34-037a-11e7-95b0-94bd5af59fbe.PNG)

**Comment by kd-11** [comment]
Still an issue?

**Comment by JohnGodgames** [comment]
Yep https://github.com/RPCS3/rpcs3/commit/7c897d5019e4706ef51205140114249f9fb251ea on both of backends.

![deadly ogl](https://user-images.githubusercontent.com/11453507/30164259-2476184e-93dc-11e7-9a79-99e2723b25ce.PNG)
![deadly vk](https://user-images.githubusercontent.com/11453507/30164260-247d07e4-93dc-11e7-8ad5-e8f0c0fdc42c.PNG)

**Comment by Megamouse** [comment]
any update on this?

**Comment by MarioSonic2987** [comment]
@JohnGodgames Any update?

**Comment by digitaldude555** [comment]
![screenshot 583](https://user-images.githubusercontent.com/26138653/47942675-6c4ddd80-defb-11e8-899b-4abe5c63b7d8.png)

Nothing changed.

**Comment by Realmantik** [comment]
Transparency issues is not fixed for this game after #6228. Though it looks like the same problem with trees in GT games.

**Comment by Silanda** [comment]
Probably not worth mentioning, but what the hell:

Assuming that all the transparency issues in the game come from the same source, the chainlink fences in game might be quite interesting to look at. All objects viewed through them appear to be missing their colour; the models are visible and they are shaded, however, they are completely devoid of colour/texture mapping.

**Comment by Silanda** [comment]
I thought it would be more helpful if I posted RSX Captures and screenshots. The area captured is just to the side of the bar called "Galaxy of Terror". I noticed that at certain angles the areas viewed through certain chainlink fences seem to render correctly, but not at other angles. Tested on v0.0.6-8546.

![DP1](https://user-images.githubusercontent.com/4227434/63463958-21835f00-c456-11e9-8230-d7e2f053f99e.png)

Incorrectly rendering. Capture: https://mega.nz/#!8bRlmaQb!KZ24U_-bCoGoGnpcWdub2QlreEqcSDiVEWY_LIGyQjQ

![DP2](https://user-images.githubusercontent.com/4227434/63463993-352ec580-c456-11e9-924d-cb7e42a27edf.png)

Area viewed through fence now rendered correctly when viewed from a reverse angle. Capture: https://mega.nz/#!oOBFyY5b!lsHhP2WX_12uS7n76yL4MomuRgaqvg5rx4qHJG-7zD0

I'm not too familiar with the RSX capturing procedure, so if you'd like different captures I'll try to provide them.

**Comment by Silanda** [comment]
Figured I might as well post an RSX capture of the buggy trees at the start too:

![DP3](https://user-images.githubusercontent.com/4227434/64480683-c7a7c680-d1c3-11e9-99ef-d1ae19ab15fa.png)

[BLES01776_20190907223621_capture.zip](https://github.com/RPCS3/rpcs3/files/3587073/BLES01776_20190907223621_capture.zip)

Despite appearances, the issue's the same as the fence: shaded geometry is visible through the buggy outlines, but or textures (or maybe all colour information) are missing.

By the way, shouldn't the title be changed? It's not OpenGL specific and affects Vulkan too.

**Comment by maximumxp** [comment]
Just fyi, this keeps happening.
![DP](https://user-images.githubusercontent.com/19251031/80639888-08956980-8a39-11ea-8149-d9ab51eef612.png)

**Comment by Silanda** [comment]
The tie clipping might just be a problem with the game itself. IIRC I've had that happen in the PC version too.

**Comment by Silanda** [comment]
OMG! I'm not sure which, but I think a very recent commit has fixed this!

**Comment by kd-11** [comment]
Probably fixed by the alpha fix.

**Comment by Kazamanowski** [comment]
Any updates on this?

**Comment by Darkhost1999** [comment]
> Any updates on this?

Granted that this issue is closed while the mentioned issue is opened.
There won't be any updates on this issue. But there may eventually on the other one.

Did you test your game to see if the issue still exists? If so. Then that's your update for sure. You can always provide if the previous message was like 6 months old a new log, new rsx captures if needed as they may have updated and the old ones may be ineffective in finding a solution.

**Comment by Kazamanowski** [comment]
I've just tested the game, and I don't think an RSX capture can show you this... But the shadows do still flicker when using Vulkan.

**Comment by Kazamanowski** [comment]
> Probably fixed by the alpha fix.

Could you figure out the reason behind the flickering shadows of the static objects? I noticed York's shadow looks okay, but the other static objects... It's quite a mess.
