### ISSUE TITLE
GL: WWE SmackDown vs. Raw 2008 - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2449]
Tested with https://github.com/RPCS3/rpcs3/commit/1f45f05f8d376bf0c273f3ad6b7e70bbd20cb968

for ingame output you need to check **write color buffers**

**Vulkan** doesn't have any ingame output
**DX12** throws a bad conversion
 

![wwe2008 1](https://cloud.githubusercontent.com/assets/11453507/23475702/9f2f0ece-feb8-11e6-974f-6c537941a0f8.PNG)
![wwe2008 2](https://cloud.githubusercontent.com/assets/11453507/23475708/a3c5af4c-feb8-11e6-8f34-40de873d2e0d.PNG)
![wwe2008 3](https://cloud.githubusercontent.com/assets/11453507/23475712/a88c1070-feb8-11e6-8301-8d81d051e8d6.PNG)
![wwe2008 4](https://cloud.githubusercontent.com/assets/11453507/23475718/ac1be972-feb8-11e6-99e7-9ac8f7b42c25.PNG)
![wwe2008 5](https://cloud.githubusercontent.com/assets/11453507/23475727/afaba9a6-feb8-11e6-8eb3-75292b43683b.PNG)

[RenderDoc ingame OGL](https://mega.nz/#!iIkDnZwK!51axX7FZDujFtOiPeh8-Ni7ZlmbW8nAfHauqbi4J_ro)
[LOG](https://mega.nz/#!WMEl0A7Z!1V81SP7WVWLIVJZh5fM9J0Wg4FBlhodnngay5OMssfg)

**Comment by JohnGodgames** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.2-554/artifacts

with write colors buffers enabled
![wwe 08 1](https://cloud.githubusercontent.com/assets/11453507/24124469/25c1a608-0dc4-11e7-85ea-ba5d9574ef58.PNG)


with write colors buffers disabled
![wwe 08 2](https://cloud.githubusercontent.com/assets/11453507/24124475/2b0208ce-0dc4-11e7-8e69-d82a7e82b22e.PNG)

**Comment by scribam** [comment]
@JohnGodgames Any improvements with a recent build?

**Comment by kd-11** [comment]
This was fixed a while back.
