### ISSUE TITLE
DX12 : Limbo - fragment program compilation failure

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2451]
GL and Vulkan both work fine and no shader error .

> E {rsx::thread} RSX: FS build failed:C:\jacky\rpcs3\FragmentProgram.hlsl(159,10-35): error X3037: constructors only defined for numeric base types
> 
> F {rsx::thread} class std::runtime_error thrown: fragment program compilation failure
> (in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)
>

**Comment by kd-11** [comment]
Thanks for the reminder, I forgot about this one.
