### ISSUE TITLE
Unknown STOP code: 0x3fff (Out_MBox is empty)

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2452]
v0.0.1-7-2e2bb69

Sam & Max: The Devil's Playhouse - Episode 1: The Penal Zone

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/814152/RPCS3.zip)

> F {SPU[0x2000001] Thread (CellSpursKernel1)} class std::runtime_error thrown: Unknown STOP code: 0x3fff (Out_MBox is empty)
(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1309)

**Comment by raven02** [comment]
It looks okay with automatic LLE .
![untitled](https://cloud.githubusercontent.com/assets/3000282/23557273/7eda568e-006a-11e7-9c01-9414629b1dad.jpg)

**Comment by aakh1361** [comment]
whit new automatic LLE same result

yes if **press resume** go to menu but before show error

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/817420/RPCS3.zip)


>F {SPU[0x2000004] Thread (CellSpursKernel4)} class std::runtime_error thrown: Unknown STOP code: 0x3fff (Out_MBox is empty)
(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1309)

**Comment by aakh1361** [comment]
whit RPCS3 v0.0.1-10-84de022 don't have error
fix it
