### ISSUE TITLE
 Skate 3 [BLUS30464] RSX Access violation reading address

### ISSUE THREAD

**Issue by supergatto** [RPCS3/rpcs3#2454]
Skate 3 [BLUS30464]
`F {rsx::thread} struct vm::access_violation thrown: Access violation reading address 0xddf413ea`

I don't know if there is already a issues about this. I already search it but i don't found anything.
Log:
[skate3.txt](https://github.com/RPCS3/rpcs3/files/814239/skate3.txt)
Sceen:
![screen](https://cloud.githubusercontent.com/assets/18516991/23513825/b5c530e8-ff65-11e6-9118-13d652d96f7f.png)

**Comment by AniLeo** [comment]
Access violations are a general error, a few games throw them for various reasons.

**Comment by supergatto** [comment]
I tried to search the reason of this error, but without success. Can you read the log? please.

**Comment by raven02** [comment]
I dont know how many time we have to close such issues for this general error  . Closed.
