### ISSUE TITLE
GL: Midnight Club: Los Angeles - unable to find compatible overloaded function "textureGrad()'

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2455]
RPCS3 v0.0.1-4962-1f45f05

Midnight Club: Los Angeles [NPUB30471]

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/814471/RPCS3.zip)

> E {rsx::thread} RSX: Failed to compile shader: 0(261) : error C1115: unable to find compatible overloaded function "textureGrad(sampler2D, vec3, float, float)"
0(262) : error C1115: unable to find compatible overloaded function "textureGrad(sampler2D, vec3, float, float)"

> F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
0(261) : error C1115: unable to find compatible overloaded function "textureGrad(sampler2D, vec3, float, float)"
0(262) : error C1115: unable to find compatible overloaded function "textureGrad(sampler2D, vec3, float, float)"
(0) : error C2003: incompatible options for link
'

**Comment by JohnGodgames** [comment]
Those issues are already here https://github.com/RPCS3/rpcs3/issues/2328

**Comment by raven02** [comment]
Thanks .Closing it.
