### ISSUE TITLE
Unknown STOP code: 0x100 (Out_MBox is empty)

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2456]
BATTLEFIELD Bad Company 2 [NPUB90347]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/814643/RPCS3.zip)

> F {SPU[0x2000005] Thread (Job Manager - Job Thread)} class std::runtime_error thrown: Unknown STOP code: 0x100 (Out_MBox is empty)
(in file Emu\Cell\SPUThread.cpp:1310)

**Comment by raven02** [comment]
Can you test with latest build w/ automatic LLE ? It looks like missing some LLE modules enabled .

**Comment by aakh1361** [comment]
Ok I do it tonight now out of my house

**Comment by raven02** [comment]
I see thanks for testing it out.

**Comment by aakh1361** [comment]
Fix Whit #4147

**Comment by elad335** [comment]
@aakh1361 is it going further ? if the error no longer shows its not enough to say that its fixed

**Comment by aakh1361** [comment]
@elad335 Before go to further Whit press button "Resume" but now no need

**Comment by elad335** [comment]
@aakh1361 you can close the issue then :)
