### ISSUE TITLE
RSX : RSXIO memory not mapped

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2458]
HAZE [NPUB90031]

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/814851/RPCS3.zip)

> F {rsx::thread} class std::runtime_error thrown: rsx::thread::ReadIO32(addr=0xcecececc): RSXIO memory not mapped
(in file Emu\RSX\RSXThread.cpp:1073)

**Comment by AniLeo** [comment]
There's already a general issue for this. #1492
