### ISSUE TITLE
GL/VK Ragnarok Odyssey ACE - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2461]
Tested by https://github.com/RPCS3/rpcs3/commit/48b05838666cc1670ea10d83fe303c3cf1d104d6

**GL/VK** - the same
**DX12** - bad conversion

**PS3**
<img width="640" alt="ragnarok 6" src="https://cloud.githubusercontent.com/assets/11453507/23549658/889506d6-000d-11e7-9cdf-92a3632c7cf7.PNG">
<img width="634" alt="ragnarok 4" src="https://cloud.githubusercontent.com/assets/11453507/23549587/3ba2ccd2-000d-11e7-81b8-6cc4d3911d4f.PNG">
<img width="634" alt="ragnarok 5" src="https://cloud.githubusercontent.com/assets/11453507/23549615/5a3ba47a-000d-11e7-9da1-992fcbae34e7.PNG">

**RPCS3**
<img width="641" alt="ragnarok 1" src="https://cloud.githubusercontent.com/assets/11453507/23549466/bad0e4f4-000c-11e7-80ed-f3433f629998.PNG">
<img width="641" alt="ragnarok 2" src="https://cloud.githubusercontent.com/assets/11453507/23549472/c07d75ac-000c-11e7-98b1-3cb23930c65f.PNG">
<img width="641" alt="ragnarok 3" src="https://cloud.githubusercontent.com/assets/11453507/23549491/cdcca05c-000c-11e7-894e-ad5785b019ff.PNG">

[RenderDoc title screen OGL](https://mega.nz/#!yU03FCSK!Nx6w5gseGEneuoU9e-4PLSRgCVLgxeRhfVF1fBkVXzQ)
[RenderDoc ingame OGL](https://mega.nz/#!7UMDzDpA!P1H2BWSuR40QREDH4NfQty2M0gxWi2VW7gZvsllKEp4)
[LOG](https://mega.nz/#!qFMlxYyI!ihw_CxeVvw-XOCBBHvyhRztIKf_d8pYPFytRyXVW66M)

**Comment by digitaldude555** [comment]
[Isn't this the exact same issue?](https://github.com/RPCS3/rpcs3/issues/2258)

**Comment by JohnGodgames** [comment]
@digitaldude555 true moved to https://github.com/RPCS3/rpcs3/issues/2258
