### ISSUE TITLE
GL: Games displaying on half-screen only

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2464]
Family Feud [NPUB30188]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/817378/RPCS3.zip)
![0](https://cloud.githubusercontent.com/assets/25039098/23560819/f5357e0e-0050-11e7-831b-d9309b851f7b.jpg)
![1](https://cloud.githubusercontent.com/assets/25039098/23560827/f858c258-0050-11e7-9f77-a805546077f2.jpg)
![2](https://cloud.githubusercontent.com/assets/25039098/23560832/fbed8ebc-0050-11e7-90ad-3cc1c53860ba.jpg)

**Comment by digitaldude555** [comment]
A few more games with this issue.

Love Once Mermaids Tears [BLJM60322]
![screenshot 804](https://cloud.githubusercontent.com/assets/26138653/23560912/bd94e428-0044-11e7-8bd7-8470799213b0.png)

Taiheiyou no Arashi: Senkan Yamato, Akatsuki ni Shutsugekisu [BLJS10194]
![screenshot 859](https://cloud.githubusercontent.com/assets/26138653/23561141/a539014c-0045-11e7-9ab5-34a9a9a07896.png)

ELEVATOR ACTION DELUXE [NPJB00159]
![rpcs3-elevator](https://cloud.githubusercontent.com/assets/26138653/23561176/cb92803e-0045-11e7-8f24-db33fa231d0d.png)

**Comment by aakh1361** [comment]
Pixel junk monsters [NPEA00068]
![0](https://cloud.githubusercontent.com/assets/25039098/23566210/2b844cbe-0066-11e7-8cfc-1c66d610032a.jpg)

**Comment by digitaldude555** [comment]
The first four games show a squished image that takes half the window. This shows a cut off screen. probably two different problems here.

**Comment by aakh1361** [comment]
maybe relate

**Comment by raven02** [comment]
This one needs the "write to color buffer" option enabled .

**Comment by digitaldude555** [comment]
Moe Moe Daisensou Gendaiban Plus Plus [BLJS10163] 
![screenshot 1030](https://cloud.githubusercontent.com/assets/26138653/23918445/a24d2e40-08fb-11e7-9cbf-2b4554599a15.png)

Another game with this issue.

**Comment by digitaldude555** [comment]
Rocketman: Axis of Evil [NPUB30018] 
![screenshot 1080](https://cloud.githubusercontent.com/assets/26138653/23966779/53cc6072-09c5-11e7-8b73-744d9b319b3d.png)

Another one.

**Comment by digitaldude555** [comment]
Blokus [NPUB30367] 
![screenshot 1114](https://cloud.githubusercontent.com/assets/26138653/24003333/d72f0360-0a6b-11e7-9fe4-51b78b3deb3a.png)
Another one. This is an issue with write color then? Because all these are black without it on.

**Comment by mashakos** [comment]
Earhworm Jim HD has the same problem https://cdn.discordapp.com/attachments/272083901277667342/304563489832173568/Capture.PNG

**Comment by aakh1361** [comment]
Red Johnson's Chronicles [NPUB30582]

![1](https://cloud.githubusercontent.com/assets/25039098/26145942/acea2d50-3b03-11e7-8ff5-50219e0aa74a.jpg)
![2](https://cloud.githubusercontent.com/assets/25039098/26145954/b58848ca-3b03-11e7-90d7-56398da3dec1.jpg)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1007079/RPCS3.zip)

**Comment by raveskirza** [comment]
In Soul calibur II HD online. This happens in both GL and Vulkan with Write color Bffers on

![image](https://user-images.githubusercontent.com/28158623/27511643-a4f2aebc-58f7-11e7-8cd0-f147f47b504f.png)

**Comment by SakataGintokiYT** [comment]
@kd-11 
Tested with:
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.3-900
**Dragon Ball Z : Battle of Z - demo**
![bez tytulu](https://user-images.githubusercontent.com/13681488/29261860-12e98ca4-80d2-11e7-850f-10d28f5111fc.jpg)

**[Log:](https://gist.github.com/SakataGintokiYT/fe68842c8b548e602c1bf43f9ca8c89c)**

**Comment by SakataGintokiYT** [comment]
@kd-11 
I think we can close this issue.

**Comment by kd-11** [comment]
Closing as fixed by https://github.com/RPCS3/rpcs3/pull/3458

**Comment by aakh1361** [comment]
fix
![image](https://user-images.githubusercontent.com/25039098/30714525-5f64bfd0-9f28-11e7-8633-2929f246bbae.png)

improved performance of 8 -> 21
![image](https://user-images.githubusercontent.com/25039098/30714602-b5db460e-9f28-11e7-9b6b-0894cba92388.png)

**Comment by PoULkY** [comment]
I got this issue
Persona 4 Arena Ultimax [NPUB31563]

![image](https://user-images.githubusercontent.com/15938103/48673596-892e1600-eb75-11e8-910d-11e4fb678f47.png)

**Comment by PoULkY** [comment]
Oh it's okay now
Fixed in version 0.0.5-7562-92be67b4
