### ISSUE TITLE
VK/DX12: Ni no Kuni: Missing graphics and massive flickering

### ISSUE THREAD

**Issue by aeternal606** [RPCS3/rpcs3#2465]
Hi,

as discussed in http://www.emunewz.net/forum/showthread.php?tid=178993, I'm experiencing some massive graphical issues with Ni no Kuni: Wrath of the White Witch. ssshadow told me it might be worth to file a bug report along with a RenderDoc trace, so here we go.

I made a detailed post about the current status of the game and my configuration [here](http://www.emunewz.net/forum/showthread.php?tid=179175). TL;DR: The game shows massive flickering (especially 3D objects) and missing graphics (in fact, most 3D objects are missing; 2D seems to be fine for the most part). It doesn't seem to matter if the camera is moving; the flickering persists even when the game is paused. This affects OpenGL, Vulkan and DX12, although DX12 seems to be marginally better.

My configuration is as follows:

i7 4770k @ 3.5 GHz, Geforce GTX 1070 (driver 378.49), 16 GB DDR3, Win10 64 bit

rpcs3-v0.0.1-2017-03-03-48b05838_win64
PPU decoder: Interpreter (fast); SPU decoder: Recompiler (ASMJIT)
LLE modules extracted from the PS3UPDATE.PUP that came with Ni no Kuni & automatically selected by RPCS3; for the list of modules I used in previous versions with identical results, see http://www.emunewz.net/forum/showthread.php?tid=179175
Video settings: OpenGL @ 1280x720 w/ Vsync, Frame limit set to Auto; Use Legacy OpenGL Buffers checked

Interestingly, the RenderDoc trace looks MUCH cleaner (fewer missing objects, especially the background) than the actual RPCS3 output, so I've attached a screenshot of the same frame to highlight the difference.

The attached zip file contains my log, the RenderDoc trace and the RPCS3 screenshot of the captured frame. Hope that's all the information you need for now. Let me know if anything's missing.

[nnk.zip](https://github.com/RPCS3/rpcs3/files/817643/nnk.zip)

**Comment by SakataGintokiYT** [comment]
@jarveson 
@kd-11  
Graphical corruption is related with this: 

`{rsx::thread} RSX: NV0039_OFFSET_IN: pitch(in=0x0, out=0x0), line(len=0x10, cnt=0x1), fmt(in=0x1, out=0x1), notify=0x0`

**Comment by AniLeo** [comment]
This was fixed on OpenGL, still present on Vulkan and D3D12.

**Comment by Zangetsu38** [comment]
yes, only present in DX12 and Vulkan

**Comment by scribam** [comment]
@aeternal606 Ni no Kuni works better now, check this video: https://www.youtube.com/watch?v=OCP0RSIbQQw

**Comment by AniLeo** [comment]
Solved on Vulkan, closing since we're not tracking individual issues for deprecated D3D12. 

See #2896
