### ISSUE TITLE
LLE: "Load required libraries" doesn't work

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#2466]
I've tested the commit https://github.com/RPCS3/rpcs3/commit/48b05838666cc1670ea10d83fe303c3cf1d104d6 with F1 2010.
1) All settings by default, "Load required libraries" is enabled. RPCS3 gives a lot of errors, the game doesn't load to main menu, infinite loading.
![settings_lle_auto](https://cloud.githubusercontent.com/assets/14265316/23567999/c7aa479e-0069-11e7-8f0b-a564e8892cad.png)
![f1_20101](https://cloud.githubusercontent.com/assets/14265316/23568004/cce699b0-0069-11e7-843a-d1fd5fc4ef19.png)
[F1_2010_lle_auto.txt](https://github.com/RPCS3/rpcs3/files/817838/F1_2010_lle_auto.txt)
1) All settings by default, "Load required libraries" is disabled, I set all the libraries manually. The game goes to main menu and further as it should.
![settings_lle_manual](https://cloud.githubusercontent.com/assets/14265316/23568095/28b701c6-006a-11e7-99b5-b1542a4d329b.png)
![f1_20102](https://cloud.githubusercontent.com/assets/14265316/23568097/2da94c52-006a-11e7-9efa-f3618b94d98c.png)
![f1_20103](https://cloud.githubusercontent.com/assets/14265316/23568111/3805eb7e-006a-11e7-894e-f74e1b68e2bc.png)
![f1_20104](https://cloud.githubusercontent.com/assets/14265316/23568119/3bff3b90-006a-11e7-9f28-b797d8cff35e.png)
[F1_2010_lle_manual.txt](https://github.com/RPCS3/rpcs3/files/817841/F1_2010_lle_manual.txt)
Is it a bug or not? Or I did something wrong?

**Comment by Nekotekina** [comment]
Install sprx libraries from the firmware or rename *.prx to *.sprx because only original filenames are supported atm.

**Comment by rcaridade145** [comment]
> Install sprx libraries from the firmware or rename *.prx to *.sprx because only original filenames are supported atm.

The decryption changes the name from sprx to prx https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Gui/MainFrame.cpp#L394 . If i rename everything to .sprx no lib is found.

**Comment by kd-11** [comment]
For me a simple 'ren *.prx *.sprx' solved the issue. The lle list still shows sprx just fine for me.

**Comment by ScorchEmber256** [comment]
@TotalCaesar659 Some system LLE modules are not supported currently, hence the fatal error. You can try and run the game with fewer modules instead.

**Comment by rcaridade145** [comment]
@kd-11 @Nekotekina  My problem was that on Linux the emulator dir is under /home/user/.config/rpcs3 . I was expecting it to be the directory from where i was executing rpcs3. 
Seems to work ok now.

**Comment by kd-11** [comment]
Its a little unintuitive; I encountered the same issue myself. Maybe it should be on an faq?

**Comment by TotalCaesar659** [comment]
@Nekotekina , thanks for the advice, it works! But it has to be updated with more LLEs.
