### ISSUE TITLE
LLVM: rsx cache error

### ISSUE THREAD

**Issue by ScorchEmber256** [RPCS3/rpcs3#2471]
LLVM regression causes freezing
F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\rpcs3\rpcs3\emu\rsx\rsx_cache.h:112)

Code:
void reset(u32 base, u32 length)
		{
			verify(HERE), locked == false;

**Comment by raven02** [comment]
Sometimes when you restart , this error gone .

**Comment by ScorchEmber256** [comment]
Happens every time after a few seconds
