### ISSUE TITLE
FPS counter does not work on Linux

### ISSUE THREAD

**Issue by rcaridade145** [RPCS3/rpcs3#2472]
Under my branch i had this issue but i believed it had something to do with a bug on how i was introducing Vulkan on Linux. Tried the upstream code and it is the same . It stays on 0.0 fps all the time.
This is on Ubuntu building with clang. On issue #2186 same thing happens on ArchLinux with clang.

**Comment by O1L** [comment]
Try use wxString / wxString::Format here:
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Gui/GSFrame.cpp#L108

**Comment by kd-11** [comment]
Noticed this today as well when enabling mesa driver support

**Comment by rcaridade145** [comment]
Issue seems to be with fmt on Linux 

`

                std::cout << m_frames << "\n";

		std::cout << fps_t.GetElapsedTimeInSec() << "\n";

		std::cout << m_frames / fps_t.GetElapsedTimeInSec() << "\n";

		std::cout << fmt::format("FPS: %.2f", m_frames / fps_t.GetElapsedTimeInSec()) << "\n";`

Outputs 

16

0.527409

30.3364

FPS: 0.00
