### ISSUE TITLE
Support the remaining system languages: Turkish and Brazilian Portuguese

### ISSUE THREAD

**Issue by Kilowog01** [RPCS3/rpcs3#2476]
http://manuals.playstation.net/document/en/ps3/current/settings/systemlanguage.html

I don't know about Turkish, but there are many games with subtitles and dubbing in PT-BR and I don't see my language on the list :(

![112121211212](https://cloud.githubusercontent.com/assets/16064499/23598777/71b4b384-021b-11e7-8f95-375796912619.png)

**Comment by digitaldude555** [comment]
Close now?
