### ISSUE TITLE
Improve Conditions on Linux

### ISSUE THREAD

**Issue by hcorion** [RPCS3/rpcs3#2479]
After the firmware bug was fixed I can now run games on rpcs3, however there are a few nit-picks:
- [x] Vulkan support, see bug here: https://github.com/RPCS3/rpcs3/issues/2255
- [x] D3D Adapter section shouldn't even exist.
- [ ] Add controller support for linux #2678 
- [x] Add .desktop file for ease of access, instead of typing rpcs3 into a terminal.

**Comment by Areiser** [comment]
Just some thoughts:

- Afaik Vulkan is disabled for now because it is not implemented for xorg yet I think (that is on the roadmap though)

- D3D Adapter is greyed out and disabled but I agree it should not be included at all if possible

- About the desktop icon, I guess it would be nice but probably not a priority now (you don't have to type it, it can be opened by just clicking on the executable)

**Comment by rcaridade145** [comment]
@hcorion I'm working on the first two, my branch is a bit outdated however hopefully i'll be able to resume work this weekend.

**Comment by al0xf** [comment]
Perhaps the most important bit of work for Linux is to figure out why most games that work mostly fine on Windows quickly crash/hang on Linux. Atelier, Catherine, Persona 5, and so on.

**Comment by Areiser** [comment]
@rcaridade145 did you get it to build on gcc? I actually pulled your changes yesterday and tinkered a bit but I got stuck at some compilation error in VkVertextBuffers.cpp

And right now the linux version is still pretty buggy, only pretty simple games work for me.

**Comment by rcaridade145** [comment]
@Areiser I usually use clang to compile it. Some gcc versions do have problems (https://github.com/RPCS3/rpcs3/issues/2186#issue-180482637)

**Comment by logos88** [comment]
@hcorion maybe you could add gamepad support in Linux to the list aswell

**Comment by hcorion** [comment]
@logos88 I added a check-mark for controller support and filed a separate issue.

**Comment by ShalokShalom** [comment]
How is it with Wayland? Will that one improve the emulation? Or just make more work with less benefits?

**Comment by AniLeo** [comment]
Solved by #2842 , remaining issue can be tracked on #2678
