### ISSUE TITLE
Kingdom Hearts 2.5 sys_semaphore error

### ISSUE THREAD

**Issue by JackONeill12** [RPCS3/rpcs3#2483]
Kingdom Hearts 2.5 goes into Menu.

When tried to go ingame blackscreen and frozen FPS counter.

Error Logs shows

E {PPU[0x1000000] Thread (main_thread) [0x0007bbcc]} 'sys_semaphore_get_value' failed with 0x80010005 : CELL_ESRCH
E {PPU[0x100000a] Thread (dk::Thread::create) [0x0007bb98]} 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH

and a ton of

E {PPU[0x1000000] Thread (main_thread) [0x004b8a64]} 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH
E {PPU[0x1000000] Thread (main_thread) [0x004b8ba4]} 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH

**Comment by Magicalhawke** [comment]
im having the same problem, if you were able to fix it, then how did you?
