### ISSUE TITLE
GL: Sengouku Basara graphics issue

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2485]
This game is currently only checked OpenGL api+write color buffers to get output.
Vulkan / dx12 can work properly, but get a black screen
The whole series of the same graphics problems
4
![qq 20170308140752](https://cloud.githubusercontent.com/assets/20301499/23692379/1918d5bc-0409-11e7-9d8d-bda0a4e3db54.jpg)
video
https://youtu.be/Y8YjyxvqOGU
4 Sumeragi
![qq 20170308141058](https://cloud.githubusercontent.com/assets/20301499/23692531/4bd9845a-040a-11e7-9236-1a6a8ce4bb37.jpg)
video
https://youtu.be/_1y5Lu_fMOk
Sanada yukimura
![2d917a310a55b3192e501efc4aa98226cefc1764](https://cloud.githubusercontent.com/assets/20301499/23692582/8f03daf0-040a-11e7-9cc6-6fd9bd821ea4.jpg)
https://youtu.be/6Z5mcwCnk40
How can i capture graphics?

**Comment by kd-11** [comment]
Still an issue?

**Comment by Asinin3** [comment]
I think this can be closed, saw some footage of this game running on RPCS3 on YouTube: https://www.youtube.com/watch?v=fnKtaBvGOX4 and it looked fine. Apart from an issue where the split screen wouldn't render properly.
