### ISSUE TITLE
does anyone know what's wrong ?

### ISSUE THREAD

**Issue by drazera** [RPCS3/rpcs3#2486]
every time i try to boot catherine i get this message F {PPU[0x1000000] Thread (main_thread) [0x00c244d0]} struct vm::access_violation thrown: Access violation writing address 0x762
can someone help me

**Comment by AniLeo** [comment]
Please use the forum for support requests
http://www.emunewz.net/forum/forumdisplay.php?fid=172

**Comment by drazera** [comment]
ok
