### ISSUE TITLE
DX12/Vulkan : Disgaea 3 - missing loading screen special effect 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2487]
GL renders this effect correctly by enable 'Write color buffer' but not yet for DX12 and Vulkan 

![untitled](https://cloud.githubusercontent.com/assets/3000282/23709492/962d8516-0454-11e7-956a-5feff802bd50.jpg)

**Comment by AniLeo** [comment]
Needs retesting

**Comment by digitaldude555** [comment]
![screenshot 1672](https://user-images.githubusercontent.com/26138653/51090136-0a71e580-1780-11e9-87c0-10a1b5323990.png)
Loading effect works on Vulkan, can close the issue.
