### ISSUE TITLE
Kingdom Hearts 2.5 wont start anymore

### ISSUE THREAD

**Issue by JackONeill12** [RPCS3/rpcs3#2494]
PR #2488 broke Kingdom Hearts 2.5. Was going into menu before now the whole emulator freezes.
First build where I observed this is 0.0.1-4103.

RPCS3.log: http://pastebin.com/dnVivFci

**Comment by Inviuz** [comment]
Are you sure? it's not using cellGameDataCheckCreate2 anywhere in the log

**Comment by JackONeill12** [comment]
Okay seems not related to this PR. Sometimes it's starts and sometimes not. Strange. Will close this then.

**Comment by Zangetsu38** [comment]
yes, last master break KH Games

**Comment by Zangetsu38** [comment]
@JackONeill12 I have fixed this after delete data folder for this game and clear ShaderLog folder

**Comment by JackONeill12** [comment]
Sounds great. Thank you
