### ISSUE TITLE
Creating broken saves in Minecraft PS3 Edition

### ISSUE THREAD

**Issue by deadair3210** [RPCS3/rpcs3#2496]
1 Start Game
2 Save Game
3 Notice that the emulog says that the save is considered broken
4 Notice that the save appears as a blank tile, and causes an Access Violation when selected

Running latest build as of yesterday, used the Install Firmware feature to get all files needed
![cdsvzx](https://cloud.githubusercontent.com/assets/1053504/23825205/18ad0b0e-064b-11e7-8434-ffd3eeee88d2.PNG)

**Comment by deadair3210** [comment]
Still happening as of latest version 3/31/2017

**Comment by Inviuz** [comment]
@deadair3210 pull request #2631 should fix access violation, but name might still be blank.

**Comment by deadair3210** [comment]
Will test when I have a chance, won't have access to my computer until Sunday

**Comment by deadair3210** [comment]
Access Violation still occurs, names are still blank, still happens with new saves

**Comment by deadair3210** [comment]
Also can't delete saves once created

**Comment by twdarkeh** [comment]
Names now appear. If save then try to load, seems to soft lock. If you try to delete, it doesn't go away, then gives the mem access violation if you try to load it. If you restart, save is still there, can try to load, softlocks again.

Tested on https://github.com/RPCS3/rpcs3/commit/34709eb3996ea239d53f0162ce311a568ca64a06

**Comment by Dangles91** [comment]
There are a number of issues with the current save/load logic. Large portions of it don't account for the subtleties of the different methods. I've started to put some work into fixing it up. Deleting saves isn't currently implemented either.

After a couple of small changes, the behaviour for Kingdom Hearts HD 1.5 (BLUS31212) on launch has been corrected. The prompt to setup screen size is shown when no previous save data exists.

![image](https://user-images.githubusercontent.com/9249458/28100292-74fbfdba-6704-11e7-8884-08b089cdf4f5.png)

Also, the notice for save data being broken isn't always correct, depending on the save/load method used. For example, when autosaving it's only an indication to the system to go ahead and overwrite the existing data.

I'll add minecraft into my testing and update this issue with any findings.

**Comment by Dangles91** [comment]
`cellSaveDataGetListItem` wasn't implemented correctly and didn't return the path for the list item which caused the game to attempt to load data from a blank path. This also fixes the problem with renaming.

I haven't finished making changes to cellSaveData yet, but I'll include this fix once finalised.

**Comment by Megamouse** [comment]
I don't have any issues on minecraft.

can you please try again?
