### ISSUE TITLE
Tales of Xillia 2 - Fragment Program Compilation error

### ISSUE THREAD

**Issue by deadair3210** [RPCS3/rpcs3#2497]
Game installs, shows some glitch text, then proceeds to the title screen where it proceeds to die

Running rpcs3-v0.0.1-2017-03-10-9ec5caea_win64
![cdds](https://cloud.githubusercontent.com/assets/1053504/23825357/b92a6764-064d-11e7-9adb-6b82f4907283.PNG)

**Comment by raven02** [comment]
Closed. Consolidated into https://github.com/RPCS3/rpcs3/issues/2328
