### ISSUE TITLE
Fatal Error while trying to run Yu-Gi-Oh Millineaum Duels

### ISSUE THREAD

**Issue by deadair3210** [RPCS3/rpcs3#2504]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault writing location 000000006b2be040 at 00000000004cef70.
Instruction address: 00000000004cef70.
Function address: 00000000004cef29 (base+0x4bef29).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

**Comment by AniLeo** [comment]
Please don't send incorrect reports. 
Use the forums for those kind of reports / asking for support.
