### ISSUE TITLE
Grand Theft Auto V - broken graphics ingame

### ISSUE THREAD

**Issue by MattKackles** [RPCS3/rpcs3#2506]
![gta](https://cloud.githubusercontent.com/assets/22846547/23829087/10fb046e-06b5-11e7-87b9-e39e7b6604da.png)

Hardly anything is rendered, and crashes a few seconds later with:
F {rsx::thread} class std::runtime_error thrown: Invalid RSX method 0x1d04 (arg=0x3a0042)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:34)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/836297/RPCS3.zip)

**Comment by twdarkeh** [comment]
Really? I mean... really?

**Comment by clienthax** [comment]
@twdarkeh don't spam the issue tracker

**Comment by Grima04** [comment]
It renders now much more:
![screenshot 450](https://cloud.githubusercontent.com/assets/22496380/24875500/893b463e-1e28-11e7-97ea-d6557900c697.png)
My settings:
-PPU on fast
-SPU on precise
-Auto LLE
-Use legacy OpenGL buffers enabled
-OpenGL API

**Comment by Nmzik** [comment]
Crashes with an error: RSX: Failed to compile vertex shader: 0(76) : error C0000: syntax error, unexpected '.', expecting "::" at token "."
Log uploaded
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/911283/RPCS3.log.zip)

**Comment by MattKackles** [comment]
Still fails with rsx method errors,
Nice progress though!

**Comment by raven02** [comment]
If it is rsx method error , i'll close it then and consolidate into another thread which describe the rsx method error.
