### ISSUE TITLE
Can't run Demon's Souls on Arch Linux

### ISSUE THREAD

**Issue by C0rn3j** [RPCS3/rpcs3#2507]
OS: Arch Linux
GPU: GTX 970 with nvidia 378.13 drivers
Game version: The folder is named BLUS30443, so I guess that? Also it should be the USA version.

I have installed the latest firmware from SONY's website.

Output log when trying to launch the game:
http://pastebin.com/63uh6ZZb

What happens to the game window: It sets itself to display the current state of the screen and then never refreshes again.

**Comment by zaxxxxx** [comment]
I've got the same exact problem, in fact I cannot run any game at all. I'm always getting the unknown function/variable/module errors and then the rpcs3 freezes.

**Comment by al0xf** [comment]
There are some general problems with RPCS3 on Linux, some games run, most hang. It is on the short term roadmap to improve the situation.

**Comment by C0rn3j** [comment]
@al0xf Is there something I can do to help as a tester? Testing a dev branch of some sorts perhaps?

**Comment by hcorion** [comment]
@C0rn3j Try this PR: https://github.com/RPCS3/rpcs3/pull/2632 it fixed the issues for me.

**Comment by C0rn3j** [comment]
@hcorion it boots! Awesome! Thanks for letting me know

**Comment by C0rn3j** [comment]
Actually, after logos it's just black screen. Logs here

https://pastebin.com/iwkvcKbM

with these 4 being the last logs that are different color than green


```
E {PPU[0x100001b] Thread (DsTrophyMan::AsyncUpdateThread) [0x018483e8]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x191a630, arg=*0x201e2ef4, options=0x0)
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x0154d440]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM
U {PPU[0x1000005] Thread (HighGraphics) [0x01845960]} cellSail TODO: cellSailPlayerFinalize(pSelf=*0x22c4bd48)
F {PPU[0x1000005] Thread (HighGraphics) [0x01845960]} MEM: Access violation writing location 0x10dac523
```

**Comment by al0xf** [comment]
Another bug that can be worked around. 
![Use the settings in this picture](https://cloud.githubusercontent.com/assets/11020872/24655656/5ddb3dac-193f-11e7-97f2-038d09dd54c1.png)

**Comment by C0rn3j** [comment]
Awesome, that gets me here.

http://i.imgur.com/OK4e99z.png

**Comment by al0xf** [comment]
Turn on write color buffers in graphics settings.

**Comment by C0rn3j** [comment]
In game! I guess after applying the pull request I only ran issues that were already worked around on Windows and I should use the forums next time?

There's just one weird thing - one time the game's audio is almost perfect with next to no crackling and the next time it's a deafening horror. Seems to be decided at startup.

**Comment by al0xf** [comment]
The failure to automatically load all required modules is a Linux specific bug (can probably be fixed easily). 

Write color buffers and deafening horror are on Windows too, although the old OpenAL backend on Linux is a bit worse than XAudio (it will be replaced in the future).

**Comment by C0rn3j** [comment]
Thanks a lot for explaining this!

I was able to play for about 5 minutes before the game crashed.

```
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x01843b20]} sys_fs: sys_fs_open(“/dev_hdd1/cache//0b/55b1a73ab9ca1f1beafc67c3dace439d”): failed to open file (flags=0, mode=0)
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x01843b20]} 'cellFsOpen' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x01843b20]} sys_fs: sys_fs_open(“/dev_hdd1/cache//20/8fab45a43bd815983448b2e6b4c92c1d”): failed to open file (flags=0, mode=0)
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x01843b20]} 'cellFsOpen' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x01843b20]} sys_fs: sys_fs_open(“/dev_hdd1/cache//03/4dee148eb464df24e3770616dfc33d64”): failed to open file (flags=0, mode=0)
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x01843b20]} 'cellFsOpen' failed with 0x80010006 : CELL_ENOENT
```

**Comment by al0xf** [comment]
That doesn't mean anything, just that files were not cached. Would need a gdb backtrace on the crash.

**Comment by C0rn3j** [comment]
How would I go about providing that? 

I still have RPCS3 open after the crash, is what you want in the ASM tab? 

I can only go down by scrolling, grabbing the slider or using arrow keys/page down/end doesn't work.

**Comment by al0xf** [comment]
If RPCS3 is open it didn't crash. Did the game just hang on a loading screen or such? That can happen on Windows too.

**Comment by C0rn3j** [comment]
Sorry for the misunderstanding.

I was ingame, happily murdering stuff when it just froze, and this was the only "bad" recent output in the log.

So not loading screen, but ingame.

**Comment by zaxxxxx** [comment]
@al0xf 

After changing the sttings the games still doesn't work for me. Ends up being stuck on a black screen

http://storage5.static.itmages.com/i/17/0407/h_1491569141_3767931_3ced9c1700.png

**Comment by al0xf** [comment]
It may be some other issue in configuring the game, files in wrong location etc. It's a support question. Provide the log file in the forums or on Discord instead. 

http://www.emunewz.net/forum/forumdisplay.php?fid=163
https://discord.me/RPCS3

**Comment by kd-11** [comment]
Closing since the reported issue is resolved. Demon's souls does trigger freezing on rpcs3, especially when using LLVM. This is often preceded by the death of the audio mixer.
