### ISSUE TITLE
Dragon's Crown 

### ISSUE THREAD

**Issue by Omidusktf** [RPCS3/rpcs3#2508]
Dragon's Crown is not longer loading. Using DX12 with Nvidia 1070, and I'm not sure what the error means lol
![rpcs3](https://cloud.githubusercontent.com/assets/26356183/23829477/47ac8126-06c0-11e7-8cfd-98112943feec.jpg)

**Comment by Omidusktf** [comment]
Oh also log file. 
[Dragon Crown RPCS3 log.txt](https://github.com/RPCS3/rpcs3/files/836898/Dragon.Crown.RPCS3.log.txt)

**Comment by AniLeo** [comment]
That is not a log file. Log file is RPCS3.log
Use OpenGL for testing and report back. When did it stop working? Test the build it was reported working on to see if it works

**Comment by AniLeo** [comment]
Regression was fixed, it goes ingame again, plus note the issue was not correctly created.
