### ISSUE TITLE
GL: Catherine, loading intro issue

### ISSUE THREAD

**Issue by AnonJump** [RPCS3/rpcs3#2509]
After the "Atlus" logo, a black screen appears next. A black screen remains for an endless time. Background audio still remains.
Log: http://pastebin.com/a0QF0esm

**Comment by kd-11** [comment]
Hi. Please attach the rpcs3.log file from the rpcs3 directory or from the ~/.config/rpcs3 if on linux. Thanks.
The log output in the window usually does not capture all required info.

**Comment by daitoqu** [comment]
After the Atlus logo there must be a pop-up window asking about PSN connection. Game wont go further until you choose Yes or No.

**Comment by AnonJump** [comment]
@kd-11, the rpcs3.log: https://mega.nz/#!9JEWiQ7Z . 
Key: !5u2DjmIRtmA6hb67b8uUhbSToFslnDcWxJmnedcrv-s

> After the Atlus logo there must be a pop-up window asking about PSN connection
I have no this window.

**Comment by AnonJump** [comment]
The problem is solved. I followed this instruction: https://rpcs3.net/quickstart/, the title: "How can I get and install PlayStation 3 firmware files?".
