### ISSUE TITLE
One Piece: Unlimited World Red-sys_memory_allocate' failed

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2510]
@Inviuz 

```
E {PPU[0x1000000] Thread (main_thread) [0x001b65b8]} sys_vm: sys_vm_memory_map(vsize=0x8000000, psize=0x7600000, cid=0xffffffff, flags=0x200, policy=0x1, addr=*0x96ea04)
E {PPU[0x1000000] Thread (main_thread) [0x001b65e8]} 'sys_memory_allocate' failed with 0x80010002 : CELL_EINVAL
F {PPU[0x1000000] Thread (main_thread) [0x006faa54]} MEM: Access violation reading location 0xc

```

**[Log:](https://gist.github.com/SakataGintokiYT/882cbc7134ea4b1d9de9f2ae88d12afd)**

**Comment by Inviuz** [comment]
I'd love to see rpcs3.log file. Something's either missing here, or a lot of weirdness incoming

**Comment by SakataGintokiYT** [comment]
@Inviuz 
rpcs3.log : https://mega.nz/#!FVgRHZrQ!Qzv1zmAxlVmHQnRAoSgHByM7mMjWrNitPGHI59GLG_A

**Comment by Inviuz** [comment]
Flags are not specified in the call. The question is, are we supposed to use some kind of default value.
Seems to be aligned to 0x100000,

**Comment by SakataGintokiYT** [comment]
@Inviuz 
```
// Check allocation size
  	switch (flags)
  	{
	case 0:		
  	case SYS_MEMORY_PAGE_SIZE_1M:
  	{
```
<img src="http://www.fotoszok.pl/upload/582396cd.jpg" alt="Fotoszok.pl" />

**[Log:](https://gist.github.com/SakataGintokiYT/69f1f88dfb899a6e19a9796f60d8611f)**
