### ISSUE TITLE
Feature Request [Game config removal]

### ISSUE THREAD

**Issue by sirdanielk** [RPCS3/rpcs3#2511]
HI, it would be nice to have such feature like removal configuration from menu. Its easy to forget what game we individually configured. Aside, it would be nice to have game configs manager or so, in the future. That we would have listed what games has individual config. Just an idea.

**Comment by comet0** [comment]
If you simply want to remove the stored config for a title then this patch will give you another menu option on right click that removes the stored custom config.

https://gist.github.com/comet0/947639f903c1453f9f7bd84d336d52ab

**Comment by twdarkeh** [comment]
Created a fork for this, with that patch, not sure if I should make a PR with it or not, since it's not my fix.

**Comment by sirdanielk** [comment]
that is nice!
