### ISSUE TITLE
Dragon Ball Z: Burst Limit is broken Black Screen in LLVM

### ISSUE THREAD

**Issue by zerr10** [RPCS3/rpcs3#2513]
i7 6700 Skylake 4x3.4Ghz 8GB RAM dual 2133Mhz RX 460 Sapphire 4GB Windows 10 PRO aniversary (1607)

Dragon Ball Z: Burst Limit is broken Black Screen in LLVM

only sound work.

**Comment by AniLeo** [comment]
Several games don't work with LLVM, displaying a black screen. It is a known issue. Please report on #1870
