### ISSUE TITLE
Compiler warnings with clang 

### ISSUE THREAD

**Issue by rcaridade145** [RPCS3/rpcs3#2514]
> shifting a negative signed value is undefined

- PPUInterpreter.cpp:2690:69:
- BitField.h:39:72

> comparison of unsigned expression >= 0 is always true
- GLRenderTargets.h:315:14
 

>  control may reach end of non-void function
- RSXThread.cpp:140:2

> /home/rui/Programacao/upstream/rpcs3/rpcs3/Emu/Cell/../../../Utilities/BitField.h:102:54: note: 
      in instantiation of member function 'bf_t<se_t<unsigned short, true, 2>,
      2, 14>::data_mask' requested here
  ...this->m_data = static_cast<vtype>((this->m_data & ~data_mask()) | insert...
                                                        ^
/home/rui/Programacao/upstream/rpcs3/rpcs3/Emu/Cell/PPUModule.cpp:883:68: note: 
      in instantiation of member function 'bf_t<se_t<unsigned short, true, 2>,
      2, 14>::operator=' requested here
  ...const u16 value = vm::_ref<ppu_bf_t<be_t<u16>, 0, 14>>(raddr) = static_c...

> case value not in enumerated type 'systemparam_id_name' [-Wswitch]
- It is expecting that all the integers defined on the header file be on systemparam_id_name

This is just a compilation of warnings, in the hope that fixing them may lead to better experience on Linux and/or better emulation

**Comment by scribam** [comment]
The last warning was fixed with #3437. I can't find the others mentioned in this issue in Travis (https://travis-ci.org/RPCS3/rpcs3/jobs/287960941).

**Comment by AniLeo** [comment]
Closing as solved
