### ISSUE TITLE
Metal Gear Solid 3 HD black screen+sound issue

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#2515]
Metal Gear Solid 3 HD NPEB00684
Ico & Shadow of The Collosus HD collection BCES01097
both titles had shader compilation issues
both titles were fixed by https://github.com/RPCS3/rpcs3/pull/2482
now all three games has black screen render
MGS goes in menu according to sound) and Ico and SoTC go ingame
the last time MGS showed something was on revision ffb014ca, 
The screen from old revision
![30](https://cloud.githubusercontent.com/assets/7060586/23831993/568fd4c2-073d-11e7-816c-fccd5872835e.jpg)
the very next commit 63845413 breaks it, it was more than a year ago and it was only DX12 that showed smth, now all three renderers has the issue
here's the logs
MGS
https://mega.nz/#!7d52CYaK!MuS8MftkQXBmKmPd9-x2qi9RBvrjJRliR3ef_RPkM5o
Ico
https://mega.nz/#!CAYm0KxJ!nkQdOeirw6BrwFCC6CESeYfS_TD7VvVkJ_AVc8GB5-Q

**Comment by Xcedf** [comment]
84f9997

**Comment by Xcedf** [comment]
19a1754

**Comment by AniLeo** [comment]
Still an issue?

**Comment by Xcedf** [comment]
Yes, still an issue

**Comment by Xcedf** [comment]
Since https://github.com/RPCS3/rpcs3/pull/3200 merged now, i can close this
