### ISSUE TITLE
GL/VK/DX12 Anarchy Reigns - Rendering Issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2518]
Tested by https://github.com/RPCS3/rpcs3/commit/b70a1edbc7b6067ad3ce038eb7198fa58767576a

Trace from title screen should be enough, because contains ingame graphics...

## PS3:
![anarchy 1](https://cloud.githubusercontent.com/assets/11453507/23835710/65b563fc-076c-11e7-86c6-ecaa66b15472.jpg)

## RPCS3
**GL:**
![anarchy reigns 1](https://cloud.githubusercontent.com/assets/11453507/23835709/65b4ffa2-076c-11e7-9c24-3b605c5a4969.PNG)

[VIDEO (GL)](https://www.youtube.com/watch?v=t93cqtX05ks)

**VK:**
![anarchy reigns 3](https://cloud.githubusercontent.com/assets/11453507/23835792/b3c628c8-076d-11e7-840a-0a5ea021f9ae.PNG)

**DX12:**
![anarchy reigns 4](https://cloud.githubusercontent.com/assets/11453507/23835796/baa39586-076d-11e7-919f-7874f66f3a04.PNG)

[RenderDoc title screen GL](https://mega.nz/#!LVt3FJYB!x-oowpB2nfgFpWIZT4UkHjPKEzz2yZCDAv3yxJn8AW4)
[shaderlog GL](https://mega.nz/#!zcMHwTjR!Iq76eKw0foxzquVPc2XMh-5tYobAe6VHOhqA93JNcF4)
[LOG](https://mega.nz/#!7INGyRIT!OjMj-oxjC-_rAr77ZUJk_AobXHVmiPfxPw-5sW03Gjo)

**Comment by MarioSonic2987** [comment]
Is it still an issue?

**Comment by scribam** [comment]
Yes, it is.
Tested with 930ce4a, OpenGL.

**Comment by scribam** [comment]
Works better but still not perfect (because of depth issues I would say), screenshot from 304a4a1b6104ccb3f5843618b29c5ed924d9c3a1, OpenGL.

![screenshot from 2017-10-14 22-05-31](https://user-images.githubusercontent.com/25406440/31578947-de474b50-b12b-11e7-9827-18a612fc06c0.png)

**Comment by scribam** [comment]
Looks good to me with the build 3fbc960c44403e9dce363941b07bf1aeadbc2937 and OpenGL. The transparency/depth issue is gone.

![screenshot from 2017-12-01 19-40-51](https://user-images.githubusercontent.com/25406440/33497889-c8ea76c8-d6cf-11e7-8cc1-f7a451ccee70.png)

**Comment by JohnGodgames** [comment]
Yeah fixed by latest commits
