### ISSUE TITLE
GL: Bionic Commando - rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2519]
Tested by https://github.com/RPCS3/rpcs3/commit/b70a1edbc7b6067ad3ce038eb7198fa58767576a

This game have issue with datas too.I need to reinstall everytime when want to try, because it says data are corrupted.Game just stopped working while attemp to play a game propably
`{MFC Thread} MEM: Access violation reading location 0x0`

## PS3

![bionic 4](https://cloud.githubusercontent.com/assets/11453507/23836165/5bbc26f8-0774-11e7-9743-1daa6b72694e.PNG)

## RPCS3

![bionic 1](https://cloud.githubusercontent.com/assets/11453507/23836056/13b469c6-0772-11e7-9974-48241d98a53f.PNG)
![bionic 2](https://cloud.githubusercontent.com/assets/11453507/23836055/13b3014e-0772-11e7-98a2-f651049a66e8.PNG)
![bionic 3](https://cloud.githubusercontent.com/assets/11453507/23836057/13b4892e-0772-11e7-9363-ec32e3aa7be2.PNG)

![bionic 5](https://cloud.githubusercontent.com/assets/11453507/23836174/85e1b97a-0774-11e7-8738-61bf357f3657.PNG)

[RenderDoc menu](https://mega.nz/#!zRkiBRAA!l0YC7dZ5JfeMH5s0BiNHcMlJZ79plmZCqNEkkuEiJ1A)
[RenderDoc ingame](https://mega.nz/#!LRFUxYYL!2xxL06Ho4djPKLTa49RAbKciKFeyKX3hxh4mrcEhUJ4)
[LOG](https://mega.nz/#!eQFBiDIR!UBnD2bWUzKm9j8nh2y-zn4sEduJTasaycFvONxHW8UQ)

**Comment by raven02** [comment]
Did DX12 and Vulkan render correct ?

**Comment by JohnGodgames** [comment]
@kd-11 

In latest master https://github.com/RPCS3/rpcs3/commit/617746606d881f57314fc48f93df1a8e9e086d5b it shows more things.

If you use a lower resolution (720x480).You can get a clear output as  in video.If you set a 1280x720 you will get ![bionic 2](https://cloud.githubusercontent.com/assets/11453507/23836055/13b3014e-0772-11e7-98a2-f651049a66e8.PNG) some cache issue?The same engine uses a Wanted: weapons of fate, there are similar symptoms (blue/white) ingame.


[VIDEO](https://www.youtube.com/watch?v=wK8_fm5NBTU)

**Comment by kd-11** [comment]
Looks like a texture cache bug. These are very rare but there are cases where they have been reported.

**Comment by Xcedf** [comment]
No longer an issue game looks perfect after rdr blue fix

**Comment by JohnGodgames** [comment]
Yeah it's a lot of better.

https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-5320/artifacts

[![bionic commando](https://img.youtube.com/vi/wdw6ypd3lFE/0.jpg)](https://www.youtube.com/watch?v=wdw6ypd3lFE)
