### ISSUE TITLE
RSX: Unknown/illegal instruction

### ISSUE THREAD

**Issue by Nmzik** [RPCS3/rpcs3#2520]
Tested by 2c5f382
Grand Theft Auto V
E {rsx::thread} RSX: Unknown/illegal instruction: 0x2f (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x17 (forced unit 2)

**Comment by kd-11** [comment]
These are technically illegal instructions afaik, but that is not a problem. RPCS3 doesn't emulate real RSX hardware at a level where these would make a real difference, so it is possible that the shader compiler was buggy or had hand-written assembly that was buggy.
