### ISSUE TITLE
GL/VK - Command & Conquer: Red Alert 3 - Rendering Issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2524]
Tested by https://github.com/RPCS3/rpcs3/commit/c8b9cc9fe5c6eb7041721eb6f5258b5e1f0cf36f

Vulkan have a similar issues as GL.Sometimes it throws `F {rsx::thread} class std::runtime_error thrown: Invalid RSX method 0x4 (arg=0x80394) (in file Emu\RSX\rsx_methods.cpp:34)` at intro video, or just hangs.

![red alert 3 1](https://cloud.githubusercontent.com/assets/11453507/23850858/81e8e948-07e1-11e7-96db-c85735943798.PNG)
![red alert 3 2](https://cloud.githubusercontent.com/assets/11453507/23850857/81e86ef0-07e1-11e7-9213-37bbc3fd21f0.PNG)
![red alert 3 3](https://cloud.githubusercontent.com/assets/11453507/23850859/81e9c520-07e1-11e7-9fef-60297b0a05eb.PNG)

[RenderDoc menu GL](https://mega.nz/#!uEV2CAAD!UtQXWLY7helDHAQLDgngUMLXj2wtwEZ5ympk_URoSrQ)
[RenderDoc ingame GL](https://mega.nz/#!2ANxmDpA!y8ScrfamHDgKto9w2zjmcrGLRb8sq9LVAQk9Nhp4ORk)
[shaderlog GL](https://mega.nz/#!6JsCzDBD!nbp7qYirwyBHra2aHoCdFJYZlFMe6ibcE6vv4hxLhZA)
[LOG](https://mega.nz/#!yJlESJhL!f9aRLMcSnuzani7d00wu6pAmOgerj92g1K-5p1UiQ4k)

**Comment by MarioSonic2987** [comment]
@JohnGodgames Is this still an issue?

**Comment by JohnGodgames** [comment]
Retested with https://github.com/RPCS3/rpcs3/commit/da3f3fd1fb1682d2b4f7c30600b6174942b71813

![cc3 1](https://user-images.githubusercontent.com/11453507/29925874-fbe8e570-8e61-11e7-9831-8b61e8b286dd.PNG)
![cc3 2](https://user-images.githubusercontent.com/11453507/29925875-fc0142c8-8e61-11e7-96cf-08262cbbeeaa.PNG)
