### ISSUE TITLE
WWE SmackDown vs. Raw 2009 / WWE Legends of WrestleMania - sys_mutex_destroy failed

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2526]
Tested by https://github.com/RPCS3/rpcs3/commit/ed711c0e59abab4900f0ea2b30c084f4dacd8100

Both of these games have the same issue and hangs at the same point (after movies)

**WWE SmackDown vs. Raw 2009**
`E {PPU[0x1000016] Thread (CMovieControlPS3) [0x00a3d84c]} 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY`
[LOG](https://mega.nz/#!uE0w1BzR!YW4WxX8esFR8lvo62QUHD9Qa7ayIkgvTRu6upaFk2IU)

**WWE Legends of WrestleMania**
`E {PPU[0x1000016] Thread (CMovieControlPS3) [0x00946ac4]} 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY`
[LOG](https://mega.nz/#!zMUDmKKR!nd1wtBpkXw8U2W-jg9-1EBD0p8zmGubIgI1SzZ6Pc4A)

**Comment by scribam** [comment]
@JohnGodgames Any improvements on these games with a recent build?

**Comment by digitaldude555** [comment]
![screenshot 2119](https://user-images.githubusercontent.com/26138653/53021414-d4501180-3461-11e9-804a-6818ddcb8d9e.png)
If you turn off entrance videos in the ingame menu then you go ingame, otherwise, it freezes loading the match. So the issue is the movies.

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by Megamouse** [comment]
please retest. It's been over a year since the last update.

**Comment by Satan86** [comment]
Still an issue

**Comment by Megamouse** [comment]
please retest. It's almost been a year since the last update.

**Comment by Satan86** [comment]
Still an issue

**Comment by kd-11** [comment]
Can it be fixed by using LLE vdec?

**Comment by Satan86** [comment]
No

**Comment by Washong** [comment]
Can someone close this for a inactivity please?

**Comment by Jonathan44062** [comment]
Why? No, if the issue is still present, this ticket needs to be open, it will be closed once this problem is fixed

**Comment by Washong** [comment]
Oh ok

**Comment by elad335** [comment]
Maybe update logs with PPU/SPU debug options enabled.

**Comment by Satan86** [comment]
Log with PPU/SPU debug options enabled for WWE SmackDown vs. RAW 2009.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9509185/RPCS3.log.gz)

**Comment by elad335** [comment]
![image](https://user-images.githubusercontent.com/18193363/189075665-58f38765-d3a3-45e2-9ce0-d9b259e55d4c.png)
Need some testing on realhw.

**Comment by Satan86** [comment]
Works perfectly fine on my PS3.
![IMG_20220908_131616](https://user-images.githubusercontent.com/61447828/189120132-6e1a28a5-3c30-435b-b861-f2bc96f3a85d.jpg)
You did test with entrances turned on, right? If you turn them off, it works.

**Comment by Shoegzer** [comment]
Just a note that a similar hanging issue this is intended to fix also occurs with Far Cry Classic (#5968), and the same message reported here also appears in the Far Cry log:

`·E 0:00:23.256051 {PPU[0x1000005] Thread (Rendering Thread) [0x00a85ab4]} 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY [1]`
 
That said, it remains an issue after testing with PR #12625.  I'm assuming this one is at least resolved (a long-standing issue - great!), though I don't have WWE to test and confirm.

**Comment by Satan86** [comment]
It is fixed indeed.
