### ISSUE TITLE
Several games throws - Unimplemented cellGcmSetUserCommand

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2527]
Tested by https://github.com/RPCS3/rpcs3/commit/ed711c0e59abab4900f0ea2b30c084f4dacd8100

![gcmsys 1](https://cloud.githubusercontent.com/assets/11453507/23856876/6702a41a-07fb-11e7-821e-c69da00b2bce.PNG)

**Cars Mater-National Championship**
```
F {PPU[0x1000005] Thread (RenderThread) [0x004e5128]} class std::runtime_error thrown: Unimplemented (in file Emu\Cell\Modules\cellGcmSys.cpp:620)
```
[LOG](https://mega.nz/#!6UcU0RKB!Lw-bj_6Asa3UMdn-fWTrEwzYndKsg2JoAyPCtBDO-xk)

**Blacksite Area 51**
```
F {PPU[0x100000a] Thread (RenderingThread) [0x011c0ad0]} class std::runtime_error thrown: Unimplemented (in file Emu\Cell\Modules\cellGcmSys.cpp:620)
```

[LOG](https://mega.nz/#!CYFQCJhZ!t4szs3QfFqZBMi4VI3pNdW0OQfY6l_BqBXiZkvgy810)

**Transformers The Game**
```
F {PPU[0x1000000] Thread (main_thread) [0x00457bb0]} class std::runtime_error thrown: Unimplemented
(in file Emu\Cell\Modules\cellGcmSys.cpp:620)
```

[LOG](https://mega.nz/#!zNNCEDDa!UqBjEXMVc0q3gqynNUPjYvdV2i8PSNqJ0fHYdNoF-os)

**Comment by AniLeo** [comment]
Already on #1936, added those there as well
