### ISSUE TITLE
Project DIVA F 2nd-NPHB00671 issue

### ISSUE THREAD

**Issue by lijun0326** [RPCS3/rpcs3#2528]
**RPCS3 version:** v0.0.2-3-b70a1ed
**PPU**: LLVM (Interpreter also tried)
**SPU**: ASMJIT
Logs are the following:
> E {PPU[0x1000000] Thread (main_thread) [0x006403a4]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x006403a4]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x006403a4]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x006403a4]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
U {PPU[0x1000000] Thread (main_thread) [0x006403a4]} cellGcmSys TODO: cellGcmSetQueueHandler
E {PPU[0x1000000] Thread (main_thread) [0x006403a4]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x006403a4]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x006403a4]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
U {PPU[0x1000000] Thread (main_thread) [0x006403a4]} cellUsbd TODO: cellUsbdRegisterExtraLdd
E {PPU[0x1000000] Thread (main_thread) [0x006403a4]} sys_fs: sys_fs_stat(“/dev_hdd0/game/NPHB00671/USRDIR/patch/patch_flist.txt”) failed: not found
E {PPU[0x1000000] Thread (main_thread) [0x006403a4]} 'cellFsStat' failed with 0x80010006 : CELL_ENOENT
U {PPU[0x1000003] Thread (fios mediathread 2) [0x0066df68]} cellSpurs TODO: _cellSpursLFQueuePushBody

**Comment by lijun0326** [comment]
Here is the detailed log.
[RPCS3.log.txt](https://github.com/RPCS3/rpcs3/files/838424/RPCS3.log.txt)

**Comment by SakataGintokiYT** [comment]
@lijun0326 
Why you don't use Load required libraries.

**Comment by AniLeo** [comment]
You're not using the libraries correctly. Please use the forums for support and not the GitHub issue tracker.
http://www.emunewz.net/forum/forumdisplay.php?fid=172

**Comment by al0xf** [comment]
https://rpcs3.net/quickstart
