### ISSUE TITLE
Several games throws - Unimplemented cellGcmFunc2

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2529]
Tested by https://github.com/RPCS3/rpcs3/commit/ed711c0e59abab4900f0ea2b30c084f4dacd8100

![gcm 2](https://cloud.githubusercontent.com/assets/11453507/23857324/358e2bdc-07fd-11e7-8d5b-e96f0106c3b0.PNG)

**Blazing Angels Squadrons of WWII**
```
F {PPU[0x1000000] Thread (main_thread) [0x004eae58]} class std::runtime_error thrown: Unimplemented
(in file Emu\Cell\Modules\cellGcmSys.cpp:1221)
```
[LOG](url)

**Surf's Up**
```
F {PPU[0x1000000] Thread (main_thread) [0x009d41dc]} class std::runtime_error thrown: Unimplemented
(in file Emu\Cell\Modules\cellGcmSys.cpp:1221)
```
[LOG](https://mega.nz/#!vc9CgRBC!YbhaFBg9UebAtVGC5jIzuOwif962nM8A91XUu9crQG0)

**Comment by AniLeo** [comment]
Already on #1936, I have added those there. First log hyperlink is broken though.
