### ISSUE TITLE
Project DIVA F-NBJP00287 issue - Error reading edata header!

### ISSUE THREAD

**Issue by lijun0326** [RPCS3/rpcs3#2530]
RPCS3 version: v0.0.2-3-b70a1ed
PPU: LLVM (Interpreter also tried)
SPU: ASMJIT
Logs are the following:

> ·W 0:00:04.525670 {PPU[0x1000006] Thread (thr_bootcheck) [0x005730c8]} sceNp: npDrmIsAvailable(): Can't find RAP file for /dev_hdd0/game/NPJB00287/USRDIR/rom/chkboot.edat
·W 0:00:04.525696 {PPU[0x1000006] Thread (thr_bootcheck) [0x005730c8]} cellFs: cellFsOpen(path=“/dev_hdd0/game/NPJB00287/USRDIR/rom/chkboot.edat”, flags=0, fd=*0xd0077c40, arg=*0xd0077c48, size=0x8) -> sys_fs_open()
·W 0:00:04.525703 {PPU[0x1000006] Thread (thr_bootcheck) [0x005730c8]} sys_fs: sys_fs_open(path=“/dev_hdd0/game/NPJB00287/USRDIR/rom/chkboot.edat”, flags=0, fd=*0xd0077c40, mode=0, arg=*0xd0077c48, size=0x8)
·E 0:00:04.525757 {PPU[0x1000006] Thread (thr_bootcheck) [0x005730c8]} LDR: EDAT: A valid RAP file is needed for this EDAT file!
·E 0:00:04.525764 {PPU[0x1000006] Thread (thr_bootcheck) [0x005730c8]} sys_fs: sys_fs_open(“/dev_hdd0/game/NPJB00287/USRDIR/rom/chkboot.edat”): Error reading edata header!
·E 0:00:04.525769 {PPU[0x1000006] Thread (thr_bootcheck) [0x005730c8]} 'cellFsOpen' failed with 0x80010038 : CELL_EFSSPECIFIC
[RPCS3.log.txt](https://github.com/RPCS3/rpcs3/files/838396/RPCS3.log.txt)

**Comment by AniLeo** [comment]
Please use the forums for those kinds of reports http://www.emunewz.net/forum/forumdisplay.php?fid=172
This is not a game breaking issue. You haven't installed the firmware correctly.
