### ISSUE TITLE
GL / Vulkan : Sengoku Basara: Samurai Heroes-black textures

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2536]
@kd-11 

[Write color buffer is required]
<img src="http://www.fotoszok.pl/upload/c99ef0a7.jpg" alt="Fotoszok.pl" />

**[OpenGL-RenderDoc](https://mega.nz/#!cMg2BL5R!0Dc3UtdObq4Om0RwpUgTiMKxO8Omd6nlKQYnIsqJySU)**
**[ShaderLog:](https://mega.nz/#!ARBEFZQD!zsBclcHneMGYILd5OrQTD22Pqwn4onWqHCYQc0Z6FS0)**
**[Log:](https://mega.nz/#!xVJUiZJD!T-FdNJ0gd5HIYwnzQZpxbsN12rfZfLFfK9NwPzsMUDY)**

**Comment by kd-11** [comment]
Is this still an issue?

**Comment by SakataGintokiYT** [comment]
@kd-11 
Yes, still black screen with gui ;/

**Comment by MarioSonic2987** [comment]
Is this still an issue?

**Comment by kd-11** [comment]
Still an issue?

**Comment by SakataGintokiYT** [comment]
@kd-11
Still the same issue ;/
![bez tytulu](https://user-images.githubusercontent.com/13681488/30138228-68a43ed0-9367-11e7-80f1-20c414b4c82c.png)

**Comment by SakataGintokiYT** [comment]
@kd-11 

[WIP] rsx: Fixes #3699
**[Vulkan]**
![bez tytulu](https://user-images.githubusercontent.com/13681488/32413261-3520dd18-c20e-11e7-855a-7a9b10b5dc49.png)

**[OpenGL]**
![g](https://user-images.githubusercontent.com/13681488/32413263-3bca8132-c20e-11e7-9934-d186b52103b6.png)

**Comment by SakataGintokiYT** [comment]
@kd-11 
The blurry screen is fixed now.
[Vulkan]
![bez tytulu](https://user-images.githubusercontent.com/13681488/32429960-41958728-c2cd-11e7-9c1d-08933c39200f.png)
