### ISSUE TITLE
Grand Theft Auto V [NPUB31154] rsx::thread: gl::glsl::link_exception thrown: linkage failed

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2537]
RPCS3 v0.0.2-7-3fe93ef Alpha

> ·! 0:03:40.663481 {rsx::thread} RSX: Add program :
·! 0:03:40.663491 {rsx::thread} RSX: *** vp id = 205
·! 0:03:40.663496 {rsx::thread} RSX: *** fp id = 107
·F 0:03:40.689981 {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
0(131) : error C0000: syntax error, unexpected '.', expecting "::" at token "."
(0) : error C2003: incompatible options for link
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/842141/RPCS3.zip)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/2567

**Comment by aakh1361** [comment]
> E {rsx::thread} RSX: dst index out of range: 24
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: dst index out of range: 16
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: Bad src1 reg type: 0
E {rsx::thread} RSX: Bad src1 reg type: 0
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: Bad src1 reg type: 0
E {rsx::thread} RSX: Bad src1 reg type: 0
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: Bad src1 reg type: 0
E {rsx::thread} RSX: Bad src1 reg type: 0
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: Bad src0 reg type: 0
E {rsx::thread} RSX: Bad src1 reg type: 0
E {rsx::thread} RSX: Bad src1 reg type: 0
E {rsx::thread} RSX: Failed to compile vertex shader: 0(160) : error C0000: syntax error, unexpected '.', expecting "::" at token "."
0(161) : error C0000: syntax error, unexpected '.', expecting "::" at token "."
0(162) : error C0000: syntax error, unexpected '.', expecting "::" at token "."
F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
0(160) : error C0000: syntax error, unexpected '.', expecting "::" at token "."
0(161) : error C0000: syntax error, unexpected '.', expecting "::" at token "."
0(162) : error C0000: syntax error, unexpected '.', expecting "::" at token "."
(0) : error C2003: incompatible options for link
'
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/858136/RPCS3.zip)

**Comment by kd-11** [comment]
Broken VS ucode it seems.
This section
```
	dst_reg24.xw = (.zzzz + -vc[467].zxxz).xw;
	if (notEqual(cc0.xxxx, vec4(0., 0., 0., 0.)).x) dst_reg16.zw.x = (.zzzz * .xxxx).zw.x;
	if (notEqual(cc0.xxxx, vec4(0., 0., 0., 0.)).y) dst_reg16.zw.y = (.zzzz * .xxxx).zw.y;
```
Reeks of memory corruption errors

**Comment by aakh1361** [comment]
**DX12**
[DX12.zip](https://github.com/RPCS3/rpcs3/files/858327/DX12.zip)

> {rsx::thread} class std::runtime_error thrown: HRESULT = The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12RenderTargetSets.cpp:279)


**Vulkan**
[Vulkan.zip](https://github.com/RPCS3/rpcs3/files/858335/Vulkan.zip)

> F {rsx::thread} class std::runtime_error thrown: rsx::thread::ReadIO32(addr=0x10d34808): RSXIO memory not mapped
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:1073)

**Comment by kd-11** [comment]
The original bug listed here was due to corrupted memory, but that seems to have been fixed and now its a memory mapping issue. Is this correct?

**Comment by aakh1361** [comment]
Yes You Right
Fix Bug in last build

**Comment by AniLeo** [comment]
Closing this then since the issue was fixed. Feel free to open a new one if you find a new issue.
