### ISSUE TITLE
Demon's Souls loading error

### ISSUE THREAD

**Issue by clausavram** [RPCS3/rpcs3#2538]
When I try to start up Demon's Souls, I get lots of loader errors and the window stays black.
Here is a sample:

> E LDR: Unknown module 'cellLibprof'
> E LDR: Unknown function '0x05893E7C' in module 'cellLibprof' (index 3006)
> E LDR: Unknown function '0x6D045C2E' in module 'cellLibprof' (index 3007)
> E LDR: Unknown function '0x7CBA9865' in module 'cellM2AACdec' (index 3008)
> E LDR: Unknown variable '0xAC2F0831' in module 'cellM2AACdec'
> E LDR: Unknown function '0x8C7AD5ED' in module 'cellDTSdec' (index 3009)
> E LDR: Unknown variable '0x15248EC5' in module 'cellDTSdec'
> E LDR: Unknown function '0x73A2C895' in module 'cellMP3Sdec' (index 3010)
> E LDR: Unknown variable '0x292CDF0A' in module 'cellMP3Sdec'
> E LDR: Unknown function '0xF3AF1093' in module 'cellDTSHDdec' (index 3011)
> E LDR: Unknown variable '0x51AC2B6C' in module 'cellDTSHDdec'
> E LDR: Unknown function '0x9FB6228E' in module 'sysPrxForUser' (index 3012)
> E LDR: Unknown function '0xD4C180D4' in module 'cellDTSHDCOREdec' (index 3013)
> E LDR: Unknown variable '0x6C8F4F1C' in module 'cellDTSHDCOREdec'
> E LDR: Unknown function '0x75080F7B' in module 'cellTRHDdec' (index 3014)
> E LDR: Unknown variable '0xE88E381B' in module 'cellTRHDdec'
> E LDR: Unknown function '0x185591D6' in module 'cellDTSLBRdec' (index 3015)
> E LDR: Unknown variable '0x8C50AF52' in module 'cellDTSLBRdec'
> E LDR: Unknown function '0x156FE2F0' in module 'cellM4AacDec2chmod' (index 3016)
> E LDR: Unknown variable '0xDBD26836' in module 'cellM4AacDec2chmod'
> E LDR: Unknown function '0x8D45F21A' in module 'cellWMAPROdec' (index 3017)
> E LDR: Unknown variable '0xA8BAC670' in module 'cellWMAPROdec'
> E LDR: Unknown function '0xF2F9C183' in module 'cellWMALSLdec' (index 3018)
> E LDR: Unknown variable '0x602AAB16' in module 'cellWMALSLdec'
> U {PPU[0x1000000] Thread (main_thread) [0x020d51c4]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
> U {PPU[0x1000000] Thread (main_thread) [0x016bcd20]} sysPrxForUser TODO: _sys_process_atexitspawn()
> U {PPU[0x1000000] Thread (main_thread) [0x016bcee0]} sysPrxForUser TODO: _sys_process_at_Exitspawn
> U {PPU[0x1000000] Thread (main_thread) [0x020fbd80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
> ...

[Demon's Souls errors.txt](https://github.com/RPCS3/rpcs3/files/843016/Demon.s.Souls.errors.txt)

I'm running on Windows 10, with the game being in Blu-ray Disk format (PS3_GAME) and the firmware was just downloaded from PlayStation.com

Could there be an additional setup step?

**Comment by hcorion** [comment]
Some additional system information would be useful like CPU and GPU. Graphics drivers version would also be helpful.

**Comment by TheKuma** [comment]
Seems like you have the PSN version of Demon Souls, that is why it is failing to mount.
RPCS3 doesn't have the capability to mount Virtual Disks at this moment.

You are better off getting a non PSN version of the game, as that is confirmed working.

**Comment by AniLeo** [comment]
Please use the forums to ask for support and read the guide on how to report issues

**Comment by clausavram** [comment]
Didn't realize it was a PSN version.
Apologies for the wasting your time.

**Comment by boo9** [comment]
I'm having problems with demon souls as well. I have a disk category BLUS30443 and have no clue what to do or were to start. Please help and point me in the right direction.

E {PPU[0x1000000] Thread (main_thread) [0x01542270]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000000] Thread (main_thread) [0x01542ea8]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000000] Thread (main_thread) [0x01d554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x01d554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x01d554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
S {SPU[0x2000001] Thread (DLSpursManagerCellSpursKernel1) [0x0f6f8]} SPU: LLVM: Building spu-0x0f6f8-tG5zofRsLLmYjyAQEHjcGqMtt0a3 (size 14)...
F {PPU[0x100000e] Thread (MOMainThread) [0x00d5f080]} MEM: Access violation reading location 0x0
U {PPU[0x1000000] Thread (main_thread) [0x00e6a184]} sceNp2 TODO: sceNpMatching2Init(poolsize=0x0, priority=0)
U {PPU[0x1000000] Thread (main_thread) [0x00e6a19c]} cellNetCtl TODO: cellNetCtlAddHandler(handler=*0x1980238, arg=*0x1bb9f78, hid=*0x1bba070)
U {PPU[0x1000000] Thread (main_thread) [0x00e490cc]} sceNp TODO: sceNpBasicRegisterContextSensitiveHandler
U {PPU[0x1000000] Thread (main_thread) [0x00e43f78]} sceNp TODO: sceNpBasicGetMatchingInvitationEntryCount(count=*0xd0100600)
U {PPU[0x1000000] Thread (main_thread) [0x01d54f78]} sceNp TODO: sceNpManagerGetNpId(npId=*0xd01001d4)
U {PPU[0x1000000] Thread (main_thread) [0x00e123ec]} sceNp TODO: sceNpManagerGetOnlineName(onlineName=*0xd01001f8)
U {PPU[0x1000000] Thread (main_thread) [0x00e123fc]} sceNp TODO: sceNpManagerGetAvatarUrl(avatarUrl=*0xd010022c)
E {PPU[0x1000000] Thread (main_thread) [0x01d54dac]} 'cellPadSetActDirect' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [1]
E {PPU[0x1000000] Thread (main_thread) [0x00c45970]} 'cellPadGetData' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [1]
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00c3a878]} sceNp TODO: sceNpManagerGetNpId(npId=*0xd0378864)
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e123ec]} sceNp TODO: sceNpManagerGetOnlineName(onlineName=*0xd0378888)
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e123fc]} sceNp TODO: sceNpManagerGetAvatarUrl(avatarUrl=*0xd03788bc)
E {PPU[0x1000018] Thread (DsSaveLoadMan::AsyncGetHddFreeSizeThread) [0x00c3a878]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLUS30443”, errDialog=0x0, funcStat=*0x1970c00, container=4294967295)
E {PPU[0x1000000] Thread (main_thread) [0x00c3a9d4]} 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [1]
U {SPU[0x2000001] Thread (DLSpursManagerCellSpursKernel1) [0x03080]} SPU TODO: [0x30bc] Unexpected instruction on $SP: SELB
S {SPU[0x2000001] Thread (DLSpursManagerCellSpursKernel1) [0x03080]} SPU: LLVM: Building spu-0x03080-fATzErnFT3CrhR1JjKs4y38sfetP (size 24)...
U {SPU[0x2000002] Thread (DLSpursManagerCellSpursKernel2) [0x03080]} SPU TODO: [0x30bc] Unexpected instruction on $SP: SELB
U {SPU[0x2000004] Thread (DLSpursManagerCellSpursKernel4) [0x03080]} SPU TODO: [0x30bc] Unexpected instruction on $SP: SELB
U {SPU[0x2000003] Thread (DLSpursManagerCellSpursKernel3) [0x03080]} SPU TODO: [0x30bc] Unexpected instruction on $SP: SELB
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00b5d90c]} sceNp TODO: sceNpManagerGetNpId(npId=*0xd0378864)
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e123ec]} sceNp TODO: sceNpManagerGetOnlineName(onlineName=*0xd0378888)
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e123fc]} sceNp TODO: sceNpManagerGetAvatarUrl(avatarUrl=*0xd03788bc)
