### ISSUE TITLE
gui not usable with hidpi on linux

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#2539]
I'm experimenting on linux these days. I have a 4k monitor, running Archlinux and latest kde. When I open the settings, I can't see everything on the screen and resizing the window doesn't resize what's inside. So, it's impossible to use it.

![gui-hidpi-rescalingpb-01](https://cloud.githubusercontent.com/assets/7478580/23934991/779b37f2-0949-11e7-9572-ab5c38cac666.png)

**Comment by oangelo** [comment]
I am having a similar problem, also in Archlinux. This might be a KDE issue rendering a gtk screen? I had some problems with programs wit gtk interfaces in KDE....
![image](https://cloud.githubusercontent.com/assets/1669411/24022303/6d241d52-0a84-11e7-97c6-c709685fc948.png)
Try using XFCE or gnome... If you manage to make Super Street Fighter 2 work, tel me, I could not.

**Comment by Nekotekina** [comment]
Does wxWidgets really support this conception? I'm not sure.

**Comment by oangelo** [comment]
Well, running rpcs3 in MATE (gnome like desktop) I had no problems and I could see all the options.

**Comment by aakh1361** [comment]
I have This problem in windows 10
![0](https://cloud.githubusercontent.com/assets/25039098/24039041/05aa0e08-0b19-11e7-89d4-41088a0689b5.jpg)

**after search in option i see select this option**

![ll](https://cloud.githubusercontent.com/assets/25039098/24039079/18963942-0b19-11e7-88ec-1aedde62ae11.jpg)

now unselect this option and fix problem

![1](https://cloud.githubusercontent.com/assets/25039098/24039133/43c03a28-0b19-11e7-9972-1c06485fdff5.jpg)

**Comment by AniLeo** [comment]
@toccata10 please retest with latest master that uses QT instead of wxWidgets.

**Comment by toccata10** [comment]
r5251: the welcome screen is still problematic (can't see everything, but can guess the missing parts).
The rest: very good on hidpi. Well Done !

**Comment by AniLeo** [comment]
What does the welcome screen look like?

**Comment by toccata10** [comment]
[
![wlecomescreen-hidpi-pb](https://cloud.githubusercontent.com/assets/7478580/26792494/de64885a-4a1a-11e7-9d75-127774db57cc.png)
](url)
and there's no way to resize anything.

**Comment by Megamouse** [comment]
so I assume it is super small?

**Comment by toccata10** [comment]
![wlecomescreen-hidpi-pb-02](https://cloud.githubusercontent.com/assets/7478580/26792964/80a42ce6-4a1c-11e7-82d3-4030f33e3312.png)
No, I can read it perfectly. The problem is with spacing: things are overlapping. And I can't resize this box by dragging a corner.

**Comment by Megamouse** [comment]
The size is set to its sizehint, so i'm not really sure whats the problem here. Maybe @hcorion can be of use here. Cause I don't have linux

**Comment by hcorion** [comment]
@toccata10 Try setting `export QT_AUTO_SCREEN_SCALE_FACTOR=1`, it might help

**Comment by toccata10** [comment]
![wlecomescreen-hidpi-pb-03](https://cloud.githubusercontent.com/assets/7478580/26797325/d3d751c6-4a2c-11e7-833d-7d2ab75b9041.png)
With export QT_AUTO_SCREEN_SCALE_FACTOR=1: welcome screen is ok, but I have to resize rpcs3 after that. If I close and re-open, the sizes are saved.
The other applications work without this parameter, as I've put my setting in kde here:
    System Settings → Display and Monitor → Display Configuration → Scale Display
So, few people will know that they need export QT_AUTO_SCREEN_SCALE_FACTOR=1 to have a correct rendering.

**Comment by Megamouse** [comment]
please try with my PR #2834

**Comment by toccata10** [comment]
![wlecomescreen-hidpi-pb-04](https://cloud.githubusercontent.com/assets/7478580/26804499/7af14172-4a48-11e7-8eaf-ec3563341276.png)
This is what I tried (sorry, not very used to github and testing PR):
git clone https://github.com/flash-fire/rpcs3.git -b shortcut_fixes
cd rpcs3/
#test with clang
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
git submodule update --init
cmake CMakeLists.txt && make GitVersion && make

Result is nice (see screenshot). It's great to have the gui working on hidpi screen. So, problem solved from my point of view. Thanks.

**Comment by Megamouse** [comment]
what still remains of course is the hidpi implementation without interfering with gsframe render size.
It would be nice to get some gsframe related feedback for the "QT_AUTO_SCREEN_SCALE_FACTOR = 1" environment variable on hidpi scaling.
As said before, on my OS the GSframe is 3/4 black and 1/4 game. the whole game screen, only small in one corner of the gsframe. This has been top left on spyro the last time i checked and this time it was lower left on minecraft. maybe some weird stuff with origin being top left or top right depending on renderer or game engine

**Comment by toccata10** [comment]
![welcomescreen-hidpi-pb-05](https://cloud.githubusercontent.com/assets/7478580/26815639/b62b85f0-4a8d-11e7-8e81-70d8ba865017.jpg)
![welcomescreen-hidpi-pb-06](https://cloud.githubusercontent.com/assets/7478580/26815638/b629a668-4a8d-11e7-8f8a-7d6ed780269c.jpg)
![welcomescreen-hidpi-pb-07](https://cloud.githubusercontent.com/assets/7478580/26815640/b62c6a06-4a8d-11e7-939c-b71565482fdc.jpg)
![welcomescreen-hidpi-pb-08](https://cloud.githubusercontent.com/assets/7478580/26815641/b62d6550-4a8d-11e7-97fd-826541ad4f22.jpg)
With export QT_AUTO_SCREEN_SCALE_FACTOR=1, these 2 games are displayed in the lower left corner. With export QT_AUTO_SCREEN_SCALE_FACTOR=0, correct. Archlinux, mesa-stable 17.1.1

**Comment by kd-11** [comment]
Looks like QT is passing widget dimensions as modified by the scaling factor, a factor of 2 in the above case. Raster coords are usually from the lower left which is why the viewport gets stuck there. Maybe we can modify the width() and height() methods (Defined in GSFrame or GSFrameBase) to autocorrect dimensions so we can properly do the blit. Or disable scaling on GSFrame completely somehow. Unless there's a way to get "true" dimensions from widgets.

**Comment by Megamouse** [comment]
I tried scaling factor 2 but this seems so arbitrary.
Worked though.

**Comment by kd-11** [comment]
It is arbitrary. There must be a better way to query for this value from the runtime somehow.

**Comment by Megamouse** [comment]
please have a look again on my PR #2834

**Comment by toccata10** [comment]
Seems good: when I launch a game, it starts with the window maximised. I can keep it like this, go full screen with alt+enter.
Same behaviour with export QT_AUTO_SCREEN_SCALE_FACTOR=1 and with 0.
Well done !

**Comment by Megamouse** [comment]
QT_AUTO_SCREEN_SCALE_FACTOR = 1 is set as default for other than windows now btw

**Comment by AniLeo** [comment]
Fixed on #2834
