### ISSUE TITLE
DX12/GL: Minecraft - water fails to render properly

### ISSUE THREAD

**Issue by Nicba1010** [RPCS3/rpcs3#2541]
As the title says.
Included: offending screenshot, renderdoc capture (7z in zip file because github)
![water.png](https://cloud.githubusercontent.com/assets/3586606/24006928/622c59d0-0a6d-11e7-9a3c-04768f72f89f.png)

[water.zip](https://github.com/RPCS3/rpcs3/files/848357/water.zip)

In renderdoc the water screwup occurs @ EID 36771

**Comment by Nicba1010** [comment]
In renderdoc the water screwup occurs @ EID 36771

**Comment by AniLeo** [comment]
Only on OpenGL?

**Comment by darkredflame** [comment]
@AniLeo This game doesn't load when you use the Vulkan render option. As for DX12, it loads into the game, but it shows the same issue with the water.

![rpcs3_2017-03-17_12-12-27](https://cloud.githubusercontent.com/assets/12888227/24056985/5048b616-0b0b-11e7-8bc0-bc67ec59a16f.png)
[RPCS3-Vulkan.zip](https://github.com/RPCS3/rpcs3/files/851422/RPCS3-Vulkan.zip)
[RPCS3-DX12.zip](https://github.com/RPCS3/rpcs3/files/851423/RPCS3-DX12.zip)

**Comment by raven02** [comment]
I just tested it and Vulkan even not able to boot up due to vertex buffer issue

> F {rsx::thread} class std::runtime_error thrown: vertex buffer not found
> (in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKProgramPipeline.cpp:103)

(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKProgramPipeline.cpp:103)

**Comment by SakataGintokiYT** [comment]
**Vulkan / OpenGL / DX12**
![bez tytulu](https://user-images.githubusercontent.com/13681488/27950930-6d2fff96-6303-11e7-808f-74ddcb8aac01.jpg)

**Comment by raven02** [comment]
From master or the newer kd11 pull?

**Comment by SakataGintokiYT** [comment]
master

**Comment by raven02** [comment]
I see. GL also fixed?

**Comment by Megamouse** [comment]
master 2960
![image](https://user-images.githubusercontent.com/23019877/27957622-87f59824-631f-11e7-98ab-5ee0b6a20c4f.png)

![image](https://user-images.githubusercontent.com/23019877/27957700-e1bb810c-631f-11e7-8c61-6b4ded0af648.png)

![image](https://user-images.githubusercontent.com/23019877/27957797-4e872ab6-6320-11e7-9b18-8915bf91a451.png)

**Comment by AniLeo** [comment]
Since it's solved on master, closing.
