### ISSUE TITLE
[bug] Cmake stops build when checking compiler version

### ISSUE THREAD

**Issue by XenonPK** [RPCS3/rpcs3#2545]
After hearing about Demon's Souls, I decided to try my luck at packaging RPCS3 for my linux machines. From the get-go, cmake gives up on the build prematurely:

> [  90s] -- The C compiler identification is GNU 6.3.1
[   90s] -- The CXX compiler identification is GNU 6.3.1
[   90s] -- Check for working C compiler: /usr/bin/cc
[   91s] -- Check for working C compiler: /usr/bin/cc -- works
[   91s] -- Detecting C compiler ABI info
[   91s] -- Detecting C compiler ABI info - done
[   91s] -- Detecting C compile features
[   91s] -- Detecting C compile features - done
[   91s] -- Check for working CXX compiler: /usr/bin/c++
[   92s] -- Check for working CXX compiler: /usr/bin/c++ -- works
[   92s] -- Detecting CXX compiler ABI info
[   92s] -- Detecting CXX compiler ABI info - done
[   92s] -- Detecting CXX compile features
[   93s] -- Detecting CXX compile features - done
[   93s] -- cotire 1.7.3 loaded.
[   93s] CMake Error at rpcs3/cmake_modules/ConfigureCompiler.cmake:9 (list):
[   93s]   list index: 1 out of range (-1, 0)
[   93s] Call Stack (most recent call first):
[   93s]   rpcs3/CMakeLists.txt:17 (include)`

[here's](https://build.opensuse.org/package/live_build_log/home:xenonpk/RPCS3/openSUSE_Tumbleweed/x86_64) the full log, if you're interested.

After commenting the offending line in the Cmake file, it started compiling until #2248 happened. The WIP package specfile is found [here](https://build.opensuse.org/package/view_file/home:xenonpk/RPCS3/RPCS3.spec?expand=1).

**Comment by al0xf** [comment]
Don't know about the compilation errors but consider that the reason we don't have prebuilt Linux binaries is that RPCS3 on Linux is very broken at the moment. Some games work fine, but many like Demon's Souls just crash or hang more or less immediately. 

It is one of the few items left on the short term roadmap to fix this. https://github.com/RPCS3/rpcs3/wiki/Roadmap

**Comment by XenonPK** [comment]
I understand where the development stands. This was mostly for my own personal use, so that I can test without rebuilding for every machine.

The cmake error is easily fixable, however the linker error in #2248 requires someone that knows the code better than me. I tried both gcc and clang, and it happened on both builds, btw.

**Comment by paulsapps** [comment]
Must be because the GCC version components only contain 1 number, for example it is looking for "6" and "1", but if your version is just "6" then trying to check for the "1" component will be out of range.

**Comment by XenonPK** [comment]
The output of gcc -dumpversion is just "6", as @paulsapps  correctly assumed. Due to this, the check will break the build, unless it is skipped entirely.

**Comment by hcorion** [comment]
what distro has GCC compiled like that?

**Comment by XenonPK** [comment]
OpenSUSE (All versions from leap onwards). The full compiler version is 6.3.1, btw, so it would not be affected by the check.

**Comment by paulsapps** [comment]
There is probably a way to check the array size and change the condition to be len(array) >= 2 && mver == 6 && lver == 1

**Comment by clienthax** [comment]
http://stackoverflow.com/questions/14933172/how-can-i-add-a-minimum-compiler-version-requisite

**Comment by clienthax** [comment]
Test

**Comment by AniLeo** [comment]
Is this still an issue?

**Comment by hcorion** [comment]
Yeah, it should be. If OpenSUSE has updated to GCC 7, they may have fixed the issue.

**Comment by AniLeo** [comment]
Fixed by #2867
