### ISSUE TITLE
HOW TO FIX 

### ISSUE THREAD

**Issue by jackyoza** [RPCS3/rpcs3#2548]
F {PPU[0x1000000] Thread (main_thread) [0x014a6130]} class std::runtime_error thrown: Function not registered (index 3009)
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUModule.cpp:162)

**Comment by AniLeo** [comment]
Use the forums for support.
http://www.emunewz.net/forum/forumdisplay.php?fid=172
