### ISSUE TITLE
Regression: Final Fight: Double Impact - Start button does not register on arcade cabinets 

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#2549]
It seems that you can no longer start either game on the arcade cabinets in this game, however there was a previous build where this worked. I have tested this with both keyboard and xinput input methods.

http://www.emunewz.net/forum/showthread.php?tid=163283&pid=230471#pid230471

Last known good build: https://github.com/RPCS3/rpcs3/commit/4ed91d4

![rpcs3_2017-03-17_14-02-26](https://cloud.githubusercontent.com/assets/12888227/24060983/41366d5c-0b1b-11e7-9360-c189034c8a56.png)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/851656/RPCS3.zip)

**Comment by Megamouse** [comment]
Is this still happening?

**Comment by Megamouse** [comment]
I think this has to do with online functionality.
that being said it won't start the custom local game either

**Comment by Megamouse** [comment]
this might be connected to #3985
