### ISSUE TITLE
Setting dialogue issue under some Windows dpi settings

### ISSUE THREAD

**Issue by inkuxuan** [RPCS3/rpcs3#2553]
In some laptops, it is in default settings for everything to be scaled 120%.
In this case the settings dialogue cannot be properly displayed in RPCS3.
This is a screenshot.
![issue_settings](https://cloud.githubusercontent.com/assets/19793388/24071748/aa1696cc-0c14-11e7-9680-81e3a0125d5d.png)

**Comment by aakh1361** [comment]
#2539

**Comment by raven02** [comment]
Thanks @aakh1361 . I tested it and it works for over 100% scaling.
