### ISSUE TITLE
Just Dance 3-20xx PSEye bug

### ISSUE THREAD

**Issue by ttndx2014** [RPCS3/rpcs3#2559]
when i started just dance 2014,its requiring PSEye. ok,i go to settings and change input settings,Null > Fake,and Unknown > PSEye. the problem still persists. what i can do?
[log rpcs3.txt](https://github.com/RPCS3/rpcs3/files/853467/log.rpcs3.txt)

**Comment by AniLeo** [comment]
Log file is RPCS3.log, not the console output you get while running.

PSEye is not implemented, you can't play games like Just Dance that rely heavily on it.

Please use the forums for support.
http://www.emunewz.net/forum/forumdisplay.php?fid=172

**Comment by ttndx2014** [comment]
and,why you implemented the PSEye Option?

**Comment by ttndx2014** [comment]
and my question on the forum is still awaiting moderation

**Comment by AniLeo** [comment]
I can't find your thread on the forums mod queue, please resubmit so I can approve.

PSEye is not implemented, the option is just there for the emulator to try to fake a disabled camera so games that call for PSEye think there's an actual camera there but it won't work with any real cameras and the games may get stuck on it anyways.
Support for miscellaneous controllers such as PSMove and PSEye are in Roadmap already as a long-term goal.

**Comment by ttndx2014** [comment]
I posted the thread to forum,please approve,but before,verify before.
