### ISSUE TITLE
Diablo III log spam sys_event_flag_wait

### ISSUE THREAD

**Issue by OverlordCW** [RPCS3/rpcs3#2562]
When running Diablo III [NPEB01804] RPCS3 spams the log message 'sys_event_flag_wait' failed with 0x80010005 : CELL_ESRCH.
The log file can grow to gigabytes in a short amount of time (<30s).

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/853560/RPCS3.zip)

**Comment by raven02** [comment]
Please discuss this in forum .
