### ISSUE TITLE
 rsx::thread：Kamen Rider - Battride War error

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2563]
1 and 2 of the same situation, after ingame will randomly appear this problem

`F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
-------------
0(64) : error C1008: undefined variable "tex0"
0(64) : error C1008: undefined variable "tc0"
0(64) : error C1008: undefined variable "tex0_coord_scale"
(0) : error C2003: incompatible options for link
'`

![bandicam 2017-0 00_04_36 20170320-110734-0](https://cloud.githubusercontent.com/assets/20301499/24087735/bb4642c2-0d5d-11e7-8199-3af7b1b33a48.jpg)
![bandicam 2017-0 00_04_29 20170320-110813-0](https://cloud.githubusercontent.com/assets/20301499/24087745/d64cdee6-0d5d-11e7-872f-0d7e9d4aa3c1.jpg)
Should be the same as the engine Sousei only get a black screen, but the frame is active
![qq20170320102103](https://cloud.githubusercontent.com/assets/20301499/24087786/44b6f0e2-0d5e-11e7-8834-235b0c942fd8.jpg)

**Comment by SakataGintokiYT** [comment]
@raven02 

KamenRider Battlide War 1/ 2

**OpenGL:**
```
E {rsx::thread} RSX: Failed to compile shader: 0(64) : error C1008: undefined variable "tex0"
0(64) : error C1008: undefined variable "tc0"
0(64) : error C1008: undefined variable "tex0_coord_scale"

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
-------------
0(64) : error C1008: undefined variable "tex0"
0(64) : error C1008: undefined variable "tc0"
0(64) : error C1008: undefined variable "tex0_coord_scale"
(0) : error C2003: incompatible options for link
'
```
**[Log:](https://mega.nz/#!cEIDFBgC!q9WVYkyzTrG0g6LdupQakkwX5AJEV-KY6Qw2nVH_4Bg)**

**Vulkan:**
```
E {rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:89: 'tex0' : undeclared identifier 
ERROR: 0:89: 'tc0' : undeclared identifier 
ERROR: 0:89: 'xy' : vector field selection out of range 
ERROR: 0:89: 'texture' : no matching overloaded function found 
ERROR: 0:89: 'a' : vector field selection out of range 
ERROR: 5 compilation errors.  No code generated.


E {rsx::thread} RSX: 
F {rsx::thread} class std::runtime_error thrown: Failed to compile fragment shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:472)
```
**[Log:](https://mega.nz/#!4RQxiISZ!sldAGgCEz9EgCxXUnXBsg1AmaL2_965C_hgjq6N1wEs)**

**Comment by digitaldude555** [comment]
You can do any move you want but when you fire the game that's when game freezes, it must be the gun.

**Comment by kd-11** [comment]
I know what causes this one. Easy to fix. Fix will be submitted soon.

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/2567

**Comment by RainKikyou** [comment]
Thanks, now fix it

**Comment by RainKikyou** [comment]
should be reopened，there is no complete fix，still a problem
crash here
https://youtu.be/om-5UQXa4Xc
savadata
https://cdn.discordapp.com/attachments/277227681836302338/298776271364554752/BLJS102200000kamenrider.zip
`E {rsx::thread} RSX: FBO check failed: 0x8cd6
E {rsx::thread} RSX: FBO check failed: 0x8cd6
F {PPU[0x100000f] Thread (runTaskMain) [0x003b8854]} MEM: Access violation reading location 0x41bac38e`
also problems same before
![qq 20170404194619](https://cloud.githubusercontent.com/assets/20301499/24655440/e209147e-1970-11e7-9b89-52d9650de483.jpg)

**Comment by kd-11** [comment]
Is the crash happening using current master?

**Comment by RainKikyou** [comment]
digital is the same as me

**Comment by digitaldude555** [comment]
I get the error that rain posted in code but not the error in screenshoot.

**Comment by kd-11** [comment]
Dont report hw scale errors here, you can notify me on discord. The access violation error is completely different and can happen even with null renderer.

**Comment by kd-11** [comment]
Dont report hw scale errors here, you can notify me on discord. The access violation error is completely different and can happen even with null renderer.

Edit: fyi if you really want to test hw scale get the newer builds from my appveyor. Hw scale v3 is a very old build.

**Comment by RainKikyou** [comment]
The screenshot was two weeks ago, when the fragment shader error was checked. I just used to compare with the current master build

**Comment by kd-11** [comment]
Please open a different issue. The access violation error does not originate from rsx::thread.
