### ISSUE TITLE
Wrong CPU type detection

### ISSUE THREAD

**Issue by oobol2000oo** [RPCS3/rpcs3#2565]
I have i5-6200U skylake but RPCS3 PPU Recompiler LLVM detect it as haswell

Using RPCS3 v0.0.2-3-2b79a36 Alpha

Game: BLUS31431

Spec:
Windows 10 Professional
i5-6200U @ 2.30Ghz
Nvidia 930M 2GB
RAM 8GB

Using PPU Recompiler LLVM and SPU Recompiler ASMJIT

Below is the log

[RPCS3-log.txt](https://github.com/RPCS3/rpcs3/files/853953/RPCS3-log.txt)

**Comment by clienthax** [comment]
Not a bug
Workaround for an existing issue in llvm

**Comment by kd-11** [comment]
This is intentional
