### ISSUE TITLE
The Punisher: No Mercy Demo [NPUB90198] 'cellFsUtime' generates Win32 error 87

### ISSUE THREAD

**Issue by darkredflame** [RPCS3/rpcs3#2566]
When running The Punisher Demo, it appears that 'cellFsUtime' gets aborted and it results in this error message. Window just stays on a black screen with a 0.00 fps counter. (I apologize if I'm wrong about the whole 'cellFsUtime' thing)

F {PPU[0x1000000] Thread (main_thread) [0x01ad32d8]} class std::runtime_error thrown: Unknown Win32 error: 87.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/855713/RPCS3.zip)

**Comment by scribam** [comment]
@darkredflame Would you mind trying this game again to check if the issue is still here?

**Comment by Megamouse** [comment]
just tried. yes it happens
