### ISSUE TITLE
Blood Drive [BLUS30602] fails to start due to a locking mutex error

### ISSUE THREAD

**Issue by darkredflame** [RPCS3/rpcs3#2570]
When I attempt to start Blood Drive on my computer, it gives me the following error message in the log.  The game does not load past the GSFrame window for me.

```
F {PPU[0x100001d] Thread (Streaming Read Thread) [0x00848628]} class std::runtime_error thrown: Locking failed (lwmutex=*0x201a91b0, owner=0xfffffffc)
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_lwcond_.cpp:258)
```

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/859771/RPCS3.zip)

**Comment by digitaldude555** [comment]
![screenshot 846](https://user-images.githubusercontent.com/26138653/30001945-da7f746c-90a5-11e7-95ab-e6f65277942d.png)

Not an issue anymore.

**Comment by scribam** [comment]
Thanks @digitaldude555 

@AniLeo Can you close this issue?
