### ISSUE TITLE
Dengeki Bunko: Fighting Climax Ignition [BLJM61322] sys_fs_opendir failed: path is a file

### ISSUE THREAD

**Issue by SearchingForName** [RPCS3/rpcs3#2571]
hello
i am new to rpcs3

when i try to open Dengeki Bunko: Fighting Climax the screen is black for few seconds then it closes itself

and i see lots of 
failed to open directory,failed to open file,path is a file.

[RPCS3.ZIP.docx](https://github.com/RPCS3/rpcs3/files/859886/RPCS3.ZIP.docx)
(remove .docx from the extension) for some reason it keeps saying that .zip is unsupported

**Comment by ikki84** [comment]
@SearchingForName Is this still an issue? 
At least the [NPJB00580] version can get ingame with some graphics issues.

**Comment by SearchingForName** [comment]
yes this is still an issue
but now the window in stable (doesn't automatically close) and there is active fps but the window is black

failed to open directory,failed to open file,path is a file still appears

sorry i made a mistake in the title

BLJM61322 is Fighting Climax Ignition

-----------
BLJM-61322    Dengeki Bunko: Fighting Climax Ignition
NPJB-00785    Dengeki Bunko: Fighting Climax Ignition

BLJM-61210   Dengeki Bunko: Fighting Climax
NPJB-00580   Dengeki Bunko: Fighting Climax

----------
According to the compatibility list 
'NPJB-00785' also can get ingame

**Comment by SearchingForName** [comment]
Never mind,
i was able to get 'BLJM61322' ingame by using 'Write Color Buffers'

in the beginning the game crashed a lot but i think it was a driver related issue

but
"failed to open directory , failed to open file & path is a file" still appears

**Comment by scribam** [comment]
Is it still an issue? Some improvements related to the file system have been made since April. Would you mind trying again with a recent build?

**Comment by Leance777** [comment]
the game is playable, but have very fast pace and some glitch on the screen, some text not showing up and the picture color is not right, sometime stuck at video opening except we skip it
by the way this game still not listed in compatibility list

**Comment by AniLeo** [comment]
The filesystem issue was fixed, closing as solved
