### ISSUE TITLE
missing libat3multidec.sprx

### ISSUE THREAD

**Issue by zerr10** [RPCS3/rpcs3#2577]
Game naruto ultimate ninja storm

F LDR: class std::runtime_error thrown: Failed to load /dev_flash/sys/external/libat3multidec.sprx: Invalid stream or file not found

bomberman ultra :
bug.
F {PPU[0x1000000] Thread (main_thread)} class std::out_of_range thrown: invalid unordered_map<K, T> key

**Comment by clienthax** [comment]
Did you follow the guide?, I don't think you followed the guide...

**Comment by clienthax** [comment]
No Log.

**Comment by zerr10** [comment]
log ?

**Comment by Talkashie** [comment]
Read the guide... doesn't look like you have firmware installed.

https://rpcs3.net/quickstart

**Comment by zerr10** [comment]
i  used auto libraeres

**Comment by darkredflame** [comment]
Please upload your RPCS3.log file

**Comment by Talkashie** [comment]
You still have to have firmware installed. Read the guide.

**Comment by zerr10** [comment]
firmware installed this need installed ?

**Comment by darkredflame** [comment]
Please follow the instructions in the quickstart guide step-by-step, it explains how to install the firmware.

[](https://rpcs3.net/quickstart)

**Comment by zerr10** [comment]
i installed this frimeware: 4.81 naruto work but DX12 i still get this error F {rsx::thread} class std::range_error thrown: bad conversion

in naruto + Now there is a black background in the menu ehm :)
bomberman still dont work in LLVM  , interpere too dont work
F {PPU[0x1000000] Thread (main_thread)} class std::out_of_range thrown: invalid unordered_map<K, T> key

**Comment by darkredflame** [comment]
Don't use LLVM with either Naruto or Bomberman Ultra, LLVM has a low compatibility rate.

**Comment by zerr10** [comment]
i dont can use this LLVM i get only black screen + only sound work D :) al time for naruto for burst limit..

**Comment by zerr10** [comment]
, LLVM, intepere bomberman dont work  befor working but now not

**Comment by darkredflame** [comment]
Try using OpenGL for the backend render instead of Vulkan.

**Comment by zerr10** [comment]
But opengl is weaker than vlucan.

**Comment by darkredflame** [comment]
Please wait for a build in the future to come out to improve compatibility with Vulkan then. 

There is no further help I can provide to you with your issue.

**Comment by zerr10** [comment]
LLVM in opengl too have black screen and only sound D :)

**Comment by darkredflame** [comment]
Please upload your RPCS3.log file as a .zip file to our forums for additional assistance in this matter.

[Forum link](http://www.emunewz.net/forum/showthread.php?tid=171465)

**Comment by twdarkeh** [comment]
Do not use LLVM. The game does not work with LLVM.  The emulator is still early in development, the game isn't just going to work out of the box.

**Comment by zerr10** [comment]
ye but in iterpere in game burst limit have only 5 fps for now befor is faster ehm :)
LLVM have 30-40 but is black screen only sound ehm :)

**Comment by darkredflame** [comment]
Yeah, that is to be expected, it's running at 30-40 fps because it is literally not rendering any graphics at all. LLVM does not work with Naruto or Bomberman at this time and we cannot support you any further in this matter regarding LLVM. **You need to use interpreter for now, there is no other solution.**

**Comment by zerr10** [comment]
thx maybe future :)
xenia support rendering amd D finally :)

**Comment by hcorion** [comment]
Issue can be closed. Issue was no firmware installed.

**Comment by AniLeo** [comment]
Please use the forums for support and don't report stuff before properly following our quickstart guide.
