### ISSUE TITLE
Madden NFL 17 - Game stays black

### ISSUE THREAD

**Issue by panek12** [RPCS3/rpcs3#2579]
Hi, pretty new with the emulator but was curious to try it with Madden 17. I apologize for not having a better Issue title, because I'm not really sure what to make of this (yet :) ). I installed the firmware 4.81.
All settings are set to the default, OpenGL/Vulkan/DX12 make no difference.
When I hit "Boot Game", a window opens but it stays black. 

Host: Windows 10 64-Bit, CPU: AMD Ryzen 7 1700, GPU: AMD Radeon HD 7950, 16GB RAM.
Used version: RPCS3 v0.0.2-3-3bfe17a Alpha
All the game-generated logs are available in this zip: [logs.zip](https://github.com/RPCS3/rpcs3/files/866756/logs.zip)

Last displayed log message:
F {rsx::thread} class std::runtime_error thrown: Invalid RSX method 0xdf4 (arg=0x0)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:34)

**Comment by AniLeo** [comment]
Please report game statuses on the forums instead
I've added the rsx_method report on #2359 along with the others
