### ISSUE TITLE
DragonBall z burst limit poor framerate

### ISSUE THREAD

**Issue by HawkSoft3** [RPCS3/rpcs3#2580]
When in the game menu 60 fps is consistent but after entering into the gameplay it drops to 6-10fps can u please fix this

**Comment by darkredflame** [comment]
Please post your issue along with a copy of your RPCS3.log file as a .zip on the support forum.

http://www.emunewz.net/forum/forumdisplay.php?fid=163

**Comment by hcorion** [comment]
This issue should be closed. Please use the forum for support. It's impossible to tell what the problem is from the report, and a game is slow but report doesn't help the developers.
