### ISSUE TITLE
DX12: Super Street Fighter 2 Turbo HD - crashes at startup

### ISSUE THREAD

**Issue by wingsoftheraven** [RPCS3/rpcs3#2583]
I can play the game if I use OpenGL but yesterday I've heard if you choose d3d12 while playing Super Street Fighter 2 Turbo on windows 10  you can have full 60 fps and I wanted to test it but whenever I choose d3d12 it gives me fatal error before the game starts 
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000000 at 0000000000404c73.
Instruction address: 0000000000404c73.
Function address: 0000000000404ae0 (base+0x3f4ae0).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

PC Specs:

GTX 970 
I5 4460 
8 GB RAM

log file https://ufile.io/03a0e

I have the latest drivers for gpu.

**Comment by raven02** [comment]
Confirmed DX12 crash but GL and Vulkan works well
