### ISSUE TITLE
Unhandled Win32 exception 0xC000001D.

### ISSUE THREAD

**Issue by Mohamed28** [RPCS3/rpcs3#2584]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC000001D.
Exception address: 00000000000fe9ea.
Instruction address: 00000000000fe9ea.
Function address: 00000000000fe9c0 (base+0xee9c0).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

Illegal instruction exception occured.
Note that your CPU must support SSSE3 extension.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

Hi guys, this error happens when I try to install a pkg.

I'm using an AMD Phenom II X4  810, 2.6GHz / Nvidia GTX 1050TI  / 4GB DDR3.

I don't know what is wrong, my processor is x64 and supports SSE3.

**Comment by AniLeo** [comment]
Your CPU doesn't support **SSSE3**. 
RPCS3 requires SSSE3 to operate.

**Comment by danielsur63** [comment]
Hello, I have a Pentium dual core E5700 that supports SSSE3, and still got a similar error when I use RPCS3 with recompiler (LLVM) option in PPU decoder - No problem when I use it with Interpreter.
I know my PC is not very fast but I can play some games at 10 to 30 fps. I would like to use recompiler as it is said to be faster than interpreter, but I got the mentioned error ( Unhandled Win32 exception 0xC000001D ), but with different addresses from the example of this topic. I attach a picture of the error message. I am using the last build available 0.3.3-3 Alpha .
![unhandled win32 exception 0xc000001d](https://user-images.githubusercontent.com/33678757/32818909-fa850168-c9a4-11e7-9e89-b4e8461a9742.jpg)

**Comment by danielsur63** [comment]
What could be the reason for getting such error ? My PC supports SSSE3.
