### ISSUE TITLE
Failing to compile at Linux Debian 8 jessie

### ISSUE THREAD

**Issue by MorrowxD** [RPCS3/rpcs3#2585]
Hello i want to compile rpcs3 on debian 8 jessie and i have a problem when i try to compile `cmake CMakeLists.txt && make GitVersion && make ` cmake says RPCS3 requires at least gcc-5.1. I can't install gcc-5.1 on jessie because of Unfulfilled dependencies so i installed clang 3.5 but cmake still wants from me gcc-5.1. Any solution? //Sorry for my English

**Comment by Areiser** [comment]
The problem is that debian has an ancient gcc version, you can override it like this provided that clang is installed in /usr/bin/:
cmake CMakeLists.txt -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
After that you still need to run the following to complete the build:
make GitVersion && make

I'm sure you can permanently change the cmake settings but I don't know how.

**Comment by MorrowxD** [comment]
Ok it wokrs but now i have some errors
```
7 warnings and 3 errors generated.
rpcs3/CMakeFiles/rpcs3.dir/build.make:503: Commands for the object
 'rpcs3/CMakeFiles/rpcs3.dir/rpcs3.cpp.o' They failed
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/rpcs3.cpp.o] Error 1
CMakeFiles/Makefile2:277: polecenia dla obiektu 'rpcs3/CMakeFiles/rpcs3.dir/all' They failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Błąd 2
Makefile:117: Commands for the object 'all' They fialed
make: *** [all] Error 2
```

**Comment by hcorion** [comment]
@MorrowxD 
Ok, first make sure you've updated the submodules using the command:
```shell
git submodules update --init --recursive
```
Use the following for cmake: 
You'll need to make a folder, maybe call it build, and then cd to it. Then run the following command.
```shell
cmake ../ -G "Unix Makefiles" -DUSE_SYSTEM_LIBPNG=ON -DUSE_SYSTEM_FFMPEG=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS='-ldl -lyaml-cpp' -DCMAKE_SKIP_RPATH='ON' -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
```

**Comment by fagoatse** [comment]
@MorrowxD Compiling a cutting edge software in an ancient distro doesn't seem like a good idea tbh. I recommend Arch, Solus or *buntu(non-LTS) for cutting-edge software such as rpcs3. These will work out-of-box.

**Comment by thecityofguanyu** [comment]
@MorrowxD If you're married to Debian (like I am) and want to use more bleeding edge software, then you should probably consider upgrading to Sid/Unstable or Stretch/Testing. It compiles fine for me in Sid.

**Comment by mdeguzis** [comment]
This does not build in clang from all tests that I tried

Reference packaging (see debian/rules): https://github.com/mdeguzis/LibreGeek-Packaging/tree/steamos/rpcs3/debian

**Comment by hcorion** [comment]
@mdeguzis 3.8 is pretty old at this point. Try building use clang/llvm 4.0.

Instructions for installing: 
```shell
wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
sudo apt-get install software-properties-common
sudo apt-add-repository "deb http://apt.llvm.org/unstable/ llvm-toolchain-4.0 main"
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install clang-4.0 lldb-4.0 lld-4.0
```

**Comment by mdeguzis** [comment]
I tried before with llvm 4.0 when I ported 3.8. I'll try your instructions again, thank you

**Comment by mdeguzis** [comment]
I think it was the same with system png off. I'll attach a build log for the current build config:
```
			-DCMAKE_EXE_LINKER_FLAGS='-ldl -lyaml-cpp' \
			-DCMAKE_BUILD_TYPE='Release' \
			-DCMAKE_CXX_COMPILER=clang++-3.8 \
			-DCMAKE_C_COMPILER=clang-3.8 \
			-DUSE_SYSTEM_LIBPNG='OFF' \
			-DUSE_SYSTEM_FFMPEG='OFF' \
			-DCMAKE_INSTALL_PREFIX=/usr ..
```

**Comment by mdeguzis** [comment]
system png: http://sprunge.us/GQUh
system png OFF: http://sprunge.us/hZFA

**Comment by hcorion** [comment]
@mdeguzis Ok, I did some research, it looks like system png OFF is the way to go, however debian 8's libglew-dev is horribly outdated, and that is why you got the errors you did.

I'm not sure how (I use Arch Linux) but you'll have to update libglew-dev from 1.10.0 to 2.0 (the updated version is in debian 9, if that helps)

**Comment by mdeguzis** [comment]
Sweet, if that works, much easier than banging my head on the wall trying to backport gcc again :) Here goes!

**Comment by mdeguzis** [comment]
Got a tab bit farther this time, 62%.  Backported libglew-dev from [Stretch](https://packages.debian.org/stretch/libglew-dev).
```
root@archboxmtd:/build/rpcs3-0.0.2+20170418git+bsos# apt-cache policy libglew-dev
libglew-dev:
  Installed: 2.0.0-3~bsos+1
```

Log: http://sprunge.us/CSDd

**Comment by TotalCaesar659** [comment]
Debian 9 released, you can check it
https://www.debian.org/News/2017/20170617

**Comment by mdeguzis** [comment]
I build for SteamOS which is on Debian 8 until they rebase. I'll just have to be patient I suppose.

**Comment by hcorion** [comment]
Please close this, issue has to do with the outdated build system used and no response was given.
