### ISSUE TITLE
Vulkan/GL: Gundam Musou 3 - rendering issues

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2596]
vullkan same with OpenGL
![qq 20170326124542](https://cloud.githubusercontent.com/assets/20301499/24328690/996d34c0-1222-11e7-8d0f-9824373b6094.jpg)
![qq 20170326092441](https://cloud.githubusercontent.com/assets/20301499/24328693/a65103b0-1222-11e7-9b5a-fedb7128cab6.jpg)
dx12
`{rsx::thread} class std::range_error thrown: bad conversion`
rdc：https://mega.nz/#!UEoFhBBS!fOQxkRmh0_ZtA72p6G4h6Wmd6PxqK8W5-dtLwoouEmU

**Comment by kd-11** [comment]
Still an issue?

**Comment by scribam** [comment]
I think this issue can be closed. The game seems to run fine according to this recent video: https://www.youtube.com/watch?v=LuoB9QWX1B8.

Note from Wikipedia:
>Dynasty Warriors: Gundam 3, known in Japan as Gundam Musou 3

**Comment by AngeloNox** [comment]
its still a issues at least for me it is
