### ISSUE TITLE
Rending issues while playing Demon's Souls

### ISSUE THREAD

**Issue by mjfalkenstein** [RPCS3/rpcs3#2598]
I'm able to get the game up and running and can navigate the menus without issue. However, after creating a new character and trying to enter the game, I get this screen:

https://gyazo.com/8cd35b95d8490fdad1ceba2a2b0a2666

I can hear myself walking around, and when I attack my stamina bar goes down as you'd expect, but none of the world besides the UI will render. The screen is also black during the cut scenes, besides the subtitles. Here is a screenshot of my graphics settings for reference:

https://gyazo.com/d30f1763496c0465ef1723fd44f650bd

Any ideas?

**Comment by raven02** [comment]
Thanks @AniLeo . I then close it as write color buffer should solve the issue.
