### ISSUE TITLE
Way of the Samurai 4

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2602]
i don't what to this problem say

**DX12:**
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/873246/RPCS3.zip)

Show Error

**OpenGL:**
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/873249/RPCS3.zip)
![2](https://cloud.githubusercontent.com/assets/25039098/24369094/25530c4c-1338-11e7-99ee-96ebb4cfaab4.jpg)
![3](https://cloud.githubusercontent.com/assets/25039098/24369097/291d9766-1338-11e7-910d-57c4d1d4d52d.jpg)

vulkan:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/873251/RPCS3.zip)
![22](https://cloud.githubusercontent.com/assets/25039098/24369107/2f5aacd6-1338-11e7-9b21-8a02d97933d0.jpg)
![33](https://cloud.githubusercontent.com/assets/25039098/24369120/3778934c-1338-11e7-9ded-450eeb5fa8fb.jpg)

**Comment by scribam** [comment]
@aakh1361 Can you try again with a recent build to see if this is still an issue?

**Comment by aakh1361** [comment]
sorry i miss this game :-(

**Comment by digitaldude555** [comment]
![screenshot 2159](https://user-images.githubusercontent.com/26138653/53329398-aac93700-38f4-11e9-9a9c-a51be0b36e5c.png)
![screenshot 2160](https://user-images.githubusercontent.com/26138653/53329399-aac93700-38f4-11e9-8e32-1e3db8686046.png)
Fixed in OpenGL and Vulkan. Close the Issue.

**Comment by kd-11** [comment]
Closing as fixed.
