### ISSUE TITLE
Wolfenstein (Demo) UI rendering

### ISSUE THREAD

**Issue by jjsat** [RPCS3/rpcs3#2603]
As briefly discussed here #2597 the game Wolfenstein (also the demo) draws its UI with calls to ARRAY_ELEMENT16 between begin/end. This gives indices into a previously defined vertex buffer.

Here are relevant calls from a 

> log:
...
·! 0:00:58.668973 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT(0x5d0) = 0x2
·! 0:00:58.668976 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET(0x5a0) = 0x0
·! 0:00:58.668978 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 4(0x5d1) = 0x2
·! 0:00:58.668980 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 4(0x5a1) = 0x0
·! 0:00:58.668983 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 8(0x5d2) = 0x2
·! 0:00:58.668987 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 8(0x5a2) = 0x0
·! 0:00:58.668989 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 12(0x5d3) = 0x2
·! 0:00:58.668992 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 12(0x5a3) = 0x0
·! 0:00:58.668995 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 16(0x5d4) = 0x2
·! 0:00:58.668997 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 16(0x5a4) = 0x0
·! 0:00:58.668999 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 20(0x5d5) = 0x2
·! 0:00:58.669002 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 20(0x5a5) = 0x0
·! 0:00:58.669004 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 24(0x5d6) = 0x2
·! 0:00:58.669006 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 24(0x5a6) = 0x0
·! 0:00:58.669009 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 28(0x5d7) = 0x2
·! 0:00:58.669011 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 28(0x5a7) = 0x0
·! 0:00:58.669013 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 32(0x5d8) = 0x2
·! 0:00:58.669015 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 32(0x5a8) = 0x0
·! 0:00:58.669017 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 36(0x5d9) = 0x2
·! 0:00:58.669020 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 36(0x5a9) = 0x0
·! 0:00:58.669022 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 40(0x5da) = 0x2
·! 0:00:58.669024 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 40(0x5aa) = 0x0
·! 0:00:58.669026 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 44(0x5db) = 0x2
·! 0:00:58.669029 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 44(0x5ab) = 0x0
·! 0:00:58.669031 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 48(0x5dc) = 0x2
·! 0:00:58.669033 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 48(0x5ac) = 0x0
·! 0:00:58.669035 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 52(0x5dd) = 0x2
·! 0:00:58.669037 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 52(0x5ad) = 0x0
·! 0:00:58.669040 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 56(0x5de) = 0x2
·! 0:00:58.669042 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 56(0x5ae) = 0x0
·! 0:00:58.669044 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT + 60(0x5df) = 0x2
·! 0:00:58.669046 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET + 60(0x5af) = 0x0
...
·! 0:00:58.669286 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_ATTRIB_INPUT_MASK(0x7fc) = 0xb
·! 0:00:58.669288 {rsx::thread} RSX: CELL_GCM_NV4097_SET_TRANSFORM_TIMEOUT(0x7be) = 0x20ffff
·! 0:00:58.669291 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_FORMAT(0x5d0) = 0x425
·! 0:00:58.669293 {rsx::thread} RSX: CELL_GCM_NV4097_SET_VERTEX_DATA_ARRAY_OFFSET(0x5a0) = 0x801e0240
·! 0:00:58.669295 {rsx::thread} RSX: CELL_GCM_NV4097_INVALIDATE_VERTEX_CACHE_FILE(0x5c4) = 0x0
·! 0:00:58.669298 {rsx::thread} RSX: CELL_GCM_NV4097_INVALIDATE_VERTEX_FILE(0x5c5) = 0x0
·! 0:00:58.669300 {rsx::thread} RSX: CELL_GCM_NV4097_INVALIDATE_VERTEX_FILE(0x5c5) = 0x0
·! 0:00:58.669303 {rsx::thread} RSX: CELL_GCM_NV4097_INVALIDATE_VERTEX_FILE(0x5c5) = 0x0
·! 0:00:58.669306 {rsx::thread} RSX: CELL_GCM_NV4097_INVALIDATE_L2(0x7f6) = 0x1
·! 0:00:58.669308 {rsx::thread} RSX: CELL_GCM_NV4097_INVALIDATE_VERTEX_FILE(0x5c5) = 0x0
·! 0:00:58.669310 {rsx::thread} RSX: CELL_GCM_NV4097_INVALIDATE_VERTEX_FILE(0x5c5) = 0x0
·! 0:00:58.669313 {rsx::thread} RSX: CELL_GCM_NV4097_INVALIDATE_VERTEX_FILE(0x5c5) = 0x0
·! 0:00:58.669315 {rsx::thread} RSX: CELL_GCM_NV4097_SET_BEGIN_END(0x602) = 0x5
·! 0:00:58.669326 {rsx::thread} RSX: CELL_GCM_NV4097_ARRAY_ELEMENT16(0x603) = 0x2
·! 0:00:58.669329 {rsx::thread} RSX: CELL_GCM_NV4097_ARRAY_ELEMENT16(0x603) = 0x30001
·! 0:00:58.669332 {rsx::thread} RSX: CELL_GCM_NV4097_ARRAY_ELEMENT16(0x603) = 0x10002
·! 0:00:58.669334 {rsx::thread} RSX: CELL_GCM_NV4097_SET_BEGIN_END(0x602) = 0x0

The game does not boot further than the first loading screen with the current emulator version, so I have pushed the workarounds here: [https://github.com/jjsat/rpcs3/tree/wolf](https://github.com/jjsat/rpcs3/tree/wolf)

Issues addressed are:
(1) Increased TLS memory area
(2) Issues with compressed textures that have small height (Wolfenstein uses a 512x2 DXT5 texture), which fails to upload and has a calculated mipmap count of 0
(3) The drawing command mentioned above

The first loading screen hangs most likely due to a race condition between threads. This depends on the build settings (a release build has a chance of working, a debug build always hangs). If this line appears in the log the game has hung:

> E {PPU[0x1000000] Thread (main_thread) [0x00879814]} 'sys_event_queue_destroy' failed with 0x80010005 : CELL_ESRCH

![clipboard01](https://cloud.githubusercontent.com/assets/1445782/24369322/ed1142cc-1323-11e7-8fcf-1f9ad13acc93.png)

The game has some drawing issues on the main screen (missing effects), but actually goes ingame. Funnily enough there seems to be something seriously going wrong with the physics so that every object is immediately destroyed (look at the barrel to the right, also the blurry stuff is a smoke effect).

![clipboard04](https://cloud.githubusercontent.com/assets/1445782/24369345/fa5843cc-1323-11e7-9413-81e6cfd0d68e.png)

The game crashes a couple of frames after this.

**Comment by kd-11** [comment]
The indexed render path via  immediate push buffers is a priority and should land in the next few days together with the texture alignment fixes. I'll consult on the TLS issue as well.

**Comment by kd-11** [comment]
Fixed via https://github.com/RPCS3/rpcs3/pull/2606
