### ISSUE TITLE
MMJoystick: wrong mapping of O and X in Catherine for DS4

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#2604]
The title says it all: in the game O and X are switched for my DS4 (i.e. I need to press O, for X action and vice-versa), even though it EU copy of the game and the system lang in English in the settings.
Haven't yet tested with other games.

**Comment by AniLeo** [comment]
That's known, default config is made for DS3, you need a custom configuration file https://github.com/RPCS3/rpcs3/files/778233/config_dualshock4.zip

**Comment by InfamousKing13** [comment]
how do u use the custom config?

**Comment by twdarkeh** [comment]
At this point, it would be easier to simply wait for the DS4 support to be merged.

**Comment by AniLeo** [comment]
DS4 native support was implemented. You can also change mapping on MMJoystick, so this shouldn't be an issue anymore.
