### ISSUE TITLE
Feature request: making progressbar for task button

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#2605]
Hello! Could you make a progressbar for task button when installing a game/firmware? It would be comfortable not to switch to the main RPCS3 window to check the installation progress.
Windows 7-10:
![issue](https://cloud.githubusercontent.com/assets/14265316/24409963/6d79a86c-13da-11e7-8892-5b0a4908ac71.png)
![issue2](https://cloud.githubusercontent.com/assets/14265316/24409970/75bd2666-13da-11e7-9cef-4dc8514bb6f7.png)
Ubuntu:
![ubuntu](https://cloud.githubusercontent.com/assets/14265316/24409982/81111c2a-13da-11e7-84ab-fef584b96919.png)

**Comment by Megamouse** [comment]
since we will be using Qt, maybe this would help:
http://stackoverflow.com/questions/4349502/how-to-show-progress-in-windows-7-taskbar-using-qt

**Comment by Megamouse** [comment]
I implemented the Windows version for install firmware and install pkg in the upcoming Qt PR.
I'll try to do the same for the ingame progressbar, but this needs to have the dialogs working first (in Qt) and then there is the question which of the progressbars to track. I guess the first one?

**Comment by Megamouse** [comment]
Update for Windows: I managed to add the taskicon Progressbar for the messagedialog, too.
I hope it tracks the right progressbar when two bars are shown as seen in the second screenshot above.

Here is the Testbuild:
https://www.dropbox.com/s/9p2260gl3o1hnva/rpcsqt4.zip?dl=0

possible Bugs to look out for:
- progress not shown
- progress remains on dialog exit
- progress remains after dialog is closed after finished install/compile

**Comment by Megamouse** [comment]
@AniLeo this should be linux only now #tagLinux

**Comment by hcorion** [comment]
@Megamouse There are some Linux implementation details here: https://stackoverflow.com/a/43919667/4268405
