### ISSUE TITLE
far cry 2[NPUB30523] {PPU[0x1000019] Thread (GameFileLoadThread) [0x00674f34]} MEM: Access violation reading location 0x0

### ISSUE THREAD

**Issue by woody2014** [RPCS3/rpcs3#2609]
Nearl in game but this error at menu F {PPU[0x1000019] Thread (GameFileLoadThread) [0x00674f34]} MEM: Access violation reading location 0x0

**Comment by darkredflame** [comment]
The Access violation reading location 0x0 is a known error, there are many games that give out this error right now. It will be fixed when it gets fixed.

**Comment by AniLeo** [comment]
Actually it is a general error that happens for a lot of different reasons. A log is needed to check what happened before because that doesn't tell much without further testing. 
Use the big issue for access violations unless you know specifically what's the issue there.

**Comment by raven02** [comment]
Im closing this one since it is common general error.
