### ISSUE TITLE
Vulkan: Artifacting issues occurring on AMD cards

### ISSUE THREAD

**Issue by darkredflame** [RPCS3/rpcs3#2610]
Feel free to tell me to merge this comment with #2201 if you feel it is more appropriate there. The main reason I am submitting this as a separate issue is that i'm using GCN2 hardware (R9 280X). I have also confirmed that this happens to Dangles too in the RPCS3 discord, he has a R9 390X. 
I would like to mention that I have checked on Discord with other users that have multiple different generations of Nvidia cards, and none of them have this artifacting issue.

From what I can tell, these artifacts appear to be (in Persona 5's case) previous frames that were not overwritten and contains traces/shadows from those previous frames. Sorry if my explanation of this issue is poor, I am submitting some screenshots before for a better idea. 
If you would like me to include log files too, just let me know.

**==Persona 5==

OGL**
![rpcs3imejp_2017-03-27_17-44-37](https://cloud.githubusercontent.com/assets/12888227/24429321/c812c378-13ce-11e7-9eba-f55b1d235361.png)

**Vulkan**
![rpcs3_2017-03-26_19-57-34](https://cloud.githubusercontent.com/assets/12888227/24429320/c8124646-13ce-11e7-9b1a-f12a2d167bba.png)

**==NieR Replicant==

OGL**
![rpcs3_2017-03-28_15-38-25](https://cloud.githubusercontent.com/assets/12888227/24429347/e47ca3a8-13ce-11e7-8d5d-ebc5bc697982.png)
![rpcs3_2017-03-28_15-42-10](https://cloud.githubusercontent.com/assets/12888227/24429358/f2bfb310-13ce-11e7-8dce-683e11cb21e4.png)

**Vulkan**
![rpcs3_2017-03-28_15-42-36](https://cloud.githubusercontent.com/assets/12888227/24429393/134c14de-13cf-11e7-8464-c7377a5ec231.png)
![rpcs3_2017-03-28_15-42-13](https://cloud.githubusercontent.com/assets/12888227/24429394/134d17da-13cf-11e7-9537-cf5314ad64c2.png)

**Comment by kd-11** [comment]
Some of these are just bugs in the rpcs3 vulkan implementation; I've seen similar in afterburner climax and demon's souls.

**Comment by darkredflame** [comment]
@kd-11 Any known reason why it only seems to affect AMD cards? Is it just a matter of AMD's driver not playing nice with how RPCS3 has the Vulkan backend implemented?

**Comment by danilaml** [comment]
Btw, not sure if it's related but I have this weird annoying fuzzy text/border lines/textures in Catherine (and some other games) with Vulkan:
![image](https://cloud.githubusercontent.com/assets/2046350/24433713/25de710a-1433-11e7-96d5-6141db188283.png)

Sometimes it looks like messed up DoF/Fog/Blue effect (or maybe it's just a weird AA, I dunno).
OpenGL looks fine:

![image](https://cloud.githubusercontent.com/assets/2046350/24433740/686b97dc-1433-11e7-831b-543a5afe763e.png)
But it seems to be missing blue/DoF effect on falling sheep at the begining.
Btw, D3D seems to have the most correct looking result out of three:
![image](https://cloud.githubusercontent.com/assets/2046350/24433785/c6904c7c-1433-11e7-82d9-161b2c2d4156.png)
(just look at Katherine at the background and smooth shading in general).

**Comment by hrydgard** [comment]
This kind of thing on AMD cards is typical of not getting Vulkan barriers/layout transitions right. AMD uses multiple layouts for performance (such as ones that optimize single-color values) while nVidia just doesn't care.

**Comment by kd-11** [comment]
Its a known issue, we've had discussions with AMD driver team on this.
A bug relating to broken transitions has been fixed today though, so number of issues should at least go down.

**Comment by danilaml** [comment]
@kd-11 seems like the issue I had with Catherine in Vulkan is now fixed. It looks almost like D3D12 now (vulkan and oGLL are still a tad bit brighter. Not sure what renderer is closer to the "truth"):
![image](https://cloud.githubusercontent.com/assets/2046350/24708717/66810fd6-1a20-11e7-99fe-ad0a3b5cc10a.png)
![image](https://cloud.githubusercontent.com/assets/2046350/24708844/c41aacec-1a20-11e7-8df8-ec98d2ec8063.png)

After Burner Climax looks good too now:

![image](https://cloud.githubusercontent.com/assets/2046350/24708936/08049b20-1a21-11e7-89d2-182946ab9cb9.png)
![image](https://cloud.githubusercontent.com/assets/2046350/24708969/2670fa2c-1a21-11e7-8e66-3a8ca30c81b7.png)


@darkredflame What about you? Please test and close this issue if it's fixed.

**Comment by kd-11** [comment]
The particular issue reported in this case was fixed when layout transitions were re-enabled. The other issues remaining are tracked separately.
