### ISSUE TITLE
gcm_test_cube not rendering anything

### ISSUE THREAD

**Issue by AkagiShiroe** [RPCS3/rpcs3#2615]
im using : rpcs3-v0.0.2-2017-03-30-c4066b92_win64
my spec are : Intel Core I3 530 3,0ghz
                     Ram 8GB (4gb 2x)
                     Nvidia Geforce 9600 GT Digital Alliance (512MB Vram)
[LOG.TXT](https://github.com/RPCS3/rpcs3/files/883284/LOG.TXT)

**Comment by raven02** [comment]
Tested with 3 backends and it looks okay

**Comment by SakataGintokiYT** [comment]
@AkagiShiroe 
Your graphics card doesn't support OpenGL 4.3 / 4.5

**Comment by AniLeo** [comment]
You're using an Unsupported GPU. Please check system requirements on our Website.

**Comment by AkagiShiroe** [comment]
im using the latest version available for it, 342.01. and thanks for the reply a few minute ago i try PS3Doom and its rendered correctly, are 3.3 aren't supported anymore?.

**Comment by darkredflame** [comment]
OpenGL 3.3 was never supported for RPCS3.

**Comment by AkagiShiroe** [comment]
^sorry im the dumb one here, time to upgrade hardware then... its 8 year+ old too LOL like a miracle this card still running

**Comment by AniLeo** [comment]
You can get cheap and relatively good GPUs for around 100 bucks nowadays. Check out RX460 and GTX1050. You can even get something for a lower price but good price performance starts there. It will be good for other games as well, as you're probably suffering hard from gpu bottleneck in all games you play.

**Comment by AkagiShiroe** [comment]
^yeah alot since most game out now are DX11/OGL 4.0 + things. and this 512 vram is milking out my fps. its nice to see a same price VGA with this 9600 GT are equal 2 or 3 more of it.
