### ISSUE TITLE
Naruto Ultimate Ninja Storm Black Screens and Issues

### ISSUE THREAD

**Issue by Einar0012** [RPCS3/rpcs3#2618]
Hi guys I´m new with this emulator and I reallly wanted to play this game, but when I put the settings in D3D12 and run the game, it doesn´t load the main menu screen neither the background of multiplayer´s menu. When I start a battle the game just freezes and stays here. Direct X 12 is the fastest render for me. Is there anything I can do? I have an NVIDIA GeForce 930MX. and a really good core. Please Help!
![prob](https://cloud.githubusercontent.com/assets/26827285/24572033/0d410af4-163b-11e7-9411-18285f341bdd.png)
![prob 2](https://cloud.githubusercontent.com/assets/26827285/24572037/1255216a-163b-11e7-90bb-c6604d483cca.png)
![prob 3](https://cloud.githubusercontent.com/assets/26827285/24572040/1576ab48-163b-11e7-9864-3ddd3c67355d.png)

**Comment by raven02** [comment]
Please check out our forum for more detail on this game.
