### ISSUE TITLE
PPU/GL : Catherine audio cutoff 

### ISSUE THREAD

**Issue by Gncd** [RPCS3/rpcs3#2619]
When using OpenGL game gets stuck after selecting a new game and audio is cut off, using null results in the same issue
```
E {PPU[0x1000011] Thread (_cellsurMixerMain) [0x00acfef8]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM
```

While using DX12 the games audio works fine until you get into the first level, after which it dies out again, even though the game runs and does not stop working until you finish the level and get the trophy, which causes a black screen, but the fps counter keeps changing.
```
E {PPU[0x1000011] Thread (_cellsurMixerMain) [0x0044a1a0]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM

E {PPU[0x1000045] Thread (Unlock Thread) [0x000e9930]} sceNpTrophy: sceNpTrophyUnlockTrophy(context=0x1, handle=0x1, trophyId=1, platinumId=*0xd008fdf0)

```
I'm using AMD fury with 1800x

**Comment by raven02** [comment]
SPU or PPU recompiler that you are referring to ?

**Comment by Gncd** [comment]
Im using both of them
Is this not ideal?

**Comment by raulpetru** [comment]
Yeah, I have lots of sys_mutex_unlock or sys_mutex_lock errors that mess up the gameplay.
When that error occurs, first the sound stops then if I'm in a level (in tower) at the end of the level the game doesn't load the next screen (the menu or whatever should be next) the screen just goes black.
If I'm in the menu when the error occurs, the sound stops and if I select to enter the game, nothing happens.

Sometimes these errors occurs after the ATLUS logo.

I couldn't pass the first tutorial level due these errors.

**Comment by raven02** [comment]
I retest using latest build . Looks like GL did render lots of issues . Vulkan and DX12 are both running fine at least for 1st chapter

> character wireframe
> audio cut off and stuck after new game when using PPU LLVM

**Comment by Gncd** [comment]
My game still has problems with audio, even with vulkan or dx12. 
Once the 'sys_mutex_unlock' error appears in the log, theres no way to complete the level.
(The performance has degraded slightly compared to old build?)
Am I running the latest build? (RPCS3 v0.0.2-3-ac79654 Alpha) 
(I was not able compile from the source code.)
https://pastebin.com/F3U8AeGi

**Comment by AniLeo** [comment]
Log file is rpcs3.log, that's console output

**Comment by Gncd** [comment]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/909504/RPCS3.zip)
Also once the audio died out at the end of the level, the performance rose from 10 fps to around 20.

**Comment by raven02** [comment]
@Gncd  and @raulpetru 

Please test out this version to see if you still hit the same issue . for example , stuck , audio cut off etc.

https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-4057/artifacts

**Comment by Gncd** [comment]
Audio does not seem to be rattling/popping anymore on this build. 
And i was not able to make the game freeze.

(Was able to only launch the game at playble perfomance using vulkan though,
nor did my xinput work)

**Comment by raulpetru** [comment]
@raven02 I can only test it in few days. I will come back with a reply when I get the chance to test it.

**Comment by raven02** [comment]
This is the build before reservation rewritten https://github.com/RPCS3/rpcs3/pull/2404 that i also got audio cutoff on other games .

**Comment by raulpetru** [comment]
@raven02 Using the build provided by you I get the game stuck after the ATLUS logo with a mutex lock error. I'm using PPU LLVM and SPU fast.
Here's the log: https://www.dropbox.com/s/ki8xy449j506jrt/RPCS3.log?dl=0

If I'm using recompilers for both PPU and SPU I get an access violation error.
Here's the log: https://www.dropbox.com/s/zrijzk9f8p3gepo/RPCS3%20other%20log.log?dl=0

**Comment by raven02** [comment]
Tested with latest build . The stuck at title screen issue seems to be fixed  .

**Comment by raven02** [comment]
For audio cut off , it is related to LLVM and i will consolidate into the LLVM issue thread.
