### ISSUE TITLE
[Question] how playable is Modnation Racers?

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [RPCS3/rpcs3#2620]
Cant find any information on the compatibility page on the website, and nothing here on GitHub, too. Cannot test myself right now, my hardware is far from meeting the minimum requirements.

**Comment by Zangetsu38** [comment]
normal, just show nothing

**Comment by SmokeyTheBandicoot** [comment]
Alright, thank you!

**Comment by raven02** [comment]
Please discuss in forum . Closed
