### ISSUE TITLE
Mac OSX Build Error

### ISSUE THREAD

**Issue by kokowang** [RPCS3/rpcs3#2627]
`/Users/Admin/rpcs3/rpcs3/../rpcs3/Emu/Cell/PPUAnalyser.h:41:14: error: implicit
      instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
        std::string name;
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:188:33: note: 
      template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
`
Attempted with 
xCode Version: 6.4 & 8.3
Command line tools version: 6.4 & 8.3
OS: MacOS Sierra 10.12.2
Building "Release" with LLVM
LLVM Version: 4.0.0
Cmake version: 3.7.1 & 3.7.2

**Comment by clienthax** [comment]
OSX is not supported due to not meeting the minimum graphic backend specs..

**Comment by christ776** [comment]
Sadly Apple has gone the wrong path with Metal.

**Comment by kokowang** [comment]
Wait, so OpenGL won't even run on it?

**Comment by christ776** [comment]
macOS support for OpenGL has been left behind. In other words, OpenGL 4.3 is not fully supported by any version of macOS, not even Sierra.

**Comment by kokowang** [comment]
I see.
