### ISSUE TITLE
GCM_SET_DRIVER_OBJECT exceeds methods array dimensions

### ISSUE THREAD

**Issue by Overv** [RPCS3/rpcs3#2628]
The definition of `GCM_SET_DRIVER_OBJECT` is set to `229376`, but it is used as an index for the `methods` array here:

https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/rsx_methods.cpp#L1278

The methods array is only `65536` elements in size, so it triggers an indexing exception.

**Comment by kd-11** [comment]
That was a typo; will be fixed ASAP. Thanks.

**Comment by AniLeo** [comment]
Closing since it was fixed
