### ISSUE TITLE
Ryu ga Gotoku Zero: Chikai no Basho(BLAS50796) , Gray screen

### ISSUE THREAD

**Issue by okt04175** [RPCS3/rpcs3#2635]
Gray screen

Log：
E LDR: Unknown module 'cellLibprof'
E LDR: Unknown function '0x05893E7C' in module 'cellLibprof'
E LDR: Unknown function '0x6D045C2E' in module 'cellLibprof'
E LDR: Unknown module 'sys_libm'
E LDR: Unknown function '0x9FB6228E' in module 'sysPrxForUser'
U {PPU[0x1000000] Thread (main_thread) [0x01695720]} sys_prx TODO: sys_prx_register_library(library=*0x11025ec)
U {PPU[0x1000000] Thread (main_thread) [0x01695720]} sys_prx TODO: sys_prx_register_library(library=*0x1102608)
U {PPU[0x1000000] Thread (main_thread) [0x016959c0]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x016959c8]} sysPrxForUser TODO: _sys_process_at_Exitspawn
E {PPU[0x1000000] Thread (main_thread) [0x00c7a404]} sys_vm: sys_vm_memory_map(vsize=0xe000000, psize=0x9810000, cid=0xffffffff, flags=0x200, policy=0x1, addr=*0xd001fa90)
U {PPU[0x1000000] Thread (main_thread) [0x009e48c0]} HLE TODO: Unimplemented syscall sys_spu_thread_group_log -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x016e6c8c]} sys_spu TODO: Unsupported SPU Thread Group type (0x20)
U {PPU[0x1000000] Thread (main_thread) [0x016e6d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x016e6d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x016e6d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x016e6d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x016e6d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x016e6d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x01695740]} sys_prx TODO: sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x016ef63c]} HLE TODO: Unimplemented syscall sys_spu_thread_group_set_cooperative_victims -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x01690f08]} cellGcmSys TODO: cellGcmSetVBlankFrequency
E {PPU[0x1000000] Thread (main_thread) [0x01690ef0]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)

**Comment by AniLeo** [comment]
Please use the forums to report games' status.
Don't use console output when reporting stuff, always upload full RPCS3.log file.
