### ISSUE TITLE
Vulkan: Booting game hangs when multiple GPUs are enabled

### ISSUE THREAD

**Issue by OrcaXS** [RPCS3/rpcs3#2638]
RPCS3 v0.0.2-3-6548807 Alpha
Running Diva F on Windows 10 1703. The CPU is Intel i3-6100 and the GPU is R9 270X 2GB.
Runs fine when only 270X is enabled.
When both HD 530 and 270X are enabled, and 270X is chosen as D3D Adapter in settings, rpcs3.exe would be not responding after selecting "Boot game" and booting a game folder from menu.
DX12 and OpenGL seem fine.

[RPCS3.log.txt](https://github.com/RPCS3/rpcs3/files/901380/RPCS3.log.txt)

**Comment by AniLeo** [comment]
D3D adapter is only for D3D12, it doesn't affect Vulkan. What do you mean both enabled? I run HD 530 and 960M with Nvidia Optimus and have no such issue

**Comment by OrcaXS** [comment]
Mine is a desktop PC. I enabled IGFX in BIOS and connected the monitor to 270X, so I can use 270X for gaming, HD 530's QuickSync Encoder for Recording/Streaming at the same time. Really useful for CPUs like i3 to reduce CPU usage.
So currently there's no way to specify a GPU to use under Vulkan?

**Comment by kd-11** [comment]
Not implemented, uses gpu0 always at the moment

**Comment by OrcaXS** [comment]
Is there any way to know which GPU is gpu0 when using Vulkan?

**Comment by kd-11** [comment]
First enumerated device, probably by PCI init order. In your case the iGPU will be selected as first device since it is the first initialized GPU. Implementing GPU to use a specific GPU will require a rewrite of the settings dialog UI framework, since it is possible to have DX12 support without vulkan and vice-versa.

**Comment by OrcaXS** [comment]
After testing in other applications using Vulkan like Dolphin Emulator, I can now confirm that HD 530 won't perform normally under Vulkan as a secondary GPU (Driver Ver. 15.45.16.4627). So it should be the reason that caused RPCS3 to hang, since it was chosen as gpu0.
Hope RPCS3 would have an option to specify a GPU when using Vulkan someday.

**Comment by Megamouse** [comment]
could this be fixed now with new settingsdialog?
