### ISSUE TITLE
Error compiling Vulkan

### ISSUE THREAD

**Issue by Dokman** [RPCS3/rpcs3#2646]
Log:
`Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado de supresión
Error	MSB3073	:cmEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	El comando "setlocal [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	xcopy /Y /I D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\Release\vulkan-1.dll D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\..\demos\Release\ [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	if %errorlevel% neq 0 goto :cmEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:cmErrorLevel [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	exit /b %1 [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:cmDone [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	if %errorlevel% neq 0 goto :VCEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	setlocal [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	xcopy /Y /I D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\Release\vulkan-1.dll D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\..\tests\Release\ [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	if %errorlevel% neq 0 goto :cmEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:cmEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:cmErrorLevel [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	exit /b %1 [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:cmDone [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	if %errorlevel% neq 0 goto :VCEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:VCEnd" salió con el código 9009. [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	El comando "setlocal [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	xcopy /Y /I D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\Release\vulkan-1.dll D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\..\demos\Release\ [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	if %errorlevel% neq 0 goto :cmEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:cmEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:cmErrorLevel [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	exit /b %1 [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:cmDone [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	if %errorlevel% neq 0 goto :VCEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	setlocal [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	xcopy /Y /I D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\Release\vulkan-1.dll D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\..\tests\Release\ [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	if %errorlevel% neq 0 goto :cmEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:cmEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:cmErrorLevel [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	exit /b %1 [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:cmDone [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	if %errorlevel% neq 0 goto :VCEnd [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	:VCEnd" salió con el código 9009. [D:\Repos\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj]	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
Error	MSB3073	El comando "cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_CONFIGURATION_TYPES="Debug;Release" -DBUILD_TESTS=OFF -DBUILD_DEMOS=OFF -DBUILD_LAYERS=OFF -DBUILD_VKJSON=OFF ../Vulkan-LoaderAndValidationLayers
msbuild.exe ALL_BUILD.vcxproj /t:build /p:Configuration=Release /m" salió con el código 1.	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets	41	
Error	MSB3073	El comando "cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_CONFIGURATION_TYPES="Debug;Release" -DBUILD_TESTS=OFF -DBUILD_DEMOS=OFF -DBUILD_LAYERS=OFF -DBUILD_VKJSON=OFF ../Vulkan-LoaderAndValidationLayers
msbuild.exe ALL_BUILD.vcxproj /t:build /p:Configuration=Release /m" salió con el código 1.	Vulkan-build	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets	41	
`

**Comment by yxmline** [comment]
The system path variable is too long to cause the error and shorten the length of the path variable

**Comment by hcorion** [comment]
@Dokman This is an issue tracker for developers. For support, go to the forums http://www.emunewz.net/forum/forumdisplay.php?fid=172 or Discord: https://discord.me/RPCS3
Can someone please close this?
