### ISSUE TITLE
LLVM -MEM: Access violation reading location

### ISSUE THREAD

**Issue by sirdanielk** [RPCS3/rpcs3#2650]
llvm regression: F {PPU[0x1000000] Thread (main_thread) [0x004dce98]} MEM: Access violation reading location 0x501 in latest builds in some games around build #4340
Example game is Droplitz

**Comment by AniLeo** [comment]
Access violations are general errors, they happen currently on a lot of situations.
Refer to #1926

**Comment by kodathefox** [comment]
don't mean to bump something so old but I need a way to fix this error F {PPU[0x1000000] Thread (main_thread) [0x007db9ec]} MEM: Access violation reading location 0x0 every time it gets to checking dlc in tales of Xillia 2
