### ISSUE TITLE
rip model

### ISSUE THREAD

**Issue by Northwemko** [RPCS3/rpcs3#2652]
now this can be run most game,so hope provide a method ,rip model

**Comment by AniLeo** [comment]
What?

**Comment by Northwemko** [comment]
ripper 3d model

**Comment by kacek** [comment]
I think he wants option to export 3d models from games.

**Comment by hcorion** [comment]
I'm pretty sure ripping models from games is Illegal.

RPCS3 does nothing illegal, and will not do anything illegal in the future. I'm pretty sure RPCS3 doesn't want to get legal action from game laywers.

Could someone close this?

**Comment by kirbyfan64** [comment]
http://lmgtfy.com/?q=how+to+rip+3d+models+from+ps3+games

Also, I'm not sure what this quite has to do with RPCS3 to begin with...?
