### ISSUE TITLE
Field <Settings->Graphics->3D3 Adapter> is not available on Windows7

### ISSUE THREAD

**Issue by ArtyomAN** [RPCS3/rpcs3#2656]
Hi,

I try to launch Demon's Souls. It works but provide 3-15 FPS with PPU/SPU Recompiler. But I can't see or choose my video adapter in the filed <Settings->Graphics->3D3 Adapter>. May it be the reason of so poor performance?

System: i5-2500K @3.3GHz / 8RAM / GeForce GTX 960.

Thanks!

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/907884/RPCS3.zip)
![rpcs3](https://cloud.githubusercontent.com/assets/27104345/24833369/a601c298-1ccf-11e7-89e9-bbd7f77d367c.JPG)

**Comment by Zangetsu38** [comment]
D3D Adapter only for Windows 10 and Dx12

**Comment by ArtyomAN** [comment]
Sorry for silly reasking...
I guess that it means that the emulator works correct on Win7 despite of the fact that D3D Adapter is not specified on GUI. Correct?

**Comment by Zangetsu38** [comment]
yes, not need this for Vulkan and OGL

**Comment by ArtyomAN** [comment]
Thanks!

P. S. Amazing work! Wish you further progress! :)
