### ISSUE TITLE
Regression : Framerate drop on recent version

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#2658]
CPU : Core 2 Quad Q6600
GPU : NVIDIA Geforce GTX 950
On new git version , framerate drop to 15-18 FPS , not on 30 FPS on the old build , and the older build , the game is running faster than newer git version
![image](https://cloud.githubusercontent.com/assets/11285640/24836887/058b9658-1d52-11e7-9863-f1c3355f31c7.png)

**Comment by AniLeo** [comment]
I've noticed some drops but it didn't happen in the latest merge. Where did the regression happen for you exactly?

**Comment by zminhquanz** [comment]
@AniLeo After release 0.0.2 version

**Comment by raven02** [comment]
Probably related to the reservation rewritten .

**Comment by zminhquanz** [comment]
I tried all older build in the past , result it still the same , i think the problem is Windows 10 Creators Update,  i was updated 3 days ago

**Comment by raven02** [comment]
I'm closing this then if you think it is the Windows 10 problem .
