### ISSUE TITLE
give some support for old 3.3 OpenGL Hardware

### ISSUE THREAD

**Issue by AkagiShiroe** [RPCS3/rpcs3#2661]
0,0 im just need the emu to render 3D Stuff even without shader... that should not impossible... even have a lower framerate...

**Comment by AniLeo** [comment]
It doesn't have required instructions and supporting older APIs is a PITA. 

I guess it's up to @kd-11 to see if it's feasible.

**Comment by clienthax** [comment]
Please no.. we already have three render paths as it is

**Comment by paulsapps** [comment]
rendering without shaders pretty much is impossible when the target of emulation is using shaders, what else could it map to? software shaders? that wouldn't even be 1fps.

**Comment by raven02** [comment]
Closed . @paulsapps has been explained very clear .
