### ISSUE TITLE
Can't configure game on linux

### ISSUE THREAD

**Issue by Areiser** [RPCS3/rpcs3#2662]
When right clicking a game and selecting the configure menu item on linux, I hit an assertion.
commit:  4c741e9
error output: [backtrace](https://github.com/RPCS3/rpcs3/files/908473/rpcs3log.txt)

Also, debug output spams this, not sure if related: 
"21:16:03: Debug: Unknown accel modifier: 'ctrl '
21:16:03: Debug: Unrecognized accel key ' e', accel string ignored."

System: i5 4460, r9 270
Arch linux (mesa drivers)

**Comment by hcorion** [comment]
@Areiser 
You've compiled rpcs3 in debug mode, compile it in release mode, it should fix your issue.

**Comment by Areiser** [comment]
Looks like cmake caches when I compile in clion which uses -DCMAKE_BUILD_TYPE override. Thanks

**Comment by MonokelPinguin** [comment]
I still think this is an issue. We try to remove the D3D12 renderer on linux, while the renderer isn't even in the list of renders. That's why the assertion fires.
Effectively 5fce74a doesn't seem to be needed anymore. I don't know why though.
