### ISSUE TITLE
i have a issue with drakengard 3 not booting up

### ISSUE THREAD

**Issue by BLEEP00** [RPCS3/rpcs3#2665]
whenever I try to boot it up with rpcs3 it says

F LDR: class std::runtime_error thrown: Failed to load /dev_flash/sys/external/libpngdec.sprx: Invalid stream or file not found

if anyone knows a fix to this I will love you forever

**Comment by AniLeo** [comment]
Use the forums for support and read the quickstart guide as you've failed following the first step on it
