### ISSUE TITLE
Problem with SPU Decoder : Fast / ASMJIT

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2670]
@Nekotekina 
@jjsat 

**[TNT Racers]**
<img src="http://www.fotoszok.pl/upload/a5725da6.jpg" alt="Fotoszok.pl" />

Logs:
**[-Interpreter (precise):](https://mega.nz/#!8Bwl1BpA!OxUP1XHO8GzxvTn03x-w9qBrFwh96XpQtXL15KmPPeE)**
**[-Interpreter (fast):](https://mega.nz/#!lNhFTSoS!QLa8dfSFGA3FT9udhd6bh_U6TAaESC6agG0AwLXpDZw)**
**[-Recompiler (ASMJIT):](https://mega.nz/#!wd5DkLQY!HwhKwHgM2NZvCkVOoGTLa1AAB3_pok1EKPAt6gKvBqM)**

--------------------------------------------------------------------------------------------------------------
**[Bleach Soul Ignition]**
<img src="http://www.fotoszok.pl/upload/d5d58275.jpg" alt="Fotoszok.pl" />

Logs:

**[-Interpreter (precise):](https://mega.nz/#!odRmBJxY!NR142WmmkLxUSiUVloe_CbQIjwMKQ-WJRi2ItHaicaE)**
**[-Interpreter (fast):](https://mega.nz/#!0RIEGJCA!C4oa4Xxn6O6WesNsq-70sUnLcJqa2MqftAS49JbRvyc)**
**[-Recompiler (ASMJIT):
](https://mega.nz/#!0BQ33IjQ!RSgXeOvAbSrvC0EocFo3zFPKSdm1E5q7aOCdewvSUTc)**

**Comment by Zangetsu38** [comment]
other game have same issue
>Attack on titan
Vanquich
Heavy Rain
Tokyo Jungle
Midnight club

**Comment by MarioSonic2987** [comment]
With PPU fast **Skate 2**, map disappears after waiting ~5 sec. In PPU precise, it doesn't.
![image](https://cloud.githubusercontent.com/assets/20027681/24875069/24d0e56a-1e27-11e7-893a-d16a30cda9bc.png)

**Comment by slashiee** [comment]
**Persona 5** gets major polygon issues when ran in PPU Fast.
![Persona 5 in PPU Fast](https://cloud.githubusercontent.com/assets/15317421/24876841/0db6ffb2-1de2-11e7-9cff-f19c1d43ecc7.png)

PPU Precise and ASMJIT work with no issues.
![Persona 5 in PPU Precise](https://cloud.githubusercontent.com/assets/15317421/24877047/bf4d68b0-1de2-11e7-930f-9620baf7967a.png)

[RPCS3-PPUFast.zip](https://github.com/RPCS3/rpcs3/files/911077/RPCS3-PPUFast.zip)
[RPCS3-PPUPrecise.zip](https://github.com/RPCS3/rpcs3/files/911109/RPCS3-PPUPrecise.zip)
[RPCS3-ASMJIT.zip](https://github.com/RPCS3/rpcs3/files/911131/RPCS3-ASMJIT.zip)

**Comment by ikki84** [comment]
SPU* @slashiee

**Comment by Zangetsu38** [comment]
Another Game Bentley, perfect render, just color green strange
![capture d ecran 2017-04-11 01 21 13](https://cloud.githubusercontent.com/assets/5261759/24886525/75fa556a-1e55-11e7-83b2-130333010ccb.png)

![capture d ecran 2017-04-11 01 20 12](https://cloud.githubusercontent.com/assets/5261759/24886527/75fb0abe-1e55-11e7-9c5d-457fc0533b27.png)

**Comment by Xcedf** [comment]
Metal Gear Rising Here
Interpreter (fast), btw faster than ASMjit
![45](https://cloud.githubusercontent.com/assets/7060586/24893934/7187558e-1e8f-11e7-8e95-ae11951f9a7c.jpg)
Interpreter (Precise)
![46](https://cloud.githubusercontent.com/assets/7060586/24893942/7fa523d0-1e8f-11e7-9e52-dbdbc9aa9981.jpg)

**Comment by MarioSonic2987** [comment]
**_Grand Theft Auto V_**

**With SPU precise**:
![image](https://cloud.githubusercontent.com/assets/20027681/24894933/b8a408c4-1e8d-11e7-9052-c571fe0a06e2.png)

**With SPU fast**:
![image](https://cloud.githubusercontent.com/assets/20027681/24894976/0a664a50-1e8e-11e7-8862-66267976869d.png)

**Comment by RainKikyou** [comment]
DOA5 last round
sengoku musou4
SPU precise
![qq 20170411155237](https://cloud.githubusercontent.com/assets/20301499/24899240/1e31f8d8-1ed2-11e7-8b0b-82af6f30036d.jpg)
![qq 20170411160055](https://cloud.githubusercontent.com/assets/20301499/24899254/30f108d8-1ed2-11e7-87a0-50f5eb758b6f.jpg)
SPU fast
![fast2](https://cloud.githubusercontent.com/assets/20301499/24899274/3fea25a4-1ed2-11e7-8c1c-594143ea84c2.jpg)
![fast](https://cloud.githubusercontent.com/assets/20301499/24899276/45b55ac6-1ed2-11e7-9ff9-d5aa1ac89637.jpg)

**Comment by MarioSonic2987** [comment]
Tekken Revolution: SPU affects lighting.

**SPU precise**:
![tekkenrev](https://cloud.githubusercontent.com/assets/20027681/24951904/31a4a704-1f76-11e7-93ab-56da04f17070.png)

**SPU fast**:
![avzxvzv](https://cloud.githubusercontent.com/assets/20027681/24808133/fbff5dd8-1bba-11e7-81c8-4b8246d1c8ad.png)

**Comment by Xcedf** [comment]
MarioSonic2987, how did you get working shadows in Tekken?

Sly Copper: Thieves in Time
Spu Precice:
![47](https://cloud.githubusercontent.com/assets/7060586/24957377/43f18e7c-1f94-11e7-87a9-bc8094de47f4.jpg)

Spu Fast:
![48](https://cloud.githubusercontent.com/assets/7060586/24957385/48fc0b18-1f94-11e7-9fd4-c6274f07414c.jpg)

**Comment by MarioSonic2987** [comment]
@Xcedf , let the game loading that landspace. Some are fine but other aren't.

**Comment by Zangetsu38** [comment]
Arf I can't test this I am kit m'y home cry lol

**Comment by SakataGintokiYT** [comment]
@kd-11 
@Zangetsu38 
**[Recompiler (ASMJIT):]**
<img src="http://www.fotoszok.pl/upload/9f6154b2.jpg" alt="Fotoszok.pl" />

**[Interpreter (fast):]**
<img src="http://www.fotoszok.pl/upload/606474c3.jpg" alt="Fotoszok.pl" />

**Comment by MarioSonic2987** [comment]
![image](https://cloud.githubusercontent.com/assets/20027681/25002575/6f3509d0-204b-11e7-98f0-0a73f56f9196.png)
With SPU fast.
https://github.com/RPCS3/rpcs3/commit/aa2621963708f0901b47d83cdf1a0586db09aa91

**Comment by kd-11** [comment]
For lighting I suspect the RSQ methods, but I have no way of testing at the moment.

**Comment by SakataGintokiYT** [comment]
@kd-11 
Can you check same instructions in PPUTranslator ?

**Comment by kd-11** [comment]
They have already been fixed for ASMJIT as well

**Comment by kd-11** [comment]
Or do you mean PPU side? Haven't checked, but the PPU stuff is in alot better shape.

**Comment by SakataGintokiYT** [comment]
I mean LLVM

**Comment by kd-11** [comment]
As far as I can tell, its the same between PPU interpreter and recompiler. Can't just put the same stuff on the PPU since I dont know for sure how the core handles such cases. For SPUs, its easier since the precise interpreter implemented an accurate emulation of these opcodes, so its easier to confirm behaviour by comparing results.

**Comment by Xcedf** [comment]
All titles i have Metal Gear Rising, Sly Copper, Ni No Kuni work well now, i wasn't able to start Haevy Rain Demo with SPU Precice, but now it works well with ASMjit
Thanks

**Comment by Xcedf** [comment]
House of The Dead Overkill, fixed broken geometry in cutscene

**Comment by Xcedf** [comment]
Resident Evil Revelations, main chararcter model now vis
![49](https://cloud.githubusercontent.com/assets/7060586/25016760/e857e650-2089-11e7-9d9f-c6eda2c0ec64.jpg)
ible
