### ISSUE TITLE
directx 12 and vulkan not responding

### ISSUE THREAD

**Issue by akain88** [RPCS3/rpcs3#2671]
have this problem whenever i change to those two the emulator stops responding and no log no nothing just freeze, is it because my computer or do i need something else, since i just update to win 10 upgrade de drivers too 

RPCS3 V0.02-3-4C741e9 alpha although same happens in others builds
persona5 NPEB02436
AMD a4-6300 apu radeonhd (2gpu) 3.7GHz 4gb ram

**Comment by AniLeo** [comment]
Your APU doesn't have D3D12 nor Vulkan support. 
Please research a bit about requirements before opening such issues and use the forums for support, invalid issues have been increasing way too much lately.
