### ISSUE TITLE
Demon's Souls [BLES00932] freezes when using LLVM Recompiler.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#2674]
Decided to open this bug ticket.
I guess, this could be hardware-specific problem. Game freezes 100% when exiting to main menu.
Here are the log.

[RPCS3.log.txt](https://github.com/RPCS3/rpcs3/files/911531/RPCS3.log.txt)

**Comment by ArtyomAN** [comment]
I have the same problem. The game hangs on every time when I'm trying to exit to main menu. I may attach the log if it is necessary.

**Comment by raven02** [comment]
Consolidated into another thread .
