### ISSUE TITLE
Crash when starting a Game in Linux

### ISSUE THREAD

**Issue by logos88** [RPCS3/rpcs3#2675]
Segfault reading location 0000000000000000 at 00000000009af24f.

Archlinux
i5-4570
﻿RPCS3 v0.0.2-5123-3f20e0c5a Alpha

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/911646/RPCS3.zip)

**Comment by hcorion** [comment]
@logos88
The log says 

"Failed to initialize OpenGL renderer. ARB_texture_buffer_object is required but not supported by your GPU"

What system are you running this on?

**Comment by hcorion** [comment]
As in GPU

**Comment by hcorion** [comment]
Also, if you've just installed the latest mesa update, you might have to restart your computer.

**Comment by logos88** [comment]
My fault. I needed to use MESA_GL_VERSION_OVERRIDE=4.3 to run it on Mesa. This way it works
