### ISSUE TITLE
Red Dead Redemption [BLES01294]: Invalid RSX method error resulting in freeze

### ISSUE THREAD

**Issue by Grima04** [RPCS3/rpcs3#2680]
I get different issues in RDR when I boot up the game. Sometimes I get nothing but a blackscreen after the two revolver animations have loaded and the game freezes with the following error:
U {PPU[0x100000d] Thread ([RAGE] DiskCache Worker) [0x0186b458]} HLE TODO: Unimplemented syscall sys_fs_fsync -> CELL_OK
or this:
U {PPU[0x1000000] Thread (main_thread) [0x018331c0]} cellNetCtl TODO: cellNetCtlGetInfo(code=0x4 (INFO_LINK), info=*0x15f7a78)
E {rsx::thread} RSX: Unknown/illegal instruction: 0x3d (forced unit 2)
E {rsx::thread} RSX: Invalid RSX method 0xcba0 (arg=0x0)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:38)

![screenshot 500](https://cloud.githubusercontent.com/assets/22496380/24945184/8bd51636-1f5e-11e7-9da5-c0482d1bf2ae.png)

At other times however the menu loads completely and renders all textures before freezing. With some luck pressing start even works before the freeze but it is random.
![screenshot 494](https://cloud.githubusercontent.com/assets/22496380/24945198/982fcdea-1f5e-11e7-98f4-ff31d55d0528.png)

From all the errors listed the unimplemented syscall error is the most frequent one.

I also made a video about it:
https://www.youtube.com/watch?v=h9pc5sWfwf4&t=54s

Here is the RPCS3 log: 
[RPCS3-RDR-LOG-12.04.2017.zip](https://github.com/RPCS3/rpcs3/files/915662/RPCS3-RDR-LOG-12.04.2017.zip)

**Comment by AniLeo** [comment]
That unimplemented syscall should be irrelevant, load libfs with load lv2.sprx for manual override if you have fs issues. 

Issue with rdr crashing is probably on RSX/GCM and such behavior is already known. Please report game test runs on the forums.

**Comment by scribam** [comment]
@Grima04 Would you mind trying to run the game again? I think it works better now with the latest build so this issue should be gone.

**Comment by Grima04** [comment]
Since the implementation of GCM, the game doesn't hang anymore and those errors stopped occuring, so I will close this issue now.
