### ISSUE TITLE
Regression in Akiba's Trip [BLUS31425]

### ISSUE THREAD

**Issue by twdarkeh** [RPCS3/rpcs3#2685]
https://github.com/RPCS3/rpcs3/commit/370c2ecac5c6837448aa5b23a2621e14310a231b

As of this commit, it hangs after initial loading. Tested with/without LLVM, OGL and Vulkan. All hang right after it's done loading with:

F {PPU[0x1000015] Thread (savedata_sub_thr) [0x002c3e08]} MEM: Access violation writing location 0x508

http://puu.sh/vj7JU.zip Log.

**Comment by Zangetsu38** [comment]
yes, same error, working before

**Comment by Zangetsu38** [comment]
other regression in Knyt Undergrund,; after create/Load save
F {MFC Thread} MEM: Access violation reading location 0xcb6080

**Comment by isshininu** [comment]
> F {MFC Thread} MEM: Access violation reading location

I could swear I've seen this line in Demon's Souls output, too...

**Comment by davoodinator** [comment]
is this the problem with dragons crown as well?

**Comment by twdarkeh** [comment]
@davoodinator If it's the sound thread, I doubt a change in cellSaveData caused it.

**Comment by twdarkeh** [comment]
Fixed by #2690
