### ISSUE TITLE
Possible null deref in cellsave

### ISSUE THREAD

**Issue by Farseer2** [RPCS3/rpcs3#2693]
https://github.com/RPCS3/rpcs3/blob/370c2ecac5c6837448aa5b23a2621e14310a231b/rpcs3/Emu/Cell/Modules/cellSaveData.cpp#L927

The function's arguments are optional and may be NULL, but this isn't checked, leading to possible access violations in some games.
Didn't want to make the commit myself to fix it as I know someone is working on that area currently, just don't know if he is aware of the issue.

**Comment by Inviuz** [comment]
It already happened in issue #2685
