### ISSUE TITLE
help

### ISSUE THREAD

**Issue by kingpin0001** [RPCS3/rpcs3#2694]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault writing location 0000000000000000 at 0000000000000000.
Instruction address: 0000000000000000.
RPCS3 image base: 0000000000010000.

**Comment by AniLeo** [comment]
Please use the forums for help and read the part that asks for people not to send incorrect reports.

**Comment by kingpin0001** [comment]
ok sorry
