### ISSUE TITLE
Fatal Error when installing PKG file

### ISSUE THREAD

**Issue by NuLz0** [RPCS3/rpcs3#2695]
HI.
I have recently installed rpcs3 and tried to install the demon's souls pkg file but whe I try to do said thing i get this error: 

Fatal error  Unhandled Win32 exception 0xC000001D. 
Exception address: 00000000000ff82a. 
Instruction address: 00000000000ff82a. 
Function address: 00000000000ff800 (base+0xef800). 
Module name: 'rpcs3.exe'. 
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000. 

Illegal instruction exception occured. 
Note that your CPU must support SSSE3 extension.

If anyone has answers, please help me because I do not understand any of this.
Thank you.

**Comment by Talkashie** [comment]
What processor do you have?

**Comment by kirbyfan64** [comment]
> Note that your CPU must support SSSE3 extension.

The ultimate question: does your CPU support SSSE3? (**NOT** SSE3: it's three *S*'s, not two).

**Comment by NuLz0** [comment]
its a shit processdor but it can handle pretty much any game like mgsv. It's a AMD Phenom(tm) II X4 925 Processor 2.80 GHz. I have 5 gb of ram (I know) and dats it.

**Comment by AniLeo** [comment]
It doesn't support SSSE3, therefore not supporting RPCS3. 
Please check the hardware and software requirements on our website.

**Comment by NuLz0** [comment]
gad demmit 
Well thanks anyways guys.
