### ISSUE TITLE
[Sonic Unleashed] - BLES00425 : Fatal Error

### ISSUE THREAD

**Issue by AmrSaadMEGA** [RPCS3/rpcs3#2696]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000050 at 00000000002fe4a4.
Instruction address: 00000000002fe4a4.
Function address: 00000000002fe430 (base+0x2ee430).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

**Comment by AniLeo** [comment]
Please read the message asking people not to submit incorrect reports and use the forums for support.
