### ISSUE TITLE
Sonic Unleashed - [BLES00425] : Fatal Error

### ISSUE THREAD

**Issue by AmrSaadMEGA** [RPCS3/rpcs3#2697]
Hi ..
 this is the first game i have tried on rpcs3 and installed the PS3UPDAT.PUP file from "tools" menu then i got this error after a few seconds of loading :

Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000050 at 00000000002fe4a4.
Instruction address: 00000000002fe4a4.
Function address: 00000000002fe430 (base+0x2ee430).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000

My system requirements :
CPU Type - Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
GPU AMD Radeon R7 M265 
Windows Version - Windows 10 (64 bit)
System Memory - 4 GB
OpenGL® Version 6.14.10.13469
Direct3D® Version 9.14.10.01249
Vulkan™ Driver Version 1.4.1
Vulkan™ API Version 1.0.37

**Comment by AniLeo** [comment]
As said on the previous issue, please don't abuse GitHub Issues and use the forums for support. 
The Unhandled 0xC0000005 exception means nothing by itself, it happens on several games that don't work and by several reasons, Sonic Unleashed is just one of them.

Games like Sonic Unleashed won't work yet although currently the Demo boots to a title screen and freezes there as you can see on the Compatibility List on our website. 
If you want to report game statuses, also use the forums.
