### ISSUE TITLE
input are wrongly detected with latest scptoolkit

### ISSUE THREAD

**Issue by cloud1250000** [RPCS3/rpcs3#2701]
Hi,

x is square, the right analog is not completely working too.

Thanks!

ps : I got an average of 25fps in catherine :) 
here's my specs : http://valid.x86.fr/dr896z

**Comment by AniLeo** [comment]
What controller are you using

**Comment by cloud1250000** [comment]
a dualshock 3

**Comment by Talkashie** [comment]
Have you tried setting input to Xinput?

**Comment by cloud1250000** [comment]
yes and it doesn't work at all..
