### ISSUE TITLE
Build issue/question about llvm (Fedora)

### ISSUE THREAD

**Issue by martinlindhe** [RPCS3/rpcs3#2715]
I cloned the repo,
then I ran `git submodule update --init`
and noticed LLVM was pulled into ./llvm

however, cmake tells me llvm is not found.

so, why pull llvm submodule if it is not used,
or, how can i enable use of the llvm submodule?

```
CMake Warning at rpcs3/CMakeLists.txt:95 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 4.0) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
LLVM not found! LLVM 4.0 is required. RPCS3 will be compiled without LLVM support.
```

**Comment by hcorion** [comment]
@martinlindhe 
The LLVM submodule is for windows AFAIK. On Linux it expects llvm 4.0 to be installed. RPCS3 will still work and compile fine without llvm.

If you want the best performance, you can install LLVM 4.0 (not yet available on most distros).

**Comment by martinlindhe** [comment]
@hcorion Ah, I see. Thanks for clarifying that =)

**Comment by John-Gee** [comment]
@hcorion wouldn't it be feasible to compile against the llvm submodule? It would be really nice both for people with llvm < 4.0 and for people with llvm > 4.0 (my case).

**Comment by hcorion** [comment]
@John-Gee It doesn't really make a ton of sense. LLVM has to be dynamically linked anyway. Some distros have started to update LLVM to 4.0, Debian and Ubuntu have PPAs for LLVM 4.

If you want you can go ahead and build LLVM using the submodule, you might have to use some fancy cmake flags for helping it find the include folders, but yeah, you could compile it against the submodule.

**Comment by John-Gee** [comment]
It makes sense to me, since I'll never have llvm 4 installed :)

I tried but like martinlindhe I was not able to get it working, maybe I need to build llvm first or something I am not sure. I'd be happy to try if you have any idea.

I suppose the flatpak/appimage is another way to solve that problem.

**Comment by kd-11** [comment]
Please remember that loading separate llvm instances will fail if a system component uses llvm, making static compilation incompatible with gallium.

**Comment by John-Gee** [comment]
Oh I see, then there is no hope :/
