### ISSUE TITLE
Error with the game JoJo's Bizarre Adventure All-Star Battle

### ISSUE THREAD

**Issue by BIKTOP111** [RPCS3/rpcs3#2716]
F LDR: Failed to load RAP file: /dev_hdd0/home/00000001/exdata/EP0700-NPEB01922_00-DLG00000000ASB01.rap
E LDR: SELF: Can't find RAP file for NPDRM decryption!
E LDR: SELF: Failed to load SELF file metadata!
F LDR: class std::logic_error thrown: fs::file is null
  I don't know what to do. Please help

**Comment by AniLeo** [comment]
Please read the guidelines before submitting issues. 
https://github.com/RPCS3/rpcs3/tree/master/CONTRIBUTING.md 

Your question is explained on the quickstart guide
