### ISSUE TITLE
Regression: Heavenly Sword 

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#2717]
Heavenly Sword BCES00078
Game freezes with thread schedule commit 598c90f3, the commit itself is too big for me to find out more specific info,
here's the screen
![59](https://cloud.githubusercontent.com/assets/7060586/25266757/fe679502-267a-11e7-883d-58d7b33f9427.jpg)
and the log from the latest master
https://mega.nz/#!yYYzVYwR!MwSFxhtVtmnPp5KL1ShPxB62bpmv5EuoozlL3E60jCE

but i managed to get ingame on the previous e4962054 commit and many hacks:
the first of all i disabled some log meesages

·E {PPU[0x100000a] Thread (Second Hard Thread) [0x00a57970]} 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH
·E {PPU[0x100000a] Thread (Second Hard Thread) [0x00a57980]} 'sys_cond_wait' failed with 0x80010005 : CELL_ESRCH
·E {PPU[0x100000a] Thread (Second Hard Thread) [0x00a5798c]} 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH

cause emulator produces these three like every frame, making log file several GB sized to the time i reach menu, absolutely useless for debugging
replaced СELL_ESRCH with CELL_OK in sys_mutex and sys_cond files

the next hack was sys_spu_.cpp line 62 fixed by latest RPX Improvements commit
next one is 
F {rsx::thread} RSX: Invalid RSX method 0x1d08 (arg=0x0)
(in file Emu\RSX\rsx_methods.cpp:34)
not appears to be a problem for recent master

and the last one
F {SPU[0x2000000] Thread (CellSpursKernel0)} SPU: Unknown/illegal channel (ch=69 [$ch69], value=0x3)
(in file Emu\Cell\SPUThread.cpp:1038)
which not a problem for master either, the channel 69 was fixed in master
![58](https://cloud.githubusercontent.com/assets/7060586/25267072/29e42604-267c-11e7-8758-ddc246f094d7.jpg)
and the log
https://mega.nz/#!uF5HkJ6S!caeVvdFD25aLtqiaChSGW-2kDBByEY5mrIpGOIASO38

**Comment by Xcedf** [comment]
Found some sort of solution for this in commit from experimental branch
https://github.com/jarveson/rpcs3/commit/7279f4194ec7cc31553fbf8d3feb313ce2f454be
by commenting out return CELL_EINVAL; like it shown in the commit the game no longer hangs and goes into menu, no longer get ingame even with hacks, but this already another issue
and btw https://github.com/RPCS3/rpcs3/issues/1283 is also fixed by DS4 changes

**Comment by Inviuz** [comment]
All of CELL_ESRCH errors are caused by synchronization methods(mutex, cond etc), which use ipc_key. Right now rpcs3 throws error when a game tries to create one, simple hack to allow creation of those helps a lot in Heavenly Sword and iirc Skyrim.

**Comment by Xcedf** [comment]
Spent few more hours of testing, with trick from my last comment i bypassed 598c90f to another blocking commit 9000407a which make emu to freeze just before ingame
removing & spu.ch_event_mask form SPUInterpreter.cpp and SPURecompiler.cpp like it shown in commit helps to get ingame once more. 
Another blocking revision is 5e3bacbd New Reservations one, and this one is to complex for me i can't debug it

**Comment by Xcedf** [comment]
Closing this issue, opened a new one https://github.com/RPCS3/rpcs3/issues/2982

**Comment by Xcedf** [comment]
Closing this issue, opened a new one https://github.com/RPCS3/rpcs3/issues/2982

**Comment by AniLeo** [comment]
Needs retesting, probably fixed.

**Comment by Xcedf** [comment]
Nope, not fixed, game still freezes just in the moment before ingame

**Comment by Xcedf** [comment]
Fixed now
