### ISSUE TITLE
Heavy Rain no boot after logo loading just FPS Freeze

### ISSUE THREAD

**Issue by zerr10** [RPCS3/rpcs3#2730]
Heavy Rain no boot after logo loading just FPS Freeze and just black Screen

rpcs3-v0.0.2-2017-04-20-463e18f8_win64

i7 6700 4x3.4Ghz rx 460 4gb ram 8 gb dual 2133Mhz

**Comment by raven02** [comment]
Please discuss this in forum http://www.emunewz.net/forum/forumdisplay.php?fid=172

**Comment by AniLeo** [comment]
This is the forth time you open an invalid issue. Read the guidelines.
