### ISSUE TITLE
sys_rwlock implementation regression

### ISSUE THREAD

**Issue by Giza** [RPCS3/rpcs3#2731]
Hello,

We have been running several tests of Umineko no Naku Koro ni Rondo/Chiru (BLJM60292, BLJM60414), and discovered that the recent trunk version is not compatible.

In the [game thread](http://www.emunewz.net/forum/showthread.php?tid=177575) there is a reference to a [particular changeset](https://github.com/RPCS3/rpcs3/pull/2316/files) that broke game compatibility. There also are log messages showing that sys_rwlock_wlock fails CELL_EDEADLK error code.

We have spent several hours trying to understand what was changed in that commit, and debugged the latest version, but unfortunately were out of luck. Afterwards we downgraded and attempted to apply the changes partially. The game breaks immediately after merging [the first commit](https://github.com/RPCS3/rpcs3/pull/2316/commits/c4cc3ad81ec54646565d984745ca3ae18d573833), but to be honest it is hard to judge, since the commits seem to be not meant for compilation and testing.

We suspect that the issue is relevant to the way locks were changed to work in total. If we read the diff correctly, former rwlock implementation was reentrant, and current one is not. Also there is a lot of mess due to global LV2_LOCK removal in favour of local locks and a switch from notify_all to notifying the particular threads.

Could anybody look into it or at least provide some information and thoughts.

Best regards,
Giza

**Comment by vit9696** [comment]
For better tracking here are the trace logfiles of [working](https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-3663/artifacts) and [not working](https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-3665/artifacts) builds from AppVeyor:

[Logs.zip](https://github.com/RPCS3/rpcs3/files/951515/Logs.zip)

CC @Nekotekina

**Comment by Giza** [comment]
For better tracking here are the trace logfiles of working and not working builds from AppVeyor:

[Working](https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-3663/artifacts):
сюда прикрепить лог

[Not working](https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-3665/artifacts):
сюда прикрепить лог

CC @Nekotekina

**Comment by Nekotekina** [comment]
Reentrant rwlock? I don't think so.
The main difference is error reporting. In previous versions, EDEADLK could happen as well but we wouldn't know. The main question is, why it happens at all.

**Comment by Giza** [comment]
Are you sure? The only difference in error reporting we see is a slightly modified error filtering, the logging facilities themselves are exactly the same.

When we merged the [initial commit](https://github.com/RPCS3/rpcs3/pull/2316/commits/c4cc3ad81ec54646565d984745ca3ae18d573833) without the necessary modifications for it to work we immediately got a number of error messages like:
```
E {PPU[0x1000002] Thread (DVDReader) [0x0004f814]} 'sys_rwlock_wunlock' failed with 0x80010009 : CELL_EPERM
E {PPU[0x1000002] Thread (DVDReader) [0x0004f618]} 'sys_rwlock_wlock' failed with 0x80010008 : CELL_EDEADLK
```
So clearly logging itself worked fine previously, and the error simply did not happen.

If you mean the error could have logically happened but would not have been properly identified and reported by the functions, then we think it is also not the case, since ppu id checking is present in the old code as well.

**Comment by Nekotekina** [comment]
Not completely sure, of course. Logging is only possible with `error_code` return value. In order to check, we need to put `error_code` in old working code and try it.

**Comment by Giza** [comment]
Oh, we didn't realise that those error_code additions were not just a style change but a transparent error reporting feature.
The news is that we went back to the old working code, put extra breaks at EDEADLK, and got no hits.
Afterwards we modified the return types of the syscalls to error_code, and recompiled. Unfortunately no error prints as well.
So all in all the error did not happen previously.

**Comment by Giza** [comment]
From the debug session I can tell that the game:
* creates all the locks around the start and does not use sys_rwlock_destroy;
* does not use sys_rwlock_tryrlock and sys_rwlock_trywlock;
* does not use lock timeouts;
* does not print any errors from sys_rwlock with the old code and error_code return type;
* gets CELL_EDEADLK from sys_rwlock_wlock with the new code.

This makes me very suspicious about sys_rwlock_wunlock and sys_rwlock_runlock. The overall situation looks like some lock is not unlocked when it should be. I am quite uncertain whether the reworked notify_all code does the same thing it did before.

**Comment by Nekotekina** [comment]
Thanks for the clarification. There indeed could be a bug in the new implementation, and it causes EDEADLK in other games as well. I hope I'll be able to debug this problem soon.

**Comment by scribam** [comment]
@Giza Would you mind trying your games with the latest build available ? Fixes related to sys_rwlock have been merged to master.

**Comment by Giza** [comment]
@scribam Same as before
```
RPCS3 v0.0.3-5511-386ff781 Alpha
Intel(R) Core(TM) i5 CPU 760 @ 2.80GHz | 4 Threads | 14.00 GiB RAM
S LDR: Boot from gamelist per doubleclick: done
U {PPU[0x1000000] Thread (main_thread) [0x0018ed8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00167f10]} sysPrxForUser TODO: sys_prx_load_module_list(count=7, path_list=**0xd0010bfc, flags=0x0, pOpt=*0x0, id_list=*0xd0010bdc)
S {PPU[0x1000000] Thread (main_thread) [0x00167f10]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167f10]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00168218]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x00168220]} sysPrxForUser TODO: _sys_process_at_Exitspawn
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/libresc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/libpamf.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/libdmux.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/libdmuxpamf.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/libavcdec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/libadec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/libat3dec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/libatxdec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00167ef0]} sys_prx: Loaded module: /dev_flash/sys/external/libatrac3plus.sprx
E {PPU[0x1000000] Thread (main_thread) [0x00162e90]} 'cellGamePatchCheck' failed with 0x8002cb27 : CELL_GAME_ERROR_NOTPATCH
U {PPU[0x1000000] Thread (main_thread) [0x001662b0]} cellSysutil TODO: cellSysCacheClear()
E {PPU[0x1000000] Thread (main_thread) [0x00066a2c]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0x40f, alignment=0x10000000, alloc_addr=*0xd0010bf4)
E {PPU[0x1000000] Thread (main_thread) [0x00163088]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
U {PPU[0x1000000] Thread (main_thread) [0x00163070]} cellGcmSys TODO: cellGcmSetQueueHandler(handler=*0x177468)
E {PPU[0x1000000] Thread (main_thread) [0x00163088]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7) x2
E {PPU[0x1000002] Thread (DVDReader) [0x0020efc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST x3
F {PPU[0x1000002] Thread (DVDReader) [0x002109d4]} sys_fs: sys_fs_fcntl(): Unknown operation 0xc0000008 (fd=4, arg=*0xd001a820, size=0x28) x2
F {PPU[0x1000002] Thread (DVDReader) [0x002109d4]} sys_fs: sys_fs_fcntl(): Unknown operation 0xc0000008 (fd=5, arg=*0xd001a820, size=0x28) x2
E {PPU[0x1000002] Thread (DVDReader) [0x0020efc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST x3
F {PPU[0x1000002] Thread (DVDReader) [0x002109d4]} sys_fs: sys_fs_fcntl(): Unknown operation 0xc0000008 (fd=6, arg=*0xd001a820, size=0x28) x2
S {Audio Thread} XAudio 2.9 initialized
E {PPU[0x1000001] Thread (HDDReader) [0x0004fe8c]} 'sys_rwlock_wlock' failed with 0x80010008 : CELL_EDEADLK
E {PPU[0x1000002] Thread (DVDReader) [0x0004f618]} 'sys_rwlock_wlock' failed with 0x80010008 : CELL_EDEADLK x4
E {PPU[0x1000001] Thread (HDDReader) [0x0004fe8c]} 'sys_rwlock_wlock' failed with 0x80010008 : CELL_EDEADLK
E {PPU[0x1000002] Thread (DVDReader) [0x0004f618]} 'sys_rwlock_wlock' failed with 0x80010008 : CELL_EDEADLK
E {PPU[0x1000001] Thread (HDDReader) [0x0004fe8c]} 'sys_rwlock_wlock' failed with 0x80010008 : CELL_EDEADLK
```

**Comment by Nekotekina** [comment]
Any chance it's fixed by #3076 ?

**Comment by Giza** [comment]
@Nekotekina Yes, it work. Thx

**Comment by scribam** [comment]
@Giza Would you mind closing this issue if it's fixed?
