### ISSUE TITLE
F {rsx::thread} class std::runtime_error thrown: Failed to initialize OpenGL renderer. ARB_texture_buffer_object is required but not supported by your GPU

### ISSUE THREAD

**Issue by CordlessEX** [RPCS3/rpcs3#2739]
I have this error come up every time I try to launch a game. Help is appreciated

**Comment by SakataGintokiYT** [comment]
What graphic card do you have.

**Comment by CordlessEX** [comment]
it's an intel HD graphics 4600

**Comment by SakataGintokiYT** [comment]
Do you have only intel graphic card ?

**Comment by CordlessEX** [comment]
Yes, it's the only GPU I have

**Comment by kacek** [comment]
intel HD4600 have only OpenGL 4 support. According to https://rpcs3.net/quickstart RPCS3 needs GPU capable of running OpenGL 4.3 or better.

**Comment by CordlessEX** [comment]
Ooooh okay thanks for the info

**Comment by CordlessEX** [comment]
I checked my OpenGL version and it says I have version 4.3

**Comment by SakataGintokiYT** [comment]
Intel hd  4600 does not (fully) support OpenGL 4.3

**Comment by kacek** [comment]
i based on this:http://www.intel.com/content/www/us/en/support/graphics-drivers/000005524.html
but somhwere else i have read that driver updates introduced new opengl versions. Try updating your drivers.

One more thing: If you have problem not related to development, use our forum: http://www.emunewz.net/forum/forumdisplay.php?fid=172

**Comment by SakataGintokiYT** [comment]
@CordlessEX 
OpenGL Extension Viewer Use this program to check Supported opengl version

**Comment by AniLeo** [comment]
As said before, this is either due to your GPU not supporting such call or the drivers fault misreporting it. Please try updating the Intel video drivers. 

For support, please use our forums.

**Comment by kd-11** [comment]
Intel drivers do not report extensions properly. Will be fixed in a future commit.

**Comment by kirbyfan64** [comment]
FWIW if you're on Linux, you can try upgrading your Mesa version separately and overriding the supported version to 4.3. It worked for me (though I admittedly have *no* clue how).
