### ISSUE TITLE
Regression: Devil May Cry HD Collection

### ISSUE THREAD

**Issue by Zangetsu38** [RPCS3/rpcs3#2740]
Regresssion in launcher for DMC HD collection, before Intro works normally, but now freezed after press button or waiting intro video, after press Stop or close window, rpcs3 crash with this
![capture d ecran 2017-04-30 03 54 20](https://cloud.githubusercontent.com/assets/5261759/25561028/05e61468-2d63-11e7-96b4-fb45e4b184d3.png)

debug image in Visual Studio here https://cdn.discordapp.com/attachments/288114532872880128/308066606762950656/unknown.png
regression caused by this commit https://github.com/RPCS3/rpcs3/pull/2684/commits/402df6823513972d5fc35300a8f329173a9473f2 on this PR https://github.com/RPCS3/rpcs3/pull/2684
Before this PR works, and not have this fatal error.
>F {MFC Thread} MEM: Access violation reading location 0xe86080

And also,only boot and show menu/logo with automatic mode, lv2 only show nothing

**Comment by mrcmunir** [comment]
Try Recompuler LLVM PPU + Recompiler ASMJIT with DMC3.ppu.self + lv2 only

Loading fine  for me under linux

**Comment by Zangetsu38** [comment]
look my issue, i say this for DMC HD Launcher, this
![capture d ecran 2017-04-30 03 52 45](https://cloud.githubusercontent.com/assets/5261759/25565218/8f92c9bc-2dc3-11e7-8eaa-ad64cb7d2cbf.png)

**Comment by mrcmunir** [comment]
@Zangetsu38 Ah yes the launcher not working yet is freeze after that

**Comment by Zangetsu38** [comment]
Ok, after test comit one by one, regression caused by tyhis precisely commit
https://github.com/RPCS3/rpcs3/pull/2684/commits/402df6823513972d5fc35300a8f329173a9473f2
@Nekotekina you have any idea ?

**Comment by cybertronicgames** [comment]
I can get DMC 3 running by the DMC3.PPU.SELF file only but, can't get DMC 1 or 2 booted. I have a thread issue I will list.

"DMC 1"
E {PPU[0x100000b] Thread (DMC1 RegisterTrophy) [0x005297e0]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x7975e8, arg=*0x0, options=0x1)

"DMC 2"
E {PPU[0x1000011] Thread (Register Trophy Context Thread) [0x0001d9a4]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x5dffb0, arg=*0x0, options=0x1)

**Comment by Zangetsu38** [comment]
normal, this game need gcm

**Comment by M9k** [comment]
Now the game boot and work at stable 60fps, but a lot of times DMC3 stuck in loading screen or black screen, maybe a problem with some mutex or synchronization?
