### ISSUE TITLE
All game saves are considered broken

### ISSUE THREAD

**Issue by deadair3210** [RPCS3/rpcs3#2741]
Exactly what it says on the tin, the emulator in the log claims that all game saves are considered broken and in fact the saves do not work if the game is reloaded. 

Using emulator : rpcs3-v0.0.2-2017-04-29-86d864e3_win64

I have attempted to save in Disagea D2, Minecraft, Metel Slug 3, and many others

**Comment by Zangetsu38** [comment]
no real error, just ignore that

**Comment by deadair3210** [comment]
I'm almost sure there is something behind that error, as none of the saves end up working or even appearing in some cases if the game is rebooted

**Comment by kd-11** [comment]
Some types of saves are not fully supported atm. Saves do work for alot of games though.
