### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#2746]
Do you have a plan for making official Ubuntu PPA repositories? Maybe even two of them, "stable" and "testing", as [PCSX2](https://launchpad.net/~gregory-hainaut/+archive/ubuntu/pcsx2.official.ppa) and [PPSSPP](https://launchpad.net/~ppsspp/+archive/ubuntu/stable) have.

**Comment by hcorion** [comment]
The current plan is to support AppImages, which is more cross-distro.

**Comment by XenonPK** [comment]
Once cmake is ready I think it would be trivial to create an OBS repo for all the major distributions, I already got it packaged for openSUSE, it's a matter of seeing the equivalent dependencies for fedora and two major distros would be covered. As for debs, I really have no experience with them, but, at least for .rpm based distros, feel free to use my [specfile](https://build.opensuse.org/package/show/home:xenonpk/RPCS3) to get something started.
Also, I think OBS supports building [appimages](http://discourse.appimage.org/t/appimage-obs-integration/153) too? If so, I guess that would cover all of the "software distribution" problem on the linux side.

**Comment by scribam** [comment]
AppImage has been added, is it be still relevant to work on this issue?

**Comment by AniLeo** [comment]
We don't provide stables, only latest builds which are nightlies. 
Providing an Ubuntu PPA isn't needed anymore because we're providing AppImages now.

**Comment by lvonasek** [comment]
With PPA there would be automatic updates which is better

**Comment by scribam** [comment]
Hmm, how often an update on the PPA is expected ? After every update on master or when the release number increased ?

**Comment by lvonasek** [comment]
on the release number increase

**Comment by hcorion** [comment]
RPCS3 is not in a position where updating on the release number makes sense. Development is moving too rapidly. I don't want to deal with providing support for users who are on original 0.0.3. 

IMO if we do have a PPA it should be nightly.

**Comment by scribam** [comment]
Found this PPA: https://launchpad.net/~samoilov-lex/+archive/ubuntu/retrogames/?field.series_filter=bionic

**Comment by dio-gh** [comment]
Outdated ticket, closable.

**Comment by AniLeo** [comment]
Closed as we already have AppImages that support many distros and we don't plan on doing distro specific packaging
