### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by killkong1211** [RPCS3/rpcs3#2747]
Not sure why this happened, only just set up so bear with me if I'm not too familiar with RPCS3 intricacies.

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 000000000cb83000 at 0000000000109210.
Instruction address: 0000000000109210.
Function address: 00000000001091ea (base+0xf91ea).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

**Comment by AniLeo** [comment]
Please use the forums for support as explained on contributing.md guidelines. A full log will also be needed.

**Comment by AniLeo** [comment]
Approved
