### ISSUE TITLE
Cmake error on linux

### ISSUE THREAD

**Issue by logos88** [RPCS3/rpcs3#2751]
CMake Error at CMakeLists.txt:56 (add_subdirectory):
  add_subdirectory given source "3rdparty/hidapi/linux" which is not an
  existing directory.

#2733

**Comment by AniLeo** [comment]
Did you update submodules

**Comment by hcorion** [comment]
`git submodule update --init` ;) it happens to the best of us

**Comment by hcorion** [comment]
OHHHH, your using the archlinux package, you need to contact the maintainer of the PKGBUILD to add 3rdparty/hidapi

**Comment by logos88** [comment]
Oks, thanks @hcorion . Since it's related to the aur package I close the issue then.

**Comment by W4U-TOURS** [comment]
And what about Ubuntu Zesty for the same error please ?

CMake Error at CMakeLists.txt:56 (add_subdirectory):
  add_subdirectory given source "3rdparty/hidapi/linux" which is not an
  existing directory.

**Comment by hcorion** [comment]
@W4U-TOURS `git submodule update --init`
