### ISSUE TITLE
[Fixed]Unrecognizable error when loading game

### ISSUE THREAD

**Issue by TheProgramerEX** [RPCS3/rpcs3#2753]
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/979937/RPCS3.txt)

EDIT: OK, so because I had no audio device, both xaudio and openAL made the game crash. fixed by setting it to null.

Hi! When I Try to load persona 5, I get this error:

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 000000000f0e0090 at 000000000106e046.
Instruction address: 000000000106e046.
Function address: 000000000106df70 (base+0x105df70).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

I looked up the unhandled Win 32 exception issue and this is what I found on Microsoft support: This issue occurs because of a race condition. When a thread tries to close the handle to an object that is being destroyed, the operation fails.
![capture](https://cloud.githubusercontent.com/assets/21089275/25757836/271096fa-319a-11e7-886d-fdafff802caa.JPG)

And I have a Quardo K22000. Could you guys tell me what's going on? Thanks!
![config1](https://cloud.githubusercontent.com/assets/21089275/25758697/8905b32e-319d-11e7-8d85-c56dae405f61.JPG)
![config2](https://cloud.githubusercontent.com/assets/21089275/25758701/8b0aa4cc-319d-11e7-84fb-39c7b48a3e70.JPG)
![config3](https://cloud.githubusercontent.com/assets/21089275/25758703/8c46b22c-319d-11e7-944a-ec1fc6cf3b02.JPG)
![config4](https://cloud.githubusercontent.com/assets/21089275/25758705/8e5d818a-319d-11e7-898a-fbecaded7183.JPG)

EDIT: Added log file plus added config info and tried with both both Interpreters (fast) and 1280x720 with openGL. 

could it be because i'm not using it in administrator mode?

**Comment by AniLeo** [comment]
This just means something went terrible wrong, can be caused by many issues. Needs a log file and further description of the issue as explained on repo guidelines

**Comment by AniLeo** [comment]
·E 0:00:01.033363 {Audio Thread} XAudio2Thread : **CreateMasteringVoice() failed(0x88960001)**

Try OpenAL in Audio just to make sure

**Comment by TheProgramerEX** [comment]
Hello! Thanks for responding to me! Unfortunately I will not be able to access the computer that had an error for 3 days, when I can get back to it I can tell you the results.

And I was trying the lagacy opengl drivers because I was checking if changing any of the settings would fix the problem.

**Comment by TheProgramerEX** [comment]
Ok, so because I had no audio device, both xaudio and openAL made the game crash. fixed by setting it to null. Thank you!

**Comment by Derieri** [comment]
Hi, I have the same issue, and I tried the solution you gave, but it still doesn't word :(

**Comment by AniLeo** [comment]
This is not the place for Support.
