### ISSUE TITLE
Journey [NPUA80275] Error after intro screen

### ISSUE THREAD

**Issue by dareres** [RPCS3/rpcs3#2754]
After intro screens it giving an error but there is no such file.  C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1611

Log : https://pastebin.com/wdy3wpn8

I'm trying to run at DX11 and i use these libraries
![2017-05-06_07-34-39](https://cloud.githubusercontent.com/assets/28464025/25767733/95c0c89c-322e-11e7-9091-d1e1e00e44fb.jpg)

**Comment by AniLeo** [comment]
That's a not a log, that's copy paste from resumed output. Full log file is RPCS3.log

**F {SPU[0x2000002] Thread (CellSpursKernel2)} class std::runtime_error thrown: Halt**
(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1611)

There is no DX11 render and you should have sprx libraries after installing firmware and not prx libraries, then you can use auto library loading or liblv2. You did something wrong when setting it up. But Journey doesn't work yet as you can see on the forum thread for it.

As stated on the guidelines, please use the forums to report game statuses or ask for support.
