### ISSUE TITLE
GL/Vulkan: Heavy Rain - rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2756]
Tested by https://github.com/RPCS3/rpcs3/commit/b9ebf595e6588054fdedb482f1b9039555de70ca

@kd-11 
GL and VK have the same issues with the exception of blurring, main menu issues it's only with ogl.

[LOG](https://mega.nz/#!LZt1HZ6S!F1ip0CahNP3jik_bQmf0XwUf6wVZ84nxmvWxNlmNtDM)

**Main menu issue:**
![heavy 1](https://cloud.githubusercontent.com/assets/11453507/25771547/454f332c-3255-11e7-96ef-73425d26ffdb.PNG)
[RenderDoc](https://mega.nz/#!2cVmXCSY!FpoVH1qC2gGoSOeeM2XiIz9pUSLN1YZ-vadrdP9qAWc)

**Missing textures, enviroment:**
![heavy 2](https://cloud.githubusercontent.com/assets/11453507/25771548/454fc4c2-3255-11e7-93a1-740a0dd37d92.PNG)
[RenderDoc](https://mega.nz/#!HBFTTKbb!jQI74baFV-oFu70tmpM_8m-PcbKeUMABAPeicErf1BU)

**Blurred screen:**
![heavy 3](https://cloud.githubusercontent.com/assets/11453507/25771550/45536d48-3255-11e7-9bbb-f3686738492c.PNG)
[RenderDoc](https://mega.nz/#!PJlWUTzC!8rQyj9t8hwMaIQg0V-jt5RcTDYrp9Nl0bHYuM-MRCJg)

**corrupted textures (detective's coat):**
![heavy 4](https://cloud.githubusercontent.com/assets/11453507/25771549/455126fa-3255-11e7-9315-a0b4be90e1fe.PNG)
[RenderDoc](https://mega.nz/#!iFlUyDpT!U0mVa9m60D2OrQyaqwz85lwv-8vAzyWAoZc2uL8gCMo)

**Videos**
[ogl](https://www.youtube.com/watch?v=UyKw8def_rI&t=25s)
[vk1](https://www.youtube.com/watch?v=npyY5FxB6Qw&t=25s)
[vk2](https://www.youtube.com/watch?v=0DxCedGl-y0&t=25s)
[vk3](https://www.youtube.com/watch?v=_uwc2waCfxY&t=25s)

**Comment by JohnGodgames** [comment]
upps

**Comment by kd-11** [comment]
Still an issue?

**Comment by Josivan88** [comment]
@kd-11 I can confirm that this problem persists until now 10/02/2018 with the most recent build.

**Comment by kd-11** [comment]
These issues were fixed a few months ago. Request to reopen if not the case.
