### ISSUE TITLE
Running Persona 5

### ISSUE THREAD

**Issue by Thedocz** [RPCS3/rpcs3#2757]
console only showing:
E {PPU[0x1000011] Thread (game contents hdd install) [0x0123e518]} 'cellFsStat' failed with 0x8001003a : CELL_ENOTMOUNTED
Settings:
![screenshot_18](https://cloud.githubusercontent.com/assets/25303567/25772342/f30105d2-3268-11e7-9f37-5224befa46e2.png)

![screenshot_17](https://cloud.githubusercontent.com/assets/25303567/25772336/dd14e0a4-3268-11e7-9f88-fb56b8b3a1d9.png)

**Comment by raven02** [comment]
Have you tried the latest build ? you build seems to be old one

**Comment by AniLeo** [comment]
That's probably because you installed cfw "fixes" for pirated game and jap voice dlc. 
Nevertheless, please follow the repository guidelines and use the forums for support.
