### ISSUE TITLE
Nothing happens when I try to boot Devil May Cry HD Collection

### ISSUE THREAD

**Issue by rroylance** [RPCS3/rpcs3#2758]
I have placed my BLES01228 folder into /dev_hdd0/game/ it shows up properly in the games list, however when i try and boot it nothing happens other than RPCS3 seems to lock up for a second (presumably because it was trying to load the game), no messages in the log, nothing.

Any ideas?

Here is my [RPCS3.log](https://github.com/RPCS3/rpcs3/files/980975/RPCS3.txt).

And my settings;
![core](https://cloud.githubusercontent.com/assets/17881010/25773040/83390070-3244-11e7-84f0-3572a0a64125.PNG)
![graphics](https://cloud.githubusercontent.com/assets/17881010/25773043/84ac1ab4-3244-11e7-910a-1c0d046425a3.PNG)
![audio](https://cloud.githubusercontent.com/assets/17881010/25773044/85fa8590-3244-11e7-8469-46f42084d90d.PNG)

**Comment by AniLeo** [comment]
Please use the forums for support as explained on the repository guidelines.
Generally you should always try OpenGL and both interpreters first.

The Forum thread for that game though explains specific steps that need to be made for the game to run.

**Comment by rroylance** [comment]
@AniLeo Whoops. My bad. I'll take a look over there!
