### ISSUE TITLE
Vulkan : DBZ Burst Limit - black textures

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2759]
It is Vulkan specific (GL and DX12 both good)

![untitled](https://cloud.githubusercontent.com/assets/3000282/25773435/e161ce6e-32af-11e7-819f-d3e400f5fb14.jpg)

**Comment by raven02** [comment]
It is still happening in latest build 

![untitled](https://user-images.githubusercontent.com/3000282/28166848-1e44417c-680c-11e7-97a4-41fff228c25d.jpg)

**Comment by kd-11** [comment]
Retest

**Comment by kd-11** [comment]
Reopen if issue is still present.

**Comment by raven02** [comment]
Confirmed issue fixed.
