### ISSUE TITLE
Can't compile - Arch Linux

### ISSUE THREAD

**Issue by C0rn3j** [RPCS3/rpcs3#2763]
This project used to compile OK - not anymore.

I get stopped at the "cmake CMakeLists.txt && make GitVersion && make" part

https://paste.c0rn3j.com/?4d93685ae917ec57#3lJBPcDQDD6GGQHUOA57u0wv2X9O+cyvyEc5rDFft+o=

**Comment by AniLeo** [comment]
Are you using LLVM 4.0? It got updated from 3.8 this year

**Comment by C0rn3j** [comment]
✘ c0rn3j@c0rn3jDesktop  ~/rpcs3   master  pacman -Q llvm                                                                 
llvm 4.0.0-2

By the way the instructions for Arch say "Arch: sudo pacman -S glew openal wxgtk cmake llvm", but on the AUR discussion page I found out you also need `hidapi`, maybe that needs an update?

**Comment by hcorion** [comment]
Yeah, but you got llvm installed weird, look at this:

/usr/**local**/lib/cmake/llvm/LLVMExports.cmake

Normal packages don't install to `/usr/local/`, that means you have a screwed up custom llvm installed into `/usr/local`

**Comment by C0rn3j** [comment]
Thanks for pointing the /usr/local thing out. I made an ugly symlink before because of WINE and I guess it was breaking stuff. 

After removing that symlink, rpcs3 is now compiling.
