### ISSUE TITLE
Feature : CUDA , OpenCL Compute

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#2765]
Because emulator is emulate Cell Processor and Cell Processor is different and special architecture ( 1 PPE + 8 SPE ) , and i think modern CPU Intel or AMD ( Kaby Lake , Ryzen ) , does not powerful to emulate heavy game . I think you should to using GPGPU to help and improve speed emulate about that . CUDA and OpenCL is capable about to emulate Cell processor because is using parallel thread

**Comment by hcorion** [comment]
Here, let me fix your paragraph:
```
Because the PS3's processor architecture is Cell and because Cell is so different and special ( 1 PPE + 8 SPE ), I think that modern CPUs are not powerful enough to emulate more advanced games. I think you should use GPGPU (OpenCL, CUDA) to help and improve emulation speed. I think CUDA and OpenCL are good candidates to emulate the Cell processor because Cell uses parallel thread.
```

**Comment by kd-11** [comment]
Gpgpu is not suitable for all applications this is one of them. Combine that with the split memory of the pc and it quickly becomes infeasible.
Also, I dont think were even close to maxing out modern cpus. The emulator gets faster every day.

**Comment by zminhquanz** [comment]
@kd-11 persona 5 i saw test showcase is utilization CPU a lot of core , i don't think future on more advance games it emulates faster

**Comment by zminhquanz** [comment]
But at present persona 5's poor perfomance and usage a lot of core , i don't think future it's run advance games used a lot of SPU cores like GOW 3 , The Last of Us , Uncharted 2,3

**Comment by gendouhydeist** [comment]
As kd-11 explained, the emulator doesn't run based on your assumption. RPCS3 is still in early stages, and there's still a lot of things to be done.
