### ISSUE TITLE
I'm having an error each time I try to play a game on the RPCS3 emulator

### ISSUE THREAD

**Issue by RadonBlade** [RPCS3/rpcs3#2766]
I keep getting the messages in the red there. [My issue](https://cloud.githubusercontent.com/assets/28554141/25835562/a8be7a40-344d-11e7-98c0-c6fc22bea5f8.PNG)
It keeps failing to boot. What am I doing wrong?

**Comment by hcorion** [comment]
Hi!
This is a issue tracker for developers. Please close this issue.
For support you can visit the Discord channel: https://discord.me/RPCS3 or the forums: http://www.emunewz.net/forum/forumdisplay.php?fid=172

This looks like a problem with how you setup RPCS3, please follow ALL of the instructions here: https://rpcs3.net/quickstart and if you still have issues, ask over in Discord or the forums (linked above).

**Comment by AniLeo** [comment]
SLUS is not a PS3 game. You can't play non-PS3 games on RPCS3.

Please read the repository guidelines before submitting issues.
