### ISSUE TITLE
Hatsune Miku Project DIVA f2nd: Incorrect Analog Inputs

### ISSUE THREAD

**Issue by deadair3210** [RPCS3/rpcs3#2768]
Game boots fine, but when the user gets to the game menu after the title screen, all the menu will do is zoom in and spin the character, the user has to hold back both analogs to make the spinning stop and for the menu to zoom out

Version : rpcs3-v0.0.2-2017-05-07-c8b64ecb_win64

**Comment by AniLeo** [comment]
It's known, there is already an issue for it

**Comment by deadair3210** [comment]
Alright, sorry
