### ISSUE TITLE
Intel/Vulkan:rpcs3 stopped after choosing vulkan

### ISSUE THREAD

**Issue by Pixelw** [RPCS3/rpcs3#2771]
I run rpcs3 0.0.2-4852 on Windows 10 1703, with i7 4770 and HD 4600 GPU. Only D3D12 works,but only at 15fps when running project diva f.Once I switch render to vulkan and boot the game, rpcs3 stopped immediatey.
The video driver is the latest, everything lists in the QuickStarts are installed or done.

**Comment by Pixelw** [comment]
no console output, the program stopped immediately.

**Comment by Pixelw** [comment]
HD4600 supports vulkan.

**Comment by hcorion** [comment]
Make sure your graphics drivers are up to date, have you tried the OpenGL, does that work?

**Comment by AniLeo** [comment]
Can you run Vulkaninfo / Vulkan cube sample?

**Comment by Pixelw** [comment]
{
F {rsx::thread} class std::runtime_error thrown: Failed to initialize OpenGL renderer. ARB_texture_buffer_object is required but not supported by your GPU
}
console outputs when using OpenGL.

Stopped immediately when booting with Vulkan.

Same thing happens whatever you boot the game or test program

Here are some screenshots: (unsorted...sorry)
![12](https://cloud.githubusercontent.com/assets/27913491/25892046/b9f56658-35a5-11e7-861d-bfeaf9b96a2f.png)
![13](https://cloud.githubusercontent.com/assets/27913491/25892047/ba39896e-35a5-11e7-8464-a2e9b1fb5376.png)
![14](https://cloud.githubusercontent.com/assets/27913491/25892044/b9f4ade4-35a5-11e7-9f88-a3f6ae05a12b.png)
![15](https://cloud.githubusercontent.com/assets/27913491/25892045/b9f4c2f2-35a5-11e7-81a4-021c18176af6.png)

I'm Chinese,using a Chinese system, but it works fine with another PC with a NVIDIA graphic card. 

Sorry for my poor English.

**Comment by Pixelw** [comment]
I am sorry I don't know how to get Vulkan sample here, could anyone tell me what to do? I don't have IDE on this PC.

**Comment by AniLeo** [comment]
Yeah, Intel integrated graphics are not properly supported yet. Either your gpu doesn't support that extension or the driver is wrongly reporting such fact. 
You should use a dedicated gpu.

**Comment by pal1000** [comment]
Made some searches in Intel Download Center and it appears that only Skylake and Kaby Lake support Vulkan and only with driver branch 15.45.

**Comment by AniLeo** [comment]
Will be closing this since your integrated card/drivers lack Vulkan support and therefore it obviously won't work.

It also seems to lack a required OpenGL extension or the drivers are misreporting it. Intel drivers are not properly supported because they are bad. 
You'll be better off using some random dedicated GPU that supports OGL 4.3 or above.

Please use the forums if you need further support.
