### ISSUE TITLE
Catherine Black Screen

### ISSUE THREAD

**Issue by Taschenfueller** [RPCS3/rpcs3#2775]
I have a problem when i start catherine it wont start and it have black screen.
This is the log:
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: JIT initialized (haswell)
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-10200-98C15AA37D8E5A0D.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-124F98-0F8A609E4EE3EC19.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-283D08-D5DF0F8754971CB6.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-319998-56BBEB9648A3AF9F.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-40D4F8-BEF640327100ECED.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-4F34D8-C96DDE8C598949F1.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-59C3D0-2FF80CDBD8BC1D55.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-6625D0-27AF7F87FFC5D130.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-7B0194-609A0096CA2E51FC.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-895670-CDB6A0419D6290EE.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-9C72AC-988D8A49983FF5D9.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-A54CDC-86D5A409C6E0CFCF.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-AB0A80-9EBEDF82B2DC1750.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-B0673C-47A0F396E86E5837.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-B27D98-AB57E9EA7A2EE22F.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-B72A18-A0C7AB78D7079F8C.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-C245EC-C12891E0C7C26421.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-libresc.prx-0F5ABD88A359E7DD.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-librtc.prx-C804086ADDE4E2C3.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-libspurs_jq.prx-DD97CB94B36F95CD.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded executable: v1-libsre.prx-BA75A60C66E7F0FC.obj
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00010240]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
S {SPU[0x2000000] Thread (CellSpursKernel0)} SPU: SPU Database initialized...
S {SPU[0x2000000] Thread (CellSpursKernel0)} SPU: Function detected [0x00818-0x0084c] (size=0x34)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: SPU Recompiler (ASMJIT) created...
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x006c0-0x00818] (size=0x158)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x00a00-0x01230] (size=0x830)
E {PPU[0x1000000] Thread (main_thread) [0x00010240]} sys_fs: sys_fs_open(“/host_root/C:/Users/U/Desktop/PS3 Emu/dev_hdd0/game/BLUS30428-[Catherine]/PS3_GAME/USRDIR/cmdline.txt”): failed to open file (flags=0, mode=0)
E {PPU[0x1000000] Thread (main_thread) [0x00010240]} 'cellFsOpen' failed with 0x80010006 : CELL_ENOENT
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x01230-0x01470] (size=0x240)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x01d88-0x0215c] (size=0x3d4)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x01c00-0x01d88] (size=0x188)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x02630-0x0284c] (size=0x21c)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x028d0-0x029ac] (size=0xdc)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x01470-0x01600] (size=0x190)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x01600-0x01984] (size=0x384)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x02868-0x028cc] (size=0x64)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x00290-0x006c0] (size=0x430)
S {SPU[0x2000004] Thread (CellSpursKernel4)} SPU: Function detected [0x02850-0x02868] (size=0x18)
S {SPU[0x2000004] Thread (CellSpursKernel4)} SPU: Function detected [0x00808-0x00818] (size=0x10)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x00a00-0x00b00] (size=0x100)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x02aa0-0x02c70] (size=0x1d0)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x04438-0x044f8] (size=0xc0)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x045d0-0x045dc] (size=0xc)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x03d00-0x03d38] (size=0x38)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x03bb8-0x03be8] (size=0x30)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x03dd8-0x03e8c] (size=0xb4)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x01450-0x02a9c] (size=0x164c)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x044f8-0x045d0] (size=0xd8)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x03578-0x03b28] (size=0x5b0)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x00a30-0x00b00] (size=0xd0)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x033d8-0x03574] (size=0x19c)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x02d40-0x033d8] (size=0x698)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x00b00-0x00c68] (size=0x168)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x045f8-0x0465c] (size=0x64)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x01430-0x01450] (size=0x20)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x045e0-0x045f8] (size=0x18)
S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: Function detected [0x00cc8-0x01230] (size=0x568)
E {PPU[0x1000000] Thread (main_thread) [0x00010240]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} sceNp TODO: sceNpManagerRegisterCallback(callback=*0xde4b00, arg=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} cellNetCtl TODO: cellNetCtlAddHandler(handler=*0xde4b10, arg=*0x0, hid=*0xf5909c)
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0xd0010850, options=0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00010240]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x00010240]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x00010240]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (11)
S {Audio Thread} XAudio 2.9 initialized
U {PPU[0x1000000] Thread (main_thread) [0x00010240]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x000f0-0x00178] (size=0x88)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00090-0x000e0] (size=0x50)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x15470-0x1547c] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x15448-0x15470] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x15328-0x15334] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x15300-0x15328] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x14eb0-0x14ebc] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x14e88-0x14eb0] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x149a0-0x149ac] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x14978-0x149a0] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x14438-0x14444] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x14410-0x14438] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0d870-0x0d87c] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0d848-0x0d870] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0c9e0-0x0c9ec] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0c9b8-0x0c9e0] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0c358-0x0c364] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0c330-0x0c358] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0baf8-0x0bb04] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0bad0-0x0baf8] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x08020-0x0802c] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x07ff8-0x08020] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x06bc8-0x06bd4] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x06ba0-0x06bc8] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x05df8-0x05e04] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x05dd0-0x05df8] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x05730-0x0573c] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x05708-0x05730] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04858-0x04864] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04830-0x04858] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04430-0x0443c] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04408-0x04430] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x037a0-0x037ac] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x03778-0x037a0] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00f50-0x00f5c] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00f28-0x00f50] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x007a0-0x007ac] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00778-0x007a0] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00520-0x0052c] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x004f8-0x00520] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x003d0-0x003e0] (size=0x10)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00398-0x003cc] (size=0x34)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x001b0-0x001c0] (size=0x10)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00178-0x001ac] (size=0x34)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x003e0-0x00420] (size=0x40)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x001d8-0x00398] (size=0x1c0)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x17830-0x17864] (size=0x34)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1ad98-0x1ada4] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1ab48-0x1abac] (size=0x64)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x176d8-0x17720] (size=0x48)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x176a8-0x176b4] (size=0xc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1abb0-0x1acac] (size=0xfc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1a828-0x1a9f8] (size=0x1d0)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x193a8-0x19418] (size=0x70)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x19348-0x1938c] (size=0x44)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x198b0-0x19900] (size=0x50)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1a7b8-0x1a828] (size=0x70)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x19cb0-0x19cf0] (size=0x40)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x176c8-0x176cc] (size=0x4)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1a7a0-0x1a7b8] (size=0x18)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x19d40-0x1a68c] (size=0x94c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x19c70-0x19cb0] (size=0x40)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x176d0-0x176d4] (size=0x4)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1c080-0x1c138] (size=0xb8)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00650-0x00714] (size=0xc4)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x19328-0x19338] (size=0x10)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x19290-0x19324] (size=0x94)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x19c20-0x19c70] (size=0x50)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04a10-0x04ad4] (size=0xc4)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x004b0-0x004ec] (size=0x3c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00420-0x004ac] (size=0x8c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00bb0-0x00d4c] (size=0x19c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x043f8-0x04408] (size=0x10)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1bc70-0x1bdb0] (size=0x140)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00880-0x0095c] (size=0xdc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x06bd8-0x06d78] (size=0x1a0)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x06b60-0x06b9c] (size=0x3c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x06ae0-0x06b5c] (size=0x7c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x176b8-0x176c0] (size=0x8)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0cd00-0x0ce14] (size=0x114)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0cca0-0x0cd00] (size=0x60)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x03248-0x03360] (size=0x118)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x01638-0x0178c] (size=0x154)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0cab0-0x0cbc0] (size=0x110)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0d9e8-0x0da98] (size=0xb0)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0d9a8-0x0d9e4] (size=0x3c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0c7c0-0x0c864] (size=0xa4)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0c868-0x0c990] (size=0x128)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0d920-0x0d928] (size=0x8)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0d8d0-0x0d920] (size=0x50)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x197d8-0x197ec] (size=0x14)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x15338-0x15384] (size=0x4c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x19250-0x19270] (size=0x20)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0ae68-0x0aea8] (size=0x40)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x18a68-0x18aac] (size=0x44)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x189d8-0x18a68] (size=0x90)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x17e08-0x17e40] (size=0x38)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0c4a8-0x0c70c] (size=0x264)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x19858-0x198ac] (size=0x54)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1a730-0x1a7a0] (size=0x70)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1a718-0x1a730] (size=0x18)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0d880-0x0d8d0] (size=0x50)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x15388-0x15444] (size=0xbc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0ba78-0x0bac8] (size=0x50)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0bac8-0x0bad0] (size=0x8)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x17c28-0x17c6c] (size=0x44)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x17b70-0x17c28] (size=0xb8)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1ada8-0x1adf8] (size=0x50)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0aef8-0x0afac] (size=0xb4)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0aed0-0x0aef4] (size=0x24)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0aea8-0x0aecc] (size=0x24)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0e360-0x0e388] (size=0x28)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x014b0-0x01638] (size=0x188)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0cbc0-0x0cc1c] (size=0x5c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1a9f8-0x1aaf4] (size=0xfc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0c1f8-0x0c278] (size=0x80)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0d080-0x0d0f4] (size=0x74)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0cfd0-0x0d07c] (size=0xac)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0cf90-0x0cfcc] (size=0x3c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x02f38-0x030e4] (size=0x1ac)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0c150-0x0c1f4] (size=0xa4)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x02ba8-0x02be8] (size=0x40)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00d50-0x00dd8] (size=0x88)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x06a20-0x06ae0] (size=0xc0)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x05ba0-0x05c60] (size=0xc0)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04758-0x047e0] (size=0x88)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x06880-0x069c0] (size=0x140)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x005f8-0x00650] (size=0x58)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x05830-0x058d8] (size=0xa8)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x19338-0x19348] (size=0x10)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x057d8-0x0582c] (size=0x54)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x05118-0x0527c] (size=0x164)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x05740-0x057d4] (size=0x94)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x070c8-0x07154] (size=0x8c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x07158-0x071e4] (size=0x8c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04ad8-0x04c94] (size=0x1bc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x071e8-0x07238] (size=0x50)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1e200-0x1e258] (size=0x58)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04680-0x04700] (size=0x80)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04560-0x045fc] (size=0x9c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x041f0-0x04260] (size=0x70)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x042e8-0x04368] (size=0x80)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x009c8-0x00aac] (size=0xe4)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x009b8-0x009c8] (size=0x10)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x03360-0x03634] (size=0x2d4)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0cc30-0x0cca0] (size=0x70)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1bdb0-0x1bf60] (size=0x1b0)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0d0f8-0x0d168] (size=0x70)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1c138-0x1c17c] (size=0x44)
U {PPU[0x1000000] Thread (main_thread) [0x00aea8f8]} cellFont TODO: cellFontSetResolutionDpi
U {PPU[0x1000000] Thread (main_thread) [0x00aea8f8]} cellFont TODO: cellFontSetScalePoint
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0d168-0x0d228] (size=0xc0)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0c278-0x0c288] (size=0x10)
U {PPU[0x1000000] Thread (main_thread) [0x00aea8f8]} cellFont TODO: cellFontSetResolutionDpi
U {PPU[0x1000000] Thread (main_thread) [0x00aea8f8]} cellFont TODO: cellFontSetScalePoint
U {PPU[0x1000000] Thread (main_thread) [0x00aea8f8]} cellFont TODO: cellFontCreateRenderer(library=*0x1ed8000, config=*0xd00107ec, Renderer=*0x24f2412c)
U {PPU[0x1000000] Thread (main_thread) [0x00aea8f8]} cellFont TODO: cellFontSetEffectWeight
U {PPU[0x1000000] Thread (main_thread) [0x00aea8f8]} cellFont TODO: cellFontGetVerticalLayout
U {PPU[0x1000000] Thread (main_thread) [0x00aea8f8]} cellFont TODO: cellFontSetupRenderScalePixel(font=*0x24f24250, w=15.000000, h=15.000000)
U {PPU[0x1000000] Thread (main_thread) [0x00aea8f8]} cellFont TODO: cellFontSetupRenderEffectWeight
U {PPU[0x1000000] Thread (main_thread) [0x00aea8f8]} cellFont TODO: cellFontSetupRenderEffectSlant
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0c2d8-0x0c2e0] (size=0x8)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x02718-0x02ba4] (size=0x48c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x01b00-0x01ba8] (size=0xa8)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0d228-0x0d2e8] (size=0xc0)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x0cc20-0x0cc30] (size=0x10)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1bf60-0x1c07c] (size=0x11c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x00960-0x009a4] (size=0x44)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x004f0-0x004f4] (size=0x4)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04810-0x04830] (size=0x20)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x053b0-0x05708] (size=0x358)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x07078-0x070c4] (size=0x4c)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x1e258-0x1e2d0] (size=0x78)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04d00-0x04d84] (size=0x84)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04c98-0x04d00] (size=0x68)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x047e0-0x04804] (size=0x24)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x065a0-0x0677c] (size=0x1dc)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x05b40-0x05b94] (size=0x54)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x05a60-0x05b40] (size=0xe0)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x059e0-0x05a60] (size=0x80)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04750-0x04754] (size=0x4)
S {SPU[0x2000005] Thread (CriSr thread)} SPU: Function detected [0x04700-0x04750] (size=0x50)
U {PPU[0x1000000] Thread (main_thread) [0x00350df0]} cellFont TODO: cellFontSetupRenderScalePixel(font=*0x24f24250, w=15.000000, h=15.000000)
U {PPU[0x1000000] Thread (main_thread) [0x00350df0]} cellFont TODO: cellFontSetupRenderEffectWeight
U {PPU[0x1000000] Thread (main_thread) [0x00350df0]} cellFont TODO: cellFontSetupRenderEffectSlant
F {PPU[0x1000000] Thread (main_thread) [0x00350df0]} MEM: Access violation writing location 0x762

**Comment by AniLeo** [comment]
Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue
