### ISSUE TITLE
Infamous 2 doesn't start

### ISSUE THREAD

**Issue by Trender07** [RPCS3/rpcs3#2783]
The game doesn't start, its a ps3_game folder. I get this on the log:
U {PPU[0x1000000] Thread (main_thread) [0x00b34010]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x00b34018]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00b33d90]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00b33d90]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00b33d90]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00b33d90]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
F {PPU[0x1000000] Thread (main_thread) [0x0013235c]} MEM: Access violation reading location 0x0
**

**

**Comment by AniLeo** [comment]
Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.
