### ISSUE TITLE
Infamous 2 doesn't start

### ISSUE THREAD

**Issue by Trender07** [RPCS3/rpcs3#2784]
The game doesn't start, its a ps3_game folder. I get this on the log:
U {PPU[0x1000000] Thread (main_thread) [0x00b34010]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x00b34018]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00b33d90]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00b33d90]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
U {PPU[0x1000000] Thread (main_thread) [0x00bc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00b33d90]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00b33d90]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
F {PPU[0x1000000] Thread (main_thread) [0x0013235c]} MEM: Access violation reading location 0x0
**

**
CPU: Ryzen 1700
GPU: RX 480
OS: Windows 10
[rpcs3log.txt](https://github.com/RPCS3/rpcs3/files/999487/rpcs3log.txt)

**Comment by AniLeo** [comment]
**The GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports.**

**Submitting your test results for Commercial Games must be done on our forums' Commercial Games section. If there's already a thread for the game you want to report post in it, otherwise please make a new thread following the Guidelines for submitting new games.**

https://rpcs3.net/compatibility?g=infamous+2
