### ISSUE TITLE
Error when trying to boot a game

### ISSUE THREAD

**Issue by youngtomlin** [RPCS3/rpcs3#2789]
Hello

Sorry, but I am new to this and I have no idea what to do? Please be kind :)

When trying to boot GT5, I get this error

https://pastebin.com/QZDick1G

What do I do now? Sorry for the inexperience, thanks for any help!

**Comment by AniLeo** [comment]
Hello,

Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.

Use our forums for support
