### ISSUE TITLE
Katamari Forever

### ISSUE THREAD

**Issue by tetraguardian** [RPCS3/rpcs3#2790]
I'm running the newest build for rpcs3 and latest firmware for ps3.  The game gets to this screen but then doesn't load anything else.
![image](https://cloud.githubusercontent.com/assets/10821582/26178708/4f94df7c-3b14-11e7-9234-262c4dc7ddab.png)
It doesn't really freeze though, it just doesn't load anything else.

Here's my log any suggestions if you have time would be awesome.
Thanks!

RPCS3 v0.0.2-3-b9ebf59 Alpha
U {PPU[0x1000000] Thread (main_thread) [0x00c9cbf8]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00800010]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x00800018]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x007ffd90]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x007ffd90]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
E {PPU[0x1000000] Thread (main_thread) [0x007fb1b8]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x007fb1b8]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x007fb1b8]} cellGcmSys: cellGcmSetTile: bad compression mode! (9)
U {PPU[0x1000000] Thread (main_thread) [0x007ff0d0]} sceNp TODO: sceNpManagerRegisterCallback(callback=*0x5a7070, arg=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x007fed98]} sceNp TODO: sceNpBasicRegisterHandler
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x007ffd90]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x007ffd90]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} sys_fs: sys_fs_open(“/dev_flash/data/font/SCE-PS3-RD-R-LATIN.ccd”): failed to open file (flags=0, mode=0)
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} sys_fs: sys_fs_open(“/dev_flash/data/font/SCE-PS3-NR-R-JPN.ccd”): failed to open file (flags=0, mode=0)
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} sys_fs: sys_fs_open(“/dev_flash/data/font/SCE-PS3-YG-R-KOR.ccd”): failed to open file (flags=0, mode=0)
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} sys_fs: sys_fs_open(“/dev_flash/data/font/SCE-PS3-DH-R-CGB.ccd”): failed to open file (flags=0, mode=0)
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000007] Thread (GDV::RequestPool::Thread00) [0x007ff9f0]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x5a6fd0, arg=*0x7e8f28, options=0x0)

**Comment by tetraguardian** [comment]
Here's current test with diff config
![image](https://cloud.githubusercontent.com/assets/10821582/26179100/678c9460-3b16-11e7-9444-deea2b6e988c.png)

RPCS3 v0.0.2-3-b9ebf59 Alpha
U {PPU[0x1000000] Thread (main_thread) [0x00c9cbf8]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00800010]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x00800018]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x007ffd90]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: SPU Database initialized...
E {PPU[0x1000000] Thread (main_thread) [0x007ffd90]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x00818-0x0084c] (size=0x34)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: SPU Recompiler (ASMJIT) created...
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x006c0-0x00818] (size=0x158)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x00a00-0x01230] (size=0x830)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x01230-0x01470] (size=0x240)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x01d88-0x0215c] (size=0x3d4)
E {PPU[0x1000000] Thread (main_thread) [0x007fb1b8]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x007fb1b8]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x007fb1b8]} cellGcmSys: cellGcmSetTile: bad compression mode! (9)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x01c00-0x01d88] (size=0x188)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x02630-0x0284c] (size=0x21c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x028d0-0x029ac] (size=0xdc)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x01470-0x01600] (size=0x190)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x01600-0x01984] (size=0x384)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x02868-0x028cc] (size=0x64)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x00290-0x006c0] (size=0x430)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x02850-0x02868] (size=0x18)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x00808-0x00818] (size=0x10)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x00a00-0x00c3c] (size=0x23c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x01e60-0x01eac] (size=0x4c)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x00a00-0x00b00] (size=0x100)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x023fc-0x024d8] (size=0xdc)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x01338-0x01350] (size=0x18)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x01730-0x01e60] (size=0x730)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x02aa0-0x02c70] (size=0x1d0)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x00e40-0x01338] (size=0x4f8)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x02320-0x023fc] (size=0xdc)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x01eb0-0x0229c] (size=0x3ec)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x024d8-0x02590] (size=0xb8)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x04438-0x044f8] (size=0xc0)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x045d0-0x045dc] (size=0xc)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x021ec-0x0229c] (size=0xb0)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x021d0-0x021ec] (size=0x1c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x020b4-0x021d0] (size=0x11c)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x03d00-0x03d38] (size=0x38)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x02200-0x0229c] (size=0x9c)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x03bb8-0x03be8] (size=0x30)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x00c40-0x00e3c] (size=0x1fc)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x03dd8-0x03e8c] (size=0xb4)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x03070-0x030b8] (size=0x48)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x01450-0x02a9c] (size=0x164c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x03010-0x03060] (size=0x50)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x044f8-0x045d0] (size=0xd8)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x13990-0x139a0] (size=0x10)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x03578-0x03b28] (size=0x5b0)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x13938-0x1398c] (size=0x54)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x00a30-0x00b00] (size=0xd0)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x128d8-0x128e8] (size=0x10)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x033d8-0x03574] (size=0x19c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x12880-0x128d4] (size=0x54)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x02d40-0x033d8] (size=0x698)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x11db8-0x11dc8] (size=0x10)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x00b00-0x00c68] (size=0x168)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x11d60-0x11db4] (size=0x54)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x045f8-0x0465c] (size=0x64)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10da8-0x10db8] (size=0x10)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x040e8-0x04434] (size=0x34c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10d50-0x10da4] (size=0x54)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x03be8-0x03d00] (size=0x118)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10d40-0x10d50] (size=0x10)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x00ef8-0x01370] (size=0x478)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10c10-0x10d40] (size=0x130)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x04c00-0x04c20] (size=0x20)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10be0-0x10bf0] (size=0x10)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x04c88-0x05248] (size=0x5c0)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10b88-0x10bdc] (size=0x54)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x04d18-0x05248] (size=0x530)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10698-0x106a8] (size=0x10)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x04d10-0x04d18] (size=0x8)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10608-0x10694] (size=0x8c)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x05248-0x057fc] (size=0x5b4)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10260-0x10270] (size=0x10)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x03e90-0x03fa4] (size=0x114)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x0ffe8-0x10260] (size=0x278)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x03b48-0x03bb4] (size=0x6c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x03b18-0x03b28] (size=0x10)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x01430-0x01450] (size=0x20)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x03ac0-0x03b14] (size=0x54)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x045e0-0x045f8] (size=0x18)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x139a0-0x139e8] (size=0x48)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x00cc8-0x01230] (size=0x568)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x12c20-0x12c88] (size=0x68)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x137c0-0x13938] (size=0x178)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x157f8-0x15cec] (size=0x4f4)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x00a70-0x00c3c] (size=0x1cc)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x01c10-0x01e60] (size=0x250)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x014a0-0x01730] (size=0x290)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x01350-0x0139c] (size=0x4c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x022b8-0x0231c] (size=0x64)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x013a0-0x014a0] (size=0x100)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x022a0-0x022b8] (size=0x18)
U {PPU[0x1000000] Thread (main_thread) [0x007ff0d0]} sceNp TODO: sceNpManagerRegisterCallback(callback=*0x5a7070, arg=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x007fed98]} sceNp TODO: sceNpBasicRegisterHandler
U {PPU[0x1000000] Thread (main_thread) [0x00cd3d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x007ffd90]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x007ffd90]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x021f0-0x02200] (size=0x10)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x03050-0x03098] (size=0x48)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x03010-0x03040] (size=0x30)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x11200-0x1132c] (size=0x12c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x13098-0x130d0] (size=0x38)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x14e20-0x150e4] (size=0x2c4)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x150e8-0x15150] (size=0x68)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x14620-0x147ac] (size=0x18c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x107d0-0x1089c] (size=0xcc)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x131c0-0x13218] (size=0x58)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10008-0x10164] (size=0x15c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10c40-0x10d0c] (size=0xcc)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x13218-0x13280] (size=0x68)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x108a0-0x109ac] (size=0x10c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x113d0-0x115e0] (size=0x210)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x13058-0x13098] (size=0x40)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x12f40-0x12f98] (size=0x58)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x13c20-0x13cd8] (size=0xb8)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x12f98-0x12fc0] (size=0x28)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10da8-0x10fa4] (size=0x1fc)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10fa8-0x11038] (size=0x90)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x16ea0-0x17394] (size=0x4f4)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x17398-0x17700] (size=0x368)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x11e78-0x12e54] (size=0xfdc)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x115e0-0x11e78] (size=0x898)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x110b8-0x110c0] (size=0x8)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x11038-0x1106c] (size=0x34)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x110c0-0x110ec] (size=0x2c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x11080-0x110b4] (size=0x34)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x109b0-0x109f4] (size=0x44)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x091f8-0x093c8] (size=0x1d0)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x08e98-0x08ef8] (size=0x60)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x11070-0x11080] (size=0x10)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x110f0-0x1112c] (size=0x3c)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x13018-0x13058] (size=0x40)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x12ee8-0x12f40] (size=0x58)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x16688-0x16b7c] (size=0x4f4)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x16b80-0x16ea0] (size=0x320)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x17a38-0x17a80] (size=0x48)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x172a4-0x17394] (size=0xf0)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x16fd8-0x172a4] (size=0x2cc)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x172bc-0x17394] (size=0xd8)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x112c8-0x1132c] (size=0x64)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x11278-0x112c8] (size=0x50)
S {SPU[0x2000002] Thread (gmpl_CellSpursKernel2)} SPU: Function detected [0x00b60-0x00c3c] (size=0xdc)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10ad8-0x10b1c] (size=0x44)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x093c8-0x0b448] (size=0x2080)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x130d0-0x13158] (size=0x88)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x13158-0x13190] (size=0x38)
S {SPU[0x2000001] Thread (gmpl_CellSpursKernel1)} SPU: Function detected [0x10b20-0x10b64] (size=0x44)
S {SPU[0x2000002] Thread (gmpl_CellSpursKernel2)} SPU: Function detected [0x0ba90-0x0d4a0] (size=0x1a10)
S {SPU[0x2000002] Thread (gmpl_CellSpursKernel2)} SPU: Function detected [0x0b678-0x0b708] (size=0x90)
S {SPU[0x2000002] Thread (gmpl_CellSpursKernel2)} SPU: Function detected [0x0b448-0x0b480] (size=0x38)
S {SPU[0x2000002] Thread (gmpl_CellSpursKernel2)} SPU: Function detected [0x0b708-0x0ba90] (size=0x388)
S {SPU[0x2000002] Thread (gmpl_CellSpursKernel2)} SPU: Function detected [0x15f38-0x15f68] (size=0x30)
S {SPU[0x2000002] Thread (gmpl_CellSpursKernel2)} SPU: Function detected [0x15990-0x15c60] (size=0x2d0)
S {SPU[0x2000002] Thread (gmpl_CellSpursKernel2)} SPU: Function detected [0x162d8-0x164e0] (size=0x208)
S {SPU[0x2000002] Thread (gmpl_CellSpursKernel2)} SPU: Function detected [0x15fa8-0x162d8] (size=0x330)
S {SPU[0x2000002] Thread (gmpl_CellSpursKernel2)} SPU: Function detected [0x15f68-0x15fa4] (size=0x3c)
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} sys_fs: sys_fs_open(“/dev_flash/data/font/SCE-PS3-RD-R-LATIN.ccd”): failed to open file (flags=0, mode=0)
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} sys_fs: sys_fs_open(“/dev_flash/data/font/SCE-PS3-NR-R-JPN.ccd”): failed to open file (flags=0, mode=0)
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} sys_fs: sys_fs_open(“/dev_flash/data/font/SCE-PS3-YG-R-KOR.ccd”): failed to open file (flags=0, mode=0)
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} sys_fs: sys_fs_open(“/dev_flash/data/font/SCE-PS3-DH-R-CGB.ccd”): failed to open file (flags=0, mode=0)
E {PPU[0x1000000] Thread (main_thread) [0x009ea090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000007] Thread (GDV::RequestPool::Thread00) [0x007ff9f0]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x5a6fd0, arg=*0x7e8f28, options=0x0)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x101d8-0x10268] (size=0x90)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x10420-0x104ac] (size=0x8c)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x055f0-0x05dfc] (size=0x80c)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x12fc0-0x13014] (size=0x54)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x12e58-0x12ee4] (size=0x8c)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x10268-0x102f8] (size=0x90)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x08ff0-0x091f8] (size=0x208)
S {SPU[0x2000004] Thread (gmpl_CellSpursKernel4)} SPU: Function detected [0x13280-0x13454] (size=0x1d4)

**Comment by AniLeo** [comment]
Don't forget to compress the log before uploading on the forums 

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
