### ISSUE TITLE
DX12/Vulkan Tony Hawk's Project 8

### ISSUE THREAD

**Issue by kamer1337** [RPCS3/rpcs3#2794]
DX12: 
> ·F 0:00:36.088389 {rsx::thread} class std::range_error thrown: bad conversion

[log](https://mega.nz/#!kVISUAhC!EISUIOYLRgq05FclFrCuN7CKqCsxoVUfivP-E_NAFMw)

Vulkan:
> ·E 0:00:21.114496 {rsx::thread} RSX: ERROR: [Driver] Code 0 : vkCreateImage: image creation failed due to invalid parameter
·F 0:00:21.114654 {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is C4650B07h
(in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:380)

[log](https://mega.nz/#!RUJ3mbBI!IofSaIa4_F2OzmIEhvOhj8Elt6l8yuRB7z0I2j8nztw)

**Comment by hcorion** [comment]
How about OpenGL?

**Comment by kamer1337** [comment]
OpenGl is ingame with no problems just slow
