### ISSUE TITLE
Alien Rage  ---> Failed to compile shader

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2798]
RPCS3 v0.0.2-3-d5107aa Alpha

Alien Rage [NPUB30863]

> ·W 0:02:50.732246 {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 1
·! 0:02:50.772676 {rsx::thread} RSX: FP not found in buffer!
·E 0:02:50.778356 {rsx::thread} RSX: Failed to compile shader: 0(127) : error C0000: syntax error, unexpected reserved word "break", expecting "::" at token "break"
0(128) : error C0000: syntax error, unexpected reserved word "break", expecting "::" at token "break"
0(129) : error C0000: syntax error, unexpected reserved word "break", expecting "::" at token "break"
0(130) : error C0000: syntax error, unexpected reserved word "break", expecting "::" at token "break"

![2](https://cloud.githubusercontent.com/assets/25039098/26275292/4e6ed3ae-3d72-11e7-8183-a70e9946a631.jpg)

OpenGL
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1016096/RPCS3.zip)

**Comment by kd-11** [comment]
Retry with https://github.com/RPCS3/rpcs3/pull/2803

**Comment by aakh1361** [comment]
RPCS3 v0.0.2-10-5f38098 Alpha

Before show anything on screen give me error

> F {PPU[0x100000f] Thread (RenderingThread) [0x00990674]} MEM: Access violation reading location 0x14

**OR**

> F {PPU[0x100000f] Thread (RenderingThread) [0x00990674]} MEM: Access violation reading location 0x10
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1018806/RPCS3.zip)

**Comment by aakh1361** [comment]
#2806

**Comment by kd-11** [comment]
"Break" issue is fixed with master. The mem access violation is another issue altogether. Consider closing this report if the reported bug is actually fixed.

**Comment by aakh1361** [comment]
**game don't Load** whit any build

i can't go ingame for test fix error shader
