### ISSUE TITLE
Performance difference between wx and Qt build 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2802]
**DBZ burst limit** 

QT - 60 FPS
![qt_build1](https://cloud.githubusercontent.com/assets/3000282/26281624/bad80db8-3e2f-11e7-8979-226db502c88f.jpg)

Wx - 34 FPS
![wx_build1](https://cloud.githubusercontent.com/assets/3000282/26281625/bf8f8ef8-3e2f-11e7-82b4-da5e72c964e6.jpg)

**Dai-3-Ji Super Robot Taisen Z Jigoku Hen**

QT - 30 fps
![qt_build](https://cloud.githubusercontent.com/assets/3000282/26281633/d5c509c8-3e2f-11e7-873b-cdf2b4943660.jpg)

Wx - 13 fps
![wx_build](https://cloud.githubusercontent.com/assets/3000282/26281634/ddd6b2ce-3e2f-11e7-85a2-11f2824f1f1c.jpg)

**Comment by raven02** [comment]
This is the QT build i tested and couesty of pi_rho_man on discord.

https://www.dropbox.com/s/0qjqi10frrjma6b/rpcs3qt3.zip?dl=0

**Comment by kamer1337** [comment]
what has gui to emu performance?

**Comment by raven02** [comment]
Feel to test it if you have DBZ burst limit at that scene

**Comment by kd-11** [comment]
Shouldnt have an impact unless wx was doing something in the background which is unlikely. Your frame rate in dai-3 is awfully low on wx too, I have a low end setup and get 30fps. Maybe something about your setup is affected.
If more testers encounter this, it does warrant investigation even with wx being phased out.

**Comment by raven02** [comment]
It doen't make sense that there should be big difference between wx and qt build .

**Comment by kd-11** [comment]
What other games are affected?

**Comment by raven02** [comment]
One more which is 1942 strike

**Comment by bjakja** [comment]
wxWidgets makes slowdowns when many fonts are installed in system. That's why I got bad performance on my system with 7000+ fonts. I can't wait for better build working with The Legend of Heroes Trails of Cold Steel.

**Comment by inertia0153** [comment]
It breaks Trails of Cold Steel I & II

It can't do an initial "install" of the files (no response when you press "ok" when it says "commence install")

When using a copied install game data:
PPU LLVM (LLVM CPU: sandybridge) = Freeze at start
PPU Interp + SPU Recomp = freezes after the opening cinematic
PPU Interp + SPU Interp(fast) = works normally

Tested using OGL and Vulkan

**Comment by bjakja** [comment]
It looks like this build don't save some options for example last open game folder.

**Comment by RipleyTom** [comment]
Testing the version raven02 posted earlier and Catherine crash the emulator after the initial catherine loading icon.
Tested with ppu int/spu int(fast) and both vulkan and opengl.
The emulator will also randomly freeze when trying to run a game(seems to be the case for any game).

**Comment by gendouhydeist** [comment]
#2645

**Comment by bjakja** [comment]
Tested Disgaea 4 and it works a bit faster but audio not works properly, and it freezes after about two minutes just like RipleyTom wrote.

**Comment by gendouhydeist** [comment]
#2645 Please report all your issues on this pull.

**Comment by Megamouse** [comment]
#2711 Please use this Issue for Qt related problems instead

**Comment by zminhquanz** [comment]
It very impressive and improve performance

**Comment by hcorion** [comment]
When profiling rpcs3 on linux a lot of the heavy calls where to wx functions.

**Comment by raven02** [comment]
Looks like testing the build using appveyor didn't get the performance difference now . Would it be the compilation difference between pi_rho_man own QT build and appveyor build .

**Comment by AniLeo** [comment]
There doesn't seem to be any performance difference between builds

**Comment by raven02** [comment]
I just reinstalled the Windows 10 and it looks okay now .thanks.
