### ISSUE TITLE
issue in gow3 

### ISSUE THREAD

**Issue by shahabs2** [RPCS3/rpcs3#2805]
hi guys
i downloaded gow3 and copied in dev_hdd0 and rename my gow3 folder to BCES00510 after that i boot my gmae but always see black screen.
how can i fix this  issue?
this my log when i boot gow3 : 
U {PPU[0x1000000] Thread (main_thread) [0x006a2054]} HLE TODO: Unimplemented syscall syscall_462 -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00692900]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x00692624]} sys_prx TODO: _sys_prx_register_library(library=*0x6a2178)
S {PPU[0x1000000] Thread (main_thread) [0x00691c98]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x006ac188]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x00691c98]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
U {PPU[0x1000000] Thread (main_thread) [0x006920e8]} sys_prx TODO: _sys_prx_register_module()
S {PPU[0x1000000] Thread (main_thread) [0x00691c98]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00691c98]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
E {PPU[0x1000000] Thread (main_thread) [0x001f0dbc]} sys_mmapper: sys_mmapper_allocate_address(size=0x20000000, flags=0x400, alignment=0x0, alloc_addr=*0x58a920)
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00692818]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00692818]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00692818]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00692818]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
U {PPU[0x1000000] Thread (main_thread) [0x006ee840]} HLE TODO: Unimplemented syscall sys_fs_disk_free -> CELL_OK
E {PPU[0x1000008] Thread (fios mediathread) [0x006f1b88]} sys_fs: sys_fs_opendir(“/dev_hdd0/game/BCES00510/USRDIR/DLC”): failed to open directory
E {PPU[0x1000008] Thread (fios mediathread) [0x006f1b88]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=0, offset=0x1520000, width=1280, height=768, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=1, offset=0x18c0000, width=1408, height=1408, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=3, offset=0x36d0000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=2, offset=0x37b1000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=2, offset=0x3892000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=0, offset=0x1520000, width=1280, height=768, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=1, offset=0x18c0000, width=1408, height=1408, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=3, offset=0x36d0000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=2, offset=0x37b1000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=2, offset=0x3892000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
E {PPU[0x1000008] Thread (fios mediathread) [0x006f1b88]} sys_fs: sys_fs_opendir(“/dev_bdvd/PS3_GAME/USRDIR/DLC”): failed to open directory
E {PPU[0x1000008] Thread (fios mediathread) [0x006f1b88]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT
S {Audio Thread} XAudio 2.9 initialized
U {PPU[0x1000000] Thread (main_thread) [0x006a2054]} HLE TODO: Unimplemented syscall syscall_462 -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00692900]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x00692624]} sys_prx TODO: _sys_prx_register_library(library=*0x6a2178)
S {PPU[0x1000000] Thread (main_thread) [0x00691c98]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x006ac188]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x00691c98]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
U {PPU[0x1000000] Thread (main_thread) [0x006920e8]} sys_prx TODO: _sys_prx_register_module()
S {PPU[0x1000000] Thread (main_thread) [0x00691c98]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00691c98]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
E {PPU[0x1000000] Thread (main_thread) [0x001f0dbc]} sys_mmapper: sys_mmapper_allocate_address(size=0x20000000, flags=0x400, alignment=0x0, alloc_addr=*0x58a920)
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00692818]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00692818]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
U {PPU[0x1000000] Thread (main_thread) [0x006b8c28]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00692818]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00692818]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
U {PPU[0x1000000] Thread (main_thread) [0x006ee840]} HLE TODO: Unimplemented syscall sys_fs_disk_free -> CELL_OK
E {PPU[0x1000000] Thread (main_thread) [0x004fc110]} 'cellVideoOutConfigure' failed with 0x8002b221 : CELL_VIDEO_OUT_ERROR_ILLEGAL_CONFIGURATION
E {PPU[0x1000008] Thread (fios mediathread) [0x006f1b88]} sys_fs: sys_fs_opendir(“/dev_hdd0/game/BCES00510/USRDIR/DLC”): failed to open directory
E {PPU[0x1000008] Thread (fios mediathread) [0x006f1b88]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=0, offset=0x11b0000, width=1280, height=768, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=1, offset=0x1550000, width=1408, height=1408, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=3, offset=0x3360000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=2, offset=0x3441000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=2, offset=0x3522000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x004f91c0]} cellGcmSys: cellGcmSetTile: bad compression mode! (10)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=0, offset=0x11b0000, width=1280, height=768, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=1, offset=0x1550000, width=1408, height=1408, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=3, offset=0x3360000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=2, offset=0x3441000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
U {PPU[0x1000000] Thread (main_thread) [0x004f90c0]} cellGcmSys TODO: cellGcmSetZcull(index=2, offset=0x3522000, width=640, height=384, cullStart=0xf0000, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x203, sRef=0x80, sMask=0xff)
E {PPU[0x1000008] Thread (fios mediathread) [0x006f1b88]} sys_fs: sys_fs_opendir(“/dev_bdvd/PS3_GAME/USRDIR/DLC”): failed to open directory
E {PPU[0x1000008] Thread (fios mediathread) [0x006f1b88]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT
S {Audio Thread} XAudio 2.9 initialized
plz help me.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
