### ISSUE TITLE
GL/Vulkan: Grid graphical issues

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2807]
This game has scaling problems and graphical glitches.

Tested in https://github.com/RPCS3/rpcs3/commit/5f38098adc719c2305ac361deb2b351b2562bbd3.
![grid-1](https://cloud.githubusercontent.com/assets/20027681/26310354/ca1e4e8c-3f00-11e7-9bbf-0628f56fb434.png)
![grid-2](https://cloud.githubusercontent.com/assets/20027681/26310395/dc636c62-3f00-11e7-8009-296df85f354c.png)

[Log](https://drive.google.com/open?id=0B9LymxJkpT48MjAwbFVjRWthbE0)
[Shaderlog GL](https://drive.google.com/open?id=0B9LymxJkpT48amw2a3hlOUd3aW8)

**Comment by kd-11** [comment]
Retest

**Comment by MarioSonic2987** [comment]
Same with https://github.com/RPCS3/rpcs3/commit/3499d089e74439192ab1cb52c88072e1d44020f9:

![image](https://user-images.githubusercontent.com/20027681/30699494-2fce7cf4-9ee5-11e7-8249-5898336d03a6.png)

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/30699675-a4a6fe8e-9ee5-11e7-98d7-b5fe35d0c9eb.png)
Shadows are working.

**Comment by MarioSonic2987** [comment]
```
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=2048 src_pitch=64
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=2048 src_pitch=32
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=2048 src_pitch=16
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=2048 src_pitch=8
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=2048 src_pitch=4
```

```
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=256 src_pitch=8
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=256 src_pitch=4
```

**Comment by kd-11** [comment]
Yea, I suspected as much, although its troubling to think of the scaling there. I mean a 16 pixels wide render target will be awfully pixelated when stretched to 512 pixels

**Comment by MarioSonic2987** [comment]
@kd-11 
![image](https://user-images.githubusercontent.com/20027681/32089418-2f087236-baea-11e7-9bea-2d01bec018ea.png)

[Log Grid 27-10-17 GL.gz](https://github.com/RPCS3/rpcs3/files/1420884/Log.Grid.27-10-17.GL.gz)
[RenderDoc OpenGL](https://drive.google.com/open?id=0B9LymxJkpT48OXdNTVAyaGd1MEk)

**Comment by MarioSonic2987** [comment]
In #3699, now has correct aspect ratio.
![image](https://user-images.githubusercontent.com/20027681/32608565-0ba67f22-c55d-11e7-9d3a-5a81f93ed081.png)
![image](https://user-images.githubusercontent.com/20027681/32608694-7cf469b4-c55d-11e7-9017-91a7ff98905f.png)
Only remains yellow-ish overlay issue.

**Comment by MarioSonic2987** [comment]
However, in Vulkan, it's a black screen on https://github.com/RPCS3/rpcs3/commit/3c9126d91f52f6a2ee624c627166c53ebac93de8. It isn't a regression.
![gridvk](https://user-images.githubusercontent.com/20027681/32674604-36b46e70-c654-11e7-91f4-c9a74546c64f.png)
![image](https://user-images.githubusercontent.com/20027681/32674729-b4580f26-c654-11e7-8572-b24b9a259b78.png)

[Log Grid 10-11-17 VK.gz](https://github.com/RPCS3/rpcs3/files/1462457/Log.Grid.10-11-17.VK.gz)
[Shaderlog Vulkan](https://github.com/RPCS3/rpcs3/files/1462460/Shaderlog.Grid.10-11-17.VK.zip)
[RenderDoc Vulkan](https://drive.google.com/open?id=12AtBSTfwYOL94U76vY5TjsAQVHkMOwwN)

**Comment by kd-11** [comment]
Flip hack was removed recently. Please retest.

**Comment by MarioSonic2987** [comment]
With #4011, it doesn't boot with Vulkan and OpenGL.

[RPCS3 GL.log](https://github.com/RPCS3/rpcs3/files/1598671/RPCS3.log)
[RPCS3 VK.log](https://github.com/RPCS3/rpcs3/files/1598672/RPCS3.log)

**Comment by MarioSonic2987** [comment]
@kd-11 Nevermind. I haven't put the Icons folder in RPCS3 directory.

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/34522264-12022de8-f092-11e7-87a4-b0619653bb4e.png)
No change with #4011.

**Comment by MarioSonic2987** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1600465/RPCS3.log.gz)

**Comment by MarioSonic2987** [comment]
#4469 fixes yellow overlay with OpenGL and blackscreen with Vulkan in menus. Closing this issue.
