### ISSUE TITLE
Regression: FEAR 2 Demo

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#2810]
Used to work a few months back, now black screen ingame, although the game is running. I am investigating but if someone can figure out which commit broke it, that would be helpful.

**Comment by SakataGintokiYT** [comment]
@kd-11 
With https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-4220
- Black screen in game with write color and without.

**Comment by kd-11** [comment]
Thanks alot.

**Comment by Xcedf** [comment]
The game works on recent master nad ogl without writing color buffer, but ingame is blackscreen
Revertig ogl part of b0c08a16 fixes ingame rendering and it works with no writing color
Vulkan still doesn't work for this game unfortunately but ain't worked before eithrer

**Comment by kd-11** [comment]
Closed via https://github.com/RPCS3/rpcs3/pull/2861
