### ISSUE TITLE
I cannot run Persona 5 in my PC , can someone help me? 

### ISSUE THREAD

**Issue by terracus3110** [RPCS3/rpcs3#2812]
![333](https://cloud.githubusercontent.com/assets/28916272/26388593/d2c298c6-4087-11e7-9e42-587556b0ea0c.PNG)
i already boot it so many times, but i don't know what's wrong with this..

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
