### ISSUE TITLE
Resident Evil Code Veronica X HD [NPUB30467]

### ISSUE THREAD

**Issue by megas7** [RPCS3/rpcs3#2815]
Windows 10 pro
Cpu : Intel Core i7 4930K
Ram : 64,0GB
Matherboard :  RAMPAGE IV BLACK EDITION
GPU:GeForce GTX 1080 Ti (EVGA)
SSD : NVMe Samsung SSD 950

Config of RPCS3 v0.0.2-7-8a64c4c
**Core**
PPU DEcoder: Interpreter
SPU Decoder : Recompiler {ASMJIT}
Library :automatic
**Graphics**
Render : Vulkan
Resolution : 720p
with tic of Use GPU texture scaling

Thread (xf_appli_CellSpursKernel0)} MEM: Access violation reading location 0x23860080
U {PPU[0x1000000] Thread (main_thread) [0x007afa04]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK
F {SPU[0x2000006] Thread (xf_appli_CellSpursKernel3)} MEM: Access violation reading location 0x23860080
F {SPU[0x2000007] Thread (xf_appli_CellSpursKernel4)} MEM: Access violation reading location 0x23860080
F {MFC Thread} MEM: Access violation reading location 0x23860080
F {SPU[0x2000005] Thread (xf_appli_CellSpursKernel2)} MEM: Access violation reading location 0x23860080
F {SPU[0x2000004] Thread (xf_appli_CellSpursKernel1)} MEM: Access violation reading location 0x23860080
F {PPU[0x1000002] Thread (Delay Job Thread) [0x0050fee4]} MEM: Access violation reading location 0x2e52a6d1

[RPCS3.log.txt](https://github.com/RPCS3/rpcs3/files/1028235/RPCS3.log.txt)

**Comment by megas7** [comment]
i try also with other settings 
[RPCS3.log.txt](https://github.com/RPCS3/rpcs3/files/1028278/RPCS3.log.txt)

**Comment by AniLeo** [comment]
http://www.emunewz.net/forum/showthread.php?tid=177162

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
