### ISSUE TITLE
HLE: Unimplemented cellPadPeriphGetData

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#2820]
**List of games not progressing due to unimplmented cellPadPeriphGetData**

DanceStar Party Hits [BCES01505]
Disney Epic Mickey 2: The Power of Two (Demo) [NPEB90433]
Phineas and Ferb Across the 2nd Dimension [BLUS30726]
Red Faction: Armageddon [BLUS30585]
SingStar: Back to the 80s [BCES01257]
SingStar Dance [BCES00894]
SingStar Guitar [BCES00835]

@jarveson is currently implementing this and those games should be progressing once implemented

**Comment by bjakja** [comment]
With new build Phineas and Ferb Across the 2nd Dimension [BLUS30726]
Go in game, freezes after 5 minutes.

**Comment by MarioSonic2987** [comment]
With #2826, Disney Epic Mickey 2: The Power of Two (Demo) [NPEB90433] reaches ingame.

**Comment by AniLeo** [comment]
Solved by #2826
