### ISSUE TITLE
Linux error at starting.

### ISSUE THREAD

**Issue by rcaridade145** [RPCS3/rpcs3#2821]
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Verification failed (e=9): file::write
(in file /home/rui/Programacao/rpcs3/Utilities/File.cpp:955)
```
It seems it crashes while trying to write to ".config/rpcs3/rpcs3.log"

**Comment by hcorion** [comment]
backtrace?

**Comment by rcaridade145** [comment]
Ubuntu 17.04. Ext4. 
It happens both on my branch as well as upstream.
Sorry i can only provide a backtrace later this week. I updated both ubuntu and rpcs3 and started having this problem.

**Comment by kd-11** [comment]
I have wip linux vulkan code and have not encountered this. I'm on linux 4.11 + ubuntu 16.04. Maybe its something on 17.04.

**Comment by NukeMania** [comment]
Hi,
Did you use clang-4.0 from Padoka Stable Mesa PPA that's broken i think
when i build with that clang i got same error as you did
but i build with gcc-5.4.0 or pre-built clang from llvm.org it's all good
Ubuntu 16.04.2 with linux-4.8 ext4

**Comment by mrcmunir** [comment]
I can reproduced similar error  unknown system error:20  but only from Open from Self file 
with GCC and Clang under Antergos linux distro.


>Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unknown system error: 20.

If use Pkg install or Boot from game boot fine but for elf/self manually won't boot now is a regresion i think right?

**Comment by hcorion** [comment]
@mrcmunir This is not the same issue, please open another issue.
Saying that, I've recently had a similar issue on MacOS, try changing
[line 204 in rpcs3/rpcs3qt/main_window.cpp](https://github.com/RPCS3/rpcs3/blob/master/rpcs3/rpcs3qt/main_window.cpp#L204) to
```
const std::string path = sstr(filePath);
```

**Comment by hcorion** [comment]
@rcaridade145 Can you please re-test? Remember to update your packages, and recompile.

**Comment by kirbyfan64** [comment]
I can reproduce this with the latest RPCS3 master, on Kubuntu 17.04.

**Comment by kirbyfan64** [comment]
As a workaround, you can add this:

```c++
printf("%d\n", static_cast<int>(fs::open_mode::write + fs::open_mode::create + fs::open_mode::trunc));
```

right before [this line](https://github.com/RPCS3/rpcs3/blob/master/Utilities/Log.cpp#L231).

**Comment by kirbyfan64** [comment]
This is definitely a Clang bug. You can see the bad `fs::rewrite` definition in the LLVM assembly:

```
@_ZN2fsL7rewriteE = internal global i32 0, align 4
```

**Comment by kirbyfan64** [comment]
Apparently the extra `printf` causes Clang to inline the constants, and then the bug goes away. Interestingly enough, I think this is actually a bug with precompiled headers, since without using the precompiled header, the generated code is correct.

**Comment by kirbyfan64** [comment]
Ok, I got this working. Ubuntu's Clang is considered by apt to be *newer* than the official LLVM PPA. This is the command I ran to forcibly install the official LLVM clang:

```
sudo aptitude install clang-4.0=1:4.0~svn305264-1~exp
```

followed by accepting the third choice ("downgrading" the packages). Then I ran:

```
sudo aptitude hold clang-4.0 clang-4.0-doc libclang-common-4.0-dev libclang-4.0-dev libclang1-4.0 libclang1-4.0-dbg libllvm4.0 libllvm4.0-dbg lldb-4.0 llvm-4.0 llvm-4.0-dev llvm-4.0-doc llvm-4.0-examples llvm-4.0-runtime clang-format-4.0 python-clang-4.0 libfuzzer-4.0-dev
```

to prevent them from being changed. Now RPCS3 builds and runs normally.

**Comment by scribam** [comment]
@rcaridade145 Is it still an issue?

**Comment by rcaridade145** [comment]
@scribam nope :)
