### ISSUE TITLE
Hatsune Miku - Problems with Mesa + OpenGL

### ISSUE THREAD

**Issue by DrogonMar** [RPCS3/rpcs3#2822]
My video: https://www.youtube.com/watch?v=Zo6vBhw8EiI 
It has problems with opengl but in game it plays a mp4 which is why its smooth but at 4:35 on there it has rendering and its not good like a lot of flashing colors, weird thing is the movement is smooth but it cant render the background.

Linux Mint 18 with KDE

**Comment by hcorion** [comment]
Ok, System specs, video driver (binary or open source).
I've previously had issues with GCC and RPCS3 ( #2677 ), try compiling with clang.

**Comment by toccata10** [comment]
On Arch x64 with mesa 17.1 with a fury r9, I just have a black screen when I launch SuperStreetFighter 2 turboHD: I have the sound, but no picture and the fps displays 60.
Same with 1942 game.
I tried to compile with clang by doing this:
#!/bin/bash
git clone https://github.com/RPCS3/rpcs3.git
cd rpcs3/
#test with clang
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
git submodule update --init
cmake CMakeLists.txt && make GitVersion && make
Then I launch with:
MESA_GL_VERSION_OVERRIDE=4.5 ./rpcs3/bin/rpcs3
I once had it more or less working on my system (graphic was ok, but i had a lot of input lag), but maybe it was because I was on mesa-git, or maybe because of a previous version of rpcs3.

**Comment by hcorion** [comment]
@toccata10 Please don't hijack threads.

Saying that, mesa usually doesn't work very well, because of the advanced features RPCS3 uses.
Try installing mesa-git and see if that works, if not using the binary drivers is usually recommended.

**Comment by Areiser** [comment]
The mesa drivers are even used in the next steamOs over the binary ones, the binary drivers are not much better and will probably be worse in the future. @toccata10  For me rpcs3 usually works with the overrides. Maybe you are missing the MESA_GLSL_VERSION_OVERRIDE=450?

**Comment by toccata10** [comment]
Same result adding MESA_GLSL_VERSION_OVERRIDE=450.
I'll open another thread as it doesn't seem to be the same as the initial problem.

**Comment by toccata10** [comment]
mesa 17.1.1 + r5251: works (normal display).

**Comment by kd-11** [comment]
![screenshot from 2017-06-05 23-13-52](https://cloud.githubusercontent.com/assets/15904127/26801357/4fa3c344-4a45-11e7-87c5-91be5001779f.png)
![Uploading Screenshot from 2017-06-05 23-13-29.png…]()
Works fine for me as well, I'm guessing the OP is using old drivers
```glxinfo | grep 'GL renderer'
OpenGL renderer string: Gallium 0.4 on AMD PITCAIRN (DRM 3.16.0 / 4.11.0-rc7-drmwip, LLVM 4.0.1)```

**Comment by exolyte** [comment]
Menus look like this for me:
![2017-06-25-22 03 48](https://user-images.githubusercontent.com/2102492/27519404-b8416394-59f3-11e7-9c0b-64fd146ef7fd.png)
![2017-06-25-22 04 28](https://user-images.githubusercontent.com/2102492/27519405-bcde1a1e-59f3-11e7-886a-5597992c8b80.png)
![2017-06-25-22 04 59](https://user-images.githubusercontent.com/2102492/27519406-bf143412-59f3-11e7-9c89-7d917d37eb96.png)

CPU: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
GPU: gtx 760, using proprietary nvidia drivers 381.22
In the actual gameplay bits, there's only the occasional graphical glitch. It renders fine on vulkan, but the framerate is very low (~5 fps) while openGL is a constant 30 fps.

**Comment by exolyte** [comment]
After #2962 it changed to this:
![2017-07-08-16 01 35](https://user-images.githubusercontent.com/2102492/27986025-a5973cd2-63f8-11e7-8e4f-87c7f49583ec.png)
![2017-07-08-14 48 40](https://user-images.githubusercontent.com/2102492/27986026-abfaae1a-63f8-11e7-93e5-9453ef0bc893.png)
![2017-07-08-16 03 04](https://user-images.githubusercontent.com/2102492/27986027-b5421d00-63f8-11e7-9b20-8ea43e64a335.png)
![2017-07-08-16 03 26](https://user-images.githubusercontent.com/2102492/27986037-e7aefb50-63f8-11e7-9a2f-7c22a5acc685.png)

**Comment by toccata10** [comment]
mesa 17.1.4, archlinux, r9 fury. Tried with different options (recompiler, different resolutions,...): with opengl I have glitches. On Vulkan (radv), it is good.
[RPCS3-DivaF-02.zip](https://github.com/RPCS3/rpcs3/files/1136679/RPCS3-DivaF-02.zip)
![fps 30 03 opengl hatsune miku project diva f blus31319 _266](https://user-images.githubusercontent.com/7478580/28034017-450ec092-65b0-11e7-8f41-6b0f967f58fe.jpg)
![fps 29 98 opengl hatsune miku project diva f blus31319 _267](https://user-images.githubusercontent.com/7478580/28034021-48aca5ca-65b0-11e7-85e7-692cacc97921.jpg)
![fps 29 98 opengl hatsune miku project diva f blus31319 _268](https://user-images.githubusercontent.com/7478580/28034032-4d1175b4-65b0-11e7-99f6-213737bae179.jpg)
Vulkan:
![fps 29 97 vulkan hatsune miku project diva f blus31319 _269](https://user-images.githubusercontent.com/7478580/28034044-58228678-65b0-11e7-8aa9-2cc5eca81aa5.jpg)
![fps 29 98 vulkan hatsune miku project diva f blus31319 _270](https://user-images.githubusercontent.com/7478580/28034045-5ac6b3ae-65b0-11e7-8e3b-32fd6fc1b3b0.jpg)
[RPCS3-DivaVulkan.zip](https://github.com/RPCS3/rpcs3/files/1136686/RPCS3-DivaVulkan.zip)

**Comment by kd-11** [comment]
@toccata10 Could you retest this? Not sure what I can do about mesa not rendering properly as it still renders fine on my setup.

**Comment by toccata10** [comment]
Unfortunately, still problematic on mesa 17.2, with latest master (r9 fury, archlinux).
Tell me if you want me to report the bug to the mesa team or if you need anything else (renderdoc?)

![diva-01](https://user-images.githubusercontent.com/7478580/30828092-bfe19fba-a23c-11e7-936c-25cfd8178c49.jpg)
![diva-02](https://user-images.githubusercontent.com/7478580/30828096-c1adcf58-a23c-11e7-991e-adfe3687b551.jpg)
[RPCS3.log-MikuOGL.gz](https://github.com/RPCS3/rpcs3/files/1330714/RPCS3.log-MikuOGL.gz)

**Comment by kd-11** [comment]
Is this still a problem? Renderdoc wont help catch the error since it replays the draw commands using the driver installed on the device playing it back; It would not show any issues on systems not affected by this bug.

**Comment by toccata10** [comment]
Yes, same situation with mesa 17.3.1

**Comment by toccata10** [comment]
Mesa was updated to 17.3.2 but no change for these glitches

**Comment by scribam** [comment]
@toccata10 Have you had an opportunity to test with Mesa 18.0?

**Comment by toccata10** [comment]
RPCS3 v0.0.5-6692-98b715d8c Alpha | HEAD
mesa 18.0 on Arch
Still the same pbs with Ogl and now the performance is terrible (around 3fps where it was 30fps). On Vulkan (Radv), it seems ok (no glitches, 30fps once the shaders are compiled).
![selection_085](https://user-images.githubusercontent.com/7478580/39317602-4d1d7f84-497c-11e8-879b-bf319c0ad971.jpg)

**Comment by kd-11** [comment]
Miku operates at 1440p natively so 4k is actually 8k+. It fakes 720p resolution with downscaling so the slowdown when scaling is active is expected.

**Comment by kd-11** [comment]
The resolution you see there has no impact on rendering resolution. Miku with 200% scaling is 5k res regardless of what you set as display resolution. Display resolution is found in TV settings menu on ps3.
