### ISSUE TITLE
GL/Vulkan: Midnight Club: Los Angeles

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2825]
Tested in https://github.com/RPCS3/rpcs3/commit/7739f332c36ec2cd4c0b32ea1470e621ca7373c3.

**OpenGL** - Has lighting issues and doesn't have fog.
![](http://i.imgur.com/eKZv2ji.png)
**Vulkan** - Same as GL but it has fog.
![](http://i.imgur.com/K2sNtea.png)

**SPU: Interpreter (precise)** - Car model is fine.
![](http://i.imgur.com/jLOUchu.png)
**SPU: Interpreter (fast)** - Car model is broken.
![](http://i.imgur.com/pd23pXc.png)

**Comment by MarioSonic2987** [comment]
A view much clearer of how the car is rendered:

**SPU: Interpreter (precise)**:
![](http://i.imgur.com/Z0VHCfH.png)
**SPU: Interpreter (fast)**:
![](http://i.imgur.com/FienxH8.png)

**Comment by kd-11** [comment]
Retest. Most of these issues should be resolved now.

**Comment by AniLeo** [comment]
CPU issues were fixed on master, retest for the others please

**Comment by MarioSonic2987** [comment]
Tested with https://github.com/RPCS3/rpcs3/commit/6d14583f287c5b19ebb06636b9c6ecd1541436d2:

![mcla-1](https://user-images.githubusercontent.com/20027681/29351724-35f33248-8264-11e7-8255-2d03b91f8c36.png)
Car model is fixed.
![mcla-1 broken](https://user-images.githubusercontent.com/20027681/29351775-7156fd10-8264-11e7-97af-141de369031a.png)
But if you crash with it in a wall, it breaks again.

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/29352162-f839129a-8265-11e7-97a1-107e60e51cfa.png)
With SPU precise.

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/29352262-5667fa34-8266-11e7-931a-cc167dfced93.png)
With OpenGL, graphics are improved a little bit.

**Comment by kd-11** [comment]
Any issues left? I see SPU precise gives the same result as ASMJIT after crash. Is SPU precise also incorrect?

**Comment by MarioSonic2987** [comment]
Tested with https://github.com/RPCS3/rpcs3/commit/1ffc1e82b0de8950669cd879493ceb60cc570da6: 
![image](https://user-images.githubusercontent.com/20027681/32141838-e6ea63f4-bc8a-11e7-9ade-c36064faae7a.png)
![image](https://user-images.githubusercontent.com/20027681/32141871-69485612-bc8b-11e7-941a-8d9620e6538d.png)
[RPCS3.log.gz GL](https://github.com/RPCS3/rpcs3/files/1424877/RPCS3.log.gz)

**Comment by MarioSonic2987** [comment]
Transition between race mode is broken in Vulkan. In OpenGL, it's fine.
![image](https://user-images.githubusercontent.com/20027681/32141898-e1a2702a-bc8b-11e7-9bf9-e580f950e767.png)
![image](https://user-images.githubusercontent.com/20027681/32141913-310774d0-bc8c-11e7-9c1f-6f538f035bc9.png)

**Comment by MarioSonic2987** [comment]
With https://github.com/RPCS3/rpcs3/commit/de465cb9412a40e3cf7ccf9590e9fa040bf0f2e6, lighting is flashing. I think the game is trying render its shadows (at least with OpenGL).


![image](https://user-images.githubusercontent.com/20027681/33058064-06d3d6cc-ce8e-11e7-9334-5e5128794540.png)
![image](https://user-images.githubusercontent.com/20027681/33058140-75270e14-ce8e-11e7-9a9d-c7067d40b2f9.png)
![image](https://user-images.githubusercontent.com/20027681/33058317-72545bf0-ce8f-11e7-9ec3-c0c274016ca6.png)

**Comment by kd-11** [comment]
Any update?

**Comment by MarioSonic2987** [comment]
Tested with https://github.com/RPCS3/rpcs3/commit/4f01794713b09bddc51998edd060caf4f1a5e487.
There are no longer differences between backends.
![image](https://user-images.githubusercontent.com/20027681/35223891-59cc1ff8-ff83-11e7-9a8c-daf8f36c1389.png)
![image](https://user-images.githubusercontent.com/20027681/35224030-df6a58d2-ff83-11e7-9791-fed75a570ea2.png)
Transition bug is fixed in Vulkan.
![image](https://user-images.githubusercontent.com/20027681/35224153-47b3b12c-ff84-11e7-96c9-bc10801a5277.png)

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/35480164-ee931bee-0408-11e8-9186-d661c1ba5371.png)
Car model no longer breaks when you crash into a wall.

**Comment by MarioSonic2987** [comment]
[Video](https://www.youtube.com/watch?v=F3LA9kqOXJc)

With #4123, it's possible to see light and shadows. With Write Color Buffers, car's model doesn't break when it's crashed into the wall (it isn't a SPU issue). Strict Rendering Mode and Disable Vertex Cache don't make any difference. The only issues that remain are overbrigth light (in noon mainly) and broken shadows (same as RDR and Uncharted 1).

Should I close this issue for now because the original issue is fixed? (GL has no fog and reflections, or Vulkan broken transition).

**Comment by MarioSonic2987** [comment]
With #4265, shadows are rendered fine to some degree, the farther ones aren't rendered correctly: 
![image](https://user-images.githubusercontent.com/20027681/37387093-7020970c-275b-11e8-81c7-00f4492d3cd4.png)

Buildings becoming white when switching between LODs is still there. It occurs during transitions in loading screen or going to race mode.

**Comment by MarioSonic2987** [comment]
With #4312, fixes overbloom. Also, it fixes the gamma. Only remains broken shadows.
![image](https://user-images.githubusercontent.com/20027681/37874383-300cb854-302e-11e8-9ab4-887ad51ff6f5.png)
![image](https://user-images.githubusercontent.com/20027681/37874393-6bf8310e-302e-11e8-9d0e-0f0952c7914a.png)
Now car isn't darker than the map.
![image](https://user-images.githubusercontent.com/20027681/37874414-05bdd6ea-302f-11e8-81e8-31715b6cfad0.png)

**Comment by MarioSonic2987** [comment]
Before I close this issue, remember that you have to set Write Color Buffers to on to fix the broken car graphics (too bright, detached parts of the car after crashing into a wall).
