### ISSUE TITLE
Regression: [BLES00296] SoulCalibur IV - PPU Interpreter Precise: Broken graphics in the menu orb (#2736)

### ISSUE THREAD

**Issue by raveskirza** [RPCS3/rpcs3#2827]
Starting from the commit #2736

The graphics inside the ORB is pixelated in PPu precise. This was reported on the Pull request, however i misunderstood on how Github and Appveyor builds work and thought it was fixed by a different build

![image](https://cloud.githubusercontent.com/assets/28158623/26755207/b6ca5330-4856-11e7-817b-852551a03604.png)

In PPU Interpreter (fast) and (precise prior to the commit). This is how the ORB looks, there is some graphics rendering and it is not pixelated
![image](https://cloud.githubusercontent.com/assets/28158623/26755114/d5cb527c-4854-11e7-8768-4695af97b04f.png)

This is a minor issue but wanted to report as it may give some clue on the PPU threads and the Graphics rendering.

**Comment by AniLeo** [comment]
Still an issue?

**Comment by raveskirza** [comment]
Yes Still an issue.
 i dont think any of the PR's touched the precise intepretor since commit 2736

**Comment by digitaldude555** [comment]
![screenshot 2229](https://user-images.githubusercontent.com/26138653/53698168-a95ea980-3de1-11e9-9e30-5508e0e512e0.png)
still an issue.

**Comment by elad335** [comment]
Retest with https://ci.appveyor.com/project/elad335/rpcs3/builds/23202030.
