### ISSUE TITLE
Ctrl + S shortcut to stop

### ISSUE THREAD

**Issue by Ekaseo** [RPCS3/rpcs3#2831]
I know its a minor thing, but would it be possible to bring it back?

**Comment by Megamouse** [comment]
It's working in the Main window but it looks like this is not working in GSframe.
We'll look into it.

**Comment by raveskirza** [comment]
I think the buttons are disabled when the main windows lose focus.
 In wx the Pause,stop and restart buttons are enabled when main windows lose focus

![image](https://cloud.githubusercontent.com/assets/28158623/26764448/1eb95976-4935-11e7-9428-9d324fb81c2b.png)

In QT the Pause,Stop and restart buttons grey out on losing focus
![image](https://cloud.githubusercontent.com/assets/28158623/26764467/5ffc1586-4935-11e7-9154-9a09fa93e0eb.png)

**Comment by Megamouse** [comment]
The GSFrame does not seem to be recognized as an application window so I can't use the normal flag that would keep those shortcuts enabled.
Considering eventhandling

**Comment by AniLeo** [comment]
Fixed on #2834

**Comment by Wrascon** [comment]
Because of people like you, now every time the game stops when you press the block + back, namely Ctrl + s in the classic PC control of the game Demon's Souls

**Comment by AniLeo** [comment]
Golden shovel of issue digging...

**Comment by Megamouse** [comment]
That's why people who don't want to sit on their desk all day especially after work play using gamepads.
But I can see how this might be annoying. If I ever have the time i'll add some shortcut management (very low priority)
