### ISSUE TITLE
Regression : Project Diva F FMV freeze

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#2836]
![image](https://cloud.githubusercontent.com/assets/11285640/26774257/a8a8d61a-49f9-11e7-8f5a-8dd0282e3977.png)
It's boot success but play for a few second and freeze

**Comment by AniLeo** [comment]
The opening video has been freezing for more than 3 months. Just press enter to skip it. 

One has to track the commit that caused that.

**Comment by clienthax** [comment]
Im only able to get the freeze with asmjit on latest builds.
Bisected it back to this commit, https://github.com/RPCS3/rpcs3/pull/2714/commits/9b4320311140acec2162a2c937cc0125532d9c56

**Comment by SakataGintokiYT** [comment]
@AniLeo 
Fixed by [dda274a]
