### ISSUE TITLE
rpcs3 error

### ISSUE THREAD

**Issue by skwnsdh3240** [RPCS3/rpcs3#2838]
---------------------------
Fatal error
---------------------------
Unhandled exception of type 'class std::runtime_error': Can't create log file RPCS3.log (error Access violation)
HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
확인   
---------------------------

what do i do?

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
