### ISSUE TITLE
Determination of firmware version when it's installed

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#2840]
Is it possible to add determination of PS firmware version when it's installed? Like "Firmware v4.81 is installing..." etc.
![issue](https://cloud.githubusercontent.com/assets/14265316/24409963/6d79a86c-13da-11e7-8892-5b0a4908ac71.png)
P.S. When an older firmware is installed (e.g. from game disc there it's often older than the last v4.81), the message "You've installed not last firmware. You can take the last version of it on https://www.playstation.com/en-us/support/system-updates/ps3/" or smth like this may be showed.

**Comment by flash-fire** [comment]
Consider this added to my todo list ;)

**Comment by hcorion** [comment]
We discussed this on discord.

This website here describes the file header:
http://www.psdevwiki.com/ps3/Playstation_Update_Package_(PUP)#Header
The second series of 8 bytes has the version info
On the latest one from the website, that is
```
46 00 00 00
```

So we could do that, or we could checksum the current file, and just compare checksums.

**Comment by SaltyCucumber** [comment]
Implemented in PR #2958
Bugfixed in PR #3012
