### ISSUE TITLE
Demon Souls problem

### ISSUE THREAD

**Issue by chrossrank** [RPCS3/rpcs3#2846]
Every time i try to load Demon Souls, this shows up
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault writing location 0000000000000000 at 0000000000000000.
Instruction address: 0000000000000000.
RPCS3 image base: 0000000000010000.
-----------------------------
I dont know how to fix this. Can anyone help? Do i have to install something else?

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
