### ISSUE TITLE
VK: Image creation failing on zero-sized textures

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#2848]
```
E {rsx::thread} RSX: ERROR: [Driver] Code 0 : vkCreateImage: image creation failed due to invalid parameter
F {rsx::thread} : class std::runtime_error thrown: Assertion failed! Result is C4650B07h
(in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:378)
```
This is thrown when the game passes width = 0 and height = 0 to the Render. Games where this happen tend to function on OpenGL, but not on Vulkan nor on D3D12 (which is known to be extremely outdated anyways).

**List of known affected games:**
BLES00134 - Guitar Hero III
BLES00014, BLUS30011 - Tony Hawk's Project 8 (#2794)
BLUS31584 - Grand Theft Auto: San Andreas ([Thread](http://www.emunewz.net/forum/showthread.php?tid=177699&pid=242206#pid242206))
NPEB00052 - Mirror's Edge ([Thread](http://www.emunewz.net/forum/showthread.php?tid=175496&pid=233937#pid233937))
NPUB30579 - Sonic Adventure 2: Trial

**Comment by kamer1337** [comment]
same happens on:
BLES00130 Tony Hawk's Proving Ground

**Comment by kd-11** [comment]
I added checks to ignore zero sized framebuffers on vulkan and opengl so this is hopefully resolved now.

**Comment by kamer1337** [comment]
doesnt seem to be fixed, only sometimes works, tested with tony hawk games
```
E {rsx::thread} RSX: Invalid framebuffer setup, w=0, h=0
F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is C4650B07h
(in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:395)
```

**Comment by SakataGintokiYT** [comment]
@kd-11 
```
 **Sonic Adventure 2: Trial**
E {rsx::thread} RSX: Invalid framebuffer setup, w=0, h=0
F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is C4650B07h
(in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:395)

```
**Log:** https://gist.github.com/SakataGintokiYT/1aa8d84f5c48a03daf3045ed5c8a689f

------------------------------------------------------------------------------------------------------------
```
**GTA San Andreas**
E {rsx::thread} RSX: Invalid framebuffer setup, w=0, h=0
F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is C4650B07h
(in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:395)
```
**Log:** https://gist.github.com/SakataGintokiYT/754e0548a41c4f296216cd92d764e596

**Comment by kamer1337** [comment]
@kd-11 

shouldn't there be an return when false passed?

VKGSRender.cpp
Line: 1852
```
if (clip_width == 0 || clip_height == 0)
   {
   LOG_ERROR(RSX, "Invalid framebuffer setup, w=%d, h=%d", clip_width, clip_height);
   framebuffer_status_valid = false;
   }
   
 framebuffer_status_valid = true;
```

**Comment by kd-11** [comment]
Yes, a return is missing. Will be submityed with the next round of fixups

**Comment by AniLeo** [comment]
Fixed on master

**Comment by NathanMrtns** [comment]
Im getting the error:
Invalid framebuffer setup, w=0, h=0
Odin Sphere Leifthraiser (BLES02241) Tried with Vulkan and OpenGL
The game freezes on this screen [https://imgur.com/a/oklN6](https://imgur.com/a/oklN6)
