### ISSUE TITLE
Vulkan Linux: white wash

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#2849]
Archlinux, r9 fury, mesa.
Nice to see we have a linux vulkan renderer ! If I use it, there's a kind of white wash on the screen compared to opengl (which seems correct, when I compare to the windows version on the same computer).
![ogl-01](https://user-images.githubusercontent.com/7478580/26963441-da00fc56-4cec-11e7-8f7d-7a1e2daabf92.jpg)
![vulkan-01](https://user-images.githubusercontent.com/7478580/26963444-dbe128b6-4cec-11e7-9331-f2d37c2eae2b.jpg)
It's the same behaviour on the 2 games I've tested so far.

**Comment by kd-11** [comment]
Its either the color space or gamma ramp thats wrong. It happens on all titles for me as well, but I'm also using mesa. Need testers with proprietary to check so we can narrow down the cause.

**Comment by 7oxicshadow** [comment]
I have just tried vulkan on fedora 25 using propitiatory nvidia drviers 381.22 (GTX1070) and do not see any "whitewash" issues. This looks like it is mesa related.

![ds](https://user-images.githubusercontent.com/10350138/27006512-35d7980a-4e2d-11e7-8612-f2e0aafc4fa7.jpg)

I also tested Terraria with no issues aswell.

**Comment by logos88** [comment]
I also have the white wash and the words doesn't appear in Vulkan.
![captura de pantalla de 2017-06-26 14-47-21](https://user-images.githubusercontent.com/4170088/27539936-aafbafec-5a7e-11e7-9d13-d57b3a35164d.png)

And when I use Open GL i just get a black window (I hear the music though). Before QT I could play it with Open GL with MESA_GL_VERSION_OVERRIDE=4.5

Operating System: Arch Linux
Processor: 4x Intel Core i5-4570 CPU @ 3.20GHz
GPU: Intel HD Graphics 4600 with mesa 17.1.3

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1102127/RPCS3.zip)

**Comment by logos88** [comment]
I have tried with the rsx: Bug fixes but I still don't get the words

**Comment by SaschaWillems** [comment]
This was happening with my Vulkan examples on MESA too (Intel and AMD) and may be related to how you select the swap chain surface format. If you e.g. just use the first format available you may get a SRGB format on MESA instead of UNORM for most other implementations and that results in the brighter image.

So instead of just selecting the first format, you need to iterate over all available ones pick the UNORM one.

[This PR](https://github.com/SaschaWillems/Vulkan/pull/275) from my repository may help.

**Comment by kd-11** [comment]
I had suspected the color space might be wrong but I was looking in the wrong place. Thanks.

**Comment by toccata10** [comment]
On the 5408 version, vulkan white wash is gone. Closing. On mesa r9 fury, it's often way slower than opengl, but that's another pb (battlefantasia is 60fps on opengl, 35fps on vulkan).
![vulkan-5408](https://user-images.githubusercontent.com/7478580/28033288-07e28a8e-65ae-11e7-83fe-abba66a9c714.jpg)
