### ISSUE TITLE
Minor Log Text Color Glitch

### ISSUE THREAD

**Issue by flash-fire** [RPCS3/rpcs3#2851]
If you select/highlight a text while new text is being written, the written text color will be the selected color, and the selected font will be the written color.

Not sure on the cause.  But, it's fairly niche in practice. 

[Result](http://imgur.com/a/a60yu)

**Comment by Zangetsu38** [comment]
yes, log is little glitched, i have see several time eror in green and fatal is red, just QT is not stable for moment.

**Comment by Megamouse** [comment]
can be closed
