### ISSUE TITLE
Games no longer auto launch when passed as a parameter via cmd line

### ISSUE THREAD

**Issue by 7oxicshadow** [RPCS3/rpcs3#2858]
I am currently testing RPCS3 v0.0.2-5272-9aa632b Alpha and it appears that passing eboot.bin as a command line parameter no longer launches the game.

It only loads the UI. This used to work fine so i suspect that it is the result of moving to QT.

**Comment by flash-fire** [comment]
It's because of Qt.  Forgot to implement command line stuff.  Won't work on windows as well.

**Comment by flash-fire** [comment]
Can you modify the title to remove the (Linux) flag? Thanks

**Comment by 7oxicshadow** [comment]
done :)

**Comment by flash-fire** [comment]
Check with [this.](https://github.com/RPCS3/rpcs3/pull/2859)

Should be able to boot stuff from command line now.

**Comment by 7oxicshadow** [comment]
I have tested your mod and it now works as expected.

Thanks

**Comment by AniLeo** [comment]
Solved on #2859

**Comment by DannyGlover** [comment]
I'm having this issue with build: 0.0.3-3-4aa8913 and below (since the QT switch).

Launching a game (example command)

````
rpcs3.exe "E:\Games\Emulator_Games\Sony\Sony Playstation 3\PS3_HDD\game\NPEA00433\USRDIR\EBOOT.BIN"
````

The RPCS3 window shows up, then closes. The emulator process continues running in the background, but the game is not running.

This previously worked fine before the QT change. Has the launch parameter changed, or is it still broken?

Thank you

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1432617/RPCS3.zip)

**Comment by Megamouse** [comment]
did you try double \\ ?

**Comment by DannyGlover** [comment]
@Megamouse Yes. Same result.

The file path convention used above worked fine in pre-qt builds and in other emulators too. If you right click a path in the Windows explorer and chose the copy option, this is the path convention it uses (single \'s).

Thanks

**Comment by Megamouse** [comment]
works perfectly fine for me btw.
maybe its the vfs?

btw you can omit the "\USRDIR\EBOOT.BIN"

**Comment by DannyGlover** [comment]
I tested again with the default virtual file system settings and moved everything back into the standard location (dev_hdd0 inside the emulator's folder) and it still doesn't work.

**Comment by Megamouse** [comment]
no idea. sorry

what is your operating system?

**Comment by DannyGlover** [comment]
Windows 10 x64. Fall creators update.

Just to reiterate, this was working fine, prior the QT update.
Cheers

**Comment by Asinin3** [comment]
Maybe the windows update broke your system path to the RPCS3 folder? Idk, I'll test it.

**Comment by Asinin3** [comment]
@DannyGlover I think I know the solution to your problem, disable this setting "Exit RPCS3 when process finishes: true" I remember talking to someone using steam big picture with shortcuts to each game and he had the exact same problem as you.

**Comment by Megamouse** [comment]
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6668/artifacts

this should fix the problem even with "Exit RPCS3 when process finishes" enabled

**Comment by halotroop2288** [comment]
Megamouse, you are a life-saver. THANK YOU.

**Comment by DannyGlover** [comment]
@megamouse awesome! I'll try this out soon (currently sick :/)

Thank you
