### ISSUE TITLE
Error compiling rpcs3 on LinuxMint 18.1

### ISSUE THREAD

**Issue by butzsan** [RPCS3/rpcs3#2864]
I got this error while is compiling 

`/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:88:5: note:   candidate expects 2 arguments, 1 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:87:14: note: candidate: QAction::QAction(QObject*)
     explicit QAction(QObject* parent);
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:87:14: note:   no known conversion for argument 1 from ‘QString’ to ‘QObject*’
rpcs3/CMakeFiles/rpcs3.dir/build.make:7827: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/rpcs3qt/cg_disasm_window.cpp.o' failed
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/rpcs3qt/cg_disasm_window.cpp.o] Error 1
CMakeFiles/Makefile2:234: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`
Since the last 5 days, before that it was compiling fine

**Comment by hcorion** [comment]
Hi!
We've recently moved from WxWidgets to Qt.
Unfortunately the Qt version on Linux Mint is too old.
If you really want to use RPCS3 and not change distros then you can manually install a newer version of Qt, there is a guide here: http://www.linuxfromscratch.org/blfs/view/8.0/x/qt5.html

**Comment by Sunderland93** [comment]
> Unfortunately the Qt version on Linux Mint is too old.

Why you don't choose Qt 5.6 LTS as minimal version to build RPCS3? Qt 5.8> is not exists in most distro's repo's

**Comment by AniLeo** [comment]
I think you can compile with QT 5.7 as well, but grab 5.8 since it's the target version

**Comment by butzsan** [comment]
I install qt 5.8 full and it doesn't work, same error at the same place

**Comment by hcorion** [comment]
That means it's still trying to use the old Qt, where did you install qt 5.8 to?

**Comment by butzsan** [comment]
I use this ppa "https://launchpad.net/~beineri/+archive/ubuntu/opt-qt58-xenial" and I install the full version of qt5.8 in "/opt/qt58"

**Comment by hcorion** [comment]
Ok, good the first run
```
source /opt/qt58/bin/qt58-env.sh
```
then make sure to clean your build directory.
then try running cmake

**Comment by butzsan** [comment]
now Cmake is detecting qt58, I deleted CmakeCache.txt and now it's compiling :D

**Comment by butzsan** [comment]
Okey, I know I compile llvm and it compile fine, why is giving me this error at the end of the compilation?

"
[  3%] Linking CXX executable ../bin/rpcs3
/usr/bin/ld: cannot find -lLLVM
collect2: error: ld returned 1 exit status
rpcs3/CMakeFiles/rpcs3.dir/build.make:12645: recipe for target 'bin/rpcs3' failed
make[2]: *** [bin/rpcs3] Error 1
"

**Comment by hcorion** [comment]
Did you `sudo make install` LLVM?
It's hard to tell what went wrong, without seeing the process.

**Comment by butzsan** [comment]
yes, I installed it, it gave me that error and the end of the rpcs3 compilation

**Comment by hcorion** [comment]
@butzsan 
I didn't realize you could install ubuntu PPAs in Mint.
try installing this ppa:
`deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main`
and install llvm-4.0
it should link.

**Comment by butzsan** [comment]
Now it finally compiles fine :D 

Thanks **@hcorion**

**Comment by hcorion** [comment]
@butzsan Now that it compiles could you please close this issue?
