### ISSUE TITLE
Fatal error at start (Windows 10)

### ISSUE THREAD

**Issue by AnonJump** [RPCS3/rpcs3#2866]
I have window at start... But when I try to start a clean build of the RPCS3, I get a fatal error. RPCS3.log is empty.
Windows 10, Core i7-2600k, GTX 560 Ti 448 cores.
https://pastebin.com/xq1D80W1

**Comment by twdarkeh** [comment]
Delete GUIConfig folder.

**Comment by AnonJump** [comment]
I don't have this folder.

**Comment by AniLeo** [comment]
This is already known. A fix will be deployed

**Comment by AnonJump** [comment]
Now it's fixed by [https://github.com/RPCS3/rpcs3/pull/2870](url). Thanks to @jarveson.
