### ISSUE TITLE
Persona 5 boot error

### ISSUE THREAD

**Issue by raybon256** [RPCS3/rpcs3#2868]
I can get persona 5 booted but durign the initial loding screen i get this error message:

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 000000010000000f at 0000000000281f81.
Instruction address: 0000000000281f81.
Function address: 00000000002819f0 (base+0x2719f0).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

Was told to send this to you guys. Not sure if you encountered this before but here.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.

**Comment by raybon256** [comment]
Okay, I think I have made an error. All right.
