### ISSUE TITLE
Unhandled Win32 exception 0xE06D7363. Exception address: 000007fefd86a06d

### ISSUE THREAD

**Issue by iBlackS0ul** [RPCS3/rpcs3#2869]
Hey, so... i'm getting this "fatal error" while trying to open the emulator

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xE06D7363.
Exception address: 000007fefd86a06d.
ExceptionInformation[0x0]: 0000000019930520.
ExceptionInformation[0x1]: 000000000377f910.
ExceptionInformation[0x2]: 000000000187ee00.
ExceptionInformation[0x3]: 0000000000010000.
Instruction address: 000007fefd86a06d.
Function address: 000007fefd86a030 (base+0x1a030).
Module name: 'KERNELBASE.dll'.
Module base: 000007fefd850000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
   
---------------------------

Anyone knows the reason? i havent found it yet...
Windows 7 Professional, Processor Intel Core i3, 6GB RAM, GPU NVidia Geforce GT630...

**Comment by Sangabc** [comment]
I got it too wonder what happend, btw it only happend since the 6/8/2017 build the previous one work fine!

**Comment by twdarkeh** [comment]
Try with #2870

**Comment by thullanumber1** [comment]
> Duplicated. Is fixed by latest PR

How do I fix it please help?

**Comment by Darkhost1999** [comment]
Commenting on a 5 year old closed issue is not the way to go about this.
Please consider joining the discord or communicating on one of our communication platforms.
