### ISSUE TITLE
Beyond Good & Evil HD - only 1/4 of viewport showing

### ISSUE THREAD

**Issue by hcorion** [RPCS3/rpcs3#2873]
Here is a quick video showing the problem:
https://youtu.be/6joDLP6EJnU

RPCS3.log:
https://gist.github.com/faf554df91894bf07aa0a256e9c1aee4

Other games do not have this problem.
This may be a Linux-only bug, if someone can test this game under Windows, and the viewport works correctly, we can confirm it's a Linux bug.

OS: Arch Linux 64-bit
Hardware: GTX 1070
Nvidia drivers: 381.22 (beta drivers)
X Server version: 1.19.3
CPU: Intel i7 4770
Screens: Two 1920x1080 screens
Window Manager: KDE Plasma 5.10.1
Linux kernel: 4.11.3
Qt version: 5.9.0 (distro package, not custom installed)

**side note:**

The log in the GUI kept spamming 
```
RSX: NV3089_IMAGE_IN_SIZE: unknown origin (0)
```

**Comment by hcorion** [comment]
Just tested with old wxWidgets build and I've got the same issue, specifically, d5107aab4

**Comment by darkredflame** [comment]
I don't seem to have this issue on Windows using the latest QT build.

![rpcs3_2017-06-13_17-51-50](https://user-images.githubusercontent.com/12888227/27109580-1b379d02-5061-11e7-97cd-8fbac1267520.png)
![rpcs3_2017-06-13_17-52-00](https://user-images.githubusercontent.com/12888227/27109581-1b39721c-5061-11e7-93e7-8294383cf8ea.png)

**Comment by hcorion** [comment]
Not quite the same, NPUB30394 vs NPEB00435, but IMO that's enough of a difference to mark it as a linux-only bug. would still appreciate someone testing NPUB30394 on Windows.

**Comment by hcorion** [comment]
Issue occurs on Vulkan as well

**Comment by mrcmunir** [comment]
I can confirm this is also happen in Mesa3d driver and same spaming in the log unknown origin (0)

**Comment by toccata10** [comment]
R9 Fury. tested on win10 and radv (mesa stable 17.1.2). Same problem (see screenshot from win10):
![capture](https://user-images.githubusercontent.com/7478580/27252125-5738e1ce-5356-11e7-97fa-cb5dab6a9bec.PNG)
So, not linux specific.

**Comment by hcorion** [comment]
Dangit, this bug just keeps getting more confusing.

**Comment by hcorion** [comment]
Ah, turns out the bug was because I was using 1920x1080 resolution, after changing to 1280x720 the game scales properly.

**Comment by hcorion** [comment]
Closing issue, it's more a game bug with it being forced to scaled to 1920x1080.
