### ISSUE TITLE
Qt instability problems

### ISSUE THREAD

**Issue by hcorion** [RPCS3/rpcs3#2875]
Hi, 
There have been reports of Qt being unstable, this is to gather people's issues.

**WAIT! Before you post your report below, make sure to add the following**
- Windows version (including build number if your on Windows 10)
- RPCS3 build number
- Game name and game id (ex. NPUB02342)
- CPU and GPU
- Settings (PPU, SPU, Graphics backend, any additional graphics settings)
- What happens when you run the game? Crash? Black screen with 60fps?
- Include reproducibility information, for example, does it happen every time you run the game? Every time you startup RPCS3 and run the game? After you've already started 1 game in RPCS3? Randomly?

**NOTES:** 
- **DO NOT** report bugs about issues with lowered FPS with the Qt build.
- Make sure to test your game again with WxWidgets, you can find the last WxWidgets build here: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-4759/artifacts

**Comment by Kojikun1** [comment]
- Windows 10 pro 1703
- RPCS3 Build 0.0.2-4914 https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-4914/artifacts
- Naruto Ultima Ninja Storm [BLES00371]
- Intel Core i7 3630QM + GT650M
- Settings (PPU Interpreter (fast) , SPU Recompiler (ASMJIT), Vulkan and OpenGL
- Game crashes random
- With WxWidgets build here Works Last build that worked was this https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-4759/artifacts

**Comment by isshininu** [comment]
Windows 10, pro. build 1703 x64
RPCS3 https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-4927/artifacts
Demon's Souls BLES00932
Intel i-4700MQ, NVIDIA GEFORCE 840M

Random freezes when starting to boot the game. 
![_2017_06_16_19_09_34_320](https://user-images.githubusercontent.com/6324523/27232804-69a0e7e6-52c8-11e7-8f82-447d730cfe57.png)
Not specific to any used settings. Specific to Qt.

**Comment by Megamouse** [comment]
@isshininu please try again. some commits were made that could have fixed your problem and anything similar

**Comment by isshininu** [comment]
Ok, i'll try it today.
Also, it's worth to mention that UAC could affect perfomance of RPCS3, especially when RPCS3 placed in some folder in Program Files (even if it running from Administrator). At least i think so - after disabling UAC (EnableLUA=0) FPS problem was gone (there was a situation with DeS)

**Comment by isshininu** [comment]
![27](https://user-images.githubusercontent.com/6324523/27594144-206454f0-5b6a-11e7-85fd-718a8947f736.png)

Settings the same.

**Comment by Megamouse** [comment]
but the boot error is gone

**Comment by AniLeo** [comment]
Don't place RPCS3 in weird paths like Program Files <

**Comment by isshininu** [comment]
I have granted an absolute access to this folder for my account. So nothing wrong with Program Files.
Boot error (DX12) was gone after https://github.com/RPCS3/rpcs3/pull/2918/commits/6d3ae49702879bea752ab9fbab1218a90bdbe6ce

**Comment by HollowSoldier** [comment]
Delete your emu folder completely, download the latest build and start over with a clean state. It solved Qt instability for me. Just overwriting files every time must have caused some conflicts when going from GTK to Qt.

**Comment by hcorion** [comment]
@HollowSoldier It wasn't GTK, it was WxWidgets.

**Comment by scribam** [comment]
@hcorion Is there any issue left to be addressed?

**Comment by Megamouse** [comment]
I don't think there has ever been a real "QT Instability"

**Comment by AniLeo** [comment]
Closing, no real issue remaining here
