### ISSUE TITLE
[Windows 10][Vulkan] Laptop frozen on booting hatsune miku project diva.

### ISSUE THREAD

**Issue by thvardhan** [RPCS3/rpcs3#2878]
Hello,

**[Issue]** 
I've been having this issue since there was that notice of huge performance spike with Vulkan api. I've been trying to use it ever since but every time I boot hatsune miku project diva using Vulkan as my rendering api my laptop's screen freezes and game dont even boot completely. however it works fine with OpenGL and DirectX12.

**[Other game]**
I have tried running DOOM 2016 using vulkan api and it works fine.

![](https://cdn.discordapp.com/attachments/272035812277878785/324788624308830210/unknown.png)

**[Specification]**
RPCS3 - rpcs3-v0.0.2-2017-06-14-e8553500_win64 (4923 alpha build)
CPU - Intel core i5-7200U
GPU - GeForce 940MX , Driver - 382.33
RAM - 8gb
OS - 64bit windows 10 build 1703

**[Log]**
https://www.mediafire.com/?dzufzckgj7c3hbc
**[Config]**
https://gist.github.com/thvardhan/c59af0a3d9a80e9c7fa696188ef7916c

I have also noticed performance decrease using dx12. Before it used to reach ~27 fps but now it barely gets ~20 fps.

**Comment by Sora3100** [comment]
Do you mean your entire laptop freezes and you can't do anything on it but a hard reset?
In which case I had a similiar issue with Tales of Xillia 1/2 (didn't test other games), the workaround I found was to use an older driver and then it works.

**Comment by zminhquanz** [comment]
i'm using GTX 950 , but it isn't happen on Project Diva F on my Desktop , Vulkan API it better than DX 12 , i'm switch to DX 12 and perfomance decrease

**Comment by Nezarn** [comment]
@thvardhan maybe select your geforce 940MX in the options at "select graphics device"? (you don't have anything selected)

https://gist.github.com/thvardhan/c59af0a3d9a80e9c7fa696188ef7916c#file-rpsc3_vulkan_freeze_config-yml-L40

**Comment by Megamouse** [comment]
@Nezarn this is a bug I'm fixing right now. The graphics adapter is set but not saved to config. So that should not be the problem

**Comment by thvardhan** [comment]
@Sora3100 yeah it freezes and then I have to hard reset it.

also um @Megamouse can you tell me what I can fill there manually to make it select my graphics card?

**Comment by Megamouse** [comment]
Just write the exact GPU in there like this and save the config file. Close your Rpcs3. But do NOT press ok on the settings dialog, or else you will reset it to ""
After restarting rpcs3 it should stay filled in, as long as you wrote it right.

![adapter](https://user-images.githubusercontent.com/23019877/27223673-c1ee0186-5291-11e7-910d-fc67516fc2c9.png)

**Comment by thvardhan** [comment]
I made sure this stays like it. After restarting RPCS3 it auto-filled too and config stayed as shown in the picture but no luck. it still froze.

![capture](https://user-images.githubusercontent.com/17314986/27224239-aa7ce8d0-52b1-11e7-9282-12a3bdfc35d2.PNG)

**Comment by Megamouse** [comment]
at least we sorted out this possibility

**Comment by raveskirza** [comment]
Could you try with builds older than 0.0.2-4849

**Comment by thvardhan** [comment]
build 4848, issue persists.

**Comment by AniLeo** [comment]
You're not supposed to be using build 4849 is a mid-PR build, the final build from that PR is 0.0.2-4870 and the build before is 0.0.2-4856
Use https://rpcs3.net/builds to properly find older builds instead of AppVeyor history

**Comment by thvardhan** [comment]
While doing some testing, I downloaded the build 4513 which I remember was working without any problem. Apparently now that one is having this isssue as well. So I have reached the conclusion that its something else, not RPCS3's fault. I am really sorry for all the time I have wasted of you people. but what else could be the problem? maybe its just as @Sora3100 's saying graphic drivers? I guess I'll wait for the new drivers then.
Thanks a lot for all the help.

**Comment by Sora3100** [comment]
Older builds don't have the problem iirc, albeit I'd need to test again
But yes, reverting to an older nvidia drivers fixes the issue

**Comment by Epidal** [comment]
Can confirm.  Was having the same issues with HM:PD.  Rolling back to driver 378.49 fixed the freezing issue.  I've yet to try any newer drivers.

**Comment by blueskythlikesclouds** [comment]
Yes, reverting back to the driver Epidal mentioned also fixed the hard freeze for me (using Windows 10 1073), I can also confirm this.

**Comment by thvardhan** [comment]
oh I see, thanks for all the help but sadly I don't want to revert back as new drivers contain optimizations for Tekken 7 which I need so I guess I'll just wait for it to be fixed.

**Comment by oobol2000oo** [comment]
I have the same issue but my GPU is 930M :(

**Comment by oobol2000oo** [comment]
Fixed in RPCS3 v0.0.3-3-930ce4a

**Comment by thvardhan** [comment]
Yes, It's fixed. Thanks for all the hard work everyone! you guys are awesome!
