### ISSUE TITLE
shovel knight: graphical glitches with radv (linux)

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#2880]
RPCS3 v0.0.2-5282-f84f4ccd Alpha
R9 fury, latest mesa stable 17.1.2 with radv.
A few graphical glitches, specially when there are some waterfalls: the effect is replaced by a green portion.
You can try (it's at the beginning of the game, about the 3rd screen) by yourself.
On windows, same hardware, no pb with vulkan.
Linux with radv:
![shovel-02-non-ok](https://user-images.githubusercontent.com/7478580/27225851-57a0454a-529c-11e7-8196-077bbe12e8ea.png)
Windows with proprietary:
![shovel-01-ok](https://user-images.githubusercontent.com/7478580/27225854-59470d84-529c-11e7-88e1-7245c0f3436f.png)

**Comment by hcorion** [comment]
I feel like these kind of issues should be reported to radv, since the driver is at fault here, not the software.

**Comment by toccata10** [comment]
I'm not so sure. It looks more or less like this:
[https://bugs.freedesktop.org/show_bug.cgi?id=99467](url)
They say the game is doing something illegal (proprietary drivers have a lot of workaround game bugs if I understand correctly).
If I want to report the bug to mesa, I should include a fifo file. Otherwise, I don't think anyone will look at it. Do you know a way to record this fifo file with rpcs3 ?

**Comment by AniLeo** [comment]
Can you please retest?

**Comment by toccata10** [comment]
still the same on latest master. Next mesa is to be released soon. I'll see if it improves this pb.

**Comment by toccata10** [comment]
Tested today with rev5800 and mesa 17.2: same green pb with vulkan (and very low fps but that's another pb). Could not try on fbo build (freeze). If it's a mesa bug, I don't have enough knowledge to make an accurate bug report for them (chances that they install rpcs3 and have this game are super low...).

**Comment by kd-11** [comment]
Interesting that fbo freezes for you. I use radv for linux testing and vulkan seems to work fine afaict. As for performance, the SPIR-V we generate isn't optimal (even on windows, the GPU will report 100% usage on random simple scenes). There was talk of improving fbo alignment on radv by marek a while back but I don't know if its merged into mesa yet or whether it affects rpcs3 in any way. Either way, radv does state in the terminal that its not ready yet so idk.

**Comment by toccata10** [comment]
Just in case, it's my log file with your fbo build. It freezes soon after entering the 1st level
[RPCS3.log1-ShovelRadvFboBuild.gz](https://github.com/RPCS3/rpcs3/files/1290674/RPCS3.log1-ShovelRadvFboBuild.gz)

**Comment by toccata10** [comment]
Here's the bug for the mesa guys:
[https://bugs.freedesktop.org/show_bug.cgi?id=102891](url)
About the warning message: Radv has been conformant since may 2017:
[https://www.phoronix.com/scan.php?page=news_item&px=RADV-Vulkan-CTS-Conformant](url)
but it's not "officially certified", and surely not bug-free.
By the way, no freezes anymore with radv on master, but 20fps and some green parts.

**Comment by toccata10** [comment]
issue solved by updating to mesa 17.3.2.
