### ISSUE TITLE
GUI: Certain categories do not show in game list

### ISSUE THREAD

**Issue by clienthax** [RPCS3/rpcs3#2882]
EG system apps / some video apps
 youtube as example.

psn store shows as a "home" catagory, but opens the folder for the game instead of booting the bin.

**Comment by Megamouse** [comment]
Similar as other issue. Maybe Can merge to single issue

**Comment by Megamouse** [comment]
do you mean they don't show up at all? 
even in list mode?
because Grid mode only shows games at the moment

**Comment by clienthax** [comment]
Yep, YouTube doesn't show up at all on list mode, did on the qt versions

**Comment by Megamouse** [comment]
whats the category of youtube in wx?

**Comment by clienthax** [comment]
"AT"

**Comment by Megamouse** [comment]
Ah okay. There's a placeholder category called "Other" that was forgotten to add to the filters (the icons in toolbar).

What could AT stand for? And is there a list for those somewhere in PS3 documentation?

**Comment by Megamouse** [comment]
![image](https://user-images.githubusercontent.com/23019877/27260486-9c7225d4-542d-11e7-9a73-7a5f40556d7e.png)
