### ISSUE TITLE
Unable to set custom configuration for non 'hdd games'

### ISSUE THREAD

**Issue by clienthax** [RPCS3/rpcs3#2883]
Crunchyroll / Anything in the Audio / Visual catagorys

**Comment by Megamouse** [comment]
Okay this was prevented and asked multiple times beforehand........

Simple fix

**Comment by Megamouse** [comment]
This should represent the present situation:
![unknown](https://user-images.githubusercontent.com/23019877/27251627-2e10daf0-534b-11e7-8f42-78bdecbd6c0b.png)

Please discuss changes

**Comment by clienthax** [comment]
Something like this?
![Image](http://i.imgur.com/O9BzMlo.png)
