### ISSUE TITLE
Vulkan pipeline result is C4650720h

### ISSUE THREAD

**Issue by M9k** [RPCS3/rpcs3#2889]
When I use Vulkan rendering instead D3D12 it doestn't work anymore, it just show a white screen.
It work fine with v0.0.2-2017-05-26-3f836c79_win64 (4738), but with the last build or older (like v0.0.2-2017-06-13-4d53873b (4921)) i get the error:

F {rsx::thread} : class std::runtime_error thrown: Assertion failed! Result is C4650720h
(in file c:\rpcs3\rpcs3\emu\rsx\vk\VKProgramBuffer.h:146)
The line is:
CHECK_RESULT(vkCreateGraphicsPipelines(dev, nullptr, 1, &info, NULL, &pipeline));

My settings are:
Video:
  Renderer: Vulkan
  Resolution: 1280x720
  Aspect ratio: 16:9
  Frame limit: 59.94
  Write Color Buffers: false
  Write Depth Buffer: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Log shader programs: false
  VSync: false
  Debug output: false
  Debug overlay: false
  Use Legacy OpenGL Buffers (Debug): false
  Use GPU texture scaling: false
  D3D12:
    Adapter: NVIDIA GeForce GTX 950M
  Vulkan:
    Adapter: NVIDIA GeForce GTX 950M

**Comment by AniLeo** [comment]
What game(s)? Did you try game/TEST12345 samples first?

**Comment by kacek** [comment]
also: are your drivers updated?

**Comment by M9k** [comment]
With every game, like Disgaea D2, Disgaea 3, DeceptionIV, Persona 5, maybe the issue is my video driver, I try to update.

**Comment by AniLeo** [comment]
(Obviously) you have to be using latest drivers before reporting an issue, as a lot of times that alone solves it

**Comment by M9k** [comment]
Yes, it was a outdated driver problem, with Nvidia 382.53 it work really fine, sorry for the trouble and thanks for the support!
