### ISSUE TITLE
Rpcs3 Last Build ( Fatal Error)

### ISSUE THREAD

**Issue by HMDRZA** [RPCS3/rpcs3#2891]
Hi , First of all my English isn't that good so forgive me ...
When i try to open the rpcs3.exe i keep getting this fatal error i did everything that i can to fix it but i couldn't  .. Please Help me.
Error :
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xE06D7363.
Exception address: 00007ffca15c9e08.
ExceptionInformation[0x0]: 0000000019930520.
ExceptionInformation[0x1]: 000000000376f860.
ExceptionInformation[0x2]: 00000000018495f0.
ExceptionInformation[0x3]: 0000000000010000.
Instruction address: 00007ffca15c9e08.
Function address: 00007ffca15c9da0 (base+0x69da0).
Module name: 'KERNELBASE.dll'.
Module base: 00007ffca1560000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

Screenshot : 
![screenshot 1](https://user-images.githubusercontent.com/29523101/27263199-83b881ae-5479-11e7-8619-a491e56b4dd6.png)

**Comment by SakataGintokiYT** [comment]
@HMDRZA 
This problem has been fixed.

Download the latest build from the official site: 
https://rpcs3.net/download
