### ISSUE TITLE
Installing unlock PKG replaces HDD game to Game Data

### ISSUE THREAD

**Issue by Nikorasu95** [RPCS3/rpcs3#2899]
When installing a unlock pkg it replaces the HDD game to Game Data and I can no longer right click the game and boot it. I would have to manually find the folder in RPCS3\dev_hdd0\game and click the folder and boot it that way with Boot>Boot Game>Select Folder. Games that are affected after installing the unlock pkg is Scott Pilgrim vs the World, and Beyond Good and Evil. This is very annoying that I have to manually find the game folder and boot it instead of just booting the game from the RPCS3 game list. Also, I can't set the settings for both of these games because of this issue. Can this issue possibly be fixed in a future build?

**Comment by clienthax** [comment]
Can confirm that I've run into this in the past.

**Comment by Megamouse** [comment]
I wonder why it changes to game data and does not say hdd game

**Comment by hcorion** [comment]
I don't have this issue on Linux with Beyond Good & Evil HD

**Comment by Nikorasu95** [comment]
Well, it's certainly a problem on Windows.  I even downloaded PSN PKG Decryptor & Extractor and copied/replaced the files over to the game folder in  RPCS3\dev_hdd0\game, and even still it will show up as Game Data in the RPCS3 game list.

**Comment by AniLeo** [comment]
Because it writes new PARAM.SFO... Backup the old one and replace it in the end and that's no longer an issue

**Comment by Nikorasu95** [comment]
Thank's, that worked! You are a genius! I had no idea PARAM.SFO had some something to do with it.

**Comment by hcorion** [comment]
K, close issue please.
