### ISSUE TITLE
Fatal Error Unhandled Win32 exception 0xC000001D.

### ISSUE THREAD

**Issue by snoopy101x** [RPCS3/rpcs3#2907]
`---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC000001D.
Exception address: 000000000028dbbb.
Instruction address: 000000000028dbbb.
Function address: 000000000028dab0 (base+0x27dab0).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

Illegal instruction exception occured.
Note that your CPU must support SSSE3 extension.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------
`

AMD Phenom II X4 945 Processor 3.00 GHz

According to CPU-Z

Instructions: MMX(+), 3DNow!(+), SSE, SSE2, SSE3, SSE4A, x86-64, AMD-V

Get this error every time I try to boot anything. TIA.

**Comment by SakataGintokiYT** [comment]
Buy better cpu

**Comment by AniLeo** [comment]
>AMD Phenom II X4 945 Processor 3.00 GHz

**Note that your CPU must support SSSE3 extension.**
