### ISSUE TITLE
Demon Souls PSN NPUB30910 thinks it is the disk game and won't launch.

### ISSUE THREAD

**Issue by Ember2528** [RPCS3/rpcs3#2908]
Upon installing the pkg for the game rpcs3 states that the game's serial is BLUS30443 and complains that is cannot find the game's icon.
Upon booting the game the log shows that it is looking in the wrong directory and shows a black screen.
[log.txt](https://github.com/RPCS3/rpcs3/files/1099358/log.txt)

**Comment by AniLeo** [comment]
What you uploaded isn't a full log and this issue is known, PSN versions of DeS don't work as they try to mount their contents as a disc game.

**Comment by Ember2528** [comment]
Sorry for this then, is ther anything that can be done about it immediately?

**Comment by AniLeo** [comment]
Unfortunately no, until we find what the hell is the game trying to do. 
You can try "converting" the game to a disc game by moving some files around to see if it works.

**Comment by Ember2528** [comment]
Alright then, thanks for the help
