### ISSUE TITLE
Posting this again because I didn't even get a chance to respond.

### ISSUE THREAD

**Issue by snoopy101x** [RPCS3/rpcs3#2912]
Please read carefully before replying and just closing it.

`---------------------------
Fatal error

Unhandled Win32 exception 0xC000001D.
Exception address: 000000000028dbbb.
Instruction address: 000000000028dbbb.
Function address: 000000000028dab0 (base+0x27dab0).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

Illegal instruction exception occured.
Note that your CPU must support SSSE3 extension.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.

OK

`

AMD Phenom II X4 945 Processor 3.00 GHz

According to CPU-Z

**Instructions: MMX(+), 3DNow!(+), SSE, SSE2, SSE3, SSE4A, x86-64, AMD-V**

Get this error every time I try to boot anything. TIA.

And according to [cpu-world](http://www.cpu-world.com/CPUs/K10/AMD-Phenom%20II%20X4%20945%20-%20HDX945FBK4DGI%20(HDX945FBGIBOX).html) one of the features is 

Features	

- MMX instructions
- Extensions to MMX
- 3DNow! technology
- Extensions to 3DNow!
- SSE / Streaming SIMD Extensions
- SSE2 / Streaming SIMD Extensions 2
- **SSE3 / Streaming SIMD Extensions 3** **<---------------**
- SSE4a  ? 
- AMD64 / AMD 64-bit technology  ? 
- EVP / Enhanced Virus Protection  ? 
- AMD-V / AMD Virtualization technology

**Comment by Megamouse** [comment]
SSSE3

**Comment by Zangetsu38** [comment]
yes, no confond SSE3 and SSSE3, similary name but not same ^^

**Comment by AniLeo** [comment]
Please check the instructions carefully. 
SSE3 is NOT SSSE3.

**Comment by Zangetsu38** [comment]
@snoopy101x only one solution, buy news cpu :) Ryzen or other ^^
