### ISSUE TITLE
[REGRESSION] FONTS differs between OpenGL and Vulkan renderers.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#2917]
As you can see, game fonts renders different when choosing OpenGL or Vulkan/D3D12 options.

Vulkan, everything is correct.

![10](https://user-images.githubusercontent.com/6324523/27557410-9461da12-5aca-11e7-921d-39a439bbe764.png)

OpenGL, broken..

![8](https://user-images.githubusercontent.com/6324523/27557422-9ecdf7d8-5aca-11e7-9000-e6447f3a0e9d.png)

Also, seems to be a regression, so i'm adding this name to title.

game - BLES00932 Demon's Souls with latestmaster build

**Comment by AniLeo** [comment]
I think kd-11 is aware of this one already, not game-specific.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/2918
