### ISSUE TITLE
Jogos

### ISSUE THREAD

**Issue by lfabiobz** [RPCS3/rpcs3#2919]
I need to know how i can roll a game with two or mor parts. What i need to run and what i need to do. Thanks for your help

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
