### ISSUE TITLE
[Regression] Dark Souls [BLES01765] changed from "In-game" to "Loadable".

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#2920]
Ended with

F {MFC Thread} MEM: Access violation reading location 0x2424080

no matter what settings were used.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1105193/RPCS3.zip)

**Comment by AniLeo** [comment]
In what build did the regression happen?

**Comment by isshininu** [comment]
Hm, i need to test interval of builds to check it...

**Comment by isshininu** [comment]
Sowwy, false alarm.
It's used to be ingame only with "load liblv2.sprx only".
