### ISSUE TITLE
Handling Updates for Disc Games

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#2921]
Currently RPCS3 doesn't handle updates for disc games, which are installed onto dev_hdd0/game/GameID.

Booting the disc won't check for the update and booting the update directly will fail as dev_bdvd isn't mounted. Manually editing config.yml and adding the disc game's path doesn't seem to help as it doesn't get mounted as well.

I'm almost sure the way this should be handled is that when the disc is booted, either PS3_DISC.sfb or PARAM.SFO has to be read to obtain the Game ID and then dev_hdd0/game/GameID checked to see if there exists an EBOOT.bin in dev_hdd0/game/GameID/USRDIR. If there is, it boots that EBOOT while mounting the disc path to dev_bdvd.

**Comment by Megamouse** [comment]
I already check for disc games in my PR and it's really easy to find the EBOOT.BIN from there.
I'm just unsure which paths have to be exchanged in this case.
The whole file uses the path in many different places... so which need to be untouched?

**Comment by isshininu** [comment]
hdd0/disc for disc games
hdd0/game for gamedata installed

**Comment by Zangetsu38** [comment]
yes good idea, same like on PS3, boot Bd and check update and boot with Eboot.bin in folder update

**Comment by AniLeo** [comment]
Solved by #2957
