### ISSUE TITLE
Time Crisis 4 - Graphics Bug [Vulkan & DX12] (Post-processing, most likely)

### ISSUE THREAD

**Issue by billywws** [RPCS3/rpcs3#2922]
**RPCS3 v0.0.2-13-431a1ef Alpha**
Used both Interpreter (fast) and Recompiler, produces same results.

The game's graphics are incredibly bright, so it is near impossible to see the enemies on-screen.
![untitled](https://user-images.githubusercontent.com/29743068/27616652-2a83fa46-5ba9-11e7-9d65-188effa2ceb1.png)
However, in the pause menu, the game becomes visible.
![3](https://user-images.githubusercontent.com/29743068/27616658-34c94e0c-5ba9-11e7-832a-2c5f6f15d4b7.png)
I believe this is due to bloom effects being too powerful here.

**Comment by kd-11** [comment]
Retest with current master

**Comment by Zangetsu38** [comment]
same engine ?
https://youtu.be/sHQVS-e58Ow

**Comment by billywws** [comment]
Retested with the current master, still same result.
