### ISSUE TITLE
sys_fs_fcntl(): Unknown operations

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#2928]
**0xE0000025 (cellFsSdataOpenWithVersion)** - Implemented by #10172
- PlayStation Store [NPIA00025]
`sys_fs_fcntl(): Unknown operation 0xe0000025 (fd=4294967295, arg=*0xd0159250, size=0x30)`

---

**0xC000001A (cellFsSetDiscReadRetrySetting)**
- LittleBigPlanet Karting [BCES01422]
`sys_fs_fcntl(): Unknown operation 0xc000001a (fd=4294967295, arg=*0xd0040b30, size=0x18)`
- Sleeping Dogs [NPEB01046]
`sys_fs_fcntl(): Unknown operation 0xc000001a (fd=4294967295, arg=0xd0040960, size=0x18)`

---

**0xC0000008 (cellFsSetDefaultContainer, cellFsSetIoBuffer, cellFsSetIoBufferFromDefaultContainer)**
- Young Justice: Legacy [BLES01808]
`sys_fs_fcntl(): Unknown operation 0xc0000008 (fd=4294967295, arg=*0xd007d8f0, size=0x28)`
`sys_fs_fcntl(): Unknown operation 0xc0000008 (fd=17, arg=*0xd007d8e0, size=0x28)`
`sys_fs_fcntl(): Unknown operation 0xc0000008 (fd=17, arg=*0xd007e250, size=0x28)`
- Puzzle Dimension [NPEB00401]
`sys_fs_fcntl(): Unknown operation 0xc0000008 (fd=3, arg=*0xd003f8e0, size=0x28)`
`sys_fs_fcntl(): Unknown operation 0xc0000008 (fd=3, arg=*0xd003f900, size=0x28)`

**Comment by clienthax** [comment]
Playstation Store [NPIA00025]
```
·F 0:00:05.326123 {PPU[0x1000013] Thread (error_dialog) [0x0071f174]} sys_fs: sys_fs_fcntl(): Unknown operation 0xe0000025 (fd=4294967295, arg=*0xd0159250, size=0x30)
```

**Comment by Asinin3** [comment]
Puzzle Dimension
`F {PPU[0x1000000] Thread (main_thread) [0x017139d4]} sys_fs: sys_fs_fcntl(): Unknown operation 0xc0000008 (fd=3, arg=*0xd003f8e0, size=0x28)`
and
`F {PPU[0x1000000] Thread (main_thread) [0x017139d4]} sys_fs: sys_fs_fcntl(): Unknown operation 0xc0000008 (fd=3, arg=*0xd003f900, size=0x28)`

Recieved around 15 of these errors after starting first level within a few seconds however the game kept running.

**Comment by dio-gh** [comment]
Retest.

**Comment by AniLeo** [comment]
No need to, I checked the code, those are still unimplemented and the code still behaves the same way

**Comment by AniLeo** [comment]
Checked current code once again, 0xC0000008 and 0xC000001A are still unimplemented
