### ISSUE TITLE
Star Ocean Integrity and Faithlessness

### ISSUE THREAD

**Issue by kurdischerjapaner** [RPCS3/rpcs3#2931]
F {PPU[0x1000000] Thread (main_thread) [0x00016718]} MEM: Access violation reading location 0x0

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.

**Comment by kurdischerjapaner** [comment]
why closed? this a new error
