### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by PISTOLSZ** [RPCS3/rpcs3#2933]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault writing location 0000000000000000 at 0000000000000000.
Instruction address: 0000000000000000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

This is the entire error that I get. Ask me for any information you need I'll try to reply ASAP. Trying to run Demon's Souls

**Comment by Farseer2** [comment]
Please send RPCS3.log with your issues, there isn't a lot of info in your post

**Comment by AniLeo** [comment]
Please use the forums for support. The error by itself means nothing, you'll need a full log as described above when creating the support thread. 
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.

**Comment by yancylow** [comment]
running RPCS3 in Windows 8 Compatibility fixed this error for me
