### ISSUE TITLE
Feature request : 21:9 aspect ratio 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2934]
For resolution 2560x1080 , 3440x1440  ultrawide .

http://www.emunewz.net/forum/showthread.php?tid=188908

**Comment by Margen67** [comment]
Maybe related: #2282

**Comment by MrDiffin** [comment]
I think a "stretch to screen" option would be way better, as it would cover all sorts of weird and wonderful aspect ratios e.g. 5760x1080 with just one option. This is how Dolphin handles things as well.

**Comment by raven02** [comment]
It is currently working in DX12 which no aspect ratio so it stretch by default.

**Comment by Margen67** [comment]
Fixed by #3557?

**Comment by Renusek** [comment]
Not possible afaik, that's too hacky and needs to be done per game.

**Comment by Kilowog01** [comment]
I support the idea, also use monitor 21: 9

**Comment by Margen67** [comment]
This can be done with Cheat Engine: https://forums.rpcs3.net/thread-199065.html
