### ISSUE TITLE
PPU LLVM Initial D Extreme Stage - MEM: Access violation writing location 0x0

### ISSUE THREAD

**Issue by lolxapple** [RPCS3/rpcs3#2935]
Cannot start the game using LLVM. Works on Interpreter. 
```
System
Windows 10 v1607 14393.1358
i3-6100 @ 3.7Ghz
GTX 960 4GB
8GB RAM
```
[Log](https://pastebin.com/aFDYVHAC)

**Comment by AniLeo** [comment]
Please use #2909

**Comment by AniLeo** [comment]
Closing since it's a duplicate, there's #2909 for tracking LLVM discrepancies.
