### ISSUE TITLE
Framebuffer format mismatch in vulkan

### ISSUE THREAD

**Issue by mrcmunir** [RPCS3/rpcs3#2937]
Actually the code returned problem with VK_FORMAT_B8G8R8A8_SRGB that does not match the format of VK_FORMAT_R5G6B5_UNORM_PACK16

>RSX: ERROR: [DS] Code 155191008 : vkCreateFramebuffer(): VkFramebufferCreateInfo attachment #0 has format of VK_FORMAT_B8G8R8A8_SRGB that does not match the format of VK_FORMAT_R5G6B5_UNORM_PACK16 used by the corresponding attachment for renderPass (0x53). The spec valid usage text states 'Any given element of pAttachments must have been created with an VkFormat value that matches the VkFormat specified by the corresponding VkAttachmentDescription in renderPass' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkFramebufferCreateInfo-pAttachments-00880)

Needed rewrite this part for the work 
Regards
Mrc.

**Comment by kd-11** [comment]
Im pretty sure I solved this issue a while back unless I forgot to submit those commits somehow. You're still getting this with current master?

**Comment by mrcmunir** [comment]
@kd-11 Yes I'm update git pull current master RPCS3 v0.0.2-5385-190a59ce and I had this error 
![captura de 2017-07-02 14-06-14](https://user-images.githubusercontent.com/1274014/27769669-a869e798-5f2f-11e7-8fb6-78bf6ecfb869.png)

**Comment by kd-11** [comment]
Do not use "force high precision z" - thats what is causing the crash here, not the format mismatch. The fix for the other issue is not yet committed it seems, should be in a future merge.

**Comment by kd-11** [comment]
Closed via https://github.com/RPCS3/rpcs3/pull/2962
