### ISSUE TITLE
Problem with: RSX: Failed to compile shader: 0:1(10): error: GLSL 4.20 is not supported

### ISSUE THREAD

**Issue by CdK1** [RPCS3/rpcs3#2940]
Hi *. I have the following error after loading a game:

RPCS3 v0.0.2-5385-190a59ce Alpha
S LDR: Boot Game: boot done.
U {PPU[0x1000000] Thread (main_thread) [0x028841c4]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x02495088]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x02495090]} sysPrxForUser TODO: _sys_process_at_Exitspawn
E {PPU[0x1000000] Thread (main_thread) [0x02490088]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
U {PPU[0x1000000] Thread (main_thread) [0x024946d0]} sceNp2 TODO: sceNpMatching2Init2(poolsize=0x0, priority=0, param=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x02493dc0]} sceNp TODO: sceNpBasicRegisterHandler
E {PPU[0x1000000] Thread (main_thread) [0x02490088]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x02490088]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x02490088]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {PPU[0x1000000] Thread (main_thread) [0x02490088]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
U {PPU[0x1000000] Thread (main_thread) [0x024940f8]} sceNp TODO: sceNpManagerRegisterCallback(callback=*0x1676e38, arg=*0x29fe3000)
E {PPU[0x1000000] Thread (main_thread) [0x02490088]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (10)
E {rsx::thread} RSX: Failed to compile vertex shader: 0:1(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 4.00, 4.10, 1.00 ES, and 3.00 ES

E {rsx::thread} RSX: Failed to compile shader: 0:1(10): error: GLSL 4.20 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 4.00, 4.10, 1.00 ES, and 3.00 ES

F {rsx::thread} N2gl4glsl14link_exceptionE thrown: linkage failed: 'error: linking with uncompiled shadererror: linking with uncompiled shader'

My system:

root@Carlitos:/etc/X11# cd /home/CdK1/Github/rpcs3/
root@Carlitos:/home/CdK1/Github/rpcs3# uname -a
Linux Carlitos 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux
root@Carlitos:/home/CdK1/Github/rpcs3# 
OpenGL:
root@Carlitos:/home/CdK1/Github/rpcs3# glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD ARUBA (DRM 2.48.0 / 4.9.0-3-amd64, LLVM 4.0.1)
OpenGL core profile version string: 4.1 (Core Profile) Mesa 17.1.3
OpenGL core profile shading language version string: 4.10
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.1.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.1.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
root@Carlitos:/home/CdK1/Github/rpcs3#

I compile rpcs3: 

 cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_C_COMPILER="clang-4.0" -DCMAKE_CXX_COMPILER="clang++-4.0" && make install

any ideas?, thx!

**Comment by AniLeo** [comment]
Please read [the guidelines](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) for contributing. What hardware are you using?

**Comment by AniLeo** [comment]
I'm closing this since it's shown that your GPU lacks OGL 4.3 support. 
Feel free to reopen if this is an actual issue.

**Comment by CdK1** [comment]
AniLeo: 

root@Carlitos:/home/CdK1# lspci | grep Rade
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Richland [Radeon HD 8650G]
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mars [Radeon HD 8670A/8670M/8750M]
root@Carlitos:/home/CdK1#

**Comment by twdarkeh** [comment]
That only supports up to OpenGL 4.2. Needs 4.3 minimum to work.

**Comment by kd-11** [comment]
@CdK1 use MESA_GLSL_VERSION_OVERRIDE and MESA_GL_VERSION_OVERRIDE. If that doesnt work for you nothing will.
