### ISSUE TITLE
loader.c made C2220 error while building Vulkan-build.

### ISSUE THREAD

**Issue by whjhs1010203** [RPCS3/rpcs3#2943]
Hi !
I met a terrible trouble in my computer with Chinese system in recent several months.
Cause building error because of `loader.c`'s special characters.
It was lead to warning code C4819 and then caused C2220.
It is not important problem, I just inform everyone having this error.

The post looks terrible, bad grammar and simple vocabulary, I'm so sorry.
In the end, 
Thanks for persons working hard for rpcs3.

**Comment by hcorion** [comment]
What version of Visual Studio are you using?
Can you post the full build log?

**Comment by whjhs1010203** [comment]
Hi ! @hcorion 
I use 2015 and conversion to English, but log still have Chinese. 
Thanks lots of.
> 1>------ Build started: Project: Vulkan-build, Configuration: Release x64 ------
1>  -- The C compiler identification is MSVC 19.0.24215.1
1>  -- The CXX compiler identification is MSVC 19.0.24215.1
1>  -- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
1>  -- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
1>  -- Detecting C compiler ABI info
1>  -- Detecting C compiler ABI info - done
1>  -- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
1>  -- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
1>  -- Detecting CXX compiler ABI info
1>  -- Detecting CXX compiler ABI info - done
1>  -- Detecting CXX compile features
1>  -- Detecting CXX compile features - done
1>  -- Found PythonInterp: C:/Users/r2682/AppData/Local/Programs/Python/Python36/python.exe (found suitable version "3.6.1", minimum required is "3")
1>  -- Looking for secure_getenv
1>  -- Looking for secure_getenv - not found
1>  -- Looking for __secure_getenv
1>  -- Looking for __secure_getenv - not found
1>  -- Configuring done
1>  -- Generating done
1>  -- Build files have been written to: D:/test_rpcs3/rpcs3/Vulkan/Vulkan-build
1>  Microsoft (R) Build Engine version 14.0.25420.1
1>  Copyright (C) Microsoft Corporation. 著作權所有，並保留一切權利。
1>
1>  已經開始建置於 2017/7/4 上午 11:15:11。
1>       1>節點 1 (build 目標) 上的專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\ALL_BUILD.vcxproj"。
1>       1>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\ALL_BUILD.vcxproj" (1) 正在節點 1 (預設目標) 上建置 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\ZERO_CHECK.vcxproj" (2)。
1>       2>PrepareForBuild:
1>           正在建立目錄 "x64\Release\ZERO_CHECK\"。
1>           正在建立目錄 "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\"。
1>         InitializeBuildStatus:
1>           由於指定了 "AlwaysCreate"，因此正在建立 "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild"。
1>         CustomBuild:
1>           Checking Build System
1>           CMake does not need to re-run because D:/test_rpcs3/rpcs3/Vulkan/Vulkan-build/CMakeFiles/generate.stamp is up-to-date.
1>           CMake does not need to re-run because D:/test_rpcs3/rpcs3/Vulkan/Vulkan-build/loader/CMakeFiles/generate.stamp is up-to-date.
1>         FinalizeBuildStatus:
1>           正在刪除檔案 "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild"。
1>           正在變更時間戳記 "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate"。
1>       2>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\ZERO_CHECK.vcxproj" (預設目標) 建置完成。
1>       1>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\ALL_BUILD.vcxproj" (1) 正在節點 3 (預設目標) 上建置 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-norm.vcxproj" (4)。
1>       4>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-norm.vcxproj" (4) 正在節點 3 (預設目標) 上建置 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\generate_helper_files.vcxproj" (6)。
1>       6>PrepareForBuild:
1>           正在建立目錄 "x64\Release\generate_helper_files\"。
1>           正在建立目錄 "x64\Release\generate_helper_files\generate.CC45EAED.tlog\"。
1>       1>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\ALL_BUILD.vcxproj" (1) 正在節點 2 (預設目標) 上建置 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj" (5)。
1>       5>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj" (5) 正在節點 2 (預設目標) 上建置 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader_gen_files.vcxproj" (7)。
1>       7>PrepareForBuild:
1>           正在建立目錄 "x64\Release\loader_gen_files\"。
1>       6>InitializeBuildStatus:
1>           由於指定了 "AlwaysCreate"，因此正在建立 "x64\Release\generate_helper_files\generate.CC45EAED.tlog\unsuccessfulbuild"。
1>       7>PrepareForBuild:
1>           正在建立目錄 "x64\Release\loader_gen_files\loader_gen_files.tlog\"。
1>         InitializeBuildStatus:
1>           由於指定了 "AlwaysCreate"，因此正在建立 "x64\Release\loader_gen_files\loader_gen_files.tlog\unsuccessfulbuild"。
1>       6>CustomBuild:
1>           Building Custom Rule D:/test_rpcs3/rpcs3/Vulkan/Vulkan-LoaderAndValidationLayers/CMakeLists.txt
1>       7>CustomBuild:
1>           Building Custom Rule D:/test_rpcs3/rpcs3/Vulkan/Vulkan-LoaderAndValidationLayers/loader/CMakeLists.txt
1>       6>CustomBuild:
1>           CMake does not need to re-run because D:/test_rpcs3/rpcs3/Vulkan/Vulkan-build/CMakeFiles/generate.stamp is up-to-date.
1>           Generating vk_enum_string_helper.h
1>       7>CustomBuild:
1>           CMake does not need to re-run because D:/test_rpcs3/rpcs3/Vulkan/Vulkan-build/loader/CMakeFiles/generate.stamp is up-to-date.
1>           Generating vk_loader_extensions.h
1>           * Building vk_loader_extensions.h
1>           * Generated vk_loader_extensions.h
1>           Generating vk_loader_extensions.c
1>       6>CustomBuild:
1>           * Building vk_enum_string_helper.h
1>           * Generated vk_enum_string_helper.h
1>           Generating vk_struct_size_helper.h
1>           * Building vk_struct_size_helper.h
1>           * Generated vk_struct_size_helper.h
1>       7>CustomBuild:
1>           * Building vk_loader_extensions.c
1>           * Generated vk_loader_extensions.c
1>       6>CustomBuild:
1>           Generating vk_struct_size_helper.c
1>       7>FinalizeBuildStatus:
1>           正在刪除檔案 "x64\Release\loader_gen_files\loader_gen_files.tlog\unsuccessfulbuild"。
1>           正在變更時間戳記 "x64\Release\loader_gen_files\loader_gen_files.tlog\loader_gen_files.lastbuildstate"。
1>       7>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader_gen_files.vcxproj" (預設目標) 建置完成。
1>       6>CustomBuild:
1>           * Building vk_struct_size_helper.c
1>           * Generated vk_struct_size_helper.c
1>           Generating vk_safe_struct.h
1>           * Building vk_safe_struct.h
1>           * Generated vk_safe_struct.h
1>           Generating vk_safe_struct.cpp
1>           * Building vk_safe_struct.cpp
1>           * Generated vk_safe_struct.cpp
1>           Generating vk_object_types.h
1>           * Building vk_object_types.h
1>           * Generated vk_object_types.h
1>           Generating vk_layer_dispatch_table.h
1>           * Building vk_layer_dispatch_table.h
1>           * Generated vk_layer_dispatch_table.h
1>           Generating vk_dispatch_table_helper.h
1>           * Building vk_dispatch_table_helper.h
1>           * Generated vk_dispatch_table_helper.h
1>           Generating vk_extension_helper.h
1>           * Building vk_extension_helper.h
1>           * Generated vk_extension_helper.h
1>         FinalizeBuildStatus:
1>           正在刪除檔案 "x64\Release\generate_helper_files\generate.CC45EAED.tlog\unsuccessfulbuild"。
1>           正在變更時間戳記 "x64\Release\generate_helper_files\generate.CC45EAED.tlog\generate_helper_files.lastbuildstate"。
1>       6>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\generate_helper_files.vcxproj" (預設目標) 建置完成。
1>       4>PrepareForBuild:
1>           正在建立目錄 "loader-norm.dir\Release\"。
1>           正在建立目錄 "loader-norm.dir\Release\loader-norm.tlog\"。
1>         InitializeBuildStatus:
1>           由於指定了 "AlwaysCreate"，因此正在建立 "loader-norm.dir\Release\loader-norm.tlog\unsuccessfulbuild"。
1>         CustomBuild:
1>           Building Custom Rule D:/test_rpcs3/rpcs3/Vulkan/Vulkan-LoaderAndValidationLayers/loader/CMakeLists.txt
1>           CMake does not need to re-run because D:/test_rpcs3/rpcs3/Vulkan/Vulkan-build/loader/CMakeFiles/generate.stamp is up-to-date.
1>       1>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\ALL_BUILD.vcxproj" (1) 正在節點 4 (預設目標) 上建置 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-opt.vcxproj" (8)。
1>       8>PrepareForBuild:
1>           正在建立目錄 "loader-opt.dir\Release\"。
1>           正在建立目錄 "loader-opt.dir\Release\loader-opt.tlog\"。
1>       4>ClCompile:
1>           D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /I"D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\include" /I"D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader" /I"D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader" /I"D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build" /nologo /W3 /WX /O2 /Ob2 /D WIN32 /D _WINDOWS /D _CRT_SECURE_NO_WARNINGS /D NDEBUG /D VK_USE_PLATFORM_WIN32_KHR /D WIN32_LEAN_AND_MEAN /D "API_NAME=\"Vulkan\"" /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"loader-norm.dir\Release\\" /Fd"loader-norm.dir\Release\loader-norm.pdb" /Gd /TC /errorReport:queue   /w34456 /w34701 /w34703 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\extension_manual.c" "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\loader.c" "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\trampoline.c" "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\wsi.c" "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\debug_report.c" "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\cJSON.c" "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\murmurhash.c" "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\dirent_on_windows.c"
1>       8>InitializeBuildStatus:
1>           由於指定了 "AlwaysCreate"，因此正在建立 "loader-opt.dir\Release\loader-opt.tlog\unsuccessfulbuild"。
1>         CustomBuild:
1>           Building Custom Rule D:/test_rpcs3/rpcs3/Vulkan/Vulkan-LoaderAndValidationLayers/loader/CMakeLists.txt
1>           CMake does not need to re-run because D:/test_rpcs3/rpcs3/Vulkan/Vulkan-build/loader/CMakeFiles/generate.stamp is up-to-date.
1>       4>ClCompile:
1>           extension_manual.c
1>       8>ClCompile:
1>           D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /I"D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\include" /I"D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader" /I"D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader" /I"D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build" /nologo /W3 /WX /O2 /Ob2 /D WIN32 /D _WINDOWS /D _CRT_SECURE_NO_WARNINGS /D NDEBUG /D VK_USE_PLATFORM_WIN32_KHR /D WIN32_LEAN_AND_MEAN /D "API_NAME=\"Vulkan\"" /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"loader-opt.dir\Release\\" /Fd"loader-opt.dir\Release\loader-opt.pdb" /Gd /TC /errorReport:queue   /w34456 /w34701 /w34703 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\dev_ext_trampoline.c" "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\phys_dev_ext.c"
1>           dev_ext_trampoline.c
1>       4>ClCompile:
1>           loader.c
1>       8>ClCompile:
1>           phys_dev_ext.c
1>           Generating Code...
1>D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\loader.c(2005): error C2220: warning treated as error - no 'object' file generated [D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-norm.vcxproj]
1>D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\loader.c(2005): warning C4819: The file contains a character that cannot be represented in the current code page (950). Save the file in Unicode format to prevent data loss [D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-norm.vcxproj]
1>           trampoline.c
1>         Lib:
1>           D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\Lib.exe /OUT:"loader-opt.dir\Release\loader-opt.lib" /NOLOGO /MACHINE:X64   /machine:x64 "loader-opt.dir\Release\dev_ext_trampoline.obj"
1>           "loader-opt.dir\Release\phys_dev_ext.obj"
1>       4>ClCompile:
1>           wsi.c
1>           debug_report.c
1>       8>Lib:
1>           loader-opt.vcxproj -> D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-opt.dir\Release\loader-opt.lib
1>         FinalizeBuildStatus:
1>           正在刪除檔案 "loader-opt.dir\Release\loader-opt.tlog\unsuccessfulbuild"。
1>           正在變更時間戳記 "loader-opt.dir\Release\loader-opt.tlog\loader-opt.lastbuildstate"。
1>       8>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-opt.vcxproj" (預設目標) 建置完成。
1>       4>ClCompile:
1>           cJSON.c
1>           murmurhash.c
1>           dirent_on_windows.c
1>           Generating Code...
1>       4>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-norm.vcxproj" (預設目標) 建置完成 -- 失敗。
1>       5>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\vulkan-1.vcxproj" (預設目標) 建置完成 -- 失敗。
1>       1>專案 "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\ALL_BUILD.vcxproj" (build 目標) 建置完成 -- 失敗。
1>
1>  建置失敗。
1>
1>         "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\ALL_BUILD.vcxproj" (build 目標) (1) ->
1>         "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-norm.vcxproj" (預設目標) (4) ->
1>         (ClCompile 目標) ->
1>D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\loader.c(2005): warning C4819: The file contains a character that cannot be represented in the current code page (950). Save the file in Unicode format to prevent data loss [D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-norm.vcxproj]
1>
1>
1>         "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\ALL_BUILD.vcxproj" (build 目標) (1) ->
1>         "D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-norm.vcxproj" (預設目標) (4) ->
1>         (ClCompile 目標) ->
1>D:\test_rpcs3\rpcs3\Vulkan\Vulkan-LoaderAndValidationLayers\loader\loader.c(2005): error C2220: warning treated as error - no 'object' file generated [D:\test_rpcs3\rpcs3\Vulkan\Vulkan-build\loader\loader-norm.vcxproj]
1>
1>      1 個警告
1>      1 個錯誤
1>
1>  經過時間 00:00:11.80
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(41,5): error MSB3073: The command "cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_CONFIGURATION_TYPES="Debug;Release" -DBUILD_TESTS=OFF -DBUILD_DEMOS=OFF -DBUILD_LAYERS=OFF -DBUILD_VKJSON=OFF ../Vulkan-LoaderAndValidationLayers
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(41,5): error MSB3073: msbuild.exe ALL_BUILD.vcxproj /t:build /p:Configuration=Release /m" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
