### ISSUE TITLE
Catherine missing letters from font (regression)

### ISSUE THREAD

**Issue by raulpetru** [RPCS3/rpcs3#2945]
Hey,
A few updates ago I didn't had this issue. There are missing letters in subtitles.
Here are a few screenshots:
![rpcs3_2017-07-03_20-08-07](https://user-images.githubusercontent.com/16340925/27802307-ad144d68-602b-11e7-8d10-c6123913f5fe.png)
![rpcs3_2017-07-03_20-08-11](https://user-images.githubusercontent.com/16340925/27802309-af03ba8c-602b-11e7-8ea2-e0785518c602.png)
![rpcs3_2017-07-03_20-08-13](https://user-images.githubusercontent.com/16340925/27802312-b0331952-602b-11e7-981a-7e58da3b5d1a.png)

And here's the log: 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1120193/RPCS3.zip)

**Comment by Megamouse** [comment]
![image](https://user-images.githubusercontent.com/23019877/27802670-88ef6644-6025-11e7-9633-ef16ee704c47.png)

seems like it affects more than catherine

**Comment by Zangetsu38** [comment]
and with strict render mode ? lbp karting have little same think

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/27802706-cd3fe3c8-6025-11e7-9b00-990bb95cc03d.png)
![image](https://user-images.githubusercontent.com/20027681/27802714-d4ca4624-6025-11e7-91cc-147785e0d8e0.png)
Same issue in GTA V.

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/27802773-265835d2-6026-11e7-90be-2b771131944d.png)
With Strict Rendering Mode.

**Comment by Zangetsu38** [comment]
same think ?

**Comment by MarioSonic2987** [comment]
@Zangetsu38 Probably yes.

**Comment by raulpetru** [comment]
@Zangetsu38 Oh.. font in Catherine works/looks as intended with strict rendering mode enabled.

**Comment by Megamouse** [comment]
it starts definitely with kd-11 rsx fixes for minecraft menu

**Comment by Zangetsu38** [comment]
ok same bug lbp and AOT

**Comment by Megamouse** [comment]
okay I found the builds that broke stuff for minecraft:
first time the bug appears was on build #2861 
![image](https://user-images.githubusercontent.com/23019877/27803161-65fce654-6028-11e7-8678-19bac1c453d0.png)

after that, the bug changes in build #2918 to showing previously missing text in autosave screen but instead showing the menu bug:
![image](https://user-images.githubusercontent.com/23019877/27803282-050b3e80-6029-11e7-8538-29e0aa99ef03.png)

**Comment by Zangetsu38** [comment]
same pr for regression AOT, AOT only bood with strict mode now and run with only 20 fps, before 30

**Comment by kd-11** [comment]
I have intentionally moved alot of undefined behaviour behind the strict mode option - this is not a mistake. These games are using tricks that are out of spec such as reading from a target framebuffer which needs workarounds. In future we might have advanced settings to separate API strictness per "stage" but this will remain as is until then.
