### ISSUE TITLE
Scott Pilgrim black screen

### ISSUE THREAD

**Issue by Skeletonsnax** [RPCS3/rpcs3#2948]
So I followed the guide, got the PKG and all that and I only get a black screen, Oni Press logo, orange screen and a lot of nonsense. My graphics card on my laptop (W7) is a GeForce 630M which according to the site supports up to OpenGL 4.5. Along with that I when I took the whole folder as is and ran it on a W10 computer it runs like nothing so I'm left befuddled as hell.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
