### ISSUE TITLE
FFX HD Speed Regression

### ISSUE THREAD

**Issue by twdarkeh** [RPCS3/rpcs3#2956]
https://github.com/RPCS3/rpcs3/commit/d793f8ad788108db5aa621ced5b700faf531839e

Caused FFX HD to run at unplayable speeds up to the menu. Once you get in game, it's fine.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1125629/RPCS3.zip)

**Comment by Nekotekina** [comment]
I can't reproduce

**Comment by twdarkeh** [comment]
Game version is NPUB31247. Not sure of any useful way to show what's going on, since I have no idea what's going on.

**Comment by kacek** [comment]
Same version, mo regression for me on latest master.

**Comment by twdarkeh** [comment]
No one else seems to have the issue, so will assume it's just my setup and close the issue.
