### ISSUE TITLE
rpcs3 error causes deletion of files that are not used (or even in it's directory) by rpcs3

### ISSUE THREAD

**Issue by Sora3100** [RPCS3/rpcs3#2963]
OS: Windows 10 Creator's Update x64 1703 build
CPU: Intel Core i7 2600k
GPU: GTX 770 2GB
RAM: 8GB DDR3

Error in question when it happens: 
![image](https://user-images.githubusercontent.com/18172557/27935889-29e14d58-62ae-11e7-9d7c-fc726cbb41e2.png)

This error has deleted my entire pcsx2 folder (causing me to lose my save twice), rpcs3 data and flash folders (maybe a few others) and my Distance folder. (it obviously also crashed the emulator)

The game this occurs with is Tales of Zestiria (BLES02152)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1129474/RPCS3.zip)

**Comment by makotech222** [comment]
I can attest to this happening as well. I lost a huge amount of data on same drive that my rpcs3 folder is on.  All of the data that was deleted was in same folder that my rpcs3 folder is located. I don't have logs to prove this however, but seems to match up with other storied I'm hearing.

**Comment by AniLeo** [comment]
This was supposedly fixed a while back, but no one managed to reproduce this so far again. Is this still an issue? (Use some sandboxed/controlled environment to prevent important file losses)

**Comment by Sora3100** [comment]
It seems you can no longer close the "Installing game data" part anymore, which if I remember correctly is what caused this.
