### ISSUE TITLE
LLVM: [0x00aca110] Error: MFFS

### ISSUE THREAD

**Issue by fengsco000** [RPCS3/rpcs3#2964]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1129904/RPCS3.zip)
Getting an error when compiling LLVM PPU on an Intel Skylake Core i7 6770HQ
Attached is the RPCS3.txt

System:
Intel Core i7 6770HQ
16GB RAM
256GB SSD
GTX 950 2GB

RPCS3:
PPU LLVM
SPU Interpreter (fast)
Vulkan
1280x720

Unrelated question, recently watched the newest version on youtube with fixed blues and bloom, is that live in the repo? The latest one for download precompiled still has a lot of bloom errors.

Thanks for your help!

**Comment by AniLeo** [comment]
It's supposed to happen, it's an unimplemented function. Won't affect gameplay

**Comment by fengsco000** [comment]
Ah, yes its very stable was just wondering since I didn't see any documentation for it. Thanks I'll be sure to search around more next time haha
