### ISSUE TITLE
[BLUS31436] NHL 15

### ISSUE THREAD

**Issue by Kravickas** [RPCS3/rpcs3#2966]
### - S LDR: Boot Game: boot done.
- U {PPU[0x1000000] Thread (main_thread) [0x0212b088]} sysPrxForUser TODO: _sys_process_atexitspawn()
- U {PPU[0x1000000] Thread (main_thread) [0x0212b090]} sysPrxForUser TODO: _sys_process_at_Exitspawn
- U {PPU[0x1000000] Thread (main_thread) [0x0212adb8]} sys_prx TODO: _sys_prx_get_module_list(flags=2, pInfo=*0xd00302a8)
- E {PPU[0x1000000] Thread (main_thread) [0x00cb8ab0]} sys_vm: sys_vm_memory_map(vsize=0x2000000, psize=0x100000, cid=0xffffffff, flags=0x200, policy=0x1, addr=*0xd002dae0)
- E {PPU[0x1000000] Thread (main_thread) [0x0183347c]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0x40f, alignment=0x10000000, alloc_addr=*0x21ea6c4)
- E {PPU[0x1000000] Thread (main_thread) [0x0183347c]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0x40f, alignment=0x10000000, alloc_addr=*0x21ea36c)
- U {PPU[0x1000000] Thread (main_thread) [0x00c9af18]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
- U {PPU[0x1000000] Thread (main_thread) [0x00c9afa8]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
- U {PPU[0x1000000] Thread (main_thread) [0x00c9af18]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
- U {PPU[0x1000000] Thread (main_thread) [0x00c9afa8]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
- U {PPU[0x1000000] Thread (main_thread) [0x00c9af18]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
- U {PPU[0x1000000] Thread (main_thread) [0x00c9afa8]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
- U {PPU[0x1000000] Thread (main_thread) [0x00c9af18]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
- U {PPU[0x1000000] Thread (main_thread) [0x00c9afa8]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
- U {PPU[0x1000000] Thread (main_thread) [0x00c9af18]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
- U {PPU[0x1000000] Thread (main_thread) [0x00c9afa8]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x2
- E {PPU[0x1000006] Thread (NHL Render Thread) [0x02129130]} 'cellVideoOutConfigure' failed with 0x8002b221 : CELL_VIDEO_OUT_ERROR_ILLEGAL_CONFIGURATION
- F {PPU[0x1000006] Thread (NHL Render Thread) [0x01576524]} MEM: Access violation reading location 0x18

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
