### ISSUE TITLE
Vulkan : in-game rendering issue in Gundam Musou 3

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2967]
Vulkan 

![vk](https://user-images.githubusercontent.com/3000282/27982769-85702fa0-63de-11e7-9856-3c5934cfa810.jpg)

GL
![gl](https://user-images.githubusercontent.com/3000282/27982770-9250d6fc-63de-11e7-956e-c4fa6f2a3775.jpg)

**Comment by Zangetsu38** [comment]
Little same AOT/GTA4 for vulkan

**Comment by RainKikyou** [comment]
This new improvement applies to all the musou engine series, and vk has not yet merged with this improvement. In addition to gundam musou 3 graphics are now almost perfect, the other musou game graphics still have problems
![unknown](https://user-images.githubusercontent.com/20301499/27983932-d1d610e0-63fb-11e7-9430-764d0bc941b6.png)
![unknown 1](https://user-images.githubusercontent.com/20301499/27983938-eb8790ea-63fb-11e7-8af4-66ece8d508e9.png)
sengoku musou 4
https://youtu.be/JFd-8gBEOig

**Comment by kd-11** [comment]
Does GL render correctly without GPu texture scaling?

**Comment by raven02** [comment]
Yes , it still renders correctly without GPU texture scaling .

**Comment by raven02** [comment]
fixed in latest master

![untitled](https://user-images.githubusercontent.com/3000282/28495619-379d6dac-6f86-11e7-9bea-775ec4894d3b.png)
