### ISSUE TITLE
no compatible gpu devices found

### ISSUE THREAD

**Issue by trigrex** [RPCS3/rpcs3#2968]
got this error and i have windows 10 with nvidia 820m
F RSX: No compatible GPU devices found
S LDR: Boot from gamelist per doubleclick: done
U {PPU[0x1000000] Thread (main_thread) [0x016971c4]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x01243088]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x01243090]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x1000000] Thread (main_thread) [0x01242dc8]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x01242dc8]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
U {PPU[0x1000000] Thread (main_thread) [0x016cfd80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x6
U {PPU[0x1000000] Thread (main_thread) [0x01242dc8]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x01242dc8]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
E {PPU[0x1000000] Thread (main_thread) [0x01241130]} 'cellVideoOutConfigure' failed with 0x8002b221 : CELL_VIDEO_OUT_ERROR_ILLEGAL_CONFIGURATION
F {rsx::thread} class std::runtime_error thrown: No vulkan device was created

**Comment by clienthax** [comment]
Your card does not support vulkan, try opengl.

**Comment by kd-11** [comment]
This card is a rebadged GT 540M (GF117/GF108) - Nvidia does not support vulkan on fermi
