### ISSUE TITLE
Game list mismatch when searching

### ISSUE THREAD

**Issue by clienthax** [RPCS3/rpcs3#2970]
If you search for a game it seems that the data for the resulting slots is not pulled correctly
it still seems to map to the full list

EG you can click one item and another will open

**Comment by Megamouse** [comment]
I noticed that in the past but i thought i fixed that in some commit. Maybe it's in one of my PRs? I'll take a look

**Comment by Megamouse** [comment]
hmm i tried in latest master... works as expected. maybe you run some older version or one based of an older?

Or how exactly do you reproduce the bug?

I tried with search, sort, category filters and so on

**Comment by Megamouse** [comment]
and gamegrid or list ?

**Comment by clienthax** [comment]
Aha, looks like i was a bit behind on updates, works as expected :)
