### ISSUE TITLE
Audio issue to crash

### ISSUE THREAD

**Issue by Granndal** [RPCS3/rpcs3#2972]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000050 at 000000000031ad54.
Instruction address: 000000000031ad54.
Function address: 000000000031ace0 (base+0x30ace0).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------
Hi guys, been playng Okami HD  and plays normally, but i keep getting this audio explosion resulting on this crash error...

**Comment by AniLeo** [comment]
Without log and/or stacktrace and/or steps to reproduce that error itself means nothing.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
