### ISSUE TITLE
Naruto Storm 2 Regression After Updating RPCS3

### ISSUE THREAD

**Issue by TCVinNYC** [RPCS3/rpcs3#2977]
When I launch the game its pretty smooth, but it gets laggy when you go into the fighting parts or play story. To fix it, I have to make a fresh install of the newer rpcs3 build, install the PS3 firmware then move my game + saved data. It works perfectly like for everyone else. If I update the exe file for rpcs3 and then launch it goes into regression state. (I've tried deleting config files (including game config) and data folder)

Windows 10 1703 15063.413
i7 6700k (not OC)
GTX 1070 (OC)

Using this newer build:
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-5142

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1134101/RPCS3.zip)
![image](https://user-images.githubusercontent.com/15741434/27997822-3ff70f70-64ce-11e7-8dfe-c5151b15fe3f.png)

**Comment by SaltyCucumber** [comment]
I think you are supposed to use the stable master release, that is 5135

**Comment by TCVinNYC** [comment]
ok I'll try it out

**Comment by AniLeo** [comment]
That's not a master build.

**Comment by TCVinNYC** [comment]
ok then
