### ISSUE TITLE
Project Diva F 2nd cannot run ingame.

### ISSUE THREAD

**Issue by Mindxz** [RPCS3/rpcs3#2983]
Here is my settings.

![19867038_1413096258779298_1839128335_o](https://user-images.githubusercontent.com/30069740/28059358-3982fa06-664e-11e7-91e5-d3203ffa6e1f.png)
![19885842_1413095802112677_1590185828_o](https://user-images.githubusercontent.com/30069740/28059362-3fde36d6-664e-11e7-8c6c-1a1ae3fb403f.png)

It's Ok on the menu screen. (A graphic issues was fixed.)
![19885959_1413097172112540_1329660021_o](https://user-images.githubusercontent.com/30069740/28059635-fcd460f8-664e-11e7-92c1-b638806837a8.png)

But when i select the song and going to play.
![19867056_1413097535445837_629219894_o](https://user-images.githubusercontent.com/30069740/28059732-5c143af2-664f-11e7-9f62-67b1981656e5.png)

It was stuck in a loading screen :( 
![19876145_1413098172112440_1800108626_o](https://user-images.githubusercontent.com/30069740/28059789-8a1ef3e2-664f-11e7-88ef-6e21ea3b71b2.png)

**Comment by AniLeo** [comment]
This is widely known, see forum thread and #2075
Please use the forums to report compatibility 

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.

**Comment by Mindxz** [comment]
Oh , I'm so sorry.
