### ISSUE TITLE
Regression: [NPUB30126] BattleFantasia - OpenGL

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#2987]
i7 4770k, archlinux, mesa stable, r9 fury.
Rev 5395 was working very nicely with battlefantasia (npub30126) on Opengl, with an almost constant 60fps.
On rev5423, I get a blackscreen until it plays a short video (see screenshot). Then it goes back to darkness. I can hear the sound but I can't see anything.
Vulkan works fine (but is much slower: about 35fps where opengl is 60fps).
My other 2d fighting games seem ok with Opengl.
I send the logfile.
[RPCS3-battlefantasia-darkscreen.zip](https://github.com/RPCS3/rpcs3/files/1141757/RPCS3-battlefantasia-darkscreen.zip)
![fps 60 01 opengl battlefantasia npub30126 _278](https://user-images.githubusercontent.com/7478580/28114816-bc2dc6d4-6702-11e7-9d54-18dceabdd060.jpg)
I don't know how to recompile a specific revision (only the latest), so it's difficult to tell you which rev broke my config.

**Comment by raveskirza** [comment]
Does it work with "Strict rendering Mode" enabled?

**Comment by toccata10** [comment]
No: blackscreen

**Comment by toccata10** [comment]
Tried on windows (and nvidia card) this morning: exact same behaviour, ie blackscreen with opengl.
So I downloaded previous versions to find the culprit. Here's the one:
![bug-01](https://user-images.githubusercontent.com/7478580/28153347-3215e4b0-67a5-11e7-85a6-ecc7b26e3a17.JPG)
PR2962. That'll probably be for @kd-11 when he's got some time.

**Comment by toccata10** [comment]
Further testing: Dragon's lair (npub30218) has the same behaviour: used to work fine with opengl, now only the sound is audible (with a black screen).
Same PR broke the OpenGl renderer. Same thing on windows+linux.
My logs with correct and incorrect renderings.
[RPCS3-NPUB30218-CorrectScreenOGL.zip](https://github.com/RPCS3/rpcs3/files/1155077/RPCS3-NPUB30218-CorrectScreenOGL.zip)
[RPCS3-NPUB30218-BlackScreenOGL.zip](https://github.com/RPCS3/rpcs3/files/1155078/RPCS3-NPUB30218-BlackScreenOGL.zip)

**Comment by kd-11** [comment]
does vulkan work?

**Comment by toccata10** [comment]
Yes, Vulkan works fine (slower than OpenGl with my config: 35fps against 60fps, but that's another pb): correct rendering.

**Comment by toccata10** [comment]
Not sure if it'll help, but I tried enabling the "write color buffers" on Battle fantasia. Here's the result: 4 displays flashing on my screen. If I pause, I can see 2 displays. On Dragon's lair: black screen with "write color buffers" (=no change). Gpu=OGL
[RPCS3-BattleFantasia-OGL-WriteColorBuffers-01.zip](https://github.com/RPCS3/rpcs3/files/1168417/RPCS3-BattleFantasia-OGL-WriteColorBuffers-01.zip)
![battlefantasia-ogl-writecolorbuffers-01](https://user-images.githubusercontent.com/7478580/28502985-36912eb2-6ffe-11e7-88c9-d36749cf4481.jpg)
![battlefantasia-ogl-writecolorbuffers-02](https://user-images.githubusercontent.com/7478580/28502986-3852111c-6ffe-11e7-9441-08ee80f1b8bb.jpg)

**Comment by toccata10** [comment]
A little update:
on rev2017-10-14, Dragon's lair is playable with OGL with a base resolution of 720p. The 1080p resolution crashes the emulator (the videos in the folder are 1080p). On Vulkan, it works fine (720p and 1080p). 
[RPCS3-DragonLair-1920pCrash.zip](https://github.com/RPCS3/rpcs3/files/1385234/RPCS3-DragonLair-1920pCrash.zip)
BattleFantasia continues giving a blackscreen in OGL, but works fine with Vulkan (and the vulkan speed improved a lot on recent revisions: I get a solid 60fps).
[RPCS3.log-BattleFantasia-OGL.gz](https://github.com/RPCS3/rpcs3/files/1385231/RPCS3.log-BattleFantasia-OGL.gz)
[RPCS3.log-BattleFantasia-Vulkan.gz](https://github.com/RPCS3/rpcs3/files/1385232/RPCS3.log-BattleFantasia-Vulkan.gz)

**Comment by AniLeo** [comment]
Is this still an issue?

**Comment by kd-11** [comment]
Please retest

**Comment by toccata10** [comment]
Unfortunately, still exactly the same: black screen excepted during the short video intro. I hear the sound and I see that's it's compiling shaders, but no output.
[RPCS3.log-BattleFantasia.gz](https://github.com/RPCS3/rpcs3/files/1653323/RPCS3.log-BattleFantasia.gz)

**Comment by kd-11** [comment]
Update needed.

**Comment by toccata10** [comment]
Rev7103, mesa 18.1.4:
With Ogl: still problematic: no display without strict mode+write color buffers. Buggy graphics then.
With Vulkan: ok with strict mode+write color buffer (works fine excepted contours of characters with are not good).

I captured the different configurations.
[captures-bf.zip](https://github.com/RPCS3/rpcs3/files/2195930/captures-bf.zip)
[capture-bf-VulkanInGame-PbsWithContours.rrc.zip](https://github.com/RPCS3/rpcs3/files/2195937/capture-bf-VulkanInGame-PbsWithContours.rrc.zip)

With Vulkan, with only write color buffer: the intro is fine, but it goes black screen before reaching the ingame menu (in join the rpcs3 log)
[RPCS3.log-BFWithoutStrictMode.zip](https://github.com/RPCS3/rpcs3/files/2195935/RPCS3.log-BFWithoutStrictMode.zip)

**Comment by Emulator-Team-2** [comment]
@kd-11 
This game simply stopped working at 1280x720 resolution.

**[720x480]**
![bez tytulu1](https://user-images.githubusercontent.com/38318848/47221733-7d540600-d3b5-11e8-928f-0dffe724fdca.png)

**[1280x720]**
![bez tytulu2](https://user-images.githubusercontent.com/38318848/47222179-5d711200-d3b6-11e8-8ad0-2ef8b1345317.png)

**Comment by toccata10** [comment]
rev8143, mesa19.0: problem solved.
