### ISSUE TITLE
Demon's Souls [BLES00932] - crash when trying to execute RSX debugger

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#2998]
No matter what settings were using...

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1144950/RPCS3.zip)

**Comment by isshininu** [comment]
![_2017_07_15_09_50_34_261](https://user-images.githubusercontent.com/6324523/28236879-0ec3d856-6943-11e7-8b93-f94356d76102.png)

**Comment by Megamouse** [comment]
Doesn't game have to be stopped?
(I always wondered that)

**Comment by isshininu** [comment]
Well, i just tried to stop the game first
But crash still happens, so...

**Comment by AniLeo** [comment]
Can't reproduce. Try again with latest build and clean setup

**Comment by isshininu** [comment]
Reproduced on clean 0.0.3 install.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1164478/RPCS3.zip)
![_2017_07_21_08_58_06_293](https://user-images.githubusercontent.com/6324523/28449671-e7cce602-6df2-11e7-9ce1-6de5ede21579.png)

**Comment by Megamouse** [comment]
crashes here as well

**Comment by Megamouse** [comment]
does not crash in Visual Studio though

**Comment by AniLeo** [comment]
Ok, I managed to reproduce (outside of debug environment). Let me see if I can get it on VS, it's probably being shoved away by one of those ignored exceptions.

**Comment by isshininu** [comment]
I cannot find RSX Debugger in menu.
Where it is?  :/

**Comment by isshininu** [comment]
Debugger no more crashes on thread pause.
Closing?
