### ISSUE TITLE
Failed to initialize trophies

### ISSUE THREAD

**Issue by emmauss** [RPCS3/rpcs3#3011]
this happen to recent builds. anytime i try running Disgaea 4 and D2. it gives me an error
`Failed to initialize trophies. Please end the game'. On builds before rpcs3-v0.0.2-2017-07-04-9bc959fe,
the error occurs if you select load liblv2.sprx only, instead of automatic, and on quite old builds,it does not occur. but now it fails no matter which setting you use.
Games:
Disgaea 4 - BLUS30727
Disgaea D2 - BLES01939

Screens
![rpcs3](https://user-images.githubusercontent.com/5307160/28229133-154e5984-68d1-11e7-9972-0d8692cb89e4.PNG)

tested using rpcs3-v0.0.2-2017-07-14-504fa5ff_win64

**Comment by Zangetsu38** [comment]
works for me in all game
![image](https://user-images.githubusercontent.com/5261759/28230128-fa6fd7ae-68e5-11e7-9ea2-54064f7c0d61.png)

**Comment by emmauss** [comment]
creating a new rpcs3 folder and running on a clean setup works. i will move my saves to the new folder and use that. thanks for showing me that is supposed to work.
