### ISSUE TITLE
Dragon's crown sometimes won't boot.

### ISSUE THREAD

**Issue by JacobAL** [RPCS3/rpcs3#3013]
Just hangs at black screen on trying to load trophy data.
Only happens in recompiler (LLVM/ASMJIT) and will happen most times I try to boot the game. Sometimes it will just boot and work fine though.

[Specs](http://i.imgur.com/TknGYGe.png)
[Settings](http://i.imgur.com/QY1JR3B.png)

Not a problem on interpreter.

Log:
*redacted console output*

**Comment by AniLeo** [comment]
Please upload a full log.

**Comment by JacobAL** [comment]
[Here's the log](https://www.dropbox.com/s/r8imfvl5hgvjrjx/RPCS3.log?dl=0)

**Comment by JacobAL** [comment]
Doesn't seem to matter, crashes on starting a level anyway.

**Comment by JacobAL** [comment]
On further experimentation, it seems that LLVM causes the main issue with loading the game, whereas Interpreter PPU+ASMJIT will still work.

**Comment by zminhquanz** [comment]
This game have a freeze during boot when you using PPU LLVM

**Comment by JacobAL** [comment]
LLVM still an issue but the recompiled audio now works really well.

**Comment by RipleyTom** [comment]
I investigated and it's not a LLVM issue.
It's a sync issue caused by bad coding in the original game, only occurs with llvm because of the speed at which ppu runs with it.
I may release a patch for it at some point.

**Comment by RipleyTom** [comment]
Patch to add to Patch.yml:
PPU-60f7a7f5e0de894da8e5de235609228c40e70197: #DC BLUS30767 Sync Fix
  - [be32, 0x5BCA18, 0x63C30000]
  - [be32, 0x5BCA1C, 0x4BFFF829]
  - [be32, 0x5BCA20, 0x38600045]
  - [be32, 0x5BCA24, 0x4832BA7D]
  - [be32, 0x5BCA28, 0xE8410028]
  - [be32, 0x5BCA2C, 0x80BE01D8]
  - [be32, 0x5BCA30, 0x38800000]
  - [be32, 0x5BCA34, 0x90A30000]

If you need for another version, contact me on discord.

**Comment by RipleyTom** [comment]
After discussing it with jarves and kd-11 we discovered a forgotten sleep(1ms) in the rsx thread.
#3158 should fix the issue with processors with a sufficient amount of cores.
The race condition is still there however and for processors with few cores this may still be an issue and the patch still needed.

**Comment by YaPeL** [comment]
How many cores are we talking about? X > 2?

**Comment by JacobAL** [comment]
Saw the video on the youtube channel today. I'll try the newest build when i have some time. Thanks for the fix!

**Comment by davoodinator** [comment]
can you make a patch for the NPUB31235 version as well please

**Comment by RipleyTom** [comment]
Added fix for NPUB31235, not tested but it should work.

**Comment by RipleyTom** [comment]
Added fix for BCAS20298 version

**Comment by SamuelBeckingham-Cook** [comment]
Still happening for me, hangs on the loading screen.  [Here's a link to the log](https://pastebin.com/UXci2ijS)

I have it set to Recompile GPU+SPU and Vulkan - Using the BLUS30767 version.

If I swap the GPU to Interpreter - I get slightly different behaviour. The "Now loading" message briefly fades, then this logs:
`E {PPU[0x1000011] Thread (FiberFunc) [0x004a15e8]} cellSaveData: cellSaveDataEnableOverlay(enable=1)`
And then it returns.

With LLVM, this happens faster than the loading screen can appear.

**Comment by JacobAL** [comment]
U {PPU[0x1000000] Thread (main_thread) [0x00df9368]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00df9368]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
U {PPU[0x1000000] Thread (main_thread) [0x00df9368]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00df9368]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [3]
U {PPU[0x1000000] Thread (main_thread) [0x005b57a8]} cellNetCtl TODO: cellNetCtlGetInfo(code=0x2 (INFO_ETHER_ADDR), info=*0x28241858)
S {Audio Thread} XAudio 2.9 initialized
E {PPU[0x1000000] Thread (main_thread) [0x00de0090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_flash/data/font/SCE-PS3-SR-R-LATIN.ccd” [1]
E {PPU[0x1000000] Thread (main_thread) [0x00de0090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_flash/data/font/SCE-PS3-SR-R-JPN.ccd” [1]
E {PPU[0x1000000] Thread (main_thread) [0x00de0090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_flash/data/font/SCE-PS3-YG-R-KOR.ccd” [1]
E {PPU[0x1000000] Thread (main_thread) [0x00de0090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_flash/data/font/SCE-PS3-DH-R-CGB.ccd” [1]
E {PPU[0x1000010] Thread (FiberFunc) [0x005b7c18]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0xb34720, arg=*0x282418fc, options=0x1)
E {PPU[0x1000000] Thread (main_thread) [0x005b7e90]} 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x005b7e90]} 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x005b7e90]} 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000011] Thread (FiberFunc) [0x004a15e8]} cellSaveData: cellSaveDataEnableOverlay(enable=1)


Getting this issue where the game won't get past now loading any more. Not sure when this started but the last few versions I've tried are like this.

**Comment by AniLeo** [comment]
No real issue on your copy pasta

**Comment by JacobAL** [comment]
Not even all those things that say failed and the fact that it was all red? It didn't go past the first loading screen.

**Comment by AniLeo** [comment]
Maybe unimplemented cellNetCtlGetInfo, the rest is pretty normal. Most of the times the issue doesn't end up logged.

**Comment by JacobAL** [comment]
Loading liblvl2 only fixed it. Should troubleshoot before opening problems really.
