### ISSUE TITLE
Cannot open RPCS3 emulator latest build Windows 10 Pro x64 Redstone 2

### ISSUE THREAD

**Issue by WolfSpirit1999** [RPCS3/rpcs3#3014]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000018 at 0000000051315274.
Instruction address: 0000000051315274.
Function address: 0000000051315260 (base+0x145260).
Module name: 'Qt5Core.dll'.
Module base: 00000000511d0000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

**Comment by raven02** [comment]
Make sure you are using latest build and if may crash in some recent version . https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-5253

**Comment by SaltyCucumber** [comment]
@WolfSpirit1999 First, try removing old gui file in GuiConfigs, also remove config.yml and everything in data folder. This will probably fix your problem.
Second, don't do what @raven02 said, that's incorrect. You should be downloading lastes master build, not simply latest build, cause those may sometimes be unstable. To do that go here: https://rpcs3.net/compatibility?b you can find latest master at the top.

**Comment by WolfSpirit1999** [comment]
Thanks @SaltyCucumber it worked !

**Comment by chewest11** [comment]
I am having the same problem but don’t know anything I am doing. I am tryin to open it and try to follow the stupid but hard when you don’t know where what is

**Comment by RainbowCookie32** [comment]
This is a 3 years old issue, it's unlikely that's related to whatever problems you are having. Please move to our Discord server if you need help https://discord.me/RPCS3
