### ISSUE TITLE
tales of graces f background isssues 

### ISSUE THREAD

**Issue by asbel123** [RPCS3/rpcs3#3019]
its playable u cant see background i have to use opengl and its fullspeed framelimit 60 fps better than real ps3 why cant use vulkan keep crashing aduio is perfect and music and text too. 

i am using new version. i happy got newlaptop desktop cpu 6700k and 1080gtx and 3k 120hz display.

thank u rpsc3 team u the best keep working. i am not angry i am very happy ur works i love pc than ps4 i can take my laptop anywhere than tv.

**Comment by AniLeo** [comment]
Does not contain any logs or screenshots. Reopen when you follow the guidelines and add some.
