### ISSUE TITLE
Tales of graces F (BLUS30903), Tales of Xillia 1/2: Auto framelimit and Vblank problem.

### ISSUE THREAD

**Issue by Illynir** [RPCS3/rpcs3#3020]
Hello,

Auto framelimit doesn't works correctly. Normally it's 30 FPS in the overworld and 60 FPS in combat. The game is always at 60 FPS on auto, limit at 30 FPS divide the speed by two on the combat, too slow.

Vblank 30 + Framelimit 60 allows to get the real behavior of the game as it is on a real PS3.

**Comment by asbel123** [comment]
i got that same issues can u try tales of vesperia ur did with opengl strict  rendering mode see if fix the background.

**Comment by Illynir** [comment]
Yes, it fix the background, however rest many graphcis error (black character, etc..).

I think than "Strict rendering mode" fix background but it misplaces many light effect and shader as bloom, cell shading and some textures, result the graphics error.

Visible Black line on Tales of graces F are certainly the black lines around characters misplaced for example.

**Comment by GeniusMage** [comment]
With kd's latest PR, the cel-shading seems to be gone, instead of being out of place. There's also that same transparency issue as in Tales of Vesperia
![bandicam 2017-07-18 10-56-24-692](https://user-images.githubusercontent.com/27543170/28309034-5ff7ff38-6ba8-11e7-90c1-d2f6b5c2328f.png)

There's also a blur issue now
![bandicam 2017-07-17 17-56-58-726](https://user-images.githubusercontent.com/27543170/28309126-b0a2049c-6ba8-11e7-8185-fbd9aa7164b1.png)

**Comment by Illynir** [comment]
Yes, same here.

**Comment by kd-11** [comment]
Regression is fixed

**Comment by Illynir** [comment]
It's fixed, yes. Old issue are come back however. ^^

**Comment by Zangetsu38** [comment]
Crash instant in Vulkan, same issue eternal sonata and other, works in amd not in nvidia.
and in ogl yes fixed, same bugged before with strange wireframe

**Comment by asbel123** [comment]
get the save from gamefaqs now u dont need to do new game start over arts usage and use bruteforce savemanger do decryrtp. 

i am up to water cryns no issues the game there lots of slow down battle i am using opengl.

 have one annyoing issues save manger keep frezzing alot i have to wait 10 minutes to load up.

**Comment by asbel123** [comment]
dlc package works too

**Comment by Illynir** [comment]
Vulkan crash was resolved with the merge of "Vulkan fix". Still graphics bugs only now, the game is fullspeed on vulkan. Auto framelimit doesn't works correctly Normally it's 30 FPS in game and 60 FPS in combat. The game is always at 60 FPS on auto, limit at 30 FPS divide the speed by twoon combat, too slow.

Changing of title of issue.

**Comment by Llkur0** [comment]
Skit is also blurred. http://www.emunewz.net/forum/showthread.php?tid=187713&pid=280497

**Comment by Katanab** [comment]
So any news in the game ? it freezes in auto, but everything else works ok

In 30 fps lock battles are slow as hell but freezes after longer time ( 10 to 15 minutes)

F {SPU[0x2000002] Thread (SpursTLGraphicsCellSpursKernel2)} class std::runtime_error thrown: Halt
(in file Emu\Cell\SPUThread.cpp:1796)

this is the error i get when it freezes

**Comment by GeniusMage** [comment]
Ugh, forgot to update here.
Blur in skits is gone and black screen with existing shader cache is fixed (since Dec 1st).

**Comment by CafeStrix** [comment]
New to RPCS3 here,

Playing BLUS30903 too also experiencing constant freezing/crashing. Exact/identical symptoms @Katanab posted. Strict rendering is required for both OpenGL/Vulcan otherwise major graphical issues such as invisible characters or black screen. I've been playing with some of the options but still haven't found a way to prevent freeze/crashing every 5~20 minutes.

Auto/60FPS - Runs fast and smooth however it feels like game is on speed mode/hack mode (definitely not normal gameplay) Also, some cutscenes the voice/audio overlaps several times over each other. 

30FPS - Stable cutscenes with very slight lag/stuttering while running around field. However, battle frames are unacceptably super slow.

i7-8700K
GTX 1080Ti
16GB DDR4

I'm not sure what I did but my in game brightness is really dark right now. (There's not even a brightness setting in the game's menu)
![2018-01-26 2](https://user-images.githubusercontent.com/35820999/35438115-252f384c-024a-11e8-9a73-318284bd4a50.png)
Here are my settings:
![2018-01-26 3](https://user-images.githubusercontent.com/35820999/35438322-e760b4b8-024a-11e8-8953-2b371e3b71dc.png)
![2018-01-26 4](https://user-images.githubusercontent.com/35820999/35438324-e9d484a4-024a-11e8-924e-e8c86d603307.png)

**Comment by GeniusMage** [comment]
@CafeStrix There's no brightness problem here, the sky is cloudy, so it's supposed to be darker.
The framerate issue can be bypassed by using an external program to limit it to 30 when out of battle/skits, although most programs only work on OGL/DX.

**Comment by CafeStrix** [comment]
@GeniusMage Thank you! I thought I messed up something. It sounds a bit complicated to configure a 3rd party program to set custom frame limiters for the battle/skits @_@ I don't think I have the experience/skills to do that ( ._.)

**Comment by GeniusMage** [comment]
@CafeStrix Bandicam has a framelimiter which you can enable/disable with a key. AMD's driver has one too, though I don't remember if you can tie it to a key. Maybe Nvidia has one too ?
There's also one in MSI Afterburner.

**Comment by Illynir** [comment]
For the freezes on the other hand I tried everything and they will arrive randomly whatever happens. Sometimes after 5 minutes, sometimes after two hours. I've noticed that it tends to do less this way if you disable everything related to SPU like the SPU loop detection, and so on.

**Comment by CafeStrix** [comment]
@CafeStrix Oh I see, I thought it was automatic configuration. Nvidia Control Panel doesn't seem to have the option but I have Afterburner. However a manual toggle like that for every battle/skits sounds like a chore lol. That said, I guess the other way around is to toggle 30FPS exclusively during cutscenes. I could probably try to bind the toggle key on one of the unused DS4 buttons if any.

**Comment by Illynir** [comment]
Game is in 720p on PS3 then 1080p didn't works. Upscaling doesn't works also with the strict rendering. 

Personally i use one button on touchpad of my DS4 for the framelimiter of Bandicam. Put framelimit on 60 in RPCS3 et FPS limit on 30 in Bandicam and it's good.

And then it has the advantage of being able to explore faster at 60 FPS. :P

**Comment by CafeStrix** [comment]
@Illynir Oh lol and here I am playing this on a 4k monitor hoping to at least upscale it to 1080 lol.

Thanks, never used Bandicam before but I'll try binding the FPS toggle/key like that ^_^ It is indeed advantageous to be able to explore faster but I can't help but lol at sped up animations of npcs & mobs running around on the field. I just noticed some skits also go slightly out of sync even with Auto/60FPS but much much better than 30.

I just loved this game so much when I played it on the PS3 back then but I really wanted the JAP version with english subs + exclusive DLC costumes. While still not 100% playable, I'm very thankful to RPCS3 and the team of experts that are working on this. I wish only I was skilled/knowledgeable enough to be able to contribute in the development and make more games compatible.

**Comment by IceLancerSR** [comment]
rpcs3-v0.0.5-6544-f66d5adf_win64
Tested, auto fps still doesnt work on vulkan. Opengl cant reach full speed ,vulkan can.
If this could be fixed it would be eureka for the game

**Comment by wakka1** [comment]
Auto fps still doesn't work... very few graphical glitches and those jagged edges can be quite annoying.

**Comment by dio-gh** [comment]
Bumping this thread for upkeeping reasons. The original post needs adjustments to actually reflect the issue in the title. The problem still persists.

**Comment by Illynir** [comment]
The title and content have been modified to reflect the current state of the game.

**Comment by fshy00** [comment]
Has there been any progress on identifying the actual cause of why Auto isn't able to track when its supposed to change? I'd be interested in knowing why this issue seems unique (as far as I know) to Graces.

**Comment by Illynir** [comment]
The problem is not unique to Tales of Graces F but also to Tales of Xillia 1 and 2. They have the same engine in common. It doesn't do it on Tales of Vesperia because it was a different version of the engine used.

The problem can be fixed by setting the Vblank option to 30 Hz in the advanced tab.

I guess the game engine is using something unusual to handle its framelimit that RPCS3 doesn't handle for now.

The framelimit of RPCS3 is not complete anyway and would deserve a rewrite.

**Comment by IceLancerSR** [comment]
> 
> 
> The problem is not unique to Tales of Graces F but also to Tales of Xillia 1 and 2. They have the same engine in common. It doesn't do it on Tales of Vesperia because it was a different version of the engine used.
> 
> The problem can be fixed by setting the Vblank option to 30 Hz in the advanced tab.
> 
> I guess the game engine is using something unusual to handle its framelimit that RPCS3 doesn't handle for now.
> 
> The framelimit of RPCS3 is not complete anyway and would deserve a rewrite.

setting vblank to 30 made game horrible.. it feels soo sluggish and there seems to be some kind of input delay

**Comment by DJScias** [comment]
I wonder if #7723 did anything to change/improve the issue at hand.

**Comment by vsub** [comment]
Sadly no
If you set the fps limit to Auto,you will be locked to the vblank number  everywhere

According to info in that pull,this seems to be normal but in ToG case:
Auto + 30 = forces the game to run at 30fps everywhere
Auto + 60 = makes the game run at 60fps everywhere which makes those parts of the game that actually run at 30fps to run at double speed
60\59\off + 30 vblank makes the game run at proper speed in and outside of battle

The only other problem is the fmvs but vbank doesn't seem to be the case for that(the audio randomly disappear for half a second)

**Comment by elad335** [comment]
both settings are dynamically asjustable.

**Comment by tonygiang** [comment]
This issue is now among the [Top 10 oldest issues remaining open](https://github.com/RPCS3/rpcs3/issues?q=is%3Aissue+is%3Aopen+-label%3ALongterm+sort%3Acreated-asc) (if you discount Longterm issues which are functionally roadmaps) of the rpcs3 project.

**Comment by LittleWhole** [comment]
I can confirm this issue still happens. No limit = incredible speed hack mode, skits are extremely out of sync (audio plays normal speed, characters go superspeed);

60fps = skits normal, battles normal, cutscenes still have overlapping audio;

30fps = everything is normal speed, battles are incredibly slow.

I hope we can find a fix PR soon. Some of the more heavy cutscenes are completely ruined by overlapping audio :(

**Comment by tonygiang** [comment]
> 
> 
> The problem is not unique to Tales of Graces F but also to Tales of Xillia 1 and 2. They have the same engine in common. It doesn't do it on Tales of Vesperia because it was a different version of the engine used.
> 
> The problem can be fixed by setting the Vblank option to 30 Hz in the advanced tab.
> 
> I guess the game engine is using something unusual to handle its framelimit that RPCS3 doesn't handle for now.
> 
> The framelimit of RPCS3 is not complete anyway and would deserve a rewrite.

Okay, so I did not have Tales of Xillia 1 or 2 when this comment was written. But I bought Xillia 1 recently and just tested Xillia with build 0.0.10-10378. The result is... well, complicated.

So Xillia on the real hardware plays at 60fps when it's only displaying menu, and 30fps when outside of menu. Using the global configuration, it still has the same issue as Graces f. Everything runs at 60fps and gameplay moves twice as fast.

But with vblank=30Hz, Xillia correctly runs at variable framerate as the real hardware. I switched to Graces f to try out how it goes over there and disappointly, the framerate still stay locked at either 60fps or 30fps on both global and custom config, respectively. So from now, this auto framerate issue is kinda specific to Graces f(?) with a huge caveat that Xillia requires vblank=30Hz to run at variable framerate correctly, and I have not tested any other game on this engine (Xillia 2, Zestiria, Berseria) because I don't have them.

Has it always been this way with Xillia 1? I can't tell.

**Comment by vsub** [comment]
Did you tried settings the fps limit to anything other than auto(read my post above because this affect all tales 3 games)
60\59\off + 30 vblank makes the game run at proper speed in and outside of battle

**Comment by tonygiang** [comment]
> 
> 
> Did you tried settings the fps limit to anything other than auto(read my post above because this affect all tales 3 games)
> 60\59\off + 30 vblank makes the game run at proper speed in and outside of battle

I just tried this, still on build 0.0.10-10378. The result is: Framelimit at 60 of Off + vblank=30Hz produces no different result than Framelimit at Auto + vblank=30Hz. Xillia 1 runs correctly, Graces run at half speed. No data for anything released after Xillia 1.

**Comment by vsub** [comment]
Works fine here(60fps limit and 30Hz)
30 outside battles - proper speed
60 in battles - proper speed
60 in menu - proper speed
60 in skits - proper speed(the audio and mouths movements are correct)
30 in cut scenes - proper speed
60 in fmvs - proper speed

**Comment by tonygiang** [comment]
Okay, so this time my data might be a bit more correct. I tried out build 0.0.10-10383 to see if anything changed and... both games crash (Graces at SPU compilation and Xillia 1 at runtime, randomly). Recompiling everything didn't help either. Didn't bother to find out why everything broke in just a few commits, so I went back to build 0.0.10-10378, recompiled everything and this time got results similar to vsub for both games.

The difference before going to 0.0.10-10383 and back is that Framelimit at Auto + vblank=30Hz no longer let Xillia 1 runs at variable framerate, it's consistently 30fps with that setting. Dunno why. Auto framelimit is still an issue at the end of the day nonetheless.

Graces f seems to look somewhat jerky outside of battle compared to how it looks on my TV. Is it really running at 30fps outside of battle on the real hardware?

**Comment by vsub** [comment]
I used 0.0.10-10383 for the test above and I played the game for around half an hour
No problems here

**Comment by ccoffield93** [comment]
RPCS3 Version: 0.0.11-10664-c1a80b81 Alpha. Settings below. 
![image](https://user-images.githubusercontent.com/12446845/87835553-1649d680-c853-11ea-8271-f58c5175b68d.png)

![image](https://user-images.githubusercontent.com/12446845/87835576-295ca680-c853-11ea-9b11-8ec4853919ca.png)

I am getting 30FPS in the field as expected, but battles don't jump up to 60 as they should, meaning they run at half speed.

**Comment by kd-11** [comment]
Does this game still need the vblank set to 30?

**Comment by Illynir** [comment]
Yes.
