### ISSUE TITLE
Install Firmware does not respect Virtual File System folder redir

### ISSUE THREAD

**Issue by deadair3210** [RPCS3/rpcs3#3023]
1. Use Virtual Filesystem to point rpcs3 to a folder other than the default
2. Install the firmware
3. Try to launch a game, only for the emulator to not find the files due to them being placed in the dev_flash folder in the Emu Dir

**Comment by deadair3210** [comment]
This is of version rpcs3-v0.0.2-2017-07-17-93151d81_win64

**Comment by AniLeo** [comment]
It's extracting a dev_flash folder to main folder.

Offending line: https://github.com/RPCS3/rpcs3/blob/aed9b31294d34cfe1e95d29c1b79a3e6740850ed/rpcs3/rpcs3qt/main_window.cpp#L515
