### ISSUE TITLE
Conflict between GUI configurations

### ISSUE THREAD

**Issue by JarnoVgr** [RPCS3/rpcs3#3024]
Whenever launching a recent build RPCS3 crashes on startup.
Occurs on builds: v0.0.2-5271 (2017-07-16), rpcs3-spurs-scheduler3
Build that works fine: v0.0.2-5414-4b431543

`Fatal error
Unhandled Win32 exception 0xE06D7363.
Exception address: 00007ff8ecfa3c58.
ExceptionInformation[0x0]: 0000000019930520.
ExceptionInformation[0x1]: 00000000078fa160.
ExceptionInformation[0x2]: 00000000018c3dc0.
ExceptionInformation[0x3]: 0000000000010000.
Instruction address: 00007ff8ecfa3c58.
Function address: 00007ff8ecfa3bf0 (base+0x33bf0).
Module name: 'KERNELBASE.dll'.
Module base: 00007ff8ecf70000.
RPCS3 image base: 0000000000010000.
`

Platform: Windows 10 x64
Latest firmware

**Comment by JarnoVgr** [comment]
Turns out mounting the ISO/BluRay again removes the dialog, but still shows the same fatal error followed by a crash.

**Comment by SakataGintokiYT** [comment]
Delete Guiconfig folder

**Comment by JarnoVgr** [comment]
Unfortunately that doesn't fix this fatal error.

**Comment by SakataGintokiYT** [comment]
What firmware you have installed

**Comment by JarnoVgr** [comment]
The latest firmware. I highly doubt that the installed firmware matters for this issue, but I might be wrong.

**Comment by SakataGintokiYT** [comment]
4.81 ?

**Comment by JarnoVgr** [comment]
Yes

**Comment by SakataGintokiYT** [comment]
Did you try delete config.yml

**Comment by JarnoVgr** [comment]
Deleting config.yml and games.yml makes RPCS3 start fine yes. When restoring both files afterwards, it doesn't crash anymore either.

I'll keep the issue open as I don't think configs should crash the application.

Thanks for your help. :)

**Comment by Renusek** [comment]
I think you should always delete configs and data folder when updating the emulator.

**Comment by AniLeo** [comment]
Needs removing guiconfig/config related files, specially after the gui revamp. I think it's a wontfix

**Comment by isshininu** [comment]
It is necessary to renew settings after each major update.
Who will considered this as a bug?

**Comment by flash-fire** [comment]
If similar issues pop up, please save a copy to this issue so that I can fix the crash.  This crash is annoying in that it is almost impossible to replicate, but once it replicates, it'll always replicate.  So, it's really hard to find as a contributor. Thanks all!
