### ISSUE TITLE
lastest version can't play BLJS10256-[Dai-3-Ji Super Robot Taisen Z]

### ISSUE THREAD

**Issue by h188cm** [RPCS3/rpcs3#3029]
error log:

F {PPU[0x1000000] Thread (main_thread) [0x0040fdbc]} MEM: Access violation reading location 0x26b

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
