### ISSUE TITLE
Can't compile - __builtin_isinf_sign is not a member of std

### ISSUE THREAD

**Issue by latot** [RPCS3/rpcs3#3030]
Hi, i try compile rpcs3 but failed, i update the files today with the last changes, and i'm using gcc-5.4.

```
make
[  4%] Built target png16_static
[  4%] Generating something_that_never_exists
-- Found Git: /usr/bin/git (found version "2.13.2") 
-- GIT_VERSION: 5483-f91f2e3e
[  4%] Built target GitVersion
[  5%] Automatic MOC, UIC and RCC for target rpcs3
[  5%] Built target rpcs3_autogen
[  5%] Built target hidapi-hidraw
[  6%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Vulkan/glslang/glslang/MachineIndependent/intermOut.cpp.o
/home/pipe/Documentos/git/rpcs3/Vulkan/glslang/glslang/MachineIndependent/intermOut.cpp: In function ‘bool {anonymous}::is_positive_infinity(double)’:
/home/pipe/Documentos/git/rpcs3/Vulkan/glslang/glslang/MachineIndependent/intermOut.cpp:52:10: error: ‘__builtin_isinf_sign’ is not a member of ‘std’
   return std::isinf(x) && (x >= 0);
          ^
/home/pipe/Documentos/git/rpcs3/Vulkan/glslang/glslang/MachineIndependent/intermOut.cpp:52:10: note: suggested alternative:
<built-in>: note:   ‘__builtin_isinf_sign’
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/build.make:10828: rpcs3/CMakeFiles/rpcs3.dir/__/Vulkan/glslang/glslang/MachineIndependent/intermOut.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:236: rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I'm using Gentoo 64

Thx. Cya.

**Comment by hcorion** [comment]
Alright, do you know what stdc++ your using? I would guess it was quite old.

**Comment by latot** [comment]
Hi, the libstc++ lib belong to the gcc package, so what i can say is i'm using GCC-5.4, checking the docs of gcc, my libstdc++ should be between libstdc++.so.6.0.21 (GCC-5.1) and ibstdc++.so.6.0.22 (GCC-6.1)

But in any case, i don't have a previous version of libstdc++ installed.

Thx.

**Comment by latot** [comment]
Hi, searching, here a similar problem, and the fix works https://bugs.freedesktop.org/show_bug.cgi?id=95180

in Vulkan/glslang/glslang/MachineIndependent/intermOut.cpp:43

replace "math.h" with <cmath> and now pass this part.

Thx. Cya.

**Comment by hcorion** [comment]
Yes, see Vulkan/glslang, is actually a submodule, and that issue was fixed upstream in https://github.com/KhronosGroup/glslang/commit/880bf36cacee1cfce7d5d94991eb18c9e2d59d39#diff-4136f599d6d2445b854d236b7afc13a0

**Comment by hcorion** [comment]
Ahh, have you updated your submodules?
`git submodule update --init`

**Comment by latot** [comment]
mm, i update it, but for some reason don't was using the latest version, anyway, that is for other place, using the init command after update the submodules works, thx.
