### ISSUE TITLE
Vulkan: GPU Texture Scaling

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#3040]
Some games render smth olny with 
OGL and GPU Texture scaling
i wonder if smth like it could be implemented on Vulkan
here's the list of games:
AMY NPUB30613 blackscreen and sound
Bayonetta (not black screen but requires GPU Scaling to render some valueble things)
Condemned 2 blackscreen and sound
Resident Evil Revelatios blackscreen and sound
UFC 2009 Undisputed blackscreen and sound

**Comment by Xcedf** [comment]
AMY NPUB30613 also here

**Comment by AniLeo** [comment]
GPU Texture Scaling is on kd-11's TODO list.

**Comment by kd-11** [comment]
Closing via https://github.com/RPCS3/rpcs3/pull/3458
