### ISSUE TITLE
BCAS25005 PPU LLVM Error & Vulkan crash & DX12 crash

### ISSUE THREAD

**Issue by swordow** [RPCS3/rpcs3#3045]
Win10 x64
RPCS3 v0.0.2-8-6566722 Alpha
Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz | SSSE3 Supported | 12 Threads | 15.91 GB RAM
STRIX GTX 1060 6G lastest Driver 

BCAS25005

PPU LLVMError: 
S {SPU[0x2000005] Thread (SystemSpursCellSpursKernel0)} SPU: Function detected [0x09168-0x091fc] (size=0x94)
U {PPU[0x100000a] Thread (_gcm_intr_thread) [0x008c3248]} cellGcmSys TODO: cellGcmSetFlipImmediate(id=0x1)
F {PPU[0x1000007] Thread (GameInitializer) [0x00b99960]} MEM: Access violation reading location 0x0

1080p PPU Interpreter and Vulkan crash directly. log no error.

1080p PPU Interpreter and DX12 crash as following.

![popo 2017720201914](https://user-images.githubusercontent.com/7107003/28417002-feb755e2-6d88-11e7-887d-ef3a40524729.png)
![popo 2017720201522](https://user-images.githubusercontent.com/7107003/28417010-0207b6ce-6d89-11e7-921a-1ad9779d9e74.png)

720p  PPU Interpreter and DX12 hanging at this:
S {SPU[0x2000001] Thread (UserSpursCellSpursKernel1)} SPU: Function detected [0x11c78-0x11e7c] (size=0x204)
U {PPU[0x100000a] Thread (_gcm_intr_thread) [0x0140f048]} cellGcmSys TODO: cellGcmSetFlipImmediate(id=0x1)
U {PPU[0x100000a] Thread (_gcm_intr_thread) [0x0140f048]} cellGcmSys TODO: cellGcmSetFlipImmediate(id=0x0)
U {PPU[0x100000a] Thread (_gcm_intr_thread) [0x0140f048]} cellGcmSys TODO: cellGcmSetFlipImmediate(id=0x1)
U {PPU[0x100000a] Thread (_gcm_intr_thread) [0x0140f048]} cellGcmSys TODO: cellGcmSetFlipImmediate(id=0x0)
F {rsx::thread} class std::runtime_error thrown: HRESULT = D3D12 device was removed with error status 0x887A0001
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12RenderTargetSets.cpp:275)

only PPU Interpreter with OpenGL works fine....

**Comment by AniLeo** [comment]
D3D12 is not maintained, please don't report issues for it other than in the issue that's opened for it. Reporting for Vulkan/OpenGL is fine.
Please use the forums to report game compatibility though if it isn't a regression or you can't provide additional info as to why it's crashing.

**Comment by farshidbahmani** [comment]
You must install laset ps3 frimware

**Comment by AniLeo** [comment]
Not related, don't spam old issues
