### ISSUE TITLE
NPJB00435 Hatsune Miku: Project DIVA F 2nd - About play issue.

### ISSUE THREAD

**Issue by PREPERADE** [RPCS3/rpcs3#3048]
Now i know why it don't load any game data.
because it can't install game data when it first boot. Orz.
When i first boot this game pop up mesagebox about installing game data.
But install process is failed and can't play game.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
