### ISSUE TITLE
[Time Crisis 4] Coloured squares all over screen during gameplay - NVIDIA

### ISSUE THREAD

**Issue by billywws** [RPCS3/rpcs3#3050]
CPU: i5-4460
GPU: GeForce GTX 780
RAM: 16GB

Lighting issue is now remedied with the "Write Color Buffers" option, but now there are coloured squares clustered all over the screen, usually on models. Turning "Write Color Buffers" off brings back the lighting problem, and doesn't fix the coloured squares.

![image](https://user-images.githubusercontent.com/29743068/28440090-c332725e-6d9c-11e7-8a3d-5d535104ecc1.png)

**Comment by AniLeo** [comment]
Is this not an issue on AMD drivers or you just don't have hardware to check?

**Comment by billywws** [comment]
I tested on Intel HD, and the coloured squares do not appear. I do not own an AMD card though.

**Comment by AniLeo** [comment]
Needs retesting

**Comment by AlphaDelta9** [comment]
Maybe just driver problem, i use latest driver with Vulkan work well. I use GTX 960M just need optimize the performance because average 30-40 fps only sometime 50fps, and at helicopter average 10-20 fps rarely 30fps

**Comment by billywws** [comment]
This problem has been fixed a short while ago. It was an emulation problem.
   On Saturday, 3 March 2018, 10:57:44 GMT, AlphaDelta9 <notifications@github.com> wrote:  
 
 
Maybe just driver problem, i use latest driver with Vulkan work well. I use GTX 960M just need optimize the performance because average 30-40 fps only sometime 50fps, and at helicopter average 10-20 fps rarely 30fps

**Comment by legend800** [comment]
This should be closed. Game looks perfect now with WCB.
