### ISSUE TITLE
Demon's Souls [BLES00932] says: Working buffer not big enough

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#3051]
F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough, buffer_length=268435456 allocated=267911168 requested=524288 guard=65536 largest_pool=1048576
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:74)

This error was thrown right before the usual LLVM freeze today (release 0.0.3)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1164488/RPCS3.zip)

**Comment by HollowSoldier** [comment]
F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough, buffer_length=268435456 allocated=268214784 requested=259516 guard=65536 largest_pool=1043200
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:74)

Consistently getting this in Devil May Cry 4 BLES00186, at the beginning of Mission 6. Jump down the whole and proceed through the door. In the next area, the error is thrown.

Attaching log and save data at mission 6.
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/1205406/RPCS3.log.zip)
[BLES001860_0.ZIP](https://github.com/RPCS3/rpcs3/files/1205409/BLES001860_0.ZIP)

**Comment by kd-11** [comment]
Its fixed in vertex-rewrite but it will be a while before that is merged

**Comment by HollowSoldier** [comment]
Can confirm, using a build from that branch allowed me to proceed.

**Comment by SakataGintokiYT** [comment]
@AniLeo 
Fixed by #3200
