### ISSUE TITLE
Pkg installer does not handle multipart files.

### ISSUE THREAD

**Issue by clienthax** [RPCS3/rpcs3#3064]
Seems some files are split up as follows

XXXXX_00.pkg
XXXXX_01.pkg
XXXXX_02.pkg

00 contains the header, and other parts are just appended to the end of this. (This seems to be split up for psn downloads)

Currently trying to install 00.pkg will result in a wrong size error

**Comment by OverlordCW** [comment]
I have the same problem with Diablo III Ultimate Evil Edition [NPEB02026]

**Comment by Zangetsu38** [comment]
normal, no rpcs3 you needed reasemble part, with copy /b etc look google this

**Comment by clienthax** [comment]
@Zangetsu38 still a difference in the emulator that the standard ps3 can handle
While that is a workaround I think it wouldn't be too much of an issue to add support

**Comment by Zangetsu38** [comment]
yes, but ps3 have limit 4 go for that file is splitted, pc no have this problem

**Comment by clienthax** [comment]
@Zangetsu38 pc has the problem because it doesn't handle the files without a workaround ;)

**Comment by clienthax** [comment]
@OverlordCW can you test? https://github.com/RPCS3/rpcs3/pull/3128

**Comment by OverlordCW** [comment]
After I combined the pkgs with the copy /b command I removed the part files, so no unfortunately.

**Comment by AniLeo** [comment]
Solved by #3128 + #3381
