### ISSUE TITLE
Don't Load File (Error not found !)

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#3065]
FARCRY CLASSIC [NPEB00989]

> ·E 0:00:01.236421 {PPU[0x1000000] Thread (main_thread) [0x004f7e6c]} sys_spu: sys_spu_image_open() error: “/dev_hdd0/game/NPEB00989/USRDIR/Bin32/BinkPS3SPU.spu.self” not found!
·E 0:00:01.236434 {PPU[0x1000000] Thread (main_thread) [0x004f7e6c]} 'sys_spu_image_open' failed with 0x80010006 : CELL_ENOENT

![0](https://user-images.githubusercontent.com/25039098/28491265-638704e2-6f03-11e7-920b-9c94e92e71ca.jpg)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1167354/RPCS3.zip)

**Comment by aakh1361** [comment]
FARCRY CLASSIC [NPEB00989]

> E {PPU[0x1000000] Thread (main_thread) [0x004f7e6c]} sys_spu: sys_spu_image_open() error: “/dev_hdd0/game/NPEB00989/USRDIR/Bin32/BinkPS3SPU.spu.self” not found!
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1240207/RPCS3.zip)

**Comment by SakataGintokiYT** [comment]
@AniLeo 
Fixed by #3324

**Comment by AniLeo** [comment]
That PR doesn't seem to touch **sys_spu_image_open**. Have you tested?

**Comment by SakataGintokiYT** [comment]
Fixed by #3366
![bez tytulu](https://user-images.githubusercontent.com/13681488/29988481-d8e36a5c-8f6d-11e7-936f-08be2d101737.png)

**Comment by aakh1361** [comment]
it fixed
