### ISSUE TITLE
I get this error when ever i start a game.

### ISSUE THREAD

**Issue by Melahan** [RPCS3/rpcs3#3069]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000000 at 00000000004163bb.
Instruction address: 00000000004163bb.
Function address: 0000000000416250 (base+0x406250).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
