### ISSUE TITLE
Demon's Souls [BLES00932] - exception in Nvidia's nvoglv64.dll

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#3073]
Game throws an error and crash in a moment.

![_2017_07_23_18_38_58_421](https://user-images.githubusercontent.com/6324523/28500293-b9152640-6fd6-11e7-9323-0184042181e0.png)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1168147/RPCS3.zip)

{Game log is a *.7z renamed archive}

**Comment by AniLeo** [comment]
How to reproduce? Still an issue?

**Comment by kd-11** [comment]
Nvidia problems were recently fixed. Reopen if you can reproduce on current master.
