### ISSUE TITLE
Demon's Souls [BLES00932] says: Unknown comparison function 0x37c in file \RSX\gcm_enums.cpp:112

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#3074]
26217 ·F 0:03:17.401514 {rsx::thread} class std::runtime_error thrown: Unknown comparison function 0x37c
26218 (in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:112)
26219 0:04:17.088324 Stopping emulator...

This log is bigger because there was two sessions at the same time, sorry <:3

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1168151/RPCS3.zip)

**Comment by AniLeo** [comment]
How to reproduce?

**Comment by isshininu** [comment]
It a random error, it happens sometimes before game stops.

**Comment by kd-11** [comment]
This is a generic cell synchronization bug. Can happen in any game at any time and I'm guessing this particular bug doesnt happen anymore. Have you experienced this with newer builds?

**Comment by isshininu** [comment]
> Have you experienced this with newer builds?

No, since... since July, i guess?
