### ISSUE TITLE
RPCS3 instance runs in background after closing.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#3080]
I've noticed that after closing the emulator my memory not freeing. What's this?
Task manager show me rpcs3.exe consuming ~1GB of memory, running in the background.

**Comment by Zangetsu38** [comment]
i have same bug few time, need force close

**Comment by kd-11** [comment]
Happens when the emulator locks up. If you run a game and the emulator freezes - fps not updating - you have to force close. The only thing we can do is try to keep the lockups from happening in the first place.

**Comment by sirdanielk** [comment]
I also experience this. It not always happen. I have win10 is that relevant? The worst thing is that backgroung process affect new instances in a wrong way

**Comment by isshininu** [comment]
Last weeks this issue not happen at all.
I guess, this is no more a case?

**Comment by scribam** [comment]
@isshininu Is it still an issue?

**Comment by AniLeo** [comment]
This is still an issue, there's a few ways to reproduce zombie rpcs3, I'll try to enumerate some, but trying to start up rpcs3 with patch.yaml containing broken yaml syntax is one of them

**Comment by isshininu** [comment]
Zpmbie RPCS3 can be reproduced by starting https://github.com/RPCS3/rpcs3/issues/4143 in Vulkan mode

**Comment by johnnyt83** [comment]
unfortunately it is still an issue today.

**Comment by ruthan** [comment]
From time to time its still happening in 2019/09

**Comment by isshininu** [comment]
Is this still a bug?

**Comment by jeremybris** [comment]
I do not experience this... on 02/29/2020, even when the emulator freezes.

**Comment by AniLeo** [comment]
Need further testing on Windows, this doesn't happen to me on Linux

**Comment by jeremybris** [comment]
> Need further testing on Windows, this doesn't happen to me on Linux

I do not experience this with the latest Windows 10 update. 

I remember this problem a while ago, but since then I have gotten a new computer. I'm not sure if that made a difference.

**Comment by Darthagnon** [comment]
I had this happen to me (03/2020, Win10 v1709, Nvidia v442.59, rpcs3-v0.0.9-9899-f3877d11_win64). Closed RPCS3 after running Motorstorm for a while, testing different settings on Vulkan. One of the settings froze the game, and then it left two processes running in Task Manager, which I could not kill. They even prevented my computer from restarting, so I had to force-restart.

**Comment by Darthagnon** [comment]
Bug still present on latest version - I forgot to reset the bad setting(s) and it crashed while I tried Motorstorm again. Left a 1.9GB process in the background after crashing.

**Comment by Limyx826** [comment]
This had happen to me today when I noticed that my PC fans running in half speed but it supposed to idle. 

Build: RPCS3 v0.0.13-11412-235db57f Alpha

**Comment by 13xforever** [comment]
regressed in build 14000 (#9437)

**Comment by Limyx826** [comment]
RPCS3 had been closed properly in build RPCS3 v0.0.13-11420-c8947eee Alpha 
No more background task after closing main window.

**Comment by MSuih** [comment]
I think all the issues here have been resolved by now.

**Comment by deatherit** [comment]
2025 still happening
