### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Cmonaco88** [RPCS3/rpcs3#3084]
when i boot a game it starts and runs good then after a few minutes it stops and this error pops up

F {PPU[0x1000014] Thread (EMU 28669528) [0x000ded70]} class std::runtime_error thrown: Verification failed: 
(in file C:\rpcs3\rpcs3\Loader\PSF.cpp:118)

please can anyone tell me what the problem is here

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.

**Comment by Cmonaco88** [comment]
oh i i didnt know that thanks for information
