### ISSUE TITLE
Demon's Souls [BLES00932] Soldier shield not being drawn

### ISSUE THREAD

**Issue by YaPeL** [RPCS3/rpcs3#3088]
yeah, lamest of bugs, but something was off on the game, if you select the class "soldier" you cannot see your shield, pretty sure it doesn't happen on the real hardware, picture from yt as I cannot record my ps3 now:

ps3
<a href="http://es.tinypic.com?ref=2u89chl" target="_blank"><img src="http://i68.tinypic.com/2u89chl.png" border="0" alt="Image and video hosting by TinyPic"></a>

rpcs3
<a href="http://es.tinypic.com?ref=msou8m" target="_blank"><img src="http://i64.tinypic.com/msou8m.png" border="0" alt="Image and video hosting by TinyPic"></a>

happens on master, and on kd-11 pr, both vulkan and ogl.

**Comment by HollowSoldier** [comment]
Can confirm, the soldier starting shield is invisible in every RPCS3 version released so far, it isn't a regression. Happens regardless to settings/renderer being used.

**Comment by ymgve** [comment]
Confirmed here too. Renderer used doesn't matter.

**Comment by chdongsh** [comment]
Confirmed here too. expect it could be fixed soon

**Comment by Karlos007** [comment]
Still invisible, at least in Vulkan the lens flare bug is fixed.

![fps_ 29 94 _ vulkan _ 0 0 4-6448 _ demon s souls blus30443 21_02_2018 17_42_07](https://user-images.githubusercontent.com/23475289/36493018-d885e8ca-172e-11e8-9217-c1a08e3c7c08.png)

**Comment by isshininu** [comment]
This is game bug.

**Comment by YaPeL** [comment]
doesn't happen on the real deal, so yeah, rpcs3 isn't accurate enough, not a game bug

**Comment by Zangetsu38** [comment]
why you speak game bug ? not have rapport, is is bug rpcs3

**Comment by isshininu** [comment]
i dunno, lol

**Comment by isshininu** [comment]
I think I found one more missing texture case.
In Tower of Latria 3-2 after we get access to "heart" (or what was that) room:

on real PS3

![1](https://user-images.githubusercontent.com/6324523/36631023-41d0277a-198a-11e8-935b-b42a6c68ed07.png)

EMULATOR looks like dat

![2](https://user-images.githubusercontent.com/6324523/36631029-4fa1a126-198a-11e8-9985-500d5db9ddc7.png)
![3](https://user-images.githubusercontent.com/6324523/36631030-4fc29b1a-198a-11e8-96a1-9df035240ac1.png)
![4](https://user-images.githubusercontent.com/6324523/36631031-4fe2cc6e-198a-11e8-8512-e604d702060d.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1754394/RPCS3.log.gz)

**Comment by YaPeL** [comment]
reopened as this bugs its not related to #4302

**Comment by kd-11** [comment]
Its tracked in https://github.com/RPCS3/rpcs3/issues/4302.

**Comment by griever-gf** [comment]
Invisible shield bug is still presents in November, 2020.
