### ISSUE TITLE
Settings window doesn't fit into display (Linux version)

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3092]
@Megamouse I'm using notebook with 1366x768 px display, and lower part (60 px) is taskbar.
When I open menu - Configuration - System, it's OK:
![1](https://user-images.githubusercontent.com/14265316/28590239-22183da8-718a-11e7-8bd5-0c386197d11d.png)
But after switching to CPU, lower part with "Save" and "OK" buttons is hidden behind taskbar:
![2](https://user-images.githubusercontent.com/14265316/28590244-270d3c46-718a-11e7-832c-c85952aa6403.png)
Here how it looks after switching the taskbar off.
![3](https://user-images.githubusercontent.com/14265316/28590251-2df7fbd6-718a-11e7-9440-911f12160087.png)
I see the empty space on this tab
![4](https://user-images.githubusercontent.com/14265316/28590256-321e37ac-718a-11e7-97de-a256476566ef.png)
Can it be removed like here?
![5](https://user-images.githubusercontent.com/14265316/28590258-358c6d5a-718a-11e7-81ba-e540443bb62d.png)
Maybe, it should be better on my display.
Lubuntu 16.0.4, RPCS3 v0.0.3-ff772dd-7380_linux64.AppImage [2017-07-25]

**Comment by Megamouse** [comment]
Ah now I see.

This is new, did not happen before
I'll look into it

**Comment by Megamouse** [comment]
please try with #3093

**Comment by TotalCaesar659** [comment]
Yeah, could you make an AppImage with it? Or I have to wait for merging it?

**Comment by Megamouse** [comment]
Sadly You have to wait...

I made the size consistent so now it doesn't resize on switching to cpu tab anymore.
Furthermore I removed the empty space you showed me to reduce the total height like you proposed.

**Comment by TotalCaesar659** [comment]
OK, then I'll test it after merging.

**Comment by Megamouse** [comment]
Just wait a bit. It was merged right now, should be ready soon

**Comment by hcorion** [comment]
Try this one @TotalCaesar659 it should fix your problems:  https://rpcs3.net/cdn/builds/rpcs3-v0.0.3-2017-07-25-37c26b7-7385_linux64.AppImage

**Comment by TotalCaesar659** [comment]
Yeah, this bug is gone, but more empty spaces have appeared, above and under search bar.
![1](https://user-images.githubusercontent.com/14265316/28596942-009d428a-71a4-11e7-8a91-755847089330.png)

**Comment by Megamouse** [comment]
try with firmware installed
should be normal then

**Comment by TotalCaesar659** [comment]
Nah, same result.
![2](https://user-images.githubusercontent.com/14265316/28597217-59e02c62-71a5-11e7-88cd-a3bf3c93754e.png)

**Comment by Megamouse** [comment]
well. then it's just crappy LINUX

**Comment by TotalCaesar659** [comment]
Well, the important bug was fixed, so it can be closed, I guess. And this empties are not so uncomortable for every-day using.

**Comment by Megamouse** [comment]
Yeah.. it seems to be related to the used Qt Style anyway. Some people have similar occurances with custom stylesheets.

**Comment by Megamouse** [comment]
I have an idea. maybe it fixes this minor thing as well

**Comment by Megamouse** [comment]
Look out for the merge of #3091 . That should fix the empty space you have. If not, just tell me.

@AniLeo Can be closed

**Comment by TotalCaesar659** [comment]
Yeah, it's OK now, thanks.
![1](https://user-images.githubusercontent.com/14265316/28630116-0da5d288-7232-11e7-90ee-1cbfac580214.png)
