### ISSUE TITLE
AMD LLVM issue on openSUSE Tumbleweed.

### ISSUE THREAD

**Issue by kah0922** [RPCS3/rpcs3#3094]
Whenever I run rpcs3 (using [xenonpk's package](https://build.opensuse.org/package/show/home:xenonpk/RPCS3)), the following error happens:
`CommandLine Error: Option 'amdgpu-dump-rtmd' registered more than once!`
`LLVM ERROR: inconsistency in registered CommandLine options`

For reference, I am using an RX 460 with the latest MESA.

**Comment by Megamouse** [comment]
try newest AppImage

**Comment by AniLeo** [comment]
What if you use the AppImage on rpcs3.net/download?

**Comment by kah0922** [comment]
`Inconsistency detected by ld.so: dl-open.c: 677: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!`

**Comment by kd-11** [comment]
You need mesa with the same llvm version as rpcs3; llvm4. Afaik susedoes not ship mesa sith llvm4 so unless you build mesa from source, lets just say it's difficult to work around

**Comment by hcorion** [comment]
It should actually work on mesa with llvm 3. Can you run
`strace ./rpcs3-v0.0.3-2017-07-25-ff772dd-7380_linux64.AppImage`
and upload the output to pastebin or something?

**Comment by hcorion** [comment]
Also, @XenonPK could you please remove
`-DCMAKE_EXE_LINKER_FLAGS="-image-base=0x10000 $(llvm-config --libs mcjit vectorize ipo x86codegen x86disassembler)"`

from your build script? image-base has been upstreamed, and llvm linking is static

**Comment by hcorion** [comment]
Oh, I see XenoxPK is tracking releases, so llvm static won't work yet.

**Comment by kah0922** [comment]
Currently away from my personal PC, but[ I brached XenonPK's RPCS3 package a while ago](https://build.opensuse.org/package/show/home:kah0922/RPCS3), so I (think I) implemented your changes.

**Comment by hcorion** [comment]
Hmm, yes, that package you branched should work.

**Comment by kah0922** [comment]
Package failed with following error:
`/usr/lib64/../lib64/libLLVMCore.so.4: error adding symbols: DSO missing from command line`

**Comment by hcorion** [comment]
We do link against `-lpthread` though

**Comment by hcorion** [comment]
Perhaps try cleaning cmake cache?

**Comment by kah0922** [comment]
Spoke too soon, and posted wrong information. After further research, it looks like there's an argument missing when clang tries to compile that.

Also, this uses the OBS, so I wouldn't have  a clue how to clean the cmake cache, or if it even needs cleaning.

**Comment by kah0922** [comment]
Also the new appimage threw the same error.
Here's the [paste.](https://pastebin.com/3M08Jd8Y)

**Comment by hcorion** [comment]
This this build https://transfer.sh/YlbVQ/dbe095b-144_linux64 @kah0922 
Just go `chmod a+x ./dbe095b-144_linux64`
and then just go
`./dbe095b-144_linux64`
to run it

**Comment by kah0922** [comment]
`libGL error: unable to load driver: radeonsi_dri.so`
`libGL error: driver pointer missing`
`libGL error: failed to load driver: radeonsi`
`Fatal error:` 
`Segfault reading location 0000000000000000 at 00007f77474d485e.`

This error reminds me of a common [Steam runtime error.](https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues)

**Comment by hcorion** [comment]
Hmm, okay run it with `LIBGL_DEBUG=verbose ./dbe095b-144_linux64`

**Comment by hcorion** [comment]
If it just has a bunch of libpng spam, nothing else, do `strace ./dbe095b-144_linux64` again

**Comment by kah0922** [comment]
[Here's the libgl debug output.](https://pastebin.com/EqcTqm49)
[And here's the strace.](https://pastebin.com/fPXMnCEP)

**Comment by hcorion** [comment]
Hmmm, from what I can see, this no longer seems to be an issue with RPCS3, it seems like now your mesa driver is malfunctioning.

**Comment by hcorion** [comment]
Can you try running a OpenGL game or something?

**Comment by hcorion** [comment]
I'd recommend re-installing mesa, or re-building mesa.

**Comment by kah0922** [comment]
Dolphin and PCSX2 both work perfectly fine.

**Comment by kah0922** [comment]
I'm also using KDE, which relies on OpenGL for desktop effects.
I'll do a forced reinstall of Mesa and see what happens though.

**Comment by MonokelPinguin** [comment]
@kah0922 You could also try to start your original binary (with the llvm command line errors) with preloaded graphics drivers i.e.:
`LD_PRELOAD=/usr/lib64/dri/radeonsi_dri.so  rpcs3`

**Comment by kah0922** [comment]
> `LD_PRELOAD=/usr/lib64/dri/radeonsi_dri.so  rpcs3`

Actually that just worked with my old package.
I'm also working on fixing my personal OBS package.

**Comment by hcorion** [comment]
Could you try this one @kah0922 https://transfer.sh/jyNdZ/2a28bb3-146_linux64

**Comment by kah0922** [comment]
Segfaults with same error as before.
Using `LD_PRELOAD=/usr/lib64/dri/radeonsi_dri.so` fixes the issue.

**Comment by hcorion** [comment]
Does that fix it on the build I got you to do the libgl_debug thing as well?

**Comment by kah0922** [comment]
Yes.

**Comment by XenonPK** [comment]
@hcorion thanks for the build suggestions. Just to clarify, while I use the latest tag for package versioning, the code is straight from master. OBS provides a way to automate versioning based on git metadata, and commit date.

**Comment by kah0922** [comment]
Using XenonPK's updated package with `LD_PRELOAD=/usr/lib64/dri/radeonsi_dri.so` works.
So is this an RPCS3 issue or a Mesa/AMDGPU issue?

**Comment by hcorion** [comment]
I feel like this should be either a Mesa/AMDGPU issue or a OpenSUSE issue. I'll PR the fix for  `ld.so: dl-open.c` on the AppImage, and then we'll close the issue.
