### ISSUE TITLE
Vulkan problem on Linux

### ISSUE THREAD

**Issue by stumts** [RPCS3/rpcs3#3095]
Hi guys, I realize a problem with some games with Vulkan on Linux and these problens didn'd happen when using openGL. I thought this was a known problem on Linux, but when I saw some pictures on progress report about appimages I realize that it's not a known problem, I think.
![p5-ogl](https://user-images.githubusercontent.com/30453661/28602464-a50d985c-7194-11e7-9b53-b6236cd56be9.png)

![p5-vk](https://user-images.githubusercontent.com/30453661/28602485-b89de714-7194-11e7-9561-8cea39af97f9.png)

![ds-ogl](https://user-images.githubusercontent.com/30453661/28602493-bebbb3a6-7194-11e7-889d-88172742ff2b.png)

![ds-vk](https://user-images.githubusercontent.com/30453661/28602497-c4a5e200-7194-11e7-8605-d8b40445e031.png)

![twdm-ogl](https://user-images.githubusercontent.com/30453661/28602501-c9a76b52-7194-11e7-81f8-96edf94231a1.png)

![twdm-vk](https://user-images.githubusercontent.com/30453661/28602507-d1416d5e-7194-11e7-982b-dbc69e7e531d.png)

I'm using Ubuntu Xenial. My GPU is a Nvidia 850m and I'm using proprietary drivers 384.59.

**Comment by hcorion** [comment]
Yeah, that is very strange, I've got a GTX 1070 with latest beta binary drivers, and don't experience those issues. Do you have Windows setup? If so, could you try in Windows?

**Comment by stumts** [comment]
It didn't happen on WIndows.

![captura de tela 2017-07-26 02 15 14](https://user-images.githubusercontent.com/30453661/28605689-6a1b4d6a-71a9-11e7-878c-70707ee3b49e.png)

![captura de tela 2017-07-26 02 13 16](https://user-images.githubusercontent.com/30453661/28605696-73af4084-71a9-11e7-8335-4fe536f9f0b2.png)

![captura de tela 2017-07-26 02 18 06](https://user-images.githubusercontent.com/30453661/28605698-77977112-71a9-11e7-8331-f4f61c222525.png)

**Comment by kd-11** [comment]
Something is up with your drivers @stumts. These games work fine for other users on linux.

**Comment by desbh** [comment]
This happens to me as well on a GTX 1060. Every single driver offered by official Ubuntu repositories and graphics-drivers PPA is affected. Haven't tried manual install or other distros yet.

Brightness setting in DeS does work, kind of, as it not only makes the UI brighter, but also makes 3D elements barely visible. It just looks as if brightness/contrast values were adjusted by a fixed negative value.

**Comment by flavionm** [comment]
I have the exact same issue, using Linux Mint 18.1 with a GTX970, using drivers 384.69. RPCS3 version is dfc970c.

**Comment by hcorion** [comment]
and Linux Mint is also Ubuntu-based :thinking:. I wonder if this has to do with Ubuntu's packaging, or if it's a bug in nvidia's driver. (funny that it works well on arch :P)

**Comment by Enverex** [comment]
Just build from GIT and tried Vulkan on a 1060 (on Linux) and Persona 5 looked fine.

**Comment by Vochatrak** [comment]
It seems I have the same problem.
Checked on - rpcs3-v0.0.3-2017-08-26-dfc970c-7845_linux64.AppImage
Rosa R9 Plasma
GTX 650 2Gb version driver 384.59 (Set manually from the official site Nvidia)
Q8200 @ 3Ghz
8 Gb DDR2 800Mhz
In Windows build works fine.

**Comment by mikakev1** [comment]
Hi, same issue using appimage:
Arch Linux (4.13) / Mesa (17.3 - RADV) / Core I5 Haswell / R9 270X

**Comment by flavionm** [comment]
[RPCS3.log1.gz](https://github.com/RPCS3/rpcs3/files/1285794/RPCS3.log1.gz) Here's the log with Vulkan running on Linux. Works fine on Windows.
Linux Mint 13.2 / AMD FX-8320 / Geforce GTX970 / Nvidia Driver 384.69 / RPCS3 Version 7c897d5 (Both AppImage and building from source)

**Comment by oangelo** [comment]
On Arch Linux I tried to compile from the source and had no improvements. Using vulkan in Dolphin emulator I had no issue... I am not sure this is a driver issue, becaus Dolphin plays nice with vulkan. Any other sugestions to try out?

**Comment by Illynir** [comment]
Same problem. Vulkan works perfectly everywhere except RPCS3...

![screenshot_2017-12-23_09-49-21](https://user-images.githubusercontent.com/22648460/34318738-7c0b391c-e7cf-11e7-8a1a-08cc6a4daded.png)

**Comment by Zangetsu38** [comment]
Same problem witrh GTX 1080 TI, very lot game is fgull broken on Vulkan, and same for ogl with few game
![nier vulkan linux](https://user-images.githubusercontent.com/5261759/34318796-a9758dca-e7d0-11e7-9097-472d452b3034.png)

**Comment by kd-11** [comment]
For some reason the color space / pixmap for the window is in the wrong colorspace, I suspect YCbCr instead of RGB/sRGB. Unfortunately I still havent fund a reliable way of replicating this, running the same GPU with same drivers and libraries as other users is giving inconsistent results where some are affected and some are not. Investigations are ongoing.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/3998
