### ISSUE TITLE
Xinput - Xbox 360 controller not recognized

### ISSUE THREAD

**Issue by Thedocz** [RPCS3/rpcs3#3099]
Rpcs3 wont recognize my xbox 360 controller even if i set xinput in the i/o settings.

**Comment by AniLeo** [comment]
This has no info whatsoever.. What game did you test the controller on? Do you have a log file?

**Comment by hcorion** [comment]
Wired Xbox 360 controller? Wireless? Which version of Windows? 10, 8, 8.1, 7? Does it work with other games?

**Comment by kd-11** [comment]
360 controllers work just fine. You'll know its detected by windows if pressing the home button brings up the windows game bar if you're using windows 10. I'm using a 360 controller myself.

**Comment by COOLGAMETUBE** [comment]
Can't get my Xbox One controller working without an wrapper.

**Comment by AniLeo** [comment]
Has to work with XInput. Make sure it's being recognized by windows, if so, just select XInput and play. Make sure you don't have custom config on the game overriding it.

**Comment by Thedocz** [comment]
Sorry for the delay, i solved the problem, i don't know why but after a clean windows installation(Not because of this problem :) ) the controller started working, thanks to everyone

**Comment by LeonErrante** [comment]
i have the same problem. . . 360 xbox controlers, w10,

**Comment by AniLeo** [comment]
No need to golden shovel, specially for a non-issue. The tracker isn't a place for support.
