### ISSUE TITLE
Rpcs3 strange regression

### ISSUE THREAD

**Issue by dona12345** [RPCS3/rpcs3#3100]
Hi there,i have a problem,before i can get dragon ball burst limit running at 20-25 fps with vulkan render with recompilers but now suddenly it is a lot slow Like 5-8 fps with all renders,my setup is a10-6800k with an gtx1050 ti

**Comment by AniLeo** [comment]
This has no useful information. Missing logs, missing build that initiated the regression. Reopen when you edit it to include more information.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
