### ISSUE TITLE
NieR Replicant [BLJM60223] Says: Assertion failed! Edit: [Fixed]

### ISSUE THREAD

**Issue by Sandvichero** [RPCS3/rpcs3#3101]
This error comes up and causes the emulator to crash.

F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is FFFFFFFDh
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKGSRender.cpp:1873)

[Log](http://www.mediafire.com/file/ltjn6m6bj5lugdt/Log.7z)

Running Using Windows 10 with a Intel(R) Core(TM) i7-3770K CPU

Game Config:
[config.txt](https://github.com/RPCS3/rpcs3/files/1178164/config.txt)

**Comment by islandbargames** [comment]
I just ran into the same issue, I'll let you know if I find anything

**Comment by Sandvichero** [comment]
This issue has been fixed
