### ISSUE TITLE
[Linux] Missing characters onscreen in Catherine

### ISSUE THREAD

**Issue by gourdcaptain** [RPCS3/rpcs3#3102]
In RPCS3 in both v0.0.3 and v.0.0.3-5563-7fa42cfaa, in certain cutscenes and gameplay in Catherine, parts of the onscreen text are missing. This is consistent between runs, and occurs in both OpenGL and Vulkan, and on both the Interpreter (Fast) and LLVM Recompiler CPU modes.  This does not occur on the title screen, but occurs in parts of the opening cutscenes and in dialogue during stages (I have not played further.)

System:
Arch Linux 64-bit on 4.11.9 Linux Kernel
Intel Core i7-6800k
AMD Radeon RX 460 GPU (4 GB) with Mesa 17.1.5 drivers.
LLVM 4.0.1 installed, used by the graphics drivers, and used for compiling the Git version. 

Attached:
RPCS3 Log: [Catherine RPCS3-5563 Linux - Missing Letters Log.txt](https://github.com/RPCS3/rpcs3/files/1178272/Catherine.RPCS3-5563.Linux.-.Missing.Letters.Log.txt)
Examples of Problem:
![catherine rpcs3-5563 linux - missing letters 0](https://user-images.githubusercontent.com/7662067/28647503-9e8e899a-7235-11e7-8bed-774ba33d2985.jpg)
![catherine rpcs3-5563 linux - missing letters 1](https://user-images.githubusercontent.com/7662067/28647512-b0f0f4ba-7235-11e7-8d6f-3240d4c2aacb.jpg)
![catherine rpcs3-5563 linux - missing letters 2](https://user-images.githubusercontent.com/7662067/28647515-b45b5c94-7235-11e7-81c6-bc89e6a17e36.jpg)

**Comment by AniLeo** [comment]
Not linux only issue nor an issue really, need to tick Strict Rendering Mode

**Comment by gourdcaptain** [comment]
Huh. While I remember seeing this checkmark in older builds, I cannot find it on the GPU options tab in either the AppImage on the website or the GIT build I compiled.

**Comment by AniLeo** [comment]
Oh right, it's temporarily hidden. Directly edit config.yml for now, but should be back really soon

**Comment by gourdcaptain** [comment]
With Strict Rendering mode enabled by manually editing the config file, RPCS3 immediately crashes on game launch with an error in the terminal it was launched from of: 
"Fatal error: 
Segfault reading location 000000000000001c at 00007fe5c56f4e93.
HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Aborted (core dumped)."
