### ISSUE TITLE
rpcs3 regression

### ISSUE THREAD

**Issue by dona12345** [RPCS3/rpcs3#3104]
Hi there,i have a problem,before i can get dragon ball burst limit running at 20-25 fps with vulkan render with recompilers but now suddenly it is a lot slow Like 5-8 fps with all renders,my setup is a10-6800k with an gtx1050 ti and i'am using rpcs3 0.0.3 with this log RPCS3 v0.0.3-11-cd5a6f1 Alpha AMD A10-6800K APU with Radeon(tm) HD Graphics | 4 Threads | 7.94 GiB RAM | AVX S LDR: Boot from gamelist per Boot: done S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+010200-7A0666C40E2F1A24-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+0501F8-4EC9FBCF7E311537-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+08F558-CB6067D8E3FDCFB9-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+0CF3B8-482BDD5F3F3F55D8-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+10F2C8-8AD16C0E47B2C9FE-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+14D574-8017D6D7C12FB564-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+18D044-83EDE74D3A979A47-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+1CADC0-442F6191042CEEEF-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+20ACAC-0D4082B42E3B54CC-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+24A9E8-E1D947307B1E2D43-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+28B8F8-A011CB1D9F050BBB-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+2CC778-FC5A57DDA5A2591E-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+30E3F8-E3F9DE7FA615BDED-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+34EF28-45841A0E3174AC53-bdver2.obj S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2-libsysmodule.sprx-09F72D494851FEC4-bdver2.obj U {PPU[0x1000000] Thread (main_thread) [0x0220fd8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK S {PPU[0x1000000] Thread (main_thread) [0x0220c0c4]} PPU: LLVM: Loaded module v2-libsre.sprx-7BD57B68D8CA8EBC-bdver2.obj S {PPU[0x1000000] Thread (main_thread) [0x0220c0c4]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx U {PPU[0x1000000] Thread (main_thread) [0x00347c98]} sysPrxForUser TODO: _sys_process_atexitspawn() S {PPU[0x1000000] Thread (main_thread) [0x0220c0c4]} PPU: LLVM: Loaded module v2-libfs.sprx-BB8655E4C5C49381-bdver2.obj S {PPU[0x1000000] Thread (main_thread) [0x0220c0c4]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx S {PPU[0x1000000] Thread (main_thread) [0x0220c0c4]} PPU: LLVM: Loaded module v2-librtc.sprx-9CB190F178FA7E82-bdver2.obj S {PPU[0x1000000] Thread (main_thread) [0x0220c0c4]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx U {PPU[0x1000000] Thread (main_thread) [0x0225ed80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5 U {PPU[0x1000000] Thread (main_thread) [0x02264e58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) E {PPU[0x1000000] Thread (main_thread) [0x02264e58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE E {PPU[0x1000000] Thread (main_thread) [0x0020a704]} cellGcmSys: cellGcmSetTile: bad compression mode! (7) x2 S {SPU[0x2000000] Thread (CellSpursKernel0)} SPU: SPU Database initialized... S {SPU[0x2000001] Thread (CellSpursKernel1)} SPU: SPU Recompiler (ASMJIT) created... E {PPU[0x1000007] Thread (DBBLExpes) [0x00162550]} cellGame: cellHddGameCheck(version=0, dirName=“NPUB90106”, errDialog=1, funcStat=*0x46bc98, container=2) U {PPU[0x1000000] Thread (main_thread) [0x002ea68c]} sys_spu TODO: Unimplemented SPU Thread options (0x2) U {PPU[0x1000000] Thread (main_thread) [0x0225ed80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x2 U {PPU[0x1000000] Thread (main_thread) [0x02264e58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) E {PPU[0x1000000] Thread (main_thread) [0x02264e58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE S {PPU[0x1000000] Thread (main_thread) [0x0220c0c4]} PPU: LLVM: Loaded module v2-libl10n.sprx-CF794CD12F0202AD-bdver2.obj S {PPU[0x1000000] Thread (main_thread) [0x0220c0c4]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx U {PPU[0x1000000] Thread (main_thread) [0x001f6e84]} cellNetCtl TODO: cellNetCtlAddHandler(handler=*0x46dcd0, arg=*0x0, hid=*0x202e8d8) U {PPU[0x1000000] Thread (main_thread) [0x00347c98]} sceNp TODO: sceNpManagerRegisterCallback(callback=*0x46df18, arg=*0x0) U {PPU[0x1000000] Thread (main_thread) [0x001f9ad8]} sceNp TODO: sceNpBasicRegisterContextSensitiveHandler E {PPU[0x100001b] Thread (NpMatching_udpp2p) [0x00206cd0]} libnet: Unknown/illegal socket error: 0 (in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_net.cpp:207) E {PPU[0x100001b] Thread (NpMatching_udpp2p) [0x00206cd0]} libnet: setsockopt(): error 1652554232 U {PPU[0x100001b] Thread (NpMatching_udpp2p) [0x00206e0c]} libnet TODO: sys_net_free_thread_context(tid=0, flags=1) E {PPU[0x1000000] Thread (main_thread) [0x0020a704]} cellGcmSys: cellGcmSetTile: bad compression mode! (7) x2 E {PPU[0x1000000] Thread (main_thread) [0x0020a704]} cellGcmSys: cellGcmSetTile: bad compression mode! (10) U {PPU[0x1000000] Thread (main_thread) [0x002374f0]} cellGcmSys TODO: cellGcmSetZcull(index=0, offset=0xc10000, width=1280, height=768, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x201, sRef=0x80, sMask=0xff) E {PPU[0x1000000] Thread (main_thread) [0x0020a704]} cellGcmSys: cellGcmSetTile: bad compression mode! (7) x2 E {PPU[0x1000000] Thread (main_thread) [0x0020a704]} cellGcmSys: cellGcmSetTile: bad compression mode! (10) U {PPU[0x1000000] Thread (main_thread) [0x002338a8]} cellGcmSys TODO: cellGcmSetZcull(index=1, offset=0x1750000, width=1024, height=1024, cullStart=0x0, zFormat=0x2, aaFormat=0x0, zCullDir=0x0, zCullFormat=0x1, sFunc=0x201, sRef=0x80, sMask=0xff) E {PPU[0x1000000] Thread (main_thread) [0x0020a704]} cellGcmSys: cellGcmSetTile: bad compression mode! (7) x6

**Comment by SakataGintokiYT** [comment]
**[Download latest build from]:** https://rpcs3.net/download

**Step .1**
![2](https://user-images.githubusercontent.com/13681488/28659324-5dd3230a-72af-11e7-9825-ce99fb247505.png)
**Step.2**
![1](https://user-images.githubusercontent.com/13681488/28659332-62a981ee-72af-11e7-80f6-b2df8303277c.png)

**Comment by dona12345** [comment]
I get a little speed boost Like 2-4 fps but it still very slow in comparison of the first time i played it :(

**Comment by dona12345** [comment]
I get a little speed boost Like 2-4 fps but it is still very slow in comparison of the first time i played it :(

**Comment by kd-11** [comment]
Do not post the log text in the report - it makes it difficult to read. Paste into a file and attach instead
