### ISSUE TITLE
LLE-GCM Regressions

### ISSUE THREAD

**Issue by jarveson** [RPCS3/rpcs3#3105]
This issue will be for tracking regressions between lle-gcm and hle implementations, brought from PR #3096 . Best reports are games that currently work (or display 'better') with HLE, but have issues with lle.

So far I believe they are all spu post processing calls that are clipping poorly from inaccuracies in current spu instructions,  resulting in missing models and other scenery issues. Another common factor looks to be that most use the unreal engine

-Saw 2
-Lollipop chainsaw
-Supersonic Acrobatic Rocket-powered Battle-cars (doesn't run in HLE but still relevant)
-SH Downpour
-Bulletstorm
-Spec Ops The Line
-Asura's wrath

**Comment by kd-11** [comment]
I saw someone comment that hle seems to have inherited the problem as well? Or did they mess up confuguring it?

**Comment by jarveson** [comment]
Ill ask him on the PR, im thinking (hoping) its a misconfigure or mistype, because if its not, that throws a wrench into this

**Comment by JackONeill12** [comment]
Sonic Unleashed goes through a few loading screens and intros if no GCM Module is selected. Once it gets stuck its shows a lot of GCM Errors. If libGCM is selected it throws MEM violation right in the beginning and crashes. On your PR I got a MEM Crash no matter if libGCM is selected or not.

Log: https://drive.google.com/file/d/0Bzv00_6oh0fhSDJqeHFWaV9ZWUU/view?usp=sharing

**Comment by jarveson** [comment]
closing this, was way off initially and fixed the issue from zcull reporting
