### ISSUE TITLE
Battlefield 4 [NPUB31148]: RSX: Depth texture bound to pipeline with unexpected format 0x84

### ISSUE THREAD

**Issue by JusicP** [RPCS3/rpcs3#3106]
![bf44444](https://user-images.githubusercontent.com/25232950/28670510-b3cf5f62-72e1-11e7-952e-fec41fc6c8d4.png)
Log: https://drive.google.com/file/d/0B1vbIhPd5D_uRVhtUEVnamt0RUE/view?usp=sharing
Render: Vulkan
RPCS3 v0.0.3-13-e677751 Alpha
I tried use OpenGL, but textures not changed

**Comment by sirdanielk** [comment]
Same error with Digger HD demo [NPEB90231] smaller game, maybe easier to debug?

**Comment by kd-11** [comment]
I fixed these a few days ago, but its not yet merged.

**Comment by SakataGintokiYT** [comment]
@AniLeo 
Fixed by #3200
