### ISSUE TITLE
GL/Vulkan: Castle of Illusion Starring Mickey Mouse  [NPEB01427]

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#3107]
**[GL]**
![bez tytulu](https://user-images.githubusercontent.com/13681488/28671354-ac430ac8-72dc-11e7-940f-a3ef1f5f4ca5.png)

**[VK]**
![g](https://user-images.githubusercontent.com/13681488/28671587-8f1f2ff2-72dd-11e7-920b-525aa8f09b15.png)

**[Shaderlog:](https://mega.nz/#!dQpWAJhS!Ta5x_shiPbjGZ7_PPGq16tih8KAN8pY9fUgisduuXoU)**
**[Render-Doc:](https://mega.nz/#!xNYm0CAQ!sSyKQ0OSxiGuXWGPeU1zjK2UejdJ7TEv_C1amfNRO7A)**
**[Log:](https://gist.github.com/SakataGintokiYT/9915d6889bf4ab2aca7d67c923b655d1)**

**Comment by SakataGintokiYT** [comment]
https://media.giphy.com/media/fmimVT7UdSsWA/giphy.gif

**Comment by scribam** [comment]
@SakataGintokiYT Still an issue?

**Comment by scribam** [comment]
Tested with OpenGL on b3efa75206c6bc4230af3031e0d0453bfd98765c, still an issue.

**Comment by SakataGintokiYT** [comment]
Fixed by #4356
