### ISSUE TITLE
LLVM Errors after starting every game

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3109]
When LLVM is compiling modiles before starting every game, I always see these two errors:

> E PPU: LLVM: [0x00e00724] Error: MTFSF
> E PPU: LLVM: [0x00e008a4] Error: MFFS

![1](https://user-images.githubusercontent.com/14265316/28673199-a12efcb0-72ea-11e7-8c73-c92ce23c6063.png)

Is it a bug or not?

**Comment by AniLeo** [comment]
Not an error
