### ISSUE TITLE
Regression: Dengeki Bunko [BLJM61210] - OpenGL

### ISSUE THREAD

**Issue by spring568** [RPCS3/rpcs3#3111]
The game still runs (sound / input works) however the entire display output is black. In vulkan and direct 3d 12 the game is playable. I didn't see anything in the console that stood out as an error either

Windows 10 64bit
Nvidia gtx 960
latest drivers
RPCS3 ver. 0.0.3-11-b8776b8
![dbfc1](https://user-images.githubusercontent.com/27930237/28682441-cde42a3e-72b1-11e7-9a8e-be3cf3c71166.jpg)
![dbfc2](https://user-images.githubusercontent.com/27930237/28682447-d4e3bc6e-72b1-11e7-853f-40e54d65fb9b.jpg)

Edit: changed my mind about the log since I could have missed something https://pastebin.com/S4ckTa7f

**Comment by spring568** [comment]
I have no idea if I'm using apitrace correctly but it was printing this

1677815: message: major api error 1281: GL_INVALID_VALUE error generated. The y values exceeds the boundaries of the corresponding image object.
1677815 @0 glCopyImageSubData(srcName = 18, srcTarget = GL_TEXTURE_2D, srcLevel = 0, srcX = 0, srcY = 0, srcZ = 0, dstName = 107, dstTarget = GL_TEXTURE_2D, dstLevel = 0, dstX = 0, dstY = 9216, dstZ = 0, srcWidth = 32, srcHeight = 1024,
srcDepth = 1)
1677815: warning: glGetError(glCopyImageSubData) = GL_INVALID_VALUE
1677839: message: major api error 1281: GL_INVALID_VALUE error generated. The y values exceeds the boundaries of the corresponding image object.
1677839 @0 glCopyImageSubData(srcName = 18, srcTarget = GL_TEXTURE_2D, srcLevel = 0, srcX = 0, srcY = 0, srcZ = 0, dstName = 107, dstTarget = GL_TEXTURE_2D, dstLevel = 0, dstX = 0, dstY = 10240, dstZ = 0, srcWidth = 32, srcHeight = 1024,
 srcDepth = 1)
1677839: warning: glGetError(glCopyImageSubData) = GL_INVALID_VALUE
1677863: message: major api error 1281: GL_INVALID_VALUE error generated. The y values exceeds the boundaries of the corresponding image object.
1677863 @0 glCopyImageSubData(srcName = 18, srcTarget = GL_TEXTURE_2D, srcLevel = 0, srcX = 0, srcY = 0, srcZ = 0, dstName = 107, dstTarget = GL_TEXTURE_2D, dstLevel = 0, dstX = 0, dstY = 11264, dstZ = 0, srcWidth = 32, srcHeight = 1024,
 srcDepth = 1)
1677863: warning: glGetError(glCopyImageSubData) = GL_INVALID_VALUE
1677887: message: major api error 1281: too many identical messages; ignoring
1677887 @0 glCopyImageSubData(srcName = 18, srcTarget = GL_TEXTURE_2D, srcLevel = 0, srcX = 0, srcY = 0, srcZ = 0, dstName = 107, dstTarget = GL_TEXTURE_2D, dstLevel = 0, dstX = 0, dstY = 12288, dstZ = 0, srcWidth = 32, srcHeight = 1024,
 srcDepth = 1)
1677887: warning: glGetError(glCopyImageSubData) = GL_INVALID_VALUE: too many identical messages; ignoring
4422495: message: major api error 1286: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Framebuffer bindings are not framebuffer complete.
4422495 @0 glBlitFramebuffer(srcX0 = 0, srcY0 = 0, srcX1 = 512, srcY1 = 512, dstX0 = 0, dstY0 = 0, dstX1 = 512, dstY1 = 512, mask = GL_COLOR_BUFFER_BIT, filter = GL_NEAREST)
4422495: warning: glGetError(glBlitFramebuffer) = GL_INVALID_FRAMEBUFFER_OPERATION
5472076: message: major api error 1282: GL_INVALID_OPERATION error generated. The source and destination internal formats are not compatible.
5472076 @0 glCopyImageSubData(srcName = 18, srcTarget = GL_TEXTURE_2D, srcLevel = 0, srcX = 0, srcY = 0, srcZ = 0, dstName = 144, dstTarget = GL_TEXTURE_2D, dstLevel = 0, dstX = 64, dstY = 40, dstZ = 0, srcWidth = 80, srcHeight = 448, sr
cDepth = 1)
5472076: warning: glGetError(glCopyImageSubData) = GL_INVALID_OPERATION
5928701: message: major api error 1282: GL_INVALID_OPERATION error generated. The source and destination internal formats are not compatible.
5928701 @0 glCopyImageSubData(srcName = 17, srcTarget = GL_TEXTURE_2D, srcLevel = 0, srcX = 0, srcY = 0, srcZ = 0, dstName = 301, dstTarget = GL_TEXTURE_2D, dstLevel = 0, dstX = 0, dstY = 264, dstZ = 0, srcWidth = 128, srcHeight = 128, s
rcDepth = 1)
5928701: warning: glGetError(glCopyImageSubData) = GL_INVALID_OPERATION
8017428 @3 glDeleteTextures(n = 1, textures = &20)

**Comment by kd-11** [comment]
Yea you used it correctly, thanks. Region clipping doesn't seem to work properly.

**Comment by spring568** [comment]
Ah that's good to know. Also disabling it didn't work so it looks like I'll have to mess around more. I'll get back to you if I find anything else interesting

**Comment by AniLeo** [comment]
Is this still an issue on #3458 ?
Test with GPU options on/off to make sure it doesn't or does work regardless of settings

**Comment by spring568** [comment]
Well opengl works so my original bug is fixed. It doesn't give the same rendering results with gpu texture scaling enabled though. With gpu texture scaling on some sprites will distort and be discolored. It's like its decoding some of the textures incorrectly

**Comment by spring568** [comment]
I'm going to close this for now since it's fixed. A nice bonus of #3458 is fighting climax ignition doesn't black out anymore and is playable too
