### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Nisselioni** [RPCS3/rpcs3#3113]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC000001D.
Exception address: 00000000139fd016.
Instruction address: 00000000139fd016.
RPCS3 image base: 0000000000010000.

Illegal instruction exception occured.
Note that your CPU must support SSSE3 extension.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

I get this error, but only when using the recompiler for the PPU. I doubt it's a problem with my hardware, but I guess I have to state those anyway

Cpu: Pentium G2030 
Gpu: AMD Radeon HD 6900 series
16 GB Ram
OS:  Windows 10 Home 

If it's any help it happens while trying to run Persona 5

﻿RPCS3 v0.0.2-unknown Alpha
·! 0:00:00.000000 LDR: Path: E:/Downloads/rpcs3/dev_hdd0/game/NPEB02436/USRDIR/EBOOT.BIN
·! 0:00:00.000149 LDR: Title: Persona 5
·! 0:00:00.000156 LDR: Serial: NPEB02436
·! 0:00:00.000191 LDR: Cache: E:/Downloads/rpcs3/data/NPEB02436/af12cd50fd0e15f86b1148e7-EBOOT.BIN/
·! 0:00:00.000252 LDR: Applying custom config: data/NPEB02436/config.yml
·! 0:00:00.000925 LDR: Used configuration:
Core:
  PPU Decoder: Recompiler (LLVM)
  PPU Threads: 2
  PPU Debug: false
  Save LLVM logs: false
  Use LLVM CPU: ""
  SPU Decoder: Recompiler (ASMJIT)
  Bind SPU threads to secondary cores: true
  Lower SPU thread priority: true
  SPU Debug: false
  Maximum immediate DMA write size: 16384
  Lib Loader: Automatically load required libraries
  Hook static functions: false
  Load libraries:
    []
VFS:
  $(EmulatorDir): ""
  /dev_hdd0/: $(EmulatorDir)dev_hdd0/
  /dev_hdd1/: $(EmulatorDir)dev_hdd1/
  /dev_flash/: $(EmulatorDir)dev_flash/
  /dev_usb000/: $(EmulatorDir)dev_usb000/
  /dev_bdvd/: ""
  /app_home/: ""
  Enable /host_root/: false
Video:
  Renderer: OpenGL
  Resolution: 1280x720
  Aspect ratio: 16:9
  Frame limit: Auto
  Write Color Buffers: false
  Write Depth Buffer: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Log shader programs: false
  VSync: true
  Debug output: false
  Debug overlay: true
  Use Legacy OpenGL Buffers: false
  Use GPU texture scaling: true
  Stretch To Display Area: false
  Force High Precision Z buffer: false
  Invalidate Cache Every Frame: false
  Strict Rendering Mode: false
  Batch Instanced Geometry: false
  Vertex Upload Threads: 1
  Multithreaded Vertex Upload Threshold: 4096
  Enable Frame Skip: false
  Consecutive Frames Drawn: 1
  Consecutive Frames Skept: 1
  D3D12:
    Adapter: ""
  Vulkan:
    Adapter: ""
Audio:
  Renderer: OpenAL
  Dump to file: false
  Convert to 16 bit: false
  Downmix to Stereo: false
Input/Output:
  Keyboard: Basic
  Mouse: Basic
  Pad: XInput
  Camera: "Null"
  Camera type: Unknown
System:
  Language: English (UK)
Net:
  Connection status: Disconnected
  IP address: 192.168.1.1
Miscellaneous:
  Automatically start games after boot: true
  Exit RPCS3 when process finishes: false
  Start games in fullscreen mode: false
  Show FPS counter in window title: true
  Port: 2345
Log:
  {}

·! 0:00:00.011429 LDR: Elf path: /dev_hdd0/game/NPEB02436/USRDIR/EBOOT.BIN
·! 0:00:00.011456 LDR: ** Segment: p_type=0x1, p_vaddr=0x10000, p_filesz=0xccb7e8, p_memsz=0xccb7e8, flags=0x400005
·! 0:00:00.021645 LDR: ** Segment: p_type=0x1, p_vaddr=0xce0000, p_filesz=0x31217c, p_memsz=0x55cb58, flags=0x600006
·! 0:00:00.022940 LDR: ** Segment: p_type=0x1, p_vaddr=0x0, p_filesz=0x0, p_memsz=0x0, flags=0x4
·! 0:00:00.022967 LDR: ** Segment: p_type=0x1, p_vaddr=0x0, p_filesz=0x0, p_memsz=0x0, flags=0x6
·! 0:00:00.022972 LDR: ** Segment: p_type=0x1, p_vaddr=0x0, p_filesz=0x0, p_memsz=0x0, flags=0x6600006
·! 0:00:00.022977 LDR: ** Segment: p_type=0x7, p_vaddr=0xcfc9b8, p_filesz=0x0, p_memsz=0xec, flags=0x4
·! 0:00:00.022982 LDR: ** Segment: p_type=0x60000001, p_vaddr=0xcdb780, p_filesz=0x28, p_memsz=0x28, flags=0x0
·! 0:00:00.022986 LDR: ** Segment: p_type=0x60000002, p_vaddr=0xcdb7a8, p_filesz=0x40, p_memsz=0x40, flags=0x0
·! 0:00:00.022991 LDR: ** Section: sh_type=0x0, addr=0x0, size=0x0, flags=0x0
·! 0:00:00.022996 LDR: ** Section: sh_type=0x1, addr=0x10200, size=0x2c, flags=0x6
·! 0:00:00.023001 LDR: ** Section: sh_type=0x1, addr=0x10230, size=0xb332e8, flags=0x6
·! 0:00:00.023005 LDR: ** Section: sh_type=0x1, addr=0xb43518, size=0x24, flags=0x6
·! 0:00:00.023009 LDR: ** Section: sh_type=0x1, addr=0xb4353c, size=0x2a80, flags=0x6
·! 0:00:00.023013 LDR: ** Section: sh_type=0x1, addr=0xb45fbc, size=0x1ac, flags=0x2
·! 0:00:00.023018 LDR: ** Section: sh_type=0x1, addr=0xb46168, size=0x550, flags=0x2
·! 0:00:00.023022 LDR: ** Section: sh_type=0x1, addr=0xb466b8, size=0x4, flags=0x2
·! 0:00:00.023026 LDR: ** Section: sh_type=0x1, addr=0xb466bc, size=0x4, flags=0x2
·! 0:00:00.023030 LDR: ** Section: sh_type=0x1, addr=0xb466c0, size=0x4, flags=0x2
·! 0:00:00.023104 LDR: ** Section: sh_type=0x1, addr=0xb466c4, size=0x478, flags=0x2
·! 0:00:00.023113 LDR: ** Section: sh_type=0x1, addr=0xb46b3c, size=0x4, flags=0x2
·! 0:00:00.023118 LDR: ** Section: sh_type=0x1, addr=0xb46b40, size=0x74470, flags=0x2
·! 0:00:00.023121 LDR: ** Section: sh_type=0x1, addr=0xbbb000, size=0x120780, flags=0x2
·! 0:00:00.023125 LDR: ** Section: sh_type=0x1, addr=0xcdb780, size=0x28, flags=0x3
·! 0:00:00.023130 LDR: ** Section: sh_type=0x1, addr=0xcdb7a8, size=0x40, flags=0x2
·! 0:00:00.023134 LDR: ** Section: sh_type=0x1, addr=0xce0000, size=0x18, flags=0x3
·! 0:00:00.023137 LDR: ** Section: sh_type=0x1, addr=0xce0018, size=0x10, flags=0x3
·! 0:00:00.023141 LDR: ** Section: sh_type=0x1, addr=0xce0028, size=0x4, flags=0x3
·! 0:00:00.023145 LDR: ** Section: sh_type=0x1, addr=0xce0030, size=0x2aac, flags=0x3
·! 0:00:00.023149 LDR: ** Section: sh_type=0x1, addr=0xce2adc, size=0x550, flags=0x3
·! 0:00:00.023153 LDR: ** Section: sh_type=0x1, addr=0xce3030, size=0x16258, flags=0x3
·! 0:00:00.023157 LDR: ** Section: sh_type=0x1, addr=0xcf9288, size=0x3730, flags=0x3
·! 0:00:00.023161 LDR: ** Section: sh_type=0x8, addr=0xcfc9b8, size=0xec, flags=0x403
·! 0:00:00.023165 LDR: ** Section: sh_type=0x1, addr=0xcfcab0, size=0x2f56cc, flags=0x3
·! 0:00:00.023169 LDR: ** Section: sh_type=0x8, addr=0xff2180, size=0x24a9d8, flags=0x3
·! 0:00:00.023172 LDR: ** Section: sh_type=0x1, addr=0x0, size=0x28ed, flags=0x0
·! 0:00:00.023176 LDR: ** Section: sh_type=0x1, addr=0x0, size=0xc64, flags=0x0
·! 0:00:00.023180 LDR: ** Section: sh_type=0x3, addr=0x0, size=0x125, flags=0x0
·! 0:00:00.025315 LDR: *** sdk version: 0x420001
·! 0:00:00.025332 LDR: *** primary prio: 1001
·! 0:00:00.025336 LDR: *** primary stacksize: 0x10000
·! 0:00:00.025340 LDR: *** malloc pagesize: 0x100000
·! 0:00:00.025343 LDR: *** ppc seg: 0x0
·! 0:00:00.025346 LDR: * libent_start = *0xb466bc
·! 0:00:00.025350 LDR: * libstub_start = *0xb466c4
·! 0:00:00.025353 LDR: * unk0 = 0x420001
·! 0:00:00.025356 LDR: * unk2 = 0x0
·! 0:00:00.025365 LDR: ** Imported module 'cellAudio' (ver=0x1, attr=0x9, 0x0, 0x0) [0xb466c4]
·! 0:00:00.025380 LDR: **** cellAudio import: [cellAudioInit] -> 0xb4353c
·! 0:00:00.025387 LDR: **** cellAudio import: [cellAudioPortClose] -> 0xb4355c
·! 0:00:00.025393 LDR: **** cellAudio import: [cellAudioPortStop] -> 0xb4357c
·! 0:00:00.025397 LDR: **** cellAudio import: [cellAudioGetPortConfig] -> 0xb4359c
·! 0:00:00.025402 LDR: **** cellAudio import: [cellAudioPortStart] -> 0xb435bc
·! 0:00:00.025407 LDR: **** cellAudio import: [cellAudioQuit] -> 0xb435dc
·! 0:00:00.025411 LDR: **** cellAudio import: [cellAudioPortOpen] -> 0xb435fc
·! 0:00:00.025416 LDR: **** cellAudio import: [cellAudioAddData] -> 0xb4361c
·! 0:00:00.025420 LDR: **** cellAudio import: [cellAudioSetNotifyEventQueue] -> 0xb45f3c
·! 0:00:00.025426 LDR: **** cellAudio import: [cellAudioGetPortTimestamp] -> 0xb45f5c
·! 0:00:00.025431 LDR: **** cellAudio import: [cellAudioGetPortBlockTag] -> 0xb45f7c
·! 0:00:00.025435 LDR: **** cellAudio import: [cellAudioRemoveNotifyEventQueue] -> 0xb45f9c
·! 0:00:00.025439 LDR: ** Imported module 'cellSpursJq' (ver=0x1, attr=0x9, 0x0, 0x0) [0xb466f0]
·! 0:00:00.025445 LDR: **** cellSpursJq import: [cellSpursJobQueueAttributeSetDoBusyWaiting] -> 0xb4363c
·! 0:00:00.025450 LDR: **** cellSpursJq import: [cellSpursJobQueueAttributeInitialize] -> 0xb4365c
·! 0:00:00.025454 LDR: **** cellSpursJq import: [cellSpursShutdownJobQueue] -> 0xb4367c
·! 0:00:00.025458 LDR: **** cellSpursJq import: [cellSpursJoinJobQueue] -> 0xb4369c
·! 0:00:00.025463 LDR: **** cellSpursJq import: [_cellSpursCreateJobQueueWithJobDescriptorPool] -> 0xb436bc
·! 0:00:00.025467 LDR: **** cellSpursJq import: [cellSpursJobQueuePort2PushFlush] -> 0xb436dc
·! 0:00:00.025472 LDR: **** cellSpursJq import: [_cellSpursJobQueuePort2CopyPushJobBody] -> 0xb436fc
·! 0:00:00.025476 LDR: **** cellSpursJq import: [cellSpursJobQueuePort2Destroy] -> 0xb4371c
·! 0:00:00.025480 LDR: **** cellSpursJq import: [_cellSpursJobQueuePort2PushJobBody] -> 0xb4373c
·! 0:00:00.025488 LDR: **** cellSpursJq import: [cellSpursJobQueuePort2Create] -> 0xb4375c
·! 0:00:00.025494 LDR: **** cellSpursJq import: [cellSpursJobQueuePort2Sync] -> 0xb4377c
·! 0:00:00.025499 LDR: **** cellSpursJq import: [cellSpursJobQueuePort2PushSync] -> 0xb4379c
·! 0:00:00.025503 LDR: ** Imported module 'cellL10n' (ver=0x1, attr=0x9, 0x0, 0x0) [0xb4671c]
·! 0:00:00.025508 LDR: **** cellL10n import: [UTF8toUCS2] -> 0xb437bc
·! 0:00:00.025512 LDR: **** cellL10n import: [UCS2stoUTF8s] -> 0xb437dc
·! 0:00:00.025517 LDR: **** cellL10n import: [UCS2toUTF8] -> 0xb437fc
·! 0:00:00.025521 LDR: **** cellL10n import: [SJIStoUCS2] -> 0xb4381c
·! 0:00:00.025525 LDR: **** cellL10n import: [UTF8toSJIS] -> 0xb4383c
·! 0:00:00.025529 LDR: ** Imported module 'cellFont' (ver=0x1, attr=0x9, 0x0, 0x0) [0xb46748]
·! 0:00:00.025534 LDR: **** cellFont import: [cellFontCreateRenderer] -> 0xb4385c
·! 0:00:00.025539 LDR: **** cellFont import: [cellFontOpenFontsetOnMemory] -> 0xb4387c
·! 0:00:00.025543 LDR: **** cellFont import: [cellFontGetHorizontalLayout] -> 0xb4389c
·! 0:00:00.025547 LDR: **** cellFont import: [cellFontDestroyRenderer] -> 0xb438bc
·! 0:00:00.025552 LDR: **** cellFont import: [cellFontSetupRenderScalePixel] -> 0xb438dc
·! 0:00:00.025556 LDR: **** cellFont import: [cellFontSetScalePixel] -> 0xb438fc
·! 0:00:00.025561 LDR: **** cellFont import: [cellFontGetRenderCharGlyphMetrics] -> 0xb4391c
·! 0:00:00.025565 LDR: **** cellFont import: [cellFontEndLibrary] -> 0xb4393c
·! 0:00:00.025570 LDR: **** cellFont import: [cellFontBindRenderer] -> 0xb4395c
·! 0:00:00.025574 LDR: **** cellFont import: [cellFontGetVerticalLayout] -> 0xb4397c
·! 0:00:00.025579 LDR: **** cellFont import: [cellFontSetupRenderEffectSlant] -> 0xb4399c
·! 0:00:00.025583 LDR: **** cellFont import: [cellFontEnd] -> 0xb439bc
·! 0:00:00.025588 LDR: **** cellFont import: [cellFontRenderCharGlyphImage] -> 0xb439dc
·! 0:00:00.025592 LDR: **** cellFont import: [cellFontRenderSurfaceInit] -> 0xb439fc
·! 0:00:00.025596 LDR: **** cellFont import: [cellFontSetupRenderEffectWeight] -> 0xb43a1c
·! 0:00:00.025601 LDR: **** cellFont import: [cellFontCloseFont] -> 0xb43a3c
·! 0:00:00.025605 LDR: **** cellFont import: [cellFontRenderSurfaceSetScissor] -> 0xb43a5c
·! 0:00:00.025610 LDR: **** cellFont import: [cellFontInitializeWithRevision] -> 0xb43a7c
·! 0:00:00.025614 LDR: **** cellFont import: [cellFontUnbindRenderer] -> 0xb43a9c
·! 0:00:00.025618 LDR: ** Imported module 'cellFontFT' (ver=0x1, attr=0x9, 0x0, 0x0) [0xb46774]
·! 0:00:00.025623 LDR: **** cellFontFT import: [cellFontInitLibraryFreeTypeWithRevision] -> 0xb43abc
·! 0:00:00.025628 LDR: ** Imported module 'sys_fs' (ver=0x1, attr=0x9, 0x0, 0x0) [0xb467a0]
·! 0:00:00.025632 LDR: **** sys_fs import: [cellFsFtruncate] -> 0xb43adc
·! 0:00:00.025637 LDR: **** sys_fs import: [cellFsRmdir] -> 0xb43afc
·! 0:00:00.025641 LDR: **** sys_fs import: [cellFsClose] -> 0xb43b1c
·! 0:00:00.025645 LDR: **** sys_fs import: [cellFsOpendir] -> 0xb43b3c
·! 0:00:00.025650 LDR: **** sys_fs import: [cellFsRead] -> 0xb43b5c
·! 0:00:00.025654 LDR: **** sys_fs import: [cellFsOpen] -> 0xb43b7c
·! 0:00:00.025658 LDR: **** sys_fs import: [cellFsStat] -> 0xb43b9c
·! 0:00:00.025662 LDR: **** sys_fs import: [cellFsAioCancel] -> 0xb43bbc
·! 0:00:00.025666 LDR: **** sys_fs import: [cellFsUnlink] -> 0xb43bdc
·! 0:00:00.025670 LDR: **** sys_fs import: [cellFsFsync] -> 0xb43bfc
·! 0:00:00.025674 LDR: **** sys_fs import: [cellFsGetDirectoryEntries] -> 0xb43c1c
·! 0:00:00.025679 LDR: **** sys_fs import: [cellFsLseek] -> 0xb43c3c
·! 0:00:00.025683 LDR: **** sys_fs import: [cellFsSdataOpen] -> 0xb43c5c
·! 0:00:00.025687 LDR: **** sys_fs import: [cellFsMkdir] -> 0xb43c7c
·! 0:00:00.025690 LDR: **** sys_fs import: [cellFsAioRead] -> 0xb43c9c
·! 0:00:00.025696 LDR: **** sys_fs import: [cellFsAioInit] -> 0xb43cbc
·! 0:00:00.025707 LDR: **** sys_fs import: [cellFsWrite] -> 0xb43cdc
·! 0:00:00.025712 LDR: **** sys_fs import: [cellFsFstat] -> 0xb43cfc
·! 0:00:00.025716 LDR: **** sys_fs import: [cellFsRename] -> 0xb43d1c
·! 0:00:00.025722 LDR: **** sys_fs import: [cellFsClosedir] -> 0xb43d3c
·! 0:00:00.025726 LDR:

Edit: Messed up with the RPCS3.log, so I fixed it

**Comment by darkredflame** [comment]
Please use the search feature before reporting errors, this is a known error.

#2950

**Comment by AniLeo** [comment]
#2950, though it has been fixed on master for some time, unless they're running an old build, which we don't support anyways.
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
