### ISSUE TITLE
Unimplemented: sys_overlay_load_module [Metal Gear Solid 4]

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#3115]
MGS 4 demo NPUB90176 stops working after these messages
U {PPU[0x100001d] Thread (OVERLAY_LOAD) [0x00011ae0]} HLE TODO: Unimplemented syscall sys_overlay_load_module -> CELL_OK
F {PPU[0x100001d] Thread (OVERLAY_LOAD) [0x00011ae8]} MEM: Access violation reading location 0x0

**Comment by Xcedf** [comment]
fixed by https://github.com/RPCS3/rpcs3/pull/4007

**Comment by Xcedf** [comment]
As sys_overlay was merged this is not an issue now, but there's another issue i mentioned before in the PR
MGS4 Demo has this error after booting
F {PPU[0x100001d] Thread (OVERLAY_LOAD) [0x00011ae0]} class std::runtime_error thrown: vm::falloc() failed (addr=0x30000000, memsz=0x3c4160)
the game regressed from 449888b, vm.cpp requires this line to be readded
std::make_shared<block_t>(0x30000000, 0x10000000), // main extend

**Comment by elad335** [comment]
retest with #5816, I may fix that in that pr since it touches those vm addresses.

**Comment by AniLeo** [comment]
sys_overlay was merged so I'm closing this issue, feel free to create follow ups regarding different issues
