### ISSUE TITLE
Persona 5 std::runtime_error

### ISSUE THREAD

**Issue by LokiGrants** [RPCS3/rpcs3#3118]
Getting the famous class std::runtime_error thrown: Null function when trying to playing using the compiled SPU and PPU.

![image](https://user-images.githubusercontent.com/4370803/28741157-f2ca1742-73e6-11e7-8930-40a25dea2761.png)

**Comment by Talkashie** [comment]
That version is pretty outdated from the looks of it.

**Comment by Megamouse** [comment]
you are using some weird old build. try the newest

**Comment by AniLeo** [comment]
Yeah, we don't support older builds. Report results from master builds only.
If that still happens, then you're not using an untouched EBOOT as you should.
Use the forums for support, as this isn't an emulator issue.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
