### ISSUE TITLE
 MEM: Access violation reading location 0x0 with "libgcm_sys.sprx" selected in P5

### ISSUE THREAD

**Issue by Kompas9** [RPCS3/rpcs3#3121]
MEM: Access violation reading location 0x0 with "libgcm_sys.sprx" selected in Persona5 running Auto + Manual. 0.0.3-5522
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/1184789/RPCS3.txt)

**Comment by SakataGintokiYT** [comment]
@Kompas9 close this issue and download this build: https://github.com/RPCS3/rpcs3/pull/3096

**Comment by kamer1337** [comment]
did you have downloaded proper version? its not merged in master yet

**Comment by Kompas9** [comment]
Oh, I see
