### ISSUE TITLE
Program won't start

### ISSUE THREAD

**Issue by MitchMitchMitch** [RPCS3/rpcs3#3124]
I start the program and this is what comes up.
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xE06D7363.
Exception address: 00007ffd0f9f9e08.
ExceptionInformation[0x0]: 0000000019930520.
ExceptionInformation[0x1]: 00000000038feb10.
ExceptionInformation[0x2]: 00000000018346f8.
ExceptionInformation[0x3]: 0000000000010000.
Instruction address: 00007ffd0f9f9e08.
Function address: 00007ffd0f9f9da0 (base+0x69da0).
Module name: 'KERNELBASE.dll'.
Module base: 00007ffd0f990000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
