### ISSUE TITLE
Persona 5 [BLUS31604]: Vulkan Renderer Freeze

### ISSUE THREAD

**Issue by anoadragon453** [RPCS3/rpcs3#3127]
OS: Arch Linux 64bit
CPU: i7-4790
GPU: GTX 970 4GB
RAM: 16GB
Using AppImage 07/29/17

While the game works fine with OpenGL (albeit quite laggy), the game freezes anywhere from after a few frames to just after you get past the network options menu with Vulkan.

Here are my settings:
![rpcs3-settings](https://user-images.githubusercontent.com/1342360/28748609-63326fd8-74ab-11e7-9200-0c41562b35f3.png)

Also experience freeze on Vulkan with KH1.5 [BLUS31212] after selecting main game. May possibly be related to #3116.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1185299/RPCS3.zip)

**Comment by AniLeo** [comment]
Known. Needs lle-gcm to be stable, which will be merged soon. It's also a duplicated issue.

**Comment by anoadragon453** [comment]
Yep, can confirm it now works very well.
