### ISSUE TITLE
Kingdom Hearts 1.5 ReMIX [BLUS31212]: Crash on game start

### ISSUE THREAD

**Issue by anoadragon453** [RPCS3/rpcs3#3129]
OS: Arch Linux 64bit
CPU: i7-4790
GPU: GTX 970 4GB
RAM: 16GB
Tested with AppImage 07/29/17 and LLE GCM PR (b6971be)

I can start and watch up to day ~74 in 358/2 in KH 1.5, but the actual game leads to a black screen, then it crashes after a few moments.

Here are my settings:
![rpcs3-settings](https://user-images.githubusercontent.com/1342360/28748609-63326fd8-74ab-11e7-9200-0c41562b35f3.png)

~~[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1185463/RPCS3.zip)~~ [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1185990/RPCS3.zip)

**Comment by hcorion** [comment]
The log you provided is a Persona 5 log. 
Anyway, have you tried setting Framelimit -> Auto ?

**Comment by anoadragon453** [comment]
> The log you provided is a Persona 5 log.
Whoops, that's strange. My bad.

> Anyway, have you tried setting Framelimit -> Auto ?
Just tried, doesn't seem to have any effect.

Correct 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1185990/RPCS3.zip)

**Comment by Sora3100** [comment]
Last I checked you needed to boot kingdom.self directly

**Comment by anoadragon453** [comment]
That seems to have fixed it, thanks!

Does RPCS3 have a wiki or something where we can note down all the different settings/quirks a game title has? If not we should really add one.
