### ISSUE TITLE
Jojo's Bizzare Adventure: All-Star Battle: Errors, Audio Stutter, and Darkness

### ISSUE THREAD

**Issue by imsalt** [RPCS3/rpcs3#3141]
Hi! I'm using the Vulcan Renderer on build v.0.0.3-9-54f990a Alpha with a 5820k 6-Core CPU @ 4.4 GHz and a Zotac AMP! Extreme 1080ti. Edit: Also have 32 GB DDR4 RAM and I've kept all the settings to the default pre-set besides Renderer.

First issue seems to be the audio, the emulator itself displays a constant 28-30 FPS but the audio sounds as if the emulator is running at a constant 20 fps, the gameplay feels like it is running at full speed however.

2nd issue is when I get into the game play it's almost complete darkness (See link to pictures below)

[https://prnt.sc/g3oysh](url)
[https://prnt.sc/g3oysh](url)

**Comment by imsalt** [comment]
Update: When setting the Renderer to OpenGL the error and the audio stuttering is still there, but when i go into a match, the audio stuttering goes away and I can see the entire battle perfectly now but it drops to 21 FPS average.

**Comment by Dokman** [comment]
@imsalt wait until they fix the audio stuttering it appears in almost every game i think

**Comment by AniLeo** [comment]
Retest on latest master to see if the graphical issues persist.

**Comment by AniLeo** [comment]
Inactive issue.

The graphical issues on this game were fixed
See: https://www.youtube.com/watch?v=HlMEX0BKCt8

Audio stutter is unrelated and will happen due to slow emulation. Doesn't make sense to keep a per-game issue opened on a general issue like that, so closing this issue as graphical issues were solved.
