### ISSUE TITLE
Hard Corps Uprising [NPEB00332] problem with CellSysUtilAvc2

### ISSUE THREAD

**Issue by Ru4slan** [RPCS3/rpcs3#3143]
Maybe, game tries to launch video?
F {PPU[0x100000b] Thread (mnp Session Procedure) [0x0126e540]} class std::runtime_error thrown: Unimplemented
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellSysutilAvc2.cpp:114)

**Comment by AniLeo** [comment]
#3138

**Comment by Ru4slan** [comment]
okay
