### ISSUE TITLE
_sys_spu_image_import Heavenly Sword Demo NPUA80103

### ISSUE THREAD

**Issue by woj1993** [RPCS3/rpcs3#3144]
Havenly sword boots to main screen and pauses on this error.
Unimplemented syscall: _sys_spu_image_import .
I someone would look into this and these errors:
https://github.com/RPCS3/rpcs3/issues/2717
https://github.com/RPCS3/rpcs3/issues/1283
It would probably work.

Edit: Log [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1198196/RPCS3.zip)

**Comment by SakataGintokiYT** [comment]
@AniLeo 
Fixed by #3324
