### ISSUE TITLE
The Orange Box [BLUS30055] _sys_spu_image_get_information

### ISSUE THREAD

**Issue by JusicP** [RPCS3/rpcs3#3148]
RPCS3 v0.0.3-5588-7b43d88f Alpha

Unimplemented syscall: _sys_spu_image_get_information
After this message, the game stops working. Same message has Counter-Strike: Global Offensive.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1199596/RPCS3.zip)

**Comment by SakataGintokiYT** [comment]
@AniLeo 
Fixed by #3324

**Comment by AniLeo** [comment]
Impossible, that PR doesn't toch _sys_spu_image_get_information

**Comment by kacek** [comment]
retry with #3366
