### ISSUE TITLE
Default console language is Japanese

### ISSUE THREAD

**Issue by JarnoVgr** [RPCS3/rpcs3#3149]
Default console language is set to the first possible option: Japanese. I assume this should be English (US). Can be reproduced by removing the config YML file.

**Comment by AniLeo** [comment]
It's not an issue, it's on purpose

**Comment by JarnoVgr** [comment]
All right. Couldn't find any existing/closed issue on this. Care to elaborate why this is on purpose? :)

**Comment by AniLeo** [comment]
I think it's because compatibility with some Japanese games out of the box, one should ask @Nekotekina

**Comment by SaltyCucumber** [comment]
I've asked devs, you should leave it as is - japanese. Some jap games need that.
Can be closed.
