### ISSUE TITLE
BlackScreen when playing Hyperdimension.Neptunia [BLUS30701] with OpenGL

### ISSUE THREAD

**Issue by wydy** [RPCS3/rpcs3#3150]
I can see picture when I use D3D12 or Vulcan,but I cannot see anything when I use OpenGL
I can hear sound when I use OpenGL
I am using default seeting and using latest build

**Comment by scribam** [comment]
@wydy Try with the following GPU settings:
- "Write Color Buffers" and "Strict Rendering Mode" enabled
- "Use GPU Texture Scaling" disabled

**Comment by wydy** [comment]
thanks for your reply
It seem that this setting running but can not running properly...
![1](https://user-images.githubusercontent.com/1937986/29204520-146737ae-7eaa-11e7-9086-1a3d36d5517c.gif)

**Comment by kd-11** [comment]
Try https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.3-899
The game is using offscreen rendering and blitting the result to the backbuffer without a renderpass. The current implementation completely skips this (in OGL, vulkan and DX12 use much worse hacks for flip). That build might fix some of those half-height games as well

**Comment by wydy** [comment]
@kd-11 
This build can solve the problem of display,that is cool.
But it still have small bug that the graphics dislocation at right side and bottom of the window.
See this
![1](https://user-images.githubusercontent.com/1937986/29257352-e616a36c-80e3-11e7-942c-3ae302a916d4.gif)

Another problem is broken graphics in 3D battle mode of this game.I have upload the logs hoping to provide some information to help solve this problem.
![2](https://user-images.githubusercontent.com/1937986/29257360-f1f2da5c-80e3-11e7-988e-e9d588603cec.gif)
[logs.txt](https://github.com/RPCS3/rpcs3/files/1221210/logs.txt)

**Comment by kd-11** [comment]
The distortion to the right and bottom parts is a known bug when using GPU accelerated scaling. The ingame graphics bug looks like broken post-processing.

**Comment by wydy** [comment]
@kd-11 
What is post-processing?Could I fix it myself?

**Comment by AniLeo** [comment]
Original issue here has been fixed, closing.

For different issues, please open a new issue detailing on them. Don't forget to attach a log file and test on latest emulator / video drivers versions.
