### ISSUE TITLE
Occasionally error at sys_lwmutex_lock when playing BLJS10133

### ISSUE THREAD

**Issue by thu011292** [RPCS3/rpcs3#3151]
platform: i7-4700MQ/8G RAM/GTX 860M or HD 4600/Win10 10.0.14393

After playing with BLJS10133(2nd Super Robot Wars Original Generation) for a while with the latest build 0.0.3-5557, this error will raise:
`·F 0:19:24.534505 {PPU[0x1000001] Thread (PMEM_POOL000) [0x008f235c]} class std::runtime_error thrown: Locking failed (lwmutex=*0x20100e40, owner=0x1000039) (in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_lwmutex_.cpp:181)`

I'm not sure if this is a common error or something platform-dependent, but I've seen someone else meeting with the same problem at local bbs.

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/1200611/RPCS3.log.zip)

**Comment by scribam** [comment]
@thu011292 Please retest with a recent build

**Comment by scribam** [comment]
@thu011292 Any updates?

**Comment by elad335** [comment]
sys_lwmutex is lled by default, needs retesting.
