### ISSUE TITLE
Is There Anyway To Fix This Error.......And Thanks.

### ISSUE THREAD

**Issue by Veronsen** [RPCS3/rpcs3#3157]
Unhandled Win32 exception 0xC0000005
Segfault reading location 0000000000000000 at
0000000000470a87.
Instruction address: 0000000000470a87.
Fuction address: 0000000000470660(base+0x460660)
Module name: 'rpcs3.exe'
Module base: 0000000000010000
RPCS3 image base:0000000000010000

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.

**Comment by Veronsen** [comment]
thanks anyway
