### ISSUE TITLE
Couple issues with RCPS3 and Demon Souls.

### ISSUE THREAD

**Issue by anyanyanyx** [RPCS3/rpcs3#3159]
After every cutscene, game crashes with: 
system_error thrown: device or resource busy: device or resource busy

I also get a million other errors while simply playing through the game, I didn't want to spam a million code here so i'll just post an image of the code altogether in one picture (In this code, the sound cuts out and then after I die none of the textures load and it's just a black screen): http://i.imgur.com/Kd8l1vh.png

Another weird thing is that I cannot select vulkan in the GPU settings, I have all the other 3 options available except Vulkan, I even reinstalled drivers but that didn't work.

Also the game is incredibly laggy but im not sure if that's my card's problem or if it's just because the emulator is still pretty new and needs work on, anyways I appreciate any help.

**Comment by AniLeo** [comment]
**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**
