### ISSUE TITLE
[BLJM61097 Puyo Puyo Tetris] Game crash/close after level completion

### ISSUE THREAD

**Issue by Woovie** [RPCS3/rpcs3#3162]
After completion of a level, an error dialog appears and the game crashes.

http://www.emunewz.net/forum/showthread.php?tid=173703&pid=284003#pid284003

The initial dialog shown in the video is labeled as an error dialog, but it just states that the game is loading save data. After the crash, it gives a popup of what looks like probably a memory offset, and then another dialog stating that the game is going to be closed.

This error can be replicated every time on levels 5, 6, 7. I haven't fully tested this game, such as other game modes, or even other levels beyond 7, for this crash.

RPCS3.log and TTY.log https://drive.google.com/open?id=0B8HkGRwycb4LVEZiazY5Ymh2UFU

Windows 10 Pro 64bit
Intel i7 7700k
GTX 980 Ti
16GB DDR4

**Comment by scribam** [comment]
@Woovie Can you test again and upload a new log if the issue still exist?

**Comment by Woovie** [comment]
@scribam Will do as soon as I have a moment to test it.

**Comment by scribam** [comment]
@Woovie Any update on this?

**Comment by AniLeo** [comment]
Still can't be reproduced, will assume fixed due to lack of reply and the issue being so old. Reopen if you can reproduce on latest master.
