### ISSUE TITLE
Crash Bandicoot SCU94900 SCUS94154 SCUS94244 failed to boot

### ISSUE THREAD

**Issue by Woovie** [RPCS3/rpcs3#3163]
Testing all 3 of these .pkg games. Seeing the following for each after install.

RPCS3 v0.0.3-5588-7b43d88f Alpha
Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz | 8 Threads | 15.95 GiB RAM | AVX | TSX
E LDR: Failed to boot C:/rpcs3/dev_hdd0/game/NPUI94900
E LDR: Failed to boot C:/rpcs3/dev_hdd0/game/NPUI94154
E LDR: Failed to boot C:/rpcs3/dev_hdd0/game/NPUI94244

**Comment by Megamouse** [comment]
isn't that a ps1 game?
they don't work on this emulator (maybe never if the ps1 emulator inside rpcs3 won't be implemented)

**Comment by AniLeo** [comment]
You're in the wrong emulator 

Try https://mednafen.github.io/
