### ISSUE TITLE
Regressions caused by zcull implementation (#3135)

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#3165]
This ticket is here to track any regressions introduced by https://github.com/RPCS3/rpcs3/pull/3135

**Comment by isshininu** [comment]
Well, this is new:

[RPCS3.ZIP](https://github.com/RPCS3/rpcs3/files/1203068/RPCS3.ZIP)
![fps_ 21 39 _ opengl _ demon s souls _ bles00932 06 08 2017 16_48_20](https://user-images.githubusercontent.com/6324523/29003415-b3222be2-7ac7-11e7-9bf9-bdd78e2732e9.png)
![fps_ 21 39 _ opengl _ demon s souls _ bles00932 06 08 2017 16_48_52](https://user-images.githubusercontent.com/6324523/29003422-c2cbe3f8-7ac7-11e7-905e-9b62007ab749.png)

**Comment by Xcedf** [comment]
After this PR games have a hell of a slowdown before to render ingame graphics, like something being cached, when it stops fps going back to normal, but the games like Condemned 2 caching smth every second and slowdowns don't stop, what could it be?

**Comment by Xcedf** [comment]
Another regression in game Saw II, some parts of the game are blacked out
![27](https://user-images.githubusercontent.com/7060586/29005101-90eece76-7adc-11e7-8c12-c6b4f2075f16.jpg)
found the commit to cause this
https://github.com/kd-11/rpcs3/commit/7411bc27ba0486834249fafc14bc72677699e519

**Comment by kd-11** [comment]
The vertex rewrite builds have hitching due to increased time used to generate graphics pipelines. If the issue is actually present in naster that would be great actually since it makes deployment much easier once fixed.
As for missing graphics in some games, it seems they arent drawing occluders - will need to research why.
As for DeS, the game does misbehave on occasion. Rebooting usually solves the issue.

**Comment by kd-11** [comment]
Actually after looking at the commit you identified, looks like a trivial fix for saw which is a relief. Any other games  misbehaving this way?
Also, if you can, test for the stuttering issue. This PR shouldnt have affected things that much, but it is possible that locks in the texture cache are somehow causing this.

**Comment by Xcedf** [comment]
@kd-11 look's like stuttering is actually in the master now searching the commit which is after this, will give info is a few minutes

**Comment by money123451** [comment]
[Pre Zcull merge in RDR opengl](https://cdn.discordapp.com/attachments/272035812277878785/343795835210825728/2017-08-06_16_37_45-FPS__2.65___OpenGL___Red_Dead_Redemption___BLUS30418.png) and [post Zcull merge in RDR opengl](https://cdn.discordapp.com/attachments/272035812277878785/343795835210825728/2017-08-06_16_37_45-FPS__2.65___OpenGL___Red_Dead_Redemption___BLUS30418.png)

**Comment by digitaldude555** [comment]
Red Dead Redemption. 
Before Zcull
![2017-08-06_16_41_23-fps__2 06___opengl___red_dead_redemption___blus30418](https://user-images.githubusercontent.com/26138653/29005265-e054620c-7adf-11e7-899e-bdf8a34df1ca.png)

After
![2017-08-06_16_37_45-fps__2 65___opengl___red_dead_redemption___blus30418](https://user-images.githubusercontent.com/26138653/29005280-03af8740-7ae0-11e7-851e-7fa66aba4cb2.png)

**Comment by Xcedf** [comment]
Sorry about the wrong info, there are no stutters in master, they caused by some of early commits after master ones

**Comment by kd-11** [comment]
Its ok. Can I get a trace of before and after the commit that ruined saw II?
It seems to be unrelated to zcull if the state management patch is what made the game break

**Comment by Xcedf** [comment]
If you mean the log
here's one before
https://mega.nz/#!bEBFkISL!Jcx90MNwsLexq7fycA5FH5IUhwtfgvOzvg5kPFl0LJY
and one after
https://mega.nz/#!LQJWGTZI!DaqrEQPqKW32uSK4Fsd-7nzazci4gL90KGJPqfLFUXI

**Comment by kd-11** [comment]
Please check if https://github.com/RPCS3/rpcs3/pull/3168 fixes the issues

**Comment by SakataGintokiYT** [comment]
@kd-11 

**[ Saw 2 ]**
*No change #3168

**[*RenderDoc with zcull :](https://mega.nz/#!ZMJUDZyB!e-2lwzzrfR01pzC73jEnqtdbM1ylyH7u9QtstgWn-RM)**
**[*RenderDoc before zcull:](https://mega.nz/#!MIxDATCC!s19NsTwFvtD_QK_SGMON3IJ5HlbqZYgvqFFMjEHd0kw)**

**Comment by money123451** [comment]
well that new zcull build 0.0.3-867 on you appveyor (KD-11) did this to rdr under opengl lol
![2017-08-06 22_02_20-fps_ 5 17 _ opengl _ red dead redemption _ blus30418](https://user-images.githubusercontent.com/12605368/29008796-8338d2b4-7ad1-11e7-93b9-6ce4bfc97ad3.png)

**Comment by kamer1337** [comment]
still look like this with [#3168](https://github.com/RPCS3/rpcs3/pull/3168)
![zcull](https://user-images.githubusercontent.com/18437274/29017598-d028a73a-7b57-11e7-94e6-be596fec4290.PNG)

i dont know how to use renderdoc

**Comment by kd-11** [comment]
@money123451 RDR works perfectly for me although I now suspect a driver issue. It all comes down to how reliable the driver is at generating occlusion reports without notice.
@kamer1337 Its not really zcull causing that its some of the restructuring. Unfortunately the saw traces are just blank on my system so I'll need to find another case where reorganizing the renderer breaks things

**Comment by SakataGintokiYT** [comment]
@kd-11 
Do you need trace before this commit and after ?
https://github.com/kd-11/rpcs3/commit/7411bc27ba0486834249fafc14bc72677699e519

**Comment by kd-11** [comment]
Yes. I have however pushed another commit to be a little more strict with how things work now since I did not initialize the pipeline with defaults anyway. Saw is very broken on master I'm surprised it even works. Vertex rewrite solves most of those issues, but thats a different problem.
Just check if the latest commit changes anything

**Comment by SakataGintokiYT** [comment]
same on 5e12f9c

**Comment by kd-11** [comment]
Are these two games the only ones affected?

**Comment by kd-11** [comment]
Looks like RDR also regressed again. I'll keep checking but I dont think the commit listed is the one that breaks visuals. I suspect its zcull itself. It may also affect the skate game if it uses zcull to decide where the sun is visible like demons souls

**Comment by kamer1337** [comment]
tested skate 3 its also regressed on opengl, broken graphics at specified direction

**Comment by kd-11** [comment]
Can you check the log for `RSX: Conditional rendering mode enabled (mode 2)`?

**Comment by kamer1337** [comment]
the log is spammed with 
RSX: Conditional rendering mode enabled (mode 2)

**Comment by kd-11** [comment]
@SakataGintokiYT Does that message also appear in SAW?

**Comment by SakataGintokiYT** [comment]
@kd-11 
No

**Comment by SakataGintokiYT** [comment]
@kd-11 
https://github.com/kd-11/rpcs3/commit/7411bc27ba0486834249fafc14bc72677699e519

**[Saw 2]**
[RenderDoc Before](https://mega.nz/#!xFh1HDTT!d1OwAc38u7Z1mfBrp16S6EQdnYQT1icD5qkU4-iUEUs)
[RenderDoc After](https://mega.nz/#!sRY2gDgD!xiSSjG8umZFS15yaI5dMQJCq4q0ej-vjR8lZ-kZrNaI)

**Comment by kd-11** [comment]
I pushed another commit. Not sure if it does anything for saw since that rdc is blank for some reason. Its probably just a renderdoc bug though

**Comment by money123451** [comment]
it seems like build 0.0.3-870 fixed most of the issues.  👍 
![2017-08-07 10_18_47-fps_ 2 26 _ opengl _ red dead redemption _ blus30418](https://user-images.githubusercontent.com/12605368/29028193-568622be-7b38-11e7-84bd-d2a6412f9716.png)

**Comment by SakataGintokiYT** [comment]
@kd-11 
![bez tytulu](https://user-images.githubusercontent.com/13681488/29029961-c2e29676-7b89-11e7-99a6-ffe3ada2ac9e.png)

no change : c4ee280

**Comment by kd-11** [comment]
Thats a persistent image from the previous frame. Checking actual draws shows no output but the result is already there for some reason. Clear before pass also doesnt work so I cant actually tell which parts of the command stream actually affect output. Also, index buffers are not properly scoped so during playback renderdoc ends up with out-of-range access errors (You can check mesh output - its missing/empty on most passes)

**Comment by kamer1337** [comment]
no changes with latest commit for skate 3 and tony hawk

**Comment by kd-11** [comment]
Ok, so after taking a deeper look there are several minor bugs introduced by the restructuring. Will update soon

**Comment by kd-11** [comment]
Should be fixed now

**Comment by SakataGintokiYT** [comment]
@kd-11 
[7ae11174]
![bez tytulu](https://user-images.githubusercontent.com/13681488/29037682-ed9739e2-7ba4-11e7-80ff-2a69592d2e76.png)

**Comment by kamer1337** [comment]
tony hawk's project 8 fixed. skate 3 still the problem occur

**Comment by kd-11** [comment]
The problem was always there in skate 3. Its a known issue

**Comment by kamer1337** [comment]
screenshot of game before zcull bushes look ok
![adwwd](https://user-images.githubusercontent.com/18437274/29039195-9c7914b2-7baa-11e7-85a8-d9bacfc86b3f.PNG)

**Comment by Xcedf** [comment]
Confirm last commit fixed saw ii, thanks, don't have regressions in other games

**Comment by Luffykun007** [comment]
@ Kd-11 I'm having this error in RDR in its build 0.0.3-871

![capturar](https://user-images.githubusercontent.com/26087621/29043395-61171f72-7b91-11e7-8f99-75b6787af5a4.JPG)

**Comment by kamer1337** [comment]
@Luffykun007 its not related to this topic and you use vulcan, zcull is opengl only atm

**Comment by Luffykun007** [comment]
Right understood!

**Comment by money123451** [comment]
yap that is why I have been testing with opengl here even if I have a RX 480 I didn't want to ignore the regression that might make its way into vulkan.

**Comment by Asinin3** [comment]
@SakataGintokiYT The TVs in the screenshot you posted are white, is that a regression?

**Comment by SakataGintokiYT** [comment]
@Asinin3  Nope

**Comment by Asinin3** [comment]
I have found a regression with zcull in Ni No Kuni:

zcull ( RPCS3 v0.0.3-8-7ae1117  ) - latest master
https://my.mixtape.moe/imtwij.mp4
Log soon

Before Zcull ( RPCS3 v0.0.3-3-02845f5 )
https://my.mixtape.moe/rpxgwp.mp4

**Comment by Asinin3** [comment]
In case you're wondering @kd-11 Pop-in and clipping still exist in 0.0.3-5635 I will update this in a minute if I run into the texture bug again.

**Comment by kd-11** [comment]
Should be fixed in vertex_rewrite. Its a bug in the game itself that we did not check for.

**Comment by Asinin3** [comment]
It's still not fixed in latest vertex_rewrite
![image](https://user-images.githubusercontent.com/15137035/29228826-85bf74dc-7f1a-11e7-9a5c-4c0749ad54bc.png)

**Comment by kd-11** [comment]
It seems to be triggered by the re-enabling of depth clamping if its only on openGL. Another issue already tracks the issue so I'll close this one since the other issues are fixed.

**Comment by Asinin3** [comment]
@kd-11 If there is a build with zcull that doesn't have the depth clamping I can test it if you'd like.

**Comment by kd-11** [comment]
Ni no kuni issue is tracked separately. Closing this.
