### ISSUE TITLE
Issue on libsysmodule.sprx

### ISSUE THREAD

**Issue by Edeonis** [RPCS3/rpcs3#3167]
Hello,

On release 0.0.3-5575, libsysmodule.sprx seems to be not loaded correctly at start  (Personna 5): 
`F LDR: class std::runtime_error thrown: Failed to load /dev_flash/sys/external/libsysmodule.sprx: Invalid stream or file not found`
(The file exist)

I tested with old version 0.0.3-5436 and it worked well

**Comment by AniLeo** [comment]
Can you post a full log? 

Also, what firmware are you using? 4.81?

**Comment by Edeonis** [comment]
yes 4.81 for the two builds
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/1203326/RPCS3.txt)

**Comment by AniLeo** [comment]
What's the structure for your dev_flash folder? Did you try with a clean setup. It works here.

**Comment by Megamouse** [comment]
does not look like you installed the firmware

**Comment by Edeonis** [comment]
yes but it is

**Comment by Megamouse** [comment]
try with a new one

**Comment by Edeonis** [comment]
OK I will to check that

**Comment by Edeonis** [comment]
yes it works on last release
