### ISSUE TITLE
Persona 5 keeps closeing error

### ISSUE THREAD

**Issue by Yahiko12** [RPCS3/rpcs3#3169]
I  keep getting this error when I play persona 5 on the emulator, it'll load and i will get through some title cards then it'll give this error and then close. I re downloaded the emulator and I still got the error. i also left the CPU, GPU settings on default . I don't know a lot about computers or gaming and this is my first time using a emulator, so please try to give simple answers .
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000010 at 00007ffbf7c23ea6.
Instruction address: 00007ffbf7c23ea6.
Function address: 00007ffbf7c23ea0 (base+0x1b3ea0).
Module name: 'ig8icd64.dll'.
Module base: 00007ffbf7a70000.
RPCS3 image base: 0000000000010000.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
