### ISSUE TITLE
Windows: SetThreadExecutionState needs to be set to prevent screen sleep

### ISSUE THREAD

**Issue by guythnick** [RPCS3/rpcs3#3171]
In Windows, monitor will fall asleep while game is running.  Asking to add a SetThreadExecutionState to code so that monitor will not sleep while game is in use with gamepad.

**Comment by scribam** [comment]
#3172

**Comment by scribam** [comment]
@guythnick Code changes have been merged into master. Would you mind testing again to check if this is still an issue?

**Comment by AniLeo** [comment]
Solved via #3172
