### ISSUE TITLE
Portal 2 [BLUS30732] spam "Unimplemented syscall sys_net_bnet_select -> CELL_OK"

### ISSUE THREAD

**Issue by JusicP** [RPCS3/rpcs3#3173]
When i play Portal 2 about 5 minutes, RPCS3 log size about 1gb!
It spam to log "HLE TODO: Unimplemented syscall sys_net_bnet_select -> CELL_OK"
![log](https://user-images.githubusercontent.com/25232950/29015146-79fc300e-7b55-11e7-9548-7a2152af56c6.png)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1204030/RPCS3.zip)
I tried all network status in settings, but nothing changed.

**Comment by JusicP** [comment]
And P2 have graphics bugs
![p2_bug01](https://user-images.githubusercontent.com/25232950/29126487-293a0abe-7d27-11e7-96a7-515d3af42a49.png)
![p2_bug02](https://user-images.githubusercontent.com/25232950/29126492-2b0ff9fc-7d27-11e7-9dd9-a2043c385470.png)

**Comment by JusicP** [comment]
![dosomthing](https://user-images.githubusercontent.com/25232950/29241229-4915b578-7f7e-11e7-8ddd-8264248c5ec2.png)

**Comment by clienthax** [comment]
This isn't really a bug, we know it's unimplemented

**Comment by AniLeo** [comment]
Closing this one since we know unimplemented syscalls
