### ISSUE TITLE
[Linux/evdev] XBox One S Controller triggers do not work

### ISSUE THREAD

**Issue by HollowSoldier** [RPCS3/rpcs3#3179]
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x45e product 0x2ea version 0x301
Input device name: "Microsoft X-Box One S pad"

Connected via USB cable.

Every button works and is correctly mapped, except for the triggers, who do absolutely nothing. Creating a config file per RPCS3 evdev tutorial and setting "Z axis triggers" to true or false makes no difference.

Evtest shows proper trigger behavior, sending events as outlined below.

Left trigger:
Event code 2 (ABS_Z)
      Value      0
      Min        0
      Max     1023

Right trigger:
Event code 5 (ABS_RZ)
      Value      0
      Min        0
      Max     1023

**Comment by kirbyfan64** [comment]
- Can you post your log file?
- Can you show the *full* evtest output? The snippet you showed has a value of 0, which would mean the button is *not* being pressed at that time.

FWIW with the XBox controllers *Z axis triggers* should be left at the default setting of `true`.

**Comment by HollowSoldier** [comment]
The log doesn't seem to contain any input related entries, but here it is anyway. Evtest output too, though the rest is about other buttons, that work in the emulator fine. I also included some lines of testing. Left trigger pulled and released first, then right trigger pulled and released.
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/1209228/RPCS3.log.zip)
[evtest.txt.zip](https://github.com/RPCS3/rpcs3/files/1209229/evtest.txt.zip)

Let me know if more information/testing is needed.

**Comment by kirbyfan64** [comment]
@HollowSoldier Last thing: if you try this homebrew:

http://www.dashhacks.com/ps3/ps3-homebrew/ps3-game-pad-test-utitlity-by-developer-zar.html

and *just* press the left and right trigger (and nothing else), what does the log file look like then? Do you see any strange behavior (other than left and right triggers not working)?

**Comment by HollowSoldier** [comment]
Good news is that the testapp does pick up the triggers. Bad news is that it reads invalid, out of range values. Comparison with xinput follows, also notice the green rectangle around "L2". While it qualifies as pressed with xinput, it does not qualify as pressed when using evdev.

XInput, pressed halfway:
![xinput-half](https://user-images.githubusercontent.com/20152912/29092217-dd2f6b1a-7c85-11e7-939a-3af767e617ba.png)

Evdev, pressed halfway:
![evdev-half](https://user-images.githubusercontent.com/20152912/29092236-f3afaaa8-7c85-11e7-9cde-7172a45f10bd.png)

XInput, fully pressed:
![xinput-full](https://user-images.githubusercontent.com/20152912/29092241-fe5c13d8-7c85-11e7-9b65-4ffbe7883d5c.png)

Evdev, fully pressed:
![evdev-full](https://user-images.githubusercontent.com/20152912/29092246-07ec2a6e-7c86-11e7-8a0c-2304fa34ab27.png)

**Comment by HollowSoldier** [comment]
Good news is that the testapp does pick up the triggers. Bad news is that it reads invalid, out of range values. Comparison with xinput follows, also notice the green rectangle around "L2". While it qualifies as pressed with xinput, it does not qualify as pressed when using evdev.

Xinput halfway pressed:
![xinput-half](https://user-images.githubusercontent.com/20152912/29092448-af0489b8-7c86-11e7-9d33-359545215e0e.png)

Evdev halfway pressed:
![evdev-half](https://user-images.githubusercontent.com/20152912/29092450-b226f46e-7c86-11e7-9dac-76ec35c2dbe2.png)

Xinput fully pressed:
![xinput-full](https://user-images.githubusercontent.com/20152912/29092453-b506d258-7c86-11e7-96e9-9c6a55a00323.png)

Evdev fully pressed:
![evdev-full](https://user-images.githubusercontent.com/20152912/29092460-b893c94e-7c86-11e7-9dae-65bf51de9cb3.png)

**Comment by hcorion** [comment]
Xbox One (S) controller must have a large value for the triggers.

**Comment by HollowSoldier** [comment]
According to evdev, it's 0-1023. Judging from these pictures, Xinput reports 1-100 percentage. Probably the input range should be scaled, no matter what controller provides it. A future controller may report 0-99999 or anything.

**Comment by kirbyfan64** [comment]
FWIW I have a WIP fix for this, but I recently reinstalled Linux and have to rebuild RPCS3 first.

**Comment by HollowSoldier** [comment]
Fixed by #3202.

**Comment by hcorion** [comment]
Just FYI, common practice is to close issues when Pull Request is merged into master @HollowSoldier .

**Comment by kirbyfan64** [comment]
@hcorion But it's not merged yet...

**Comment by hcorion** [comment]
Exactly, that's why I'm telling him that common practice don't close issues until the related PR is merged.

**Comment by kirbyfan64** [comment]
Oh, the way you worded it sounded like you were trying to convey a slightly different idea. (Now that I think about it, though, I'm not sure what else you would've meant...)
