### ISSUE TITLE
[Linux] evdev controller input improvements

### ISSUE THREAD

**Issue by hcorion** [RPCS3/rpcs3#3181]
Just a collection of desired improvements to the linux evdev controller input.
- [x] Squircling joysticks. Completed via 66a43c35dbaa63c5ebba2690ad8ff0a982b882e5
- [x] Add joystick deadzone. Completed via 0c5cb4824b402f6cbd3616c95c6702638bf8e0e9
- [x] Add separate configs for more controllers.
- [x] Allow binding axis to digital buttons [requested by toccata10](https://github.com/RPCS3/rpcs3/pull/2885#issuecomment-318586297)
- [x] Add rumble emulation
- [x] Add ability to configure evdev controllers via the the GUI. via 662fe8cc957d8d4991bcb74f354b3b6dfab4ef4d

**Comment by mirh** [comment]
May I suggest ([again](https://github.com/RPCS3/rpcs3/pull/2885#issuecomment-318625190)) a "get in touch with kernel input maintainers" point?

> Add an analog to d-pad converter as requested by toccata10

Cannot this just be reworded with "allow binding axis to digital buttons"?

**Comment by toccata10** [comment]
I'm trying to address the 2nd (deadzones) with this #3519

**Comment by toccata10** [comment]
My #PR3551 should address the 4th point (analog to dpad inputs).

**Comment by Megamouse** [comment]
Last point can be checked

**Comment by pmandin** [comment]
Hello,

I think there is a problem in how pad_setttings_dialog.cpp and the evdev backend talk to each other via evdev_joystick_handler::GetNextButtonPress that prevent correct configuration:

Example with my Saitek dual analog P990 when trying to configure it:
GetNextButtonPress: 127: LZ+ (any button released)
GetNextButtonPress: 255: Top 2 (pressing button for L1)

Any attempt to configure a button fails, and are mapped to LZ+, because of the line (at end of function):
	if (pressed_button.first > 0)
		return callback(pressed_button.first, pressed_button.second, preview_values);

If I change it to

	if (pressed_button.first > 128)
		return callback(pressed_button.first, pressed_button.second, preview_values);

Any button is correctly detected when pressed

**Comment by Megamouse** [comment]
rumble can be checked

**Comment by Megamouse** [comment]
this can pretty much be closed. at least after profiles have been added

**Comment by mirh** [comment]
Sorry, I thought buttons pressure sensitivity was still missing?

**Comment by Megamouse** [comment]
?

**Comment by mirh** [comment]
The buttons?
The dualshock 3 X/O/△/◻ buttons?
They are pressure sensible from 0 to (iirc) 255

**Comment by Megamouse** [comment]
what does it have to do with this issue

**Comment by mirh** [comment]
> controller input improvements 

?

**Comment by Megamouse** [comment]
If the ds3 event isn't sending values below 255 I can't do anything about it

**Comment by mirh** [comment]
It is (except for what I said in the first comment)?

**Comment by Megamouse** [comment]
well then what are the button's event codes and types

**Comment by Megamouse** [comment]
for example pushing normal buttons on 360 controllers gives me an EV_KEY with value 1.
If the DS3 does the same I can't do anything.

**Comment by mirh** [comment]
Oh, I was wrong. Action buttons goes from default of -32767 to +32767 
OTOH digital pad (and R1 and L1, but I guess you might already know this) goes from 0 to 255. 

Being axis, of course, their event type is 3 (EV_ABS)

**Comment by Megamouse** [comment]
so what... X/O/△/◻ go from -32767 to +32767  on DS3 evdev?

**Comment by mirh** [comment]
Yes. 
Then, they are \*also\* digital buttons, as you can read on comments [here](https://github.com/torvalds/linux/blob/a687c5765b5ae19fe559e14615ddc87ebb46d409/drivers/hid/hid-sony.c#L76-L82).

**Comment by AniLeo** [comment]
Last two points have been completed as of the introduction of Input Profiles, closing this issue.
