### ISSUE TITLE
[Linux] Fedora package requirements documentation

### ISSUE THREAD

**Issue by duracellh** [RPCS3/rpcs3#3182]
Not sure if this is worth opening an issue for, but the main documentation (https://github.com/RPCS3/rpcs3/blob/master/README.md) lists Fedora needing:

> "Fedora: sudo dnf install cmake qt5-devel vulkan-devel libGLEW" 

You would think libGLEW would take care of it, but I at least seem to also need the **_glew-devel_** and **_glew_** packages (also sort of surprised libGLEW doesn't pull these in). They are in the default repos, don't need rpmfusion or anything.

If you don't have these packages, you will get the error:

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLEW_LIBRARY
    linked by target "rpcs3" in directory /home/nanashi/rpcs3/rpcs3
-- Configuring incomplete, errors occurred!

I am using GCC (7.1.1 20170622 (Red Hat 7.1.1-3)) on Fedora 26.

**Comment by hcorion** [comment]
Good catch, thanks!
