### ISSUE TITLE
Ni No Kuni Shadow Bug (Even with invalidate cache)

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#3188]
While turning Invalidate cache on in the GPU settings fixes the shadow/lighting bugs for the most part  occasionally you will run into an issue where a shadow will follow the camera around. It seems to only occur after playing the game for a little while and/or loading a new area. It's hard to explain how it looks with a picture so I included a short video with the log.
[results.zip](https://github.com/RPCS3/rpcs3/files/1213689/results.zip)

This bug exists in Vulkan and OpenGL it also isn't related to any zcull regressions as I have been testing those builds and noticed it there as well. I tried turning all of the GPU settings on/off and deleting the data folder but it still occurs.

How to reproduce:
Seems to occur 100% of the time when entering Ding Dong Well, I included a save file outside the door so you can reproduce this very easily.

**Comment by kd-11** [comment]
Its a game bug. I have a fix for this in the vertex_rewrite branch

**Comment by Asinin3** [comment]
I did notice this in the older vertex_rewrite branch but I will try the latest builds and report back.

**Comment by kd-11** [comment]
I only fixed the depth problems. This looks to be an unrelated bug to the other ones. If the shadows bug out it might be related to the root cause of the 'invalidate cache' option.

**Comment by Asinin3** [comment]
After some more testing, this happens with Invalidate cache on and off. However it seems to occur in every single area consistently with the option set to OFF whereas having it set to on makes it more randomly appear (depending on area) I guess it could still be happening with it set to ON in all areas but just not visible.

I suspect that Kd-11 is correct and that "Invalidate Cache Every Frame" isn't applying properly occasionally or in some areas.

**Comment by kd-11** [comment]
I'll need a renderdoc trace of this one to see what values the game is passing in to the depth clip range.

**Comment by Asinin3** [comment]
@kd-11 Here you go: https://my.mixtape.moe/jtsgjh.7z

**Comment by kd-11** [comment]
Just retry with the new PR build. I've disabled the depth range partially since the parameters passed by the game guarantee broken output.

**Comment by Asinin3** [comment]
@kd-11 Your latest PR fixed all of my issues with Ni No Kuni apart from the shadow bug, I'll post another renderdoc soon incase you need it.

The clipping, pop-in, black/white/invisible textures and a few other oddities are all gone. Well done!

**Comment by P1llus** [comment]
I can confirm this is still a issue. Using both OpenGL and Vulcan. I see someone mentioned that the following shadows only appear after a longer period of time, according to @Asinin3 on the 13th of August it also changes depending on your settings of invalidated cache.

Mine is set to ON, and it happens constantly from when you leave your house (30 sec into the game).

**Comment by Asinin3** [comment]
Fixed by #3618
