### ISSUE TITLE
High Threshold from Xinput

### ISSUE THREAD

**Issue by wandbrandon** [RPCS3/rpcs3#3192]
When Playing Persona 5, movement on the analog sticks is quite slow, as my character switches from running to walking at random times. Unfortunately, I cannot change the threshold options in Xinput, or I just don't know how to.

**Comment by RipleyTom** [comment]
config_xinput.yml has a pad squircling factor setting.
If you lower it, it will make diagonals closer to corner value(it basically makes the circle output of your pad more like a square, hence the name).
Generally people are happy with 4000 for persona 5.
Note that if you want to use 3rd party software to do this you can put pad squircling factor at 0 and it'll disable it.

**Comment by wandbrandon** [comment]
That did the trick, appreciate it.
