### ISSUE TITLE
Persona 5: Runtime_error thrown: Assertion failed!

### ISSUE THREAD

**Issue by Muramas** [RPCS3/rpcs3#3195]
In persona 5 on 5/4 in the evening after selling treasure and getting a call the game just froze randomly. It didn't seem like anything out of the norm was happening.

F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is FFFFFFFEh
(in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:275)

I don't even have a folder on my C:/ with the above name and I store RPCS3 on my F:/ drive.

I had to truncate the log because it was huge...Could I advise that RPCS3 creates new log files after reaching a certain size or make it so certain things are not as verbose? Though because of the size of how large these logs are it would be unwise to to make constant log files (1gb from an evening of playing) 
[RPCS3logs.zip](https://github.com/RPCS3/rpcs3/files/1217032/RPCS3logs.zip)

Also I cant seem to get my tty logs to work...

**Comment by kd-11** [comment]
Should be fixed in master. You ran out of VRAM due to a probable memory leak  - or you have too little VRAM to begin with. I'm closing this - reopen if it happens again.
