### ISSUE TITLE
BLJS10223-[Super Robot Taisen OG Saga Masou Kishin III - Pride of Justice] MEM: Access violation reading location 0x1c

### ISSUE THREAD

**Issue by keith5544** [RPCS3/rpcs3#3198]
MEM: Access violation reading location 0x1c
·tried with latest build v0.0.3-5646 Alpha [2017-08-10] with interpreter and recompiler

this error occurs when im using the ultimates moves from most of not all of the masou kishin

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1217653/RPCS3.zip)

Windows 7
![image](https://user-images.githubusercontent.com/30905924/29210349-bbc7914a-7ec5-11e7-974a-5da3c11ce628.png)

![image](https://user-images.githubusercontent.com/30905924/29210336-afe75806-7ec5-11e7-8b0f-a89423b1ec2f.png)

**Comment by AniLeo** [comment]
No proper test was provided after asking (the provided test is using manual firmware mode), closing the issue as invalid due to the lack of information.

Feel free to open a new one with a proper report.
