### ISSUE TITLE
VK : FPS suddenly dropping, possible memory leak

### ISSUE THREAD

**Issue by GeniusMage** [RPCS3/rpcs3#3201]
**Games affected:** 
Tales of Vesperia
Tales of Graces f

SInce #3083, those games have severe FPS drops (down to 0.5, usually stays between 0.5 and 5 afterwards). It may also freeze.
This only happens on Vulkan.
In Tales of Vesperia, RAM usage is also going through the roof (but not in Tales of Graces)
![bandicam 2017-08-11 17-12-56-255](https://user-images.githubusercontent.com/27543170/29219878-a3905da2-7eb9-11e7-91aa-3a44f3664529.png)
_A few seconds later..._
![bandicam 2017-08-11 17-13-01-128](https://user-images.githubusercontent.com/27543170/29219959-e3c65160-7eb9-11e7-9918-8a491399037c.png)
![capture](https://user-images.githubusercontent.com/27543170/29219980-f27efef0-7eb9-11e7-990d-e0740a98b71b.PNG)

![bandicam 2017-08-11 17-27-19-546](https://user-images.githubusercontent.com/27543170/29220364-1d42763e-7ebb-11e7-868e-ce83472de38a.png)
![bandicam 2017-08-11 17-27-34-706](https://user-images.githubusercontent.com/27543170/29220394-334da5e8-7ebb-11e7-8dee-46195a2aeca2.png)

[TOV log](https://github.com/RPCS3/rpcs3/files/1218300/RPCS3.zip)
[TOGf log](https://github.com/RPCS3/rpcs3/files/1218338/RPCS3.zip)

**Comment by hcorion** [comment]
This should be fixed with the latest WIP build, please re-test.

**Comment by GeniusMage** [comment]
I'm afraid it's not fixed.

**Comment by kd-11** [comment]
Run GPU-Z and check where the leaking memory is coming from. Its important to know if its coming from the dedicated VRAM or system memory

**Comment by SakataGintokiYT** [comment]
@kd-11 
**GTX 660 2GB**
**Build: Master**  
![bez tytulu](https://user-images.githubusercontent.com/13681488/29363963-401d3c0e-8292-11e7-838a-9fb7d26b5a29.png)

**Comment by kd-11** [comment]
That version of GPU-Z isnt showing the difference between device-local and host-local memory. Or maybe GTX 660 doesnt have that?
![image](https://user-images.githubusercontent.com/15904127/29364556-866f8770-829c-11e7-856c-f52f60fd6d42.png)

**Comment by SakataGintokiYT** [comment]
@kd-11 with latest 2.2.0 only show ''Memory Used''

**Comment by GeniusMage** [comment]
End of first scene (at this point, RPCS3 eats up 6GB of memory according to Windows)
![bandicam 2017-08-16 15-13-26-154](https://user-images.githubusercontent.com/27543170/29365434-47cef14a-8297-11e7-869b-6efae6388c8d.png)
End of second scene (RAM was flushed at the beginning of this one, then went up again, maxed at 4.3GB)
![bandicam 2017-08-16 15-23-02-988](https://user-images.githubusercontent.com/27543170/29365457-6027cfd2-8297-11e7-894c-38596775ffc9.png)
Memory usage (Dynamic) slowly goes up the whole time

**Comment by Asinin3** [comment]
After a bit of google-fu it seems like GPU-Z only reports the memory usage as dynamic or dedicated with certain cards. It's not an option in the settings either quite strange.

**Comment by SakataGintokiYT** [comment]
@kd-11 
Gtx960m
![bez tytulu](https://user-images.githubusercontent.com/13681488/29366187-9f857416-8299-11e7-976a-317cf13a726d.jpg)

**Comment by zminhquanz** [comment]
![image](https://user-images.githubusercontent.com/11285640/29394575-789ad39a-8335-11e7-96f1-658cceb6beff.png)
I don't know it's a bug on rpcs3 or my PC , but in recent version build , Catherine on my PC specs drop FPS , before it stable 30 FPS when i set preffered SPU threads to 1 , and now , it dropped

**Comment by zminhquanz** [comment]
![image](https://user-images.githubusercontent.com/11285640/29395282-f16f4676-8339-11e7-8e4d-7cae848d6cc5.png)

Same to you , drop FPS in game , i think it's vulkan api or SPU bugs ( I enable SPU loop detection , low spu thread priority and preferred SPU threads set to 1 )

**Comment by GeniusMage** [comment]
Texture uploading time almost reaching 2 seconds.
![capture0](https://user-images.githubusercontent.com/27543170/29407116-8cfc7506-8343-11e7-8f10-6fcb9b7fc271.PNG)

**Comment by kd-11** [comment]
Its leaking texture memory which is why VRAM usage is growing. It'll  get fixed.

**Comment by zminhquanz** [comment]
@kd-11 how about bug on my PC ( picture in above ) ?

**Comment by Asinin3** [comment]
@zminhquanz If you're issue doesn't have anything to do with a memory leak then you shouldn't be posting in an issue about memory leaks... if it IS caused by the memory leaks then yes this will solve it. You didn't post any information about your memory usage so it wasn't especially helpful.

**Comment by zminhquanz** [comment]
@Asinin3 No , never , do you understand for my post , it's not shader cache problem , got it , it's a spu bug or memory leak

**Comment by mchtt** [comment]
@zminhquanz In any case, please submit a log, at worst it will shorten the time for answers about your questions, at best it will help devs improving the emulator.

**Comment by kd-11** [comment]
Finally got around to testing this and it consumes all my vram within seconds. A fix should be incoming soon.

**Comment by kd-11** [comment]
@GeniusMage Retest with https://github.com/RPCS3/rpcs3/issues/3201

**Comment by GeniusMage** [comment]
Confirmed: the slowdowns in both games and the memory leak are fixed. Freezes still happen, but that probably belong in #3243.
Closing this. Good job boss.
