### ISSUE TITLE
Ni No Kuni Completely Freezes With Vulkan and Null Renderer

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#3208]
Ni No Kuni completely freezes (not crash) for me in 0.0.3-5656 and even much earlier builds before zcull (however the graphics were so glitchy with vulkan that I thought that was the cause and never reported this problem. The freeze happens around 1-20seconds after getting in-game, I do seem to be the odd one out because others seem to be able to play it just fine with vulkan e.g the recent reznoire video.
[RPCS3_Ni_No_Kuni_Vulkan_Freeze2.zip](https://github.com/RPCS3/rpcs3/files/1219642/RPCS3_Ni_No_Kuni_Vulkan_Freeze2.zip)

I have created many fresh installs of RPCS3 and have had this issue in all of them, and I've also tried a physical and PSN version of the game (ripped using Rebug CFW).

Last two lines when it freezes:
F {rsx::thread} class std::runtime_error thrown: Unknown wrap mode 0xf
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:588)

And here's the error from another run:
E {rsx::thread} RSX: Invalid RSX method 0x2004 (arg=0x0)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)

For future reference Kd-11 said: "Freezing with corrupt heap might be just from increased framerate."
I did try setting the FPS limiter to 30 however and still have the same problem.

I am using windows 10 (so it shouldn't be related to the win7 hang in DeS)
CPU: R7 1700 OCed @ 3.9ghz
GPU: GTX 1080ti - tried rolling back to older drivers

Edit: still happens in latest master (5705)

**Comment by kd-11** [comment]
This issue is tracked in a metabug here https://github.com/RPCS3/rpcs3/issues/2359. Its an issue affecting many games so I'll close this ticket.
