### ISSUE TITLE
Castlevania Lord of Shadow 2 [NPEB01434] hangs after selecting dificulty

### ISSUE THREAD

**Issue by guruemulation** [RPCS3/rpcs3#3209]
OS: win10 home version 10.0.15063
RPCS3 v0.0.3-3-e9fc411 Alpha
Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz | 8 Threads | 7.90 GiB RAM | AVX | TSX
NVIDIA GeForce GTX 950M 2GB

Attract mode is working fine with some gfx issues at a good framerate around 25 - 30fps
After selecting the difficulty mode the game hangs at the same point
tested with
- ogl
- ogl llvm
- vulkan
- vulkan llvm

![castlevania2-001](https://user-images.githubusercontent.com/30950311/29239611-0aa13680-7f53-11e7-8a38-430a180dee44.png)
![castlevania2-002](https://user-images.githubusercontent.com/30950311/29239614-0aa80186-7f53-11e7-854e-2e252c6e8732.png)
![castlevania2-004](https://user-images.githubusercontent.com/30950311/29239612-0aa426ec-7f53-11e7-8eb9-58d240c9dbdd.png)
![castlevania2-005](https://user-images.githubusercontent.com/30950311/29239613-0aa5f846-7f53-11e7-8f40-c2eaf2f47ab6.png)
[RPCS3 log output.txt](https://github.com/RPCS3/rpcs3/files/1219643/RPCS3.log.output.txt)
[RPCS3 log vulkan.zip](https://github.com/RPCS3/rpcs3/files/1219644/RPCS3.log.vulkan.zip)
[RPCS3 log vulkan llvm.zip](https://github.com/RPCS3/rpcs3/files/1219645/RPCS3.log.vulkan.llvm.zip)
[RPCS3 log ogl.zip](https://github.com/RPCS3/rpcs3/files/1219647/RPCS3.log.ogl.zip)
[RPCS3 log ogl llvm.zip](https://github.com/RPCS3/rpcs3/files/1219648/RPCS3.log.ogl.llvm.zip)

**Comment by Asinin3** [comment]
This game was only listed as Intro (e.g you can't get in-game) in the compatibility list I don't think you need to make a report about this.

**Comment by guruemulation** [comment]
Ah ok, didn't see it in the compatibility list under NPEB01434
thanks for the info.

**Comment by AniLeo** [comment]
Please report compatibility in the forums, unless you know exactly what's making it hang.
