### ISSUE TITLE
Persona 5(?) fps suddenly went down a lot. 

### ISSUE THREAD

**Issue by Kompas9** [RPCS3/rpcs3#3210]
![image](https://user-images.githubusercontent.com/26677881/29240265-27ca1c60-7f6a-11e7-9a2c-934e5498567b.png)

Game windows shows 28-30fps, but game (and videos), now slowdown/shutters like it's running 2-3 fps at most
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1219716/RPCS3.zip)

Strangely this now happens with even older builds, that worked perfectly fine, no hardware or software changes were made. Can't find any other problems with system too, everything else runs without his, also  none CPU or GPU intensive stuff that I could find running in background.

**Comment by AniLeo** [comment]
This is not an issue, that's video rendering by the SPU and the FPS counter is not accurate

**Comment by Kompas9** [comment]
4690k, done around 30h of game, with no bigger problems (after GCM implementation), yet now it's barely working, the only thing I can assume Windows update did something, cuz I can't find any leads to the problem....

**Comment by bjakja** [comment]
Which are working builds? I have slowdown on most of games from sunday, and Persona 5 also works bad on new builds.

**Comment by Muramas** [comment]
Update graphics driver? run malwarebytes and scan for malware?

What is your CPU look like in the task manager

**Comment by bjakja** [comment]
I mean sunday builds, builds from saturday works as good. It is caused using yield instead sleep_for. Yield function makes constant 100% use of one core. On 4 cores it slows on "powerful" games.

**Comment by Asinin3** [comment]
You can disable Invalidate cache every frame for Persona 5 It's only needed for a few games with broken shadows e.g Ni No Kuni it will help performance a little. Also try setting CPU priority it task manager to high. I don't really think people should be making issues about performance loss just yet we are still in heavy development and things are changing all the time. Also the FPS counter is known not to be completely accurate.

**Comment by AniLeo** [comment]
Why is frame limiter on? Waste of resources when the game already limits itself.

This is not a RPCS3 issue, I've tested it on latest build and videos on Persona 5 play at full speed on 6700HQ.

**Comment by GeraltDeRivia** [comment]
I had the same problem, in the last build the game was working fine. I hope someone can help.

PC Specs: 
i7 4790k OC 4.7 ghz
ASUS GTX 1080

**Comment by Asinin3** [comment]
@GeraltDeRivia This isn't the place to ask for support, it's for reporting an issue you found I can help on discord #help channel if you log in.

**Comment by Kompas9** [comment]
With newest [#3200](https://github.com/RPCS3/rpcs3/pull/3200) even thou game videos still playing poorly, after setting SPU to 1 (from 2 in my case), everything looks like runs better, except video that one can describe as "meh", compared to older versions.

@AniLeo and @Asinin3 Thanks for information.

**Comment by kensos789** [comment]
YES i have the some problem.
Since i use 2017-08 適用於 x64 系統 Windows 10 Version 1703 的累積更新 (KB4034674) and 2017-07 適用於 x64 系統 Windows 10 Version 1703 的累積更新 (KB4032188).
The problem is coming.@@

**Comment by hcorion** [comment]
A user on discord has reported that updating to Windows 10 Insiders Build 16251 fixed the issue for him.

**Comment by GeraltDeRivia** [comment]
After updating to Windows 10 Insiders Build 16251 the issue was fixed for 4 days but today started again, I update again to Windows 10 Insider Preview 16275.1000 (rs3_release) the issue was fixed again but only for a few minutes something is doing W10 whit RPCS3 also I noticed RPCS3 now is only using 50-60% of the CPU when yesterday was using 80-90%.

**Comment by 1whatleytay** [comment]
Just got the same issue. Super weird. I'll try some updates, but it's sad to see this problem coming back. Good to know it's not an issue with RPCS3 though!
