### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by rzarectha** [RPCS3/rpcs3#3212]
This is my first time reporting a bug so please forgive me if my report is not written properly or it's irrelevant.

System specs: Desktop
CPU: FX 8350
GPU: GTX 770 4GB
OS: Windows 10 Pro x64

Repro:
1. Installed rpcs3
2. Installed firmware
3. Installed Demon Souls
-At this point the game booted correctly, however, the in-game screen was black. I then modified the video settings to:
4 PPU LLVM Recompiler 
SPU ASMJIT Recompiler 
SPU loop detection: On
Preferred SPU Threads: 4
SPU delay penalty: 0 
OpenGL + Write Color Buffers + Invalidate cache every frame
5. On rpcs3 reboot, if I try to access the application settings i get the below error:
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xE06D7363.
Exception address: 00007ffdcef19e08.
ExceptionInformation[0x0]: 0000000019930520.
ExceptionInformation[0x1]: 0000000003932120.
ExceptionInformation[0x2]: 00000000018830b8.
ExceptionInformation[0x3]: 0000000000010000.
Instruction address: 00007ffdcef19e08.
Function address: 00007ffdcef19da0 (base+0x69da0).
Module name: 'KERNELBASE.dll'.
Module base: 00007ffdceeb0000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

.log reads the following

RPCS3 v0.0.3-6-dac3a31 Alpha
·F 0:00:00.000000 CFG: class YAML::ParserException thrown: yaml-cpp: error at line 13, column 43: illegal map value
·W 0:00:02.441311 Could not load image from path E:/Games/rpcs3-v0.0.3-2017-08-12-dac3a318_win64/dev_hdd0/game/NPEB01202/PS3_GAME/ICON0.PNG

If I try to boot the title, the console gives two errors:

F CFG: class YAML::ParserException thrown: yaml-cpp: error at line 13, column 43: illegal map value
and
F {PPU[0x1000005] Thread (HighGraphics) [0x01d76c70]} MEM: Access violation reading location 0x0

needless to say, the title does not boot properly.

**Comment by AniLeo** [comment]
Not an issue- user error, you broke YAML syntax.

Use a proper editor like Notepad++ to edit config.yml

**Comment by Asinin3** [comment]
I should probably just add that you can delete config.yml and rpcs3 will create another.

**Comment by rzarectha** [comment]
Thanks a lot for your answers, and once again, please forgive me for creating this issue for my mistake.
I am not experienced with emulators and I assure you my intentions were good.

Have a very good day!
