### ISSUE TITLE
RPCS3.log too big

### ISSUE THREAD

**Issue by JacobAL** [RPCS3/rpcs3#3215]
Just played Kingdom Hearts for about 5 hours and went to check the log to report some errors and found that it was 1.33GB in size. 
Could you possibly make it so that the log can be limited to a certain size?

**Comment by RipleyTom** [comment]
If you don't want any log you can set the last line of config.yml to:
Log: {"": Fatal}

**Comment by JacobAL** [comment]
The problem is that I want a log so I can take the details of errors to report, I just don't want it to get massive.

**Comment by AniLeo** [comment]
You either have a log or not. You can also reduce level to Error instead.
You can't stop the game from calling stuff that has logging in place.

**Comment by JacobAL** [comment]
So there's no way to implement a system where the log will just delete its first lines once the .log file gets too large?
I'll turn it off for now. Thanks for the help.

**Comment by Asinin3** [comment]
The best solution currently would be to delete the log file (or re-name it) when booting a new game up so each game has a seperate log instead of having the full log of details from when the emulator was first opened. If you zip the log file it also get's tiny (e.g 1gb > 20mb) so it's not that big of a deal.

**Comment by JacobAL** [comment]
If I have a long play session though, It's just accumulating a hell of a lot of data. Sure, I can zip it after the fact, but it could get massive if I played all day.

**Comment by JacobAL** [comment]
Also, setting the last line to "Log: {"": Fatal}" doesn't seem to be working. It's still creating the log.

**Comment by RipleyTom** [comment]
My bad, I had seen neko recommend it for a specific issue and I thought it set all logging levels to Fatal but it's just for blocking error reporting(if you have lwmutex spam).
You can try this line:
`Log: {"": Fatal, cellDaisy: Fatal, cellDmux: Fatal, cellFiber: Fatal, cellFont: Fatal, cellFontFT: Fatal, cellFs: Fatal, cellGame: Fatal, cellGameExec: Fatal, cellGcmSys: Fatal, cellGem: Fatal, cellGifDec: Fatal, cellHttp: Fatal, cellHttpUtil: Fatal, cellImeJp: Fatal, cellJpgDec: Fatal, cellJpgEnc: Fatal, cellKey2char: Fatal, cellL10n: Fatal, cellLibprof: Fatal, cellMic: Fatal, cellMusic: Fatal, cellMusicDecode: Fatal, cellMusicExport: Fatal, cellNetCtl: Fatal, cellOskDialog: Fatal, cellOvis: Fatal, cellPamf: Fatal, cellPhotoDecode: Fatal, cellScreenshot: Fatal, cellSearch: Fatal, cellSheap: Fatal, cellSpudll: Fatal, cellSpurs: Fatal, cellSpursJq: Fatal, cellSsl: Fatal, cellSubdisplay: Fatal, cellSync: Fatal, cellSync2: Fatal, cellSysconf: Fatal, cellSysmodule: Fatal, cellSysutil: Fatal, cellSysutilAp: Fatal, libmixer: Fatal, libnet: Fatal, libsnd3: Fatal, libsynth2: Fatal, sceAppMgr: Fatal, sceAppUtil: Fatal, sceAudio: Fatal, sceAudioIn: Fatal, sceAudiodec: Fatal, sceAudioenc: Fatal, sceCamera: Fatal, sceCodecEngine: Fatal, sceCommonDialog: Fatal, sceCtrl: Fatal, cellSysutilAvc: Fatal, cellSysutilAvc2: Fatal, cellSysutilMisc: Fatal, cellSysutilNpEula: Fatal, cellUsbPspcm: Fatal, cellUsbd: Fatal, cellUserInfo: Fatal, cellVdec: Fatal, cellVideoExport: Fatal, cellVideoUpload: Fatal, cellVoice: Fatal, cellVpost: Fatal, cell_FreeType2: Fatal, libmedi: Fatal, cellPhotoExport: Fatal, cellPhotoImportUtil: Fatal, cellPngDec: Fatal, cellPngEnc: Fatal, cellPrint: Fatal, cellRec: Fatal, cellRemotePlay: Fatal, cellResc: Fatal, cellRtc: Fatal, cellRtcAlarm: Fatal, cellRudp: Fatal, cellSail: Fatal, cellSailRec: Fatal, cellSaveData: Fatal, sceDbg: Fatal, sceDeci4p: Fatal, sceDeflt: Fatal, sceDisplay: Fatal, sceFiber: Fatal, sceFios: Fatal, sceFpu: Fatal, sceGxm: Fatal, sceHttp: Fatal, sceIme: Fatal, sceJpeg: Fatal, sceJpegEnc: Fatal, sceLibKernel: Fatal, sceLibXml: Fatal, cellCrossController: Fatal, cellCelpEnc: Fatal, cellCelp8Enc: Fatal, cellCamera: Fatal, cellBGDL: Fatal, cellAvconfExt: Fatal, cellAudio: Fatal, cellAtracMulti: Fatal, cellAtrac: Fatal, cellAdec: Fatal, sceLibc: Fatal, sceLibm: Fatal, sceLibstdcxx: Fatal, sceLiveArea: Fatal, sceLocation: Fatal, sceMd5: Fatal, sceMotion: Fatal, sceMt19937: Fatal, sceNet: Fatal, sceNetCtl: Fatal, sceNgs: Fatal, sceNp: Fatal, sceNp2: Fatal, sceNpBasic: Fatal, sceNpClans: Fatal, sceNpCommerce2: Fatal, sceNpCommon: Fatal, sceNpManager: Fatal, sceNpMatching: Fatal, sceNpScore: Fatal, sceNpSns: Fatal, sceNpTrophy: Fatal, sceNpTus: Fatal, sceNpUtil: Fatal, sceNpUtility: Fatal, scePerf: Fatal, scePgf: Fatal, scePhotoExport: Fatal, sys_lwmutex: Fatal, sys_memory: Fatal, sys_mmapper: Fatal, sys_mutex: Fatal, sys_ppu_thread: Fatal, sys_process: Fatal, sys_prx: Fatal, sys_rsx: Fatal, sys_rwlock: Fatal, sys_semaphore: Fatal, sys_spu: Fatal, sys_time: Fatal, sys_timer: Fatal, sys_Fatal: Fatal, sys_tty: Fatal, sys_vm: Fatal, sceRazorCapture: Fatal, sceRtc: Fatal, sceSas: Fatal, sceScreenShot: Fatal, sceSfmt: Fatal, sceSha: Fatal, sceSqlite: Fatal, sceSsl: Fatal, sceSulpha: Fatal, sceSysmodule: Fatal, sceSystemGesture: Fatal, sceTouch: Fatal, sceUlt: Fatal, sceVideodec: Fatal, sceVoice: Fatal, sceVoiceQoS: Fatal, sysPrxForUser: Fatal, sys_cond: Fatal, sys_dbg: Fatal, sys_event: Fatal, sys_event_flag: Fatal, sys_fs: Fatal, sys_gamepad: Fatal, sys_interrupt: Fatal, sys_io: Fatal, sys_libc: Fatal, sys_lv2dbg: Fatal, sys_lwcond: Fatal}`

**Comment by PeterMcteague** [comment]
I do wonder if cellAudio: cellAudioGetPortConfig(portNum=0, portConfig=*0xd0099810) needs to be in the log quite as much as it is. 

I ran Persona 5 for 48 seconds , on simply the first screen and notepad++ counts 9000 counts of that line.

**Comment by AniLeo** [comment]
That issue has been there since ever. Very likely inaccuracies in HLE implementation of cellAudio, one needs to debug and check if the game calls it that much on real hardware.

**Comment by JacobAL** [comment]
@RipleyTom 
That's still making a log. Maybe if I just set the file to read only?

**Comment by kd-11** [comment]
You have to setthose options in whichever config file the game is using, which means if you have a custom config you need to edit that as well. It will access the log file but maybe only write a line or two at boot.

**Comment by JacobAL** [comment]
I'll double check how much it's making. I have set the config in each specific game config file.

**Comment by JacobAL** [comment]
Turning off the log works fine, but causes KH1.5 to crash on trying to start the game.
#3269 has more details.

**Comment by AniLeo** [comment]
Closing as log size was limited recently. Plus it also compresses itself after closing RPCS3.
