### ISSUE TITLE
[BLUS30443] Demon's Souls crash during/after cutscenes

### ISSUE THREAD

**Issue by C0rn3j** [RPCS3/rpcs3#3218]
i7-4790k, 1080 Ti, nvidia 384.59, 32GB RAM, Arch Linux.

RPCS3 v0.0.3-5630-a909bd6ed Alpha - launched with PULSE_LATENCY_MSEC=30.

Using OpenGL backend. Vulkan crashes too, seemingly way more often but at random times. But that seems to be a known issue already.

I have deleted the whole RPCS3 folder a few days ago, so it is not likely an issue from an old build misconfig.

It seems to only crash at the beggining or end of cutscenes. 

First crash in the game was when I finished the tutorial, cutscene played, I entered Nexus and as soon as I got control back and turned around the game crashed.

Another crash that I recall was after defeating the first boss, teleporting to Nexus and I believe soon after the cutscene ended and I got control back it crashed again.

It crashes in a way that whole RPCS3 segfaults.

Using the AUR package of rpcs3.

**Comment by PeterMcteague** [comment]
Do you have a log file? Might be helpful.

**Comment by C0rn3j** [comment]
My savefile got corrupted midgame - now whenever I Try to load it it will just load endlessly.

I started a new game, got to the tutorial boss and the moment it meant to hit me my game crashed. Here's a log.

https://cloud.c0rn3j.com/s/ocRafAKacDN3doe

And here is the broken savefile in case it's RPCS3 fault that it wont load and not just corrupted save.

https://cloud.c0rn3j.com/s/ZteXATlL7WnGnLT

**Comment by Asinin3** [comment]
Save backups are in the to-do list but it's really a shame that the souls games rely on one save with no backup... I do believe RPCS3 has been known to corrupt save files under certain circumstances but I'm not sure if they can be recovered easily although I do remember something about ssshadow saying if it was only the meta-data that was corrupted it may be possible to fix.

**Comment by kd-11** [comment]
Its not possible to eliminate other factors if running AUR package, so you'll have to build from source or use appimage then run the emulator under gdb and obtain a stacktrace of the segfault. Thats the only way we can determine why things crash for you.
As for save files, yea, crashes during saving will corrupt your save. Backup your saves often to avoid losing too much progress.

**Comment by C0rn3j** [comment]
@kd-11 Okay - I'm up for that but I need to explain a few things about compiling and gdb.

If I follow the instructions and build from source on Linux - how do I then rebuild it when a new commit happens?

How do I run stuff under gdb and how do I obtain the stacktrace for you?

**Comment by kd-11** [comment]
Its better if you could ask on discord since it is a fairly involved process, especially on linux. Ask https://discord.me/RPCS3, try the help channel or development channel. Someone running arch might be able to help.
An easy way is to download the appimage from the rpcs3.net website, then run under gdb via
`gdb ./rpcs3`. There is alot more required to debug since segfaults should be passed to the program first anyway, but thats the basic rundown.

**Comment by C0rn3j** [comment]
So far I haven't been able to reproduce this with a git-built RPCS3 as opposed to AUR built, where it was 100% guaranteed crash.

**Comment by C0rn3j** [comment]
This was either fault of the AUR package, fixed in new releases or very likely the same bug as here

https://github.com/RPCS3/rpcs3/issues/3266

Closing this issue to avoid duplicates/old bugs, and because the newer bug report actually has a log.
