### ISSUE TITLE
Skate 1 problem

### ISSUE THREAD

**Issue by ALexPDo** [RPCS3/rpcs3#3224]
Hi,I saw skate 1 thats is working ingame,and i tried myself but i get this error:F {PPU[0x1000006] Thread (rwfilesys_sk8) [0x00a4f180]} class std::runtime_error thrown: Verification failed (e=0x2): 
(in file C:\rpcs3\rpcs3\Emu\Cell\lv2\sys_cond.cpp:279),in intro or when I try to load freeskate it freezes and I get that error,while using vulkan
Please help me!

**Comment by Asinin3** [comment]
This game is in-game with certain settings/build but if you want help close this and ask me in Discord in the #help channel. This isn't the place to ask for assistance https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md

Skate 1 is only playable using certain builds (not yet merged) so this error report isn't helpful.

**Comment by ALexPDo** [comment]
how do i Ask you?(I know this sounds so stupid but pls help me)

**Comment by Asinin3** [comment]
https://discord.me/RPCS3 on there.
