### ISSUE TITLE
Official AppVeyor link shows Experimental Build Warning

### ISSUE THREAD

**Issue by darktohka** [RPCS3/rpcs3#3225]
Downloading the latest release from AppVeyor (using the link from https://rpcs3.net/download) will result in an Experimental Build Warning being shown every time the emulator is started.

https://i.imgur.com/pnsuAxm.png

This is because, even though the build is being done on master, the branch that's being built on AppVeyor is not master, rather the pull request's temporary branch.

This is rather complicated, as non-merged pull requests also start out on the master branch, and AppVeyor builds them just the same: example; https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-5693 is an open pull request (not merged), and it still has a Build origin of "RPCS3/rpcs3/master/#3223".

**Comment by Nekotekina** [comment]
Sorry about this, I hope it'll be fixed soon.

**Comment by AniLeo** [comment]
Fixed. https://rpcs3.net/download will only link "branch" builds (the ones that are built after the pull request is master) now. 

Builds history list links latest pull request build if there's no "branch" build available still, but I'll get to it too when I have the time.
