### ISSUE TITLE
about a sys_mmapper issue

### ISSUE THREAD

**Issue by believer7788** [RPCS3/rpcs3#3229]
Thanks Dev Team.
OS: Windows 10 64bits  1703 15063.540
CPU: i7 4770k @3.5GHz no oc
GPU: Nvidia 980Ti 6GB 385.28
RAM: 24GB
I noticed that many game (Ridge Racer Unbounded NPEB01086,Gran Turismo5 BCAS20298,Gran Turismo6 NPEA00502 )and more,sys_mmapper A problem Causing the game to fail.

Gran Turismo5 BCAS20298
RPCS3 v0.0.3-3-d8c449a Alpha
Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz | 8 Threads | 23.94 GiB RAM | AVX
S LDR: Boot from gamelist per doubleclick: done
U {PPU[0x1000000] Thread (main_thread) [0x01a490e4]} HLE TODO: Unimplemented syscall syscall_462 -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x01a58e64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x01a590bc]} sys_prx TODO: _sys_prx_register_library(library=*0x1a5b6a0)
S {PPU[0x1000000] Thread (main_thread) [0x01a599ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x01a60d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x01a5a4d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x01a5a4d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x01a5a4d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x01a5961c]} sys_prx TODO: _sys_prx_register_module()
E {PPU[0x1000000] Thread (main_thread) [0x00c0aa00]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0x1020a, alignment=0x10000000, alloc_addr=*0xd0010920)
E {PPU[0x1000000] Thread (main_thread) [0x00c0aa00]} sys_mmapper: sys_mmapper_allocate_address(size=0x20000000, flags=0x20f, alignment=0x10000000, alloc_addr=*0xd0010910)
E {PPU[0x1000000] Thread (main_thread) [0x00c0aa00]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0x208, alignment=0x10000000, alloc_addr=*0xd0010700)
U {PPU[0x1000000] Thread (main_thread) [0x00c058ec]} sys_mmapper TODO: sys_mmapper_enable_page_fault_notification(addr=0x80000000, eq=0x8d023100)
F {PPU[0x1000000] Thread (main_thread) [0x00bea11c]} MEM: Access violation writing location 0x80000000

Gran Turismo6 NPEA00502
RPCS3 v0.0.3-3-d8c449a Alpha
Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz | 8 Threads | 23.94 GiB RAM | AVX
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2-EC520E2D5FB058EC-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2-liblv2.sprx-1DA050AFB1619383-haswell.obj
U {PPU[0x1000000] Thread (main_thread) [0x0005d0e4]} HLE TODO: Unimplemented syscall syscall_462 -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x0006ce64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x0006d0bc]} sys_prx TODO: _sys_prx_register_library(library=*0x6f6a0)
S {PPU[0x1000000] Thread (main_thread) [0x0006d9ac]} PPU: LLVM: Loaded module v2-libsysmodule.sprx-09F72D494851FEC4-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x0006d9ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00078d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x0006e4d0]} PPU: LLVM: Loaded module v2-libgcm_sys.sprx-92BB3C6B43076AD9-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x0006e4d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0006e4d0]} PPU: LLVM: Loaded module v2-libsre.sprx-88954A551E4344B8-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x0006e4d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0006e4d0]} PPU: LLVM: Loaded module v2-libfs.sprx-BB8655E4C5C49381-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x0006e4d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0006d61c]} sys_prx TODO: _sys_prx_register_module()
E {PPU[0x1000000] Thread (main_thread) [0x0001ef4c]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0x1020a, alignment=0x10000000, alloc_addr=*0xd0010920)
S LDR: Boot from gamelist per doubleclick: done
F {PPU[0x1000000] Thread (main_thread) [0x0001ef50]} class std::runtime_error thrown: Unregistered PPU function

Ridge Racer Unbounded NPEB01086
RPCS3 v0.0.3-3-d8c449a Alpha
Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz | 8 Threads | 23.94 GiB RAM | AVX
S LDR: Boot from gamelist per doubleclick: done
U {PPU[0x1000000] Thread (main_thread) [0x014060e4]} HLE TODO: Unimplemented syscall syscall_462 -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x01415e64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x014160bc]} sys_prx TODO: _sys_prx_register_library(library=*0x14186a0)
S {PPU[0x1000000] Thread (main_thread) [0x014169ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0141dd8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x014174d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014174d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014174d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0141661c]} sys_prx TODO: _sys_prx_register_module()
E {PPU[0x1000000] Thread (main_thread) [0x0140b4ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x0140b4ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x007fbce4]} sys_mmapper: sys_mmapper_allocate_address(size=0x20000000, flags=0x20f, alignment=0x10000000, alloc_addr=*0x1072338)
U {PPU[0x1000000] Thread (main_thread) [0x00f882d8]} sceNp TODO: sceNpManagerGetChatRestrictionFlag(isRestricted=*0xd0100504)
F {PPU[0x1000002] Thread (TransferManager) [0x00f89698]} MEM: Access violation reading location 0x0

There are a lot more
I know sys_mmapper ps3 RAM is used to solve the lib, a lot of games using memory mapping.
Thanks again

**Comment by AniLeo** [comment]
There's no actual information for the issue here, just random output. 

Please read the guidelines. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
