### ISSUE TITLE
The Last Of Us tested

### ISSUE THREAD

**Issue by Arth19** [RPCS3/rpcs3#3230]
U {PPU[0x1000009] Thread (Data) [0x00e49a78]} libnet TODO: sys_net_if_ctl
U {PPU[0x1000009] Thread (Data) [0x00a0f0a8]} libnet TODO: gethostbyname
E {PPU[0x1000009] Thread (Data) [0x00e49a78]} libnet: shutdown(): non existent socket cannot be shutdown

**Comment by AniLeo** [comment]
Troll? 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
