### ISSUE TITLE
[BLUS30178] Armored Core for Answer - game freezes after pressing start.

### ISSUE THREAD

**Issue by tridbee** [RPCS3/rpcs3#3231]
Upon pressing start on the main screen, the game freezes. Here's the log after it stopped.

`E {PPU[0x1000024] Thread (InstallDiskMount) [0x01142c50]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLUS30187”, errDialog=0x0, funcStat=*0x12c4fe8, container=4294967295)`
`U {PPU[0x1000024] Thread (InstallDiskMount) [0x01143b70]} libnet TODO: sys_net_free_thread_context(tid=0, flags=1)`
`E {PPU[0x1000000] Thread (main_thread) [0x00e4337c]} 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH`
`E {PPU[0x1000025] Thread (GameDataInstaller) [0x01142c50]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLUS30187”, errDialog=0x0, funcStat=*0x12c4fe8, container=4294967295)`
`U {PPU[0x1000025] Thread (GameDataInstaller) [0x01143b70]} libnet TODO: sys_net_free_thread_context(tid=0, flags=1)`
`E {PPU[0x1000000] Thread (main_thread) [0x00e4337c]} 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH`
`E {PPU[0x1000000] Thread (main_thread) [0x011427b0]} 'cellFsStat' failed with 0x8001003a : CELL_ENOTMOUNTED`
`E {PPU[0x1000000] Thread (main_thread) [0x011427b0]} 'cellFsStat' failed with 0x8001003a : CELL_ENOTMOUNTED`
`E {PPU[0x1000000] Thread (main_thread) [0x011427b0]} sys_fs: sys_fs_stat(“/dev_hdd1/cache/BLUS30187/lang/us/text/partsexplain_us.fmg”) failed: not found
E {PPU[0x1000000] Thread (main_thread) [0x011427b0]} 'cellFsStat' failed with 0x80010006 : CELL_ENOENT`
`E {PPU[0x1000000] Thread (main_thread) [0x011427b0]} sys_fs: sys_fs_stat(“/dev_hdd0/game/BLUS30187/USRDIR/install/lang/us/text/partsexplain_us.fmg”) failed: not found`
`E {PPU[0x1000000] Thread (main_thread) [0x011427b0]} 'cellFsStat' failed with 0x80010006 : CELL_ENOENT`
`E {PPU[0x1000000] Thread (main_thread) [0x011420f0]} cellNetCtl: cellNetCtlNetStartDialogLoadAsync(param=*0x19e78b4)`
`F {PPU[0x1000000] Thread (main_thread) [0x01142170]} class std::runtime_error thrown: Unimplemented
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellNetCtl.cpp:142)
`

Any help to identify this issue is appreciated!

**Comment by Asinin3** [comment]
"Any help to identify this issue is appreciated!" This sounds like you already know that this is more of an issue with your settings and not with the emulator itself. I suggest you read this: https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md before posting here. If you want assistance you can ask in the discord #help channel https://discord.me/RPCS3 and someone like myself will assist you. 

Please close this issue.

**Comment by Asinin3** [comment]
This has been solved he was using RPCS3 0.0.1
