### ISSUE TITLE
RPCS3 Opengl issues

### ISSUE THREAD

**Issue by ssboss** [RPCS3/rpcs3#3234]
For some reason, when I try to run a game on RPCS3 on Linux using opengl, I get a shader error, when I run a game through null, I get 30 fps, but the screen glitched with the desktop and only shows what's on the desktop even though the game is still running and is playable. (besides the fact that you can't see)

The game is persona 5. I heard people got it playing a little on rpcs3. The issue happens immediately though.

**Comment by AniLeo** [comment]
Missing information

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md)**

**Comment by ssboss** [comment]
This isn't from the game though. It's in general.

**Comment by ssboss** [comment]
Nevermind. I figured out what happened.
