### ISSUE TITLE
Tekken Tag Tournament HD - Game stuck at black screen

### ISSUE THREAD

**Issue by tabnk** [RPCS3/rpcs3#3236]
Tekken Tag Tournament HD

Game stuck at black screen. Build rpcs3 0.0.3-5733

Error message:
F {PPU[0x1000011] Thread (HLE Video Decoder)} class std::runtime_error thrown: Interlaced frames not supported (0x1)

Tested Setting: Both Vulkan and OpenGL
![image](https://user-images.githubusercontent.com/10874582/29344074-12bf55f0-8268-11e7-8fd1-3ee8551b4a72.png)

![image](https://user-images.githubusercontent.com/10874582/29344089-24606358-8268-11e7-98ff-baa21f0f3161.png)

**Comment by Asinin3** [comment]
Try turning "Write Color Buffers" on, if it doesn't work try Strict Rendering Mode.

**Comment by tabnk** [comment]
Try on both OpenGL and Vulkan. It is same issue. 

Al possible combination 
![image](https://user-images.githubusercontent.com/10874582/29362921-6f0a2652-82c0-11e7-9d6a-075f298c7568.png)

Also tried SPU Decoder to Interpreter (fast). Same issue.

**Comment by Asinin3** [comment]
Try this: ![image](https://user-images.githubusercontent.com/15137035/29363076-ac23c112-82cd-11e7-882e-67275d5215d0.png) I would also be using Preferred SPU threads at 2 or 3 for increased performance.

**Comment by tabnk** [comment]
Tried and it work. :)

![image](https://user-images.githubusercontent.com/10874582/29364401-d8dea7b0-82c5-11e7-97c3-2ae46259a59f.png)

**Comment by Asinin3** [comment]
@tabnk Please close the issue if it works now, next time ask on discord https://discord.me/RPCS3 #help channel if you want assistance.

**Comment by tabnk** [comment]
Yes, it work but there is video decoder issue. I will probably open another issue next time.

**Comment by Asinin3** [comment]
@tabnk I'm fairly certain the developers are aware of issues with the HLE decoder.
