### ISSUE TITLE
[Arch Linux] [BLUS30443] Demon's Souls hang if you get killed by dogs in second area

### ISSUE THREAD

**Issue by C0rn3j** [RPCS3/rpcs3#3239]
**EDIT4: Scroll to the bottom, the issue was that my RPCS3 install broke in some way, feel free to diagnose**

---

https://cloud.c0rn3j.com/s/GIvyHfdq8KKSgPG

Here's a save file. Using Arch Linux, today's git RPCS3-6d14583f, 1080 Ti with Nvidia proprietary drivers.

If you load the save and run 3 seconds forwards, dogs will break vases. Let **the dogs** kill you. Game should hang. Not sure if it happens on Windows.

This is using OpenGL. 

With Vulkan I still trigger a no-respawn bug but this time it's not black screen, the image just freezes >.<

EDIT: Not reproduceable with a different game version on Windows with either OpenGL or Vulkan - BLES00932

EDIT2: looks like death by fireball from the sorcerer triggers it too

EDIT3: Someone on Windows tested exact build of RPCS3 and same game version and wasn't able to reproduce.

**Comment by C0rn3j** [comment]
Also the area after the dogs doesn't seem to render at all. Looks like this area is glitchy overall.

https://youtu.be/-D8Jhu5PhiA

**Comment by kd-11** [comment]
This problem seems specific to the poster's setup (Arch) from a debugging session we heldon discord. Any other users experiencing the same issues would help narrow down the problem. It happens on both AUR package and self compiled builds. The area is stonefang mine 2-1.

**Comment by kd-11** [comment]
@C0rn3j Also include rpcs3.log file

**Comment by hcorion** [comment]
Just tested on Arch Linux, self-compiled with clang 4.0, and wasn't able to reproduce.
i7 4770
GTX 1070 with NVIDIA beta binary driver v384.59
KDE Plasma
X11
Latest master as of 334327df

Log: https://gist.githubusercontent.com/anonymous/46599a9bb33853e4518e3e13d96bea63/raw/ea2f443062da3ba1c149b47ec13efd1e9b2806e0/RPCS3.log
Notably, I was using Vulkan. I haven't been able to get OpenGL past the loading screen.

**Comment by hcorion** [comment]
I was able to get OpenGL working, and again, wasn't able to reproduce.
Log: https://gist.githubusercontent.com/hcorion/59fa7d3dfbe07fdef8a5392d8837981c/raw/11e11fbeb88b1bc7ad75d982433aa8d5c2d56f19/RPCS3.log
This was using no previous shader cache, the Vulkan already had some shaders in the cache.

**Comment by C0rn3j** [comment]
[OpenGL, Vulkan] Tried with 334327df - now when it gets to the dead loading screen I get following in the log console - 
```
U {PPU[0x100002c] Thread (ChrProxyThreadMan::Thread) [0x00a662f0]} libnet TODO: sys_net_free_thread_context(tid=0, flags=1)
E {PPU[0x1000000] Thread (main_thread) [0x00c3a9d4]} 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [2]
U {PPU[0x100002b] Thread (ChrInsManThread::Thread) [0x00a662f0]} libnet TODO: sys_net_free_thread_context(tid=0, flags=1)
E {PPU[0x1000000] Thread (main_thread) [0x00c3a9d4]} 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [3]
```

---

After more testing **I actually found the issue**. My RPCS3 install somehow bugged out it seems, because I moved the whole install elsewhere, let everything generate anew and now I can proceed with the save.

I will upload the broken+working version of my rpcs3 folder(1.1GB), but it will be in about 13 hours since my upload speed is horrible and I don't want to make my net unusable for the whole hour.

**Comment by C0rn3j** [comment]
https://sc2.c0rn3j.com/rpcs3-2builds.7z

Broken + working rpcs3 folder.

If someone wants to figure out why my rpcs3 broke, please do so. If devs don't have any interest in diagnosing why the install broke feel free to close the issue.

**Comment by kd-11** [comment]
DeS writes some cached files to /dev_hdd1 - I suspect this is why the issue kept persisting even when /data was deleted. Its now something to be aware of for other users with broken DeS installations.

**Comment by C0rn3j** [comment]
@kd-11 Can I then remove the _rps3-2builds.7z_ file? 

If that is why it broke the cached files would be there.

**Comment by kd-11** [comment]
Yea, its not really needed anymore.
