### ISSUE TITLE
E {rsx::thread} RSX: Depth texture bound to pipeline with unexpected format 0x83

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#3245]
Game: After Burner Climax (NPUB30151)
Tested on: e668ecd45332a0b7e771557159b993b9f67741f0
(on current master it crashes for me)

**Comment by kd-11** [comment]
This was fixed on master by this commit: https://github.com/RPCS3/rpcs3/commit/b2b5f564a14d9855f162f87368c2e8e63c0a81f3
