### ISSUE TITLE
#3366 Regression: Castlevania: Harmony of Despair

### ISSUE THREAD

**Issue by Couls** [RPCS3/rpcs3#3247]
"unsupported relocation in dllalucard.ppu.sprx. Please report."
freezes when clicking start game 
![image](https://user-images.githubusercontent.com/30060146/29388623-c6546e5c-82b3-11e7-9b66-5cdcaf2e861c.png)

Log:
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/1229715/RPCS3.txt)

**Comment by Couls** [comment]
Game has regressed further into a "Nothing" state with a memory access violation(rip castlevania)
F {PPU[0x1000000] Thread (main_thread) [0x007e0b68]} MEM: Access violation writing location 0xd0000fe0

**Comment by AniLeo** [comment]
What commit broke it?

**Comment by SakataGintokiYT** [comment]
@AniLeo 
Regression by #3366
This game works with #3354

**Comment by JacobAL** [comment]
Still ain't working. Tries to boot but no graphics.

**Comment by Felina-Lain** [comment]
After trying the mentioned working version (#3354), I get a "Not enough available space". The game launch, but freeze at the menu when I press start

**Comment by Nekotekina** [comment]
Try #3984

**Comment by Felina-Lain** [comment]
>Nekotekina commented 22 hours ago:
Try #3984<

I went to the download page, looked the download history for the 3984
Did not find it
Tried 3983 instead
Still stuck with
"F {PPU[0x1000000] Thread (main_thread) [0x007e0b68]} MEM: Access violation writing location 0xd0000fe0"

**Comment by SakataGintokiYT** [comment]
@Felina-Lain 
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7316/artifacts

**Comment by AniLeo** [comment]
Ongoing pull requests aren't on the downloads page.
Obviously trying 3983 has nothing to do with trying 3984.

**Comment by Felina-Lain** [comment]
>SakataGintokiYT commented 14 minutes ago
@Felina-Lainhttps://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7316/artifacts<
Thank you, trying right now, will edit with results

>AniLeo commented 14 minutes ago
Ongoing pull requests aren't on the downloads page.
Obviously trying 3983 has nothing to do with trying 3984.<

Of course, but being so close in number, I figured maybe there was a chance that it would work, so I still tried *shrug*

**Comment by Sukunda** [comment]
Setting the PPU decoder to Interpreter (fast) will allow the game to play through levels. I did not finish the first level as my frame rate was far too low to take the time to do the whole level.
![untitled](https://user-images.githubusercontent.com/34880125/34373852-3e002e80-eaa3-11e7-9550-6d576d577bf1.png)

**Comment by AniLeo** [comment]
Closing as reported regression has been fixed.

_If new issues appear, open a new issue, don't revive this one_
