### ISSUE TITLE
F1 2010: black screen only on Vulkan

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3248]
Hello @kd-11, couldn't you look at this: F1 2010 doesn't show it's picture on Vulkan, OpenGL only.
![31](https://user-images.githubusercontent.com/14265316/29393092-861de046-830a-11e7-85cb-4f9f334c58e7.png)
![32](https://user-images.githubusercontent.com/14265316/29393103-8c41f642-830a-11e7-9803-9ae958e8ce1f.png)
![33](https://user-images.githubusercontent.com/14265316/29393117-905fdef6-830a-11e7-8b52-149d99b0075c.png)
![4](https://user-images.githubusercontent.com/14265316/29393120-95b99694-830a-11e7-88f3-7bb0bd31e207.png)
![41](https://user-images.githubusercontent.com/14265316/29393121-9b65952a-830a-11e7-93f5-e715de05d495.png)
And I can even go through the interview and input my name:
![42](https://user-images.githubusercontent.com/14265316/29393130-adb710d2-830a-11e7-8e7c-c4077dfad8ce.png)
Logs: [F1_2010.zip](https://github.com/RPCS3/rpcs3/files/1229957/F1_2010.zip)
P.S. In OpenGL, this thing appeared:
>·F 0:05:22.545378 {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 
'

**Comment by kd-11** [comment]
Retest with current master

**Comment by TotalCaesar659** [comment]
Same result.
![f1_2010](https://user-images.githubusercontent.com/14265316/30722622-f0b60c20-9f3a-11e7-82bd-8ba749bb1e8b.png)
![f1_20102](https://user-images.githubusercontent.com/14265316/30722625-f5f10276-9f3a-11e7-95d8-2b096ea6e36b.png)
[F1_2010.zip](https://github.com/RPCS3/rpcs3/files/1322992/F1_2010.zip)

**Comment by kd-11** [comment]
Retest

**Comment by TotalCaesar659** [comment]
Same result, "Strict Rendering Mode" and "Write Color Buffers" don't help.
[F1_2010.zip](https://github.com/RPCS3/rpcs3/files/1598956/F1_2010.zip)

**Comment by TotalCaesar659** [comment]
Fixed in https://github.com/RPCS3/rpcs3/pull/4469.
