### ISSUE TITLE
Batman: Arkham city | missing textures

### ISSUE THREAD

**Issue by fenix008** [RPCS3/rpcs3#3250]
There's missing textures on character turning. Recent update of kd-11 did textures more displayable, but they are still disappearing on turning.

Thread: http://www.emunewz.net/forum/showthread.php?tid=158792
![ss 2017-08-17 at 10 54 02](https://user-images.githubusercontent.com/4106942/29402021-10107a6c-833c-11e7-8c77-8d7bd5151d6a.jpg)

**Comment by Asinin3** [comment]
This may be a zcull regression have you tried the earlier builds without zcull? Or have you tried it under vulkan?

**Comment by fenix008** [comment]
@Asinin3 yes, i tried earlier builds. It's the same. Vulkan doesn't working properly...idk why.
When i'm trying to run as Vulkan, it still loads openGL...

**Comment by Megamouse** [comment]
if you changed it in global settings, see if you have a custom configuration on that game

**Comment by fenix008** [comment]
ooh, i didn't know about that. I just delete all folders and config file to recreate it.

**Comment by Asinin3** [comment]
If you encounter this again under vulkan please post your log file here. If you don't you may want to just try this build: https://ci.appveyor.com/api/buildjobs/try2sv2lhp0j2k1o/artifacts/rpcs3-v0.0.3-2017-07-27-02845f54_win64.zip with openGL.

If that fixes it then it's probably a zcull regression.

**Comment by fenix008** [comment]
@Asinin3 okay, i did. On Vulkan it's absolutely the same (all is missing when i'm turning and show textures at the edges of the screen, but it's 30 fps (full speed). I tried it on openGL on llv-gcm build, before this build and now (last master build).
[RPCS3_Batman_AC.zip](https://github.com/RPCS3/rpcs3/files/1230593/RPCS3_Batman_AC.zip)

**Comment by Asinin3** [comment]
@fenix008 Okay well at least we ruled that out, is it the same with Write Color Buffers ON? and what about Strict Rendering Mode?

**Comment by fenix008** [comment]
@Asinin3 same

**Comment by fenix008** [comment]
Okay, i did small video about this problem.
[https://www.youtube.com/watch?v=KXDKiSUAaiA](url)

**Comment by scribam** [comment]
@fenix008 Is it still an issue?

**Comment by fenix008** [comment]
@scribam this game doesn't work anymore (i can't remember what's the update killed him...), so I can't say about that graphic glitch now :(

**Comment by fenix008** [comment]
@scribam ooh, okay...I just tester it.
It's working now, but until main menu, i can't press "start", because buttons don't work.
And infinity spam "E {rsx::thread} RSX: Blit request denied because the destination region does not fit! x8940"

**Comment by kd-11** [comment]
Retest and update

**Comment by fenix008** [comment]
I hope someone can test it, cause my hdd is broken with rpcs3 and stuff :(

**Comment by prinskarnatie** [comment]
Missing textures still an issue on build 8143. Tested with Vulkan and OpenGL.

System Info

Windows 10 1804
Nvidia 980Ti 430.64
Intel i7-6700K

Game serial : NPEB00941

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3194051/RPCS3.zip)
[TTY.zip](https://github.com/RPCS3/rpcs3/files/3194053/TTY.zip)
![NPEB00941 Batman Arkam City missing textures](https://user-images.githubusercontent.com/43773503/57969668-a94e5e80-7979-11e9-9194-a2fb5015d6cc.png)

**Comment by weter11** [comment]
Batman: Arkham Origins also the same issue, not only Arkham city. Looks like appearance and disappearance of textures on turning.

**Comment by digitaldude555** [comment]
![Screenshot (239)](https://user-images.githubusercontent.com/26138653/62937816-58ae9c00-bdd6-11e9-9923-5e9baaf9055d.png)
write depth buffers fixes it.

**Comment by fenix008** [comment]
We got it boys! Congratulation to rpcs3 team :)

**Comment by arkhamsaiyan** [comment]
Can confirm write depth fixes this in all ARKHAM games. Now if only it did the same in Ultimate Tenkaichi hahaha
