### ISSUE TITLE
Skate 3 Crashes on Boot

### ISSUE THREAD

**Issue by sambow23** [RPCS3/rpcs3#3251]
In earlier builds, it would work perfectly fine.

These are my specs:
Motherboard : GIGABYTE Z97M-DS3H
CPU: Intel Core i5 4690k 4.7GHz
RAM: 8GB
Graphics Card: MSI GTX 1060 GAMING X 6G
OS: Windows 10 Pro

![image](https://user-images.githubusercontent.com/14916663/29407660-be040b52-830a-11e7-96fa-bf9d31cf9507.png)

[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/1230925/RPCS3.txt)

**Comment by kd-11** [comment]
`·E 0:00:17.300074 {Audio Thread} XAudio2Thread : CreateMasteringVoice() failed(0x80070490)`
You have issues with audio setup it seems. Set audio to Null and retry. If it works, your system's sound configuration is broken or there are no audio output devices. It is an emulator bug though, the emulator should disable audio if no possible output is possible.

**Comment by sambow23** [comment]
@kd-11 Will do! Thanks!


_Sent from my Motorola DROID Turbo using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mchtt** [comment]
i confirm @AniLeo this as i'm testing this game on a regular basis, no regressions to report yet.

**Comment by mikeair8** [comment]
when i launch the game i only get to the "press start button to continue" and then the game crashes everytime

**Comment by mchtt** [comment]
Weird, i tried with yesterday builds, it's still loading for me, maybe your game backup is corrupted.
Without a proper **log** nobody can tell.
.
