### ISSUE TITLE
Battlefield 4 OpenGL yellow gameplay screen

### ISSUE THREAD

**Issue by JusicP** [RPCS3/rpcs3#3252]
Battlefield 4 on OpenGL has yellow gameplay screen. Tested on RPCS3 v0.0.3-3-334327d
![bf4 gl](https://user-images.githubusercontent.com/25232950/29409432-d16bd69e-8354-11e7-8f85-1e97e289b545.png)
[BF4 OpenGL.zip](https://github.com/RPCS3/rpcs3/files/1231059/BF4.OpenGL.zip)

**Comment by Ru4slan** [comment]
Видел тест. Там было тоже желтоватое, но всё было видно.

**Comment by MoochMcGee** [comment]
Try enabling write color buffers I guess.

**Comment by JusicP** [comment]
With write color buffers nothing changed, but in log i can see this message RSX: Unsupported RTT scaling factor: dst_pitch=256 src_pitch=8 x41 with random full freeze

**Comment by scribam** [comment]
@JusicP Any progress with a recent build?

**Comment by JusicP** [comment]
Fixed
