### ISSUE TITLE
Game frozes when i start.

### ISSUE THREAD

**Issue by Augiss** [RPCS3/rpcs3#3253]
Can't play any games on RPCS3. When I starting game everything is okei, but 1 min later game froze and black screen. Please help me fix this error.
![crashes](https://user-images.githubusercontent.com/31098554/29410121-e477c902-8357-11e7-9676-b2f305af9e1f.PNG
![crashes 2](https://user-images.githubusercontent.com/31098554/29410154-0631656c-8358-11e7-89a9-a4486e1fe187.PNG)
)

**Comment by Asinin3** [comment]
This is not the place to ask for assistance, please read https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md before making an issue report. If you want assistance join the RPCS3 #help channel on discord here: https://discord.me/RPCS3 and someone such as myself will help you.

Please close this issue as there isn't enough information for it to be useful anyway and the game is clearly working for other people (probably with different settings or build.)

**Comment by Augiss** [comment]
Help me fix this problem.
