### ISSUE TITLE
Update README.MD and add gdb info to wiki

### ISSUE THREAD

**Issue by C0rn3j** [RPCS3/rpcs3#3254]
https://github.com/RPCS3/rpcs3/blob/master/README.md

- [ ] Add the following line to the Linux compile instructions as a "how to update the build to latest git commit"

```
git pull origin master && make
```

---

- [ ] Add Linux gdb debugging info (to wiki?) (and link to it from the readme)
```
gdb ./rpcs3
> set logging on
> handle SIGSEGV nostop noprint
> break exit
Function "exit" not defined.
Make breakpoint pending on future shared library load? (y or [n])
> n
> run
```

If game crashes you should be able to run `bt` in gdb to get useful debug info. If you somehow close the terminal it should also be logged in gdb.txt

If the game doesn't actually crash but just freeze, you could try getting the game to bug, then CTRL+C in gdb and then execute `thread apply all bt` to dump all threads.

---

- [x] README.MD refers to **OS X**, which was renamed to **macOS**

**Comment by greentop** [comment]
If the game doesn't actually crash but just freezes, a procedure or option is needed to consistently get the game to bug in order to then follow with the CTRL+C in gdb.

**Comment by kirbyfan64** [comment]
Sometimes I wonder if an LLDB and/or GDB script(s) would be useful to make debugging easier to a person less familiar with the intricacies of the respective debuggers...

**Comment by C0rn3j** [comment]
>Sometimes I wonder if an LLDB and/or GDB script(s) would be useful to make debugging easier to a person less familiar with the intricacies of the respective debuggers...

Honestly I'd be fine with a good tutorial, at least I'd learn something new ^^

**Comment by dio-gh** [comment]
Outdated ticket, closable.
