### ISSUE TITLE
 RSX: Depth texture bound to pipeline with unexpected format 0x95

### ISSUE THREAD

**Issue by kamer1337** [RPCS3/rpcs3#3258]
i think it doesn't affect gameplay but this error is spammed in the log like crazy

Tony Hawk's Project 8
Tony Hawk's Proving Ground

both games are ingame

LOG [thp8.zip](https://github.com/RPCS3/rpcs3/files/1234040/thp8.zip)

**Comment by Asinin3** [comment]
Wasn't this fixed in [https://github.com/RPCS3/rpcs3/commit/b2b5f564a14d9855f162f87368c2e8e63c0a81f3](url) ? Try the latest master and see if it's still happening. Looks like you're using an older build before kd-11s changes were merged yesterday.

**Comment by kamer1337** [comment]
i used the latest master build

**Comment by Asinin3** [comment]
@kamer1337 Must be using an old config.yml then because you have the option to disable vertex cache.

**Comment by kamer1337** [comment]
commit you linked is 404 not found

**Comment by Asinin3** [comment]
@kamer1337 Sorry about the 404, should work now.

**Comment by kamer1337** [comment]
no. itsn ot included here

CELL_GCM_TEXTURE_Y16_X16 = 0x95

**Comment by kd-11** [comment]
That requires alot more investigation actually since Y16X16 does not map cleanly to any depth formats.

**Comment by Kravickas** [comment]
I think the spam on this ''memory leaked'' rpcs3 and crashed gpu driver in THP 8-> needed hard restart.
It spams like 200x depth text... per sec.

**Comment by scribam** [comment]
Found the log also in Full Auto 2: Battlelines.

**Comment by AniLeo** [comment]
Also happens on several Guitar Hero games

**Comment by kamer1337** [comment]
this issue seems to be fixed with #5785

**Comment by AniLeo** [comment]
PR is not yet merged, reopened.

**Comment by kd-11** [comment]
Closing as fixed.
