### ISSUE TITLE
Dragon's Crown glitchy under Vulkan mode 

### ISSUE THREAD

**Issue by ryan0432** [RPCS3/rpcs3#3260]
Hi, today I tested Dragon's Crown on the latest ver. of PRCS3, the frame rate is significantly improved and looks amazing.
However, I am having an issue where the screen glitches badly in game.
I am using a Quadro M4000, don't know if it's the graphic card causing this issue.
In addition, I am playing the traditional Chinese ver. BCAS20298  instead of BLUS30767. So the patch is probably not working in my case.
**E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: unknown origin (0)** This happens from time to time. 
Is there any method to solve the problem? Cheers.

log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1234579/RPCS3.zip)

**Comment by RipleyTom** [comment]
Using "Strict rendering mode" should solve all graphical issues in Dragon's Crown.
If you want a patch for your version contact me on discord.

**Comment by RipleyTom** [comment]
Posted hang fix for that version in #3013 .
He told me that his graphic glitches were fixed by updating drivers.
Can be closed.
