### ISSUE TITLE
Cant play Persona 5 with Vulkan

### ISSUE THREAD

**Issue by nilfgaard12** [RPCS3/rpcs3#3261]
![rcps3](https://user-images.githubusercontent.com/31137450/29466792-c2a6ba26-8470-11e7-8254-7e55f1ca2d72.png)

it works okay with OpenGL but very low FPS , i want to use vulkan but it doesnt play the game and just displays this error message. any help would be appreciated.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
