### ISSUE TITLE
Project Diva F 2nd performance drop

### ISSUE THREAD

**Issue by oobol2000oo** [RPCS3/rpcs3#3262]
It seem run smoothy on RPCS3 commit [e668ecd45332a0b7e771557159b993b9f67741f0](https://github.com/RPCS3/rpcs3/commit/e668ecd45332a0b7e771557159b993b9f67741f0) but after commit [e668ecd45332a0b7e771557159b993b9f67741f0](https://github.com/RPCS3/rpcs3/commit/e668ecd45332a0b7e771557159b993b9f67741f0) it's kinda laggy on my laptop
Laptop specs:
i5-6200U
Nvidia 930M 2GB
RAM 8GB
Game serial: BLUS31431
Render: Vulkan

**Comment by AniLeo** [comment]
Read https://rpcs3.net/blog/2017/08/16/rewriting-vertex-processing-for-massive-performance-gains/

**Comment by oobol2000oo** [comment]
Well, I play the second and third time it's still laggy :( (at least better than the first play)

**Comment by divStar** [comment]
Hello!
Yeah - I checked it out, too, and yes - it is stuttering even the 2nd and 3rd time (to a degree that it's unplayable / freezes (music keeps going) for a few moments).
i7-4770
GeForce GTX980
32GB RAM
Game serial: BLUS31431
Render: Vulkan and OpenGL.

Still amazing how well it works considering the huge architecture differences of the PS3 and a x86-system, but I'd say it is rather unplayable than playable, but it is very close to being perfectly playable. So I just want to thank you and humbly ask to keep going on improving this pretty baby!
