### ISSUE TITLE
[Arch Linux] [BLUS30443] Demon's Souls randomly crashes with Vulkan and LLVM

### ISSUE THREAD

**Issue by C0rn3j** [RPCS3/rpcs3#3266]
https://cloud.c0rn3j.com/s/x5gVx3yWOhdrAyU
^ RPCS3.log

Seems to happen randomly, usually shortly after or during teleporting/starting the game.

**Comment by kd-11** [comment]
This is a major spurs synchronization bug with linux that affects almost all titles I have tested. Closing in favor of something more complete since more logs and reports cannot help fix it.

**Comment by C0rn3j** [comment]
I did expect this on most titles on linux+ vulkan indeed.

Would you be so kind and post the issue that replaces this one here so I can subscribe to it? ^^
