### ISSUE TITLE
Kingdom Hearts 1.5 ReMix won't launch in new build

### ISSUE THREAD

**Issue by JacobAL** [RPCS3/rpcs3#3269]
[Here's the log.](https://www.dropbox.com/s/r8imfvl5hgvjrjx/RPCS3.log?dl=0)
[Here's an error code.](http://i.imgur.com/2id21op.png)
[Here's what the console looked like.](http://i.imgur.com/652BoX4.png)

I haven't had issues with launching the game in previous builds.

**Comment by JackONeill12** [comment]
Still works fine for me.

**Comment by JacobAL** [comment]
Ah, I found out that It's because I turned off the RPCS3.log.
Doesn't make other games crash, but I guess it does for KH because it has to relaunch when you choose which game you're playing.
