### ISSUE TITLE
Unity Games-- Death by 0x38

### ISSUE THREAD

**Issue by flash-fire** [RPCS3/rpcs3#3271]
After looking in the forums, I noticed several Unity games in nothing die in the same way--

F {PPU[0x1000005] Thread (UnityMain) [Some address]} MEM: Access violation reading location 0x38

From doing some relatively basic analysis of the assembly, it seems to have something to do with sys_ppu_thread_get_id.

Anyhow, here's a (probably incomplete) list of games I noticed so far that died like this:

The bridge
The swindler
Space hulk
Renevant Saga
Back to Bed
Frozen Free Fall - Snowball Fight 
Aaru's Awakening
Anna - Extended Edition

(Logs can be found in the forums. I'm mostly making this since it seemed peculiar that many games died like this. And, so that, if someone wants to fix several games at once, they have a target.)

EDIT 1: Added another game that has this behavior.

**Comment by digitaldude555** [comment]
Slender - The Arrival.
In Space We Brawl.
2 more I found.

**Comment by Farseer2** [comment]
Thomas was Alone has this error as well

**Comment by NotMyKoDa** [comment]
Cosmophony is another. Majority of Unity games are plagued with this issue I have found.

**Comment by RipleyTom** [comment]
#3294 should fix some of those crashes(0x38 ones).

**Comment by SakataGintokiYT** [comment]
@RipleyTom 
https://github.com/RPCS3/rpcs3/pull/3294#issuecomment-323852887
**The bridge** 
```
F {PPU[0x1000005] Thread (UnityMain) [0x000c1158]} class std::runtime_error thrown: Trap!
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:3093) 

```
**[Log:](https://gist.github.com/SakataGintokiYT/2694fea5794908dae0e38a1a15ec1e21)**

**Comment by RipleyTom** [comment]
I'm aware, it's a different issue.

**Comment by Zangetsu38** [comment]
thomas alone fixed in you PR

**Comment by Zangetsu38** [comment]
Also, Lone surivor finally fixed :)

**Comment by NotMyKoDa** [comment]
F {PPU[0x1000005] Thread (UnityMain) [0x000c1158]} class std::runtime_error thrown: Trap!
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:3093) for Cosmophony as well.

**Comment by digitaldude555** [comment]
In Space We Brawl, Krinkle Krusher, Slender Man, The Bridge, The Swindle, Frozen FreeFall Snowball Fight and Sky Force Anniversary.

`F {PPU[0x1000005] Thread (UnityMain) [0x000dcc08]} class std::runtime_error thrown: Trap!
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:3093)`

Also I don't remember thomas was alone ever having this error, it was playable unlike these games that have been nothing forever. Also how exactly is Lone Survivor fixed when it used Adobe Air and not Unity?

**Comment by flash-fire** [comment]
This issue is technically fixed but I want to keep this issue open still until my page fault PR is done.

**Comment by scribam** [comment]
@flash-fire PR #3309 is merged :+1:

**Comment by AniLeo** [comment]
Closing as it's solved
