### ISSUE TITLE
error the evil within F {rsx::thread} class std::runtime_error thrown: Unknown draw mode (0x9)

### ISSUE THREAD

**Issue by luisloco** [RPCS3/rpcs3#3272]
F {rsx::thread} class std::runtime_error thrown: Unknown draw mode (0x9)
(in file C:\rpcs3\rpcs3\Emu\RSX\Common\BufferUtils.cpp:756

![1](https://user-images.githubusercontent.com/5092869/29490375-6b02fc96-84ff-11e7-8ba9-b9100b0a6e4f.png)
![2](https://user-images.githubusercontent.com/5092869/29490376-6b068b7c-84ff-11e7-937d-5404ac457e8f.png)
![3](https://user-images.githubusercontent.com/5092869/29490377-6b09a0aa-84ff-11e7-915a-ccb776db34d0.png)

log
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1236693/RPCS3.zip)

**Comment by Zangetsu38** [comment]
yes, dev know that, already informed in other game ^^

**Comment by luisloco** [comment]
ahhh ok :)

**Comment by kd-11** [comment]
Its a very rarely used. I'll implement it soon

**Comment by kd-11** [comment]
Retest with PR build at https://github.com/RPCS3/rpcs3/pull/3315

**Comment by kd-11** [comment]
Fixed in current master. Reopen if the issue persists.

**Comment by Zangetsu38** [comment]
no is good, juste game crash with vulkan but run ingame in ogl, with few glitch lightning

**Comment by isshininu** [comment]
SH:D crashes on Vulkan too. It's vertex bug.
