### ISSUE TITLE
Command line launching results in crash

### ISSUE THREAD

**Issue by mashakos** [RPCS3/rpcs3#3274]
Launching rpcs3 games via command line causes the following crash
https://cdn.discordapp.com/attachments/272035812277878785/348683476519878657/cras.jpg

**Comment by Asinin3** [comment]
I was talking to someone yesterday who had a similar issue but fixed it by disabling a few options in the RPCS3 settings > emulator tab. IIRC it was the exit process when RPCS3 finishes setting, can you try that?  If it doesn't work it may be the resize window on boot coupled with start in full-screen.

You should post the command you're using and the full log file though.

**Comment by mashakos** [comment]
thanks for the suggestion, turns out that disabling the exit on process close setting avoids a crash.

It kinda sucks though as the exit on process close setting makes RPCS3 very easy to use with a frontend.

**Comment by Megamouse** [comment]
please test with https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6668/artifacts
