### ISSUE TITLE
Glitchy Project Diva F 2nd background & crash issues

### ISSUE THREAD

**Issue by KyofushoKinoko** [RPCS3/rpcs3#3275]
[log (1).txt](https://github.com/RPCS3/rpcs3/files/1236887/log.1.txt)
Background for all menus are missing and blank ( black ) 
<img width="636" alt="1" src="https://user-images.githubusercontent.com/31175752/29492562-118d4e2e-85b2-11e7-9a9f-0b2e28febefb.PNG">
<img width="633" alt="2" src="https://user-images.githubusercontent.com/31175752/29492563-11b7233e-85b2-11e7-8c47-3934d0c03e50.PNG">

The whole emulator also crash when the window for the game is minimised
message: ---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000010 at 00007ffeabf84e16.
Instruction address: 00007ffeabf84e16.
Function address: 00007ffeabf84e10 (base+0x1a4e10).
Module name: 'ig75icd64.dll'.
Module base: 00007ffeabde0000.
RPCS3 image base: 0000000000010000.

system : 
<img width="345" alt="s" src="https://user-images.githubusercontent.com/31175752/29492502-f509dfda-85af-11e7-9509-83c0db25e897.PNG">

I have realized that earlier builds like the one on 15 August does not have the problem and does not lag at loading screen unlike the newest build.

**Comment by kd-11** [comment]
Issues presented here are already tracked here:
https://github.com/RPCS3/rpcs3/issues/3194
https://github.com/RPCS3/rpcs3/issues/3243
Closing as a duplicate.
