### ISSUE TITLE
Project Diva F / F 2nd edit mode loading loop

### ISSUE THREAD

**Issue by samyuu** [RPCS3/rpcs3#3276]
Both games are stuck in an infinite loading loop when trying to create new edit data, loading old edit data or when using the juke box inside the diva room. 
This does not happen when selecting one of the three sample edits in F 2nd as this just happens to skip the music selection screen.
Editing and playing these sample edits is fully functional.
This happens on all current releases regardless of hardware.

**Comment by Nezarn** [comment]
needs cellSearch stuff implemented

**Comment by scribam** [comment]
Can someone test if the loading loop is gone with PR #3996? If the issue is still here, upload a log file.

**Comment by Nezarn** [comment]
loading loop is gone (but since that PR just makes everything return error, it doesn't actually enables cellsearch related stuff, its basically does the same as I did on my PC, I just returned an error instead of cell_ok everywhere (aside from searchinitialize since that already had some code))

**Comment by Megamouse** [comment]
yeah the loading loop is gone.
