### ISSUE TITLE
OSK: closing by X or ESC hangs the Game

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#3277]
When you close/cancel the On Screen Keyboard Dialog the game won't continue.
It has worked before when we fixed Msg_dialog, so I think something else than the Qt part is at fault.
The on_close seems to work fine. So it has to be the sysutil in cellosk or something past that.

Games I tested this were Demon's Souls and Dragon's Crown

**Comment by Megamouse** [comment]
#3287

**Comment by Megamouse** [comment]
needs max length check / max input field length still though

**Comment by RipleyTom** [comment]
Everything fixed&implemented in #3287, it can be closed.
