### ISSUE TITLE
GL/Vulkan: Homebrew regression 

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#3278]
**PS3 Homebrew:** **[ Link ](http://store.brewology.com/homebrew.php?category=Games)**
[with write color / strict rendering  / disable Vertex cache : same result] 

**1.UFO Racer 
OpenGL /Vulkan** 
![1](https://user-images.githubusercontent.com/13681488/29494047-b6dad866-85a2-11e7-9719-15809ebf0368.png)

---------------------------------------------------------------------------------------------------------------
**2.Winters End
OpenGL / Vulkan** 
![2](https://user-images.githubusercontent.com/13681488/29494060-e0e067b6-85a2-11e7-8296-3dfb952dd4b5.png)

---------------------------------------------------------------------------------------------------------------
**3.Sketch Fight
OpenGL/ Vulkan**
![3](https://user-images.githubusercontent.com/13681488/29494067-f64f040e-85a2-11e7-9b2d-b7c93fa0bcbe.png)

---------------------------------------------------------------------------------------------------------------
**4.Neo Racer
OpenGL**
![6](https://user-images.githubusercontent.com/13681488/29494084-354a286e-85a3-11e7-81e0-0093000780c9.png)

---------------------------------------------------------------------------------------------------------------
**5.Hero City 2
OpenGL / Vulkan**
![7](https://user-images.githubusercontent.com/13681488/29494089-49977a6a-85a3-11e7-82b4-ba0b0b5e7402.png)

---------------------------------------------------------------------------------------------------------------
**6.Gambol
OpenGL / Vulkan**
![8](https://user-images.githubusercontent.com/13681488/29494096-625117fa-85a3-11e7-9217-a8db654bd52b.png)

**Comment by Sir-Weebz-A-Lot** [comment]
#OGLIsTheNewVulkan

**Comment by SakataGintokiYT** [comment]
It's weird because after compile the shader cache and after reboot emulator the graphic is rendered correctly.
