### ISSUE TITLE
Toolbar icons missing (Linux/Qt)

### ISSUE THREAD

**Issue by gasinvein** [RPCS3/rpcs3#3279]
Subj. Buttons on toolbar work, but they are very small and missing icons.
![screenshot_20170820_140012](https://user-images.githubusercontent.com/4569691/29494316-2cae0cf4-85b0-11e7-8349-7b5452e3959d.png)

**Comment by Megamouse** [comment]
assign to hcorion hehe

**Comment by scribam** [comment]
@gasinvein Would you mind testing the PR #3376 and telling me if the issue is still there ?

**Comment by gasinvein** [comment]
@scribam Yes, it works.
