### ISSUE TITLE
Pac Man Museum Text don't read

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#3285]
Left Screen Text Game don't read

![image](https://user-images.githubusercontent.com/25039098/29497011-e9f09446-85f4-11e7-92ad-c77bf6a4a3a7.png)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1237238/RPCS3.zip)

**Comment by Kravickas** [comment]
strict rendering ?

**Comment by aakh1361** [comment]
after select strict rendering

![image](https://user-images.githubusercontent.com/25039098/29497204-23fcc91c-85f9-11e7-8bc0-11fb4b6b6d64.png)

**Comment by MarioSonic2987** [comment]
Could you retest and close this issue if it fixes text problem?

**Comment by aakh1361** [comment]
new test whit Strict Rendering
![image](https://user-images.githubusercontent.com/25039098/29744886-2af0f4e0-8ac3-11e7-9dac-e9860d24d2ef.png)

**Comment by aakh1361** [comment]
fixed in last build
![image](https://user-images.githubusercontent.com/25039098/31577930-f0089022-b123-11e7-8e8c-0955046689e1.png)
