### ISSUE TITLE
Unhandled Win32 exception

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#3288]
Blue screen after trying to play a game. And when i restarted the PC, can´t open RPCS3.

( Testing build  v0.0.3-5822 Alpha [2017-08-20] )

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xE06D7363.
Exception address: 00007ffb958f9e08.
ExceptionInformation[0x0]: 0000000019930520.
ExceptionInformation[0x1]: 000000000375e4f0.
ExceptionInformation[0x2]: 00000000018aa1d8.
ExceptionInformation[0x3]: 0000000000010000.
Instruction address: 00007ffb958f9e08.
Function address: 00007ffb958f9da0 (base+0x69da0).
Module name: 'KERNELBASE.dll'.
Module base: 00007ffb95890000.
RPCS3 image base: 0000000000010000.

**Comment by AniLeo** [comment]
Delete config.yml when you get KERNELBASE errors. And update your drivers before asking for support.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
