### ISSUE TITLE
Yakuza Dead Souls (BLUS30826)

### ISSUE THREAD

**Issue by Milii20** [RPCS3/rpcs3#3295]
Greetings, i write this since i searched a bit and coudnt find anything about the game.
I was playing Yakuza Dead Souls, and this is what i found:

![yakuza dead souls](https://user-images.githubusercontent.com/10578092/29541632-b7ec7408-86ab-11e7-8627-1d6f9777d3dc.jpg)

" E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: unknown origin (0) "

If we dont count the 6  to 10 fps, there is rarely any flickering or anything, and the sound is kinda broken, also, ingame videos work, but laggy, even when it says it's 30 fps,
The most stable config i was able to achieve was:

CPU: 
ppu = recompiler LLVM (any other option lags like crazy)
spu = recompiler ASMJIT 
and load automatic and manual selection of:
libaudio, libfiber, libfs, libl10n, libresc, librtc, libspurs_jq and libsre

GPU:
Vulkan, and write color buffers (opengl is way slower, and sometimes crashes when kiryu grabs the phone), and without write color buffers, everyone in the streets has broken textures)

Sound: tried both, xaudio and openal, both work the same

**Comment by AniLeo** [comment]
Before you go to forums, we don't care about ancient versions, so use latest if you want support

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net) for that.

The issue has been marked as **Invalid** and closed.

**Comment by Renusek** [comment]
@Milii20 right click your log and select "stack mode" - that way you can avoid spamming the log.
