### ISSUE TITLE
Project Diva F2nd has major graphical issues. 

### ISSUE THREAD

**Issue by TheRebellionIsHere** [RPCS3/rpcs3#3296]
Project Diva F2nd has very noticeable graphical issues that you can see in many of its stages and character models. None of which happened in the first Project Diva F.

I have noticed issues such as textures being incorrectly shaded, textures being non-existent where they should exists, and textures having a weird red texture plastered over them. Here are some screenshots:
![bug1](https://user-images.githubusercontent.com/31230438/29547155-70e0cd64-86c6-11e7-9ef9-30bd8ef62bf4.png)
![bug2](https://user-images.githubusercontent.com/31230438/29547167-82f068d4-86c6-11e7-8c2d-039a9977512a.png)
![bug3](https://user-images.githubusercontent.com/31230438/29547180-924200e0-86c6-11e7-8b4b-f03baf6fb4b8.png)
![bug4](https://user-images.githubusercontent.com/31230438/29547192-a0e5fd4a-86c6-11e7-8df4-cf13d551c239.png)
![bug5](https://user-images.githubusercontent.com/31230438/29547490-3e4aa10c-86c8-11e7-8d89-aaba5fff3cb7.png)

Build:
v. 0.0.3-5829

Specs:
Windows 8.1 64bit OS
NVIDIA GeForce GTX 1060 3GB
Intel Core i5-6500

Log:
https://pastebin.com/Y18jaYfS

**Comment by kd-11** [comment]
Duplicate of https://github.com/RPCS3/rpcs3/issues/3194
