### ISSUE TITLE
Broken vertices in Dead Space 2 demo

### ISSUE THREAD

**Issue by jjsat** [RPCS3/rpcs3#3299]
The demo for Dead Space 2 exhibits the following problem: 3D geometry as well as text is correctly rendered, but what basically are 2D billboards are broken. They are used for all floating UI elements in game and certain other effects as well as some splash screen elements.

![grafik](https://user-images.githubusercontent.com/1445782/29565580-c97e4fd4-8746-11e7-9221-b3e743cde109.png)
![grafik](https://user-images.githubusercontent.com/1445782/29565589-ce073cfa-8746-11e7-82a7-5c094da73f38.png)
![grafik](https://user-images.githubusercontent.com/1445782/29565593-d1cf9bfc-8746-11e7-9c65-6dd3418cf08a.png)

What these elements all have in common is that they:
- are drawn as quads with an index buffer
- have a vertex buffer with a stride of 48
- have a too small vertex buffer size of 48 if supposed to contain 4 vertices (size is larger for more vertices, but always too small - only 1/4th of required size)
- have 6 interleaved "locations" for that buffer
- have another location that seems to contain indices (0, 1, 2, 3 ...) which is also too small
- some vertex positions are obviously correct because they are anchored at the correct place in the world

Dead Space 1 demo has basically the same issue but there the affected vertices are defined with a stride of 64. The stride is not the root cause but it seems to come as a side effect of the drawing mode the game uses for these elements.

This issue occurs with both Vulkan and OpenGL and regardless of SPU/PPU setting. I don't see any setting that has an effect on this actually.

**Comment by Zangetsu38** [comment]
dead space 1 have same think in HUD

**Comment by kd-11** [comment]
Thank you @jjsat for researching the issue. I noticed one case where it appeared but I was unsure if it was a game bug or not. This at least confirms its the emulator thats at fault.

**Comment by jjsat** [comment]
There are other games in which the uploaded vertex count does not correspond to the number of vertices to draw. One that seems similar is Metro Last Light (stride 96, also multiple locations).

**Comment by kd-11** [comment]
Its expected for indexed draws that vertex count != draw count. Index buffer scanning is used to determine the minunum number of vertices referenced but admittedly that might be broken.

**Comment by jjsat** [comment]
Yes, I didn't write this correctly. I specifically meant cases in which the number of uploaded vertices is not enough to draw the primitive like in Dead Space. The emulation code draws quads as triangles anyway, so the draw count is in that case different from the original.

**Comment by kd-11** [comment]
I wonder, did it work correctly before the rewrite?

**Comment by Zangetsu38** [comment]
no, dead space 1 have same think, and rewrite no have affecter this

**Comment by jjsat** [comment]
I went back to commit 24002101448bc7eeff16d47806994ced775b268a before the vertex rewrite. Same behaviour as Zangetsu38 said.

Another game with this issue is Dantes Inferno. Unsurprising since it might use the same engine:
![grafik](https://user-images.githubusercontent.com/1445782/29577128-a01362e6-876a-11e7-8ba0-93358e73451d.png)

**Comment by Xcedf** [comment]
Thanks for reporting this issue wanted to report too, played Dante's Inferno to the third level where's these artifacts become very nasty which doesn't allow to play further

**Comment by kd-11** [comment]
Looks like its caused by broken vertex attrib divisor implementation. A fix will be submitted soon.

**Comment by kd-11** [comment]
This is very likely fixed here https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.3-919
I'd urge testing especially with silent hill 3 since it was used by the original author of that bit of code to determine ARL opcode behaviour. Let me know if anything breaks.

**Comment by jjsat** [comment]
Very nice!

Dead Space 2 Demo and Dantes Inferno are fixed.

Silent Hill 3 looks the same as before (the lighting is somewhat broken):
![grafik](https://user-images.githubusercontent.com/1445782/29636400-bf3d263e-8850-11e7-95c3-87000a6e78f6.png)

Also fixes flickering in Rayman Origins:
Before:
![grafik](https://user-images.githubusercontent.com/1445782/29636560-5990acb0-8851-11e7-9179-69695f8354ae.png)
After:
![grafik](https://user-images.githubusercontent.com/1445782/29636490-1e04ecf6-8851-11e7-89b6-a1d07fff435e.png)

**Comment by Zangetsu38** [comment]
fixed also Dead space 1 
![image](https://user-images.githubusercontent.com/5261759/29637881-d64b272c-8855-11e7-80c5-81568d7aeb1a.png)
![image](https://user-images.githubusercontent.com/5261759/29637899-dc7a05f0-8855-11e7-9263-ceee467f1389.png)
![image](https://user-images.githubusercontent.com/5261759/29637909-e595f37e-8855-11e7-9267-37b94bf94481.png)

**Comment by SakataGintokiYT** [comment]
@kd-11 
It's progress ?
![2](https://user-images.githubusercontent.com/13681488/29638705-5b20278e-8858-11e7-9932-ae6de267bc4b.png)

![bez tytulu](https://user-images.githubusercontent.com/13681488/29638693-502c8fca-8858-11e7-8278-833eb98e1821.jpg)

**Comment by Xcedf** [comment]
kd-11, awesome fix, thanks

**Comment by MarioSonic2987** [comment]
@kd-11 
**Before**:
![image](https://user-images.githubusercontent.com/20027681/29651204-ce1ca644-889f-11e7-974d-c234dd09c351.png)

**After**:
![image](https://user-images.githubusercontent.com/20027681/29651166-8fa6f75c-889f-11e7-941f-8fda8626a60d.png)

**Comment by SakataGintokiYT** [comment]
Fixed broken characters
![bez tytulu](https://user-images.githubusercontent.com/13681488/29659948-1e26ca96-88c0-11e7-839c-bdbf8d532b8a.png)

**Comment by nicesn2000** [comment]
@kd-11 
Dead Space 2 [BLUS30624]
Before: (rpcs3-v0.0.3-2017-08-21-607e57ad)
![rpcs3_dead_space_2_kd-11bf](https://user-images.githubusercontent.com/16824470/29696954-697f3f4a-8961-11e7-9bf7-ea86faf60122.jpg)
After:
![rpcs3_dead_space_2_kd-11af](https://user-images.githubusercontent.com/16824470/29697011-c8b82422-8961-11e7-967e-2458ad000984.jpg)

**Comment by woj1993** [comment]
@AniLeo This is fixed and can be closed. I think so at least.

**Comment by AniLeo** [comment]
Yeah, looks correct
