### ISSUE TITLE
Can't find RAP file for NPDRM decryption!

### ISSUE THREAD

**Issue by NotMyKoDa** [RPCS3/rpcs3#3300]
BEFORE CLAIMING I'M AN (idiotic) PIRATE: ![issue01](https://user-images.githubusercontent.com/31223914/29577882-0c780dac-8765-11e7-938a-74f2d2ca426e.JPG)
All the RAP files are in the correct area.

Anyway, now that I have said that, there are multiple games I have seen with custom .sprx files that I have failed to decrypt each time through the emulator. I always get the same error message, which is the title. Unity games (as I have seen) have the most custom .sprx files, but there are also a few others that still use them (from my own game collection: NFS The Run and DC Universe Online). I was told that these files should be decrypted and loaded by the emulator when the game boots, but this is not the case. I'll post an exerpt of all the modules loaded when trying to load up Cosmophony and what custom .sprx files the game has:

Log:
`Line 2731: ·S 0:00:00.962112 {PPU[0x1000000] Thread (main_thread) [0x01199fc8]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx

Line 3051: ·S 0:00:00.973007 {PPU[0x1000000] Thread (main_thread) [0x01199fc8]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx

Line 3176: ·S 0:00:00.979057 {PPU[0x1000000] Thread (main_thread) [0x01199fc8]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx

Line 3381: ·S 0:00:00.993650 {PPU[0x1000000] Thread (main_thread) [0x01199fa8]} sys_prx: Loaded module: /dev_flash/sys/external/libfiber.sprx

Line 3489: ·S 0:00:00.997147 {PPU[0x1000000] Thread (main_thread) [0x01199fa8]} sys_prx: Loaded module: /dev_flash/sys/external/libspurs_jq.sprx`

Here's an image of the all .sprx files for Cosmophony: ![issue02](https://user-images.githubusercontent.com/31223914/29577883-0c876130-8765-11e7-8398-7b0edd3503d7.JPG)

If you want more proof so as to not think this is a one off, contact me directly on discord.
Below is the full log of Cosmophony if anyone wants to sift through it.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1242778/RPCS3.zip)

**Comment by kamer1337** [comment]
this is not place for such problems, go to https://forums.rpcs3.net/

**Comment by NotMyKoDa** [comment]
>this is not place for such problems
Well it's here now.

**Comment by hcorion** [comment]
I looked through the log you provided and I didn't see any errors about rap files?
Have you tried this build: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-5838/artifacts

**Comment by NotMyKoDa** [comment]
Ah, sorry didn't clarify properly. The log I provided was because I was told that these .sprx files would be decrypted as the game boots and would then be loaded with the game. The log was to show that none of the files were ever loaded nor did it ever mention that they were decrypted either.

Yes, I have tried that build as well.

Here's a log where I tried to decrypt all the sprx files inside my game folder.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1243802/RPCS3.zip)

**Comment by RipleyTom** [comment]
They are decrypted in memory.
There is no issue here.

**Comment by NotMyKoDa** [comment]
Oh well. Boop

**Comment by zephirusgit** [comment]
the rap file ussualli is used to decript contents, from pkg files, their go copy in rpcs3 folder called
dev_hdd0\home\00000001\exdata\ (example) EP0102-NPEB01187_00-HDDBOOTTBHRUE0001.rap 
and inside have a key to decrypt, 
but not have idea were download it or how make it. 
ussually come adjunt whit the pkg file
