### ISSUE TITLE
Resonance of Fate [NPEB01348] RSX: Depth texture bound to pipeline with unexpected format 0x91

### ISSUE THREAD

**Issue by machomuu** [RPCS3/rpcs3#3302]
This error seems to come up after the first cutscene upon starting a new game.  Several times.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1243699/RPCS3.zip)

After that the game hangs and, at least that I've found, there aren't any workarounds to the issue.  Admittedly, at least from what I saw in the compatibility thread, it does progress further than it did back when it initially earned the "Intro" status since that was a different issue.

**Comment by kd-11** [comment]
Shouldn't cause crashes. I should lower severity to warning instead since people are panicking over this message. It only affects how the shader processes depth textures which might only affect shadows or depth testing issues.

**Comment by kd-11** [comment]
I'll close this since that game seems to have other issues not related to this that keep the game from running.
