### ISSUE TITLE
Sometimes RPCS3 crashes right after doubleclick-to-fullscreen

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#3304]
This happens for me with Demon's Souls, and [probably] only with Vulkan.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1244405/RPCS3.zip)

**Comment by RaulDJ** [comment]
For me, it crashes every single time I try to start a song on Project Diva DT 2nd or Extend when on fullscreen:

[PDDT2nd.zip](https://github.com/RPCS3/rpcs3/files/1246540/PDDT2nd.zip)

Ar noSurge also crashes randomly on fullscreen:

[ANS.zip](https://github.com/RPCS3/rpcs3/files/1246541/ANS.zip)

This started happening two or three weeks ago and does not happen when not using fullscreen.

**Comment by kd-11** [comment]
The log wont help catch segfaults, only a stacktrace can. If the crash is in the graphics driver it usually comes from the present function. If its just in 'rpcs3.exe' it should be a simpler to fix emulator crash, but a stacktrace will still be needed. You may obtain one by running rpcs3 from visual studio or using gdb on linux.

**Comment by isshininu** [comment]
You mean crash dumps with ".dmp" extension?

**Comment by kd-11** [comment]
That can also work sometimes. Not sure how reliable they will be especially with appveyor builds.

**Comment by RaulDJ** [comment]
Well, I tried using Visual Studio to get a dump but I have absolutely no idea on how to do it.

At least I figure out this problem happens only when the screen refresh rate is set to 60Hz or lower. When it's higher than that, even when playing on fullscreen, there seems to be no problems whatsoever.

**Comment by isshininu** [comment]
[rpcs3.exe.10404.zip](https://github.com/RPCS3/rpcs3/files/1247971/rpcs3.exe.10404.zip)
This is dump created by Windows 10. Affiliated with the log i've uploaded in first post.

**Comment by paulsapps** [comment]
For dump to be useful you need the PDB's - not sure if they get published with the build or not.

**Comment by kd-11** [comment]
Appveyor doesnt generate pdbs afaik which complicates things. Dump might still be useful in a limited way since the asm is still there, but still quite inconvenient.

**Comment by isshininu** [comment]
Hm. I have vsync enabled through nvidia driver too...

**Comment by kd-11** [comment]
I doubt that works with vulkan though. Is your fps truly locked to refresh rate?

**Comment by RaulDJ** [comment]
@kd-11 Yes they are, but only if you force it through the driver, because as I said, the setting in RPCS3 does nothing.

**Comment by isshininu** [comment]
I am starting to investigate this, using VS debugger.
First of all, using these settings - [config.zip](https://github.com/RPCS3/rpcs3/files/1299453/config.zip)

i get countless spam of this exception:
![72](https://user-images.githubusercontent.com/6324523/30378607-d55bd974-98a4-11e7-8159-2ae827e4ec9d.png)

**Comment by isshininu** [comment]
OK, got it.
Program crashes when entering fullscreen.

![73](https://user-images.githubusercontent.com/6324523/30379301-153286c2-98a7-11e7-9ebe-fd23fc49cf02.png)

Could be related to: https://github.com/RPCS3/rpcs3/issues/3073

Similar issue cause crash in: https://github.com/RPCS3/rpcs3/issues/3438 (at least the same line of code, where exception was thrown)

**Comment by kd-11** [comment]
This is a known issue with nvidia drivers. Will resume investigations after the pipeline rewrite in fbo_fixes are done.

**Comment by Megamouse** [comment]
please retry

**Comment by RaulDJ** [comment]
This is totally fixed for me right now, GTX 1060.

**Comment by Asinin3** [comment]
Fixed for me too with nvidia drivers, tested it with builds from kd-11 and now the fix was merged to master.

**Comment by pepodmc** [comment]
Im having this problem, if I force Vsync from nvidia panel , all games crashes at some point when im playing.

Windows 10 PRO
Geforce 750 TI
8gb Ram
core i3 4170  3,7ghz

Using Vulkan renderer
