### ISSUE TITLE
0xC0000005: Recompiling EBOOT (possible bad file)

### ISSUE THREAD

**Issue by NoFriendsThatSlav** [RPCS3/rpcs3#3306]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000018 at 0000000000c18e62.
Instruction address: 0000000000c18e62.
Function address: 0000000000c1894e (base+0xc0894e).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------
log: https://openload.co/f/CuixSjM2xfE/RPCS3.log
GPU: GTX 980 Ti
CPU: Intel Core i7-3770K
RAM: 16 GB
OS: Windows 10 Pro 64bit

**Comment by kd-11** [comment]
You've edited your config to disable logging. Also, you don't explain how the error happens, what causes it, if its spurious or reliably recreated, etc.

**Comment by NoFriendsThatSlav** [comment]
Whoops, didn't realize I did, here's the new log: https://openload.co/f/msLv4UsURug/RPCS3.log.
It happens when ever I try to launch any game with the PPU recompiler, it also sometimes gives me a 0x80000005 error too, alongside with the other one.

**Comment by AniLeo** [comment]
0x80000003 0x80000005 or 0xC0000005?

This looks like a bad/corrupted EBOOT. Can you try ripping your disc again?
Also, clear the contents of data\BLUS31604 to have LLVM recompile it again.

**Comment by NoFriendsThatSlav** [comment]
I ripped the disc again and cleared the contents of the data folder. Yet I still get the same error along with the other which follows:

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault writing location ffffffffffffff8c at 000000000188bf60.
Instruction address: 000000000188bf60.
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault writing location ffffffffffffff8c at 0000000000e242f5.
Instruction address: 0000000000e242f5.
Function address: 0000000000e23d60 (base+0xe13d60).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

**Comment by AniLeo** [comment]
Nothing is wrong on the log, it has to be a corrupted EBOOT. 
What's the checksum for your EBOOT.bin?

**Comment by scribam** [comment]
@NoFriendsThatSlav Still an issue? What is the checksum of your EBOOT.bin file?

**Comment by AniLeo** [comment]
Inactive issue. Closing as invalid, assuming it's a bad file.
