### ISSUE TITLE
blackscreen on opengl in a few games 0.0.2 -5134

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#3308]
in Skydrift, Puzzlegeddon,Crimsonland and lots of other games the screen is black but you can hear the music
i have come across 35 games so far (all PSN) with the same problem
ok then i have tested on the master builds
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-5133/artifacts
was the last good version they worked on
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-5134/artifacts
is when the bug appeared.

**Comment by Asinin3** [comment]
Have you tried enabling write color buffers or strict rendering mode?

**Comment by benderscruffy** [comment]
yes and there was no change

**Comment by AniLeo** [comment]
Invalid report. 
"0.0.2 767" and "0.0.2 768" are not even existing versions.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by benderscruffy** [comment]
of course they are existing versions
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.2-767
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.2-768
so how could it be an invalid report ?????

**Comment by AniLeo** [comment]
Those aren't even master builds. There are no master builds with that versioning. 

Regressions have to be bisected on master, not on forks. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by benderscruffy** [comment]
and if you look in this issue
https://github.com/RPCS3/rpcs3/issues/3257
kd -11 was asking him to use an old version of his
he didnt ask about master builds

**Comment by AniLeo** [comment]
He asked specifically to test his fix to see it would solve that issue, unrelated to this issue. 

Regressions have to be tracked on master, enough already 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by benderscruffy** [comment]
ok then i have tested on the master builds
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-5133/artifacts
was the last good version they worked on
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-5134/artifacts
is when the bug appeared

**Comment by AniLeo** [comment]
5133 isn't a master build, previous master to 5134 is 5119.

This means there's a possible regression on #2962 if testing was accurate

**Comment by benderscruffy** [comment]
so far i have come across over 20 games (all PSN) and still counting with this problem

**Comment by aakh1361** [comment]
@benderscruffy 
You must used of forum for solved your problem
https://forums.rpcs3.net/index.php

**Comment by benderscruffy** [comment]
@aakh1361 
what for ???
i know which build broke the games if you read in my first post so now it is up to the developers to fix it whenever
