### ISSUE TITLE
NCAA Football 14 Crash After Opening Sequence

### ISSUE THREAD

**Issue by PSG-Sparrow** [RPCS3/rpcs3#3312]
Runs over 65+ FPS in opening sequence
(Crash @ End Of Opening Sequence) 
--Using -CPU--
LLVM
ASMJIT
Preferred SPU Threads (1)
Enable SPU Loop Detection
Firmware 4.81
load liblv 2.sprx
-------------------------------------------------------------------------------------------------------------------
Crash report
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault writing location 0000000049dbf010 at 00000000001941cc.
Instruction address: 00000000001941cc.
Function address: 0000000000194120 (base+0x184120).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.
-------------------------------------------------------------------------------------------------------------------
Other errors after starting game
------------------------------------
RPCS3 v0.0.3-3-c7c0139 Alpha
AMD A4-5000 APU with Radeon(TM) HD Graphics  | 4 Threads | 7.47 GiB RAM | AVX
E {PPU[0x1000005] Thread (tib:) [0x01dc5090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR//qkl_cache.ast” [1]
E {PPU[0x1000005] Thread (tib:) [0x01dc5090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR//qkl_cache.ast” [2]
E {PPU[0x1000005] Thread (tib:) [0x01dc5090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///indexedassets.txt” [1]
E {PPU[0x1000005] Thread (tib:) [0x01dc5090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/indexedassets.txt” [1]
E {PPU[0x1000005] Thread (tib:) [0x01dc5090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/ps3/indexedassets.txt” [1]
E {PPU[0x1000005] Thread (tib:) [0x01dc5090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/ps3/speech/indexedassets.txt” [1]
E {PPU[0x1000005] Thread (tib:) [0x01dc5090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/ps3/speech/pa/indexedassets.txt” [1]
E {PPU[0x1000005] Thread (tib:) [0x01dc5090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/ps3/speech/pchat/indexedassets.txt” [1]
E {PPU[0x1000005] Thread (tib:) [0x01dc5090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR///data/ps3/speech/tv/indexedassets.txt” [1]
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f00c] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f018] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f020] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f030] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f03c] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f040] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f050] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f068] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f078] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f080] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f090] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f094] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f0c0] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f0cc] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f0d0] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f104] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f108] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f110] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f114] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f128] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f134] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3fd34] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3fd34] Function call without $LR
E {SPU[0x2000003] Thread (Render-Ant-Sim-Comp-Movie 4/5)} SPU: [0x3fd34] Function call without $LR
E {SPU[0x2000001] Thread (Render-Ant-Sim-Comp-Movie 2/5)} SPU: [0x3fd28] Function call without $LR
E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: unknown origin (0)
E {PPU[0x1000005] Thread (tib:) [0x01dc5090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR//data/common/debugmanager.ini” [1]
E {PPU[0x1000005] Thread (tib:) [0x01dc5090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR//data/common/debugmanager.ini” [2]
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f74c] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f74c] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f758] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f758] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f7e8] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f8a0] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f8b4] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f8cc] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f8e0] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3fb10] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3fb34] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3fbf0] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f104] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f108] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f110] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f114] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3fdf0] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f718] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f740] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f53c] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f794] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f7a4] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f020] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f030] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f03c] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f040] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f050] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f068] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f078] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f080] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f090] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f094] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f0c0] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f0cc] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f0d0] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f128] Function call without $LR
E {SPU[0x2000004] Thread (Render-Ant-Sim-Comp-Movie 5/5)} SPU: [0x3f134] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f634] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f664] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f57c] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f594] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f4c8] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3f4e0] Function call without $LR
E {SPU[0x2000002] Thread (Render-Ant-Sim-Comp-Movie 3/5)} SPU: [0x3fcc4] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f8f0] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f9b8] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f5b0] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f5b4] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f5c0] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f5cc] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f5e0] Function call without $LR
E {SPU[0x2000000] Thread (Render-Ant-Sim-Comp-Movie 1/5)} SPU: [0x3f60c] Function call without $LR
E {PPU[0x1000013] Thread (LoopCore) [0x016d2a80]} 'cellKbClearBuf' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [1]
E {PPU[0x1000013] Thread (LoopCore) [0x016d2a80]} 'cellKbClearBuf' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [2]
E {PPU[0x1000013] Thread (LoopCore) [0x016d2a80]} 'cellKbClearBuf' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [3]
-------------------------------------------------------------------------------------------------------------------
Can someone look at my game files and see if they are OK?
I will upload @Mega if yes.

**Comment by AniLeo** [comment]
**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net) for that.

The issue has been marked as **Invalid** and closed.

**Comment by PSG-Sparrow** [comment]
What is the problem? 
And whet is Meta invalid? 
Are you accusing me of something?
I am only submitting a test on NCAA FOOTBALL 14 to show the errors so nobody is asking for support.
I am asking for a file check to make sure these errors are legit.
