### ISSUE TITLE
Vulkan crashes (AMD)

### ISSUE THREAD

**Issue by CrestfallenWarrior** [RPCS3/rpcs3#3316]
So I'm trying to play Demon's Souls, and after about 10 seconds ingame the entire screen freezes, then it goes black for a few seconds and windows start working again, but the emulator stays frozen.

I'm already with the latest versions of Vulkan and AMD radeon drivers.

System; Ryzen 5 1600, RX470, Windows 10

**Comment by danilaml** [comment]
Looks it's the same issue I had introduced by the shader cache PR: https://github.com/RPCS3/rpcs3/issues/3243#issuecomment-323813610. @kd-11 has managed to identify the issue, but it looks like he is yet to submit the fix.

**Comment by CrestfallenWarrior** [comment]
Interesting, seems like waiting is all that's left for me then.

**Comment by rhythmthief** [comment]
It appears to be hardware-related. I have been experiencing the issue since before the vertex rewrite, and it is persistent across multiple operating systems (tested on W10 and Linux with the latest kernel running Mesa drivers).

**Comment by kd-11** [comment]
Please retest. It should be fixed. If AMD still crashes under linux but not on windows let me know so the workarounds can be extended to linux as well.

**Comment by rhythmthief** [comment]
Can confirm that it's fixed on Windows but still crashes under Linux. Thanks for looking into it!

**Comment by AniLeo** [comment]
Linux issue solved by #3629, closing as fixed

Feel free to reopen the issue if such fix didn't work for you
