### ISSUE TITLE
Persona 5 Black Screen nothing happend

### ISSUE THREAD

**Issue by NghiaPhamJF** [RPCS3/rpcs3#3318]
Today i tried Persona 5 on RPCS3 but it appear black sreen no matter i change to vulkan or OPEN GL. First time i thought the game is loading so i waited extacly 30mins but nothing happend then. Only fps active around 28 ~ 30 fps. Then i try Street Fighter II Turbo HD Remix (Vulkan and open GL) it's work perfectly with 60 fps no lag. Can anyone teach me how to config setting? :( i would play Persona 5 even it has 4 - 5 fps. (Sorry for bad Eng and this is my 1st time here so if i have any fault you can tell me don't delete my post in silent okay? :( ) Thank You for reading.
My specs:
- i3 - 4150
- GTX 950 2GB DDR5
- 8GB ram

**Comment by AniLeo** [comment]
**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net) for that.

The issue has been marked as **Invalid** and closed.     

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
