### ISSUE TITLE
F {MFC Thread} MEM: Access violation reading location 0x1606080

### ISSUE THREAD

**Issue by luisloco** [RPCS3/rpcs3#3320]
![error 1](https://user-images.githubusercontent.com/5092869/29742242-f616eee6-8a40-11e7-8bf5-6bd909f7dc08.png)

log
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1253727/RPCS3.zip)

**Comment by SakataGintokiYT** [comment]
@luisloco 
Load liblv2.sprx only

**Comment by luisloco** [comment]
@SakataGintokiYT  Thanks working

**Comment by AniLeo** [comment]
This is not the forums. Use the forums for support unless you know what you're doing.
