### ISSUE TITLE
Nier Replicant [BLJM60223]: Major graphic problem

### ISSUE THREAD

**Issue by Illynir** [RPCS3/rpcs3#3321]
Hello,

We can pass the prologue with Write color buffer (else all is too white) but after that, the game is black and purple. Same problem on OpenGL, Vulkan, With strict order rendering ON or OFF, Write buffer color ON or OFF.
Game will be playable without that...

Windows 10
I5 4670K
8 Go DDR3
Nvidia GTX 1050 Ti 4Go

Screenshot of problem:

![unknown](https://user-images.githubusercontent.com/22648460/29742920-f51457da-8a87-11e7-9f15-a8ff3245d2da.png)

Also, Spam of that in log:
E {rsx::thread} RSX: Unsupported RTT scaling factor: dst_pitch=5120 src_pitch=3072

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1253785/RPCS3.zip)
[shaderlog.zip](https://github.com/RPCS3/rpcs3/files/1253786/shaderlog.zip)

**Comment by Sandvichero** [comment]
![capteure](https://user-images.githubusercontent.com/26612410/29783382-29526b2e-8bee-11e7-942a-c4482937d93e.PNG)

The areas after that one seem to render fine.

**Comment by Sandvichero** [comment]
This problem is fixed as of the latest RSX fixes
![nier](https://user-images.githubusercontent.com/26612410/30718236-4d29753a-9eed-11e7-939b-9a9bfa3421a7.PNG)

**Comment by Illynir** [comment]
Fixed yes and no, closed too rapidly.

Look the game now:

![image](https://user-images.githubusercontent.com/22648460/31050673-278b6420-a652-11e7-8bcd-fba3a3a914bc.png)

Last master build.
