### ISSUE TITLE
Deception IV: Blood Ties - graphics artifacts

### ISSUE THREAD

**Issue by Vlakipn** [RPCS3/rpcs3#3322]
Related to #3200 change. Before that, traps were black and some objects (like lamps, trap triggers) were missing, same as healing and jump pads light. Now everything mentioned above is present (which is actualy very good), but, trap triggers are now green-yellow color and produces artifacts as you will see in video below. Tested with Master and rsx/vp: ARL fix build, result is same. Blood is also colored in green (should be red), but it wasnt present at all before change. 

Current state :  https://youtu.be/Eu9naVigU4I
How it was before #3200 :  https://youtu.be/JPlsa8LSVEs
How it should look :   https://youtu.be/otcuExaxtR4

Log file:
https://www.mediafire.com/file/vmg06tgakz61bgl/RPCS3.zip

**Comment by Vlakipn** [comment]
So, #3200 effect on this game:
Pros:
Lights from jump and heal pads are visible now
Blood is visible
Some other objects (wall lamps) and room effects (dust or something like it) are also visible
Trap triggers arent black anymore (and room trap triggers are also visible)

Cons:
Artifacts appeared (trap triggers probably causing them)
Blood is green

Basicly this change is very good, problems that brought with it are minor comparing to improvement.

**Comment by kd-11** [comment]
If you're on nvidia, try updating to the latest driver - another user had similar artifacts that got fixed by moving to the current driver.
If that doesnt fix it, its likely broken attribute format decode which is alot harder and will need a renderdoc capture but also needs https://github.com/RPCS3/rpcs3/pull/3315 merged first.

**Comment by Vlakipn** [comment]
Yes im on nVidia gtx970 - driver 385.51 (released 2 days ago - latest), its same. 
Guess ill wait for merge and test.

**Comment by Vlakipn** [comment]
Hopefuly its right @kd-11 

renderdoc
https://www.mediafire.com/file/kz2nwt65ak1oy1m/RDC.7z

**Comment by Vlakipn** [comment]
Here is new renderdoc done with latest master (#3315 merged meanwhile).
https://www.mediafire.com/file/4k5qsgz9nkca4tf/RDCC.7z
Please let me know if i did something wrong @kd-11  (first time using that app)

**Comment by kd-11** [comment]
I forgot to ask, does it flicker when using openGL? There are bugs in the new vulkan implementation that was introduced with #3200

**Comment by Vlakipn** [comment]
It does (acting absolutely same as Vulkan)
![desktop 28-aug-17 18-02-34-166](https://user-images.githubusercontent.com/8547420/29781962-310d27b4-8c1b-11e7-9d21-a3c42e5b1040.png)
![desktop 28-aug-17 18-02-32-224](https://user-images.githubusercontent.com/8547420/29781963-31118e6c-8c1b-11e7-9c33-d24634f0d37a.png)

**Comment by Vlakipn** [comment]
Also i saw someone opened issue with report that some games has green like layer, this one has it too.

**Comment by bjakja** [comment]
I tested Deception 4 Nightmare princess on latest fbo fixes 2afbb1ac, and this artifacts are gone. It now shows "towers" of traps but still not properly.

**Comment by MarioSonic2987** [comment]
Any change?

**Comment by bjakja** [comment]
Fixed lighting and fps drops from 2 to 0.8 on Nightmare Princess.

**Comment by MarioSonic2987** [comment]
@bjakja Could you retest this? Graphics should be better since then.

**Comment by Vlakipn** [comment]
Ive tested this, artefacts are gone, graphics much much better, but still, totaly unplayable. 
Cant even do workarround as before to reach some 'playable' fps.

**Comment by bjakja** [comment]
I have tested Nightmare Princess and something that stick from her back is fixed but rest is still in mess.

**Comment by digitaldude555** [comment]
![screenshot 2189](https://user-images.githubusercontent.com/26138653/53370690-1512c380-3957-11e9-84b3-018e90175cbd.png)
![screenshot 2191](https://user-images.githubusercontent.com/26138653/53370691-1512c380-3957-11e9-830e-3cd44e169ec0.png)
@bjakja @Vlakipn retest please it seems graphically fine now, but I can't confirm with the exact same level you were in.

**Comment by Vlakipn** [comment]
Havent tested RPCS3 a while. But..
With ASMJIT i cant get long ingame because it crashes for me nearly after starting it. Therefor im unable to confirm graphic improvements.
Gotta test other compiler too and will provide infos here.

**Comment by digitaldude555** [comment]
Test with spu fast and disable spu cache.

**Comment by bjakja** [comment]
I can only go ingame on asmjit, and from what I see almost all bugs are fixed instead of brightness.

**Comment by digitaldude555** [comment]
@bjakja @Vlakipn  should work with asmjit now.

**Comment by AniLeo** [comment]
The graphical issues reported are already fixed as indicated above. If there are any remaining issues, please submit a new issue for those issues specifically testing on the latest build.
