### ISSUE TITLE
GL/Vulkan: Afro Samurai  / Broken graphic

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#3323]
EDIT:
-update

**[OpenGL]**
![gl](https://user-images.githubusercontent.com/13681488/40170487-df322012-59c8-11e8-8078-c3291c74e9af.png)
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2012679/RPCS3.log.gz)

-----------------------------------------------------------------------------------------------------------

**[Vulkan]**
![vk](https://user-images.githubusercontent.com/13681488/40170970-3ea73d6a-59ca-11e8-81f8-d1bd79704d04.png)
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2012689/RPCS3.log.gz)

**Comment by kd-11** [comment]
I'd say the zero dimension textures are a cause for concern. I'll see about implementing a stable workaround.

**Comment by gatsuslayer** [comment]
Is there any build that fixes this issue?

**Comment by gatsuslayer** [comment]
Is there any build that fixes this issue?

**Comment by SakataGintokiYT** [comment]
@pauls-gh 
Can you look at this issue?
Link for demo:(451MB)
https://store.brewology.com/demos.php?letters=abcd

**Comment by Emulator-Team-2** [comment]
@kd-11 
**OpenGL: (50MB) --> [RSX Capture](https://mega.nz/#!4EBh1bjZ!KqaZ1vNIGfrCU2eik6CxGia0mzNuObMC4H11JhYEqP4)**

**Comment by kd-11** [comment]
I'm looking into this.

**Comment by Emulator-Team-2** [comment]
**Fixed #4844**
![bez tytulu](https://user-images.githubusercontent.com/38318848/42178255-e945f82c-7e2f-11e8-92e1-47e0968c4082.png)
