### ISSUE TITLE
Vulkan and Direct3d not showing in the render option

### ISSUE THREAD

**Issue by ZeNiTh264** [RPCS3/rpcs3#3325]
Help, I do not have the option of vulkan and direct3d in the render option. I have windows 10 

https://user-images.githubusercontent.com/31377349/29745961-177545c4-8aa0-11e7-9f2b-5150ff8a6496.jpg

**Comment by AniLeo** [comment]
User fault. Update your drivers, this assuming your hardware does support Vulkan.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
