### ISSUE TITLE
Hard Corps: Uprising [NPUB30096] randomly crashes on Vulkan

### ISSUE THREAD

**Issue by jabroany** [RPCS3/rpcs3#3330]
Hard corps: Uprising [NPUB30096]

Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz | 8 Threads | 7.88 GiB RAM | AVX | GTX 770
RPSC3 v.0.0.3.3-dfc970c Alpha
Only non-default setting is: Vulkan and load liblv2.sprx only

Game randomly hangs - it's happened on level 1 and once it didnt happen at all through out 5 levels until game over. Music keeps playing (but no other sound - in other words the gameplay isnt active). In general it happens quite frequently. Always the same error in the log.

Playing in OpenGL the crash doesnt happen even once. I've included the log

https://www.sendspace.com/file/v7cwd9

**Comment by raveskirza** [comment]
Please try with an older build i.e 0.0.3-5891 from the below link
https://rpcs3.net/compatibility?b
The latest builds are probably crashing the nvidia driver.

**Comment by jabroany** [comment]
I've already tested it with an older version:
rpcs3-v0.0.3-2017-08-17-9d1aebce_win64

Same results

**Comment by kd-11** [comment]
Needs thread inspection which isnt possible without attaching a debugger. Sometimes hangs will happen when framerate goes above some threshold so it might not actually be related to the renderer. Either way, need to know what rsx::thread is executing when the game hangs.
I have not seen the `Invalid RSX method` error in the log so I dont think its basic RSX lock desync

**Comment by jabroany** [comment]
Whether the crash happens or not the FPS is the same (capped at just over 60). I've tried lowering the limit to 50, indeed the crash happened at just over 50 (like 50.52 or something) FPS. For that reason I don't believe a framerate threshold is the problem.

As for the debugger - I unfortunately don't know how to properly use it, and I can't seem to find a guide to do it.

**Comment by jabroany** [comment]
This isn't proper reporting, I don't know which commit caused this, but when I tried in RPCS3 v0.0.3-3-e7db0c7 Alpha (23rd september) the freezing bug is completely gone!

On the other hand shadow issues occur, which are only significant in stage 6 where there is a chance the whole background becomes black (which is used for some part of the stage). But at least the random freezing stopped!

**Comment by kd-11** [comment]
Use the invalidate cache option to fix corrupted shadows. The nvidia crashes were fixed a dew days ago so I'll close this. Reopen if issue persists.
