### ISSUE TITLE
RSX: Unknown/illegal instruction: 0x1c (forced unit 1) and 0x1d (forced unit 1) Fear 2 Project Origin Demo

### ISSUE THREAD

**Issue by woj1993** [RPCS3/rpcs3#3331]
Game print RSX: Unknown/illegal instruction: 0x1c (forced unit 1) and RSX: Unknown/illegal instruction: 0x1d (forced unit 1) errors.

Serial NPEB90184
My pc config:
Intel I5 2300 2,8 GHz 4 Cores
4 Gb ram
Asus GT440 1 GB DDR3

Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1254679/RPCS3.zip)
P.S. Game also has horrible audio shuttering so headphone developers warning.

**Comment by AniLeo** [comment]
Don't think it's a relevant error that affects the game

**Comment by kd-11** [comment]
Not a real error, should be a warning. Unless it causes the game to give incorrect visual output (as was the case with 0x17) its doesnt mean much. Games with terrible audio can have audio fixed by shifting CPU resources over to the SPU threads - Disable lower SPU thread priority and also disable SPU loop detection. This will speed up SPU emulation but the hit to the PPU cores and RSX thread will usually tank performance.

**Comment by woj1993** [comment]
@kd-11 I think it gives graphical issues. Demo is randomly flashing for about 0,5 of a second with random color. I don't see it on YouTube videos from game. It may not be this but it is only error in log I think that affect graphic.

**Comment by kd-11** [comment]
Does the flashing happen with openGL as well? Skipping computation instructions after wrong fence instruction has always been there and is not recent.

**Comment by SakataGintokiYT** [comment]
@woj1993 
Disable Strict Rendering Mode

**Comment by woj1993** [comment]
@kd-11 Flashing happens in OpenGl I can't test Vulcan
@SakataGintokiYT  Flashing happens without strict rendering mode and game have other errors in game (z fighting, flashing textures) but strict rendering mode has this error in movies and in game has other error it shutters (pause emulation for 1 second and continue randomly) [Turning SPU loop detection off fixes (make less visible?) shutters].

@AniLeo Somthing like this is happening.
https://www.dropbox.com/s/glz6mk5vgx5tlhr/rpcs3_2017_09_06_18_53_51_716.mkv?dl=0
Video: Warning turned upsidedown by catching program. Game is not turned upsidedown.

**Comment by SakataGintokiYT** [comment]
@woj1993 
What graphic driver version you have installed ?

**Comment by MoochMcGee** [comment]
@woj1993 If you want to make extended use of RPCS3, you're going to have to
upgrade your machine. Might I recommend the GeForce GTX 750 Ti? It's a very
good card, and it's only $60-70 used.

**Comment by woj1993** [comment]
@MoochMcGee Yeah I know but for now I don't have money. Computer probably shouldn't make this error?
