### ISSUE TITLE
Dragon's Crown fatal error

### ISSUE THREAD

**Issue by Diphy** [RPCS3/rpcs3#3332]
I started up Dragon's Crown today and this popped up 

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault writing location 0000000000000000 at 0000000000000000.
Instruction address: 0000000000000000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------
Specs https://prnt.sc/dlbxk6

Any help?

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
