### ISSUE TITLE
·F 0:01:03.454020 {PPU[0x1000000] Thread (main_thread) [0x007a2920]} St13runtime_error thrown: Verification failed (e=110): 

### ISSUE THREAD

**Issue by miguel-nunes** [RPCS3/rpcs3#3336]
·F 0:01:03.454020 {PPU[0x1000000] Thread (main_thread) [0x007a2920]} St13runtime_error thrown: Verification failed (e=110): 
(in file /home/mnunes/apps/rpcs3/rpcs3/Emu/Cell/lv2/sys_lwcond.cpp:192)

Game: BLUS30793

Symptoms: After the last commits, the games started to have audio issues and when is building shader cache, crashes.

The name of the issue is the last entry in the log when the issue happens.

Follows the logs.

--
Micaelis
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1257068/RPCS3.zip)

**Comment by AniLeo** [comment]
Game has recently been reported as Playable at https://forums.rpcs3.net/thread-197235.html

Please confirm whether it is still or not an issue for you. 
If issue enters inactivity will assume fixed and close it.

**Comment by miguel-nunes** [comment]
Ani,

Is playable, and shows correct graphics with both renders ( Vulkan and 
OpenGL ) in Windows.
In Linux, only OpenGL displays correct graphics. Vulkan have some 
artifacts. Some textures got blurred. ( This is more noticable in the 
final of a fight, when some actions got completely blurred).

I can't generate a screenshot now, but I will provide one as soon as 
possible.

Cheers!

**Comment by AniLeo** [comment]
Thanks for confirming. 

Please open a separate issue reporting on the discrepancies between Windows / Linux graphics in Vulkan for the game.
Don't forget to indicate used drivers for both system and OS versions.

Closing this one since it has been solved.
