### ISSUE TITLE
The evil Within E {rsx::thread} RSX: Failed to compile shader: ERROR: 0:112: 'r8' : syntax error syntax error

### ISSUE THREAD

**Issue by luisloco** [RPCS3/rpcs3#3338]
![1](https://user-images.githubusercontent.com/5092869/29786084-6cd83bf2-8bef-11e7-8970-62970229ecb2.png)

![2](https://user-images.githubusercontent.com/5092869/29786089-7244cbbe-8bef-11e7-9912-d9d6279ef45f.png)

![3](https://user-images.githubusercontent.com/5092869/29786104-825ddd56-8bef-11e7-8b8c-510909a19a60.png)

log
[RPCS3 the evil within.zip](https://github.com/RPCS3/rpcs3/files/1257711/RPCS3.the.evil.within.zip)

**Comment by AniLeo** [comment]
·W 0:00:00.328666 Experimental Build Warning! Build origin: RPCS3/rpcs3/master/=3186
·! 0:00:25.596241 {rsx::thread} RSX: 4.3.0 - Build 20.19.15.4703
·! 0:00:25.596243 {rsx::thread} RSX: 4.30 - Build 20.19.15.4703
·! 0:00:25.596243 {rsx::thread} RSX: Intel

#3313 

Do read the guidelines, don't spam issues.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
