### ISSUE TITLE
PPU LLVM modules get loaded while using PPU interpreter

### ISSUE THREAD

**Issue by TGEnigma** [RPCS3/rpcs3#3341]
Not sure if it's a GUI bug or a logic bug, but it happens.
Launching an uncached game seemingly also compiles LLVM modules? But the time taken is very short, so it seems something is amiss.
This happens on both interpreter modes.

**Comment by AniLeo** [comment]
How to reproduce? 

(Also don't tell me you're using per game config)

**Comment by TGEnigma** [comment]
Nailed it. I apologize, I didn't realize the per game config was active. Might be worth adding some kind of notification upon boot though, similar to what Dolphin does.
