### ISSUE TITLE
No Vulkan on Linux version

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3342]
There is no Vulkan on Linux version, but my video card supports Vulkan and Windows version of RPCS3 has it.
![1](https://user-images.githubusercontent.com/14265316/29798639-deca13b2-8c66-11e7-95c2-61cb2192e5c2.png)
Is it a bug or Vulkan doesn't work yet on Linux? I remember that you had "enable Vulkan on Linux" on the roadmap and closed it.

**Comment by TotalCaesar659** [comment]
I have to test something more.

**Comment by TotalCaesar659** [comment]
I've updated Lubuntu to 16.04.3, the bug remains, so I re-open it.

**Comment by AniLeo** [comment]
There's no useful information on this post. Drivers, GPU.. We can't guess what's the issue if you're the only one having it

**Comment by AccountOneOff** [comment]
Do you have vulkan-utils and libvulkan1 installed?

**Comment by TotalCaesar659** [comment]
Yes, I have them. Lubuntu 16.04.3, Mesa 17.0.7, AMD A8-7410 APU.
