### ISSUE TITLE
Apache Air Assault Rendering Issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3344]
Tested by https://github.com/RPCS3/rpcs3/commit/818df50bb58f87489e28803dbcfe215b2290576f

![apache vk](https://user-images.githubusercontent.com/11453507/29799442-f832dc60-8c63-11e7-9e78-4da361853f22.PNG)

**[RenderDocVK](https://mega.nz/#!HVFSVY5T!vLuokR2ctrlCybIy0ws1bpNJb5HOXU01o1LXVtYBvPY)**
**[RenderDocGL](https://mega.nz/#!2MkyACyC!SiJNiTrv7qIwlFccohZCC6vt9SuidvnN-LZgmEM8mn4)**

**[LOG VK](https://mega.nz/#!6ct10JoC!7K1BZhLm9qpL5HePvzHItz6GipiiDqZLh7OsI8tSs6I)**
**[LOG GL](https://mega.nz/#!SENRwZ6Z!DsR-HNfEBhTDbowNdcpDF-31PJc8lYik_bKO66v-qjQ)**

**Comment by digitaldude555** [comment]
![Screenshot (2352)](https://user-images.githubusercontent.com/26138653/55673883-8d559880-58b6-11e9-82cf-d58434f32c5e.png)
Graphics work now with wcb. Can close it now.

**Comment by TheOnePersonYouHate** [comment]
I just have a black screen when loading into training. I can see some HUD elements but nothing more. Tried using OpenGL and Vulkan. Can't get it show anything. Advice?
