### ISSUE TITLE
GL/VK Untold Legends: Dark Kingdom Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3345]
Tested by https://github.com/RPCS3/rpcs3/commit/818df50bb58f87489e28803dbcfe215b2290576f

**PS3:**
![untold 1 real](https://user-images.githubusercontent.com/11453507/29802630-d586d05a-8c76-11e7-8f2a-e2b5dae49fa6.PNG)

**RPCS3:**
![untold 1](https://user-images.githubusercontent.com/11453507/29802542-2dad481e-8c76-11e7-8fff-92be0513c5a0.PNG)

**[RenderDoc GL](https://mega.nz/#!GBU1zCRT!DzsMk9umxUXb0PmV30fS_422iByBM_ZJJhh3PqL2myE)**
**[LOG](https://mega.nz/#!bBtlRBAA!tKOwaVWo2jt2TEiszZJDvciibHGaUoDzFlCFA5yRhGs)**

**Comment by AniLeo** [comment]
What if you use Strict Rendering Mode?

**Comment by JohnGodgames** [comment]
Will fix text only...

**Comment by digitaldude555** [comment]
![screenshot 1647](https://user-images.githubusercontent.com/26138653/51085041-729ed800-173c-11e9-800c-2b6c2ab27eb7.png)
![screenshot 1648](https://user-images.githubusercontent.com/26138653/51085042-73d00500-173c-11e9-9feb-e7f4b914c881.png)
Vulkan and OpenGL fixed can close the issue.
