### ISSUE TITLE
GL/VK Army of Two: The Devil's Cartel - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3351]
Tested by https://github.com/RPCS3/rpcs3/commit/64a6fbe39ff089d0155a36aeb0d3c6360d223ad9

**Real HW:**
![army devils gl real](https://user-images.githubusercontent.com/11453507/29821405-110fc810-8cc8-11e7-965f-b6801ac298a3.PNG)

**RPCS3 GL:**
![army devils gl](https://user-images.githubusercontent.com/11453507/29821410-13e56ab8-8cc8-11e7-8d46-23a61f2ed115.PNG)

![army devils gl rd](https://user-images.githubusercontent.com/11453507/29821507-77abddd4-8cc8-11e7-8799-e3c33409e267.PNG)

**[RenderDoc GL](https://mega.nz/#!eEVQ1RpY!oxvC5PUC8MI2k0H92cASOisiYWMI4_zqGh2gzbi5vIA)**
**[LOG GL](https://mega.nz/#!fINjCY4L!GU20SmgkjB5XYbqD7F8L2sYC6tbkaipEb_s-PKskhzM)**

**Comment by AniLeo** [comment]
Can you retest in latest master? Latest RSX changes fixed several graphical bugs in this game.

**Comment by Asinin3** [comment]
Tried to re-test this for awhile but couldn't get ingame or into the menus. Had a bunch of different errors, I know this issue is seperate but I posted log here anyway.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1367721/RPCS3.zip)

**Comment by AniLeo** [comment]
This specific menu needs retesting

**Comment by kd-11** [comment]
Closing due to years of inactivity.
