### ISSUE TITLE
GL/VK Army of Two: The 40th Day - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3352]
Tested by https://github.com/RPCS3/rpcs3/commit/64a6fbe39ff089d0155a36aeb0d3c6360d223ad9

**Real HW:**
![army of two 40 th day gl real](https://user-images.githubusercontent.com/11453507/29822308-419e8a36-8ccb-11e7-828d-a495ffe6ec4e.PNG)

**RPCS3 GL:**
![army of two 40 th day gl](https://user-images.githubusercontent.com/11453507/29822311-44a54a08-8ccb-11e7-8794-86c614d6cafb.PNG)

![army of two 40 th day gl rd](https://user-images.githubusercontent.com/11453507/29822337-655e992a-8ccb-11e7-8d30-a72a0da0e549.PNG)

**[RenderDoc GL](https://mega.nz/#!GZ9AWT5R!53qqLpKJgPhHtYuV8iTNQC-BzOppyggIxN8vVbBOnbU)**
**[LOG GL](https://mega.nz/#!nVcj1BQL!FJanhSq84u-wz7QZ-m2-Il-2KixifHi2dnwp9zmq_E0)**

**Comment by Asinin3** [comment]
Not sure if you wanted a retest Ani, but since you asked for one on the other Army of Two titles:

![image](https://user-images.githubusercontent.com/15137035/31328396-6b300232-ad1c-11e7-9140-87c0c988b617.png)

**Comment by Asinin3** [comment]
Fixed with #4382 
![mpc-hc64_2018-04-02_125](https://user-images.githubusercontent.com/15137035/38240018-e0d6a8ca-371d-11e8-8e5d-ea93462462c2.jpg)

**Comment by AniLeo** [comment]
Closing as solved
