### ISSUE TITLE
Persona 5 patch causes PPU execution to stall indefinitely

### ISSUE THREAD

**Issue by tge-was-taken** [RPCS3/rpcs3#3353]
The patch is tested and works on console just fine.

How to reproduce:
Use this patch.yml for NPEB02436 (replace the hash with your executable hash), go ingame and load your save.
```
PPU-037b75e17a0d93a8bbda11459839c3061c6b7dd3:

    # .text segment
    # branch to trampoline
    - [ be32, 0x0006CD68, 0x48B44B52 ] # ba 0x00B44B50
    
    # .sceStub.text segment 
    # overwrites one of the unused cellSail import stubs (they're all unused)
    # Rnd() % MaxBgm
    - [ be32, 0x00B44B50, 0x4891DA07 ] # bla 0x91DA04 (Rnd)
    - [ be32, 0x00B44B54, 0x38C0000B ] # li r6, 11 (MaxBgm)
    - [ be32, 0x00B44B58, 0x30860001 ] # addic   r4, r6, 1
    - [ be32, 0x00B44B5C, 0x7C832396 ] # divwu   r4, r3, r4
    - [ be32, 0x00B44B60, 0x7CA431D6 ] # mullw   r5, r4, r6
    - [ be32, 0x00B44B64, 0x7C852014 ] # addc    r4, r5, r4
    - [ be32, 0x00B44B68, 0x7C641810 ] # subfc   r3, r4, r3
    - [ be32, 0x00B44B6C, 0x7C6307B4 ] # extsw   r3, r3
    
    # patch music id
    - [be32, 0x00B44B70, 0xB07E0000] # sth r3, 0(r30) <--- this instruction causes an infinite stall
    #- [ be32, 0x00B44B70, 0x60000000 ] # nop <--- doesn't happen if you nop it, but then the patch doesnt really work either.
    
    # return to normal code
    - [ be32, 0x00B44B74, 0x2C1E0000 ] # cmpwi r30, 0
    - [ be32, 0x00B44B78, 0x4806CD6E ] # ba 0x0006CD6C
```

**Comment by LeZfX** [comment]
@TGEnigma sorry for the probably dumb question but, how do i get the executable hash from a game? :p

**Comment by TGEnigma** [comment]
@LeZfX Right click on the log in RPCS3 and select 'Trace'. After that, launch the game and stop the emulation when you can. The PPU-* hash will be in the log someplace at the very top.

**Comment by RipleyTom** [comment]
First, a sth won't stall anything, it will crash if the memory pointer is invalid or it will work.
Second, you're storing data on a pointer(r30) by putting it before the code that checks if that pointer is valid(yes the cmp r30, 0), that is completely idiotic...

**Comment by LeZfX** [comment]
@TGEnigma got it! Thanks!

**Comment by TGEnigma** [comment]
@RipleyTom Have you tried the patch at all? Good catch, the comparison is what was replaced by the branch, but even so r30 is never 0.

**Comment by dio-gh** [comment]
Needs retesting, this ticket is more than 2 years old. I'll try getting myself to do it tonight.

**Comment by RainbowCookie32** [comment]
The patch on the OP causes an access violation fatal now, tested with PPU LLVM, Fast, and Precise. The same error on all 3 of them

PPU Precise:
`·F 0:01:33.620968 {PPU[0x1000000] Thread (main_thread) [0x00b44b70]} MEM: Access violation writing location 0xb49738`
[P5_Precise.zip](https://github.com/RPCS3/rpcs3/files/3704351/P5_Precise.zip)

PPU Fast:
`·F 0:01:14.213432 {PPU[0x1000000] Thread (main_thread) [0x00b44b70]} MEM: Access violation writing location 0xb49738`
[P5_Fast.zip](https://github.com/RPCS3/rpcs3/files/3704353/P5_Fast.zip)

PPU LLVM:
`·F 1:03:00.790742 {PPU[0x1000000] Thread (main_thread) [0x00b44b54]} MEM: Access violation writing location 0xb49738`
[P5_LLVM.zip](https://github.com/RPCS3/rpcs3/files/3704355/P5_LLVM.zip)

**Comment by elad335** [comment]
Needs updating + reuploading log

**Comment by RainbowCookie32** [comment]
The access violation is still there, and it also still happens on all PPU Decoders. The log is from PPU LLVM, let me know if you want logs from the Interpreters too.

`F {PPU[0x1000000] Thread (main_thread) [0x00b44b54]} VM: Access violation writing location 0xb49738 (read-only memory)`

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4204994/RPCS3.log.gz)

**Comment by elad335** [comment]
Test #9706

**Comment by RainbowCookie32** [comment]
Still crashes
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5909051/RPCS3.zip)

**Comment by RipleyTom** [comment]
It might just be different behaviour because of different scheduling on rpcs3 but like I noted in my previous comment there is a check for nullptr after the pointer is used in the patch...

**Comment by TGEnigma** [comment]
The actual reason this doesn't work is because it's writing to a read-only segment. Real hardware doesn't care about this, however.
The nullptr check is irrelevant due to it being a global assigned at boot.

**Comment by kd-11** [comment]
I think we should close this issue unless there is a reason to keep it open. By the way, as rpcs3 gets ported to more platforms hoping to write illegally to rx memory becomes less and less likely due to modern OS security constraints.

**Comment by illusion0001** [comment]
Yea, we have written bad patches that only work with interpreter, rewriting the logic to not use rx segment fixes the issue
