### ISSUE TITLE
Shader preloading issues

### ISSUE THREAD

**Issue by TGEnigma** [RPCS3/rpcs3#3356]
Multiple problems:

1. Shader preload does not stop immediately if you close the progress dialog for it. It continues compiling until it's done, and then stops and closes the game window.

2. Segfault occurs if you close the game window while preloading shaders. After closing the window, the preloading continues as usual except when it finishes, you're greeted with a segfault.

3. There isn't a way to restart the emulation of a game without reloading all of the shaders. This is really bothersome if you're trying to debug a game and have to reload often.

**Comment by JohnGodgames** [comment]
@kd-11 is there way how to disable shader caching?It's annoying and maybe no boost for me.Caching and preloading is also more time consuming while testing.

**Comment by hcorion** [comment]
@JohnGodgames from what I understand, you can't just disable shader caching (besides using an older build). It's not the caching of the shaders that takes so long. The reason kd-11 introduced shader caching was because the shaders got more complex and were taking too long to compile.

If kd-11 did introduce an option to disable shader caching, it would lag like it does every single time it loads a shader. I believe kd-11 has some optimizations planned, but I'm not sure what's the status on that.

**Comment by Ru4slan** [comment]
@JohnGodgames go to WinHex, to Config.yml and disable this option. In this file you may try enable frame skip.
Change true to false and delete one byte(letter e). This very needs. If you not delete letter e then config file is not valid

**Comment by kd-11** [comment]
Just delete the cache before a run if it takes too long to start up. I'll add a passthrough cache for those who dont need this functionality

**Comment by TGEnigma** [comment]
@JohnGodgames I didn't open this issue with the intent of being able to disable shader caching as it's quite obvious having read the previous updates that this is just a side-effect of processing more on the gpu as opposed to doing it on the cpu, and it kinda detracts from the issues at hand here.

@kd-11 Do you intend for this to be a temporary workaround for the restart issue or is there simply no clean way to reset a game without reloading everything yet?

**Comment by kd-11** [comment]
I just prefer to have all enhancements be toggleable. The shaders cache was due to necessity and I admittedly rushed it a bit so the null alternative is unimplemented. With the current state of shader compilation it is now feasible to use a null cache as stutter is alot less frequent now.

**Comment by kd-11** [comment]
The technical bugs listed here are already fixed. Also with current master, number of shaders has been drastically reduced making the pre-loading a lot faster.
