### ISSUE TITLE
GL/VK Full Auto 2: Battlelines - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3358]
Tested by https://github.com/RPCS3/rpcs3/commit/64a6fbe39ff089d0155a36aeb0d3c6360d223ad9

**Real HW:**
![full auto 2 menu real](https://user-images.githubusercontent.com/11453507/29840637-fa3f738e-8d02-11e7-9bef-ab345b43c3e3.PNG)

**RPCS3 GL:**
![full auto 2 menu](https://user-images.githubusercontent.com/11453507/29840624-f1dbf42e-8d02-11e7-9360-e4046dfffc54.PNG)

**[RenderDoc GL](https://mega.nz/#!7IlgEZpa!S8XrBXVS-DRAnqjc7SvXzLeBCq4gO9rZy_99YGuEwIgU)**
**[LOG GL](https://mega.nz/#!TBE31baK!p0dxKXv7QQGcQKOuHfLmkT-orYxhbOrsvip4kVxnOtw)**

**Comment by scribam** [comment]
Not an issue anymore with Strict Rendering Mode

![screenshot from 2018-03-31 17-40-19](https://user-images.githubusercontent.com/25406440/38164846-f803851e-350a-11e8-9e2e-bcaf8a2b0a71.png)

**Comment by digitaldude555** [comment]
So close the issue?

**Comment by kd-11** [comment]
Closing as fixed
