### ISSUE TITLE
GL/VK Fracture - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3359]
Tested by https://github.com/RPCS3/rpcs3/commit/64a6fbe39ff089d0155a36aeb0d3c6360d223ad9

**Real HW:**
![fracture gl real](https://user-images.githubusercontent.com/11453507/29847009-c61142a6-8d19-11e7-9359-a1357b8a1310.PNG)

**RPCS3 GL:**
![fracture gl](https://user-images.githubusercontent.com/11453507/29847015-cbf6b746-8d19-11e7-8722-d98f9fa808cf.PNG)

**[RenderDoc GL](https://mega.nz/#!2E8RVKBS!Qh2CL6D1KbeMT9bD-cEt_EMhq4J8hBFzStVZEl9lM04)**
**[LOG GL](https://mega.nz/#!acdU2C6L!qydSpJQ_OAoBJKa-EyLij4igavYySb6Fv1CfVdBbm7Y)**

**Comment by AniLeo** [comment]
Is it still an issue on latest master?

**Comment by scribam** [comment]
Yes

![screenshot from 2018-03-31 17-30-52](https://user-images.githubusercontent.com/25406440/38164753-5502e018-3509-11e8-8cb1-9b2388c264e5.png)

**Comment by Asinin3** [comment]
Fixed with #4382 
![kd_2018-04-02_168](https://user-images.githubusercontent.com/15137035/38240232-95cf11b8-371e-11e8-8154-4a556512cff1.jpg)

**Comment by AniLeo** [comment]
Closing as solved
