### ISSUE TITLE
GL/VK Golden Axe: Beast Rider - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3361]
Tested by https://github.com/RPCS3/rpcs3/commit/64a6fbe39ff089d0155a36aeb0d3c6360d223ad9

**Real HW:**
![golden axe gl real](https://user-images.githubusercontent.com/11453507/29850001-b29ccbe4-8d2a-11e7-9902-41fcbfb15031.PNG)

**RPCS3 GL:**
![golden axe gl 1](https://user-images.githubusercontent.com/11453507/29850092-52302200-8d2b-11e7-8ae9-5f932184163a.PNG)

and after only solid black

![golden axe gl rd](https://user-images.githubusercontent.com/11453507/29850466-45581918-8d2e-11e7-9a26-900fda1c895c.PNG)

**[RenderDoc GL](https://mega.nz/#!OF1HyIRY!c2CxWiFDqNnd7knFmoDXd9VQuKDicXnPqdOxI9saZLA)**
**[LOG GL](https://mega.nz/#!GZFmCZTD!afgAOyEGDyKvyrWNodJtxO_0vgQcbt0vzJChRAA9IXM)**

**Comment by AniLeo** [comment]
Working fine on current builds
https://www.youtube.com/watch?v=kR5061-V5e4

If there are any remaining graphical issues with this game, open a new issue specifically for those graphical bugs, testing on current builds
