### ISSUE TITLE
GL/VK Iron Man - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3362]
Tested by https://github.com/RPCS3/rpcs3/commit/64a6fbe39ff089d0155a36aeb0d3c6360d223ad9

**Real HW:**
![iron man gl real](https://user-images.githubusercontent.com/11453507/29850625-3d269192-8d2f-11e7-897a-d0ae4d1b016a.PNG)

**RPCS3 GL:**
![iron man gl 1](https://user-images.githubusercontent.com/11453507/29850635-4e33c662-8d2f-11e7-87ef-f8b8f1985767.PNG)

![iron man gl rd](https://user-images.githubusercontent.com/11453507/29850641-55b93fb6-8d2f-11e7-896f-90e5413819dd.PNG)

**[RenderDoc GL](https://mega.nz/#!fF0hWKKB!dI3yOGxx2F0yHEE466jjlKFO7ZHfqv4AtvbpeMqLCv0)**
**[LOG GL](https://mega.nz/#!uB9xiArL!g9R7Whf_Q305RufZX2ZI25WZSDerdPllQNSW6Vyzcr0)**

**Comment by digitaldude555** [comment]
![Screenshot (862)](https://user-images.githubusercontent.com/26138653/72684778-31c66580-3aec-11ea-88c2-81d6d3e55386.png)
Can close now.
