### ISSUE TITLE
Can't start the game,can someone help me?

### ISSUE THREAD

**Issue by jordan851017** [RPCS3/rpcs3#3364]
i had installed step by step,but still can't play
this is imformation i don't know how to solve it :'(
![qq](https://user-images.githubusercontent.com/31498688/29906641-ce599078-8e48-11e7-88a3-9b4246cb84c6.jpg)

**Comment by Ariq139** [comment]
please check https://rpcs3.net/compatibility before you want to play a game
GT series is not playable yet

**Comment by AniLeo** [comment]
Don't spam issue tracker, read contributing guidelines.
