### ISSUE TITLE
Puyo Puyo Tetris - the game crashes with error 80022920

### ISSUE THREAD

**Issue by wasawasa0002** [RPCS3/rpcs3#3365]
on da3f3fd
The game always crashes after completing a match in single player mode, giving me the error code 80022920.

![screenshot_273](https://user-images.githubusercontent.com/31498320/29906349-48980094-8e4f-11e7-8c70-e998760cdb21.png)

[LOG](https://mega.nz/#!oJ4niDgA!BhVdE7NnttRTgnd1qmwuZRx3nWnj75e7HtC1T7dHpYA)

**Comment by Woovie** [comment]
Duplicate issue of #3162, can be closed.
@AniLeo
