### ISSUE TITLE
Dragon's Crown shader cache error

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#3374]
![image](https://user-images.githubusercontent.com/11285640/29996634-54ad0382-902c-11e7-9c18-cf9b127bca94.png)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1272263/RPCS3.zip)

It's white screen , game doesn't boot and show error log , but when i was deleted shader cache , it worked

**Comment by SakataGintokiYT** [comment]
@zminhquanz 
Wrong log

**Comment by hcorion** [comment]
Are you using the patch.yml? https://cdn.discordapp.com/attachments/277227681836302338/350242476151537664/patch.yml

**Comment by kd-11** [comment]
I'm closing this as it is likely triggered by a race condition that is mitigated using a patch. It has nothing to do with the shader cache, but the delay caused by compiling new shaders on the fly can make it get past the error. This is a game bug.
