### ISSUE TITLE
Issues with video decoding module

### ISSUE THREAD

**Issue by sirdanielk** [RPCS3/rpcs3#3377]
Two games suffer from video files loading/decoding problem
First is MOH frontline [NPUB30288] game stops after loading stage intro video. Intro EA logo .bik loads, just files with .mpcx suffix does not work. Deleting them from videos folder makes game go further. Files are probably mpeg2 format.
error: F {PPU[0x1000000] Thread (main_thread) [0x037dfec0]} MEM: Access violation writing location 0x31d2f9cc

Second game is Resident Evil 5 Demo NPEB90124 and what help to pass video is to enable autoloading and manual selection of modules and exclude from loading libvdec.sprx module. That way game skip video and advance. Video files are not bik, but in different format. Coded in mpeg2
error when using liblv2 only: F {PPU[0x100009b] Thread (HLE Video Decoder) [0x00f2f998]} MEM: Access violation reading location 0xffff8fd4

If that looks like two different issues i can split them

Edit: correction: Actually resident evil can go abit further with liblv2 only option,  after deleting all videos.

Same issue also in forum here http://www.emunewz.net/forum/showthread.php?tid=173757

**Comment by Psycho-A** [comment]
I can confirm video issues for Silent Hill: Downpour too. The game uses .mp4 (aac+avc) format. The first video played after intro level (in the prison). The emulator plays it correctly, but cannot correctly stop it on finish. As a result, it's hanging on latest frame not being able to continue game process. When I recoded video files to mp4-PSP (with the same codecs, resolution and bitrate), the emulator plays it without hangings.

**Comment by sirdanielk** [comment]
Both games behaves correctly now. Enrty videos are played with no crash. I think this errors were fixed long time ago. No need to keep this issue open. Also Streets of Rage 2 [NPUB30444] from the link works with default configuration.

**Comment by sirdanielk** [comment]
Self Close
