### ISSUE TITLE
Ability to dump RAM

### ISSUE THREAD

**Issue by eikap** [RPCS3/rpcs3#3383]
The hex viewer for memory is very limited, the ability to make a full binary dump of RAM to a file would help ease the process of, for example, searching for a string and it shouldn't be too hard to implement.

**Comment by dio-gh** [comment]
This ticket needs labels added. Looks to be rather straightforward, might need a guest VM pause while doing the dumping though to keep state consistent. #6038 might close this too, if extended, imo. I'd need OP's input on this though. @eikap

**Comment by elad335** [comment]
Its practically a duplicate of #4218 (its a part of it), closing.
