### ISSUE TITLE
Loop Boot Metal Gear Online

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#3386]
RPCS3 v0.0.3-3-9440e65 Alpha
Metal Gear Online [NPEB90122]

After Select New Game In intro Menu Game
Show Loading Game And Before into ingame Back To First Menu Game
Image **1**
![image](https://user-images.githubusercontent.com/25039098/30006191-366ff21c-9108-11e7-852d-85d2da57254b.png)

Image **2**
![image](https://user-images.githubusercontent.com/25039098/30006206-9cfa1db4-9108-11e7-9c64-c4bb1d26bbf7.png)

1->2->1->2->1->2->1->2.......

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1273209/RPCS3.zip)

**Comment by aakh1361** [comment]
Yes

**Comment by dio-gh** [comment]
I've seen people going ingame with MGO2 on a private server, so I don't think this is an issue anymore. Needs confirmation though.

![proof](https://cdn.discordapp.com/attachments/195663385453527040/617595901464150016/unknown.png)

**Comment by MSuih** [comment]
Closing this as private server implementations are out of scope for this project.
