### ISSUE TITLE
RPCS3

### ISSUE THREAD

**Issue by Jacabus** [RPCS3/rpcs3#3392]
I keep getting this "E {PPU[0x1000000] Thread (main_thread) [0x01b62fc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/NPEB02021//datamine/” [1]
F {PPU[0x1000000] Thread (main_thread) [0x01b62fcc]} class std::runtime_error thrown: sys_crash_dump_get_user_log_area" And i have no idea how to fix it, it makes it impossible to play anything.

**Comment by Megamouse** [comment]
I think Destiny won't work anyway because it needs PSN
