### ISSUE TITLE
Distinguish between LEFT and RIGHT key modifiers

### ISSUE THREAD

**Issue by h3x4n1um** [RPCS3/rpcs3#3393]
RPCS3 cannot distinguish input between **left SHIFT** and **right SHIFT**, **left CTRL** and **right CTRL**, **left ALT** and **right ALT**

**Comment by Megamouse** [comment]
I think this needs VirtualKeyCodes and so on.

e.g. https://codetato.wordpress.com/2013/06/19/left-and-right-shift-ctrl-alt-in-qt/

**Comment by oobol2000oo** [comment]
and RPCS3 detect SHIFT is 16777248 and CTRL is 16777249 in config_kbpad_qt.yml

**Comment by nitroos-ai** [comment]
Is it fixed now?

**Comment by Megamouse** [comment]
Only for windows
