### ISSUE TITLE
Tekken Tag Tournament 2 does not work

### ISSUE THREAD

**Issue by Gncd** [RPCS3/rpcs3#3394]
Game launches but after pressing start it gets stuck at a black screen
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1274301/RPCS3.zip)

**Comment by AniLeo** [comment]
Known, see https://rpcs3.net/compatibility?g=tekken+tag+tournament

Unless you know exactly what's the issue, report game compatibility on the forums as per the guidelines
