### ISSUE TITLE
Regression - The Simpsons Game

### ISSUE THREAD

**Issue by bobthecooldad** [RPCS3/rpcs3#3395]
Final Fixes #3366 
The game now doesnt start and throws a memory error, I have checked all the builds and this one casued the error.
·F 0:00:25.347310 {PPU[0x1000000] Thread (main_thread) [0x0050b1e8]} MEM: Access violation writing location 0xd0000fd0

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1274851/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Where's the log

**Comment by bobthecooldad** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1274845/RPCS3.log.gz)

**Comment by Xcedf** [comment]
regressed after a85caaee

**Comment by SakataGintokiYT** [comment]
fixed by #3984
