### ISSUE TITLE
sceNpTrophyCreateContext: SCE_NP_TROPHY_ERROR_CONF_DOES_NOT_EXIST (Disgaea D2 DLC)

### ISSUE THREAD

**Issue by suam3524** [RPCS3/rpcs3#3402]
Without DLC, it works well.

I used "rpcs3-v0.0.3-2017-09-03-4558f93f_win64"

Please check the log.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1279924/RPCS3.zip)

By the way i can do this game with dlc by old version of rpcs3. (rpcs3-v0.0.2-2017-06-25-fc6b303c_win64)

Why not in the latest version?

**Comment by hcorion** [comment]
Have you tried with this build: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6035/artifacts ?

**Comment by suam3524** [comment]
I tried it with the version you mentioned, but it does not work either.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1279959/RPCS3.zip)

**Comment by suam3524** [comment]
The version of rpcs3 that can boot BLSU31313 + DLC .pkg. (Disgaea D2)
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-5092/artifacts﻿

And log file.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1283448/RPCS3.zip)

**Comment by AniLeo** [comment]
Why are you using library manual loading mode only?

**Comment by suam3524** [comment]
Because when i used library auto loading mode, it didn't work. So I found another way and tried that method on the link below. 
https://www.youtube.com/watch?v=AMsxYsRTkkk

Of course, if i do not install DLC, it works well "Automatically load required libraries".


Version of rpcs3
rpcs3-v0.0.3-2017-09-08-882c56c6_win64

Log file (Auto load libraries)
[RPCS3 (Auto).zip](https://github.com/RPCS3/rpcs3/files/1289510/RPCS3.Auto.zip)

Log file (Auto & Manually load libraries)
[RPCS3 (Auto & Manually).zip](https://github.com/RPCS3/rpcs3/files/1289511/RPCS3.Auto.Manually.zip)

**Comment by POEMisaMisa** [comment]
Same error occurs on BLES01939 version too (patched+DLC).

**Comment by inuboshi** [comment]
@POEMisaMisa  found a way to solve it? i'm getting it too. failed to initialize trophies.

**Comment by POEMisaMisa** [comment]
@inuboshi no, waiting for developers to fix it. Game is unplayable until then, sadly.

**Comment by hozz8528** [comment]
are there any versions that run the 1.40 patch? I've tried installing the patch on a bunch of recent versions and they all give me failed to initialize trophies :/

**Comment by ilcane87** [comment]
The latest RPCS3 version that will run Disgaea D2 + Patch 1.40 + DLC is 0.0.3-5591, downloadable here:

https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-5591/artifacts


Some error must have been introduced in the next version, 0.0.3-5594, by Megamouse, and is still present as of the present time.

**Comment by hozz8528** [comment]
awesome. I tried it and I think the DLC works (I'm not post-game yet so I can't get the additional characters but I can see the additional save icon, so I'm assume it reads it correctly). However, the speed patch found here https://www.patreon.com/posts/march-progress-8627774 no longer works (the game now runs at like 10 fps in the base and some levels, and I think this is expected from reading the forum in the comments). Hopefully there's a new patch released so this is finally playable with everything

**Comment by ilcane87** [comment]
The latest version of RPCS3 that correctly employs the speed patch with Disgaea D2 + Patch 1.40 + DLC is 0.0.2-5177, downloadable here:

https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-5177/artifacts

Again, some kind of error must have been introduced in the next version, 0.0.2-5194, by Nekotekina, and is still present as of the current latest release.

**Comment by suam3524** [comment]
Thank you

**Comment by POEMisaMisa** [comment]
@ilcane87 I created [new issue](https://github.com/RPCS3/rpcs3/issues/4022) about patch.yml speedhack and managed to get it work on latest RPCS3 with NPUB31321 version (latest patch + DLC) by adding an extra hash to patch.yml. Full info in issue link above.

**Comment by ilcane87** [comment]
It appears that the "Trophies could not be initialized" error has been fixed in the latest release of RPCS3, so this topic should be marked as solved, while the speed patch issue can be tracked in POEMisaMisa's topic above.

**Comment by hozz8528** [comment]
I absolutely love you all.
