### ISSUE TITLE
Render to texture sample issue

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#341]
Just for record .The texture is rendered somewhere instead on the cube surface

![render_to_texture](https://cloud.githubusercontent.com/assets/3000282/3280643/40e4a178-f473-11e3-83a4-0972efebdf5a.jpg)

Should be 
![fw_render_to_texture_ps3](https://cloud.githubusercontent.com/assets/3000282/3280675/c04a5100-f474-11e3-9c3e-0671c2035277.PNG)

**Comment by tambry** [comment]
@raven02 Does this happen to fixed on the rsx branch?

**Comment by raven02** [comment]
@tambry , yep , it partially fixed in rsx branch

**Comment by vlj** [comment]
The gl backend doesnt use the correct framebuffer size (it always use RSXThread::m_widht/height, which are size of the window, but here the sample renders to a 256x256 fbo. The format is wrong too, fbo in gl backend use GL_RGBA8 but the sample write/reads half float values, which explains the green pattern.

**Comment by tambry** [comment]
@raven02 @vlj Has this been fixed on master?

**Comment by vlj** [comment]
I don't have the sample off hand

**Comment by tambry** [comment]
Can anyone confirm if this is still an issue?

**Comment by raven02** [comment]
Tested with latest build using OpenGL .It runs correct now.
