### ISSUE TITLE
Some bluray games need an installation from XMB (INSDIR folder)

### ISSUE THREAD

**Issue by jjsat** [RPCS3/rpcs3#3412]
If the games folder structure contains the folder "PS3_GAME/INSDIR", the PS3 displays an installation dialog on first start of the game and installs the packages from the folder. For some games this is probably only a mandatory patch but the game starts without it (e.g. Dishonored GOTY), others like Heavy Rain (BCES00797) hang or crash upon starting if the packages are not installed. With it installed HR goes ingame.

It is possible to install the packages manually but it would be more correct to offer an option to install like the VSH. At least this could be mentioned in the getting started documents.

**Comment by AniLeo** [comment]
What's the structure of an INSDIR folder? Just pkg files inside? I can't find it on any of my games

**Comment by jjsat** [comment]
http://www.psdevwiki.com/ps3/PARAM.SFO describes it (look for INSDIR on the page).

**Comment by PeterMcteague** [comment]
Could you expand on where the games expect their packages installed to? Also are they extracted or not?

**Comment by MarioSonic2987** [comment]
Can this issue be closed? #3799 is merged.

**Comment by v0idst4r** [comment]
^
