### ISSUE TITLE
Shader Cache loads too long after restarting

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3416]
That's what I figured out during this time for this issue.
I have NVidia card, so I'll be write about it as an example.

Slow loadings happen because in fact it's not re-loading of compiled data -- it's a new compiling process that video drivers do! For some reasons they sometimes clears %AppData%\Roaming\NVIDIA\GLCache\ contents -- on new game loading, on running different emulator version, on system rebooting etc. Compiled data not exist, so it starts from scratch on loading shader_cache pipelines. And it's that a pain in the ass.

I suggest developers to think about it, and implement saving compiled caches in game data folder to exclude permanent data losses. Or maybe make some own format that will be translated to GLCache on game loading.

== old text ==
_If we close emulator after shaders compiled, then on the next game booting it loads cache ULTRA-SLOW (about 1 or two shader unit per second). It happens not always, but launching some other 3D apps or exigins system leads chances of it to 100%. So, just imagine if we have about 6k files of full cache, how many *hours* loading will be happen. It's definitely needed to do something with. I'm no alone with that problem, and nothing changes from revision by revision._

**Comment by Kompas9** [comment]
https://rpcs3.net/blog/2017/09/01/progress-report-august-2017/

> Other games do not work quite as well. Persona 5 is one such game. After playing through a few very stuttery minutes of that game one will have compiled literally thousands of shaders. This is not intended. The game does not use 2,000 different shaders in five minutes. Think of it instead as using the same shaders in different ways. This will be improved in September, not only in Persona 5 but in (hopefully) every game. In reality it seems incredibly unlikely that any game would actually have more than a few hundred shaders. The end goal is to reach that point where Persona 5 and really every other game will only see a few hundred shader compiles, ever.

**Comment by raveskirza** [comment]
I had this issue some time back. But i resolved it by following the below steps
1. Delete all the data stored under data/<GameID> i.e config.yml, shader caches and LLVm cache
2. Delete the config.yml from the root under the rpcs3 folder
3. Delete all the files under "shaderlog" folder under the rpcs3 directory
4. Setup the configurtion. to create the config.yml when you save the configuration
5. Run your games LLVM and shader caches will be regenerated

If you are using nVidia GPU and if you have lot of shaders(4000+) then the initial few shaders will compile fast and once you run out of memory, the loading of shaders slow down. This is because there is a bug with nvidia drivers which cause excessive RAM usage while loading shaders. A large page file will stop RPCS3 from crashing on the driver however the shader compilation will slow down.

**Comment by Psycho-A** [comment]
Your solution helps but not for long time. Once we restart system, it may back again.
Also, I have no problems with RAM overflowing - the same problem exist for me even if 100-200 shaders exist and RAM usage is low. I'm anyway thinking it's not normal behavior.

**Comment by raveskirza** [comment]
Also ddd the rpcs3 directory in the exclusion list of your antivirus program, so that your antivirus doesnt scan it unnecessarily
I have this set in my Windows defender
![image](https://user-images.githubusercontent.com/28158623/30245636-9e7a5d0c-95ae-11e7-8f8a-e3f4108dd6f2.png)

**Comment by Psycho-A** [comment]
> Also add the rpcs3 directory in the exclusion list of your antivirus program, so that your antivirus doesnt scan it unnecessarily

I'm using Windows 7 with all antivirus junk disabled. And I have no any CPU or RAM load during that slow boot. Loading games may take a hour and just makes me to delete cache at all or don't close emulator forever that's no good too.

**Comment by raveskirza** [comment]
Then i would expect it is a game or system related issue.
I had faced the slowdown yesterday while I was testing games with different GPU options. Some of the games started loading the shaders very slow at 2 shaders /sec, but after restarting RPCS3, it was back to normal at 50 shaders/sec

**Comment by zerocold1981** [comment]
I have 4000 cache and it loads for half an hour)

**Comment by KainXS** [comment]
That is pretty excessive, I have my shader cache at about 5300 now and it it only takes 6 minutes to load with persona 5.

**Comment by zerocold1981** [comment]
I've already adapted, turn on the emulator and watch the video on YouTube until it loads

**Comment by Psycho-A** [comment]
That's what I figured out during this time for this issue.
I have NVidia card, so I'll be write about it as an example.

Slow loadings happen because in fact it's not re-loading of compiled data -- it's a new compiling process that video drivers do! For some reasons they sometimes clears %AppData%\Roaming\NVIDIA\GLCache\ contents -- on new game loading, on running different emulator version, on system rebooting etc. Compiled data not exist, so it starts from scratch on loading shader_cache pipelines. And it's that a pain in the ass.

I suggest developers to think about it, and implement saving compiled caches in game data folder to exclude permanent data losses. Or maybe make some own format that will be translated to GLCache on game loading.
