### ISSUE TITLE
RSX: Attempt to download render target that doesn't exist (Ar Nosurge: Ode to an Unborn Star)

### ISSUE THREAD

**Issue by ryokasho12** [RPCS3/rpcs3#3421]
E {rsx::thread} RSX: Attempted to download render target that does not exist. Please report to developers
E {rsx::thread} RSX: FBO check failed: 0x8cd6

**Comment by AniLeo** [comment]
Will probably be fixed after fbo_fixes but better wait for the man himself

**Comment by AniLeo** [comment]
Needs retesting on latest master

**Comment by al0xf** [comment]
Still spams FBO check failed and has missing 2D on OpenGL
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1366945/RPCS3.log.gz)

**Comment by ryokasho12** [comment]
still same

Pada tanggal 8 Okt 2017 10.20 PM, "al0xf" <notifications@github.com>
menulis:

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/3638. Also, does this game need synchronized render targets? Or are you just trying it out? @ryokasho12

**Comment by AniLeo** [comment]
Needs retesting.

**Comment by al0xf** [comment]
Fixed
