### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by KitomaGithub** [RPCS3/rpcs3#3422]
---------------------------
Fatal error
---------------------------
Unhandled exception of type 'class std::runtime_error': Unknown Win32 error: 32.
HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

**Comment by Asinin3** [comment]
This is not the place to ask for support please read: https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md
