### ISSUE TITLE
N2gl4glsl14link_exceptionE thrown: linkage failed: 'error: fragment shader input `tc2' has no matching output in the previous stage

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#3423]
Affected game is Raiden IV Overkill [NPUB31371]
Linux, Mesa 17.2, OpenGl (Vulkan crashes instantly), R9 Fury
After a short while on 1st level, the game freezes with "F {rsx::thread} N2gl4glsl14link_exceptionE thrown: linkage failed: 'error: fragment shader input `tc2' has no matching output in the previous stage"
On my laptop (win10+nvidia), no pb.
[RPCS3.log-RaidenIV.gz](https://github.com/RPCS3/rpcs3/files/1290337/RPCS3.log-RaidenIV.gz)

**Comment by kd-11** [comment]
This issue is a duplicate and has been fixed for a while on fbo fixes

**Comment by toccata10** [comment]
Compiled your branch and pb solved. Nice. Closing.
