### ISSUE TITLE
Red Color Issue occurred when playing the game(Kingdom Hearts HD 1.5 Remix)

### ISSUE THREAD

**Issue by Victor9805** [RPCS3/rpcs3#3424]
![screenshot 101](https://user-images.githubusercontent.com/31816484/30247279-2b53cb48-9643-11e7-9d70-c9008dcd9813.png)

Does anybody know this problem and how to fix it??

I downloaded RPCS3-v0.0.3 and using OpenGL as renderer.

![desktop screenshot](https://user-images.githubusercontent.com/31816484/30247339-9a296af4-9644-11e7-8423-41d6bc67da5e.jpg)
GPU : NVIDIA GEFORCE 820M
SSD: 77.0 GB

**Comment by mchtt** [comment]
Maybe try with vulkan for the moment or provide a proper log.

**Comment by Asinin3** [comment]
820m doesn't support vulkan but the 830m and up do... you're out of luck until it gets fixed.

**Comment by Victor9805** [comment]
@mchtt @Asinin3 
Thanks for the info. 
I guess I really out of luck......[Sad]

**Comment by scribam** [comment]
@Victor9805 Would you mind trying a recent build to see if the problem is fixed?

**Comment by Victor9805** [comment]
@scribam Thanks for the reminder.
The recent build has fixed the previous problem, but a new problem occurs.

![2](https://user-images.githubusercontent.com/31816484/36771855-dda2c422-1c8d-11e8-9e4a-9b64eb13e871.JPG)

There's a black box appeared under the screen. I have tried to adjust the resolution and scale, but there's no luck of it.
It's the resolution problem or ??

**Comment by MarioSonic2987** [comment]
Disable GPU texture scaling.

**Comment by Victor9805** [comment]
@MarioSonic2987 Works well. Thanks.
