### ISSUE TITLE
Unhandled Win32 exception 0xC0000005 when launch game

### ISSUE THREAD

**Issue by Aztec2012** [RPCS3/rpcs3#3425]
Fatal error

Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000041249070 at 000000000019847c.
Instruction address: 000000000019847c.
Function address: 00000000001983d0 (base+0x1883d0).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

Game is: Fight Night Round 4
RPCS3 v0.0.3-3-b11f9e0 Alpha
Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz | 8 Threads | 7.94 GiB RAM | AVX

**Comment by AniLeo** [comment]
No good if you don't know what's the issue, the fatal error message doesn't say anything useful.
Please use the forums for support.
