### ISSUE TITLE
[Feature] Allow to have more than one default configuration

### ISSUE THREAD

**Issue by flash-fire** [RPCS3/rpcs3#3428]
When testing games vs playing games for enjoyment, I usually have different configurations.  However, it's annoying to use custom configurations for each game.  It'd be convenient if I could choose between preset configurations instead of manually having to adjust each game.

A combobox of options loaded from a default folder.  Or, perhaps, a save as/load button would be convenient.

(I might implement this myself.  Mostly making this issue to see how others perceive this idea)

**Comment by Asinin3** [comment]
Hmm I'm honestly not sure how useful this would be. Maybe a preset option for custom configurations would be more useful. As an example you set up a configuration and give it a name. Now you can right-click a game and select that preset. Selecting multiple games would allow you to change it for many games.

One of my bigger concerns is not having an easy way to clear out the data folder and keep custom configurations for each game.

**Comment by twdarkeh** [comment]
One idea might be to move all custom configs to a single folder called 'configs' somewhere, and name them by game ID, then load them from there. That way, deleting the data folder doesn't delete all your configs. It would also making sharing configs easier, which would help for games that have strange config requirements when the wiki gets set up: could just post the config with a "put this in the configs folder" instruction.

**Comment by Asinin3** [comment]
@twdarkeh I agree with the config folder. But when it comes to the wiki it should only be for very specific settings and leave the others up to the user. For instance with DeS it would have a file or some kind of integration with rpcs3 that enables write color buffers and recompilers but has everything else left up to the user.

**Comment by dio-gh** [comment]
Outdated ticket, should be closed unless it's still up for discussion. Afaik the current longer term plan is implementing automatic per-game configs where required, and apply single good defaults elsewhere.

**Comment by AniLeo** [comment]
Pretty sure this is still a valid suggestion, we don't have any plans for premade/automatic per-game config

**Comment by Asinin3** [comment]
Closing issue. Most of this has been addressed with upcoming changes allowing you to boot default configuration, or global, or custom via right-click in new PR soon to be merged. Otherwise the amount of required settings for games has gone down a lot since 2017, and ticket maintainer is no longer around.

@Darkhost1999 https://github.com/RPCS3/rpcs3/issues/4434 Issue for that already exists. But we're already aware its something people want. Its just not easy to implement for a number of reasons so requesting it won't really do anything.

**Comment by elad335** [comment]
Upcoming changes?
