### ISSUE TITLE
Dragon's Crown [FATAL]

### ISSUE THREAD

**Issue by CristianPietrobon** [RPCS3/rpcs3#3435]
Version: 0.0.3-3-553f67d

Crash error:
F 3:38:22.798025 {rsx::thread} class std::runtime_error thrown: Unknown texture dimension 0
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:137)

[log.zip](https://github.com/RPCS3/rpcs3/files/1296428/log.zip)

**Comment by hcorion** [comment]
Are you using the path.yml for Dragon's Crown?
https://cdn.discordapp.com/attachments/277227681836302338/350242476151537664/patch.yml
Place it in the same directory as rpcs3.exe.

**Comment by CristianPietrobon** [comment]
Ok done! Sorry, I will play for some hours to check.
Can we create an automatic "hack/fix" loading for each game?
If you point me in the right direction I can do that, I don't know if you have documents or something like that for this project.

**Comment by AniLeo** [comment]
Nope no bundling hacks
