### ISSUE TITLE
Dragon Ball Raging Blast 2 error Crash with several characters  including the hidden characters

### ISSUE THREAD

**Issue by renzobich** [RPCS3/rpcs3#3436]
E {rsx::thread} RSX: Invalid RSX method 0xac00 (arg=0xe810440)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x005583dc]} Stat: 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x198560]
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x005583dc]} Stat: 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [x198560]

**Comment by kd-11** [comment]
1. This is a duplicate - there already exists an issue tracking unknown method ids.
2. A fix for this exists but I'm yet to submit to master. Just be a little patient of ask on discord if you wish to test.
Closing as a duplicate
