### ISSUE TITLE
Silent Hill: Downpour [BLUS30565] crash on Vulkan after start.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#3438]
I was using VS debugger to see this.
It says:

![70](https://user-images.githubusercontent.com/6324523/30377951-aba52542-98a2-11e7-9013-c5faf449fc8a.png)
after I press Continue:
![71](https://user-images.githubusercontent.com/6324523/30378001-dbbfbbb6-98a2-11e7-9250-dfd63d2f304f.png)

**Comment by isshininu** [comment]
No log.

**Comment by kd-11** [comment]
This isnt an issue though if it recovers on clicking continue. The swapKHR crash on nvidia is known and the previous one is expected - rpcs3 uses segfaults to notify the application to invalidate memory regions.

**Comment by isshininu** [comment]
So, first exception is not an issue.
And the second (screenshot) will be investigated after https://github.com/RPCS3/rpcs3/issues/3304#issuecomment-329194217 fbo_fixes, right?

**Comment by Psycho-A** [comment]
Disabling "Strict Rendering Mode" helps Vulkan crashings, although all game texts get broken. OpenGL is currently the best render for this game.

**Comment by isshininu** [comment]
Now this game works with Vulkan & "Strict Rendering Mode" enabled.
I am closing this issue.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1358218/RPCS3.log.gz)
