### ISSUE TITLE
Wizardry Labyrinth of the Lost Soul - Name text getting cut off

### ISSUE THREAD

**Issue by Krusher97** [RPCS3/rpcs3#3447]
A minor issue in this PSN title. The last letter in name field gets cut off when you go to rename your character.
Hopefully the webm will clear it up.
https://my.mixtape.moe/lznnaz.webm

Log
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1307621/RPCS3.zip)

**Comment by Megamouse** [comment]
We suspect it must be a game bug since our code for the text input dialog works just fine.
It literally gives us the correct size of the name but the name itself just ends one character short.

other games are working fine in that regard

**Comment by Krusher97** [comment]
https://youtu.be/4nm4SfvSDs8?t=4m51s

Huh it is a game bug after all.
