### ISSUE TITLE
Save's PARAM.SFO invalidation

### ISSUE THREAD

**Issue by appel28** [RPCS3/rpcs3#3449]
Hey
So I played Persrona 5 for about 9 hours and then I saved.
Next day I booted everything up like normal but the game said this:
```

F {PPU[0x1000017] Thread (xrd664_list_load) [0x001ab598]} class std::runtime_error thrown: Verification failed: 
(in file C:\rpcs3\rpcs3\Loader\PSF.cpp:118)
```

The cause is PARAM.SFO.

PC SPECS: i5-4590 3.30GHz/ 8 GB ram / nvidia geforce gtx 1050 ti / windows 10

**Comment by Megamouse** [comment]
try deleting your shader cache before boot (maybe make backup before that)

**Comment by appel28** [comment]
Nope, still not working.

**Comment by Farseer2** [comment]
Known issue: Copy the save to another folder, then delete the original one. Start the game and save it, then close the game and copy the save file (NOT the param.sfo) back.
Problem occurs because the PARAM.SFO is zeroed out for some reason, but the save data itself is fine.

**Comment by appel28** [comment]
OMG! It works tanks ALOT! :D

**Comment by AniLeo** [comment]
Fixed issue formatting, if someone has further information on this issue please update it

**Comment by isJuhn** [comment]
Had this happen to me, just overwriting the PARAM.SFO with one from another save is fine, it shows the info from the other save in the menu but the savedata is fine, and if you just save again after loading it will be replaced with a proper one.

**Comment by Megamouse** [comment]
@Farseer2 could this have been related to #4832 ?

**Comment by elad335** [comment]
Need a log.

**Comment by elad335** [comment]
PARAM.SFO write of savedata is now atomic, data corruption is unlikely.
Closing for now, if someone encounters it with latest master I'll reopen. (with savedata from it)
