### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by stainslav** [RPCS3/rpcs3#3450]
Please RPCS 3 Android/IOS please @Nekotikina
@DAGINATSUKO PLEASE PLEASE:(

**Comment by darkdrifter** [comment]
sure, probably just after the 3DS release

**Comment by clienthax** [comment]
Which is right after the lua version which is only supported on sparc

**Comment by Renusek** [comment]
HTML 5 version is coming right after RPCS3 is ported to Unity.

**Comment by AniLeo** [comment]
Spam account, repository ban.
