### ISSUE TITLE
Settings window changes its size when switching to "CPU"

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3453]
@Megamouse When choosing Menu > Configuration > GPU (or any other point except CPU), and switching to CPU, the Settings window changes its size, and its annoying.
![1](https://user-images.githubusercontent.com/14265316/30513407-692432a6-9b0b-11e7-9682-0af216d3ac91.png)
![2](https://user-images.githubusercontent.com/14265316/30513408-6e25ede4-9b0b-11e7-9457-1ffab6d3ce24.png)
Wouldn't it be good to equalize them?

**Comment by Megamouse** [comment]
I'm sorry but this seems to be a Qt bug right now. (believe me, at least I tried most things)

When I put the gpu tab in front of the cpu tab everything works as you might expect.
I suspect the list size is interfering with some size calculation

**Comment by Megamouse** [comment]
try with that PR

**Comment by TotalCaesar659** [comment]
Well, I think it's good, I haven't seen any other bugs with this PR yet.

**Comment by TotalCaesar659** [comment]
@Megamouse, this bug returned in https://github.com/RPCS3/rpcs3/commit/0129c54ab6e8a38bb152f2c9a10a29a76f8dcbb0.
![1](https://user-images.githubusercontent.com/14265316/31517441-99d0bda4-afa4-11e7-97c2-a23b11570c62.png)
![2](https://user-images.githubusercontent.com/14265316/31517445-9de2e9f8-afa4-11e7-9f9b-2e02834d191a.png)
