### ISSUE TITLE
Demon's Souls [BLUS30443]: Vanguard boss not rendering

### ISSUE THREAD

**Issue by Pacundito** [RPCS3/rpcs3#3456]
Hello i have a rare issue, vanguard boss is not rendering, my specs are:

Intel Core i7 4970
Mem 16 GB DDR3 1866mhz
GPU GeForce GTX 970
RPCS3 build 6172

https://i.imgur.com/ff1A0sx.jpg

**Comment by kd-11** [comment]
Does it happen more than once. Demon's souls has rather interesting glitches even on real hardware.

**Comment by Pacundito** [comment]
It happend all the time,everytime i tried with every version of rpcs3

**Comment by Asinin3** [comment]
How is it a rare issue if it happens every time?

**Comment by Pacundito** [comment]
It's rare for me because i didn't see other people posting this issue in particular, i searched a lot before posting

**Comment by kd-11** [comment]
So it might be a bad dump of the game? If it always happens for you but not for anyone else, you probably have a corrupted dump.

**Comment by AniLeo** [comment]
Needs more information as per the guidelines.
We can't do anything if we can't reproduce the issue to start with.
Used version (retest with latest), drivers' version and log files.

**Comment by kd-11** [comment]
I'm convinced this is a bad dump of the game otherwise a missing boss in Demon's souls would have been mentioned by other users. As such, I will close this issue for now unless someone else can confirm the same is happening to them.

**Comment by Pacundito** [comment]
i tried another dump with same result
