### ISSUE TITLE
Kingdom Hearts 1.5 crash

### ISSUE THREAD

**Issue by Shika93** [RPCS3/rpcs3#3457]
After the battle with Unknown (Xenmas) at Hollow Bastion, the video crashed. I attach a video found on Youtube. Crash is at minute 5.48 
https://youtu.be/ygFwAkdGzQY?t=5m45s 

This is the log:
> E {PPU[0x100001b] Thread (Axa PPU Thread) [0x02c67fc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/BLUS31212//SaveData0” [1]
E {PPU[0x100001c] Thread (Axa PPU Thread) [0x02c67fc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/BLUS31212//SaveData0” [1]
S {rsx::thread} RSX: New program compiled successfully
F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough, buffer_length=134217728 allocated=121364480 requested=8294400 guard=65536 largest_pool=8294400
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:74)
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-95/BISLPS-25198-95” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-69/BISLPS-25198-69” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-24/BISLPS-25198-24” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-51/BISLPS-25198-51” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-67/BISLPS-25198-67” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-27/BISLPS-25198-27” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-68/BISLPS-25198-68” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-25/BISLPS-25198-25” [x47]
E {PPU[0x1000008] Thread (CDevSd VSYNCHandler) [0x002eabdc]} Stat: 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [x9439]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-05/BISLPS-25198-05” [x47]
E {PPU[0x1000008] Thread (CDevSd VSYNCHandler) [0x002eabdc]} Stat: 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [x9439]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-14/BISLPS-25198-14” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-09/BISLPS-25198-09” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-99/BISLPS-25198-99” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-98/BISLPS-25198-98” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-03/BISLPS-25198-03” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-47/BISLPS-25198-47” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-45/BISLPS-25198-45” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-90/BISLPS-25198-90” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-83/BISLPS-25198-83” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-43/BISLPS-25198-43” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-10/BISLPS-25198-10” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-21/BISLPS-25198-21” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-91/BISLPS-25198-91” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-63/BISLPS-25198-63” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-20/BISLPS-25198-20” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-61/BISLPS-25198-61” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-85/BISLPS-25198-85” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x6]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-60/BISLPS-25198-60” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-15/BISLPS-25198-15” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-58/BISLPS-25198-58” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [x152132]
E {PPU[0x1000007] Thread (CDevSd MSECHandler) [0x002eabdc]} Stat: 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [x45496]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [x4436]
E {PPU[0x1000007] Thread (CDevSd MSECHandler) [0x002eabdc]} Stat: 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [x45496]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-04/BISLPS-25198-04” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-46/BISLPS-25198-46” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-93/BISLPS-25198-93” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-13/BISLPS-25198-13” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-06/BISLPS-25198-06” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-52/BISLPS-25198-52” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-73/BISLPS-25198-73” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-02/BISLPS-25198-02” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-16/BISLPS-25198-16” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [x152132]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-07/BISLPS-25198-07” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-54/BISLPS-25198-54” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-49/BISLPS-25198-49” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-39/BISLPS-25198-39” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-41/BISLPS-25198-41” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-32/BISLPS-25198-32” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-18/BISLPS-25198-18” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-38/BISLPS-25198-38” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-56/BISLPS-25198-56” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-96/BISLPS-25198-96” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-77/BISLPS-25198-77” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-53/BISLPS-25198-53” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-08/BISLPS-25198-08” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-42/BISLPS-25198-42” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-40/BISLPS-25198-40” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-30/BISLPS-25198-30” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-55/BISLPS-25198-55” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-11/BISLPS-25198-11” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-23/BISLPS-25198-23” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-28/BISLPS-25198-28” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-19/BISLPS-25198-19” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-48/BISLPS-25198-48” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-57/BISLPS-25198-57” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-34/BISLPS-25198-34” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-12/BISLPS-25198-12” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-17/BISLPS-25198-17” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-44/BISLPS-25198-44” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [x4430]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-37/BISLPS-25198-37” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-31/BISLPS-25198-31” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-29/BISLPS-25198-29” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-75/BISLPS-25198-75” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-22/BISLPS-25198-22” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-59/BISLPS-25198-59” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-36/BISLPS-25198-36” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-35/BISLPS-25198-35” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-26/BISLPS-25198-26” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-33/BISLPS-25198-33” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-50/BISLPS-25198-50” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-62/BISLPS-25198-62” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-64/BISLPS-25198-64” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-65/BISLPS-25198-65” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-66/BISLPS-25198-66” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-80/BISLPS-25198-80” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-70/BISLPS-25198-70” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-71/BISLPS-25198-71” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-72/BISLPS-25198-72” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-74/BISLPS-25198-74” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-87/BISLPS-25198-87” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-76/BISLPS-25198-76” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-78/BISLPS-25198-78” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-79/BISLPS-25198-79” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-81/BISLPS-25198-81” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-82/BISLPS-25198-82” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-84/BISLPS-25198-84” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/BLUS31212//SaveData0/system.bin” [x4]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-86/BISLPS-25198-86” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-88/BISLPS-25198-88” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-94/BISLPS-25198-94” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-89/BISLPS-25198-89” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-92/BISLPS-25198-92” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-97/BISLPS-25198-97” [x47]
E {PPU[0x1000000] Thread (main_thread) [0x00260fcc]} Stat: 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-01” [x4]
E {PPU[0x1000009] Thread (TrophyThread) [0x000fbe04]} Stat: 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [x7]
E {PPU[0x1000009] Thread (TrophyThread) [0x000fbe04]} Stat: 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [x7]
E {PPU[0x100000a] Thread (KH1 dkThread) [0x000448d8]} Stat: 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [x63541]
E {PPU[0x100000a] Thread (KH1 dkThread) [0x000448d8]} Stat: 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [x63541]

**Comment by AniLeo** [comment]
Check the Guidelines and reopen when you fix the issue, removing console output spam and properly providing log files

**Comment by Shika93** [comment]
Sorry. I've edited

**Comment by miskimt** [comment]
h
