### ISSUE TITLE
Ignoring LLVM-compiled modules on changing game/emulator path

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3460]
If we moved emulator or game to some other location, compiling LLVM modules starts again everytime that's really vexatious. I understand it made for not-executing alien code for alternate game versions, but isn't it better to sign compiled code with boot/eboot.bin's hash checksums instead of game/module path hashes? It will save emulator's portability and will allow to share compiled code with each-other.

**Comment by Nekotekina** [comment]
It's possible to move cache dir within /data/ABCD12345/ locations (from old to new one), and I will think how to do it automatically or at least with minimal user interaction.

**Comment by AniLeo** [comment]
This is also useful for people that dual-boot between different OS and share game folders between the installations. Currently (without symlinking everything) one needs to have two object caches since locations vary due to path differences (e.g. Linux and Windows).

**Comment by Nekotekina** [comment]
Closing as fixed
