### ISSUE TITLE
Physics doesn't work properly on Dante's Inferno making the game unbeatable

### ISSUE THREAD

**Issue by geo98** [RPCS3/rpcs3#3464]
In Sins of the Father on Dantes Inferno, the axe on the bull's hand doesn't answer properly when triggered, making impossible to move on, since is a key element on the game.

You can see this issue on this video https://www.youtube.com/watch?v=rhVlogL4_aU

I tested many settings and its the same result.

I'm attaching the save file if someone is willing to test it.

Settings used:
https://www.youtube.com/watch?v=sPS9xRIqVQw

[RPCS3 Dantes Inferno Save File.zip](https://github.com/RPCS3/rpcs3/files/1315022/RPCS3.Dantes.Inferno.Save.File.zip)

I found and work around, it does not solve the physics issue, but allow you to progress on the game without using the mechanism, if someone wants, I can do a video showing it.

**Comment by geo98** [comment]
Finished the game using the work around I found.
![credits](https://user-images.githubusercontent.com/32105209/30719803-4fe94c42-9efb-11e7-9969-8bae53023443.png)

**Comment by geo98** [comment]
But the issue persists, I just found a way to go around it. So technically this should be keep open until it get fixed properly.

**Comment by geo98** [comment]
Here it goes the work around with the physics issue:
Part 1:
https://www.youtube.com/watch?v=KKE9EPn7SmU

Part 2:
https://www.youtube.com/watch?v=KKE9EPn7SmU

I'm attaching the closest save point after doing the work around for who doesn't want to bother doing the work needed to get through on this part.

[Save Data for Dantes Inferno - After Work Around.zip](https://github.com/RPCS3/rpcs3/files/1326309/Save.Data.for.Dantes.Inferno.-.After.Work.Around.zip)

**Comment by UroshUchiha** [comment]
This is still not resolved, I just got to this part and have the same issue. Will try the work around, but yeah, the bug is still present.

**Comment by maxgerhardt** [comment]
Still present in most recent master version.

**Comment by WasabiDRS** [comment]
GPU - 03G-P4-2888-KR

F {RSX [0x07f6614]} RSX: class std::runtime_error thrown: Invalid location (offset=0x191f700, location=0xc)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsxthread.cpp:101)

**Comment by arcadee1977** [comment]
This issue is still exist on last relase version

**Comment by Xcedf** [comment]
Look's like Eladash latest fixes fixed not only MGS4, Demon statue is also fixed now, the game is playable
![4](https://user-images.githubusercontent.com/7060586/63008353-201cca00-be8b-11e9-9651-1cefaaa14e0d.jpg)

**Comment by legend800** [comment]
Fantastic news, thanks for the update. Guess we can close this and update the compat. list.

**Comment by Asinin3** [comment]
Some people still said there were audio issues, so need to make sure its running well for the majority of users before we classify it as playable. But yeah, good news 👍

**Comment by Leopard1907** [comment]
If you count audio issues as blockers, i'm sure many games will regress into ingame category. There are many issues like overtime audio choppiness etc that affects whole emulator , not a handful of games.

**Comment by arcadee1977** [comment]
When this problem is solved, the game can be fully playable , I have cleared this game completely .

**Comment by dio-gh** [comment]
I'd be more concerned about the game randomly crashing really.

**Comment by elad335** [comment]
Move this discussion to forums, the core issue here is fixed.
