### ISSUE TITLE
MEM: Access violation writing location 0x0

### ISSUE THREAD

**Issue by alex-phillips** [RPCS3/rpcs3#3470]
I get the following error when attempting to run Demon's Souls in RPCS3: `MEM: Access violation writing location 0x0`

The problem occurs at the load screen when entering the game. I am able to launch the game, watch the opening cinematic, and create a character. Upon completing character creation, the load screen comes up and I get the error.

My character is saved and on next launch, I can choose to 'load game' instead, but the same loading screen crash occurs.

I've talked with several people in the discord channel and tried just about every CPU/GPU configuration possible. I *believe* we've ruled out the GPU being an issue since using `null` as the renderer (although no video is displayed in the window) I can still hear the game and hit the necessary buttons to navigate through the menu and the same crash occurs.

This problem occurs on both my Linux and Windows 10 partition on this computer.

Below are my logs following one of these crashes:

https://paste.ubuntu.com/25581739/

![screenshot from 2017-09-19 11-04-29](https://user-images.githubusercontent.com/3135216/30663365-68fc98c6-9e18-11e7-9fc2-5e5f35de67e8.png)

**Comment by hcorion** [comment]
I made a custom build with TSX removed (because I thought it might have to do with buggy TSX implementation), and that didn't fix it either.

Something about his CPU (E3-1505M v5), doesn't work well with RPCS3.

**Comment by Papermanzero** [comment]
Same error for Heavy Rain Move Edition (EU)

**Comment by hcorion** [comment]
Not at all related @Papermanzero

**Comment by alex-phillips** [comment]
It looks like this issue may have been related to a bad dump of the game. I re-did it and I can actually get in-game now.

I was assuming that if it was a bad dump the game wouldn't run at all, but apparently that isn't the case.
