### ISSUE TITLE
Demon's Souls [BLES00932] - video flickering.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#3476]
After fbo_fixes or something. After I test game and exit to the main menu, it happens.
https://youtu.be/bT61XEtifZg
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1322355/RPCS3.log.gz)

**Comment by kd-11** [comment]
Classic cellSail issue. If it started after fbo_fixes, use https://github.com/RPCS3/rpcs3/issues/3474

**Comment by isshininu** [comment]
I want to bump this issue, this time with a video and a short explanation!

https://youtu.be/kD1Gp-fFR14

After exiting game through "Options" - "Quit Game" main menu screen is flickering. It happens each time and can be easily reproduced.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1595874/RPCS3.log.gz)

**Comment by isshininu** [comment]
Also affects end titles:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1689162/RPCS3.log.gz) (this is https://ci.appveyor.com/api/buildjobs/g8qh72ukpnlp4610/artifacts/rpcs3-v0.0.4-2018-02-02-55821041_win64.zip)

https://youtu.be/ti50VGtB0yk
