### ISSUE TITLE
NPUB31366 - Soul Calibur 2 HD Online Black Screen with audio

### ISSUE THREAD

**Issue by Kojikun1** [RPCS3/rpcs3#3477]
Game stay Black Screen With Audio after intro video
Tested with last master
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6262/artifacts

**Comment by SakataGintokiYT** [comment]
@Kojikun1 
https://github.com/RPCS3/rpcs3/issues/3474

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
