### ISSUE TITLE
BLJS10286-[Gundam Breaker 2] Game Can not install 

### ISSUE THREAD

**Issue by Kojikun1** [RPCS3/rpcs3#3478]
When are installing the game stop installing and show this error in log
F {PPU[0x1000001] Thread () [0x01388d44]} class std::runtime_error thrown: Verification failed: 
(in file C:\rpcs3\rpcs3\Emu\Cell\lv2\sys_lwcond.cpp:116)

And in some old build this game install it works

**Comment by AniLeo** [comment]
Missing log and PR that regressed it.
Reopen after editing with the information.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by Kojikun1** [comment]
Unfortunately I do not know which pr broke this
