### ISSUE TITLE
No Pad settings in I/O

### ISSUE THREAD

**Issue by Hatsune-xMikux** [RPCS3/rpcs3#3480]
Xinput is not showing up or there is no settings in I/O global or game settings Xbox One controller won't work via Bluetooth or USB.

Error on boot:
E CFG: cfg::try_to_enum_value(''): invalid enum value: invalid stoull argument

Windows 10 (64 bit) Build 16288.1

**Comment by Megamouse** [comment]
try it in the actual pad settings. it has changed a bit, so don't freak out

**Comment by AniLeo** [comment]
Not an issue, it's not on I/O anymore, it's on Configuration -> Pads.
