### ISSUE TITLE
Strict Rendering Mode crashes some games in Vulkan

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3484]
Here's a typical error log on the crash:
> F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is FFFFFFFCh
> (in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:1070)

It's mainly related to Unreal Engine 3 games such as Saw or Silent Hill Downpour, but also noticed at Castle of Illusion and Demon's Souls which seems to be not used UE3. Unfortunately, some games have graphical glitches without Strict Rendering Mode option enabled.

**Comment by kd-11** [comment]
These issues are tracked here https://github.com/RPCS3/rpcs3/issues/3474. A fix is in the works and will be available soon.

**Comment by Psycho-A** [comment]
You talk about "Tracker for any regressions introduced after merging #3458", but it was always for me far time ago, especially for UE3 games...
