### ISSUE TITLE
Minecraft [NPUB31419] - XInput Left stick not working correctly (walking)

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#3485]
When you walk to the left side everything is fine, but walking to the right I noticed strange behaviour:
You can only walk at full speed to the right or up and down, no diagonal or slight movements are possible.

![image](https://user-images.githubusercontent.com/23019877/30736271-5c2e3512-9f82-11e7-83bf-49d425c1a9ee.png)

**Comment by Marthgun** [comment]
in Trails of Cold Steel 2, you end up switching from run to walk at the diagonals.  so you have to keep it straight up or down to run (which can get a tad annoying).  Not sure if it's related to what you're saying exactly, just mentioning it.

**Comment by firewolfgames** [comment]
It seems this is something with your controller itself, both games work fine for me with an xinput gamepad

**Comment by Megamouse** [comment]
definitely not because the left stick works on every other game and XInput works the same on every game. So there is not distinction between games on XInput side, especially not when using the same controller

**Comment by Marthgun** [comment]
i'm using Xbox 360 controller with xinput enabled.  Only thing i've used or tried.  that's interesting both games work for you though.  ToCS2 is the only game that had controller issues.   maybe it was the game dump.

**Comment by Megamouse** [comment]
I thinkI was missing an update back then
