### ISSUE TITLE
 Rpcs3 crash in Persona 5 while changing personas in Mementos

### ISSUE THREAD

**Issue by NaaleinGrohiik** [RPCS3/rpcs3#3486]
This happened 6 times now with different personas.
It doesn't happen all the time though, just randomly in combat. 
I tried forcing the crash by spamming persona change, but just when I think it is gone the next fight it crashes.

i7 2700K
Gtx 980
build version 0.0.3-6266

**Comment by AniLeo** [comment]
Missing log

**Comment by NaaleinGrohiik** [comment]
Rpcs3 didn't generate log zip file when the game crashes and there is another rpcs3 file 132 mb I think that's the one that get's turned into a zip.

**Comment by AniLeo** [comment]
Compress it yourself with 7-zip or similar

**Comment by NaaleinGrohiik** [comment]
I feel so stupid, I apologize never thought 131 mb would turn to 890 kb


[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1325124/RPCS3.zip)

**Comment by kd-11** [comment]
@NaaleinGrohiik Screencap the error box. Does it crash rpcs3.exe or nvoglv.dll?

**Comment by NaaleinGrohiik** [comment]
I think it's rpcs3.exe. This crash exactly happens in combat when i press triangle and then switch the personas with R1 or L1.

![untitled](https://user-images.githubusercontent.com/32201158/30758606-04ba7c2a-9fcb-11e7-9ca3-8bc9863eafac.jpg)

**Comment by AniLeo** [comment]
I can't reproduce this, maybe need to fight more..

**Comment by NaaleinGrohiik** [comment]
I tried changing the settings(had write color buffer and invalidate cache every frame on) still same problem :(. weird thing is if I press triangle and then square(for detailed persona view) and then switch personas it does not crash, it also does not crash when I press R1 to directly get the persona with the weakness spell.


![erztert](https://user-images.githubusercontent.com/32201158/30760034-71e16282-9fd0-11e7-875d-ff3b988c2b9b.jpg)

**Comment by NaaleinGrohiik** [comment]
Good news, I just updated to 0.0.3-6267 from 0.0.3-6266 and it seems the problem is gone. Thanks.
