### ISSUE TITLE
SPU: FM instruction inaccuracies (Precise vs. Fast/ASMJIT)

### ISSUE THREAD

**Issue by PZerua** [RPCS3/rpcs3#3487]
I found out that starting Journey with SPU Interpreter (Precise) allows it to go ingame (but seems to have issues uploading the textures, so it  doesn't show any 3D graphics).

![7d08ed8adc6f603a08b59c99cfb1f051](https://user-images.githubusercontent.com/8772233/30756295-6d894598-9fca-11e7-9eca-20ebdf5a22a7.png)

I tested the PR #3388, but it doesn't prevent the halt.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1325305/RPCS3.log.gz)

P.D: The faulty instruction is FM (Float multiply) in SPU fast and ASMJIT. If I make SPU Fast to use the Precise implementation, the issue is solved. I have isolated the output of the instruction in one specific thread for each of the interpreters, making clear that it gives different outputs for specific inputs (NaN, and inf).

Here is a zip with both outputs: [SPU_Comparison.zip](https://github.com/RPCS3/rpcs3/files/1349600/SPU_Comparison.zip)

For example, in SPU Fast:
```
anyNumber(included 0) * inf = inf
```
In SPU Precise:
```
anyNumber * inf = NaN
```

**Comment by SerJons** [comment]
![1](https://user-images.githubusercontent.com/6071784/30775046-5ac42038-a095-11e7-948e-29f3e01dc2db.jpg)
![2](https://user-images.githubusercontent.com/6071784/30775047-5cfb3878-a095-11e7-82c5-1583b491cdbb.jpg)

Yep, if fix halt. Journey probably going playable.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1326671/RPCS3.log.gz)

**Comment by PZerua** [comment]
I have updated the issue with further information I have found.

**Comment by AniLeo** [comment]
Hm, finding matches with #3388 
Just needs a correct implementation

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/3526

**Comment by PZerua** [comment]
Fixed

**Comment by Zangetsu38** [comment]
yes, juste render veyr glitched, and very slow speed ingame
https://cdn.discordapp.com/attachments/272875751773306881/364868552739651584/unknown.png
