### ISSUE TITLE
Black screen on Boot and Run with Catherine

### ISSUE THREAD

**Issue by AshThatBurns** [RPCS3/rpcs3#3489]
When I boot and run the game Catherine on RPCS3, first the game screen flashes in different colors, and after a few seconds, the picture in the corner that Catherine uses in the loading screen comes, then everything goes black and some background music starts to play. I'm pretty new to using rpcs3, I've installed the lastest bios file, my gpu is GTX 1050, my log file is in the attached text file.

[log.txt](https://github.com/RPCS3/rpcs3/files/1325442/log.txt)

**Comment by AniLeo** [comment]
Missing log. 
Please fix the issue by providing a RPCS3.log file and the drivers version you're using.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.
