### ISSUE TITLE
persona 5 memotes frezzing issues

### ISSUE THREAD

**Issue by asbel123** [RPCS3/rpcs3#3491]
i tried new latest build fix the shadows.
i cant go to mementoes area frezze on the loading screen.

 i done the pe teacher first dugoen i cant go in mementoes frezze the game .

**Comment by AniLeo** [comment]
Please try actually reading the guidelines

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
