### ISSUE TITLE
[Feature Request] Make xinput gamepad as default option when it is recognised by first run

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#3492]
[Suggestion] Make xinput gamepad as default option when it is recognised by first run

Currently only keyboard sets as default.

**Comment by AniLeo** [comment]
What do you mean?
Note that Pad Settings are global too.

**Comment by isshininu** [comment]
Oh my, here is the response.

I mean, when RPCS3 starts first time and finds gamepad inserted into USB port, it could automatically make it input device by default.

**Comment by AniLeo** [comment]
Whatever controller you set is saved to config and used until you change it.

I don't think it makes sense defaulting to gamepad just because it's connected, what if I want to use keyboard on RPCS3? Just let people choose manually, it isn't hard to click a couple of buttons.

**Comment by isshininu** [comment]
ok then
