### ISSUE TITLE
Rendering errors on Dragon Ball Raging Blast 2 Demo [NPEB90287] 

### ISSUE THREAD

**Issue by woj1993** [RPCS3/rpcs3#3493]
If you play game for the first time as (goku super sayan or Dabura) it will throw many unknow command errors and there will be many graphical glitches (especially on goku) for example:
![obraz](https://user-images.githubusercontent.com/11420970/30774690-f64b1e30-a086-11e7-8b37-4d37cad724db.png)
Log+shaders cache+shaders log:
[Dragon Ball Raging Blast 2 Demo Schaders+Logs.zip](https://github.com/RPCS3/rpcs3/files/1326647/Dragon.Ball.Raging.Blast.2.Demo.Schaders.Logs.zip)
Also if you try to reload it will trow many other RSX errors (this log)[it crashed before going into game]:
[Dragon Ball Raging Blast 2 Demo.zip](https://github.com/RPCS3/rpcs3/files/1326626/Dragon.Ball.Raging.Blast.2.Demo.zip)
My CPU is Intel(R) Core(TM) i5-2300 CPU 
@ 2.80GHz. 
RAM:4GB 
GPU: ASUS NVIDIA GT440 1GB GDDR3 OpenGL
Edit: Dabura has more interesting error: RSX: Texture unit 3 is sampled as both a shadow texture and a depth texture
Dabura Log:[Dragon Ball Raging Blast 2 Demo Dabura Schaders.zip](https://github.com/RPCS3/rpcs3/files/1326661/Dragon.Ball.Raging.Blast.2.Demo.Dabura.Schaders.zip)
P.S. If something else is needed tell me.

**Comment by AniLeo** [comment]
Needs retesting on latest master. 
If someone has a more recent GPU please test this game on both OpenGL and Vulkan to see if the issue is there.

Also, forum thread needs updating: https://forums.rpcs3.net/thread-173766.html

**Comment by woj1993** [comment]
@AniLeo I tested in on master (Date: 11-10-2017) and it stil has the same errors.
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1376693/RPCS3.log.gz)
Sorry I can't help you with more recent GPU tests but from what I see error was on Vulcan too (watch last video from forum thread. He tested it on NVIDIA GeForce GTX 1050 Ti 4 GB and test was on 20-09-2017).

**Comment by AniLeo** [comment]
Clothing still flickers and there's RSX method flood, probably a corruption issue

**Comment by benderscruffy** [comment]
still a problem on opengl
shadows are not correct aswell
![dragon](https://user-images.githubusercontent.com/2696404/66190436-8d482100-e6be-11e9-9fa2-d69c344459f7.PNG)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3689526/RPCS3.zip)

**Comment by MarioSonic2987** [comment]
@benderscruffy 
Shadows are working with a GTX 970 in both backends:

![image](https://user-images.githubusercontent.com/20027681/66196875-94a90380-e699-11e9-93f9-8634bbe2a93c.png)
![image](https://user-images.githubusercontent.com/20027681/66196588-16e4f800-e699-11e9-816a-c8c74b0fd8e0.png)

**Comment by benderscruffy** [comment]
any special settings WCB or SRM

**Comment by MarioSonic2987** [comment]
@benderscruffy No. It doesn't require any special setting. It could be an AMD-specific bug.

**Comment by kd-11** [comment]
Probably caused by the same issue as https://github.com/RPCS3/rpcs3/issues/6701 (Bad AMD drivers for old cards). Same suggestion applies here; give linux+mesa a try.

**Comment by woj1993** [comment]
@kd-11 I want to ask: Do you want/need RSX Capture?
If so how to do it?

**Comment by kd-11** [comment]
For memory corruption? No. That just means the emulator is in a broken state. Even if I replayed the capture on a real PS3 it would still be broken.
