### ISSUE TITLE
Red Dead Redemption doesn't start

### ISSUE THREAD

**Issue by Joycon75** [RPCS3/rpcs3#3494]
**Hello,

I'm unsuccessfully trying to play RDR GOTY on latest version of RPCS3
Can you check the logs and tell me if there is something relevant ?

my config : 
GPU =GTX1080
CPU = i5 3570K

Thanks !**

`S LDR: Boot from gamelist per doubleclick: done
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2-3830CB775801B378-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2-libsysmodule.sprx-09F72D494851FEC4-ivybridge.obj
U {PPU[0x1000000] Thread (main_thread) [0x000f6d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x000f30c4]} PPU: LLVM: Loaded module v2-libsre.sprx-7BD57B68D8CA8EBC-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread) [0x000f30c4]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x000f30c4]} PPU: LLVM: Loaded module v2-libfs.sprx-BB8655E4C5C49381-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread) [0x000f30c4]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
S {PPU[0x1000000] Thread (main_thread) [0x000f30c4]} PPU: LLVM: Loaded module v2-librtc.sprx-9CB190F178FA7E82-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread) [0x000f30c4]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx
E {PPU[0x1000000] Thread (main_thread) [0x00010844]} sys_vm: sys_vm_memory_map(vsize=0x2000000, psize=0x200000, cid=0xffffffff, flags=0x200, policy=0x1, addr=*0x65880)
U {PPU[0x1000000] Thread (main_thread) [0x00143c8c]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
U {PPU[0x1000000] Thread (main_thread) [0x00143d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5
U {PPU[0x1000000] Thread (main_thread) [0x00149e58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00149e58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
S {SPU[0x2000000] Thread (PrimaryCellSpursKernel0)} SPU: SPU Database initialized...
S {SPU[0x2000004] Thread (PrimaryCellSpursKernel4)} SPU: SPU Recompiler (ASMJIT) created...
U {PPU[0x1000000] Thread (main_thread) [0x00143d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00149e58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00149e58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
E {PPU[0x1000000] Thread (main_thread) [0x00010970]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0xf0, alignment=0x10000000, alloc_addr=*0xd0040b44)
E {PPU[0x1000000] Thread (main_thread) [0x00010988]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0xf0, alignment=0x10000000, alloc_addr=*0xd0040b44)
E {PPU[0x1000000] Thread (main_thread) [0x000109a0]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0xf0, alignment=0x10000000, alloc_addr=*0xd0040b44)
U {PPU[0x1000000] Thread (main_thread) [0x00028dcc]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x00028d94]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x1000000] Thread (main_thread) [0x00027514]} libnet TODO: sys_net_show_ifconfig
S {PPU[0x1000000] Thread (main_thread) [0x000f30c4]} PPU: LLVM: Loaded module v2-libfiber.sprx-90B538A6D4A84178-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread) [0x000f30c4]} sys_prx: Loaded module: /dev_flash/sys/external/libfiber.sprx
U {PPU[0x1000000] Thread (main_thread) [0x003af368]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x003af368]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
S {PPU[0x1000000] Thread (main_thread) [0x00028d24]} sysPrxForUser: Process finished
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+010200-5BB932283D1A081B-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+0511A0-A3C180DBE9B6AFBF-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+091B74-0F60843157897EE7-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+0D2768-285E5D1FDF472873-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+113540-8CEFD6AD67A3D9EA-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+154778-29326E2FDF37247A-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+195338-3F965D9E25957B12-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+1D5900-D59F0812EBCB24A5-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+215DAC-6B581B0CC55FD190-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+256268-304D81E4D7593834-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+2962C8-394ACC13CDD89DB4-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+2D6344-460146D0693A0A2D-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+3169C4-D6EB716C44BA1AA9-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+357234-69812373D60B2F72-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+397DB8-6B3E4931CCFB3484-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+3D9220-4E61FBA4C2D6C8F9-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+41A34C-41E7409AE173A239-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+45B448-6E18B0EA89A01BF3-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+49C6A4-27FF768C777F685A-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+4DDD20-7131A58CDD674256-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+51E9E0-2AB7D86F411B708E-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+55F8C4-896A4D680E8CC9BE-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+59FD80-5776A44FDDA5C1EB-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+5E0C50-29FE5279359648E5-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+621CE4-8783F2ADC32FF2FD-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+662520-D4A09E9C0BE9EB8F-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+6A37BC-A21A6882D5F68943-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+6E3D20-9390ACB9410CC3D0-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+7241E4-411650300BDC8931-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+7650AC-DFE3AA4850A471C6-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+7A5E1C-344C5BFC825B3FB5-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+7E6998-08218C63A2158026-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+827578-C19BEA5D3C4670B2-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+868118-C8AAE05974F8EBEA-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+8A8BA0-9CB1CB3F0B6247CC-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+8E9920-4D0BC6680A63346E-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+92B040-A4F51A0098869FE8-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+96B9D0-4670A7190B9B44CC-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+9AC938-5DCC83512C2654BA-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+9ED590-8C4DAB061CDF5E9B-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+A2E9A0-3AF1528F6CBCB74C-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+A6FF88-F6F406BEB176CCD9-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+AB1310-9FDA21AAC21FC82B-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+AF24C8-307151C1FE7FE78F-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+B33044-2FE02283EB71ECD8-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+B743B0-5B768B4512BFD21D-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+BB5748-CF7F814C15B5DCC5-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+BF6DC4-A0EFC84F54363C6A-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+C376C4-BADAF02783AC23E1-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+C78808-11134A545F118A90-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+CB96A8-AD8630D35EE53478-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+CFA12C-97091F8A19621A1F-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+D3A9D0-C2CB82965E61A9F4-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+D7A800-E4A58EC9965EDEF9-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+DBA7F4-0C404AAFD3737C00-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+DFA778-9DC4ADB91A3FFD5C-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+E3A6A0-047877CACBBAAB97-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+E7A6A8-8D5379196D900EF7-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+EBA63C-715F8153DACFFD16-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+EFA240-310B16F15A280FCF-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+F3A5D8-5664982114C93875-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+F7A978-F8CD1AAAFDD449FC-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+FBA9D0-D932BDC44483C58A-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+FFAD28-05C1B55B7A0A9B31-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+103B0F8-967FAAA22EDB82E2-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+107B60C-E916EDF250E3F207-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+10BB68C-B0CCEDFC68DB87A8-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+10FB700-FAFFFBA746A4ED00-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2-libsysmodule.sprx-09F72D494851FEC4-ivybridge.obj
U {PPU[0x1000000] Thread (main_thread) [0x0183bd8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x018380c4]} PPU: LLVM: Loaded module v2-libsre.sprx-7BD57B68D8CA8EBC-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread) [0x018380c4]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x018380c4]} PPU: LLVM: Loaded module v2-libfs.sprx-BB8655E4C5C49381-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread) [0x018380c4]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
S {PPU[0x1000000] Thread (main_thread) [0x018380c4]} PPU: LLVM: Loaded module v2-librtc.sprx-9CB190F178FA7E82-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread) [0x018380c4]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx
E {PPU[0x1000000] Thread (main_thread) [0x00010d1c]} sys_vm: sys_vm_memory_map(vsize=0x2000000, psize=0x200000, cid=0xffffffff, flags=0x200, policy=0x1, addr=*0x1559880)
U {PPU[0x1000000] Thread (main_thread) [0x01888c8c]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
U {PPU[0x1000000] Thread (main_thread) [0x01888d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5
U {PPU[0x1000000] Thread (main_thread) [0x0188ee58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0188ee58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
S {SPU[0x2000000] Thread (PrimaryCellSpursKernel0)} SPU: SPU Database initialized...
S {SPU[0x2000004] Thread (PrimaryCellSpursKernel4)} SPU: SPU Recompiler (ASMJIT) created...
U {PPU[0x1000000] Thread (main_thread) [0x01888d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x0188ee58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0188ee58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
E {PPU[0x1000000] Thread (main_thread) [0x00010e80]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0xf0, alignment=0x10000000, alloc_addr=*0xd0040b24)
E {PPU[0x1000000] Thread (main_thread) [0x00010e98]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0xf0, alignment=0x10000000, alloc_addr=*0xd0040b24)
E {PPU[0x1000000] Thread (main_thread) [0x00010eb0]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0xf0, alignment=0x10000000, alloc_addr=*0xd0040b24)
E {PPU[0x1000000] Thread (main_thread) [0x01137514]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH
E {PPU[0x1000000] Thread (main_thread) [0x0113746c]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH x839
E {PPU[0x1000000] Thread (main_thread) [0x01137514]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH
E {PPU[0x1000000] Thread (main_thread) [0x0113746c]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH
E {PPU[0x1000000] Thread (main_thread) [0x01137514]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH
E {PPU[0x1000000] Thread (main_thread) [0x0113746c]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH
E {PPU[0x1000000] Thread (main_thread) [0x01137514]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH
U {PPU[0x1000000] Thread (main_thread) [0x01137514]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x011374dc]} sysPrxForUser TODO: _sys_process_at_Exitspawn
U {PPU[0x1000000] Thread (main_thread) [0x01134e94]} libnet TODO: sys_net_show_ifconfig
S {PPU[0x1000000] Thread (main_thread) [0x018380c4]} PPU: LLVM: Loaded module v2-libfiber.sprx-90B538A6D4A84178-ivybridge.obj
S {PPU[0x1000000] Thread (main_thread) [0x018380c4]} sys_prx: Loaded module: /dev_flash/sys/external/libfiber.sprx
U {PPU[0x1000000] Thread (main_thread) [0x01af4368]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x01af4368]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE
U {PPU[0x1000000] Thread (main_thread) [0x011339cc]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0xd00407a0, options=0x0)
U {PPU[0x1000000] Thread (main_thread) [0x018383a0]} sys_prx TODO: _sys_prx_unload_module(id=0x23025f00, flags=0x0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0113746c]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
U {PPU[0x1000000] Thread (main_thread) [0x0113746c]} cellGcmSys TODO: cellGcmSetZcull(index=0, offset=0x710000, width=1152, height=640, cullStart=0x0, zFormat=0x2, aaFormat=0x3, zCullDir=0x0, zCullFormat=0x1, sFunc=0x2, sRef=0x0, sMask=0xff)
E {PPU[0x1000000] Thread (main_thread) [0x0113586c]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (11)
E {PPU[0x1000000] Thread (main_thread) [0x0113746c]} cellGcmSys: cellGcmSetTileInfo: bad compression mode! (7)
E {PPU[0x1000000] Thread (main_thread) [0x018b7ee4]} sys_fs: sys_fs_stat(“/dev_hdd0/game/BLES00680/USRDIR/rdr2_installed.sdat”) failed: not found
E {PPU[0x1000000] Thread (main_thread) [0x018b7ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x018b7ee4]} sys_fs: sys_fs_stat(“/dev_hdd0/game/BLES00680/USRDIR/rdr2_installed.sdat”) failed: not found
E {PPU[0x1000000] Thread (main_thread) [0x018b7ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x018b7ee4]} sys_fs: sys_fs_stat(“/dev_bdvd/PS3_GAME/USRDIR/rdr2_installed.sdat”) failed: not found
E {PPU[0x1000000] Thread (main_thread) [0x018b7ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x018b7ee4]} sys_fs: sys_fs_stat(“/dev_bdvd/PS3_GAME/USRDIR/rdr2_installed.sdat”) failed: not found
E {PPU[0x1000000] Thread (main_thread) [0x018b7ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT
U {PPU[0x1000000] Thread (main_thread) [0x018383a0]} sys_prx TODO: _sys_prx_unload_module(id=0x23026000, flags=0x0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x018b7ee4]} sys_fs: sys_fs_stat(“/dev_bdvd/PS3_GAME/USRDIR/rdr2_layer0.rpf”) failed: not found
E {PPU[0x1000000] Thread (main_thread) [0x018b7ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x018b8090]} sys_fs: sys_fs_open(“/dev_bdvd/PS3_GAME/USRDIR/rdr2_layer0.rpf”): failed to open file (flags=0, mode=0)
E {PPU[0x1000000] Thread (main_thread) [0x018b8090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
S sys_process: Process finished`

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by Joycon75** [comment]
Ok, so RDR is masked as "Ingame:  Games that go somewhere but not far enough to be considered playable" on websites.
So we can't open issues about this game...

got it

**Comment by AniLeo** [comment]
Maybe actually try reading the guidelines first?

**Comment by Joycon75** [comment]
Thank you for this helpfull answer.
Next time, ask me to google my question... maybe google won't redirect me to a github which again redirect me to google.
bootlooped :)

**Comment by Joycon75** [comment]
not matter, in the [forum](https://forums.rpcs3.net/thread-188169-page-2.html) RDR is also in a "broken mode".
I will test an another game.

**Comment by Zangetsu38** [comment]
Normal, verify you folder game, missing file

**Comment by AniLeo** [comment]
I'm not sure if you're trolling but in the event you're not, once more:

"the GitHub Issue Tracker is not the place to ask for support"
