### ISSUE TITLE
Bayonetta Demo Texture resides in render target memory, but requested type is not 2D (2)

### ISSUE THREAD

**Issue by woj1993** [RPCS3/rpcs3#3495]
@kd-11 Bayonetta Demo throws "Texture resides in render target memory, but requested type is not 2D (2)" more than 20 times per second.
Log+Shader Cache:[rpcs3-v0.0.3.zip](https://github.com/RPCS3/rpcs3/files/1326802/rpcs3-v0.0.3.zip)

**Comment by AniLeo** [comment]
Known issue but will leave open

**Comment by kd-11** [comment]
Retest, should've been fixed over a month ago.

**Comment by woj1993** [comment]
@kd-11 Ok this error is fixed but two new emerged.
E {rsx::thread} RSX: Cached object for address 0xC7C8F100 was found, but it does not match stored parameters.
E {rsx::thread} RSX: 16 x 16 vs 16 x 16
And this

![bayonetta](https://user-images.githubusercontent.com/11420970/34644443-0149a90c-f337-11e7-8b78-132aa0a5d9dc.jpg)
Should I close this issue and make new?
