### ISSUE TITLE
Persona 5 (BLUS31604) - Fatal Error/Crash

### ISSUE THREAD

**Issue by SirKaffee** [RPCS3/rpcs3#3497]
Emulator received an error message and crashed when I went to the first rooftop encounter with Ryuji. It occurred as soon as dialogue began. Before this, the game was running all right, with a few minor bugs.

Here is the error message (sorry for not copying it. didn't read the blurb at the end and just screencapped it.): https://gyazo.com/d8f2be3e2e6e9ca8407290e4c3a52961 

As I said before, there were a couple minor bugs worth mentioning here. There was a small diagonal slash (of a variety of colors) from the date indicator to about midway through the window, maybe a little smaller. I've seen this discussed before (from what I understand, it's an issue with the Vulkan renderer), but I thought it was worth mentioning.

Also, in a few cutscenes (specifically the first jail/castle encounter with Kamoshida), parts of Kamoshida's hair became very long and narrow, protruding from his head. I should also say that I haven't returned to see if this was a "one-time" error at this time since it's kinda late right now and I just decided to report this.

**Comment by Asinin3** [comment]
You need to post the rpcs3.log.gz file, not a screenshot or a copy/paste from the log inside the rpcs3 window.

**Comment by AniLeo** [comment]
Issue will be reopened after guidelines are complied with.
Missing log file and system information (AMD driver version too).

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.
