### ISSUE TITLE
Dai-3-Ji Super Robot Taisen Z Jigoku-hen crash Dai-3-Ji Super Robot Taisen Z Jigoku-hen crash on rpcs3-v0.0.3-2017-09-23 

### ISSUE THREAD

**Issue by sinangis** [RPCS3/rpcs3#3499]
Dai-3-Ji Super Robot Taisen Z Jigoku-hen crash on rpcs3-v0.0.3-2017-09-23 with warning E {rsx::thread} RSX : cannot perform scale blit for depth/stencil images

i using Nvidia card and AMD prosesor

please help..

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
