### ISSUE TITLE
Metal gear solid HD collection (BLUS30847) not launching the games

### ISSUE THREAD

**Issue by Idanlego1001** [RPCS3/rpcs3#3501]
The launcher itself is working (the sound is slow but the launcher itself is at full speed) but when I try launch one of game it's just a black screen

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
