### ISSUE TITLE
White Knight Chronicles Character Creation Freezes

### ISSUE THREAD

**Issue by Dorky106** [RPCS3/rpcs3#3502]
No idea how much this will help at all but here you go
NP++ says the file is too big, so can't easily give that info.
So I put the RPCS3.log into dropbox for you https://www.dropbox.com/s/sq69zw9uqtnjkk4/RPCS3.log?dl=0
I'm using OpenGL, also have tried Vulkan
Below is a picture of where it gets to before locking up.  Audio still plays but the game freezes.
https://www.dropbox.com/s/w4be901xcnje1xn/Screenshot%202017-09-24%2012.42.23.png?dl=0

**Comment by geo98** [comment]
Just a question, you tried with interpreter?

**Comment by Dorky106** [comment]
Just tried both precise and face for PPU and SPU all 4 get to character creation than just freeze up.

**Comment by geo98** [comment]
I meant PPU interpreter, since I had a similar issue with dantes inferno where it froze on a specific part of the game but the sound kept running and the cpu usage too, and switching to interpreter didn't freeze. 

But in your case is probably something different. I hope it get fixed.

**Comment by Dorky106** [comment]
idk if you guys want a new log each time I update this or not.
Probably just going to update it every other week or every month.

**Comment by scribam** [comment]
@Dorky106 Is it still an issue? According to the forums thread (https://forums.rpcs3.net/thread-180906-page-2.html?highlight=white+knight), this game goes ingame.

**Comment by Megamouse** [comment]
happens on white knight chronicles II on both new game WKC1 and WKC2.
The standalone white knight chronicles (1) is fine

**Comment by Dorky106** [comment]
So semi still an issue.

**Comment by davoodinator** [comment]
build 6500 -> WK2 does not get past the creation screen. "Enter your name" freezes there.

**Comment by dio-gh** [comment]
Needs retesting, probably not an issue anymore.

**Comment by Yahfz** [comment]
![image](https://user-images.githubusercontent.com/17715080/67308001-cf030500-f4cf-11e9-8966-928f4b25837e.png)
Works fine. I used both interpreters Fast.

**Comment by AniLeo** [comment]
Closing as reported fixed.
