### ISSUE TITLE
"Load automatic and manual selection" doesn't work in new versions

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3504]
Broken about month ago...
I checked libadec.sprx, libapostsrc_mini.sprx, libavcdec.sprx, libm4aacdec.sprx, libmp4.sprx and libsail.sprx to have ppu modules pre-compiled before starting game. In v0.0.3-5650-4f84edbd they precompiled together with game ELF, but they totally ignored in latest emulator version, and starts to compile only during game on system calls, like it's in "Load syslv2.sprx only" mode. "Automatically load required libraries" seems to be broken too, as it behaves the same way,

**Comment by Nekotekina** [comment]
Loading mode has nothing to do with their precompilation.

**Comment by Psycho-A** [comment]
> Loading mode has nothing to do with their precompilation.

However, manually selected modules *were* precompiled before game start in earlier versions, but do *not* on latest ones! But still, "Manually load selected modules" works as I suppose on last versions too. I guess if user selects "Load automatic and manual selection" he wants to see all modules he selected compiled before game start, unlike to see them compiled during game process. Or what's exactly sense this loading mode has?

**Comment by Nekotekina** [comment]
People who were using this solely for precompilation are wrong. They shouldn't touch these settings unless absolutely necessary for **compatibility**, i.e. one game runs with particular settings but another doesn't.

There is a trick to precompile sprx file manually: just boot sprx file in RPCS3 (possibly by drag and drop) and run it. But I don't want to force anyone to do this, so there is a record in the roadmap to compile all libraries automatically upon the firmware installation.

**Comment by Psycho-A** [comment]
Wrong these people or not, but it doesn't cancel a fact that pre-compiling works in "Manually load.." but it doesn't in "Automatic and manually.." that for me looks illogic. And I anyway guess that precompiling all modules which current game uses is good behavior, and it would be better to add into all existing (except Manual selection) modes. People are unlikely want to search each module in firmware and manually run it to compile.

**Comment by scribam** [comment]
@Psycho-A The feature which compiles all libraries automatically has been implemented. Does that solve this issue or do you expect something else?

**Comment by Psycho-A** [comment]
@scribam New feature uses binding to emulator's installation path which is not very good in some cases, like using standalone game builds based on emulator. If firmware was already installed to dev_flash, it makes new feature totally useless any time we're changing emulator's path. It means that we need to reinstall firmware everytime we change path, otherwise modules will be compiled on-the-fly during game as before. It's strongly needed to make unbinding compiling modules from path hashes and use constant paths instead!

**Comment by Psycho-A** [comment]
@kd-11, I meant data/ folder's *.obj files that compiles after firmware installation. They are hard drive path-sensitive which makes totally useless implemented feature (as said above) when local path was changed. That's why I'm still for old behavior in which user could choose modules to compile before the game starts.

**Comment by Nekotekina** [comment]
Old behaviour won't be implemented. This one is unrelated issue.
