### ISSUE TITLE
Dragon Ball Ragin Blast Error

### ISSUE THREAD

**Issue by zerr10** [RPCS3/rpcs3#3505]
i7 6700 skylan 3.4Ghz 8 GB RAM dual DDR4 2133Mhz GTX 1070 8GB

rpcs3-v0.0.3-2017-09-16-c18e71ca_win64  Vulcan

i Get this error when loading map only black Screen and music.

E {rsx::thread} RSX: Invalid RSX method 0xac00 (arg=0x10800140)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)

**Comment by zerr10** [comment]
some won help ?

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by zerr10** [comment]
https://forums.rpcs3.net/member.php?action=activate&uid=1457&code=gQ88erSt

ii traiet POST THER BUT THER DONT CAN I DONT SEE ME POST why ???

**Comment by AniLeo** [comment]
It says you need to wait for moderation approval for some reason.
Stop spamming the GitHub repository.

**Comment by arkhamsaiyan** [comment]
doesn't it say DONOTUSE on DX12? lol
