### ISSUE TITLE
Disgaea 4 ppu error

### ISSUE THREAD

**Issue by violn** [RPCS3/rpcs3#3512]
F {PPU[0x100000a] Thread (fios mediathread 9) [0x02b441cc]} class std::runtime_error thrown: Verification failed (e=0x70): file::write
(in file C:\rpcs3\Utilities\File.cpp:886)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by violn** [comment]
Thaks
