### ISSUE TITLE
Silent Hill Downpour - broken lighting and shadows

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3515]
Hoped on fixes from #3458, but still no any changes for this game. Game uses Unreal Engine 3, and lighting is overbrighten and buggy, and no any dynamic shadows from characters and objects. Some similar I see in Saw game that uses UE3 too.

**Comment by hcorion** [comment]
You have `Invalidate Cache Every Frame` enabled @Psycho-A ?

**Comment by Xcedf** [comment]
Nope, Invalidate Cache Every Frame ain't work for these games

**Comment by AniLeo** [comment]
Needs retesting

**Comment by Xcedf** [comment]
Unlikely fixed, non of my UE3 games fixed

**Comment by kd-11** [comment]
In that case shouldnt all ue3 graphical bugs be coalesced into one tracker? It would make life easier for testers as well as developers.

**Comment by Psycho-A** [comment]
@kd-11, agree with you, that would be really useful and noticeable. There are a lot of UE3 games which really good and have no PC versions.

**Comment by AniLeo** [comment]
Superseded by  #4025
