### ISSUE TITLE
Yakuza Games - White border around game

### ISSUE THREAD

**Issue by 16bitblastprocessing** [RPCS3/rpcs3#3520]
For some reason there is some fading white border in Yakuza 3 when you play it in RPCS3. This does not appear on real hardware.

Video: https://www.youtube.com/watch?v=gNUJri-Gj24

![rpcs3_2017-09-30_19-44-34](https://user-images.githubusercontent.com/31392773/31057609-bd64fb32-a6a2-11e7-956b-6dadc1aef8f8.png)

Log File:  [RPCS3 - Yakuza 3.zip](https://github.com/RPCS3/rpcs3/files/1347397/RPCS3.-.Yakuza.3.zip)

**Comment by Renusek** [comment]
![ishin](https://user-images.githubusercontent.com/4978744/31554899-605e6a6c-b03f-11e7-82ce-95068eec5f5e.png)

The same issue with Ryu ga Gotoku Ishin BLJM61149

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1383166/RPCS3.log.gz)

**Comment by Renusek** [comment]
Also in Ryu ga Gotoku Ishin demo NPJB90690

![unknown](https://user-images.githubusercontent.com/4978744/31555491-850d01a0-b041-11e7-9a48-35c7b6e7f24f.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1383218/RPCS3.log.gz)

**Comment by Renusek** [comment]
@AniLeo it was fixed some time ago (not sure which PR did this tho), can be closed

**Comment by AniLeo** [comment]
Closing as solved
