### ISSUE TITLE
Persona 5 freezing at the title screen.

### ISSUE THREAD

**Issue by AnonTheHuman** [RPCS3/rpcs3#3524]
I get this error after I open Persona 5 and let it load until the title screen which causes it to freeze.

E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: unknown origin (0)

U {PPU[0x1000000] Thread (main_thread) [0x012443a0]} sys_prx TODO: _sys_prx_unload_module(id=0x2300b800, flags=0x0, pOpt=*0x0)
E {PPU[0x1000015] Thread (UNLOCK Thread) [0x001977f4]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x2, statusCb=*0xce3f18, arg=*0x0, options=0x1)
E {PPU[0x1000000] Thread (main_thread) [0x009011a4]} 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [1]
U {PPU[0x1000016] Thread (addContSyncThread) [0x012443a0]} sys_prx TODO: _sys_prx_unload_module(id=0x23010f00, flags=0x0, pOpt=*0x0)
**F {PPU[0x1000017] Thread (xrd664_list_load) [0x00ad7b00]} class std::runtime_error thrown: Verification failed: (in file C:\rpcs3\rpcs3\Loader\PSF.cpp:118)**

Specs just in case: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz | 8 Threads | 31.95 GiB RAM | AVX | TSX

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1350448/RPCS3.log)

**Comment by AniLeo** [comment]
Several settings are wrong, use the forums if you need support and read the tooltips in the emulator by hovering settings.

Very likely invalid issue, need to confirm what's causing the verification failed there.

**Comment by kd-11** [comment]
Typical corrupted save issue. It happens.

**Comment by AniLeo** [comment]
Can close then. Remove your existing saves and retry.

Make sure you have a way to backup your saves like a cloud synced folder. 
Although I finished the whole game without getting a single save corrupted, it does rarely happen.

**Comment by AnonTheHuman** [comment]
Yep. Removing a folder named NPUB31848-00--005-- fixed the issue. Thanks.
