### ISSUE TITLE
vulkan player not showing on windows nor is D3D

### ISSUE THREAD

**Issue by mahbeermalik** [RPCS3/rpcs3#3525]
i have downloaded the latest version of rpcs3, visual studio 64 bit, and i have direct x 12 but still D3D is not showing i also dont have vulkan player
![rpcs3 issue](https://user-images.githubusercontent.com/32492527/31138068-a3cab956-a886-11e7-8578-f2aaecebac23.png)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
