### ISSUE TITLE
Dark Souls - BLES01765: Game Froze

### ISSUE THREAD

**Issue by olethorin** [RPCS3/rpcs3#3528]
Running Dark Souls from fresh start for ~30 minutes and was averaging ~10 FPS when game froze. Emulator did not crash and game could be restarted.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1354306/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/1354307/TTY.log)

Computer Stats:
Windows 7
Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
GTX 1050TI with 4G RAM

RPCS3 Version:
RPCS3 v0.0.3-3-eb8af97 Alpha | HEAD

Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz | 8 Threads | 11.96 GiB RAM | AVX

**Comment by geo98** [comment]
@AniLeo
