### ISSUE TITLE
Saint Seiya Sanctuary Battle [BLES01421] white clothes

### ISSUE THREAD

**Issue by marsselluo** [RPCS3/rpcs3#3531]
The armor of the characters  are blank, the problem appears on Vulkan and OGL. The game runs stable at 30 FPS. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1355924/RPCS3.log.gz)
![sem titulo](https://user-images.githubusercontent.com/30375393/31178084-5a186b92-a8ee-11e7-88da-a3eaea1e58b6.jpg)

**Comment by marsselluo** [comment]
With the latest build, using vulkan+strict rendering mode, the game has been fixed and runs nearly perfect at 28-30 fps. Using ogl+strict rendering mode, the problem also has been fixed but the performance is poor, 10-15 fps. Without strict rendering mode the problem dont appear but the image turns out of focus. The only problem still observed at the game is the pre rendered videos stutter all time but a lot of games have this same problem. 
Thanks very much and congratulations for this great project. Just sorry for my bad english.

**Comment by marsselluo** [comment]
I forgot my specs:
Core i7 2600@3.4ghz
16gb ram
Gtx960 4gb with the latest Nvidia drivers 388.31
Windows 10 x64 Fall Creators

**Comment by AniLeo** [comment]
Closing as reported issue has been solved as described above
