### ISSUE TITLE
Dante Inferno: no cinematics

### ISSUE THREAD

**Issue by legluondunet** [RPCS3/rpcs3#3533]
Hello,
cinematics does not play in Dante Inferno.

I joined the logs.
Other informations:

rcps3 config:
RCPS3 version rpcs3-v0.0.3-2017-10-02-81b3e7e-8244_linux64.Appimage
interpreter /OpenGL/automatic load required library

Game: 
Dante's Inferno (EU PAL) BLUS30405

Computer config:
Ubuntu 17.10 Artful Aardvark 64 bits - NVIDIA GeForce GTX 770 - official Ubuntu Nvidia drivers 384.90 - 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 8 Go RAM

**Comment by AniLeo** [comment]
Please read the guidelines and fix your issue

**Comment by legluondunet** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1366884/RPCS3.log.gz)
TTY.log is empty

Do you have all the info needed?

Thank you for your help.

**Comment by AniLeo** [comment]
This is reported working on current master, do you still have this issue?

Will be closed as fixed otherwise.

**Comment by legluondunet** [comment]
I just downloaded the last RCPS3 appimage version, the issue is still here.

**Comment by AniLeo** [comment]
RPCS3 does not read that files because they don't exist in your disc, that's what ENOENT means

**Comment by legluondunet** [comment]
This is the tree of the game:

BLUS30405[Dantes.Inferno.Divine.Edition]/
├── PS3_DISC.SFB
└── PS3_GAME
    ├── ICON0_01.PNG
    ├── ICON0_02.PNG
    ├── ICON0_03.PNG
    ├── ICON0.PNG
    ├── ICON1.PAM
    ├── LICDIR
    │   └── LIC.DAT
    ├── PARAM.SFO
    ├── PIC1.PNG
    ├── PS3LOGO.DAT
    ├── SND0.AT3
    ├── TROPDIR
    │   └── NPWR00745_00
    │       └── TROPHY.TRP
    └── USRDIR
        ├── BIGFILE0.VIV
        ├── BIGFILE1.VIV
        ├── BIGFILE2.VIV
        ├── ealogo.vp6
        └── EBOOT.BIN

Effectively, there is no movies folder in PS3-GAME/USRDIR

I don't understand what happened

**Comment by AniLeo** [comment]
Just because the game tries to read a file doesn't mean it absolutely has to be there.. Could be part of debug checks, for example

**Comment by legluondunet** [comment]
as you can see on this Youtube video, the cinematics start before the menu appear. I have ealogo.vp6 but RCPS3 dies not play it.

**Comment by legluondunet** [comment]
I think I made a bad rip, it's not RCPS3 related.
Thank you for your help.

**Comment by Asinin3** [comment]
You should verify your gamedumps so you don't end up making invalid issue reports and wasting people's time + clogging the issue tracker.


To check if your disc was dumped correctly, you can use PS3-ISO-Rebuilder tool (http://jonnysp.bplaced.net/) You will need to load a corresponding IRD file, and then your dumped disc folder (JB Folder) or the decrypted ISO. Wait until all files are checked, everything should be green, counters for missing and corrupted files in the lower left corner should be 0.
