### ISSUE TITLE
Regression - unknown commit cause controls in Silent Hill 3 menu (from HD Collection) move fast & chaotically

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#3538]
The description says it all. Now it's very problematically to choose something in menu because of very fast scrolling... or somewhat <^.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1358235/RPCS3.log.gz)

**Comment by isshininu** [comment]
Not even in SH3, but in SH2 and KONAMI selection menu too. Everything so fast I even cannot choose original or new voices.

**Comment by PZerua** [comment]
What are the fps in the menu?

**Comment by jjsat** [comment]
This has always (at least for a long time) happened for me if I disable the frame limit. The FPS goes up to several hundred, which causes the menu to become unresponsive and the intro movie restarts again after a few seconds (since the timeout is obviously based on the frame count).

**Comment by isshininu** [comment]
Oh, my!
Turn fps limiter to "Auto" and everything now works as it should be.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1360048/RPCS3.log.gz)

Closed for now, too.
