### ISSUE TITLE
Analog Axis not working: Castlevania Lords of Shadow 2

### ISSUE THREAD

**Issue by pea458** [RPCS3/rpcs3#3539]
In Castlevania Lords of Shadow 2 analog axis is not working and I can't walking in the game.
![errorcontrol](https://user-images.githubusercontent.com/32544363/31229600-76b9908c-aa0b-11e7-92ff-3cca60d22705.png)

**Comment by AniLeo** [comment]
What's the Input? Keyboard, controllers, or both?

**Comment by pea458** [comment]
I'm test on keyboard and xinput but i can't control to move.

**Comment by Megamouse** [comment]
this will be fixed with my PR.
I just need to check a few things with jarveson

**Comment by Megamouse** [comment]
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6651/artifacts

**Comment by pea458** [comment]
Thank for fixed this issue.

เมื่อ 30 ต.ค. 2017 12:03 AM "Megamouse" <notifications@github.com> เขียนว่า
