### ISSUE TITLE
Raging Blast 2 RSX Error

### ISSUE THREAD

**Issue by renzobich** [RPCS3/rpcs3#3541]
{rsx::thread} RSX: Invalid RSX method 0xac40 (arg=0x10800240)
{rsx::thread} RSX: Invalid RSX method 0xac40 (arg=0x3e99)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)

**Comment by AniLeo** [comment]
#2359

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
