### ISSUE TITLE
Dark Souls - BLES01765: Emulation Consistently Fails at Specific Point in Game

### ISSUE THREAD

**Issue by olethorin** [RPCS3/rpcs3#3543]
Game emulation consistently fails with the same error message (shown in log) at the exact same point (see pic PointOfFailure.png). There is no other specific action taking place other than basic forward motion (walking).

--

Computer Stats:
Windows 7
Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
GTX 1050TI with 4G RAM
XBOX 360 Wired Controller

RPCS3 Version:
RPCS3 v0.0.3-3-eb8af97 Alpha | HEAD

Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz | 8 Threads | 11.96 GiB RAM | AVX

Error From Log File Line 48788
·F 0:01:21.687038 {PPU[0x1000000] Thread (main_thread) [0x00cec530]} MEM: Access violation reading location 0x59150c73

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1361258/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1361257/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/1361256/TTY.log)
![pointoffailure](https://user-images.githubusercontent.com/32499334/31256696-22ec28c4-aa02-11e7-936d-cfd0c726c5ce.png)

**Comment by isshininu** [comment]
> Lib Loader: Automatically load required libraries

Have you tried liblv2 option?

**Comment by olethorin** [comment]
If you mean have i tried selection option "Load livlv2.sprx only", yes I tried this option and it had the exact same results.

**Comment by olethorin** [comment]
Any suggestions on how I might help to debug this issue?
Is it something specific to this game or a possible issue across games?

**Comment by olethorin** [comment]
Am not absolutely certain, however, I believe the issue here is related to the game trying to pre-load the next areas.

**Comment by isshininu** [comment]
Why you close this issue?
Did you make past through it?

My game stops at this point too.
![1404](https://user-images.githubusercontent.com/6324523/46962062-30b9b380-d0b3-11e8-8d6b-f81d177fb08b.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2479479/RPCS3.log.gz)
