### ISSUE TITLE
Regression: Beyond Two Souls Demo Ingame -> Intro (#3503)

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#3544]
The game shows only a white screen after booting and that's it.
When closing the game window sometimes the emulator shows an error and then crash and some other times the game can be safetly closed and restarted.  
CPU utilazation gets stuck at around 50% right after the white screen shows up.

RPCS3 version -
RPCS3 v0.0.3-7-49a5ba3 Alpha | render_move

Specs -
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz | 4 Threads | 7.96 GiB RAM | AVX | TSX
GTX 980 ti
NVIDIA Drivers 376.53
Windows 10 Home

Input device -
DualShock 4 

Log -
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1362436/RPCS3.log.gz)

PS3 firmware Version-
4.81 (latest)

deatails about the game from the emulator-

![image](https://user-images.githubusercontent.com/18193363/31275797-4af02f2e-aaa1-11e7-9ca2-92615413d20b.png)

screenshot -
![image](https://user-images.githubusercontent.com/18193363/31274915-c1f135f4-aa9d-11e7-8284-e97144e9df5b.png)

**Comment by Zangetsu38** [comment]
Game have regressed after recently commit, wait fix for that

**Comment by AniLeo** [comment]
Since #3503 I assume?

**Comment by Zangetsu38** [comment]
no, with @Megamouse  have see it is little before

**Comment by Kravickas** [comment]
no its week or 2, like  GTA 4, 5, Midnight club LA, skate 3...

**Comment by Megamouse** [comment]
I believe it is since this commit:
https://github.com/RPCS3/rpcs3/commit/b9a0c107abde35b6deff2eafeb2b26c336c639f7
But iirc Neko said it was a hack before or sth on these lines.

**Comment by JohnGodgames** [comment]
Yep reverting https://github.com/RPCS3/rpcs3/commit/b9a0c107abde35b6deff2eafeb2b26c336c639f7 helps

**Comment by clienthax** [comment]
Ok, the problem is, its trying to call socket function after it unloads the module...... (bad game code is bad)

**Comment by rodjun** [comment]
How does it not crash on real ps3 @clienthax?

**Comment by clienthax** [comment]
@rodjun the real ps3 tends to be more lenient to dipshits

**Comment by Xcedf** [comment]
Another way to bypass the problem is to manual module selection
provide all modules the game needs except libnet.sprx to make it work

**Comment by Zangetsu38** [comment]
@Xcedf what lle exactly, i have tested in full game not works

**Comment by elad335** [comment]
for me it crashes with this message 

F LDR: class std::out_of_range thrown: invalid vector<T> subscript

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1506664/RPCS3.log.gz)

**Comment by Xcedf** [comment]
@Zangetsu38 
Fiber, fs, gcm_sys, sre, spurs
or there's another way to add libnet to ignore list in sys_prx.cpp

**Comment by Zangetsu38** [comment]
Yes works, with libfs

**Comment by elad335** [comment]
![image](https://user-images.githubusercontent.com/18193363/34348551-2c4a5e02-ea14-11e7-9424-7bea0ad00fa7.png)
a bit better with 5be9247c

**Comment by elad335** [comment]
I take that back it hangs with 
```F {SPU[0x2000003] Thread (QDSpursCellSpursKernel3)} class std::runtime_error thrown: Halt
(in file Emu\Cell\SPUThread.cpp:1859)``` 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1586790/RPCS3.log.gz)

**Comment by Xcedf** [comment]
Ingame hang regression caused by 5a03db7d
reverting VKTectureCache.h helps for Vulkan (tested only Vulkan)
![48](https://user-images.githubusercontent.com/7060586/34431386-cd803130-ec7f-11e7-9188-ae94c8cceb21.jpg)

**Comment by elad335** [comment]
https://cdn.discordapp.com/attachments/272875751773306881/409589203232620544/unknown.png

seems like the demo is working on NPEA9017 but not on NPUA72074

**Comment by Asinin3** [comment]
I found Beyond two souls to be very random, first few times i booted i got ingame then after that with same settings after 2hours i couldn't even get to the title screen. So just take that with a grain of salt.

**Comment by elad335** [comment]
Remaining stability issues sloved.
