### ISSUE TITLE
GL/Vulkan: Saints Row: The Third/IV/Gat Out of Hell graphical issues

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#3545]
Graphical issues (as of 0.0.7-8878):

- [x] Broken heat/explosion effects - Fixed in #6388
- [x] Brightness setting not working - Fixed in #6925
- [ ] Broken lighting
- [ ] Missing textures in some objects (grass, clothes)

<details>
<summary>Original comment</summary>

Tested in https://github.com/RPCS3/rpcs3/commit/cc594ad353462b2949e346180717da60c7b5ba1d:

In these games, character and map are rendered with very strange colors.

**OpenGL** (In SRTT, character is invisible almost all the time):
![srtt gl](https://user-images.githubusercontent.com/20027681/31282388-bb5327ce-aab2-11e7-8c1b-83de76fc1289.png)
![sriv gl](https://user-images.githubusercontent.com/20027681/31282393-bfb4e460-aab2-11e7-9434-982a7ead37d4.png)

**Vulkan**:
![srtt vk](https://user-images.githubusercontent.com/20027681/31282418-cd7a786c-aab2-11e7-8d4c-01905151d49a.png)
![sriv vk](https://user-images.githubusercontent.com/20027681/31282427-d39d17cc-aab2-11e7-8c49-2ccbccd7fa32.png)

**Reference** (SRIV PC version):

![20171006162855_1](https://user-images.githubusercontent.com/20027681/31282694-a3d45914-aab3-11e7-9c23-2b17c72e250b.jpg)

[Log SRTT 6-10-17 GL.gz](https://github.com/RPCS3/rpcs3/files/1362976/Log.SRTT.6-10-17.GL.gz)
[Log SRTT 6-10-17 VK.gz](https://github.com/RPCS3/rpcs3/files/1362977/Log.SRTT.6-10-17.VK.gz)
[Log SRIV 6-10-17 GL.gz](https://github.com/RPCS3/rpcs3/files/1362978/Log.SRIV.6-10-17.GL.gz)
[Log SRIV 6-10-17 VK.gz](https://github.com/RPCS3/rpcs3/files/1362979/Log.SRIV.6-10-17.VK.gz)

[Shaderlog SRTT GL](https://drive.google.com/open?id=0B9LymxJkpT48S1p3RUkyMDlGT3c)
[Shaderlog SRTT VK](https://drive.google.com/open?id=0B9LymxJkpT48a2ZvcUdFOGhQaU0)
[Shaderlog SRIV GL](https://drive.google.com/open?id=0B9LymxJkpT48NFJlSGQ4dHNlQkE)
[Shaderlog SRIV VK](https://drive.google.com/open?id=0B9LymxJkpT48bWZTSUtnNnZQWW8)

[RenderDoc](https://drive.google.com/open?id=0B9LymxJkpT48U0xZUzdqV1JRVGM)

</details>

**Comment by MarioSonic2987** [comment]
With #3744, graphics are improved a little bit (lighting and textures)
![](https://cdn.discordapp.com/attachments/272875751773306881/382783360784924672/image.png)

**Comment by kd-11** [comment]
Retest

**Comment by MarioSonic2987** [comment]
Tested with https://github.com/RPCS3/rpcs3/commit/4f01794713b09bddc51998edd060caf4f1a5e487:

![image](https://user-images.githubusercontent.com/20027681/35224303-d7af2694-ff84-11e7-8d5c-7a0b456c3322.png)
![image](https://user-images.githubusercontent.com/20027681/35224751-5b58daf2-ff86-11e7-8ba5-5cc3730f8979.png)

[Log SRTT 22-1-18 GL.gz](https://github.com/RPCS3/rpcs3/files/1652223/Log.SRTT.22-1-18.GL.gz)
[Log SR4 22-1-18 GL.gz](https://github.com/RPCS3/rpcs3/files/1652225/Log.SR4.22-1-18.GL.gz)

[Shaderlog OpenGL (SRIV)](https://drive.google.com/open?id=1fA9MdG24XIAK0ruXsyWRSneXgk1aRMtT)

[RenderDoc OpenGL (SRIV)](https://drive.google.com/open?id=1MPjG26pANuVMnZZvpkIpOKUz8TyKsXZG)

**Comment by MarioSonic2987** [comment]
Tested with https://github.com/RPCS3/rpcs3/commit/568118634e8cbdee1bb3546248eee6fda23af639:
![image](https://user-images.githubusercontent.com/20027681/38349977-a00161d6-38a9-11e8-897b-1d200a4f709a.png)
![image](https://user-images.githubusercontent.com/20027681/38350057-fc3159de-38a9-11e8-9abe-dba654004940.png)

In log, spams: 
```
E {rsx::thread} RSX: Cached object for address 0xC2861E00 was found, but it does not match stored parameters.
E {rsx::thread} RSX: 1 x 1 vs 16 x 1
E {rsx::thread} RSX: Could not gather all required slices for cubemap/3d generation
```

[Log OpenGL (SRTT)](https://github.com/RPCS3/rpcs3/files/1878774/Log.SRTT.D.5-4-18.GL.gz)
[Log OpenGL (SRIV)](https://github.com/RPCS3/rpcs3/files/1878775/Log.SRIV.D.5-4-18.GL.gz)
[Shaderlog OpenGL (SRTT)](https://drive.google.com/open?id=1UNB2dcRl4eKkV8LCQN_KdNRJGTTohE6R)
[Shaderlog OpenGL (SRIV)](https://drive.google.com/open?id=1tgXTk7FVXyEqamVHK2dFvWim5oMQMAAf)
[RenderDoc OpenGL](https://drive.google.com/open?id=1TqMzMOdBXKXrni6Gcx-23xbNlOd8u-kr)

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/42516065-84ee8a2c-845d-11e8-92ef-47162f5eb63e.png)
![image](https://user-images.githubusercontent.com/20027681/42516196-cb5c2686-845d-11e8-9949-49643b7409cb.png)

[RSX Capture (SRTT)](https://github.com/RPCS3/rpcs3/files/2180733/capture.SRTT.10-7-18.zip)
[RSX Capture (SRIV)](https://github.com/RPCS3/rpcs3/files/2180719/capture.SRIV.10-7-18.zip)

**Comment by MarioSonic2987** [comment]
With #5675, fixes black graphics in both games.

Full versions of both games require WCB+CPU blit to show graphics. Previously, at the beginning of that PR, they only required WCB.

![image](https://user-images.githubusercontent.com/20027681/54085957-fd1e4500-4343-11e9-86ea-faa2c77af098.png)
![image](https://user-images.githubusercontent.com/20027681/54085977-5a19fb00-4344-11e9-8998-b7f74f9e9136.png)


The demo versions of these games require WCB only.
![image](https://user-images.githubusercontent.com/20027681/54085894-5cc82080-4343-11e9-9377-1afa3d17122a.png)
![image](https://user-images.githubusercontent.com/20027681/54085881-2db1af00-4343-11e9-868d-2e0fd6d7bc00.png)

Graphical issues:

- [ ] Dark lighting
- [ ] [Some clothes aren't rendered](
https://user-images.githubusercontent.com/20027681/54086047-6ce0ff80-4345-11e9-9c82-d11cbbea206b.png
)

**Comment by MarioSonic2987** [comment]
Textures become corrupted when replaying a RSX capture, but in the game itself there's no problems.

![image](https://user-images.githubusercontent.com/20027681/54371645-0bd56680-467a-11e9-9f7f-ad2a32fddc5a.png)
![image](https://user-images.githubusercontent.com/20027681/54371571-e2b4d600-4679-11e9-8e62-6d220f510a9c.png)

With SRIV, throws when replaying a RSX capture:
```
F {RSX [0x1007a554]} RSX: class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkgsrender.cpp:2048)
```

[RSX Capture (SRTT Demo)](https://drive.google.com/open?id=1YHPMihF8c7iNzCy3MuzUIVcXqqQ6wMn2)

**Comment by MarioSonic2987** [comment]
In Saints Row: The Third spams in console during gameplay:
```
·W 0:00:49.136732 {RSX [0x02ac870]} RSX: Cache miss at address 0xC3200000. This is gonna hurt...
·W 0:00:49.147482 {RSX [0x02ddba4]} RSX: Cache miss at address 0xCF7D8480. This is gonna hurt...
·W 0:00:49.148302 {RSX [0x02df880]} RSX: Cached object for address 0xC2799280 was found, but it does not match stored parameters (width=32 vs 256; height=32 vs 128; depth=32 vs 1; mipmaps=0 vs 1)
```
In Saints Row IV, it spams the same lines in the same moment:
```
·W 0:00:46.062078 {RSX [0x01643b8]} RSX: Cache miss at address 0xC3060000. This is gonna hurt...
·W 0:00:46.071936 {RSX [0x018f398]} RSX: Cache miss at address 0xCF7B8E00. This is gonna hurt...
·W 0:00:46.072582 {RSX [0x0191460]} RSX: Cache miss at address 0xC2839280. This is gonna hurt...
·W 0:00:46.072821 {RSX [0x0191460]} RSX: Cached object for address 0xC2839280 was found, but it does not match stored parameters (width=32 vs 256; height=32 vs 128; depth=32 vs 1; mipmaps=0 vs 1)
```


[Log SRTT 5-4-19 Ingame VK](https://github.com/RPCS3/rpcs3/files/3047962/RPCS3.log.gz)
[Log SRIV 5-4-19 Ingame VK](https://github.com/RPCS3/rpcs3/files/3047977/RPCS3.log.gz)

**Comment by kd-11** [comment]
Just because something gets logged does not mean it is a problem that needs solving.

**Comment by MarioSonic2987** [comment]
With 0.0.7-8700-32a4c224, it has the same graphical issues as before.

[RenderDoc OpenGL (SRTT Demo)](https://drive.google.com/open?id=1rNijwumtdBAzXV5EVVhJtpWY9DXFpT6G)

**Comment by MarioSonic2987** [comment]
With 0.0.7-8878, heat and explosion effects are now rendered correctly in both games.

<details>
<summary>Heat effect</summary>

![](https://cdn.discordapp.com/attachments/272875751773306881/632986293739061286/unknown.png)
![](https://cdn.discordapp.com/attachments/272875751773306881/632992311676239887/unknown.png)
</details>
<details>
<summary>Explosion effect</summary>

![](https://cdn.discordapp.com/attachments/272875751773306881/632990117878824961/unknown.png)
![image](https://user-images.githubusercontent.com/20027681/66719399-6f319d80-edef-11e9-8aff-c3f7f42e5ac2.png)
</details>

**Comment by MarioSonic2987** [comment]
I've attached a RSX capture for the missing textures (like this pot in SR4)

![image](https://user-images.githubusercontent.com/20027681/68046649-a69fb580-fcdc-11e9-94f5-b4c9f0c26f4c.png)

[RSX Capture](https://drive.google.com/open?id=1MX44cLghPG1R3CdpSm5Ccxr9hkvXm3J5)

**Comment by kd-11** [comment]
For someone who's never touches this series, I can tell something is off, but I cannot tell what it is. Attach comparison pictures.

**Comment by MarioSonic2987** [comment]
The pot model itself is there, but in RPCS3 its textures don't render at all. PC version:
![20191101194640_1](https://user-images.githubusercontent.com/20027681/68048222-6a6e5400-fce0-11e9-95b0-e6b75148b89f.jpg)

**Comment by MarioSonic2987** [comment]
#7643 breaks aspect ratio in these games.

**Before**:
![image](https://user-images.githubusercontent.com/20027681/75621924-eac39980-5b9a-11ea-9e7c-41160c3db87b.png)
![image](https://user-images.githubusercontent.com/20027681/75621894-90c2d400-5b9a-11ea-932d-f9d40716bcd0.png)

**After**:
![image](https://user-images.githubusercontent.com/20027681/75621814-b9969980-5b99-11ea-8036-8e3ffc879ca8.png)
![image](https://user-images.githubusercontent.com/20027681/75621873-51948300-5b9a-11ea-9755-51558b22713a.png)

**Comment by kd-11** [comment]
The game is forcing the emulator to use 720x480 resolution, no idea why it's behaving like this, probably unexpected control flow. I'll check what's going on with it.

**Comment by kd-11** [comment]
@MarioSonic2987 Can I get a log of the broken aspect ratio?

**Comment by MsDarkLow** [comment]
Got a log from Gat Out of Hell w/ broke aspect ratio
Master: [RPCS3 Gat out of hell brok.zip](https://github.com/RPCS3/rpcs3/files/4272062/RPCS3.Gat.out.of.hell.brok.zip)

(good) Before pr merge: [RPCS3 Gat out of hell.zip](https://github.com/RPCS3/rpcs3/files/4272063/RPCS3.Gat.out.of.hell.zip)

**Comment by kd-11** [comment]
Any update?

**Comment by MsDarkLow** [comment]
For Gat Out of Hell, there is nothing noteworthy. Lighting is still kinda broke and Missing textures in some objects still remains.

**Comment by kd-11** [comment]
Maybe I can see some screenshots or RSX captures or something? Otherwise I have no idea what I'm supposed to work on, I'm notoriously bad at noticing differences in visuals of games I have not played vs realhw.

**Comment by MarioSonic2987** [comment]
Here are some screenshots (emulator and PC version) and a RSX capture from Saints Row IV. All Saints Row games mentioned in this issue have the same graphical issues.

**RPCS3**:
![image](https://user-images.githubusercontent.com/20027681/81432464-3f6b2e00-9163-11ea-87bd-980b639d1e6c.png)
**PC**:
![20200508193821_1](https://user-images.githubusercontent.com/20027681/81432742-c0c2c080-9163-11ea-93a9-ffd28219021c.jpg)

[RSX Capture (SR4)](https://drive.google.com/open?id=1xjSn8A2jRrZ-Tbz9wsuloF24BtBOrqHT)
