### ISSUE TITLE
The Tomb Raider Trilogy (BLES01195) games only show white screen

### ISSUE THREAD

**Issue by kotn3l** [RPCS3/rpcs3#3547]
The game selection menu works wonderfully. After choosing a game, all I got is a blank screen.
The Tomb Raider Trilogy, BLES01195

RPCS3 v0.0.3-3-cc594ad Alpha

Ryzen 5 1600X @ 3.6ghz, 12 threads, 15.95GB RAM, AVX
GTX 1070 8GB (using Vulkan)
Win 10 Pro 64bit

Input device: XBOX ONE controller (Xinput, works fine in the menu)
PS3 firmware version: 4.81

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1363509/RPCS3.log.gz)

![screenshot_8](https://user-images.githubusercontent.com/32578937/31291624-a845699e-aad0-11e7-880e-9f7ffd2ac7cb.png)
![screenshot_9](https://user-images.githubusercontent.com/32578937/31291631-ac602c80-aad0-11e7-9cce-9c6d39439333.png)

**Comment by AniLeo** [comment]
https://forums.rpcs3.net/thread-180128.html

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
