### ISSUE TITLE
GSL: Precondition failure (Sly cooper Thieves in time)

### ISSUE THREAD

**Issue by Finnishmotorfreak** [RPCS3/rpcs3#3552]
Hello! i have a problem with my emulator. So i wanted to play this game and it boots up yeah but when the main game tries to load it pops up this message: F {rsx::thread} struct gsl::fail_fast thrown: GSL: Precondition failure at c:\rpcs3\3rdparty\gsl\include\span.h: 382
Now i have no idea what that means or how to fix it.. help?
(all the emulator settings are stock)

**Comment by AniLeo** [comment]
Reopening after guidelines are complied with

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.
