### ISSUE TITLE
Making DirectX 12 mention Windows-only

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3555]
@Megamouse , DirectX 12 is mentioned in both RPCS3 versions, Windows and Linux. Could you make it Windows-only?
![1](https://user-images.githubusercontent.com/14265316/31324052-080f2850-acb7-11e7-91e8-1e4b31463c70.png)

**Comment by Asinin3** [comment]
Honestly the setting is probably going to get removed at some point and I'm sure that linux users are smart enough to figure this out.

**Comment by Megamouse** [comment]
Easy fix. maybe in one of the next few changes to the dialog.
The additional code can always be removed again later along with DX12 if ever.
If DX12 stays it has been done already so there's no real disadvantage.

I can actually make a seperate tooltip file. But then We would have to make any normal changes to those twice.

Then we wouldn't have all those: Windows: do this / Linux: do that
worth consideration imho.

It's not that hard to copy paste changes.

**Comment by Megamouse** [comment]
Okay I added ***LINUX*** versions for all tooltips that distinguish linux and windows and adjusted the windows versions accordingly.

Please be patient for the next Pull Request sometime this week

**Comment by Megamouse** [comment]
#3558

**Comment by Megamouse** [comment]
fixed

**Comment by TotalCaesar659** [comment]
Thank you very much!

**Comment by TotalCaesar659** [comment]
@Megamouse There is one more forgotten DirectX 12 in description of graphics device:
![1](https://user-images.githubusercontent.com/14265316/33053370-41da6e52-ce84-11e7-8fbb-1540feefe855.png)

**Comment by Megamouse** [comment]
noticed
