### ISSUE TITLE
_sys_prx_load_module_by_fd unimplemented: Ninja Gaiden Sigma 2

### ISSUE THREAD

**Issue by zekesonxx** [RPCS3/rpcs3#3561]
Even with `Load liblv2.sprx only` selected.

Issue created at the prodding of @hcorion.

[RPCS3-sigma2-lv2only.log.gz](https://github.com/RPCS3/rpcs3/files/1369660/RPCS3-sigma2-lv2only.log.gz)

**Comment by hcorion** [comment]
This should be fixed by https://github.com/RPCS3/rpcs3/commit/0fbb8b9a18ca974c7e83d64b9ef998d526db7640

Ninja Gaiden Sigma 2 should now be ingame

**Comment by zekesonxx** [comment]
Neat, will test tomorrow.

**Comment by zekesonxx** [comment]
Tested on 0fbb8b9 and on 7d3a52887, gets to the menu and to an in-game cinematic. (the game then encounters other errors, but those are outside the scope of this bug report).
