### ISSUE TITLE
Access Violations with Unity games and the Page Fault changes

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#3562]
**Entwined**

First run:
F {PPU[0x1000005] Thread (UnityMain) [0x000cf3bc]} MEM: Access violation writing location 0xb
Second run:
F {PPU[0x1000005] Thread (UnityMain) [0x000cf3b4]} MEM: Access violation writing location 0x7
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1369690/RPCS3.log.gz)

**Comment by Nekotekina** [comment]
Ugh.

**Comment by Asinin3** [comment]
I'm going to close this as it's most likely not an issue with the changes from the page fault implementation but simply because they progress further now and fail on something else.
