### ISSUE TITLE
Scott Pilgrim vs. the World  [NPUB3016] graphics bug.

### ISSUE THREAD

**Issue by Nikorasu95** [RPCS3/rpcs3#3565]
I'm having this gfx bug on Scott Pilgrim. The game used to run perfectly from a build way way back. Don't remember which one. Here is a Youtube video I made showing the issue. https://www.youtube.com/watch?v=XedikOS7...e=youtu.be

**Comment by hcorion** [comment]
You need to manually edit `config.yml` and change
```
Disable Vertex Cache: false
```
to
```
Disable Vertex Cache: true
```

**Comment by kd-11** [comment]
Or enable the debug tab in gui settings config and set it using the settings dialog.

**Comment by Nikorasu95** [comment]
Okay, thanks, guys. Vertex cache fixed the bug. Now another problem. How do I expand the game to fill the screen? The image is centered therefor there are black bars all around. This wasn't an issue on a build way way back. FYI "Use GPU Texture Scaling and " Stretch to Display Area" does nothing to expand the game to completely fill the screen.

**Comment by AniLeo** [comment]
Closing since the game does work properly with Disabled Vertex Cache.

Please use the discord's help channel if you need help with other issues.
