### ISSUE TITLE
SONIC THE HEDGEHOG 4 Episode 1 [NPUB30127] no longer boots.

### ISSUE THREAD

**Issue by Nikorasu95** [RPCS3/rpcs3#3566]
The game used to boot on a previous build. But now when I try to boot it on v0.0.3-1d375cb Alpha, I get "S LDR: Boot from gamelist per doubleclick: done" in the log and it does nothing.

**Comment by hcorion** [comment]
upload RPCS3.log.gz

**Comment by AniLeo** [comment]
Needinfo. Make sure you're actually starting the game after booting. 
If it does not work, reopen the issue with proper information as per the guidelines.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
