### ISSUE TITLE
Has anyone considered porting OpenGL 4.3 to Metal 2 so that there is a MacOS version of the PS3 emulator?

### ISSUE THREAD

**Issue by shyamalschandra** [RPCS3/rpcs3#3568]
Anyone know of any effort like this in the past?

**Comment by hcorion** [comment]
Sure, perhaps when Apple starts caring more about their users then their walled garden.

In all seriousness, the immense effort of creating and maintaining a Metal backend is seriously not worth the effort. If someone wants to do it, and the code works and they maintain it, we'll accept it.

If the [Vulkan Portability Initiative](https://www.khronos.org/blog/khronos-announces-the-vulkan-portability-initiative) gets to a place where it gets good enough for our intensive uses, perhaps we can add Mac support through that.

Please close this issue.

**Comment by AniLeo** [comment]
Closing issue, no one is going to waste time adding support for Metal just because Apple doesn't want to support OGL 4.3 or Vulkan. 

If they do support any of those eventually, MacOS support will eventually come back through those renders.

**Comment by dyorgio** [comment]
OpenGL is now officially deprecated on macOS:

https://developer.apple.com/macos/whats-new/
<img width="740" alt="captura de tela 2018-06-04 as 16 23 14" src="https://user-images.githubusercontent.com/1438251/40937134-039d4c7a-6814-11e8-92c9-28efb22d07e4.png">

and 

https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_intro/opengl_intro.html :
<img width="978" alt="captura de tela 2018-06-04 as 16 24 34" src="https://user-images.githubusercontent.com/1438251/40937145-082dd098-6814-11e8-8422-36e53e90672f.png">

**Comment by AniLeo** [comment]
LOL! Apple is going insane HAHAHA

"Hey, we just deprecated this widely used and non-legacy standard, use our proprietary API instead !!11!"

Why bother fixing the broken support, just remove it altogether!

**Comment by johnneijzen** [comment]
Well Apple I hope you like losing like 50+% of programs

**Comment by AniLeo** [comment]
It's likely going to remain "deprecated" "forever" and not removed, so the programs will still work - if they already worked before that is

**Comment by dyorgio** [comment]
Yes, the big announce here is that now you don't need to wait for update on supported OpenGL version. Deprecated are only updated to fix security problems, never new features. It's the end of the line.
