### ISSUE TITLE
RSX GLVertexDecompiler: diff_color & spec_color not declared

### ISSUE THREAD

**Issue by yzwduck** [RPCS3/rpcs3#3569]
Some vertex shaders code is not generated correctly, and then emulator throws `gl::glsl::link_exception` and freezes.

The following snippet is a piece of generated vertex shader.
Variable `diff_color` and `spec_color` are referenced in `main`, but they are not declared.
```
#version 430
// snip.
layout(location=0) uniform usamplerBuffer persistent_input_stream;
layout(location=1) uniform usamplerBuffer volatile_input_stream;

layout(location=1) out vec4 back_diff_color;
layout(location=2) out vec4 back_spec_color;
layout(location=3) out vec4 front_diff_color;
layout(location=4) out vec4 front_spec_color;
layout(location=5) out vec4 fog_c;
layout(location=6) out vec4 tc0;
// snip.

void main ()
{
	vec4 dst_reg0= vec4(0.0f, 0.0f, 0.0f, 1.0f);
	vec4 dst_reg7= vec4(0.0, 0.0, 0.0, 0.0);

	vs_main(dst_reg0, dst_reg7);

	gl_Position = dst_reg0;
	diff_color = vec4(1.);  // not declared
	spec_color = vec4(1.);  // not declared
// snip.
```

I made a patch, but haven't tested it... yzwduck@c0bd3c2
@kd-11 would you like to take a look?

---

Reproduce: game serial BLJM61288, at the end of battle scene.
Known work: v0.0.2-3f6b24d3
Known crash: v0.0.3-2b1c757 v0.0.3-5a03db7d
[Full log v0.0.2-3f6b24d3 and v0.0.3-5a03db7d](https://mega.nz/#!M6gjyBxT!o_TiEP45sNMT-wxVfkYOpW64i6-aDkmvjHG8abZfWPw)

**Comment by kd-11** [comment]
Should be fine. Open a PR for it
