### ISSUE TITLE
Heavy Rain - White Screen with MEM:Acces violation

### ISSUE THREAD

**Issue by Papermanzero** [RPCS3/rpcs3#3573]
Just start Heavy Rain EU Version (BCES00802). The game will boot with a white screen and following log:
F {PPU[0x1000013] Thread (SplashScreenThread) [0x01553e34]} MEM: Access violation reading location 0x0
E {PPU[0x1000000] Thread (main_thread) [0x00814e58]} Stat: 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [x62]
E {PPU[0x1000000] Thread (main_thread) [0x00814e58]} Stat: 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x62]

Version: 0.0.3-3-5a03db7 Alpha

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by Papermanzero** [comment]
??? I followed the guidlines. I do not need support. The issue i posted is about memory violation.
