### ISSUE TITLE
Demon's Souls [BLES00932] random crash

### ISSUE THREAD

**Issue by Dani1977** [RPCS3/rpcs3#3577]
Hi,

Since version 0.0.3-6390 i have random crash with error:

F 0:13:24.759460 {SPU[0x2000004] Thread (DLSpursManagerCellSpursKernel4)} class std::runtime_error thrown: Halt
(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1796)

I have nvidia 1080 gtx with Vulkan

Regards .
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1375437/RPCS3.log.gz)

**Comment by kd-11** [comment]
This issue affects all spurs games and has nothing to do with demons souls. Its less of an issue on windows but on linux spurs will eventually crash after a certain amount of time with near absolute certainty. I'm not sure its worth tracking such a huge problem with a single game tracker so I'm closing this.
