### ISSUE TITLE
HiDPI issues in RPCS3 UI

### ISSUE THREAD

**Issue by io8titan** [RPCS3/rpcs3#3580]
I am using RPCS3 v0.0.3-3-2e5f8c0 Alpha on Windows 10 Creator's Update x64 with a 4k hidpi display and Windows scaling set to 250%.

All in all the UI looks pretty good with an hidpi display but there are a few smaller issues without RPCS3 would look even better ;)

- Buttons in top right of "game list", "log" and "debugger" window too small
![image](https://user-images.githubusercontent.com/30977406/31451633-ccda3a1e-aed6-11e7-9223-fa1c66927829.png)

- Text cropped in dialog when importing pkg
![image](https://user-images.githubusercontent.com/30977406/31451359-16f67532-aed6-11e7-8f15-6d2fbec09793.png)

- Stylesheet messes up layout
Kuroi:
![image](https://user-images.githubusercontent.com/30977406/31452138-435bb3a6-aed8-11e7-8b72-7eede28720d1.png)
default:
![image](https://user-images.githubusercontent.com/30977406/31452159-56d16bba-aed8-11e7-9357-94a0a7a8873e.png)

- Down arrow in drop-down box relatively small (maybe Qt issue?)
RPCS3:
![image](https://user-images.githubusercontent.com/30977406/31451810-5085a06a-aed7-11e7-9939-3224d0df9cdd.png)
Filezilla (wxWidgets based but for comparison):
![image](https://user-images.githubusercontent.com/30977406/31451896-999c70da-aed7-11e7-89e1-0daff2ba0155.png)

- Unused help button in dialogs. Since RPCS3 uses tool tips, these buttons are superfluous. 
![image](https://user-images.githubusercontent.com/30977406/31452222-7e5bef66-aed8-11e7-8f5d-5a05e396087c.png)

**Comment by Megamouse** [comment]
The down arrow and the small buttons are some Qt issue.
The ? on top of each window will be removed.
The stylesheet will be adjusted to some extend.
I fixed the installation dialog.

**Comment by Megamouse** [comment]
I couldn't make them any bigger or else the original scaling would be too big. But I think it's a compromise for 250% scaling. which really is very heavy scaling.

Left: old
![image](https://user-images.githubusercontent.com/23019877/31463883-dc17a284-aecf-11e7-85c3-71efd0e8f098.png)
![image](https://user-images.githubusercontent.com/23019877/31463931-0769b21a-aed0-11e7-8258-5f1087faf134.png)

The size of the titles was easier to fix though.
![image](https://user-images.githubusercontent.com/23019877/31463982-3f96def6-aed0-11e7-8f9b-d1a5827355a7.png)

**Comment by Zangetsu38** [comment]
250 % ? whaa ^^ in 4K Screen Need Only 200 % ^^

**Comment by Megamouse** [comment]
I think I got it. Had to use other units for the scaling.

**Comment by Megamouse** [comment]
look at #3558

**Comment by io8titan** [comment]
> 250 % ? whaa ^^ in 4K Screen Need Only 200 % ^^

The required scaling depends on the dpi of the display (in my case 281 dpi), so a larger 32" 4k desktop monitor requires a lower scaling value than a smaller 15" laptop display for example.

[https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx#dpi_and_the_desktop_scaling_factor](url)

**Comment by Megamouse** [comment]
All has been fixed that could be fixed for now

**Comment by io8titan** [comment]
In case everything was supposed to be fixed with the newest build;
the kuroi theme still causes the above mentioned problems, no changes at all.

**Comment by Zangetsu38** [comment]
you can try this theme ? 
[GuiConfigs.zip](https://github.com/RPCS3/rpcs3/files/1404719/GuiConfigs.zip)

**Comment by io8titan** [comment]
Yes, this one looks better!

**Comment by AniLeo** [comment]
Can you test Kuroi on latest build? Don't forget to replace the theme with the updated version

**Comment by Megamouse** [comment]
@AniLeo  close please.
can be reopened if really needed
