### ISSUE TITLE
Error with BlazBlue

### ISSUE THREAD

**Issue by CaripijaXXX** [RPCS3/rpcs3#3582]
Hey guys, I need help, I'm trying to play Blazblue in my rpcs3 emu, however, it keeps freezing, either whn I enter to a mode or when I skip the opening(It does not freeze when I skip the credit intro screen), if you have any solution, answer me.
Thanks!
![cpu](https://user-images.githubusercontent.com/32713427/31459018-372cc862-ae98-11e7-8ae9-fbdd8753c919.png)
![gpu](https://user-images.githubusercontent.com/32713427/31459030-3f6231ca-ae98-11e7-9481-853e3c8ac166.png)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
