### ISSUE TITLE
Portal 2 [BLUS30732] Invisible menu on OGL, VK, DX12

### ISSUE THREAD

**Issue by JusicP** [RPCS3/rpcs3#3584]
RenderDoc:
[P2 Renderdoc.zip](https://github.com/RPCS3/rpcs3/files/1378062/P2.Renderdoc.zip)
Log:
[P2 Log.zip](https://github.com/RPCS3/rpcs3/files/1378065/P2.Log.zip)
Screenshots:
RPCS3
![image](https://user-images.githubusercontent.com/25232950/31479464-1d4dea06-af20-11e7-95a2-fe4f63bc38b3.png)

Real HW
![realhw](https://user-images.githubusercontent.com/25232950/31479469-23642d06-af20-11e7-97eb-54d851cf39f4.png)

**Comment by Margen67** [comment]
From log: 
 >{rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 3
{rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 2

Maybe that's the cause?

**Comment by digitaldude555** [comment]
![screenshot 1649](https://user-images.githubusercontent.com/26138653/51085501-eb089780-1742-11e9-8e0d-8ed333d8c501.png)
![screenshot 1650](https://user-images.githubusercontent.com/26138653/51085521-30c56000-1743-11e9-9297-c83141c219d9.png)
Vulkan and OpenGL menu are visible now. Close issue.
