### ISSUE TITLE
Regression: NPUB30051 Bomberman ULTRA

### ISSUE THREAD

**Issue by Kojikun1** [RPCS3/rpcs3#3586]
OS - Windows 10 Pro x64 1703
CPU - Intel core i7 3630QM
GPU - GT650M
Vulkan and OpenGL- black Screen

Tested Build last Master and build before this PR 
https://github.com/RPCS3/rpcs3/pull/3503
Before this PR game the game worked

show this in log 
U {PPU[0x1000000] Thread (main_thread) [0x00389bc4]} sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd0020648)
E {PPU[0x1000000] Thread (main_thread) [0x00388410]} sys_net: sys_net_bnet_socket(): unsupported type (6)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1378921/RPCS3.log.gz)

**Comment by clienthax** [comment]
That's odd.. I had tested this and it was working fine after that pr a few days ago..

**Comment by Megamouse** [comment]
can't get it to run either

**Comment by raven02** [comment]
Confirm regressed since #3503

**Comment by clienthax** [comment]
Confirmed regression, very odd.. im wondering if something else was added in between me testing the pr and it being merged

**Comment by hcorion** [comment]
Yeah, it's due to crappy bomberman Ultra coding.

After hacking at the code a bit.
I was able to get bomberman to do 
```
E {PPU[0x1000000] Thread (main_thread) [0x003aa410]} sys_net: sys_net_bnet_socket(): unsupported type (6)
E {PPU[0x1000000] Thread (main_thread) [0x003aa5f4]} sys_net: sys_net_bnet_setsockopt(s=0, SOL_SOCKET): unknown option (0x1000)
E {PPU[0x1000000] Thread (main_thread) [0x003aa5f4]} sys_net: sys_net_bnet_setsockopt(s=0, SOL_SOCKET): unknown option (0x2000)
```
but then it just spammed
```
E {PPU[0x1000000] Thread (main_thread) [0x003aaafc]} sys_net: Socket error ENOTCONN
```

**Comment by Kojikun1** [comment]
closing fixed by https://github.com/RPCS3/rpcs3/pull/3702
