### ISSUE TITLE
Persona 5 cant run on rpcs3 and i dunno what to do..

### ISSUE THREAD

**Issue by KeisnaDieka** [RPCS3/rpcs3#3590]
Please help me solve this..
![aaaa](https://user-images.githubusercontent.com/25382614/31533372-e1231fe2-afbf-11e7-9c8a-73db7ae9809d.png)

**Comment by KeisnaDieka** [comment]
why my thread getting closed?? i new please explain.. thanks..

Pada tanggal 13 Okt 2017 2.12 PM, "Ani" <notifications@github.com> menulis:

**Comment by AniLeo** [comment]
https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md
