### ISSUE TITLE
Inaccessible drives on games.yml paths throw 0xE06D7363 exception

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#3592]
See: https://github.com/RPCS3/rpcs3/issues/3592#issuecomment-337986559
---

Build version:  #3587

Pleas make error Windows text possible to copy as text.. Now i can make only screenshot, also strongly recommend add build date in error message.
  I had same problem with yesterday version, im upgrading every 2 days, something like than, i didnt mess with settings or install new game.

Windows 7 64bit, UAC disabled.
Core i7, 32 GB
Nvidia lastest drivers, Geforce 970
Avira antivirus

I just copied new version, into old version directory.

![starterror](https://user-images.githubusercontent.com/1702944/31559031-7e4651d8-b04f-11e7-969b-20a02adf023c.png)

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	rpcs3.exe
  Application Version:	0.0.0.0
  Application Timestamp:	59e0b2bd
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.23889
  Fault Module Timestamp:	598d50ba
  Exception Code:	e06d7363
  Exception Offset:	000000000001a06d
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1029
  Additional Information 1:	fb50
  Additional Information 2:	fb504e57a06e90942e942782818ef5f4
  Additional Information 3:	b766
  Additional Information 4:	b7665e5470533d32c0b4323993f1f21e

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

 This errors should be already fixed but is not.

[RPCS3Log.zip](https://github.com/RPCS3/rpcs3/files/1383530/RPCS3Log.zip)

**Comment by AniLeo** [comment]
Config.yml or GUIConfigs.ini conflit. Move them to a separate folder so newer ones are generated. If it works, send us the bad files

**Comment by ruthan** [comment]
Its not Config.yml thing its working, but i have not GUIConfigs.ini, where it should be?
In log is something about missing png, i dont know why log has 120 MB when is empty..

**Comment by AniLeo** [comment]
GuiConfigs is in GuiConfigs.

Log remains at 131mb if emulator crashes and it's not successfully trimmed on closure.

**Comment by ruthan** [comment]
I have only:
CurrentSettings.ini
Kuroi (Dark) by Ani.qss 

Files in GUIConfigs folder.

**Comment by AniLeo** [comment]
Move CurrentSettings.ini elsewhere and try using RPCS3 again, as said before

**Comment by ruthan** [comment]
No change, same error.

**Comment by AniLeo** [comment]
If you extract latest build to a new folder it works, I assume. 

One of your config files must be corrupted for this to happen. This time try moving elsewhere the data folder, games.yml and config.yml.

I also assume you don't place disc games inside dev_hdd0/game and the BLUS30295 folder you have there is a DLC/Patch for the game. You can ignore that warning.

**Comment by ruthan** [comment]
I downloaded new version and its run fine from other directory.

  But i deleted all you config with above its not working.. Need i create also new games list, or what files i should try to delete / replace?

**Comment by AniLeo** [comment]
If you want to move over your games, just copy over dev_hdd0 folder to the new directory. 

We need to find out how that error happened to you, I have no other clues on what could cause that though..

**Comment by ruthan** [comment]
Ok i did some testing problem is nit games.yml. Are you really sure that problem is not issues icon image, already mention above? 
   If yes, i should be fixed, because crash because of icon file is silly.

**Comment by AniLeo** [comment]
Icon not loading should be completely irrelevant to this issue, it's just a warning

**Comment by ruthan** [comment]
Ok i did more testing problem was, iso in game list, which i not now mounted.

[name]/BCES00081/
BLES00635: H:/

  I thing that such thing could be handled by better way and user should be warned what is working, delete this entry from game.yml fixed problem.

**Comment by AniLeo** [comment]
Ok, I can reproduce.

In games.yml add directory to a drive you can't read files from (e.g: physical empty disc reader, virtual empty disc reader, partitions that windows can't open such as EXT4)

**Comment by Nedula** [comment]
I was getting the same error message and couldn't figure out what it was but I did figure it out and it was when I'd clear my downloads folder where the PS3UPDAT.PUP file was. 
Make sure to keep that with your emulator/don't delete it after updating your firmware
