### ISSUE TITLE
GUI glitches with custom skins on last versions

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3593]
This appears sometimes we're calling settings dialogs and move mouse cursor over elements.

![1](https://user-images.githubusercontent.com/1223276/31559875-dc947836-b05a-11e7-8c78-832c6e1c1f86.PNG)

**Comment by AniLeo** [comment]
Can't reproduce

**Comment by AniLeo** [comment]
Retest on latest, don't forget to update the theme as well, verify if it's still happening, because I can't reproduce this at all

**Comment by AniLeo** [comment]
Closing as couldn't reproduce since then until current master. Feel free to reopen if it's still an issue and you can provide some details that help with reproducing.
