### ISSUE TITLE
Update rpcs3 in engine

### ISSUE THREAD

**Issue by DaemonSnake** [RPCS3/rpcs3#3595]
Upgrading to a new version of rpcs3 is currently annoying (redownloading everything and having to copy past the saves file and all).
Could we have a built-in way to update rpcs3?
I don't believe that'd be hard to implement anyway.

**Comment by Renusek** [comment]
Current way is good enough, you are just doing it wrong.

All you need to do is:
1. delete data/ folder
2. delete config.yml
3. swap the old rpcs3.exe for the new rpcs3.exe

**Comment by DaemonSnake** [comment]
I don't see how that's good enough. A user shouldn't have to delete and replace files by hand to have the latest version of a program.

**Comment by Asinin3** [comment]
Generally all you need to do is replace the rpcs3.exe 99% of the time. But I believe the devs have been discussing that something could be done to make it easier.

**Comment by Renusek** [comment]
@DaemonSnake the emulator is in alpha state, a user shouldn't expect quality of life features from it.

**Comment by frymezim** [comment]
I don't get why you're getting annoyed, your a programmer yourself why not make a solution for it, submit a pull request then everyone is happy.

**Comment by AniLeo** [comment]
There's an update serverside API for that which I implemented a couple of days ago, poke me if you're willing to implement it on the emulator.

**Comment by dio-gh** [comment]
#6566 will close this issue. Referencing it, so this won't become a zombie ticket.

**Comment by AniLeo** [comment]
Closing as implemented
