### ISSUE TITLE
Regression - Braid[NPUB30133] - run game few second later get black screen 

### ISSUE THREAD

**Issue by kokutoukiritsugu** [RPCS3/rpcs3#3597]
OS - Windows 10 Pro x64 1703
CPU - i7 6700k@4.5
GPU - gtx 1070
Vulkan and OpenGL ,whatever ppu/spu 1 or 3

build:
no balck screen 
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-5740/artifacts

Braid - run game few second later get black screen 
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-5743/artifacts

**Comment by kd-11** [comment]
Attach your log file or the issue will be closed as invalid.

**Comment by kokutoukiritsugu** [comment]
here:
when screen get black, i closed rpcs3.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1385353/RPCS3.log.gz)

**Comment by kokutoukiritsugu** [comment]
rpsc3 version  v0.0.4-2017-11-30

![image](https://user-images.githubusercontent.com/5471433/33417105-f9cacd1a-d5da-11e7-881a-83c6e838d1b8.png)

when go right, and left text fade out.
screen will get black.
go left will show back.


1M gif:
![1](https://user-images.githubusercontent.com/5471433/33417225-90e7b80c-d5db-11e7-8ee3-19a60c8e1f34.gif)


log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1516750/RPCS3.log.gz)

**Comment by kokutoukiritsugu** [comment]
version:     rpcs3-v0.0.4-2018-01-04-19d181fa_win64

if enable "disable vertex cache" will fix this problem.

**Comment by PZerua** [comment]
This is the pull request that regressed the game: https://github.com/RPCS3/rpcs3/pull/3241

**Comment by Emulator-Team-2** [comment]
@AniLeo 
I think this problem can be closed, this game just requires to enable "Disable Vertex Cache".

**Comment by digitaldude555** [comment]
Should be closed braid is back in playable as of March this year.
