### ISSUE TITLE
From Dust - Some objects and water are not rendered

### ISSUE THREAD

**Issue by JackTerok** [RPCS3/rpcs3#3602]
That's on current Master:

![screenshot_2](https://user-images.githubusercontent.com/10469129/31584565-fffa1bc6-b1b0-11e7-8d36-3425be0ea7ef.png)

That's how it supposed to look like:

![screenshot_3](https://user-images.githubusercontent.com/10469129/31584550-b2d06df0-b1b0-11e7-8b74-1f56301297a3.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1385408/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Still an issue on **v0.0.6-8056-2b4da187**

![](https://cdn.discordapp.com/attachments/272875751773306881/573521762575187980/unknown.png)

R9 280X
AMD 19.4.3

RSX Capture (rename to 7z file): [NPEB00466_20190502155052_capture.7z](https://github.com/RPCS3/rpcs3/files/3138595/NPEB00466_20190502155052_capture.zip)

**Comment by Realmantik** [comment]
Still the same on v0.0.7-8637-0dfe85dc.

**Comment by CrabLugo** [comment]
Maybe try PR #6467 ? From screenshots it looks like a similiar issue

**Comment by Realmantik** [comment]
No effect. I think It is different issues.

**Comment by AniLeo** [comment]
Better, but still broken

![image](https://user-images.githubusercontent.com/10283761/78031826-feaa1900-735b-11ea-80f8-d40acdb3a9fb.png)

**Comment by kd-11** [comment]
Need a more recent RSX capture for binary compatibility reasons.

**Comment by JackTerok** [comment]
[NPUB30418_20200508172845_capture.7z.zip](https://github.com/RPCS3/rpcs3/files/4599965/NPUB30418_20200508172845_capture.7z.zip)


Renamed to .zip since Github doesnt let me upload 7z files.

**Comment by JackTerok** [comment]
This has been fixed on master.
