### ISSUE TITLE
Graces F still freezes in last build 

### ISSUE THREAD

**Issue by Katanab** [RPCS3/rpcs3#3604]
F {SPU[0x2000002] Thread (SpursTLGraphicsCellSpursKernel2)} class std::runtime_error thrown: Halt
(in file Emu\Cell\SPUThread.cpp:1796)

I keep getting this error

In locked 30 fps the games are slow as hell in battle, and freezes after 10-20 minutes

IN AUTO- games work good in battle, and faster outside, but freezes faster

Both ways still freezes...

**Comment by P1llus** [comment]
I can confirm this. When running in 30 FPS, which is where it should be, when you enter a battle, fps is still displayed as 30, but the battle itself is going in slow motion.

Did you also enable strict rendering?

**Comment by amakuramio** [comment]
in Japanese versions it freezes randomly, or it goes fine, very random behaviour

**Comment by kd-11** [comment]
Still a issue?

**Comment by Illynir** [comment]
Yes.

**Comment by vsub** [comment]
I don't know about the freezing part but the game speed is still all over the place.
At 30fps:
Outside of battle while running the speed randomly switches between normal and double speed
In battle it switches between normal and twice slower
The fps doesn't change but everything is moving at different speeds

At 60fps:
Same as above but normal is 2x and 2x is 4x and in battle it's 4x when it's normal and 2x when it slows down

With Auto\Off:
I am not sure exactly,it's like it is switching between the 30fps and 60fps problems

**Comment by benderscruffy** [comment]
time to update the issue

**Comment by HerrHulaHoop** [comment]
Didn't see any FPS issues when testing it recently. Setting Framelimit to 60 and Vblank rate to 30Hz will cap the FPS in the free-roam sections to 30FPS while providing 60FPS in battle sequences and menus, similar to what we see on an actual PlayStation 3.

While Vblank isn't an accurate solution, we already have #3020 to track that issue. So this one can be closed.

**Comment by HerrHulaHoop** [comment]
Happy anniversary!
