### ISSUE TITLE
on screen keyboard bug

### ISSUE THREAD

**Issue by implsh** [RPCS3/rpcs3#3610]
cant seem to use on screen keyboard properly, when i enter something the thing just pops up again like nothing happened
(game requires to enter something for your plate number(initial d))

logs:

U {PPU[0x1000000] Thread (main_thread) [0x00f85fb8]} cellOskDialog TODO: cellOskDialogSetLayoutMode(layoutMode=5120)
U {PPU[0x1000000] Thread (main_thread) [0x00f85fa8]} cellOskDialog TODO: cellOskDialogSetKeyLayoutOption(option=0x3)
U {PPU[0x1000000] Thread (main_thread) [0x00f85fb8]} cellOskDialog TODO: cellOskDialogSetLayoutMode(layoutMode=5120)
U {PPU[0x1000000] Thread (main_thread) [0x00f85fa8]} cellOskDialog TODO: cellOskDialogSetKeyLayoutOption(option=0x3)
U {PPU[0x1000000] Thread (main_thread) [0x00f85fb8]} cellOskDialog TODO: cellOskDialogSetLayoutMode(layoutMode=5120)
U {PPU[0x1000000] Thread (main_thread) [0x00f85fa8]} cellOskDialog TODO: cellOskDialogSetKeyLayoutOption(option=0x3)
E {PPU[0x1000012] Thread (_cellsurMixerMain) [0x0041f23c]} Stat: 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x1317312]
E {PPU[0x1000012] Thread (_cellsurMixerMain) [0x0041f23c]} Stat: 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [x1317312]

**Comment by Nezarn** [comment]
Clearly you don't own and played the game on a real PS3 (and you don't know japanese and have common japanese knowledge), you need to enter at least 1 hiragana character.

https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Japan

**Comment by marcussacana** [comment]
And if you aren't a shit weeb like us and don't know what is hiragana\kanji just put this 2 underline: ＿＿
![https://a.pomf.cat/wlafni.png](https://a.pomf.cat/wlafni.png)

**Comment by Nezarn** [comment]
or just use this and copy characters: http://www.lexilogos.com/keyboard/hiragana.htm
