### ISSUE TITLE
Xbox One Controller for Windows (USB): Select Button doesn't work

### ISSUE THREAD

**Issue by d3vv** [RPCS3/rpcs3#3612]
Select button doesn't work for Xbox One (not Xbox360) Controller with XInput API.

Left button (Select/View[3]) near Start Button at the picture below: 
https://xboxdesignlab.xbox.com/en-us/customize?productid=900WZDF9XJVG
https://support.xbox.com/en-US/xbox-one/accessories/xbox-one-wireless-controller

RPCS3: v0.0.3-3-5146f3e Alpha
OS:  Microsoft Windows 10 Pro (64bit)
CPU: Intel(R) Core(TM) i7 CPU X 980 @ 3.33GHz
GPU: NVIDIA GeForce GTX 770  (2 GB)
GAME: Demon's Souls [ BLUS30443 ]

UPD. It seems like "#define XINPUT_GAMEPAD_BACK             0x0020" doesn't work like SELECT button with PS3 DualShock..

**Comment by Megamouse** [comment]
lmao demons souls has no usage of select button xD

it works fine in other games

**Comment by d3vv** [comment]
Yes it is, thnx
I'm sorry for this topic
Just thought that select is for gestures into Demon's Souls :((
