### ISSUE TITLE
Vulkan API call failed with unrecoverable error: Device lost

### ISSUE THREAD

**Issue by d3vv** [RPCS3/rpcs3#3613]
It is often unexpected error like:

·F 0:45:26.662708 {rsx::thread} class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:1089)
·E 0:46:12.540014 {PPU[0x1000000] Thread (main_thread) [0x009e03f8]} Stat: 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [x47]
·E 0:46:12.540110 {PPU[0x1000011] Thread (_sys_MixerChStripMain) [0x0154cb2c]} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x4062480]
·E 0:46:12.540261 {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01548450]} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x2031240]
·E 0:46:12.540267 {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01548450]} Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x507804]

RPCS3 v0.0.3-3-5146f3e Alpha | HEAD
Intel(R) Core(TM) i7 CPU X 980 @ 3.33GHz | 12 Threads | 23.99 GiB RAM

Operating System	Microsoft Windows 10 Pro

Video Adapter	NVIDIA GeForce GTX 770  (2 GB)
Driver Version	23.21.13.8792 - nVIDIA ForceWare 387.92

Vulkan DLL	C:\WINDOWS\system32\nvoglv32.dll (23.21.13.8792)
API Version	1.0.56
Driver Version	387.368.0

LDR: Title: Demon's Souls
LDR: Serial: BLUS30443
LDR: Used configuration:
Core:
  PPU Decoder: Recompiler (LLVM)
  PPU Threads: 2
  PPU Debug: false
  Save LLVM logs: false
  Use LLVM CPU: ""
  SPU Decoder: Recompiler (ASMJIT)
  Bind SPU threads to secondary cores: false
  Lower SPU thread priority: false
  SPU Debug: false
  Maximum immediate DMA write size: 16384
  Preferred SPU Threads: 4
  SPU delay penalty: 3
  SPU loop detection: true
  Lib Loader: Load liblv2.sprx only
  Hook static functions: false
Video:
  Renderer: Vulkan
  Resolution: 1280x720
  Aspect ratio: 16:9
  Frame limit: Off
  Write Color Buffers: true
  Write Depth Buffer: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Log shader programs: false
  VSync: false
  Debug output: false
  Debug overlay: false
  Use Legacy OpenGL Buffers: false
  Use GPU texture scaling: true
  Stretch To Display Area: false
  Force High Precision Z buffer: false
  Invalidate Cache Every Frame: true
  Strict Rendering Mode: false
  Disable ZCull Occlusion Queries: false
  Disable Vertex Cache: false
  Enable Frame Skip: false
  Force CPU Blit: false
  Consecutive Frames To Draw: 1
  Consecutive Frames To Skip: 1
  Resolution Scale: 100
  Anisotropic Filter Override: 16
  Minimum Scalable Dimension: 128
  D3D12:
    Adapter: ""
  Vulkan:
    Adapter: GeForce GTX 770

**Comment by Asinin3** [comment]
You should always include a log file, but in this case it might be best to install vulkan SDK here: https://vulkan.lunarg.com/ open GuiConfigs folder (inside RPCS3 folder) edit the CurrentSettings.ini file and set "showDebugTab=false" to "showDebugTab=true" (without quotes) Now enable debug output (do this in custom config if you have one enabled for the game) then run the game again and once you have this error appear post log file again.

**Comment by d3vv** [comment]
Should/Could or must? Just kidding )))
Okey-dockey... 
I installed SDK and set showDebugTab option to true as well. It is quick to reproduce an error with set video resolution to high ( 1920x1080 in my case) and minimize game window...
So You can see a log file into attach below..
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1392671/RPCS3.zip)

**Comment by d3vv** [comment]
Sorry, I miss to enable Debug output into previous post.. Here a new log-file below
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1392694/RPCS3.zip)

**Comment by Asinin3** [comment]
Logfix here:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1392760/RPCS3.log.gz)

`·! 0:00:41.194912 {rsx::thread} RSX: Swapchain: present mode 3 in use.
·E 0:00:41.198470 {rsx::thread} RSX: ERROR: [IMAGE] Code 161481200 : vkCmdBlitImage: region [0] dstOffset[].x values (22, 1894) exceed dstSubresource width extent (0). The spec valid usage text states 'dstOffset[0].x and dstOffset[1].x must both be greater than or equal to 0 and less than or equal to the destination image subresource width' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageBlit-dstOffset-00248)
·E 0:00:41.198486 {rsx::thread} RSX: ERROR: [IMAGE] Code 161481202 : vkCmdBlitImage: region [0] dstOffset[].y values (0, 1053) exceed dstSubresource height extent (0). The spec valid usage text states 'dstOffset[0].y and dstOffset[1].y must both be greater than or equal to 0 and less than or equal to the destination image subresource height' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageBlit-dstOffset-00249)`

**Comment by d3vv** [comment]
But it was just a quick reproduction... I can't reproduce an error with normal (recommended) video mode due to it is too hard play with slow performance with "Debug Output" option cause an error will be present after sometime of gameplay.. maybe there is another issue with normal play...

**Comment by Asinin3** [comment]
@d3vv Huh? You already provided a log, you can turn debug options off, I just want to know if it crashes with 1280x720 (you should be using that + resolution scaling anyway). I just provided logfix for the devs.

**Comment by d3vv** [comment]
Yes, it crashed with 1280x720 but if i play "a long time".. One thing - during the play I do a lot of changes from windowed to full screen mode (not minimize game window)

**Comment by raveskirza** [comment]
The same error message appears while using Vulkan every time, when you try to minimize the GSframe Window
The same is not happening with OpenGL
This could be probably related to nVidia cards only
Attached Log
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1405676/RPCS3.zip)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/3668

**Comment by raveskirza** [comment]
Still get the error
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1424472/RPCS3.zip)

**Comment by kd-11** [comment]
Should be fixed now. A workaround for nvidia has been committed

**Comment by raveskirza** [comment]
Still crashes on minimize
Not sure if I am doing anything wrong, I have vulkan SDK installed and turned on "debug Output" in the debug tab but still do not see vulkan debug messages.
Here is the RPCS3 log and the Windows event log for the driver crash
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1424808/RPCS3.zip)
[Windows system Event Log.zip](https://github.com/RPCS3/rpcs3/files/1424809/Windows.system.Event.Log.zip)

**Comment by kd-11** [comment]
Interesting. I've created another patch that allows swapchain creation to fail. I suspect it might not fix the issue with high scaling since dimensions calculated can never be 0 if scaling is enabled but its worth trying anyway.

**Comment by kd-11** [comment]
Autoclosed with the PR merge but you can retest. Swapchain of 0x0 will never be created so this should be fixed theoretically. Let me know if it persists.

**Comment by raveskirza** [comment]
Great it no longer crashes now :)

**Comment by d3vv** [comment]
@raveskirza Yes
Here is a log
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1425452/RPCS3.zip)

**Comment by kameronkemnitz** [comment]
I am hitting the same issue as @d3vv. I see he provided logs for his a couple days ago in the most recent post, would you like me to provide my own as well or are they not needed?

**Comment by hinicekindname** [comment]
im on mac and have the same problem would appreciate if could get help
