### ISSUE TITLE
The Darkness II :  Error  (in file ..\Utilities\VirtualMemory.cpp:83)

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#3614]
The Darkness II [BLUS30743]

> 
> F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0x57): 
> (in file ..\Utilities\VirtualMemory.cpp:83)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1391725/RPCS3.log.gz)

**Comment by kd-11** [comment]
This was fixed recently
