### ISSUE TITLE
Rumble not working (Xbox one controller) 

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#3616]
Xbox one rumble not working (I think this is happening since the latest changes of controller management, one or two months ago, this option was in Config>Input/output)

Now the rumble´s got a very great lag, for example playing demon´s souls, if one monster hits my character, no rumble in that moment. But the rumble for that hit can appear 5 minutes after. This happens even if the emulator is closed. I played some other games, with no rumble, and 10 minutes after i close the emulator, the controller starts to rumble/receive the rumble data. 

Note: This happens in all games, and only with the xbox one controller. The xbox 360 controller works fine.

**Comment by Megamouse** [comment]
I don't have this issue at all.
maybe you should try to update your drivers.
What operating system do you use and which pad handler?

**Comment by d3vv** [comment]
I have another issue - I have continuous vibration(rumble?) after time of play game. More over vibration don't stop after exit from rpcs3 application.

**Comment by LuismaSP89** [comment]
@d3vv 
Yes, that happens to me. And it´s because the rumble lag that i say.
Are you using too the xbox one controller? And in that case... do you have rumble correctly ingame?

**Comment by d3vv** [comment]
Nop. I always disable vibration ingame yet..

**Comment by Megamouse** [comment]
try with this build:
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6623/artifacts

I fixed an issue where the xboxone controller (and only that controller) can't handle vibrations being updated in lower intervals than 10ms.

**Comment by LuismaSP89** [comment]
@Megamouse  Awesome, it works now ; )

**Comment by chdongsh** [comment]
I see my xbox elite controller still has this vibration trouble

**Comment by Megamouse** [comment]
https://ci.appveyor.com/project/Megamouse/rpcs3/build/artifacts

maybe that runs the elite as well?

**Comment by chdongsh** [comment]
No, I tried 0.0.3-379 (f2cdb74f) , but the rumble still got lag

**Comment by Megamouse** [comment]
You are supposed to test the build I linked before

**Comment by Megamouse** [comment]
Sorry it seems the link is wrong. One second.

**Comment by Megamouse** [comment]
Try this.
https://ci.appveyor.com/project/Megamouse/rpcs3/build/0.0.3-374/artifacts

**Comment by chdongsh** [comment]
I just now tried 374, but it don't solve the lag

**Comment by chdongsh** [comment]
no, I am wrong, it work.

**Comment by Megamouse** [comment]
Hmm this is weird. I'll send you another one later with a more extreme approch to see what happens.

Btw i read somewhere that it might be a driver issue on win10 . I saw people using custom drivers. Maybe those are necessary if my tests do not work

**Comment by Megamouse** [comment]
Huh? For real?

**Comment by chdongsh** [comment]
yes, I test two times in demon´s souls, it works. one strange thing is when got first hit, elite don't rumble, then it rumble well.

**Comment by Megamouse** [comment]
Okay. Good to know. I'll see if that is our error or just can't be helped

**Comment by chdongsh** [comment]
excuse me, I just found that I can configure the pad in 374, after pad configure, elite work very well.  :)

**Comment by chdongsh** [comment]
I test the newest version 6699 and other versions including pad5 branch, but elite's rumble only work well with your 374. the others all lag.

**Comment by Megamouse** [comment]
try this again:
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6696/artifacts

**Comment by chdongsh** [comment]
6696 work well.
