### ISSUE TITLE
Dante's inferno randomly freezes [NPUB30478] using Vulkan

### ISSUE THREAD

**Issue by jabroany** [RPCS3/rpcs3#3617]
RPCS3 v0.0.3-3-5146f3e Alpha | Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz | 8 Threads | 7.88 GiB RAM | AVX | GTX 770 

This doesn't happen in OpenGL as far as I can tell - only in Vulkan, however the speed in openGL is worse while Vulkan is pretty much fullspeed.

When playing Dante's inferno, version 1,00, using Vulkan - the game seems to randomly freeze at some points. This is the case for pretty much all versions of RPCS3 I could find where this game worked. The recent fix to the random freezing for Vulkan + Nvidia GPUS in other games didn't fix this problem. 

It happens randomly - sometimes after hours of play, other times after a couple of minutes, I can't seem to find a pattern. RPCS3 doesn't crash, just permanently freeze. Included is the log with debugger on.

[RPCS3 DantesInferno NPUB30478.zip](https://github.com/RPCS3/rpcs3/files/1392520/RPCS3.DantesInferno.NPUB30478.zip)

**Comment by ScorchEmber256** [comment]
I notice that other games freeze when trying to compile new shaders with vulkan

**Comment by jabroany** [comment]
This problem seems to be currently fixed!
