### ISSUE TITLE
srw-z3-tengoku.suparobo BLJS10299 doesn't work 

### ISSUE THREAD

**Issue by simon5949** [RPCS3/rpcs3#3620]
rpcs3-v0.0.3-2017-10-19-b3efa752_win64.zip | Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz | 8 Threads | 16GiB RAM | NVIDIA| GTX 1070

Click in, the game is like this, black screen. No work, no reaction 

![20171019222828](https://user-images.githubusercontent.com/32933432/31776232-89892e12-b51d-11e7-9ee1-bbeaa34f71a0.png)

RPCS3.log:RPCS3 v0.0.3-3-b3efa75 Alpha | HEAD
Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz | 8 Threads | 15.93 GiB RAM | AVX
S Successfully installed PS3 firmware version 4.81.
S LDR: Boot from gamelist per doubleclick: done
S LLVM: Created module: v2+114268-647D2CA772A0FBE6-haswell.obj
S LLVM: Created module: v2+09406C-B3BDFD8BA613EF7F-haswell.obj
S LLVM: Created module: v2+010200-BCE57842CA73C681-haswell.obj
S LLVM: Created module: v2+0514BC-A7C67BCFF2DDF0D1-haswell.obj
S LLVM: Created module: v2+1963A0-6078A798A2BE86E1-haswell.obj
S LLVM: Created module: v2+0D3C9C-2053B196344DC9FE-haswell.obj
S LLVM: Created module: v2+1D7054-9616AA201B7F877C-haswell.obj
S LLVM: Created module: v2+154A10-07BA6B164F6F8A37-haswell.obj
S LLVM: Created module: v2+3E079C-FFF8A29E2081CB2D-haswell.obj
S LLVM: Created module: v2+3A0AAC-02B4D393FC67543E-haswell.obj
S LLVM: Created module: v2+2DFC58-0171837A39DD16B9-haswell.obj
S LLVM: Created module: v2+29D2D0-B9F18854095D66BB-haswell.obj
S LLVM: Created module: v2+25AC14-FAEEA0F6A5253B61-haswell.obj
S LLVM: Created module: v2+217F30-CCA50F6A14DE69F6-haswell.obj
E PPU: LLVM: [0x005391a4] Error: MTFSF
E PPU: LLVM: [0x00539618] Error: MFFS
S LLVM: Created module: v2+320464-3B591967F159E783-haswell.obj
S LLVM: Created module: v2+3609D4-EC347ECF92921FC8-haswell.obj
S LLVM: Created module: v2+49ADA0-AB47D83EA90B99D4-haswell.obj
S LLVM: Created module: v2+420688-3E821CFC8DACFDA7-haswell.obj
S LLVM: Created module: v2+45B280-355819ED7AFDC628-haswell.obj
S LLVM: Created module: v2+4DA0BC-693697930BEB13CB-haswell.obj
S LLVM: Created module: v2+518C2C-7EDCC9B5B5356BC5-haswell.obj
S LLVM: Created module: v2+5D90E8-BAB0D5733F577A08-haswell.obj
S LLVM: Created module: v2+559288-7B22441065809128-haswell.obj
S LLVM: Created module: v2+598BF4-B07FE45A26BE7C43-haswell.obj
S LLVM: Created module: v2+619B44-89C988CD3CFD36C0-haswell.obj
S LLVM: Created module: v2+6995B4-0EF2FAB8A1762186-haswell.obj
S LLVM: Created module: v2+763EF4-D828A47CD81A97A6-haswell.obj
S LLVM: Created module: v2+659D74-2538B60E3C5D7613-haswell.obj
S LLVM: Created module: v2+6DF2A0-B717D3AB698F1FD5-haswell.obj
S LLVM: Created module: v2+72394C-4C97B1DE3202CC43-haswell.obj
S LLVM: Created module: v2-liblv2.sprx-6E56691FE33B8E4B-haswell.obj
U {PPU[0x1000000] Thread (main_thread) [0x00f010e4]} HLE TODO: Unimplemented syscall syscall_462 -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00f10e64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x00f110bc]} sys_prx TODO: _sys_prx_register_library(library=*0xf136a0)
S LLVM: Created module: v2-libsysmodule.sprx-E926430A8C1D5DCB-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00f1bd8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S LLVM: Created module: v2-libgcm_sys.sprx-92BB3C6B43076AD9-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f124d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S LLVM: Created module: v2-libsre.sprx-7BD57B68D8CA8EBC-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f124d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S LLVM: Created module: v2-libfs.sprx-BB8655E4C5C49381-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f124d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00f1161c]} sys_prx TODO: _sys_prx_register_module()
S LLVM: Created module: v2-libresc.sprx-868A23FA3425D270-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/libresc.sprx
S LLVM: Created module: v2-libl10n.sprx-CF794CD12F0202AD-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00f12038]} sys_prx TODO: _sys_prx_unload_module(id=0x23004600, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x00f12038]} sys_prx TODO: _sys_prx_unload_module(id=0x23004700, flags=0x0, pOpt=*0x0)
E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed
U {PPU[0x1000000] Thread (main_thread) [0x00724e54]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd01004d0, option=*0x0, waitForEvent=0)
S {rsx::thread} RSX: New program compiled successfully
S {rsx::thread} RSX: New program compiled successfully
U {PPU[0x1000000] Thread (main_thread) [0x0002937c]} cellMusicDecode TODO: cellMusicDecodeInitialize2
U {PPU[0x1000000] Thread (main_thread) [0x00f3ad80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00f3ad80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00f3ad80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00f10f0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00f10f0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
S {SPU[0x2000000] Thread (CellSpursKernel0)} SPU: SPU Database initialized...
S {SPU[0x2000000] Thread (CellSpursKernel0)} SPU: SPU Recompiler (ASMJIT) created...
S LLVM: Created module: v2-libfiber.sprx-90B538A6D4A84178-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/libfiber.sprx
S LLVM: Created module: v2-libspurs_jq.sprx-356285E488E56CBE-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/libspurs_jq.sprx
S {Audio Thread} XAudio 2.9 initialized
S LLVM: Created module: v2-librtc.sprx-9CB190F178FA7E82-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx
S {rsx::thread} RSX: New program compiled successfully
S LDR: Boot from gamelist per doubleclick: done
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+010200-BCE57842CA73C681-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+0514BC-A7C67BCFF2DDF0D1-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+09406C-B3BDFD8BA613EF7F-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+0D3C9C-2053B196344DC9FE-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+114268-647D2CA772A0FBE6-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+154A10-07BA6B164F6F8A37-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+1963A0-6078A798A2BE86E1-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+1D7054-9616AA201B7F877C-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+217F30-CCA50F6A14DE69F6-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+25AC14-FAEEA0F6A5253B61-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+29D2D0-B9F18854095D66BB-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+2DFC58-0171837A39DD16B9-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+320464-3B591967F159E783-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+3609D4-EC347ECF92921FC8-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+3A0AAC-02B4D393FC67543E-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+3E079C-FFF8A29E2081CB2D-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+420688-3E821CFC8DACFDA7-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+45B280-355819ED7AFDC628-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+49ADA0-AB47D83EA90B99D4-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+4DA0BC-693697930BEB13CB-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+518C2C-7EDCC9B5B5356BC5-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+559288-7B22441065809128-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+598BF4-B07FE45A26BE7C43-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+5D90E8-BAB0D5733F577A08-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+619B44-89C988CD3CFD36C0-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+659D74-2538B60E3C5D7613-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+6995B4-0EF2FAB8A1762186-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+6DF2A0-B717D3AB698F1FD5-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+72394C-4C97B1DE3202CC43-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+763EF4-D828A47CD81A97A6-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2-liblv2.sprx-6E56691FE33B8E4B-haswell.obj
U {PPU[0x1000000] Thread (main_thread) [0x00f010e4]} HLE TODO: Unimplemented syscall syscall_462 -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00f10e64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x00f110bc]} sys_prx TODO: _sys_prx_register_library(library=*0xf136a0)
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} PPU: LLVM: Loaded module v2-libsysmodule.sprx-E926430A8C1D5DCB-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00f1bd8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x00f124d0]} PPU: LLVM: Loaded module v2-libgcm_sys.sprx-92BB3C6B43076AD9-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f124d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00f124d0]} PPU: LLVM: Loaded module v2-libsre.sprx-7BD57B68D8CA8EBC-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f124d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00f124d0]} PPU: LLVM: Loaded module v2-libfs.sprx-BB8655E4C5C49381-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f124d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00f1161c]} sys_prx TODO: _sys_prx_register_module()
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} PPU: LLVM: Loaded module v2-libresc.sprx-868A23FA3425D270-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/libresc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} PPU: LLVM: Loaded module v2-libl10n.sprx-CF794CD12F0202AD-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00f12038]} sys_prx TODO: _sys_prx_unload_module(id=0x23004600, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x00f12038]} sys_prx TODO: _sys_prx_unload_module(id=0x23004700, flags=0x0, pOpt=*0x0)
S {rsx::thread} RSX: New program compiled successfully
S {rsx::thread} RSX: New program compiled successfully
S {rsx::thread} RSX: New program compiled successfully
E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed
U {PPU[0x1000000] Thread (main_thread) [0x00724e54]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd01004d0, option=*0x0, waitForEvent=0)
U {PPU[0x1000000] Thread (main_thread) [0x0002937c]} cellMusicDecode TODO: cellMusicDecodeInitialize2
U {PPU[0x1000000] Thread (main_thread) [0x00f3ad80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00f3ad80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00f3ad80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00f10f0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00f10f0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
S {SPU[0x2000000] Thread (CellSpursKernel0)} SPU: SPU Database initialized...
S {SPU[0x2000002] Thread (CellSpursKernel2)} SPU: SPU Recompiler (ASMJIT) created...
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} PPU: LLVM: Loaded module v2-libfiber.sprx-90B538A6D4A84178-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/libfiber.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} PPU: LLVM: Loaded module v2-libspurs_jq.sprx-356285E488E56CBE-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/libspurs_jq.sprx
S {Audio Thread} XAudio 2.9 initialized
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} PPU: LLVM: Loaded module v2-librtc.sprx-9CB190F178FA7E82-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00f119ac]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx

**Comment by simon5949** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1398925/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Invalid issue, please read the repository guidelines.

**Comment by simon5949** [comment]
tell me why the game doesn't work,thanks,i very like play the game.
