### ISSUE TITLE
Minecraft Keyboard only one move per once tap!

### ISSUE THREAD

**Issue by 13yearoldADULT** [RPCS3/rpcs3#3622]
While playing Minecraft PS3 edition. It rans beautifully and nice, it works fine
But. Whenever I enter in game I have to spam my mapped forward key to move.
The emulator works fine and it acts like nothing happened. Please. Fix the issue

**Comment by RainbowCookie32** [comment]
Can't reproduce using the Keyboard pad handler on latest master

**Comment by Megamouse** [comment]
probably old minecraft version.
I'll close this for now
