### ISSUE TITLE
Regression-Nier BLJM60223 [Fixed]

### ISSUE THREAD

**Issue by Sandvichero** [RPCS3/rpcs3#3624]
The town went from the textures being fine to all of them being black.

Before:
![nier](https://user-images.githubusercontent.com/26612410/31794854-b045b9e8-b4f1-11e7-8429-ed7d74b7a598.PNG)

After:
![niere](https://user-images.githubusercontent.com/26612410/31794865-b90ecb32-b4f1-11e7-8faf-f26a8a94ae54.PNG)

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1400043/RPCS3.log.gz)

**Comment by Illynir** [comment]
No problem on texture here, but problem of ghosting effect with framebuffer.

![image](https://user-images.githubusercontent.com/22648460/31795980-2b4458bc-b528-11e7-90e7-a76ec06154f3.png)

**Comment by Sandvichero** [comment]
Are you on the latest version of rpcs3 because the problem is still there.
If you are then maybe my settings are wrong though they shouldn't be

**Comment by Illynir** [comment]
Last master, yes. Your problem is old, maybe you have CPU Blit on True dans config.xml ?

**Comment by Sandvichero** [comment]
Thanks this fixed it for me.

**Comment by ScorchEmber256** [comment]
The issue is not being caused by config.yml... it is a regression
