### ISSUE TITLE
Thread (DLSpursManagerCellSpursKernel1)} class std::runtime_error thrown: Unknown STOP code: 0x2a80

### ISSUE THREAD

**Issue by d3vv** [RPCS3/rpcs3#3626]
It is a rare error which occurs on load game save:

F {SPU[0x2000001] Thread (DLSpursManagerCellSpursKernel1)} class std::runtime_error thrown: Unknown STOP code: 0x2a80 (Out_MBox is empty)
(in file Emu\Cell\SPUThread.cpp:1770)

RPCS3: v0.0.3-3-34a6085 Alpha
OS: Microsoft Windows 10 Pro (64bit)
CPU: Intel(R) Core(TM) i7 CPU X 980 @ 3.33GHz
RAM: 24GB
GPU: NVIDIA GeForce GTX 770 (2 GB)
GAME: Demon's Souls [ BLUS30443 ]

Log file attached below..
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1403125/RPCS3.log.gz)

**Comment by scribam** [comment]
@d3vv Is it still an issue ?
This game is playable according to the compatibility list and that probably means saves are working correctly.

**Comment by d3vv** [comment]
@scribam Really don't know cause don't run RPCS3 long time. In any cases I will close an issue.
