### ISSUE TITLE
Yakuza 4[NPEB02036] Crashing after roughly 30 seconds in game

### ISSUE THREAD

**Issue by Neucomac3** [RPCS3/rpcs3#3632]
This issue has been persisting ever since the build that added enhanced resolution. Yakuza 4 worked long enough on that day for me to get through the tutorial fight and save in Theater Square, but now when I try to run the game it'll crash as soon as I start moving out of Theater Square.
Crash text reads as such:
F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0x57): 
(in file ..\Utilities\VirtualMemory.cpp:83)
This is on build  #3629 
Log file included:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1404514/RPCS3.log.gz)

OS: Windows 10 64bit
GPU: Nvidia GTX 980ti
CPU: Intel i7 7700k
RAM: 16gb

**Comment by rodjun** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/3638

**Comment by Zangetsu38** [comment]
for moment, i can play wihtout crash

**Comment by Neucomac3** [comment]
![image](https://user-images.githubusercontent.com/32991174/31969810-ef03a288-b90d-11e7-8742-9d2ae374c8e9.png)
confirming this as fixed. Before, it would crash as soon as you got just outside the poppo store at best, so this seems to be sorted for now.
