### ISSUE TITLE
sys_cond_wait: Mutex ownership verification failing

### ISSUE THREAD

**Issue by d3vv** [RPCS3/rpcs3#3634]
One more a rare error:

F {PPU[0x1000044] Thread (ChrProxyThreadMan::Thread) [0x009e03f8]} class std::runtime_error thrown: Verification failed: 
(in file Emu\Cell\lv2\sys_cond.cpp:279)

RPCS3: v0.0.3-3-96fd855 Alpha
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1404776/RPCS3.log.gz)

OS: Microsoft Windows 10 Pro (64bit)
CPU: Intel(R) Core(TM) i7 CPU X 980 @ 3.33GHz
RAM: 24GB
GPU: NVIDIA GeForce GTX 770 (2 GB)
GAME: Demon's Souls [ BLUS30443 ]
Log file attached below..

**Comment by d3vv** [comment]
It looks like the same error:

F {PPU[0x1000063] Thread (ChrInsManThread::Thread) [0x009e03f8]} class std::runtime_error thrown: Verification failed: 
(in file Emu\Cell\lv2\sys_cond.cpp:279)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1406168/RPCS3.log.gz)

**Comment by kamer1337** [comment]
skate [BLES00124] have same error

> F {PPU[0x100000e] Thread (rwfilesys_sk8) [0x00a4f180]} class std::runtime_error thrown: Verification failed: 
> (in file Emu\Cell\lv2\sys_cond.cpp:279)

**Comment by scribam** [comment]
@d3vv Does this issue still happening in Demon's Souls? This game is playable according to https://rpcs3.net/compatibility?g=BLUS30443

**Comment by d3vv** [comment]
@scribam don't know ))) It was long time ago )))

**Comment by elad335** [comment]
all of the mentioned games need retesting with ppu threads number set to 1. @Asinin3 can you test white album?

**Comment by legend800** [comment]
Backbreaker is completely fixed with https://github.com/RPCS3/rpcs3/pull/5265. If the other games have the same issue, then all of these games are fixed too!

**Comment by elad335** [comment]
Fixed by #5314
