### ISSUE TITLE
Star Ocean 4 failure to boot

### ISSUE THREAD

**Issue by amakuramio** [RPCS3/rpcs3#3635]
This is on 0.0.3-5 head git 10-20-2017

Persona 5 works fine at 11-13 fps so it definitely isn't fault of my low i5 4300u / intel hd 4400 tablet.
However, Star Ocean 4 shows 

- LLVM linkage failed
- unimplemented SPU thread options 0x2 (sys.spu)
- OpenGL initalization of glDepthboundsEXT, glGetTextureImage, glTextureBufferRange, glTextureBarrierNV failed
- invalid blit dimensions passed
- sys_fs_open failed

I have my own lle modules, would selecting them do any good?

Here is 128MB log file:
https://drive.google.com/file/d/0B7yWC9_hcFZcb3FlV0pmZDB3TmM/view?usp=sharing

**Comment by Ekaseo** [comment]
https://rpcs3.net/compatibility?g=star+ocean+4
