### ISSUE TITLE
Feature request: install .pkg to alternate directory

### ISSUE THREAD

**Issue by JacobAL** [RPCS3/rpcs3#3636]
Is there any chance that a feature for installing .pkgs to a different location/hard-drive could be added?

**Comment by isJuhn** [comment]
Isn't this already possible with the Virtual File System?

**Comment by flash-fire** [comment]
Installing on different drives is indeed possible with VFS.  Caveat! Dev_hdd1 and dev_hdd0 *must* be on the same drive for game installs to work. (not sure bout package installs but put them as same drive just to be safe).  If you want to install pkgs in multiple directories simultaneously, that isn't supported, I think.  But, you can change the directory.

**Comment by JacobAL** [comment]
Well thanks, didn't know that was a thing.
