### ISSUE TITLE
"Loading pipeline object" dialog is broken in Fullscreen

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3641]
On the latest builds, if I use "Start games fullscreen" option, I get nothing but emulator hanging on some minutes until shaders cache loaded.

**Comment by Megamouse** [comment]
can confirm. this is how it looks like afterwards:
![image](https://user-images.githubusercontent.com/23019877/31934659-047164c2-b8ad-11e7-8e0c-81076527cee3.png)

**Comment by Psycho-A** [comment]
To be more precise, the problem came with build 6436 and merging #3581 (2017-10-12).

**Comment by Megamouse** [comment]
There might be another connected issue based on my guts:
When you try to move the gsframe while precompiling shader cache you can't click anything else anymore.
And you can only move the mouse in the area that is not the windows taskbar.
meaning the taskbar is not accessible

**Comment by Psycho-A** [comment]
@Megamouse 
Don't know all details, but all what I'm doing is clicking game from game list to launch (or use command line to directly run some game), and do nothing with gsframe. It tries to go fullscreen, and then just freezing both with emulator. If I unfocus the emulator via Alt+Tab, I see no "Normal dialog" window in the Windows taskbar. But it does when GS window starts windowed. It wasn't happen before #3581 by any ways, so I find it as a regression that needed to be fixed.

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/3668

**Comment by Megamouse** [comment]
now the window only opens after the shader compilation.
so the problem has been circumvented. Fine by me 👍

**Comment by Psycho-A** [comment]
Problem is gone for me both for OpenGL and Vulkan. Although in OpenGL GS frame tries to appear, but then turns off by shader cache dialog. In Vulkan window appears only when all shaders loaded.

**Comment by Megamouse** [comment]
true, and before it finally opens you can see two overlapping smaller black rectangles, one where the normal window would be and one on top left corner

**Comment by kd-11** [comment]
@Megamouse Problem with leaving the window open when loading is that it doesnt notice the resolution bump. You get blocky upscaled overlay text as a result, so I just chose to hide it until the pipeline was ready to monitor window events. For OGL I think the window creation part takes too long so you can see the window briefly. Either way, its just a cosmetic choice now.
