### ISSUE TITLE
Blazblue games and Persona 4 Arena render at the wrong position (Regression from #3458)

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#3642]
Made a new issue because #3474 was closed, this regression still exists.

While all the blazblue games got increased performance (WCB not needed anymore) and the glitchy rendering was fixed there is a regression. These games now have black bars on the top, the game is still displaying at the correct aspect ratio however the bottom is cut off.

![image](https://user-images.githubusercontent.com/15137035/30773437-a20f1aa0-a0af-11e7-80e8-6e7e88b54c75.png)
Left = Before
Right = After

Persona 4 Arena has the same issue and appears to be running on the same engine.
![rpcs3_2017-09-24_10-49-35](https://user-images.githubusercontent.com/15137035/30778778-76bb5b8e-a11d-11e7-94e2-f58ca06a7c03.jpg)

**Comment by kd-11** [comment]
This is fixed in the latest PR

**Comment by Asinin3** [comment]
Confirmed, I'll close as soon as it's merged.
