### ISSUE TITLE
Regression - Demon's Souls [BLES00932] - Sun Glare / Lens Flare effect indoors

### ISSUE THREAD

**Issue by Fwompa** [RPCS3/rpcs3#3643]
Version: v0.0.3-34a6085 Alpha
Renderer: Vulcan non-strict only

Issue can be observed anywhere during normal gameplay where you should not be able to see the sun (e.g. indoors, or near a wall). Simply look up a bit and spin around while indoors or near walls and you will see light beams and a lens flare effect coming from the direction of the sun which you shouldn't be able to see.
![sunglare](https://user-images.githubusercontent.com/33057129/31939737-86f82e46-b8f6-11e7-88f2-59cbe05e0d3c.png)

**Comment by kd-11** [comment]
Its because zcull unit is not properly emulated using vulkan. Use openGL to get around this. Its also not a regression since it has always been an issue in one form or another.

**Comment by Fwompa** [comment]
@kd-11 , it didn't occur in v0.0.3-7-a81c5e7

**Comment by AniLeo** [comment]
Of course, that's an ancient build without proper zcull emulation

**Comment by Fwompa** [comment]
I only bring it up because the game only runs smooth in Vulcan on my system. I tried OpenGL for a while but it dropped below 30 fps too frequently, making things really choppy. Anyways, I didn't come here for support, I was already aware of multiple workarounds, but none of them are worth the performance loss (or in the case of the old build, more frequent crashes).

**Comment by Karlos007** [comment]
So in Vulkan is fixed but if I use OpenGL the Sun doesn't get blocked in interiors.

**Comment by Asinin3** [comment]
@Karlos007 That's an issue with Nvidia drivers, on AMD it works with both OGL and VK.

**Comment by Karlos007** [comment]
Good to know, thanks. I suppose they won't fix it.

**Comment by jobs-git** [comment]
.It just needs another implementation for Nvidia, like

```
if(AMD){
   do the usual zcull
}
if(Nvidia){
   do the zcull that works in nvidia
}
```

**Comment by Asinin3** [comment]
Just going to leave this here:
![image](https://user-images.githubusercontent.com/15137035/36570755-77ec7b52-182b-11e8-89f7-b119dd1f3efd.png)
