### ISSUE TITLE
F {PPU[0x1000012] Thread (LoadThread) [0x00bd2250]} class std::out_of_range thrown: invalid map<K, T> key

### ISSUE THREAD

**Issue by Zolika1351** [RPCS3/rpcs3#3645]
Using v0.0.3-2017-10-21-96fd8556 with default settings, but it seems to happen on every PPU decoder setting.
Happens in the legal text in GTA IV (NPEB00882) and freezes the emulation.

OS:
Windows 10 Professional (Creators Update)

CPU:
AMD FX(tm)-6100 Six-Core Processor  | 6 Threads |  AVX

RAM: 8GB DDR3

GPU:
AMD Radeon (TM) R9 380 Series

Log: https://mega.nz/#!mJpDVJQI!6cN0fhUskiuFs1tdGi8C4UJEXiGu5qk1ZEfw8EFvkHo

**Comment by AniLeo** [comment]
Incomplete issue, will be closed if not properly updated

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

**Comment by scribam** [comment]
Can you try this [build](https://ci.appveyor.com/project/MarioSonic2987/rpcs3/build/0.0.3-23/artifacts) and check if you still have the issue?

**Comment by Zolika1351** [comment]
Yup, happens on that build as well, exact same message.

**Comment by Zolika1351** [comment]
Anyone? It STILL happens, exact same error.

**Comment by MarioSonic2987** [comment]
@Zolika1351 It's caused by broken savedata. It's fixed with PR #3918. You have to delete this folder:
```
dev_hdd0\home\00000001\savedata\BLES00229PROFILE
```
And test with this build: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7244/artifacts

**Comment by scribam** [comment]
@Zolika1351 Can be closed? PR #3918 is merged.
