### ISSUE TITLE
reproducible MEM: Access violation writing location

### ISSUE THREAD

**Issue by d3vv** [RPCS3/rpcs3#3646]
There is a reproducible "MEM: Access violation writing location" bug into Demon's Souls:

E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x01deb090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache//08/526dceef2e155030fc19c2b7d7370285” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x01deb090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache//16/f4307e6eac2bea1ef029ac6a5addd7f8” [1]
F {PPU[0x1000000] Thread (main_thread) [0x01d654e0]} MEM: Access violation writing location 0xfabeac60

So, there is a video where I always get an error when I try to move on:

https://youtu.be/0gUfw8Cz6k4

There is a log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1411111/RPCS3.log.gz)

There is a game save:
[BLUS30443DEMONSS005.ZIP](https://github.com/RPCS3/rpcs3/files/1411117/BLUS30443DEMONSS005.ZIP)

This is not a game-dump bug, cause it is my own bcd-dump from my CFW REBUG PS3..
Moreover I checked MD5-sums from PS3... So there is no issue on PS3 (I can check/move saves from PRCS3 on PS3)..

OS: Microsoft Windows 10 Pro (64bit)
CPU: Intel(R) Core(TM) i7 CPU X 980 @ 3.33GHz
RAM: 24GB
GPU: NVIDIA GeForce GTX 770 (2 GB)
GAME: Demon's Souls [ BLUS30443 ]

P.S. There is no way to fully complete the game w/o escaping this bug place.. How can I help you to resolve this issue?

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/31951031-aab72f5a-b8e5-11e7-8520-99effcd43f1b.png)
Tested with build from https://github.com/RPCS3/rpcs3/pull/3638 and it doesnt crash. I dont know if it happens on master and is fixed in that PR but it works fine now

**Comment by d3vv** [comment]
Could it possible to share this build?

**Comment by elad335** [comment]
@d3vv that build is in https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6574/artifacts

**Comment by d3vv** [comment]
@elad335 This build doesn't work too for me:

[https://s1.postimg.org/16bwgx68gv/RPCS3_00.jpg](url)

@kd-11 Would you like to share your build to be sure if it my local problem or not?

**Comment by AniLeo** [comment]
He literally sent you the build above and you tested it..

It's probably stuff in dev_hdd1/cache causing the issue

**Comment by d3vv** [comment]
@AniLeo I always see:

E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x01deb090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache//19/ad58285fde5e5a887fa77e5379bb633f” [1]
E {SPU[0x2000004] Thread (DLSpursManagerCellSpursKernel4)} SPU: [0x0b83c] Branch-to-next with $LR
E {SPU[0x2000003] Thread (DLSpursManagerCellSpursKernel3)} SPU: [0x0b83c] Branch-to-next with $LR
E {SPU[0x2000003] Thread (DLSpursManagerCellSpursKernel3)} SPU: [0x11fd4] Branch-to-next with $LR
E {SPU[0x2000002] Thread (DLSpursManagerCellSpursKernel2)} SPU: [0x11fd4] Branch-to-next with $LR
S {rsx::thread} RSX: New program compiled successfully
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x01deb090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache//08/526dceef2e155030fc19c2b7d7370285” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x01deb090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache//16/f4307e6eac2bea1ef029ac6a5addd7f8” [1]

And what can I do?

**Comment by kd-11** [comment]
Delete /dev_hdd1/cache and let the game recreate its cache

**Comment by d3vv** [comment]
I did, but issue still present... Moreover late I did clean install for each build (new directory, install ofw, gameboot and settings)...

**Comment by kd-11** [comment]
No idea. I tried running around that area for 10 mins and got nothing. Even replicated your movements down to the roll and still nothing. It just works as it always has for me. Try changing to interpreters and see if it still happens.

**Comment by d3vv** [comment]
@kd-11 
I tried all variants of interpreters and it still happens. Moreover I did clean build installation on other HDD..
Do You have two files below?
 “/dev_hdd1/cache//08/526dceef2e155030fc19c2b7d7370285” 
 “/dev_hdd1/cache//16/f4307e6eac2bea1ef029ac6a5addd7f8”

Does it possible to debug why those files can't be created?

**Comment by kd-11** [comment]
I have those files in dev_hdd1 yes. The game generates the cache itself from game files which is why I assumed it was a broken dump the first time. Delete the dev_hdd1/cache again and run DeS then attach the log. You will know its generating a cache because the first screen will take a lot longer than usual to proceed.

**Comment by d3vv** [comment]
@kd-11 
There is a log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1415567/RPCS3.log.gz)

Thank You for a time.. I did dump with multiMAN and I understand that maybe disk is broken, maybe it is multiMAN fault, maybe bad sync between PS3 and PC (too many maybe)... But I never see any error during any process.. 

There is a file with all md5-sums of all content w/o a PS3UPDAT.PUP:
[BLUS30443-[Demons Souls].zip](https://github.com/RPCS3/rpcs3/files/1415599/BLUS30443-.Demons.Souls.zip)

Would You like to compare it or give me ur md5-sums and I do a diff myself?

**Comment by d3vv** [comment]
I will close a ticket cause this is my fault due to bad sync from PS3 HDD with file system corruption..
It is OK now...
I beg your pardon! :((
