### ISSUE TITLE
Regressions with #3638

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#3649]
Master:
![image](https://user-images.githubusercontent.com/15137035/31966283-b8f3aa5a-b951-11e7-87fb-95db904b4616.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1412418/RPCS3.log.gz)

Before #3638 was merged:
![image](https://user-images.githubusercontent.com/15137035/31966069-ffc73a1a-b950-11e7-8d53-1a8265bc44d2.png)

**Comment by Asinin3** [comment]
Young Justice crashes shortly after starting a new game.
![rpcs3_2017-10-25_09-46-27](https://user-images.githubusercontent.com/15137035/31972865-6ee26672-b96a-11e7-8cd9-32c83b93cd61.jpg)
[RPCS3_Logfix.log.gz](https://github.com/RPCS3/rpcs3/files/1412800/RPCS3_Logfix.log.gz)

I tried around 15 games but this was all i found.

**Comment by asbel123** [comment]
same problem in tales of graces f on title screen new version build its happen now

**Comment by asbel123** [comment]
cant play it

**Comment by kd-11** [comment]
A fix for the first issue will be up in the next 24h. For the second crashI just need more info, specifically small test cases where the behaviour is present.

**Comment by Asinin3** [comment]
@kd-11 Well It's a 100% reproducible crash, just get to the title-screen and start a new game and RPCS3 will crash within a few seconds. Assuming the other crashes are reproducible as well I'm not sure what else I can provide you with apart from finding more games that exhibit this behavior.

**Comment by asbel123** [comment]
its vulkan issue opengl doesnt have issue with tales of graces f tittle screen error

**Comment by kd-11** [comment]
Just to clarify, all these are using write color buffers option?

**Comment by kd-11** [comment]
Retest with https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.3-1061

**Comment by SakataGintokiYT** [comment]
@kd-11 
Write color buffers causes crash ('nvoglv64.dll') in Young Justice.

**Comment by Asinin3** [comment]
@kd-11 I tried Young Justice again and it still crashes with nvoglv64.dll but **only** when WCB is enabled regardless of using the fork or Master after #3638 was merged. I then ran a few other games with WCB enabled to see if they would crash. Gatling Gears and Demon's Souls did not have this error however Young Justice, Army of Two and Ni No Kuni did. While Ni No Kuni does not require WCB I tried it anyway.

After realizing I was using Vulkan for all three games that crashed with a nvoglv64.dll error I tried OpenGL+WCB. While they wouldn't crash RPCS3 with a nvoglv64.dll error, they did however freeze RPCS3 at the exact same spot where Vulkan crashes. I didn't see any relevant error/fatal error in my log with OpenGL so I don't think that would be helpful.
**Vulkan logs from the nvoglv64.dll crash:**
[YoungJusticeLogFix.gz](https://github.com/RPCS3/rpcs3/files/1420162/YoungJusticeLogFix.gz)
[ArmyOfTwoLogFix.gz](https://github.com/RPCS3/rpcs3/files/1420283/ArmyOfTwoLogFix.gz)
[NiNoKuniLogFix.gz](https://github.com/RPCS3/rpcs3/files/1420312/NiNoKuniLogFix.gz)


With your fork Gatling Gears graphics are no longer flickering and the menu displays properly. **However**, when using resolution scale the image does not properly scale down to fit the display/window. You can only see around 1/4 of the top left corner at 300% scaling. This issue is present in-game and it doesn't matter if the game is full screen or windowed.
![image](https://user-images.githubusercontent.com/15137035/32077220-29d1f5d0-baea-11e7-97b9-dc4bf8b89636.png)
I didn't notice this issue in other games though I did not test extensively.

**Comment by money123451** [comment]
![2017-10-26 19_42_42-fps_ 27 90 _ vulkan _ 0 0 3-3-head _ shadow of the colossus _ npua80677](https://user-images.githubusercontent.com/12605368/32082071-1b1c7d5c-ba87-11e7-9887-619a95feec0a.png) Shadow of the colossus you can also put on the list of regressions that are causing crashes it works up till you turn on full pixel mode with write color buffers enabled as long as you use vulkan where it used to work fine opengl dose not seem to exhibit this crash either.

**Comment by kd-11** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.3-1064 Should fix the issues with wcb. Still a corner case does exist that will mess things up and freeze the renderer, but I'll think of a workaround soon.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/3664

**Comment by elad335** [comment]
#3671 @Asinin3
