### ISSUE TITLE
sys_fs_open: Unimplemented flag 01000000 (HDR files)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#3653]
[Rock Band Blitz Trial Version [NPEB00988]](https://forums.rpcs3.net/thread-197351.html)
sys_fs_open(“/dev_hdd1/cache/NPEB00988//hdcache_0.hdr”): Invalid or unimplemented flags: **01000000**
 
[Rock Band Blitz Trial Version [NPUB30749]](https://forums.rpcs3.net/thread-197350.html)
sys_fs_open(“/dev_hdd1/cache/NPUB30749//hdcache_0.hdr”): Invalid or unimplemented flags: **01000000**

[Green Day: Rock Band [BLUS30350]](https://forums.rpcs3.net/thread-188697.html)
sys_fs_open(“/dev_bdvd/PS3_GAME/USRDIR/gen/patch_ps3.hdr”): Invalid or unimplemented flags: **01000000**

[Rock Band 3 [BLUS30463]](https://forums.rpcs3.net/thread-188535.html)
sys_fs_open(“/dev_hdd1/cache/BLUS30463//hdcache_0.hdr”): Invalid or unimplemented flags: **01000000**

[The Beatles: Rock Band [BLES00532]](https://forums.rpcs3.net/thread-188614.html)
sys_fs_open(“/dev_hdd0/game/BLES00532/USRDIR/gen/patch_ps3.hdr”): Invalid or unimplemented flags: **01000000**

**Comment by PixelGaming123** [comment]
how do i fix this
