### ISSUE TITLE
Add Support Argument To Direct Boot Files SELF Or ELF

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#3654]
Sometime We Need To Add Arguments To Some Programs And Games (Direct Boot File SELF or ELF)
I Think This Useful To Add RPCS3

**Comment by clienthax** [comment]
What?

**Comment by hcorion** [comment]
I think what aakh1361 means, is that he wants to be able to boot an ELF/SELF with arguments.
Like `.\RPCS3.exe TESTSTUFF.self --version` and `--version` would be passed to TESTSTUFF.self

I'm not 100% sure if this is actually a thing you can do with (S)ELFs on a real PS3/DECR?

**Comment by clienthax** [comment]
Yeah it's completely possible via target manager, and a lot of games have debug args in them

**Comment by aakh1361** [comment]
@hcorion 
Yes You Right

Some Files Load Whit argument Like Inside Emulators PS1 PS2 PSP whit arguments

http://www.psdevwiki.com/ps3/PS1_Emulation_enviroments_in_PS3_firmware#arguments
http://www.psdevwiki.com/ps3/PSP_Emulation_enviroments_in_PS3_firmware#arguments

End my goal is Run this emulators in RPCS3

**Comment by kd-11** [comment]
Nekotekina had this implemented a few weeks ago, but its not in master yet. Maybe it doesn't work properly yet or something.

**Comment by hcorion** [comment]
Should be fixed by 00a0d374550b5e53d9da2e7ba0d0aa805eeeb4f2
