### ISSUE TITLE
Render glitches in Silent Hill Downpour when Strict Mode is off

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3656]
Both OpenGL and Vulkan, both native or multiplied resolution.
There are some areas where moving camera on some angles provokes these glitches. The first one is repeatable on intro scene fighting. Some areas are just full of that, and hard to be passed through. Is the any way to implement some from Strict Mode to fix that?

![rpcs3 2017-10-26 11-40-55](https://user-images.githubusercontent.com/1223276/32043779-60676b26-ba44-11e7-8a1b-d12341a459a3.png)
![rpcs3 2017-10-26 11-41-08](https://user-images.githubusercontent.com/1223276/32043780-6089c96e-ba44-11e7-89d3-b13e26ba2848.png)
![rpcs3 2017-10-26 11-45-10](https://user-images.githubusercontent.com/1223276/32043781-60a9b8e6-ba44-11e7-8733-d5dd6d692800.png)
![rpcs3 2017-10-26 11-45-35](https://user-images.githubusercontent.com/1223276/32043782-60d154d2-ba44-11e7-8a5d-3407a674915b.png)

**Comment by kd-11** [comment]
Thats what strict mode is for. The emulator should run with strict mode always on, but the toggle is there to avoid the performance loss associated with accurate emulation.

**Comment by Psycho-A** [comment]
@kd-11 I understand, but I know there were fixes for other games that allowed to not use Strict mode anymore when playing in upscaled resolution. Is there something to do to allow run THIS game better..?

**Comment by kd-11** [comment]
The most common causes of the need for strict mode will never be worked around any other way. Maybe something can be done to allow a half-way option where accurate paths are taken and some enhancements are available, but that is a slippery slope. Which options should be allowed into strict or not? I'm trying to avoid users having to deal with dozens of checkboxes in options that most people won't understand, which is why they are all grouped under strict option.

**Comment by Psycho-A** [comment]
@kd-11 What about extra options in Debug tab? This needed for advanced users only, so they can experiment with settings, while common users will get just one Strict Mode checkbox as usual. Imho, this is the best way to make individual configurations instead of making some workarounds in emulator for each game.

**Comment by isshininu** [comment]
@Psycho-A Strict Rendering Mode still works for you?
It causes crash on my machine https://github.com/RPCS3/rpcs3/issues/4203

**Comment by isshininu** [comment]
btw, is that the glitch you are talking?
![472](https://user-images.githubusercontent.com/6324523/37832832-3568c1f6-2ec3-11e8-9744-a88c7c2c9bce.png)
warning: game scaled to 125% + anisotropic filtering at x16 used

**Comment by Psycho-A** [comment]
Yes, it's exactly that kind of glitches I often get.
Strict rendering works for me (on Vulkan at least).

**Comment by pitkevich80** [comment]
How to enable "Force CPU blit emulation" ??
