### ISSUE TITLE
GL/Vulkan: Kingdom Hearts II Final Mix (HD 2.5) graphical issues

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#3658]
Tested in https://github.com/RPCS3/rpcs3/commit/9c9495621cd22950bb7bcc3236b249477e1ca220:

In OpenGL and Vulkan, there's broken bloom in World Map and Twilight Town (look at the yellow-ish line). In Timeless River, trees have an Alpha issue and when you pause the game, background is black.

**OpenGL**:
![kh2-3](https://user-images.githubusercontent.com/20027681/32058436-427520ec-ba6a-11e7-85f6-489dc147faaa.png)
![kh2-4](https://user-images.githubusercontent.com/20027681/32058442-44eb4aae-ba6a-11e7-8671-8be73655cf1a.png)
![kh2-5](https://user-images.githubusercontent.com/20027681/32058452-4a9cf1c8-ba6a-11e7-810a-51322dca47ff.png)

**Vulkan**:
![kh2-1](https://user-images.githubusercontent.com/20027681/32058392-2c72a97c-ba6a-11e7-947e-c25baa4392cc.png)
![kh2-2](https://user-images.githubusercontent.com/20027681/32058401-3293c840-ba6a-11e7-8880-7ca4c178c192.png)
![kh2-6](https://user-images.githubusercontent.com/20027681/32058412-363d1dd4-ba6a-11e7-9726-c76bdbb91b85.png)

[Log OpenGL](https://drive.google.com/open?id=0B9LymxJkpT48QWctX2R0NVRNNHc)
[Log Vulkan](https://drive.google.com/open?id=0B9LymxJkpT48a2xoQjNWYjVxcGs)

[Shaderlog OpenGL](https://drive.google.com/open?id=0B9LymxJkpT48MXFiUDEzM0Z2VWs)
[Shaderlog Vulkan](https://drive.google.com/open?id=0B9LymxJkpT48V0QzU1lieTJlMTA)

[RenderDoc](https://drive.google.com/open?id=0B9LymxJkpT48WGxQTHB4WFlaNlE)

**Comment by MarioSonic2987** [comment]
With #3699, bloom is fixed.
![image](https://user-images.githubusercontent.com/20027681/32608852-f2ccbb82-c55d-11e7-807d-754288277689.png)
![image](https://user-images.githubusercontent.com/20027681/32608911-24ce871e-c55e-11e7-8cfb-1d60146aa299.png)

**Comment by MarioSonic2987** [comment]
With #3744, background in pause menu is fixed.
![](https://cdn.discordapp.com/attachments/272875751773306881/382167886841643008/image.png)
![image](https://user-images.githubusercontent.com/20027681/33021903-a9f72358-ce03-11e7-8aeb-20a8f56fe178.png)

**Comment by MarioSonic2987** [comment]
With #4162, fixes missing lens flare in Twilight Town:
![image](https://user-images.githubusercontent.com/20027681/36311049-47da08ea-132a-11e8-9545-82af27e0d195.png)

**Comment by jobs-git** [comment]
Then this can be closed?

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/36315856-047b239a-1339-11e8-9925-8b83211574aa.png)
Remains this glitch.
@jobs-git

**Comment by MarioSonic2987** [comment]
With #4261, fixes alpha issue in Timeless River:

![image](https://user-images.githubusercontent.com/20027681/37221099-0589194a-23c9-11e8-8df4-1189b89600ca.png)
![image](https://user-images.githubusercontent.com/20027681/37221052-d149b4be-23c8-11e8-968f-23a4eee52dc9.png)

With this, all reported graphical issues are fixed. Closing this issue.
