### ISSUE TITLE
Compatibility Issue fix request.

### ISSUE THREAD

**Issue by itzJamz** [RPCS3/rpcs3#3659]
Hello, Im trynna make a request with a game i wanna play and its the only reason why i decided to use this emulator its called "Midnight Club Los Angeles Complete Edition" and it aint compatible. When i launch the game the loading screen is fine but the menu it drops down to 1fps and its completely unusable, trust me i tried everything and it still doesnt work. Please try to make it compatible as soon as possible.
Thank you

**Comment by HenningJW** [comment]
From https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md

> The GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. Requests for support or incorrect reports will be closed.
