### ISSUE TITLE
Blurred textures in Vulkan, not in OpenGL [BLUS30793]

### ISSUE THREAD

**Issue by miguel-nunes** [RPCS3/rpcs3#3662]
In Linux, the Vulkan drive shows blurred Textures and OpenGL not. Follows the screenshots, logs and shaderlogs. If you folks need aditional information let me know.

I like a lot this game and I'd like to see it perfect in Linux! Those issues doesn't happen in Windows.

Vulkan
![ssfa4-vulkan](https://user-images.githubusercontent.com/21225981/32101483-23ae632a-baf7-11e7-9126-a311fb52fbaa.png)

OpenGL
![ssfa4-ogl](https://user-images.githubusercontent.com/21225981/32101500-31f08936-baf7-11e7-917e-751f289c5453.png)

RPCS3 OGL Logs: https://drive.google.com/file/d/0B9Pdstc3j3I_U0pQWGJKN1Jlajg/view?usp=sharing
RPCS VK Logs: https://drive.google.com/file/d/0B9Pdstc3j3I_RWplb0xVbENjSG8/view?usp=sharing
ShaderLogs OGL: https://drive.google.com/file/d/0B9Pdstc3j3I_MFFRSmtPNzYwSHc/view?usp=sharing
ShaderLogs VK: https://drive.google.com/file/d/0B9Pdstc3j3I_VFdpaFNxMnNJSEE/view?usp=sharing

Cheers and amazing work with this PS3 Emulator!

**Comment by scribam** [comment]
@miguel-nunes Is it still an issue? The blur was fixed for #2536 with #3699

**Comment by miguel-nunes** [comment]
@scribam, I'll check later if the issue still happens. I'm at work now, unable to open the emulator right now. I really hope this issue was fixed!

**Comment by miguel-nunes** [comment]
@scribam The problem still happens. I tested with my own builds and with AppImage builds and the results are the same. I've cleared both LLVM and shader caches just to be sure. The blurred textures are not fixed yet for BLUS30793... :(

**Comment by miguel-nunes** [comment]
Guys, 

Proud to say that all those issues are now gone! Congrats to everyone!
