### ISSUE TITLE
Some issues with SoulCalibur IV [ BLUS30160 ]

### ISSUE THREAD

**Issue by miguel-nunes** [RPCS3/rpcs3#3663]
This game have a lot of issues, but I'd like to point out two. These maybe affect more games, so fixing them will help a lot the emulator overall.

First, corruption of textures with Vulkan in the intro:

![sc4-vulkan](https://user-images.githubusercontent.com/21225981/32107658-173ebe48-bb0e-11e7-9c8d-f7dc6cd934ce.png)

And after sometime into the intro, this Exception:

F {PPU[0x1000001] Thread (mainThread) [0x00087ca0]} St13runtime_error thrown: Verification failed (e=11) (0): 
(in file /home/mnunes/apps/rpcs3/rpcs3/Emu/Cell/lv2/sys_memory.cpp:52)

This error occurs at this point, but some releases fixed it and broke the same way more ahead in the intro.

Follows Log: https://drive.google.com/file/d/0B9Pdstc3j3I_UmdKdkh1Sk9KV1U/view?usp=sharing
Shaderlog Logs: https://drive.google.com/file/d/0B9Pdstc3j3I_cG5ieTVpWHE3eVU/view?usp=sharing

If you folks need more info or help let me know!

Cheers and keep up with the great job on this emulator!

**Comment by raveskirza** [comment]
Please check with the latest RPCS3 version. Jarves commit dc0f2ca has reduced sys_memory.cpp:52 error in the game. 
For the corrupt textures, I have the european version of the game and i dont see any texture corruption. This may be probably related to nvidia Linux drivers. 

![image](https://user-images.githubusercontent.com/28158623/33511491-630f84be-d6e9-11e7-85e6-18ab926bdad5.png)

**Comment by miguel-nunes** [comment]
I think we can close this issue @raveskirza. The graphical problems is directly related to Driver problems so there's not too much to do.

But I saw that the SPU improvements made the intro animations runs completely. Nice work guys. This awesome work is making a lot of games working like a charm!
