### ISSUE TITLE
AppImage fails to run, GLIBCXX_3.4.21 not found

### ISSUE THREAD

**Issue by probonopd** [RPCS3/rpcs3#3666]
Currently the mimimum system requirement for applications listed in the [AppImageHub central directory of available AppImages](https://appimage.github.io/apps/) is Ubuntu 14.04 trusty, the oldest still-supported LTS version.

However, the RPCS3 AppImage fails to run since it needs a newer libstdc++ than what comes with Ubuntu 14.04 trusty. This results in a `GLIBCXX_3.4.21 not found` error.

```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-7327/AppRun)
/run/firejail/appimage/.appimage-7327/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /run/firejail/appimage/.appimage-7327/AppRun)
```
References:
* https://travis-ci.org/AppImage/appimage.github.io/builds/294055878#L701-L702
* https://github.com/AppImage/appimage.github.io/pull/376

This could be solved by compiling RPCS3 on a stock Ubuntu 14.04 trusty system, while making sure that no never libstdc++ version is installed on the build system than what comes with the system by default. 

Alternatively, libstdc++ could be bundled inside the AppImage; in this case, care must be taken not to load this bundled libstdc++ version if a newer version of it is already present on the system, or else it will crash. For further information, please see https://github.com/darealshinji/AppImageKit-checkrt.

**Comment by probonopd** [comment]
Yes, `libstdc++.so.6: version 'GLIBCXX_3.4.20' not found` still persists. To check, run it on a Ubuntu 14.04 Live ISO.

**Comment by hcorion** [comment]
Alright, the latest build now works on Ubuntu Trusty.
I was looking at your script, and you can get the latest build of rpcs3 using something like 
`https://rpcs3.net/cdn/builds/$(curl -s https://rpcs3.net/cdn/builds/latest-llvm.txt)`

**Comment by probonopd** [comment]
> https://rpcs3.net/cdn/builds/$(curl -s https://rpcs3.net/cdn/builds/latest-llvm.txt)

Thanks @hcorion is there any chance you could add permalinks? Reason is that we can't have bash scripts in the data files for each application (only links).

**Comment by AniLeo** [comment]
Yes, will add permalink for latest Linux build. latest-llvm.txt is used on internal scripts and wasn't meant for end user usage, although it can be accessed by anyone who wants to fetch the latest filename.

**Comment by AniLeo** [comment]
I've added permalink for the latest Linux AppImage

**wget**
`wget --content-disposition https://rpcs3.net/latest-appimage`

**curl**
`curl -JLO https://rpcs3.net/latest-appimage`
