### ISSUE TITLE
Regression Sly Cooper Thieves in Time PR 3458

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#3676]
The very first commit 2033f3f of PR 3458 causes an invisible environment issue, can't tell for sure which part of it cause commits were squashed, no 3d graphics only black screen and some parts of HUD are visible
![56](https://user-images.githubusercontent.com/7060586/32139391-95b314a8-bc4f-11e7-8ef1-aebe0c6a416f.jpg)
please take a look

**Comment by Zangetsu38** [comment]
![capture d ecran 2017-10-29 01 23 22](https://user-images.githubusercontent.com/5261759/32139408-cad27096-bc47-11e7-8793-09b64b80dc2a.png)
works for me

**Comment by Xcedf** [comment]
am i doing smth wrong?
pc: 6700k gf gtx1070 driver 387.92
btw i also do not have image in SoTC game, and like with this game i only have strange colored image with wcb on

**Comment by Xcedf** [comment]
This is how it looked before 2033f3f with wcb off
![34](https://user-images.githubusercontent.com/7060586/32139558-ea925a1a-bc54-11e7-9aaf-100248cf51f6.jpg)
and this how it looks with WCB On now
![54](https://user-images.githubusercontent.com/7060586/32139569-3d5527be-bc55-11e7-9217-75519a6d9a48.jpg)

**Comment by Zangetsu38** [comment]
for wrong color kd already know that

**Comment by Asinin3** [comment]
With SoTC i think you need OpenGL+WCB and enable pixel mode in the in-game options. I don't think it works with Vulkan but it may.

**Comment by Xcedf** [comment]
SoTC with Vk or OGL + WCB ON + Full Pixel Mode looks fine but same colors as my last screen

**Comment by kd-11** [comment]
It happens with wcb+vulkan. Its been like this for a while, its a known issue.

**Comment by Xcedf** [comment]
I think you're right, tested OGL a bit more, it has normal colors with WCB

**Comment by AniLeo** [comment]
#3031
