### ISSUE TITLE
Demon's Souls Setup Issues

### ISSUE THREAD

**Issue by LordCrason** [RPCS3/rpcs3#3677]
Build: 
intel core i5 7600k
EVGA Geforce GTX 1060
16 GB RAM (2 x 8 GB)
Version of RPCS3: v. 0.0.3-3-882e949 Alpha
I downloaded both the .pkg and the .rap files for Demon's Souls [US] from [edited] and used the .pkg installer to get RPCS3 to recognize it. I put the .rap file in dev_hdd0 > home > 00000001 > exdata. When I try to run the game, the .log file says the below:
RPCS3 v0.0.3-3-882e949 Alpha | HEAD
Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz | 4 Threads | 15.96 GiB RAM | AVX | TSX
E LDR: Disc game BLUS30443 found at invalid location /dev_hdd0/game/
E LDR: Failed to move disc game BLUS30443 to /dev_hdd0/disc/ (Already exists)
S LDR: Boot from gamelist per doubleclick: done

What have I done wrong, and how can I fix it?

**Comment by Talkashie** [comment]
Piracy is not supported here!

**Comment by Asinin3** [comment]
Not to mention this isn't the place to ask for support.

**Comment by B1ackDaemon** [comment]
Sorry, no piracy is allowed.
