### ISSUE TITLE
cellGameGetParamString: bad_alloc

### ISSUE THREAD

**Issue by Ankris** [RPCS3/rpcs3#3679]
Log: [log.txt](https://github.com/RPCS3/rpcs3/files/1425021/log.txt)

**Comment by AniLeo** [comment]
That's not a full log, we need RPCS3.log

**Comment by Ankris** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1425047/RPCS3.log.gz)

**Comment by AniLeo** [comment]
```·W 0:00:07.073388 {PPU[0x1000000] Thread (main_thread) [0x0071e2a0]} PPU: 'cellGameGetParamString' aborted
·F 0:00:07.094435 {PPU[0x1000000] Thread (main_thread) [0x0071e2a0]} class std::bad_alloc thrown: bad allocation
```

**Comment by Farseer2** [comment]
Should fix the crash, it was an overflow - don't know if the bufsize==0 is a different bug, though.
