### ISSUE TITLE
screen problem

### ISSUE THREAD

**Issue by bijita1** [RPCS3/rpcs3#3680]
Anyway hi and thanks for the hard work up to now it is hard to find a real ps3 emulator that can run game at 30 fps in a full hd to 4k TV but that is not what I’m here for regarding playing game I found that the game ‘’ super heroine chronicle ‘’ in 60 % of the game play only show in the lower half of the screen not all the game but the welcome screen and action .

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
