### ISSUE TITLE
What is causing THIS error? 

### ISSUE THREAD

**Issue by anitadickrightnow** [RPCS3/rpcs3#3684]
Specs: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz | 8 Threads | 7.91 GiB RAM | AVX

I keep on getting the error 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1] whenever I try to run games with RPCS3. The game just shows up, all white screen, and that's it. Any idea on what's causing this error?

**Comment by AniLeo** [comment]
Not an error, expected behavior as cellLibprof is a debug module.
