### ISSUE TITLE
【GUI】hide null renderer option

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#3685]
since this option used only for debugging purposes and to prevent someone who's english isn't great from choosing this option thinking it's like any other renderer e.g OpenGl, hide this option .
If someone wants to use it , modifing config.yml will be the way to use this option .

**Comment by hcorion** [comment]
RPCS3 is still very much in Alpha. Stupid users will be stupid.

**Comment by elad335** [comment]
there are a lot of other debbuging features that work exactly like that , and most of the world aren't native english speakers nor stupid.

**Comment by AniLeo** [comment]
I've never seen anyone choosing it thinking it was an actual render..

**Comment by elad335** [comment]
so I'll leave it closed for now

**Comment by AniLeo** [comment]
I have moderated forums for more than a year now, discord since it exists and reddit since we revamped it, it's safe to say it's not an issue. 

It would be more of a hassle for people who need to use it than actually help
