### ISSUE TITLE
Regression: Ridge Racer 7 (#3686)

### ISSUE THREAD

**Issue by Zangetsu38** [RPCS3/rpcs3#3697]
Ridge racer 7 with update 1.01 now crash after launch main.self in update.
regression caused directly by commit https://github.com/RPCS3/rpcs3/commit/0e7e40f2cbe2cce45fed49b6815e32fefc4e322e
Log crash with last master build appveyor.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1442481/RPCS3.log)
And if you see, in this log, rpcs3 try open update and loop. 
Veryfied in my build after remove only this commit, game re works normal with this update.

For compare in my build last master without this commit, with game works normally.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1442510/RPCS3.log)

**Comment by AniLeo** [comment]
@Zangetsu38 retest with master

**Comment by Zangetsu38** [comment]
It is fixed now with last PR :) 
![image](https://user-images.githubusercontent.com/5261759/34418234-314c2f62-ebfd-11e7-96de-6c4716b8a3f4.png)

**Comment by Zangetsu38** [comment]
@Nekotekina with your last PR, you have fixed issue for RR7, but other game with update is now full totaly broken, for exemple, Sword art online, Update 1.04, caused infinite loop.
Dragon quest Builder, Update 1.03, have just black screen.
My old tips with disable fxm::clear now don't works :/
