### ISSUE TITLE
Blit request denied because the destination region does not fit!

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#3698]
On Rayman Legends [BLUS31183], I've got graphical glitches: foreground goes from perfect to black depending on the character position.
I noticed a lot of these messages in the logs:
{rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 1
{rsx::thread} RSX: Blit request denied because the destination region does not fit!
Tested with vulkan and ogl, recompiler and interpreter.

RPCS3 v0.0.3-50-4600094 Alpha | HEAD
Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz | 8 Threads | 15.62 GiB RAM | AVX
Archlinux with r9 fury (mesa 17.2)

![fps 61 37 vulkan 0 0 3-50-head rayman legends blus31183 _001](https://user-images.githubusercontent.com/7478580/32404054-d4a459ee-c148-11e7-8550-6f777ee4e885.jpg)
![fps 61 37 vulkan 0 0 3-50-head rayman legends blus31183 _002](https://user-images.githubusercontent.com/7478580/32404056-d6951d9c-c148-11e7-8dbe-c2f138326c1d.jpg)

[RPCS3-RaymanLegends-OGL.zip](https://github.com/RPCS3/rpcs3/files/1443087/RPCS3-RaymanLegends-OGL.zip)
[RPCS3-RaymanLegends-Vulkan.zip](https://github.com/RPCS3/rpcs3/files/1443088/RPCS3-RaymanLegends-Vulkan.zip)

**Comment by Megamouse** [comment]
can you retest please?

**Comment by toccata10** [comment]
rev6926: Spu LLVm crashes (segfault) the emu.
With Asmjit: same message:
E {rsx::thread} RSX: Blit request denied because the destination region does not fit!
Compared to the previous tested version, I'd say it's worse because the background is rapidly blinking all the time. WCB+strict rendering mode don't change anything. Don't know which PR caused this (but it happened quite some time ago).
[RPCS3.log-RaymanL.gz](https://github.com/RPCS3/rpcs3/files/2131882/RPCS3.log-RaymanL.gz)

**Comment by Emulator-Team-2** [comment]
Graphic flicker is fixed by #5427

**Comment by kd-11** [comment]
Dst clipping was fixed in the last RSX PR.
