### ISSUE TITLE
Regression: Earth Defense Force 2025 - VK_ERROR_DEVICE_LOST (#3458)

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#3700]
After the "select number of players" screen Earth Defense Force 2025 freezes here then gives a fatal error.
![image](https://user-images.githubusercontent.com/15137035/32412027-168ef740-c23b-11e7-8a63-23623eff4a6b.png)

So I went back and eventually found that #3458 caused me to no longer be able to get ingame and freezes at the exact same spot as master with an almost identical error. The builds before are fine.

#3458 RPCS3 v0.0.3-3-3499d08 Alpha
`E {rsx::thread} RSX: Cached object for address 0xCB866A80 was found, but it does not match stored parameters.`
`E {rsx::thread} RSX: 1280 x 720 vs 2560 x 720`
`E {rsx::thread} RSX: ERROR: [IMAGE] Code 419430670 : vkCmdCopyImage called with unmatched source and dest image format sizes.. The spec valid usage text states 'The VkFormat of each of srcImage and dstImage must be compatible, as defined below' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdCopyImage-srcImage-00135) x21`
`F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is FFFFFFFCh
[3458_VK_Debug_EDF_logfix.gz](https://github.com/RPCS3/rpcs3/files/1443780/3458_VK_Debug_EDF_logfix.gz)

GPU: 1080ti + Latest 388.13 WHQL drivers
OS: Win10

**Comment by kd-11** [comment]
I have a fairly good idea why it happened. You can use cpu blit to verify it stops happening.

**Comment by Asinin3** [comment]
@kd-11 That fixed it.

**Comment by Asinin3** [comment]
![image](https://user-images.githubusercontent.com/15137035/34418001-88347228-ec4b-11e7-80c3-ebfb89d62fa4.png)
Fixed
