### ISSUE TITLE
street fighter 4 arcade edition stops at character entrance. help pls

### ISSUE THREAD

**Issue by sydpad** [RPCS3/rpcs3#3705]
street fighter 4 arcade edition stops at character entrance. help pls
this is the one appearing...

F {PPU[0x1000000] Thread (main_thread) [0x00ab8798]} class std::runtime_error thrown: Verification failed (e=0x3): 
(in file Emu\Cell\lv2\sys_lwcond.cpp:192)
E {PPU[0x1000000] Thread (main_thread) [0x00ab8798]} Stat: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30649/USRDIR/dlc/ui/user_title/ENG/user_title.eaf” [x4]
E {PPU[0x1000000] Thread (main_thread) [0x00ab8798]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “window_06_cursor.gfx” [x7]
E {PPU[0x1000000] Thread (main_thread) [0x00ab8798]} Stat: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30649/USRDIR/dlc/ui/user_icon/user_icon.eaf” [x4]
E {PPU[0x1000000] Thread (main_thread) [0x00ab8798]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “window_06_spinbox.gfx” [x19]
E {PPU[0x1000000] Thread (main_thread) [0x00ab8798]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “window_06_frame.gfx” [x7]
E {PPU[0x1000000] Thread (main_thread) [0x00ab8798]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “window_06_action.gfx” [x7]

**Comment by AniLeo** [comment]
Issue template saying this isn't a place for support didn't appear? We added it a while back

**Comment by ikki84** [comment]
The same fail also happens in Super Street fighter 4 Arcade Edition [NPUB30649] during the first fight, causing the emulator to freeze.

F {PPU[0x1000000] Thread (main_thread) [0x00ab8798]} class std::runtime_error thrown: Verification failed (e=0x3):
(in file Emu\Cell\lv2\sys_lwcond.cpp:192)
