### ISSUE TITLE
[NPUB30649] Fail in sys_lwcond.cpp:192 , Verification failed (e=0x3)

### ISSUE THREAD

**Issue by ikki84** [RPCS3/rpcs3#3706]
In RPCS3 v0.0.3-3-6782b22 Alpha:

F {PPU[0x1000000] Thread (main_thread) [0x00d3f398]} class std::runtime_error thrown: Verification failed (e=0x3): 
(in file Emu\Cell\lv2\sys_lwcond.cpp:192)

Full log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1451295/RPCS3.log.gz)

**Comment by Farseer2** [comment]
Is it reproducible? If not, does it still happen consistently?

**Comment by kd-11** [comment]
Yes, on (some) id tech 5 titles it happens without fail. Tested with Rage and The Evil Within.

**Comment by ikki84** [comment]
I believe it´s reproducible. I also did a clean install and the error persists. 
Happens consistently (always during the first fight).

**Comment by Zangetsu38** [comment]
GT6 Game also
>F {PPU[0x100001d] Thread (fmBKi) [0x00bbe7d0]} class std::runtime_error thrown: Verification failed: 
(in file Emu\Cell\lv2\sys_cond.cpp:279)

**Comment by elad335** [comment]
Retest with ppu threads number set to 1.

**Comment by ikki84** [comment]
I am sorry for the late reply.
I could not test before because the game was freezing in the intro video, But its not happening with https://github.com/RPCS3/rpcs3/pull/5310

The fail in "sys_lwcond.cpp:192" doesnt happen anymore if you merge https://github.com/RPCS3/rpcs3/pull/5265 
@elad335 

Now that the emulator proceeds without that error, another issue occured: 
-The game freezes/lock after the fight end if using PPU LLVM (doesn´t frezees in while using PPU interpreter)

**Comment by ikki84** [comment]
Fixed with https://github.com/RPCS3/rpcs3/pull/5314

**Comment by jonyvx** [comment]
same error : verification failed..unhandeld error worker 1
Latest version
Mortal Kombat 9 Vulkan

https://imgur.com/a/oZ9ODJ7

**Comment by jonyvx** [comment]
after some testing got this :

https://imgur.com/a/b8BolbV

**Comment by jonyvx** [comment]
after more testing ...fixed or avoiding or cause for Fatal error is choosing giga instead of safe in spu block size..made rpcs3 crash with no error message ...also when choosing vulkan + safe spu block size mortal kombat 9 loads with no error or crash but all black screen with audio working in background.....any fix ?
thanks

**Comment by jonyvx** [comment]
after more testing... made game mortal kombat 9 run with vulkan at 60 fps smooth fast with some audio lag stutering but very playable with low resolution but rpcs3 stops completly after some minutes of playing ..also rpcs3 dosn't  fully stop game or close the game, it stays ocuping lots of mb in ram ...must terminate whole program then reopen it .

https://imgur.com/a/dscdiYf

**Comment by jonyvx** [comment]
after more testing and removing all caches of game : mortal kombat 9 komplete edition run good with vulkan  on practice mode but stutering audio and after changing options it dosnt crash or stop or close after long play and finaly fixed no black screen on vulkan ..but game stops after random minutes in ladder mode
i can upload video for this to help people 
these are the options for good play but not stable fps nor audio

for cpu:
https://imgur.com/a/bMslpsv
for gpu:
https://imgur.com/a/T9hqPcy

**Comment by jonyvx** [comment]
should change game status to " playable" it got fast fps on practice mode ,and fast fps on story mode but stop with error "rsx:FIFO error: possible desync event x 2240" in story mode,and stop on ladder mode..it should be playable status because can practice with all characters fine .

**Comment by AniLeo** [comment]
Removed all spam and locked the issue

This issue has been long solved and it has not regressed up until this day, don't go around spamming issues with random things completely unrelated to the issue you're on
