### ISSUE TITLE
Regression ( BLES00464) Fear 2 Project Origins

### ISSUE THREAD

**Issue by Gamedev1909** [RPCS3/rpcs3#3712]
Game went from playable fully max fps to not playable newest master Build 
fps from 43fps to 7fps 
also new flicker on logo's and in game as well

Pull request #3708 - Fix cond timeout overflow [Windows]
Correctness
0.0.3-6762
an hour ago by Ofek (committed by GitHub)
master 429dfdb2
OS: Microsoft Windows 10 Pro (x64) • CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (4.00GHz) • Memory: 16.0 GiB Total (9.9 GiB Free)  • VGA: AMD Radeon R9 200 Series • Uptime: 2d 16h 20m 53s

**Comment by Gamedev1909** [comment]
also deleted llvm cache and shader cache no change reverted back to https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6759 and issues are fixes

**Comment by AniLeo** [comment]
It's not a valid regression to report on a standalone issue if it's not a master build in the first place. Report on the pull request.
