### ISSUE TITLE
Regression: Silent Hill Downpour (#3699)

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3716]
After merging PR #3699 the title screen of game displays with crappy stretching. Repeats only with OpenGL. Scaling, Strict Mode or other settings don't matter. Enabling Write Color Buffers makes game to stop after loading. My video is GeForce GTX 760Ti with latest drivers, OS Win7 x64.

Before:
![rpcs3 2017-11-10 01-23-24](https://user-images.githubusercontent.com/1223276/32633218-b1bdf110-c5b7-11e7-916a-cea918f4c7fe.png)

After:
![rpcs3 2017-11-10 01-21-02](https://user-images.githubusercontent.com/1223276/32633217-b19f0d4a-c5b7-11e7-8761-effb96981c2a.png)

**Comment by kd-11** [comment]
Did you load the binary directly or launch using the main window launcher?

**Comment by Psycho-A** [comment]
@kd-11, both ways gives the same result.

**Comment by Asinin3** [comment]
I just tested this before/after 3699 I deleted shader cache each time but couldn't even get the title screen to show properly. I tried with and without WCB/Strict mode and I either got a black screen or this:
![before_2017-11-10_23-58-11](https://user-images.githubusercontent.com/15137035/32661193-e59175c0-c675-11e7-81e0-a00d34279408.jpg)

Same result on both builds, I even deleted LLVM + Game data, weird that it's not showing for me as it used to work.

**Comment by Asinin3** [comment]
Affects Vulkan for me too

Before:
![image](https://user-images.githubusercontent.com/15137035/32661842-5412f13e-c678-11e7-8dd2-919ac8848d82.png)

After #3699 :
![image](https://user-images.githubusercontent.com/15137035/32661782-22530152-c678-11e7-94ac-2d0a1f92df51.png)

**Comment by isshininu** [comment]
![145](https://user-images.githubusercontent.com/6324523/32815318-e563dbb0-c9cc-11e7-9a1d-ebcdad89ccab.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1473182/RPCS3.log.gz)


Affects me too. Also I would like to notice that loading screen in original game have NO red lines. (e.g. second screen shot taken from YT stream)
![144](https://user-images.githubusercontent.com/6324523/32815302-ce60e5b6-c9cc-11e7-9ba4-64023f60b04a.png)

**Comment by Zangetsu38** [comment]
in last build
![image](https://user-images.githubusercontent.com/5261759/32815942-b12a133e-c9b6-11e7-90e6-c9fa2dec8872.png)

**Comment by isshininu** [comment]
LOL.

Everyone have _their own_ level of redness.

**Comment by Psycho-A** [comment]
Bug is still exist after #3744 and #3749.

**Comment by joaozin23** [comment]
![esboco 3](https://user-images.githubusercontent.com/17303493/32997367-5db2b670-cd76-11e7-8c70-68d19d042676.png)
![esboco 2](https://user-images.githubusercontent.com/17303493/32997369-5dd5050e-cd76-11e7-8b6a-6071ed0845a7.png)

**Comment by Psycho-A** [comment]
Still not fixed...

**Comment by digitaldude555** [comment]
![screenshot 1587](https://user-images.githubusercontent.com/26138653/38084822-093bf7b8-3357-11e8-9ee8-e899f4ce4a11.png)
close?

**Comment by Asinin3** [comment]
Fixed for me with default settings 
![image](https://user-images.githubusercontent.com/15137035/40366970-e78a1668-5dc7-11e8-9ffa-c633c466e104.png)

Can close this issue.

**Comment by Psycho-A** [comment]
@Asinin3 How did you get the FPS 60 while game have cap to 30?

**Comment by Asinin3** [comment]
Magic? I'm not sure myself, maybe different region has different cap in the menus?

**Comment by Psycho-A** [comment]
@Asinin3 I have the same-coded region version, and it was never higher than 30. Is FPS in game >30 too?

**Comment by Asinin3** [comment]
![image](https://user-images.githubusercontent.com/15137035/40481110-e5d2e1c8-5f3f-11e8-8b1c-4cdd3bb31e77.png)
Are you sure you don't have framelimiter on :/

**Comment by Psycho-A** [comment]
@Asinin3 I never enable frame limiter, as well as never seen FPS more than 30 in this game...

**Comment by AniLeo** [comment]
When was this fixed?

**Comment by Psycho-A** [comment]
I don't know exactly, but all latest builds during month shows normal picture on Vulkan and OpenGL too (probably when kd11's epic fixes for UE3 were released). Just forgot to close earlier. If you still encounter some of this, feel free to open...
