### ISSUE TITLE
Trophy Manager doesn't remember its settings and window size/state

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3717]
@flash-fire Hello, could you implement saving Trophy Manager settings and its window size/state?

**Comment by Zangetsu38** [comment]
if you speak icon, yes, no save change size

**Comment by TotalCaesar659** [comment]
Not only icon size, it doesn't save all its checkboxes like "Show hidden trophies" and its window size/state.

**Comment by Marthgun** [comment]
trophy_manager_dialog.cpp
line 32 and 122 should be read from an ini, any adjustment should be written to it

or whatever other file type they use.  i thought QT would remember dialog sizes, maybe its b/c its reinitialized every time u call it.  idk, should be easy fix unless there's some reason not to have variable values.
