### ISSUE TITLE
Kingdom Hearts 2.5 OpenGL regression with #3699

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#3718]
After #3699 was merged the game no longer fills the window with OpenGL, Vulkan works fine. I believe this is related to #3716 .

Before:
![before_2017-11-10_22-59-44](https://user-images.githubusercontent.com/15137035/32659860-65bd3924-c670-11e7-8b3c-609b19c938f1.jpg)

After:
![rpcs3_2017-11-10_23-13-12](https://user-images.githubusercontent.com/15137035/32659803-3e83cc2e-c670-11e7-92c0-6595af7efc08.jpg)

This can be reproduced on the launcher and title screen as well no need to go ingame.

**Comment by kd-11** [comment]
Is there anything actually cropped or is it just inset?

**Comment by Asinin3** [comment]
It's just inset as far as I can tell.

**Comment by MarioSonic2987** [comment]
It's caused by loading directly the game executable.

**Comment by Asinin3** [comment]
Ah you're right... I had KH crash on the launcher so i loaded the .SELF sorry for confusion.

**Comment by kd-11** [comment]
Yeea, dont do that until its proven to work properly. The config path can differ when you load the binary directly
