### ISSUE TITLE
Bugs out of memory when i'm minimize windows GSFrame on Vulkan

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#3719]
You can see at the logs and image
Spec : 
CPU : Core 2 Quad Q6600
GPU : NVIDIA Geforce GTX 950
![image](https://user-images.githubusercontent.com/11285640/32663397-6841bdec-c660-11e7-8326-e63c4c3c0c0a.png)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1461673/RPCS3.zip)

**Comment by AniLeo** [comment]
Only happens with 150% scaling? Or without scaling it happens too?

**Comment by kd-11** [comment]
This issue has 2 other duplicates including one where I have posted a potential fix. Closing as duplicate.
