### ISSUE TITLE
GL Error: Too many instructions (build 8c0bdd7)

### ISSUE THREAD

**Issue by StarWolf3000** [RPCS3/rpcs3#3723]
When trying to fire up Hyperdimension Neptunia mk2 (US, BLUS30901), execution stops before anything happens with:
```
Internal error: assembly compile error for vertex shader at offset 385555:
-- error message --
line 16432, column 1:  error: too many instructions
-- internal assembly text --
```

My system:
* i5-4590 @ 3.3 GHz
* NVIDIA GeForce GTX 960
* Windows 8.1 x64
* RAM: 16 GB
* Vulkan drivers: not installed
* RPCS3 version: 8c0bdd7
* Configuration:
* * PPU Decoder: LLVM
* * SPU Decoder: ASMJIT
* * Threads: auto
* * Add. settings: Bind SPU threads to secondary cores, Enable SPU loop detection, Hook static functions
* * Libraries: autoload required
* * Renderer: OpenGL (DX12 is not available on 8.1, Vulkan is not installed)
* * GPU Add. settings: Strict rendering mode, VSync
* Full log: see attachment

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/1463859/RPCS3.log.zip)

**Comment by kd-11** [comment]
Clear the shaderlog folder then run the game and zip the shaderlog folder and upload that.
That said, this is likely a limitation of nvidia's glsl compiler - unfortunately for emulation its common for the generated code to be larger than original and nothing will change that. If the shader itself is broken it can be fixed otherwise the bug/limitation is in the driver and nothing can be done about that.

**Comment by StarWolf3000** [comment]
Here's the shaderlog zipped, contains 4 4files: 
[shaderlog.zip](https://github.com/RPCS3/rpcs3/files/1464009/shaderlog.zip)

**Comment by StarWolf3000** [comment]
Any info on if this is now just a broken shader or bad shader compiler on nvidia's side?

**Comment by kd-11** [comment]
Its the shader compiler. The shader in question is very long with dynamic branches all over the place. It looks to be an assert for their dev team, I've never seen the compiler spit out gpu_program5 assembly which means its supposed to be for their team to debug. The shader in question, should you choose to take it up with nvidia, is VertexProgram4.glsl.

**Comment by kd-11** [comment]
I'll close this as there isn't much we can do from our end. Maybe in future when the shader decompiler is properly structured to support assembers we can write a nvidia specific backend to work around limitations like these.
