### ISSUE TITLE
Misinterpreted instruction db16cyc

### ISSUE THREAD

**Issue by isJuhn** [RPCS3/rpcs3#3724]
While looking through the code of Ratchet and Clank: Tools of Destruction, I noticed an opcode that is interpreted wrongly by rpcs3. I also had trouble finding documentation on what the opcode does as it seems to be CELL only. the opcode is called `db16sys` and has the hex `0x7FFFFB78`. 

In the rpcs3 debugger, it is shown as a `mr r31, r31` which is wrong. from what I found, it is supposed to delay the current thread 16 cycles. The opcode exists in the variants `db8cyc, db10cyc, db12cyc, db16cyc`. 
db[x]cyc would delay the current thread for x cycles. For accuracy reasons, the opcode should probably be implemented.

The reason why RPCS3 interprets it wrongly is probably because it's almost a `mr r31, r31` except for the fact that `mr` and instructions have a specific value from bit 21 to bit 30. the `db[x]cyc` instruction does not have this specific value.

Here are the opcodes and hex for db[x]cyc
```
db8cyc:  0x7f9ce378
db10cyc: 0x7fbdeb78
db12cyc: 0x7fdef378
db16cyc: 0x7ffffb78
```

**Comment by Marthgun** [comment]
according to PPC documentation `mr r31, r31` is an extended mnemonic that is equivalent to   `or rx, ry, ry`, which i believe means that it uses a bitwise or on ry and 'or's' it with ry again, then stores it in register x.

unless its labeled wrong or my source is wrong, an OR operation is a D-Form, bits 16 to 31 should be used to hold a 16 bit signed or unsigned integer, or a two's complement integer extended to 64 bits.

I don't see any flags for it that would delay clock cycles.

**Comment by isJuhn** [comment]
As you can see [here](https://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/external/gpl3/binutils/dist/opcodes/ppc-opc.c), the instructions `db8cyc, db10cyc, db12cyc, db16cyc` exist for the CELL. It is also mentioned in the book [Practical Computing on the Cell Broadband Engine](https://books.google.se/books?id=f9FxS-mdF8UC&pg=PA25&lpg=PA25&dq=db8cyc&source=bl&ots=H9zjrCNLcb&sig=lltfzDCMCYSP2N3bc6h8cvJr50s&hl=sv&sa=X&ved=0ahUKEwifxI76pLfXAhUJL1AKHUpgA0UQ6AEIJzAA#v=onepage&q=db8cyc&f=false) on page 25.

**Comment by Marthgun** [comment]
well i guess it would help if i was reading the book for PPE :sob:

**Comment by kd-11** [comment]
Doesn't this all mean it's fine as is? Rpcs3 has no real clk and 8 or even 16 cycle delay isnt really going to change anything running via emulation. Besides its already a nop as is and we arent running on hw that needs the cycle delays for instruction latency.

**Comment by isJuhn** [comment]
The instructions have been added to the debugger as of #3899. And as kd-11 says, no implementation is probably needed so I'm closing this issue.
