### ISSUE TITLE
Debugger Crash \ Exception

### ISSUE THREAD

**Issue by Marthgun** [RPCS3/rpcs3#3725]
__Reopened, test with proper VS toolkit, still get same exception__

__Game: Tales of Graces F BLES01617__
__Win 7 (x64)  |  Intel i7-3770k  |  16gb Ram  |  GTX 670__

-------

As of now, using the newest pull, I'm getting an unhandled exception thrown when attempting to view the atrac3plusCellSpursKernel0 thread in the RSX Debugger.  

Using Bin exe, 
![capture](https://user-images.githubusercontent.com/15056246/32695996-14c1a980-c731-11e7-8ad3-ec156f30172e.PNG)

![11](https://user-images.githubusercontent.com/15056246/32696008-67c12d0e-c731-11e7-8d7a-66c3366a0349.PNG)

--------

In VS2017 Release - LLVM x64,  in BEType.h

![222](https://user-images.githubusercontent.com/15056246/32696033-16b01d0c-c732-11e7-8ec7-6b92bc5f3e8b.PNG)

-------
if you need something else let me know

**Comment by scribam** [comment]
@Marthgun Still an issue? Anyway, I think VS2017 is not officially supported by RPCS3. You might find some support on Discord.

**Comment by Marthgun** [comment]
@scribam 
i left this alone because the issue only arose prior to fully loading the game, so it's possible the debugger thread wasn't actually active yet.  it is/was certainly an issue, but not something game breaking, i just needed to check that thread at the earliest possible moment when opening a save.  and setting that thread prior to loading the save would cause the crash, and that's not just in VS2017, that is/was in your releases.  I wouldn't really be surprised if this issue was actually fixed by now.

**Comment by Marthgun** [comment]
If you want me to close this topic, I will, I doubt that anyone else is ever going to run into this problem tbh.

**Comment by scribam** [comment]
@Marthgun It is up to you to keep this issue opened or not. A lot of changes happened since this issue has been created. It could have fixed it and I would like to know if this issue is still relevant. Honestly, I don't think I will not look into it but it's an open source project so anyone can try to help you and I believe it's easier when you have up-to-date information.
