### ISSUE TITLE
[BLUS31002]TEKKEN TAG TOURNAMENT2 /'sys_fs_open' failed/cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)

### ISSUE THREAD

**Issue by gkfrnwkd** [RPCS3/rpcs3#3726]
E {PPU[0x1000019] Thread (tk::async::Thread) [0x019b3090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_flash/data/font/SCE-PS3-RD-R-LATIN.ccd” [1]
E {PPU[0x1000019] Thread (tk::async::Thread) [0x019b3090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_flash/data/font/SCE-PS3-NR-R-JPN.ccd” [1]
E {PPU[0x1000019] Thread (tk::async::Thread) [0x019b3090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_flash/data/font/SCE-PS3-YG-R-KOR.ccd” [1]

U {PPU[0x1000000] Thread (main_thread) [0x0035c85c]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)
U {PPU[0x1000000] Thread (main_thread) [0x0019d6c4]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)
U {PPU[0x1000000] Thread (main_thread) [0x0049a41c]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)
U {PPU[0x1000000] Thread (main_thread) [0x012480a4]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)
U {PPU[0x1000000] Thread (main_thread) [0x00aab24c]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)
U {PPU[0x1000000] Thread (main_thread) [0x00375a14]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)
U {PPU[0x1000000] Thread (main_thread) [0x001a7c3c]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)
U {PPU[0x1000000] Thread (main_thread) [0x001c78a0]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)
U {PPU[0x1000000] Thread (main_thread) [0x0026c0c0]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)
U {PPU[0x1000000] Thread (main_thread) [0x00aab3d4]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)
U {PPU[0x1000000] Thread (main_thread) [0x00b14dd8]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, userData=*0x200fd2e8)
U {PPU[0x1000000] Thread (main_thread) [0x0026bf98]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=100, func=*0x152aae0, `userData=*0x200fd2e8)

**Comment by clienthax** [comment]
Not a issue.
