### ISSUE TITLE
SPU: Recompiler vs. Interpreter mismatch - House of The Dead Overkill [BLUS30774]

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#3730]
Found the mismatch between SPU Precice & Fast and Asmjit in 
House of The Dead Overkill [BLUS30774]
here's the screen comparison
Precise (looks fine)
![12](https://user-images.githubusercontent.com/7060586/32704632-72d1073a-c819-11e7-95fe-d54d59811446.jpg)
Fast (looks fine)
![13](https://user-images.githubusercontent.com/7060586/32704640-805109be-c819-11e7-9d1c-a75223f771e7.jpg)
ASMJit (trees behind the heroes are flickering with artifacts)
![22](https://user-images.githubusercontent.com/7060586/32704649-9a707406-c819-11e7-8d8c-cacfc9644bb6.jpg)

**Comment by scribam** [comment]
@Xcedf Is it still an issue with master (98b715d8c89f3c57b5e0e9f0a541a53d13e96617)? There have been some changes related to the spu recompiler recently that might have affected this game.

**Comment by Xcedf** [comment]
@scribam yes still an issue on ASMJit, but works fine on SPU Fast, unfortunately after ASMjit 2.0 there's some issue within Interpreter Fallbacks, when i tried to fallback a bunch of instructions emu just crashed, didn;t happened before , i wil do some extra debuging on earlier version and perhaps will find some culprit instruction

**Comment by Xcedf** [comment]
On recent builds this issue seems to be fixed, not happening any mor on both LLVM and ASMJit
