### ISSUE TITLE
Device or resource busy (Kingdom Hearts 1.5)

### ISSUE THREAD

**Issue by JacobAL** [RPCS3/rpcs3#3731]
Getting this error: F {rsx::thread} class std::system_error thrown: device or resource busy: device or resource busy when trying to save or open the menu in Kingdom Hearts 1.5 Remix in atlantica.
Specs: https://i.imgur.com/dMlfyL3.png
Error log: https://i.imgur.com/zpM6gkv.png
https://mega.nz/#!YOQ1ma4Q!f_q-eo-O4Deia87vfs5305pAlVZDkiRDXUUPmO7xtQo

Happens in OGL and Vulkan and even happens when using the interpreters rather than recompilers.

Has happened in an older build as well, I think #3690

**Comment by Psycho-A** [comment]
This happens for me too, on some games when WCB is enabled.

**Comment by JacobAL** [comment]
Seems to work with write colour buffers off, thanks.

**Comment by AniLeo** [comment]
This is not a regression, so don't tag unrelated pull requests on the issue's title

**Comment by lumo93** [comment]
Wanted to give my input on this issue. I get the same error when using "write color buffers" and attempting to pause, but only when I also use "strict rendering mode". If I use write color buffers without strict rendering, the game continues to play, and I can pause. When using both it seems I can pause when I first load the game, but only until I enter a new area. I'm thinking this could fix the Jafar fight and Atlantica glitch where it shows you the last frame before you save the game at a save point. I'm just kinda throwing this out there at this point.

**Comment by AniLeo** [comment]
Closing as this is likely not an issue anymore and wasn't an issue without Write Color Buffers in the first place.
