### ISSUE TITLE
No DirectX on GPU Options

### ISSUE THREAD

**Issue by ZaRHD** [RPCS3/rpcs3#3733]
Hello!
I am running Windows 10 with Intel HD Graphics GPU.
In RPCS3 on GPU options I have no Direct X renderer.Only OpenGL, which I can't use because my current graphics driver supports only OpenGL 4.0 .
On the other hand,when running "dxdiag" it returns me DirectX 12, so it should (theoretically) show in RPCS3.
Am I doing something wrong, or there is something on the software side?
![dxdiag](https://user-images.githubusercontent.com/33635803/32742313-c0a4efce-c8b1-11e7-82da-779051154d53.jpg)
![rpc3](https://user-images.githubusercontent.com/33635803/32742328-c43f7f32-c8b1-11e7-81c0-967e7fd80563.jpg)

**Comment by AniLeo** [comment]
That DirectX 12 is software level, you don't have hardware support for DirectX 12 with that iGPU for sure

**Comment by ZaRHD** [comment]
Ok, so it must be supported on both hardware and software. Good to know!
Thank you!

**Comment by kd-11** [comment]
Yep. Thats an ivb chip.
