### ISSUE TITLE
Logitech F310 Gamepad not working

### ISSUE THREAD

**Issue by Propzy** [RPCS3/rpcs3#3736]
I've aready messed around with the configuration, tried the MMjoypad and everything but still nothing.

But i opened the Game The last of us, and the choose language part, it was working.. I mean, i was trying to choose the option but it was going at full speed.

Now at the "press A to download content" and it doesn't work. I'm just stuck there

**Comment by hcorion** [comment]
The Last of Us doesn't work yet. instead of MMjoypad you should be using xinput, do you have a different game where you can reproduce the same issue?

**Comment by AniLeo** [comment]
Invalid, reproduce with an actual working game.
