### ISSUE TITLE
Resize window issues when "Start in fullscreen" enabled

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3737]
In some cases the game image doesn't stretches into the full screen area staying at 1280x720 in the top left corner and black borders around. I can't track this issue's behavior, since it happens absolutely random with about 1/10 probability, - but it seems to be a Vulkan problem, because I never saw this on OGL.

My OS is Win7, video is NVidia GTX 760 Ti, if it helps somehow...

**Comment by kd-11** [comment]
Its unlikely this will be solved any time soon. Its caused by dwm not always notifying the window of changes and does happen even with regular commercial games. I have only experienced it once on rpcs3 and a few times launching a game via steam (dark souls iii).
