### ISSUE TITLE
Corrupted graphics - Hyperdimension Neptunia [BLES01178]

### ISSUE THREAD

**Issue by chandlerviolet** [RPCS3/rpcs3#3740]
Graphics are coming out weird. During Every World Screen and dungeons, there are a pattern of tiny pixels in front of the screen, the textures behind it are okay though:
![pic 1](https://user-images.githubusercontent.com/33677848/32817817-7f1ee62a-c985-11e7-9fe2-5a206ca8b824.png)
![pic8](https://user-images.githubusercontent.com/33677848/32817822-84beec10-c985-11e7-85e5-47500e594d24.png)
![pic7](https://user-images.githubusercontent.com/33677848/32817826-87e50ed8-c985-11e7-89c3-2d2481417980.png)

But in the snow dungeons, the pattern of tiny pixels disappear (By pressing the start button and going through the menu, then closing it):
![pic2](https://user-images.githubusercontent.com/33677848/32817872-c7eec168-c985-11e7-9c7c-b1350c47eeb0.png)
![pic3](https://user-images.githubusercontent.com/33677848/32817876-cdfa0694-c985-11e7-9138-914a7d146b17.png)
![pic4](https://user-images.githubusercontent.com/33677848/32817880-d30af3d2-c985-11e7-80b5-1fdf74163910.png)

During skills and transformations cutscenes the pixels disappear as well:
![pic11](https://user-images.githubusercontent.com/33677848/32818248-ad3b9e7a-c987-11e7-839f-c3d1e52b3b0c.png)
![pic6](https://user-images.githubusercontent.com/33677848/32817911-f8e0a764-c985-11e7-8b44-052ad4147247.png)

Using Vulkan makes the game much slower and makes the graphics worse, and weirdly the higher the Resolution Scale the worse the graphics get. But graphics has gone a lot better since v0.04 of RPCS3.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1473402/RPCS3.log.gz)

**RPCS3 v0.0.4-6077-9e0b881b Alpha**

**_AMD A8-7410 APU with AMD Radeon R5 Graphics  
6.94 GiB RAM 
AVX_**

**Comment by StarWolf3000** [comment]
Thats a known problem with the first Neptunia game since a lot of versions, I have these "pixels" too. It may take some time, till it gets fixed, the priority is very low.

**Comment by rekongstor** [comment]
Using rpcs3-v0.0.4-2017-12-01-3fbc960c_win64

Intel Core i7-7700 @ 3.60GHz
DDR4-2400 16 GB
AMD Radeon R7 370 Series 4 GB
Microsoft Windows 10  64-bit

Config file [config.zip](https://github.com/RPCS3/rpcs3/files/1523715/config.zip)
and log file [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1523713/RPCS3.log.gz)

The same issue but I have some results comparing to original PS3 game. Images are taken from youtube TheTwitGamer footage because I cannot capture my PS3 in proper way for now.

PS3 footage:
Looks like land menu
![image](https://user-images.githubusercontent.com/18365300/33514387-30c439e8-d764-11e7-9d5b-654a1797280b.png)
main menu
![image](https://user-images.githubusercontent.com/18365300/33514400-685b6b60-d764-11e7-8a06-09b994ed9ed0.png)
and this snow forest dungeon (like other dungeons)
![image](https://user-images.githubusercontent.com/18365300/33514379-0d268306-d764-11e7-812a-416714f4c328.png)

use the same Blur effect. When I reproduced the operation 

> But in the snow dungeons, the pattern of tiny pixels disappear (By pressing the start button and going through the menu, then closing it):

 on my PS3 - blur disappeared.

**Comment by rekongstor** [comment]
https://forums.rpcs3.net/thread-196992-post-291344.html#pid291344

> In the world map, they Disappear for 2 seconds:

Here RenderDoc captures for those frames. 1 is bugged, 2-4 are clear and 5 is bugged again.
[NepRenderDoc_dds.zip](https://github.com/RPCS3/rpcs3/files/1544919/NepRenderDoc_dds.zip)
[NepRenderDoc_log.zip](https://github.com/RPCS3/rpcs3/files/1544920/NepRenderDoc_log.zip)
And zip for .rdc files dropbox link: [NepRenderDoc_rdc.zip](https://www.dropbox.com/s/ujboz5ldo8wunmh/NepRenderDoc_rdc.zip?dl=0)

Also I have some results. 
[#5961601](https://github.com/rekongstor/rpcs3/commit/596160149c4f11f5b34add3f37584b6c2af553de)
In OpenGL disabling GL_COLOR_BUFFER_BIT in mask in <GLGSRender.cpp> 
905:		//mask |= GLenum(gl::buffers::color); 
makes grid disappear but at cost of proper textures clearing:
![1](https://user-images.githubusercontent.com/18365300/33798031-df6e1158-dd22-11e7-8303-c8c69b9f76ab.png)
![2](https://user-images.githubusercontent.com/18365300/33798032-df8eefea-dd22-11e7-9f0b-5b9f9f452497.png)
![3](https://user-images.githubusercontent.com/18365300/33798033-dfb092e4-dd22-11e7-8cb3-79c93490250f.png)

Better state with Vulcan.
[#0d1788e](https://github.com/rekongstor/rpcs3/commit/0d1788ea73b6cc61d5f6ec734468aacd80a78487)
Setting vk::get_image_subresource_range from (0,0,1,1) to (0,1,1,1) where 2nd parameter is uint32_t base_mip makes game feel better but... not:
![_1](https://user-images.githubusercontent.com/18365300/33798339-9d699214-dd27-11e7-8831-a9c9f3b7f661.png)
![_2](https://user-images.githubusercontent.com/18365300/33798340-9d86233e-dd27-11e7-8a42-d3bd5cd25852.png)
![_3](https://user-images.githubusercontent.com/18365300/33798341-9da206a8-dd27-11e7-893e-f032c15edd94.png)

Now disabling vkCmdDraw for vertex_count == 14400 (info from RenderDoc)  in <VKGSRender.cpp>
1499:	const auto vertex_count = std::get<1>(upload_info);
1500:		if (vertex_count != 14400)
1501:		vkCmdDraw(*m_current_command_buffer, vertex_count, 1, 0, 0);
game will feel much better but... still not. And #0d1788e commit is necessary!
![1_](https://user-images.githubusercontent.com/18365300/33798399-b1a3fcd2-dd28-11e7-97e3-6040f8aa3207.png)
![2_](https://user-images.githubusercontent.com/18365300/33798400-b1c4569e-dd28-11e7-9b69-4ab08c4206e3.png)
![3_](https://user-images.githubusercontent.com/18365300/33798401-b1e4faa2-dd28-11e7-9118-7cbfaa5a7259.png)

As I thought, scaling and blurring frames causes this issue but I have no idea where I should start from.

**Comment by kd-11** [comment]
No, this has nothing to do with the texturing pipeline. The game renders 14400 dots on top of the "correct" image - I'm not sure what the goal is, maybe filmgrain effect or pixel geometry correction filter. I'd need to see direct capture from a ps3 (youtube is too blurry unfortunately) to determine what the intention is. Its also likely a rasterization flag of sorts is set that should mean the points should not be rendered at all, but is not honored.

**Comment by rekongstor** [comment]
I'm not sure but I think this is for blur optimization - blurred image is blurred. Not needed to blur the whole area 1280x720, but blurring down-scaled - that's the point for optimization. 
I'll try to get capture device as soon as possible.

**Comment by kd-11** [comment]
No, the dots you see are real dots (GL_POINTS). Nothing beats a TMU at texture ops, it would make no sense to use 14400 points to simulate blurring. You can already see blurring in the other passes such as bloom filter using TMUs correctly. I dont get why you are so convinced its blurring. I've checked the pixel shader and there is no texel gathering there either. Its not used for blur.

**Comment by StarWolf3000** [comment]
@kd-11 Will #3931 be implemented for OpenGL too or do I have to install the Vulkan drivers?

**Comment by rekongstor** [comment]
@StarWolf3000 both of them

**Comment by twdarkeh** [comment]
@kd-11 https://puu.sh/yIWPq.jpg

For the first time, at least that I'm aware of, battles have backgrounds/floors/whatnot, however, the overbloom makes it hard to see much of anything. Still, amazing progress.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/3953

**Comment by twdarkeh** [comment]
![](https://puu.sh/yLlPn.jpg)

Still present.

**Comment by rodjun** [comment]
Did you delete the shader cache?

**Comment by rekongstor** [comment]
![image](https://user-images.githubusercontent.com/18365300/34276986-f7ff9642-e6b4-11e7-8d32-4235490af4d8.png)
works fine for me. shader cache cleared previously
but some issues left 
major: this appears kinda randomly but mostly on dialog skips (both renders)
![image](https://user-images.githubusercontent.com/18365300/34277050-3f1842c2-e6b5-11e7-8cd6-3469194ddd11.png)
![image](https://user-images.githubusercontent.com/18365300/34277062-52ed263c-e6b5-11e7-9a63-48d85c89b318.png)


minor: blur has to be based on depth (both renders)
![image](https://user-images.githubusercontent.com/18365300/34277122-8eacdce4-e6b5-11e7-98f3-3259600e207f.png)
![image](https://user-images.githubusercontent.com/18365300/34277148-a3f54532-e6b5-11e7-99a4-765777f25651.png)

minor: bloom issues on hammer crash (probably on other key items and chests on dungeons), OpenGL only
![image](https://user-images.githubusercontent.com/18365300/34277198-cc9e7710-e6b5-11e7-8bb7-9942cd8f9a3d.png)

**Comment by twdarkeh** [comment]
What settings are you using?

**Comment by rekongstor** [comment]
@twdarkeh default with only changing renderer. But I build rpcs3 by myself using kd-11 fork, you can try to use latest build from here https://ci.appveyor.com/project/kd-11/rpcs3

**Comment by chandlerviolet** [comment]
hmmm...everything seems fine to me, the only thing issues i see are:
- Some pics on the dialogue just as @rekongstor stated:
[https://i.imgur.com/NlNImzH.png](url) 

- There's a type of blur in the character menu:
[https://i.imgur.com/b4jor1I.png](url)
[https://i.imgur.com/CIitBzx.png](url)

But of all, everything seems to be in place!:
[https://i.imgur.com/ZQPgt9X.png](url)
[https://i.imgur.com/0U7pAb8.png](url)

**Comment by chandlerviolet** [comment]
hmmm...everything seems fine to me, the only thing issues i see are:
- Some pics on the dialogue just as @rekongstor stated:
![pic 1](https://i.imgur.com/NlNImzH.png)

- There's a type of blur in the character menu:
![pic 2](https://i.imgur.com/b4jor1I.png)
![pic 3](https://i.imgur.com/CIitBzx.png)

But of all, everything seems to be in place!:
![pic 4](https://i.imgur.com/ZQPgt9X.png)
![pic 5](https://i.imgur.com/0U7pAb8.png)

**Comment by twdarkeh** [comment]
Strange. Even when running from a fresh rpcs3 install, it still is a white screen on Vulkan for me. OGL is graphically perfect though.

**Comment by greentop** [comment]
The blooming is more intense on Vulkan (Nvidia) in the latest pr. 
![screenshot from 2017-12-22 00-55-49](https://user-images.githubusercontent.com/2325766/34287311-787c0a5e-e6b4-11e7-8a28-7f2d873d8cb2.png)

**Comment by chandlerviolet** [comment]
@twdarkeh This game runs weirdly, apparently the higher the graphic settings, the worse the textures/graphics get. For now the best option is to use OpenGL when playing this game....

**Comment by StarWolf3000** [comment]
Runs fine for me now with OpenGL. Had some sporadic crashes, but deleting trophyusr.dat and let it generate again fixed the error messages that occured on my installation. For some reason the file was just 112 Bytes instead of about 10 KiB.

**Comment by kd-11** [comment]
@twdarkeh @greentop Retry with newer PR build. I'd forgotten to clear some memory and it may have contained garbage.

**Comment by twdarkeh** [comment]
![](https://puu.sh/yLG47.png)

It is fixed now.

**Comment by twdarkeh** [comment]
![]http://puu.sh/yLG8y.jpg

Seems to be fixed now, yes.

**Comment by greentop** [comment]
The blooming in Vulkan is fixed as of 9e3ed27
![screenshot from 2017-12-22 05-08-10](https://user-images.githubusercontent.com/2325766/34294546-fd76d280-e6d6-11e7-87b9-e1e83d644f33.png)
![screenshot from 2017-12-22 05-09-17](https://user-images.githubusercontent.com/2325766/34294559-05765776-e6d7-11e7-84e6-04512971194d.png)

**Comment by StarWolf3000** [comment]
I guess this can be closed now, almost all graphical problems seem now solved for this game.

**Comment by chandlerviolet** [comment]
Yes, the only graphic problem i see is the blur, but other than that everything is all good. Thank you very much for everyone that helped make this game working and playable. ❤
