### ISSUE TITLE
Savedata: Select Entry saving not working [BLUS31597]

### ISSUE THREAD

**Issue by greentop** [RPCS3/rpcs3#3747]
**Ubuntu 16.04 / Nvidia 387.12 / LLVM 4 / (RPCS3 Master as of 223f17a)**

**RPCS3 GPU Additional Settings:**
Enabled - Vulkan / Use GPU Texture Scaling / 16xAF

**Game:** ToCS2 BLUS31597

**Regression:** When using the "Save Data Interface" to save the current game progress with the "Select Entry" option to save over an existing save slot, the game progress is not saved, and no "Saving System Data..." game message is displayed.

**Workaround:** The "Save New Entry" button option will allow the current game progress to be saved successfully. 

[RPCS3_Master_223f17a.log.gz](https://github.com/RPCS3/rpcs3/files/1481026/RPCS3_Master_223f17a.log.gz)

**Comment by LuismaSP89** [comment]
@greentop Sorry to bother you, but i think i have the same problem. Could you tell me where is that "Save new entry button" ?  When i go to "Manage>save data" and open the save manager, only two buttons show to me "Delete selection" and "Close".

Thanks in advance!

**Comment by greentop** [comment]
The "Save New Entry" button is available while doing a normal in-game save. For ToCS2, the Start button when pressed while within the Camp Menu will popup the following "Save Data Interface" window:

![screenshot from 2017-11-26 22-06-19](https://user-images.githubusercontent.com/2325766/33249254-9088a63c-d2f7-11e7-9cff-eb87e37a21b1.png)

**Comment by LuismaSP89** [comment]
@greentop Ok, what a shame, my game has autosave function and pop ups nothing. Btw thanks for your answer : )

**Comment by greentop** [comment]
Closing issue now that PR #3918 has been merged into Master. (Fix confirmed.)
