### ISSUE TITLE
sys_fs_fstat doesn't work on folders

### ISSUE THREAD

**Issue by Farseer2** [RPCS3/rpcs3#3748]
Spotted by @clienthax when testing a vsh build - when using fstat on a folder file descriptor, EBADF is returned (only lv2_file is fetched, not lv2_dir).
Example output:

```
·W 0:00:05.845717 {PPU[0x1000028] Thread (ScePafJob) [0x00aab504]} sys_fs: sys_fs_opendir(path=“/dev_hdd0”, fd=*0x20800224)
·E 0:00:05.845800 {PPU[0x1000028] Thread (ScePafJob) [0x00aab504]} sys_fs: sys_fs_opendir(): fd = 19
·W 0:00:05.845804 {PPU[0x1000028] Thread (ScePafJob) [0x00aad020]} sys_fs: sys_fs_fstat(fd=19, sb=*0xd0294ef8)
·E 0:00:05.845807 {PPU[0x1000028] Thread (ScePafJob) [0x00aad020]} 'sys_fs_fstat' failed with 0x8001002a : CELL_EBADF [1]
```

**Comment by clienthax** [comment]
Ran some tests on the decr.. oddly this seems to be correct

sys_fs_open /dev_hdd0 ffffffff80010012 fd=-2
sys_fs_opendir /dev_hdd0 0 fd=3
sys_fs_fstat /dev_hdd0 ffffffff8001002a fd=3
