### ISSUE TITLE
BLES01446 dont load

### ISSUE THREAD

**Issue by jonaand** [RPCS3/rpcs3#3750]
hello
when try load this game said
E CFG: cfg::try_to_enum_value('16x9'): unexpected characters (pos=2)
E CFG: cfg::try_to_enum_value('16x9'): unexpected characters (pos=2)
E LDR: Failed to mount disc directory for the disc game BLES01446

what can i do
thanks

**Comment by Zangetsu38** [comment]
Silent Hill Downpour works for me

**Comment by Zangetsu38** [comment]
i have Euro version, so i no understund your problem here, and other user have works same think

**Comment by jonaand** [comment]
i've downloaded game again and dont wanna load
usa version yes load but is not playlable

**Comment by jonaand** [comment]
was easy
the EUR version i've been downloaded doesn't have
PS3_DISC.SFB file
so i've download USA version and just copy these file of USA in EUR
and now work!!

**Comment by jonaand** [comment]
now after the intro of the game, after the car crash in the way
the image still in black, if i press start i see the menu option for change
but without start all is in black
what options do you use for emulation?

**Comment by Asinin3** [comment]
This is not the place to ask for support especially bad pirated copies.... not an issue with the emulator. Didn't you see the links to https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md before posting?

**Comment by jonaand** [comment]
yes THIS is the place
i wish you  and your family DIE
go to hell
piece of jerk

**Comment by MoochMcGee** [comment]
are you stupid? lmao

**Comment by jonaand** [comment]
not
all you are stupid people dont enjoy piracy
game
go to hell, i wish all you die  SOON SOON

**Comment by MoochMcGee** [comment]
@jonaand piracy is illegal lmao, so is threatening people like that.

**Comment by AniLeo** [comment]
What kind of cancer meme is this
