### ISSUE TITLE
Vulkan renderer option don't show with NVIDIA QUADRO 2000

### ISSUE THREAD

**Issue by daviaws** [RPCS3/rpcs3#3755]
I'm sure the QUADRO 2000 achieves the minimum requisites.

I'm in Windows 10 (64bits) with a NVIDIA Quadro 2000 GPU, a I7 Xeon processor and 16GB ram.
My drivers are up to date and I downloaded the last build 0.0.4-6902.

But the render option just show "null / OpenGl / D3D12[DO NOT USE]".

I don't think I'm missing something.
I'm googling the problem, and don't see anybody else talking about it.
All youtube videos shows Vulkan option from a fresh download... so, I opted to open this issue.

I'm anexing the logs.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1485339/RPCS3.log.gz)

**Comment by Gamedev1909** [comment]
That gpu doesn’t have vulkan support from what I’ve read sorry man

**Comment by Asinin3** [comment]
![image](https://user-images.githubusercontent.com/15137035/32988221-8d7c9514-cd4f-11e7-8181-b824be255395.png)

**Comment by daviaws** [comment]
Yes, it does :)
Already searched for that, as @Asinin3 already quoted.

**Comment by Gamedev1909** [comment]
Then email nvidia and get a driver fix so far not seen vulkan working yet on one of these not even in Linux

**Comment by daviaws** [comment]
https://github.com/skeeto/vulkan-test

With this software I got this result:
![image](https://user-images.githubusercontent.com/12686471/32988345-94f2f308-cce9-11e7-8bf6-9a9af651bdf6.png)

I'll try to run a benchmark and post the results :)

**Comment by daviaws** [comment]
https://github.com/skeeto/vulkan-test

With this software I got a positive result: "Successfully created a Vulkan instance."
Although it don't show in a PrintScreen, dunno why.

I'll try to run a benchmark and post the results.
But I don't think the problem is in NVIDIA driver or infos, though.

**Comment by Gamedev1909** [comment]
Go grab the doom 2016 Demo and try vulkan most of the time older nvidia cards have issues with vulkan and dx12

**Comment by daviaws** [comment]
So... are you saying I won't get support for a feature that by definition I achieve the minimum specification?

Cause even if I could have issues running it, don't mean I can't enable it.

So, I don't got your point.

Think I'll need to hack the code and learn what's up then.

**Comment by Asinin3** [comment]
It's an rpcs3 issue, it thinks the card doesn't have vulkan support. I remember it happening to another card...

**Comment by Megamouse** [comment]
try to debug VKHelpers.h line 1276 and onwards to see where exactly it fails.
obviously the vector "gpus" should contain at least one entry to show the Vulkan Renderer Option

**Comment by Megamouse** [comment]
maybe we need to update Vulkan on our end? Need to wait for KD-11 to look at it

**Comment by Gamedev1909** [comment]
Update vulkan to 1.0.65.0 ? 
Has any other old 2011 cards had issues like this I mean his card isn’t very powerful either

**Comment by kd-11** [comment]
We use the khronos loader to load the vulkan driver. I recently updated the loader we use too. If vulkan isn't showing up then the loader cannot find the driver for some reason. Alot of times reinstalling the drivers helps as does installing the vulkan runtime library (vulkanRT) which is needed. This is one of those support issues that really should be on discord and not here.

**Comment by kd-11** [comment]
Scratch that, Quadro 2000 is a fermi chip. Vulkan drivers for fermi never shipped and it was dropped by nvidia for "low install base" reasons. The D3D12 driver came out this year (an earlier version had already leaked online a year before) but they categorically stated that vulkan support was abandoned.

Direct quote:
>“We are currently not planning to support for 4-5 (Fermi) class GPUs. It is not an engineering issue, it’s an install base issue. So if that causes you pain, please contact your local NVIDIA representative and let me know.”

**Comment by Asinin3** [comment]
Strange that it's still listed on the developer Nvidia page as having Vulkan support, maybe the developer drivers work?

**Comment by Gamedev1909** [comment]
Well from what I’ve seen nvidia is a mess when it comes to cards like some 600 cards being femi based and even some 700 so maybe he has the femi and not the Kepler model it happens all the time

**Comment by kd-11** [comment]
Vulkan and DX12 were announced a long time before they were actually released and back then fermi was still newish. This was kepler era so fermi being only one generation removed meant it was planned to be supported. Later on they dropped support for fermi, but users were angry about DX12 support being dropped and a beta driver with DX12 support leaked online. It was buggy and slow but it proved that they had drivers and just abandoned them. This year after a windows version update, they stealthily re-enabled fermi DX12 but no vulkan. The material on the site is promotional and often times doesnt get updated when roadmap changes like in this case. Hell, the overview clearly mentions that Quadro 2000 is a fermi card but then mention vulkan when listing API support. It likely went unnoticed now that fermi is 7+ years old.

**Comment by daviaws** [comment]
@kd-11, @Gamedev1909 

Seems I lost this one. Sorry for the mess opening this issue.
