### ISSUE TITLE
MacOS build Error

### ISSUE THREAD

**Issue by sergds** [RPCS3/rpcs3#3756]
log:[macos_try.txt](https://github.com/RPCS3/rpcs3/files/1485595/macos_try.txt)

OS: MacOS High Sierra 10.13.1
XCode: Version 9.1 (9B55)
Command line tools version: 9.1
cmake version 3.9.6
LLVM version 5.0.0

Config command: `cmake ../rpcs3 -DUSE_SYSTEM_FFMPEG=ON`
Environment Variables : 
`Qt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5`
`LLVM_DIR=/usr/local/opt/llvm/bin`

**Comment by elad335** [comment]
Mac is not supported because it doesn't support OpenGL.
