### ISSUE TITLE
BLUS30947 

### ISSUE THREAD

**Issue by joaozin23** [RPCS3/rpcs3#3762]

**Comment by joaozin23** [comment]
![esboco](https://user-images.githubusercontent.com/17303493/32997393-acd8d8ce-cd76-11e7-8bbc-23eeec6a3ab6.png)
![esboco 1](https://user-images.githubusercontent.com/17303493/32997394-acfbea76-cd76-11e7-9795-3c26c8959236.png)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
