### ISSUE TITLE
Missing (cropped) text when upscaling Tekken 6 [BLES00635]

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#3769]
rpcs3-v0.0.4-2017-11-20-380f90b-8873_linux64
Mesa 17.2, r9 fury, OpenGl and Vulkan.
When upscaling, there are some missing (=cropped) texts. It seems like there's a black box at the bottom. The higher the resolution, the bigger this box.
Native (strict rendering):
![fps 59 95 opengl 0 0 4-50 tekken 6 bles00635 _023](https://user-images.githubusercontent.com/7478580/33058828-c7a8f0e6-ce91-11e7-95ec-dcc1fe833091.jpg)
1080p:
![fps 59 90 opengl 0 0 4-50 tekken 6 bles00635 _027](https://user-images.githubusercontent.com/7478580/33058836-d7b8718c-ce91-11e7-8a0f-aed770b7c90b.jpg)
4k:
![fps 59 88 opengl 0 0 4-50 tekken 6 bles00635 _025](https://user-images.githubusercontent.com/7478580/33058850-e54dba5a-ce91-11e7-8a4b-4997eda8df5a.jpg)
Another scene:
Native:
![fps 57 38 opengl 0 0 4-50 tekken 6 bles00635 _024](https://user-images.githubusercontent.com/7478580/33058859-fac7ef22-ce91-11e7-952e-f4583e673fde.jpg)
1080p:
![fps 56 07 opengl 0 0 4-50 tekken 6 bles00635 _028](https://user-images.githubusercontent.com/7478580/33058869-0731c594-ce92-11e7-9fee-73467a8e4982.jpg)
4k:
![fps 23 98 opengl 0 0 4-50 tekken 6 bles00635 _026](https://user-images.githubusercontent.com/7478580/33058881-14140d80-ce92-11e7-90ce-0a40af1dc13f.jpg)
And the log files:
[RPCS3.log-Tekken6-StrictMode.gz](https://github.com/RPCS3/rpcs3/files/1490327/RPCS3.log-Tekken6-StrictMode.gz)
[RPCS3.log-Tekken6-Upscaled.gz](https://github.com/RPCS3/rpcs3/files/1490328/RPCS3.log-Tekken6-Upscaled.gz)

**Comment by kd-11** [comment]
Set scalinh threshold to 1x1 and see if it helps

**Comment by toccata10** [comment]
This solves the pb. The threshold is about 20x20. Above this value, it starts cropping some texts. I wonder if a lower value has a performance hit (didn't seem to be the case).

**Comment by kd-11** [comment]
Its a calibration value and doesnt affect performance. Some types of images should never br scaled but I think the default should be lowered to 16x16 to avoid such issues

**Comment by toccata10** [comment]
I tested a few games from my library. I couldn't see any negative impact of lowering to 16x16, so it's probably worth setting this as the default value.
