### ISSUE TITLE
Adding date/time of unlocking trophies

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3777]
Hello, could you add date/time of unlocking to Trophy Manager?

**Comment by Megamouse** [comment]
I think timestamps are only added while connected to psn on real hardware

**Comment by Vahkiti** [comment]
> I think timestamps are only added while connected to psn on real hardware

Well if that's the case they should still be logged to a separate file or something just for user convenience. As mentioned in the above apparent duplicate issue, some people may want to manually copy that data to original hardware which IS possible to do with timestamps via PS3TrophyIsGood.

**Comment by jhonathanc** [comment]
As @MSuih suggested, there is already some code to write timestamps to trophies, but it's always filling it with "0".

https://github.com/RPCS3/rpcs3/issues/10254#issuecomment-835179669

About it, is there anyway to set internal RTC clock of RPCS3 (if it exists) to use the system clock? If so, RPCS3 could use that to fill the correct timestamp.

**Comment by Vahkiti** [comment]
It's just a shame that between this and the missing header, it's so close, but otherwise generates a partially invalid file. I've also found that IMPORTING a real trophy list will actually be read initially, but entirely wiped the moment an in-game trophy trigger is hit. Not sure if it's related to this or the header, but it's still an issue.

**Comment by marcoluc97** [comment]
@RipleyTom do you think RPCN can help here? Or is it something else as said in:
https://github.com/RPCS3/rpcs3/issues/10254#issuecomment-835179669

**Comment by RipleyTom** [comment]
Technically trophies are stored on PSN but it's not a functionality I plan to implement.

**Comment by marcoluc97** [comment]
Thanks for the reply. @Megamouse do you think is possible to "fix" it locally (in the TODO left) or is still needed XMB?

**Comment by Megamouse** [comment]
@RobbedColek can you compare the output of #13867 with your reference data?

**Comment by RobbedColek** [comment]
Sorry for late response, I rarely get on Github.

I'll take a look at it in next few days.

**Comment by Megamouse** [comment]
@RobbedColek it should be fine now in the PR.
I only wondered if the values written to file match the values that you'd expect (microseconds since ...).

**Comment by RobbedColek** [comment]
@Megamouse looks all fine to me, thank you for working on this!
