### ISSUE TITLE
Required Fedora Packages changes

### ISSUE THREAD

**Issue by Gamedev1909** [RPCS3/rpcs3#3779]
For fedora 27

systemd-devel needs to be added on github as required stuff for compiling same with gcc-c++ and 
qt-devel cmake 

without these we get errors like 
No CMAKE_CXX_COMPILER could be found

just somethings ive noticed 

http://rpmfind.net/linux/fedora/linux/updates/27/x86_64/Packages/s/systemd-devel-234-9.fc27.x86_64.rpm is needed also and libatomic

**Comment by hcorion** [comment]
err, what? gcc/clang is already mentioned as a requirement, 
> Linux
> 
> - Qt 5.7+
> - GCC 5.1+ or Clang 3.5.0+ (not GCC 6.1)

qt5-devel is mentioned in the fedora installation instructions?
I'm not sure why systemd-devel is needed? What happens when you compile without it?

**Comment by Gamedev1909** [comment]
error after error fedora 27 might be a no go for now for most

**Comment by scribam** [comment]
Does it help if you run `sudo dnf install libatomic libudev-devel`?

`libudev-devel` is an alias for `systemd-devel` which adds the header file `libudev.h`, necessary for hidapi.

**Comment by Gamedev1909** [comment]
I don’t think people are getting what I’m saying sadly changed in fedora 27 means a few things where left out that 26 does have. It’s not that hard to get is it .... even the install iso is smaller and yes qt had a error so did libdev. Was just trying to be helpful I will try again on a vm and show all the errors as they came

**Comment by Gamedev1909** [comment]
sudo dnf install libatomic libudev-devel gcc-c++ cmake qt5-devel vulkan-devel glew glew-devel and thats  it i just did a video on a new vm with the errors i will post it soon after i edit it out

**Comment by Gamedev1909** [comment]
https://youtu.be/lCNRvya965E

**Comment by scribam** [comment]
Thank you for the video, I made a PR to add the missing packages: `libatomic`, `libudev-devel` and `openal-devel`. `gcc-c++` is not in the list as the README file explicitly mentions the compiler requirements:
> GCC 5.1+ or Clang 3.5.0+ (not GCC 6.1)

Let me know if it is an issue for you.

**Comment by AniLeo** [comment]
Already solved, closing. Reopen if it's still an issue
