### ISSUE TITLE
Some games return error 18 on rename, if files are on a different device

### ISSUE THREAD

**Issue by hcorion** [RPCS3/rpcs3#3781]
Games I've found: Uncharted 2, Ninja Gaiden Sigma 2.

The error occurs in `cellGameContentPermit` at
https://github.com/RPCS3/rpcs3/blob/3628a8593facb4b32eb1ae728878fd9f00c52419/rpcs3/Emu/Cell/Modules/cellGame.cpp#L396-L399

because I have dev_hdd0 on a different drive (to save space on my SSD).

**Comment by hcorion** [comment]
I was able to fix this by doing 
changing
https://github.com/RPCS3/rpcs3/blob/e77d5cf970c03a9e3d2e8c82bf739cb4d1f157a8/Utilities/File.cpp#L573-L574
to
```cpp
		if (errno == EXDEV)
		{
			std::experimental::filesystem::copy(from, to, std::experimental::filesystem::copy_options::recursive);
		}
		else
		{
			g_tls_error = to_error(errno);
			return false;
		}
```

but of course, this is not a good fix because of the experimental status of std::filesystem.

**Comment by Nekotekina** [comment]
Hmm, shouldn't be a problem anymore, because everything now happens within dev_hdd0.
