### ISSUE TITLE
Arabic lang

### ISSUE THREAD

**Issue by Omaranwa** [RPCS3/rpcs3#3782]
its this program support this lang
and if it supportedm, how can i add it.
thanks

**Comment by AniLeo** [comment]
RPCS3 doesn't support non-english languages itself nor are we planning to do so in the short term.
Changing the console language in settings is doable, but that only affects games and PS3 system messages.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by elad335** [comment]
no other language other than english is Implemented at the moment

**Comment by Omaranwa** [comment]
ok thanks for fast replay
