### ISSUE TITLE
Size of config windows is too big in linux.

### ISSUE THREAD

**Issue by latot** [RPCS3/rpcs3#3786]
Hi all, well this don't happen in windows, but in linux the size of the winfows for config is very big, i can't see the topbar or the buttons for save and close...

This is my full window, (imp pant):

![captura de pantalla de 2017-11-26 04-14-29](https://user-images.githubusercontent.com/10523095/33237930-95dcd8ac-d260-11e7-8898-6e79e8e21b92.png)

Note: I'm running without my nvidia card (because with it i can't run the app, there is other issue for that)

Thx. Cya.

**Comment by Megamouse** [comment]
maybe you should buy a bigger screen. looks like you are running on less than 1280×720.
(please state your resolution etc. is  what i mean)

**Comment by latot** [comment]
mm, i'm running in a notebook:

Size: 14''
Aspect: 16:9
Resolution: 1366x768 (16:9)

Thx.

**Comment by Megamouse** [comment]
I have ubuntu in 1280x720 and even then I see more of the window.
maybe you have it zoomed in or sth like that?

**Comment by latot** [comment]
Hi, i don't have zoomed, and what you mean with sth?

Thx.

**Comment by latot** [comment]
Only in case, i'm running a Gentoo64 system

**Comment by Gamedev1909** [comment]
On fedora and arch the windows are to big I agree

**Comment by Megamouse** [comment]
~~move to better OS~~

**Comment by latot** [comment]
:cry:

**Comment by cybertronicgames** [comment]
Try configuring your UI in Linux.

**Comment by Gamedev1909** [comment]
gnome has a auto gui scaler but it seems rpcs3 doesnt follow that

**Comment by nhydock** [comment]
maybe the settings can be redesigned using QML and allow for scrolling and configuration on even a 10ft display, like retroarch.

**Comment by Megamouse** [comment]
try my new PR. I made the dialog more widescreen friendly

**Comment by greentop** [comment]
The line spacing and font size is larger in his OS when compared to mine on Ubuntu 16.04.
![screenshot from 2017-11-26 16-03-54](https://user-images.githubusercontent.com/2325766/33244413-b9a05a66-d2c4-11e7-866e-4e30b2c015f2.png)

**Comment by clessley** [comment]
I see both huge configuration fonts (like input windows) but "0 sized" fonts in most other places that are unreadable/unusable on Ubuntu MATE 17.10. Setting both qt4 and qt5 configs (GTK+ or default) does not help. Some areas, like the log can be zoomed in with the mouse but not anywhere else. It is unusable at this time.

**Comment by cybertronicgames** [comment]
@latot They fixed the setting window for you! So, awesome!
![screenshot 44](https://user-images.githubusercontent.com/14711758/33283210-bc320656-d370-11e7-975d-e382daaa1bf1.jpg)

**Comment by AniLeo** [comment]
Fixed on the latest build, closing the issue.
Feel free to reopen if it's still somehow a problem.

**Comment by latot** [comment]
Thx All :smile:

**Comment by latot** [comment]
@clessley is working all of this for you?

**Comment by clessley** [comment]
@latot Font sizing ok now but the menu icons are now huge and some windows still go off screen such as the controller input mapping window. A lot of alt-F7 is needed to use the GUI outside of a game but the game play itself is fine (was before also). Machine using proprietary Nvidia drivers. The card itself is GeForce GTX 760 2GB TWIN FROZR video card.

Another machine using the same theme and OS+version but with an AMD card with open source drivers looks perfectly fine(?).

I can post images a bit later tonight (11-30-2017) of the issue.

**Comment by poVoq** [comment]
On Linux at 1920x1080 the gamepad config screen is also cut off at the bottom. I guess that is where the save/apply button is?

**Comment by bscubed** [comment]
Also having the same issue as ghost, also with proprietary Nvidia drivers.
```
OS: Arch Linux x86_64
Kernel: 5.0.9-arch1-1-ARCH 
Resolution: 1920x1080 
DE: Budgie 
WM: Mutter(Budgie) 
CPU: AMD FX-8320 (8) @ 3.500GHz 
GPU: NVIDIA GeForce GTX 970 
Memory: 1448MiB / 7870MiB 
```

**Comment by SilverMight** [comment]
Also experiencing the same issue
