### ISSUE TITLE
 Invalid FIFO queue get/put registers found, get=0x1F800000, put=0x8AA2C

### ISSUE THREAD

**Issue by SparrowYT** [RPCS3/rpcs3#3790]
<!---

hi im new to this site but i've got a problem with my ps3 emulator when i try to run persona 5.
it says: 
E {rsx::thread} HLE: Getting the real address failed. (addr=0x1f800000)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1F800000, put=0x8AA2C
 if anyone can help me please, i really want to play that game

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
