### ISSUE TITLE
[BLES00932] [Linux] [AMD] Vulkan/OpenGL primitive restart hang

### ISSUE THREAD

**Issue by itzexor** [RPCS3/rpcs3#3792]
Hello there, you have recently fixed this bug for Windows and enabled it for Linux, but the device strings do not match. I built git master yesterday and replaced "RX 470" and "RX 480" with "RADV" and "POLARIS10" respectively and this does fix the issue in Demons Souls tutorial on Vulkan.

Adding the RADV device names to the quirk isn't that big of a deal honestly, but I figured I'd report this as I believe you said there aren't enough Linux testers to add them in the PR.

The real reason I opened this issue is to report that the same exact system hang exists in opengl and I'm wondering if I missed a second quirk definition for the opengl path, or is this a separate issue with the same exact symptoms?

I haven't been able to get any log info for either hang as the RPCS3 log usually becomes corrupted when I force restart, and nothing is ever printed to syslog/stdout regarding the GPU hang.

Thanks for your time.

OS: Arch
GPU: AMD RX 480
Driver: Mesa 17.4-dev
Vulkan GPU ID String: "AMD RADV POLARIS10"
OpenGL Renderer String: "AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.18.0 / 4.13.12-1-ARCH, LLVM 6.0.0)"

**Comment by itzexor** [comment]
Update: I removed the replacement hack and instead added just "POLARIS10" and increased the count to 9. This way I'm sure "POLARIS10" is enough to enable the quirk for RX 480 on RADV.

```
diff --git a/rpcs3/Emu/RSX/VK/VKHelpers.cpp b/rpcs3/Emu/RSX/VK/VKHelpers.cpp
index ebb89b93..76d0d07c 100644
--- a/rpcs3/Emu/RSX/VK/VKHelpers.cpp
+++ b/rpcs3/Emu/RSX/VK/VKHelpers.cpp
@@ -259,7 +259,7 @@ namespace vk
 	{
 		g_current_renderer = device;
 
-		const std::array<std::string, 8> black_listed = 
+		const std::array<std::string, 9> black_listed =
 		{
 			// Black list all polaris unless its proven they dont have a problem with primitive restart
 			"RX 580",
@@ -270,6 +270,7 @@ namespace vk
 			"RX 470",
 			"RX 460",
 			"RX Vega",
+			"POLARIS10",
 		};
 
 		const auto gpu_name = g_current_renderer.gpu().name();
```

**Comment by AniLeo** [comment]
Mesa fixed this upstream?

**Comment by itzexor** [comment]
No idea but I can't test this anymore so no point leaving it open.

**Comment by sibradzic** [comment]
@AniLeo @kd-11 @itzexor this still hits Linux (Mesa 18.0.0) with both Vulkan RADV & Mesa OpenGL, 100% reproducible in Demon's Souls (blocking tutorial when you reach the end of the "tunnel", seeing other mob with a torch), tested on both 6694-25ec899c & git master.

I could push a PR that takes care of adding all known POLARIS / VEGA into a black_listed quirk (tested against master on my RX570, fixes the hang), but that only fixes Vukan RADV. I tried to locate a similar OpenGL quirk in the code, but couldn't find any, any clues?
