### ISSUE TITLE
PS2 Controller not working in this build . it's works on 0.0.4-7049

### ISSUE THREAD

**Issue by ps2player** [RPCS3/rpcs3#3794]

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
