### ISSUE TITLE
Xinput remapping problems after #3611

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#3795]
oops, that shouldn't have happened

![1](https://user-images.githubusercontent.com/6324523/33302143-9ae66c3c-d413-11e7-9d17-0ac47e10e842.png)

This is not actually a regression, this misconfugyration was introduced in PR, i guess

**Comment by Megamouse** [comment]
should be fixed now.
reopen when another Xinput "regression" pops up

**Comment by isshininu** [comment]
Thank you!

works like a charm
