### ISSUE TITLE
No Audio in "The Unfinished Swan" [NPUA98202]

### ISSUE THREAD

**Issue by Nikorasu95** [RPCS3/rpcs3#3798]
I'm using 0.0.4-6142. I tried different troubleshooting steps trying the different PPU and SPU decoder modes, as well as the different "Additional Settings". I also of course changed the Audio backend from XAudio2 to OpenAl and tried Convert to 16-bit and downmix to Stereo, but still nothing. I also tried all the GPU backends including the DX12[DO NOT USE] all of this troubleshooting didn't make the audio work. The game works perfectly with stable 60fps and should be considered fully playable with no graphic glitches or crashes. Only problem is no audio. Only way to enjoy the game is with the music playing. One could go on youtube and play the OST while playing the game but that's not the point.
My specs is:
CPU: i7 4790K @4.7Ghz
GPU: GTX 1050Ti
RAM: 16Gb DDR3 @ 2400Mhz
OS: Windows 10 Pro x64 falls creator update.

**Comment by hyperspeedgx** [comment]
Others games that are without audio are God of War 1&2 from the HD collection and Ninja Gaiden Sigma 1.

**Comment by hyperspeedgx** [comment]
Audio is fixed on God of War 1&2 now, unfortunate no changes on Ninja Gaiden Sigma though.

**Comment by Nikorasu95** [comment]
Audio is fixed in "The Unfinished Swan" thanks to the new update that released today.

**Comment by AniLeo** [comment]
Closing as audio is working.
Audio lagging is an completely unrelated issue, mostly due to slow emulation.
