### ISSUE TITLE
Keyboard: Space and Tab buttons are not mappable now

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3801]
After new input behavior I can't bind these buttons to controls because **Tab** is just switching between active elements, and **Space** press "Restore defaults" button. There are also issues with **Left arrow** button - it starts selecting action buttons first, and then only does binding. I think the controls dialog needs default input force freezing during timer goes!

Also, still didn't solved #3452, and with Cyrillic layout by default I get "Ф" instead of "A" etc.

Windows 7 x64, latest Master build.

**Comment by Megamouse** [comment]
try this

https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7067/artifacts

**Comment by Psycho-A** [comment]
@Megamouse, Tab and space works nice for now!

**Comment by Megamouse** [comment]
What about the left arrow

**Comment by Psycho-A** [comment]
@Megamouse, Left arrow works fine now too :)
