### ISSUE TITLE
[BLJM60223] invalid name when first play

### ISSUE THREAD

**Issue by Oky12** [RPCS3/rpcs3#3804]
![screenshot 68](https://user-images.githubusercontent.com/30838114/33378229-bc5e9fb8-d546-11e7-949b-566924c18731.png)
![screenshot 69](https://user-images.githubusercontent.com/30838114/33378232-bcc0387c-d546-11e7-865a-4c3b7c456d54.png)
i try anything name but still invalid....
i am using Rpcs3 0.0.4-6147-a4de4950 alpha

**Comment by SakataGintokiYT** [comment]
@Oky12 
You need to write a name in Japanese.
