### ISSUE TITLE
Castlevania:Lords of Shadow 2[BLUS30999]

### ISSUE THREAD

**Issue by joaozin23** [RPCS3/rpcs3#3810]
![esboco 14](https://user-images.githubusercontent.com/17303493/33405225-b0303654-d54e-11e7-8fad-5fb4eef0b76b.png)
![esboco 11](https://user-images.githubusercontent.com/17303493/33405226-b050c612-d54e-11e7-9ec9-ef092c1d7d33.png)
![esboco 12](https://user-images.githubusercontent.com/17303493/33405227-b06dfab6-d54e-11e7-9a60-8ebc67f1c9aa.png)
![esboco 13](https://user-images.githubusercontent.com/17303493/33405228-b08b6a42-d54e-11e7-979a-358f21942a50.png)

**Comment by joaozin23** [comment]
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7079

**Comment by joaozin23** [comment]
Vulkan api not rederiza game

**Comment by AniLeo** [comment]
Same here, this is not the forums. Reporting games status must be there.

This is an issue tracker for proper reports on what's wrong or at least sufficient information for a dev to find out.
