### ISSUE TITLE
 Sherk Forever After[BLES00837]

### ISSUE THREAD

**Issue by joaozin23** [RPCS3/rpcs3#3811]

**Comment by joaozin23** [comment]
![esboco 7](https://user-images.githubusercontent.com/17303493/33405382-41f5cbda-d54f-11e7-95d1-71edfa8145fa.png)
![esboco 6](https://user-images.githubusercontent.com/17303493/33405383-421ab5a8-d54f-11e7-8d5b-f33b3a41a018.png)

**Comment by joaozin23** [comment]
giclée grafics framas very low

**Comment by AniLeo** [comment]
This is not the forums
