### ISSUE TITLE
Emulator crushes Ni No Kuni: Wrath of the White Witch [NPUB30932]

### ISSUE THREAD

**Issue by vasiliyaltunin** [RPCS3/rpcs3#3812]
RPCS3 v0.0.4-6149-ae643135 Alpha | HEAD
Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz | 4 Threads | 7.97 GiB RAM | AVX+

It may happens anytime in game process, and sometimes when i run game second time, if i close it before

here error:

![crash2](https://user-images.githubusercontent.com/417082/33423562-558b017e-d60d-11e7-8ba1-5523bfc86a95.png)

also another one happens and i post about it [here](https://forums.rpcs3.net/thread-196848-post-292433.html#pid292433)

I upload log here https://yadi.sk/d/kdm_-Owb3Q6pkT - 301117- v0.0.4-7083-ae64313-vulcan-log-1.7z

**Comment by paulsapps** [comment]
CRUSHED

**Comment by vasiliyaltunin** [comment]
RPCS3 v0.0.4-6269-58d8d126 Alpha | HEAD
Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz | 4 Threads | 7.97 GiB RAM | AVX+

similar error with opengl 

![2017-12-23_10-24-25](https://user-images.githubusercontent.com/417082/34314829-0618c51a-e7cc-11e7-8186-c73e1d3c6912.png)

[231217- v0.0.4-6269-58d8d126-opengl-log-1.zip](https://github.com/RPCS3/rpcs3/files/1583673/231217-.v0.0.4-6269-58d8d126-opengl-log-1.zip)

**Comment by kd-11** [comment]
Is this still an issue?

**Comment by vasiliyaltunin** [comment]
No, it just stuck just before movie may start and did not show any usefull info in logs.
