### ISSUE TITLE
Possibility about porting rpcs3 to macOS via MoltenVK

### ISSUE THREAD

**Issue by CNAmira** [RPCS3/rpcs3#3813]
While there ain't an official support of Vulkan on macOS, but someone have developed a framework named [MoltenVK](https://moltengl.com/moltenvk/) that make it possible to run Vulkan apps on macOS without change any codes.
Some famous gaming libraries such as SDL, GLFW and LWJGL have accept it as a Vulkan implementation on macOS.
How about to run RPCS3 on macOS via MoltenVK?

**Comment by elad335** [comment]
If it works why not

**Comment by HenningJW** [comment]
Not possible as of now because of the license of MoltenVK. Once they switch to an open source (/GPL) compatible license this will be possible.

**Comment by CNAmira** [comment]
While it may cause some legal issues, but it should not be a problem if this project only provides source codes and compile scripts but not binary distributions.
