### ISSUE TITLE
Skyrim -Failed to compile vertex shader VKVertexProgram.cpp:345 during gameplay

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#3815]
Hello,
Skyrim with Vulkan can be now played, but i first location - during excape from starting location i have made this error:

F {rsx::thread} class std::runtime_error thrown: Failed to compile vertex shader
(in file Emu\RSX\VK\VKVertexProgram.cpp:345)

 Last emulator version.

  With OpenGl there is some physx problem during intro, physix not working properly, at least not on my slow machine - Core i7 4770S, 32GB, Geforce 970- Last Nvidia driver, Windows 7 - 64bit, so intro freeze in loop - cart is stuck and dont reach checkpoint, Vulkan works fine.
  FPS: Opengl during intro 5,6 with vulkan is 8-30 FPS, game is usually faster what intro..

  I tried game twice with Vulkan and once i have Vulkan problem with intro too - not big enough graphics buffer problem,second time it was fine and intro was completed.

Log:
https://www.dropbox.com/s/6vb3mhyep72s518/RPCS3.zip?dl=0

**Comment by kd-11** [comment]
Desync bug, should've been fixed on current master after robustness improvements.
