### ISSUE TITLE
BLUS31202 Skyrim Loading system not working, saving is working

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#3816]
Last emulator version, Windows 7. Load from my menu or Contiue from save place always ends with error right at loading start..

F {PPU[0x1000002] Thread (Save Data Utility OSD Thread) [0x0097ef60]} class std::runtime_error thrown: Verification failed (e=0x3e6): file::read
(in file ..\Utilities\File.cpp:887)
E {PPU[0x1000002] Thread (Save Data Utility OSD Thread) [0x0097ef60]} Stat: 'sys_memory_get_page_attribute' failed with 0x80010002 : CELL_EINVAL [x33]

 I dont know if matters than game is loaded from Windows network share, its working fine at least for game loading..

**Comment by Kravickas** [comment]
Loading saves works fine with me, look like maybe just corrpted save after crash ?

**Comment by ruthan** [comment]
I highly doubt it, i have tried multiple saves / multiple times and i never got crash during saving.

**Comment by ruthan** [comment]
Load still not working error:
E {PPU[0x1000002] Thread (Save Data Utility OSD Thread) [0x0098df5c]} MEM: Page_fault writing location 0x90250000 because of using unmapped memory
E {PPU[0x1000001] Thread (Page Fault Handler) [0x0080ccf0]} 'sys_memory_get_page_attribute' failed with 0x80010002 : CELL_EINVAL [2]

**Comment by ruthan** [comment]
On 8700K is playable for half a hour ~30 FPS, its really shame that saving is not working. I hope that Elad the fixer will once fix it..

**Comment by ruthan** [comment]
I did more testing - for other (older) version of Skyrim - BLUS30778, its loading working.. But at least now, i have problem, on at least 2 machines to go through intro, but fortunatelly save is created before end of intro.
  I tested it on 2 machines.

  What is strange:
- that older version of Skyrim still see saves for newer version, only inform user that they are for newer version and refuse to open that.
- save thumbnails are broken for all save in BLUS30778 version

**Comment by elad335** [comment]
@ruthan Please retest with #5668, this game uses read-only memory a little before halting. Even if unfixed post log.

**Comment by ruthan** [comment]
I did some retesting with 7888 build, it able to load some old save on my Coffee lake machine (i usually much some stable with RPCS what my Haswell machine), but i get through intro - because of other bugs it took 3 tries and save, new game save i cant load it.

**Comment by benderscruffy** [comment]
time to update the issue

**Comment by Muhlawor** [comment]
Gran Turismo 5 throwing these errors like crazy

**Comment by money123451** [comment]
works fine for me 
![Screenshot_20200224_105858](https://user-images.githubusercontent.com/12605368/75168459-e6a7ff80-56f4-11ea-9980-78f1847bc69f.png)

**Comment by tbergeron** [comment]
@ruthan did you ever get that fixed? I have a very similar problem with Oblivion https://github.com/RPCS3/rpcs3/issues/13802
