### ISSUE TITLE
Error while configuring keyboard gamepad settings?

### ISSUE THREAD

**Issue by irinrin** [RPCS3/rpcs3#3818]
![screen-08 43 16 01 12 2017](https://user-images.githubusercontent.com/34145845/33462668-bf9d793c-d673-11e7-8eac-bbf69a00b240.png)

**Comment by Megamouse** [comment]
When exactly did this happen

**Comment by irinrin** [comment]
Whenever I try to click save on keyboard config

**Comment by Megamouse** [comment]
okay. I fixed this already it just has to be merged into master

**Comment by irinrin** [comment]
Okay thank you so much. 👍
