### ISSUE TITLE
BLES00932 Demon's Souls with 4k Resolution Scale

### ISSUE THREAD

**Issue by Dani1977** [RPCS3/rpcs3#3822]
Hi,
I'm using Vulkan with Nvidia GeForce 1080

with Resolution Scale upper than 100% there are some white line and / or square .
Also on the bottom of the screen the buttons are partially covered

No issue leaving 100% Resolution Scale .

Thanks, regards .
PS
I have the issue before the #3772 and now with #3772 
PPS
Sorry for my bad bad English 

The screen is with 300% Resolution Scale
![bles00932_4k](https://user-images.githubusercontent.com/31347274/33498411-85f058fe-d6d1-11e7-93b9-addc79315af9.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1522610/RPCS3.log.gz)

**Comment by SakataGintokiYT** [comment]
@Dani1977 
GPU Tab:
Resolution Scale Threshold:16x16.

**Comment by Dani1977** [comment]
@SakataGintokiYT 
Thanks , changing Resolution Scale Threshold fixed problem of button on bottom .

but strange line and squares remains i try any of those Resolution Scale Threshold 1, 2, 4, 8 ,16, 32, and 64

![bles00932_4k_a](https://user-images.githubusercontent.com/31347274/33500163-2a9be732-d6d8-11e7-8377-cec5b5e8134e.png)

Regards .

**Comment by kd-11** [comment]
It only happens on nvidia GPUs afaik.

**Comment by Dani1977** [comment]
thanks for reply, is not a big problem just a little annoying

**Comment by fifazalata** [comment]
@kd-11 I notice that those white lines appear in most cases in fullscreen mode (ex: DeS)
while on windowed mode, the scaling works as it should without any white lines
Hope that helps.

**Comment by slx7R4GDZM** [comment]
Not really sure if it's relevant but the PC version of Dark Souls had those white lines at high resolution too.

**Comment by kd-11** [comment]
It is actually relevant and something I discussed with others before. The game does not like non-integer scaling so 200% is the safest bet. When windowed, pixel overlap will hide the problem but you can stretch the window to more than double size and they appear again. Remember that upscaling is technically inaccurate so this is not really a surprise.
