### ISSUE TITLE
[BLJM60223] Nier replicant missing texture ingame

### ISSUE THREAD

**Issue by Oky12** [RPCS3/rpcs3#3829]
i am playing nier replicant with rpcs3 0.0.4-6200-8f314c51 alpha.
when ingame/gameplay is only with white screen. but UI game is exist
![screenshot 74](https://user-images.githubusercontent.com/30838114/33517204-4f399eb0-d7b2-11e7-9c00-5be2dd67fee0.png)

when cutscene is no problem !!
![screenshot 75](https://user-images.githubusercontent.com/30838114/33517212-70cf1fa0-d7b2-11e7-8eff-18c4af7df757.png)

here a log for help fix missing texture for nier replicant : 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1523914/RPCS3.log.gz)

i hope this game and exclusives game quickly fixed :D

**Comment by Illynir** [comment]
Issue fixed on: https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.4-1183/artifacts

**Comment by Oky12** [comment]
![screenshot 81](https://user-images.githubusercontent.com/30838114/33794173-1cc71b50-dcf9-11e7-8335-8ca040b29191.png)

Still missing texture

**Comment by Oky12** [comment]
i try playing until i save the game with rpcs3 v0.0.4-6226-17bfb3be Alpha. when gameplay on the village (look screenshot). some texture is loaded but the lightning is too bright (screenshot 1). 
![screenshot 94](https://user-images.githubusercontent.com/30838114/34091049-cc9da1de-e3ed-11e7-97f3-d4b61cec2c39.png)

i try experiment with using additional setting Gpu. i try use strict rendering mode and use gpu texture scalling. i try play again and the brightnes is too dark (screenshot 2). 
![screenshot 95](https://user-images.githubusercontent.com/30838114/34091074-f0adfe66-e3ed-11e7-9b07-8ad78e8f1344.png)

not only that. when in the village. fps dropped to 5 fps T_T . when first play ( snow place) i got 30 fps

**Comment by kd-11** [comment]
The problems listed here are long fixed in master. The framerate issue has nothing to do with graphics so I'll close this.

**Comment by turbocat2001** [comment]
@kd-11 hello. Launched "Nier: Replicant" today on a nightly build. I observe the same problems with white textures. 

![image](https://github.com/RPCS3/rpcs3/assets/51446645/c3d43969-587b-4459-afde-0f0d308656e0)

Commit [#13917](https://github.com/RPCS3/rpcs3/pull/13917)
Build: https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-c37fc73a028717f891e12e56db784fd2d8d060ae/rpcs3-v0.0.27-15111-c37fc73a_win64.7z

```
OS: Windows 10 Pro (build 19044)
CPU: Intel64 Family 6 Model 151 Stepping 5 GenuineIntel ~3300 МГц
Video: Nvidia GeForce RTX 3060 (Vulkan render)
RAM: DDR4 16Gb.
```

**Comment by AniLeo** [comment]
Removed invalid report and locked thread to avoid further spam from users not using proper settings from wiki.
