### ISSUE TITLE
RPCS3 hangs on boot

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#3830]
In Linux Mint 18.3 x64, RPCS3 will boot but not display the Qt UI, instead appearing to do nothing (though the rpcs3 process is in the list of running processes and must be terminated).

Boots: 662fe8cc957d8d4991bcb74f354b3b6dfab4ef4d
Doesn't boot: 8f314c5101791c60e74eac7fa8bf5f81f9a7e767

Is this a known issue?  I could bisect if needed but want to be sure that's necessary first.

**Comment by Megamouse** [comment]
try installing these:

https://launchpad.net/~beineri/+archive/ubuntu/opt-qt593-xenial 
https://launchpad.net/~beineri/+archive/ubuntu/opt-qt593-trusty

**Comment by Shoegzer** [comment]
Thank you!  I installed xenial's, as that corresponds closest with my distro release.  I then tried installing qt59-meta-full (full stack) and qt59-meta-minimal (minimal core) and then launched RPCS3, but RPCS3 still hangs on boot.  The other packages didn't seem to be relevant, but are there others to install?  

Note: The only qt-related dependency listed on the main GH page is "qt5-default", which is already installed, and even if that one's only at 5.5.1 RPCS3 has been launching fine up until the build from a few days ago as listed above.

**Comment by Megamouse** [comment]
There have been so many commits between these two builds.
maybe try at this commit to see if it worked there:
https://github.com/RPCS3/rpcs3/commit/3fbc960c44403e9dce363941b07bf1aeadbc2937

**Comment by Shoegzer** [comment]
Okay this is odd.  I moved back to the build I reported as working in my first post above just to be sure it worked, and now it doesn't.

Is there anything I can do, like provide a trace on the rpcs3 binary, that might hint at what's going on?
