### ISSUE TITLE
God of War Collection white screen!!

### ISSUE THREAD

**Issue by WolfSpirit1999** [RPCS3/rpcs3#3831]
i can't play GOW Collection
rpcs3-v0.0.3-2017-10-09-86fb6f4b_win64
![bandicam 2017-12-02 22-50-43-483](https://user-images.githubusercontent.com/30192305/33517277-a417ea8a-d7b3-11e7-854e-b5ad51020284.jpg)

> E {PPU[0x1000008] Thread (fios mediathread) [0x00af7090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/GOW1/exec/wad/r_perm.wad_ps3” [1]
F {PPU[0x1000000] Thread (main_thread) [0x001bf1f4]} MEM: Access violation reading location 0x8

MY SPECS

- Intel Core i5 4670K CPU @3.40GHz

- 8GB RAM

- NVIDIA GeForce GTX 970

- Windows 10 64bit

**Comment by Asinin3** [comment]
That's an old build it only works in new versions update. Also seems like you're using the same bad pirated version as other people who have this issue and you have split multiman files.

**Comment by WolfSpirit1999** [comment]
yes im sorry dont knw wht to do, 

what should i do?? to play ths game?

**Comment by Asinin3** [comment]
https://rpcs3.net/download download latest version
https://rpcs3.net/quickstart follow the guide on how to dump and rip the real game
then don't submit issues that stem from using bad pirated versions and ask for support on github, use the discord server: https://discord.me/RPCS3 close this issue please.
