### ISSUE TITLE
Regression: Baja: Edge of Control (#3366)

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#3834]
The game regressed after PR3366
commit 05442bdb
BAJA: Edge of Controll was ingame before, now crashes with
F {PPU[0x1000000] Thread (main_thread) [0x002d2100]} MEM: Access violation writing location 0x60
reverting the commit helps

**Comment by Xcedf** [comment]
First part of it fixed now

**Comment by AniLeo** [comment]
Retest on master to confirm whether this is still a bug

**Comment by Xcedf** [comment]
Yes, still an issue

**Comment by Xcedf** [comment]
Def Jam Icon BLES00042 also has this issue

**Comment by Xcedf** [comment]
Harry Potter and the Deathly Hallows: Part 1 [BLES00931] here
