### ISSUE TITLE
[NPEB00847] Mortal Kombat

### ISSUE THREAD

**Issue by ScorpionMKXL** [RPCS3/rpcs3#3838]
![bandicam 2017-12-03 14-56-17-371](https://user-images.githubusercontent.com/29108928/33525137-97e40136-d83a-11e7-8eb1-f163c543ce86.jpg)
![bandicam 2017-12-03 14-56-41-501](https://user-images.githubusercontent.com/29108928/33525138-98211f30-d83a-11e7-8b11-4153c443e0a6.jpg)
![bandicam 2017-12-03 14-57-42-786](https://user-images.githubusercontent.com/29108928/33525139-98559b52-d83a-11e7-897c-761dcc72013e.jpg)
![bandicam 2017-12-03 14-58-42-724](https://user-images.githubusercontent.com/29108928/33525140-98ac5d5c-d83a-11e7-93c2-d1fb10a89133.jpg)
Some maps have a black screen

**Comment by Xcedf** [comment]
Should be fixed now, with Strict render of course

**Comment by AniLeo** [comment]
Game is displaying stages properly now with SRM, closing as solved
