### ISSUE TITLE
RPCS3 ( minor ) GUI Bugs

### ISSUE THREAD

**Issue by M220** [RPCS3/rpcs3#3839]
Hi Guys
There is a problem with RPCS3 GUI as listed below : 
- Can't save additional edits to things like view list icons ( Like previous problem , restored to default after resseting RPCS3 )
- game list icon is at "Small" in default but it says it's in "Tiny" and when you select tiny , that's when the emulator display what tiny must display

I think @Megamouse will be good for this Issue :)
Sorry for my bad english :D 
Thank you guys !
( and my RPCS3 version is the latest master and this bugs isn't there at two or three months ago builds ( I Think )

**Comment by Megamouse** [comment]
should be fixed now

**Comment by M220** [comment]
Fixed :D 🎉
