### ISSUE TITLE
GUI message box / window/input box on same monitor as game window always on top and focused

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#3840]
Hello,
when i test this emulator there is 1 annoying thing - not main windows message boxes and other windows and not spawned on same monitor as primary windows.

  From my POV they should be on same monitor always on top and input box should have focus by default, or at least in the options should be option for set how they should behave.. For some read only windows like - hey this game has autosave - would be nice auto close after few seconds.

  Also is annoying that not these windows could be handled by controller and i have to reach keyboard for them..

**Comment by AniLeo** [comment]
This issue was long solved on master, closing.
