### ISSUE TITLE
Gamepads keyboard input BUG!!

### ISSUE THREAD

**Issue by gkfrnwkd** [RPCS3/rpcs3#3844]
TEKKEN 6 skill
←→ <- No input
→← <- No input

**Comment by Megamouse** [comment]
Does this fix the problem?

https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7156/artifacts

**Comment by Megamouse** [comment]
I don't think this issue makes any sense

**Comment by scribam** [comment]
@gkfrnwkd Please read the rules on creating issues: https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md

**Comment by scribam** [comment]
@AniLeo Can you close this issue unless someone understands it?
