### ISSUE TITLE
Regression: [BLJM61325] Star Ocean 5 (#3823)

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [RPCS3/rpcs3#3872]
newest master Build Causes the error below 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1529022/RPCS3.log.gz)

F {PPU[0x1000000] Thread (main_thread) [0x000e1690]} MEM: Access violation reading location 0xed496ffe

**Comment by AniLeo** [comment]
What PR regressed it

**Comment by Gamedev1909** [comment]
https://github.com/RPCS3/rpcs3/pull/3823 this one because before this the game works weird as that sounds

**Comment by Parthorisian** [comment]
**MEM: Access violation reading location 0x0** log [StarOcean5_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2220764/StarOcean5_RPCS3.zip)

**Comment by Narihari** [comment]
> This game is "Ingame" according to https://forums.rpcs3.net/thread-178040.html
> @Gamedev1909 is it still an issue?

Yes it is, the game don't load and when you close the window, RPCS3 crash and completely close.

`F {PPU[0x1000000] Thread (main_thread) [0x00016700]} MEM: Access violation reading location 0x0`

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2547988/RPCS3.log)

**Comment by digitaldude555** [comment]
![snap3417](https://user-images.githubusercontent.com/26138653/48301564-a79e6c80-e4f8-11e8-8e87-1a66cf1cad22.jpg)
How do you regression folks explain a man going ingame with master build that isnt even 20 days old right. @Narihari

**Comment by Narihari** [comment]
> ![snap3417](https://user-images.githubusercontent.com/26138653/48301564-a79e6c80-e4f8-11e8-8e87-1a66cf1cad22.jpg)
> How do you regression folks explain a man going ingame with master build that isnt even 20 days old right now. @Narihari

Are you dumb or something ? We are talking about the latest version who does not start the game.

**Comment by digitaldude555** [comment]
This issue is 1 years old. use the build that cheng used in the image and see if this game works for you. [Here](https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-966c3fea5b420ba3d947416035cb01d6d65c5440/rpcs3-v0.0.5-7452-966c3fea_win64.7z) @Narihari

**Comment by Narihari** [comment]
> This issue is 1 years old. use the build that cheng used in the image and see if this game works for you. [Here](https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-966c3fea5b420ba3d947416035cb01d6d65c5440/rpcs3-v0.0.5-7452-966c3fea_win64.7z) @Narihari

The LATEST build DOES NOT work. Man omg.

**Comment by Narihari** [comment]
> @Narihari this issue is from december the same error for 1 year not latest build, does it work in the link I gave you?

I don't care about the 7452, it does not work with the latest version.

**Comment by ReaperOfSouls1909** [comment]
issues are depending on the settings the game is picky

**Comment by digitaldude555** [comment]
![rpcs3_2018-11-18_11-47-57](https://user-images.githubusercontent.com/26138653/48678529-3ceed000-eb8d-11e8-89e4-b61bcbce53df.png)
A user was able to get intro every time can you guys confirm it improved? @ReaperOfSouls1909 @Narihari

**Comment by Narihari** [comment]
![image](https://user-images.githubusercontent.com/33153067/48700368-20ce4b80-ebec-11e8-8529-166c9617c4c8.png)

Not working for me.

**Comment by Asinin3** [comment]
@Narihari Something seems off with your log, can you please verify your game dump so we know that the game was ripped properly.


Use the PS3-ISO-Rebuilder tool (http://jonnysp.bplaced.net/)
Then load the corresponding IRD file, and then your dumped disc folder (JB Folder) or the decrypted ISO.
Wait until all files are checked, everything should be green, counters for missing and corrupted files in the lower left corner should be 0.

**Comment by Narihari** [comment]
> Then load the corresponding IRD file

The IRD file is not on the website.
![image](https://user-images.githubusercontent.com/33153067/48705683-1dda5780-ebfa-11e8-95f4-9764ec39651c.png)

**Comment by digitaldude555** [comment]
Star Ocean 5 is ingame, close the issue now?

**Comment by Metafalica** [comment]
Umm, why this closed? Same issue still happens according to forum thread in latest revisions.
https://forums.rpcs3.net/thread-178040-page-2.html

**Comment by ReaperOfSouls1909** [comment]
Still bugs out also

**Comment by ReaperOfSouls1909** [comment]
Same thing newest build

**Comment by ReaperOfSouls1909** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4024582/RPCS3.log)

**Comment by ReaperOfSouls1909** [comment]
@Narihari turns out we had a bad rip so when you rip it again be sure to make a iso this time and than copy the files off the iso this can be closed @AniLeo 
![image](https://user-images.githubusercontent.com/18043258/72097116-0b394b00-32f2-11ea-891f-f1199b5a2da2.png)
