### ISSUE TITLE
HLE: cellVdec Unknown colorMatrixType (64)

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3897]
> ·F 0:00:34.653947 {PPU[0x1000000] Thread (main_thread) [0x002d7430]} class std::runtime_error thrown: Unknown colorMatrixType (64)
> (in file Emu\Cell\Modules\cellVdec.cpp:617)

[Ridge_Racer_7.txt](https://github.com/RPCS3/rpcs3/files/1529251/Ridge_Racer_7.txt)
![1](https://user-images.githubusercontent.com/14265316/33583787-22aa04d6-d96d-11e7-858f-9f7912eef2ad.png)

**Comment by hcorion** [comment]
does it work with lle vdec?

**Comment by TotalCaesar659** [comment]
No, black screen and
> ·F 0:00:21.802619 {PPU[0x100000f] Thread (CPamfDemuxer::ReadThread) [0x002d72e0]} class std::runtime_error thrown: Unregistered PPU function

[Ridge_Racer_7.txt](https://github.com/RPCS3/rpcs3/files/1529592/Ridge_Racer_7.txt)

**Comment by Zangetsu38** [comment]
Very old issue, i bypasse with little hack, but need found correctly fix :/
Siren blood have problem also with video, after video finish, game freeze, but works with libvdec, and few game have glitch during video, uncharted etc.

**Comment by AniLeo** [comment]
Fixed by #5341
Closing
