### ISSUE TITLE
sys_tty_read: Unimplemented - American Mcgee's Alice [BLUS30607] DLC

### ISSUE THREAD

**Issue by moozhub** [RPCS3/rpcs3#3906]
Hello,

After installing the DLC for Alice: Madness Returns, when navigating through the main menu and choosing to play American Mcgee's Alice, the emulator attempts to load the package but fails to do so throwing the following runtime error:

`F 0:03:32.735303 {PPU[0x1000005] Thread (ReadTTY) [0x000ba75c]} class std::runtime_error thrown: Unimplemented (in file Emu\Cell\lv2\sys_tty.cpp:15) 
E 0:03:32.735316 {PPU[0x1000005] Thread (ReadTTY) [0x000ba75c]} Stat: 'sys_mutex_trylock' failed with 0x80010005 : CELL_ESRCH [x79]`

I've attached the log in it's entirety from initially installing the game data into /game and afterward installing the DLC and attempting to launch it.

System specifications:

**Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz | 12 Threads | 31.95 GiB RAM | AVX+ | Nvidia 1080GTX**

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1535132/RPCS3.log.gz)

**Comment by clienthax** [comment]
Game seems to be attempting to read from the TTY
Something I've never seen another retail game do ;)

**Comment by moozhub** [comment]
Yeah.. I sorta figured as much. The DLC content it's trying to load is ancient... even in PS3 standards (but may be nice to look into long lost ancient games ported to the PS3 ;)). For what it's worth, the TTY console is reporting this which makes me believe that it's not resolving the path to some files correctly:

`could not load shader pool file //ps3shaders.bin`

I have no idea though, just now getting into this project. Let me know if you need me to test something else..

**Comment by Zardas81** [comment]
sys_tty_read implemented in #4831, needs retesting.

**Comment by Parthorisian** [comment]
Crash - log [crashAlice_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2212019/crashAlice_RPCS3.zip)
But it seems it attempts load something

**Comment by Megamouse** [comment]
I fixed this as Zardas81 mentioned.
The PPU function stuff is a general issue that can be found somewhere here.
The game won't even run in interpreters so idk what that's all about
