### ISSUE TITLE
Majin and the Forsaken Kingdom demo - Video driver crash

### ISSUE THREAD

**Issue by Krusher97** [RPCS3/rpcs3#3907]
The demo crashes the video drivers on my computer on both Vulkan and OpenGL. In case of Vulkan it caused a BSOD so I haven't tried using that again. Video card is 750Ti with driver version 387.92.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1535698/RPCS3.zip)

**Comment by hcorion** [comment]
You're using a older version of RPCS3 (dec 1st). Please update your RPCS3 before filing a bug report.

**Comment by Krusher97** [comment]
Unless I am missing some secret build absolutely nothing has changed

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1540217/RPCS3.zip)
