### ISSUE TITLE
South Park doesn't react after character's name input

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3910]
After character's name input, the game doesn't react to choosing Yes or No.
![1](https://user-images.githubusercontent.com/14265316/33721927-818e2afa-db79-11e7-8471-4f71525bc81b.png)
![2](https://user-images.githubusercontent.com/14265316/33721935-86b6ae8a-db79-11e7-8a93-048fb2e233a0.png)
[South_Park_The_Stick_of_Truth.txt](https://github.com/RPCS3/rpcs3/files/1539550/South_Park_The_Stick_of_Truth.txt)

**Comment by BiatuAutMiahn** [comment]
Same, Build 0.0.5-6859-8826948c4

**Comment by Megamouse** [comment]
please try with https://github.com/RPCS3/rpcs3/pull/5465
