### ISSUE TITLE
Debug eboots are not correctly inflated after decryption

### ISSUE THREAD

**Issue by clienthax** [RPCS3/rpcs3#3911]
Tested with the retroarch DEX pkg.

The eboot data appears to be zlib data after it is decrypted + written to the cache.
When this is loaded into the loader, it explodes as its not a valid elf.
Ideally we should check for a zlib header after decryption and inflate the data before writing to the data cache.

**Comment by dio-gh** [comment]
Is this still an issue? Can't test it myself.
