### ISSUE TITLE
Please Help :( RPCS3 Problem

### ISSUE THREAD

**Issue by Feather4011** [RPCS3/rpcs3#3912]
I Was Really Excited For Playing A Game On RPCS3 The Fps And Everything was great til i joined a map it crashes and shows this:
![wju](https://user-images.githubusercontent.com/34346898/33724853-3d532250-db79-11e7-8bb6-3756c3612251.JPG)
So Please help!

**Comment by M220** [comment]
Close this issue your self before Ani Comes and say :
For God Sake please read the guidelines before opening an issue.

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use our forums for that.
:D

**Comment by M220** [comment]
Also don't forget the part : 
The issue has been marked as Invalid and closed :)))

**Comment by clienthax** [comment]
Issue tracker not for this.. Seriously, follow the link, read, dont be a dum dum
https://www.youtube.com/watch?v=2C7mNr5WMjA
