### ISSUE TITLE
fatal error: 'optional.hpp' file not found

### ISSUE THREAD

**Issue by JasonFengIce** [RPCS3/rpcs3#3915]
/Users/huibin/rpcs3/rpcs3/Emu/RSX/Common/../rsx_utils.h:8:10: fatal error: 'optional.hpp' file not found
#include <optional.hpp>
         ^
1 error generated.
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/Common/TextureUtils.cpp:4:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/Common/../RSXThread.h:14:
/Users/huibin/rpcs3/rpcs3/Emu/RSX/Common/../rsx_utils.h:8:10: fatal error: 'optional.hpp' file not found
#include <optional.hpp>
         ^
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/Common/BufferUtils.cpp.o] Error 1
1 error generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/Common/TextureUtils.cpp.o] Error 1
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GL/GLGSRender.cpp:4:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GL/GLGSRender.h:2:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GSRender.h:3:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/RSXThread.h:14:
/Users/huibin/rpcs3/rpcs3/Emu/RSX/rsx_utils.h:8:10: fatal error: 'optional.hpp' file not found
#include <optional.hpp>
         ^
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GL/GLRenderTargets.cpp:3:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GL/GLGSRender.h:2:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GSRender.h:3:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/RSXThread.h:14:
/Users/huibin/rpcs3/rpcs3/Emu/RSX/GL/../rsx_utils.h:8:10: fatal error: 'optional.hpp' file not found
#include <optional.hpp>
         ^
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp:2:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GL/GLGSRender.h:2:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GSRender.h:3:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/RSXThread.h:14:
/Users/huibin/rpcs3/rpcs3/Emu/RSX/rsx_utils.h:8:10: fatal error: 'optional.hpp' file not found
#include <optional.hpp>
         ^
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/Null/NullGSRender.cpp:2:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/Null/NullGSRender.h:2:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GSRender.h:3:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/RSXThread.h:14:
/Users/huibin/rpcs3/rpcs3/Emu/RSX/rsx_utils.h:8:10: fatal error: 'optional.hpp' file not found
#include <optional.hpp>
         ^
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GSRender.cpp:5:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GSRender.h:3:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/RSXThread.h:14:
/Users/huibin/rpcs3/rpcs3/Emu/RSX/rsx_utils.h:8:10: fatal error: 'optional.hpp' file not found
#include <optional.hpp>
         ^
1 error generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/Null/NullGSRender.cpp.o] Error 1
1 error generated.
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/RSXTexture.cpp:3:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/RSXThread.h:14:
/Users/huibin/rpcs3/rpcs3/Emu/RSX/rsx_utils.h:8:10: fatal error: 'optional.hpp' file not found
#include <optional.hpp>
         ^
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/GSRender.cpp.o] Error 1
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/RSXThread.cpp:5:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/RSXThread.h:14:
/Users/huibin/rpcs3/rpcs3/Emu/RSX/rsx_utils.h:8:10: fatal error: 'optional.hpp' file not found
#include <optional.hpp>
         ^
1 error generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/RSXTexture.cpp.o] Error 1
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GL/GLTexture.cpp:5:
In file included from /Users/huibin/rpcs3/rpcs3/Emu/RSX/GL/../RSXThread.h:14:
/Users/huibin/rpcs3/rpcs3/Emu/RSX/GL/../rsx_utils.h:8:10: fatal error: 'optional.hpp' file not found
#include <optional.hpp>
         ^
1 error generated.
1 error generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/GL/GLTexture.cpp.o] Error 1
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/RSXThread.cpp.o] Error 1
1 error generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/GL/GLGSRender.cpp.o] Error 1
1 error generated.
1 error generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/GL/GLVertexBuffers.cpp.o] Error 1
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/GL/GLRenderTargets.cpp.o] Error 1
2 warnings generated.
2 warnings generated.
2 warnings generated.
2 warnings generated.
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2

**Comment by clienthax** [comment]
No where enough info on your environment

**Comment by kd-11** [comment]
You need to initialize ur submodules, or at least thats what it looks like since you didnt give info on your setup. Closing.

**Comment by ezhdanov** [comment]
got same error

```
[ 60%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Emu/Cell/Modules/cellGcmSys.cpp.o
<built-in>:1:9: warning: '__STDC_CONSTANT_MACROS' macro redefined [-Wmacro-redefined]
#define __STDC_CONSTANT_MACROS 1
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdint.h:116:12: note: previous definition is here
#   define __STDC_CONSTANT_MACROS
           ^
<built-in>:3:9: warning: '__STDC_LIMIT_MACROS' macro redefined [-Wmacro-redefined]
#define __STDC_LIMIT_MACROS 1
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdint.h:113:12: note: previous definition is here
#   define __STDC_LIMIT_MACROS
           ^
In file included from /Users/eugene/depo/rpcs3/rpcs3/Emu/Cell/Modules/cellGcmSys.cpp:8:
In file included from /Users/eugene/depo/rpcs3/rpcs3/Emu/RSX/GSRender.h:3:
In file included from /Users/eugene/depo/rpcs3/rpcs3/Emu/RSX/RSXThread.h:14:
/Users/eugene/depo/rpcs3/rpcs3/Emu/RSX/rsx_utils.h:8:10: fatal error: 'optional.hpp' file not found
#include <optional.hpp>
         ^~~~~~~~~~~~~~
2 warnings and 1 error generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/Cell/Modules/cellGcmSys.cpp.o] Error 1
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2
```

also I was try fix it with #include <optional>

```
In file included from /Users/eugene/depo/rpcs3/rpcs3/Emu/Cell/Modules/cellGcmSys.cpp:8:
In file included from /Users/eugene/depo/rpcs3/rpcs3/Emu/RSX/GSRender.h:3:
In file included from /Users/eugene/depo/rpcs3/rpcs3/Emu/RSX/RSXThread.h:14:
/Users/eugene/depo/rpcs3/rpcs3/Emu/RSX/rsx_utils.h:8:10: fatal error: 'optional' file not found
#include <optional>
         ^~~~~~~~~~
2 warnings and 1 error generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/Cell/Modules/cellGcmSys.cpp.o] Error 1
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2

```

environment: OSX 10.13.3
```
spaceship:rpcs3_build eugene$ brew install boost
Warning: boost 1.66.0 is already installed
```

```
spaceship:rpcs3_build eugene$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
spaceship:rpcs3_build eugene$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

```
