### ISSUE TITLE
Graphical glitches in Valkyria Chronicles [ BLUS30196 ]

### ISSUE THREAD

**Issue by miguel-nunes** [RPCS3/rpcs3#3916]
Folks,

This game is close to be perfect!

In Linux and Windows, with OGL and VK, this bug is happening:

![valkyria-chronicles](https://user-images.githubusercontent.com/21225981/33772314-54eae2fc-dc1b-11e7-8124-19fd3745bbb2.png)

This is happen in the small portraits that occurs in some battles. I can't go further because withou looking correctly to the shape of the enemies, is almost impossible to aim.

One exclusive bug in the Linux builds is that the small videos quickly lost sync and don't play nicely. In th Windows builds that not happen.

As usual, logs for your review:

[valkyria.zip](https://github.com/RPCS3/rpcs3/files/1543049/valkyria.zip)

Thanks for all hard work, ppl. It was a grateful surprise see VC running so well and so close to be perfect!

Cheers!

**Comment by miguel-nunes** [comment]
@jarveson and @kd-11

Even after the PR #4356, there's a lot of glitches involving vertices on Linux. Just like that:

![vc-vertexes-wrong-position](https://user-images.githubusercontent.com/21225981/38155130-469dae1c-344c-11e8-9e59-952d2d9f31a5.png)

I'm adding the logs too. They're not that clean. If they are confusing to find something, let me know and I´ ll generate fresh logs with only VC running.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1864872/RPCS3.log.gz)

Cheers!

**Comment by jarveson** [comment]
Yea, it looks like not *every* case of exploding or weird vertices were fixed by the pr, theres a chance the fix is incomplete, or it may be something else entirely. Unfortunately they may just need to be looked into specifically at some point to see whats up

**Comment by miguel-nunes** [comment]
I wasn't able to see the behavior on Windows @jarveson , but I'm assuming that's the same there. Since Linux drivers are note all complete on the Linux side of things, maybe this a behavior only on Linux. I'll report if there's something different there.

**Comment by digitaldude555** [comment]
@miguel-nunes strict rendering will fix the water issue. Can be closed after you confirm.

**Comment by miguel-nunes** [comment]
@digitaldude555 , I'll close the issue, but the water problem persists even with Strict Rendering. As @jarveson said, this maybe is a problem in somewhere else and now there's no basis where could be. 

Closing anyway! Cheers!
