### ISSUE TITLE
Input bug with Scott Pilgrim and "Maybe" other games.

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#3924]
Ok, i found an input "bug" that almost drives me crazy...

I´ll try to explain it better as i can with my rookie english level.

NOTE: This only happens when using two different controllers (Xbox one controller and Xbox 360 controller)

Steps:

- Open gamepad settings

- Set xinput for player 1 (with Xinput Pad #0) (The xbox one controller)

- Set xinput for player 2 (with Xinput Pad #1) (Xbox 360 controller) "You can set more players with Pad #2, #3, etc, but to test this bug it´s enough with two players.

-Start a multiplayer game

-All works ok. Close the emulator.

-Now you want to play alone, 1 player, then you disconnect one pad from your computer, (The 360 controller) but if you open the gamepad settings, you can see both pads (or more if you added it) and both have the "xinput pad #1"

- If you try to start a game (Scott pilgrim in my case) the game is freezed with 0 fps. This can be solved only disabling the second pad, closing the emulator, and open the game again. The game now works, but the player 1 remains with xinput pad #1, and you need to disable and disconnect from the usb, then connect and enable the xinput again, now your pad gots finally the xinput pad #0.

I tested a few multiplayer games with this, bomberman ultra, castle crashers, etc. And the only one who hangs with this is "Scott Pilgrim vs the world".

This message is showed in the log when i try to start the game with this problem:

F {PPU[0x1000000] Thread (main_thread) [0x00140e08]} MEM: Access violation writing location 0x22c

**Comment by Megamouse** [comment]
should be fixed now

**Comment by LuismaSP89** [comment]
@Megamouse  Perfectly fixed : )
