### ISSUE TITLE
Red Dead Redemption: "RSX: Invalid framebuffer setup, w=0, h=0"

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3925]
There are these errors in each frame until the game world is loaded.

```
E {rsx::thread} RSX: Invalid framebuffer setup, w=0, h=0
U {PPU[0x1000000] Thread (main_thread) [0x010d791c]} cellNetCtl TODO: cellNetCtlGetInfo(code=0x4 (INFO_LINK), info=*0x1588d98)
```

GTX 760 Ti, Win 7 x64.
Using LLVM, ASMJIT, Load liblv2.sprx only.
Vulkan, Strict Mode Off, GPU Texture Scaling On.
Force CPU blit off, ZCull on (no matter).

**Comment by kd-11** [comment]
Thats not a true error. I'll downgrade severity to warning to avoid log spam, but from observing games, it is possible to push draw commands with a 0x0 framebuffer. Of course nothing will be drawn but rpcs3 already handles that correctly.
