### ISSUE TITLE
Project Diva F 2nd [BLUS31431] Bloom clamping issues

### ISSUE THREAD

**Issue by MaikelChan** [RPCS3/rpcs3#3926]
Hi everyone!

There's a small issue with Project Diva F 2nd (and maybe other Project Divas) where colors sometimes don't appear correctly. You can frequently see red, green or blue splotches all over the place.

And it appears that it is due to some weird clamping values used when applying the bloom post-process. As you can see in the fragment shader, there are a lot of clamps with min and max values of -65504 and 65504. I don't know if that is how it's supposed to be? I found it a bit weird. Anyway, changing them to 0 and 1 fixes the issue.

Some screenshots from Renderdoc with and without the issue:

![1](https://user-images.githubusercontent.com/7031754/33808378-8f5c12f0-dde5-11e7-9e08-6bacaa7f5f6e.png)
![2](https://user-images.githubusercontent.com/7031754/33808379-8f7868e2-dde5-11e7-8df8-8f0c35f29f15.png)

The selected lines are the ones I changed in order to fix the weird colors. But it darkens the image a little bit, so it's not the correct fix, but I don't know exactly how it should be. This happens with all graphic backends.

Specifications:
RPCS3 0.0.4-6216-60f5929f.
Windows 10 Pro x64.
Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
8 Threads
9.98 GiB RAM
AVX+
GeForce GTX 980

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1546006/RPCS3.log.gz)

**Comment by elad335** [comment]
follow https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md or your issue will get closed

**Comment by MaikelChan** [comment]
Sorry about that. Updated first post.
