### ISSUE TITLE
RPCS3 is running on ancient PC?

### ISSUE THREAD

**Issue by AkagiShiroe** [RPCS3/rpcs3#3933]
i tried some games and got them rendered.. of course with low FPS.. do RPCS3 now support OpenGL 3.x Hardware? well the issue are... bad FPS on PPU LLVM(stutter with slower image projection while game still running) and faster with Interpeter (Fast).
![divf2](https://user-images.githubusercontent.com/14356240/33905492-2c1963da-dfc2-11e7-9759-178f1478cda2.jpg)
as you can see the FPS are barely playable (8-10) while in-game menu yield 15-30.
here my spec: -Intel Core I3 540 3,0Ghz
                       -NVIDIA Geforce 9600GT 512mb
                       -4GB DDR3 x 2 (8GB)
im looking forward to this emulator then..

**Comment by AniLeo** [comment]
That GPU is OpenGL 2.1

Need RPCS3.log and drivers information

**Comment by AkagiShiroe** [comment]
![project diva 2nd ogl](https://user-images.githubusercontent.com/14356240/33905994-e4c5139c-dfc3-11e7-8b93-3e662556e48d.jpg)
RPSC3 V.0.0.4-6223-a1fa10ac Alpha

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1553142/RPCS3.zip)

**Comment by AniLeo** [comment]
Drivers are indeed reporting 3.3, NVIDIA's website is wrong.

Interesting though, I guess you got lucky there, but most games shouldn't work correctly.

**Comment by AkagiShiroe** [comment]
i tried ELF demo from RPSC3 and got all of them rendered.. and tried other game like Minecraft.. yield bad fps like 6-10.. so im asking.. do this emulator capable rendering it on Lower API?. thx if you can verify this

**Comment by kd-11** [comment]
Due to the design of opengl, it is possible to run methods from newer versions on very old hardware as long as the driver reports the functionality as being present. Rpcs3 checks for function support and not the version number itself so some older graphics hardware can still work just fine. That being said, the i3-540 is what will hold back performance in this case.

**Comment by AkagiShiroe** [comment]
![rin len](https://user-images.githubusercontent.com/14356240/33933179-df36b27c-dfec-11e7-92bd-9ff750ae3195.jpg)
[RPCS3_2.zip](https://github.com/RPCS3/rpcs3/files/1554995/RPCS3_2.zip)
i tried this beatmap and got freezing state, shader compilation seems slower and make RPCS3 Stuck
(i lower the resolution and got 15-20 fps playable state)

**Comment by AniLeo** [comment]
Closing as it's an old discussion and RPCS3 isn't designed to work on OpenGL 3.x

**Comment by AkagiShiroe** [comment]
my bad, i should close this myself long time ago, beside it was just a whimp for testing ancient builds
