### ISSUE TITLE
Haze can't be started

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3934]
Haze doesn't show "Press Start button" and doesn't react on pressing keys.
![1](https://user-images.githubusercontent.com/14265316/33911214-ac5cd506-dfa2-11e7-968d-1348894304b4.png)
Youtube screenshot:
![2](https://user-images.githubusercontent.com/14265316/33911204-a63cf64c-dfa2-11e7-8a1d-0b62de14052d.png)
[Haze.zip](https://github.com/RPCS3/rpcs3/files/1553469/Haze.zip)

**Comment by hcorion** [comment]
Pressing the start button does initialize something though, after pressing the start button, the log outputs:
```cpp
U {PPU[0x1000000] Thread (main_thread) [0x007172c0]} cellNetCtl TODO: cellGameUpdateInit()
U {PPU[0x1000000] Thread (main_thread) [0x0071a2c0]} cellNetCtl TODO: cellGameUpdateCheckStartAsync(param=*0xd00ff780, cb_func=*0xe715e0, userdata=*0x0)
```
