### ISSUE TITLE
Feature request: PPU module counter

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3935]
Hello, could you implement a counter of PPU modules ("Compiling PPU module **(1/30)**:") or smth like this for knowing remaining time approximately?
![1](https://user-images.githubusercontent.com/14265316/33911475-858495d0-dfa3-11e7-8b77-f718b6f4ec4e.png)

**Comment by marcussacana** [comment]
And maybe will be good if use a single window with all progress bar's, it's the constant creation of windows is very annoying.

**Comment by VelocityRa** [comment]
@TotalCaesar659 That'd be useful, I'll add that.
@marcussacana This has been discussed and deemed too much effort for little benefit.

**Comment by Nekotekina** [comment]
No, single accumulating dialog should be feasible.

**Comment by flash-fire** [comment]
I love having multiple dialogs spamming. It makes it look like that true progress is happening with all the windows going crazy.

**Comment by hcorion** [comment]
I don't, I'd like only one window because while I'm trying to work windows keep popping up and distracting me from whatever I'm looking up/reading.

**Comment by TotalCaesar659** [comment]
Fixed in https://github.com/RPCS3/rpcs3/pull/4005.
