### ISSUE TITLE
Drakengard 3 BLJM61043 and BLUS31197 -  PPU  Access Violation

### ISSUE THREAD

**Issue by Kojikun1** [RPCS3/rpcs3#3936]
Drakengard 3 
When press the L3 + R3 for Intoner Mode, the game crash immediately
with this 
F {PPU[0x1000000] Thread (main_thread) [0x01b4c09c]} MEM: Access violation reading location 0x3b4
Tested : with DS4 Controller 
PPU : Recompiler (LLVM)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1553932/RPCS3.log.gz)

And other Access violation during gameplay the game crash randomly with
F {PPU[0x1000019] Thread (RenderingThread) [0x01394128]} MEM: Access violation reading location 0x0

if someone  wants to complete with something else

**Comment by AniLeo** [comment]
Regression since when? Because I remember this being an issue recently.

**Comment by Kojikun1** [comment]
I did not say it was regression , issues it just for regressions or point problems in emulator ?

**Comment by AniLeo** [comment]
I was just asking, since it has been brought up recently as well and no one found if it was a regression or not

**Comment by Kojikun1** [comment]
not a regression this problem already had only that no one had opened a issue

**Comment by Illynir** [comment]
Yes, no regression here. Problem has been there. It's not the only crash with access violation memory on thius game by the way. Even without press L3+R3, the game crash further.

**Comment by Kojikun1** [comment]
@Illynir Yes the game crashes with access violation memory  but i dont know but problably it not the same error its PPU but ...
F {PPU[0x1000019] Thread (RenderingThread) [0x01394128]} MEM: Access violation reading location 0x0
"RenderingThread" and "Thread (main_thread)" for press the L3 + R3
 @AniLeo I should open another issue for this other or just modify this one ?

**Comment by Illynir** [comment]
Regroup all the problem no ? Graphic also. The game is too white, shadow are missing, etc + the crashes.

With screenshot, RPCS3 log, shaderlog, etc..

**Comment by ZeratuLx** [comment]
yesterday launched, yes crashes when trying to switch to the mode of intoner (L3 + R3)

I'll get to the laptop and collect the necessary information. I'll add an additional screenshot with CPU and GPU loading

**Comment by Kojikun1** [comment]
@Illynir I do not know if you're being ironic. But one problem at a time do not you think?

**Comment by Illynir** [comment]
Not really, It's better to have a issue for all the problems than several in my opinion.

**Comment by Illynir** [comment]
![image](https://user-images.githubusercontent.com/22648460/33931816-7fc2c75e-dff1-11e7-9886-4d8ffb6c248b.png)

The menu corruption. :)

**Comment by Kojikun1** [comment]
I don't think this is a big stuff, ok the game have some graphics issues but not not related with PPU 
and this is Menu I Tested in last master now
![drakengard](https://user-images.githubusercontent.com/29433315/33932692-cf6f6eae-dfda-11e7-8ae9-ce9d17e23cf8.jpg)

**Comment by Illynir** [comment]
Oh, I am on the PR RSX Fixes, i will test on master to see if there is a regression on that.

**Comment by ZeratuLx** [comment]
![rpcs3_drakengard31](https://user-images.githubusercontent.com/1352269/33932746-3fa2801c-e00d-11e7-9c33-fed3dfaabc26.png)

Hmm, I also have everything ok with the menu, the version of the game is 1.01, but in the game itself there are problems with sound and drawdowns FPS + the game hangs when I try to press L3 + P3

![rpcs3_drakengard3](https://user-images.githubusercontent.com/1352269/33932945-c5cd0aa4-e00d-11e7-9280-c593f67d8924.png)
I also drop my logs with the folder "shaderlog" and "shaders_cache
[RCPS3.zip](https://github.com/RPCS3/rpcs3/files/1555000/RCPS3.zip)
" (RPCS3 0.0.4-6223-a1fa10ac alpha)

**Comment by Illynir** [comment]
On Master it's the same for me:

![image](https://user-images.githubusercontent.com/22648460/33933361-bfe01a86-dff5-11e7-87ea-4ae852b44117.png)

I don't understand, maybe à specific problem for this version ? Oo

**Comment by ZeratuLx** [comment]
Illynir, my gpu settings:
![default](https://user-images.githubusercontent.com/1352269/33933559-8a64f650-e00f-11e7-80fb-2353808c35b3.png)

**Comment by Kojikun1** [comment]
I use the default settings of the emulator I just changed the Renderer for Vulkan

**Comment by Illynir** [comment]
Probably a problem with specific version of game (PSN Version) or with Nvidia GPU i guess.

**Comment by ZeratuLx** [comment]
Illynir I can share the torrent on the game, from where he downloaded, there is a version in the English + all DLC and Japanese voice

**Comment by Kojikun1** [comment]
@ZeratuLx Jesus man delete this comment whe dont suport piracy

**Comment by AniLeo** [comment]
Genius... Will issue a ban on future pirate discussions

**Comment by ZeratuLx** [comment]
@Kojikun1 @AniLeo  personal messages have not been canceled yet). it's clear that piracy is not welcome. Sometimes there is no choice, when in my country this game is not on sale, and there is also no possibility to remove the rip disk.

**Comment by M220** [comment]
@Zerotulx
Yeah, you completely right
PS3 Games is not in sell in my country And our currency Can't convert to Dollar so i can't buy PS3 Games with a game store too so all my hope ( and everyone else that not that their don't want , but can't buy this games ) is one day RPCS3 can emulate PS3 Games With ease...

**Comment by M220** [comment]
@Illynir maybe you have to delete your shader  cache so new shaders can be generated?

**Comment by Atrboomy** [comment]
for those who will find this issue in future - seems that as of version v0.0.5-6626-717f2b0ac it's fixed

**Comment by Illynir** [comment]
Yes, it's fixed. You can closed. :)
