### ISSUE TITLE
RPCS3 Not Opening

### ISSUE THREAD

**Issue by ThanksLori** [RPCS3/rpcs3#3939]
Try to open RPCS3, it will not open, if I try to run it again it shows the error of another RPCS3 being open, I need to end it in Task Manager.

Only thing in log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/1564323/RPCS3.log)

I've tried updating it, doesn't work, a fresh install works, transferring over my stuff makes it do the same thing.

Specs:
Windows 10 Home 1709 16299.98
i7-6700HQ
NVIDIA 960M 4GB
8GB RAM
64-Bit

**Comment by Asinin3** [comment]
This seems more like a support question, maybe ask in discord: https://discord.me/RPCS3 #help channel and me or someone else can try and see why that is happening. if you identify what the cause is you can update your issue.
