### ISSUE TITLE
Jump tables not found spam; emulator hanging

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3942]
After starting the game, the emulator is hanging and shows nothing. After two hours of waiting, I had to stop it.
[Robert_Ludlums_The_Bourne_Conspiracy.txt](https://github.com/RPCS3/rpcs3/files/1565178/Robert_Ludlums_The_Bourne_Conspiracy.txt)

**Comment by AniLeo** [comment]
Also happens on Bourne Demo

**Comment by Deminating** [comment]
Apparently happens on UEFA Euro 2008 [BLES00227] and its associated demo [NPEB90060]

Forum has nothing report open for disc, I tested demo but no thread is open for it yet.

Log attached, issue happens regardless of PPU setting.

[UEFA Euro.log](https://github.com/RPCS3/rpcs3/files/2302423/UEFA.Euro.log)

Similar to the Bourne games, it may boot after enough time. Will leave it running and edit comment accordingly with findings.

**Comment by elad335** [comment]
Fixed Bourne Conspiracy in #6347

**Comment by elad335** [comment]
Can you retest more games which had this issue @Deminating with #6347 ?

**Comment by Deminating** [comment]
Confirmed fixed UEFA 2008 +demo boot with #6347
