### ISSUE TITLE
Unregistered PPU function. Tales of Xillia.

### ISSUE THREAD

**Issue by SinonStrike** [RPCS3/rpcs3#3945]
Tales of xillia, in early game everything is ok, but in very late, it crashes everytime after fights 
with 
F {PPU[0x1000000] Thread (main_thread) [0x00878ccc]} class std::runtime_error thrown: Unregistered PPU function

error

vulcan, win 8.1. 1080ti, i7 4790(non k).
Emulator version is https://github.com/RPCS3/rpcs3/pull/3930

Savegame for possibly testing : 
First save : early game and battles are ok
Last save : Late and crashes everytime.
[WinRAR ZIP archive.zip](https://github.com/RPCS3/rpcs3/files/1565962/WinRAR.ZIP.archive.zip)

On previous versions of emulator, everything in battles works, so not a save problem
 but random spu\mem crashes appears.

**Comment by Megamouse** [comment]
I think this can be merged with #2909
