### ISSUE TITLE
NPUA70080 White Textures und crush

### ISSUE THREAD

**Issue by ScorpionMKXL** [RPCS3/rpcs3#3946]
FOW3 E3 DEMO 2009
PPU: LLVM
SPU: LLVM
Render: Vulkan
![bandicam 2017-12-18 14-48-43-045](https://user-images.githubusercontent.com/29108928/34104941-8ead2c6c-e403-11e7-9261-bff412e4fe9b.jpg)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1567764/RPCS3.log.gz)
rpcs3-v0.0.4-2017-12-18-de5dab35_win64

**Comment by AniLeo** [comment]
This is known and expected for now, those AAA titles are unstable and broken.

There's no specific issue being reported here, this is a game report.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
