### ISSUE TITLE
Regressions with #3931

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#3947]
After #3931 was merged Persona 5 now displays the following blue background when opening the map.
![image](https://user-images.githubusercontent.com/15137035/34108913-e553f3c2-e451-11e7-88e8-8350cf053a04.png) 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1568097/RPCS3.log.gz)

**Comment by hyperspeedgx** [comment]
this pr also regressed Ninja Gaiden Sigma HUD on OpenGL, Vulkan doesn't have the issue.

![001](https://user-images.githubusercontent.com/5109698/34112732-a5264e2e-e3f4-11e7-841d-281add3efbc8.png)
![002](https://user-images.githubusercontent.com/5109698/34112733-a5446cce-e3f4-11e7-9b7b-ed5b8ba2c552.png)
![003](https://user-images.githubusercontent.com/5109698/34112734-a56284c0-e3f4-11e7-8c86-35a2f5c2a1e5.png)
![004](https://user-images.githubusercontent.com/5109698/34112736-a57fdcf0-e3f4-11e7-82c4-14faf34565f1.png)
![005](https://user-images.githubusercontent.com/5109698/34112737-a59d2012-e3f4-11e7-8417-ea25c8750f7c.png)

**Comment by kd-11** [comment]
Try https://github.com/RPCS3/rpcs3/pull/3953

**Comment by Asinin3** [comment]
That fixed the Persona 5 issue I'll test Ninja Gaiden in a sec.
![image](https://user-images.githubusercontent.com/15137035/34200693-eb7e8f8e-e5c1-11e7-900b-a07b8332443e.png)

**Comment by Kravickas** [comment]
Skate 3 glitching textures to pure white or grey.
![obrazek](https://user-images.githubusercontent.com/29986095/34294963-33a609be-e70b-11e7-8e06-14f56744e103.png)

**Comment by SakataGintokiYT** [comment]
@Kravickas 
https://github.com/RPCS3/rpcs3/issues/3952

**Comment by hyperspeedgx** [comment]
Ninja Gaiden Sigma 2 regressed on OpenGL only too and just like Ninja Gaiden Sigma Vulkan is fine.
![001o](https://user-images.githubusercontent.com/5109698/34420367-4a2680b2-ebf0-11e7-8ca7-e8480de4c901.jpg)
![002o](https://user-images.githubusercontent.com/5109698/34420382-5a22cdf4-ebf0-11e7-9fdf-95cd21782e26.jpg)
![001](https://user-images.githubusercontent.com/5109698/34420395-686a670a-ebf0-11e7-8b16-3567224b1e4b.jpg)
![002v](https://user-images.githubusercontent.com/5109698/34420399-7177836e-ebf0-11e7-94a8-58c54e823b5d.jpg)

**Comment by alex88510** [comment]
Stopped playing for a while and while trying to play ToCS1 for the 2nd round, found out that ToCS1 regress after #3931 merged. 
The whole image are blur while the text are still clear though. 

Before (this master: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7238)
![clear](https://user-images.githubusercontent.com/6214348/34670553-cf709d42-f4b1-11e7-84d5-69ec34bb6b3a.JPG)

After
![blur](https://user-images.githubusercontent.com/6214348/34670552-cf2d20da-f4b1-11e7-908b-d8a2c9c79c56.JPG)

It happens on ToCS2 also
![blur2](https://user-images.githubusercontent.com/6214348/34671019-b0d22a20-f4b3-11e7-93c3-c0d70b838c7d.JPG)

**Comment by kd-11** [comment]
@alex88510 Provide before and after renderdoc traces for trails of cold steel. You may ask for assistance on discord if you do not know how to do so.

**Comment by alex88510** [comment]
@kd-11 Not really sure how to do, but checked the documentation and played with it a bit, hopefully I get it correctly. 

Before: https://mega.nz/#!V50zTLrY!ytUSjoH42sPmgkV0zzix7M12QuC7Ld82-g51mrvlEJc
After: https://mega.nz/#!okMxWQZS!plkxngyUo_ZTpuV2aYmMBL-7VI-6iOvy0ARovNbejC8

Let me know if I did it wrong...

**Comment by PeterTh** [comment]
@kd-11 I don't know if this is helpful to you, but what's somewhat special about that context in ToCS1 and ToCS2 is that it is sampling depth from a multisampled depth buffer in order to implement the DoF.

**Comment by kd-11** [comment]
Doesnt matter, multisampling is disabled on rpcs3, rather, multisampled surfaces are rendered as resolved for technical reasons. It makes no difference. Haven't had time to investigate this particular bug at this time.

**Comment by greentop** [comment]
**Game:** ToCS2 [BLUS31597]
**OS:** Ubuntu 16.04
**Video:** Nvidia 390.25

6891323c18590cfe54f993a587500650523e4627 - blurred
71c8885678886563fe030ad965cf2a64ca497c96 - blurred
7c7cd4153efc1b5a0a39553446e9a44a108ef03b - blurred
ff0f1510e5fbd50ea5214c75c533a686bf0e9e68 - blurred
3338fdb9361f9c051e63f22de2fc11a610b6928c - blurred
6dfe32c6d2a76ca84da2a6125a755eebd2994a74 - blurred
95966a467e232f0f4c4b337927bd668d6a031925 - **Untested**
ac0022483ae92ddd82d95e90b28728aa6a87e985 - Not blurred / 6dfe32c build fix manually applied

17bfb3beaf1d2b67348d9258bfe2c5e32d5b4db6 - Not blurred

**Comment by kd-11** [comment]
Thanks. This singles out 95966a4 as the culprit.

**Comment by kd-11** [comment]
Oops. Really silly bug lol. Is OGL also affected?

**Comment by alex88510** [comment]
Tested with the master build from a few days back, and yes, it is also blurred in OGL.

**Comment by kd-11** [comment]
https://github.com/kd-11/rpcs3/commit/378f8e539f804c0eabe6791e8876019e33833ba3 Should fix TOCS. The other bugs here are already fixed iirc.

**Comment by alex88510** [comment]
Confirmed fixed on vulkan, but for OGL, when you compare the background of the same scene from both renders, it seems there is still a little bit issue on OGL. 

OGL
![ogl](https://user-images.githubusercontent.com/6214348/35919809-1c2a90aa-0c51-11e8-8512-e8d2cbc3e58a.JPG)

Vulkan
![vk](https://user-images.githubusercontent.com/6214348/35919817-24fa0cba-0c51-11e8-81da-01033f662dcc.JPG)

Look at the background on OGL and compare it with vulkan, the background on OGL is blur while vulkan is clear. Both foreground has no issues though.

**Comment by Asinin3** [comment]
Did you check how it runs on real hardware? could be depth of field or something, just not working on vulkan.

**Comment by kd-11** [comment]
Yea, its not working on vulkan from the screenshot, ogl should be the correct one. The depth resource is blank (all 0, near) in the vulkan traces that were provided to me. Traces for both opengl and vulkan should be made available for further analysis.

**Comment by kd-11** [comment]
All issues listed here are fixed in current master.
