### ISSUE TITLE
Any way to emulate the entire OS?

### ISSUE THREAD

**Issue by grepwood** [RPCS3/rpcs3#3948]
I'd like to mess around with some low-level programming, so rpcs3 seemed like an appropriate provider of a virtual environment, just so I don't break my PS3. Any chance?

**Comment by clienthax** [comment]
A lot more work is required to be able to load vsh (the xmb etc)

**Comment by grepwood** [comment]
I would love that.

**Comment by AniLeo** [comment]
Talk to Farseer if you want to help, he was working on it

**Comment by jokoputera** [comment]
can we close this thread now?

**Comment by clienthax** [comment]
Soontm.

**Comment by Megamouse** [comment]
Closing.
This ticket has zero value
