### ISSUE TITLE
Minecraft does not start

### ISSUE THREAD

**Issue by altiereslima** [RPCS3/rpcs3#3951]
Minecraft NPEB01899 and NPUB31419 more updates only works until version 0.0.3-6350 (2017-10-05)
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6350/artifacts

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1572626/RPCS3.log.gz)

**Comment by AniLeo** [comment]
#3627
