### ISSUE TITLE
Regression: Skate 3 (#3827)

### ISSUE THREAD

**Issue by kamer1337** [RPCS3/rpcs3#3952]
after #3827 the textures become white when rotate in specified direction (sun?)

![skate3_1](https://user-images.githubusercontent.com/18437274/34175274-38a7ae7e-e4fc-11e7-9326-b721fc0777bd.PNG)
![skate3_2](https://user-images.githubusercontent.com/18437274/34175276-38e4bb7a-e4fc-11e7-9795-b7ad1cbbc817.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1573012/RPCS3.log.gz)

**Comment by mchtt** [comment]
Great improvements on the 0.0.0.6-1380 build :-D thx @kd-11 
i can almost enjoy this game now 
[https://youtu.be/jSlykcHsi2Q](https://youtu.be/jSlykcHsi2Q)

**Comment by kamer1337** [comment]
fixed in #4265
