### ISSUE TITLE
semaphore_acquire() timeout ignores paused emulation

### ISSUE THREAD

**Issue by InsertK** [RPCS3/rpcs3#3954]
Pausing emulaion sometimes prints log "nv406e::semaphore_acquire has timed out.".

I think semaphore_acquire() loop needs a check about paused emulation

Title : NPUA80662[LittleBigPlanet2]
CPU : Intel i5-4570
GPU : GTX750ti 2gb

PPU Decoder : Any of them
SPU Decoder : ASMJIT
liblv2 only
Vulkan renderer

![rpcs333](https://user-images.githubusercontent.com/29673304/34197644-c48b9bd6-e5aa-11e7-85d5-254d8da8416b.png)

**Comment by kd-11** [comment]
Should be fixed in https://github.com/RPCS3/rpcs3/pull/3953
