### ISSUE TITLE
Advice on Vita emulation parts

### ISSUE THREAD

**Issue by frangarcj** [RPCS3/rpcs3#3956]
I would like to start digging on getting VITA emu working at least for some basic homebrew implementing HLE's.

Where should I start? 

Thanks in advance

**Comment by AniLeo** [comment]
Interpreter is still missing a lot of functions AFAIK, and there's zero sceGxm emulation (graphics)

**Comment by frangarcj** [comment]
I know about sceGxm missing almost everything but there's a lot of work before getting there. If I reach SceDisplay would be amazing :)

I just need confirmation that if I try to load a vita elf I can start debugging it or there is no elf loading done

**Comment by AniLeo** [comment]
It kinda works with a simple hello world, you can load other vita ELFs as well

**Comment by AniLeo** [comment]
Closing as psp2 has been removed
