### ISSUE TITLE
Games display correct graphics on 720x480 resolution but broken graphics on 1280x720 resolution

### ISSUE THREAD

**Issue by digitaldude555** [RPCS3/rpcs3#3957]
Giana Sisters Twisted Dream 1280x720 flickering between correct graphics and those shown in screenshot.
![screenshot 223](https://user-images.githubusercontent.com/26138653/34217659-b59b404a-e5b4-11e7-8b1b-faab91eb7edb.png)
720x480 Correct graphics all the time.
![screenshot 218](https://user-images.githubusercontent.com/26138653/34217701-ceebd302-e5b4-11e7-9dcb-f3606e3f8de0.png)

Frogger Hyper Arcade Edition 1280x720 flickering between correct graphics and ESRB message ingame.
![screenshot 227](https://user-images.githubusercontent.com/26138653/34217759-008f4fe2-e5b5-11e7-8224-a20720ce53af.png)
720x480
![screenshot 226](https://user-images.githubusercontent.com/26138653/34217768-091048ba-e5b5-11e7-9eb9-da7aa6bcf3b6.png)

The Swindle 1280x720 Ingame.
![screenshot 232](https://user-images.githubusercontent.com/26138653/34217792-1ac883a6-e5b5-11e7-8a00-3c6faab32cc7.png)
720x480
![screenshot 231](https://user-images.githubusercontent.com/26138653/34217800-221f036e-e5b5-11e7-9c2f-1f2979e8a57a.png)

Iron Man 1280x720
![1](https://user-images.githubusercontent.com/26138653/34217878-5d65212e-e5b5-11e7-9c94-dda40f494580.png)
720x480
![2](https://user-images.githubusercontent.com/26138653/34217893-6398997c-e5b5-11e7-991b-f9d170a6cfa7.png)

**Comment by Asinin3** [comment]
Some games require 1920x1080 as well. Derrick the Deathfin and Entiwned both flicker constantly with 1280x720 even with strict rendering mode.

**Comment by digitaldude555** [comment]
![Screenshot (2353)](https://user-images.githubusercontent.com/26138653/55674086-80d23f80-58b8-11e9-9319-a43f909df9b4.png)
![Screenshot (2354)](https://user-images.githubusercontent.com/26138653/55674087-816ad600-58b8-11e9-8c2d-0c25cc0dfb7c.png)
The graphics are fine on both resolutions now. Can be closed.
