### ISSUE TITLE
DS4 gamepad analog sticks are broken in Linux/evdev

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#3966]
Using a system with Linux Mint 18.3 and kernel 4.13.
Using version cb627a6bd7937348d9aacf908522f289ceca09eb
Tested against 3rd generation DS4 pads, though not sure if this affects other gen DS4 pads too.

Go into joystick settings, set player 1 to "Evdev / Wireless Controller" and click "Config".  Notice that the analog graphic in the lower-right now shows dead center to be in the lower-right of each diagram for both left and right sticks.  Attempting to set them again does nothing - clicking a settings button does not register, and won't allow the stick itself to be set properly.
 
Sticks were working with a build from just yesterday.  I noticed that today's commits added really nice and much-appreciated features like rumble, so hopefully this can be isolated and fixed soon.

@Megamouse can you have a look when you get a chance?  Thanks.

**Comment by Megamouse** [comment]
Start rpcs3. Go into the ds4 config window without touching the controller. Click "filter noise" once. Exit rpcs3 and upload the log

**Comment by Shoegzer** [comment]
Here you go:

E HLE: Evdev Calibration: Added axis [ 4 = RY+ ] to blacklist. [ Value = 128 ] [ Min = 0 ] [ Max = 255 ]
E HLE: Evdev Calibration: Added axis [ 3 = RX+ ] to blacklist. [ Value = 127 ] [ Min = 0 ] [ Max = 255 ]
E HLE: Evdev Calibration: Added axis [ 1 = LY+ ] to blacklist. [ Value = 128 ] [ Min = 0 ] [ Max = 255 ]
E HLE: Evdev Calibration: Added axis [ 0 = LX+ ] to blacklist. [ Value = 128 ] [ Min = 0 ] [ Max = 255 ]

Btw this was from a 2nd generation DS4 pad which also exhibits the same behavior.

**Comment by Megamouse** [comment]
why use evdev for ds4?
btw you can now set ABS_X and ABS_Y to true in evdev_positive_axis.yml and it should work

this issue can be closed I think

**Comment by Shoegzer** [comment]
Ah yes, setting those values ABS_X and ABS_Y (but also ABS_RX and ABS_RY) to "true" fixes the issue.  Thanks!  I believe we can close this out now.  

Two questions though:

1) Is there any reason these values have to be set manually or can they default to true?

2) What other choice would I have but evdev for ds4?  For example using "DualShock 4" triggers the following in the log:

E HLE: [DS4] hid_open_path failed! Reason: %S
E HLE: [DS4] No controllers found!

**Comment by Megamouse** [comment]
1. The reason is that most controllers don't need this and would therefore be broken instead. So we would have the same problem, only that you'd have to change this manually for other stuff.

2. I think the %S should be %s
Maybe try changing that in the code and then report back.
I'm not that familiar with linux and hid, but maybe you are missing the driver?

**Comment by Megamouse** [comment]
There is a driver called ds4drv. You should install it and retry with ds4 setting

**Comment by Megamouse** [comment]
this can be closed

**Comment by Shoegzer** [comment]
@Megamouse 

1. Perhaps you are right, but wouldn't you agree that a ds4 pad represents a majority of the pads rpcs3 users would use?  In that case I think defaulting these values to "true" would actually cause fewer problems for the majority of users.  I've never had any issues using the pads in other emulators like Dolphin or MAME, they "just work" there.

2.  What part of the code would that be?  Also what value would using DualShock 4 setting over evdev give me?

Also - slighly unrelated, but are you aware that evdev will not work for more than one ds4 pad connected?  Connecting a second pad, going into configuration for that pad will only register button presses from the first pad.
