### ISSUE TITLE
Regression: Graphics on Linux w/ proprietary NVIDIA drivers (#3953)

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#3971]
As requested in #3953 , I open a new issue.
Sorry @kd-11 , I can't create the renderdoc for all the versions. Just for 2 of them:
![fps 61 73 vulkan 0 0 4-50 battlefantasia npub30126 _056](https://user-images.githubusercontent.com/7478580/34308833-6846a6ee-e74f-11e7-99fd-b6833b08c77c.jpg)
https://www.dropbox.com/s/x1o7bct3ne11rd7/2017-12-22-5800-BF-VK.rdc?dl=0
Avec with a more recent version:
![fps 59 91 vulkan 0 0 4-6268-rsx_volatile battlefantasia npub30126 _054](https://user-images.githubusercontent.com/7478580/34308835-6acd615a-e74f-11e7-956d-e4343e2c99d4.jpg)
https://www.dropbox.com/s/8npl69mwqlxl2v6/2017-12-22-6268-BF-VK.rdc?dl=0

**Comment by toccata10** [comment]
By updating to a newer renderdoc, I was able to capture also this one:
![fps 59 99 vulkan 0 0 4-6226 battlefantasia npub30126 _055](https://user-images.githubusercontent.com/7478580/34309344-cb8cb43a-e751-11e7-839a-78193440ffa4.jpg)
https://www.dropbox.com/s/mmuzte2w65olra5/2017-12-22-6226-BF-VK.rdc?dl=0

**Comment by AniLeo** [comment]
That white outline ish bug I'm also getting in Naruto UNS 1 on Linux + Vulkan with NVIDIA proprietary. 

Can you verify if works on Windows?

**Comment by toccata10** [comment]
nvidia+windows: works fine

**Comment by AniLeo** [comment]
Then this isn't a regression on this game specifically, @kd-11 same issue I told you about

**Comment by AniLeo** [comment]
Fixed by #3998
