### ISSUE TITLE
Syberia 2 - No input

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#3985]
No much to say. Syberia 2 has no input, tested with xbox one controller, xbox 360 controller, and keyboard, all other games works perfect. But this can´t pass the main menu. (The game is not freezed, it runs between 58 and 63 FPS)

https://forums.rpcs3.net/thread-197584-post-293657.html#pid293657

**Comment by LuismaSP89** [comment]
Update: Tested with PR #3989 but the issue remains.

**Comment by Asinin3** [comment]
Yeah, I retested and it's broken for me as well. If you do want to play the game remember that you can just use the older build i tested with.

**Comment by Megamouse** [comment]
I don't even get to the menu

**Comment by Asinin3** [comment]
Yeah it's really unstable now but back when I tested it the game was fine 😕 I can confirm it goes to intro with: 
![image](https://user-images.githubusercontent.com/15137035/34396709-70b4c874-ebbe-11e7-8d93-935ceb08e3e8.png)
Might want to enable framelimiter as well.

**Comment by LuismaSP89** [comment]
@Megamouse Maybe i explained it wrong, with "menu" i mean the "press start" screen. Sorry.
Can´t pass that screen, because there´s no input.

You need to disable "Use GPU texture scaling" and the resolution scale must be set to "Default" (100%) else it shows graphical glitches.

**Comment by LuismaSP89** [comment]
@Asinin3 I tested it the other day with the older builds and the (RPCS3 v0.0.4-6200-8f314c51 Alpha) but the problem for me is the same, no input (only) with this game. I don´t know what is happening...

**Comment by Megamouse** [comment]
set the keyboard handler in configuration->Input/Output to Null

**Comment by toccata10** [comment]
No pb here with keyboard, evdev, ds4. Maybe a corrupted pkg ? It crashes when I try to get out of the 1st room (but it's another pb).
Screenshot:
![fps 59 87 opengl 0 0 4-6300 syberia 2 npeb02016 _002](https://user-images.githubusercontent.com/7478580/34601525-a94a208c-f1fc-11e7-886b-fb2d28c851bf.jpg)

**Comment by LuismaSP89** [comment]
@Megamouse My keyboard is set to null in the Input/output section, wich is the default config comes with rpcs3. And still the same.

@toccata10  I tested with the .pkg from the digital game and the .pkg from the disc version (Syberia collection) and in both the result is the same.

Tested too with clean install of rpcs3, i don´t know whats happening here, but i can´t pass the "press start" screen only in this game, all games i have, works very well.

**Comment by Megamouse** [comment]
you should try my cellpad PR

**Comment by LuismaSP89** [comment]
@Megamouse Errr... Im the same "LuismaSP89" that posted two times in your cellpad PR and referenced this issue in that PR... xD

And like i said on the cellpad PR, it doesn´t solve this issue.

**Comment by Megamouse** [comment]
It is really interesting because i had the same problem until i changed this config entry. Maybe i was on another branch. We'll see

**Comment by spyropt** [comment]
tested syberia II and same problem no input on my side NPEB02016

**Comment by spyropt** [comment]
@Megamouse  tested the game setting mouse and keyboard handler to null and it worked

**Comment by LuismaSP89** [comment]
@spyropt Oh man... at last! Thank you so much, it was the problem with mouse "basic" input, which comes by default. 

I´m going to post the solution with your permission in the Syberia 2 site, in rpcs3 forums:

https://forums.rpcs3.net/thread-197584-post-294399.html#pid294399
