### ISSUE TITLE
God of War Ascension hang issue

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#3986]
Not sure i understand the problem correctly
but GoW Ascension Prison of Damned Demo NPEA90123 goes menu/ingame much more willingly with LLEing libaudio, but still hangs most of the time with 
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300510
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300520

**Comment by Asinin3** [comment]
It's an issue with race conditions, always been there it took blackdaemon hours to get ingame just to record the footage for the channel which is why the status hasn't been moved yet.

**Comment by weter11** [comment]
The same problem is with Nier Replicant [BLJM60223]. And for prevent hangs I use option Strict rendering mode. It really help. But overall game is unplayable, with Vulkan backend game often crash, with OpenGL distorted colors.

**Comment by greentop** [comment]
The game ToCS2 BLUS31597 also has been producing this error while trying to load a game from the game's title window. If you wait more than one second after once the QT load save window appears, the error will be thrown and the game will then hang after once making your selection of the save file to load.

`·E 0:00:51.476544 {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300400`
[RPCS3_semaphore.log.gz](https://github.com/RPCS3/rpcs3/files/1628035/RPCS3_semaphore.log.gz)

**Comment by kd-11** [comment]
Timeout detection is currently configurable @greentop. Set it to some large value to avoid rsx giving up.
The timeout itself isnt an error, its a symptom. Real hardware also has a timeout but the duration has not been determined yet. In almost all cases you see this, SPUs are bogged down and unable to keep up with rsx which outruns them and ends up stalling. If the timeout causes problems, increase the timeout duration to several seconds (units are in microseconds). The option is called 'Driver Recovery Timeout' or something similar in rsx options.

**Comment by FrozenPyrozen** [comment]
Where I can change this value?(Cant find rsx options)
