### ISSUE TITLE
DBZ Budokai HD Resolution Scaler does not function

### ISSUE THREAD

**Issue by ShadowRaptor675** [RPCS3/rpcs3#3991]
Hello, in using this emulator to play Budokai HD I found that when using the resolution scaler to try to get a 1440p image the resulting fullscreen effect was not as crisp and seemed to be a scaled 720p image, I don't know why this is happening but I guess this "might" be the effect of having to launch the Budokai 3 section of the game through the gamefiles instead of the normal way, but that is just my guess.

https://imgur.com/a/Ec9j1

Here are a few images, hopefully showing the staircasing and aliasing that I saw but that's objective, either way it didn't render at 1440p or 4K

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1588148/RPCS3.log.gz)

And here is my log which should have everything you need

**Comment by AniLeo** [comment]
You uploaded an empty log

Make sure you read the tooltip and it's not user error before uploading a proper log, otherwise it's not an issue

**Comment by ShadowRaptor675** [comment]
Try lowering resolution scale threshold, you mean, I had it set to 1x1 and nothing changed, how can I get the program to start recording its log also?

**Comment by AniLeo** [comment]
You don't enable logging, it logs by default
After quitting RPCS3, compress RPCS3.log and upload

**Comment by ShadowRaptor675** [comment]
Do you just mean the RPCS3.txt file, RPCS3.log started existance as a compressed winrar file already

**Comment by AniLeo** [comment]
No, I mean RPCS3.log.
RPCS3 doesn't generate RPCS3.txt, only RPCS3.log and RPCS3.log.gz

**Comment by ShadowRaptor675** [comment]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1588180/RPCS3.zip)

Sorry that took so long, windows hid the .log from me, making one look like another

**Comment by kd-11** [comment]
Do you need write color buffers with this game? If not please disable that or use opengl

**Comment by ShadowRaptor675** [comment]
![budokai hd 4](https://user-images.githubusercontent.com/34873835/34449116-c6cd9fb0-ecc2-11e7-9041-5df8da1ea777.png)
Turned that off, used openGL nothing changed, still aliased as all hell on my 1440p screen
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1594007/RPCS3.zip)

**Comment by ShadowRaptor675** [comment]
I don't even think its rendering at any higher resolution than 720p or 1080p cause even when I change the amount to even something like 5K or 6K, the average rendering load reported by Afterburner isn't changing.

**Comment by kd-11** [comment]
This was already tested; the game does upscale then the engine copies over an image to the display through blit output which downscales the image again, before finally stretching it to the display area. This double resize makes it seem like its not working. To confirm, grab a renderdoc trace and step through the renders - you will see output in your preferred upscaled resolution which will suddenly get downscaled before output. For some engines this is inevitable.
