### ISSUE TITLE
Persona 5 BLUS31604 Error (sorry for posting here, main forum post hasn't been accepted)

### ISSUE THREAD

**Issue by Insomiac234** [RPCS3/rpcs3#3992]
Sorry for posting tis here, but my post hasn't been accepted in the main forums yet. 
I get this error on the BLUS31604 version of Persona 5

Unhandled Win32 exception 0x0000005.
Segfault writing location 0000000000000000 at 0000000000000000.
Instruction address: 0000000000000000.
RPCS3 image base: 0000000000010000.

Based on my research, it's from the OpenGL renderer, and since I'm testing this on an average laptop most people have, (runs games pretty well, like CS:GO, Battlerite and Outlast) I can't use Vulkan and I don't even have it as an available renderer.
When I set my renderer to Null my PS3 game opened, but all I could see was white. Just white.

If I can somehow get a 3rd renderer to use without having to buy a gaming PC is appreciated.
This is only a test run though, I'm not actually gonna try and beat the game. Thanks for any help given.

(LOG POSTED BELOW)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1589461/RPCS3.log.gz)

**Comment by AniLeo** [comment]
https://forums.rpcs3.net/thread-197751.html

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
