### ISSUE TITLE
Kingdom Hearts 1.5 HD Remix , Kingdom Hearts 1 Final Mix Atlantica world unplayable

### ISSUE THREAD

**Issue by lukas116** [RPCS3/rpcs3#4001]
Hello, i have used the Rpcs3 emulator to play the Kingdom Hearts collection in HD for a while now since RPCS3 hopefully will be the definitive version to play these games, on my playthrough of the first game( Kingdom Hearts 1 Final Mix) ,i fond a glitch on the world Atlantica where the screen would show the last screen that blurred (paused or saved) my guess is that water effect in the game, its just the game rendering the game image on a flat poly then distort this poly to create a water distortion effect, i have seen more people with the same glitch so i belive, this is not a user glitch.

Here is a screenshot of what it looks on my version of RCPS3 (RPCS3 v0.0.4-6277):
https://user-images.githubusercontent.com/34944315/34443537-fecba22c-ecae-11e7-9f24-3e9d57980084.png

Here is a screenshot of what it should look like:
https://user-images.githubusercontent.com/34944315/34443865-38cef1ac-ecb1-11e7-9bfe-693695de0f61.png

My specs:
NVIDIA GeForce GTX 1060 6GB
Intel Core i5 6400 @ 2.70Ghz-3.24Ghz
Windows 10 Pro 64-bit
1 TB
8,00GB DDR4

**Comment by Asinin3** [comment]
Those screenshots are from completely different locations, also duplicate of #3134 please close this.

**Comment by lukas116** [comment]
Thanks for awsering! this is acutually my first post here so i did not know that people already posted it here, but they are from the same world , the reason that they look completely diferent is because like i said in the post, "screen would show the last screen that blurred" in the first screenshot i had paused at gummi ship session, so when i was in the world it would show that instance, but well i hope they fix it soon.
