### ISSUE TITLE
Regressions with #4005

### ISSUE THREAD

**Issue by greentop** [RPCS3/rpcs3#4009]
**Ubuntu 16.04 - Nvidia 387.34**
**Game:** ToCS2 BLUS31597

**Issue:** The game fails to boot, with error message `F {PPU[0x1000000] Thread (main_thread) [0x010a4578]} MEM: Access violation reading location 0x20`. This is a regression caused by changes from https://github.com/RPCS3/rpcs3/pull/4005

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1595574/RPCS3.log.gz)

**Comment by nicesn2000** [comment]
Dead Space 2 Regression
PPU LLVM:
F {PPU[0x1000012] Thread (EARS::Online::NetServiceHttps::StartupThread) [0x01a13f78]} MEM: Access violation reading location 0x0
PPU precise/fast is fine (intro_new.game.infinite.loading)
![ds2_mem_access_violation](https://user-images.githubusercontent.com/16824470/34465221-20e64de6-eeba-11e7-806a-029a1cde2a64.png)
[RPCS3[DeadSpace2].log.gz](https://github.com/RPCS3/rpcs3/files/1595582/RPCS3.DeadSpace2.log.gz)
