### ISSUE TITLE
Dead Space 2 Infinite Loading

### ISSUE THREAD

**Issue by newsource-trem** [RPCS3/rpcs3#4013]
Hi, me very need your help! Im hope, im in correct place..

Im trying to run Dead Space 2 (EU) with no luck. Doesn't matter, im pressing New Game, or trying load game...im have the same result - INFINITE LOADING....

Any ideas what is it and how fix it?

When menu loads, im see this code:
E {PPU[0x1000016] Thread (EARS::PDLC::ProcTrophiesThread) [0x00a14f4c]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0x214a2c1c, count=*0xd0107d70)

When im pressing "New Game" or "Continue", in logs nothing happens, but keeps this, what im wrote above...

**Comment by elad335** [comment]
@newsource-trem you need to post rpcs3.log.gz file for the issue to be valid

**Comment by AniLeo** [comment]
This is not a support forum, this is an issue tracker. Read the guidelines.
