### ISSUE TITLE
NieR [BLUS30481] Vulkan crash (Assertion Failed)

### ISSUE THREAD

**Issue by Kosyne** [RPCS3/rpcs3#4015]
Version: RPCS3 v0.0.4-6295-198e9dce
Game: NieR [BLUS30481]

16gb Ram
GTX 770 4GB
i7 6700k

---

### Summary

Semi-randomly, during the opening sequence (camera panning across the snowy buildings, etc), the game will completely freeze. I HAVE managed to get to the portion where I control the character ONCE. This is tested across multiple builds, but I have listed the one I most recently confirmed this issue with.

(Edit: Reading around, it seems this is caused due to the combination of NVIDIA hardware and Write Color Buffers)

If any more information is required, let me know and I can fetch that and report back.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1597128/RPCS3.log.gz)

[config.yml](https://github.com/RPCS3/rpcs3/files/1597137/config.yml.txt)

**Comment by kd-11** [comment]
The cause of the nier crash is known. A fix is in the works.

**Comment by Kosyne** [comment]
Yeah, I found that out just now actually, looking around the discord. Thanks, I really appreciate the work you guys are doing!

**Comment by matiastulio** [comment]
Hi, could you try again with 0.0.4-7423?

**Comment by Kosyne** [comment]
Just tested.

In my first test, I crashed in about the same place as usual.
In my second, I was able to get ingame properly, but crashed in the second cutscene (Where he reaches out for the book).

Seems to keep happening at cutscenes, might be related to how very, very off sync the character dialogue is?

Anyway, logfile was so huge I had to snip the last several lines from it, but I also have the console output from RPCS3:

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1598667/RPCS3.log.zip)

[Console Log](https://github.com/RPCS3/rpcs3/files/1598668/log2.txt)

**Comment by kd-11** [comment]
Like I said, the cause of the crash is known and will be patched soon.

**Comment by Kosyne** [comment]
Ok, tested again and 9ec23371927a87813518896b11632202d43fd5df seems to fix the freezing issue I was having. I'm closing this issue for now.

As for other issues with this game:

* I still get fairly frequent semaphore timeouts, particularly in gameplay (i.e. it happens less in cutscenes it seems?)

* During cutscenes, voice+sfx are very, very desynced. This is fixed somewhat by limiting framerate to 30, but lag/semaphore timeouts cause it to go further out of sync.

Are any of these warrant creating a new issue?

**Comment by kd-11** [comment]
No, performance issues are not real issues unless they're known to be regressions. As for semaphore timeouts, hardware tests need to ne written; according to envydocs the 'semaphore' timeout on nvidia chips is currently unknown. You can configure it via config file to a lower value ro avoid the 1s freezes.
