### ISSUE TITLE
SoulCalibur 2 HD [NPUB31366] doesn't seem to upscale 

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#4017]
When trying to upscale the game in 4k, it seems it stays at 720p.
My resolution scale threshold is at 1x1.
When I compare with the same game in Dolphin (4k too), there's a big difference.
Screenshots
rpcs3:
![selection_059](https://user-images.githubusercontent.com/7478580/34490948-d71d1478-efe1-11e7-97f9-e0c2b1e9d2cc.jpg)
dolphin:
![dolphin 5 0-6074 jit64 dc vulkan experimental hle fps 60 - vps 60 - 100- soulcalibur ii grseaf _062](https://user-images.githubusercontent.com/7478580/34490973-f35c9c3a-efe1-11e7-94d7-c6116bde16f4.jpg)
Another one:
rpcs3:
![selection_061](https://user-images.githubusercontent.com/7478580/34490982-fc012036-efe1-11e7-9818-ea30fd22f825.jpg)
dolphin:
![dolphin 5 0-6074 jit64 dc vulkan experimental hle fps 60 - vps 60 - 100- soulcalibur ii grseaf _063](https://user-images.githubusercontent.com/7478580/34491002-09768292-efe2-11e7-8449-2c068aec7cc9.jpg)
My log file:
[RPCS3.log-Soul2UpscalePb.gz](https://github.com/RPCS3/rpcs3/files/1598054/RPCS3.log-Soul2UpscalePb.gz)

**Comment by kd-11** [comment]
Upsacling works, but then the game copies the upscaled data directly to the display buffer which is 720p and then stretches it again to your 4k screen, because thats how it was designed to work on the ps3. Happens in every game where you see complaints about scaling not working; it is working but the final image is downsampled first to ps3 display size then stretched to fill the screen. You can compare with actual 720p and see a difference. Not much can be done for these games without intrusive hacks.

**Comment by toccata10** [comment]
Thanks for the explanation.

**Comment by toccata10** [comment]
Just for documentation purpose: screenshots with no upscaling (=720p)
![selection_065](https://user-images.githubusercontent.com/7478580/34512249-5c192322-f061-11e7-934f-e4b8be9772f6.jpg)
![selection_068](https://user-images.githubusercontent.com/7478580/34512252-5dc1e2f4-f061-11e7-8e79-c55d12bff8a6.jpg)

**Comment by deatrocker** [comment]
upscaling not working. this is 450% scaling (NPEB01828) you clearly can see here is 720p, not 4k+

![Rpcs3 Screenshot 2022 07 15 - 00 38 38 06](https://user-images.githubusercontent.com/20367262/179091308-f159a3f1-33d9-4a8e-9509-3509cedf44e8.png)

**Comment by deatrocker** [comment]
Upscaling not works, this is "450% scaling". But its 720p by fact. i7700k, 3060 RTX
![Rpcs3 Screenshot 2022 07 15 - 00 38 38 06](https://user-images.githubusercontent.com/20367262/179091497-4ca8c83e-6482-4dbe-9629-ed99f2360f0f.png)
