### ISSUE TITLE
God of War: Collection crash on title screen with USB gamepad  

### ISSUE THREAD

**Issue by weter11** [RPCS3/rpcs3#4023]
I tried many different options, but only now I understand that segfault in emulator happened because my gamepad is in USB port. Emulator hangs with:
`RPCS3: Fatal error. Segfault reading location 0000000000000000 at 0000000000f07f37`
This don't pappen with keyboard, but I don't play games with it. And it is only in this game. All other games working well. My gamepad is Gembird JPD-FFB-A. Vibration don't work in Lubuntu 18.04, but Windows systems I don't use.

**Comment by LeChuckye** [comment]
Worked fine for me with the latest build, and Xbox One Controller

**Comment by weter11** [comment]
After #5611 game no longer crash after title screen.
Thanks to all devs for their hard work on the emulator.
