### ISSUE TITLE
sys_lwcond: Verification failed (e=0x57) Gundam Breaker 2 [BLJS10286]

### ISSUE THREAD

**Issue by Kojikun1** [RPCS3/rpcs3#4024]
Gundam Breaker 2 Crash in intro

F {PPU[0x1000001] Thread () [0x01388d44]} class std::runtime_error thrown: Verification failed (e=0x57): 
(in file Emu\Cell\lv2\sys_lwcond.cpp:116)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1600891/RPCS3.log.gz)

**Comment by scribam** [comment]
@Kojikun1 This issue doesn't seem to appear anymore (see https://forums.rpcs3.net/thread-174736-page-2.html), can you confirm it?

**Comment by Kojikun1** [comment]
I dont have this game anynome i can not confirm anything this game install sometimes and get error in others. and this game spaw the same log always sys_lwcond.cpp think

**Comment by Kojikun1** [comment]
@scribam I tested now i last master 0.0.5-6814 still crash with the same error. This Game sometimes
very rare can install but still crashing with
F {PPU[0x1000001] Thread () [0x013a5d44]} class std::runtime_error thrown: Verification failed (e=0x57): 
(in file Emu\Cell\lv2\sys_lwcond.cpp:116)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2021441/RPCS3.log.gz)

**Comment by elad335** [comment]
Retest with ppu threads number 1 in config.

**Comment by Kojikun1** [comment]
Yes works thankyou. can i close this issue ?

**Comment by elad335** [comment]
No, thats a workaround and not a proper fix, I was curious how it would affect this issue.

**Comment by Kojikun1** [comment]
Works Perfectly now goes in game the game is now almost playable with little graphic gliches

**Comment by elad335** [comment]
@Kojikun1 Can you verify that #5265 fixes it?

**Comment by Kojikun1** [comment]
sorry I'm away from my computer
I'm traveling now

**Comment by AkagiShiroe** [comment]
@elad335 was the game playable(at least in-game)? since i luckily get it booted and.. i got fatal exception in the middle of playing.. (u know the first stage in city).

**Comment by Kojikun1** [comment]
@elad335 this pr https://github.com/RPCS3/rpcs3/pull/5265 fix this issue but when enable Write Color Buffers the emulator just crash in intro. in this pr

**Comment by elad335** [comment]
Fixed by #5314
