### ISSUE TITLE
JJBA:ASB Attached fragment shader is not compiled.

### ISSUE THREAD

**Issue by memeboyz** [RPCS3/rpcs3#4028]
RPCS3 Version:
v0.0.4-7455 (19d181f) Alpha [2018-01-04]

Specs:
CPU - Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz 2.40GHz
Ram - 8.00 GB
OS - Windows 7 Professional SP1 x64
HDD - 750 GB
GPU - Intel HD 4400

The game I'm trying to run is Jojo's Bizarre Adventure: All Star Battle running as a disk game. I can load it through the first couple of logos and copyrights, but after it gets through an opening scene displaying all the characters, it suddenly just stops and black screens, yet it shows a number of fps. (I don't know if that helps or not) The large amount of error lines I get after this happens is shown:

`
E {PPU[0x1000000] Thread (main_thread) [0x0098f25c]} 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000092] Thread (TrophyInstallThread) [0x00615904]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0xfa2348, arg=*0x284a2a10, options=0x1)
E {PPU[0x1000000] Thread (main_thread) [0x00513048]} cellNetCtl: cellNetCtlNetStartDialogLoadAsync(param=*0xd0010610)
U {PPU[0x1000000] Thread (main_thread) [0x008c5ec8]} sceNp TODO: sceNpManagerGetOnlineId(onlineId=*0xd00105b0)
E {rsx::thread} RSX: Failed to compile shader: ERROR: 0:149: 'Error' : Cannot offset into the vector 
ERROR: 0:149: 'assign' :  cannot convert from 'const 4-component vector of float' to '3-component vector of float'
ERROR: 0:152: 'Error' : Cannot offset into the vector 
ERROR: 0:152: 'assign' :  cannot convert from 'const 4-component vector of float' to 'float'
ERROR: 0:167: 'Error' : Cannot offset into the vector 
ERROR: 0:167: 'assign' :  cannot convert from 'const 4-component vector of float' to 'float'

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Attached fragment shader is not compiled.
'
`

Could it be an issue with Intel's compilers? I'm not very tech savvy when it comes to coding, please help!

**Comment by AniLeo** [comment]
Yes, Intel's drivers are utterly bad. Are you at least using latest drivers?

If this is an Intel driver bug, you have to wait for kd-11 to evaluate whether this is worth a workaround or not

**Comment by memeboyz** [comment]
Yes, I’m using the latest drivers. Thanks for the quick reply and I guess ill try to google around for some fixes or something.

**Comment by AniLeo** [comment]
Leave this open, there's a possibility it gets fixed

**Comment by memeboyz** [comment]
Understood.

**Comment by kd-11** [comment]
Need the log file for this. Reopen if you have it although intel's glsl compiler is an embarassment to graphics technology.
