### ISSUE TITLE
Discrepancies in Sonic Unleashed

### ISSUE THREAD

**Issue by ScorchEmber256** [RPCS3/rpcs3#4033]
Tested on latest #2481 
Sonic Unleashed crashes in different parts of the game depending on which version.

BLES00425 and NPUB31204 reaches the main menu and crashes before ingame.
![bles00425](https://user-images.githubusercontent.com/13728013/34646310-4056626a-f3b0-11e7-944b-759961792159.PNG)

![bles00425 png loading screen](https://user-images.githubusercontent.com/13728013/34646371-b082a3a4-f3b1-11e7-972f-e837f2b5a374.PNG)
Logs:
[TTY.log](https://github.com/RPCS3/rpcs3/files/1609471/TTY.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1609472/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1609473/RPCS3.log.gz)

NPEB01347 crash before reaching the title screen.
![not working](https://user-images.githubusercontent.com/13728013/34646398-568068b8-f3b2-11e7-9262-0c6136705620.PNG)
Logs:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1609476/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1609477/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/1609478/TTY.log)

Settings:
![settings](https://user-images.githubusercontent.com/13728013/34646409-b0df335c-f3b2-11e7-8075-97a0bebff03f.PNG)
![settings 2](https://user-images.githubusercontent.com/13728013/34646410-b118b352-f3b2-11e7-83b5-fe61c99ae862.PNG)

**Comment by JackONeill12** [comment]
Also important to note. Precise SPU Interpreter goes to title screen while fast interpreter and recompiler are stuck on the loading screen before.

**Comment by elad335** [comment]
this is fixed for a long time now.
