### ISSUE TITLE
Diablo 3 Graphical Issue

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#4035]
###  Issue
Color is not rendering correctly, missing colors are displayed as red hue. 

### System
Status: Gameplay 30fps, goes ingame but renders red hue everwhere.
Proc: 2x Intel E5 2670 2.7Ghz AVX 32 logic cores, 16 threads utilized
RAM: 24Gb
Disk: 1Tb Hitachi
GPU: GTX 1060 6gb
RPCS3 Conf: Default
RPCS3 Ver: 0.0.4-6300
OS: Windows 10
Affects: OpenGl and Vulkan

### Captured Info
This is a screencap
![red_hue](https://user-images.githubusercontent.com/13552004/34755404-bed02b1c-f5fe-11e7-8d62-cdc47c9306f3.jpg)
In RPCS3 OpenGl, rendering is at approximately at 30fps. But when renderdoc is used in the emulator, its now rendered at 0fps with a latency of 12k because RenderDoc only utilizes 1-2CPU core thus limiting the RPCS3 run into 1-2 cores as well. In contrast, RPCS3 alone could utilize 16 cores.

This is the RPCS3 log
[rpcs3_log_red_hue.txt](https://github.com/RPCS3/rpcs3/files/1617487/rpcs3_log_red_hue.txt)

This is the RenderDoc
[InStart.rdc](https://ufile.io/07ycu) (RenderDoc is only stored for 30 days)

This is how it looks like in the video of a Youtuber https://www.youtube.com/watch?v=dC9nxzMXcIs

@AniLeo Anything I could have missed?

**Comment by AniLeo** [comment]
BlackDaemon who recorded is part of the team, he's aware.

You do need to submit a proper report for the issue to be useful though, being that these are graphical issues, you'll need to submit a RenderDoc capture in addition to the normal requirements as well.

You can just reopen this one after editing it, don't need to submit a new one.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by jobs-git** [comment]
@anileo I could not reopen it since github says it was closed by an author. Only an author could reopen it. If there might be no addtl info needed, could we reopen it? Regards

**Comment by AniLeo** [comment]
Thanks, I have reopened the issue.

As for RenderDoc, in the future you can use Legacy OpenGL Buffers (config.yml) to speed up performance when running it attached to RenderDoc.

**Comment by jobs-git** [comment]
I will keep that In mind in the future, If there is still a need for more debug info, just let me know.

**Comment by Asinin3** [comment]
Fixed with #4382 
![image](https://user-images.githubusercontent.com/15137035/38240158-5b2af3ec-371e-11e8-9dd7-ea60fedd4855.png)

**Comment by AniLeo** [comment]
Closing as solved
