### ISSUE TITLE
The Blur Bug in ToCS II

### ISSUE THREAD

**Issue by liududu** [RPCS3/rpcs3#4037]
**@kd-11** The **blur bug** still appers when I recently play this game.
**Here's the picture:**
![default](https://user-images.githubusercontent.com/20725799/34730394-3b07f242-f59a-11e7-8bf2-e17bc2c758c5.PNG)
I know you got a huge pull about the graphic issues.
But this bug is still here,maybe there was something wrong with the calculation that the blur should be.
It's now obvious over blur.
I think you would consider to fix this after your first PR this year is merged.

Leave a message if you notice this.A lot of thanks. **:D**

**Comment by liududu** [comment]
By the way,I'm using the latested commit on AppVeror.That **RSX:improvement** version.

**Comment by SakataGintokiYT** [comment]
@liududu 
https://github.com/RPCS3/rpcs3/issues/3947

**Comment by liududu** [comment]
so I guess I shall close this?

**Comment by SakataGintokiYT** [comment]
yes close this issue.
