### ISSUE TITLE
Syberia 2, can´t run twice

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#4039]
Strange problem with Syberia 2, it can be opened and played normally, but if you close rpcs3 (or the game) and try to run again, it shows this error:

F {PPU[0x1000002] Thread (te_engine_auto_check) [0x002b0344]} MEM: Access violation writing location 0x3c3f7879

You must restart your computer in order to play it again. I wonder if the problem is related with rpcs3 and RAM ¿?

All the other games i have works ok with this.

**Comment by spyropt** [comment]
try this settings it should work

ppu/spu interpreter (precise)
spu threads 2

**Comment by LuismaSP89** [comment]
Works with that config, but the fps fall down from 60 to 15 fps and it´s unplayable.

**Comment by scribam** [comment]
@LuismaSP89 Is it still an issue with master (737db90058beb93d83d12ea94c405476ee594bfc)?

**Comment by LuismaSP89** [comment]
@scribam Not yet, but now has a different error, this time can be opened, but freezes on the "Loading precompiled shaders" screen.

F {PPU[0x1000000] Thread (main_thread) [0x0051ba90]} MEM: Access violation reading location 0x72736973

**Comment by scribam** [comment]
Can you please add a log file? These information are not enough to help.

**Comment by LuismaSP89** [comment]
@scribam Sure, here it is, sorry for not provide it before.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1993090/RPCS3.log.gz)

**Comment by Asinin3** [comment]
I'm getting the same issue on latest master.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2216153/RPCS3.log.gz)

**Comment by LuismaSP89** [comment]
For me now, with latest builds (Using 0.0.5-7117) can run twice and thrice

 (Using SPU and PPU LLVM) but after some more tries the game hangs with blackscreen, and show me in the log (This errors change each time):

F {PPU[0x1000000] Thread (main_thread) [0x007b51a4]} MEM: Access violation writing location 0x10
F {PPU[0x1000002] Thread (te_engine_auto_check) [0x007b5654]} MEM: Access violation writing location 0x3c3f7879


[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2216300/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
No longer an issue.
