### ISSUE TITLE
Failed download compatibility database!

### ISSUE THREAD

**Issue by Oky12** [RPCS3/rpcs3#4046]
I am posting this issue here. because in the forum rpcs3 cannot solve it
hi everyone. i need help. in version rpcs3 v0.0.4-6307 there is a compatibility feature. I want to try the feature but it must be downloaded first. at the time will be downloaded. the warning appears like in the screenshot. I do not understand what it means. Please help me!!!!!

![screenshot 136](https://user-images.githubusercontent.com/30838114/34880425-f796ccea-f7e2-11e7-86f5-ba5182ba8500.png)

**Comment by elad335** [comment]
https://indy.fulgan.com/SSL/openssl-0.9.8r-x64_86-win64-rev2.zip

**Comment by AniLeo** [comment]
That's an old openssl version, current is 1.1.0

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker **is not the place to ask for support** or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by Kosyne** [comment]
It's not surprising people are having issues with this. The error message could be changed to point users in the right direction and/or have it documented in the quickstart guide.

**Comment by AniLeo** [comment]
That's the idea, but no one has looked into it yet. If someone wants to provide instructions on how to properly install latest OpenSSL on Windows, feel free to

**Comment by StarWolf3000** [comment]
Why not offer an option to let the emulator download (a recent) OpenSSL for the user and put it in the correct path? This way you can prevent problems with the "not allowed to export cryptographic mechanics" like the US has, bc you're not bundling the files with the emulator itself, like mentioned in #4129.

**Comment by windyboy1704** [comment]
https://indy.fulgan.com/SSL/openssl-1.0.2p-x64_86-win64.zip
The working version of OpenSSL. No more SSL handshake error

**Comment by UroshUchiha** [comment]
The link has changed. that particular zip has been moved to the archive and can be found here now: https://indy.fulgan.com/SSL/Archive/openssl-1.0.2p-x64_86-win64.zip

**Comment by AniLeo** [comment]
RPCS3 doesn't work anymore with versions below 1.1.0.
The SSL DLLs are in the appveyor artifacts list on every build.

**Comment by UroshUchiha** [comment]
Ah I wasn't aware of that. I downloaded the latest RPCS3 build last night after a while and noticed that this option didn't work. Wasn't aware that there are SSL DLLs on appveyor, I'll look into it again later today.

Thanks for your quick reply as always. Any plans to include these DLLs in the download directly from the website or a custom message when the error happens?

**Comment by klepp0906** [comment]
even with those newly linked dlls from 9/19/18 - same error.  I had this working way back when.  grrr
