### ISSUE TITLE
Degraded perfomance on Windows 10.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4047]
Symptoms: the perfomance was degraded with comparison with W7 (settings was the same).
Anything i run is suffering from HUGE fps drop. Even when shaders is NOT compiling.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1626828/RPCS3.log.gz)

nvidia driver is 388.71

https://youtu.be/w5rJVZMTufk - 02:20, shaders not compiling as you can see, FPS around zero

**Comment by kd-11** [comment]
That seems to be specific to your setup. I've heard similar complaints and reinstalling windows fixes it for some users. There isnt much we can do about stuff like that.
