### ISSUE TITLE
Deathspank - Broken polygons

### ISSUE THREAD

**Issue by Krusher97** [RPCS3/rpcs3#4054]
Windows 7 Ultimate 64-bit SP1
Intel Core i5 6500 @ 3.20GHz
NVIDIA GeForce GTX 750 Ti

The character arms are not connected to his wrists and certain models suffer from polygon tearing or under specific conditions, the player model when its standing on a collectable flower and the witch model when moving around it.

![rpcs3_2018-01-14_02-21-23](https://user-images.githubusercontent.com/25664221/34909990-43fcbd94-f8a4-11e7-82db-c76087478a43.png)
![rpcs3_2018-01-14_02-22-39](https://user-images.githubusercontent.com/25664221/34909991-4a28f0f2-f8a4-11e7-8310-3d70a6acceef.png)
![rpcs3_2018-01-14_02-24-34](https://user-images.githubusercontent.com/25664221/34909992-5046e444-f8a4-11e7-9af9-03ef3aa025ba.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1628739/RPCS3.log.gz)

**Comment by kd-11** [comment]
Likely fixed, update or close this issue.

**Comment by Krusher97** [comment]
Seems to be fixed. Closing.
![rpcs3_2018-09-23_22-30-43](https://user-images.githubusercontent.com/25664221/45930664-b2209900-bf80-11e8-929b-73b8e899c7ff.png)
