### ISSUE TITLE
corrupted PARAM.SFO makes RPCS3 not start

### ISSUE THREAD

**Issue by nojus64** [RPCS3/rpcs3#4056]
Hardware:
Ryzen 1600 (overclocked)
Sapphire Radeon HD 7950 Dual OC Boost
Windows 10
Note that I am perfectly able to use the emulator without any problems.
Version tested on:
RPCS3 v0.0.4-6314-2053de088 Alpha

Game tested on:
BLUS31604 - Persona 5

RPCS3 does not start if a game contains a bad param.sfo file. The process rpcs3.exe stays alive making you incapable of starting it again without killing the process before. It's not capable of creating log files.
This should be easily recreateable by modifying param.sfo in any way possible.

example of broken file:
[BLUS31604_PARAM_broken.zip](https://github.com/RPCS3/rpcs3/files/1629365/BLUS31604_PARAM_broken.zip)

**Comment by Zangetsu38** [comment]
issue know, just backup you save, clean save, restart game, recreate news save, and after past file save backup inside

**Comment by nojus64** [comment]
I think you misunderstood something.
I am able to play games fine. It's just that if one game contains a corrupted .sfo file rcps3 WONT start. no error messages. no log files. some people said that there was a sfo checker to avoid this (that probably broke).
