### ISSUE TITLE
Shadows of the damned have no longer correct gamma

### ISSUE THREAD

**Issue by Parthorisian** [RPCS3/rpcs3#4059]
**Shadows of the damned** now have incorrect gamma colours displaing. Oobjects/models in menu/game are red or wrong coloured now.

[rpcs3.log](https://www.mediafire.com/file/tqizz6hr123l4t5)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1630315/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/1630316/TTY.log)

[q](http://www.mediafire.com/view/t9y31t8lv5fl6t6/q.png)
[qe](http://www.mediafire.com/view/0y9hxewwd7xjkkf/qe.png)
[qw](http://www.mediafire.com/file/prlrdafgvxpaana/qw.png)
[qwe](http://www.mediafire.com/view/g76o3gxd0vjx5xj/qwe.png)

**Comment by elad335** [comment]
log? screenshots? description? something!?

**Comment by Parthorisian** [comment]
[RPCS3.log](http://www.mediafire.com/file/tqizz6hr123l4t5/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1630474/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/1630475/TTY.log)
![q](https://user-images.githubusercontent.com/35437970/34928256-57832a90-f9cd-11e7-87f3-266400147b9b.png)
<img width="584" alt="qe" src="https://user-images.githubusercontent.com/35437970/34928257-57a2ae7e-f9cd-11e7-816b-560f7854b4bb.png">
![qw](https://user-images.githubusercontent.com/35437970/34928258-57bc35e2-f9cd-11e7-8cb2-ff530d401008.png)
<img width="640" alt="qwe" src="https://user-images.githubusercontent.com/35437970/34928259-57d7c154-f9cd-11e7-88e1-5a0ec2fd2525.png">

**Comment by isshininu** [comment]
Strict rendering mode enabled?

**Comment by Parthorisian** [comment]
No. But just two weeks before all colors was correct

**Comment by isshininu** [comment]
You'd better try again with STRICT mode enabled.
Unity-based games required this option in most situations.

**Comment by Parthorisian** [comment]
:( PS3 and STRICT mode looks something different way

**Comment by JamieeLee** [comment]
Not sure if the game uses pre and post exposure but it looks like the whatever changed its just not returning the correct value for nvidia or amd.

**Comment by kd-11** [comment]
Grab rdc traces before and after the regression. You may ask for help on how to do it on discord or someone who knows how to use renderdoc can do it for you.

**Comment by Psycho-A** [comment]
Seems like it's Unreal Engine 3 game, and I see typical UE3 bugs on RPCS3, like it was on Silent Hill Downpour and other games.

**Comment by Parthorisian** [comment]
Psycho-A commented

> Seems like it's Unreal Engine 3 game, and I see typical UE3 bugs on RPCS3, like it was on Silent Hill Downpour and other games.
Yep, following [wikipedia page](https://en.wikipedia.org/wiki/Shadows_of_the_Damned) **Shadows of the Damned** is powered by**Unreal Engine 3**

**Comment by Psycho-A** [comment]
I'm really waiting when developers will focused on UE3 games...

**Comment by AniLeo** [comment]
Try fixing them yourself if you're in a hurry 🤔🤔🤔

**Comment by Megamouse** [comment]
renderdocs:

https://mega.nz/#!a3p2SLrK!1Vqj1y3SITMYAWNf8Y5jby3C8rC7sf7nAgWbsLwqa0Q

**Comment by kd-11** [comment]
Will track with main ue3 tracker for now.

**Comment by isshininu** [comment]
And what to do with that?

**Comment by kd-11** [comment]
Wait. More rdcs will not make a difference as the issues are well known.
