### ISSUE TITLE
Trails of Heroes Legend of cold steel 2

### ISSUE THREAD

**Issue by jizang58** [RPCS3/rpcs3#4064]
Hi Guys,
I am trying to run Trails of Herloes legend of cold steel 2 npub31836 the undubbed version on rpcs3 the latest version, i installed the latest software update from the playstation website, but the game only starts a big screen and afterwards closes it again, i dont know what the mistake is, i hope someone can look at it,

Down i copied the console outputs, maybe it can help.

Console comment
S LDR: Boot from gamelist per doubleclick: done
U {PPU[0x1000000] Thread (main_thread) [0x010a1d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x0109d828]} sysPrxForUser TODO: sys_prx_load_module_list(count=7, path_list=**0xd0010bfc, flags=0x0, pOpt=*0x0, id_list=*0xd0010bdc)
S {PPU[0x1000000] Thread (main_thread) [0x0109d828]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0109d828]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0109d828]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/libresc.sprx
E {rsx::thread} RSX: OpenGL: initialization of glDepthBoundsEXT failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetTextureImage failed.
E {rsx::thread} RSX: OpenGL: initialization of glTextureBufferRange failed.
E {rsx::thread} RSX: OpenGL: initialization of glTextureBarrierNV failed.
U {PPU[0x1000000] Thread (main_thread) [0x01097598]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd0010910, option=*0x0, waitForEvent=0)
E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/libnet.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/libusbd.sprx
U {PPU[0x1000000] Thread (main_thread) [0x010fed80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x010fed80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x010fed80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x010fed80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x010fed80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x0109d870]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0109d870]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
S {SPU[0x2000000] Thread (CellSpursKernel0)} SPU: SPU Database initialized...
S {SPU[0x2000000] Thread (CellSpursKernel0)} SPU: SPU Recompiler (ASMJIT) created...
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/libadec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/libat3dec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/libatxdec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/libatrac3plus.sprx
E {PPU[0x1000000] Thread (main_thread) [0x0109d780]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x0109d790]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
S {Audio Thread} XAudio 2.9 initialized
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/libpngenc.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0109ae20]} cellScreenshot TODO: cellScreenShotSetParameter(param=*0xd000fb80)
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/libssl.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0109d808]} sys_prx: Loaded module: /dev_flash/sys/external/libhttp.sprx
E {PPU[0x1000000] Thread (main_thread) [0x01097080]} sceNpTrophy: sceNpTrophyCreateContext CONF does not exist
E {PPU[0x1000000] Thread (main_thread) [0x01097080]} 'sceNpTrophyCreateContext' failed with 0x8002291b : SCE_NP_TROPHY_ERROR_CONF_DOES_NOT_EXIST [1]
E {PPU[0x1000000] Thread (main_thread) [0x0045ec94]} 'sys_ppu_thread_join' failed with 0x80010002 : CELL_EINVAL [1]
U {PPU[0x1000000] Thread (main_thread) [0x0109d848]} sys_prx TODO: _sys_prx_unload_module(id=0x2300c500, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x0109d848]} sys_prx TODO: _sys_prx_unload_module(id=0x2300c400, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x0109d848]} sys_prx TODO: _sys_prx_unload_module(id=0x2300c300, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x0109d848]} sys_prx TODO: _sys_prx_unload_module(id=0x2300c200, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x0053f668]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK
S sys_process: Process finished

/consolecomment

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
