### ISSUE TITLE
Dante's Inferno some sort of issue

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#4066]
I don't know which kind of issue is this
I played up to this place with no problems (more or less) this issue prevents it from being playable
here's the screen according to walkthrough i must turn the lever t o turn the huge demon statue
but it doesn't react on pressing R1 and doesn't even highlights for me to press it like any other object ingame
![22](https://user-images.githubusercontent.com/7060586/34973544-57d8a85e-fa99-11e7-8f31-0ab26fba8c49.jpg)
tried many revisions even the very old ones to confirm it's not a regression
and here's the savefiles of the game the one which is closest ot the issue named
"Descent to Violence"
https://mega.nz/#!WZgWUKTS!yv_nfeKRO1FhybZEc1g68GemVkKbtdqvxg9KNzCvBcM

**Comment by sftlbcn** [comment]
https://github.com/RPCS3/rpcs3/issues/3464

**Comment by hcorion** [comment]
Yeah, this is a duplicate issue, please close.
