### ISSUE TITLE
0.0.4-6329 has no picture

### ISSUE THREAD

**Issue by KujiKita** [RPCS3/rpcs3#4068]
When I launch games such NPJB00435, picture doesn't appear and no framerate (It doesn't seen in header)

Short system summary:
Intel i5-4570
16GB RAM
Nvidia GTX 960
Windows 7

**Comment by AniLeo** [comment]
![image](https://user-images.githubusercontent.com/10283761/35018443-77c9c244-fb19-11e7-870f-aaf11a3803f6.png)

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
