### ISSUE TITLE
Disable on-disk shader cache option [Question]

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4069]
Good to see such an useful option, and I would suggest to extend it into more functional. For now the emulator doesn't write and read cache files. Okay, good. But can it also perform the behavior that was in old emulators of the last summer, where shader compiling program used some different on-the-fly program? That would help to keep already compiled shaders as well as keep complied videodriver's GLCache from overwritting and have smooth running.

**Comment by kd-11** [comment]
The shader (de)compiling and caching system has remained unchanged at its core for years. The only thing added was the on-disk cache to reduce stutter as shaders became more and more complex in nature, making drivers slower at compiling them. Other minor bugfixes have been implemented, but nothing like what you have described has ever existed on rpcs3. Also, if you're asking for the old shader system back, then no, it was buggy and incomplete and is not even compatible with rpcs3 in its current state.

**Comment by kd-11** [comment]
Resolving since the suggestion is not possible without maintaining a separate set of backends.
