### ISSUE TITLE
[BLES02237] Unimplemented syscall 462

### ISSUE THREAD

**Issue by xiangzhai** [RPCS3/rpcs3#4071]
Hi rpcs3 developers,

rpcs3 [435ea8d55379a887442916ff309c6f1e28fc9652](https://github.com/RPCS3/rpcs3/commit/435ea8d55379a887442916ff309c6f1e28fc9652) is pretty cool about binary translation through LLVM! but unimplemented syscall 462:

```
U {PPU[0x1000000] Thread (main_thread) [0x028c10e4]} HLE TODO: Unimplemented syscall syscall_462 -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x028d0e64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x028d10bc]} sys_prx TODO: _sys_prx_register_library(library=*0x28d36a0)
...
U {PPU[0x1000000] Thread (main_thread) [0x028dcd8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
...
U {PPU[0x1000000] Thread (main_thread) [0x028d161c]} sys_prx TODO: _sys_prx_register_module()
E {PPU[0x1000000] Thread (main_thread) [0x00134758]} sys_mmapper: sys_mmapper_allocate_address(size=0x20000000, flags=0x200, alignment=0x10000000, alloc_addr=*0xd00204e0)
E {PPU[0x1000000] Thread (main_thread) [0x00134778]} sys_mmapper: sys_mmapper_allocate_address(size=0x20000000, flags=0x200, alignment=0x10000000, alloc_addr=*0xd00204e0)
E {PPU[0x1000000] Thread (main_thread) [0x028c7948]} 'sys_mmapper_map_shared_memory' failed with 0x80010010 : CELL_EALIGN [1]
F {PPU[0x1000000] Thread (main_thread) [0x028c792c]} St13runtime_error thrown: Unregistered PPU function
```

So I checked the [COMPATIBILITY](https://rpcs3.net/compatibility?g=pro+evolution) for [BLES02237](https://forums.rpcs3.net/thread-185614.html), then I realized :)

But how to fix? The [patch](https://github.com/RPCS3/rpcs3/pull/2737/) is not related to this bug.
I want to dig into rpcs3, please teaching me, thanks a lot!

Regards,
Leslie Zhai - https://reviews.llvm.org/p/xiangzhai/

**Comment by isJuhn** [comment]
Syscall 462 does not exist on retail consoles, so it being unimplemented would not affect game emulation. The game is broken by something else. That specific error in your log is because of using the PPU LLVM decoder. Using PPU Fast interpreter would possibly make it go further. But as seen on the compatibility list, it was recently tested and did not work.

**Comment by xiangzhai** [comment]
@isJuhn thanks for your kind response! but Game compatible is just like Magic to me :) it is easy to [make GCC compatible](https://reviews.llvm.org/D39712) how to dig into it?

**Comment by isJuhn** [comment]
I don't understand your question. You should join the RPCS3 discord server for faster and easier communication: https://discord.me/RPCS3
