### ISSUE TITLE
Mortal Kombat (Demo) - "Unimplemented"

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#4075]
Black screen and:
> ·F 0:05:01.279828 {PPU[0x1000000] Thread (main_thread) [0x014ad20c]} class std::runtime_error thrown: Unimplemented
> (in file Emu\Cell\Modules\sceNpSns.cpp:156)

[Mortal_Kombat_(Demo).txt](https://github.com/RPCS3/rpcs3/files/1640748/Mortal_Kombat_.Demo.txt)

**Comment by AniLeo** [comment]
Proper networking switch (on/off) should be implemented IMO instead of stubbing these to work

If we tell sceNpSns there's no network at once, it won't try to reach this unimplemented function.

**Comment by Zangetsu38** [comment]
Fix by stub function
![image](https://user-images.githubusercontent.com/5261759/35080447-e376c880-fc0d-11e7-827f-28eb2dcce6aa.png)
