### ISSUE TITLE
AMD OpenGL driver crashes with AMD RX Vega GPU

### ISSUE THREAD

**Issue by Xerrok** [RPCS3/rpcs3#4080]
RPCS3 0.0.4-6314-2053de088 (and many others)

I have an AMD RX Vega 64 GPU and I get lighting flickering in Vulkan and bad performance (0,5 - 1 seconds freezes) with driver crashes in OpenGL. ssshadow replied to me in the forums, that it could be a Vega issue, because no team member has one, that's why I'm creating this issue.
[Here](https://www.youtube.com/watch?v=93kYpa21F24) you can find a video of the Vulkan issue.
I'm using an AMD Ryzen 1800x (Hyperthreading disabled), AMD RX Vega 64 with the driver version 17.12.2, 16GB Ram 2800MHz and everything is installed on a SSD operating in Windows 10 Pro.
I've tested the same game (Demon's Souls EU and US version btw) with the same specs, but with my old AMD R9 290 and everything works fine.

Here is the log:
[RPCS3_RX_Vega64_Vulkan.zip](https://github.com/RPCS3/rpcs3/files/1642866/RPCS3_RX_Vega64_Vulkan.zip)

**Comment by kd-11** [comment]
How does opengl crash? Any error message? Not sure what we can do for that specific issue, there are already workarounds for bad vega drivers to prevent crashing.

**Comment by Xerrok** [comment]
No error message at all, it's just like if your OC of your graphics card is bad and crashes the driver.
The screen(s) go black and after several seconds the desktop and applications are normal except of some which doesn't responds anymore and needs to be restarted, like RPCS3, the Radeon Software, Browsers, etc.

**Comment by kd-11** [comment]
Thats odd. Try using older drivers then, maybe something from the 17.11.x series.

**Comment by Xerrok** [comment]
Will try it this evening when I'm home and report back.

**Comment by Xerrok** [comment]
Tried drivers version 17.11.1 and 17.11.4, and both had the same issues in Vulkan and OpenGL as 17.12.2.
[Here](https://youtu.be/18r-kWjnJZU) is the video showing OpenGL crashing the video drivers.

**Comment by kd-11** [comment]
That's definately not normal. I'll ask if any vega users can run some tests. If its a common thing it needs reporting to AMD. Opengl should not cause tdr to kick in. Any other games affected by this? Or do you only have access to demon's souls?

**Comment by Xerrok** [comment]
I have Persona 5 here, will test it.

**Comment by Xerrok** [comment]
Persona 5 didn't even start, only black screen.
But I've tested Catherine and it worked like a charm.

**Comment by kd-11** [comment]
According to other testers, opengl crash is confirmed - can be skipped by pressing start to skip the intro where the character walks into the light.
Vulkan on vega56 works okay with no flickering.

The opengl issue may be caused by a spec violation on rpcs3 side in conjunction with a driver bug on AMD side where the driver executes a malformed command instead of returning an error. I'll look into this.
As for vulkan, use the default scaling threshold of 16. I see you have it set to 24. That will affect the game's HDR calculations and could easily cause black screen or flickering as in your case.

**Comment by Xerrok** [comment]
Thanks for the response.
Yes I know that I can skip the intro but I thought I report this. Maybe there will be similar other crashes like this, later in the game.
I have the lighting flickering with Vulkan on nearly every combination of settings, even with the default value of 16 for the scaling treshold.

**Comment by kd-11** [comment]
How about cpu settings? Those will also affect graphics output. Set preferred threads to auto (DeS will not work properly with 1)

**Comment by Xerrok** [comment]
Even with different CPU Settings. The interpreters make the game more laggy and still have the lighting flickering.

**Comment by Xerrok** [comment]
ok... the flickering is gone with the newest RPCS3 Version... only the bad performance remains

**Comment by kd-11** [comment]
For ryzen:
Performance tips for ryzen
1. Re-enable HT
2. Enable the manual thread scheduler since windows has really bad ryzen scheduling
The lowest framerate (unless you mean performance drops related to compiling shaders) should be around 29 fps when looking at castle boletaria. All other areas hold about full speed. SPU threads Auto, lower SPU priority and SPU loop detection on.

**Comment by Xerrok** [comment]
Both of the tips didn't change the performance.

**Comment by kd-11** [comment]
Its more of a general rule for rpcs3 on ryzen really. You need the thread scheduler enabled and HT enabled for good performance on windows.
What kind of performance are you getting anyway? I know there are issues with rpcs3 vulkan performance on AMD drivers but it should not be that bad.

**Comment by Xerrok** [comment]
I get between 10 - 20 FPS in Demon's Souls in the Boletarian Palace (The first Arcstone level).
But I've just read, that it is a common issue for everyone. Catherine for example is working fine.

**Comment by kd-11** [comment]
No its not normal. With ryzen I have 27-28 fps minimums overlooking the entire castle. This is the slowest part by far. Even an i3 does not dip below 20 very often.

**Comment by Xerrok** [comment]
The FPS Counter says 24-30 FPS, but it feels like 12 FPS. I can't even time a normal dodge roll.

**Comment by kd-11** [comment]
Set framelimiter to off. It runs a bit slower cpu side but it should not be that bad

**Comment by Xerrok** [comment]
I've already set the framelimiter to off
Here are my settings for Demon's Souls:
![cpu](https://user-images.githubusercontent.com/10530989/35481704-22956350-0429-11e8-9a69-6e3b23010995.JPG)
![gpu](https://user-images.githubusercontent.com/10530989/35481705-284f6430-0429-11e8-80ab-6aa9dfa089f1.JPG)

**Comment by AniLeo** [comment]
Does the Crash still happen in latest master with OpenGL? (You may want to check with and without GPU texture scaling as well)

**Comment by Xerrok** [comment]
Nope, it isn't crashing anymore (even with and without GPU texture scaling).
Thanks for that :)
