### ISSUE TITLE
Sonic Unleashed [BLUS30244] PPU LLVM Errors

### ISSUE THREAD

**Issue by slashiee** [RPCS3/rpcs3#4087]
RPCS3 v0.0.5-7077-f0a9799b4 Alpha | HEAD
Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz | 4 Threads | 15.94 GiB RAM | AVX+ | TSX

Compatibility threads: [US](https://forums.rpcs3.net/thread-187276-post-297444.html) | [EU](https://forums.rpcs3.net/thread-184131.html)

Issues that can't be accessed easily on master will not be mentioned.

Missing Byte on Save ID
---
On PPU Recompiler LLVM, the save ID is cut off by one byte. (BLUS30244 -> BLUS3024) Both PPU interpreters do not have this issue.

![2018-04-22_00-53-24](https://user-images.githubusercontent.com/15317421/39092654-92c56d84-45c7-11e8-8363-1c56edfb8253.png)

Both logs go to the world map.
[PPU Interpreter Fast](https://github.com/RPCS3/rpcs3/files/2173121/RPCS3-SaveFast.log.gz)
[PPU Recompiler LLVM](https://github.com/RPCS3/rpcs3/files/2173119/RPCS3-SaveLLVM.log.gz)

Quickstep black screen while moving
---

Whenever Sonic is moving past his walking animations, the game will have a high tendency of black screening when doing the quick step move.

[Video Demonstration](https://streamable.com/za0bs)

Log goes until multiple quick steps in Holoska (Cool Edge) Act 1 day.
[PPU Interpreter Fast](https://github.com/RPCS3/rpcs3/files/2173122/RPCS3-QSFast.log.gz)
[PPU Recompiler LLVM](https://github.com/RPCS3/rpcs3/files/2173124/RPCS3-QSLLVM.log.gz)

Enemy Crash
---

Whenever an enemy spawns, the game will crash with an access violation.

![2018-07-07_15-02-37](https://user-images.githubusercontent.com/15317421/42414990-f13c7dc4-81f6-11e8-8744-a5e609b1269b.png)

[Video Demonstration](https://youtu.be/bJKg0ApFJxM)

Log goes until the first event setter in Apotos (Windmill Isle) Act 1 night.
[PPU Interpreter Fast](https://github.com/RPCS3/rpcs3/files/2173130/RPCS3-EventFast.log.gz)
[PPU Recompiler LLVM](https://github.com/RPCS3/rpcs3/files/2173127/RPCS3-EventLLVM.log.gz)

**Comment by NeoSlude** [comment]
This guy is using a pirated version of the game. Doesn’t deserve help

**Comment by AniLeo** [comment]
Don't spam.

**Comment by slashiee** [comment]
SPU ASMJIT freeze at title screen is solved with PR #4422, however interpreter fast still freezes.

**Comment by NeoSlyde** [comment]
https://youtu.be/HQed0SzHTuA

**Comment by NeoSlyde** [comment]
Using https://github.com/RPCS3/rpcs3/pull/4422
Works great can load some stages but freeze after 1-2 seconds in stage
If we remove Cooledge textures and geometry (credit to BeatZ) it can run infinitely and great
Also freeze if it’s 60 fps
So need to lock to 30fps

**Comment by slashiee** [comment]
With the merge of #4844, I have updated the main post of this issue with issues specifically related to the PPU LLVM Recompiler that was discovered while testing with that PR. All the logs are done on the latest master.

**Comment by MarioSonic2987** [comment]
With #5749, the game doesn't go blackscreen when doing quicksteps (L1/R1 buttons) and doesn't crash in night stages.

![image](https://user-images.githubusercontent.com/20027681/54821930-e3fe8800-4ca3-11e9-8ec7-f0e2baf3ecf5.png)
![image](https://user-images.githubusercontent.com/20027681/54822319-1066d400-4ca5-11e9-880e-70e89a27f7b3.png)

**Comment by slashiee** [comment]
can confirm, these issues are fixed. will close issue when pr is merged into master
![2019-03-22_17-09-03](https://user-images.githubusercontent.com/15317421/54858965-487e0f00-4cc5-11e9-989d-35b9b4c30214.png)
