### ISSUE TITLE
 Problems with Persona 5

### ISSUE THREAD

**Issue by Zeckrom66** [RPCS3/rpcs3#4096]
When I run the game, I get an error           
 F LDR: Failed to load RAP file: /dev_hdd0/home/00000001/exdata/EP4062-NPEB02436_00 GPERSONA5X000001.rap
E LDR: SELF: Can't find RAP file for NPDRM decryption!
E LDR: SELF: Failed to load SELF file metadata!
F LDR: class std::logic_error thrown: fs::file is null

**Comment by Zangetsu38** [comment]
Missing rap, close issue please

**Comment by kd-11** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
