### ISSUE TITLE
sys_spu_thread_group_set_cooperative_victims

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#4098]
Leaving this issue opened to document which games are known to call for it, for when someone wants to implement it.

**List of games:**
- Deadpool
- Men in Black: Alien Crisis
- Transformers: Fall of Cybertron
- J-Stars Victory VS
- The Last of Us
- God of War: Ascension "Prison of the Damned"
- Binary Domain
- Teenage Mutant Ninja Turtles: Mutants in Manhattan
- R.U.S.E.
- CS:GO
- Far Cry 4

**Comment by isJuhn** [comment]
Binary Domain also uses this syscall, it's in loadable.

**Comment by isJuhn** [comment]
Teenage Mutant Ninja Turtles: Mutants in Manhattan uses this syscall too.

**Comment by isJuhn** [comment]
MLB 15: The Show also has this

**Comment by elad335** [comment]
just a FYI, this system call came from cellSpursAttributeEnableSystemWorkload.

**Comment by dio-gh** [comment]
Not really sure if there's a point in keeping this thread open, considering that the discord bot now has a syscall tracking feature. It's not like the listed games hard-require this syscall either, several on the list work or at least go ingame. There's no point in opening and upkeeping a thread for every single missing syscall.

Unless there's a special reason that this syscall is special and worths keeping track of separately, this ticket is closeable.

**Comment by Kravickas** [comment]
FC4 is ''ok'' with #7557

**Comment by AniLeo** [comment]
Closing as implemented
