### ISSUE TITLE
Persona 4 Arena not running 

### ISSUE THREAD

**Issue by Jessomadic** [RPCS3/rpcs3#4104]
Said gaming marked as Playable does not run on newest PS3 Firmware

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by Zangetsu38** [comment]
@Jessomadic  game works full speed
![image](https://user-images.githubusercontent.com/5261759/35341955-2ab7a944-0127-11e8-86f0-718cea40da96.png)
