### ISSUE TITLE
hle: cellGameContentPermit does not support installation cancellation

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#4107]
**cellGameContentPermit** will throw an exception if the install process is canceled

```
·W 0:02:13.108630 {PPU[0x1000016] Thread (Thread09) [0x0072d1d0]} cellGame: cellGameContentPermit(contentInfoPath=*0x67a460, usrdirPath=*0x67a4e0)
·W 0:02:13.109260 {PPU[0x1000016] Thread (Thread09) [0x0072d1d0]} PPU: 'cellGameContentPermit' aborted

·F 0:02:13.109482 {PPU[0x1000016] Thread (Thread09) [0x0072d1d0]} class std::runtime_error thrown: cellGameContentPermit(): failed to initialize directory '/dev_hdd0/game/BLJS10174DAT'
```

Some games like Accel World - Awakening of the Blue Sky allow for canceling the installation process, as installing the game to the hard drive is an optional process.

![image](https://user-images.githubusercontent.com/10283761/35358177-a95c277c-014d-11e8-95d6-09eaef618e95.png)
_(X) - Cancel_

**Comment by dio-gh** [comment]
Needs retesting.

**Comment by AniLeo** [comment]
Fixed on master
