### ISSUE TITLE
Missing TSX Support

### ISSUE THREAD

**Issue by Enverex** [RPCS3/rpcs3#4114]
May be Linux specific. Built with GCC 7.2.1.

Processor is an i7-5775C which, according to Intel supports TSX - https://ark.intel.com/products/88040/Intel-Core-i7-5775C-Processor-6M-Cache-up-to-3_70-GHz

Linux confirms this via cpuinfo which lists HLE and RTM available. Running two TSX testing programs also confirms the presence of TSX.

For some reason RPCS3 isn't seeing TSX support. The terminal line shows:
```
RPCS3 v0.0.4-6355-c8965564e Alpha | master
Intel(R) Core(TM) i7-5775C CPU @ 3.30GHz | 8 Threads | 7.54 GiB RAM | AVX+
```

**Comment by hcorion** [comment]
Are you sure tsx wasn't disabled via microcode? Wikipedia says some early broadwell CPUs got that disabled.

**Comment by Enverex** [comment]
Certain. All the tests show that it's enabled now, within the OS (that's what my tests were for above). If it's disabled then it won't even show in cpuinfo.

**Comment by JamieeLee** [comment]
While the processor does support it , it can return the result of the cpu supported feature Unless your motherboard allows it to be enabled it is typically disabled and blocked in linux and window for that processor do to its instability and possible data corruption .   

Snip
Intel Broadwell-H and Skylake-S/H have critical errata that causes HLE
to be extremely dangerous to use on those processors, resulting in
unpredictable behavior (i.e. process crashes when you are lucky, data
corruption when you are not) when hardware lock-elision is enabled in
glibc/libpthread.

Broadwell errata BBD50 (desktop/mobile), BDW50 (server):

	An HLE (Hardware Lock Elision) transactional region begins with
	an instruction with the XACQUIRE prefix.  Due to this erratum,
	reads from within the transactional region of the memory
	destination of that instruction may return the value that was
	in memory before the transactional region began

According to the Intel errata list, a firmware fix is possible, but I
have no idea whether it is done by toggling a boot-locked MSR that
disables HLE, or through a microcode update.  The MSR is more likely,
but if it is a microcode update, it is going to be as much of a hazard
as the Haswell one that disabled TSX+HLE.

I recommend that we extend the HLE blacklist in glibc to also include
CPU signature 0x40671.  This will disable HLE on Xeon E3-1200v4, and
5th-generation Core i5/i7.  These processors are supposed to already
have TSX disabled (errata BBD51/BDW51).

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800574

while it pertains to linux, it seem's your chip supports it but do to buggy microcode its blocked or disabled.

**Comment by Enverex** [comment]
Further reading of the bug you've linked to shows that if it's disabled via Microcode, it won't show in cpuid. It's running the latest microcode and TSX still works in other test programs I've run that use TSX and it's still listed in cpuid. Also running GCC's native info command still also shows that GCC is enabling HLE and RTM for this processor. Therefore I think the discussion you linked to wasn't corrected (or at least never actually happened, as Intel never actually disabled TSX on this processor).

**Comment by kd-11** [comment]
```
bool utils::has_rtm()
{
	// Check RTM and MPX extensions in order to filter out TSX on Haswell CPUs
	static const bool g_value = get_cpuid(0, 0)[0] >= 0x7 && (get_cpuid(7, 0)[1] & 0x4800) == 0x4800;
	return g_value;
}
```
rpcs3 disables TSX on all haswell due to the erratum listed above. This is to avoid trying to actually run tsx ops on unpatched cpus.

**Comment by Enverex** [comment]
This CPU is Broadwell rather than Haswell. Can you make this a build flag or at least toggleable somewhere? Blocking TSX on CPUs that are patched and thus will work seems like unnecessary collateral damage.

For anyone else's benefit regarding which CPUs are broken and which aren't, Intel updated the broken CPUs on ARK and they are listed as "TSX-NI = No" so you can use that as an authoritative reference.

**Comment by kd-11** [comment]
Compile time flag or option makes more sense than manually parsing a list of cpu names to determine if cpuid flag should be ignored.
