### ISSUE TITLE
[Linux] Event/EVDev Device Gamepad Assignment

### ISSUE THREAD

**Issue by Enverex** [RPCS3/rpcs3#4116]
Not sure when this changed as it used to be fine, but now RPCS3 is using a different way to "see" the controllers. Historically it would just show me the name of the controller. That, whilst a bit confusing if you had multiple controllers of the same type (as they'd have the exact same name) worked fine and was persistent.

The issue now is that assignment seems to be done based on the EVDev ID which isn't static, it can change on reboot. So there's a good chance your controllers won't be assigned next time you reboot and start RPCS3.

Additionally, the automatic assignment of controllers is... a bit weird. Rather than it assigning the controllers incrementally to players 1 to 4, it seems to assign the last controller to all 4 players. Image showing this below:

![image](https://user-images.githubusercontent.com/958670/35447591-039e1c46-02b0-11e8-9d47-c58255418cd2.png)

Here you can see the controllers are event IDs 5, 6, 7 and 8. But for some reason the gamepad interface has decided rather than assigning ID 5 to player 1, 6 to player 2, etc, it has simply assigned the last controller (ID 8) to all 4 people.

Even if you fix it, it'll likely break itself again on a reboot in future when the event IDs of the controllers change, which will then result in it mapping the last controller detected to all 4 players again.

**Comment by kd-11** [comment]
Can confirm, evdev needs pads to be reconfigured for rpcs3 every reboot. Its kinda annoying

**Comment by Megamouse** [comment]
This will have to wait until jarves has finished his stuff.

If it's easy enough i can provide a fix maybe tomorrow

**Comment by Megamouse** [comment]
ugh I can't find a way to get a stable unique id of those controllers.
I guess evdev is kinda.... useless in that regard.

**Comment by Enverex** [comment]
How did it work prior to when the event IDs were added next to the controller names?

**Comment by Megamouse** [comment]
It wasn't working before since there was no real way of distiguishing the controllers.

**Comment by randomstuff** [comment]
The way it's done in dolphin is that a device number is added to each device name. The full identifier is in the form "$backend/$number/$deviceName" where `$number` is [chosen](https://github.com/dolphin-emu/dolphin/commit/788e19f54d86ba45cdc83d39c0488b17aa1d00dd#diff-766fe5f4c3684c597c10bd18606179caR150) unique per `(backend, deviceName)` pair.

**Comment by Megamouse** [comment]
I'll leave this to @jarveson and close my PR in order to prevent conflicts.
Be patient guys

**Comment by Megamouse** [comment]
I'll assume this is not an issue anymore. Please open a new issue with a new explanation if there is still a problem.
