### ISSUE TITLE
Shaders Compilation Issue

### ISSUE THREAD

**Issue by AkagiShiroe** [RPCS3/rpcs3#4126]
I don't know if this gonna help but here some testing and issue in old hardware
My Spec are an old Intel I3 CPU 3,0ghz (westmere, 2 physical core + 2 virtual) with 4GBx2 DDR3(8GB) and Geforce 9600 GT 512 (partial/half OpenGL 4.x support)
-somehow old GPU like mine which isn't fully supporting 4.30 can run RPCS3 in 10-20fps but when Shader compilation start (particularly blur/distored image shader) the compiler just crash due too much instruction (limitation i think? or bug? issue? i don't know) here some log
(just read the end line for shader compilation since i test some games like homebrew DOOM as well who give significant boost today compared to old build)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1673518/RPCS3.zip)
using this build: rpcs3-v0.0.4-2018-01-22-4f017947
(keep the good work guys i even didn't believe it anymore how RPCS3 will growth from now)

**Comment by sirdanielk** [comment]
Whatever kind of nvidia cheap card will be sufficient and you will get better results than with 9600

**Comment by kd-11** [comment]
This PR https://github.com/RPCS3/rpcs3/pull/4127 has work reducing amount of code generated by shader emitters. Maybe it helps your problem, maybe it doesnt, but trying to squeeze the emulator to work on really old hardware will not be viable long term.

**Comment by kd-11** [comment]
Please retest with current master

**Comment by AkagiShiroe** [comment]
@kd-11  thank you, the performance getting better after that PR but still sadly.. shader compilation are crash when "reflection" stuff are requested (i recognize this after testing to change from Miku to Meiko or Rin since both have object that reflect image like metal), pushing old hardware wasn't good but thanks~ i got 2-5 FPS+(and stable gameplay) with this minor fix.
best example for this issue are Project Diva F 2nd demo 2nd song Tsuki Kirai with default character(which crash from the begining of song) and Hello,wolker when luka tried to wipe chalk marker from chalkboard (the game instantly tried to compile some shader which sadly not compatible and crash instantly with my old hardware)... here some log (crash in Tsuki Kirai):
[tsuki kirai.zip](https://github.com/RPCS3/rpcs3/files/1684300/tsuki.kirai.zip)
(the differences between old build and this new build are, game succesfully compile a lot shader before crashing compiling this shader, from log.. i see around 14x are success)
(crash when luka wipe chalkboard, but the performance increase a lot in this build):
[luka.zip](https://github.com/RPCS3/rpcs3/files/1684317/luka.zip)
(crash when trying swap character into meiko):
[meiko.zip](https://github.com/RPCS3/rpcs3/files/1684321/meiko.zip)
anything similiar between those three? if this can help your development thank and for reading this.. i hope RPCS3 in future can run most games without issue.
( i don't mind RPCS3 didn't support old hardware, im here for testing the software)

**Comment by kd-11** [comment]
retest, probably fixed now with new recompiler generating shorter shaders.

**Comment by AkagiShiroe** [comment]
@kd-11 
Great There's a Huge Improvement i've felt here, there's not even a slight stutter anymore from shader compilations but still those reflection stuff really need more instruction > .< than what my GPU could handle,sadly its gated by my GPU which only support partial 4.x (yeah some extensions are missings)
so here's my result after testing from RPCS3 0.0.5-7101-65d270e5d Alpha,
you won't believe me.. but i did play this game under 10-20fps with 10 year old NVIDIA 9600 GT 512MB and damned 4-thread intel core i3 540 3,0ghz(westmere).

Compatible Song(Stable running 10-20 fps):
Tutorial Songs (Ievan Polka)
World's End Umbrella (8-16fps,Smooth but sometimes in-game video didn't play at all.. but overall.. there's not anymore stutter and jitter in video)
Negaposi Countinues (14-23fps)
Unhappy Refrain (7-13fps)
Nyanyanyanyanyanyanya! (10-21fps, whole song is a damned cute "nya" line)
Stay with me (8-14fps)
ACUTE (9-14fps)


Not Compatible (Crash When Compiling Vertex Shaders):
Senbonzakura (Crash from beginning)
Sweet's Devil(crash after hand scene from beginning)
Rin~chan Now!(crash after miku[actor 1] and rin walking together)
Dream-Eating Monochrome Baku(crash from beginning)
Tokyo Teddy Bears(crash when rin start to fall [in deep red sea?] )
Tell Your World (Crash from beginning)
Continuing Dream (Crash from beginning)
Sadistic Music Factory(Crash in beginning after staring on lock [and jail?] for fewsecond)
Black Rock Shooter (Crash after few second when miku sing first line)
God-Tier Tune (Crash when "kamikyo" line)
Tengaku (crash even before i start the song > .<, yes i still use original Kagamine Rin Skin,also changing skin didn't help. maybe guitar are the culprit lol)
Odds & end (crash after staring into.. a display and computer?)
Nostalogic (Crash from another vertex shaders again)
The MMORPG Addict's Anthem (crash after a few second in beginning)
World's End Dance Hall (crash after a few second in beginning)
Kagamine HachiHachi Flower Fight (Crash from beginning)
Glasses (yes.. its crash from beginning again.. possible because of glasses [because it have reflection?])
Monochrome Blue Sky (same like glasses.. maybe because reflection? damn, i wish i could skip this vertex shader or replace it as dummy)
Freely Tomorrow (crash from beginning)
Ashes To Ashes (crash when "saraba" line)
Remote Controller (crash from beginning)
Hm? Ah, Yes. (crash from beginning)
What Do You Mean!? (crash even before i start the song)
Urabandoment (crash after a few second from beginning, maybe because the car?)
Summer Idol (7-14fps, when song allmost end(when actor 1 and actor 2 trying to hold hand each other).. yes.. its crash, sad)
Fire Flower (crash from beginning)
DYE (crash after a few second from beginning)
Time Machine (crash from beginning, i really want to play this one T~T after Senbonzakura)
Weekender Girl (crash from beginning)
Melancholic (its crash even before i start the song > .<)
Secret Police (crash after a few second too.. good grief, i give up at this point)
Cat Food (crash after a few second too, this is the last song i tried)
Diva Room (crash even before entering(its still loading, and its show 0(2) : warning C7568: #version 430 not fully supported on current GPU target profile .. holy crap)

**Comment by AniLeo** [comment]
Closing since its quite an old issue and falls outside of required OpenGL level of support
