### ISSUE TITLE
Regression: Yakuza 3 Demo (#3772)

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#4128]
commit 51891039 makes yakuza 3 suffer from unknown color artifact
also i found that reverting line
if (pitchs[index] < required_color_pitch)  back to
if (pitchs[index] < 64) fixes this for both backends
that how it looks on master
![1](https://user-images.githubusercontent.com/7060586/35532334-f3e90dea-054a-11e8-964d-3ee325e738d1.jpg)
and how it should look after fix and looked before it was broken
![5](https://user-images.githubusercontent.com/7060586/35532335-f8a695b4-054a-11e8-87c2-1515b8a2364d.jpg)
please take a look

**Comment by Xcedf** [comment]
Little update:
It seems also affects Gran Turismo HD Concept
broken revision
![22](https://user-images.githubusercontent.com/7060586/35533476-c0008e1e-054e-11e8-8931-435edcbbc330.jpg)
the revision before the broken one
![13](https://user-images.githubusercontent.com/7060586/35533503-cfa2f53c-054e-11e8-93bf-4621139eb070.jpg)

**Comment by kd-11** [comment]
Just FYI, that fix actually just disables the whole block since pitch will never be less than 64. Pitch 64 seems to be allowed for some corner cases but I'm not enabling it as viable until I find the registers affecting its validity.

**Comment by Xcedf** [comment]
I see, anyway i reported that's all i can do.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/4136 has a potential fix for this. Retest with that build.

**Comment by Xcedf** [comment]
Yes fixed, thanks alot

**Comment by AniLeo** [comment]
Fixed by #4136
