### ISSUE TITLE
Regression: #3858 causes slowdown on Windows 10 + Vulkan.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4130]
This is a follow-up of my previous bug request. https://github.com/RPCS3/rpcs3/issues/4047

I have identified a pull request that causes this - https://github.com/RPCS3/rpcs3/pull/3858 

I have recorded two videos - one with previous PR (#3842) and with 3858.
#3842 
https://youtu.be/CTjBh20y8x0

After #3858 
https://youtu.be/rLnyREQA_-0

**Comment by kd-11** [comment]
The PR isnt the cause of the regression, something else is. That PR only changes order of unprotecting memory and does it correctly without hacks. Is your Demons Souls install modified in some way? I certainly do not have the issue shown in your video nor have I heard of similar complaints. The only way to check what is wrong with your setup involves you setting up a development environment and running a profiler to determine where all the lost time is going. Visual studio 2015 would work well for this purpose; should you choose to go ahead, visit the development channel on discord for further assistance.

**Comment by isshininu** [comment]
Okay, i have created a perfomance analyze of process with VS.
[RPCS3perfn.zip](https://github.com/RPCS3/rpcs3/files/1683547/RPCS3perfn.zip)

also log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1683553/RPCS3.log.gz)

**Comment by kd-11** [comment]
Profile refuses to load symbols but thats because of different paths on every machine and it does not seem to be portable. From the log, not much seems to be off with the exception of preferred spu threads being 2 (should be auto or at least 4). It still should be nowhere near that slow. Does the same lockup stutter happen using opengl? As for profile, screenshots of the call tree (start debug->analysis without debugging, then launch) should suffice. Something like 
![image](https://user-images.githubusercontent.com/15904127/35665346-ed03130c-0736-11e8-8c2b-a8ba181ffb67.png)

**Comment by isshininu** [comment]
With opengl RPCS3 have stutters only when shaders compiling.
I'll try different profiling soon as you wish.

**Comment by isshininu** [comment]
To use this function I need compile RPCS3 by myself?

**Comment by kd-11** [comment]
you have to build yourself

**Comment by kd-11** [comment]
BTW, the changes should've been identical on gl and vulkan on both. If building for yourself you can start by just checking if reverting one of the two commits fixes performance. Also, it would be helpful to find someone else with an 840m to confirm the results. On other nvidia chips performance is just fine; this includes dekstop kepler.

**Comment by isshininu** [comment]
I think this problem is Windows 10-specific

**Comment by isshininu** [comment]
![167](https://user-images.githubusercontent.com/6324523/35703935-3dde2246-07b7-11e8-8e1b-614597728561.png)

**Comment by isshininu** [comment]
A workaround is found: patch for DES as described here https://forums.rpcs3.net/thread-197087.html can keep my FPS at 20-30 without CPU spikes.

**Comment by kd-11** [comment]
Do you have any frame control settings active, either in rpcs3 (should be explicitly disabled for demons souls) or in nvidia control panel? I'm only able to achieve such bad framepacing when using nvidia's vsync option, especially adaptive-half refresh option. Any frame control/limiting software will cause this including rivatuner/afterburner if the setting to control framerate/vsync is enabled.

**Comment by isshininu** [comment]
I am always disable RPCS3' vsync option, but i probably was used Nvidia control panel Vsync option for RPCS3 enabled.

**Comment by kd-11** [comment]
Just set the vsync option in control panel to fast and it should work fine. The timing changes introduced by the driver will mess with the game's own timing code used to simulate 30fps when performance is low. This will be less of an issue once spu performance is improved.

**Comment by kd-11** [comment]
Ask to reopen if problem persists without any tear control enabled.

**Comment by isshininu** [comment]
I found the reason why Demon's Souls have FPS drops on Windows 10 - because it is trying to switch to Intel HD Graphics 4600 instead of using Nvidia 840M all the time.

@kd-11 could you PLEASE look into this Optimus issue and settings that were created for RPCS3?
(I believe it is optimus issue since RPCS3 tried to use Intel + Nvidia cards together at the same time).

![1](https://user-images.githubusercontent.com/6324523/44081754-8c4aba9c-9fc0-11e8-8b8e-fcff7e9773c0.jpg)
![2](https://user-images.githubusercontent.com/6324523/44081816-b7111ad2-9fc0-11e8-8d45-280e61754643.jpg)
![3](https://user-images.githubusercontent.com/6324523/44081898-f3dcbc0a-9fc0-11e8-8cb1-be47c15f4a55.jpg)
![4](https://user-images.githubusercontent.com/6324523/44081973-19ae67a8-9fc1-11e8-9817-4a94574e342d.jpg)

**Comment by isshininu** [comment]
> Regression: #3858 causes slowdown on Windows 10 + Vulkan. 

Looks like it was PR #3200 which causes slowdown and heavy stuttering on Windows 10 only. After testing ~40 builds today I finally found the source of regression.

**Comment by isshininu** [comment]
As for now, latest build (v0.0.6-8159) and latest nvidia driver.
Win 10, x64, 1809 LTSC. After test no more usual FPS drops and pikes as seen on videos.
Looks like this bug was finally resolv
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3219737/RPCS3.log.gz)
ed
