### ISSUE TITLE
Make Vulkan mode on Windows compatible with RivaTurner/MSI afterburner monitoring tool?

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#4134]
Hello,
i have trying few month this emulator on multiple Windows pc and it (OSD overlay) never worked on MSI Afterburner in Vulkan mode ( OpenGL is fine) which is great monitoring tool.

  Doplhin and PPSSPP is working fine, i didnt find any Rivaturner / MSI Afterburner support contact, i only tried to ask on Guru3D and response is usually that its emulator fault not Afterburner bug.

  Could you try to fix it on emulator side? Its great for logging performance and this much better that just present FPS number in emulator window titlebar.

**Comment by clienthax** [comment]
What actually doesn't work?

**Comment by Asinin3** [comment]
It doesn't hook into the window at all. There is only few software that can when rpcs3 is using vulkan.

Geforce Experience
Bandicam
Steam overlay
Dxtory

And probably a couple others.

**Comment by kd-11** [comment]
You need to ask the authors of those software to make them compatible with rpcs3. There is nothing wrong with the emulator, just means its not compatible with whatever hooking methods the softwares are trying to use. The onus would be on the third party tool in that case.

**Comment by VelocityRa** [comment]
Alternatively, a subset of whatever these tools provide could be implemented as overlays, seems like a good application for them.

![image](https://user-images.githubusercontent.com/6632271/35678557-7ef639b8-075c-11e8-990f-ad72fb24c934.png)

Maybe some simple graphs even, for things like framerate/frametime?
Just throwing ideas out there.

**Comment by kd-11** [comment]
Framerate is already implemented, just not hoked up yet. Alot of this functionality can be provided via native interface api. The tools themselves should be able to provide this if they install layers properly and dont try hooking the vulkan1.dll since we dont use it. We use vkstatic instead which is why I'm guessing these apps dont work with rpcs3.

**Comment by VelocityRa** [comment]
Oh I see, I just read about the Vulkan loader and its layers concept and it makes sense how they'd be able to do it without hooking to a dll.
Whether or when they _will_ is a different question entirely though, so it may be still worth extending the framerate overlay to implement some of that functionality in rpcs3. Obviously has added benefit of not needing external software.

I'd just try and do some of it myself, but as usual with these things I don't know beforehand whether 1) there is interest 2) it would get merged.

**Comment by ruthan** [comment]
As i wrote problem is that i cant find any Rivaturner / MSI Afterburner contact address to ask them.. From end user perspective i only want to make it work.. I thing that it could be fixed on both side.. on emulator side it would be probably possible and some sauce to make monitoring tool notice that some Vulkan app is  running..

**Comment by Asinin3** [comment]
@ruthan That's not a RPCS3 issue, also pretty sure you can just comment in the guru3d thread, not sure if they use anything else

**Comment by Zangetsu38** [comment]
It is issue with rpcs3, all other probleme in vulkan works, no have rappoort for hiom, and rpcs3 works with him on ogl and dx12.
Just vulkan have problem on rpcs3, that all

**Comment by clienthax** [comment]
https://forums.guru3d.com/threads/osd-is-not-working-for-rpcs3-ps3-emulator-and-vulkan-mode-opengl-is-fine-other-vulkan-apps-fine.419101/

**Comment by oscarbg** [comment]
So unwinded says it’s because rpcs3 is linking vulkan library statically instead of dinamically..
So please someone a separate issue urging devs to change rpcs3 to link vulkan dynamically..

**Comment by ruthan** [comment]
>  So unwinded says it’s because rpcs3 is linking vulkan library statically instead of dinamically..
  And he is saying that is obsolete way, which could cause other problems with Vulkan..

**Comment by kd-11** [comment]
Closing as fixed via https://github.com/RPCS3/rpcs3/pull/4639
