### ISSUE TITLE
log: Additional debug information

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#4145]
A few features that would be useful when analyzing other people's logs to provide help:

- ogl: Log used GPU;
- vk: Log drivers' version (and maybe VulkanRT version?);
- core: Log used OS;

**Comment by Asinin3** [comment]
What about pad settings? it would be nice to see what input method people are using as well.

**Comment by isshininu** [comment]
More telemetry!

**Comment by Renusek** [comment]
I suggested that long time ago -.-

**Comment by Asinin3** [comment]
@Renusek Showing different settings in log file has nothing to do with collecting telemetry from every user...

**Comment by Renusek** [comment]
@Asinin3 so collecting gpu/drivers/os info is not telemetry? because that's what I was suggesting

**Comment by Asinin3** [comment]
"Telemetry is an automated communications process by which measurements and other data are collected at remote or inaccessible points and transmitted to receiving equipment for monitoring"

This may collect a bit more info but it's not like it will gather data from every user, it's just written to the log file. It's not putting it up on a server somewhere so we can see statistics on what people use etc.

**Comment by AniLeo** [comment]
There is no telemetry, you only submit your logs if you want help. 
If one wants help and is not willing to provide basic system information to help people help them, then at that point they shouldn't be asking for help and should figure out how to do it themselves.

That being said, if telemetry ever gets added to RPCS3, it will be disabled by default.

**Comment by AniLeo** [comment]
Don't think so
