### ISSUE TITLE
New UI: freeze while saving.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4146]
I just encountered one.
Here is the screenshot and a log.
![201](https://user-images.githubusercontent.com/6324523/35771430-1e94797c-0946-11e8-96f4-cd7cbe107b83.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1692187/RPCS3.log.gz)

_Title: Silent Hill: Homecoming
Serial: BLES00460_

**Comment by AniLeo** [comment]
Is this still an issue? kd-11 recently pushed changes to the overlay

**Comment by isshininu** [comment]
Yes, this is still an issue for this game atleast.
Can reproduce it on latest master, here is the log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2173613/RPCS3.log.gz)

**Comment by AniLeo** [comment]
This is not an issue with disabled overlay? May be something to add onto #4072

**Comment by isshininu** [comment]
I just checked - this is issue even when native overlay was disabled...
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2498053/RPCS3.log.gz)

**Comment by elad335** [comment]
this is probably fixed by #5792 .

**Comment by isshininu** [comment]
I will retest soon, when I have time.

**Comment by Megamouse** [comment]
Please retest

**Comment by digitaldude555** [comment]
@isshininu retest.

**Comment by isshininu** [comment]
oh yeah

**Comment by isshininu** [comment]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4240508/RPCS3.zip)
No freezes when trying to save several times in a row.
