### ISSUE TITLE
God Of War II HD [NPEA00256] Bug with shader gen

### ISSUE THREAD

**Issue by TheeLich** [RPCS3/rpcs3#4153]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1700658/RPCS3.log.gz)

**Comment by Zangetsu38** [comment]
share log file, and no past all line

**Comment by TheeLich** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1700644/RPCS3.log.gz)
Okay,sorry bro is my first time

**Comment by Zangetsu38** [comment]
not worry, but delete you long message lol, edit post and delette log

**Comment by AniLeo** [comment]
Read the guidelines instead of trying to guess what to do, GitHub issue template and warning message on issue creation isn't enough? 

The error you're getting is not a bug on shader compiler, it's just trash from corruption being sent to it.

**Comment by Asinin3** [comment]
It doesn't happen with vulkan anyway, no idea why someone on discord advised you to open an issue on github.

**Comment by kd-11** [comment]
Duplicate of https://github.com/RPCS3/rpcs3/issues/2359. Caused by desynchronization when spu emulattion is slower than rsx
