### ISSUE TITLE
rpcs3 CommandLine Error: Option 'track-memory' registered more than once!

### ISSUE THREAD

**Issue by soredake** [RPCS3/rpcs3#4157]
```bash
❯ rpcs3
qt5ct: using qt5ct plugin2
: CommandLine Error: Option 'track-memory' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
gentoo amd64, latest rpcs3 from git, llvm 4

**Comment by hcorion** [comment]
What GPU and driver? what version of LLVM was the gpu driver compiled with? 
Does the AppImage work? Download it from https://rpcs3.net/download
What additional flags did you use, and what compiler?

**Comment by soredake** [comment]
rx 560, amdgpu with DC enabled, llvm4
appimage works.
gcc 7.3.0, glibc 2.27 if that's matter

additional flags:
FLTO="-flto=16"
GRAPHITE="-fgraphite-identity -ftree-loop-distribution -floop-nest-optimize"
CFLAGS="-O3 ${GRAPHITE} ${FLTO} -fuse-linker-plugin -pipe"

**Comment by hcorion** [comment]
Perhaps the lto is screwing with the build, can you try without lto?

**Comment by soredake** [comment]
Tried without lto and graphite, nothing changed.

**Comment by hcorion** [comment]
Alright, can you try with clang instead of gcc?

**Comment by soredake** [comment]
Tried without lto and graphite, nothing changed.

**Comment by soredake** [comment]
Same with clang.

**Comment by soredake** [comment]
Fixed by deleting llvm5.
