### ISSUE TITLE
GUI shows wrong version on updated games

### ISSUE THREAD

**Issue by Nicba1010** [RPCS3/rpcs3#4161]
After installing updates for a game that is a disc release (I only tested disc releases honestly) the version in the GUI doesn't get updated, not even after restarting RPCS3.
_Note: Where to get updates? https://a0.ww.np.dl.playstation.net/tpl/np/{game_id}/{game_id}-ver.xml_
Screenshot:
![](https://image.prntscr.com/image/CRz5zW5hSZabPJ6qa89coA.png)
As you can see this is the param.SFO from the game folder, as in where the updates are installed.
![](https://image.prntscr.com/image/XgABluP1TbKd4LUl_gdpGw.png)
The param.SFO from the disc folder tells a different story though.

My suggested fix is checking the game folder first to see if there are any updates installed. Also there is no reason to believe that the updates aren't actually being installed since the LLVM Recompiler recompiles additional modules after the game update!

**Comment by Megamouse** [comment]
the version is shown on gamedata
