### ISSUE TITLE
Offer a place to download compatible database for people who use the emulator offline

### ISSUE THREAD

**Issue by deadair3210** [RPCS3/rpcs3#4164]
Not so much of an issue as a request, if possible is there a way to offer the downloadable database some other way that just through the emulator? Would be useful for people without internet or just don't want to be online

**Comment by AniLeo** [comment]
Already implemented, the emulator ships with compatibility database and has functionality to download latest version.

**Comment by isJuhn** [comment]
if you really want to you can copy all the text on [here](https://rpcs3.net/compatibility?api=v1&export) and save it to a file called `compat_database.dat` in rpcs3/GuiConfigs/

**Comment by Megamouse** [comment]
dude.... just.... i dunno... dude .... man...
