### ISSUE TITLE
LLVM - Assertion failed Expression: !HasError && "Cannot get value when an error exist"

### ISSUE THREAD

**Issue by AquilesEsparta** [RPCS3/rpcs3#4165]
Windows 8.1 
Intel(R) Core(TM) i7-4710HQ CPU @ 2.5GHz  2.49 GHz
NVIDIA GeForce GTX 970M
16 RAM
Hi, i have a problem with Visual C, i have been unistalled and installed it again but it doesnt work, this is the problem that appears when i try to run Demons Souls

![image](https://user-images.githubusercontent.com/36319350/36058063-10ba811a-0dde-11e8-8ee0-d825a7595114.png)

**Comment by AniLeo** [comment]
Missing information, read the guidelines.

**Comment by AquilesEsparta** [comment]
i have edit the post, thanks (:


________________________________
De: Ani <notifications@github.com>
Enviado: viernes, 9 de febrero de 2018 09:19 p. m.
Para: RPCS3/rpcs3
CC: AquilesEsparta; Author
Asunto: Re: [RPCS3/rpcs3] LLVM - Assertion failed (#4165)


Missing information, read the guidelines.

**Comment by scribam** [comment]
@AquilesEsparta Any updates?

**Comment by AniLeo** [comment]
Likely fixed as this was an issue on a very old RPCS3/LLVM version. Assuming fixed due to lack of activity, if it's still an issue on latest master, a new issue can be opened.
