### ISSUE TITLE
Graphics driver crash

### ISSUE THREAD

**Issue by Zusion** [RPCS3/rpcs3#4166]
Only tested with Persona 5. Can get ingame fine, but doesn't take long for the driver to crash when it starts compiling shaders. Throws this error:

error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:1166)

The problem only appears from #4011 (71f69d1d) onwards. The build before that #4061 works fine. 

From the latest build: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1713169/RPCS3.log.gz) (Had to kill the process to get the log file. It doesn't always freeze though.)

Windows 8.1
i5 6600K
16GB
HD7850
Crimson 17.7.1

**Comment by kd-11** [comment]
Update to newer drivers and retest

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/4344

**Comment by kdlz4161** [comment]
Only tested with Sly Cooper:Thieves in.Can get ingame fine, but doesn't take long for the driver to crash when it starts compiling shaders. Throws this error:

F {rsx::thread} class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:912)

The problem only appears from #4011 (71f69d1) onwards. The build before that #4061 works fine.

From the latest build:

**Comment by kd-11** [comment]
This is about AMD drivers. Do not derail the discussion.

**Comment by kd-11** [comment]
Closing as fixed via https://github.com/RPCS3/rpcs3/pull/4344. Report if the same crash still happens.
