### ISSUE TITLE
Shadows of the Damned [BLUS30653] - image still red with Strict Rendering Mode enabled.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4168]
Shadows of the Damned [BLUS30653] - red colored noise still remains with Strict Rendering Mode being enabled in both Vulkan and OpenGL, LLVM + ASMJIT.

Image looks like this:
with Strict Rendering Mode
![240](https://user-images.githubusercontent.com/6324523/36073836-52c962b0-0f50-11e8-8ba0-282bf884b30d.png)
![233](https://user-images.githubusercontent.com/6324523/36073856-90b34b4a-0f50-11e8-9867-959e8a35deb7.png)

without
![241](https://user-images.githubusercontent.com/6324523/36073852-8005890c-0f50-11e8-97fc-044bb890952b.png)
![239](https://user-images.githubusercontent.com/6324523/36073859-98d74092-0f50-11e8-8c2f-568f94630136.png)

Not so much red, but still remains.

Settings and log: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1714385/RPCS3.log.gz)

**Comment by Parthorisian** [comment]
Yes, there is some graphical glitch progress with these borders, definitely. less black noise, now are solid ![qqe](https://user-images.githubusercontent.com/6324523/36073859-98d74092-0f50-11e8-8c2f-568f94630136.png)
![qqq](https://user-images.githubusercontent.com/35437970/37489842-9368fd16-28a1-11e8-9cd9-dd02db7091fd.jpg)

**Comment by Megamouse** [comment]
fixed in #4312 (both strict and without)

![image](https://user-images.githubusercontent.com/23019877/37714691-7b1c227e-2d1a-11e8-9c2d-9ad715355a4e.png)
![image](https://user-images.githubusercontent.com/23019877/37714814-c7bcc73c-2d1a-11e8-8988-33379dc1da3d.png)

**Comment by isshininu** [comment]
Uh, you say "without"?
![459](https://user-images.githubusercontent.com/6324523/37718796-fa5645d4-2d3c-11e8-8958-09b3ea682526.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1833877/RPCS3.log.gz)

**Comment by Megamouse** [comment]
set Resolution Scale to 100%

**Comment by Megamouse** [comment]
also your log tells me you have strict mode enabled

**Comment by isshininu** [comment]
Resolution scale 100 % = Strict Rendering Mode in terms of functionality.
I mean, those resolutions are kinda weird.

**Comment by Megamouse** [comment]
so what. does 100% fix it for you

**Comment by kd-11** [comment]
Strict mode does alot more including disabling anisotropic filters where they are not requested by the game and transferring texture data in case of feedback loops. If a game breaks with scaling, use the threshold slider to find a safe threshold. If default settings still break the game, then another compatibility workaround may be needed for nvidia.

**Comment by isshininu** [comment]
OK, let me check one more thing...

**Comment by isshininu** [comment]
OK, the purpose of this bug report was to remove red noise when Strict Rendering Mode is enabled. So, it can be closed because it is done. There is no need for me to convert it into something more continuous.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1834053/RPCS3.log.gz)

![466](https://user-images.githubusercontent.com/6324523/37721091-255c7730-2d42-11e8-94ba-43ff93b03db7.png)

**Comment by isshininu** [comment]
This problem (red noise when upscaling non-Strict rendered output) also appears in Silent Hill: Downpour main menu.

**Comment by Megamouse** [comment]
maybe we should let kd-11 decide how to track this properly

**Comment by kd-11** [comment]
If the problem disappears when upscaling is in place it usually means there is a shader with math that is sensitive to the resolution. There is no non-hacky solution other than to raise the scaling threshold to a value larger then the surface dimension in question - usually setting scaling threshold to some large value like 512 or higher fixes it. Remember that upscaling in itself is a major deviation from real hardware.

**Comment by Megamouse** [comment]
It appears with upscaling. not disappears

**Comment by kd-11** [comment]
Fixed in https://github.com/RPCS3/rpcs3/pull/4312

**Comment by isshininu** [comment]
Just visit this page before kd-11 comment :)

**Comment by zahdab** [comment]
looks like its back ?
