### ISSUE TITLE
Gran Turismo HD Concept [NPEA90002] Graphic issues

### ISSUE THREAD

**Issue by AtrisMio** [RPCS3/rpcs3#4171]
CPU: Intel i5-6500, RAM: 16G, Video Card: GTX 1060 6GB, System: Win10 1709

rpcs3: 0.0.4-6422-95c6ac699 alpha

# Graphic issues

> the text show as color block.
> and the console logs huge amount of `E {rsx::thread} RSX: rsx::nv308a::color<0>::impl: y is not null (0x1)`

![image](https://user-images.githubusercontent.com/8896399/36139668-7816d446-10d9-11e8-9bbd-f721238e07db.png)

**Comment by relaxfm** [comment]
Write color buffers on?

**Comment by Zangetsu38** [comment]
no have rapport, old issue :/

**Comment by AtrisMio** [comment]
@relaxfm cannot display the text neither on nor off.

**Comment by AtrisMio** [comment]
@Zangetsu38 Oh, sorry. I Don’t see some issue like this. I don’t know it’s a old issue.

**Comment by kd-11** [comment]
Visuals in this game have changed a lot since february.

**Comment by AtrisMio** [comment]
@kd-11 thanks for replying, I will try it weekend.

**Comment by AtrisMio** [comment]
@kd-11 same as before, is here a recommended setting for GT?

**Comment by digitaldude555** [comment]
![screenshot 1657](https://user-images.githubusercontent.com/26138653/51088444-721c3680-1768-11e9-9186-8d5681a8243f.png)
fixed can close this issue.
