### ISSUE TITLE
Crash on exceeding directory character count - PAIN! (EU) NPEA00054

### ISSUE THREAD

**Issue by Smoker1** [RPCS3/rpcs3#4177]
I am trying to Install PAIN Package File, but when I try to, it is stuck at 0%, even overnight. When I close out the Installer, I get this Error Message, as shown in the Attached Image.
![pain package install problem](https://user-images.githubusercontent.com/8584462/36298011-b856de98-12aa-11e8-8bd0-04785d8fc230.jpg)
Package is from NPS, so it is from the Sony Server (Official)
Disk Based Version (BCES00548) seems to be ok as it is not in PKG Format, however that gets stuck on the Installing Game Data.

**Comment by AniLeo** [comment]
Yeah, that's a windows limitation on path size, closing
