### ISSUE TITLE
NHL 2K8 [BLES00131]: many graphical bugs

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#4179]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1732880/RPCS3.zip)
![1](https://user-images.githubusercontent.com/14265316/36330006-1731661c-1379-11e8-8173-dfb29b37bd48.png)
![2](https://user-images.githubusercontent.com/14265316/36330010-1b0a7e36-1379-11e8-9159-50d9f0d5d5a3.png)
![3](https://user-images.githubusercontent.com/14265316/36330018-1e4784b8-1379-11e8-9edb-59259a7cab8b.png)
![4](https://user-images.githubusercontent.com/14265316/36330027-223534e4-1379-11e8-8e08-5e8123dca8bb.png)
![5](https://user-images.githubusercontent.com/14265316/36330030-24ef89c8-1379-11e8-9aaa-f3eeb5dee634.png)

**Comment by digitaldude555** [comment]
@TotalCaesar659  retest with master build should be improved.

**Comment by kd-11** [comment]
Retest.

**Comment by TotalCaesar659** [comment]
I had to start the game several times for going to ingame.
[NHL_2K8.zip](https://github.com/RPCS3/rpcs3/files/2191074/NHL_2K8.zip)
![nhl_2k82](https://user-images.githubusercontent.com/14265316/42669820-3108ab04-8660-11e8-87a3-8b326c0f916c.png)

**Comment by TotalCaesar659** [comment]
Fixed in https://github.com/RPCS3/rpcs3/pull/5612.
