### ISSUE TITLE
Regression in God of War III due to #4002

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#4183]
Vulkan not booting in pull request from pull #4002 https://github.com/RPCS3/rpcs3/commit/95c6ac699b654e9c7ad35a5c63a9113db60ba125

It says, `compiling shaders` and then nothing much.

OpenGl is slow

**Comment by kd-11** [comment]
Which version of GOW3? This game has never booted consistently due to race conditions so freezing with "compiling shaders" is normal and will usually proceed if you reboot a few times. Once it boots it will then be more consistent. E3 demo version is confirmed to still be working fine.

**Comment by kd-11** [comment]
A log file will also be required for analysis.

**Comment by kd-11** [comment]
Full game also confirmed to boot properly.

**Comment by spyropt** [comment]
@kd-11 Theres still something wrong with gow III it boots but just shows a black screen and goes from 60 to 0.96fps
there are other users with the same problem, i haven't pinpoint the commit but its something with 4162 pr
BCES00510
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1772239/RPCS3.log.gz)
