### ISSUE TITLE
The Orange Box [BLES00153] Black screen on Vulkan and DX12

### ISSUE THREAD

**Issue by JusicP** [RPCS3/rpcs3#4189]
RPCS3 v0.0.4-6440-877b296fc Alpha | HEAD
Tried all settings but nothing changed.
![vkbs](https://user-images.githubusercontent.com/25232950/36354323-1bbc51e8-14db-11e8-9fe8-4e3fa1125508.png)
[123.zip](https://github.com/RPCS3/rpcs3/files/1734881/123.zip)

**Comment by Xcedf** [comment]
The same issue presented in Haze, Sly Copper Thieves in time (some places) Simpsons the Game (some places), all these games has yellowish render on OGL and black screen+HUD on Vulkan
