### ISSUE TITLE
Vulkan Crashing on new AMD Adrenalin drivers

### ISSUE THREAD

**Issue by ltl114** [RPCS3/rpcs3#4195]
With the new driver installed, Vulkan will just crash when i try to launch any game on rpcs3. I tried to roll back to Crimson drivers and then Vulkan will work. OpenGL always works but the performance is kinda lousy so I have to stick to Vulkan. The driver and the runtime library should be fine since other game such as dota 2 runs just fine using Vulkan with the newer driver, only rpcs3 is having problem right now. I'm not sure if this will happen on other AMD gpu, as the problem might be limited to certain ones. Please look into the problem, thank you.

Error message:
Unhandled Win32 exception OxC0000005. 
Segfault reading location 0000000000000020 at 00007fff0724bff0. 
Instruction address: 00007fff0724bff0. 
Function address: 00007fff0724bfe0 (base+Oxbfe0). 
Module name: 'amdvIk64.d11'. 
Module base: 00007fff07240000. 
RPCS3 image base: 0000000000010000. 

Rpcs3 version: 0.0.4-6412

System Spec:
CPU: Core i7 5500U
RAM: 8GB
GPU: AMD Radeon R7 M260
OS: Windows 10 Version 1709 64-bit

Rpcs3 Log file: https://drive.google.com/open?id=1dLpWUCzsp_ICACyk1_GaLZdebwTS26ay

**Comment by JohnHolmesII** [comment]
Just for the record, I am not having any issues with vulkan on 18.2.3
RX 580

**Comment by kd-11** [comment]
I have a gpu from the same era (pitcairn, also gcn1); no crashes that I could trigger. Does it happen in all games?

**Comment by Dravonic** [comment]
Happening on 18.2.3 with a 390x. 

Seems to me like it happens in all games since the 3 games I usually play have this issue: Persona 5, Demon Souls and Nier Replicant. I didn't try reverting but it does look driver related since it began with 18.1.x.

**Comment by ltl114** [comment]
> Menus work fine, it's when I get ingame that it happens. The time it takes to happen is random but it usually happens in under 1 min.

Probably not the same issue, all of my games crash as soon as the lle modules are loaded, did not even go in game.

**Comment by kd-11** [comment]
1. Download and install the vulkan SDK from lunarG site.
2. Enable the hidden debug tab and enable debug output or set "Debug Output" option to true in the config.yml. This should activate the (very very slow) validation layers
3. Enable strict mode
4. Load gs_gcm_basic_triangle sample from the /dev_hdd0/game/TEST12345 folder. Load via Load ELF option.
5. If it crashes attach log file

By design, vulkan is a minimal error API, any problems will not be checked by the driver so nothing is logged, unless the validation layers are enabled. That comes with a significant performance penalty though.

**Comment by ltl114** [comment]
The test sample also instantly crashes with exactly the same error message, the log file is [here](https://drive.google.com/open?id=1dLpWUCzsp_ICACyk1_GaLZdebwTS26ay). Also tried different versions of rpcs3, from 0.0.3 to 0.0.5, no luck. This could more likely be a driver issue.

**Comment by ltl114** [comment]
Alright I seem to find the problem. The newer driver does a terrible job at managing switchable graphics. A 3d application cannot utilize the discrete graphic device unless you set it to do so in radeon settings.
Older drivers always use
