### ISSUE TITLE
X-Men Origins Wolverine [BLES00150] Misaligned layer

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#4196]
Game: X-Men Origins: Wolverine [BLES00150]
Commit: ee88e7f94
Renderer: Vulkan (same issues affect OpenGL as well)
Specs: Ryzen 5 1600 / RX 480 8GB / 16GB RAM

During the drop from the helicopter, there is a weird picture-in-picture effect that changes size depending on how close Wolverine is to the bottom of the screen (visible in screenshot). The second layer is used to render clouds and distortion effects so it should be visible but something causes it to change its size.

[Screenshot](https://user-images.githubusercontent.com/19759300/36429713-1ae7ae98-165c-11e8-83c6-b90a0c916bf8.png)
[Video](https://streamable.com/kedbu)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1740247/RPCS3.log.gz)

**Comment by kd-11** [comment]
Retest, this is an unreal engine title

**Comment by MSuih** [comment]
a36acf49

Flickering is fixed by strict rendering mode and visuals are improved but the picture-in-picture effect still remains. It's a very quick game to test btw as all intros and cutscene videos can be skipped with one button.

**Comment by MSuih** [comment]
[OpenGL capture with renderdoc](https://mega.nz/#!GeQDWAYI!VQ2am2NI731nV6EcnfWOLJQ1TcRtbn7hzByNsGr5qis). The game is incompatible with rsx captures for some reason.

**Comment by MSuih** [comment]
Finally got an RSX capture done. This is on commit 3ef16be
![image](https://user-images.githubusercontent.com/19759300/54523972-696afb00-4979-11e9-822a-10c9e496b35b.png)
https://mega.nz/#!TLIjyaoA!G-55XOAfG0rtSK_qmeOjSob1ih3vCK9KBkwXsxbGYJo

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/8171
