### ISSUE TITLE
Regression: Silent Hill: Downpour - "Strict Rendering Mode" now causes crash

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4203]
Silent Hill Donwpour BLUS30565

It looks like one of the recent commits broke "Strict Rendering Mode" in both OpenGL and Vulkan.

F {rsx::thread} class std::system_error thrown: device or resource busy: device or resource busy
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1747571/RPCS3.log.gz)

**Comment by Asinin3** [comment]
This issue still happens on the latest master however I never got the above fatal error. Instead "loading" text appears on screen for a split second then the game hangs on a black screen with OpenGL and Vulkan.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2027013/RPCS3.log.gz)

**Comment by isshininu** [comment]
Yeah, same for me. Just black screen now.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2027085/RPCS3.zip)

**Comment by isshininu** [comment]
Looks like it was surprisingly fixed somehow.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2123171/RPCS3.log.gz)
I guess it can be closed for now.
