### ISSUE TITLE
I keep getting this error...

### ISSUE THREAD

**Issue by Addoi** [RPCS3/rpcs3#4207]
I don't know what to do, everytime i try to play a game i get this error, my version is v 0.0.4, here's the log

U {PPU[0x1000000] Thread (main_thread) [0x00952d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00952d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00952d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00952d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00952d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00928f0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00928f0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000000] Thread (main_thread) [0x00928f0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00928f0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
S {SPU[0x2000000] Thread (SP_LIB CellSpursKernel0)} SPU: SPU Database initialized...
S {SPU[0x2000000] Thread (SP_LIB CellSpursKernel0)} SPU: SPU Recompiler (ASMJIT) created...
E {PPU[0x1000000] Thread (main_thread) [0x0060c008]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000000] Thread (main_thread) [0x0060cc1c]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {rsx::thread} RSX: OpenGL: initialization of glDepthBoundsEXT failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetTextureImageEXT failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetTextureImage failed.
E {rsx::thread} RSX: OpenGL: initialization of glTextureBufferRange failed.
E {rsx::thread} RSX: OpenGL: initialization of glCopyImageSubData failed.
E {rsx::thread} RSX: OpenGL: initialization of glTextureBarrier failed.
E {rsx::thread} RSX: OpenGL: initialization of glTextureBarrierNV failed.
F {rsx::thread} class std::runtime_error thrown: Failed to initialize OpenGL renderer. ARB_direct_state_access or EXT_direct_state_access is required but not supported by your GPU

**Comment by tlm-2501** [comment]
Upload your RPCS3.log file.

**Comment by Addoi** [comment]
RPCS3 v0.0.4-6455-5266dd6c6 Alpha | HEAD
Intel(R) Core(TM) i5-3330S CPU @ 2.70GHz | 4 Threads | 7.88 GiB RAM | AVX
S LDR: Boot from gamelist per doubleclick: done
U {PPU[0x1000000] Thread (main_thread) [0x00928e64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x009290bc]} sys_prx TODO: _sys_prx_register_library(library=*0x92b6a0)
S {PPU[0x1000000] Thread (main_thread) [0x009299ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00933d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x0092a4d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0092a4d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x0092a4d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0092961c]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x0092a038]} sys_prx TODO: _sys_prx_unload_module(id=0x23003e00, flags=0x0, pOpt=*0x0)
S {PPU[0x1000000] Thread (main_thread) [0x009299ac]} sys_prx: Loaded module: /dev_flash/sys/external/libfiber.sprx
S {PPU[0x1000000] Thread (main_thread) [0x009299ac]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx
S {PPU[0x1000000] Thread (main_thread) [0x009299ac]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x009299ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
S {PPU[0x1000000] Thread (main_thread) [0x009299ac]} sys_prx: Loaded module: /dev_flash/sys/external/libnet.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00952d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00952d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00952d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00952d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00952d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x00928f0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00928f0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000000] Thread (main_thread) [0x00928f0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00928f0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
S {SPU[0x2000000] Thread (SP_LIB CellSpursKernel0)} SPU: SPU Database initialized...
S {SPU[0x2000000] Thread (SP_LIB CellSpursKernel0)} SPU: SPU Recompiler (ASMJIT) created...
E {PPU[0x1000000] Thread (main_thread) [0x0060c008]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000000] Thread (main_thread) [0x0060cc1c]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {rsx::thread} RSX: OpenGL: initialization of glDepthBoundsEXT failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetTextureImageEXT failed.
E {rsx::thread} RSX: OpenGL: initialization of glGetTextureImage failed.
E {rsx::thread} RSX: OpenGL: initialization of glTextureBufferRange failed.
E {rsx::thread} RSX: OpenGL: initialization of glCopyImageSubData failed.
E {rsx::thread} RSX: OpenGL: initialization of glTextureBarrier failed.
E {rsx::thread} RSX: OpenGL: initialization of glTextureBarrierNV failed.
F {rsx::thread} class std::runtime_error thrown: Failed to initialize OpenGL renderer. ARB_direct_state_access or EXT_direct_state_access is required but not supported by your GPU

**Comment by Parthorisian** [comment]
Just make sure to attach the RPCS3.log.gz file from your RPCS3 directory. Just click blue "selecting them" below your comment and select it

**Comment by Asinin3** [comment]
Does your GPU support Open GL 4.3? Also please read the rules on creating issues. https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md
