### ISSUE TITLE
0X1638044 Unsupported Relocation(10) in 'liblv2.sprx. 

### ISSUE THREAD

**Issue by JadenG523** [RPCS3/rpcs3#4210]
I get that error most of the time when trying to launch
-MX VS ATV Reflex
--MX VS ATV SUPERCROSS
-- and for some reason MX VS ATV Untamed loads but stops when "compliling shaders" pops up

**Comment by AniLeo** [comment]
Missing log and further information. What firmware version are you using?

**Comment by JadenG523** [comment]
ill send you screen shot, im using the lastest firmware from playstation website

**Comment by JadenG523** [comment]
i try to copy the log but it crashes everytime i try to, can i find the log in files?
![capture](https://user-images.githubusercontent.com/36807005/36638190-c17920f4-19a2-11e8-9eef-13688eeac9a7.PNG)

**Comment by AniLeo** [comment]
Read the guidelines and then reopen your issue, you're not supposed to copypasta the log.

Also read "how to ask for support" on wiki
