### ISSUE TITLE
The Simpsons the Game [BLES00146] - Input broken

### ISSUE THREAD

**Issue by frankyfife** [RPCS3/rpcs3#4212]
**Tested Build :**
 rpcs3-v0.0.5-6463

**Hardware Specs :**
Nvidia GeForce GTX 1080Ti
Intel Core i7 8700k
32 GB of Ram
Windows 10 Pro x64 [Version 10.0.16299.248]
Xbox ONE Elite (Wireless) Controller

**Issue :**
The controller inputs are only partially accepted. For example, it is not possible to navigate by analog stick or control pad (menus). Ingame is the same. Input of the X or Start buttons has been accepted.

In the rpcsx3 configuration menu of the controller all keys are recognized and can be assigned unambiguously. Counter-tested with Metal Gear HD Collection, here I found no problems with the input.

Most recently I tested the Simpsons game with the build of rpcs3-v0.0.4-2018-02-18, where the inputs worked smoothly.

**Comment by greggameplayer** [comment]
i have test this game but the EU Version on RPCS3 0.0.4-6448-1b26ec56e Alpha and there is an input bug with the analog stick or control pad only in the menus.
