### ISSUE TITLE
SKATE 3 SHADOW ISSUE

### ISSUE THREAD

**Issue by mchelequim** [RPCS3/rpcs3#4213]
please fix
![captura de tela 18](https://user-images.githubusercontent.com/36716836/36644056-6d48c246-1a33-11e8-8ef2-8cb4b4405ff7.png)
t the shadow problem in the game.
I love this title and I can not buy a console.thank you !!

**Comment by AniLeo** [comment]
#3952 already exists

Read the guidelines when making future issues to prevent spam
