### ISSUE TITLE
Gal Gun [BLJM60434] is not Playable anymore

### ISSUE THREAD

**Issue by Bikkoist** [RPCS3/rpcs3#4215]
Game: Gal Gun [BLJM60434]
Renderer: OpenGL, Vulkan

Tested on:
i7-880 / GTX750ti / 16GB RAM / Windows 7 SP1
i7-4720HQ / GTX970M / 16GB RAM / Windows 8.1

The game was Playable with some minor issues(Such as graphical glitch on Vulkan renderer) till v0.0.4-2018-02-12-95c6ac69, but It is broken by v0.0.4-2018-02-16-ee88e7f9. The game will be freeze with 'MEM: Access violation reading' message on very specific points and not playable anymore.

**Comment by al0xf** [comment]
Need the log file

**Comment by Bikkoist** [comment]
Include 4 logs. Just in case.
2 logs from v0.0.4-2018-02-16-ee88e7f9, Vulkan and OpenGL
2 logs from v0.0.5-6464-b61a69c8, Vulkan and OpenGL
All logs from system : i7-880 / GTX750ti / 16GB RAM / Windows 7 SP1
All freeze at same point.
[RPCS3.log_BLJM60434.zip](https://github.com/RPCS3/rpcs3/files/1762619/RPCS3.log_BLJM60434.zip)

**Comment by maxlefou** [comment]
I can make run the game, but I experience a huge lag. And the game completely freezes if i hit any button of the gamepad. The logs display this error when it happens:
```
E {PPU[0x1000000] Thread (main_thread)} Stat: 'cellPadClearBuf' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [x10926]
E {PPU[0x1000000] Thread (main_thread)} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x4]
```

Tested on RPCS3 0.0.05-7163-451b3f3c9
CPU : i3 530 2.93GHz
GPU : Nvidia Geforce GTX 960 with 4Gb of DRAM
RAM : 8Gb
OS: WIndows 10

**Comment by digitaldude555** [comment]
Doesn't freeze anymore, or lag and doesn't freeze when hitting a button. Can close the issue.

**Comment by maxlefou** [comment]
Sorry but still experiencing unbearable lag (though, it notably decreased and the commands doesn't freeze the game indeed)

**Comment by digitaldude555** [comment]
Well, your CPU is i3 530...
