### ISSUE TITLE
Feature Request : Save state

### ISSUE THREAD

**Issue by M220** [RPCS3/rpcs3#4218]
There wasn't any issue for this Feature so I created this issue!
And here is some PRs of other Emulators that have this feature working in it's core:
https://github.com/hrydgard/ppsspp/pull/266 ( Main PR for PPSSPP Save state )
https://github.com/PCSX2/pcsx2/blob/master/pcsx2/SaveState.cpp ( and here is the Savestate.cpp file of PCSX2 [ sorry but I couldn't find any Core PR For the save states or save slots in their github ] )
Dolphin Emulator have this feature working too so I Will update the issue if i find The main PRs for savestates in PCSX2 and Dolphin emulator githubs.
I know that this is not something that is on your list of TOP IMPORTANT Things TO DO but it will be pretty good to have it working on your Emulator too :D 
Thank you guys for Your Hard work on the Emulator and sorry for my bad English ;)

**Comment by CV01HatsuneASD** [comment]
I haven’t used or played PS3 games using RPCS3 … but save states may be a good addition to the emulator. Though it sounds awesome, it may be difficult for the devs to make it possible.

Sent from Mail for Windows 10

From: M220
Sent: Monday, February 26, 2018 7:13 PM
To: RPCS3/rpcs3
Cc: Subscribed
Subject: [RPCS3/rpcs3] Feature Request : Save state (#4218)

There wasn't any issue for this Feature so i created this issue.
And here is some PRs of other Emulators that have this feature working in it's core.
hrydgard/ppsspp#266 ( core PR for PPSSPP Save state )
https://github.com/PCSX2/pcsx2/blob/master/pcsx2/SaveState.cpp ( and here is the Savestate.cpp file of PCSX2 [ sorry but I couldn't find any Core PR For the save states or save slots in their github ] )
I know that this is not something that is on your list of IMPORTANT Things TO DO but it will be pretty good to have it working on your Emulator too :D
Thank you guys for Your Hard work on the Emulator and sorry for my bad English ;)

**Comment by VelocityRa** [comment]
I did some work on this a few months ago: https://github.com/VelocityRa/rpcs3/commit/save-states

It's not just difficult, it's impossible without changing and refactoring a bunch of fundamental components in the emulator. A lot of stuff wasn't written with saves states in mind, unfortunately.

Save states are one of these features that should happen a lot later in RPCS3's development.

**Comment by M220** [comment]
a journey of a thousand miles begins with a single step!
If you think your PR or a part of it will help Implementing this feature in future then there's no need to worry , go ahead and try to do a small part of it if you can :D

**Comment by Parthorisian** [comment]
This will be great if will be done

**Comment by CV01HatsuneASD** [comment]
Try to have your code on PR and let Ani analyze it.

**Comment by AniLeo** [comment]
Lol

**Comment by TristisOris** [comment]
yep, it must be to a custom path to ssd or pre reserved memory.
memory dump would be too heavy on PS3.

can't imaginate any emulator without this feature(

**Comment by rayman3003** [comment]
Hope to see "Save State" in RPCS3 soon. Bcuz I think save state is a very important feature in any emulator. IMO, any emulator without save state, looks incomplete.

Please look forward to "Save State" in RPCS3.

**Comment by Asinin3** [comment]
Elad is already working on trying to make save states a reality.

**Comment by rayman3003** [comment]
> Elad is already working on trying to make save states a reality.

It's a very good news. Hope we see this reality soon. :D

**Comment by elad335** [comment]
See #10478

**Comment by cglmrfreeman** [comment]
I don't really need a savestate, I just need to dump the memory for analysis, but I see that was closed here #3383, and as PR #10478 for savestates isn't buildable at the moment, I still don't see why one feature could exist until the other is implemented? Should a memory dump be developed to aid the creation of savestates?

**Comment by VelocityRa** [comment]
@cglmrfreeman That's a pretty niche use-case, for which you can use also any generic process dumper tool. The guest's RAM in RPCS3 is mapped at `0x300000000` to `0x310000000`.

**Comment by cglmrfreeman** [comment]
I'm a Linux user so Cheat Engine isn't really an option. I also need to extract specific data from the RAM into file usable in other programs (an even more niche case I guess). I'll see if I can dump memory from those mappings.

**Comment by VelocityRa** [comment]
No idea if the RAM base is the same on Linux.

**Comment by cglmrfreeman** [comment]
Oh, well that's not helpful, lol

**Comment by VelocityRa** [comment]
It's printed in the log. Just run a game and Ctrl+F "g_base_addr". Add `0x310000000` to the starting one and you have your range.

**Comment by cglmrfreeman** [comment]
"g_base_addr" not found in my logs...

**Comment by VelocityRa** [comment]
You need to set the notice log level. 
This is turning into unrelated support, please refrain from posting here anymore about this, use our Discord.

**Comment by cglmrfreeman** [comment]
The feature requested was closed as a duplicate, I came into the issue where where it was initially marked which would offer that type of support I needed. I opened discussion of how that feature might be useful until the "Save state" was implemented while very limited options of what I can do to achieve what I wanted are currently available. This issue has been stale for many months, and I'm actively participating in the PR that will resolve this issue. If someone else were looking for the same thing I needed, they would probably find it here, so the discussion is healthy, but this is the last thing I will comment here.
