### ISSUE TITLE
Shader compilation error [NPUB30096]

### ISSUE THREAD

**Issue by kapodamy** [RPCS3/rpcs3#4220]
**Game**: Hard Corps: Uprising [NPUB30096]

**Commit**: v0.0.5-6463-7753ac60b Alpha | HEAD

**Renderer**: OpenGL

**Specs**: 
1. Intel(R) Core(TM) i3-4130 CPU.
2. Intel(R) Graphics HD 4400 GPU.

**Issue** : game crash after level loading (pressing X to play).

**Extra**: 

1. Tested with any cache cleared.
2. Interpreters also doesn't work.

**Log**: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1758996/RPCS3.log.gz)
```
E {rsx::thread} RSX: Failed to compile shader: ERROR: 0:48: 'Error' : Cannot offset into the vector 
ERROR: 0:48: 'assign' :  cannot convert from 'const 4-component vector of float' to 'float'
ERROR: 0:50: 'Error' : Cannot offset into the vector 
ERROR: 0:50: 'assign' :  cannot convert from 'const 4-component vector of float' to '3-component vector of float'
ERROR: 0:52: 'Error' : Cannot offset into the vector 
ERROR: 0:52: 'assign' :  cannot convert from 'const 4-component vector of float' to '3-component vector of float'
```

**Comment by kd-11** [comment]
Another intel driver bug. The compiler is unable to handle statements in the form
`reg.xyz = clamp(vec4, 0., 1.).xyz;` which is a serious flaw. There are many other bugs with their compiler that are difficult to work around, for example, replacing the [0,1] range with [-65504,+65504] mysteriously works. It also refuses to accept the register name h8, does not support vector component indexing, etc, etc
