### ISSUE TITLE
Feature Request ( NOT AN ISSUE ): Instant input swithing support

### ISSUE THREAD

**Issue by M220** [RPCS3/rpcs3#4221]
Problem is that when you change the input while you are ingame ( like disabling a controller accidantally or simply want to continue the game with another input ) just changing the input in the pads setting will not work and you have to close the game and then change the pads setting and then reopen the game.
But some emulators have real-time input detection, this emulators are :
- PCSX2
- CEMU
- Dolphin
- PPSSPP
- Citra
You guys can port their ( related to this feature ) PRs in your emulator so RPCS3 support this Feature too!
And because megamouse is the one who do input works so I'm going to summon him here :D
@Megamouse
Thank you guys for your wonderful job!

**Comment by Megamouse** [comment]
That should be working soon. Just wait

**Comment by Megamouse** [comment]
Well this took a bit longer due to some Projekt-Management issues.

Implemented in #5426
