### ISSUE TITLE
Zone of the Enders no longer goes ingame ( #4079 Regression )

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#4229]
After #4079 merged Zone of the Enders 1 (Standalone and HD Collection) started to randomly freeze during the intro Konami logo video.

Tried a bunch of builds and it definitely seems to be this pull request which broke it. Cleared Cache + LLVM Cache as well.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1765501/RPCS3.log.gz)

**Comment by kd-11** [comment]
That PR only adds the thread scheduler. The rest are minor fixes that wouldn't affect stability (shader code updates and a single command flush on vulkan only). This would point to the game not having been stable to begin with. Try disabling thread scheduler and see if it helps. Also, dont use "preferred spu threads" option if testing unstable titles, games with race condition issues dont always fare too well. Ironically, sometimes setting the preferred threads to 1 can help some of the more unstable titles by slowing things down.

**Comment by Asinin3** [comment]
Still freezes with SPU preferred threads 1 and no scheduler. I did run it a bunch of times but it may be possible that its a race condition however the build before #4079 was merged did seem to go ingame every time.
