### ISSUE TITLE
All Macross Games

### ISSUE THREAD

**Issue by SiTWulf** [RPCS3/rpcs3#4233]
Hi.

I make a test of all Macross Games in RCPS3. (Im a Fan from Macross Games, and downloading the RCPS3 emulator for play this games)
Tested in RCPS3 0.0.5 6480

Macross Trial Frontier. [BLJS93001]
* Ingame (only random crashes due Mem Reading Bugs).
* Incorrect Lights. (Hard to play with brightness in Stage 3+)
* Incorrect Shadows.
* Incorrect Depth.

Macross Last Frontier. [BLJS93004]
* Ingame (only one stage works (Stage 3)).
____ Stage 1 Crash on Loading.
____ Stage 2 only show Take Off and Crash on Loading.
____ Stage 3 ingame (Heavy Light/Shadows Error). 
* Incorrect Lights.
* Incorrect Shadows.
* Incorrect Depth.

Macross 2012. [BLJS93007]
* Only Main Menu. (no Intro)
* Crash on Loading.
F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsx_cache.h:88)

Macross 30 -Voices across the galaxy - [BLJS10184]
* Sometimes crash on Install 
* Crash on Loading intro video. (Black Screen)

**Comment by AniLeo** [comment]
Reporting games statuses must be done on our forums. Please read the issue guidelines.
