### ISSUE TITLE
Demon's Souls after #4204 

### ISSUE THREAD

**Issue by Dani1977** [RPCS3/rpcs3#4235]
Hi,
i try demon's souls after PR#4204, and I saw a loot of this line:

·U 0:03:12.633318 {PPU[0x1000017] Thread (NexusRevolution Main) [0x00b5f384]} sceNp TODO: sceNpManagerGetNpId(npId=*0xd0251864)
·U 0:03:12.633326 {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e13e64]} sceNp TODO: sceNpManagerGetOnlineName(onlineName=*0xd0251888)
·U 0:03:12.633329 {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e13e74]} sceNp TODO: sceNpManagerGetAvatarUrl(avatarUrl=*0xd02518bc)
·W 0:03:12.633347 {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d30f74]} sys_lwmutex: _sys_lwmutex_create(lwmutex_id=*0xd0251660, protocol=0x2, control=*0xd0251890, arg4=0x80000001, name=0xd0251880, arg6=0x0)
·W 0:03:12.633351 {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d30f74]} sys_lwmutex: _sys_lwmutex_create(lwmutex_id=*0xd02515c0, protocol=0x2, control=*0xd0251860, arg4=0x80000001, name=0xd0251888, arg6=0x0)
·W 0:03:12.633359 {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d31218]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x95060d00)
·W 0:03:12.633363 {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d31218]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x95060c00)

The game with vulkan looks playable (never used opengl)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1771177/RPCS3.log.gz)

Regards

**Comment by Asinin3** [comment]
Those are warnings and Todo's not even errors

**Comment by isshininu** [comment]
I agree.

We must stop this spam in log.

**Comment by Dani1977** [comment]
Thanks for reply,
with this "spam" of logs, the perceptual of my cpu usage is close to 100%, before was around 20 - 40 % .
Thanks

**Comment by AniLeo** [comment]
Then disable logging on your config file if you don't want to see it, or just disable sceNp related modules logging.

**Comment by Dani1977** [comment]
@AniLeo Thanks for the advise
