### ISSUE TITLE
The Simpsons Game [BLES00142] audio not synchronized with the video

### ISSUE THREAD

**Issue by greggameplayer** [RPCS3/rpcs3#4238]
## RPCS3 Build Version Used :
RPCS3 0.0.5-6491-f96e9b6ed Alpha

## Hardware specs :
- Nvidia GeForce GTX 960
- AMD FX-6300
- 8 GB Of Ram
- Windows 7 Pro

## The Issue :
When you launch the game at the beginning in the 70th century fox screen, in the gracie films screen and in all cinematics of this game, you'll see that the audio is played before the video, and the audio have also some stutters.

## Log :
[→ Click Here ←](https://gist.github.com/greggameplayer/d130d41052b39eff0c4fcefc28b2c09b)

**Comment by greggameplayer** [comment]
@kd-11 , @Nekotekina or another person can help me please

**Comment by AniLeo** [comment]
This isn't support forums, and your CPU is too weak. don't spam tag people.

**Comment by greggameplayer** [comment]
this is not a support that i request, i explain an issue

**Comment by AniLeo** [comment]
How are you not requesting support by pinging people and asking them for help? ...
If you're reporting an issue, it's reported, now leave it here and wait for it to be fixed.

**Comment by greggameplayer** [comment]
ok

**Comment by greggameplayer** [comment]
resolved by a PR

**Comment by matthew17777** [comment]
how did you fix this i have the same issue

**Comment by YuriNator557** [comment]
Commenting on a closed issue from 4 years ago isn't going to give you a fix, ask for help in the discord server or the forums

**Comment by matthew17777** [comment]
im rly new how do i do that

**Comment by Darkhost1999** [comment]
https://forums.rpcs3.net/

https://discord.com/invite/Af7H9yp
