### ISSUE TITLE
Demon's Souls - {rsx::thread} RSX: Unknown vp opcode 0x1c [Vulkan regression]

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4242]
Sympthoms: booting game now causes this error and game stop.
Pressing "continue" icon in RPCS3 game allows game to continue, but without sound.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1776845/RPCS3.log.gz)

**Comment by isshininu** [comment]
·W 0:01:31.589459 {Audio Thread} XAudio2Thread : too many buffers enqueued (33, pos=0)

**Comment by kd-11** [comment]
Delete your shaders cache as it seems to be corrupted. Also remove /dev_hdd1/cache
