### ISSUE TITLE
Chainsaw Lollipop Canot Access Juliets Room

### ISSUE THREAD

**Issue by sabi3293043** [RPCS3/rpcs3#4244]
i tried everything all ppu settings all spu settings directx to volcan to open gl

i get
F {PPU[0x1000000] Thread (main_thread) [0x00922878]} MEM: Access violation reading location 0x6c
in the log

Type: class ppu_thread
State: 0x104[s|PAUSE]
Priority: 2000
Stack: 0xd0001000..0xd0040fff
Joiner: detached
Commands: 0

Registers:
=========
GPR[0] = 0x922854
GPR[1] = 0xd003f130
GPR[2] = 0x198f168
GPR[3] = 0x205000f8
GPR[4] = 0x38
GPR[5] = 0x8
GPR[6] = 0x0
GPR[7] = 0xd003ed00
GPR[8] = 0x21eae540
GPR[9] = 0xffffffff
GPR[10] = 0x205000f8
GPR[11] = 0x0
GPR[12] = 0x192e328
GPR[13] = 0x20007060
GPR[14] = 0x21eae540
GPR[15] = 0x0
GPR[16] = 0x0
GPR[17] = 0x30
GPR[18] = 0x1
GPR[19] = 0xd003ff70
GPR[20] = 0x19dc494
GPR[21] = 0x19d0000
GPR[22] = 0x0
GPR[23] = 0xd003fe80
GPR[24] = 0x1
GPR[25] = 0xd003ff70
GPR[26] = 0x19dc494
GPR[27] = 0xd003fe08
GPR[28] = 0x0
GPR[29] = 0x205000f8
GPR[30] = 0x204e0010
GPR[31] = 0x1
FPR[0] = -8.05043E+08
FPR[1] = 0
FPR[2] = 0
FPR[3] = 0.0005
FPR[4] = -0.141139
FPR[5] = 0.258361
FPR[6] = 8.10117E+06
FPR[7] = 2.12795E+07
FPR[8] = 1
FPR[9] = 0.75
FPR[10] = 0.477592
FPR[11] = -1.29289
FPR[12] = 0
FPR[13] = 0.973644
FPR[14] = 0
FPR[15] = 0
FPR[16] = 0
FPR[17] = 0
FPR[18] = 0
FPR[19] = 0
FPR[20] = 0
FPR[21] = 0
FPR[22] = 0
FPR[23] = 0
FPR[24] = 0
FPR[25] = 0
FPR[26] = 0
FPR[27] = 0
FPR[28] = 0
FPR[29] = 0
FPR[30] = 0.258861
FPR[31] = 0
VR[0] = 0x80000000800000008000000080000000 [x: -0 y: -0 z: -0 w: -0]
VR[1] = 0x00000000000002000000020000000000 [x: 0 y: 7.17465e-43 z: 7.17465e-43 w: 0]
VR[2] = 0x3c010204bf800000bf800000bf800000 [x: 0.00787402 y: -1 z: -1 w: -1]
VR[3] = 0x3c010204bf800000bf800000bf800000 [x: 0.00787402 y: -1 z: -1 w: -1]
VR[4] = 0x3c010204bf800000bf800000bf800000 [x: 0.00787402 y: -1 z: -1 w: -1]
VR[5] = 0x3c010204bf800000bf800000bf800000 [x: 0.00787402 y: -1 z: -1 w: -1]
VR[6] = 0x000000003fc848490000000000000000 [x: 0 y: 1.56471 z: 0 w: 0]
VR[7] = 0x00000000400080810000000000000000 [x: 0 y: 2.00784 z: 0 w: 0]
VR[8] = 0x00000200018f00000000000000000000 [x: 7.17465e-43 y: 5.25299e-38 z: 0 w: 0]
VR[9] = 0xffffffffffffffffffffffffffffffff [x: -nan y: -nan z: -nan w: -nan]
VR[10] = 0x80000000800000008000000080000000 [x: -0 y: -0 z: -0 w: -0]
VR[11] = 0x80000000800000008000000080000000 [x: -0 y: -0 z: -0 w: -0]
VR[12] = 0x00000000000004000000040000000000 [x: 0 y: 1.43493e-42 z: 1.43493e-42 w: 0]
VR[13] = 0x3f8000003f800000ffc00000ffc00000 [x: 1 y: 1 z: -nan(ind) w: -nan(ind)]
VR[14] = 0x3f8000003f8000003f8000003f800000 [x: 1 y: 1 z: 1 w: 1]
VR[15] = 0x0000000043ac55c70000000000000000 [x: 0 y: 344.67 z: 0 w: 0]
VR[16] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[17] = 0x80000000800000008000000080000000 [x: -0 y: -0 z: -0 w: -0]
VR[18] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[19] = 0x80000000800000008000000080000000 [x: -0 y: -0 z: -0 w: -0]
VR[20] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[21] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[22] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[23] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[24] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[25] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[26] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[27] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[28] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[29] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[30] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[31] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
CR = 0x24000044
LR = 0x922854
CTR = 0x1b5762c
VRSAVE = 0xffffffff
XER = [CA=0 | OV=0 | SO=0 | CNT=0]
VSCR = [SAT=1 | NJ=1]
FPSCR = [FL=0 | FG=0 | FE=1 | FU=0]

Call stack:
=========
0x00922878 (0x0) called
> from 0x0094f1a0 (0x0)
> from 0x01505920 (0x0)
> from 0x00089cac (0x0)
> from 0x00090d3c (0x0)
> from 0x00090b68 (0x0)
> from 0x00089104 (0x0)
> from 0x000880b4 (0x0)
> from 0x008d78ec (0x0)
> from 0x0050e2c8 (0x0)
> from 0x0050e840 (0x0)
> from 0x0050e92c (0x0)
> from 0x0050e92c (0x0)
> from 0x003fc110 (0x0)
> from 0x0037a9d4 (0x0)
> from 0x0094d4f0 (0x0)
> from 0x0093568c (0x0)
> from 0x00917904 (0x0)
> from 0x00917bb8 (0x0)
> from 0x009509ac (0x0)
> from 0x00950740 (0x0)

and thats from the debug menu from that address

i hope it gets fixed

other wise the game is playable even when i am playing it on a crappy laptop
just not being able to change costume and stuff frustrates me

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
