### ISSUE TITLE
Regression Resident Evil 4 [NPEB00342]

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#4245]
When Go To Ingame show Error
"MEM: Access violation reading location"

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1777885/RPCS3.log.gz)

**Comment by greggameplayer** [comment]
there are multiple problems :

> (main_thread)} Thread time: 10.015625s (27.931789Gc); Faults: 2 [rsx:1, spu:0];

> {MFC Thread} Thread time: 4.687500s (16.831249Gc); Faults: 6 [rsx:6, spu:0];

> {PPU[0x1000002] Thread (asyncReader_RD)} Thread time: 1.062500s (2.978616Gc); Faults: 44 [rsx:44, spu:0];

> {SPU[0x2000002] Thread (CellSpursKernel2)} Thread time: 33.562500s (98.375697Gc); Faults: 143 [rsx:143, spu:0];

And also anyone can put the regression label please

**Comment by greggameplayer** [comment]
The error was probably corrected by a PR

**Comment by greggameplayer** [comment]
I think it's because the first time you launch RPCS3 the controls files are not created so there is a bug for me when i tested The Simpsons Game in this case, the game said that i have to reconnect my controller but after a reboot of RPCS3 this error has disappeared so i supposed it's because of the No NPDRM control info found errors appear only on the first time you launch RPCS3.

**Comment by aakh1361** [comment]
@Zangetsu38 
but for me in this place game have freeze and show error
"MEM: Access violation reading location"

![image](https://user-images.githubusercontent.com/25039098/36940062-20aa3e2e-1f51-11e8-8ae8-ee8bca1a8661.png)

**Comment by greggameplayer** [comment]
have you tried in openGL and in vulkan ?

**Comment by kd-11** [comment]
Does replacing rpcs3.exe with an older one work? The game runs just fine for me as well.

**Comment by Asinin3** [comment]
Why is that image in 4:3 make sure you're running the game at 16:9 1280x720 it helps compatibility.

**Comment by aakh1361** [comment]
i Delete Old Folder rpcs3 and Install new full rpcs3 whit firmware 4.81 and single game resident evil 4 but have same problem

opengl 16:9 1280x720

![image](https://user-images.githubusercontent.com/25039098/36970297-559a723e-207d-11e8-83f3-0acb6bf1f316.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1780441/RPCS3.log.gz)

**Comment by greggameplayer** [comment]
try with vulkan said the result with that graphic motor

**Comment by Zangetsu38** [comment]
also, you have again 4/3 resolution, select 16/9

**Comment by greggameplayer** [comment]
In order to have the game properly work on your device, you have to choose a compatible resolution written on the menu of RPCS3.

**Comment by aakh1361** [comment]
same result
select 16/9
vulkan and opengl

![image](https://user-images.githubusercontent.com/25039098/37146599-743091f2-22d9-11e8-914a-3929c8ce5bc4.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1792759/RPCS3.log.gz)


![image](https://user-images.githubusercontent.com/25039098/37146825-1f45062c-22da-11e8-8a42-fc1bef0e0e38.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1792789/RPCS3.log.gz)

**Comment by Zangetsu38** [comment]
? your screen is not 16/9 but 4:3

**Comment by Zangetsu38** [comment]
![image](https://user-images.githubusercontent.com/5261759/37150687-e6a77df6-22d2-11e8-8d65-96b7173a84cd.png)
With this setting

**Comment by kd-11** [comment]
Access violation problems are a sign of missing/corrupted files. Especially when only one user has the issue. I'd suggest confirming the files are in working order as they are currently. This is why I asked about replacing only the exe with an older one.

**Comment by aakh1361** [comment]
@Zangetsu38 
Please Look In My Last Log (Vulkan and OpenGL) You See I Select 16/9 and also 1280x720
![image](https://user-images.githubusercontent.com/25039098/37215400-15339330-23cd-11e8-97fd-2181cc63f122.png)

@kd-11 
Ok
Possible My Files Is corrupted
