### ISSUE TITLE
Boot Loop in Space Ace [NPUB30386]

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#4246]
Game Have Boot Loop In Intro
just like "metal gear online" https://github.com/RPCS3/rpcs3/issues/3386

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1777934/RPCS3.log.gz)

**Comment by greggameplayer** [comment]
there is a problem here :

> line 13779 : {PPU[0x100001d] Thread (_libsail-vdec_copy)} Thread time: 27.531250s (82.229209Gc); Faults: 2693 [rsx:2693, spu:0];

This problem appear before or not ?

**Comment by aakh1361** [comment]
no this problem not exist before

when i select "Load auto +manual Selection" and libvedc.sprx game go to ingame

**Comment by greggameplayer** [comment]
I think that because when you select the option automatically select required libraries, it don't select libvedc.sprx.
Because the problem you report concern the libvedc.sprx, like i've notice in your log before.

And please @Nekotekina can you put the regression label.

**Comment by toccata10** [comment]
Rev7104, ArchLinux with mesa 18.1.4
Dragon's lair [NPUB30217] also has the same problem: it bootloops. With "load automatic + manual selection" with libvdec.sprx selected, it goes ingame. It looks like a slideshow then (even though the fps counter shows 60fps).

**Comment by benderscruffy** [comment]
still happens in RPCS3 v0.0.7-8717-2b8890b1
[RPCS3.loop.log.gz](https://github.com/RPCS3/rpcs3/files/3621266/RPCS3.loop.log.gz)
With "load automatic + manual selection" with libvdec.sprx selected, it goes ingame
here is the log
[RPCS3 ingame.log.gz](https://github.com/RPCS3/rpcs3/files/3621270/RPCS3.ingame.log.gz)

**Comment by benderscruffy** [comment]
can be closed now
