### ISSUE TITLE
Regression: #4162 GL/VK Graphical glitches in Kingdom Hearts 2.5 [BLES02070]

### ISSUE THREAD

**Issue by sycoforbidden** [RPCS3/rpcs3#4263]
There are graphical glitches on the characters in town, and my guess in all characters of the game, both in OPENGL and Vulkan.

These appear anytime GPU Texture Scaling is turned ON.

On an earlier build, rpcs3-v0.0.3-2017-10-09-6d6b2812_win64, this issue was not present. Tomorrow I may try to look for an updated build which does not have this issue as well, if you wish to fix this, or any of the logs.

PC Specs:
i7-4510U @ 2 GHz
GeForce 840M
8GB RAM

EDIT: It regressed in build 0.0.4-7975
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7975/artifacts

Vulkan examples:

![captura de ecra 2](https://user-images.githubusercontent.com/18195463/37236592-2c04811c-2401-11e8-8c4f-91b967d58521.png)
![captura de ecra 3](https://user-images.githubusercontent.com/18195463/37236593-2c281712-2401-11e8-9e6e-e1bc27f0bbab.png)
![captura de ecra 6](https://user-images.githubusercontent.com/18195463/37236594-2c4933ac-2401-11e8-9a47-8fd812d800c6.png)

OpenGL examples:

![captura de ecra 7](https://user-images.githubusercontent.com/18195463/37236616-53d6d6e0-2401-11e8-85f8-722665f43dd4.png)
![captura de ecra 8](https://user-images.githubusercontent.com/18195463/37236617-53fd3696-2401-11e8-9948-5aa61c48c1d8.png)
![captura de ecra 10](https://user-images.githubusercontent.com/18195463/37236618-542141a8-2401-11e8-8101-75ddc7a3956a.png)
![captura de ecra 15](https://user-images.githubusercontent.com/18195463/37236619-5441cefa-2401-11e8-97ad-f84b80f51c5b.png)
![captura de ecra 16](https://user-images.githubusercontent.com/18195463/37236620-548431d2-2401-11e8-9734-0d7ffe27c72c.png)

**Comment by AniLeo** [comment]
Need exact build where it regressed, saying it worked half year ago doesn't help much

**Comment by sycoforbidden** [comment]
The earliest build i could find working was 0.0.4-7952

It regressed in build 0.0.4-7975
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7975/artifacts

**Comment by Fwha** [comment]
Just leave GPU Texture Scaling off since it doesn't happen when it's off.

**Comment by Illynir** [comment]
With the "Texture Scaling GPU" on OFF, some effects (such as depth of field in some cutscene) are missing.
It is not really a solution, moreover it is a regression that needs to be corrected.

**Comment by Fwha** [comment]
Which cutscenes because I didn't notice any that were missing. The only thing that was actually bad was a cutscene in Mulan's world that kept crashing the emulator and had a lot of graphical glitches in it but that was awhile ago. Don't know how that cutscene is now. When you actually complete Hercules' world and the title of the word is coming in had some graphical glitches too but that was still over a month ago.

**Comment by kd-11** [comment]
GPU texture scaling option used to do something very different from what it does now. Its on its way out for accuracy reasons. Most of what it used to do is now done automatically without need for the toggle.

**Comment by sycoforbidden** [comment]
I see, thank you people for the comments. I was only reporting since i have a low end PC, and turning that  option would affect performance.

**Comment by kd-11** [comment]
Update or close.

**Comment by SpeddieSwagetti** [comment]
On latest builds, graphical flickering of textures is present despite the GPU scaling option. Turning Force CPU Blit option ON fixes the flickering. The game used to function perfectly without any debug options enabled.

Force CPU Blit OFF
![Broken](https://user-images.githubusercontent.com/48142631/69492960-88e8f900-0ef4-11ea-83fa-f968f7c20b29.PNG)

Force CPU Blit ON
![Fixed](https://user-images.githubusercontent.com/48142631/69492984-d9605680-0ef4-11ea-8248-e08757ac8c90.PNG)

RSX Capture:
[BLES02070_20191124195317_capture.zip](https://github.com/RPCS3/rpcs3/files/3883409/BLES02070_20191124195317_capture.zip)

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3883410/RPCS3.log.gz)
@kd-11

**Comment by MarioSonic2987** [comment]
@SpeddieSwagetti That bug is already reported in #6822.
