### ISSUE TITLE
Linux binaries on download page are out of date

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#4264]
https://rpcs3.net/download
There's a difference between windows and linux versions
![selection_037](https://user-images.githubusercontent.com/7478580/37239628-a87c4494-243f-11e8-8a3c-172438e83b32.jpg)

**Comment by Megamouse** [comment]
I think that's because the build errored. we don't really have power over that. maybe nekotekina can try to restart it?

**Comment by AniLeo** [comment]
Can't do anything if Travis keeps failing to build
