### ISSUE TITLE
Lollipop Chainsaw [BLUS30917] Error: Not enough available space. 

### ISSUE THREAD

**Issue by Nikorasu95** [RPCS3/rpcs3#4266]
This issue didn't occur on a previous build. Sorry I don't remember the build. Its been 2 months since I messed around with RPCS3. Anyways the new build this issue is occurring on is 0.0.5-6519. The error is "Error: Not enough available space (terminate application). Space needed: 1174664412 KB."
I have terabytes of free space left over so I don't know why it's throwing this error. I also deleted the save data and cache to see if it would fix the issue, it didn't.
Specs:
i7 8700K @ 5.1GHz
RAM: DDR4 16GB @ 4200MHz
GPU: GTX 1080 Ti
OS; Windows 10 Pro x64

**Comment by Noiseko** [comment]
#3506

**Comment by greggameplayer** [comment]
close this issue please because of duplicated issue
