### ISSUE TITLE
Dragon ball raging blast 2 " transformations problem"  BUILD 0.0.5-847ee2aa

### ISSUE THREAD

**Issue by samipower** [RPCS3/rpcs3#4267]
Dragon ball raging blast 2 " transformations problem"
You can see in my video that when transformations happen, the game is slow and with wrong colours .

https://www.youtube.com/watch?v=iV_QicuEhWI

I have latest build and latest nvidia drivers.

I have intel i5 3570k and gtx 980 .

I saw olders builds 0.0.3 with vulkan that are working well but in gtx 1000 series.

In gtx 900 series vulkan option are not available in this older versions.

It is rare.

But in new builds vulkan available for both series. 900/1000.
¿nvidia driver guilty?

for example in 0.0.3 5878 and 0.0.3 5740 in theory works well but in gtx 1000 with vulkan.

But with these versions when I opened ...vulkan is missing... only open gl and dx12

Any idea??

**Comment by AniLeo** [comment]
Invalid report, read the guidelines.

1. Don't report stuff with non-master builds.
2. When reporting a regression, report latest working build, saying it worked on a build from over 6 months isn't helpful.
3. Missing information like logs, etc.

Reopen issue when you fix it.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by Zangetsu38** [comment]
@AniLeo it is not invalide issue, is very old issue that, cloth and lot effect have problem, during battle cloth is good, but during cutescenne before battle is broken, and kd already informed for that.

**Comment by AniLeo** [comment]
Need a proper report then
