### ISSUE TITLE
Missing (unpacked) dependencies on Linux AppImage

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#4271]
On ArchLinux, I can't launch the precompiled binaries anymore:
```
./rpcs3-v0.0.5-6509-ac82ecf3_linux64.AppImage: error while loading shared libraries: libGLEW.so.2.0: cannot open shared object file: No such file or directory
```
rpcs3-v0.0.5-6498-7233640c_linux64.AppImage was fine.
The size is much smaller now 44Mo=>19Mo, so the needed libraries are not included anymore.

**Comment by AniLeo** [comment]
Regression from #4269

**Comment by hcorion** [comment]
Fixed by https://github.com/RPCS3/rpcs3/commit/f2e5b6c35099cd7c575b350b997ca3793bf4f739
