### ISSUE TITLE
Folklore [BCES00050] have to delete cache folder in order to boot.

### ISSUE THREAD

**Issue by Nikorasu95** [RPCS3/rpcs3#4272]
The build i'm using is 0.0.5-c031122d. The error is : 
E {PPU[0x1000000] Thread (main_thread) [0x0063efc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/BCES00050//cg” [1]
E {PPU[0x1000000] Thread (main_thread) [0x0063efc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/BCES00050//cg” [2]
E {PPU[0x1000000] Thread (main_thread) [0x0063efc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/BCES00050//cg” [3]

This issue use to not happen, don't know which build it was though. Anyway's deleting the cache folder allows the game to boot.

**Comment by AniLeo** [comment]
DeS also depends on this sometimes. Maybe it's calling for the unimplemented sys cache clear function.

**Comment by Nikorasu95** [comment]
DeS? I have no idea what game that is.

**Comment by MarioSonic2987** [comment]
Demon's Souls.

**Comment by Nikorasu95** [comment]
Ahh, thanks.

**Comment by TheAnig** [comment]
With my latest commit, this issue has been solved, Folklore should be 100% playable now.

**Comment by AniLeo** [comment]
Closing as it's fixed per #4445 

Open a new issue if the issue reappears
