### ISSUE TITLE
Kingdom Hearts II Final Mix Roxas Slowdown

### ISSUE THREAD

**Issue by Sirius902** [RPCS3/rpcs3#4274]
When playing as Roxas doing any of the following: attacking, blocking, or jumping causes the game to slow from 30 fps to around 15 fps and once the attacking animation ends the game goes back to 30 fps. 
Generally whenever Roxas is on-screen. Once you become Sora this issue goes away as while attacking the game stays at 30 fps.

I don't know if I need to attach a log file for this issue but I haven't as the file is so big that pasting the text it in Pastebin causes Chrome to crash so I'm not sure how I would.

**Comment by Asinin3** [comment]
RPCS3 automatically gzips logs for you, after running the game you close rpcs3 and upload the RPCS3.log.gz file. Anyway this issue has been happening for a while, it's a known regression from one of the PRs last year. There is some more information in the forum threads.

**Comment by Sirius902** [comment]
Okay I just thought I'd report an issue since I hadn't heard about this before.

**Comment by Fwha** [comment]
A lot of people experience this but some people, like me, don't experience it.

**Comment by Asinin3** [comment]
This was fixed on the 20th of July, should be closed. https://github.com/RPCS3/rpcs3/pull/4876#issuecomment-406509121

**Comment by B1ackDaemon** [comment]
Closed.
