### ISSUE TITLE
Dante's Inferno[blus30405] physics bugs

### ISSUE THREAD

**Issue by Parthorisian** [RPCS3/rpcs3#4280]
Dante's Inferno is still too dark
Also in addition there is gamepad issue - sometimes(very often) without any LStick pushing hero starts run into the wall. Or abyss. He can be recovered with attempts pushing RStick for roll back or <x> hitting for jumping
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1805250/RPCS3.log.gz)
**PS3**
![qq](https://user-images.githubusercontent.com/35437970/37320007-b7099562-2682-11e8-9090-63e4e781e262.jpg)

**RPCS3**
![qw](https://user-images.githubusercontent.com/35437970/37320013-c4ce082c-2682-11e8-8db8-fe10e26c9993.jpg)
**PS3**
![qqw](https://user-images.githubusercontent.com/35437970/37320345-5d7154fc-2684-11e8-8730-9d7e64988817.jpg)

**RPCS3**
![qqq](https://user-images.githubusercontent.com/35437970/37320353-66d59e4a-2684-11e8-9b41-a1fc7a8c8089.jpg)
In addition - tutorial boss issue. Hero is just hanged somewhere above in air. Boss is unreachable
![qw](https://user-images.githubusercontent.com/35437970/37370504-7a2e6f3c-271d-11e8-9616-4087c755509d.jpg)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1808693/RPCS3.log.gz)

**Comment by Xcedf** [comment]
Darkness no longer an issue

**Comment by AniLeo** [comment]
Closing since there's already an open issue for physics
#3464
