### ISSUE TITLE
Some new QT assets seems to be unused and might be deleted

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4282]
I noticed some new QT platform assets are included inside new RPCS3 builds, so I checked what is not used and might be removed, so this is the list that not affect emulator funtionality at all:

bearer/
imageformats/
platforminputcontexts/
qmltooling/
scenegraph/
styles/
Qt5Quick.dll

This also frees about 6,3 mb of the build capacity.

**Comment by AniLeo** [comment]
At least styles are used I'm sure, imageformats are likely used as well

**Comment by Psycho-A** [comment]
After deleting all of them, all custom visual styles works good as before, and nothing bad happened with in-game overlay and other stuff.

**Comment by isshininu** [comment]
> After deleting all of them

Very strange way of debug, tho

**Comment by Megamouse** [comment]
i am pretty sure we need the bearers for the qnetwork stuff

**Comment by Psycho-A** [comment]
>  edit: also. maybe you have qt installed

No, I have not.

**Comment by Psycho-A** [comment]
I made dependencies checks, and here's the list of junk that *really* not referenced anywhere in rpcs3.exe and all of his child Qt dlls:

Qt5Quick.dll
|-- platforminputcontexts\*.dll
|-- qmltooling\*.dll
|-- scenegraph\*.dll

bearer\*.dll (network stuff *doesn't* references it, and managing compat.database works as well)
imageformats\*.dll

So I don't see the reason to keep this inside of release.

**Comment by Megamouse** [comment]
I was sure that it crashed on my laptop without the bearer folder.

you can always open a pull request btw.

**Comment by Megamouse** [comment]
Also we did nothing to add qtquick. It just appeared out of nowhere so it seems

**Comment by Psycho-A** [comment]
You seems to be right, bearer and imageformats folders uses to search and load dlls inside of them, not directly by dll name. So its need to keep (although I have no any crashes). But qtquick is really orphaned stuff.

**Comment by Megamouse** [comment]
I easily managed to remove the qtquick on visual studio builds but I couldn't find out why they appear on the sppveyor artefacts. Probably are added by qml

**Comment by Psycho-A** [comment]
So what to do with this? I don't think it's good to carry some garbage stuff with software...

**Comment by AniLeo** [comment]
#4361 should take care of the unused Qt extensions

**Comment by AniLeo** [comment]
Solved via #4361
