### ISSUE TITLE
[Kingdom Hearts II Final Mix] Sound Cuts Out

### ISSUE THREAD

**Issue by Sirius902** [RPCS3/rpcs3#4287]
I was fighting the big door heartless in Beast's Castle and all sound stopped playing. But not only that, when I died the game softlocked. The screen faded to white, which is normal, but then instead of asking me if I wanted Mickey Mouse to come save me, the loading indicator in the bottom right was spinning forever. I have attached the log and a video I recorded in OBS if it helps. On other occasions when the sound has cut out completely and the game didn't crash, the sound will not return until you restart the emulator.

RPCS3 build 6514

Windows 10 Creators Update
Intel(R) Core(TM) i7-6700 CPU
NVIDIA GeForce GTX 980 Ti

Here's the log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1809221/RPCS3.log.gz)

And the video:
[KH2FM Crash.zip](https://github.com/RPCS3/rpcs3/files/1809230/KH2FM.Crash.zip)

**Comment by Asinin3** [comment]
I would set Preferred SPU Threads to auto not 1, and if you're going to use resolution scale it's best to leave resolution on 1280x720 as that's what we scale from anyway. As far as the infinite loading screen, this seems like a random error, and will probably work on a game restart. 

Some rare issues like this don't stop a game from being Playable. If it persists and is a confirmed regression we can look into moving it back to ingame though. 

You may want to update RPCS3 as it will have kd-11's new changeset which might improve rendering in performance in KH.

**Comment by Sirius902** [comment]
Alright. But what about the sound issue? It seems like when I've been playing a game for a while all sound will stop playing.

**Comment by Sirius902** [comment]
The only games I've played on the emulator so far is Kingdom Hearts Re Chain of Memories and Kingdom Hearts II Final Mix, and the sound has cut  out randomly on both.

**Comment by Sirius902** [comment]
At some point soon I'll play BBSFM and KHFM and test to see if the sound cuts out in those games as well and I'll report back.

**Comment by Asinin3** [comment]
When the audio thread in a game dies it's common for the game to run for a bit then crash. Generally speaking turning off SPU "hacks" such as lowering spu threads or the additional spu options can help.

**Comment by Sirius902** [comment]
As you said I changed SPU Threads to Auto and started playing and the sound cut out again.

**Comment by Sirius902** [comment]
It's happening almost every time I try to play a game. Once the sound disappeared while I was on the title screen trying to load a game.

**Comment by Sirius902** [comment]
Just opened JP KH2FM and waited on the title screen to see what would happen and it happened again. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1817666/RPCS3.log.gz)

**Comment by Sirius902** [comment]
Though this has happened countless times, usually ending in crashes due to access violations, I've made a new discovery which could help narrow the issue down with a log included. I was fighting Xemnas in the final battle and the sound stopped playing but when the final cut-scene fmv movie started playing the sound came back. And it continued playing until the fmv stopped and the sound was once again gone on the report screen and before I could save my game; the game crashed.

Here's the log file:
[Final Battle Crash.log.gz](https://github.com/RPCS3/rpcs3/files/1844014/Final.Battle.Crash.log.gz)

**Comment by Sirius902** [comment]
@Asinin3 Though this has happened countless times, usually ending in crashes due to access violations, I've made a new discovery which could help narrow the issue down with a log included. I was fighting Xemnas in the final battle and the sound stopped playing but when the final cut-scene fmv movie started playing the sound came back. And it continued playing until the fmv stopped and the sound was once again gone on the report screen and before I could save my game; the game crashed. Hopefully this issue can be resolved.

Here's the log file:
[Final Battle Crash.log.gz](https://github.com/RPCS3/rpcs3/files/1844015/Final.Battle.Crash.log.gz)

**Comment by Sirius902** [comment]
As a side note, it seems to happen faster when using recording software. I use Open Broadcasting Software.

**Comment by Sirius902** [comment]
@Asinin3  As a side note, it seems to happen faster when using recording software. I use Open Broadcasting Software.

**Comment by AniLeo** [comment]
Needs retesting

**Comment by Sirius902** [comment]
I've retested it and the issue seems to be fixed.
