### ISSUE TITLE
Shadows of the damned[blus30653] wrong rendered objects+performance slowdown

### ISSUE THREAD

**Issue by Parthorisian** [RPCS3/rpcs3#4288]
**shadows of the damned[BLUS30653]**
**[UPDATED]** Log [ShadowsoftheDamned_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2025002/ShadowsoftheDamned_RPCS3.zip)

**[EDIT]:** Load menu for **PS3**
<img width="640" alt="sod00" src="https://user-images.githubusercontent.com/35437970/40346758-7f3a661a-5da6-11e8-9242-de24c3cecbfa.png">

Load menu for **RPCS3** - fleming castle isnt fully rendered but completely solid, even for increased brightness (playtime works for now, since 6590!)
![sod001](https://user-images.githubusercontent.com/35437970/40348243-c4ec5d4e-5dab-11e8-937e-acb8457430ab.png)

Ingame image for now is almost same as for PS3
**PS3**
![qq](https://user-images.githubusercontent.com/35437970/37444518-b46da020-281a-11e8-952c-c999cafbb277.jpg)
**RPCS3**
![sod04](https://user-images.githubusercontent.com/35437970/40341270-d843822e-5d8c-11e8-8e88-5e8ac642ba97.png)

Image distortion in demon opera(chapter1) is fixed. Was fixed even lamp lights(only for Strict mode), 
**nonStrict mode** ![sod03](https://user-images.githubusercontent.com/35437970/40343320-f5b45ab2-5d97-11e8-99be-f71a76b7606c.png)
**Strict mode** ![sod04](https://user-images.githubusercontent.com/35437970/40343322-f5d5472c-5d97-11e8-9f94-22d4055e7f60.png)

but unfortunately performance sometimes is slowed down for now
![sod01](https://user-images.githubusercontent.com/35437970/40342825-7835e260-5d95-11e8-84c8-f9f07dd60a58.png)
![sod01](https://user-images.githubusercontent.com/35437970/40341858-2728c8c4-5d90-11e8-9832-472e5154a460.png)
![sod02](https://user-images.githubusercontent.com/35437970/40341859-274ef77e-5d90-11e8-96dc-96967bd9ea57.png)
![sod03](https://user-images.githubusercontent.com/35437970/40341860-276ee4bc-5d90-11e8-896c-31c792cf6440.png)

**Comment by isshininu** [comment]
https://github.com/RPCS3/rpcs3/issues/4168

**Comment by Megamouse** [comment]
I can't say much about the image distortion (demon opera, chapter1), but fixed red stuff in #4312

![image](https://user-images.githubusercontent.com/23019877/37714691-7b1c227e-2d1a-11e8-9c2d-9ad715355a4e.png)
![image](https://user-images.githubusercontent.com/23019877/37714814-c7bcc73c-2d1a-11e8-8988-33379dc1da3d.png)

**Comment by Parthorisian** [comment]
Excellent news, cant wait for proper build. Sorry for
> Relegated to WIP status until the supporting patches

**Comment by IbanPetrov** [comment]
Now[#4312](https://github.com/RPCS3/rpcs3/pull/4312) game contains tons of red. In strict mode ive dont noticed important issues. Playable

**Comment by Parthorisian** [comment]
![sod6592](https://user-images.githubusercontent.com/35437970/37885845-2409f4ee-30c0-11e8-8126-3d44c48ea435.jpg)

**Comment by Asinin3** [comment]
![image](https://user-images.githubusercontent.com/15137035/40350258-cc4c1452-5d98-11e8-982c-637ea46931db.png)
It's time to stop :D it spams the github tracker and preview button exists.

**Comment by Parthorisian** [comment]
No need to hide problems. They are still exists https://youtu.be/HOmna9hRmOk
timestamp 0:34 - Garcia disappearing!. Performance slowdown even for i7-7700 is really bad(his spec in description)

**Comment by Parthorisian** [comment]
Closed as fixed #5427
