### ISSUE TITLE
Add support for platinum trophies.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4289]
![433](https://user-images.githubusercontent.com/6324523/37486802-09c69192-28a9-11e8-9954-5769e0e409a0.png)
![435](https://user-images.githubusercontent.com/6324523/37486808-0e9af442-28a9-11e8-85e6-019180d1977d.png)
This is what i got today.

**Comment by ildomar00** [comment]
oi boa noite estou com bug nos trofeus platina de god of war chains of olympus e god of war ghost of sparta completei todos os trofeis porem nao libera o platina

hi good night i have bug in the god of war platinum trophies olympus chains and god of war sparta ghost completed all the trophies but does not release the platinum

**Comment by AniLeo** [comment]
Platinum Trophy support is not yet present

**Comment by Megamouse** [comment]
Closing as the mentioned PR was merged.
