### ISSUE TITLE
Project Diva F 2nd [NPJB00435] - AMD Driver Crash

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#4301]
Project Diva F 2nd [NPJB00435] is hard crashing AMD Drivers (tested on latest 18.3.2, R9 280X and Windows 7, Vulkan)

How to reproduce:
1. Boot with clean shader cache.
2. A little after compiling 11th shader, game will hard crash AMD driver.

Debug Output doesn't catch anything.

**Comment by AniLeo** [comment]
On M260 and Windows 10 it doesn't hard crash drivers, it throws fatal error on amdvlk64.dll

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/4344

**Comment by AniLeo** [comment]
Fixed by #4344. Tested with 18.3.3, R9 280X, Windows 7 and Vulkan.

**Comment by kd-11** [comment]
Closing as fixed via https://github.com/RPCS3/rpcs3/pull/4344.
