### ISSUE TITLE
Performance regression after #4265

### ISSUE THREAD

**Issue by scribam** [RPCS3/rpcs3#4307]
After PR #4265 gets merged, I notice a performance regression in all the games I tested. For example, in Devil May Cry HD Collection, FPS doesn't go above 2 whereas I could reach 60 FPS before. Logs seem to be slower as well.

System specs:
- OS: Antergos
- Kernel: x86_64 Linux 4.15.10-1-ARCH
- CPU: Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz | 8 Threads | 15.57 GiB RAM | AVX+
- GPU: AMD Radeon HD 8790M
- Mesa 17.3.6

RPCS3:
- Default settings
- OpenGL
- "Delete Shaders Cache" before each test

Good: 07cbf3da48974ed49649b7823bdc75d444424e7d, [RPCS3-07cbf3da4.log.gz](https://github.com/RPCS3/rpcs3/files/1824982/RPCS3-07cbf3da4.log.gz)
Bad: ffe6c9ba5a10dfccdf235446d974456ae5329880, [RPCS3-d13584f85.log.gz](https://github.com/RPCS3/rpcs3/files/1824983/RPCS3-d13584f85.log.gz)
Commits between these two revisions don't build on Linux.

**Comment by kd-11** [comment]
Any other linux users having this problem? @toccata10 @greentop Plz help
60 fps to 2 sounds like something is seriously wrong other than it being a simple case of bad optimization for mesa. Thats about half a second increase in frametime which is ridiculous. Is vulkan also affected? How about null renderer? Is it all games (samples included)? Does it happen with both appimage and local builds as well?
I've lost the ability to use mesa+ogl on my system in the interim until I find a permanent solution to having nvidia's horrendous glx stack coexist with mesa. Radv is usable with minor issues (after some significant reworking of the swapchain code)

**Comment by kd-11** [comment]
@scribam I forgot to mention - you need https://github.com/RPCS3/rpcs3/commit/d13584f8587ec35fc3764098518a3083db8b92ec for mesa to work properly. I merged it earlier today.

**Comment by 13xforever** [comment]
I have antergos with proprietary nvidia drivers and perf is the same

**Comment by Asinin3** [comment]
Seems like the same problem as what gamedev was happening with Ninja Gaiden Sigma, guess it's specific to linux. Apparently he compiled RPCS3 and performance went back to normal.

**Comment by scribam** [comment]
- Null Renderer is fine, running at full speed with a black screen
- This issue also exists with samples, tested with gs_gcm_basic_triangle.elf and gs_gcm_cube.elf
- I use a local build with the following option: `-DUSE_SYSTEM_FFMPEG=ON -DUSE_SYSTEM_LIBPNG=ON -DUSE_VULKAN=OFF`
- I have the same issue with an AppImage, version tested: `rpcs3-v0.0.5-6545-d13584f8_linux64.AppImage`

About Vulkan, even with the package [vulkan-radeon](https://www.archlinux.org/packages/extra/x86_64/vulkan-radeon/) and an AppImage (which includes Vulkan support), I can not see my graphic card in RPCS3. Same for `vulkaninfo`. Only my integrated graphic card (Intel HD Graphics 4600) is displayed thanks to the `vulkan-intel` package but not usable with RPCS3:
```
F {rsx::thread} St13runtime_error thrown: No hardware support for z24s8
(in file ../rpcs3/Emu/RSX/VK/VKFormats.cpp:40)
```

**Comment by toccata10** [comment]
With my r9 fury, i7 4770k, on Arch, I don't have any performance regression on my config (OpenGl, radv is slow, as usual). SoulCaliburIV goes from 40-43 to 45-47fps, SoulCaliburV stays the same around 30fps, TekkenTag2:60fps. DevilMayCryHd (episode 1):60fps.
So either a bit better or the same for me. Tested version: 6545

**Comment by greentop** [comment]
@kd-11 The Appimage has a significantly slower shader compile time when compared to a local build from the current Master. Other than that, the performance is looking good under the Nvidia proprietary driver. (Probably not very helpful here.) Test results follow below. 

**Ubuntu 16.04
Nvidia 390.25
i7 3770**

**Master as of d13584f:**

ToCS2-
	Vulkan: 30FPS
 
Hyperdimention Neptunia-
	OpenGL: 26 FPS / Vulkan (High Precision Z-Buffer enabled): 30 FPS
 
Disgaea 4-
	Vulkan: 77 FPS / OpenGL: 49 FPS
 
Atelier (Arland)-
	OpenGL: 60 FPS / Vulkan: 60 FPS

gs_gcm_basic_triangle.elf-
	Vulkan: 657 FPS / OpenGL: 1339 FPS


**AppImage rpcs3-v0.0.5-6545-d13584f8_linux64:**

ToCS2- 
	Vulkan: 30FPS & Sluggish shader compiling  

Hyperdimention Neptunia- 
	OpenGL: 26 FPS / Vulkan (High Precision Z-Buffer enabled): 30 FPS

Disgaea 4 -
	Vulkan: 74 FPS / OpenGL: 49 FPS 

Atelier (Arland): 
	OpenGL: 60 FPS / Vulkan: 60 FPS

gs_gcm_basic_triangle.elf-
	Vulkan: 633 FPS / OpenGL: 1295 FPS

**Comment by kd-11** [comment]
Thanks. Thats as expected - nothing much was changed for opengl other than removal of a redundant makecurrent call before swapbuffers. Optimizations should have improved performance slightly but the altered code had nothing to do with opengl at all. @scribam You'll need to find a way to profile the code as the bug seems specific to your setup. Its the only way to figure out where all that time is being spent.
