### ISSUE TITLE
Option to disable compiling ppu modules message boxes

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#4310]
It would be nice to have an option to hide these message boxes popping up (and stealing) the focus, so forbidding to do anything else. That's a job for @Megamouse.

**Comment by Megamouse** [comment]
no. this is useless. It will be fixed once the magical unified compile dialog was created

**Comment by toccata10** [comment]
Ok. Waiting eagerly for this nice upcoming feature.

**Comment by Megamouse** [comment]
well. we all are xD
