### ISSUE TITLE
[BLES01987] The Witch and the Hundred Knight enemies despawn/die?

### ISSUE THREAD

**Issue by Fwha** [RPCS3/rpcs3#4318]
Enemies seem to despawn and even if you manage to kill one before it does despawn, it doesn't count towards anything. When you get to the point where the game is teaching you about locking on, you can't lock on to the monster that spawns because it immediately despawns causing the tutorial prompt to come up over and over again. So it becomes impossible to get past the tutorial area. I think it might have something to do with the enemy scripts.

RPCS3 v0.0.5-6553-af89b6219 Alpha | HEAD
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz | 8 Threads | 15.96 GiB RAM | AVX+ | TSX

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1836084/RPCS3.log.gz)

**Comment by dio-gh** [comment]
Similarly to #4317, the underlying issue for this one has also probably been fixed since, as I cannot reproduce this on current master. Closeable.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3714492/RPCS3.log.gz)
