### ISSUE TITLE
[BLES01987] The Witch and the Hundred Knight graphical issue

### ISSUE THREAD

**Issue by Fwha** [RPCS3/rpcs3#4319]
Some of the graphics show just fine but the Hundred Knight only has some texture but not all. His reflection in the water shows what he's supposed to look like but his model is just black. Turning on Write Color Buffers makes the mask have a texture and same with the sword you get in the beginning + enemies have some texture aswell. They don't with WCB off. The hill with the door in the beginning also doesn't have any texture and is just black with the door flickering some texture at certain angles.
![untitled](https://user-images.githubusercontent.com/35583249/37751650-dfd50bb4-2d50-11e8-8ce6-fd0df048b0de.png)
![untitled1](https://user-images.githubusercontent.com/35583249/37751651-dff1d352-2d50-11e8-9b51-7ff80ae8178b.png)

RPCS3 v0.0.5-6553-af89b6219 Alpha | HEAD
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz | 8 Threads | 15.96 GiB RAM | AVX+ | TSX

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1836099/RPCS3.log.gz)

**Comment by dio-gh** [comment]
WCB is definitely required for this game, but that's not a bug. I don't see any issues with the hill / door area on current master either (see the pic below). Closeable.

![image](https://user-images.githubusercontent.com/10439488/66604050-a284ea00-ebad-11e9-94d2-450b395a353a.png)
