### ISSUE TITLE
[BLUS31460/BLJM61220] (KH 2.5 Eng/Jpn) Credits Crash

### ISSUE THREAD

**Issue by Sirius902** [RPCS3/rpcs3#4326]
After finishing the credits fmv movie the game crashes right before it displays your battle report and allows you to save your game with your clear data. I've tested this with the English and Japanese versions of KH2.5. So currently, I can't finish the game.  And in the log in the application while the emulator's running says:

F {SPU[0x2000002] Thread (_libsailCellSpursKernel1)} MEM: Access violation reading location 0x0

Though, this happens during the fmv and before the game crashes and after the fact it displays multiple similar messages to:

U {PPU[0x10000b1] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23015e00, flags=0x0, pOpt=*0x0)

Log from Eng version:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1844142/RPCS3.log.gz)

Log from JP version:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1844097/RPCS3.log.gz)

**Comment by Sirius902** [comment]
@Asinin3 Still happens on build 6693 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1959548/RPCS3.log.gz)

**Comment by Sirius902** [comment]
Again can confirm that the issue persists on build 6970.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2120895/RPCS3.log.gz)

**Comment by elad335** [comment]
Fixed by #5310

**Comment by jokoputera** [comment]
please recheck with the latest release

**Comment by Sirius902** [comment]
@jokoputera Confirmed no longer happens on latest master 10435.
