### ISSUE TITLE
Shovel Knight: Treasure Trove white screen

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#4327]
nothing but a white screen
F {PPU[0x1000001] Thread (Game Thread) [0x00629abc]} MEM: Access violation reading location 0x0

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1844099/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Need information, since this is a regression, need to know in which build it regressed
https://rpcs3.net/builds

**Comment by AniLeo** [comment]
Not an issue on latest master, tested with both PPU Interpreter Fast and Recompiler LLVM.

![image](https://user-images.githubusercontent.com/10283761/37869721-e0613326-2fb4-11e8-9b46-5614726615ba.png)

You likely have a bad dump or something on your RPCS3 setup is broken.

**Comment by benderscruffy** [comment]
are you just testing shovel knight ???
as you can see in the title of my picture it says shovel knight treasure trove 
in your picture it does not have treasure trove in the title 
i know shovel knight works but not treasure trove
![treasure](https://user-images.githubusercontent.com/2696404/37871182-8c78dc12-301a-11e8-996e-298b75fe1d45.PNG)

**Comment by AniLeo** [comment]
The game ID is the same. Is that just the full version or is it an additional update to the base game?

**Comment by benderscruffy** [comment]
using 0.0.5-7428
still the same problem

**Comment by digitaldude555** [comment]
![Screenshot (3164)](https://user-images.githubusercontent.com/26138653/59626250-135a4f00-9144-11e9-96e1-e29737971a5b.png)
Game works with dlc. CLOSE.
