### ISSUE TITLE
fifa street error rpcs3

### ISSUE THREAD

**Issue by arpioer** [RPCS3/rpcs3#4330]

**Comment by AniLeo** [comment]
Please don't spam our issue tracker

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
