### ISSUE TITLE
SAW [BLES00676] some sound effects are missing

### ISSUE THREAD

**Issue by psennermann** [RPCS3/rpcs3#4332]
The game SAW is almost perfectly emulated, but unfortunately some sound effects are missing, like for example when you use the bat against a wall or a person, you don't hear anything.
Switching SPU decoder from Recompiler (ASMJIT) to Interpreter (fast) makes audio stutter, but slightly improves the issue, since in the same situation a very very distant and muffled fake sound comes out...

Win10
Gtx1060 3gb
i5 7400
MSI b250 integrated Realtek high definition audio

**Comment by psennermann** [comment]
Forgot to mention the build used: 0.0.5-6573

**Comment by dio-gh** [comment]
The sound requires accurate xfloat to work properly it seems. Tested on `RPCS3 v0.0.7-8852-e9ea226e Alpha`. Closeable.

**Comment by psennermann** [comment]
You're right! Closing
