### ISSUE TITLE
[BLUS30285] Fight Night Round 4 regression - not working anymore

### ISSUE THREAD

**Issue by kroaton** [RPCS3/rpcs3#4339]
Hi,

Fight Night Round 4 doesn't seem to work anymore due to "F {PPU[0x1000010] Thread (LoopSimulation) [0x000853e4]} MEM: Access violation reading location 0xa6ab4054" while compiling shaders.

It used to work on 0.0.3-6389 ([video of it working](https://www.youtube.com/watch?v=hMlE6sxNS50)) with Vulkan support, close to full speed and for the most part fully playable (though getting it to boot required a few tries as it'd randomly crash and there were still a few stability problems here and there).

Here is the log (tried both Vulkan and OpenGL, same results) : it hangs on the last error message while "Compiling shaders..." appears at the bottom of the screen.

RPCS3 v0.0.5-6592-a36acf49d Alpha | HEAD
Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz | 8 Threads | 15.95 GiB RAM | AVX+ | TSX
E {PPU[0x1000000] Thread (main_thread) [0x000821d4]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0x40f, alignment=0x10000000, alloc_addr=*0x20106ba4)
E {PPU[0x1000000] Thread (main_thread) [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/fe/main.ast” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/audio/indexedassets.txt” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/audio/aems/indexedassets.txt” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/audio/crowds/indexedassets.txt” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/audio/music/indexedassets.txt” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/loc/indexedassets.txt” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/loc/eng/indexedassets.txt” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/loc/eng/speech/indexedassets.txt” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/loc/fre/indexedassets.txt” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/loc/fre/speech/indexedassets.txt” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/common/config/indexedassets.txt” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/config/indexedassets.txt” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01492000]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/config” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01492000]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/config” [2]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/ps3/gameexplorer/char/indexedassets.txt” [1]
E {PPU[0x1000000] Thread (main_thread) [0x0041ab3c]} 'cellKbSetCodeType' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [1]
E {PPU[0x1000000] Thread (main_thread) [0x0041ab4c]} 'cellKbSetReadMode' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [1]
E {PPU[0x1000000] Thread (main_thread) [0x0041ab5c]} 'cellKbClearBuf' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [1]
E {PPU[0x1000000] Thread (main_thread) [0x0041ab3c]} 'cellKbSetCodeType' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [2]
E {PPU[0x1000000] Thread (main_thread) [0x0041ab4c]} 'cellKbSetReadMode' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [2]
E {PPU[0x1000000] Thread (main_thread) [0x0041ab5c]} 'cellKbClearBuf' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [2]
E {PPU[0x1000000] Thread (main_thread) [0x0041ab3c]} 'cellKbSetCodeType' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [3]
E {PPU[0x1000000] Thread (main_thread) [0x0041ab4c]} 'cellKbSetReadMode' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [3]
E {PPU[0x1000000] Thread (main_thread) [0x0041ab5c]} 'cellKbClearBuf' failed with 0x80121002 : CELL_KB_ERROR_INVALID_PARAMETER [3]
E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed
E {PPU[0x1000000] Thread (main_thread) [0x0146d260]} sys_net: sys_net_bnet_poll(fd=24): events=0xc x2
E {PPU[0x1000010] Thread (LoopSimulation) [0x000842bc]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLUS30285”, errDialog=0x1, funcStat=*0x114d158, container=0)
E {PPU[0x1000010] Thread (LoopSimulation) [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30285/USRDIR/ICON0.PNG” [1]
E {PPU[0x1000010] Thread (LoopSimulation) [0x01491f44]} 'sys_fs_unlink' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30285/USRDIR/ICON0.PNG” [1]
E {PPU[0x1000010] Thread (LoopSimulation) [0x009210c4]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLUS30285”, errDialog=0x0, funcStat=*0x114d070, container=0)
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/databigs/ps3/fe_big.ast” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/databigs/ps3/boot_other.ast” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/databigs/ps3/be_gp.ast” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/databigs/ps3/shaders_big.ast” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/databigs/ps3/venue_big.ast” [1]
E {PPU[0x1000010] Thread (LoopSimulation) [0x0027a760]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x112e9d8, arg=*0x0, options=0x0)
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/audio/aems/sound_sfx2_big.ast” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/audio/aems/sound_loadloops_big.ast” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/audio/crowds/sound_crowds_big.ast” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/audio/aems/sound_fesfx_big.ast” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/audio/aems/sound_sfx2_big.ast” [2]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/audio/aems/sound_fesfx_big.ast” [2]
E {PPU[0x1000010] Thread (LoopSimulation) [0x0146d260]} sys_net: sys_net_bnet_poll(fd=24): events=0xc x10
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/audio/aems/sound_loadloops_big.ast” [2]
E {PPU[0x1000010] Thread (LoopSimulation) [0x0146d260]} sys_net: sys_net_bnet_poll(fd=24): events=0xc x118
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/common/fmv/boot_movie_eng.vp6” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30285/USRDIR/data/common/fmv/boot_movie_eng.vp6” [1]
E {PPU[0x1000010] Thread (LoopSimulation) [0x0146d260]} sys_net: sys_net_bnet_poll(fd=24): events=0xc x1242
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/common/fmv/fn4_custom.vp6” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30285/USRDIR/data/common/fmv/fn4_custom.vp6” [1]
E {PPU[0x1000010] Thread (LoopSimulation) [0x0146d260]} sys_net: sys_net_bnet_poll(fd=24): events=0xc x2572
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/common/fmv/attract_movie_eng.vp6” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30285/USRDIR/data/common/fmv/attract_movie_eng.vp6” [1]
E {PPU[0x1000010] Thread (LoopSimulation) [0x0146d260]} sys_net: sys_net_bnet_poll(fd=24): events=0xc x2438
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/audio/aems/fe_sfx_stream.aems” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30285/USRDIR/data/ps3/audio/aems/fe_sfx_stream.aems” [1]
E {PPU[0x1000010] Thread (LoopSimulation) [0x0146d260]} sys_net: sys_net_bnet_poll(fd=24): events=0xc x316
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/saveload/000/icon0.png” [1]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30285/USRDIR/data/ps3/saveload/000/icon0.png” [1]
E {PPU[0x1000018] Thread (check_space_thread) [0x0098a384]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLUS3028500”, errDialog=0x0, funcStat=*0x114e7f8, container=1)
E {PPU[0x1000010] Thread (LoopSimulation) [0x0146d260]} sys_net: sys_net_bnet_poll(fd=24): events=0xc x560
E {PPU[0x1000010] Thread (LoopSimulation) [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30285/USRDIR/version.txt” [1]
E {PPU[0x1000010] Thread (LoopSimulation) [0x0146d260]} sys_net: sys_net_bnet_poll(fd=24): events=0xc x55
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/audio/aems/sound_fesfx_big.ast” [3]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/audio/crowds/sound_crowds_big.ast” [2]
E {PPU[0x1000003] Thread () [0x01492090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30285/data/ps3/gameexplorer/char/ge_char_big.ast” [1]
F {PPU[0x1000010] Thread (LoopSimulation) [0x000853e4]} MEM: Access violation reading location 0xa6ab4054

**Comment by AniLeo** [comment]
Closing until issue is fixed. If reporting a regression, needs to contain in which build the regression happened

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by kroaton** [comment]
Sorry, it totally slipped my mind: rpcs3-v0.0.5-6592-a36acf49

**Comment by AniLeo** [comment]
Read the guidelines to fix the issue. You're missing a proper log. Copy paste from emulator log output is not a valid log file.

Did you test other builds? It seems very unlikely the regression happened on that PR by kd-11. Remember, you must state the build on which it regressed, not any random build where it doesn't work.

**Comment by Kravickas** [comment]
#4247
