### ISSUE TITLE
OpenGL+Intel: Failure on saturate compilation [BLUS31604]

### ISSUE THREAD

**Issue by EnvyKiwi** [RPCS3/rpcs3#4342]
Not very tech-savvy nor do I have the brightest common sense out there, forgive me if this doesn't follow guidelines or has been brought up before.
RPCS3 Version: 0.0.5-6592 a36acf49d Alpha

I am using an i7 4790 4th gen CPU with an integrated HD 4600 GPU and OpenGL 4.3 on a DELL Windows 7. When trying to run BLUS31604 - (installed through the proper steps, as far as I know) for Persona 5, the game will run at ~30 fps until after the opening sequence. Once the opening is either skipped or ends naturally, the game will freeze at a blackscreen while trying to compile shaders. The logs show OpenGL failing to initialize. Every issue of this kind I've been able to read about has claimed that this is due to Intel not being able to run OpenGL 4.3, yet mine can. I have to assume this means the emulator went wrong somewhere. Attempts with different settings show the same thing. Drivers are, as far as I can tell, up to date, as is the emulator. 

[TTY.zip](https://github.com/RPCS3/rpcs3/files/1846252/TTY.zip)
[RPCS3.log.gz.7z.zip](https://github.com/RPCS3/rpcs3/files/1846267/RPCS3.log.gz.7z.zip)

**Comment by kd-11** [comment]
Intel drivers are trash. In this case (this issue is a duplicate as I have seen this before), a saturate fails to compile. The driver cannot compile the line `h0.w = clamp((tc2 * fc48), 0., 1.).w;` and complains. Intel does not work with rpcs3 on windows due to bugs like these. There are many other bugs, including refusing to register some variables for no reason, lack of indexed component access for vectors, etc.

**Comment by EnvyKiwi** [comment]
So the only solution is to get a new (non-intel) GPU?

**Comment by 13xforever** [comment]
Yes

**Comment by hcorion** [comment]
You could try mesa on windows, it might be your best bet.

**Comment by AniLeo** [comment]
Closing as superseded by the Intel GPU Megathread #6199

**Comment by d-apps** [comment]
@EnvyKiwi Read my comment on [Megathread](https://github.com/RPCS3/rpcs3/issues/6199)
