### ISSUE TITLE
Regression: Conan [BLUS30069] Slower performance + lighting issue

### ISSUE THREAD

**Issue by IbanPetrov** [RPCS3/rpcs3#4346]
Conan 2007 yr Is too slow now
![c61](https://user-images.githubusercontent.com/37421626/37924215-d65f6880-3139-11e8-9ef7-6c1c20beb95d.jpg)
![c31](https://user-images.githubusercontent.com/37421626/37924547-db0a0682-313a-11e8-896e-9a7b2ec9c938.jpg)
Wrong character rendered. Reason is lighting issue
![c41](https://user-images.githubusercontent.com/37421626/37924350-49ff5b6a-313a-11e8-8341-64101d51194c.jpg)

Sstrict mode (another render problem - save stone is wrong rendered)
![c61strct](https://user-images.githubusercontent.com/37421626/37924231-e508d07e-3139-11e8-8f9c-5e52beb2d365.jpg)
Non strict mode
![c51](https://user-images.githubusercontent.com/37421626/37924338-40974420-313a-11e8-94dd-3ae202f3cf31.jpg)
and Rpcs3 bug - after prisoner is free and cage empty, this empty cage(no prisoner) crys and shakes after loading(old issue - january-february)

**Comment by AniLeo** [comment]
Since you're reporting a regression, you need to state in which build it regressed.

**Comment by IbanPetrov** [comment]
build 6592 
![yourcap](https://user-images.githubusercontent.com/37421626/37925050-5497bef8-313c-11e8-8d9e-bc38eb1ea376.jpg)
 log http://www.mediafire.com/file/6m01b3tchbges0z/ConanRPCS3.log.gz

**Comment by Parthorisian** [comment]
This game was'nt playable since kd11 released build 6541
because
![conan_prev31](https://user-images.githubusercontent.com/35437970/37930186-b49626ba-314a-11e8-8fb9-087e66c1198b.jpg)
Regression it seems was caused 6551 because
![conan_prev11](https://user-images.githubusercontent.com/35437970/37930202-c4989d2c-314a-11e8-994f-c652d869b4db.jpg)
![conan_prev21](https://user-images.githubusercontent.com/35437970/37930211-ce9a23fe-314a-11e8-9745-c0cc7eea63f9.jpg)

**Comment by AniLeo** [comment]
I don't understand, what build exactly regressed the game and how did it regress? Speed and performance at the same time, or speed and graphics regressed in separate builds?

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/4354

**Comment by Parthorisian** [comment]
Even much lesser fps https://imgur.com/Gg7VJwr master [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1917818/RPCS3.log.gz)

**Comment by ruthan** [comment]
This bug is not still fixed..

**Comment by legend800** [comment]
The game is fine performance wise now, just broken lighting/textures. Can you please log a new bug for that and close this issue (mostly pertains to perf regression).

**Comment by IbanPetrov** [comment]
#5554 replase , performance still very bad ~15fps
