### ISSUE TITLE
[BLUS30478] R.U.S.E. fails to install

### ISSUE THREAD

**Issue by XXLuigiMario** [RPCS3/rpcs3#4352]
# General Information

* **RPCS3 version**: RPCS3 v0.0.5-6595-05fc49506 Alpha
* **Game version**: BLUS30478 01.00

# System specs

* **OS**: Windows 10 Home (64-bit)
* **CPU**: Intel Core i7-4720HQ @ 2.60GHz
* **RAM**: 8GB DDR3
* **GPU**: GeForce GTX 860M

# Issue description

After the intro, R.U.S.E. tries to install data to the HDD, however it appears to fail to save anything and crashes right before the progress bar reaches the end with the message:
"MEM: Access violation reading location 0x8".

# Screenshots

![ruse](https://user-images.githubusercontent.com/7153662/37995911-423c4d52-3216-11e8-8cec-ac37fd1c9416.png)

# Log

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1853844/RPCS3.log.gz)

**Comment by magiruuvelvet** [comment]
The same happens on Tales of Graces f (BLUS30903) too. Seems like some kind of regression. The database says Ingame with a last year date. If "crashes" after the install is "complete" and than freezes. There are files in hdd1/game. They are removed once the emulator is stopped.

**Comment by XXLuigiMario** [comment]
The game now seems to install fine in the latest builds. Though it doesn't reach ingame because of a different issue.
