### ISSUE TITLE
Silent Hill: Downpour [BLUS30565] - disappearing surface textures.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4358]
~~Appearing in last builds. Looks like it may be a regression after Unreal Engine fixez commit.~~
Description: textures of... thrash on surface now can disappear on camera move.
![489](https://user-images.githubusercontent.com/6324523/38087884-ece2b8ea-336a-11e8-8080-30ae0958bdbd.png)
![490](https://user-images.githubusercontent.com/6324523/38087889-f1c522e4-336a-11e8-8acd-aa2b60d3095d.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1859980/RPCS3.log.gz)
Happens also with normal, non-adjusted settings
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1859988/RPCS3.log.gz)

**Comment by Asinin3** [comment]
Need to try and figure out what build exactly may have caused the issue. Maybe provide a renderdoc with a build before and after (make sure to put these in separate 7zip files and use Ultra LZMA2 for compression as kd hasn't got the best internet/datacaps.

**Comment by isshininu** [comment]
well, just give me some time...

**Comment by Psycho-A** [comment]
This solves with Strict Rendering mode enabled (you won't able to play in HD though).

Also, internal antialiasing and resolution downscaling in this game looks terrible even with HD. Use my patch for coalesced.int file that disables all this crap :)

[Coalesced_Int.zip](https://github.com/RPCS3/rpcs3/files/1866085/Coalesced_Int.zip)

**Comment by isshininu** [comment]
This is probably a patch with keyboard symbols, not gamepad icons.

**Comment by kd-11** [comment]
Closing since its not an issue with accurate rendering. Maybe try adjusting res threshold and hope you get lucky or use psycho-A's patch for the game.
Also, why open an issue about graphics bugs without first trying strict rendering mode? Maybe it should be renamed to "accurate emulation mode" to avoid confusion since some people think its a problem if a game breaks because its disabled.

**Comment by isshininu** [comment]
Strict Rendering mode is broken in this game when using only GUI settings (I heard it works with disabled GPU Blit)

**Comment by isshininu** [comment]
Disable Vertex Cache to resolve issue.
No Strict Rendering Mode required.

**Comment by Psycho-A** [comment]
@isshininu You mean resolving flickering textures, or your crashes in Strict mode?

**Comment by isshininu** [comment]
Only resolving of flickering ground textures.

**Comment by Psycho-A** [comment]
Strange, because nothing happens to me... I even checked the same place you showed on screenshots.
