### ISSUE TITLE
[BLES02143] [OpenGL] Rendering issues at a lot of places

### ISSUE THREAD

**Issue by magiruuvelvet** [RPCS3/rpcs3#4359]
**RPCS3 Version:** v0.0.5-6601-ee0fe28dd
**Game:** Atelier Shallie \~Alchemists of the Dusk Sea\~
**Title ID:** BLES02143

**OS:** Linux
**Renderer:** OpenGL
**GPU:** NVIDIA GeForce GTX 980m
*default settings*

---

Rendering artefacts like this at a lot of places around the game. I tried out #4356 but that didn't fixed it. The problem seems to be somewhere else.

![before](https://user-images.githubusercontent.com/13280758/38107271-b91a3a7a-3391-11e8-8df2-888d422b0308.png)

---

EDIT: What files do I need to provide to help finding the source of the problem? Also I can't use Vulkan because of optimus laptop.

**Comment by miguel-nunes** [comment]
This one particular artifact in Atelier games. This can be seen in Escha & Logy too

![aeel](https://user-images.githubusercontent.com/21225981/38178410-d8f96330-35e8-11e8-91b2-25d8bf2f52f0.png)

I didn't notice on Meruru nowadays. In some moment, such artifacts exists on Meruru, but some PR fixed.

If somenoe need logs, let me know

Cheers!

**Comment by kd-11** [comment]
This was fixed some time ago.
