### ISSUE TITLE
(BLES00668) Top Spin 4 loading bug

### ISSUE THREAD

**Issue by pcmaniaco** [RPCS3/rpcs3#4362]
When press start and start loading then freeze and show the error "F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsx_cache.h:88)"

my specs are:
I7 6700K
32gb DDR4
GTX1080
Windows 10
last nvidia driver
![topspin error](https://user-images.githubusercontent.com/37944886/38157979-f42afbfa-3462-11e8-82e1-79bcbd371b23.jpg)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1865055/RPCS3.log.gz)

sorry my bad english! thx!

**Comment by Zangetsu38** [comment]
not sur if real bug,i have already signaled this error to KD, for other game, same issue, need enable CPU blit and works
![image](https://user-images.githubusercontent.com/5261759/38158077-1017b65c-348e-11e8-9bac-e78bacf9e0be.png)

**Comment by Asinin3** [comment]
This game doesn't need CPU Blit, but i did read that GPU Texture scaling must be off. Anyway, just re-tested and still works fine here. Trey with GPU Texture Scaling disabled

**Comment by Zangetsu38** [comment]
yes i kinow, and yes, you havez right, for him just disable gpu scal and works

**Comment by pcmaniaco** [comment]
same problem, enable the cpu blit in config file (doesnt appear in config menu), disable the gpu texture scaling, but doesnt resolve :(
![config](https://user-images.githubusercontent.com/37944886/38158313-479369a8-3468-11e8-86c5-a045595c171b.jpg)
![config2](https://user-images.githubusercontent.com/37944886/38158314-47b471de-3468-11e8-8859-54bc801a361f.jpg)
![config3](https://user-images.githubusercontent.com/37944886/38158315-47d29d26-3468-11e8-9d79-a9d8d1541cfc.jpg)

**Comment by Asinin3** [comment]
Your changing main settings when you have a custom configuration for the game. you need to right-click configure the game.

**Comment by Zangetsu38** [comment]
juste disable GPU scal on config game and works

**Comment by Asinin3** [comment]
Please close the issue, (click the big red button) and try to check forum threads for issues on games before posting an issue. There is information in the threads for this game that it does not work with GPU Texture Scaling already.
