### ISSUE TITLE
[BLUS31937] tales of xillia 2 freezes

### ISSUE THREAD

**Issue by bk2710** [RPCS3/rpcs3#4363]
When progressing the main story (talking to leia, chapter 4 start iirc) the game freezes before the cutscene plays.

F {PPU[0x1000000] Thread (main_thread) [0x007e33dc]} MEM: Access violation reading location 0x207e00ec
E {PPU[0x1000000] Thread (main_thread) [0x007e33dc]} Stat: 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [x4]
E {PPU[0x1000000] Thread (main_thread) [0x007e33dc]} Stat: 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [x6]
E {PPU[0x1000000] Thread (main_thread) [0x007e33dc]} Stat: 'sys_ppu_thread_set_priority' failed with 0x80010005 : CELL_ESRCH [x5] 

happens no matter which options you choose, apparently this does not happen in the EU version of the game.
The game also has random freezes likely connected to this.

**Comment by AniLeo** [comment]
It's dead with access violation. That doesn't mean anything by itself without further debugging though.

**Comment by bk2710** [comment]
I know little of these things simply posting the logs I got so people who actually have a clue can work with it :^(

**Comment by AniLeo** [comment]
The log doesn't hint to anything and rarely helps on access violations, it needs to be ran and debugged properly. These issues are usually closed. 

Plus, you just pasted a few lines from console output, not the log.

**Comment by AniLeo** [comment]
Closing as invalid
