### ISSUE TITLE
[NPEA00279] ICO (possibly other games) random freezes on OGL with SRM

### ISSUE THREAD

**Issue by fifazalata** [RPCS3/rpcs3#4366]
So recently I've been trying ICO & I was trying it with VK but it's too unstable with that vertex cache crash
so I went with OGL with SRM enabled otherwise the game won't properly scale to fullscreen & would went to black screen if not using SRM
The problem is that I encountered random freezes with a new error I've never seen before when using rpcs3:

> ·F 0:56:39.279429 {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
0(225) : error C0000: syntax error, unexpected '.', expecting "::" at token "."
(0) : error C2003: incompatible options for link

I'm afraid it might be a common problem that appeared recently since someone else faced the same problem when using OGL with GOW & GOW was very stable before with it:

[https://forums.rpcs3.net/thread-190188-post-296607.html#pid296607](url)

Tested on: rpcs3-v0.0.5-6605 (2c16ddd) Alpha [2018-03-30]
& with some builds from a week back & also got the same result

My Rig:
Intel Core i7 2600k @ 3.4
GTX 1070
8GB DDR3

Also here is the log:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1865793/RPCS3.log.gz)

**Comment by kd-11** [comment]
This must have been fixed long ago. Request to reopen if not.
