### ISSUE TITLE
[NPUB31251] Drakengard 3 Green and red outlines/dots when Strict Rendering Mode is disabled.

### ISSUE THREAD

**Issue by Omusoru** [RPCS3/rpcs3#4367]
Rpcs3 version used: v0.0.5-6607-7359774c
OS: Windows 10 64 Version 1709 (OS Build 16299.309)
CPU: i7-6700k 4.4Ghz
GPU: GTX1070(Driver version 391.01)
RAM: 16gb

Screenshot with Strict mode enabled Vulkan renderer:
https://i.imgur.com/MfQEzpv.png

Screenshot with Strict mode disabled Vulkan renderer:
https://i.imgur.com/pZPflb1.png

Write Color Buffers and Disable Vertex Cache seem to make no difference bee them on or off.

The lower the Resolution Scale the more accentuated the problem becomes since the dots seem to be only one pixel wide.

**Comment by AniLeo** [comment]
Do you have Anisotropic Filtering on anything that's not the default setting?

**Comment by Zangetsu38** [comment]
it is normal, set aniso to 2x, scaling to 300 % and 32x32 and good

**Comment by Omusoru** [comment]
Setting Anisotropic Filter to 2x Fixed the Issue:
Screenshot of menu :
https://i.imgur.com/R4563UU.png

**Comment by AniLeo** [comment]
Anisotropic Filter on automatic also works?

**Comment by Zangetsu38** [comment]
@AniLeo yes

**Comment by AniLeo** [comment]
Then not an issue, closing

**Comment by Omusoru** [comment]
Can confirm it works on
