### ISSUE TITLE
Guilty Gear XRD rev 2 - Overall slowdown after PR #4335 (Get rid of MFC Thread)

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#4369]
Guilty Gear XRD rev 2 - Slowdown after PR #4335  (7-10 FPS difference in most cases)

After: From 20 to 23-24 FPS.

Before: From 25 to 30 FPS.

**My specs:**

Windows 10 x64
GTX 970 4GB GDDR5
i7 4790k 4.4 Ghz.
16 GB DDR3

Note: Tested with Vulkan backend.

**Comment by AniLeo** [comment]
I think this is normal, the MFC thread was removed after all

**Comment by LuismaSP89** [comment]
@AniLeo  I suppose there´s a reason to remove it, but... there will be a method in the future to improve this, or replace the MFC thread? (Sorry, I don´t know much about programming and I created this issue to let know the Rpcs3 team that removing this MFC, some games like GG XRD rev 2 has a big slowdown)

**Comment by AniLeo** [comment]
MFC was removed because it had several issues on its implementation, was causing synchronisation problems and whatnot.

The improvements that can be done now are enhancing the SPU emulation mainly in this scenario.

**Comment by scribam** [comment]
@LuismaSP89 Can you try again your game and see if the changes made by Nekotekina in PR #4422 help?

**Comment by LuismaSP89** [comment]
@scribam Yes, indeed it has a better performance. Thanks a lot. Clossing the issue.
