### ISSUE TITLE
Marvel: Ultimate Alliance [BLUS30010] all characters in T-pose

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#4371]
all characters in game is the cross

![1](https://user-images.githubusercontent.com/25039098/38169302-c6f266ea-357b-11e8-8d13-477a72ddc767.jpg)
![2](https://user-images.githubusercontent.com/25039098/38169304-ca27dc6e-357b-11e8-8ceb-bc16f2f295b8.jpg)
![3](https://user-images.githubusercontent.com/25039098/38169308-cced965a-357b-11e8-9f96-5eb0a4192cd9.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1866071/RPCS3.log.gz)

**Comment by GeniusMage** [comment]
The correct expression is "T-posing", I think.

**Comment by AniLeo** [comment]
Needs retesting

**Comment by kd-11** [comment]
Retest with current master.

**Comment by aakh1361** [comment]
test whit master and fix
![image](https://user-images.githubusercontent.com/25039098/46565991-113cc100-c924-11e8-9ed0-592a015c6e1a.png)
![image](https://user-images.githubusercontent.com/25039098/46566011-30d3e980-c924-11e8-8461-485140889488.png)
![image](https://user-images.githubusercontent.com/25039098/46566020-5103a880-c924-11e8-8bfc-bb24e060d4a6.png)
