### ISSUE TITLE
Regression: NFL Blitz [NPUB30665] Black screeen on load 

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#4375]
This game use to launch and reach in-game (albeit with gfx issues) prior to this build:
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7109/artifacts

Works fine on the build from the previous day:
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7092/artifacts

Suspect commit:
https://github.com/RPCS3/rpcs3/commit/d17093e65bdf6fa558e3f2b1146ce297cebc06d8

Spams this at startup (black screen only now):
E {SPU[0x2000005] Thread (SPU Sound 1/1)} SPU: [0x3f0a8] Function call without $LR
E {SPU[0x2000005] Thread (SPU Sound 1/1)} SPU: [0x3f0ac] Function call without $LR
E {SPU[0x2000005] Thread (SPU Sound 1/1)} SPU: [0x3f104] Function call without $LR
E {SPU[0x2000005] Thread (SPU Sound 1/1)} SPU: [0x3f110] Function call without $LR

Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1866762/RPCS3.log.gz)

**Comment by kroaton** [comment]
Maybe it has something to do with this https://github.com/RPCS3/rpcs3/issues/4247 ?

**Comment by legend800** [comment]
Unlikely I think. NFL Blitz was broken over 4 months ago and the issue referenced above was from about 2 months ago.

**Comment by legend800** [comment]
Fixed a few months ago.
