### ISSUE TITLE
Please delete X50 "compiling ppu module" windows

### ISSUE THREAD

**Issue by twistedmetalps3** [RPCS3/rpcs3#4379]
This is so annoying, please delete this at all or make it in one big "Now installing" 1/50 loading line, i swear i will never use your emulator because these windows is most annoying thing i've seen, and i will get epilepsy watching 50 windows every game i load. jesus please DELETE THESE STUPID WINDOWS

**Comment by AniLeo** [comment]
Well written issue, 10/10 would read again

Tip: When you want to suggest something to a FOSS project, do it properly.
