### ISSUE TITLE
Ni no kuni EUR [BLUS30947] black screen when feeding a familiar

### ISSUE THREAD

**Issue by edu8000** [RPCS3/rpcs3#4386]
Im using rpcs3-v0.0.5-6630-0e74f2e34 alpha, all settings on default except for the resolution scale, its set to 4k
pc specs:
CPU: intel corei5-4670(3.4 GHz)
GPU: ASUS Radeon HD 7870 DirectCU II
OS: windows 10 64 bit

When i give a treat to a familiar the screen goes black while the treat is falling to the ground and then it goes back to normal like in the gif below:
![prueba](https://user-images.githubusercontent.com/28019000/38280411-6cf1185e-37a5-11e8-80cb-154c1ca88cc4.gif)

**Comment by 13xforever** [comment]
This has never happened to me since at least 0.0.5-6646-8a51af0b, I'm not sure when I first started to play this game in earnest, but it was a bit earlier than pr #4401

**Comment by Metasynic** [comment]
I also haven't had this issue since I started playing, which was somewhere in the early 7000's. I have Ryzen 5 1500X and GTX 970.

**Comment by Metasynic** [comment]
Just finished a complete 45 hour playthrough of the game on latest versions of RPCS3, using both renderers intermittently, and this issue is gone.

This can be closed now.
