### ISSUE TITLE
WWE Smackdown vs RAW 2010 [BLES00651] Game no longer starts

### ISSUE THREAD

**Issue by BlackShadow** [RPCS3/rpcs3#4387]
After booting game for the first time, i was able to reach main menu. But then after re-starting the game all i got was black screen and nothing more.

End of console output:
```
E {PPU[0x100001c] Thread (CTrophyUtilPS3) [0x0177e310]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x1375df0, arg=*0xd015fd40, options=0x1)
E {PPU[0x100001c] Thread (CTrophyUtilPS3) [0x0177e310]} 'sceNpTrophyRegisterContext' failed with 0x8002290f : SCE_NP_TROPHY_ERROR_PROCESSING_ABORTED [1]`
```

RPCS3 Ver: 0.0.5-6595-05fc49506
Renderer: Vulkan

Specs:

i5-7400
GTX 1060
8GB DDR4 2400MHz
Win10 Pro 64-Bit

**Comment by Kravickas** [comment]
Post log not wall of text...

**Comment by AniLeo** [comment]
This is missing an actual log - I'll redact the console output flood above.
It also requires retesting with latest build.

**Comment by BlackShadow306** [comment]
Ah, sorry for that. Uploaded log!
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2127814/RPCS3.log)

**Comment by AniLeo** [comment]
Needs retesting, several updates to sceNpTrophy were already made

**Comment by BlackShadow** [comment]
This issue is fixed. Game boots properly after restart. However there's still issues with the game. I will post another issue for that. Closing this as fixed.
