### ISSUE TITLE
RSX: Format incompatibility VK_FORMAT=0x81, GCM_FORMAT=0x95

### ISSUE THREAD

**Issue by kamer1337** [RPCS3/rpcs3#4392]
games works fine, but im reporting this in case it may affect performance

games:
Tony Hawk's Project 8
Tony Hawk's Proving Ground

RSX: Format incompatibility detected, reporting failure to force data copy (VK_FORMAT=0x81, GCM_FORMAT=0x95)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1879817/RPCS3.log.gz)

**Comment by kd-11** [comment]
There's no way around that, its not a real error. I might lower it to maybe warning or something but its also an err_once message - its there to hint to devs if there are serious graphical glitches in a game, that format cast may have been attempted by a naughty ps3 developer.
