### ISSUE TITLE
RSX: Depth texture bound to pipeline with unexpected format 0x94

### ISSUE THREAD

**Issue by stride21** [RPCS3/rpcs3#4398]
The message RSX: Depth texture bound to pipeline with unexpected format 0x94 is spammed thousands of times during gameplay with both OpenGL and Vulkan in Battlefield: Bad Company.

![battlefield](https://user-images.githubusercontent.com/37915864/38422403-3a6fddf8-3970-11e8-92f3-5279375a2153.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1884032/RPCS3.log.gz)

**Comment by stride21** [comment]
Killzone 3 also has this issue, I will add a picture and log once Neko merges #4504 .

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/4844

**Comment by Shadow221332** [comment]
Fied by #9150

**Comment by Shadow221332** [comment]
Fixed by #4398
