### ISSUE TITLE
Race Condition(?) on _cellsurMixerMain/sys_mutex_unlock killing audio and game (Catherine)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#4408]
Audio on Catherine will die as soon as a sys_mutex_unlock on _cellsurMixerMain fails with CELL_EPERM. This causes the game to eventually die anytime. This happens randomly and looks like a Race Condition, though I'm not completely sure.

`E {PPU[0x1000011] Thread (_cellsurMixerMain) [0x00ae477c]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]`

I'm also pretty sure this isn't a recent issue. Don't have any full log of the game with the unlock fail right now, but can get one if needed.

**Comment by miguel-nunes** [comment]
@AniLeo, I think we can include Valkyria Chronicles on the list. I was thinking that was a problem with no memory, but could to that. In Valkyria Chronicles, any video transitions hangs, but the moment is random.

**Comment by AniLeo** [comment]
But does it die with the same error? Otherwise it's can be anything else

**Comment by miguel-nunes** [comment]
The error after the hang is that:

E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x00d3c4ec]} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x237582]
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x00d3c4ec]} Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x28929]
E {PPU[0x1000006] Thread (_sys_MixerChStripMain) [0x0071f2e8]} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x233184]

Maybe this is a different unexpected behavior, but I was thinking it was related. If it's not, you can desconsider and delete from the thread.

**Comment by elad335** [comment]
Still an issue?

**Comment by AniLeo** [comment]
Need someone to play this for a while and see if it still happens, I haven't replayed this in RPCS3 yet

**Comment by phantasia15** [comment]
Hi, Utawarerumono Itsuwari no Kamen had the same (?) problem and it freezed at the opening movie with the similar error log. The latest build (v0.0.6-7972 df3b46a6) has fixed the problem for me.

**Comment by RainbowCookie32** [comment]
I was just playing Catherine and I didn't get the issue. If phantasia's comment is correct, I think it's fixed?

**Comment by AniLeo** [comment]
Closing, if I'm able to reproduce this again I'll reopen
