### ISSUE TITLE
[BLUS31476] Tears to Tiara 2 keep crashing

### ISSUE THREAD

**Issue by RedMagus** [RPCS3/rpcs3#4409]
`F {PPU[0x1000005] Thread (Thread Change Thread) [0x001c80e0]} MEM: Access violation writing location 0xd001bfa0`

or 

```
F {PPU[0x100000d] Thread (Sound Play Thread) [0x001835b0]} class std::runtime_error thrown: Locking failed (lwmutex=*0x202b8278, owner=0x1000005)
(in file Emu\Cell\Modules\sys_lwmutex_.cpp:181)
```

RPCS3 ver: rpcs3-v0.0.5-6645-c77b3104_win64
CPU: i7 4790k 
GPU: GTX 1080
RAM: 16GB

I've been trying using all the builds but it keeps crashing randomly at main scenario where Hamil is awoken (after the prologue):
v0.0.4-2018-01-16-d6c4d8ee 
v0.0.4-2018-01-17-71f69d1d
v0.0.5-6461-d78b0467
v0.0.5-6645-c77b3104 (gives me access violation writing)

The setting I used:
CPU:
- PPU Decoder: LLVM Recompiler
- SPU Decoder: ASMJIT

GPU:
- Renderer: Vulkan
- Use GPU Texture Scaling
- Res scale: 300%
- Res scale threshold: 16x16

I am not sure which file log do you need. I assume the log is in main folder so I attached the file here. It's too big for github so I uploaded it to google drive instead
https://drive.google.com/open?id=1GxNoQjM5Epj_PNUKh4hLRYy2KwtrGaQ1

**Comment by digitaldude555** [comment]
https://forums.rpcs3.net/thread-180082-page-2.html

Update from December says it doesn't crash anymore, playable. Can close the issue.

**Comment by AniLeo** [comment]
Closing as solved then, if you can somehow still reproduce this on the latest builds ping for reopening
