### ISSUE TITLE
Peggle [NPUA30005] Trial version is perfect | Full game crashes at startup

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#4411]
The trial version of game works perfectly but the game crashes with the license EDAT (placed in \dev_hdd0\home\00000001\exdata and changed to .rap - this is what you have to do with C00 games).

This has been the case going back to builds from 2017.

PPU error thrown at startup:
F {PPU[0x1000000] Thread (main_thread) [0x00446484]} MEM: Access violation reading location 0x4e9

Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

[RPCS3-peggle.log.gz](https://github.com/RPCS3/rpcs3/files/1886821/RPCS3-peggle.log.gz)

**Comment by legend800** [comment]
Apologies, proper log attached. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1949282/RPCS3.log.gz)

**Comment by JonesCroatia** [comment]
Another PopCap game, Plants Vs Zombies, both NPEA00271 and NPUA30059 are playable only as Trial versions. Proper .rap file in exdata folder crashes game with white screen. It must be the same emulator bug that crashes Peggle.

Windows 7 x64 Sp1
Q9550@ 3.6GHz, 8GB RAM
GTX 1060 6GB, 397.94 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2087755/RPCS3.log.gz)

**Comment by legend800** [comment]
Fixed on today's master!!

**Comment by Emulator-Team-2** [comment]
Fixes by #5450

**Comment by pyros777** [comment]
Looks like this is broken again:

> F {PPU[0x1000005] Thread (auto_load_thread) [0x00425ac4]} VM: Access violation writing location 0x4baac9e4 (unmapped memory)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5220898/RPCS3.log.gz)

**Comment by legend800** [comment]
Incorrect, nothing's broken.

![2020-09-14 20_05_07-FPS_ 60 00 _ Vulkan _ 0 0 12-10881 _ Peggle  NPUA30005](https://user-images.githubusercontent.com/20983844/93160682-af676300-f6c5-11ea-9e7f-7c768f531383.png)

**Comment by pyros777** [comment]
Hmm, its difficult to reconcile "nothing's broken" when it doesn't work for me.  I had hoped my log file would provide some insight, but perhaps it is both broken and not broken all at once, depending on the system.

**Comment by pyros777** [comment]
To elaborate, I'm getting the hang-at-white screen with the non-demo version.
