### ISSUE TITLE
Regression: Rayman Legends [NPEB01356] Flickering GFX 

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#4412]
Massive flickering GFX now occurs on the game.

Worked fine on this build:
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7109/artifacts

Broken by the the next (available) build:
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7112/artifacts

Looks like it was this commit:
https://github.com/RPCS3/rpcs3/pull/3772 by kd-11

Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

[RPCS3-rayman.log.gz](https://github.com/RPCS3/rpcs3/files/1886818/RPCS3-rayman.log.gz)

**Comment by toccata10** [comment]
On rpcs3-v0.0.5-7104-a1911302_linux64.AppImage, this is the rsx capture:
[capture-RaymanLegends-01.rrc.zip](https://github.com/RPCS3/rpcs3/files/2196894/capture-RaymanLegends-01.rrc.zip)
Background is massively flickering

**Comment by AniLeo** [comment]
Needs retesting on master

**Comment by legend800** [comment]
Thanks for checking. Still flickers on OpenGL/Vulkan and with/without Strict Rendering.

**Comment by legend800** [comment]
@kd-11 Just FYI, this is still an issue on today's mainline (9/4). Let me know if there's anything else I can provide.

**Comment by legend800** [comment]
@kd-11 
Game has regressed further by the rsx changes merged in the past couple days. From another user in the official game thread:

Starting with "rpcs3-v0.0.5-7387-a3d44b5e_win64", the intro animation with developer logos and such, the one preceding the main menu, is no longer displayed (on both OpenGL and Vulkan).

The errors in the console are as follows:
U {rsx::thread} RSX TODO: Flushable section 0xc1750000 data may have been lost (lock_memory_region)
U {rsx::thread} RSX TODO: Valid region data may have been incorrectly unprotected (0xc1750000-0xc1830fff)
U {rsx::thread} RSX TODO: Flushable section 0xc1660000 data may have been lost (lock_memory_region)
U {rsx::thread} RSX TODO: Valid region data may have been incorrectly unprotected (0xc1660000-0xc1740fff)

The entire sequence is just pitch black. The menu itself works (if you wait though the pitch black intro), but flickers just the same way it did after previous regression. All the previous errors such as Blit request denied are still there.

The "strict rendering mode" and all the other options, including "hidden in the config file" ones such as "force CPU blit", as I mentioned earlier. None of them influence the issue in any significant way.

I tried looking at the code, and it seems that the blit surface is not being initialized in that game using the usual methods. Apparently, it sends a certain additional data structure to cellVideoOut method though the last parameter, the reading of which is not currently implemented. It is apparent, that either the code related to the init of the blit surface has been modified to strengthen the checks and not assume any default dimensions (the checks are there, I don't know if they always were), or some other modification to the RSX caused the discarded blit requests to result in flickering. As to what is currently happening to the intro sequence I have no idea, it started happening just yesterday after certain changes made by kd-11.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2415908/RPCS3.log.gz)

**Comment by Emulator-Team-2** [comment]
Fixed by #5427

**Comment by legend800** [comment]
Verified fixed.

**Comment by AniLeo** [comment]
PR still not merged
