### ISSUE TITLE
Regression: Uncharted 1

### ISSUE THREAD

**Issue by JohnHolmesII** [RPCS3/rpcs3#4420]
After pr #4377 trying to start a new game causes the following:

F {PPU[0x1000022] Thread (Save/Load Game Thread) [0x00180ee8]} MEM: Access violation reading location 0x0

Loading a save doesn't seem to trigger any problems. It's only new game.

**Comment by JohnHolmesII** [comment]
The error comes from this line in overlays.h (395)
new_stub = std::make_unique<save_dialog_entry>(title, "Select to create a new entry", id, icon);

**Comment by Margen67** [comment]
@JohnHolmesII Did you try disabling the native UI?

**Comment by JohnHolmesII** [comment]
Well of course it works fine, I know what the problem is. I just have no idea how to fix it. I'll come up with something.

**Comment by JohnHolmesII** [comment]
So the problem seems to be this line:
title = picon->title.get_ptr(); (overlays.h, 380)

title was already set to "Create New", but then its gets overwritten here. printing picon->title  shows 0 in the log, though that could be a an endianess bit of joy. Then again, maybe not.

Printing title after that line returns 2^32 exactly.

Any ideas?

**Comment by jjsat** [comment]
If pcon->title is null (could be), then adding a check for just that should do the trick?

```
if (picon->title)
  title = picon->title.get_ptr();
```

**Comment by JohnHolmesII** [comment]
I could. I just don't really understand what the code is doing, i.e. what is title supposed to be? Is icon the actual icon that gets displayed in the save dialog? Is picon->title supposed to be the name of the resource?

@kd-11 can you shed any light on this, since I believe you wrote it?

**Comment by MSuih** [comment]
>what is title supposed to be?
The title for creating a new save. "New saved data" in [this image](https://github.com/RPCS3/rpcs3/pull/4377#issuecomment-377929403)

>Is icon the actual icon that gets displayed in the save dialog? Is picon->title supposed to be the name of the resource?
Yes, variable `icon` is the icon that's actually shown on new save entry. `picon->title` is the title for new save that comes from the game. I guess that some dev's arent interested in providing a custom title so they send a null instead and system is supposed to show locale default in that case.

**Comment by JohnHolmesII** [comment]
Well actually for previously made saves the title shows up in the box as the name of the game. I think it looks good without it. I'll open a pr for more feedback.

**Comment by kd-11** [comment]
Thanks. neko recently updated the code recently to use custom "new save" image and text which is why the regression only appeared recently. Should be fixed now.

**Comment by kodathefox** [comment]
don't mean to bump something so old but I need a way to fix this error F {PPU[0x1000000] Thread (main_thread) [0x007db9ec]} MEM: Access violation reading location 0x0 every time it gets to checking dlc in tales of Xillia 2 on RPCS3 emulator

**Comment by MSuih** [comment]
Do you have all the required licenses? Normally DLC's are encrypted and you need decryption key to be able to read them.

Come to #help on rpcs3 Discord for tech support, github isn't the place for this.
