### ISSUE TITLE
Tekken 6 (BLES00635) Failed save 

### ISSUE THREAD

**Issue by Rpcs3tester** [RPCS3/rpcs3#4426]
![2018-04-10_20-08-57](https://user-images.githubusercontent.com/38118895/38572424-c11ad0a4-3cfb-11e8-9453-43f773fa36bf.jpg)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1895627/RPCS3.log)

i tried to

1- Delete Tekken 6 save folder but it's not exist 

2- Create Tekken 6 empty save folder but it's not fix it

3- using old build (rpcs3-v0.0.4-2017-12-09-eb00bd50_win64) that may fix save but it didn't

4- Downloading save dir from google and put it in save folder fails too .

**Comment by markcagatandavis** [comment]
BUILD: RPCS3 0.0.5-6884-dcd7f442f-Alpha
OS: Windows 10 Build 17134
Mobo: G1.Sniper M5
RAM: 16GB Sniper
GPU: NVidia GeForce GTX 1060 6GB
CPU: i7-4790k @ 4.0GHz

Log attached, confirmed same issue reported above. 

Troubleshooting: 
1. Deleted all saves from \dev_hdd0\home\00000001\savedata
2. Downloaded save and imported too \dev_hdd0\home\00000001\savedata

[Log.txt](https://github.com/RPCS3/rpcs3/files/2064666/Log.txt)

**Comment by Kravickas** [comment]
Saves working.
Tried saving progress, loading, deleting saves and let the game create new one.

**Comment by AniLeo** [comment]
Closing as reported solved
