### ISSUE TITLE
Regression Pure [NPUB30449]

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#4429]
Pure [NPUB30449] graphically regressed after da1e9761 for both VK and OGL
in ingame graphics
master
![1](https://user-images.githubusercontent.com/7060586/38608614-86b4587a-3d84-11e8-96f1-03a44e9f6f58.jpg)
and the way it looked before da1e9761 and after i've readded lines from this commit
![2](https://user-images.githubusercontent.com/7060586/38608778-fd98f982-3d84-11e8-99e9-048d7dfb9aa5.jpg)
kd-11, please take a look

**Comment by kd-11** [comment]
Before & after RDC please. This is one very sensitive piece of code where multiple registers affect the outcome of a contented address

**Comment by Xcedf** [comment]
What is RDC?

**Comment by MarioSonic2987** [comment]
RenderDoc

**Comment by scribam** [comment]
@Xcedf Can you try again with the latest build available (98b715d)? I have no issue with it.

![screenshot from 2018-04-25 20-57-22](https://user-images.githubusercontent.com/25406440/39266868-83986de6-48cb-11e8-84d7-972c5257cdbb.png)

**Comment by TheRibbit** [comment]
@kd-11 I was looking through issues and just decided to make renderdoc report (using nightly build). 
Main menu and at "1" countdown frame captures. New game, shader cache cleared.
"before" - #3820 | 0.0.4-7109 aka rpcs3-v0.0.4-2017-12-01-d17093e6
"after" - #3772 | 0.0.4-7112 aka rpcs3-v0.0.4-2017-12-01-3fbc960c
"current" - master | rpcs3-v0.0.5-6694-25ec899c_win64
Actually, "after" is better than "current" for me fps-&stability-wise.

https://mega.nz/#F!BZ8xQIzA!17N5TiMCJ177w5GFe0xMHg - mega folder

R7 260x 2GB, 18.3.4 drivers, i5-4670K Haswell, Win7SP1 x64, 16GB RAM

**Comment by scribam** [comment]
@Xcedf I tried the first race from the World Tour on master (737db90058beb93d83d12ea94c405476ee594bfc) and I don't have the issue (Linux/OpenGL). Is it related to a specific race?

![screenshot from 2018-05-10 13-19-28](https://user-images.githubusercontent.com/25406440/39867433-2d550918-5455-11e8-891f-093ee5acba01.png)

**Comment by TheRibbit** [comment]
Still the same situation for me. First tutorial race (right after loading with no saves).
![2018-05-10_16-21-53](https://user-images.githubusercontent.com/20685847/39869480-b9da7f1c-546e-11e8-8c84-be4d7b321b01.png)

**Comment by Xcedf** [comment]
Strange, i still have black screen (Ogl/Win10), could it be Linux/Windows difference

**Comment by kd-11** [comment]
Retest and update. May have been fixed with newer drivers.

**Comment by scribam** [comment]
It looks like this game has regressed for me since my last try
![screenshot from 2018-07-07 15-57-12](https://user-images.githubusercontent.com/25406440/42411654-b6688ec8-81ff-11e8-8548-0694cd347cbe.png)

**Comment by Xcedf** [comment]
Unfortunately same picture for me even on newest driver

**Comment by Xcedf** [comment]
Fixed now with https://github.com/RPCS3/rpcs3/pull/5427

**Comment by Xcedf** [comment]
Fixed now with https://github.com/RPCS3/rpcs3/pull/5427
