### ISSUE TITLE
Skate 2: Black boxes around audience

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#4431]
In larger events of Skate 2 the audience is made out of 2D "cardboard cutouts" rather than actual 3D models. For some reason RPCS3 is not cutting out the border for these. Tried stict rendering mode, write color buffers, disabling anisotropic filtering, switching between vulkan & opengl, disabling GPU texture scaling but none of them had any effect on this. Log didn't contain anything unusual even with debug output enabled.
![untitled](https://user-images.githubusercontent.com/19759300/38630235-0a066c7e-3dbf-11e8-926a-85f4df77eb4f.png)
[OpenGL renderdoc](https://drive.google.com/open?id=11wNn99_YOxQXFFb7asWQg7TvuZMZemRv)

**Comment by legend800** [comment]
Same thing occurs in the Backbreaker football games.

**Comment by HHCHunter** [comment]
@MSuih The black around the textures is called alpha.

**Comment by MSuih** [comment]
Fixed on latest version.
