### ISSUE TITLE
Hatsune Miku Project Diva f [BLUS31319] Graphical Issues on newer versions of RPCS3

### ISSUE THREAD

**Issue by Cainan-Corlett** [RPCS3/rpcs3#4439]
RPCS3 0.0.5-65XX-66XX and above cause graphical issues on OpenGL for Hatsune Miku PJ Diva F having inverted colours on models but UI and some of Miku's modules are perfectly fine (Like the Senbonzakura and Hm, Ah Yes? Modules being fine but Miku's Model is inverted.  But 64XX builds are perfectly fine with no issues whatsoever.

https://cdn.discordapp.com/attachments/277227681836302338/434164998370230272/unknown.png
https://cdn.discordapp.com/attachments/277227681836302338/434161513553723402/unknown.png
 
System Specs:
Windows 10 Pro
i3-4310 @ 3.5ghz
8GB Ram
No GPU

Versions Tested
0.0.5-6649, 0.0.5-6648, 0.0.5-6640, 0.0.5-6606, 0.0.5-6595, 0.0.5-6495 and 0.0.5-6464

**Comment by AniLeo** [comment]
Bad Intel drivers.


**Intel**
```
·E 0:00:12.779093 {rsx::thread} RSX: OpenGL: initialization of glDepthBoundsEXT failed.
·E 0:00:12.779120 {rsx::thread} RSX: OpenGL: initialization of glGetTextureImage failed.
·E 0:00:12.779126 {rsx::thread} RSX: OpenGL: initialization of glTextureBufferRange failed.
·E 0:00:12.779132 {rsx::thread} RSX: OpenGL: initialization of glTextureBarrierNV failed.
·! 0:00:12.779137 {rsx::thread} RSX: 4.3.0 - Build 21.20.16.4565
·! 0:00:12.779138 {rsx::thread} RSX: 4.30 - Build 21.20.16.4565
·! 0:00:12.779138 {rsx::thread} RSX: Intel
·! 0:00:12.779201 {rsx::thread} RSX: Supported texel buffer size reported: 134217728 bytes
```
![screenshot_133](https://user-images.githubusercontent.com/10283761/38744708-69dc6e56-3f3a-11e8-85cd-5bc3aa17f041.png)

**NVIDIA**
![screenshot_132](https://user-images.githubusercontent.com/10283761/38744726-7746a822-3f3a-11e8-98cd-eed338c3ab07.png)

**Comment by Cainan-Corlett** [comment]
Bad Drivers? Hmm where can I get better Graphical Drivers then?

**Comment by AniLeo** [comment]
By using [Mesa](https://mesa3d.org/intro.html) or by acquiring an NVIDIA or AMD card.

I'm not sure how's Mesa support on Windows, you may need to use a Linux distro for an optimal experience.

**Comment by kd-11** [comment]
Closing as wont fix.
