### ISSUE TITLE
Level 22 Gary's Misadventures - NPEB02332 black screen

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#4442]
nothing but a black screen
stops at this error
F {PPU[0x100001c] Thread (HLE Video Decoder)} class std::runtime_error thrown: Unsupported time_base.num (180000/1, tpf=2)
(in file Emu\Cell\Modules\cellVdec.cpp:345)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1910107/RPCS3.log.gz)

**Comment by elad335** [comment]
try to LLE cellvdec.

**Comment by AniLeo** [comment]
Closing as there's already an opened issue regarding this situation at #4110 

You can continue discussion and indicate other games that hit the same unimplemented feature there
