### ISSUE TITLE
Nascar The Game - Inside Line [BLUS30932] - Multiple Rendering Issues

### ISSUE THREAD

**Issue by JMC47** [RPCS3/rpcs3#4452]
RPCS3 Version - 0.0.5-6649-7303f04bc Alpha

Game: Nascar The Game - Inside Line [BLUS30932]

Issues:

The game suffers from mild to severe rendering issues when on the racetrack.  The more minor of the issues I noticed is that the car's look appears to be corrupted.

I included both OpenGL and Vulkan Renders due to potential issues with Vulkan renderdocs brought up on Discord.

https://drive.google.com/open?id=1qMSKjb5gE38tsj9P456pE2tPUI6_eDac

Write color buffers partially fixes the issue but there are still a lot of weird lines across the car.

![image](https://user-images.githubusercontent.com/6598209/38806569-ad2b7cf6-4147-11e8-9ab4-219d16a3279b.png)

The other issue is much worse.  Whenever you hit another object or even skid the tires sometimes, the entire screen turns bright white.  Write Color buffers does not affect this one.

https://drive.google.com/open?id=1Hq0K3RZhcgRPfuym32t8yQygfoN91z4y

I currently don't have my PS3 hooked up to a capture card, but, I can do that and get direct console comparisons if need be.  I'll make it a priority to figure out what effect the game is doing when you hit something (maybe a screen dim/shake?)

**Comment by uaqlover** [comment]
same for 

NASCAR '15 [BLUS31560]
NASCAR '14 [BLUS31378]

hope @kd-11 can fix it soon

**Comment by uaqlover** [comment]
@AniLeo it been fixed with https://github.com/RPCS3/rpcs3/pull/5937
