### ISSUE TITLE
No Vulkan Renderer for Intel GPU

### ISSUE THREAD

**Issue by Dudamax** [RPCS3/rpcs3#4454]
I was able to use the vulkan renderer for rpcs3 but now its gone. I have tried to create the DWORD in my registry and give it the name of the file path of the nv-vk64.json, but i cant find the nv-vk64.json! How can i get one? Im using a laptop and my intel iris pro graphics 540 is the graphics card

**Comment by AniLeo** [comment]
Update your drivers and RPCS3. This is not a RPCS3 issue.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
