### ISSUE TITLE
[Feature request] Bind mouse axis to analog sticks

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4455]
Since mouse buttons binding was added recently, will be added ability to map mouse axis to any PS3 control or at least to analog sticks? It would be really great for all who plays on keyboard.

**Comment by tlm-2501** [comment]
I completely agree and I don't entirely understand why this already isn't a thing. Mouse to RS binding seems very intuitive and will actually make the emulator usable for those who play on keyboard, as it stands right now there's too many buttons to handle.

**Comment by Parthorisian** [comment]
better idea(in my opinion) is autohotkey script using mouse moves for emulation ![qw](https://user-images.githubusercontent.com/35437970/38902080-9a45dac6-42a7-11e8-8b51-409bbcca0304.jpg) hits. 
Emulator is able support vJoy only in much weird way and nobody cares. Even <W><A><S><D> default sensitivity(for hits) is horrible comparing to LStick moves (for normal xinput gamepad). And not every game can allow change stick axes sensitivity

**Comment by jobs-git** [comment]
Autohotkey is less effective at this point since keyboard keys lacks analog rotation for >45 degree angle, see the issue I posted.

**Comment by Psycho-A** [comment]
Btw, can some share the ready Autohotkey script for mouse axis? I could use it as temporary solution.

**Comment by Megamouse** [comment]
This has been implemented. But it is very much in a pre-alpha stage.

**Comment by Megamouse** [comment]
Thematically followed up in #5157
