### ISSUE TITLE
Custom UI input broken

### ISSUE THREAD

**Issue by BParks21** [RPCS3/rpcs3#4456]
When using multiple save files in Ni No Kuni I can only select the very top and very bottom save slots using the custom save file UI. The save files in between are always skipped. I can only access create new save and slot 01
![screenshot 22](https://user-images.githubusercontent.com/12180630/38917753-ab59a998-42b9-11e8-866c-191f703bdd35.png)
![screenshot 23](https://user-images.githubusercontent.com/12180630/38917758-aded11c2-42b9-11e8-8c91-3ca8b51dbc65.png)

 RPCS3 v0.0.5-6657-cecfc590. Windows 10 64bit, i7 7700k, GTX 1080ti, 32gb ddr4.

**Comment by Megamouse** [comment]
what controller do you use?
could it be a turbo mode or something like that?
I don't get this issue

**Comment by WizLizard** [comment]
Xbox One controller.

**Comment by Dizziex** [comment]
Same issue here with Xone controller, except from save game ui the game controls work fine ingame.

**Comment by WizLizard** [comment]
Game controls work fine for me as well.

**Comment by WizLizard** [comment]
Tested this with an xbox one controller wirelessly and plugged in along with a dualshock 4 plugged in. All controllers give me the same problem. Save files are skipped with a single press up or down on the dpad. I've had time to test other games like Infamous and God of War Origins, both of these games have the same problem.

**Comment by Megamouse** [comment]
can you attach your zipped inputconfigs folder? and log

**Comment by Dizziex** [comment]
Her you go MegaMouse:
This is on rpcs3 build 0.0.5-6675

[InputConfigs.zip](https://github.com/RPCS3/rpcs3/files/1938888/InputConfigs.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1938904/RPCS3.log.gz)

**Comment by theoldsport** [comment]
This occurs in Dante's Inferno as well

**Comment by WizLizard** [comment]
Im finding a lot of games that have issues. Gow 3 as well. Can't even load any saves.

**Comment by WizLizard** [comment]
Here is my log and input config files.
[Input Config and Log.zip](https://github.com/RPCS3/rpcs3/files/1960287/Input.Config.and.Log.zip)

**Comment by BParks21** [comment]
Any news on this? Still broken in latest build.

**Comment by Megamouse** [comment]
can you retest?
I still haven'T encountered this bug

**Comment by BParks21** [comment]
Seems to be fixed.

**Comment by Dizziex** [comment]
Problem still persistant here, tried on latest version 0.0.5.7123

Same issue when trying to save, only last and first slot available.

**Comment by Megamouse** [comment]
This has to be your save file. I am clueless

**Comment by BParks21** [comment]
It's not the save file. I used the same file used to test this issue last time unaltered.

**Comment by Dizziex** [comment]
@BParks21: Ni no Kuni: Wrath of the White Witch [BLES01555]

Installed rpcs3 build 7130 today, deleted all my savegames through the gui (Manage - Save Game).

Started a new game, went to the point where you are able to save. Saved game three times.
When trying to load, only top and bottom savegame selectable.

**Comment by BParks21** [comment]
@Dizziex I don't know why but i simply can't reproduce this issue anymore with Ni no Kuni. Tested ogl and vulkan.

**Comment by isshininu** [comment]
Does this bug still occurs when FrameLimit set to "Auto" instead of default "OFF"?

**Comment by Dizziex** [comment]
Great work Megamouse, works like a charm 💃
