### ISSUE TITLE
[Linux] Just a Black Screen

### ISSUE THREAD

**Issue by hcorion** [RPCS3/rpcs3#4460]
If you get a black screen on linux, please add a comment to this issue with the following information:
- Linux Distro
- Graphics Card
- Graphics Driver version
and please test if it happens with both the AppImage and with self-compiled version.

**Comment by Caliel666** [comment]
Distro: Ubuntu 17.10
Graphics Card: Nvidia Gtx 1080
Driver: 384.111
Both Appimage and self-compiled 6661

**Comment by distinctV** [comment]
Black Screen stuck on 
rpcs3-v0.0.5-6661-3b24e7e6_linux64.AppImage and self compiled
Distro: Ubuntu 18.04
Graphics Card: Nvidia Gtx 1080 TI
Driver: 390.48

**Comment by Kierek** [comment]
Linux Distro: Arch Linux
Graphics Card: Radeon RX 580
Graphics Driver version: Mesa 18.0
AppImage and self-compiled, 6661

**Comment by apathyrecharge** [comment]
arch linux (4.16.2-2)
gtx 970
nvidia 390.48
both appimage & selfcompiled

**Comment by mateoag** [comment]
Linux Distro: Arch Linux (4.15.15-1)
Graphics Card: Radeon R9 270X
Graphics Driver version: Mesa 18.0.1
AppImage and self-compiled, 6661

**Comment by 7oxicshadow** [comment]
Linux Distro: Fedora 27
Graphics Card : GTX 1070
Graphics Driver : 390.48
Appimage and self compiled.

I have tried building an old version (as far back as Dec 2017)
Building with GCC
Building with Clang
Removing NVIDIA drivers and reverting to nouveau.

The only thing I have not messed with is LLVM. When building it detects that LLVM is not installed and as such builds from source. I am wondering if have a distro version of LLVM will make a difference.

**Comment by 7oxicshadow** [comment]
I have attached a back trace from a debug build incase it helps to shed some light on things.
[debug_bt.txt](https://github.com/RPCS3/rpcs3/files/1933766/debug_bt.txt)

**Comment by 7oxicshadow** [comment]
Out of curiosity, does anybody else that is having this problem use PCSX2 aswell?

I have just tried the latest build (of PCSX2) and have found that I am having problems with that now aswell. All other emulators are working fine (Including Wine).

Something has changed and I cant tell if it is a driver thing or something to do with a library file.

**Comment by Caliel666** [comment]
@7oxicshadow pcsx2 works fine for me

**Comment by dgmvecuador** [comment]
@7oxicshadow PCSX2, RetroArch and Dolphin (OpenGL and Vulkan) works fine for me ..

**Comment by ArnaudE** [comment]
Arch Linux 4.14.34-1-rt27-rt-bfq
Nvidia GeForce GTX 1080
Drivers 390.48

**Comment by Whatcookie** [comment]
I think omitting the cpu family is obscuring the problem here. The black screen problem started with the commits that changed tsx functionallity. Setting the code that detects if the cpu has tsx or not to always return false lets the program run properly and all my games go ingame again. 

try setting this function in utilities/sysinfo to always return false if your cpu supports tsx

bool utils::has_rtm()
{
    // Check RTM and MPX extensions in order to filter out TSX on Haswell CPUs
    static const bool g_value = get_cpuid(0, 0)[0] >= 0x7 && (get_cpuid(7, 0)[1] & 0x4800) == 0x4800;
    return g_value;
}
i7 7700K 
arch linux 4.16.3
amd 7950
mesa 18.0.1

I booted into windows for the first time in months and the tsx commits worked fine there. I guess this is some weird race condition but I don't know how to debug further.

**Comment by hcorion** [comment]
Hm, I bet that's the issue, because both of the linux systems I have to test with don't have TSX and work fine.
If anybody that has commented on the issue doesn't have TSX, please mention it.

Tagging @Nekotekina because he introduced the code.

**Comment by qm3ster** [comment]
- [i7-6700K](https://ark.intel.com/products/88195/Intel-Core-i7-6700K-Processor-8M-Cache-up-to-4_20-GHz) which allegedly has "Intel® TSX-NI"
- Ubuntu GNOME 17.10
- GTX 960
- Nvidia binary driver 384.111 from nvidia-384 package in the repo

Returning `false` as per @Whatcookie fixes the problem for me.

**Comment by jclc** [comment]
I also have i7-6700K and @Whatcookie's solution works for me.

**Comment by qm3ster** [comment]
@jclc does it have `hle`? `tsx` is just the name of the extension, which consists of `hle` and `rtm`.
(Irrelevant though, since `hle` is backwards compatible and doesn't require feature detection, so the function is, as named, after `rtm`)
It's fairly certain at this point that the problem is in the `rtm`-using code, unless we suddenly discovered a bug in 2-generation-old CPUs.

**Comment by oangelo** [comment]
Yes! @Whatcookie's solution works for me to!

**Comment by jclc** [comment]
@qm3ster You're right, it does have 'hle'.

**Comment by jclc** [comment]
I don't know if this is related, but loading a game or starting a new game in Persona 5 now hangs the game while frantically logging `E {rsx::thread} RSX: Dangling reports found, discarding...` twice every 0.3 seconds or so while it worked on an earlier build. Changing the PPU/SPU decoder and number of SPU threads doesn't make a difference.

**Comment by jclc** [comment]
Can someone else confirm if they're having the same issue?

**Comment by qm3ster** [comment]
@jclc maybe delete the two comments then, to keep this issue clean.

**Comment by qm3ster** [comment]
@Caliel666 @distinctV @Kierek @apathyrecharge @mateoag Please try Whatcookie's temporary rollback:
In `./Utilities/sysinfo.cpp` change line **~38** (in the `bool utils::has_rtm()` function): 
```diff
bool utils::has_rtm()
{
	// Check RTM and MPX extensions in order to filter out TSX on Haswell CPUs
	static const bool g_value = get_cpuid(0, 0)[0] >= 0x7 && (get_cpuid(7, 0)[1] & 0x4800) == 0x4800;
-	return g_value;
+	return false;
}
```

Also, if possible, post your CPU.

**Comment by mrcmunir** [comment]
I detected only under archlinux broken OpenGL backend when compile from source always black screen but working fine in latest Appimages in some recents IGPUS 9gen+ 
This problem I can't reproduced under Debian/ubuntu with latest  mesa3d compiled from source.
For Vulkan backend does work perfectly and is not affected of any kind.

**Comment by mateoag** [comment]
I have an i7-7700K, same as @Whatcookie. I just tried the temporary rollback and can confirm that it fixes the issue for me too.

**Comment by apathyrecharge** [comment]
confirming that the return false change fixes the issue on 6600k

**Comment by kisacamel** [comment]
I have ArchLinux  4.16.6 - i7-6700, @Whatcookie solution worked for me as well.
