### ISSUE TITLE
OpenGL | Worms Graphical Issue [NPUB30060]

### ISSUE THREAD

**Issue by zkitX** [RPCS3/rpcs3#4464]
![worms1](https://user-images.githubusercontent.com/30784008/39018302-a7d32eb2-43f3-11e8-9faa-d08063996dd9.jpg)

![worms2](https://user-images.githubusercontent.com/30784008/39018337-bdb0206e-43f3-11e8-870b-258effc292ac.jpg)

https://streamable.com/pnbt4

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1929823/RPCS3.log.gz)

(Windows 10 Pro 1709, Intel i7-6700 @ 3.4GHz, Nvidia 970 4GB)

**Comment by MarioSonic2987** [comment]
Disable GPU texture scaling. In Worms 2: Armageddon, it causes those glitches shown in this game.

**Comment by zkitX** [comment]
Should of looked around, closed.
