### ISSUE TITLE
ERROR 0xC000005 pls help i just wanna play persona

### ISSUE THREAD

**Issue by omar9121** [RPCS3/rpcs3#4468]
so yeah i was downloading persona 5.pkg and when i tried to play it it just says that in the title and then the program just crash. and yes i did the fix overwriting thing already, so i need your help heres the RPCS3 log file thing
[i just wanna play a game ffs.txt](https://github.com/RPCS3/rpcs3/files/1934179/i.just.wanna.play.a.game.ffs.txt)

**Comment by Renusek** [comment]
Obtain your games legally next time.

https://rpcs3.net/quickstart

**Comment by MsDarkLow** [comment]
I don't know how you downloaded Persona 5 but be sure to download it through the PS3 and dump it on your computer. kthx
Here is the link for the game https://www.playstation.com/en-us/games/persona-5-ps3/

**Comment by omar9121** [comment]
Oh ok thx guys

**Comment by HerrHulaHoop** [comment]
Close the issue?
