### ISSUE TITLE
Hatsune Miku Project DIVA F 2nd [BLUS31431] | Graphical Intel Bug

### ISSUE THREAD

**Issue by 2ASCII2** [RPCS3/rpcs3#4472]
Theres a bug on Intel(R) that causes this...

![](https://image.ibb.co/c73Abx/Captura_de_pantalla_361.png)

There's any fix to this?

**Comment by AniLeo** [comment]
Missing all information there is to miss

**Comment by 2ASCII2** [comment]
Here is the log: https://cdn.discordapp.com/attachments/319224795785068545/437365311616974858/RPCS3.log.gz

**Comment by AniLeo** [comment]
Wrong log, there's nothing related to this there

**Comment by 2ASCII2** [comment]
Nevermind.

I close this.
