### ISSUE TITLE
Regressions after #4422 (SPU ASMJIT v2.0)

### ISSUE THREAD

**Issue by TigiHof** [RPCS3/rpcs3#4473]
Dead Space Extraction (NPUB30314) no longer goes ingame.

[RPCS3-6664.log.gz](https://github.com/RPCS3/rpcs3/files/1935102/RPCS3-6664.log.gz)
[RPCS3-6675.log.gz](https://github.com/RPCS3/rpcs3/files/1935103/RPCS3-6675.log.gz)

**Comment by JMC47** [comment]
Causes severe physics slowdown in the EA NHL games (NHL 09 onward)

**Comment by JMC47** [comment]
I have tested the other spu backends but am not at home right now to
confirm.

Spu interpreter is much slower in the sense that less frames are rendered.
Videos and gameplay and sound are incredibly choppy.  But the actual
physics of the game are more consistent.

The old asmjit had physics inconsistent for the first 15 to 30 seconds.
New asmjit is stuck like that permanently with only these brief moments
where the game goes to normal speed, mostly when the puck is not in play.

It is kind of hard to explain, I can get videos of all behaviors if it
would be of assistance.

**Comment by Nekotekina** [comment]
@JMC47 I'm talking about Preferred SPU Threads (primarily), and other options. #4422 made them more important.

**Comment by Zangetsu38** [comment]
i have also few probleme on few game nows, freeze randomly, before not have that, god of war 3 Puppeetter, and same for tlou, him very more freeze compared before

**Comment by JMC47** [comment]
Apologies. I will test it next time I get a chance.

**Comment by JMC47** [comment]
I've tried all the SPU options, nothing seems to affect this whatsoever.  I noticed that replays are not affected by the slowdown (in fact they run quite well,) so I truly do believe it's something to do with the puck's movement/physics.

**Comment by AniLeo** [comment]
Add Catherine to the list, also verified it's black screen after intro logo here

**Comment by frymezim** [comment]
Games won't compile LLVM cache PPU modules on my 4th Intel Processor. The last working commit was #4336.

**Comment by MsDarkLow** [comment]
The thing that happens with Catherine also happens on Persona 4 Arena Ultimax.
The game freezes after the intro cutscene

Doesn't work on Latest nor Neko's Merge.
Latest: 
[RPCS3P4AU6692.log.gz](https://github.com/RPCS3/rpcs3/files/1958915/RPCS3P4AU6692.log.gz)
Older build: 
[RPCS3P4AU6664.log.gz](https://github.com/RPCS3/rpcs3/files/1958916/RPCS3P4AU6664.log.gz)

**Comment by lexer98** [comment]
From 6675, I have this error with Catherine, i tried multiple settings but always happens the same. 
![captura de pantalla_2018-05-01_20-55-32](https://user-images.githubusercontent.com/3074179/39499155-ad8eb4a0-4d82-11e8-8a98-e29bde448f06.png)
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/1965534/RPCS3.log.zip)

**Comment by MarioSonic2987** [comment]
Some games are unable to skip certain videos. In this case, with Worms Revolution freezes after ending or skipping Team17's video:
Prior to #4422:
![image](https://user-images.githubusercontent.com/20027681/40682249-92611082-638b-11e8-9582-4cec3aff1418.png)

#4422 and newer (I skipped Team17's video):
![image](https://user-images.githubusercontent.com/20027681/40682353-c636ea76-638b-11e8-8a39-e966dc5c801d.png)

Also affects KH 1.5, KH 2.5 and Super Street Fighter IV Arcade Edition [NPUB30649].

[Log WR 29-5-18 GL.gz](https://github.com/RPCS3/rpcs3/files/2050563/Log.WR.29-5-18.GL.gz)
[Log WR 29-5-18 GL Broken.gz](https://github.com/RPCS3/rpcs3/files/2050617/Log.WR.29-5-18.GL.Broken.gz)

**Comment by AniLeo** [comment]
Test with #5310

**Comment by MarioSonic2987** [comment]
I confirm that it's fixed.
![image](https://user-images.githubusercontent.com/20027681/48005094-dbe9e580-e112-11e8-888e-3c03f4c05c68.png)
![image](https://user-images.githubusercontent.com/20027681/48005141-f623c380-e112-11e8-8a67-611fc9214dcb.png)
![image](https://user-images.githubusercontent.com/20027681/48005396-a42f6d80-e113-11e8-93c8-6d1b45be676a.png)

KH 2.5 is tested 3 times (intro cutscene).

**Comment by elad335** [comment]
Needs closing as fixed.

**Comment by TigiHof** [comment]
Here you go! :-)
