### ISSUE TITLE
Unnamed [BLES02247] - Character portrait black lines

### ISSUE THREAD

**Issue by BRI4RHEART** [RPCS3/rpcs3#4474]
This issue has been going since January but I didn't bother reporting until now as #4422 has just been released.

My specs:
Windows 10 Pro x64
i3 4170 3.7Ghz
GTX 960 4Gb
12Gb RAM

![p5-glitch](https://user-images.githubusercontent.com/38596853/39090327-92ab062a-45b2-11e8-8868-1456dabe6781.png)
(Pay attention to Nijima's portrait on the left side)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1935144/RPCS3.log.gz)

(This is my first post on this project and on GitHub, please bear with me)

**Comment by AniLeo** [comment]
There's a mod for Persona 5 around that makes textures upscalable.
That only happens if you use Resolution Scale. You must use the mod if you want to play at Scaled Resolutions with proper portraits.
