### ISSUE TITLE
A compilation problem

### ISSUE THREAD

**Issue by xyc19970716** [RPCS3/rpcs3#4476]
When i want to compile this project, my visual studio community 2017 shows me a problem that needs a narrowing conversion.   It's Compiler Error C2397.
![default](https://user-images.githubusercontent.com/20499955/39093956-8b44032a-465a-11e8-885b-c88bb58be797.PNG)
 I do not know how to do next.  The version is current.  No percomiled LLVM Lib, just use debug x64 to build.  Or maybe i do something wrong.

**Comment by 4669842** [comment]
If you do not understand how to install dependencies to build, then download an edge release from projects appveyor https://ci.appveyor.com/project/rpcs3/rpcs3

The last build was an hour ago: https://ci.appveyor.com/project/rpcs3/rpcs3/build/artifacts

**Comment by AniLeo** [comment]
Build Release, not Debug.

**Comment by 13xforever** [comment]
Release-LLVM to be precise
