### ISSUE TITLE
Uncharted SPU issue

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#4478]
On ASMjit and SPUFast in Uncharted there are few issues
1 When you kill an enemy NPC it not just remain dead, body models are shaking in convulsion like it catch some seizure
https://c.radikal.ru/c34/1804/83/73f6d089d09ft.jpg
https://a.radikal.ru/a11/1804/68/de12137732b3t.jpg
2 Grenades. When you or enemy throw it, it just get stuck in the air and never explodes, unless you come very close to it
https://b.radikal.ru/b01/1804/d1/64480819e6d6t.jpg

but all these issues ain't presented on Spu Precise, found out that FS instruction cause this it's broken for both Fast and ASMJit
https://a.radikal.ru/a42/1804/74/f17055fe91b7t.jpg
https://d.radikal.ru/d36/1804/c6/cf1977330389t.jpg

Was able to fallback to it from asmjit by swithching spu_interpreter_fast and spu_interpreter_precise between FS versions and got it fixed, perhaps it helps some other stuff
Please someone take a look

**Comment by kd-11** [comment]
Thanks for doing the required debugging. It makes fixing bugs a lot easier. I might look into this issue during or after my next PR.

**Comment by Xcedf** [comment]
That would be nice, thanks a lot

**Comment by elad335** [comment]
This issue is fixed by using SPU LLVM with xfloat enabled.

**Comment by Xcedf** [comment]
Yes, i know but only for LLVM, asmjit still has it

**Comment by Xcedf** [comment]
I think since SPU LLVM progressed so far there's no need to fix it for ASMjit, Uncharted 1 has a very little amount of SPU cache, so i gues this one could be fixed. But i also think some kind of option should be added for accurate FS instruction, or an aproximate version should be added, cause using accurate xfloat is pretty exepensive, and Uncharted 1 is the only game so far which reqires accurate FS instruction

**Comment by dio-gh** [comment]
I'm not sure it's LLVM related, but there's another math issue with Uncharted, namely floating/swaying vegetation. Just wanted to drop this here, in case it's not reported elsewhere and it's related.

**Comment by Xcedf** [comment]
I'm not sure if it's SPU related at all, i tested vegetaton in all SPU options and nothing

**Comment by Xcedf** [comment]
fixed with https://github.com/RPCS3/rpcs3/pull/6894
