### ISSUE TITLE
Drakengard 3 [BLUS31197] - Artifacts everywhere when upscaling.

### ISSUE THREAD

**Issue by xyph3rz** [RPCS3/rpcs3#4480]
**RPCS3 Version:** 0.0.5-6675-bd1d4de4 Alpha
**Game:** Drakengard 3 [BLUS31197]

**Issues:**
The game graphics/textures are riddled with red or green artifacts when I try to upscale the game. I've already tried several settings but none of them elevates the issue except when I run the game at strict rendering mode at 720p (no upscale). Increasing/decreasing the threshold also does nothing.

**Settings & ingame screenshot:**
![cpu](https://user-images.githubusercontent.com/9674936/39110051-357d098e-4702-11e8-8363-0761c1c8a0c6.jpg)
![gpu](https://user-images.githubusercontent.com/9674936/39110053-373fc004-4702-11e8-8c4f-0ae655a47ac3.jpg)
![ss](https://user-images.githubusercontent.com/9674936/39110055-38e6305a-4702-11e8-806e-6877fa0c1db6.jpg)

**RPCS3 Log:**
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1936906/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Invalid issue, disable anisotropic filter

**Comment by Mikur0** [comment]
i got the same issue but with this config

<img width="1792" height="1018" alt="Image" src="https://github.com/user-attachments/assets/adb46a52-5fdf-4048-959f-8604de41fdca" />
