### ISSUE TITLE
stop gaving issue rpcs3 rpcs3 support fastfoward

### ISSUE THREAD

**Issue by asbel123** [RPCS3/rpcs3#4483]
get cheat engine there a option called speedhack u can play games fastfoward i use 2 times on ni no kuni its better than real ps3 better than pcsx2. make the music faster like pcsx2 u dont need support fastfoward rpcs3 u got in cheat engine speed hack its work everygame pc like chrono trigger pc version better than andriod.

**Comment by clienthax** [comment]
Don't spam the issue tracker with non sensical crap
