### ISSUE TITLE
Yakuza 1&2 HD EDITION (BLJM60471) graphic blur

### ISSUE THREAD

**Issue by Rpcs3tester** [RPCS3/rpcs3#4493]
![2018-04-27_15-34-01](https://user-images.githubusercontent.com/38118895/39362883-c8099b10-4a30-11e8-9df3-f39a72b8eeaa.jpg)
![2018-04-27_15-34-34](https://user-images.githubusercontent.com/38118895/39362884-c83e2eb6-4a30-11e8-92f0-ae00edc35406.jpg)
![2018-04-27_15-35-22](https://user-images.githubusercontent.com/38118895/39362885-c86ed3b8-4a30-11e8-8024-8c65fce9ed3c.jpg)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1955102/RPCS3.log)

it's almost fixed with Strict rendering mode but blur show up for seconds randomly

**Comment by kd-11** [comment]
Close if issue does not happen with strict mode.

**Comment by MsDarkLow** [comment]
Issue still persists
Log: [RPCS3Yakuza1and2.log.gz](https://github.com/RPCS3/rpcs3/files/2300658/RPCS3Yakuza1and2.log.gz)
![1](https://user-images.githubusercontent.com/9060436/44313256-fefed600-a3fc-11e8-9961-5eacfd11441b.jpg)

**Comment by MsDarkLow** [comment]
Issue still persists.
Without SRM its the same
![2](https://user-images.githubusercontent.com/9060436/54650691-987f8a80-4aa7-11e9-9f94-6383e182fcf0.jpg)
[RPCS3Y1n2.log.gz](https://github.com/RPCS3/rpcs3/files/2986047/RPCS3Y1n2.log.gz)


With SRM it has this weird cube on top left which renders slightly different, its present 
during cutscenes and gameplay.
![1](https://user-images.githubusercontent.com/9060436/54650742-c82e9280-4aa7-11e9-9e4f-9e6369e10b4d.jpg)
[RPCS3Y1n2 SRM.log.gz](https://github.com/RPCS3/rpcs3/files/2986044/RPCS3Y1n2.SRM.log.gz)

**Comment by Solidcal** [comment]
Tried this on the latest build and it would appear the issue of the blur has been fixed. Both 720 and 1080 resolutions are fine and even when upscaled past these, it seems to work without the blur issue.

![Screenshot_8](https://user-images.githubusercontent.com/52046674/64913673-5bd1da80-d73c-11e9-9fb4-492330e76a78.png)
![Screenshot_9](https://user-images.githubusercontent.com/52046674/64913674-5bd1da80-d73c-11e9-9572-8eefaca09362.png)
![Screenshot_10](https://user-images.githubusercontent.com/52046674/64913675-5c6a7100-d73c-11e9-8795-299e6af4c434.png)
![Screenshot_11](https://user-images.githubusercontent.com/52046674/64913676-5c6a7100-d73c-11e9-8d8d-b7732439abbe.png)
![Screenshot_12](https://user-images.githubusercontent.com/52046674/64913677-5c6a7100-d73c-11e9-8b96-9412ac9b5a64.png)

**Comment by AniLeo** [comment]
Closing as fixed
