### ISSUE TITLE
Game generates a lot of shaders

### ISSUE THREAD

**Issue by rdeleonp** [RPCS3/rpcs3#4495]
Hi.

RPCS3 v0.0.5-6692-98b715d8c Alpha | HEAD
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz | 8 Threads | 31.95 GiB RAM | AVX+ | TSX
Title: Castle of Illusion Starring Mickey Mouse (Trial)
Serial: NPUB31099

Just a question: Is it normal for this game to generate hundreds/thousands of shaders?

If so, please feel free to close this issue.

Thanks for your time.

Cheers.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1957022/RPCS3.log.gz)

**Comment by legend800** [comment]
Please close this. This is a place for legitimate code defects not Q&A sessions.

**Comment by rdeleonp** [comment]
@legend800 

Sorry for any troubles. Will do as you request.

Cheers.
