### ISSUE TITLE
Ryu ga Gotoku Kenzan! (aka Yakuza Kenzan!) [BLJM60064] unable to go ingame

### ISSUE THREAD

**Issue by Renusek** [RPCS3/rpcs3#4496]
This game won't boot in RPCS3 right now. There is a problem with loading a SPRX module from game files that prevents the game from going to main menu (and ingame).

Using latest master: RPCS3 v0.0.5-6692-98b715d8c Alpha | HEAD (it never worked though, so you can reproduce it on any version)

All testing was done using **OpenGL** and with **strict rendering enabled** (since it helps other Yakuza game too - *1&2 HD*)

The problematic SPRX module is: "BLJM60064\PS3_GAME\USRDIR\bin\module\ps3\pxd_shader_ps3.ppu.sprx"
If you remove or rename that file the game will boot, showing 2 prerendered cutscenes and main menu.

### With SPRX file
PPU and SPU set to **Precise**: [KenzanPrecise.zip](https://github.com/RPCS3/rpcs3/files/1958901/KenzanPrecise.zip)
PPU and SPU set to **Fast**: [KenzanFast.zip](https://github.com/RPCS3/rpcs3/files/1958902/KenzanFast.zip)
PPU and SPU set to **Fastest**: [KenzanFastest.zip](https://github.com/RPCS3/rpcs3/files/1958903/KenzanFastest.zip)

### Without SPRX file

PPU and SPU set to Fastest (with renamed SPRX file): 
[KenzanFastest-noSPRX.zip](https://github.com/RPCS3/rpcs3/files/1958921/KenzanFastest-noSPRX.zip)

5 bucks to anyone who solves this issue [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=57733711)](https://www.bountysource.com/issues/57733711-ryu-ga-gotoku-kenzan-aka-yakuza-kenzan-bljm60064-unable-to-go-ingame?utm_source=57733711&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by elad335** [comment]
fixed in #4728
