### ISSUE TITLE
Check game compatibility doesn't launch firefox on linux

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#4498]
ArchLinux.
Rev 6638: right clic>Check game compatibility launches firefox
Rev6653 and above (maybe also a few revisions before): right clic>Check game compatibility: nothing happens.
On the console:
```
qt.core.logging: Ignoring malformed logging rule: '’*=false’'
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
/usr/bin/xdg-open : ligne 609 :  3617 Abandon                 (core dumped)kde-open${KDE_SESSION_VERSION} "$1"

```

**Comment by scribam** [comment]
@toccata10 Do you have the issue with an AppImage or with a build you compiled (if yes, please specify the version of Qt)?

**Comment by toccata10** [comment]
On AppImage: here's the console output:
kde-open5: /tmp/.mount_rpcs3-YE6UpV/usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /usr/lib/libQt5Xml.so.5)
kde-open5: /tmp/.mount_rpcs3-YE6UpV/usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /usr/lib/libQt5X11Extras.so.5)
kde-open5: /tmp/.mount_rpcs3-YE6UpV/usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /usr/lib/libQt5Svg.so.5)

I compiled RPCS3 v0.0.5-6889-4b0796e97 Alpha | rsx_volatile yesterday. The compatibility check launches firefox at the correct page. My qt version is 5.11
![selection_099](https://user-images.githubusercontent.com/7478580/40925623-75379862-681a-11e8-8cc1-6e5147f1973b.jpg)

Might be something for @hcorion

**Comment by scribam** [comment]
I confirm this is an issue related to the AppImage only.
Tested with [rpcs3-v0.0.5-7435-8540399e_linux64.AppImage](https://rpcs3.net/cdn/builds/rpcs3-v0.0.5-7435-8540399e_linux64.AppImage) on Antergos and I have the following error when I click on "Check Game Compatibility":
```
Error: no DISPLAY environment variable specified
```

**Comment by AniLeo** [comment]
Still happening, tested on arch as well
