### ISSUE TITLE
[Feature Request] Hiding the Mouse Cursor

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#4502]
Hi,

Since there's a "Don't use double click for fullscreen mode" option to support the binding of the mouse buttons, it'd make sense if people could also hide & lock the mouse cursor within the game window boundaries with a certain key combo. Auto-hiding the cursor (again, in windowed mode) if it's not moving for several seconds would also be a nice touch.

* [x] auto-hide cursor after idle
* [x] hotkey for hiding and locking the cursor within window boundaries

Thanks!

**Comment by JohnHolmesII** [comment]
Why not just move the mouse to the titlebar?

**Comment by MsDarkLow** [comment]
Its already in there

**Comment by Renusek** [comment]
if anything, the cursor should disappear after x seconds if not moved imo

**Comment by nitrohigito** [comment]
@JohnHolmesII Because if I click on the titlebar, it minimizes the window...

@Renusek Sure, but the point is that it should disappear when in use too. You hardly need it while in combat in e.g. God of War. I agree that it's not that important, but one might find it distracting/annoying, and rightfully so.

**Comment by tlm-2501** [comment]
I agree that the mouse shouldn't be visible over the emulator window, I don't even think this has to be an option, just hide it and that's it. This would be particularly useful in combination with a mouse-to-right-analog movement setup if and when that becomes possible.

**Comment by nitrohigito** [comment]
Actually, with 3rd party tools it's already a possibility afaik. There's a Feature Request for implementing that natively too, but that hasn't come to fruition yet.

**Comment by Megamouse** [comment]
we can't put gui settings into per game configs. You'll have to deal with the global setting for it.

**Comment by Megamouse** [comment]
to be fair... it seems we already have a few misc options in there. we'll see in time

**Comment by shinra358** [comment]
I second this request. This is an easy application and the best way to go about it is to hide cursor while inside the emu box after 2 seconds of inactivity. Of course we can use 3rd party programs to do it. But why? I'm glad ppl came to their sensing about adding hotplugging and afterplugging for controllers. This is just as important to have for all of emulation and this is one of those things that are always requested that shouldnt even have been requested because gamers should know by now that this is a necessity and one of those things that contribute to a real pc being poorly ported or not.

**Comment by isJuhn** [comment]
we could do like how PCSX2 did it, bind a button to lock the cursor in the window and hide it. That could also work well in conjunction with #4455

**Comment by shinra358** [comment]
completely hiding it over a window is annoying and can be hard to track it when you're trying to do something else with the emu on. There's nothing hard about the above and is pretty much less than 6 lines of code : P

But also, pcsx2 had the option of unclicked: hides after 2 seconds of keyboard mouse inactivity, and click: hide completely all the time. So yeah, I pretty much covered it.

**Comment by nitrohigito** [comment]
I think there might be some misunderstanding regarding what I'm asking for, so I'll reword the original post.

**Comment by shinra358** [comment]
Binding that to a button makes no sense and is a nightmare for ppl with gamepads. I don't want to get up to press the keyboard when it can automatically happen for me right where I am xD

**Comment by bevanweiss** [comment]
I think I get the use-case.  When using mouse+keyboard, you don't want the mouse flying all over the screen.
But likewise there are situations when the mouse does want to be 'released' from the game window during the game.

So, a configurable keyboard combo to toggle 'lock cursor to game window'.
Should it also hide the cursor (within the game window)?

**Comment by dio-gh** [comment]
> Binding that to a button makes no sense and is a nightmare for ppl with gamepads.

??? If you're using a gamepad, why would you care about locking the mouse cursor inside the window viewport?

> So, a configurable keyboard combo to toggle 'lock cursor to game window'.
Should it also hide the cursor (within the game window)?

Yes, as the original ticket describes (lock & hide).

**Comment by bevanweiss** [comment]
@dio-gh is this close enough to be considered done? :)
If there's any other minor annoyances, perhaps we could raise a new issue for it?

**Comment by dio-gh** [comment]
I thought this was auto-closed on merge, sorry. Current implementation is flawless, thank you.
