### ISSUE TITLE
Linux: DDX drivers not loading correctly (AppImage only)

### ISSUE THREAD

**Issue by John-Gee** [RPCS3/rpcs3#4509]
Hello,

sometimes after build rpcs3-v0.0.5-6592-a36acf49_linux64.AppImage RPCS3 stopped working with Vulkan and prints "Could not find a supported Vulkan surface extension". Only the OpenGL and Null renderer are available.

I only see old builds for Windows on rpcs3.net so I am not able to find which one started having this issue, the oldest one I have with this problem is rpcs3-v0.0.5-6675-bd1d4de4_linux64.AppImage.

I am on Arch Linux, using a 280X with mesa-git and llvm-svn. I use RADV-git for Vulkan.

**Comment by Gamedev1909** [comment]
sudo gedit /etc/default/grub, and edit/make the line:

GRUB_CMDLINE_LINUX="radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1"

and then 

update-grub and reboot then sudo apt get install mesa-vulkan-drivers

**Comment by John-Gee** [comment]
That's unrelated.

RADV already works with a previous build so I should not need to change anything related to amdgpu.

**Comment by Gamedev1909** [comment]
but you do need to do as i said above as of kernel 4.13 sorry

**Comment by John-Gee** [comment]
Again, it currently works with an older RPCS3 build so that's unrelated, but I've already done that long ago since without it radv would not work (well minus the ck part since my card is si).

**Comment by kd-11** [comment]
Use X not wayland.

**Comment by John-Gee** [comment]
Oh I should have specified that but I'm using Xorg, with Plasma if it matters.

**Comment by Gamedev1909** [comment]
im using wayland and have no issues

**Comment by John-Gee** [comment]
That's reassuring for the future!

**Comment by kd-11** [comment]
Try forcing dri3. Also need vulkaninfo output to verify surface extension is not being reported.

**Comment by John-Gee** [comment]
grep -i dri3 /var/log/Xorg.0.log 
[    34.668] (**) AMDGPU(0): DRI3 enabled

vulkaninfo: https://gist.github.com/John-Gee/c93f6d4e89ec15b1c1ad58a68dff071d

**Comment by kd-11** [comment]
Nothing seems to be wrong according to ouput. I would suggest building rpcs3 from source and see if there's something not working well with appimage itself.

**Comment by John-Gee** [comment]
Good guess, that worked!

Since I'm using llvm-svn I cannot use the llvm backend with RPCS3 if I simply build it. I doubt it's related but just in case I thought I'd specify it.

**Comment by John-Gee** [comment]
In case it helps, when starting the appimage if it does not complain about Vulkan (but won't show it in the menu...) it prints this:

No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.

And when I start a game using OGL:
Could not initialize GLX
zsh: abort (core dumped)  ./rpcs3-v0.0.5-6694-25ec899c_linux64.AppImage

Maybe @hcorion knows about appimage stuff.

**Comment by kd-11** [comment]
I'm guessing deleting libgl/libvulkan shared libs from the appimage will fix it for you. The appimage dependencies need more extensive testing which is a chore due to the different configs ppl have. If you can, always build from source.

**Comment by John-Gee** [comment]
I don't know anything about appimages so I simply extracted it with "--appimage-extract", removed libvulkan.so.1 in squashfs-root/usr/lib then ran AppRun but it was no different. 

If I run rpcs3 in squashfs-root/usr/bin without removing anything it seems to run fine, including with Vulkan and LLVM.

Does that make sense to you? If all I have to do is extract the image it's an easy workaround. 

I'd be very happy to build it from source myself but I don't know how to workaround the LLVM issue. How do I get it to build and run with the LLVM recompiler while using llvm-svn on my system?

Thank you!

**Comment by hcorion** [comment]
It should build and run fine with llvm-svn on your system, if the cmake build doesn't find a compatible version of llvm it'll build it's own version.

**Comment by John-Gee** [comment]
Oh I had no clue you fixed that, it's awesome!

Indeed it built and started without an issue, though I can't install it since the llvm libraries conflict, but I should be able to find something about that.

I'm happy to help with the appimage issue if needed.

**Comment by kd-11** [comment]
Still an issue? Its likely an update to cmake or system libs has since fixed this.

**Comment by John-Gee** [comment]
It's still the same, I've just tried with latest appimage.

**Comment by toccata10** [comment]
Confirming that on ArchLinux, the appimage doesn't work: 
```
./rpcs3-v0.0.5-6927-3dd45fc8_linux64.AppImage 
qt.core.logging: Ignoring malformed logging rule: '’*=false’'
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.
Could not initialize GLX
Abandon (core dumped)
```
Vulkan doesn't show up, just OpenGl and null.
If I build from source, it works fine.
Old versions don't work anymore. Yesterday, mesa was updated from 18.0 to 18.1.1. Seems related.

**Comment by logos88** [comment]
I have the same problem with last appimage in Archlinux

``No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.
Could not initialize GLX``
