### ISSUE TITLE
God of War 3 Black Screen RPCS3

### ISSUE THREAD

**Issue by ridhoilhamkaspari** [RPCS3/rpcs3#4513]
Specs:
CPU : Intel Core i3-3227U 1,9Ghz
RAM : 4GB
VGA : Nvidia GeForce 710M
RPCS3 0.0.5-6694-25ec899cf Alpha
PS3 System Software 4.82

Setting:
PPU : LLVM
SPU : ASMJIT
Enabled thread scheduler
Enable SPU loop detection
Renderer : OpenGL
Resolution Scale : 100%
Used GPU Texture Scaling
Disabled Vertex Cache

When I try to boot the God of War 3 (BCES00510), i just seen the black screen with 60fps. After waiting for several minutes, the framerate freeze at 0,96 and the screen still black. Please help me to fix this problem.

My Log:
https://drive.google.com/open?id=1Q4lb75jw2yboxtS-_-ofJ0vtbir4ltpP

[log.txt](https://github.com/RPCS3/rpcs3/files/1971833/log.txt)

**Comment by AniLeo** [comment]
Thread on GoW3 regression is already opened, closing as duplicate
