### ISSUE TITLE
SSX LoopSimulation Issue

### ISSUE THREAD

**Issue by PlayerWind** [RPCS3/rpcs3#4518]
Trying to Boot the Game only show light blue

And show a Loop Error+MEM Error

Log: http://ge.tt/2twQigp2

Screenshot: http://ge.tt/7BRVigp2

Bulid: RPCS3 v0.0.5-40c9e031f Alpha | akiba

**Comment by AniLeo** [comment]
Invalid issue, not using master build, plus this game is only Loadable and it has already been reported on our forums
