### ISSUE TITLE
crash in infernal dante's

### ISSUE THREAD

**Issue by Shark1337** [RPCS3/rpcs3#4519]
Hello,

the game crashes me in the infernal dante's on the part of death, always in the same part,
My PC:
gtx970
i7 7700k
16 GB

I have uploaded the logs generated by the crash

https://drive.google.com/open?id=1ByJua4fRmNRrKZrXjxbeRfxyFgUjwaW0

**Comment by Shark1337** [comment]
hello, thank you very much for the answer, with opengl I did not work either,

**Comment by AniLeo** [comment]
Closing as there's another more detailed issue regarding this bug at #4534

You can follow discussion there
