### ISSUE TITLE
NI NO KUNI [BLES01555] crackling/skipping sound only with OpenGL

### ISSUE THREAD

**Issue by psennermann** [RPCS3/rpcs3#4520]
I don't know why (video backend shouldn't affect audio), but in the game NI NO KUNI [BLES01555] using Vulkan I get perfect audio, while OpenGL has crackling sound even at full speed 30 fps (especially audible in the Factor 5 logo screen and intro music, while during gameplay audio sometimes skips).

Win10
i5 7400
gtx1060 3gb
MSI Realtek integrated audio

**Comment by Asinin3** [comment]
This is due to having a slow processor, Audio with OpenGL on Ni No Kuni is fine with both renderers with a faster processor. Vulkan is probably helping by removing some of the cpu overhead which is helping give your CPU more room to compute other tasks. Invalid issue

**Comment by BongoEADGC6** [comment]
Same issue occurs with a Ryzen 5 1600 and AMD 7970.

OpenGL crackles, Vulkan barely any at all.

**Comment by psennermann** [comment]
Tried on the i8700 of my brother and it crackles as well, so it's definitely a backend issue

**Comment by psennermann** [comment]
Yes, it's fixed!
