### ISSUE TITLE
High cpu core usage when SPU Thread is set to Auto

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#4523]
In testing from my friends PC, I noticed that CPU core usage is higher when spu threads is set to auto, what should be expected was the thread should get distributed to more cores. Below are the Images for comparison.

SPU Thread = 2
![report2](https://user-images.githubusercontent.com/13552004/39667463-7ba68c5a-50e9-11e8-99eb-46a4db2da3cf.jpg)

SPU Thread = Auto
![report1](https://user-images.githubusercontent.com/13552004/39667462-7b625ba2-50e9-11e8-880b-b5962871f513.jpg)

SPU Thread = 6
![report3](https://user-images.githubusercontent.com/13552004/39667495-4c1fba64-50ea-11e8-99a2-d4ef07d9d4c6.jpg)

Params
2x Xeon EP-2670 2.7 GHz 24Gb ram Gtx 1060
SPUASMJIT Recompiler
PPU LLVM Recompiler
Vulkan
OpenAl
D3 BLUS31467

**Comment by kd-11** [comment]
Closing as its not a real issue (more cores at slow ghz is not the same as few cores with more ghz)
