### ISSUE TITLE
Huge performance drop after upgrade to Windows 10 1803

### ISSUE THREAD

**Issue by Couchy** [RPCS3/rpcs3#4528]
This is probably a Windows issue, but thought it should be tracked here due to its severity and as a warning to others. I was in the middle of playing Persona 5 on Windows 10 1709, and was getting very much playable framerates around 30 FPS. "Upgrading" to 1803 caused it to become totally unplayable with extreme stuttering and drops to about 10 FPS. Rolling back to 1709 restored the performance.

Specs: i5 4670k @ 4Ghz, AMD RX 470, 8GB RAM
rpcs3-v0.0.5-6692-98b715d8_win64

**Comment by TigiHof** [comment]
Go to Windows 10 safe mode and execute "Display Driver Uninstaller" (https://www.wagnardsoft.com) to completely remove your graphics driver. Then restart Windows and install the driver afresh. That should resolve the problem.

**Comment by pauls-gh** [comment]
I saw similar performance drop with Tales of Vesperia on Windows 10, 1803 update.

Performance fell from 45 to 25 fps (sleeping dog) and 17 to 14 fps (town). To confirm the 1803 update was responsible, I uninstalled the 1803 update, and performance is restored. 

I'll try the display driver uninstall.

**Comment by pauls-gh** [comment]
I tried Display Driver Uninstaller.  Performance is still poor. 
I also tried to disable the new transparent UI in the Windows 10 1803 update (Personalization/Colors/Transparency Effects).  No difference.

Tales of Vesperia is very much CPU dependent.  I don't think this is GPU related.

**Comment by DarKotE** [comment]
Try rightclick on rpcs3.exe - properties - compability - tick [ ] disable fullscreen optimizations. Not sure if it will help though.

**Comment by pauls-gh** [comment]
disable fullscreen optimizations - didn't help.

**Comment by isshininu** [comment]
Looks like your issue is similar to mine https://github.com/RPCS3/rpcs3/issues/4130
You can try switching to W7 or W8.1 to avoid perfomance loss.

**Comment by allstar319** [comment]
Have the same issue. Reported it the first day on the forum, nobody replied unfortunately. Even tried a brand new install of 1803 and I still get the same results.

**Comment by Kravickas** [comment]
U need to install gpu drivers from nvidia/amd site again after win big updates

**Comment by GoaLitiuM** [comment]
I had this problem initially when I upgraded to Windows Insider builds few weeks back but the performance got restored back after reinstalling the drivers and restarting the PC couple times. Again today the performance dropped back to those numbers but few other games are also affected, not just RPCS3.

**Comment by gandalfthewhite19890404** [comment]
Seems native Win10 driver has some issues.

**Comment by allstar319** [comment]
Guess I'll give the Insider builds a try and see what happens seeing as nothing I do on a fresh copy of 1803 (even DDUing and reinstalling Nvidia drivers) does nothing for me.

**Comment by pauls-gh** [comment]
I tried 17666 also.   I initially saw 6 fps at the Vesperia Start Menu (should be 30+), much worse than 1803.  I reinstalled the graphics driver a few times, freed hard drive space, downloaded the latest RPCS3 and magically it started to get decent performance again.  Not sure exactly why this occurred.

Tales of Vesperia performance with 17666 is the same as 1803 i.e. less than before 1803.

For reference,  performance in Tales of Vesperia when using 17666
>> Performance fell from 45 to 25 fps (sleeping dog) and 17 to 14 fps (town). 

My system
Alienware R7, Intel i7 8700,  Nvidia 1070ti

@allstar319 - not sure if you have an Alienware machine, but there is a new BIOS update for 8700K to fix an overclocking issue. 
[http://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=5805W]

**Comment by LobsterBeef** [comment]
Rolling back to .5-6675 fixed it for me

**Comment by pauls-gh** [comment]
I figured out the Tales of Vesperia performance issue with Windows 10 update 1803. 

It appears to be related to the Windows timer resolution.
[](url)https://msdn.microsoft.com/en-us/library/windows/desktop/dd757633(v=vs.85).aspx

By default, timers have a 15 msec resolution in Windows.  Multimedia applications can set the timer resolution lower if needed (e.g. for animation).

RPCS3 sets the timer to 1 msec.

If I force the timer resolution to the minimum (0.5 msec), then the Vesperia frame rates return to normal.

Sleeping dog 25 fps => 45 fps
Town  14 -15 fps => 18-19 fps

You can get/set the timer resolution by using this small app.
[https://vvvv.org/contribution/windows-system-timer-tool](url)

I'm guessing prior to Win10 1803, there was an OS component or possibly another app that was setting a 0.5 msec timer resolution.  Note that the timer resolution is system wide.  

I'd recommend that we change RPCS3 to use a 0.5 msec timer resolution.  Also, we'd probably need to look at removing any dependencies on these timers (if possible) as it is definitely affecting multiprocessor performance.

**Comment by pauls-gh** [comment]
I'm going to create a separate issue for the timer resolution / Tales of Vesperia problem as it appears its not truly related to the 1803 update.

**Comment by kd-11** [comment]
Can anyone confirm this issue still happens even with timer resolution fixed?

**Comment by Zm0n** [comment]
Testing the latest nightly says it's now fixed. Timer goes to it's appropriate setting (0.5) and FPS is back to where it was prior to Windows 1803.

**Comment by kd-11** [comment]
Closing as fixed via https://github.com/RPCS3/rpcs3/pull/4579
