### ISSUE TITLE
Kingdom Hearts 2.5 crashing after Nobody fight BLUS31460

### ISSUE THREAD

**Issue by Laughenman** [RPCS3/rpcs3#4530]
Besides the coin flip crash after the intro cutscene, fight the first nobody and the cutscenes that follow crash the game, either during the cutscene of Sora's memories or right after the cutscene ends
Edit:Forgot to mention I'm running this on an HP Envyx360 Laptop.
RPCS3- 0.0.5-6694-25ec899cf Alpha
CPU
PPU-interpreter
SPU-ASM recompiler
SPU Thread-1
Load liblv2.sprx
Enable thread scheduler
Lower SPU Thread Priority
GPU
OpenGl
Frame limit off
No Additional settings
Default resolution
Automatic Anisotropic filter

S Elf Boot from drag and drop done: C:/Users/mofacah/Downloads/K_H_2/BLUS31460-[KINGDOM HEARTS HD 25 ReMIX]/PS3_GAME/USRDIR/kingdom2.self
U {PPU[0x1000000] Thread (main_thread) [0x02973e64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x029740bc]} sys_prx TODO: _sys_prx_register_library(library=*0x29766a0)
S {PPU[0x1000000] Thread (main_thread) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0297bd8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x029754d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x029754d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x029754d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0297461c]} sys_prx TODO: _sys_prx_register_module()
S {PPU[0x1000000] Thread (main_thread) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libresc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx
S {PPU[0x1000000] Thread (main_thread) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libpamf.sprx
S {PPU[0x1000000] Thread (main_thread) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsail.sprx
U {PPU[0x1000000] Thread (main_thread) [0x02a501c4]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
E {rsx::thread} RSX: OpenGL: initialization of glDepthBoundsEXT failed.
E {rsx::thread} RSX: OpenGL: initialization of glTextureBarrierNV failed.
S {rsx::thread} RSX: New program compiled successfully x15
E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed
U {PPU[0x1000000] Thread (main_thread) [0x00601830]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd000f640, option=*0x0, waitForEvent=0)
S HLE: XInput device 0 reconnected
S {PPU[0x1000000] Thread (main_thread) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libfiber.sprx
E {PPU[0x1000003] Thread (TrophyThread) [0x00601310]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x611a10, arg=*0x0, options=0x0)
U {PPU[0x1000000] Thread (main_thread) [0x02998d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x02973f0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x02973f0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
E {PPU[0x1000000] Thread (main_thread) [0x029694ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x029694ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x029694ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
S {SPU[0x2000000] Thread (AxaSoundCellSpursKernel0) [0x00818]} SPU: SPU Recompiler Runtime (ASMJIT) initialized...
E {PPU[0x1000000] Thread (main_thread) [0x029c8090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/KH2Image/kh2.cnf” [1]
E {PPU[0x1000000] Thread (main_thread) [0x0001632c]} 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x0001638c]} 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x0001632c]} 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x0001638c]} 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x0001632c]} 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000000] Thread (main_thread) [0x0001638c]} 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [3]
S {Audio Thread} XAudio 2.9 initialized
E {PPU[0x1000003] Thread (TrophyThread) [0x00601368]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0xd002fd24, count=*0xd002fd20)
E {PPU[0x1000000] Thread (main_thread) [0x0007bbcc]} 'sys_semaphore_get_value' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x100000a] Thread (dk::Thread::create) [0x0007bb98]} 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x100000f] Thread (Axa PPU Thread) [0x029cbfc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/BLUS31460//SaveData0” [1]
E {PPU[0x100000f] Thread (Axa PPU Thread) [0x00601448]} cellSaveData: Failed to open file C:/Users/mofacah/AppData/Local/Temp/Rar$EXa5332.48030/dev_hdd0/home/00000001/savedata/BLUS31460-BISLPM66675FM/
E {PPU[0x1000000] Thread (main_thread) [0x0007bbcc]} 'sys_semaphore_get_value' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x100000a] Thread (dk::Thread::create) [0x0007bb98]} 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x100000a] Thread (dk::Thread::create) [0x0001632c]} 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x100000a] Thread (dk::Thread::create) [0x0001638c]} 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x0007bbcc]} 'sys_semaphore_get_value' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x100000a] Thread (dk::Thread::create) [0x000162a0]} 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x100000a] Thread (dk::Thread::create) [0x000162a0]} 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000000] Thread (main_thread) [0x029c7ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS31460//SaveData0/BISLPM-66675FM-SYS/BISLPM-66675FM-SYS” [1]
U {PPU[0x1000019] Thread (_libsail-control) [0x02998d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x4
U {PPU[0x1000019] Thread (_libsail-control) [0x02973f0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000019] Thread (_libsail-control) [0x02973f0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
E {PPU[0x1000016] Thread (_sys_MixerChStripMain) [0x029694ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000016] Thread (_sys_MixerChStripMain) [0x029694ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000016] Thread (_sys_MixerChStripMain) [0x029694ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000018] Thread (_cellsurMixerMain) [0x00544c6c]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000018] Thread (_cellsurMixerMain) [0x00544c6c]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [2]
E {PPU[0x1000018] Thread (_cellsurMixerMain) [0x00544c6c]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [3]
S {PPU[0x1000019] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libmp4.sprx
S {PPU[0x1000019] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libapostsrc_mini.sprx
S {PPU[0x1000019] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libadec.sprx
S {PPU[0x1000019] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libm4aacdec.sprx
S {PPU[0x1000019] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libvpost.sprx
S {PPU[0x1000019] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libavcdec.sprx
U {PPU[0x1000019] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23017700, flags=0x0, pOpt=*0x0)
U {PPU[0x1000019] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23017600, flags=0x0, pOpt=*0x0)
U {PPU[0x1000019] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23017300, flags=0x0, pOpt=*0x0)
U {PPU[0x1000019] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23018900, flags=0x0, pOpt=*0x0)
U {PPU[0x1000019] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23018800, flags=0x0, pOpt=*0x0)
U {PPU[0x1000019] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23018200, flags=0x0, pOpt=*0x0)
U {PPU[0x1000019] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23016d00, flags=0x0, pOpt=*0x0)
E {PPU[0x1000017] Thread (_sys_mixerSurBusReq) [0x00542b9c]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000016] Thread (_sys_MixerChStripMain) [0x00548ad0]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000016] Thread (_sys_MixerChStripMain)} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x2640]
E {PPU[0x1000018] Thread (_cellsurMixerMain)} Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x330]
E {PPU[0x1000000] Thread (main_thread) [0x00543c70]} 'sys_event_port_disconnect' failed with 0x80010016 : CELL_ENOTCONN [1]
U {PPU[0x1000041] Thread (_libsail-control) [0x02998d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x4
U {PPU[0x1000041] Thread (_libsail-control) [0x02973f0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000041] Thread (_libsail-control) [0x02973f0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
E {PPU[0x100003e] Thread (_sys_MixerChStripMain) [0x029694ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x100003e] Thread (_sys_MixerChStripMain) [0x029694ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x100003e] Thread (_sys_MixerChStripMain) [0x029694ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000040] Thread (_cellsurMixerMain) [0x00544c6c]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000040] Thread (_cellsurMixerMain) [0x00544c6c]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [2]
E {PPU[0x1000040] Thread (_cellsurMixerMain) [0x00544c6c]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [3]
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x0B1E4B8F' in module 'cellMp4'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x15CCEA27' in module 'cellMp4'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x390BFF1F' in module 'cellMp4'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xC4E9C174' in module 'cellMp4'
S {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libmp4.sprx
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x24F4ECD3' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x24FA3789' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x35506005' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x7156446D' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x736513CA' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x752E10C4' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x827CB70E' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x8A6D4227' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x9AAA0039' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xA87B5742' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xB3226E6A' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xC4248C51' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xCAA48B00' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xCB3974E7' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xCF350A4C' in module 'cellApostSrcMini'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xF960FCA7' in module 'cellApostSrcMini'
S {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libapostsrc_mini.sprx
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellAdecDecodeAu' in module 'cellAdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellAdecStartSeq' in module 'cellAdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellAdecQueryAttr' in module 'cellAdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellAdecClose' in module 'cellAdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellAdecOpenEx' in module 'cellAdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellAdecGetPcm' in module 'cellAdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellAdecGetPcmItem' in module 'cellAdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellAdecOpen' in module 'cellAdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellAdecOpenExt' in module 'cellAdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellAdecEndSeq' in module 'cellAdec'
S {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libadec.sprx
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x431A1DCA' in module 'cellM4AacDec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked variable '0xAB61278D' in module 'cellM4AacDec'
S {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libm4aacdec.sprx
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellVpostClose' in module 'cellVpost'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellVpostOpenEx' in module 'cellVpost'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellVpostQueryAttr' in module 'cellVpost'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellVpostExec' in module 'cellVpost'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function 'cellVpostOpen' in module 'cellVpost'
S {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libvpost.sprx
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x00E2D84B' in module 'libavcdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x3A92F3DF' in module 'libavcdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x5267175E' in module 'libavcdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x765DE1B4' in module 'libavcdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0x9D523894' in module 'libavcdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xC68B81BF' in module 'libavcdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xD83259E8' in module 'libavcdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xDF6F03FC' in module 'libavcdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xE1134B5D' in module 'libavcdec'
E {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} LDR: Already linked function '0xF1A9AF6F' in module 'libavcdec'
S {PPU[0x1000041] Thread (_libsail-control) [0x029749ac]} sys_prx: Loaded module: /dev_flash/sys/external/libavcdec.sprx
U {PPU[0x1000041] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23076f00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000041] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23076e00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000041] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23076b00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000041] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23078100, flags=0x0, pOpt=*0x0)
U {PPU[0x1000041] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23078000, flags=0x0, pOpt=*0x0)
U {PPU[0x1000041] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23077a00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000041] Thread (_libsail-control) [0x02975038]} sys_prx TODO: _sys_prx_unload_module(id=0x23076500, flags=0x0, pOpt=*0x0)
E {PPU[0x100000a] Thread (dk::Thread::create) [0x0007bb98]} Stat: 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [x14932]
E {PPU[0x100000a] Thread (dk::Thread::create) [0x0007bb98]} Stat: 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [x1874]
E {PPU[0x100003e] Thread (_sys_MixerChStripMain) [0x00548bd4]} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x121552]
E {PPU[0x1000040] Thread (_cellsurMixerMain) [0x005450ac]} Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x15193]
E {PPU[0x1000000] Thread (main_thread)} Stat: 'sys_semaphore_post' failed with 0x80010005 : CELL_ESRCH [x41617]
E {PPU[0x1000000] Thread (main_thread)} Stat: 'sys_semaphore_get_value' failed with 0x80010005 : CELL_ESRCH [x16386]
E {PPU[0x1000000] Thread (main_thread)} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x12]
E {PPU[0x1000000] Thread (main_thread)} Stat: 'sys_semaphore_wait' failed with 0x80010005 : CELL_ESRCH [x41617]

**Comment by Konata400** [comment]
Your GPU is Intel® UHD Graphics 620? retry reinstalling driver, but i don't recommend this gpu for play.

**Comment by Laughenman** [comment]
After reinstalling and messing with the settings again, I finally got past Day 1.
Day 1 fix
CPU
SPU and PPU fastest
Load liblv2 only
Preferred SPU threads- auto
Enable Thread Scheduler
Enable SPU loop detection
GPU OpenGL no addition settings
Frame limit off
Anisotropic filter Auto

Had to mess with it again to get to day 3, the solution was disabling thread scheduler.
 
I really appreciate the answer, I never would of thought about my driver on my own. Thank you very much

**Comment by AniLeo** [comment]
Closing as this is likely not an issue anymore, Thread Scheduler is not enabled for Intel CPUs anymore, only for Ryzen CPUs. If this is still an issue on the latest master, submit a new issue following the guidelines.
