### ISSUE TITLE
Tales of Xillia (BLES01815) graphics too dark (postprocessing to 70% brightness globally)

### ISSUE THREAD

**Issue by PeterTh** [RPCS3/rpcs3#4533]
In Tales of Xillia, across the **entire game**, the screen is at 70% of the brightness level it should be. This happens regardless of settings and graphics backend (i.e. OpenGL or Vulkan).

It's nice for debugging in that it already happens on the very first logo screen (which has just 3 draw calls in total), here's a comparison:
RPCS3
![rpcs3](https://user-images.githubusercontent.com/1033475/39860400-846e4e2a-543d-11e8-97f4-78302be3b98c.png)
Correct
![correct](https://user-images.githubusercontent.com/1033475/39860406-8b29f0e8-543d-11e8-896f-b563e16ea5b6.png)

The same behaviour continues throughout the game, including videos, menus and 3D rendered content.

I've looked into it using Renderdoc ([trace file here](https://github.com/RPCS3/rpcs3/files/1990941/xillia_brightness.zip), using OpenGL for better portability), and there is a draw call (EID 92) drawing a single fullscreen triangle which is responsible.

It's really just this:
```
void fs_main(inout vec4 r0, inout vec4 r1, inout vec4 r2, inout vec4 r3, inout vec4 r4)
{
	r0 = TEX2D(0, tex0, tc0.xy);
	r1 = fc32;
	//FENCB
	r0 = (r0 * fc80 + r1);
}
```
With fc32 being set to 0/0/0/0 and fc80 being set to 0.7/0.7/0.7/1.0. I've written a hack to work around this specific scenario, which "fixes" it as expected.

Sadly I don't know enough about RPCS3 to figure out where and why fc32/fc80 in the fragment constant buffer are set to these values, or what, if anything, FENCB has to do with it.

This issue is reproducible on any recent (and probably also older) commit, e.g. 98b715d8c89f3c57b5e0e9f0a541a53d13e96617.

**Comment by marcussacana** [comment]
If you enable the libsysutils manually will shows correct.... welll... in the lastest version if you enable manually you got a black screen (vulkan) or a random color screen (open gl)...
i commented before about this here: https://forums.rpcs3.net/thread-177361-page-2.html

**Comment by PeterTh** [comment]
That's very interesting, since it seems that most likely it is not really a graphics issue at all. I'll have to experiment and see what the value passed to that shader is in that case.

**Comment by marcussacana** [comment]
With this build works: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7051/artifacts

**Comment by dravenlh4** [comment]
Hey, so was this ever fixed?

**Comment by HerrHulaHoop** [comment]
Not yet

![rpcs3_2019-06-20_17-28-29](https://user-images.githubusercontent.com/31934788/59847713-e646b000-9380-11e9-93f5-12a013ffea6c.png)

**Comment by shizukachan** [comment]
I don't think this is actually a bug in RPCS3. Whites are gray on a real PS3.

**Comment by marcussacana** [comment]
wtfff really?

**Comment by HerrHulaHoop** [comment]
Hmm @shizukachan is right. Here's [video footage](https://youtu.be/0OG_f86hFPg?t=10) I found on YouTube. Seems to indeed be present even on the real hardware.

**Comment by Illynir** [comment]
Indeed, it is not a bug but how the game is made. I think it can be closed. They probably wanted to soften the image and give the game a genre. It's a bit of a failure to be honest.
