### ISSUE TITLE
Dante's Inferno BLUS30405 - Crashes at the first boss fight

### ISSUE THREAD

**Issue by UroshUchiha** [RPCS3/rpcs3#4534]
RPCS3 version: v0.0.5-6718 (737db900) Alpha [2018-05-09] 

To reproduce the issue, just start the game, kill the first few mobs and watch the "Grim Reaper" cutscene. When the battle with him starts the emulator crashes either instantly or a couple of seconds later.

System specs:
OS: Windows 10
CPU: i7-8700K
RAM: 16GB 3200Mhz
GPU: Asus Rog Strix 1080Ti

![Screenshot](https://user-images.githubusercontent.com/36758864/39882104-33330f28-5483-11e8-985a-29f40a00a2f0.png)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1992483/RPCS3.zip)

**Comment by fede7911** [comment]
i have the same problem idk how to fix it

**Comment by UroshUchiha** [comment]
Now the game won't even boot since build 6784 I believe

**Comment by Web1017** [comment]
Here is a temporary fix to pass through the First Boss without Crashing. It only seemed to work with ### **OpenGL**, but with Vulkan it still crashes.

1 - Go to X:\rpcs3-v0.0.5-xxxx-xxxxxxxxx_win64\GuiConfigs"
2 - Open currentsettings.ini and find this line "showDebugTab=false"
3 - Change false to true.
4 - Open RPCS3 Options a new tab will appear called "Debug"
5 - Press on Debug you will find an option there called "Disable ZCull Occlusion Queries" check the box 
-------------------------------------------------------------------------------------------------
After you get to the first Save using OpenGL - Save the game and Switch to Vulkan and continue playing.

![capture22](https://user-images.githubusercontent.com/19266952/42240839-a46fc1c2-7ed6-11e8-880b-ef0ade337bef.PNG)

**Comment by UroshUchiha** [comment]
I finished that part by simply switching to OpenGL. After the first save I went back to Vulkan.
By the time I completely finished the whole game I had around four to five more random crashes, but nothing that had me go back to OpenGL, I simply tried again on Vulkan and I got through that area.

**Comment by ivicamarkovic** [comment]
If I switch to OpenGL, I am missing most of the graphics. I only see enemies. In Vulkan the same segfault error as in the first post.

**Comment by Web1017** [comment]
It is possible the version of the RPCS3 Version you downloaded may be breaking the graphics or the selected options you had. Can you post some pictures of the options and submit the log? In order to find the problem that you are having. Because I when I tried it. I didnt have such issues

**Comment by ivicamarkovic** [comment]
In spu precise branch I have correct graphics in Ogl. Broken graphics were in several master revisions, 7092 at least. Here is log from master.

[Dante.zip](https://github.com/RPCS3/rpcs3/files/2197410/Dante.zip)

**Comment by AniLeo** [comment]
Not an issue on current builds

I recorded a video playing past the first boss fight
https://www.youtube.com/watch?v=-gx2AKgUAGc

Closing as fixed
