### ISSUE TITLE
Journey NPEA00288 

### ISSUE THREAD

**Issue by UroshUchiha** [RPCS3/rpcs3#4535]
RPCS3 version: v0.0.5-6718 (737db90) Alpha [2018-05-09]

The log section is constantly being filled with these messages. Is there any way to stop it?

![Screenshot](https://user-images.githubusercontent.com/36758864/39882644-a3e7ff48-5484-11e8-8483-8ef7cb6a4ed5.png)

System specs:
OS: Windows 10
CPU: i7-8700K
RAM: 16GB 3200Mhz
GPU: Asus Rog Strix 1080Ti

**Comment by Illynir** [comment]
And ? Close the log, it's not a problem.

It's normal.

**Comment by UroshUchiha** [comment]
The game is very laggy and slow. So I thought that text might be a reason for the issue. If it's not truly an issue worth being here, close it.

**Comment by elad335** [comment]
:thisisfine:, close it, its not a real issue
