### ISSUE TITLE
Regression in FIFA street 3 [BLES00188] after v0.0.5-6718

### ISSUE THREAD

**Issue by Josivan88** [RPCS3/rpcs3#4536]
Game works fine before 6718, after the frames oscillate to 3-20fps in menus and can't go in game even more. before the game was almost playable with 300+ fps in menus.
Default settings.
Cleared LLVM Cache and Shader cache does nothing.
![fifa street 3 problem](https://user-images.githubusercontent.com/36341425/39887170-ec5d0808-5467-11e8-82fa-c20ab7f5bba8.jpg)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1992863/RPCS3.log.gz)

**Comment by Josivan88** [comment]
Fifa Street 3 still slow and crash in 6737

**Comment by Josivan88** [comment]
Fifa Street 3 crash RPCS3 in 0.0.5-7138
intro - > nothing

**Comment by Josivan88** [comment]
Fifa Street 3 crash RPCS3 in 0.0.5-7570
SPU interrupts not implemented...

**Comment by elad335** [comment]
duplicate of #5591

**Comment by AniLeo** [comment]
Closing as duplicate of #5591
