### ISSUE TITLE
Borderlands crashing after ASMJIT improvements

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#4538]
Hello, after the series of commits ending with commit 737db90058beb93d83d12ea94c405476ee594bfc, per [this](https://github.com/RPCS3/rpcs3/pull/4504#issuecomment-387916428) PR, Borderlands now freezes at startup, with the following logged:

F {PPU[0x1000000] Thread (main_thread) [0x01001640]} St13runtime_error thrown: Memory mapping failed - blame Windows (addr=0x25f80000, size=0x20000, flags=0x23)

Tested with Linux 4.15 kernel (note message to blame Windows?), with i7-7820HK and GTX 1070.

**Comment by Hirato** [comment]
I'm not sure what changed, but drakengard 3 seems to be fixed in master now, I suspect a46ef4f29ae3857747b2708d7d24a895701a6d50 did the trick.

Is Borderlands fixed too?

**Comment by Deminating** [comment]
Borderlands seems to work on current master fine now.
<img width="427" alt="rpcs3_2018-05-14_02-38-31" src="https://user-images.githubusercontent.com/37973506/39997935-34d27130-5720-11e8-8786-1664ab4096c4.png">
Using Windows 10

**Comment by Shoegzer** [comment]
Yes it's fine now, so I'll close this.  Bioshock crashes after the "All things flow into the city" intro with these commits too, but that should probably be a different writeup.
