### ISSUE TITLE
Dead Island Ripptile lack of sensitivity of the keyboard-joystick

### ISSUE THREAD

**Issue by PlayerWind** [RPCS3/rpcs3#4544]
Rpcs3 Bulid: v0.0.5-94fa6b239 No Master

At the time of making adjustments controls do not work

Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1997368/RPCS3.log)

Screenshot:
![screenshot2](https://user-images.githubusercontent.com/38998444/39954845-7dbb424e-559c-11e8-87c4-213822dc407d.png)

System :Windows 7

**Comment by AniLeo** [comment]
Needs proper test done on latest master, that's not even a master build

**Comment by elad335** [comment]
Fixed by #5311
