### ISSUE TITLE
#4504 regressions (SPU improvements) 

### ISSUE THREAD

**Issue by Renusek** [RPCS3/rpcs3#4548]
*Tales from Space: About a Blob (Playable Demo)* **NPEB00388** shows mostly black screen now (#4504) - on previous master build (#4526) it was still working.

### Scenario 1
![6697 1](https://user-images.githubusercontent.com/4978744/39958001-6c485ea6-55fc-11e8-8d0b-a57a714fc91c.jpg)
![6718 1](https://user-images.githubusercontent.com/4978744/39957989-49ac6eb4-55fc-11e8-95ee-87cbd4b3a45b.png)

### Scenario 2
![6697 2](https://user-images.githubusercontent.com/4978744/39957991-4f911cf8-55fc-11e8-9d99-46476835f2f1.jpg)
![6718 2](https://user-images.githubusercontent.com/4978744/39957993-517f5ee4-55fc-11e8-9839-3f0cf6b2d4ad.png)

### Scenario 3
![6697 3](https://user-images.githubusercontent.com/4978744/39957995-56db8ab6-55fc-11e8-9cf9-77f49cef1380.jpg)
![6718 3](https://user-images.githubusercontent.com/4978744/39957996-57e98ac0-55fc-11e8-921a-27e13cecfb93.png)

#### Log files
[4526 RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1997655/4526.RPCS3.log.gz) - working
[4504 RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1997656/4504.RPCS3.log.gz) - regressed
![unknown](https://user-images.githubusercontent.com/4978744/39958037-23339126-55fd-11e8-85a4-b2dd5a74b00c.png)

Others are welcome to post any other regressions.

**Comment by Renusek** [comment]
fixed in #4553, can be closed

**Comment by NotUnknownbrackets** [comment]
🍆
