### ISSUE TITLE
SPU LLVM seems to be broken

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4549]
I don't know exactly, was SPU LLVM fully implemented in last Master or no, and I'm not this level coder, but now it looks totally buggy. First, none of my games weren't loaded without MEM access violation crash when it's enabled. Second, it generates very strange files during load, which seems to be not able to read itself. New files found in folder kind of "ppu-3ajNAd4t5EKKpYZFq9SkNuZP4pfP-EBOOT.BIN". Why "ppu" if this is an SPU cache, and what does mean this symbol sequence? The files inside look like this to me, and I'm not sure it's normal: 
![cropimage](https://user-images.githubusercontent.com/1223276/39958404-e0816066-55f1-11e8-829a-dfb12a6335c4.png)

If I'm wrong on something, you can explain it or just close issue..

**Comment by Relsig** [comment]
Afaik spu llvm hasn't been fully implemented and is most likely horribly buggy. From what I've gathered I don't think it's even in a testing state currently.

In any case SPU Asmjit is still the preferred option at the moment.
