### ISSUE TITLE
llvm cannot pull

### ISSUE THREAD

**Issue by yxmline** [RPCS3/rpcs3#4551]
git message
error: Server does not allow request for unadvertised object 6154c0dcaf1a5a105afffa106ea3298b3020dffb
Fetched in submodule path 'llvm', but it did not contain 6154c0dcaf1a5a105afffa106ea3298b3020dffb. Direct fetching of that commit failed.
error: Server does not allow request for unadvertised object 6154c0dcaf1a5a105afffa106ea3298b3020dffb
Fetched in submodule path 'llvm', but it did not contain 6154c0dcaf1a5a105afffa106ea3298b3020dffb. Direct fetching of that commit failed.

**Comment by scribam** [comment]
Fixed by #4553 
Update your master branch then the llvm submodule, it should work

**Comment by scribam** [comment]
@yxmline Feel free to close this issue if resolved

**Comment by yxmline** [comment]
this issue resolved
