### ISSUE TITLE
Regression: Verification failed (e=0xb7) on PR #4554

### ISSUE THREAD

**Issue by L3X4RS** [RPCS3/rpcs3#4555]
I did a clean install to see and the game opens, but after being closed, it does not open again in new build 
S LDR: Boot successful.
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Recompiler Runtime (ASMJIT) initialized...
F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: Verification failed (e=0xb7) (0): 
(in file Emu\Cell\SPUASMJITRecompiler.cpp:2753)

**Comment by isshininu** [comment]
Getting the same error with Demon's Souls.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1998125/RPCS3.log.gz)

**Comment by Rpcs3tester** [comment]
i can confirm 

Silent Hill Downpour - [BLUS30565] 

F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: Verification failed (e=0xb7) (0): 
(in file Emu\Cell\SPUASMJITRecompiler.cpp:2753)

in 0.0.5-6718 were works perfectly .

**Comment by Megamouse** [comment]
can you retry?

**Comment by Parthorisian** [comment]
Demon soulz[blus30443] still stuck before going to menu
https://i.imgur.com/K3FTtJG.jpg
[DemonsoulzStuck_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2003164/DemonsoulzStuck_RPCS3.zip)
SH: Downpour worki for now https://i.imgur.com/BVieZYE.jpg
[downpourWorkinRPCS3.zip](https://github.com/RPCS3/rpcs3/files/2003198/downpourWorkinRPCS3.zip)

**Comment by uvraj** [comment]
F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: Verification failed (e=0xb7) (0): 
(in file Emu\Cell\SPUASMJITRecompiler.cpp:2753)

Same error in midnight club los angeles.

**Comment by AniLeo** [comment]
Send logs and system information - tested with latest master build.

**Comment by isshininu** [comment]
Silent Hill Downpour works
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2019069/RPCS3.log.gz)
Demon's Souls is not
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2019071/RPCS3.log.gz)

**Comment by Parthorisian** [comment]
**Demon soulz**[blus30443] runs but hang(after killing octopushead) https://i.imgur.com/fprN2jg.png +after exploding miracle https://i.imgur.com/jKdNNbs.jpg May be physics bug
Log [DemonSoulz_hangRPCS3.zip](https://github.com/RPCS3/rpcs3/files/2018931/DemonSoulz_hangRPCS3.zip)

**Comment by Parthorisian** [comment]
Demon soulz[blus30443] loads menu but unfortunately throws this exception for now
F {PPU[0x100002f] Thread (ChrInsManThread::Thread) [0x009e1e70]} class std::runtime_error thrown: Verification failed (e=0x57): 
(in file Emu\Cell\lv2\sys_cond.cpp:279)
Log [DemonSouls_throwRPCS3.zip](https://github.com/RPCS3/rpcs3/files/2020868/DemonSouls_throwRPCS3.zip)

**Comment by AniLeo** [comment]
Closing as it was already fixed
