### ISSUE TITLE
Some games (ex: persona 5) cannot boot after #4553

### ISSUE THREAD

**Issue by tanpro260196** [RPCS3/rpcs3#4556]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1998063/RPCS3.log.gz)
Nothing show up at all whatsoever.
The error show up on the log is:
```S LDR: Boot successful.
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Recompiler Runtime (ASMJIT) initialized...
F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: Verification failed (e=0xb7) (0): 
(in file Emu\Cell\SPUASMJITRecompiler.cpp:2753)```

**Comment by MrBlue9** [comment]
Getting the exact same error on Tom Clancy's Splinter Cell HD. Was running just fine when I played yesterday. Not working on the latest build. 
Game boots up just fine when changing SPU to Interpreter but has really bad performance then.

**Comment by johnneijzen** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1998367/RPCS3.log.gz)
yep same error also persona 5

**Comment by Nekotekina** [comment]
Will be fixed soon

**Comment by ruipgpinheiro** [comment]
FYI, building without be5c18c seems to workaround this issue.

**Comment by raulpetru** [comment]
Temporary way to boot: right click on the game from rpcs3>Open Config Folder> remove PPU folder then launch the game. You will have to this every time until the issue is fixed.

**Comment by Megamouse** [comment]
please rename this issue to be more descriptive and general in order to prevent other people from constantly opening new ones.

**Comment by jaaanko** [comment]
Persona 5 (ASMJIT) now boots after #4565

**Comment by johnneijzen** [comment]
Yep Persona 5 working with latest master build

**Comment by tanpro260196** [comment]
Yep. It's working now.

**Comment by blueobelix1** [comment]
After all these years Prince of Persia 2008 Epilogue its still not working I get
E {PPU[0x1000000] Thread (main_thread) [0x00e13518]} SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x00e13628]} SYS: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x016107b0, LR:0x000fa6c8]} cellGame: cellHddGameCheck(version=0, dirName=“NPUB30424”, errDialog=1, funcStat=*0x133a890, container=1056964608)
E {PPU[0x1000000] Thread (main_thread) [0x000b50f8]} SYS: 'sys_fs_open' failed with 0x80010012 : CELL_EISDIR, “/dev_hdd0/game/NPUB30424/USRDIR/” [1]
F {PPU[0x1000000] Thread (main_thread) [0x00130e7c]} VM: Access violation reading location 0x288 (unmapped memory) [type=u32]
