### ISSUE TITLE
RPCS3 fails to launch due to Qt issue

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#4563]
After commit a39384cadda5244fe64e40bbae750c26d101463c, RPCS3 no longer starts.  Starting from commandline, the following is returned:

This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".  Reinstalling the application may fix this problem.

Using Linux 4.15 x64 with Mint 18.3 along with Qt 5.10 as required:

$ qmake --version
QMake version 3.1
Using Qt version 5.10.0 in /opt/qt510/lib

Note however that by default, Mint uses Qt 5.5.1.  I have to run the following command before compiling to use Qt 5.10:

$ source /opt/qt510/bin/qt510-env.sh

**Comment by Megamouse** [comment]
#4562

**Comment by Megamouse** [comment]
Please retest with master and close if fixed

**Comment by Shoegzer** [comment]
Fixed, and closing.  Thanks again.

**Comment by ezoltbn** [comment]
This will fix your issue:

sudo apt-get install libxcb-xinerama0
