### ISSUE TITLE
build issues with xxHash

### ISSUE THREAD

**Issue by Hirato** [RPCS3/rpcs3#4573]
Hello,

I've basically got 3 problems with the recently introduced dependency of xxHash.
1. There's no way to tell RPCS3 to not build xxHash and use a system version
1. The compiled version is installed to `$PREFIX/lib64` this bizarrely introduces conflicts with Arch linux's `filesystem` package.
Libraries should be installed to `$PREFIX/lib`, however as this is a 3rd party library RPCS3 is building for its own use, it should ideally go to `$PREFIX/lib/rpcs3` instead.
1. the `xxhsum` utility is always built - `BUILD_XXHSUM` should probably default to off.

As an additional observation, I also notice that the built `rpcs3` binary (via ldd) does not link dynamically to `libxxhash` or anything resembling it, which seems to suggest there is no need for `make install` to install any of the xxhash files.

**Comment by sl1pkn07** [comment]
see my comment here https://github.com/RPCS3/rpcs3/pull/4510/files

**Comment by sl1pkn07** [comment]
also, pugixml, vulkan/glslang (this can be handle with https://github.com/RPCS3/rpcs3/pull/4497 (?)), hidapi and asmjit can be used system versions instead use blundled versions

**Comment by Hirato** [comment]
I think it is using the system yaml-cpp.
I'm less bothered about the other dependencies because they're not causing weird conflicts with system files - LLVM aside, but there's a `LLVM_DIR` option to fix that.

**Comment by sl1pkn07** [comment]
yes, used system yaml-cpp if add `-DCMAKE_EXE_LINKER_FLAGS='-ldl -lyaml-cpp' `, but this can be done inside cmake instead of set external LDFLAG
