### ISSUE TITLE
Error killzone 2 trying to load campaign on new SPU

### ISSUE THREAD

**Issue by MrJordanL** [RPCS3/rpcs3#4586]
The other spus get the standard mem violation error. but on the new llvm the error is  {SPU[0x2000005] Thread (LowPriorityCellSpursKernel0) [0x0a9b0]} class std::runtime_error thrown: Unknown STOP code: 0x3fff (Out_MBox is empty)

However skimirish mode now has a mem violation access error but on the other SPU decoders it does not.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2004235/RPCS3.log)

**Comment by AniLeo** [comment]
You're using a pirated copy. 

## Do NOT file issues if you're running pirated software.
