### ISSUE TITLE
Loading a world in Minecraft: PS3 Edition stuck on Compiling Shaders

### ISSUE THREAD

**Issue by Mario3264** [RPCS3/rpcs3#4587]
There doesn't seem to be anything happening in the log, the last lines of code are:

`S {rsx::thread} RSX: New program compiled successfully x2`

Details about my computer are the same as my last issue. The log was too big so I tried reproducing but it didn't do it again.

This image below could help (it is resized so it isn't too big):
![image](https://user-images.githubusercontent.com/16366524/40060805-4ca3e270-580c-11e8-82a9-d56b738e5fa7.png)

**Comment by Mario3264** [comment]
After a while, it came up with an error after me trying to reproduce: 
![image](https://user-images.githubusercontent.com/16366524/40087171-5130aaae-5856-11e8-966c-2a2eced3069d.png)

**Comment by Mario3264** [comment]
Installed 0.0.5-6745 and the issue persisted.

**Comment by Mario3264** [comment]
The errors seem to be the same as issue #3627.

**Comment by geniiii** [comment]
have the same problem, disable gpu texture scaling; for some reason it.. fixes this? yeah this is an odd one

**Comment by Mario3264** [comment]
Yes, but causes the GUI to be really messed up:
![image](https://user-images.githubusercontent.com/16366524/40623724-3398a04e-625d-11e8-886e-e7530e80c4c2.png)

**Comment by Mario3264** [comment]
The latest build seems to give me a missing dll error, about vulkan-1.dll

**Comment by Mario3264** [comment]
I think I tried this build because of the issue above, thinking that it could fix the problem.

**Comment by Mario3264** [comment]
Installed VulkanRT drivers and it works successfully.
