### ISSUE TITLE
Dante inferno

### ISSUE THREAD

**Issue by fede7911** [RPCS3/rpcs3#4590]
i have a issue with this game... so it goes 60 fps all the time but when dante gets stab and starts the fight versus the first boss the game crashes with this error https://gyazo.com/fb81f72ad246fd41fefbb56d42018bfa 
i have a  gtx 1060 6gb
8gb ram 
i7 4790

**Comment by legend800** [comment]
You could have just done a search and seen this issue is already logged.
https://github.com/RPCS3/rpcs3/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+dante+inferno 

Please following the submission instructions next time you file something.
