### ISSUE TITLE
God of War III #2339

### ISSUE THREAD

**Issue by barashmecha** [RPCS3/rpcs3#4595]

**Comment by AniLeo** [comment]
Don't spam our issue tracker.
If you have no idea what Git is, don't use it to spam other people's projects. This is a development platform.
If you want to learn, make your own repositories and do whatever you want in them.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
