### ISSUE TITLE
Demon's Souls sound regression - Garbled Sound in Videos and Menu

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4597]
I noticed that videos and menu of this game now have really garbled sound. Not like before.
In-game sound in this and other games is still good, though.
Build used is rpcs3-v0.0.5-6755-25324834

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2011191/RPCS3.log.gz)
https://youtu.be/Y1CuYuvb0Ww

**Comment by isshininu** [comment]
Happens on Windows 8.1.
Not happen on Windows 10.

**Comment by isshininu** [comment]
While this issue still remained on older versions of Windows for me, I guess it can be closed since RPCS3 team efforts are mainly targeted W10 as a main Windows version now (or, maybe, I am wrong?)
lol

**Comment by AniLeo** [comment]
Nope, it's meant to work on all supported Windows distros equally. Win7, 8 and 8.1 support will remain.

**Comment by isshininu** [comment]
While RPCS3 should run equally on all systems as you say, but in reality behavior differs between versions.
But actually there is one more reason why I dont want to see this issue be opened by me - simply because my machine specs are not great enough to run Demon's Souls on constant 30 FPS / 60 FPS with fps unlock patch.
I suspect some of my bug reports were caused by hitting the limits of CPU load, that's why none reported those issue.
