### ISSUE TITLE
Beowulf not works in new build

### ISSUE THREAD

**Issue by L3X4RS** [RPCS3/rpcs3#4598]
[Beowulf] BLUS30091 

I was playing on the weekend and it was working perfectly on build 6718 (I think it was) and now on the new build, it does not work anymore, black screen, background sound and the emulator crashes with fatal error
I know this game had been regressed for a long time, but it worked again in the build of the weekend
Could this be fixed? I was finishing the game

[https://cdn.discordapp.com/attachments/277227681836302338/446542345224060928/unknown.png](url)

[https://cdn.discordapp.com/attachments/277227681836302338/446543538746818560/unknown.png](url)

**Comment by AniLeo** [comment]
Closing as there's no proper regression report.

Please file a proper regression report if the issue persists. If it regressed on a PR that has a regression issue opened for it, post there, otherwise open a new issue.

Remember, you must indicate exactly what PR regressed it on a regression report.
