### ISSUE TITLE
graphick god of war3

### ISSUE THREAD

**Issue by kurosh10000** [RPCS3/rpcs3#4599]
please fix the black graund in the god of war 3

**Comment by kurosh10000** [comment]
fix the tex too.tanks for hard work

**Comment by Asinin3** [comment]
Don't spam the issue tracker with nonsense, this is not what it is for. By making an issue with no relevant information all you're doing is being a hindrance to the project. Please close this issue by clicking the big red button below.

**Comment by AniLeo** [comment]
Is this some kind of meme? I'm not following
