### ISSUE TITLE
Got this error when trying to launch BLJM61048

### ISSUE THREAD

**Issue by ItsukaNakou** [RPCS3/rpcs3#4602]
What should I do?
![rpcs3_ fatal error 17_05_2018 16_18_12](https://user-images.githubusercontent.com/39378481/40184995-df26f858-59f1-11e8-8434-9d04faf8d9a7.png)

**Comment by ItsukaNakou** [comment]
Why did you do this!!??

**Comment by AniLeo** [comment]
Why are you spamming our tracker?
Did you even bother to read the Issue Tracker Guidelines on the textbox before you erased it to write?
