### ISSUE TITLE
Poor Vulkan performance on AMD RX Vega GPU

### ISSUE THREAD

**Issue by Yukonz** [RPCS3/rpcs3#4612]
I have noticed, that Vulkan renderer is significantly slower then OpenGL on my system.
After many attempts to find reason of this problem, I replace my RX Vega 64 videocard to GTX 970 and get 30-50% FPS improvement for Vulkan.

CPU: AMD Ryzen 5 1600X
RPCS3 build 6784 (trying 6675, 6541 - no difference)
AMD Driver 18.4.1 (18.2.1 - no difference)
Windows 10 ver.1803 (trying 1709 - no difference)

A few tested games with 6784 buld:
Persona 5 [BLUS31604]: 
RX Vega Vulkan   - 23 FPS
<a href="http://piccy.info/view3/12343431/e29010bf761a3cfdbf40c02cf10f0a06/" target="_blank"><img src="http://i.piccy.info/i9/cf8d1247a7c6bf2c8a59d67d6bcc9d3e/1526735098/10681/1245362/rx_vega_p5_vulkan_240.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-05-19-13-04/i9-12343431/240x144-r" target="_blank"><img src="http://i.piccy.info/a3/2018-05-19-13-04/i9-12343431/240x144-r/i.gif" alt="" border="0" /></a>
RX Vega OpenGL - 27 FPS
<a href="http://piccy.info/view3/12343430/6ff0e5a091a946cc4c2d0c56f81fa892/" target="_blank"><img src="http://i.piccy.info/i9/f99c4a7de84578b250fd656af08857bc/1526735069/10579/1245362/rx_vega_p5_opengl_240.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-05-19-13-04/i9-12343430/240x144-r" target="_blank"><img src="http://i.piccy.info/a3/2018-05-19-13-04/i9-12343430/240x144-r/i.gif" alt="" border="0" /></a>
GTX 970 Vulkan   - 28 FPS  
<a href="http://piccy.info/view3/12343432/02db9ea7dbad903292ab726db811e6af/" target="_blank"><img src="http://i.piccy.info/i9/4bbf70544ecf0679abf405d546350065/1526735105/10577/1245362/GTX970_p5_vulkan_240.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-05-19-13-05/i9-12343432/240x144-r" target="_blank"><img src="http://i.piccy.info/a3/2018-05-19-13-05/i9-12343432/240x144-r/i.gif" alt="" border="0" /></a>

Dead Space [BLES00308]
RX Vega Vulkan   - 16 FPS
<a href="http://piccy.info/view3/12343434/61e533a53edac0baa6edf50d5601c1e4/" target="_blank"><img src="http://i.piccy.info/i9/911452dbb5b583780e58fbbe10047801/1526735136/5374/1245362/rx_vega_dead_space_vulkan_240.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-05-19-13-05/i9-12343434/240x144-r" target="_blank"><img src="http://i.piccy.info/a3/2018-05-19-13-05/i9-12343434/240x144-r/i.gif" alt="" border="0" /></a>
RX Vega OpenGL - 20 FPS
<a href="http://piccy.info/view3/12343433/f0c9effecd676bc866de137581e981cf/" target="_blank"><img src="http://i.piccy.info/i9/31d61cebd26c987e0dd1227819c4e450/1526735131/5502/1245362/rx_vega_dead_space_opengl_240.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-05-19-13-05/i9-12343433/240x144-r" target="_blank"><img src="http://i.piccy.info/a3/2018-05-19-13-05/i9-12343433/240x144-r/i.gif" alt="" border="0" /></a>
GTX 970 Vulkan   - 28 FPS
<a href="http://piccy.info/view3/12343493/0cae8b2da39691e4f837288d27af14ce/" target="_blank"><img src="http://i.piccy.info/i9/89422b189c277758f36430023e048702/1526736238/5374/1245362/GTX970_dead_space_vulkan_240.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-05-19-13-23/i9-12343493/240x141-r" target="_blank"><img src="http://i.piccy.info/a3/2018-05-19-13-23/i9-12343493/240x141-r/i.gif" alt="" border="0" /></a>

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/wiki/Graphics-Driver-Issues
There are several driver bugs that require workarounds for AMD hardware to work without crashing. This does add a load on the CPU. You can experiment with a config file option to disable one workaround (enable Force Primitive Restart) but this will likely just kill the renderer. For now we have to wait for the issues to be fixed by AMD. They are reported for some time now but still no reply.
