### ISSUE TITLE
Regression from "Asmfixes" #4580

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#4615]
**Dante's Inferno** Regressed from Ingame to Nothing after #4580 was merged. After the asmfixup PR It no longer gives the event mask 0x420 fatal error but is still not booting properly. Interpreters do not help.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2019630/RPCS3.log.gz)

**Tales of Vesperia** Performance regression see: #4606 

> At the sleeping dog scene in the beginning of the game:
>    6748 + timer resolution = 0.5 --- 45 fps
>   6750 + timer resolution = 0.5 --- 35 fps
>    6755 + timer resolution = 0.5 --- 35 fps
>    6784 + timer resolution = 0.5 --- 35 fps (latest build as of today, 5/17/18)
>Builds 6750+ also freeze from time to time.
>Windows 10, update 1803
>Intel i7-8700
>Nvidia 1070ti

**Red Dead Redemption** Regressed from Ingame to Intro, now freezes on the first logo screen on every boot.

**Comment by Xcedf** [comment]
Same commit also regresses RDR, MGS3 HD, Killzone 2, Metal Gear Rising and maybe others

**Comment by Crimsom13** [comment]
Earths defense force 2025 crashes on load into game was very playable before, and resistance 2 is back to crashing at load.

**Comment by Xcedf** [comment]
The others fixed as well

**Comment by AniLeo** [comment]
Regressions fixed, closing the issue.

Ask for reopening if there's any regression **from #4580** that remains.

**Comment by Asinin3** [comment]
JoJo All-Star Battle regressed to Loadable after the Asmfixes PR, as of #4622 it now displays intro scenes again but then gets stuck on a black screen before it can reach the title screen. This title screen can be reached without issue before asmfixes merged. Re-Open please.

Didn't see anything interesting in log but here it is: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2022341/RPCS3.log.gz)

**Comment by jbeich** [comment]
On FreeBSD, Intel i7-6700K, Intel HD530 (OpenGL) as of c09c79263658 I still see the following regressions:
- Aquapazza **loses sound** after video intro
- Bomberman Ultra **hangs** in-game, shortly after a map has loaded, music still playing
- Persona 4 Arena Ultimax **hangs** after video intro
- Persona 5 **hangs** during game loading screen

@myfreeweb, do you also see similar hangs after 367f039523fb i.e., since freebsd/freebsd-ports@8a79a729c6ce?

**Comment by raveskirza** [comment]
@jbelch it may be doe to Kd's RSX fixes, Soul Calibur IV hanged after the recent RSX fixes. Chec issue #4651

**Comment by myfreeweb** [comment]
@jbeich I don't have these games & I'm not testing very actively right now. Waiting on #4122. Just got 0.0.5-382 from pkg... no regressions in that game, still just that graphics bug :D

**Comment by Asinin3** [comment]
@jbeich Persona 4 Arena hanging after intro video is a known and old issue you just need to move/rename/delete this: \USRDIR\data\movie\P4U_001.pam

**Comment by jbeich** [comment]
@Asinine, thanks but doesn't help: still hangs. fd525ae1cf83 works fine. 367f039523fb6 up to c09c79263658 hang.

Also by intro I meant music video introducing characters that shows before title screen, shortly after the game has loaded. Moving P4U_001.pam doesn't seem to affect it.

**Comment by jbeich** [comment]
@asinine, US version was uses \USRDIR\data\movieeng\. After moving the whole direcotry the game does manage to reach title screen but **loses sound** (like Aquapazza) then **hangs** shortly after.

**Comment by jbeich** [comment]
@raveskirza, no easy to notice changes in the affected games from reverting to fd525ae1cf83.

**Comment by Asinin3** [comment]
Not sure when, but JoJo's All-Star Battle is fixed now 
![image](https://user-images.githubusercontent.com/15137035/40536615-50ded596-5ffc-11e8-8d21-0c21f4c06f96.png)

**Comment by jbeich** [comment]
#4705 (7397b010e2a8 in particular) appears to fix everything but Persona 5 for me.

**Comment by jbeich** [comment]
Persona 5 hangs even if downgraded to 72574b11ffe1 with 7397b010e2a8 cherry-picked on top. What helped is forcing TSX off (via `has_rtm()` -> `false`) at the cost of performance. Before 367f039523fb it worked fine as is.

**Comment by jbeich** [comment]
Persona 5 appears to work fine after #4742 (eb081bbcfaa6 in particular).

**Comment by jbeich** [comment]
@Crimsom13, does Resistance 2 still crash on load with the latest build? Otherwise, this issue can probably be closed.

**Comment by Asinin3** [comment]
@jbeich What about Aquapazza, Persona 4 Arena and Bomberman Ultra?

**Comment by Asinin3** [comment]
P4A works for me 
![image](https://user-images.githubusercontent.com/15137035/44036514-788a9320-9f01-11e8-81da-c7cf6809ab90.png)I've also heard reports of Aquapazza working, so going to close this.
