### ISSUE TITLE
PC Games are getting slow

### ISSUE THREAD

**Issue by kumarks1122** [RPCS3/rpcs3#4616]
### My PC Configuration:
i7 processor
NVidia Quadro K1100m - 2GB Graphics Memory
32GB Ram
Windows 10
### Issue
I did installed RPCS3 by downloading from https://rpcs3.net. Tried to play PS3 Games including Tekken and God Of War III. But it was so slow.
Then I went to play my PC games. They also getting slow. But it was giving the awesome performance before installing RPCS3.
Please help me to get resolve that slow issue for my PC games.

**Comment by elad335** [comment]
ugh

**Comment by Megamouse** [comment]
did you make sure the process isn't still running in the task manager ?

**Comment by AniLeo** [comment]
Just a note, "i7 processor" doesn't mean anything, that's like someone asking about a car model and you answering "electric"

Also, no OS information at all..
Did you reboot between testing emulator and other games?

**Comment by kumarks1122** [comment]
@AniLeo 
Yes. I did restarted the machine
OS : **Windows 10**

@Megamouse : It is not running

**Comment by CrabLugo** [comment]
Reboot PC, reinstall drivers, reinstall windows.
Check compatibility list for playable games. Surprise! GoW 3 isn't stated as playable. 

I wouldn't recommend 2gb vram graphic card in 2018 for awesome performance in pc games.

Use forum and discord for issues, Github is for reporting bugs and regressions. Be gone

**Comment by AniLeo** [comment]
Windows 10 is also very vague, what build? Also, you still didn't say CPU model.

**Comment by 13xforever** [comment]
This _might be_ related to timer resolution changes from #4569.

See e.g. [these benchmarks](https://www.anandtech.com/show/12678/a-timely-discovery-examining-amd-2nd-gen-ryzen-results/5) and how higher timer resolution impacts game performance:

**Comment by kumarks1122** [comment]
@AniLeo The updated build which is now in rpcs3.net

@13xforever I tried to play my PC game **Assassin's Creed IV Black Flag** .

**Comment by AniLeo** [comment]
We don't offer Windows 10 builds. Answer the questions properly. Windows 10 build and CPU model?

**Comment by 13xforever** [comment]
I can confirm that rpcs3 doesn't have any permanent impact on timer configuration, and even when it requests higher timer resolution, it doesn't alter timestamp source that can impact other software.

As such I highly doubt that rpcs3 is the root cause of any performance abnormalities.

**Comment by MSuih** [comment]
It could be an overheating issue. RPCS3 taxes CPU far more than normal games do, and this might cause features like Turbo Boost and GPU Boost to not reach as high clock speeds as normally or even force the CPU or GPU to downclock it's base speed.  The effect might persist for some time after emulator has been closed depending on fan speed curves and heat sink dissipation rate.

**Comment by Relsig** [comment]
My GF's old craptop (an HP zbook) happens to run an i7-4700MQ, a Quadro k1100m 8gb ram and an even older version of Windows 10 (16299.64).

Ac: IV Black Flag (PC version) performance was good for a laptop, it only got a tiny bit warm.

It only took RPCS3 10 mins to turn the laptop into a space heater.

After cooling AC:IV performance was the same as before.

I wouldn't recommend running RPCS3 on any laptop in it's current state because laptops tend to have shoddy cooling.

**Comment by kumarks1122** [comment]
@MSuih Thanks Man. it is overheating issue. fixed fan issue. Then it is working fine now.
@Relsig Giving good performance after I fix the fan issue. Thanks Bro.
