### ISSUE TITLE
Bad stuttering on pre-rendered cutscences and hang after they play on Valkyria Chronicles [ BLUS30196 ]

### ISSUE THREAD

**Issue by micaelis72** [RPCS3/rpcs3#4624]
Folks,

After some commits (As a Linux user, I have hard time to pinpoint which commit screwed the game), this game hangs after the pre-rendered cutscenes run

In the logs on the log console on Qt's interface, I noticed that:

E {PPU[0x1000006] Thread (_sys_MixerChStripMain) [0x0071c050]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000006] Thread (_sys_MixerChStripMain) [0x00717274]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000006] Thread (_sys_MixerChStripMain) [0x00717334]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000006] Thread (_sys_MixerChStripMain) [0x00717274]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [2]
E {PPU[0x1000006] Thread (_sys_MixerChStripMain) [0x00717334]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000006] Thread (_sys_MixerChStripMain) [0x00717274]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [3]
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x0071a608]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x0071a608]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [2]
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x0071a608]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [3]
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x0073bc84]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x00717484]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x0071752c]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x00717484]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [2]
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x0071752c]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000008] Thread (_cellsurMixerMain) [0x00717484]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [3]

This happens all the time I've ran the game. Only loading liblv2 gives you a short version of this log above, automatic loading of libraries give you a more lengthy and complete one.

I'm attaching a log where I did several tests with multiple scenarios. I hope it will help:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2020400/RPCS3.log.gz)

PS.: This behavior was noticed on Super Street Fighter IV Arcade edition [ BLUS30793 ] in the same scenario of waiting the pre-rendered cutscenes ran and after that, hangs. Probably these games share a common framework. Both hangs after the emulator tries to unload some previously loaded libraries.

Valkyria also have a bug on native interface on Linux using Vulkan, where get black screen on a dialog that doesn't show and needs user intervention to make the videos running.

Two more things found:

OGL: Video stuttering (Sometimes doesn't happen using the Thread Option, even on Linux. Not consistent, but happens each three times I test)
Vulkan: Video smooth all the time

Cheers guys!

**Comment by digitaldude555** [comment]
Been 2 years no update @micaelis72

**Comment by digitaldude555** [comment]
Its not an issue anymore just tested.
