### ISSUE TITLE
Provided appimage is incompatible with Ubuntu 18.04 

### ISSUE THREAD

**Issue by Ado-Riano** [RPCS3/rpcs3#4626]
Ubuntu 18.04 has Qt 5.9, while rpcs3 appimage requires 5.10.
Qt 5.10 should be inside appimage, to make it truly portable. 

Error:
rpcs3: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by rpcs3)

EDIT: i don't know why, but it works now.

**Comment by AniLeo** [comment]
Works for me
