### ISSUE TITLE
S LDR: Boot successful. Error in some Games

### ISSUE THREAD

**Issue by PlayerWind** [RPCS3/rpcs3#4627]
Hello i got some issues with the recent bulid}

Some Games like Resident Evil 4 HD

and Reasonate of Fate  too

Shank game those are all for now

Only Boot on a Older Bulid 5 May

OS:Windows 7 X64

Cpu:Amd

Gpu:Amd

there's not much to prove if he just says that

**Comment by AniLeo** [comment]
No useful information, if it's a regression you need to point exactly which PR regressed it and actually provide logs.

**Comment by PlayerWind** [comment]
Actually checked...only say that but if you want a log is ok

**Comment by AniLeo** [comment]
Yeah, games go way past boot. You have to clarify what's the issue and in which PR they regressed

**Comment by AniLeo** [comment]
Closing issue as there's no answer and there's no visible issue, boot successful is not an error
