### ISSUE TITLE
VK: Tetris [NPUB30226] - Missing Textures In Upper Left

### ISSUE THREAD

**Issue by ehea617** [RPCS3/rpcs3#4630]
Tested on RPCS3 commit hash c9669818ebde71820ba243eaf668da2a162ca6ba.

Specs:
Windows 10 x64 v1803 (OS build 17134.48)
AMD A8-6500 APU @ 3.5GHz (4.1GHz Turbo)
GIGABYTE GeForce GT 1030
Driver version: 391.35 Driver date: 3/23/2018
16 GB (2x8GB Dual Channel) DDR3 1600MHz RAM

Steps to reproduce:
1. Switch the Renderer to Vulkan in the game or emulator configuration.
2. Launch the game and notice that some textures in the upper left corner are missing.
3. Close the game and switch the Renderer to OpenGL in the game or emulator configuration.
4. Launch the game and notice that the missing textures are now visible.

Vulkan:
![image](https://user-images.githubusercontent.com/12926544/40320348-659038c8-5cf9-11e8-8e7d-93b66e13ad9f.png)
![image](https://user-images.githubusercontent.com/12926544/40320380-83a87f28-5cf9-11e8-9dca-836fa0702913.png)

OpenGL:
![image](https://user-images.githubusercontent.com/12926544/40320607-3f66ec18-5cfa-11e8-82b1-c4249c612a61.png)
![image](https://user-images.githubusercontent.com/12926544/40320631-4d4fc534-5cfa-11e8-81a7-2d3a3fb9bb9f.png)

**Comment by kd-11** [comment]
Disable "GPU texture scaling" if you have it enabled.

**Comment by ehea617** [comment]
> Disable "GPU texture scaling" if you have it enabled.
The issue still occurs with GPU texture scaling disabled.

**Comment by ehea617** [comment]
Some further testing shows that it still occurs with the PPU set to Interpreter (precise), Write color buffers enabled, Disable Vertex Cache enabled, and Strict Rendering Mode enabled.

**Comment by TheRibbit** [comment]
Works fine for me too.
i5-4670K 4.4GHz, 16GB 2133MHz RAM, R7 260X 2GB GPU, 18.3.4 drivers version, Windows 7 SP1 x64

![image](https://user-images.githubusercontent.com/20685847/40373067-219ae434-5df7-11e8-8d1a-3bc8008b935d.png)

**Comment by ehea617** [comment]
I just retested this on b230b0df0d6abcea74c578dbae2d68ea488dd5d3 with a fully clean install with all default settings except for renderer changed to Vulkan and the issue still persists. I've added some more detail to my listed PC specifications also.

**Comment by kd-11** [comment]
Few suggestions
1. Use ppu and spu interpreters to rule out recompiler differences
2. Post log file so we can see what is happening

The fact that it only happens on your setup and is confirmed to work well for nvidia and amd cards makes it possible its caused by something cpu side or settings config.

**Comment by ehea617** [comment]
Here's all the testing I've done with the different recompilers (commit hash dcd7f442fac3b9b45ecaddf5460ecb8f7238df2e):
Combo 1:
PPU - LLVM Recompiler
SPU - ASMJIT Recompiler
Outcome - Missing textures still occur

Combo 2:
PPU - Interpreter (fast)
SPU - ASMJIT Recompiler
Outcome - Missing textures still occur

Combo 3:
PPU - Interpreter (precise)
SPU - ASMJIT Recompiler
Outcome - Missing textures still occur

Combo 4:
PPU - LLVM Recompiler
SPU - Interpreter (fast)
Outcome - Unknown - Sits on the game loading screen for a long time with no indication in the log that it is still loading

Combo 5: 
PPU - LLVM Recompiler
SPU - Interpreter (precise)
Outcome - Unknown - Sits on a black screen for a long time with no indication in the log that it is still loading

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2064018/RPCS3.log)

**Comment by kd-11** [comment]
You have aspect ratio forced to 16:9, leave it on auto. If that still doesnt work attach log from the broken vulkan run. The one posted is opengl + scaling enabled.

**Comment by ehea617** [comment]
Issue still occurs with auto aspect ratio on Vulkan. Tested on f491dc14135e070fa78048451fbfe2f63db4a163.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2098941/RPCS3.log)

**Comment by ehea617** [comment]
I can no longer reproduce this issue.
