### ISSUE TITLE
Dynasty Warriors Gundam Reborn (BLES02057) Exploding Vertices

### ISSUE THREAD

**Issue by reaper185** [RPCS3/rpcs3#4632]
i7-7500U  2.90Ghz
16GB RAM
250Gb SSD
Intel HD Graphics 620

RPCS3 v0.0.5-6815-c9669818e Alpha
Vulkan
PPU LLVM
SPU ASMJIT

This character in specific (Gundam Wing Endless Waltz Custom DLC) gets broken graphics all the time except when using the dash option. Have tried changing settings and the problem still persist

PS3
![untitled3](https://user-images.githubusercontent.com/39013260/40335506-04d39082-5d32-11e8-94ae-7595f44f948a.jpg)

RPCS3
![untitled](https://user-images.githubusercontent.com/39013260/40334740-85d8faf0-5d2d-11e8-93b5-abca77a805d8.jpg)

PS3
![untitled2](https://user-images.githubusercontent.com/39013260/40335530-2e0c31ca-5d32-11e8-8b5d-773f521e54a5.jpg)

RPCS3
![untitled1](https://user-images.githubusercontent.com/39013260/40334743-8892af2a-5d2d-11e8-93e7-a3dbfff70660.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2024392/RPCS3.log.gz)

**Comment by reaper185** [comment]
Tested with newer versions of rpcs3 #4871 and in another PC and the issue is still present. Just updating.

RPCS3 v0.0.5-7268-4c145953 Alpha | HEAD
Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz | 4 Threads | 5.92 GiB RAM | AVX+
Intel HD Graphics 4600
TOSHIBA DT01ACA050 500Gb 

[config.zip](https://github.com/RPCS3/rpcs3/files/2336227/config.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2336208/RPCS3.log.gz)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/5125
