### ISSUE TITLE
Big Regression In God of War Collection 1-3 FPS

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#4636]
RPCS3 v0.0.5-6815-c9669818e

![image](https://user-images.githubusercontent.com/25039098/40361746-9df15e9a-5ddf-11e8-8796-ec6d8658115a.png)

![image](https://user-images.githubusercontent.com/25039098/40361786-bb90ec9a-5ddf-11e8-9632-95002e510476.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2026546/RPCS3.log.gz)

PPU LLVM + SPU ASMJIT

xeon E5472
GTX 780ti
16gb ram
win 10 version 1607

**Comment by AniLeo** [comment]
Missing build where it regressed

**Comment by Asinin3** [comment]
Try the latest build, nekotekina just merged some performance fixes.

**Comment by aakh1361** [comment]
@Asinin3 
No different whit last build

@AniLeo 
I do not know which reduction started
whit build 6592 fps is good
reduction is after 6592

![image](https://user-images.githubusercontent.com/25039098/40365655-4a648cba-5dea-11e8-92c4-50b3acc91f0b.png)

**Comment by AniLeo** [comment]
6593 are text fixes, so I doubt it regressed there. It's also a very old build, saying it worked 2 months ago isn't of much help.

You need to pinpoint exactly which build regressed it, otherwise it's not a valid regression issue

**Comment by aakh1361** [comment]
this is for 6697
![image](https://user-images.githubusercontent.com/25039098/40366754-32403b40-5ded-11e8-9f1f-4a8894c99d86.png)

May This reduction is not just about a build

I'm sorry I do not have enough bandwidth and I can not download and try all of them.

**Comment by Asinin3** [comment]
Someone told me that this game likes spu loop detection disabled and only a few spu threads, it might help. Performance is okay for me. 
![image](https://user-images.githubusercontent.com/15137035/40369358-50dbdc50-5dcd-11e8-9492-6afc67db17c7.png)

**Comment by Illynir** [comment]
Yes, SPU LOOP Detection kill the performance on video sometimes on these games. Deactivate SPU LOOP DETECTION and try with SPU THREAD on 1.
