### ISSUE TITLE
TSX not recognized

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#4640]
Using build from commit c9669818ebde71820ba243eaf668da2a162ca6ba, on Linux 4.15 kernel, the UI does not recognize TSX with i7-7820HK, even though TSX-NI [is supported](https://ark.intel.com/products/97464/Intel-Core-i7-7820HK-Processor-8M-Cache-up-to-3_90-GHz).  The following is shown:

RPCS3 v0.0.5-6815-c966981 Alpha | master
Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz | 8 Threads | 15.63 GiB RAM | AVX+

**Comment by AniLeo** [comment]
Intel's Ark doesn't mean anything, use an actual tool to see if it's enabled.

**Comment by Shoegzer** [comment]
Ah, right.  Doing a cat /proc/sysinfo reveals support for AVX etc. but no TSX.  Interesting, especially for a Kaby Lake (albeit mobile) proc.  I wonder if you can turn the feature on somehow such as in BIOS/UEFI but I'll check when I have more time.  

I'll close this issue soon pending no other comments from anyone else about this.  Thanks.

**Comment by AniLeo** [comment]
I'm closing since it's not an issue with RPCS3. Your CPU lacks TSX support.
