### ISSUE TITLE
Ninja Gaiden Sigma crashes when I try to save the game

### ISSUE THREAD

**Issue by Albin13** [RPCS3/rpcs3#4644]
System specs: i7 7600k, GTX 1070, 8GB DDR4 2133
At first the emulator would stop working when I try save the game, now it also stops working when I try to load the save. I am using the build from 05/21

**Comment by AniLeo** [comment]
Is this a regression or? Missing log either way

**Comment by Albin13** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2028266/RPCS3.log)
Sorry, here is the log.
It was working perfectly with previous builds

**Comment by Megamouse** [comment]
you should try a newer build

**Comment by Parthorisian** [comment]
https://imgur.com/eTI73px Log [NinjaGaiden_crashRPCS3.zip](https://github.com/RPCS3/rpcs3/files/2029577/NinjaGaiden_crashRPCS3.zip)

**Comment by Albin13** [comment]
Ok, so I just updated the emulator and tried to play the game several times to see what happens. It turns out that sometimes the emulator freezes when loading a save or saving the game and sometimes it works normally. It's very odd. Anyway, here is the new log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2029584/RPCS3.log)

**Comment by Megamouse** [comment]
I tried this with the latest master.
it works fine on my end

**Comment by Megamouse** [comment]
also. you should play with "Load liblv2.sprx only"

**Comment by Parthorisian** [comment]
Runs as usual for me. Haswell 4770, Win7SP1Ultx64bit and Win10LTSB. Dont noticed any issues

**Comment by Albin13** [comment]
Well, after updating the emulator again and using the "load liblv2.sprx only" option I tested the game several times, and I am happy to inform that the problem has been solved. The game is working perfectly again. Keep up the good work guys!
