### ISSUE TITLE
Regression: Call of Duty: Modern Warfare 3 [BLUS30838] (#4382)

### ISSUE THREAD

**Issue by creeperjedi** [RPCS3/rpcs3#4645]
Begining from pr #4382 and onwards, Call of Duty: Modern Warfare 3 no longer goes ingame. The game now stalls right before going ingame, and no combination of decoders and renderders fixed the regression. Looking at the comments from pr #4382, it seems that Modern Warfare 2 was also affected in the same way. 

Logs:
[RPCS3 Log v0.0.5-6633.zip](https://github.com/RPCS3/rpcs3/files/2028655/RPCS3.Log.v0.0.5-6633.zip) - Last Working Build
[RPCS3 Log v0.0.5-6638.zip](https://github.com/RPCS3/rpcs3/files/2028656/RPCS3.Log.v0.0.5-6638.zip) - Build from pr #4382
[RPCS3 Log v0.0.5-6826.zip](https://github.com/RPCS3/rpcs3/files/2028657/RPCS3.Log.v0.0.5-6826.zip) - Current Master Build

Specs:
Windows 10 x64 v1709 (OS build 16299.371)
Intel Core i7-4770
NVIDIA GeForce GTX 745
8 GB (2x4GB Dual Channel) DDR3 1600MHz RAM

**Comment by AniLeo** [comment]
Testing with MW2 here which has the same reported issue.

I don't understand how MW2 was supposed to get Ingame.
I tested 6633, the build right before #4382, and it doesn't go Ingame for me as well.

6633
![image](https://user-images.githubusercontent.com/10283761/40854543-c0e74d50-65c9-11e8-8e0a-9a2c9a1d3cdf.png)

6882
![image](https://user-images.githubusercontent.com/10283761/40854552-c740d298-65c9-11e8-8a86-8838b7688274.png)

**Comment by Josivan88** [comment]
I can confirm what @creeperjedi is observing, the same whit me.

**Comment by RainbowCookie32** [comment]
Just tested with MW2 Demo. In 0.0.5-6633 it goes ingame, latest master crashes after the loading screen with F 0:02:41.453921 {RSX [0x002696c]} MEM: Access violation reading location 0xcfaee000
[Log from master](https://github.com/RPCS3/rpcs3/files/3124547/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
![Screenshot (2558)](https://user-images.githubusercontent.com/26138653/57440090-08142980-7250-11e9-9cd2-8cdbc52b3606.png)
the demo is ingame. @creeperjedi test full version

**Comment by RainbowCookie32** [comment]
Goes ingame, crashes with ```
F 0:06:59.384454 {RSX [0x0155454]} RSX: class std::runtime_error thrown: Assertion failed: !cached.is_locked()
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\gltexturecache.h:809)
```
![Untitled](https://user-images.githubusercontent.com/16805474/57467800-92ad5680-7259-11e9-83c0-96e86886fdeb.jpg)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3162959/RPCS3.zip)

**Comment by creeperjedi** [comment]
The Campaign suffers from poor performace, but could go for about a minute ingame before I encountered the same crash as RainbowCookie32: 
```
F {RSX [0x004672c]} RSX: class std::runtime_error thrown: Assertion failed: !region.is_locked()
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vktexturecache.h:963)
```
Loading into Survival gives semi-playable performance that can be improved by using the latest update. The only exception to this is the map Underground which instantly dies with the error:
```
F {RSX [0x00ffa70]} RSX: class std::runtime_error thrown: Unknown blend eq 0x0
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gcm_enums.cpp:734)
```
[RPCS3.7z.log](https://github.com/RPCS3/rpcs3/files/3164500/RPCS3.7z.log) (just remove the .log in the name then extract)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3164498/RPCS3.log.gz)

**Comment by creeperjedi** [comment]
Because the regression is gone and is now running better than before the regression, I'm closing the issue. If you have any specific problems then start a new issue.
