### ISSUE TITLE
Hyperdimension Neptunia Mk.2 Regressions

### ISSUE THREAD

**Issue by Charmareian** [RPCS3/rpcs3#4654]
#6638
![untitled2](https://user-images.githubusercontent.com/24770185/40456600-3995b284-5ec0-11e8-9094-52fd0ed53eb9.png)

#4611
![untitled](https://user-images.githubusercontent.com/24770185/40456595-35101ad8-5ec0-11e8-9f48-71092d7db8c2.png)

Game was playable at a locked 22fps. Now it averages 11 fps with drops to 1 fps. 

GTX 1070
i5 4690
16gb ddr3

**Comment by Asinin3** [comment]
I don't know why you closed this but it belongs in https://github.com/RPCS3/rpcs3/issues/4651 if it's still accurate.

**Comment by Charmareian** [comment]
Ah okay thanks. The regressions were from a long time ago so I thought it
was pointless to mention
