### ISSUE TITLE
Excessive amount of RAM on loading shaders cache

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4656]
Maybe I'm repeating - if so, just remove...
If the emulator compiled 1000 and more shaders for game, they start to consume really large amounts of RAM. For example, 1000 shaders takes about 4 Gb immediately after game loaded, 2000 shaders already about 6 GB, and 3000 and more shaders eats all 8 Gb of my RAM and starts swapping. 

Have anybody encounter this, and don't you think it's not very adequate behavior? Or this is driver/hardware sensitive issue? I checked it on GTX 560, GTX 750 and GTX 760, Win 7 and Win 10, and all the same.

**Comment by AniLeo** [comment]
Not our issue, NVIDIA drivers use a lot of RAM. AMD drivers are fine in that aspect.

**Comment by CrabLugo** [comment]
I have had similiar issue on nvidia gtx 1060 w7. Using w10 fixed the issue for me. Maybe you have installed ssd software to keep more data in RAM memory?
