### ISSUE TITLE
Kingdom Hearts HD 1.5 Remix not playable after opening

### ISSUE THREAD

**Issue by iEldik3** [RPCS3/rpcs3#4663]
Kingdom Hearts Final Remix make some noise after opening and then shows black screen with freezed fps(rpcs3 not stopping working)
Kingdom Hearts 258/2 and Re:Chain of Memories has the same problem.After opening game stops on logo,fps not freezed(rpcs3 not stopping working)
All games have chopped screen but in 258/2 days there is subtitles

CPU-Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
GPU-Nvidia GeForce GTX 750 8 RAM
OS-Windows 10 64-bit

RPCS3 Settings:
PPU Decoder-LLVM Recomplier
SPU Decoder-ASMJIT Recomplier
Spu Threads-Auto
Firmware settings-Load libv2.sprx only
Additional Settings:
Enable thread scheduler-on
Lower Spu thread priority-off
Enable spu loop detection-on
Hook static functions-off
Renderer-Vulkan
Resolution-1280x720
Aspect Ratio-16:9
Framelimit-30
Antisotropic Filter-Automatic
Additional settings:
Write color buffers-off
Use GPU Texture Scaling-on
Strict Rendering Mode-off
VSync-off
Stretch To display Area-off
Disable Vertex Cache-off

Screenshots and logs in archive

[KH logs.zip](https://github.com/RPCS3/rpcs3/files/2042406/KH.logs.zip)

**Comment by 13xforever** [comment]
These are known issues, some of which has workarounds. Please use forums of discord to get support instead of opening tickets on github.

Also please stop submitting issues for pirated copies of the game.
