### ISSUE TITLE
Minecraft: PS3 Edition [BLES01976] - Multiple issues

### ISSUE THREAD

**Issue by geniiii** [RPCS3/rpcs3#4670]
1. Doesn't go ingame with GPU Texture Scaling  
![image](https://user-images.githubusercontent.com/24881499/40661798-59f6ecd6-635d-11e8-939a-cc8edd1e3ae6.png)    
This is the furthest it gets, goes in-game without it. Issue affects both OpenGL and Vulkan. #4587 also references this. The log it saves after this doesn't get compressed (emulator crashes after closing), so I had to compress it myself.
[RPCS3-6852-gpu_texture_scaling.log.gz](https://github.com/RPCS3/rpcs3/files/2048419/RPCS3-6852-gpu_texture_scaling.log.gz)

2. Random crashes on PPU LLVM  
Crashes aren't present on any of the interpreter modes.  
[RPCS3-6852-ppu_llvm_crash.log.gz](https://github.com/RPCS3/rpcs3/files/2048413/RPCS3-6852-ppu_llvm_crash.log.gz)

3. Shaders saved to disk crash RPCS3
Any on-disk shaders saved from in-game crash the emulator while it attempts to load them. Had to compress the log myself again.
[RPCS3-6852-shaders_loading.log.gz](https://github.com/RPCS3/rpcs3/files/2048431/RPCS3-6852-shaders_loading.log.gz)

RPCS3 v0.0.5-6852-824340363 Alpha | HEAD
Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz | 4 Threads | 15.95 GiB RAM | AVX+

**Comment by altiereslima** [comment]
Several games are crashing while saving the shaders

**Comment by niko1point0** [comment]
Minecraft goes in-game now, but for some reason, wolves spawn all around the players when Multiplayer is enabled

**Comment by geniiii** [comment]
> Minecraft goes in-game now, but for some reason, wolves spawn all around the players when Multiplayer is enabled

Can confirm, wolves spawn around *one* of the players in multiplayer. I don't know if it's intended or not.

**Comment by digitaldude555** [comment]
Minecraft is fully playable, is this still an issue at all?

**Comment by niko1point0** [comment]
There is still a big bug in this game. In multiplayer, wolves randomly spawn around Player #2, but will not spawn around any other player. What my friends and I have to do, is spawn player 2, make player 2 run to the corner of the map, and then we use the other players to play the game. Please fix this bug. We think it happens whenever player 2 sprints

**Comment by niko1point0** [comment]
Also, I tried making multiple user accounts for additional players, but I cannot log players 2, 3, or 4 into user accounts, they just log into the same temporary NULL account. Please make a way for all 4 players to be logged into different users. Thank you

@digitaldude555 

After that, the game will be playable

**Comment by Fanapixelados** [comment]
![image](https://user-images.githubusercontent.com/78716737/130345524-feee140c-549c-483d-9493-62be140c0ff4.png)
Infinite Loading
