### ISSUE TITLE
Different CPU managing on Win7 and Win10 OS'es?

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4674]
I made some checks on how the emulator behaves on different Windows versions, and found that it seems have differences in how it manages CPU and its threads. I have not very stong CPUs which are sensitive to all stuff, and for example, enabling "SPU Threads" to "Auto" on Windows 7 leads my CPU to infinity stutterings in 100% load (to all 4 cores), while the same thing on Windows 10 (I use LTSB version) even makes my games run faster, and CPU load is averaged enough. In Win7 I need to set "SPU Threads" to 1-2 only to get smooth process. Also I can't notice the issue #4643 on Win10 which I openend playing on Win7. If it's important, the current checks done on the same machine, with two OSes installed in parallel. CPU is Intel Core i5-760.

**Comment by CrabLugo** [comment]
After switching w7 to w10 i definitely can say that rpcs3 works better on 10. CPU and RAM memory are handled better.
It's realy hard to not notice difference ^^ i5 8400/gtx 1060 6gb (tested i5 8400 w7 too)
No idea what is a cause, but would like to know too.

**Comment by Zangetsu38** [comment]
it is normal, WIndows 7 is totaly dead now, my ryzen, my 960 evo don'tr have anby suppoort on Windows 7, jit is just dead now

**Comment by Zangetsu38** [comment]
no, ryzen not works on Windows 7, not fulkl compatible, and with this,n MS disable Windows update lol , and for 960 evo eu yes, works like this but eu need also install in Windows 7 disc install all driver usb.., just now is very shit xD, install WIndows 10 and all works perfectly

**Comment by AniLeo** [comment]
That's MS crap. You can well enable updates on newer CPUs, and it works with them

**Comment by CrabLugo** [comment]
Since we already talk about w7 and this stuff, i'm gonna say one more thing.

I couldn't force yet w10 to work with chipset b360/h370. z370 works without problems, but it's chipset made in differerent technological process (new chipsest are improved and made in 14nm process). Somehow w7 WITH installed USB drivers, didn't  let me use USB ports with b360 motherboard. No matter which bios configuration i tried. PS/2 keyboard still works, but any USB port didn't want to let me use them after w10 was loaded, only for energy.

Tried to google answer, but found nothing. If anyone have an answer/solution, go ahead and share info :)

**Comment by Psycho-A** [comment]
> it is normal, Windows 7 is totally dead now, my Ryzen and my samsung 960 evo don't have any support on Windows 7, it is just dead now

If you talk about modern CPUs, it's understandable, maybe (although I'm sure some unoficial driveers and updates do fix that). But what about MY CPU which was released even when Win 10 even weren't planned in project? It works equally good on both Windows' for other stuff, and only for RPCS3 I notice difference.

**Comment by Zm0n** [comment]
> I couldn't force yet w10 to work with chipset b360/h370. z370 works without problems, but it's chipset made in differerent technological process (newer chipsests are improved and made in 14nm process). Somehow w7 WITH installed USB drivers, didn't let me use USB ports with b360 motherboard. No matter which bios configuration i tried. PS/2 keyboard still works, but any USB port didn't want to let me use them after w10 was loaded, only for energy. z370 is just another z170/z270 revision.
Also worth noting is the fact, that chipsets z370/b360/h370 share identical chipset drivers. So i assume it's Intel intentional action.

This makes no sense whatsoever. I'd return the board you bought.

**Comment by CrabLugo** [comment]
It makes sense. Gigabyte website shows 
older (z370) motherboards with oficial w7 support. But w7 is not officialy supported by any mobo manufacter b360/h370

**Comment by Zm0n** [comment]
Your post made it sound like you couldn't get b360/h370 to work on W10, that's why I said that. Z370 will work if you slip the drivers into the install, but IMO, there's really no point when 10 is the better choice at this point. Of course, the same thing happened with 7 when it came out with people wanting to use XP over it.

**Comment by CrabLugo** [comment]
My point is that i am unnable to run w7 with b360 with working USB ports, while z370 is working ok

**Comment by Parthorisian** [comment]
But older CPUs like my Haswell4770 runs much better with Win7(my updates before december 2017) ). Performance is much better not only for windows games. Large slowdown for w10 since... unsure, may be december-february builds

**Comment by TheRibbit** [comment]
Seems like it's configuration and luck dependent. Windows 7 just broke for me recent rpcs3 builds in several places. So I installed Windows 10 1607 (yeah, that old) - it's all good now.
(i5-4670K 4.5GHz, 16GB 2133MHz RAM, R7 260X 2GB GPU, 18.5.1 drivers version)

**Comment by Psycho-A** [comment]
Found that performance differences between OS dramatically increased after build 6817. I don't know what were done, but seems like it's really unwanted on Win7.
