### ISSUE TITLE
Latest RPCS3 randomly freezes during shader compilation if perfomance overlay is enabled...

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#4675]
0.0.5-6871

If Performance Overlay is enabled and set to Medium\High and the interval is set above certain value,rpcs3 will almost always freezes during the initial shader compilation

This is my first time trying the overlay and I though 350ms is too often(I don't want to get the info that often)so I set it to 1 second(1000)and when I tied a random game(I tied all other games I have after that)I saw that rpcs3 freezes

On Minimal and Low,it's fine with 1s but it almost always freezes with Medium and High
Revertting it back to 350ms fixes the problem(I think)

**Comment by Megamouse** [comment]
Try openGL.
Vulkan is bugged.

**Comment by vsub** [comment]
Hmm yes,it works with OGL

**Comment by PuppyCodeMaster** [comment]
tbh turning on preformance overlay helped
