### ISSUE TITLE
6869 Regression: vkFence management issues (threading)

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#4690]
Red Dead Redemption crashes as soon as the main menu appears with amdvlk64.dll error. With debug output enabled, the following lines appear in console as it crashes:

>·E 0:01:26.498220 {rsx::thread} RSX: ERROR: [THREADING] Code 1 : Object: 0x4cd57 | THREADING ERROR : object of type VkFence is simultaneously used in thread 3012 and thread 10220
>·E 0:01:26.498235 {rsx::thread} RSX: ERROR: [ObjectTracker] Code 704677889 : Object: 0x4cd57 | Invalid Fence Object 0x4cd57. The spec valid usage text states 'fence must be a valid VkFence handle' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkGetFenceStatus-fence-parameter)

Managed to narrow down the PR which caused it, 6866 (3d632a3) can reach menu just fine while 6869 (cf2cb79) crashes as soon as it appears, which means that #4671 is the suspect. I tested with latest version (6884 / dcd7f442f) but the same crash appears, so it's not related to the memory leak issue that was fixed after that PR.

[Full log](https://github.com/RPCS3/rpcs3/files/2064700/RPCS3.log.gz). This is on RX 480 8GB.

Edit: OpenGL is not affected.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/4698
