### ISSUE TITLE
Move controllers issue

### ISSUE THREAD

**Issue by Radkhyn** [RPCS3/rpcs3#4693]
Good after-noon everyone, i'm able to play my game Folklore on my computer but for whole game i will have to shake my controller to capture or kill ennemies and this does not work, i can not go further than chapter 1 :(

Can someone help me to resolve this problem, i'm using xbox 360 controller, i tried with "under ps3 controller" i havent ps3 bluetooth controller.

Thank you very much

**Comment by MSuih** [comment]
Only controller that supports motion controls is DS4. DS3 or Sixaxis has no driver support for it and your x360 controller doesn't even have the required hardware for it.

**Comment by AniLeo** [comment]
It's not an issue, sixaxis is not implemented outside of DS4.

Furthermore, the issue tracker is not the place to ask for support, as explained in the guidelines.

**Comment by DumF0rGaming** [comment]
@AniLeo Any chance fake tiliting implementation would be possible anytime soon? That literally made Dead Space Extraction unplayable, since you can't pass intro. I believe there's many more games with Sixaxis movement as a requirement
