### ISSUE TITLE
[Regression] Dark Souls II after #4553 does not go ingame  

### ISSUE THREAD

**Issue by spyropt** [RPCS3/rpcs3#4696]
Darks souls II Hangs before going ingame

Cpu xeon x5675 without avx /tsx
Logs
[RPCS3 6718.log.gz](https://github.com/RPCS3/rpcs3/files/2065239/RPCS3.6718.log.gz)
latest master same issue

[RPCS3 6884 .log.gz](https://github.com/RPCS3/rpcs3/files/2065240/RPCS3.6884.log.gz)
 
![image](https://user-images.githubusercontent.com/34097932/40879486-712afd50-6698-11e8-9fd3-0a0346157316.png)

![image](https://user-images.githubusercontent.com/34097932/40879500-c859ba08-6698-11e8-87ce-781ebfdd750d.png)
log from 4553
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2065244/RPCS3.log.gz)

**Comment by kd-11** [comment]
I can sometimes boot using PPU+SPU interpreters but others cannot. I also have a CPu without TSX.

**Comment by spyropt** [comment]
It does work with interperters but its 11fps vs 30/40fps :(

**Comment by kd-11** [comment]
This was recently fixed on master.
