### ISSUE TITLE
Regression : Performance decreasing in PR 4384 and 4422 on Tony Hawk's Project 8

### ISSUE THREAD

**Issue by Larxian** [RPCS3/rpcs3#4700]
I noticed performances decreasing in Tony Hawk's Project 8 over two different builds, Build 6642, PR [#4384](https://github.com/RPCS3/rpcs3/pull/4384) and build 6675, PR [#4422](https://github.com/RPCS3/rpcs3/pull/4422)

- A first regression happened on build 6642
Here is a comparison between 6639, the last one before 6642, and 6642

6639, overall between 24 and 30 Fps :
![](https://i.imgur.com/I4UcloR.jpg)
6642, first regression, between 14 and 19 fps:
![](https://i.imgur.com/0DlZWLC.jpg)

- A second regression happened on build 6675
Here is a comparison between 6664, and the next one, 6675

6664, same performances as all the builds after the first regression: 
![](https://i.imgur.com/Luj8S59.jpg)
6675, second big regression, taking the framerate under the 10 fps:
![](https://i.imgur.com/quXHMsA.jpg)

Same exact settings used during all situations.

I7 2600k @4,4 Ghz.

Logs:
6639 (original "good" performances") : [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2634146/RPCS3.log)

6642, first regression : 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2634157/RPCS3.log)

6675, second regression:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2634189/RPCS3.log)

**Comment by kamer1337** [comment]
i noticed the same,  i thought its my shitty laptop issue. performance is getting worse and worse in this game

**Comment by mtsaccorsi** [comment]
Same here... I have na Intel i7 4790k and only get 15 fps no matter what. With 6541 I can get full 30 fps at 4k! So thanks (for now). Maybe it's a bug with the non-TSX CPUs in the recent builds?

**Comment by Larxian** [comment]
Seems like it since recent CPUs don't seem to have this problem

**Comment by Banduck** [comment]
It still hasn't gotten any better.
build 6541: 25fps
build 7513: 7fps

 Is there any explanation for this?

**Comment by Larxian** [comment]
> 
> 
> It still hasn't gotten any better.
> build 6541: 25fps
> build 7513: 7fps
> 
> Is there any explanation for this?

Nope :( I asked several times in the discord but never got an answer on that. It seems like it works fine on modern CPU with TSX, so it will probably never get fixed for older CPUs sadly =/

**Comment by HenningJW** [comment]
Well if you don't pinpoint the exact commit(s) which caused a significant performance loss (with logs), nothing will happen.

**Comment by Larxian** [comment]
Hi again, so I compared tons of different builds, and I identified the specific builds that started the regression, the performances ingame actually regressed on 2 builds.

- A first regression happened on build 6642
Here is a comparison between 6639, the last one before 6642, and 6642

6639, overall between 24 and 30 Fps : 
[https://i.imgur.com/I4UcloR.jpg](url)
6642, first regression, between 14 and 19 fps:
[https://i.imgur.com/0DlZWLC.jpg](url)

- A second regression happened on build 6675
Here is a comparison between 6664, and the next one, 6675

6664, same performances as all the builds after the first regression: 
[https://i.imgur.com/Luj8S59.jpg](url)
6675, second big regression, taking the framerate under the 10 fps:
[https://i.imgur.com/quXHMsA.jpg](url)

Hope that helps.

**Comment by jobs-git** [comment]
I get the slow down too, and I suspect its the TSX, I am on 2x Intel Sandy Bridge - 16 core

**Comment by HenningJW** [comment]
Thanks @Larxian. So it's #4384 that cut the performance by a third and #4422 that additionally halved the performance. For the second one there is an open issue: #4473. Could you add logs and update the title to mention the PRs please? Then the apropiate labels will be added and hopefully someone will look into it. 33% and 50% performance loss is pretty significant.

**Comment by Larxian** [comment]
@HenningJW Just edited the title, is it good like that?
What logs am I supposed to add exactly? Just upload the "RPCS3.log" file created after running a game? Sorry if I don't know better, I never really reported issues like that.

**Comment by HenningJW** [comment]
@Larxian looks good, I think you can leave it like that. In the future you can upload the RPCS3.log.gz, it's the compressed version (like zip) and should be faster to up/download and put a # in front of the PR numbers, that way Github detects it and links to the PRs. But these are nitpicks, you can leave it like that.

**Comment by scribam** [comment]
@Larxian Can you check the performance again with the latest build?

**Comment by Larxian** [comment]
@scribam The game actually doesn't work anymore, just tried it on the latest build.
I get the following error during the initial loading of the game:
`F {RSX [0x00a4974]} RSX: class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vktexture.cpp:80)`

**Comment by kamer1337** [comment]
works fine for me. looks like this for me. looks like yuo are on this [issue](https://github.com/RPCS3/rpcs3/pull/5937#issuecomment-490413349)

**Comment by Larxian** [comment]
@scribam @kamer1337 
You're right, it now works after lowering the resolution.
Framerate is at 15 fps
https://i.imgur.com/5HrQ3l7.png
Doesn't seem to be changes on this specific build, was there a reason you wanted me to try it Scribam? Are performances better for you now?

**Comment by AniLeo** [comment]
Should be better now, try with SPU LLVM as well

**Comment by kamer1337** [comment]
i think this issue can be closed frame rate is decent now

**Comment by TakUser** [comment]
Looking to potentially open.  Latest build of RPCS3 runs this game horrendously, and the upscaling to 4K doesn't work correctly either unlike its older sibling: THP8.

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/2445901b-6916-45e3-8222-2118e3138d83" />

**Comment by AniLeo** [comment]
Unrelated, this ticket is 6 years old. If there is a new regression, track it down and file a new ticket.
