### ISSUE TITLE
FPS drops significantly after #4580

### ISSUE THREAD

**Issue by noname94** [RPCS3/rpcs3#4703]
I noticed FPS drops after #4580 (commit 367f039) in Persona5.
Actually, if "Preferred SPU Threads" set to auto or >= 2, FPS drops by around 20%. If set to 1, FPS is OK but video playback becomes laggy in game.
I found this was caused by replacing "vm::notify" with "notifier" class. The issue disappeared after I simply added back "vm::notify" and replaced all "vm::reservation_notifier(u32 addr, u32 size).notify_all()" with "vm::notify(u32 addr, u32 size)" in the latest version.
With issue:
<img width="651" alt="rpcs3_with_issue" src="https://user-images.githubusercontent.com/16044351/40884681-6c994056-6753-11e8-9e4f-cb05f1a63717.png">
Without issue:
<img width="651" alt="122" src="https://user-images.githubusercontent.com/16044351/40884693-9eb8cde0-6753-11e8-8abc-2fca9b200678.png">
Log:[RPCS3_log.zip](https://github.com/RPCS3/rpcs3/files/2065785/RPCS3_log.zip)
OS: Win8.1
CPU: i7 6700HQ
RAM: 16 GB
GPU: GTX1060 6G

**Comment by Psycho-A** [comment]
Probably the same issues as my #4643 and #4653, and this is bad, if so...

**Comment by wandbrandon** [comment]
can confirm I have the same issue

**Comment by scribam** [comment]
@noname94 Can you test again to see if the performance is back as before?

**Comment by noname94** [comment]
> 
> 
> @noname94 Can you test again to see if the performance is back as before?

Yes, this issue has been solved.
