### ISSUE TITLE
Custom aspect ratios (Increase rendered FOV)

### ISSUE THREAD

**Issue by b0ssplz** [RPCS3/rpcs3#4710]
I know this issue has been closed since enabling resolution scaling, but it should be easy to implement with lots of benefits for lots of 21:9 users.
So basically that's a function that prevents image stretching (HUD still stretches) but the rendered horizontal FOV is increased.

I know this sounds kind of pretentious and isn't a main topic, but it would be cool to see all those games in 21:9.

**Comment by 13xforever** [comment]
1. aspect ratio will not change fov; changing fov requires per-game patches
2. officially supported resolutions on ps3 are very specific 4:3 and 16:9 options, and the game can support only subset of those; you can't magically tell the game to use anything it doesn't support
3. current full screen mode will adapt to your native resolution as best as it can already

**Comment by b0ssplz** [comment]
Basically I'm asking for a functionality that seems to be already available by indirect methods.

https://www.youtube.com/channel/UC_Pi2Yz52L6KphGSITPQaUw/videos
This youtuber managed to get 21:9 aspect ratio in lots of games, but I have no idea how does he do it.

**Comment by 13xforever** [comment]
Yes. By using specific game patches.

There won't be any generic solution for this.

**Comment by Margen67** [comment]
The problem with an ultra-widescreen hack like Dolphin is that it tends to have more graphical issues than per-game hacks.

Typically you can just search for ~1.77777 Big Endian Float in Cheat Engine and change it to ~2.37 (depends on resolution: http://www.wsgf.org/article/common-hex-values)

Sometimes you can even take the address and convert it into a patch.yml and put it into the game's config folder and then it will apply automatically.

**Comment by kd-11** [comment]
There is no universal way to make a game work with a custom aspect ratio especially once you consider cell is also used to perform some of these transforms if not all of them (notice how spu bugs make graphics go crazy).
