### ISSUE TITLE
Folklore no voice since #4705

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#4712]
Folklore game has no voice sound in the videos "At least the first one, when you select a new game"

This started in #4705, previous builds such as #4707 works Ok.

There´s too some background sounds in the "Pub/inn of the beggining" that doesn´t works.  I think this happens since some builds ago, but I remember background sound of people talking and beer mugs colliding in previous buils, maybe one month ago.

**Comment by allens39** [comment]
Can you tell me what build it last worked in?

**Comment by AniLeo** [comment]
It literally says above, in #4707 and before

**Comment by LuismaSP89** [comment]
@AniLeo You took the words from my mouth xD

**Comment by LuismaSP89** [comment]
Update: Fixed in #4920
