### ISSUE TITLE
Data installation issue for BLJS10133

### ISSUE THREAD

**Issue by ChillyPrince** [RPCS3/rpcs3#4722]
BLJS10133 (Dai-2-Ji Super Robot Taisen OGs) can boot smoothly when first time of game data installation. But when boot the next time it shows up a window "The game data is broken, please delete the game data...", which means I have to reinstall the game data everytime to start playing.

Problems of BLJS10133 have been perfectly sovled except the data installation issue. There was some insights inside #2532 but I cant figure out what causes the game to be "broken" after naming the game data folder as "BLJS10133" instead of something like "BLJS10133DATA".

Im not sure if the log file is helpful. The "GameDataInstall" thread does not tell too much. But anyway i put them here: 
[RPCS3_first_installation.zip](https://github.com/RPCS3/rpcs3/files/2085897/RPCS3_first_installation.zip)
[RPCS3_boot_failure.zip](https://github.com/RPCS3/rpcs3/files/2085898/RPCS3_boot_failure.zip)

**Comment by Realmantik** [comment]
"Jissen Pachi-Slot Hisshouhou! Hokuto no Ken F - Seikimatsu Kyuuseishu" [BLJM60468] game also has this problem.

**Comment by Wizzy2018** [comment]
So if you have a disk version of this game go to location Rpcs3-dev hdd0-game-and delete a folder BLJS10133 it will fix second startup.You need do this everytime when you start a game 2nd time.

**Comment by digitaldude555** [comment]
This problem still exists.

**Comment by digitaldude555** [comment]
#6588 #2532 these are the same issue.

**Comment by Megamouse** [comment]
#2532 reports this as working.
Closing as duplicate anyway
