### ISSUE TITLE
Unreal Tournament 3 doesn't boot after installation.

### ISSUE THREAD

**Issue by MsDarkLow** [RPCS3/rpcs3#4723]
Windows 10
i7-8700k | GTX 1070 | 16 GB Ram

Build: rpcs3-v0.0.5-6907-fb20c27e_win64

The game successfully starts and manages to go ingame for the first time but, if I want to start the game again I always have to delete the folder _BLES00200_ in \dev_hdd0\game\ in order to boot up.

When I try to boot this error shows up on the log:
_F {PPU[0x1000000] Thread (main_thread) [0x0032aac8]} MEM: Access violation reading location 0xa02a5075_

![1](https://user-images.githubusercontent.com/9060436/41181432-6cdda5a6-6b69-11e8-9ad3-2de1de5f7df5.jpg)

Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2086139/RPCS3.log.gz)

**Comment by isJuhn** [comment]
post log

**Comment by MsDarkLow** [comment]
I'm an idiot, here.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2086130/RPCS3.log.gz)

**Comment by MsDarkLow** [comment]
Haven't tested in a long while and only tested again recently, doesn't seem to be happening anymore.
Closing the issue.
