### ISSUE TITLE
Ni No Kuni - Cutscenes can't be watched with ASMJIT recompiler (Linux)

### ISSUE THREAD

**Issue by BlackLotus** [RPCS3/rpcs3#4726]
Tested on 182259e4a51208d64da4179248f77b4e6af475e5, 72574b11ffe1e6f13213cbcfe46f4694f80c7bd5 and dde4a9c6e72016f08fb188dc3902d9e401b2cee8 (and some in between).
Thought that it should have worked in one of the latter since #2930 solved some problems with the cut-scene, but no version worked for me.
I can't even begin watching the first cut-scene the loading logo in the right corner just stops rotating.
```
U {PPU[0x1000000] Thread (main_thread) [0x002076dc]} sceNp TODO: sceNpManagerUnregisterCallback()
U {PPU[0x1000000] Thread (main_thread) [0x001fc7a0]} cellNetCtl TODO: cellNetCtlDelHandler(hid=0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0003554c]} 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [2]
```
are the last lines printed in the log. Selecting interpreter mode instead of ASMJIT works thought and the same lines as above are printed.
I tested it on 2 different archlinux systems (intel and amd cpu) compiled from git and also with the appimages. (for lack of windows or mac I couldn't test there)
No other setting combination with the asmjit I tested worked. Jumping to an older release like a36acf49 works, but with #2930 still affecting the game.
It seems like this commit be5c18cc859f5274b03e9a0a9c499089c03d1a63 +-1 caused the regression.
Going now to bed will post tomorrow more

**Comment by Megamouse** [comment]
https://github.com/RPCS3/rpcs3/issues/4589

**Comment by BlackLotus** [comment]
Hot damn didn't see that somehow even thought I searched
