### ISSUE TITLE
LEGO Star Wars 3: The Clone Wars [BLUS30540]: Graphical Glitches

### ISSUE THREAD

**Issue by creeperjedi** [RPCS3/rpcs3#4734]
All previously mentioned graphical issues have been fixed and this issue is now closed. If I find any more I will reopen the issue, or if you find any feel free to open a new issue or comment below. 

<s>LEGO Star Wars 3: The Clone Wars has some graphical glitches that I can't begin to explain. They consistently appear when starting a new game, loading a save, and ingame.

Settings:
I tried every combination almost every combination of setting I could think of, but they either didn't fix the glitches, or they prevented me from getting ingame.

Log:
Using Master (rpcs3-v0.0.5-6926-53ca2526): [LEGO Star Wars III Graphical Glitches.log.gz](https://github.com/RPCS3/rpcs3/files/2088221/LEGO.Star.Wars.III.Graphical.Glitches.log.gz)

RenderDocs:
They're too big to upload to GitHub so you can download them at: https://filehost.net/a2a9ca007a83e2e1

Specs:
Windows 10 x64 v1709 (OS build 17134.48)
Intel Core i7-4770
NVIDIA GeForce GTX 745
8 GB (2x4GB Dual Channel) DDR3 1600MHz RAM
<hr>
Glitch 1 - Weird grey streching accross the arena: (Fixed - See below)
<details><summary><s>Image:</s></summary><img width="641" alt="lego star wars iii graphical glitch 1" src="https://user-images.githubusercontent.com/38361979/41206157-c4c29f32-6ccd-11e8-82c0-4b032af15ec9.png"></details>
<hr>
Glitch 2 - Parts of limbs strech ouside of some characters (exploding vertices?): (Fixed - See below)
<details><summary>Image:</s></summary><img width="641" alt="lego star wars iii graphical glitch 2" src="https://user-images.githubusercontent.com/38361979/41206158-c6d05b16-6ccd-11e8-851a-19b13b820195.png"></details>

**Comment by creeperjedi** [comment]
Checked with Master (rpcs3-v0.0.5-7428-cc846eb6) and saw that Glitch 2 is now fixed (though I don't know exactly which PR fixed it)
<img width="641" alt="fixed" src="https://user-images.githubusercontent.com/38361979/46587339-18192000-ca59-11e8-8c7f-cef21b5bff0f.png">

**Comment by creeperjedi** [comment]
Just checked with Master (rpcs3-v0.0.5-7594-9717e19b) and saw that Glitch 1 is now also fixed (though I, again, don't know exactly which PR fixed it)
<img width="641" alt="arena graphics fixed" src="https://user-images.githubusercontent.com/38361979/50377539-f9a0da80-05ec-11e9-85a2-01c8fd1830be.png">

**Comment by isJuhn** [comment]
Can this issue be closed or are there more graphical glitches you'd like to report?
