### ISSUE TITLE
Metal Slug 3 [NPEB02252] Regression after 0.0.5-ae27454c

### ISSUE THREAD

**Issue by amayra** [RPCS3/rpcs3#4736]
Metal Slug 3 freezes and RPCS3 crashes as soon as close the game window 
this is my logfile : https://file.io/fzhSKw
it doesn't matter which option i use to encounter this issue as long as i use DX12 and this last build 0.0.5-ae27454c i try it and work fine to me without any problem with solid 30fps in 720p
my system specs : 
i7-3770
Intel HD Graphics 4000 (this GPU does not support Directx 12 but i still can lunch some game )
windows 10 

i wish to play with MS3 in iGPU until my new GPU arrived 
ps : you should change DX12 to Software renderer or something and keep it even if you do not maintain it anymore i was happy to see this renderer work

edit : i used last build to tested v0.0.5-c27604ba

**Comment by amayra** [comment]
i know that but is broken now too

**Comment by amayra** [comment]
look like OpenGL and Vulkan are not affected with this only D3D12
and this all happend after this pull: https://github.com/RPCS3/rpcs3/pull/4505 
[RPCS3 - Copy.log](https://github.com/RPCS3/rpcs3/files/2092477/RPCS3.-.Copy.log)

**Comment by AniLeo** [comment]
Then it's not relevant, there's a general issue for D3D12 issues at #2896

D3D12 render is not being maintained anymore, it rarely gets changes.
