### ISSUE TITLE
戦国バサラ4：皇

### ISSUE THREAD

**Issue by tghuaerzi** [RPCS3/rpcs3#4738]
[
![5](https://user-images.githubusercontent.com/39900736/41221063-b522cd04-6d95-11e8-9781-dad8227be623.png)
](url)
can not

**Comment by tghuaerzi** [comment]
can not  see the 2P

**Comment by AniLeo** [comment]
But you can see the guidelines. Don't post in the issue tracker if you don't know what you're doing.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
