### ISSUE TITLE
RSX: NV3089_IMAGE_IN: Invalid dimensions or scaling factor.

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#4747]
**Genji: Days of the Blade-(Demo)**
![bez tytulu1](https://user-images.githubusercontent.com/38318848/41300087-3210df3e-6e65-11e8-8e65-6d323aa571f8.png)
`E {rsx::thread} RSX: NV3089_IMAGE_IN: Invalid dimensions or scaling factor. Request ignored (ds_dx=1048576, dt_dy=4293918720)`

`F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsx_cache.h:105)`

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2094670/RPCS3.log.gz)

-----------------------------------------------------------------------------------------------------------
**Atomic Ninjas-(Demo)**
![bez tytulu2](https://user-images.githubusercontent.com/38318848/41300287-9678e552-6e65-11e8-8950-ef672d96cc8d.png)
`E {rsx::thread} RSX: NV3089_IMAGE_IN: Invalid dimensions or scaling factor. Request ignored (ds_dx=1048576, dt_dy=4293918720)`

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2094676/RPCS3.log.gz)

**Comment by miguel-nunes** [comment]
This kind of problem occurs to Macross 30 too. And the symptoms are the same

**Comment by elad335** [comment]
Fixed by #5381 
![image](https://user-images.githubusercontent.com/18193363/49334870-39981300-f595-11e8-9c83-6ba634067131.png)

Send log and report in case its not fixed.
