### ISSUE TITLE
rpcs3.exe - System Error (can't find vulkan-1.dll)

### ISSUE THREAD

**Issue by AkagiShiroe** [RPCS3/rpcs3#4753]
![test](https://user-images.githubusercontent.com/14356240/41370311-3e23be18-6f82-11e8-9b3e-4d233c179f05.png)
rpcs3-v0.0.5-6694-25ec899c_win64

**Comment by AniLeo** [comment]
This is not the place for support, ask for help in the support channel if you need in order to reinstall drivers / install Vulkan libraries if needed. 

Furthermore, you're using an old build.

**Comment by AkagiShiroe** [comment]
so i needed vulkan libraries? since i only have OpenGL 4.x support here.. not VK
