### ISSUE TITLE
Games don´t boot after #4733

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#4758]
After #4733 All games shows: 

 F LDR: class std::out_of_range thrown: invalid vector<T> subscript

Can´t boot any game since this PR, all previous builds works ok.

**Comment by scribam** [comment]
Fixed by #4757

**Comment by AniLeo** [comment]
Closing as fixed by #4757 . If issue persists with it, ping and it will be reopened.
