### ISSUE TITLE
Demon's Souls - keeps freezing

### ISSUE THREAD

**Issue by Rozzemak** [RPCS3/rpcs3#4759]
(You can find my specs in log file.) 
So, I tried Demon's Souls month ago, and it was perfectly playable for me (30fps constantly).
(tutorial level + boss + nexus)
Obviously my CPU is not capable of that big castle level after tutorial... but for like past 4 commits,
I can´t can´t be in-game for more than 1 minute. Game will freeze at 10-14 fps and never unfreezes.
This does not happen with SPU LLVM Recompiler, only with ASMJIT. (With LLVM, I can´t get past first bonfire.) (Vulkan || OpenGL does not matter, Game will always crash.)
If anybody wants, I could find first commit, that does not have this issue for me.

![demonsoulsfreeze](https://user-images.githubusercontent.com/28568671/41463112-8c14847c-7095-11e8-98c0-8a4124b466bc.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2105655/RPCS3.log.gz)

**Comment by Asinin3** [comment]
Duplicate of https://github.com/RPCS3/rpcs3/issues/4568

**Comment by Rozzemak** [comment]
Sorry.
