### ISSUE TITLE
Last of Us (BCES01585) crashes after first launch

### ISSUE THREAD

**Issue by kirugan** [RPCS3/rpcs3#4765]
I've tried to run Last of Us game on fresh RPCS3 install, it was ok. But subsequent launches of game crash even though i delete llvm or shader cache.
RPCS3 version: RPCS3 v0.0.5-6953-903da117e
Game settings: default, no customization
CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz | 4 Threads | 23.98 GiB RAM | AVX
OS: win 10 pro (version 1803)
Here are log files:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2108146/RPCS3.log)
[TTY.log](https://github.com/RPCS3/rpcs3/files/2108147/TTY.log)

**Comment by BreakBB** [comment]
The compatibility list lists it only as [Intro](https://rpcs3.net/compatibility?g=the+last+of+us).

Even though someone on the [forum](https://forums.rpcs3.net/thread-180731-post-298033.html#pid298033) says you can get ingame if you have a savefile.

**Comment by kirugan** [comment]
Well, in my case there is no intro just an error during a launch =)

**Comment by kd-11** [comment]
This is no longer an issue.
