### ISSUE TITLE
Hatsune Miku: Project DIVA F 2nd [BLUS31431]: incorrect transparency

### ISSUE THREAD

**Issue by vietnam13231** [RPCS3/rpcs3#4773]
Incorrect transparency that happens everytime, no matter the settings. Tried with both Vulcan and OpenGL. Visible mostly in songs "Akatsuki Arrival" and "Glory 3uzi9".
Used build: RPCS3 v0.0.5-6957-af62c92b7 Alpha | HEAD
My specs:
-OS: Windows 10 x64 v1709 build 16299.371
-CPU: Intel i5-4690
-GPU: Nvidia GeForce GTX1080
-RAM: 8 GB (2x4GB Dual Channel) DDR3 1600MHz RAM

Comparison photos:
Original:
![pdf2nd transparensy correct](https://user-images.githubusercontent.com/16107604/41537134-d2955fc4-7307-11e8-8262-787b592565a1.jpg)
Emulator:
![pdf2nd transparensy glitch](https://user-images.githubusercontent.com/16107604/41537135-d2f331ee-7307-11e8-9d3b-7dbebee5273f.jpg)

Edit:
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2120933/RPCS3.log.gz)

**Comment by allens39** [comment]
Simply a bug and without uploading the log this doesn't do us much good...

**Comment by Xequiel** [comment]
Have you solved it?

**Comment by vietnam13231** [comment]
How have I not noticed that when I was checking if there was a thread like that already...? I went page by page checking it out... Ok, closing, because partial duplicate.
