### ISSUE TITLE
Regression: Backbreaker [NPEB00592] Field textures do not display correctly on Vulkan now

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#4775]
Backbreaker gfx just become near perfect. Unfortunately, I just found out that the following commit broke Backbreaker field textures (never seen this issue before): 
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.5-77ce876b/artifacts
as part of this PR:
https://github.com/RPCS3/rpcs3/pull/4698

Perfect gfx on the commit right before:
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.5-60dde5d9/artifacts

Looks fine on OpenGL.

Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

![41504625-72a3ed38-71a9-11e8-98a9-52dd3de4e991](https://user-images.githubusercontent.com/20983844/41546305-2a5612b6-72d2-11e8-95e2-4108359f9b47.png)

**Comment by kd-11** [comment]
They're broken on OpenGL as well and I'm not sure its a regression (every build I have tried actually has this to varying degrees). Messed up textures are getting uploaded, with some parts interleaved with others, likely the developer tried to Z reorder block coded texels then realized it does not work properly and undid it with a second shuffle.

**Comment by legend800** [comment]
Thanks for the reply kd-11. 

While maybe not perfect, GFX do look "very, very descent" in OpenGL (doesn't need WCB or CPU blit) and they did look fine in one of the commits in that PR. I guess that one commit just really exacerbated the existing issue in only the one backend. So I'm not sure if that's a regression by definition as the root problem is always there but it was just made significantly worse. :P I'll update the title a little to reflect this. 

Just for some reference for this issue, here's a screenshot of OpenGL on today's master and Vulkan from the working commit in your PR (no repeating/corrupted texturing):

![40888331-8da4ed66-670a-11e8-88f7-2330bee740fc](https://user-images.githubusercontent.com/20983844/41574156-2847f512-7335-11e8-9823-2ff0d018c780.png)

![2018-06-18 20_10_09-window](https://user-images.githubusercontent.com/20983844/41574160-2bc80c2c-7335-11e8-8e03-836e47e7aff4.png)

**Comment by legend800** [comment]
@kd-11 Just FYI, this is still an issue on today's mainline (9/4). Let me know if there's anything else I can provide.

**Comment by legend800** [comment]
Checked out today's master after all the rsx PRs were merged. Looks like using CPU blit helps this specific issue now, but breaks other things. Here's the latest:

OpenGL default: Looks perfect, except for 1 issue - field colors get broken after ~3 stages (cache issue I guess)
OpenGL WCB: Missing menu gfx/broken field logo, field colors FIXED

Vulkan default:  Field texture pattern is broken (original issue here), field colors get broken after ~3 stages
Vulkan WCB: Field texture pattern is broken, missing menu gfx/broken field logo, field colors FIXED
Vulkan WCB+Blit: Field texture pattern FIXED, missing menu gfx/broken field logo, field colors FIXED

Let me know if there's anything else you need. We're getting closer here.... 

![broken field logo](https://user-images.githubusercontent.com/20983844/45993575-6505fb00-c044-11e8-8917-bf364f8ac302.png)
![missing menu gfx](https://user-images.githubusercontent.com/20983844/45993577-6505fb00-c044-11e8-93cd-4fba4432fb01.png)
![vulkan and blit](https://user-images.githubusercontent.com/20983844/45993578-659e9180-c044-11e8-96e0-cc992a17c23a.png)

**Comment by legend800** [comment]
Just a quick update on this issue: 
No change from above noted comments - Field textures are all garbled on Vulkan but look perfect on OpenGL. If you turn on WCB+Blit though, Vulkan field textures render fine. 

Due to recent changes (gt_fixes specifically), the game is fully playable except for speed - the additional options to correct Vulkan gfx bring it down to 70-80% speed. If Vulkan can display gfx properly, like OGL, without the need for WCB+Blit, the game would run at near 100% (just tested with them off) and we can finally move this fussy game over to the "Playable" category.

**Comment by legend800** [comment]
Fixed by build in https://github.com/RPCS3/rpcs3/issues/5708
