### ISSUE TITLE
Lollipop chainsaw unplayable since #4752

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#4781]
Game completely broken after PR #4752  "rsx: stuff " ( I completed the game using previous builds)

Rpcs3 completely hangs when a video scene begins "For example the intro video of the first mission in the prologue, the sniping scene in the beggining of the cathedral level, etc.

Using Vulkan backend. Windows 10 x64. 

Rpcs3 can´t create the "RPCS3.log.gz" as usually because I need to kill the process in order to exit the emulator, but I post the .log (I don´t know if it´s a complete log, but hope it helps)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2113348/RPCS3.zip)

**Comment by kd-11** [comment]
At least mention the graphics card and driver version when reporting driver crashes.

**Comment by Xcedf** [comment]
Gf 1070 397.96

**Comment by kd-11** [comment]
Are other UE3 titles affected as well? Might be something affecting all UE3 games on nvidia.

**Comment by kd-11** [comment]
Also, check if high precision Z has any impact on the crash, could help narrow down the cause as it uses a different (spec-compliant) path.

**Comment by LuismaSP89** [comment]
My graphics card is in the .log, Nvidia GTX 970. Using 398.11 driver version.

Also tested Guilty Gear XRD rev 2 (Uses UE3) and all works ok.

**Comment by Xcedf** [comment]
Triedmany settings and updated driver, and it turns out the game don't like scaling anymore, i only have this error with scaled resolution, native works fine

**Comment by isshininu** [comment]
Set resolution scale to 100% and try again.
I have a suspision that one of the latest PR somehow **might** broke resolution scale feature in some games.

**Comment by Xcedf** [comment]
Found out: game works with scaled image but only if Cpu Blit is ON, the beginning scene also requires WCB but it will made overall game slower, besides new WIP kd-11 changes fixes "zoom" issue for scaled resolutions in the beginning scene with WCB+CpuBlit ON

**Comment by Dagda52** [comment]
Yeah mine hangs while doing the multi kill screen like this one https://www.youtube.com/watch?v=7upYm3D_oTE&t=198s

GTX 1080 and i7 3770k

but forcing the cpu  blip option in the debug tab it fixes it

**Comment by LuismaSP89** [comment]
@Dagda52 Sorry for the dumb question, but... how do you enabled the debug tab? I searched and googled it with no results :S 

Thanks in advance.

**Comment by Dagda52** [comment]
@LuismaSP89 go to the guiconfigs folder and modify the file called CurrentSettings.ini 

inside find meta, looks like this

[Meta]
showDebugTab=false

change false for true

**Comment by LuismaSP89** [comment]
@Dagda52 Thanks a lot : ) I'll try that to fix the game using CPU blip.

Btw, the debug settings is a hide option for most users and only must be used by advance users to test. So I hope a proper fix for this other than enable this option.

**Comment by tabnk** [comment]
Same issue on Build-7536. Blit error mesaage but unable to capture log due to all application crash.  

Stuck at this screen.
![loli](https://user-images.githubusercontent.com/10874582/49324695-0d1cd080-f56e-11e8-80c0-fcc26a23aabf.png)

**Comment by AniLeo** [comment]
Issue very likely fixed, recent issue #5904 reporting on this game mentions the game is playable as of current builds and doesn't mention any of these freezes

If this is still an issue on current master, you can ping for reopening
