### ISSUE TITLE
Modern Warfare 2 Issue with starting Multiplayer

### ISSUE THREAD

**Issue by itsLollo1000** [RPCS3/rpcs3#4792]
Hello,

im new to this kind of scene but im trying to open Modern Warfare 2 BLUS30377 US version in RPCS3.
I want to start Multiplayer and when trying to open it i get this error:

RPCS3 v0.0.5-6977-8f1c36d79 Alpha | HEAD
Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz | 4 Threads | 7.91 GiB RAM | AVX+
S LDR: Updates found at /dev_hdd0/game/BLUS30377/!
S LDR: Boot successful.
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Recompiler Runtime (ASMJIT) initialized...
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built 698 functions.
U {PPU[0x1000000] Thread (main_thread) [0x024c3d0c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x024a6828]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x024a6828]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
U {PPU[0x1000000] Thread (main_thread) [0x02567c94]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
U {PPU[0x1000000] Thread (main_thread) [0x02567d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5
U {PPU[0x1000000] Thread (main_thread) [0x024a6890]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x024a6890]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000000] Thread (main_thread) [0x02567d88]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x024a6890]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x024a6890]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
S {PPU[0x1000000] Thread (main_thread) [0x024a6828]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
S {PPU[0x1000000] Thread (main_thread) [0x024a6828]} sys_prx: Loaded module: /dev_flash/sys/external/libresc.sprx
E {PPU[0x1000000] Thread (main_thread) [0x02741ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30377/USRDIR/packfile1.pak” [1]
E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed
E {PPU[0x1000000] Thread (main_thread) [0x0025f27c]} sys_mmapper: sys_mmapper_allocate_address(size=0x10000000, flags=0x20b, alignment=0x10000000, alloc_addr=*0x1ce4c14)
U {PPU[0x1000000] Thread (main_thread) [0x024a0830]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd00104b0, option=*0x0, waitForEvent=0)
E {PPU[0x1000000] Thread (main_thread) [0x024a67a0]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x024a67b0]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000000] Thread (main_thread) [0x024a67a0]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x024a67b0]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [2]
E {PPU[0x1000000] Thread (main_thread) [0x024a67a0]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000000] Thread (main_thread) [0x024a67b0]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [3]
U {PPU[0x1000000] Thread (main_thread) [0x024a6868]} sys_prx TODO: _sys_prx_unload_module(id=0x23008900, flags=0x0, pOpt=*0x0)
E {PPU[0x1000008] Thread (game_data_directory) [0x024a04b0]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLUS30377”, errDialog=0x0, funcStat=*0x710bf8, container=4294967295)
E {PPU[0x1000000] Thread (main_thread) [0x02742090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30377/USRDIR/ez_patch.cbo” [1]
E {PPU[0x1000000] Thread (main_thread) [0x0025f300]} 'sys_memory_get_page_attribute' failed with 0x80010002 : CELL_EINVAL [1]
E {PPU[0x1000000] Thread (main_thread) [0x0025f300]} 'sys_memory_get_page_attribute' failed with 0x80010002 : CELL_EINVAL [2]
E {PPU[0x1000000] Thread (main_thread) [0x0025f300]} 'sys_memory_get_page_attribute' failed with 0x80010002 : CELL_EINVAL [3]
S {PPU[0x1000000] Thread (main_thread) [0x024a6828]} sys_prx: Loaded module: /dev_flash/sys/external/libnet.sprx
S {PPU[0x1000000] Thread (main_thread) [0x024a6828]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x024a6828]} sys_prx: Loaded module: /dev_flash/sys/external/libhttp.sprx
U {PPU[0x1000000] Thread (main_thread) [0x024a5548]} sceNp TODO: sceNpBasicRegisterContextSensitiveHandler
U {PPU[0x1000000] Thread (main_thread) [0x024a5798]} sceNp TODO: sceNpCustomMenuRegisterActions
U {PPU[0x1000000] Thread (main_thread) [0x027b1bc4]} sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd0010258)
U {PPU[0x1000000] Thread (main_thread) [0x024a2fc8]} cellMic TODO: cellMicSetNotifyEventQueue
U {PPU[0x1000000] Thread (main_thread) [0x024a1560]} cellAudio TODO: cellAudioPortOpen(): CELL_AUDIO_PORTATTR_OUT_SECONDARY
E {PPU[0x1000000] Thread (main_thread) [0x024a67a0]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000000] Thread (main_thread) [0x024a67a0]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [2]
E {PPU[0x1000000] Thread (main_thread) [0x024a67a0]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [3]
F {PPU[0x1000000] Thread (main_thread) [0x002f7b94]} MEM: Access violation reading location 0x0

Can anybody help me????
Cause im trying to avoid buying a Jailbreak PS3 again and try to use this for SPRX Developing.

Thanks indeed

Im using a standard macbook pro mid 2014 with an i5 and no GPU

Kind Regards

lollo

**Comment by itsLollo1000** [comment]
why closed???

**Comment by itsLollo1000** [comment]
thanks......

**Comment by AniLeo** [comment]
Why ignore the guidelines? Thanks

**Comment by itsLollo1000** [comment]
>Why ignore the guidelines? Thanks

@AniLeo please Tell me what I did wrong and about those guidelines

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AniLeo** [comment]
The issue template begins with

**THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
https://forums.rpcs3.net
or our discord:
https://discord.me/RPCS3**

ends with

**Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use our forums for that.**

and the guidelines reiterate

**The GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. Requests for support or incorrect reports will be closed. If you are not sure whether the issue you want to report is an actual issue that is not yet known, please use the forums to submit such report.**

**Comment by itsLollo1000** [comment]
>The issue template begins with ...

@AniLeo
Okay thank you!!! I didn’t know that!!! 

Kind regards 

Gerner

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
