### ISSUE TITLE
Persona 5 BLUS31604 - SPU LLVM don't Boot Game Then RPCS3 Freeze/Crashes

### ISSUE THREAD

**Issue by kerojin180** [RPCS3/rpcs3#4798]
New RPCS3 LOG FILE (Finally got the log file before it got empty it's 50MB after extraction):-
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2130119/RPCS3.zip)

(commit hash) of RPCS3: rpcs3-v0.0.5-6990-78ef205b_win64

Issue details:-
The game works fine on ASMJIT but once i switch to LLVM after the precompiled shader of the game finish loading a black screen is presented and the whole app freezes/crashes and when i checked task manager it appears that the CPU usage of RPCS3 is 0%.

I checked around and i belive some people have SPU LLVM Working for this game like this guy:-
https://www.youtube.com/watch?v=UF2GlFDJNl0

The only difference is that in the video it's persona 5 NPUB31848

Screenshot of log changes seconds before crash:-
![rpcs3 error](https://user-images.githubusercontent.com/40502437/41798677-cfc07bfc-766e-11e8-95f1-fe83f9478fc0.PNG)

System Specs:-
OS: Windows 10 Pro 64Bit
CPU: AMD Ryzen 3 2200G with Vega Graphics
GPU: AMD Radeon Vega 8
RAM: 8GB 2400mhz (6.93GB usable)

Note: AMD Ryzen 3 2200G is an APU

Thanks in advance!

**Comment by AniLeo** [comment]
I can confirm it works with SPU LLVM on FX8350.
Furthermore, your log is empty.

**Comment by kerojin180** [comment]
how do i get the log to not be empty then ?
i will try looking into it then upload it if i find something.
i just hope that the crash part is not the reason it's empty

**Comment by resadent** [comment]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2129074/RPCS3.zip)
Crashes on my PC too. Exactly the same behavior. Core i5 4690k 4.2GHz, 16GB DDR3 1600MHz cl9, radeon rx 480 8gb, opengl driver.

**Comment by kerojin180** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2129077/RPCS3.log)

i was able to get the data from inside rpcs3 itself before the game finish precompiling shaders otherwise i can't get any data.

**Comment by kerojin180** [comment]
![rpcs3 error](https://user-images.githubusercontent.com/40502437/41798558-66f3fa2c-766e-11e8-9dfe-bfcb2c4c7fc9.PNG)

This image shows the rest of my log seconds before the crash happens (Captured by VIDEO recording)

**Comment by kerojin180** [comment]
In my issue on github i provided you with log file which precomplied shades
were still loading and a screenshot of the log seconds before rpcs3 crashes
cause the log don't seem to be saved because of the crash for some reason.

Thanks in advance

**Comment by wakka1** [comment]
SPU LLVM doesn't work for me. i7 7700

**Comment by raven02** [comment]
Also tried untick spu loop detection and thread scheduler also not helping on my i7 6700k . I wonder if only AMD cpu works only using SPU LLVM on P5

**Comment by kerojin180** [comment]
@AniLeo I updated the issue with as much information as I could

**Comment by makotech222** [comment]
Just want to add, i'm on a 6600k and it crashes for me as well. On latest artifact as of today.

**Comment by makotech222** [comment]
I cleared my llvm cache and it still crashed on start.

**Comment by kerojin180** [comment]
@AniLeo the log file is empty after the crash happens I don't think there is something I can do about that

**Comment by M220** [comment]
Persona 5 LLVM Crash Log (did it very fast after crash and compressed it so it's not empty)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2130111/RPCS3.zip)

**Comment by kerojin180** [comment]
@M220 good work

**Comment by M220** [comment]
Thanks ;)

**Comment by kerojin180** [comment]
@AniLeo I finally got the log file while it's not empty.
I updated the link in the post above and will upload it here again.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2130122/RPCS3.zip)

@M220 seems to have the same issue and uploaded his log file as well in the comments please check it out as well.

**Comment by AniLeo** [comment]
Oh.. you have a pirated version.

Someone has to open an issue on this with a clean one then.

**Comment by kerojin180** [comment]
@M220 u have a clean one?

**Comment by makotech222** [comment]
Mine is modded with the texture fix thing for higher resolutions. Also have a patch.yaml for 60 fps and skip intro.

**Comment by kerojin180** [comment]
@makotech222 if your persona 5 is not a pirated version please make a new issue as ani said

Thank you

**Comment by AniLeo** [comment]
If it's modded it also doesn't count

**Comment by kerojin180** [comment]
@AniLeo is it worth changing to SPU LLVM
I noticed earlier that the video was released by you.

I mean how much performance difference did you get?

**Comment by kerojin180** [comment]
@makotech222 how you got the texture fix? I need that too my gpu can manage high resolutions without performance issue.

**Comment by M220** [comment]
It's fixed in #4816 ( though, it's not merged to master :] ) so there's no need to open a new issue anymore

**Comment by kerojin180** [comment]
@M220 I tried before after that update but it wasn't working I tried clearing spu and llvm cache this time

**Comment by M220** [comment]
Yes, maybe it's your driver fault or something :D

**Comment by M220** [comment]
Try a Fresh Install and/or update your drivers and then retest ( try different settings too but if that not solved your problem then you have to wait for an update from neko )

**Comment by kerojin180** [comment]
@M220 thanks a lot for your help BTW what version u used?

**Comment by M220** [comment]
This version :
https://ci.appveyor.com/api/buildjobs/frlx4yax6mv2g1np/artifacts/rpcs3-v0.0.5-9c768625_win64.7z 😁

**Comment by kerojin180** [comment]
@M220 thanks a lot it's working fine with this version

**Comment by ZhimouYang** [comment]
Can anyone help me out, please? I just downloaded persona 5 and the RPCS3 yesterday. It kept showing a black screen when I tried to open it. My device is RAM 8GB ,GTX 1050 2GB , Intel i7, windows 10 64bits. Thanks!

**Comment by RainbowCookie32** [comment]
Don't spam issues to ask for help. Ask on the proper places, like the help channel on our Discord server https://discord.me/RPCS3
