### ISSUE TITLE
SRW Dark Prison : Battle Artifact (Nvidia Only)

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#4799]
Tested on i7-6700k with GTX 970 using vulkan backend. (DX12 and GL also same artifact)

![untitled](https://user-images.githubusercontent.com/3000282/41805122-9791e0f6-76d5-11e8-97c2-ceeced14ff5e.png)
![untitled](https://user-images.githubusercontent.com/3000282/41805317-70e9f984-76da-11e8-8f11-61dcdda6bee2.jpg)

**Comment by raven02** [comment]
Tested with Intel 530 . It works cool for both GL and Vulkan.

**Comment by raven02** [comment]
Just tried it on AMD GPU and confirm it is working fine.

**Comment by raven02** [comment]
Still happened in latest build

**Comment by kd-11** [comment]
Fixed in [this build](https://ci.appveyor.com/project/kd-11/rpcs3/builds/23947642)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/5860
