### ISSUE TITLE
God of war 3

### ISSUE THREAD

**Issue by saurabh185** [RPCS3/rpcs3#4809]
I have a pc with i5 7500 3.3GHz and a laptop with i7 7700hq 2.8GHz. Both have gtx 1060 graphic card.
But god of war 3 is loading on pc not on laptop.
I have done same settings.
Please help

**Comment by JohnHolmesII** [comment]
God of War 3 barely loads anywhere at all.

**Comment by kerojin180** [comment]
Hate to say this but I belive they will close this issue since this kind of problems are to be posted on the forums on their official website according to what was written before you write the issue.

**Comment by kd-11** [comment]
Use forums for discussing games. Github is a tracker for technical details.
