### ISSUE TITLE
dev_flash is not set when changing the virtual file system

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#4812]
It started with this commit https://github.com/RPCS3/rpcs3/commit/81e5f3b7f299942f56bcfdde54edd09c722b32d8 and by that change,the dev_flash folder was excluded from the virtual file system "changing the location"(you had to copy the dev_flash too along with the data folder if you want to try different rpcs3 version without overwriting your old one

Then the change was reverted https://github.com/RPCS3/rpcs3/commit/d62b0c88b0169f9f43b2d11695817986a410430a but with one problem left
Choosing a different folder for the virtual file system will set all the paths exept for the dev_flash(you have to set it separetly)

In the dev_flash tab it says "dev_flash_directory: Empty Path"

**Comment by AniLeo** [comment]
Can confirm it's still happening on current master

**Comment by AniLeo** [comment]
Still happens, not sure if it's intended
