### ISSUE TITLE
MEM: Access violation reading location 0xbfffff38

### ISSUE THREAD

**Issue by AdrianoPc** [RPCS3/rpcs3#4814]
F {PPU[0x1000000] Thread (main_thread) [0x006b4f84]} MEM: Access violation reading location 0xbfffff38
errors apears on all versions that have (Max LLVM Compile Threads) on the Emulation options.
same error OGL/Vulkan.....all gaes tested and random crash
RPCS3 v0.0.5-7006-3b8eab87d Alpha | HEAD
Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz | 4 Threads | 7.95 GiB RAM | AVX
Gpu R7 250x 2gb 
Windows 7 64bits ultimate

**Comment by AdrianoPc** [comment]
whats is wrong?

**Comment by HenningJW** [comment]
You did not mention the game, you did not upload logs. Also this isn't a compatibility report tool, please use the forums for this.
Also with a short search you will probably find out that "MEM: Access violation reading location" are generic errors.

If the game you tested ran on an older version, please test which version broke compatibility and retest again.

**Comment by Emulator-Team-2** [comment]
@AdrianoPc 
@kd-11 
This regression is already reported but KD-11 don't care about it. :P
https://github.com/RPCS3/rpcs3/issues/4651

**Comment by xTheWhiteTigerx** [comment]
**SOLUTION:** Delete RPCS3 completely, then download it again. This issue is happening because the developers unfortunately did not do their homework or test nearly enough to learn the basic fact that _people update RPCS3_. When people update RPCS3 and drop the new version into the existing version's folder, it somehow messes up the installation. Not only is this problem extremely likely to occur with all RPCS3 users, there is zero mention of it on the front homepage or the download page.

I'm really disappointed in the developers for this one. This should never have been a problem.

**Comment by AniLeo** [comment]
Lmao, go to sleep, I update RPCS3 on a daily basis and never had this issue. 

Also, not only this issue is 9 months old at this point, but the issue was an actual regression and the parent issue mentions it was fixed last year.

You think people with an existing setup are constantly creating new setups with every new build?...

**Comment by xTheWhiteTigerx** [comment]
> Lmao, go to sleep, I update RPCS3 on a daily basis and never had this issue.
> 
> Also, not only this issue is 9 months old at this point, but the issue was an actual regression and the parent issue mentions it was fixed last year.
> 
> You think people with an existing setup are constantly creating new setups with every new build?...
> 
> Also, there's a submenu for Updating RPCS3 on the Quickstart Guide..

The fact of the matter is that this issue has occurred at least once, likely many more times, therefore it needs addressing. If RPCS3 has any special instructions for upgrading, they should be present on the homepage or more likely the download page. In fact, the instructions for upgrading should be even more prominent than the download page, as people update their existing installation far more than the initial download. An auto-update mechanism would solve this problem entirely but may be too difficult to code, so a more minor change to the software or website would be understandable.

**Comment by AniLeo** [comment]
Memory Access Violations are not an issue itself, they're a symptom of issues elsewhere. 
There are thousands of different issues that can cause them. If you got one, it doesn't mean it was caused by the same issue, and here it wasn't since this one was fixed a long time ago.
The auto update mechanism would do exactly what people do right now, replacing all files. All caches are version bumped when they become incompatible between versions to avoid issues.

Your issue is not "updating rpcs3 breaks existing data", it's something else. RPCS3 is designed to be updated by pasting all new files on top and replacing, and it always worked by doing so.

**Comment by juliancrack121** [comment]
hay solucion?

**Comment by elad335** [comment]
Better retest and repload log, good chances are that newer logs have more informative about this.

**Comment by plov92** [comment]
S {PPU[0x1000000] Thread (main_thread) [0x018f09ac]} sys_prx: Loaded module: /dev_flash/sys/external/libpamf.sprx
U {PPU[0x100002e] Thread (NoSyncThread) [0x018eff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x100002e] Thread (NoSyncThread) [0x018eff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x100002e] Thread (NoSyncThread) [0x018eff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x100002e] Thread (NoSyncThread) [0x018eff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
E {PPU[0x1000033] Thread (NoSyncThread) [0x016c5218]} SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [1]
E {PPU[0x1000033] Thread (NoSyncThread) [0x016c5218]} SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [2]
E {PPU[0x1000033] Thread (NoSyncThread) [0x016c5218]} SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [3]
S {RSX Decompiler Thread} RSX: New program compiled successfully
E {PPU[0x1000033] Thread (NoSyncThread)} SYS: Stat: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [x16]
U {PPU[0x1000000] Thread (main_thread) [0x018f1038]} sys_prx TODO: _sys_prx_unload_module(id=0x23038500, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x018f1038]} sys_prx TODO: _sys_prx_unload_module(id=0x23038400, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x018f1038]} sys_prx TODO: _sys_prx_unload_module(id=0x23038300, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x018f1038]} sys_prx TODO: _sys_prx_unload_module(id=0x23038700, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x018f1038]} sys_prx TODO: _sys_prx_unload_module(id=0x23038600, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x018f1038]} sys_prx TODO: _sys_prx_unload_module(id=0x23038800, flags=0x0, pOpt=*0x0)
S {RSX Decompiler Thread} RSX: New program compiled successfully
F {SPU[0x1000100] Thread (SPU Thread 1) [0x049a8]} VM: Access violation reading location 0x0 (unmapped memory)
E {PPU[0x1000000] Thread (main_thread) [0x00f0773c]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000004] Thread (_cellsurMixerMain) [0x0134be70]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000001] Thread (_gcm_intr_thread) [0x0195833c]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000002] Thread (_sys_MixerChStripMain) [0x013524c8]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000006] Thread (NoSyncThread) [0x00ab170c]} SYS: 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x1000007] Thread (FrameSynchronizerThread) [0x01284464]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000004] Thread (_cellsurMixerMain)} SYS: Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x75881]
E {PPU[0x1000000] Thread (main_thread)} SYS: Stat: 'cellPadGetData' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [x43167]
E {PPU[0x1000004] Thread (_cellsurMixerMain)} SYS: Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x351186]
E {PPU[0x1000000] Thread (main_thread)} SYS: Stat: 'cellPadClearBuf' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [x43167]
E {PPU[0x1000005] Thread (NoSyncThread) [0x00aa9878]} SYS: 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x1000002] Thread (_sys_MixerChStripMain)} SYS: Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x607072]
E {PPU[0x1000008] Thread (FrameSynchronizerThread) [0x01284464]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000009] Thread (UpdateResourceInFrustumThre) [0x01284464]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000a] Thread (UpdateResourceInFrustumThre) [0x01284464]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000003] Thread (_sys_mixerSurBusReq) [0x0134a680]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000039] Thread (DocMarathonWorkerThread) [0x01284464]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100003a] Thread (ManageParticleTask::StepSup) [0x018e54ec]} SYS: '_sys_lwmutex_lock' failed with 0x00000000 : 0 [1]

**Comment by Cervoxx** [comment]
This is not a log file

**Comment by plov92** [comment]
But the same error as OP. Where is the log file?

**Comment by Cervoxx** [comment]
https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support

**Comment by AniLeo** [comment]
Locking as off-topic since it's being used to ask for support, moreso with unrelated issues.
