### ISSUE TITLE
cellGameDataCheckCreate2 overwrites game data param.sfo with useless/empty data

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#4823]
cellGameDataCheckCreate2 overwrites game data param.sfo with useless/empty data.
This leads to failed boots in games like LAIR due to an empty title_id in Emu.Load() after an update was detected.

right: before
left: after
![image](https://user-images.githubusercontent.com/23019877/41946219-8de0fa0e-79b1-11e8-809a-815c428bd072.png)

**Comment by TheCrazyChopper** [comment]
Hi i have this error when trying to boot a game. someone please help. (and admin before u remove for offtopic. this isnt off topic
![image](https://github.com/user-attachments/assets/1e5f6288-4c2c-4caa-afcb-5ba4f608975a)

**Comment by Jonathan44062** [comment]
@TheCrazyChopper Stop spamming messages here, if you need help, go to the Discord server, Github is not for support
