### ISSUE TITLE
Bulletstorm [BLES01134] Access violation

### ISSUE THREAD

**Issue by alexsilva** [RPCS3/rpcs3#4826]
Regardless of configuration always fails with the error below

`(RenderingThread) [0x009d16d8]} MEM: Access violation reading location 0x10`

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2142727/RPCS3.log.gz)

**Comment by AniLeo** [comment]
If it's a regression, you need to specify in which build it regressed

**Comment by alexsilva** [comment]
@AniLeo Always test the latest version available for Windows (v0.0.5-7018 Alpha [2018-06-27] ).

**Comment by JohnHolmesII** [comment]
@alexsilva not which build you found the problem on, which build was the FIRST one that stopped working.

**Comment by alexsilva** [comment]
According to quickstart: https://rpcs3.net/quickstart

> For Windows users, download the latest build and drag and drop all files into your RPCS3 root directory, replacing all files when prompted.

How to test one by one will be unfeasible for me. I downloaded the latest version available, made the necessary settings and with that the game returned to work.

At least it is working with the latest version but this model update caused this problem.

**Comment by Emulator-Team-2** [comment]
@alexsilva 
Change resolution to 1280x720 (Recommended).

**Comment by AniLeo** [comment]
Obviously you dont' have to test one by one, you do a binary search, go back month by month, then week by week, then half week, then day

**Comment by alexsilva** [comment]
@Emulator-Team-2 Changing the resolution caused the game to load again.
