### ISSUE TITLE
Freezing Issue with tales of graces using vulkan or openGL

### ISSUE THREAD

**Issue by Fake2406** [RPCS3/rpcs3#4836]
The games is crashing no matter API I used opengl and vulkan. I tried all the settings possible to this game and other tales game like xillia 2 but same issue I think other game must have same problem. 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2151631/RPCS3.zip)

**Comment by Zangetsu38** [comment]
hmmmm all is missing lol

**Comment by Fake2406** [comment]
I'm so sorry. I'm new to github so I'm still getting to know it :)

**Comment by AniLeo** [comment]
The log doesn't show any crash. Furthermore, it hints to you using an undub, non-clean version of the game. 

Closing this issue for lack of information, information inconsistency (title says it's a freezing issue, description says it's a crash issue), and use of modified game copy.

When reporting issues, please provide as much detail as possible, while following the guidelines.
