### ISSUE TITLE
NieR (Gestalt, USA ver.) - Popola and Devola are invisible ~ Boss fight only

### ISSUE THREAD

**Issue by knzchaos** [RPCS3/rpcs3#4837]
During Devola and Popola's boss fight, they appear invisible.

Video on issue: https://www.youtube.com/watch?v=VGZ9Iij4GrM
PS3: https://youtu.be/qq5dVHY4Es0?t=3m55s

Emulator settings: All default + 200% resolution scale + Write color buffers + 16xAF ()
PC Specs: Core i5 6500, GTX1060 6GB, 16GB DDR4, Windows 10 Pro x64
RPCS3 0.0.5-7018-345f92ab

Issue persists on both OpenGL and Vulkan.

**Comment by jjsat** [comment]
With the European version they are visible for me when using Vulkan.
![grafik](https://user-images.githubusercontent.com/1445782/42135223-187c002a-7d48-11e8-9e3c-6d087a49a519.png)

My specs are the same except for an i7 6700k and an AMD R9 380 (driver 18.6.1).

With OpenGL they are not visible, but the draw calls are there when capturing with renderdoc. They seem to be discarded or transformed away in the vertex shader. The capture is quite large but I can upload if necessary.

**Comment by jjsat** [comment]
Ok. Here is a capture that should look exactly like the screenshot above. I cannot verify that though because replaying with OpenGL immediately crashes after creating the game window and replaying with Vulkan displays this
![grafik](https://user-images.githubusercontent.com/1445782/42137480-4dcc5d22-7d6d-11e8-9ef0-2f4862a667e1.png)

This a 7z file, the extension is just to make github happy:
[capture.zip](https://github.com/RPCS3/rpcs3/files/2153055/capture.zip)

**Comment by knzchaos** [comment]
How do I capture? I can't find this option in the emulator.

**Comment by knzchaos** [comment]
Thanks. After pressing the RSX Capture button my game just froze and it's been like this for 20~ minutes, is this how it's supposed to work?
There were a few lines written in the log though:
```
E {rsx::thread} RSX: Cannot invalidate a currently bound render target! x2
E {SPU[0x2000000] Thread (CellSpursKernel0) [0x1f620]} SPU: GETLLAR took too long: 10 x3
E {SPU[0x2000000] Thread (CellSpursKernel0) [0x1f620]} SPU: GETLLAR took too long: 11
```

Here is my save file (the middle one ingame is the one right before this fight) - rename to .7z:
[Nier save.zip](https://github.com/RPCS3/rpcs3/files/2153283/Nier.save.zip)

**Comment by kd-11** [comment]
They show up on AMD but not on NVIDIA. OpenGL seems to have another unrelated bug, a fix is likely to be ready soon for both.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/4869. I had no evidence that non-2D vertex textures were possible in the G70 era, so I had left it hardcoded. It also seems to not support any filtering, seemingly only supporting point sampling only which fixes the openGL error as well.

**Comment by Illynir** [comment]
Works for me without problem.

**Comment by nitrohigito** [comment]
@knzchaos because you are using an older version which doesn't contain the fix

**Comment by knzchaos** [comment]
Am I? I just downloaded the latest one from 10 hours ago from the website (#4866)

**Comment by Illynir** [comment]
Website is Master, The fix is in a PR for now, not merged in MAater for now.

KD gave you the PR: https://github.com/RPCS3/rpcs3/pull/4869

**Comment by nitrohigito** [comment]
Yes. The fix hasn't been rolled out to master yet. You'll need to grab the correct version from the project's [appropriate AppVeyor page] to test it. (https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.5-8ba10462/artifacts)

**Comment by knzchaos** [comment]
Sorry, I thought the latest website version already had the fix.
Thanks for the heads up.
