### ISSUE TITLE
Skate 3 Replay Editor Regression

### ISSUE THREAD

**Issue by theoldsport** [RPCS3/rpcs3#4838]
**Description** - After reaching ingame and pressing **Select** (entering the replay editor), the game hangs, occasionally shows some graphical errors, and spams the log with FIFO errors or semaphore locks. No combination of settings, including debug settings, seem to affect the issue. Present in Vulkan and OpenGL

**Last functional build** - rpcs3-v0.0.5-6831-f8a0be8c_win64 (Performance enhancement - Vulkan memory allocator (#4635))

**Culprit PR** #4611

Can be reproduced on any build since the noted PR.

**Log** - [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2152735/RPCS3.log.gz)
(Log not from master, but output is the same)

**Comment by theoldsport** [comment]
Whoops looks like I should post this info here #4611

**Comment by Megamouse** [comment]
no
here:
https://github.com/RPCS3/rpcs3/issues/4651

**Comment by theoldsport** [comment]
Beat ya
