### ISSUE TITLE
Feature request: Option to disable double click fullscreen and lock mouse cursor in the window

### ISSUE THREAD

**Issue by counter185** [RPCS3/rpcs3#4843]
(sorry for bad english)
CS:GO is a game that supports keyboard and mouse on PS3, and it got ingame only recently. While kb+m work on RPCS3, mouse inputs will only work when the cursor is in the game window. This could be fixed by adding an option to lock the mouse cursor to the window. 

Another thing is that one-tapping (shooting in short delays so you always hit the target) is literally impossible on RPCS3, because of the double click fullscreen feature. The best solution here would be to add an option to disable it (leaving Alt+Enter as the only fullscreen shortcut).

**Comment by isshininu** [comment]
You can disable doubleclick in RPCS3 already.

**Comment by counter185** [comment]
how the fck did i not notice this already
