### ISSUE TITLE
Issue with TSX on Haswell CPUs

### ISSUE THREAD

**Issue by Syrusse** [RPCS3/rpcs3#4847]
Hello, first of all, I want to thank a lot the developpers who heard our complaint about TSX for minority of us who have an old microcode with an old CPU, unfortunately, TSX never worked after the merge of Megamouse (https://github.com/RPCS3/rpcs3/pull/4766) and the old way to force it with an hex editor doesn't work either, I don't know if TSX is really working or not and unfortunately I'm unable to tell it by reading the code, I think something is wrong as it says that TSX is disabled even though I've "forced" it as you can see here https://imgur.com/a/CdMikac, I'm 100% that TSX is enabled so I'm sure that the issue is comming from the emulator itself, here's the log :  
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2160884/RPCS3.log.gz)
Here are my specs : GTX 770, 8 go RAM DDR3, I7 4770
Thanks in advance for taking care of this issue :)

**Comment by AniLeo** [comment]
Show CPU-Z screenshot

**Comment by Megamouse** [comment]
`·W 0:01:37.558251 TSX forced by User`
means you definitely have it enabled.

the ` | AVX+ | TSX disabled by default` means you have TSX but your CPU model usually has it disabled.

The fact that you can force it already means you can use it

**Comment by AniLeo** [comment]
Closing as there's no issue here then
