### ISSUE TITLE
Tiger Woods 14 stuck on intro with huge log file

### ISSUE THREAD

**Issue by bigmanon** [RPCS3/rpcs3#4853]
here the huge log file
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2171509/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Just removed comment on #4844 regarding this issue and log a few minutes ago for being a pirated copy.
It's looping on sys_fs_readdir, can't trust if it's an emulator issue with a pirated copy, needs to be reproduced on a clean one.

**Comment by bigmanon** [comment]
Dont know what you're talking about this is clean one
