### ISSUE TITLE
Normal to receive 1,000's of draw calls???

### ISSUE THREAD

**Issue by bigmanon** [RPCS3/rpcs3#4854]
![tigere](https://user-images.githubusercontent.com/40898617/42393591-d5db5758-8124-11e8-9810-9a60a46b89de.PNG)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2171513/RPCS3.zip)

**Comment by bigmanon** [comment]
bro what going on these are clean ones

**Comment by AniLeo** [comment]
Read the Guidelines and don't spam the Issue Tracker
