### ISSUE TITLE
Conan [BLES00076] soft locks on data load screen 

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#4856]
Broken on new mainline builds with a few issues. I think it happened in the past week or two. Clearing caches doesn't help.

Issues:
1)  Soft locks frequently on the long load screen. 50/50 if it makes it to 100% load, where as before this was a sure thing. 

<strike>2)  [Update: Workaround available]  When it does makes it past the loading screen, it will always crash if using Vulcan trying to load gameplay with this:
F {rsx::thread} class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST) (in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:1083)</strike>

<strike>3)  [Update: Improved] On OpenGL, you get into gameplay but will run at only 2 fps.</strike>

Working fine before:
https://forums.rpcs3.net/thread-197776.html

===============

UPDATES:
#2 is fine with WCB+CPU Blit, but hangs if they're not on (so still a regression). Fine at 100% resolution also. Issue is triggered at higher upscale resolutions and no WCB+Blit. kd has since fixed 5/18/19.

#3 is a better now

=================

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2172270/RPCS3.log.gz)

**Comment by Parthorisian** [comment]
Build77084(pr4820) and later [can boot](https://imgur.com/4OJhdzS) USA version [unbrokenConan_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2185002/unbrokenConan_RPCS3.zip)

**Comment by legend800** [comment]
@kd-11 Just FYI, this is still an issue on today's mainline (9/4).

**Comment by ruthan** [comment]
With 7338 its working with Vulkan, but broken colors are still there and its months..

**Comment by legend800** [comment]
No change here on even a newer build:
OpenGL: 2 fps
Vulkan: Driver error upon entering gameplay
Existing Issue: Missing textures/broken coloring

![2018-09-15 20_52_14-window](https://user-images.githubusercontent.com/20983844/45592712-def20200-b929-11e8-837d-b9ad78c7a904.png)

![opengl](https://user-images.githubusercontent.com/20983844/45592713-e0bbc580-b929-11e8-8b57-b73c294bc929.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2386274/RPCS3.log.gz)

**Comment by legend800** [comment]
Added another update to initial post.

**Comment by uaqlover** [comment]
it fix the game in this build or not ? 

https://github.com/RPCS3/rpcs3/pull/5675

**Comment by legend800** [comment]
Not quite. It still soft locks half the time on load and OpenGL only runs at half speed. The latter is not that big of a deal since Vulkan is full speed, so you can workaround this (like issue #2).

**Comment by uaqlover** [comment]
did it fix it in https://github.com/RPCS3/rpcs3/issues/5708 ?

**Comment by legend800** [comment]
#1 still the same - 50/50 soft lock on launch
#2 is fine with the workarounds
#3 OpenGL is 15 fps still (might have always been that way though)

**Comment by legend800** [comment]
Updated to cross out #2 and #3. Only Issue #1 persist which is where it'll freeze sometimes while loading data on this screen. 
![2019-05-18 17_17_07-FPS_ 30 04 _ Vulkan _ 0 0 6-5eeb3be8-tsx _ Conan  BLUS30069](https://user-images.githubusercontent.com/20983844/57976271-cfcbc400-7990-11e9-9ee1-ae26c5ac08d6.png)

**Comment by legend800** [comment]
Seems fixed now. 6/6 boots in a row without a hang.
