### ISSUE TITLE
Lollipop chainsaw stops drawing to screen during certain effects

### ISSUE THREAD

**Issue by JustinSpedding** [RPCS3/rpcs3#4859]
During specific times of gameplay and cutscenes, the game stops drawing what it is rendering to the screen. Post effects such as blur are still applied. But, the image that they are applied to is just a still image. This happens in many cutscenes, and a lot during boss fights. For instance, it always happens when lightning strikes during the stage with Vikke. The first frame that it renders with this bug is then used for the rest of the game. So, if I start out the level looking at the entrance to the building, then that image will be displayed whenever lightning strikes, etc. for the rest of the time that the game is loaded. The interesting thing is that, by looking at the blur effects, I can see silhouettes of characters moving around. So, it is rendering the scene somewhere in memory in order to calculate which areas should be blurred. The rendered scene just doesn't make it to the screen.

Here is an example of it happening during a cutscene: https://www.youtube.com/watch?v=fOVROfsuueM

Here is the output in the main window: https://pastebin.com/ShN2vZsW

I am using rpcs3-v0.0.5-7077-f0a9799b_linux64
I run Linux Mint 19 with the nvidia 396.24 driver, i7-6700k processor, gtx 1080, 16GB of ddr4 ram

**Comment by JustinSpedding** [comment]
This is still an issue as of rpcs3-v0.0.5-7405-da6ce80f_linux64. Is there anyone looking into it?
In the final boss, this bug makes the level unplayable, despite the "Playable" rating in the compatibility db.

**Comment by kd-11** [comment]
Probably fixed by https://github.com/RPCS3/rpcs3/pull/5785

**Comment by kd-11** [comment]
Request to reopen if issue is still present.

**Comment by JustinSpedding** [comment]
I just tried it locally, and it works. Thank you so much for your work to fix this!
