### ISSUE TITLE
Game:Devil May Cry 4

### ISSUE THREAD

**Issue by PlayerWind** [RPCS3/rpcs3#4860]
System: Windows 7

Cpu: AMD A8-7600 Radeon R7 10

Gpu: Radeon HD 7700+CrossFire with a Sapphire

Ploblem E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed

And need Fast Intrepeter Fast for Boot

Log: http://ge.tt/6W2AKUq2

Screenshots:
![screenshot](https://user-images.githubusercontent.com/38998444/42421551-b1ccd3f2-82ad-11e8-9376-8a82326f4c44.png)

![screenshot2](https://user-images.githubusercontent.com/38998444/42421558-c83f6cd0-82ad-11e8-8520-8508e74bec8a.png)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
