### ISSUE TITLE
Battlefield: Bad Company Graphical Issue

### ISSUE THREAD

**Issue by stride21** [RPCS3/rpcs3#4862]
Battlefield: Bad Company gets an error 
"{rsx::thread} RSX: Could not gather all required slices for cubemap/3d generation" just before going ingame.

![battlefield bc](https://user-images.githubusercontent.com/37915864/42422388-b04298e4-82aa-11e8-81b5-f2cb05bcbe8f.JPG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2173950/RPCS3.log.gz)

**Comment by Asinin3** [comment]
Lots of games have this "error" the game is still ingame. Not really a real issue.

**Comment by stride21** [comment]
ok I'll close it.
