### ISSUE TITLE
Hatsune Miku: Project Diva F [BLUS31319] Models Not Showing as of 0.0.5-6917

### ISSUE THREAD

**Issue by Blinding-Awesomeness** [RPCS3/rpcs3#4864]
The character models are no longer showing in songs or on menus (but do appear in the Diva Rooms) for Hatsune Miku: Project Diva F [BLUS31319]. The models tested included default and DLC models of several characters. 

This began on version 0.0.5-6917-da9affb34 (#4698) and is still a problem on the latest builds (as of v0.0.5-7079-1c9769670, #4858). The models appear properly on the previous build, version 0.0.5-6907-fb20c27e7 (#4658) and below.

A visual example and logs from three builds are attached. Please let me know if you need any other information.

Specifications:
CPU: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz | 6 Threads
RAM: 15.95 GiB
GPU: GeForce GTX 1070 Ti
OS: Windows 10 Pro (x64) Version 1803

![v0 0 5-6907](https://user-images.githubusercontent.com/38484951/42423799-561110a2-82ce-11e8-9068-a598a991c565.PNG)

![v0 0 5-6917](https://user-images.githubusercontent.com/38484951/42423798-5279f3a0-82ce-11e8-905e-4ab6748376ff.PNG)

[RPCS3-v0.0.5-6907.log](https://github.com/RPCS3/rpcs3/files/2174109/RPCS3-v0.0.5-6907.log)
[RPCS3-v0.0.5-6917.log](https://github.com/RPCS3/rpcs3/files/2174110/RPCS3-v0.0.5-6917.log)
[RPCS3-v0.0.5-7079.log](https://github.com/RPCS3/rpcs3/files/2174111/RPCS3-v0.0.5-7079.log)

**Comment by Lemiru** [comment]
Just checked it and on vulkan everything works perfectly.
On OpenGL characters do not show up but only in menus. In songs they are perfectly visible. Another thing I noticed on OpenGL by accident is that prerendered background (like in for example "sadistic.music∞factory") are "broken" and are the only thing that is visible (except hud and notes)
![screen shot 07-08-18 at 11 07 pm](https://user-images.githubusercontent.com/25465452/42423998-32731e7a-8304-11e8-9e19-3fdb988a51b0.PNG)

**Comment by kd-11** [comment]
Confirmed. Its a regression on OpenGL only.

**Comment by Blinding-Awesomeness** [comment]
That must have been what was up with the songs. All the ones I checked used prerendered backgrounds. Thanks for confirming!

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/4866
