### ISSUE TITLE
Unresponsive Application

### ISSUE THREAD

**Issue by ParkerPompeii** [RPCS3/rpcs3#4865]
My RPCS3 Application is unresponsive. I have tried:

- Killing the process via Task Manager

- Run on Admin Mode

- Rebooting 

So far, no luck. I'm attaching the  [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2174513/RPCS3.log.gz) file here in hopes that one of you smart lads could help me out. Thank you.

**Comment by 13xforever** [comment]
Github is not for support questions. Please read the guidelines before opening an issue, and use discord or forums in the future.

**Comment by AniLeo** [comment]
Closing as this is a support request, and is not reporting a specific issue.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
