### ISSUE TITLE
GL / Vulkan: Arcania: The Complete Tale | Broken graphics

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#4868]
![bez tytulu](https://user-images.githubusercontent.com/38318848/42464629-f0f639c2-83a9-11e8-96ef-3d660452c977.png)

**[Video](https://youtu.be/ETKGJ5nMJzA)**

I uploaded ''RenderDoc capture'' because ''rsx capture'' doesn't work in this game. :P 

[Old renderdoc capture - Deleted.]

**[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2177289/RPCS3.log.gz)**
**[vp_analyser.zip](https://github.com/RPCS3/rpcs3/files/2177183/vp_analyser.zip)**

**Comment by kd-11** [comment]
Retest and update.

**Comment by Emulator-Team-2** [comment]
@kd-11 
Tested with the latest master build (0.0.6-7932) and with (rsx: Texture cache fixes # 5785)
 no change.

I upload only rdc capture from vulkan, because when capturing a frame with opengl, the driver crashes.
RSX Capture still doesn't work with this game.

[Vulkan]
![1](https://user-images.githubusercontent.com/38318848/55638071-a8e17600-57c6-11e9-9103-ada62536c023.png)
[OpenGL]
![2](https://user-images.githubusercontent.com/38318848/55638115-c0b8fa00-57c6-11e9-9d8b-16621d133189.png)

[RenderDoc v1.2]
[RDC Capture-Vulkan](https://drive.google.com/file/d/1-sFvVcDdNLJGh70tdKdjo73nDFQhX4SX/view?usp=sharing)
