### ISSUE TITLE
Tales of Vesperia crashes when unlocking costumes from snowboard mini-game.

### ISSUE THREAD

**Issue by Seroneiei** [RPCS3/rpcs3#4873]
Unlocking costumes after beating the Repede snowboarding mini-game causes the game to crash with "MEM: Access violation reading location". 
Happens in both Vulkan and OpenGL Renderer. LLVM and ASMJIT and interpreter(fast).
2500k @ 4.6ghz
16gb DDR3
R9 Nano Radeon Drivers: 18.4.1
Windows 10 Pro 10.0.17134 Build 17134
Translation patch and DLC installed

Crashes after this textbox:
![tovcrash1](https://user-images.githubusercontent.com/39671204/42571226-c8c388a6-8516-11e8-9a78-3a3465d40e66.JPG)

Freezes completely like this, but the music continues playing:
![tovcrash2](https://user-images.githubusercontent.com/39671204/42571233-d144f032-8516-11e8-90c9-bb39e44a2b83.JPG)

Screenshot of the error messages and version visible:
![tovcrash3](https://user-images.githubusercontent.com/39671204/42571257-df948cba-8516-11e8-925d-a215606bda5e.JPG)

Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2184423/RPCS3.log)

Save file right next to the mini-game:
[BLJS10053-SAVEDATA001.zip](https://github.com/RPCS3/rpcs3/files/2184425/BLJS10053-SAVEDATA001.zip)

Go left and down to the tents and talk to the guy, beat the mini-game in under 1 minute with the correct attachments equiped on Repede and you're supposed to unlock costumes but this freezes the game.

EDIT: Doesn't crash if you play as whichever character's costume you unlock. Weird.

**Comment by Realmantik** [comment]
I can say that this bug is gone for me. I beat the mini-game and got costumes and no memory errors. But now I able run this game only on OpenGL. Using Vulkan API gives me a bunch of fatal errors.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3383256/RPCS3.zip)

**Comment by Realmantik** [comment]
No, i was wrong. I retested and can conclude this bug is Vulkan related. Using Vulkan i got this bug.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3383642/RPCS3.zip)

**Comment by Realmantik** [comment]
This is no more a bug. Cannot reproduse. Tried on 0.0.12-10954 build. Standart settings.

**Comment by Realmantik** [comment]
Cannot reproduce on v0.0.14-11816-0012f393. https://www.youtube.com/watch?v=rFML1gx16YA

**Comment by Megamouse** [comment]
reported as fixed. reopen if the issue persists.
