### ISSUE TITLE
OpenGL/Vulkan Battlefield Bad Company Shader Issues

### ISSUE THREAD

**Issue by stride21** [RPCS3/rpcs3#4874]
The crash happens when you look in a certain direction while riding in the truck after the opening cutscene, if you look elsewhere you can avoid this crash.

![bad company 2](https://user-images.githubusercontent.com/37915864/42583297-4c0ce9f8-84f6-11e8-8317-dbf05175c166.JPG)

Here are some of the errors around when it happens:
 
E {rsx::thread} RSX: Src type 3 used, opcode=0x1, dst=0x1BA01BB s0=0x1BC01BB s1=0x1BB01BC s2=0x1BD0119
E {rsx::thread} RSX: BRK opcode found outside of a loop
E{rsx::thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 1)
E {rsx::thread} RSX: Src type 3 used, opcode=0x1, dst=0x1340137 s0=0x1370133 s1=0x13C013B s2=0x13C0137

[RPCS3 log.zip](https://github.com/RPCS3/rpcs3/files/2185192/RPCS3.log.zip)

**Comment by kd-11** [comment]
Classic heap corruption, rpcs3 ends up compiling trash and dies.

**Comment by stride21** [comment]
I also found another place where it crashes and seems to be the same issue. Also, found an E {rsx::thread} RSX: Depth texture bound to pipeline with unexpected format 0x9B so I think I'll open an issue on that soon.
[RPCS3log.zip](https://github.com/RPCS3/rpcs3/files/2185550/RPCS3log.zip)

**Comment by kd-11** [comment]
Those errors are not fatal. They cannot crash the emulator.

**Comment by stride21** [comment]
This issue is now fixed with #5076

**Comment by stride21** [comment]
Reopening the issue because it still seems to have shader issues but it just no longer crashes because of them.

**Comment by alexjjording** [comment]
W wee was on o look Ed d didjj try it re youn't see

**Comment by elad335** [comment]
Is it still an issue?

**Comment by kd-11** [comment]
Any update? Looks like a duplicate of the RSX desync metabug.

**Comment by stride21** [comment]
@kd-11 Its still an issue. I can post else where and close this issue if you want.

**Comment by Wizzy2018** [comment]
I have this issue too on Gran Turismo 5 RSX: BRK opcode found outside of a loop And when it happens the whole emulator Frezzes and stops.

**Comment by kd-11** [comment]
That is an obvious sign of emulator desynchronizing and RSX trying to process garbage.

**Comment by stride21** [comment]
This issue is fixed on master for both OpenGL and Vulkan.
