### ISSUE TITLE
RPCS3 hangs at the end of the playback of pre-rendered cutscenes in [BLUS30793, BLUS30196, BLJS10184]

### ISSUE THREAD

**Issue by micaelis72** [RPCS3/rpcs3#4875]
Guys,

All this worked fine, some of them are considered playable. From some PR in the last few months until now they stopped to work properly.

Follows the logs of the [BLUS30793], but the behavior are the same on those three games and I think some others that share the same framework.

[rpcs3-logs-1.zip](https://github.com/RPCS3/rpcs3/files/2186071/rpcs3-logs-1.zip)

I hope it helps to analyse and fix the problem. If you guys need more information, let me know.

Cheers!

**Comment by MADZEROPIE** [comment]
The same problem in the NieR Replicant

**Comment by AniLeo** [comment]
Closed as you mentioned it was fixed in #5310 

Update the issue and ping for it to be reopened if it's not the case
