### ISSUE TITLE
RPCS3 broken dll lead to unresponsive or frozen behaviour on resizing or full screen

### ISSUE THREAD

**Issue by Wheel-Of-Fate** [RPCS3/rpcs3#4878]
i made many tests i figured that the last working build was #4870 
rpcs3-v0.0.5-7088-a5d4e58d_win64
![1](https://user-images.githubusercontent.com/40186693/42727918-6404ce0c-87af-11e8-8636-666aa724e68a.png)

the issue started from #4872 
rpcs3-v0.0.5-7089-d3596fbc_win64
![2](https://user-images.githubusercontent.com/40186693/42727919-642fa35c-87af-11e8-85f0-7d1d8aa10ad0.png)

how i figured that dll files were broken?
the answer is simple i downloaded clean build without replacing RPCS3.exe
and i started to test and when i hit v7089 i knew the dll files were broken
i had to use dll files from build 7088 and i updated RPCS3.exe with latest build which is v7091 and it worked perfectly as you see in the first picture above
notes:
i used the test samples as well they were really big help
the issue happens on both renders Vulkan and OGL
I'm Using Windows 7 SP1 Ultimate x64

**Comment by Buzing** [comment]
This fixed my issue.

Win 10 , 1803 latest build.

**Comment by jobs-git** [comment]
I also experience the freeze described. When the screen is clicked on rpcs3, window stops responding.

Specs:
Win 10, Gtx 1060, Intel Avx cpu, D3 blus31437

**Comment by Psycho-A** [comment]
> Qt dlls changed externally between the two builds. The Qt build environment is now different than it was on 7088. Probably a regression that affects windows 7 only, we'll have to wait for other reports to be sure.

The same bug for me. GS window is now uncontrollable and system says it's not responding. 
Using Windows 7, Vulkan, nVidia card.

**Comment by kd-11** [comment]
There is a bug in qt 5.11.1 that is being fixed for 5.11.2. A workaround will be merged shortly.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/4885
