### ISSUE TITLE
Long pause after loading PPU LLVM modules

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4883]
From some last RPCS3 build about a week ago, I've noticed that 10-15 second pause (or freeze) happens after last PPU module loaded. It accompanies with high (but variable) CPU load, and nothing shows in the log/dialog windows. Here's the log piece that shows place where freeze happens. Is it related to new SPU experiments somehow?

```
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+15A7558-69C6A355B4E37502-nehalem.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+15E7580-A163FBA2CED7C8FF-nehalem.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+1627758-0349E61CADAAB085-nehalem.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+1667A20-AFE8CD476A82224B-nehalem.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+16A79F0-D5FAD2E4EBA30DBC-nehalem.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+16E7C78-AC4D78842DFB9170-nehalem.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+1727F18-070B790F8903AC98-nehalem.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+1767E30-A62154783C391C78-nehalem.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+17A8C58-67466E11A24FE2EF-nehalem.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+17E6930-9326437037A26E3D-nehalem.obj
--- FREEZE ---
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2-liblv2.sprx-6E56691FE33B8E4B-nehalem.obj
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Recompiler Runtime (ASMJIT) initialized...
U {PPU[0x1000000] Thread (main_thread) [0x01e5fe64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x01e600bc]} sys_prx TODO: _sys_prx_register_library(library=*0x1e626a0)
S {PPU[0x1000000] Thread (main_thread) [0x01e609ac]} PPU: LLVM: Loaded module v2-libsysmodule.sprx-E926430A8C1D5DCB-nehalem.obj
...
```

**Comment by miguel-nunes** [comment]
I've noticed the same and if you clean your PPU LLVM cache and recompile all the modules, you'll probably get something like this:
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+9570B8-44ED5E1DF1F26FC0-skylake.obj
E {PPU[0x1000000] Thread (main_thread)} LLVM: Writeable data section not supported!
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+9961E0-D1B42360283676CA-skylake.obj
E {PPU[0x1000000] Thread (main_thread)} LLVM: Writeable data section not supported!
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+9D6CA0-A9831168CE2E91F3-skylake.obj

**Comment by Illynir** [comment]
Same problem here.

**Comment by vsub** [comment]
Any special settings or maybe it's certain games related problem?
I can try only one game right now(Atelier Shallie)and the only freeze I get is like 2 seconds and then the game window appear after 1 more second

The only "outside" difference(unrelated to rpcs3 settings)is that I am forcing the gpu to always run in maximum perferformance mode because for whatever reason any game I try is randomly freezing for second or two when the gpu is switching between idle and higher core\vram\shader speeds(it is especially bad on ocasuanally demanding places in less demanding games)

I also tried with Optimal Performance but there was no difference in the loading speed(5seconds from boot until all of the game window appear)

i7-6700HQ,GTX1060,16GB ram Win10

**Comment by Psycho-A** [comment]
@vsub Settings doesn't matter this behavior, operating system too. And many of my games started to suffer of this during last updates.

**Comment by vsub** [comment]
@Psycho-A there was an update done related to this problem https://github.com/RPCS3/rpcs3/commit/9187911a29e43e9401e4892e3f54f0014bd2b904
You can try the latest version

**Comment by Psycho-A** [comment]
I can confirm that issue was gone.

**Comment by MSuih** [comment]
If that's the case then click on the "Close issue" button below the comment field.
