### ISSUE TITLE
Demon's Souls hangs with verification problem error

### ISSUE THREAD

**Issue by Finoderi** [RPCS3/rpcs3#4887]
RPCS3 is running on Windows 10 (17134.165), Ryzen 5 1600, AMD Radeon RX480 with Radeon Software Adrenalin Edition 18.7.1
My Settings are following.
https://imgur.com/a/MI8OIih

And at in an arbitrary point of time Demon's Souls hangs with this error: https://i.imgur.com/m4wWnBm.png

The game can hang anywhere - in Nexus, Boletaria Palace, Stonefang Tunnel etc.

I believe this problem occured after PR #4844 or #4858. It persists in builds 0.0.5-7078 - 0.0.5-7101. I tried them all and got this error.

**Comment by Parthorisian** [comment]
And whats unregular there? This game have a lot of random fatal errors since february, maybe even december

**Comment by Finoderi** [comment]
Yes, I understand that, but it's not just a random crash, it's the same error every time and I didn't see it until recently.

**Comment by AniLeo** [comment]
Try disabling SPU loop detection, if it still doesn't work then set SPU threads to auto.

May be an issue with SPU loop detection.

**Comment by Finoderi** [comment]
I disabled SPU Loop Detection and set Preffered SPU Threads to Auto and after about 5 minutes of playing the game hanged with the same error. Oh well...

**Comment by Joltee** [comment]
I have the exact same problem, this problem showed up last week after some updates.

Like described my problem also happening anywhere at random times.

Running on Windows 10, 8700K & gtx 1080 (latest drivers)

I also have flickering issues with both vulkan&opengl in demon souls. Sometimes the screen goes complete white rpcs3 crashes.

Flickering is happening anywhere as well.

**Comment by Fashish** [comment]
I have the same problem but for me the game hangs before I get to the main menu screen.

**Comment by isshininu** [comment]
·F 0:15:18.894279 {PPU[0x1000005] Thread (HighGraphics) [0x01d551a4]} class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\../Common/texture_cache.h:299)

Got almost the same error today. Game hangs in background when I switch to another window with Firefox browser.
![- - 987](https://user-images.githubusercontent.com/6324523/43359814-71a1f0ce-92ba-11e8-9ff4-db825c9de6df.jpg)

**Comment by Dani1977** [comment]
as @isshininu I have the same error in all area

**Comment by Tyralyon** [comment]
Add me to the list, I also get these verification errors. It seems to happen more often if I stand still, like standing on top of one of the towers in 1-2 to kill the red dragon. I finally managed to do it, by switching to OpenGL, but not sure if that was random or if these crashes only happen with Vulkan.

**Comment by Joltee** [comment]
Demon Souls should be changed to non-playable game for now. I have tried all settings, even switched computer. Still same issue.

**Comment by Finoderi** [comment]
> Demon Souls should be changed to non-playable game for now.
For that the game should be unplayable for anybody, but it's playable for many. It's playable for me, with some crashes, but still.

**Comment by dukenukemx** [comment]
Good to know I'm not the only person with this issue.  I'm using 7224 and it still happens.

**Comment by ruipin** [comment]
Might be worth retesting with https://github.com/RPCS3/rpcs3/pull/5013 since that contains fixes for the texture cache (which is where the verification is failing).

**Comment by dukenukemx** [comment]
Where do I get RPCS3 with that #5013 fix?  I am using 7224.

**Comment by dukenukemx** [comment]
Ok I just tried #5013 and the game still freezes randomly.  The texture flicker also still occurs.  But it frooze in such a way that I couldn't get the error.

**Comment by sunshan1990** [comment]
why there is a hud shows spu usage on the screen, while I never got that

**Comment by kd-11** [comment]
If it freezes in a way where you dont get the error that is a different issue, the issue @ruipin is referring to will give purple text and a message about failing verification in texture_cache.h. PR https://github.com/RPCS3/rpcs3/pull/5013 has been updated retry. Also, about flickering, for me it seems to be much worse with SPU LLVM and almost completely gone when using ASMJIT, but it can happen when near or interacting with physics objects.

**Comment by Parthorisian** [comment]
Non TSX CPU. Tested around >4hrs and no issues noticed. Except random appearing of infinite loading screen if you used any teleport(archstone, shard or spell "Evacuate") of course. It seems **class std::runtime_error thrown: Verification failed** hang has been replaced by this new (for SPU ASMJIT Recompiler) issue, log [DemonsSouls_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2307003/DemonsSouls_RPCS3.zip)

**Comment by ruipin** [comment]
That log is using RPCS3 v0.0.5-b5b1597f5 which had at least one known bug. Please re-test on master (f3d3a1a4a5d7d32f4fbcf2057d7272ea40beeb2b)

**Comment by Parthorisian** [comment]
Sorry, my fault. The game for now is incredibly stable, can't see any hangs, crashes, infinite loading screens and fatal errors etc. And yes there is some flickering but enough minor and rare and flickers only 1 time if happens... maybe 3-5 fps. 
P.S. Performance has been reduced+looks like whole shaders cache which is required. Tested almost all locations except final and <600 compiled pipeline objects in total

**Comment by AniLeo** [comment]
Texture cache was recently rewritten and it has been mentioned here the issue has been fixed, so I'm closing the issue.

If this is still an issue **(Verification failure on texture cache code)** on the latest master please open a new issue following the guidelines.
