### ISSUE TITLE
Broken shadows on Skullgirls Encore [NPUB31445]

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#4888]
rpcs3-v0.0.5-7104-a1911302_linux64.AppImage
ArchLinux, r9 fury, mesa 18.1.4, i7 4770k
This game plays nicely at 60fps, but the shadows are broken (Vulkan and Ogl)
Joining the log + rsx capture.
![selection_025](https://user-images.githubusercontent.com/7478580/42746881-4587e4c4-88da-11e8-94ff-45154ab2977b.jpg)
[capture-SkullGirls.rrc.zip](https://github.com/RPCS3/rpcs3/files/2196762/capture-SkullGirls.rrc.zip)
[RPCS3.log-SkullGirls.gz](https://github.com/RPCS3/rpcs3/files/2196763/RPCS3.log-SkullGirls.gz)

**Comment by benderscruffy** [comment]
shadows are correct now 
but the players have glitchy  lines on them
![skullgirls](https://user-images.githubusercontent.com/2696404/65367754-0419fe80-dc69-11e9-842e-398f90e7e91b.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3638283/RPCS3.log.gz)
[NPUB31445_20190921084743_capture.zip](https://github.com/RPCS3/rpcs3/files/3638284/NPUB31445_20190921084743_capture.zip)

**Comment by toccata10** [comment]
On rev9085, no problems with shadows, neither with lines. It looks very fine now and plays well.
