### ISSUE TITLE
Skate 3 Missions, Replay Editor, Object Editor, and Edit Skater Loading Forever or Freezing

### ISSUE THREAD

**Issue by mouselag** [RPCS3/rpcs3#4889]
Whenever I boot up Skate 3 in the emulator, I can use a preset skater a free skate around but when ever I want to do a mission, place an object, look at a replay, or edit my skater it gets stuck in this infinite loading screen or it will freeze. In free skate I am getting consistent 30+ FPS and its really smooth and few audio issues but whenever I try to do stuff like this it fails, any help would be appreciated.

My Specs : Windows 10
                  Intel Core i7-6700K
                  GeForce GTX 980 Ti

**Comment by raveskirza** [comment]
Duplicate #4651
