### ISSUE TITLE
Closing game with SPU LLVM makes emulator crash

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#4891]
OS - Windows 10.
CPU - x4 Intel Core i5-4210U
GPU - NVIDIA GeForce 840M
Here is the problem:
If i will open any game with SPU LLVM, and then close it by pressing the X button in the right upper corner, then emulator will freeze and after some time will crash.
This issue has started to happening with me at the PR of the SPU LLVM
Here is the log with InFamous:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2200111/RPCS3.log)

**Comment by Otakon7** [comment]
Can you try to run a game with OpenGL?

I had the crashes as well, but when I playing with the settings, I noticed that using OGL doesn't crash it.

**Comment by Hasster1** [comment]
Nope. Still freezes and then crashes.

**Comment by isshininu** [comment]
Yes, I can confirm this too, but SPU LLVM is not ready for daily use yet.

**Comment by vietnam13231** [comment]
It indeed crashes, but not every single time. For example, Injustice crashes always with SPU LLVM, Project Diva F 2nd only sometimes (like 50/50) and Project Diva F never. For me at least.

**Comment by elad335** [comment]
still an issue? likely fixed by recent recompiler changes.

**Comment by Hasster1** [comment]
Yup, now it closes properly. Issue is fixed.
