### ISSUE TITLE
Vulkan Fatal Error Crash

### ISSUE THREAD

**Issue by Gunzerker111** [RPCS3/rpcs3#4893]
Whenever I try to start a game using vulkan, it gets a fatal error which crashes the emulator, I do have all the requirements and haven't been able to find a fix online
![screenshot 4](https://user-images.githubusercontent.com/41083719/42832712-0749c808-89c0-11e8-8e37-a1d62ccdf233.png)

**Comment by reaper185** [comment]
I think it's the same #4756
