### ISSUE TITLE
Persona 5 PSN ver. [NPEB02436] freezes on start screen somtimes

### ISSUE THREAD

**Issue by DistantThunder** [RPCS3/rpcs3#4894]
Hello, 

Hoping to be respecting the guidelines enough.

### Specs

- Ryzen 1800x @4Ghz
- GTX 1060 6GB VRAM
- 16 GB DDR4 @ 2666 Mhz
- Arch Linux 64bits
- Kernel: 4.17.5-1-ARCH #1 SMP PREEMPT
- PulseAudio 12.0
- X.Org X Server 1.20.0
- NVIDIA PROPRIETARY DRIVER: version 396.24

### Log 

```
AMD Ryzen 7 1800X Eight-Core Processor  | 16 Threads | 15.67 GiB RAM | AVX+
E RSX: Image resource file `/home/user/.config/rpcs3/Icons/ui/fade_top.png' not found
E RSX: Image resource file `Icons/ui/fade_top.png' not found
E RSX: Image resource file `/home/user/.config/rpcs3/Icons/ui/fade_bottom.png' not found
E RSX: Image resource file `Icons/ui/fade_bottom.png' not found
E RSX: Image resource file `/home/user/.config/rpcs3/Icons/ui/cross.png' not found
E RSX: Image resource file `Icons/ui/cross.png' not found
E RSX: Image resource file `/home/user/.config/rpcs3/Icons/ui/circle.png' not found
E RSX: Image resource file `Icons/ui/circle.png' not found
E RSX: Image resource file `/home/user/.config/rpcs3/Icons/ui/triangle.png' not found
E RSX: Image resource file `Icons/ui/triangle.png' not found
E RSX: Image resource file `/home/user/.config/rpcs3/Icons/ui/square.png' not found
E RSX: Image resource file `Icons/ui/square.png' not found
E RSX: Image resource file `/home/user/.config/rpcs3/Icons/ui/save.png' not found
E RSX: Image resource file `Icons/ui/save.png' not found
E RSX: Image resource file `/home/user/.config/rpcs3/Icons/ui/new.png' not found
E RSX: Image resource file `Icons/ui/new.png' not found
S LDR: Boot successful.
E )} PPU: LLVM: Loaded module v2+6FBD78-949184B30158B0F9-znver1.obj
/sys/external/libsre.sprx
E {PPU[0x1000000] Thread (main_thread) [0x012714d0]} LLVM: Writeable data section not supported!

... 

F {PPU[0x1000017] Thread (xrd664_list_load) [0x00acf4f8]} St13runtime_error thrown: Unknown system error: 36.
```

This is with most shaders I believe, if not all, having already been compiled for the menu.
Using PulseAudio and Vulkan.

- Coredump: http://dl.free.fr/jtW4KvhYW (warning 21 GiB uncompressed)

- Screenshot: 

![image](https://user-images.githubusercontent.com/3923810/42849506-c33b62f2-8a23-11e8-8246-1aa291107529.png)

Thanks again for your amazing work.

**Comment by DistantThunder** [comment]
Here's the log file.

[RPCS3.upload.log.zip](https://github.com/RPCS3/rpcs3/files/2207056/RPCS3.upload.log.zip)

> Thats something to do with saves. Try removing them completely and see which is corrupted. Saves are in dev_hdd0/home/00000001/savedata by default.

Could very well do. I tried loading my PS3 imported saves but the EMU wouldn't be cooperative and freeze. 

I don't think they're encrypted though but ok, I'll remove them and see.

**Comment by AniLeo** [comment]
```
·W 0:02:25.721469 {PPU[0x1000017] Thread (xrd664_list_load) [0x00acf4f8]} cellSaveData: cellSavaDataGetListItem(dirName=“˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˿��ʪ˻ސĪʪ*��%	”, dir=*0x10a5cb8, sysFileParam=*0x10a5cf0, bind=*0xd0184b88, sizeKB=*0xd0184b84)
·W 0:02:25.739691 {PPU[0x1000017] Thread (xrd664_list_load) [0x00acf4f8]} PPU: 'cellSaveDataGetListItem' aborted
·W 0:02:25.739715 {PPU[0x1000017] Thread (xrd664_list_load) [0x00acf4f8]} PPU: 'cellSaveDataListAutoLoad' aborted
·F 0:02:25.740332 {PPU[0x1000017] Thread (xrd664_list_load) [0x00acf4f8]} St13runtime_error thrown: Unknown system error: 36.
```

Yeah, it's not freezing, it crashed with a bad save

**Comment by DistantThunder** [comment]
Alright, turns out the saves were encrypted and I have very old memories of encryption occurrence on PS3 save data. I guess RPCS3 tripped over that but it's strange that it was random.

I can't reproduce the problem across 10 reboots now. I guess we can close this?
