### ISSUE TITLE
update website FAQ suggestion

### ISSUE THREAD

**Issue by shellscriptz** [RPCS3/rpcs3#4897]
As is: 

**What input devices can I use with RPCS3?**
We currently support keyboard / mouse inputs and native DualShock 4 controllers. We also support XInput and MMjoy based controllers. Unfortunately, we currently do not natively support DualShock 3 controllers. You can however use third-party tools like SCP Driver Package to allow your DualShock 3 controller to function like an XInput controller. We plan to add additional input methods in the future as we implement more meaningful features to the emulator.

To Be: 
**What input devices can I use with RPCS3?**
We currently support keyboard / mouse inputs and native DualShock 4 controllers. We also support XInput and MMjoy based controllers. **_Keyboard inputs may be mapped to other joysticks using JOYTOKEY, a multi-purpose joystick accessibility tool (https://joytokey.net/en/download)_**   Unfortunately, we currently do not natively support DualShock 3 controllers. You can however use third-party tools like SCP Driver Package to allow your DualShock 3 controller to function like an XInput controller. We plan to add additional input methods in the future as we implement more meaningful features to the emulator.

Tested, and it worked in all games I tried. I mapped the default keyboard profile to an xbox one controller, a logitech g13, and other devices.  Config file attached. 
[ps3_jtk_config_file.zip](https://github.com/RPCS3/rpcs3/files/2204599/ps3_jtk_config_file.zip)

**Comment by Asinin3** [comment]
Can't you just use the inbuilt pad configuration to map buttons to your keyboard...?
![image](https://user-images.githubusercontent.com/15137035/42862775-7a0b46a6-8a50-11e8-9387-ecf3dc100ac3.png)
![image](https://user-images.githubusercontent.com/15137035/42862785-7f456dd6-8a50-11e8-9b10-036cceca8d3c.png)

**Comment by hcorion** [comment]
this should actually be filed here: https://github.com/DAGINATSUKO/www-rpcs3

**Comment by nitrohigito** [comment]
@hcorion you can't open issues there, only PRs

**Comment by Megamouse** [comment]
@AniLeo any news on this?

**Comment by Megamouse** [comment]
The website now supports issues.
So it's not the main project's issue anymore.
