### ISSUE TITLE
Tony Hawk Pro Skater 5 30 FPS Audio Problem

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#4907]
he game works with the intros with perfect audio, but when it is in play the audio is bad as if it had low fps for now it has not had any graphic error it is only the audio attached an example in a video.

https://www.youtube.com/watch?v=aJteOIflc4g&t=151s

![image](https://user-images.githubusercontent.com/16367065/42953111-484c5f84-8b3f-11e8-8994-711d1ee8c017.png)

![image](https://user-images.githubusercontent.com/16367065/42953131-583a8eac-8b3f-11e8-8b31-cd0853526d25.png)

![image](https://user-images.githubusercontent.com/16367065/42953198-8b20b972-8b3f-11e8-96d4-b3e619c5a06d.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2210572/RPCS3.log.gz)

Note: other games also present the same problem
SSX

**Comment by AniLeo** [comment]
This is a general performance issue, audio is lagging because game is not being emulated at full speed, happens with many games

---

Closing as there's no specific issue but instead it's a general performance issue
