### ISSUE TITLE
Config Not Working

### ISSUE THREAD

**Issue by CutesyWOOT** [RPCS3/rpcs3#4912]
Every time I simply try to enter a config menu, I get this error message:

RPCS3: Fatal Error

Unhandled Win34 exception 0xE06D7363.
Exception address: 00007ff9ee79a388.
ExceptionInformation[0x0]: 0000000019930520.
ExceptionInformation[0x1]: 0000000002cf7b40.
ExceptionInformation[0x2]: 0000000001d5e098.
ExceptionInformation[0x3]: 0000000000010000.
Instruction address: 00007ff9ee79a388.
Function address: 00007ff9ee79a388 (base+0x3a320).
Module name: 'KERNELBASE.dll'
Module base: 00007ff9ee760000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS:
https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support
Please, don't send incorrect reports. Thanks for undestanding.

I have no idea what any of that means or why it's appearing. I think it might have something to do with the fact that I altered one tiny thing in the config.yml file. I changed it back, too, and it still didn't work. Anything I can do about this?

**Comment by AniLeo** [comment]
You corrupted your config.yml file by editing it, the syntax is broken. This is not an emulator issue.

**Comment by CutesyWOOT** [comment]
well what do I do about it?

**Comment by CutesyWOOT** [comment]
Nevermind, I just deleted the corrupted file and when I opened rpcs3, it automatically made a new, uncorrupted one. Sweet.
