### ISSUE TITLE
vk: Broken shadow on Ninja Gaiden Sigma

### ISSUE THREAD

**Issue by darkangelire** [RPCS3/rpcs3#4913]
the bug makes an over  exaggerated shadow 

**Vulkan:**
![image](https://user-images.githubusercontent.com/41484945/43029612-a6aef386-8c3c-11e8-919d-5c922a83c5d8.png)

**OpenGL:**
![image](https://user-images.githubusercontent.com/41484945/43030278-0f7ebac6-8c43-11e8-8305-c070390cfcf7.png)

**pc specs**
ryzen 7 1700x
amd r9 280x
16 gb ddr4

**Comment by darkangelire** [comment]
thanks

**Comment by AniLeo** [comment]
I assume the issue was fixed?

**Comment by darkangelire** [comment]
no not as of yet

**Comment by darkangelire** [comment]
it is a very strange bug to me

**Comment by Zangetsu38** [comment]
few game have strange glitch with shadow, like bleach, depending camera or emplacement character, shadow can get glitch

**Comment by sunshan1990** [comment]
@darkangelire can you share a downloading address of the ninja gaiden sigma? I would like to test and play it as well!

**Comment by sunshan1990** [comment]
@darkangelire

**Comment by darkangelire** [comment]
that is piracy.....so no

**Comment by Whatcookie** [comment]
This is fixed by https://github.com/RPCS3/rpcs3/pull/5860
Tested on both radv and windows amd
