### ISSUE TITLE
When I run Sonic Unleashed it just shows up with a blank screen.

### ISSUE THREAD

**Issue by nonmeme12** [RPCS3/rpcs3#4917]
I tried every solution to try to fix this but nothing works. Previous versions of the emulator worked but only to the loading screen. My rig is GPU: Nvidia GeForce 8400GS CPU: Intel i3 Memory: 4GB Operating system: Window 10 pro

**Comment by elad335** [comment]
wtf

**Comment by Asinin3** [comment]
8400GS doesn't even have open GL 4.3

**Comment by nonmeme12** [comment]
Really? I actually thought that it has open GL 4.3. Then what does it have then?

**Comment by Asinin3** [comment]
It's using OpenGL 3.3 It's a very ancient (10 years old) GPU that's also a low-end model the time it was released. Please hit the big red close button at the bottom of the screen, this issue is invalid.

**Comment by nonmeme12** [comment]
What big red button?

**Comment by AniLeo** [comment]
This is not a support helpdesk. Read the guidelines.
