### ISSUE TITLE
install firmware crash

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#4918]
the installation does not exceed 4%

![image](https://user-images.githubusercontent.com/16367065/43039236-d20eb23e-8cee-11e8-834d-c84dec6523e4.png)

![image](https://user-images.githubusercontent.com/16367065/43039230-b5ab106a-8cee-11e8-8fca-a23ccf174dda.png)

**Comment by HerrHulaHoop** [comment]
delete dev_flash folder and try again. Also, you can head over to the [Discord server](https://discord.me/RPCS3) for support. This issue tracker isn't the ideal place for this.

**Comment by AniLeo** [comment]
Not the most recent master, no log file...

Try with a separate clean installation too

**Comment by mkultimate** [comment]
@HerrHulaHoop 
problem solving removing and creating the folder dev_flash full installation thank you very much

**Comment by AniLeo** [comment]
Be careful about submitting an invalid issue. If you're not sure if it's an issue, ask for support first on the appropriate places.
