### ISSUE TITLE
Regression: Far Cry Classic after #4794

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#4924]
@kd-11 
https://github.com/RPCS3/rpcs3/pull/4794 [Fixes]
This game crashes with vulkan on the loading screen with fatal error:
```
F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKCompute.h:137)
```
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2219894/RPCS3.log.gz)

**Comment by kd-11** [comment]
Can I get a trace of this? Try and get rrc capture, 120 compute invocations in one frame is too much. You can capture with openGL.

**Comment by Emulator-Team-2** [comment]
OpenGL: --> [RSX Capture](https://mega.nz/#!YEYnEAhL!BB12BhS9gM-Y9ke5IU90vvVLgOQpAKCYX-H_XMPvOMU)
