### ISSUE TITLE
Stretch To Display Area option depends on -when- fullscreen is entered

### ISSUE THREAD

**Issue by clidx** [RPCS3/rpcs3#4926]
I've found that if I double click to fullscreen while the PPU shaders on disk are being loaded/compiled, the stretch option is ignored. I leave it unchecked because I have a 16:10 monitor. If I fullscreen too early, there are no black bars and the image is stretched. If I wait to fullscreen until the game itself starts then I get black bars as expected. This has happened on both Nier and Drakengard 3 - the only 2 games I have run on the emulator so far.

It has happened on multiple commits - I've updated the emulator ~3 times and I've been using it for about 2 weeks total. Running 7123 now.

My GPU settings:
Vulkan
16:9
Framelimit off
AF 16x
1280x720
150% resolution scale to 1920x1080
default resolution scale threshold
Everything unticked except Use GPU Texture Scaling

My specs:
Win 10 x64, Xeon X5660, 10GB RAM, RX480 8GB, 16:10 1920x1200 monitor

**Comment by Megamouse** [comment]
Is this still happening?

**Comment by clidx** [comment]
It doesn't seem to be although I have changed hardware and clean installed since then.
