### ISSUE TITLE
Tekken Tag Tournament 2 [BLES01702] on RPCS3 build 7123

### ISSUE THREAD

**Issue by Zudrit** [RPCS3/rpcs3#4927]
Tekken Tag Tournament 2 has issue on 2 stages are "Heavenly Garden" & "Fallen Garden" as this.
https://youtu.be/kaPE8KkO1qk
You can try these 2 stages in Practice mode.

My settings:
Vulkan
16:9
Framelimit off
1280x720
150% resolution scale to 1920x1080

My spec.
CPU i7 6700K
RAM Corsair Vengeance 8 Gb bus 3000 x 2
VGA MSI GTX 1060 OCV2
Windows 10 Pro x64

**Comment by Asinin3** [comment]
Needs strict rendering mode, read our forum threads for the game, it explains this. It's not really a valid issue.

**Comment by Zudrit** [comment]
Thank you so much for your answer.

**Comment by arcadee1977** [comment]
Strict rendering mode OFF:
![未标题-0](https://user-images.githubusercontent.com/47111657/54426986-27ad3b00-4754-11e9-8f4e-1e803990b2d6.jpg)


When pause the game ,the graphics is fine and clear:
![未标题-00](https://user-images.githubusercontent.com/47111657/54427125-883c7800-4754-11e9-9c56-c38421af2e7d.jpg)

Strict rendering mode ON ( graphics is fine , but too blur):
![未标题-1](https://user-images.githubusercontent.com/47111657/54427234-d94c6c00-4754-11e9-993c-139b978efac8.jpg)

**Comment by Zudrit** [comment]
> Strict rendering mode OFF:
> ![未标题-0](https://user-images.githubusercontent.com/47111657/54426986-27ad3b00-4754-11e9-8f4e-1e803990b2d6.jpg)
> 
> When pause the game ,the graphics is fine and clear:
> ![未标题-00](https://user-images.githubusercontent.com/47111657/54427125-883c7800-4754-11e9-9c56-c38421af2e7d.jpg)
> 
> Strict rendering mode ON ( graphics is fine , but too blur):
> ![未标题-1](https://user-images.githubusercontent.com/47111657/54427234-d94c6c00-4754-11e9-993c-139b978efac8.jpg)

All right, Thanks a lot.
