### ISSUE TITLE
Unhandled Win32 exception on Silent Hill: Downpour

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4929]
Tested on build 7123 and Windows 10 LTSB.

After end of passing through the intro level, when we're walking the corridor before the elevator, I get this error, which repeats every time.
![bug](https://user-images.githubusercontent.com/1223276/43180300-de9710ca-8fc6-11e8-81ca-cec480bacf89.png)
Never seen this before, when I tested latest build about 5 days ago.

Additional settings:
SPU ASMJIT;
SPU Threads: Auto,
SPU Block Size: Mega,
Renderer: Vulkan,
Use GPU Texture Scaling,
VSync,
Disable Vertex Cache,
Force CPU blit emulation (game's unloadable for me without it).

**Comment by Psycho-A** [comment]
@Parthorisian I'll try with Safe block size and report here again...

**Comment by AniLeo** [comment]
Closed due to inactivity and since WIP non-recommended settings were used
