### ISSUE TITLE
issuei have a problem with rpcs3 : it works at 60 fps while plugged in but only 30 when unplugged 

### ISSUE THREAD

**Issue by m1mm2** [RPCS3/rpcs3#4932]

**Comment by clienthax** [comment]
No.

**Comment by 13xforever** [comment]
Github is not the place to get support.

Please _read_ the [guidelines](../blob/master/.github/CONTRIBUTING.md) before opening an issue.

**Comment by reaper185** [comment]
Your computer is probably set to use less CPU while unplugged. It's not rpcs3. Go to Control Panel->System and Security->Power Options->Change Plan Settings->Change Advanced Power Settings->Processor Power Management->Maximum Processor State. On battery option should be 100% if you want rpcs3 to run better while unplugged however it will drain your battery faster even when not using rpcs3.
