### ISSUE TITLE
SPU LLVM graphical issues

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#4937]
Spu llvm has a lot graphical issues, i've made investigation on some of them and discovered that long time ago SPU ASMJit also suffered from these issues, but they were fixed by https://github.com/RPCS3/rpcs3/pull/2683. I reverted this PR on current build to made some comparisson with llvm and the issues look the same:
Red Dead Redemption 
ASMJit +PR Reverted
![4](https://user-images.githubusercontent.com/7060586/43329739-f5d9d4a2-91c9-11e8-8b68-711304054f5d.jpg)
SPU LLVM
![5](https://user-images.githubusercontent.com/7060586/43330481-05c3966c-91cc-11e8-8c67-7fefe2eac357.jpg)

Midnight Club: Los Angeles
ASMJit +PR Reverted
![12](https://user-images.githubusercontent.com/7060586/43329842-3ec399d2-91ca-11e8-8366-fe1fde48320f.jpg)
SPU LLVM
![6](https://user-images.githubusercontent.com/7060586/43329841-3ea40e5a-91ca-11e8-9bc4-2fe2290800dc.jpg)

Metal Gear Rising
ASMJit +PR Reverted
![13](https://user-images.githubusercontent.com/7060586/43329920-67d598a2-91ca-11e8-9ed4-260472e2dd7b.jpg)
SPU LLVM
![22](https://user-images.githubusercontent.com/7060586/43329927-6c15ab0a-91ca-11e8-8513-04576b1890c3.jpg)

Ninja Gaiden Sigma 2
ASMJit +PR Reverted
![29](https://user-images.githubusercontent.com/7060586/43329968-8dc60b82-91ca-11e8-8afa-ffd4868e32b7.jpg)
SPU LLVM
![30](https://user-images.githubusercontent.com/7060586/43329969-8de97c84-91ca-11e8-8afe-ac6c3672a9d6.jpg)

God of War III Demo
ASMJit +PR Reverted
![32](https://user-images.githubusercontent.com/7060586/43330006-a4c5d40c-91ca-11e8-8ad4-d31694795522.jpg)
SPU LLVM
![31](https://user-images.githubusercontent.com/7060586/43330012-a7121ed2-91ca-11e8-8bbb-a1a55d055836.jpg)

The PR itself above the year old, the reason ASMJit never had these issues, cause none of these games, except Metal Gear Rising showed ingame graphics back those days, i think improving these instructions accuracy in llvm will make games more playable.

**Comment by hcorion** [comment]
These are all fixed in #4920

**Comment by Xcedf** [comment]
Fixed now

**Comment by Xcedf** [comment]
Fixed now
