### ISSUE TITLE
RSX: Unknown blend factor 0x7 (gcm_enums)

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#4938]
After starting a new game:
> ·F 0:11:54.867391 {rsx::thread} class std::runtime_error thrown: Unknown blend factor 0x7
> (in file Emu\RSX\gcm_enums.cpp:773)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2237484/RPCS3.zip)
![disney_bolt](https://user-images.githubusercontent.com/14265316/43350321-e1e39ede-920e-11e8-94ed-7fef35ff0798.png)

**Comment by Zangetsu38** [comment]
ouch, this issue is very old :/

**Comment by uaqlover** [comment]
any updates...?

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by Zangetsu38** [comment]
Tested here and yes, not changed
``F {RSX [0x01955f4]} RSX: class std::runtime_error thrown: Unknown blend factor 0x7
(in file h:\git\rpcs3-gui\rpcs3\emu\rsx\gcm_enums.cpp:774)``
I can get works with hack but not best idea ^^

**Comment by digitaldude555** [comment]
Call of Duty 3 and 4 also have this error.

**Comment by digitaldude555** [comment]
Virtua Tennis 3 is another one.

**Comment by kd-11** [comment]
Is it always 7 for all these games? Or are they different values?

**Comment by digitaldude555** [comment]
@kd-11 
They all have
`F {RSX [0x000525c]} RSX: class std::runtime_error thrown: Unknown blend eq 0x0
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gcm_enums.cpp:734)`
so it's different my bad...

**Comment by kd-11** [comment]
Clearly not, the value matters.  In your example its 0x0 but the OP is 0x7

**Comment by digitaldude555** [comment]
So make a separate issue for virtua tennis 3 and the rest?

**Comment by kd-11** [comment]
No need. One hardware test can confirm all of these.

**Comment by elad335** [comment]
Yes.

**Comment by Realmantik** [comment]
Another game with this issue is "007: Quantum of Solace".

**Comment by CookiePLMonster** [comment]
Gran Turismo 5 Prologue throws `Unknown blend eq 0x0` when attempting to race on High Speed Ring. Other tracks also don't work (with the exception of Suzuka and Eiger Nordwand), but I haven't checked if it's the same blend eq.

**Comment by money123451** [comment]
needs testing with #7780

**Comment by uaqlover** [comment]
still not fixed after https://github.com/RPCS3/rpcs3/pull/7780

now it shows 

`F {RSX [0x000bbd4]} sig_log: Thread terminated due to fatal error: Unknown blend factor 0x7
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:751)`

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/8479
