### ISSUE TITLE
game froze not can paly haha BLEACH: Soul Resurreccion

### ISSUE THREAD

**Issue by kuzeyuta** [RPCS3/rpcs3#4939]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2237685/RPCS3.log.gz)
![1414](https://user-images.githubusercontent.com/41793905/43353149-328df23e-925b-11e8-87f3-da980c64e6ed.jpg)
not can play time start froze all @@

**Comment by Zangetsu38** [comment]
no report bug or other on other build, report only with last master
