### ISSUE TITLE
PS1 Classics saves ignore /home/user directory

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4943]
Problem:

Saves for PS1 Classics game (not sure if this is common behavior - I have tested only 1game so far - Silent Hill 1 EU) are located at "dev_hdd0\savedata" path instead of "dev_hdd0\home\00000001\savedata".

Now, when user profiles are implemented, this is a bug.

**Comment by clienthax** [comment]
That's how how the emulator works, https://github.com/RPCS3/rpcs3/pull/4802/files#diff-8d33537da71725790aa810521eef7244R912
Unless these are remapped by vsh

**Comment by isshininu** [comment]
@clienthax what do you mean?

**Comment by clienthax** [comment]
On a real PS3 they are stored in the same location as they are currently, and not in the user home.

**Comment by isshininu** [comment]
So this is not really an issue?

**Comment by clienthax** [comment]
@isshininu it's not a issue at all, to work around it would be hacky and most likely upset vsh
