### ISSUE TITLE
Persona 5 [NPEB02436] freezes indefinitely instead of playing pre-rendered cutscenes as of v0.0.5-7105

### ISSUE THREAD

**Issue by supernikio2** [RPCS3/rpcs3#4951]
As of v0.0.5-7105-064d0619 every time a prerendered cutscene is supposed to play in Persona 5, a black screen shows up indefinately preventing the game from being completed. The latest version in which intended behavior takes place is v0.0.5-7022-3d8223fc.

**How to replicate:**
In the latest build of RPCS3, boot up Persona 5 (I'm using the European version, if that's relevant) and once the start menu appears, navigate to "New game" and create a new save. After the intro dialogue (the one that asks the player for consent that this game is a work of fiction), [this cutscene](https://youtu.be/W4vDgZOhuHA) is supposed to start playing. However, the graphics completely freeze at the first frame, but (at least some part of) the game logic is still running. This means that if the user presses any button, the "START to skip" prompt will appear at the bottom right as per usual. If "START" is indeed pressed, the game will indefinitely freeze at a black screen.

Nevertheless, this cutscene behaves slightly different from others I've encountered--for instance the one at the end of the 4th palace--as this is the only one that allows the user to "skip" it by pressing START: the aforementioned cutscene doesn't play at all; it gets stuck at a black screen.

As previously mentioned, this bug doesn't happen at all in v0.0.5-7022-3d8223fc.

**System specs:**
CPU: Ryzen 5 1600 @ 3.85GHz
RAM: Crucial 8GB DDR4-2400
GPU: XFX R9 380X
MoBo: MSI B350 Gaming Pro
OS: Windows 10 Pro 64-bit

**Game config:**
[CPU and GPU settings. I don't think the others are relevant to the issue, but will provide them if necessary](https://imgur.com/a/cwQeZaq)

**Comment by 13xforever** [comment]
> no logs
> using Giga block size

That's a support question, and not an issue report. Please read the guidelines before opening an issue.

**Comment by 13xforever** [comment]
You should close this issue

**Comment by AniLeo** [comment]
Try reproducing with default CPU settings

**Comment by 13xforever** [comment]
Already sorted on discord
