### ISSUE TITLE
Error a games Asura's Wrath

### ISSUE THREAD

**Issue by dokker66** [RPCS3/rpcs3#4959]
Help me please 
ERROR

U {PPU[0x1000000] Thread (main_thread) [0x01603d98]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd0040230, option=*0x0, waitForEvent=0)
U {PPU[0x1000000] Thread (main_thread) [0x01c87c8c]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
U {PPU[0x1000000] Thread (main_thread) [0x01c87d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5
E {PPU[0x1000000] Thread (main_thread) [0x01c87d84]} '_sys_spu_printf_attach_group' failed with 0x00000000 : 0 [1]
U {PPU[0x1000000] Thread (main_thread) [0x01c8d304]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x01c8d304]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000000] Thread (main_thread) [0x01c87d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
E {PPU[0x1000000] Thread (main_thread) [0x01c87d84]} '_sys_spu_printf_attach_group' failed with 0x00000000 : 0 [2]
U {PPU[0x1000000] Thread (main_thread) [0x01c8de50]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x01c8de50]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
U {PPU[0x1000000] Thread (main_thread) [0x01604f50]} sceNp TODO: sceNpManagerGetNpId(npId=*0xd003fd90)
E {rsx::thread} RSX: Dangling reports found, discarding... x178
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/INSTALL” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/INSTALL” [2]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/INSTALL” [3]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/BCGAME/PS3TOC.TXT” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/BCGAME/PS3TOC.TXT” [2]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/BCGAME/PS3TOC.TXT” [3]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/BINARIES/PS3/SAVE/ICON0.PNG” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/BINARIES/PS3/SAVE/ICON1.PAM” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc2090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BINARIES/PS3/SAVE/ICON1.PAM” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/BINARIES/PS3/SAVE/PIC1.PNG” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc2090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BINARIES/PS3/SAVE/PIC1.PNG” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/BINARIES/PS3/SAVE/SND0.AT3” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc2090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BINARIES/PS3/SAVE/SND0.AT3” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc2000]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/DLC” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc2000]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/DLC” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/INSTALL/___LOCK” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/INSTALL/___LOCK” [2]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/BCGAME/COOKEDPS3/COALESCED_INT.BIN” [1]
E {PPU[0x1000012] Thread (fios mediathread 11) [0x01cc1ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30721/USRDIR/FIOS-UNREALENGINE3/BINARIES/EPICINTERNAL.TXT” [1]
F {PPU[0x1000000] Thread (main_thread) [0x01f50fd4]} class std::runtime_error thrown: Unimplemented
(in file Emu\Cell\Modules\sys_libc_.cpp:445)

**Comment by elad335** [comment]
use the default `load liblv2.sprx only` option in cpu settings and close this issue, this is not a support forum.
