### ISSUE TITLE
[GUI Feature Request] Play ICON1.PAM on game-list hover/Other XMB Features 

### ISSUE THREAD

**Issue by HexyFify** [RPCS3/rpcs3#4960]
First  """Issue""" by me;
More of a feature request but it would be nice to play the animated ps3 video icon ( ICON1.PAM) on hover/single click of a game, and optionally enable xmb icon audio to play with it. (SND0.AT3)

Also it could be possible to have the old ps3 splash screen back in optionally;
Because Almost all games contain "PS3LOGO.DAT" which is basically a png/jpg file used for older firmware game startups before FW 3.00. 

This would make rpcs3 feel a bit more like home in terms of gui 

PS3 Old Game Launch Splashscreen:
https://www.youtube.com/watch?v=kjaABg4aNVc
https://www.youtube.com/watch?v=tgPXlMbchFM

Game Contents:
http://www.psdevwiki.com/ps3/Content_Information_Files#Disc_Game

**Comment by Oky12** [comment]
your request may take a long time to apply to rpcs3. because the request is more suitable in the new gui. not now. i am a programmer. and I also have a dream to make a new gui for rpcs3 and have the same features as you requested. but I'm not professional aka studying

**Comment by dio-gh** [comment]
@Megamouse this sounds like should be much closer to feasibility, right?

**Comment by Megamouse** [comment]
No

**Comment by Roet-Ivar** [comment]
Since this is still open I can just inform that booting into xmb now handles SND0.AT3 but not yet ICON1.PAM.

**Comment by oltolm** [comment]
https://github.com/RPCS3/rpcs3/pull/14835 implemented this, I think.

**Comment by kd-11** [comment]
Yep, closing as implemented.

**Comment by AhayriSG** [comment]
does this feature rely on the Windows Media Foundation Pack?

I can't get ICON1.PAM or SND0.AT3 audio to play in the GUI. I've verified the file locations using Open Folder > Game Directory, and the .AT3 file plays without issue outside of RPCS3.

custom GIFs hover (like replacing game icons/ICON0) work perfectly fine in the GUI, and custom backgrounds work during SPU/PPU compilation. It's just the ICON1.PAM and the SND0.AT3 audio (in both the GUI and compilation screens) that remain completely silent/inert.
