### ISSUE TITLE
Regression: Drakengard 3 [BLUS31197] installation fails

### ISSUE THREAD

**Issue by Sztefanol** [RPCS3/rpcs3#4961]
Regression introduced in https://github.com/RPCS3/rpcs3/pull/4715
Installation fails when game disc resides in non-default DEV_HDD0 directory. When game disc is in default DEV_HDD0 installation proceeds correctly with files being created there. In earlier versions game installs in default DEV_HDD1 regardless of game disc directory location.
In this version emulator creates temporary directory with ICON0.PNG and empty USRDIR, then installation halts with following message:
![image](https://user-images.githubusercontent.com/22085527/43795026-5e93ef3c-9a80-11e8-9d90-94fe48737c43.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2267783/RPCS3.log.gz)

**Comment by AniLeo** [comment]
> In earlier versions game installs in default DEV_HDD1 regardless of game disc directory location

Games don't install to dev_hdd1, that's a cache partition which is mounted as a clean partition on a real PS3 whenever you start a game.

**Comment by AniLeo** [comment]
Needs retesting, this is probably not happening on master builds

**Comment by AniLeo** [comment]
Closing for both inactivity and no one being able to reproduce this at all, it was just tested on current master and it installs just fine

**Comment by 13xforever** [comment]
Works fine.
![image](https://user-images.githubusercontent.com/36445/61150982-34714e00-a4fe-11e9-96ba-7cf3f31e358f.png)
![image](https://user-images.githubusercontent.com/36445/61150983-363b1180-a4fe-11e9-8de2-828db8d71d77.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3387629/RPCS3.log.gz)
