### ISSUE TITLE
Homebrew: Font rendering incorrectly with L8 texture format

### ISSUE THREAD

**Issue by Dnawrkshp** [RPCS3/rpcs3#4963]
In [Mini2D](https://github.com/Dnawrkshp/mini2d) I changed the font class to draw glyphs as 8-bit grayscale (TINY3D_TEX_FORMAT_L8). Following that, RPCS3 only outputs black boxes.
[This is the commit that produced this bug.](https://github.com/Dnawrkshp/mini2d/commit/612849263a177969746a9b1f4f98bc96d8b16934)

#### Screenshots:
![rpcs3_2018-08-08_15-36-03](https://user-images.githubusercontent.com/2020854/43868136-fa5fea60-9b20-11e8-81ad-a15e5937df90.png "bad")

![rpcs3_2018-08-08_15-37-03](https://user-images.githubusercontent.com/2020854/43868141-feccfd72-9b20-11e8-874d-05a12bfe44e2.png "good")

#### To reproduce (requires PSL1GHT):

```
git clone https://github.com/Dnawrkshp/mini2d
cd mini2d
make
cd samples/printtest
make
```

If you would prefer I upload the self just let me know.

----------------------
Specs:
RPCS3 451b3f3c9
6700K @ 4.5 GHz
GTX 1070
16GB DDR4 @ 2100 MHz
Windows 10

**Comment by kd-11** [comment]
Just upload the self

**Comment by Dnawrkshp** [comment]
[mini2d-printtest.zip](https://github.com/RPCS3/rpcs3/files/2275245/mini2d-printtest.zip)

**Comment by Dnawrkshp** [comment]
My bad. Here's the unsigned version for both (just in case).

[mini2d-printtest-elf.zip](https://github.com/RPCS3/rpcs3/files/2380429/mini2d-printtest-elf.zip)

**Comment by elad335** [comment]
Thats pretty much how it looks on the DECR. (B8 texture)
![img0000](https://user-images.githubusercontent.com/18193363/46249411-88a8b700-c431-11e8-99f0-d69161d6a77b.PNG)

**Comment by kd-11** [comment]
Yea, I forgot to update this after checking the source, but rpcs3 is right. B8 aka L8 is read as RRR1 by hardware, so you need to set the texture read to grab one of the RGB channels and write to alpha. My guess is that this is why the L8 format path was disabled in mini2 before, because it did not work correctly.

**Comment by Dnawrkshp** [comment]
Thanks for the response. I did not know about this. I'll try and see if I can get it working. 

I'll go ahead and close this issue. Thanks again!
