### ISSUE TITLE
Skate 3 hangs on character creation [BLES00760]

### ISSUE THREAD

**Issue by dustinpaluch** [RPCS3/rpcs3#4965]
### Version:
RPCS3 https://github.com/RPCS3/rpcs3/commit/451b3f3c9d73508ee583d0c555e23c1174c2ab57

### Reproduce:
Start the game, proceed through menus making default selections, skip intro video, choose "Customize Skater" when prompted. Accept the default character name. The game will hang, but music will continue to play. Sometimes you get additional graphical artifacts.

### RPCS3.log.gz
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2279821/RPCS3.log.gz)

### Specs:
i5-4690 @ 3.5GHz
NVIDIA GTX 770 
8GB RAM
[DxDiag.txt](https://github.com/RPCS3/rpcs3/files/2259763/DxDiag.txt)

**Comment by MSuih** [comment]
Probably a duplicate of #3621 or #4651.

**Comment by dustinpaluch** [comment]
@MSuih oops, you're right.
