### ISSUE TITLE
Skate 2 misbehaving shadows [BLES00461]

### ISSUE THREAD

**Issue by dustinpaluch** [RPCS3/rpcs3#4967]
### Version: 
RPCS3 v0.0.5-7166-fdcc5adc8 Alpha | HEAD https://github.com/RPCS3/rpcs3/commit/451b3f3c9d73508ee583d0c555e23c1174c2ab57

### Reproduce:
Start the game, wait for the start screen to appear. As the skateboarders in the half pipe go up and down, a horizontal shadow follows them.

## Screens:
![skate2-shadow2](https://user-images.githubusercontent.com/6547887/43995594-73dbaa76-9d76-11e8-92a0-96cac40faf1d.png)
![skate2-shadow](https://user-images.githubusercontent.com/6547887/43995595-78b7e5c8-9d76-11e8-9e0e-ea5577accd77.png)

### RPCS3.log.gz
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2280508/RPCS3.log.gz)

### Specs:
i5-4690 @ 3.5GHz
NVIDIA GTX 770 
8GB RAM
[DxDiag.txt](https://github.com/RPCS3/rpcs3/files/2259763/DxDiag.txt)

**Comment by kd-11** [comment]
Same bug as the other skate titles, happens because of arithmetic drift.

**Comment by MarioSonic2987** [comment]
With #5436, fixes broken shadows in this game. Also affects Skate 3.
![image](https://user-images.githubusercontent.com/20027681/50739783-1cceab00-11e5-11e9-998f-925e9275d0db.png)

Now this issue should be closed.

**Comment by kd-11** [comment]
Closing as fixed
