### ISSUE TITLE
[Feature Request] Emulate buzz controllers

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#4968]
Since all Buzz games require a special controller in order to play it, Rpcs3 needs to emulate that controllers, for example using DS4, Xinput or other controllers (Games boots in Rpcs3, but can´t pass the first screen because it asks for the buzz controllers)

I assume that this is not an urgent request, but maybe (I don´t know) It´s easy to add or implement.

**Comment by hcorion** [comment]
This would fall under the category of usb device connection emulation, IMO it's out of the scope of RPCS3 to emulate the controllers themselves, but if we got proper usb device connection emulation, then you could just connect the Buzz Controllers to your computer, and RPCS3 will pass that information to the game.

**Comment by LuismaSP89** [comment]
But in other cases, Rpcs3 emulates the DS4 by using xinput. You can use xbox 360/One controllers or other controllers compatible with xinput, then, the games detect it like a DS4. 

Why we can't just emulate the buzz controller and mapping the buttons to the keyboard/ds4/xbox controllers?

**Comment by hcorion** [comment]
DualShock 4 is different though because it's just a controller, we could emulate guitar, drum, dancemats, flight stucks and "DJ" (whatever that means), because of the way it's handled by the PS3, but emulating generic usb peripherals is IMO outside of the scope of RPCS3.

**Comment by LuismaSP89** [comment]
Maybe I don´t explained it very well (In that case, sorry, english is not my mother language ^^)

The buzz controllers are just a controller made for the ps3, and the ps3 supports it natively. I don´t want to connect my buzz controllers to my PC´s usb in order to use it with rpcs3. I only want to use a controller like DS4, Xbox controllers, and map the buttons to an emulated/virtual buzz controller in order to play those games.

I don´t know if this is a different explanation, or you understood it the first time, in that case, sorry again.

**Comment by aritztg** [comment]
No news, right?

**Comment by AniLeo** [comment]
Buzz controllers are now supported

**Comment by LuismaSP89** [comment]
@AniLeo But real buzz controllers? Or emulated buzz controllers using a controller. If the case is the 2nd, this can be closed.

**Comment by illusion0001** [comment]
Yes

**Comment by aritztg** [comment]
I bought a buzzers pack (on second-hand marketplace, 2€). They were perfectly detected by RPCS3! (although I couldn't make the game work).  So great work!

**Comment by bevanweiss** [comment]
@LuismaSP89 can you please clarify how you think the Buzz Controller 'could' be emulated?

I note that the original Buzz Controllers allowed for 4 Controllers attached to each USB connection.
And each Buzz Controller has 5 buttons on it (the large Red button, and four smaller choice selection buttons).

Normal controllers (like the DS3, DS4, XBox etc) may have more buttons individually, but certainly not in a similar arrangement as the Buzz Controllers, and not as many as the Buzz Controller supported as a system.

**Comment by LuismaSP89** [comment]
@bevanweiss There are many ways to do this, for example enable to the user for mapping each buzz controller button in each button of the ps3/ps4/xbox controller, like this:

red button - start
Buzz button 1 - triangle
Buzz button 2 - circle
Buzz button 3 - cross
Buzz button 4 - square

Or else you want. The question here is to map each buzz button to your controller/keyboard/etc. Yes, the colors are different for the buttons, but there's no way to avoid this unless you can edit the game images and change the buzz buttons for the ps3/ps4 buttons, like some others emulators like dolphin can do. I play for example in smash bros brawl with xbox buttons on the screen, by only editing 7 images.

**Comment by aritztg** [comment]
> @bevanweiss There are many ways to do this, for example enable to the user for mapping each buzz controller button in each button of the ps3/ps4/xbox controller, like this:
> 
> red button - start
> Buzz button 1 - triangle
> Buzz button 2 - circle
> Buzz button 3 - cross
> Buzz button 4 - square

This would be a great addition. Over the years, it may be harder to find and buy those controllers.

**Comment by LuismaSP89** [comment]
> > @bevanweiss There are many ways to do this, for example enable to the user for mapping each buzz controller button in each button of the ps3/ps4/xbox controller, like this:
> > red button - start
> > Buzz button 1 - triangle
> > Buzz button 2 - circle
> > Buzz button 3 - cross
> > Buzz button 4 - square
> 
> This would be a great addition. Over the years, it may be harder to find and buy those controllers.

Harder and expensive. Also the emulation points preserve the games and the consoles during the years. You can not simply depend on a specific device or controller wich can be broken or stop working.

**Comment by clamatac** [comment]
very interesting post, but, are buzz games playable in rpcs3?

**Comment by LuismaSP89** [comment]
Yes, they are "at least two months ago when I did the last test" there's no problem emulating this games since they're very simple on graphics side. The only reason to be not playable right now are the lack of emulated controllers.

**Comment by clamatac** [comment]
I have my ps3 with the buzz game and the buzzers controlers, If I use/connect the buzzers to my pc in usb ports, will they be emulated and I will have probles? or for using the real buzzers I will be able to play the game perfectly?

**Comment by AniLeo** [comment]
Real controllers work fine, this issue is about creating a virtual controller in RPCS3

**Comment by clamatac** [comment]
great, I will try it

**Comment by todestoast** [comment]
Is the buzz controller support only for the wired ones? Because I am trying to connect PS3 wireless buzzers. They get recognized by the Linux OS, but the game won't recognize them on boot...

**Comment by LuismaSP89** [comment]
Rpcs3 gots usb passthrough, so if you have wired ones it must work. Maybe it's only supported on windows?

You can also try with Zadig app to play with different usb drivers.

**Comment by todestoast** [comment]
As stated above I am trying to connect *wireless* ones - that's why I am asking if they're part of the official support mentioned by @AniLeo :)

**Comment by LuismaSP89** [comment]
Oh, sorry, I read wire instead of wireless.

This wireless version of buzz controllers are native for the ps3? Or are a ps4 controllers.

**Comment by todestoast** [comment]
They are native for ps3. ![wireless ps3 buzzers](https://upload.wikimedia.org/wikipedia/commons/7/7d/Playstation_2_3_Wireless_Buzzer.jpg)

**Comment by todestoast** [comment]
For everyone with the same issue/question:

Yes, the wireless controllers are fully supported (under Linux). What I missed is the udev-step described [here](https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories#On_Linux).

**Comment by Megamouse** [comment]
I think this has been implemented already.
Reopen if not

**Comment by LuismaSP89** [comment]
I can see that now is implement but in my case it doesn't work, anyway, since I don't know if this is related with this PR or a new bug, I opened a new issue (https://github.com/RPCS3/rpcs3/issues/10750) Thanks a lot.

**Comment by LuismaSP89** [comment]
> Official Buzz Controllers do connect fine to rpcs3 and each button press is recognized in any buzz game but it always freezes up the game and displays error
> PPU[0x1000000] Thread (main_thread) [0x00c785e8]} sys_usbd: Usb transfers are saturated
> this will need to be fixed before playing with official remotes. you can play with ps3 controllers with no issues

I'm using ps4 controller with emulated buzz controller and actually is not working, it doesn't detect the buttons.

**Comment by zeusin** [comment]
> Official Buzz Controllers do connect fine to rpcs3 and each button press is recognized in any buzz game but it always freezes up the game and displays error PPU[0x1000000] Thread (main_thread) [0x00c785e8]} sys_usbd: Usb transfers are saturated this will need to be fixed before playing with official remotes. you can play with ps3 controllers with no issues

I was having same problem, It was fixed changing the driver from WinUSB to libusb-k ( or maybe libusb-win32, can't remember right now ) in zadig.

**Comment by LuismaSP89** [comment]
> > Official Buzz Controllers do connect fine to rpcs3 and each button press is recognized in any buzz game but it always freezes up the game and displays error PPU[0x1000000] Thread (main_thread) [0x00c785e8]} sys_usbd: Usb transfers are saturated this will need to be fixed before playing with official remotes. you can play with ps3 controllers with no issues
> 
> I was having same problem, It was fixed changing the driver from WinUSB to libusb-k ( or maybe libusb-win32, can't remember right now ) in zadig.

But the default driver for DS4 controllers on windows is not WinUSB, is HidUsb. I tested your proposal using Zadig but RPCS3 doesn't recognized the controller anymore, not with WinUSB, libusb-win32, or libusb-k. Also other apps like ds4 windows stopped to recognized the controller. I needed to uninstall completely the driver from the device manager and reverted to the HidUsb wich is the only driver suitable for DS4 controllers under windows.

**Comment by Florin9doi** [comment]
> > > **Official Buzz Controllers** (...) always freezes up the game and displays error (...)
> > 
> > I was having same problem, It was fixed changing the driver from WinUSB to libusb-k (...) in zadig.
> 
> But the default driver for DS4 controllers on windows is not WinUSB (...)

DS4 in not an Official Buzz Controller. [This is](https://github.com/RPCS3/rpcs3/issues/4968#issuecomment-695312325) an official buzz controller.

**Comment by LuismaSP89** [comment]
Oh, sorry, bad reading xD. I thought you were talking about the ds4, since this post is to request emulated buzz controllers.
