### ISSUE TITLE
New Skate 3 glitch in 7180 LLVM SPU with xfloat

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#4978]

**Comment by niko1point0** [comment]
I made a mistake, this is what I meant to say:
Skate 3 7177 ASMJIT SPU: everything works fine
Skate 3 7177 LLVM SPU: game does not start
Skate 3 7180 LLVM SPU: player falls through floor no matter what
Skate 3 7180 LLVM SPU with accurate xfloat: player falls through floor whenever on skateboard

**Comment by AniLeo** [comment]
So.. there's no regression, game didn't start with SPU LLVM and now it does. What's the regression exactly? It doesn't work anymore with ASMJIT?

**Comment by niko1point0** [comment]
On second thoughts, ignore all that ^^
Pretend everything else doesn't exist, and just look at these three lines:
Skate 3 7177 LLVM SPU: game does not start
Skate 3 7180 LLVM SPU: player falls through floor no matter what
Skate 3 7180 LLVM SPU with accurate xfloat: player falls through floor whenever on skateboard

The truth is that 7180 didn't break anything, I was wrong about that. 
7180 (with accurate xfloat enabled) almost makes Skate 3 fully work in LLVM SPU, except for this one bug where the player falls through the floor while on the skateboard. I would be very happy if this bug could be fixed. Thank you for your time.

**Comment by niko1point0** [comment]
If you run skate 3 in RPCS3 7180: LLVM SPU with xfloat, you'll see what I mean. I'm sorry for the confusion.
