### ISSUE TITLE
red color with intel hd graphic 630 [BLES01276] Shadows of the Damned

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#4979]
![image](https://user-images.githubusercontent.com/16367065/44049013-8f46f1f2-9ef8-11e8-9eed-8c7bf97f6a86.png)

log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2284130/RPCS3.log.gz)

**Comment by Megamouse** [comment]
This should be caused ny upscaling, which isnt fully working on every game and a well known problem

**Comment by AniLeo** [comment]
This is usually caused by Anisotropic Filter values that not Automatic. Log shows Automatic though. Try settings like Strict Rendering Mode and/or Write Color Buffers.

**Comment by mkultimate** [comment]
@AniLeo @Megamouse the mentioned combinations are already made and the problem continues using vulkan, because with opengl it looks worse with the difference that red does not come out

**Comment by AniLeo** [comment]
Try with Threshold at 512x512 and Aspect Ratio 16:9, need to confirm this is not an Intel-only issue, which it doesn't appear to be

**Comment by AniLeo** [comment]
Still needing confirmation whether it's intel-specific or not

**Comment by kd-11** [comment]
Request to reopen if still an issue.

**Comment by zahdab** [comment]
It's not Intel related i am getting thi on nvidea as well
