### ISSUE TITLE
[Feature Request] Add options to title bar

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#4980]
In the title bar, we can see which graphics API we are using (OpenGL vs Vulkan)
I would like it if the title bar could display which SPU decoder we are using (ASMJIT vs LLVM)

**Comment by NeoSlyde** [comment]
It would be really nice if the **CPU model was shown in the title bar** so when people share screenshots or videos with no information we don't have to ask them what CPU they are using to get an idea of what performance we can expect.

**Comment by dio-gh** [comment]
Title bars have been customizable since #7478 and #7480. There are no variables exposed for the chosen PPU and SPU decoders I guess, but otherwise the requested feature is taken care of.

Closeable.
