### ISSUE TITLE
Skate 3 crashing trying to get out of the Skate.school

### ISSUE THREAD

**Issue by Technial** [RPCS3/rpcs3#4983]
Spec: 
OS: Windows 10
Ram: 8 gigs
Processor:Intel Core i3-6100T 3.20GHz, 3201 Mhz 
GPU: Intel HD Graphics 530

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2285079/RPCS3.log)

Ok so, whenever i try to teleport outside the training area my game crashes, whenever i try to free skate or customize character my game crashes as well, i just got this today and its my first time using an emulator i had other problems but i fixed those my problems myself.

**Comment by AniLeo** [comment]
That log file is empty, has no game run

**Comment by Asinin3** [comment]
You have to use preset skater, can't customize them at the moment. Please don't spam the issue tracker, you opened an issue just before this then closed it :/

**Comment by Megamouse** [comment]
There's already an issue for this: #3621
