### ISSUE TITLE
Red Dead Redemption: GOTY Edition black screen with TSX Enabled in build 7175

### ISSUE THREAD

**Issue by B-Knight49** [RPCS3/rpcs3#4986]
The build 7175 (which introduced memory improvements and performance improvements) caused RDR to no longer go in-game when TSX instructions are forced or enabled. The game boots, shows the intro logos and then goes to a black screen with a working framerate when it should go to the main menu (press START to continue). 

My Specs:

Intel Core i7-4790K | TSX Enabled
GTX 980Ti
16GB RAM

rpcs3-v0.0.5-7175-801089cf

**Comment by Cade-H** [comment]
Issue is also present in Midnight Club LA. #5004
