### ISSUE TITLE
regression after #4975 {KernelBase}

### ISSUE THREAD

**Issue by Rpcs3tester** [RPCS3/rpcs3#4990]
as it shown

after closing any game that error appears

![2018-08-14_22-52-43](https://user-images.githubusercontent.com/38118895/44114776-d2e6aa16-a014-11e8-8dae-4b4dfb9dfa3b.png)

**Comment by spyropt** [comment]
Same problem here

**Comment by HenningJW** [comment]
Log, system configuration? SMH ...

**Comment by spyropt** [comment]
i dont think a log will do much 
but here it is
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2288455/RPCS3.zip)

**Comment by EmulationChannel** [comment]
![rpcs3 master](https://user-images.githubusercontent.com/37957125/44118944-0a17d3a6-9fee-11e8-821d-26bc16160cb1.png)
