### ISSUE TITLE
Scott Pilgrim wont register clicks

### ISSUE THREAD

**Issue by dgray111** [RPCS3/rpcs3#4993]

**Comment by dgray111** [comment]
I launch the game and it goes to the main menu where it says press start but nothing i press works. I tried wth keyboard and ps4 controller but nothing.

**Comment by Syst3mSh0ck** [comment]
Either provide info or close the issue.

**Comment by legend800** [comment]
This is a setup issue. Close this issue and seek help using appropriate means (discord or forums).

**Comment by dgray111** [comment]
i commented the issue and already fixed it myself. thanks for the help.
