### ISSUE TITLE
Yakuza Kenzan! - SPU LLVM Pre-rendered graphical glitches

### ISSUE THREAD

**Issue by MsDarkLow** [RPCS3/rpcs3#4994]
rpcs3-v0.0.5-7195-23b52e1b_win64

Windows 10 | i7-8700K @ 4.5GHz | GTX 1070 | 16GB RAM

When using SPU LLVM the pre-rendered cutscenes have some weird graphical glitches on the brighest parts. The game has multiple pre-rendered cutscenes and this can be kinda annoying.
The pictures are self explanatory.
I believe this issue has persisted since the beginning of SPU LLVM implementation.

P.S: Using Accurate xfloat doesn't help the issue
P.P.S: Also happens on Yakuza 3, 4, and Dead Souls

SPU LLVM
![1](https://user-images.githubusercontent.com/9060436/44231743-0ae95e80-a197-11e8-8181-a6e814f551a2.jpg)

SPU ASMJIT
![2](https://user-images.githubusercontent.com/9060436/44231747-0cb32200-a197-11e8-9f4a-a96a8a1eec0d.jpg)

LLVM Log: 
[RPCS3KenzanSPULLVM.log.gz](https://github.com/RPCS3/rpcs3/files/2295074/RPCS3KenzanSPULLVM.log.gz)

ASMJIT Log: 
[RPCS3KenzanSPUASMJIT.log.gz](https://github.com/RPCS3/rpcs3/files/2295075/RPCS3KenzanSPUASMJIT.log.gz)

**Comment by programmargorp** [comment]
Appears to be fixed in Yakuza 3 using SPU LLVM and Accurate xfloat in 7736
![image](https://user-images.githubusercontent.com/11531066/51531471-61736b00-1ea2-11e9-914c-04ef1a54f1c1.png)

**Comment by MsDarkLow** [comment]
> Appears to be fixed in Yakuza 3 using SPU LLVM and Accurate xfloat in 7736
> ![image](https://user-images.githubusercontent.com/11531066/51531471-61736b00-1ea2-11e9-914c-04ef1a54f1c1.png)

**Comment by MsDarkLow** [comment]
> Appears to be fixed in Yakuza 3 using SPU LLVM and Accurate xfloat in 7736
> ![image](https://user-images.githubusercontent.com/11531066/51531471-61736b00-1ea2-11e9-914c-04ef1a54f1c1.png)
The issue still persists, whenever its with accurate xfloat or not.

![abc](https://user-images.githubusercontent.com/9060436/51545953-04a09200-1e5b-11e9-91a1-ed0bb2542c8e.jpg)

**Comment by programmargorp** [comment]
Sorry for incorrect report. Got tripped up on per game config with the game using SPU ASMJIT.
![image](https://user-images.githubusercontent.com/11531066/51570495-04a89c80-1f04-11e9-94c7-f7b58c9133b8.png)

Issue is not fixed.

**Comment by MsDarkLow** [comment]
Since #5762 has been merged, when using SPU Interpreter (Fast) this issue also occurs.

**Comment by arcadee1977** [comment]
Sonic Unleashed have the same issue, when use SPU LLVM, the opening movie have weird graphical glitches
![未标题-1](https://user-images.githubusercontent.com/47111657/55271802-dffae780-52ed-11e9-9dee-07f22d900333.jpg)

**Comment by elad335** [comment]
looking into.

**Comment by elad335** [comment]
Fixed by #5749 , the fix for xfloat will be supported soon as well.
Because appveyor fails because of llvm libs, heres the build 
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/3025388/rpcs3.zip)

**Comment by arcadee1977** [comment]
@elad335  OK，this issue is fixed !!

![未标题-1](https://user-images.githubusercontent.com/47111657/55275560-fa9b8380-5322-11e9-89ec-22a82a71de68.jpg)

**Comment by MsDarkLow** [comment]
@elad335 Your build completely fixes the issue, pretty nice!
![abc1](https://user-images.githubusercontent.com/9060436/55279489-d9319c00-5310-11e9-9c83-affeee161168.png)

**Comment by darkdragonz12** [comment]
![dbz](https://user-images.githubusercontent.com/39471183/55279898-9d301400-52db-11e9-852b-ae2e58f234fa.jpg)
 
dbz burst limit fix video work, great  work elad!

**Comment by darkdragonz12** [comment]
MASTER
![master](https://user-images.githubusercontent.com/39471183/55280029-44fa1180-52dd-11e9-8f17-65229a5b33e4.jpg)

PR
![dbz](https://user-images.githubusercontent.com/39471183/55279940-0c0d6d00-52dc-11e9-86c2-92cc4409e6fa.jpg)

 
fix dbz burst limit video on LLVM, great work elad!!

**Comment by MsDarkLow** [comment]
Fixed in #5749
