### ISSUE TITLE
Another Century's Episode R keeps small jumping

### ISSUE THREAD

**Issue by lsycxyj** [RPCS3/rpcs3#4997]
When I try to move ARX-7 of Full Metal Panic, it keeps jumping small steps which makes me difficult to move but I didn't press the jump button (the following picture shows that it's not standing on the ground).
![acer](https://user-images.githubusercontent.com/916567/44298408-38f4ad00-a315-11e8-816a-d21a658ee2e9.png)
It occurs when I upgrade RPCS3 from one version to another, and it's not related to certain versions. For example, This problem didn't occur when it's rpcs3-v0.0.5-7161-69af6074_win64, and after I downloaded rpcs3-v0.0.5-7195-23b52e1b_win64 and unzip and overwrote the files, this problem happens. The problem remains either I tried to clear all caches or unzip the old versions.  
This problem happened quite a few times. I had this problem and after a few days I upgraded to some version, the problem had gone. But after another few days I upgraded to another version, it came back again.

Hardware:  
E3-1230V2  @ 3.30GHz 3.70GHz
14gb DDR3  
Windows 10 Pro (1709 16299.547)
NVIDIA GTX 650 Ti Boost 2GB (Driver 388.13) with Vulkan

ASMJit Log:  
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2299395/RPCS3.log.gz)

Thank you very much.

**Comment by AniLeo** [comment]
Your GPU drivers are too outdated, need to update to latest and retest.

**Comment by lsycxyj** [comment]
After I upgrade my GPU driver to latest, the problem hasn't happened again.
