### ISSUE TITLE
#4920 seems to break Asura's Wrath

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5003]
https://github.com/RPCS3/rpcs3/pull/4920 which is 0.0.5-7175
The game works fine on https://github.com/RPCS3/rpcs3/pull/4787 which is 0.0.5-7166 but with 7175 few things happen
1.During the title screen(the cut scene with Press Start)will often don't have any sound
2.When you start a new game,the audio during the first cut scene may not load and the game WILL freeze at some point
3.If the above cut scene have sound,the game will play fine but the Episode 1 have so many cut scenes on which the sound randomly stop and once that happens,the game WILL freeze at some point.

This is the log while using 0.0.5-7175
At the title screen the sound plays for 15-20 seconds and then stop
Then I load my save and choose to replay episode 1
Then on the next screen the sound will either load or don't load(it played during the test)
The music did not play on the next screen and I played the game untill it freezes while switching cutscenes

There is some "AsyncIOSystem" in the log and if you are going to ask if I tried enabling "Disable Async shader compilation",then yes I did,I also tried OGL,SPU LLVM,Strict Rendering Mode,FPS set to 60,59,Off and Auto

If there is something I miss in my report,just tell me.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2299855/RPCS3.zip)

The game seems to freeze more often when the spu cache don't exist
And yes,I did tried the latest beta(0.0.5-7217),it was the first thing I tried

6700HQ
GTX1060
16GB
Win10

**Comment by Xcedf** [comment]
Mostly #4920 has nothing to regress, but some of my games may randomly hang after sound suddenly cuts off, which caused by https://github.com/RPCS3/rpcs3/pull/4920/commits/d1fd4d5000d72bac4b86f0a9c46ea70020d55d92 so i just reverted it to keep playing, try to revert it maybe it'll help

**Comment by Xcedf** [comment]
@vsub try this one https://mega.nz/#!TcImhSRK!bFXkYEqt9Ox1MHfzirjfz415roDKyzs8tAmnHDZlk44
it's a  bit old but contains all new changes and d1fd4d5 reverted, and tell if it works

**Comment by Xcedf** [comment]
Perhaps you should close ToV issue in favor of this one as a cummulative issue, as for me i reverted d1fd4d5 cause it breaks Uncharted 1 and GoW3 the same way

**Comment by jobs-git** [comment]
with or without that pull, I still get the same slowness and fatal :(

 @xcedf how were you able to run GOW3 at 27fps when d1fd4d5 is on revert?

**Comment by AniLeo** [comment]
@jobs-git 

> how were you able to run GOW3 at 27fps when d1fd4d5 is on revert?

TSX On and a good CPU

**Comment by Xcedf** [comment]
@jobs-git i've made some hacks based on latest SPU LLVM Xfloat
in this issue i've posted a build it contain this hacks, if you remove and recreate config file for GoW3 you will find in it a few new options:
Accurate FCXX: false
Accurate FM: false
Accurate FNMS: false
Accurate FS: false
Accurate FMX: false
The GoW3 and other game do not need whole Xfloat instruction set to look and work fine, for example 
GoW 3 only needs FNMS and FCXX to be true, but it will be a lot faster than LLVM with Accurate Xfloat or AsmJit

**Comment by vsub** [comment]
@Xcedf can you retest Ausra's Wrath but with SPU LLVM(this is the only thing I did not try because it takes so much time to compile the spu cache and waiting for that while doing tests is just annoying especially all those logos and intros)

It works fine with ASMJIT but the sound stops at the exact same place every time with LLVM if xfloat is not enabled(probably expected behaviour because maybe it needs xfloat)

I used the rpcs3 version you posted and I also tried the latest beta(the log is from the latest beta and I stop the game as soon the sound stops)

![2018-08-20_163009](https://user-images.githubusercontent.com/5032540/44350752-03c49800-a498-11e8-8d5e-b57eabd0828d.jpg)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2303002/RPCS3.zip)

**Comment by Xcedf** [comment]
@vsub sorry, i do not have Ausra's Wrath

**Comment by Wontell** [comment]
@vsub 
I can confirm that ASURA'S WRATH [BLUS30721] + RPCS3-7405, using LLVM sound disappears in exact point where you took that screenshot.

**Comment by Wontell** [comment]
@vsub 
I can confirm that ASURA'S WRATH [BLUS30721] + RPCS3-7405, using LLVM sound disappears in exact point where you took that screenshot.

**Comment by vsub** [comment]
RPCS3-7405
1.If xfloat is enabled,then the sound don't dissapear but the fps does down and the audio often stutters
2.If I disable xfloat,the the sound dissapears at the exact same place(screenshot)every time
3.With ASMJIT,the sound don't dissapear,the stuttering is a lot less often and the speed is better(like llvm without xfloat)

**Comment by kroaton** [comment]
I can confirm that this issue still exists with this version:
![image](https://user-images.githubusercontent.com/6411688/117080468-8d028280-ad46-11eb-9d2d-d01de10c78d5.png)

The game starts out fine but then audio cuts off.
