### ISSUE TITLE
Scott Pilgrim vs the World The Game

### ISSUE THREAD

**Issue by natalialuzak** [RPCS3/rpcs3#5007]
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC000001D.
Exception address: 000000001198c81c.
Instruction address: 000000001198c81c.
Function address: 000000001198c7e0 (base+0x198c7e0).
RPCS3 image base: 0000000000010000.

Illegal instruction exception occured.
Note that your CPU must support SSSE3 extension.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------
please help me

**Comment by Zardas81** [comment]
Exception 0xC000001D refers to an illegal or unsupported instruction. Either your processor doesn't support SSSE3, or you're running a 32-bit operating system.

Not an emulator issue.
