### ISSUE TITLE
[Regression] Purple overlay Issue

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#5009]
A year old regression. In most insomniac games and maybe oter games some parts or surfaces may be covered with purple overlay. Used Resistance 1 Demo as a testcase. The regression itself comes from #3200, commit d54c2dd3 but commit itself to complex for me to investigate, however i found some other commit that affects this 142bfb52 and changing line 2431 of RSXThread.cpp in current code
from vertex_push_buffers[index].vertex_count > 1)
to vertex_push_buffers[index].vertex_count > 0)
do this 
before (hud and crosshair are purrple)
![34](https://user-images.githubusercontent.com/7060586/44310900-b1776e80-a3e6-11e8-9be4-5b4eaab75fb6.jpg)
after (badly visible but normal colored)
![33](https://user-images.githubusercontent.com/7060586/44310906-d66be180-a3e6-11e8-8040-bab6779dff0b.jpg)

**Comment by kd-11** [comment]
At first the seemingly broken graphics threw me off, but watching demo footage on real hw, it seems that the purple overlay is the only major issue. I'm looking into it.

**Comment by kd-11** [comment]
Yea, confirmed to be a single byte ordering bug. The other 'issues' like the black stairway at the start of the demo are actually the same on real hw. Fix incoming ASAP.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/5047
