### ISSUE TITLE
Weird graphics corruption in Tales of Graces f since 7216

### ISSUE THREAD

**Issue by Metafalica** [RPCS3/rpcs3#5016]
W10, i5 660 3.3 GHz, Radeon HD 5750.
This game does not render most of graphics at all without "Strict rendering mode", but the problem is since 7216 even "Strict rendering mode" produce strange graphics artifacts. In 7195 there is no such issues.
![togf_ok](https://user-images.githubusercontent.com/5286295/44350508-15ee0880-a48f-11e8-9102-8af2d2d8f6ec.jpg)
![togf_bad](https://user-images.githubusercontent.com/5286295/44350522-20a89d80-a48f-11e8-8f16-fab62e700b5f.jpg)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2302994/RPCS3.log.gz)

**Comment by vsub** [comment]
Any reason why you are using OpenGL but yes,I also get weird things happening so it's not AMD gpu specific(I have nvidia card)

**Comment by AniLeo** [comment]
Radeon HD 5750 doesn't support Vulkan

**Comment by Metafalica** [comment]
This bug is no longer present in v0.0.5-7404, but I am not sure since when.
