### ISSUE TITLE
Skits unreadable (blurry) in Tales of Graces f

### ISSUE THREAD

**Issue by Metafalica** [RPCS3/rpcs3#5017]
W10, i5 660 3.3GHz, Radeon HD 5750. rpcs3-7216.
There is special feature in "Tales of" series called skits.  Characters chit-chat about something. This skits is totally blurred. The first image is how skits looks like on console.
![togf_skits_ok](https://user-images.githubusercontent.com/5286295/44350978-3c607380-a490-11e8-80c2-851c3fe97099.jpg)
![togf_skits_bad](https://user-images.githubusercontent.com/5286295/44350985-41252780-a490-11e8-9ff6-724fa3d0979c.jpg)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2303022/RPCS3.log.gz)

**Comment by vsub** [comment]
Looks like a duplicate https://github.com/RPCS3/rpcs3/issues/5016
They look fine(like your first screenshot)here but while using Vulkan not OpenGL

**Comment by AniLeo** [comment]
Closing as it's already reported fixed
