### ISSUE TITLE
BACKBREAKER VENGEANCE [NPEB00592]: Field texture cache gets corrupted after switching stadiums

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5020]
After changing from one field to another, the field turf get corrupted (texture/color, etc.).

Navigating here on first launch:
![2018-08-20 08_55_26-window](https://user-images.githubusercontent.com/20983844/44377652-95d99a00-a4b2-11e8-8149-284f1169b5cc.png)

Navigating here after playing in a different stadium:
![2018-08-20 08_54_07-window](https://user-images.githubusercontent.com/20983844/44377651-95d99a00-a4b2-11e8-8e42-47cf84465d86.png)

![2018-10-14 11_41_38-fps_ 19 81 _ vulkan _ 0 0 5-7438 _ backbreaker vengeance trial npeb00592](https://user-images.githubusercontent.com/20983844/46921037-46dc4c80-cfab-11e8-8593-747c2df03ad8.png)

Notes:
- No setting (even disabling save cache to hdd and clearing cache) impact this. 
- This was not an issue before and first started noticing it about a month or two ago.
- Affects OpenGL and Vulkan
- Probably related to this spammed error in log:
·W 0:21:40.340197 {rsx::thread} RSX: Format incompatibility detected, reporting failure to force data copy (VK_FORMAT=0x2C, GCM_FORMAT=0x82)
·W 0:21:40.340239 {rsx::thread} RSX: Format incompatibility detected, reporting failure to force data copy (VK_FORMAT=0x2C, GCM_FORMAT=0x82)
·W 0:21:40.340269 {rsx::thread} 

This affects (at least):
BACKBREAKER VENGEANCE [NPEB00592]
BACKBREAKER [BLUS30334]

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by Kravickas** [comment]
Turn off async shaders ?

**Comment by digitaldude555** [comment]
@legend800  well? the kd fixes are merged can it be closed?

**Comment by legend800** [comment]
@kd-11 , @digitaldude555 

The text corruption is fixed but this should remain open I think. WCB is still needed to prevent the original problem - field textures get corrupted after switching to a different stadium, at which point the game needs to be restarted to get correct looking fields. 

Not sure if we would count that as a bug so I'll defer to you guys. It does cause a massive perf hit and really the only thing holding this game back from perfection. 

Note: On VK, you need Blit + WCB, else the textures are all garbled since Jun 2018, which cause more of a speed hit. Tracking here:
https://github.com/RPCS3/rpcs3/issues/4775

**Comment by legend800** [comment]
Fixed by: https://github.com/RPCS3/rpcs3/pull/5675
