### ISSUE TITLE
FPS display bug

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#5021]
![glitch](https://user-images.githubusercontent.com/7824443/44382067-57a79f00-a4e1-11e8-8436-458c3aed56a5.PNG)

When I use RivaTuner Statistics and MSI Afterburner to record FPS, the FPS it gives me is always exactly double the FPS that RPCS3 gives me. My Nvidia Control Panel disables VSYNC for all games, and RPCS3 has a cap that locks FPS at 60. Can this contradiction be fixed?

**Comment by niko1point0** [comment]
Ya you're right, it was 2am when I wrote that, so I hadn't thought of a proper title

**Comment by niko1point0** [comment]
I actually tested 40 games

**Comment by vsub** [comment]
I am not sure if that is actually a bug because the same numbers are displayed on other emulators.

**Comment by vsub** [comment]
Btw sorry for the offtopic but how did you make afterburner/RTSS work with vulkan?
I have AfterBurner 4.5.0 and RTTS 7.1.0

**Comment by vsub** [comment]
Which version are you using @kd-11 
AfterBurner 4.5.0
RTTS 7.1.0
I also get double the speed set in Framelimit

**Comment by isshininu** [comment]
>RivaTuner
>Afterburner

Remember this software being a crapware, actually.

**Comment by vsub** [comment]
RPCS3 - Vulkan\OGL - double speed
PCSX2 - OGL - double speed,DX9\11 correct speed
PPSSPP - Vulkan\OGL - double speed,DX9\11 correct speed
ePSXe - OGL2.9 - double speed,OGL 1.78 correct speed
Citra - OGL correct speed
Cemu - OGL correct speed

**Comment by kd-11** [comment]
Looks like an issue with afterburner which isn't surprising. Btw, I still use the old version 4.4.2.

**Comment by kd-11** [comment]
3rd party issue, closing as wont fix.
