### ISSUE TITLE
RADV graphical glitches on Demon Souls

### ISSUE THREAD

**Issue by Lithium64** [RPCS3/rpcs3#5025]
![captura de tela de 2018-08-23 16-21-05](https://user-images.githubusercontent.com/10705488/44547268-e76f6800-a6f0-11e8-95f1-df5e0360138a.png)

Tested on:
Ubuntu 18.04 LTS
Mesa 18.1.6
i3-4150
AMD R7 260X 2GB VRAM
12 GB RAM

Log file
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2316728/RPCS3.zip)

**Comment by reaper185** [comment]
You should always upload the rpcs3.log file. Also what CPU are you using and how much RAM is installed in your device. This looks related to #4632

**Comment by Lithium64** [comment]
@reaper Thanks, i will upload the log file and my CPU is a i3-4150

**Comment by kd-11** [comment]
Cannot reproduce this with latest mesa and RPCS3.
