### ISSUE TITLE
Sly 4 crashes before reaching the menu in build 0.0.5-7231 

### ISSUE THREAD

**Issue by awad19977** [RPCS3/rpcs3#5026]
sly 4 crashes or hangs before reaching menu in the latest build with high cpu usage at 100%
Spec : i5-6300HQ - GTX 950 4GB - 8GB Ram 
![screenshot 4](https://user-images.githubusercontent.com/42657657/44553438-c416de00-a72d-11e8-9bae-9e5f05e87af5.png)

**Comment by Parthorisian** [comment]
Non TSX CPU. Works as usual [vid](https://streamable.com/6wg1d) 
[CooperSly_ThievesinTime_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2319285/CooperSly_ThievesinTime_RPCS3.zip)

**Comment by awad19977** [comment]
never mind it worked after build 7234
