### ISSUE TITLE
Fix the buffer view size for m_persistent_attribute_storage

### ISSUE THREAD

**Issue by kvark** [RPCS3/rpcs3#5028]
This is latest blocker for  #4996
Problematic code:
```cpp
//View 64M blocks at a time (different drivers will only allow a fixed viewable heap size, 64M should be safe)
const size_t view_size = (persistent_range_base + 0x4000000) > m_attrib_ring_info.size() ? m_attrib_ring_info.size() - persistent_range_base : 0x4000000;
m_persistent_attribute_storage = std::make_unique<vk::buffer_view>(*m_device, m_attrib_ring_info.heap->value, VK_FORMAT_R8_UINT, persistent_range_base, view_size);

```

Instead of taking 64M as a safe assumption, we should use `maxTexelBufferElements` in the exposed [limits structure](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPhysicalDeviceLimits.html). MacOS texel buffers can't exceed 16K, for example.

cc @kd-11

**Comment by kd-11** [comment]
@kvark Looking at vulkaninfo output from a mac with Iris graphics, the limit seems to be a lot more reasonable. Is this a gfx-rs limitation?

FTR
`maxTexelBufferElements                  = 0x40000000`

Btw, 16k is not enough, there are applications that can easily consume 4M at once if they use proper draw-call batching.

**Comment by kvark** [comment]
@kd-11 

> Lol, I'm not even sure 16k can fit the data requirements for some large draw calls.

Why do you even need to provide the draw call data in texel buffer textures? Can't you instead just bind the buffer directly as `UNIFORM_BUFFER`?

> Looking at vulkaninfo output from a mac with Iris graphics, the limit seems to be a lot more reasonable. Is this a gfx-rs limitation?

The fact that MVK is shipped in LunarG SDK for Mac doesn't make it correct :stuck_out_tongue_closed_eyes: 

What we do in Metal is casting a part of the buffer as a Texture, and thus it has to obey to standard texture size limitations. Reason why MVK reports a higher limit is because they give you a 2D texture, which is incorrect according to the spec (not to mention you have no way to find out what the height is):

> Uniform texel buffers define a tightly-packed 1-dimensional linear array of texels

**Comment by kd-11** [comment]
> Why do you even need to provide the draw call data in texel buffer textures? Can't you instead just bind the buffer directly as UNIFORM_BUFFER.

Afaik texel buffers were intended to overcome the uniform buffer size limitations in openGL implementations, with texel buffers expected to give access to huge chunks of VRAM while uniform buffers are much smaller. All things being equal texel buffers would be preferred as the data length is unknown to the shader.

> The fact that MVK is shipped in LunarG SDK for Mac doesn't make it correct
> Reason why MVK reports a higher limit is because they give you a 2D texture, which is incorrect according to the spec (not to mention you have no way to find out what the height is)

I don't understand why this is an issue. If the driver handles the 2D->1D coordinate unwrap transparently, isn't it effectively a 1D texel array? If they are indeed wrong and violating their own spec, then shouldn't a bug report be filed with khronos? 16k texel buffer length is a strange limitation, which is why I was asking if it is a hard limit imposed by metal. Its so small that any other type of storage makes more sense.

**Comment by kvark** [comment]
> Afaik texel buffers were intended to overcome the uniform buffer size limitations in openGL implementations, with texel buffers expected to give access to huge chunks of VRAM while uniform buffers are much smaller. All things being equal texel buffers would be preferred as the data length is unknown to the shader.

That makes sense. And it would be unfortunate if Vulkan Portability implementation on Metal would not provide this benefit, but it's still legal.

> If the driver handles the 2D->1D coordinate unwrap transparently, isn't it effectively a 1D texel array? 

I'd be hugely surprised, tbh. If you shader sees it as 2D texture while accessing the (N, 0) texels than you'll just get zeroes past the texture width size (which is at max 16K). If your shader sees it as a 1D texture, then Metal will either just ignore the rows above zero, or straight fire a validation error. That's what I expect from it, anyway.

I'll add it to my list to discuss on the Vulkan Portability call.

> If they are indeed wrong and violating their own spec, then shouldn't a bug report be filed with khronos?

Not with Khronos, but with MotenVK specifically. You can just file a bug report saying "MVK is not a conformant Vulkan implementation" :stuck_out_tongue_closed_eyes:

**Comment by kvark** [comment]
@kd-11 

> I'd honsetly be surprised if khronos endorsed MVK with such a glaring error

You might have misunderstood the whole endorsement thing. Khronos basically said "there is a library that translates Vulkan to Metal. It can run Dota2, but it's not conformant, so use at your own risk". MVK is not a Khronos project, it just happens to be owned Khronos github organization and bundled with LunarG SDK.

>  if accessing texel_buffer[limits.maxTexelBufferElements - 1] will return something untrue, isn't that an error?

It sure is an error! And until an implementation passes some kind of conformance test suite, there are many (known) bugs in it, like this one.

> I know metal supports buffer textures natively, why is it not possible to use those?

Which buffer textures do you have in mind?

I thought about this some more, and I think we'll be able to raise up the limit much higher eventually (to 1GB), but it would require heavy changes and can hardly be prioritized given that it doesn't improve the CTS coverage. The idea would be to generate indexed buffer access code in SPIRV-Cross for those texel buffers. This way we wouldn't need to create a metal texture placed on the buffer.

**Comment by kvark** [comment]
Apparently, things are not as bad as I thought. SPIRV-Cross supposedly handles that 2D texture and addresses it accordingly, so we can expose the same (higher) limit for the texel buffers as MVK.

**Comment by kd-11** [comment]
> Which buffer textures do you have in mind?

Quoting directly from the Metal Shading Language spec, v2.1, Section 2.8.1 - Texture Buffers

> 2.8.1 Texture Buffers
> All OS: texture buffers supported since Metal 2.1. A texture buffer is a texture type that can access a large 1D array of pixel data and perform dynamic type conversion between pixel formats on that data with optimized performance.
> ...
> A texture buffer can support more texture data than a generic 1D texture, which is limited to a width of 16384. However, a texture buffer cannot be sampled.

I had done a feasibility check on how difficult it would be to use metal on rpcs3, and I distinctly remembered that texture buffers were supported. It is also clearly inferred that the 16k 1D limit is far too small which is why texture buffers are added in metal 2.1.

If possible to use this, it would be better imo than using textureSize() math to decode the 2D block into a linear array.

**Comment by kd-11** [comment]
Thanks. I see you went the 2D route, is metal's support for texture buffers really that bad? Every other API supports it natively pretty nicely.

**Comment by kvark** [comment]
Well, you quoted the texture buffer support from MSL 2.1. I wasn't aware of them, and I don't think SPIRV-Cross uses them at this moment. It does, however, fiddles with buffer access indexes to route the texel fetches into 2D texture properly, and that's something I didn't know, so now we do the same thing as MVK. If that's not enough, we can easily extend to 3D ;)
