### ISSUE TITLE
Regression: Medal of Honor [BLES01067] doesn't load (#4975)

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#5030]
Medal of Honor [BLES01067] doesn't load and shows error window.
[Medal_of_Honor.zip](https://github.com/RPCS3/rpcs3/files/2318899/Medal_of_Honor.zip)
https://github.com/RPCS3/rpcs3/pull/4953:
![medal_of_honor_ 7182](https://user-images.githubusercontent.com/14265316/44592573-a6975200-a7c9-11e8-90f6-cd331b163e03.png)
https://github.com/RPCS3/rpcs3/pull/4975:
![medal_of_honor_ 7186](https://user-images.githubusercontent.com/14265316/44592582-ab5c0600-a7c9-11e8-88e0-3cc3a7b5c18e.png)

**Comment by Asinin3** [comment]
DREAM C CLUB ZERO Special Edipyon! [BLJS10208]
Regressed to nothing.

RPCS3 v0.0.5-7182-57ba9d393 Alpha
Intro, shows loading graphic then gets stuck on black screen.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2342535/RPCS3.log.gz)


RPCS3 v0.0.5-7186-aa4040bb7 Alpha
Nothing, opens game window and crashes rpcs3 with a fatal error instantly. 
![image](https://user-images.githubusercontent.com/15137035/44948118-c94beb00-ae07-11e8-81f5-db60e537f0ee.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2342537/RPCS3.log)
