### ISSUE TITLE
build faild on visual studio 2017 15.8.1

### ISSUE THREAD

**Issue by yxmline** [RPCS3/rpcs3#5035]
build faild on visual studio 2017 15.8.1 at https://github.com/RPCS3/rpcs3/commit/c30a7c00412f821e1b894e5f11ec22b2459a8bdc
error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior.
files:
Emu\Cell\lv2\sys_ppu_thread.cpp 
Emu\Cell\lv2\sys_spu.cpp
Emu\Cell\Modules\cellAdec.cpp
Emu\Cell\PPUModule.cpp
Emu\Cell\Modules\cellDmux.cpp
Emu\Cell\Modules\cellFs.cpp
Emu\Cell\Modules\cellGcmSys.cpp
Emu\Cell\Modules\cellSpurs.cpp
Emu\Cell\Modules\cellVdec.cpp
Emu\Cell\Modules\libmixer.cpp
Emu\Cell\RawSPUThread.cpp
Emu\System.cpp

**Comment by Nekotekina** [comment]
Try #5033

**Comment by yxmline** [comment]
thank

**Comment by yxmline** [comment]
solved at https://github.com/RPCS3/rpcs3/commit/93a9201316f1d6d93c225664b9d667983bed5745
