### ISSUE TITLE
Persona 5 [NPUB31848] Stuck on First Loading Screen

### ISSUE THREAD

**Issue by Oky12** [RPCS3/rpcs3#5036]
hi... i have problem with my persona 5. this game stuck on first loading Screen. but the game not freeze or Crash. only Stuck and no respone. i try wait until 1 hours and not happen. 

i am using RPCS3 0.0.5-7234

my Spec 
CPU : Amd A8-7410 2.20Ghz
RAM : 8 Gb 
GPU : AMD Radeon R5 M430
Windows : Windows 10 Home 64bit

LOG : 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2320773/RPCS3.log.gz)

Screenshot
![08d049cd-7d8e-42ae-9507-ac074861aaa6](https://user-images.githubusercontent.com/30838114/44619266-c6a04180-a8ad-11e8-8031-7911f5515050.png)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
