### ISSUE TITLE
Add comma to description

### ISSUE THREAD

**Issue by mwarning** [RPCS3/rpcs3#5042]
`The world's first open-source PlayStation 3 emulator/debugger written in C++ for Windows and Linux.`
=>
`The world's first open-source PlayStation 3 emulator/debugger, written in C++ for Windows and Linux.`

Otherwise it would mean that there might be another emulator that might be written C++ but may only target Windows. It might be wrong here, since I am no native speaker.

just my2cents :-)

**Comment by JohnHolmesII** [comment]
Indeed. Just PR it.

**Comment by mwarning** [comment]
On my way. To make a PR for this is golden. :D
