### ISSUE TITLE
Broken vertices in Grand Theft Auto: San Andreas

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#5044]
@kd-11 
This game has only broken character models.
![bez tytulu1](https://user-images.githubusercontent.com/38318848/44674171-02ade080-aa2d-11e8-9bfb-034f170896ab.png)

I uploaded `RenderDoc` capture because `RSX Capture` doesn't work in this game.

**RenderDoc v1.1:**
[GL-rdc capture](https://mega.nz/#!lcYRSAaT!ClxmxKHGBWU_EfY8A1oxkYqcjBVb5PXepHHvtlCuL3w)
[VK-rdc capture](https://mega.nz/#!YEIDgIrD!Ax6UnG9dhlKVCFPYSBUy_P0obYNNo6yq9eDECqahKBA)

**Comment by kd-11** [comment]
Broken matrix palette skinning. Looks like some vec opcodes need precision tuning.

**Comment by kd-11** [comment]
Figured out what was wrong with this, a fix will be made available soon.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/5125
