### ISSUE TITLE
RSX: Dialog input loop exited with error code=-3 Need For Speed Rival

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#5052]
the game starts but when you get to this image the pad does not respond the fps keep running

![image](https://user-images.githubusercontent.com/16367065/44787879-02f9c900-ab5e-11e8-84f9-7d3b23fcd77e.png)

log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2332098/RPCS3.log.gz)

**Comment by kd-11** [comment]
known issue, disable native dialogs to bypass this

**Comment by Megamouse** [comment]
See #4072
