### ISSUE TITLE
Regression: Trophies (#4871)

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5056]
Backbreaker series and other titles now freeze on loading main menu (trophy related). See log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2333538/RPCS3.log.gz)

Broken by this:
https://github.com/RPCS3/rpcs3/pull/4871 

Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by Xcedf** [comment]
Confirm, i have infinite installing trophies in Tekken 6 after #4871

**Comment by raveskirza** [comment]
Tekken 6, tekken tag tournament 2 are now only Intro
Soul Calibur V has the "Installing Trophy " Overlay persistent on the screen. 
![image](https://user-images.githubusercontent.com/28158623/44947412-c5ee3a80-adda-11e8-9ed4-d2cb8695ba17.png)

**Comment by joshuacode751** [comment]
This regression not fixed yet?

**Comment by AniLeo** [comment]
No, otherwise the issue would have been closed.
