### ISSUE TITLE
RSX:God of War Ascension™ (Demo)

### ISSUE THREAD

**Issue by EmulationChannel** [RPCS3/rpcs3#5057]
Test RPCS3 Master Build: 685eaedb

E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x60300510
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x60300520
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2334015/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2334016/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/2334017/TTY.log)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to **submit Game Compatibility reports**. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
