### ISSUE TITLE
[Feature Request] Multithreading for Building SPU Cache

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#5058]
When I use LLVM SPU with accurate xfloat in RPCS3 7273, with an Intel i7-7700HQ, it takes around four full minutes for the SPU cache to be built, in any game, and I noticed that RPCS3 only used 10% of my CPU to build the SPU cache.

Is there any way to use multithreading to build the SPU cache, so that it can be built faster?

**Comment by vsub** [comment]
I was actually going to ask the same thing.
When I open Process Hacker,I notest that only one core is maxed out(out of 4 and 4HT)
The marked is from the dialog appearing until the building is done.

![cpu](https://user-images.githubusercontent.com/5032540/44863057-fcf60c00-ac73-11e8-85ff-d5eba55b41bb.jpg)

This is while creating ppu modules
![ppu](https://user-images.githubusercontent.com/5032540/44863395-ed2af780-ac74-11e8-8882-d2ebdbb942c2.jpg)

And this while compiling shaders
![shaders](https://user-images.githubusercontent.com/5032540/44863411-f916b980-ac74-11e8-9bed-5de8a6889f44.jpg)

**Comment by kd-11** [comment]
Implemented in https://github.com/RPCS3/rpcs3/pull/5586
