### ISSUE TITLE
P5 : NPCs Whisper popups Wrong color

### ISSUE THREAD

**Issue by M220** [RPCS3/rpcs3#5061]
When NPCs are Talking, their "Whisper"s have a pink color ( and it's supposed to be white )

Screenshot of the bug : 
![untitled](https://user-images.githubusercontent.com/26696487/44873537-c341f700-acad-11e8-8a11-b747a7b4b8e5.png)
it's supoosed to be something like this : 
![untitled](https://user-images.githubusercontent.com/26696487/44873612-f5ebef80-acad-11e8-8dfe-c11478211c3d.jpg)
I finished the game around three month ago and I never saw that bug happening so it's definitely a regression but I didn't found the PR that caused this.
I have a GTX1080Ti with Nvidia Driver Version 399.07

**Comment by HerrHulaHoop** [comment]
Have you tried #5047? It might help.

**Comment by M220** [comment]
Yeah, tried it but unfortunately Bug is still present :(

**Comment by kd-11** [comment]
Check if its still an issue. I gave up looking for the word "whisper" but all the other npc text and symbols are ok.

**Comment by M220** [comment]
It's still an issue and if you want to get this Bug, just go to station Square and Go to Ginza Line From there, there's two person "Whispering" there, and you can see the bug when their whispers pop ups show up 😬

**Comment by vsub** [comment]
It could be video drivers problem or game version specific.
I tried few versions from 0.0.5-7161 to the latest 0.0.5-7261 and that word is always white(maybe it happens only on specific places)

I am using default settings and 150% scaling(1920x1080)
i7-6700HQ,GTX1060 and not the latest gpu drivers(397.64)
![2018-09-08_145527](https://user-images.githubusercontent.com/5032540/45254861-36ff9600-b377-11e8-890e-8b58bcb1a9ac.jpg)

**Comment by Zardas81** [comment]
Purple means you have to eavesdrop on that conversation for a quest. Normal game behavior, not an issue. Can be closed.

**Comment by M220** [comment]
I'm Very Sorry For My Mistake then 😶❤️
