### ISSUE TITLE
Idea to encourage more people to donate

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#5070]
On the Patreon, I am always able to see how much money is currently being donated to the RPCS3 Team. Can you please post graphs that shows how much growth there has been in donations over the last 12 months?

I would like to see graphs for number of donators, total amount of funds being donated, and average donation per donator, over the past 12 months. I strongly believe that these graphs can inspire more people to donate

**Comment by VelocityRa** [comment]
These sorts of stats are publically availale from websites like Graphtreon:
https://graphtreon.com/creator/Nekotekina

**Comment by VelocityRa** [comment]
These sorts of stats are publically available from websites like Graphtreon:
https://graphtreon.com/creator/Nekotekina

**Comment by AniLeo** [comment]
This is already provided by Patreon as indicated by @VelocityRA
