### ISSUE TITLE
project diva F - Pink overlay? (opengl)

### ISSUE THREAD

**Issue by AkagiShiroe** [RPCS3/rpcs3#5073]
i dunno if this was only my hardware or something else, just want to put it here.
![152](https://user-images.githubusercontent.com/14356240/44958428-297f8180-af1b-11e8-8338-13e96957aeb7.png)
rpcs3-0.0.5-7272-9acaee56-alpha

**Comment by vsub** [comment]
Need more info.
I just tried the latest beta and it works fine...in could be only on certain stages(that I did not tried)or amd gpu specific

**Comment by 13xforever** [comment]
Please follow the [guidelines](../blob/master/.github/CONTRIBUTING.md) and provide the required information, including your system information and logs. Otherwise this issue is useless.

**Comment by AkagiShiroe** [comment]
LLVM with ASMJIT and pretty much normal settings. as for spec. it's fairly old hardware which i only use for testing purposes.
Intel Core I3 540 (Westmere,3,0ghz,2 core,4 thread)
NVIDIA 9600GT 512mb (Full compability upto 3.3 and partial 4.x)
RAM 8GB
you may close it if this doesn't make sense at all since im using old hardware. but im just providing information xD

**Comment by vsub** [comment]
Is that on all stages or just in that one?
Can you post your save and tell me which stage is that...also post the log(that will tell me exactly what settngs you are using)after loading that stage and close rpcs3

**Comment by AkagiShiroe** [comment]
i believe only stage that have "flare" like effect. as you could see in this three songs:
![1](https://user-images.githubusercontent.com/14356240/44993793-d408aa80-afd6-11e8-8128-097f99b269b8.jpg)
![2](https://user-images.githubusercontent.com/14356240/44993796-d66b0480-afd6-11e8-90f6-f06619081b90.jpg)
![3](https://user-images.githubusercontent.com/14356240/44993800-d79c3180-afd6-11e8-96d9-e2e4b5bc7d72.jpg)
![4](https://user-images.githubusercontent.com/14356240/44993803-d8cd5e80-afd6-11e8-9e32-e42d9c237a82.jpg)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2345994/RPCS3.zip)
^last log for last screenshot
also here comparison using my older RPCS3 version 7138 (before i update to 7282) and this version was a lot slower than 7282 for my rigs.
![5](https://user-images.githubusercontent.com/14356240/44993913-4da09880-afd7-11e8-9718-be7f85b21105.png)
![6](https://user-images.githubusercontent.com/14356240/44993914-4da09880-afd7-11e8-895d-f92d235af5f6.png)
[RPCS3_2.zip](https://github.com/RPCS3/rpcs3/files/2346003/RPCS3_2.zip)
^here some log (using same LLVM cache and same settings with same shader cache)
also here my settings:
![8](https://user-images.githubusercontent.com/14356240/44993967-83458180-afd7-11e8-926d-1c370c8a136f.png)
(its an 10 year old hardware for testing purposes, so i use lower resolutions)

**Comment by AniLeo** [comment]
Since your card only has OGL 3.3 support, I'll ping @kd-11 for the decision whether to consider this a wontfix or not

**Comment by AkagiShiroe** [comment]
![1567](https://user-images.githubusercontent.com/14356240/45000151-7dfb2d80-affd-11e8-8ff2-fcd59703915c.jpg)
on 7290, it start producing weird artifact and blue overlays.

**Comment by AkagiShiroe** [comment]
looks like this one are safe to close, i found the culprit.. when i tried to run the game at normal resolution artifact didn't pop-out. i don't know if upscaling was affected too since i barely could handle 720p.
@AniLeo @kd-11
