### ISSUE TITLE
Sonic Unleashed motion blur

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#5074]
I have tested Sonic Unleashed on RPCS3, and on a real PS3. Right now, the FPS on RPCS3 is higher than native PS3 (on 8700k overclock). However, RPCS3 still looks laggy at 40fps while PS3 looks fine at 20fps. Could this be a motion blur problem? Does RPCS3 support motion blur yet, or has it been disabled to prevent glitches?

**Comment by AniLeo** [comment]
Closing issue, please use the forums for such discussions
