### ISSUE TITLE
GL/Vulkan: Sly 3 graphical issues

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#5079]
Tested with https://github.com/RPCS3/rpcs3/commit/ca5158a03e5ca66623ff39c8bda7185a51a05e9e.

These errors have been there since June 2018, when Sly PS2 games went ingame.

- [x] Screen covered by the rendering of two/three cameras (Episode 3 and 4 missions) - Fixed in #6224
- [ ] Broken shadow on characters (Vulkan only)

[Settings used (GPU tab)](https://user-images.githubusercontent.com/20027681/45015944-82d2d800-b023-11e8-9b57-179f67b7ef6d.png)

<details>
 <summary>Two/Three cameras rendering issue</summary>

![image](https://user-images.githubusercontent.com/20027681/45015534-5bc7d680-b022-11e8-8976-0da08e6f1734.png)
![image](https://user-images.githubusercontent.com/20027681/45015339-ae54c300-b021-11e8-9953-4dc694b29667.png)

Screenshot taken with PPU interpreter fast and SPU interpreter precise, no visual differences:
![image](https://user-images.githubusercontent.com/20027681/45015462-12778700-b022-11e8-82c3-8a1b3727025f.png)
</details>
<details>
<summary>Shadow issue</summary>

**OpenGL** (correct):
![image](https://user-images.githubusercontent.com/20027681/45015918-70f13500-b023-11e8-8943-e82fa35231cd.png)
**Vulkan** (wrong):
![image](https://user-images.githubusercontent.com/20027681/45015804-1bb52380-b023-11e8-9f0d-7ff89e171188.png)

Also happens in Sly 2:
![image](https://user-images.githubusercontent.com/20027681/45017248-6cc71680-b027-11e8-8a9c-eb7b88142adc.png)

</details>

[Log Vulkan](https://github.com/RPCS3/rpcs3/files/2347608/Log.Sly.3.4-9-18.VK.gz)
[RenderDoc](https://drive.google.com/open?id=18SPpU1DD7TZIOwW4ZKjuMytmHD8kabVT)

**Comment by MarioSonic2987** [comment]
With 0.0.6-7886, it still has the bugs mentioned previously. I attached a RSX capture of the triple camera bug.

[RSX Capture (triple cameras bug in Episode 3 of Sly 3)](https://github.com/RPCS3/rpcs3/files/2985863/Capture.Triple.Camera.Sly.3.zip)

**Comment by MarioSonic2987** [comment]
With #6224, fixes double camera issue:

![sly3_before](https://user-images.githubusercontent.com/20027681/62307017-22daf080-b483-11e9-8bd6-c1efb9fb5070.png)
![image](https://user-images.githubusercontent.com/20027681/62306787-c2e44a00-b482-11e9-9a5c-9286693e6f2c.png)

Also fixes double camera issue in Dragon Ball: Raging Blast during some superattacks, cutscenes and in Player 1 vs Player 2 battles.

**Comment by digitaldude555** [comment]
@MarioSonic2987 still broken?

**Comment by MarioSonic2987** [comment]
@digitaldude555 
Shadows are still broken in Vulkan.
<details>
<summary>Images</summary>

![image](https://user-images.githubusercontent.com/20027681/75380715-d1d79180-58d7-11ea-82b5-069361586eed.png)
![](https://cdn.discordapp.com/attachments/348932810452500492/682310004388528207/unknown.png)
</details>

**Comment by kd-11** [comment]
Need a more recent RSX capture of the shadow issue so I can start work on it.

**Comment by MarioSonic2987** [comment]
PR #7798 breaks Carmelita's face in the first mission of Episode 1:

**Pre-PR 7798**:
![image](https://user-images.githubusercontent.com/20027681/81483192-a27cc380-923c-11ea-94a7-131e3c86e726.png)
**PR 7798 and newer**:
![image](https://user-images.githubusercontent.com/20027681/81483196-a6104a80-923c-11ea-9dbb-995f2e1b60e2.png)

**Comment by kd-11** [comment]
Are shadows still broken though? PPU issue from that PR would be in @Nekotekina's domain.

**Comment by MarioSonic2987** [comment]
Shadows are still broken with PPU interpreter fast:

![image](https://user-images.githubusercontent.com/20027681/82125468-64385480-97a6-11ea-87db-6205d00b7989.png)
![image](https://user-images.githubusercontent.com/20027681/82125369-d9575a00-97a5-11ea-926f-04bf6a6b61b6.png)

It's only present with Vulkan.

**Comment by kd-11** [comment]
@MarioSonic2987 I need more recent RSX captures. The ones from over a year ago no longer run properly on rpcs3.
