### ISSUE TITLE
Diablo III [BLES01922] and Diablo III: Reaper of Souls – Ultimate Evil Edition [BLES02036] - gamedata bug

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [RPCS3/rpcs3#5084]
Diablo III [BLES01922] and Diablo III: Reaper of Souls – Ultimate Evil Edition [BLES02036] does not create gamedata (not installs to HDD). Real console does.

**Comment by AniLeo** [comment]
Missing RPCS3 log file

**Comment by gandalfthewhite19890404** [comment]
[Diablo3_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2353278/Diablo3_RPCS3.log.gz)
[Diablo3RoS_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2353279/Diablo3RoS_RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
You can install it by going to `More->Install game` from its main menu.

**Comment by gandalfthewhite19890404** [comment]
I mean - why game does not installing automatically like real console does?

**Comment by RainbowCookie32** [comment]
I don't see how this is an issue, especially when considering that the game installing itself in RPCS3 is a waste of time and space.

**Comment by MSuih** [comment]
I can find multiple sources saying that d3 didn't have mandatory install on PS3. Are you certain that it always installed data on real PS3? 

And yes, not having to install stuff on emulator is a good thing, even if it's inaccurate.
