### ISSUE TITLE
Macross 30 [BLJS10184] game goes black screen after finished game loading screen

### ISSUE THREAD

**Issue by reshuter** [RPCS3/rpcs3#5090]
![1](https://user-images.githubusercontent.com/26632345/45173416-59d46200-b232-11e8-919f-64262dc32211.PNG)
![2](https://user-images.githubusercontent.com/26632345/45173417-5a6cf880-b232-11e8-8c30-4e05796eb395.PNG)
![3](https://user-images.githubusercontent.com/26632345/45173418-5a6cf880-b232-11e8-9cae-8bbbfe4751a9.PNG)
![4](https://user-images.githubusercontent.com/26632345/45173419-5a6cf880-b232-11e8-9572-52b52fe079a6.PNG)

I tried to find information on the internet about black screen issue but it didn't help me to fix this game 

PC Spec
Core i 5 6600k
GTX 970 SLI
Ram 16 gb

**Comment by reaper185** [comment]
@reshuter Always include the RPCS3.log.gz

**Comment by AniLeo** [comment]
Removed huge copy pasta flood from emulator. Missing RPCS3.log.gz as indicated.

**Comment by miguel-nunes** [comment]
This probably related to the problem that happen when cinematics finish to play in Valkyria Chronicles and Super Street Fighter IV Arcade Edition. The same scenario happens in Macross 30. I've been testing recent releases to see if this bug is fixed. The same bugs seems to affect those 3 games in the same way.

**Comment by reshuter** [comment]
@miguel-nunes i have been waiting for a long time but it still black screen and no sound
i had watched in youtube, they use same setting as me and when boot the game cinematics poped up

**Comment by reshuter** [comment]
@AniLeo how do i get RPCS3.log.gz

**Comment by AniLeo** [comment]
After getting the issue close the emulator and upload RPCS3.log.gz which is on the main emulator folder.

**Comment by raveskirza** [comment]
@reshuter why are you using default resolution 1920x1080? You are not supposed to change that.

**Comment by reshuter** [comment]
@raveskirza i already tried both default and 1920x1080

**Comment by reshuter** [comment]
@AniLeo 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2361948/RPCS3.log.gz)

**Comment by kd-11** [comment]
An update. I recently debugged a different bug with this title. The game is completely paused when this happens, but I did not bother going too deep into it. Thing is, it boots just fine on linux and runs with good performance. This bug is windows-only.

**Comment by digitaldude555** [comment]
Needs wcb but seems to go ingame now can close.

**Comment by muhammadwibisonojanuar** [comment]
I just got frozen after loading. Even if it works, i just got 15 fps.
Specs:
-20gb ram
-GTX 950M
Intel 6700hq

**Comment by petran79** [comment]
> An update. I recently debugged a different bug with this title. The game is completely paused when this happens, but I did not bother going too deep into it. Thing is, it boots just fine on linux and runs with good performance. This bug is windows-only.


Yes, on Linux it plays fine.

For Windows users, a save game of the first level that skips the videos that freeze the game, in case you want to test performance 

[BLJS10184_SAVEDATA_00.zip](https://github.com/user-attachments/files/22741382/BLJS10184_SAVEDATA_00.zip)
