### ISSUE TITLE
Regression - After Burner Climax Fog bug (Vulkan/opengl)

### ISSUE THREAD

**Issue by pepodmc** [RPCS3/rpcs3#5100]
Windows 10
Geforce 750 TI (Driver 388.71)

![d9bb4cfe-e16a-11e5-9636-afbbadf2b9fc](https://user-images.githubusercontent.com/4150364/45254330-eb37f700-b34c-11e8-8c93-7b3f6c752241.png)

**Comment by Zangetsu38** [comment]
What is this old screen with very old build ?

**Comment by AniLeo** [comment]
Driver too old, issue has no relevant information at all. This is likely not an issue on the most recent master too.

**Comment by Asinin3** [comment]
Actually I reported this to kd already about a week ago. It happens to me too and surfaced after https://github.com/RPCS3/rpcs3/pull/5086

**Comment by AniLeo** [comment]
Nope, that PR is 3 days old and supposed to fix it, you mean the reset one by elad

**Comment by Asinin3** [comment]
It's definetely one of kd's PRs, I assumed the fog one but maybe one before that. https://cdn.discordapp.com/attachments/442667232489897997/484104988268691456/unknown.png
