### ISSUE TITLE
Ni No Kuni [BLES0555] - Verification Failed Freeze

### ISSUE THREAD

**Issue by hockland** [RPCS3/rpcs3#5105]
Previously I'd only encountered this on the odd occasion, but on reaching the boss "Moltaan" of the Volcano location, this particular freeze is encountered on all attempts that I've made. Making the game unplayable (in terms of being able to beat the game). Up until this point, I'd only encountered this freeze on rare occasions. For this boss though, it happens every single time. Though of differing amounts of time in each test. Sometimes it occurs within 3-5 seconds, and other times it's not for a few minutes.

Some log snippets:

E {rsx::thread} RSX: 2048 x 720 vs 1024 x 720
E {rsx::thread} RSX: Cached object for address 0xCB150000 was found, but it does not match stored parameters.
E {rsx::thread} RSX: 2048 x 720 vs 1024 x 720
F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkcompute.h:137)
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01dd5ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/HDD_GAMEDATA/hd05.adat” [x6]
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01dd5ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/HDD_GAMEDATA/hs06.adat.sdat” [x6]
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01dd5ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES01555/USRDIR/HDD_GAMEDATA/hs06.adat.sdat” [x6]

[log.txt](https://github.com/RPCS3/rpcs3/files/2365917/log.txt)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2365947/RPCS3.log.gz)

Tested under RPCS3 #5102.

System specs:

Intel Core i7-4790K CPU @ 4.00GHZ 
16GB RAM
GPU: NVIDIA GeForce GTX970
Windows 7 PRO, 64 bit

**Comment by HerrHulaHoop** [comment]
Please don't spam the post with log entries. Just upload the rpcs3.log.gz. 

If you must post snippets, try to keep it below 5 lines. Anything more and the you're better off giving the full log.

**Comment by hockland** [comment]
Patience young padawan. The log is at the end of the post.

**Comment by kd-11** [comment]
You can bypass this error with openGL where compute is not used to do work since the driver does conversions automatically. I'm not sure why some titles are using so much compute resources that the queue fills up so fast.

**Comment by hockland** [comment]
Tested openGL and that did indeed fix that. Not had that error since. Still be good to see it fixed under Vulcan.

**Comment by psennermann** [comment]
Just for curiosity: while in-game could you try to set rpcs3 process priority to "real time" and see if it fixes this costant crash? I ask because I've always done this to get rid of NiNoKuni Vulkan random crashes...

**Comment by Asinin3** [comment]
Provide us the save file so we can try to reproduce this please. Also, when you first posted the issue it was just a massive log spam and no log file then you edited your post and pretended like that never happened :laughing:

**Comment by hockland** [comment]
Sorry about that. HerrHulaHoop's comment was very quick after I'd posted.

As for a saved game. The problem I have now is that in the end I managed to proceed past that point in the game (after switching to OpenGL). So the save I have now is much more later on.

**Comment by Niroc** [comment]
RPCS3 crashed for me on that boss fight a couple of time but, I managed to get through on the third attempt.

version "rpcs3-v0.0.5-7229-f3d3a1a4_linux64.AppImage" got me through it, the SPU was set to ASMJIT... if your itching to play through the game, try that build. Though I do run RPCS3 on Linux as RPCS3 is CPU heavy and Linux has superior thread handling because of WIndow's "Easy to Maintain" micro kernel.  Also, if the audio degrades and begins to stutters, just restart.

Specs:
Intel Core I7-4710MQ @ 3.4Ghz
16 GB @ 1867 Mhz (Dual channel)
gpu: 870M (Yes it's a Laptop)
Ubuntu 18.04 64bit

Great work on RPCS3 btw

**Comment by CrabLugo** [comment]
So i've finished volcano location on current master using vulcan and i didn't encounter even a single issue. no freeze, no crash, nothing.
i5 8400, 1060 GB, W10 1703

**Comment by hockland** [comment]
Wish I'd done that. I just took kd-11's advice on using OpenGL, got passed that bit and moved on. It's my first play of the game, so just enjoying the game.

**Comment by ruipin** [comment]
Do you still have the save from where it crashed? It might be worth trying it again with #5115 and reporting whether the freeze still occurs.
