### ISSUE TITLE
Feature Request:Ask before starting another game while a game is running

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5107]
It's not really a big deal but I lost some progress by accedently double click on another game while switching in and out from full screen by double click.

It can be even an ini only option to ask or not

**Comment by Nekotekina** [comment]
How many clicks you did in total? If less than 4, it may be considered a bug or unwanted behaviour. No need to ask in this case, just make it less possible.

**Comment by vsub** [comment]
Well I said it's not a big deal,there is no need to be rude about it.
If you exit full screen by double click but accidenly click 4 times and you mouse possition happens to be(when you exit full screen)over the main window(and another game),rpcs3 will start it.

The game window is positioned over the main window when you start a game and then it goes full screen but when you exit and move windows around,the window is not moved again over the main window when you enter=>exit full screen.

The same thing can happen if the main window is maximized(or resized to a size bigger than the game window)and you accidently click 4 times to exit full screen

You don't know where the mouse it when it is over the game window

And yes,I know that this is an user error and that's why I said,it's not a big deal.

**Comment by Megamouse** [comment]
you might as well have accidentally closed the whole app by clicking on X or even something random as oneclick buying some book on amazon.

**Comment by vsub** [comment]
Ok then,lets see
Dolphin for examle don't allow you to run another game while a game is running(or maybe it is because of some option I forget about)

**Comment by vsub** [comment]
Ok then,lets see
Dolphin for examle don't allow you to run another game while a game is running(or maybe it is because of some option I forget about)
