### ISSUE TITLE
Feature Request: Enable/Disable the Logging

### ISSUE THREAD

**Issue by elhaya** [RPCS3/rpcs3#5113]
Currently, there's no 'real' option to completely turn off the process of logging.
Some of the games, i.e: Demon's Souls perform a network connectivity test at a very short interval. This I believe makes the log grow in size.
Admittedly, I do not know exactly how to process of writing the log works, however, I am pretty sure that by eliminating need for a dedicated thread for keeping log some performance gain can be made. Even if a small one - it can still prove to be important on machines low on cores or not hyper-threaded

I suggest either an option in the emulator section of the config panel or in the context menu of the log itself, to completely turn off the log (and not just by gui)

I know you guys are very busy - please keep up the good work!

**Comment by Nekotekina** [comment]
The most effective way of disabling messages selectively is already available in config.
The cost of idle thread is nothing.
There is also way to block logs (and reduce runtime cost to near-zero) by blocking access to RPCS3.log or RPCS3.log.gz. For example, by creating non-empty directories with said names.
Adding another option is just plainly redundant.

**Comment by elhaya** [comment]
I really wish you would reconsider. Maybe just as another option above 'fatal' (in the errors) to 'off' and this will also turn off the thread

**Comment by vsub** [comment]
What I use is setting the logging method to fatal and set rpcs3.log to read only
The archive is still created but only after you close rpcs3 which means the logging stays in ram which is WAY faster and less resourse intensive that updating the gui.

On pcsx2 for example on Onimusha 4,the game is spamming in the console so bad that it reduced the game speed at least 10 times and reducing the logging(what is added to the console)restores the speed

**Comment by AniLeo** [comment]
Option to silent logging has already been implemented - closing
