### ISSUE TITLE
Feature Request: Apply changes made to config immediately even when game running

### ISSUE THREAD

**Issue by elhaya** [RPCS3/rpcs3#5114]
This request should be at the lowest priority. To be honest, I don't know how feasible it is.
The way the emulator works right now, you have to restart the game entirely in order for new changes to take affect. I am hoping there is some way to make them apply to the currently running game without the need for a restart.

Knowing how complicated the innards of the emulator - I'm not holding much hope. Would be nice though

**Comment by elad335** [comment]
Highly doubt its useful, or even, possible in a lot of cases.

**Comment by elad335** [comment]
The only way I can see this happening is with save states. new settings applied at runtime -> emulation stopped and saved -> save state is loaded and run with the new settings.

**Comment by elhaya** [comment]
Exactly what I had in mind.. Alhough there will be issues to think about. Such as what happens when you switch from ogl to vulkan - with precompiled shaders & spu.
It has the potential t make it easier to find the best settings more easily

**Comment by AniLeo** [comment]
This is already implemented. Not all settings are possible to change while Ingame for now due to limitations on the emulator itself, but this functionality itself is implemented, so I'll close this issue.
