### ISSUE TITLE
Cross Edge (BLUS30348) cannot launch with LLVM PPU Compiler, device not found 

### ISSUE THREAD

**Issue by nevuk** [RPCS3/rpcs3#5122]
Computer Information :
RPCS3 Version:
0.0.5-7330
Ryzen 1600x, 16 GB RAM, Nvidia GTX 1060

Reproduce:
Try to boot Cross Edge (BLUS30348 ) with LLVM PPU compiler and it will throw an error window and hard crash RPCS3 (won't even compress the log that is generated, had to do it manually). (None of the other settings matter, does it with any SPU decoder and any renderer).
May be a fairly low priority issue as the game will run with the other PPU decoders, though obviously slower.

I think the relevant part of the log starts at line 3326, but not totally sure. Log provided.

Screenshot (since I'm unsure if all data provided in screenshot is in log)

https://github.com/RPCS3/rpcs3/files/2372867/RPCS3.zip

https://user-images.githubusercontent.com/6707114/45390115-06746200-b5ec-11e8-9c16-7befe08d000f.png

I initially thought this was related to https://github.com/RPCS3/rpcs3/issues/3062 , however, terminology is different (device not found vs device not mounted) 

edit :  I no longer believe this is related to issue #3062  . It seems to instead crash after trophies are fully loaded, looking at the log file.

**Comment by digitaldude555** [comment]
Fixed now.
