### ISSUE TITLE
Regression: Sine Mora [NPUB30483]

### ISSUE THREAD

**Issue by profzerg** [RPCS3/rpcs3#5126]
Title doesn't Start since 

RPCS3 v0.0.5-7337-ed7012c9 Alpha 

F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\common\texture_cache.h:2510)

**Comment by AniLeo** [comment]
False report, #4958 doesn't touch RSX.

Need correct PR, last PR that touched that part of texture cache is #5099 so I'm pretty sure it was that one.
