### ISSUE TITLE
OpenGL shaders compiling a lot slower that Vulkan's

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#5131]
Looks like they don't compiling in multithreads, but instead compiling one by one, just like year ago.

After recent (I did't touch OpenGL really for a long time, so recent means no less than 1 year) changes in Vulkan it is now capable to produce 100 shaders in few seconds. But OpenGL seems to not benefit from these changes?

**Comment by HerrHulaHoop** [comment]
PR #4677 is where multi-threading of shader compilation was introduced for Vulkan. From my discussion with @Dravonic, this is what he had to say about the same with OpenGL:
> It's possible to parallelize OpenGL compilation too, but due to the way OpenGL works, it's a pain to do it properly and it doesn't bring much more performance.

**Comment by kd-11** [comment]
Opengl multithreading is not friendly and actually breaks down in some cases. Its why even the async compilation while ingame is slower than vulkan.

**Comment by isshininu** [comment]
Looks like OpenGL multithreading will never be a thing, I will close this question then.
