### ISSUE TITLE
NFL Blitz [NPUB30665] Field gfx have exploding vertices

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5132]
![45581295-142a2180-b850-11e8-889e-94f0591f65f3](https://user-images.githubusercontent.com/20983844/45587723-994c1f80-b8be-11e8-91d8-d10583bd3ae1.png)

![45581269-b695d500-b84f-11e8-8586-574d205dd9bd](https://user-images.githubusercontent.com/20983844/45587739-db756100-b8be-11e8-90f9-77b0363ee0a4.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2385839/RPCS3.log.gz)

RSX Capture:
[NPUB30665_20180915144902_capture.zip](https://github.com/RPCS3/rpcs3/files/2386113/NPUB30665_20180915144902_capture.zip)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by legend800** [comment]
Sure, but for this, it has been an issue for years. Disregard the actual build (which is actually in Master anyway as of today).

**Comment by Asinin3** [comment]
Also for graphical issues you should probably provide a render doc capture https://renderdoc.org/ of the issue. And maybe even a capture using RPCS3's inbuilt tool but renderdoc should be enough.

**Comment by legend800** [comment]
Added a RSX capture. I'll do that for all future gfx issues.

**Comment by elad335** [comment]
Reupload capture, rsx capture replay system was changed since then.

**Comment by legend800** [comment]
@elad335 Sure thing, but the button doesn't seem to be working.  Don't I just need to use this button? Capture folder is empty though. Maybe I'm missing something...

![2018-10-13 18_04_24-d__video games_ps3](https://user-images.githubusercontent.com/20983844/46911537-9a02c080-cf13-11e8-96f8-437e1c9f6871.png)

**Comment by elad335** [comment]
Use strict rendering mode while capturing. then it will appear in rpcs3/capture.rrc .

**Comment by legend800** [comment]
Works with Strict Mode. We should let users know that somehow in the UI, else others will come asking. ;)

It also just goes to root, not the Capture folder (for me at least).

New capture attached with the pic of the capture spot. Let me know if you need anything else!

[capture.zip](https://github.com/RPCS3/rpcs3/files/2476111/capture.zip)

![2018-10-13 22_04_40-fps_ 1 47 _ vulkan _ 0 0 5-7438 _ nfl blitz npub30665](https://user-images.githubusercontent.com/20983844/46912828-08a44600-cf35-11e8-8701-293f2f387ccc.png)

**Comment by kd-11** [comment]
Closing as fixed by https://github.com/RPCS3/rpcs3/pull/5565
