### ISSUE TITLE
Unreal Tournament III [BLES00200] very broken ingame sound

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#5134]
With 7337(default settings Xaudio2), Unreal Tournament III its running, im able to play / complete Instant match at 30 FPS mostly on Core i7 4770S (i seems not hang as lots of others games without TSX), Win10, G970 and Realtek HD sound card (driver 27.3.2018) used  Vulkan, but sound is very broken.. There is some constant noise which is more noise or silent, in depends on game evens, sometimes i can heard good in game sound mixed into noise but not very often.
   Sound with other RPC3 games is fine. I tried OpenAL is exactly the same. I now that sound sound like game is slideshow, but speed is almost fine 20-30 FPS, i not sure but on console its probably 30 FPS.

  I dunno if have similar root cause but even with 30 FPS, input seems to be a bit lagy too, or FPS counter is not correct and framerate is slower that RPCS3 reports.

   Here sound sample Audacity recording:
https://www.dropbox.com/s/ala4a7mwtc1eile/UT3-2.mp3?dl=0
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2388639/RPCS3.zip)

**Comment by Hasster1** [comment]
Are you using the "Enable SPU loop detection" option?

**Comment by ruthan** [comment]
Yes, i do.

**Comment by ruthan** [comment]
Its more than half and year and its still broken, except sound game is fully playable..

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by MsDarkLow** [comment]
Seems to be fine for me nowadays. Here's a video of a 4 minute Deathmatch on v0.0.15-12074-a4859571
https://youtu.be/i-1Ic363Z6o

**Comment by Megamouse** [comment]
needs retest

**Comment by MsDarkLow** [comment]
Its still working perfectly fine for me still
Some more footage - https://cdn.discordapp.com/attachments/442667232489897997/974377575130497124/2022-05-12_19-25-55.mp4
8700K@5GHz & RTX 3080
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8681711/RPCS3.log.gz)

**Comment by Megamouse** [comment]
closing as presumed fixed
