### ISSUE TITLE
Demon's Souls [BLES00932] - Stuck on loading screen

### ISSUE THREAD

**Issue by mizinin** [RPCS3/rpcs3#5141]
Right after game starts, loading screen with animated logo appears and nothing else happens, screen not changes (animation still works endlessly). "Stop emulation" works without crash.

![screenshot](https://user-images.githubusercontent.com/11798478/45638107-56649480-bad6-11e8-9ac6-5613359d7b1e.png)

Tested under #7352 (e37da61).
Used ASMJIT Recompiler and Vulkan renderer.
Also added `Log: {sceNp: Fatal}` in config.yml

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2389528/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2389529/RPCS3.log)

Machine specs: 4670k, GTX 970, Win 10

**Comment by NTZ1989** [comment]
Did you mark the option, "white collors buffer" on? It is in the "GPU tab", right corner and it required in order to make it displays the graphics on the game correctly... When you set it off, it displays a black screen on the game, like ur picture, though it comes off by standard, you need to switch on, in order to play Demon Souls.

**Comment by mizinin** [comment]
> Did you mark the option, "white collors buffer" on?

yep

**Comment by NTZ1989** [comment]
I've tested this version of the game Demon Souls 3 [BLUS30443] in these version:

RPCS3 7345 - I ran the game until the start of the introduction, it played fine.
![demon souls 3 rpcs3 ver 7345](https://user-images.githubusercontent.com/39391129/45653825-b72ca680-baaf-11e8-87b6-0d03a5b80431.png)

RPCS3 7352 - I played the complete introduction and I went until Boletarian, the first dungeon of the game, there I played about 5 minutes on the dungeon, no hangs, no issues, just problems in the frametime but this is an known issues... I thought the graphics more prettier than the previous versions  
![demon souls rpcs3 ver 7352](https://user-images.githubusercontent.com/39391129/45653826-b72ca680-baaf-11e8-915f-69f161cd333d.png)


ver.

**Comment by ruipin** [comment]
You might wish to try #5115, fixes some bugs that could cause infinite loading / loading screen freezes. Possibly unrelated, but no harm trying.

**Comment by mizinin** [comment]
Sadly, #5115 PR don't resolve this problem

**Comment by Quistnix** [comment]
Same issue here, exact same specs. I'll try and get some logs later.

**Comment by NTZ1989** [comment]
@mizinin sorry by the late replay, I've just see ur post now, my settings are:

Ryzen 1700
My gpu is from Nvidia too
Windows 10 build ver. 1803

all drivers are updated, 
![demon souls rpcs3 ver 7352 set 1](https://user-images.githubusercontent.com/39391129/45718252-c9bbe400-bb72-11e8-9b68-15446f3a7ff8.png)

![demon souls rpcs3 ver 7352 set 2](https://user-images.githubusercontent.com/39391129/45718259-cd4f6b00-bb72-11e8-8ab9-439fff71a5f6.png)

**Comment by mizinin** [comment]
Sorry, problem was caused by corrupted game cache :(
