### ISSUE TITLE
[BCES01277] God of War Origins Collection hangs on loading save or retry with the same error

### ISSUE THREAD

**Issue by fifazalata** [RPCS3/rpcs3#5142]
just like the title suggests, the game hangs with this error
> E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300450

when trying to load or retry a save. it happens frequently till the point of frustration
I tried every setting wether with vulkan or ogl & it still happens
I also tried multple builds
the latest master I tried is **rpcs3-v0.0.5-7345-ed8aa774_[2018-09-15]**

my rig is i7 2600 @ 3.4
gtx 1070
8 gb ram

& here is the log in case you need it
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2390204/RPCS3.log.gz)

**Comment by elhaya** [comment]
increase this value in your config file: Driver Recovery Timeout: 1000000

**Comment by fifazalata** [comment]
based on what & what does that actually do?

**Comment by fifazalata** [comment]
@kd-11: I tried that already. I also tried all settings combinations including disabling Async but the issue still exist.
Out of 10 tries for example, it will only load once or twice and then hang again.
Hope you can have an idea of what maybe the cause of this.

**Comment by benderscruffy** [comment]
time to update the issue

**Comment by fifazalata** [comment]
I haven't tried the game for over a year now
But I have managed to beat it after multiple tries. I will close the issue for now.
