### ISSUE TITLE
Yakuza 4 [BLUS30643] regression - Invalid location

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#5143]
With version 7346 (pull request #5137) and all versions after it Yakuza 4 crashes with `std::runtime_error thrown: Invalid location (offset=0x0, location=0xff)` after loading shader cache. Interestingly, if shader cache is cleared the game will start without issues, but will crash on every boot afterwards untill shader cache is cleared again.

7345 (#5111) and versions before it do not have the same issue.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2392762/RPCS3.log.gz)

**Comment by elad335** [comment]
retest with #5144
