### ISSUE TITLE
Build error in Travis clang

### ISSUE THREAD

**Issue by leskal** [RPCS3/rpcs3#5148]
https://github.com/RPCS3/rpcs3/blob/59090f6d268c808599d423bf72e34d734040dc57/.travis/deploy-linux.bash#L8
Build failing with this:
`--appimage-extract-and-run is not yet implemented in version 504b6d2`

After quick search of the hash "504b6d2" i found this: https://github.com/AppImage/AppImageKit/commits?author=TheAssassin&since=2018-07-01T00:00:00Z&until=2018-07-21T00:00:00Z with date **Jul 18, 2018** but the `--appimage-extract-and-run` has been merged at **Aug 17, 2018** at this pull request: https://github.com/AppImage/AppImageKit/commit/581f9829453ef816d044775ccbff7734490fe69c

**Comment by hcorion** [comment]
Yes, the issue is with linuxdeployqt, https://github.com/probonopd/linuxdeployqt which hasn't had a rebuild in quite a while.

**Comment by leskal** [comment]
As of #5152
