### ISSUE TITLE
Improve the mouse movement configuration of the Qt keyboard_pad_handler

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#5157]
Maybe it's more of a request than an issue, but...
I was checking the new mouse support on games that uses right stick as the camera rotating, and found it's very low. I need several mouse swings just to made about 90 degrees look. I found no any options to tweak it in inputconfigs, so think the emulator really needs ability to adjust mouse sensitivity and/or higher default value. Also, won't be excess mouse deadzone adjusting feature.

**Comment by HerrHulaHoop** [comment]
Please see #4957 for instructions on how to change the deadzones and mouse sensitivity.

**Comment by Psycho-A** [comment]
Oh, thanks, I didn't know about that.
But is it writes to somewhere, or I need to set it manually every time? Sounds like this, because I can't find any saved values and they're reset on next launch. Also it uses only log info which is invisible if playing fullscreen.

**Comment by Megamouse** [comment]
This is a highly experimental feature. so don't expect it to be perfect in any way
