### ISSUE TITLE
GLIBCXX_3.4.22 and CXXABI_1.3.11 not found - Linux Mint 18.3 ( Ubuntu 16.04 based )

### ISSUE THREAD

**Issue by Leopard1907** [RPCS3/rpcs3#5159]
I have that issue on RPCS3 lately. New builds are not booting. 

Tested on :
rpcs3-v0.0.5-7367-afa7eacf_linux64.AppImage
rpcs3-v0.0.5-7372-dafc914b_linux64.AppImage

Same issue.

Error is:

`rpcs3: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by rpcs3)
rpcs3: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by rpcs3)
`

Output of ldd --version:

`ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23
Kopya Hakkı (C) 2016 Free Software Foundation, Inc.
Bu bir serbest yazılımdır; kopyalama koşulları için kaynak koduna bakınız.
HİÇBİR garanti yoktur; hatta SATILABİLİRLİĞİ veya ŞAHSİ KULLANIMINIZA
UYGUNLUĞU için bile garanti verilmez.
Roland McGrath ve Ulrich Drepper tarafından yazıldı.`

My system info:

> System:    Host: asus-FX553VD Kernel: 4.15.3-041503-generic x86_64 (64 bit gcc: 7.2.0)
           Desktop: Cinnamon 3.6.7 (Gtk 3.18.9-1ubuntu3.3) Distro: Linux Mint 18.3 Sylvia
Machine:   System: ASUSTeK (portable) product: GL553VD v: 1.0
           Mobo: ASUSTeK model: GL553VD v: 1.0 Bios: American Megatrends v: GL553VD.304 date: 09/07/2017
CPU:       Quad core Intel Core i7-7700HQ (-HT-MCP-) cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 22464
           clock speeds: max: 3800 MHz 1: 1164 MHz 2: 3276 MHz 3: 3121 MHz 4: 3171 MHz 5: 3087 MHz 6: 3285 MHz
           7: 2787 MHz 8: 3187 MHz
Graphics:  Card-1: Intel Device 591b bus-ID: 00:02.0
           Card-2: NVIDIA Device 1c8d bus-ID: 01:00.0
           Display Server: X.Org 1.19.6 driver: nvidia Resolution: 1920x1080@60.01hz
           GLX Renderer: GeForce GTX 1050/PCIe/SSE2 GLX Version: 4.6.0 NVIDIA 396.54 Direct Rendering: Yes
Audio:     Card Intel Device a171 driver: snd_hda_intel bus-ID: 00:1f.3 Sound: ALSA v: k4.15.3-041503-generic
Network:   Card-1: Intel Wireless 7265 driver: iwlwifi bus-ID: 02:00.0
           IF: wlp2s0 state: up mac: <filter>
           Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: d000 bus-ID: 03:00.0
           IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:    HDD Total Size: 1128.2GB (85.9% used) ID-1: /dev/sda model: SanDisk_SD8SN8U1 size: 128.0GB
           ID-2: /dev/sdb model: HGST_HTS541010A9 size: 1000.2GB
Partition: ID-1: / size: 110G used: 47G (46%) fs: ext4 dev: /dev/sda2
           ID-2: /home size: 917G used: 848G (98%) fs: ext4 dev: /dev/sdb1
           ID-3: swap-1 size: 8.59GB used: 0.00GB (0%) fs: swap dev: /dev/sda3
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 57.5C mobo: N/A gpu: 0.0:50C
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 243 Uptime: 26 min Memory: 1287.7/7861.4MB Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.481) inxi: 2.2.35

**Comment by hcorion** [comment]
What's the output of `lsb_release -rcs`

**Comment by Leopard1907** [comment]
`18.3
sylvia`

@hcorion

**Comment by hcorion** [comment]
This will have been fixed in https://github.com/RPCS3/AppImageKit-checkrt/commit/e9147cd3d5e2b232e1dbb85909169e7508f6b94a but you'll need to wait until a new PR merges before you can test if it fixes it.

**Comment by Leopard1907** [comment]
Thanks , i'll wait.

**Comment by hcorion** [comment]
Please retest, it should be fixed now.

**Comment by Leopard1907** [comment]
It boots now with;

`rpcs3-v0.0.5-7376-0da556e1_linux64.AppImage`

Thanks , issue solved.

**Comment by unknown321** [comment]
Same issue here, debian 9
`$ ./rpcs3-v0.0.5-7376-0da556e1_linux64.AppImage 
rpcs3: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by rpcs3)`

`$ lsb_release -rcs
9.5
stretch`
