### ISSUE TITLE
Battle Fantasia [NPUB30126] incorrect outline on characters

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#5165]
rpcs3-v0.0.5-7377-b7e010bb_linux64
Archlinux, r9 fury, mesa 18.2
With Vulkan (Ogl has many more problems): WCB is necessary (but not "Strict rendering" anymore). Characters have an incorrect outline
![selection_018](https://user-images.githubusercontent.com/7478580/45927312-c7220b80-bf31-11e8-9573-93e342fea7bc.jpg)
The renderdoc:
https://www.dropbox.com/s/jz86j1i8h70abm0/2018-09-23-BattleFantasia-Vulkan-Outline-pb_frame2922.zip?dl=0
The rsx capture:
[BattleFantasia_NPUB30126_20180923131310_capture.rrc.zip](https://github.com/RPCS3/rpcs3/files/2408648/BattleFantasia_NPUB30126_20180923131310_capture.rrc.zip)

**Comment by digitaldude555** [comment]
Doesnt even go ingame anymore, freeze with this
```
 F {RSX [0x0037144]} RSX: class std::runtime_error thrown: NV3089_IMAGE_IN_SIZE: unknown src_color_format (3)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsx_methods.cpp:927)
```

**Comment by toccata10** [comment]
On rev8143, this problem is solved. WCB is needed to play the game, but it now works both with vulkan and Ogl.
