### ISSUE TITLE
[BLES01756] Zoe 2 HD collection crashing

### ISSUE THREAD

**Issue by resadent** [RPCS3/rpcs3#5167]
Hi. I've been trying to complete this game since quite a while but for now just can't. It freezes and graphics break (except the hud) at a point in the game. This is with latest build 0.0.5-7387. As shown in the first picture, I can get to the menu just fine but once ingame the image is basically broken. Sound is fine though.

Windows 10 64 bits, 16gb dram ddr3, i5 4690k (no tsx), rx 480 (8gb) with driver 18.9.1.
UPDATE: now with nvidia gtx 1060 6gb driver 417.71.

Btw using asmjit, since spu llvm won't even make it into the game.
edit: llvm now plays just as well as asjmit but still suffers from the same issue.

![captura](https://user-images.githubusercontent.com/34896462/45968598-c1135400-c031-11e8-917d-fdb87338e997.PNG)
![failure](https://user-images.githubusercontent.com/34896462/45968603-c375ae00-c031-11e8-90c6-094e7338b159.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2412172/RPCS3.log.gz)

I think this is my first Issue. Hope I haven't messed up.

UPDATE: new log as of jan 18 [RPCS3.log.gz]
UPDATE2: another new log 09 mar 2020.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4318014/RPCS3.log.gz)

**Comment by Asinin3** [comment]
PR = Pull Request, this is just an issue :p 
Anyway, did you try updating the game through psn to get the latest version? I remember specifically hearing about how you need the latest game updates for ZoE2 to fix an issue with it.

**Comment by resadent** [comment]
Lul sorry about the PR thing, glad you fixed it :P

And yeah, the game has the latest patch.

**Comment by resadent** [comment]
The error still happens as of today. I've been having a look at the log and I think it seems a little bit different now, so I will upload it just in case it helps.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2772972/RPCS3.log.gz)

**Comment by resadent** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3389085/RPCS3.log.gz)
Figured out Id update the log since it's been quite some time since the last one I posted.

**Comment by digitaldude555** [comment]
@resadent update?

**Comment by resadent** [comment]
Dont have the time to update right now, will do ASAP.

**Comment by resadent** [comment]
Alright I can confirm the issue still persists with the last build. I will add log soon.

**Comment by resadent** [comment]
Hi. The issue is now fixed, game should be fully playable although can't say for sure cause I haven't completed it in rpcs3.
