### ISSUE TITLE
(FEATURE REQUEST)not supported shader compilling skip feature for asynch shader

### ISSUE THREAD

**Issue by AkagiShiroe** [RPCS3/rpcs3#5169]
could you make emulator skip some shader compiling in first boot? since that kinda feature help my GPU (not fully openGL 4.x support but with asynch shader, any rpcs3-compatible game running fine on my place now)
i use geforce 220GT (OpenGL 3.3 with incomplete 4.x) and rpcs3 7387

**Comment by 13xforever** [comment]
disable on-disk cache in the settings.

also github is not a place to ask for support, use discord or forums for this in the future.

**Comment by AkagiShiroe** [comment]
what i want to request was skipping not compatible shader compile process, if shader wasn't supported, shader compiler will stuck there and leave other shader uncompiled which making in-game effect goes weird and sometimes doesn't show. if i disable asynch shader.. i completely can't play the game.
![5678](https://user-images.githubusercontent.com/14356240/46027299-77596500-c128-11e8-926d-ac38db6759ae.png)
if this selectable feature implemented (which is i hope possible), it will make most legacy hardware to able emulating rpcs3 by skipping unnecessary not supported shader and compile another shader (at least with small issues).
