### ISSUE TITLE
[BLUS30847] Metal Gear Solid HD Collection: Heavy Flickering After kd's PR#5162 Got Merged

### ISSUE THREAD

**Issue by fifazalata** [RPCS3/rpcs3#5170]
Hey there, so like I said in discord there is heavy flickering introduced in one of recent masters (0.0.5-7387)
that merged the PR https://github.com/RPCS3/rpcs3/pull/5162

Like that:
![ezgif com-optimize](https://user-images.githubusercontent.com/30318673/45976515-49502400-c047-11e8-87ed-13d206e934ef.gif)

My rig specs:
intel core i7 2600k @3.4
gtx 1070
8GB RAM

Here is a log when it's heavily flickering:
[RPCS3.log-heavy-flickering.gz](https://github.com/RPCS3/rpcs3/files/2412705/RPCS3.log-heavy-flickering.gz)

& Here's a log when it's working correctly in the master before:
[RPCS3.log-working-good.gz](https://github.com/RPCS3/rpcs3/files/2412707/RPCS3.log-working-good.gz)

**Comment by ruipin** [comment]
@kd-11 you might wish to take a look

**Comment by fifazalata** [comment]
NieR also looks like this
![1](https://user-images.githubusercontent.com/30318673/45977181-1870ee80-c049-11e8-9ed9-9b298e383557.jpg)

**Comment by fifazalata** [comment]
it turns out that enabling "skip frame" was the cause of this
Sorry for inconvenience
gonna close the issue now
