### ISSUE TITLE
"Heavy Rain" no longer Starts (BCUS98164)

### ISSUE THREAD

**Issue by questore** [RPCS3/rpcs3#5172]
After PR 5166 the game only hangs after loading screen. Before the PR it was loaded and the game can be started.

_Originally posted by @questore in https://github.com/RPCS3/rpcs3/pull/5166#issuecomment-424117589_

**Comment by Xcedf** [comment]
Confirm, commit e0a676a3 caused this

**Comment by kd-11** [comment]
Retest with https://ci.appveyor.com/project/kd-11/rpcs3/build/1693

**Comment by Xcedf** [comment]
Fixes vertex explosion regression, but still suffers from WCB stuck

**Comment by stride21** [comment]
Motorstorm also can't go ingame when using WCB with that PR.  Should I create a new issue?

**Comment by kd-11** [comment]
I'm only concerned with the vertex bug right now, the WCB thing is from #5115 by @ruipin

**Comment by questore** [comment]
Confirmed that #5175 fixes the problem.

**Comment by Xcedf** [comment]
I think this one can be closed, WCB regression superseeded by Issue5180

**Comment by elhaya** [comment]
why was this closed? is it a duplicate?? the problem still exists, even with ver. 7404
the menu screen will always hang when WCB is on and doesn't if it's off...
