### ISSUE TITLE
Feature Request: Additional Post-Processing

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#5189]
The PCSX2 emulator has shader configuration to adjust settings like Brightness, Contrast, and Saturation. Can this be added to RPCS3?

**Comment by marosis** [comment]
Why?

**Comment by HexyFify** [comment]
> Why?

Why include resolution scaling, we include these things because they make emulators better in a customize-ability way

**Comment by B-Knight49** [comment]
Anti-Aliasing also. It's included in the GUI but grayed out and not available for all games (that I'm aware of). Perhaps there's a reason for this but it'd be greatly appreciated given how jaggedy the lines are in some games.

**Comment by Dweeblord** [comment]
Why not use Reshade?

**Comment by dio-gh** [comment]
Indeed, I don't think this should be the emulators job, ReShade is plenty good for this job, and games offer these to various extents as well (brightness and gamma).

**Comment by Megamouse** [comment]
This feels more like a random discord discussion than a real ticket

**Comment by Calinou** [comment]
> Indeed, I don't think this should be the emulators job, ReShade is plenty good for this job, and games offer these to various extents as well (brightness and gamma).

Note that Reshade does not work on native Linux applications, and vkBasalt isn't easily usable on Flatpaks (and doesn't work on OpenGL applications, so you need to use Vulkan in RPCS3). I was looking for a way to apply SMAA on RPCS3 in the Linux Flatpak.

So I still think there's a point in having native post-processing support, much like Dolphin or PCSX2.

**Comment by Rex000** [comment]
This would be a great and very useful feature, just like it is on PCSX2. There are games with issues like being dark or too bright among others and it would be perfect if it could be fixed form within the emulator.

**Comment by Rex000** [comment]
This would be a great and very useful feature. There are games with issues like being dark or too bright among others and it would be perfect if it could be fixed from within the emulator.

**Comment by Rex000** [comment]
This would be a great and very useful feature. There are games with issues like being too dark or bright among numerous others and it would be perfect if it could be fixed from within the emulator.

**Comment by Calinou** [comment]
I've started to poke around in a branch: https://github.com/Calinou/rpcs3/tree/add-smaa

I've never looked at the RPCS3 codebase before, so I'm not sure if this is the best avenue for implementing this. It's mostly a copy of the upscaler code right now. We should also ensure post-process AA runs at the game's internal resolution *before* upscaling for best results, so that FSR 1.0 can work with an antialiased image if the game doesn't have any antialiasing.
