### ISSUE TITLE
Beyond: Two Souls [BCUS98298] Crashes Emulator after boot

### ISSUE THREAD

**Issue by tommis15** [RPCS3/rpcs3#5190]
Specs:
Windows 10 Pro x64
i7-6700K
GTX 970
16 GB DDR4

RPCS3 build: rpcs3-v0.0.5-7404-72ba062b_win64

Issue:
Previously I could get to menu, and or crash ingame, now I crash almost immediately after boot.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2426415/RPCS3.log)
![error](https://user-images.githubusercontent.com/40190153/46183540-51a29c00-c29f-11e8-8a10-7b19c0948352.PNG)

**Comment by Asinin3** [comment]
"previously" means nothing to us, find the exact build / Pull Request which broke it. And you have a nvidia driver crash, did you try OpenGL? please remember this isn't a support forum, it's an issue tracker. And in order to fix issues we need proper documentation of the issue.

**Comment by tommis15** [comment]
Ok, I've done more research, I checked

**Comment by tommis15** [comment]
I was mistaken, the issue is still there. On build rpcs3-v0.0.5-7394-bdf85ed9_win64, the issue is not present. With the latest build, it crashes on the intro cutscene, then on every subsequent attempt to load the game.

Default settings except Vulkan is renderer.

**Comment by stride21** [comment]
I'm not seeing this issue and I have the same CPU. @tommis15 you should use Write Color Buffers and in the debug tab also turn on Force CPU blit emulation, it fixes some of the graphical issue with the game.

**Comment by tommis15** [comment]
I did a clean install again, did not receive the same error but as I closed the emulator I got this:

![err](https://user-images.githubusercontent.com/40190153/46511638-b3be4c80-c81d-11e8-9a4a-dc94e6630467.PNG)

Not sure if I should close this or not, it seems the games is a lot less stable for me than before.

**Comment by stride21** [comment]
@tommis15 I have a GTX 1070 and have no issues with Vulkan or OpenGL. You should just ask for help on discord, it could possibly just be a video card driver issue or an issue with your config.

**Comment by tommis15** [comment]
Ok, I'll close it for now. I'll test at a later time.
