### ISSUE TITLE
Any way of use GPGPU for increase performance in any way??

### ISSUE THREAD

**Issue by Ghostotakoi** [RPCS3/rpcs3#5191]
I have notice that, in regular PC games, my CPU i7-6700k, is used like a 60% and my GPU GTX 1060 6GB 100%. but in rpcs3 is complete opposite 100% CPU and like 30% GPU, so i was wondering if any way to use something like this https://en.wikipedia.org/wiki/General-purpose_computing_on_graphics_processing_units in order to increase the performance in any way??? could be using open-cl or something witch is cross platform???

**Comment by AniLeo** [comment]
#2765
