### ISSUE TITLE
Jojo All Star [BLUS31405] crashes on Unknown system error: 20

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#5194]
RPCS3 v0.0.5-7405-da6ce80f
Archlinux, r9 fury, mesa 18.2
Jojo crashes on 
![selection_022](https://user-images.githubusercontent.com/7478580/46242244-937a3200-c3c6-11e8-8a1e-84cd61d3d37a.jpg)
with 
```
S {PPU[0x1000000] Thread (main_thread) [0x014509ac]} sys_prx: Loaded module: /dev_flash/sys/external/libnet.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014509ac]} PPU: LLVM: Loaded module v2-librtc.sprx-9CB190F178FA7E82-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014509ac]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx
E {PPU[0x1000000] Thread (main_thread) [0x0098f25c]} 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [1]
S {RSX Decompiler Thread} RSX: New program compiled successfully
E {PPU[0x1000000] Thread (main_thread) [0x0098f25c]} 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x100008f] Thread (DataInstallThread) [0x0089979c]} cellGame: cellGameCreateGameData(init=*0xd009b800, tmp_contentInfoPath=*0xd009b700, tmp_usrdirPath=*0xd009b680)
S {PPU[0x100008f] Thread (DataInstallThread) [0x0089979c]} cellGame: cellGameCreateGameData(): temporary directory '/dev_hdd0/game/_GDATA_1806787945238' has been created
F {PPU[0x100008f] Thread (DataInstallThread) [0x00899b64]} St13runtime_error thrown: Unknown system error: 20.
```
tried PPU recompiler and Interpreter, with the same result.
`/dev_hdd0/game/_GDATA_1806787945238` contains just a USRDIR which is empty
[RPCS3.log-Jojo.gz](https://github.com/RPCS3/rpcs3/files/2430363/RPCS3.log-Jojo.gz)

**Comment by kd-11** [comment]
Needs retest. It seems the game is creating a file somewhere and attempting to open it as a folder. Could have been fixed in the past few months.

**Comment by toccata10** [comment]
Still not working on rev7932
```
E {PPU[0x1000000] Thread (main_thread) [0x01444dac]} 'cellMsgDialogProgressBarReset' failed with 
0x8002b302 : CELL_MSGDIALOG_ERROR_DIALOG_NOT_OPENED [1]
E {PPU[0x100008f] Thread (DataInstallThread) [0x0089979c]} cellGame: cellGameCreateGameData(init=*0xd00b3990, tmp_contentInfoPath=*0xd00b3890, tmp_usrdirPath=*0xd00b3810)
S {PPU[0x100008f] Thread (DataInstallThread) [0x0089979c]} cellGame: cellGameCreateGameData(): temporary directory '/dev_hdd0/game/_GDATA_1320697559420' has been created
F {PPU[0x100008f] Thread (DataInstallThread) [0x00899b64]} St13runtime_error thrown: Unknown system error: 20.
```

**Comment by k10kan** [comment]
It came as a surprise to me to see that BLUS31405 has such an issue.

For a long time this game has no such problems, even as far as v7405-da6ce80f build as I can remember.

I have a dump of this game and it has no issue running on Win7 nor on Ubuntu 18.10.

I have tested this in clean install (on ubuntu, using appimage with totally clean env. by creating folder rpcs3-v0.0.6-7932-d7ad991b_linux64.AppImage.config), installed FW 4.84 and game itself. It runs as good and as fast as never before.

Also, did a test on Win7 (same RPCS3 build) - same result.

Your issue looks like problem with modified game files or failed dump.

Check you dump (IRD - MD5 sums).

**Comment by toccata10** [comment]
The problem seems to lie in the DLC: after a new clean install, I've got the problem described here: #3841
Removing the DLC folder allows the game to run. So, closing for now.
