### ISSUE TITLE
MRTC00002[Lost Planet 2]

### ISSUE THREAD

**Issue by xelmasx** [RPCS3/rpcs3#5199]
System Specs ; OS "Fedora 29 Linux", CPU "AMD 2700x", GPU "AMD vega 56".
Problem Launching Lost Planet 2 : I am unable to run this game, when I attempt to load it up but I cant pass installation  screen  nothing happens.
![screenshot from 2018-09-29 21-21-21](https://user-images.githubusercontent.com/21128451/46249209-f81ca780-c42d-11e8-916a-872350b3d3a2.png)

**Comment by AniLeo** [comment]
Please use the forums to submit game compatibility reports, the issue tracker is for specific issue reports
