### ISSUE TITLE
 BLES01047 Castlevania Lords of Shadow - Strange lines on OpenGL

### ISSUE THREAD

**Issue by NoUserNameForYou** [RPCS3/rpcs3#5200]
i5 4460 TSX isn't enabled by bios hack
GTX 970, doesn't matter which driver

Used software version:
Oldest one I could get rpcs3-v0.0.5-6601-ee0fe28d_win64
Newest one as my time of testing rpcs3-v0.0.5-7404-72ba062b_win64

Tried many settings, none of them work. There are strange, mostly vertical lines with the OpenGL version.

The reason I'm trying OpenGL is because of Reshade, otherwise Vulkan version is perfect.

**Comment by Asinin3** [comment]
No screenshot? No log file? Also does it happen without reshade? And what GPU and GPU Driver? If it's a single diagonal line then it could be the bug that affects AMD.

**Comment by NoUserNameForYou** [comment]
Yes, happens without reshade. Tried writing colour buffers, strict rendering, different resolutions, anisotrophy, frame rate auto, off, arbitrary ones, enabled cpu blit, tried different things in debug tab, cleared shader cache both from nvidia folder and emu folder. SPU cache safe, giga doesn't matter, interpreter doesn't matter. GPU texture scaling on/off.

Here's the SS: https://imgur.com/5gjWqtD

Will try to upload log as well, the site shows an error, something went wrong blabla.

**Comment by NoUserNameForYou** [comment]
Don't worry about the Nvdia driver versin, already tried the latest one and returned back to my favorite.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2431512/RPCS3.log.gz)

**Comment by elhaya** [comment]
I can confirm also,
happens only with opengl. vulkan runs without this problem so I never even bothered reporting

**Comment by NoUserNameForYou** [comment]
I'm not expecting this to be fixed btw, just wanted to report, since it may fix more problems with the emu.

I already play on PC (though PC misses animated foliage) but reshade, including Depth Buffer, works fine there. 

can't have it all I guess.

**Comment by kd-11** [comment]
Cannot reproduce with current rpcs3 (tested on nvidia+linux)
