### ISSUE TITLE
God of War texture corruption

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#5201]
I've managed to complete this game on RPCS3 (with hacks of course), but all over the game there are places and things with textures wich look overstretched, and i think it also related to well known font issue, i think the latters are no fonts they're small textures, just like flowers on tree on screen below
![4](https://user-images.githubusercontent.com/7060586/46252860-81a49780-c477-11e8-98e9-637e1b6ba3f3.jpg)
![27](https://user-images.githubusercontent.com/7060586/46252861-8701e200-c477-11e8-9b26-62634207626f.jpg)

**Comment by Asinin3** [comment]
Can you please get a RRC capture using RPCS3's debugger?

**Comment by Xcedf** [comment]
Managed to capture it, finally
https://mega.nz/#!fF4VBKZA!LVmhESYgOtRSqVrx7-qH4R7kVRNLQfvHkvRqTcT6AXM

**Comment by Xcedf** [comment]
kd-11;s gt_fixes PR fixes it and the text
![13](https://user-images.githubusercontent.com/7060586/48984946-3a532400-f113-11e8-986d-582a2e1b45bd.jpg)

**Comment by jobs-git** [comment]
It would be interesting if you could share your build with hacks? Tnx!

**Comment by Xcedf** [comment]
Sure, here's the build, 
https://mega.nz/#!bAwQHazb!WZ-S84zQPaLKqlaQX4hJQMoAsPXakF3LsSFGdXSJMes
It contains speedhacks and the last commit from gt_fixes, cause it works with Vulkan
i also found it fixes some other bugs. Ingame graphics looks almost playable now, it has only particle effects issues left.
Before
![12](https://user-images.githubusercontent.com/7060586/49124146-564df580-f2cc-11e8-8e5c-d27264b7118d.jpg)
After
![13](https://user-images.githubusercontent.com/7060586/49124150-5bab4000-f2cc-11e8-9352-51e68ec5572a.jpg)
Before
![22](https://user-images.githubusercontent.com/7060586/49124162-66fe6b80-f2cc-11e8-9a49-edd570e442c5.jpg)
After
![27](https://user-images.githubusercontent.com/7060586/49124170-6ebe1000-f2cc-11e8-8484-e0f19ee9c7c2.jpg)

**Comment by jobs-git** [comment]
That's impressive! Can I request your config for this to work this way?

**Comment by jobs-git** [comment]
That is very impressive! However, I couldn't get it to load at the beginning, can I request your configurations and the config file for this?

**Comment by Xcedf** [comment]
Here's my config for this game
[config.gz](https://github.com/RPCS3/rpcs3/files/2625923/config.gz)

**Comment by jobs-git** [comment]
You were amazing! I think you finished the game playing at approximately 20 fps!

**Comment by Xcedf** [comment]
Thanks, yea i've finished the game a month ago

**Comment by Emulator-Team-2** [comment]
@Xcedf 
Can you share your SPURecompiler.cpp?

**Comment by Xcedf** [comment]
@Emulator-Team-2 here's two files which make it happen
different options will be usefull for different games
[patch.gz](https://github.com/RPCS3/rpcs3/files/2642479/patch.gz)

**Comment by Emulator-Team-2** [comment]
@Xcedf Thanks

**Comment by Xcedf** [comment]
Yea, i've discarded latest llvm submodule update because it crashes during spu cache compilation, rolled back to previous state

**Comment by MarioSonic2987** [comment]
@Xcedf Could you close this issue? PR #5436 is merged now.
![image](https://user-images.githubusercontent.com/20027681/50394162-de081200-075b-11e9-997e-288ed00873f6.png)

**Comment by Xcedf** [comment]
Sure, fixed now
