### ISSUE TITLE
RPCS3 will randomly not load my save

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5202]
I am playing Atelier Escha and Logy and for whatever reason when I try to load my save,rpcs3 will freeze on the load screen after I press X to load a save(not on the loading screen that appear after that,I mean the screen on which you select your save)

I am not sure since when this started happening and there is only two lines difference at the end in the log between when the save is loaded and when rpcs3 freezes when I try to load the save.

This is when the game don't freeze(the music actually continues when it freezes but nothing else happens)while I am using "Success" logging method(I think that was the default one)
U {PPU[0x1000000] Thread (main_thread) [0x00ba1038]} sys_prx TODO: _sys_prx_unload_module(id=0x23016c00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x00ba1038]} sys_prx TODO: _sys_prx_unload_module(id=0x23016d00, flags=0x0, pOpt=*0x0)

When I use 0.0.5-7161,the save is loaded every time(I cleared the game using this version and load\save the game at least 100 times)but on the latest beta and some older,it randomly freezes

All settings are set to default exept
FPS set to 50
Aspect to 16:9
Scaling to 150%
Disable Async Shader compiler is enabled

If it is of any use to you,here are two trace logs,one when the game freezes and one when it works fine
[AEL.zip](https://github.com/RPCS3/rpcs3/files/2431317/AEL.zip)

**Comment by y-salnikov** [comment]
Same behavior with Atelier Shallie.

**Comment by vsub** [comment]
So shallies is also affected?
I clear that game before escha and logy using the same version(0.0.5-7161)and that did not happen even once(more than 60 hours) and compared to escha and logy,shallie crashed only once while AE&L crashes often with access violation errors

**Comment by vsub** [comment]
Ok,I finaly found the problematic rev.
It was a real pain because it was happening at random.

I made an Autohotkey script that will run the game,load my save and if after a specific time if the color at certain position is black,that would mean that rpcs3 freeze on the loading screen and I will get a message box(there is no chance of mistake because I left plenty of time for the script to decide if the game has frozen or not))

I left it running for an hour(acourding to the counter it made 128 attempts)while using 0.0.5-7385 https://github.com/RPCS3/rpcs3/pull/5115 and when I get back to it,the script was still running fine.

Then I tried 0.0.5-7387 https://github.com/RPCS3/rpcs3/pull/5162 and of the second run,I get the message box and I saw that rpcs3 stays frozen at the save loading screen.

Now I don't know how this will help but here is the log from 387 when the bug happens
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2499167/RPCS3.log.gz)

**Comment by vsub** [comment]
Still no change on 0.0.5-7587
I just downloaded that version to try it out and again it freeze on my first attempt to load my save

One thing to mention tho...this never happens if I use the qt interface(not native)or any rev below 0.0.5-7385

It takes 1 minute to load the spu cache and then it randomly freezes

**Comment by vsub** [comment]
Ar noSurge also seems to be affected(0.0.6-7776)

The log contains trying to run the game 4 times

1.Attempt,successfully load the save but going to the save menu and exiting from it freezes rpcs3
2.Attempt,same as before
3.Attempt,successfully loading and exiting from the save menu(tried it once)
4.Same as above but I tried entering and exiting the save menu 3 times and on the 3rd time rpcs3 freezes

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2824444/RPCS3.log.gz)

**Comment by vsub** [comment]
No change on the latest version(0.0.6-7932)
This time I just enter=>exit=>enter the save screen few times and at one point rpcs3 freeze
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3048326/RPCS3.zip)

**Comment by vsub** [comment]
Fixed since #6069
