### ISSUE TITLE
MRTC00002[Lost Planet 2] hdd installation screen section doesnt pass.

### ISSUE THREAD

**Issue by xelmasx** [RPCS3/rpcs3#5203]
System Specs ; OS "Fedora 29 Linux", CPU "AMD 2700x", GPU "AMD vega 56".
Problem Launching Lost Planet: Extreme Condition. I am unable to run this game, when I attempt to load it up hdd installation section doesnt pass and nothing happens.
![screenshot from 2018-09-29 21-21-21](https://user-images.githubusercontent.com/21128451/46254752-d27ab700-c49c-11e8-9b03-2ad6d82efcfb.png)
[lost planet2.log](https://github.com/RPCS3/rpcs3/files/2431337/lost.planet2.log)

**Comment by 13xforever** [comment]
You already have opened #5199, and you’ve been told to use proper channels to ask for help / report compatibility status.

Opening the same issue again will only get you banned for spamming.

**Comment by HerrHulaHoop** [comment]
@xelmasx also, consider join our [discord server](https://discord.me/RPCS3) to better debug this issue.
