### ISSUE TITLE
Vulkan Crash in AC Brotherhood BLUS30537

### ISSUE THREAD

**Issue by tobugi** [RPCS3/rpcs3#5204]
i7 7700HQ 16GB RAM Nvidia 1060 Windows 10 

With every setting I try I cannot get it running With Vulkan. Everytime it should start Rendering 3D graphics it crash (very simple to reproduce)
I also tried downloading Vulkan SDK.
I cannot trace where it started this problem.
Thanks in advance
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2431789/RPCS3.zip)

**Comment by Xcedf** [comment]
I think it's Issue https://github.com/RPCS3/rpcs3/issues/5001 here

**Comment by tobugi** [comment]
Should I erase it?

**Comment by AniLeo** [comment]
Log does not show it's related to #5001 

This needs to be retested on latest build. Edit config.yml and set Debug Output to true, then run the game again in order to try to get detailed output

**Comment by kd-11** [comment]
Closing as issue reported by OP no longer occurs. Request to reopen if otherwise.
