### ISSUE TITLE
Fifa Street Stutters

### ISSUE THREAD

**Issue by greggameplayer** [RPCS3/rpcs3#5205]
# RPCS3 Build : 
0.0.5-7405-da6ce80f Alpha

# System Specs : 
- Intel I7-7700k @ 4.5 Ghz
- Intel HD 630
- 8 Gb Of Ram 3200 Mhz
- Windows 10 Pro

# The issue : 
there are stutters on fifa street when we are in-game it's related to the spu caches because in mega mode there are less stutters than in safe mode and the spu caches because larger and larger, run after run of the game because i think it caches all the movements and shadows so you need to do an optimization on spu caches to be able to run the game properly

**Comment by AniLeo** [comment]
If it's just a "lag" report and you're not reporting a specific issue it can be closed since it falls under a game compatibility report. SPU Analyser is not finished and some games are not supported yet so some caches will be built forever, there's also another opened issue regarding that.
