### ISSUE TITLE
Ni No Kuni [BLES0555] - Boss Freezes

### ISSUE THREAD

**Issue by hockland** [RPCS3/rpcs3#5207]
So the early RSX works fixed about 90% of the freeze issues in Ni No Kuni, but not all of them.

Occasionally in normal battles, but far more common in boss battles. The game now freezes with a "E {rsx::thread} RSX: FIFO: RET found without corresponding CALL. Discarding queue" error reported. When this occurs, all audio continues to play (music only), but the screen freezes completely.

I would attach my log, but it's over 1GB. Will edit my post with the log when I'm able to get one at a much lower file size. 

I'm currently at the final boss of the game, and it's occurred on both attempts at it. Though it is not an error that occurs 100% of the time, unlike the earlier freeze bugs which occurred more frequently. I'll try a 3rd attempt at that boss so that I can get some log data at a far lower file size.

Here is a save up to that boss.
[BLES01555_00001.zip](https://github.com/RPCS3/rpcs3/files/2433297/BLES01555_00001.zip)

**Comment by CrabLugo** [comment]
I had this freeze everytime i tried final boss. It happens sooner oraz later, but it's really long fight. With better preparation, it's difficult (but possibile) to do it fast enough, before definitely freeze.
Can't provide log for now as well

**Comment by hockland** [comment]
3rd attempt resulted in me beating her, so yeah no log. Hmm. Happens quite often though, so if you use my save and #5188 you'll have it happen to you quite likely.

**Comment by Metasynic** [comment]
I'm working my way through the game at the moment and had this crash once on a boss already (can't remember which one). Next time I get it (probably on the final boss) I'll upload the log here.

**Comment by Metasynic** [comment]
Happened a lot sooner than expected, with no clear cause, in the Fairygrounds. My hardware is Ryzen 5 1500X, GTX 970 with Win10.

Log: [RPCS3.log (NNK, ret without call).gz](https://github.com/RPCS3/rpcs3/files/2738447/RPCS3.log.NNK.ret.without.call.gz)

**Comment by Zardas81** [comment]
Here's a log file with OpenGL.

`·E 0:43:49.326547 {RSX [0x000098c]} RSX: FIFO: RET found without corresponding CALL. Discarding queue`

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2861814/RPCS3.zip)

**Comment by elad335** [comment]
Retest with rsx wake-up delay.

**Comment by elad335** [comment]
I suggest closing this issue as users have reported crashes are fixed with rsx wake-up delay on discord long ago.
