### ISSUE TITLE
Resistance 2 [BCES00226] Segfault

### ISSUE THREAD

**Issue by xelmasx** [RPCS3/rpcs3#5208]
System Specs ; OS "Fedora 29 Linux", CPU "AMD 2700x", GPU "AMD vega 56".
[Resistance 2 [BCES00226].log](https://github.com/RPCS3/rpcs3/files/2433336/Resistance.2.BCES00226.log)
![screenshot from 2018-10-01 11-52-11](https://user-images.githubusercontent.com/21128451/46279576-1ee3f680-c572-11e8-9d61-a3eb173c198f.png)
![screenshot from 2018-10-01 11-57-20](https://user-images.githubusercontent.com/21128451/46279577-1ee3f680-c572-11e8-9924-d1f79f2a242b.png)

I will add pics and log.

**Comment by digitaldude555** [comment]
@xelmasx is this still an issue?

**Comment by AniLeo** [comment]
Manjaro, R7 2700X, R9 280X
Using Mesa 19.3 with radv amdvlk

![image](https://user-images.githubusercontent.com/10283761/73983704-ee168d00-492e-11ea-9b8e-87b82eed5ed2.png)

Cannot reproduce. Very likely not an issue anymore.

**Comment by xelmasx** [comment]
so far so good.Thanks.
