### ISSUE TITLE
"Heavy Rain" hard audio/video stuttering

### ISSUE THREAD

**Issue by questore** [RPCS3/rpcs3#5209]
Heavy Rain have hard audio stuttering from the start.
After starting the game the audio has a constant stuttering.
- On the main loading video the FPS counter shows 30/60 according to the configuration maximum, but the audio is already stuttering. 
- When the main menu comes in the rain effect sound is fine but the music has hard stuttering
- Durring the game the audio stuttering is constant.

System specs:
Win10, AMD FX-8120E, 8Gb, SSD, Radeon R9 380 4Gb Gaming (NVIDIA 770GTX 2Gb same specs have the same problem) 

RPCS options: tryed spu thread 1-6 no change only stuttering interval becomes a little different. 
Disabled vertex cache, async, Strict mode, etc  but nothing helped. 
OpenGL a little worse then Vulcan.

**Comment by AniLeo** [comment]
This is not a specific issue report but rather a "lag" / game report
This game is not Playable yet and your specs are low end so this is pretty much expected

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
