### ISSUE TITLE
Xinput not working in some cases (DS4 Windows)

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#5212]
Ok, this is hard to explain, but I´ll try with some examples:

We have 3 or 4 controllers:

1 ps4 controller
2-3 xbox one/360 controllers

4 Controllers:
-Connect the 4 controllers in random order
In gamepad settings we have:

Player 1: Dualshock 4 (Handlers Dualshock 4)
Player 2: Xbox one/360 (Handler xinput) (Xinput pad 0)
Player 3: Xbox one/360 (Handler xinput) (Xinput pad 1)
Player 4: Xbox one/360 (Handler xinput) (Xinput pad 2) ---In my case this one doesn´t work unless is set to (Xinput pad3)

DISCONNECT ALL CONTROLLERS A CONNECT IT AGAIN

3 Controllers:
-Connect the 3 controllers in random order
In gamepad settings we have:

Player 1: Dualshock 4 (Handlers Dualshock 4)
Player 2: Xbox one/360 (Handler xinput) (Xinput pad 0) --- This one doesn´t work this time with this conf
Player 3: Xbox one/360 (Handler xinput) (Xinput pad 1) --- This is now the player two 
Player 4: Xbox one/360 (Handler xinput) (Xinput pad 2) --- This is now the player three, but it usses the 4th port, and is a only 3 player game for example.

I don´t know how to explain better, in any case, someone with 3-4 controllers (I think one of theese must be an DS4 ir order to trigger the problem) can test it by opening for example the emulator with (1 DS4 + 3 xbox controllers) unplug all, connect again but only three (including DS4) and retest again. (DS4 windows needs to be open)

I don´t know why this is happening, I think this only happens when DS4 windows is used (This program detects the DS4 as a xinput) but a possible workaround for this is to keep the ID of the controllers to each player, like for example the DS4 does. Or maybe an option to avoid DS4 to use/increment one of the xinput ports at the same time of the Handler Dualshock 4 is being used.

**Comment by LuismaSP89** [comment]
Note: Tested the same scenario with other emulators like cemu, and all works Ok.

**Comment by Megamouse** [comment]
We literally have a ds4 handler. So why not just use that one instead of some weird xinput workaround

**Comment by LuismaSP89** [comment]
@Megamouse Because DS4 windows is needed for some gyro games like uncharted 1, heavy rain, etc.

**Comment by LuismaSP89** [comment]
@Megamouse Ok, tested without DS4 windows and it works, I thought is needed in rpcs3 to use Gyro controls, sorry.

Closing.
