### ISSUE TITLE
Controller input issues with all Call of Juarez games

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#5215]
All of the Call of Juarez games have a serious issue, they are not registering inputs from the face buttons ( X, Square, Triangle and Circle). Thankfully all of the other buttons and joysticks are working fine as far as I can tell. I have tried using both my keyboard as an input and Xinput but both had the same issue with all of these games. Thankfully Call of Juarez: Bound in Blood can still go ingame if you just push "start" instead of "X", but you will get stuck pretty quickly as you cannot open this door.

![rpcs3_2018-10-03_2856](https://user-images.githubusercontent.com/15137035/46368893-ee36b680-c670-11e8-9806-d2ffd1f5e538.jpg)

Unlike Call of Juarez: Bound in Blood which can go ingame; Call of Juarez: Gunslinger, and Call of Juarez Cartel are stuck in the "Intro" status as you can't get past the gamma screen because X is not being registered.

![rpcs3_2018-10-03_2858](https://user-images.githubusercontent.com/15137035/46367458-263bfa80-c66d-11e8-90b0-fe323286d583.jpg)
![image](https://user-images.githubusercontent.com/15137035/46368924-03134a00-c671-11e8-940f-7a3f3aa5bfc2.png)
[Call of Juarez: Bound By Blood.log.gz](https://github.com/RPCS3/rpcs3/files/2438739/RPCS3.log.gz)
[Call of Juarez: Gunslinger.log.gz](https://github.com/RPCS3/rpcs3/files/2439098/RPCS3.log.gz)

Call of Juarez: Cartel (Log from GrantKane on our forums)
https://forums.rpcs3.net/attachment.php?aid=10300

**Comment by Asinin3** [comment]
It seems like this is also affecting Call of Juarez: Gunslinger. During the intro it will come to a screen where you can adjust gamma levels. While you can move the slider left/right pressing X doesn't do anything so you cant progress past it. Once again, I tried both Xinput and using keyboard as an input.
![rpcs3_2018-10-03_2858](https://user-images.githubusercontent.com/15137035/46367458-263bfa80-c66d-11e8-90b0-fe323286d583.jpg)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2439098/RPCS3.log.gz)

**Comment by Xcedf** [comment]
Same issue as Dead Island always had

**Comment by elad335** [comment]
Fixed by #5311
