### ISSUE TITLE
AppImage: Missing libnsl.so.1 (Fedora 28)

### ISSUE THREAD

**Issue by pmilleroly27** [RPCS3/rpcs3#5224]
RPCS3 Fedora 28, Appimage unable to run

```
chmod a+x ./rpcs3-v0.0.5-7390-8e268aed_linux64.AppImage
./rpcs3-v0.0.5-7390-8e268aed_linux64.AppImage
rpcs3: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
```

Already installed package, but didn't change output

dnf install libnsl.so.1

ls output is :
rpcs3-v0.0.5-7390-8e268aed_linux64.AppImage

Build

Fedora 28
Ryzen 2700
GTX 1060
NVIDIA Proprietary Drivers

Same result on Fedora 28 with a 2700u Laptop, I also previously had CentOS 7 installed with the same issue. I was told on RPCS3 Forums to post this issue here. I've tried several different RPCS3 installers. I'm a newb poster sorry for the sloppy post.

**Comment by hcorion** [comment]
@probonopd any ideas?

for reference, build script here: https://github.com/RPCS3/rpcs3/blob/master/.travis/build-linux.bash and packaging script here: 
https://github.com/RPCS3/rpcs3/blob/master/.travis/deploy-linux.bash
and you can get the latest appimage via `curl -JLO https://rpcs3.net/latest-appimage`
The AppImage is being built on a Ubuntu 14.04 docker container, dockerfile here: 
https://github.com/hcorion/rpcs3-docker/blob/master/trusty/Dockerfile

**Comment by probonopd** [comment]
Yes, I guess you need to bundle `libnsl.so.1` thanks to https://gitlab.com/probono/platformissues#glibc

I don't know yet whether this can have any ill side effects. So may be worth a try.

**Comment by hcorion** [comment]
I've removed libnsl.so.1 and done a bunch of testing on these distros:
Ubuntu 14.04
Fedora 26, 27 and 28
Pop! OS 17.10, 18.04
OpenSUSE Tumbleweed
Debian 8, 9
Arch Linux

And have also been able to get our community to test the following distros: 
Elementary 5.0
Ubuntu 16.04, 17.10, 18.04
Linux Mint 18.3

And noticed no ill-effects, that's a good enough selection for me to put it into production. I'll make a PR to upstream it soon.
