### ISSUE TITLE
Xbox 360 controller can be configured but not recognized in game

### ISSUE THREAD

**Issue by e88z4** [RPCS3/rpcs3#5226]
I am experiencing an issue with my xbox 360 controller detection in the game. The controller is recognized by evdev input and can be configured. When the game starts, the controller is not recognized. Some games displayed "wireless controller is not detected".

No obvious error on the console or log. 

My system is Debian Sid with Kernel 4.17.18. 
CPU: Ryzen 5 2600
16 GB Memory
Radeon 7950
RPCS3 7428

I played other emulators such as ppsspp or PCSX2, the controller is working fine in game. Is this a known issue?

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2452373/RPCS3.log.gz)

**Comment by kd-11** [comment]
The evdev handle is lost on device reboot so you have to reconfigure it every time you boot rpcs3 off a fresh start. Its a known issue because evdev keeps reassigning the controller to different mount points.

**Comment by e88z4** [comment]
Do I have to go to the pad menu, press refresh and click apply each time I start rpcs3?
If that's the case, I couldn't see the apply button in linux because of the huge pad menu problem like in this issue https://github.com/RPCS3/rpcs3/issues/3786

I couldn't adjust the pad screen menu or even scroll. 

Is there a way to do this directly in the configuration file?

**Comment by Monkena** [comment]
having problems with exactly this on ubuntu 18.04, has anyone found any workarounds?

**Comment by GitArUs** [comment]
@e88z4 You may be able to move a window by holding left Alt, clicking anywhere on window and dragging it, thus making "save" button available.

**Comment by e88z4** [comment]
@GitArUs , thank you for your resolution. I was able to save the controller setting by dragging the window. Refreshing and saving the controller setting each time I start rpcs3 after reboot solves the problem. This is the temporary workaround for me.

**Comment by hcorion** [comment]
Is this still an issue?

**Comment by ipkpjersi** [comment]
I use an Xbox 360 wireless controller on Ubuntu 16.04 without issues on Red Dead Redemption and both Skate 2 and 3, I tested build 7460 and it works fine for me.

**Comment by Megamouse** [comment]
@e88z4 can you please retest this

**Comment by e88z4** [comment]
@Megamouse 
I just built the latest master commit 75221a6078226327ea90370ca179e8cd7b06ed1c. 
The issue seems to be fixed. I don't have to save the controller's evdev configuration after reboot. Issue can be closed.

**Comment by sergoncano** [comment]
This issue happened to me on linux mint, with an un-official xbox 360 controller.
It got solved by adding a custom gamepad configuration to each game I wanted to play.
