### ISSUE TITLE
Crash with ***LINUX*** when entering loading screen in Demon's Souls [BLES00932]

### ISSUE THREAD

**Issue by dolohow** [RPCS3/rpcs3#5228]
Version: `cc846eb6`
OS: `Arch Linux`
Graphics: `Mesa 18.2.1 with RX 480`
When running `Demon's Souls [BLES00932]` emulator crashes when loading tutorial with:
```
terminate called after throwing an instance of 'std::runtime_error'                                                  
  what():  Verification failed (e=11): semaphore_base: overflow                                                      
(in file ../Utilities/sema.cpp:65)
```

**Comment by eggboys** [comment]
Are you by any chance using KDE?
If so, try launching with `KDE_DEBUG=1` in environment variables. 
This disables KCrash, which intervenes in signal handling used in the emulator.
