### ISSUE TITLE
Doom 3 BFG -BLUS31024 is not starting

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#5230]
Tested on Geforce 970, Core i7 4770S, 32GB, Win10 64bit.

Its old known error, but there is not bug for it, at least not with Doom with its name.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2453338/RPCS3.zip)

**Comment by Asinin3** [comment]
This Pull Request, which has been open for awhile and not yet merged already fixes this. https://github.com/RPCS3/rpcs3/pull/4592 Also this issue seems more like a compatibility report and not an actual issue report.

**Comment by ruthan** [comment]
It is bug by definition, bug by definition shouldnt be dependent if there is some planed or existing not merged piece of code (there is pretty big change that fix, will not work..). Otherwise is you development workflow very twisted.

**Comment by AniLeo** [comment]
Review yes, respond mostly there's no need too. No one is going to check thousands of games on a case by case basis.

**Comment by dcon03** [comment]
> Hey guys can you help me fix the black screen on DOOM Classic Complete

Forums isn't the place for game support (not to mention necro'ing an old closed report)

go to the Discord server for help
