### ISSUE TITLE
Tekken Dark Resurrection [NPUB30009] - Polygon spasms

### ISSUE THREAD

**Issue by CarlHalstead** [RPCS3/rpcs3#5233]
Hey,

Just tested Tekken Dark Resurrection and there are issues with what I would describe as 'Polygon spasms' specifically with 'Kazuya Mishima's' hair. There are times when it is positioned incorrectly as well times where it goes invisible. This not only affects the hair but also the clothes, however, I think this hair represents the issue best.

I am using the latest master build (7428 I believe) and my PC specs are:

- OS - Windows 10 - Latest build
- CPU - i3-6320 - 2C/4T
- GPU - RX 470 - Latest optional driver (18.9.3)
- RAM - 16GB DDR4 2400MHz
- Storage - rpcs3 is on my secondary 1TB HDD.

### Heres a video of the spasms:
[Video](https://i.imgur.com/XlDpfQK.gifv)

Apologies for the low framerate while recording.

### Here are my CPU settings in rpcs3:
![CPU](https://i.imgur.com/Rd4elNe.png)

### Heres my GPU settings:
![GPU](https://i.imgur.com/Q2FZ16z.png)

Everything else is default and I believe these CPU and GPU settings are all default too but have tried a number of different settings to no avail, including 'Strict Rendering Mode'.

### Log file
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2454091/RPCS3.log.gz)

I had a look and saw no previous reports of this so here I am.
If you need anything else just let me know, loving the progress so far.

**Comment by scribam** [comment]
@CarlHalstead Is it still an issue? It works fine for me with the latest RPCS3 build.

**Comment by CarlHalstead** [comment]
@scribam Hey, I have just tested it and it does not appear to be an issue. Since the creation of this post, I has also upgraded to a Ryzen 7 2700 but I assume that would not affect an issue such as this. So yes, it does appear to be fixed. Closing.
