### ISSUE TITLE
RPCS3:Fatal Error ( Segfault reading location 00007fdaf1fa61d0 at 00007fdaf1fa61d0 )

### ISSUE THREAD

**Issue by btpp2010** [RPCS3/rpcs3#5235]
Hi Guys,
can anybody help me with this error:
![screenshot from 2018-10-08 10-55-22](https://user-images.githubusercontent.com/39798112/46600064-4cd4b800-cae9-11e8-8a17-9009b0b946ec.png)
My scpecs are:
![screenshot from 2018-10-08 11-00-50](https://user-images.githubusercontent.com/39798112/46600171-a0470600-cae9-11e8-8452-2fbdd1e956c8.png)

**Comment by AniLeo** [comment]
Closed for disrespecting tracker guidelines

**Comment by btpp2010** [comment]
?

**Comment by HerrHulaHoop** [comment]
The prompt when you try to create a new issue clearly states this is not a support forum. Please use our [forums](https://forums.rpcs3.net) or [discord](https://discord.me/RPCS3) to get help.

**Comment by btpp2010** [comment]
oh sorry 
thanx
