### ISSUE TITLE
Goldeneye 007 reloaded can't install since 0.0.5-7262

### ISSUE THREAD

**Issue by Josivan88** [RPCS3/rpcs3#5238]
Since RPCS3 0.0.5-7262 @jmatich PR Goldeneye 007 reloaded can't do the first install, after launch game said:
"installing data... please do not switch off the power...
and stays in there, sometimes hangs, sometimes crash the emulator and so on.

My Specs:
Core i7 4790
16 Gb of RAM
Nvidia 1070Ti

7261 build:
![7261](https://user-images.githubusercontent.com/36341425/46645983-f9e91800-cb5d-11e8-80aa-30f77f67c97f.jpg)

7262 build:
![007 reloaded 7262](https://user-images.githubusercontent.com/36341425/46646166-f86c1f80-cb5e-11e8-937e-bd6a35bd0885.jpg)

LOG 7262
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2458824/RPCS3.log.gz)

Errors start in this:
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x50300480

Keep and finish in this:
U {PPU[0x1000009] Thread (MoveThread) [0x0041b270]} cellGem TODO: cellGemUpdateFinish()
E {PPU[0x1000014] Thread (_sys_MixerChStripMain) [0x0086fbec]} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x68912]
E {PPU[0x1000016] Thread (_cellsurMixerMain) [0x0086c3a8]} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x17228]
E {PPU[0x1000016] Thread (_cellsurMixerMain) [0x0086c3a8]} Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x8614]

**Comment by reecespieces** [comment]
problem persists in 0.0.6-7857

**Comment by Josivan88** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2963470/RPCS3.log.gz)
fixed on 0.0.6-7866 to me

**Comment by AniLeo** [comment]
Closing as reported fixed
