### ISSUE TITLE
RPCS3 crashes when compiling SPU cache

### ISSUE THREAD

**Issue by IvoryKing1991** [RPCS3/rpcs3#5245]
RPCS3 0.0.5-7433. R5 1600, RX550, Win10.
Emulator crashes every time, when compiling SPU cache. I try Vulkan and OpenGL - same. I try all my games (4 titles) - same.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2467210/RPCS3.log)

**Comment by M9k** [comment]
Same error with SPU Decoder: Recompiler (LLVM), work with other settings.

**Comment by AniLeo** [comment]
Closing as duplicate of #5257
