### ISSUE TITLE
Hatsune Miku Project Diva F 2nd (Possibly affects F)

### ISSUE THREAD

**Issue by whymsical210** [RPCS3/rpcs3#5249]
Project Diva F2nd (USA BLUS31431 + DLC)
PPU: LLVM
SPU: LLVM (no xfloat)
Vulkan Renderer

The game will at random freeze up. Video will stop responding. Controls will stop responding and the emu will become unresponsive. Interestingly, the emulator will also turn off the DS4 controller when this occurs. 

![image](https://user-images.githubusercontent.com/19926555/46895747-b6392b80-ce47-11e8-9626-e7ac02f9091e.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2474698/RPCS3.log)

If you need any more info, I'm obviously always in Discord, so hit me up if you need more information. 
Thus far, I've only had time to test on current master, as it is a random bug that has no real timing defined for it that i can tell. I will test on previous master releases a bit later today when I can get a chance and post any new information I can find.

**Comment by whymsical210** [comment]
Happend again. Log looks very different this time, looks to be showing whats causing the issue.  

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2474947/RPCS3.log)

**Comment by kd-11** [comment]
This ended up being the infamous nvidia driver hang. Closing as fixed.
