### ISSUE TITLE
 Kingdom hearts 2.5 BLES02070 Errors Audio Solved

### ISSUE THREAD

**Issue by CateNow** [RPCS3/rpcs3#5251]
I'm trying to play it from the beginning but the audio is cut randomly and it does not sound again until it reboots, Sometimes the game crashes,, but the audio always goes away after a short time of playing.
I've tried all kinds of CPU and GPU configurations and nothing

My system: I5-4460 Gpu: 960 2gb 8 RAM Windows 10 Home
Tested with RPCS3 Build 0.0.5-7435-8540399e Alpha

Edit 2
I have tried to change the preferred SPU Threads to 1 but there are no changes. I'm also forcing vsync from the NVIDIA control panel because the rcps3 vsync does not remove the tear

Edit 3
In this log the audio followed a little more, and after trying several I think it happens when loading a new zone.
I left just when the auido was removed
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2476657/RPCS3.log)

Edit 4 
I find a solution https://ibb.co/eT2cgL
                             https://ibb.co/bwDpvf
 Try these setting ami they worked for me , In CPU Preferred threads put the number of threads of your processor in my case is 4 
It was a temporary solution I was again removed the audio

**Comment by Diserasta** [comment]
Can you please upload your RPCS3.log from the folder RPCS3 is installed in? If it's too big, zip it up.

**Comment by CateNow** [comment]
> ¿Puede por favor cargar su RPCS3.log desde la carpeta donde está instalado RPCS3? Si es demasiado grande, ciérralo.
> 
> Además, ¿has intentado usar la versión más reciente?
I will try with the latest version if there are any changes

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2475508/RPCS3.log)

**Comment by CateNow** [comment]
I've seen that when the audio is removed the SPU stops, and it can not be restarted

[https://www.youtube.com/watch?v=2H96OTeCsmk&feature=youtu.be](url)

**Comment by Diserasta** [comment]
> 
> 
> > > ¿Puede por favor cargar su RPCS3.log desde la carpeta donde está instalado RPCS3? Si es demasiado grande, ciérralo.
> > > Además, ¿has intentado usar la versión más reciente?
> > 
> > 
> > I will try with the latest version if there are any changes
> > [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2475508/RPCS3.log)
> 
> That log file contains no information. Devs/Helpers need a complete log file in order to begin troubleshooting. It sounds simliar to the issue with the surmix thread dying, though.

Try playing the game for a while until you see the SPU stop, and then upload the new log file. Make sure to exit RPCS3 before uploading the log.

**Comment by CateNow** [comment]
> > > > ¿Puede por favor cargar su RPCS3.log desde la carpeta donde está instalado RPCS3? Si es demasiado grande, ciérralo. 
> > > > Además, ¿ha intentado usar la versión más reciente?
> > > 
> > > 
> > > Voy a probar con la última versión si hay algún cambio 
> > > [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2475508/RPCS3.log)
> > 
> > 
> > Ese archivo de registro no contiene información. Los desarrolladores / ayudantes necesitan un archivo de registro completo para comenzar la solución de problemas. Sin embargo, suena similar al problema con la muerte del hilo de la mezcla.
> 
> Intente jugar el juego por un tiempo hasta que vea que la SPU se detiene, y luego cargue el nuevo archivo de registro. Asegúrese de salir de RPCS3 antes de cargar el registro.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2476293/RPCS3.log)

**Comment by CateNow** [comment]
I do not understand why some do not like it, so I do not know anything about it until yesterday. I did not know what a registry was, I'm just a normal user who has tried to play a playable game that is not. And that's why I report here if you could find a solution and more people like me that did not work, the game does not happen to them
I gave my donation to Patreon but ...
I know that emulation is a complicated process, but why do not I like a problem?

**Comment by CateNow** [comment]
Solved for me
