### ISSUE TITLE
Diablo 3 Freezes after character select.

### ISSUE THREAD

**Issue by makotech222** [RPCS3/rpcs3#5253]
Game: Diablo 3 Ultimate Evil Edition
ID: NPEB02026 & BLUS31437 (I tested both)
Description:

After selecting a character and starting the campaign, as soon as the level finishes loading, the game locks up, with no way to proceed. No error occurs, and the emulator does not crash. 

I've seen other people play much farther into the game, but I've noticed all of them having an 8 core CPU (I have a 4 core 6600k). This is just speculation. Also, the logs mention deadlock/mutex issues, likely pointing to a threading issue. This has been an issue for me for a long time ( > 1 year), just never got around to reporting it.

[rpcs3.log](https://github.com/RPCS3/rpcs3/files/2476066/rpcs3.log)

**Comment by MSuih** [comment]
It's the same desynchronization issue that affects hundreds of other games as well. On Ryzen 1600 the game either freezes within 10 seconds after going ingame or continues for about a minute before freezing. And yes, the issue had existed even when the emulator rendered acid colors.

**Comment by johan2121** [comment]
Game: Diablo 3 Ultimate Evil Edition
ID:BLUS31437 (I tested both)
emulator does not crash but frezze the games 

I5 3450 y I5 3570  Itested
GPU: GTX660ti and gts 450 opengl y vulkan

please fix this problem
and sorry for my bad inglish, im south american

**Comment by ruthan** [comment]
I have same problems for long times, on multiple Windows 10 + Nvidia G970 machines. In best scenario, you can play up to few minutes, it could be connected with problem, that my progress is never saved.

**Comment by gabrielformiga** [comment]
I5 7600k, 1070 GTX, same problem, unless I set process priority to realtime, but still crashes sometimes.

**Comment by johan2121** [comment]
> Tengo los mismos problemas durante mucho tiempo, en varias máquinas Windows 10 + Nvidia G970. En el mejor de los casos, puedes jugar hasta unos minutos, podría estar relacionado con un problema, y ​​mi progreso nunca se guarda. 
> Otra observación es que en la máquina TSX es más estable, pero todavía tiene este problema.

could you check in w7? in a video I watched an i5 sandybridge playing for an hour and ran the w7 system

**Comment by johan2121** [comment]
> I5 7600k, 1070 GTX, el mismo problema, a menos que establezca la prioridad del proceso en tiempo real, pero a veces se bloquea.

could you check in w7? in a video I watched an i5 sandybridge playing for an hour and ran the w7 system

**Comment by ruthan** [comment]
This last build 7458 is there at least error: F {PPU[0x1000000] Thread (main_thread) [0x01305e60]} MEM: Access violation reading location 0x451240d0

**Comment by namescmyta** [comment]
Tried so many times to progress in this game on lastest build, freezed every one of them. Any CPU/GPU configuration has no effect, maybe a bit more gameplay time, but freeze 100% occurs at the end

**Comment by Crispy81** [comment]
For me, can play for anywhere between 5 - 10 minutes before this gem appears... very frustrating.

F {SPU[0x2000001] Thread (CellSpursKernel1) [0x05ce8]} MEM: Access violation writing location 0xffdead00

**Comment by Crispy81** [comment]
All versions of Diablo 3 and RoS are riddled with MEM access violation errors. Hopefully they get fixed soon.

**Comment by Josivan88** [comment]
last PR (0.0.5-7623) make Diablo 3 remain on infinite load at very 1st screen - "Autosave - Diablo 3 supports autosaving."

**Comment by benderscruffy** [comment]
time to update the issue

**Comment by digitaldude555** [comment]
Tested few weeks ago still an issue.

**Comment by Crispy81** [comment]
All versions, all editions still have MEM access violations and random freezing ingame.

**Comment by MSuih** [comment]
Original issue has been fixed, same for the autosave issue. Random freezing and crashes during gameplay is tracked at #5593.

**Comment by LightAcolyte** [comment]
I have been able to play through the game on single player, but playing multi-player (local co-op) I can't get even to Tristram after starting each time.
