### ISSUE TITLE
Regressions from #5211

### ISSUE THREAD

**Issue by Gingira** [RPCS3/rpcs3#5257]
No games are managing to boot with this SPU decoder since a few weeks now. The last build I tried with a still working LLVM recompiler is ver 0.0.5-7411. Anything after that doesn't boot at all. The ASMJIT recompiler is still fine.
Sorry if this is a known issue or if it's being reworked hard enough to break it for now (it does say it's experimental after all, but it was working like a charm) but it's worrying since no one else seems to have noticed for a while and it could also be a problem on my end, too.

**Comment by AniLeo** [comment]
Need exact version that regressed it

**Comment by HerrHulaHoop** [comment]
You might've already done this, but try clearing your SPU and LLVM cache.

**Comment by IvoryKing1991** [comment]
#5245

**Comment by Gingira** [comment]
After more testing, I actually got it. It's the SPU Block Size.
Since 7412, The "Giga" setting crash without fail on every games when paired with the SPU LLVM Recompiler, however the games does boot on the "Mega" setting!
Also, the ASMJIT Recompiler still work with the "Giga" setting.
Now I feel dumb. Hopefully this helps someone though.

**Comment by beavermml** [comment]
i confirm it with P5.. setting to SAFE will make it boot

**Comment by Megamouse** [comment]
_NPEB00592: Backbreaker Vengeance Trial_ crashes while compiling SPU cache on every build after this PR was merged.

**Comment by Dagda52** [comment]
spu llvm recompiler works on ubuntu 18.04.1 on any game without issues, is even faster, but crashes on windows 10.

**Comment by legend800** [comment]
So this is a Windows 10 only issue? How did that PR impact compat.? Track down what could affect functionality on different OSes and there's your culprit I guess.

**Comment by legend800** [comment]
@Nekotekina Can you look into this regression? Still active as of today. Let me know if you need anything.

Log from Backbreaker - if SPU cache exist, crashes emu during compile:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2845827/RPCS3.log)

If it doesn't exist, it'll crash when entering gameplay. Always worked fine before this commit:
https://github.com/RPCS3/rpcs3/pull/5211

**Comment by legend800** [comment]
Still present on today's build. Whole emu crashes when building or loading SPU cache, on at least Backbreaker series. 

Log:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3069406/RPCS3.zip)

**Comment by legend800** [comment]
Fixed on new build. This can probably be closed.
