### ISSUE TITLE
Regression: LittleBigPlanet 2 & 3 after #5146

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#5259]
Before #5146 (version 7372), both LittleBigPlanet 2 and 3 used to go ingame. After it, they crash with validation error after intro movies.

Vulkan: `F {rsx::thread} class std::runtime_error thrown: Verification failed: (in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\glgsrender.cpp:1483)`
OpenGL: `F {rsx::thread} class std::runtime_error thrown: Verification failed: (in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\glgsrender.cpp:1483)`

I tested the commits one by one and, as expected, 7b7c5a3 was the culprit. Disabling the verification and putting the condition into the next if statement causes the emulator to go ingame, but it causes the emulator to freeze fairly quickly.

[Log with debug output](https://github.com/RPCS3/rpcs3/files/2488414/RPCS3.log.gz)

**Comment by HexyFify** [comment]
afaik cpu blit fixes freezing in lbp2 as quickly

**Comment by HexyFify** [comment]
Nope doesn't help after #5146

**Comment by kd-11** [comment]
This particular issue should be fixed by https://github.com/RPCS3/rpcs3/pull/5315. Surface store miss due to pitch mismatch was the cause for the merged fetch failing.

**Comment by MSuih** [comment]
The fatal error is gone, but both games just freeze instead. It's hard to say whether that is an error with the PR or just other regression that was just hidden by the more oblivous bug,

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2566593/RPCS3.log.gz)

**Comment by Hopefullyidontgetbanned** [comment]
@kd-11 seems like it still has that error

**Comment by Hopefullyidontgetbanned** [comment]
it now has this error after it locks up and the user exits the program
`F {rsx::thread} RSX: class std::runtime_error thrown: Verification failed: 
(in file c:\users\sean buckley\documents\rpcs3\rpcs3\rpcs3\emu\rsx\vk\vkgsrender.cpp:3235)`

it locks up with this error seen in all 3 of the games 
`E {PPU[0x1000017] Thread (game host thread) [0x00ea016c]} sys_net: sys_net_bnet_select(): exceptfds not implemented`

**Comment by MSuih** [comment]
Fixed with 52ac0a9
