### ISSUE TITLE
Hard Corps Uprising regressed to nothing after #5188

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#5260]
After https://github.com/RPCS3/rpcs3/pull/5188 merged Hard Corps Uprising crashes RPCS3 upon boot.
![image](https://user-images.githubusercontent.com/15137035/47108865-48707380-d23c-11e8-9293-0167d1d05ec0.png)
Cleaning LLVM cache did not help.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2488784/RPCS3.log)

**Comment by Wizzy2018** [comment]
i have a same error

**Comment by Wizzy2018** [comment]
I tested and i have a black screen after a intro movie :(

**Comment by Asinin3** [comment]
Then it's not the same error.

**Comment by Wizzy2018** [comment]
Oh yes you are right :D

**Comment by Wizzy2018** [comment]
I send tommorow my log of issue

**Comment by Wizzy2018** [comment]
Here is my error on Build 0.0.5-7439
![screenshot 7](https://user-images.githubusercontent.com/44261686/47252080-d5831a80-d43e-11e8-9d09-d45465b9327c.png)

**Comment by Wizzy2018** [comment]
On builds before 5188 i getting a black screen after a intro movie

**Comment by Asinin3** [comment]
This has been fixed, not sure when.
