### ISSUE TITLE
Problem setting joystick (cross, square, triangle, circle)

### ISSUE THREAD

**Issue by latot** [RPCS3/rpcs3#5262]
Hi, i don't use RPCS3 in a while, i was playing a game, and i config my joystick, it works fine before, and only to be sure now, i test the joystick with the ppsspp options to detect keys of it, seems to work fine.

For some reason i can't set right some keys, i press it but set other thing..., is weird, here an image with all buttons configured:

![captura de pantalla de 2018-10-17 18-06-23](https://user-images.githubusercontent.com/10523095/47116344-c41bf180-d237-11e8-9e19-087115b61411.png)

The face buttons, L1, L2, L3, R1, R2, R3, and more have exactly the same code, RZ+, and when i try to play the left analog works to move but i can't pass the first "yes/no" option ingame, so, at least i can confirm the cross/circle buttons don't works.

The only output of RPCS3 is:

```
libpng warning: iCCP: known incorrect sRGB profile
qt.qpa.xcb: QXcbConnection: XCB error: 146 (Unknown), sequence: 5877, resource id: 0, major code: 139 (Unknown), minor code: 20
qt.qpa.xcb: QXcbConnection: XCB error: 146 (Unknown), sequence: 6060, resource id: 0, major code: 139 (Unknown), minor code: 20
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

If you need something ask for it, i don't know very well where get more logs.

Edited:

Ups, i use Linux, Gentoo 64, git updated version.

Edited: This is only in linux, in windows works fine,

Bye.

**Comment by Megamouse** [comment]
I wont comment on this again. There are other issues that provide the solution

**Comment by Megamouse** [comment]
closing because there are already workarounds and this seems to be a driver issue

**Comment by latot** [comment]
Hi, i don't whink is a driver issue, at least, the control works perfectly with ppsspp.
