### ISSUE TITLE
R&C: Nexus deadlocks on boot

### ISSUE THREAD

**Issue by ScorchEmber256** [RPCS3/rpcs3#5266]
On latest mater build (build origin: RPCS3/rpcs3/master/=5261), Ratchet & Clank: Nexus softlocks prior to title screen when using vulkan API. The only way to progress further is to delete the shadercache every boot. Does not affect OpenGL.

Ratchet & Clank: Nexus - First Boot
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2494251/RPCS3.log.gz)

Ratchet & Clank: Nexus - Second Boot
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2494259/RPCS3.log.gz)

**Comment by kd-11** [comment]
Looks like a race condition (loading shaders pauses the emulator which some games do not like). Likely has nothing to do with the shaders. In fact the graphics renderer is still running in the second log when you close the game - it never crashed, but Cell seemingly desynchronized and is stuck. Needs retesting with every synchronization update for Cell thread management.

**Comment by Megamouse** [comment]
Does this still happen?

**Comment by Xcedf** [comment]
Have Nexus BCES01908, and also faced this issue, but no more goes ingame every try, no shader cache deleting required, Whatever it was guess it's fixed now.

**Comment by kd-11** [comment]
Closing as fixed.
