### ISSUE TITLE
Diablo 3 Reaper of Souls Ultimate Evil Edition [BLUS31437]  No Sound

### ISSUE THREAD

**Issue by xelmasx** [RPCS3/rpcs3#5273]

**Comment by xelmasx** [comment]
RPCS3 v0.0.5-7451-aed83e69 Alpha | HEAD
AMD Ryzen 7 2700X Eight-Core Processor | 16 Threads | 15.67 GiB RAM | AVX+
GPU : Amd vega 56
There is no sound.

[log.txt](https://github.com/RPCS3/rpcs3/files/2498390/log.txt)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
