### ISSUE TITLE
[BLJM61210] Freeze in second runs

### ISSUE THREAD

**Issue by latot** [RPCS3/rpcs3#5275]
Hi, i'm trying to play this game, i play it before, 8 months, and was working fine, but now don't.

When we open rpcs3 and open the game for first time it works, we can play and all fine, but if we restart the app, the game freeze seconds after start, consuming a lot of CPU, (i have 8 cores, usually eat 4 or 5 at 100%).

I test this in windows rpcs3-0.0.5-7452-966c3fea Alpha, in linux (git version) is similar, instead this happen in the first run, i try change the PPU, SPU and render but is the same result.

I use Gentoo 64, and Win 10 64.

**Comment by latot** [comment]
Okis, here the log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2498678/RPCS3.log)

**Comment by AniLeo** [comment]
You're using a pirated game

**Comment by latot** [comment]
by curiosity, you mean the games need to be run from their own disks?
