### ISSUE TITLE
 The game stays frozen or the audio goes

### ISSUE THREAD

**Issue by CateNow** [RPCS3/rpcs3#5278]
Good I'm trying to play Kingdom Hearts 2.5 although every time I get the audio or I freeze the game I can play it little by little supporting me in the saved.It is more common to cut the audio to cut the game
An example With the log https://youtu.be/9rat1AocYlU
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2499142/RPCS3.log)

**Comment by AniLeo** [comment]
You're using a pirated copy and disrespecting guidelines.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
