### ISSUE TITLE
ratchet and clank future tools of destruction freeze

### ISSUE THREAD

**Issue by Demir2007** [RPCS3/rpcs3#5279]
when i open up the game
it freezes when the game preforms the initial setup process
any help

note: i have tried to upload my problem to the actual rcps3 forum,but i have not figured out how to post

**Comment by AniLeo** [comment]
If you need fórum related help PM a moderator or ask on Discord's help channel 

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
