### ISSUE TITLE
Bionic Commando Rearmed 2 (NPUB30131)

### ISSUE THREAD

**Issue by dallenc** [RPCS3/rpcs3#5287]
Previously playable on the 2017-11-09 Build but PKG after installing successfully does not load when trying to boot with the following error log:

E LDR: SELF: Can't decrypt network NPDRM!
E LDR: SELF: Failed to load SELF file metadata!
E LDR: Failed to decrypt SELF: C:/RPCS3 v0.0.5 Build 7459 (Release 271018)/dev_hdd0/game/NPUB30131/USRDIR/EBOOT.BIN
S LDR: Boot successful.

BUILD:
RPCS3 v0.0.5 Build 7459 (Release 271018)

RAP (Placed in dev_hdd0\home\00000001\exdata):
UP0102-NPUB30131_00-BCREARMED20000NP

SYSTEM:
RPCS3 v0.0.5-7459-1cf62e9d Alpha | HEAD
Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz | 4 Threads | 7.84 GiB RAM | AVX+

PS3 FIRMWARE:
4.83

NOTE:
Other PKG installed games load fine.

**Comment by AniLeo** [comment]
It's an issue with your RAP or PKG. Not an emulator issue, the decryption works fine.

You must ask for support on forums or discord as per the guidelines.

**Comment by jeremybris** [comment]
For anyone that has this, you need to install the (seperate) pkg that unlocks the game.
