### ISSUE TITLE
Regression: Resident Evil Revelations 1 and 2 Infinite loading screens

### ISSUE THREAD

**Issue by Crispy81** [RPCS3/rpcs3#5288]
Both games went ingame and mostly playable at pull request #4526 (rpcs3-v0.0.5-6697-753d8170_win64). 

Pull Request #4504 (rpcs3-v0.0.5-6718-737db900_win64) is when both Resident Evil Revelations 1 and 2 both got into infinite loading screens, and every version following, including most current build, do the same.

BLES01773 - Resident Evil Revelations
BLUS31444 - Resident Evil Revelations 2

**Comment by AniLeo** [comment]
Same issue as #4813

Closing as duplicate
