### ISSUE TITLE
Regression: HLE gcm no longer works after #5244

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#5290]
after cellGcmInit, gcm intr thread will start and access violate. workaround is making its type an interrupt thread so it will only run when needed such as in https://github.com/elad335/rpcs3/commit/862ed16e877244478f7b0d0d36c50e79dcd22b01. but thats a hack so its not the way to go.

**Comment by Nekotekina** [comment]
Interrupt thread should be fine. Stop flag needs to be removed only once after creation.
