### ISSUE TITLE
Suggestion: Add a line that shows your firmware

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#5295]
What about adding a line, that will show you your current firmware version in the "About RPCS3" tab?

**Comment by marosis** [comment]
Not needed. Everybody know that he just have FW 4.83. when he have PS3 right?(ONLY if you don't have pirate version) and now has been updated by PULL REQUEST to 4.83 firmware of RPCS3

**Comment by AniLeo** [comment]
"About RPCS3" dialog doesn't sound like the right place.
Maybe on the log upon initialization and/or on settings dialog near the modules box?

It can be read from line 1 at `dev_flash/vsh/etc/version.txt`

**Comment by Marthgun** [comment]
seems like it would be better to have it in help dropdown somewhere or toggable for the main window bar; somewhere out of the way.  it seems necessary to have the updated firmware anyway, but for whatever reason (testing,etc) it seems like you would know which version you are using anyway.

**Comment by vsub** [comment]
Or in the CPU tab,something like this
![2018-11-08_165053](https://user-images.githubusercontent.com/5032540/48214688-65e6b800-e378-11e8-9f7d-2a79a5bcbea9.jpg)

**Comment by Omaranwa** [comment]
> Or in the CPU tab,something like this
> ![2018-11-08_165053](https://user-images.githubusercontent.com/5032540/48214688-65e6b800-e378-11e8-9f7d-2a79a5bcbea9.jpg)

This Is a good idea.
