### ISSUE TITLE
Regression: Asura's Wrath

### ISSUE THREAD

**Issue by Luffykun007** [RPCS3/rpcs3#5296]
Game it worked well until 0.0.5-7460, the error started at 0.0.5-7461!

Screenshots of configurations used in Rev 0.0.5-7460

![capturar5](https://user-images.githubusercontent.com/26087621/47813844-f1ce6380-dd2a-11e8-871e-7864e887152a.PNG)
----------------------------------------------------------------------------------------------------------------------
![capturar6](https://user-images.githubusercontent.com/26087621/47813868-03177000-dd2b-11e8-98df-5a3cc0b6926c.PNG)
-------------------------------------------------------------------------------------------------------------------
![capturar7](https://user-images.githubusercontent.com/26087621/47813887-11fe2280-dd2b-11e8-868d-fd79ec4b56e8.PNG)
-------------------------------------------------------------------------------------------------------------------
![capturar8](https://user-images.githubusercontent.com/26087621/47813910-1d514e00-dd2b-11e8-8de5-a70e15f5f53c.PNG)
-------------------------------------------------------------------------------------------------------------------
![capturar9](https://user-images.githubusercontent.com/26087621/47813932-28a47980-dd2b-11e8-8eaa-a76d2c6c3a94.PNG)
-------------------------------------------------------------------------------------------------------------------
Log For 0.0.5-7460:

[Log RPCS3 0.0.5-7460.zip](https://github.com/RPCS3/rpcs3/files/2536135/Log.RPCS3.0.0.5-7460.zip)

 ------------------------------------------------------------------------------------------------------------------
Screenshots With error in 0.0.5-7466

![capturar](https://user-images.githubusercontent.com/26087621/47814105-994b9600-dd2b-11e8-82c7-811d878dce93.PNG)
-------------------------------------------------------------------------------------------------------------------
![capturar1](https://user-images.githubusercontent.com/26087621/47814125-a49ec180-dd2b-11e8-80c4-db12378245c9.PNG)
-------------------------------------------------------------------------------------------------------------------
![capturar2](https://user-images.githubusercontent.com/26087621/47814150-b08a8380-dd2b-11e8-9891-ff4c6af43155.PNG)
-------------------------------------------------------------------------------------------------------------------
![capturar3](https://user-images.githubusercontent.com/26087621/47814169-bbddaf00-dd2b-11e8-9c0c-dd75d1b10a13.PNG)
-------------------------------------------------------------------------------------------------------------------
![capturar4](https://user-images.githubusercontent.com/26087621/47814194-c5ffad80-dd2b-11e8-9ae6-8b315e2cb36a.PNG)
-------------------------------------------------------------------------------------------------------------------
Log For 0.0.5-7466:
[Log RPCS3 0.0.5-7466.zip](https://github.com/RPCS3/rpcs3/files/2536126/Log.RPCS3.0.0.5-7466.zip)

**Comment by HerrHulaHoop** [comment]
That happens when you choose incorrect settings. Set Anisotropic filtering to auto and change resolution scaling threshold to 512 x 512. 

Also, this tracker isn't for getting support. Use our [discord](https://discord.me/RPCS3) for getting help running games.

**Comment by Asinin3** [comment]
Also, you should **never** disable Anisotropic Filtering, as it means RPCS3 won't allow games to even use their own inbuilt texture filtering and it can cause issues. Use Automatic or 16x for most games, but for Asura's Wrath you **need** to leave it on **Automatic** or it will create some visual issues.

**Comment by Luffykun007** [comment]
Ok Guys worked was my mistake thank you.
