### ISSUE TITLE
Haze [BLES00169]: in-game texts don't appear

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#5306]
There are no in-game texts ("Press START", menu text, ammo counts), but it's possible to start game in blind. Strict rendering mode and write color buffers don't help.
[Haze.zip](https://github.com/RPCS3/rpcs3/files/2545904/Haze.zip)
![haze](https://user-images.githubusercontent.com/14265316/47965494-198a3800-e059-11e8-8b2e-925580f7b842.png)
![haze2](https://user-images.githubusercontent.com/14265316/47965497-2149dc80-e059-11e8-866a-d0b46652b3a8.png)
![haze3](https://user-images.githubusercontent.com/14265316/47965500-2575fa00-e059-11e8-9ade-72cab6b6b5c8.png)

**Comment by elad335** [comment]
You need to attach a capture file and footage on how it looks on realhw for comparison. Theres a "RSX capture" buttom on the debugger, press it while the playing the start screen, on succesful capture the file would appear on in rpcs3/captures. upload it preferably as a compressed file.

**Comment by TotalCaesar659** [comment]
Here it it, I hope I did it right.
[BLES00169_capture.zip](https://github.com/RPCS3/rpcs3/files/2545931/BLES00169_capture.zip)

**Comment by Hopefullyidontgetbanned** [comment]
This is still present, btw

**Comment by jade010** [comment]
Works fine on latest master ( v0.0.6-8056 Alpha [2019-05-02] // #5901 (2b4da187) by Nekotekina ) for me.
![haze1](https://user-images.githubusercontent.com/36518512/57099865-b6364580-6d1d-11e9-9c1d-2d4da00e8da5.PNG)
![haze2](https://user-images.githubusercontent.com/36518512/57099866-b6cedc00-6d1d-11e9-94b0-a427fe84ab9d.PNG)
![haze3](https://user-images.githubusercontent.com/36518512/57099867-b6cedc00-6d1d-11e9-8e84-bca9b1a20ccd.PNG)

LOG: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3139558/RPCS3.log.gz)

**Comment by Zangetsu38** [comment]
ah it have issue, i have report in on discord before, so like i have said on discord, this game can get statut Playable now i think

**Comment by digitaldude555** [comment]
![Screenshot (3431)](https://user-images.githubusercontent.com/26138653/60396872-5efef680-9b4f-11e9-9318-548b785624f3.png)
seems this issue has been fixed for months please close.
