### ISSUE TITLE
RPCS3 wont open

### ISSUE THREAD

**Issue by persianmyth** [RPCS3/rpcs3#5307]
i extracted the files although the emulator does not has the avatar and when try to open it windows tell me this can't run on your PC
![capture](https://user-images.githubusercontent.com/44752461/47967765-2e26fa00-e072-11e8-84eb-27a809215f34.PNG)

![image](https://user-images.githubusercontent.com/44752461/47967806-83fba200-e072-11e8-8a26-c3a647fc473b.png)

**Comment by 13xforever** [comment]
Please read the [guildelines](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) for submitting an issue.
1. github issues are **NOT** for support questions, use discord or forums for that
2. you're using an unofficial build of an emulator, so you'll have to ask for support from the people who made it, **NOT** here

**Comment by elad335** [comment]
You are probably running 32-bit windows, rpcs3 only supports 64 bit.

**Comment by persianmyth** [comment]
> Please read the [guildelines](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) for submitting an issue.
> 
> 1. github issues are **NOT** for support questions, use discord or forums for that
> 2. you're using an unofficial build of an emulator, so you'll have to ask for support from the people who made it, **NOT** here

sorry i didn't know that
but i downloaded it from the official site

**Comment by persianmyth** [comment]
> You are probably running 32-bit windows, rpcs3 only supports 64 bit.

actually i have 64 bit windows

**Comment by RainbowCookie32** [comment]
> > Please read the [guildelines](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) for submitting an issue.
> > 
> > 1. github issues are **NOT** for support questions, use discord or forums for that
> > 2. you're using an unofficial build of an emulator, so you'll have to ask for support from the people who made it, **NOT** here
> 
> sorry i didn't know that
> but i downloaded it from the official site

The official site? Like rpcs3.net? Because that compressed file doesn't look to be from RPSC3's website, and it's an old build

**Comment by persianmyth** [comment]
> > > Please read the [guildelines](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) for submitting an issue.
> > > 
> > > 1. github issues are **NOT** for support questions, use discord or forums for that
> > > 2. you're using an unofficial build of an emulator, so you'll have to ask for support from the people who made it, **NOT** here
> > 
> > 
> > sorry i didn't know that
> > but i downloaded it from the official site
> 
> The official site? Like rpcs3.net? Because that compressed file doesn't look to be from RPSC3's website, and it's an old build

sorry for the Confucian i have tried both the latest version and it didn't work so i tried an older one from another site 
 
![capture](https://user-images.githubusercontent.com/44752461/47968099-1b162900-e076-11e8-9a26-a5383f2938f9.PNG)

**Comment by RainbowCookie32** [comment]
All your files are 0kb, something's wrong there. Try to update winrar

**Comment by persianmyth** [comment]
> All your files are 0kb, something's wrong there. Try to update winrar

it WORKED thanks man i really appreciate it
