### ISSUE TITLE
[BLJS10286] - Gundam Breaker 2 crash with WCB enabled

### ISSUE THREAD

**Issue by Kojikun1** [RPCS3/rpcs3#5319]
In the game Loading when WCB is enabled the emulator just Freeze and crash 
this starts after this https://github.com/RPCS3/rpcs3/pull/5314 PR this PR fix the sys_lwcond but 
the Gundam Breaker 2 needs WCB for the graphics Render corretly.

**Comment by benderscruffy** [comment]
i have not had any crashes or freezes so far with WCB enable
can be closed
![gundam1](https://user-images.githubusercontent.com/2696404/73112185-6309c000-3f48-11ea-9697-691b3ee54d14.PNG)
