### ISSUE TITLE
Soulcalibur 4 [BLUS30160] Hang - {Audio Thread} XAudio2Thread : too many buffers enqueued (33, pos=8354880)

### ISSUE THREAD

**Issue by tabnk** [RPCS3/rpcs3#5322]
Soulcalibur 4 [BLUS30160] crash during in games for both PPU LLVM+SPU ASMJIT and PPU LLVM+SPU LLVM.

Log:
·W 0:03:12.722333 {Audio Thread} XAudio2Thread : too many buffers enqueued (33, pos=8354880)

**Comment by RainbowCookie32** [comment]
Attach the actual log rather than a line copied from it
