### ISSUE TITLE
Regressions after #5302

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#5328]
Tracker for regressions introduced by https://github.com/RPCS3/rpcs3/pull/5302. Report any issues here and not in the PR itself.

Tagging the PR author @elad335

**Comment by MarioSonic2987** [comment]
_Crosspost from #5302 thread._

That PR breaks graphics in GTA V. For example, minimap's map isn't visible and there's overbright lighting.

![image](https://user-images.githubusercontent.com/20027681/48138197-0f0fae80-e2a4-11e8-88f1-69e483dc0883.png)
![image](https://user-images.githubusercontent.com/20027681/48138294-539b4a00-e2a4-11e8-8a55-4411dc57ec6b.png)

**Comment by elad335** [comment]
@questore @MarioSonic2987 can you post an RSX capture.

**Comment by MarioSonic2987** [comment]
@elad335 
**Before**:
![image](https://user-images.githubusercontent.com/20027681/48316257-8f564c80-e5e1-11e8-9ddb-97c5fc173bc1.png)
**After**:
![image](https://user-images.githubusercontent.com/20027681/48316260-98471e00-e5e1-11e8-99dd-17ab662dc12f.png)
[RSX Capture](https://github.com/RPCS3/rpcs3/files/2569628/NPEB01283_RSX_Capture.zip)

**Comment by kd-11** [comment]
Retest, should be fixed now.

**Comment by MarioSonic2987** [comment]
GTA V return to its previous state:
![image](https://user-images.githubusercontent.com/20027681/48317758-2aa5ec80-e5f7-11e8-95e0-9aeedc405f4d.png)
![image](https://user-images.githubusercontent.com/20027681/48317774-6ccf2e00-e5f7-11e8-95a1-136fbcfae389.png)

**Comment by questore** [comment]
Yes, Heavy Rain loading screen is back and fine.
