### ISSUE TITLE
Suggestion: Add a setting for saving mouse move adjustments.

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#5329]
Please, add in "Pads" tab or somewhere else - something, that will keep mouse move adjustment multiplier and deadzone same every time you enter the game, because it's so boring to adjust it every time you enter the game.

**Comment by Ghostotakoi** [comment]
yeah, should be very useful

**Comment by gidan80** [comment]
I'd rather suggest to make a costom pad/keyboard config for every game, just like how it works for the others custom configs (CPU, GPU, ...).

**Comment by Megamouse** [comment]
Ugh I hoped to ignore these settings for as long as possible

**Comment by gidan80** [comment]
I managed to implement something about custom pad/keyboard config. I'ts the first time i look into RPS3 code and i'm sure i'd have done something wrong about coding style or something else, but it works. If someone wants to give it a look it'd be great!
https://github.com/gidan80/rpcs3/tree/padConfig

**Comment by Megamouse** [comment]
@gidan80  I'll have a look. give me a few days.
Just letting you know that I have the stuff in this issue mostly implemented, so you dont need to worry about mouse settings.
