### ISSUE TITLE
Silent Hill Downpour crashes at a certain point

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [RPCS3/rpcs3#5339]
The game crashes when I am walking out of the prison with this error mesage:

![screenshot_20181114_025401](https://user-images.githubusercontent.com/29783425/48484840-e8abbf00-e81f-11e8-8a7f-38f047e35f0f.png)

**System specs:**
OS: Manjaro Linux KDE 18
GPU: AMD HD 8750M
CPU: Intel Core I5 4200M
Ram: 6 GB
Driver: Mesa 18.3 latest version.
RCPS3 version: v0.0.5-7496-0e0a82e5 ALPHA
PS3 Firmware version: 4.83

**RCPS3 configurations:**

![screenshot_20181114_145531](https://user-images.githubusercontent.com/29783425/48484746-a2566000-e81f-11e8-9ba7-82182da6c2f9.png)

![screenshot_20181114_145613](https://user-images.githubusercontent.com/29783425/48484757-a84c4100-e81f-11e8-95f2-7d505651b61e.png)

**Comment by ahmed-elsayed2017** [comment]
I played the game on Window mode instead of Fullscreen mode and it didn't crash like it used to be!

**Comment by ahmed-elsayed2017** [comment]
The game after while start to be so slow and I have to close it and open it again to fix performance lag.

Any tips?

**Comment by AniLeo** [comment]
This is not a support forum, if you're reporting a specific issue then do, otherwise if you just want general support go to the forums or our Discord Server's help channel.
