### ISSUE TITLE
Serious Sam 3 [NPUB31165] is having a serious problem.

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#5340]
A couple of months ago, Serious Sam 3 [NPUB31165] stopped working. It was just crashing right at start of first intro with 

F {rsx::thread} class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
On vulkan. (OpenGL and D3D12 are working normally)

And i didn't know what to do. I wasn't sending any reports, because i thought somebody will find it, and report himself, but that didn't happend.

Then, when i lowered resolution (to 720x576 and 720x480), it suddenly started to work.
After some time, i found that i can boot serious sam in lower resolution, and set the resolution scale to about 120% (More % = crash with same error), to play in normal quality.
But still, i want to play in 1280x720.

I don't really remember on which pr it started to happen, but by testing every build i found that the last build, serious sam can work on - is a https://github.com/RPCS3/rpcs3/pull/4769
Which means, that build https://github.com/RPCS3/rpcs3/pull/4752 - Is the build that caused serious sam 3 to stop working in 1280x720p

**Comment by Hasster1** [comment]
Oops, forgot about log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2581309/RPCS3.log)

**Comment by AniLeo** [comment]
Update your NVIDIA drivers to the latest version, install the [Vulkan SDK](https://vulkan.lunarg.com/sdk/home) and set "Debug Output" to true on config.yml. Then re-run the game and see if you get detailed API output regarding that error. If so, reupload a new log.

**Comment by Hasster1** [comment]
I've installed Vulkan SDK, downloaded latest NVIDIA drivers from NVIDIA GeForce Experience, and checked "Debug Output" on serious sam 3 in debug options.
Still crash.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2584945/RPCS3.log)

**Comment by Hasster1** [comment]
Crash at the same time, but this time in rpcs3's log window there is no error. Just crash.

**Comment by Hasster1** [comment]
Just this - 
E {rsx::thread} RSX: Blit request denied because the source region does not fit!

**Comment by kd-11** [comment]
That is not a crash message, just an error. Was there a crash box? Or what do you mean crashed? Did it close itself? Just saying it crashed is not very definitive.

**Comment by Hasster1** [comment]
On earlier versions of RPCS3 it was giving a pink error 
Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
Then SS3 was just freezing, and if you will try to stop it or close it - entire rpcs3 will completely freeze.
Right now it does the same thing, but without error.

**Comment by Emulator-Team-2** [comment]
@kd-11 
This game stopped working only on nvidia. 

The game hangs after loading the screen with:
`E {rsx::thread} RSX: Blit request denied because the source region does not fit!`

Works fine on amd [RX 570] with Vulkan:
![vk](https://user-images.githubusercontent.com/38318848/48570966-ea4fb280-e905-11e8-98a6-4f52b46ed5c3.png)
Vulkan: --> [RSX Capture](https://mega.nz/#!tYpz1Y6A!fAJCM788tiVEfb2xFe6r73PN5XRjyORkXekPzERu2Gs)

**Comment by Hasster1** [comment]
This problem has been fixed in some previous build. Now everything works perfectly in any resolution.
