### ISSUE TITLE
[Regression] Ridge Racer7 3D [NPUB30457] Game crashes in menus with SPU LLVM 

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5342]
SPU LLVM now crashes the game with a RSX semaphore error at the same point in the menus. Worked fine previously and the only means to fix the crackly audio. Same for xfloat on/off. 

No log (emu crash).

![2018-11-14 17_21_06-rpcs3 0 0 5-7497-0044eb44 alpha not responding](https://user-images.githubusercontent.com/20983844/48523547-bdca6680-e831-11e8-9b21-822ed30780f3.png)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by legend800** [comment]
Broken by this PR last week:  https://github.com/RPCS3/rpcs3/pull/5310

**Comment by RipleyTom** [comment]
That PR probably just revealed an underlying issue in spu llvm, it's not touching anything spu llvm related directly.

**Comment by legend800** [comment]
That's a shame. Hopefully Neko's upcoming SPU work addresses it. It was nice to finally have clean audio in RR7. 

@AniLeo Can you remove the 'need info' tag now please?

**Comment by legend800** [comment]
@AniLeo  Can you remove the "Need Information" tag?

@Nekotekina Any thoughts as to why this PR: https://github.com/RPCS3/rpcs3/pull/5310 prevents Ridge Racer 7 from being playable with SPU LLVM and throws a semaphore error?

![2018-12-22 15_38_50-window](https://user-images.githubusercontent.com/20983844/50379498-d3386a80-05ff-11e9-8c9e-dbfb28e134d3.png)

[rr7.zip](https://github.com/RPCS3/rpcs3/files/2705629/rr7.zip)

**Comment by RipleyTom** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/5353 , similar issue to catherine with spu threads getting stuck on a looping BR.
I rebased it if you want to test.

**Comment by legend800** [comment]
Confirmed, that PR fixes this issue. Thanks for recognizing that and doing a rebase. Good luck getting that merged soon.

**Comment by legend800** [comment]
Fixed by today's SPU changes checked in by @Nekotekina

**Comment by legend800** [comment]
Not sure if it regressed after or was never actually fixed by that PR, but the RSX semaphore error is still present when using SPU LLVM SAFE. When using MEGA, it's fine (same with ASMJit). 

Log:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2822454/RPCS3.zip)

**Comment by elad335** [comment]
fixed by #5749

**Comment by legend800** [comment]
Confirmed, closing.
