### ISSUE TITLE
Ridge Racer7 3D [NPUB30457] Missing/flickering bg objects/trees - Nvidia Only Issue

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5343]
Background objects and trees mostly don't appear or constantly flicker around the race course. 

Note: 
This is the last issue of any kind with this game.
Currently crashes upon stopping emulation or attempting to get a rsx capture (so no logs)

![2018-11-14 17_25_40-fps_ 59 98 _ vulkan _ 0 0 5-7497 _ ridge racer7 3d license ver full game npub](https://user-images.githubusercontent.com/20983844/48523831-ca02f380-e832-11e8-83c0-2cfb2f968685.png)

![2018-11-14 17_34_59- 21 new year special ridge racer 7 harborline 765 ta with bayonet - youtube](https://user-images.githubusercontent.com/20983844/48524070-a55b4b80-e833-11e8-82b7-687ef81c25ea.png)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by Emulator-Team-2** [comment]
@kd-11 
Only Nvidia has broken and flickering trees.

**[Nvidia]**
![bez tytulu1](https://user-images.githubusercontent.com/38318848/51340071-4bbf0980-1a8e-11e9-9632-1887b188e9ac.png)
[RSX Capture-Nvidia](https://mega.nz/#!AJJyAYJZ!xjeZLaky18XYCNm0-8MzkXvaLvasit6PshnH2e2OnCk)

**[AMD]**
![1](https://user-images.githubusercontent.com/38318848/51340111-62656080-1a8e-11e9-851a-450a0d5f175e.png)
[RSX Capture-AMD](https://mega.nz/#!BYIgEapD!Giu8b7s6Evks9ApMyJtytgRw61w4XpIGHzPIRXduehA)

(This broken color/shader on the car is a regression after rsx: Fbo fixes.)

**Comment by legend800** [comment]
@kd-11  Just an FYI, on AMD foliage renders perfectly. On nvidia though, it flickers/transparent.

**Comment by arcadee1977** [comment]
Same issue on Time crisis 4 stage2 (flickering trees)
![未标题-1](https://user-images.githubusercontent.com/47111657/54513429-62041b80-4992-11e9-8ddc-5753c3cd2813.jpg)

**Comment by Emulator-Team-2** [comment]
Only NVIDIA has broken and flickering trees.

[NVIDIA]
![1](https://user-images.githubusercontent.com/38318848/56164725-9b4f9b80-5fd1-11e9-884f-30bb493185eb.png)
[RSX Capture-NVIDIA](https://drive.google.com/file/d/16sJ3CPna4WMTK55juqsd-9lF3YjOR5kl/view?usp=sharing)

[AMD]
![2](https://user-images.githubusercontent.com/38318848/56164755-a86c8a80-5fd1-11e9-8169-f81e5f420a89.png)
[RSX Capture-AMD](https://drive.google.com/file/d/1Xefeqbz4MWhdEXUdL7KLMyCgAw09uI6R/view?usp=sharing)

**Comment by kd-11** [comment]
Fixed in [this build](https://ci.appveyor.com/project/kd-11/rpcs3/builds/23947642)

**Comment by legend800** [comment]
Beautiful!
![2019-04-18 08_27_53-Window](https://user-images.githubusercontent.com/20983844/56372739-694a5f00-61b4-11e9-83dc-7ca7337b1903.png)

Thanks so much kd-11! I'll close once in master.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/5860
