### ISSUE TITLE
Regression from #5298 

### ISSUE THREAD

**Issue by raveskirza** [RPCS3/rpcs3#5347]
Tekken Tag Tournament 2 (NPEB01140) save data gets corrupted since #5298 was merged.
The build before this merge does not corrupt the saves.

Attached logs from latest master and Last working build
[RPCS3.log_latest_master.gz](https://github.com/RPCS3/rpcs3/files/2587155/RPCS3.log_latest_master.gz)
[RPCS3.log_last_working.gz](https://github.com/RPCS3/rpcs3/files/2587156/RPCS3.log_last_working.gz)

**Comment by Nekotekina** [comment]
Please upload valid and corrupted save somewhere

**Comment by raveskirza** [comment]
@Neko Attached Save files one generated from Pr and other from the last working build.
[NPEB01140_AUTO - Corrupt.tar.gz](https://github.com/RPCS3/rpcs3/files/2591511/NPEB01140_AUTO.-.Corrupt.tar.gz)
[NPEB01140_AUTO.tar.gz](https://github.com/RPCS3/rpcs3/files/2591512/NPEB01140_AUTO.tar.gz)
[RPCS3.log - Corrupt.gz](https://github.com/RPCS3/rpcs3/files/2591513/RPCS3.log.-.Corrupt.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2591514/RPCS3.log.gz)

**Comment by Nekotekina** [comment]
Thanks, try new commit

**Comment by raveskirza** [comment]
Great! the new commit fixes the save data corruption.

**Comment by Nekotekina** [comment]
Merged in master.

**Comment by neko** [comment]
?
