### ISSUE TITLE
Feature request: Decrease the shader/texture cache accuracy to increase performance

### ISSUE THREAD

**Issue by Ghostotakoi** [RPCS3/rpcs3#5348]
Some others emulators have the chance to decrease the cache accuracy (At your own risk) to increase performance and decrease the compile time, example of this is Dolphin and Cemu both have this feature, so I was wondering if any way to do this in rpcs3.

**Dolphin**
![screenshot_20181114010622](https://user-images.githubusercontent.com/20958581/48600666-dc685480-e93a-11e8-8a7f-b91c9fbfaefa.png)

**Cemu**
![screenshot_20181114011025](https://user-images.githubusercontent.com/20958581/48600710-09b50280-e93b-11e8-9185-5e8218268a28.png)

**Comment by HexyFify** [comment]
I think rpcs3 devs want accuracy 
Even if it means sacrificing performance for a while

**Comment by kd-11** [comment]
Please just stop this. We already have cache accuracy options like "write color buffers". And no, you cannot change the emulated shader accuracy for performance,  rpcs3 is not gpu limited.
