### ISSUE TITLE
Gran Turismo 5 - Save file broken

### ISSUE THREAD

**Issue by jenci8888** [RPCS3/rpcs3#5350]
Version: RPCS3 0.0.5-7496-0e0a82e5 Alpha

Game: Gran Turismo 5 [BCES00569] (Other version the game, it should be same)
Issue: Save file doesn't work when emulator gets completely frozen. I have to delete save file to make run again. (I've tried the Neko's PR "Time fixes" that doesn't solve it.)

This might be fix workaround.
![image](https://user-images.githubusercontent.com/40495799/50686689-a4b68880-101e-11e9-9b78-d7f1407727cc.png)

Hardware specs: i5-4690k @ 3.5ghz, ddr3 8gb 2400mhz, GTX 1050Ti 4GB.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2589886/RPCS3.log.gz)

[RPCS3_save broken.zip](https://github.com/RPCS3/rpcs3/files/2589932/RPCS3_save.broken.zip)

**Comment by mignolo4** [comment]
To me it happens systematically.
I can only play the first time I load the game (even if it doesn't freeze and I close the emulator regularly).

Tested on 30th December 2018 with RPCS3 v0.0.5-7650-0554ff6f (kd-11 branch with a lot of work on GT Series)

**Comment by jenci8888** [comment]
Fixed by elad335.
![image](https://user-images.githubusercontent.com/40495799/52931300-2a329580-334c-11e9-91b2-42c399aa99b8.png)
