### ISSUE TITLE
BLES00932 - Demon's Souls RPCS3 Crash during cutscenes

### ISSUE THREAD

**Issue by Dani1977** [RPCS3/rpcs3#5355]
Hi,
since version 0.0.5-7490 RPCS3 crash during every cutscene. 

I can only attach a partial log as the RPCS3 stops badly.

Regards

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2601581/RPCS3.zip)

**Comment by Dani1977** [comment]
since 0.0.5-7537 crash on intro cutscene
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2636353/RPCS3.zip)

**Comment by AniLeo** [comment]
Retest with the latest build

**Comment by Dani1977** [comment]
hi,
with v0.0.5-7645 no more crash, i do training, boletaria 1-1 and 1-2. 
regards
