### ISSUE TITLE
Persona 5 certain cut scene pauses at exact place every time

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5356]
RPCS3 don't freeze and you can just press start when that happens to skip the cut scene.
![2018-11-19_224731](https://user-images.githubusercontent.com/5032540/48832815-f8705980-ed71-11e8-918f-59e70f1de000.jpg)
[Log.zip](https://github.com/RPCS3/rpcs3/files/2603686/Log.zip)
[Save.zip](https://github.com/RPCS3/rpcs3/files/2603687/Save.zip)

About the save,it's the day before the cutscene.
I tried without the 60fps patch,with spu interpreter,setting the fps limit to different modes,and with no shaders and some older revs but no change,it's like it's pausing there(this is the first cut scene where it happens)

**Comment by RipleyTom** [comment]
Currently playing persona 5 and I just watched that cutscene, worked just fine for me.
Did you check your dump?

**Comment by vsub** [comment]
Hmm,seems to be a bad dump,sorry
