### ISSUE TITLE
Need for better icons

### ISSUE THREAD

**Issue by gidan80** [RPCS3/rpcs3#5358]
Like the title said, we need better icons, in particular custom config and pad config icon.
The icons need to always have good contrast, even when placed on top of another image.
I'll attach some samples (same as stock icons, but with white borders).

![combo_bordered](https://user-images.githubusercontent.com/14052998/48859925-b66e0480-edbf-11e8-8776-ac4cb72b1cf3.png)
![controllers_bordered](https://user-images.githubusercontent.com/14052998/48859926-b66e0480-edbf-11e8-89f3-d606ab3c5732.png)
![custom_config_bordered](https://user-images.githubusercontent.com/14052998/48859927-b7069b00-edbf-11e8-8c55-b4aafef7d6bd.png)

**Comment by niko1point0** [comment]
There have been several UI improvements over the last 6 months. Is this issue still relevant?
