### ISSUE TITLE
Metro Last Light: Fails at launch

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#5369]
Metro Last Light [BLES01867]

The game does not launch, it fails with the error message:

{PPU[0x1000000] Thread (main_thread) [0x009c72d4]} MEM: Access violation writing location 0x2dc

Specs: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz | 8 Threads | GeForce GTX 1060 6GB
Configurations: Default
Version: rpcs3-v0.0.5-7510-7f1cbb11_win64

[RPCS3.tar.gz](https://github.com/RPCS3/rpcs3/files/2612236/RPCS3.tar.gz)

**Comment by Xcedf** [comment]
I think this is a regression issue, cause it worked on earlier versions, don't know which version caused the bug

**Comment by AniLeo** [comment]
```
·W 0:00:07.835443 {PPU[0x1000000] Thread (main_thread) [0x009c72d0]} sys_fs: sys_fs_open(path=“/dev_bdvd/PS3_GAME/USRDIR/sounds.ru.vfs0”, flags=0, fd=*0xd002efc0, mode=0, arg=*0x0, size=0x0)
·E 0:00:07.835493 {PPU[0x1000000] Thread (main_thread) [0x009c72d0]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/sounds.ru.vfs0” [1]
·F 0:00:07.835509 {PPU[0x1000000] Thread (main_thread) [0x009c72d4]} MEM: Access violation writing location 0x2dc
```

Check if your copy is properly dumped, or someone else who has a proper dump of this game please check if the file exists

**Comment by digitaldude555** [comment]
https://forums.rpcs3.net/thread-182792.html its working now as shown in the forum thread.
