### ISSUE TITLE
Ridge Racer 7 ( all versions ) -  MEM: Access violation reading location 0x20

### ISSUE THREAD

**Issue by arcadesfan** [RPCS3/rpcs3#5371]
CPU: Intel Dual Core E5700 3 Ghz
GPU: Nvidia GeForce GT 640
RAM: 4 GB

RPCS3 v0.0.5-7510-7f1cbb11 Alpha
PPU: LLVM Recompiler
SPU: ASMJIT
Renderer: Vulkan

Ridge Racer 7 Playable Demo ( NPUB90006 )

I get a MEM access violation error on Ridge Racer 7 Demo and also every version of Ridge Racer 7 ( the full game and the Playable Demos, both US or European versions ). This is happening on all builds from at least the last six months. Tried with all kind of configurations, both Vulkan and OpenGL.
This issue doesn´t happen on older builds from many months ago ( game has other issues on the older builds, but on some of them ( using a special configuration ) at least I can reach the intro or even the menu in a few cases ( then game freezes during the intro or other times on the menu while selecting a car for example ).

The reason I post this issue here instead of in the Support Forum, is because it can take a lot of time to be read there, maybe the devs can be aware of the issue earlier and can fix it.

The first time I run the game, it gets stuck on this error:

U {PPU[0x1000043] Thread (CPamfDemuxer::ReadThread) [0x00507d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000043] Thread (CPamfDemuxer::ReadThread) [0x0047ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000043] Thread (CPamfDemuxer::ReadThread) [0x0047ff0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]

When I run it for the second time the emulator finally stops and crashes asking to be closed. I finally get this error ( in purple color ):

F {PPU[0x1000006] Thread (TTFontRender Thread) [0x0027f960]} MEM: Access violation reading location 0x20

The link to download the Log is the following:

<a href="https://drive.google.com/file/d/1Ab6EwODwJnXUoslkLh4mDc4ci79A2BxN/view?usp=sharing">rpcs3-v0.0.5-7510-LOG.7z</a>

**Comment by legend800** [comment]
Is this still happening? I've never seen this and test the game all the time. 

Only issues remaining with game are broken on SPU LLVM (safe) and tree flicker (nvidia).

**Comment by arcadesfan** [comment]
I wouldn´t mind flickering trees, I would be happy just to see the game running. 
By the way, what PC do you have ? Is it core i7 ? can you give me the specs you have ? I´m planning to buy an intel core i7, but I want to be sure to buy the right model so as to run this game. Thanks in advance !

**Comment by legend800** [comment]
Please close this issue then as the game runs fine for others and it doesn't sounds like a legitimate issue.
