### ISSUE TITLE
Not an important, but still a suggestion...

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#5373]
I've just thought... What makes this emualtor great, even on development state? BUGS!
When i booted GTA SA on this emulator, i have laughed so hard... Just by looking at that flat CJ i'm smiling...
That's why i think about this thing:

Fun menu.
The menu, that will diable some fixes, like piss filter, wrong colors or bad models/textures.
Why? Because it's fun.
Didn't you ever had a fun, just by looking at glitches?

**Comment by elad335** [comment]
One can always create his own hacked builds with intentional bugs, its an open souce project, you can do whatever you want with it. but master won't ever have intentional bugs. Please close the issue.
