### ISSUE TITLE
Inconsistent Home/End key treatment in the game list

### ISSUE THREAD

**Issue by 13xforever** [RPCS3/rpcs3#5383]
Current behavior
-----------------
When the game library is in the List view mode, <kbd>Home</kbd> and <kbd>End</kbd> keyboard buttons do nothing, whereas <kbd>Page Up</kbd> / <kbd>Page Down</kbd> behave as expected.

When it's in the Grid view mode, <kbd>Home</kbd> and <kbd>End</kbd> move selection to the beginning / end of the current row.

In both modes <kbd>Ctrl</kbd>+<kbd>Home</kbd> moves selection to the first item, and <kbd>Ctrl</kbd>+<kbd>End</kbd> does nothing.

Expected behavior
------------------
In List view mode: <kbd>Home</kbd>/<kbd>Ctrl</kbd>+<kbd>Home</kbd> should move to the first item, <kbd>End</kbd>/<kbd>Ctrl</kbd>+<kbd>End</kbd> should move to the last item in the list.

In Grid view: <kbd>Home</kbd>/<kbd>End</kbd> should move to the first/last element of the row, <kbd>Ctrl</kbd>+<kbd>Home</kbd>/<kbd>Ctrl</kbd>+<kbd>End</kbd> should move to the first/last element of the library.

**Comment by Megamouse** [comment]
you don't understand. those are both tables and not lists.
so home/end moves horizontally and not vertically. (working fine on both modes here)

also.. ctrl+End works as it should in both modes. The reason why it doesn't work sometimes in grid mode is that the last row has filler elements. if you select one of those fillers by using any of those navigations you get a deselection (as if you were clicking empty space with your mouse)

**Comment by 13xforever** [comment]
That might be the technical explanation why it works now as it does, but from the user perspective, UI doesn't behave as in other similar situations.

Also <kbd>Ctrl</kbd>+<kbd>End</kbd> doesn't work for me at all for some reason, in both modes. And on the topic of the last row in grid mode, if your row is not full, <kbd>End</kbd> doesn't work, which is also inconsistent.

**Comment by Megamouse** [comment]
~~use a mouse~~ 🙄

**Comment by Megamouse** [comment]
Maybe I can take a look sometime next week. But it really sounds like an issue only few people would even notice

**Comment by Megamouse** [comment]
In case you are interested, this should go into Qt 5.12.1 or Qt 5.12.2.
Here's the commit that presumably will fix it:
https://codereview.qt-project.org/#/c/247710/3//ALL

**Comment by Megamouse** [comment]
can you please retest?

**Comment by 13xforever** [comment]
Current behavior:
- List mode:
  - 🤔 `Home`/`End` move focus to the beginning/end of current row
  - ✅ `Ctrl`+`Home` moves focus to the beginning of the first row
  - 🤔 `Ctrl`+`End` moves selection to the end of the last row
  -  ✅ `PgUp`/`PgDn` page as expected
  - ❌ `Ctrl`+`PgUp`/`Ctrl`+`PgDn` work the same way as without modifiers, instead of moving focus to the first/last row

**Comment by Megamouse** [comment]
since this is a Qt issue i think you should rather open an issue there with a test case and close this here

**Comment by 13xforever** [comment]
😔
