### ISSUE TITLE
Rayman Legends: Menu background image flicker

### ISSUE THREAD

**Issue by jcapsule** [RPCS3/rpcs3#5394]
Rayman Legends [NPUB31218]

In the game menu is shown the flickering, between:
![capture1](https://user-images.githubusercontent.com/15172818/49408034-9ee53300-f752-11e8-9884-38beeaf6432e.png)

and

![capture2](https://user-images.githubusercontent.com/15172818/49408028-9856bb80-f752-11e8-927f-c4e4bd7ee1b1.png)

Specs: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz | 8 Threads | GeForce GTX 1060 6GB
Configurations: Frame Limit: Auto

Version: rpcs3-v0.0.5-7550-32059bfa_win64
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2641659/RPCS3.log.gz)

**Comment by legend800** [comment]
Dup. Logged here:  https://github.com/RPCS3/rpcs3/issues/4412

Not just menu, it's in game gfx flickering as well. Game is unplayable in current state. 

@kd-11 This game regressed over a year ago by:  https://github.com/RPCS3/rpcs3/pull/3772 
Any update on a fix?

**Comment by ruthan** [comment]
Its very old bug.

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/5427

**Comment by Emulator-Team-2** [comment]
Fixed by #5427

**Comment by kd-11** [comment]
Closing as fixed
