### ISSUE TITLE
Kung Fu Rabbit: Bad image size

### ISSUE THREAD

**Issue by jcapsule** [RPCS3/rpcs3#5395]
Kung Fu Rabbit [NPUB31359]

At the start of the game, its shows the image:

![capture1](https://user-images.githubusercontent.com/15172818/49408566-b9201080-f754-11e8-8898-2591a069d248.png)

With the error: 
{rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed

Specs: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz | 8 Threads | GeForce GTX 1060 6GB
Configurations: Frame Limit: Auto

Version: rpcs3-v0.0.5-7550-32059bfa_win64
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2641698/RPCS3.log.gz)

**Comment by elad335** [comment]
that aint an error, more like misleading logging, please close the issue.

**Comment by RainbowCookie32** [comment]
Retest using the settings from the Playable report just in case https://forums.rpcs3.net/thread-197938.html
