### ISSUE TITLE
Regression: Castlevania Harmony of Despair.

### ISSUE THREAD

**Issue by blackman91** [RPCS3/rpcs3#5401]
Using LLVM recompiler the game gets stuck in this screen forever and won't start:
![rpcbug2](https://user-images.githubusercontent.com/6578180/49490411-8b4ed080-f815-11e8-80a2-750326c0acbe.png)

It runs with interpreter but it is a lot slower and it used to run on previous builds with llvm. Using latest RPCS3 build form the website on Windows 10. To reproduce this just try to run the game with default settings and after pressing start in the title screen you will get the bug.

**Comment by blackman91** [comment]
Tested random older build 0.0.5-7454-eba2216c and it doesn't have this bug.

**Comment by Asinin3** [comment]
Missing log file and information on when it actually regressed.

**Comment by blackman91** [comment]
I managed to fix it but don't really know what setting did it, with llvm I get 80 fps instead of 30, I'll keep testing, dlc characters still make the game crash but that is another issue.
