### ISSUE TITLE
Half-Life 2 Issues

### ISSUE THREAD

**Issue by QuaiGoner** [RPCS3/rpcs3#5402]
Its strange as i havent seen this game on compatibility webpage on the site, but game plays pretty good overall, decent framerate on my iGPU (R2400G+Vega 11) 30 fps all the time. But emulator hangs as soon as i try to save the game in the console slot (in-game quicksave function is working perfectle). Also some issues with the graphics:
Broken reflections
![half life reflectionspng](https://user-images.githubusercontent.com/41058180/49500237-c519e880-f8a2-11e8-9405-10d37b4b0cc8.PNG)
Strange white strips here on the edges of textures or models.
![default](https://user-images.githubusercontent.com/41058180/49500271-e11d8a00-f8a2-11e8-8014-8a766733df43.PNG)
![hi](https://user-images.githubusercontent.com/41058180/49500305-f7c3e100-f8a2-11e8-9937-d351a3fad85d.PNG)
Characters shadows is just squares
![iohjhoij](https://user-images.githubusercontent.com/41058180/49500290-eed30f80-f8a2-11e8-9c36-5b4a170bd4ad.PNG)

Also there is strange bug with the gamepad. It can randomly get your stick on always down position or always up etc. Helps unplugging and plugging gamepad again 

Renderer: Vulkan
Block Size: Mega
CPU: ASMJIT
Host: Ryzen 2400g + Vega11 APU, latest drivers, Windows 10
Everything tested on latest master

**Comment by MSuih** [comment]
Provide RSX captures for at least some of the visual glitches and a log file for the save crash.

**Comment by QuaiGoner** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2647907/RPCS3.log)
That log file is the right one for the saving issues? About RSX captures, i am not sure how to make one

**Comment by 13xforever** [comment]
Please use forums for compatibility teports in the future. Read [guidelines first](https://forums.rpcs3.net/thread-196671.html).


Half-Life is not in the list because it was part of the Orange Box only on consoles.
[EU](https://forums.rpcs3.net/thread-196916.html), [US](https://forums.rpcs3.net/thread-181310.html).

**Comment by MSuih** [comment]
I can't check the details right now, but you need to open debugger (View -> Show Debugger or something like that). After it's open, start the game and play it untill you have one of the glitches visible on screen. Once that happens, press the RSX capture button on debugger, wait untill it saves the capture (and either resume emulation or close the emulator). A capture file should be created in the capture folder.

You can view the captures to double check that they were done successfully, there is a menu item (Open RSX capture) for it. Once you're satisfied, compress them into a .zip/.rar/.7z file and upload them to f.ex. megaupload or google drive and share the link here.

**Comment by digitaldude555** [comment]
Any update its been a year.

**Comment by Shoegzer** [comment]
Seeing a similar issue here, with 0.0.8-9534.  Game lcoks up at random intervals.  Are you seeing this too with a recent build, or just when you save?

**Comment by Realmantik** [comment]
I have not noticed any graphics issue on RPCS3 v0.0.12-10960-52260766 build.
![rpcs3_2020_10_01_12_18_03_445](https://user-images.githubusercontent.com/22906342/94794943-5138c080-03e5-11eb-9143-10744f147275.png)
![rpcs3_2020_10_01_12_21_38_997](https://user-images.githubusercontent.com/22906342/94794946-53028400-03e5-11eb-9155-280668ba17bd.png)
I played ~1 hour without crash or lock.
So I think this ticket must be closed.

**Comment by AniLeo** [comment]
Closing as reported fixed, game compatibility reports should go on our forums either way
