### ISSUE TITLE
Support for Dualshock 4 under DS4Windows

### ISSUE THREAD

**Issue by vpontin** [RPCS3/rpcs3#5403]
Currently, under Gamepads settings any Dualshock 4 connected using @Ryochan7 's [DS4Windows](https://github.com/Ryochan7/DS4Windows) fork will only be detected under Xinput devices, and not in the dedicated Dualshock 4 (which i presume only works for SCP package).

Yeah, i know this would be a very low-priority request, but why not? If rpcs3 can detect a Dualshock 4 installed with SCP, detecting DS4Windows would be good too, mainly to expose features like Gyro (currently DS4W serves via an UDP implementation), touch, any extra buttons and actions not supported under "vanilla" Xinput specification.

Anyway thanks in advance for reading this ticket!

**Comment by vpontin** [comment]
Screenshot showing the issue:
![image](https://user-images.githubusercontent.com/3485505/49581903-8df71600-f93a-11e8-99fe-a8870371919c.png)

For reference, i'm using DS4W backed by Vigem driver.

**Comment by RipleyTom** [comment]
DS4Windows exists for things that don't natively support the DS4 to pass it as a xinput.
Either use it as an xinput device with DS4Windows or use our native handler.

**Comment by vpontin** [comment]
And what about support for Gyro via UDP (provided by DS4W) just like other emulators like cemu did? Good for sixaxis emulation.

**Comment by isJuhn** [comment]
We already support sixaxis with ds4 through our native handler

**Comment by MSuih** [comment]
Just set the input handler to Dualshock 4, and the emulator will automatically use the motion control features in it. No futher tweaks are required.

**Comment by vpontin** [comment]
@MSuih but as i said in OP selecting Dualshock 4 the device selection is disabled (see screenshot)

**Comment by AniLeo** [comment]
Probably because 3rd party hooks are interfering. Disabled them and try again.

**Comment by vpontin** [comment]
Meh, i need to talk with @Ryochan7 on DS4Windows repo about how to temporarially disable DS4W, because i cant connect with the controller while DS4W is off (perharps vigem or hidguardian are blocking the controller somehow).

Anyway thanks for the help.

**Comment by Ryochan7** [comment]
I would guess that exclusive mode is active either from DS4Windows or due to using HidGuardian. One note should be made that if you are using a Bluetooth connection, the original DirectInput controller would be visible to other programs in Shared Mode but it would be seen as a dead controller. You would have to reconnect the controller while DS4Windows is not running in order for other programs to use it.

**Comment by vpontin** [comment]
Thanks @Ryochan7 for the explanation!
