### ISSUE TITLE
tag_framebuffer causes FIFO corruption in a few games

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#5406]
Seen in Skate 3 and NFS most wanted
the sympthoms are similar: You will see semaphore timeouts and errors about fifo call executed inside a subroutine.
In skate this causes a massive slowdown, in NFS this causes a freeze.

[NFS Most wanted.log.gz](https://github.com/RPCS3/rpcs3/files/2658382/RPCS3.6.log.gz)
[Skate 3 Demo.log.gz](https://github.com/RPCS3/rpcs3/files/2658448/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Probably JStars is also affected

**Comment by kd-11** [comment]
Potentially fixed by [this commit](https://github.com/kd-11/rpcs3/commit/7216a7d51957048b6b199bf9fab18d55c0efcdd6). Test build [here](https://ci.appveyor.com/project/kd-11/rpcs3/builds/20864586)

**Comment by MSuih** [comment]
In Skate 3, that build fixes the <1 FPS issue when entering some missions and no longer has infinite load screen when entering skater edit screen.

**Comment by Emulator-Team-2** [comment]
This commit fixes regression in "Dragon Ball Z: Battle of Z" after #4611.
![1](https://user-images.githubusercontent.com/38318848/49684648-e06d3980-fad6-11e8-86c2-07ff8fd393f8.png)

**Comment by legend800** [comment]
Yep, Captain America just started getting this recently.

**Comment by legend800** [comment]
Wipeout HD now freezes with a fifo error too.

**Comment by elad335** [comment]
@legend800 framebuffer tagging issue is a very old regression, the issues you're reporting are newer if I understand you right.
its unrelated to this issue. may want to try #5404 as it fixes a few fifo regressions.

**Comment by elad335** [comment]
Lego indiana jones also affected by this.

**Comment by Aurorans** [comment]
E {RSX [0x00a4000]} RSX: FIFO error: possible desync event (last cmd = 0x3eb645a7)
E {RSX [0x003c0d0]} RSX: FIFO: CALL found inside a subroutine. Discarding subroutine
E {RSX [0x001c000]} RSX: FIFO: CALL found inside a subroutine. Discarding subroutine

Can confirm this is happening today with current update in NCAA football 13, causing gpu freezing, but the audio still plays and the game still plays without the picture on the screen.
