### ISSUE TITLE
[Feature request] Batch processing for all entries 

### ISSUE THREAD

**Issue by goedzo** [RPCS3/rpcs3#5407]
I would like to have a Batch menu under file, that allows to execute a tasks for all entries in the game list. This would save a lot of clicking and waiting when long running tasks need to be executed for all games in a big library.

My suggestion is to have the following:
File->
    For all entries ->
-                 Create PPU Cache
-                 Compile PPU modules
-                 Remove Entry
-                 Remove Completely
-                 Remove Custom Configuration
-                 Remove Shaders Cache
-                 Remove PPU Cache
-                 Remove SPU Cache

**Comment by scribam** [comment]
@goedzo Try the latest build. You should have some batch operations available if you go into "File" > "All Titles".

**Comment by goedzo** [comment]
@scribam 

Cool! Did not see it but like it! Will test it out.

**Comment by goedzo** [comment]
Well I tested it, but I am missing the option: "Compile PPU modules".

**Comment by AniLeo** [comment]
Implemented on current builds, closing as solved
