### ISSUE TITLE
Weird issue in Grid View(changing the game name)

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5409]
I notest this by accident
Is this some kind of work in progress feature or a bug?

1.Switch to grid view
2.Select any game
3.Start typing...the game image will be changed to text area in which you can change the game name

To apply the name,you have to click somewhere to deselect the game and change the name BUT...
After restarting rpcs3,switching view modes or just refreshing,the name is restored to the original one and this happens only in grid view

**Comment by Megamouse** [comment]
lmao i never noticed.
