### ISSUE TITLE
Regression from #5414

### ISSUE THREAD

**Issue by TristisOris** [RPCS3/rpcs3#5415]
after update to current build, game and rpcs3 hangs, when trying to save game.

F {PPU[0x100001c] Thread (xrd664_auto_save) [0x00ad8e20]} class std::runtime_error thrown: Failed to create directory D:/Games/RPCS3/hdd0/home/00000001/savedata/../.working_NPUB31848-00--001--/ (Access violation)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2668339/RPCS3.zip)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2668334/RPCS3.log.gz)

**Comment by TristisOris** [comment]
same for 0.0.5-7566.
works in 0.0.5-7564.

**Comment by SunFlea** [comment]
Seems to be an issue with [this commit](https://github.com/RPCS3/rpcs3/pull/5414/files).

**Comment by TristisOris** [comment]
yep, because it's the only one commit in this build)

**Comment by TristisOris** [comment]
all works in v0.0.5-7623.
