### ISSUE TITLE
Hard crash when closing RPCS3 with an active running game

### ISSUE THREAD

**Issue by myhaksown** [RPCS3/rpcs3#5420]
Hello!

I've been running flawlessly until I hit the X to close a game I was emulating.  An error was immediately thrown.

[Screenshots of error message, RPCS3 settings, and a copy of my logs](https://github.com/RPCS3/rpcs3/files/2674700/RPCS3.zip)

**Error**
Unhandled Win32 exception 0xC0000005.
Segfault writing location 00007ff8c9d42cc0 at 0007ff8c9d42cc0.
Instruction address: 00007ff8c9d42cc0.
RPCS3 image base: 00000000000100000.

**PC Specs**
Windows 10 Pro 64bit
Intel Core i5 - 8600
8GB 2400 DDR4 RAM (4GBx2)
Nvidia GTX 1080 Founders (Driver Version 417.22) 
RPCS3 Version 0.0.5-7576-76f94940 Alpha

**Game**
Hatsune Miku Project Diva F (NPUB31241)

**Comment by bevanweiss** [comment]
@myhaksown lots has changed in rpcs3 since you originally raised the issue.
Could you please re-test and advise if this is still a problem for you?
If the issue has gone away, if you could close this issue it would be greatly appreciated.
Thanks.

**Comment by dio-gh** [comment]
This is indeed like the most freaking random ticket ever, this is an issue that can haplen with any game. It became even more common once neko switched to a no exceptions model. So it kind of still holds true probably, but is also a duplicate with other tickets.

**Comment by bevanweiss** [comment]
I think this ticket should be closed if we won't be getting an updated log (from the OP).
The emulator will have changed so much since 2018... so even if it still crashes sometimes now, it might not be for the same reasons as this issue was raised on.

**Comment by jeremybris** [comment]
Fixed by [#9773](https://github.com/RPCS3/rpcs3/pull/9773) ?

**Comment by Megamouse** [comment]
closing as this doesn't seem to go anywhere
