### ISSUE TITLE
Regression: Guilty Gear XRD Rev2 freezes after build 0.0.5-7576 (#5276)

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#5421]
While in a battle, the game has some random freezes, and the entire emulator hangs. This happens since build 0.0.5-7576 (PR #5276)

Log attached:

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2677141/RPCS3.zip)

**Comment by LuismaSP89** [comment]
Update: The problem persists, three logs attached:


[RPCS3 log 1.zip](https://github.com/RPCS3/rpcs3/files/2777214/RPCS3.log.1.zip)
[RPCS3 log 2.zip](https://github.com/RPCS3/rpcs3/files/2777215/RPCS3.log.2.zip)
[RPCS3 log 3.zip](https://github.com/RPCS3/rpcs3/files/2777213/RPCS3.log.3.zip)

**Comment by AniLeo** [comment]
Needs retesting with latest build

**Comment by LuismaSP89** [comment]
@Anyleo I think now it works, closing.

Thanks.
