### ISSUE TITLE
Alien Isolation [BLES01697] - broken lighting (OpenGL/Vulkan)

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#5422]
The problem is:
a) weird color gamma and
b) light sources works on a very short distances 

WCB option seems uneffective.
P.S. USM movies are not currently supported by emulator, so they should be deleted from game folder in order to start playthrough.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2679242/RPCS3.log.gz)
![1590](https://user-images.githubusercontent.com/6324523/49992758-62a9a200-ff9e-11e8-8fab-0393b9f2883c.png)
![1591](https://user-images.githubusercontent.com/6324523/49992759-62a9a200-ff9e-11e8-9486-bf5cf958769d.png)
![1592](https://user-images.githubusercontent.com/6324523/49992760-62a9a200-ff9e-11e8-841e-c6dc0edfb94f.png)
![1594](https://user-images.githubusercontent.com/6324523/49992761-62a9a200-ff9e-11e8-8fdc-45e382a06d0b.png)

**Comment by RainbowCookie32** [comment]
Except for the videos, the game is working correctly on latest master

**Comment by kd-11** [comment]
Closing as fixed.
