### ISSUE TITLE
Pre-rendered scene causing freeze KHRe:CoM(BLUS31212)

### ISSUE THREAD

**Issue by Alelachis** [RPCS3/rpcs3#5429]
Hi there! I found an error by passing the first world in Re:Chain of Memories(BLUS31212), I got into a pre-rendered scene and got a stop in the scene(I could skip scene and save safely, the system didn't freeze). I checked the logs and it says repeatedly:

E {PPU[0x100001a] Thread (_libsail-mp4) [0x009e1174]} LDR: EDAT: Block at offset 0x37ce020 has invalid hash!
E {PPU[0x100001a] Thread (_libsail-mp4) [0x009e1174]} LDR: Error Decrypting data

Tried Vulkan and OpenGL both with recommended settings from rpcs3's wiki.
Thank you a lot. Regards
![imagen](https://user-images.githubusercontent.com/45594859/50057275-6721b680-0168-11e9-89a3-153c2a1105b5.png)

**Comment by AniLeo** [comment]
This is actually a duplicate, I remembered this being reported back then: #3732

Closing as duplicate, please post your input on the mentioned issue
