### ISSUE TITLE
GUI GPU config resolution scale, percent reference incorrect

### ISSUE THREAD

**Issue by Arturbc** [RPCS3/rpcs3#5431]
Hello guys,

In settings of GPU, the resolution reference about scale selected is incorrect calculate. If select 225% as scale the resolution is calculated as (2880x1620), but the correct is (1920x1080), if this 225% is (1280x720)*2.25.

Note: (1280x720)*N is not equal (1280*Nx720*N).

Thanks.

**Comment by elad335** [comment]
I see from where the confusion is coming from, the percentage is about the scale of each axis, not the total pixel count.

**Comment by MSuih** [comment]
Yes, exactly. The end result is 1280 * 2,25 * 720 * 2,25, which can be represented as 1280 * 720 * 5,0625.

And your note is wrong, they both result in 4665600 pixels so they're equal, just different representations.

**Comment by Arturbc** [comment]
Ah, ok elad335.

In my mind this scale is equal total of pixels image.

Sorry by this.

Thanks again.

**Comment by elad335** [comment]
Close the issue then.

**Comment by Arturbc** [comment]
Ok.
