### ISSUE TITLE
Skate 3 fatal error

### ISSUE THREAD

**Issue by RaneyDay5** [RPCS3/rpcs3#5432]
![lkl](https://user-images.githubusercontent.com/45475828/50127071-863e4800-023d-11e9-95ed-b9d4ef968bd2.PNG)

Running skate 3
windows 10
copied my config file from https://www.reddit.com/r/rpcs3/comments/8gmfxu/i_could_get_skate_3_running_very_playable_on_a_i3/
trying to get it running smooth

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
