### ISSUE TITLE
Move ~/.config/rpcs3/.../cache to ~/.cache/rpcs3/...

### ISSUE THREAD

**Issue by mxnemu** [RPCS3/rpcs3#5438]
Hello, it would be nice for cache data to not be in ~/.config.
The problem is that a lot of people set up scripts to backup ~/.config, and for rpcs3 this will also backup a bunch of probably reproducible cache data they won't need.

Some relevant code:
https://github.com/RPCS3/rpcs3/blob/ae85c40a0aa10813780ddd3b1d6fd6f58773f30d/rpcs3/Emu/System.cpp#L294
Also:
https://github.com/RPCS3/rpcs3/blob/ae85c40a0aa10813780ddd3b1d6fd6f58773f30d/Utilities/File.h#L485

Relevant spec:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Thank you for this great project.

**Comment by Nekotekina** [comment]
I'm working on it

**Comment by AniLeo** [comment]
Closing as implemented
