### ISSUE TITLE
Linux: wrong permissions on RPCS3.log.gz

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#5442]
Archlinux.
In ~/.config/rpcs3, the permissions are:
1) RPCS3.log: 0644 (correct)
2) RPCS3.log.gz: 0000 (incorrect)
So, I can't copy,... the compressed file (until I changemod it).
It should be 0644 too

**Comment by AniLeo** [comment]
Are you sure that when rpcs3 is completely closed the .log.gz is `0000`?
It's intended behavior for the .log.gz to be locked during runtime.

**Comment by MSuih** [comment]
If RPCS3 crashes, the permission might remain as 000. This doesn't really matter though as the file is corrupted at that point. On Windows the corrupted log would get automatically deleted but AFAIK this isn't possible to implement on Linux.

**Comment by toccata10** [comment]
Seems ok now. So I'm closing it.
