### ISSUE TITLE
Does Thread Scheduler even working?

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#5447]
RPCS3 v0.0.5-7593-b5cbe02f Alpha | HEAD (But i think it was even before)
GPU - NVIDIA GeForce 840M
CPU - Inter Core i5-4210U CPU @ 1.70GHz

So, i've just tried to disable the thread scheduler on InFamous, and it... Gave me nothing. FPS was the same.
It wasn't less or more, it was the same fps, just like if this option does not existed...
Then i've tried to enable it again, and... Same fps.
Is this thing even working? Because it should do something, because i have... well.. this...
![image](https://user-images.githubusercontent.com/20757715/50358924-f9142f80-056b-11e9-8569-aaac17f02726.png)
Here is logs.
Without Thread Scheduler
[RPCS3_Thread_Off.log](https://github.com/RPCS3/rpcs3/files/2703910/RPCS3_Thread_Off.log)
With Thread Scheduler
[RPCS3_Thread_On.log](https://github.com/RPCS3/rpcs3/files/2703911/RPCS3_Thread_On.log)
Maybe someone should test it with more powerfull pc.

**Comment by AniLeo** [comment]
> Intel Core

It's a Ryzen option only.

**Comment by MSuih** [comment]
It's not ryzen only feature, there's an implementation for intel processors as well. But it's only useful for 2c4t processors, and very likely to have no significant impact for even those.

https://github.com/RPCS3/rpcs3/blob/634a5fa31cf4dfe7583e73c0a140e0b75ccd34f3/Utilities/Thread.cpp#L1881-L1901
