### ISSUE TITLE
Minecraft [NPUB31419] Horizon bug (OpenGL)

### ISSUE THREAD

**Issue by altiereslima** [RPCS3/rpcs3#5452]
To be in high place the texture of the horizon gets errors. Only in OpenGL.

![sem titulo](https://user-images.githubusercontent.com/18044879/50403176-a01ee400-0783-11e9-9c18-2846d9166650.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2707543/RPCS3.log.gz)

**Comment by altiereslima** [comment]
Resolution Scale 100%

![sem titulo](https://user-images.githubusercontent.com/18044879/50404345-e5481380-078d-11e9-8b2b-de60d2c91619.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2707617/RPCS3.log.gz)

**Comment by Megamouse** [comment]
looks good to me: (don't mind the custom build. it's basically 0.0.5-7715)
![image](https://user-images.githubusercontent.com/23019877/51089089-bd821500-1767-11e9-8306-f984a81b2ffd.png)

**Comment by altiereslima** [comment]
Still the same here

**Comment by Megamouse** [comment]
Maybe its a specific shader pack you are using?

**Comment by altiereslima** [comment]
> Maybe its a specific shader pack you are using?

No.

**Comment by niko1point0** [comment]
Wolves spawn all around the players when Multiplayer is enabled

**Comment by AniLeo** [comment]
![image](https://user-images.githubusercontent.com/10283761/52480893-e057eb80-2ba4-11e9-9076-5c0e60d9e226.png)

Can reproduce, there's some weird flickering alongside it

**Comment by AniLeo** [comment]
Cannot reproduce on latest MESA. Last 6 versions of AMD drivers don't support OpenGL...

**Comment by YuriNator557** [comment]
Cannot reproduce on my end, maybe this can be closed?
![image](https://user-images.githubusercontent.com/76178650/114310787-eed32200-9ae3-11eb-946f-951722a7f5b6.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6292135/RPCS3.log.gz)

**Comment by kd-11** [comment]
Closing as fixed.
