### ISSUE TITLE
add some shortcut's parameters

### ISSUE THREAD

**Issue by Andryshik345** [RPCS3/rpcs3#5454]
How to about add some shortcut's parameters to start games without any gamelist selectors and debug consoles? Only game window itself. e.g. this(```"Persona 5.ink"```):
```...\rpcs3.exe -GameID=NPEB02436 -GameConfig=NPEB02436.cfg (optional)```
And also easily make them from gamelist too.

**Comment by vsub** [comment]
If you make a shortcut like this
"path to rpcs3\rpcs3.exe" "path to the game eboot.bin"
and then right click=>properties=>run=>minimized

You will get almost the same result
You can also close the debug console

Right now I am just double clicking on the shortcut and the game starts in fullscreen without seeing the main rpcs3 window

Btw using the game id rather that the whole path to the eboot.bin would be nice

**Comment by Megamouse** [comment]
The mentioned cli args were addeda while ago.
Shortcut creation will be handled in #9806

**Comment by elad335** [comment]
Fixed in #13008 actually.
