### ISSUE TITLE
Cars: Race-O-Rama - Cannot load game saves

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#5458]
When trying to load a saved game with `Cars: Race-O-Rama [BLES00620]` the screen goes completely black, but it just returns to the title screen (I can tell due to background music, and you can navigate the title-screen and bring up the load menu again even though you can't see anything.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2710397/RPCS3.log.gz)
[save.zip](https://github.com/RPCS3/rpcs3/files/2710399/save.zip)

**Comment by Asinin3** [comment]
Same issue, goes back to title-screen, it's not caused by native interface

**Comment by jjsat** [comment]
The fact that the game spawns a new thread to handle the savedata functions could indicate that it is this issue: https://github.com/RPCS3/rpcs3/pull/3918#issuecomment-354595886.

**Comment by elad335** [comment]
test with #5697

**Comment by Asinin3** [comment]
Same issue except when native UI is disabled screen no-longer goes black but it still goes back to title-screen.

**Comment by elad335** [comment]
Fixed by https://ci.appveyor.com/project/elad335/rpcs3/builds/23569503, potentially fixing similar issues. not only with save dialog, but also with message dialog etc.
