### ISSUE TITLE
can not lift the tree 1st god of war 3

### ISSUE THREAD

**Issue by mahdilivecoder** [RPCS3/rpcs3#5470]
i can't lift the tree at started game after smashing circle very fast,I was test this with keyboard and joystick in always, but not working at all time .

**Comment by Xcedf** [comment]
What framerete do you have during this event

**Comment by AniLeo** [comment]
This is a symptom of low performance, there's no specific issue being reported here

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
