### ISSUE TITLE
3D is not supported

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5471]
Whatever flag sets "3D" is not being passed to certain titles. The option is just greyed out as if my 'setup' doesn't support it. 

Impacted titles:
House of the Dead Overkill
Ridge Racer 7
Motorstorm 3D Rift

Motorstorm example:
![2018-12-29 11_08_33-fps_ 29 96 _ vulkan _ 0 0 5-ee208a5c-fbo_fixes _ motorstorm _ 3d rift npua80499](https://user-images.githubusercontent.com/20983844/50541600-062db180-0b5e-11e9-9da3-7cebdb912220.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2716676/RPCS3.log)

Note: 
Captain America (uses top/bottom) works, but the other games probably use steroscopy to achieve 3D.

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM
3D Monitor

**Comment by kd-11** [comment]
This option won't be available for some time to come. We do not report 3D support to applications at the moment as part of the supporting infrastructure is missing. Also likely needs a ton of RE work with different 3D hw to determine exactly how PS3 outputs 3D content.

**Comment by kd-11** [comment]
Closing as fixed via https://github.com/RPCS3/rpcs3/pull/7657

**Comment by legend800** [comment]
How are you tracking stereoscopic 3D support if we're closing this? That's really by far the best way to play 3D (assuming you got the right monitor\tv.

**Comment by kd-11** [comment]
Read the issue description and it's obviously a different issue. 3D is supported even if its not the best viewing method right now. Anyway, monitor-based viewing will be ready soon enough.
