### ISSUE TITLE
Game crashing  with RPCS3

### ISSUE THREAD

**Issue by GoryTarrafa** [RPCS3/rpcs3#5477]

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Comment by GoryTarrafa** [comment]
Penso que tambem és Portugues/a ,  já tenho tudo a funcionar menos o jogo que não arranca fica em freeze o que penso ser só má config do jogo , não me podes ajudar com o teamviewer por 1 minuto pf ?

**Comment by AniLeo** [comment]
Submit a RPCS3.log file in our Discord Server's #help channel, I'm on the middle of work and don't have teamviewer, I can help you on the help channel with a log file though.

**Comment by GoryTarrafa** [comment]
Can you send me the discord invite plz ?

**Comment by MSuih** [comment]
https://discord.me/RPCS3

**Comment by GoryTarrafa** [comment]
Thank you for the help , and sorry for the mess . :(
