### ISSUE TITLE
Godzilla Regressed to Intro after #4623

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#5480]
Godzilla broke after https://github.com/RPCS3/rpcs3/pull/4623 merged. Upon starting the game, you'll be met with the language selection screen. when you select a language the Native UI will open and give you a confirmation dialog (yes or no).

Upon hitting X, the dialog closes but the game doesn't progress any further, and button inputs become unresponsive. Restarting the game and selecting the language again generally crashes RPCS3.

In the latest versions of RPCS3 it doesn't simply close the dialog on the first run, but crashes every time.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2717711/RPCS3.log.gz)

**Comment by Megamouse** [comment]
should be fixed with #5465

**Comment by Asinin3** [comment]
Confirmed, fixed disc and psn versions of Godzilla.
