### ISSUE TITLE
Drakengard 3 Problem

### ISSUE THREAD

**Issue by Wizzy2018** [RPCS3/rpcs3#5483]
Hi all :) i have a little problem
RPCS3 0.0.5-7642
So i just boot up Drakengard 3 NPEB01741 and i got this error and black screen
{PPU[0x1000010] Thread (RenderingThread) [0x0157d6f8]} MEM: Access violation reading location 0x10
My system
CPU: Intel I5-4590
Ram: 8Gb DDR3-1600Mhz
GPU: Gigabyte RX470 G1 4Gb
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2718716/RPCS3.log)

**Comment by AniLeo** [comment]
Closed as invalid for disrespecting Issue Guidelines, this is not a support forum, this is an issue tracker

**Comment by 13xforever** [comment]
Github is not for support, please close the issue and use forums or discord instead.

You've changed random settings, so it's your fault, and not an issue with the emulator.
