### ISSUE TITLE
Feat. req. - implement option to turn off logging to disk (*.log, *.gz)

### ISSUE THREAD

**Issue by necros2k7** [RPCS3/rpcs3#5486]
subj

**Comment by MSuih** [comment]
Pull request #5333 implements this.

**Comment by AniLeo** [comment]
Duplicate of #5113

**Comment by eadmaster** [comment]
> Pull request #5333 implements this.

https://github.com/RPCS3/rpcs3/pull/5333 only allows to change the verbosity, not disabling the logs on disk, correct?

**Comment by elad335** [comment]
It's implemented I do not remember which pull request made it. It's in advanced tab  I think.

**Comment by MSuih** [comment]
There are two options:
* Silence logging after game starts
* Raise logging level to fatal so that barely anything gets logged.

There's no way to completely disable logging though so that even the file wouldn't get created.

**Comment by elad335** [comment]
I do not think there should be a way to completely disable it on purpose.

**Comment by elad335** [comment]
Like if you are really want it for some reason you can mark them as read only files  and rpcs3 won't bother.
