### ISSUE TITLE
Rapala Pro Bass Fishing [BLES00957]

### ISSUE THREAD

**Issue by Hermann3524** [RPCS3/rpcs3#5498]
The game is running fine, almost perfect, needs corrections in the rendering of distance under the water you can see at 2:41 until 3:17, please someone could work on it, the game would be perfect

https://www.youtube.com/watch?v=cMzKK-wRiOg&t=5s

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
