### ISSUE TITLE
RPCS3 Stopper working

### ISSUE THREAD

**Issue by voxsoftware** [RPCS3/rpcs3#5500]
====================================================

When submitting an issue, please check the following:

- RPCS3 version: 0.0.5-7652-37c621eb Alpha 
- Playing virtua tennis 4 in mode arcade. Fails in 4th or in last game 
- Windows server 2016, 32 gb ram, NVIDIA Quadro M4000, Vulkan renderer (I tested opengl same result), Intel xeon e5 2623 v4 (8 cpus) 

- Please also provide:
  - How can i get the backtrace??

**Comment by elad335** [comment]
??

**Comment by AniLeo** [comment]
This reads as a support request rather than an issue report, contains no log file or backtrace

**Comment by AniLeo** [comment]
Use our forums or discord server to ask for support

**Comment by voxsoftware** [comment]
let me know how get the backtrace and log in a crash, because after a crash the log looks deleted

**Comment by AniLeo** [comment]
To get a backtrace you need to run it under VS debugger after building the commit locally, the RPCS3.log isn't deleted after crash, just the compressed version, you can manually compress it and upload

**Comment by voxsoftware** [comment]
you mean that for backtrace i need compile the source code?

**Comment by AniLeo** [comment]
Yes, it's impossible to provide the pdb together with the emulator since it's 128MB

**Comment by voxsoftware** [comment]
I understand you, but if you have a link to pdb i will download. I am a programmer but i really don't have so much time.
