### ISSUE TITLE
Mouse acceleration, lerp and window issues

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#5501]
With introducing mouse settings to GUI, I'd like to share issues I found.

1) In some games acceleration of 5.00 is still not enough. While Windows mouse sensitivity is good enough, it may move really slow in RPCS3. I'd suggest to raise values at least up to 10. Also, for Y-axis raising values work very unobvious.

2) Interpolation seems work wrong on Y-axis. While I really see smoothing differences on horizontal moving, I can't see it on vertical.

3) "Pad config" window size is now grows when we switching from Keyboard to gamepads, and then doesn't return back when Keyboard selected. I'd suggest to use fixed window size for all modes instead.

**Comment by Megamouse** [comment]
1 can be easily done.
2 what interpolation are you referring to?
3 the window size is precalculated by Qt. I don't have this issue but I can try to improve it.

**Comment by Psycho-A** [comment]
So, will at least points 1 and 3 be done...?

**Comment by Megamouse** [comment]
#6109 will close this issue since there is at least another issue that mentions point 3
