### ISSUE TITLE
NIER [BLUS30481] crashes randomly in the old shrine [rpcs3-v0.0.5-7678-52ac0a90_linux64.AppImage]

### ISSUE THREAD

**Issue by Faunenschnitt** [RPCS3/rpcs3#5512]
Hello, while the game runs great (except the minor sound crackling) and without crashes for the first part, it starts to randomly crash for me in the old shrine while encountering shades. I tried various combinations of settings without success so far (vulkan crashes earlier, opengl a bit later). Log file is attached. The logs might vary for different runs as the reproducibility is difficult. Maybe a race condition or out of memory problem? Sometimes the game crashes directly to the linux console with a segmentation fault. Regards

- RPCS3 version: rpcs3-v0.0.5-7678-52ac0a90_linux64.AppImage (tested versions starting from 5465 due to the name input issue https://github.com/RPCS3/rpcs3/issues/5494)
- Linux 4.14.78-gentoo #1 SMP PREEMPT Sun Oct 28 09:09:28 CET 2018 x86_64 Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz GenuineIntel GNU/Linux

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2730344/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Closing due to blatant signs of piracy on the log, specially from a group that modifies games with their "loaders"
