### ISSUE TITLE
After #5315 moving,resizing,minimizing the game window while emulation is paused,causes rpcs3 to freeze

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5515]
0.0.5-7536 - freeze
0.0.5-7513 - works fine

There is no log because after you pause and do anything to the game window,rpcs3 freezes and the only way out is killing the process which also deletes the gz file and the log stops at the time you pause the emulation

**Comment by kd-11** [comment]
This was caused by some lost commit, likely an error during rebase of the fifo fixups PR. There was a new emulation state and an accompanying backend task, no idea how it got lost.

**Comment by kd-11** [comment]
Coincidentally fixed by the nvidia workaround patch here https://ci.appveyor.com/project/kd-11/rpcs3/builds/21420755/artifacts

**Comment by vsub** [comment]
Seems to be fixed,thanks

**Comment by Megamouse** [comment]
I don't think this is in master yet

**Comment by vsub** [comment]
No it's not.
So do I leave a issue open until it's merged?

**Comment by Megamouse** [comment]
obviously

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/5612

**Comment by kd-11** [comment]
Its is not the same issue

**Comment by vsub** [comment]
Works fine on 0.0.6-7790,thanks
