### ISSUE TITLE
Double Dragon Neon [NPUB30764]: 2D background does not render properly

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5517]
The background of Double Dragon Neon does not render correctly. 

![2019-01-06_10_39_01-window](https://user-images.githubusercontent.com/20983844/50740393-7792e300-11a2-11e9-9321-d72d1cf14299.png)

Note: 
Aside from bg, gfx, audio, perf, stability are perfect. Xenia renders the bg correctly. 

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

[NPUB30764_20190106105936_capture.zip](https://github.com/RPCS3/rpcs3/files/2730767/NPUB30764_20190106105936_capture.zip)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2730768/RPCS3.log.gz)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/5565
