### ISSUE TITLE
Bioshock freezes at game load

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#5520]
As of 52ac0a901acac98d05ed9c989069b9ea107082b4, Bioshock freezes when loading into a game.  The game ran fine at build cfe07098674b46b10cfdb527dce9c405f54c7621 from December 28, though I haven't had time to bisect this yet.

Logs spam messages such as:

`E {PPU[0x1000000] Thread (main_thread) [0x01121ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30393/USRDIR/system/modeffects.ini” [1]
`

Tested on an Intel i7-7820HK and Nvidia GTX 1070 running Linux Mint 19.1 x64 with kernel 4.18

**Comment by RainbowCookie32** [comment]
You should attach the whole log instead of one line

**Comment by Shoegzer** [comment]
Sure, [here](https://pastebin.com/RpsPAWAs) is a full log of messages written immediately before the freeze.

**Comment by Jhonny-2005** [comment]
I`m also have this in twisted metall
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2732123/RPCS3.log.gz)
and other
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2732126/RPCS3.zip)

**Comment by Shoegzer** [comment]
Right, I figured that would have been enough but here's the log anyway: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2733955/RPCS3.log.gz)

**Comment by Shoegzer** [comment]
Oh gads.  I started working on the bisect and then I remembered that my super-sneaky evil twin changed the SPU block size to "Mega" from "Safe".  Reverting to Safe fixed the issue of course.  I feel wonderfully brilliant now!  -_-

@Jhonny-2005 check this setting for Twisted Metal, bope it helps.
