### ISSUE TITLE
Can a 'eventually consistent' concurrent hashmap be used for the cell processor?

### ISSUE THREAD

**Issue by i30817** [RPCS3/rpcs3#5521]
I mean instead of mutual exclusion or naive read write locks. With that kind of structure, you don't have the writers blocking the reads (at the cost of more memory used and it being 'eventually' consistent).

Here is a example of what i mean:
https://youtu.be/s19G6n0UjsM?t=1996

and here is the crate that implements this:
https://github.com/jonhoo/rust-evmap

I was wondering because it seems to me your already delaying reads with barriers - based on your latest blogs - and you might have similar mechanism here that scales better.

If you need multiple writers you can get it with a write lock (it's explained in the github, though the video is better to see how it works in  the optimal case).

Of course, if 'eventual' consistency is a deal breaker, this might be completely useless compared to a read write lock. Though, the github says:
> Preliminary results show that evmap performs well under contention, especially on the read side. This benchmark represents the worst-case usage of evmap in which every write also does a refresh

So it might not so bad to throw away the 'eventually' when needed.

**Comment by kd-11** [comment]
I looked at this a while back, I cannot speak for neko, but it would not work due to multi-write, multi-read of spu code, combined with interdependency all over the place. Something a lot more complicated would be required than the simple redirection technique in that presentation. Maybe someone else can interpret it differently but thats my 2 cents.

**Comment by Nekotekina** [comment]
Situationally, yes, this approach may be useful.
But not for Cell emulation.
