### ISSUE TITLE
Total number of installed games on GUI?

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5524]
if it's possible adding total number of installed games in rpcs3

and adding games genres automatically by Emulator rpcs3 itself by database file

**Comment by AniLeo** [comment]
There's no genre database nor config database.

Total number of installed games is up to Megamouse but I don't even see where it could be placed.

**Comment by Megamouse** [comment]
The question is: what defines as game?
Do we only count HDD games or do we also count Disc games?
And then there are movies and apps and ps1 classics etc.

This is where I could add it for now:
![image](https://user-images.githubusercontent.com/23019877/50836092-ab176e00-1358-11e9-9644-cedf2b3f7b54.png)

**Comment by legend800** [comment]
I'd rather not lose vertical space in my game list (lose a whole game maybe) for some weird, arbitrary, ocd thing like displaying the total number of games all the time. I don't get the value here and I'm strongly against this.

**Comment by Asinin3** [comment]
While we're on the topic of vertical space, it does bother me a bit that the docking areas can't be hidden so you can get some of that precious screen real-estate back.

**Comment by nitrohigito** [comment]
Docking areas?

**Comment by uaqlover** [comment]
@Megamouse 

it will be better like this 

Game List (##) HDD games (##) Disc games (##) ps1 classics (##)

it's good for who has so many games like tester and who has collection of games

**Comment by Asinin3** [comment]
@nitrohigito The toolbar isn't a docking area... this is. (ignore cursor, for some reason it's not in the right position in the capture :/ ) but these bars are what I am talking about. https://puu.sh/CtBBE/747d667bd0.mp4
