### ISSUE TITLE
Regression: flickering text in Gran Turismo HD Concept

### ISSUE THREAD

**Issue by Resident007** [RPCS3/rpcs3#5532]
After some recent updates (I think it's rpcs3-v0.0.5-7691-d9d5f45e_win64 #5497) text in menu started to flicker. This is my first report here so don't judge me strictly :)
Specs:
Intel Core i5-2300 (2,8 GHz, 4 Cores, 4 Threads) CPU
Gigabyte GTX 1060 Windforce OC 3GB
8GB DDR3 1333MHz RAM
Windows 10 Pro
![base profile screenshot 2019 01 10 - 22 13 13 27](https://user-images.githubusercontent.com/25570319/50991489-d4d1c000-1525-11e9-9efb-a3c16011d3c8.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2746762/RPCS3.log)

**Comment by kd-11** [comment]
Need a proper regression test since its very unlikely that changing dialog boxes caused this, It definitely broke somewhere after merging GT fixes PR so that's a good place to start.

**Comment by Megamouse** [comment]
my impression is that it works much better on master than on the GT fixes PR

**Comment by kd-11** [comment]
Grass flicker has always been there, its the menu text flicker that is new. I saw this in the demo, will check AMD card, maybe only affects nvidia.

**Comment by Megamouse** [comment]
No, i just said i have the flicker too. but it is there on the GT fixes as well so it can't be new if you mean "new since gt fixes"

**Comment by kd-11** [comment]
Maybe it regressed in GT fixes before merge then.

**Comment by Megamouse** [comment]
do you remember a commit in gt that worked?

**Comment by kd-11** [comment]
Must have changed towards the end since I played this game a bit looking for some regressions in fbo_fixes and it was fine. Both PRs were open at the time.
I'll check final GT fixes commit for the flicker just to be sure its the same one I'm seeing on master.

**Comment by Resident007** [comment]
If it would be helpful, the issue is also present in latest build now, #5453

**Comment by Kravickas** [comment]
I had this too, but only on one line and very minor.. maybe the better cpu less glitches.

**Comment by Resident007** [comment]
This issue is no longer present in 0.0.5-7755 (Master branch)
