### ISSUE TITLE
Regression from #5497: Skate 3 crashes when entering a name

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#5533]
On #5497, if Skate 3 is started without a pre-existing save file, the game can be played untill you get to selecting a name for your skater. But once you try to enter a name, the whole emulator will freeze after hitting ok. Before this PR was merged, the input dialog worked fine.

Interestingly, the issue can be avoided if one cancels the name input at least two times by pressing ESC. Cancelling once isn't enough, but two cancels (or more) will fix it. Also, the team name dialog that pops up before skater name dialog doesn't have any issues.

[RPCS3_7681_enterName.gz](https://github.com/RPCS3/rpcs3/files/2748180/RPCS3_7681_enterName.gz)

[RPCS3_7691_enterName.gz](https://github.com/RPCS3/rpcs3/files/2748181/RPCS3_7691_enterName.gz)
[RPCS3_7691_cancelOnce.gz](https://github.com/RPCS3/rpcs3/files/2748182/RPCS3_7691_cancelOnce.gz)
[RPCS3_7691_cancelTwice.gz](https://github.com/RPCS3/rpcs3/files/2748184/RPCS3_7691_cancelTwice.gz)

**Comment by mchtt** [comment]
I fix it by keeping space key pressed while validating the hidden window with the corresponding key (like X on my DS4 controller)

**Comment by MSuih** [comment]
Resolved with #5536
