### ISSUE TITLE
Armored Core: For Answer [BLUS30187] - No collision

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#5545]
The GIF below illustrates the problem with the first few seconds of gameplay, and why you can't progress any further: https://i.imgur.com/Y5LdZPz.gif

RPCS3 Discord's #help channel confirmed the issue is universal and not due to a setting or my specific hardware.

Compatibility Report here: https://forums.rpcs3.net/thread-194303-post-302749.html#pid302749

**Comment by Aidolii** [comment]
Sadly there's still no improvement with today's latest stable https://github.com/RPCS3/rpcs3/commit/d4591b15083b8ae8b3429c2616e677c9fc016aab or even the current stage of the big Fixes/Improvement PR https://github.com/RPCS3/rpcs3/pull/5565/commits/2d606c75703d0e56b7dc55657f9a3941119da45c

**Comment by Aidolii** [comment]
@kd-11 CPU label? Has something about this bug been discovered? I'd like to hear it if so.

**Comment by MSuih** [comment]
No. It's just a bug with physics or collision detection, not f.ex. graphics or controller input.

**Comment by elad335** [comment]
Can you test this with ppu precise and build https://ci.appveyor.com/project/elad335/rpcs3/builds/23202030?

**Comment by Aidolii** [comment]
@elad335 I'm afraid I don't have a compiling environment for RPCS3, I just typically use the AppVeyor artifacts. And looking at the dependencies, setting up a compiling environment would take quite a lot of work.

**Comment by Asinin3** [comment]
Pretty sure elad just wants you to use that build he linked. Click on the artifacts button and you can download the binary directly already compiled from appveyor.

**Comment by Aidolii** [comment]
@Asinin3 @elad335 There are no binaries compiled from appveyor on what he linked.

**Comment by Aidolii** [comment]
..or at least there weren't 10 minutes ago.

**Comment by RainbowCookie32** [comment]
Yes, right there on artifacts https://ci.appveyor.com/api/buildjobs/ypn9hx4ohb2vya5u/artifacts/rpcs3-v0.0.5-7888-62507cd3_win64.7z

**Comment by Aidolii** [comment]
I swear on my mother that it said the compilation had failed and there were 0 artifacts listed 12 minutes ago.

**Comment by Asinin3** [comment]
is that why it says it finished building over 2 hours ago :D anyway, let's not spam this. Just test it and see if it's fixed

**Comment by Aidolii** [comment]
@Asinin3 Here look, I'm not crazy after all.

![image](https://user-images.githubusercontent.com/37132025/54646988-e035f000-4a6e-11e9-831d-340bd41b2ae8.png)

It finished compiling just as I was finishing up my first reply to elad.

**Comment by Aidolii** [comment]
Oh thank goodness I have the tab still open.

![image](https://user-images.githubusercontent.com/37132025/54647077-399e1f00-4a6f-11e9-896a-a6a2d5122e61.png)

**Comment by RainbowCookie32** [comment]
Doesn't matter, just test as elad asked you and stop flooding the issue with those messages. Everyone involved gets a notification on each new message

**Comment by Aidolii** [comment]
@RainbowCookie32 I'm not going to apologize when my competency was being called into question. That makes my testing look unreliable. And I found proof, so it's pretty much settled now anyway.

As for the testing, I'm afraid there was no change. Still falling through the floor, same as before. Here's the log: https://cdn.discordapp.com/attachments/463890612559806496/557700096834273290/RPCS3.log.gz

**Comment by Asinin3** [comment]
![rpcs3_x8gWaU090M](https://user-images.githubusercontent.com/15137035/73999384-84d95d00-49b4-11ea-8b2d-141eeaf18c8b.jpg)
Can be closed.
