### ISSUE TITLE
Conan [BLUS30069] Missing shaders/lighting/textures

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5554]
Missing lighting/textures/shaders on Conan.

Console:
![2019-01-14 08_45_06-window](https://user-images.githubusercontent.com/20983844/51127422-433ea880-17da-11e9-83df-0a3578c1e548.png)

rpcs3:
![2019-01-14 08_47_42-window](https://user-images.githubusercontent.com/20983844/51127449-52bdf180-17da-11e9-89e7-7acd92257417.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2756168/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by RESELEV** [comment]
The night Battle play would in it but not goes

**Comment by legend800** [comment]
@RESELEV Do not comment on issues unless relevant. None of that makes any sense.

Here's a rsx capture:
https://drive.google.com/file/d/1eodXRn4XQVnwsSBvy9VWg9KYM6tlTBvZ/view?usp=sharing

**Comment by ruthan** [comment]
Its still the same for at least year where i testing it.

**Comment by ruthan** [comment]
Im testing it periodically even some PR but this nothing :( Does someone know more exactly where is the problem?

**Comment by ruthan** [comment]
Still the same problem.

**Comment by legend800** [comment]
How are you able to get into gameplay to check? For me, it's been crashing for months with this error once gameplay begins (assuming I can get past the file copy upon launch - 1/5 times):
F {RSX [0x016014c]} SIG: Thread terminated due to fatal error: Verification failed: 
(in file d:\a\1\s\rpcs3\Emu\RSX\RSXThread.cpp:359)

Issue: https://github.com/RPCS3/rpcs3/issues/7785

Can you upload a log so we can see your settings?

Here's mine:  
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4640706/RPCS3.zip)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/8367
