### ISSUE TITLE
RPCS3 welcome screen won't go away in Linux

### ISSUE THREAD

**Issue by arabek** [RPCS3/rpcs3#5556]
![screenshot_20190115_102827](https://user-images.githubusercontent.com/2504890/51171186-8703e180-18b0-11e9-92fe-52f24572ffa2.png)

Even after checking both the options, it reappears on subsequent runs.
Clearing the config folder (as in rm -rf) didn't help either.

RPCS3 v0.0.5-7729-f19fd232 Alpha | master
QT 5.11.3
Built from sources

**Comment by arabek** [comment]
Fixed on Linux after deleting ~/.config/RPCS3rc (i didn't notice the file at first) and the config folder completely.

**Comment by Megamouse** [comment]
if you have these problems then you usually have your gui settings file set to "default" which will reset them every time you open rpcs3
