### ISSUE TITLE
Few incorrect behaviours since the cache location change(data to cache)

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5557]
1.I don't know if this is expected behavior but the custom settings are saved and loaded from\in the data folder which basically will mean after this change,two folder for one file.
2.PPU\SPU\Shaders are loaded and saved from \to the cache folder but all "Remove" options are deleting the files from the data folder not the newly created in the cache folder

**Comment by MSuih** [comment]
1. This is intentional, cache folder was created just for storing cache files. This makes more sense on linux, as there caches are stored in completely separated location from configuration files.
2. Should be resolved with pull request #5558

**Comment by vsub** [comment]
Ok thanks but one question.
Does this changing of the location mean I lose everything...I have to recreate the ppu modules,spu cache and the shaders for all games
