### ISSUE TITLE
Screenshot glitches

### ISSUE THREAD

**Issue by KillZone** [RPCS3/rpcs3#5564]
When I take a screenshot in Ni no Kuni it shows the same image over and over till I minimize the game and go to fullscreen again. The first picture is outdated but I'm on that map, on the second I should be in the house but it still looks like I'm outside. The third picture was taken after I minimized the game and gone into fullscreen again. It shows the house correctly.
If you check the bottom of the pictures it seems like the frames got overlapped and got an offset too. At smaller resolutions (1280x720) the problem becomes even 
more visible. (4)
![2019-01-16 22](https://user-images.githubusercontent.com/1431347/51250954-5eefad80-1998-11e9-8dd4-a787282200cd.png)
![2019-01-16 23](https://user-images.githubusercontent.com/1431347/51250951-5e571700-1998-11e9-853d-5891e93d3eef.png)
![2019-01-16 25](https://user-images.githubusercontent.com/1431347/51250952-5e571700-1998-11e9-99ad-84856bd8fee2.png)
![2019-01-16 1](https://user-images.githubusercontent.com/1431347/51250953-5e571700-1998-11e9-8188-301cd70d698a.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2764292/RPCS3.log.gz)

I hope it is a useful report. :) I know this issue doesnt have too much significance, but might help out in finding some other emulator related problems.

System specs: Ryzen 1800x, RX 580, 16 Gb RAM, Windows 10 
RPCS3: v0.0.5-7731 Alpha [2019-01-16]

**Comment by kd-11** [comment]
Screenshot software grabs the image from windows and we already submitted to windows the 'correct' image, otherwise you would not be able to see anything on screen. This means the problem lies in windows vulkan integration and can only be fixed by Microsoft and your driver vendor, AMD in this case.
