### ISSUE TITLE
[AMD Proprietary Only] Deus Ex: Human Revolution DC graphical issue in OpenGL only

### ISSUE THREAD

**Issue by jjsat** [RPCS3/rpcs3#5569]
DX:HR DC (BLES01928) has an issue when using the OpenGL renderer. Vulkan is fine. With OpenGL there are stray shadow-like lines present on many surfaces, see images. The artifacts are not fixed on the surface but appear in relation to the camera

RSX Capture: [BLES01928_20190117190312_capture.zip](https://github.com/RPCS3/rpcs3/files/2770023/BLES01928_20190117190312_capture.zip)

Log (using OpenGL): [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2770055/RPCS3.log.gz)

OpenGL:
![grafik](https://user-images.githubusercontent.com/1445782/51338894-54621080-1a8b-11e9-933e-0d1d556f28e4.png)

Vulkan:
![grafik](https://user-images.githubusercontent.com/1445782/51338992-92f7cb00-1a8b-11e9-8cd1-21ed2e9735d6.png)

~~Note: The screenshots are from the RSX capture. When running the game normally the part left of the curtain is a transparent window. This does not render correctly in the capture.~~ I was mistaken about this. The capture renders correctly.

This is not a recent regression. It has been like this for months.

**Comment by kd-11** [comment]
Looks like an issue with border color decode.

**Comment by kd-11** [comment]
This doesn't seem to be an issue anymore by replaying the capture. Tested on an AMD card, confirm if fixed for you.

**Comment by jjsat** [comment]
For me the capture looks like this on current master with OpenGL:
![grafik](https://user-images.githubusercontent.com/1445782/60754089-766d3200-9fdc-11e9-9f2c-5bede4d4334e.png)
Vulkan still renders fine.
Log from replaying the capture on OpenGL: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3364560/RPCS3.zip)

**Comment by kd-11** [comment]
Glitches when replaying captures are expected though. Is the real game also glitchy like that?

**Comment by jjsat** [comment]
Yes, the game looks the same as the screenshot and is very slow

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/61121040-ee3cd000-a4a6-11e9-8279-88f546ff9ee5.png)
Seems to ok on radeonsi (RX 470), but I have yet to retest on windows driver. Is it still broken for you?

**Comment by kd-11** [comment]
Broken on windows proprietary driver, isolating it to another possible driver bug. Its also ok on nvidia drivers on both windows and linux. I'll try and isolate the cause for a bug report soon.

**Comment by digitaldude555** [comment]
Update?

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/74087591-ed9d0400-4a9e-11ea-9f06-626275580c37.png)

Seems to have been fixed for some time now.
