### ISSUE TITLE
Wolfenstein (2009) graphical ssue since #5427 - OpenGL only

### ISSUE THREAD

**Issue by jjsat** [RPCS3/rpcs3#5570]
Wolfenstein (also the demo, NPUB90248) has a new issue since #5427 with OpenGL only. Before the PR the game required strict rendering mode, now it doesn't anymore. With OpenGL some transparent textures (water effects at the start of the game) are rendered in solid color. Whether the effect is rendered correctly or with solid color is dependent on the camera position and angle.

RSX Capture: [NPUB90248_20190117192829_capture.zip](https://github.com/RPCS3/rpcs3/files/2770111/NPUB90248_20190117192829_capture.zip)

Log (with OpenGL): [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2770107/RPCS3.log.gz)

OpenGL:
![grafik](https://user-images.githubusercontent.com/1445782/51339995-1e725b80-1a8e-11e9-952c-a3617086befd.png)

Vulkan:
![grafik](https://user-images.githubusercontent.com/1445782/51340136-74470380-1a8e-11e9-8c60-95c0aed69133.png)

Generally there is a problem with how the raindrops on the screen are rendered. They have always appeared with a distorted texture and with the vertices seemingly rotated at an angle. This is not part of the regression.

Settings like "Write Color buffer" or "Strict Rendering Mode" do not affect the behaviour.

**Comment by kd-11** [comment]
Looks like broken gl state management, a fix will be made available soon.

**Comment by jjsat** [comment]
This is fixed in #5565. Thank you!
