### ISSUE TITLE
Vulkan always streches to display area even if it is disabled

### ISSUE THREAD

**Issue by KillZone** [RPCS3/rpcs3#5571]
Starting a game in fullscreen with the Vulkan renderer always stretches the image to the display. (Stretch To Display Area off, Ascpect Ratio set to 16:9)
Going to windowed mode then fullscreen again solves the problem after the Loading Precompiled Shaders Screen. 

![loading precompiled](https://user-images.githubusercontent.com/1431347/51353667-8edea400-1ab1-11e9-8018-80171a7452ff.png)

![ni no kuni](https://user-images.githubusercontent.com/1431347/51353267-728e3780-1ab0-11e9-81a1-529372afd23a.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2770863/RPCS3.log.gz)

**Comment by Megamouse** [comment]
There has always been an issue with the stretch in the loading screen.
I'm glad someone else noticed :)

I think it is mentioned in another general issue though iirc

**Comment by Megamouse** [comment]
here from #4072 
![image](https://user-images.githubusercontent.com/23019877/51353872-280dba80-1ab2-11e9-90e0-d56fe0a59bed.png)

**Comment by KillZone** [comment]
So should I keep the issue?

**Comment by Megamouse** [comment]
Yes

**Comment by Megamouse** [comment]
It is probably only coming to light like this because you have a widescreen resolution. Most people have 16:9. Thats why noone else complains

**Comment by Megamouse** [comment]
Cant you assume 720p for the native dialog by default?

**Comment by kd-11** [comment]
We certainly could. That requires setting up avconfig though with fake data. Not sure what consequences that would have. Currently missing avconfig data falls back to stretching.

**Comment by Megamouse** [comment]
But cant you just use the default just in the native dialog until avconfig is set up?

**Comment by kd-11** [comment]
This was solved a long time ago.
