### ISSUE TITLE
Can't get tales of Xillia past the recompiling shaders screen

### ISSUE THREAD

**Issue by lennethz** [RPCS3/rpcs3#5573]
I'm using latest version's default settings.
Specs: 
-NVIDIA GeForce GTX 960
-Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 CPUs), ~4.0GHz
-16GB RAM

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2774238/RPCS3.log)
[TTY.log](https://github.com/RPCS3/rpcs3/files/2774239/TTY.log)

**Comment by RainbowCookie32** [comment]
Don't ask for support while using pirated copies
