### ISSUE TITLE
Cancel Load? Screen - Ridge Racer 7

### ISSUE THREAD

**Issue by alondero** [RPCS3/rpcs3#5578]
When loading Ridge Racer 7 (BCES00009) I get a 'Cancel Load' screen as attached. I can hear the demo game playing behind but can't exit the screen and progress further.

Using RPCS3 version 0.0.5-7736-d4591b15. Vulkan. LLVM PPU, ASMJIT SPU, Load liblv2.sprx only.
i7 4790k, GTX 980, 32GB RAM, Windows 10[
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2775997/RPCS3.log.gz)
![image](https://user-images.githubusercontent.com/1269060/51432550-71d0df00-1c31-11e9-9e27-e209bca6f742.png)

](url)

**Comment by arcadesfan** [comment]
Hello, I have had this issue, It is not really a problem. Try to press Yes or No to see what happens. If it does nothing, just restart rpcs3, I think the second time the game will start fine, according to the hardware you have.

**Comment by legend800** [comment]
Is this still an issue? If not please close.

**Comment by alondero** [comment]
Hi, I worked around this problem by deleting my saves (I had brought these over from my PS3). I no longer have my saves and can't test any more - though this was still an issue as recent as 2 weeks ago. I'll close the issue as have no means to reproduce now.

**Comment by LogosTP** [comment]
I have the same issue, only happens when using save data from console it seems.

The in-game **Save** menu option shows no save data is present, but prompts if you want try and overwrite the current saved data.

![1](https://user-images.githubusercontent.com/8525344/154024859-79dc348f-6c5b-459f-a2cc-0f1dbb782740.PNG)
