### ISSUE TITLE
Switch Pro Controller analog axis value not centered 

### ISSUE THREAD

**Issue by e88z4** [RPCS3/rpcs3#5580]
Hi Everyone, 

I have a switch pro controller that pair with bluez. Below is my calibrated switch pro controller via evdev-joystick.

```
Supported Absolute axes:
Absolute axis 0x00 (0) (X Axis) (value: 30016, min: 5800, max: 52000, flatness: 4095 (=7.88%), fuzz: 0)
Absolute axis 0x01 (1) (Y Axis) (value: 36703, min: 12319, max: 59471, flatness: 4095 (=6.89%), fuzz: 0)
Absolute axis 0x03 (3) (X Rate Axis) (value: 29696, min: 6500, max: 53500, flatness: 4095 (=7.65%), fuzz: 255)
Absolute axis 0x04 (4) (Y Rate Axis) (value: 37314, min: 14300, max: 61000, flatness: 4095 (=6.71%), fuzz: 255)
Absolute axis 0x10 (16) (Hat zero, x axis) (value: 0, min: -1, max: 1, flatness: 0 (=0.00%), fuzz: 0)
Absolute axis 0x11 (17) (Hat zero, y axis) (value: 0, min: -1, max: 1, flatness: 0 (=0.00%), fuzz: 0)
```

When the device is detected on RPCS3, the origin value of the left and right analog stick are not centered as shown in the picture below. 

![rpcs3_analog_deadzones](https://user-images.githubusercontent.com/15828154/51442988-f878d100-1cb0-11e9-8f05-641596c72d92.png)

The left and right analog controllers are pretty much unusable. 

I don't have this issue with dolphin emulator. When I calibrate the deadzone in dolphin-emu the origin value of the left and right analog controllers are centered. 

Is this an issue with RPCS3 or something else?

**Comment by e88z4** [comment]
Just want to add my comment, the minimum and maximum value of the X and Y axis don't register full range on the circle (probably covering only half of the radius of the circle).

**Comment by Megamouse** [comment]
your drivers are wrong:

> Analog-Sticks:
> (for ABS values negative is left/up, positive is right/down)
> Triggers:
> (ABS trigger values start at 0, pressure is reported as positive values)

see: https://www.kernel.org/doc/html/v4.18/input/gamepad.html

we have a workaround for this (just make sure to set the correct axis to true):
> Hey again! I had contact to GalCiv (one of the RPCS3 developers), he pointed me to the following issue: [RPCS3/rpcs3#3974](https://github.com/RPCS3/rpcs3/pull/3974)
> 
> That means that the problem is on their side but there is a workaround described in the issue, in short:
> 
> * open ` ~/.config/rpcs3/evdev_positive_axis.yml`
> * change `false` to `true` in the following lines:
>   
>   * `ABS_X: false`
>   * `ABS_Y: false`
>   * `ABS_RX: false`
>   * `ABS_RY: false`
> 
> Maybe xpadneo should switch to a range from –32.768 to 32.767 in future version... I am not yet sure.
> I would be still interested in the `evtest` log for the other gamepad.

**Comment by e88z4** [comment]
Thanks for the direction in the yaml config. Can the yaml config be configured per controller? I have a switch pro and a xbox 360 controller. 

The switch pro controller has positive axis while the xbox 360 controller has -32.768 and 32.767 range.

**Comment by Megamouse** [comment]
I'm afraid not.
I didn't think this was a common issue so I made it as simple as possible.

**Comment by e88z4** [comment]
Thanks for clarifying. Issue can be closed.
