### ISSUE TITLE
Shadow of the Colossus HD [BCES01097] - Game freezes on FIFO error

### ISSUE THREAD

**Issue by paxsyr** [RPCS3/rpcs3#5584]
While playing, the game will freeze up with an "RSX: FIFO error: possible desync event" error at seemingly random points.

A full video starting from the boot of the game to the freeze can be seen here: https://youtu.be/AeJ5iC_WDLI
But this gif sums it up: 
![shadow of the colossus hd - short](https://user-images.githubusercontent.com/38361979/51452792-0f97dd00-1d0a-11e9-81d7-071475917d25.gif)

Basicly everyting is going smoothly until it just freezes up and the audio gets stuck. I was able to replicate this error with the default settings and the Vulkan renderer. I also used Write Color Buffers as it seemed to delay when the error occurs (normaly occurs at the very start of the cutscene vs. towards the end, from what I could tell) but I don't know for sure.

Logs:
[Shadow of the Colossus HD.log](https://github.com/RPCS3/rpcs3/files/2777591/Shadow.of.the.Colossus.HD.log)
[Shadow of the Colossus HD.log.gz](https://github.com/RPCS3/rpcs3/files/2777592/Shadow.of.the.Colossus.HD.log.gz)

Tested using RPCS3 v0.0.5-7736
Edit: Error is still present on RPCS3 v0.0.6-8322

**Comment by Realmantik** [comment]
The same error happens for Resonance of Fate [BLES00789].

**Comment by zminhquanz** [comment]
Same error happen on God Of War 3 [BCES00510]

**Comment by elad335** [comment]
Retest with rsx wake-up delay.

**Comment by elad335** [comment]
Confirmed fixed with it.

**Comment by FranciscoCarlosJunior** [comment]
Same error Happens to  Red Dead Redemption
