### ISSUE TITLE
Borderlands - Improper audio in opening cutscenes

### ISSUE THREAD

**Issue by Krusher97** [RPCS3/rpcs3#5592]
The audio in the fmv cutscenes of the game gets cut off at certain points and any voice over that should be present is completely absent while the subtitles are displayed.
Very easily reproducable by creating a new character and letting the opening cutscene play out.
In the attract cutscene which plays when you let the game stay at the main menu for a while has the music getting cut off at same points every time.

[Borderlands.gz](https://github.com/RPCS3/rpcs3/files/2787483/Borderlands.gz)

I don't know what else to add

EDIT: Apparently it does not happen in the disc version of the game. The one I used was NPUB30413 

Video of the issue : https://drive.google.com/open?id=1qTBi5QAqpYuUxqvuIg9iU91lf1n4kDEI

**Comment by questore** [comment]
Same happens in Uncharted1 scenes. 
Further information: 
- First run after clearing SPU cache: The audio stutters, out of sync from display (60fps stabile) but no missing audio parts.
- Second run no SPU cache clear, The audio smooth and no stuttering, but when camera switches, the audio is cut off until new camera switch. 
Other setting does not matters as i tried to reproduce it.

**Comment by questore** [comment]
> Same happens in Uncharted1 scenes.
> Further information:
> 
> * First run after clearing SPU cache: The audio stutters, out of sync from display (60fps stabile) but no missing audio parts.
> * Second run no SPU cache clear, The audio smooth and no stuttering, but when camera switches, the audio is cut off until new camera switch.
>   Other setting does not matters as i tried to reproduce it.

I have managed to find the solution.
Windows 10 audio playback device setting was set to 16bit output. 
I changed it back to 24bit and audio cutoff is gone in cutscenes. Even gain some performance ingame.

**Comment by questore** [comment]
> The audio in the fmv cutscenes of the game gets cut off at certain points and any voice over that should be present is completely absent while the subtitles are displayed.
> Very easily reproducable by creating a new character and letting the opening cutscene play out.
> In the attract cutscene which plays when you let the game stay at the main menu for a while has the music getting cut off at same points every time.
> 
> [Borderlands.gz](https://github.com/RPCS3/rpcs3/files/2787483/Borderlands.gz)
> 
> I don't know what else to add

Could you check if you have the same issue?

**Comment by Krusher97** [comment]
We aren't talking about the same issue

**Comment by questore** [comment]
> We aren't talking about the same issue

I don't have Borderlands NPUB30413 as yours but tried my BLUS30386 version and it don't have audio cutoff problem. vaiting for a NPUB31519 from someone to test your problem and see if i can confirm it.

**Comment by Krusher97** [comment]
You're telling me that the prerendered cutscenes in your game have voice acting?

Could you post a video of the cutscene after you start a new game if you can record one?

**Comment by questore** [comment]
Yes they have voice. I have uploaded it to my drive. 
Sorry for video stuttering it because I only have a weak AMD FX-8320E@4000Ghz
[video](https://drive.google.com/file/d/1KF8dKj9z9V0MgVxyk1tYMlntWe9GoEM_/view?usp=sharing)

**Comment by Krusher97** [comment]
Then the problem might be unique to the digital copies

**Comment by questore** [comment]
The problem is still exist I dont doubt it. If i got the other media, maybe i can confirm it on other version.

**Comment by RainbowCookie32** [comment]
I have audio and I have the same Game ID you have. [https://drive.google.com/open?id=1-Hn44IQrcRwUbmtdg3tX0OYmhGmiJAIC](url)

**Comment by Krusher97** [comment]
Fixed the no voice over issue by setting the console language to English from Japanese
Thanks to Majestic on discord for the suggestion.
