### ISSUE TITLE
Strange Vulkan framepacing issue in Persona 5

### ISSUE THREAD

**Issue by tet666** [RPCS3/rpcs3#5594]
I've got a strange Vulkan framepacing issue going on in Persona 5. The game has constant frametime spikes mostly in dungeons

Used RPCS3 builds: 7742 and most other builds since November
Settings I've tried:

PPU: LLVM
SPU Decoder: ASMJT & LLVM
Preffered SPU Threads: 1,2 & Auto

Additional Settings: Enable thread scheduler: On & Off
Lower SPU thread priority: On & Off
Enable SPU loop detection: On
SPU Cache: On
Accurate xfloat: On
SPU Block Size: Safe
VSync: On/Off

Switching to OpenGL helps. The stutters went completely away. Only the performance was lower (as it is expected). Also lowering the internal rendering resolution, the frametime issues are almost completly gone at 150% and get worse from 200% on, my GPU is still hardly used at all at this point.

I've also have a few other games dumped i tried but none have any framepacing issues even at 4k+ rendering resolutions.

PC specs:
Windows 10 64x - Version 1809 
AMD Ryzen 2600x @ stock
16GB RAM @ 3200 MHz
Nvidia GTX 1060  @ stock (Driver Version: 399.24 tried 398 and every 4xx Driver  as well but the 4xx drivers have the fullscreen freeze bug so i went back ) my GPU was set to High Performance in all my tests. I've also tried it on my brothers 1080 TI with the same result.

This is @300% Rendering Resolution as you can see frametime spikes are pretty bad:
![clipboard01](https://user-images.githubusercontent.com/35034841/51729614-c41c6080-2074-11e9-8edf-16dbd809dd7e.png)

And this @150% they are completely gone:
![clipboard02](https://user-images.githubusercontent.com/35034841/51729821-8835cb00-2075-11e9-8caf-d8674f5fa8f3.png)

**Comment by tet666** [comment]
So i was testing different rendering resolutions to see if the issue got worse if i go any higher and at about 500% rendering resolution the frametime issues stop and framepacing is a completely smooth line this is really weird:

![clipboard01](https://user-images.githubusercontent.com/35034841/51743060-d8278880-209b-11e9-95dd-a3ff4a0bdd17.png)

**Comment by kd-11** [comment]
Disable vsync in nvidia control panel and hope for the best. There is no difference in-code that changes based on upscaling resolution. Its just a multiplier. Maybe there is a hook by the driver trying to detect and optimize for 4k rendering (300%). I'd suggest using a slightly different value to avoid this, like cinematic 4k or 1800p.

**Comment by tet666** [comment]
I've tried about every rendering resolution from 150% to 500% by now with and without vsync ( i use Force FIFO present mode in the config for on since driver forced seems to cause additional stuttering) and there is no difference also this wouldn't explain why this only happens in Persona 5 and no other game.

**Comment by tet666** [comment]
As i allrdy wrote in the first post i always use prefer maximum performance mode and this doesn't help at all.

**Comment by ruipin** [comment]
Due to higher upscaling making things worse, I sort of suspect texture cache flushing and PCIe bandwidth is the limiting factor here. We see similar behaviour in Nier with PCIe2.0. Please make sure your GPU is set to PCIe3.0 mode.

**Comment by tet666** [comment]
My card is set to PCIe3.0 mode 
![kfa 1060](https://user-images.githubusercontent.com/35034841/51750545-a4a42880-20b2-11e9-957d-a62ed1de7990.PNG) and this doesn't explain at all why it's  completely smooth at 500% resolution scaling and above..

Oh and since we are just talking about Nier this is it running at 300%::
![111](https://user-images.githubusercontent.com/35034841/51751052-1fba0e80-20b4-11e9-8445-d1b5fbade04a.png) it runs completely fine no matter what rendering resolution i throw at it.

**Comment by ruipin** [comment]
`PCIe x16 3.0 @ x8 3.0`
Doesn't this mean your GPU is only using half your PCIe lanes? This effectively means it has half bandwidth.

**Comment by tet666** [comment]
Dunno why it says x8 i installed driver version 399 since then and it says x16 now.

**Comment by kd-11** [comment]
Check your GPU clocks with afterburner and watch for any dips when the stutter occurs.

**Comment by tet666** [comment]
Nah sorry it stays on max clock the whole time not even small dip.

**Comment by kd-11** [comment]
Vsync now works, maybe try with that enabled.

**Comment by tet666** [comment]
Doesn't help sorry, i'm playing at 500% scaling for the time being which fixes it, my card seems to handle it just fine i'm staying below 100% usage most of the time.

**Comment by kd-11** [comment]
I'm not sure this issue should remain open since there is nothing we can do about it from our side.

**Comment by tet666** [comment]
Sure go ahead and close it if there is nothing you guys can do, ty for your help.

**Comment by tet666** [comment]
https://github.com/RPCS3/rpcs3/pull/6069 actually fixed this for me btw good job.

**Comment by eduardohteixeira** [comment]
i'm having the same behaviour with Demon Souls
frametimes with many spikes but framerate at 60fps
![image](https://user-images.githubusercontent.com/9701812/91616620-6b056480-e95c-11ea-9568-f29f821d84b6.png)
![image](https://user-images.githubusercontent.com/9701812/91616642-7b1d4400-e95c-11ea-8bca-c2c12f60a316.png)
![image](https://user-images.githubusercontent.com/9701812/91616653-81132500-e95c-11ea-828a-b2cfe6c23a58.png)
![image](https://user-images.githubusercontent.com/9701812/91616661-84a6ac00-e95c-11ea-9c2d-842c5eeae051.png)
