### ISSUE TITLE
Fatal Error: Unhandled Win32 Exception 0xC0000005

### ISSUE THREAD

**Issue by yugi1408** [RPCS3/rpcs3#5598]
---------------------------
RPCS3: Fatal Error
---------------------------

			<p style="white-space: nowrap;">
				<p>Unhandled Win32 exception 0xC0000005.<br>
Segfault reading location 0000000035ba0090 at 00000000002cf75c.<br>
Instruction address: 00000000002cf75c.<br>
Function address: 00000000002cf660 (base+0x2bf660).<br>
Module name: 'rpcs3.exe'.<br>
Module base: 0000000000010000.<br>
RPCS3 image base: 0000000000010000.<br>
<br>
				HOW TO REPORT ERRORS:<br>
				<a href='https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support'>https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support</a><br>
				Please, don't send incorrect reports. Thanks for understanding.<br>
			</p>
			
---------------------------
OK   
---------------------------

**Comment by RainbowCookie32** [comment]
Pretty sure this is not issue worthy, go to Discord for support

**Comment by yugi1408** [comment]
ok thanks I just put it there
