### ISSUE TITLE
Issue compiling emulator

### ISSUE THREAD

**Issue by thx4ever** [RPCS3/rpcs3#5601]
I have a problem when trying to compile with Intel C++ Compiler 2019 Update 1

The errors i get is one header only, the other files are fine, no errors at all, if someone can help me out fix this problem, so i can compile it?

This file C:\rpcs3\Utilities\StrFmt.h(314): error : a value of type "u64={uint64_t={unsigned __int64}} *" cannot be used to initialize an entity of type "fmt_args_t<Args...>"
1>  		raw_throw_exception<T>(fmt, type_list, fmt_args_t<Args...>{fmt_unveil<Args>::get(args)...});

1>C:\rpcs3\Utilities\StrFmt.h(293): error : a value of type "u64={uint64_t={unsigned __int64}} *" cannot be used to initialize an entity of type "fmt_args_t<Args...>"
1>  		raw_append(out, fmt, type_list, fmt_args_t<Args...>{fmt_unveil<Args>::get(args)...})

Regards

**Comment by RipleyTom** [comment]
Instructions to build:
https://github.com/RPCS3/rpcs3/blob/master/README.md

Intel C++ compiler is not supported because it lacks some C++ 17 compliance:
https://software.intel.com/en-us/articles/c17-features-supported-by-intel-c-compiler
