### ISSUE TITLE
RSX: Allocation failed! - Star Wars: The Force Unleashed II [NPUB30695]

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5602]
SWFU sits on a load screen with a spinner while spamming this:

E {RSX [0x029ee24]} RSX: ZCULL report queue is overflowing!!
U {PPU[0x100000e] Thread [0x002e7ce4]} sceNp TODO: sceNpManagerGetNpId(npId=*0x136c080) x128

If you wait for about 3-4 mins, it may show the menu splash screen, but freezes immediately. 

"Disable zcull occusion queries" removes the RSX error but still hangs here because of the main issue (get np id message). 

![2019-01-27 10_30_01-rpcs3 0 0 5-7757-587fe421 alpha](https://user-images.githubusercontent.com/20983844/51805130-9b37cf00-221e-11e9-8e88-297a73668b71.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2800374/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by AniLeo** [comment]
That's not an error, that's an unimplemented function that could have nothing to do with the actual issue

**Comment by AniLeo** [comment]
Needs retesting after latest sceNp code improvements

**Comment by legend800** [comment]
No change, still just sits there in a loop, spamming a sceNPManager error with the rotating spinner on screen.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3627304/RPCS3.log.gz)

**Comment by legend800** [comment]
@AniLeo Can you remove the 'needs info' label? Thanks!

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by legend800** [comment]
Change in behavior in latest build. Get this now instead of infinite load:

F {RSX [0x007ef74]} RSX: class std::runtime_error thrown: Allocation failed!

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4265917/RPCS3.log.gz)

**Comment by legend800** [comment]
Game boots now with TSX disabled.

**Comment by legend800** [comment]
Fixed by:  https://github.com/RPCS3/rpcs3/pull/8175
