### ISSUE TITLE
Dead Nation - Unregistered PPU function

### ISSUE THREAD

**Issue by Krusher97** [RPCS3/rpcs3#5606]
The game does not boot in PPU LLVM, stopping with an unregistered PPU function error. 
Opening a new issue as the older issue list was closed.

[Dead Nation.gz](https://github.com/RPCS3/rpcs3/files/2802483/Dead.Nation.gz)
![rpcs3_2019-01-28_16-02-12](https://user-images.githubusercontent.com/25664221/51830562-234cd000-2316-11e9-97bd-f17cec4ca157.png)

**Comment by elad335** [comment]
Duplicate of #2909

**Comment by Krusher97** [comment]
Should I close this and post there?

**Comment by elad335** [comment]
Yes.
