### ISSUE TITLE
Improper rendering of Bioshock water effects

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#5609]
Soon after beginning a game there are rendering issues with water effects such as black borders around raindrops (seen soon before the bathysphere opens) or around the flood streams soon after, as seen in this screenshot:

![pic1](https://user-images.githubusercontent.com/12475371/51869854-c3701c80-2349-11e9-89a3-3493a293c92c.png)

Tested against 587fe421eef80112471320a85c8f6e701c48649b though this issue has been observed since rpcs3 testing began over a year ago.  Issue occurs with either OpenGL or Vulkan renderer.

Test system is linux mint 19.1 with kernel 4.18, Nvidia GTX 1070M and driver 390.77.

Update: As noted below, WCB and Force CPU blit emulation fixes this issue but at a significant performance cost that renders the game unplayable on this test system.

**Comment by sambow23** [comment]
(not related to your problem) You need to update your drivers, they're severely out of date.
https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

**Comment by Shoegzer** [comment]
Thanks, I realize that.  I assume you're using Ubuntu - I've tried installing updated drivers from that PPA in the past in Mint and it never worked properly or caused major issues.  Since it's not related to the problem though, it's not really an issue here.

**Comment by sambow23** [comment]
Not using ubuntu, arch user, though outdated drivers can contribute to graphical issues. If you don't want to use PPAs just install the driver manually.

**Comment by Shoegzer** [comment]
Installing the driver manually contributed to similar issues in the past as well - when it comes to graphics drivers, Ubuntu/Mint have difficulties accepting anything not specifically built to their respective environments.  I'm sure it's been done but it's risky.  Arch is certainly a lot more forgiving in that regard as you can use whatever you'd like.  

In any event are we saying for sure that this isn't an RPCS3 issue?  I thnk we need more info.  If we can get someone else to confirm the issue and report their driver rev. that should help.

**Comment by Shoegzer** [comment]
Just noticed [this](https://youtu.be/K7YnVSJeq7I?t=475) video posted today.  I assume he's using Windows, and while I don't know what Nvidia driver he's using, it's probably more up-to-date than mine.  If I'm right then this seems more likely to be an RPCS3 issue.

**Comment by Shoegzer** [comment]
Update: as of 0.0.6-7857 at least, further graphical corruption is visible (pink haze over almost everything).  Here's the same scene from above as it appears in this build:

![pic](https://user-images.githubusercontent.com/12475371/54166914-50d18100-445f-11e9-8ad3-e24c38775426.png)

WCB and Force CPU blit fixes this issue **and also the water effects noted above**; however at a significant  (>10fps) performance drop to the point of being unplayably slow.

**Comment by kd-11** [comment]
How does it get fixed by CPU blit? Completely correct graphics? Or just the same way it was before?

**Comment by Shoegzer** [comment]
Ah, good question.  With just CPU blit turned **on** and WCB turned **off**, the graphics are the same as before (i.e. broken water effects as in the issue summary screenshot).  As noted though, given that turning both of these on fixes the issue, I *could* close this if you want - I just figured I'd keep it open since CPU blit emulation is a debug feature with dramatic negative performance impact.  Your call.

**Comment by kd-11** [comment]
We can track general issues that need cpu blit in that other ticket. I'm already working on it so it would make testing and reports easier. As such, if it works with the debug option I think we can close this for now.

**Comment by Shoegzer** [comment]
Fantastic, thanks.
