### ISSUE TITLE
Playstation Dualshock 2 controller

### ISSUE THREAD

**Issue by aripisprecer** [RPCS3/rpcs3#5613]

**Comment by nitrohigito** [comment]
_"No description provided."_

Hmm.

**Comment by aripisprecer** [comment]
Hello again,

it seems that my description was not saved here.

So again: i am testing your sofware with a PS 2 Dualshock controller and an usb adapter.

There is a problem with the joystics (only here): i am using the MMJoystick Handler, but the problem is that  up is down and down is up for both joysticks.

I cannot change this config.

My system:
MSI GL72 EQF
Windows 10 pro x64
8 GB ddr4
Intel i7 6700hq
nvidia geforce gtx960M

**Comment by Megamouse** [comment]
then why don't you simply map down to up and up to down ?

**Comment by aripisprecer** [comment]
Because i can't. You can't map the two joysticks :(

**Comment by aripisprecer** [comment]
Sorry, i think i managed it with left analog and right analog.

Excuse me for disturbing. I appreciate you good job 👍
