### ISSUE TITLE
SSX: white screen ingame

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#5615]
SSX is rendered properly until going ingame, when nothing but a white screen is rendered.  Despite what is reported [here](https://forums.rpcs3.net/thread-178995.html) about this issue, it occurs with either the OpenGL or Vulkan renderer - so perhaps this is a regression.

Tested against 25aa5f80a6ea321b4aa72189e120d1e25541fc2a. 

Test system is linux mint 19.1 with kernel 4.18, Nvidia GTX 1070M and driver 390.77.

**Comment by Asinin3** [comment]
I'm not getting this, can you post the RPCS3.log.gz file when you run the game with Vulkan? (You should always include it anyway)

![image](https://user-images.githubusercontent.com/15137035/52066629-d9abf180-2570-11e9-9c1b-c138a7d95498.png)

**Comment by Shoegzer** [comment]
Sure, here it is: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2823637/RPCS3.log.gz)

Here's the white screen I'm getting (though it should be obvious).  I should also note the sound is very choppy as well.

![pic](https://user-images.githubusercontent.com/12475371/52154429-aef79100-2675-11e9-9f7c-9a916829ec08.png)

**Comment by Asinin3** [comment]
Open the config.yml file inside RPCS3's folder and change
 Use GPU texture scaling: **true** to **false** (the setting should almost never be used, you must have an old config file from before we hid the setting with it still enabled.

Otherwise, your drivers are really old and should be updated.

**Comment by Shoegzer** [comment]
Hey thanks.  There's actually a setting for GPU texture scaling within the Debug tab, so no need to change config.yml.  I toggled that off, but it didn't make a difference.

And yeah, the mint 19.1/ubuntu bionic repo supports nvidia 390.77 so definitely a bit old.  I've updated in the past, e.g. from the PPA vs. repo, but it caused major issues - apparently this distro doesn't take kindly to that sort of thing.  So I'm stuck on this one at least for now.

One other issue I observed, perhaps to be reported separately - rpcs3 has a tendency to hang at the loading screen with this game.  I thought I had fixed it before but while testing your suggestion above, it happened again.  I was able to fix it by removing the dev_hdd0/home/00000001/savedata/BLUS308490000A folder, but of course that shouldn't be necessary.

**Comment by 7oxicshadow** [comment]
Out of curiosity have you been able to get into an actual race (not the training part)?

If i start a race the emulator seems to go into an infinity loop of the SPU threads building the same modules over and over again.

The music plays but the game has effectively locked up. All cores on my processor are maxed out at 100% and temperatures start to sky rocket :)

I have tried leaving it for 5 minutes but it doesnt seem to make any difference.

**Comment by Shoegzer** [comment]
Interesting.  The only option available to me is "World Tour" mode.  I select that and get the white screen and the sound starts stuttering badly.  CPU usage is at 95-98% but that's not unusual for RPCS3.  Waiting for 5 minutes doesn't seem to make a difference here either.

**Comment by Shoegzer** [comment]
This is no longer a problem as of commit be6d9af1abef5dd2d9a4bd38c56facf0440358de, so I'm closing this issue.  There are stil massive delays during the paraski training at the beginning, followed by a lockup immediately afterwards, but that's a different issue and I'm not convinced it's limited to SSX.
