### ISSUE TITLE
Can't go to fullscreen after #5612

### ISSUE THREAD

**Issue by weter11** [RPCS3/rpcs3#5617]
Can't change any game from windowed mode to fullscreen and vice versa.
7768 ok.
Ubuntu linux, nvidia GPU.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2818856/RPCS3.log.gz)

**Comment by kd-11** [comment]
If you do build locally, test with https://github.com/RPCS3/rpcs3/pull/5618. It will be merged shortly.

**Comment by weter11** [comment]
I'm sorry, but Vulkan still not work as it should. Only OpenGL.
And I first time see options: 
1) Boot with custom configuration;
2) Boot with global configuration.
In 7772 only "Boot".

**Comment by AniLeo** [comment]
Those options were added on the config PR that was merged today, unrelated to this issue

**Comment by kd-11** [comment]
Fullscreen works fine on ubuntu with the latest master (0.0.6-7774). I checked it myself. This issue was specifically about the fullscreen issue and since that is fixed, this issue is closed. Other issues should be reported separately.

**Comment by weter11** [comment]
I thought it was 7773.
Yea it work as it should.
Thanks.
