### ISSUE TITLE
CPU settings: Enable Thread Scheduler

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#5621]
I noticed that in the Description of the option Enable Thread Scheduler, it says that this function is only implemented on Ryzen CPUs. Is it possible for RPCS3 to gray-out the box if the user does not have a Ryzen CPU?

For example, the Accurate xFloat box is grayed-out when LLVM Recompiler is not selected, could you do the same for the Enable Thread Scheduler if a Ryzen CPU is not detected?

**Comment by vietnam13231** [comment]
I would be against it. I have i5-4690 and it gives me quite a lot of performance boost in pretty much every game I have. I think that description is simply very outdated.

**Comment by AniLeo** [comment]
Lol... There is no magic code, thread scheduler only runs on AMD CPUs.
https://github.com/RPCS3/rpcs3/blob/25aa5f80a6ea321b4aa72189e120d1e25541fc2a/Utilities/Thread.cpp#L1933

**Comment by vietnam13231** [comment]
P5:
with "Enable Thread Scheduler"
![p5on](https://user-images.githubusercontent.com/16107604/53199262-e5924d00-361e-11e9-94b7-df7829191423.jpg)

without "Enable Thread Scheduler"
![p5off](https://user-images.githubusercontent.com/16107604/53199282-f642c300-361e-11e9-977f-b94ae0f44166.jpg)

i5-4690 @ 3.5GHz
GTX 1080
8GB RAM
Win10x64 1809

**Comment by AniLeo** [comment]
Doesn't make sense with it being disabled on Intel, I get the same performance with or without thread scheduler

@kd-11

**Comment by kd-11** [comment]
I'd need the two logs for p5 with scheduler enabled and disabled, just to be sure. I could've sworn we disabled it for intel CPUs.

**Comment by vietnam13231** [comment]
Well, help yourself.
[P5 on.zip](https://github.com/RPCS3/rpcs3/files/2895643/P5.on.zip)
[P5 off.zip](https://github.com/RPCS3/rpcs3/files/2895645/P5.off.zip)

**Comment by Hasster1** [comment]
Wait, if it's not meant for intel CPUs at all, then how the hell it's even working on intel CPUs?

**Comment by AniLeo** [comment]
No idea

**Comment by kd-11** [comment]
This looks to be yet another windows bug. Which intel CPUs seem to be affected? There must be something common with all of them that causes the problem. For intel CPUs SetThreadAffinity is called with all 1s for the available processors, it should not interfere with scheduling for windows.

**Comment by vietnam13231** [comment]
Well, I written it before, it was i5-4690. And it really may have been windows bug, because after changing CPU that problem/bug(?) disappeared. So I'm not able to give any other info in this topic.

**Comment by kd-11** [comment]
Request to reopen if still an issue with current windows versions.
