### ISSUE TITLE
Time and Eternity [NPUB31189] - Black lines around sprites

### ISSUE THREAD

**Issue by Krusher97** [RPCS3/rpcs3#5622]
The character sprites in the game have frames where the sprite is surrounded by black lines even at native resolution with strict rendering enabled.

Video of the issue : https://drive.google.com/open?id=19jgNkvZ88g6HtJijeDfY65R072tS4Bp1
Log : [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2820725/RPCS3.log.gz)

**Comment by benderscruffy** [comment]
time to update the issue

**Comment by Krusher97** [comment]
![rpcs3_2020-02-21_18-39-46](https://user-images.githubusercontent.com/25664221/75037291-d5cf7200-54d9-11ea-9277-067dd77d289b.jpg)

Seems to be fixed now
