### ISSUE TITLE
[Feature Request] Startup screen (yuzu-like)

### ISSUE THREAD

**Issue by QuaiGoner** [RPCS3/rpcs3#5624]
So is that even possible? Making a startup screen like yuzu has where it will show SPU/PPU compilation process with some nice animation in the background, maybe PS3 ribbon with RPCS3 logo in the lower right corner? Ready to take stones in my side because all i can do is propose stuff like that. Thanks!

**Comment by niko1point0** [comment]
I like this idea, I hope they implement it

**Comment by AniLeo** [comment]
Overlay already exists for shader compilation. PPU/SPU compilation at startup happens before the GSFrame is created, don't think it's feasible as is.

**Comment by QuaiGoner** [comment]
Thank you for explanation, do i need to close the issue or it can stay?

**Comment by niko1point0** [comment]
Stay, because somebody might figure out a way how to do it in the future

**Comment by dio-gh** [comment]
Closeable, implemented.
