### ISSUE TITLE
Open custom config folder don't work very well on 0.0.6-7776

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5625]
Is any of the other options executing some different command?
I am using an addon for the explorer called QTTabBar(make explorer as tabbed browser)which adds tons of features to the explorer but:

Open Install Folder - works fine
Open Data Folder - works fine
Open Custom Config Folder - works fine but only if I did not save my custom settings(which meants the option will open the old location)

If I try to open the new location,the current tab is renamed and I just see the loading cursor but nothing happens
If I close the window and open it again,then I see that the location is opened
The new location is also opening fine if I first close the window or if I switch to another tab and then switch to the custom_config tab

Is the code used to open "config\custom_configs" any different?

**Comment by Megamouse** [comment]
it opens both locations if you have an old and a new config file.
So your weird extension probably cant handle it at the same time

**Comment by vsub** [comment]
Ok that explains it but was the second line of your post nessasery

**Comment by Megamouse** [comment]
yes
