### ISSUE TITLE
Shank 2: crash on load

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#5626]
Shank 2 crashes RPCS3 entirely during initial game load.  Logfile: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2823653/RPCS3.log.gz) and screenshot:

![pic1](https://user-images.githubusercontent.com/12475371/52159074-56d18680-2697-11e9-9f94-c0ba08f984e2.png)

Tested against 25aa5f8, though this has occurred since testing began over a year ago.  Note that at one point it has apparently worked (see [here](https://forums.rpcs3.net/thread-199551.html)) though I never observed it working, so I'm assuming this is now a regression.

Test system is linux mint 19.1 with kernel 4.18, Nvidia GTX 1070M and driver 390.77.

**Comment by AniLeo** [comment]
Needs a backtrace

**Comment by Yahfz** [comment]
![image](https://user-images.githubusercontent.com/17715080/64064965-4b6b1d00-cbde-11e9-80b9-a07897df0696.png)
Game works fine on Master (8620). This issue can be closed.

**Comment by Shoegzer** [comment]
@AniLeo please reopen, the report above is not accurate - the game still crashes at least on Linux systems.  I changed the title.

**Comment by Leopard1907** [comment]
Update your driver. That is too old.

https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

**Comment by Shoegzer** [comment]
@Leopard1907 I just changed my post while editing earlier to reflect that I'm using updated Nvidia drivers.
