### ISSUE TITLE
Rpcs3: Fatal Error 0.0.6

### ISSUE THREAD

**Issue by bolsonaro18** [RPCS3/rpcs3#5628]
Getting this error after updating to the 0.0.6 version on all games i have.
![rpcs3error](https://user-images.githubusercontent.com/29050273/52164984-a5a40e00-26e1-11e9-8d0b-7d8d9371a24f.png)

It didn't generate a log file because i can't get in game.

Config:
Windows 10 64-bit
GeForce GTX 1050
i5-7400@ 3GHZ
16GB RAM

**Comment by AniLeo** [comment]
Without a backtrace there's nothing to see, furthermore this is a support request and therefore should be asked in the appropriate channels.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
