### ISSUE TITLE
Auto CI build retry on failure to build latest merges

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#5638]
When a pull request is merged, its build is shown on the website available for downloading.
Currently, If that build fails due to random events, the build is lost until the next pull request is merged.
We need a system that will notify automatically the CI to rebuild on failure, waiting for it succeed and fetch it into the website.

**Comment by Megamouse** [comment]
is this still an issue ?

**Comment by Megamouse** [comment]
closing as outdated and inactive
