### ISSUE TITLE
Remove OpenGL calls that require 'Compatibility' profile

### ISSUE THREAD

**Issue by xsacha** [RPCS3/rpcs3#564]
The project currently uses several calls that only work on a compatibility profile.
Opensource drivers on Linux and drivers on Mac OSX only expose a Core profile. Even though many things in compatibility will work, they will also provide an error.

Example of some invalid calls I encountered:
glEnable(TEXTURE_2D)
glDrawArrays(GL_QUADS, 0, m_draw_arrays_count);
Enable(m_set_alpha_test, GL_ALPHA_TEST);
Enable(m_set_depth_bounds_test, GL_DEPTH_BOUNDS_TEST_EXT);
Enable(m_set_blend || m_set_blend_mrt1 || m_set_blend_mrt2 || m_set_blend_mrt3, GL_BLEND);
Enable(m_set_logic_op, GL_LOGIC_OP);
Enable(m_set_point_sprite_control, GL_POINT_SPRITE);
Enable(m_set_specular, GL_LIGHTING);
Enable(m_set_line_stipple, GL_LINE_STIPPLE);
Enable(m_set_polygon_stipple, GL_POLYGON_STIPPLE);
glPolygonMode(GL_FRONT, m_front_polygon_mode);

It's likely this fixed-function code would slow done the graphics code anyway.

**Comment by tambry** [comment]
I think these have been removed now. Reopen if still an issue.
