### ISSUE TITLE
Setting default resolution above 1280x1080 causes NieR to freeze

### ISSUE THREAD

**Issue by Skiggl** [RPCS3/rpcs3#5647]
BLUS30481

Was noticing the game failed to launch with my default settings (froze on a white screen instantly) so played around with a custom config and found that this requires the default res at 1280x720 to run at all.

Figure it's worth noting for anyone else who runs into this to save em some time.

**Comment by mavethee** [comment]
@Skiggl
Default resolution should be set to 1280 x 720. You must using Resolution Scaling, leave Resolution tab alone, okay?

**Comment by 13xforever** [comment]
Using resolutions that are not supported by the game will cause various issues by definition.

This issue is useless and doesn’t even meet the requirements for a proper report, please close it.

**Comment by AniLeo** [comment]
Obviously running games at base resolutions they don't support won't work properly
