### ISSUE TITLE
Make resolution setting more idiot-proof

### ISSUE THREAD

**Issue by 13xforever** [RPCS3/rpcs3#5648]
Currently a lot or people change resolution to the highest one without reading a single word, which often breaks games.

Hereby I propose UI-only changes that should drastically reduce the misconfiguration accidents:
- Make `Resolution` in global settings disabled, always defaulting to 720p
- Make `Resolution` in custom game settings to only show resolutions supported by the game
    - Don't forget patches
- Optionally add a check on game boot that the selected resolution is supported
    - Optionally add a new config parameter to disable said check on boot

**Comment by vsub** [comment]
>     * Make `Resolution` in custom game settings to only show resolutions supported by the game
I was thinking about the same thing when I read the other issue about using non supported resolution in Nier

The question is,is there is any good reason to show resolutions not supported by the game to begin with(not just in the custom config)

Is there is any difference between using supported resolution + scaling and highest supported resolution +scaling
Can anyone actually run 720p at 800% scaling

And btw I don't know if this is a bug or that's just how the slider works but settings any non 720p resolution and moving the slider shows a resolution based on 720p

1920x1080 at 101% shows 1292x727
I don't know how to check if the game is actually running at the correct resolution
For example 1920x1080 with 150% scaling,will it run at 1920x1080(this is what the slider shows)or at 2880x1620

**Comment by Hasster1** [comment]
Maybe add a setting in debug, that will allow to make any resolution in any games for debug purposes?

**Comment by kd-11** [comment]
There is a much better way of doing this. Implementation details are already planned just busy with other parts right now. The current single resolution method is very hacky and needs to be rewritten.

**Comment by Megamouse** [comment]
I can easily filter these for any sfo that has a resolution setting.
But this won't be useful when configuring a game data entry for example.

Also there are plans to check for valid resolutions when setting the HLE video parameters for the game and using one of the supported resolutions as fallback (which would practically always be 720p).

Btw the resolution slider is based on 720p, which is also stated in the description of that setting when hovering over it. So what you see is what you get.

**Comment by kd-11** [comment]
In truth we should return all the resolutions as available since the virtual AV device can output at any configuration. The game should just pick the resolution that it wants from the list, the connection between av and the backends is already mostly done anyway. This should be added as an "auto" setting instead of allowing one resolution and/or restricting based on sfo.

**Comment by AniLeo** [comment]
Currently only resolutions supported by the game are shown, is this issue solved?

**Comment by 13xforever** [comment]
Yes, it is already much better, and we can wait for the proper resolution handling now.
