### ISSUE TITLE
BROKEN SOUND BLES02070

### ISSUE THREAD

**Issue by SrAle** [RPCS3/rpcs3#5653]
KH2FM sound explodes like half speed or less when attacking **a lot of enemies**(in other sites works just fine). 
My config:
Intel Core i5-8250U @3.37GHz 
7.88GiB RAM 
GTX 1050
HDD: HGST HTS5410 (5400RPM 1TB) 
Windows 10 (1809) Home 64 bits 

RPCS3 build 0.0.6-7795
PPU: LLVM 
SPU: ASMJIT 
RENDERER: VULKAN
RES: 1920x1080
XAudio2
Video: https://youtu.be/RIs9ejWwBRs
Log here: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2850937/RPCS3.log.gz)

Thanks a lot, keep working on ^_^

**Comment by AniLeo** [comment]
This is just a general performance issue due to a low performance CPU, there's no specific issue here
