### ISSUE TITLE
Regression: Demon's Souls [BLUS30443] - Infinite loading (#5623)

### ISSUE THREAD

**Issue by Parthorisian** [RPCS3/rpcs3#5654]
Build 7795(PR#5623) - infinite loading screen, caused by attempting to warp to Tower ofLatria/World3-1, SPU AsmJiT b7795 / [LLVM b7795](https://github.com/RPCS3/rpcs3/files/2855855/RPCS7795.zip) - that doesnt matter

Build 7793(PR#5643) - OK with SPU [AsmJiT b7793](https://github.com/RPCS3/rpcs3/files/2860641/RPCS7793.zip) / [LLVM b7793](https://github.com/RPCS3/rpcs3/files/2855856/RPCS7793.zip)

**Comment by AniLeo** [comment]
#5645 already followed up with a regression fix, needs retesting

**Comment by elad335** [comment]
Its a regression from #5623.

**Comment by Parthorisian** [comment]
closed as fixed#5667
