### ISSUE TITLE
Rampage World Tour [NPUB30003] issue

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5658]
on first time the game boot and i play it and was fine on next time it show 

! {RSX [0x0004248]} RSX: Add program (vp id = 0, fp id = 1)
F {PPU[0x1000006] Thread (Thread 1) [0x0001791c]} MEM: Access violation reading location 0x0
S {RSX Decompiler Thread} RSX: New program compiled successfully
W {cellAudio Thread} cellAudio: Audio backend stopped unexpectedly, likely due to a buffer underrun

 i try to remove the game and clear PPU Cache and SPU Cache and it's same thing 

the first time when work fine the log file 

[RPCS3 Rampage World Tour [NPUB30003].log.gz](https://github.com/RPCS3/rpcs3/files/2862315/RPCS3.Rampage.World.Tour.NPUB30003.log.gz)

**Comment by AniLeo** [comment]
Missing log file for the bad run

**Comment by uaqlover** [comment]
Sorry about that 

here the log file of the bad run 

[RPCS3 bad run.log.gz](https://github.com/RPCS3/rpcs3/files/2866714/RPCS3.bad.run.log.gz)

**Comment by uaqlover** [comment]
fixed in https://github.com/RPCS3/rpcs3/pull/5675
