### ISSUE TITLE
Vulkan crashes with VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5659]
RPCS3 v0.0.6-7802-56e24f89 Alpha | HEAD

fixed

PAC-MAN and the Ghostly Adventures 2 [NPUB31535]
Eat Lead: The Return of Matt Hazard [BLES00495]
Matt Hazard: Blood Bath and Beyond [NPUB30102]
Shaun White Skateboarding [NPUB31269]
Ben 10™ Galactic Racing [BLUS30822] 
Madagascar 3 [BLES01624] 

still have issue

Sonic & All-Stars Racing Transformed™ [BLES01646]

 opengl

F {RSX [0x0000000]} RSX: class std::runtime_error thrown: Verification failed:

(in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\glhelpers.h:899)

Vulkan

F {RSX [0x00165b8]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)

(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1278)

---

**Comment by uaqlover** [comment]
Now I don't know how but in openGL the works 

![fps_ 11 42 _ opengl _ 0 0 6-7793 _ pac-man and the ghostly adventures 2 npub31535 2_15_2019 12_47_32 am](https://user-images.githubusercontent.com/45731484/52816940-cbef8380-30bb-11e9-8791-2ea2827e6ca3.png)


but still problem in Vulkan 

[RPCS3 Vulkan.log.gz](https://github.com/RPCS3/rpcs3/files/2866757/RPCS3.Vulkan.log.gz)

**Comment by uaqlover** [comment]
same problem 

Eat Lead: The Return of Matt Hazard [BLES00495]

F {RSX [0x040b6c8]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1278)

**Comment by uaqlover** [comment]
same problem

Matt Hazard: Blood Bath and Beyond [NPUB30102]
[RPCS3 Matt1.log.gz](https://github.com/RPCS3/rpcs3/files/2883785/RPCS3.Matt1.log.gz)


F {RSX [0x045904c]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1278)

**Comment by uaqlover** [comment]
same problem

Sonic & All-Stars Racing Transformed™ [BLES01646]
[RPCS3 Sonic & All-Stars Racing Transformed™ [BLES01646].log.gz](https://github.com/RPCS3/rpcs3/files/2883815/RPCS3.Sonic.All-Stars.Racing.Transformed.BLES01646.log.gz)

F {RSX [0x1442970]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1278)

**Comment by uaqlover** [comment]
same problem

Shaun White Skateboarding [NPUB31269]
[RPCS3 Shaun White Skateboarding [NPUB31269].log.gz](https://github.com/RPCS3/rpcs3/files/2883879/RPCS3.Shaun.White.Skateboarding.NPUB31269.log.gz)

F {RSX [0x006f584]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1278)

**Comment by kd-11** [comment]
Stop renaming the title every time you see a crash. It spams developer's emails notifications.

**Comment by uaqlover** [comment]
OK sorry about that

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/5741. It doesn't have any specific fix for this generic error but its likely some of these have gotten fixed over time. Device lost error is nearly meaningless, just means driver crashed.

**Comment by uaqlover** [comment]
Shaun White Skateboarding [NPUB31269] - fixed

but has Regression since i last test it in 0.0.6-7793

https://drive.google.com/file/d/1sO5MkS78KZu5gPU9xxK3jym8Nx7B0j0b/view?usp=sharing

![FPS_ 35 34 _ Vulkan _ 0 0 6-92eb5413-fbo_fixes _ Shaun White Skateboarding  NPUB31269  19_03_2019 3_57_18 PM](https://user-images.githubusercontent.com/45731484/54648313-ffc71b80-4a62-11e9-9990-d3ec3481feba.png)


PAC-MAN and the Ghostly Adventures 2 [NPUB31535] - fixed with performance improvement

![FPS_ 29 60 _ Vulkan _ 0 0 6-92eb5413-fbo_fixes _ PAC-MAN and the Ghostly Adventures 2  NPUB31535  19_03_2019 4_00_56 PM](https://user-images.githubusercontent.com/45731484/54647641-80384d00-4a60-11e9-8ad6-b9b62ce019ea.png)

Sonic & All-Stars Racing Transformed™ [BLES01646] - it show the issue with other line 

F {RSX [0x144a4dc]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1297)

[RPCS3 race.log.gz](https://github.com/RPCS3/rpcs3/files/2985874/RPCS3.race.log.gz)

Matt Hazard: Blood Bath and Beyond [NPUB30102] - fixed with performance improvement

![FPS_ 59 74 _ Vulkan _ 0 0 6-92eb5413-fbo_fixes _ Matt Hazard_ Blood Bath and Beyond  NPUB30102  19_03_2019 4_12_40 PM](https://user-images.githubusercontent.com/45731484/54648018-f0939e00-4a61-11e9-8d4a-955cf54654d2.png)

Eat Lead: The Return of Matt Hazard [BLES00495] fixed with performance improvement

![FPS_ 29 91 _ Vulkan _ 0 0 6-92eb5413-fbo_fixes _ Eat Lead_ The Return of Matt Hazard  BLES00495  19_03_2019 4_19_19 PM](https://user-images.githubusercontent.com/45731484/54648270-d7d7b800-4a62-11e9-8a5d-41fd6834f493.png)

**Comment by uaqlover** [comment]
Ben 10™ Galactic Racing [BLUS30822] fixed also 

![FPS_ 29 97 _ Vulkan _ 0 0 6-92eb5413-fbo_fixes _ Ben 10™ Galactic Racing  BLUS30822  19_03_2019 7_41_36 PM](https://user-images.githubusercontent.com/45731484/54655467-475ba080-4a7f-11e9-8142-0ae11037c528.png)

RPCS3 v0.0.6-7881-3ef16bee Alpha | HEAD

![58555](https://user-images.githubusercontent.com/45731484/54655589-bc2eda80-4a7f-11e9-9195-a6cc6d4896f7.png)

**Comment by uaqlover** [comment]
Madagascar 3 [BLES01624] fixed also

![FPS_ 29 96 _ Vulkan _ 0 0 6-92eb5413-fbo_fixes _ Madagascar 3  BLES01624  19_03_2019 9_53_30 PM](https://user-images.githubusercontent.com/45731484/54660007-a6c2ac00-4a91-11e9-8238-587eee196994.png)
![FPS_ 29 89 _ Vulkan _ 0 0 6-92eb5413-fbo_fixes _ Madagascar 3  BLES01624  19_03_2019 9_51_10 PM](https://user-images.githubusercontent.com/45731484/54660011-aaeec980-4a91-11e9-917a-7e641affa74c.png)

RPCS3 v0.0.6-7881-3ef16bee Alpha | HEAD

![668](https://user-images.githubusercontent.com/45731484/54660021-b4783180-4a91-11e9-8658-bda02bae0001.png)

@kd-11 or i update the main issue only and delete another posts

**Comment by uaqlover** [comment]
fixed by https://github.com/RPCS3/rpcs3/pull/5741

**Comment by jonyvx** [comment]
same problem 

game: Eat Lead matt hazard

F {RSX [0x0010000]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1051)

**Comment by Xenthria** [comment]
Same issue as above:

Game: Rune Factory: Tides of Destiny

RPCS3 Version: 0.0.6-6e89e4eb Alpha
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3490354/RPCS3.log.gz)


F {RSX [0x044f9b4]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1051)

**Comment by Parotaku** [comment]
Same issue with many games, Vulkan only:

Game: Catherine (Japan version)

RPCS3 v0.0.7-8674-cb66d056 Alpha | HEAD | Firmware version: 4.83
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3592325/RPCS3.log.gz)


RPCS3 Version: 0.0.6-6e89e4eb Alpha
RPCS3.log.gz

 {RSX [0x02ae680]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:1052)

**Comment by kd-11** [comment]
Turing is pissy about some stuff I was doing to keep performance on NVIDIA cards from going to shit; just use "High Precision Z" option in your config file for the moment until a workaround is implemented.

**Comment by NogNoa** [comment]
same problem, with vulkan

Game: Resistance: Fall of Man™ [NPEA00430]

RPCS3 v0.0.23-14088-698c3415 Alpha
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9439334/RPCS3.log.gz)

F {RSX [0x28573c4]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\sync.cpp:214[:5], in function wait_for_event)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error)

**Comment by Darkhost1999** [comment]
Your log was empty here too btw.
