### ISSUE TITLE
XImput

### ISSUE THREAD

**Issue by wowyswag** [RPCS3/rpcs3#5661]
The XImput option is not reading my device. I've searched all over for the solution but I don't know what's causing it. The controller is properly connected in device manager. I don't know what to do.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
