### ISSUE TITLE
MotoGP 09/10 [BLES00756] and CRASH COMMANDO Fatal Error 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5662]
ingame it show 

same thing opengl or Vulkan

![12333](https://user-images.githubusercontent.com/45731484/52832089-839e8880-30f0-11e9-80dd-54411e9d5c5a.png)

[RPCS3 MotoGP 0910 [BLES00756].log.gz](https://github.com/RPCS3/rpcs3/files/2867680/RPCS3.MotoGP.0910.BLES00756.log.gz)

and CRASH COMMANDO™ [NPUA80216] also is same ingame

![fps_ 61 05 _ vulkan _ 0 0 6-7802 _ crash commando npua80216 2_15_2019 7_26_06 am](https://user-images.githubusercontent.com/45731484/52832715-307a0500-30f3-11e9-9df7-20f0fda599a9.png)
[RPCS3 CRASH COMMANDO™.log.gz](https://github.com/RPCS3/rpcs3/files/2867717/RPCS3.CRASH.COMMANDO.log.gz)

**Comment by AniLeo** [comment]
Log shows pirated game, closing issue
