### ISSUE TITLE
Since #5635 the custom background(shaders loading)is shows as black and white

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5664]
https://github.com/RPCS3/rpcs3/pull/5635
Vulkan only and it happens on any game but there are some things I need to mention

1.I am not using the latest nvidia drivers so I don't know if this is causing the problem
2.It doesn't happen while using my Intel GPU

**Comment by Patkos96** [comment]
Same here, but only in full screen mode, when it's windowed it displays the icon correctly.
OpenGL does work here too.

Ryzen 5 2600
GTX680
399.24 driver (newer causes bad shadows in some games and brightness issues, on normal, non-emulator PC games)

**Comment by vsub** [comment]
Strange,it's black and white in windowed and fullscreen here

**Comment by vsub** [comment]
Not sure what exactly cased this but after I update my drivers to the latest,the image is displayed correctly so solved I guess
