### ISSUE TITLE
Linux - Gamepad not configurable (Greyed out)

### ISSUE THREAD

**Issue by 7oxicshadow** [RPCS3/rpcs3#5671]
I am using the latest appimage with the following build info:

RPCS3 Verison: 0.0.6-7807-4c72f7c1

I am using xboxdrv as the joypad driver and RPCS3 does detect the pad fine. I can go in game an play fine but the L2 / R2 buttons are not mapped correctly. If I go into the gamepad settings screen, the pad is listed but all of the buttons remain greyed out so I cannot reconfigure...

As a process of elimination I have tried using the system default xpad driver. In this case the buttons are already mapped correctly and do not require any configuration BUT if I choose to goto the configuration screen anyway the buttons are still greyed out UNTIL I press any button or push any stick on the controller and then all configuration buttons become available.

![gamepad](https://user-images.githubusercontent.com/10350138/52967324-a6a39380-33a1-11e9-8698-f7c3b133ee0e.png)

Specs:

Fedora 28
6700K @ 4.5
32GB Ram
GTX 1070

Tagging @Megamouse

**Comment by 7oxicshadow** [comment]
Oops. Some additional information:

I am using a wireless 360 module (assume it is a cheap Chinese clone) and an official 360 pad.

**Comment by Megamouse** [comment]
What does the log say

**Comment by 7oxicshadow** [comment]
So it looks like the appimage does not create a log file (or if it does it is lost in the virtual appimage file system).

If i look at the log window within RPCS3 all i get is:
```
RPCS3 v0.0.6-7807-4c72f7c1 Alpha | HEAD
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz | 8 Threads | 31.36 GiB RAM | AVX+ | TSX
```

I have made a discovery though that might explain so of what is going on. When I launch xboxdrv I launch it with command line options to allow 4 controller configurations to be loaded.

```
xboxdrv --daemon --dbus system --device-name "Xbox Gamepad (userspace driver)" --led 2 --force-feedback -c ~/xboxdrv_configs/rpcs3.xboxdrv \
        --next-controller --device-name "Xbox Gamepad (userspace driver 1)" --led 3 --force-feedback -c ~/xboxdrv_configs/rpcs3.xboxdrv \
        --next-controller --device-name "Xbox Gamepad (userspace driver 2)" --led 4 --force-feedback -c ~/xboxdrv_configs/rpcs3.xboxdrv \
        --next-controller --device-name "Xbox Gamepad (userspace driver 3)" --led 5 --force-feedback -c ~/xboxdrv_configs/rpcs3.xboxdrv &
```

Within RPCS3 under the Devices section I see 4 controllers available even though only one wireless connector is currently powered and synced. By default I select "Xbox Gamepad (userspace driver)". I have found that the buttons remain greyed out until I connect all 4 controllers then they become unlocked **BUT** only when I touch anything on the 4th joypad.

It also appears that no matter which Xbox Gamepad I choose from the dropdown box for devices, It will only respond to pad 4?

Is the problem caused by the fact that 1 usb device is providing 4 controller inputs?

**Comment by 7oxicshadow** [comment]
The wireless device is one of these (there are many clones but it will give you an idea)

https://www.amazon.com/Microsoft-Xbox-Wireless-Receiver-Windows/dp/B000HZFCT2/ref=sr_1_5?keywords=xbox+360+wireless+pc+adapter&qid=1550514097&s=gateway&sr=8-5

The command line that I use for RPCS3 works fine for other emulators. All controllers are independent of each other.

**Comment by 7oxicshadow** [comment]
Just tested xpad using the 4 controllers simultaneously.

It does the same thing. There are 4 pads listed under devices but no matter which you select, it will only listen to the input from pad 4.

**Comment by Megamouse** [comment]
Please try again

**Comment by 7oxicshadow** [comment]
The buttons are no longer greyed out but the interface will still only listen to pad 4.

I have confirmed that if I set controller 1 to be evdev pad 2 and start the emulator it does use pad 2 as the primary controller in game so the drop down box is at least working as expected in the QT interface.

Based on my testing I think that it is the QT interface where the problem resides. Trying to bind a button or moving the joystick to check the deadzones only responds to pad 4 on all 4 tabs within the QT interface regardless of which pad is selected in the drop down box.

**Comment by 7oxicshadow** [comment]
Video to help explain the problem.

https://youtu.be/I7y-7cZxTdc

**Comment by Megamouse** [comment]
I've added the device name to the log notice that appears when you press a button in the pad settings dialog.
If those appear to be correct then I think this is an evdev/xboxdrv issue or the way you use it and not ours.
(Unless it works on other similar evdev implementations)

**Comment by 7oxicshadow** [comment]
Thanks for adding the log message. A log message is shown but only when anything on pad 4 is pressed. None of the other pads do anything. The name of the device that shows in the log entry is what ever is currently set in the drop down box even though I am only using pad 4.

I will attach some evdev info incase you spot something that might explain things.
```

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="Xbox Gamepad (userspace driver)"
P: Phys=
S: Sysfs=/devices/virtual/input/input49
U: Uniq=
H: Handlers=event24 js0 
B: PROP=0
B: EV=20000b
B: KEY=7fdb000000000000 0 0 0 0
B: ABS=3001b
B: FF=13f870000 0

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="Xbox Gamepad (userspace driver 1)"
P: Phys=
S: Sysfs=/devices/virtual/input/input50
U: Uniq=
H: Handlers=event25 js1 
B: PROP=0
B: EV=20000b
B: KEY=7fdb000000000000 0 0 0 0
B: ABS=3001b
B: FF=13f870000 0

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="Xbox Gamepad (userspace driver 2)"
P: Phys=
S: Sysfs=/devices/virtual/input/input51
U: Uniq=
H: Handlers=event26 js2 
B: PROP=0
B: EV=20000b
B: KEY=7fdb000000000000 0 0 0 0
B: ABS=3001b
B: FF=13f870000 0

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="Xbox Gamepad (userspace driver 3)"
P: Phys=
S: Sysfs=/devices/virtual/input/input52
U: Uniq=
H: Handlers=event27 js3 
B: PROP=0
B: EV=20000b
B: KEY=7fdb000000000000 0 0 0 0
B: ABS=3001b
B: FF=13f870000 0
```

If you can not see anything obvious I will stick with using a single pad for the time being and when the project will build on a newer compiler I will add some extra debug in to see if I can spot anything.

**Comment by 7oxicshadow** [comment]
Forgot to mention. I believe Dolphin uses evdev and all 4 pads work fine when using that.

**Comment by Megamouse** [comment]
It seems like they use udev to enumerate the devices while we kinda just iterate over the /dev/input/ entries.

**Comment by 7oxicshadow** [comment]
Here is the output of a udev monitor in case it helps. It shows how the usb addressing works if nothing else (Note: The log will show connection and disconnection) :

```
[toxicshadow@PC_1 ~]$ udevadm monitor
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[11875.892484] add      /devices/virtual/input/input109 (input)
KERNEL[11875.892580] add      /devices/virtual/input/input109/event24 (input)
KERNEL[11875.892624] add      /devices/virtual/input/input109/js0 (input)
KERNEL[11875.892655] add      /devices/virtual/input/input110 (input)
KERNEL[11875.892679] add      /devices/virtual/input/input110/event25 (input)
KERNEL[11875.892700] add      /devices/virtual/input/input110/js1 (input)
KERNEL[11875.892728] add      /devices/virtual/input/input111 (input)
KERNEL[11875.892749] add      /devices/virtual/input/input111/event26 (input)
KERNEL[11875.892771] add      /devices/virtual/input/input111/js2 (input)
KERNEL[11875.892795] add      /devices/virtual/input/input112 (input)
KERNEL[11875.892812] add      /devices/virtual/input/input112/event27 (input)
KERNEL[11875.892829] add      /devices/virtual/input/input112/js3 (input)
UDEV  [11875.894264] add      /devices/virtual/input/input109 (input)
UDEV  [11875.894586] add      /devices/virtual/input/input110 (input)
UDEV  [11875.895537] add      /devices/virtual/input/input112 (input)
KERNEL[11875.895586] bind     /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0 (usb)
KERNEL[11875.895645] bind     /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2 (usb)
KERNEL[11875.895678] bind     /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.4 (usb)
KERNEL[11875.895713] bind     /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.6 (usb)
UDEV  [11875.896503] add      /devices/virtual/input/input109/js0 (input)
UDEV  [11875.896625] add      /devices/virtual/input/input110/js1 (input)
UDEV  [11875.897174] bind     /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0 (usb)
UDEV  [11875.897448] add      /devices/virtual/input/input111 (input)
UDEV  [11875.898630] add      /devices/virtual/input/input112/js3 (input)
UDEV  [11875.899177] add      /devices/virtual/input/input111/js2 (input)
UDEV  [11875.899207] bind     /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2 (usb)
UDEV  [11875.899237] bind     /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.6 (usb)
UDEV  [11875.899623] bind     /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.4 (usb)
UDEV  [11875.928635] add      /devices/virtual/input/input111/event26 (input)
UDEV  [11875.928671] add      /devices/virtual/input/input110/event25 (input)
UDEV  [11875.932602] add      /devices/virtual/input/input112/event27 (input)
UDEV  [11875.933460] add      /devices/virtual/input/input109/event24 (input)
KERNEL[11888.393210] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0 (usb)
KERNEL[11888.393305] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2 (usb)
KERNEL[11888.393426] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.4 (usb)
KERNEL[11888.393507] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.6 (usb)
KERNEL[11888.393684] remove   /devices/virtual/input/input112/event27 (input)
UDEV  [11888.395871] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0 (usb)
UDEV  [11888.395919] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2 (usb)
UDEV  [11888.396644] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.4 (usb)
UDEV  [11888.397305] remove   /devices/virtual/input/input112/event27 (input)
UDEV  [11888.397598] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.6 (usb)
KERNEL[11888.409015] remove   /devices/virtual/input/input112/js3 (input)
UDEV  [11888.411216] remove   /devices/virtual/input/input112/js3 (input)
KERNEL[11888.429884] remove   /devices/virtual/input/input112 (input)
KERNEL[11888.429910] remove   /devices/virtual/input/input111/event26 (input)
UDEV  [11888.430653] remove   /devices/virtual/input/input112 (input)
UDEV  [11888.431053] remove   /devices/virtual/input/input111/event26 (input)
KERNEL[11888.439806] remove   /devices/virtual/input/input111/js2 (input)
UDEV  [11888.440729] remove   /devices/virtual/input/input111/js2 (input)
KERNEL[11888.448883] remove   /devices/virtual/input/input111 (input)
KERNEL[11888.448963] remove   /devices/virtual/input/input110/event25 (input)
UDEV  [11888.449967] remove   /devices/virtual/input/input111 (input)
UDEV  [11888.450467] remove   /devices/virtual/input/input110/event25 (input)
KERNEL[11888.462935] remove   /devices/virtual/input/input110/js1 (input)
UDEV  [11888.464794] remove   /devices/virtual/input/input110/js1 (input)
KERNEL[11888.473008] remove   /devices/virtual/input/input110 (input)
KERNEL[11888.473184] remove   /devices/virtual/input/input109/event24 (input)
UDEV  [11888.475751] remove   /devices/virtual/input/input110 (input)
UDEV  [11888.477053] remove   /devices/virtual/input/input109/event24 (input)
KERNEL[11888.483089] remove   /devices/virtual/input/input109/js0 (input)
UDEV  [11888.486365] remove   /devices/virtual/input/input109/js0 (input)
KERNEL[11888.491050] remove   /devices/virtual/input/input109 (input)
UDEV  [11888.494161] remove   /devices/virtual/input/input109 (input)

```

**Comment by toccata10** [comment]
I can confirm some strange behaviour here (Archlinux, rev8744 (after this one, there are other problems with gamepad inputs):
I have 2 gamepads: an arcade stick (based on DragonRise) and a xbox-360 controller.
I want to remap the buttons, so a few tests:
1) Player1: evdev, xbox360. Arcade Stick not connected. I can record the new controls: ok.
2) Player1: evdev, Arcade Stick. xbox360 not connected. I can record the new controls: ok (with Filter Noise, but that's normal).
3) Player1: evdev, xbox360. Arcade Stick connected, but player2: null. I can record the new controls: ok.
4) Player1: evdev, Arcade Stick. xbox-360 connected, but player2: null. I can't record the new controls from the Arcade Stick: it registers the inputs from the xbox-360 controller.

So, for now, if I want to remap a controller: I disconnect everything apart from this controller.

**Comment by Megamouse** [comment]
please retest

**Comment by 7oxicshadow** [comment]
Tested with RPCS3 0.0.7-912-9a8c59a1 Alpha.
Tried 4 players with Diablo III. All controllers worked independently as expected.
Confirmed fixed for me.
