### ISSUE TITLE
Duplicated items in Graphics Device settings

### ISSUE THREAD

**Issue by Y0ba** [RPCS3/rpcs3#5672]
RPCS3 Verison: 0.0.6-7807-4c72f7c1
OS: Windows 10 1809

There should be only one 980 and one 2080Ti.
![pic](https://user-images.githubusercontent.com/1163958/53014427-820af280-3459-11e9-9243-1c3bd582c8ff.jpg)

**Comment by 13xforever** [comment]
Please upload log file, preferably booting some game.
Have you installed vulkan rt or sdk manually in the past?

**Comment by Y0ba** [comment]
> Have you installed vulkan rt or sdk manually in the past?

No.

Log: https://gist.github.com/Y0ba/b2752f0a948f92daaa6de79ef5c4fc40

**Comment by kd-11** [comment]
I'm interested in seeing a vulkaninfo dump from the system in question. You can get vulkaninfo application by installing the vulkan SDK tools from lunarg and running 'vulkaninfo' from cmd.

**Comment by Y0ba** [comment]
vulkaninfo: https://gist.github.com/Y0ba/734c6fdb410cf6156a78edff247e205d

**Comment by Y0ba** [comment]
There was an error when running vulkaninfo:
```
WARNING: [Loader Message] Code 0 : ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
```
Not sure if it affects output.

**Comment by Y0ba** [comment]
Fixed after drivers update.
