### ISSUE TITLE
crashes on newest NVIDIA drivers

### ISSUE THREAD

**Issue by pietergmail** [RPCS3/rpcs3#5673]
if i install the newest nvidia drivers every pcs3 game crashes after a bit of playing.

its solved if i downgrade to older drivers.

**Comment by MSuih** [comment]
Are you talking about #5351? Does this happen when vsync is enabled?

**Comment by pietergmail** [comment]
yes according to this reddit post: https://old.reddit.com/r/rpcs3/comments/ap3fcc/rpcs3_freezes_on_fullscreen_task_manager_doesnt/ 
its related to the issue but not exactly the same

**Comment by 13xforever** [comment]
It's exactly the same issue

**Comment by pietergmail** [comment]
oh it is sorry i will delet e the thread

**Comment by pietergmail** [comment]
nevermind it seems i cant delete it

**Comment by 13xforever** [comment]
just close it, Ani will label this as duplicate later

**Comment by pietergmail** [comment]
ok, sorry i am kinda new to github
