### ISSUE TITLE
Infamous hangs after pressing start for second time. version 0.0.6-7807-4c72f7c1 alpha

### ISSUE THREAD

**Issue by AlexS2412** [RPCS3/rpcs3#5674]
F {RSX [0x0554728]} RSX: class std::runtime_error thrown: [attrib buffer] Working buffer not big enough, buffer_length=402653184 allocated=402345728 requested=412298 guard=4194304 largest_pool=536576
(in file c:\projects\rpcs3\rpcs3\emu\rsx\common\ring_buffer_helper.h:78)

**Comment by RainbowCookie32** [comment]
I think it's either related or the same as #5600
