### ISSUE TITLE
"Ignore doubleclicks for Fullscreen" does not save for game custom configurations

### ISSUE THREAD

**Issue by ddscentral** [RPCS3/rpcs3#5676]
"Ignore doubleclicks for Fullscreen" option does not seem to work for custom game configurations.
As soon as I create a custom configuration for a game, "Ignore doubleclicks for Fullscreen" option disables itself and refuses to stick even after clicking the Save button.

RPCS3 version 4c72f7c1

**Comment by Megamouse** [comment]
They are not supposed to work with custom configurations since they use the gui settings instead of the emu settings.
I'll have to hide them from the game configs.

**Comment by ddscentral** [comment]
That's what I thought as well, judging from the settings dialog code.
If the setting is global-only, it should be either greyed out in game configs or removed from them entirely.
