### ISSUE TITLE
RPCS3 Persona 5 stuck on black screen

### ISSUE THREAD

**Issue by ProtoZero** [RPCS3/rpcs3#5679]
I am trying to get persona 5 to work, but no matter what configuration I do, the game won't load. I can redownload rpcs3 and it will say "creating game data for persona 5", but after that it's just a black screen for all eternity, and I can't seem to get anything to work. I am running a windows 10 laptop with intel core i7 - 5500U CPU 2.40 GHz 7.91 GB RAM, and am assuming it's because my computer is underpowered, but if that was the case, wouldn't the game at least load at a very slow framerate? anyways, I need help with this, as i've really wanted to play persona 5 and heard great things about it.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
