### ISSUE TITLE
Remove rClassname types

### ISSUE THREAD

**Issue by Bigpet** [RPCS3/rpcs3#568]
They were used as a temporary measure to make a workable split project with as little linking dependencies to functions and types from wx as possible.

I'm going to transfer the checklist for the progress toward that to this new issue to make it more visible, the original place was here: https://github.com/DHrpcs3/rpcs3/pull/239#issuecomment-44066262

- [x] needed for complete independence from wxWidgets
  - [x] figure out how to seperate the logging stuff a little better 
  - [x] figure out where to put the wxString conversion functions (currently in strmft)
  - [x] provide non wx implementation of rConcurrency (things like wxSemaphore, wxCriticalSection, etc.) 
  - [x] rFile (wxFile, wxDir, etc.)
  - [x] rMessageBox 
  - [x] rPlatform (GLContext creation, wxImage to save an image and instantiation of IO handlers like WindowsKeyboardHandler etc.)
  - [x] rTime (wxDateTime and related functionality, no clue what to replace this with yet)
  - [x] rXml
  - [x] wxZlibInputStream (wxMemoryInputStream, wxMemoryOutputStream as well)

**Comment by Nekotekina** [comment]
I guess it's all clear now. Of course I cheated with celRtc, I don't really want to exterminate things like that, but LLE must be fine for now.
