### ISSUE TITLE
Nvidia 418.31.03 bug

### ISSUE THREAD

**Issue by stumts** [RPCS3/rpcs3#5683]
This is God of War 3 after I've updated Nvidia driver to 418.31.03 
![captura de tela de 2019-02-23 11-10-44](https://user-images.githubusercontent.com/30453661/53287527-1b891b80-375c-11e9-9b3e-d93b4d51162a.png)
**System Specs:**
- RPCS3 v0.0.6-7809
- HP Envy 15;
- Graphic Card: GTX 850m;
- Graphic Driver: NV Proprietary Driver (nvidia-418.31.03);
- SO: Ubuntu 18.04

**Comment by 13xforever** [comment]
Github is not a place to ask for support, use discord or forums instead.

Also please read the [guidelines](/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) for issue reporting, your current report does not qualify.

**Comment by stumts** [comment]
Do I ask for support? I'm reporting an issue. I saw a guy with the same problem here #5675

**Comment by stumts** [comment]
Problem fixed with Nvidia 418.42.02

![captura de tela de 2019-03-03 16-52-35](https://user-images.githubusercontent.com/30453661/53700802-f38d5e00-3dd4-11e9-9be2-a750c9bc2db9.png)

**Comment by kd-11** [comment]
We probably got lucky and some AAA game also broke. Closing.
