### ISSUE TITLE
overlay problem in Sengoku Basara 4 co op

### ISSUE THREAD

**Issue by egfgs007** [RPCS3/rpcs3#5684]
<img width="1905" alt="ashampoo_snap_2019 02 23_23h56m51s_001_" src="https://user-images.githubusercontent.com/47930983/53292952-87ef3380-37cb-11e9-98de-fd719844a6b4.png">

Hey, this is what it looks like. The situation is that you start a round with another player but there is only one problem. The screen of player1 does cover the screen of player2 so it is not possible to watch at the second players screen. I also tried to restart the game, use other stages and even other settings. But nothing helped me out, so i decided to ask in the discord but up there i got linked to the github community. 

In the picture you can also see with the blacker part of the screen where it should be cut that you can see the player2 screen.
<img width="655" alt="ashampoo_snap_2019 02 24_00h35m31s_002_" src="https://user-images.githubusercontent.com/47930983/53293009-5165e880-37cc-11e9-8f8e-fec93b5896a8.png">
<img width="648" alt="ashampoo_snap_2019 02 24_00h36m19s_003_" src="https://user-images.githubusercontent.com/47930983/53293011-52971580-37cc-11e9-9056-cfc1c3f88530.png">

those are my settings. And following there are the logs of the game starting till the point i am ingame with the overlay problem:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2897392/RPCS3.log)

**Comment by devildante** [comment]
Re5 have same issue

**Comment by AniLeo** [comment]
Probably fixed, needs retesting

**Comment by digitaldude555** [comment]
![Screenshot (1124)](https://user-images.githubusercontent.com/26138653/74090119-ab7cbe00-4ab0-11ea-9c09-3363fe350c9d.png)
Fixed just as ani said.
