### ISSUE TITLE
AppCrash on Emulator exit

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#5685]
Latest Master build, Windows 7 HP x64

If I'm closing emulator during playing game, it crashes on exit with this log.
Tested on Silent Hill Downpour (BLUS30565).
The problem wasn't exist on previous tests a month ago.

```
Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	rpcs3.exe
  Версия приложения:	0.0.0.0
  Отметка времени приложения:	5c713fc8
  Имя модуля с ошибкой:	StackHash_57ef
  Версия модуля с ошибкой:	6.1.7601.19160
  Отметка времени модуля с ошибкой:	56bcd74c
  Код исключения:	c0000374
  Смещение исключения:	00000000000c0aa2
  Версия ОС:	6.1.7601.2.1.0.768.3
  Код языка:	1049
  Дополнительные сведения 1:	57ef
  Дополнительные сведения 2:	57effe57c70a131b74edb85c26c095d6
  Дополнительные сведения 3:	54f7
  Дополнительные сведения 4:	54f746d2110b8ddf752fe7fcf733b3f2
```

**Comment by darlong** [comment]
I have the same problem. If I delete all the files and reinstall rpcs3 , It work. But sadly after exit the game it crash again.

**Comment by AniLeo** [comment]
What GPU drivers?

**Comment by darlong** [comment]
Hello,

My computer have this
Geforce gtx 1060
I7-7700HQ
DDR4-2400 16G

At write at the forum that, I had to reinstall the program. Now found a new
way. That it's erase all the files inside cache folder, except BLUS31212.

I don't know if that make help.

Thank you , I really appreciate your help.

**Comment by Psycho-A** [comment]
@AniLeo GPU drivers are one of latest NVidia WHQL for Win7, I installed them a month ago.
Also, I can't see this crash if I run emulator on Windows 10, so, again some compatibility is broken I guess.

**Comment by darlong** [comment]
It may not be the same problem as @Psycho-A , but right now it doesn't work
at all. Not erasing cache not reinstalling the app. I am so sad because it
was working fine until a couple of days before. I don't know what to do
anymore. I tried change compatibility but didn't work neither.



compatibilityde marzo de 2019 4:36 a. m., Psycho-A <notifications@github.com>
escribió:

**Comment by Psycho-A** [comment]
Latest master build 7869, it seems the issue's gone (can't reproduce anymore).
