### ISSUE TITLE
Exit game dialog doesn't show on top in fullscreen mode

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#5686]
When we're trying to exit game directly from fullscreen, using Alt+F4 hotkeys, the exit game dialog doesn't show over the screen, and hidden behind it. As result, we need to minimize emulator or exit fullscreen to see and manage the dialog.

**Comment by Megamouse** [comment]
Can you please test with the mentioned build once it is ready?

**Comment by vsub** [comment]
Are you somehow running the game window with Always on Top status?
Because here pressing Alt+F4 while in full screen shows the confirm dialog even without exiting full screen.

Or maybe you are using something that kills the active process with Alt+F4(I think there is some windows registry settings that does this)

**Comment by MSuih** [comment]
Qt dialogs often spawn behind the fullscreen window, this was a common complaint before native UI was implemented.

**Comment by Psycho-A** [comment]
> Qt dialogs often spawn behind the fullscreen window, this was a common complaint before native UI was implemented. On multi-monitor setups they can also occasionally spawn on wrong displays.

Then that would be really nice, if exit dialog would replaced with the native UI implementation. It would even much more organic in the design aspect...

@vsub I don't use any crutches on running the emulator - all is by default.

**Comment by Megamouse** [comment]
So does it fix the problem or not

**Comment by RainbowCookie32** [comment]
> So does it fix the problem or not

I just tested the PR, and the game does exit fullscreen after hitting alt+f4, but the exit game dialog gets behind the game window.

**Comment by vsub** [comment]
I am not sure what is so different on anyone else but here(not using this pr)pressing alt+f4 brings the confirm dialog and I am not allowed to click anywhere else other than the dialog.
Also minimizing all(Winkey+D)and clicking on the confirm taskbar button brings me back to full screen where the dialog is still there waiting for yes or no

At least here,the dialog works exactly as expected and no matter what I do,I cannot make the confirm dialog to go behind the game window(even if I try to bring the main window,the dialog will again be on top of it and I can't do anything other than clicking yes or no...or the X button)

**Comment by RainbowCookie32** [comment]
> I am not sure what is so different on anyone else but here(not using this pr)pressing alt+f4 brings the confirm dialog and I am not allowed to click anywhere else other than the dialog.
> Also minimizing all(Winkey+D)and clicking on the confirm taskbar button brings me back to full screen where the dialog is still there waiting for yes or no
> 
> At least here,the dialog works exactly as expected and no matter what I do,I cannot make the confirm dialog to go behind the game window(even if I try to bring the main window,the dialog will again be on top of it and I can't do anything other than clicking yes or no...or the X button)

Actually. I just tested master and I have the same experience you describe. Alt+f4 on fullscreen displays the dialog on top of the game. I'm not sure if I see the issue

**Comment by Megamouse** [comment]
please retest with the linked Pull Request
https://github.com/RPCS3/rpcs3/pull/5687

**Comment by Psycho-A** [comment]
> please retest with the linked Pull Request

I can't see any difference with before builds, and game doesn't go out of fullscreen on Alt+F4.

**Comment by Megamouse** [comment]
@Psycho-A 
Are you normally able to leave our fullscreen game window with ESC or Alt+Enter ?

**Comment by Psycho-A** [comment]
@Megamouse 
Yes, Escape and Alt+Enter works.
I also have option "Don't use doublecklick to switch fullscreen" enabled (to have mouse controls work).

**Comment by Megamouse** [comment]
Well the changes are in master now.
But for now you seem to be the only person with that problem left :(

**Comment by Psycho-A** [comment]
@Megamouse, I doubt the emulator may behave itself so different on various machines. If Alt+F4 first time does fullscreen exit, it must be this way anywhere. Otherwise it's just some hack dependant on the OS version.

**Comment by Megamouse** [comment]
might be driver issues. did you install the latest ?
Sometimes 3rd party apps or old Qt files might also be the reason

**Comment by Megamouse** [comment]
We designed the app to first exit fullscreen and then spawn the dialog as a modal dialog in front of the entire Application. So whatever happens on your side will probably be some window management issue caused by drivers or the operating system.
It would help if you posted a log file or tell us your specs.

**Comment by Psycho-A** [comment]
Works for me with latest master builds.
