### ISSUE TITLE
Persona 5 horizontal line and missing upscaling on cutscenes/movies

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#5689]
Persona 5 misses the upscale filtering at the upper half of the image on both vendors' cards, and repeats the last line of the FBO right into the middle, creating a horizontal line effect dividing the upper and lower half of the image output.

The horizontal line issue has been long known but had been swept under the rug. Only occurs while upscaling, with 150% vs 200% showing no difference, all configurations (integer and non-integer modes) are affected.

Try looking at Joker's chin if you don't see any one of the issues.

![image](https://user-images.githubusercontent.com/10439488/53355180-c2221780-3928-11e9-9f33-1d8e31b8bd65.png)

Catherine also produces a similar issue, though the upscale filter is working as intended there, and the line repetition is not exactly in the middle of the image, but a bit below.

![image](https://user-images.githubusercontent.com/10439488/53356485-d0bdfe00-392b-11e9-91e8-5df68cbfeb32.png)

![image](https://user-images.githubusercontent.com/10439488/53356492-d61b4880-392b-11e9-9e94-0a461d6af3fd.png)

**Comment by Gonbatfire** [comment]
still present on latest build.

**Comment by Kimarnic** [comment]
Still bugged in RPCS3 v0.0.9-10173-8e61c65c Alpha | HEAD | Firmware version: 4.85
Ruined my playthrough of Persona 5, now i have to record everything again

**Comment by dio-gh** [comment]
Closing as resolution scaling is a hack and is not supposed to be perfect. Can reopen if needed.
