### ISSUE TITLE
intel: Games not initializing properly (HD 5500)

### ISSUE THREAD

**Issue by d-apps** [RPCS3/rpcs3#5690]
**RPCS3 Version:** `v0.0.6-7809-c325534f Alpha | HEAD

**Specs:**
CPU - Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz | 4 Threads | AVX+
Ram - 8.00 GB
OS - Windows 10 last build
HDD - 1 TB
GPU - Intel HD Graphics 5500 (driver updated)

Before I format my laptop I was using some older version of RPCS3 and I was playing Super Street Fighter II Turbo HD Remix fine but now when I try to boot I got blackscreen/whitescreen, I just installed the latest version and testing other game, Naruto Ultimate Ninja STORM I got the same error according the log below.

**Log:** Updated
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2907494/RPCS3.log)

**Comment by RainbowCookie32** [comment]
The problem is most likely your iGPU. Older intel iGPUs are known to have issues. It's failing to compile a shader

**Comment by d-apps** [comment]
Thank you but is there anything I can do to fix it?

**Comment by RainbowCookie32** [comment]
Pretty sure you can't fix it, and this is not an issue with the emulator. You should go to the Discord server for this, not here

**Comment by d-apps** [comment]
Testing version: v0.0.5-**7550-32059bfa**, I didn't have this error, I had some erros in log but at least the game is working, is it possible that this issue is related to my GPU only with newer versions? 

![rpcs3](https://user-images.githubusercontent.com/20110433/53376978-1a641400-393f-11e9-8e49-940f1e6da971.jpg)

[log.txt](https://github.com/RPCS3/rpcs3/files/2903114/log.txt)

**Comment by RainbowCookie32** [comment]
If you are going to attach the log, please attach the correct file. Don't copy-paste from rpcs3, upload RPCS3.log from the emulator's folder

**Comment by AniLeo** [comment]
Needs proper log file, note that Intel GPU Drivers are not supported

**Comment by d-apps** [comment]
Sorry guys, I updated with the correct log now, thank you.

**Comment by AniLeo** [comment]
```
·E 0:05:36.516891 {RSX Decompiler Thread} RSX: Failed to compile shader: ERROR: 0:123: 'tex00' : undeclared identifier 
ERROR: 0:123: 'texture' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:123: 'process_texel' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:123: 'assign' :  cannot convert from 'const highp float' to 'inout 4-component vector of highp float'
```

Pinging @kd-11

**Comment by kd-11** [comment]
```
index = 0
TEX_NAME(index) = tex##index (concatenation, returns "tex" + index)
```
Somehow intel returns tex00 instead of tex0. And this is just one of the many reasons why intel drivers are not supported. Where did it get '00' from? It defies logic.

**Comment by d-apps** [comment]
Is there any chance rpcs3 future updates solve this or probably this will happen with all new versions too?

**Comment by RainbowCookie32** [comment]
I think it's a driver issue, so it'd be on intel's side to fix it if I'm correct

**Comment by d-apps** [comment]
only rpcs3 use RSX Decompiler? Because I use other emulators like cemu, dolphin and they work fine...

**Comment by AniLeo** [comment]
The only console with a RSX GPU is PS3...

**Comment by sirdanielk** [comment]
Intel implementation of vulkan in drivers is ok. This game work nice with vulkan. Opengl have different problem - buffer underrun on HD620.

**Comment by d-apps** [comment]
I opened a ticket with Intel Support explaining the RSX Compiler problem, let's wait for their response.

**Comment by AniLeo** [comment]
How RPCS3's RSX Decompiler works is not Intel's problem, the problem here is the drivers' GLSL Compiler being broken.

**Comment by RainbowCookie32** [comment]
And considering it's an older product that doesn't receive driver updates anymore, I don't think they are really eager to fix it

**Comment by d-apps** [comment]
Latest update was released march 2019, I have some hope :)

**Comment by RainbowCookie32** [comment]
It was a security update if memory serves

**Comment by AniLeo** [comment]
Yeah, even Skylake 15.45's latest update were just security fixes

**Comment by sirdanielk** [comment]
Update 
that error F {RSX [0x02c0d30]} RSX: struct gsl::fail_fast thrown: GSL: Precondition failure at c:\projects\rpcs3\3rdparty\gsl\include\gsl\span: 621
also happen with nvidia at opengl

Latest intel drivers supports opengl 4.6, not yet to known since what generation

**Comment by AniLeo** [comment]
Probably the ones that supported OGL 4.5 before, Skylake and above I would guess

**Comment by AniLeo** [comment]
Closing as superseded by the Intel GPU Megathread #6199

**Comment by bukyapavankumar** [comment]
> Testing version: v0.0.5-**7550-32059bfa**, I didn't have this error, I had some erros in log but at least the game is working, is it possible that this issue is related to my GPU only with newer versions?
> 
> ![rpcs3](https://user-images.githubusercontent.com/20110433/53376978-1a641400-393f-11e9-8e49-940f1e6da971.jpg)
> 
> [log.txt](https://github.com/RPCS3/rpcs3/files/2903114/log.txt)

Did u try it on Linux with latest mesa drivers?
