### ISSUE TITLE
Need for Speed Most Wanted Debug Build doesn't launch (Nothing)

### ISSUE THREAD

**Issue by MoussaBayou** [RPCS3/rpcs3#5698]
Hello,

Debug Builds of games like Need For Speed Most Wanted (2012) can be modified to boot on rpcs3, however they crash on as soon as they are booted. However I have no idea how to fix that. Tried to make the E3 build look like the file tree of Retail Need for Speed Most Wanted (2012) exactly and Hex edited some stuff, with no avail.

Here is a resume on what does it say in the Log:
`S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v1-tane-5xMfRrcnyF35muvffonmf7-000000-westmere.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v1-tane-ag6ChuhSXpzembwh5Xr3TA-000000-westmere.obj
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Recompiler Runtime initialized...
U {PPU[0x1000000] Thread (main_thread) [0x00053d7c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x000500c4]} PPU: LLVM: Loaded module v1-tane-47i92m7FhMAd310FJYM8oE-000000-westmere.obj
S {PPU[0x1000000] Thread (main_thread) [0x000500c4]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x000500c4]} PPU: LLVM: Loaded module v1-tane-TP3c8YsdNggjaG5WRjcboe-000000-westmere.obj
S {PPU[0x1000000] Thread (main_thread) [0x000500c4]} PPU: LLVM: Loaded module v1-tane-LWAKW9c35vXJad6uHkwzhK-000000-westmere.obj
S {PPU[0x1000000] Thread (main_thread) [0x000500c4]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
U {PPU[0x1000000] Thread (main_thread) [0x000102f0]} sysPrxForUser TODO: sys_prx_exitspawn_with_level()
S sys_process: Process finished -> /dev_bdvd/Alaska_PS3_Internal.self`

Here is THE COMPLETE LOG: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2922036/RPCS3.log.gz)

Specs & Config:

rpcs3-v0.0.6-7804-63a94216_win64 | Windows 7 64Bits
Intel(R) Core(TM) CPU i5 430M OC'd @‍ 2.80GHz | 4 Threads | 4 GiB RAM
GPU: OC'd GeForce G105M (342.01)

CPU Settings
PPU ‍Decoder: ‍ ‍ ‍ ‍ ‍Recompiler ‍(LLVM)
SPU ‍Decoder: ‍ ‍ ‍Recompiler ‍(LLVM)
SPU ‍Lower ‍Thread ‍Priority: ‍ ‍ ‍ ‍ ‍[ ‍]
SPU ‍Loop ‍Detection: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍[x]
Thread ‍Scheduler: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍[ ]
SPU ‍Threads: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍Auto
SPU ‍Block ‍Size: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍Safe
Accurate ‍xfloat: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍[ ‍]
Force ‍CPU ‍Blit: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍[ ‍]
Lib ‍Loader: ‍ ‍Automatically load required libraries
GPU Settings
Renderer: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍OpenGL
Aspect ‍ratio: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍Auto
Resolution: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍1280x720
Resolution ‍Scale: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍100%
Resolution ‍Scale ‍Threshold: ‍ ‍ ‍ ‍ ‍16
Write ‍Color ‍Buffers: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍[ ‍]
Anisotropic ‍Filter: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍Automatic
Frame ‍Limit: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍Off
Disable ‍Async ‍Shaders: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍[ ‍]
Disable ‍Vertex ‍Cache: ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍[ ‍]
Debug Settings
Enable Debug Mode [x]

Hope to hear from you soon,

**Comment by elad335** [comment]
#5632

**Comment by AniLeo** [comment]
You need to use Renderer Null because your GPU doesn't support any of the Render APIs used by RPCS3.

**Comment by MoussaBayou** [comment]
Pretty sure it does, OpenGL Extentions Viewer reveals that my GPU supports OpenGL 3.3, DirectX10.1 and Doesn't support Vulkan. I suggest a Re-Opening of this issue please.

**Comment by isJuhn** [comment]
RPCS3 requires at least OpenGL 4.3 or greater, as detailed in the quickstart guide.

**Comment by kd-11** [comment]
I don't think the crash here is because of graphics at all. It never even gets to the point where the renderer is initialized. Likely the edited eboot introduces other issues and breaks compatibility, but if thats the case, its up to the modder to figure out what breaks as with all other eboot modifications.

**Comment by AniLeo** [comment]
Doesn't support OGL 4.3, issue was closed because it's also a duplicate of #5632

**Comment by MoussaBayou** [comment]
Okay, thank you people :)

**Comment by Bo98** [comment]
Yes @kd-11. The issue here is the lack of cellSearch support. #4714.
