### ISSUE TITLE
Issue with MLB The Show and Vulkan, possibly specific to RTX cards

### ISSUE THREAD

**Issue by connorwalks** [RPCS3/rpcs3#5699]
CPU: i9 9900K (stock)
GPU: RTX 2080 (stock)
Memory: 16 GB (dual channel) DDR4-3000 (C15)
OS: Windows 10 64-bit (Education) 1809 OS Build 17763.316
NVIDIA Driver Version: 419.17

Hello, I have been trying to play a few of the MLB The Show games (specifically MLB The Show 16 and 13) and have had a few issues that I think are bugs. I have tested the game on two separate builds, so I will split my explanation up accordingly.

First, I tested MLB The Show 16 [BCUS01089] on build 0.0.6-7825-ebb24375 on February 28th, shortly after the build released. I first tested in OpenGL, and the game boots up well. Once I load up a live game or batting practice however, even after all shaders are compiled, there is horrible flickering all over the screen (seizure inducing if you are prone to that). Aside from that the game runs well with occasional crashes. I then try to boot up in Vulkan and get into the menu fine. Once I try to load up a live game or batting practice, RPCS3 hard crashes. No error message. The game window and RPCS3 GUI window close without warning and are sometimes even unable to be closed out in task manager, requiring a system restart. 

I tried uninstalling my graphics driver (which was up to date) using DDU and reinstalled RPCS3 as well and got the same results. This bug occurs on multiple versions of the MLB The Show game (tested on 13,14 and 16, which is all I have access to right now). When testing other games with Vulkan on the same build (tested Skate 3 and College Hoops 2K8), there is no issue getting into the game. I spoke with another. After speaking with another user in the discord with different hardware (unknown CPU and 780Ti), he was able to get the game running with Vulkan fine (low frames due to GPU horsepower, but it loaded into a rendered scene). So I tried using DDU once more and borrowed a friends GTX 1060 6GB and installed the same 417.19 drivers. This time, however, the game loaded into rendered scenes perfectly using Vulkan. It would crash after a while, but that is normal according to other user reports. 

I tried using DDU one more time and put my RTX 2080 back into the system and experienced the crashing upon my GPU trying to render a game scene. This all happened on the evening of Thursday, February 28th. I then tested the game using an older build from May of 2018 (0.0.5-6906-7b5dcd9d6) and experienced no issues whatsoever when loading into a rendered scene using Vulkan. There was no flashing either. I even tried launching the game using OpenGL and experienced no flashing when in game. However there was a blue tint in game and in the menu screen (known issue that has since been fixed and is not a present issue in 0.0.6-7825-ebb24375).

This morning, March 2nd, I tried launching the game (MLB 16 The Show) on build 0.0.6-7825-ebb24375 once more and to my surprise, I was able to load into a batting practice session using Vulkan! No blue tint, no flashing, the game looked great. However, the game crashes after one or two pitches and is extremely unstable, which was not the case for the other discord user I spoke to and not the case when using my friend's GTX 1060. Nothing has changed with anything with Windows, GPU drivers, or RPCS3 settings in the past two days, but for some reason it is finally loading into the game (albeit for a very short amount of time) while using Vulkan. I have attached screenshots of the game from both builds used showing off gameplay and the menus, as well as my logs from each build (all titled accordingly). 

Thank you for taking the time to read this long write-up. I am just very fond of the MLB The Show franchise and would absolutely love to have it playable on my system. Please let me know if there is anything you would like me to clarify or test so we can get this bug squashed. 

![0 0 5-6906-7b5dcd9d6 menu](https://user-images.githubusercontent.com/48158481/53685210-b4ccaa80-3ce5-11e9-974b-5e7d20fd91aa.jpg)
![0 0 5-6906-7b5dcd9d6 opengl game](https://user-images.githubusercontent.com/48158481/53685212-b8603180-3ce5-11e9-98ab-e6618a8b3496.jpg)
![0 0 5-6906-7b5dcd9d6 vulkan game](https://user-images.githubusercontent.com/48158481/53685214-bac28b80-3ce5-11e9-94cc-afc168ebe9f9.jpg)
[0.0.5-6906.log.gz](https://github.com/RPCS3/rpcs3/files/2922338/0.0.5-6906.log.gz)

![0 0 6-7825-ebb24375 menu](https://user-images.githubusercontent.com/48158481/53685215-bf873f80-3ce5-11e9-917d-7f94d1f80cc7.jpg)
![0 0 6-7825-ebb24375 opengl game](https://user-images.githubusercontent.com/48158481/53685223-ca41d480-3ce5-11e9-8193-4c52f3d02323.jpg)
![0 0 6-7825-ebb24375 vulkan game](https://user-images.githubusercontent.com/48158481/53685224-cca42e80-3ce5-11e9-826d-773ad82ced1c.jpg)
[0.0.6-7825-ebb24375.zip](https://github.com/RPCS3/rpcs3/files/2922351/0.0.6-7825-ebb24375.zip)

**Comment by isJuhn** [comment]
second log is empty

**Comment by connorwalks** [comment]
> 
> 
> second log is empty

How do I get RPCS3 to save the log if it hard crashes every time?

**Comment by RainbowCookie32** [comment]
Only the compressed log gets deleted on a crash. RPCS3.log (notepad icon) doesn't. You can compress that one and upload it

**Comment by connorwalks** [comment]
Thanks for letting me know. Just updated it in the original post but here it is again: 
[0.0.6-7825-ebb24375.zip](https://github.com/RPCS3/rpcs3/files/2922356/0.0.6-7825-ebb24375.zip)

I also want to note that I tried launching the game on the current build using Vulkan once again and now it crashes before ever loading into a rendered scene, just as it was two days ago

**Comment by connorwalks** [comment]
Issue seems to be fixed for me with 430.39 Nvidia driver

**Comment by AniLeo** [comment]
Closing as it's solved on newer drivers
