### ISSUE TITLE
Persona 5 [BLUS31604] crashes to zombie process with Vulkan

### ISSUE THREAD

**Issue by mcilya** [RPCS3/rpcs3#5701]
OS: Windows 10
CPU: AMD FX-8350
RAM: 12 GB
GPU: NVIDIA GTX 1050ti 4GB
rpcs3 version: 0.0.6-7825

Clearing caches sometimes help.
Works fine with OpenGL.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2929180/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2929181/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
This is a known issue with nvidia's 400 series drivers, if you use fullscreen, it'll freeze and get stuck as a background process
