### ISSUE TITLE
issue with Inferno Pool [NPUB30104]

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5703]
RPCS3 v0.0.6-7827-e38b7aee Alpha | HEAD

·W 0:00:37.340944 {RSX [0x0001374]} RSX: NV3089_IMAGE_IN: Operation NOPed out due to empty regions
·F 0:00:37.340980 {PPU[0x1000000] Thread (main_thread) [0x003c89c0]} MEM: Access violation reading location 0xfffffff4

log file 
[RPCS3 Inferno Pool.log.gz](https://github.com/RPCS3/rpcs3/files/2934530/RPCS3.Inferno.Pool.log.gz)

**Comment by elad335** [comment]
This game needs Debug Console Emulation enabled.
![image](https://user-images.githubusercontent.com/18193363/53885491-896bf780-4026-11e9-8b11-47cce42f7bf0.png)

**Comment by uaqlover** [comment]
yep thanks again @elad335 : )
