### ISSUE TITLE
issue with MotoGP™13 [BLES01805]

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5705]
RPCS3 v0.0.6-7827-e38b7aee Alpha | HEAD

i tried with interpreter and it same also enabled Debug Console Emulation 

and tried opengl and Vulkan all same 

·! 0:00:54.094932 {cellAudio Thread} Thread time: 0.000000s (0.091193Gc); Faults: 0 [rsx:0, spu:0];
·W 0:00:54.096488 {PPU[0x1000000] Thread (main_thread) [0x01e55218]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x9500a300)
·U 0:00:54.196584 {PPU[0x1000000] Thread (main_thread) [0x0112a5e0]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK
·W 0:00:54.196598 {PPU[0x1000000] Thread (main_thread) [0x01e55218]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x95002c00)
·W 0:00:54.196619 {PPU[0x1000000] Thread (main_thread) [0x000126d8]} sys_memory: sys_memory_free(addr=0x30000000)
·F 0:00:54.197084 {SPU[0x2000002] Thread (CellSpursKernel2) [0x011a8]} MEM: Access violation reading location 0x300d8f80
·F 0:00:54.197086 {SPU[0x2000001] Thread (CellSpursKernel1) [0x011a8]} MEM: Access violation reading location 0x300d8f80
·F 0:00:54.197084 {SPU[0x2000000] Thread (CellSpursKernel0) [0x011a8]} MEM: Access violation reading location 0x300d8f80
·F 0:00:54.197084 {SPU[0x2000003] Thread (CellSpursKernel3) [0x011a8]} MEM: Access violation reading location 0x300d8f80

log file 

[RPCS3 issue with MotoGP™13 [BLES01805].log.gz](https://github.com/RPCS3/rpcs3/files/2936786/RPCS3.issue.with.MotoGP.13.BLES01805.log.gz)

**Comment by elad335** [comment]
I'm not getting it, tried ppu interpreter and LLVM. Is it random? occurs at specific points? 
![image](https://user-images.githubusercontent.com/18193363/53903929-93552100-404d-11e9-934d-4497d791358d.png)

**Comment by uaqlover** [comment]
mine not getting ingame at all 

here the video 

https://drive.google.com/file/d/1HIylcJHIGfujqewDbXnKZCS4wxFT9Hd4/view?usp=sharing

**Comment by AniLeo** [comment]
Log shows pirated game, closing issue
