### ISSUE TITLE
games with stuttering audio problem 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5706]
games with stuttering audio problem only 

and they are playable 

Hail to the Chimp (U) [BLUS30153]
Tony Hawk's® Pro Skater™ 5 [BLUS31568]
F1 2010™ [BLES00917]
The Punisher: No Mercy [NPUB30070]

Hail to the Chimp (U) [BLUS30153]

![11](https://user-images.githubusercontent.com/45731484/53911640-e27a6200-400b-11e9-9c0d-108eeb39a9a1.png)

video

https://drive.google.com/file/d/1fBwrR_aNb7BeUWwf164LFmUohFt-onBG/view?usp=sharing

Wangan Midnight [BLJM60028]

![22](https://user-images.githubusercontent.com/45731484/53911649-e8704300-400b-11e9-9fb1-c6d349281af1.png)

video

https://drive.google.com/file/d/17aIi2QYMt-Crmh69HixoUPoavLUsGu53/view?usp=sharing

Tony Hawk's® Pro Skater™ 5 [BLUS31568]

![33](https://user-images.githubusercontent.com/45731484/53911678-fcb44000-400b-11e9-99ec-f32536696d22.png)

video

https://drive.google.com/file/d/1voAJL10vNXfQpVvNDiKIRi0AROzTEGNl/view?usp=sharing

**Comment by Asinin3** [comment]
Playable =/= perfect. E.g Wangan Midnight only has some audio issues (for some people) when at high rev count. Using SPU LLVM fixes it. I don't see why you'd make an issue on github for this. This isn't what the github issue tracker is for. These are more like compatibility reports..

**Comment by uaqlover** [comment]
about Wangan Midnight i tired with every thing possible all same it still has stuttering audio 

i disabled spu loop detection and changed thread priority 

![44](https://user-images.githubusercontent.com/45731484/53913071-43576980-400f-11e9-845a-352a3deaed40.png)

here the video i also make auto in the video 

https://drive.google.com/file/d/1h4-Z1DJTJBVmddE6CkW5Lvqbnqg4yHOQ/view?usp=sharing

and about another games they all are ingame Status Now the only problem is stuttering audio need to be fixed

**Comment by digitaldude555** [comment]
tony hawk skater 5 already has an issue open for it. #4907

**Comment by uaqlover** [comment]
aonthers games also all using SPU LLVM 

F1 2010™ [BLES00917]

https://drive.google.com/file/d/1FEgcNIGisf2paSc-ZrT5cjgSZ8zS-hdM/view?usp=sharing

The Punisher: No Mercy [NPUB30070]

https://drive.google.com/file/d/1fGSdBAeMZOfewsY66dMrXPDf84BEpuBB/view?usp=sharing

**Comment by Asinin3** [comment]
The issue is invalid, just close it. Github isn't the place for issues like this. It's more for issues where you know where something regressed, or how exactly something is broken. These are more like compatibility reports. It's almost like creating an issue "Games that have low fps" and posting half the PS3 library even though we're in Alpha.

**Comment by uaqlover** [comment]
true sorry about that
