### ISSUE TITLE
[Regression] Gran Turismo 5 access violation

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#5707]
Gran Turismo 5 regressed from ingame to nothing after e38b7aee
console shows
F {PPU[0x1000000] Thread (main_thread) [0x01ae1c70]} MEM: Access violation reading location 0x8
reverting it makes it work again, please take a look

**Comment by elad335** [comment]
upload log.

**Comment by Xcedf** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2945022/RPCS3.log.gz)

**Comment by elad335** [comment]
Retest with #5697

**Comment by Melodycloudu** [comment]
I dont know if this is right for me to message me but GT5 has again ran into this regression as of any 0.0.29 version I know of and used
