### ISSUE TITLE
LLVM: Broken instruction on Ryzen architecture - Drakengard 3: No shadows, Regression after #4820

### ISSUE THREAD

**Issue by yatsukiko** [RPCS3/rpcs3#5709]
In build 7084 (pr #4820) new changes makes LLVM PPU decoder break shadows in Drakengard 3, fast ppu interpreter works just fine and build before that (7079) with LLVM PPU will have working shadows as well. Any other settings like SPU decoder or anything in GPU doesn't make difference to shadows. If you run the game at least once on build before 7084 then update it to newer (max 7727 build) shadows will still work. Downgrading from 7084 to 7079 doesn't fix shadows.

[7079 working shadows RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2949602/7079.working.shadows.RPCS3.log.gz)

[7084 no shadows RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2949603/7084.no.shadows.RPCS3.log.gz)

**Comment by elad335** [comment]
>Downgrading from 7084 to 7079 doesn't fix shadows.

Make sure to clear ppu llvm cache everytime you switch builds.

**Comment by yatsukiko** [comment]
A follow up on how it looks like and how it should 


![image](https://user-images.githubusercontent.com/40772846/54088529-caca1300-4356-11e9-86db-3f7c272461b0.png)



![image](https://user-images.githubusercontent.com/40772846/54088712-a111eb80-4358-11e9-9667-f4dacce7255c.png)


I will also mention that I have ryzen 5 2600 and gtx 1080 
and [ rsx captures ](https://yatsukiko.me/u/drakengard%203%20rsx%20captures.zip) for both

**Comment by yatsukiko** [comment]
It seems like changing  `Use LLVM CPU: ""`  to  `Use LLVM CPU: "skylake" ` fixes it

**Comment by kd-11** [comment]
There are some upstream bugs in LLVM itself (or ryzen hw) that causes this. It has improved with newer LLVM versions but it used to be pretty bad (black screen in most games unless you set CPU to intel arch)

**Comment by yatsukiko** [comment]
In latest master build (0.0.6-8437) shadows works fine without any changes in config.
