### ISSUE TITLE
[Bounty: $5]Family Guy: Back To The Multiverse [BLES01625] does not run

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5711]
rpcs3-v0.0.6-7857-1875dc3f_win64

Family Guy: Back To The Multiverse [BLES01625]

F {RSX [0x025c598]} RSX: class std::runtime_error thrown: VirtualProtect failed (00000003c594b000, 0x33e24000, addr=0x3cf900000, error=0x1e7)

log file 

[RPCS3 family.log.gz](https://github.com/RPCS3/rpcs3/files/2950186/RPCS3.family.log.gz)

**Comment by kd-11** [comment]
Retest

**Comment by uaqlover** [comment]
the error is gone But 

Infinite loading after press start 

also I try with openGL same thing 

![FPS_ 29 96 _ Vulkan _ 0 0 6-7881 _ Family Guy_ Back To The Multiverse  BLES01625  18_03_2019 4_12_02 PM](https://user-images.githubusercontent.com/45731484/54569605-bf9b6680-4998-11e9-875a-12917a0a153a.png)

https://forums.rpcs3.net/thread-188435.html

in old build was getting ingame 

log file

[RPCS3 family 2.log.gz](https://github.com/RPCS3/rpcs3/files/2980842/RPCS3.family.2.log.gz)

**Comment by kd-11** [comment]
Nothing crashed, which means it likely is just locking up with a race condition. Also, please don't use 'SPU loop detection' unless you know a game is stable enough with it enabled. It's a speedhack known to break games and mess with audio.

**Comment by uaqlover** [comment]
i disabled SPU loop detection and Nothing happens samething

**Comment by uaqlover** [comment]
Bountysource link: https://www.bountysource.com/issues/71206828-family-guy-back-to-the-multiverse-bles01625-does-not-run

**Comment by elad335** [comment]
This is technically fixed [here](https://ci.appveyor.com/project/elad335/rpcs3/builds/23517768), keep in mind that the game sufferes from a regression from rsx side so it needs a few tries before it boots.

**Comment by uaqlover** [comment]
good enough 

and good job @elad335 

please claim reward in bountysource

https://www.bountysource.com/issues/71206828-bounty-5-family-guy-back-to-the-multiverse-bles01625-does-not-run

![FPS_ 30 01 _ Vulkan _ 0 0 6-7934 _ Family Guy_ Back To The Multiverse  BLES01625  02_04_2019 3_29_29 PM](https://user-images.githubusercontent.com/45731484/55440635-1be7b400-555d-11e9-8eb5-8b24347b13d7.png)

![FPS_ 30 01 _ Vulkan _ 0 0 6-7934 _ Family Guy_ Back To The Multiverse  BLES01625  02_04_2019 3_29_34 PM](https://user-images.githubusercontent.com/45731484/55440641-1f7b3b00-555d-11e9-9515-9ff94469f945.png)

![FPS_ 30 01 _ Vulkan _ 0 0 6-7934 _ Family Guy_ Back To The Multiverse  BLES01625  02_04_2019 3_30_00 PM](https://user-images.githubusercontent.com/45731484/55440645-23a75880-555d-11e9-936f-79f2d3c18a5f.png)

if any time soon make Pull Request to add to the master : )
