### ISSUE TITLE
Regression: Yakuza 1&2 HD EDITION [BLJM60471] (#5244)

### ISSUE THREAD

**Issue by MsDarkLow** [RPCS3/rpcs3#5713]
i7-8700K @ 4.6GHz | GTX 1070 | 16GB RAM

Yakuza 1&2 HD EDITION no longer goes ingame since #5244 
The game crashes the emulator upon selecting which game you want to play (Y1 or Y2)

The last merged build that worked was in https://github.com/RPCS3/rpcs3/pull/5250
No options seem to help the game to go ingame.

Edit: If we boot Yakuza 1 or Yakuza 2 directly w/ `Boot SELF/ELF` it goes ingame just fine. Its only the selection screen crashing the game.

Log Latest: [RPCS3YLatest.log](https://github.com/RPCS3/rpcs3/files/2958240/RPCS3YLatest.log)
Log of no longer going ingame: [RPCS3Y5244NoWork.log](https://github.com/RPCS3/rpcs3/files/2958256/RPCS3Y5244NoWork.log)
Log Working: [RPCS3Y5250Works.log.gz](https://github.com/RPCS3/rpcs3/files/2958259/RPCS3Y5250Works.log.gz)

**Comment by elad335** [comment]
Fixed in https://ci.appveyor.com/project/elad335/rpcs3/builds/23037197.

**Comment by MsDarkLow** [comment]
> Fixed in https://ci.appveyor.com/project/elad335/rpcs3/builds/23037197.

Can confirm the fix works. Will close the PR once its merged.
