### ISSUE TITLE
Access Violation on Nascar 09

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5717]
NASCAR® 09 [BLES00268]

PPU Interpreter

```
F {SPU[0x2000005] Thread (Job Manager - Job Thread) [0x0bd00]} class std::runtime_error thrown: RawSPU not found (cmd=0x40, lsa=0x4b20, ea=0xe779c580, tag=0x0, size=0x400)
(in file c:\projects\rpcs3\rpcs3\emu\cell\sputhread.cpp:754)
```

Log File
[RPCS3 nas.log.gz](https://github.com/RPCS3/rpcs3/files/2959394/RPCS3.nas.log.gz)

PPU LLVM

```
F {SPU[0x2000005] Thread (Job Manager - Job Thread) [0x0bcb0]} MEM: Access violation reading location 0xe77b9e00
```

**Comment by elad335** [comment]
Its an access violation near RSPU MMIO area, the name of the issue is misleading.

**Comment by elad335** [comment]
Can I get the TTY of this?

**Comment by uaqlover** [comment]
RPCS3 v0.0.6-7932-d7ad991b Alpha | HEAD

PPU Interpreter

`F {SPU[0x2000005] Thread (Job Manager - Job Thread) [0x0bd00]} class std::runtime_error thrown: RawSPU not found (cmd=0x40, lsa=0x4b20, ea=0xe779c280, tag=0x0, size=0x400)
(in file c:\projects\rpcs3\rpcs3\emu\cell\sputhread.cpp:723)
`
PPU LLVM

`F {SPU[0x2000005] Thread (Job Manager - Job Thread) [0x0bd00]} class std::runtime_error thrown: RawSPU not found (cmd=0x40, lsa=0x4b20, ea=0xe77b8780, tag=0x0, size=0x400)
(in file c:\projects\rpcs3\rpcs3\emu\cell\sputhread.cpp:723)`



[TTY.zip](https://github.com/RPCS3/rpcs3/files/3041388/TTY.zip)

**Comment by benderscruffy** [comment]
just tried it out and have not come across the error yet
@uaqlover can you test again

**Comment by digitaldude555** [comment]
@uaqlover  retest

**Comment by uaqlover** [comment]
fixed and playable now.
