### ISSUE TITLE
rsx: SAO Lost Song - Wrong Colors

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#5720]
Wrong colors are being rendered regardless of the Render being used

**RRC**
[BLAS50790_20190313160313_capture.7z.gz](https://github.com/RPCS3/rpcs3/files/2962439/BLAS50790_20190313160313_capture.7z.gz)

**OpenGL**
![OpenGL](https://user-images.githubusercontent.com/10283761/54295063-4243b080-45aa-11e9-989a-012ec1c56775.png)

**Vulkan**
![Vulkan](https://cdn.discordapp.com/attachments/303330503392755712/555420880461758465/unknown.png)

**Expected**
![image](https://user-images.githubusercontent.com/10283761/54295441-f04f5a80-45aa-11e9-8a2b-9c79a7511b30.png)

**Comment by kd-11** [comment]
Caused by a negative result from a MAD instruction, investigating why it happens.

**Comment by AniLeo** [comment]
Still an issue with current master and current commit from kd-11/rpcs3/optimizations

**Comment by AniLeo** [comment]
Fixed by #6388
