### ISSUE TITLE
DLC Issue with JJBA ASB  

### ISSUE THREAD

**Issue by Sassorik54** [RPCS3/rpcs3#5722]
Good time of the day. I was hoping to find an advice for the game,which I have emulated for RPCS3. The game is JoJo Bizarre Adventure All Star Battle. 
I have managed to install the game properly, it works fine with good FPS, except there is a slight bug where the health bars are not displayed, but I have researched it and apparently it is a common bug that happens randomly, sadly unfixable. 
The main issue that have occurred is when I tried to download the DLC packages to the game. I have downloaded the packages successfully and tried running the game, but my emulator got an infinite mistake. The code in the configuration was sending a repeated error message and the game was stuck on an "checking installed DLC". I have tried to research this bug on forums and reddit, but sadly couldn't find a proper solution, so I was hoping to maybe get advice from somebody who ran into a similar issue. I will send out the error message right after this one
E {PPU[0x1000008] Thread (CRI FS File Access 1) [0x01511174]} LDR: EDAT: Block at offset 0x120 has invalid hash!
E {PPU[0x1000008] Thread (CRI FS File Access 1) [0x01511174]} LDR: Error Decrypting data
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2967195/RPCS3.log.gz)

**Comment by reaper185** [comment]
Always include the rpcs3.log

**Comment by Sassorik54** [comment]
How to do so? I dont know

**Comment by SaladSnake58** [comment]
you have to keep exiting and rejoining hoping to god it goes to the main menu.

**Comment by HerrHulaHoop** [comment]
Your log shows that a few DLCs are missing the license (rap) file. Your game dump is also missing files that should be there. Dump your disc properly. Head over to our [Discord server](https://discord.me/RPCS3) for help.

Please close this issue as it is an invalid report.
