### ISSUE TITLE
Musou Orochi 2 Ultimate crash issue!

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#5723]
This is the best Musou game on PS3. But  crashes frequently （please see the error logs in picture):

![未标题-1](https://user-images.githubusercontent.com/47111657/54343496-e6e0f380-4679-11e9-9993-b3c93c04762d.jpg)
![未标题-2](https://user-images.githubusercontent.com/47111657/54343668-4dfea800-467a-11e9-91f5-ced08a5ebac2.jpg)

SPU LLVM is too slow, SPU ASMJIT+MEGA is full speed , but crashes frequently :(

**Comment by reaper185** [comment]
Always include the rpcs3.log to understand the issue better

**Comment by creeperjedi** [comment]
JIT: Out of Memory crashes can also be seen in Gundam: Dynasty Warriors 3 (link to related issue: #3678) and Gundam: Dynasty Warriors 2. (They all probably use the same game engine)

In a Patreon-exclusive update (link to Patreon: https://www.patreon.com/Nekotekina/overview) it's stated that this error is planed to be fixed "soon".

**Comment by arcadee1977** [comment]
Sengoku Musou 4 [BLJM61144] crashes due to similar errors.

**Comment by Emulator-Team-2** [comment]
@arcadee1977 
Can you retest with the latest master?

**Comment by arcadee1977** [comment]
> @arcadee1977
> Can you retest with the latest master?
It's fine,no longer crash. But still freezing occasionally

**Comment by AniLeo** [comment]
Closing as crashing issue reported fixed
