### ISSUE TITLE
[BLJM61220] Kingdom Hearts 2 Final Mix Random Crash

### ISSUE THREAD

**Issue by Sirius902** [RPCS3/rpcs3#5724]
I'm running RPCS3 version 0.0.6-7869-e9b6bead on Windows 10 and when playing the game it has randomly started to crash after I updated the emulator and will hang with music still playing and refuses to be closed. Even using command prompt and task manager the process won't close until I reboot my computer. I have the compressed log below.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2969165/RPCS3.zip)

**Comment by 13xforever** [comment]
Duplicate of #5351

**Comment by AniLeo** [comment]
Closing as duplicate of #5351
