### ISSUE TITLE
[BLUS30036]Ninja Gaiden Sigma doesn´t get ingame anymore

### ISSUE THREAD

**Issue by Albin13** [RPCS3/rpcs3#5727]
The emulator freezes completely during the loading screens that appear when you load a save, start a new game or start a new mission in mission mode. This game used to be playable.

Specs:
i5 7600k OC 4.5 Ghz
GTX 1070 Zotac
Asus Maximus lX Hero
16 GB DDR4 2133 Mhz
Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2974046/RPCS3.log)

RPCS3 version: rpcs3-v0.0.6-7869-e9b6bead_win64

**Comment by Albin13** [comment]
These are my settings:
![Captura de Tela (11)](https://user-images.githubusercontent.com/17118902/54477710-f16dcb00-47e8-11e9-973e-ce5e96fc2565.png)
![Uploading Captura de Tela (10).png…]()

**Comment by Asinin3** [comment]
Works fine here, and there was a mention in one of kd-11's PR's that there was a regression with this game and it was fixed. Can you update RPCS3 and try it again?

**Comment by Asinin3** [comment]
This issue report is missing information, but regardless it was fixed by https://github.com/RPCS3/rpcs3/pull/5726 which is exactly one version higher than the build you were using. Update RPCS3.
