### ISSUE TITLE
Firmware Install not working

### ISSUE THREAD

**Issue by wpugles** [RPCS3/rpcs3#5728]
Hey guys.

I have a problem. I'm trying to install the firmware PS3UPDAT.PUP in RPCS3 and it stops and appears:

RPCS3: Fatal Error

{Firmware Installer} Unhandled exception of type 'St11logic_error': fs::file is null

Please, how can I get install the firmware correctly?

Thanks

**Comment by Zangetsu38** [comment]
you have already fw installed ?

**Comment by AniLeo** [comment]
This is not the place to ask for support

Please read the issue guidelines and ask for support on the appropriate places

**Comment by wpugles** [comment]
Ok, sorry
