### ISSUE TITLE
RPCS3 Bug

### ISSUE THREAD

**Issue by wpugles** [RPCS3/rpcs3#5729]
Hey guys.

I've been trying to run RPCS3 in my PC and it isn't working.

I try to install the PS3UPDAT.PUP firmware and it closes with a fatal error. And when i try to access any setting of the program, it closes every time.

I'm using a Notebook Lenovo T440 with;

Intel core i5-4300 
4GB RAM
GPU Intel Graphics 

My system is Linux Mint 19.1 Cinnamon

Am I doing anything wrong? Please, help me!

Thanks!

**Comment by AniLeo** [comment]
This is not the place to ask for support

Please read the issue guidelines and ask for support on the appropriate places

Looking at our specs it may not even meet rpcs3 minimum requirements, so read quickstart guide as well to be sure
