### ISSUE TITLE
[BCUS98114] SPU Recompilers: Gran Turismo 5 no longer progresses past menu since build 7825

### ISSUE THREAD

**Issue by kirbyguy22** [RPCS3/rpcs3#5730]
As of build 7825 and onwards, Gran Turismo 5 freezes at the menu using either SPUJIT or LLVM. The SPU interpreters are able to go in-game still.

Logs:
7817 (OK)
[RPCS3_GT5_7817_OK.log.gz](https://github.com/RPCS3/rpcs3/files/2974699/RPCS3_GT5_7817_OK.log.gz)

7825 (Freeze)
[RPCS3_GT5_7825_X.log.gz](https://github.com/RPCS3/rpcs3/files/2974701/RPCS3_GT5_7825_X.log.gz)

7869 (Freeze)
[RPCS3_GT5_7869_X.log.gz](https://github.com/RPCS3/rpcs3/files/2974702/RPCS3_GT5_7869_X.log.gz)

**Comment by alexloxldlol** [comment]
You need update the game at 1.05 or more, do not increase above 2.04

**Comment by AniLeo** [comment]
My non-updated version works with ASMJIT

**Comment by HHCHunter** [comment]
@Kirbyguy22, would you mind updating this issue?
I'm fairly certain this issue should be closed.
