### ISSUE TITLE
Guacamelee! Regressed to Intro after #5314

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#5740]
**Still an issue as of 11/10/2019**

After https://github.com/RPCS3/rpcs3/pull/5314 merged, Guacamelee now gets stuck on this screen.
![image](https://user-images.githubusercontent.com/15137035/54590011-1055a280-4a1f-11e9-846d-8e435742b2aa.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2982215/RPCS3.log.gz)
Note that this game requires PPU Interpreter (fast)

**Comment by elad335** [comment]
Is it fixed by using auto lib loading?

**Comment by Asinin3** [comment]
Nope.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2982282/RPCS3.log.gz)

**Comment by Asinin3** [comment]
Still an issue, also i thought it might be worth mentioning that it's odd this screen is locked to 15fps.

**Comment by AniLeo** [comment]
Worth updating so it can be checked

**Comment by elad335** [comment]
Use 3 ppu threads for now.

**Comment by benderscruffy** [comment]
goes ingame again
![guacamelee](https://user-images.githubusercontent.com/2696404/74234876-d4978b80-4d08-11ea-8450-473d3694b1ff.PNG)

**Comment by AniLeo** [comment]
Goes Ingame with 2 PPU threads normally?

**Comment by digitaldude555** [comment]
No.

**Comment by AniLeo** [comment]
Playable on **v0.0.12-10821-3c43d8fe** with default settings, closing as fixed

![image](https://user-images.githubusercontent.com/10283761/92216778-ae952c80-ee8e-11ea-96f6-ab71f081e7c4.png)

**Comment by Asinin3** [comment]
I'm still stuck on the loading screen
