### ISSUE TITLE
Fritz Chess [BLES00559] issue 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5744]
Fritz Chess [BLES00559]

![12223](https://user-images.githubusercontent.com/45731484/54605799-5141bd00-4a07-11e9-81a8-a6888cdb0d1e.png)

·W 0:01:39.580379 {PPU[0x100001f] Thread (ThreadLoad) [0x0039b580]} cellSaveData: cellSaveDataAutoLoad2(version=0, dirName=“BLES00559”, errDialog=1, setBuf=*0xd004ef40, funcStat=*0x6a4b38, funcFile=*0x6a4b28, container=0xffffffff, userdata=*0x0)
·F 0:01:39.861470 {PPU[0x100001f] Thread (ThreadLoad) [0x0039ad98]} MEM: Access violation reading location 0x4a8

i think something to do with cellSaveDataAutoLoad2

https://github.com/RPCS3/rpcs3/pull/2318

log file 

[RPCS3 Fritz Chess.log.gz](https://github.com/RPCS3/rpcs3/files/2983233/RPCS3.Fritz.Chess.log.gz)

**Comment by Asinin3** [comment]
Does it happen with native user interface disabled?

**Comment by uaqlover** [comment]
yes same thing 

![FPS_ 499 53 _ Vulkan _ 0 0 6-7881 _ Fritz Chess  BLES00559  19_03_2019 5_41_53 AM](https://user-images.githubusercontent.com/45731484/54606717-d4fca900-4a09-11e9-853c-5924d5515434.png)

**Comment by uaqlover** [comment]
after research : )

i found this game break after v0.0.3

RPCS3 v0.0.2-6-6346db2 Alpha

![FPS_ 60 78 _ OpenGL _ Fritz Chess _  BLES00559  19_03_2019 6_05_47 AM](https://user-images.githubusercontent.com/45731484/54608045-2490a400-4a0d-11e9-87fd-3b9c75b35c2b.png)

here the log file 

[RPCS3 Fritz Chess v2.log.gz](https://github.com/RPCS3/rpcs3/files/2983433/RPCS3.Fritz.Chess.v2.log.gz)

i will put update after which specific build it break

**Comment by elad335** [comment]
Retest with https://ci.appveyor.com/project/elad335/rpcs3/builds/23593934.

**Comment by uaqlover** [comment]
![FPS_ 499 62 _ Vulkan _ 0 0 6-7940 _ Fritz Chess  BLES00559  04_04_2019 7_28_57 AM](https://user-images.githubusercontent.com/45731484/55563818-768f2600-56ab-11e9-89c4-ca7b9d609b26.png)

it stop here 

log file 

[RPCS399.log.gz](https://github.com/RPCS3/rpcs3/files/3043934/RPCS399.log.gz)

**Comment by elad335** [comment]
Give log with [this](https://ci.appveyor.com/project/elad335/rpcs3/builds/23606374) build please.

**Comment by uaqlover** [comment]
with this build it's playable 

![FPS_ 461 41 _ Vulkan _ 0 0 6-7942 _ Fritz Chess  BLES00559  04_04_2019 5_09_17 PM](https://user-images.githubusercontent.com/45731484/55596257-82ef9f00-56fc-11e9-8531-26e41a1c421b.png)

![FPS_ 461 41 _ Vulkan _ 0 0 6-7942 _ Fritz Chess  BLES00559  04_04_2019 5_09_33 PM](https://user-images.githubusercontent.com/45731484/55596262-86832600-56fc-11e9-93d1-967f7d04135d.png)

intro>playable
