### ISSUE TITLE
Blur issue with Shaders cache

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5747]
if it has Shaders cache it show this 

![RPCS3_ Fatal Error 19_03_2019 7_53_27 PM](https://user-images.githubusercontent.com/45731484/54656441-db7b3700-4a82-11e9-844d-a61f95f7c6e8.png)

if i remove it Shaders cache 

1 time shows this 

(in file c:\projects\rpcs3\utilities\file.cpp:957

2 time game works 

![FPS_ 29 98 _ Vulkan _ 0 0 6-7881 _ Blur  BLUS30295  19_03_2019 8_20_38 PM](https://user-images.githubusercontent.com/45731484/54656942-d7e8af80-4a84-11e9-9c34-34bec6259c4e.png)

here the video to show the problem 

https://drive.google.com/file/d/1TBWkAqfcp7vHT-oJqCEHrI_xZam6FCYX/view?usp=sharing

**Comment by kd-11** [comment]
Retest. Also this issue is invalid/incomplete due to a missing log file!

**Comment by kd-11** [comment]
Track this in with https://github.com/RPCS3/rpcs3/issues/6356 as this game is very broken anyway.
