### ISSUE TITLE
Ni no Kuni errors in the overworld

### ISSUE THREAD

**Issue by TheStremon** [RPCS3/rpcs3#5748]
Hey guys,

I got an issue with Ni no Kuni, the games works really well, very smooth and all, except in the overworld, where I get a lot of "RSX: FS exports depth component but depth test is disabled (INVALID_OPERATION)" errors.
It seems to cause lags and stutter.

My config is the following:
i7 3770@4.0GHz
GTX 1060 6GB
32GB Ram DDR3 1333MHz

RPCS3 is the last nightly, but it was doing the same thing on previous builds too.

**Comment by kd-11** [comment]
`FS exports depth component but depth test is disabled (INVALID_OPERATION)` Is relevant to the developer of the game. It is an error on any graphics device to attempt depth export if depth test is disabled, and the PS3 is no exception. This is essentially a game bug, not an rpcs3 bug. As for the log spam causing performance issues - there is no simple way to address this. We need the message logged for debugging purposes. Maybe when rpcs3 is more mature a 'disable logging' option can be added, but this is a won't fix for me right now.
