### ISSUE TITLE
Skyrim - BLUS31202 Intro - B7888 RSX: Could not gather all required slices for cubemap/3d generation

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#5751]
Skyrim intro was always problematic, had random freezes etc, but its not skippable, so it has to work, with new version of emulator, im getting repeated freeze at same place (not everytime)
), it was in the past usually random, with same error:
**RSX: Could not gather all required slices for cubemap/3d generation**
Its spawned during whole intro.

And because of save system is now at least somehow working and game speed is quite good on 8700K and game otherwise is stable (i have some save after intro from the past), make sense to fix it. Maybe someone can do also some Skyrim video for project YT channel.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2991098/RPCS3.log.gz

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/5752

**Comment by ruthan** [comment]
Now its no spawning, but it occurs at least 15 times during the intro, its ok?

**Comment by kd-11** [comment]
It can happen without affecting visuals in some cases due to some slices not having been generated via rendering or copying. I'll close this as its not really a problem.
