### ISSUE TITLE
[BLES00289] The Incredible Hulk All renderers - Broken GFX

### ISSUE THREAD

**Issue by QuaiGoner** [RPCS3/rpcs3#5754]
On Vulkan i have this
![Снимок](https://user-images.githubusercontent.com/41058180/54837041-0f12c700-4cf8-11e9-812d-45cf7a211111.PNG)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2997321/RPCS3.log)
On OpenGL its a little bit better where effects are working correctly (explosions etc) but everything else is absent.
New KDs PR has the same problem
RSX Capture is not working and just hangs the game

GTX1050
R2400G
Win10
All latest drivers

**Comment by Emulator-Team-2** [comment]
@QuaiGoner 
The Incredible Hulk requires Strict Rendering Mode.
Close this issue.
