### ISSUE TITLE
Guilty Gear Xrd -  Revelator - runtime error thrown

### ISSUE THREAD

**Issue by Avakin28** [RPCS3/rpcs3#5755]
Specs:

i5-8250U
MX150
8GB RAM

Error: F {PPU[0x1000000] Thread (main_thread) [0x02b112fc]} class std::runtime_error thrown: Unimplemented
(in file c:\projects\rpcs3\rpcs3\emu\cell\modules\sys_libc_.cpp:450)

Happen during initial loading, everytime you run it.
RPCS3 version: 0.0.6-7884-3eb2bcad

**Comment by elad335** [comment]
Use load liblv2.sprx only option in cpu tab and close this issue.
