### ISSUE TITLE
Kingdom Hearts 1.5 and 2.5 slowdown on menu screens with Vulkan only

### ISSUE THREAD

**Issue by Cyril22** [RPCS3/rpcs3#5757]
Not a glaring issue I guess, but still probably worth explaining. In Vulkan, the menus where you choose which game to launch switches the framerate cap from 60 to 30 at random points, causing an audio desync. On the title screens of the three games that I tested (KH 1, Chain of Memories, and KH2) the FPS can drop as low as 2 fps. None of these issues happen with OpenGL. I'm using the master build 0.0.6-7901.

Specs: 
i5 8300h (set to reach a max of 3.4 GHz)
GTX 1060 (driver version 398.36)
8gb RAM

Images
https://imgur.com/a/wwZK1iI

Edit: I had vsync enabled in my Nvidia control panel when I did the tests, and decided to try without it. Turns out that was what caused menu screens to get framerate drops in Vulkan. Same thing happens when I enable vsync in RPCS3. Can anybody with more recent Nvidia drivers try this out? Since it doesn't occur in OpenGl, I'm thinking it could be a driver problem.  
  
Edit 2: Setting the emulator's framelimiter to 60 fps in combination with vsync stops the menus of the individual games from slowing down, but the collection menu still drops to 30 fps randomly.

**Comment by Sammy789** [comment]
Same issues for me too. I have tried to run GoW HD Collection in Vulkan, but somehow the game suffers abysmal slowdown. Thus, switching to OpenGL Renderer seems more accurate with no slowdown whatsoever.

**Comment by darkash** [comment]
tried reproducing this, but it seems like this is no longer an issue
<details>
<summary>KH 1.5</summary>

![image1](https://user-images.githubusercontent.com/2842880/75265086-f58cd000-5822-11ea-8dcc-939f3ef77801.png)
![image2](https://user-images.githubusercontent.com/2842880/75265179-19501600-5823-11ea-98b9-25cd976878b7.png)

</details>
I tried moving between game entries in there as well and it's stable 57 fps (my laptop screen frame rate is 57 Ghz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4250965/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Closing as fixed
