### ISSUE TITLE
cellCamera TODO: cellCameraGetType

### ISSUE THREAD

**Issue by Zaza06** [RPCS3/rpcs3#5772]
I tried it on Heavy rain[BCUS98164] with the latest Master 7916, following log is being spammed.
cellCamera TODO: cellCameraGetType(dev_num=0, type=*0xd0020900)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3026135/RPCS3.log)

**Comment by Zangetsu38** [comment]
this is "Normal" this function is not implemented

**Comment by AniLeo** [comment]
Don't need to report that kind of standard library TODO stuff, it's known that's yet to be implemented
