### ISSUE TITLE
Game slowdowns when running Vulkan API on God of War 1 & 2 HD Collection [BCUS98229]

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#5773]
For some reason, the game slows down when I run with Vulkan API on God of War 1 & 2 HD  Collection [BCUS98229] which animation looks choppy, juddery, not smooth (even at 60fps). Yet somehow, running OpenGL seems to be more accurate with no slowdown but it's slower than Vulkan. Already tested latest and previous build (0.0.5-7761), but none of it helps at all. Please fix the game slowdown for Vulkan Render. 

Log: RPCS3 v0.0.5-7761-88639ae8 Alpha | HEAD
Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz | 16 Threads | 63.95 GiB RAM | AVX+ | TSX

Weird screen artifact when booting God of War HD Collection (Vulkan Renderer).
<img width="1280" alt="god of war hd collection screen error" src="https://user-images.githubusercontent.com/49124947/55291870-bc40ab80-5398-11e9-9107-7a4fe2a3d0eb.PNG">

No screen artifact when booting God of War HD Collection (OpenGL Renderer)
<img width="1280" alt="no screen artifact god of war hd collection" src="https://user-images.githubusercontent.com/49124947/55292104-6cafaf00-539b-11e9-9c44-1267bcd455b4.PNG">

Spec: 
i9-9900k
RTX 2080 Ti
64GB DDR4 RAM

> The logs are still empty, run the game, get to the issue, post that log

Currently testing latest RPCS3 build 0.0.6-7929.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3026874/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3026875/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Missing log, system specifications..

**Comment by Asinin3** [comment]
Also make sure you have shaders compiled. If you load into a game for the first time with a different renderer (be it openGL or Vulkan) RPCS3 will need to compile a new shader cache. So, to best compare renderer performance, just stand in one spot for a bit to make sure there's no slow-down from shaders being compiled. You can see when shaders are being compiled in the bottom left corner of the game window. If it's slow while that message is on-screen then it's completely normal.

**Comment by AniLeo** [comment]
Your log file is empty and is from a really outdated build, you have to be running latest master to submit issue reports

**Comment by RainbowCookie32** [comment]
The logs are still empty, run the game, get to the issue, post that log

**Comment by AniLeo** [comment]
You have a lot of wrong settings like

>  Preferred SPU Threads: 6
>  SPU Block Size: Giga

Again, you can't submit issue reports on experimental settings that aren't fully implemented like Giga

Set everything to default, change SPU to SPU LLVM, Render to Vulkan and run the game.

**Comment by dlim389** [comment]
> You have a lot of wrong settings like
> 
> > Preferred SPU Threads: 6
> > SPU Block Size: Giga
> 
> Again, you can't submit issue reports on experimental settings that aren't fully implemented like Giga
> 
> Set everything to default, change SPU to SPU LLVM, Render to Vulkan and run the game.

Okay, I'll try that. I'll let you know to see how it goes.

**Comment by Emulator-Team-2** [comment]
@dlim389 
Don't change the resolution from the recommended 1280x720.
Because it can cause such problems as in the first screenshot.

**Comment by AniLeo** [comment]
I did say to leave as default which is 720p

**Comment by dlim389** [comment]
Already tested 720P resolution after I changed from 1080P to 720P resolution. As a result, game still slows down while running Vulkan Render.

**Comment by kd-11** [comment]
Change vsync options in nvidia control panel to force fast sync.

**Comment by kd-11** [comment]
Pretty sure this should not be an issue anymore with recent improvements. Request to reopen if the issue is still present.
