### ISSUE TITLE
Feature Request:Prevent screen saver\off during gameplay

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5777]
While watching a long cut scene,the screen turns off(it is set to do so after 10 minutes but sometimes that's still not enough)

**Comment by al3xtjames** [comment]
It looks like SetThreadExecutionState() is repeatedly called whenever a button is pressed (for the XInput/DS3/DS4 handlers on Windows only). Perhaps this could be changed by calling SetThreadExecutionState() with ES_CONTINUOUS (removes the need for repeated calls) in Emulator::Run() (with additional calls to reset it in Emulator::Pause() and Emulator::Stop()).

**Comment by Megamouse** [comment]
is this still an issue?

**Comment by RainbowCookie32** [comment]
Just tested on Manjaro and it seems to be fixed
