### ISSUE TITLE
Newer Windows 10 versions perfomance regression

### ISSUE THREAD

**Issue by Tahei** [RPCS3/rpcs3#5779]
I found that 18xx Windows 10 builds provide worse perfomance than 16xx. For example I've tried to run Persona 5 on Win10 1809 and Windows 1607. Difference is on screens below.

Win 10 1607:
![Win10_1607](https://user-images.githubusercontent.com/49169556/55356590-c61af980-54d3-11e9-8df7-2345fca30c2b.png)

[RPCS3Win10_1607.log.gz](https://github.com/RPCS3/rpcs3/files/3031167/RPCS3Win10_1607.log.gz)

Win 10 1809:
![Win10_1809](https://user-images.githubusercontent.com/49169556/55356605-ce733480-54d3-11e9-9738-28d7ad30d30e.png)

[RPCS3Win10_1809.log.gz](https://github.com/RPCS3/rpcs3/files/3031168/RPCS3Win10_1809.log.gz)

**Comment by 13xforever** [comment]
As I asked you on Discord, do you use Windows Defender? And if so, is disabling Real-time protection restores the performance?

**Comment by Tahei** [comment]
> As I asked you on Discord, do you use Windows Defender? And if so, is disabling Real-time protection restores the performance?

No it is permanent disabled.
Also i did clean windows instalation for both builds. No changes.

**Comment by kd-11** [comment]
Intel vulnerability mitigations maybe?

**Comment by CrabLugo** [comment]
or windows game mode enabled/disabled?

**Comment by Tahei** [comment]
There is no game mode in 1607 and in 1809 it made no impact.

**Comment by AniLeo** [comment]
There's a difference of 3 threads between screenshots too, weird

**Comment by cloud1250x4** [comment]
Possible to take a screenshot with the taskmanager open? (for both version of windows 10?)

**Comment by Tahei** [comment]
> Possible to take a screenshot with the taskmanager open? (for both version of windows 10?)

like this?

![unknown](https://user-images.githubusercontent.com/49169556/55637409-a7677c00-57cd-11e9-8599-7a11a0a90e8e.png)

**Comment by vsub** [comment]
On 1809 you are using newer nvidia drivers(maybe it's coming from them)

Win10 1607 - 372.280
Win10 1809 - 419.67.0

**Comment by Tahei** [comment]
> On 1809 you are using newer nvidia drivers(maybe it's coming from them)
> 
> Win10 1607 - 372.280
> Win10 1809 - 419.67.0

No, drivers does not affect perfomance.

**Comment by vsub** [comment]
I am not so sure about that...I think I notest some speed drop while I was playing Atelier Shallie and I update my drivers at one point(actually windows did that without asking)

**Comment by RainbowCookie32** [comment]
> > On 1809 you are using newer nvidia drivers(maybe it's coming from them)
> > Win10 1607 - 372.280
> > Win10 1809 - 419.67.0
> 
> No, drivers does not affect a perfomance.

There's a big difference in driver versions in this case, you should make the tests as similar as possible to discard possible differences that could influence the results

**Comment by Tahei** [comment]
> I am not so sure about that...I think I notest some speed drop while I was playing Atelier Shallie and I update my drivers at one point(actually windows did that without asking)

I am shure, because i tried it.

**Comment by Tahei** [comment]
> > > On 1809 you are using newer nvidia drivers(maybe it's coming from them)
> > > Win10 1607 - 372.280
> > > Win10 1809 - 419.67.0
> > 
> > 
> > No, drivers does not affect a perfomance.
> 
> There's a big difference in driver versions in this case, you should make the tests as similar as possible to discard possible differences that could influence the results

Only difference i notticed that old drivers has glitchy textures in GoW 3.
The problem is somewhere in Windows, because i did clean instalation of it and it give me nothing.

**Comment by Tahei** [comment]
Tried Demon’s Souls today, its also shows a difference in total threads. Older windows runs it a lot smoother.
![83F2CA94-9121-46D3-B5EA-AD337F9E883D](https://user-images.githubusercontent.com/49169556/55658235-96d2f800-5805-11e9-8a69-1feb2b6dc940.jpeg)
![212A0941-548E-4B9C-858E-1B69912117E5](https://user-images.githubusercontent.com/49169556/55658236-96d2f800-5805-11e9-8928-9728c044ba7c.jpeg)

**Comment by Tahei** [comment]
> I am not so sure about that...I think I notest some speed drop while I was playing Atelier Shallie and I update my drivers at one point(actually windows did that without asking)

I was a bit wrong guys. Newest drivers instaled on older system gave me 3 fps drop. But 372.28 on newer Windows build gave me 1 - 2 fps boost. So newer drivers really degrade perfomance.

But unfortunately this doesn't change this situation in general.
It's somwhere in hypertreding and windows comunication i think. Because when i disable hyperthreading its starts to work the same on both versions.
On 4c4t Persona 5 shows more fps than 4c8t everywhere in the game (but 4c4t also gives u a little amount of micro freezes)

**Comment by 13xforever** [comment]
Run [this script](https://support.microsoft.com/en-us/help/4074629/understanding-the-output-of-get-speculationcontrolsettings-powershell#section-1) and post output from both versions of windows.

**Comment by Tahei** [comment]
> Run [this script](https://support.microsoft.com/en-us/help/4074629/understanding-the-output-of-get-speculationcontrolsettings-powershell#section-1) and post output from both versions of windows.
Windows 10 1809
Hardware is vulnerable to L1 terminal fault: True
Windows OS support for L1 terminal fault mitigation is present: True
Windows OS support for L1 terminal fault mitigation is enabled: True


BTIHardwarePresent                  : True
BTIWindowsSupportPresent            : True
BTIWindowsSupportEnabled            : True
BTIDisabledBySystemPolicy           : False
BTIDisabledByNoHardwareSupport      : False
BTIKernelRetpolineEnabled           : False
BTIKernelImportOptimizationEnabled  : False
KVAShadowRequired                   : True
KVAShadowWindowsSupportPresent      : True
KVAShadowWindowsSupportEnabled      : True
KVAShadowPcidEnabled                : False
SSBDWindowsSupportPresent           : True
SSBDHardwareVulnerable              : True
SSBDHardwarePresent                 : False
SSBDWindowsSupportEnabledSystemWide : False
L1TFHardwareVulnerable              : True
L1TFWindowsSupportPresent           : True
L1TFWindowsSupportEnabled           : True
L1TFInvalidPteBit                   : 45
L1DFlushSupported                   : False

**Comment by Tahei** [comment]
Windows 10 1607

![unknown](https://user-images.githubusercontent.com/49169556/55662491-5763d600-581c-11e9-8e6e-34657d516a44.png)

**Comment by 13xforever** [comment]
Well, there's your answer. nVidia also added some spectre mitigations in several driver releases around 39x series.

You see the noticeable performance hit only because your xeon is very old and there's no effective speed mitigations could be applied like on skylake and newer cpus. Especially with HT enabled.

You'll either have to live with the reality, or manually disable all protections and leave your system exposed to speculative attacks to gain a couple of fps back.

**Comment by Tahei** [comment]
Guys, if u need to disable Spectre/Meltdown mitigations, use this video for help:
https://www.youtube.com/watch?v=W-AHuwfyLoo

**Comment by 13xforever** [comment]
Please do not encourage or promote bad security practices. Every user who wants to do this must learn and understand the implications of every change. Do not blindly follow some youtube guide :-/
