### ISSUE TITLE
RPCS3 always crashes on game exit\stop while using OpenGL

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5786]
I don't know if it is just here(nvidia 419.35)but no matter what I run(even the demos in dev_hdd0\game\TEST12345\USRDIR),closing the game window cases rpcs3 to crash with Fatal Error coming from nvoglv64.dll'

---------------------------
RPCS3: Fatal Error
---------------------------

Segfault reading location 000000000c0fa0b0 at 00000000598081e9.<br>
Instruction address: 00000000598081e9.<br>
Function address: 00000000598081c0 (base+0xaf81c0).<br>
Module name: 'nvoglv64.dll'.<br>
Module base: 0000000058d10000.<br>
RPCS3 image base: 0000000000010000.<br>
<br>	

---------------------------
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3034657/RPCS3.zip)

Edit:Yes,nvidia only...when I use my intel card,it does not crash

**Comment by LordDuma** [comment]
![Capture](https://user-images.githubusercontent.com/50001441/56775532-0dbc3a80-678d-11e9-9098-a7226a3e005d.PNG)

**Comment by LordDuma** [comment]
What seems to be the problem here?

**Comment by LordDuma** [comment]
![Capture](https://user-images.githubusercontent.com/50001441/56777305-5a584380-6796-11e9-8b51-f21fa29bc5d8.PNG)

**Comment by kd-11** [comment]
I'm not seeing this issue. Using 425 series drivers.

**Comment by vsub** [comment]
I also don't see this while using the latest drivers.

**Comment by LordDuma** [comment]
It has done this every time I try playing a game on RPCS3.

**Comment by kd-11** [comment]
Which drivers are you using @LordDuma? Maybe something limited to windows 7?

**Comment by LordDuma** [comment]
It has a AMD touchscreen graphics processor. Maybe that?

**Comment by AniLeo** [comment]
Can not reproduce

Tested with Intel HD 530 and NVIDIA GTX 960M on Windows 7 with OpenGL and Vulkan with gs_gcm_cube

**Comment by CrabLugo** [comment]
Maybe just try to unistall NVIDIA drivers and unistall only GPU drivers. It's most likely due to broken drivers. According to my google search skills.

**Comment by LordDuma** [comment]
> Can not reproduce
> 
> Tested with Intel HD 530 and NVIDIA GTX 960M on Windows 7 with OpenGL and Vulkan with gs_gcm_cube
> 
> Tested with NVIDIA Driver 430.39 and whatever is the latest Skylake driver Intel released for Windows 7

So how can I fix this?

**Comment by AniLeo** [comment]
Fix what? I literally said in my comment I can't find any issue

Also, you're spamming with unrelated input as your crash doesn't mention OpenGL drivers and you're not even running an NVIDIA card.

**Comment by AniLeo** [comment]
> I also don't see this while using the latest drivers.

@vsub @isshininu
You can't reproduce on latest drivers? If you can't, the issue can be closed, because no one is being able to reproduce this issue at all. If you can, provide more details to what setup you're using (CPU, GPU, OS and Drivers Version)

**Comment by vsub** [comment]
Umm,I thought the issue will be closed by some dev when I mention that I don't have the problem anymore
The fix is to update the nvidia drivers
