### ISSUE TITLE
[BLUS30011] Tony Hawk's Project 8  can't skip bink videos, intro, cutscenes

### ISSUE THREAD

**Issue by kamer1337** [RPCS3/rpcs3#5791]
this issue is happening since forever
**LOG:**
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3046874/RPCS3.log.gz)

**Comment by scribam** [comment]
According to https://www.reddit.com/r/patientgamers/comments/ugatb/i_bought_tony_hawks_project_8_earlier_this_week/
> You can't skip the intro screens for Activision and Neversoft.

So I think this issue can be closed.
