### ISSUE TITLE
shader loading screen issue (minor severity)

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#5793]
The background image of the shader loading screen (PIC0.png) turns greyscale if you make RPCS3 go fullscreen while the shader compilation is ongoing. The colors return once you make it return to windowed mode.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3048104/RPCS3.log.gz)

See system info in the logs. I don't have a clue since when this issue is possibly present,

**Comment by vsub** [comment]
Maybe it's the same thing as in my case
https://github.com/RPCS3/rpcs3/issues/5664

**Comment by nitrohigito** [comment]
@vsub Entirely possible, will update drivers and retest later today. Thanks.

**Comment by dio-gh** [comment]
Wtf, thought I already closed this smh
