### ISSUE TITLE
Ashes Cricket 2009 [BLES00639] issue

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5795]
i was trying to get ingame but no lock at all 

try it to enable Debug Console Mode 

and try it ppu and llvm all same 

![5588](https://user-images.githubusercontent.com/45731484/55670312-a9febb80-5837-11e9-82dc-dec47fd187fb.png)

[RPCS3opengl.zip](https://github.com/RPCS3/rpcs3/files/3050522/RPCS3opengl.zip)

[RPCS3vl.zip](https://github.com/RPCS3/rpcs3/files/3050523/RPCS3vl.zip)

**Comment by elad335** [comment]
Please check the tty and upload it if not empty, especially in cases like this where the game prints one gigantic message right before it crashes :p

**Comment by AniLeo** [comment]
Closed due to clear signs of piracy

**Comment by uaqlover** [comment]
in tty 

`ERROR - LIBAUDIO DROPOUT - LIBAUDIO POSITION NO LONGER INCREMENTING!!
ERROR - LIBAUDIO DROPOUT - LIBAUDIO POSITION NO LONGER INCREMENTING!!
ERROR - LIBAUDIO DROPOUT - LIBAUDIO POSITION NO LONGER INCREMENTING!!
ERROR - LIBAUDIO DROPOUT - LIBAUDIO POSITION NO LONGER INCREMENTING!!
ERROR - LIBAUDIO DROPOUT - LIBAUDIO POSITION NO LONGER INCREMENTING!!
exception: bad allocation
`
