### ISSUE TITLE
[NPUB30811] Ferrari Racing Legends is loading infinitely

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5796]
issue with Ferrari Racing Legends [NPUB30811]

now the game is intro 

![FPS_ 36 88 _ Vulkan _ 0 0 6-7932 _ Ferrari Racing Legends  NPUB30811  06_04_2019 10_01_57 AM](https://user-images.githubusercontent.com/45731484/55672768-982b1180-5853-11e9-9f7e-5dcaee9d4eb1.png)

also try it with @elad335 build https://github.com/RPCS3/rpcs3/pull/5792

[RPCS3 2.log.gz](https://github.com/RPCS3/rpcs3/files/3050720/RPCS3.2.log.gz)

[RPCS3 el.log.gz](https://github.com/RPCS3/rpcs3/files/3050719/RPCS3.el.log.gz)

tty 

[TTY.zip](https://github.com/RPCS3/rpcs3/files/3050716/TTY.zip)

**Comment by Asinin3** [comment]
This game didn't regress from what i can tell and it has always been broken according to compatibility database. The GitHub issue tracker is not for compatibility reports of "this game doesn't work" it's for "this game used to work, but then **this** pull request broke it" etc.

**Comment by uaqlover** [comment]
so it could be fix it or should i close the issue

**Comment by elad335** [comment]
Don't close, you can rename it to something like "[NPUB30811] Ferrari Racing Legends is loading infinitely".
This way its a little more informative and looks better as an issue.

**Comment by benderscruffy** [comment]
this can be closed
![test](https://user-images.githubusercontent.com/2696404/62940450-346ab380-be06-11e9-965d-6d370a8cea08.PNG)
