### ISSUE TITLE
[Regression]: MLB 09 The Show regressed to Intro only if a game save is created / auto-load enabled

### ISSUE THREAD

**Issue by incognitoh** [RPCS3/rpcs3#5798]
This is an old regression that occurred in August 2018, but has yet to be addressed so I am reporting it now. The good news is I know the exact PR that broke it.

MLB 09 The Show BCUS98180 was in-game but regressed to intro with Nekotekina's Split fixes #4975 PR back in August 2018. 

The last build to work with this game was 0.0.5-7182, which allowed the game to go ingame / gameplay. But after that, the game is intro only. Now, just the opening FMVs play but it crashes right before it loads into the main menu. Something in the Split fixes PR broke the game and stopped it from going into the opening menu.

![MLB09](https://user-images.githubusercontent.com/39333810/55681977-9f592a80-58fa-11e9-9df5-a6ff8e784870.JPG)

The error reads as:

F {PPU[0x1000008] Thread (Utility PPU Thread) [0x00013500]} MEM: Access violation reading location 0xd2d0a0a0

I have tried multiple settings and fresh installs with the same result.

One thing that is odd, is that with a fresh install, the game requires you to install a few gb of install files. Sometimes with a new install, the game will get to the opening menus and gameplay. But after you shut down the emulator and return, the game will not work again.

specs:
i7 4790k
gtx1070
16gb RAM
Win10

Log from 0.0.6-7934 included

[RPCS3 MLB09.zip](https://github.com/RPCS3/rpcs3/files/3051419/RPCS3.MLB09.zip)

**Comment by elad335** [comment]
Retest with #5816

**Comment by incognitoh** [comment]
Hi @elad335 

No, it still does not work. Using this build: https://ci.appveyor.com/project/rpcs3/rpcs3/builds/23754448

It has the same behavior as before. On a fresh install of the emulator and game, it goes to menus and gameplay just fine. But once the emulator is shut and reopened, the game only goes to intro again and gives this error every time:   

{PPU[0x1000008] Thread (Utility PPU Thread) [0x00013c20]} MEM: Access violation reading location 0xe2e0b0b0

**Comment by incognitoh** [comment]
hi @elad335 

Tried again with this latest build: https://ci.appveyor.com/project/rpcs3/rpcs3/builds/23779297/artifacts

Still not working. Same issue.

**Comment by incognitoh** [comment]
@elad335 

Quick update. After further testing with newer builds, it turns out that it is the game save that is preventing it from starting. In this game, when you first start, you are given the option to make a profile save right away. If you do make one, the game will not load after you shut down the emulator and reload the game. The profile game save that is created seems to be preventing the game from starting. If you _don't_ create a save, the game will start and work properly every time.

So this is still a regression but it definitely seems to be related to the save file that is created. Any ideas of what I should try? If so, let me know. Thanks.

**Comment by connorwalks** [comment]
This is still an issue for me. Can we re-open this issue? Any save file loaded either manually or through auto-load will instantly cause a crash. 

Also could you link me to whichever build specifically fixed the issue for you? I'd rather not retest 6 months of PRs blindly

**Comment by connorwalks** [comment]
@AniLeo I've tried PRs from around June 4 (when the issue was closed) and it seems as if the issue was closed for no reason. Since the original author is no longer active can you re-open this? Or would you rather me start a new issue?

**Comment by AniLeo** [comment]
You can open a new one with current information if it's still an issue
