### ISSUE TITLE
Qt: Scrollbar placement in gamelist window

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#5800]
The current scrollbar placement in the gamelist window makes comprehensive theming a pain. Would it be possible to move the scrollbar into the confines of the gamelist window? Or is this a conscious choice?

Here's a mock-up of the suggestion:
![scrollbar_placement](https://user-images.githubusercontent.com/49168108/55684235-99426880-5951-11e9-9c24-c7cd7c8c6ea4.png)

**Comment by drysalter** [comment]
The trophy manager has the same scrollbar placement.

**Comment by Megamouse** [comment]
That's how tables work.
You might be able to do it in your own stylesheet.
But this is not something worth wasting time on imo.

**Comment by Megamouse** [comment]
Closing because of missing relevance and feasability.
