### ISSUE TITLE
issue with NASCAR '14 and 15

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5803]
issue with NASCAR '14 and 15

![551](https://user-images.githubusercontent.com/45731484/55692011-a747b780-5958-11e9-8c0c-a8ccc33eb759.png)

i think something with 'cellSaveDataListAutoLoad' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT 

i also try it with @elad335 build is same https://github.com/RPCS3/rpcs3/pull/5792

**Comment by uaqlover** [comment]
the log file

[RPCS3 nas 2014.zip](https://github.com/RPCS3/rpcs3/files/3056009/RPCS3.nas.2014.zip)

**Comment by elad335** [comment]
This game has `·E 0:00:22.739467 {PPU[0x1000000] Thread (main_thread) [0x01b41250]} cellGame: cellGameContentPermit(): failed to initialize directory '/dev_hdd0/game/BLUS31378' (Access violation)` on master.
should be fixed now that #5784 merged.

**Comment by uaqlover** [comment]
yep fixed https://github.com/RPCS3/rpcs3/pull/5784

thanks @elad335 for taking time to trying fix the issues : ) 

game from intro > ingame

![FPS_ 30 01 _ Vulkan _ 0 0 6-7952 _ NASCAR '14  BLUS31378  10_04_2019 7_23_17 AM](https://user-images.githubusercontent.com/45731484/55887040-aafa5a80-5b61-11e9-9c3c-2787650124e5.png)
