### ISSUE TITLE
RPCS3 system clock(date)don't update until you restart rpcs3

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5804]
I am not sure what exactly to do to make a useful log but this is the situation.

In Tales of Xillia 2 there is a feature(kitty dispatch)which gives you different bonuses depending on the day of the week.
RPCS3 seems to synchronize the PS3 clock with the current time upon starting rpcs3 and never update it after that.

For example I start the game in Sunday=>stop it at one point(just close the game window to stop the emulation)=>run the game again without closing rpcs3 first on the next day=>when I check the active bonus,the bonus is still for Sunday

If I close rpcs3 and run the game,then the date will be changed to Monday.
When I use kitty dispatch and when I check the progress,I often get a message that the PS3 system clock was changed and search failed.

**Comment by bevanweiss** [comment]
Is this still an issue?
In having a very superficial look at the date/time code a few days ago, it does appear that it should be working as expected (reported rpcs3 wall clock time matches host PC)

**Comment by Sora3100** [comment]
I can confirm that this was fixed a while ago.

**Comment by bevanweiss** [comment]
@vsub (or @AniLeo) can you please close this issue?
