### ISSUE TITLE
NBA 2K11 [BLUS30574] Memory Leak 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5805]
CellGem log spam same as https://github.com/RPCS3/rpcs3/issues/5616 after that game will freeze

log file 

[RPCS3 nba 2011.log.gz](https://github.com/RPCS3/rpcs3/files/3055745/RPCS3.nba.2011.log.gz)

**Comment by HerrHulaHoop** [comment]
If it's the same as that issue, post your log and information there. Don't create separate threads for each game.

**Comment by uaqlover** [comment]
https://github.com/RPCS3/rpcs3/issues/5616
