### ISSUE TITLE
God Of War 3 physics bug

### ISSUE THREAD

**Issue by Wizzy2018** [RPCS3/rpcs3#5806]
Rpcs 3 0.0.6-7947 version

Just started playing God of War 3 and when i reach the first Boss suddenly Kratos dissapears! And a screen goes black and it says You Died! After that screen stuck and emulator don't respond to anything i need to close it to be able to use it again.

CPU-Ryzen 7 1700
RAM-DDR4-2400Mhz
GPU-RX 470 4Gb

Here is a screenshoot 
A resolution is default 1280x720

Here is a part when Kratos dissapears

![FPS_ 14 56 _ Vulkan _ 0 0 6-7947 _ God of War® III  BCES00510  09-Apr-19 15_00_28](https://user-images.githubusercontent.com/44261686/55802893-73e06680-5ad9-11e9-8c72-8151749e5727.png)

**Comment by RainbowCookie32** [comment]
Attach a log when creating an issue.

Reproduce the issue, close RPCS3, grab RPCS3.log from the emulator's folder and add it to your original post

**Comment by Asinin3** [comment]
Log won't help with this. But either way it's a random bug that happens from time to time. You just need to try a few more times and eventually you will be attached to the ground on this section. It's one of many reasons the game is not listed as playable.

**Comment by Wizzy2018** [comment]
Here it is a log file and the screenshoot

![FPS_ 17 46 _ Vulkan _ 0 0 6-7947 _ God of War® III  BCES00510  09-Apr-19 17_44_00](https://user-images.githubusercontent.com/44261686/55814588-266ef400-5aef-11e9-89e3-58e239cc8c20.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3059840/RPCS3.log.gz)

**Comment by QuaiGoner** [comment]
I have that issue too, i think this happens because of the low framerate and Kratos spawns somewhere behind the wall that you should climb or something and starts to fall where on real HW you need to climb

**Comment by MSuih** [comment]
It's a known fact that GOW 3 physics break if perfomance is not ideal. The game can be played from start to finish on overclocked 8700k but anything slower than that will probably run into issues. Improving SPU performance should eventually fix this.

**Comment by RandomP8** [comment]
The game can be played from start to finish on overclocked 8700k...

this is crazy!

**Comment by Wizzy2018** [comment]
I have now another problem.
I getting this error now on latest build of RPCS 3 0.0.6-8002
Here is a log file
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3100567/RPCS3.log.gz)

**Comment by kd-11** [comment]
Retest. All problems here are caused by sub-optimal performance; maybe the recent improvements may have alleviated most of them.

**Comment by Wizzy2018** [comment]
I test it soon and report back to you

**Comment by QuaiGoner** [comment]
Ryzen 5 2400G
GTX 1050
Latest Drivers

Same issue, perfomance is still too low. Maybe something chaged for more powerful processors that could not get through that sequence

**Comment by Wizzy2018** [comment]
I retest it.On my Ryzen 7 1700 3.2@Ghz same issue nothing changed.One thing i noticed when i disable in cpu option a Thread scheduler i gain 5-6 more fps and my fps is more stable.When i enable thread scheduler it going very slow and fps jumping from 1-15fps every sec.

**Comment by Wizzy2018** [comment]
I just think this emulator is not optimized for Ryzen cuz it was mostly favored Intel.I don't believe 8 core 16 thread Cpu can't run it well with 3.2 Ghz and God of War usses only 50 % of Ryzen cpu so there is enough room left for a boost

**Comment by kd-11** [comment]
Thread scaling does not work like that. You cannot split a PS3 hardware thread into multiple simulated threads so 50% is about where a PS3 system would map to a Ryzen 7 (2 PPE + 6 SPE threads). 3.2 Ghz is also very slow, consider overclocking to 3.6-3.9. The reason newer intel performs so much better is because of TSX technology, for which AMD has no alternative in the real world. TSX makes a huge difference because it closely matches PS3 behavior and does not require complicated workarounds. I have a Ryzen processor as well so this claim about rpcs3 being anti-AMD is just not true. While AMD has proposed processor extensions for transactional memory, none have been actually implemented in hardware to date. See https://en.wikipedia.org/wiki/Advanced_Synchronization_Facility

**Comment by Wizzy2018** [comment]
Thx for explain KD-11.
Do you think is it possible somewhere in future we see Ryzen 7 better
performance??

**Comment by kd-11** [comment]
Well, yes of course, its just a lot harder than on intel where we have hardware assistance to emulate difficult features. Performance on all processors does improve just slower on some processors than others. Compared to where performance was at ryzen launch, performance has gone up an order of magnitude in most games. Its just that this specific game is one of the last ones that are still slow.

**Comment by Wizzy2018** [comment]
I want to say Thx KD-11 for a hard work you doing with this emulator 😘
Love you bro <3

**Comment by Wizzy2018** [comment]
So i tested again with Overclocking my R7 1700 to 3.7Ghz and i past a screen where i was stuck but after a fight wit a water horse is done i got this screen and i stuck there.
[God of War® III [BCES00510] 2019-07-12 09-28-49.zip](https://github.com/RPCS3/rpcs3/files/3385455/God.of.War.III.BCES00510.2019-07-12.09-28-49.zip)

**Comment by jeremybris** [comment]
Try this game again. It may have been recently fixed.

**Comment by AniLeo** [comment]
Accuracy differences between Interpreters and Recompilers are known, may not be fixed

**Comment by RainbowCookie32** [comment]
Just played through this area and couldn't reproduce the issue with the same CPU. 

Issue can probably be closed, unless OP can still reproduce it on latest master.

**Comment by Xcedf** [comment]
Oh come on, the game just needs to be fast enough
here's the example, issue still here when i use SPU Interpreter and it runs very slow
even ASMjit is enough for me to pass it
https://youtu.be/qBWbjji2U1g

**Comment by Asinin3** [comment]
It happens on my R7 1700 @3.9ghz consistently even when my fps is 23-26 there.
![image](https://user-images.githubusercontent.com/15137035/75617339-c02f0c00-5bad-11ea-8b9c-9478250b86fc.png)

And yet I've seen another person with an 8700k having the issue too, though his 8700k was at stock he was using the right settings. I still think it's performance related, but it seems to require quite a lot of FPS for it not to happen.

**Comment by lokeshsharmaj** [comment]
I am Stuck on Chapter 4: The Flame of Olympus where Kratos is running after Hermes and he goes in a door and closes it and we need to climb vertical stairs from left side then jump to right side then in the end we need to jump in the left side stairs but Kratos never catch the stairs but in game it catches and climb at the top. This bug happened with me. even if I restarted from checkpoint or loading from last save (which is a round room where heremes come and he is sitting on roof after we leave the round room).

**Comment by lokeshsharmaj** [comment]
> It happens on my R7 1700 @3.9ghz consistently even when my fps is 23-26 there.
> ![image](https://user-images.githubusercontent.com/15137035/75617339-c02f0c00-5bad-11ea-8b9c-9478250b86fc.png)
> 
> And yet I've seen another person with an 8700k having the issue too, though his 8700k was at stock he was using the right settings. I still think it's performance related, but it seems to require quite a lot of FPS for it not to happen.

this happened only first time with my pc, at second time this issue didn't happen but I faced vertical stair climbing bug at chapter 4 when Kratos is running after Hermes.

**Comment by ChenSmallX** [comment]
> I am Stuck on Chapter 4: The Flame of Olympus where Kratos is running after Hermes and he goes in a door and closes it and we need to climb vertical stairs from left side then jump to right side then in the end we need to jump in the left side stairs but Kratos never catch the stairs but in game it catches and climb at the top. This bug happened with me. even if I restarted from checkpoint or loading from last save (which is a round room where heremes come and he is sitting on roof after we leave the round room).

Hello bro, this problem happened in my pc just right now, did you solve it?
And I found a method to let the game go on to trace Hermes, but the game run on a low FPS mode(maybe the reason is my GPU is GTX1066, hah)

just need to change the renderer to `OpenGL` (not the `Vulkan`), and start the game.

Then change the settings back while Kratos passed this place.

![image](https://user-images.githubusercontent.com/24445771/195131920-094ebdf5-aba2-493b-8ab2-91a4996d5de2.png)

I hope it can help you really~

**Comment by marwanhxh** [comment]
> > I am Stuck on Chapter 4: The Flame of Olympus where Kratos is running after Hermes and he goes in a door and closes it and we need to climb vertical stairs from left side then jump to right side then in the end we need to jump in the left side stairs but Kratos never catch the stairs but in game it catches and climb at the top. This bug happened with me. even if I restarted from checkpoint or loading from last save (which is a round room where heremes come and he is sitting on roof after we leave the round room).
> 
> Hello bro, this problem happened in my pc just right now, did you solve it? And I found a method to let the game go on to trace Hermes, but the game run on a low FPS mode(maybe the reason is my GPU is GTX1066, hah)
> 
> just need to change the renderer to `OpenGL` (not the `Vulkan`), and start the game.
> 
> Then change the settings back while Kratos passed this place.
> 
> ![image](https://user-images.githubusercontent.com/24445771/195131920-094ebdf5-aba2-493b-8ab2-91a4996d5de2.png)
> 
> I hope it can help you really~

Thank you king it worked for me
5600X
3060

**Comment by abhmyn** [comment]
> > I am Stuck on Chapter 4: The Flame of Olympus where Kratos is running after Hermes and he goes in a door and closes it and we need to climb vertical stairs from left side then jump to right side then in the end we need to jump in the left side stairs but Kratos never catch the stairs but in game it catches and climb at the top. This bug happened with me. even if I restarted from checkpoint or loading from last save (which is a round room where heremes come and he is sitting on roof after we leave the round room).
> 
> Hello bro, this problem happened in my pc just right now, did you solve it? And I found a method to let the game go on to trace Hermes, but the game run on a low FPS mode(maybe the reason is my GPU is GTX1066, hah)
> 
> just need to change the renderer to `OpenGL` (not the `Vulkan`), and start the game.
> 
> Then change the settings back while Kratos passed this place.
> 
> ![image](https://user-images.githubusercontent.com/24445771/195131920-094ebdf5-aba2-493b-8ab2-91a4996d5de2.png)
> 
> I hope it can help you really~

This worked for me as well, thank you. (GTX 660 Ti and i7 3770k)

**Comment by Caspy23** [comment]
I have an i7 12700h and an rtc 3050ti.gow3 is getting stuck on both iris xe and rtx.. what should I do?

**Comment by GTziolas** [comment]
> > I am Stuck on Chapter 4: The Flame of Olympus where Kratos is running after Hermes and he goes in a door and closes it and we need to climb vertical stairs from left side then jump to right side then in the end we need to jump in the left side stairs but Kratos never catch the stairs but in game it catches and climb at the top. This bug happened with me. even if I restarted from checkpoint or loading from last save (which is a round room where heremes come and he is sitting on roof after we leave the round room).
> 
> Hello bro, this problem happened in my pc just right now, did you solve it? And I found a method to let the game go on to trace Hermes, but the game run on a low FPS mode(maybe the reason is my GPU is GTX1066, hah)
> 
> just need to change the renderer to `OpenGL` (not the `Vulkan`), and start the game.
> 
> Then change the settings back while Kratos passed this place.
> 
> ![image](https://user-images.githubusercontent.com/24445771/195131920-094ebdf5-aba2-493b-8ab2-91a4996d5de2.png)
> 
> I hope it can help you really~

This is still happening to me today. RX 6750 XT, AMD 7600X. I cannot use OpenGL because everything I see is black and the game crashes a minute after it starts.
