### ISSUE TITLE
Regressions from #5785 (rsx: Texture cache fixes)

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#5807]
After https://github.com/RPCS3/rpcs3/pull/5785 merged Toy Home regressed to Intro. Ingame graphics and the menu graphics now has nothing rendering apart from text. Tried OpenGL and Vulkan, and also with Write Color Buffers, but it didn't fix the issue. (ogl and vk worked fine on the previous build before https://github.com/RPCS3/rpcs3/pull/5785 merged and did not need WCB).

RDC before/after (26MB): https://mega.nz/#!rM5kCS4I!DHhv8wfYp4OYmhhw3pE9dahkO_GJfE8lQ4ac5t_StPk

**Comment by Asinin3** [comment]
Uncharted 1 also crashes when using Vulkan after the spinning loading icon with the following error:
`F {RSX [0x0660f94]} RSX: class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vktexture.cpp:80)`
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3061829/RPCS3.log.gz)

**Comment by kd-11** [comment]
Blit engine woes are fixed by https://github.com/RPCS3/rpcs3/pull/5813

**Comment by Asinin3** [comment]
Confirmed Toy Home graphics are fixed, can't reliably test UC so not sure about that issue.
![image](https://user-images.githubusercontent.com/15137035/55884115-0561de00-5b97-11e9-9685-f73bbe4c60e3.png)

**Comment by kd-11** [comment]
Closing as fixed by #5813
