### ISSUE TITLE
Persona 5 freeze after a few minutes

### ISSUE THREAD

**Issue by GitKarones** [RPCS3/rpcs3#5811]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3061387/RPCS3.log.gz)

Commit f15eb88
MB - Asrock AB350 Pro4
CPU - Ryzen 5 1600 (overclock to 3.7Ghz)
RAM - Corsair Vengeance DDR4 2x4GB 2400MHz
GPU - Gigabyte Windforce GTX 1060 6GB
SSD - Kingston SA400 250GB

While playing Persona 5, a few minutes after starting the session(7-10 mins), the screen changes and freezes to an instance of the game from a few minutes ago. For example, after starting a new game and playing for a while, the game froze with the ATLUS logo, in another session it froze while showing a corridor I was some time ago, frozen like a screenshot. The image is always from the same session, the music does not stop but the game doesn't seems to be running(no dialogue or sound effects when triyng to move the character).
I kept the task manager open to see if I noticed anything, but there are no spikes when the game freezes, everything runs quite normally, RAM stays at around 3.9GB, half the CPU cores are pretty much maxed while others are at half usage.
I get some pretty strong temporary freezes when compiling shaders in a few areas, but I'm not sure if they are connected to the perma freeze.

**Comment by AniLeo** [comment]
Log shows it's a pirated game, removed log and closing issue
