### ISSUE TITLE
Uncharted 2 Chapter 2 Segfault

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#5815]
Thanks to the latest kd-11's texture cache improvement i spent last few days playing Uncharted 2, there's a Segfault issue that blocks playthrough in chapter 2, just after putting down the first museum guard, segfault captured on ASMJit, on SPU LLVM emulator just crashes
![6](https://user-images.githubusercontent.com/7060586/55899910-9c965800-5bce-11e9-9192-4ec8e36646ed.jpg)
I used a save file to play further, and the rest of the game is mostly playble, played through all the chapters, except 25th without a problem, in chapter 25 there's a bug; for some reason i can't explode the blue stuff with shooting as it supposed to be
![4](https://user-images.githubusercontent.com/7060586/55900082-11699200-5bcf-11e9-96ec-97cc34e233b0.jpg)
Despite graphical issues and random Traps if not these two issues the game will be playable

**Comment by AniLeo** [comment]
Needs information, at least a save file and a log file after it crashes

**Comment by Xcedf** [comment]
Here's the log
https://mega.nz/#!6VQDAYqK!Lku-ingeZHWzcK1VPSwiHli1opas30KULJmIfpgYbHM
and here's the save files for both EU and US versions of the game, saves has disc game ID's but they're also work for PSN versions, to see th crash just load the save with 5% or 6% game completed
https://mega.nz/#!rFID3SyC!nQwLUFDVWSkCch5gjSL6TGnnzuROkgHSYie9IY-aa64

**Comment by Xcedf** [comment]
Don't know when exactly it happened but second chapter seems to be playable now, segfault fixed
![1](https://user-images.githubusercontent.com/7060586/61978925-21c93f80-affb-11e9-93bd-697e29814ad4.jpg)

**Comment by Xcedf** [comment]
Closing this issue, found a way to pass this normally, without debug menu

**Comment by Xcedf** [comment]
I can reopen this if you still consider this an issue, but the main Segfault isue is fixed and here's the video demonstration of bypassing this bug
https://www.youtube.com/watch?v=lbqiwIWAdKQ
