### ISSUE TITLE
Linux Appimage : SSL missing for compatability database?

### ISSUE THREAD

**Issue by 7oxicshadow** [RPCS3/rpcs3#5817]
Version:
RPCS3 v0.0.6-7955-52a12185 Alpha | HEAD

Error:
Can not retrieve the online database! Please make sure your system supports SSL

Information:
I am trying to download the latest compatability database but it fails with the above error. I have looked in the source and it appears that QSslSocket::supportsSsl() is returning false.
I have checked that openssl is installed on my machine
```
Last metadata expiration check: 0:22:45 ago on Thu 11 Apr 2019 10:55:10 BST.
Package openssl-1:1.1.1b-3.fc29.x86_64 is already installed.
```
Does the appimage need to be compiled with SSL support?

**Comment by 13xforever** [comment]
rpcs3 is probably linked against openssl 1.0, and we can't redistribute compatible version with emulator itself due to license issues.

you get up-to-date compatibility database snapshot with every update anyway, so updating the compatibility database is a very minor issue

**Comment by 7oxicshadow** [comment]
Thanks for your response. If it is correct that a new version of the database is shipped with the release then this can probably be closed.

The reason I raised this is that I believe that the latest version of the GUI should now report when updates are available but i just get the following:

![image](https://user-images.githubusercontent.com/10350138/55951599-8e3c5080-5c4f-11e9-8547-d88db954b254.png)

I am confident that it should be reporting updates for Gran Turismo at least.

**Comment by AniLeo** [comment]
It's working for me on the AppImage, Ubuntu 18.04

**Comment by 7oxicshadow** [comment]
@AniLeo Thanks for reporting that it is working for you. The problem must be at my end.

I will try renaming my rpcs3 folder in /home/.config and recreate to see if that does anything.

**Comment by 7oxicshadow** [comment]
Sadly starting from scratch doesn't help either.
One thing it has shown though is that it doesn;t appear to release with the compatability database as a games now list "database missing" and trying to download obviously fails with the SSL problem.

![image](https://user-images.githubusercontent.com/10350138/55952431-89789c00-5c51-11e9-81e1-291d7f49f6a0.png)

Is it possible to download the database manually just to see if it makes any difference?

**Comment by 7oxicshadow** [comment]
Ok, so i downloaded the windows version and extracted the compat_database.dat file from that into ~/home/.config/rpcs3/rpcs3_data/GuiConfigs and now it works as expected:

![image](https://user-images.githubusercontent.com/10350138/55952673-0f94e280-5c52-11e9-8ec7-06a9fe92d61b.png)

This is a temporary workaround (for me at least) until I can find the correct SSL library.

**Comment by drysalter** [comment]
Working fine for me on Ubuntu 18.10, just for the record.

**Comment by 7oxicshadow** [comment]
I now have this working on Fedora 29 (64bit)
I had to download the 64bit version of libssl.so.1.0.2 and place it in the same directory as the appimage file. (I tried using the compat libraries but they didn't seem to work)
Launch from either terminal or script in the following way:
`
LD_LIBRARY_PATH="PATH/TO/LIBSSL/FILE/HERE" ./rpcs3.AppImage`

Note: A word of caution. Everything I have read so far suggests that libssl 1.0.x series was dropped because of a security vulnerability so if you wish to try this but are security concious I would recommend waiting until rpcs3 is built with libssl 1.1.x support.

**Comment by 13xforever** [comment]
It might have been dropped from fedora, but it is still supported on other distros, and on windows (which means security patches are back ported to 1.0 version).

**Comment by montvid** [comment]
Thanks for the info @7oxicshadow, For debian download this and extract x86_64-linux-gnu folder
http://security-cdn.debian.org/debian-security/pool/updates/main/o/openssl1.0/libssl1.0.2_1.0.2t-1~deb9u1_amd64.deb
` LD_LIBRARY_PATH="/home/user/folder/x86_64-linux-gnu" ./rpcs3.AppImage`

**Comment by montvid** [comment]
This should be reopened until rpcs3 is upgraded to use openssl 1.1.1
