### ISSUE TITLE
"Update Available" GUI notification reports incorrectly on GTA5

### ISSUE THREAD

**Issue by 7oxicshadow** [RPCS3/rpcs3#5821]
GTA5 reports as the following even though it is fully updated:

![image](https://user-images.githubusercontent.com/10350138/55970813-2d753e00-5c78-11e9-88a1-07ddb0cba898.png)

I decided to look into why and it appears that there is 2 folders in the dev_hdd0/game folder that both start with BLES01807:

![image](https://user-images.githubusercontent.com/10350138/55970941-70cfac80-5c78-11e9-9006-3e5e71a6c6bd.png)

If I delete the BLES01807_install folder the GUI reports that the game is at the latest version BUT when you run the game it recreates the BLES01807_install folder resulting in the wrong version being reported again.

Both folders contain a PARAM.SFO and only the BLES01807 folder gets patched.

I am guessing that an additional check should be done to verify which folder contains an EBOOT.BIN and use that one.

**Comment by Zangetsu38** [comment]
Oh i see it look inside wrong folder hmm and update have only "id" for path fooder

**Comment by Megamouse** [comment]
we need the info of both param.sfo in order to see why

**Comment by 7oxicshadow** [comment]
I assume there is no legal issue in posting them here?

**Comment by Megamouse** [comment]
Please try again

**Comment by 7oxicshadow** [comment]
Confirmed fixed. Closing.
