### ISSUE TITLE
[Regression] NFL Blitz has an blue square overlaid on image (caused by PR 5675 - RSX Texturing Improvements)

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5824]
There's a blueish square that's now present on the screen (100% resolution). 

Started here it looks like:
https://github.com/RPCS3/rpcs3/pull/5675

![2019-04-11 13_15_23-RPCS3 - Compatibility List](https://user-images.githubusercontent.com/20983844/55991148-67d1e180-5c5e-11e9-9696-697402ad6864.png)

![2019-04-11 13_15_13-RPCS3 - Compatibility List](https://user-images.githubusercontent.com/20983844/55991149-67d1e180-5c5e-11e9-89c9-4aa6f2465dec.png)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3070502/RPCS3.zip)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/5895

**Comment by legend800** [comment]
Yep, fixed in that PR! Nice work as always and appreciate the quick turnaround on the regression. I can close once merged.
