### ISSUE TITLE
Regression on Madden NFL 11 [BLUS30546] caused by PR #5784

### ISSUE THREAD

**Issue by connorwalks** [RPCS3/rpcs3#5827]
Intel i9-9900K (stock)
Nvidia RTX 2080 (419.67)
16 GB 3000MHz (C15) DDR4 

Although the game has no official compatibility in the database, the game is completely playable on RPCS3-v0.0.6-7947-12dc3c18. Only major graphical issue is how dust is rendered in the intro before each game. Aside from that no major graphical issues that render the game unplayable in any way. I average 65 FPS on my hardware, so I'm sure some it is playable on lower end hardware as well. 

~~As of when playing on RPCS3-v0.0.6-7955-52a12185, the game crashes right before kickoff every time with error "F {PPU[0x1000002] Thread (TaskManager:WorkerThread) [0x013cde20]} MEM: Access violation reading location 0x8". This issue is also present on current build RPCS3-v0.0.6-7969-c34821de. I have attached appropriately titled logs and screenshots showing 7947 getting beyond the kickoff with build 7955 crashing right before kickoff.~~ Turns out the issue is caused by RPCS3-v0.0.6-7952-40142420 (PR #5784). All builds after this also have the crashing issue on this game. Here is a log from that build: 
[RPCS3-7952-crash.zip](https://github.com/RPCS3/rpcs3/files/3071562/RPCS3-7952-crash.zip)

Here is the screenshot showing the game progressing beyond kickoff and its log:

![RPCS3-7947-playable](https://user-images.githubusercontent.com/48158481/56011852-a1830680-5cb7-11e9-80a6-234b248d0ee3.jpg)
[RPCS3-7947-playable.zip](https://github.com/RPCS3/rpcs3/files/3071507/RPCS3-7947-playable.zip)

Here is the game crashing on a later build right at kickoff and its log:
![RPCS3-7955-crash](https://user-images.githubusercontent.com/48158481/56011881-c37c8900-5cb7-11e9-8ff9-75a4bc738c49.jpg)
[RPCS3-7955-crash.zip](https://github.com/RPCS3/rpcs3/files/3071508/RPCS3-7955-crash.zip)

Let me know if you need any more information!

**EDIT:**
I would also like to mention that starting with this new version (7955) after running every game there is a new folder in my RPCS3 directory with odd names such as "＄mMiyRFZjGWs9cHNjh35GV9" with sub folders inside. Does not happen when switching back to previous builds and it is present on builds after 7955 as well. Not sure if this is intentional or not

**Comment by Asinin3** [comment]
There is a number of builds between those. You need to find which build exactly broke it. https://rpcs3.net/compatibility?b Then tag the PR (Pull Request) in your comment/issue description (like this #1234) - replace 1234 with the PR number.

**Comment by connorwalks** [comment]
It's caused by v0.0.6-7952-40142420 (PR #5784)

Updating issue description now

**Comment by legend800** [comment]
Same issue on NFL Blitz (commented in the PR). Another EA sports game. Neko's trying to fix it.

**Comment by connorwalks** [comment]
Seems to be fixed with latest release?

**Comment by AniLeo** [comment]
Closed as fixed, followup to 5784 was already merged
