### ISSUE TITLE
Ni No Kuni - Fatal Error with v0.0.6-7968 and -7969

### ISSUE THREAD

**Issue by Utopolyst** [RPCS3/rpcs3#5829]
My Setup: Win10, i7-6700k (Skylake), 32gb, Geforce 1080.

Just wanted to drop a line that the new build causes overall stuttering when creating ppu cache and the game won't start anymore. (haven't checked other games). Cheers. 

These builds don't work: 
v0.0.6-7969
v0.0.6-7968

The last build that works for me is:
v0.0.6-7967

**Comment by Utopolyst** [comment]
Nope, -7967 also causes issues when compiling. Back to rpcs3-v0.0.6-7956... (which I had been using fine for hrs...)

**Comment by elad335** [comment]
upload log after you find the build.

**Comment by Utopolyst** [comment]
From the faulty build


[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3072278/RPCS3.log)
[TTY.log](https://github.com/RPCS3/rpcs3/files/3072279/TTY.log)

**Comment by elad335** [comment]
then its fixed by #5816 and #5823.

**Comment by elad335** [comment]
fixed on master, needs closing.
