### ISSUE TITLE
rsx: Broken depth on AMD GPUs (GoW 3 Demo)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#5830]
Opening issue for tracking purposes, there's a known issue with depth that affects shadows on AMD GPUs. On NVIDIA they work fine.

Demonstration of issue (R9 280X):
https://www.youtube.com/watch?v=uakYMsKwd1U

Working fine on NVIDIA (GTX 1080):
![Screenshot1](https://cdn.discordapp.com/attachments/442667232489897997/566055599377481758/unknown.png)
![Screenshot2](https://cdn.discordapp.com/attachments/442667232489897997/566055923903365150/unknown.png)

I'm not aware whether this affects full game, as I didn't get it yet.

**Comment by kd-11** [comment]
This appears to be some kind of spec violation or oversight on khronos' part. It is not well defined what should happen with border texels when a compare operation is also active. The spec has this special condition governing replacement of border texels:
`If the read is the result of an image sample instruction or image gather instruction`
When comparison is enabled this does not happen for the DEPTH32_SFLOAT_S8_UINT format on both AMD and NVIDIA hardware. Border comparison always fails in this case which is not the correct solution as it should replace the invalid fetch with border color which is a float4(1) in this case and then do comparison after the fact. This very much looks to be a driver bug, but for the moment I'm designing a simple workaround just in case IHVs are not interested in fixing it. Can anyone confirm if intel drivers are also affected by this issue?

**Comment by kd-11** [comment]
After looking deeper into the issue, it appears it may be more complex than initially thought. In the GoW case, the texel replacement does not seem to be the culprit as the SamplerAddressingMode is quite different (ClampToEdge, unlike Yakuza series which uses ClampToBorder).

**Comment by kd-11** [comment]
[This build](https://ci.appveyor.com/project/kd-11/rpcs3/builds/23867358) fixes this issue. This is not really a bug, its just how nvidia is doing the comparison. DEPTH24 is a fixed point format so when comparing D to Dref, NVIDIA hw is converting Dref into fixed point as well so any values larger than 1 are getting truncated. When using DEPTH32_FLOAT, the storage format is in FP32 and comparing the incoming Dref fails if it has a value larger than 1 (overflow).
For now, all drivers with D24 missing are emulated in software (we still get PCF using textureGather so no big loss there). The same is done for NVIDIA hw if the 'Use high precision Z' option is enabled.

**Comment by AniLeo** [comment]
![image](https://user-images.githubusercontent.com/10283761/56154866-86fba680-5fb1-11e9-96b2-e580688bb66d.png)

Confirmed fixed

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/5860
