### ISSUE TITLE
Vertical synchronization can be broken

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#5834]
I have tested RPCS3 v0.0.6-7969-c34821de on a game "The Unfinished Swan"[NPEA00395] and V-Sync can be broken using OpenGL (overlay shows more fps than 60) if i press buttons that throws blots multiple times and fast. And I can see screen tearing using V-Sync on Vulkan and OpenGL. Also audio processing in that moment does not work good (sound is stuttering though audio buffering is on and even if v-sync is off and fps is 200+ nothing changes)
My specs:
AMD FX-6300
Radeon R7 265
Windows 8.1 Build 9600
Radeon Software Version 17.7.1

I hope someday developers will take a look on improving audio processing.

**Comment by AniLeo** [comment]
There's no problem with audio processing, it's already really good, your CPU is just too low end and loses performance on those peak areas.

How high do frames go with VSync on?
Your drivers are also too old, update and retest.

**Comment by kd-11** [comment]
Vsync tearing bugs are for the driver devs if you see tearing, except OpenGL where we use adaptive Vsync and tearing is allowed. Timing improvements should fix this adaptive sync erratic behaviour; it's being worked on. This will not fix tearing with vsync enabled on vulkan though unless a driver update fixes it.
