### ISSUE TITLE
Xinput gamepad don't detected.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#5835]
Logitech F310 on latest master. Can be detected as mmjoystick.
No log, because it's empty anyway.
![Снимок экрана (108)](https://user-images.githubusercontent.com/6324523/56073139-8d6f0000-5db0-11e9-90cd-a973b2ab0d68.png)
![Снимок экрана (109)](https://user-images.githubusercontent.com/6324523/56073140-8d6f0000-5db0-11e9-9080-69032d26e079.png)

**Comment by vsub** [comment]
Stupid question but did you tried switching from D to X by using the switch at the back of the gamepad

**Comment by isshininu** [comment]
lmao, you are right
