### ISSUE TITLE
Sort console language

### ISSUE THREAD

**Issue by Jhonny-2005** [RPCS3/rpcs3#5838]
Hi.
In setting of rpcs3 on System tab - Languages in "Console Language" isn`t sorting. 
Is it possible to fix this?

**Comment by AniLeo** [comment]
Isn't sorting how specifically? As far as I'm aware, it's sorted by ID

**Comment by Jhonny-2005** [comment]
I think alphabetical sorting would be more logical.

**Comment by Jhonny-2005** [comment]
Now:
![image](https://user-images.githubusercontent.com/46434878/56081034-4ebd6200-5e11-11e9-8d6d-51ea2ac6a62e.png)

**Comment by kd-11** [comment]
They're alphabetically sorted on real PS3 as well. Looks like a good project for a casual/first-time contributor to tackle.
