### ISSUE TITLE
Regression Juiced 2 : Hot Import Nights [BLES00143]

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5839]
has Regression 

![54777](https://user-images.githubusercontent.com/45731484/56081953-e5653100-5dc7-11e9-9040-7e7ea10a4aa2.png)

the game was working https://github.com/RPCS3/rpcs3/pull/5749

in this pr by @elad335 RPCS3 v0.0.6-4120ca14 Alpha | new-wip

log file 

[RPCS3 Juiced 2  Hot Import Nights.zip](https://github.com/RPCS3/rpcs3/files/3076406/RPCS3.Juiced.2.Hot.Import.Nights.zip)

**Comment by elad335** [comment]
In what pull request it regressed.. ?

**Comment by elad335** [comment]
Can't reproduce on master.

![image](https://user-images.githubusercontent.com/18193363/56097671-41cb6c00-5f00-11e9-9da5-060c91e1d179.png)

**Comment by uaqlover** [comment]
RPCS3 v0.0.6-7981-f9957711 Alpha | HEAD


![FPS_ 30 02 _ OpenGL _ 0 0 6-7981 _ Juiced 2 _ Hot Import Nights  BLES00143  14_04_2019 2_17_55 PM](https://user-images.githubusercontent.com/45731484/56099313-2b052500-5ec0-11e9-82cf-e9957e0d7daf.png)
