### ISSUE TITLE
Feature Request:Ini only option to limit writing the log to the logging mode selected

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#5841]
Or maybe a fix
In Tales of Xillia 2,rpcs3 is spamming non stop(~100 times per seconds)
cellScreenshot TODO: cellScreenShotEnable() (I know what that mean and why it is shown)

Unless I block in some way rpcs3 to write to the log(including the gz archive),the file RPCS3.log becomes 30mb in less than 10 minutes of gameplay and the log contains that same line more than 18k times

Setting Fatal as logging method applies just for the log window,rpcs3 is still writing the log file and the archive the same way regardless of what logging method I select
If I don't block writhing to the file,the log fle is often more than 1gb after I close rpcs3(when it reaches 1gb rpcs3 becomes more and more sluggish)

I know it is good to have a log to be able to fix problems but I usually don't consider posting an issue of a problem if I encounter it only once.
When I want to find the problem,then I switch to a more useful logging method.

**Comment by elad335** [comment]
Limiting logging to whats only visible on UI would be pretty bad for debugging and issue helping.
You can already disable log channels manually in config.yml.
set in the last line of config `{ "cellScreenshot" : "Fatal"}`
This disables writing non-fatal messages to the log file and UI.

**Comment by MSuih** [comment]
You can disable logging channels by modifying the config.yml manually (either the global config or by creating a game-specific one and modifying that). This comment https://github.com/RPCS3/rpcs3/issues/3215#issuecomment-322067042 has the most complete list of various log channels to disable I think.

Your request has been implemented in #5333 but the owners of this repository are hesitant to merge it as it can be a major headache when helping people with the issues they're having.

**Comment by vsub** [comment]
This is just from watching the intro and waiting for the title screen to appear(~3min)
```
U {PPU[0x1000000] Thread (main_thread) [0x011f40b8]} cellScreenshot TODO: cellScreenShotDisable() x728
U {PPU[0x1000000] Thread (main_thread) [0x011f40b0]} cellScreenshot TODO: cellScreenShotEnable() x2
U {PPU[0x1000000] Thread (main_thread) [0x011f40b8]} cellScreenshot TODO: cellScreenShotDisable() x93
U {PPU[0x1000000] Thread (main_thread) [0x011f40b0]} cellScreenshot TODO: cellScreenShotEnable() x5812
E {PPU[0x1000000] Thread (main_thread) [0x00994d68]} 'sys_ppu_thread_set_priority' failed with 0x80010005 : CELL_ESRCH [1]
U {PPU[0x1000000] Thread (main_thread) [0x011f40b0]} cellScreenshot TODO: cellScreenShotEnable() x4
S {RSX Decompiler Thread} RSX: New program compiled successfully
U {PPU[0x1000000] Thread (main_thread) [0x011f40b0]} cellScreenshot TODO: cellScreenShotEnable() x719
S {RSX Decompiler Thread} RSX: New program compiled successfully
U {PPU[0x1000000] Thread (main_thread) [0x011f40b0]} cellScreenshot TODO: cellScreenShotEnable() x218
```

If I copy all from this post,https://github.com/RPCS3/rpcs3/issues/3215#issuecomment-322067042 will rpcs3 still write useful information while posting a log file for a problem,or I have to restore it to Log: {}

Using { "cellScreenshot" : "Fatal"} don't write the cellScreenShotEnable to the log anymore,but the file size is still growing.

> Limiting logging to whats only visible on UI would be pretty bad for debugging and issue helping.

Yes that's why I suggested ini only option...or a command line.
AniLeo mention there that the file size was limited recently but isn't 1gb txt file WAY too big

**Comment by 13xforever** [comment]
For support and error reporting you'll be asked to  disable any filters.

**Comment by vsub** [comment]
Ok then
I think this problem is related to #3215 and a solution would be #5333 if it is merged(some day hope)so closing this one
