### ISSUE TITLE
Backbreaker Vengenance [NPEB00592] Broken crowd gfx

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5842]
The crowd never rendered until about a week ago (which was fine). With recent commit though, they now render, but as you can see are quite broken. Their appearance and flickering is fairly distracting. 

![2019-04-14 09_05_46-FPS_ 30 52 _ Vulkan _ 0 0 6-7fee51f3-Nekotekina_master _ BACKBREAKER VENGEANCE ](https://user-images.githubusercontent.com/20983844/56096706-8f17f100-5ea0-11e9-9f57-00c4f5ea1ad9.png)

![2019-04-14 09_05_55-FPS_ 30 00 _ Vulkan _ 0 0 6-7fee51f3-Nekotekina_master _ BACKBREAKER VENGEANCE ](https://user-images.githubusercontent.com/20983844/56096707-8f17f100-5ea0-11e9-96e9-0dd6a0eb1fa7.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3077660/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by nitrohigito** [comment]
Thanks for referencing it in the regression tracker ticket, but could you copy over the whole report there and close this one instead? Would be easier for kd,  and I was just noting all the issue numbers for completeness' sake.

**Comment by legend800** [comment]
The only thing is, does kd-11 treat this as a true regression? Before it was nothing, now it's partially working (although wonky). Maybe it's just necessary iterative progress? That's why I felt maybe it should just be separate.

**Comment by nitrohigito** [comment]
Hmm, fair point. Keep the issue open then, but copy over the contents maybe? It might come in handy for him if things are in one place, even if technically it's not really a regression.

**Comment by nitrohigito** [comment]
How's it looking with #5895 in master?

**Comment by legend800** [comment]
No change yet - crowd is a still bunch of stick figures. :)

![2019-05-01 08_19_49-Window](https://user-images.githubusercontent.com/20983844/57024668-01e7d280-6bea-11e9-826b-7a321b6cc4a0.png)

**Comment by kd-11** [comment]
I believe the crowd stopped rendering. This issue can be closed for now.

**Comment by legend800** [comment]
Correct, back to empty stands and ghost cheers. ;) Better than creepy slender men for sure.

![2019-07-04 09_51_34-Window](https://user-images.githubusercontent.com/20983844/60680735-52291e00-9e41-11e9-8121-e7ad9c1db05d.png)
