### ISSUE TITLE
cellVdec: Unknown format (12), The Smurfs 2 [BLES01797]

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5845]
`F {PPU[0x1000024] Thread (_libsail-vdec_copy) [0x00f053a8]} class std::runtime_error thrown: Unknown format (12)
(in file c:\projects\rpcs3\rpcs3\emu\cell\modules\cellvdec.cpp:644)`

log file
[RPCS3 the.log.gz](https://github.com/RPCS3/rpcs3/files/3077862/RPCS3.the.log.gz)

**Comment by Zangetsu38** [comment]
12 is :
>AV_PIX_FMT_YUVJ420P

**Comment by Zangetsu38** [comment]
after test code one think
i get video perfectly play and game Ingame
![image](https://user-images.githubusercontent.com/5261759/56138155-928da400-5f96-11e9-893e-a8c595435c7c.png)

**Comment by uaqlover** [comment]
@Zangetsu38 any new update for this issue

**Comment by elad335** [comment]
Reopen if issue persist, closed by accident.
