### ISSUE TITLE
Regression Mobile Suit Gundam Target in Sight [BLES00034]

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5847]
![FPS_ 46 60 _ Vulkan _ 0 0 6-7981 _ Mobile Suit Gundam Target in Sight  BLES00034  15_04_2019 9_55_28 PM](https://user-images.githubusercontent.com/45731484/56182987-62132d80-5fc9-11e9-9352-f40c3f8fce33.png)

log file 

[RPCS3 m.log.gz](https://github.com/RPCS3/rpcs3/files/3083083/RPCS3.m.log.gz)

**Comment by elad335** [comment]
if you state its regression you must find the pull request where it regressed.

**Comment by uaqlover** [comment]
@elad335 sure : )

it was ok before  https://github.com/RPCS3/rpcs3/pull/5785

0.0.6-7947

![FPS_ 36 09 _ Vulkan _ 0 0 6-7947 _ Mobile Suit Gundam Target in Sight  BLES00034  15_04_2019 10_09_02 PM](https://user-images.githubusercontent.com/45731484/56183389-41e46e00-5fcb-11e9-9e18-43fdccd30bc5.png)


0.0.6-7935

![FPS_ 38 57 _ Vulkan _ 0 0 6-7935 _ Mobile Suit Gundam Target in Sight  BLES00034  15_04_2019 10_07_38 PM](https://user-images.githubusercontent.com/45731484/56183384-3e50e700-5fcb-11e9-9ec4-e63dff530d0c.png)

**Comment by nitrohigito** [comment]
@uaqlover We seem to share the same issue, so kd asked to move this and my issue into a single regression tracker ticket. Could you close this issue and move the report and the pics to the regression ticket I just opened? (#5869)

**Comment by uaqlover** [comment]
sure : )

**Comment by nitrohigito** [comment]
@uaqlover Thanks. Are you not going to copy over your report though?
