### ISSUE TITLE
Regression #5785 Ni no Kuni: Wrath of the White Witch [BLUS30947]

### ISSUE THREAD

**Issue by k10kan** [RPCS3/rpcs3#5848]
Last good build #5797 (0.0.6-7935)
First bad build #5785 (0.0.6-7947)

Vulkan: VK_ERROR_DEVICE_LOST
OpenGL: gfx corruption

After PR #5785, when accessing book withing the game (Read the Wizards's Companion):

  * Vulkan - After opening the book game freezes with the error RSX: class std::runtime_error
    thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device
    lost (Driver crashed with unspecified error or stopped responding and
    recovered) (VK_ERROR_DEVICE_LOST). RPCS3 is not frozen and clean exit is possible.

  * OpenGL - Gfx gets distorted (sample image included). After closing the book,
    gfx returns to normal.

Same issue with all PPU/SPU Decoders. Logs done using PPU LLVM/SPU LLMV.

Vulkan:
![rpcs3-v0 0 6-7947-12dc3c18_win64-Vulkan](https://user-images.githubusercontent.com/37659629/56197005-38ddb600-6038-11e9-871c-f4346918f844.png)
[rpcs3-v0.0.6-7947-12dc3c18_win64-Vulkan.log.gz](https://github.com/RPCS3/rpcs3/files/3084004/rpcs3-v0.0.6-7947-12dc3c18_win64-Vulkan.log.gz)

OpenGL:
![rpcs3-v0 0 6-7947-12dc3c18_win64-OpenGL](https://user-images.githubusercontent.com/37659629/56197035-45620e80-6038-11e9-9afd-42a97ccf0dfa.png)
[rpcs3-v0.0.6-7947-12dc3c18_win64-OpenGL.log.gz](https://github.com/RPCS3/rpcs3/files/3084005/rpcs3-v0.0.6-7947-12dc3c18_win64-OpenGL.log.gz)

Also, same issue presists in latest PR #5840 (0.0.6-7981).

**Comment by psennermann** [comment]
I confirm that accessing book in NiNoKuni is actually broken (Win10, i7 7700, gtx1060)

**Comment by Asinin3** [comment]
You should check to see if it still appears in latest kd-11 PR. https://github.com/RPCS3/rpcs3/pull/5860

**Comment by k10kan** [comment]
I have tested this issue yesterday with rpcs3-v0.0.6-0b0fe8bf-kd-11/master from PR #5860, but it was not resolved, so I did not comment here.

Now that you suggested to test that PR, I noticed that F line now points to line vkhelpers.h:964, not to vkhelpers.h:832 from rpcs3-v0.0.6-7947, if that is relevant at all.

![rpcs3-v0 0 6-0b0fe8bf_win64-Vulkan](https://user-images.githubusercontent.com/37659629/56434681-d43f8700-62d5-11e9-94fe-88e1f2a1e4bf.png)

Also, OpenGL is the same as before.

Maybe some future additions to that PR will resolve it...

**Comment by MSuih** [comment]
The PR added more code to vkhelpers.h which pushed the offending line downwards into the file. Nothing about the error itself changed.

**Comment by nitrohigito** [comment]
@k10kan Hi, kd [asked](https://github.com/RPCS3/rpcs3/issues/5864#issuecomment-485126770) to group #5785-related issues together a bit, so could you please close this ticket and copy the original report over to #5869 instead? You can do this easily by clicking on `Edit`, copying everything out, and just pasting it in as a comment to the other ticket.

**Comment by k10kan** [comment]
Sure.

@nitrohigito Please, update problem description in #5869 from "a (certain?) book" to "the book from main menu (Wizards's Companion)". That is the only book in Ni no Kuni as far as I know.

I have added a picture as well.

**Comment by nitrohigito** [comment]
Ok, thanks for clarifying that bit, I wasn't sure.
