### ISSUE TITLE
Heavy rain graphical glitch

### ISSUE THREAD

**Issue by Zaza06** [RPCS3/rpcs3#5849]
RPCS3 v0.0.6-7972

When playing heavy rain, after changing cloth animation at the bedroom, the face section skin is corrupted.

Spec:
i5-7600
32GB RAM
GTX-1070Ti (425.31)
![image](https://user-images.githubusercontent.com/46767305/56211920-86cfd980-608b-11e9-8ec3-b0407c8dabc1.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3084971/RPCS3.log.gz)

**Comment by Emulator-Team-2** [comment]
@Zaza06 
Enable `Write Color Buffers` in GPU tab setting.
Close this issue.
