### ISSUE TITLE
Additional Regressions with PR #5427 (FBO_Fixes) in NCAA Football 13 & 14

### ISSUE THREAD

**Issue by connorwalks** [RPCS3/rpcs3#5854]
Saw some Youtube videos of people getting ingame with NCAA 13 and NCAA 14 and decided to see where compatibility broke for these two games using Vulkan. Both games still get ingame just fine with OpenGL on current builds, but performance is pretty bad.

It seems the culprit was 0.0.5-7678 (PR #5427). When using this build, I get stuck with this error message in NCAA Football 13 [BLUS30948] when I try to enter any sub-menu (trying to access settings, start a game, or anything else) and the game freezes at this screen: `F {RSX [0x019fbf4]} RSX: class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkgsrender.cpp:1943)` 

Here is a screenshot of the crash: ![PR5427_crash_NCAA13](https://user-images.githubusercontent.com/48158481/56232201-338b6600-604e-11e9-9afa-0649ea72736e.jpg)

Log of crash: [PR5427_crash_NCAA13.zip](https://github.com/RPCS3/rpcs3/files/3086277/PR5427_crash_NCAA13.zip)

Same deal with NCAA Football 14 [BLUS31159]. Error code: `F {RSX [0x0068e1c]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkgsrender.cpp:1943)`

Screenshot of crash: 
![PR5427_crash_NCAA14](https://user-images.githubusercontent.com/48158481/56232561-0ee3be00-604f-11e9-8f60-60c2223a3f95.jpg)

Log of crash: [PR5427_crash_NCAA14.zip](https://github.com/RPCS3/rpcs3/files/3086262/PR5427_crash_NCAA14.zip)

Meanwhile, the previous build 0.0.5-7658 (and several before that) got ingame just fine with both games. Heavy graphical glitches but both games do get ingame.

NCAA 13 screenshot: ![build7658_ingame_NCAA13](https://user-images.githubusercontent.com/48158481/56234524-713ebd80-6053-11e9-8586-8123740fb2a5.jpg)

NCAA 13 log: [build7658_ingame_NCAA13.zip](https://github.com/RPCS3/rpcs3/files/3086346/build7658_ingame_NCAA13.zip)

NCAA 14 screenshot: ![build7658_ingame_NCAA14](https://user-images.githubusercontent.com/48158481/56234542-7ef44300-6053-11e9-85a1-200a943b87e9.jpg)

NCAA 14 log: [build7658_ingame_NCAA14.zip](https://github.com/RPCS3/rpcs3/files/3086349/build7658_ingame_NCAA14.zip)

**Comment by tristannibbe** [comment]
Just adding that I am also experiencing the same issue as of v0.0.6-8034.
[Logs.zip](https://github.com/RPCS3/rpcs3/files/3126172/Logs.zip)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/5895

**Comment by connorwalks** [comment]
Unfortunately does **NOT** fix the issue in either game. 

NCAA 13: 
![PR5895_NCAA13](https://user-images.githubusercontent.com/48158481/56900271-6a587780-6a63-11e9-853e-fe0bc2e81c73.jpg)
log: [PR5895_NCAA13.log.gz](https://github.com/RPCS3/rpcs3/files/3127607/PR5895_NCAA13.log.gz)

NCAA 14:
![PR5895_NCAA14](https://user-images.githubusercontent.com/48158481/56900297-7a705700-6a63-11e9-8efe-970501cde4a7.jpg)
log: [PR5895_NCAA14.log.gz](https://github.com/RPCS3/rpcs3/files/3127608/PR5895_NCAA14.log.gz)

As soon as it is fixed though I'm sure both games will be playable. Both games are just missing performance in OpenGL (using 9900k) and have no visual glitches. Other similar games (such as NCAA Football 10) are playable on Vulkan

**Comment by kd-11** [comment]
Retest again, should be fixed now.

**Comment by connorwalks** [comment]
It's fixed!!!

![NCAA14](https://user-images.githubusercontent.com/48158481/56911429-ddb9b380-6a7a-11e9-87d2-0f83fa26b74f.jpg)

You're a wizard. The game still need better performance until it's considered playable, but being able to play this game at 4K on my hardware is amazing. Thank you so much for fixing this!
