### ISSUE TITLE
Regression with Naughty Bear: Panic in Paradise 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5856]
after research hours know what is build break the game 

https://github.com/RPCS3/rpcs3/pull/5008

0.0.5-7222

![778888888](https://user-images.githubusercontent.com/45731484/56268525-65301b80-60a6-11e9-95b5-1e42945f149e.png)

0.0.5-7221

![488855555](https://user-images.githubusercontent.com/45731484/56268537-695c3900-60a6-11e9-903e-5ec00a92bba1.png)

[RPCS3 0.0.5-7221.log.gz](https://github.com/RPCS3/rpcs3/files/3088324/RPCS3.0.0.5-7221.log.gz)

[RPCS3 0.0.5-7222.log.gz](https://github.com/RPCS3/rpcs3/files/3088325/RPCS3.0.0.5-7222.log.gz)

RPCS3 v0.0.6-7989-78659822 Alpha
[RPCS3 Naughty Bear1.log.gz](https://github.com/RPCS3/rpcs3/files/3088264/RPCS3.Naughty.Bear1.log.gz)

**Comment by uaqlover** [comment]
also Naughty Bear Gold Edition [NPUB31067] is same

**Comment by elad335** [comment]
Ah, Gold edition is fixed by #5346.
Likely the same with Panic in Paradise.
Its a race condition which is probably why you pinpointed that pr which seems unrelated.

**Comment by uaqlover** [comment]
@elad335 really it fix Naughty Bear Gold Edition 

![FPS_ 1281 40 _ Vulkan _ 0 0 6-41c67fb9-spu3 _ Naughty Bear Gold Edition  NPUB31067  18_04_2019 3_37_00 AM](https://user-images.githubusercontent.com/45731484/56356245-1f01b780-618d-11e9-90fe-9838ac744db9.png)

![FPS_ 1208 86 _ Vulkan _ 0 0 6-5f4522b4-spu3 _ Naughty Bear Gold Edition  NPUB31067  18_04_2019 3_43_10 AM](https://user-images.githubusercontent.com/45731484/56356251-245f0200-618d-11e9-8d06-72b1efc0c69e.png)

but it's a improvement little bit in Panic in Paradise but black screen 

![FPS_ 1468 27 _ Vulkan _ 0 0 6-5f4522b4-spu3 _ Naughty Bear_ Panic in Paradise  NPUB30828  18_04_2019 4_00_32 AM](https://user-images.githubusercontent.com/45731484/56356751-93892600-618e-11e9-9172-ec199c416495.png)

after that black screen
 
![FPS_ 3315 19 _ Vulkan _ 0 0 6-5f4522b4-spu3 _ Naughty Bear_ Panic in Paradise  NPUB30828  18_04_2019 3_46_20 AM](https://user-images.githubusercontent.com/45731484/56356259-2b861000-618d-11e9-93e0-a70f723eac35.png)

**Comment by elad335** [comment]
Both works
![image](https://user-images.githubusercontent.com/18193363/56357570-c78f3600-61e4-11e9-8159-ad48f01abd31.png)

**Comment by uaqlover** [comment]
@elad335 i set it 60fps and goes ingame any idea when will be merge your pr to master because it's is old pr thanks again 

![FPS_ 59 98 _ Vulkan _ 0 0 6-5f4522b4-spu3 _ Naughty Bear_ Panic in Paradise (trial)  NPUB30828  18_04_2019 4_34_03 AM](https://user-images.githubusercontent.com/45731484/56358352-38a5fd80-6193-11e9-84fa-a590f1eb5c76.png)

**Comment by Realmantik** [comment]
I tested recent builds and Naughty Bear Gold Edition [NPUB31067] works good with OpenGL, but craches with Memory violations errors.

**Comment by uaqlover** [comment]
@elad335 any new updates for this issue

**Comment by AniLeo** [comment]
Is it still an issue?

**Comment by elad335** [comment]
should be.

**Comment by digitaldude555** [comment]
![Screenshot (1125)](https://user-images.githubusercontent.com/26138653/74091482-b6d7e580-4ac0-11ea-8b0a-8c09cf984e3d.png)
Goes ingame in master still an issue or can be closed?

**Comment by elad335** [comment]
NO

**Comment by elad335** [comment]
Try SPU execution delay with mask = 0x1
