### ISSUE TITLE
(Regression?) Devil May Cry HD Collection launcher hangs when booting one of the three games.

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#5857]
Devil May Cry HD Collection is suffering from an issue where it hangs when using the launcher to boot any of the three included games. I spent about an hour and a half trying to deduce what exactly broke it and while I was able to reproduce it working, and then not working 10 times in a row on two different builds. It seems i was just very unlucky. Right now I have no clue where the game broke, after trying around 50 builds I didn't come to any kind of concrete conclusion. But I can say that using SPU Interpreter does seem to increase the chances of it booting properly.

Boothing the .self files directly works fine however.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3089531/RPCS3.log.gz)

**Comment by elad335** [comment]
have you tried lle libvdec?

**Comment by Asinin3** [comment]
RPCS3 does this whenever i use libvdec, but i can hear the audio in the background.
![7498_2019-04-17_4821](https://user-images.githubusercontent.com/15137035/56287784-c985c600-610c-11e9-86fc-efd69dcc5d91.jpg)
