### ISSUE TITLE
issue with EA SPORTS Active 2

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5858]
`·W 0:01:32.420315 {PPU[0x100000f] Thread (DLC) [0x0131133c]} sys_fs: sys_fs_readdir(fd=11, dir=*0xd00e0bd0, nread=*0xd00e0ac8)`

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3091656/RPCS3.log.gz)

the log file get 2gb in 4minutes

**Comment by elad335** [comment]
Thats an invalid/non-issue, please close.

**Comment by elad335** [comment]
you can always disable sys_fs logging so you won't get log spam.

**Comment by davidnecas** [comment]
Guys I Have a problem with NHL15, i want to play, but the pop-up window in the menu still shows that "an online connection is required to play...", but i am connected to internet. Thanks for response
