### ISSUE TITLE
Assertion failed: !cached.is_locked() in BLJS10184

### ISSUE THREAD

**Issue by micaelis72** [RPCS3/rpcs3#5859]
RPCS3 on Fedora 30 0.0.6-7989

i7-7700HQ
64Gb RAM
nVidia GTX1060 6GB

Hangs when try to play the second cutscene, Both Vulkan and OGL.

Follow logs

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3091989/RPCS3.log.gz)

**Comment by frankyfife** [comment]
Well, the latest build 0.0.6-82e129d0 breaks every game, while building spu cache, with many assertion failed error.

**Comment by AniLeo** [comment]
There's no 82e129d0 in master.

**Comment by Emulator-Team-2** [comment]
@micaelis72 
Can you retest with the latest master build?

**Comment by kd-11** [comment]
Closing as fixed.
