### ISSUE TITLE
God of War Collection [BCES00791] Game Selection Menu Regression

### ISSUE THREAD

**Issue by nitrohigito** [RPCS3/rpcs3#5864]
The game selection menu now has about ~1/3rd of its output missing, similarly to #5847. This issue is also caused by #5785.

**Expected** (before #5785):

![image](https://user-images.githubusercontent.com/10439488/56432899-59736d80-62cf-11e9-8d77-891409c1ae17.png)

**Current** (after #5785):

![image](https://user-images.githubusercontent.com/10439488/56433029-d999d300-62cf-11e9-9d32-f438e2c49770.png)

Logs from before #5785: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3098668/RPCS3.log.gz)

Logs from after #5785:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3098673/RPCS3.log.gz)

Couldn't take RRCs due to the fact that they were broken at the time, but I could take one with current master (v0.0.6-7990-777a99d0). Hopefully it'll suffice.
[BCES00791_20190419182307_capture.zip](https://github.com/RPCS3/rpcs3/files/3098679/BCES00791_20190419182307_capture.zip)

System information:
 - CPU: i7 7700HQ
 - RAM: 16 GB
 - GPU: GTX 1060M (6GB ver, driver version: 425.31 [latest])
 - OS: Windows 10 Home (version: 1809, build: 17763.437 [latest])

**Comment by kd-11** [comment]
Isn't this a duplicate then?

**Comment by nitrohigito** [comment]
@kd-11 Good point, but that other thread was opened for that specific game and that game only. As Asinine pointed out in #testers, there was also #5807, which acted as a regression tracker ticket for #5785, but that was closed since.

So, I'm not really sure what the real resolution should be. I could either move this to #5847 if that ticket was aptly renamed, or I could move this to #5807 if it was reopened and #5847 was moved there too.

**Comment by kd-11** [comment]
Create a proper regression ticket and close both this and the other issue. Otherwise they will get lost in the sea of issues and likely never get fixed.

**Comment by nitrohigito** [comment]
I'll ask uaqlover to close that and repost this and maybe that one too as a single regression ticket then.
