### ISSUE TITLE
Feature request possibility to keep (synchronize) Saves to Systems Users directory..

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#5865]
My HDD died, so i have to install emulator from scratch and i lost the saves, i a bit hoped that saves are saved in system users directory like for other apps / games - i mean Users directory for Windows and home for Linux.

 Its possible to implement it, or just add some synchronization between emulators drive and these directory and if there not same or newer saves on emulators hdd, add possiblity to backup saves from users directory?

**Comment by Nekotekina** [comment]
I'm sorry to hear that but I'm afraid it's not emulator's responsibility. Backups are normally user's responsibility. Likely, looking for specialized software which will synchronize backups for you.

**Comment by AniLeo** [comment]
I do this with Dropbox, fairly easy to set up just symlink the home folder to Dropbox. I agree that this is out of RPCS3's scope and would add unneeded complexity and possibly weird bugs too.

**Comment by ruthan** [comment]
It depends, i would say that all modern PC 2005+ games and lots of emulators keep game saves outside of program folder, it would be probably also good for keep more version of emulator available for testing. 
  I dont see too much complexity in implementing such thing, synchronization could be done before / after emulation is started.
  Even PS3 sort of has it you have PS plus, there is could save synchronization too, Xbox has cloud drive too, Steam too and even Gog i thing implemented it for some games.

**Comment by AniLeo** [comment]
This is emulating a complete OS that handles savedata itself, storing it in guest's dev_hdd0/home/USERID/savedata. Other emulators that store savedata where they want aren't emulating the PS3 too so it's unrelated. 

This is not a PC game nor a PC Game Storefront. This is completely out of scope.

**Comment by Relsig** [comment]
I'm also sorry to hear this happened to you. In addition to dropbox if you're using windows you can set windows backup to automatically backup those specific folders at specific intervals. That aside, I would strongly recommend using any of the other free softwares that are available, symlinks, or even a batch file on a cron job. I personally have an autorun batch file on a flash drive that copies important folders whenever i plug it in, though that requires manual intervention.

Dropbox might be a very simple solution or maybe someone has a better idea. Unfortunately this isn't the place for such discussions. You might consider asking for advice on the forums or the discord.

**Comment by ruthan** [comment]
So saves for all games are in dev_hdd0/home/USERID/savedata?

**Comment by MSuih** [comment]
Yes, just like they would be on a real PS3. The only exception are virtual memory cards (for PS1 & PS2 games), which are located in `dev_hdd0/savedata/vmc`. dev_hdd0 "drive" contains other useful files as well, such as earned trophies, installed games and licenses; you can consider backing them up as well..

**Comment by nitrohigito** [comment]
@ruthan Looking at the discussion, there's not much more we can do unfortunately. Please close the issue if you have no more related requests.
