### ISSUE TITLE
Regression : GRAN TURISMO HD Concept [NPEA90002] save doesn't work

### ISSUE THREAD

**Issue by jade010** [RPCS3/rpcs3#5868]
Since: v0.0.6-8000 Alpha [2019-04-19] Pull request: #5792 (ae5a4b69) by elad335
System: i5 4670k and nVIDIA GTX 750Ti
Game: GRAN TURISMO HD Concept [NPEA90002] 

When you boot the game or when you're trying to save a race, the game shows an error.

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3100205/RPCS3.log.gz)

Captures:
![error2](https://user-images.githubusercontent.com/36518512/56458344-bb8eaa00-6385-11e9-9727-6283af13a776.PNG)
![error1](https://user-images.githubusercontent.com/36518512/56458345-bc274080-6385-11e9-97c8-fa69350409b4.PNG)

**Comment by elad335** [comment]
Game sends corrupted buffers to cellSave, looking into.
