### ISSUE TITLE
Regression on Mountain Crime: Requital

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5875]
`·F 0:00:23.354951 {PPU[0x1000005] Thread (PreloadThread) [0x0019f4d4]} MEM: Access violation writing location 0xd01025e8`

log file 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3102167/RPCS3.zip)

**Comment by Realmantik** [comment]
On which builds results are better?

**Comment by AniLeo** [comment]
In what build did it regress?

**Comment by elad335** [comment]
Probably #5214 which makes stack gaps bigger, this game is doing something really sketchy with its stack.
Consider the last few instructions the thread is executing begfore it access violates.
ADDIS moves current stack ptr + 64k to r9 then dereference it, and the thread only got 4k of stack so it cant use those iffsets on his own stack.
![unknown](https://user-images.githubusercontent.com/18193363/57999534-6659cb80-7ade-11e9-8ff1-d06fc68218ee.png)
I'd honestly wait until more more modules will be LLEd and stack will be more accurate as on realhw there are clearly more ppu threads from lle that may change stack layout so it will somehow catch this bad dereference and won't access violate

**Comment by benderscruffy** [comment]
same error
F {PPU[0x1000005] Thread (PreloadThread) [0x0019f4d4]} VM: Access violation writing location 0xd01025e8
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4169860/RPCS3.zip)

**Comment by AniLeo** [comment]
Still an issue, reproduced on RPCS3 v0.0.12-10824-0b023d4e

**Comment by elad335** [comment]
Fixed by #8979
