### ISSUE TITLE
Crash on sceNpTrophyCreateContext (topatoi)

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5876]
![7777788](https://user-images.githubusercontent.com/45731484/56488915-cf750180-6494-11e9-995a-f96b63f1189d.png)

try it to enable Debug Console Emulation 
and gpu texture scaling also same 

log file 

[RPCS31.zip](https://github.com/RPCS3/rpcs3/files/3102574/RPCS31.zip)

TTY
`
New mouse (0) is connected. VENDOR_ID=4660 PRODUCT_ID=4660
New joypad (0) is connected:
	* Joypad conforms to PS3 standards
	* Joypad has pressure sensitivity support
	* Joypad has six-axis sensor support
	* Joypad has high-precision stick support
	* Joypad has vibration feature support
`

**Comment by uaqlover** [comment]
it was pull request by @elad335 but didn't merge

https://github.com/RPCS3/rpcs3/pull/4928

**Comment by Realmantik** [comment]
I have no crashes with this game on latest builds.

**Comment by Megamouse** [comment]
Please test again

**Comment by Realmantik** [comment]
With default settings no crashes.
