### ISSUE TITLE
Sega Rally Online Arcade[NPUB30375]: black screen only

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#5877]
RPCS3 v0.0.6-8004-258df80b Alpha
Archlinux, R9 fury (mesa)

Stuck on a black screen with "Compiling shaders..."
On the console:
```
U {PPU[0x1000000] Thread (main_thread) [0x00c20120]} cellCamera TODO: cellCameraReadEx(dev_num=0, read=0x9fc808)
U {PPU[0x1000000] Thread (main_thread) [0x00c201f0]} cellGem TODO: cellGemGetInfo(info=*0xd0040710)
U {PPU[0x1000000] Thread (main_thread) [0x00c20288]} cellGem TODO: cellGemUpdateStart(camera_frame=*0x0, timestamp=0)
U {PPU[0x1000000] Thread (main_thread) [0x00c20280]} cellGem TODO: cellGemUpdateFinish()
U {PPU[0x1000000] Thread (main_thread) [0x00c20210]} cellGem TODO: cellGemGetState(gem_num=0, flag=0x0, time=0xffffffffffffaa10, gem_state=*0xd0040630)
U {PPU[0x1000000] Thread (main_thread) [0x00c20210]} cellGem TODO: cellGemGetState(gem_num=1, flag=0x0, time=0xffffffffffffaa10, gem_state=*0xd0040630)
U {PPU[0x1000000] Thread (main_thread) [0x00c201f0]} cellGem TODO: cellGemGetInfo(info=*0xd00406b0)
```
![FPS: 0,00 | Vulkan | 0 0 6-8004 | SEGA Rally™ Online Arcade  NPUB30375 _102](https://user-images.githubusercontent.com/7478580/56490533-cb250480-64e5-11e9-9c37-393818cfd3a5.jpg)
Complete log:
[SegaRallyOnline-log.zip](https://github.com/RPCS3/rpcs3/files/3102678/SegaRallyOnline-log.zip)

**Comment by Asinin3** [comment]
Doesn't this game need PSN to work anyway? It's also already listed as Loadable on our compatibility forums. I don't see a need to open issues for games that require PSN to work especially when this is more of a compatibility report rather than a specific issue/regression report.

**Comment by toccata10** [comment]
With libvoice and libaudio (thanks digitaldude: https://forums.rpcs3.net/thread-197979-post-305496.html#pid305496), there's a short intro before freezing (while the fps counter is still fluctuating). Looks like some other guy was able to get ingame (but very slowly).
![Capture_001](https://user-images.githubusercontent.com/7478580/59302234-c681fe80-8c93-11e9-8075-3b9d449d6d5f.jpg)

**Comment by digitaldude555** [comment]
I was that man, have you tried pressing circle button a lot?

**Comment by toccata10** [comment]
Testing on rpcs3-v0.0.6-8355-537d3f25_linux64 today (with libvoice and libaudio)
1) to get pass the frozen screen: I have to press X
2) here are my results:
![Capture_012](https://user-images.githubusercontent.com/7478580/61031774-71cfc180-a3c0-11e9-8a55-4e9da44e785a.jpg)
![Capture_013](https://user-images.githubusercontent.com/7478580/61031780-74321b80-a3c0-11e9-86b1-fa3145d96464.jpg)
So very slow fps
3) the very weird thing: I stop the game and launch it again: here are my results:
![Capture_014](https://user-images.githubusercontent.com/7478580/61031847-975ccb00-a3c0-11e9-82a4-00b9fc516aa1.jpg)
![Capture_015](https://user-images.githubusercontent.com/7478580/61031853-988df800-a3c0-11e9-9d7c-4f7f5a6f6451.jpg)
Graphics are very messed up in menus, but I have a solid 30fps on the track ! It has no sound, but it is enjoyable.
4) If I stop the game and launch it again, I'm back in situation 3. If I close rpcs3 and open it again, I'm back in situation 2
Very weird.

**Comment by toccata10** [comment]
With #6757, the game now plays without any specific config. Sound good, looks nice. Some fps drops, but it now in a great shape.
