### ISSUE TITLE
[SOLVED] Working settings to enable resolution scaling in some (if not all) UE3 based games

### ISSUE THREAD

**Issue by k10kan** [RPCS3/rpcs3#5878]
Affected games:

  * ASURA'S WRATH
  * LOLLIPOP CHAINSAW

Both games use Unreal Engine 3.

After PR #4312 rsx: Epic fixes (rpcs3-v0.0.5-6590-887ea43e_win64) ASURA'S WRATH and LOLLIPOP CHAINSAW work correctly only when resolution scale of 300% is used (4k IR).

Other scale values like:

  * 50% (downscale)
  * 100% (no rescale)
  * 150% (upscale - 1080p)
  * 200%
  * 250%
  * 350%
  * 400%

produce red texture artefacts, as can be seen on provided RSX captures. Haven't tested greater scale values because for my 750Ti w/ 2GB even some of these values are way too much, let alone bigger ones.

Both OpenGL/Vulkan renderes are affected.

"Use GPU Texture Scaling" has no effect (either ON or OFF).

If Strict Rendering Mode is applied, everything works ok (alas at lower resolution).

SPU Decoder ASMJit/LLVM behave the same.

First previous PR #4328 (rpcs3-v0.0.5-6579-a35bcb13_win64) had many other issues that #4312 solved (like red eyes in ASURA'S WRATH), but on that PR resolution scaling works with **any** other scale value without red texture artefacts.

Last Good Build:  rpcs3-v0.0.5-6579-a35bcb13_win64 (2018-03-24)
First Bad Build:  rpcs3-v0.0.5-6590-887ea43e_win64 (2018-03-25)
Latest Bad Build: rpcs3-v0.0.6-8004-258df80b_win64 (latest)

How to reproduce:

Run ASURA'S WRATH, start Episode 1 and 55 seconds into it red texture artefacts will pop up.

Resolution Scale of 150% (1080p) - BAD
![150percent](https://user-images.githubusercontent.com/37659629/56514215-04389580-6535-11e9-8c48-43b4f6e7aa16.png)

Resolution Scale of 300% (2160p) - GOOD
![300percent](https://user-images.githubusercontent.com/37659629/56514218-07338600-6535-11e9-8fb5-c1491cf6aa8c.png)

RSX Captures made on RPCS3 0.0.6-8004-258df80b Alpha using default settings, only changing SPU Decoder from ASMJIT to LLVM, and setting GPU renderer to Vulkan with Resolution Scale of 150% (red texture artefact) and 300% (all ok).

[BLES01227_20190422190041_capture_rpcs3-v0.0.6-8004-258df80b_150percent_BAD.rrc.zip](https://github.com/RPCS3/rpcs3/files/3104260/BLES01227_20190422190041_capture_rpcs3-v0.0.6-8004-258df80b_150percent_BAD.rrc.zip)
[BLES01227_20190422190932_capture_rpcs3-v0.0.6-8004-258df80b_300percent_GOOD.rrc.zip](https://github.com/RPCS3/rpcs3/files/3104262/BLES01227_20190422190932_capture_rpcs3-v0.0.6-8004-258df80b_300percent_GOOD.rrc.zip)

**Comment by RainbowCookie32** [comment]
At least for Asura's Wrath you have to increase the scale threshold to 512x512 to avoid those artifacts

**Comment by MSuih** [comment]
Resolution scaling is a hack and will never work with every single game out there. The red artifacts just happen due to the way UE3 is programmed and how that interacts with scaling. If scaling threshold doesn't help then you'll just have to use 100% scaling with these games.

**Comment by k10kan** [comment]
Thanks for quick replies and useful advice.

Just finished some testing and it took some time...

I have tested both ASURA'S WRATH and LOLLIPOP CHAINSAW and **both work** with other resolution scale values (50%, 150%, 350%) when resolution scale threshold is set to 512x512.

I was informed that resolution scaling is a hack that sometimes works, sometimes does not, but it did work before as explained (maybe you missed that part MSuih), so this is a bit different than previous cases.

Having said that, **this is technically a regression** since in PR #4328 (rpcs3-v0.0.5-6579-a35bcb13_win64) all resolution scale values worked with default resolution scale threshold of 16x16, and after PR #4312 hit master, it regressed, and it needs manually setting arbitrary value!

All versions after PR #4312 **do not work** with 16x16 scale threshold when using other scale values but 300%, but require modification (in this case setting scale threshold to 512x512).

However, I have no problem in closing this issue if you or others strongly advise it.

It does look like out there could be a solution, but if devs do not fill it is worth doing it at this time due to some other things being more important and such, or any other reason, fine by me.

Will wait a bit and take necessary action (close issue or supply additional infos/logs)...

**Comment by k10kan** [comment]
After analyzing this issue with RenderDoc v1.2, it turned out that PR #4328 rendered differently but that it also contained red texture artefacts, just in different places, and that makes this issue not a regression, and effectively non-issue.

Thanks for help and answers that pointed to correct solution to make resolution scaling in (at least these two) UE3 based games.

I have changed the title so others that may stumble here could find some info that may help them, too.

If someone has other UE3 based PS3 titles, please try if setting 512x512 scale threshold makes resolution scaling working for them also and share your findings.

**Comment by kd-11** [comment]
Also I feel like I need to mention this - non-integer scaling is going to be sketchy in most modern engines. This is why even the Xbox back-compat emulation only uses integer scaling (100%, 200%, 300%). This is usually because some data types do not like getting filtered as they may not contain pixels but arbitrary data like motion vectors, luminance coeffecients, vertex attributes (render-to-vertex-buffer) etc. Fortunately, since these kinds of high precision floating point operations are quite heavy for the rather weak PS3 GPU, they are often done at a lower resolution (as they still are even on modern titles for performance reasons). This is why the threshold works so well for such situations since it allows skipping small renders which are more likely to contain such data.
