### ISSUE TITLE
Regression Bayonetta graphical issue 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5880]
was fine in  0.0.6-7786 
![FPS_ 60 10 _ Vulkan _ 0 0 6-7786 _ BAYONETTA  NPEB01134  23_04_2019 5_33_37 AM](https://user-images.githubusercontent.com/45731484/56581586-20b2ed00-658a-11e9-9f3f-75381d0e6652.png)
little bit off like https://github.com/RPCS3/rpcs3/issues/2481 0 0 6-7935 
![FPS_ 60 00 _ Vulkan _ 0 0 6-7935 _ BAYONETTA  NPEB01134  23_04_2019 5_36_46 AM](https://user-images.githubusercontent.com/45731484/56581608-2b6d8200-658a-11e9-83ee-fd6dfbf32eaa.png)
in 0 0 6-8004 full black 
![FPS_ 59 96 _ Vulkan _ 0 0 6-8004 _ BAYONETTA  NPEB01134  23_04_2019 5_25_13 AM](https://user-images.githubusercontent.com/45731484/56581656-47712380-658a-11e9-8160-8d3927f08eb1.png)

**Comment by Asinin3** [comment]
I remember this being a random issue, even a year or two ago that randomly occured. Are you sure about this one?

**Comment by uaqlover** [comment]
yes i'm sure i clean cache's and start it a new game. still same 

and before https://github.com/RPCS3/rpcs3/pull/5785 was little bit better in this build 0 0 6-7935 

![FPS_ 60 00 _ Vulkan _ 0 0 6-7935 _ BAYONETTA  NPEB01134  23_04_2019 5_36_46 AM](https://user-images.githubusercontent.com/45731484/56583470-76899400-658e-11e9-8e67-04b563819ee4.png)

but in latest build full black 

![FPS_ 59 99 _ Vulkan _ 0 0 6-8004 _ BAYONETTA  NPEB01134  23_04_2019 6_06_12 AM](https://user-images.githubusercontent.com/45731484/56583314-27436380-658e-11e9-8e6c-535f1ad8cf81.png)

do you need RSX Capture ?

**Comment by Asinin3** [comment]
You should always include RSX captures or Renderdocs when reporting a graphical issue. If it's a regression, maybe post a before/after RSX/Renderdoc as well so if someone needs to look into it they can compare the captures.

**Comment by uaqlover** [comment]
rpcs3-v0.0.6-7786

https://drive.google.com/file/d/1MmnR1w_v5FunQNj6rxCu8CtsWQzepjFL/view?usp=sharing

rpcs3-v0.0.6-7935

https://drive.google.com/file/d/1XQ67fHyD5TK0Fr5wLCIx-d5qm2_VHTjr/view?usp=sharing

rpcs3-v0.0.6-8004

https://drive.google.com/file/d/1fUgKSSQSTFuNOx23aKmxLRLtRHfShkDl/view?usp=sharing

in v0.0.6-7786 it not shows this 

in log file `E {RSX [0x0056678]} RSX: Could not gather all required slices for cubemap/3d generation` in v0.0.6-7935 and v0.0.6-8004 only

**Comment by TigiHof** [comment]
Just wanted to confirm this regression on a freshly installed version rpcs3-v0.0.6-8004 (Nvidia GTX 1070).

**Comment by legend800** [comment]
For your issue submissions, can you please add a brief description in the title so people know what the issue is without having to open and read details.

**Comment by uaqlover** [comment]
let @AniLeo or @kd-11 to add proper title for the issue

**Comment by legend800** [comment]
It takes a couple secs to summarize your issue into a sentence. You need a decent title for proper defect submission. Everyone else writes their own without bothering devs\admins fyi. And don't ping kd-11 for stuff like this (remove that).

**Comment by TigiHof** [comment]
Just wanted to bump this issue. It is still relevant with the latest release!

**Comment by uaqlover** [comment]
Game is fixed now playable on RPCS3 v0.0.6-8503-f2a2dfda Alpha

https://imgur.com/a/95mxORE

**Comment by TigiHof** [comment]
I did a fresh install of RPCS3 v0.0.6-8510-d8402008_win64 an cannot confirm at all that this issue is fixed. At the start of the game the problems are exactly the same as before.

**Comment by Asinin3** [comment]
Yes another user also talked to me today who tried Bayonetta for the first time and it was still there. It's very random.
