### ISSUE TITLE
It couldn't find the Radeon RX 550 in vulkan mode, and I detected that the RX 550 supported vulkan using gpu-z

### ISSUE THREAD

**Issue by glasscat** [RPCS3/rpcs3#5887]
![image](https://user-images.githubusercontent.com/21314345/56788970-6219f580-6833-11e9-8f84-9fcb87023df2.png)
System：Windows 10
RPCS：0.0.6-8034

**Comment by MSuih** [comment]
It's an issue with your drivers. Use DDU to wipe away your current drivers and then install latest ones from [here](https://www.amd.com/en/support/graphics/radeon-500-series/radeon-rx-500-series/radeon-rx-550). If you have any questions or need further help, join the Discord server. Github issue tracker is not the place for tech support.
