### ISSUE TITLE
[Request] Add steam-devices package on Ubuntu/Debian a requirement for making PS4 controller working in RPCS3

### ISSUE THREAD

**Issue by Lukypie** [RPCS3/rpcs3#5892]
Hi, I am making this just for letting you know that RPCS3 Dualshock 4 detection doesn't work on Ubuntu/Debian based distros when the steam-devices package (udev rules) is not installed, and since evdev doesn't seem to behave nicely (Maybe another bug separate for that) 

I would suggest to add this as a requirement for Linux on Ubuntu distros users, maybe in the FAQ? 

Or is there a way to add an udev rule via .appimage in the local user config directory? (I don't think)

**Comment by JohnHolmesII** [comment]
Just installed a clean ubuntu 19.04, and following the instructions on the wiki [wiki](https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration) worked just fine.

Installing the steam-devices package did not help at all. The same rpcs3 error as if no action was taken over vanilla ubuntu occurred.

@AniLeo recommend simply closing

**Comment by Lukypie** [comment]
Yeah I know, that steam package isn't hooked too but the rules are almost the same, strangely enough the steam package on the valve website is different than the one from Ubuntu

And anyway, I just wanted to point out a simple alternative to newbies who do not feel comfortable using the terminal

**Comment by RainbowCookie32** [comment]
If the instructions on the wiki work fine, then this should be closed. No need to make installing a package a required/recommended thing when adding a few lines to a file gets the job done as well

**Comment by RussianNeuroMancer** [comment]
I guess then there is no need for releasing rpcs3 binary builds if simple "make" command gets job done as well.

**Comment by RainbowCookie32** [comment]
Are we really comparing compiling RPCS3 to pasting a few lines into a file? 
People can install the package if they want to, but we already cover what I think is a simpler way of doing it without having to download unneeded stuff. I don't think it's needed to add this package as a requirement/recommendation. Can always add it as a note on the wiki I guess

**Comment by RussianNeuroMancer** [comment]
People can install Slackware or Gentoo if they wanted to. But most of the gamers would like avoid unnecessary fiddling with "few lines files" as much as possible, with shortest trajectory from intention to play the game and playing the game. Need to create/edit some file, applying it with some systemd commands (or reboot) just to get gamepad working - is really unnecessary when there is already working solution that allow to avoid this.

steam-devices size is 20 kilobytes - what we were arguing about?

**Comment by JohnHolmesII** [comment]
as i said, it is actually 250 mb. You just so happen to have those packages installed. You two are the only users who seem to suggest that this is an issue. Copying and pasting a file off the wiki it not slackware or gentoo, and it really isn't even close. Please end the ridiculous hyperbole.
