### ISSUE TITLE
Silent Hill Downpour: Vulkan API unrecoreable error

### ISSUE THREAD

**Issue by alexsilva** [RPCS3/rpcs3#5898]
Windows 10 64bits
Current RPCS3 version `0.0.6-8039-c24b7439`
Old RPCS3  version that works: `0.0.6-7986-1152317b`

Main error:

"""
·F 0:04:11.882856 {RSX [0x001b5a8]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:964)
"""

It has the log of the two versions for comparison.

[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/3132648/rpcs3.zip)

**Comment by kd-11** [comment]
You need to provide more information on how to reproduce the actual crash. For example,with https://github.com/RPCS3/rpcs3/pull/5895, the game loads just fine; so there must be special steps to make this happen.

**Comment by alexsilva** [comment]
I did not do more than start the game.

**Comment by kd-11** [comment]
Did you try the build from the pull request? I was able to reach menus with no issues. Build link https://ci.appveyor.com/project/rpcs3/rpcs3/builds/24185666

**Comment by alexsilva** [comment]
Yes! v0.0.6-30bf3e11 works.

**Comment by alexsilva** [comment]
log v0.0.6-30bf3e11 (if useful).
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3133264/RPCS3.log.gz)
