### ISSUE TITLE
Tekken Tag Tournament 2 - Black texture on all characters clothing. 

### ISSUE THREAD

**Issue by tabnk** [RPCS3/rpcs3#5900]
Tekken Tag Tournament 2 - Black texture on all characters clothing. 

Tested on 0.0.6-8043 with Windows 10/Nvidia GPU 960/ Vulkan 

<img width="1270" alt="Untitled" src="https://user-images.githubusercontent.com/10874582/57005857-f9a18e80-6c0d-11e9-9be3-9e9927b8a40c.png">

<img width="1280" alt="Untitled2" src="https://user-images.githubusercontent.com/10874582/57005859-ff976f80-6c0d-11e9-9337-9fe0dd32fc20.png">

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3133810/RPCS3.log.gz)

**Comment by Asinin3** [comment]
Enable write color buffers, like i wrote in my compatibility tests on the forum

**Comment by kd-11** [comment]
Request to reopen if problems persist with proper settings.

**Comment by tabnk** [comment]
Enabled write color buffers does fixed the issue, although it was never required before.

**Comment by Asinin3** [comment]
It always required it. https://forums.rpcs3.net/thread-192189-post-299212.html#pid299212
