### ISSUE TITLE
How to Use Japanese on the Screen Keyboard?

### ISSUE THREAD

**Issue by DS8PPD** [RPCS3/rpcs3#5902]
Hello I've downloaded RPCS3 to do the initial stage Extreme Stage, but I have a big problem, I can not play the game because I can not write Japanese on the license plate of the car with the screen keyboard. Is there any way to write Japanese on the screen keyboard? #

**Comment by HerrHulaHoop** [comment]
On-screen keyboard does not currently support non-English character. Disable Native UI and use Qt dialogs instead. 

The issue tracker is not for support requests. Use our Discord server or Forums for that. Please close this issue.

**Comment by AniLeo** [comment]
There's already an issue tracking remaining stuff on OSK including that, closing as duplicate.
