### ISSUE TITLE
Failed to kill process after emulator stucked

### ISSUE THREAD

**Issue by kotori2** [RPCS3/rpcs3#5906]
System: Windows 10 RS5
Hardware: i7-8700K/RTX2080Ti/16GB
Version: v0.0.6-8004-258df80b/v0.0.6-8051-6b7cd458

I was testing out 初音ミク -Project DIVA- F 2nd [NPJB00435] but the window froze. 
I tried to force close the emulator and one process stay unkilled. And I tried to kill that process with task manager, but it says "access denied". 
![ss](https://user-images.githubusercontent.com/17663689/57072226-8d0eb880-6d0f-11e9-9c5f-7e947286912f.png)
I also tried `taskkill /f /t /im rpcs3.exe` but it seems not working.
```
PS C:\WINDOWS\system32> taskkill /f /t /im rpcs3.exe
ERROR: The process with PID 4168 (child process of PID 9380) could not be terminated.
Reason: There is no running instance of the task.
```
It seems an older version (some version at v0.0.5, but i can't remember) doesn't have this issue.
I can reproduce this bug with many game. And it seems the only solution to kill that process is to reboot.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3137764/RPCS3.log)
~~Anyway I think this log contains nothing useful~~

**Comment by AniLeo** [comment]
Stuck on NVIDIA hook, probably duplicate issue

**Comment by kotori2** [comment]
@AniLeo #5351 ? Seems it is an old issue since Nov 2018, but does it really related to the unkillable process?

**Comment by AniLeo** [comment]
Yeah, try reverting to driver 399 to confirm

**Comment by kotori2** [comment]
@AniLeo I checked but it seems 399 doesn't support RTX 2080 Ti. Going to close this and wait for a fix.
