### ISSUE TITLE
Crash during firmware ppu compilation

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#5908]
How to reproduce:
File->Install Firmware
Choose "PS3UPDAT.PUP" file
When window "Compiling PPU modules..." pops up, press Pads button. Crash occurs immediatly.
![Desktop_2019_05_02_22_08_27_830_cr](https://user-images.githubusercontent.com/22906342/57101423-db30b580-6d29-11e9-928b-40fa2409c4c4.png)

**Comment by AniLeo** [comment]
Confirmed

**Comment by GarettJaxx** [comment]
Only way I could get around this was to delete the "Dev_Flash" directory and then install the firmware

**Comment by AniLeo** [comment]
Nope. There's no dev_flash folder on a clean installation and this happens regardless. How would pads even interfere with a dev_flash folder being there before you install the firmware which creates the folder?

**Comment by AniLeo** [comment]
Call Stack

![image](https://user-images.githubusercontent.com/10283761/57183749-5c628680-6ea9-11e9-8e6e-f7c603733b85.png)

**Comment by GarettJaxx** [comment]
ah ok - to be fair i was using my existing installation, not fresh

Apologies if I mislead

**Comment by digitaldude555** [comment]
Still issue in the year 2020.

**Comment by hradec** [comment]
This is happening to me to in Linux. Just download the latest version, latest firmware, and it crashes consistently when compiling PPU. 

I can't run it!

**Comment by Nekotekina** [comment]
Need more informatiion about Linux crash.

**Comment by meikodunois** [comment]
Still an issue in 2022, and it seems nobody cares

**Comment by AniLeo** [comment]
If we can't reproduce, it's not a bug.
