### ISSUE TITLE
Physic problem - Little Big Planet [BCES00611]

### ISSUE THREAD

**Issue by AMMAREN** [RPCS3/rpcs3#5911]
Speed   : Slow
Movie   : Work
Graphic : Work with physic problem
Music   : Work

See this Link For details

- https://forums.rpcs3.net/thread-187762-post-304889.html#pid304889

**Comment by AniLeo** [comment]
Report was submitted with a non-master build, closing as invalid and moved thread to General Discussion

If this issue also happens on current master, submit a proper issue, read the guidelines before submitting
