### ISSUE TITLE
Access violation reading location problem

### ISSUE THREAD

**Issue by AMMAREN** [RPCS3/rpcs3#5912]
The RPCS3 Stop (Both ASMJIT and LLVM Recompiler)
Then said this message

STREET FIGHTER X TEKKEN [NPEB01792] --- (Resource Manager) [0x00aa47c4]} MEM Access violation writing location 0x0
See this Link For details:-

- https://forums.rpcs3.net/thread-174857-post-304890.html#pid304890

---------------------------
Call of Duty® Black Ops [BLUS30591]  ---  Access violation reading location 0xcf91aa00                                          
See this Link For details:-

- https://forums.rpcs3.net/thread-181391-post-304891.html#pid304891

---------------------------
Call of Duty® Ghosts [BLES01945] --- MEM Access violation reading location 0xcfae4000
See this Link For details:-

- https://forums.rpcs3.net/thread-199093-post-304892.html#pid304892

--------------------------
Modern Warfare® 2 [BLES00683] --- MEM Access violation reading location 0xcfaee000
See this Link For details:-

- https://forums.rpcs3.net/thread-200455.html

--------------------------
DYNASTY WARRIORS GUNDAM Reborn [BLES02057] --- Thread (CStageSceneBuilder) [0x001fff54]} MEM Access violation reading location 0x10010010 
See this Link For details:-

- https://forums.rpcs3.net/thread-194635-post-304894.html#pid304894

--------------------------
Tom Clancy's™ Splinter Cell Chaos Theory® HD [NPEB00557] --- Thread (MAINTHREAD) [0x00625998]} MEM Access violation writing location 0xd004cfe0
See this Link For details:-

- https://forums.rpcs3.net/thread-194892-post-304895.html#pid304895

**Comment by Emogop** [comment]
The same for me with Silent Hill Downpour
Was working fine with LLVM Recompiler until recently. Now I got this even before the game shows some logo:
F {PPU[0x1000013] Thread (CellMemoryManager) [0x0074ea24]} MEM: Access violation reading location 0x1aca62c4
But with ASMJIT the game still works.

**Comment by AniLeo** [comment]
Those are symptoms of other problems, every one of these can be caused by a different issue

All of these were tested on non-master builds too, so the issue is invalid, read the guidelines before submitting
