### ISSUE TITLE
Drakengard 3 can't start new game with SPU LLVM after recent commits

### ISSUE THREAD

**Issue by z0z0z** [RPCS3/rpcs3#5914]
﻿RPCS3 v0.0.6-8056-2b4da187

After recent commits in the past few days, I can't start a new game in Drakengard 3 with SPU LLVM, RPCS3 just freezes and needs to be killed.

I see this in the console right before that happens:

![image](https://user-images.githubusercontent.com/12925873/57179578-d0336d80-6e6e-11e9-84b0-3be87bfa8657.png)

Here's a log file: 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3144467/RPCS3.zip)

**Comment by AniLeo** [comment]
Which PR regressed this? Likely one of the last Nekotekina PRs since they touched this part of the code

**Comment by z0z0z** [comment]
It's only after this https://github.com/RPCS3/rpcs3/pull/5901
