### ISSUE TITLE
ratchet and clank: tools of destruction [BCES0052] crashes on startup on openGl

### ISSUE THREAD

**Issue by allhailbilloverbeck** [RPCS3/rpcs3#5918]

**Comment by RainbowCookie32** [comment]
No system specs, no log. Read the guidelines before opening issues https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md

**Comment by allhailbilloverbeck** [comment]
ratchet and clank tools of destruction crashes when launching on opengl with current build [8064]. works fine on vulkan, tried clearing spu and shaders cache, still crashes
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3145182/RPCS3.log)

AMD fx-6300 6 core cpu
gtx 1050ti
8gb ddr3 ram
windows 7 SP1
all gpu drivers up to date

**Comment by allhailbilloverbeck** [comment]
> No system specs, no log. Read the guidelines before opening issues https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md

sorry, just posted them, accidently post before i wrote specs and provided the log file

**Comment by allhailbilloverbeck** [comment]
re tested on latest build, same issue

**Comment by AniLeo** [comment]
Fixed by #6376
