### ISSUE TITLE
It is impossible to enter a name

### ISSUE THREAD

**Issue by dev-iCEY** [RPCS3/rpcs3#5920]
Guys, I understand that you are doing everything for the convenience of users, but unfortunately, I can not start the game until I enter the name in Japanese. I have a Japanese layout, but now I can't just type characters from the keyboard. Is it possible to correct this, add a setting, for example, what would be the choice of input, through the pop-up window it was much more interesting. The game is [BLJM60223] 
![изображение](https://user-images.githubusercontent.com/36455482/57191324-eef83980-6f2c-11e9-818a-91e6018751cb.png)

![изображение](https://user-images.githubusercontent.com/36455482/57191320-e6076800-6f2c-11e9-8c5b-02847dfaacf0.png)

**Comment by raveskirza** [comment]
Duplicate. See #5902

**Comment by kd-11** [comment]
There is literally an option to disable all of the integrated dialogs in the emulator settings tab that will give you back the old osk.
