### ISSUE TITLE
Website is GPU Intensive

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#5925]

**Comment by AniLeo** [comment]
This is not the website repository, but that's load from your browser's javascript rendering engine for sure.

You can use every part of the website apart from the index with javascript turned off if you prefer.

**Comment by smathews** [comment]
@AniLeo Just noticed this, its alarmingly high (40%). You guys trying to mine with visitors gpus?

**Comment by AniLeo** [comment]
If your CPU hits 40% just from opening a website I think you need a better CPU.

You can turn off javascript if you want, I certified the website is 100% noscript compatible.

**Comment by RainbowCookie32** [comment]
CPU usage seems to come from the visual effects on the site. Disabled Particles, Waves, and Pulsate and CPU usage dropped to 0% (down from 1% :D)

**Comment by snakeeater4526** [comment]
well actually i confirm that fact , when you open the website it take around 15 to 20% of my 3080 xD

i don't complain just confirm the fact ^^

**Comment by smathews** [comment]
@AniLeo while not a gaming card, my xe g7 isn't exactly a bad performer, especially for an informational website. And seeing that @snakeeater4526's 3080 is registering 15-20% definitely confirms this. I understand that this might not be your issue being that its for the website and not the emulator, but it needs to be investigated more than just telling some to get better hardware. 

@RainbowCookie32 gpu not cpu.

**Comment by RainbowCookie32** [comment]
> @RainbowCookie32 gpu not cpu.

Yeah, misread. But it's still the same deal. Went from 7% usage to 0 after disabling the visual effects

**Comment by AniLeo** [comment]
It's from drawing the visual effects, you should ask @DAGINATSUKO to see if there are ways to optimize it as I avoid javascript like the plague, I work on the backend and that doesn't have a single line of JS.

**Comment by MSuih** [comment]
Maybe the animation processing could be paused if the page is out of focus? That would help the case where someone forgets the page in background and it hogs resources for no purpose. Another option is to pre-render the animation as a video file, but the downsides of that are not worth the reduced gpu load.

Causing a higher GPU usage when the page is focused seems fine to me, as the visual effects look nice and I don't expect anyone to spend long time on the main page.

**Comment by jobs-git** [comment]
Glad that this was noticed after 1.5 years, lol. Then this should be re-opened? That time when I created this, I could not find the www repo for rpcs3. I was using GTX 1060, so the website should not be that hard on GPU.
