### ISSUE TITLE
Regression: Test Drive Unlimited 2 [BLES00884] (#5565)

### ISSUE THREAD

**Issue by jenci8888** [RPCS3/rpcs3#5926]
I wasn't very motivated to report issue but now I have to post... 

Anyway, TDU2 has been regression since PR#5565 and one the commit breaks this one [5bc8b39](https://github.com/RPCS3/rpcs3/commit/66559fb258f413ee0664f53cbe387e220ece6e35)
Before: 0.0.5-7742
![image](https://user-images.githubusercontent.com/40495799/57198969-ad41b000-6f79-11e9-9280-7772c29f9685.png)
After: 0.0.5-7755, just before start menu screen. (after intro)
![image](https://user-images.githubusercontent.com/40495799/57198974-bdf22600-6f79-11e9-93f4-e825d40dfa12.png)

log:
[RPCS3.log.gz - Before](https://github.com/RPCS3/rpcs3/files/3145914/RPCS3.log.gz)
[RPCS3.log.gz - After](https://github.com/RPCS3/rpcs3/files/3145925/RPCS3.log.gz)

**Comment by AniLeo** [comment]
@kd-11 Any idea what regressed here? It's not a small commit unfortunately

**Comment by kd-11** [comment]
Please retest.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/6164
