### ISSUE TITLE
File creation exception in `dev_hdd0\game`. AMD Ryzen Threadripper 2950X 

### ISSUE THREAD

**Issue by 3038922** [RPCS3/rpcs3#5927]
The first run can enter the game normally. Because of the abnormal storage, the second run will make a mistake.

win10 1809 17763.437
rpcs3 0.0.6-8071 
AMD Ryzen Threadripper 2950X
2080TI

**Comment by 13xforever** [comment]
Please follow the [guidelines](../blob/master/.github/CONTRIBUTING.md) and provide logs as you were asked in the issue template.

**Comment by AniLeo** [comment]
Missing log file, will be closed if it doesn't comply to guidelines
