### ISSUE TITLE
Virtua Fighter 5 Random Freeze

### ISSUE THREAD

**Issue by schubertguilherme** [RPCS3/rpcs3#5934]
The game freeze random, run very best in 60FPS, but freeze frequently.

**Comment by RainbowCookie32** [comment]
Please read the guidelines before opening an issue https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md

You skipped system specs and a log

**Comment by schubertguilherme** [comment]
All right thanks.

**Comment by elad335** [comment]
Hello, you might have pressed the comment & close button accidentaly? In this case you can reopen.
