### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [RPCS3/rpcs3#5935]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by AniLeo** [comment]
We already distribute RPCS3 as AppImage as far as Linux builds go. There's no reason to switch to FlatPaks as the AppImage is working properly.

**Comment by AniLeo** [comment]
Added Discussion tag, it's expected reasons to switch from AppImage to FlatPak bundling are provided since the links above don't do any sort of comparison between the two but only mention the advantages of using an approach like this over the standard per distro bundling, otherwise there's obviously no reason to switch over.

**Comment by Relsig** [comment]
AFAIK Flatpak doesn't offer any significant advantages over AppImage that would benefit RPCS3 and, in fact, has several 'benefits' that may be considered detrimental in this case.

For your reference:
https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison

**Comment by Leopard1907** [comment]
Well , AppImage works great as of now. No need to change imo. Only if Rpcs3 Appimage's had Rpcs3 logo...

**Comment by LeandroStanger** [comment]
I am [Endless OS](endlessos.com) user only Flatpak is supported

**Comment by RipleyTom** [comment]
Afaik you can run appimages on Endless OS just fine.
Supporting Flatpak would be the same as making .deb or .rpm packages because that's the "standard" of some distributions, it wouldn't make much sense.

**Comment by LeandroStanger** [comment]
@barthalion @TingPing

**Comment by kd-11** [comment]
Closing since appimages are already supported.

**Comment by osirase** [comment]
Where can I find information on how rpcs3 is packaged into a snap image?

**Comment by mhoangvslev** [comment]
With flatpak the app is more integrated into the system. You can find it in application, pin it, etc. If you want to upgrade, you can do flatpak upgrade and that's it.

**Comment by Lctrs** [comment]
Hi @mhoangvslev, an unofficial flatpak exists for rpcs3, you can find it on [flathub](https://flathub.org/apps/details/net.rpcs3.RPCS3).

**Comment by mhoangvslev** [comment]
@Lctrs In fact, when used with https://github.com/TheAssassin/AppImageLauncher, AppImage is best because it's self-contained.

**Comment by Danik1601** [comment]
> Hi @mhoangvslev, an unofficial flatpak exists for rpcs3, you can find it on flathub.

Unofficial is still unofficial and may not always work correctly without the developer's support😟.

My question is: Is it really hard to maintain both AppImage and Flatpak versions?
They both work across distributions, but they serve different purposes. Flatpak is more like a traditional installed application while AppImage is more like Windows's portable application. So I don't believe that some version should replace the other. I personally prefer Flatpak so I would like to see official Flatpak support at some time.

**Comment by reggiiie** [comment]
One advantage of flatpak would be support for musl based distros (Void and Alpine) cause AppImages don't work on them unlike flatpaks. Also, and this is just my personal opinion, flatpaks are better than appimages because the appimage is just gonna be in a random directory where user downloads it, while flatpak manages things for you and makes it easy to install or uninstall software without having to look for it.

**Comment by matheuswillder** [comment]
Just in case any user finds this, the unofficial Flatpak/Flathub build is experiencing issues so the games currently no longer launch with it, this can be tracked here: https://github.com/flathub/net.rpcs3.RPCS3/issues/1874

Regarding the upstream supporting Flatpak or not, I think all the pros and cons have already been raised in this issue, so I would just like to point out that, over the years, Flatpak seems to be becoming the most popular way to packaging and distributing apps on Linux, finally ending the packaging mess that Linux was before.

It is supported by the Steam Deck and out-of-the-box by many popular distros, and many emulators currently also have adopted it for distributing their builds to Linux users, such as PCSX2, Azahar, Cemu and melonDS, just to name a few (some of these still support .AppImage as well), and Dolphin already host their own Flatpak builds on their website.

So I hope this will be reconsidered at some point.

Edit: corrections.

**Comment by ghost** [comment]
> So I hope this will be reconsidered at some point.

Only rpcs3 appimage is supported.
