### ISSUE TITLE
Vulkan exhausts compute heap when using high resolution scaling

### ISSUE THREAD

**Issue by alex88510** [RPCS3/rpcs3#5938]
When using vulkan, the game graphic was corrupted
This was regressed after #5785 has merged. 
![miku_latest](https://user-images.githubusercontent.com/6214348/57386099-4d037600-71e6-11e9-97e2-eb9c55a692ef.PNG)

It was spamming error message like this
`E {RSX [0x0030a68]} RSX: Inadequate buffer length submitted for a compute operation.Required=117964800 bytes, Available=67108864 bytes`
[RPCS3_latest.log.gz](https://github.com/RPCS3/rpcs3/files/3157983/RPCS3_latest.log.gz)

The master version before #5785 merged is working fine. 
![miku_working](https://user-images.githubusercontent.com/6214348/57385623-57714000-71e5-11e9-9b7a-5d734680f536.PNG)
[RPCS3_working.log.gz](https://github.com/RPCS3/rpcs3/files/3157955/RPCS3_working.log.gz)

However, if disabled the scaling (back to 100%), it works fine. Usually I use 250% scaling.

**Comment by z0z0z** [comment]
Might be Nvidia/Windows specific, because game works for me on RX580/RADV, and it also spams this

```E {RSX [0x0030a68]} RSX: Inadequate buffer length submitted for a compute operation.Required=117964800 bytes, Available=67108864 bytes```

So that probably doesn't matter.

You should try clearing the shader cache.

**Comment by vsub** [comment]
I have little weird problem
If I set the resolution to 1280x720 with 150% scaling,everything is fine(and no spam)
If I set the resolution to 1920x1080 with 150% scaling,everything is fine(and no spam)
720x480 also the same result

But settings the scaling to 200%,I get the spam on all 3 resolutions(the game is still working,I don't get that black screen)

250% - 720x480 work fine but I get the spam
250% - 1280x720,spam and black screen
250% - 1920x1080 ,work fine but I get the spam

300% - 720x480 work fine but I get the spam
300% - 1280x720,Device Lost(rpcs3 crashes)
300% - 1920x1080 ,work fine but I get the spam

nvidia gpu on windows

**Comment by kd-11** [comment]
This game's base resolution is already 200% internal scaling (1440p) on PS3. Adding more scaling on top of that is blowing the VRAM budget for compute and causing the error. I have patches to unlock this limit coming soon.

**Comment by alex88510** [comment]
That is good to hear but wondering why the base resolution is already 200% scaling...

**Comment by kd-11** [comment]
Maybe my phrase was too vague - the game runs at 1440p internally, so if you add 200% scaling to that, its 5k rendering, not 1440p. The game developers just decided to do this to improve visuals on PS3, especially since the game's graphics are very basic. There are games that run at very high res on PS3, but of course it has to be a very simple game to be able to do so. We cannot determine the internal resolution of a game without messing with it, which is why the resolution scaling slider shows incorrect values for games that do not render at 720p natively.

**Comment by AniLeo** [comment]
@kd-11 can you rename this one and tag appropriately since you know what's the issue and already have patches planned for it?

**Comment by alex88510** [comment]
Not sure since which PR but I think the issue has been somewhat resolved. 

Tested 300% scaling from kd-11 latest PR #6112 and looks fine
![3](https://user-images.githubusercontent.com/6214348/59937378-dca67080-9484-11e9-9cd6-77111b2438fb.PNG)

However the same error message is still being spammed...
Wondering if I should close this instead?

**Comment by kd-11** [comment]
Don't close, its still an issue, but the optimizations have made its impact less awful.

**Comment by alex88510** [comment]
tested again with the latest master, with 250% scaling, the game works fine with no error message spammed. 
![f](https://user-images.githubusercontent.com/6214348/63850761-66177900-c9c7-11e9-9638-a05bb9c1d4b7.PNG)

With 300% scaling, the same error message is spammed however my GPU is becoming the bottleneck at that point as the game no longer runs at full speed (GPU usage maxed at 100%).

@kd-11 is this still an issue or I can close it?

**Comment by kd-11** [comment]
Leave it open for now. I'll close it when I get around to improving memory management.
