### ISSUE TITLE
[BLES01035] Call of Duty Black Ops - broken vram copy

### ISSUE THREAD

**Issue by QuaiGoner** [RPCS3/rpcs3#5941]
Game is able to boot and go ingame and compile shaders, but doesnt show anything. Same with Vulkan/OpenGL - SPU ASMJIT/LLVM
No errors in log.
Tested with latest master a this moment (8085)
![image](https://user-images.githubusercontent.com/41058180/57427275-6be92300-724d-11e9-83c4-8f9598adb000.png)
RSX Capture - Vulkan:
https://mega.nz/#!mn4QWSoB!EAtOKI2rWEI1Op1j-KAIHmBpBgMcuypgrxU03JULJ8w
RSX Capture - OpenGL:
https://mega.nz/#!nyow2STR!pwZD9sKovmm9ggxeHHISO_o-mRYBbSym_VYaf_V4zWI
Log - Vulkan:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3160343/RPCS3.log.gz)
Log - OpenGL
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3160372/RPCS3.log.gz)
TTY Screenshot - OpenGL (Same with Vulkan)
![image](https://user-images.githubusercontent.com/41058180/57427584-b7e89780-724e-11e9-8ac5-6373a6522e5f.png)
TTY Log - OpenGL
[TTY.log](https://github.com/RPCS3/rpcs3/files/3160374/TTY.log)

**Comment by elad335** [comment]
from a first glance thats not a graphicsl issue, the game hangs.

**Comment by QuaiGoner** [comment]
> from a first glance thats not a graphicsl issue, the game hangs.

It hangs after RSX Capture, if not making it, it can be played if you can say so

**Comment by elad335** [comment]
Wow, looks like zcull needs an accuracy setting, it will be a bit slower, but more accurate.

**Comment by kd-11** [comment]
Will also break resolution scaling if you actually try to sample count. And dividing by the square of scale is not actually correct either.

**Comment by QuaiGoner** [comment]
Maybe you can rename that issue too, kd? So ot would be show whats the problem

**Comment by kd-11** [comment]
After talking it over with elad, it seems the issue was neither sample counting (as I interpreted) and not the report timing as elad speculated. We're having issues with possibly memory address translations, so we have no concise diagnosis at this time. I'll update the title once we know more.

**Comment by QuaiGoner** [comment]
There is some graphics on Zombies Map - FIVE
Log - Vulkan
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3180756/RPCS3.log.gz)
RSX Capture - Vulkan
https://mega.nz/#!6rhSjQiQ!1KQHvKIZH2oXOU8K6HfgzNh7gXxC64iX4CfeB-UeZhI

**Comment by QuaiGoner** [comment]
I dont know how useful this information is but anyway:
So BO1 uses the same engine as World at War (which shows graphics now) with ,according to Wiki, BO1 engine has an addition of 
1. "Texture streaming technology"
2. "Deferred Rendering" - https://web.archive.org/web/20140726112404/http://www.altdev.co/2011/01/18/forward-vs-deferred-rendering-whywhen-forward-rendering-still-matters/
As MW3 engine goes further with Texture streaming and it works now i can guess that Deferred Rendering/Lightning is why we dont see anything on the screen maybe?
More info on Def. Rendering
http://c0de517e.blogspot.com/2011/01/mythbuster-deferred-rendering.html
http://c0de517e.blogspot.com/2016/08/the-real-time-rendering-continuum.html
http://c0de517e.blogspot.com/2016/08/a-retrospective-on-call-of-duty.html
More on CoD BO engine:
https://www.unknowncheats.me/wiki/Call_of_Duty:_Black_Ops

**Comment by kd-11** [comment]
Deferred rendering has worked properly on rpcs3 for many years, since around 2015/2016.
The issue here is already identified (broken vram copy), just wait for a proper non-hacky fix.

**Comment by QuaiGoner** [comment]
Regressed after recent PR - doesnt go in menu/ingame
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3190084/RPCS3.log.gz)

**Comment by QuaiGoner** [comment]
Fixed by #6376. Thank you. Will close the issue when it will be merged and confirmed to work on master
