### ISSUE TITLE
MEM: Access violation writing location 0x0 (Ashes Cricket 2009)

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5948]
this one i self-dumped the game 

![mmm1](https://user-images.githubusercontent.com/45731484/57563655-231c9180-7355-11e9-9f9f-471048afc1c7.png)

sometimes it shows 

`
·! 0:00:44.011563 {PPU[0x1000000] Thread (main_thread) [0x0025d544]} sys_tty: sys_tty_write(ch=1, buf=*0x31ea67e0, len=26, pwritelen=*0xd007f3b0)
·F 0:00:44.011638 {PPU[0x1000000] Thread (main_thread) [0x002743d4]} MEM: Access violation writing location 0x0
·W 0:00:44.011739 {cellAudio Thread} cellAudio: Audio backend stopped unexpectedly, likely due to a buffer underrun
`

or

`
·W 0:00:17.345540 {PPU[0x1000000] Thread (main_thread) [0x00ba4268]} sys_event: sys_event_port_disconnect(eport_id=0xe00ce00)
·W 0:00:17.345547 {PPU[0x1000000] Thread (main_thread) [0x00ba4300]} sys_event: sys_event_port_destroy(eport_id=0xe00ce00)
·! 0:00:20.841155 Stopping emulator...

`

log file 

[RPCS3 LOG.zip](https://github.com/RPCS3/rpcs3/files/3168510/RPCS3.LOG.zip)

[RPCS3 log 2 .log.gz](https://github.com/RPCS3/rpcs3/files/3168512/RPCS3.log.2.log.gz)

TTY

`exception: bad allocation
`

i hope to play this game for long time i hope to see any fix's for it

**Comment by AniLeo** [comment]
Needs triaging, just shows a regular access violation on 0x0

**Comment by uaqlover** [comment]
anyway to debug properly ?

to know what is the issue

**Comment by uaqlover** [comment]
with RPCS3 v0.0.7-9228-e380a8c2 Alpha it show this 

![785555](https://user-images.githubusercontent.com/45731484/71062091-8a39ca00-211e-11ea-9a7b-00c9d77d57ed.png)

**Comment by elad335** [comment]
Upload log with cellVdec logging set to trace.

**Comment by uaqlover** [comment]
here @elad335 

[RPCS3 Ashes Cricket 2009 2.zip](https://github.com/RPCS3/rpcs3/files/3988204/RPCS3.Ashes.Cricket.2009.2.zip)

or this one 

[RPCS3 Ashes Cricket 2009.log.gz](https://github.com/RPCS3/rpcs3/files/3988205/RPCS3.Ashes.Cricket.2009.log.gz)

**Comment by elad335** [comment]
You should set 
```
Log:
  { cellVdec: "Trace" }
```
In config.yml, originally this setting looks like 
```
Log:
  {}
```

**Comment by elad335** [comment]
Also try in advanced tab, firmware settings : load liblv2.sprx + manual selection, select `libvdec.sprx`.

**Comment by uaqlover** [comment]
liblv2.sprx + manual selection, select libvdec.sprx

fix the game thanks a lot for the your help it been long time since i wanted it to play this game

![FPS_ 121 85 _ OpenGL _ 0 0 7-9235 _ Ashes Cricket 2009  BLES00639  12_20_2019 4_25_09 AM](https://user-images.githubusercontent.com/45731484/71254986-81452600-22e1-11ea-81b8-c70de5be13b6.png)

![FPS_ 51 55 _ OpenGL _ 0 0 7-9235 _ Ashes Cricket 2009  BLES00639  12_20_2019 4_28_21 AM](https://user-images.githubusercontent.com/45731484/71254991-85714380-22e1-11ea-92bf-83980d801631.png)


anyway here is the log file with the Trace

[RPCS3 2009 with Trace.log.gz](https://github.com/RPCS3/rpcs3/files/3988273/RPCS3.2009.with.Trace.log.gz)


same solution for https://github.com/RPCS3/rpcs3/issues/5845 

![FPS_ 59 92 _ Vulkan _ 0 0 7-9236 _ The Smurfs™ 2  BLES01797  12_20_2019 4_36_51 AM](https://user-images.githubusercontent.com/45731484/71255347-83f44b00-22e2-11ea-89c1-61f636e78b97.png)

there is anyway to make it load automatically in settings for new users thanks again @elad335

**Comment by elad335** [comment]
ok, I also need a log with libvdec.sprx unselected.

**Comment by uaqlover** [comment]
here 

[RPCS3 with Trace unselected.zip](https://github.com/RPCS3/rpcs3/files/3988331/RPCS3.with.Trace.unselected.zip)

**Comment by elad335** [comment]
Try with this build, cellVdec set to trace, libvde.sprx not selected, and upload log.
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/3988766/rpcs3.zip)

**Comment by uaqlover** [comment]
still same 

![7557](https://user-images.githubusercontent.com/45731484/71300271-e29fe000-2347-11ea-9bef-9e240da7e9c3.png)


[RPCS3 with Trace unselected 2.zip](https://github.com/RPCS3/rpcs3/files/3990834/RPCS3.with.Trace.unselected.2.zip)

**Comment by elad335** [comment]
Good chances are that it's fixed with #7366

**Comment by digitaldude555** [comment]
Its fixed.

**Comment by elad335** [comment]
I assume it's still fixed?

**Comment by digitaldude555** [comment]
ye
