### ISSUE TITLE
Regression: PR5923 Mega mode broken

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#5950]
Starting any game in Mega mode gives me this
![32](https://user-images.githubusercontent.com/7060586/57570776-74d52280-740e-11e9-9a3d-bb179091ab14.jpg)
The games refuses to pick my old cache even on Safe mode, tried to make new safe cache in Heavy Rain and it crashed on second run

**Comment by Nekotekina** [comment]
Upload SPU cache file (dat) please.

**Comment by Xcedf** [comment]
I'll upload but a bit later, i see in your newest PIC PR speed regression and i think it's up to giga PR, there're are few pushes in your Giga and it seems earlier ones works fine, want to know which one broke things

**Comment by Xcedf** [comment]
Confirmed my warnes about Giga PR slowdown
Giga PR (had to wait a few minutes on Safe mode until it stops gain cache ~47k) new SPU PIC pr has same speed
![30](https://user-images.githubusercontent.com/7060586/57572070-9938fb00-741e-11e9-96a6-447d09a8b1ac.jpg)
Older build:
![31](https://user-images.githubusercontent.com/7060586/57572075-a2c26300-741e-11e9-85ff-cc55bc2bed16.jpg)
RDR
Giga (used SPU PIC for this one, can't wait for 100+k compiles on normal build)
![33](https://user-images.githubusercontent.com/7060586/57572228-1153f080-7420-11e9-980a-01e8164136fa.jpg)
Older build:
![34](https://user-images.githubusercontent.com/7060586/57572232-187afe80-7420-11e9-8f3b-76785f558ad4.jpg)
and here's the caches
[Heavy Rain.gz](https://github.com/RPCS3/rpcs3/files/3169247/Heavy.Rain.gz)
[RDR.gz](https://github.com/RPCS3/rpcs3/files/3169251/RDR.gz)

**Comment by Nekotekina** [comment]
@Xcedf try new commit in PIC PR after it builds.

**Comment by Xcedf** [comment]
Tried new commit, it's faster in RDR but same speed in Heavy Rain
