### ISSUE TITLE
Improve Vulkan checks on Windows

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#5953]
Right now RPCS3 doesn't handle errors related to Vulkan detection very well and ends up either showing a badly worded error dialog or freezing completely. To fix this, I got a couple of suggestions. I don't know much about C++, RSX code or dynamic linking on Windows so I've no idea how feasible any of these would be to implement, but they'd definitely help with the end user experience.

1. If Vulkan runtime cannot be found, the default error message informs that `vulkan-1.dll` is missing. This is bad, as it causes some people to download the missing dll file from internet instead of sorting out their drivers or installing Vulkan RT properly. The error message should be reworded to suggest better solutions and hide the actual dll from end users.

2. ~~When Vulkan RT is found, the emulator will query it for vulkan-compatible devices next. This can cause the emulator to freeze while f.ex. some badly programmed driver is waiting for a device to be connected. Thus, the Vulkan check should have a timeout attached to it, so that the emulator could at least show some kind of error message when the timeout expires and not just freeze in background.~~ Implemented in #6138

3. Since vulkan isn't actually required to run this emulator, would it be possible to add a "continue" option that would disable Vulkan and allow users to run the emulator with just OpenGL? This is probably difficult as you'd have to ensure emulator won't try to access anything vulkan-related, and any GPU that doesn't have any kind Vulkan support is likely not going to run the emulator anyways. But still, it'd be nice to have some kind of way to get the emulator to work even if the end user can't sort out his dll issues.

**Comment by AniLeo** [comment]
1 and 3: That's handled by Windows, not RPCS3. Dynamic library loading fails because the DLL can't be found.

**Comment by MSuih** [comment]
Coudn't you replace the automatic library loading with explict LoadLibrary calls though?

**Comment by AniLeo** [comment]
No

**Comment by kd-11** [comment]
@MSuih You can try delay-loading vulkan-1.dll instead if you wish to work on this. You'll then need to set up a startup routine to check if vulkan-1 is needed and make changes in other places to keep the setup/config code from creating a test vulkan instance, etc.

**Comment by nitroos-ai** [comment]
Is this still a problem?

**Comment by kd-11** [comment]
The reason this discussion was relevant was because vulkan runtime did not ship with drivers. It is a 3rd party component that has nothing to do with the graphics drivers themselves, but as time went on they did start shipping the runtime just to avoid the headache of users having to separately download and install the vulkan runtime library.
With that in mind I propose to close this unless there is a good reason to handle dll loading manually.
