### ISSUE TITLE
Regression in Red Dead Redemption

### ISSUE THREAD

**Issue by Dungeonseeker** [RPCS3/rpcs3#5954]
Red Dead Redemption now crashes after around 30 seconds of being in game with the error

F {RSX [0x01d21d4]} RSX: class std::runtime_error thrown: Unknown index array type 16
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gcm_enums.cpp:27)

This only happens in game, it will sit on the title screen indefinitely. 

Latest Build - v0.0.6-8091 Alpha [2019-05-11]
Ryzen 7 2700X
AMD Vega 64 - 19.04.3 Driver Version
Vulkan
1280x720
No other settings changed at all
BLUS30418 on V1.0

**Comment by elad335** [comment]
Not a regression, rdr was never stable.

**Comment by AniLeo** [comment]
Closing as there's no real regression, the game has always been unstable and RSX corruption has always happened

**Comment by avindra** [comment]
seems to go in game a bit longer w/ a recent build. good to know that it is considered to be unstable.
