### ISSUE TITLE
More options to use system libraries instead of 3rdparty [Linux packaging]

### ISSUE THREAD

**Issue by akien-mga** [RPCS3/rpcs3#5955]
I'm looking at packaging RPCS3 for my Linux distribution Mageia, and like many distributions we prefer to build software against system provided shared libraries whenever possible, instead of rebuilding them from bundled source code.

RPCS3 already provides options to build against the system libpng, zlib and ffmpeg, which works well.

There are more libraries which could be candidates for having such options too, namely:
- GSL
- hidapi
- libusb
- OpenAL
- pugixml
- xxHash
- yaml-cpp
- glslang
- llvm (already possible it seems, but enforces current dev branch 9.0 - is this an actual strong requirement, or could RPCS3 use system LLVM 8.0?)

I guess cereal and discord-rpc too, but I don't have those as system libraries on my distro yet.

I could provide PRs to add options for unbundling those, but as it would take some time I'd prefer to check with you if that's something that would be considered for merging. Or if only a subset of the above should be made unbundle-able, e.g. if others have custom changes or need a very specific version or build options.

**Comment by MSuih** [comment]
The llvm that RPCS3 uses is a [fork](https://github.com/RPCS3/llvm/commits/master) and has been customized to better fit the emulator. While it's possible to use system llvm it's not recommended.

**Comment by akien-mga** [comment]
Thanks, I've just seen that indeed (forcing `8.0` version in `llvm.cmake` allows configuring, but build fails ultimately due to missing APIs).

I'm a lot less interested in trying to make a distro package if it has to use a builtin LLVM fork, even though I fully understand why you would need this for the emulator's needs.
As such the incentive for unbundling the other libraries is lower, since I guess most distro packagers will frown when seeing the bundled LLVM and not attempt making a proper package that fits their distro policies.

Given that you have a good pipeline for automated AppImage builds of each commit (which works well AFAICT on my distro), I guess this can stay as is for now.

**Comment by sl1pkn07** [comment]
as libusb uses a official repo and is commonly provided by any distro (except BSDfoo, witch use a own implementation, i this cam be swaitch to use system libraries when detect linux

https://github.com/RPCS3/rpcs3/blob/3aa293a7a3a8521dca8f9ee078297054f8d1fc4a/3rdparty/CMakeLists.txt#L133-L144

greetings

**Comment by hcorion** [comment]
Superseded by #7961
