### ISSUE TITLE
Random Freeze Mortal Kombat Vs. DC

### ISSUE THREAD

**Issue by schubertguilherme** [RPCS3/rpcs3#5957]
Random Freeze in Mortal Kombat Vs. DC Universe

![gfhfghfghf](https://user-images.githubusercontent.com/36903073/57586669-a7931f80-74cf-11e9-9586-52d2b824af81.jpg)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3170456/RPCS3.zip)

Settings

Gigabyte 990X Gaming SLI
FX 8370 @ 4.7GHz
16GB DDR3
GTX 760 2GB
SSD Samsung 250 B840 EVO

**Comment by digitaldude555** [comment]
This game is now in playable section. close.
