### ISSUE TITLE
Error: no DISPLAY environment variable specified

### ISSUE THREAD

**Issue by snshn** [RPCS3/rpcs3#5959]
- RPCS3 Version
0.0.6-8066-9c346c92
 - What I did
Started the .AppImage, tried to click on "Quickstart" link within the "Welcome to RPCS3" dialog window.
- Operating system
Ubuntu 18.04.2 LTS
- Last few log lines:
```
Error: no DISPLAY environment variable specified
Error: no DISPLAY environment variable specified
Error: no DISPLAY environment variable specified
```
- General result
Web browser doesn't get opened

**Comment by AniLeo** [comment]
Reproduced on same SO and rpcs3-v0.0.6-8094-22f61caf_linux64.AppImage

**Comment by Megamouse** [comment]
can you guys click the patreon link in the "About" window ?

**Comment by Megamouse** [comment]
And how about "Check compatibility" in the game list?

**Comment by vflyson** [comment]
None of those blue links work for me, same error in the console.

`RPCS3: Fatal Error`'s window with "How-to-ask-for-Support" link, all the links in the "Welcome" dialog. I'm sorry, I can't seem to find a way to test "Check compatibility" within game list, don't really have any games, just interested in the UI and the software you're working on.

**Comment by drysalter** [comment]
Same here with rpcs3-v0.0.6-8094-22f61caf_linux64.AppImage.

**Comment by Leopard1907** [comment]
`rpcs3-v0.0.6-8094-22f61caf_linux64.AppImage`

Linux Mint 19.1 ( Ubuntu 18.04 based )

Behaviour: Installing game updates then exiting from emulator triggers that behaviour. Result is ; update didn't applied ( at least according to GUI ) at all.

Behaviour: Dowloading compability database also triggers same behaviour. In both cases ; segfault message is only visible when exiting emulator.

![segfault](https://user-images.githubusercontent.com/24878978/57631827-e648d880-75a8-11e9-90c2-cec5faff54c7.png)

**Comment by Megamouse** [comment]
No one tested the "Check compatibility" for a game yet

**Comment by Leopard1907** [comment]
"Check game compatibility" works without problems for me.

Same goes for links at " About Rpcs3 " section.

Things doesn't work ( but no segfaults ) : 

1-) Open install folder
2-) Open custom config folder

There is zero response but there are no errors either.

**Comment by z0z0z** [comment]
Are you guys running in Wayland?

It would explain DISPLAY not being set, and Qt having problems choosing a browser to open in.

**Comment by vflyson** [comment]
Not me, just plain default installation of Ubuntu Desktop x86_64 18.04.2 LTS + latest updates which uses gnome-shell under Xorg.

According to https://www.omgubuntu.co.uk/2018/01/xorg-will-default-display-server-ubuntu-18-04-lts it's no longer a thing on Ubuntu.

**Comment by JohnHolmesII** [comment]
That is only about default; someone could still be using wayland if they choose to.
More relevant, I just tried the check game compat and got the same error.

**Comment by drysalter** [comment]
Xorg here as well.
