### ISSUE TITLE
Re-enable Travis GCC builds

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#5962]
CI GCC builds were previously disabled to speed-up compile times on travis: https://github.com/RPCS3/rpcs3/blob/master/.travis.yml#L4

However, saved time didn't end up being that much, just a couple of minutes, it's not worth the trade off. Specially that we now have warnings enabled and people interested in fixing them, it's good having the CI turned on so people can fix those while still in PR stage.

**Comment by JohnHolmesII** [comment]
I think I'm gonna disagree with this one. I re-enabled gcc locally and it takes 20:15 mins compared to clang's 3:30 mins. That's a huge delay if lots of people are pushing to PRs. Iteration time is awful.

You say "it's not worth the trade off". Could you detail what the trade off is exactly? What really is lost?

**Comment by AniLeo** [comment]
GCC took ~15 min vs ~6 min Clang on the last build where both were enabled on travis-ci/push

We're not pushing that many builds where 9 min is worth saving versus having CI of GCC showing warnings and possible errors caused by the changes where it builds on one compiler but not the other

And even if we had such a giant afluent of PR commits being pushed triggering builds, what's the reason to not have GCC building master commits?

**Comment by elad335** [comment]
It affects minimum pr merging time, TBH.

**Comment by AniLeo** [comment]
I disagree, AppVeyor check also has to pass before a PR can be merged and AppVeyor takes ~15 min to build as well

**Comment by AniLeo** [comment]
Solved via #7525
