### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by JohnHolmesII** [RPCS3/rpcs3#5966]
Travis is merging the two websites into the .com domain. They are no longer separate. This looks like it needs to be handled by project devs.

Instructions:
https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg

**Comment by AniLeo** [comment]
Seems like it's still a closed beta test thing, doesn't seem like something that needs to be done ASAP. They should provide more instructions after the closed beta.

**Comment by Megamouse** [comment]
Is this still a thing?

**Comment by JohnHolmesII** [comment]
It is in the sense that it still needs to happen. It would take all of 10 minutes though, don't know if people can be bothered.

**Comment by AniLeo** [comment]
Migrated, closing as solved
