### ISSUE TITLE
Far Cry Classic [NPUB30737]: Freezes after entering ship hull

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#5968]
After playing the game for 10-15 minutes, in the final section of the first mission (the training mission), you steer a small boat towards a large ship in the water (the save game below will take you straight to this area).  You are looking for a hole in the left side of the side of the ship, which is half underwater (easiest to drive around the right side of the ship, then back to the left side and in the hole).  Once you enter the hole, the screen turns black and "freezes" (the fps counter in the titlebar continues to deviate from e.g. 58.2fps to 58.8fps etc., so the game doesn't entirely freeze).  Can provide a trace if needed.

YouTube links:

* RPCS3 showing freezing problem: [Video](https://youtu.be/YXnb3TgFs8s?t=932)
* PS3 showing "Mission Complete": [Video](https://youtu.be/GucdQuUH4m4?list=PLyex3XU-d_c_Z40dc6TwzSYPIU_s7IbfS&t=741)
 
Latest testing information:
* OS: Linux Mint 20.2 / kernel 5.11
* CPU: Intel i7-10870H
* GPU: Nvidia gtx 3070 / driver 470.57
* Commit: f0ab4b51dc6bdc3d339a5a368d17987f5ad411dc
* Save file: [farcry_classic_save.zip](https://github.com/RPCS3/rpcs3/files/7079521/farcry_classic_save.zip)

**Comment by RainbowCookie32** [comment]
You should always provide a log when opening an issue from a run where you reproduce the issue, it might have something useful for devs.

**Comment by Shoegzer** [comment]
I always do, I just give a day or so just in case this is a known issue and no need to generate logs.  I also wasn't near the system when I wrote that.

That said, RPCS3 does not appear to be generating logs.  I deleted my old rpcs3.log and rpcs3.log.7z files from ~/.cache/rpcs3 but when I exit the game I don't see replacement log files.

**Comment by Shoegzer** [comment]
Update: deleted game saves and restested after https://github.com/RPCS3/rpcs3/pull/6393 was merged, hoping this would have fixed it but still seeing the same results.  @RipleyTom any thoughts on this one?  The game itself is buggy/flaky at save points even on a real PS3 but of course not to this degree.

**Comment by digitaldude555** [comment]
update? @Shoegzer

**Comment by Shoegzer** [comment]
Tested against 0.0.8-9562 with same results, unfortunately.

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by Shoegzer** [comment]
@digitaldude555 Is that a question?  If so, then yes it's still an issue.  This game has never been fully playable as far back as I've been testing updates.

**Comment by digitaldude555** [comment]
No it wasnt a question.

**Comment by Shoegzer** [comment]
Thanks, I ask because you've wondered about an update from me before. Good to know you're seeing it too at least.  

This game is known to be pretty buggy (and to my knowledge was never patched), so it may be exposing some rare PS3 hardware behavior the emulator doesn't yet know how to handle.

**Comment by Shoegzer** [comment]
Update: Still freezes at the end of the training mission upon entering boat, as of commit 546b52200b7c0d00edbc22d55a7b4bb1b9497f94.  I found a YT video online showing the problem, which I've added to the issue summary along with a video of a real PS3 without the problem, for comparison.

**Comment by Shoegzer** [comment]
Update: Issue still occurs as of commit a06a93d5baf39aa7505c727b6d4f530fd06826f3.  I was hoping #10611 might have resolved this but to no avail, then I noticed this gets logged immediately after it freezes:

`E SYS: 'cellAudioRemoveNotifyEventQueue' failed with 0x80310709 : CELL_AUDIO_ERROR_TRANS_EVENT [1]
`

So perhaps something to do with audio but seems unlikely.  Also, the last item logged is the following - and the last value on this line increases even after the "freeze" so I suppose rpcs3 doesn't actually freeze even though all that is shown is a black screen:

`E RSX: Transfer cropped in Y, src_h=720, offset_y=1, block_h=720 x6407`

**Comment by Shoegzer** [comment]
Update: Freezing still occurs as of commit f0ab4b51dc6bdc3d339a5a368d17987f5ad411dc.  I updated the issue with the latest testing information and added a save file in case it helps debugging. 

Also, this game is NPUB30737, however I noticed that RPCS3 prefixes its game saves with NPEB00989 (the EU version of the same game) for some reason.  Not sure if that factors in here but I've never seen that behavior before.  @elad335 or @Megamouse thanks for any thoughts you may have.

**Comment by Shoegzer** [comment]
Update: This still occurs as of the merged #11846 which resolves other seemingly similar issues related to save files.

Updated test information:
     
* OS: Linux Mint 20.3 / kernel 5.13
* GPU: Nvidia gtx 3070 / driver 510.60

**Comment by Shoegzer** [comment]
Update: Issue still occurs as of eb4131e1c799e08356d4c9e4fdc25a7c43cc574a.

Test system is now Linux Mint 21 (Ubuntu 22.04 base) with kernel 5.15, but same hardware.

I should probably clarify something posted earlier: the final line of the running log shows a monotonically increasing integer value that would not be reflected in an uploaded text-based log:
 
`E SYS: 'cellAudioRemoveNotifyEventQueue' failed with 0x80310709 : CELL_AUDIO_ERROR_TRANS_EVENT [1]
E RSX: Transfer cropped in Y, src_h=720, offset_y=1, block_h=720`
`x2448` <--- This value rapidly increases even though game seems to have hung on black screen

In testing, I let it increase for about ten minutes (up to about 150k) before stopping the emulation.  Not sure what the value is related to (a failed attempt to load assets?) but hopefully it's helpful information.

**Comment by marcoluc97** [comment]
@elad335 #12625 can help here?

**Comment by Darkhost1999** [comment]
Someone commented the issue is still present for this issue. 
https://github.com/RPCS3/rpcs3/issues/2526#issuecomment-1241059376

**Comment by Shoegzer** [comment]
Tested this title against #13492 since it was merged to master, though no change unfortunately.

**Comment by Shoegzer** [comment]
Yeah, see my comment above about that.  It seems to suggest something wrong with an audio event but then again, it only occurrs when entering the ship's hull, which completes the training mission and I believe triggers an auto-game save.  This gave some hope the big save-related fix introduced in #13492 might have resolved it, as it fixed so many other issues.

**Comment by elad335** [comment]
![image](https://user-images.githubusercontent.com/18193363/224482378-2f07440a-7bd9-4ad5-b263-7c8f0e51bc7a.png)

**Comment by elad335** [comment]
Test with #13531

**Comment by FlexBy420** [comment]
Finally can finish the mission, will be testing later if the game is fully playable
![obraz](https://user-images.githubusercontent.com/68403300/224494078-c1e6f212-5d13-4fad-b414-4646e6fe6761.png)

**Comment by Shoegzer** [comment]
I too have tested and confirmed it's possible to pass the training mission with PR #13531, as it apparently breaks out of a non-zero loop.  I'll close when this is merged to master unless someone gets there first.

A long-standing issue is resolved thanks to @elad335.
