### ISSUE TITLE
Tekken 6: Models glitching on Vulkan

### ISSUE THREAD

**Issue by ZxSol** [RPCS3/rpcs3#5969]
RPCS3 Version:0.0.6-80890-8194c92f

What I did:Tried playing both normal arcade, practice, and scenario campaign modes with Vulkan, tried all different GPU settings with it resulting in no changes to the problem

Operating System:Windows 10

System specs: 
Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
NVIDIA GTX 1060 3GB
8GB RAM

General Result this:
![GLITCH](https://user-images.githubusercontent.com/50655701/57759106-3918b200-76c7-11e9-947f-dccda0cb30c8.png)
character and stage background models distort and explode
also a short video demonstrating this, this also occurs during Scenario Campaign and on the character select, with Scenario Campaign almost being near unplayable past the first stage https://www.youtube.com/watch?v=_iW0ZFN7D2E

I also have a log file and a RSX capture
[BLUS30359_20190515035448_capture.zip](https://github.com/RPCS3/rpcs3/files/3181564/BLUS30359_20190515035448_capture.zip)

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/3181562/RPCS3.log.zip)

**Comment by 13xforever** [comment]
You should add a comparison screenshot with expected visuals

**Comment by raveskirza** [comment]
It is because your FPS goes below 60 in Vulkan. You will not have exploding vertices if your system can maintain the 60 FPS.
Switch off the motion blur to alleviate the exploding vertices. It is under Options--> Other Options

![image](https://user-images.githubusercontent.com/28158623/57799772-746dbc00-776d-11e9-9f87-dec1bbb93aa3.png)

**Comment by Kravickas** [comment]
I dont know if that issue is fixed or it changed to this, but in earlier versions of emu i was fixing broken animation model with 59.94Hz frame limiter.

**Comment by proganime1200** [comment]
I have the same problem vertices explode massive performance hit

**Comment by abosma** [comment]
What @Kravickas said is right, putting the frame limiter on 59.94hz fixes the crazy glitching.

**Comment by kd-11** [comment]
Closing due to multiple reports of fixing the problem with settings.

**Comment by proganime1200** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4092779/RPCS3.log)
Still getting exploding vertices and model glitching in the latest build  #7300

**Comment by AniLeo** [comment]
Removed comment containing log from a pirated game.

**Comment by Danhanado** [comment]
The game still has this issue and there doesn't seem to be a 59.94hz setting for the frame limiter anymore

**Comment by 13xforever** [comment]
There's PS3 Native

**Comment by Darkhost1999** [comment]
> The game still has this issue and there doesn't seem to be a 59.94hz setting for the frame limiter anymore

There's also NTSC fixup next to vblank frequency in the advanced tab that should help.
