### ISSUE TITLE
Feature request: Analog stick “range” (sensitivity) setting OR in-emulator analog stick range tracing

### ISSUE THREAD

**Issue by MisakaMikotoDolphin** [RPCS3/rpcs3#5971]
**SHORT VERSION**

For controllers that have **Nintendo-style octagonal (”notched”) analog stick gates**, RPCS3 expects the stick’s full range of movement to be larger than it is. As a result, when using these controllers (such as the GameCube controller or the Classic Controller Pro), full stick extension (such as is used to run in Ni no Kuni) is impossible in any direction but the 8 orthogonal/diagonal directions (so that full stick extension in anything but those 8 exact directions produces only a walk).

**LONG VERSION**

This issue doesn’t relate to any particular game. Rather, it has to do with notched analog stick gates such as are common on Nintendo controllers (such as the GameCube controller and the Classic Controller Pro).

These controllers have an octagonal analog stick gate, with the notches (representing the farthest point the stick can reach) at the 8 orthogonal/diagonal directions. When moving the stick along the straight edge between two such notches, it is thus not as far from center as if it were pushed into a notch.

![image](https://user-images.githubusercontent.com/13497669/57794907-5c188580-770a-11e9-9cb1-62154a30c51d.png)

As a result, the analog sticks on notched-gate controllers are not able, through most of their rotation, to reach their apogee. The practical upshot of this is that in, for example, Ni no Kuni, Oliver runs when the stick is in a notch but walks when the stick is along a straight edge of the octagonal gate.

Cemu and Dolphin (both of which emulate Nintendo consoles and thus encountered this issue early on) account for this issue in two different ways. (To my mind, Dolphin does it better, but either could work.)

Cemu has simply added a “Range” setting that acts as a multiplier: at a setting of, say, 110%, when the stick is at 50% of its max range, the emulator considers it to be at 55% of its max range—and so forth.

![image](https://user-images.githubusercontent.com/13497669/57794646-b82eda00-7709-11e9-99fd-33d9d226379e.png)

Dolphin has (just recently) added the ability to “calibrate” analog sticks in the input mapping dialog, so that the emulator gets an exact picture of the stick’s full range and can compensate accordingly—that is, can adjust range multipliers on the fly to get full-circle movement out of any given controller’s approximation of a true circle.

![image](https://user-images.githubusercontent.com/13497669/57794636-b49b5300-7709-11e9-9133-5b4721ef2009.png)

Cemu’s method is quick and dirty, whereas Dolphin’s is more precise; but either would work.

Giving users the ability to multiply the perceived range of their controller’s analog stick (or to “calibrate” in emulator, inputting the exact range of that particular controller’s stick) would be very, very helpful to those of us who use Nintendo-style notched-gate controllers.

**Comment by Megamouse** [comment]
Maybe I can try to add a multiplier and in consequence even try to adapt dolphin's version

**Comment by vsub** [comment]
Hmm,I have a similar problem with my gamepad in wireless mode.
In Persona 5 it is really difficult to make the character run,he is almost always walking instead of running when I move the analog to some diagonal direction

Having a multiplier will be nice

PS.It is fine if I use the gamepad in wired mode

**Comment by MisakaMikotoDolphin** [comment]
I’m not a contributor, so I can hardly nag anyone else to work on this, either; but I thought I’d check in to see whether there’s been any progress, even behind the scenes, toward possibly implementing this feature so that Nintendo-style gated controllers can be used in RPCS3 without walking at half the joystick positions.

**Comment by vsub** [comment]
This was done(if I understand your post correctly)long time ago but the option is ini only.

Go to Input\Your preferred input mode\ and open Default Profile.yml with your text editor
Change
Left Stick Multiplier: - mine is on 130 and fixes the problem I have with Persona 5
Right Stick Multiplier:

**Comment by MisakaMikotoDolphin** [comment]
Ah! Thanks so much. I kept looking for it in the UI and didn’t realize it had been done in INI instead.

I can confirm—using a value of 125 fixes this problem when using the Wii Classic Controller. I can now play Ni no Kuni without walking half the time. Thanks for the heads-up!

**Comment by Megamouse** [comment]
Let me know if #8553 works for you

**Comment by Megamouse** [comment]
Closing as assumed fixed
