### ISSUE TITLE
RPCS3 v0.0.6-8105-3753d27a - LittleBigPlanet 3 [BCUS98362]: Unimplemented syscall syscall_253

### ISSUE THREAD

**Issue by theclashingfritz** [RPCS3/rpcs3#5974]
To reproduce the issue just start the game on latest commit, It'll just up and close leaving with you with this error in the log.

Specs: Windows 10 1803 Intel Core i7-7700 | 8 Threads | 15.94 GiB RAM | AVX+ | TSX GPU: GeForce GTX 1060 3GB (430.64)

Firmware: 4.84

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3184985/RPCS3.log.gz)

**Comment by theclashingfritz** [comment]
Fixed as of latest?

**Comment by isJuhn** [comment]
the syscall was never an issue, it was a spu regression from #5944 fixed in #5967

**Comment by AniLeo** [comment]
This wasn't implemented in any recent commit... what?
