### ISSUE TITLE
NASCAR 2011 and Inside Line regression

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5981]
NASCAR The Game 2011 and

![FPS_ 30 01 _ Vulkan _ 0 0 6-8134 _ NASCAR The Game 2011  BLUS30604  16_05_2019 9_15_54 PM](https://user-images.githubusercontent.com/45731484/57902889-5f9e3080-7820-11e9-8f77-e374d6e4e11c.png)

NASCAR The Game: Inside Line psn only disc works fine 

![FPS_ 30 01 _ Vulkan _ 0 0 6-8134 _ NASCAR The Game_ Inside Line  NPEB01256  16_05_2019 9_22_00 PM](https://user-images.githubusercontent.com/45731484/57902961-b0ae2480-7820-11e9-9b92-0f689ce6e7a1.png)

**Comment by jacob1218** [comment]
Likely affects NASCAR 14 and 15 as well: those games use the same engine.

**Comment by uaqlover** [comment]
@jacob1218 No all works fine 

NASCAR The Game: Inside Line [BLUS30932]

![FPS_ 30 01 _ Vulkan _ 0 0 6-8134 _ NASCAR The Game_ Inside Line  BLUS30932  16_05_2019 9_33_08 PM](https://user-images.githubusercontent.com/45731484/57903296-40080780-7822-11e9-8a70-b4fa5face6cd.png)

NASCAR '14 [BLUS31378]

![FPS_ 30 01 _ Vulkan _ 0 0 6-8134 _ NASCAR '14  BLUS31378  16_05_2019 7_20_49 PM](https://user-images.githubusercontent.com/45731484/57903309-4bf3c980-7822-11e9-9623-9b10cbb07f30.png)

NASCAR '15 [BLUS31560]
![FPS_ 30 01 _ Vulkan _ 0 0 6-8134 _ NASCAR '15  BLUS31560  16_05_2019 7_44_21 PM](https://user-images.githubusercontent.com/45731484/57903321-56ae5e80-7822-11e9-8634-4b18ef7f5cc8.png)

**Comment by jacob1218** [comment]
Weird how the disc versions work fine.

**Comment by uaqlover** [comment]
@jacob1218 yeah if you have the game can you test it maybe something wrong with my setup 
if you have amd card will be better because my is nvidia mayabe issue with card not sure

**Comment by AniLeo** [comment]
Regression from what build?

Missing log files and RSX Captures for the regressed scenes too

**Comment by kd-11** [comment]
This game is known to work correctly or wrongly at random; it has always been this way.
