### ISSUE TITLE
VK: black screen in Chariot[NPUB31538]

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#5984]
Chariot game has improvements after #5937. But it works only using OpenGL.
I captured rdc file for Vulkan and logs are provided.
[RenderDoc Capture](https://drive.google.com/open?id=17FxkP1EM1IJywi1z-8VRYYrCpaScx0ER)
[RPCS3-Chariot-OpenGL.log.gz](https://github.com/RPCS3/rpcs3/files/3192041/RPCS3-Chariot-OpenGL.log.gz)
[RPCS3-Chariot-Vulkan.log.gz](https://github.com/RPCS3/rpcs3/files/3192042/RPCS3-Chariot-Vulkan.log.gz)

[2 rrc files, OpenGL and Vulkan](https://drive.google.com/open?id=1kJJxI3Qnb3JdsGY26oX-EeKs0SSZCHpK)

**Comment by kd-11** [comment]
I think RSX capture would be more beneficial in this case.

**Comment by kd-11** [comment]
Or a comparison renderdoc with both OpenGL and Vulkan

**Comment by Realmantik** [comment]
I tried get a capture using OpenGL with various settings, but RPCS3 and RenderDoc hang without a result.

**Comment by Realmantik** [comment]
[2 rrc files, OpenGL and Vulkan](https://drive.google.com/open?id=1kJJxI3Qnb3JdsGY26oX-EeKs0SSZCHpK)

**Comment by AniLeo** [comment]
@kd-11 can you triage this one?

**Comment by kd-11** [comment]
I'll take a look soon.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/6164

**Comment by Realmantik** [comment]
It is working now with Vulkan.
