### ISSUE TITLE
Emulator dies after initial game video prior to main menu ~ compiled from Git with GCC 9.1.0

### ISSUE THREAD

**Issue by Valmar33** [RPCS3/rpcs3#5986]
As per the title, RPCS3 just dies after the initial pre-main menu video plays. It doesn't matter what my PPU / SPC Decoder settings are, nor Renderer choice, nor additional setttings. RPCS3 always simply dies.

Hardware:
CPU ~ AMD 2600X
GPU ~ AMD RX580

RPCS3 commit: 4037225e989ec798593d64e0ac1a1f887469d11e

System LLVM commit: https://github.com/llvm/llvm-project/commit/457d7caac82260adc5754d62f7133b178c7766be
Mesa commit: https://gitlab.freedesktop.org/mesa/mesa/commit/b6e2a9eca7e81342ac0c1aab21f037543e09736e

Log:
[RPCS3.tar.gz](https://github.com/RPCS3/rpcs3/files/3192288/RPCS3.tar.gz)

Coredump link:
https://mega.nz/#!2NlCEKzZ!872bFtGrbKOIcNjVCcFPdUO6DXmCzdgRuaOGVX7Ait8

Stack trace of thread 11607:
#0  0x00007fe0d289b573 n/a (n/a)

Rather useless. The coredump was truncated, due to being a massive 2GB, so I'm not sure if it helps.

**Comment by Valmar33** [comment]
If I need to provide anything else, let me know.

**Comment by AniLeo** [comment]
> System LLVM commit

RPCS3 uses a custom LLVM fork. Are you using AppImage or self built RPCS3? If it's self built, you need to build against the fork.

**Comment by Valmar33** [comment]
Is there any point posting the `RPCS3.buf` file? What about terminal output?

**Comment by Valmar33** [comment]
Self-built.

I'm using the rpcs3-git package from Arch AUR, which builds against said fork.

**Comment by Valmar33** [comment]
I'll try the AppImage, out of curiousity.

**Comment by AniLeo** [comment]
No need to ping 3 times in a row, use edit functionality

RPCS3.buf is not needed, all terminal output is present in the log file as well. You can post TTY.log if you want too.

**Comment by Valmar33** [comment]
AppImage works, interestingly. So, the issue lies elsewhere...

`CXXFLAGS="-march=native -O2 -pipe -fstack-protector-strong -fno-plt -ftree-vectorize -ftree-slp-vectorize"`

Ah. Also, I compiled RPCS3 with GCC 9.1.0.

**Comment by Valmar33** [comment]
@AniLeo How do you compile your AppImage? What GCC version?

I've compiled with

    cmake ../rpcs3 \
        -GNinja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX='/usr' \
        -DCMAKE_SKIP_RPATH='ON' \
        -DUSE_NATIVE_INSTRUCTIONS='OFF'

But it still crashes on me. GCC 9.1.0 might be the cause here.

**Comment by AniLeo** [comment]
Clang 6

**Comment by Valmar33** [comment]
Ah. Why Clang 6, anyways?

Hmmm. Could you try compiling with GCC 9.1.0 and/or Clang 8?

How many bug reports do you get from people who've compiled from Git, rather than just using the AppImage?

**Comment by AniLeo** [comment]
> How many bug reports do you get from people who've compiled from Git, rather than just using the AppImage? 

Nearly none

> Ah. Why Clang 6, anyways?

Because we still didn't update the docker to use xenial and Clang 8

> Hmmm. Could you try testing with GCC 9.1.0 and/or Clang 8? Not the AppImage, but for reproducing this bug.

I can't, maybe someone else can

**Comment by Whatcookie** [comment]
I'm still on GCC 8.3.0 so I can't test 9.1.0 yet, but last I tried clang 8 worked without issue if you take the commit from this pull request: https://github.com/RPCS3/rpcs3/pull/4989

Note that I didn't find any speed difference between clang 8 and the appimage. GCC is just a little faster than clang for me. 

Have you tried compiling without the pkgbuild yet?

**Comment by Whatcookie** [comment]
I saw that GCC 9 was in the testing repository for arch, so I downloaded it, and compiled rpcs3 with it.

Seems to work without issue for me.

**Comment by Valmar33** [comment]
Hmmmm. Maybe there was fix in RPCS3 master since then.

Guess I'll try again, now. :)

**Comment by Valmar33** [comment]
Still fails for me, even when compiling manually with the README instructions. :(

**Comment by Valmar33** [comment]
Still no luck... WTF is going wrong?

**Comment by Valmar33** [comment]
Turns out this bug is caused by https://bugs.kde.org/show_bug.cgi?id=401637

Discovered the fix here: https://github.com/RPCS3/rpcs3/issues/5324#issuecomment-443421886
