### ISSUE TITLE
[BLUS30069] freezes on load with SPU LLVM since build8116

### ISSUE THREAD

**Issue by Parthorisian** [RPCS3/rpcs3#5992]
<Using SPU LLVM(AsmJit - OK) for [BLUS30069] freezes on load since b8116 log 
[Conan_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3194331/ConanRPCS3.zip)
 b8105 - OK>

**Comment by Nekotekina** [comment]
Upload SPU cache dat file please.

**Comment by Parthorisian** [comment]
Hope this has been meaned spu-safe-v1-tane 
[spu-safe-v1-tane.zip](https://github.com/RPCS3/rpcs3/files/3194481/spu-safe-v1-tane.zip)

**Comment by legend800** [comment]
Try it a few more times. Game can load for me on today's build. The game freezing during load randomly has been around for about a year. Logged here:
https://github.com/RPCS3/rpcs3/issues/4856
You can close this issue.

**Comment by Parthorisian** [comment]
Not randomly. Every build(since b8116) process freezes or must be shutdown using win taskmanager ![pherr](https://user-images.githubusercontent.com/35437970/58026999-6084da00-7b20-11e9-95f5-9f97acf186ec.png)

**Comment by legend800** [comment]
Fine here. Download today's master and start completely clean. It should work, else they broken something specific to your hw which is unlikely.

**Comment by legend800** [comment]
This should be closed. Games loads fine on **_SPU LLVM_**

**Comment by Parthorisian** [comment]
Closed as fixed PR#6020
