### ISSUE TITLE
[regression] PR5988 causes a lot of stuttering in the game NiNoKuni

### ISSUE THREAD

**Issue by psennermann** [RPCS3/rpcs3#5996]
#5988 causes NiNoKuni (BLES01555) to stutter all over the place (FPS shown in the window bar are always 30-full speed, but visually the game is very choppy and keeps on stuttering)

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/3195630/RPCS3.log.zip)

**Comment by Ghostotakoi** [comment]
Have you try use mega or giga?? also try increase or decrease the spu threads

**Comment by psennermann** [comment]
Nothing changes...

**Comment by psennermann** [comment]
Also for reference the build that introduces the problem is  0.0.6-8147 (PR5988)

**Comment by kd-11** [comment]
Any other people affected by this specific bug? If its triggered by a specific hardware combination I'd like to know. Can you capture a screenshot of this issue with afterburner overlay? I'm interested in the frame persistence graph. Also enable the debug overlay with "high" details so we can see what is happening.

**Comment by psennermann** [comment]
I've installed MSI Afterburner 4.6.2 beta but in the list of graph (hardware monitor) there's no "frame persistance graph"...where do I find it or enable it?

**Comment by RainbowCookie32** [comment]
He probably means frametime

**Comment by psennermann** [comment]
I have tons of graphs but all related to hardware, I don't see any software graphs...

**Comment by psennermann** [comment]
Ok, I found it...it had to be manually enabled :-/

**Comment by psennermann** [comment]
![image](https://user-images.githubusercontent.com/6342467/58113574-1a9a4580-7bf6-11e9-92a4-025855a060bf.png)

**Comment by kd-11** [comment]
Check if current master (with https://github.com/RPCS3/rpcs3/pull/5995) resolves the issue.

**Comment by psennermann** [comment]
Yes it's fixed
thanks
