### ISSUE TITLE
Pad settings dialog window size changes 

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#5997]
- [x] 1. When we pressing "Filter noise" on disconnected pad, we're getting "Fatal Error: Unhandled Win32 exception" crash. The button itself is inactive only when we're choosing disconnected gamepads with dropdown list, but getting active when we next calling Configuration -> Pads dialog.

- [x] 2. The scrolling controls are missing in "Skyline" visual theme (both light and dark):
![Screenshot_2019-05-20_135352](https://user-images.githubusercontent.com/1223276/58017331-98802300-7b08-11e9-8ca9-f07c844acafa.png)

- [x] 3. Hints for Stick Interpolation and Mouse acceleration controls are missing, although I remember they were displayed into Description field before. Now Description field is fully stucked on Dualshock 3 info.

- [ ] 4. Window size changes when we're changing control type from keyboard to gamepads, or selecting from Player 1 with keyboard type to Player # with Null types.

**Comment by vsub** [comment]
1.Maybe I did not understand this very well but,the button is active on every handler(selecting disconnected gamepad or not)except on Null\keyboard(that's probably expected to be inactive there).
But yes,clicking on the button on inactive gamepad cases a fatal error(which means,the button must be disabled or the button to do nothing on inactive gamepads )

4.No change here.,I am using the default theme

**Comment by Megamouse** [comment]
I don't really understand why it's so important to have the dialog initialized in it's max size. Seems like a major nitpick to me

**Comment by Megamouse** [comment]
I can most likely fix all of these today btw. We'll see.

**Comment by Megamouse** [comment]
3. I don't think there ever was a description

**Comment by Megamouse** [comment]
I fixed 1. in #5978

**Comment by Megamouse** [comment]
4 should be fixed in #8571

**Comment by Megamouse** [comment]
3 should be implemented in #8581

**Comment by Megamouse** [comment]
2 is fixed in #8586

**Comment by Megamouse** [comment]
This issue now mostly depends on the length of the button labels.
So a workaround might be to shorten the longer ones.

**Comment by Megamouse** [comment]
Closing since the pad dialog is now fully resizeable
