### ISSUE TITLE
Strange problem with Persona 5 in certain condition

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#6000]
BLUS31604
Probably happens on any rpcs3 version or maybe on some 8\900 revs older version(I think I started playing the game while using 0.0.5-7161 or maybe older)
Lets say you move to a newer rev from an old one(it can be very old)and you decided to delete the shaders.

When I try to load this save with no shaders(you can also achieve this if you don't want to delete the shaders by enabling the "Disable On-Disk Shaders Cache),rpcs3 will load until you start hearing the rain and it will freeze there.

If you try to load the save again after part of the shaders are created from the first run,the save will load.
[NPUB31848-00--016--.zip](https://github.com/RPCS3/rpcs3/files/3203685/NPUB31848-00--016--.zip)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3203686/RPCS3.zip)

**Comment by kd-11** [comment]
Retest, certainly this isn't an issue I have encountered and given how often I have to run the emulator without shaders (in almost all games) it would have been noted already. Request to reopen if you can still reproduce and the freezing does not go away after about a minute.

**Comment by vsub** [comment]
Yes,just tried the latest version with no shaders and it worked  fine(tested it 3 times)
