### ISSUE TITLE
DS4 led color change bugs

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#6001]
- [ ] **Bug 1:**

When setting led color in `Pads`, if you e.g. fiddle with `Enable Vibration -> Switch` right after setting a new color, the color reverts on the controller to the previously set one, meaning there's some variable that's not being properly updated, or its update was not properly accounted for everywhere (data hazard).

The led color picker will remember the freshly set color though, and upon saving then reopening the `Pads` dialog, it will then set the led color properly.

- [ ] **Bug 2:**

The led color picker will only allow you to drop down to `#000014` for some reason (at least visually). You *can* set `#000000`, but upon reopening the color picker dialog it will say `#000014` was set, even though `#000000` is the one that's clearly & visibly set (the led is turned off on the controller).

Setting `#000001` does the same thing, except the led will switch to a super dim blue color, instead of off or grey. Not sure if that's the expected behaviour either, idk what the controller led is capable of otherwise displaying (should be very dim grey in reality).

**Software version:**

RPCS3 v0.0.6-8152-9a26c0ab Alpha (current master as of writing)

cc @Megamouse

**Comment by Megamouse** [comment]
Fix for bug 2: https://github.com/RPCS3/rpcs3/pull/5978
Btw: `#000001` is in fact a very dim blue. The ds4 led cannot display every color correctly though. That's to be expected (e.g. looks pink instead of white).

**Comment by dio-gh** [comment]
Can confirm, #5978 fixes both issues. Will close / closable after merging.
