### ISSUE TITLE
[Feature Request] Additional features to the custom DS4 led color picker

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#6002]
It would be nice if these were a thing:

* [ ] only activating custom color while RPCS3 is running an emulated application (read: game), and maybe have the controller led otherwise disabled (== #000000)
* [ ] resetting the controller color on RPCS3 exit
* [ ] having an option to reset the original color without having to nuke the entire pad config for the given profile
* [ ] auto-coloring the led per-game, based on the logo that each game has (e.g. by determining their dominant color w/ k-means clustering)

I'm also thinking about maybe switching to pulsating orange on spu module or shader compilation (after like 2 seconds of rpcs3 doing that), but meh, that's kinda far fetched i guess.

**Comment by dio-gh** [comment]
Actually, I've changed my mind, let's play [The Show Must Go On](https://www.youtube.com/watch?v=t99KH0TR-J4) while shader compiling.

**Comment by Megamouse** [comment]
I don't think auto coloring is a good idea. It defeats the whole purpose of having per player colors. And I can guarantee that some people won't like it.
Define the "original color". Afaik there is now way of knowing the current color based on the ds4 alone

**Comment by dio-gh** [comment]
Honestly, I didn't quite figure out per-player-colors was the idea behind it, it kinda makes lot more sense now :joy: Thought it was just a stylistic thing.

I also didn't know "the original color" is not a thing, what I do know is that resetting the entire pad config does restore it, so :woman_shrugging: See my issue #6001, it's actually kinda related to that.

**Comment by dio-gh** [comment]
Closing as dumb.
