### ISSUE TITLE
[Feature Request] Make it so all 4 players can log into users

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#6003]
This would fix many bugs in multiplayer games like Minecraft. For example, in Minecraft, only Player 1 has a name, and saving/loading gets really buggy when you try to use 4 players.

**Comment by dariocdj** [comment]
Please how to play Minecraft with two players???

**Comment by Megamouse** [comment]
closing in favor of #8472 , which is newer and more fleshed out
