### ISSUE TITLE
Black screen: Unhandled GL format: 0x8058

### ISSUE THREAD

**Issue by es20490446e** [RPCS3/rpcs3#6004]
F {RSX [0x0000000]} RSX: St13runtime_error thrown: Unhandled GL format 0x8058
(in file ../rpcs3/Emu/RSX/GL/GLHelpers.h:1651)

Game: Any in the compatible list
Emulator: rpcs3 0.0.6-8155
Firmware: 4.84
Renderer: OpenGL
Tested settings: Default, any other
Operating System: Manjaro Linux Stable
Graphics Card: Radeon HD5870
Driver: Mesa 19.0.4

**Comment by RainbowCookie32** [comment]
Attach a full log when opening an issue, it's under ~/.cache/rpcs3/ on Linux

**Comment by es20490446e** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3205607/RPCS3.log)

**Comment by kd-11** [comment]
This is a driver bug and has likely been resolved in newer mesa. On your system glGetTexLevelParameteriv is not returning the bit sizes for the color channels. Not our issue, should be reported to mesa if its still present in 19.2.

**Comment by AniLeo** [comment]
Removed log showing pirated game and closing the issue.

**Comment by es20490446e** [comment]
@AniLeo Not piracy intended. The first game I tested, Scott Pilgrim, is unlisted. I actually tried it on the emulator before uploading it to the Internet Archive, to make sure the archive has no defects.

Archiving software that couldn't be used otherwise, due to been the running platform no longer available, is an exception to the copyright. It's legal, since the main intention is the software not to be lost.

I downloaded the second game I tried just to check out that the bug will happen with any title. My intention wasn't to play it.

**Comment by AniLeo** [comment]
Just because it works, it doesn't mean it's an untouched copy. You need to checksum it. 

Your log clearly shows it's a pirated game, we obviously don't want logs here that scream piracy when you open it.

**Comment by es20490446e** [comment]
* [Bug report on Mesa](https://bugs.freedesktop.org/show_bug.cgi?id=110724)

**Comment by es20490446e** [comment]
We now know the cause. Reported at:
https://github.com/RPCS3/rpcs3/issues/6007
