### ISSUE TITLE
Silent Hill Downpour [BLUS30565] Screen Rendering

### ISSUE THREAD

**Issue by alexsilva** [RPCS3/rpcs3#6005]
RPCS3 v0.0.6-8155-370b9e19 Alpha | HEAD | Firmware version: 4.84
Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz | 8 Threads | 15.87 GiB RAM | AVX+
Windows 10 64bits

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3207393/RPCS3.log.gz)

The home screen loads normally but when you enter the game, the screen does not display the scenes and is as in the attached photo.

![Capturar](https://user-images.githubusercontent.com/2024086/58175599-ddc26300-7c76-11e9-9547-9c1f3390bede.PNG)

**Comment by psennermann** [comment]
Maybe your video driver is too outdated? (I have a Nvidia card too - gtx1060 driver 430.64)

![image](https://user-images.githubusercontent.com/6342467/58185712-dcfbf200-7cb3-11e9-8524-738d73b34f4e.png)

**Comment by RainbowCookie32** [comment]
Looking at the compatibility report in the forum, the user that made the report used "Disable Vertex Cache". On your Log it's disabled, maybe try that?

**Comment by alexsilva** [comment]
Driver version: 416.94 Date: 11/13/2018
I will update the driver and see if anything changes.

**Comment by alexsilva** [comment]
Enabling "Disable Vertex Cache" does not solve the problem.

**Comment by alexsilva** [comment]
I updated the driver but did not solve, however...

The screen looks like this when `Xinput` is used in Gamepads settings, but changing to `Keyboard` solves the problem.

What the relation of pads to the screen I have no idea.

But I can say that I do not have a gamepad on the PC, just a keyboard.

**Comment by kd-11** [comment]
Closing as this seems to be a settings issue.
