### ISSUE TITLE
[Request] Invert the SPU verification checkbox in Debug tab

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#6012]
Can you please invert this setting so the default is "unchecked" to be consistent with the other 22 settings? So like call it "Disable SPU Verfication" and by default it's unchecked. 

![2019-05-24 08_16_01-Settings](https://user-images.githubusercontent.com/20983844/58338244-3f600a00-7dfc-11e9-872f-afaf23adebf7.png)

**Comment by 13xforever** [comment]
Or **maybe** we should invert all the **Disable** settings to be _without_ the `Disable` part, and checked by default...

**Comment by elad335** [comment]
You would think debug options are turned off by default though.

**Comment by legend800** [comment]
There's 4 settings in there that are enabled by default with the label "disable". This is just to align it with those effectively.
