### ISSUE TITLE
Possible bad places in code

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#6014]
@AniLeo suggested to make an issue with high priority warnings that you can see in this [static analysis report](https://drive.google.com/open?id=1EbuNt_Vypto0ebkGGyp1XKERhbvy_OgB) . I am not a C++ or PS3 specialist, so most of them may be false detection or just irrelevant. But I think a couple of places are very interesting.

**High Warnings (43)**
<details>

- [ ] sys_spu.h:242 	    	V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: args.

- [ ] CPUDisAsm.h:48 	    	V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: dump_pc.

- [ ] PadHandler.h:225 	    V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: m_class_type, m_cable_state, m_battery_level.
**_See https://github.com/RPCS3/rpcs3/commit/baf98e76bbcfea565c62691ddffcb280a0120f0b#diff-cb1be9eae4a83d32842255d4a8d5c5daR230_**

- [ ] vm_ptr.h:124 	    	V568 	Instantiation of vm::ptr < cellOskDialogConfirmWordFilterCallback >: It's odd that the argument of sizeof() operator is the 'T' expression.

- [ ] vm_ptr.h:112 	     	V568 	Instantiation of vm::ptr < cellOskDialogConfirmWordFilterCallback >: It's odd that the argument of sizeof() operator is the 'T' expression.

- [ ] ProgramStateCache.h:167 	 	V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: vp.

- [ ] texture_cache_utils.h:225 	V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: m_capacity.

- [ ] D3D12MemoryHelpers.h:78 	 	V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: m_mipmap.

- [ ] rsx_cache.h:852 	 	    V629 	Consider inspecting the expression. Bit shifting of the 32-bit value with a subsequent expansion to the 64-bit type.

- [ ] rsx_cache.h:852 	    	V610 	Undefined behavior. Check the shift operator '<<'. The right operand ('(index << 2)' = [0..60]) is greater than or equal to the length in bits of the promoted left operand.

- [ ] rsx_decode.h:32 	 	    V591 	Non-void function should return a value.

- [ ] rsx_methods.h:540 	 	V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: register_previous_value, transform_program, current_draw_clause.

- [ ] VKCompute.h:182 	 	    V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: m_data.

- [ ] VKHelpers.h:2259 	 	V516 	Consider inspecting an odd expression. Non-null function pointer is compared to null: 'vkCreateInstance != nullptr'.

- [ ] VKOverlays.h:482 	 	V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: m_clip_enabled, m_texture_type.

- [ ] VKOverlays.h:403 	 	V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: src_scale_x, src_scale_y.

- [ ] mm_joystick_handler.cpp:300 	 	V607 	Ownerless expression 'cur_pad == padId'.
**_https://github.com/RPCS3/rpcs3/pull/5978/commits/377984054e63e5937e06e135748236efb03eb5b8#diff-db406b150610c1fea0bcee6168a36d92R300_**

- [ ] rpcs3_app.cpp:64 	 	V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: RPCS3MainWin.
**_https://github.com/RPCS3/rpcs3/commit/377984054e63e5937e06e135748236efb03eb5b8#diff-52b70e042121ceae27fc045383f829afR55_**

- [ ] emu_settings.h:158 	 	V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: type.
**_https://github.com/RPCS3/rpcs3/pull/5978/commits/377984054e63e5937e06e135748236efb03eb5b8#diff-99c2a274f9ba7bb93a537e743a88f1f0R153 This is really just to get rid of the warning. There isn't any use in the code for type unless you use Vulkan or DX12_**

- [ ] main_window.cpp:100 	 	V501 	There are identical sub-expressions to the left and to the right of the '!=' operator: "" != ""

- [ ] memory_string_searcher.cpp:33 	V758 	The 'str' reference becomes invalid when temporary object returned by a function is destroyed.

- [ ] osk_dialog_frame.cpp:183 V1028 	Possible overflow. Consider casting operands of the 'text.size() + 1' operator to the 'size_t' type, not the result.
**_https://github.com/RPCS3/rpcs3/pull/5978/commits/377984054e63e5937e06e135748236efb03eb5b8#diff-b532285872c84452a14122dcd3738138R183_**

- [ ] rsx_debugger.cpp:106 	V763 	Parameter 'table' is always rewritten in function body before being used.

- [ ] xinput_pad_handler.cpp:5 V730 	Not all members of a class are initialized inside the constructor. Consider inspecting: state, result.

- [ ] asm.h:47 	        	V502 	Perhaps the '?:' operator works in a different way than it was expected. The '?:' operator has a lower priority than the '||' operator.

- [ ] asm.h:11 	         	V502 	Perhaps the '?:' operator works in a different way than it was expected. The '?:' operator has a lower priority than the '||' operator.

- [ ] asm.h:23 	 	        V502 	Perhaps the '?:' operator works in a different way than it was expected. The '?:' operator has a lower priority than the '||' operator.

- [ ] asm.h:35 	 	        V502 	Perhaps the '?:' operator works in a different way than it was expected. The '?:' operator has a lower priority than the '||' operator.

- [ ] Atomic.h:850 	 	    V790 	It is odd that the assignment operator takes an object by a non-constant reference and returns this object.

- [ ] dynamic_library.h:48 	V568 	Instantiation of utils::dynamic_import < NTSTATUS (PULONG MinimumResolution, PULONG MaximumResolution, PULONG CurrentResolution) >: It's odd that the argument of sizeof() operator is the 'F' expression.

- [ ] File.h:358 	        	V521 	Such expressions using the ',' operator are dangerous. Make sure the expression 'seek(0),!read(result)' is correct.

- [ ] File.h:358 	        	V639 	Consider inspecting the expression for 'seek' function call. It is possible that one of the closing ')' parentheses was positioned incorrectly.

- [ ] File.h:348 	        	V639 	Consider inspecting the expression for 'seek' function call. It is possible that one of the closing ')' parentheses was positioned incorrectly.

- [ ] File.h:348 	        	V521 	Such expressions using the ',' operator are dangerous. Make sure the expression 'seek(0),!read(result)' is correct.

- [ ] types.h:422 	        	V512 	A call of the 'memcpy' function will lead to underflow of the buffer 'data'.

- [ ] types.h:422 	        	V512 	A call of the 'memcpy' function will lead to underflow of the buffer '& mptr'.
</details>

**Always false or always true**

<details>

- [ ] d3dx12.h:1407 	 	 	A part of conditional expression is always false: RequiredSize > (SIZE_T) - 1.

- [ ] rsx_cache.h:60 	 	 	A part of conditional expression is always false.

- [ ] gs_frame.cpp:122 	 	 	A part of conditional expression is always true: !_user_interaction_active.

- [ ] instruction_editor_dialog.cpp:72 	 	 	A part of conditional expression is always false: opcode > 0xffffffffui32.

- [ ] pad_settings_dialog.cpp:635 	 	 	A part of conditional expression is always false: m_button_id <= button_ids::id_pad_begin.
**_id_pad_begin is 0 in this case. But in case someone adds more enum values in front of this one there is a chance that they forget to check this. And it's a good idea to check your valid range. In gui code you won't have to worry about performance as much and you might introduce bugs in the long run if you don't check everything possible._**

- [ ] pad_settings_dialog.cpp:660 	 	 	A part of conditional expression is always false: m_button_id <= button_ids::id_pad_begin.
**_See above_**

- [ ] pad_settings_dialog.cpp:685 	 	 	A part of conditional expression is always false: m_button_id <= button_ids::id_pad_begin.
**_See above_**
   
- [ ] typemap.h:1253 	 	 	A part of conditional expression is always true: ++ locked.
     
- [ ] d3dx12.h:1460 	 	 	Expression 'MemToAlloc > 0xffffffffffffffffui64' is always false.

- [ ] d3dx12.h:1423 	 	 	Expression 'pRowSizesInBytes[i] > (SIZE_T) - 1' is always false.

- [ ] rsx_utils.h:966 	 	 	Expression '_loc < _size' is always true.

- [ ] rsx_utils.h:994 	 	 	Expression '_loc < _size' is always true.

- [ ] VKProgramBuffer.h:46 	 	 	Expression 'num_targets == other.num_targets' is always true.

- [ ] keyboard_pad_handler.cpp:523 	 	 	Expression 'p_profile == nullptr' is always false.

- [ ] mm_joystick_handler.cpp:300 	 	 	Expression 'cur_pad == padId' is always false.

- [ ] save_manager_dialog.cpp:318 	 	 	Expression 'idx != - 1' is always true.
**_If the table or list is empty your selected row will be -1. We already make sure not to run this code if idx < 0 before. So in a perfect world this check would be redundant. But it's always a good idea to check your parameters, especially in gui code._**

- [ ] texture_cache_utils.h:1410 	 	 	Expression 'valid_offset' is always true.

</details>

**Update(01.06.19)**: Previously I analyzed only rpcs3 project, not entire solution. In [this report](https://drive.google.com/open?id=1jnSfOnhfMa9tn28XSI2yfxiJvbcDnsPS) you can see analysis of all projects. Over 400 high priority warnings.

**Comment by Megamouse** [comment]
Is it ok if we devs edit and comment on the list ?

**Comment by Realmantik** [comment]
Ok.

**Comment by necros2k7** [comment]
my 5 cents (sorry if duplicated):
[CgBinaryVertexProgram.cpp:137]: (performance) Function parameter 'value' should be passed by const reference.
[Common\ProgramStateCache.cpp:22]: (error) Shifting 32-bit value by 40 bits is undefined behaviour
[Common\GLSLCommon.h:79]: (performance) Function parameter 'wide_vector_type' should be passed by const reference.
[Common\GLSLCommon.h:79]: (performance) Function parameter 'input_coord' should be passed by const reference.
[GL\GLHelpers.h:1533]: (performance) Variable 'target' is assigned in constructor body. Consider performing initialization in initialization list.
[Overlays\overlay_list_view.cpp:13]: (performance) Variable 'm_scroll_indicator_top' is assigned in constructor body. Consider performing initialization in initialization list.
[Overlays\overlay_list_view.cpp:14]: (performance) Variable 'm_scroll_indicator_bottom' is assigned in constructor body. Consider performing initialization in initialization list.
[Overlays\overlay_list_view.cpp:15]: (performance) Variable 'm_accept_btn' is assigned in constructor body. Consider performing initialization in initialization list.
[Overlays\overlay_list_view.cpp:16]: (performance) Variable 'm_cancel_btn' is assigned in constructor body. Consider performing initialization in initialization list.
[Overlays\overlay_list_view.cpp:17]: (performance) Variable 'm_highlight_box' is assigned in constructor body. Consider performing initialization in initialization list.
[Overlays\overlay_perf_metrics.cpp:166]: (performance) Function parameter 'font' should be passed by const reference.
[Overlays\overlay_save_dialog.cpp:81]: (performance) Variable 'm_dim_background' is assigned in constructor body. Consider performing initialization in initialization list.
[rsx_cache.h:503]: (performance) Function parameter 'pipeline_class' should be passed by const reference.
[rsx_cache.h:503]: (performance) Function parameter 'version_prefix_str' should be passed by const reference.
[rsx_utils.h:876]: (performance) Variable '_capacity' is assigned in constructor body. Consider performing initialization in initialization list.
[rsx_utils.h:877]: (performance) Variable '_size' is assigned in constructor body. Consider performing initialization in initialization list.
[rsx_utils.h:913]: (error) Common realloc mistake: '_data' nulled but not freed upon failure
[VK\VKHelpers.h:1560]: (performance) Variable 'm_width' is assigned in constructor body. Consider performing initialization in initialization list.
[VK\VKHelpers.h:1561]: (performance) Variable 'm_height' is assigned in constructor body. Consider performing initialization in initialization list.
[VK\VKHelpers.h:2018]: (performance) Variable 'createSwapchainKHR' is assigned in constructor body. Consider performing initialization in initialization list.
[VK\VKHelpers.h:2260]: (performance) Variable 'm_instance' is assigned in constructor body. Consider performing initialization in initialization list.
[VK\VKRenderPass.cpp:55]: (error) Signed integer overflow for expression '32767<<22'.

**Comment by Realmantik** [comment]
Update: Today's analysis
[Analysis](https://github.com/RPCS3/rpcs3/files/3488945/fullhtml.zip)

**Comment by kd-11** [comment]
Some are indeed false positives, but some are proper warnings. I'll go over them and fix up the rsx related ones. The ones reported by necros2k7 are mostly false positives in a 64-bit environment though.

**Comment by Realmantik** [comment]
@kd-11, If you want, I can update analysis report.

**Comment by kd-11** [comment]
No rush. The code may have changed by the time I decide to start cleaning up the warnings.

**Comment by necros2k7** [comment]
What type of errors are false positives?

**Comment by kd-11** [comment]
size_t on amd64 is 64 bits not 32.

**Comment by kd-11** [comment]
A lot of noise in the reports comes from a few shortcomings of the tools:
1.
```
bool thing(int& optional_in_out)
{
    optional_in_out = 0;
    return true;
}

int optional;
thing(optional);
do_something_with(optional): <--- optional is uninitialized warning despite being modified by thing
```
2.
```
ptr x = nullptr;
if (some_other_check) x = some_func_that_sets_x_to_not_null();
...
if (x)... <--- x is always false warning
```
3.
```
int func()
{
    switch(something)
    {
    case a:
    case b:
        return 0;
    default:
        fmt::throw("error");   <----- Does not realize throw is noreturn. Warnings about missing break and missing return value
    case c:
        return 1;
    }
}
```

**Comment by kd-11** [comment]
There are also a few which look like errors but really are not, especially the initialization ones since most of them have a ton of optional fields that are useless unless some other condition is met. There is no way for the tools to know this, so they show warnings.
Another issue happens when self-referencing an interface:
```
class a : class b { unique_ptr<b> interface; }
a::a()
{
    interface.reset(this);
}

a::~a()
{
    interface.release();        <----- REEEEEEEEEEEE
}
```

**Comment by kd-11** [comment]
I have dealt with the sensible complaints in https://github.com/RPCS3/rpcs3/pull/6455, although there was only one actual error that could affect code execution. The rest are mostly QOL improvements for readability where applicable.

**Comment by Megamouse** [comment]
This issue is severely outdated.
I suggest to either do a complete renewal of the analysis or close the issue.
