### ISSUE TITLE
unplayable co-op in the sengoku basara series of games

### ISSUE THREAD

**Issue by ZexxTheReaper** [RPCS3/rpcs3#6015]
Player 2's camera is obscured by the stage geometry in every sengoku basara game from samurai heroes/3 to 4 sumeragi.

here is an example taken with OBS in sengoku basara 4 sumeragi

https://www.youtube.com/watch?v=EeXW5HyFGJQ&feature=youtu.be

**Comment by RainbowCookie32** [comment]
Probably related or a duplicate of #5684

**Comment by Hasster1** [comment]
And it also has the same problem as https://github.com/RPCS3/rpcs3/issues/5663

**Comment by AniLeo** [comment]
Video mentions issue has been fixed, closing issue
