### ISSUE TITLE
Various issues throughout the Kingdom Hearts ReMIXes

### ISSUE THREAD

**Issue by bandrew03** [RPCS3/rpcs3#6018]
I've begun to compile a list of the issues I've found in the Kingdom Hearts ReMIX remasters. I have put them into this Google Doc and provided demonstrations and pictures to assist in fixing the issues. Thanks for making a sick emulator.

https://docs.google.com/document/d/16RobtrmNFvvEveIrKCYUHqmGFsL5pbJ_LpMKipWf_I8/edit?usp=sharing

**Comment by digitaldude555** [comment]
@bandrew03 update

**Comment by Asinin3** [comment]
Closing, no update from OP and many of the mentioned issues were fixed. If any remain make a new issue and include log +rsx capture of graphical issues this time.
