### ISSUE TITLE
Qt 5.12.4

### ISSUE THREAD

**Issue by necros2k7** [RPCS3/rpcs3#6019]
Needs:
- [x] Appveyor support (already on Qt 5.13)
- [x] Docker support

**Comment by AniLeo** [comment]
Not available on AppVeyor, not available on any trusty PPAs.

**Comment by Psycho-A** [comment]
Just one question: why? Are there some new features that would be useful for emulator?

**Comment by HenningJW** [comment]
Point releases are bugfixes (usually and in case of Qt), so very little risk with the potential of fixing bugs that have yet to be discovered. There's no reason to not update Qt 5.12 once it's available on AppVeyor and TravisCI without too much hassle.

**Comment by necros2k7** [comment]
Qt 5.12.2 is available

**Comment by Megamouse** [comment]
The docker should be at 5.12.6 already

**Comment by necros2k7** [comment]
Do I understand right that docker and Qt is part of build environment at appveyor? so Qt updates are appveyor dependant? do these parts free?
