### ISSUE TITLE
Can you help me when i click on rpcs3  it doest start when i click it again its says fatal error another instanse of RPCS3 is running close it or kill its procces and i cant open my RPCS3 id doesnt show up what do i do pls help me

### ISSUE THREAD

**Issue by Stefan6666666** [RPCS3/rpcs3#6021]

**Comment by RainbowCookie32** [comment]
GitHub is not the place to ask for support, join our Discord server for that https://discord.me/RPCS3
Please close this issue

**Comment by AniLeo** [comment]
wtf

**Comment by Stefan6666666** [comment]
![image](https://user-images.githubusercontent.com/51028567/58372304-acb68c80-7f1b-11e9-9b79-4ec797bed2b9.png)

**Comment by Stefan6666666** [comment]
![image](https://user-images.githubusercontent.com/51028567/58372320-c5bf3d80-7f1b-11e9-8dc2-4d9303d02437.png)

**Comment by RainbowCookie32** [comment]
Do I really need to post my other message again?

**Comment by Stefan6666666** [comment]
![image](https://user-images.githubusercontent.com/51028567/58372327-da033a80-7f1b-11e9-9f1c-c8a783e7f058.png)
