### ISSUE TITLE
Vulkan: Sengoku Basara 4 ~Sumeragi~ [BLJM-61248] Resolution Scale - Not working [0.0.6-8158-c348fec8_win64]

### ISSUE THREAD

**Issue by Vermilleon** [RPCS3/rpcs3#6023]
Vulkan: Sengoku Basara 4 ~Sumeragi~ [BLJM-61248] Resolution Scale - Not working [0.0.6-8158-c348fec8]

- Resolution Scale - not working (also with Custom game configuration). Resolution Scale Treshold - doesn't give effect.
- Anisotropic Filter/Bloom/Bump mapping - it is also possible does not work properly.
------------------------------------------------------------------------
My computer:
OS: Windows 10 Enterprise LTSC (10.0.17763.379 [1809])
Monitor: Samsung U32H850UMI (31.5"/3840x2160)
CPU: Intel Core i7–4960X Extreme
Video: MSI GeForce RTX 2080 Ti DUKE 11G OC
RAM: Kingston HyperX Beast (T3) DDR3 32Gb [8Gbx4]
SSD: Samsung 850 Pro (2.5", SATA III) [1Tbx2]
------------------------------------------------------------------------
Example - Menu (Bad Bloom Rendering):
![SB4 - Menu (Bad Bloom Rendering)](https://user-images.githubusercontent.com/51031248/58452550-cc6ed000-8128-11e9-9a53-6fab65295ba1.png)

Example - Choose Character 1:
![SB4 - Choose Character 1](https://user-images.githubusercontent.com/51031248/58452569-d85a9200-8128-11e9-93a1-56e6a642e3f6.png)

Example - Choose Character 2:
![SB4 - Choose Character 2](https://user-images.githubusercontent.com/51031248/58452571-da245580-8128-11e9-8525-c5b9c62e98af.png)

Example - Choose Character 3:
![SB4 - Choose Character 3](https://user-images.githubusercontent.com/51031248/58452574-db558280-8128-11e9-970a-dd5e0d5c369a.png)

Example - Stage 1:
![SB4 - Stage 1](https://user-images.githubusercontent.com/51031248/58452576-de507300-8128-11e9-9cd0-3c0e254c8713.png)

Example - Stage 2:
![SB4 - Stage 2](https://user-images.githubusercontent.com/51031248/58452581-df81a000-8128-11e9-8cb6-587bbe0f3171.png)

Example (Settings):
![SB4 - Settings](https://user-images.githubusercontent.com/51031248/58452583-e1e3fa00-8128-11e9-93c8-3f8fb5643830.png)

**Comment by Pontifice** [comment]
It seems you are changing the general no settings not the per-game settings. Try editting the settings for the game. (right click over the game)

**Comment by Vermilleon** [comment]
Resolution Scale not working also with Custom game configuration

**Comment by kd-11** [comment]
It just means the game is using incompatible methods to move the framebuffer around. Resolution scale cannot choose to not work (its a base multiplier), same with anisotropic filtering. If you see jaggies, the game copied over stuff using DMA from where we rendered to where it wanted to output and that definately breaks resolution scaling. Nothing we can do about it other than have someone write a patch.yml entry to reprogram the display section of the game as explicit game-specific hacks are not allowed.

**Comment by Vermilleon** [comment]
Thank you kd-11 for the answer. It is a pity that such a good game has so much blocked the resolution, because not only Sumeragi suffers, but the whole series (Utage, Sanada Yukimura-Den...). I hope soon there will be developers or hackers who will start creating patches for games that suffer from various kinds of problems.

**Comment by Vermilleon** [comment]
Perhaps this LOG will also help to deal with the screen resolution in Sengoku Basara 4 ~Sumeragi~ [BLJM-61248].

Sengoku Basara 4 ~Sumeragi~ [BLJM-61248] right after gameplay with settings: Write Color Buffers: Enabled, Resolution scaling: 100%, Anisotropic Filtering: Auto, Aspect ratio: Auto, AV Resolution: 720p:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3229625/RPCS3.log)

Sengoku Basara 4 ~Sumeragi~ [BLJM-61248] right after gameplay with settings: Write Color Buffers: Disabled, Resolution scaling: 400%, Anisotropic Filtering: 16x, Aspect ratio: 16:9, AV Resolution: 720p:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3229630/RPCS3.log)

**Comment by digitaldude555** [comment]
@Vermilleon fixed now?

**Comment by kd-11** [comment]
Not really a bug to begin with.

**Comment by FutonGama** [comment]
I'm waiting years and no one fixed that =/ the game resolution scale.

**Comment by YuriNator557** [comment]
Resolution scaling is a hack, not all games will work properly with it. FidelityFX Super Resolution has been added since this was closed, use that instead.
