### ISSUE TITLE
Light/Reflection needs fixing for Dragon Quest Builders

### ISSUE THREAD

**Issue by awsdert** [RPCS3/rpcs3#6026]
- You have read the above.
I'll provide the version after helping my neighbor out as I have to copy it by hand (got a script re-naming the file to just rpcs3.AppImage so I could launch from my taskbar)
- You have provided sufficient detail for the issue to be reproduced.
First chapter of DQB and run over to where the bridge "was", you'll see the issue directly
- You have provided system specs.
Linux Mint Cinnamon x64
- Please also provide:
Again I'll do a screenshot when I come back from my neighbor, also just remembered that the camera randomly jumps far from the island, bit of movement restores it eventually but still annoying, you'll probably encounter it on your way to the broken bridge, if not load a save then try running to it as I did

**Comment by awsdert** [comment]
Forgot to mention it's via OpenGL, still struggling to get vulkan running despite my graphics driver having actually provided the relevant vulkan libraries (e.g. libGLX_nvidia-390.so I think it was) - if anyone can point me to a decent guide for this for linux mint, bionic I would appreciate it - I'm gonna boot up now and copy the version then the screenshot

**Comment by awsdert** [comment]
0.0.6-8159-507ec825 Alpha

**Comment by awsdert** [comment]
https://drive.google.com/file/d/1pU3xJPl50T0DpZdtYEtQ3ufNT-19RUJc/view?usp=sharing

**Comment by awsdert** [comment]
Struggling to get that camera issue to re-appear, I'll post it the next time I get it and think to screen shot it.

**Comment by AniLeo** [comment]
Use the edit funcionality instead of pinging everyone to death 🤔

**Comment by awsdert** [comment]
Downloaded the latest update today and noticed the lighting issue is still there, however I then noticed that it was affected by camera position not play position, nearby water whenever you turn the camera the top-right part of the water is garbled.

Anyway the main reason I popped on today is that I somehow managed to speedup the gameplay fps by several fps after modifying config.yml to contain the following:
[code]
Video:
  Renderer: OpenGL
  Resolution: 1280x720
  Aspect ratio: Auto
  Frame limit: Auto
  Write Color Buffers: false
  Write Depth Buffer: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Log shader programs: false
  VSync: false
  Debug output: false
  Debug overlay: false
  Use Legacy OpenGL Buffers: false
  Use GPU texture scaling: false
[/code]

My download is v0.0.6-8193-b2e08100

**Comment by digitaldude555** [comment]
![Screenshot (1168)](https://user-images.githubusercontent.com/26138653/75172786-7ae68680-5736-11ea-8d12-2760785d7a38.png)
![Screenshot (1169)](https://user-images.githubusercontent.com/26138653/75172789-7e7a0d80-5736-11ea-8527-91549f819910.png)
Fixed.

**Comment by awsdert** [comment]
:)
