### ISSUE TITLE
Vulkan: SoulCalibur V [BLUS-30736] Problems of Rendering and not only... [0.0.6-8158-c348fec8_win64]

### ISSUE THREAD

**Issue by Vermilleon** [RPCS3/rpcs3#6029]
Vulkan: SoulCalibur V [BLUS-30736] Problems of Rendering and not only... [0.0.6-8158-c348fec8]

- Overall low FPS (low FPS, even in the menu/cutscenes).
- Resolution Scale working not correctly - partial aliasing is present (also with Custom game configuration). Resolution Scale Treshold - doesn't give effect.
- Overblooming (with/without Write Color Buffers).
- Ghosting (on Characters) (with Write Color Buffers).
- Artifacts on Characters (with Write Color Buffers).
- Overbright (without Write Color Buffers).

Anisotropic Filter - it is also possible does not work properly.
Post-processing effects - perhaps any missing.

------------------------------------------------------------------------
My computer:
OS: Windows 10 Enterprise LTSC (10.0.17763.379 [1809])
Monitor: Samsung U32H850UMI (31.5"/3840x2160)
CPU: Intel Core i7–4960X Extreme
Video: MSI GeForce RTX 2080 Ti DUKE 11G OC
RAM: Kingston HyperX Beast (T3) DDR3 32Gb [8Gbx4]
SSD: Samsung 850 Pro (2.5", SATA III) [1Tbx2]
------------------------------------------------------------------------
Example (Low FPS (cutscene)):
![SCV - CG](https://user-images.githubusercontent.com/51031248/58451019-b3fbb700-8122-11e9-9698-4952f87c798f.png)

Example (Low FPS (menu)):
![SCV - Menu](https://user-images.githubusercontent.com/51031248/58451021-b827d480-8122-11e9-9cc0-3c8c63a533b5.png)

Example (without Write Color Buffers):
![SCV - Without Write Color Buffers 1](https://user-images.githubusercontent.com/51031248/58451067-e7d6dc80-8122-11e9-9fd1-424a17c2c9ef.png)

Example (with Write Color Buffers):
![SCV - With Write Color Buffers 1](https://user-images.githubusercontent.com/51031248/58451082-f1604480-8122-11e9-9ba4-9cc1512b8980.png)

Example (with Write Color Buffers - Resolution issues):
![SCV - With Write Color Buffers 2](https://user-images.githubusercontent.com/51031248/58451105-15238a80-8123-11e9-91b4-f8f436ad2799.png)

Example (Settings):
![SCV - Settings](https://user-images.githubusercontent.com/51031248/58451119-34221c80-8123-11e9-9c13-43f40d17b9c6.png)

**Comment by kd-11** [comment]
Does it work with default (i.e PS3-compatible) settings? If so, close this issue.
PS3-compatible settings in this case would be Write Color Buffers: Enabled, Resolution scaling: 100%, Anisotropic Filtering: Auto, Aspect ratio: Auto, AV Resolution: 720p.

**Comment by Vermilleon** [comment]
Greetings kd-11! I changed the settings to those that you wrote and here's what happened:

Write Color Buffers: Enabled, Resolution scaling: 100%, Anisotropic Filtering: Auto, Aspect ratio: Auto, AV Resolution: 720p (gameplay):
![Gameplay](https://user-images.githubusercontent.com/51031248/58486584-2ac29f80-8177-11e9-95fa-2dc28b0b8503.png)

Write Color Buffers: Enabled, Resolution scaling: 100%, Anisotropic Filtering: Auto, Aspect ratio: Auto, AV Resolution: 720p (character creation - Overbright):
![new 1](https://user-images.githubusercontent.com/51031248/58486667-53e33000-8177-11e9-81dd-9e989ce45bd2.png)

Write Color Buffers: Enabled, Resolution scaling: 100%, Anisotropic Filtering: Auto, Aspect ratio: Auto, AV Resolution: 720p (character creation - Overbright/Artifacts):
![new 2](https://user-images.githubusercontent.com/51031248/58486674-58a7e400-8177-11e9-9679-2a0a4dd68ac1.png)

Write Color Buffers: Enabled, Resolution scaling: 100%, [Changed: Anisotropic Filtering: 16x, Aspect ratio: 16:9], AV Resolution: 720p:
![gameplay 1](https://user-images.githubusercontent.com/51031248/58487153-2d71c480-8178-11e9-868b-dae18f79a800.png)

Some problems still remained:
- Overall low FPS (low FPS, even in the menu/cutscenes)
- Overbright
- Artifacts (on Characters)
- The image is not stretched to the window size (with default settings)

Now I know that the main problem is Resolution Scale, because of him in the game occur:
- Ghosting (on Characters)
- Heavy Artifacts (on Characters)

And Anisotropic Filtering: 16x / Aspect ratio: 16:9 - it is a safe setting for the game.

**Comment by Emulator-Team-2** [comment]
I have better FPS on i5 8500.
![1](https://user-images.githubusercontent.com/38318848/58494920-70329d00-8176-11e9-8ca9-f3e613c18ec9.png)

**Comment by Vermilleon** [comment]
> I have better FPS on i5 8500.
Probably it's about optimizing for those instructions and commands that my processor ( i7–4960X) supports.

**Comment by Licmi007** [comment]
to fix this graphics problem you have to mess with Resolution Scale Threshold
![rpcs3_2019_06_02_11_07_42_673](https://user-images.githubusercontent.com/51286085/58759236-0aa03100-8527-11e9-807f-9cb44bbd5a23.png)

4k wcb on  resolution scale threshold 144x144(or more(depends on the game )
![rpcs3_2019_06_02_11_10_19_031](https://user-images.githubusercontent.com/51286085/58759252-420edd80-8527-11e9-86b7-16b7bc865349.png)

custom creations part  is broken   low fps+over bloom  visible triangles,+ low fps in menu(native res or higher =same fps)  
pc  RX 480 I7 7700k

**Comment by kd-11** [comment]
@Vermilleon I don't know why you have such low fps, maybe its related to turing? No idea. I doubt it's the cpu as my first generation ryzen 1700 runs this fine at fullspeed. How is your GPU hooked up to the system? First PCI-e slot on the motherboard? Is the slot PCI-e 3.0x16? We've observed similar issues on older motherboards where a GPU in a PCI-e 2.0 slot does not work properly (RPCS3 is very PCI-e heavy).

**Comment by Licmi007** [comment]
his fps is realy low..my fps on ship is 40-50 i cant hit 60 on any map..( fresh rpcs3 instalation+ default settings) idk how you have 60...
![rpcs3_2019_06_03_18_12_10_175](https://user-images.githubusercontent.com/51286085/58817092-399fcb00-862b-11e9-83b0-ba610b5c482c.png)
i'm going to restart bios settings and see if that change anything

**Comment by Vermilleon** [comment]
@Licmi007 Thank you! Resolution Scale Treshold 144x144 (for 4k Resolution Scale) working well and many artifacts (on characters) have disappeared, but not all. But Fps is still low (17-25).

@kd-11 Hello! It may be the case in Turing, or maybe because of the tweaks that I applied in the system to disable the telemetry and tracking Windows. The video card is plugged into the first PCI-e slot 3.0x16 (MB: ASUS X79–DELUXE). The drivers are the latest (all previous same low fps). Maybe the thing in the drivers?

**Comment by Licmi007** [comment]
Vermilleon do you have low fps only in this ps3 game ? try soulcalibur 4(works fine on my pc 55-60+ all the time)

**Comment by Vermilleon** [comment]
@Licmi007 SoulCalibur IV [BLUS-30160] (Training stage). RPCS3 v0.0.6-8176-32776db8 [win64] with settings:
1) Vulkan: Write Color Buffers: Enabled, Resolution scaling: 400%, Resolution Scale Treshold 16x16, Anisotropic Filtering: 16x, Aspect ratio: 16:9, AV Resolution: 720p:
![1](https://user-images.githubusercontent.com/51031248/58820618-20574880-8644-11e9-80b8-6f5b35a13fef.png)

2) Vulkan: Write Color Buffers: Enabled, Resolution scaling: 300% (4k), Resolution Scale Treshold 336x336, Anisotropic Filtering: 16x, Aspect ratio: 16:9, AV Resolution: 720p:
![2](https://user-images.githubusercontent.com/51031248/58820998-1e41b980-8645-11e9-9559-37ed5f460620.png)

**Comment by Licmi007** [comment]
yeah there is something wrong on your side,my pc i weaker but my fps is higher(you dont need to use Resolution Scale Treshold  for sc 4)
reinstall your windows

**Comment by Vermilleon** [comment]
@Licmi007 Probably, after 2 months I will reinstall Windows and try to check SC IV / V before using any tweaks. If nothing changes after upgrading RPCS3 and Nvidia drivers

**Comment by Licmi007** [comment]
@Vermilleon good luck
back to sc 5 problem now
the one of biggest problem in soulcalibur 5 now is custom character creation part
![rpcs3_2019_06_03_20_01_18_673](https://user-images.githubusercontent.com/51286085/58823770-c43bf680-863a-11e9-9551-cb093876ddb5.png) rpcs3 default settings

**Comment by kd-11** [comment]
Need an update on this issue. Aspect ratio problems have been resolved and poor performance was found to be unrelated to graphics (the game has software post-processing on SPUs that can be disabled with a patch).

**Comment by Aurez** [comment]
Thanks for the info. 
Any hope to get the patch you are talking about? Please :)

**Comment by kd-11** [comment]
I don't have the raw patch entry on hand, ask around on discord. Do note that it may require the "embedded SPU patching" pull request that has not yet been merged.

**Comment by GraionDilach** [comment]
Can confirm the patch at https://wiki.rpcs3.net/index.php?title=Help:Game_Patches#SPU_MLAA_removal_patch fixes game performance on RPCS3 version 0.0.8.9577 (Ryzen 3600X@3.8 GHz, 32 GB RAM. GTX 1660 Super).
