### ISSUE TITLE
Regression: Tales of Symphonia Chronicles graphic glitch (#5937)

### ISSUE THREAD

**Issue by kleung1221** [RPCS3/rpcs3#6032]
Tales of Symphonia Chronicles display error after version 0.0.6-8119

https://i1000.photobucket.com/albums/af129/kleung19821/image%202_zpsmavmk0e5.png

https://i1000.photobucket.com/albums/af129/kleung19821/image%201_zpsfansbqec.png

https://i1000.photobucket.com/albums/af129/kleung19821/image_zpsnxz2s7n1.png

thank you~

log file
https://drive.google.com/open?id=1ifOx2c1ZWvuDHMGUZi-2iVIutQ6uAsuM

**Comment by AniLeo** [comment]
Missing log file

**Comment by kleung1221** [comment]
update~

**Comment by greentop** [comment]
Tales of Zestiria also has this graphical issue. It appears in PR #5937 within commit 88c20afd.

**Comment by AniLeo** [comment]
Still an issue? A follow-up PR already happened
Need to know if it's still an issue so it's properly assigned for review as a regression

**Comment by greentop** [comment]
The regression still remains as of Master 232a35b

**Comment by AniLeo** [comment]
May require a capture, either RSX or RenderDoc
Regression from #5937 so cc @kd-11 to triage this one

**Comment by greentop** [comment]
@kd-11
https://drive.google.com/open?id=1Pfzh_fUP559KbiqmoQyLzpBgCoP2_Eo_
RenderDoc v1.4 capture of the character ghosting post PR #5937 at the bottom right corner. Sorry for the large file size, I hope that it got the desired capture.

**Comment by kleung1221** [comment]
> Still an issue? A follow-up PR already happened
> Need to know if it's still an issue so it's properly assigned for review as a regression

Yes,i try the newest version 0.0.6-8315,

Still have an issue,here is log files

https://drive.google.com/open?id=1teJZ6ObbRT41UMp9a40sVkJuMY48z7Q9

**Comment by Emulator-Team-2** [comment]
@kleung1221
@greentop 

Retest with https://github.com/RPCS3/rpcs3/pull/6205

**Comment by brunociaciare** [comment]
> > Still an issue? A follow-up PR already happened
> > Need to know if it's still an issue so it's properly assigned for review as a regression
> 
> Yes,i try the newest version 0.0.6-8315,
> 
> Still have an issue,here is log files
> 
> https://drive.google.com/open?id=1teJZ6ObbRT41UMp9a40sVkJuMY48z7Q9

Hey, guys! Having the exact same issue around here, with version 0.0.7-8641 (2019-09-03). I'm getting my log files to post here. 

@AniLeo  @kd-11  @greentop  any progress on this one?

**Comment by greentop** [comment]
@kd-11 @brunociaciare 
In later parts of the game, the ghosting issue triggers a far more excessive fullscreen flash that should not be present.
**RSX capture:** https://drive.google.com/file/d/1ioDNfo1if6xYYsvv9dJwOMVlX2hk2mjn/view?usp=sharing
**Screenshot:** 
![Screenshot from 2019-09-04 16-22-11](https://user-images.githubusercontent.com/2325766/64289133-a7f96f80-cf31-11e9-918a-eef88277231d.png)

**Comment by brunociaciare** [comment]
> @kd-11 @brunociaciare
> In later parts of the game, the ghosting issue triggers a far more excessive fullscreen flash that should not be present.
> **RSX capture:** https://drive.google.com/file/d/1ioDNfo1if6xYYsvv9dJwOMVlX2hk2mjn/view?usp=sharing
> **Screenshot:**
> ![Screenshot from 2019-09-04 16-22-11](https://user-images.githubusercontent.com/2325766/64289133-a7f96f80-cf31-11e9-918a-eef88277231d.png)

Thank you for the answer, @greentop . That's weird - I'd never figure that it could get worse, I'm early game on the first ToS by now.

There's any way to at least reduce the issue/effect?

**Comment by greentop** [comment]
@brunociaciare Older builds such as RPCS3 0.0.6-8119 (2019-05-16) do not have the issue present.

**Comment by brunociaciare** [comment]
> @brunociaciare Older builds such as RPCS3 0.0.6-8119 (2019-05-16) do not have the issue present.

That's nice to hear! I'll download it right away to play - It's the only game I'm currently experimenting on RPCS3 anyway now. Thank you!

**Comment by greentop** [comment]
Display ghosting corruption remains in Zestiria with PR #7340

**Comment by kd-11** [comment]
Did it regress from the same PR as symphonia? Might not be technically related otherwise.

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/73467447-6233bc80-4394-11ea-8dc1-e58f25e95e3f.png)
Not getting any ghosting on zestiria. Maybe attach a save file and screenshots @greentop

**Comment by greentop** [comment]
@kd-11 After loading the save file, press the D-Pad Down button on the gamepad to quickly trigger the character ghosting effect. The character ghosting can also be observed while within a battle play. The shaded area within this map that is covering the top half of the screen also appears to be related.

Save File:
[BLUS31533_SAVE1_007.zip]

Screenshot:
(https://github.com/RPCS3/rpcs3/files/4135968/BLUS31533_SAVE1_007.zip)
![Screenshot01](https://user-images.githubusercontent.com/2325766/73485156-98f7db80-4370-11ea-90b6-dd6346c1d813.jpg)
