### ISSUE TITLE
RSX [0x0008d40]} RSX: class std::runtime_error thrown: Verification failed (e=0xb7)

### ISSUE THREAD

**Issue by gleidsonnunes** [RPCS3/rpcs3#6033]
This issure is on Call of Duty Advanced Warfare

````
F {RSX [0x0008d40]} RSX: class std::runtime_error thrown: Verification failed (e=0xb7): 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsx_methods.h:372)
````
[LOG](https://github.com/RPCS3/rpcs3/files/3230094/RPCS3.zip)

**Comment by AniLeo** [comment]
User using unsupported D3D12 renderer, invalid issue. If you get this on a supported renderer, ping for issue reopen and upload a log on such renderer.

**Comment by RainbowCookie32** [comment]
And the game is also marked intro, it's not supposed to "work"
