### ISSUE TITLE
Spider-Man Edge of Time [BLUS 30760] - Game freezes on launch when game's trophies folder exists

### ISSUE THREAD

**Issue by TheRealPSV** [RPCS3/rpcs3#6035]
RPCS3 version: v0.0.6-8171-c638e826 Alpha
PS3 Firmware version: 4.84
OS: Win10 x64
CPU: Intel i7-6700K
GPU: Nvidia GeForce GTX 1080

The game freezes on launch if it's been run before and its trophies folder has been generated (`dev_hdd0\home\00000001\trophy\NPWR01899_00`). Deleting that trophies folder allows it to run normally, but it has to be deleted before each launch of the game.

Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3230550/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
Issue is fixed.
