### ISSUE TITLE
Dualshock 3 compatibility issues in latest builds

### ISSUE THREAD

**Issue by xNameleSS** [RPCS3/rpcs3#6036]
Hello! Thank you for your hard work!
Straight to the point. Some gamepads stops working correctly with sony official drivers. My DS3 works with WinUSB method, sixaxis\gyro works flawlessly. But with new build and new drivers it still recognized but not react to any input. Not sure is it a driver/software problem or a unoriginal/uncommon gamepad, cant check it right now.
Seems that old DS3 handler not really outdated - it has better compatibility! It can handle some third-party gamepads that sony driver obviosly can not. So please, leave it as legacy plugin at least (for example). It can be vital for some users.

**Comment by RipleyTom** [comment]
Just in case... you pushed the PS button right? The ds3 doesn't send any output unless the user pushes it(it was the same with WinUSB though).

As for the 3rd party pads I had no idea they worked with the WinUSB implementation, I'll see what I can do.

**Comment by xNameleSS** [comment]
Yes, i pushed PS  (It works with default win driver, but not with sony one. Tried on Win10 and win7 machines)
My gamepad identified as VID_054c&PID_0268 (just like original) and some third-party pads has different ID - i think it can potentially work trough WinUSB too.

**Comment by MSuih** [comment]
Woudn't be too hard to revert d616ce223 but with some kind of winusb config entry instead of ifdefs.

**Comment by Krusher97** [comment]
My 3rd party pad doesn't work with Sony's official drivers either whereas it worked with the WinUSB implementation before(albeit without gyro).

**Comment by kd-11** [comment]
No ifdefs, my suggestion was to implement winusb as a new windows-only input handler and allow manual or even automatic detection between winusb and the SCE drivers. With some refactoring, the winusb handler should be fairly light since most code is shareable with the SCE driver.

**Comment by redfoxxyz13** [comment]
Hi I'm new to getting this emulator. Idk where I can get games for rpcs3. I tried looking online but can't find anything.

**Comment by RainbowCookie32** [comment]
> Hi I'm new to getting this emulator. Idk where I can get games for rpcs3. I tried looking online but can't find anything.

RPCS3 doesn't provide links to pirated games or support piracy. Read the quickstart guide for methods of getting games legally, don't spam Github threads with this

**Comment by cb88** [comment]
> 
> 
> Yes, i pushed PS (It works with default win driver, but not with sony one. Tried on Win10 and win7 machines)
> My gamepad identified as VID_054c&PID_0268 (just like original) and some third-party pads has different ID - i think it can potentially work trough WinUSB too.

I have the same controller it's a Sony controller from everything I can see... CECHZC2H A1 .. I've had it a *long* time and am pretty sure it is not a fake since I used it since the day I bought my PS3 (and I played a lot of skyrim on there untill i got my PS4).  It also has the reset button while some of the fakes of this part # do not.

**Comment by Megamouse** [comment]
Is this still an issue in the latest build? @xNameleSS

**Comment by Megamouse** [comment]
closing. assumed fixed
