### ISSUE TITLE
Project DIVA F (BLUS31319) problems with rsx cache

### ISSUE THREAD

**Issue by vietnam13231** [RPCS3/rpcs3#6037]
There is a problem with correct shader caching, makes a lot of graphics to not display (black elements).

Screenshots:
should be:
![diva-intro correct](https://user-images.githubusercontent.com/16107604/58595866-55455300-8272-11e9-8a54-7068ef1f5a6f.jpg)
![diva-mainMenu correct](https://user-images.githubusercontent.com/16107604/58595868-570f1680-8272-11e9-9ffb-a8b1528fa84d.jpg)

current master:
![diva-intro master](https://user-images.githubusercontent.com/16107604/58595742-fbdd2400-8271-11e9-8d06-d3ae037ff8a0.jpg)
![diva-mainMenu master](https://user-images.githubusercontent.com/16107604/58595745-fe3f7e00-8271-11e9-9c02-0b1404199ced.jpg)

Also log is spammed with lines like this:
E {RSX [0x02f75d4]} RSX: Inadequate buffer length submitted for a compute operation.Required=169869312 bytes, Available=134217728 bytes

RPCS3 version: from 0.0.6-7947 (PR #5785) to current master
PS3 Firmware version: 4.84
OS: Win10 x64
CPU: Intel i9-9900K
GPU: Nvidia GeForce GTX 1080

Reproducing method: simply start the game after clearing shader cache on any master build from 0.0.6-7947 onwards.

Log: 
[RPCS3-divaF.log.gz](https://github.com/RPCS3/rpcs3/files/3234663/RPCS3-divaF.log.gz)

**Comment by Emulator-Team-2** [comment]
@vietnam13231 
Can you check this game again with default `Resolution scaling: 100%`.
For me that's a duplicate of https://github.com/RPCS3/rpcs3/issues/5938.

**Comment by vietnam13231** [comment]
@Emulator-Team-2 
You are right, it is. Didn't find it, too complicated title.
Closing.
