### ISSUE TITLE
Moving the game window cases audio video desync

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#6043]
Not sure about AMD but it does not happen on intel gpu but it does happen on nvidia(vulkan only)

Run any game and click and hold the left mouse button on the game window titlebar
The audio will continue but the video will stop for two seconds

If you keep holding the left button,the game window will unfreeze after 2 seconds and jump to the correct frame(not always)but if you press and hold few times and release the button in less than 2 seconds,you may end up watching an intro(for example)without audio because the audio was over long time ago.

With Intel is ok,there is no freeze at all
I am using the latest beta but I tried some older versions too

PS.This does not happen while using PPSSPP with my nvidia card and vulkan

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/6069
