### ISSUE TITLE
Musou Orochi 2 Ultimate [BLAS50676] rendering issues

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#6044]
Some object maps appear weird dark blue color ：

![未标题-1](https://user-images.githubusercontent.com/47111657/58742330-add54580-8456-11e9-89b5-50ad91bf3eb0.jpg)
![未标题-11](https://user-images.githubusercontent.com/47111657/58742333-b2016300-8456-11e9-8671-6059d06f3219.jpg)
![未标题-1](https://user-images.githubusercontent.com/47111657/58756274-c1041600-8527-11e9-894e-73582229e1af.jpg)
![未标题-1](https://user-images.githubusercontent.com/47111657/58756931-ff073700-8533-11e9-8dbc-95ab4d58bfe5.jpg)

When attacking enemy, the body color of the character (enemy or our side) will appear in multicolour ：

![未标题-2](https://user-images.githubusercontent.com/47111657/58742383-36ec7c80-8457-11e9-8205-858918996111.jpg)

version: 0.0.6--8151
setting: VULKAN
PC: 8700k+1070ti+16gb ram

WCB or SRM is invalid for the issues

**Comment by arcadee1977** [comment]
I retest with the latest master，this issues still exist

**Comment by Emulator-Team-2** [comment]
@arcadee1977 
Can you also retest this issue (#5723)?

**Comment by digitaldude555** [comment]
@arcadee1977 update

**Comment by AniLeo** [comment]
@arcadee1977 needs update as per latest test

**Comment by arcadee1977** [comment]
This issue has been fixed by https://github.com/RPCS3/rpcs3/pull/8367
