### ISSUE TITLE
Armored core 4 collision issue 

### ISSUE THREAD

**Issue by dulsan** [RPCS3/rpcs3#6064]
I am using the experiential version of the EM, given to me by a discord server member. 

RPCS3 v0.0.6-8160-1df11d40 Alpha | HEAD | Firmware version: 4.84
Intel(R) Core(TM) i5-4570T CPU @ 2.90GHz | 4 Threads | 15.89 GiB RAM | AVX+ 

Armored core 4 first had an issue with the error:
F {RSX [0x00c35b8]} RSX: class std::runtime_error thrown: Unknown stencil op 0x6
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gcm_enums.cpp:706)

One of the discord members created an experimental build to counter this. 
https://ci.appveyor.com/api/buildjobs/0msf9f6egflokwse/artifacts/rpcs3-v0.0.6-8160-1df11d40_win64.7z 

However, there are other problems, such as: Collision detection on world is garbage, and makes the guy hover forever. Second problem is the MEM violation error, which happens by going to different places. 

It might be the same with For Answer as well. But i am not sure.

**Comment by elad335** [comment]
move to #5545 as a comment please.

**Comment by kd-11** [comment]
Closing as duplicate.
