### ISSUE TITLE
resident evil 4 [NPEB00342] - Crash after "Six years later..."

### ISSUE THREAD

**Issue by mavethee** [RPCS3/rpcs3#6066]
RPCS3 v0.0.6-8196-2bc0ea37 Alpha | HEAD | Firmware version: 4.84
Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz | 4 Threads | 7.87 GiB RAM | AVX+
resident evil 4 [NPEB00342] - Random MEM: Access Violation.
![unknown](https://user-images.githubusercontent.com/47083527/59161949-5d5e8780-8ae9-11e9-8492-f08803f02765.png)
Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3269777/RPCS3.log)
Savefile:
[NPEB00342-PAL-000.zip](https://github.com/RPCS3/rpcs3/files/3269778/NPEB00342-PAL-000.zip)
Sadly I have no idea when it reggresed but I saw two old closed simular issues so I guess this issue may be still a thing.

**Comment by StalkerDolg** [comment]
Oh god. Play it on pc....

**Comment by RainbowCookie32** [comment]
> Oh god. Play it on pc....

Please avoid commenting if you are not going to contribute anything useful to the issue. Just because the game has a PC port doesn't mean we should ignore it here.

**Comment by AniLeo** [comment]
Don't post trash irrelevant to the issues being tracked

**Comment by Realmantik** [comment]
This issue related with Vulkan. On OpenGL the game works fine.(asmjit\LLVM)

[RPCS3-0.0.6-8336_SPU-asmjit_Vulkan.zip](https://github.com/RPCS3/rpcs3/files/3371310/RPCS3-0.0.6-8336_SPU-asmjit_Vulkan.zip)
[RPCS3-0.0.6-8336_SPU-LLVM_Vulkan.zip](https://github.com/RPCS3/rpcs3/files/3371311/RPCS3-0.0.6-8336_SPU-LLVM_Vulkan.zip)

**Comment by Realmantik** [comment]
This crash happens not only in "Six years later..." moment, that you can skip, but in the whole game.

**Comment by kd-11** [comment]
I'll investigate this soon.

**Comment by Realmantik** [comment]
The game is working fine with that commit https://github.com/RPCS3/rpcs3/pull/6376/commits/64cf07624053eb3c7de4fd2c19546bcbea117971.

**Comment by Yahfz** [comment]
Just tested with master 8620, it works fine.

**Comment by AniLeo** [comment]
Closing as fixed
