### ISSUE TITLE
MMJoystick wrong y-axis direction

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#6072]
Its best illustrated in picture, as you can see, on windows it says UP but on rpcs3 is says DOWN. This leads to wrong direction.

![mmjoystick_wrong_direction](https://user-images.githubusercontent.com/13552004/59229952-8462a980-8c0e-11e9-9e8e-c69823f60c62.jpg)

**Comment by vsub** [comment]
I am using the gamepad settings window to be able to tell which gamepad I am currently using and to be able to tell,I always use the left analog and it works fine here,up is up in xinput and mmjoystick

**Comment by Megamouse** [comment]
If the gamepad (you never said which one) say up is down and down is up in mmjoystick then you just have to deal with it XD

**Comment by darkash** [comment]
Just deal with it, but this is quite strange as xinput detects it correctly but mmjoystick is inversed
The gamepad brand and model, it was logitech f710

seeing the plus and minus axis on the analog settings getting inversed in rpcs3 is strange enough but it's not really a problem I guess
<details><summary>XInput
</summary>
<img src="https://user-images.githubusercontent.com/2842880/59304901-4ffcf500-8cc3-11e9-844d-4e53eaf75d63.png"></img>
</details>
<details>
<summary>
MMJoystick
</summary>
<img src="https://user-images.githubusercontent.com/2842880/59304933-6014d480-8cc3-11e9-92e2-e09635ef9cad.png"></img>
</details>

Not sure what's actually the cause

**Comment by jobs-git** [comment]
I just configured it with the assignment button, so I got to thank the Devs for giving us flexibility. However, as you mentioned its strange they are different

**Comment by Megamouse** [comment]
I'll try to add log messages to the detected values soon. So maybe we can find out if there's a flaw.

**Comment by Megamouse** [comment]
you can try this build once it is ready:
https://ci.appveyor.com/project/Megamouse/rpcs3/builds/25236741/artifacts
it will log the min and max values for each axis (the only place I could think of that might cause this problem if it isn't a driver issue)

**Comment by jobs-git** [comment]
I will test this as soon as I get access to win machine.

**Comment by jobs-git** [comment]
Log with mmjoy

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3293728/RPCS3.log)

**Comment by Megamouse** [comment]
That looks normal to me.
I think this controller simply wasn't built with mmjoystick in mind

**Comment by jobs-git** [comment]
Its reversed:

In my test when analog is RIGHT it registers X+ & When analog is LEFT it registers X-, this is correct behavior.

But when analog is UP it registers Y- (instead of Y+) and DOWN registers as Y+ (instead of Y-), this is opposite behavior to that of RIGHT-LEFT analog.

**Comment by Megamouse** [comment]
Mmjoystick is old and deprecated. Usually you would use directinput, but we simply didn't add it yet for project management reasons. Btw. Why are you using mmjoy anyway? Your controller is designed to work with xinput or directinput. Not mmjoystick

**Comment by jobs-git** [comment]
Oh, that is why. XInput is not registering my generic game controller other options were just dualshock but this is definitely not a dualshock. I might just wait for the directinput since mmjoystick is deprecated

**Comment by Megamouse** [comment]
or simply map the controller inverted? that's why i added mapping in the first place

**Comment by jobs-git** [comment]
Yeah, closing this. Looking forward to the directinput in the future.

**Comment by vsub** [comment]
@jobs-git one stupid question(I just notest something)
Did you set your controls or use the default once

Here is the situation(the default configuration does not work properly at all with MMjoystic and my gamepad)
The left side is my old settings and the right side is the settings I get when I click "Restore Defaults"

When I click on "Restore Defaults"
LAU becomes Y+ which is the Left analog down but the console says Y-(the button in the gui says Y+)
LAD becomes Y- which is the left analog up but the console says Y+(the button in the gui says Y-)

RAU(R+ on the button and R- in the console)
RAD(R- on the button and R+ in the console)

Also R2 becomes RAL,the button says Z-(on the analog)but the console says Z+
L2 becomes RAR,the button says Z+ but the console says Z-

RAL in the console it says Button U- and if you look at the old settings Button U- is R2 and ingame it is acting as R2
RAR in the console it says Button U+,in the old settings it is L2 and ingame it act as L2

And also,almost all of the button(except circle(button2))names are shown wrong(default names)in the gui but properly in the console and in windows game controllers

If I set all of the buttons manually,then all of the buttons work properly,all names are correct and the analogs in that circle are moving the right way

![2019-06-22_152015](https://user-images.githubusercontent.com/5032540/59965382-128b3980-9505-11e9-8f47-3125f344993a.jpg)

**Comment by jobs-git** [comment]
Hi @vsub 

I set nothing than selected mmjoystick, all else are default. I am doing what you did now, I assign buttons manually, thank goodness the devs made it!

I just submitted an issue cause I find it reacts differently than that of standard Windows behavior.
