### ISSUE TITLE
Feature request: Remove all cache

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#6073]
On current implementation, we have to clear the SPU, PPU, & Shader Cache one by one if we want to clear all of those.
![remove_all](https://user-images.githubusercontent.com/13552004/59229911-65641780-8c0e-11e9-9240-62b6a1da82c6.jpg)

**Comment by vsub** [comment]
Or go to the cache folder and delete the folder with the game id

**Comment by Megamouse** [comment]
I'm guessing that this new option is only meant for the 3 caches?

**Comment by jobs-git** [comment]
hi @Megamouse  yes, only those 3 but not the config.
