### ISSUE TITLE
Gran Turismo 6 VK_ERROR_DEVICE_LOST crash

### ISSUE THREAD

**Issue by extgame** [RPCS3/rpcs3#6074]
Vulcan crashes with VK_ERROR_DEVICE_LOST every time I start up Gran Turismo 6. I have tried 0.0.6-8202, 8194, 0.0.5-7505, and sends the same error. OpenGL also crashes with an error like Unmapped Memory, Unexpected internal format. I got the game to go till buying our first car, where it crashed. After that it crashes at the name selecting part, just like every single time before. 

I tried updating the game to v1.06 and it goes through the 15th anniversary gift at the start but crashes as usual at the name selecting part.

CPU-Ryzen 5 2400G
GPU-GTX 1060 3GB
Driver-430.86
RAM-8GB
Windows 10 1903

CPU settings- LLVM Recompiler, ASMJIT compiler, all additional settings but Lower SPU thread priority.
GPU- Vulkan/OpenGL, at 1280x720 100% Res Scale

**Comment by kd-11** [comment]
Pretty sure this isn't an issue anymore. GT6 loads fine; it will hang and crash in other ways but not due to driver crashing.
