### ISSUE TITLE
TSX Causing Crashes

### ISSUE THREAD

**Issue by Kian-Stevens** [RPCS3/rpcs3#6077]
For the past few pull requests, a couple of games have been crashing when TSX is enabled
These games are: LEGO Harry Potter (Years 1-4) and Gran Turismo 5

As for Harry Potter, the game will simply freeze for a second, and the executable will close itself down completely
The crashes always happen before you can load a save, i.e. on the intro video or on the start menu
Here's the log file from the latest crash (which happened on the intro video): [Harry Potter.log](https://github.com/RPCS3/rpcs3/files/3278738/Harry.Potter.log)

As for Gran Turismo, the game will freeze but the emulator will stay open whilst music continues to play
My tests have always been performed by browsing the track/car selection menus in Time Trial mode
The crashes happen whilst browsing said menus, but will also sometimes happen if the game is left idle on the 'Accessing Game Data' confirmation screen
The crashes show a 'MEM: Access violation writing location 0x0' message, followed by a 'FIFO error: Possible desync event' message
Here's the log file from the latest crash which happened on the 'Accessing Game Data' confirmation screen: [Gran Turismo 1.log](https://github.com/RPCS3/rpcs3/files/3278816/Gran.Turismo.1.log)
Here's the log file from the latest crash which happened whilst browsing menus: [Gran Turismo 2.log](https://github.com/RPCS3/rpcs3/files/3278817/Gran.Turismo.2.log)

Both games have the following configurations:
![Settings](https://user-images.githubusercontent.com/31938249/59311223-ab69bb80-8ca0-11e9-81e2-8457d25d9ed9.png)

**Comment by psennermann** [comment]
For me Ninokuni, Persona 5 and Shadow of the Damned crash with TSX enabled and LLVM Recompiler (0.0.6-8229), so I think that almost every game is affected; TSX+ASMJIT recompiler instead seems to be fine.
Maybe #6056 aims to fix this problem, but I think it's better to have it up to date with the base (master) branch before testing it...

**Comment by Kian-Stevens** [comment]
> For me Ninokuni, Persona 5 and Shadow of the Damned crash with TSX enabled and LLVM Recompiler (0.0.6-8229), so I think that almost every game is affected; TSX+ASMJIT recompiler instead seems to be fine.
> Maybe #6056 aims to fix this problem, but I think it's better to have it up to date with the base (master) branch before testing it...

The tests I performed last night (which generated the attached log files) were using version 0.0.6-8206, so I suppose that's adequately up-to-date with master

I haven't tried ASMJIT yet, nor have I tried #6056, so I'll give them a try later and report on my findings... However, from what you and others in the referenced pull request thread have said, LLVM doesn't seem to go well with TSX on the master builds as current

**Comment by metspo** [comment]
i can comp this! Had crashes last night. SPU LLVM + TSX causes crashes. AMSJIT + TSX aint crashing, so either play with ASMJIT or LLVM without TSX :)

**Comment by Kian-Stevens** [comment]
Just tested Gran Turismo 5 again, thrice...

**0.0.6-8206 : ASMJIT + TSX**
The 'Accessing Game Data' confirmation screen worked fine, the menus worked fine -- meaning I could get into races each time -- and two of the three races I did also worked fine
Re the one race which _didn't_ work fine, the game froze with the FIFO error message
Additionally, ASMJIT -- with and without TSX -- introduced a lot of audio stuttering and overall the game ran quite a bit slower compared to LLVM

**Using #6056 : LLVM + TSX**
This pull request fixes the crashes when TSX is enabled with LLVM!
The performance of this pull request is comparatively similar to the master build, but in some areas, I noticed that the master build _did_ have slightly better FPS (a maximum of 5 FPS greater in fact)

I'm yet to test Harry Potter, but I can imagine #6056 will fix that too

**Comment by mjuzikfrik** [comment]
#6056 fixes crashes of LLVM+TSX of Persona 5. :)

**Comment by psennermann** [comment]
Now that #6056 has been merged, I think this issue can be closed...
