### ISSUE TITLE
KEY_HOMEPAGE not recognized on Bluetooth gamepad

### ISSUE THREAD

**Issue by unascribed** [RPCS3/rpcs3#6079]
I have an ASUS Bluetooth gamepad intended for use with Android devices. Everything about it works except the cluster of three buttons in the top center, which I can set in the pad configuration, but are completely unrecognized in-game.

The buttons are recognized as "Back Key", "Mode", and "Homepage Key":
![screenshot](https://user-images.githubusercontent.com/6185037/59386205-f0323880-8d1a-11e9-9b14-17b232bc60f7.png)

Here's evtest output from pressing these three buttons in sequence:
<details>
<summary>evtest output</summary>
<pre>
$ evtest /dev/input/event20
Input driver version is 1.0.1
Input device ID: bus 0x5 vendor 0xb05 product 0x4500 version 0x40
Input device name: "ASUS Gamepad"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 158 (KEY_BACK)
    Event code 172 (KEY_HOMEPAGE)
    Event code 304 (BTN_SOUTH)
    Event code 305 (BTN_EAST)
    Event code 307 (BTN_NORTH)
    Event code 308 (BTN_WEST)
    Event code 310 (BTN_TL)
    Event code 311 (BTN_TR)
    Event code 316 (BTN_MODE)
    Event code 317 (BTN_THUMBL)
    Event code 318 (BTN_THUMBR)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 1 (ABS_Y)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 2 (ABS_Z)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 5 (ABS_RZ)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 9 (ABS_GAS)
      Value      0
      Min        0
      Max      255
      Flat      15
    Event code 10 (ABS_BRAKE)
      Value      0
      Min        0
      Max      255
      Flat      15
    Event code 16 (ABS_HAT0X)
      Value      0
      Min       -1
      Max        1
    Event code 17 (ABS_HAT0Y)
      Value      0
      Min       -1
      Max        1
    Event code 40 (ABS_MISC)
      Value      0
      Min        0
      Max      255
      Flat      15
    Event code 41 (?)
      Value     64
      Min        0
      Max      255
      Flat      15
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
  Event type 17 (EV_LED)
    Event code 0 (LED_NUML) state 0
    Event code 1 (LED_CAPSL) state 0
    Event code 2 (LED_SCROLLL) state 0
    Event code 3 (LED_COMPOSE) state 0
Properties:
Testing ... (interrupt to exit)
Event: time 1560373204.213064, type 4 (EV_MSC), code 4 (MSC_SCAN), value c0224
Event: time 1560373204.213064, type 1 (EV_KEY), code 158 (KEY_BACK), value 1
Event: time 1560373204.213064, -------------- SYN_REPORT ------------
Event: time 1560373204.494207, type 4 (EV_MSC), code 4 (MSC_SCAN), value c0224
Event: time 1560373204.494207, type 1 (EV_KEY), code 158 (KEY_BACK), value 0
Event: time 1560373204.494207, -------------- SYN_REPORT ------------
Event: time 1560373205.975452, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9000d
Event: time 1560373205.975452, type 1 (EV_KEY), code 316 (BTN_MODE), value 1
Event: time 1560373205.975452, -------------- SYN_REPORT ------------
Event: time 1560373205.976685, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9000d
Event: time 1560373205.976685, type 1 (EV_KEY), code 316 (BTN_MODE), value 0
Event: time 1560373205.976685, -------------- SYN_REPORT ------------
Event: time 1560373207.456727, type 4 (EV_MSC), code 4 (MSC_SCAN), value c0223
Event: time 1560373207.456727, type 1 (EV_KEY), code 172 (KEY_HOMEPAGE), value 1
Event: time 1560373207.456727, -------------- SYN_REPORT ------------
Event: time 1560373207.794199, type 4 (EV_MSC), code 4 (MSC_SCAN), value c0223
Event: time 1560373207.794199, type 1 (EV_KEY), code 172 (KEY_HOMEPAGE), value 0
Event: time 1560373207.794199, -------------- SYN_REPORT ------------
^C
</pre>
</details>

Rebinding any of these buttons to a face button such as Y makes them work, and this issue occurs in every game I've tried.

I am on Linux, specifically KDE neon (based on Ubuntu 18.04). I don't believe it's relevant but I'll throw in my specs as requested; CPU is a Ryzen 1700X, GPU is an XFX AMD Radeon RX 480 8G. Using the Vulkan graphics backend and LLVM recompilers for PPU and SPU, with Accurate xfloat enabled.

RPCS3.log from running [a homebrew gamepad tester](https://www.psx-place.com/threads/ps3-gamepad-test.144/) and pressing the three buttons in sequence four times (Select, PS, Start, Select, PS, Start, ...): https://gist.github.com/unascribed/768d7e8afb228806623c4bd7b5fa7203 (The buttons did not light up in the tester. Other buttons did, and the sticks move correctly. Also, I couldn't find an RPCS3.log file anywhere so instead I copied out of the log window with the level set to Trace; I hope this is equivalent.)

I unfortunately do not have any other controllers to test with. I searched the repo and forum for other issues that may be related, and found nothing.

**Comment by Megamouse** [comment]
Do these physical buttons work when you assign them to a face button instead?
Like Homepage Key to X

**Comment by unascribed** [comment]
Just tested; no.

**Comment by Megamouse** [comment]
funny that they mapped those shoulder buttons to gas and break XD

**Comment by unascribed** [comment]
The configuration I tested with, for clarity:
![screenshot](https://user-images.githubusercontent.com/6185037/59390361-dfd38b00-8d25-11e9-9802-6a222893a931.png)

Start now works by pressing X, but Square is no longer recognized as it's bound to Homepage.

Something I just noticed by accident is that pressing Homepage while Firefox is focused makes it, well, go to the homepage. Firefox probably isn't listening to controllers, so is it possible it's generating a keyboard event instead of a gamepad event...?

Completely guessing, I don't know very much about this.

**Comment by Megamouse** [comment]
Looking at the other weird names there isn't really a better alternative I guess XD

**Comment by Megamouse** [comment]
There's actually a possibility that those particular events are caught by another application.

**Comment by unascribed** [comment]
> At least they seem to use the proper axis minima and maxima

Nope, I had to do the absolute axis config thing to make this controller work right. Figured it wasn't relevant to buttons so I didn't mention it initially.

> There's actually a possibility that those particular events are caught by another application.

Hm. Like what? Firefox only goes to the homepage if it has the focus, and I can't think of any apps I have installed that'd listen for it.

**Comment by Megamouse** [comment]
are you using the travis builds or do you build from source?

**Comment by unascribed** [comment]
I'm using the AppImage from rpcs3.net; I'm currently updating my system so I can install the needed packages to build from source to try and poke at this myself.

**Comment by Megamouse** [comment]
no. there weren't any changes to evdev lately.
But in case you find the specific line where it seems to fail then just tell me.
I'll see if I can fix it then (I don't have that gamepad nor a linux distro installed but I wrote most of the code)

**Comment by unascribed** [comment]
I didn't think there'd been any changes, but I committed Issue Reporter Cardinal Sin #1: not running the latest version

Not sure how successful I'll be trying to fix this or isolate it myself, considering I only really know Java, but I fixed one bug in OBS one time, so clearly that means I'm an accomplished C++ developer and can fix this no sweat.

**Comment by Megamouse** [comment]
The ingame functions are:

Mapping to the virtual DualShock3: `evdev_joystick_handler::bindPadToDevice`
-> You could look at line 960 and see what `find_key(p_profile->start)` returns

The main input loop: `evdev_joystick_handler::ThreadProc`
-> You could try to see if button_code ever corresponds to your KEY_HOMEPAGE or such

The main loop gets the latest button press with: `evdev_joystick_handler::GetButtonInfo`

**Comment by unascribed** [comment]
The problem seems to be on line 555:
```c++
/* 555 */ if (code < BTN_MISC)
/* 556 */    return -1;
```

All keyboard-y buttons (like `KEY_BACK` and `KEY_HOMEPAGE`) are less than BTN_MISC; I'm not sure the purpose of this line, but it's almost certainly causing the issue. I'd test removing it, but I can't get RPCS3 to run when built from source. My Vulkan headers appear to be slightly too old, and if I disable Vulkan it builds, but I get various crashes; first in the logger, now in the PPU emulator due to not checking an Expected value before unwrapping it.

**Comment by Megamouse** [comment]
ugh I could've spared you the trouble if I had actually looked up the value last night. I kinda didnt see that Keys come _before_ and after the btns so I assumed they'd be bigger.
I think I only added the `code < BTN_MISC` as performance improvement because there was no reason to assume that gamepads use KEYs. (It was stated somewhere that gamepads should only use ABS and BTN).
I added the KEY_BACK and the KEY_HOMEPAGE later when I tested my own bluetooth xbox one controller on the pad settings dialog and probably forgot to remove that line (my laptop was never compatible so I couldn't test ingame). I think the cabled version actually uses BTN_BACK and BTN_SELECT or something like that.

**Comment by unascribed** [comment]
Used the Travis docker image and a bunch of messing around to build that PR; it indeed fixes my issue, and now I can hit Start and get past the title screen on Tools of Destruction. :P

I saw the PR adding the back/homepage keys for the Xbox One controller, which was why this issue kind of puzzled me at first; it looked like those keys were Supported™, but if you never got the chance to properly test it I guess that explains it.
