### ISSUE TITLE
OSK doesn't block input in Bound by Flame

### ISSUE THREAD

**Issue by 13xforever** [RPCS3/rpcs3#6082]
Problem: when you start new game in Bound by Flame (BLES01952 in my case), you can change character name.
With Native UI enabled, when you enter the name, as soon as you enter the first letter with ✕, your input is starting to get passed back to the game, meaning that you randomly change other options, and also can start a new game while still trying to enter the name.

Expected behavior: OSK blocks your input until you're finished entering the name with Start, or cancelled input with 〇.

![Trying to input a name](https://user-images.githubusercontent.com/36445/59413168-7496c100-8dd8-11e9-9bd9-86e8f3d715af.png)
![Going in game inadevertantly](https://user-images.githubusercontent.com/36445/59413172-7791b180-8dd8-11e9-92b4-d035f36b08f1.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3284749/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Maybe the game doesn't care for interception. Or it uses a function that doesn't pass that data. Or for some reason there's a bug that disables the interception.
