### ISSUE TITLE
Incorrect Start Emulation button behavior

### ISSUE THREAD

**Issue by 13xforever** [RPCS3/rpcs3#6083]
RPCS3 v0.0.6-8204-d361eedb

Problem: when you open RPCS3, **select some game**, and then press Start button in toolbar, it will launch **last played** game instead (as if you haven't selected anything).
Note that when you select any game in your library, Start button hint tooltip still says "Start last played game".

Expected behavior: selected game is launched.

Log for adding a new game, then selecting Dante's Inferno, then pressing the Start button in toolbar.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3284783/RPCS3.log.gz)

**Comment by Megamouse** [comment]
That button was always intended for restart though

**Comment by Megamouse** [comment]
And tbh I never heard of anyone using it that way XD It never even crossed my mind XD

**Comment by 13xforever** [comment]
Well, it looks like a Play button, so it kinda implies you can use it to start the game, but idk

**Comment by Megamouse** [comment]
Btw your issues sound very pragmatic :)

**Comment by Megamouse** [comment]
maybe make a poll

**Comment by elad335** [comment]
imo there should be some rewind buttom to start last played, I think there should be a button for each feature.

**Comment by Megamouse** [comment]
Please test the new version.
You can see details in the description of #7712

**Comment by 13xforever** [comment]
Yes it works as expected now
