### ISSUE TITLE
Stop emulation button wrong behavior

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#6086]
After fatal memory errors (Access violation writing\reading location) pressing "stop emulation" causes closing of entire application. May be this happens after all fatal errors, I don't know.

**Comment by AniLeo** [comment]
That's very likely a crash, not the stop emulation functionality. Try the same thing with any of the other buttons.

**Comment by RainbowCookie32** [comment]
Some games make the emulator crash after they froze/crash themselves. The Stop button should always close the game, not the emu. You can probably get the same behavior if you try to close the game's window

**Comment by Realmantik** [comment]
Only "Stop emulation" closes the applicaion, But I have noticed another strange behavior, game window is not closed after fatal error happens, play button is activated, I can press it and emu runs some instructions of the game with the same result, memory access violation writing location (I tested only Mountain Crime: Requital game)

**Comment by elad335** [comment]
It's intentional, but I can improve it to not crash in specific situations for PPU threads, but not all of them.

**Comment by elad335** [comment]
Play button is activated because Emu.Pause() is called immediatly afterwards. It also allows you to "replay" the violating memory access for debugging in case you suspect the memory was allocated afterwards.
