### ISSUE TITLE
rpcs3 crashes when trying to play persona 5 [BLUS31604]

### ISSUE THREAD

**Issue by sianhulo** [RPCS3/rpcs3#6087]
I'm on commit ac3982d2b0334bc2cbfd88b6e9b70ec5dc9bd48f but I also tried with the binary release of https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-a43e7c172c724378187c9b78a3fb94f3bda5c4a3/rpcs3-v0.0.6-7840-a43e7c17_linux64.AppImage

System: Archlinux x64
intel xeon E5450
8gb of ram
AMD HD 7770 (mesa 19.0.6)
LLVM 8.0.0

What happens: after clicking play and the game starts (flaming top hat loading icon appears) game crashes along with rpcs3, but process still need to be manually killed. Whether I use opengl or vulkan has no effect on this.

For PPU decoder and SPU Decoder I tried LLVM Recompiler and Interpreter, again, no change.

The log file shows a bunch of `{cellAudio Thread} cellAudio: Could not enqueue buffer onto audio backend. Attempting to recover...` before crashing, so it might be an audio problem. My system uses pulseaudio.

UPDATE
----
The game is still crashing, but I just noticed that I was using ALSA as a backend (I don't know how I missed it) instead of pulseaudio, the log changed a little bit but the behavior is the same, the game just crashes a few seconds after the loading icon.

New log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3288427/RPCS3.log)

**Comment by AniLeo** [comment]
Pirated release detected 

Removed log files and closing issue

**Comment by sianhulo** [comment]
I guess I should save for a bluray reader
