### ISSUE TITLE
Fist of the North Star: Ken’s Rage [BLES01062] high brightness ligt effect on characters

### ISSUE THREAD

**Issue by masaki1988** [RPCS3/rpcs3#6088]
When i go to sun light areas then, sun light effect looks having abnormally high brightness
effect on main character and enemys. When character or soldiers return to dark zones where not have sun light then, textures return to normal state.
![1](https://user-images.githubusercontent.com/19761504/59507360-7d0ffa00-8eb3-11e9-9872-7af1071a119d.jpg)
![2](https://user-images.githubusercontent.com/19761504/59507362-7d0ffa00-8eb3-11e9-89b9-abc06a0d2a25.jpg)
![3](https://user-images.githubusercontent.com/19761504/59507363-7da89080-8eb3-11e9-8621-2c6e1028a184.jpg)
![4](https://user-images.githubusercontent.com/19761504/59507364-7da89080-8eb3-11e9-8af7-f8836535b6aa.jpg)

My pc config 

Intel Core i7 7700k
gtx 1060 6gb driver 430.86
16gb ram ddr4
Windows 10 Home 1903 x64

Log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3290483/RPCS3.log.gz)

**Comment by masaki1988** [comment]
If i can help fix this issue then. let me know please if you need debug log.

**Comment by MsDarkLow** [comment]
Issue still persists
