### ISSUE TITLE
rsx: Failed Assertion in Texture Cache (Hyperdimension Neptunia Victory)

### ISSUE THREAD

**Issue by DracioFX** [RPCS3/rpcs3#6098]
RPCS3 v0.0.6-8256-b29a8980
Game crashes upon loading the combat sequence following a certain story event.
Error code varies a bit based on the renderer used:
OpenGL:

> F {RSX [0x00880b8]} RSX: class std::runtime_error thrown: Assertion failed: !cached.is_locked()
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\gltexturecache.h:807)

Vulkan:
> F {RSX [0x006c128]} RSX: class std::runtime_error thrown: Assertion failed: !region.is_locked()
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vktexturecache.h:951))

[RPCS3 OpenGL.zip](https://github.com/RPCS3/rpcs3/files/3294287/RPCS3.OpenGL.zip)
[RPCS3 Vulkan.zip](https://github.com/RPCS3/rpcs3/files/3294288/RPCS3.Vulkan.zip)
Save file included:
[SAVE.zip](https://github.com/RPCS3/rpcs3/files/3294290/SAVE.zip)

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/mcsEkRB0xC0/0.jpg)](https://www.youtube.com/watch?v=mcsEkRB0xC0)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/6512
