### ISSUE TITLE
Broken colors with AA Enabled on NVIDIA Kepler

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#6103]
Some users reported broken colors with AA Enabled on Skate 3, and that disabling AA fixes the issue

- GTX 760
- GTX 670
- GT 640

RSX Capture: https://drive.google.com/file/d/1umE-qLgY3RJ8t056fPejGmbsoV30eQQY/view (GT 640)

RSX Capture renders with correct colors for me on R9 280X

![](https://i.imgur.com/qJKMSPa.jpg)

**Comment by drysalter** [comment]
This also affects my GTX 760.

**Comment by kd-11** [comment]
I have a theory as to why this is happening, I'll push some commits for it soon.

**Comment by Cereal-Killa** [comment]
Same here, GTX 770.

Thanks!

**Comment by NovaPrima** [comment]
This happens with Tomb Raider Trilogy [BLES01195] too, but only with Vulkan.

![tomb2](https://user-images.githubusercontent.com/42202690/61927861-c2970b00-afb9-11e9-95c3-614fd2e4719e.jpg)
![tomb](https://user-images.githubusercontent.com/42202690/61927504-494ae880-afb8-11e9-8be7-69b8f35be747.jpg)

 v0.0.6-8416 Alpha [2019-07-25]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3434280/RPCS3.log.gz)

**Comment by leopard20** [comment]
Same issue in Catherine:
![Screenshot (22)](https://user-images.githubusercontent.com/16115820/63232106-0e944300-c23a-11e9-86da-9e26bf2c6bfd.png)

GTX 760m

**Comment by PaulBGD** [comment]
Happens with The Sly Collection (BCUS98246): https://www.youtube.com/watch?v=UPF7JkgBix0

Disabling anti-aliasing does fix it, or switching to OpenGL. There's more info in my previous issue linked above.

**Comment by AniLeo** [comment]
Still reported to be happening

**Comment by AniLeo** [comment]
@PaulBGD @leopard20 @NovaPrima @Cereal-Killa test with
https://ci.appveyor.com/api/buildjobs/lko1t51vi2rmibel/artifacts/rpcs3-v0.0.7-8894-89f582dd_win64.7z

**Comment by Cereal-Killa** [comment]
> @PaulBGD @leopard20 @NovaPrima @Cereal-Killa test with
> https://ci.appveyor.com/api/buildjobs/lko1t51vi2rmibel/artifacts/rpcs3-v0.0.7-8894-89f582dd_win64.7z

This build seems to freeze on my PC:

`E {RSX [0x000bcb0]} RSX: 
F {RSX [0x000bcb0]} RSX: class std::runtime_error thrown: Failed to compile compute shader
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:3210)`

I cleared all caches and retried, same exception gets thrown.

![gnqEGbcc5t](https://user-images.githubusercontent.com/25939765/66862416-3ae0ed00-ef67-11e9-87f7-b814dfd1e3c5.png)

![wuFq9j1LN7](https://user-images.githubusercontent.com/25939765/66862417-3ae0ed00-ef67-11e9-9dba-79d456a6c6ab.png)

**Comment by 13xforever** [comment]
please always provide full log instead of a screenshot

**Comment by Cereal-Killa** [comment]
> please always provide full log instead of a screenshot

Absolutely.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3731133/RPCS3.log.gz)

**Comment by kd-11** [comment]
New build compiling here https://ci.appveyor.com/project/kd-11/rpcs3/builds/28132087

**Comment by Cereal-Killa** [comment]
> New build compiling here https://ci.appveyor.com/project/kd-11/rpcs3/builds/28132087

Thank you.

First time I ran it the emulator terminated by itself, then I ran it again and this is how it rendered:

![1eWVYwRwiI](https://user-images.githubusercontent.com/25939765/66868395-9f09ae00-ef73-11e9-958b-630076de5688.png)

The "stable" branch renders like this for comparison:

![kjIunBQGta](https://user-images.githubusercontent.com/25939765/66868420-a9c44300-ef73-11e9-8752-33fb2e44da9c.png)

**Comment by Cereal-Killa** [comment]
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3731373/RPCS3.zip)

**Comment by kd-11** [comment]
It appears format conversion on these old cards is taken literally (which is completely wrong) and means a workaround is required in the shader.

**Comment by kd-11** [comment]
[This build](https://ci.appveyor.com/project/kd-11/rpcs3/builds/28134350/artifacts) works around this problem. Unfortunately, this also means I will need to gather chip IDs for maxwell and kepler cards since right now it is applied to all unknown nvidia cards and I have only registered pascal and up. I'll try and gather the required device IDs in the next day or two, since that will have to be merged before the workaround to avoid breaking things for everyone else.

**Comment by Cereal-Killa** [comment]
> [This build](https://ci.appveyor.com/project/kd-11/rpcs3/builds/28134350/artifacts) works around this problem. Unfortunately, this also means I will need to gather chip IDs for maxwell and kepler cards since right now it is applied to all unknown nvidia cards and I have only registered pascal and up. I'll try and gather the required device IDs in the next day or two, since that will have to be merged before the workaround to avoid breaking things for everyone else.

I appreciate your hard work.

10DE 1184 - 196E 1033

![LaLNKZMvH3](https://user-images.githubusercontent.com/25939765/66873092-f745ad80-ef7d-11e9-872d-5bfef63904b7.png)

**Comment by kd-11** [comment]
Check if it is fixed by https://github.com/RPCS3/rpcs3/pull/6780

**Comment by Cereal-Killa** [comment]
FYI, I get twice the FPS without AA.

![rpcs3_mBkroVwOom](https://user-images.githubusercontent.com/25939765/66935053-d333ac00-f011-11e9-94b9-1046246c814d.jpg)

**Comment by kd-11** [comment]
Thats a bit of an unfair comparison since MSAA is technically smart upscaling. Makes more sense to compare MSAA vs something like 200% scaling. Even then, due to some features missing from NVIDIA cards, they can perform very poorly at times.

**Comment by kd-11** [comment]
Closing as fixed.

**Comment by Cereal-Killa** [comment]
> Thats a bit of an unfair comparison since MSAA is technically smart upscaling. Makes more sense to compare MSAA vs something like 200% scaling. Even then, due to some features missing from NVIDIA cards, they can perform very poorly at times.

No problem man, just wanted to point that out in case it was something not expected, graphics look more or less the same even without AA considering the resolution.
Thank you

**Comment by kd-11** [comment]
There have been a few developments over the past 24h that tangentially relate to this ticket. Please check if MSAA still works ok on rpcs3's [latest master](https://ci.appveyor.com/project/rpcs3/rpcs3/builds/28550922) (wait about an hour for it to build). Alternatively, just test with the build from https://github.com/RPCS3/rpcs3/pull/6930

**Comment by Cereal-Killa** [comment]
> There have been a few developments over the past 24h that tangentially relate to this ticket. Please check if MSAA still works ok on rpcs3's [latest master](https://ci.appveyor.com/project/rpcs3/rpcs3/builds/28550922) (wait about an hour for it to build). Alternatively, just test with the build from #6930

The game ran incredibly well with AA set to Auto on this build, it's butter smooth really, only thing I noticed is that after reaching the menu the console will start throwing an endless exception:

`SPU[0x2000003] Thread (job Manager - Job Thread) Please report to the devloper (0x059e8).`

![rpcs3_dgPkpNKnhp](https://user-images.githubusercontent.com/25939765/68044962-2fa3f600-fcb7-11e9-8992-4837b12e48c9.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3799029/RPCS3.log.gz)

**Comment by Drayano** [comment]
Sorry for posting on this old issue but that's the first one that came up when doing a search on github issues, I know intel isn't technically supported but the same problem happens with my igpu (intel uhd 630), disabling aliasing fix it.

**Comment by levonnn** [comment]
Mortal Kombat II [NPUB30004] has the same issue.

**Comment by kd-11** [comment]
Please open new tickets with full details regarding your setup, this ticket is marked as closed.
