### ISSUE TITLE
Skate 3 - [BLES00760] White screen crash or fatal error

### ISSUE THREAD

**Issue by Chriktion** [RPCS3/rpcs3#6111]
I installed RPCS3 for the first time, intalled Skate 3 and when I runned it, it gave me this error message.
![Untitled](https://user-images.githubusercontent.com/52039973/59852370-58b29280-9377-11e9-8420-082c3a14e600.png)

Game:Skate 3 (Playable)
Specs:Windows 7 Home Premium
6GB RAM DDR3 (I think)
CPU: i7 Intel Core 870 2.93GHz
GPU: ATI Radeon HD 5750

I Love your emulator and keep up the good work!
Thank you.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
