### ISSUE TITLE
Unable to select specific gpu with same name

### ISSUE THREAD

**Issue by asl97** [RPCS3/rpcs3#6113]
#### Version (commit hash) of RPCS3 you are using.
rpcs3-v0.0.6-8271-517a2bc3_linux64.AppImage

#### Issue to be reproduced.
Having Multiple driver install result in multiple same name gpu resulting in being unable to select specific (newer) driver.

```
GPU0
VkPhysicalDeviceProperties:
===========================
        apiVersion     = 0x401060  (1.1.96)
        driverVersion  = 79691781 (0x4c00005)
        vendorID       = 0x8086
        deviceID       = 0x0166
        deviceType     = INTEGRATED_GPU
        deviceName     = Intel(R) Ivybridge Mobile

...
irrelevent info removed
...

FORMAT_D32_SFLOAT_S8_UINT:
        linearTiling   FormatFeatureFlags:
                None
        optimalTiling  FormatFeatureFlags:
                VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT
                VK_FORMAT_FEATURE_BLIT_SRC_BIT
                VK_FORMAT_FEATURE_BLIT_DST_BIT
                VK_FORMAT_FEATURE_TRANSFER_SRC_BIT_KHR
                VK_FORMAT_FEATURE_TRANSFER_DST_BIT_KHR
        bufferFeatures FormatFeatureFlags:
                None
```

```
GPU1
VkPhysicalDeviceProperties:
===========================
        apiVersion     = 0x401066  (1.1.102)
        driverVersion  = 79695971 (0x4c01063)
        vendorID       = 0x8086
        deviceID       = 0x0166
        deviceType     = INTEGRATED_GPU
        deviceName     = Intel(R) Ivybridge Mobile

...
irrelevent info removed
...

FORMAT_D32_SFLOAT_S8_UINT:
        linearTiling   FormatFeatureFlags:
                None
        optimalTiling  FormatFeatureFlags:
                VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT
                VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT
                VK_FORMAT_FEATURE_BLIT_SRC_BIT
                VK_FORMAT_FEATURE_BLIT_DST_BIT
                VK_FORMAT_FEATURE_TRANSFER_SRC_BIT_KHR
                VK_FORMAT_FEATURE_TRANSFER_DST_BIT_KHR
        bufferFeatures FormatFeatureFlags:
                None
```

##### Cause:
RPCS3 just use the name and not the driver version.
https://github.com/RPCS3/rpcs3/blob/790962425cfb893529f72b3ef0dd1424fcc42973/rpcs3/rpcs3qt/emu_settings.cpp#L165
So only the first gpu with the same name is selected.
https://github.com/RPCS3/rpcs3/blob/790962425cfb893529f72b3ef0dd1424fcc42973/rpcs3/rpcs3qt/emu_settings.cpp#L76-L78

#### System specs.
Some old Gen 7 intel cpu which probably isn't enough to run RPCS3 anyway but one could always hope.

#### Additional info
I gotten the error `No hardware support for z24s8`.
Which the required feature should just been added a few days ago.

https://github.com/RPCS3/rpcs3/blob/517a2bc34a6479ed011dff64d215c47dfae64614/rpcs3/Emu/RSX/VK/VKFormats.cpp#L18-L21

That's the reason I had multiple drivers.
https://bugs.freedesktop.org/show_bug.cgi?id=99493

**Comment by kd-11** [comment]
Tracking GPU with driver information is not feasible, the selection will immediately get lost whenever the driver version changes. Any concession made thereafter to try and prefer one driver over the other will always fail some simple case as well. For anyone having a similar situation, please use the VK_ICD_FILENAMES environment variable instead.
`VK_ICD_FILENAMES=path/to/driver/icd ./rpcs3`

**Comment by asl97** [comment]
This is definitely an unusual edge case,
IE: having more than 1 driver with the same name.

##### Causing the UI to show multiple gpu but regardless of which is selected, it would always use the first one.

Which I don't expect to be fixed, it's understandable.

Most system should only have drivers with unique name anyway.

<details>

> the selection will immediately get lost whenever the driver version changes.

If the driver version change, the user should be expected to check the config to make sure the right driver is selected, but a reasonable default could be selected.

Such as, if the selected driver version is no longer available, it should prioritize newer driver with same name, follow by default.

As such under normal cases, there should only be 1 driver per gpu so an implementation that takes into account the version as well shouldn't cause a problem.

Priorities:
1. Specified version
2. New drivers
3. Current implementation default.

<details>
<summary>Not the best pseudocode:</summary>

```python
# new drivers not seen before in last startup
new_drivers = drivers-seen_drivers
selected = None
# search in reversed order so the earlier driver get defaulted, same as current implementation
for driver in reverse(drivers):
    if driver.name == name:
        selected = driver
        # bail early if the selected version is found
        if driver.version == version:
             return driver

# check if there new drivers with the same name
for driver in new_drivers:
    if driver.name == name:
        return driver

return selected
```
</details>
</details>
