### ISSUE TITLE
Regression: Frame Skipping not working (#6069)

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#6114]
I really don't want to blame that rev because it fixed so many problems but the game works fine on
0.0.6-8202 and it instantly gets a fatal error when I try to run it with 0.0.6-8204 or newer

F {RSX [0x0000000]} RSX: class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkgsrender.cpp:3052)

Vulkan only and not gpu specific(crashes on nvidia and intel while using vulkan)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3311754/RPCS3.zip)

**Comment by kd-11** [comment]
Please update with a recent build. The error message must have changed since line 3052 no longer has an error check.

**Comment by vsub** [comment]
Now it is 3175 on RPCS3 v0.0.6-8330
F {RSX [0x0002b90]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkgsrender.cpp:3175)

[log.zip](https://github.com/RPCS3/rpcs3/files/3363213/log.zip)

But I find out why it is crashing
I enabled frame skipping(I enable it at least half a year ago and the game always worked)and something changed since 8204 that makes using frame skipping impossible.

I get the same fatal error on any game if that option is enabled while using anything newer than 8202

If this is not really a bug,then the issue can be closed

**Comment by kd-11** [comment]
Its a minor bug definately. Thanks, will push a fix for it soon.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/6164

**Comment by vsub** [comment]
Yes,fixed
