### ISSUE TITLE
The Legend of Heroes: ToCS2 - Clamping issues on vertex shader

### ISSUE THREAD

**Issue by alex88510** [RPCS3/rpcs3#6118]
I believe this issue has been there since the very early stage and not a regression from any recent PR.
I also believe the same issue also occurs on ToCS1. 

In some scenes, some of the objects (e.g. rooftops, the top of a train, top of a crate box) having abnormally high brightness. 
Below is an example of those, where some carpets in the room are very bright (as if the sun was shining at it).
![1](https://user-images.githubusercontent.com/6214348/59938317-3ad45300-9487-11e9-9ab0-55375f4ce15b.PNG)

Since it doesn't really affect the gameplay and only cause very minor graphic issue, I didn't bother to raise it previously.

EDIT: Let me know what is needed for debugging. Logs? renderdoc?

**Comment by PeterTh** [comment]
Interestingly enough, I think that's a bug I encountered and solved when porting the game to PC. IIRC, some shaders don't limit an intermediate value to the 0..1 range even though that was the intended behaviour (and apparently the hardware on PS3 did it).

**Comment by kd-11** [comment]
Yea, its a common problem with PS3. The real hardware is also very inconsistent on when it does apply clamping of inputs making this a complicated issue that needs testing via a bot. I have some work on this done but I've yet to have time to set up all required instructions / setups.

**Comment by alex88510** [comment]
Seems like it is an issue way more complicated than I expected.
Do you still need any logs/renderdoc for debugging?

**Comment by kd-11** [comment]
Rsx capture would help.

**Comment by masaki1988** [comment]
Same issue i think here https://github.com/RPCS3/rpcs3/issues/6088 but maybe im wrong.

**Comment by alex88510** [comment]
@kd-11 here you go https://mega.nz/#!DVxXza7B!Y_hGBiNmfDP5I6VhROToA5I4RSoCMqLHhXvB-Js_TJM

**Comment by alex88510** [comment]
It seems it was fixed either by the latest PR(#6388 ) or some other PR that got merged after this issue was raised (didn't keep track of it)

![image](https://user-images.githubusercontent.com/6214348/63631070-c5d2f480-c654-11e9-9333-5471b630b192.png)

If need me find out which exact PR that solve this, let me know. Otherwise, this can be closed?

**Comment by AniLeo** [comment]
If it's fixed on master, you can close

**Comment by RainbowCookie32** [comment]
If it's fixed then yeah, close it

**Comment by alex88510** [comment]
Ok, tested on latest master, it is not fixed...lol

![image](https://user-images.githubusercontent.com/6214348/63631138-e6e81500-c655-11e9-8e1c-eb47120ee43f.png)

Likely to be kd-11's MGS4 PR that fixes it.

**Comment by kd-11** [comment]
Yea the mgs4 PR implements autoclamping in som registers just as hypothesized. Took days of hardware tests to get them all but it seems to help a lot of games.

**Comment by greentop** [comment]
@kd-11 It's fixed from PR#6388

**Master:**
![Screenshot from 2019-08-24 04-17-52](https://user-images.githubusercontent.com/2325766/63638201-25300500-c653-11e9-858c-d6c8d827c94f.png)

**PR#6388:**
![Screenshot from 2019-08-24 09-37-10](https://user-images.githubusercontent.com/2325766/63638208-37aa3e80-c653-11e9-8217-a095a7cf2e99.png)

**Comment by alex88510** [comment]
Closing this as PR#6388 has been merged and fixed the issue.
