### ISSUE TITLE
Regression: Huge performance hit, ~40fps on NFL Blitz (#6056)

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#6121]
NFL Blitz (and probably some other games) saw a dramatic performance hit with PR https://github.com/RPCS3/rpcs3/pull/6056, making it run significantly worse than with TSX off even.

0.0.6-8266
TSX on: 20 fps
TSX off: 50 fps

0.0.6-8262 (build before)
TSX on: 60 fps

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3316983/RPCS3.log.gz)

**Comment by isJuhn** [comment]
retest with preferred spu threads auto

**Comment by Nekotekina** [comment]
Need to check results with SPU LLVM.

**Comment by digitaldude555** [comment]
SPU LLVM Auto - TSX On![Screenshot (3364)](https://user-images.githubusercontent.com/26138653/59967681-35821180-9536-11e9-9362-90d82ef303b2.png)

SPU LLVM Auto - TSX Off
![Screenshot (3366)](https://user-images.githubusercontent.com/26138653/59967691-4fbbef80-9536-11e9-9afd-a64158c0d01b.png)

No difference at least on my cpu.

**Comment by legend800** [comment]
Strange, here's my results on the latest master:

SPU LLVM+SPU threads Auto+TSX On = 10 fps
![2019-06-22 15_08_07-FPS_ 25 00 _ Vulkan _ 0 0 6-8274 _ NFL Blitz  NPUB30665](https://user-images.githubusercontent.com/20983844/59969381-e5d52300-9500-11e9-8956-4b9e77142de2.png)
[RPCS3-auto.log.gz](https://github.com/RPCS3/rpcs3/files/3317320/RPCS3-auto.log.gz)

SPU LLVM+SPU threads 2+TSX On = 20 fps
![2019-06-22 15_11_15-Window](https://user-images.githubusercontent.com/20983844/59969383-f08fb800-9500-11e9-86a1-50d413ed2c2f.png)
[RPCS3-spu2.log.gz](https://github.com/RPCS3/rpcs3/files/3317321/RPCS3-spu2.log.gz)

SPU LLVM+SPU threads 2+TSX Off = 50 fps
![2019-06-22 15_14_17-Window](https://user-images.githubusercontent.com/20983844/59969390-1ae17580-9501-11e9-81a2-ef59621cf04d.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3317322/RPCS3.log.gz)

This is the only game in my collection where spu auto is broken (only 30-40fps). Requires SPU threads=2 for proper speed (60fps).

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by digitaldude555** [comment]
Try with spu loop on.

**Comment by legend800** [comment]
It helps but only gets back to around 45fps on avg. - slowdowns still observed constantly. Whereas before the regression, it was a steady 60fps.

SPU LLVM+SPU threads 2+TSX On+SPU Loop = 45 fps
![2019-06-23 09_13_22-Window](https://user-images.githubusercontent.com/20983844/59979064-93931100-9597-11e9-8e3c-8752aabfeaec.png)

**Comment by legend800** [comment]
I can confirm this was fixed in the past week or so (on master).
