### ISSUE TITLE
Regression: Persona 5 freezes similarly to fullscreen crash (TSX Issues) 

### ISSUE THREAD

**Issue by blackecos** [RPCS3/rpcs3#6125]
Hi thanks for the great emulator! I hope I can explain the issue well enough.

After a random time of play P5 the game crashes. Unlike in the nvidia bug I can close the game window without rpcs3.exe.
"~~" a Discord-user have the same issue.

I tested 4 different versions of rpcs3:

rpcs3-v0.0.0.6-**8197**-3e620f14 (preview build)
This prev build was the release of the nvidia fix for the fullscreen errors with nvidia hardware.
This seems to be the only build where the crash doesn't appear. (same by "~~" -> 5 hours without crash)

**8272**
This build need some time to play before it crash.

All builds after **8272**
This builds crashes after 10-30 minutes

------------------------------------------------------

"~~" and me have sometime simular errors in log files:
I write sometime because the error doesn't appear every time.

·E 1:15:24.909721 {RSX [0x00b2938]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x403005A0

·E 0:36:29.511218 {RSX [0x00e99b8]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x403005A0
·! 0:36:59.819143 Stopping emulator

------------------------------------------------------

My hardware:
9900k - 1080 ti - 32 GB RAM

------------------------------------------------------

Hope you can help us / fix it

[secondcrash.log](https://github.com/RPCS3/rpcs3/files/3321258/secondcrash.log)
[third.log](https://github.com/RPCS3/rpcs3/files/3321260/third.log)
[third.gz](https://github.com/RPCS3/rpcs3/files/3321261/third.gz)
[fourth.gz](https://github.com/RPCS3/rpcs3/files/3321262/fourth.gz)
[fourth.log](https://github.com/RPCS3/rpcs3/files/3321263/fourth.log)

[log-~~.log](https://github.com/RPCS3/rpcs3/files/3321255/log-.log)

**Comment by GitArUs** [comment]
Looks like it started happening after commit 5d45a3e. Setting spu threads to auto maybe improves stability, but does not prevent these crashes.

**Comment by Thutnmrd** [comment]
Yup, happens to me as well.

**Comment by blackecos** [comment]
I already have SPU Threads on Auto. :)
At the moment I try ASMJIT Recompiler so far no crashes for me. I will test it for longer time.

**Comment by AniLeo** [comment]
>   SPU Block Size: Giga
One of your logs has this, stick to Safe

>   SPU loop detection: true
Try disabling this

Alternatively, try setting TSX to Disabled too, this is probably due to all the fuckery introduced by Intel's latest microcode which impacts performance in RPCS3 and Nekotekina is currently fixing

**Comment by blackecos** [comment]
Good evening!
After some hours of playtime it seems 2 ways prevents the crash:
1. Use ASMJIT Recompiler (faster) instead of LLVM
2. LLVM + TSX disabled

Seems to be stable with this settings so far.
Disable SPU loop detections didn't fix the crashes. :/

I have stable 58-60 FPS on both "ways" so I can't say what's the better solution at the moment.

**Comment by blackecos** [comment]
Hello guys after update to #8322 I got a new crash + error
Sry for double post but I need to push this thread ;(

Screenshot + Log

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3349478/RPCS3.log)
![NewError](https://user-images.githubusercontent.com/5955453/60504185-6c3bf280-9cc1-11e9-9e8c-c58ebb990d34.jpg)

**Comment by AmineI** [comment]
> Hello guys after update to #8322 I got a new crash + error (LLVM + TSX disabled)
> Sry for double post but I need to push this thread ;(
> 
> Screenshot + Log
> 
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/3349478/RPCS3.log)
> ![error2](https://user-images.githubusercontent.com/5955453/60505042-297b1a00-9cc3-11e9-907b-ba33c25fb6a3.jpg)

If TSX was disabled then you should create a new issue for this, as it's probably not the same problem.

**Comment by blackecos** [comment]
Seems to be fixed in the latest release, no crashes since hours. (Unhandeld Win32...)

TSX enabled still crashes ;)
But its okay for me the game runs smooth without it.

**Comment by Midergo** [comment]
It's not just you, I have the same issue with "enabled TSX", hope this get a fix in the future (keep the good work rpcs3 team), anyway I can play the game at solid 30fps (I don't like the glitches in 60fps patch so I'm ok with native framerate) but TSX is a good boost for others games (like gow 3).

**Comment by Midergo** [comment]
issue (TSX Freeze) seems to be fixed (at least for me) in lastest build 0.0.6-8330 (around 3 hours of play without freeze).

**Comment by blackecos** [comment]
TSX Freeze after 15 minutes here @8330 ;(

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3364018/RPCS3.log)

**Comment by Midergo** [comment]
update, around 4 hours of playing, happen again in build  0.0.6-8330... well, i´ll switch to the "stable settings" for now.

**Comment by raiderstudent** [comment]
I am also having issues with Persona 5.  In the second dungeon where you select the original painting.  Joker disappears while walking through this room and I lose complete control, essentially causing the game to freeze.  Has this happened to anyone else?
![Capture](https://user-images.githubusercontent.com/13390052/63651788-853fad80-c71e-11e9-8e16-b2c5ea719518.PNG)

**Comment by CrabLugo** [comment]
Maybe try to disable 60fps patch

**Comment by digitaldude555** [comment]
Still issue?

**Comment by dio-gh** [comment]
This was probably fixed already 100x over. Closeable.

**Comment by elad335** [comment]
closing as dio suggested.
