### ISSUE TITLE
Dynasty Warriors Gundam Reborn Crashing on Level Loading

### ISSUE THREAD

**Issue by AizerMortenort** [RPCS3/rpcs3#6126]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3321816/RPCS3.log)

So the game still crashes and this issue is not fixed for more than a year

**Comment by reaper185** [comment]
Indeed, this makes the game near unplayable. Most of the stages freeze right after cinematic intro or going to certain places in the stage with a memory access violation error.
Intel i7-7500u
Intel HD Graphics 620
16GB Ram

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3323286/RPCS3.log.gz)

**Comment by AizerMortenort** [comment]
seems like devs do not care so we will never be able to play this game outside real ps3

**Comment by reaper185** [comment]
I opened this issue more than a year ago #4522

**Comment by AniLeo** [comment]
Duplicate of #4522
