### ISSUE TITLE
FarCry Classic: loading game causes entire computer to freeze

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#6129]
Halfway through the loading screen before going ingame, the entire test computer system locks up and a reboot is necessary.  Note that I cannot provide logs because the system freezes prior to the point where they are commited to disk.

I'm not sure if this is related to the [other issue](https://github.com/RPCS3/rpcs3/issues/5968) I reported on this game but hopefully so.  I will leave the other issue open in case it isn't though.  At least the system freezing symptom was not apparent at that time that was tested.

Tested with commit 9ce7b8a401a133b864d6ddcb41d460af4ff857bc on Linux Mint 19.1 Cinnamon x64 with kernel 4.18, NVIDIA GTX 1070M 390.116

**Comment by Leopard1907** [comment]
Your driver is so old.

Add Padoka Stable PPA to your system and update it 430.26

https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/pkppa

https://devtalk.nvidia.com/default/topic/1046736/linux/nvidia-415-27-nvidia-nvidia-prime-5ec2b-timed-out-issue-system-hang-/

Your issue might be related to this , which was causing a system hang on Optimus laptops. Fixed on 418.56 era

**Comment by Shoegzer** [comment]
@Leopard1907 perfect, thanks.  I didn't realize they were so outdated, but I haven't checked in a while.  That seemed to have fixed this issue; however the other one as I've referenced above still exists unfortunately, so I can't close it yet.
