### ISSUE TITLE
Zen Pinball 2: Nothing displays at all

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#6130]
On loading Zen Pinball 2 [NPUB30573], nothing is displayed at all.  Is this one of the two games reported as "Nothing" in the progress reports?  Logfile is [here](https://github.com/RPCS3/rpcs3/files/3327044/rpcs3.log.zip).  Patching to 1.26 doesn't fix the issue.

Tested with commit 629eddfb9fd5fc5740b08deaf77965c1ec731044 on Linux Mint 19.3 Cinnamon x64 with kernel 5.3, NVIDIA GTX 1070M driver 440.59

**Comment by RainbowCookie32** [comment]
No, [it's listed as Playable](https://rpcs3.net/compatibility?g=zen+pinball). Check what users recommended on the thread for the game in the forums https://forums.rpcs3.net/thread-198779.html
Apparently the game needs framelimiter set to auto and CPU Blit. And some DLCs need updates to be installed as well

**Comment by Shoegzer** [comment]
It's really not though, at least on the test system here.  I set those options and I still get the same result (though those options apparently only resolve the game running too fast and not rending the menu properly anyway).  Also the DLC comment is only for updates to DLC itself - I'm testing the base game, none of the DLC is loaded here.

**Comment by digitaldude555** [comment]
![Screenshot (3389)](https://user-images.githubusercontent.com/26138653/60134034-484f4d00-97a7-11e9-82ed-8a9c9537fdef.png)

**Comment by Shoegzer** [comment]
@digitaldude555 as I said, not on this test system.  It could be a linux issue, I don't know.  I even updated my drivers to 430.26 and removed all caches but same result.

**Comment by digitaldude555** [comment]
Add the label linux then or ani can add @Shoegzer

**Comment by kd-11** [comment]
Pretty sure this is fixed. If problem persists, request to reopen.

**Comment by Shoegzer** [comment]
It's not fixed @kd-11, at least not on linux under the setup above.  I've updated the OP and added a few more details, and provide anything else you may need.  Please reopen.

**Comment by Shoegzer** [comment]
@kd-11 Okay this is fixed now, I'm not sure which commit fixed it (and no sense bisecting now) but it was something between commits 0361184930d8931246f12d1aeadaa1f916c80bf6 and deb6bd3e25f94311d1177df578e388111aa0f5e2.  There's still an issue with audio cutting out during gameplay but that's an issue I just discovered and will log separately so I can close this one.  Thanks for your help with this.
