### ISSUE TITLE
Yakuza Ishin Bad Upscaling

### ISSUE THREAD

**Issue by MsDarkLow** [RPCS3/rpcs3#6133]
i7-8700k | Windows 10 version 1903 | GTX 1070
RPCS3 v0.0.6-8261-d52953fc Alpha
(During the time of the writing, newer builds caused more issues unrelated to this PR and so this older build is used)

Yakuza Ishin seems to have really weird upscaling and I found two possible workarounds. One is trough ingame w/ fullscreen and the other is by using CPU Blit.
When using the workarounds the framerate is boosted and the RSX utilization goes up nearing 100%.
*Note: This also happens for Yakuza Dead Souls, 5, 0 and Kiwami.*

The game is upscaled to 4k
This is how it normally looks w/ the upscale
![Normal](https://user-images.githubusercontent.com/9060436/60146494-b6a10900-97c1-11e9-9ae0-c3372a751836.jpg)

Through Ingame&fullscreen workaround
![Upscaling Ingame Workaround](https://user-images.githubusercontent.com/9060436/60146511-c7517f00-97c1-11e9-9baa-70d6ab711a3c.jpg)

Through CPU Blit
![Upscaling CPU Blit](https://user-images.githubusercontent.com/9060436/60146527-dc2e1280-97c1-11e9-8faf-fb07f0069377.jpg)

Ingame workaround and cpu blit show similar results.

To do the ingame workaround you must:
1. Be playing at fullscreen
2. Encounter a fight
3. Fight till the end and hope the upscale workaround works.

This method doesn't always work, sometimes it gets the upscale to work only by a split second. It remains for the rest of the playthrough OR until you change the windowed mode.
Got some video examples to explain better. (Recorded at 1080p but rendered at 4k due to the youtube's lower bitrate)
- When it works: https://youtu.be/fNw93i4a2GU
- When its by a splitsecond: https://youtu.be/9mKf44PKXG0
- When it works but you go back to windowed mode: https://youtu.be/1iF4YwEz_jw

Using CPU Blit doesn't require to go ingame and do a battle for the upscale to work better but it introduces to visual bugs during combat and cutscenes.
*Note: The visual bugs don't occur in Dead Souls and 5*
- Example during combat: https://youtu.be/B8N6yD_bTBs

Log of attempting to do the ingame workaround:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3327960/RPCS3.log.gz)

**Comment by kd-11** [comment]
This is a game bug. ~~Possible trolling by developers.~~
A workaround will be investigated but I'm closing this as its not a problem with the emulator.
