### ISSUE TITLE
Regressions caused by #6112 (optimizations)

### ISSUE THREAD

**Issue by jacob1218** [RPCS3/rpcs3#6135]
There seems to be a regression after https://github.com/RPCS3/rpcs3/pull/6112 . Gran Turismo 6 used to go ingame, now crashing on car select or hanging after it displays the name of the track. Log attached.
[RPCS3 hang.log.gz](https://github.com/RPCS3/rpcs3/files/3332282/RPCS3.hang.log.gz)

**Comment by legend800** [comment]
Same thing happens in Wipeout HD now too.

**Comment by kd-11** [comment]
It would be better to not restart the game over and over in the same instance. It would also be much more helpful to have a log with a crash instead of a silent hang. If this is really related to the wipeout issue, then [this build](https://ci.appveyor.com/project/kd-11/rpcs3/builds/25560620/artifacts) should hide the issue. It will take a long time to finish though.

**Comment by jacob1218** [comment]
With that new build, still hung. Clean log posted
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3336335/RPCS3.log.gz)

**Comment by legend800** [comment]
Wipeout (which may be a diff. issue) still hangs as well.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3337672/RPCS3.zip)

**Comment by Emulator-Team-2** [comment]
@jacob1218 
Did you try to disable `Multithreaded RSX` option?
Your processor doesn't have enough cores. 
From KD-11:
`A quad core cannot handle RSX multithreading as of now. Its meant for wider Ryzens or the newer hexacore and octacore intel chips which have enough resources to spare.`

**Comment by kd-11** [comment]
New build with the issue properly fixed. https://ci.appveyor.com/project/kd-11/rpcs3/builds/25622170
The commits are still a bit rough, I'll try and clean them up in the next few days for a PR. Multiple issues were identified, some introduced with optimizations and others existing even before that.

**Comment by kd-11** [comment]
I've upgraded this ticket to handle all regressions from optimizations PR as they are likely all related.

**Comment by legend800** [comment]
Wipeout HD fine again on fix build:

![2019-06-28 19_22_29-FPS_ 59 97 _ Vulkan _ 0 0 6-8303 _ WipEout® HD  NPUA80105](https://user-images.githubusercontent.com/20983844/60378647-39041580-99da-11e9-8355-9a109cee9fc0.png)

**Comment by incognitoh** [comment]
big regression in MLB 2k7.  Before #6112 , the game was almost perfect but #6112 broke it quite a bit. This title requires WCB and cpublit but looked good prior to this PR. The game uses a lot of zoom-in and DOF effects which is what seems to be the issue. I've tried with Async,  MSAA and Multi RSX disabled and enabled but the issue remains and is a constant issue throughout this game. here are a couple quick comparison gifs of the issue, using Vulkan:

Before #6112: 
![01](https://user-images.githubusercontent.com/39333810/60401280-d5e6c000-9b4c-11e9-9058-223d8116e466.gif)



After #6112 
![02](https://user-images.githubusercontent.com/39333810/60401286-fa429c80-9b4c-11e9-87ee-e5734e0a6b4d.gif)

(gtx1070 gpu)

**Comment by kd-11** [comment]
@incognitoh Please provide comparison renderdoc traces with renderdoc 1.4
