### ISSUE TITLE
Expected<T> must be checked before access or destruction.

### ISSUE THREAD

**Issue by John-Gee** [RPCS3/rpcs3#6139]
Hello,

for the past couple days my builds of RPCS3 crash when starting a game, whereas the appimages work fine.

Current commit built from: https://github.com/RPCS3/rpcs3/commit/1641be5e0cf2f1ab7cca8351a32cbc992e4e129e

The gdb backtrace with a debug build is:

Expected<T> must be checked before access or destruction.
Expected<T> value was in success state. (Note: Expected<T> values in success mode must still be checked prior to being destroyed).

Thread 19 "PPU[0x1000000] " received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff237fe700 (LWP 3411)]
0x00007ffff7a83755 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7a83755 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7a6e851 in abort () from /usr/lib/libc.so.6
#2  0x000000000196857b in llvm::Expected<std::unique_ptr<llvm::object::ObjectFile, std::default_delete<llvm::object::ObjectFile> > >::fatalUncheckedExpected (this=this@entry=0x7fff237fd370) at /usr/include/c++/9.1.0/bits/unique_ptr.h:357
#3  0x0000000001969d88 in llvm::Expected<std::unique_ptr<llvm::object::ObjectFile, std::default_delete<llvm::object::ObjectFile> > >::assertIsChecked (this=0x7fff237fd370) at /usr/include/c++/9.1.0/bits/unique_ptr.h:75
#4  llvm::Expected<std::unique_ptr<llvm::object::ObjectFile, std::default_delete<llvm::object::ObjectFile> > >::get (
    this=0x7fff237fd370) at rpcs3-git/src/rpcs3/llvm/include/llvm/Support/Error.h:533
#5  jit_compiler::add (this=<optimized out>, path=...) at rpcs3-git/src/rpcs3/Utilities/JIT.cpp:826
#6  0x0000000001941755 in ppu_initialize (info=...) at /usr/include/c++/9.1.0/bits/shared_ptr_base.h:1020
#7  0x000000000194367c in ppu_initialize () at rpcs3-git/src/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:1309
#8  ppu_thread::cpu_task (this=0x65c7aa0) at rpcs3-git/src/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:583
#9  0x000000000181fe44 in cpu_thread::operator() (this=0x65c7aa0)
    at rpcs3-git/src/rpcs3/rpcs3/Emu/CPU/CPUThread.cpp:148
#10 0x0000000001918cae in named_thread<ppu_thread>::entry_point (this=0x65c7aa0)
    at rpcs3-git/src/rpcs3/rpcs3/../Utilities/Thread.h:322
#11 named_thread<ppu_thread>::entry_point (arg=<optimized out>)
    at rpcs3-git/src/rpcs3/rpcs3/../Utilities/Thread.h:294
#12 0x00007ffff7c1557f in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007ffff7b450e3 in clone () from /usr/lib/libc.so.6

I'm guessing that means 

void jit_compiler::add(const std::string& path)
{
	m_engine->addObjectFile(std::move(llvm::object::ObjectFile::createObjectFile(*ObjectCache::load(path)).get()));
}

should be changed to check the Expected, but this function has not been changed in years so maybe not. It might be related to something on my computer instead.

I run Arch Linux with llvm builds from git, though I believe rpcs3 still use its own llvm and not my system's.

As always, I'm happy to dig into that with a little help.
Thanks!

**Comment by RainbowCookie32** [comment]
Is this still an issue for you? 
I build RPCS3 on Manjaro and I've never had any different behavior when compared to AppImages.
