### ISSUE TITLE
Ninja Gaiden Sigma 2[BLAS50160] Final Boss FPS low for WIN10

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#6140]
Ninja Gaiden Sigma 2[BLAS50160] Final Boss almost 10 fps for WIN10. But full speed(60 FPS) for WIN7! Hope to be fixed it , thanks!

![未标题-1](https://user-images.githubusercontent.com/47111657/60340264-a5ccdf00-99dd-11e9-9064-468e3e9d1e0a.jpg)
WIN10

![f29d38c79f3df8dcdc029970c311728b461028e1](https://user-images.githubusercontent.com/47111657/60340280-aebdb080-99dd-11e9-9362-993a6dbcef19.jpg)
WIN7

Both WIN10 and WIN7 were tested at 8700K

**Comment by Margen67** [comment]
You're using different builds in those screenshots..

**Comment by arcadee1977** [comment]
> You're using different builds in those screenshots..

The test is accurate, and the WIN7 picture is the test results of other people cited (because I only have WIN10)

**Comment by AniLeo** [comment]
No, not only the builds are too far apart, neither of them is recent, and also they're not done on the same hardware as you just made clear

This is more than invalid for these three reasons

**Comment by arcadee1977** [comment]
This issue is fixed now
