### ISSUE TITLE
Regression: Verification failed (0): sys_spu.cpp:1341 [BLJM61322] (#6143)

### ISSUE THREAD

**Issue by rdeleonp** [RPCS3/rpcs3#6145]
Log attached.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3341340/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
Does it also happen with SPU Block Size set to Mega? Giga can be (is) unstable

**Comment by rdeleonp** [comment]
> _Does it also happen with SPU Block Size set to Mega? Giga can be (is) unstable_

It happens with both _Safe_ and _Mega_.
