### ISSUE TITLE
tools of destruction regresses after v0.0.6 8300 [BCES00052]

### ISSUE THREAD

**Issue by allhailbilloverbeck** [RPCS3/rpcs3#6149]
tools of destruction no longer gets ingame with the resolution on anything other than 1280x720, at 720x576 and 720x480 the game simply hangs upon loading into a planet displaying nothing but a black screen and no sound. changing to SPU asmjit or other than SPU LLVM doesnt help.
one other issue is the game isnt really playable at 1280x720 because if the aspect ratio of the game window doesnt match your monitors aspect ratio it simply freezes randomly with no error message while audio still plays, so i have to play at 720x576 to match my monitors 5:4 aspect ratio, but the recent PR #8300 prevents this from being possible due to the hanging issue. the issue with random freezing at other aspect ratios has been around for a while and is not an issue with #8300

specs
amd fx 6300  6 core processor
nvidia 1050ti
8gb ddr3 ram
windows 7 sp1
latest nvidia drivers
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3342409/RPCS3.log)

**Comment by AniLeo** [comment]
v0.0.6-8300 is not a contender for regression report since it literally only adds a BOM on vm.cpp.

Needs proper regression report indicating the actual PR regressing it.

**Comment by RainbowCookie32** [comment]
Can't reproduce, I just got Ingame with 720x480. Ryzen 7 1700, RX 570
![Rc](https://user-images.githubusercontent.com/16805474/60391549-41864a00-9ac7-11e9-97ab-3924515a6543.jpg)

**Comment by allhailbilloverbeck** [comment]
found the PR that broke it
https://github.com/RPCS3/rpcs3/pull/6112

**Comment by allhailbilloverbeck** [comment]
also just wondering, what was you settings that got you ingame? are they just the default settings with the resolution changed to 720x420 and 720x576?

**Comment by RainbowCookie32** [comment]
Yep. Defaults, Vulkan and the changed resolution

**Comment by allhailbilloverbeck** [comment]
okay ill try that quickly

**Comment by allhailbilloverbeck** [comment]
okay, thats odd. works all of a sudden now, and i KNOW the settings were default before.
