### ISSUE TITLE
Persona 5 (Vulkan): native fp16 has graphical glitches on Vega (RADV and AMDVLK)

### ISSUE THREAD

**Issue by aqxa1** [RPCS3/rpcs3#6150]
### Description
With a Vega 56 on Linux, native fp16 support exhibits graphical glitches (glitches and inaccurate colours).

Screenshot with latest RPCS3 git (using Mesa RADV git, although the symptoms are the same with AMDVLK):
![Native fp16 enabled](https://i.imgur.com/NOyfaN7.jpg)

Screenshot when disabling native fp16 with Vulkan (shader_types_support.allow_float16 = false) (or reverting to a build before PR #5860):
![No native fp16](https://i.imgur.com/7oYKdBi.jpg)

Here's an [RSX capture](https://drive.google.com/file/d/1yq4ePlT7xud0DRdxYu4PvR8kkeipxOGR/view?usp=sharing) although I couldn't figure how to replay it, so I'm not sure if it's valid.

Bug does not affect an RX 550 (so looks to be Vega specific) and also doesn't affect the OGL renderer for either card. 

### System information

Gentoo Linux AMD64
RX Vega 56
Mesa RADV Git (LLVM 9)
RPCS3 git  - 43f919c04b6f6ce6bad1cf61d9e641147d5f4475

**Comment by kd-11** [comment]
There is already a config option for this in the yml file. You don't need to edit code.
Does this also happen on windows? Looks like vega has even more hw issues than expected. Need more people with similar issues to come forward so we can find the common denominator. Fp16 can be forcefully disabled on vega in such a situation.

**Comment by aqxa1** [comment]
>Does this also happen on windows? 
Not sure, I haven't booted Windows in a while, but I can test it.

**Comment by aqxa1** [comment]
Bug doesn't appear on Windows, with AMD drivers 19.2.3 and 19.6.3.

**Comment by kd-11** [comment]
The engine uses FP16 heavily, the only thing that can cause that issue is incorrect handling of extended values e.g clamp(NaN, x, y) which should return NaN. This must be something with the codegen, so its likely another LLVM bug. The patch removes some post-processing effects that can generate NaN values which the game does handle properly by itself but if the codegen incorrectly handles NaNs and INFs then we have to just disable that path entirely.

**Comment by aqxa1** [comment]
I submitted a RADV bug report here: https://bugs.freedesktop.org/show_bug.cgi?id=111039

**Comment by aqxa1** [comment]
Workaround, use the experimental [ACO shader compiler](https://github.com/daniel-schuermann/mesa) (make sure it's a recent compile as a bug was fixed that prevented the game from launching).

I can't say if it introduces other bugs, but it does workaround this particular problem.

**Comment by kd-11** [comment]
Workaround included in https://github.com/RPCS3/rpcs3/pull/6164

**Comment by aqxa1** [comment]
It would be nice to keep it enabled with ACO at least (the driver string includes "ACO"), although I guess you don't want to keep too many driver overrides in the codebase.

**Comment by Whatcookie** [comment]
ACO doesn't support native half floats yet, so it won't make a difference for now.
see: https://vulkan.gpuinfo.org/displayreport.php?id=6274#extensions (We're looking for the VK_KHR_shader_float16_int8 extension) 
Needs retesting after they expose half float support. 

If it works on windows, then it likely works on AMDGPU-PRO as well, however the device string reported is exactly the same as amdvlk, so sadly we can't filter between these drivers by device string.

I used this PKGBUILD to install AMDGPU-PRO on my system: https://github.com/Tk-Glitch/PKGBUILDS/tree/master/amdgpu-pro-vulkan-only
Obviously you can't use the PKGBUILD itself on gentoo, but you can manually follow the steps in the script to extract it from the .deb and try it for yourself.

**Comment by aqxa1** [comment]
Ah okay, that makes sense. So it's only working with ACO because it doesn't support the feature yet, and is falling back to the non-native form.
