### ISSUE TITLE
Freeze persona 5 PPU[0x1000003]-[0x012f948c]} 'sys_spu_thread_group_join' failed with 0x00000000

### ISSUE THREAD

**Issue by Midergo** [RPCS3/rpcs3#6154]
line in log when freeze "E {PPU[0x1000003] Thread (gfdSpursSpursHdlr0) [0x012f948c]} 'sys_spu_thread_group_join' failed with 0x00000000 : 0 [1]"

My Setup:
I7 6700k @4.4Ghz (stable Oc)
Asrock Fatal1ty z270 k4 (bios 2.0, vulnerabilities unpatched)
16Gb ram T-force Delta @3200Mhz dual channel
Rx480 8Gb (asus rog) driver 19.6.3 (lastest)

-game and emulator in SSD kingston Sata (not m.2)
-rpcs3 6146 (lastest, also tested in 6128... i did not tested other versions)
-i can stop/pause/full screen/windowed the emulation when it freeze but can not recover from that point (the game still freeze no matter what i do)
-it happen randomly but always when "some time passed", like... 15-40 min gameplay
-it happen with/without thead scheduler

![Sin título](https://user-images.githubusercontent.com/52369354/60394429-2aa91d00-9af2-11e9-91c8-c4398c0e37e5.png)

New Logs (correct ones)
Log.gz from rpcs3 folder
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3343397/RPCS3.log.gz)
Log.txt from rpcs3 folder
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3343398/RPCS3.log)

(old log)
copy paste log rpcs3.exe
[freeze.txt](https://github.com/RPCS3/rpcs3/files/3342671/freeze.txt)

i dont know if i "miss" something... pls tell me if i did. 

and thx in advandce, ur work is awesome except for this the emulator runs flawless (some little glitch here and there but nothing really important).

**Comment by elad335** [comment]
Should be fixed as of latest master.

**Comment by RainbowCookie32** [comment]
Is it consistent? I just played an hour or two on latest master and I couldn't reproduce it. I did get one freeze the other day, but I updated since then

**Comment by Midergo** [comment]
> Is it consistent? I just played an hour or two on latest master and I couldn't reproduce it. I did get one freeze the other day, but I updated since then

yeah, i have been testing a lot since yesterday and now i think i got the problem... is something to do with the "TSX", no matter what settings i use the problem persist but if i disable "TSX" seems like it do not happen anymore (over 4 hours playing with no freeze)... for now i´m playing without TSX but there are places were i get low fps without it so... hope this get a fix in the future, i will try older bulds with "TSX related fixed" and see what happen.

**Comment by RainbowCookie32** [comment]
Just checked the log, duplicate of #6125

**Comment by Midergo** [comment]
> Just checked the log, duplicate of #6125

yeah, seems to be the same case, actually i´m testing his second settings"LLVM + TSX disable" and looks like it work (around two hours without freeze), i´ll wait for a fix and thx for the "link" with that info, that may help more people with the same issue.

**Comment by Asinin3** [comment]
If you know it's a duplicate then why didn't you close the issue? 😕 No need to wait for one of the maintainers to come and close it for you
