### ISSUE TITLE
CPU usage increase while paused

### ISSUE THREAD

**Issue by asl97** [RPCS3/rpcs3#6161]
#### Version (commit hash) of RPCS3 you are using.
4c2fb54b9961dea6fba3daff07135c28e16924e9

#### Issue to be reproduced.
CPU usage higher when pause compare to when running.

Step to reproduce:
1. Find a simple game or homebrew, I used this hello world:
https://github.com/RPCS3/rpcs3/blob/baea02901bb8bc2ffc9fc5259666879b857d320d/bin/dev_hdd0/game/TEST12345/USRDIR/gs_gcm_hello_world.elf

2. Notice how it used one core (100% in top)

3. Click the pause button (which sets `G-PAUSE`)

4. Notice how CPU usage increased to two core (200% in top)

#### System specs.
Should be irrelevant.

#### Additional info
`pref top` shows `cpu_thread::check_state` is the cause, seem like a busy wait issue somewhere.

**Comment by Nekotekina** [comment]
Can't reproduce, it might be fixed. Feel free to open if not.
