### ISSUE TITLE
NPEA00088 Ratchet and Clank Quest for Booty crashes rpcs3

### ISSUE THREAD

**Issue by arabek** [RPCS3/rpcs3#6166]
Game crashes before going ingame (menus work).

Log: [NPEA00088-RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3364613/NPEA00088-RPCS3.log.gz)

**Comment by AniLeo** [comment]
This should be reported on our Game Tracker as indicated on our guidelines, as it is a compatibility report and not a specific issue report, a crash is very vague. If this is a regression, you can open a regression ticket mentioning what build regressed this game.

**Comment by benzoahoj** [comment]
still have this problem
