### ISSUE TITLE
Intel Driver Incompatibility With RPCS3

### ISSUE THREAD

**Issue by reaper185** [RPCS3/rpcs3#6170]
I have had this issue for some time now. If I update do the newer Intel DCH drivers Rpcs3 wont open, it will run on background only. If I use legacy drivers it runs fine. The driver that im using is 22.20.16.4815. The latest driver right now is 26.20.100.6912

Intel I7-7500u
Intel HD Graphics 620

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3365800/RPCS3.log.gz)

**Comment by MSuih** [comment]
Test with version that includes #6138 (0.0.6-8312 or later) and see if the error dialog pops up.

**Comment by proganime1200** [comment]
clean install the driver install the vcredist and vulkan sdk

**Comment by windyboy1704** [comment]
That’s weird, I also have 620 but I don’t have any issue with latest DCH versions. They make RPCS3 compile shader faster than older ones.

**Comment by reaper185** [comment]
Will try later today

**Comment by reaper185** [comment]
With latest Rpcs3 and latest driver I get this now
![Untitled](https://user-images.githubusercontent.com/39013260/60931558-c8c58180-a26e-11e9-958f-af40d2b77303.jpg)

If I hit abort this error appears
![Untitled1](https://user-images.githubusercontent.com/39013260/60931597-ee528b00-a26e-11e9-8a2d-0cbfa1081766.jpg)

**Comment by kd-11** [comment]
amdvlk.dll is an AMD driver. Why is that in your system? Wipe your old driver stack with DDU before reinstalling.

**Comment by windyboy1704** [comment]
Maybe you should uninstall GPU driver completely with *DDU uninstaller* from Guru3D. Then install the driver again

**Comment by reaper185** [comment]
My pc has 2 Graphic cards. Intel Hd Graphics 620 and AMD Radeon R7 M440. The AMD card is always disabled since games run worst with it. Before al of this I had reinstalled my computer from scratch already. Just in case I also updated the AMD GPU

**Comment by AniLeo** [comment]
This doesn't look like a RPCS3 issue, more like an OS issue with Vulkan registry

**Comment by kd-11** [comment]
If you have disabled the AMD GPU, uninstall the AMD drivers.
The AMD drivers are hanging rpcs3 because they are waiting for your AMD card to respond. Besides, you should be able to select which GPU to use for games in OS settings if you're on windows 10.

**Comment by proganime1200** [comment]
select the your main gpu not the disabled one

**Comment by kd-11** [comment]
This is not our bug.
