### ISSUE TITLE
Regressions from: (rsx: Refactor rsx_decode.h and bugfixes) #6168

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#6176]
@elad335 

Samurai Warriors 4:  ( Black background in character section  /  Black sky )

**[0.0.6-8336]**
![1S-2](https://user-images.githubusercontent.com/38318848/60913374-878d9b80-a287-11e9-8197-031b9b6a9d95.png)

**[ 0.0.6-8339 ]** #6168 
![1S](https://user-images.githubusercontent.com/38318848/60913309-6462ec00-a287-11e9-8b1f-8d53ee89846d.png)

**Log:**  [SW4-RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3374383/SW4-RPCS3.zip)

---------------------------------------------------------------------------------------------------

Skate 3:  ( Black screen on the title screen and in the menu  /  Black sky )

**[0.0.6-8336]**
![2-2](https://user-images.githubusercontent.com/38318848/60913497-d6d3cc00-a287-11e9-9e90-ff867029c0ea.png)

**[ 0.0.6-8339 ]** #6168 
![2](https://user-images.githubusercontent.com/38318848/60913488-ce7b9100-a287-11e9-8087-b2c4c4337aa6.png)

**Log:**  [S3-RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3374376/S3-RPCS3.zip)

**Comment by elad335** [comment]
Not enough people test my prs, but regardless I'll look into it.

**Comment by elad335** [comment]
Found it.

**Comment by Xcedf** [comment]
Confirm this regression, also happened in Uncharted 2, and confir it fixed ofr U2 with https://github.com/RPCS3/rpcs3/pull/6173

**Comment by Emulator-Team-2** [comment]
Samurai Warriors 4 /  Skate 3 fixed by  rsx: Typo fix #6177
