### ISSUE TITLE
IDOLM@STER: One For All black screen in-game with HUD since 0.0.6-8253

### ISSUE THREAD

**Issue by waddicto** [RPCS3/rpcs3#6181]
Ever since release 0.0.6-8253 (PR #6055), IDOLM@STER OFA has been showing a black screen in place of gameplay, with the game seemingly working perfectly behind the black scenes. Menus work, as well as appeals and subtitles still show up.
after 8253 vs before
![image](https://user-images.githubusercontent.com/8264967/60931320-21a11400-a287-11e9-97e2-64c567b17fef.png)

for comparison, 0.0.6-8231 
![image](https://user-images.githubusercontent.com/8264967/60931345-3a112e80-a287-11e9-8671-465a9fcf2162.png)

i've included logs of both versions
0.0.6-8253 [RPCS3.log](https://github.com/RPCS3/rpcs3/files/3375210/RPCS3.log)
0.0.6-8231 [RPCS3.log](https://github.com/RPCS3/rpcs3/files/3375229/RPCS3.log)

there is no FPS difference between either version

the same thing happens on the latest version (0.0.6-8350 as of right now)
![image](https://user-images.githubusercontent.com/8264967/60931363-52814900-a287-11e9-8344-891e9e757723.png)

my PC has a Ryzen 5 2600 an RX580 4GB and 8GB of RAM

**Comment by kd-11** [comment]
What happens if you set MSAA to Disabled? How about OpenGL which does not have MSAA implemented?

**Comment by waddicto** [comment]
I get the same result with MSAA set to off but it works fine on OpenGL

**Comment by waddicto** [comment]
something i noticed, if i set the amount of girls on stage to a lighter amount (in this case just one) i get an intermittent image where it shows for a bit but then goes black again

i uploaded some videos to compare the two versions
https://streamable.com/xarex here is the latest version (8365)
https://streamable.com/5ywds here is 8231

i don't know why it shows a little with less girls instead of straight up five but it might be related to the load since having five girls on stage is really laggy

**Comment by kd-11** [comment]
You need to provide RSX capture file of the scene.

**Comment by waddicto** [comment]
how do i do that?

**Comment by MSuih** [comment]
1. `View -> Show Debugger`. You can detach the debugger from the main window if you want.
2. Start the game and wait untill you get to the part that has the visual error shown on screen
3. Press `RSX Capture` button on debugger, this will create a rrc file in captures folder.
4. Close the emulator, start it again and then check that the capture works with `Utilities -> Open RSX Capture`
5. Compress the capture, upload it to file sharing site (f.ex. megaupload or google drive) and share a link to it here.

**Comment by waddicto** [comment]
[BLJS10260_20190716005742_capture.zip](https://github.com/RPCS3/rpcs3/files/3395370/BLJS10260_20190716005742_capture.zip)

that's the latest version

something else i noticed: the RSX capture seems to show the full image even though i'm only seeing black when actually playing, i can't get the capture to display just a straight up black screen

**Comment by waddicto** [comment]
my apologies, i just realized i never sent a version of the capture for 8231
[BLJS10260_20190716012226_capture.zip](https://github.com/RPCS3/rpcs3/files/3395446/BLJS10260_20190716012226_capture.zip)

**Comment by kd-11** [comment]
Seems to work fine. I'll check if its some windows bug or something.
![image](https://user-images.githubusercontent.com/15904127/63973654-de5b6880-cab3-11e9-83d9-035d061e1096.png)

**Comment by kd-11** [comment]
Windows is also fine. Nothing looks off with your settings so idk whats up with your system. Try deleting all the caches and recreating them.
I have very similar hardware and drivers: Ryzen 1700, RX 470 on same vulkan driver 2.0.99.

**Comment by waddicto** [comment]
did you try the stage mode? i just tried the story mode after deleting the cache (hadn't given it a thought before, my apologies) and the visual novel parts seem to work fine but the Stage 4 U mode is still bugged as usual, eventually though the story mode will exhibit the same bugs presumably since lives are a big part of the game

if you didn't know how to access it, going through here 
![image](https://user-images.githubusercontent.com/8264967/64016287-8d1f9900-caf4-11e9-95e4-a72c7391419e.png)
will let you put 5 girls into a single live, which usually triggers the bug for the whole performance, while putting less than 4 (say 1, 2, or 3) triggers the bug only occasionally

**Comment by kd-11** [comment]
I can't read anything in the game which means I just press O to go next-next-next. You'll have to capture the renderdoc traces before and after for this one. The RSX capture had nothing in it for some reason (probably asynchronous timing by the game engine), but you can use a special build from [here](https://ci.appveyor.com/project/kd-11/rpcs3/builds/27068332/artifacts) that will capture frames correctly for replay.

**Comment by kd-11** [comment]
This was fixed recently.
