### ISSUE TITLE
rpcs3.exe is not a valid Win32 application?

### ISSUE THREAD

**Issue by Sotarouwu** [RPCS3/rpcs3#6183]
![Capture](https://user-images.githubusercontent.com/51849582/60955600-c547fe00-a333-11e9-82a4-dfc51ad4a917.PNG)

This always pops-up when I try to open rpcs3.exe. Any help? (I have the latest version of it btw.)

**Comment by elad335** [comment]
No Operation system version, no link fot source of this executable..

**Comment by 13xforever** [comment]
One day people will read the system requirements and stop trying to run emulator on potato 32-bit systems.
