### ISSUE TITLE
Dynasty Warriros Gundam Reborn Graphic bug since newest Emu version

### ISSUE THREAD

**Issue by AizerMortenort** [RPCS3/rpcs3#6186]
I get graphic bug in the "War is about Quality and Numbers" scenario and stage is "Giants Blocking Path" level is not rendered correctly - sky is all dark and gone . Reverted to "8275" and clouds and sky appeared again.

**Comment by RainbowCookie32** [comment]
Please follow the guidelines when opening an issue and attach logs.

**Comment by AizerMortenort** [comment]
Seems to have been fixed downloaded new version and bug is gone.

**Comment by RainbowCookie32** [comment]
It was probably #6176 then
