### ISSUE TITLE
WRC 5 [BLES02165] color bleeding

### ISSUE THREAD

**Issue by Kravickas** [RPCS3/rpcs3#6187]
Issue - https://streamable.com/jrsbq

Affected both OGL and Vulkan
WCB doesnt help, PRs #6185 and #6179 doesnt change anything either

RDC
https://drive.google.com/file/d/1DNRKDfKq2_Q6oUOpSloitgXTH5VMqD8n/view?usp=sharing

**Comment by kd-11** [comment]
Video looks like a borked LUT, I'll take a look later.
