### ISSUE TITLE
LittleBigPlanet™2 [BCES01086] Keyboard inputs are interpreted as text / on-screen keyboard chat entries

### ISSUE THREAD

**Issue by B-Knight49** [RPCS3/rpcs3#6191]
RPCS3 0.0.6-8355-537d3f25

i7-4790K
GTX 980Ti
16GB DDR3

In LittleBigPlanet 2 (I imagine in all versions, but I'm using the UK edition), using the keyboard to move causes your character to begin typing in the in-game chat. If I had to guess, this is probably the result of the emulator now accepting keyboard presses when typing a message that'd prompt the on-screen keyboard on PS3. 

![image](https://user-images.githubusercontent.com/26165117/61067307-1e309880-a3ff-11e9-874b-0dd0dae8c786.png)

Temp workaround is obviously to use a gamepad instead.

**Comment by Megamouse** [comment]
Try disabling the keyboard in the emulator settings (not the pad settings).
It looks like the game uses the basic keyboard handler.
You'd have to disable that one in the input tab (or was it named I/O ?)

**Comment by B-Knight49** [comment]
Yeah, that works. This is essentially the same as "unplug your keyboard" though, right? To fix this bug we shall remove the thing that is bugged - solved! hahaha. 

It's not an issue without a keyboard e.g using a gamepad but having native keyboard+mouse controls is always nice. It seems like LBP2 automatically has support for keyboards and, as such, automatically accepts any input from them as just raw text as opposed to, say, movement keys.

**Comment by Megamouse** [comment]
Well. It's not a surprise since the keyboard handler uses the same input from your keyboard that the pad handler uses. In the future I could solve this in a few ways. But right now it isn't really feasible or wise to spend time on.

**Comment by B-Knight49** [comment]
Nah, that's understandable. Thought I'd make this purely to draw attention to it and make it known. I'd expect this sort of thing to be fixed way, way later in development. 

Cheers for taking a look though.
