### ISSUE TITLE
[BLUS31431] Project Diva F2nd graphic issues on OpenGL

### ISSUE THREAD

**Issue by Wasarety** [RPCS3/rpcs3#6194]
The intro and gameplay goes fine. The problem is on the 3D objects, which have a lot of pixels that are distracting while playing, besides some objects and/or graphics doesn't load. When pausing the pixels are gone. With the strict rendering option the problem is gone, but it goes at 8-15 FPS. When I try playing with Vulkan the game doesn't boot, in previous builds it did but went slow. I've tried a lot of configurations but it's always either 15 fps or graphic issues. Project Diva F doesn't present these problems for me.
I haven't seen anyone else with the same issue.

**Screenshots:**
![Captura de pantalla (22)](https://user-images.githubusercontent.com/52798698/61077426-60041380-a3ec-11e9-9ae1-6c8123b401a0.png)
![Captura de pantalla (23)](https://user-images.githubusercontent.com/52798698/61077427-609caa00-a3ec-11e9-9b41-23a7b62d9627.png)

**Settings;**
![Captura de pantalla (24)](https://user-images.githubusercontent.com/52798698/61078652-1832bb80-a3ef-11e9-88b8-c8130e88b13a.png)
![Captura de pantalla (25)](https://user-images.githubusercontent.com/52798698/61078653-1832bb80-a3ef-11e9-83c2-a309e9f7f716.png)
![Captura de pantalla (26)](https://user-images.githubusercontent.com/52798698/61078654-1832bb80-a3ef-11e9-9f69-90dd29d0b514.png)

**Video:**
https://www.youtube.com/watch?v=44_A0pg6ogE
(0:00 - 0:18 Intro, 1:35 PV)

**Build:**
v0.0.6-8355-537d3f25 Alpha

**Specs:**
Windows 10 64bit
Intel UHD Graphics
Intel Core i5-8265U

**Log**

**Comment by AniLeo** [comment]
Missing RPCS3.log file, post just contains copy paste from GUI

**Comment by Wasarety** [comment]
> Missing RPCS3.log file, post just contains copy paste from GUI

Fixed (I hope)

**Comment by AniLeo** [comment]
Log shows pirated game, removed log

If someone can reproduce this on a clean game dump, this issue can be reopened
