### ISSUE TITLE
Regression: Broken Vulkan rendering on Tales of Vesperia [BLJS10053] (#6112)

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#6197]
The game regressed after #6112. Vulkan only affected.

![tales-of-vesp](https://user-images.githubusercontent.com/22906342/61118143-c6e30480-a4a0-11e9-8e7b-7b9eb76af9a3.gif)

Used same settings.
[RPCS3_build-8280.log.gz](https://github.com/RPCS3/rpcs3/files/3385880/RPCS3_build-8280.log.gz)
[RPCS3_build-8298.log.gz](https://github.com/RPCS3/rpcs3/files/3385881/RPCS3_build-8298.log.gz)

RSX capture (build 8280):
https://drive.google.com/file/d/1N35UKf-enLF6s-ADkrpprynNDrrrsHfQ

RSX capture (build 8298):
https://drive.google.com/file/d/1Z4RnYS-rfy45VKqP6WnGMAumXLKHZix-

**Comment by kd-11** [comment]
Does it happen if you force a frame limit of say, 30? I don't trust that CPU to keep up with the renderer after the optimizations.

**Comment by Realmantik** [comment]
On 8298 build it happens with framelimit (i tried 30)

**Comment by Realmantik** [comment]
I updated radeon drivers from 19.5.2 to 19.7.2 and the bug disappeared.

**Comment by Realmantik** [comment]
I`ve updated video drivers to 19.7.5 and bug is back.

**Comment by kd-11** [comment]
Tried any newer drivers?

**Comment by Realmantik** [comment]
I will try today later.

**Comment by Realmantik** [comment]
Still an issue.

**Comment by kd-11** [comment]
Retest.

**Comment by Realmantik** [comment]
Still an issue on v0.0.7-8829-f5d8110e build with drivers ver. 19.9.3

**Comment by kd-11** [comment]
Test with current master and try playing around with the driver wakeup delay. Try incrementing by 100 units each time and see if it helps.

**Comment by kd-11** [comment]
Request to reopen if problem persists.

**Comment by Realmantik** [comment]
Driver wake-up setting has no impact on this bug.
