### ISSUE TITLE
Regression: Mirror's Edge Sound Regression with xfloat on (#6056)

### ISSUE THREAD

**Issue by illusion98** [RPCS3/rpcs3#6198]
Mirror's Edge's sound used to work with accurate xFloat on in v0.0.6-8262-17d0dcb7
Since 8266-5753b322 Sound has stopped working.
Accurate xfloat is needed to fix missing sounds (i.e footsteps, gunshots)
Below is the log from both builds.
[8262-17d0dcb7](https://cdn.discordapp.com/attachments/319224795785068545/599239829594570753/RPCS3.log.gz)
[8266-5753b322](https://cdn.discordapp.com/attachments/319224795785068545/599239477952643093/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Regression from previous TSX PR #6056

**Comment by plappermaul** [comment]
Try approximate xfloat with #6894 . Maybe it fixes the sound problems.

**Comment by illusion98** [comment]
I just tested this on latest master and the sound issue is now fixed.
