### ISSUE TITLE
Dead or alive 5: last round [NPEB02203]: wrong colors when upscaling (Linux)

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#6200]
rev8365, linux, r9 fury (mesa 19.1).
Default resolution is 1280x720
When the upscaling is 100%, the colors are good:
![Capture_022](https://user-images.githubusercontent.com/7478580/61168197-bb4c1800-a54a-11e9-8c1b-a393319d79a0.jpg)
![Capture_023](https://user-images.githubusercontent.com/7478580/61168199-be470880-a54a-11e9-9699-ea524dfce0f1.jpg)
![Capture_024](https://user-images.githubusercontent.com/7478580/61168201-c2732600-a54a-11e9-8365-eeaca7a01131.jpg)
If I upscale (200%, or 300%), the colors are wrong in some places:
![Capture_020](https://user-images.githubusercontent.com/7478580/61168211-e171b800-a54a-11e9-842d-7fbe9799c32a.jpg)
![Capture_021](https://user-images.githubusercontent.com/7478580/61168213-e5053f00-a54a-11e9-8bf8-c5c6ef8553da.jpg)
Some stages are rendered correctly, some others not:
![Capture_025](https://user-images.githubusercontent.com/7478580/61168214-e9315c80-a54a-11e9-92a0-9e041ca6b57e.jpg)

**Comment by kd-11** [comment]
Isn't this what the resolution scale threshold is for? GPUs are also used for compute and you cannot differentiate between compute PS and graphics PS. Obviously upscaling data is a bad idea and will never work. Try and find the best scaling threshold that avoids touching data buffers and close the issue.

**Comment by toccata10** [comment]
Thanks. Best scaling threshold: 580x580. Upscale can go up to 250% with my hardware.
Closing
