### ISSUE TITLE
Red Dead Redemption: Game of the Year Edition [BLES01294] Does not start

### ISSUE THREAD

**Issue by kristjaan10** [RPCS3/rpcs3#6215]
when I try to start rdr
this appears in the log
U {PPU [0x1000000] Thread (main_thread) [0x001a7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
F {SPU [0x2000000] Thread (PrimaryCellSpursKernel0) [0x00818]} class std :: logic_error thrown: Invalid SPU decoder
F {SPU [0x2000003] Thread (PrimaryCellSpursKernel3) [0x00818]} class std :: logic_error thrown: Invalid SPU decoder
F {SPU [0x2000004] Thread (PrimaryCellSpursKernel4) [0x00818]} class std :: logic_error thrown: Invalid SPU decoder
do you know what problem is
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3396977/RPCS3.log)

**Comment by MSuih** [comment]
Update the emulator to latest version.

**Comment by kristjaan10** [comment]
> Update the emulator to latest version.
Thanks
