### ISSUE TITLE
Red Dead Redemption: Game of the Year Edition [BLES01294] Doesn't start

### ISSUE THREAD

**Issue by kristjaan10** [RPCS3/rpcs3#6216]
I started up red dead
everything went well until I was on the start menu
My PC screen got stuck and I couldn't do anything anymore
so i switched off my pc
and restart the PC
I then tried restarting RDR
and then vester came up again with loading precompiled shaders form disk
but nothing happens this time
just get stuck at 0 or 111
Someone knows why remains at 0 or 111

![RD1 SHADERS COMPILING](https://user-images.githubusercontent.com/52962194/61299193-ebf8af80-a7df-11e9-9ac0-160bc61547e9.PNG)

**Comment by AniLeo** [comment]
Removed log file showing pirated copy of the game, closed

**Comment by kristjaan10** [comment]
> Removed log file showing pirated copy of the game, closed
what do you mean
I know what a pirated game is
but why is it closed

**Comment by kristjaan10** [comment]
> Removed log file showing pirated copy of the game, closed

Hello is there someone

**Comment by dio-gh** [comment]
Because we don't provide support for pirated games.

@AniLeo Lock the thread please.

**Comment by kristjaan10** [comment]
> Because we don't provide support for pirated games.
> 
> @AniLeo Lock the thread please.

I can't help it that I don't have ps3
single reason why I have installed ps3 emulator
to play ps3 games on
ps3

**Comment by dio-gh** [comment]
You don't need a PS3 to play legally on this emulator. (You do need a blu-ray drive though, or someone with one.)

**Comment by AniLeo** [comment]
The Spam is Very (Not) Appreciated.
