### ISSUE TITLE
Tekken Tag Tournament 2 (BLES01702): Incorrect lighting on characters

### ISSUE THREAD

**Issue by kharij** [RPCS3/rpcs3#6220]
Tested on **0.0.6-8385-736ec403** at the time of writing.

![](https://i.imgur.com/Lr43pUw.jpg)
> Left image has the correct lighting, while on the right is what you see in RPCS3.

To reproduce this issue, character/s should be in areas where there is no "light source" (Under bridges, or inside buildings), then they appear darker than usual, which makes it difficult to see during gameplay. This issue also persists regardless of your settings.

There are also cases where characters (despite being under a light source) appear discolored (skin turning grey, or even black) like the attached image below:
![](https://i.imgur.com/BZvnB8l.png)
> Image on the right is taken from RPCS3.

**System Specs:** 
- CPU: i7-8750H 
- GPU: RTX 2080 Max-Q (8GB VRAM)
- RAM: 16GB
- OS: Windows 10 Home (1903)

**Log:**
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3400611/RPCS3.log.gz)

**RSX Capture:**
[BLES01702_20190717145739_capture.zip](https://mega.nz/#!8ZZjGIrb!pai-FU1xyeMmv5u2YTSBHyUMlKc4l4kekfO9BWoe43A)

**Comment by kd-11** [comment]
Needs retesting with native fp16 disabled in config file.

**Comment by jeremybris** [comment]
Retest; fixed by #8367 ?

**Comment by MarioSonic2987** [comment]
@jeremybris Yep. It's fixed by #8367.

**Before**:
![screenshot-2020_06_07_14_01_44](https://user-images.githubusercontent.com/20027681/83968153-70a45e80-a8c7-11ea-957c-dccbda99b614.png)

**After**:
![screenshot-2020_06_07_13_59_38](https://user-images.githubusercontent.com/20027681/83968102-23c08800-a8c7-11ea-922e-32115361c9cd.png)

**Comment by jeremybris** [comment]
Great!
