### ISSUE TITLE
Mortal Kombat vs DC Random Crashes when trying to compile shaders? 

### ISSUE THREAD

**Issue by AizerMortenort** [RPCS3/rpcs3#6222]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3403997/RPCS3.log)
<!---

Randomly crashes quitting EMU altogether. 

Maybe its the LLVM Recompiler option

**Comment by RainbowCookie32** [comment]
Does it also happen with SPU ASMJIT? Last thing the log shows is an SPU module being built, might be the game desyncing because of the compilation stutter. I'll try to reproduce tomorrow here

**Comment by AizerMortenort** [comment]
Tested and no crash with normal spu but the "experimental" one causes crashes

**Comment by RainbowCookie32** [comment]
Just tested on latest master with SPU LLVM and I can't reproduce the crash. Does it happen somewhere in particular?

**Comment by AizerMortenort** [comment]
use the "fastest" LLVM compiler and it crashes when trying to generate shaders on some levels. Maybe log helps ?

**Comment by digitaldude555** [comment]
@AizerMortenort still issue?

**Comment by Asinin3** [comment]
Since RPCS3 has seen some recent crash fixes when compiling shaders, and this issue has not been updated I think this can be closed safely. Issues like this where it's a random hard to reproduce error, and not a regression where it can be narrowed down to a single PR is hard to debug anyway.
