### ISSUE TITLE
Winter Stars [BLES01224] Regression of transparency textures

### ISSUE THREAD

**Issue by Kravickas** [RPCS3/rpcs3#6232]
After #6224 ''transparency textures'' regressed and CSAA didnt fix that.
![unknown](https://user-images.githubusercontent.com/29986095/61541677-63c51500-aa40-11e9-8e68-b1f2dd401759.png)

RRC + RDC https://drive.google.com/file/d/1fSGU3MpXBrXJeQ0wPVgcljTlQEJLw8oj/view?usp=sharing

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/6236

**Comment by Kravickas** [comment]
fixed :ok
