### ISSUE TITLE
fatal error plz help

### ISSUE THREAD

**Issue by friendlyguyhere** [RPCS3/rpcs3#6240]
![fatal error asdas](https://user-images.githubusercontent.com/53139358/61589279-a4b24c00-ab5c-11e9-94fc-5b89cddd015d.JPG)

Always froze when it's loading in the credit/intro
CPU- AMD Ryzen 5 2600 X
GPU- GTX 1070
RAM- 16 GB 3000 DDR4

**Comment by AizerMortenort** [comment]
do not waste your time here this github is for elitists and not for regular people

**Comment by HerrHulaHoop** [comment]
> you should have added at least game title and report

careful now, you're starting to sound like the elitists.
But yes, this issue is also devoid of any meaningful information and all 3 issues will probably be closed once @AniLeo comes online.
