### ISSUE TITLE
RSX DRIVER error 

### ISSUE THREAD

**Issue by AizerMortenort** [RPCS3/rpcs3#6241]
Whats the point of issues section if you are to criticize and mock people who complain and submit those?!

**Comment by HerrHulaHoop** [comment]
This issue has literally zero information. Did you not see the below message in the issue template?

PLEASE READ THE GUIDELINES BEFORE OPENING AN ISSUE:
https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md

When submitting an issue, please check the following:

- You have read the above.
- You have provided the version (commit hash) of RPCS3 you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs.
- Please also provide:
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use our forums for that.

Come over to our [Discord server](https://discord.me/rpcs3) if you want support.

**Comment by AizerMortenort** [comment]
![Desktop Screenshot 2019 07 21 - 12 36 45 81](https://user-images.githubusercontent.com/10715203/61589850-ae699d00-abb8-11e9-8737-2f45c99c496a.png)
