### ISSUE TITLE
can't start Resident Evil 4 after the update

### ISSUE THREAD

**Issue by fjjking** [RPCS3/rpcs3#6242]
Today,My Resident Evil 4 can't start after the update.
before the update I can enabling Force CPU Blit 
play Resident Evil 4.
this is log
(PS:My English is not great)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3414671/RPCS3.log.gz)

**Comment by CrabLugo** [comment]
Try to find build with regression

**Comment by mavethee** [comment]
Isn't issues with RE4 still a thing? Why creating another? :P

**Comment by Realmantik** [comment]
I have tested on 8400 build, the game is working on Windows OS.

**Comment by fjjking** [comment]
> I have tested on 8400 build, the game (NPEB00342) is working on Windows OS.

I tested on 8400. but it didn't work , I don't understand why.
I got same log.
