### ISSUE TITLE
SIREN BLOOD CURSE : F {RSX [0x001104c]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST) (in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1051)

### ISSUE THREAD

**Issue by DendyRaglan** [RPCS3/rpcs3#6243]

**Comment by proganime1200** [comment]
reinstall video card driver using DDU (clean install) and what specs of your pc

**Comment by AniLeo** [comment]
Closing as there doesn't seem to be any intent of fixing the issue as 2 hours already passed. If you want to actually submit a proper issue following guidelines, you can do so.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
