### ISSUE TITLE
GRAN TURISMO HD Concept [NPUA80019]: Vulkan Crash on low FPS

### ISSUE THREAD

**Issue by Andryshik345** [RPCS3/rpcs3#6251]
Have the same issue in #6144, but in other game. FPS is around 2-3(2.89) whatever i use SPU LLVM or SPU ASMJIT with 10% CPU use only. 
With Vulkan on v0.0.6-8411-85b1152e, crash after ~40 secs in main menu:
`·F 0:02:20.049489 {RSX [0x0013088]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1051)`
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3420510/RPCS3.log.gz)

With OpenGL game woking fine, FPS is 30.

Specs:
RPCS3 v0.0.6-8411-85b1152e Alpha | HEAD | Firmware version: 4.82
AMD Ryzen 3 1200 Quad-Core Processor | 4 Threads | 7.95 GiB RAM | TSC: Bad | AVX+
NVIDIA GTX 750 Ti 2 GB

**Comment by kd-11** [comment]
Nvidia cards do not support some required features for MSAA to work properly. Disable MSAA in GPU options and this problem should go away. Its improved a lot in more modern cards, but the older maxwell and kepler cards are extremely buggy despite the khronos validation layers showing no errors from rpcs3 itself.

**Comment by kd-11** [comment]
Request to reopen if problem persists. Its a known hardware/driver limitation.
