### ISSUE TITLE
Yakuza Games - AMD specific issues

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#6254]
I have noticed the following issues with Yakuza series games that only affect AMD drivers. The pictures are from Yakuza Dead Souls but 3 and 4 are all on same engine so they're affected in similar ways.

Dark or rainbow-colored graphics on faces:
![screenshot-2021_08_10_21_06_24](https://user-images.githubusercontent.com/19759300/128911975-38733581-1feb-4344-8bee-4feffe80bcd2.png)
[Rainbows.zip](https://github.com/RPCS3/rpcs3/files/6963599/Rainbows.zip)

Exploding eye vertices:
![screenshot-2021_08_10_21_08_51](https://user-images.githubusercontent.com/19759300/128912298-1de33d4d-352d-447f-868d-557f7cd03c00.png)
(Multipart due to size limit, remove the 2nd .zip from the end of the name)
[BLUS30826_20210810205504_capture.zip.001.zip](https://github.com/RPCS3/rpcs3/files/6963622/BLUS30826_20210810205504_capture.zip.001.zip)
[BLUS30826_20210810205504_capture.zip.002.zip](https://github.com/RPCS3/rpcs3/files/6963623/BLUS30826_20210810205504_capture.zip.002.zip)

**Comment by Whatcookie** [comment]
This issue is specific to the shader compiler in the proprietary AMD driver.
Radv: ok
amdvlk: ok
amdgpu-pro: rainbow

RX 570

**Comment by AniLeo** [comment]
Does it still happen on the latest build?

**Comment by MSuih** [comment]
Yes, still happens with version 8934

**Comment by AniLeo** [comment]
![image](https://user-images.githubusercontent.com/10283761/67135651-c5e60f80-f213-11e9-950f-12ca4e14f9fd.png)

R9 280X | Driver 19.10.1

**Comment by mlgubolin** [comment]
I can confirm that's happening in Yakuza Dead Souls as well.

**Comment by MSuih** [comment]
Still an issue with 20.1.4 drivers

**Comment by signas2** [comment]
Still an issue with 20.5.1 drivers

**Comment by Rikiki87** [comment]
Still an issue with 20.11.2 drivers (RX 5700XT)

**Comment by yoyossef** [comment]
![image](https://user-images.githubusercontent.com/31565280/101268993-c750ff00-3769-11eb-8982-9b150a4d0324.png)
Same issue here: RX 6800XT, driver version: 20.11.3, Windows 10

**Comment by MSuih** [comment]
RPCS3 0.0.14-11635-67dd6754
AMD driver 21.1.1
![screenshot-2021_01_28_16_21_07](https://user-images.githubusercontent.com/19759300/106151471-0f4a3c00-6185-11eb-9b2e-0db4c19f8db6.png)

**Comment by MSuih** [comment]
Updated the thread with another AMD-specific issue, a weird effect where parts of the eye explode vertically. This explosion effect moves around when replaying the capture, as does the previously mentioned rainbow issue.

**Comment by AniLeo** [comment]
Please retest and update this issue with AMD drivers 23.2.1 or newer as recently there have been changes that positively impact RPCS3.

**Comment by MSuih** [comment]
I no longer have access to this card. If someone else can reproduce this issue then ask for this to be reopened

**Comment by marinm99** [comment]
Hi im having the same issue, i use a RX 6700 XT
