### ISSUE TITLE
Ni no Kuni(VK_ERROR_DEVICE_LOST)

### ISSUE THREAD

**Issue by fjjking** [RPCS3/rpcs3#6255]
I play Ni no Kuni to use Vulkan
I will get stuck when I open my backpack
log:
{RSX [0x002bd78]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1051)

**Comment by RainbowCookie32** [comment]
Follow the guidelines when opening an issue and attach the log file (RPCS3.log.gz), not just a line from RPCS3's window

**Comment by fjjking** [comment]
> Follow the guidelines when opening an issue and attach the log file (RPCS3.log.gz), not just a line from RPCS3's window

Ok this is log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3423075/RPCS3.log.gz)

**Comment by kd-11** [comment]
Need an update on this.

**Comment by digitaldude555** [comment]
@fjjking is it working now?

**Comment by fjjking** [comment]
> @fjjking is it working now?

yes , is working
