### ISSUE TITLE
Missing vulkan-1.dll error.

### ISSUE THREAD

**Issue by KingBraiden** [RPCS3/rpcs3#6257]
**I have bad english sorry**

I have downloaded the latest file from the website. And I have my 'PS3UPDAT.PUP' file inside the folder that has all the files (That I downloaded from the site) and when I run the program it comes up with this message: "The code execution cannot proceed because vulkan-1.dll was not found. Reinstalling the program may fix this problem." I have redownloaded the program many times and it still comes up.

System Specs:
![image](https://user-images.githubusercontent.com/32782516/61755113-baea2300-ad7b-11e9-9f87-02b53ad1e2a0.png)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by RainbowCookie32** [comment]
Don't use Github issues for support, [The discord server](https://discord.me/RPCS3) is there for that. Close the issue and ask for help there

**Comment by dio-gh** [comment]
Remove and reinstall your video driver. 

Please also note that GitHub is not for support-related questions. Use our Discord for that.
