### ISSUE TITLE
Huge regpession of performance in Replicant

### ISSUE THREAD

**Issue by StalkerDolg** [RPCS3/rpcs3#6260]
After Ivan released a new build (006-8413), the game speed dropped a lot. Before that, there were stable 27-30 frames. Now it's 7-11. Thanos requires fix)))))
UPD.: Regression began with 0.0.6-8411. Details and log file - in comments

**Comment by StalkerDolg** [comment]
Just look at FPS
![Безымянный](https://user-images.githubusercontent.com/50276678/61868429-1572b300-af25-11e9-9255-d3fffe523c2c.png)

**Comment by HerrHulaHoop** [comment]
Please follow the contribution guidelines and post the log file as well. Also, post screenshots with performance from the build before as well.

**Comment by StalkerDolg** [comment]
I was wrong about something. I tested a lot of builds just now. This is not Ivan’s fault. Regression began with 0.0.6-8411.  Here is the log file from this build
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3431334/RPCS3.log.gz)
Previous build works fine, here's a screenshot
![Безымянный](https://user-images.githubusercontent.com/50276678/61872521-47891280-af2f-11e9-8b24-482c47b781ab.png)

**Comment by isJuhn** [comment]
Try changing "Sleep timers accuracy" from Host to Usleep in the config file

**Comment by StalkerDolg** [comment]
I'll test it later, after i will back to home.

**Comment by StalkerDolg** [comment]
Yes it helped. But it would be nice if in the emulator settings there was a function to switch this option. Because most users do not read forums and pull requests, so they will not guess to fix something manually. Yes, and no one will have the desire to crawl to the config every time

**Comment by dio-gh** [comment]
There are some discussions about setting the default back to usleep.

**Comment by StalkerDolg** [comment]
It is not necessary to return by default. Just need to make a switcher in the settings. As I said, most people simply do not think of looking at the config and rewriting something)))

**Comment by kd-11** [comment]
I've opened a dedicated ticket for the settings https://github.com/RPCS3/rpcs3/issues/6337. Closing this.
