### ISSUE TITLE
RPCS3 keeps freezing randomly! help please!

### ISSUE THREAD

**Issue by NaufalHama** [RPCS3/rpcs3#6263]
Hi,

I really have a serious problem here and I have been trying for weeks  to solve but couldn't.

First my specs:

-GTX 1070

-i7 6700

-16 gb ram

Second:

my issue with this emulator is that when I play any game, like: God of war origins, super robot dark prison, etc, my game just freezes, but fps and music is still playing and sometimes fps freezes too.....Log file is attached too.

I updated Nvidea driver, I downloaded even old drivers, I updated windows, I tried all different settings given by the emulator, I even tried newer and older versions of the emulator, and IT IS STILL THE SAME PROBLEM! freezing random times.

Please anyone help me, I really want to play, but the freezing is driving me crazy, please help!

And as always, thank you guys for making this amazing emulator, you are awesome :)

**Comment by AniLeo** [comment]
Removed log file showing pirated game and closing as invalid.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by NaufalHama** [comment]
I have been trying days to find what "semaphore_acquire has timed out." means...., and this freeze happens anytime, and not on a specific place, please anyone help.
