### ISSUE TITLE
Little Big Planet 2 [NPEA00324] regression on SPU LLVM

### ISSUE THREAD

**Issue by SpeddieSwagetti** [RPCS3/rpcs3#6276]
Freezes\Loops after intro before in-game 3D when using SPU LLVM. Regressed after #5976.
After Regression: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3439047/RPCS3.log.gz)
Before Regression(Working): [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3439055/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
No longer an issue on latest master.
