### ISSUE TITLE
Nier Gestalt [BLUS30481] Flickering scene lighting 

### ISSUE THREAD

**Issue by fixedbadd** [RPCS3/rpcs3#6277]
RPCS3 v0.0.6-8424-65134f73 Alpha

Default settings, with configuration recommendations for Nier from wiki.
Permanent change of general lighting from medium to bright.
Is any chance to fix this? It seems the same situation is described in #4708.

![Nier Gestalt  BLUS30481  Flickering scene lighting ](https://user-images.githubusercontent.com/53396542/62005411-441ea280-b14c-11e9-9f04-9fee685bd97e.gif)
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/3439083/RPCS3.log.zip)

 Big love for the entire RPCS3 community and developers.

**Comment by Asinin3** [comment]
If its the same issue, why did you open a duplicate? We don't like our issue tracker being spammed and there was a lack of info provided in this report anyway. (No log, no rsx capture or renderdoc). Regardless it's a known issue iirc with the games "eye adaption" feature.

**Comment by fixedbadd** [comment]
Sorry, log uploaded. I'm not going to spam issue tracker.
Thank you for your reply.

**Comment by AniLeo** [comment]
Closing as duplicate, post your findings on the existing ticket for this issue

#4708
