### ISSUE TITLE
Regression on GT6 after #6261

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#6282]
Hello,

After PR #6261 (Build 0.0.6-8422), Gran Turismo 6 BCES01893 (using version 1.05 here) crashes when entering a race track with the following error:
F {RSX [0x12f5bf4]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:274)

Tested with
CPU: Ryzen 7 2700
GPU: RX 580 4GB
RAM: 8GB
OS: Windows 10 1903
GPU Driver: 19.7.3

Settings:
PPU LLVM and SPU Safe LLVM
Force CPU Blit (with or without the error still appears)
Write Color Buffers (with or without the error still appears)

Build 0.0.6-8421 does not exhibit this error.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3443811/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
I can also reproduce. By looking at MSI Afterburner, the VRAM usage goes from 900MB to 3543MB almost immediately, and there the game freezes. R7 1700 and RX 570 4gb
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3443862/RPCS3.log.gz)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/6376

**Comment by Asinin3** [comment]
Its best not to close issues until the Pull Request that fixes them merges.
