### ISSUE TITLE
Game freezes at halftime and super sweaty players nba 2k7 [BLUS30004]

### ISSUE THREAD

**Issue by Deliveredmean42** [RPCS3/rpcs3#6289]
![NBA 2k7](https://user-images.githubusercontent.com/42306608/62246775-5d288d00-b3b2-11e9-894d-4ad0de1f88ec.png)

There is an issue with the game where it tends to always freeze around the halftime report. Running using ASMJIT recompiler as LLVM recompiler doesn't work with the game.

![image](https://user-images.githubusercontent.com/42306608/62247759-80ecd280-b3b4-11e9-8289-5298033b7c44.png)

![image](https://user-images.githubusercontent.com/42306608/62247865-c27d7d80-b3b4-11e9-8a44-9d1bd7830963.png)

Players model also uses an incorrect use of alpha transparency for the sweating effect.

System Hardware:
-Windows 10 64bit
-Ryzen 3600
-RX 480
-2600mhz of 16gb ram

RPC Build 0.0.6-8437
API: Vulkan

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/3453833/RPCS3.log.zip)

**Comment by incognitoh** [comment]
hmm, SPU LLVM works fine for me with 2k7...

**Comment by digitaldude555** [comment]
https://forums.rpcs3.net/thread-200352.html freeze and sweat are no longer issues.
