### ISSUE TITLE
System clock showing date as 2228/10/25

### ISSUE THREAD

**Issue by DenL** [RPCS3/rpcs3#6291]
System clock(datetime) is reflected on save file timestamp in some games.

Behavior on rpcs3-v0.0.6-8406-070c3af5_win64:
Would correctly show current GMT+3 datetime for the first ~30 minutes of launching emulator. After the first ~30 minutes, system clock would loop back to the beginning of timestamp when emulator was first launched.

Bahavior on rpcs3-v0.0.6-8437-f0bd0b5a_win64:
System is showing 2228/10/25 GMT-4 time (minues ~40 minutes) (just happens to be my local timezone, unsure if related or coincidence). Unclear whether clock would loop after extended time.

**Comment by elad335** [comment]
What operating system are you on?

**Comment by elad335** [comment]
#6286 Hopefully fixes the regression you are having.

**Comment by Kian-Stevens** [comment]
This sounds a bit like the issue I opened up in #6084, in which the clock would be ahead of the actual time, and was seemingly dependent on when you launched the emulator

Furthermore, if you look at the second lap time on the rankings, I apparently set it some time in 1972:
![Untitled2](https://user-images.githubusercontent.com/31938249/62285568-c4dfe600-b44d-11e9-9b17-cb7a6769d6b9.png)

If these issues are in fact related, then as of #6286 (0.0.6-85f09f58), the issue I opened in #6084 persists:
![Untitled](https://user-images.githubusercontent.com/31938249/62285904-8139ac00-b44e-11e9-9089-908b826511c0.png)
(The time I took the screenshot was 11:10)

**Comment by elad335** [comment]
They are not the same issue.

**Comment by Kian-Stevens** [comment]
> They are not the same issue.

My apologies, it seemed as though they're similar

**Comment by elad335** [comment]
Any update?

**Comment by d4rkne55** [comment]
Does this maybe have sth. to do with #81a110f? Maybe you should check again.

**Comment by digitaldude555** [comment]
![Anmerkung_2020-02-08_201016](https://user-images.githubusercontent.com/26138653/74090748-b25aff00-4ab7-11ea-8956-0f4d4a2e4ef2.jpg)
can be closed.

**Comment by AniLeo** [comment]
Closing as fixed, if you can still reproduce ping for reopening
