### ISSUE TITLE
Naughty Dog games another Trap Issue

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#6296]
To investigate this issue i used a build with hack that not throws exception on Trap. Here's the few examples that i've found
In Uncharted 2 i've found two of them, both look like overflow or smth, the first with temple trap screen becomes black and console spams with Traps, the second is camera disortion and also Traps
Here's the video:
https://youtu.be/rZEhjkeG35A
In Uncharted 3 issue that looks like second in U2 camera disortion(usually) and Trap, on video it also crashes, this place keeps me from further playing through this game, until this place it more or less possible to play
here's the video:
https://youtu.be/Q8kNyUyosFI
And The Last of Us also has issue, trap spamming and blackscreen impossible to play further
here's the video:
https://youtu.be/pGIgCpoNuB8
If any other info or save files required just let me know

**Comment by kd-11** [comment]
A trap is usually part of an assert statement so there should be corresponding information in the TTY window.

**Comment by Asinin3** [comment]
While not entirely related, since you don't seem to be in our Discord server I just wanted to let you know that you can bypass trap errors by making a patch.

You will need to put your ppu-hash from the game in and edit in the address from the trap.
```
PPU-<ppu-hash>:
    - [ be32, 0x<address in Trap message>, 0x60000000 ]
```

**Comment by Xcedf** [comment]
@kd-11 here's the TTY's, for some reason Uncharted 3 didn't showed any assertion in tty on traps
so i've got only U2 and TLoU
[U2.gz](https://github.com/RPCS3/rpcs3/files/3463892/U2.gz)
[TLOU.gz](https://github.com/RPCS3/rpcs3/files/3463893/TLOU.gz)
@Asinin3 interesting method, thanks, but i guess it ain't fixes the issue itself and these games have a ton of different trap addresses so making a patch for this will take a hell of a time.

**Comment by kd-11** [comment]
This are all NaN checks. assert(x == x) checks for NaN and isFinite(x) checks for inf. Looks like a CPU bug somewhere - does it occur with accurate Xfloat?

**Comment by Xcedf** [comment]
Yes, Accurate Xfloat not helps this.

**Comment by elad335** [comment]
Have you tried #6556 with ppu precise interpreter? SPU precise interpreter also has s similar fix for DFMA family, but lets hope its only a ppu issue since its easier to test.

**Comment by Xcedf** [comment]
Tried now, not working, as for SPU Precise, it took me an hour t run the test with elevator scene at 0,2fps speed, and it froze at the point when you can control your cahracter after the elevator fall.

**Comment by Xcedf** [comment]
Catched another of these issues, but now it also gives another message except Traps
F {PPU[0x1000000] Thread (main_thread) [0x007555e0]} VM: Access violation reading location 0x9ead5124 (unmapped memory)
![image](https://user-images.githubusercontent.com/7060586/75637392-48a5bf00-5c37-11ea-97a0-8fb72e5522e4.png)

**Comment by elad335** [comment]
This issue has 0 amount of logs...
