### ISSUE TITLE
MotorStorm [BCES00006] Track stripes issues

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#6303]
Track has weird stripes that flicker and are yellow sometimes.

![2019-08-04 18_20_27-FPS_ 28 51 _ Vulkan _ 0 0 6-8442 _ MotorStorm™  BCES00006](https://user-images.githubusercontent.com/20983844/62432678-ebb84980-b6e5-11e9-8b0b-b34c7345c028.png)

![2019-08-04 18_21_12-FPS_ 30 11 _ Vulkan _ 0 0 6-8442 _ MotorStorm™  BCES00006](https://user-images.githubusercontent.com/20983844/62432621-8fedc080-b6e5-11e9-8011-00065749cd11.png)

Also, kicked up dirt is purple. 
![2019-08-04 18_21_20-Window](https://user-images.githubusercontent.com/20983844/62432620-8fedc080-b6e5-11e9-9d6d-1374471d6815.png)

[RPCS3motorstorm.log.gz](https://github.com/RPCS3/rpcs3/files/3465593/RPCS3motorstorm.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by AniLeo** [comment]
Still an issue, and probably needs an RSX Capture

**Comment by legend800** [comment]
@AniLeo @kd-11 
Here's the RSX capture:  
https://drive.google.com/file/d/125Tvbxq8z3L2pBKcs7XdzbM83QXxPwKN/view?usp=sharing

**Comment by legend800** [comment]
@AniLeo Can you remove the 'needs info' label? Thanks!

**Comment by Cereal-Killa** [comment]
> Still an issue, and probably needs an RSX Capture

That's the only thing preventing the game from looking nice atm I think, it's running 30fps stable and so far no crashes, would you like another RSX capture? If so then how do I generate one?

Thank you.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4463249/RPCS3.log.gz)

**Comment by marcoluc97** [comment]
Any more news? @kd-11 ?

**Comment by kd-11** [comment]
This game has some weird shaders. Should be fixed by https://github.com/RPCS3/rpcs3/pull/8329

**Comment by marcoluc97** [comment]
@legend800 & @Cereal-Killa Can you test this PR #8329 ?

**Comment by Yahfz** [comment]
![image](https://user-images.githubusercontent.com/17715080/83568577-a200e100-a4f9-11ea-8cfa-88bb547fe74a.png)
fixed, can be closed once its merged.
