### ISSUE TITLE
Pad handler misbehaving under very high or low fps conditions

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#6306]
The pad handler seems to suffer from starvation issues.

While testing NieR with Whatcookie's patch applied and the framerate limiter off (using a DS4), I noticed that it's very cumbersome to type my name in at the start of a new playthrough. In fact I couldn't at all during the first try. At very high fps (think 300+) the pad handler seem to barely work if at all, and while I could navigate the menus, the OSK went basically crazy, and kept going left for a good minute, without catching a break. 

I also noticed a similar behavior once in P5, under normal framerates but heavy SPU congestions, that while typing in my name the char position would sometimes jump several places instead of just one (not OSK, also DS4).

Then I was testing TLOU, and at very low fps (~7) I managed to get stuck beside a door. My character would keep strafing left, would stop sometimes, I could barely get it out. After that, the controls seemed to work normally, so this wasn't the general experience. (this was also using a DS4)

And today, I tried out Arkedo Jump on my i5 4440. I was using the keyboard pad handler, and having the framerate limiter off, I was at around 300 fps. I couldn't move, could sometimes make my character turn to the left and start the running animation, but that's it. After limiting the game to 60 fps, it worked fine.

![](https://cdn.discordapp.com/attachments/483198470275203072/607959850822926357/unknown.png)

All in all, it looks like the pad handler thread can get into very heavily starved situations, and stay there pretty much indefinitely. While there, it'll just keep repeating the previously recieved signal, making it very hard to break out of.

Tested with latest master, with the DS4 and keyboard handlers, and on an i7 7700HQ (4c8t laptop) and an i5 4440 (4c4t desktop) running on Win10 & Pop OS and Win8.1 respectively.

These issues may be hard or impossible to reproduce on CPUs with significantly better IPC or threadcounts.

**Comment by dio-gh** [comment]
Still an issue, input handling is still very hit-or-miss for me.

**Comment by dio-gh** [comment]
Still an issue, appears to affect the keyboard handler more than the DS4 one.

**Comment by Megamouse** [comment]
I just tested this and found out that we properly pass the events to cellPad.
So this is just random game derp in my opinion.
Probably some weird lerp based on framerate.

**Comment by Megamouse** [comment]
Another thing to mention is that I wouldn't be surprised if some part didn't work if the CPU is already at 100% doing emu shenanigans.
Like... my PC is basically useless when I compile RPCS3. So why would some pad thread behave otherwise.
That being said, I never noticed any problems. keep in mind that we poll the pad thread very very often.
And even if it only updated with 10Hz (very very unlikely), it would probably still be kinda usable and way less clunky than Arkedo at 300fps.

**Comment by dio-gh** [comment]
I'm not really sure what's going on tbh. Just had a user on Discord that presented with a bug I also had, pretty much related to this: input becomes doubled, tripled, skipped, repeated seemingly without end.

One time I even had my d-pad controls flipped upside down, purely due to some race cond in the input handling. It's pretty bonkers.

I can close the ticket I guess because it's extremely difficult to repro, but the input handling in my experience is pretty scuffed sometimes regardless.

**Comment by Megamouse** [comment]
It's highly unlikely that this is our fault.
We just tell the game which buttons are pressed.
What the game does with this information depends on the buggy coding of random game devs.

I can imagine that someone simply used the time between each frame to calculate some movement physics. This will obviously fail if you suddenly have 5 times the frames.
You can actually see that in arkedo the menu is very usable while in-game is just a mess.
But cellPad code doesn't know about any menu.

**Comment by dio-gh** [comment]
I had the button press doubling/trippling happen in the osk too though?

**Comment by Megamouse** [comment]
no issues here. even with the unlock fps patch

**Comment by dio-gh** [comment]
Not really sure it's worth keeping the ticket open if you absolutely can't repro 🤷
