### ISSUE TITLE
crash to desktop,error message,missing texture

### ISSUE THREAD

**Issue by jonyvx** [RPCS3/rpcs3#6308]
hi..thanks for this great software "rpcs3" i hope more updates come fast real soon...

just wanted to post error log for matt hazard and nvoglv64.dll error 
and please do something about log file size getting more than 7+ gigabyte ..more than a game size
...is there a way to extract .pkg files and do speed hack and dll injections using other tools and compressing their size to work faster and stored temporarly in ram for faster use by creating virtual disk drive in ram which is 10x times faster than ssd ? for super fast read and write for game files ? also can't we use cheat engine for speed hack and modify some hex bytes in game dlls and compress its files after extracting ? i mean real time reverse engineering stored temprarly in ram for any ps3 game that has been loaded in ram ? i we can use Texmod and Dll injector hacker tools for many usefull things ...i used Texmod tool for online game for real time texture moding it was really cool thing..just saying there are many alternative ways to do speed hacks for rpcs3 and extract and hack ps3 games for fast and smooth playable status

**Comment by jonyvx** [comment]
https://imgur.com/a/bTU1rmR

**Comment by RainbowCookie32** [comment]
Github is not the place for support, that's for our discord server. Even if it wasn't one, you completely skipped the guidelines for opening issues. Please close this and move to [the Discord server](https://discord.me/RPCS3) if you are having issues

**Comment by jonyvx** [comment]
rpcs3-v0.0.6-8440-c219417f_win64
Log file : 
https://file.io/0GJGYQ

**Comment by RainbowCookie32** [comment]
> Please close this and move to the Discord server if you are having issues.

and your link 404s

**Comment by jonyvx** [comment]
i dont mean store the whole game in virtual disk ...i mean just for like a quick temporarly dissassembling and bypassing and modifying  to alter the game's graphics, dialogue, levels, gameplay, and/or other elements using some types of brute forcing i mean there are many ways of " Hacking the Game" Like data hacking ,music hacking ,Assembly hacking, Level , Rom ,Graphics ,Palette hackings..changing values that stored in Hex ...i mean isn't there a way to make software think it got the files it needs to load textures and game files..when it dosnt ? 
Log file:
http://s000.tinyupload.com/index.php?file_id=90380770128048995143

**Comment by jonyvx** [comment]
i joined the discord server chat but cannot send messages ..say" you do not have persmission to send messages in this channel" 
i already verifyed and bypassed boring captcha.

**Comment by RainbowCookie32** [comment]
There's a waiting time on the server, so people read the rules before starting to send messages
