### ISSUE TITLE
Gran Turismo 6 Vulkan API call failed with unrecoverable error

### ISSUE THREAD

**Issue by Wizzy2018** [RPCS3/rpcs3#6310]
Sudenly new build give me this error  Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
Here is a log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3471873/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Duplicate of #6282
