### ISSUE TITLE
Regression: Sacred 2 [BLES00410] (#5315)

### ISSUE THREAD

**Issue by PlatinSource** [RPCS3/rpcs3#6311]
While testing some games from my library I found something that regressed.

The following figure shows the menu of the game:

![sacred_2_menu](https://user-images.githubusercontent.com/53820225/62537065-dceda600-b84f-11e9-8efe-9655074d9122.PNG)

While searching through Github I found the that this Problem was mentioned in Pull request #5315. But it seems like it was forgotten. This issue is present on both Vulkan and OpenGL . WCB and SRM have no visual impact. Also Blit emulation does not help.

When going ingame the output looks almost the same with  SRM on/off. 

![sacred_ingame_srm](https://user-images.githubusercontent.com/53820225/62537080-e6770e00-b84f-11e9-945f-aa8389536690.PNG)

It also does not matter if AA is en- or disabled. But even though SRM is not needed ingame resolution scaling doesn't work. When enabled the output looks similar to the menu. See the next image for reference:

![sacred_2_res_scaling](https://user-images.githubusercontent.com/53820225/62537382-8fbe0400-b850-11e9-9715-ed0b851f4879.PNG)

The test were done on rpcs3-v0.0.6-8442-6e89e4eb_win64

Hope that this helpful and continue to do such an amazing work.

System Specs
Windows 10 1903
i7 6700k
16GB RAM
AMD Radeon R390x

**Comment by kd-11** [comment]
Need an RSX capture of that menu glitch.
Ingame not liking upscaling is usually not considered a bug since some games are just coded in an incompatible way.

**Comment by PlatinSource** [comment]
Will update the error report as fast as possible

**Comment by PlatinSource** [comment]
I have tested the game on the latest master version and the issue still persists. But enabling read color buffer crashes the game which was not the case before. See log:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4167166/RPCS3.log.gz)

And the rsx.capture of the scene:

[BLES00410_20200206193954_capture.zip](https://github.com/RPCS3/rpcs3/files/4167178/BLES00410_20200206193954_capture.zip)

File name was changed to .zip but it is a .7z
