### ISSUE TITLE
[Massive Regression] Tekken 5 DR(NPUB30009), I have pinpointed the exact build it occurs

### ISSUE THREAD

**Issue by VenomBlade91** [RPCS3/rpcs3#6313]
After randomly trying a much older build(0.0.5-6957) and seeing how much better T5DR performed when compared to the latest builds that have substantial performance drop offs, I tested an embarrassing number of builds to pinpoint the exact revision where this performance drop happens. 

0.0.5-7495 is the last build where the game runs at mostly full speed, with the very next iteration 0.0.5-7496 having substantial performance loss, as evidenced by these two pictures I've uploaded. I've also attached the logs of both revisions. A helpful user on the Discord replied with "If your logs are correct then pull #5310 is what caused the regression." Hopefully this is enough information for those with the knowledge and power to rectify this for later builds because performance isn't perfect and it still crashes semi-frequently on 7495.
![RPCS3-7495](https://user-images.githubusercontent.com/53836560/62571394-40cb9b00-b85f-11e9-8fd7-e7e0dc5b8c9c.jpg)
[RPCS3-7495.log](https://github.com/RPCS3/rpcs3/files/3473860/RPCS3-7495.log)
![RPCS3-7496](https://user-images.githubusercontent.com/53836560/62571395-40cb9b00-b85f-11e9-9342-cbfc4f421d76.jpg)
[RPCS3-7496.log](https://github.com/RPCS3/rpcs3/files/3473861/RPCS3-7496.log)

**Comment by dio-gh** [comment]
After a bit of discussion with the PR author, we determined that it is because the PR enabled more SPU threads to run with the fix. A tester managed to restore the original performance by limiting the number of SPURS threads to 3.

Please test and see if that fixes it. You can find the option in the debug tab, the latter of which you have to enable in `GuiConfigs\CurrentSettings.ini` by setting `showDebugTab` to `true`.

**Comment by VenomBlade91** [comment]
Amazing work! The game is now absolutely flawless performance wise. Even certain visual effects that wouldn't properly display in the older revisions display now. Is this a fix I could apply forwards to other Tekken games(or other games in general) that don't run at full speed as well?

**Comment by RainbowCookie32** [comment]
> Is this a fix I could apply forwards to other Tekken games(or other games in general) that don't run at full speed as well?

Maybe. Not all games react in the same way when you limit the amount of SPU threads that they can use. Some don't really care and might show improvements in performance, while others break. Uncharted 1 didn't even get to the main menu last time I tried that with it

**Comment by dio-gh** [comment]
Yup, just as @RainbowCookie32 says. You may close this issue now if it's fixed. :)
