### ISSUE TITLE
[Resogun] - Playable -> Intro (Black screen on startup)

### ISSUE THREAD

**Issue by KcrPL** [RPCS3/rpcs3#6315]
Hey,

Today I tried playing Resogun on my PC. As always I updated to the latest version available.
>Version: v0.0.6-8444 Alpha [2019-08-07]

All I can see is two splash screens and then when the `This game autosaves...` fades in, the emulation crashes. I'm attaching a screenshot: 

![123](https://user-images.githubusercontent.com/17184296/62693173-41d10980-b9d2-11e9-8cd1-1b765a63cf98.PNG)
 
...and the log file.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3481010/RPCS3.log)

Notice how it says:
>·W 0:00:15.892884 {PPU[0x1000000] Thread (main_thread) [0x00267e68]} RSX: Cache miss at address 0xC6360000. This is gonna hurt...

This is where the emulation crashes. The main window changes it's state to `Not responding` and I have to close it from the Task Manager.

My specs:
>CPU: Intel Core i5-8600K @ 4,2GHz
>GPU: NVIDIA GeForce GTX 1060 6GB
>RAM: 16GB

P.S: Closing the overlay didn't really changed anything. Just saying if anyone is curious.

**Comment by Zangetsu38** [comment]
i have get same crash, but on second boot have works

**Comment by KcrPL** [comment]
Well, it doesn't work for me at all.

**Comment by kd-11** [comment]
Cache miss warning is about performance not crashing. Its a side-effect of enabling Write Color Buffers which is unnecessary for this game so you are losing performance for no gain.
The game itself runs fine for me out of the box:
![image](https://user-images.githubusercontent.com/15904127/62935844-d8396c80-bdd0-11e9-8949-8189888b41b8.png)

**Comment by KcrPL** [comment]
Huh, interresting. I remember that the performance was perfectly fine for me. (4K 60FPS)

So what should I do?

**Comment by KcrPL** [comment]
Turned off `Write Color Buffers` and well... it's working.

Closing the issue. Thanks for help.
