### ISSUE TITLE
SUPER STARDUST™ HD [NPEA00014] - Invisible bullets

### ISSUE THREAD

**Issue by SpeedouTM** [RPCS3/rpcs3#6317]
Hello,

So as said in the title, the bullets of the bosses and the bullets of the "rock crusher" (the green bullets) mode are invisible and it's gameplay killer, hard to avoid something invisible.

I searched on youtube about this game and on the older versions of RPCS3 (2017) the problem doesn't appear. I applied the configuration they did on their video and that's the same so I would say that's linked to the actual version of RPCS3. Tried multiple configuration but the problem cannot be solved at my side.

I attached a log.gz of RPCS3 bellow
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3486289/RPCS3.log.gz)

I precise that the game is very very stable and never crashes, there is just this problem that kill the gameplay.

**Comment by arabek** [comment]
Confirmed. Same observed here. Both OpenGL and Vulkan with WCB ON|OFF affected.

**Comment by unascribed** [comment]
Is there anything that non-devs can do to help isolate and fix this issue? Stardust is one of my favorite PS3 games and enemy bullets being invisible makes it extremely frustrating to play.

I've tried virtually every combination of settings.

(Interestingly, this issue doesn't seem to occur with older versions of Super Stardust HD.)

**Comment by arabek** [comment]
I've managed to capture a renderdoc and probably identified the EID of the event that draws the bullets in the VS, but then fails to display anything to the screen. Strange.

[SUPER_STARDUST_HD_NPEA00014-EID2227.rdc.bz2] (https://arabek.net/rpcs3/SUPER_STARDUST_HD_NPEA00014-EID2227.rdc.bz2)

EID in question is 2227
As seen in the object viewer for the VS buffer, there are clearly bullets flying from the ship position to the edge of the globe.

Hope this helps

**Comment by arabek** [comment]
fixed-by: #6966
