### ISSUE TITLE
Block RPCS3 from working when vulkan-1.dll is in RPCS3 folder

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#6318]
A lot of people think it's a good idea to download random system DLLs from the web and place them in the folders of the software that needs it, instead of fixing the root of the problem.

This causes other silent issues such as RPCS3 not being able to initialize properly with cryptic errors such as 0xc000007b, or random issues with the API itself due to the DLLs being too old, for example. Not to mention they could be downloading some adulterated DLL.

RPCS3 should check if there's a vulkan-1.dll in its own folder (vulkan-1.dll's location is system32, no one is going to place RPCS3 there) and error out with a message explaining users not to download the system DLL and how they can fix the root issue (reinstalling drivers, or downloading VulkanRT if their latest GPU drivers are too old).

**Comment by ghostslayer989** [comment]
Should be a very simple file check it does just before trying to run vulkan.

**Comment by AniLeo** [comment]
Not that simple as just adding a file check, it needs to be checked on startup and a message box needs to pop up with the relevant information, we need to figure out if it's possible to trigger that check before the cryptic 0xc000007b or silent hang too

**Comment by kd-11** [comment]
This can be combined with my other suggestion for delay-loading vulkan-1 I think. First, this would prevent users of systems without vulkan support from being forced to have vulkan-1 dll available and would therefore make this check less of a headache for them. This task by itself is very simple once vulkan-1 is not an enforced requirement.

**Comment by readywer** [comment]
Is this still a valid issue?

**Comment by AniLeo** [comment]
Yes

**Comment by kd-11** [comment]
I completely forgot about this one. I'll push something to close it.
