### ISSUE TITLE
God of War HD Collection and GoW Origin Collection [Unplayable/Hard Crash with TSX Instruction Enabled]

### ISSUE THREAD

**Issue by Pantsay126** [RPCS3/rpcs3#6320]
Every time I tried to boot God of War HD Collection and/or God of War Origin HD Collection, game ends up freezing/crashing while TSX Instruction Enabled.  Build version: 0.0.6-8445

i9-9900k 
RTX 2080 Ti
64GB RAM
Windows 10 64-bit Pro May 2019 Update

![rpcs3 hard crash](https://user-images.githubusercontent.com/49543895/62817716-f876dc00-baef-11e9-9324-e96cf95eb708.PNG)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3488521/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3488525/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Retry with 0.0.6-8455 once it builds and appears on website

**Comment by Pantsay126** [comment]
I tried that build but still constantly crash. Somehow, after going through trial & error, setting TSX Instruction causes the game to crash/freeze and even during cutscenes in God of War HD 1 & 2 and God of War: Origins Collection.

**Comment by digitaldude555** [comment]
Its fine with tsx enabled can close.

**Comment by AniLeo** [comment]
Closing as fixed, ping if you can still reproduce
