### ISSUE TITLE
Regressions from: (rsx: Minor fixup for image_in) #6314

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#6323]
@kd-11 
Issue: ( These game crashes without enable GPU texture scaling after #6314. )

[Crash Commando]

Build:[0.0.6-8444]
![2](https://user-images.githubusercontent.com/38318848/62820261-2137b980-bb62-11e9-9611-b1cf193ed93e.png)
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3488716/RPCS3.log.gz)

Build:[0.0.6-8445]
![1](https://user-images.githubusercontent.com/38318848/62820242-af5f7000-bb61-11e9-93fc-4be4a7324f19.png)
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3488714/RPCS3.zip)

---------------------------------------------------------------------------------------------------
[Swords and Soldiers]

Build:[0.0.6-8444]
![4](https://user-images.githubusercontent.com/38318848/62820306-aa4ef080-bb62-11e9-8148-74acdbf0385a.png)
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3488718/RPCS3.log.gz)

Build:[0.0.6-8445]
![3](https://user-images.githubusercontent.com/38318848/62820313-d8343500-bb62-11e9-8772-272c6a22d55d.png)
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3488719/RPCS3.zip)

**Comment by elad335** [comment]
Retest with #6321

**Comment by kd-11** [comment]
Its caused by a missing resize on temp3. I figured it wouldn't cause issues until I had time to push the whole thing I have locally, but I guess not. Its a one-liner in https://github.com/RPCS3/rpcs3/pull/6325.
Not sure if elad's PR has the same fix, if it already does I can withdraw mine.

**Comment by Emulator-Team-2** [comment]
@elad335 
Still crashing with #6321.
![5](https://user-images.githubusercontent.com/38318848/62821105-9c539c80-bb6f-11e9-9790-b1e50428b408.png)
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3488766/RPCS3.zip)

**Comment by Emulator-Team-2** [comment]
Fixed by #6325 
![6](https://user-images.githubusercontent.com/38318848/62821327-41bc3f80-bb73-11e9-87a8-94fad53b935d.png)
![5](https://user-images.githubusercontent.com/38318848/62821329-48e34d80-bb73-11e9-8a40-55dd6ad0e3b5.png)
