### ISSUE TITLE
Demon's Souls [BLUS30443] crashing

### ISSUE THREAD

**Issue by PyrotechnicAxe** [RPCS3/rpcs3#6327]
rpcs3-v0.0.6-8457-94d33003

**System Specs:**
Windows 10 1803 (17134.885)
Ryzen 5 1600
GeForce GTX 1060 6GB (driver 417.22)
16 GB ram

Started playing through Demon's Souls but would randomly crash. 4 times in the nexus and 1 time right past the Phalanx archstone.

During the crash at the Phalanx archstone, I could hear myself getting hit even though RPCS3 is not responding.

**Log File:**
https://mega.nz/#!fgUFiAQI!BXotiOsbczoYUFSoSzt3tWLWPQEGitPfBzhZHhJgKyw

The log file is massive and I'm not sure why. I can't seem to modify log levels in config.yml.

**Settings:**
![CPU](https://user-images.githubusercontent.com/53982134/62827061-9912dd80-bb7c-11e9-8ca7-4f65f6bd9769.JPG)
![GPU](https://user-images.githubusercontent.com/53982134/62827062-9c0dce00-bb7c-11e9-9aff-717607b408a5.JPG)

My settings are mostly default. Maybe there is something I could try changing?

**Comment by Weskerbossezi** [comment]
enable LLVM Recomplier (fastest) this may help a little

**Comment by PyrotechnicAxe** [comment]
I recall trying LLVM Recompiler + Multithreaded RSX and it froze indefinitely on the first loading screen so I went back to ASMJIT Recompiler.

I have since tried Strict Rendering Mode which seems to help significantly, although it doesn't completely solve the crashing.

**Comment by kingcailan** [comment]
I've been running into the same problem. [Log File Link](https://drive.google.com/open?id=1wxBWjNzId3EV9G8L4AD46-P2Rx9E0H0r)

In the above log, I have sceNp: Fatal set in config.yml, to make it easier to search the logs myself. Upon some examination, I did notice the following four lines looped indefinitely until the emulator was terminated:

`·W 0:02:43.037074 {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d54f74]} sys_lwmutex: _sys_lwmutex_create(lwmutex_id=*0xd02687f0, protocol=0x2, control=*0xd0268a20, has_name=0x80000001, name=0xd0268a10)`
`·W 0:02:43.037081 {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d54f74]} sys_lwmutex: _sys_lwmutex_create(lwmutex_id=*0xd0268750, protocol=0x2, control=*0xd02689f0, has_name=0x80000001, name=0xd0268a18)`
`·W 0:02:43.037089 {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d55218]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x95063800)`
`·W 0:02:43.037092 {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d55218]} sys_lwmutex: _sys_lwmutex_destroy(lwmutex_id=0x95063700)`

**Comment by kd-11** [comment]
After having tested this numerous times on both AMD and NVIDIA hardware,  I feel this can be closed. Request to reopen if problem persists to this day.
