### ISSUE TITLE
Tekken 6 rpcs3 game stucks after trophy loading screen

### ISSUE THREAD

**Issue by MrXterminator** [RPCS3/rpcs3#6328]
Hello...
I have downloaded tekken 6 for ps3 from internet...
And trying to run it on rpcs3..
I have downloaded firm ware and updated the game..
But when i launch the game...
The game loads trophies and after it seems like the emulator freezes..cz no change in fps
I have also tried deleting cache and saved data..nothing works...
Plz help...
After reading log.. I think that emulator is not loading any textures.

Specs:
Intel core i5 vpro 2.40 to 2.80 ghz
Intel hd graphics 4600
Render: open gl 
Ram 8gb

And plz if u know the solution..plz explain cz.. I dont know about programming like changing entries in files..

**Comment by MrXterminator** [comment]
hey why u closed. plz help

**Comment by Megamouse** [comment]
Because you didnt follow the rules:
RPCS3 is not designed to enable illegal activity. We do not promote piracy nor do we allow it under any circumstances.
