### ISSUE TITLE
Robot Rescue Revolution [NPEB00516] HDD error

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6332]
![robot](https://user-images.githubusercontent.com/2696404/62861324-ad4e0a80-bd35-11e9-95d2-d1e0df061dd3.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3492029/RPCS3.log.gz)

**Comment by Megamouse** [comment]
this should be fixed by #6444
