### ISSUE TITLE
LittleBigPlanet 2 [BCES01086] motor bolts are not spinning, elastic not stretching and springs not springy; stopping story being fully "Playable"

### ISSUE THREAD

**Issue by B-Knight49** [RPCS3/rpcs3#6333]
**System Information**
rpcs3-v0.0.6-8464-0a5b6ad9

i9-9900K @ 4.70 GHz
16GB RAM
GTX 980Ti
Windows 10 Build 1803

Log is 13MB compressed. 340MB uncompressed. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3492096/RPCS3.log.gz)
 
**Issue**
The rotating / motor bolt is a type of motor in LittleBigPlanet 2 that allows one item to spin relative to another. This motor does not spin in RPCS3. Elastic is a type of strut that makes one object have a stretchy attachment to another, in RPCS3 the elastic does not stretch but rather gets stuck at a distance and no longer moves. The spring is another strut that instead makes an object bouncy (like a trampoline) when it is suppressed by a weight on top of it, this also doesn't work and instead suppresses and then doesn't bounce back again.

These are used everywhere throughout the story mode and can be vital to your progression in some levels. By not working correctly, some machines and contraptions are completely broken. One example is the story level "Currant Affairs" where a platform is attached to a spring and is used to gain momentum and height to jump over an obstacle. This platform does not move at all.

**Motor bolt**
![image](https://user-images.githubusercontent.com/26165117/62860559-6beb3a00-bcf8-11e9-8918-cd10b61c4755.png)

**Spring**
![image](https://user-images.githubusercontent.com/26165117/62861538-b621ea80-bcfb-11e9-9861-253bced593eb.png)

**Elastic**
![image](https://user-images.githubusercontent.com/26165117/62861664-19138180-bcfc-11e9-9465-b9d55890c2cb.png)

These issues aside, LBP2 is performing very well, rarely crashes and has only a few visual bugs that are non-intrusive. The game could easily be pushed into "Playable" if these were to be fixed and I imagine they could possibly all be related to a single physics issue rather than individual problems.

**Comment by Hopefullyidontgetbanned** [comment]
This Part of a Larger Issue with the Physics in the main ps3 games. This is Especially Egregious in Story Levels in LittleBigPlanet 1. As You Can't Finish the 3rd level in LBP1 because it relies on the physics to move the checkpoint over a Fallen bridge as part of a tutorial.

**Comment by B-Knight49** [comment]
Yeah I gathered it was an issue with physics in general. Hopefully this and the log I've attached can help solve this issue though and actually improving the accuracy/speed of the emulator in general. Who knows, fixing this could sort out several problems with other games too.

**Comment by Kilowog01** [comment]
I come to update this thread. I made a level to test the 10 types of junction with 4 units of each, I recorded a video and a log. Xfloat and spu fast make no difference.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4141644/RPCS3.log.gz)
https://youtu.be/3_1q2IbzV3Y

**Comment by jeremybris** [comment]
Retest this with https://ci.appveyor.com/api/buildjobs/pe9poxs8twn8nig3/artifacts/rpcs3-v0.0.8-6fb3307a_win64.7z (elad's fix preview).

**Comment by B-Knight49** [comment]
Wasn't a complete fix, definitely feels like there's an improvement though. Pistons are still broken in many areas.

**Comment by tekofu** [comment]
After I heard LBP1 was playable I decided to try out this game as well. As far as this specific issue goes all "tools" (Motor bolt, Spring, Elastic) that were a problem now work properly and the level in question "Currant Affairs" is able to be completed. I recorded a short video to demonstrate and I feel like this issue can be closed. I actually had quite a bit of an issue with the level "Brainy Cakes" due to the hazardous gas not despawning on a specific puzzle but I would have to investigate further and was able to bypass it with a little luck.

RPCS3 Version: 0.0.10-10427-865180e6

https://www.youtube.com/watch?v=CAOrdMIYUQo

**Comment by jeremybris** [comment]
I agree, this was fixed for me after #7565. It should be retested. That said, tekofu, you are using the digital U.S. version vs. the disk European version reported here.

**Comment by BattleUrine** [comment]
> 
> 
> After I heard LBP1 was playable I decided to try out this game as well. As far as this specific issue goes all "tools" (Motor bolt, Spring, Elastic) that were a problem now work properly and the level in question "Currant Affairs" is able to be completed. I recorded a short video to demonstrate and I feel like this issue can be closed. I actually had quite a bit of an issue with the level "Brainy Cakes" due to the hazardous gas not despawning on a specific puzzle but I would have to investigate further and was able to bypass it with a little luck.
> 
> RPCS3 Version: 0.0.10-10427-865180e6
> 
> https://www.youtube.com/watch?v=CAOrdMIYUQo

can you tell me how you got past the Brainy Cakes level? im stuck on it right now and i kinda got a thing going by throwing the cakes at the wheel to make it spin ever so very slightly but one, its not enough force to make it spin over and two, the jelly wall is still a constant effect

**Comment by B-Knight49** [comment]
Not fixed on BCES01086.

Currant Affairs is my go-to level to check. As it currently stands, you can reach the end but the final door leading to the scoreboard doesn't open.

Recently, there's a piston at the very start of the level above a chicken and that now falls to the ground. About midway through the level there's sackbots being shaken around and behind them is a mechanical system with pistons - the system goes crazy and the things the pistons are attached to are flailing around wildly. 

Latest build RPCS3 0.0.10-10446.
LittleBigPlanet 2 Special Edition (UK Edition)

**Comment by dio-gh** [comment]
@B-Knight49 please retest with #8316

**Comment by B-Knight49** [comment]
Apologies, I've forgot how to download the open PR build - can you link me to a binary?

**Comment by dio-gh** [comment]
https://dev.azure.com/nekotekina/nekotekina/_build/results?buildId=2015&view=artifacts&type=publishedArtifacts

**Comment by B-Knight49** [comment]
No change, unfortunately. Still broken.

**Comment by Whatcookie** [comment]
Try with accurate xfloat off and spu llvm if you weren't before

**Comment by B-Knight49** [comment]
XFloat off did it - had LLVM on before, don't worry. 

Beautiful - finally aced the level too haha. 

Well, looks like I know what I'm doing for the rest of the day- time to test the game from beginning to end. Good job mate.

**Comment by elad335** [comment]
Still an issue? I believe the pull request which fixed it got partially reverted.

**Comment by B-Knight49** [comment]
Things look good from playing Currant Affairs. 

I don't have the time to test the whole game again right now though. 
@Kilowog01 and @tekofu - can you test with your levels?
