### ISSUE TITLE
Add timer options to GUI

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#6337]
Followup on https://github.com/RPCS3/rpcs3/issues/6260.
Some games do not like the automatically selected option of "Host" for sleep timings. For this reason, usleep timing should either be default, or the option should be easy to switch in GUI.

**Comment by dio-gh** [comment]
I'd opt for Usleep default *and* easy switching via GUI. There isn't a single game that improves for me with Host, seems to be a Ryzen × Linux thing.
