### ISSUE TITLE
performance lost in Project DIVA F & F 2nd

### ISSUE THREAD

**Issue by spiraluc** [RPCS3/rpcs3#6341]
With old build 0.0.6-8119 i have around 25-30FPS, but on any newer build only 10FPS.

I try this game on my friend PC with AMD GPU, but i got same result on openGL. If i try vulkan it goes full speed.

CPU: i5 2430M 
GPU: NVIDIA GT525M (openGL only)
RAM: 8GB

![NVIDIA(old build)](https://user-images.githubusercontent.com/54077874/62966654-c1623c80-be07-11e9-8d95-c60fe10142ca.png)
![NVIDIA(new build)](https://user-images.githubusercontent.com/54077874/62966655-c1623c80-be07-11e9-8fe5-f4c9c3fe3b49.png)
![AMD opegl](https://user-images.githubusercontent.com/54077874/62966666-c6bf8700-be07-11e9-8900-b5a602764d03.png)
![AMD vulkan](https://user-images.githubusercontent.com/54077874/62966667-c6bf8700-be07-11e9-902d-cf6beb15635c.png)
[AMD opegl.log](https://github.com/RPCS3/rpcs3/files/3498319/AMD.opegl.log)
[NVIDIA(new build).log](https://github.com/RPCS3/rpcs3/files/3498320/NVIDIA.new.build.log)
[NVIDIA(old build).log](https://github.com/RPCS3/rpcs3/files/3498321/NVIDIA.old.build.log)
[AMD vulkan.log](https://github.com/RPCS3/rpcs3/files/3498322/AMD.vulkan.log)

**Comment by AniLeo** [comment]
What build regressed it exactly? Also note that your CPU is way too weak for RPCS3, way below recommended requirements.

**Comment by spiraluc** [comment]
No matter what build i use. I have FPS drop since 0.0.6-8119. But i think the slowdown started after rsx: Surface cache improvements #5937.

**Comment by kd-11** [comment]
Haven't had time to check this properly, but its definately a strange bug. You can "fix" it by running the game at any resolution scale below 100%. For me, even 99% is fast but 100% is slow. I'll check it soon.

**Comment by kd-11** [comment]
Turns out this is not actually our bug. It seems most drivers did not bother to implement pixel unpack operations in hardware so its emulated by the driver in software mode. This means I need to write some compute kernels for OpenGL to actually do this in hardware for them. I'll try and get it done soon.

**Comment by kd-11** [comment]
I've implemented some basic transforms in [this build.](https://ci.appveyor.com/project/kd-11/rpcs3/builds/27860532) Check if it improves performance for you. On my desktop performance is back to normal, but mobile systems may struggle with compute for all we know.

**Comment by spiraluc** [comment]
In PD1 i see no improvement on logo, menu or song select but ingame i have playable FPS. 
In PD2 i have now 30FPS on logo, loading, song start, but game start, song select and ingame is too slow.

**Comment by spiraluc** [comment]
It's still slow like before but i see around 1-2FPS improve

**Comment by AniLeo** [comment]
If you have at least the same performance you had before, it can be closed

**Comment by spiraluc** [comment]
After merging the performance is same like i describe before. I see some improvements, but the old build 0.0.6-8119 is still much faster.

**Comment by spiraluc** [comment]
[Desktop.zip](https://github.com/RPCS3/rpcs3/files/3747636/Desktop.zip)

There is comparison between old build, build before merge and build after merge. 

I see strange behavior, because some parts in the old build that were previously slow are now fast and those that were fast are now slow.

**Comment by kd-11** [comment]
Need comparison on PDF1 which seems to run fine. I don't have PDF2

**Comment by kd-11** [comment]
I have identified a point of optimization that may help with the situation.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/7260
It's not possible to match "old build" performance as old builds were missing a bunch of features needed to emulate other titles, but that PR should, in theory, get as close as it is possible to do so, to reasonable performance on that GPU.

**Comment by spiraluc** [comment]
Yes, now PD1 run 30FPS stable on all stages and PD2 too, but one stage is still slow.

OLD
![8119 5](https://user-images.githubusercontent.com/54077874/72554797-b1a9c100-389b-11ea-95bf-64c34b54f5f7.png)
NEW 
![5](https://user-images.githubusercontent.com/54077874/72554829-c1c1a080-389b-11ea-8403-51de28b0786a.png)

**Comment by kd-11** [comment]
Unfortunately its not possible to optimize further, the step that was added there is critical but can cause performance slowdown on old hardware. Note that this game runs with 4x SSAA which means that when its saying 720p its actually rendering at 1440p internally. That is the reason for the troubles. You can get native 1080p for example by actually using 75% resolution scale or 720p using 50% scaling.
I think what we have with the PR is the best possible outcome.

**Comment by spiraluc** [comment]
Now it´s run fine. I can not complain :)
