### ISSUE TITLE
Instablilty in Ratchet and Clank Future: Tools of Destruction

### ISSUE THREAD

**Issue by stride21** [RPCS3/rpcs3#6349]
Ratchet and Clank Future: Tools of Destruction can randomly hang when ingame. RPCS3 doesn't crash, it just shows a still image and it can still have the background audio playing even after it hangs.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3506352/RPCS3.log.gz)

**Comment by allhailbilloverbeck** [comment]
this has actually been an issue for a long time, long before #6293

**Comment by elad335** [comment]
@isJuhn also exprienced and debugged this issue, he can confirm its an issue probably appearing since the game went ingame on rpcs3 for the first time.

**Comment by isJuhn** [comment]
Yes, some time ago I tried to bisect but I couldn't find a build where it didn't happen. Here's a patch to bypass the issue on BCES00052 disc version
```
PPU-c4e26433d1eed9166eb0c67b6f66b2268f3704e2: #BCES00052 R&C ToD Freeze fix
  - [be32, 0x5056f0, 0x409efff0]
```

**Comment by stride21** [comment]
The frequency of crashes after this PR is some much more than the previous build for me. I have yet to complete the first planet and get to where it crashes after the cutscene with over 10 attempts at it. If you guys really think this is an old issue, I'll close it.

**Comment by isJuhn** [comment]
rename it since that PR is not the cause of the issue

**Comment by stride21** [comment]
@isJuhn Wouldn't this be covered under the issue on Ratchet & Clank Future that you opened? I only opened this issue because ToD on the PR was having significantly more crashing for me but the PR isn't the cause of the crashing.

**Comment by stride21** [comment]
Closing this issue since its unrelated to any PR and stability issues with Ratchet and Clank Future games are covered by issue #4258.
