### ISSUE TITLE
Crashes with MultiThreaded RSX when using Write Color Buffers/CPU Blit

### ISSUE THREAD

**Issue by CaptainStarPaw** [RPCS3/rpcs3#6351]
### Video
https://youtu.be/lJ4sEny8rTQ

### Log file for v0.0.6-8501-a0f0c418
https://bit.ly/2KLhheX

### Specification
`RPCS3 v0.0.6-8501-a0f0c418 Alpha | HEAD | Firmware version: 4.84
Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz | 12 Threads | 15.93 GiB RAM | TSC: Bad | AVX+ | TSX-FA
Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0
·! 0:00:00.000000 RSX: Found vulkan-compatible GPU: 'GeForce RTX 2070' running on driver 431.60.0.0`

### Notes
This can be consistently replicated with a fresh install of RPCS3. LLVM with all cache/dev_hdd1 and configs freshly created.

I have already troubleshooted in the #help channel on Discord to no avail. I am running the game using recommended settings. I have tried many different combinations of settings to see if it affects the freeze, but it would seem that nothing fixes it.

Thank you!

**Comment by kd-11** [comment]
Try disabling RSX multithreading. I identified a potential deadlock bug with it recently but haven't yet pushed a patch for it, so it can actually cause the emulator to lock up.

**Comment by Colibri-Pawel** [comment]
> Try disabling RSX multithreading. I identified a potential deadlock bug with it recently but haven't yet pushed a patch for it, so it can actually cause the emulator to lock up.

By jove Sir, that was precisely the cause of the issue. I disabled RSX multithreading and bam, problem gone. Thank you so much for the recommendation. Looking forward to the patch!

**Comment by CaptainStarPaw** [comment]
> 
> 
> Try disabling RSX multithreading. I identified a potential deadlock bug with it recently but haven't yet pushed a patch for it, so it can actually cause the emulator to lock up.

By jove Sir, that was precisely the cause of the issue. I disabled RSX multithreading and bam, problem gone. Thank you so much for the recommendation. Looking forward to the patch!

**Comment by Asinin3** [comment]
Can you please test with https://github.com/RPCS3/rpcs3/pull/6377 to see if it fixes it for you when MT RSX is enabled?

**Comment by CaptainStarPaw** [comment]
@Asinin3 @kd-11 Thank you both. I noticed the PR is still open, is there an automated build available or would you require me to build locally?

**Comment by dio-gh** [comment]
It's at the bottom of the PR page; see AppVeyor details there if you are using Windows.

**Comment by CaptainStarPaw** [comment]
> 
> 
> It's at the bottom of the PR page under `Show all checks`; see AppVeyor details there if you are using Windows.

Thank you @dio-gh

**Comment by CaptainStarPaw** [comment]
@Asinin3 @kd-11 Unfortunately I am unable to replicate the run because it crashes almost immediately after it loads my save. This crash occurs approximately 2-4 seconds after I can see my character and run around.

**Comment by CaptainStarPaw** [comment]
@kd-11 Log file https://bit.ly/2KM72qU

**Comment by Asinin3** [comment]
Can you rename this to "Crashes with MultiThreaded RSX when using Write Color Buffers"? I'm pretty sure that it only affects games that are using Write Color Buffers. Here's what I found with Modnation Racers:

Vulkan - Goes ingame fine, but graphics are broken without WCB
Vulkan+WCB - Goes ingame just fine
Vulkan+WCB+MT RSX - Crashes where the game used to crash (on loading screen right before the title-screen.
Vulkan+MT RSX - Goes ingame just fine except graphics are wrong due to no WCB.

https://github.com/RPCS3/rpcs3/pull/6377 did not fix the issue either.

**Comment by kd-11** [comment]
Pushed a new fix, please confirm if it fixes the problems for you.

**Comment by Asinin3** [comment]
Yeah everything is fixed by the looks of it from a quick test, thanks!
