### ISSUE TITLE
Persona 5 on compatibility list?

### ISSUE THREAD

**Issue by densandwitch** [RPCS3/rpcs3#6352]
I noticed that Persona 5 isn't on the compatibility list for some reason despite it being a very popular game and is talked about on this site. I am using version v0.0.6-8501 Alpha and the game is playable on my computer fully from start to end, of course with some pop up problems. My PC is high end though, but I still think that qualifies for "Playable". If there was a way to add it without notifying you all my apologizes.

**Comment by RainbowCookie32** [comment]
The game is listed as Unnamed in the list, due to past problems with Atlus.

GitHub is not the place for this kind of questions. Use our Discord server for this next time https://discord.me/RPCS3

**Comment by Tenkuuu** [comment]
That is because Atlus sued RPCS3 some time ago for the fact that they could run it on PC. It's a lot more than what I just told tbh. Check this for more info:
https://www.reddit.com/r/emulation/comments/72lo12/statement_atlus_usa_attempts_to_shut_down/

**Comment by RainbowCookie32** [comment]
Just for future reference, they didn't sue RPCS3. Atlus "just" sent a DMCA takedown request to Patreon, so they'd shut down the emulator's Patreon. The issue can be closed now, since it's not really one, and the question was answered.

**Comment by AniLeo** [comment]
Removed misleading comment

Link for reddit thread with the relevant information is https://www.reddit.com/r/emulation/comments/72lo12/statement_atlus_usa_attempts_to_shut_down/
