### ISSUE TITLE
[Regression] Random freezes/crashes on Dante's Inferno

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#6353]
Game is no longer stable and crashes with various types of errors when using SPU LLVM - unhandled exception popups, mem access freezes, "sys_spu_thread_group_join' failed" errors, etc. 

This occurs in menus, during cutscenes, first fight or making your way to Death battle. ASMJIT is more stable, though it did freeze for me post Death fight (existing issue?). 

Not sure yet the build that broke it but it's believed to be recently. Issues confirmed on Discord by other users. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3508228/RPCS3.log.gz)

UPDATE:
- Seems to happen with both SPU ASMJit and LLVM. 
- The more (valid) cache you have, the more stable it is. 

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by legend800** [comment]
Actually, after playing more, I continue to advance further and further (so maybe something to do with the caching....). 

Here's a log of a full playthrough on SPU LLVM from start to first save point with no issues. Maybe I should close this unless others have more details. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3508285/RPCS3.log.gz)

**Comment by Xcedf** [comment]
I should say Dante's Inferno was never stable on SPU LLVM, if you boot the game with no SPU Cache on LLVM right after the intro movie you'll have
F {PPU[0x1000011] Thread (RWAC Dac) [0x00803da0]} MEM: Access violation reading location 0x4e800040
But if you build some cache with ASMJit  before, than load with LLVM again it accept it and you'll play further.
On the other hand LLVM became more stable, previously there were places in the game when sound cuts off and after a short time game crases on SPU LLVM. Here's one of those places:
![12](https://user-images.githubusercontent.com/7060586/63149032-abbd6480-c00b-11e9-9ffa-a584e4c7d7a3.jpg)
In this place game stopped produce sound and crashed before but on recent builds this is a problem no more, but Access violation issue if there's no cache still exist.

**Comment by legend800** [comment]
So you're basically saying the game is as stable as it's ever been but the issue where you need cache from SPU ASMJIT persists? That may explain why some of us thought it regressed - because the SPU cache was invalidated by some recent build.

**Comment by web1018** [comment]
The crashes/Freezing are very random and happen at any point with Asmjit or LLVM options. I have tested it several times as well and the game keeps freezing at the Caravan point where a fight takes place on top of a giant boat. I believe there is a serious issue facing the game. Someone on Discord said it may have something to do with the "Framelimit" Because with the option OFF, the game runs over 180 FPS.

**Comment by legend800** [comment]
@web1018 
Yeah, I think framelimit = Auto is needed here. 

So you can confirm this instability is new, correct? It was working fine for you before? If so, any idea when this became a problem?

I'll update title to reflect that it's not just LLVM. I did get a freeze with ASMJit (after the Death fight). The more (valid) cache you have though, the more stable it is it appears.

**Comment by Asinin3** [comment]
It would help if you find where the game actually broke though? Maybe try before the SPU PIC Pull Request from Neko merged and try from there?

**Comment by web1018** [comment]
> @web1018
> Yeah, I think framelimit = Auto is needed here.
> 
> So you can confirm this instability is new, correct? It was working fine for you before? If so, any idea when this became a problem? The more (valid) cache you have though, the more stable it is it appears.
> 
> I'll update title to reflect that it's not just LLVM. I did get a freeze with ASMJit (after the Death fight).

Even with "Framelimit" set to  "Auto" it still crashes/Freezes. Most of my tests were done with that option and it still Frooze with Asmjit and LLVM option. I used to be able to play with Asmjit option without rapid crashes but the crash was still present in LLVM in the previous versions. But as time went by it got a lot worse, I am not sure from which update it made it worse, but Ill will take a look into it.

**Comment by Asinin3** [comment]
I was the one who mentioned the auto frame-rate in Discord. It was needed for me to reach the title-screen. On-top of using Asmjit.

**Comment by web1018** [comment]
> I was the one who mentioned the auto frame-rate in Discord. It was needed for me to reach the title-screen. On-top of using Asmjit.

Oh yes, thank you for taking a look at it as well. I noticed that with Asmjit you are able to play a bit more but then it freezes as well a bit after where LLVM would usually freeze. I switched as many options as I could and it still made no different with the freezing.

**Comment by web1018** [comment]
> > I was the one who mentioned the auto frame-rate in Discord. It was needed for me to reach the title-screen. On-top of using Asmjit.
> 
> Oh yes, thank you for taking a look at it as well. I noticed that with Asmjit you are able to play a bit more but then it freezes as well a bit after where LLVM would usually freeze. I switched as many options as I could and it still made no different with the freezing.

I still havent mentioned the DLC content as well, such as the Trial of St Lucia. Which is more playable but it freezes as well.

**Comment by legend800** [comment]
Thanks to web1018, it looks like using PPU Interpreter (fast) fixes all stability and physics issues. 

So the issue seems to lie in the PPU LLVM.

**Comment by Xcedf** [comment]
SPU LLVM issue should be resolved, was able to start the new game with no cache from scratch, please confirm

**Comment by legend800** [comment]
Ok, closing this and we can create a new one for any remaining (specific) issues.
