### ISSUE TITLE
BLAS50682-[SHIN GUNDAM MUSOU]  frezzed when loading

### ISSUE THREAD

**Issue by lingdomking** [RPCS3/rpcs3#6362]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3511643/RPCS3.zip)
Here is the log
i7-9700k
RTX2070 8G
16G DDR4
RPCS3 Version: 0.0.6-8499-9f854dba Alpha

**Comment by elad335** [comment]
Seems like the same issue as #4522, even address of access violation is the same.
Comment on that issue and close this one.

**Comment by lingdomking** [comment]
> 似乎与[＃4522](https://github.com/RPCS3/rpcs3/issues/4522)相同的问题，甚至访问冲突的地址和违反线程的名称都是相同的。
> 评论这个问题并关闭这个问题。

But it is not the same game serial，I had tried it，DYNASTY WARRIORS: GUNDAM Reborn [BLES02057] is really right and fixed
真・鋼彈無雙 [BLAS50682] is not fixed
Or the code I written is wrong？

PPU-da76bae72f6d8fef4865e63c4e75e91d8b7204ac : #Dynasty Warriors Gundam Reborn BLES02057 hack
  - [be32, 0x212494, 0x63e30000]

PPU-d526f54bfa95c26ecb612318f58a49c62ea53915: #Dynasty Warriors Gundam Reborn NPUB31531 hack
  - [be32, 0x212464, 0x63e30000]

PPU-3cea7a3a766105e781d7cd3379c569baf7a565e8: #真・鋼彈無雙 BLAS50682 hack
  - [be32, 0x212494, 0x63e30000]

**Comment by elad335** [comment]
Sorry, its still a duplicate.

**Comment by lingdomking** [comment]
> Sorry, its still a duplicate.

OK，let me check the formation，thank you so much

**Comment by tqhnar** [comment]
那么，请问这问题解决了吗

**Comment by lingdomking** [comment]
> 那么，请问这问题解决了吗

转到4522，中文版暂时不行，欧版可以

**Comment by lingdomking** [comment]
> Sorry, its still a duplicate.

Here is different crash code with the patch.yml
F 0:02:17.016624 {PPU[0x1000036] Thread (CAppResourceLoad) [0x0017e314]} MEM: Access violation reading location 0x3f
I can paly some DLC mission in Ultimate Mode,Offical Mode still crash

[RPCS3 2019.8.19.zip](https://github.com/RPCS3/rpcs3/files/3514122/RPCS3.2019.8.19.zip)

**Comment by AniLeo** [comment]
Comment on 4522
