### ISSUE TITLE
Twisted Metal™ Demo [NPUA70192]  crashes out with Invalid RSX method

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6363]
crashes out after one loading screen
[RPCS3 log.zip](https://github.com/RPCS3/rpcs3/files/3511838/RPCS3.log.zip)

**Comment by kd-11** [comment]
How many times did you try? Your system desychronized, probably due to excessive stuttering when compiling SPU LLVM objects. I'm seeing a lot of trampoline simplified messages; did you try with interpreters? Desync events are a symptom of the problem and not the cause.

**Comment by benderscruffy** [comment]
no matter what i choose now comes up with a fatal error 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3536758/RPCS3.zip)

**Comment by Jhonny-2005** [comment]
[logs.zip](https://github.com/RPCS3/rpcs3/files/3542488/logs.zip)
It`s my logs in TM.

**Comment by benderscruffy** [comment]
ok doesnt fatal error anymore
comes up with a runtime_error thrown now
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3589684/RPCS3.zip)

**Comment by benderscruffy** [comment]
ok goes ingame now
![twisted](https://user-images.githubusercontent.com/2696404/66392543-bc35fe00-ea02-11e9-830c-e2cca3687bd3.PNG)
