### ISSUE TITLE
Regression: Some games regressed to Loadable (#5111)

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#6365]
Tried different settings, but no luck, the game throws this error before rendering of graphics:
`F {PPU[0x1000005] Thread (UnityMain) [0x000ff458]} class std::runtime_error thrown: Trap! (0xff458)`

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3512149/RPCS3.log.gz)

---

List of known affected games:
- Asdivine Hearts [NPUB31850]
- Revenant Saga [NPUB31863]

**Comment by benderscruffy** [comment]
still an issue 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3689479/RPCS3.log.gz)

**Comment by kd-11** [comment]
In cases of Trap! it is worth including TTY.log as it contains the actual crash information related to the assert the game is throwing.

**Comment by benderscruffy** [comment]
here is the tty.log
[TTY.log](https://github.com/RPCS3/rpcs3/files/3692757/TTY.log)

**Comment by digitaldude555** [comment]
Last worked in 0.0.5-7338 build and broke 0.0.5-7345.
#5111 broke it.

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by Megamouse** [comment]
weird. these games are not in the loadable section

**Comment by AniLeo** [comment]
Still an issue? If it is, the games need to be moved to Loadable

**Comment by AniLeo** [comment]
Confirmed to still be an issue

**Comment by AniLeo** [comment]
Still an issue, these games were retested again with new logs, reports present on the forums: https://forums.rpcs3.net/thread-179705.html

Tested build: RPCS3 v0.0.25-14474

[AsdivineHearts.log.gz](https://github.com/RPCS3/rpcs3/files/10221719/AsdivineHearts.log.gz)

[RevenantSaga.log.gz](https://github.com/RPCS3/rpcs3/files/10221720/RevenantSaga.log.gz)

These are the last 2 games in the Loadable section
