### ISSUE TITLE
Linux crash

### ISSUE THREAD

**Issue by rcaridade145** [RPCS3/rpcs3#6367]
When running rpcs3-v0.0.6-8514-050339bb_linux64.AppImage  on Linux (Ubuntu 19.04) i get this everytime i start a game (PPU caches removed etc) rpcs3-v0.0.6-8492-4df1c160_linux64.AppImage runs ok.

Thread 38 "PPU[0x1000004] " received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff02ffd700 (LWP 3047)]
0x00007ffff4c9ffbf in _Unwind_Resume ()
   from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) bt full
#0  0x00007ffff4c9ffbf in _Unwind_Resume ()
   from /lib/x86_64-linux-gnu/libgcc_s.so.1
No symbol table info available.
#1  0x0000000000830e1a in _sys_lwcond_queue_wait(ppu_thread&, unsigned int, unsigned int, unsigned long) ()
No symbol table info available.
#2  0x000000000080210b in $_80::__invoke(ppu_thread&) ()
No symbol table info available.
#3  0x0000000000752d7f in ppu_thread::exec_task() ()
No symbol table info available.
#4  0x0000000000752788 in ppu_thread::fast_call(unsigned int, unsigned int) ()
No symbol table info available.
#5  0x0000000000751cd8 in ppu_thread::cpu_task() ()
No symbol table info available.
#6  0x00000000009be1ec in cpu_thread::operator()() ()
No symbol table info available.
#7  0x000000000074f639 in named_thread<ppu_thread>::entry_point(void*) ()
No symbol table info available.
#8  0x00007ffff6df5182 in start_thread (arg=<optimized out>)
    at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140733243709184, 
                3402256401433784148, 140734736886062, 140734736886063, 0, 
                140733243706752, -3402122260511559852, -3402236879693779116}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#9  0x00007ffff4bbfb1f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by Nekotekina** [comment]
It should be fixed on master, but I'll ask to confirm.

**Comment by rcaridade145** [comment]
Tested it with the new build and it is OK for me now

**Comment by RainbowCookie32** [comment]
You can close the issue then
