### ISSUE TITLE
SPU LLVM Regression (Ratchet & Clank Future: A Crack in Time)

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#6372]
After https://github.com/RPCS3/rpcs3/pull/5770 merged, R&C A Crack in Time refuses to boot with the SPU LLVM recompiler. This is 100% reproducible.

[After Merge (Broken).zip](https://github.com/RPCS3/rpcs3/files/3513319/RPCS3.zip)
[Before.log.gz](https://github.com/RPCS3/rpcs3/files/3513318/RPCS3.log.gz)

[SPU Log.zip](https://github.com/RPCS3/rpcs3/files/3513321/spu.zip)
SPU IR log is here: 
[spu-ir.log.gz](https://github.com/RPCS3/rpcs3/files/3513324/spu-ir.log.gz)

**Comment by incognitoh** [comment]
LLVM boots fine for me...but it didnt used to. I think disabling TSX fixed it though..but idk about Ryzen. 

i7
Win10

**Comment by Asinin3** [comment]
Well, i can at least say that many other users are experiencing the same problem, when we released the last YouTube video showcasing Ratchet & Clank ACiT many people were commenting it didn't boot and I replied to them saying to use Asmjit and ~4 people said it fixed it for them. So it's not just me at least. And with Ryzen I obviously don't have TSX. I was also using safe block size and cleaned caches, so i don't think it can be anything wrong with my settings. Perhaps just a bad code path for ryzen or something?

**Comment by incognitoh** [comment]
Yea I know it doesnt have TSX, that why I said Idk about Ryzen. But like I mentioned, I definitely experienced the same freeze other people have but it works now for some reason. not sure exactly what fixed it but I think it was after I disabled TSX. whats strange is, after that, it now works with tsx enabled. very odd... my SPU settings is 1 thread, MEGA and just SPU cache enabled.

**Comment by incognitoh** [comment]
maybe it wasnt tsx..i changed ppu(not spu) threads to 4(was at 2) and it wouldnt boot again with spu llvm. but if i left it at 4 and changed max spurs to 5, it booted with spu llvm.  so maybe try different ppu and spurs values?

**Comment by Asinin3** [comment]
Still an issue with v0.0.7-8855-9242f165

**Comment by doesthisusername** [comment]
I just spent a few hours looking at this. I know basically nothing about the SPU, but the short of it is that it seems to be a `rdch $81,$SPU_RdSigNotify1` instruction (present in both A Crack in Time and Into the Nexus, in an identical block), where, after reached by the recompiler, said block seems to be recompiled successfully (?), but then chokes very soon after, something like the next block (tested with setting Max LLVM Compile Threads to 1). This also seems to be reflected in the SPU log posted above, as said block is quite near the bottom of it.

If I change the instruction to `rdch $81,$SPU_RdSigNotify2`, the same thing happens; if I nop it, or change it to `rdch $81,$MFC_RdAtomicStat`, the game starts, but hits a trap very soon after, which may or may not be related.

Additionally, I did not see any other `rdch` instructions accessing those channels earlier in the log, nor in other games (well, game, I looked at NPEA00385 Ratchet & Clank), making me think the problem could lie there, but I am not familiar enough with RPCS3/LLVM/SPU to say.

This was all tested on 8871. Hope it helps someone more knowledgeable.

**Comment by Asinin3** [comment]
Gets a bit further now, probably because of Nekotekina's recent Asynchronous SPU Compilation Pull Request. Window opens before it crashes now. 
![image](https://user-images.githubusercontent.com/15137035/67304042-ceec1f00-f53a-11e9-90ff-3587d845b53e.png)

**Comment by Asinin3** [comment]
![image](https://user-images.githubusercontent.com/15137035/69558474-36910080-0ff8-11ea-9acd-54ed354fec91.png)
Works for me now, dunno what fixed it though :/
