### ISSUE TITLE
 Catherine [BLUS30428]: Wrong color (regression)

### ISSUE THREAD

**Issue by leopard20** [RPCS3/rpcs3#6373]
Red colors have somehow turned into blue:
![Screenshot (22)](https://user-images.githubusercontent.com/16115820/63232106-0e944300-c23a-11e9-86da-9e26bf2c6bfd.png)
Doesn't happen in the cutscenes. Only the world is affected.

Last working build I tested was 0.0.6-8200. I'm not sure since when it started but all builds from 0.0.6-8444 up to the latest have this problem.

This is on Vulkan backend, of course. Didn't test OGL.

OS: Windows 8.1 64 bit; 
GPU: GTX 760m; driver version 425.31 
CPU: Core i7 4700HQ

**Comment by RainbowCookie32** [comment]
Try disabling Antialiasing in the GPU tab. If it works properly, then it's a duplicate of #6103

**Comment by leopard20** [comment]
Yes. It worked.
