### ISSUE TITLE
Regression: NCAA14 No facemasks and blocky cold breath (#6357)

### ISSUE THREAD

**Issue by huskereurocat** [RPCS3/rpcs3#6380]
In this photo you can see that the left side of the screen is now blurry. I say now because this became noticeable with the release of build 8534. It wasn't in 8531 and has been in every build since 8534.  Still have the issues of no face masks and seeing the square clouds of breath when playing in a cold climate or foggy game. Haven't tried snowy conditions, but will try that next. BTW, is this the best place to put feedback stuff like this?
![Desktop Screenshot 2019 08 19 - 19 29 06 45](https://user-images.githubusercontent.com/52609668/63311020-742c1200-c2c2-11e9-86ec-b8318ba9a440.png)

The original PR that this issue sprang from.  https://github.com/RPCS3/rpcs3/pull/6357

**Comment by Asinin3** [comment]
Yes, this is the place to post issues but you should link the Pull Request which broke it like so: https://github.com/RPCS3/rpcs3/pull/6357 in the comments so its referenced and the developers know what broke it.

**Comment by huskereurocat** [comment]
So its the PR associated with the build #, correct? Good to know the dev team goes by the PR. Thanks!

**Comment by Emulator-Team-2** [comment]
@huskereurocat 
Can you retest with the latest master build.

**Comment by huskereurocat** [comment]
The screen being blurry is fixed with the 8568 build. Do I need to make a new issue report for the facemasks and blocky cold weather breath?

**Comment by AniLeo** [comment]
It will need an RSX capture, you can add one here, wait for #6790 to be merged then take one with its master

**Comment by huskereurocat** [comment]
This should have been closed because that is working already. I do feel the need to open a new request concerning the night time shader issue where the apron of the stadium is black and of course the choppy sound is still an issue. Should I open a new issue?
![Desktop Screenshot 2019 08 30 - 21 30 01 43](https://user-images.githubusercontent.com/52609668/67091338-fffed500-f171-11e9-9d1b-574fc2c2fcc4.png)

**Comment by Asinin3** [comment]
If it should be closed, then click the close issue button 🤔

**Comment by AniLeo** [comment]
If it does not concern the regression, it needs a new issue yes.
