### ISSUE TITLE
LittleBigPlanet 2 [NPUA80662] Crashes after completing or exiting a level

### ISSUE THREAD

**Issue by ajunior7** [RPCS3/rpcs3#6382]
**Using build v0.0.6-8536**

**System Information:**
i5 8400 
16GB RAM
GTX 1060 6GB
Windows 10 Build 1809

Log: (93MB uncompressed, 4MB compressed): [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3520191/RPCS3.zip)
Log.gz: N/A (The emulator crashes before it can give me Log.gz)

**Issue**
Upon completing or exiting a level in LittleBigPlanet 2, the game crashes along with the emulator. This has been a problem since build **8524**.

This issue can be replicated by going in to any random level and exiting as shown in the gif below:

https://gfycat.com/admirableclumsycutworm

**Comment by B-Knight49** [comment]
For me it hangs / freezes rather than crashes. UK edition of the game; BCES01086

**Comment by B-Knight49** [comment]
Uses an ancient, pre-release debug build of the game doesn't do this, weirdly. Not sure if that's of any help but could potentially narrow things down if the offending function/instruction can't be identified.

**Comment by digitaldude555** [comment]
No longer an issue.
