### ISSUE TITLE
Trophy manager crashes after commit f051f53 (#6326)

### ISSUE THREAD

**Issue by GitArUs** [RPCS3/rpcs3#6386]
Linux (Fedora 30).
After commit f051f53 RPCS3 crashes whenever I try to open trophy manager (RPCS3: fatal error, Segfault reading location [number] at [the same number]). It happens for downloaded appimage as well as for self-compiled binary.
Output from terminal window in the attachment:
[trophy_crash_terminal_output.txt](https://github.com/RPCS3/rpcs3/files/3522468/trophy_crash_terminal_output.txt)

**Comment by GitArUs** [comment]
Backtrace. It's from RelWithDebInfo build, Debug build can not finish final linking because of some undefined reference.
[trophy_backtrace.txt](https://github.com/RPCS3/rpcs3/files/3526647/trophy_backtrace.txt)

**Comment by Megamouse** [comment]
Try this pull request:
https://github.com/RPCS3/rpcs3/pull/6272

If you are building with linux you should add QtConcurrent to Qt Modules.

**Comment by GitArUs** [comment]
Works fine in #6272. Let me retest after merge.

**Comment by Megamouse** [comment]
Please retest

**Comment by GitArUs** [comment]
The crash is gone. Thank You. Closing this.
