### ISSUE TITLE
METAL GEAR SOLID 4 Controller Issue

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#6389]
I'm trying to test MGS 4 BLES00246 02.00
Game install is complete.
My controller (Logitech F710) has stopped to work in the start menu (new game,options,...) but was working at the game's launching (I tried to change any RPCS3 configs by changing LLVM,ASMJIT,...but with same results).

I79700K
GTX1080
16go RAM
Windows 10

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3526621/RPCS3.log)

**Comment by dio-gh** [comment]
Misleading. The controls might lock up randomly for everyone due to race conditions currently.

**Comment by Pouncha** [comment]
Ok...I'll wait for this fix

**Comment by pitrako** [comment]
> Misleading. The controls might lock up randomly for everyone due to race conditions currently.

What are race conditions?

**Comment by pitrako** [comment]
> I'm trying to test MGS 4 BLES00246 02.00
> Game install is complete.
> My controller (Logitech F710) has stopped to work in the start menu (new game,options,...) but was working at the game's launching (I tried to change any RPCS3 configs by changing LLVM,ASMJIT,...but with same results).
> 
> I79700K
> GTX1080
> 16go RAM
> Windows 10
> 
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/3526621/RPCS3.log)

I didn't know before but currently It freezes due to "unsolvable RSX issues" or something like that. The game locks to 24 fps and nothing moves, no configuration resolves the problem for now I think.

**Comment by AniLeo** [comment]
There is no controller issue, the game just locks up randomly as mentioned as it's still unstable. Closing as actual controls work fine.

**Comment by Miste-core** [comment]
i have the exact same issue but with dualshock 4
