### ISSUE TITLE
LLVM Graphic downgrade issue (God Of war 3 example)

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#6390]
Here's some glitches happens when I use LLVM in the game God Of War 3 (BCES00510 v1.03)
[GOW3LLVM-1](https://user-images.githubusercontent.com/54372547/63459378-b8e7b280-c454-11e9-91c8-bad587876f25.jpg)
![GOW3LLVM-2](https://user-images.githubusercontent.com/54372547/63459389-bc7b3980-c454-11e9-960d-d7165ef01d17.jpg)

But those glitches are no more when I use ASMJIT (but I lose FPS)

![GOW3ASMJIT-1](https://user-images.githubusercontent.com/54372547/63459433-ce5cdc80-c454-11e9-9cab-295f8dc2856b.jpg)
![GOW3ASMJIT-2](https://user-images.githubusercontent.com/54372547/63459441-d0bf3680-c454-11e9-9557-780ccd11a143.jpg)

It seems that LLVM recompiler downgrades graphics displaying (probably in any other games)

I7 9700K
GTX 1080
16go RAM
Windows 10 1809

Logs (with ASMJIT & LLVM)
[RPCS3(WithASMJIT).log](https://github.com/RPCS3/rpcs3/files/3526816/RPCS3.WithASMJIT.log)
[RPCS3(WithLLVM).log](https://github.com/RPCS3/rpcs3/files/3526817/RPCS3.WithLLVM.log)

**Comment by RainbowCookie32** [comment]
Isn't this the same as #5886 ? Can't really tell by the pictures, but I assume it might be that

**Comment by legend800** [comment]
Looks like a dup, yes, please add your comments to that one and close this. Thanks!

**Comment by Pouncha** [comment]
I dunno if it's same as #5886 coz I have no banners,no color changes...just multi glitches spots
![63459378-b8e7b280-c454-11e9-91c8-bad587876f25](https://user-images.githubusercontent.com/54372547/63496344-077f6600-c4c2-11e9-8bd5-b633322562d9.jpg)

**Comment by Pouncha** [comment]
I just checked.
Yep,it the same pb as #5886...
I close this topic
