### ISSUE TITLE
[Feature Request] RPCS3 should offer useful command output

### ISSUE THREAD

**Issue by Fisk24** [RPCS3/rpcs3#6398]
When using RPCS3 from the terminal (or the command prompt as i imagine it would be the same in that case), the program does not attempt to tell the user that they have issued the command incorrectly. 

This is especially aggravating when pointing the emulator to an EBOOT.BIN. As if the user types the file location incorrectly (or in my case has a space in the directory string) The emulator just opens normally and acts like I didn't just tell it to do something. Most any other program when evoked from the command line would simply tell me that the file doesn't exist and exit. 

   For example, if I tried to pass the string "some/dir/with some spaces" the program might return something like "the file 'some/dir/with' does not exist." And the program would exit. Do not pass go. Do not collect $100. Why? because the program read until the space and assumed that what ever came after it was a different argument.

   RPCS3 also does this, but you would never know unless you happened to guess that this was the case. Please allow the emulator to explain to me what I did wrong so that my self and others don't waste time trying every permutation of quotes and escapes only to give up and remove spaces from every folder and file involved.

I believe that this issue is platform agnostic but as per the guide lines here are my specs
RPCS3 Version: v0.0.6-795-gb70908c8f
Platform: Manjaro Linux
Intel® Core™ i7-4720HQ CPU @ 2.60GHz × 8 
GeForce GTX 965M/PCIe/SSE2

**Comment by seanocali** [comment]
CLI feedback is sorely needed when launching —no-gui from a front end. No indication the game launched or failed, and if it needs to compile modules it could be 5 minutes for the game to launch. And no way to cancel.

**Comment by Megamouse** [comment]
I think this is mostly implemented.
Specifics can be discussed in newer tickets.
