### ISSUE TITLE
Split/Second [NPUB30450] Game has severe gfx issues

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#6399]
Split Second currently has several issues:

1) GFX: Weird tiling issue throughout the menus and gameplay. Broken and smearing skybox. Boxy smoke and explosions. 

2) Extreme performance issues, only runs at ~6 fps. 

I've tried various settings but doesn't change much. WCB fixes skybox a little but makes the tiling issue much more prevalent (see below).

![2019-08-23 20_37_21-Window](https://user-images.githubusercontent.com/20983844/63632182-92598100-c5e6-11e9-81a1-a81ab8053669.png)
![2019-08-23 20_38_38-Window](https://user-images.githubusercontent.com/20983844/63632183-92598100-c5e6-11e9-943f-c69c5ecb1885.png)
![2019-08-23 20_34_57-Window](https://user-images.githubusercontent.com/20983844/63632184-92f21780-c5e6-11e9-941a-7e5b0745f7b6.png)
![2019-08-23 20_36_31-Window](https://user-images.githubusercontent.com/20983844/63632185-92f21780-c5e6-11e9-99f7-15d63162b355.png)

WCB on:
![2019-08-23 20_44_13-Window](https://user-images.githubusercontent.com/20983844/63632206-da78a380-c5e6-11e9-8f6b-b6d2ccee6766.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3536822/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by kd-11** [comment]
The artifacts here are very reminiscent of CPU rendering in TLoU; I'll try and isolate if they are indeed (very likely) what Cell spits out when using the edge library (I think).

**Comment by digitaldude555** [comment]
Update? @legend800

**Comment by legend800** [comment]
Only slight improvements maybe, but pretty similar to what it's looked like for awhile - ~5fps and glitchy boxes over screen. 

![2020-02-21 20_45_50-FPS_ 15 00 _ Vulkan _ 0 0 8-9665 _ Split_Second  NPUB30450](https://user-images.githubusercontent.com/20983844/75086686-ea1c6a80-54eb-11ea-9a9f-48a6ecf36892.png)

![2020-02-21 20_46_35-FPS_ 6 31 _ Vulkan _ 0 0 8-9665 _ Split_Second  NPUB30450](https://user-images.githubusercontent.com/20983844/75086689-ebe62e00-54eb-11ea-9e38-785c6e20f029.png)

![2020-02-21 20_47_21-FPS_ 6 92 _ Vulkan _ 0 0 8-9665 _ Split_Second  NPUB30450](https://user-images.githubusercontent.com/20983844/75086693-f0124b80-54eb-11ea-9333-18dd38119332.png)

**Comment by legend800** [comment]
No change as of today's master. Still 7fps with the boxey gfx issue. 

Needs some post processing patches maybe for now since the beta version looks and performs much better.

**Comment by legend800** [comment]
Perf issues are fixed as of 12/13/20. Gfx issues persist.

**Comment by benderscruffy** [comment]
RPCS3 v0.0.26-14743-6b30cdac Alpha | master
still an issue

**Comment by jedinjapan** [comment]
Just updating this issue since it's been dormant. Latest nightly builds still presenting with checkerboarding issues across various graphics including menus and in-game. Persistent across OpenGL and Vulkan renderers, regardless of resolution scale. Tried some other settings, but none with any noticeable effect. Happy to test any other alternatives.

**Comment by cas-1092** [comment]
Force CPU Blit fixes the checkerboarding but causes artifacts to appear on vehicles and breaks effects like explosions. 
It doesn't fix the skybox.
No explosion: (Background is supposed to have two explosions) ![image](https://github.com/RPCS3/rpcs3/assets/137835937/b496af0e-34c2-42d1-8858-9749badbb323)
Broken skybox: ![image](https://github.com/RPCS3/rpcs3/assets/137835937/d9f380e5-ef0a-48be-a2b2-0a7aa2563493)
Corrupted Livery: ![image](https://github.com/RPCS3/rpcs3/assets/137835937/3b66e4d8-3158-4853-863f-26ce41db3514)

**Comment by kd-11** [comment]
The correct fix for this is still not upstreamed. That will need a few more weeks at least (the underlying cause has been known for years)

**Comment by jedinjapan** [comment]
That's great. It's good to know it's been identified and zeroed in on at least, rather than remaining an open ended mystery.
For now the CPU Blit setting helps if one really must play right away. Hopeful to see how it looks in a few months.

**Comment by scorpion81** [comment]
> The correct fix for this is still not upstreamed. That will need a few more weeks at least (the underlying cause has been known for years)

Hmm does not upstreamed mean this fix is inside one of the pull requests or so ? (not being ready yet for the public / main branch ?)

**Comment by scorpion81** [comment]
Here I have my settings for split second and rpcs3 on my steam deck. which are different from the defaults.
RPCS3 v0.0.29-1-be0a789e
CPU -> Relaxed Xfloat, spu loop detection enabled, spu block size mega, preferred spu threads 6
GPU -> zcull accuracy relaxed, framelimit 30, shader quality auto
Audip -> convert to 16 bit (seems to reduce crackle)
Advanced -> Read depth buffers, 
                      write depth buffers. 
                      allow host gpu labels, 
                      vulkan queue scheduler safe,
                       rsx fifo accuracy fast
                       max number of spurs threads 4
Debug -> force cpu blit emulation enabled, accurate ppu 128 reservation disabled

Tested the tutorial missing, fps is between 15 and 25 fps, with steam deck tdp 7 watts and fixed gpu clock 1200 mhz, with a few watts more fps may increase slightly. But unlimited tdp aka higher cpu clock frequency only the fan noise gets very loud, with fps keeping the same.
Also note, the fixed gpu clock at about 1200 MHz mitigates some flicker of black squares near to the ground, or even the flickering of the whole screen. The only thing which is not fixed yet is the "ghosting" in the skybox as mentioned earlier.
But this is close to usable even with the steam deck already. :+1:

**Comment by AniLeo** [comment]
Use the forum thread for the game for game reports, this is for tracking the bug which is not solved yet

Also, do not do any reports with the flatpak as that's not an official build
