### ISSUE TITLE
Metal Gear Solid 4 BLES00246 PPU LLVM Out of memory

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#6401]
Tried many times with clearing and not clearing ppu cache issue always happens in the same place
Emulator throws a segfault and console says
F LLVM: Out of Memory (size=0xd8116, aligned 0x10)
Here's the video of error
https://youtu.be/FECeCC3xsYE
Tried to play this place through on interpreter, but it's impossible to even get close to this palce cause of freezes

**Comment by Nekotekina** [comment]
It's in my old TODO list.

**Comment by Xcedf** [comment]
Tried PSN version of this game NPUB31633, the place on the video is passable on it unlike BLES00246, game still may have crash on PPU LLVM first time compiling but it will compile after the second try. Will continue the playthrough to see if there's smth like in disc version.

**Comment by zombie167** [comment]
The efficiency of compiling the cache is now very good on the disc version.
Just one time and no errors with the pr build
https://github.com/RPCS3/rpcs3/pull/6771
https://github.com/rajkosto/rpcs3/releases

**Comment by rajkosto** [comment]
Both disc (1.0 or 2.0) and PSN versions of MGS4 would suffer from LLVM out-of-memory after playing a few levels, disc just gets affected sooner since it has one more overlay self it loads (the installer) before loading the level. #6771 fixes it in either case by having a new allocator for LLVM JIT output code.

**Comment by Xcedf** [comment]
@rajkosto Confirm https://github.com/RPCS3/rpcs3/pull/6771 fixes it, tested it on my original case BLES00246, and played through about 7 areas with PPU loading with no crash, previously it was 2-3, it seems original problem was not even in compiling modules but in loading them, crashes happen on master even if you loading already compiled modules. Anyway once again huge thanks for making MGS4 emulation better.

**Comment by Xcedf** [comment]
Since https://github.com/RPCS3/rpcs3/pull/6771 merged, close this one.
