### ISSUE TITLE
Windows Regression: Can't download compatibility database since #6322

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#6404]
After https://github.com/RPCS3/rpcs3/pull/6322 merged i always get the following error when trying to update RPCS3's compatibility database.
![image](https://user-images.githubusercontent.com/15137035/63644051-1020a800-c71f-11e9-9c2f-a382672b671a.png)
I made sure to check with the latest SSL dll's and its always the same error. Seems like it doesn't affect Linux users

**Comment by illusion98** [comment]
Same issue as of 0.0.6-8568-b70908c8 and Windows 10 1903

**Comment by Megamouse** [comment]
https://wiki.qt.io/Qt_5.13.0_Known_Issues
https://bugreports.qt.io/browse/QTBUG-76498

**Comment by Megamouse** [comment]
Qt5.13 needs openSSL 1.1.1 binaries

**Comment by ImPanda123** [comment]
> After #6322 merged i always get the following error when trying to update RPCS3's compatibility database.
> ![image](https://user-images.githubusercontent.com/15137035/63644051-1020a800-c71f-11e9-9c2f-a382672b671a.png)
> I made sure to check with the latest SSL dll's and its always the same error. Seems like it doesn't affect Linux users

it dose

**Comment by AniLeo** [comment]
No, it works on Linux, I tested it.

**Comment by ImPanda123** [comment]
doesn't work for me i'm using lubintu 19.04 idk maybe i have to updatae my system

**Comment by AniLeo** [comment]
Windows only issue due to the OpenSSL DLLs we package on AppVeyor builds being too old.

---

Ubuntu 18.04
```
libssl-dev/bionic-updates,bionic-security,now 1.1.1-1ubuntu2.1~18.04.4 amd64 [installed]
libssl1.0.0/bionic-updates,bionic-security,now 1.0.2n-1ubuntu5.3 amd64 [installed]
libssl1.1/bionic-updates,bionic-security,now 1.1.1-1ubuntu2.1~18.04.4 amd64 [installed]
```
`S Compatibility success: { Write database to file: /home/ani/.config/rpcs3/GuiConfigs/compat_database.dat }`

You probably don't have libssl 1.1.1.

**Comment by Zangetsu38** [comment]
i more understund my old issue with using already old 1.12.X
