### ISSUE TITLE
South Park: The Stick of Truth - Scene transition loading fails when invited by Cartman to come inside - RPCS3 v0.0.6-11b80b46 Alpha | fixup | Firmware version: 4.83

### ISSUE THREAD

**Issue by goedzo** [RPCS3/rpcs3#6409]
When you are invited by Cartman into his house in the beginning of the game, the game freezes on the loading of the new scene. It gets stuck on the scene loading animation, and the animation (icon right bottom) is not animating anymore and the game freezes.

Last 3 errors are:

```
E {PPU[0x100000a] Thread (Render Thread) [0x0019227c]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “dialogue.gfx” [3]
E {PPU[0x1000019] Thread [0x0019227c]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “ic_por_butters_lrg.tga” [1]
E {PPU[0x1000018] Thread [0x0019227c]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “ls_neighborhood.tga” [1]

```
Full log attached.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3538133/RPCS3.log)

**Comment by AniLeo** [comment]
Provided log file is not from the master branch

**Comment by digitaldude555** [comment]
No longer an issue.

**Comment by goedzo** [comment]
Yes confirmed to be working!
