### ISSUE TITLE
[Regression] UE3 Games PR6377

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#6413]
Some Unreal Engine 3 games show after https://github.com/RPCS3/rpcs3/pull/6377 this error
E {RSX [0x0002794]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x60300FE0
Games keep processing but show nothing and have 1fps
Games affected:
Lolipop ChainSaw
Bourne Demo
Silent Hill downpour
Shadow of damned
Army of Two The 40th Day

**Comment by illusion98** [comment]
Mirror's Edge and Life is Strange also runs extremely at 1 fps during intro videos
with `RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x50300FE0` for both games.
