### ISSUE TITLE
Build 8578 (PR6405) is freezing NCAA14 and then crashes RPCS3

### ISSUE THREAD

**Issue by huskereurocat** [RPCS3/rpcs3#6418]
The above mentioned build based on PR6405 is freezing NCAA14. I rolled back to the prior build 8576 based on PR 6414 and it works just fine. No crashes. 
Here is where the crash happens. 
![Desktop Screenshot 2019 08 26 - 23 21 27 85](https://user-images.githubusercontent.com/52609668/63741468-d48af880-c85a-11e9-9b41-a1ea27fcaa27.png)
And here is log that came from the crash. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3544290/RPCS3.log)

**Comment by isJuhn** [comment]
You should link to the issue by doing #6405 
I have noticed this same issue after the PR in Ratchet & Clank: ToD also. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3544324/RPCS3.log.gz)

**Comment by elad335** [comment]
Fixed by #6420.
