### ISSUE TITLE
Soul Calibur 5[BLUS30736] random crash

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#6422]
version:0.0.6-8576

win10 1803
8700k 16gram 1070ti

·W 0:02:52.163241 {PPU[0x1000001] Thread (mainThread) [0x01335b10]} sceNp: sceNpBasicGetEvent(event=*0xd0052298, from=*0xd005229c, data=*0xd0052374, size=*0xd0052574)
·W 0:02:52.164650 {PPU[0x1000001] Thread (mainThread) [0x00403304]} RSX: Cache miss at address 0x35300280. This is gonna hurt...

Now,this game change playable into ingame :(

**Comment by arcadee1977** [comment]
this is RPCS3.log:


[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3546117/RPCS3.zip)

**Comment by kd-11** [comment]
None of the messages there are of any concern to stability.

**Comment by arcadee1977** [comment]
This issue is fixed at newest version :)

**Comment by AniLeo** [comment]
Should have been closed earlier if already fixed
