### ISSUE TITLE
[Linux] Crash at 'Create PPU cache' -- RPCS3 v0.0.6-8599-dd79a5ef

### ISSUE THREAD

**Issue by Leopard1907** [RPCS3/rpcs3#6424]
When you hit ' Create PPU cache' on any game , emulator just crashes.

Terminal output of it:

`awk: /tmp/.mount_rpcs3-BJfAQs/usr/lib/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
terminate called after throwing an instance of 'std::runtime_error'
  what():  PPU Cache location not initialized.`

On build 8578-a921fe33 it doesn't crash right away but looks like it doesn't work.

Terminal output of that build:

`awk: /tmp/.mount_rpcs3-55WI2q/usr/lib/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)`

System info: Linux Mint 19.2 ( Ubuntu 18.04 based)
Cpu: i7 7700HQ
Driver: Nvidia 430.26 blob
Kernel: 5.0.0-20-mfutex

**Comment by Nekotekina** [comment]
Already fixed in #6421

**Comment by Leopard1907** [comment]
Nope , still same result at 8603-ec8c5453.

`awk: /tmp/.mount_rpcs3-xq9mBg/usr/lib/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unknown system error: 30.`

**Comment by Nekotekina** [comment]
It's different error, seems unrelated (EROFS).

**Comment by Leopard1907** [comment]
Outcome is the same. Crashes at creating ppu caches. Yes , error is different.

**Comment by MSuih** [comment]
30 is read only file system. If you have windows installed then make sure that fast boot hasn't gotten enabled. Windows updates can sometimes toggle it on silently.

**Comment by Leopard1907** [comment]
Linux only system. Not dual booting with any other distro or Windows.

**Comment by Leopard1907** [comment]
It doesn't crash with https://github.com/RPCS3/rpcs3/pull/6425 this though looks like it doesn't create PPU caches. Or lacks some GUI popup etc to inform about this or happens instantly so i can't notice it.

Because when i look into `~/.cache/rpcs3/cache` i can see many PPU related entries. 

Closing it since crash issue is fixed. Thanks.
