### ISSUE TITLE
Jurassic Park: The Game EPISODE 1: [NPUB30499] save Crash

### ISSUE THREAD

**Issue by Evil0Dead** [RPCS3/rpcs3#6428]
The game run smoothly but in some point in game just before autosave checkpoint it's freezing with error

`F {PPU[0x1000000] Thread (main_thread) [0x0036c6f0]} MEM: Access violation reading location 0x0`

this is rpcs3 freezing screenshot 

![2](https://user-images.githubusercontent.com/54598787/63803682-2779b400-c91e-11e9-8eec-7fafac041afe.png)

This is real consle right after the freezing screenshot above

![1](https://user-images.githubusercontent.com/54598787/63803751-4710dc80-c91e-11e9-865f-8fa71f2eed43.png)

rpcs3 log

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3547876/RPCS3.log)

**Comment by RainbowCookie32** [comment]
Still an issue. Also happens with PPU Fast.

![imagen](https://user-images.githubusercontent.com/16805474/82009369-81a1dd00-9645-11ea-97bc-c0da2eb699d9.png)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4632141/RPCS3.zip)

**Comment by digitaldude555** [comment]
No longer an issue can close. 
![Screenshot (69)](https://user-images.githubusercontent.com/26138653/95592935-de1cf300-0a51-11eb-81ac-34fa4ea37a7a.png)
