### ISSUE TITLE
Viking: Battle for Asgard graphics issues and missing fonts

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#6431]
Upon loading the game you will notice large white/grey squares vertically arranged on the left side of the screen:

![pic1](https://user-images.githubusercontent.com/12475371/63809808-ce585300-c912-11e9-8a11-f7643e563cbb.png)

Game loads but  does not display any fonts on the main menu (this issue has gone back at least a year):

![pic2](https://user-images.githubusercontent.com/12475371/63809850-e3cd7d00-c912-11e9-83f1-4f7291e67833.png)

Tested on Linux Mint 19.3 Cinnamon x64 with kernel 5.3, NVIDIA GTX 1070M 440.59

Logfile: [RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/3548245/RPCS3.log.zip)

**Comment by kd-11** [comment]
That commit specifically has nothing to do with booting games though.

**Comment by Shoegzer** [comment]
Thanks.  I just noticed the speed issue has been fixed with a more recent commit anyway so I'll strike that from the list above.  The graphics issues are still valid though, unfortunately.

**Comment by benderscruffy** [comment]
all the text goes down the page instead of across
![vikings](https://user-images.githubusercontent.com/2696404/74073219-763a8680-4a44-11ea-9e0c-fa8e1bf20727.PNG)
![vikings1](https://user-images.githubusercontent.com/2696404/74073221-789ce080-4a44-11ea-97a3-10cc0c57cdb3.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4173330/RPCS3.log.gz)
here are a few RSX captures
https://mega.nz/#!knQhUaLb!Fe1t7k2SPMB8v34gKMu0jgqb3INSkGRwGCqD6vLvt50

**Comment by Shoegzer** [comment]
Interesting, this seems like progress at least!  I'm still encountering the same issue as with my OP and I'm running 0.0.8-9522.  I noticed you're using 0.0.8-9528, so I'm guessing one of today's commits from @kd-11 led to the improvement.  

I've also updated test system specs from my OP.

**Comment by benderscruffy** [comment]
here is a Renderdoc
https://mega.nz/#!YiRUgSRR!0KbHWYMeZeWgonuyUC8qCBUmDmFb7cxKr2-UEFY2xMs

**Comment by Shoegzer** [comment]
I just updated to 0.0.8-9534 and can now see the vertical text as you've posted above.  I also updated my graphics driver to 440.59 and cleared all caches which I hadn't done for this game in a while, so I can't conclude 100% that updating rpcs3 fixed this.

Also important to note that Viking no longer goes ingame - it crashes right after the main menu.  I've updated the OP to indicate this.

**Comment by benderscruffy** [comment]
still goes in game for me on Windows
![vikings](https://user-images.githubusercontent.com/2696404/74094669-ff72bb80-4b1f-11ea-9a77-932ebfc9b77d.PNG)

**Comment by Shoegzer** [comment]
Not sure.  Sounds like the crashing issue might be linux-only.  Updating the OP for clarity.

**Comment by Yahfz** [comment]
@Shoegzer Can you retest with Strict Rendering + WCB + RDB + RCB + WDB?

**Comment by Shoegzer** [comment]
@Yahfz Thanks, you had my hopes up there but still seeing vertical text after those changes.

**Comment by Shoegzer** [comment]
Confirmed fixed with PR #10453 with no other issues performance or otherwise that I could tell.  Thanks @kd-11!

**Comment by Shoegzer** [comment]
Guessing you reopened because the PR hasn't been merged to master, and in that case it's fine just close afterwards.  Thanks.
