### ISSUE TITLE
[Regression] The Idolm@ster One For All [BLJS10260] crashes in stage mode after PR #6376

### ISSUE THREAD

**Issue by orz1515** [RPCS3/rpcs3#6433]
Testing on The Idolm@ster One For All [BLJS10260] and the game would crash with a fatal error after #6376. The game crashes when it tries to load into stage mode, crashing at this log line:

> F {RSX [0x011366c]} RSX: g_access_violation_handler(0xcd040800, 1): Verification failed: (in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\gltexturecache.h:383)

RPCS3 immediately crashes and shuts down after the fatal error.

Log file is attatched. RSX capture from working build PR #6383  is also attatched.

[BLJS10260_20190828075218_capture.zip](https://github.com/RPCS3/rpcs3/files/3548518/BLJS10260_20190828075218_capture.zip)

[logs.zip](https://github.com/RPCS3/rpcs3/files/3548505/rpcs3-v0.0.6-8445-033836d8_win64.zip)

Tested on Windows 10, i5-9400F, Nvidia GTX 1660 OC, OpenGL and all settings default.

**Comment by kd-11** [comment]
Need a video of how to reproduce this that I can follow step by step (I cannot understand anything in this game).

**Comment by orz1515** [comment]
> Need a video of how to reproduce this that I can follow step by step (I cannot understand anything in this game).

I'll do that. 
In the meantime here's a text-only guide:
when you're in the game's main menu, select the second icon from the left. It should ask you for a game save, just select one. When you're inside the character selection screen just press square and then yes (should be はい or something in Japanese.) the game would load into stage mode and crash in the build tested.

**Comment by orz1515** [comment]
> Need a video of how to reproduce this that I can follow step by step (I cannot understand anything in this game).

[https://youtu.be/ZUiA-6ZlSrA](url)
Here's the video. The gray screen in the end is the game crashing.

**Comment by orz1515** [comment]
The game seems to not crash when using Nvidia driver version 419.67. It seems like the game crashes only on newer versions of nvidia drivers (I initially tested with driver version 436.15).

**Comment by kd-11** [comment]
The OpenGL crash should be fixed by https://github.com/RPCS3/rpcs3/pull/6359.

**Comment by orz1515** [comment]
> The OpenGL crash should be fixed by #6359.

I downloaded that PR and the crashing persists. I suspect it has something to do with Nvidia's new drivers...

**Comment by kd-11** [comment]
Both issues should be fixed by https://github.com/RPCS3/rpcs3/pull/6493

**Comment by orz1515** [comment]
> Both issues should be fixed by #6493

The OpenGL issue is indeed fixed by #6493 . Vulkan still crashes for me though.
Closing this anyways since this is the OpenGL thread.
