### ISSUE TITLE
The Idolm@ster One For All [BLJS10260] crashes in Vulkan API

### ISSUE THREAD

**Issue by orz1515** [RPCS3/rpcs3#6434]
Testing on The Idolm@ster One For All [BLJS10260]. Game would crash immediately with a fatal error after endering stage mode, crashing at this log line:
> F {RSX [0x001366c]} RSX: g_access_violation_handler(0xcd040800, 1): Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST) (in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1051)

RPCS3 immediately crashes and shuts down after the fatal error.

Log file is attatched. Tested on PR #6299 but issue exists after this PR.
[log.zip](https://github.com/RPCS3/rpcs3/files/3548634/log.zip)

Decided to open new issue since it appears it might be a seperate issue.

**Comment by kd-11** [comment]
> Vulcans (sometimes Vulcanians) are a fictional extraterrestrial humanoid species in the Star Trek universe

**Comment by kd-11** [comment]
I'm trying to reproduce the crashing in this game, but I cannot understand anything in it. There exists another ticket in the same game; not sure if related.
It would help to provide a video to show step by step instructions on how to reproduce this for someone who cannot read japanese.

**Comment by orz1515** [comment]
> I'm trying to reproduce the crashing in this game, but I cannot understand anything in it. There exists another ticket in the same game; not sure if related.
> It would help to provide a video to show step by step instructions on how to reproduce this for someone who cannot read japanese.

Sorry for the typo. LOL
The steps to reproduce the crashing is the same as the other ticket (Video here: https://youtu.be/ZUiA-6ZlSrA), but I believe that they're seperate issues.

**Comment by orz1515** [comment]
The game doesn't crash when using Nvidia driver version 419.67. It seems like the game crashes only on newer versions of nvidia drivers (I initially tested with driver version 436.15).

**Comment by kd-11** [comment]
I tried to reproduce the crash with driver 430 on a pascal GPU and it ran just fine. Try enabling "Use High precision Z" debug option, maybe turing doesn't take too kindly to unsafe bitcasts like older NVIDIA cards. High precision Z forces NV cards to use the normal rendering path used by the other manufacturers.

**Comment by Emulator-Team-2** [comment]
@kd-11 

I have the same problem, but in different game with GTX 1660 (Driver: 436.15).

[Legend of the Guardians: The Owls of Ga'Hoole]

This game crashes in vulkan after the loading screen with:
```
F {RSX [0x005d774]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:1052)
```
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3587921/RPCS3.log.gz)

--------------------------------------------------------------------------------------------------------

Doesn't crash when the "Use High precision Z" option is enabled.

<details> 
<summary>Screenshot</summary>

![Bez tytułu](https://user-images.githubusercontent.com/38318848/64493032-398f1700-d27b-11e9-9142-1d9bff53b051.png)

</details>

Log with enabled "Use High precision Z" option:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3587924/RPCS3.log.gz)

--------------------------------------------------------------------------------------------------------

Another problem:
This game crashes with this error when Anti-Aliasing is enabled. 
```
F {RSX [0x0086840]} RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKRenderTargets.h:61)
```
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3587933/RPCS3.log.gz)
