### ISSUE TITLE
Option "Manually load selected libraries" does compiling them but NOT loading

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#6442]
If I'm choosing firmware option "Manually load selected libraries", the emulator compiles their PPU modules on the first launch, but does nothing with *loading* them into the PS3 OS. At the same time, options "Load automatic and manual selection", "Load liblv2.sprx and manual selection" and others related to manual selection, do exactly inverse thing: they load modules automatically on demand (by game), but does *not* compiling manually selected modules on the first time. I think the logic of every these option is broken.

**Comment by Nekotekina** [comment]
It's legacy option and shouldn't be used. Compiling firmware modules should also happen after firmware installation.

**Comment by Psycho-A** [comment]
Although it's legacy, it worked different when it was useful: it had normally loaded libraries into the OS and then compiled them only. In that form like it exists now it's buggy and absolutely useless.

About firmware: 
1) I may just remove the whole /cache folder if lots of game's garbage collected inside, and then all compiled FW modules will be erased, and new games will need to compile them on demand (which is inacceptable in many cases).
2) I may update emulator builds, but have the same firmware as before because it just works well. Some major updates requires cleaning of obsolete PPU modules, so again, we have firmware with no compiled modules and need to reinstall the SAME firmware again.

I'd just suggested to fully remove manual loading libraries, but add "compile selected modules on game load" or even "compile whole firmware modules on game load". It's very useful for listed cases and not resource capable for second launches when modules are already compiled.

**Comment by Nekotekina** [comment]
Running rpcs3 with full path to /dev_flash/sys/external/ location in first command line parameter recompiles all sprx libraries, just like firmware installation does. Someone may add dedicated menu option for this.

**Comment by elad335** [comment]
I didnt understand where the problem lies here, it loads the modules fine at startup.
I tested it recently with libsre.sprx and its working just fine.
Also so what if we compile PPU modules if they requested by game with the other settings and we dont have their cache? normally when installing firmware it already compiles them so if you encounter in-game compilation of firmware it means you removed firmware cache manually which is not an ideal situation.

**Comment by elad335** [comment]
actually theres a valid bug here of not returning PRX ID in sys_prx_load_module in such case (LIBRARY_FOUND error is returned), reopening.
It wont affect all games but its definitely a bug.

**Comment by elad335** [comment]
well manual list loading mode is nearly perfect except from minor issie which is resolved with an open pr.

**Comment by elad335** [comment]
oh, of course LLVM wont compile them, because in manual list mode module list is the only thing being loaded.
unlike the other modes which have a secret LLE list.
