### ISSUE TITLE
RPCS3 0.0.6.8612 Alice Madness Returns FPS Counter 0,98 Menu

### ISSUE THREAD

**Issue by Joaozin-tech** [RPCS3/rpcs3#6445]
![SharedScreenshot98](https://user-images.githubusercontent.com/53271430/63944944-ecc06a80-ca48-11e9-9668-96a936b4587b.jpg)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3555774/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3555775/RPCS3.log.gz)

**Comment by AniLeo** [comment]
What's the specific issue here? Low performance does not warrant opening an issue as it's merely a symptom of possibly several issues

**Comment by Joaozin-tech** [comment]
likely to be ppu and spu

**Comment by CrabLugo** [comment]
So it's a regression report? Then find a build where it regressed

**Comment by Joaozin-tech** [comment]
we can say that GAME suffered serious regressions update RPCS3 waiting to fix i love this game too much Xd

**Comment by Evil0Dead** [comment]
there's another regression with this game .. i think one PR for this month or 2 months ago .. game used to load after you speak with old lady .. now it's back to infinit loading ..


@Joaozin-tech  can you test which PR was passing infinit loading ? i have no time but im sure it's 1 or 2 months old

**Comment by Joaozin-tech** [comment]
@Evil0Dead https://github.com/RPCS3/rpcs3/pull/4846
https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-e2ee959ac8b90920f4c8568f1aa3a1af2f36c0fd/rpcs3-v0.0.5-7023-e2ee959a_win64.7z

**Comment by Joaozin-tech** [comment]
E {RSX [0x0133e24]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x60300F80
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3587044/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3587045/RPCS3.log)

**Comment by Joaozin-tech** [comment]
Fixed pr master #7173 fps 30fps GREAT rpcs3  however game still breaks next error

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4017286/RPCS3.log.gz)
E {RSX [0x02d3b4c]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x60300F8
![SharedScreenshot66](https://user-images.githubusercontent.com/53271430/71692191-028fc480-2d88-11ea-88e0-ec68305cc525.jpg)
![SharedScreenshot67](https://user-images.githubusercontent.com/53271430/71692192-028fc480-2d88-11ea-8fef-b26af3f6dbd9.jpg)
![SharedScreenshot68](https://user-images.githubusercontent.com/53271430/71692193-03285b00-2d88-11ea-8c4c-9077da4607d2.jpg)

**Comment by AniLeo** [comment]
Next error is unrelated, the original issue / regression is fixed so it can be closed.

**Comment by Joaozin-tech** [comment]
Thanks rpcs3 thean fixe latest rpcs3 master build thanks!!!!!!!!

**Comment by AniLeo** [comment]
If you keep flooding our tracker with garbage you'll be blocked, this is not a chat platform
