### ISSUE TITLE
Audio regression and freeze (gof of war 3,god of war ascension,red dead redemption)

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#6449]
I don't know if coz of new nvidia graphic/realtek driver or coz of new code of LLVM but now I have sound repetitions in god of war 3,god of war ascension.Those games also freeze after some time during game and Red Dead Redemption freeze avec the Rockstar logo (like probably others)

**Comment by kd-11** [comment]
Probably something local to your system; I checked RDR a few hours ago and its fine. Using HDMI audio though.

**Comment by legend800** [comment]
Please fill out the bug submission form and not just delete it. And don't submit various issues in multiple games in the same issue, with a vague description and no logs/broken build notes or anything that's actually actionable. 

Close this and resubmit a proper defect once you've confirmed this is not your actually system config.
