### ISSUE TITLE
God Of War 3 sound pb and freeze

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#6452]
God of War 3 have now sound flickering and freezes.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3562323/RPCS3.log)
Red Dead Redemption freezes after Rockastar logo's video
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3562325/RPCS3.log)

I7 9700k
GTX 1080
16gb RAM
Windows 10 1903

**Comment by Yahfz** [comment]
God of war 3 is fine on master. Unless you can give us more info about the regression the issue can be closed.

**Comment by Pouncha** [comment]
Yes.Apparently it works now.
Issue closes but red Dead Redemption still on the way...
