### ISSUE TITLE
about the new version rpcs3 of dpi 

### ISSUE THREAD

**Issue by anseesaw** [RPCS3/rpcs3#6453]
system：Win10 1903（18362.329）
Display resolution：5120 x 2160
Scale and layout：200%

old:
![TIM图片20190831183633](https://user-images.githubusercontent.com/28805459/64062816-4e85fd80-cc1e-11e9-82e4-5173c8599ce4.jpg)

new:
![TIM图片20190831183637](https://user-images.githubusercontent.com/28805459/64062817-5180ee00-cc1e-11e9-87cb-d58df6c0551d.jpg)

**Comment by JohnHolmesII** [comment]
Was there a question you had? If you want you can adjust the size of the images in the UI.

**Comment by Megamouse** [comment]
try again please

**Comment by Megamouse** [comment]
Gonna close this due to inactivity and because I think I fixed the problem anyway.
