### ISSUE TITLE
[BLES01035]Call of Duty Black Ops crash - Assertion failed: !region.is_locked()

### ISSUE THREAD

**Issue by QuaiGoner** [RPCS3/rpcs3#6456]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3562425/RPCS3.log.gz)
Crashes when attempting to buy a gun in zombie mode.

**Comment by kd-11** [comment]
One of the rarest bugs in rpcs3. I'm assuming this makes it easy to reproduce?

**Comment by QuaiGoner** [comment]
Yes, very easy. Launch the game,go to zombie mode, first map, buy a gun
from wall - it will immediately crash

сб, 31 авг. 2019 г., 19:08 kd-11 <notifications@github.com>:

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/6512
