### ISSUE TITLE
[BLES00148] Call of Duty games - Unknown blend eq 0x0

### ISSUE THREAD

**Issue by QuaiGoner** [RPCS3/rpcs3#6459]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3562585/RPCS3.log.gz)
Crash right before getting ingame and compiling couple shaders
If its a duplicate - will close but i saw an issue with blend eq 0x7 only
Also happens in: 
CoD 5 World at War - for ex. when staring new game
CoD Black Ops - for ex. when starting Zombie map "Ascension" (DLC map)
Every game has blend eq 0x0

**Comment by QuaiGoner** [comment]
Same with CoD WaW
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3562633/RPCS3.log.gz)

**Comment by elad335** [comment]
Fixed by #7780
