### ISSUE TITLE
[BLES00691] Call of Duty Modern Warfare 2 - broken transparency/size of some effects

### ISSUE THREAD

**Issue by QuaiGoner** [RPCS3/rpcs3#6460]
![screenshot-2019_08_31_22_58_42](https://user-images.githubusercontent.com/41058180/64066410-658b1680-cc43-11e9-8539-9e189a42dff1.png)

![screenshot-2019_08_31_22_58_37](https://user-images.githubusercontent.com/41058180/64066412-68860700-cc43-11e9-97b2-c92c155a47d5.png)

![screenshot-2019_08_31_22_58_23](https://user-images.githubusercontent.com/41058180/64066413-6c198e00-cc43-11e9-8d07-4ea570965051.png)

RSX Capture:
https://mega.nz/#!nmZATITI!WkaO6tF1qzIR4F09-H7qw2VVinOiskDOvDgv--OShn0

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3562627/RPCS3.log.gz)

R2400G + GTX1050 latest drivers, latest master.
Vulkan + LLVM PPU/SPU + WCB

**Comment by Megamouse** [comment]
see old_logs folder in the future

**Comment by wheelmac92** [comment]
This happens in MW3 as well
