### ISSUE TITLE
[BLES01720] Call of Duty Black Ops 2 MP\SP - does not boot .elf file of multiplayer\broken font

### ISSUE THREAD

**Issue by QuaiGoner** [RPCS3/rpcs3#6461]
Log is over 2GB because of spamming of this error while launching multiplayer (either manual of from ingame):
![Снимок](https://user-images.githubusercontent.com/41058180/64066574-c582bc80-cc45-11e9-8438-06eb142e229e.PNG)
Broken font in game:
![screenshot-2019_08_31_23_15_14](https://user-images.githubusercontent.com/41058180/64066578-d2071500-cc45-11e9-978b-39827f582ff0.png)

RSX Capture impossible (fatal error when attempting to do RSX Capture):
![image](https://user-images.githubusercontent.com/41058180/64066623-68d3d180-cc46-11e9-9958-8d92caf15064.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3562621/RPCS3.log.gz)

**Comment by Yahfz** [comment]
@QuaiGoner still an issue?

**Comment by Darkhost1999** [comment]
Broken font sure is it's frequently discussed on discord. Can we get updated logs, screenshot and rsx captures?

**Comment by Megamouse** [comment]
the multiplayer and zombie games seem to load fine for me:
![image](https://user-images.githubusercontent.com/23019877/170814187-483f3646-1738-4311-be1c-1391dae1fa98.png)

Closing as superseded by #8718
