### ISSUE TITLE
[BLES00246] Metal Gear Solid 4: Guns of The Patriots - Alpha Textures Corrupted

### ISSUE THREAD

**Issue by HHCHunter** [RPCS3/rpcs3#6463]
With PR #6450 

MGS4
Alpha Textures have an issue with decoding correctly when faced at certain LOD / MIP Level.

![image](https://user-images.githubusercontent.com/18048891/64067357-eead4800-cc59-11e9-9e5a-d9d1a7daf02d.png)

![image](https://user-images.githubusercontent.com/18048891/64067363-fcfb6400-cc59-11e9-93b6-8f43cbb83fe1.png)

![image](https://user-images.githubusercontent.com/18048891/64067366-097fbc80-cc5a-11e9-97b6-eaaca84c3d82.png)

RSX capture:
https://1drv.ms/u/s!AgLgPtiiLQdWjm8BZx61Ay1z9sxT?e=MzJJ08

**Comment by rajkosto** [comment]
Making a RSX capture and playing it back with same settings except OpenGL/Vulkan:
https://images.sshnuke.net/2019-10-12_08-06-07_QPLfQhZFL.png
https://images.sshnuke.net/2019-10-12_08-06-38_q1d7hcLca.png

So this issue doesn't happen in OpenGL. And it's not a texture corruption problem during upload, only a rendering mistake.

**Comment by rajkosto** [comment]
https://github.com/RPCS3/rpcs3/commit/5af8a9fbbcba6e683a8a0a89ff733e548215a3e7 changed some calculations that make it not show up on the previously attached RSX capture, but it still shows up ingame and on a newly made RSX capture (and the mips are still corrupted/wrong): https://files.sshnuke.net/NPUB31633_20191017175448_capture.7z

**Comment by kd-11** [comment]
Thanks.

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/67050530-65869d80-f141-11e9-837e-1b67727f339a.png)
I think its fixed by https://github.com/RPCS3/rpcs3/pull/6790

**Comment by rajkosto** [comment]
The issue was not affected by #6790 both the previously attached RSX capture: https://images.sshnuke.net/2019-10-18_07-36-09_OCudg5NSX.png
 or ingame still look the same: https://images.sshnuke.net/2019-10-18_07-34-47_dq2p8qX6W.png

**Comment by rajkosto** [comment]
Actually fixed now with https://github.com/RPCS3/rpcs3/pull/6790/commits/dc82fe532af115367fd3278356ffe31c4f4ec6b0 which is part of #6790
