### ISSUE TITLE
--no-gui mode needs error MsgBox on panic (pink) log events

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#6469]
Since we're disabling GUI and log window by this command line, we're not able to know if something critical is happen. As a result, the emulator stands to hang in the OS processes and needs manual killing. That's incorrect for usability.

**Comment by Megamouse** [comment]
Well. You can't just open a box Everytime the thing stalls or has a fatal error.
Fatal errors don't necessarily mean that the program crashed.
It would need to be some generic message which btw should appear already anyway.

**Comment by Megamouse** [comment]
And the process should kill itself anyway. So it's probably a bug in general that is more obvious in this case

**Comment by Psycho-A** [comment]
`And the process should kill itself anyway. So it's probably a bug in general that is more obvious in this case`

Yes, in my case process doesn't kill itself on pink event, that meant it will stay active forever. Anyway, the message with log text and suggestion to close emulator would more user-friendly that silent closing program without any infos.

**Comment by Blaypeg** [comment]
If there is no gui then a msgbox is bad, that would hinder automated testing. It would be better to write to log and kill itself

**Comment by bevanweiss** [comment]
So we already write these events to the log.
Perhaps we should be streaming things that are 'Error' or above to stderr?
That means that they could be captured by an automated testing.  They would also show up as a console message if run via CLI.

**Comment by Megamouse** [comment]
We implemented report_fatal_error.
This should pop up for the most horrific errors.
It also logs to stderr.

I'll close this issue.
