### ISSUE TITLE
Shank 2: crash on load [Possibly Linux Only]

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#6473]
On Linux systems, Shank 2 crashes RPCS3 entirely during initial game load with the following exception thrown:

![52159074-56d18680-2697-11e9-9f94-c0ba08f984e2](https://user-images.githubusercontent.com/12475371/64128882-68534c00-cda8-11e9-885f-ca635929d94a.png)

Note: this game now seems to load on Windows systems at least from [this](https://github.com/RPCS3/rpcs3/issues/5626) closed issue report and [this](https://forums.rpcs3.net/thread-199551.html) compability thread.

Tested against 0.0.7-8620, though this has occurred since testing began over a year and a half ago. Test system is Linux Mint 19.2 with kernel 4.18, Nvidia GTX 1070M and driver 430.40.

Logfile: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3566798/RPCS3.log.gz)

**Comment by sambow23** [comment]
Getting the same issue with Skate 3

**Comment by Shoegzer** [comment]
This issue seems to be fixed as of 8234bdb8f000e1dc2c11523ba596007dabe3f78a, and was not working with 81c61e230f3f96f4427d87833b033c949af3aac5 so clearly a very recent commit fixed it (guessing memory allocation / heap fixes - thanks @kd-11).   Closing.
