### ISSUE TITLE
RPCS3 fails to compile

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#6474]
RPCS3 fails to compile buid 08c12f4c0094046528c0731edafb69e063b752ad (0.0.7-8620 compiles just fine).  Getting the following in term (as the first of many more errors similar to this):
```
In file included from /home/shoegzer/Desktop/rpcs3/rpcs3/Utilities/File.cpp:1:
/home/shoegzer/Desktop/rpcs3/rpcs3/Utilities/File.h:20:13: error: multiple definition of ‘enum class fs::open_mode’
   20 |  enum class open_mode : u32
```
Test system is Linux Mint 19.2 with kernel 4.18, Nvidia GTX 1070M and driver 430.40.

**Comment by JohnHolmesII** [comment]
Which compiler are you using?

**Comment by Shoegzer** [comment]
gcc (Ubuntu 9.1.0-2ubuntu2~18.04) 9.1.0

**Comment by Shoegzer** [comment]
Commit 6bdab5322c7590d58fb6ca4ee79610fc8ad55447 fixes this and RPCS3 compiles once again, so closing the issue.  Thanks @RipleyTom for the fix.

**Comment by RipleyTom** [comment]
After further investigation the issue is a gcc bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56549

Leaving info here in case someone encounters the same problem.
You're welcome visitor from the future!
