### ISSUE TITLE
Borderlands often hangs on loading or saving games

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#6475]
Borderlands (NPUB30413 or BLUS30386) often hangs on loading or saving games.  This seems to be sporadic because sometimes it does work - for example I'll try loading a game three times and on the third attempt it will work.  Sometimes this can occur when loading from the main menu, sometimes when exiting and saving from a game in progress, etc.

I've noticed that this seems to be linked to a problem with textures - randomly ingame, the textures are rendered blurry / out of focus and a restart is needed to get them to render properly again.  Every time this happens though, the game hangs when saving a game (and autosave points don't even work).  Here's an example of the texture problem as seen with the two vending machines in front of the player:

![pic](https://user-images.githubusercontent.com/12475371/101999752-2d7bdb80-3cae-11eb-9520-2afddf8ef2ad.png)

I tried clearing all caches, deleting save game and trophy data, deleting configuration data, finally deleting the ~/.config/rpcs3 directory and starting from scratch, and even reinstalling the game at one point but nothing seemed to work.  I've also tried just about every setting in RPCS3 to fix the problem to no avail.

This may be a Linux-only issue because I'm aware of others with Windows that have had no issues loading or saving with this game.

Note also: I filed several other reports for the same issue months ago such as [this one](https://github.com/RPCS3/rpcs3/issues/5332) - it seemed as if the issue was resolved, but while testing again recently I encountered it again (so it could be a regression?).

**Update:** More recent settings as of 2020/12/12:

* OS: Linux Mint 20, kernel 5.8
* CPU: i7-7820HK CPU
* GPU: Nvidia GTX 1070M, Nvidia driver 455.38
* Compiler: gcc-10.2.0
* Commit ee814cfd0c8446a93195db139f25ab5335cd6980

Updated log file is here: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5683975/RPCS3.log.gz)

**Comment by kd-11** [comment]
Confirmed the issue on linux.

**Comment by digitaldude555** [comment]
Still issue?

**Comment by Shoegzer** [comment]
Yes, unfortunately.  Just tested this issue yesterday against 0.0.8-9652.

**Comment by Shoegzer** [comment]
This issue seems to have been resolved: tested loading a save game and then quitting back to main menu 10 times with no hanging.

Issue seems to have been resolved somewhere between commit cab4c78b7bee01840c48df942171f1c367832710 and  e0635cf65c0510bba967442107434163235c7dae though I haven't performed a bisect.  Note that the test system was upgraded from kernel 5.4 > 5.8 between these commits but I don't believe that played a role here.

Closing this issue but @kd-11 please feel free to reopen if you continue to observe as you reported.

**Comment by kd-11** [comment]
I agree to close as I cannot reproduce either. Not really a fair test since my old saves are incompatible with current rpcs3 anyway but its not happening anymore.

**Comment by Shoegzer** [comment]
Reopening this as the issue is back as of commit d1e783742293bf9516f50863dedca175a6b98b4b unfortunately, not sure why.  It doesn't seem to be happening as often at least.

**Comment by Shoegzer** [comment]
I've updated this issue with new details including a rendering issue that seems to be linked to the game hanging upon saving a game.  I've also attached a more recent logfile.

@kd-11 If you get a spare cycle to look further into this, could you see if there's anything wrong in my logfile or different from yours?  I'm now encountering this issue with equal frequency to when I had originally posted the issue and I'm curious how it's now working for you.  Also, maybe the rendering issue provides some clue as to what's happening?

**Comment by kd-11** [comment]
I only checked with a clean/new save, I haven't done any sort of thorough testing. In the past I could never go ingame unless I deleted a previous save. If I find some spare time I can try and start a new game and see if I can reload it without crashing on current master.

**Comment by Shoegzer** [comment]
Thanks for looking into tihs @kd-11.  My recent tests are also with a clean/new save.  If it helps, it might take multiple attempts to encounter the issue, and I''ve found it's most often on the inital game load to a save from a cold boot.  If there's anything I can supply to help (like my own game save or an RSX capture for the texture issue?) please let me know and I'm happy to help.  Would be great for this major title to be playable.

**Comment by Shoegzer** [comment]
Update: I've noticed that setting Accurate PPU 128 Reservations to "Always Enabled" *seems* to make the issue less frequent, though it still occurs.  I was playing the game for several hours without any issue, but then as soon as I got back into Fyrestone (the main "hub" area where you begin the game), the issue still occurs sometimes.  Again I'll know when it will freeze the next time I save the game because the textures will look corrupt as I posted above.

**Comment by dyno0** [comment]
The problem is still present but following the PRs #10566 and #10574 log and tty returns an actual error instead of a no message deadlock.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6837019/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/6837020/TTY.log)

**Comment by Megamouse** [comment]
Test again

**Comment by Shoegzer** [comment]
I no longer have this title for testing but hopefully someone else can help - @dyno0 can you test again?

**Comment by MrGrosNounours** [comment]
The game seems to be working now.
