### ISSUE TITLE
Freeze at [BLES01102] (Ar tonelico 3): "Verification failed at C:\projects\rpcs3\rpcs3\Emu\RSX\GL\GLTextureCache.h:383"

### ISSUE THREAD

**Issue by Metafalica** [RPCS3/rpcs3#6481]
i5 880 (4 cores/8 threads 3.3GHz), Radeon HD 5750, Windows 10, RPCS3 v0.0.7-8641-6bdab532.
Emu specific configuration is in log attached.

Game randomly freezes. Try to play to reproduce. Yesterday it froze after second battle from game start and today before it. It is unknown to me if it ever worked.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3573041/RPCS3.log)

Last message in log:
F {RSX [0x005b988]} RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\GL\GLTextureCache.h:383)

**Comment by kd-11** [comment]
Technically this issue was fixed a while back but the PR has yet to be merged/finalized. See https://github.com/RPCS3/rpcs3/pull/6359.
