### ISSUE TITLE
Vulkan causing AMD driver crashing and BSOD in certain areas in Demon's Souls.

### ISSUE THREAD

**Issue by alexhunt7** [RPCS3/rpcs3#6487]
Running Demon's Souls in Vulkan on Vega hardware crashes the driver (black screen of death, but the driver restarts after several seconds, but RPCS3 is not recoverable) at various points in the game, the first of which is in the tunnel during the tutorial (between the 2nd and 3rd enemy in the game).

I've tried several other settings, and Vulkan is the only one I've found that seems to make a difference. Using OpenGL doesn't have this behavior, but the performance is unplayably slow.

Tested with:
rpcs3-v0.0.7-8640-08c12f4c_win64
rpcs3-v0.0.7-8643-8de12391_win64

RX Vega 56
AMD Ryzen 3600
32GB Ram
Windows 10 1903
Radeon driver version 19.10.16

Log from RPCS3 8643:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3581841/RPCS3.zip)

This seems similar to https://github.com/RPCS3/rpcs3/issues/3482 .

I understand that a driver crash is probably not RPCS3's fault, but maybe you can work around it or provide more detail to the AMD team. I did report it to them as well, but they don't seem to have a public forum for their bug reports.

**Comment by kd-11** [comment]
Install the vulkan SDK and run the game with debug output enabled. If there is no error shown before the crash. Honestly I'd start with downclocking everything just to see if it improves stability. I tried to reproduce with your scenario in tutorial and got nothing; no crash and no logged validation errors. This makes it nigh impossible to create any meaningful bug report with the manufacturer.

**Comment by alexhunt7** [comment]
Nothing is/was overclocked.

Logs with vulkan SDK and debug output enabled:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3586121/RPCS3.log)

**Comment by Reeeven** [comment]
I have the same problem when using vulkan, my game crashes also when entering the tunnel early in the tutorial. 

RX Vega 56
AMD Ryzen 1600
16GB Ram
Windows 10 1903
Radeon driver version 19.10.15.05
RPCS3 Version: 0.0.7-8741-e0005ec3 Alpha
[error.txt](https://github.com/RPCS3/rpcs3/files/3640123/error.txt)

**Comment by alexhunt7** [comment]
Solved! It seems that it's a problem with the 19.10.x drivers. Running with 19.9.2 seems to solve it. @Reeeven Please try again with the latest stable drivers.

**Comment by Reeeven** [comment]
Thank you it fixed the problem!
