### ISSUE TITLE
Battle Los Angeles[NPUB30470] has problems with graphics

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#6489]
It seems that this game has problems with ordering light/sprite effects to the camera or/and with brightness or/and with alphakill on Vulkan.

PS3, Menu
![battle los angeles ps3 correct](https://user-images.githubusercontent.com/22906342/64461293-79cc8900-d105-11e9-8361-a1eedb64dac1.png)

RPCS3 v0.0.7-8650-efa501da Alpha, Menu
![screenshot-2019_09_07_00_12_27](https://user-images.githubusercontent.com/22906342/64461291-79cc8900-d105-11e9-868a-269713316531.png)

In the game
![screenshot-2019_09_07_00_15_06](https://user-images.githubusercontent.com/22906342/64461292-79cc8900-d105-11e9-99bf-b6cd61b14c33.png)

[RSX Capture](https://drive.google.com/open?id=1PUdxdPxSHi0-SjzFoqcqFo9vR_SSF_9k)

Since #6376 when I use OpenGL, emulator throws this error
`F {RSX [0x0093348]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\gltexturecache.h:383)`
[RPCS3 OpenGL Crash.log.zip](https://github.com/RPCS3/rpcs3/files/3585749/RPCS3.OpenGL.Crash.log.zip)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3585751/RPCS3.log.gz)

**Comment by Realmantik** [comment]
With this #6359 no more error. Rendering with OpenGL and Vulkan look identical but visuals still broken.

**Comment by AniLeo** [comment]
Is this still an issue?

**Comment by benderscruffy** [comment]
yep
![battle](https://user-images.githubusercontent.com/2696404/72197304-bbc25e80-345a-11ea-9ca3-f237606ce565.PNG)

**Comment by kd-11** [comment]
Test with RDB/RCB

**Comment by digitaldude555** [comment]
The game stopped working.

**Comment by benderscruffy** [comment]
no differance with RDB/RCB

**Comment by digitaldude555** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/26138653/92923351-02c87f80-f440-11ea-9edb-b61d4244b0bc.png)
Close it.

**Comment by AniLeo** [comment]
Closing as fixed

**Comment by TylerJaacks** [comment]
Ok I am having this issue.
![Untitled](https://user-images.githubusercontent.com/1505374/172067024-28502cc2-6eb7-44bd-9c2c-2ec913182711.png)

**Comment by TylerJaacks** [comment]
I was wondering if we can reopen this issue.

**Comment by Megamouse** [comment]
Open a new issue
