### ISSUE TITLE
Regression: Iron Man freezes after intro videos (#6421,  #6423)

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#6490]
After #6421, #6423 were merged the game freezes after intro videos on loading screen.
[RPCS3 v0.0.6-8604-b6b7d7b4.log.zip](https://github.com/RPCS3/rpcs3/files/3586163/RPCS3.v0.0.6-8604-b6b7d7b4.log.zip)

**Comment by StuDentBRz** [comment]
Iron man BLES00247 does not go in game anymore since (BAD) rpcs3-v0.0.6-8603-ec8c5453
The last build which it goes in game is (GOOD) rpcs3-v0.0.6-8599-dd79a5ef.

**Comment by StuDentBRz** [comment]
[(BAD) RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3639856/BAD.RPCS3.log.gz)
[(GOOD) RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3639857/GOOD.RPCS3.log.gz)

**Comment by Emulator-Team-2** [comment]
@AniLeo 
This issue was fixed some time ago.
