### ISSUE TITLE
[Linux] Skate 3 [BLES00760] Segfault

### ISSUE THREAD

**Issue by sambow23** [RPCS3/rpcs3#6491]
Upon Launching Skate 3, after pressing start on the menu, it proceeds to load then show this segfault message: 
![image](https://user-images.githubusercontent.com/14916663/64469688-302b7080-d0fc-11e9-84cf-bcf7e57110c2.png)

RPCS3 Version: v0.0.7-8650-efa501da
OS: Arch Linux
Kernel: linux52/linux53
GPU: NVIDIA GTX 1060 6GB
CPU: AMD Ryzen 7 2700X 4.3GHz
Driver: 435.19.03 (latest vulkan dev driver)

RPCS3 log:
[RPCS3.log.tar.gz](https://github.com/RPCS3/rpcs3/files/3586236/RPCS3.log.tar.gz)

**Comment by kd-11** [comment]
Need a GDB stacktrace.

**Comment by sambow23** [comment]
ran `gdb ./rpcs3-v0.0.7-8650-efa501da_linux64.AppImage` but it doesnt seem to work because there is no debugging symbols
`Reading symbols from ./rpcs3-v0.0.7-8650-efa501da_linux64.AppImage...
(No debugging symbols found in ./rpcs3-v0.0.7-8650-efa501da_linux64.AppImage)`

**Comment by kd-11** [comment]
Yea, you need to extract the appimage since its just a big 'zip'file. The real executable is inside but that may be too complicated.

**Comment by AniLeo** [comment]
Cannot reproduce on current Manjaro linux53 with radv on R9 280X, may be an NVIDIA thing or any misconfiguration in your system. 

Try retesting on current build nevertheless.

**Comment by sambow23** [comment]
Sorry to reply so late! figured it out, I guess some PR from a few months ago changed how saves work. Creating a new User in RPCS3 fixed it, sorry for the trouble
