### ISSUE TITLE
[BCUS98246] [Vulkan] The Sly Collection swaps between rendering blue as orange and orange as blue

### ISSUE THREAD

**Issue by PaulBGD** [RPCS3/rpcs3#6496]
RPCS3 Version: 0.0.7-8654-10c81fbd Alpha
Hardware: 8700k, GTX 980ti, Windows 10 Version	10.0.17763 Build 17763

To reproduce: run The Sly Collection (BCUS98246) with the Vulkan render and run the first game. Throughout the entire game (including its cutscenes) it will switch between rendering blue as orange and orange as blue. It doesn't seem like all colors in the game are affected. This issue goes away with OpenGL.

I changed a lot of settings including changing settings "Write Color Buffers", "Strict Rendering Mode", and "Force CPU blit emulation" in a few different ways, but only switching to OpenGL fixes the issue.

Example of issue: https://www.youtube.com/watch?v=UPF7JkgBix0

In screenshots:
![vlcsnap-2019-09-07-15h56m55s654](https://user-images.githubusercontent.com/3516420/64480153-1df71400-d188-11e9-9030-efadd6d87dfe.png)

![vlcsnap-2019-09-07-15h57m01s475](https://user-images.githubusercontent.com/3516420/64480155-1f284100-d188-11e9-8833-e11bce633d71.png)

**Comment by MarioSonic2987** [comment]
Have you tried to disable Anti-Aliasing? You can find that option in GPU tab, in Settings. Also, it's already reported in #6103.

**Comment by PaulBGD** [comment]
Anti-aliasing does fix the orange swapping.

I just took a look at that issue, I somehow didn't find that with my previous searches. I'll add a comment there so it comes up in the future.
