### ISSUE TITLE
RPCS3 v0.0.7-8662-0af96853 WET F {PPU[0x1000017] Thread (A2M Render Task Thread) [0x00a568d0]} MEM: Access violation writing location 0xc

### ISSUE THREAD

**Issue by Joaozin-tech** [RPCS3/rpcs3#6501]
![SharedScreenshot9](https://user-images.githubusercontent.com/53271430/64489704-8dbeda80-d22c-11e9-817b-9dd8d093420b.jpg)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3587681/RPCS3.log)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3587682/RPCS3.zip)

**Comment by AniLeo** [comment]
Access violations are a symptom of something else, just having an access violation by itself isn't very useful

**Comment by Joaozin-tech** [comment]
@AniLeo asked to close or leave open

**Comment by M9k** [comment]
I detected a strange behavior with this game.
If, after the memory access violation, I close the game window or press stop, the whole emulator closes.
It doesn't happen with other games.

**Comment by ruthan** [comment]
I still have this error, for me its 
F {PPU[0x1000000] Thread (main_thread) [0x00a568d0]} MEM: Access violation writing location 0x8
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4109756/RPCS3.zip)

**Comment by Megamouse** [comment]
This hasn't bee updated for over a year.
Is this still happening?

**Comment by ruthan** [comment]
Well, im not 100% sure, you can check my compatibility post log.. i played it for while, but after 20 minutes, but after that i got some crash.
https://forums.rpcs3.net/thread-181110-page-2.html

**Comment by Megamouse** [comment]
If this is just some random crash then I don't think this issue is really helpful.
There are plenty of other games that crash from time to time.
I'll close this until someone can find a reasonable and reproducable error.

**Comment by M9k** [comment]
> I tried the demo today and it crashes at the loading screen before going ingame. [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8620957/RPCS3.log.gz)

The game and the demo is currently marked as "in-game".
Maybe you can try the full game too and report it in the thread on the forum.

I haven't tried it for a long time and therefore I don't know how it behaves recently.

**Comment by Joaozin-tech** [comment]
fixed new latest rpcs3 master build ?
