### ISSUE TITLE
Regression: ToCS1 regressed to nothing after PR6405

### ISSUE THREAD

**Issue by alex88510** [RPCS3/rpcs3#6502]
The Legend of Heroes: Trails of Cold Steel I (ToCS1) has regressed from playable -> nothing since "lv2: Wait for rescheduling before confirming ETIMEOUT" has been merged. (~~I couldn't find that PR for some reason...the emulator version is 0.0.6-8578~~ Found the PR, it was #6405 and it seemed there is other user mentioned similar issue on other games in that PR)

The game will freeze on boot up and eventually crash the emulator. 
[ToCS1_freeze.zip](https://github.com/RPCS3/rpcs3/files/3587751/ToCS1_freeze.zip)

At the next master version (after #6411 merged), the game will auto close by itself (no freeze and no emu crash).
[ToCS1_autoquit.log.gz](https://github.com/RPCS3/rpcs3/files/3587752/ToCS1_autoquit.log.gz)

Tried clear all the caches and tried different combination of settings but still get nothing. 
Here is the log after clear cache 
[ToCS1_clearedcache.log.gz](https://github.com/RPCS3/rpcs3/files/3587755/ToCS1_clearedcache.log.gz)

Same issue happens on the latest master as well. 

For some reason, the next version of the game (ToCS2) is not affected by this.

**Comment by alex88510** [comment]
This issue is still present in the latest master (0.0.7-8709). 

I have tried different system (e.g. Nvidia GPU/Intel Graphics...) and still get the same issue on this game so I don't think it is something wrong with my setup. 

I am worry if this will go unnoticed for years if there is no response at all, so it will be good if there is one. 
Let me know if any other debug info is required.

**Comment by elad335** [comment]
Retest with #6556

**Comment by alex88510** [comment]
Tried with all three PPU(fast, precise, recompiler), still the same issue. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3629214/RPCS3.log.gz)

**Comment by lostromb** [comment]
I was also seeing ToCS1 crashing on startup on the latest master and bisected the regression to PR #6405 . It seems to be a race condition because I was able to start the game successfully once, but other times it has failed. The main error I see in the log is:
```
sys_spu TODO: Unimplemented SPU Thread options (0x2)
sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
'_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
```

File attached. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3705088/RPCS3.log.gz)

**Comment by GiantEnemyCrab** [comment]
In build 9047, this boots just fine.

**Comment by alex88510** [comment]
@GiantEnemyCrab Thanks for letting me know, I don't check it quite often after almost 2 months of opening this issue. 

Btw, I have backtracked and identified that it was PR #6698 that fixed this. 
![tocs1](https://user-images.githubusercontent.com/6214348/67856111-c5704180-fb4e-11e9-88e9-c173fa153433.PNG)

**Comment by LucasAlberton** [comment]
Hey guys, I'm using the latest RPCS3 update, but I'm still getting problems with this game. I get the best performance out of this build:
PPU = Recompiler LLVM
SPU = Recompiler ASMJIT
GPU = Vulkan

It emulates in 25/30 FPS, you can play it nicely, but most of the time after a boss or cutscene an infinite blackscreen appears, or the dialogue just doesn't show, and I get stuck. And also there's that problem with the audio.

But if I use this build:
PPU = Interpreter FAST, with the same SPU and GPU the game works normally, no blackscreen, cutscenes normal,, but gotta hell of slow! It runs between 5/10 FPS, and the audio problem remain.

I'm using RPCS3 = 0.0.11 - 10661 - 182b20c3 Alpha
The game is updated to version 1.02 and it shows as Playable, does anyone knows how to fix it?
