### ISSUE TITLE
[Linux] Game updates on disc games shown as available despite they're being applied correctly

### ISSUE THREAD

**Issue by Leopard1907** [RPCS3/rpcs3#6506]
This is basically a longstanding issue. As described on title. That behaviour doesn't exists on PSN games.

Versions can be used for repro: Basically any Appimage version of RPCS3. 

Basically same issue actually:

https://github.com/RPCS3/rpcs3/issues/4161

**Comment by Megamouse** [comment]
no log was attached

**Comment by Leopard1907** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3588104/RPCS3.log.gz)

**Comment by Leopard1907** [comment]
That gone unnoticed but i uploaded the log awhile ago.

**Comment by RipleyTom** [comment]
Tested here and it works fine:
![image](https://user-images.githubusercontent.com/6031700/65269320-39afd200-db19-11e9-82cc-766065e4da37.png)
![image](https://user-images.githubusercontent.com/6031700/65269336-42080d00-db19-11e9-9d7c-32d3652fa1e8.png)

Tested on linux with latest appimage.

**Comment by RainbowCookie32** [comment]
I also have the issue. Game version is not updating on the disc, but game data is created with the proper version.
![Screenshot_20190919_160516](https://user-images.githubusercontent.com/16805474/65273378-694de280-daf7-11e9-90b0-bc710a74da72.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3632801/RPCS3.log.gz)

**Comment by toccata10** [comment]
Same behaviour as @Leopard1907  here on Archlinux: it's the same problem.

**Comment by Leopard1907** [comment]
I can confirm that is fixed. Thanks!
