### ISSUE TITLE
After Burner Climax [NPUB30151] stuck on autosave screen

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6508]
start level 1 then press start to go the menu screen
choose exit and it gets stuck on the saving screen
but you can hear the music and sound fx for the intro in the background
![afterburner](https://user-images.githubusercontent.com/2696404/64516174-9c86b980-d320-11e9-84e7-62d4fbb28185.PNG)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3589491/RPCS3.zip)

**Comment by OperatorUmbra** [comment]
You can fix the issue by going to the help & options in-game - settings - and selecting auto-save off

**Comment by Margen67** [comment]
That's a workaround.

**Comment by duduke** [comment]
@OperatorUmbra Does disabling Auto-Save fixes the issue? Does manual save work?

**Comment by barolo** [comment]
@duduke It does and it works.

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by benderscruffy** [comment]
still an issue

**Comment by Ishan333** [comment]
Still an issue.

**Comment by smiglo5** [comment]
Still an issue.

**Comment by RzoregDe96** [comment]
Still an issue.

**Comment by Tha14** [comment]
Still an issue.

**Comment by Rex000** [comment]
Still an issue on build v0.0.26-14743

**Comment by Asinin3** [comment]
Test with #13492

**Comment by Rex000** [comment]
Nope, still the same

**Comment by Tha14** [comment]
Problem seems to have been fixed with RPCS 14804-65eb6258. I assume it was #13492 which was included with this version. I tested it only once though so it would be nice if someone else could confirm that it works properly now.

**Comment by Asinin3** [comment]
> Problem seems to have been fixed with RPCS 14804-65eb6258. I assume it was #13492 which was included with this version. I tested it only once though so it would be nice if someone else could confirm that it works properly now.

Sounds like it is fixed. Rex000 probably didn't check the pull request build, and just checked the latest rpcs3 build when the pull request wasn't merged... Closing

**Comment by Rex000** [comment]
Yep, it's fixed now.
