### ISSUE TITLE
[Feature Request] PS Button Menu in Fullscreen Mode

### ISSUE THREAD

**Issue by Oky12** [RPCS3/rpcs3#6513]
This feature makes it easy for users to access several options when pressing the PS button and in full screen mode. example: stop / quit emulation. restart emulation. show / hide overlay and many more

might look like this
![Screenshot_82](https://user-images.githubusercontent.com/30838114/64551886-446fa780-d360-11e9-84e2-47193c096fe7.png)

this feature is not very important but might be useful for some users

**Comment by B-Knight49** [comment]
I really like this feature but thinking in the long-term, wouldn't this interfere with vsh emulation? Perhaps this could be better if it were bindable rather than set to the PS button?

**Comment by Oky12** [comment]
> wouldn't this interfere with vsh emulation?

no. when PS menu opens. the game will be paused



> Perhaps this could be better if it were bindable rather than set to the PS button?

do you mean the keyboard shortcut?
Example: F5 to enable/disable Fps limit

**Comment by dio-gh** [comment]
Kinda duplicate of #5444.

**Comment by Oky12** [comment]
@dio-gh sorry if my request looks the same as yours. but I see the menu/ui for the PS button has not been added by Megamouse. so it doesn't matter if I request again?

**Comment by RainbowCookie32** [comment]
It'd be ideal to avoid duplicates. Just because a feature wasn't added doesn't mean we should keep opening issues requesting it until it gets added. I think the basic idea is the same as the issue dio pointed to above, so this one should be closed imo

**Comment by Oky12** [comment]
@RainbowCookie32 ok. i will close it
