### ISSUE TITLE
[Feature Request] More obvious signs when encountering a "Fatal" message during a game

### ISSUE THREAD

**Issue by B-Knight49** [RPCS3/rpcs3#6517]
It'd be nice if something could pop-up or RPCS3's window is pushed to the foreground when a fatal error is occurred. So often I'll be playing and mistake a simple freeze for a fatal crash or visa versa and assume a fatal is just a freeze which I need to wait out. 

I know the log outputs a pink error but that can sometimes be delayed if the game in question spams the log often or if the user has disabled logging. Additionally, some users have only a single monitor and can not have the log open at all times. Like this maybe:

![fatalErrorRPCS3](https://user-images.githubusercontent.com/26165117/64564580-c3a5b100-d349-11e9-842b-889f196a406f.png)

Perhaps its own issue but so often RPCS3 encounters fatal errors in a game and then completely seizes up and no longer responds requiring me to force close it with task manager. This isn't always obvious and so an error message could help alleviate this even a tiny bit.

**Comment by kd-11** [comment]
I believe this was added (report_fatal_error) although sometimes it does not work right.

**Comment by Megamouse** [comment]
The core idea behind this issue has been implemented.
I'll close this to make way for newer, more specific requests.
