### ISSUE TITLE
MotorStorm PR Crash Startup  - RSX: class std::runtime_error thrown: Assertion failed: !region.is_locked()

### ISSUE THREAD

**Issue by docace911** [RPCS3/rpcs3#6521]
#0.07-8674
Motorstorm Pacific Rift BCES00129 v1.03
i7/2080ti
Windows 10 1903

Freeze at startup. Last working rpcs3-v0.0.6-8570-0aea3368_win64

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3593651/RPCS3.log)
[TTY.log](https://github.com/RPCS3/rpcs3/files/3593652/TTY.log)

**Comment by arabek** [comment]
Try with #6512

**Comment by docace911** [comment]
I have to compile that branch right?

**Comment by Margen67** [comment]
@docace911 No. You can download compiled builds from AppVeyor:
![image](https://user-images.githubusercontent.com/3462541/64583835-5ee95700-d347-11e9-857f-034f1dc6b1dc.png)
![image](https://user-images.githubusercontent.com/3462541/64583857-758fae00-d347-11e9-8ae3-7c0253bfa571.png)

**Comment by docace911** [comment]
Got further - new crash 
0:02:51.123798 {PPU[0x1000000] Thread (main_thread) [0x0060cf28]} MEM: Access violation reading location 0xc0

(last working build rpcs3-v0.0.6-8570-0aea3368_win64)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3593819/RPCS3.log)

**Comment by kd-11** [comment]
The issue reported here is fixed, if you need to open a separate issue for the remaining crash (but that looks like a broken filesystem error to me, you may just need to reinstall the game and clear caches).

**Comment by kd-11** [comment]
Closing as fixed by https://github.com/RPCS3/rpcs3/pull/6512
