### ISSUE TITLE
Drakengard 3 Branch D Final boss Seam Shading

### ISSUE THREAD

**Issue by sagaevan** [RPCS3/rpcs3#6525]
The shading makes seams on the models very obvious. It also makes the shadows much darker than they were originally.

![image](https://user-images.githubusercontent.com/16433536/64656136-6880c680-d3fc-11e9-9ae2-6f2080fad564.png)
in comparison to
![image](https://user-images.githubusercontent.com/16433536/64656141-78000f80-d3fc-11e9-91d7-7d31cee85795.png)

**Comment by AniLeo** [comment]
This has always been an issue by the way, not a regression

**Comment by dio-gh** [comment]
Could you attach an RRC (maybe an RDC too)? Missing logs, specs and emu version too.

To take an RRC go to `View -> Debugger`, then click `RSX Capture` during the scene. The resulting `.rrc` file will be saved to `\captures\`. Use 7zip or similar to compress it, it's gonna be huge (compresses really well though).

Taking an RDC (RenderDoc Capture) is somewhat similar, but you'll need to grab [RenderDoc itself](https://renderdoc.org/) for it first. You'll have to attach RenderDoc to RPCS3 (prior to booting up the game), then use a hotkey to trigger a capture during the scene. I don't remember the exact steps, but it's not rocket science, don't worry.

Taking an RDC isn't a priority either, usually an RRC suffices. Logs would be definitely nice to have though.

@AniLeo Should have been reported long ago then.

**Comment by sagaevan** [comment]
@dio-gh sorry, here you are
CPU: AMD Radeon 7 2700x Eight Cores, GPU: Nvidia GeForce RTX 2070 16gb RAM, Windows 10. RPCS3 version: v0.0.7-8637-0dfe85dc_win64
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3598293/RPCS3.zip)
[BLUS31197_20190910204724_capture.zip](https://github.com/RPCS3/rpcs3/files/3598294/BLUS31197_20190910204724_capture.zip)

**Comment by sagaevan** [comment]
Sorry for not responding sooner btw, got distracted with playing the game lol.

**Comment by digitaldude555** [comment]
This is unreal 3 issue already tracked here. #4025

**Comment by kd-11** [comment]
Needs a retest with the recent fixes.

**Comment by AniLeo** [comment]
I did test, couldn't notice a different

**Comment by kd-11** [comment]
I need new captures for this particular issue, the old ones are incompatible. I'm working with other UE3 titles that have similar problems, but it would be better to be sure.

**Comment by AniLeo** [comment]
Fixed by #8398

**Comment by sagaevan** [comment]
I don't know how to use Github or anything but I'm happy to hear it's finally getting fixed with other games! Looking forward to its implementation in the easy-to-download versions of RPCS3 lol
