### ISSUE TITLE
Game not booting due to leftover dev_hdd1 cache

### ISSUE THREAD

**Issue by jeff3779** [RPCS3/rpcs3#6526]
"issues: 1- when booting the game once then closing it to boot it again you get a black screen with 32fps 

Workaround for the first issue is to delete the BCES00050 folder in "RPCS3 directory"/dev_hdd1/cache/ and if it happens again just close the emulator and delete the folder again (this will not affect anything with the game) EDIT:              Fixed with PR #4445 "

Well this is actually happening again for me ( the hdd1 cache file have to be removed to play the game again )

**Comment by AniLeo** [comment]
If it is consistently fixed by removing dev_hdd1 cache contents, then this is not an issue per se, and the auto removal dev_hdd1 setting just needs to be enabled by default as the real hardware also mounts dev_hdd1 as an empty path every time a game is booted.

**Comment by jeff3779** [comment]
how do i enable it by default ? i see no options

**Comment by AniLeo** [comment]
Enabling it as the default obviously has to be done upstream, you can enable it on your installation by going to configuration and looking for the setting that mention automatically clearing cache

**Comment by MSuih** [comment]
Enable cache clearing from System tab in settings and set the threshold to 0 MB. You can add this as game-specific setting, but it will clear the whole cache and not just that game's files.

**Comment by jeff3779** [comment]
Ok thanks for your answers

**Comment by jeff3779** [comment]
the setting of cache clearing at 0MB didn't work , i guess imma just delete this game as i experience also fatal error crashes with it

**Comment by AniLeo** [comment]
Deleting the game is obviously not a solution to solve this issue. Check to make sure it's wiping dev_hdd1 when you boot the game.

**Comment by jeff3779** [comment]
unless BCUS version work better with rpcs3 ?
no it is not wiping the Hdd1 folder

**Comment by AniLeo** [comment]
Then you're likely not configuring it properly. You need to set to 0MB and enable the checkbox above. 
And you need to do it on the per game config if you have one, not on global. If you don't have one, then do on global.

Whether BCUS version does this or not is not relevant for this issue as it's happening with one version

**Comment by elad335** [comment]
Have you tested #6582 ?

**Comment by elad335** [comment]
@jeff3779 Any update on pr testing ?

**Comment by jeff3779** [comment]
nope , i gave up on this sry

**Comment by Emulator-Team-2** [comment]
@AniLeo 
@elad335 
Fixed by https://github.com/RPCS3/rpcs3/pull/6698.
Tested with Folklore-Demo.

**Comment by elad335** [comment]
Close issue?
