### ISSUE TITLE
rpcs3 Doesn't Respect gcc in /usr/local?

### ISSUE THREAD

**Issue by 0pLuS0** [RPCS3/rpcs3#6528]
Hello,

I'm running Slackware 14.2 x86_64, and I have GCC-9.2.0 compiled/installed in /usr/local and when I try to compile rpcs3 it looks like llvm is not respecting the ```export``` options I've enabled for gcc in /usr/local.

This my compile script I'm using;

PRGNAM=rpcs3
BRANCH=${BRANCH:-master}
BUILD=${BUILD:-1}
TAG=${TAG:-_foo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/foo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM
git clone -b $BRANCH https://github.com/$PRGNAM/$PRGNAM
cd $PRGNAM
COMMIT=$(git rev-parse --short HEAD)
DATE=$(date -d "$(git log | awk '/Date:/ {print $4 " " $3 " " $6}' | head -1)" +%Y.%m.%d)
VERSION=${COMMIT}_$DATE
git submodule update --init
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

slackware does not package LLVMHello.so
sed -i '/LLVM CONFIG/d' $PRGNAM/CMakeLists.txt

export CC=/usr/local/bin/gcc
export CXX=/usr/local/bin/g++
export LD_LIBRARY_PATH=/usr/local/${LIBDIRSUFFIX}

mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_SKIP_RPATH=ON \
    -DUSE_SYSTEM_LIBPNG=ON \
    -DUSE_NATIVE_INSTRUCTIONS=OFF \
    -DCMAKE_BUILD_TYPE=Release ..
  make VERBOSE=1
  make install DESTDIR=$PKG
cd ..

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a LICENSE README.md $PKG/usr/doc/$PRGNAM-$VERSION

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-${VERSION}_$BRANCH-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
***
This is the output where it fails in the terminal;
***
[ 12%] Building Attributes.inc...
cd /tmp/sar/rpcs3/build/3rdparty/llvm_build/include/llvm/IR && ../../../bin/llvm-tblgen -gen-attrs -I /tmp/sar/rpcs3/llvm/include/llvm/IR -I /tmp/sar/rpcs3/llvm/include /tmp/sar/rpcs3/llvm/include/llvm/IR/Attributes.td -o /tmp/sar/rpcs3/build/3rdparty/llvm_build/include/llvm/IR/Attributes.inc
../../../bin/llvm-tblgen: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ../../../bin/llvm-tblgen)
3rdparty/llvm_build/include/llvm/IR/CMakeFiles/intrinsics_gen.dir/build.make:109: recipe for target '3rdparty/llvm_build/include/llvm/IR/Attributes.inc' failed
make[2]: *** [3rdparty/llvm_build/include/llvm/IR/Attributes.inc] Error 1
make[2]: Leaving directory '/tmp/sar/rpcs3/build'
CMakeFiles/Makefile2:2727: recipe for target '3rdparty/llvm_build/include/llvm/IR/CMakeFiles/intrinsics_gen.dir/all' failed
make[1]: *** [3rdparty/llvm_build/include/llvm/IR/CMakeFiles/intrinsics_gen.dir/all] Error 2
make[1]: Leaving directory '/tmp/sar/rpcs3/build'
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
***
You'll notice in the above output this line;  ```/usr/lib64/libstdc++.so.6``` showing it's not looking in /usr/local

```How can I fix this?```

THANKS

**Comment by clienthax** [comment]
This looks like it's going to be fun
https://stackoverflow.com/questions/30352255/how-to-compile-llvm-against-a-custom-glibc

**Comment by 0pLuS0** [comment]
@clienthax All I'm looking at trying to accomplish, is simply getting the rpcs3 source to look at /usr/local 

Hmm

**Comment by MSuih** [comment]
This seems like a llvm issue instead of rpcs3 issue.

**Comment by 0pLuS0** [comment]
Ok...

Originally I didn't want to mess with the default gcc in Slack, but I went back and recompiled gcc-9.2.0 to /usr and then upgraded gcc in Slack and recompiled rpcs3 and it compiled! :)

Thanks

**Comment by kd-11** [comment]
If this is an upstream llvm issue which it likely is then close this issue.

**Comment by AniLeo** [comment]
Closing as it's an upstream llvm issue
