### ISSUE TITLE
GTA San Andreas [BLUS31584] Rainbow stairs graphic issue

### ISSUE THREAD

**Issue by Evil0Dead** [RPCS3/rpcs3#6531]
stairs front

![1](https://user-images.githubusercontent.com/54598787/64681127-cdcdc980-d487-11e9-9be2-fa9d32eddada.png)

stairs rear

![2](https://user-images.githubusercontent.com/54598787/64681167-de7e3f80-d487-11e9-9261-ebbc91a31ce9.png)

rsx Captures for two pics

[BLUS31584_20190911112130_capture.zip](https://github.com/RPCS3/rpcs3/files/3599780/BLUS31584_20190911112130_capture.zip)
[BLUS31584_20190911112158_capture.zip](https://github.com/RPCS3/rpcs3/files/3599781/BLUS31584_20190911112158_capture.zip)

**Comment by CookiePLMonster** [comment]
It's not a bug, those stairs are supposed to be like this.

![image](https://user-images.githubusercontent.com/7947461/64732635-6a718500-d4e3-11e9-9eaf-6bffda03ee80.png)

Apparently this is a represensation of some real staircase in Los Angeles but I haven't been able to find a reference picture.

**Comment by kd-11** [comment]
This is supposed to be like that. Its always rendered that way even on PS2.
