### ISSUE TITLE
Segmentation fault on opening RPCS3 - Slackware 14.2, GCC 9.2.0

### ISSUE THREAD

**Issue by 0pLuS0** [RPCS3/rpcs3#6532]
rpcs3 Segmentation fault - Won't run...

Hello,

I'm running Slackware 14.2 x86_64

App versions compiled against rpcs3

cmake-3.14.4
gcc-9.2.0
OpenAL-1.19.1
qt5-5.13.1
vulkan-sdk-1.1.114.0

These are my compile options;
***
sed -i '/LLVM CONFIG/d' $PRGNAM/CMakeLists.txt

mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_SKIP_RPATH=YES \
    -DUSE_NATIVE_INSTRUCTIONS=OFF \
    -DCMAKE_BUILD_TYPE=Debug ..
  make VERBOSE=1
  make install DESTDIR=$PKG

***

When I try to run rpcs3 at the terminal it simply says this;

```~ >rpcs3```
```zsh: segmentation fault  rpcs3```

I ran ```gdb```, hopefully I did this correct, here's the output, this is all I have for it;'
***

```~ >gdb rpcs3```
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-slackware-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rpcs3...done.

```(gdb) r```
Starting program: /usr/bin/rpcs3 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
stx::type_info<stx::manual_fixed_typemap<void>::typeinfo>::type_info (info=..., 
    this=0x50ce2a0 <stx::type_counter<stx::manual_fixed_typemap<void>::typeinfo>::type<rsx::overlays::display_manager>>) at /tmp/foo/rpcs3/rpcs3/util/typeindices.hpp:117
117	/tmp/foo/rpcs3/rpcs3/util/typeindices.hpp: No such file or directory.

```(gdb) bt full```
0  stx::type_info<stx::manual_fixed_typemap<void>::typeinfo>::type_info (info=..., 
    this=0x50ce2a0 <stx::type_counter<stx::manual_fixed_typemap<void>::typeinfo>::type<rsx::overlays::display_manager>>) at /tmp/foo/rpcs3/rpcs3/util/typeindices.hpp:117
No locals.
1  __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /tmp/foo/rpcs3/rpcs3/util/typeindices.hpp:107
No locals.
2  _GLOBAL__sub_I_trophy_notification_helper.cpp(void) () at /tmp/foo/rpcs3/rpcs3/rpcs3qt/trophy_notification_helper.cpp:25
No locals.
3  0x00000000029ad1c2 in __do_global_ctors_aux ()
No symbol table info available.
4  0x0000000000000000 in ?? ()
No symbol table info available.

```How might I fix this?```

THANKS

P.S. Why is this also looking for the ```/tmp``` path?

**Comment by AniLeo** [comment]
Does it build on Release? Debug is not very used, may not be working at all

**Comment by Nekotekina** [comment]
Looks like a compiler bug.

**Comment by 0pLuS0** [comment]
Yes it builds on ```Release```,  and I had the same issue with the ```Release version. I only did this as ```Debug``` to submit the Issue here...

If this is a compiler bug, then why is it looking for like what appears in /tmp?

```make install DESTDIR=$PKG``` this is ok for installing?

SO I need to try and use a different GCC version?

Hmm

**Comment by 0pLuS0** [comment]
This the complete build script I am using to compile and package rpcs3 into a slackware package for installation.

As you can see below it has ```TMP=${TMP:-/tmp/foo}``` where it builds rpcs3 in /tmp/foo, where it's complaining it can't find the /path and files?

!/bin/sh
Slackware build script for rpcs3

PRGNAM=rpcs3
BRANCH=${BRANCH:-master}
BUILD=${BUILD:-1}
TAG=${TAG:-_foo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/foo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM
git clone -b $BRANCH https://github.com/$PRGNAM/$PRGNAM
cd $PRGNAM
COMMIT=$(git rev-parse --short HEAD)
DATE=$(date -d "$(git log | awk '/Date:/ {print $4 " " $3 " " $6}' | head -1)" +%Y.%m.%d)
VERSION=${COMMIT}_$DATE
git submodule update --init
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

slackware does not package LLVMHello.so
sed -i '/LLVM CONFIG/d' $PRGNAM/CMakeLists.txt

mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_SKIP_RPATH=YES \
    -DUSE_NATIVE_INSTRUCTIONS=OFF \
    -DCMAKE_BUILD_TYPE=Debug ..
  make VERBOSE=1
  make install DESTDIR=$PKG
cd ..

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a LICENSE README.md $PKG/usr/doc/$PRGNAM-$VERSION

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-${VERSION}_$BRANCH-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}

**Comment by Nekotekina** [comment]
I found one bug, maybe it will help

**Comment by Nekotekina** [comment]
@0pLuS0 Please retest master

**Comment by 0pLuS0** [comment]
Maybe one day I'll get back to this app when it becomes more stable, because I assumed the precompiled images would work, meaning the games in the list that showed as ```Playable``` would work good and some didn't. I also couldn't even get a PS3 controller to work properly...

There are way to many bugs, so I'll hold off and watch the project...

THANKS

**Comment by liberodark** [comment]
Hi have segfault on arch linux with Ryzen 5 1600

**Comment by RainbowCookie32** [comment]
Is this still an issue for you @0pLuS0, or someone else? 

> Maybe one day I'll get back to this app when it becomes more stable

Should be closed if no one is going to update it.

**Comment by 0pLuS0** [comment]
I have QT5 5.9, personally I have no need for another version...

Maybe I'll get around to checking this out sometime, not sure for now...

**Comment by AniLeo** [comment]
Pre-emptively closing, if you get this issue on current master with updated dependencies you can open a new follow-up issue
