### ISSUE TITLE
Regression: Huge performance loss in Persona 5 (#6507)

### ISSUE THREAD

**Issue by Lenox548** [RPCS3/rpcs3#6536]
Since the build 0.0.7-8687 or the PR #6507 i've been experiencing a major performance lost in Persona 5, in older builds, like 0.0.7-8677 for example, the fps was always in beetwen 30-40 in Shibuya underground mall, but now in this new build, i have constant 15-20 fps with drops of 5-1 fps, i've tried to change the prefered spu threads, enabling and disabling spu loop detection, changing the spu block size with no good results. One strange thing is that the performance gets better when i'm not in the RPCS3 window, and the fps goes to 25-30. Obviously the performance lost is still present in all the zones of the game, but i'm using Shibuya underground mall as reference because is the zone that i am in my last save 

My pc specs:
i3-8100 3.60GHz 
RX-570 8gb driver ver. 19.8.2
16gb ram

[RPCS3 build 0.0.7-8687 log.zip](https://github.com/RPCS3/rpcs3/files/3601340/RPCS3.build.0.0.7-8687.log.zip)

[RPCS3.build.0.0.7-8677.log.zip](https://github.com/RPCS3/rpcs3/files/3601342/RPCS3.build.0.0.7-8677.log.zip)

**Comment by Nekotekina** [comment]
Please try build https://ci.appveyor.com/project/rpcs3/rpcs3/builds/27274817

**Comment by Lenox548** [comment]
Ok, I'll give it a try, thanks

**Comment by Lenox548** [comment]
Mmmm, i haven't seen almost any improvement in the performance, the game runs a little bit better, but it still having drops of fps down to 0.26-5 fps and this:

> One strange thing is that the performance gets better when i'm not in the RPCS3 window, and the fps goes to 25-30

still happening

**Comment by vsub** [comment]
No problems here between 0.0.7-8677 and 0.0.7-8689
In my room - 34fps
Ginza Ticket Gate - 32fps
Central Street - 20fps
Backstreets in a heavy raining day - 28fps

Maybe it's AMD gpu thing 
i7-6700HQ,GTX1060...using MUCH weaker Intel gpu don't lower the speed by much

**Comment by AniLeo** [comment]
Seems to be a performance decrease as reported by other users, maybe you're bottlenecking somewhere else and didn't get the performance hit

**Comment by Lenox548** [comment]
> No problems here between 0.0.7-8677 and 0.0.7-8689
> In my room - 34fps
> Ginza Ticket Gate - 32fps
> Central Street - 20fps
> Backstreets in a heavy raining day - 28fps
> 
> Maybe it's AMD gpu thing
> i7-6700HQ,GTX1060...using MUCH weaker Intel gpu don't lower the speed by much

But if it is an AMD gpu thing, why in the build 0.0.7-8677, a build just before 0.0.7-8687, the game runs well without drops and without the issue when i'm not in the rpcs3 window

**Comment by vsub** [comment]
Maybe something in that rev is changed that affects AMD gpus
Someone else with AMD gpu have to confirm

I just tried going to a lot of different places and even beat a boss and everything works fine

**Comment by AniLeo** [comment]
The offending pull request does not target any GPU code directly, so that's almost certainly not the case.

**Comment by Lenox548** [comment]
> Maybe something in that rev is changed that affects AMD gpus
> Someone else with AMD gpu have to confirm
> 
> I just tried going to a lot of different places and even beat a boss and everything works fine

Other guy said that Tekken Tag Tournament 2 got worse for him too, although I don't have much information about it

**Comment by windyboy1704** [comment]
I also experienced this as well on #6507 on Intel GPU. Currently using previous version until this is fixed.

**Comment by Lenox548** [comment]
This issue is fixed now in latest master thanks to Nekotina's PR #6543 so imma close this thread

**Comment by Lenox548** [comment]
Welp. I'mma reopen this thread because since PR #6602 P5 has again a huge loss of performance,again the game suffers stuttering, and there are a lot of freezes of about 1 to 3 seconds during normal gameplay

**Comment by Lenox548** [comment]
Welp. I'mma reopen this thread because since PR #6602 P5 has again a huge loss of performance,again the game suffers stuttering, and there are a lot of freezes of about 1 to 3 seconds during normal gameplay

**Comment by Aijul** [comment]
I can confirm this happening to me as well on PR #6602 it seems normal on PR #6571 

![ss 8809](https://user-images.githubusercontent.com/55964122/65842157-365be800-e35c-11e9-9bbf-ffad887d5ef7.png)
![ss 2 8741](https://user-images.githubusercontent.com/55964122/65842158-365be800-e35c-11e9-8210-85cb59835f92.png)

**Comment by vsub** [comment]
I am not sure if this has anything to do with it but if you look at the screen shots you will notice that everyone reporting the problem have the psn version of the game

**Comment by windyboy1704** [comment]
> 
> 
> I am not sure if this has anything to do with it but if you look at the screen shots you will notice that everyone reporting the problem have the psn version of the game

I got the same issue on Bluray version. Debunked

**Comment by osmos1** [comment]
Can confirm this also happens on BLUS31405 and BLJS10318 along with the high CPU usage on the latest master.

**Comment by Nekotekina** [comment]
Does the problem happen if Max SPURS threads is set to 3?

**Comment by purifiedh2o** [comment]
Not much, but it's still slower about 5fps loss

**Comment by Nekotekina** [comment]
I'd like to test two PRs in regard to this issue:
https://github.com/RPCS3/rpcs3/pull/6791
https://github.com/RPCS3/rpcs3/pull/6800

**Comment by purifiedh2o** [comment]
With SPURS limit 3: both PRs are OK, better performance than older versions.
Without SPURS limit: #6800 is much better (#6791 still suffers slow Thieve Guild), although it still suffers performance loss and more sound shuttering, I only get about 16-22 fps in the title screen.

**Comment by Nekotekina** [comment]
Merged #6800 and rebased #6791. Need to retest #6791

**Comment by purifiedh2o** [comment]
Better now. Still 16-22fps in title screen and lots of sound stuttering like #6800 tho (unlimited).

**Comment by Lenox548** [comment]
Hi, I realized that the issue I was reporting also happens to all the other games that I have, so I will close this thread and I will open a new one with the appropriate and updated data to try to help solve this issue

**Comment by Lenox548** [comment]
The new thread that I opened is this #7007 in case anyone wants to take a look
