### ISSUE TITLE
Regression: Warriors Orochi 3 Ultimate doesn't boot (#6416)

### ISSUE THREAD

**Issue by pancirno** [RPCS3/rpcs3#6537]
Game runs fine on previous build (0.0.7-8666)

**Comment by RainbowCookie32** [comment]
Post a proper log instead of pasting a wall of text from the log window. RPCS3.log.gz from the emulator's folder

**Comment by pancirno** [comment]
Here are the logs
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3602452/RPCS3.log.gz)

"Now Loading" will flash briefly then process abruptly ends

**Comment by AniLeo** [comment]
Tagging #6416 @Megamouse
