### ISSUE TITLE
Regression: Huge performance hit in Uncharted, God of war 3, Sonic Unleashed and possibly other titles? (#5923)

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#6539]
This is a lost regression that was buried a long time ago. No one cares about Sonic but since this an SPU regression i don't think it should be ignored.

This is the build that broke it https://github.com/RPCS3/rpcs3/pull/5923.
Anything before that will restore performance.

Before - 8063 [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3602353/RPCS3.log.gz)
![image](https://user-images.githubusercontent.com/17715080/64727393-22386f80-d4af-11e9-85f5-6220055b3f56.png)

After -  8089 [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3602369/RPCS3.log.gz)
![image](https://user-images.githubusercontent.com/17715080/64727547-76435400-d4af-11e9-859e-b8ab7a29b004.png)

**Comment by Xcedf** [comment]
Never had time to report it, or was too lazy, but confirm this regression, especially in the Safe mode, tested in Uncharted   games, i should say about 10% performance loss.

**Comment by mfdsrax2** [comment]
Yeah I was playing sonic and uncharted these days and I thought the fps drop was just an illusion. It's good to find someone else who has the same problem.

Here's a small hint. I regained some fps by disabling 'Approximate xfloat'.

**Comment by Nekotekina** [comment]
May try https://github.com/RPCS3/rpcs3/pull/6696

**Comment by Yahfz** [comment]
@Nekotekina No performance difference between the PR and master.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3690163/RPCS3.log.gz)


[spu-safe-v1-tane.zip](https://github.com/RPCS3/rpcs3/files/3690172/spu-safe-v1-tane.zip)

**Comment by Yahfz** [comment]
As of master the performance is back to where it should be. closing.
