### ISSUE TITLE
Motorstorm Pacific Rift: MEM: Access violation reading location 0xc0

### ISSUE THREAD

**Issue by docace911** [RPCS3/rpcs3#6549]
Windows 10
2080ti/i7
0.0.7-8699 (Main build 9/12)

Gets to loading screen and crashes with Access Violation.

--
S {RSX Decompiler Thread} RSX: New program compiled successfully x2
E {PPU[0x1000004] Thread (fios mediathread) [0x01141ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00129/USRDIR/ms2.psarc” [3]
F {PPU[0x1000000] Thread (main_thread) [0x0060cf28]} MEM: Access violation reading location 0xc0----

Cleared cache, same issue.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3608415/RPCS3.log)

**Comment by AniLeo** [comment]
I already closed this.
