### ISSUE TITLE
God Of War 3 very weird issue

### ISSUE THREAD

**Issue by Wizzy2018** [RPCS3/rpcs3#6550]
CPU Ryzen 7 1700 OC 3.7 Ghz
RAM DDR4-2400Mhz
GPU RX 470 4Gb
Rpcs3 0.0.7-8700

God of war 3 is pretty playable but i have weird problem and if can someone check this out to see what is going on here?

[God of War® III [BCES00510] 2019-09-13 09-15-57.zip](https://github.com/RPCS3/rpcs3/files/3608841/God.of.War.III.BCES00510.2019-09-13.09-15-57.zip)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
