### ISSUE TITLE
God of War 3 BCES00510 - Linux Problem

### ISSUE THREAD

**Issue by rcaridade145** [RPCS3/rpcs3#6552]
When trying to run GOW 3 on Linux i get this under gdb

Thread 26 "SPU[0x2000000] " received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffefd7fa700 (LWP 20308)]
0x0000000000800760 in spu_thread::do_dma_transfer(spu_mfc_cmd const&) ()

#0  0x0000000000800760 in spu_thread::do_dma_transfer(spu_mfc_cmd const&) ()
Backtrace stopped: Não é possível acessar a memória no endereço 0x7ffefd7f9a68
(gdb) bt full
#0  0x0000000000800760 in spu_thread::do_dma_transfer(spu_mfc_cmd const&) ()
No symbol table info available.
Backtrace stopped: Não é possível acessar a memória no endereço 0x7ffefd7f9a68

This is with SPU to Mega and Multithreaded RSX enabled (Vulkan API) .

If i run it not under GDB i get 

terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at

**Comment by XenonPK** [comment]
It boots for me with SPU=safe
Mega segfaults.

I tested with Multithreaded RSX off, BTW.

**Comment by rcaridade145** [comment]
@XenonPK  Thank you. It also boots for me using SPU=safe.

**Comment by AniLeo** [comment]
Closing then, since Mega and Giga are expected and known to be unstable as is with many games, only Safe should be used.
