### ISSUE TITLE
Motorstorm Pacific Rift crashing: MEM Access 0xc0 - **NOT fixed****

### ISSUE THREAD

**Issue by docace911** [RPCS3/rpcs3#6553]
Something must be hardware related as prior ticket closed.

RCPS3
0.0.7-87009
Last working build - rpcs3-v0.0.6-8570-0aea3368_win64

Windows 10 1903
Intel i7/16gb
NVIDIA 2080ti
![Capture](https://user-images.githubusercontent.com/54877160/64902225-0a0c5000-d669-11e9-8a85-f33a0d0d5f73.PNG)

Hangs entering game, Mem Access 0xC0
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3612257/RPCS3.log)

**Comment by RainbowCookie32** [comment]
You should take a look at the 2 comments of the original issue:
https://github.com/RPCS3/rpcs3/issues/6527#issuecomment-530728435
https://github.com/RPCS3/rpcs3/issues/6527#issuecomment-530862281

There's a problem in your side. It's not a regression.

**Comment by AniLeo** [comment]
If you have comments to add, you do so on the original issue, even if it's closed. Stop spawning new issues. It was already explained to you you're missing game files.
