### ISSUE TITLE
Regression: Armored Core Verdict Day; RSX Access Violation Handler on versions beyond #6206 (8566)

### ISSUE THREAD

**Issue by greyyzilla** [RPCS3/rpcs3#6563]
The main issue is that the current version I've mentioned where I play on Armored Core Verdict Day (BLUS31194) works fine but later versions of the RPSC3 simply made the game not work, rather it pops out an error instead.

Currently playing on version #6206 0.0.6 8546 but I may recall this error not happening on #6394 

Exact error log states from latest #6557 :
RSX: g_access_violation_handler(0xc0320080, 0): Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKTextureCache.h:292)

The error log can be found on RPCS3 Discord:

https://discordapp.com/channels/272035812277878785/319224795785068545/622800127190630401

**Comment by kd-11** [comment]
You should update the title and description mentioning which game exactly regressed, as well as the first broken version of rpcs3.

**Comment by greyyzilla** [comment]
I have done more testing and have not pinpointed which exact version of RPSC3 has been causing Armored Core: Verdict Day to cause crashes. I also have avoided builds that causes severe issues.

During testing, with PPU Recompiler on causes strange crashes such as:

> F {RSX [0x0008e40]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
> (in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKTextureCache.h:304)

> RSX: g_access_violation_handler(0xc0320080, 0): Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
> (in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:1052)

_maybe this is related to launching RPSC3 through Steam with controller support for it?_

This may be a false regression but latest PR #6557 has the game working fine, perhaps the issues I was having were related to launching RPSC3 through Steam and the fix was to not launch RPSC3 through Steam then.

Closing issue, I hope this is true for the next RPCS3 builds to come!
