### ISSUE TITLE
Broken and flickering vertices in Rio / Vancouver 2010

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#6565]
[ Rio - Vulkan / OpenGL ]
![1](https://user-images.githubusercontent.com/38318848/64925112-343a4b00-d7ec-11e9-86b8-8bbdff3fa93e.png)
**Link:**
[RSX Capture](https://drive.google.com/file/d/1hCYuXNBM17wLJtujz5LPjX1rN0V6TlLr/view?usp=sharing)
[RDC Capture-OpenGL](https://drive.google.com/file/d/1DMugm2716imIeHtkVmURYC77-EnLRnJm/view?usp=sharing)

---------------------------------------------------------------------------------------------------
[ Vancouver 2010 - Vulkan / OpenGL ]
![2](https://user-images.githubusercontent.com/38318848/64925186-3cdf5100-d7ed-11e9-850d-4172aed270ea.png)
**Link:**
[RSX Capture](https://drive.google.com/file/d/1Vh2joodV9fhn0f-bFLY_0XfH0kqxukkD/view?usp=sharing)
[RDC Capture-OpenGL](https://drive.google.com/file/d/1CqFHvkVhse7F0rP8Xuk-WOfpl93xDAEw/view?usp=sharing)

**Comment by kd-11** [comment]
Is this a regression or was it always like this? I remember working on RIO bugs a long time ago, but I don't remember this issue being present.

**Comment by Emulator-Team-2** [comment]
@kd-11 
It's not regression, these two games have always looked like this.
