### ISSUE TITLE
Crash Persona 5

### ISSUE THREAD

**Issue by Boddah22** [RPCS3/rpcs3#6569]
I'm having this problem where I'm playing normally until an error pops up, crashes the game and closes RPCS3. I know that I have to upload the log file but I don't know this is the correct one

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3618906/RPCS3.log.gz)

**Comment by AniLeo** [comment]
The issue tracker is not the place to ask for support as indicated on the issue guidelines. Ask for support on the appropriate channels.
