### ISSUE TITLE
ROTQMBI/ROTQBI/SHLQBI implementation

### ISSUE THREAD

**Issue by plappermaul** [RPCS3/rpcs3#6570]
The description of the above functions in the SPU instruction manual reads:

The contents of register ra are ... by the number of bits specified by the 3 least significant bits of word element 0 of register rb. ...

The implemenation in ASMJITRrecompiler always starts with:

void spu_recompiler::...(spu_opcode_t op)
{
	const XmmLink& va = XmmGet(op.ra, XmmType::Int);
	const XmmLink& vb = XmmGet(op.rb, XmmType::Int);
	const XmmLink& vt = XmmAlloc();
	const XmmLink& v4 = XmmAlloc();
	c->psrldq(vb, 12);
	c->pand(vb, XmmConst(_mm_set_epi64x(0, 7)));
	c->movdqa(v4, XmmConst(_mm_set_epi64x(0, 64)));
        ...

Looking at the code I expect the c->psrldq(vb, 12) command to be wrong here. If I did not miss any byte ordering problems the above code will shift/rotate by bits 12-14 of word element 0 in register rb and not by bits 0-2.

**Comment by elad335** [comment]
Looking at rotqmbi it's fine.

**Comment by elad335** [comment]
You should read PSRLDQ description, it shifts by bytes, not bits.
element 0 is actuslly the high word and not lowest.

**Comment by kd-11** [comment]
Yea, this is actually correct. If psrldq/pslldq worked with bits, we wouldn't have to split the op into 2 shifts and or the result.

**Comment by plappermaul** [comment]
Thanks for the clarification. As already guessed i messed up with the byte order.

**Comment by Nekotekina** [comment]
Closing as answered.
