### ISSUE TITLE
Regression: Race The Sun [NPUB31532] now only loadable (#6545)

### ISSUE THREAD

**Issue by burninrubber0** [RPCS3/rpcs3#6574]
RPCS3 v0.0.7-8712-794a1fef Alpha | HEAD
Previously playable, this game is now only loadable regardless of settings or system. Seemingly caused by #6545. The issue remains present on latest master (0.0.7-8725-c900fb0d).
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3622721/RPCS3.log.gz)

**Comment by elad335** [comment]
Fixed by #6556
