### ISSUE TITLE
SHLQBI inperformant

### ISSUE THREAD

**Issue by plappermaul** [RPCS3/rpcs3#6575]
From the documentation we read: 

shlqbi rt, ra, rb Shift left quadword (128 bit value) by bits. The contents of register ra are shifted left by the number of bits specified by the 3 least significant bits of word element 0 of register rb. The result is placed in register rt. 

The current recompiler code reads:

```
void spu_recompiler::SHLQBI(spu_opcode_t op)
{
	const XmmLink& va = XmmGet(op.ra, XmmType::Int);
	const XmmLink& vb = XmmGet(op.rb, XmmType::Int);
	const XmmLink& vt = XmmAlloc();
	const XmmLink& v4 = XmmAlloc();
	c->psrldq(vb, 12);
	c->pand(vb, XmmConst(_mm_set_epi64x(0, 7)));
	c->movdqa(v4, XmmConst(_mm_set_epi64x(0, 64)));
	c->movdqa(vt, va);
	c->pslldq(vt, 8);
	c->psubq(v4, vb);
	c->psllq(va, vb);
	c->psrlq(vt, v4);
	c->por(vt, va);
	c->movdqa(SPU_OFF_128(gpr, op.rt), vt);
}
```

Summed up this results in:

vb = ( vb >> 96 ) & 0x7
vt = ( va << 64 ) >> ( 64 - vb ) 
va = va << vb
vt = vt | va

vt is more or less the lower 64 input bits shiftet left by the 3 bit value. Or-ing with the 3 bit shiftet 128 bit input really does nothing. The simple short form should be:

```
void spu_recompiler::SHLQBI(spu_opcode_t op)
{
	const XmmLink& va = XmmGet(op.ra, XmmType::Int);
	const XmmLink& vb = XmmGet(op.rb, XmmType::Int);
	c->psrldq(vb, 12);
	c->pand(vb, XmmConst(_mm_set_epi64x(0, 7)));
	c->psllq(va, vb);
	c->movdqa(SPU_OFF_128(gpr, op.rt), vt);
}
```

**Comment by Nekotekina** [comment]
You just shift two 64-bit words separately...

**Comment by elad335** [comment]
What neko means it is that this instruction shifts the entire vector as a whole instead of in saperate parts (bits lost in the lower 64bit word where they should be shifted to the upper 64bit word.

**Comment by kd-11** [comment]
I feel this isn't the place to learn how the emulator works, discord or reddit would have been a much better discussion forum for questions like these. Also, the alternative implementation given is wrong and does something completely different. There are no 128-bit shifts with bit granularity on x86.

**Comment by plappermaul** [comment]
Hi,

sorry for the confusion. I totally mixed the quadword (128bit) from SPU instruction set with quadword (64 bit) from x86 SIMD instruction set. There was no intention to provide wrong code. So I will take some time to learn it better and come back if I have tested code. 

Issue can be closed.
