### ISSUE TITLE
Unhandled win32 exception since #6560

### ISSUE THREAD

**Issue by kacperoo29** [RPCS3/rpcs3#6579]
Ever since #6560 every game that I try to run crashes with unhandled win32 exception 0xc0000005. Build previous to that one work just fine. Log always ends on the line "static_hle: Added a pattern for memcmp(id:0xC3E14CBE)". Other people have reported the same issue on discord, but during firmware installation instead of game startup.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3628281/RPCS3.log)
![exception](https://user-images.githubusercontent.com/5243877/65184162-3f4be000-da65-11e9-9e34-6c884b7f713c.png)

**Comment by Nekotekina** [comment]
Try #6576

**Comment by kacperoo29** [comment]
Still the same, the only thing that changed is Segfault reading location.
![exception2](https://user-images.githubusercontent.com/5243877/65188439-b76ad380-da6e-11e9-9f48-823233991c5b.png)

**Comment by kacperoo29** [comment]
So after some debbuging I have found out what causes this error. In sys_usbd.cpp at line 138  libusb_free_device_list() returns an invalid list. Simple if statement has fixed it, but propably breaks something else.

**Comment by RipleyTom** [comment]
Thanks for debugging, I submitted a fix.
