### ISSUE TITLE
White screen when booting a game after GPU change

### ISSUE THREAD

**Issue by giggioman00** [RPCS3/rpcs3#6581]
As above, I recently changed my GPU, of course upgraded the drivers and all but now when I try to boot the game I always get a white screen. I attach the log

> RPCS3 v0.0.5-7503-65ca9344 Alpha | HEAD
> Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz | 8 Threads | 15.95 GiB RAM | AVX+
> ·! 0:00:00.000000 RSX: Found vulkan-compatible GPU: 'AMD Radeon RX 5700' running on driver 2.0.106
> ·! 0:00:00.233909 Compatibility notice: { Finished reading database from file: E:/PS3/GuiConfigs/compat_database.dat }
> ·! 0:00:10.130054 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.130350 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.130623 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.130894 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.131534 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.132178 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.132818 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.133101 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.133409 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.133685 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.134093 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.134511 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.134934 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.135233 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.135505 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.135771 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.136039 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.136315 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.136601 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.136868 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.137144 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.137412 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.137674 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.137939 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.138203 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.138473 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.138733 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.139016 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.139279 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.139546 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.139809 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.140074 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.140340 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.140600 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.140861 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.141122 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.141384 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.141651 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.141915 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.142176 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.142438 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.142750 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.143015 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.143276 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.143539 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.143803 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.144063 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.144340 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.144605 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.144868 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.145134 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.145398 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.145664 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.145926 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.146188 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.146450 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.146709 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.146970 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.147229 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.147493 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.147753 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.148357 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.148626 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.148892 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.149161 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.149423 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.149714 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.150033 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.150327 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.150942 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.151232 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.151502 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.151771 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.152046 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.152315 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.152581 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.152843 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.153114 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.153379 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.153649 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.153914 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.154176 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.154444 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.154711 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.154973 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.155247 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.155520 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.155790 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.156063 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.156336 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.156617 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.156898 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.157188 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.157458 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.157723 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.157988 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.158254 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.158519 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.158785 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.159047 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.159312 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.159577 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.159841 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.160107 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.160370 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.160658 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.160926 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.161193 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.161461 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.161724 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.161988 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.162251 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.162515 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.162781 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.163045 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.163313 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.163579 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.163842 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.164106 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.164368 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.164631 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.164893 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.165157 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.165419 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.165686 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.165948 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.166212 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.166478 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.166744 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.167017 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.167305 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.167573 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.167838 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.168101 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.168368 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.168634 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.168897 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.169160 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.169428 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.169693 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.169955 LDR: SELF: No NPDRM control info found!
> ·! 0:00:10.170217 LDR: SELF: No NPDRM control info found!
> ·W 0:00:10.171494 RSX: Last used Vulkan adapter not found: setting to default!

**Comment by AniLeo** [comment]
This is not the place to ask for support as indicated in the guidelines, ask for support on the appropriated platforms

**Comment by giggioman00** [comment]
You're forum doesn't send emails

**Comment by AniLeo** [comment]
It does, users are activating their accounts on a daily basis, check Spam or if your provider filters them out then any of the other platforms available for support
