### ISSUE TITLE
Storm [NPUB30210] cannot start a new game (stuck in a loop)

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6586]
in the trail version you can start a new game but in the retail version when you choose new game or load save game it just keeps going back to the menu
![storm](https://user-images.githubusercontent.com/2696404/65232126-3578ba00-db03-11e9-9cc6-f8bedea16d1a.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3630446/RPCS3.log.gz)

**Comment by elad335** [comment]
Can you just upload log with #6587 ?

**Comment by benderscruffy** [comment]
sorry i dont know how to compile it
if someone wants to do it for me please that would be great

**Comment by incognitoh** [comment]
@benderscruffy https://ci.appveyor.com/project/rpcs3/rpcs3/builds/27533755/artifacts

**Comment by benderscruffy** [comment]
ok here is the new log with #6587 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3639187/RPCS3.log.gz)
thanks to incognitoh aswell

**Comment by elad335** [comment]
Can you reupload log using latest master?

**Comment by benderscruffy** [comment]
still happens in the latest master

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by benderscruffy** [comment]
still an issue

**Comment by Megamouse** [comment]
I think this is fixed now

**Comment by digitaldude555** [comment]
![Screenshot (3028)](https://user-images.githubusercontent.com/26138653/200183670-c6875078-c932-403d-ac41-5b4533364446.png)
close it.
