### ISSUE TITLE
VKTextureCache issues after #6359

### ISSUE THREAD

**Issue by jacob1218** [RPCS3/rpcs3#6597]
After PR #6359, some games now crash with VKTextureCache errors.\
GT5's crash can be reproduced by starting a race in arcade mode, and finishing or quitting the race.
Logs attached.
[RPCS3 madden.log](https://github.com/RPCS3/rpcs3/files/3638141/RPCS3.madden.log)
[RPCS3 GT5.log.gz](https://github.com/RPCS3/rpcs3/files/3638132/RPCS3.GT5.log.gz)

**Comment by kd-11** [comment]
Test https://github.com/RPCS3/rpcs3/pull/6667

**Comment by jacob1218** [comment]
#6667 Fixed this. Closing.

**Comment by AniLeo** [comment]
It's not yet merged
