### ISSUE TITLE
Sonic & SEGA All-Stars Racing Demo [NPEB90229] nothing but a white screen

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6599]
tried differant settings nothing but a white screen
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3638534/RPCS3.log.gz)

**Comment by Xcedf** [comment]
Works just fine, perhaps you have smth wrong with your emu or settings
![17](https://user-images.githubusercontent.com/7060586/65386353-3304a300-dd43-11e9-9125-cdb4fbe50b3f.jpg)

**Comment by AniLeo** [comment]
This game does work properly at least with Vulkan, probably an issue with OpenGL which is known to currently have several issues which will be fixed, closing this one
