### ISSUE TITLE
USE_SYSTEM_YAML_CPP?

### ISSUE THREAD

**Issue by guoyunhe** [RPCS3/rpcs3#6600]
In openSUSE, we have yaml-cpp in system. Can we use system yaml-cpp rather than compile it inside rpcs3?

**Comment by AniLeo** [comment]
Pretty sure you'll have to use the RPCS3 fork after the recent modifications to exceptions
Tagging @hcorion

**Comment by Nekotekina** [comment]
Sadly, not possible. It had to be modified to be compatible with -fno-exceptions

**Comment by hcorion** [comment]
Gonna close this issue, as mentioned, currently yaml-cpp headers are incompatible, and yaml-cpp doesn't seem to be meant as a system-wide library. In addition, upstream yaml-cpp hasn't done any releases since 2019.
