### ISSUE TITLE
[Feature Request] Allow for custom DNS settings via config.yml

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#6606]
As there seem to be more and more private servers popping up, it'd be useful if the emulator supported DNS overriding without having to recompile.

The idea is to have a new line added to `config.yml` called `Primary DNS`, which would accept an IPv4 address and a port in the usual fashion (`127.0.0.1:53`).

This is where the DNS address and port is being set currently afaik:
https://github.com/RPCS3/rpcs3/blob/c43a126f6210373db9b249eae9d80ca47d647705/rpcs3/Emu/Cell/lv2/sys_net.cpp#L456-L458

**Comment by RipleyTom** [comment]
I don't think overriding dns is necessary when we can override ips directly if needed.

**Comment by dio-gh** [comment]
I've tried looking into that, but I can't seem to find a way? Per-application MITM I mean. I'm aware you can do IP/hostname based redirects e.g. on Windows through the `hosts` file, but that's a host system-level redirect, and I think that would also mess with the host system's DNS settings. (As it is very possible that a user would also be using Google's DNS servers.) That file requires admin privileges to be edited too btw. Just all-around messy and unclean imo.

But maybe I've indeed missed something like that. Google didn't help. :man_shrugging:

**Comment by RipleyTom** [comment]
What I was saying is that we don't need MITM at all.
When an application tries to connect it will call sys_net_bnet_connect with addr being the address it wants to connect to, we can simply change that address there.
Same with host resolution, it will call sys_net_gethostbyname and we can solve the hostname to any address we want if needed.

**Comment by dio-gh** [comment]
That has interesting implications. So you'd imagine a feature where you could create per-game redirection tables instead and the emu would resolve them on-demand?

**Comment by RipleyTom** [comment]
Yes, that's the best option imo.

**Comment by dio-gh** [comment]
I'll come up with a design idea, maybe talk it out on Discord, then open a different feature request ticket about that then. Thanks for the insights.
