### ISSUE TITLE
Demon's Souls: breaking any furniture makes CPU go 100% and FPS go 1

### ISSUE THREAD

**Issue by gfaren** [RPCS3/rpcs3#6607]
Every time something like a barrel, chair, table, etc, is broken by me or NPCs in Demon's Souls, the framerate goes from whatever it is at the time to 1-7fps. This was already happening before the 60fps patch (which I installed to see if it could solve this issue). Moving some planks also affects the framerate.

The game before breaking something: 
![image](https://user-images.githubusercontent.com/55062291/65379342-d9499d80-dc9c-11e9-8b93-9fbceb5129d3.png)

And when I break something, this goes for about 10 seconds or more sometimes: 
![image](https://user-images.githubusercontent.com/55062291/65379349-f2eae500-dc9c-11e9-82c7-cb6ee22af637.png)

After this, it takes a while for performance to come back
![image](https://user-images.githubusercontent.com/55062291/65379363-1ada4880-dc9d-11e9-8176-e7d21c92dce4.png)

Hardware is:
i5-7600K, 
16GB DDR4 2133Mhz
GTX 970
Running the game on native resolution (720p), with and without 60fps patch.
RPCS3 builds:
v0.0.7-8751-3121fecc_win64 
v0.0.7-8752-399ea2ed_win64
Had a previous build with the same issue in the morning, but updated (8751) to use the 60fps patch. Updated again later to the current build (8752) as per suggestion of Discord member.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3639106/RPCS3.log.gz)

**Comment by AniLeo** [comment]
May be related to SPU caching when you break the object, try repeating the same action a few times, if it stops happening (due to SPU being cached) then that's it

**Comment by gfaren** [comment]
> 
> 
> May be related to SPU caching when you break the object, try repeating the same action a few times, if it stops happening (due to SPU being cached) then that's it

Thanks for the reply. As of now, I ran the tutorial +  Boletarian Palace 1-1 twice now, also reloading the bridge on the start to respawn the breakables. Sadly, the problem still persists. Also removed the 60 patch (and config mods that were needed) before getting back to break more things.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3640091/RPCS3.log.gz)

Since I didn't notice any rule against an external link, here is a shot of what happens, in video https://imgur.com/a/UiOd6E5 

(sorry if this is not allowed, will remove if needed)

**Comment by AniLeo** [comment]
Your video shows that it's slowing down due to CPU bottleneck, when you get frame drops your CPU is pinned at 100% - it's not able to execute logic fast enough when you break objects and struggles to keep pace.

**Comment by kd-11** [comment]
Yea, this is a performance bottleneck on SPU emulation and not necessarily a bug. This game has its logic largely dependent on the physics engine (Havok) and that is very SPU heavy. I'd suggest playing around with options. Disable 'Thread scheduler', you don't need it for an intel chip. Disable SPU loop detection. If nothing changes you may play around with Max SPU threads option; try something like 3 or 4, but expect worse average performance than using auto.

**Comment by gfaren** [comment]
@kd-11 @AniLeo thank you both for clarifying my issue! I'll make the issue closed, as well trying kd-11 suggestions to try to improve performance on my end, since it became clear that the issue is my rig.

Again, thanks everyone for the patience.
