### ISSUE TITLE
OutRun Online Arcade [NPEB00073] shader compilation failure when selecting car

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6613]
E {RSX Decompiler Thread} RSX: Failed to compile shader: Fragment shader failed to compile with the following errors:
ERROR: 0:74: error(#143) Undeclared identifier: diff_color1
ERROR: 0:74: error(#162) Wrong operand types: no operation ":" exists that takes a left-hand operand of type "float" and a right operand of type "default in highp 4-component vector of vec4" (or there is no acceptable conversion)
ERROR: 0:75: error(#143) Undeclared identifier: spec_color1
ERROR: 0:75: error(#162) Wrong operand types: no operation ":" exists that takes a left-hand operand of type "float" and a right operand of type "default in highp 4-component vector of vec4" (or there is no acceptable conversion)
ERROR: error(#273) 4 compilation errors.  No code generated

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3639422/RPCS3.log.gz)

**Comment by kd-11** [comment]
Closing as fixed.
