### ISSUE TITLE
Regression: Monopoly Streets [NPUB30592] doesn't boot (#6421)

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6614]
could be due to 
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x3b7420
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x3b7794
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x41ece8
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x427868
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x427b2c
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x428028
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4280f8
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4286b4
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x428a98
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x435fb4
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x43614c
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x45b798
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x45b9bc
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4ab240
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4ab41c
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4ab424
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4ab42c
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4ab434
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4ab518
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4ae808
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4afe74
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4baf4c
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4c036c
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4c1e90
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4c4180
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4c42d0
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4c45b4
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4c4844
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4c48f4
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4c48fc
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4cee18
E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __0x4d1e44

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3639449/RPCS3.log.gz)

**Comment by incognitoh** [comment]
@Nekotekina @elad335 

regression..  RPCS3 v0.0.6-8576-3317e13b Alpha seems to be the last build that worked properly.

0.0.6-8578 - game is broken.  doesnt load past first intro/loading screen
https://ci.appveyor.com/project/rpcs3/rpcs3/builds/26976440


0.0.6-8603- white screen. doesnt start loading at all 
https://ci.appveyor.com/project/rpcs3/rpcs3/builds/26988064

**Comment by AniLeo** [comment]
Test with #6584

**Comment by benderscruffy** [comment]
yep goes ingame with #6584

**Comment by benderscruffy** [comment]
close as it it #6584 merged into master
