### ISSUE TITLE
The Last of Us Approximate Xfloat issue

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#6616]
Previously this was jus a part of https://github.com/RPCS3/rpcs3/pull/6359 discusion, but decided to do a separate issue from that:
Here's my observations on The Last of US from SPU side if, before i start none of SPU options affect Sunrays effect, i use different instruction sets to achieve best Accuracy/Speed. For this game Approximate FCGT and FNMS instructios must always be ON, otherwise the game will crash, the only instruction that has visual affect on this game is FMA, so here's the difference

Inaccurate FMA: has colored pixels artifacts (which is actually old regression, can't find myself what caused it), girl's hair missing, and game crashes on first gunshot or if girl pick ups the cell phone, the reason i guess in some effect that called Omni/nonshadow light in U2 Debug menu, i think it interferes. But the main thing: aside all of these bugs the screen is clear, black squareas are not presented.
![34](https://user-images.githubusercontent.com/7060586/64955524-2094f000-d891-11e9-873a-b3a35b18e4b6.jpg)

Approximate FMA: also can have colored pixels by itself (which is fixed if combined with Approximate FM) girl's hair is working, no crashes on gunshots, but here's the well known black squared artifacts.
![36](https://user-images.githubusercontent.com/7060586/64955385-c6942a80-d890-11e9-9eac-66aa522ee400.jpg)

Accurate FMA: the instruction not work by itself, requires at least Approximate FM to be in pair with, otherwise crashes, but visuals are clear, everything works, no crashes, yet has a major performance impact.
![33](https://user-images.githubusercontent.com/7060586/64955648-75386b00-d891-11e9-917e-f1fbc80f2b12.jpg)
My verdict from all of this: smth is wrong with Approximate FMA, it would be great if it gains a little bit more accuracy.

**Comment by KatherineFtw** [comment]
Isn't this what the Accurate XFloot option is for?

**Comment by plappermaul** [comment]
Hi,

could you compare your observations with the following fix of mzero_if_xtended():

```
const auto aa = bitcast<s32[4]>(fabs(a));
const auto ab = bitcast<s32[4]>(fabs(b));
return eval(select(max(aa, ab) > 0x7f7fffff, fsplat<f32[4]>(0.), a * b));
```

```
const auto aa = eval(bitcast<u32[4]>(a) << 1);
const auto ab = eval(bitcast<u32[4]>(b) << 1);
return eval(select(min(aa, ab) == 0, fsplat<f32[4]>(0.), a * b));
```

Idea behind that: The function currently produces zero if one of the input operands is +/-INF or +/-iNaN. That does don't make sense at all but might be a lucky coincidence. Instead it must read: if one of the input operands is zero just produce zero as the result of the multiplication.

**Comment by Xcedf** [comment]
@plappermaul, Hi, here's my observation from this code, yes the black squares are gone now, but girl's hair is also missing now, just like on non-accurate FMA. The second thing it not very stable, emulator closes itself right before i gain control of character.
![3](https://user-images.githubusercontent.com/7060586/67624513-22f84b80-f83a-11e9-84c8-468c27a3f625.jpg)

**Comment by plappermaul** [comment]
Fuck, missed the shift. Please try

```
const auto aa = eval(bitcast<u32[4]>(a) << 1);
const auto ab = eval(bitcast<u32[4]>(b) << 1);
return eval(select(min(aa, ab) <= 0xffffff, fsplat<f32[4]>(0.), a * b));
```

**Comment by Xcedf** [comment]
@plappermaul, no difference, but here's an update on previous code:
for some games i use a hacky version of FM, based on approximate FMA code
set_vr(op.rt, mzero_if_xtended(get_vr<f32[4]>(op.ra), get_vr<f32[4]>(op.rb)));
it's not as accurate as original but work for some games including TLoU, and combined with this mzero_if_xtended code, looks fine and stable
![3](https://user-images.githubusercontent.com/7060586/67624917-dadc2780-f83f-11e9-89d0-7b63a9b2ada7.jpg)

**Comment by dio-gh** [comment]
Referencing #6872 and [this](https://github.com/RPCS3/rpcs3/pull/6872#issuecomment-546470731) comment in particular, just so everyone's on the same page and won't investigate needlessly.

**Comment by Xcedf** [comment]
@dio-gh i can remove comment from the PR, in case it may confuse someone

**Comment by elad335** [comment]
dont remove comment from pr, it's better for future referencing of pr changes.

**Comment by plappermaul** [comment]
Added #6894 for further discussion on this issue. Maybe someone can test ...

**Comment by elad335** [comment]
Close issue?

**Comment by Xcedf** [comment]
The issue still happens without MLAA patch...

**Comment by xddxd** [comment]
Works with approximate xfloat without any patches.
![Screenshot_3](https://user-images.githubusercontent.com/1712979/83278959-0d3a7280-a1dd-11ea-9824-e7a44e9aa9c6.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4702816/RPCS3.log.gz)
