### ISSUE TITLE
Demon's Souls [BLES00932] issue with async shaders on AMD Navi GPU

### ISSUE THREAD

**Issue by Yuzhi1** [RPCS3/rpcs3#6618]
Crashes on v0.0.6-8574 and newer when compiling shaders with Radeon RX 5700 XT. 
If enabled "Disable Async Shader Compiler", works fine without crashes. 
v0.0.6-8570 and older don't have this trouble.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3639875/RPCS3.log.gz)

![ds_crash](https://user-images.githubusercontent.com/50018464/65390175-fb1f4f00-dd86-11e9-88a9-b8c4f1f928dc.png)

**Comment by kd-11** [comment]
Try enabling "debug output" option (in the debug setttings). You need to first install the vulkan SDK found [here.](https://vulkan.lunarg.com/sdk/home#windows) Attach the resulting rpcs3.log once the crash appears.

**Comment by Yuzhi1** [comment]
VulkanSDK-1.1.121.2 installed.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3640742/RPCS3.log)

**Comment by AniLeo** [comment]
Removed log showing pirated game. Only validation error that was in it was

```
·E 0:01:01.414242 {RSX [0x03a53fc]} RSX: ERROR: [Validation] Code 0 :  [ UNASSIGNED-CoreValidation-DrawState-QueryNotReset ] Object: 0x4572a260 (Type = 6) | vkCmdBeginQuery(): VkQueryPool 0x34f1700000000055[] and query 16383: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.
```

**Comment by kd-11** [comment]
That validation error is usually a sign that the driver already died or deadlocked. Retest with current master, I fixed an AMD driver deadlock recently.

**Comment by Yuzhi1** [comment]
AMD driver 19.11.1 fixed this problem, crashes gone.
I think was needed vulkan extensions that were added in driver.
https://www.amd.com/en/support/kb/release-notes/rn-rad-win-19-11-1
