### ISSUE TITLE
REORC Cannot Start a Mission [BLUS30750]

### ISSUE THREAD

**Issue by Myoko** [RPCS3/rpcs3#6621]
this game only can load on main menu! always stop when i start a mission.

log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3640481/RPCS3.log.gz)

**Comment by AniLeo** [comment]
```
·F 0:01:37.791747 {PPU[0x1000000] Thread (main_thread) [0x0017b584]} class std::runtime_error thrown: Null function
(in file F:\Project\rpcs32\rpcs3\Utilities\JIT.cpp:341)
```

Doesn't work with Recompilers. #5831
