### ISSUE TITLE
House of the Dead Overkill (BLES01326): Some fog effects do not appear to be blended correctly

### ISSUE THREAD

**Issue by Silanda** [RPCS3/rpcs3#6626]
As per the title, some fog effects (but not all) appear to be more opaque than they're supposed to be. 

![HOTD1](https://user-images.githubusercontent.com/4227434/65450746-c3bbab80-de35-11e9-9982-dd7cabd473ce.jpg)

For comparison, the same scene played on real hardware is shown in this Youtube video at around the 2:09:00 mark: https://www.youtube.com/watch?v=9KGprhahARU

Here's a screenshot from that video of the same scene:

![HOTD-Youtube](https://user-images.githubusercontent.com/4227434/65450972-32990480-de36-11e9-97e7-e23d9365be3a.jpg)

That video was taken using the US version of the game, but I have tested the European version on my PS3 and the translucent smoke looks the same as in the video and is much more transparent than it is rendered in RPCS3.

This was tested on Windows 10 using a Ryzen 7 3700X and Nvidia GTX 1080. The RPCS3 version tested was 0.0.7-8759-40fcd457.

I've attached my RPCS3 log and this is a link to an RSX capture of another part of the pictured scene where the fog is clearly visible: https://mega.nz/#!kCIhlYAA!H0zPsDMI6ZeIBizvzfoPmICh88wNVmCl3dgoHVCiCVw

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3643577/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
@Silanda  update?

**Comment by Silanda** [comment]
It still doesn't look right.

**Comment by jeremybris** [comment]
Is this fixed by #8367 ?

Here is the build:
https://dev.azure.com/nekotekina/nekotekina/_build/results?buildId=2155&view=artifacts&type=publishedArtifacts

**Comment by Silanda** [comment]
It is indeed.

**Comment by AniLeo** [comment]
Add before/after comparison to the PR when possible
