### ISSUE TITLE
Folklore BCES00050

### ISSUE THREAD

**Issue by AlexDCIT** [RPCS3/rpcs3#6629]
There is an old issue again when i must delete Cache folder. before every game launch. Please, help
rpcs3 0.0.7 8759

**Comment by AlexDCIT** [comment]
Why closed? I must add screenshots or what?

**Comment by AniLeo** [comment]
Because you're asking for help instead of submitting an issue report, you didn't include any log file nor any other informations that may be relevant, completely ignoring guidelines. Also, there are already a couple of issues discussing the need to wipe dev_hdd1 by default.
