### ISSUE TITLE
Demon's Souls [BLES00932] nv406e::semaphore_acquire has timed out.

### ISSUE THREAD

**Issue by Dani1977** [RPCS3/rpcs3#6632]
Hi,
since v0.0.7-8755 sometime when I start the game, I have this infinite error

nv406e::semaphore_acquire has timed out.

the error appear after loads Shaders . 

![immagine](https://user-images.githubusercontent.com/31347274/65519350-0e94fc00-dee6-11e9-8cec-cd3115bccfa0.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3647628/RPCS3.log.gz)

Regards.

**Comment by Silanda** [comment]
This has been happening to me with House of the Dead Overkill. Initially I thought there was a correlation between getting the error and having RTSS running, but now I think that was a false positive.

**Comment by triggerhappy187** [comment]
Same thing happens on MGS4.
