### ISSUE TITLE
Killzone 2 [BCES00081] - graphical issues

### ISSUE THREAD

**Issue by davewuk** [RPCS3/rpcs3#6641]
Many particle effects in Killzone 2 are not rendered correctly in RPCS3.

![Image1](https://user-images.githubusercontent.com/55807111/65627207-c4d01280-dfc6-11e9-9c94-d8c139b6a8b8.png)

Most noticeable is the smoke emitted from the gun when firing, though the smoke from flares and some other objects have the same issue.

There seem to be four separate issues:

1. The scaling is possibly incorrect, the smoke particles seem to be too large
2. The particles are not transparent enough
3. Objects obscured by the particles but still visible appear pixelated
4. The particles seem to have excessive bloom/brightness

Overall the game runs well and can be completed, though it is extremely hard to see enemies in many scenes because of the issue with the weapon smoke.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3654129/RPCS3.log.gz)

**Comment by kd-11** [comment]
Its one bug, not 4. The reason for it is known, but the hardware disagrees with the "easy fix". I get the feeling there is another issue for this?
