### ISSUE TITLE
get_system_time() slowed down by verify()

### ISSUE THREAD

**Issue by plappermaul** [RPCS3/rpcs3#6643]
This was found on a very weak setup with a scratch build from current master of github (as per the online documentation). Results might be not accurate because I guess I'm using a debug build. 

- Pentium Gold G6500 with UHD 630. 
- Bomberman Ultra displaying the welcome screen only

I noticed that get_system_time() is in the top CPU consumer of the PPU thread. A perf record of 10 seconds gives: 

![before](https://user-images.githubusercontent.com/10179087/65632904-11bde400-dfdb-11e9-8713-93dbbd51b88d.png)

It seems as if the verification function inside the procedure slows things down a bit. So I patched it.

```
diff --git a/rpcs3/Emu/Cell/lv2/sys_time.cpp b/rpcs3/Emu/Cell/lv2/sys_time.cpp
index dbf0c4c4c..d2a19a80d 100644
--- a/rpcs3/Emu/Cell/lv2/sys_time.cpp
+++ b/rpcs3/Emu/Cell/lv2/sys_time.cpp
@@ -158,7 +158,7 @@ u64 get_system_time()
                const u64 result = time / freq * 1000000ull + (time % freq) * 1000000ull / freq;
 #else
                struct timespec ts;
-               verify(HERE), ::clock_gettime(CLOCK_MONOTONIC, &ts) == 0;
+               ::clock_gettime(CLOCK_MONOTONIC, &ts);
 
                const u64 result = static_cast<u64>(ts.tv_sec) * 1000000ull + static_cast<u64>(ts.tv_nsec) / 1000u;
```
 

With the patch applied the usage percentage of the function is lower in perf.
![after](https://user-images.githubusercontent.com/10179087/65633222-ea1b4b80-dfdb-11e9-824d-d282f93c7676.png)

From the documentation of the kernel clock_gettime() can only give a result code != 0 if the clock type is not available. So it would be enough to check the availability once and omit the check inside the critical section.

**Comment by CookiePLMonster** [comment]
> Results might be not accurate because I guess I'm using a debug build.

Profiling in Debug is never feasible though? Something like this is probably perfectly fine, unless it also executes in Release and is noticeable on profiling results.
