### ISSUE TITLE
#6636 (Works) and #6638 (Does not Work, Missing VCRUNTIME140_1.dll Error)

### ISSUE THREAD

**Issue by jeremybris** [RPCS3/rpcs3#6646]
Build #6636 works, build #6638 or #6637 (whichever is first) and after, RPCS3 will not open. The error "VCRUNTIME140_1.dll was not found" (seen in the attached picture) appears.

![RPCS3 Runtime](https://user-images.githubusercontent.com/11889359/65719877-c0fac980-e074-11e9-828e-65b4dcbd6eb8.PNG)

I'm using Windows 10, and a standard computer. I try to install [VCRUNTIME140_1.dll from Microsoft](https://www.microsoft.com/en-us/download/details.aspx?id=52685), but when I do, it says I already have that installed.

Can anyone replicate this? I apologize if this issue is something I am doing wrong, otherwise I hope this can be helpful.

**Comment by RainbowCookie32** [comment]
Install the [Visual C++ 2019 Redistributable](https://aka.ms/vs/16/release/VC_redist.x64.exe) linked in [the quickstart guide](https://rpcs3.net/quickstart) and see if the error is still there. 

By the way, you should ask for support in our Discord server's help channel, not in Github's issues.

**Comment by jeremybris** [comment]
> Install the [Visual C++ 2019 Redistributable](https://aka.ms/vs/16/release/VC_redist.x64.exe) linked in [the quickstart guide](https://rpcs3.net/quickstart) and see if the error is still there.
> 
> By the way, you should ask for support in our Discord server's help channel, not in Github's issues.

That fixed, thanks. I will from now on. I am not too familiar with Discord so I came here first (I wasn't sure if it was a bug).

**Comment by jeremybris** [comment]
This can be closed, I believe.

**Comment by RainbowCookie32** [comment]
If it's fixed by it, then yes, it can be closed

**Comment by jeremybris** [comment]
> If it's fixed by it, then yes, it can be closed.
