### ISSUE TITLE
Fatal Errors randomly in Tales of Xillia 

### ISSUE THREAD

**Issue by FireFistYK** [RPCS3/rpcs3#6647]
So the game works fine and all but the game gets fatal error randomly and most of the times it keeps running until it forcibly crashes. I've tried all sorts of config combos and even tried reinstalling RPCS3 but to no success. 

Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz | 16 GB RAM | GTX 1060 MaxQ 

Log file: REMOVED

**Comment by AniLeo** [comment]
Removed link for log file showing a clearly pirated version and closing as invalid

Use your own clean dumps when submitting issues
