### ISSUE TITLE
evdev: Gamepad events not recognized by rpcs3

### ISSUE THREAD

**Issue by tomplast** [RPCS3/rpcs3#6649]
I bought a few cheap gamepad controllers with bluetooth support. The gamepad controller is  paired and I'm using it successfully in PCSX2 but in RPCS3 everything is detected as **RZ-** when I try to map the axis and buttons.

My build is made on commit 5ac631e03b5e3c8004b96224ab1f30e74ce3a413.

I'm also attaching output from evtest software where I tested all the axis and buttons.

[evtest.log](https://github.com/RPCS3/rpcs3/files/3661270/evtest.log)

**Comment by Leopard1907** [comment]
Can you try the solution on that issue report?

https://github.com/RPCS3/rpcs3/issues/4754

**Comment by tomplast** [comment]
Yes, "Filter noise" solved my issues. Is it possible to auto detect if there is noise so it's not needed to press the button manually?

The issue can be closed I guess. Thank you for the help!
