### ISSUE TITLE
Hyperdimension Neptunia [BLES01178] Graphics Regression after PR#6388

### ISSUE THREAD

**Issue by Silanda** [RPCS3/rpcs3#6650]
The old issue seems to have returned where the battle scenes are made up of dots. Similar to closed issue #3740

![Neptunia](https://user-images.githubusercontent.com/4227434/65768045-b5b4a600-e127-11e9-96c2-4ac407e2e1f9.jpg)

The graphics work fine in builds prior to PR #6388 as long as no upscaling is applied.
 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3662624/RPCS3.log.gz)

EDIT - I should probably add an RSX capture too: https://mega.nz/#!YXYXECiY!ghQQ1SlAiFJtXlVHkKgPmp3LR85n0tsa1cIuNbeKzeo

**Comment by kd-11** [comment]
Its one of those situations where the hw testing results conflicted with earlier fixes. I'll try and get this fixed properly asap.

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/6673

**Comment by Silanda** [comment]
I've only tested briefly, but #6673 does indeed seem to fix the game!

**Comment by Silanda** [comment]
I've played some more and it definitely seems fixed. Shall I close this now?

**Comment by dio-gh** [comment]
No need, it'll auto-close when that PR is merged.
