### ISSUE TITLE
Light color effect error with Write Color Buffer Last Of US

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#6665]
I have a light color glitches with any config  in The Last Of Us (Write Color Buffer must be enabled).
![Pic](https://user-images.githubusercontent.com/54372547/65818944-e9222e00-e216-11e9-8f77-72be22598d48.JPG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3665670/RPCS3.log.gz)

I7 9700K
Nvidia GTX 1080
16go RAM

**Comment by kd-11** [comment]
Actually you need read color buffers and read depth buffers for this game to work correctly. The remaining issues after that are not unique to the game and are well known.
