### ISSUE TITLE
Fatal Error Firmware Compiling Modules RPCS3 0.0.7-8802-14640694 Alpha

### ISSUE THREAD

**Issue by leondecastro1357** [RPCS3/rpcs3#6669]
Just downloaded the latest one and apparently this happened when installing the firmware:

![Capture1](https://user-images.githubusercontent.com/55934678/65824797-2c28e380-e2a1-11e9-8698-d8f6f9678a73.PNG)

Do I need to move to Windows 10? It says on the requirements "Windows 7". I installed all the necessary software requirements and yet the error persists.

So, I downloaded an older build: 7947 which worked without fatal errors.

**Comment by yxmline** [comment]
Delete all files under dev_flash, but do not delete the dev_flash folder
reinstall Firmware again

**Comment by AniLeo** [comment]
Windows 7 works just fine, just tested a clean installation and there's no issue. Could be something on your side, if you have the issue ask for support first instead.

This issue also doesn't contain any backtrace, so it's impossible to know what was wrong.
