### ISSUE TITLE
Sound offbeat pb in NIER 

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#6679]
I started to emulate Nier.The game seems to work fine but I found a pb with the voice during the intro (at the beginning) : 
Here's where you suppose to have it (but you have only the subtitles) : 
![Nier1](https://user-images.githubusercontent.com/54372547/65837454-ee0ade80-e2f7-11e9-9ede-a38244f8e2a3.JPG)
And here's when you can listening it : 
![Nier2](https://user-images.githubusercontent.com/54372547/65837474-1db9e680-e2f8-11e9-9fc4-aa05f7758e2a.JPG)

I tried to change config with PPU,SPU,...disabled sound buffer,changed sound drivers,..but nothing has changed it.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3667915/RPCS3.log.gz)

I7 9700K
Nvidia GTX 1080
Realtek and Nvidia sound drivers
16go RAM

**Comment by dio-gh** [comment]
I suppose you mean that the audio is running early? That is unfortunately a game issue, not much we can do about it as far as I know.

**Comment by Whatcookie** [comment]
Set the framelimit to 30FPS for correct game speed. The game will desync from the audio if you don't have a perfect 30 FPS.

**Comment by Pouncha** [comment]
@dio-gh yes,was an audio desync but thank to @Whatcookie : with the framelimit set to 30FPS, the audio is perfect !
Thank you very much for the help !
I close the topic
