### ISSUE TITLE
Uncharted 3 [BCAS25014] black screen

### ISSUE THREAD

**Issue by Myoko** [RPCS3/rpcs3#6682]
i can hear sound, but screen its black.
![2](https://user-images.githubusercontent.com/3013386/65851556-e72aad00-e385-11e9-8f70-258ab0dfcc12.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3668975/RPCS3.log.gz)

**Comment by mfdsrax2** [comment]
You need to enable 'Write Color Buffers' and 'Force CPU blit emulation'

**Comment by Myoko** [comment]
thanks!

**Comment by elad335** [comment]
It was not always used to be like this (needing wcb + cpu blit), please reopen.

**Comment by kd-11** [comment]
You don't. You only need Read Color Buffers and Read Depth Buffers for newer naughty dog engine.

**Comment by mfdsrax2** [comment]
I got broken visual on title and it freezes when starting a new game.

![155952](https://user-images.githubusercontent.com/13324717/66027606-df0d7180-e52d-11e9-9eeb-a0509fe8c67d.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3680042/RPCS3.log.gz)

**Comment by Keerthish17** [comment]
> I got broken visual on title and it freezes when starting a new game.
> 
> ![155952](https://user-images.githubusercontent.com/13324717/66027606-df0d7180-e52d-11e9-9eeb-a0509fe8c67d.png)
> 
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3680042/RPCS3.log.gz)

Hi bro does it fixed?
