### ISSUE TITLE
Metal Gear Solid 4 new report for crashes and fix (Intel processor)

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#6684]
I could make MGS 4 playable with some issues (I reach the second chapter then stop to make this report)
All issues I noticed will be reported here but you must keep that I use I7 9700 with a GTX 1080 (so,no ideas for ryzen).
I can't make a log for all issues,so please if you want it,tell me which issue you interested by.
I use MGS 4 NPUB31633 : it's the most runable game (BLES still have HDD pb)

So,first,the RPCS 3 config :
To make the make functionnal,I put this config : 
CPU:
PPU LLVM Recompiler
SPU LLVM  Recompiler
Load liblv2.sprx only
Enable SPU Loop Detection
SPU Cache
TSX Disable (make it enable will make the game crash in any config)

GPU:
Vulkan
Framelimit Off
Anisotropic filter Automatic
Anti-Aliasing Auto (MUST STAY AUTO COZ ON MAKE THE GAME CRASHES)
1280x720
Write Color Buffer OFF (MUST BE OFF COZ ON MAKE THE GAME CRASHES)
All other GPU options off

Audio
I must use OPENAL coz XAudio make the game crashes (no immediately)

Debug : 
Force CPU Blit enabled (It's strictly necessary ,epecially when the game compile shaders or new graphic area or detecting game CD even if I use NPUB game)

ISSUES : 
The game has some graphic effect glitches and bugs but the most important is it crashes after each PPU Compilation (when you change chapter) or sometime when you're entering new area (maybe due to SPU memory comilation) or start a new cinematic.
KEEP IN YOUR MIND THAT THE GAME MUST BE RESTART AFTER ANY CRASH WITHOUT CHANGE ANYTHING IN THE CONFIG

Some glitches and bug : 

FPS shutdown (game or cinematic)
![IMG_7794](https://user-images.githubusercontent.com/54372547/65880782-a71df700-e392-11e9-938e-e6dbc52e5503.JPG)

Shadow effects
![IMG_7804](https://user-images.githubusercontent.com/54372547/65881316-83a77c00-e393-11e9-8319-5a621348b0a8.JPG)

Icons glitches
![IMG_7797](https://user-images.githubusercontent.com/54372547/65881451-b6517480-e393-11e9-970b-b0634d6ea161.JPG)
![IMG_7798](https://user-images.githubusercontent.com/54372547/65881461-b94c6500-e393-11e9-99b3-6de7afd38324.JPG)

Right part of the screen color and display effect (check each color part of the robot or the Snake's mustache and Colonel's scares to understand)
![IMG_7796](https://user-images.githubusercontent.com/54372547/65881635-f9abe300-e393-11e9-861d-f4b0c665ebc1.JPG)
![IMG_7799](https://user-images.githubusercontent.com/54372547/65881665-029cb480-e394-11e9-9026-7f933975ed0e.JPG)
![IMG_7800](https://user-images.githubusercontent.com/54372547/65881671-06303b80-e394-11e9-9ae7-78af1acb7c93.JPG)
![IMG_7801](https://user-images.githubusercontent.com/54372547/65881678-092b2c00-e394-11e9-8cbb-b0e306d10264.JPG)
![IMG_7802](https://user-images.githubusercontent.com/54372547/65881685-0b8d8600-e394-11e9-9f87-4248102a4661.JPG)

Hope it will help

**Comment by rajkosto** [comment]
the furthest ive gotten on 5GHz 7700K was with Preferred SPU threads 3, LLVM recompiler for both, no accurate xfloat, TSX on, GPU is Vulkan with 100% res, no framelimit, no checkboxes, OpenAL audio with Time stretching enabled, and in Advanced set Maximum Number of SPURS threads to 3 and VBlank frequency to 240hz to try and sustain highest possible FPS (game desyncs and hangs when FPS drops too low, which often happens during shader/SPU compilation)
