### ISSUE TITLE
Silent Hill Downpour[BLUS30565] Stop in the shower

### ISSUE THREAD

**Issue by Myoko** [RPCS3/rpcs3#6686]
everytime i hit that fat, it always stop in this place
![1](https://user-images.githubusercontent.com/3013386/65957720-23dacf00-e480-11e9-9fb2-8f270f8011cf.jpg)
log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3675892/RPCS3.log.gz)

**Comment by psennermann** [comment]
I tried Yesterday with 0.0.7-8817 and didn't encounter this problem...from the log seems that the only differences are that I use firmware 4.83, Nvidia Driver 436.15 and Enable thread scheduler: true but there might be something else that I've misssed…

My spec:

Win10
gtx1060 3gb
Intel i7700

**Comment by psennermann** [comment]
I've just noticed that you use frame limiter to 30...I suggest to try to set it to off

**Comment by Myoko** [comment]
thank you! i will retest again.

**Comment by Myoko** [comment]
happen in the last hit
![2](https://user-images.githubusercontent.com/3013386/66092047-e2037300-e5bc-11e9-89b6-0832747d3f1a.jpg)
![3](https://user-images.githubusercontent.com/3013386/66092049-e596fa00-e5bc-11e9-9e90-72a2af7a6910.jpg)

**Comment by psennermann** [comment]
Strange...I don't have a clue...you might want to try to disable TSX, use ASMJIT recompiler, an older Nvidia Driver and so on.
I also use resolution scaler 150% and resolution scale treshold 512x512

**Comment by Myoko** [comment]
i found problem the problem is rpcs3 cannot support update for this game
1.00 its normal 1.01 always happen
![1](https://user-images.githubusercontent.com/3013386/67065067-6d752a80-f19f-11e9-8c23-7e58f99d2d4e.jpg)

**Comment by elad335** [comment]
So its an issue with 1.01 version, reopen.

**Comment by Myoko** [comment]
i just delete all file and re-install pkg files its normal. 
maybe!! i broken something before
