### ISSUE TITLE
DAYTONA USA [NPUB30493] glitchy graphics on opengl

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6687]
doesnt matter what PPU Decoder or SPU decoder or any other settings i use the graphics keep flickering and glitching
another opengl problem maybe ??
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3676112/RPCS3.log.gz)

**Comment by Andryshik345** [comment]
Can you post screenshots or video of gameplay?

**Comment by incognitoh** [comment]
seems to work ok with vk and interpreter (but kind of slow) .  the game has major flickering when using PPU LLVM with both ogl and vk renderers.  this has always been an issue and still not fixed as referenced here #5831

ppu interpreter + vk:
![jpr1](https://user-images.githubusercontent.com/39333810/65972979-9cb63880-e438-11e9-9d2f-e217df35f698.JPG)

**Comment by elad335** [comment]
So it is a duplicated issue.

**Comment by kd-11** [comment]
OpenGL + interpreter works fine btw. I think the flickering is caused when performance is not optimal. And no, its not an AMD issue since I'm on AMD too.
![image](https://user-images.githubusercontent.com/15904127/66202313-1571fa80-e6ae-11e9-951f-7d3bb9cccdd8.png)

**Comment by kd-11** [comment]
Closed since the old bug with llvm is already known.
