### ISSUE TITLE
Regression: Retro/Grade messed up graphics on Vulkan and OpenGL (#6357)

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6688]
have tried differant settings and still the graphics are messed up
most of the time it is a black screen with the music and sound fx 
![retro](https://user-images.githubusercontent.com/2696404/65962502-6a81f680-e48b-11e9-81dc-971121ff7ba6.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3676188/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Needs an RSX capture

**Comment by benderscruffy** [comment]
when the opengl driver has been fixed

**Comment by benderscruffy** [comment]
here is a couple of RSX captures
https://mega.nz/#!lroFTA6C!bbwmTvL7BcW0I96VNQZKbaZbc31boKdg9aTK0cizE-g

**Comment by benderscruffy** [comment]
still happens in the latest master
here is a few renderdocs
https://mega.nz/file/ojJ2iSxb#LBY3lxgmra9QUsfkCJWNOxJlHWzqxZJgKe9OGjhfbqc

**Comment by AniLeo** [comment]
@kd-11 for triaging what kind of graphic issue is this

**Comment by Asinin3** [comment]
Still an issue, graphics just output garbage on VK and OGL. tried multiple settings and nothing helped. Relaunching game can output different graphics so don't mislead yourself into thinking one setting helped.
![image](https://user-images.githubusercontent.com/15137035/133440700-2ca987f7-f484-4fd2-811e-574eace7e787.png)
No RSX capture because it kept crashing e.g with:
```F SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderTargets.h:81[:10], in function as_rtt)```

**Comment by nitroos-ai** [comment]
It all began here #6357

**Comment by kd-11** [comment]
> Still an issue, graphics just output garbage on VK and OGL. tried multiple settings and nothing helped. Relaunching game can output different graphics so don't mislead yourself into thinking one setting helped. ![image](https://user-images.githubusercontent.com/15137035/133440700-2ca987f7-f484-4fd2-811e-574eace7e787.png) No RSX capture because it kept crashing e.g with:
> 
> ```
> (in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderTargets.h:81[:10], in function as_rtt)```
> ```

This is correct output, just needs the tiled DMA patches I have on my local. Hopefully I'll have them cleaned up before too long.

**Comment by Triticum0** [comment]
Note: similar issue happens with mercury hg when RCB is enabled. so tited DMA patches will be the needed for that game to be moved to playable.
https://imgur.com/a/vqk4OLr

**Comment by benderscruffy** [comment]
have upgraded to a new computer so can not test it with old computer anymore

**Comment by Triticum0** [comment]
@AniLeo This needs to be reopened as it is the same #6609

**Comment by kd-11** [comment]
I checked this with RSX detiling enabled (and CPU blit) and the logos and menu now are mostly correct. However, the detiling is not kicking in for some situations when it absolutely should, the same issue observed in some games like NFS Rivals.

**Comment by kd-11** [comment]
Found it. Unfortunately it's messy. Blit engine writes to texture cache surfaces then RCB ignores them when loading memory leading to the loss (CPU blit off). When CPU blit is ON, the same fails because the CPU path does not support tiling.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/14934 when using CPU blit. The full fix for GPU-only blit is to unify texture and surface cache needs months of work and is a known long-term goal.
