### ISSUE TITLE
Folklore[BCUS98147]

### ISSUE THREAD

**Issue by VG3M** [RPCS3/rpcs3#6691]
I keep encountering the same issue with Folklore and a black screen during boot. The FPS is ~30 and nothing occurs. I am not sure if its just an issue with the US version or what, looking for a fix to this. 

LOG:
U {PPU[0x1000000] Thread (main_thread) [0x00580660]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd0010904, option=*0x0, waitForEvent=0)
U {PPU[0x1000000] Thread (main_thread) [0x005802d0]} cellGame TODO: cellDiscGameRegisterDiscChangeCallback(funcEject=*0x5562b8, funcInsert=*0x5562c0)
E {PPU[0x1000000] Thread (main_thread) [0x008f5fc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/BCUS98147/cg” [1]
E {PPU[0x1000000] Thread (main_thread) [0x008f5fc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/BCUS98147/cg” [2]
E {PPU[0x1000000] Thread (main_thread) [0x008f5fc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/cache/BCUS98147/cg” [3]

**Comment by AniLeo** [comment]
Missing log file

**Comment by VG3M** [comment]
@AniLeo where do i pull the log file from? The one I have found is way too big to send here

**Comment by VG3M** [comment]
https://drive.google.com/file/d/1gO-ucpC-w3b6xbVeNAGHEtIKvoGi1P4r/view?usp=sharing

**Comment by AniLeo** [comment]
Removed log showing pirated game and closing as invalid.
