### ISSUE TITLE
VCRUNTIME140_1.dll gone despite having all required software

### ISSUE THREAD

**Issue by PItlosTails** [RPCS3/rpcs3#6694]
Thought i'd report this as this may be some sort of bug, as my specs are far better than that which is required and the download is fresh. my firewall and anti-virus is turned off theres no logs of this as far as im aware. i'd also like to tell you that your discord invite link is expired.

**Comment by dio-gh** [comment]
As for the .dll issue, you'll have to update to vc redist 2019: https://aka.ms/vs/16/release/VC_redist.x64.exe

And no, the discord invite link isn't expired, no idea where you got an expired link from. The one on our website works just fine.

Lastly, this is not a support forum, but a bug tracker. If you have issues setting up a game or the emu, ask on our Discord first. (or heck, on our subreddit at /r/rpcs3) Knowing that you couldnt find our Discord does explain why you didnt though, but then again, the link on our site works fine.
