### ISSUE TITLE
AMD RADEON HD 6800: No vulkan device was created

### ISSUE THREAD

**Issue by keyhab** [RPCS3/rpcs3#6699]
![image](https://user-images.githubusercontent.com/56144872/66179388-29324800-e63f-11e9-93e0-03db3c56b3d2.png)

Hey guys, sorry for bothering.
I've read some  closed posts about that same issue but couldn't resolve it myself.
I've tried to use Vulkan for some time in Dolphin and rpcs3 without success.

I already tried the REG_DWORD solution, but I actually couldn't find the "nv-vk64.json" file in the System32 folder. I already downloaded and instaled the [latest Runtime and SDK](https://vulkan.lunarg.com/sdk/home#windows), but when I run vulkaninfo.exe it shows only this message:

> c:\vulkansdkbuild\workspace\khronos-tools\repo\vulkaninfo\vulkaninfo.c:708: failed with VK_ERROR_INITIALIZATION_FAILED

Did I skip any steps regarding Vulkan API installation or something? I just did the things I mentioned above.

**Comment by RainbowCookie32** [comment]
Your GPU doesn't support Vulkan according to AMD's site: https://www.amd.com/en/technologies/vulkan

Please use [our Discord server](https://discord.me/RPCS3) to ask for support instead of GitHub's issues.

**Comment by keyhab** [comment]
@RainbowCookie32 I see it. Thank you.
