### ISSUE TITLE
OutRun™ Online Arcade [NPEB00073] dark shadow on road on opengl

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6701]
using opengl
during gameplay there is a dark shadow across the road
ticking WCB or SRM does not change it
![outrun](https://user-images.githubusercontent.com/2696404/66187187-cc727400-e6b6-11e9-88ba-def8b8a10f08.PNG)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3689296/RPCS3.zip)
[NPEB00073_20191004144641_capture.zip](https://github.com/RPCS3/rpcs3/files/3689298/NPEB00073_20191004144641_capture.zip)

**Comment by kd-11** [comment]
This seems to be a driver issue with old AMD drivers. I would suggest giving linux+mesa(r600g) a try for your GPU.
For reference, this game works fine on RX470
![image](https://user-images.githubusercontent.com/15904127/66198676-97a9f100-e6a5-11e9-8407-aa593a17cda0.png)

**Comment by benderscruffy** [comment]
ok thanks for that
i have now got an amd Radeon RX580
