### ISSUE TITLE
MGS4 disc versions [BLES00246] will always reinstall Chapter data on Windows

### ISSUE THREAD

**Issue by rajkosto** [RPCS3/rpcs3#6706]
RPCS3 v0.0.7-8820-4a19a2dd Alpha

Happens with both Version 1.0 or Version 2.0, original disc release or anniversary edition, regardless if install type is Cumulative or Chapter, Windows RPCS3 will ignore currently installed Chapter data and always ask to reinstall it when you load a save/start a new game unless you have installed the data during that RPCS3 game session already. Linux RPCS3 uses existing installed Chapter data properly. Attached are logs from both linux (no install needed) and windows (install always needed) runs with the same configs and dev_hdd0 folders used.

[RPCS3_linux.log](https://github.com/RPCS3/rpcs3/files/3691652/RPCS3_linux.log)
[RPCS3_windows.log](https://github.com/RPCS3/rpcs3/files/3691704/RPCS3_windows.log)

The big difference seems to be that on windows it does 

```
·W 0:00:35.420511 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d30ec0]} sys_fs: 0xc0000006: 0x20, 0x10, 0x18, “/dev_hdd0/game/BLES00246/USRDIR/stage01.dat”, 0x0, 0x80010003, 0x0
·W 0:00:35.420512 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d32090]} sys_fs: sys_fs_open(path=“/dev_hdd0/game/BLES00246/USRDIR/stage01.dat”, flags=0, fd=*0xd0032360, mode=0, arg=*0x0, size=0x0)
·W 0:00:35.420547 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d31380]} sys_fs: sys_fs_fstat(fd=209, sb=*0xd0032880)
·W 0:00:35.420557 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d30ec0]} sys_fs: 0xc0000006: 0x20, 0x10, 0x18, “/dev_hdd0/game/BLES00246/USRDIR/stage01.dat”, 0x0, 0x80010003, 0x0
·W 0:00:35.420558 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d31f44]} sys_fs: sys_fs_unlink(path=“/dev_hdd0/game/BLES00246/USRDIR/stage01.dat”)
·! 0:00:35.457583 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d31f44]} sys_fs: sys_fs_unlink(): file “/dev_hdd0/game/BLES00246/USRDIR/stage01.dat” deleted
·W 0:00:35.457595 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d30ec0]} sys_fs: 0xc0000006: 0x20, 0x10, 0x18, “/dev_hdd0/game/BLES00246/USRDIR/stage02.dat”, 0x0, 0x80010003, 0x0
```

while on linux it doesnt unlink
```
·W 0:00:33.288617 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d30ec0]} sys_fs: 0xc0000006: 0x20, 0x10, 0x18, “/dev_hdd0/game/BLES00246/USRDIR/stage01.dat”, 0x0, 0x80010003, 0x0
·W 0:00:33.288619 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d32090]} sys_fs: sys_fs_open(path=“/dev_hdd0/game/BLES00246/USRDIR/stage01.dat”, flags=0, fd=*0xd0032360, mode=0, arg=*0x0, size=0x0)
·W 0:00:33.288706 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d31380]} sys_fs: sys_fs_fstat(fd=209, sb=*0xd0032880)
·W 0:00:33.288732 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d30ec0]} sys_fs: 0xc0000006: 0x20, 0x10, 0x18, “/dev_hdd0/game/BLES00246/USRDIR/stage01.dat”, 0x0, 0x80010003, 0x0
·W 0:00:33.288734 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d32090]} sys_fs: sys_fs_open(path=“/dev_hdd0/game/BLES00246/USRDIR/stage01.dat”, flags=0, fd=*0xd0032200, mode=0, arg=*0x0, size=0x0)
·W 0:00:33.288816 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d31380]} sys_fs: sys_fs_fstat(fd=210, sb=*0x482698)
·W 0:00:33.288830 {PPU[0x1000001] Thread (MGS4 MAIN) [0x00d30ec0]} sys_fs: 0xc0000006: 0x20, 0x10, 0x18, “/dev_hdd0/game/BLES00246/USRDIR/stage02.dat”, 0x0, 0x80010003, 0x0
```

when the game makes the stage01.dat.ctmp file on either linux or windows, it makes it with filesize 1199763456 bytes even though the size of the file on bluray is 879255552 bytes . So once the file is written to, all the bytes after 879255552 remain zero. Even with a Cumulative install, all the stage files installed get made with a size of 1199763456 (the size of the largest stageXX.dat file on bluray) and not their correct size, but this seems to be inconsequential.

The next time the game is booted, the fstat check passes on linux, but not on windows ? To make the fstat check pass on windows, the file mtime should be exactly the same as the bluray file's, which doesnt happen if the game installs the file. However if the file is copied manually, it works. Somehow, on linux, the mtime check is less stringent and passes if the game installs the file.

**Comment by rajkosto** [comment]
I've fixed this in PR https://github.com/RPCS3/rpcs3/pull/6708

**Comment by HHCHunter** [comment]
I think this is actually a regression, I know I had this working at one point without having to constantly re-install data per chapter once I'd changed to Cumulative.

**Comment by rajkosto** [comment]
It's probably because you manually copied files. That works if the file you copied has the same LastWrite and Changed timestamps on windows.

**Comment by rajkosto** [comment]
PR Merged and mtime issue fixed with https://github.com/RPCS3/rpcs3/commit/297e3c5996d97ede5b9897720251160f752f1cb1
