### ISSUE TITLE
Gran Turismo 6 (BCES01893) Updates made Black screen

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#6711]
Gran Turismo 6 works (with screen flickering) when you launch it from the first version (the one you get on the original game disc).
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3693339/RPCS3.log.gz)

But after made all updates ('til 01.22),the same game with the same settings make a black screen with only HUD during game
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3693341/RPCS3.log.gz)

Any settings change doesn't remove the issue : the screen stay black with only the HUD on display.

I7 9700K
GTX 1080
16go RAM

**Comment by arabek** [comment]
Past Patch Version 1.05 it's expected.

**Comment by kd-11** [comment]
From the time I spent with this one, you need to enable full RSX<->Cell synchronization with the following options:
- Write Color Buffers
- Write Depth Buffer
- Read Color Buffers
- Read Depth Buffers
From there you can try disabling the options to gain some performance back (I believe it can work without the depth ones) but hilariously you get tearing. Not GPU->Display tearing, but tearing from the virtual emulated GPU. If nothing else it speaks to improved accuracy and I found it rather amusing.

**Comment by Pouncha** [comment]
@kd-11 
I tried different combinations.The best results I got was with Read Color Buffers & Read Depth Buffers (any other graphic or system options doesn't get better results).
Like that,and PPU & SPU as LLVM,safe,SPU cache and TSX,I could get all the graphics back but I still have flickering when you start the race and tearing during the race).
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3693752/RPCS3.log.gz)

I could stop tearing by changing the SPU option as Interpreter (Fast) setting.
This stop tearing during race but I still have flickering when you start the race and the game is too slow (& you can get crash and sound cut at any times).
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3693753/RPCS3.log.gz)

**Comment by kd-11** [comment]
In that case close this issue as the stated problem is fixed with configuration options.
