### ISSUE TITLE
Multiple evdev dualshock 3

### ISSUE THREAD

**Issue by lsarakinos** [RPCS3/rpcs3#6712]
Hello everyone!
Under ubuntu 18.04 I am facing the following issue:
When multiple same pads are added (2 x dualshock3 setup) only the latest added is configurable (no matter what you select under devices see below) and it is working for all players. 

Thank you
________________________________________________
~/.config/rpcs3/config_input.yml
Player 1 Input:
  Handler: Evdev
  Device: Sony PLAYSTATION(R)3 Controller
  Profile: Default Profile
Player 2 Input:
  Handler: Evdev
  Device: 2. Sony PLAYSTATION(R)3 Controller
  Profile: Default Profile
____________________________________________
evtest results
Available devices:
/dev/input/event13:     Sony PLAYSTATION(R)3 Controller Motion Sensors
/dev/input/event14:     Sony PLAYSTATION(R)3 Controller
/dev/input/event15:     Sony PLAYSTATION(R)3 Controller Motion Sensors
/dev/input/event16:     Sony PLAYSTATION(R)3 Controller
_____________________________________________
rpcs3 Latest Build: v0.0.7-8829

**Comment by Megamouse** [comment]
Did this work before 0.0.7-8769 ?

**Comment by lsarakinos** [comment]
Hello Megamouse
No luck even with 0.0.7-8768 or the older v0.0.7-8623!!
?
Thanks

**Comment by Shoegzer** [comment]
I can confirm - and this is also an issue with dualshock 4 controllers.  We struggled for about 30 minutes yesterday trying to get multiple pads working but it just doesn't anymore.  In case it helps, I don't believe this was an issue on builds earlier than 81a110f3469a54e843e72fc314731d726d15213b, though I haven't had time to bisect from db7042b986abe7a588aa306a31d84fd976c65951, which is the latest build tested that has the above problem.

Also, attempting to save controller configuration in the middle of a game will often crash RPCS3 entirely, though it seems that this behavior is linked to the above problem.

Test system is linux mint 19.2 with kernel 5, locally-compiled with gcc-9.1.0.

**Comment by Megamouse** [comment]
Please retest

**Comment by Shoegzer** [comment]
Thanks @Megamouse .. indeed this seems to fix the core issue.  

There's another issue where the p1 controller (default blue color on a ds4 pad) is reassigned from "Wireless Controller" to "2. Wireless Controller" when you plug in a second pad (it should stay the same).  I'm guessing that's an issue with evdev itself and not rpcs3 though, and even if it were that would be separate from the one here.  I'm okay with this one being closed.
