### ISSUE TITLE
Having no Audio Output Source available always results in a "FATAL ERROR" when trying to launch any game

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#6714]
Unplug/Disconnect/Disable all your audio output sources in the Windows 10 Sound Control Panel and you will always get a FATAL ERROR when launching any game with RPCS3.

**Comment by lextra2** [comment]
Here are 2 videos demonstrating the behavior
[With LPCM (no crash)](https://drive.google.com/open?id=1aKJLNN8ivIypiQZQSiN1BYqPK-5sQ6EO)
[Without LPCM (crash)](https://drive.google.com/open?id=12Wb-INAXZjQIls0aWsTPKTixzdwW98db)

**Comment by clienthax** [comment]
@lextra2 What is your default sound device set to ?

**Comment by lextra2** [comment]
> @lextra2 What is your default sound device set to ?

None when I do get the error. I have literally no audio source connected to my PC in that case.

**Comment by clienthax** [comment]
Right.. well for the sound to work you are going to need a sound device :)

**Comment by lextra2** [comment]
Correct. But it shouldn't result in a Fatal Error

**Comment by lextra2** [comment]
> Or set audio to null
