### ISSUE TITLE
Far Cry 4 [BLUS31420] texture bug: broken lighting and NPC skin black

### ISSUE THREAD

**Issue by stan0danny** [RPCS3/rpcs3#6718]
i was play far cry 4 ingame rpcs3 ( v0.0.7-8834 ) working and far cry 4 menu new game and video fine, 
vulkan fine, i see Vulkan ( fary cry 4  texture problem )  is light, black and texture face black skin  ( screenshot ) 

![Screenshot (14)](https://user-images.githubusercontent.com/41484098/66275777-a7d3f300-e894-11e9-9c78-2514f6913399.png)

![Screenshot (15)](https://user-images.githubusercontent.com/41484098/66275782-af939780-e894-11e9-9a0f-56223a2d7451.png)

![Screenshot (17)](https://user-images.githubusercontent.com/41484098/66298948-4004c300-e8fb-11e9-962e-8f4af29f4b64.png)

![Screenshot (18)](https://user-images.githubusercontent.com/41484098/66305766-b2c86b00-e908-11e9-9f90-815be62295bf.png)

**Comment by AniLeo** [comment]
Log file shows pirated game, removed log. Needs RSX captures and a log file from a clean copy.

**Comment by stan0danny** [comment]
i was play fry cry 4 rpcs3 (v0.0.7-8939 Alpha) : Vulkan fine, it's freeze 

![Screenshot (20)](https://user-images.githubusercontent.com/41484098/67145928-9a543b00-f28e-11e9-8ac1-d24806c74f85.png)

![Screenshot (21)](https://user-images.githubusercontent.com/41484098/67145930-9f18ef00-f28e-11e9-8c3a-124364a27ee5.png)

look log file done --- > [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3746720/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Removed reposted log file from pirated copy, again.
Closing as invalid until there's a log from a clean copy.

**Comment by stan0danny** [comment]
I'm sorry,  I'm understood
