### ISSUE TITLE
[Vulkan] TTT2 NPEB01140 crashes in intro bot fight with write color buffers and nVidia 1050

### ISSUE THREAD

**Issue by raveskirza** [RPCS3/rpcs3#6719]
Tekken Tag Tournament 2 seems to crash on Vulkan with nVidia 1050 when wcb is enabled. This is a recent phenomenon probably  started in the last 2 months.

![image](https://user-images.githubusercontent.com/28158623/66305321-b7971a00-e91c-11e9-9b10-bb24c849d5e3.png)

RPCS3 Logs:

nVidia WCB on - Crash
[RPCS3_nv_wcb_on.log.gz](https://github.com/RPCS3/rpcs3/files/3696865/RPCS3_nv_wcb_on.log.gz)

Intel WCB on - No Crash
[RPCS3_intel_wcb_on.log.gz](https://github.com/RPCS3/rpcs3/files/3696911/RPCS3_intel_wcb_on.log.gz)

nvidia WCB off - No Crash
[RPCS3_nv_wcb_off.log.gz](https://github.com/RPCS3/rpcs3/files/3696927/RPCS3_nv_wcb_off.log.gz)

Tried in a different system with the same nVidia Diver but a different card 940MX. It doesnt crash with wcb on
[RPCS3_nv_940mx_wcb_on.log.gz](https://github.com/RPCS3/rpcs3/files/3697114/RPCS3_nv_940mx_wcb_on.log.gz)

Edit 1: As of Master 0.0.7-8909, the error is now handled differently(happens only with wcb on)
`
·W 0:04:32.485051 {PPU[0x1000000] Thread (main_thread) [0x0038ed4c]} RSX: Cache miss at address 0xC1200B40. This is gonna hurt...
·F 0:04:32.485123 {PPU[0x1000000] Thread (main_thread) [0x0038ed4c]} RSX: g_access_violation_handler(0xc1200000, 1): Access violation - no RTTI data!
`

Edit 2: As of Master v0.0.7-9029-479d92d0. The error message has again changed to a different message

`·W 2:14:25.900007 {PPU[0x1000000] Thread (main_thread) [0x0038ed4c]} RSX: Cache miss at address 0xC1584A00. This is gonna hurt...
·F 2:14:25.900104 {PPU[0x1000000] Thread (main_thread) [0x0038ed4c]} RSX: g_access_violation_handler(0xc1584000, 1): Verification failed (0000000000000000): 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKRenderTargets.h:544)`

**Comment by Aurez** [comment]
I confirm thats a regression when using WCB+Vulcan (I have a GTX970) 
- "Bandai Namco Games" start logo (white screen) is flashing
- RPCS3 is crashing after demo play
- RPCS3 is crahing at the end of a match
...
These problems seems to be appeared from PR #6357

**Comment by kd-11** [comment]
Need more info on how this is happening and how to reproduce. Also check if current master is still affected. OP mentions "intro bot fight", what does this mean? @Aurez mentions demo play as well. Do you mean the game plays itself or do you mean there is some intro cinematic (video) that triggers the crash?

**Comment by Aurez** [comment]
Thanks to work on this :)
At start the "Bandai Namco Games" logo is flashing (wasn't before PR#6357)
If you let the game running it crashes right after the 1st demo play (when the game should restart and display again the "Bandai Namco Games" logo and it didn't crash before PR#6357)

I will try to send a log but I just tried and it seems there is a new bug with this game:
most of the time I now get this and it runs at 1fps :)  
**E {RSX [0x0310010]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300600**
![Image1](https://user-images.githubusercontent.com/45921529/73175153-cc84fc80-4109-11ea-91cf-60da725570ae.jpg)

**Comment by Aurez** [comment]
here is the log and a screen of the crash:
![Image2](https://user-images.githubusercontent.com/45921529/73175577-d22f1200-410a-11ea-9a39-ec9815b40500.jpg)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4117143/RPCS3.zip)

**Comment by raveskirza** [comment]
For me it is a different error message with nVidia 1050

·F 0:02:43.244377 {PPU[0x1000000] Thread (main_thread) [0x0038ed4c]} RSX: g_access_violation_handler(0xc1200000, 1): Access violation - no RTTI data!

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4126022/RPCS3.log.gz)

**Steps to reproduce:**

Dont Press Start after reaching this screen. The game will automatically load the bots to fight
![image](https://user-images.githubusercontent.com/28158623/73325188-8481e900-4273-11ea-9b0b-9d02aff32eac.png)

When the bots start fighting. Press start
![image](https://user-images.githubusercontent.com/28158623/73325219-a8452f00-4273-11ea-988c-235c9908d1c5.png)

The game crashes when wcb is enabled
![image](https://user-images.githubusercontent.com/28158623/73325295-f823f600-4273-11ea-85a5-3e74bd66d35e.png)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/7353.
The 'flickering logo' thing only happens on first run when things are still getting compiled in the background. The crash on missing RTTI data however is a legit bug caused by some optimizations in surface cache not being reflected in texture cache.

**Comment by Aurez** [comment]
Good work: Crash fixed for me  :)
The 'flickering logo' is still present for me each time I start the game (but it doesn't when the game demo loops)

**Comment by kd-11** [comment]
Flickering is not present on either AMD or NVIDIA for me, but I did see it during the first run when everything was compiling for the first time. Resolution scaling and MSAA don't seem to affect it either. In fact, no settings could make it reappear no matter what I tried.

**Comment by Aurez** [comment]
strange, I have the exact opposit result : it doesn't happen when I start the game just after clearing my cache but always the next times.

**Comment by SmitheeGuy** [comment]
Fixes the crash on Dante's Inferno when WCB is enabled that I reported in #7308
