### ISSUE TITLE
Having no Audio Output Source available always results in a "FATAL ERROR" when trying to launch any game

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#6723]
Disconnect / Disable every audio output sources in the Windows 10 Sound Control Panel and you will always get a FATAL ERROR when launching any game with RPCS3.

Edit: Re-opened the issue (miss-click-closed the old thread #6714 )

As suggested by @clienthax manually setting the audio output to "disabled" inside RPCS3s settings fixed this fatal error. But in reality I'd like this to occur automatically.

Imo RPCS3 should check if there is any valid audio output option available upon start up. And if there is none it should default to "Null" and grey out the "Audio Out" tab in RPCS3s audio settings. And there could also be a seperated dedicated option that lets you choose what device the audio should play from (in cases where someone has more than 1 audio device connected to the pc, like lets say a TV and some Headphones).

**Comment by AniLeo** [comment]
Fixed by #7511
