### ISSUE TITLE
[BLUS30750]REORC Zombie can't broken the door!

### ISSUE THREAD

**Issue by Myoko** [RPCS3/rpcs3#6724]
always trapped in here, zombie cant broken that door
![REORC](https://user-images.githubusercontent.com/3013386/66371359-82023780-e9d5-11e9-9de1-c8d66410a170.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3700954/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
@Myoko Did Zambie come out now?
