### ISSUE TITLE
WRC 2 [BLES01442] VkTextureCache  errors cause game freeze

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#6725]
After playing a race or 2, the textures of the cars gets screwed up and then you'll hit a vk texture cache error soon after.

Note: This game requires WCB + Strict for correct rendering. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3700959/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by legend800** [comment]
Appears fixed.

**Comment by segbed** [comment]
still same issue based on description. When I selecting a car for next race part of textures on the car are black.

**Comment by segbed** [comment]
I've tried both options. Same result. OK will new isse.
