### ISSUE TITLE
Ni no Kuni NPUB30932 appears to have a regression on or about 8559/8561

### ISSUE THREAD

**Issue by klepp0906** [RPCS3/rpcs3#6747]
So i had played NNK with RPCS3 over a span of several months and made it to the end.   A good ole fashion bout of adulting kept me away for a few months, and I updated NNK and its now booting to a black screen.

All other titles I own are fine.  I troubleshot(troubleshooted?) a bit backwards as I first removed all caches, and reinstalled the game and changed every setting under the sun both relative to my gpu, and in rpcs3.

low and behold - simply rolling back RPCS3 was the only thing that solved the issue but I had to go back quite far.   The last version that would boot the game is #6376 0.0.6-8546.   Even with that version, the boot is tremendously slower than it used to be.

if I hop back another month or so from that point, it boots fast n easy like the rest of the titles.  Boot time isnt what concerns me, its the not booting at all part.  

#6381 0.0.6-8559 has a fatal error on startup so #6385 0.0.6-8561 is the first version that works but wont boot NNK to anything but a black screen.

Here is a link to a log from the last booting build 
[RPCS3 8546 booting.log.gz](https://github.com/RPCS3/rpcs3/files/3719063/RPCS3.8546.booting.log.gz)

and from the first non booting build
[RPCS3 8561 no booting.log.gz](https://github.com/RPCS3/rpcs3/files/3719064/RPCS3.8561.no.booting.log.gz)

hopefully some of this is helpful

**Comment by Asinin3** [comment]
The whole booting to a black screen thing has been there for years for me and used to seem to only happen when i already had a shader cache and clearing the shader cache would fix it. However more recently cleaning the cache no longer seemed to fix it and it was just random and with enough reboots i could get past it. How many times did you try?

**Comment by klepp0906** [comment]
ive been at this ALL day. ~6 hours into trying to get past it without rolling back to a 2 month old build that boots every single time.  Exhausted every avenue i could think of before coming here.

oddly enough this was never an issue prior with NNK or anything else.  Even now is only a NNK issue.  Of course I have a reaaally small sample size to draw on.  (6 games or so) lol.

Hopefully that stuff gives them something to go on.

**Comment by Asinin3** [comment]
Working fine here. 
![rpcs3_i3oEnJMyn1](https://user-images.githubusercontent.com/15137035/66675547-0e01b100-ecad-11e9-8444-837eacd83cac.jpg)

**Comment by klepp0906** [comment]
yea, i mean.. thats why i provided logs.   it worked fine for me too.  since ever.   and once i updated - it stopped.   and im able to repeat it 100x by rolling back to that build, then any build after does not work.

im not a programmer so out of my hands at that point.  it very well may apply to a particular processor or who knows what.  apart from the dev team.

**Comment by Asinin3** [comment]
Can you try disabling TSX-FA on the Settings > CPU tab just set it to disabled.

**Comment by klepp0906** [comment]
yea I did try that, but ill try again.  Taking any and all suggestions for SURE.

fwiw if its telling/helpful on the non working builds the running log in the GUI just sits on

U {PPU[0x1000000] Thread (main_thread) [0x01fe1038]} sys_prx TODO: _sys_prx_unload_module(id=0x231ffa00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x01fe1038]} sys_prx TODO: _sys_prx_unload_module(id=0x231ffb00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x01fe1038]} sys_prx TODO: _sys_prx_unload_module(id=0x231ffc00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x01fe1038]} sys_prx TODO: _sys_prx_unload_module(id=0x231ffd00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x01fe1038]} sys_prx TODO: _sys_prx_unload_module(id=0x231ffe00, flags=0x0, pOpt=*0x0)

and it goes on and on and on perpetually it looks like.   Just brought in groceries and left it running, 10 mins later still doing that ^

will grab new version and try w/ tsx off.  report back asap

**Comment by klepp0906** [comment]
no change w/ TSX off.  

let me see if i can figure out how to compile a build of rpcs3.  always just pulled from the website but i dont think that newest one is up yet.

**Comment by Asinin3** [comment]
It's already compiled automatically through appveyor, do this:
![image](https://user-images.githubusercontent.com/15137035/66678708-0691d600-ecb4-11e9-9079-365ec0955e8b.png)
![image](https://user-images.githubusercontent.com/15137035/66678725-114c6b00-ecb4-11e9-8fc9-f7db39f5529e.png)
![image](https://user-images.githubusercontent.com/15137035/66678740-1a3d3c80-ecb4-11e9-9a0e-5ee5d120ad3c.png)
![image](https://user-images.githubusercontent.com/15137035/66678763-275a2b80-ecb4-11e9-8e06-bf52f81a8ce5.png)

**Comment by klepp0906** [comment]
ah, excellent - was not aware.

in the middle of reinstalling the game again and waiting for the ppu modules to compile so once thats done - ill try that build.

appreciate it very much

**Comment by klepp0906** [comment]
well, i was hopeful.  after a complete clearing out and reinstall of nnk, and that new build.    Still just repeats `unloading module idxxxxxx` forever and ever in the log ><

open to all suggestions but ive tried all that i know and the only thing that works is rolling back, waaay back >.<

**Comment by klepp0906** [comment]
heres the log w/ the new build, though i imagine it doesnt say anything any different than the older ones.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3719464/RPCS3.log.gz)

**Comment by klepp0906** [comment]
well, one of two things is happening here.  Either this only affects the NPUB version and not the BLUS version, or the NPUB version has some kinda residual something hidden somewhere within the rpcs3 directory that is messing things up.

ive cleared the cache entirely, re installed entirely several times.

low and behold BLUS30947 works fine.   

Not exactly a solution considering my saves are for NPUB for starters, plus i would still love to understand what the issue is in case it ever crops up in the future.

**Comment by elad335** [comment]
Any update?

**Comment by klepp0906** [comment]
unfortunately no.  Ive been busy with so many things i havent revisited.   I "think" this was only haunting me using OGL, which was basically mandatory as I play remote 99% of the time and steam refuses to stream vulkan.

I found away around the vulkan capture problem by forcing block-transfer instead of page-flip for the buffer.  I can now stream anything vulkan fine and last I just fired it up and all seems well.

in the end vulkan is almost always the way to go if you can anyhow.  I just have good hardware and so opengl wasnt holding me back from anything.  the ability to steam, and the uniform compatibility across almost all platforms and mediums was attractive.

unfortunately things like this were significant drawbacks however rare.

anyways - its running for me now at least via vulkan w/ a couple week (last time i updated)  old build.

**Comment by elad335** [comment]
Closing until relevant information on how to reproduce is added, and it must be a valid situation. (using correct settings etc)
