### ISSUE TITLE
Planet Minigolf™ [NPEB00163] Vulkan graphic glitches 

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6750]
during the videos they are blurry and during the gameplaythe bottom of the screen is blurry aswell
the lighting is not correct aswell
when you go to do a RSX capture the game crashes out with
F {RSX [0x01397ac]} MEM: Access violation reading location 0xcf900000
![minigolf](https://user-images.githubusercontent.com/2696404/66695385-90ad5f00-ecf3-11e9-9b36-29db950a8625.PNG)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3720242/RPCS3.zip)
doesnt happen in opengl

**Comment by AniLeo** [comment]
Upload an RSX capture

**Comment by benderscruffy** [comment]
graphics are fixed now
![golf](https://user-images.githubusercontent.com/2696404/70841078-43b04b00-1e52-11ea-89fb-06b33f347012.PNG)
