### ISSUE TITLE
Gatling Gears [NPUB30454] vulkan graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6753]
using Vulkan on the right hand side of the screen it is glitchy lines
![gattling](https://user-images.githubusercontent.com/2696404/66697076-ecccaf00-ed04-11e9-93d5-25b2b63330d3.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3720327/RPCS3.log.gz)
[NPUB30454_20191013081129_capture.zip](https://github.com/RPCS3/rpcs3/files/3721283/NPUB30454_20191013081129_capture.zip)
[NPUB30454_20191013081129_capture.z01.zip](https://github.com/RPCS3/rpcs3/files/3721292/NPUB30454_20191013081129_capture.z01.zip)
[NPUB30454_20191013081129_capture.z02.zip](https://github.com/RPCS3/rpcs3/files/3721285/NPUB30454_20191013081129_capture.z02.zip)
on the z01 and z02 files just remove the .zip on the end of it

**Comment by Asinin3** [comment]
Missing Renderdoc or RRC capture. And need more info, I've played this game previously and the issue wasn't there on Vulkan so it must be a regression. Would be best to find where it broke so the developers know how to fix it, a log doesn't by itself isn't much use to finding the cause here.

**Comment by Asinin3** [comment]
I duplicated your settings, cleared caches and tried multiple builds of RPCS3 but I can't reproduce this at all. Might be specific to AMD GPU's.
![image](https://user-images.githubusercontent.com/15137035/66706268-ff340080-ed77-11e9-9cbb-8cac2055ff58.png)

You should provide a Renderdoc and RRC capture and try some builds from e.g each month over 2019 until you find where it broke though..

**Comment by benderscruffy** [comment]
here is a renderdoc
https://mega.nz/#!5mwWzQ6L!qQ059JLACXzvGIfere2ybA_jdWu0oLLxGiAhCMN2pWQ

**Comment by benderscruffy** [comment]
with "Force CPU blit" and "Write color buffers it is fixed

**Comment by kd-11** [comment]
All these AMD issues are regressions but not reported as such. This has caused much time wasted.
