### ISSUE TITLE
WRC 5 FIA World Rally Championship [NPEB02265] rainbow graphics

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6754]
using Vulkan lots of rainbow graphics
opengl the same with flashing graphics aswell
![wrc5](https://user-images.githubusercontent.com/2696404/66698258-df1c2700-ed0e-11e9-88b8-ddc967bab60b.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3720397/RPCS3.log.gz)

**Comment by legend800** [comment]
Turn on WCB + Strict Rendering for perfect gfx for the WRC series. Please confirm and close issue.

**Comment by incognitoh** [comment]
if a game requires strict rendering, then it is an issue worth looking into by kd11 at some point, no reason to close the issue. with that said, those settings do not fix this game's graphics.

**Comment by kd-11** [comment]
Actually not true. Strict rendering is how the emulator is supposed to operate, we just disable it optionally for performance reasons.

**Comment by Kravickas** [comment]
Same as #6187 . Close this.
