### ISSUE TITLE
Resident Evil: The Umbrella Chronicles [NPUB30650] 50/50 behaviour

### ISSUE THREAD

**Issue by dyno0** [RPCS3/rpcs3#6760]
When running the game for the first time, having to compile ppu and spu modules from scratch, game runs flawlessy and is in a fully playable state. On the other hand, if you happen to close and reopen the game it will crash right after building spu cache, every single attempt after the first run.

[crashing.log.zip](https://github.com/RPCS3/rpcs3/files/3721222/crashing.log.zip)
(BackgroundJob failure, memory read access violation)

[working.log.gz](https://github.com/RPCS3/rpcs3/files/3721223/working.log.gz)
(rapid spam of cellCamera and cellGem stubs, but proceeds ingame and is perfectly playable)

**Comment by dyno0** [comment]
With further testing I noticed it will boot up if it's SPU cache is cleared before starting the game, running fine during the session. If the games' SPU cache is preexisting or not cleared during any other run attempt, it will result in an error identical in the attached crashing.log.zip.

**Comment by digitaldude555** [comment]
No longer an issue.

**Comment by dyno0** [comment]
Yea it's still very much an issue.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4172193/RPCS3.log.gz)
