### ISSUE TITLE
[Regression] Dead space (BLUS30177/BLES00309) crash "runtime error" since 8819

### ISSUE THREAD

**Issue by LuckyGuit** [RPCS3/rpcs3#6764]
Hi everyone!
Dead space (EU or NTSC version) is randomly crashing at startup of the game, in the menu or few seconds after going ingame. I tested every versions and **it started with 0.0.7-8819**
Worked perfectly with older builds.
Rpcs3 Log says in purple(see log attached) : 

**F {PPU[0x1000003] Thread () [0x0073cb00]} class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\Cell\lv2\sys_cond.cpp:294)**

Crashes occurs on my 2 rigs: I7 4770k+vega 64 and 7300hq+nvidia 1050Ti. Windows 10 latest, ram 16gb.
I tried to uninstall/reinstall Vc runtime but nothing...
It seems in last version (0.0.7-8880) i can go further ingame but still the same crash.
Any help developpers? Thanks!!!

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3724650/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3724651/RPCS3.log.gz)

**Comment by elad335** [comment]
Got it.

**Comment by elad335** [comment]
Test with #6762

**Comment by LuckyGuit** [comment]
Thank you, tested with 0.0.7-94e980c8 and i can confirm it solves the crashes! Besides a bit more audio stuttering, no problem with this build!

**Comment by LuckyGuit** [comment]
Thank you, i tested it with 0.0.7-27983fb9 and can confirm it resolves the crashes! Seems to have more audio stuttering than previous builds though. Will it be merged with the master branch soon? Thanks again!

**Comment by elad335** [comment]
Merged, should close the issue now.
