### ISSUE TITLE
RPCS3 crashes when opening global Config dialog on Windows if it's placed in a folder directly on drive (so like C:/rpcs3)

### ISSUE THREAD

**Issue by rajkosto** [RPCS3/rpcs3#6775]
```
bool fs::create_path(const std::string& path)
{
	const std::string parent = get_parent_dir(path);

	if (!parent.empty() && !is_dir(parent) && !create_path(parent))
	{
		return false;
	}
```
Something in there fails and an exception is thrown when parent is a drive letter like "C:". 
Moving rpcs3 to one folder deeper like C:/ps3/rpcs3/ worksaround the issue.
Last working commit before this happens is 4d0291ed so PR #6763 broke it

**Comment by Nekotekina** [comment]
I think it's fixed now

**Comment by rajkosto** [comment]
Fixed with https://github.com/RPCS3/rpcs3/commit/7ca76ae5a8a560fbe27f4d64cfbd4bfa6c8be9fd but further regressions from using raw paths on windows may still happen.
