### ISSUE TITLE
[BLES01593] Atelier meruru ALWAYS crashes with MEM: Access violation reading location 0x68686878 at same place.

### ISSUE THREAD

**Issue by y-salnikov** [RPCS3/rpcs3#6776]
I know that phyre engine games are not very stable and random crashes and hangings are expected, but this game marked as playable. The game always (not randomly) crashes when you initiate battle at places "Crescent Lake" and "Dry Wasteland" with message:
 `F {PPU[0x1000000] Thread (main_thread) [0x006c560c]} MEM: Access violation reading location 0x68686878`
or
`F {PPU[0x100010f] Thread (ThreadEasyMainTime) [0x0026d570]} MEM: Access violation reading location 0x68686874` 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3730549/RPCS3.log.gz)
[SAVEDATA_BLES01593-LIST-03.tar.gz](https://github.com/RPCS3/rpcs3/files/3730558/SAVEDATA_BLES01593-LIST-03.tar.gz)
By crash i mean black screen, music still playing for couple of seconds, fps counter is working, then access violation message occur. 
Switching to PPU interpreter doesn't help as well as manually loading   libfs.sprx module as recommended on compatibility page.

**Comment by 13xforever** [comment]
Have you tried setting spu decoder to interpreter (fast)

**Comment by y-salnikov** [comment]
Yes. Same results.

**Comment by HerrHulaHoop** [comment]
I'm on BLUS30941 but I managed to get your save to work. Both locations work flawlessly for me. No crashes at all. Managed to clear out all monsters and collect all herbs without issues. This might have to do with something specific to your setup. Please join our [discord server](https://discord.me/RPCS3) for support on this issue.

[Log](https://github.com/RPCS3/rpcs3/files/3731278/RPCS3.log.gz) for what it's worth.


<details>
 <summary>Crescent Lake</summary>

![rpcs3_8891_2019-10-16_01-34-24](https://user-images.githubusercontent.com/31934788/66866325-ac945780-efb6-11e9-92a7-c2e9e35c1b4b.jpg)
![rpcs3_8891_2019-10-16_01-43-29](https://user-images.githubusercontent.com/31934788/66866328-ad2cee00-efb6-11e9-90c3-5975b1ca4be5.jpg)
</details>

<details>
 <summary>Dry Wasteland</summary>

![rpcs3_8891_2019-10-16_01-36-45](https://user-images.githubusercontent.com/31934788/66866326-ad2cee00-efb6-11e9-824a-2cb82db75132.jpg)
![rpcs3_8891_2019-10-16_01-37-48](https://user-images.githubusercontent.com/31934788/66866327-ad2cee00-efb6-11e9-85e9-c693945596cf.jpg)
</details>

**Comment by y-salnikov** [comment]
Yes, i think my "backuped" image was bad. Works fine on BLUS30941.
