### ISSUE TITLE
[NPUB30836] One Piece: Pirate Warriors Flickering/Flashing Background

### ISSUE THREAD

**Issue by web1018** [RPCS3/rpcs3#6777]
During the cutscenes, only the game background is Flicking/ Flashing constantly. The rest of the gameplay textures are fine without any issues. 

![Capture2](https://user-images.githubusercontent.com/51851411/66875216-88675500-ef7b-11e9-9c1d-2dba97cd6f26.PNG)
![Capture3](https://user-images.githubusercontent.com/51851411/66875218-89988200-ef7b-11e9-9d22-4d285a74ae35.PNG)
![Capture1](https://user-images.githubusercontent.com/51851411/66875219-8ac9af00-ef7b-11e9-8121-eaa3b5361f68.PNG)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3731728/RPCS3.log.gz)

**Comment by MarioSonic2987** [comment]
This bug was already reported on #2262. Could you close this issue?
