### ISSUE TITLE
crash during press+hold key if game does not call cellkbinit()

### ISSUE THREAD

**Issue by plappermaul** [RPCS3/rpcs3#6781]
I'm running The Ratchet & Clank Trilogy with the current master rpcs3. This games starts a menu application where you can choose from 1 of 3 games. After you choose one of them the the main window closes and a new starts. Game loads fine but as soon as you press and hold (!) a key the game crashes.

![grafik](https://user-images.githubusercontent.com/10179087/66935364-27538600-f03c-11e9-93f5-347060927061.png)

Error seems to come from a missing keyboard initialization for the second window. 

```
void basic_keyboard_handler::keyReleaseEvent(QKeyEvent* keyEvent)
{
	if (!keyEvent)
	{
		return;
	}

        * CRASH HERE BECAUSE M_KEYBOARDS IS NOT SET!
	if (keyEvent->isAutoRepeat() && !m_keyboards[0].m_key_repeat)
	{
		keyEvent->ignore();
		return;
	}

	const int key = getUnmodifiedKey(keyEvent);

	if (key >= 0)
	{
		Key(static_cast<u32>(key), false);
	}
}

```

From my desperate debug analysis I would say it boils down to the fact that cellKbInit() is not called for the second window.

**Comment by plappermaul** [comment]
Btw. this is Linux.

**Comment by plappermaul** [comment]
Correction: Seems to depend on the game and has nothing to do with a second window. Crash happens in Persona 5 too. cellkbinit() is not called.

![grafik](https://user-images.githubusercontent.com/10179087/67025170-e162f480-f105-11e9-8c66-3f22edb1f02c.png)

**Comment by Megamouse** [comment]
I think this is a regression from fxm stuff and breaks all the handlers similarly but I might be wrong.

**Comment by Megamouse** [comment]
Could you please retest this

**Comment by Megamouse** [comment]
Retest please :)

**Comment by plappermaul** [comment]
yeah, works fine now wit latest master
