### ISSUE TITLE
Gotham City Impostors [NPUB30252] stuck on title screen

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6793]
stuck on the title screen
![gotham](https://user-images.githubusercontent.com/2696404/67070722-6a843500-f1b3-11e9-870d-5f5eccefe1be.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3742528/RPCS3.log.gz)

**Comment by lextra2** [comment]
Yes. And? This has been known since 2017-08-06
https://rpcs3.net/compatibility?g=Gotham
https://forums.rpcs3.net/thread-195425.html

**Comment by benderscruffy** [comment]
sorry dont check out the forums

**Comment by lextra2** [comment]
Like I said, it is an online only game. What exactly do you expect here?

**Comment by AniLeo** [comment]
Closing as this isn't the place for compatibility reports, the game tracker is over at our forums
