### ISSUE TITLE
NCAA 14: Shader issue

### ISSUE THREAD

**Issue by huskereurocat** [RPCS3/rpcs3#6796]
![Desktop Screenshot 2019 09 01 - 13 57 04 83](https://user-images.githubusercontent.com/52609668/67092713-8e288a80-f175-11e9-9e67-c02f260d4106.png)Need to see if the shaders can be improved. See the photo above where the apron around the field remains dark. This only happens in night games. 
Sound is still choppy, I have consulted the discord help forum and reset some things according to their recommendations with no improvement. Current settings attached. I have been told that I need a stronger CPU. Is a R7 1700 not a strong enough CPU for running RPCS3? 
![Desktop Screenshot 2019 10 18 - 07 10 17 06](https://user-images.githubusercontent.com/52609668/67093227-c2507b00-f176-11e9-910e-b5a14ec67794.png)
![Desktop Screenshot 2019 10 18 - 07 10 31 42](https://user-images.githubusercontent.com/52609668/67093228-c2507b00-f176-11e9-94ed-ecc7737f867f.png)

**Comment by kd-11** [comment]
> Is a R7 1700 not a strong enough CPU for running RPCS3?

It is. I use one and its fine.

As for choppy audio, you're intentionally throttling SPUs with the preferred threads option and audio is mostly generated using SPUs. Choppiness is somewhat expected. Note that windows does not handle zen1 processors properly to this day, even with all the improvements to the scheduler. Its very likely the choppy audio is not a problem on other operating systems.

**Comment by huskereurocat** [comment]
So basically an upgraded CPU is needed, correct. I don't see that happening any time soon since that would mean an upgraded MoBo as well. $500, so it'll have to wait. 
Would improvements to the SPUs help? I changed the SPU threads to auto and that has very little affect. 

Whatever the case, looking into the shader issue would be appreciated!

**Comment by digitaldude555** [comment]
Disabling async shaders fixes this. @huskereurocat try that.

**Comment by huskereurocat** [comment]
This is what the field looks like when I disable the async shaders. Doesn't
seem to make a difference.
As well, unless I spend a bunch of cash and upgrade from my R7 1700 CPU I
will still have the stuttering sound issue. I can't see doing that right
now. I thought that  with all the improvements in performance, that would
have been taken care of but not yet.
I appreciate your help and any added assistance is appreciated!!!
*Kelly Yero*
1827 Taylor Creek Dr
Fresno, TX 77545
Cell: 779-456-0836
Home: 815-582-4036

**Comment by huskereurocat** [comment]
Tried that and I still get the black shaded out apron around the field as above. 
I appreciate all the help!

**Comment by huskereurocat** [comment]
The comment was made that this shader issue may be specific to just this stadium. It was suggested that this may happen in the PS3 version of the game, but since I don't have a console, I can't confirm this. If this is true then this issue would be irrelevant and this issue could be closed because I haven't seen this happen in other stadiums. Does anyone have a console that this could be tested on?

**Comment by Asinin3** [comment]
Still an issue?

**Comment by huskereurocat** [comment]
Are you referring to the shader issue or the choppy sound in this game? In any case, I've updated to the latest build and both are still a problem. I think I need to upgrade my CPU for the sound issue to be resolved since I have an r7 3600x. Can't do that at the moment. I've put in a request today again for someone with the PS3 version of the game to let me know if this is just a game glitch or is specific to RPCS3. I will update this by the end of the day whether I get a response or not.

**Comment by Darkhost1999** [comment]
Are you asking for comparison screenshots from a real physical console because you do not have a PS3 anymore?

**Comment by huskereurocat** [comment]
Yes. Because I've never had a console before and still don't. I just bought the PS3 disk knowing that I could use it with RPCS3.

**Comment by Asinin3** [comment]
Audio issues are often fixed by changing settings but its hard to suggest anything if you dont post a log file.
Typically, turn spu loop off, make sure your using SPU/PPU LLVM Recompilers, and then if audio is still bad try 1, 2,3 and auto preferred spu threads on cpu tab and see if any of them help.

**Comment by huskereurocat** [comment]
Just wanted to give an update on the shader issue. Seems that this is an issue in the base game. So the shader issue isn't really an issue. 

Asinin3 - I've attached the log for audio direction's, but am in the middle of testing using your recommendations above. Thanks 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7173859/RPCS3.log)

![image0](https://user-images.githubusercontent.com/52609668/133527354-a29e16c0-5392-428a-a69f-985dbbdc5adb.jpg)
