### ISSUE TITLE
Regressions from #6774

### ISSUE THREAD

**Issue by Josivan88** [RPCS3/rpcs3#6799]
Tested on 0.0.7-8909 and it is working:
![Untitled-1](https://user-images.githubusercontent.com/36341425/67123339-66adde00-f1c6-11e9-848f-0ded8c64b759.jpg)
Tested on 0.0.7-8920 and 007 games can't pass from intro videos since #6774 mipmap PR by @kd-11 
![Untitled-4](https://user-images.githubusercontent.com/36341425/67123401-978e1300-f1c6-11e9-8e00-e8aaabec67dd.jpg)

Showing:
F {RSX [0x0268bb0]} RSX: class std::runtime_error thrown: Verification failed:
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:1380)

Just open the game and diference is visible, problem happens with openGL and Vulkan, tested on a:
i7 9700k
16Gb of RAM
Nvidia GTX 1070

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3745443/RPCS3.log.gz)

**Comment by kd-11** [comment]
Can you update with the latest build? There is no verification on the line in the error message. Several other commits have been added to master since then so the current builds should print a different line address.

**Comment by Josivan88** [comment]
Latest build tested, and:
F {RSX [0x0248e10]} RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:1389)
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3745494/RPCS3.log.gz)

**Comment by Josivan88** [comment]
Latest build openGL:
F {RSX [0x027a388]} RSX: class std::runtime_error thrown: Verification failed (e=0xb7): 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\GL\GLHelpers.h:2049)
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3745499/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Also happens with Knights Contract [BLES01001]

**Comment by jeremybris** [comment]
> Latest build openGL:
> F {RSX [0x027a388]} RSX: class std::runtime_error thrown: Verification failed (e=0xb7):
> (in file C:\projects\rpcs3\rpcs3\Emu\RSX\GL\GLHelpers.h:2049)
> Log:
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3745499/RPCS3.log.gz)

Same error in

- Haze [BLUS30094]
- James Bond 007 Blood Stone [BLUS30289]
- Goldeneye 007 Reloaded [BLUS30755]

, I'm pretty sure.

**Comment by kd-11** [comment]
This PR fixes it https://github.com/RPCS3/rpcs3/pull/6813. Check for any other glitches.

**Comment by incognitoh** [comment]
hi @kd-11 found a regression and finally narrowed it to pr #6774. still happens on latest master.

![mlb2](https://user-images.githubusercontent.com/39333810/67228607-a283b600-f407-11e9-840c-69cd4bcc92e6.JPG)
![mlb1](https://user-images.githubusercontent.com/39333810/67228608-a283b600-f407-11e9-8bb5-1d8ed9e82cdc.JPG)
![mlb03](https://user-images.githubusercontent.com/39333810/67228915-3e152680-f408-11e9-81d1-8a586b73e343.JPG)

 here is a rsx cap: https://mega.nz/#!II1UHKrY!6E_ZoxVKYkXVAcEmX_U6jDpa29iNhpagtOzg8iF9hGA

(gtx 1070 gpu)

**Comment by kd-11** [comment]
I'll investigate and reopen if necessary.

**Comment by Josivan88** [comment]
everything is ok with 007 games on last master, thank you kd-11

**Comment by incognitoh** [comment]
@kd-11 not sure if you got to look at this yet, but just to update, the regression still remains in today's master:

![ml2](https://user-images.githubusercontent.com/39333810/68302273-abaf8c80-006f-11ea-8439-4a6ed1e696fd.jpg)

**Comment by kd-11** [comment]
Forgot about this one; the regression is not real, its just unhidden another issue with framebuffer setup. The game is not setting them up correctly which causes the emulator to rely on guessing and we guess incorrectly. The only thing that changed is that now we're able to see the other LODs and we can see they're filled with bogus depth data.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/6956
