### ISSUE TITLE
Injustice: Gods Among Us [NPUB31181] missing intro videos [CELL_VDEC_ERROR] maybe

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6801]
no videos just a black screen but you can hear the sounds and music
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3746038/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Needs test with LLE libvdec

**Comment by benderscruffy** [comment]
yes the videos work with libvdec ticked

**Comment by RainbowCookie32** [comment]
Got ingame without a save and all videos played just fine on default settings, is this still an issue?

**Comment by benderscruffy** [comment]
this has been fixed
