### ISSUE TITLE
Duke Nukem Forever [NPEB00828] nothing but a black screen

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6802]
no matter what settings i use nothing but a black screen
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3746097/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
Seems to be the expected result, considering the game is marked as Intro on the compatibility database https://rpcs3.net/compatibility?g=duke+nukem

**Comment by benderscruffy** [comment]
doesnt even show the logos any more

**Comment by lextra2** [comment]
What is your plan here? To spam tickets about every game that has not changed its compatibility state?

> doesnt even show the logos any more

Than go and figure out the last build that showed the logo,

**Comment by benderscruffy** [comment]
so it has gone from intro to loadable
so noone show open an issue then

**Comment by RainbowCookie32** [comment]
If you are reporting a regression, then you should find which build broke it. Makes debugging the issue easier for developers

**Comment by benderscruffy** [comment]
closing as to many cry babies
