### ISSUE TITLE
Dragon Ball Raging Blast 2 crashes more frequently after #6737

### ISSUE THREAD

**Issue by StevenMiller123** [RPCS3/rpcs3#6803]
On 0.0.7-8855 and newer, Dragon Ball Raging Blast 2 crashes when trying to load some characters with graphical glitches (Vegeta (Scouter) consistently causes crashes). This happens regardless of what settings I apply, I tested various versions between 0.0.7-8850 and 0.0.7-9122. Before testing each version I did clear caches.

If I need to add any more details, please let me know. 
[RPCS3 0.0.7-9035.log.gz](https://github.com/RPCS3/rpcs3/files/3781350/RPCS3.0.0.7-9035.log.gz)
[RPCS3 0.0.7-8852.log.gz](https://github.com/RPCS3/rpcs3/files/3746101/RPCS3.0.0.7-8852.log.gz)

**Comment by kd-11** [comment]
This should have been introduced by the fifo reset fix, not the mipmaps PR.

**Comment by jeremybris** [comment]
> This should have been introduced by the fifo reset fix, not the mipmaps PR.

I just tested this game again, and I did not receive the same error for some reason. Just ignore me linking the two issues. I retested the other games too I listed, and I still get the error though.

**Comment by elad335** [comment]
Retest and upload log with #6810.

**Comment by StevenMiller123** [comment]
Here is the new log: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3747309/RPCS3.log.gz)

**Comment by StevenMiller123** [comment]
#6737 also introduced similar crashes in Dragon Ball Z: Ultimate Tenkaichi and J Stars Victory VS+. Should I also add logs for these?
