### ISSUE TITLE
Enemy Territory: QUAKE Wars™ Demo [NPUB90092] sys_net: Unknown/illegal socket error: 10048

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6804]
every time you press x to start the game it always comes up with this error
E {PPU[0x1000000] Thread (main_thread) [0x020d10a4]} sys_net: Unknown/illegal socket error: 10048
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3746116/RPCS3.log.gz)

**Comment by lextra2** [comment]
This is known
https://rpcs3.net/compatibility?g=Enemy+Territory
https://forums.rpcs3.net/thread-178928.html

And you were already told that 
> this isn't the place for compatibility reports

**Comment by RainbowCookie32** [comment]
Indeed. As reported [here](https://forums.rpcs3.net/thread-200181-post-305868.html#pid305868), that error is why the game is currently marked Intro.

Please check the compatibility list and reports before opening issues.

**Comment by benderscruffy** [comment]
https://forums.rpcs3.net/thread-178928.html
and there is no log on that thread and was last tested over 2 years ago 
so should people just let threads die and nothing done about them

**Comment by RainbowCookie32** [comment]
Then make a report there. "Game is still Intro, with this error, here's the log". 

Compatibility reports go to the forums, not here. If the thread wasn't updated in a long time, or there are no proper reports, then make one, don't open an issue here instead.

**Comment by benderscruffy** [comment]
closing as to many crybabies
