### ISSUE TITLE
Ridge Racer 7: When will they fix these bugs

### ISSUE THREAD

**Issue by GrandGTA** [RPCS3/rpcs3#6805]
there are the things that are needed to be fixed in this game in the next release of RPCS3

-crashing
-flickering trees
-red screen on Sunset Heights or the Sunset Heights black screen
-lag

i guess we have to wait till these things are fixed

Edit: wait and also the You got a new machine black screen or red screen

**Comment by boy13epic** [comment]
you’re just toxic,it’s completely valid

**Comment by AniLeo** [comment]
Yes, as valid as the milk that just expired last month

**Comment by boy13epic** [comment]
k
