### ISSUE TITLE
Persona 5 Batting Cages minigame has graphics issues, also doesn't work as intended

### ISSUE THREAD

**Issue by emandrow** [RPCS3/rpcs3#6807]
I'm using version 0.0.7-8935-d4ba7f37 Alpha.

My system specs are Nvidia GeForce GTX 1060 6GB GPU and Intel i7-7700 CPU, and I'm using Windows 10.

During the batting cages minigame a semi-transparent ball icon should appear around the middle of the screen, like in this video: https://www.youtube.com/watch?v=ZakXCcp2eo8

The problem is this icon doesn't show up:
![screen1](https://user-images.githubusercontent.com/53008975/67144133-cf06c900-f273-11e9-900c-17820b4651eb.png)

Also, the screenshot above shows a bug where the machine shoots two balls every turn instead of one; it also locks player input and doesn't show the red bat icon for tries #2 and #4, skipping them: 
![screen2](https://user-images.githubusercontent.com/53008975/67144396-345bb980-f276-11e9-8c54-23abd09c57aa.png)

By the way, I'm using the 60fps patch, but the problem persists even when I set the framelimiter to 30.

**Comment by AniLeo** [comment]
Test without the 60fps patch and no frame limit. Timing results with the patch are not valid.

**Comment by MsDarkLow** [comment]
The semi-transparent ball shows up on my end. 
No mods, No patches, No nothing.
![3](https://user-images.githubusercontent.com/9060436/67145834-cebefb80-f27c-11e9-844b-ede7b22b21d3.jpg)

**Comment by emandrow** [comment]
I turned the 60fps patch off and now it works perfectly. Thanks!

**Comment by SpoilerOfGames** [comment]
> I turned the 60fps patch off and now it works perfectly. Thanks!

Hi there, I am having the exact same issue. I was able to get the game running smoothly at 60 fps, but this part of the game is bugging out as you described. How do I turn off the 60 fps patch? I am using the Mod Loader. I would really really appreciate your help in getting past this section.

**Comment by 13xforever** [comment]
github is not for support, and this is issue with your mods, and not with the emulator itself
