### ISSUE TITLE
NCAA 14: Reproducible System Crash Bug

### ISSUE THREAD

**Issue by LRizoJr** [RPCS3/rpcs3#6808]
Hello,

RPCS3 v0.0.7-8779-ee0633f4 Alpha | HEAD | Firmware version: 4.85
AMD Ryzen 7 2700X Eight-Core Processor | 16 Threads | 15.93 GiB RAM | TSC: Bad | AVX+
Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0

![image](https://user-images.githubusercontent.com/6733316/67146353-49c1eb00-f258-11e9-92c3-8fde8569eb0b.png)

![image](https://user-images.githubusercontent.com/6733316/67146356-57777080-f258-11e9-8430-20c52f3970c1.png)

![image](https://user-images.githubusercontent.com/6733316/67146357-5b0af780-f258-11e9-976e-ba9021dd9ad0.png)

This bug freezes the game instantly and can be reproduced in my current save game state by trying to perform a Scouting action on the last player in my recruiting board. The player is 90% scouted and this scouting action would reveal his final rating value. Note that I have fully scouted other players on my board and this issue does not occur. It may be something with the particular player, position, or possibly his position on my recruiting board. 

I will make a back-up of the Save Game in case you need it. Attached is the log file. 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3746774/RPCS3.zip)

**Comment by LRizoJr** [comment]
Stack trace of the moment the game freezes:
W {PPU[0x1000015] Thread (LoopRender) [0x01ff1c44]} sys_rsx: sys_rsx_attribute(packageId=0x2, a2=0x1, a3=0x0, a4=0x0, a5=0x0)
W {PPU[0x1000015] Thread (LoopRender) [0x01ff1c6c]} sys_rsx: sys_rsx_context_attribute(context_id=0x55555555, package_id=0x101, a3=0x1, a4=0x2, a5=0x0, a6=0x0)
! {PPU[0x1000014] Thread (LoopSimulation) [0x004bc060]} 
Type: class named_thread<class ppu_thread>
State: 0x294[w|s|mem|G-PAUSE]
Priority: 1000
Stack: 0xd0155000..0xd0174fff
Joiner: detached
Commands: 0
Last function: sys_mutex_unlock
Waiting: 0.000082s

Registers:
=========
GPR[0] = 0x4bc060
GPR[1] = 0xd016fd80
GPR[2] = 0x1c64fd0
GPR[3] = 0x211276a0
GPR[4] = 0xd016fdf0
GPR[5] = 0x8a14fc5d
GPR[6] = 0x69bfde62
GPR[7] = 0x1
GPR[8] = 0x1fde62
GPR[9] = 0x38c6b4df
GPR[10] = 0xc635a6f8
GPR[11] = 0xffffffffffffffff
GPR[12] = 0xd016fd50
GPR[13] = 0x200095e0
GPR[14] = 0xe
GPR[15] = 0xe
GPR[16] = 0xe6
GPR[17] = 0x14e
GPR[18] = 0xd016fdf4
GPR[19] = 0xd016fdf0
GPR[20] = 0x2
GPR[21] = 0x0
GPR[22] = 0x211276a0
GPR[23] = 0x1
GPR[24] = 0x2
GPR[25] = 0x16fa9b4
GPR[26] = 0xd016fe28
GPR[27] = 0x8d256c00
GPR[28] = 0xd0170000
GPR[29] = 0x1cf2e60
GPR[30] = 0x3
GPR[31] = 0xffff
FPR[0] = 6
FPR[1] = 1.88399E-314
FPR[2] = 4.29497E+09
FPR[3] = 0.112161
FPR[4] = 70
FPR[5] = 0.69217
FPR[6] = 0
FPR[7] = 1
FPR[8] = 1.5708
FPR[9] = 0.514975
FPR[10] = 1
FPR[11] = 0.848308
FPR[12] = 0.851024
FPR[13] = 1
FPR[14] = 0
FPR[15] = 0
FPR[16] = 0
FPR[17] = 0
FPR[18] = 0
FPR[19] = 0
FPR[20] = 0
FPR[21] = 0
FPR[22] = 0
FPR[23] = 0
FPR[24] = 0
FPR[25] = 0
FPR[26] = 0
FPR[27] = 0
FPR[28] = 0
FPR[29] = 0
FPR[30] = 33.5833
FPR[31] = 0.0166667
VR[0] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[1] = 0x80000000800000008000000080000000 [x: -0 y: -0 z: -0 w: -0]
VR[2] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[3] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[4] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[5] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[6] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[7] = 0x437f0000437f0000437f0000437f0000 [x: 255 y: 255 z: 255 w: 255]
VR[8] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[9] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[10] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[11] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[12] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[13] = 0xffffffff000000000000000000000000 [x: -nan y: 0 z: 0 w: 0]
VR[14] = 0xffffffffffffffffffffffffffffffff [x: -nan y: -nan z: -nan w: -nan]
VR[15] = 0xffffffffffffffffffffffffffffffff [x: -nan y: -nan z: -nan w: -nan]
VR[16] = 0x3f8000003f8000003f8000003f800000 [x: 1 y: 1 z: 1 w: 1]
VR[17] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[18] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[19] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[20] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[21] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[22] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[23] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[24] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[25] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[26] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[27] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[28] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[29] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[30] = 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
VR[31] = 0x00000010000000100000001000000010 [x: 2.24208e-44 y: 2.24208e-44 z: 2.24208e-44 w: 2.24208e-44]
CR = 0x88000088
LR = 0x4bc060
CTR = 0xf5b780
VRSAVE = 0xffffffff
XER = [CA=0 | OV=0 | SO=0 | CNT=0]
VSCR = [SAT=1 | NJ=0]
FPSCR = [FL=0 | FG=1 | FE=0 | FU=0]

Call stack:
=========
0x004bc060 (0x0) called
> from 0x00222d20 (0x0)
> from 0x002c901c (0x0)
> from 0x008c3c54 (0x0)
> from 0x0056b950 (0x0)
> from 0x008c3bb4 (0x0)
> from 0x0155a10c (0x0)
> from 0x00806dc8 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00847438 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00847438 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x0084675c (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x0084675c (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x00840ba8 (0x0)
> from 0x0084675c (0x0)
> from 0x00806b64 (0x0)
> from 0x00807224 (0x0)
> from 0x0081e2b8 (0x0)
> from 0x00823324 (0x0)
> from 0x00823ac8 (0x0)
> from 0x00823bf4 (0x0)
> from 0x00826764 (0x0)
> from 0x0070ab98 (0x0)
> from 0x00563ef8 (0x0)
> from 0x004032ac (0x0)
> from 0x00403380 (0x0)
> from 0x00169610 (0x0)
> from 0x00687900 (0x0)
> from 0x0040300c (0x0)
> from 0x00402a70 (0x0)
> from 0x00402ee0 (0x0)
> from 0x005c42cc (0x0)

F {PPU[0x1000014] Thread (LoopSimulation) [0x004bc060]} MEM: Access violation reading location 0xad33dc70
W {cellAudio Thread} cellAudio: Audio backend stopped unexpectedly, likely due to a buffer underrun

**Comment by elad335** [comment]
Just upload rpcs3.log.gz which is found on your rpcs3 folder, after you close the game.

**Comment by LRizoJr** [comment]
Thanks, I attached the log file to my original post.

**Comment by digitaldude555** [comment]
@LRizoJr update?

**Comment by LRizoJr** [comment]
I unfortunately can't find my Save Game backup so I can't test and be 100% sure we're good, but the issue has not occurred again after I updated in Dec or Jan after occurring almost once every season. I think we can close it for now.
