### ISSUE TITLE
Far Cry 4 [BLES02011] texture bug and freeze 

### ISSUE THREAD

**Issue by stan0danny** [RPCS3/rpcs3#6812]
i'm sorry, i'm wrong this avoid far cry 4 [BLUS31420] (Log file shows pirated game) , i'm found  far cry 4 [BLES02011] (ingame) ; log file check, fry cry 4 on rpcs3 is texture color bug and freeze , look my video here https://youtu.be/Yv6m6usrmaQ
Log file --> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3747435/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
Should be closed in favor of the more complete #8390
