### ISSUE TITLE
Dead Nation graphical glitch

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#6817]
I'm not really sure what to call this sort of graphical glitch. But it only happens in some areas and only after some time of being in it.

[Video](https://drive.google.com/open?id=1IHqXCV98lS48kem7Qo__US5fhaV0dc_8)

[Log](https://drive.google.com/open?id=1iXORUE2-cj0pTGWFCdVBBhr1sKaUKce7)

These lines is what I'm talking about.
![Untitled](https://user-images.githubusercontent.com/20690384/67183306-6c334000-f3e1-11e9-8b01-50ffe93641fd.png)

**Comment by RainbowCookie32** [comment]
I can't seem to reproduce this in latest master, unless the issue only happens on a later stage. If that's the case, someone should post a save. Otherwise, this can be closed probably

**Comment by dio-gh** [comment]
Can't repro here either.

**Comment by lextra2** [comment]
the place of the issue was chapter 2 after the second shop. anyway. I think either #8367 or #8398 fixed it (can't check atm for exact build)

closing
