### ISSUE TITLE
resistance fall of man  freezes

### ISSUE THREAD

**Issue by mahaleksmos** [RPCS3/rpcs3#6821]
resistance fall of man freezes.  rpcs3-v0.0.7-8935
The most recent error is purple
U {PPU[0x1000000] Thread (main_thread) [0x006c5d28]} sceNp TODO: sceNpManagerRegisterCallback(callback=*0x691188, arg=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x006c5d38]} sceNp TODO: sceNpManagerGetStatus(status=*0xd00ffb50)
F {PPU[0x1000000] Thread (main_thread) [0x000f2fcc]} MEM: Access violation reading location 0x61b8

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
