### ISSUE TITLE
[Linux] Autoupdater warning as 'you're currently running a custom pr or build' despite using official build from #6823

### ISSUE THREAD

**Issue by Leopard1907** [RPCS3/rpcs3#6827]
So it gives this warning.

![Ekran Görüntüsü - 2019-10-22 11-12-45](https://user-images.githubusercontent.com/24878978/67268412-15029d80-f4bd-11e9-89e3-3d70ab106d48.png)

When you click yes ( which it shouldn't yell at you at first place with official builds but it does) , it prints out "E [Auto-updater] Network Error: SSL handshake failed" at tty.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3754354/RPCS3.log)

Steps for repro:

1-) Get the latest build from RPCS3 website and boot it
2-) Click "Check for updates" in RPCS3
3-)Profit

**Comment by AniLeo** [comment]
Fixed
