### ISSUE TITLE
WWE Smackdown vs RAW 2010 [BLES00651] Black screen

### ISSUE THREAD

**Issue by BlackShadow** [RPCS3/rpcs3#6831]
System Specs:

CPU: Intel i9-9900K - @ 4.80GHz All Cores
GPU: MSI RTX 2080Ti Gaming Trio
RAM: G-Skill DDR4 32GB RAM @ 3000MHz
OS: Windows 10 x64 1903
RPCS3 Build: v0.0.7

After starting the game, there's minor flickering and it cannot make into in-game. It says at dark screen after choosing a match. This issue is same with Road to WrestleMania  

Also there's a video about the issue:

https://streamable.com/11pt4

RPCS3 Log :

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3755659/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Does it also happen with Vulkan? Make sure to update before checking

**Comment by BlackShadow** [comment]
Yes, it happens on Vulkan too.

**Comment by BlackShadow** [comment]
Yes, this issue occurs on Vulkan too. Everything is updated.

**Comment by toonninja66** [comment]
This also happens with WWE smackdown vs raw 2011

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by BlackShadow** [comment]
Tested on v0.0.11 - OpenGL and Vulkan - Windows 10 x64 2004 - Specs are same listed on above. Still black screen. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5066731/RPCS3.log.gz)

**Comment by Satan86** [comment]
a similar issue also happens on wwe '12 and wwe 2k14 but instead of not loading the match, it freezes while loading back to the main menu after the end of the match. It happens regardless of settings

WWE '12 log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5068192/RPCS3.log.gz)

WWE 2K14 log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5068210/RPCS3.log.gz)

**Comment by BlackShadow** [comment]
Tested on v0.0.15 - OpenGL and Vulkan - Windows 10 x64 20H2 - Specs are same listed on above. Issue still occurs.

**Comment by BlackShadow** [comment]
Tested on v0.0.19 - OpenGL and Vulkan - Windows 11 x64 - Specs are same listed on above. Issue still occurs.

**Comment by MrPwner01** [comment]
Here to report v0.0.21-13335 still black screens after selecting a match and opening superstar creator.
