### ISSUE TITLE
Modnation Racers [NPUA80535] is all green

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#6832]
Rpcs3, 8975, linux, r9 fury (tested also on nvidia gpu: same result), vulkan and OpenGl
![Capture_082](https://user-images.githubusercontent.com/7478580/67288370-22c81b00-f4dd-11e9-960e-5752d3bf807b.jpg)
![Capture_083](https://user-images.githubusercontent.com/7478580/67288567-83575800-f4dd-11e9-96cb-c3deb9a9d76e.jpg)

The rsx capture is here:
https://www.dropbox.com/s/gkhuye345908nk6/NPUA80535_20191022145920_capture.rrc.zip?dl=0

**Comment by Emulator-Team-2** [comment]
This issue is caused by the resolution scaling.

This game requires setting the resolution scale threshold to 1024x1024 when using resolution scaling.
