### ISSUE TITLE
Missing support for OpenGL on Wayland

### ISSUE THREAD

**Issue by linkmauve** [RPCS3/rpcs3#6835]
On Intel on X11, the OpenGL backend is much more fluid than the Vulkan backend (using their experimental Iris OpenGL driver), but it doesn’t seem to be hooked for Wayland at all.

Do you plan on supporting more than just Qt as a window creation library?  Otherwise we could replace the `QWindow` with either a `QVulkanWindow` or a `QOpenGLWindow` class, to avoid having to do any kind of platform-specific initialisation.

If this is acceptable I can start working on that soon, otherwise it would require Wayland-specific code to be added, and probably EGL support as well.

**Comment by kd-11** [comment]
No, backends should not rely on the frontend at all if possible, so no QVulkanWindow. As for OpenGL, we only used QOpenGLWindow because there were no good alternatives that would work across platforms. Unlike vulkan which is pretty easy to integrate, wgl initialization is a mess, and this is doubly so when creating a core context.

**Comment by kd-11** [comment]
> On Intel on X11, the OpenGL backend is much more fluid than the Vulkan backend (using their experimental Iris OpenGL driver), but it doesn’t seem to be hooked for Wayland at all.

You mean OpenGL on wayland? You can add it, but it will likely suffer from bit rot and get removed if you're not around to keep it alive. Not really sure we should do this ourselves either; doesn't Qt have proper OpenGL support on wayland?

> Do you plan on supporting more than just Qt as a window creation library? Otherwise we could replace the QWindow with either a QVulkanWindow or a QOpenGLWindow class, to avoid having to do any kind of platform-specific initialisation.

Yes, including a no-GUI mode.

**Comment by Geo25rey** [comment]
I would reccomend using the [glew-egl-glx](https://aur.archlinux.org/packages/glew-egl-glx/) package for Wayland support. It adds support for the EGL (Wayland) and GLX (X11) backends to GLEW at compile time.

**Comment by hcorion** [comment]
Is this issue still valid?

**Comment by kd-11** [comment]
This is not our bug even if it still happens.
