### ISSUE TITLE
Write Color Buffer freezes some games then crashes emulator

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#6836]
When the Write Color Buffer is enabled, some games that needs it freezes then crashes the emulator.
Impossible to send a log coz after the crash the log is not recorded.
For the best way to reproduce it,run GOW 3 or GOW Ascension (these 2 games needs WCB enables and makes the bug happens with LLVM or ASMJIT...

I9 9900KF
GTX 1080
Windows 10 16go

**Comment by Pouncha** [comment]
Ok,I found a 'gateaway' but I don't know if it helps : 
For GOW 3,the TSX enabled is the PB.The game works without TSX enabled.Here's the log without TSX (impossible to get a log with TSX enabled coz the emulator crashes)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3757471/RPCS3.log.gz)

For GOW Ascension,I deleted the old PPU and SPU cashes.Now,it works (I did same with GOW 3 but nothing has changed for this game : TSX is still the pb)

**Comment by RainbowCookie32** [comment]
You have TSX-FA, which is known to cause issues. If disabling TSX fixes it, then you should close the issue, and report your findings in #6028 

Also, only the compressed log is deleted when RPCS3 crashes. You still get RPCS3.log, the plain text one
