### ISSUE TITLE
Auto update: missing SSL on windows

### ISSUE THREAD

**Issue by FlorianPons** [RPCS3/rpcs3#6837]
On version v0.0.7-8977-14c63ec0_win64, I have the error "Can't update! please make sur your system supports SSL"

I have the last version of windows 10.

![2019-10-22](https://user-images.githubusercontent.com/729998/67311499-0093c480-f500-11e9-8a45-744522788b53.png)

**Comment by AniLeo** [comment]
You're missing the SSL libraries on path or local folder, ask for support on the appropriate channels.

**Comment by FlorianPons** [comment]
Yes, it's not in the quick start guide. I've download both dll libssl and libcrypto into the rpcs3 folder and now it works. This requirement must be add to the guide.
