### ISSUE TITLE
Strategy for auto updater when running rpcs3 with cli arguments

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#6839]
We need to discuss what should happen once you run rpcs3 with no GUI mode or headless mode or with any game path as boot param while the auto updater is enabled.

And noooow FIGHT !

**Comment by dio-gh** [comment]
Auto-update off by default, as CLI launch usually happens with gaming frontends, so users expect their games not to break over time. There should also be a `--force-update` startup flag added, that bypasses it and does it anyway (and fails silently if it fails).

This is my 2 cents.

**Comment by Megamouse** [comment]
Well. Headless and no-gui are not gonna do it anyway at the moment. So the actual issue is what should happen with game boot

**Comment by dio-gh** [comment]
:thinkfidget:
