### ISSUE TITLE
Unable to add Folder from UNC path in GUI

### ISSUE THREAD

**Issue by mooock** [RPCS3/rpcs3#6841]
When adding a game from an UNC path it will not appear in the GUI. and is also unable to start if pointing to the Eboot.

I tried a lot of versions until i found where it breaks., all new versions has the same issue
rpcs3-v0.0.7-8888-076a80d7_win64.7z dont Work
rpcs3-v0.0.7-8886-4d0291ed_win64.7z Works with UNC

It is possible to mount the UNC to a drive letter or do a Symlink and it will still work.

OS Windows 10 1903 build 18362.418

**Comment by AniLeo** [comment]
Closing as fixed, if you somehow can still reproduce this on latest build feel free to ping for reopening

**Comment by mooock** [comment]
Confirmed working again in v0.0.8-9349-f5cb147f
