### ISSUE TITLE
LLVM Recompiler making floating position

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#6856]
When I use LLVM Recompiler in God of War 3, it makes floating position on a special event during the game.
Kratos lose his postion and start floating in the air -> this makes the game to end (it considers Kratos as fallen).
I tried to take a pic when it happens and stop emulation to make a right log.
![GOW3LLVMFloat](https://user-images.githubusercontent.com/54372547/67438779-ac1e4100-f5f4-11e9-8e90-b9c69febc8bf.JPG)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3764794/RPCS3.log.gz)

This not happens when I use ASMJIT

**Comment by Pouncha** [comment]
@Asinin3 
This 'random issue' was each time I played it with LLVM...After 4 tries,I changed LLVM to ASMJIT and it never been again.
LLVM makes glitches and some issues effects to this game and some other anyway (see #5886)

**Comment by QuaiGoner** [comment]
I was able to pass this section on about 4th attempt on LLVM, as far as i am aware it happens because of desyncing events - the result of low FPS, it really should be closed
