### ISSUE TITLE
Final Fantasy XIII-2 cant load game save file[BCAS20224]

### ISSUE THREAD

**Issue by Myoko** [RPCS3/rpcs3#6859]
the same issues with FFXIII, i have check save manager, it's there but rpcs3 cant read it!

main menu it's no load game option
![FF13-2-1](https://user-images.githubusercontent.com/3013386/67472958-7b85e800-f684-11e9-8108-3633dc45a6e9.png)
check save manager the files exist
![FF13-2-2](https://user-images.githubusercontent.com/3013386/67472978-85a7e680-f684-11e9-8e11-32ff8b221226.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3766780/RPCS3.log.gz)

**Comment by HerrHulaHoop** [comment]
Attach your save files here as well. Might assist with testing.

**Comment by Myoko** [comment]
ok! there you go
[BCAS20224-00.zip](https://github.com/RPCS3/rpcs3/files/3767011/BCAS20224-00.zip)

**Comment by lextra2** [comment]
probably the same issue as #6610

**Comment by Myoko** [comment]
yeah! i think it is

**Comment by lextra2** [comment]
So I tested my version (BLUS30416) of FFX13 and it works just fine. This issue is most likely related to the japanese letters the asia version of these games use.

![ff1](https://user-images.githubusercontent.com/20690384/67498896-7fb00680-f680-11e9-9c7f-cbee4073d742.PNG)
![ff2](https://user-images.githubusercontent.com/20690384/67498903-82126080-f680-11e9-90c3-6b7f964f99f4.PNG)

**Comment by Myoko** [comment]
maybe the issues only exist in asia version.

**Comment by GitArUs** [comment]
I used strace to check, what two FFXIII games are doing during startup, before the main menu is displayed. FFXIII (MRTC00003, which is the same as BLUS30416 and BLES00783) lists contents of dev_hdd0/home/00000001/savedata and for every MRTC00003-xx subfolder reads files PARAM.SFO and ICON0.PNG. FFXIII-2 (BLES01269) only lists contents of dev_hdd0/home/00000001/savedata and doesn't touch anything inside any BLES01269-xx subfolders, like it was not recognising them as it's saves. However, when a new game is started, FFXIII-2 requires selecting an autosave slot and at that time it presents a list of all existing saves. So in one situation the game can not recognise its savedata, in other it can.

**Comment by GitArUs** [comment]
Could it be, that the game wants to check EVERY subfolder in savedata directory regardless of name prefix ? RPCS3 assumes that directory prefix should always be provided. According to the following log lines the same save list should be returned in both cases (cellSaveDataFixedLoad2 and cellSaveDataListSave2), but directory prefix list is empty when cellSaveDataFixedLoad2 is called (I have checked it using `std::cout << static_cast<char*>(setList->dirNamePrefix.get_ptr())`).

```
·W 0:00:24.985082 {PPU[0x1000007] Thread (GameInitializer) [HLE:0x0156487c, LR:0x00c1bac0]} cellSaveData: cellSaveDataFixedLoad2(version=0, setList=*0xd0058b10, setList->dirNamePrefix.get_ptr=*0x3d0058ba8, dirNamePrefixContent=, setBuf=*0xd0058b30, funcFixed=*0x116e508, funcStat=*0x0, funcFile=*0x0, container=0xffffffff, userdata=*0x0)

·W 0:00:34.674381 {PPU[0x1000007] Thread (GameInitializer) [HLE:0x015648b4, LR:0x00c1baf8]} cellSaveData: cellSaveDataListSave2(version=0, setList=*0xd0058b10, setList->dirNamePrefix.get_ptr=*0x3d0058ba8, dirNamePrefixContent=BLES01269-, setBuf=*0xd0058b30, funcList=*0x116e4e0, funcStat=*0x116e4c8, funcFile=*0x116e498, container=0xffffffff, userdata=*0x0)
```

When I do something like the following in savedata_op function, saves work properly:
```
               //const auto prefix_list = fmt::split(setList->dirNamePrefix.get_ptr(), {"|"});
               const auto prefix_list = fmt::split("BLES01269-", {"|"});
```
Of course the reason for which dirNamePrefix is empty may be burried somewhere deep in the code (rpcs3 code or game code), but I'm unable to find out how dirNamePrefix gets its contents.

**Comment by bnthomason** [comment]
@GitArUs How do I append this fix?

**Comment by digitaldude555** [comment]
Retest its in master build now @bnthomason @Myoko @PlatinSource

**Comment by PlatinSource** [comment]
The Game now lists and loads all savefiles properly. At least for the EU Version, can't say anything about the asian version.

**Comment by Megamouse** [comment]
apparently works
