### ISSUE TITLE
NCAA Football 14 BLUS31159 Black Field in Daytime Games

### ISSUE THREAD

**Issue by connorwalks** [RPCS3/rpcs3#6861]
RPCS3-v0.0.7-8981
Intel i9 9900K 
16 GB 3000MHz DDR4 
NVIDIA RTX 2080 (Driver 436.48)

Game is playable when NIGHT games are played, however, during day games the field turns completely black. This issue does not seem to plague any other version of NCAA Football (tested 09-14 and this was the only game affected).

[Here is video showcasing loading into a night game and then loading into a day game after](https://youtu.be/Hsgszq_3-Os)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3768334/RPCS3.log.gz)

**Comment by connorwalks** [comment]
UPDATE: Disabling asynch shader compiler fixes this issue. Results in lower FPS but this solves the "black field glitch" for now

**Comment by kd-11** [comment]
Close the issue then.

**Comment by connorwalks** [comment]
> 
> 
> Close the issue then.

I was going to but someone in the discord channel told me that having the option enabled should not be necessary and that I should update the issue but NOT close it. If this is incorrect though I will close it. Just let me know

**Comment by kd-11** [comment]
Async compiler is expected to cause missing visuals. The only way to fix it needs a few more months of work.
