### ISSUE TITLE
Linux compilation now failing

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#6868]
Linux compilation now fails on today's code commits.  Based on the log below, the suspect is the FAudio commit 06433d614acdb46ba4a7f8635445eafe8038d0bd, which apparenlty can't deal with SDL 2.0.8 which is shipped with Ubuntu 18.04 based distros such as this one (@Oschowa any way to make SDL2 part of RPCS3's 3rdparty libs, or at least bump the requirement down to 2.0.8?). Log:
```
/home/shoegzer/Desktop/rpcs3/rpcs3/3rdparty/FAudio/src/FAudio_platform_sdl2.c: In function ‘FAudio_PlatformInit’:
/home/shoegzer/Desktop/rpcs3/rpcs3/3rdparty/FAudio/src/FAudio_platform_sdl2.c:101:9: error: expected expression before ‘#pragma’
  101 | #pragma message("Please update to SDL 2.0.9 ASAP!")
      |         ^~~~~~~
3rdparty/FAudio/CMakeFiles/FAudio.dir/build.make:446: recipe for target '3rdparty/FAudio/CMakeFiles/FAudio.dir/src/FAudio_platform_sdl2.c.o' failed
...
[  8%] Built target asmjit
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```
Note that this issue can be easily resolved with an update to [SDL2](https://www.libsdl.org/download-2.0.php), and has been tested here and found to work fine.  However I opened this issue out of awareness that the majority of linux users will fail initially until this is done, in case there's a way to resolve this in some other way.

Specs: Linux mint 19.2, kernel 5.0, gcc 9.2.1

**Comment by Nekotekina** [comment]
Should be fixed now

**Comment by Shoegzer** [comment]
@Nekotekina ah, thanks.  I had just updated the issue.  I'll close it now.
