### ISSUE TITLE
Cannot apply patches using patch.yml

### ISSUE THREAD

**Issue by fletcher89** [RPCS3/rpcs3#6876]
### Setup

**CPU**: AMD Ryzen 1700
**GPU**: NVIDIA GTX 1070
**RAM**: 8 GB DDR4 @ 2667MHz
**OS**: Windows 10 Version 1903
**RPCS3 Version**: RPCS3 Version: 0.0.7-9007-f3ed26e9 Alpha

### Description

The Issue I'm having is with the patch.yml file.
RPCS3 doesn't seem to load it for me at all.
I've tried patches for both Drakengard 3 and Demon's Souls.
Both games don't get the patches applied.

Here's a log from one launch: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3773995/RPCS3.log.gz)

### What have I tried to fix the issue

I talked to a few people on the Discord about the issue and tried a few things.

* Made sure the file is actually called patch.yml (not patch.yml.txt or anything similar)
* Checked the PPU Hashes for patches and games
* Updated RPCS3 - I had an older build at first
* Fully re-installed (i.e. deleted the RPCS3 directory)
* Tried game specific patch.yml (`<rpcs3>/data/<title>/patch.yml`)
* Set the `RPCS3_CONFIG_DIR` environment variable to a different directory and put the patch.yml there to see if that changes anything.

### Additional Notes

I'm not a C++ developer (nor am I familiar with Windows besides using it to play games), so take this with a large grain of salt, but maybe it helps. I dug through the code a bit to see if I could identify the issue myself. To me it _looks_ like the log should actually output something if the patch.yml couldn't be parsed in case the YAML is invalid. So I changed the patch.yml to something invalid and started the games again. The log didn't contain the error I had found in the code. This leads me to believe that the issue happens earlier in the code, before actually parsing the patch.yml. It doesn't even seem to be able to open/access the file.

**Comment by fletcher89** [comment]
Took me longer than it should have, but I was able to make RPCS3 load the `patch.yml` by converting the file to Windows Style line endings.

I'm closing this.

**Comment by Snakeraiden** [comment]
> Took me longer than it should have, but I was able to make RPCS3 load the `patch.yml` by converting the file to Windows Style line endings.
> 
> I'm closing this.

I'm having the same issue on a RPCS3 custom build made for MGS4 and based on the 0.08 official build (no patch manager).
Could you PLEAAAASE explain to me in a bit more detail what you did in order to solve the problem ? I'm not very familiar with coding so I wasn't able to apply what you described as "converting the file to windows style line endings".

Thanks a bunch
