### ISSUE TITLE
Madden NFL 09 [BLUS30146] increasing resolution scaling makes game more pixelated

### ISSUE THREAD

**Issue by connorwalks** [RPCS3/rpcs3#6878]
RPCS3-v0.0.7-9007
Intel i9 9900K 
16 GB 3000MHz DDR4 
NVIDIA RTX 2080 (Driver 436.48)

Setting the resolution scaling to anything above 100% seems to cause extreme pixelation, making the game look even worse than it does at 100% scaling. 

This issue seems to also plague NCAA Football 09 [BLUS30155]. Let me know if you want screenshots and video of that game too, but in this report I have only included evidence of the issue in Madden 09.

For reference, here are screenshots showing the game when scaled to 300%:

![1](https://user-images.githubusercontent.com/48158481/67608742-907f7b80-f757-11e9-98df-7bb79a459825.jpg)
![2](https://user-images.githubusercontent.com/48158481/67608743-92e1d580-f757-11e9-84d3-534f943ec0a3.jpg)

Here is the game being scaled at 100%:
![3](https://user-images.githubusercontent.com/48158481/67608925-69757980-f758-11e9-875b-b27a7144c340.jpg)

Notice how the grass at 100% does not cause eye strain (more noticeable in the video), and how there is no major pixelation beyond what you would expect at 720p.

[Here is a video showing me running the game at three different resolutions](https://www.youtube.com/watch?v=01eqbaw246E)

Here is the log from the video: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3774089/RPCS3.log.gz)

 The first run in the video is at 300% scaling, the second is at 150% and the third is at 100% for reference. Please ignore the red hue in the third run at 100% scaling, that is a totally separate issue for now. Let me know if you need something like an RSX capture at each level, thanks!

**Comment by cooperate** [comment]
Can confirm the same thing is happening in NHL games.

**Comment by nsoeth** [comment]
any updates on this? NHL Legacy has the same problem as has NHL 14. NHL 12 is working fine.

**Comment by kd-11** [comment]
Not all games can be upscaled without issues. There is nothing we can do to fix the issues officially but community patches can be applied to these games to bypass whatever post-processing effect is causing issues.
Also, 150% and 300% are terrible scaling options, try 200% first. Scaling factors that are not based on even sample grids such as 2x2 or 4x4 will cause issues with some algorithms such as anti-aliasing.
