### ISSUE TITLE
Read of uninitialized base_offset in VKGSRender::update_vertex_env

### ISSUE THREAD

**Issue by Cebtenzzre** [RPCS3/rpcs3#6880]
https://github.com/RPCS3/rpcs3/blob/f7842b765f0490e85a993eb84515c911fb426ccd/rpcs3/Emu/RSX/VK/VKGSRender.cpp#L2743-L2747
https://github.com/RPCS3/rpcs3/blob/f7842b765f0490e85a993eb84515c911fb426ccd/rpcs3/Emu/RSX/VK/VKGSRender.cpp#L2754-L2755

If this branch is taken, then either `m_vertex_layout_storage` was null or `m_vertex_layout_storage->in_range` returned false. In both cases, `base_offset` is still uninitialized by the time its value is read on lines 2754 and 2755.

This behavior was introduced by commit 6a32f716db2dc5989b1c3802c55317455b157043.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/6890/commits/4872d1ab5b00fe2646dbb8ba6784a4b259ad5ff6. I didn't even want to access base_offset; I'm surprised things didn't completely break.

**Comment by kd-11** [comment]
Closing as fixed by https://github.com/RPCS3/rpcs3/pull/6890
