### ISSUE TITLE
[Regression] PR #6757 broke Backbreaker games

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#6884]
Game crashes on boot now with a PPU mem error. Caused by: https://github.com/RPCS3/rpcs3/pull/6757

Broken: 0.0.7-8945
Fine: 0.0.7-8944

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3774333/RPCS3.zip)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by elad335** [comment]
retest with #6862

**Comment by legend800** [comment]
Still crashes with a mem error:

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3774480/RPCS3.zip)

**Comment by elad335** [comment]
lol, try now.

**Comment by legend800** [comment]
Yep, works perfect again on the new commit. Thanks for the quick fix!
