### ISSUE TITLE
Lightning Return FFXIII the shadow issues[BCAS20279]

### ISSUE THREAD

**Issue by Myoko** [RPCS3/rpcs3#6886]
LR FFXIII Messy shadow in everywhere! you just push right analog and you can see it

![LRFFXIII](https://user-images.githubusercontent.com/3013386/67613920-1944f880-f7e6-11e9-8211-95653d407530.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3774414/RPCS3.log.gz)

i have recording video
https://streamable.com/dq71x

**Comment by elad335** [comment]
Duplicate if #8603
