### ISSUE TITLE
Graces f (BLUS30903) Crash and Freezing to Save Game from Internet (and Gameplay)

### ISSUE THREAD

**Issue by JoNuttanon1994** [RPCS3/rpcs3#6887]
Tales of Graces f BLUS30903

F {PPU[0x1000000] Thread (main_thread) [0x0031ee88]} MEM: Access violation reading location 0x6a3752f8

os: windows 10 pro 64-bit
cpu: intel pentium g3220 3.0ghz
mb: asrock h81m-vg4
ram: kingston 8gb ddr3
gpu: asus geforce gtx 650 1gb
psu: 600w great wall gw-600se
hdd: wd 1tb 7200rpm sata iii WD10EALX-009BA0
ssd: hikvision c100 120gb sata 3d nand

**Comment by AniLeo** [comment]
No emulator issue here, you either have encrypted or corrupted save data.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
