### ISSUE TITLE
Choplifter HD [NPUB30619] RenderingThread: Access violation reading 0x10

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6891]
black screen 
·F 0:00:53.995682 {PPU[0x1000012] Thread (RenderingThread) [0x008e3338]} MEM: Access violation reading location 0x10
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3774736/RPCS3.zip)

**Comment by AniLeo** [comment]
Needs information on what is causing this access violation

**Comment by benderscruffy** [comment]
goes ingame again
![choplifter](https://user-images.githubusercontent.com/2696404/72196640-cda10300-3454-11ea-9569-8b54cf7ef00a.PNG)
