### ISSUE TITLE
UI: Maybe include change log / release notes functionality to the auto-updater window

### ISSUE THREAD

**Issue by rdeleonp** [RPCS3/rpcs3#6893]
Visual examples below.

**RPCS3 (none):**

![RPCS3](https://user-images.githubusercontent.com/20749249/67623759-b572fd80-f7ee-11e9-8f8a-62c20d251dba.jpg)

**CEMU (OK-ish):**

![CEMU](https://user-images.githubusercontent.com/20749249/67623760-b7d55780-f7ee-11e9-979f-276db3c8d649.jpg)

**Dolphin (better):**

![Dolphin](https://user-images.githubusercontent.com/20749249/67623761-b9068480-f7ee-11e9-9072-4b08a573c203.jpg)

**Comment by dio-gh** [comment]
We don't have changelogs for every release. We could do what Dolphin does though.

**Comment by rdeleonp** [comment]
> @dio-gh:
> _We don't have changelogs for every release. We could do what Dolphin does though._

Thanks for considering it.

Bellow is a quick mock-up of how the "Release Notes" area could look like; maybe it could work as a base:

![RPCS3 update change log mockup](https://user-images.githubusercontent.com/20749249/67624954-57014b80-f7fd-11e9-95d7-bace50b31787.png)

**Comment by AniLeo** [comment]
I'll look into adding the pull request names into our database and expose them through the API

**Comment by Asinin3** [comment]
https://github.com/RPCS3/rpcs3/pull/10844 Already being looked at

**Comment by Asinin3** [comment]
Closing, pr merged
