### ISSUE TITLE
id_traits is defined incorrectly

### ISSUE THREAD

**Issue by Cebtenzzre** [RPCS3/rpcs3#6896]
Commit 4599d5841353fdf8096191c30a592fedc844efce an incomplete/incorrect fix.

In IdManager.h, `id_traits` has its static variables assigned inline, right where they are declared.  This is incorrect unless the `inline` keyword is used.  I'm not a C++ expert but the current code may violate the One Definition Rule.  Without the `inline` keyword, the linkage works strangely, which is the source of the undefined reference error on debug builds.

One solution besides `inline` would be out-of line declarations of the static variables, but this is tricky because of the `void_t`.  Once implemented, this solution causes gcc to complain about the use of non-`contexpr` variables in the `static_assert`, so it does not work.

The best solution IMO is to replace the `const` keyword with `constexpr` for `base`, `step`, `count`, and `invalid` in both specializations of `id_traits`.  This makes the `static_assert` in the second class template valid, and it also fixes the undefined reference error.

Regardless, a new local variable in the destructor of `sys_vm_t` is not a good fix.

**Comment by bevanweiss** [comment]
Hi @Cebtenzzre, it would be great if you'd be willing to put together a PR for the fix that you propose.

**Comment by Cebtenzzre** [comment]
@bevanweiss Actually, my suggested fix was already implemented as part of 3265772ae4d5dc32fcd499c276f20f110c3bedd1, though probably discovered independently. But I still think 4599d5841353fdf8096191c30a592fedc844efce should be reverted.

**Comment by bevanweiss** [comment]
@Cebtenzzre You could submit a PR that does this reversion :)  if it builds under the CI bots then it might make it in..
