### ISSUE TITLE
Final Fantasy XIII - Fails to load Lake Bresha zone

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#6899]
The zone fails to load, leaving the emulator with a black screen, which prevents me from progressing any further.

Apparently not everyone has this issue as [this person](https://youtu.be/cqY3et5HrUo) seems to be able to progress further into the game.

[Savedata](https://drive.google.com/file/d/1vRTkVDeznj3b6IoyKsU5sEMuJXkyzFQq/view)
[Logs](https://drive.google.com/file/d/1wDRVxF2rDQ3O5dBelJQRcIlBXVLalRdJ/view)

**Comment by Asinin3** [comment]
Can you provide a save file please?

**Comment by lextra2** [comment]
Yes. Of course.
[Here you go.](https://drive.google.com/open?id=1vRTkVDeznj3b6IoyKsU5sEMuJXkyzFQq)
Actually all my save files. I saved on every new save point or when asked to save. Conveniently the game asks to save right before the Lake Bresha zone. Which is MRTC00003-15

**Comment by digitaldude555** [comment]
@lextra2  how about now?

**Comment by lextra2** [comment]
@digitaldude555 sorry for the late reply. And nope, I'm still stuck in an infinite black loading screen.

**Comment by lextra2** [comment]
So I got fed up with seeing others get past this zone but not me, and decided to re-dump the game. Works now. No longer stuck after the cutscene. Closing.
