### ISSUE TITLE
Williams Pinball Classics [BLES01051] cannot start a new game (doesnt detect when you press the start button on USB game controller)

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6902]
doesnt detect when you press the start button on USB game controller
![williams](https://user-images.githubusercontent.com/2696404/67634525-26eaa300-f8f8-11e9-8c77-d271b8f1adcd.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3775832/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
Works now close it.

**Comment by AniLeo** [comment]
Closing as fixed

**Comment by benderscruffy** [comment]
this is not fixed 
please reopen

**Comment by benderscruffy** [comment]
this could be related to #6093

**Comment by benderscruffy** [comment]
@AniLeo this is not fixed
please reopen

**Comment by benderscruffy** [comment]
has been fixed
