### ISSUE TITLE
[Linux] Ratchet and clank trilogy graphical problems

### ISSUE THREAD

**Issue by InfamousKnight** [RPCS3/rpcs3#6904]
Before I begin, here are my specs:

Notebook
--
product: | HP Pavilion Laptop 15-cs0xxx (4AL57UA#ABA)
vendor: | HP

CPU
--
product: | Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
vendor: | Intel Corp.
physical id: | 4
bus info: | cpu@0
version: | Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
serial: | To Be Filled By O.E.M.
slot: | U3E1
size: | 1545MHz
capacity: | 4005MHz
width: | 64 bits
clock: | 100MHz
cores | = | 4
-- | -- | --
enabledcores | = | 4
threads | = | 8

intel UHD Graphics 620   33MHz

Running ubuntu 19.04 64bit

With vulkan turned on, it shows a black screen once RC1 boots but audio plays in the background. If I turn on opengl, the graphics flicker from the very beginning to in game. I also have multithreaded RSX enabled.

**Comment by AniLeo** [comment]
Needs checking on non-Intel cards, as Intel iGPUs are not supported. It's known that latest Mesa (padoka or stable) doesn't behave very well with RPCS3's renders, I also get a bunch of issues when testing a HD 530.

**Comment by InfamousKnight** [comment]
Has anyone managed to get this running on intel GPU's? Well, as in at a good frame rate at the very least.

**Comment by Cervoxx** [comment]
The game runs on my GTX 1080.

**Comment by AniLeo** [comment]
Mesa 20.0.5, HD 530, RPCS3 0.0.9-10298

Multithreaded RSX: On

![image](https://user-images.githubusercontent.com/10283761/80678711-61094d00-8ab3-11ea-9be5-872b70a9a29b.png

No issues with the Intel driver nor with the game itself, rendering correctly. Closing.
