### ISSUE TITLE
Linux: RPCS3 with FAudio will not start if rpcs3 binary is moved

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#6906]
After compiling rpcs3 with FAudio, then moving the rpcs3 binary to another location, then deleting the original source directory, rpcs3 will not start.  The following exception is thrown:

`/home/shoegzer/RPCS3/bin/rpcs3: error while loading shared libraries: libFAudio.so.0: cannot open shared object file: No such file or directory
`

Before FAudio was added, rpcs3 binary could be moved anywhere outside of source tree and then source tree deleted without causing any issues. 

Test system is Linux Mint 19.2 with kernel 5.0 and gcc 9.2.1.  SDL 2.10.0 is installed.

**Comment by jbeich** [comment]
Also affects FreeBSD. Workaround is to install system faudio package. However, unless RPCS3 builds against system headers this may lead to ABI mismatch.
[![Packaging status](https://repology.org/badge/vertical-allrepos/faudio.svg)](https://repology.org/project/faudio/versions)

**Comment by Shoegzer** [comment]
Yup.  Another workaround can be to move the libFAudio.so.0.19.10 out of the source directory into your path (install directory) and rename to libFAudio.so.0.  It just shouldn't be necessary - this really should be fixed so rpcs3 can find the library properly like the others.

**Comment by jbeich** [comment]
Likely fixed by #7530.

**Comment by Shoegzer** [comment]
Thanks, you're right.  Closing this.
