### ISSUE TITLE
[Bounty: $75 USD] [Feature Request] Ability to track and display Time Played

### ISSUE THREAD

**Issue by ipkpjersi** [RPCS3/rpcs3#6909]
Hi there,

I have an idea for a feature for RPCS3. I checked and haven't found this idea suggested before but if it has been posted anywhere and I missed it, I do apologize.

I think that RPCS3 should have a column in the game list for displaying time played, much like other modern launchers like Origin, Steam, even open-source ones like Lutris have. It could just be a simple text-only column like a bunch of the other columns that already exist in RPCS3 game list window. I think this is a useful feature that encourages players to be more engaged, and if gamers are anything like me then this is a very important feature that is really interesting. Sure, some games track this information in-game but I feel it's much better to have this at a global level. To start I think it could just use local storage to store the time played, but maybe later on this could somehow have cloud synchronization so players can have their play time saved from any PC they use RPCS3 on.

Here's a couple of examples of what I am talking about:
![](https://i.imgur.com/FyAdqRe.png)
![](https://i.imgur.com/9Kx7DBV.png)
![](https://i.imgur.com/u1ZIEGf.png)

A couple of ways I think this might be able to be implemented would be storing the timestamp when you start a game and the timestamp when you stop a game. However, I think a better (but possibly slightly more challenging way) of doing this would be having a timer running for a game when you have the game running.

Does anyone have any thoughts on this? I don't think this would be too hard to implement, but I'm not a C++ developer so I can't say for sure if it would be hard or not. Since this code would likely be decoupled from the game emulation code since it's not like fixing one game, realistically it should be easier to test since it basically shouldn't have any chance of breaking emulation for any games. I think this is definitely worth investigating. 

Thank you for your time.

Edit: In order to generate more interest for this, I've posted a $60 USD bounty to be claimed here https://www.bountysource.com/issues/82730799-feature-request-ability-to-track-and-display-time-played for anyone who is willing to do this.

Edit 2: Bountysource themselves have now added an additional $15 USD, the bounty is now $75 USD for anyone who is willing to implement this feature.

**Comment by Resident007** [comment]
Good idea though. Another example is Cemu, which also has this column.

**Comment by purifiedh2o** [comment]
Should this be closed now?

**Comment by Atrosincity** [comment]
Another cool feature i've seen in some emulators is savestates, it would be awesome if can resume instantly to my boss fight after a while! cooler if with many slots.

**Comment by Leopard1907** [comment]
RPCS3 does not implement save states, and if it ever happens, it won’t be as useful as you’d think.

Consider that PS3 has 512 MB RAM (split in two 256 MB regions), plus cpu state, plus emulator state. And that’s just for saving/loading I/O bandwidth.

On top of that, you can only accurately save and restore save state when you’re using interpreters, due to complexity of tracking and mapping the emulated and native code states to each other, when using recompilers.

Copy pasta from Rpcs3 bot.

Good bot

**Comment by purifiedh2o** [comment]
PS3 is a complex console (even Sony has hard time making it backward compatible on PS4), implementing savestate is not practical. And further console generations won't implement this either. Due to this, I think savestate is the last priority.
