### ISSUE TITLE
EA sports fighting games ( EA MMA, Fight Night Round 3, FNR 4 and FN Champion) don't display textures for created fighters

### ISSUE THREAD

**Issue by libal44** [RPCS3/rpcs3#6910]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3778624/RPCS3.log.gz)

Version v0.0.7-9024 Alpha
Pull Request #6907 (69e9ee26)

Windows 10 
I7 9700
RX 470 4GB
8GB RAM

Fighting games from EA Sports don't display the faces and sometimes the bodies of created fighters - this if for the ones the player creates himself or the pre-made ones that you play against in Career mode. Instead of the proper textures, the body / face appears all black. 

This bug can be seen in EA MMA, Fight Night Round 3, Fight Night Round 4 and Fight Night Champion. All these games can be playable if not for this bug since it makes Career mode unplayable.

Easiest way to see the bug is to start a Career or to quickly create a boxer / fighter and start an Exhibition match with him.

![Untitled3](https://user-images.githubusercontent.com/57097173/67678600-b7c08d80-f98f-11e9-8695-29f89c755090.jpg)
![Untitled](https://user-images.githubusercontent.com/57097173/67678601-b7c08d80-f98f-11e9-8b16-595a03437b5e.jpg)
![Untitled1](https://user-images.githubusercontent.com/57097173/67678603-b7c08d80-f98f-11e9-82cc-1c2f23da38a9.jpg)
![Untitled2](https://user-images.githubusercontent.com/57097173/67678604-b8592400-f98f-11e9-8736-0ec339392a1d.jpg)

**Comment by kd-11** [comment]
Need an RSX capture dump from an affected scene, preferrably with both a good and bad character in it (the example scene in the screenshots will suffice). You can get assistance on our discord server on how to generate the file.

**Comment by libal44** [comment]
Hello kd-11, thank you for taking an interest in this problem. Here is a capture from FNR 4 and FNC. The  bigger file is from Champion.

Had to upload to my google drive as its a big file:
https://drive.google.com/file/d/1T7cxH9EcHSHrmE4DkkeYvp9PwnXtmjKp/view?usp=sharing

**Comment by Silanda** [comment]
Have you tried disabling async shader compilation? IIRC I had to do that for FNR4 to avoid this problem. Not that it matters too much as the game's still broken anyway (opponents tend to stop punching and evasion stops working after someone gets dizzied, music doesn't stop and start correctly, etc).

**Comment by kd-11** [comment]
So the rendering is technically correct. The custom face is supposed to generate a face UV texture but this data is missing, probably supposed to be procedurally generated. The texture passed is never initialized so you get black output.
There are 2 possibilities here:
1. The game uses the GPU to generate the textures. In this case, you need to test with write color buffers and possibly read color buffers enabled.
2. The game uses the CPU to generate the textures. In this case, I have no idea what would fix it as it would require disassembling and reversing the game logic.
