### ISSUE TITLE
Dead Nation - Fatal Error, only sometimes

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#6915]
Dead Nation sometimes reports a Fatal Error when building the cache upon going in-game for the first time. I've seen the same thing happen for a couple of other games as well, like Final Fantasy 13 or Tales of Xillia.

It dosen't always happen but still frequently enough. Also, the games don't straight up freeze, but still continue to run for a while until RPCS3 eventually closes itself. They can still be played fine without the fatal error ever appearing again after restarting the emulator.

![Fatal Error](https://user-images.githubusercontent.com/20690384/67766803-945d1780-fa4f-11e9-9c9d-4e4b2d7f6969.png)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3783498/RPCS3.zip) (Log file)
[Windows Event Viewer.txt](https://github.com/RPCS3/rpcs3/files/3783499/Windows.Event.Viewer.txt)

I've included the error report from the Windows Event Viewer as well. Not sure how useful that one is though.

**Comment by Shoegzer** [comment]
Confirmed.  This might happen in all games (it happens on every game tested here), and in Linux as well (tested with Linux Mint 19.2, kernel 5.0, self-compiled using gcc 9.2.1).  

@lextra2 you might consider removing "Dead Nation" from the issue title and just add it to your list of games where you've observed this occurring.

**Comment by dio-gh** [comment]
Couldn't repro on my i5 4440, which is a CPU where you'd definitely expect something like this to creep up. Unless it's reliably reproducable, the issue is very vague and there's no point in keeping it open.

**Closeable.** Can be reopened if a somewhat reliable repro method is found (or a person who can somewhat reliably repro).

**Comment by RainbowCookie32** [comment]
Also couldn't reproduce while testing for #6817

**Comment by lextra2** [comment]
just for the record, I have not gotten a fatal error in any of the games mentioned in the op since 0.0.9 onwards. some shader cache optimizations must have fixed it.
