### ISSUE TITLE
Atelier game and Tales of xillia 1 Anti alliasing problem on Rx 5700 xt

### ISSUE THREAD

**Issue by walikour** [RPCS3/rpcs3#6920]
Well this is my very first post on github so be lenient on me if i forget something, thanks.
Here is my configuration taken from the log:

RPCS3 v0.0.7-9047-35794dc3 Alpha | HEAD | Firmware version: 4.85
AMD Ryzen 7 3700X 8-Core Processor | 16 Threads | 15.92 GiB RAM | TSC: Bad | AVX+
Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0
·! 0:00:00.000000 RSX: Found vulkan-compatible GPU: 'AMD Radeon RX 5700 XT' running on driver 2.0.106

Here are the pictures of before and after i disable anti alliasing in atelier ayesha, the one with the diagonal bar are with anti alliasing on and the others clearer are with anti alliasing off.
I have the same problem on all the atelier game.

![2019 10 30-00 56_01](https://user-images.githubusercontent.com/57159438/67818503-c30bda00-fab1-11e9-944b-15c8f3fede65.png)
![2019 10 30-00 55](https://user-images.githubusercontent.com/57159438/67818504-c30bda00-fab1-11e9-8ae0-7c9826a1c683.png)
![2019 10 30-00 55_01](https://user-images.githubusercontent.com/57159438/67818505-c3a47080-fab1-11e9-8d68-00eea741ee30.png)
![2019 10 30-00 56](https://user-images.githubusercontent.com/57159438/67818507-c3a47080-fab1-11e9-8bf6-53103f038c06.png)

I doesn't end here, here are the pictures of tales of xillia 1, keep in mind that the resolution is at 2160p in 720p there isn't much difference except the character selection (i only tested the begining of the game), the messed up image is when anti alliasing is on auto.

![2019 10 30-01 11_01](https://user-images.githubusercontent.com/57159438/67818719-94423380-fab2-11e9-8651-6b33d7349245.png)
![2019 10 30-01 11_02](https://user-images.githubusercontent.com/57159438/67818720-94423380-fab2-11e9-84a8-66d24d1d075e.png)
![2019 10 30-01 10](https://user-images.githubusercontent.com/57159438/67818721-94423380-fab2-11e9-8784-6a30e89bb247.png)
![2019 10 30-01 11](https://user-images.githubusercontent.com/57159438/67818723-94daca00-fab2-11e9-8266-c9c8440cab62.png)

**Comment by lextra2** [comment]
I can not replicate the issue with my rx 580. So it might be a driver issue or an issue exclusive to navi.
What is your driver version? Mine is 19.9.2. Have you tried another driver?

**Comment by kd-11** [comment]
Polaris and vega seem to be ok, looks to be something exclusive the navi series of cards.

**Comment by walikour** [comment]
> I can not replicate the issue with my rx 580. So it might be a driver issue or an issue exclusive to navi.
> What is your driver version? Mine is 19.9.2. Have you tried another driver?

Mine is 19.9.2 too and it doesn't work

> Polaris and vega seem to be ok, looks to be something exclusive the navi series of cards.

Maybe for know i don't encounter to much problem in other games so i will avoid updating my drivers, who know what new bug could be added, i will wait until we are a few more month after the release to update them again.

**Comment by kd-11** [comment]
Can you try disabling the 'native fp16 support' option in the config file? May be something simple (hopefully)

**Comment by kd-11** [comment]
It would also be helpful to get someone with navi on linux with the RADV driver to check if it is also affected.

**Comment by mignolo4** [comment]
> Can you try disabling the 'native fp16 support' option in the config file? May be something simple (hopefully)

it's the same for me even with fp16 off; it only changes when MSAA is OFF
radeon rx5700xt with 19.11.1 (they added something for vulkan compatibility)

**Comment by kd-11** [comment]
Let's move this discussion to https://github.com/RPCS3/rpcs3/issues/6999
