### ISSUE TITLE
No digital right input on gamepad after #6593

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#6922]
Archlinux, xbox controller (or arcade stick).
After #6593 , with the gamepad test application, I can't register the digital right input.
Was ok on rev8744, but the problem appears on rev8748

**Comment by Megamouse** [comment]
This isn't really helpful as it gives no information about anything. no log. no config, no settings...

**Comment by toccata10** [comment]
Fixed now (maybe with #6950)
