### ISSUE TITLE
Update WIKI page : controller configuration

### ISSUE THREAD

**Issue by fraf** [RPCS3/rpcs3#6944]
Hi retro gamerz,

Can somenone with enough privileges update the wiki page about controller help for RPCS3 :
https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration
Particularly, the dualshock 3 supports part. The wiki page recommends to install PSNow bundle sofware to install official Dualshock 3 drivers which are the ones supported by RPCS3.
It is ok, but can someone directly upload the actual drivers bundle integrated into the FAT and useless psnow executable. 
Here you will find the two zipped drivers : there are two versions : 2.5 and 3.0 :
https://darkcloud.forumcommunity.net/?t=56241030
If someone can upload both in the wiki page it will be kind.

Thanks.

**Comment by HerrHulaHoop** [comment]
Anyone can update the Wiki. Just create an account and submit an edit.
Please close this issue. The GitHub issue tracker is not the right place to discuss this. Join our [Discord server](https://discord.me/rpcs3) if you want to talk about this.
