### ISSUE TITLE
RTX 2070 SUPER and AMD RYZEN 2700X cracking bad FPS

### ISSUE THREAD

**Issue by AizerMortenort** [RPCS3/rpcs3#6954]
I updated my gpu to RTX 2070 SUPER GAMING OC from my NVIDIA 1060 GAMING OC and the fps I get now are lower and sound is cracking?
What can cause this?

Before i get solid 60 fps on most of my games now fps drop like and audio is terrible. No settings help 

CPU RYZEN 2700X
RAM 16 GB 3200Mhz
X470 ASROCK SLI MOBO

GAME In test DYNASTY WARRIORS GUNDAM REBORN
GUNDAM EXTREME VS FULL BOOST

**Comment by AizerMortenort** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3814104/RPCS3.log)

**Comment by 13xforever** [comment]
github is not for support, use the appropriate channel on [discord](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/forum-18.html)

please close this issue

**Comment by kd-11** [comment]
OP has a framelimit of 59.94hz AND display has double-buffered Vsync enabled at 60.00hz. You're basically just going to get 30fps if you do that in any application. Disable framelimit or vsync or set vsync mode to "fast" in nvidia control panel.

**Comment by AizerMortenort** [comment]
@kd-11 
i FOUND the fix is to always go to task manager and open SETUP CPU AFFINITY and then just press apply thing. I wonder do RPCS3 changes affinity?

**Comment by AizerMortenort** [comment]
And why the hatred here? Someone asking for help and you all dislike ... MOTHERFU....

**Comment by RainbowCookie32** [comment]
Because, as 13x already said, this is not the channel to ask for help. 
Our Discord server or the forums are the place for that.

**Comment by AizerMortenort** [comment]
Your discord servers are useless . No one cares what feedback people give. I am still waiting for old issue to be fixed and will wait for eternity. Still I DON'T HATE on people if they ask for help. Its enough to have manners and politely tell them where to post stuff instead of making them feel like shit for asking for assistance here.
my two cents to all of you.

**Comment by RainbowCookie32** [comment]
Well, if you don't want to ask for help on our server because they are "useless", then don't fill our issue tracker with your garbage issues

**Comment by AizerMortenort** [comment]
I think the only garbage here is the one ABOVE me.

**Comment by illusion98** [comment]
Deleting comments now 😥
