### ISSUE TITLE
Gran Turismo 5 - LAN function

### ISSUE THREAD

**Issue by jenci8888** [RPCS3/rpcs3#6957]
Me and my friends have discovered the hidden LAN functional on Gran Turismo 5 (2.11 game version.)
Here are some pictures, what my friend did on PS3 real hardware, so they did worked pair PS3.
Since it's very possible to do 16 players maximum via LAN.
- [x] Needs to get working LAN.
- [x] Needs to get working 2 or more players in LAN. (Partially, but I'm having issues with firewall right now.)
<details>
 <summary>PS3 Real hardware tested pictures: (click here to show pictures)</summary>

 ![image](https://user-images.githubusercontent.com/40495799/68321914-cfe88900-00c2-11ea-96fa-b82869c06d80.png)
 ![image](https://user-images.githubusercontent.com/40495799/68321924-d4ad3d00-00c2-11ea-878f-e72ce464bc6a.png)
 ![image](https://user-images.githubusercontent.com/40495799/68321976-e1ca2c00-00c2-11ea-8b98-f2cacdcd57cd.png)
 ![image](https://user-images.githubusercontent.com/40495799/68321982-e42c8600-00c2-11ea-829c-fb214c26a4d6.png)

</details>

Then I tried to try out RPCS3 emu myself.
![image](https://user-images.githubusercontent.com/40495799/68322086-15a55180-00c3-11ea-9183-c1e493d76f2e.png)
![image](https://user-images.githubusercontent.com/40495799/68322096-18a04200-00c3-11ea-9f8e-bd8416107025.png)
And gave me error the network error, also here's log: [RPCS3.gz](https://github.com/RPCS3/rpcs3/files/3815891/RPCS3.gz)

I wonder, it would be nice adding the LAN support in long-term plan.

**Comment by Resident007** [comment]
Shouldn't RPCS3 be able to work with LAN and network (besides PSN) already?

**Comment by SirGouki** [comment]
From what I've read in the settings, the LAN stuff is dummied in.  You can simulate it grabbing an IP address (which it forces to whatever is set in the .conf file), and thats it.  No actual network activity ever occurs, to include verifying DLC and such.  RPCS3 does use the internet to check for updates for RPCS3, and the compatibility database, but that appears to be all.

Source:  Hover on the GUI config option for network where the drop down is:
![image](https://user-images.githubusercontent.com/11664236/70822059-42274a00-1da2-11ea-9d53-b3836b3220c0.png)

**Comment by Satan86** [comment]
Thanks to recent improvements from @RipleyTom, GT5 LAN has progressed further on RPCS3. Now we can see other lobbies in our network:
![lobby](https://user-images.githubusercontent.com/61447828/95652309-fccdc900-0ae7-11eb-943b-019eff38ca10.png)

When attempting to join them, it fails with "You have been disconnected from the server":
![disconnected from server](https://user-images.githubusercontent.com/61447828/95652343-24bd2c80-0ae8-11eb-9b3f-ceaaf8f81aee.png)

**Comment by Fabianpaw** [comment]
Also FYI, since it hasn't been mentioned here, but hosting a Game on RPCS3, then joining it with a real PS3 has been functional for quite a while now. What Satan, Galciv and Me are trying now is to make RPCS3+RPCS3 Play work aswell.

**Comment by bevanweiss** [comment]
@Satan86 I assume you're already digging into this a bit with Galciv etc, but any chance you could post a log from the GT5 server disconnection event?

**Comment by Satan86** [comment]
That actually reminds me, I forgot to mention here that #9065 made LAN progress even further. Now we can join the lobby and see the other players in the players list, but as soon as someone goes to the track everybody else in the lobby softlocks and the log spams `E {Network Thread} sys_net: Unknown/illegal socket error: 10040`. The person in the track has no issues at all, the game keeps running normally with no errors.
![image](https://user-images.githubusercontent.com/61447828/96728639-afc0e100-138a-11eb-8cd7-d8bd9b2d9c00.png)
[satan_log.zip](https://github.com/RPCS3/rpcs3/files/5416410/satan_log.zip) (with the error)
[fabs_log.zip](https://github.com/RPCS3/rpcs3/files/5416416/fabs_log.zip) (went to the track causing the error)

**Comment by bevanweiss** [comment]
That's great.  From a quick google, the socket error 10040 for Windows is that the receive buffer was too small.
If you could get a wireshark capture of the data being received (and ideally sent) it would be useful to get an idea of what kind of packet sizes are being sent around.

**Comment by bevanweiss** [comment]
@Satan86, If you'd be able to try with the PR #9126 that I just pushed it would be appreciated.
I don't think this will fix things, since I can't see any setsockopts call in the logs that would suggest the existing 64kB buffer was too small.. but it appears that TCP is able to be set up to 512kB, so I'm pretty sure this buffer would need to be increased in size in the future anyway.

**Comment by Fabianpaw** [comment]
We tried that PR, and sadly the game still softlocked when going to the track. Didn't notice any other changes either.
[My Log](https://github.com/RPCS3/rpcs3/files/5434658/RPCS3.zip) (Host, going to track)
[Satans Log](https://github.com/RPCS3/rpcs3/files/5434657/RPCS3.zip) (Guest, softlocked)

**Comment by Satan86** [comment]
Thanks to @RipleyTom's latest improvements, GT5 LAN is working! 
![image](https://user-images.githubusercontent.com/61447828/97167847-46641800-1766-11eb-8454-0257cc4a6f7e.png)
![image](https://user-images.githubusercontent.com/61447828/97167865-4d8b2600-1766-11eb-84de-59f7abc3a9c8.png)
@jenci8888 can close this issue

**Comment by Nekotekina** [comment]
Was closed by mistake

**Comment by Asinin3** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/9127 closing.
