### ISSUE TITLE
Namco Museum Essentials [NPUB30086] graphic glitches on title screen and menu

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6964]
missing half of the title screen 
on menu screen there is glitches
![namco](https://user-images.githubusercontent.com/2696404/68458632-3e9e2180-023e-11ea-97bc-c7c3afdb3458.PNG)
![namco1](https://user-images.githubusercontent.com/2696404/68458639-41007b80-023e-11ea-916f-684039ef4e28.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3823417/RPCS3.log.gz)
[captures.zip](https://github.com/RPCS3/rpcs3/files/3823418/captures.zip)

**Comment by AniLeo** [comment]
Vulkan looks the same

![image](https://user-images.githubusercontent.com/10283761/68542834-52659700-03a8-11ea-8a4e-6c540566f0a3.png)

**Comment by benderscruffy** [comment]
still happens in the latest master

**Comment by benderscruffy** [comment]
with "Force CPU blit" and "Write color buffers it is fixed
