### ISSUE TITLE
[BCUS98180] MLB 09 The Show Random Crashing Early in Games

### ISSUE THREAD

**Issue by connorwalks** [RPCS3/rpcs3#6979]
RPCS3 v0.0.7-9122-8234bdb8
i9 9900K
RTX 2080
Windows 10

Essentially as the title says, this game experiences random crashes early in games (usually within the first two innings, so 5-10 minutes). This game seems to be essentially the same as MLB 07 and 08 the Show, which are both playable, but for some reason only this specific game suffers from the instability issues. 

Seems to be an RSX issue as the error code was "unknown surface target"

Video and log are linked below:

[Video Link](https://www.youtube.com/watch?v=7Zv1tjbFPZY&feature=youtu.be)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3828993/RPCS3.log.gz)

**Comment by elad335** [comment]
Retest with tsx wake up delay.

**Comment by connorwalks** [comment]
Yup, stability seems to be completely fixed with a setting of 400us! Only issue preventing game from being playable now is #5798 

I completely forgot about it but will open a new issue this weekend since original creator seems to have abandoned it. Thanks elad
