### ISSUE TITLE
[BCES01585] The Last of us

### ISSUE THREAD

**Issue by bogdik** [RPCS3/rpcs3#6980]
I tested this game on last build v0.0.7-9122 and get this (see screnshot) menu without bachground render after
Load normal work with glitches

Normal view menu render i see on v0.0.5-7628

I tested many builds after no normal work

If start game i norml see first cutscene after show i get only black window, audio work normal

<img width="1459" alt="lastofus" src="https://user-images.githubusercontent.com/15012904/68551148-df493880-041a-11ea-9ba2-5d11941dcfd1.png">

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3829058/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
You need to enable `Read Depth Buffers` and `Read Color Buffers` in the Advanced tab of settings.

The issue tracker is not the place to ask for support, go to [our Discord server](https://discord.me/RPCS3) for that.
