### ISSUE TITLE
[BLUS31197] Drakengard 3 crashes at Chapter 2 Verse 3

### ISSUE THREAD

**Issue by TahOmegaFire** [RPCS3/rpcs3#6984]
For some reason, the game crashes while loading ch2v3. I tried using an actual PS3 with the same game dump to check if it was maybe a file error, and the game ran without a problem. I tried with the 1.00 and 1.01 version of the game, both with and without the 60FPS patch, but nothing seems to fix it. 
![imagen](https://user-images.githubusercontent.com/8252359/68646763-da5bb600-04fa-11ea-9d3d-ac86f5a7bb4e.png)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3834635/RPCS3.zip)

**Comment by Illynir** [comment]
Give your saves, I could test it on my version.

**Comment by TahOmegaFire** [comment]
> 
> 
> Give your saves, I could test it on my version.

Not 100% sure if these are the saves, but here you go: 
[NPUB31251-SAVE.zip](https://github.com/RPCS3/rpcs3/files/3834664/NPUB31251-SAVE.zip)

Thanks for your quick reply!

**Comment by Illynir** [comment]
I tested with your save and I have no problems.

![drake](https://user-images.githubusercontent.com/22648460/68648779-82847580-0521-11ea-89a9-19223be9ae16.jpg)

It's very likely that the problem comes from your rip then.

**Comment by TahOmegaFire** [comment]
Yeah, I got another dump and the game worked fine now. My bad, sorry.

**Comment by renzobau** [comment]
Hi! Sorry I'm having the same issue. I would like to ask how you were able to fix this?
