### ISSUE TITLE
Regression: El Shaddai ASCENSION OF THE METATRON installation stuck at 100% [BLUS30466] 

### ISSUE THREAD

**Issue by Oizaro** [RPCS3/rpcs3#6985]
From some tests I've been doing, this regression has been happened somewhere during development of version 0.0.6.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3836982/RPCS3.zip)

**Comment by Oizaro** [comment]
My current version is 0.0.7-9124

**Comment by digtal-devil** [comment]
This is the build causing the problem - 0.0.6-7831 (#5506) [326 days ago (2019-03-08)].

Temporary workaround to this problem is using builds like 0.0.5-7727, 0.0.6-7799, 0.0.6-7827 that can bypass the install screen successfully. Copy the install folder of any of these builds and then paste in \dev_hdd0\game to get the game working in the latest master.

**Comment by Oizaro** [comment]
Thanks...

**Comment by deldiablo** [comment]
Regression still exists as of 0.0.8-9436 and 0.0.10-10486
Install reaches 100%, the animated bar freezes, no actual error until you attempt to force halt the game via the stop button.

El Shaddai ASCENSION OF THE METATRON [BLUS30466]

"Would you like to install the game data?”
E {PPU[0x1000000] Thread (main_thread) [0x01ab08c0]} cellGame: cellGameCreateGameData(init=*0xd0017f60, tmp_contentInfoPath=*0x17c2e6c, tmp_usrdirPath=*0x17c2dec)
S {PPU[0x1000000] Thread (main_thread) [0x01ab08c0]} cellGame: cellGameCreateGameData(): temporary directory '/dev_hdd0/game/_GDATA_442129701275700' has been created
E {PPU[0x1000000] Thread (main_thread) [0x01ab08b8]} cellGame: cellGameContentPermit(): failed to initialize directory '/dev_hdd0/game/BLUS30466Install' (Access violation)
E {PPU[0x1000019] Thread (31580fb0) [0x01ab0318]} cellSysutil: “Install complete.”
E {MsgDialog Thread} RSX: Dialog input loop exited with error code=-2

**Comment by elad335** [comment]
cellGameContentPermit access violation error was fixed in #8894, will close for now. I'll reopen if someone encounters this issue.
