### ISSUE TITLE
LLVM compiling znver1 PPU modules on Ryzen 3000 CPUs

### ISSUE THREAD

**Issue by z0z0z** [RPCS3/rpcs3#6989]
LLVM has support for `-march=znver2` target, but in RPCS3 is compiling modules for znver1 on third-gen Ryzen.

RPCS3 8e39c778a15b6315f395f8aa2f1203a64a8d2efb (latest commit as of now) on x86_64 Linux, Ryzen 3600. Compiled against bundled LLVM.

```
S LDR: Boot successful.
S PPU: LLVM: Compiled module v3-tane-jgjaANAdNM0hwTPFTEvUKC-000007-znver1.obj
S PPU: LLVM: Compiled module v3-tane-pAWwyfxjSzCnQ1uv7Ke5Qa-000007-znver1.obj
S PPU: LLVM: Compiled module v3-tane-Ki65gFsW6eAPAeXEQvQX1V-000007-znver1.obj
S PPU: LLVM: Compiled module v3-tane-XKRxSUYPCJnRtu1i9T1x45-000007-znver1.obj
```

**Comment by Silanda** [comment]
Yeah, I've been seeing this too. I tend to set "Use LLVM CPU:" to znver2 manually in the config file.

**Comment by Nekotekina** [comment]
Can someone test the PR?

**Comment by Silanda** [comment]
Looks good here!

**Comment by al3xtjames** [comment]
This should now be fixed in upstream LLVM: https://github.com/llvm/llvm-project/commit/ff75bf6ac93a9ef5a7d41f7645e02fde3e968ce1
