### ISSUE TITLE
Mass Effect graphical glitch

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#6990]
Probably among the long known graphical glitches of this game series. I'll report it nonetheless.

Shepard is colored in a cyan hue on the character creator screen. Not sure if it is caused by the lighting or his textures.  (Read/Write Color Buffers does _not_ have any effect on this)

![Capture](https://user-images.githubusercontent.com/20690384/68849128-cb7b2c00-06d1-11ea-89ab-0d931a15b0b9.PNG)

[Logs.zip](https://github.com/RPCS3/rpcs3/files/3845952/Logs.zip)
[RSX Capture.zip](https://github.com/RPCS3/rpcs3/files/3845953/RSX.Capture.zip)

**Comment by digitaldude555** [comment]
![Screenshot (1195)](https://user-images.githubusercontent.com/26138653/75356847-26b7df80-58b9-11ea-91ff-4908fffe9ef5.png)
Not cyan anymore.

**Comment by AniLeo** [comment]
Closing as fixed

**Comment by lextra2** [comment]
please re-open. not fixed for me. neither in the build 9724 nor 9812. tried all settings stock and tried read/write color and depth buffer. still cyan. gpu is amd rx 580. maybe it only works for nvidia?

**Comment by kd-11** [comment]
@lextra2 Two things I'd like to request:
1. Check what happens with OpenGL renderer.
2. A renderdoc trace of the broken view. I have a GPU from the same family so it should load fine for me even if you capture with vulkan.

**Comment by lextra2** [comment]
@kd-11 
> 1. Check what happens with OpenGL renderer.

In OpenGL the intros are all black, can't see anything. And once I load into the title screen (3D planet model) it gets all white, leaving me once again not be able to see anything.

> 2. A renderdoc trace of the broken view

[Here you go](https://drive.google.com/file/d/1pWkHXwMywaoJE3sA6Ef3p43Gl2c0qPyg/view)

**Comment by Andryshik345** [comment]
Still glitches on the view and faces. Vulkan and OGL have the same behavior.
![изображение](https://user-images.githubusercontent.com/24612088/81774313-b279f900-9503-11ea-8cdd-b09911aeee7e.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4620014/RPCS3.log.gz)
[RenderDoc.7z](https://drive.google.com/file/d/1P5ybTUYCZjcwdJPp242vcx35t0hybDZe/view?usp=sharing)

Specs:
Ryzen 5 1600 3.4 GHz, GTX 750 Ti 2Gb

**Comment by galahadhiryu** [comment]
Testing today i noticed that shepard is no longer displaying that cyan hue, and some other rendering problems were solved. 
![2020 07 03-01 01](https://user-images.githubusercontent.com/51791923/86430848-999ef000-bcc9-11ea-8fdb-9bd80e248e27.png)

But those black squared glitches are still present.
![2020 07 03-00 59](https://user-images.githubusercontent.com/51791923/86430897-b804eb80-bcc9-11ea-96ca-d500b0d46677.png)
Specs:
Ryzen 5 3500x
AMD Rx 5500xt
Vulkan
System: windows

**Comment by lextra2** [comment]
I can confirm. No more cyan hue on Shepard when creating a character. Closing.
