### ISSUE TITLE
Trash Panic NPUA80247: Vulkan device lost random hang

### ISSUE THREAD

**Issue by n1ghttrap** [RPCS3/rpcs3#7010]
At any given point the game will stop with the following errors in the log:

E {RSX [0x0282160]} RSX: [vulkan] vk::wait_for_event has timed out!
F {RSX [0x0283708]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:1178)

Happens regardless of high precision Z toggled or not.

Game runs well otherwise.

Checked Windows Event Log for Nvidia driver crashes, none reported.

Ryzen 3700x, 2060 Super, 16gb, Win10 1903, Nvidia Driver 441.20

**Comment by kd-11** [comment]
Is this recent or always there? There was a regression in the past 2 days that has been now resolved.

**Comment by n1ghttrap** [comment]
I've not used the emulator or had this computer long enough to say if it's a regression or recurring.  I haven't seen this particular Vulkan issue with any other games (yet), but only tested 6 or so.  FWIW I don't *think* I've seen OGL crash with it but the fire effect (even with write color buffers) is broken and mostly missing.  I will test more after work today.

**Comment by n1ghttrap** [comment]
Spent about 30-45 minutes with it, reaching stage 5 with no crashes with 9164 last night.  If it crashes again I'll let you know.

**Comment by kd-11** [comment]
Closing as fixed.
