### ISSUE TITLE
graphical issues and performance issues in international cricket 2010

### ISSUE THREAD

**Issue by bukyapavankumar** [RPCS3/rpcs3#7019]
RPCS3 v0.0.7-9160-8d5ef2c7 Alpha | HEAD | Firmware version: 4.85
Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz | 4 Threads | 7.91 GiB RAM | TSC: Bad | AVX+
S [Auto-updater] RPCS3 is up to date!
S HLE: XInput device 0 connected
S LDR: Boot successful.
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-eFdYc8hYSJp91mUTXsh94s-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-RXXJ1q0wKainArFM0FKCvi-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Luuvh9wNjmcYt1Ve8q5CG5-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-45gKouvdXdfcJZ7vWaN4hG-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-oVTQ0sfLtzCHbLpztihm0a-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-m3Maay2yvGdHa7UQ6K5oYp-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-JgTZhCqmxcdYkbZJqwVjg1-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-i0gfXAxvbsZcyHvqmvoe8C-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-fPnUg2wFqwp7dYC8hjPcPc-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Mwxb5Z1wZx4eKpVKZpYGtb-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-LmTa1URXoQxNYYpMwkroe5-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-5aA7dfAYwdZStAodgvtagh-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-rZbuGGkCJ9dg8r0enbiPiH-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-UW4GUmxLv6iR1CsSdexgn1-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-68jYYz3Q7t1kG3gZe7298a-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-5XSGa3n9nAdoKGyt0xk6eM-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-1deh8Tc9N8wg9og8KWA1x9-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-CGbmzucAPNMPnwtio2Xk0F-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Ycx60vapdyKt3pbYT1k9CS-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-78bRp0wLRYeKfng8PZ5cKJ-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-F3CYAtMpKaPMftYt2K7xRy-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Xa1PH1nKP16nUYYsW8Eoyb-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-NF4johKTG4cgx02w1zasqr-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-RPeCj3eh4jdMWwFxX2zmTL-000000-broadwell.obj
S {cellAudio Thread} XAudio 2.9 initialized
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-KiVGC0nGvnb5wGvjkr50eR-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-CtRjwEcndCMTdbWYd85EpP-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-cF0kghFNP0WmyMTqiTeMYL-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-aNFcudHr8T3K1cda8ajxwg-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-1fQxuKj8jyKkVAT0cTQiVJ-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-GPCQ2CT98JfRaAZHLypA6U-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-QGAQcWJxs0fAvg8K694nTv-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-6yw7t2r5SuH0xVtXCP6GVm-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-sE9uZoUcdS6bEKoboC03cM-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-mQLbsPW7Kz4TSWbRUWmtg0-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ryhxs9ghS3EGcnUrAKAxzd-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-8vphr6orL9yiiyU0x0QavP-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-GFZ7u8YLhfhVmK57KJn8mk-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-QhnAbnNqjTaZWwcmjLp3Lm-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-FgCbR8eRAzGZM8346r0HS7-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-s9EQbCnekK7FUrbmCRZYxj-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-5orVT3V5E9yd2k3KE8603d-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-GTdGPkm7LrhqVLqb1TT4wN-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-V3ACsUMmi6pVZs7aunw8oE-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-eKvttkHqpacH2mNkv10b4a-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-48vqMNT3w1anLXh9euovJe-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Kx7qakS7SA7muaRPXW6mke-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-MwWFToy3LjGTrfCgzQHrKt-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-M4naq6XVYe4ir4TnayFQvN-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-g4ZjKbUr7EQe9zhaRbAax1-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-d7XdG6kGz6Arsfrmb5YdaA-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-1VkrCsrc158s2F68pkYSt0-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ZwFT34tUX508WSjCnnrC4o-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-6GVy5xTxo5qY5Z7WGuRtCR-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-0kPZWA3LpYkrbz7Snhqqqh-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-HGkUnPVZfefGL5Lp0pyTRb-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-PAqYmgHo73aF94rZKMFhPb-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Z8bWceNHy5QE8pSdMi0VfH-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-pqQNKoTsVYv359xLr50hkd-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-j9ZTURZSXff1zWf2C0a90H-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-pAoRaa0LYuHiJeWqhLFUYA-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-2j8oa7rzMKrMhUbhYj531R-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-axA3iXtSuXPPgAUrKK52Vo-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-oL0MmV6MUuFE6e3RypTvJj-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-HbdTM18NbQo5Pdpv401FgQ-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-KHyzV2cS9cgKjAuaqQ2mhn-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-6yrz6627dAirtxtsZ2iifR-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-9M23T5AYweEqXv7rzEo0yQ-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-7kZzXq1xGwEixtMENYCTfF-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-8CzwTZ8fzQVH9mhMZ7VXjE-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-b2fSURMxaYETwfs27WAX4C-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-UiCaLx90WWdhzygx3h63vq-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-9SGNJTexAmoFVgUdTipsVZ-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Q6Z3106HkCm6vxybxS9Cr1-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-giy6pj0dT8YbU4Xc0rhYXn-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-oYMuEKZKsMtJp2zajzzUSa-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-kySiK3aLHtGg9dgpERutGX-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-EUrdnH98bjLqPcL52mnVVW-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-dpvUTx8ewU1Scm6nTjizn1-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-XCLuZhAcCUaTRoVLciXmwZ-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Lp1dJhkEkhSYygSenHAmZY-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-LW0KZxb45a6JCJZXycThPC-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-VPJd5ic78FgQWqU8RSmabg-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-rEGaNndcfXQhifLK3QGptm-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Vk2dKnrJE26KRNvvGrxLpd-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-386oQb2Z6vy6gk8NkJUh5y-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-GqmGA4tzr1xNQmp3QC1EKk-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-1bLAE21J9P1kKZe2dxyTwN-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-SbRqKqaE7VwrzH3kRPr3r8-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-3PfGhFnzwNvMWKN03EutPX-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-K8frMV5fwbTTt8mabJEX1n-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-4zvFGQGobqf0ywq9K5hfVr-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ntSuZeSbEu001eU49u6XuX-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ktL8ok8nfK5jzXwprrRwoh-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-LUAV19H61N7dN49QZc9NtF-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-LgzKebG5AzR6kQhtEQ2Cck-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-o47L0fZG0xis37UHfnmQrC-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-qQqcpRjES1TmTgeYp04999-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-7QZHLn2ro29WXTAabbPiMo-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-PYzanT9ZzbzV8k2WpjvX82-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-9rL55UuPLFMeiHHN6FY8uw-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-caGEhWc0j8xbv1q9baEnvv-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Y1tV2yfe5h0SZ4m65GL1F4-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-mCuagM3ivVeSNN6r1CezK1-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-9yu5A14X21kVNGoFSCuvcy-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-odkUNqU1ME9f17iGXaAvUt-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Z4SZpUHCAkqG7WrxQbk9gE-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-iP9aVMifX2AKuTn8Qjhn8N-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-374mQivj5HnN23uSkdVstL-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-tKheTKypMXU0YtsLogfZRn-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-68JunvQf0Rz5V85Jj0bpYX-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-PuyzZqv0vEXfiZctfLE29b-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-CJHuFXPbtnMgVcusXpX8kP-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-e6WGqFSa6YTQjRhPAJnx4S-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-P9rat1zz7d3bhsm6ZStQQN-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-9n8AhaN21drpCZX1JMUhJJ-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-2wKgMHbNZR99QzzppzgLRy-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ghzW0GdFJMtTRSqLqFUPmd-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-kGRUxcVz5EsZmCzpZfcMNj-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-j3xMGYYYmULbsu8xV9y0Cc-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-LhuTwkrobFeeN7WfYMG6i4-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-N6N2tp20yoqAEsc5HPs53e-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-fce81GuvYKVHoLb8r4LmEv-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-8GhonPNLhCGFQcH2vzVTjq-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Ya947ULC59TMTCSJdWonM1-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-No6M76eQTWT1shtcfNtx8r-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-9XTsbRRWZPeJ1gP2QcakC2-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-7zp6G0SLrKY8jWRYMYCVGX-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-YqFcgu9rfY9ReYVq5QKxhE-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-C5642JUAVqi4yP596jKnzR-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-8T9tV5Samw598gYY5oVktE-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-rPrMH1U2Ce7Ytu8tVR1vke-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-KCXPzQvyKS0TkKaAdvtP8r-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built the interpreter.
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built 901 functions.
U {PPU[0x1000000] Thread (main_thread) [0x0134fe64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x013500bc]} sys_prx TODO: _sys_prx_register_library(library=*0x13526a0)
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} PPU: LLVM: Loaded module v3-tane-1z3Pyu8YVnnorJiQ2hfu1e-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x01393d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} PPU: LLVM: Loaded module v3-tane-XCgQWMc1s99n1WTwrpWvw4-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} PPU: LLVM: Loaded module v3-tane-TP3c8YsdNggjaG5WRjcboe-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} PPU: LLVM: Loaded module v3-tane-LWAKW9c35vXJad6uHkwzhK-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0135061c]} sys_prx TODO: _sys_prx_register_module()
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} PPU: LLVM: Loaded module v3-tane-fLV79QqHgPi90UziTsWrHo-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} PPU: LLVM: Loaded module v3-tane-UnNP3fZh95wiCGy3Q0csRy-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} sys_prx: Loaded module: /dev_flash/sys/external/libresc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} PPU: LLVM: Loaded module v3-tane-ttuWcrR8vkrZXRoK2sr771-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} PPU: LLVM: Loaded module v3-tane-2my7r7Nd2rncZdtcuT9g60-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} PPU: LLVM: Loaded module v3-tane-aaAKL9HJRRAWFrQ1t0vFNk-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} sys_prx: Loaded module: /dev_flash/sys/external/libnet.sprx
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} PPU: LLVM: Loaded module v3-tane-jJoZ07PrzerYWWhZciLzhv-000000-broadwell.obj
S {PPU[0x1000000] Thread (main_thread) [0x013509ac]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx
U {PPU[0x1000000] Thread (main_thread) [0x01350208]} sys_prx TODO: _sys_prx_register_library(library=*0xd540fc)
U {PPU[0x1000000] Thread (main_thread) [0x01350208]} sys_prx TODO: _sys_prx_register_library(library=*0xd54118)
U {PPU[0x1000000] Thread (main_thread) [0x013d7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x4
U {PPU[0x1000000] Thread (main_thread) [0x0134ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0134ff0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
S {RSX [0x0000000]} RSX: New program compiled successfully x39
U {PPU[0x1000000] Thread (main_thread) [0x01120660]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd007fec0, option=*0x0, waitForEvent=0)
U {PPU[0x1000000] Thread (main_thread) [0x014c1bc4]} sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd007fd08)
E {PPU[0x1000013] Thread (PS3TrophyRegister) [0x01120078]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0xf7b680, arg=*0x0, options=0x1)
![Screenshot (12)](https://user-images.githubusercontent.com/25202276/69346510-e8e36380-0c98-11ea-8361-ba042a538444.png)

**Comment by RainbowCookie32** [comment]
Instead of copy pasting a part of the log into the issue, attach the full log file from RPCS3's folder. For graphical issues, attach an RSX Capture and/or a RenderDoc trace, if you need help with that, go to [our Discord server](https://discord.me/RPCS3) to ask for assistance.

**Comment by AniLeo** [comment]
This is also on an Intel laptop dual core with an unsupported iGPU, besides not following the guidelines
