### ISSUE TITLE
Pandora's Double Music Glitch in God of War 1 [BCUS98229]

### ISSUE THREAD

**Issue by Pantsay126** [RPCS3/rpcs3#7021]
For some reason, when I enter in Pandora's temple, I kept hearing two music background at the same time which can get irritating. Even if I exit the game and went back to main menu, it still plays double music in the background at once. Is there a way to fix double music background glitch in God of War 1 [BCUS98229]? 
https://gamefaqs.gamespot.com/ps2/919864-god-of-war/faqs/52361

i9-9900k
RTX 2080 Ti
Windows 10 Pro 64-bit
Here are the example of these footage that plays two musics simultaneously in Pandora's Temple:
https://www.youtube.com/watch?v=PACPzKSQXm8
https://www.youtube.com/watch?v=z2on5KEElkY
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3877277/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3877278/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/3877279/TTY.log)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3877280/RPCS3.log)

**Comment by Pantsay126** [comment]
[https://www.youtube.com/watch?v=PACPzKSQXm8](url)

**Comment by Yahfz** [comment]
That happens even on realhw so its not a RPCS3 issue.

**Comment by AniLeo** [comment]
Closing as it is a game issue that happens on physical PS3s
