### ISSUE TITLE
Regressions caused by PR #7000

### ISSUE THREAD

**Issue by gouranga** [RPCS3/rpcs3#7023]
When starting a game I receive 

```
F {RSX [0x02b0ac4]} RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2310)
```

this happens since pull #7000

![m3unzl81si (1)](https://user-images.githubusercontent.com/1222966/69433350-82b81880-0d4c-11ea-8de6-60fc9f1aa1a3.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3879892/RPCS3.log.gz)

**Comment by scott-tancock** [comment]
Can confirm this affects Dengeki Bunko Fighting Climax Ignition as well.  The game gets to the point where it wants to load character models before hitting the error.

![image](https://user-images.githubusercontent.com/27858273/69464155-7d22f880-0d75-11ea-8714-da94ef2712d3.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3881644/RPCS3.log.gz)

Shall I attach copies of the models in question?  If you have a copy, it's in folder [BLJM61322]\PS3_GAME\USRDIR\grpdat\CSel\chara\ and the models it loads first are chara_sha_1.dds.gz and chara_sha_2.dds.gz

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/7028

**Comment by Asinin3** [comment]
This fixes DMC 1 not loading or going ingame when starting a new game too. Previously gave this error:
```F {RSX [0x0168ad0]} RSX: class std::runtime_error thrown: Verification failed: (in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2310)```

![image](https://user-images.githubusercontent.com/15137035/69478881-5d5c0500-0e47-11ea-846e-e1e8e122d5ee.png)

Will check top spin now.

**Comment by gouranga** [comment]
Yes, got fixed! Ty @kd-11 !
