### ISSUE TITLE
[Regression] PR #7000 broken kingdom hearts final mix loading save files

### ISSUE THREAD

**Issue by danshuter** [RPCS3/rpcs3#7024]
the issue is with kingdom hearts final mix, the game will no longer load save files, it will attempt to but just freeze with a black screen and the logo in the bottom right hand corner. 
was working on the previous build but the issue has transfereed over to newer builds as well.
#7000 
still broken after the recent fixup pr

only at the start of the game but have uploaded save file for use 

[BLUS31212-BISLPS25198.zip](https://github.com/RPCS3/rpcs3/files/3880212/BLUS31212-BISLPS25198.zip)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3880153/RPCS3.log) Working

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3880100/RPCS3.log) Not working

my system
windows 10 
ryzen 5 3600 4.25ghz 
rtx 2080 
16gb ram

**Comment by Asinin3** [comment]
Please tag pull requestsin the description/issue instead of the title since it doesn't work there. #7000 .

I'm not so sure it's this pr that's causing it though... you should be providing log files before and after.

**Comment by danshuter** [comment]
> f

**Comment by danshuter** [comment]
i have updated it thankyou

**Comment by kd-11** [comment]
Duplicate of https://github.com/RPCS3/rpcs3/issues/7023
