### ISSUE TITLE
[BLES01167] Capitan America regresion since build 8179 to 9163

### ISSUE THREAD

**Issue by maricelase** [RPCS3/rpcs3#7026]
Since the the build 0.0.6-8179 or the PR #4450 to all more recents build, the game give me this error trying boot, and can't run 

>F LDR: class std::out_of_range thrown: invalid string position
>S LDR: Boot successful.

![capitan NOo](https://user-images.githubusercontent.com/58095928/69471643-38e92580-0d80-11ea-8896-e77d1905ab17.JPG)

in build 0.0.6-8178 or the PR #6042 and older builds, the game boot and run fine
![capitan YES](https://user-images.githubusercontent.com/58095928/69471489-41d8f780-0d7e-11ea-8312-a10f4fec6ce2.JPG)

the problem is from 8179 to the most recent's build

My pc specs:
i7-4790k 4,00ghz
GTX 1080 driver 441.20
32gb ram
Windows 10 x64 18363.476
[capitan america log build 0.0.6-8179.log.gz](https://github.com/RPCS3/rpcs3/files/3882065/capitan.america.log.build.0.0.6-8179.log.gz)
[capitan america log build 0.0.6-8178.log.gz](https://github.com/RPCS3/rpcs3/files/3882066/capitan.america.log.build.0.0.6-8178.log.gz)

**Comment by Asinin3** [comment]
I'm not so sure about this report, because going by these posts: https://github.com/RPCS3/rpcs3/issues/5886#issuecomment-546481048 people could still get ingame in recent builds of RPCS3. Maybe it was fixed later? Have you tried the most up-to-date builds of RPCS3? Also, you don't need to tag the 6042 PR, since this has nothing to do with it. And it will just notify kd-11 even though it's not related.

**Comment by maricelase** [comment]
> 
> 
> I'm not so sure about this report, because going by these posts: [#5886 (comment)](https://github.com/RPCS3/rpcs3/issues/5886#issuecomment-546481048) people could still get ingame in recent builds of RPCS3. Maybe it was fixed later? Have you tried the most up-to-date builds of RPCS3? Also, you don't need to tag the 6042 PR, since this has nothing to do with it. And it will just notify kd-11 even though it's not related.

i've tried all builds since 8179 to 9163 and all give me same error

**Comment by legend800** [comment]
American version has never had this issue and I'm not sure another region disc could regress like this. Do a fresh install of emu and redump game maybe. 

![2019-11-23 08_51_21-FPS_ 59 96 _ Vulkan _ 0 0 7-9164 _ Captain America™_ Super Soldier  BLUS30642](https://user-images.githubusercontent.com/20983844/69482329-8be9c980-0dce-11ea-9fd9-beb9c620fd53.png)

**Comment by maricelase** [comment]
i reinstall emulator and game and have the same issue, how you can see in the log's file

**Comment by maricelase** [comment]
was solved erase game together BLES01167install folder. and reinstall again
maybe some has change from 8178 to 8179 and never say nothing
