### ISSUE TITLE
Drakengard 3 NPUB31251 - Access violation reading location 0x0

### ISSUE THREAD

**Issue by IceBlizz6** [RPCS3/rpcs3#7032]
Playing through Drakengard 3 flawlessly until Chapter 0, Verse 2.
Interacting with 4 items, then walking out the door.
Entering loading screen, and that is where it crashes
F {PPU[0x1000000] Thread (main_thread) [0x0037ac38]} MEM: Access violation reading location 0x0

Retried 4-5 times with same result.
Noticed similar thread https://github.com/RPCS3/rpcs3/issues/3936
Last message said the problem was fixed, not sure if this is a regression or a different problem.

RPCS3 version: 0.0.07-9165-8ca53f9c (same problem on 9164)
Game version: NPUB31251 (with patch 1.01 + jpn voices)
CPU: AMD Ryzen 5 2600X Six-Core
GPU: NVIDIA GeForce GTX 1060 6GB
Log file: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/3883829/RPCS3.log)

**Comment by AniLeo** [comment]
Should upload TTY.log as well since it wrote something there before dying

**Comment by IceBlizz6** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3883862/RPCS3.log)
[TTY.log](https://github.com/RPCS3/rpcs3/files/3883863/TTY.log)
Included TTY.log + rpcs3 log for same run

**Comment by IceBlizz6** [comment]
I tried reinstalling the game, including 1.01 and jpn voices while leaving out all the other DLCs.
It actually worked. I suspect either one of the minor DLCs were incorrectly installed or they caused some problem for RPCS3. If someone else comes across this issue then try to remove all the DLCs.
i'll close this for now.
