### ISSUE TITLE
Army of TWO™: The 40th Day [BLUS30408] doesnt display the whole screen in Vulkan and Opengl

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7038]
it just displays a small strip across the screen with default settings
![army](https://user-images.githubusercontent.com/2696404/69859424-1d75a180-12cf-11ea-8bca-6fc525e16efe.PNG)
here is a renderdoc
https://mega.nz/#!A6YnGYzT!z4o_Myp1lt-dQrfjPxbFcToKbdXlkyW4qAEEebkdJ10
log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3904589/RPCS3.log.gz)

**Comment by benderscruffy** [comment]
ok if you set aspect ratio to auto it just displays a small strip across the screen 
if you set to 16:9 graphics are fine

**Comment by kd-11** [comment]
Closing as fixed by https://github.com/RPCS3/rpcs3/pull/7207
