### ISSUE TITLE
Golden Axe: Beast Rider™ [BLUS30209] runtime_error thrown

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7043]
using vulkan or opengl freezes up on the loading screen before level 1
F {RSX [0x028c104]} RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2577)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3906850/RPCS3.log.gz)

**Comment by benderscruffy** [comment]
Knytt Underground [NPUB30820] throws the same error

**Comment by Emulator-Team-2** [comment]
@kd-11 
This issue can be closed.
