### ISSUE TITLE
Regression pes 2016 Fatal Error

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#7048]
RPCS3 v0.0.7-9191-d45fbc33 Alpha | HEAD | Firmware version: 4.85
Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz | 16 Threads | 15.92 GiB RAM | TSC: Bad | AVX+ | TSX
Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0
·! 0:00:00.000000 RSX: Found vulkan-compatible GPU: 'GeForce GTX 780 Ti' running on driver 441.41.0.0

![RPCS3_ Fatal Error 12_1_2019 12_29_25 PM](https://user-images.githubusercontent.com/45731484/69919899-b8d55680-1436-11ea-89b3-623b9ac1d8ef.png)

log file

[RPCS3 pes.zip](https://github.com/RPCS3/rpcs3/files/3908680/RPCS3.pes.zip)

**Comment by AniLeo** [comment]
What's the offending PR?

**Comment by uaqlover** [comment]
@AniLeo graphics also is broken 

after testing so many builds it broke after https://github.com/RPCS3/rpcs3/pull/7044

![75](https://user-images.githubusercontent.com/45731484/70148661-6f198580-165b-11ea-946f-054424b80f52.png)

in build https://github.com/RPCS3/rpcs3/pull/7040 was working fine 

![55574](https://user-images.githubusercontent.com/45731484/70148714-89536380-165b-11ea-933f-becd5a68d649.png)

**Comment by elad335** [comment]
This is an rsx access violation.. (segfault because unhandled) bad testing is bad.
