### ISSUE TITLE
Revenant Saga [NPUB31863] nothing but a black screen

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7050]
F {PPU[0x1000005] Thread (UnityMain)} class std::runtime_error thrown: Trap! (0xff458)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3912033/RPCS3.log.gz)

**Comment by Illynir** [comment]
PPU Interpreter works perfectly.

**Comment by RainbowCookie32** [comment]
The playable report was done on PPU Fast. If running the game with it instead of LLVM fixes it, then comment in #5831 and close this one.

**Comment by benderscruffy** [comment]
if i use ppu instead of LLVM it still crashes
F {PPU[0x1000005] Thread (UnityMain)} class std::runtime_error thrown: Trap!
(in file C:\projects\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:3186)

**Comment by benderscruffy** [comment]
still the same error
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4121046/RPCS3.zip)

**Comment by digitaldude555** [comment]
Last worked in 0.0.5-7338 build and broke 0.0.5-7345.
#5111 broke it. Same exact issue as #6365.

**Comment by benderscruffy** [comment]
still happens in the latest master
here is an updated log and tty
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4480817/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/4480818/TTY.log)

**Comment by AniLeo** [comment]
Closing as duplicate of #6365, please continue to discuss there
