### ISSUE TITLE
Games on multi-game discs fail to boot with updates/game data installed

### ISSUE THREAD

**Issue by 13xforever** [RPCS3/rpcs3#7051]
As a continuation of #4448, in pr #4450 we got basic support for multi-game discs. And it works fine until you install the game data or update, then it will fail to boot.

Log excerpt from the failed boot:

```
·! 0:00:13.339912 LDR: Disc: E:/FakeCDs/PS3 Games/[BLES 00635] TEKKEN 6/
·! 0:00:13.339915 LDR: Game: E:/FakeCDs/PS3 Games/[BLES 00635] TEKKEN 6/PS3_GM02/
·S 0:00:13.341529 LDR: Updates found at /dev_hdd0/game/BLES01250/!
·! 0:00:13.350362 LDR: Path: C:/Games/Emulators Collection/Emulators/PS3/rpcs3/dev_hdd0/game/BLES01250/USRDIR/EBOOT.BIN
·! 0:00:13.351489 LDR: Disc: E:/FakeCDs/PS3 Games/[BLES 00635] TEKKEN 6/
·! 0:00:13.351491 LDR: Game: E:/FakeCDs/PS3 Games/[BLES 00635] TEKKEN 6/PS3_GAME/
·E 0:00:13.351636 LDR: Unexpected disc directory for the disc game BLES01250 (found BLES00635)
```

[RPCS3.sc5_no_updates.log.gz](https://github.com/RPCS3/rpcs3/files/3913272/RPCS3.sc5_no_updates.log.gz)
[RPCS3.sc5_with_updates.log.gz](https://github.com/RPCS3/rpcs3/files/3913273/RPCS3.sc5_with_updates.log.gz)

**Comment by Megamouse** [comment]
Please try the linked build

**Comment by 13xforever** [comment]
All three games boot with proper updates applied. However, each game is duplicated thrice in the library.
![library duplicates](https://user-images.githubusercontent.com/36445/74956674-44ec8e00-5428-11ea-99a9-8358f4b150f4.png)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4231839/RPCS3.zip)

**Comment by Megamouse** [comment]
The duplication doesn't appear on master?

**Comment by 13xforever** [comment]
I've updated the master build and it's the same there, so I guess it's a separate issue
