### ISSUE TITLE
The Book of Unwritten Tales 2 [NPEB02256] Hdd boot game is corrupt

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7055]
![book](https://user-images.githubusercontent.com/2696404/70029824-e3641280-15e2-11ea-98d3-fe829be5b01d.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3915208/RPCS3.log.gz)

**Comment by benderscruffy** [comment]
happens with
The Book of Unwritten Tales 2 [NPUB31695] aswell
![book](https://user-images.githubusercontent.com/2696404/72792775-84328e00-3c74-11ea-947a-aab10fd4a8dd.PNG)

**Comment by digitaldude555** [comment]
Removing keyfile.edat from the game folder causes the game to boot.
![Screenshot (1961)](https://user-images.githubusercontent.com/26138653/78506142-52fc3100-7780-11ea-93ec-eb2a6bba96b2.png)

**Comment by dragonslayer2555** [comment]
Good morning,
I have the same problem with Drakengard 3 and in the folder game there aren't a keyfile.edat file

**Comment by digitaldude555** [comment]
It's fixed now, can be closed.

**Comment by dragonslayer2555** [comment]
Si, ho risolto. Grazie comunque
