### ISSUE TITLE
Monster Jam Battlegrounds [NPUB31686] stuck on loading screen

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7056]
after you press X on title screen it is stuck on the loading screen
![monster](https://user-images.githubusercontent.com/2696404/70049630-0bb23800-1608-11ea-8e21-3b97bafd25ea.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3916447/RPCS3.log.gz)

**Comment by uaqlover** [comment]
it was working in  rpcs3-v0.0.4-2018-01-19-49e64b9e_win64

long file 

[RPCS3 jam.zip](https://github.com/RPCS3/rpcs3/files/3988125/RPCS3.jam.zip)

**Comment by elad335** [comment]
It's actually working in latest master.
