### ISSUE TITLE
Dungeon Siege III [BLES01161] cannot start a new game (missing menus)

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7057]
happens on both vulkan and opengl 
![dungeon](https://user-images.githubusercontent.com/2696404/70052616-a6157a00-160e-11ea-8fd0-3c348efbc842.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3916653/RPCS3.log.gz)
this is what it is supposed to look like
![dungeon1](https://user-images.githubusercontent.com/2696404/70052718-d8bf7280-160e-11ea-965e-d095c23583b5.PNG)
captures
https://mega.nz/#!ZnJADKbQ!7qTxV8R97vdpKwMcbWeorsY-dyHpFV5YNTVme2PeVGA

**Comment by benderscruffy** [comment]
is fixed now
![dungeon](https://user-images.githubusercontent.com/2696404/70839794-7f92e280-1e49-11ea-913d-169a42530e83.PNG)

**Comment by DonChino** [comment]
Um, so how did you get it to work? I still have no menu... >:(
