### ISSUE TITLE
RSXIO memory not mapped Overlord II 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#7069]
RPCS3 v0.0.7-9203-c3862b74 Alpha | HEAD | Firmware version: 4.85
Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz | 16 Threads | 15.92 GiB RAM | TSC: Bad | AVX+ | TSX

[RPCS3 over.zip](https://github.com/RPCS3/rpcs3/files/3928656/RPCS3.over.zip)

F {RSX [0x01b31b8]} RSX: class std::runtime_error thrown: GetAddress(offset=0x662a00, location=0x1): RSXIO memory not mapped
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:68)

**Comment by digitaldude555** [comment]
@uaqlover update.

**Comment by elad335** [comment]
Try driver wake-up delay.

**Comment by uaqlover** [comment]
now it has

i set it to 200us in driver wake-up delay.

F {RSX [0x00d12ec]} RSX: class std::runtime_error thrown: rsx::get_address(offset=0x511080, location=0x1): RSXIO memory not mapped!
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:1718)

**Comment by uaqlover** [comment]
now is fixed
