### ISSUE TITLE
[Linux] Enslaved: Odyssey to the West - No longer ingame

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#7071]
Booting this game (NPUB31342) under commit e050dcbc52d692465d365c3519d126344923f2ff, only a black screen is shown at startup.  [This](https://www.youtube.com/watch?v=GjiAgDbW97I) recent video shows the game running on a Windows system; however, builds earlier than the one shown in that video don't work on this test system, so this must be a linux-only issue.

Test system is linux mint 19.2 with kernel 5.0, GTX 1070M and driver 440.36.

Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3933277/RPCS3.log.gz)

**Comment by elad335** [comment]
The only thing there is in your log is ```Could not load image from path /home/darren/.config/rpcs3/dev_hdd0/game/BLUS30003/ICON0.PNG```
Check your dump.

**Comment by Shoegzer** [comment]
Reuploaded the log, thanks.

**Comment by 13xforever** [comment]
the log is still empty, it _looks_ like your game is simply missing; please ask in discord for help instead, this looks like an invalid issue

**Comment by Shoegzer** [comment]
Strange.  The log is much more complete on my end.  I just reupped the log again, downloaded it from gh and it seems to be fine, please check and let me know.

**Comment by 13xforever** [comment]
Log looks ok now, but you still need to find the last working version and provide log from that build

**Comment by Shoegzer** [comment]
I've never needed to do that before, but okay.  See above.

**Comment by 13xforever** [comment]
what? you uploaded log from UI for the same build.

I'm asking for a proper log from the last build that worked, before you started to get this problem.

**Comment by Shoegzer** [comment]
Sorry, I misunderstood.  I just tried the build immediately prior to the one posted in the video which didn't work either, so I'm marking this as Linux-only.  

Not sure if it helps, but other people have encountered this black screen issue in the past as shown in the compatibility report, though I can't get to it at the moment because the site is down for maintenance.

**Comment by JohnHolmesII** [comment]
![image](https://user-images.githubusercontent.com/8901018/70381181-dbd39f00-193d-11ea-94a1-e35a904467ba.png)

Works on my machine™

**Comment by Shoegzer** [comment]
@JohnHolmesII care to share your specs?  Need system, build, kernel, graphics drivers, game version, rpcs3 settings, etc.

**Comment by JohnHolmesII** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3935658/RPCS3.log.gz)

I have a feeling it's the novideo drivers you got.

**Comment by Shoegzer** [comment]
What do you mean "novideo"?  I'm using nvidia 440.36 drivers, and all other games test just fine going ingame etc.

**Comment by JohnHolmesII** [comment]
Are you using the appimage or building?

**Comment by Shoegzer** [comment]
Building myself using gcc 9.2.1

**Comment by Shoegzer** [comment]
@JohnHolmesII Just noticed from your logs you are using the disc version, which ]works fine.  The one I'm testing is the "Premium Edition" PSN version which does not.

**Comment by benderscruffy** [comment]
this works for me
what about you
![enslaved](https://user-images.githubusercontent.com/2696404/74076526-6a09f580-4a53-11ea-88af-ba51bf06fb82.PNG)

**Comment by Shoegzer** [comment]
I haven't tested it since my last post as I don't have that game anymore.  If anyone else can confirm your finding I'll close the issue.
