### ISSUE TITLE
PPU: Function aborted Winter Stars [BLES01224]

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#7072]
F {PPU[0x1000000] Thread (main_thread) [0x008c5aa0]} PPU: Function aborted: sceNpBasicAddPlayersHistoryAsync
F {PPU[0x1000000] Thread (main_thread) [0x008c5aa0]} MEM: Access violation reading location 0x0

[RPCS3 0.0.7-9209.zip](https://github.com/RPCS3/rpcs3/files/3934253/RPCS3.0.0.7-9209.zip)

**Comment by elad335** [comment]
Retest with #7074

**Comment by uaqlover** [comment]
it fixed with https://github.com/RPCS3/rpcs3/pull/7074 thanks @elad335
