### ISSUE TITLE
Custom vblank Frequency (custom refresh rate) only work on 576p resolution

### ISSUE THREAD

**Issue by Nerboruto** [RPCS3/rpcs3#7075]
i use this hack to speedup emulation a bit!!!
please unlock it for 720p resolution...
576p force me to stretch in orizontal..

**Comment by Nerboruto** [comment]
![vblank](https://user-images.githubusercontent.com/10599012/70375887-8e3a4080-1903-11ea-9946-80c9de72f036.png)
 no confusion here..
try it yourself...

**Comment by Margen67** [comment]
Why are you upvoting your own posts?

**Comment by RainbowCookie32** [comment]
Vblank frequency override is not locked to any resolution. It works just fine on 720p in all games I tested since it was implemented

**Comment by Nerboruto** [comment]
> Vblank frequency override is not locked to any resolution. It works just fine on 720p in all games I tested since it was implemented
I did several tests with 2 different PCs and with latest firmware 4.85... and several games...
only works at 576p.
I can prove it with screenshots if you want.

**Comment by Asinin3** [comment]
Then you're literally the only person with this issue. I have not seen a single person mention this. Show screens and post log files. My guess is that you had it set incorrectly in a custom config file

**Comment by Nerboruto** [comment]
![vblank2](https://user-images.githubusercontent.com/10599012/70378574-365f0200-1922-11ea-847d-a5e910f1008c.png)

**Comment by Nerboruto** [comment]
> Then you're literally the only person with this issue. I have not seen a single person mention this. Show screens and post log files. My guess is that you had it set incorrectly in a custom config file

I did a lot of testing look at the fps

**Comment by kd-11** [comment]
Or, you know, maybe the game doesn't use the vblank clock for 720p? There is no requirement that the game does this, afterall 720p/30 and 720p/60 are guaranteed to work. Maybe the game doesn't even use refresh rate if you use 720p. The option is not tied to any resolution, its a global clock that the game can access at any time if it wants to.

**Comment by Nerboruto** [comment]
> Or, you know, maybe the game doesn't use the vblank clock for 720p? There is no requirement that the game does this, afterall 720p/30 and 720p/60 are guaranteed to work. Maybe the game doesn't even use refresh rate if you use 720p. The option is not tied to any resolution, its a global clock that the game can access at any time if it wants to.

ok I understand...
however use 576p and a custom refresh allows to get a boost on slow machines which results in less audio crackling

**Comment by Nerboruto** [comment]
we can close the issue

**Comment by Asinin3** [comment]
Only you, and people who have the rights to this github repository can close the issue. You see that big red close issue button below? Click on it to close the issue.
