### ISSUE TITLE
Don Bradman JIT: Null Function 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#7079]
before was 

`F {PPU[0x100000a] Thread (InitThread) [0x000a8c38]} class std::runtime_error thrown: Null function (in file c:\projects\rpcs3\utilities\jit.cpp:324)`

https://github.com/RPCS3/rpcs3/issues/5972

in RPCS3 v0.0.7-9212-6a4ba9d5 Alpha
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3936549/RPCS3.log.gz)

`F {PPU[0x100000a] Thread (InitThread)} class std::runtime_error thrown: Null function
(in file C:\projects\rpcs3\Utilities\JIT.cpp:567)`

**Comment by MSuih** [comment]
The file got other stuff added to it, which pushed the line about null function downwards and thus changed the line number to 567. Changes in capitalization of the path are irrelevant as windows paths are case-insensitive. There's no actual difference between those two errors.

**Comment by MarioSonic2987** [comment]
Isn't it already reported in #5831?
