### ISSUE TITLE
cascadelake of error llvm

### ISSUE THREAD

**Issue by dsyo2008** [RPCS3/rpcs3#7082]
rpcs3 0.0.7-9217 llvm compilation errors, change skylake next attempt to compile OK.
Llvm is the problem?

10900x
8gx4 3800
rtx2080ti
PRIME X299-DELUXE

Most games are like this
cascadelake compilation errors llvm
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3956037/RPCS3.log)

Use LLVM CPU: "skylake"
Compile OK
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3956054/RPCS3.log.gz)

**Comment by MSuih** [comment]
Should be fixed with #7086

**Comment by dsyo2008** [comment]
> 
> 
> Should be fixed with #7086

No, the same mistake!
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3960120/RPCS3.log)

**Comment by MSuih** [comment]
How about #7088?

**Comment by dsyo2008** [comment]
> 
> 
> How about #7088?

Solve OK, you can turn off! Thank you
