### ISSUE TITLE
Vulkan API  still causing Out of video Memory crash

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#7092]
I still have this message in GOW Ascension NPEA00445 at the beginning of the game (or later in the game if I change setting,but issue still happens) : 
"F {RSX [0x03b1f24]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:339)
W {cellAudio Thread} cellAudio: Audio backend stopped unexpectedly, likely due to a buffer underrun
! {rsx::thread} Thread time: 118.421875s (427.516569Gc); Faults: 13912 [rsx:13912, spu:0];
! {RSX Decompiler Thread} Thread time: 0.000000s (1.714264Gc); Faults: 0 [rsx:0, spu:0];
! {VBlank Thread} Thread time: 0.000000s (0.656227Gc); Faults: 0 [rsx:0, spu:0];"

Unable to take an RSX capture (nothing happens when I click on the icon)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3963808/RPCS3.log.gz)

**Comment by Wagnard** [comment]
Set back your resolution scale to default (100%)
