### ISSUE TITLE
Stuck on Loading PPU with Vulcan [BLES00246]

### ISSUE THREAD

**Issue by HidroSaphire** [RPCS3/rpcs3#7093]
On RPCS3 0.07-9224 Alpha, I was trying to play MGS4 [BLES00246] . After the Konami logo, it freeze on Loading PPU Modules.

Then, black screen and nothing happens.

Here's the Log (last part, where the errors begins)

E {PPU[0x1000014] Thread (CDBIOS_NORMAL) [0x00de2090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/s/stage00.dat./0001/.f0000p00000000013fc000s00000800.ca.ctmp” [1]
E {PPU[0x1000014] Thread (CDBIOS_NORMAL) [0x00de5fc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/s/stage00.dat.” [1]
E {PPU[0x1000014] Thread (CDBIOS_NORMAL) [0x00de2090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/s/stage00.dat./0004/.f0000p00000000047c6000s00040000.ca.ctmp” [1]
E {PPU[0x1000014] Thread (CDBIOS_NORMAL) [0x00de5fc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/s/stage00.dat.” [2]
E {PPU[0x10003a2] Thread (STGDEC) [0x00031964]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000014] Thread (CDBIOS_NORMAL) [0x00de2090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/s/stage00.dat./0002/.f0000p000000000286d000s00065000.ca.ctmp” [1]
E {PPU[0x1000014] Thread (CDBIOS_NORMAL) [0x00de5fc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/dev_hdd1/s/stage00.dat.” [3]
E {PPU[0x10003a4] Thread (SAVE) [0x009f0238]} 'cellSaveDataListAutoLoad' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
E {PPU[0x10003a6] Thread (SAVE) [0x009f0238]} 'cellSaveDataListAutoLoad' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
S PPU: LLVM: Compiled module v3-tane-8G8Siw0thFwb1Pcpoo0ZbQ-000000-haswell.obj
S {PPU[0x1000001] Thread (MGS4 MAIN) [0x009f6d20]} sys_prx: Loaded module: /dev_flash/sys/external/libvdec.sprx
S {PPU[0x1000001] Thread (MGS4 MAIN) [0x009f6d20]} PPU: LLVM: Loaded module v3-tane-ttuWcrR8vkrZXRoK2sr771-000000-haswell.obj
S {PPU[0x1000001] Thread (MGS4 MAIN) [0x009f6d20]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
E {PPU[0x1000001] Thread (MGS4 MAIN) [0x013b04f0]} 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000001] Thread (MGS4 MAIN) [0x013b0500]} 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [1]
S {SPU LLVM} SPU: New block compiled successfully x8
E {PPU[0x1000001] Thread (MGS4 MAIN) [0x013b1880]} 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000001] Thread (MGS4 MAIN) [0x013b1894]} 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [2]
S {SPU LLVM} SPU: New block compiled successfully x113
E {SPU[0x3000100] Thread (MGS4_MAINCellSpursKernel3) [0x166e0]} SPU: Trampoline simplified at ??? (level=35)
S {SPU LLVM} SPU: New block compiled successfully x5
E {PPU[0x10003a7] Thread (_libvdec_smvd2) [0x013b2010]} 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x10003a7] Thread (_libvdec_smvd2) [0x013b20d4]} 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [1]
S {SPU LLVM} SPU: New block compiled successfully x6
E {PPU[0x10003a7] Thread (_libvdec_smvd2) [0x013b2010]} 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x10003a7] Thread (_libvdec_smvd2) [0x013b20d4]} 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [2]
S {SPU LLVM} SPU: New block compiled successfully x19
E {PPU[0x10003a7] Thread (_libvdec_smvd2) [0x013b2010]} 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x10003a7] Thread (_libvdec_smvd2) [0x013b20d4]} 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [3]
S {SPU LLVM} SPU: New block compiled successfully x628

**Comment by AniLeo** [comment]
As indicated on the guidelines, the tracker is for issue reporting, not for support requests. Submit your support request on the appropriate platform(s).
