### ISSUE TITLE
Ghostbusters: Sanctum of Slime NPUB30365 missing graphics during gameplay using opengl (Vulkan works fine)

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7096]
·E 0:01:34.544455 {RSX [0x05008e4]} RSX: FS exports depth component but depth test is disabled (INVALID_OPERATION)
might be an AMD problem ???
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3964547/RPCS3.log.gz)

**Comment by dulsan** [comment]
It might be a problem with the AMD gpu, try turning on read and write depth buffers, see if that helps. My question is, why would you use Opengl if it works on Vulkan?

**Comment by benderscruffy** [comment]
it is an amd fault
every game i use opengl is a black screen
it started happening from amd driver 19.12.2 and still continues
looks like i will stick to just vulkan

**Comment by benderscruffy** [comment]
![ghost](https://user-images.githubusercontent.com/2696404/73256026-2665ef00-41fc-11ea-9700-ebc67f436cf9.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4121862/RPCS3.log.gz)
[NPUB30365_20200128182514_capture.zip](https://github.com/RPCS3/rpcs3/files/4121864/NPUB30365_20200128182514_capture.zip)

**Comment by benderscruffy** [comment]
goes ingame with graphics now
![ghost](https://user-images.githubusercontent.com/2696404/79328094-1bdc0b80-7f48-11ea-9f16-0650adb1ecb6.PNG)
