### ISSUE TITLE
Using 2 graphics card at the same time

### ISSUE THREAD

**Issue by GrandGTA** [RPCS3/rpcs3#7099]
i have two graphics card in my computer
Nvidia Quadro 6000 and Nvidia Quadro K620

i was wondering if using both of them at the same time would work
can anyone tell me how to use both of them at the same time?

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
