### ISSUE TITLE
'sys_fs_open' failed with 0x8001003a : **CELL_ENOTMOUNTED**

### ISSUE THREAD

**Issue by vigneshkiruba** [RPCS3/rpcs3#7100]
'sys_fs_open' failed with 0x8001003a : CELL_ENOTMOUNTED, “/host_root//home/shamli/Downloads/FIFA 19 PT - BR - [BLUS31617]/PS3_GAME/USRDIR/memoryfw.ini” [1]

I found this issue while downloading FIFA 19.
I installed previous builds not the newer version of RPCS3.
Please help me to find the issue in "memoryfw.ini".

Dont close the issue. I want solution.

**Comment by MilkFlavor** [comment]
> 'sys_fs_open' failed with 0x8001003a : CELL_ENOTMOUNTED, “/host_root//home/shamli/Downloads/FIFA 19 PT - BR - [BLUS31617]/PS3_GAME/USRDIR/memoryfw.ini” [1]
> 
> I found this issue while downloading FIFA 19. I installed previous builds not the newer version of RPCS3. Please help me to find the issue in "memoryfw.ini".
> 
> Dont close the issue. I want solution.

lmao
