### ISSUE TITLE
9228 RE:ORC stop in main menu[BLUS30750]

### ISSUE THREAD

**Issue by Myoko** [RPCS3/rpcs3#7105]
![QQ截图20191218102022](https://user-images.githubusercontent.com/3013386/71050647-b5ed9c00-2180-11ea-81d4-464158682613.jpg)

this game always stop in please wait, can't go on 
back to 9217 its normal! something has been broken?

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3976362/RPCS3.log.gz)

**Comment by elad335** [comment]
try changing network setting.

**Comment by Myoko** [comment]
> try changing network setting.

i have
![sa](https://user-images.githubusercontent.com/3013386/71072747-151bd280-21ba-11ea-8fe9-b1bca739bec2.jpg)

**Comment by CrabLugo** [comment]
Try to wait longer, for 10-15min. Alsu use 2 or 3 spu preferred threads. And use ip obtained network setting

**Comment by Myoko** [comment]
> Try to wait longer, for 10-15min. Use 2 or 3 spu preferred threads. And use ip obtained network setting

its the same results

**Comment by uaqlover** [comment]
i think it fixed in https://github.com/RPCS3/rpcs3/pull/7115

**Comment by elad335** [comment]
Nothing relevant in log.

**Comment by Myoko** [comment]
this issues fixed in #7115 thanks @elad335 
https://streamable.com/ysaav
