### ISSUE TITLE
Toy Story 3 black flickering textures

### ISSUE THREAD

**Issue by infamouskill156** [RPCS3/rpcs3#7120]
Anyone know how to fix these annoying black flickering textures on Toy Story 3. I've updated all my drivers I've messed with the rpcs3 configurations. I've messed with my Nvidia control panel nothing seems to work. I know this can be fixed easily because I found a YouTube video of someone playing the game without flickering textures. Anyone got any solutions would much appreciate it thanks.

[No flickering textures](https://youtu.be/lDQtMI-e7mM)
![Screenshot_20191219-174720](https://user-images.githubusercontent.com/59070087/71302304-dfbce380-2377-11ea-8c6f-a7b5a12bb7cb.png)

**Comment by dio-gh** [comment]
As the instructions you've failed to remove say, this is not a support forum, and for support you should visit those other linked places. Please close this ticket.
