### ISSUE TITLE
Game Hacking

### ISSUE THREAD

**Issue by wheelmac92** [RPCS3/rpcs3#7123]
When building my own EXE file to edit process memory, WriteProcessMemory fails to edit the game's memory

I noticed that RPCS3 requires a flag to be enabled in Cheat Engine, before attempting to hack games. This flag is MEM_MAPPED under Scan Settings.

I was able to find, and change, the values that I need in the game I am trying to mod, from within Cheat Engine.

However, I am trying to make a standalone EXE file that edits RPCS3's memory, to make the mod function, by using ReadProcessMemory and WriteProcessMemory. No matter what I do, ReadProcessMemory and WriteProcessMemory fail with RPCS3. Is there anything special that I need to do, to enable memory with this emulator?

**Comment by VelocityRa** [comment]
Use [RPCS3's patching system](https://github.com/RPCS3/rpcs3/wiki/Game-Patches).

**Comment by doesthisusername** [comment]
I've done this, albeit from C# using DllImport. I haven't needed to do anything special for MEM_MAPPED (though I don't know much about it, to be fair).
A few things to make sure about:

- Are you compiling your program for 64-bit? You probably need to do that, as the relevant game values are located above 0xFFFFFFFF, and you can't really have such a pointer in a 32-bit program.
- Are you writing in the 0x3xxxxxxxx range? I'm not sure 0x4xxxxxxxx works, though I haven't tried it out thoroughly.

I have some example (C#) code:
```cs
Process rpcs3 = Process.GetProcessesByName("rpcs3")[0];
if(rpcs3 != null)
{
    int readAmount = 0;
    ulong handle = OpenProcess(0x0038, false, rpcs3.Id);
    ReadProcessMemory(handle, 0x300000000ul + offset, result, (int)length, ref readAmount);
    CloseHandle(handle);
}
```

**Comment by wheelmac92** [comment]
Thank you so much! I was compiling in x86
