### ISSUE TITLE
Diablo 3: Reaper of Souls - Ultimate Evil Edition (BLUS31437) freezes when starting a new game

### ISSUE THREAD

**Issue by LOuroboros** [RPCS3/rpcs3#7124]
Using the [build e176f543 from AppVeyor](https://ci.appveyor.com/project/rpcs3/rpcs3/builds/29693837) _(which seems to work far, FAR better than v0.0.7-9227 btw)_, the game freezes when starting to load the assets of the very first map in the game, Overlook Road.

Here's a quick video I recorded: https://streamable.com/awldb
*Note: the main menu where the wizard is standing runs at 30 FPS without recording, which on itself feels like a great achievement. In v0.0.7-9227 that screen stutters like hell and jumps constantly from 17 to 20 something, for reference.*

Here's the settings that I modified from default:
![rpcs3-2019-12-21_10-40-59](https://user-images.githubusercontent.com/4485172/71308843-11699500-23e0-11ea-94a2-e5c3ad97fb5f.png)
![rpcs3-2019-12-21_10-41-02](https://user-images.githubusercontent.com/4485172/71308844-11699500-23e0-11ea-9f70-b7befe02154b.png)

And here's the log of the RPCS3 window:
https://justpaste.me/ifHA

I understand my rig may be uncapable of running PS3 flawlessly, but I figured that maybe my log and my report could be useful to someone somehow.

Keep up the good work guys. The effort poured into RPCS3 and how long it has come is simply amazing.

**Comment by AniLeo** [comment]
Issues need to be reported with the master branch, this is not a master build so the report is invalid. For issues with pull requests you need to report it on the pull request directly. 
#7121

**Comment by LOuroboros** [comment]
In the latest master build _(v0.0.7-9238, right? Please correct me if I'm wrong.)_ I get the exact same problem except that, as I said, the game stutters a lot more and it runs much worse, @AniLeo.

Video: https://streamable.com/7uume
Log: https://justpaste.it/65rxh

Same configuration I showed up there.

It would have been nice if you had given me the chance to reply instead of swiftly closing the issue.

**Comment by AniLeo** [comment]
You can always reply for reopening, the issue is always writable even if closed until it is locked

I've reopened the issue since you've reported it also happens with master build

**Comment by RainbowCookie32** [comment]
Can't reproduce here. As far as I know, the game freezes usually on lower end CPUs, which is likely what's happening here. 
![Diablo](https://user-images.githubusercontent.com/16805474/72193418-28e8dc00-33e8-11ea-8f85-5a9093a9d7ce.jpg)
The issue doesn't have a proper log attached to it either, just a copy from RPCS3's window.

**Comment by LOuroboros** [comment]
> The issue doesn't have a proper log attached to it either, just a copy from RPCS3's window.
What is a "proper log"?
I did some quick searchs on Google and I couldn't find explicit information. I thought the window's log was the only log.

I'm definitely willing to test this out again and provide "a proper log", just to clarify, though certainly:
> OP's CPU is way below recommended specs (i3-2120).
That could definitely be an issue, if not the cause of the issue. I wasn't sure of whether it was or not, and I still aren't.
That's why I originally posted this issue.

**Comment by RainbowCookie32** [comment]
To get a proper log, run the game, get to the freeze, close rpcs3, go to it's folder and look RPCS3.log.gz or just RPCS3.log. Then just upload that one here

**Comment by LOuroboros** [comment]
I noticed that I deleted RPCS3, so I had to set it up again pretty quickly.
Here's the RPCS3.log.gz compressed file made by RPCS3 v0.0.8-9365 downloaded from [RPCS3's website](https://rpcs3.net/download).
https://www105.zippyshare.com/v/MWOgmfbs/file.html

**Comment by RainbowCookie32** [comment]
Doesn't look like there's any specific issue I'm the log. I'd check with default settings just in case, but it's very likely that the game is just locking up because of low performance.

For reference, back when I had my R3 1200, most of the times I wouldn't get past the menu before freezing, because my CPU couldn't sustain enough performance. Once I moved to my R7 1700, those kinds of freezes disappeared

**Comment by LOuroboros** [comment]
> Doesn't look like there's any specific issue I'm the log. I'd check with default settings just in case, but it's very likely that the game is just locking up because of low performance.
> For reference, back when I had my R3 1200, most of the times I wouldn't get past the menu before freezing, because my CPU couldn't sustain enough performance. Once I moved to my R7 1700, those kinds of freezes disappeared

Understood. I knew this could be the outcome, but I had to make sure just in case.

If the problem is the hardware, it means that it's completely unrelated to the emulator and as such, this issue should be closed.
