### ISSUE TITLE
Shadow Striping in Gundam Extreme VS. Full Boost after PR#6774

### ISSUE THREAD

**Issue by delta7890** [RPCS3/rpcs3#7132]
After PR #6774 (RPCS3 v0.0.7-8920-5af8a9fb), I've noticed severe shadow striping in Gundam Extreme Vs. Full Boost.  This is present on both environments and player unit models.  Previous versions of the emulator did not have this issue.

[NPJB00512_20191224184218_capture.zip](https://github.com/RPCS3/rpcs3/files/3999199/NPJB00512_20191224184218_capture.zip)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3999204/RPCS3.log)

**Comment by kd-11** [comment]
It's always best to attach screenshots before and after so I can know what to look out for. Sometimes replaying the captures on different hardware can cause different results to appear.

**Comment by delta7890** [comment]
![exvsgood](https://user-images.githubusercontent.com/34465681/72465506-4da4d100-37a5-11ea-94a9-026ac5e43d67.PNG) Before: PR #6774 (RPCS3 v0.0.7-8920-5af8a9fb)
![exvsbad](https://user-images.githubusercontent.com/34465681/72465517-539ab200-37a5-11ea-91e8-4221c32c499b.PNG) After

**Comment by JumpingY** [comment]
It seems that this problem will only appear on NVIDIA GPU

**Comment by epyon102** [comment]
im having the same issue it seems as if the problem is with vulkan as opengl has no issues upon testing

**Comment by johnsonkiss** [comment]
> After PR #6774 (RPCS3 v0.0.7-8920-5af8a9fb), I've noticed severe shadow striping in Gundam Extreme Vs. Full Boost. This is present on both environments and player unit models. Previous versions of the emulator did not have this issue.
> 
> [NPJB00512_20191224184218_capture.zip](https://github.com/RPCS3/rpcs3/files/3999199/NPJB00512_20191224184218_capture.zip)
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/3999204/RPCS3.log)

Have you solved the problem? I have the problem, too.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/8445. If you can, please test with the PR build.

**Comment by Emulator-Team-2** [comment]
No changes with the (PR: https://github.com/RPCS3/rpcs3/pull/8445).

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/8451, please confirm.

**Comment by Emulator-Team-2** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/8451.
