### ISSUE TITLE
LEGO Harry Potter: Years 1-4 [BLES00720] Performance Regression

### ISSUE THREAD

**Issue by Kian-Stevens** [RPCS3/rpcs3#7133]
It appears as though this game suffered a performance regression all the way back in #6507 (a while ago, I know, but I haven't played this game in a while)

From extensive testing of builds, it ran at a smooth 60 FPS before that PR, but stutters a lot on ones after it; the performance gradually got worse up until the current build, where the frame rate and stuttering are the worst out of all the builds I tested
Strangely enough, opening Task Manager or File Explorer (essentially just putting RPCS3 in the background) seems to make the game run just fine on the problematic builds, i.e. it shoots up to 60 FPS with no stuttering

My specs are:
Intel i5-7600K
GTX 1050 Ti
16 GB RAM

And these are the settings used for all tests:
![Untitled](https://user-images.githubusercontent.com/31938249/71427128-7ce78700-26ac-11ea-92df-50d8c29534e4.png)
![Untitled2](https://user-images.githubusercontent.com/31938249/71427129-7f49e100-26ac-11ea-805e-4dfa95b1582a.png)
(As well as 'Disable ZCull Occlusion Queries' enabled in the Debug tab)

**Comment by Kian-Stevens** [comment]
Just to add: the person testing Persona 5 on #6580 seems to describe this very issue, in which their FPS increases to full when they're out of the emulator window (and subsequently decreases when they're back in it)

**Comment by digitaldude555** [comment]
update?

**Comment by Asinin3** [comment]
Can be closed. This was fixed by https://github.com/RPCS3/rpcs3/pull/9117 , same issue as https://github.com/RPCS3/rpcs3/issues/8363 and https://github.com/RPCS3/rpcs3/issues/7007
