### ISSUE TITLE
performance regression and choppy audio from pr #7064 "use WSAPoll on win32"

### ISSUE THREAD

**Issue by Nerboruto** [RPCS3/rpcs3#7137]
tested on 4 pc, intel bad performance, amd is ok.
game tested dragon's crown, ninja gaiden sigma, GOW ghost of sparta

e6700@3100mhz bad audio bad fps . previous build ok
xeon x3220@3150mhz bad audio bad fps . previous build ok

athlon x4 760k@4300mhz performance and audio ok
fx 8300@4200mhz performance and audio ok

every build after WSAPoll pr are bad on my old intel pc.

**Comment by dyno0** [comment]
Can confirm it also happens with Resident Evil 4 for builds 9224 and above, while 9223 works fine.

**Comment by digtal-devil** [comment]
Can confirm with Persona 5. 

In the Qliphoth World with builds before this, the field runs at 10-14 FPS while in battle, the FPS is 14-18. Audio quality is very good and stutters rarely happen.

In builds after this, the Qliphoth World field and battle runs at 1-4 FPS, with heavy stuttering and horrible audio quality. It's unplayable.

**Comment by Nerboruto** [comment]
> Can confirm with Persona 5.
> 
> In the Qliphoth World with builds before this, the field runs at 10-14 FPS while in battle, the FPS is 14-18. Audio quality is very good and stutters rarely happen.
> 
> In builds after this, the Qliphoth World field and battle runs at 1-4 FPS, with heavy stuttering and horrible audio quality. It's unplayable.
> 
> **EDIT :** Tried the latest build and now the menus load and run very slowly. I used to get a solid 30 FPS almost always in menus.
> 
> **EDIT 2 :** I updated my GeForce drivers to 441.66 from 430.86 and tried Persona 5 on the latest RPCS3 build (v0.0.7-9259). The performance is really bad and the shader compilation time takes a lot longer. Normally it takes about 2-3 minutes to get into the main menu of Persona 5 on builds 9219 and lower but build 9259 took atleast 7-10 minutes to get me to the main menu. Rolled back to build 9219 and both performance and shader compilation is back to normal.

intel or amd cpu? I noticed that the slowdown is not present on amd cpu

**Comment by digtal-devil** [comment]
I have an AMD CPU (FX 4100 3.6 Ghz Black Edition).
