### ISSUE TITLE
Bad analog sticks emulation on using keyboard

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#7144]
On using keyboard, there are only main axis directions emulate (x+/-, y+/-), but no intermediate ones. Some games really don't like it when some gestures required. For example, there are rain roll (middle of game) and gate's opening lever (in the end of game) in Silent Hill: Downpour, required to be rotated clockwise or counterclockwise, that just don't want to be rotated until we switch to gamepad. We just see player's attempts but even can't move them on inch!

I suggest to add some inertia or interpolation to keyboard presses when bound to sticks, to emulate intermediate axis values between two keys pressing. Maybe it's already in here, but judging noticed issues, it's obviously not enough.

**Comment by Megamouse** [comment]
already existing

**Comment by Psycho-A** [comment]
Can you point me, where? I couldn't find...

**Comment by Megamouse** [comment]
in the pad settings obviously

**Comment by Psycho-A** [comment]
I thought you mean my issue is duplicated here, sorry. You mean "Stick interpolation" setting? But how can it be configured to have most optimal interpolation values for the keyboard? For "1.0" there are issues I already described above.

**Comment by Megamouse** [comment]
1.0 means that no interpolation is applied.
The lower this value goes the smoother the stick will move. This is (for example) useful when you want the character to turn normally instead of simply snapping into that direction (0.0 means that you won't get any movement).
So try with 0.1 or whatever

**Comment by Psycho-A** [comment]
Oh, than you so much! Value of 0.2 fully solved all that kinds of issue!
