### ISSUE TITLE
Significant performance drop in Silent Hill: Downpour [BLUS30565]

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#7146]
I didn't test all intermediate builds for this time, but build 8637 had perfect and smooth performance on that game, while latest master (9254) just rapes my 4-core CPU with 100% load and constant freezes. Even the main menu screen shows 80-90% CPU load, although 8637 had only 40-45% and 60-75% during gameplay. I didn't change settings between these two builds, so the issue is not on my side.

**Comment by AniLeo** [comment]
Could be related to WSAPoll implementation, need to know what build decreased performance

**Comment by Psycho-A** [comment]
@AniLeo can you please tell me what the first build had this implemented? This will narrow my searches.

**Comment by isshininu** [comment]
Downpour does not even load existing autosave for me, for months. https://github.com/RPCS3/rpcs3/issues/6558

**Comment by Psycho-A** [comment]
I found the issue about WSAPoll in #7137, and tried build 9223. Raping my CPU is gone, but generic CPU load is still about 10-15% higher than at 8637, and FPS is a bit lower anyway. And yes, I have Intel CPU.

**Comment by Psycho-A** [comment]
@isshininu, It seems there were some changes in files encryption format, but if we'll start new game and use new saves, they'll be loaded normally. It happened since the issue you pointed.

**Comment by Psycho-A** [comment]
So, I want to sum up some results:

Build 8637 - everything fine.
Build 9065 - everything fine.
Build 9075 - CPU load is 10-15% higher (it seems it produced by Nekotekina's PR #6942 ??).
Build 9254 - CPU load is insane, game isn't playable because of constant freezes.

**Comment by AniLeo** [comment]
Should be closed then if issue is fixed. Slightly higher CPU load may be normal, if there's no significant performance regression there's no reason to keep this open.

**Comment by Psycho-A** [comment]
Well, I don't think that increasing load from 40-50% to 60-70% and FPS drop to 10% is "slightly". At least should be reason for that. As I wrote above, I found the first build when it happened, so maybe someone still will see on it.

**Comment by digitaldude555** [comment]
I'm getting 30fps everywhere. i5 6600.
