### ISSUE TITLE
Windows AMD 19.12 driver breaks OpenGL

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#7149]
_Meta issue for driver bug discussion_

---

Latest Windows AMD drivers no longer work render applications/games\* on OpenGL not even on the triangle test.
\* The performance overlays are still rendered, but not any application or game content

Vulkan is not known to be affected.

**Tested drivers:**
- 19.11.1 - Work
- 19.11.3 - Work
- 19.12.1 - Don't work
- 19.12.2 - Don't work
- 19.12.3 - Don't work

**Tested OS:**
- Windows 7 x64
- Windows 10 x64

**Comment by goedzo** [comment]
Can confirm. 19.11.3 has some graphic issues. See attached
![JPEG_20191229_142620](https://user-images.githubusercontent.com/23582713/71557583-5d53b400-2a48-11ea-831c-68433c8e2a58.jpg)

**Comment by AniLeo** [comment]
Test with 19.11.1 and the same RPCS3 version to see if it's a driver issue or a regression from a previous PR

**Comment by goedzo** [comment]
Tested on 19.11.1 and same opengl issue occurs. So could be a problem with my nightly version 0.0.7-9255-9f106be3

**Comment by kd-11** [comment]
Preliminary investigation shows vertex stage is completely borked. My initial guess is that vertex ID is not incrementing correctly.

**Comment by Doregon** [comment]
It looks like AMD Adrenalin solves this problem, no more graphics problems in the 2020 edition. It includes OpenGL and Vulkan drivers, so maybe installing that helps users with the new AMD drivers.

**Comment by AniLeo** [comment]
It was reported not to be working on 19.12.3 as well.

**Comment by AniLeo** [comment]
https://community.amd.com/message/2949336

Confirmed driver bug and being fixed by AMD

**Comment by benderscruffy** [comment]
still not fixed in 20.1.1

**Comment by kd-11** [comment]
Fixed by driver 20.1.4
![image](https://user-images.githubusercontent.com/15904127/73217357-d2f69100-4168-11ea-970a-582aff7045b5.png)
