### ISSUE TITLE
Feature Request: RPCS3 on ARM architecture

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#715]
I know most of you will be facepalming, raising the ban hammers, and laughing, but before you close this, hear me out at least (please): ARM64 is coming soon, and 3.0+GHz ARM processors will be happening in the foreseeable years. ARM processors will also have improved microarchitectures as manufacturers learn that the old IPW vs. IPC has to let up and ARM processors must depend on cycles and more power. The Xiamio Mi Pad is a tablet featuring an ARM SoC with NVIDIA, AKA NVIDIA Tegra K1, which has  OpenGL 4.4 support, 192 stream processors, and comes with a 2.2 GHz CPU that can be overclocked to 2.5 GHz. The guy who invented Play!, the alternative PS2 emulator to PCSX2, is very much considering and agreed to work on getting a JIT dynarec on ARM/Android for testing. Dolphin, the Gamecube/Wii emulator, runs near perfect on the latter, with just some optimizations needed. 

Assuming RPCS3 doesn't even have a stable dynarec for Intel, wouldn't now be the best time to consider cross-platform capabilities (before it's too ingrained and tailored to Intel)? For example, one could implement an ARM v7/v8 capable build with some dynamic recompilation, and/or the interpreters.
I realize the massive requirements TODAY, but in several years who knows if ARM processors are soon to reach comparability to Haswell i7s. My assumption is just that if you carried on and tailored RPCS3 just to one CPU architecture (Intel), you may end up in a rut like PCSX2, where they have no possible plans of ever getting it on other platforms, despite being stagnant for more than five years. Does anyone ever plan on having RPCS3 maybe someday in the future running on other processors, platforms, etc.? If so, one should at least consider that, despite ARM's very poor results now, when RPCS3 possibly gets somewhere stagnant along the line ARM64/3.0+GHz/etc. processors may hold their own and be somewhat capable of this. All I ask is that you consider this ... thanks.

**Comment by ruthan** [comment]
Is there now 3 years later strong enough ARM CPU+GPU board / machine?

**Comment by tanpro260196** [comment]
Well, we still doesn't have a decent emulator for the ps2 on arm...

**Comment by AniLeo** [comment]
Nope. 
ARM devices can barely run Dolphin as of today, PS3 emulation on current ARM CPUs would be a performance disaster, even on Snapdragon 835.

**Comment by ruthan** [comment]
> Well, we still doesn't have a decent emulator for the ps2 on arm...

  Now we have DamonPS2, using stolen code, but it seems to work, somehow.. But yeah it would take years, we still not have any ARM CPU with high TDP, Nvidia Jetson is still 15W device, if im not wrong..

  In theory it should not matters if emulator will translate PowerPC to x86 or to ARM. Doplhin is doing the same..

**Comment by AniLeo** [comment]
Yeah, but Dolphin doesn't emulate a console with a Cell processor at 3.2GHz with 2PPEs+6SPEs(+1)

**Comment by AlexAltea** [comment]
Playing devil's advocate for a second (and despite having little knowledge about Dolphin), I believe they have to deal with MMU and RPCS3 doesn't, since you guys just HLE `sys_memory_allocate` and return a valid pointer into the host process.

Performance aside, I'd bet there's hordes of guys waiting to play their PS3-exclusive visual novels on their phones. That's not very demanding and should run fine in most ARM-based systems.

**Comment by dio-gh** [comment]
There were some more discussions on this since in #testers. https://discordapp.com/channels/272035812277878785/483198470275203072/593493062005686336

**Comment by bevanweiss** [comment]
Is it worth having a list of known 'code roadblocks' that would prevent ARM compilation (i.e. down to the code file, and potentially function call level)?

I think the weaker ordering of the ARM CPUs might 'help' us to identify a few race conditions that we don't have proper guards around.

I've already been looking a little bit at some of the intrinsics that we have around the place, and potentially migrating them across to utilise SIMD Everywhere (https://github.com/simd-everywhere/simde).  That should reduce the burden of us implementing similar instructions in non-x86-64 platforms.

**Comment by clienthax** [comment]
Apple moving to arm could be interesting too

**Comment by Serentty** [comment]
M1 Macs definitely provide hardware powerful enough to run this. I know that RPCS3 currently only supports Windows and Linux, but I'm typing this from the ARM version of Windows on an M1 right now, so operating systems aren't too much of a barrier, and I wouldn't mind an ARM version for Windows and Linux even if it means I need to use a VM or reboot to run it.

**Comment by Mew8000** [comment]
We phone emulate switch think good started working ps3 emulator on phone like 10 years rpcs3 come out so stated rpcs3 mobile port.

**Comment by ruthan** [comment]
> M1 Macs definitely provide hardware powerful enough to run this. I know that RPCS3 currently only supports Windows and Linux, but I'm typing this from the ARM version of Windows on an M1 right now, so operating systems aren't too much of a barrier, and I wouldn't mind an ARM version for Windows and Linux even if it means I need to use a VM or reboot to run it.

   You are running Windows 10 ARM, on physical HW, or just virtually? Because i so far find only how to run them through Paralells.. https://www.youtube.com/watch?v=pVfQ9e1PhAY

**Comment by Serentty** [comment]
@ruthan There's no driver support yet in Windows, so you do need to use virtualization. But Parallels provides DirectX 11 hardware acceleration, so gaming isn't that bad.

**Comment by ruthan** [comment]
@Serentty Ne there never would be Windows driver, or it would be really first one good unofficial GPU driver from scratch.. BTW in video above are some games running through Steam, how it is working? Is there some inbuild Windows 10 ARM - x86 to ARM translation layer?

**Comment by A-Humane-Dragon** [comment]
Can RPCS3 be run on the Raspberry Pi? If so what model and what are the requirements for Linux based systems?

**Comment by ruthan** [comment]
Even if yes it wouldnt be able emulate anything more complex than Tetris.

**Comment by Nekotekina** [comment]
RPCS3 could be made multi-architecture with limitations. Not only a platform should be 64-bit. Also, for example, I'd like to assume that all pointers are 47-bit positive integers. If a platform can't provide such guarantees it coincidentally may be not worth a time investment. At least while absolute majority of decently capable PCs are running on x86-64.

**Comment by Serentty** [comment]
> @Serentty Ne there never would be Windows driver, or it would be really first one good unofficial GPU driver from scratch.. BTW in video above are some games running through Steam, how it is working? Is there some inbuild Windows 10 ARM - x86 to ARM translation layer?

Windows has x86 emulation on ARM, yes. It works decently well, but it's not as good as Apple's.

**Comment by kd-11** [comment]
Well, this came to pass finally. I think we can close this issue almost 8 years after it was opened.
PR: https://github.com/RPCS3/rpcs3/pull/11315
And yes, it does run some basic software https://github.com/RPCS3/rpcs3/pull/11315#issuecomment-1007108161
I tested it myself back then during development, it works only on linux and with low performance, but it is a working arm64 port that will improve over time.

**Comment by DrKipKnight** [comment]
Compiles fine on Raspberry Pi 5 if you use local ffmpg and comment out Dark Mode code (4-5 lines) due to old Qt < 6.5.  Unfortunately can't get through some Vulkan feature not present crash while running a game.
