### ISSUE TITLE
WRC5 - regression after #7064

### ISSUE THREAD

**Issue by Kravickas** [RPCS3/rpcs3#7151]
WRC 5 regression after #7064
Ingame -> Nothing

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4008350/RPCS3.log)

_____________________________________

With #7150 its still nothing, but SOMETIMES i get 
> E {Network Thread} sys_net: WSAPoll failed: 10038 x56

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4008353/RPCS3.log)

**Comment by Nekotekina** [comment]
Try #7150 again
