### ISSUE TITLE
Feature Request: Disable emulator update check

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#7153]
Sometimes updates are harmful for certain game setup, everytime I launch the outdated version it's annoying me by asking for update. Just asking for add a simple "Disable update check" checkbox in the "Emulator" tab of settings to let users decide will they update or not.

**Comment by MarioSonic2987** [comment]
The option was already present in GUI tab, only in global settings:
![image](https://user-images.githubusercontent.com/20027681/71561683-fa7b1080-2a79-11ea-876b-75e1bfdb7e2b.png)

**Comment by Psycho-A** [comment]
Oh, I didn't think it was in GUI tab, sorry.

**Comment by udance4ever** [comment]
I can't seem to find any documentation in regards to the new picklist.

What is the difference between "Yes", "Background" and "Automatic" in the current release?

![RPCS3 - Check for updates on startup](https://github.com/user-attachments/assets/7661770e-64f3-4bb2-8000-07e0d221868b)
