### ISSUE TITLE
Pre-compiling of shaders from disk takes longer than before

### ISSUE THREAD

**Issue by digtal-devil** [RPCS3/rpcs3#7155]
I've observed this to happen in 9276(#7150) and 9259. Persona 5 takes normally 2-3 minutes to load before I hit the main menu on builds 9223 and lower but on 9276 and 9259, it takes 7-10 minutes.

**Comment by MSuih** [comment]
This is most likely an issue with your driver's shader caching and not rpcs3. Try clearing the driver's shader cache and restarting the system between comparisons of different versions, you'll most likely see that the shader loading is slow for the first try and then speeds up after that when shaders are loaded from cache. Operating systems file caching is a factor as well.

**Comment by digtal-devil** [comment]
Restarting the PC fixed the problem. Load times are back to 2-3 minutes like before. Thank you :)
