### ISSUE TITLE
Error on exit since PR #7157

### ISSUE THREAD

**Issue by jacob1218** [RPCS3/rpcs3#7159]
RPCS3 produces an error message on exit after pr #7157 . Message pictured.
![image](https://user-images.githubusercontent.com/6559034/71606365-1daeca00-2b25-11ea-866c-249808ae3317.png)

**Comment by Andryshik345** [comment]
the same for me
![изображение](https://user-images.githubusercontent.com/24612088/71611666-a3ca1f80-2bbc-11ea-85ba-e2bb7bd6a4cf.png)
after click on "retry"
![изображение](https://user-images.githubusercontent.com/24612088/71611674-b5132c00-2bbc-11ea-9e1e-ecdbdca396d1.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4012007/RPCS3.log.gz)
