### ISSUE TITLE
[Regression] Ar Tonelico III stuck on black screen after boot

### ISSUE THREAD

**Issue by darkash** [RPCS3/rpcs3#7164]
Used version: 0.0.8-341fdf7e

Operating System:
Windows 10 build 1909
Ram: 8 GB
CPU: i7-8550U
GPU: Nvidia Geforce MX130

<details>
<summary>Ar Tonelico III</summary>

Vulkan
![image](https://user-images.githubusercontent.com/2842880/71641995-f566cd00-2cd6-11ea-8556-43beaadb5d5d.png)

OpenGL
![image](https://user-images.githubusercontent.com/2842880/71641997-0283bc00-2cd7-11ea-9f67-1707e0de7929.png)
</details>

I will try finding the offending commit and update it here, but the last version I know to be working is from months ago.

log file
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4014117/RPCS3.log.gz)

**Comment by darkash** [comment]
build 9295 is the cause
![image](https://user-images.githubusercontent.com/2842880/71642593-71194780-2ce0-11ea-99db-5b116fa473d4.png)

build 9294 loads just fine
![image](https://user-images.githubusercontent.com/2842880/71642614-9b6b0500-2ce0-11ea-9a5c-f2dd71ddd94d.png)

PR #6933

**Comment by darkash** [comment]
9294 log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4014164/RPCS3.log.gz)

9295 log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4014168/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Fixed by #7166
