### ISSUE TITLE
[Regression] Neither Castlevania LoS or LoS 2 will boot after PR#6933 merged

### ISSUE THREAD

**Issue by GarettJaxx** [RPCS3/rpcs3#7165]
As title - ver 0.0.7-9295 appears to have broken these 2x games, both verified working in ver 0.0.7-9294

I get the following error messages immediately upon boot:

**Castlevania - LoS**
![image](https://user-images.githubusercontent.com/46201027/71642908-7b205380-2caa-11ea-87d5-9f0bfa2e98f7.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4014197/RPCS3.log.gz)

**Castlevania - LoS 2**
![image](https://user-images.githubusercontent.com/46201027/71642929-b3279680-2caa-11ea-8c68-b8ae5687e80d.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4014198/RPCS3.log.gz)

in both cases, the emulator is still running and hasn't frozen, reverting back to 9294 allows them to be played as normal

**Comment by AniLeo** [comment]
Fixed by #7166
