### ISSUE TITLE
Kingdom Hearts HD 1.5 COM [BLUS31212] Verification Failed

### ISSUE THREAD

**Issue by Baxusfox** [RPCS3/rpcs3#7170]
RPCS3 v0.0.8-9302-c4e59b51 Alpha | Firmware version: 4.84
Windows 10 Version 10.0.19536 Build 19536
NVIDIA GeForce GTX 1070
Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz | 8 Threads | 15.94 GiB RAM | TSC: Bad | AVX

When entering the next room, during the cutscene with Pinocchio, the game freezes and stops running.

Log [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4014561/RPCS3.log.gz)

Save File [BLUS31212-BISLPM66676COM.zip](https://github.com/RPCS3/rpcs3/files/4014562/BLUS31212-BISLPM66676COM.zip)

![Annotation 2020-01-01 161854](https://user-images.githubusercontent.com/40281591/71646380-ae1c1480-2cb5-11ea-8c2b-5d515698037a.jpg)

**Comment by 13xforever** [comment]
You have a bad game dump, this issue is invalid

**Comment by Baxusfox** [comment]
> 
> 
> You have a bad game dump, this issue is invalid

Ah ok. I'll do a new dump then. Thank you.

**Comment by Baxusfox** [comment]
I just used your PS3 dumping tool and I'm still receiving
 the same error.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4014625/RPCS3.log.gz)

**Comment by Baxusfox** [comment]
Seems to be a vulkan issue. I switched to openGL and made it past the cutscene.

**Comment by Emulator-Team-2** [comment]
@AniLeo 
This error was fixed by #7259.
Close this issue.
