### ISSUE TITLE
SPU Memory leak on Guitar Hero 5

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#7172]
During a song playthrough RAM will increase until it's maxed out and computer hangs. Upon trying to boot the game again, it will get stuck on building SPU cache's last module while maxing out RAM (16GB) and never complete.

[spu-safe-v1-tane.zip](https://github.com/RPCS3/rpcs3/files/4014576/spu-safe-v1-tane.zip)

Tested with different hardware on both Windows & Linux

**Comment by Nekotekina** [comment]
Does SPU ASMJIT build cache without problems?

**Comment by AniLeo** [comment]
Yes, and it builds instantly

**Comment by AniLeo** [comment]
Yahfz reported it doesn't happen on an 8700K.

I've tested this on both FX-8350 (Win7) and R7 2700X (Manjaro) and it happens on both.

**Comment by mavethee** [comment]
SPU Memory leak in Need for Speed™ Hot Pursuit [NPEB00587]
[spu-safe-v1-tane.zip](https://github.com/RPCS3/rpcs3/files/4050600/spu-safe-v1-tane.zip)
https://media.discordapp.net/attachments/319224795785068545/665882629177868289/unknown.png?width=753&height=670
Also this makes unable to load the game when SPU cache exists.
"E {PPU[0x1000000] Thread (main_thread)} LLVM: Linkage failed: __mfspr_136"

**Comment by AniLeo** [comment]
Confirmed fixed
