### ISSUE TITLE
Skate 3 random crash (VK_ERROR_DEVICE_LOST) [BLES00760]

### ISSUE THREAD

**Issue by Cereal-Killa** [RPCS3/rpcs3#7191]
Can happen at any time, any level, really random but does happen to me on this latest build.

`S {SPU LLVM} SPU: New block compiled successfully
E {PPU[0x1000001] Thread (null:) [0x01c52090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/data/audio/doorman_whistle.abk” [3]
E {PPU[0x1000001] Thread (null:) [0x01c52090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00760_INSTALL/USRDIR/data/audio/doorman_whistle.abk” [3]
E {RSX [0x01112dc]} RSX: CB chain has run out of free entries!
F {RSX [0x0111360]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:3045)`

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4021041/RPCS3.log.gz)

**Comment by kd-11** [comment]
Retest current master.

**Comment by Cereal-Killa** [comment]
Seems fixed to me, no crashes at all anymore.
Thank you!
