### ISSUE TITLE
Isn't this a wrong behaviour when deleting cache?

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#7212]
If you use any of the options to clear the cache,it doesn't matter how deep(in sub folders)shaders cache is,rpcs3 will delete it

cache\gameid\ppu-numbers\shaders_cache
Using the option will delete the shaders_cache folder as expected
Renaming the folder,will prevent the option from deleting them...as expected
Moving the folder in no matter how many number deep in sub folders,the option will also delete it
cache\gameid\ppu-numbers\1\1\1\1\1\shaders_cache

**Comment by Megamouse** [comment]
Expected behaviour

**Comment by vsub** [comment]
Ok,then
