### ISSUE TITLE
[Regression] Golden Axe: Beast Rider/Iron-Man/Sword Art Online: Lost Song crashes when Force CPU Blit is not enabled since pr #6797.

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#7225]
These games crash on the loading screen with a fatal error when `Force CPU Blit` is not enabled.

[ Iron-Man-Demo ]

```
RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2577)
```

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4042769/RPCS3.log.gz)

------------------------------------------------------------------------------------------------------

[ Golden Axe: Beast Rider ]

```
RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2577)
```

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4042780/RPCS3.log.gz)

------------------------------------------------------------------------------------------------------

[ Sword Art Online: Lost Song ]

Build: #6797 - 0.0.7-8956
```
RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2566)
```

Build: 0.0.7-9029
```
RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2564)
```

Build: 0.0.7-9164
```
RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2577)
```

Build: 0.0.8-9370
```
RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2577)
```

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4060880/RPCS3.log.gz)

**Comment by Emulator-Team-2** [comment]
@kd-11 
This regression started since pull request #6797.

**Comment by Emulator-Team-2** [comment]
These games with `Force CPU Blit` enabled look like this.

1. [ Iron-Man-Demo - White texture at the bottom of the screen. ]
![1](https://user-images.githubusercontent.com/38318848/72375078-b93a6000-370b-11ea-8b53-57367c0a7ea4.png)

--------------------------------------------------------------------------------------------------------

2. [ Golden Axe: Beast Rider - White texture at the bottom of the screen. ]
![2](https://user-images.githubusercontent.com/38318848/72375153-df600000-370b-11ea-97c9-8dbae9bd8849.png)

--------------------------------------------------------------------------------------------------------

3. [ Sword Art Online: Lost Song - Broken graphic. ]
![3](https://user-images.githubusercontent.com/38318848/72375247-07e7fa00-370c-11ea-933e-12d8ec8c3019.png)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/7259

**Comment by Emulator-Team-2** [comment]
I confirm the issue is now fixed by https://github.com/RPCS3/rpcs3/pull/7259.
Tested with `Default Settings`.

[ Iron-Man-Demo ]
![1](https://user-images.githubusercontent.com/38318848/72527551-4fd06380-3869-11ea-9672-ef780676cde8.png)

--------------------------------------------------------------------------------------------------------

[ Golden Axe: Beast Rider ]
![2](https://user-images.githubusercontent.com/38318848/72527605-6d9dc880-3869-11ea-9764-8b207729ba1f.png)

--------------------------------------------------------------------------------------------------------

[ Sword Art Online: Lost Song ]
![3](https://user-images.githubusercontent.com/38318848/72527647-827a5c00-3869-11ea-84ee-2ced4c69fb7c.png)
