### ISSUE TITLE
[UI] Deleting game data with Read Only flag doesn't report failure

### ISSUE THREAD

**Issue by CookiePLMonster** [RPCS3/rpcs3#7228]
If for some reason Read Only flag is ticked on game data and user prompts to delete the game, RPCS3 claims it's deleted the game successfully while in fact it failed to do so. This results in an odd situation where success is reported, despite the game not disappearing from the UI list at all.

It may or may not be same with caches, but Read Only caches are obviously more disastrous than just having Read Only game data.

**Comment by Megamouse** [comment]
~~User error~~
