### ISSUE TITLE
Time played statistics are unset if changing GUI configuration .ini

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#7237]
Since they're stored on the GUI configuration file, these will be unset if you change the GUI .ini file. These should ideally be stored somewhere where it doesn't change if the settings .ini is changed.

Furthermore, if you change config to **default** and then set them back to **CurrentSettings.ini** the CurrentSettings file will be reset and that will cause the loss of the time played statistics.

_Tested on Manjaro Linux, assuming it behaves the same on Windows_

**Comment by HerrHulaHoop** [comment]
I've been meaning to open an issue for this exact issue but never got around to it. Thanks for opening it!

IMO information relating to last played date, total playtime and special titles should be stored separately so that it doesn't disappear when the CurrentSettings.ini gets nuked.

**Comment by Megamouse** [comment]
Please test
