### ISSUE TITLE
[BLUS30901] [Regression] Hyperdimension Neptunia mk2 

### ISSUE THREAD

**Issue by BuIlDaLiBlE** [RPCS3/rpcs3#7240]
Heavy graphics glitches started happening since [0.0.7-9151](https://github.com/RPCS3/rpcs3/pull/7000), every intro screen is just a white screen. Main menu background is absent, many graphics in the game are also shown as white squares.
I'm using the latest (atm) build 0.0.8-9366-765bd6b6.
![image](https://user-images.githubusercontent.com/12040085/72272629-0221e400-363a-11ea-819f-5924e37f4281.png)
![image](https://user-images.githubusercontent.com/12040085/72272812-4a410680-363a-11ea-86e5-711cdaeff6e8.png)
![image](https://user-images.githubusercontent.com/12040085/72272968-91c79280-363a-11ea-803b-c97588b3c1af.png)
I'm also attaching a log with my PC config and current settings, the same settings work fine in any version lower than 0.0.7-9151.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4054607/RPCS3.log.gz)
[BLUS30901 Regression RSX.7z](https://bpnet.host/files/BLUS30901%20Regression%20RSX.7z)
[BLUS30901 Regression RSX (Working).7z](https://bpnet.host/files/BLUS30901%20Regression%20RSX%20(Working).7z)

--- BLUS31150 (Hyperdimension Neptunia Victory) issue ---
#7330 mostly fixed the game, but it still has some minor graphical glitches. They seem to appear after some time, not at the beginning of the game. These glitches include corruption of controller buttons and character pictures. I took two RSX captures, the first one is when graphics are ok, the second one is when they have become corrupted. I'm using US version of the game though but I don't believe that matters. I've also attached save data with which you can easily trigger this glitch. Simply load the save and go to the dungeon with event marker, you'll see the glitches immediately. You can then exit back to the menu and see that controller buttons pictures have disappeared.
[BLUS31150 Regression RSX.7z](https://bpnet.host/files/BLUS31150%20Regression%20RSX.7z)
[BLUS31150 Regression Save Data.zip](https://github.com/RPCS3/rpcs3/files/4119526/BLUS31150.Regression.Save.Data.zip)

**Comment by kd-11** [comment]
You need to provide RSX capture files. Ask on discord if you need help in doing so.

**Comment by BuIlDaLiBlE** [comment]
> You need to provide RSX capture files. Ask on discord if you need help in doing so.
Oh, right. I've took a few and included those to the issue.

**Comment by kd-11** [comment]
I suppose I'll need RSX capture from a working build to compare. I tried debugging with the regressed one but the raw data was seemingly also affected.

**Comment by BuIlDaLiBlE** [comment]
> I suppose I'll need RSX capture from a working build to compare. I tried debugging with the regressed one but the raw data was seemingly also affected.

Sure. I attached a second set of captures from build 0.0.8-9433.

**Comment by Emulator-Team-2** [comment]
@BuIlDaLiBlE 
Kd-11 wanted you to attach, rsx capture from the last working build, e.g. `0.0.7-9146`.

**Comment by BuIlDaLiBlE** [comment]
> @BuIlDaLiBlE
> Kd-11 wanted you to attach, rsx capture from the last working build, e.g. `0.0.7-9146`.

OH! Man I feel dumb now... sure, I updated the post.
Btw, kinda unrelated but are any of you aware of the framerate slowdown when RPCS3 window is active? Started happening long time ago it seems (probably in some build of 0.0.6 or 0.0.7), but older builds such as 0.0.5 don't have this weird issue for me.

**Comment by Emulator-Team-2** [comment]
@BuIlDaLiBlE 
There is an open issue regarding this problem https://github.com/RPCS3/rpcs3/issues/7007.

**Comment by BuIlDaLiBlE** [comment]
> @BuIlDaLiBlE
> There is an open issue regarding this problem #7007.

Good to know someone else already created an issue about this.

**Comment by BuIlDaLiBlE** [comment]
Continuing from #6735, I've updated this issue to also include Hyperdimension Neptunia Victory.

**Comment by kd-11** [comment]
@BuIlDaLiBlE How about mk2? Does it also get graphics corruption after some time with the PR build?

**Comment by BuIlDaLiBlE** [comment]
> @BuIlDaLiBlE How about mk2? Does it also get graphics corruption after some time with the PR build?

No, the graphics in that game seem to be perfect.

**Comment by kd-11** [comment]
A specific tracker for victory exists https://github.com/RPCS3/rpcs3/issues/7063

**Comment by BuIlDaLiBlE** [comment]
> A specific tracker for victory exists #7063

Should I add my report to there then?

**Comment by kd-11** [comment]
Is it not the same issue?

**Comment by BuIlDaLiBlE** [comment]
> Is it not the same issue?

Hm, it does look similar. Still, my RSX captures and save data should be useful for investigation of that issue.
Aside from Victory, I also believe there is a tiny weird graphics thing with mk2 still present. Not sure how to describe it best though, maybe comparison screenshots will be enough for that. I can't provide them right now though and I'm not sure if another issue really needs to be opened for that as it is really tiny.

**Comment by kd-11** [comment]
Anything that has always been broken is not a major priority, I'm trying to weed out regressions quickly so regular development can proceed. If the glitches were always there, they do not have to get fixed right now.
I can reproduce the glicthing in Victory, we'll see what can be done about it.

**Comment by BuIlDaLiBlE** [comment]
Then I believe that's all for this issue. AFAIK it should autoclose when the PR is merged. Thanks for doing the complicated graphics work!
