### ISSUE TITLE
Emulator doesn't start after updating to the 0.0.8-9369 ver.

### ISSUE THREAD

**Issue by vietnam13231** [RPCS3/rpcs3#7243]
After updating RPCS3 from 0.0.8-9367 to 0.0.8-9369 (literally one version newer) the window of RPCS3 doesn't show up. It shows up in task manager, but there is nothing else happening for 5 minutes. In the log after forcing RPCS3 process to stop there are only those 5 lines:

RPCS3 v0.0.8-9369-a2451465 Alpha | HEAD | Firmware version: 4.85

Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz | 16 Threads | 15.87 GiB RAM | TSC: Bad | AVX+ | TSX-FA

Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0

·! 0:00:00.000000 RSX: Found vulkan-compatible GPU: 'GeForce GTX 1080' running on driver 436.2.0.0

·! 0:00:00.000026 RSX: Found vulkan-compatible GPU: 'Intel(R) UHD Graphics 630' running on driver 0.401.94

All that is needed to reproduce this is go back to 0.0.8-9367 and update to 0.0.8-9369 (either auto or manual update, doesn't matter).

Specs (if needed):
Win 10 1903
Intel I9-9900k
Nvidia GeForce GTX 1080
RAM: 16GB 3200Mhz DDR4 
Running of the SSD

**Comment by Asinin3** [comment]
Works on my machine. Megamouse did update Qt though in that build so you need to make sure you have the new dll's which are included in the newest builds. I am on windows 10 1903 as well.

**Comment by vsub** [comment]
Works fine here
0.0.8-9371 and 0.0.8-9366 auto updated to 0.0.8-9371

**Comment by vietnam13231** [comment]
Well, I downloaded 0.0.8-9369 from AppVeyor and pasted all files into my RPCS3 dir (which is why I said it happens even with manual update) and I still have this problem.

This is how it looks on my PC:
![obraz](https://user-images.githubusercontent.com/16107604/72383519-ee4eae80-371b-11ea-93de-1fc5f02b3886.png)

**Comment by xperia64** [comment]
I deleted my cache folder and the "bearer" (I think that was it?) folder, and it launches again

**Comment by vietnam13231** [comment]
@xperia64 Yup, that helped. Thanks. Still weird it happened...

**Comment by hockland** [comment]
That fixed it for me as well

**Comment by RainbowCookie32** [comment]
The cache folder was probably unrelated btw
