### ISSUE TITLE
RPCS3 crashing in Vulkan API (using Sonic Unleashed as a reference).

### ISSUE THREAD

**Issue by vanderleivieirainacio** [RPCS3/rpcs3#7247]
Vulkan API crashing the game at random causing it to freeze the screen.
![Anotação 2020-01-15 001850](https://user-images.githubusercontent.com/46516229/72402195-31fde400-372d-11ea-8cff-9a1897569958.png)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
