### ISSUE TITLE
Broken GUI and low res game icons since #7230

### ISSUE THREAD

**Issue by mavethee** [RPCS3/rpcs3#7248]
Latest master, but it started since #7230
https://media.discordapp.net/attachments/277227681836302338/666904501982199819/unknown.png?width=1249&height=670
Game Icons for some reason became low res, for comparision, look at this pic:
https://media.discordapp.net/attachments/277227681836302338/666905112484118538/unknown.png?width=1249&height=670
Broken GUI (some treaky issues with scalling or idk what):
![image](https://user-images.githubusercontent.com/47083527/72415062-f4707980-3773-11ea-8ecb-6b34dc90774f.png)
![image](https://user-images.githubusercontent.com/47083527/72415121-1833bf80-3774-11ea-9e9a-8e51e3a4caaf.png)
Even if I changed whole OS to 100% still looks super weird a way too big. Here latest master and older build to compare:
https://media.discordapp.net/attachments/277227681836302338/666910858844176394/unknown.png?width=1133&height=671
https://media.discordapp.net/attachments/319224795785068545/666912459210358784/unknown.png?width=1144&height=671

**Comment by Andryshik345** [comment]
Also it looks like a font is affected too(at least on YoRHa skin, other skins is just using system font and it looks right). Installing the SCE-PS3 Rodin LATIN is not fixing that problem.
latest:
![Screenshot_1](https://user-images.githubusercontent.com/24612088/72433787-f0684a00-37bb-11ea-8ac2-d127cc25bc7f.png)

before new Qt version update:
![Screenshot_2](https://user-images.githubusercontent.com/24612088/72433788-f100e080-37bb-11ea-92a7-e554ba4d2901.png)

Looks like anti-aliasing is off.

**Comment by Megamouse** [comment]
Gonna close this because the first bug is fixed and there's a newer ticket for the second one
