### ISSUE TITLE
D3D12 in config.yml

### ISSUE THREAD

**Issue by wheelmac92** [RPCS3/rpcs3#7250]
![image](https://user-images.githubusercontent.com/58401060/72446523-bb3f0600-3781-11ea-9b72-369ae5d0cd62.png)

Looks like this was left over from the old D3D12 backend. Should it be removed from the config file?

**Comment by MSuih** [comment]
The setting has been removed, but the entry will stay in config.yml until it is manually removed or the config file is deleted and recreated from defaults.

**Comment by AniLeo** [comment]
If you remove the file and generate a new one it won't be there anymore, it's not left over in code
