### ISSUE TITLE
No more heroes BLES01101 not installing

### ISSUE THREAD

**Issue by Emogop** [RPCS3/rpcs3#7254]
![Screenshot_155](https://user-images.githubusercontent.com/42875723/72460816-9927a100-37de-11ea-8e77-8f8c5fe3a6d4.png)
Emulator doesn't hang, the fps counter is active.

Last 3 lines of the log:
E {PPU[0x1000000] Thread (main_thread) [0x00ca1f44]} 'sys_fs_unlink' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES01101/USRDIR/INSTALL.SYM” [1]
E {PPU[0x1000000] Thread (main_thread) [0x009b02f8]} cellSysutil: “Installing game data.
Please do not turn off your system while installing.”

**Comment by AniLeo** [comment]
Post disc checksum with PS3 ISO Rebuilder and a log file

**Comment by Emogop** [comment]
![Screenshot_156](https://user-images.githubusercontent.com/42875723/72482369-84fb9800-380e-11ea-9227-2006b05095bf.png)
Like this?
And log file gets too big (5mb in 10 seconds)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4068492/RPCS3.log)

**Comment by AniLeo** [comment]
That doesn't seem to be compressed, seems way too big, I can't download it that way

**Comment by Emogop** [comment]
![Screenshot_158](https://user-images.githubusercontent.com/42875723/72508822-6e2d6380-3857-11ea-8fc1-b5caf10dacd0.png)

Oh, somehow updating the emulator to the newest version solved the problem. I'm closing this issue.
