### ISSUE TITLE
Vulkan API call failed

### ISSUE THREAD

**Issue by Anderstend** [RPCS3/rpcs3#7263]
Hello,

i just wanted to inform you that i get the following error message in infamous2 [BCES01143] and castelvania [BLES01047] since approx. a week now: Vulkan API call failed with unrecoverable error: Out of pool memory (VK_ERROR_OUT_OF_POOL_MEMORY_KHR) after a few minutes of playing.

I'm using #9390 with a AMD Ryzen 5 3600 CPU and a Radeon RX Vega GPU. I tried different compiler options and as well disable vulkan memory allocator. It has no effect, I get alway the same issue. Before i played both games for hours with no issue.

best regards

**Comment by vanderleivieirainacio** [comment]
Glad someone else saw this problem, thanks! There is also this same bug in the SONIC UNLEASHED game [NPUB31204].
![Anotação 2020-01-15 101915](https://user-images.githubusercontent.com/46516229/72579531-1ffc7c80-38b8-11ea-88c4-9118165bedbb.png)
