### ISSUE TITLE
[BLJM60527] 初音ミク -Project DIVA- F - Graphical glitch

### ISSUE THREAD

**Issue by pCloudsp** [RPCS3/rpcs3#7265]
Hatsume Miku Diva F Japanese version started to have bars on the top of the screen that blocks elements under it. Every time enter/exit the gameplay, or navigating around the menu makes the pattern change.
Screenshots:
![2](https://user-images.githubusercontent.com/27007705/72586645-86859880-38c0-11ea-93e8-128a8e08be84.png)
![1](https://user-images.githubusercontent.com/27007705/72586653-8e453d00-38c0-11ea-8e30-73dcaacfbe52.png)
working screenshot
![image](https://user-images.githubusercontent.com/27007705/72587611-b4b8a780-38c3-11ea-8457-f82ff0a5ea1b.png)

Commit hash: e2512e7
Log (broken):
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4075216/RPCS3.log.gz)
Log (last working):
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4075223/RPCS3.log.gz)

System spec: R5 1600 / RX 580 8G / Windows 10 1909

**Comment by kd-11** [comment]
Confirmed, I accidentally broke it with the last commit. Will push a fix ASAP.
