### ISSUE TITLE
Alien Isolation - unimplemented 6ch audio.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#7272]
Some videos in USM format contains no audio and can be played by emulator, however several of them contains 6ch audio, maybe 2ch too.
Those can't be played and cause game to stuck.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4079003/RPCS3.log.gz)

**Comment by TigiHof** [comment]
In order to generate more interest for this long term issue I have posted a bounty of 50 USD over at BountySource for anyone willing to fix this:
https://www.bountysource.com/issues/87156170-alien-isolation-unimplemented-6ch-audio
