### ISSUE TITLE
Gran Turismo 6 - Crashes with VK_ERROR_INCOMPATIBLE_DISPLAY_KHR

### ISSUE THREAD

**Issue by RainbowCookie32** [RPCS3/rpcs3#7274]
This is running on Manjaro, with RADV LLVM 9.0.1 on an RX 570.
Happens always when loading into a race, either just before starting to show 3D graphics or after a few seconds.
Example of the moment when it crashes:
![image](https://user-images.githubusercontent.com/16805474/72654908-6d3c2500-3970-11ea-8c9f-eac3cf1c6e55.png)

Doesn't seem to be a regression. I've always had this issue on Linux, but I don't remember ever having it on Windows.
Attaching a log with Debug Output enabled:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4079765/RPCS3.log.gz)

Let me know if you need anything else.

**Comment by kd-11** [comment]
How does anyone ever get this game to actually run?

**Comment by Andryshik345** [comment]
@kd-11 i've noticed that game is crashing, if SPU decoder is set to LLVM. On ASMJIT it runs.

**Comment by RainbowCookie32** [comment]
Unrelated to the issue, and probably causes by overall instability of the game. It runs fine for me on LLVM

**Comment by kd-11** [comment]
From the log, it appears RSX is running in a 'bad' state and bogus data is being passed for rendering. Could be some race condition depending on both settings and user hardware setup.

**Comment by RainbowCookie32** [comment]
Adding to this: I can't reproduce the issue in Windows, yet in Manjaro it's always there consistently.

**Comment by RainbowCookie32** [comment]
Update: After doing some testing, the crash seems to only happen when CPU Blit is enabled, which is needed to avoid screen flickering. Without CPU Blit the game runs fine until a random freeze (which is "normal" GT behavior).

[RPCS3.tar.gz](https://github.com/RPCS3/rpcs3/files/4719523/RPCS3.tar.gz)

**Comment by RainbowCookie32** [comment]
Got a new log with Debug Output enabled, took a while to get. The error doesn't seem to trigger if it runs at slower framerates, which is Debug Output's specialty, managed to get it by disabling MSAA.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4739158/RPCS3.zip)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/8455

**Comment by RainbowCookie32** [comment]
Fixed indeed, thanks kd :+1: 
![Screenshot from 2020-06-17 16-10-09](https://user-images.githubusercontent.com/16805474/84939666-0c4a8180-b0b5-11ea-9611-12881eec2bfa.png)
