### ISSUE TITLE
Blade Arcus from Shining [BLJM61310] - offset ingame

### ISSUE THREAD

**Issue by Aurez** [RPCS3/rpcs3#7277]
Partial display offset ingame (very old bug, but appears to be not reported)
(I tried approx every options but it is always present even with OpenGL)

![Image2](https://user-images.githubusercontent.com/45921529/72668733-23b01080-3a2a-11ea-9c2d-c469954ba41b.jpg)

**Comment by kd-11** [comment]
Looking at this, its probably a game using GL_CLAMP to sample. A fix for these old game techniques requires a feature to be added so I'll first verify if that is the case and skip it for now if it is. A texturing rewrite is scheduled for soon and will automatically fix such problems.

**Comment by kd-11** [comment]
Looks to be a legit issue surprisingly, not clamping as I initially thought. Looking back, I seem to have gone down this same path 3 years ago but didn't reach a conclusion.

**Comment by kd-11** [comment]
Ok, turns out we completely forgot about 24-bit render targets; they're very poorly supported on rpcs3. I'll write up some hardware tests, this is now a major task as initial half-fix is not working correctly.

**Comment by kd-11** [comment]
Fixed by v
https://github.com/RPCS3/rpcs3/pull/8476
