### ISSUE TITLE
Mortal Kombat vs. DC Universe [NPUB30594] - wrong ratio in 1080p

### ISSUE THREAD

**Issue by Aurez** [RPCS3/rpcs3#7278]
The ratio is wrong when the game is set to 1920x1080 (4:3 instead of 16:9)
This is a very old bug I always had with this game but it seems to be not reported

![Image1](https://user-images.githubusercontent.com/45921529/72668815-e0a26d00-3a2a-11ea-9563-e6357b58b7fa.jpg)

**Comment by kd-11** [comment]
This is not a bug. You set it to render an aspect ratio of 4:3 so the game rendered to your 'TV' setting of 4:3. i.e you're telling the game you have a square old-school TV. Note how the graphics aren't stretched or deformed. The same thing would happen on a PS3.

**Comment by Aurez** [comment]
The ratio was set to 16:9 btw, it just crashes if you set 4:3

**Comment by Asinin3** [comment]
Don't set resolution to 1920x1080. 1280X720 says recommended for a reason. Most games either don't support it, or work at a res inbetween 1280x720. Aside from a very few cases it should really never be used. Use 150% resolution scaling to get 1080p output instead. Next time, read the tool-tips for settings.

**Comment by kd-11** [comment]
This game does not support 1920x1080 from what I can tell. Max resolution is 1280x1080 which is 4:3. When you set your TV res to 1920x1080, it does not use 1920x1080; instead it selects 1280x1080.
As such, unless it can be shown to run on a 1080p non-HDMI TV with only the 1080p resolution selected, I'm inclined to believe this game was just badly written.
The way the emulator works is we give the game a virtual TV with the resolution you select, but without the other resolutions. You cannot find a HDMI 1080p TV with no 720p support obviously, so this setup is only possible on AV cables. I don't know if they support 1080p though.

**Comment by kd-11** [comment]
I think because it is not possible to find a 1080p display without 720p support, some games are not coded to take that situation into account and use a fallback path instead. Its also why using the old 'auto' aspect ratio was causing black screens - because games were never coded to take it into account as it doesn't exist in the real world.

**Comment by Aurez** [comment]
ok I was thinking the that now only the supported resolutions were listed for each game. And 1920x1080 is listed for this game.

**Comment by kd-11** [comment]
It supports 1080p displays by rendering at 720p and 1080p in 4:3. I have the game, I have tested it.

**Comment by Aurez** [comment]
ok so thanks for the explaination and sorry for the false issue.
