### ISSUE TITLE
Access violation - inFamous 2 [BCES01143]

### ISSUE THREAD

**Issue by Anderstend** [RPCS3/rpcs3#7280]
Hello Guys,

thanks for fixing the Vulkan API error in #7263. But now i get MEM: Access violation at the exact same points in the game.

**Comment by AniLeo** [comment]
Probably invalid as a regression report, but needs more information

**Comment by kd-11** [comment]
You're missing a bunch of information including:
- Game ID and title
- Log file showing the exact problem
- Explanation of what happens with alternative settings e.g OpenGL, ASMJIT, interpreters, etc

**Comment by Anderstend** [comment]
Sorry for the late answer.
The Games is inFamous 2 [BCES01143]. I tried ASMJIT and LLMV with the same result, that the game stops inbetween exactly at the same point, where the vulkan API error occured before.
The the last few lines of the log are:
U {PPU[0x1000000] Thread (main_thread) [0x00bb0c78]} cellCamera TODO: cellCameraSetAttribute(dev_num=0, attrib=9=LED, arg1=0, arg2=0)
E {RSX [0x0011000]} RSX: [Performance warning] Unexpected ZCULL read caused a hard sync
U {PPU[0x1000000] Thread (main_thread) [0x00bb0c78]} cellCamera TODO: cellCameraSetAttribute(dev_num=0, attrib=9=LED, arg1=0, arg2=0)
E {RSX [0x0012000]} RSX: [Performance warning] Unexpected ZCULL read caused a hard sync
U {PPU[0x1000000] Thread (main_thread) [0x00bb0c78]} cellCamera TODO: cellCameraSetAttribute(dev_num=0, attrib=9=LED, arg1=0, arg2=0)
F {PPU[0x1000000] Thread (main_thread) [0x0046bfa8]} MEM: Access violation reading location 0x1c

**Comment by RainbowCookie32** [comment]
Attach the full RPCS3.log.gz file from the emulator's folder instead of copying stuff from its window

**Comment by Anderstend** [comment]
I couldn't catch the .gz-file because rpcs3 breaks down too. But i got the log file after restarting it.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4099644/RPCS3.log)

**Comment by AniLeo** [comment]
·! 0:05:25.534385 {PPU[0x1000000] Thread (main_thread) [0x0046bfa8]} 
Last function: cellKbGetInfo
·F 0:05:25.534394 {PPU[0x1000000] Thread (main_thread) [0x0046bfa8]} MEM: Access violation reading location 0x1c

**Comment by Anderstend** [comment]
Got the log-file with a newer version of rpcs3.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4227695/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
Needs update. @Anderstend

**Comment by Asinin3** [comment]
No update, closing.

**Comment by DxTea** [comment]
same error
