### ISSUE TITLE
The Godfather Don's Edition - flickering cubemaps

### ISSUE THREAD

**Issue by CookiePLMonster** [RPCS3/rpcs3#7286]
Nowadays the game seems to be running and rendering nearly perfectly, with the exception of cubemap reflections flickering. It would seem like cubemaps render properly every other frame, for example:

(ignore transparency issues, they are not present in the game nor on captures, looks like I just chose wrong settings while saving the JPG)

"Good" frame, notice reflections on the car:
![good-frame](https://user-images.githubusercontent.com/7947461/72678625-015cd800-3aa8-11ea-8072-ac8733aa600d.jpg)

"Bad" frame - reflections are downgraded, most noticeably on the rear windshield:
![bad-frame](https://user-images.githubusercontent.com/7947461/72678643-2c472c00-3aa8-11ea-9434-5f077f7e9761.jpg)

Basing on my observations in RenderDoc, it seems like reflections are rendered to a 256x256 cubemap texture and every other frame seems to have this cubemap either fully black or have only one side rendered. Attached "bad frame" capture only have 1 out of 6 sides rendered, while a "good frame" capture has them all.

As for the log file, there seems to be nothing of use there except for the fact game **spams**
`E {RSX [0x00d2cc0]} RSX: Could not gather all required slices for cubemap/3d generation`

Attaching an RSX capture (don't know if it comes from a "good" or a "bad" frame) and two RDC captures. I bookmarked the draw call drawing the car's body in both captures, as I consider it a good starting point for the analysis.
https://mega.nz/#!u3pTBaKD!XeZkMBXmwniGLj4NXiYMemOWs_KfaPk04i4GMGCJxjg

**Comment by Yahfz** [comment]
@CookiePLMonster is it still an issue?

**Comment by CookiePLMonster** [comment]
Checked with clean caches and on the latest version - yes, still the same.

**Comment by USAS-XII** [comment]
First time i'm checking this game and yes still the same.

**Comment by istalo** [comment]
> Reflection flickering Fix:
> 
> Turn on write color buffers (GPU tab)
> 
> Force CPU blit emulation (debug tab)

You sir are a savior, thank you so much, that solved it, I can enjoy the game now without having a migraine with the flickering reflections.

**Comment by kd-11** [comment]
@CookiePLMonster Please retest. This looks similar to another cubemap reflections bug in GOW3 where memory was not being initialized correctly.

**Comment by CookiePLMonster** [comment]
Tested **RPCS3 v0.0.24-14195** - cubemaps do **not** flicker anymore with WCB+CPU Blit disabled, log spam is also gone.
