### ISSUE TITLE
Gran Turismo 5 & 6 wobbly wheels. 

### ISSUE THREAD

**Issue by aka2k** [RPCS3/rpcs3#7289]
I'm not really sure when it started, but I noticed since two days ago. Wheels are moving wobbly and making squeak noises in replays. Happens in both GT5 and GT6.

![wheels](https://user-images.githubusercontent.com/16308596/72687695-42241380-3adf-11ea-8052-7efcc228cb9f.png)

Log: https://www.dropbox.com/transfer/AAAAAHTGSbI13tc3t_zrTsTWDhc5Qbj8pwDv8qyawR5U96F3dhi-R94

**Comment by ameenross** [comment]
Aren't trolley cart wheels supposed to be wobbly and squeaky?

**Comment by jenci8888** [comment]
I can this confirm behavior issue on emulator, but it doesn't happens on real hardware.
![image](https://user-images.githubusercontent.com/40495799/72806923-8128a500-3c56-11ea-8257-061acbbe1c1e.png)

**Comment by kd-11** [comment]
It goes without saying that a proper regression bisect should be done.

**Comment by aka2k** [comment]
I've pinpointed the start of the issue on the 0.0.8-9389 build.

**Comment by kd-11** [comment]
That build is from PR https://github.com/RPCS3/rpcs3/pull/6998. Assigning to @elad335

**Comment by Satan86** [comment]
this hasn't been a probelm for a while now, closeable.
![Screenshot_12](https://user-images.githubusercontent.com/61447828/86018474-51f43c00-ba1d-11ea-9070-8213b9dca061.png)
