### ISSUE TITLE
Verification failed (e=0x5): file::write

### ISSUE THREAD

**Issue by Tom-Neverwinter** [RPCS3/rpcs3#7291]
====================================================

When submitting an issue, please check the following:

- You have read the above. 
yup
- You have provided the version (commit hash) of RPCS3 you are using.
rpcs3-v0.0.8-9412-858ce014_win64
- You have provided sufficient detail for the issue to be reproduced.
error at start "Verification failed E-0x5"
- You have provided system specs.
https://pastebin.com/kgGWBKpe
- Please also provide:
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.

====================================================

similar to this never answered post: https://forums.rpcs3.net/thread-200757.html

**Comment by RainbowCookie32** [comment]
Missing a log file, how the crash happened, and on which game

**Comment by Tom-Neverwinter** [comment]
running wipeout fury like always.

my apologies for not uploading the crash log: 
https://pastebin.com/yB3RBHXG
TTY is clear.

**Comment by Tom-Neverwinter** [comment]
issue happens when booting up ratchet and clank a crack in time. not sure how to resolve the error though. 

It pops up every time I open rpcs3 now. rpcs3 main menu is not accessable. 

I could just wipe everything but my saves and dlc? might try this later or narrow down the lock

**Comment by Tom-Neverwinter** [comment]
RPCS3 seems to have triggered: "Controlled Folder Access" thinking the process is a ransomware attack. not sure why though. It may be my attempt at a mass delete or the replacement of rpcs3 to fix the initial issue?

https://www.winhelponline.com/blog/error-file-not-found-save-files-desktop-windows-10-controlled-folder-access/
