### ISSUE TITLE
Gran Turismo 6 BCES01893 crash

### ISSUE THREAD

**Issue by Attelee** [RPCS3/rpcs3#7292]
Gt6 1.02
Pcsx 0.0.8-9412
Win 10, Nvidia 441.66, Vulkan SDK 1.1.130,

PC:
Ryzen 2600,4Ghz
GTX 1070
16GB DDR4 3000Mhz
Rpcs location on a  Samsung HDD
DualShock 4

PPU decoder and SPU decoder set to LLVM,the emulator always freezing just stopped the screen,and no error message.
 Maybe the only way i think  for the non TSX support cpu's yet is the PPU interpreter ,and SPU LLVM.
So I can play 4 Races in Career mode without crash,with PPU interpreter ,but Grand Valley always freezing,before,or after the race in the tittle screen. this with this error message.

F {RSX [0x12b8ef0]} RSX: class std::runtime_error thrown: [index buffer] Working buffer not big enough, buffer_length=16777216 allocated=2075648 requested=4294967290 guard=65536 largest_pool=38892
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\ring_buffer_helper.h:91)

![Névtelen](https://user-images.githubusercontent.com/56631527/72709825-fd8f8b00-3b65-11ea-956e-63f97fceb278.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4085113/RPCS3.log.gz)

**Comment by HHCHunter** [comment]
Disable AA & Resolution Scaling, test again.

**Comment by Attelee** [comment]
OK i try New build 0.0.8. 9637. 
And selected in Debug menu the Accurate RSX reservation acces and this solved my problem.
I think Now playable with Ryzen cpu the game,but need more test. So thank you guys for your's hard work. :)

**Comment by LowOrbitNZ** [comment]
Locks up at startup.  Boots ok with occasional lockups on earlier version.

(10194) with same settings.  - settings as above.

RX570 card.

RPCS3 v0.0.9-10228-0df6c415 Alpha | HEAD | Firmware version: 4.81
AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.94 GiB RAM | TSC: 3.394GHz | AVX+ | FMA3
