### ISSUE TITLE
[Kingdom Hearts 2.5 (KH2FM)] Major Slowdown and Save Data is Corrupt

### ISSUE THREAD

**Issue by Sirius902** [RPCS3/rpcs3#7296]
After [#7281](https://github.com/RPCS3/rpcs3/pull/7281), now when launching the game from the 2.5 menu, the game seems to run at an extremely low frame rate (probably somewhere in 5-10 fps). Also while this is occurring the emulator incorrectly reports the game to be running at 60fps even though the game only runs at 30fps. When the game is launched directly from the self file for kh2 this part of the issue seems to be fine.

However, regardless of the method to launch the game, the game now also incorrectly reports that the save data is corrupt which is not true since reverting back to the previous build shows that the save data is fine.

Specs:
Windows 10
NVIDIA RTX 2070
Intel i7-9750H CPU

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4087741/RPCS3.log.gz)

**Comment by darkash** [comment]
can confirm the "corrupted save data" problem is already fixed on latest master

**Comment by elad335** [comment]
close issue then.
