### ISSUE TITLE
[Fixed] Hyperdimension Neptunia [BLUS30701] crash upon entering a dungeon and corrupt display on save menu. Issues fixed in #7300.

### ISSUE THREAD

**Issue by Skynet-Prime** [RPCS3/rpcs3#7298]
Note: Issues fixed in build 0.0.8-9428 (#7300)

System Specs: Intel Core i5-3470 3.2 GHz, 8 GB RAM, nVidia GeForce GTX 660, Windows 8.1 64-bit.

Game: Hyperdimension Neptunia [BLUS30701]

Commit Hash: #7176, #7281

First Issue: The game freezes upon entering a dungeon in build 0.0.8-9419 (#7281), but was working fine in build 0.0.8-9414 (#7176). The freeze occurs after selecting to go into a dungeon from the world map.

0.0.8-9419 Log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/4088571/RPCS3.log)

Second Issue: There is text and graphics corruption in the save menu after getting into a few battles and then going into the save menu in build 0.0.8-9414 (#7176), but works fine in the previous build 0.0.8-9412 (#7287).

0.0.8-9412 (#7287)
![rpcs3_0 0 8-9412_HDN_menu](https://user-images.githubusercontent.com/60119287/72767647-6b0fea00-3c40-11ea-8ea2-cf3230218735.png)

0.0.8-9414 (#7176)
![rpcs3_0 0 8-9414_HDN_menu](https://user-images.githubusercontent.com/60119287/72767658-7400bb80-3c40-11ea-959e-e4bc8e5ef888.png)

**Comment by elad335** [comment]
Lol. theres a close issue button next to reply comment.

**Comment by Skynet-Prime** [comment]
Ah, thanks. lol
