### ISSUE TITLE
Textures instead of renderbuffers as attachments

### ISSUE THREAD

**Issue by elisha464** [RPCS3/rpcs3#73]
why not use textures for the framebuffer instead of renderbuffers?
why were renderbuffers chosen in the first place?

**Comment by tambry** [comment]
@vlj @elisha464 Is this still relevant?

**Comment by elisha464** [comment]
I dont remember

**Comment by tambry** [comment]
@elisha464 I'm going to close this one, as the OpenGL has probably almost completely changed since this issue was created and likely isn't relevant. If it is, please let us know, so we can reopen the issue.
