### ISSUE TITLE
Kingdom Hearts HD 1.5 Remix black spots

### ISSUE THREAD

**Issue by albertocastillo2001** [RPCS3/rpcs3#7316]
Hello

I am trying out this emulator with Kingdom Hearts 1.5 Remix.
When playing Kingdom Hearts Final Mix I get these black spots as in issue #6279 that was reported more than a half year ago.

I have no Vulkan support
System specs are:
Core 2 Quad Q9550
 8 GB RAM DDR2
ATI Radeon HD 6970
Windows 10

As you see I cover the minimum requirements, and other than that the game runs impressively well, rarely any hiccup, 60 FPS and so on, which is quite impressive for this machine

However I tried playing around with the settings provided such as raising the resolution scaling threshold, and enabling the read color buffers, but none solves the issue.

Attached log file.

Thank you so much in advance.
[RPCS3.log - copia.gz](https://github.com/RPCS3/rpcs3/files/4112177/RPCS3.log.-.copia.gz)

**Comment by kd-11** [comment]
Excerpt from your log file...
```
Renderer: OpenGL
  Resolution: 1920x1080
  Aspect ratio: 16:9
  Frame limit: Off
  MSAA: Auto
  Write Color Buffers: true
  Write Depth Buffer: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Log shader programs: false
  VSync: true
```
Some issues here:
1. Unless you have eliminated all other issues, don't use 1080p virtual display, use 720p and upscale properly with the resolution scaler. Setting 1080p virtual display resolution does not mean the game will render at that resolution natively (think of it as setting a PS4 to "4K mode" and expecting actual 4k output)
2. Note that there are 4 buffer options. You enabled "write color buffers" which is the wrong option. You were supposed to enable "Read color buffers" which is in the "advanced" configuration tab, not the GPU tab.

**Comment by kd-11** [comment]
Oh and remember to disable strict rendering mode if you want to use anything other than 720p resolution and poor performance.

**Comment by albertocastillo2001** [comment]
Sorry, my log file could be slighly outdated as I started playing with different options, but RCB didn't work either. I will try again and confirm tho. Thanks

**Comment by albertocastillo2001** [comment]
Attached a new verison of the log file. Set resolution to default and rnabled RCB on advanced tab. Same issue
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4112261/RPCS3.log.gz)

**Comment by kd-11** [comment]
Ahh, right. RCB is unimplemented for OpenGL, will add it soon. OpenGL is lagging behind in feature completeness as it is rarely used.

**Comment by albertocastillo2001** [comment]
Well, for people like me with old cards it's good. I am surprise about the performance I am getting with the game on this old computer. Is there maybe an older build that supported this feature in the past by any chance or some kind of workaround I can do to solve this?

Thanks!

**Comment by kd-11** [comment]
Sorry, I don't have a specific build in mind. You can check on our downloads page on rpcs3.net and try builds from maybe a year ago.

**Comment by albertocastillo2001** [comment]
@kd-11 if there are guidelines and documentation about the code maybe I could try to add these features myself to OpenGL. I will be only using OpenGL (as my computer is only capable of this) and might be probably a good candidate to test it as well. Althought I am only planning to play the Kingdom Hearts saga right now.

Thanks

**Comment by kd-11** [comment]
Try with this build https://ci.appveyor.com/project/kd-11/rpcs3/builds/30360923/artifacts
It implements the required functionality but is completely untested. It won't get added to master builds for a while though as renderer code is under maintenance at the moment.

**Comment by albertocastillo2001** [comment]
Tried that build. The black holes dissapeared. Also had disable Vertex cache disabled before and I think that has solved some of the graphics glitching across characters too, as for example Donald Duck missing it's beak.

I also have this line, that dseems to dissapear if I use 1920x1080 on the settings, but tried to use resolution scale as mentioned earlier. The line still appears. It's not an issue for me, but it's curious to know that it doesn't show up the other way.

Also, on movement (screen movement or character movement) I get a tearing effect similar to when you have vsync disabled. Not that it bother much tho. But all are other "missing features" added as well on this build on OpenGL now so I can try to play with settings?

Thanks!
![linekh](https://user-images.githubusercontent.com/37253614/73139064-2b933480-406a-11ea-8181-b42d43b54d44.JPG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4113841/RPCS3.log.gz)

**Comment by kd-11** [comment]
Not all functionality is completed for OpenGL but I think that is it for the major features leaving only PS3 MSAA emulation which is not useful for most games. Tearing usually means the "CPU" part of the virtual PS3 is not able to outpace the "GPU" part and is largely processor dependent. On a real PS3 the CPU is much faster in clocks than the GPU so this can cause issues on PC. If 1080p virtual resolution hides the upscaling artifacts then its good enough I suppose.

**Comment by kd-11** [comment]
Fix was merged to master, therefore this issue is closed as resolved.
