### ISSUE TITLE
vampire rain rps3 [BLES00239]

### ISSUE THREAD

**Issue by tsou21** [RPCS3/rpcs3#7318]
Hello 

after the second mission called 'Odor' the game crashes viewing this error
F {RSX [0x04191bc]} RSX: class std::runtime_error thrown: GetAddress(offset=0x40000000, location=0x0): Local RSX offset out of range
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:63)
the game is categorised as playable .
anyone has a solution????
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4112731/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/4112732/TTY.log)

**Comment by digitaldude555** [comment]
![Screenshot (941)](https://user-images.githubusercontent.com/26138653/73133673-cd982a00-4034-11ea-9b5d-a35ca02b973f.png)
Im in third mission(after odor), does the error happen at a specific point in this level?

**Comment by elad335** [comment]
Have you tried driver wake-up delay in advanced settings?

**Comment by tsou21** [comment]
i tried adjusting driver wake-up delay with different values but nothing happened
this error happens in every mission or tutorial after the second mission Odor
![image](https://user-images.githubusercontent.com/60301198/73134770-1b1b9380-4043-11ea-8262-75f955951104.png)
the game just freezes

**Comment by elad335** [comment]
Maybe game updates related?

**Comment by tsou21** [comment]
i cant find any game updates

**Comment by elad335** [comment]
Upload log with #7345

**Comment by tsou21** [comment]
so it will be fixed after an update of the application??

**Comment by elad335** [comment]
No, upload rpcs3.log.gz

**Comment by tsou21** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4140857/RPCS3.log.gz) #7345

**Comment by elad335** [comment]
Again, wrong build, use https://ci.appveyor.com/project/rpcs3/rpcs3/builds/30487539/artifacts and make sure you are uploading the correct log which is written after you close rpcs3.

**Comment by tsou21** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4140951/RPCS3.log.gz)
i used your recommended build and the game runs fine except there is no music playing in the background and i cant save

**Comment by Asinin3** [comment]
@tsou21 So you can get into the 2nd mission now, but the sound regressed and so did saving? Are those broken now still or?

**Comment by Asinin3** [comment]
No update for a year, ask to re-open if still an issue.
