### ISSUE TITLE
Allow XAudio2 to be used without output device

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#7321]
Right now, having no output device will cause XAudio to not initialize properly and cause either the game or even whole emulator to crash. This will even cause a crash when compiling modules after installing firmware, even though it doesn't play any sounds. It causes a lot of confusion as people don't expect crashes to occur just because they don't have headphones plugged in.

The solution would probably be to catch that initalization failure and have it toggle a flag which causes xaudio to not output anything.

**Comment by lextra2** [comment]
#6723

**Comment by MSuih** [comment]
Oh, this is a duplicate. Apologies.
