### ISSUE TITLE
Unable to Install the Latest Firmware

### ISSUE THREAD

**Issue by mirzaatifbaig** [RPCS3/rpcs3#7327]
I can't seem to install firmware 
the error is 
`Segfault reading location 0000000000000034 at 00007f3d2a82ae50.

HOW TO REPORT ERRORS:
https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support
Please, don't send incorrect reports. Thanks for understanding.
`
I am trying to get it work on Arch Linux with the latest appImage and binaries.Works fine on windows.

**Comment by AniLeo** [comment]
Closing as it doesn't follow the guidelines and didn't get updated.

Also we have several people on arch and it's working fine.
