### ISSUE TITLE
Call of Duty games: Existing save data can't be used

### ISSUE THREAD

**Issue by RainbowCookie32** [RPCS3/rpcs3#7329]
This issue happens in *at least* Ghosts and Advanced Warfare (the ones I currently have), but I'm pretty sure other games in the series are affected as well.

If you have an existing save, the game will delete it saying its from another user before loading into the menu. 
The issue can be reproduced just by starting a new game, going back to the menu and running the game again.

Advanced Warfare:
![AW](https://user-images.githubusercontent.com/16805474/73183789-27aef300-40fa-11ea-8975-fe359ddd4526.png)

[Log without a save](https://github.com/RPCS3/rpcs3/files/4117603/CoDAW_FirstRun.log.gz)
[Log with a save](https://github.com/RPCS3/rpcs3/files/4117608/CoDAW_SecondRun.log.gz)
[The savefile created by the game](https://github.com/RPCS3/rpcs3/files/4117609/CoDAW_Save.zip)

Ghosts:
![Ghosts](https://user-images.githubusercontent.com/16805474/73183926-5e850900-40fa-11ea-8a6b-690d0be433c3.png)

[Log without a save](https://github.com/RPCS3/rpcs3/files/4117611/CoDGhosts_FirstRun.log.gz)
[Log with a save](https://github.com/RPCS3/rpcs3/files/4117613/CoDGhosts_SecondRun.log.gz)
[The savefile created by the game](https://github.com/RPCS3/rpcs3/files/4117612/CoDGhosts_Save.zip)

**Comment by QuaiGoner** [comment]
Same with CoD BO, but MW2 seems to be fine

**Comment by elad335** [comment]
I need log from the moment of saving it.

**Comment by elad335** [comment]
Test with #8706 please.

**Comment by RainbowCookie32** [comment]
Closed as fixed by #8706
