### ISSUE TITLE
A Boy and His Blob [NPEB02164] graphic glitches on Vulkan and Opengl

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7332]
![boy](https://user-images.githubusercontent.com/2696404/73243598-ef371400-41e2-11ea-839f-bf9821ad6bd0.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4121098/RPCS3.log.gz)
[NPEB02164_20200128152613_capture.zip](https://github.com/RPCS3/rpcs3/files/4121099/NPEB02164_20200128152613_capture.zip)

**Comment by digitaldude555** [comment]
![Screenshot (997)](https://user-images.githubusercontent.com/26138653/73568509-31758500-4471-11ea-96ed-72b4ecef7a5c.png)
My game is fine with default settings.

**Comment by benderscruffy** [comment]
must be an AMD driver issue

**Comment by benderscruffy** [comment]
with "Force CPU blit" and "Write color buffers it is fixed
