### ISSUE TITLE
UFC Undisputed 3 - Loading screen freeze

### ISSUE THREAD

**Issue by tipleavalentin** [RPCS3/rpcs3#7334]
Hi,

After some time of loading the game freezes, please take a look at this.
I understand this is an alpha version and it's great until now, I'm trying to help improve it.
Thanks!

RPCS3 version: 0.0.8-9452 ad8988af (the results are the same for an older version 0.0.6-8400-9a7c2784 which is working on some guy on youtube)

[BLES01231_20200128173033_capture.zip](https://github.com/RPCS3/rpcs3/files/4123139/BLES01231_20200128173033_capture.zip)

[LOG.zip](https://github.com/RPCS3/rpcs3/files/4123140/LOG.zip)

<img width="1439" alt="stuck" src="https://user-images.githubusercontent.com/14072036/73278477-514c4500-41f4-11ea-8182-a9bc468f00dc.png">

Also the light/color issue of the fighters was presented by me in another ticket and partially fixed for UFC 2009, here is even worst:
<img width="1438" alt="light issue" src="https://user-images.githubusercontent.com/14072036/73278490-55786280-41f4-11ea-9b56-3c726865da0f.png">

**Comment by Emulator-Team-2** [comment]
To fix color/light issues:

Enable `Write Color Buffers` and `Force CPU Blit`.

Disable `Multithreaded RSX`-(Causes graphical glitches).

On the CPU tab:
Change the `SPU Decoder to ASMJIT Recompiler` to fix the game freezing on the loading screen.

Note:
-Force CPU Blit is on the Debug tab of the emulator settings.
-To enable debug tab setting change `showDebugTab` false to true in `GuiConfigs/CurrentSettings.ini`.

**Comment by tipleavalentin** [comment]
@Emulator-Team-2 thanks! I did manage to run it but only with SPU Decoder: Interpreter (fast), using ASMJIT Recompiler freezes too. But is slow, around 20 fps...

**Comment by Emulator-Team-2** [comment]
@tipleavalentin
I also tried with the Interpreter, but with PPU Interpreter (fast) seems this game is more stable on low fps.

**Comment by tipleavalentin** [comment]
Hopefully the speed will be improved in the future. :D
