### ISSUE TITLE
Prince of Persia Classic - Broken UI

### ISSUE THREAD

**Issue by RainbowCookie32** [RPCS3/rpcs3#7343]
Apparently this is a regression that's been around [since 2017](https://forums.rpcs3.net/thread-196988-post-292563.html#pid292563). 

The menu is completely white.
![PoP01](https://user-images.githubusercontent.com/16805474/73414957-2d215e80-42ef-11ea-85b6-a3ec267f67a0.jpg)

[RSX Capture](https://github.com/RPCS3/rpcs3/files/4131856/PoPC_Menu.zip)

And ingame UI is has white rectangles.
![PoP02](https://user-images.githubusercontent.com/16805474/73414947-25fa5080-42ef-11ea-978a-fddb3ced6d15.jpg)

[RSX Capture](https://github.com/RPCS3/rpcs3/files/4131855/PoPC_Ingame.zip)

Couldn't fix it with any settings, and Write color buffers causes it to crash with `RSX: class std::runtime_error thrown: GetAddress(offset=0xa6b680, location=0x1): RSXIO memory not mapped` after the Ubisoft logo.

[Normal log](https://github.com/RPCS3/rpcs3/files/4131874/RPCS3.log.gz)
[Log from the crash](https://github.com/RPCS3/rpcs3/files/4131871/RPCS3_PoPC_Crash.zip)

**Comment by jokoputera** [comment]
You can play this game all way through, but all the cut scene and all the text cant be read

**Comment by jokoputera** [comment]
Additional information: 0.0.3-3-c6e6f4a menu and text works fine

**Comment by kd-11** [comment]
I'm fairly certain this is the same bug as puzzle dimension where the game loads shaders as textures because some developers are weird (or the psgl driver is just made that way?)

**Comment by RainbowCookie32** [comment]
The crash when Write Color Buffers is enabled is now fixed, everything else is still valid as of latest master

**Comment by kd-11** [comment]
Strangely, this issue is fixed when using https://github.com/RPCS3/rpcs3/pull/8106 and forcing to use shader interpreters.

**Comment by jokoputera** [comment]
Will this related to this:
https://github.com/RPCS3/rpcs3/issues/6598# as it also using Vulkan shader renderer?

**Comment by jokoputera** [comment]
Prince Of Persia Classic title textures work by enable shader interpreter only, with FPS below 10fps, while in menu can achieve around 30-60. Ingame status texture load correctly, but the game itself is black.

**Comment by jokoputera** [comment]
ive tried latest build (https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-37df3c6f9613b7ed517106f1c468164f1be40667/rpcs3-v0.0.10-10395-37df3c6f_win64.7z), it work without using "Shader Intpreter Only".

ive cleared all cached, and it run just fine 60FPS using Vulkan.
im using AMD Ryzen 5 3600, GTX1660

OP, please try on your end, try to clear all caches first, then run.
close thread and if its working

**Comment by AniLeo** [comment]
Fixed by #8243 

![Screenshot from 2020-05-17 10-54-13](https://user-images.githubusercontent.com/10283761/82141332-f97e2c00-982c-11ea-8276-c3b0f2fdd872.png)

![Screenshot from 2020-05-17 10-53-14](https://user-images.githubusercontent.com/10283761/82141334-fbe08600-982c-11ea-94ad-51054c5de0d8.png)
