### ISSUE TITLE
OpenGL: Cannot capture screenshots

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#7352]
Trying to take a screenshot just writes `[Screenshot] Failed to capture image: 0x500`in log, which is the error code for GL_INVALID_ENUM.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4140311/RPCS3.log.gz)

**Comment by kd-11** [comment]
Does it work for other games? I did refactor code around this recently, maybe I broke it. Or could be a driver bug which is not uncommon for OpenGL drivers.

**Comment by MSuih** [comment]
It varies. For example in RDR and Uncharted I can take screenshots during intro video but not after that, in Yakuza 4 I can't screenshot even the intro video and in Skate 3 & THPS HD screenshots work just fine.

**Comment by MSuih** [comment]
Seems to have been fixed, probably in #7403
