### ISSUE TITLE
Shoot Many Robots (Demo) [NPUB30600] graphic glitches on Vulkan and Opengl

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7357]
during gameplay graphics are all messed up
with "Force CPU blit" and "Write color buffers no change
![shoot](https://user-images.githubusercontent.com/2696404/73582909-5ba76100-44ca-11ea-8000-e22938110b11.PNG)
here is a renderdoc
https://mega.nz/#!QuwXlQ5Q!FPdT7E8Yi1E2a9GNwLmMG_UsE2cOqSBbxRZjaqkBlfs
rsx captures
https://mega.nz/#!9m4VhAwD!DnTQFWqKMvPMuluYpbKP1dVUlGLhaWqySIM5y3hxtgs
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4141938/RPCS3.log.gz)
happens in both Vulkan and Opengl

**Comment by uaqlover** [comment]
still same with RPCS3 v0.0.12-10981-a5cff8b1 Alpha | HEAD | Firmware version: 4.85

@kd-11

**Comment by uaqlover** [comment]
any update ? @kd-11

**Comment by kd-11** [comment]
Still happening. I'm investigating.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/10406
