### ISSUE TITLE
Strider Trial Version [NPUB31139] graphic glitches on Vulkan and Opengl

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7358]
during gameplay graphics are all messed up
with "Force CPU blit" and "Write color buffers no change
![strider](https://user-images.githubusercontent.com/2696404/73585383-c57c3680-44db-11ea-9b21-c3c32947a75e.PNG)
here is a renderdoc
https://mega.nz/#!Rmo3wKyI!6qni391rQq2agRBk20Ade0WA69F94RBa9gS7MAROzEo
RSX capture
https://mega.nz/#!Q7wHBCqA!8PIav_vMM0Oimm4APqTSmyk8Q-Vc72EUUuurCn7NQok
Log
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4142072/RPCS3.zip)

**Comment by Asinin3** [comment]
Still an issue?

**Comment by digitaldude555** [comment]
Yes.

**Comment by nitroos-ai** [comment]
You have to enable:
GPU : Write Color Buffers
Advanced : Read Color Buffers

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7358271/RPCS3.zip)

**Comment by digitaldude555** [comment]
Can be closed then.
