### ISSUE TITLE
Conan BLUS30069 keeps reinstalling to hdd (it takes few minutes) with every execution.

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#7367]
Hello,
its long term problem, for at least for few years, i dont remember that it worked otherwise..

 I dunno if its same for other users or had to something with my setup (i have all games data on Windows network share), i tried lots (30+) games, but afaik only Conan has such problem.
  I simulated it on multiple PCs, but i always have files on network storage. 
![ConanInstall](https://user-images.githubusercontent.com/1702944/73603299-e5196a80-4580-11ea-8ee5-9254fc02f85f.png)

 I console its lots lines like this:
_E {PPU[0x1000000] Thread (main_thread) [0x00afae74]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/textures/levels/ui_fnt_mikadan_28.gtf” [1]_

 I have also problems that at least sometimes whole install process freeze.. and i can progress into game at all - uploaded log is from such situation.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4143554/RPCS3.zip)

I also got some hardcoded path error during gameplay, im sure that such directory doesnt exists:
F {RSX [0x0158604]} RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:350)
 I have RPCS3 isntalled on drive D.

**Comment by legend800** [comment]
Thanks for logging this. I can confirm this behavior. On top of that, it freezes about ~25% of the time during this install (long standing issue) forcing a restart.

**Comment by legend800** [comment]
It's hanging during this load also pretty consistently again. Only loads menus 1/5 times at best.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4270914/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
Still an issue.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5893903/RPCS3.log.gz)
Still an issue.

**Comment by legend800** [comment]
Confirmed, and to summerize, there's two ways to get this game fully playable: have a proper working check to see if these files exist or don't hang on file transfer.

**Comment by legend800** [comment]
Menus seem to load pretty reliably now. This can be closed.

**Comment by ruthan** [comment]
I tried it now, but got stuck at 95.7%.. here is log. So at least sometimes it is still not working.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6495437/RPCS3.zip)

**Comment by ruthan** [comment]
Other interesting thing it when i reach this state, emulator is just dead, when i try to run other games it crash without any message.

  I tried it now 4 times and 4 times it got stuck..

**Comment by legend800** [comment]
For me, it rarely gets stuck now, but that could be just because I moved to a new SSD drive (so the % flies by). Maybe less chance of hitting the race condition (since it's intermittent soft lock). Definitely something funky going on with the file copy. 

If we can just get the emu to SEE the installed files properly, this won't be an issue since you can use Interpreter to install fine every time (just too slow to play).

**Comment by elad335** [comment]
What are the chances of updating log?

**Comment by legend800** [comment]
This was fixed earlier this year.  This can be closed.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9540802/RPCS3.log.gz)

**Comment by ruthan** [comment]
I dunno when it was fixed, i  tested i no so long ago - 2 months i guess.. but its working for me, im using SSD from the start.

**Comment by koksoni** [comment]
> This was fixed earlier this year. This can be closed.
> 
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9540802/RPCS3.log.gz)

Did not work for me
