### ISSUE TITLE
God Of War 3 PPU fatal error ( Run both Interpreter 2 and LLVM )

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#7371]
This issue always happen nearly the end of game , when follow Pandora in the Darkness Map after Zeus Battle
Error Log : F {PPU[0x1000000] Thread (main_thread) [0x001f2428]} VM: Access violation writing location 0x50100034
Log file : [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4144263/RPCS3.log.gz)
![image](https://user-images.githubusercontent.com/11285640/73609413-e63dac80-45ff-11ea-9af9-c2f6bbfb9a25.png)

**Comment by AniLeo** [comment]
You should also upload a savefile

**Comment by zminhquanz** [comment]
[GOW3 save.zip](https://github.com/RPCS3/rpcs3/files/4144332/GOW3.save.zip)
Here is the save file , you can check that

**Comment by zminhquanz** [comment]
Same with PPU Interpreter (precise)
F {PPU[0x1000000] Thread (main_thread) [0x001f2428]} VM: Access violation writing location 0x50100034
Log file : [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4148749/RPCS3.log.gz)
![image](https://user-images.githubusercontent.com/11285640/73667987-b661d800-46d7-11ea-89a5-6742e951f468.png)
![image](https://user-images.githubusercontent.com/11285640/73668000-bc57b900-46d7-11ea-9ffc-31a52e795f4b.png)

**Comment by zminhquanz** [comment]
It's fixed on a new build
