### ISSUE TITLE
[AMD] vk: Some games need cpu blit fallback to avoid artifacts

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#7372]
Meta tracker for a glitch seemingly unique to AMD cards at this time.
See https://github.com/RPCS3/rpcs3/issues/7332, https://github.com/RPCS3/rpcs3/issues/6753, https://github.com/RPCS3/rpcs3/issues/6753 and several others.

**Comment by JohnHolmesII** [comment]
You linked the same issue twice, was there a 3rd issue you wanted to link here directly, or just leave it as "others"?

**Comment by kd-11** [comment]
Double link was a copypasta but there are way more than 3 affected titles anyway, no need to list them all.

**Comment by digitaldude555** [comment]
Add these two to the pile. #7042 #7284

**Comment by benderscruffy** [comment]
@digitaldude555 them 2 are not fixed with force cpu blit and WCB

**Comment by kd-11** [comment]
I almost forgot about this. Investigating...

**Comment by kd-11** [comment]
All these AMD issues are regressions but not reported as such. This has caused much time wasted.

**Comment by kd-11** [comment]
Seems to have broken somewhere between v8614 and v8990 going by the executables I have in my archive.

**Comment by kd-11** [comment]
First broken build is 8956... but it goes deeper. It has always been broken when 'use GPU texture scaling' is enabled, which is partly what that build enables for special textures. Honestly, seems like a driver bug to me, but I'll try to isolate and work around it.

**Comment by kd-11** [comment]
Found a nasty driver bug, retest with https://github.com/RPCS3/rpcs3/pull/7639
