### ISSUE TITLE
NASCAR 09 Demo [NPUB90120] marks itself as Game Data after the first boot

### ISSUE THREAD

**Issue by CookiePLMonster** [RPCS3/rpcs3#7373]
Curiously, NASCAR 09 Demo seems to overwrite its own param.sfo on the first boot, marking itself as Game Data (on the first boot, it is properly recognized as HDD Game). This results in the game being playable only once, after that it has to be reinstalled.

Looking at the code, `cellGameDataCheckCreate2` appears to be the offender - to make matters worse, it cannot handle param.sfo being read-only, so an attempt to prevent the game from "commiting suicide" like this will instead result in an exception being thrown.

Attaching a log file from the first boot and param.sfo before/after "suicide":
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4144343/RPCS3.log.gz)
[param.sfo-before.zip](https://github.com/RPCS3/rpcs3/files/4144344/param.sfo-before.zip)
[param.sfo-after.zip](https://github.com/RPCS3/rpcs3/files/4144346/param.sfo-after.zip)

**Comment by CookiePLMonster** [comment]
Modifying `cellGameDataCheckCreate2` to handle failure to open `param.sfo` for writing works correctly - it could likely be a good enough stop gap solution?

**Comment by digitaldude555** [comment]
Chronicles of Riddick Assault On Dark Athena Demo has the same issue.
