### ISSUE TITLE
Error:  Basara 4 Sumeragi

### ISSUE THREAD

**Issue by flyingspider2** [RPCS3/rpcs3#7376]
some characters had  choosed  
screen becomed 
![image](https://user-images.githubusercontent.com/60579614/73613036-83aed580-462c-11ea-8b5c-0c41e7894815.png)

RPCS3  show this
[error.txt](https://github.com/RPCS3/rpcs3/files/4144885/error.txt)

how should i do??

**Comment by RainbowCookie32** [comment]
Don't just copy paste a random piece of the log. Upload the full log from RPCS3's folder, RPCS3.log.gz.

**Comment by flyingspider2** [comment]
[error.txt](https://github.com/RPCS3/rpcs3/files/4144949/error.txt)

this??

**Comment by AniLeo** [comment]
That is incomplete, boot the game and try again

**Comment by flyingspider2** [comment]
but it is too large  

![image](https://user-images.githubusercontent.com/60579614/73613438-ad69fb80-4630-11ea-9622-e969953d4010.png)

is that?

**Comment by AniLeo** [comment]
yes, boot the game, reproduce the issue then close the emulator
if you can't reproduce quickly, 7z that and try uploading

**Comment by flyingspider2** [comment]
I  try 
[RPCS3.log.gz.txt.zip](https://github.com/RPCS3/rpcs3/files/4145884/RPCS3.log.gz.txt.zip)

**Comment by AniLeo** [comment]
Needs triaging

**Comment by Asinin3** [comment]
Ask for re-open if still an issue on latest builds with wcb. I can see multiple videos of this game running and posts on forum.
