### ISSUE TITLE
Teenage Mutant Ninja Turtles : Danger of the Ooze no sound and stop in intro 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#7379]
the game stops in intro if you didn't have a save file 

if you have a save file it goes in game but no sound at all 

in old build it goes ingame and a sound was broken

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4145867/RPCS3.log.gz)

**Comment by Yahfz** [comment]
Which build prevents it from going ingame? All of your reports seems to be missing that critical information. Please edit them with it.

**Comment by digitaldude555** [comment]
The sound is now fixed!!

**Comment by AniLeo** [comment]
Closing as fixed
