### ISSUE TITLE
F1 Race Stars fatal error Regression after 7142 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#7385]
![11](https://user-images.githubusercontent.com/45731484/73674265-fe93e280-4664-11ea-9d68-2f5fba0c2f1b.png)

log file 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4149080/RPCS3.zip)

**Comment by Asinin3** [comment]
When reporting a regression you actually need to find what version/pull request broke the game. Issues like this where developers have to do the testing are no good to us.

**Comment by uaqlover** [comment]
it broke after 7142

![47](https://user-images.githubusercontent.com/45731484/73679783-f3927f80-466f-11ea-928d-a5e379700be5.png)


after 7142

![FPS_ 59 61 _ Vulkan _ 0 0 7-9250 _ F1 Race Stars™  BLES01715  2_3_2020 10_26_30 AM](https://user-images.githubusercontent.com/45731484/73679771-ed040800-466f-11ea-9ba8-b82233722a87.png)

**Comment by CookiePLMonster** [comment]
Did you clear all caches then? For a good measure, try removing your entire `cache\BLES01715' directory.

**Comment by uaqlover** [comment]
@CookiePLMonster yeah i remove it it has still same problem
