### ISSUE TITLE
[ui] last played dates are in the host OS's language

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#7390]
Very minor issue.

As RPCS3 is not localized yet, localized dates stick out like a sore thumb.

![image](https://user-images.githubusercontent.com/10439488/73692705-21f67600-46d5-11ea-9ef8-d9c04800cbdb.png)

As you can see, dates are currently displayed in the host OS's language, while attempting to follow the US date notation. That's a solid 0/2, chief.

I recommend either enforcing English month names and the US date format properly, e.g. `February 3, 2020` instead of `february 3 2020`, **or** switching to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), the arguably superior date format.

*This post was brought to you by the /r/ISO8601/ gang.*

**Comment by Megamouse** [comment]
I don't see how using a format that can be misinterpreted is superior

**Comment by dio-gh** [comment]
It's not misinterpretable. [No country uses a YDM format.](https://en.wikipedia.org/wiki/Date_format_by_country) If it starts with a year it's always YMD.

**Comment by Megamouse** [comment]
but for example noone in germany would ever use that format

**Comment by dio-gh** [comment]
According to Wikipedia, you guys are using a DMY order, so no wonder. :D
