### ISSUE TITLE
Regression: E.X. Troopers - Black screen on OpenGL only (#7260)

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#7395]
[ The last working version is 0.0.8-9386. ]
![1](https://user-images.githubusercontent.com/38318848/73780784-65adb600-478f-11ea-9889-de41d643dda7.png)

[ Build #7260 - 0.0.8-9388 ]
![2](https://user-images.githubusercontent.com/38318848/73780859-8c6bec80-478f-11ea-96f1-77e5ad121b9c.png)

[ The latest master build - 0.0.8-9501. ]
![3](https://user-images.githubusercontent.com/38318848/73780974-c1783f00-478f-11ea-904f-9b6529f22dbe.png)

RSX Capture:
[RSX-Capture-(Build-0.0.8-9386)](https://drive.google.com/open?id=1-l2or-pScySENVMqJ7tF5-mIeYHdCNQK)
[RSX-Capture-(Build-0.0.8-9501)](https://drive.google.com/open?id=1I9-HtwLrDCtnPYzfku_7adeW3ERp_5z_)

**Comment by kd-11** [comment]
Test with new commits on https://github.com/RPCS3/rpcs3/pull/7393

**Comment by Emulator-Team-2** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/7393.
![1](https://user-images.githubusercontent.com/38318848/73853980-0a80cf80-4832-11ea-94af-0ed822274178.png)
