### ISSUE TITLE
version 9508 broke Fight Night Round 4

### ISSUE THREAD

**Issue by gedou44** [RPCS3/rpcs3#7401]
9506 last build working
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4159868/RPCS3.log.gz)

log of version 9508 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4159631/RPCS3.log)

**Comment by elad335** [comment]
wrong testing it seems.

**Comment by gedou44** [comment]
> wrong testing it seems.

what do you mean?

**Comment by elad335** [comment]
its not very possible considering the changes in pr.

**Comment by gedou44** [comment]
can you test it ?
here it won't work anymore after 9508

**Comment by AniLeo** [comment]
Needs someone to test this on master and validate

**Comment by TonyAMG** [comment]
Build 10220 - game works fine (both american and european versions) 
i5 8400, RX580 8GB

**Comment by AniLeo** [comment]
Closing as reported working
