### ISSUE TITLE
OpenGL Regression with Modnation Racers after #6744

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#7406]
Before https://github.com/RPCS3/rpcs3/pull/6744 
![8871_PM6DvjsOAQ](https://user-images.githubusercontent.com/15137035/73955372-2af47b00-4953-11ea-834b-ce6120880bab.jpg)

After:
![8878_kwTLalGlbn](https://user-images.githubusercontent.com/15137035/73955602-87f03100-4953-11ea-85f3-d896fe83b4df.jpg)
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4166229/RPCS3.log.gz)

RSX Captures: https://puu.sh/F7Mvb/23b76fe6ec.7z

**Comment by Asinin3** [comment]
I should note that master does look a bit better, but it's still not as good as the earlier builds before it broke. 
![rpcs3_BeFYfgwwGa](https://user-images.githubusercontent.com/15137035/73957670-a0157f80-4956-11ea-896f-8deba345d21e.jpg)

**Comment by kd-11** [comment]
This needs a retest, I recently fixed a typo introduced by the compute PR that also affected DeS.

**Comment by RainbowCookie32** [comment]
Yeah, it actually seems to be fixed on latest master
![imagen](https://user-images.githubusercontent.com/16805474/76688503-18352c00-660c-11ea-8430-f96341de9174.png)

**Comment by Asinin3** [comment]
Ground here shouldn't be black tho..?
![image](https://user-images.githubusercontent.com/15137035/77250259-abb6ce80-6c96-11ea-831a-b868f9bff055.png)

**Comment by Asinin3** [comment]
NVM, restarted the game cleaned shaders and ground is back to normal 
![image](https://user-images.githubusercontent.com/15137035/77250311-06502a80-6c97-11ea-9022-14511ccbf307.png)

**Comment by ToppestOfDogs** [comment]
I'm still having this issue both in OpenGL and Vulkan. The vertex explosions make it impossible to beat the tutorial.
![screenshot-2020_04_12_23_23_03](https://user-images.githubusercontent.com/17092742/79090014-4cd4fa00-7d16-11ea-9f8d-5e1d07a21974.png)
![screenshot-2020_04_12_23_36_53](https://user-images.githubusercontent.com/17092742/79090102-90c7ff00-7d16-11ea-916b-be5bc5c0e335.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4467882/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
You need to use Write color buffers to fix it

**Comment by ToppestOfDogs** [comment]
Alright thanks
