### ISSUE TITLE
Create PPU Cache redefines the game's last played date

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#7411]
It's obvious why this happens, since the game is essentially being booted. However, when used as an "All titles" option, it resets all games' Last Played dates to the current date. It also adds extra time on playtime, but that doesn't seem very relevant.

**Comment by Megamouse** [comment]
You'd need to create a new callback that only gets triggered if you actually run the game.

**Comment by CookiePLMonster** [comment]
Alternately, bind a parameter to whatever existing callbacks handle this now?
