### ISSUE TITLE
YoRHa theme's background does not work properly on the Trophies window

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#7413]
Bug:
![image](https://user-images.githubusercontent.com/10283761/73987515-911fd480-4938-11ea-93c6-f2f7530e2c50.png)

**Comment by Megamouse** [comment]
This is probably an upstream regression.
Might be worth recreating this in a very simple example and opening a ticket on their bugtracker

**Comment by Megamouse** [comment]
Try if this happened before qt 5.14

**Comment by AniLeo** [comment]
This has happened for a long time, even before qt 5.14, I just got around to it now

I believe it has happened since the trophy manager window overhaul

**Comment by Megamouse** [comment]
find the proper PR

**Comment by AniLeo** [comment]
I can try, but CG Disasm has the same problem and it was already like that (not allowing to set a background image) already when I was making the theme back then

**Comment by AniLeo** [comment]
This happens on the oldest AppImage on rpcs3.net/builds , the Trophy Overhaul PR is #4604 which predates last listed Windows build as well

I went on the build archive and got the PR and the build before it though, but I can't open Trophy Manager, it crashes RPCS3 with
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unknown system error: 20.
```

**Comment by Megamouse** [comment]
can you try #4234
