### ISSUE TITLE
GOD OF WAR ASCENSION hanging on NON-TSX Path [BCES01741]

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#7416]
GOW Ascension is already a really unstable title but the behavior changes when you don't have TSX. Instead of getting a semaphore error like you do on TSX (which prevents you from going ingame), you just get nothing on the non-tsx path and the game hangs or sometimes goes further which indicates an obvious race condition. 

![image](https://user-images.githubusercontent.com/17715080/73997369-0c838500-493d-11ea-9d07-c185fcfb838d.png)

[TSX ENABLED.log](https://github.com/RPCS3/rpcs3/files/4168786/TSX.ENABLED.log)
[TSX DISABLED.log](https://github.com/RPCS3/rpcs3/files/4168780/TSX.DISABLED.log)

**Update:**

- Found the RSX Sync primitive, RSX report, but disabling Zcull doesn't fix it. These reports are being written to main memory so i tried to add a reservation notification to these reports and it didn't work.

- Neko suggested to try a different approach in the SPUThread instead and completely remove the following line:

**vm::reservation_notifier(raddr, 128).wait<UINT64_MAX & -128>(rtime, atomic_wait_timeout{100'000});**

After removing that line the results haven't changed. Tinkering with reservations definitely helped, but it wasn't enough. I guess that means it's an issue in the SPUThread, so maybe that's worth checking out.

I'll keep updating this issue as new info comes out.

**Comment by elad335** [comment]
Fixed by #7483.
