### ISSUE TITLE
GUI Font bug in YoRHa skin after bump to QT 5.14

### ISSUE THREAD

**Issue by Andryshik345** [RPCS3/rpcs3#7417]
There's a bug in YoRHa skin with font starts appearing after a2451465 commit. Font is 'jumping' and there's more pixels on edges, seems like AA is off, but i'm not sure.

latest(and also on that commit):
![изображение](https://user-images.githubusercontent.com/24612088/74000136-d4099880-4988-11ea-935b-3b64ce93016a.png)

on 9300 for example(before bump to qt 5.14):
![изображение](https://user-images.githubusercontent.com/24612088/74000158-e4ba0e80-4988-11ea-8214-ed4fef4d4db0.png)

P.S: it's not important to fix this, i'm just want to report about that.

**Comment by Megamouse** [comment]
Probably a Qt bug which means it might get fixed with some update.

**Comment by MSuih** [comment]
It's possible to set text antialiasing in Qt but this would have to be done for the painter object which renders the text. Waiting for Qt to fix this sounds more sensible.

**Comment by Andryshik345** [comment]
![изображение](https://user-images.githubusercontent.com/24612088/84809691-bf6a9a80-b023-11ea-8359-2a07587146b4.png)
Looks like it doesn't appear on latest masters, so i'll close this issue.
