### ISSUE TITLE
Multiple games crash the emulator on startup since v0.0.8-9527 (#7410)

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#7422]
Steps to reproduce:-
1. Run game
2. After the native GUI has loaded, and you hit the X button to confirm, the emulator will crash

Picture of crash:-
![SCIV crash](https://user-images.githubusercontent.com/4345150/74036919-2cc44a00-49f8-11ea-846d-dce33d3c16f4.PNG)

Logfiles when the crash occurs:-
[Soul Calibur IV log](https://github.com/RPCS3/rpcs3/files/4171199/RPCS3.log) 
[Soul Calibur V log](https://github.com/RPCS3/rpcs3/files/4171227/RPCS3.log)

List of affected games:-
1. Soul Calibur IV
2. Soul Calibur V
3. Catherine
4. Lollipop Chainsaw

Workarounds:-
1. When encountering the native GUI prompt, just leave it be, don't hit the X button, and after that the games load normally.

2. Disable native GUI and use QT prompts instead.

**Comment by Asinin3** [comment]
I can confirm that it's happening in catherine, can turn off native GUI under system settings or revert to old build to fix it.

**Comment by solarmystic** [comment]
> 
> 
> I can confirm that it's happening in catherine, can turn off native GUI under system settings or revert to old build to fix it.

Thanks for the confirmation, I've listed another workaround as well which is just to let the GUI fade out normally.

**Comment by digtal-devil** [comment]
[Uploading RPCS3 (1).log…]()
![1](https://user-images.githubusercontent.com/41947332/74038518-5e341a00-49e6-11ea-93de-67683246c441.png)

Getting problems with Persona 5 and Ninja Gaiden Sigma.

**Comment by digitaldude555** [comment]
Its every game with native ui dont need further tests.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/7423
