### ISSUE TITLE
The Evil Within - RSX: Out of video memory (VRAM) error on launch.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#7424]
Shortly after pressing start or any key:
F {RSX [0x00662ac]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:353)

Using Vulkan; on OpenGL game is unplayable. Though even on Vulkan FPS is very low, but I was able to finish 2 chapters before this error started to pop up.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4172707/RPCS3.log.gz)

**Comment by kd-11** [comment]
So is it on launch or not? You said you played two levels then it ran out? Or you played two levels on an old build and recently could not resume playing?

**Comment by isshininu** [comment]
Yes, it was old build which (kinda) have the same problem, but occasionally (pretty often) let me to continue game. Now error is unavidable, by pressing any key to continue.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/7758

**Comment by isshininu** [comment]
Yes, it fixed, a bunch of regressions and uneven FPS revealed.
