### ISSUE TITLE
Regression: CB chain has run out of free entries! (#7242)

### ISSUE THREAD

**Issue by okass** [RPCS3/rpcs3#7427]
Game hangs when opening "Grimore Weiss" menu and last message in RPCS3 window console is "{RSX [0x025a65c]} RSX: CB chain has run out of free entries!"
The issue seems to have started to appear in rpcs3-v0.0.8-9370-8bbda3de build because previous build works just fine also this build has some fps cap issues which hangs game while its still loading for ingame. Latest rpcs3-v0.0.8-9528-54da9ac7 seems to have fixed the fps cap issue but menu problem still exists. Im adding both build 9528 and 9370 logs to attachments also Im adding savegame  in case that helps.
[9370_RPCS3.log](https://github.com/RPCS3/rpcs3/files/4172994/9370_RPCS3.log)
[9528_RPCS3.log](https://github.com/RPCS3/rpcs3/files/4172992/9528_RPCS3.log)
[BLUS30481_GAME_DATA0.zip](https://github.com/RPCS3/rpcs3/files/4173006/BLUS30481_GAME_DATA0.zip)

**Comment by AniLeo** [comment]
I've gotten that issue in other games too, seems recent and not related to a specific game

I remember I got it on Beijing 2008 yesterday in just a few minutes

**Comment by okass** [comment]
I wonder what causes that

**Comment by AniLeo** [comment]
Regression from #7242 
@kd-11

**Comment by JohnHolmesII** [comment]
Happens to me in Demon's Souls as well.

**Comment by AniLeo** [comment]
The solution in the meantime is to not use MTRSX

**Comment by kd-11** [comment]
Wasn't able to reproduce this.
![image](https://user-images.githubusercontent.com/15904127/74100548-53da6300-4b41-11ea-8787-2b47042c8cbf.png)

Same thing with Demon's souls. Runs fine for me after about half an hour of running around killing bosses.

Ironically, with older builds than the PR mentioned, I get the crashing all the time with event timeouts.

**Comment by okass** [comment]
yeah disabling "Multithreaded RSX" fixes that

**Comment by Alvilos** [comment]
Yeah so I'm having this problem in Demon's Souls and it freezes up my game. I tried disabling "Multithreaded RSX" and it didn't fix the issue I'm afraid. any other ideas I might be able to use?

**Comment by Artins90** [comment]
I experienced this crash in Nier with Multithreaded RSX, disabling it fixes the issue.  
Actually it's not opening the menu that triggers it for me, it's moving within the sub-menus of the Word Edit section.

**Comment by kd-11** [comment]
@Alvilos 
> I tried disabling "Multithreaded RSX" and it didn't fix the issue I'm afraid.

Then we're not talking about the same bug. This tracker is specifically for the crash tied to MTRSX being enabled. I think I saw you mention somewhere it hangs for you even on OpenGL which completely rules out this vulkan related problem.

**Comment by nev3rfail** [comment]
@kd-11 
> Wasn't able to reproduce this.
Error is appearing not every time and not only while entering/leaving "Grimore Weiss", it is also merchant menus. Sometimes game crashes first time you enter/leave said menus, and sometimes you can play about an hour to encounter error. Also, for me it is not on menu enter only, but on menu exit either. Game crashes, emulator hangs (renderer window and main window). There is an RPCS3.buf file in rpcs3 folder, is it helpful to upload it somewhere?

**Comment by kd-11** [comment]
That's the problem though, if I try for around 15 minutes and nothing happens I have to move on to something else. I'll revisit this issue over the weekend while I finish redesigning the whole MTRSX ecosystem.

**Comment by kd-11** [comment]
Try with https://ci.appveyor.com/project/kd-11/rpcs3/build/artifacts

**Comment by kd-11** [comment]
After a playthrough of dark souls with the aforementioned build I am convinced the lockup issue is now gone. Calling for testing here, I don't want to make assumptions and close prematurely.

**Comment by nev3rfail** [comment]
Still present:
`E {RSX [0x00f9694]} RSX: CB chain has run out of free entries!` second time I left merchant menu.
Quick steps for reproduce:
1. to go to any merchant (white dots on minimap)
2. buy something
3. exit from merchant menu back to game
4. repeat

Also works with Grimore Weiss as starting post states.
Quick steps for reproduce:
1. press start, choose "Grimore Weiss"
2. roam randomly left/right, enter some submenus
3. exit from grimore menu back to game 
4. repeat

I got error every second or third time. Tested with my own saves and save from starting post.

**Comment by kd-11** [comment]
Hold up, are you saying you see the error, or you get the deadlock? Seeing the error is harmless, it's just a performance warning.

**Comment by nev3rfail** [comment]
This line is last one I see before game hangs.

**Comment by kd-11** [comment]
Well, still can't make it happen on my end, not sure why. I was able to get it once and only once in something like 10 hours, but I could not repeat.

**Comment by jeremybris** [comment]
I am getting this on Motorstorm 1 [BCES00006]. It's like 2/10 times, always in the main menus.

To reproduce, it should happen no further than when you hit play in the main menu.

![Capture4](https://user-images.githubusercontent.com/11889359/76151088-e3aaf880-607e-11ea-9899-1d4bda4903cf.PNG)

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/7766

I was never actually able to reproduce it in the end, but that fix is reported to work.

**Comment by okass** [comment]
nice ill try it out later

**Comment by okass** [comment]
just confirming this fixed the issue
