### ISSUE TITLE
The Cave [NPUB30676] overbloom effect

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7429]
this has the same problems as Trine 2  #5610 
![cave](https://user-images.githubusercontent.com/2696404/74077282-6c6f4e00-4a59-11ea-951a-90fdaacde175.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4173626/RPCS3.log.gz)
[captures.zip](https://github.com/RPCS3/rpcs3/files/4173629/captures.zip)

**Comment by AniLeo** [comment]
Requires retesting with #8367

**Comment by AniLeo** [comment]
Overbloom was actually already fixed, will close and the remaining lighting issue will be tracked on #5610

**Comment by benderscruffy** [comment]
this needs to be reopened
trine 2 is fixed for me aswell but this game still has the same problem so not the same as #5610
![cave](https://user-images.githubusercontent.com/2696404/83967400-829bf680-a8f3-11ea-938b-39d29dba6aef.PNG)

**Comment by Asinin3** [comment]
@benderscruffy  Please retest. Also it goes without saying that you tried using write color buffers right? And other gpu/advanced buffer settings etc?
