### ISSUE TITLE
GoldenEye 007™: Reloaded [NPUB30752] lighting issue on Vulkan and Opengl

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7432]
during gameplay when you look around at light sources they become really bright 
![007 1](https://user-images.githubusercontent.com/2696404/74078306-c83ed480-4a63-11ea-8fce-2ee4d9ad68a8.PNG)
![007 2](https://user-images.githubusercontent.com/2696404/74078307-caa12e80-4a63-11ea-8efe-91bc1bc01769.PNG)
![007 3](https://user-images.githubusercontent.com/2696404/74078308-cc6af200-4a63-11ea-981c-308e70e74a38.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4173709/RPCS3.log.gz)
here are a few RSX captures
https://mega.nz/#!ByI1yCKA!p2olpKfDjEL_4FJwGHSmEKBMVp6f81ExaR5nSWWWVjE

**Comment by kd-11** [comment]
Did you try with the all the buffer options enabled? might be solved by just enabling WCB and/or CPU blit.

**Comment by jeremybris** [comment]
Hey, I used to have this issue, but it has been fixed for me. Hbu?

**Comment by benderscruffy** [comment]
this is fixed now
