### ISSUE TITLE
"Boot with global configuration" doesn't work on disc games with updates

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#7433]
When booting disc games with updates installed, "Boot with Global Configuration" still uses settings from game-specific configuration. These games first try to boot from the disc and then switch to HDD to run the updated executable, my theory is that this confuses the emulator and causes it to lose track of the global config preference.

Here's a log of a game that was had renderer set to null in custom config and vulkan in global. The game booted with nothing being rendered.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4173928/RPCS3.log.gz)

**Comment by Megamouse** [comment]
you can test this much easier if you enable/disable the native overlays

**Comment by MSuih** [comment]
Seems to affect all settings, yes.
