### ISSUE TITLE
Frame stutter in fullscreen after #6039 on Windows 7

### ISSUE THREAD

**Issue by voorunde** [RPCS3/rpcs3#7449]
After PR #6039 there's occasional frame stuttering when a game is in fullscreen, only when its fps is limited by V-sync.

0.0.6-8172-e118c9e5
![8172](https://user-images.githubusercontent.com/60842735/74101199-4d9bb500-4b48-11ea-99ca-0842e3703b49.png)

0.0.6-8174-f2cac261
![8174](https://user-images.githubusercontent.com/60842735/74101201-55f3f000-4b48-11ea-9f94-174178abe85e.png)

0.0.8-9541-792c481f
![9541](https://user-images.githubusercontent.com/60842735/74101205-64daa280-4b48-11ea-9d84-703e5747a98a.png)

It doesn't happen on Windows 10, or when in windowed mode, or when the game's framerate is limited by anything other than V-sync.
Tested on Nvidia drivers 442 and 399. The problem appears either when vsync is turned on in RPCS3 or forced through driver controls.

**Comment by psennermann** [comment]
Windows 7 has been deprecated by Microsoft so...well (IMHO) is it worth to "support" it anymore?

**Comment by 13xforever** [comment]
RPCS3 is relying on drivers for proper submit timings now, so if anything you should bug nVidia

**Comment by kd-11** [comment]
Try using 60Hz refresh rate. Or set rpcs3's vblank rate to match your odd display timing, but beware it can break the game's internal timing events. PS3 does not support 75Hz displays at that refresh rate and software isn't actually made to account for it.

**Comment by voorunde** [comment]
I don't think it has to do with a particular refresh rate. Here's tested at 60hz:

0.0.6-8172-e118c9e5
![8172](https://user-images.githubusercontent.com/60842735/74103579-29e36980-4b5e-11ea-813c-600610bed422.png)

0.0.8-9541-792c481f
![9541](https://user-images.githubusercontent.com/60842735/74103581-31a30e00-4b5e-11ea-9d90-80ea328aec47.png)

Here's tested at 50hz

0.0.6-8172-e118c9e5
![8172-2](https://user-images.githubusercontent.com/60842735/74103583-39fb4900-4b5e-11ea-9e98-725e4de081cf.png)

0.0.8-9541-792c481f
![9541-2](https://user-images.githubusercontent.com/60842735/74103584-3ebffd00-4b5e-11ea-8632-4286bfea0bb3.png)

**Comment by kd-11** [comment]
Here's the problem though, the PR is working as intended. If you run the old build with vulkan asserts enabled, the driver constantly complains and may crash. So the 'aux' queue has to wait, which means it cannot smooth random spikes anymore if the CPU is more than 2 frames behind. This is by design, it was a mistake the way it was running before.
At this point, I have to assume the vsync is doing something messy for rpcs3, seemingly holding the CPU back for some reason. Does windows 7 support fast sync? That might solve your problem better than double-buffered vsync.

**Comment by voorunde** [comment]
It is not a problem for me personally because I mainly use Windows 10, I just thought it might help people who are still on Windows 7. If pr is working as intended then there's little to be done, except maybe not listing w7 in recommended requirments for rpcs3. My configuration is 8700k and gtx 1080.

**Comment by kd-11** [comment]
Fair point. With w7 being EOL it should be moved to minimum requirements instead.
