### ISSUE TITLE
Zone of the Enders 1 HD Collection broken textures using Vulkan

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#7452]
Using AMD RX 580 8GB with Adrenalin 19.12.1.
Vulkan:
![scr_vulkan](https://user-images.githubusercontent.com/36518512/74107658-bdbf3080-4b72-11ea-9c3f-2733acb60261.png)
OpenGL:
![scr_ogl](https://user-images.githubusercontent.com/36518512/74107659-c1eb4e00-4b72-11ea-808b-4846e3bf7ef5.png)
Vulkan and OpenGL RSX Capture:
[vulkan_and_ogl_rsx_captures.zip](https://github.com/RPCS3/rpcs3/files/4177381/vulkan_and_ogl_rsx_captures.zip)
Log:
[vulkan.log.gz](https://github.com/RPCS3/rpcs3/files/4177383/vulkan.log.gz)

Looks like on nVIDIA works fine (credits 13xforever):
![unknown](https://user-images.githubusercontent.com/36518512/74107678-f828cd80-4b72-11ea-836c-57ab71814343.png)

**Comment by kd-11** [comment]
Please retest.

**Comment by jade010** [comment]
Same problem using 0.0.9-9791, 
RSX Capture on Vulkan : 
[BLES01756_20200301123242_capture.zip](https://github.com/RPCS3/rpcs3/files/4271717/BLES01756_20200301123242_capture.zip)

**Comment by digitaldude555** [comment]
How about now?

**Comment by sorasword** [comment]
This is still an issue as of 1/1/2023 using latest RPCS3 with a RX5600xt on Adrenalin 22.11.2. I unfortunately have no luck with either OpenGL or Vulkan.

**Comment by AniLeo** [comment]
Please retest and update this issue with AMD drivers 23.2.1 or newer as recently there have been changes that positively impact RPCS3.

**Comment by sorasword** [comment]
> Please retest and update this issue with AMD drivers 23.2.1 or newer as recently there have been changes that positively impact RPCS3.

Updated to Adrenalin 23.2.2 and RPCS3 Version: 0.0.27-14788-1d7a0066, still having the same issue with both OpenGL and Vulkan using the default settings.

**Comment by EQQx110** [comment]
Textures are still broken with Zone Of The Enders HD Collection, on both ZOE 1 and The 2nd Runner using:

AMD Radeon RX 6700 XT graphics card
Adrenaline v23.4.3
RPCS3 v0.0.27-15050-3aa15c8a

I have tried both Vulkan and OpenGL, almost same problems with textures.
If I can help in any way (by providing info, logs, trying different settings, etc...) I would be happy, so let me know.

**Comment by RobbedColek** [comment]
I'd like to just confirm that it's working properly on NVIDIA GPU.

Vulkan rendered tested.

RPCS3 v0.0.27-cbe1628c
AMD Ryzen 9 5900X
GTX 1080 
Windows 11

There are some slowdowns in some places, but it seems to be because of MLAA turned on on some of the maps.

**Comment by kd-11** [comment]
Verified. Only affects the windows AMD driver, AMDVLK which is the same driver with LLVM backend works fine on linux.

**Comment by EQQx110** [comment]
> Definitely an AMD compiler bug with nested ifs inside an infinite loop outer block. I can rewrite it easily to avoid the issue but a bug report is needed to get this resolved by the vendor.

I'm no expert in these things and almost never comment on github, so excuse my noobish questions in general:
Can't you report it? I would, but I don't know how it works, unlike you.

**Comment by kd-11** [comment]
It was reported a few weeks ago. We're waiting for a fix.

**Comment by sorasword** [comment]
> It was reported a few weeks ago. We're waiting for a fix.

Any updates on this?

**Comment by kd-11** [comment]
The bug tracker shows a fix was provided in Dec 2023. Now we wait until it ships in an official driver release.

**Comment by kd-11** [comment]
This issue was fixed. I tested with the latest driver on a 7900 GRE card.
