### ISSUE TITLE
Spec Ops: The Line | RSX Verification Failed

### ISSUE THREAD

**Issue by RainbowCookie32** [RPCS3/rpcs3#7454]
The game seems like it can be Playable, but there's this spot in the game that consistently triggers a crash with `RSX: St13runtime_error thrown: Verification failed (e=62): 
(in file ../rpcs3/Emu/RSX/RSXThread.cpp:355)`.

Luckily, this is probably one of the easiest crashes to reproduce in the history of crashes, so I'm attaching a save that loads pretty much straight into it. Just load it and the crash will happen a few seconds into the cutscene.

[The save](https://github.com/RPCS3/rpcs3/files/4178140/BLES01157-SPECOPSSAVE.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4271103/RPCS3.log.gz)

**Comment by dio-gh** [comment]
Can confirm on my machine as well. Altough if you enable relaxed zcull, you're able to progress beyond. That option breaks the game's graphics, however.

**Comment by RainbowCookie32** [comment]
Still an issue on commit 256c74d

`{RSX [0x0067e9c]} SIG: Thread terminated due to fatal error: Verification failed (e=62): 
(in file /home/rainbowcookie32/Documents/RPCS3/rpcs3/rpcs3/Emu/RSX/RSXThread.cpp:356)`

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4524965/RPCS3.log.gz)

**Comment by Emulator-Team-2** [comment]
@RainbowCookie32 
Retest with PR: https://github.com/RPCS3/rpcs3/pull/8538.

**Comment by RainbowCookie32** [comment]
Still an issue with the PR
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4854228/RPCS3.zip)

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/8555

**Comment by RainbowCookie32** [comment]
Fixed indeed 👍 
![imagen](https://user-images.githubusercontent.com/16805474/86535535-628e3180-beb7-11ea-8f52-4513e4dc16d5.png)
