### ISSUE TITLE
Sonic Unleashed [BLUS30244] Incorrect Shadow Rendering

### ISSUE THREAD

**Issue by slashiee** [RPCS3/rpcs3#7455]
Shadows in Sonic Unleashed seemed to be rendered weirdly, especially on the cloth shader.

<img width="1729" alt="2020-02-09_19-56-31" src="https://user-images.githubusercontent.com/15317421/74120359-e4339a80-4b77-11ea-9c86-d412ad04f04f.png">

[RSX Capture](https://cdn.discordapp.com/attachments/207547103726010368/676279133767991296/BLUS30244_20200209195628_capture.7z)

Real Hardware for reference
<img width="960" alt="2020-02-09_20-18-45" src="https://user-images.githubusercontent.com/15317421/74120727-63759e00-4b79-11ea-9977-1d2edc3880d2.png">

[Source](https://youtu.be/hxGQJW94aVk)

OS: Windows 10 Home
CPU: AMD Ryzen 9 3900X 12-Core Processor 
GPU: NVIDIA GeForce RTX 2080
Driver: 442.19.0.0

Log that goes to Rooftop Run Act 1 (1st screenshot): [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4178978/RPCS3.log.gz)

RSX captures do seem to be a bit iffy with Sonic Unleashed, if needed I can try to provide RenderDoc captures. It's also worth mentioning that when upscaling the game, shadows have missing pixels in them.

**Comment by Cervoxx** [comment]
## Quick summary
Tails from sonic unleashed has weird shaded gloves. These weird shading issues also persist in in-engine cutscenes.

## Details
- Real HW: https://youtu.be/74Q5w378tOs?t=2084
- Emulator visuals: https://i.imgur.com/YZD3xaB.jpg
- RSX capture: https://files.catbox.moe/ah9nyw.7z
- Renderdoc: https://files.catbox.moe/vz243f.7z
- Serial: BLUS30244
- Version: 1.02

**Comment by AniLeo** [comment]
Requesting submission review from @kd-11

**Comment by kd-11** [comment]
Unfortunately to replay a turing capture you need a turing card. I'll see if we can find something in the rsx capture though, could be some filtering issue or precision clamping in the fp16 code. Any AMD users with this issue should report it as well so we can get more data points.
In the meantime I'd suggest first disabling native fp16 in the config.yml and see if it helps.

**Comment by slashiee** [comment]
Still happens with `Disable native float16 support` set to `true`
<img width="1729" alt="2020-04-10_13-58-14" src="https://user-images.githubusercontent.com/15317421/79022689-6407c200-7b33-11ea-95ef-a027121f7126.png">

**Comment by windwhirl94** [comment]
Also happens with BLES00425.

OS: Windows 10 Pro
CPU: Ryzen 5 3600
GPU: Radeon RX 580 8 GB - Adrenaline 20.4.2
RPCS3 ver. 0.0.10.10394

![2020 05 16-15 37 mp4_snapshot_00 09 876](https://user-images.githubusercontent.com/61765524/82128010-ff710000-978d-11ea-8230-6c406073e396.png)

RSX Capture: https://files.catbox.moe/sscq94.rrc
RenderDoc Capture: https://files.catbox.moe/ik5lfn.7z
RPCS3 log:[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4639095/RPCS3.log)

**Comment by slashiee** [comment]
Worth mentioning that this also occurs when the shader interpreter is forced on.
<img width="1729" alt="2020-05-18_15-23-13" src="https://user-images.githubusercontent.com/15317421/82265639-5573ae00-991c-11ea-92b2-c83d401c7ba7.png">

**Comment by windwhirl94** [comment]
As far as I have tested, this issue is not affected by PPU/SPU decoders' settings, nor RSX multithreading, nor Shader Mode, nor Resolution or Renderer settings. The Read/Write Depth/Color Buffers options don't affect this issue either.

**Comment by slashiee** [comment]
Can confirm that #8367 fixes this issue.
<img width="1729" alt="2020-06-06_15-08-21" src="https://user-images.githubusercontent.com/15317421/83955415-90744d80-a807-11ea-8982-f24e51a869d9.png">

**Comment by Millennium-Eagle** [comment]
I hate to be the one to point this out, but while this did fix the obvious shadow glitches like with Sonic's gloves, the baked shadows on the ground are still not accurate to hardware.
