### ISSUE TITLE
[BLUS30463] Guitar defaulting to controller+mic instead of guitar

### ISSUE THREAD

**Issue by plonk264** [RPCS3/rpcs3#7462]
## Quick summary
guitar (currently using a Guitar Hero 3 guitar) is defaulting to controller+mic rather than guitar

## Details
Please provide as much detail as you can here, including
- expected (real hw) and observed (emulator) behavior
GH3 guitar (and RB2 guitar) works as guitar in Rock Band 3 on hardware. and even works in Rock Band 2 on RPCS3 (build 7969). however, build 9546 is only thinking the controller+mic is being activated/started (i even Null'd out the DS4 in the Player 1 tab and physically disconnected it, and put the MMInput: Guitar on the Player 1 tab)
- screenshots, Renderdoc, and RSX captures (for visual issues)
![unknown](https://user-images.githubusercontent.com/4464684/74144200-89229780-4bb9-11ea-915e-69c437d7573c.png)
![unknown (1)](https://user-images.githubusercontent.com/4464684/74144213-8d4eb500-4bb9-11ea-858d-50b5b7b04515.png)

Rock Band 2 with working guitar behavior (logs visible):
https://www.youtube.com/watch?v=cwYHDFOlKrk
https://www.youtube.com/watch?v=3jpgMFj7pXo

**Comment by leftyfl1p** [comment]
Duplicate of #7457. This game has another issue with USB not initializing properly that prevents it from being playable.

**Comment by AniLeo** [comment]
There's a bug on sys_usbd games as discussed on Discord, this issue specifically details the RB2 guitar not working, which is a bug, Guitar as a normal pad on Pad Settings stuff is unrelated

**Comment by Kenderlovag** [comment]
Just tried RB3 with GH guitar, unfortunately exactly how you described, RB2 works great.

**Comment by Megamouse** [comment]
There have been updates since back then.
- Plugging in the guitar per USB before booting the game might just work natively without any pad settings.
- If that's not working then the device class selection in the pad settings now lets you choose the type of guitar as well.

**Comment by YuriNator557** [comment]
Confirmed, no longer an issue. Set controller type to Guitar > Rock Band

![image](https://user-images.githubusercontent.com/76178650/139483187-9c7d7612-103e-4243-b51b-e016a32b8f23.png)
