### ISSUE TITLE
[BCES01086] After some time, LBP2 freezes with an "Access violation writing location 0xffdead00" [Unmapped Memory]

### ISSUE THREAD

**Issue by B-Knight49** [RPCS3/rpcs3#7469]
## Quick summary
RPCS3 0.0.8-9545-16bbd938
i9-9900K @ 5.00Ghz 
GTX 980Ti 
16GB DDR4 @ 3600Mhz \ CL15

Roughly every 45 - 90 minutes LittleBigPlanet 2 crashes with the fatal error:
`F {SPU[0x2000100] Thread (jobmanagerCellSpursKernel2) [0x00f00]} VM: Access violation writing location **0xffdead00**`

The memory location is always the same in the error, 0xff**dead**00. Which, I've gotta point out, is the best and most suitable mem-violation crash of all-time. 

## Details
Interestingly, the audio from the game is fine even after the fatal error. Shortly before the complete crash, FPS slows to a crawl and about a second later freezes altogether forcing me to quit.

### Important note regarding logs:
LittleBigPlanet 2 logs are always huge because of 2 repeated warnings that spam the console. In just that ~90 minute session, my log file is now **8GB** and the compressed log file is **400MB**. It's 69 million lines long. I will upload the compressed version to MEGA [(Link here)](https://mega.nz/#!hm5BwCaI!PIFTY9SkJT3tOkO2h1cfwt3zKqSstL41pM_V1Kpb-CM). I tried editing the .log using Python to remove the warnings but it can't recognise the encoding unfortunately. Sorry.

The warnings that spam the log if you guys plan on compressing the file yourselves:

- `Â·W 0:00:39.635959 {PPU[0x1000000] Thread (main_thread) [0x00ec5ef8]} sceNp: sceNpUtilCmpNpId(id1=*0xe23f30, id2=*0xdc4d1c)`
- `Â·W 0:00:39.636006 {PPU[0x1000017] Thread (PSMove Read Thread) [0x00ec0c50]} cellCamera: cellCameraIsAvailable(dev_num=0)`

**Comment by AniLeo** [comment]
0xffdead00 is a SPU halt
https://github.com/RPCS3/rpcs3/blob/c0f80cfe7a2a05011bffc51b9bb85c18478af637/rpcs3/Emu/Cell/SPURecompiler.cpp#L7773

**Comment by B-Knight49** [comment]
Could that be indicative of a certain setting I've got enabled?
Alternatively, I've got Whatcookie's MLAA patch enabled but, from what I'm aware, that's a PPU thing no?

**Comment by AniLeo** [comment]
No. Also, you shouldn't really submit issues when using game patches, make sure it happens without them.

**Comment by B-Knight49** [comment]
Yeah, I only just remembered I had the patch enabled. I'll close the issue if it turns out it's the patch otherwise I'll leave it open.

**Comment by B-Knight49** [comment]
Okay, an interesting follow-up:

I changed the patch.yml's file extension to path.yml.disabled. Whilst at it, I also disabled all logging by making the .log and .log.gz read-only. I then rebooted RPCS3 and played LBP2 for about 3-4 hours without any crash at all. Interestingly, the MLAA patch was still applied and working so I assume .disabled doesn't prevent the emulator from reading the patch.yml and that therefore leads to the logs being the culprit. 

Like I mentioned, LBP2 makes an absurdly large log file and if it seems to crash consistently after a certain time-frame, that leads me to believe that the log file reaches a certain size or certain point and then throws the error. Could it be a memory issue? Though I feel like an OOM error would lead to a full emulator crash instead. 

I honestly wouldn't be surprised if the logs were causing it. In previous versions of the emulator when I couldn't maintain a constant 30FPS, disabling logging through my method above typically gave a 3-4FPS performance boost. And, of course, it seems logical that 8GB worth of raw text might just end badly for the program...

**Comment by Whatcookie** [comment]
the patch wouldn't be loading if it was named patch.yml.disabled, It may be related after all.

**Comment by B-Knight49** [comment]
It definitely was loaded. Crystal clear upscaling and perfect 30FPS. Like I showed you on Discord the other day when I was being dumb with the debug build and CPU Blit. 

If it wasn't enabled then that's going to make this situation a 1000x more confusing because I am absolutely adamant that MLAA was disabled. The picture quality was crystal clear at 1440p and I'm certain it was the official build since it has my profile data that I copied from my PS3.

I'll provide screenshots and information tomorrow since it's 4am but I truly can't express how confident I am that MLAA was off and upscaling was working perfectly.

**Comment by Whatcookie** [comment]
the "crystal clear image" is possible even without my patch so long as you enable cpu blit, that option is what makes resolution scaling work. The patch only skips work on the spu side and doesn't fix any resolution issues.

**Comment by B-Knight49** [comment]
Damn, how long has that been the case? I've been waiting months for an MLAA removal patch solely for the image quality but all along it was simply cpu blit? Fuck my life hahaha. 

In that case, yeah, I can see how it'll be the patch. Let me know how I might be able to help you out tomorrow. I'll re-enable logging and send it through. For now I'm going to sleep and seriously debate the fact I waited months for MLAA removal when it was CPU blit all along...

**Comment by B-Knight49** [comment]
I just got the crash whilst the patch was disabled. Rules that one out. Unfortunately I had logging disabled at the time, but it proves it's not your patch at least.

**Comment by B-Knight49** [comment]
Crashed twice now with the patch disabled, this time I had logging enabled. Seems like the timeframe is random too since I just played for 2 hours and 49 minutes before it happened. 

As usual, LBP2 logs are absurd. 24GB this time (which is honestly small for 3 hours in-game). 700MB double-compressed. [Uploading to MEGA now...(url)

Let me know if there's anything I can do to make the log more reasonable in the future. I don't even know of any program that can open a 24GB text file.

**Comment by GitArUs** [comment]
I'm not sure if it is related, but I'm observing similar errors and similar behavior in FFXIII-2. Happens always around the same moment during episode 1 intro (when the meteor appears on the sky or when I try to skip this particular scene):

·F 0:06:16.497580 {SPU[0x1000100] Thread (UserSpursCellSpursKernel1) [0x00ee8]} VM: Access violation writing location 0xffdead00 (unmapped memory)

·F 0:09:12.141121 {SPU[0x4000100] Thread (UserSpursCellSpursKernel4) [0x03930]} VM: Access violation reading location 0xb10 (unmapped memory)

And although it seems to be related to SPU I can prevent it from happening only in one way - by switching PPU decoder to "Interpreter (fast)". Switching SPU to recompiler/interpreter does not make any change.
(side note: switching PPU to interpreter also fixes disappearing/flickering of character/npc models in ffxiii games).

Log: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4246821/RPCS3.log.gz)

**Comment by B-Knight49** [comment]
I feel confident that this is fixed. I recently played through the entire story mode - beginning to end - and never got this once. Also played ~3 hours in Creative mode yesterday and nothing of the sort either. 

I'll close it, but if anyone else gets this issue: comment and I'll reopen.

**Comment by ThePoker96** [comment]
I have this problems F {PPU[0x100000e] Thread (MOMainThread) [0x00dceca0]} VM: Access violation reading location 0x0 (unmapped memory) Demon's Souls
