### ISSUE TITLE
MLB The Show 09 [BCUS98180] crashes when loading any save data

### ISSUE THREAD

**Issue by connorwalks** [RPCS3/rpcs3#7472]
## Quick summary
When booting the game, if there is any save data for it, it crashes on intro (auto loading settings, user profile, etc). Without save data, it is perfectly playable.

## Details
RPCS3 v0.0.8-9568-bcbe3245 Alpha | HEAD | FW 4.85 | Windows 10 1909
Intel Core i9-9900K | 16 Threads | 15.86 GiB RAM | AVX+ | TSX-FA
GPU: GeForce RTX 2080 (442.19)

On current master the game boots fine and is playable as long as there is no save data for BCUS98180 in `dev_hdd0\home\00000001\savedata`. If there is any save data such as a user profile or settings that the game tries to automatically load, it crashes with the following error: `VM: Access violation reading location 0xd2d0a0a0`

This issue was initially reported as a regression as #5798. However, after doing some testing myself, this has always been an issue and the PR blamed in that issue actually changed nothing. I even went back and tested on 0.0.5-6906 and I was able to replicate this issue. That author also seemingly abandoned the issue and closed it for no reason, as I have yet to see any build in which this issue does not occur. This is and always has been an issue. Let me know if any further information is needed

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4189851/RPCS3.log)

Crash screen:
![MLB 09](https://user-images.githubusercontent.com/48158481/74303399-a83f3780-4d27-11ea-9312-03c69a82aa34.png)

**Comment by incognitoh** [comment]
must be something youre doing wrong.  saves load fine for me.  no special settings
and actually the PR blamed in that issue was indeed the culprit. autoload worked fine before 0.0.5-7182, thats just a fact.  no idea what youre doing wrong

**Comment by connorwalks** [comment]
Care to elaborate? Saying "works for me" isn't very helpful. Logs, settings, did you have the game update installed? You never even included a log in your original issue, only a screenshot. Are you on windows or linux?

Can you upload some sort of proof of it working? I'm running default settings + vulkan and it is most definitely still an issue. I checked the PR that was merged immediately before that PR you blamed and it was still problematic.

**Comment by connorwalks** [comment]
@incognitoh could you post some kind of log and proof showing the autoload works?

I have tested on multiple systems and am still having issues with autoload on both. Even tried redumping. If there's something I'm missing I'd like to know so I can close the issue and we can move the game to playable. But as of now it's still not working on my systems with default settings

**Comment by connorwalks** [comment]
Not sure exactly which build fixed this but issue seems to be fixed as of latest master (0.0.9-10228).

Unable to reproduce the issue anymore so I'm closing this
