### ISSUE TITLE
Truck Racer [NPEB01838] incorrect shadows and lighting on Vulkan and Opengl

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7486]
![truck](https://user-images.githubusercontent.com/2696404/74580491-c931b200-4fdf-11ea-93a8-358ae4573363.PNG)
![truck1](https://user-images.githubusercontent.com/2696404/74580493-cafb7580-4fdf-11ea-9be4-3c4a889fa98a.PNG)
![truck2](https://user-images.githubusercontent.com/2696404/74580495-ccc53900-4fdf-11ea-8453-43922c42bd07.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4207668/RPCS3.log.gz)
here is a couple of renderdocs
https://mega.nz/#!9m4TQCTK!mWRcgFGbLtqCW0SjOo3Gar-7WGSbgElcLBN0ITwFPeE
here is a couple of RSX captures
https://mega.nz/#!EmwDWQQa!KgWQ3QDGMaa8sIcBbgvOjTeU_3bZSMfhkscMvq3S6Ro

**Comment by AniLeo** [comment]
Needs testing with #8367

**Comment by benderscruffy** [comment]
fixed with #8367
