### ISSUE TITLE
[NPEA00430] - Resistance: Fall of Man - Out of Bounds Bug

### ISSUE THREAD

**Issue by web1018** [RPCS3/rpcs3#7492]
## Quick summary
After dying at any point during the gameplay a bug occurs where the player starts flying towards the sky and out of bounds and gets stuck there infinitely until a player resets the game again after quitting to the main menu and starts the game from the last checkpoint.

## Details
RPCS3 v0.0.8 - 9593 - ddf87864 Alpha | Hardware Specs :
Nvidia GeForce GTX 960M | Intel Core i7 6700HQ | 16GB of Ram | Windows 10

This is a known bug that has been around for a while and there is currently no known fix for this bug. 

## Screenshot
![Annotation 2020-02-15 074814](https://user-images.githubusercontent.com/51851411/74588059-7c41e180-4fc7-11ea-861e-ab7f7d298f45.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4208474/RPCS3.log.gz)

## Update

- Further Regression after #7304. The screen turns black after the player dies and the game hangs. There is currently no fix for this issue either. Further updates will be released upon change.

**Comment by jeremybris** [comment]
Will you retest with the latest RPCS3, and tell us if this still happens, please?

**Comment by lainiwaku** [comment]
#7304 is a regression for RE
On ASMJIT recompiler =
before #7304 = player REspawn and jump out of the map
after #7304 = black screen
On LLVM recompiler =
Enemies spawns bugged and make the emulator crash
[RPCS3ASMJIT.log.gz](https://github.com/RPCS3/rpcs3/files/4223696/RPCS3ASMJIT.log.gz)
LLVM recompiler : 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4223697/RPCS3.log)

**Comment by web1018** [comment]
> #7304 is a regression for RE
> On ASMJIT recompiler =
> before #7304 = player REspawn and jump out of the map
> after #7304 = black screen
> On LLVM recompiler =
> Enemies spawns bugged and make the emulator crash
> [RPCS3ASMJIT.log.gz](https://github.com/RPCS3/rpcs3/files/4223696/RPCS3ASMJIT.log.gz)
> LLVM recompiler :
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/4223697/RPCS3.log)
> 
> EDIT : i just tested with "SPU DECODER : Interpreter (fast)"
> and it works just great with this one, player can respawn, enemy spawn without bugs

Can Confirm that after the #7304, there is a regression. The game goes into black screen after death with LLVM Recompiler, as well as other bugs do occur.

**Comment by digitaldude555** [comment]
Can be closed now.

**Comment by AniLeo** [comment]
Closing as fixed
