### ISSUE TITLE
game.yml corruption can cause emulator crash

### ISSUE THREAD

**Issue by Nerboruto** [RPCS3/rpcs3#7495]
I currently don't have the corrupt file with incomprehensible characters after an emulator crash.
I solved it by deleting the file.

**Comment by Nekotekina** [comment]
Ok, maybe there is a fix to improve this situation.

**Comment by MSuih** [comment]
Corrupted config.yml can end up causing emulator not to boot as well. Our yml parser isn't good at handling corrupted files.
