### ISSUE TITLE
[NVIDIA ONLY] vulkan performance regression

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#7502]
Gran Turismo HD Concept exhibits a severe performance regression since #7487 

Screenshots with MSI Afterburner overlay demonstrating the issue:
Before problematic PR (0.0.8-9594) (locked 60 FPS, lower CPU and GPU usage)
![rpcs3_9594](https://user-images.githubusercontent.com/4345150/74600191-d4acd800-50c8-11ea-8758-d3f08936e844.png)

After problematic PR (0.0.8-9595) (47 FPS, drastically increased CPU and GPU usage, staticky audio)
![rpcs3_9595](https://user-images.githubusercontent.com/4345150/74600203-de364000-50c8-11ea-990b-ba15265e1004.png)

Logs:-
For the unaffected build (0.0.8-9594):-
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4209419/RPCS3.log.gz)

For the affected build (0.0.8-9595):-
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4209420/RPCS3.log.gz)

System Specifications:-
Intel i7-7700 @ 4 GHz
NVIDIA Geforce GTX 1070TI
32 GB DDR4-2400 RAM
Game running on SSD

**Comment by solarmystic** [comment]
Other games have basically gone up in GPU demands as well since #7487 :-

Demon Souls [BLUS30443]

Before:- locked 60 FPS, with a very smooth frametime graph and lower GPU utlization
![rpcs3_before](https://user-images.githubusercontent.com/4345150/74601594-d8e1f100-50da-11ea-9546-bda525aab37e.png)

After:- still 60 FPS but the frametime graph is more erratic, with 22% higher GPU utilization at the same settings (stock except Write Color Buffers and 4K) with the same scene
![rpcs3_after](https://user-images.githubusercontent.com/4345150/74601596-e13a2c00-50da-11ea-9d7c-00dbcf4d58f4.png)

Tekken 6 [BLES00635]

Before:- locked 60 FPS, lower GPU utilization
![rpcs3_t6before](https://user-images.githubusercontent.com/4345150/74601931-59eeb780-50de-11ea-89fe-ffd9d9d29246.png)

After:- still 60 FPS, but with a higher 31% GPU utilization at the same settings with the same scene
![rpcs3_t6after](https://user-images.githubusercontent.com/4345150/74601935-6bd05a80-50de-11ea-8a4d-0347acb5d3d5.png)

**Comment by kd-11** [comment]
This is an nvidia-only bug, I'm working on a workaround.

**Comment by Nerboruto** [comment]
unfortunately I had also noticed that on nvidia vulkan performances decreased...

**Comment by kd-11** [comment]
workaround commited into master.
