### ISSUE TITLE
Regression - PS1 Classics games fail to boot with SPU LLVM

### ISSUE THREAD

**Issue by CookiePLMonster** [RPCS3/rpcs3#7503]
## Quick summary
After #5882, PS1 Classics games stopped booting with SPU LLVM enabled. Instead of the iconic PSX logo, an error dubbed "Personified Fear" plays. From what I know, other than being a jumpscare it plays when some files on the PSX disk are corrupted.

## Details
The exact build in which it broke is **0.0.6-8043**.

[RPCS3.log-8039.gz](https://github.com/RPCS3/rpcs3/files/4209636/RPCS3.log-8039.gz)
[RPCS3.log-8043.gz](https://github.com/RPCS3/rpcs3/files/4209634/RPCS3.log-8043.gz)

**Comment by illusion0001** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/7944

**Comment by CookiePLMonster** [comment]
Fixed with #7944
