### ISSUE TITLE
vk: Verification failed: Invalid image layout! on game startup (Persona 5)

### ISSUE THREAD

**Issue by ConcealedSentinel** [RPCS3/rpcs3#7517]
## Quick summary
Persona 5 crashes once again, and this happens periodically.
I can’t remember the specific builds of the emulator versions, but one thing is certain: this game periodically ceases to work and it hangs with a black screen regularly after several builds, at least I have noticed this recently.
The problem was fixed last time with the next update of the RPCS3 version.
## Details
- full logs (not from UI)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4218072/RPCS3.log)

- screenshots, Renderdoc, and RSX captures (for visual issues)
![2020 02 18-10 48](https://user-images.githubusercontent.com/61180045/74717200-0e085380-5241-11ea-982b-832511c9924d.png)
![2020 02 18-11 14](https://user-images.githubusercontent.com/61180045/74717284-33955d00-5241-11ea-8d90-489157ebf120.png)
![2020 02 18-11 15](https://user-images.githubusercontent.com/61180045/74717323-40b24c00-5241-11ea-8641-0b8e9706072d.png)
![2020 02 18-11 15_01](https://user-images.githubusercontent.com/61180045/74717346-4a3bb400-5241-11ea-95b9-5e6325c9506c.png)

- your system configuration (OS, CPU, GPU, driver versions, etc)
PS3 Firmaware: 4.85
Windows 10 x64 Version 1803
CPU: AMD Ryzen 1700
Motherboard: MSI X470 Gaming Pro
Memory: DDR4 32 GB Samsung M378A2K43CB1-CTD x 2
GPU: Radeon RX 590 GDDR5 8 GB
GPU Driver: AMD Radeon Software Adrenalin 20.2.1 Beta
Sound card: Creative Sound Blaster Audigy RX/5

**Comment by AniLeo** [comment]
```
·F 0:01:35.420823 {RSX [0x0001538]} RSX: class std::runtime_error thrown: Verification failed: Invalid image layout!
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKTexture.cpp:142)
```

**Comment by AniLeo** [comment]
Possible regression, needs triaging

**Comment by kd-11** [comment]
Need info on first build that triggers the issue.

**Comment by kd-11** [comment]
I just noticed the OP has WCB+RCB+RDB enabled for this game which does not need any of those options enabled. Probably why it's not been encountered by others, it's the only thing I can think of.

**Comment by ConcealedSentinel** [comment]
Thank you so much for the tip.
The cause of the error was the parameter - RDB in additional settings. I have only checked the game so far for the possibility of launching as a whole.
With any combination of these parameters: RDB, WDB, RCB, if RDB is on, the game displays a black screen and freezes.

**Comment by ConcealedSentinel** [comment]
But are these parameters necessary in general for launching games at the moment, or only for individual cases for launching games?

**Comment by RainbowCookie32** [comment]
Some games need them, Persona 5 doesn't need any of those extra settings you enabled

**Comment by kd-11** [comment]
Ok, thanks for confirming. I'll see about fixing it correctly so it doesn't happen.
Those settings are rarely needed, only a handful of games need the options in "advanced" tab. The WCB option is in normal GUI options because some popular games need it for lighting to work properly, but it is very rare to need the other 3.

**Comment by lextra2** [comment]
For future reference, you could check out the [RPCS3 wiki](https://wiki.rpcs3.net/index.php?title=Main_Page) to see what games need which boxes to be checked.
