### ISSUE TITLE
BACKBREAKER VENGEANCE [NPEB00592] black playing field in Vulkan

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7518]
i think this is just an amd problem 
not fixed with WCB and Force CPU Blit
![back1](https://user-images.githubusercontent.com/2696404/74729671-c9e87380-527f-11ea-9b75-ee9f40ac0f8c.PNG)
![back2](https://user-images.githubusercontent.com/2696404/74729681-cce36400-527f-11ea-81be-f07993299c91.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4218769/RPCS3.log.gz)
here is a few RSX captures
https://mega.nz/#!dyQBlKQI!QobbLta-2AOBGTDYhfCahGi7oPv1DntIddzOa6BjKCw

**Comment by incognitoh** [comment]
disable Asynchronous Shader maybe...

**Comment by benderscruffy** [comment]
![backb](https://user-images.githubusercontent.com/2696404/74737557-07ed9380-5290-11ea-884d-ee569b3d18e2.PNG)
yep that did it 
Good find for that one

**Comment by jiddly** [comment]
> disable Asynchronous Shader maybe...

how do you disable Asynchronous Shader?

**Comment by Darkhost1999** [comment]
> how do you disable Asynchronous Shader?

Start with asking on our forums, or at our discord, reddit, or twitter.
Commenting on a 3 year old issue for support on a developer platform isn't the best way to go about it.

However, you can change your shader mode in the gpu tab of your settings/config.
