### ISSUE TITLE
pr #7513 Use more starts_with/ends_with cause performance regression 

### ISSUE THREAD

**Issue by Nerboruto** [RPCS3/rpcs3#7520]
tested on various games
low fps and big audio stuttering!!!
on my dualcore pc...
previous build is ok.

**Comment by AniLeo** [comment]
I believe issues have a template on them

**Comment by Nerboruto** [comment]
sorry I'm not in front of the pc I did from the phone ... as soon as possible I fix the post and I will do other tests ...

**Comment by Nerboruto** [comment]
[RPCS3-9614.zip](https://github.com/RPCS3/rpcs3/files/4220860/RPCS3-9614.zip)
[RPCS3-9619.zip](https://github.com/RPCS3/rpcs3/files/4220861/RPCS3-9619.zip)
9614 audio is ok 60fps solid in the opening screen
9519 audio stuttering 55fps in opening screen
I tried to clean up the cache but the result does not change

**Comment by elad335** [comment]
test #7521

**Comment by Nerboruto** [comment]
sound good!!!

**Comment by Nerboruto** [comment]
can we close? seems solved..

**Comment by RainbowCookie32** [comment]
Yeah, close it if it's fixed
