### ISSUE TITLE
Overlay eating performance

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#7523]
This is an extremely edge case since we are running at **over 6000FPS** and it most likely will never show up in real games, but the performance lost here is so drastic that maybe something good will come out of it. Here's a comparison between a few tests that i've done with the RPCS3 overlay and Rivatuner (3rd party).

**No Overlay**
![no overlay](https://user-images.githubusercontent.com/17715080/74795641-3a55bb80-52a5-11ea-9d71-326aeaabf5ff.png)
Performance is fine as it should be.

**RivaTuner Overlay**
![riva tuner overlay](https://user-images.githubusercontent.com/17715080/74795681-56595d00-52a5-11ea-85d2-750526faefff.png)
-1100FPS, thats fine since its a third party overlay.

**RPCS3 Overlay**
![rpcs3 overlay](https://user-images.githubusercontent.com/17715080/74795719-6d984a80-52a5-11ea-9879-633ee8fc7064.png)
This is where things goes south, 2400 frames lost just by having the overlay enabled. I did note that by every overlay added you lose about 800 frames i.e frametime graph, framerate graph.

But like i said, this is an extremely edge case and _probably_ won't hurt the framerate in actual games, i've tested Persona 5 and Ratchet and Clank Tools of Destruction and no performance loss was measured.

**Note:** To reproduce this you need the patch to uncap the framerate in triangle.elf provided below.

```
PPU-a17c612917900ad433c29bd09ecf297fc6d222bf: #triangle
- [ be32, 0x000122e8, 0x38600001 ] # li  r3, 1
```

**Comment by lextra2** [comment]
Does changing the polling rate of the overlay have any effect on this? For example, Try 1000ms instead of the default 350ms.

**Comment by VelocityRa** [comment]
The overlay is rendering orders of magnitude more things than the test elf in that instance so that's to be expected.

And the third-party overlay you showed _is_ faster, but it has no graphs.

**Comment by AniLeo** [comment]
I don't think there's an issue here, the perf hit seems reasonable considering the added graphs and the fact you're only rendering a triangle?

**Comment by Yahfz** [comment]
It's not really an issue, like i mentioned twice it doesn't affect actual games (at least the ones i tested).

**Comment by kd-11** [comment]
This is also not a pure overlay, other math is going into calculating the other statistics shown on screen and could be the bottleneck.

**Comment by kd-11** [comment]
Turns out its only a loss of 40 microseconds per frame, perfectly reasonable for this kind of thing.
