### ISSUE TITLE
NIER [BLUS30481] corrupt monsters graphics in Vulkan (AMD problem maybe ??)

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7526]
could be an AMD problem
not fixed with WCB and Force CPU blit
![nier](https://user-images.githubusercontent.com/2696404/74826941-6fb2e580-5347-11ea-9d8b-0243245230a1.PNG)
![nier1](https://user-images.githubusercontent.com/2696404/74826945-717ca900-5347-11ea-9648-ed5855700d59.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4224538/RPCS3.log.gz)
here is a few RSX captures
https://mega.nz/#!1j5l1T7K!EVrupXtA44VMyoqDHE_J9ZW_4H7thq27C5kpqsckx_M

**Comment by AniLeo** [comment]
I don't see the problem, can you clarify?

**Comment by benderscruffy** [comment]
my mistake doh
