### ISSUE TITLE
Feature request: Game progress import/export

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#7549]
"Bug report" doesn't feel like the best place to describe this so please feel free to move if it isn't:

Thinking about a feature where the user could right-click a game from the UI and select "Export all game progress" which would export a 7z-compressed file that would include the selected game's save and trophy data to a directory of the user's choice.

A corresponding option to "Import all game progress" would then decompress the selected file to its respective save and trophy directories after checking to ensure a Title ID match.

This can be done manually today of course, but this method should be easier especially in certain cases e.g. switching between rpcs3 instances on multiple systems.

**Comment by MSuih** [comment]
This is difficult to implement as games can have multiple save directories with completely arbitary naming. Trophies are using different ID numbering from games so it's difficult to find matches for those as well. We could try to find something that's close enough to the main game but that solution would have a lot of pitfalls.

**Comment by Shoegzer** [comment]
Ah, good point.  If not by ID numbering, is there something else in common between all game data or trophy data, maybe even folder creation dates if nothing else exists?  And failing that, could rpcs3 maintain and bind a unique index value across a given game's data so it could be pulled together when requested?

**Comment by MSuih** [comment]
There's not much common aside from names, and I feel like matching with those would cause a lot of issues. Linux does not store creation dates for things, so that idea's not going to work either.

Custom folder tracking would work, but sounds like a huge amount of work for such a niche feature.

**Comment by digitaldude555** [comment]
Close it.

**Comment by Shoegzer** [comment]
@MSuih No worries, and I can certainly close this if you feel it's really not worth any further consideration or effort.  That said I do think such a feature could be a big plus for users particularly in specific circumstances if a creative and reasonably stable/cross-platform solution can somehow be devised, and I'm willing to perform any tests.  I'll leave it up to you though.  Thanks either way!
