### ISSUE TITLE
#7551 Mobile Suit Gundam Senki [BLJS 10050] and Phantom Breaker: Extra [BLJM61098] breaks when displaying Japanese characters after loading "fatal error".

### ISSUE THREAD

**Issue by Shuneferus** [RPCS3/rpcs3#7561]
#7551 0.0.8-9675
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4240426/RPCS3.log)

Mobile Suit Gundam Senki [BLJS 10050] and Phantom Breaker: Extra [BLJM61098] breaks when displaying Japanese characters after loading "fatal error".

**Comment by kd-11** [comment]
Run the game with [this build](https://www.dropbox.com/s/diun69wbijjf4oi/rpcs3-dump-strings.7z?dl=1) and attach the log after it crashes.

**Comment by Shuneferus** [comment]
Good morning and thanks for the excellent work!

Phantom Breaker: Extra [BLJM61098] is now resolved.

Mobile Suit Gundam Senki [BLJS 10050] the error still remains.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4241749/RPCS3.log)

**Comment by kd-11** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/7580

**Comment by Shuneferus** [comment]
Hello KD-11 people, kindly if possible to send the link with executable #
7580. Thanks.

Em seg., 24 de fev. de 2020 às 13:37, kd-11 <notifications@github.com>
escreveu:

**Comment by kd-11** [comment]
Link https://ci.appveyor.com/api/buildjobs/mqg8cpr5572au6ck/artifacts/rpcs3-v0.0.8-142f11a0_win64.7z
You can also get them from the pull request page at the bottom by clicking the 'all checks passed' area and choosing the first option in the area that pops up.

**Comment by Shuneferus** [comment]
Problem was solved in both games thanks KD-11!

Mobile Suit Gundam Senki [BLJS 10050] is now resolved.
Phantom Breaker: Extra [BLJM61098] is now resolved.

**Comment by AniLeo** [comment]
PR still unmerged, issue reopened
