### ISSUE TITLE
Regression: Ratchet and Clank Future: ToD BCUS98127 causes the emulator to crash upon death

### ISSUE THREAD

**Issue by Cervoxx** [RPCS3/rpcs3#7562]
## Quick summary
If you die, you're supposed to respawn. Instead, the game hard crashes. This was tested by having Ratchet jump into the gap on Planet Fastoon.

## Details
This build and up has the regression: rpcs3-v0.0.8-9622-727d7839_linux64

This build and down does not have the regression: rpcs3-v0.0.8-9620-8a176de6_linux64

Please remember to attach TWO logs: one for the build that exhibits regression, and one for the previous build that works as expected.

Regressed build logs: https://files.catbox.moe/dccjxq.gz

Unregressed build logs: https://files.catbox.moe/x0s6og.gz

**Comment by elad335** [comment]
test latest master log as well.

**Comment by Cervoxx** [comment]
Latest master as in the latest build that was pushed out? Or compile from source?

**Comment by elad335** [comment]
The one on the website. Also define"hard crashes", if its just a freeze with no errors in log it makes a huge difference for debugging.

**Comment by Cervoxx** [comment]
Gotcha, will do. As for what I mean by hard crashes, the window where the game is running is frozen but the rpcs3 gui where you launch games and such works just fine. And stuff like the FPS counter stops updating. The emulator can close the game after the freeze and relaunch it. Perhaps I'm not using the right terminology?

**Comment by Cervoxx** [comment]
Logs of it happening on the latest version, which at the time of writing is rpcs3-v0.0.8-9682-7eccbecb_linux64: https://files.catbox.moe/miw8df.gz

**Comment by elad335** [comment]
Test with #7565

**Comment by elad335** [comment]
Can someone on windows test it ?

**Comment by SonofUgly** [comment]
> Test with #7565

Yep, that fixes it.

**Comment by 8hodgsonkh** [comment]
> > Test with #7565
> 
> Yep, that fixes it.

Im a noob with all this, how do I get the version with the fix? Do i have to compile? because I cant find it anywhere

**Comment by SonofUgly** [comment]
@8hodgsonkh - For Windows builds click the [green check mark on the commit, or 'Show all checks'](https://i.imgur.com/kuzMYns.png) on the bottom of the pull request page, and then click on the appveyor 'Details' link. Then on the appveyor site [click on the 'Artifacts' tab and download the largest file.](https://i.imgur.com/pdb377O.png)

**Comment by 8hodgsonkh** [comment]
> @8hodgsonkh - For Windows builds click the [green check mark on the commit, or 'Show all checks'](https://i.imgur.com/kuzMYns.png) on the bottom of the pull request page, and then click on the appveyor 'Details' link. Then on the appveyor site [click on the 'Artifacts' tab and download the largest file.](https://i.imgur.com/pdb377O.png)

Thank you so much! It works :D

**Comment by Cervoxx** [comment]
If only there was an appimage download for linux users. ;-;

**Comment by Cervoxx** [comment]
Fixed by #7565
