### ISSUE TITLE
Sly 4 [BCUS98247] photo issue and weird RSX Capture behaviour

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#7573]
When you take photos ingame, the resulting image won't show up. I have no idea if this is a regression or not.

![Képernyőfelvétel (11)](https://user-images.githubusercontent.com/10439488/75123689-2a294c00-56aa-11ea-9ec2-65272245d3de.png)

After taking an RSX Capture and resuming the emulation, the image does appear however:

![Képernyőfelvétel (12)](https://user-images.githubusercontent.com/10439488/75123701-3f9e7600-56aa-11ea-879f-284a7bfbaec2.png)

Tried with SRM and relaxed zcull on/off, AF 16x/Auto, etc., no change.

RSX Capture: [BCUS98247_20200223143831_capture.zip](https://github.com/RPCS3/rpcs3/files/4242831/BCUS98247_20200223143831_capture.zip)

Logfile: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/4242832/RPCS3.log)

System: recent master, Ryzen 3600 × GTX 1660 Ti

The MLAA off patch was not in use.

**Comment by digitaldude555** [comment]
But have you tried....write color buffers?

**Comment by dio-gh** [comment]
Sounds like nonsense but sure, I can give 'er a go.

**Comment by dio-gh** [comment]
No change with it enabled or not.

**Comment by dio-gh** [comment]
This ticket needs the `Bug` and `RSX` labels added.

**Comment by dio-gh** [comment]
Not interested in pursuing a fix for this issue anymore, if it's still a problem even.

If someone can take a fresh RSX capture of the issue still happening, please reopen.
