### ISSUE TITLE
Sonic 06 sometimes freezes the entire emulator when trying to play it

### ISSUE THREAD

**Issue by Cervoxx** [RPCS3/rpcs3#7574]
## Quick summary
Decided to load up sonic 06 in the emulator, upon loading into the world the emulator window froze as the game had crashed. Then when I tried to use the RPCS3 GUI, that had frozen too, my computer now prompting me to force quit the application. Heck, I even had to change the permissions of the log file just so I could upload it, since the emulator couldn't even do that.

Logs: https://files.catbox.moe/uw50y3.gz

Sonic 06 serial: BLUS30008

RPCS3 ver: v0.0.8-9697-1dc2eb1c_linux64

**Comment by Cervoxx** [comment]
In an attempt to reload the game over and over again to ensure the bug is reproducible, I encountered something strange. I "loaded" into the game just fine however upon closing the game window to go back to the RPCS3 emulator I had found that the emulator UI had frozen. With another prompt asking me to force quit the app.

Logs: https://files.catbox.moe/s9bsbp.gz

Video: https://youtu.be/gmSJdKod88Q

**Comment by Asinin3** [comment]
Closing, this game isn't listed as playable and logs aren't showing anything helpful to debug plus most people not experiencing this issue.

**Comment by Megamouse** [comment]
it's happening to me 50% of times

**Comment by elad335** [comment]
I think this was fixed. Closing.
