### ISSUE TITLE
OpenSSL broken on the Linux Appimage

### ISSUE THREAD

**Issue by Cervoxx** [RPCS3/rpcs3#7575]
## Quick summary
RPCS3 is unable to use its own updater nor download the compatibility database for games either. Forcing the user to have to go to the RPCS3 website to download any updates. OpenSSL _**is**_ installed on the home system.

## Details
Logs: https://files.catbox.moe/9sn4zo.gz

System specs: https://i.imgur.com/SxBEIaA.png

Proof that OpenSSL is installed on my system: https://i.imgur.com/ELRdq8l.png

**Comment by 13xforever** [comment]
You need openssl 1.0, not 1.1. Some distros provide compat package.

**Comment by Cervoxx** [comment]
1. My distro, Pop!_OS 19.10 is based on and pulls many packages from Ubuntu 19.10. At the time of writing 19.10 is the latest version of ubuntu, and then the next big Long Term Support release, 20.04, is coming out soon. 19.10 does not provide an outdated version of OpenSSL, and neither will 20.04 or any future release of ubuntu ever ship with OpenSSL 1.0. It's not going to be feasible to ask people to downgrade their OpenSSL package.
2. [Irregardless of this comment](https://github.com/RPCS3/rpcs3/issues/7239#issuecomment-573474653), the purpose of an appimage is to use the dependencies that come with the appimage, not the ones installed by the system. 
3. I also can't help but think that installing outdated versions of security software is a bad idea in general.

**Comment by MSuih** [comment]
We cannot bundle openssl with rpcs3 due to licensing issues, so it has to be installed separately. Windows users have the same issue as well, but they solve it by adding additional dll files to the executable folder.

**Comment by 13xforever** [comment]
openssl 1.0 is still supported; library versioning pertains to the API surface, and does not indicate support cycle

**Comment by Cervoxx** [comment]
> openssl 1.0 is still supported; library versioning pertains to the API surface, and does not indicate support cycle

Thank you for explaining this to me, this makes more sense now.



> We cannot bundle openssl with rpcs3 due to licensing issues, so it has to be installed separately. Windows users have the same issue as well, but they solve it by adding additional dll files to the executable folder.

The following two solutions come to my mind when I read this, either:

- Warn users on the RPCS3 quickstart page about this issue, and provide some sort of workaround like you did with windows users by telling them to download the OpenSSL runtime.
- Create some sort of new updating system for Linux users that works around this issue.

Pardon me if I'm not thinking realistically here.

**Comment by MSuih** [comment]
The windows situation isn't ideal either, we really should replace the ssl handling with f.ex. Mozillas NSS or some other solution with better licensing. But it's not easy to do as it would require replacing all Qt networking calls with something else.
