### ISSUE TITLE
The simplified Chinese language patched game can no longer enter the game

### ISSUE THREAD

**Issue by zombie167** [RPCS3/rpcs3#7576]
After the merge of the PR# overlays: Proper multi-language support https://github.com/RPCS3/rpcs3/pull/7551 ,the simplified Chinese language patched game can no longer enter the game.
I have tested several games with simplified Chinese language and the same happened.They freeze when creating an save or when loading a save.Those saves are usually displayed in simplified Chinese language.The last working build is 0.0.8 -9294.
When the emulator crashes, there will be such an error message

![test ](https://user-images.githubusercontent.com/22722505/75127618-0b9f7100-56fb-11ea-8c75-d3f965702486.jpg)

[log.zip](https://github.com/RPCS3/rpcs3/files/4243038/log.zip)

**Comment by kd-11** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/7580

**Comment by zombie167** [comment]
kd-11@Test with #7580


There is no problem now, no crashes have occurred.The text display is some messy code,it is not the correct simplified chinese character,only the text displayed in the red box is correct.Maybe it's not displayed in unicode
Thank you very much!

![sshot-2](https://user-images.githubusercontent.com/22722505/75185232-ac843f80-5780-11ea-8417-cab530a55bd8.jpg)
