### ISSUE TITLE
Sonic Unleashed: Tails has weirdly shaded gloves

### ISSUE THREAD

**Issue by Cervoxx** [RPCS3/rpcs3#7578]
## Quick summary
Tails from sonic unleashed has weird shaded gloves. These weird shading issues also persist in in-engine cutscenes.

## Details
- Real HW: https://youtu.be/74Q5w378tOs?t=2084
- Emulator visuals: https://i.imgur.com/YZD3xaB.jpg
- RSX capture: https://files.catbox.moe/ah9nyw.7z
- Renderdoc: https://files.catbox.moe/vz243f.7z
- Serial: BLUS30244
- Version: 1.02

**Comment by digitaldude555** [comment]
Duplicate of #7455

**Comment by Cervoxx** [comment]
Indeed it is, closing and moving my info over to that issue.
