### ISSUE TITLE
RPCS3 no longer loads - rpcs3.exe hangs until killed

### ISSUE THREAD

**Issue by laggerific** [RPCS3/rpcs3#7579]
## Quick summary
RPCS3 fails to load. The .exe hangs until killed from task manager. 

## Details
Ever since the QT library 12/6/19 update, RPCS3 fails to load with the following log entry:

RPCS3 v0.0.8-9697-1dc2eb1c Alpha | HEAD | Firmware version: 4.83
Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz | 12 Threads | 31.93 GiB RAM | TSC: Bad | AVX+ | TSX
Operating system: Windows, Major: 10, Minor: 0, Build: 18363, Service Pack: none, Compatibility mode: 0
·! 0:00:00.000000 RSX: Found vulkan-compatible GPU: 'GeForce GTX 1080 Ti' running on driver 442.19.0.0
·! 0:00:00.000030 RSX: Found vulkan-compatible GPU: 'GeForce GTX 1080 Ti' running on driver 442.19.0.0
·F 0:00:00.026943 SYS: 
Unhandled Win32 exception 0xC0000005.
Segfault reading location ffffffffffffffff at 00007ff8ba07ada6.
Thread id = 10264.
Instruction address: 00007ff8ba07ada6.
Function address: 00007ff8ba07ad80 (base+0x2ad80).
Module name: 'Qt5Core.dll'.
Module base: 00007ff8ba050000.
RPCS3 image base: 0000000000010000.

Rolling back to any version that uses older QT libraries works just fine.

Thank you!

**Comment by 13xforever** [comment]
Are you sure you're extracting _all_ the files from the new version? Also what happens if you delete `bearer` and `qt` folders before updating?

**Comment by laggerific** [comment]
Thank you for your response. I had been allowing RPCS3 to perform its own upgrades until this started happening. That said, yesterday I pulled the latest files and attempted to overwrite everything, but the issue persisted.

Per your suggestion, I deleted the `qt` and `bearer` folders and redeployed all the files from the latest RPCS3 build, and it worked!

Thank you!

**Comment by z0z0z** [comment]
Would just like to say this will probably be effecting more people. Just had someone in the discord with this same exact issue, fixed by removing the `bearer` folder (which is now inside `qt` instead of the root), and replacing the `qt` folder with new one.

**Comment by ahmmad88** [comment]
i have the same problem did you manage to fix it?
