### ISSUE TITLE
MOBILE SUIT GUNDAM SIDE STORIES [BLAS50710] game breaks after loading spu cache in spu block size giga mode

### ISSUE THREAD

**Issue by Shuneferus** [RPCS3/rpcs3#7585]
MOBILE SUIT GUNDAM SIDE STORIES [BLAS50710] game breaks after loading spu cache in spu block size giga mode

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4247141/RPCS3.log)

**Comment by AniLeo** [comment]
Mega and Giga are known to be broken, stick to Safe.
