### ISSUE TITLE
The overlay is brek

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#7588]
## Quick summary
- [ ] OSK crashes when closing the dialogs
- [ ] MsgDialog crashes when closing dialogs
- [ ] Savedata hangs when closing dialogs

## Details
![Screenshot_20200227-085924](https://user-images.githubusercontent.com/23019877/75423771-abe5d780-593f-11ea-8b1f-56b455e10663.png)

**Comment by Nekotekina** [comment]
Please retest with master.

**Comment by solarmystic** [comment]
Issue still happens with current master 0.0.8-9739

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4259993/RPCS3.log)
