### ISSUE TITLE
Drop and hang at vulkan render (Idolm@ster OFA)

### ISSUE THREAD

**Issue by rikimtasu** [RPCS3/rpcs3#7591]
## Quick summary
Emulator doesn't work correctly on vulkan,and opengl have wrong effect when view in near camera angle.

## Details

Full log attached here:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4249513/RPCS3.log.gz)

- screenshots, Renderdoc, and RSX captures (for visual issues)
![rpcs3_GBDUJZUQn7](https://user-images.githubusercontent.com/1460843/75239853-5ce45900-57fe-11ea-8064-1a733ca89213.png)
![rpcs3_HcexeHe8I6](https://user-images.githubusercontent.com/1460843/75239862-5fdf4980-57fe-11ea-929c-e62da680b730.png)

Windows 10 1909
AMD Ryzen 5 2600 16 GB DDR4 RAM
GPU: GeForce GTX 1660 SUPER ( Driver version:442.37)

**Comment by Cervoxx** [comment]
I'm confused, is the emulator crashing or simply displaying things wrong?

**Comment by rikimtasu** [comment]
> I'm confused, is the emulator crashing or simply displaying things wrong?

It just hang at 2 fps.
The display wrong one was opengl only

**Comment by kd-11** [comment]
We can use this ticket to track the crashing issue and https://github.com/RPCS3/rpcs3/issues/5890 for the visual glitches. That being said - does it still crash on latest builds?

**Comment by kd-11** [comment]
Cannot reproduce in latest builds.
