### ISSUE TITLE
Regression: The Last of Us [BCES01584] only the text appears no image is rendered

### ISSUE THREAD

**Issue by ESRDEV** [RPCS3/rpcs3#7593]
An possible regression in TLOU, I tested the game a few months ago and it opened and worked with some graphic bugs but it was possible see something from the game but now months later I can only see the text and hear the characters voices. what I said before occurs if I'm lucky but often when starting the game the error Access Memory Violation appears.

RPCS3 Emulator updated to last build, NVIDIA drivers and Windows 10.

RPCS3 v0.0.8-9710-136d7698 Alpha | HEAD | Firmware version: 4.85
Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz | 16 Threads | 7.91 GiB RAM | TSC: Bad | AVX+
OS: Windows 10 Build: 18363
GPU: GeForce GTX 1080 Ti Drivers: 442.19

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4250702/RPCS3.log.gz)

**Comment by Andryshik345** [comment]
Try to enable Read Color Buffer and Read Depth Buffer and boot again.

**Comment by MsDarkLow** [comment]
Yes. And you call this a regression despite the fact that you obviously didn't even research if you had the settings right or pin point the regression build.
![3](https://user-images.githubusercontent.com/9060436/75263288-ad9b8800-57e5-11ea-986e-a707505bf946.jpg)
![4](https://user-images.githubusercontent.com/9060436/75263396-d28ffb00-57e5-11ea-80d7-34cc95904309.jpg)

**Comment by ESRDEV** [comment]
> Yes. And you call this a regression despite the fact that you obviously didn't even research if you had the settings right or pin point the regression build.

I searched the official forum and found nothing related, the fact that the game ran before without these "CONFIGURATIONS" that you mention already shows that you don't hear the emulator's progress with this game.

I almost forgot that the fact that every 10 times I try to start the game it 9 the error Access Memory Violation really is is irrelevante right ? sorry lord developer for my stupidity.

**Comment by ESRDEV** [comment]
> Try to enable Read Color Buffer and Read Depth Buffer and boot again.

Thanks for the tip.
