### ISSUE TITLE
Soul calibur V BLUS30736 freeze at start

### ISSUE THREAD

**Issue by Atrosincity** [RPCS3/rpcs3#7598]
E {PPU[0x1000014] Thread (any_workerThread_2) [0x01651ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30736/USRDIR/DLC29/index_29_PS3.edat” [1]

**Comment by RainbowCookie32** [comment]
We have templates for opening issues, showing what's needed to open a proper issue. But this still happens...

You are missing a log from the issue, and system specs.
