### ISSUE TITLE
Emulator crashes if encrypted trophies are copied from a ps3

### ISSUE THREAD

**Issue by Masamune3210** [RPCS3/rpcs3#7599]
## Quick summary
If a user copies the trophy folder or any of its contents to the emulated home folder for rpcs3, the emulator will crash while trying to parse the trophy information in the Trophy Viewer

## Details
Please provide as much detail as you can here, including
- Expected - Error message or silent failure, Got Hard Crash
![image](https://user-images.githubusercontent.com/1053504/75308886-29f98f80-5815-11ea-933b-45b5e10136ba.png)

- Ryzen 7 2700X, Radeon 5700XT

Possibly add a guide to transfer trophies from an actual ps3 if possible?

**Comment by deadair3210** [comment]
Log = https://gist.github.com/deadair3210/f2d5284e1e72c7b187eb6ce64fda333b

Forgot to attach to issue, sorry

**Comment by elad335** [comment]
Thanks, also uploae the trophy files.
Can the game which these trophies belong to boot and show `sceNpTrophyRegisterContext` in log?

**Comment by deadair3210** [comment]
I will try tomorrow morning, do I just need to try to boot the game with the encrypted trophies in the folder? Or do I need to do something different. The trophies are just the trophy folder that I copied from my PS3 HDD after syncing them from psn

**Comment by elad335** [comment]
Yes, booting the game with the encrypted trophy files, until `sceNpTrophyRegisterContext` is shown in the log.

**Comment by deadair3210** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4259357/RPCS3.log)
Here is the log from crazy taxy
[NPWR01440_00.zip](https://github.com/RPCS3/rpcs3/files/4259364/NPWR01440_00.zip)
And here is the trophy folder

**Comment by Megamouse** [comment]
@Masamune3210  please try again

**Comment by Masamune3210** [comment]
Seems to work fine, shows up in the trophy viewer! Game boots up and everything! Thanks!
