### ISSUE TITLE
White screen 0 FPS when booting up Persona 5

### ISSUE THREAD

**Issue by Cosmic-Gary** [RPCS3/rpcs3#7600]
I am unsure of how to fix this, does anyone have a solution
![image](https://user-images.githubusercontent.com/61487890/75312404-a472e100-580e-11ea-98db-bcd81dd9ac12.png)

LOG:
S GUI: Boot successful.
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-guxwrxyQg8Q12tfErNZ629-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-4FCMJM7KTTvrS04fz5drCk-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-pAWwyfxjSzCnQ1uv7Ke5Qa-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-LooHyXeFkgTEof0rm5TY1g-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-NdSUXRQmfK5GTpLgx3LVaq-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Xihbw7FZpEFPRWbunGxbFV-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Ki65gFsW6eAPAeXEQvQX1V-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-XKRxSUYPCJnRtu1i9T1x45-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-jzsAPdHiEdjftpW0qU8X70-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-dSYfadka6wQpghGfs8iY7L-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-jgjaANAdNM0hwTPFTEvUKC-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-k4knCzHtCC5buCC4yNpz3q-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-MP2fYdvzFjKrgf6b6a3ZEU-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-2ohPs5ytcWaAYX8MPQduaG-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Xgtu2n4w2TzAL2uF3uTp85-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ffpXwoLyvf2YJGsf6nJmec-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ovPQnwG1kCyF7QiwCTxAtx-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-GZZhvsAAsYx2FU7GkubaaN-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-haQvXENAKo5XESvmYvCkSV-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-pPkJzf9WjNqTzcfAE5xpYG-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-R7c8xw2fPEmUgEHQAZ2yAS-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-aVzELZ5QnK735xmQ15gCV9-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ckMdo0JfpnHKF2AmTT86fX-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-h4jYNp3tAjGQpSMHoZKF0X-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-q3zatz6Uzoko9Qpwy5b8vk-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Q6YFtoq7Jn2ezVYAkG5eLL-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-3LU0NF0eqHrWKh0VmYbQTp-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-pJbPbsbccHqrqa60zoCRy2-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Nazm91xkhVeXbPtKsazm9Z-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-JwkSSnmfpXZiGUP3AniTdH-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-afga5ofeNMnj3owJA2ac4h-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-NKkJY8kSXHkikhfY27SXMy-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-cX49m1qUZvHJJphm9q9Tv3-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-PXmepkepM3ECZexXNWKwVU-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-WQjCAjg40FpYoKScbJAELG-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-naAA0bePSYeAvy38jULGwt-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-XMyMmaGwJSmCGmNS9gJvJV-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-EYx72aGdb8EL615Qy5iX4M-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-AHYxa4ksWcPfTcbjZjVRWb-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-2j7a5mni1moJcF021ywq6W-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ZyRu87na7wbrebyo0KdRrk-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-g8TfjqYTAZfSCAwTtJ7h2W-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ZVUjAVLM73MXpSQA0MvzaT-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-SRPt4UVKVPhmFda1rEoUKd-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-R7MupTF93r4GAXva2yNmhz-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-X9isTpKVXU6YPhsuy7ndHH-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-QsXPXPydyHgCFGPCJe8pLr-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ZadTtXUZEmepZiecFNcMLV-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-fCWTMvi3RLUJxL6PfE59Y1-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-4ZpM2zFLVowHs0pNYqWZu6-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-f9cEV0gG1knYQvP2uHStF3-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-iwsxV8EV1NooYAQxcct6h3-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-0NW7A2m374324ubjvjksXF-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-0utbhkNU9jKkwHmXRzL9en-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ecr3Cxy1SqZd6y7EoYrtQ4-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Jw3jZwc9psJ947dFQAwdpe-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-4cYRA3SUy3gR7qFFW4TH4e-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-q3iKEf2N2gzFKTs4xrrtah-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ZKg22hjQqcMXcotxTZKRdg-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-TeTf9MErbQq1kCVSupfZ7Q-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-cWWKmkwQw8fFpauQQmWMns-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-cCqqQYcjX9FFnjM0PvEJfb-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-QL4Fh4QuZy18raPt3K7RSj-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Y3ASaE4mEcdHYwtZG2pXLS-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-oHmE0zGgn6t6nNRYRhr9UE-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-PZNYbfYormQHWt4oM9M37Z-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-N6YgivH4wTsgw7ruVPswWa-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-tgN8SqeNTQRoNAdKZqLYrU-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-5Qiywx87XXUX4kWKNm6vra-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-GV8bfYVq6t2ibEPzXXFajb-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ijyW2mfHKL45Xd28uZSjzh-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-fR4TGr48VwHsRsNFp7ivve-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-eWLECqKSpzTdda0h529kTj-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-6b6Pq35pu48FdGNuUShQKh-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-pUwymPsSsjmqEonjQWCGqn-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-CAgKktuCN2wF6ARo0T77PF-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-RMN7N5KVgkAjAaMmdLjvzP-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-pTrZpamFd81JJTh4KxsM0q-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-tQMnzY6SpYs7mXu84VcThn-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-VnXujbxVy4RLANrMT4e2Ey-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-oPYnVVu5t8UHEdkotMepYa-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-W06188ChEdaGhfhpkYdZEV-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-dcmq0b6SVWUf6GT8wHZUQA-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-jVxL6EJ0Zag8Vs3qgrGNsi-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-kgC5K7LXWHmP7GnGjo0wEQ-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-rgVbc9fkZV8U6RhjLvY8qg-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-aV31yNs92WxrA5fgNF9gTi-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ThrkFX22onwS4SwUewLQUt-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-23UXMKfdaSXLh7Qhob0a4h-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-HoVvSz5NroSAL5b1MnCaw5-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-awy8hJizQtzfRbaS6Rr6jN-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-c49XWPg1CQjGr7vkeGvP0i-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-696nTzW5TY6WczXA2LLiA2-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-3AUv2W9WPQzQzwWwRuncAx-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-bM2bsc2Vjt73CEMUH52yke-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-YcwAUxuiAPygnwn9hS9gGy-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-p7bH9m2cLd5LNwtjwgAHS3-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-0cbmxU4C0ZFVwtTvys3JR3-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-gP71Vx1NfuqkUTUiVsFG2e-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-A373bGv14h1TkYgSEs5kwg-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Wo0Ku1q10kTKqv2PTwSYsa-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-JPrzFfZNnA0qvkYs086Lx1-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-hJJ9sT3M7cEkdVmjF0uU1L-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-b0yR4PnU7C8SmPZ00zdzMQ-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-sx7caEGW0ni5F0NzyzhpHU-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-VTH3zoitbtij8yjefXJKd8-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-PLMFtaCjqdRsjG123E6mod-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-94bANtcz9A1amAYSb2EtHq-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-TN5W3F9qKNfNxtEQy9TXbQ-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-1wFzxmCQbMo7VHfahzTzCv-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-WbWqW0FMHMZGLs3U3CvaWA-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-2HCJo52SVWvrCjzWPMnHxV-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-kKsT5e0sZ7bovxt2rchjXK-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-2heCyskynP288ydd0b8mc8-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-gphfug57pEXP0fNLU9TACA-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-KCXPzQvyKS0TkKaAdvtP8r-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built the interpreter.
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built 59 functions.
U {PPU[0x1000000] Thread (main_thread) [0x0146fe64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x014700bc]} sys_prx TODO: _sys_prx_register_library(library=*0x14726a0)
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v3-tane-1z3Pyu8YVnnorJiQ2hfu1e-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x014b3d8c]} sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0010a50)
E {PPU[0x1000000] Thread (main_thread) [0x014b3d8c]} SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U {PPU[0x1000000] Thread (main_thread) [0x014b3d24]} sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0010a50, a3=0x0)
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} PPU: LLVM: Loaded module v3-tane-XCgQWMc1s99n1WTwrpWvw4-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} PPU: LLVM: Loaded module v3-tane-TP3c8YsdNggjaG5WRjcboe-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} PPU: LLVM: Loaded module v3-tane-LWAKW9c35vXJad6uHkwzhK-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} PPU: LLVM: Loaded module v3-tane-fLV79QqHgPi90UziTsWrHo-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0147061c]} sys_prx TODO: _sys_prx_register_module()
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v3-tane-GidnR56pzgun0Z5aqipN0L-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libusbd.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v3-tane-WoisQeLxhd27z3jTVxPE2F-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libfiber.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v3-tane-AdfFkwpv688RAZ5NkstSem-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libspurs_jq.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v3-tane-Ak6wUfy1tdbeNwGYnYRQR6-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libfont.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v3-tane-prcigdp3hSacKnE2ATTKR0-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v3-tane-XdfninF20TfAZVs040wd0d-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v3-tane-NMvxa7gGobm3hdVuA1MMP7-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v3-tane-CxZ8Nhfz8VQ9URuwAeUqfZ-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libfreetype.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v3-tane-sTYR53o5j258q9f8foaTQg-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libfontFT.sprx
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} PPU: LLVM: Loaded module v3-tane-jJoZ07PrzerYWWhZciLzhv-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0146ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0146ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000000] Thread (main_thread) [0x0146ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0146ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/fade_top.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/fade_top.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/fade_bottom.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/fade_bottom.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/select.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/select.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/start.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/start.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/cross.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/cross.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/circle.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/circle.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/triangle.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/triangle.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/square.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/square.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/L1.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/L1.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/R1.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/R1.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/L2.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/L2.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/R2.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/R2.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/save.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/save.png' not found
E {RSX [0x0000000]} RSX: Image resource file `C:/Users//AppData/Local/Temp/Rar$EXa12492.20137/Icons/ui/new.png' not found
E {RSX [0x0000000]} RSX: Image resource file `Icons/ui/new.png' not found
F {RSX [0x0000000]} RSX: class std::runtime_error thrown: Unhandled GL format 0x8058
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\GL\GLHelpers.h:1703)
E {PPU[0x1000001] Thread (_fs_aio_thread) [0x0153f17c]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000002] Thread (gfdSpursSpursHdlr1) [0x014fb604]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000003] Thread (gfdSpursSpursHdlr0) [0x014f948c]} SYS: 'sys_spu_thread_group_join' failed with 0x00000000 : 0 [1]
E {PPU[0x1000005] Thread (gfdJobQueueFiberWorker) [0x008f5544]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000006] Thread (gfdJobQueueFiberWorker) [0x008f5544]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000007] Thread (_gcm_intr_thread) [0x014d833c]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000004] Thread (gfdJobQueueFiberWorker) [0x008f5544]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]

**Comment by Cosmic-Gary** [comment]
Please leave helpful comments

**Comment by RainbowCookie32** [comment]
Should start by a helpful issue and attaching a proper log, not copy pasting it from RPCS3's window. Run the game, get to the crash, then close RPCS3, go to its folder and upload RPCS3.log here

**Comment by money123451** [comment]
dying rn thanks for the issue.

**Comment by AniLeo** [comment]
Not even with the new templates with buttons for different things...
