### ISSUE TITLE
NHL 12 Freezing error

### ISSUE THREAD

**Issue by MakiSalonga** [RPCS3/rpcs3#7601]
I found this while trying to boot up NHL 12

F {RSX [0x01d8e1c]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:352)

My specs:
Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz | 4 Threads | 3.90 GiB RAM | TSC: Bad | AVX+

**Comment by AniLeo** [comment]
Does not follow guidelines, adding need information tag

**Comment by sampletext32** [comment]
Log file is necessary for applying an issue.
