### ISSUE TITLE
NHL 12 Freezing error (Take 2)

### ISSUE THREAD

**Issue by MakiSalonga** [RPCS3/rpcs3#7602]
Let's try this again:

I encountered this error while booting up NHL 12:
F {RSX [0x02c4480]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:352)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4256319/RPCS3.log)

My specs:
RPCS3 v0.0.8-9724-df1813b4 Alpha | HEAD | Firmware version: 4.85
Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz | 4 Threads | 3.90 GiB RAM | TSC: Bad | AVX+

**Comment by AniLeo** [comment]
Don't duplicate issues next time

This one looks like it's caused due to your specs, integrated graphics and only 4G RAM.

Asking for @kd-11 to triage whether it's a wontfix or not.

**Comment by MakiSalonga** [comment]
Integrated graphics?

**Comment by AniLeo** [comment]
I'm reading off your specs which don't mention any specific GPU other than the integrated 7200U, I can't open the log file as I'm on metered LTE at the moment

**Comment by Kravickas** [comment]
GPU: GeForce 940MX (441.66) 4GB VRAM

NHL isnt eating that much VRAM + he is at 100% scale

**Comment by AniLeo** [comment]
Ok, should be an actual bug, needs checking

**Comment by AniLeo** [comment]
Ok, should be an actual bug, needs checking

**Comment by nitroos-ai** [comment]
Is it fixed now?

**Comment by kd-11** [comment]
This should already be fixed. We've had multiple changes to the VRAM load balancer since then.
The OP can request to reopen if not.
