### ISSUE TITLE
[Regression] MLB the Show 10-16 broken textures with Vulkan after PR #5860, might only affect Turing cards

### ISSUE THREAD

**Issue by connorwalks** [RPCS3/rpcs3#7606]
## Quick summary
Prior to #5860, jerseys and equipment displayed fine in MLB the Show games 10-16 with Vulkan. Since that PR, there are broken textures all over jerseys. Only happens with Vulkan, the textures are fine with OpenGL even after #5860

## Details
I know this is a very old build that caused this regression, but this is still an issue on the current master. It appears to only affect Turing cards. I have had a few discussions with other discord users with Pascal GPUs and learned that they don't have this issue. Regardless I think it's worth looking into. Here are logs, RSX captures and screenshots from MLB 15 the Show [BCUS00236] as an example.

**Working build:**
[LOG 0.0.6-8021.gz](https://github.com/RPCS3/rpcs3/files/4257531/0.0.6-8021.gz)
[RSX CAPTURE 0.0.6-8021](http://www.mediafire.com/file/hn343ssnrlphary/BCUS00236_20200226133458_capture.rrc/file)

![image](https://user-images.githubusercontent.com/48158481/75375673-8d7ad000-589c-11ea-8109-2cd385b04410.png)

**Broken build:**
[LOG 0.0.6-8033.gz](https://github.com/RPCS3/rpcs3/files/4257597/LOG.0.0.6-8033.gz)
[RSX CAPTURE 0.0.6-8033](http://www.mediafire.com/file/lwg7z2l5zgh4ikw/BCUS00236_20200226134752_capture.rrc/file)

![image](https://user-images.githubusercontent.com/48158481/75376728-8359d100-589e-11ea-8ce4-8c56319ad407.png)

If needed I can provide a log and RSX capture from latest master as well. Let me know if any further information is needed.

**Comment by jacob1218** [comment]
![image](https://user-images.githubusercontent.com/6559034/75390482-2c9fc780-589d-11ea-9dea-536670a757df.png)
https://cdn.discordapp.com/attachments/272035812277878785/682341871535521860/NPUA80969_20200226133942_capture.rrc.gz

This issue doesn't sem to affect Pascal series gpus, the one i have is a 1050ti and graphics look normal (at least for rpcs3)

**Comment by kd-11** [comment]
Go into the config file and disable native fp16. Pretty sure it's just a difference in NVIDIA's fp16 implementation vs the one on PS3.

**Comment by connorwalks** [comment]
> 
> 
> Go into the config file and disable native fp16. Pretty sure it's just a difference in NVIDIA's fp16 implementation vs the one on PS3.

Yup that seems to do the trick:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4271051/RPCS3.log.gz)

![image](https://user-images.githubusercontent.com/48158481/75615845-316fb000-5b17-11ea-813f-609a682e5193.png)

Would this be something that should be disabled on all games for someone with a Turing card?

**Comment by kd-11** [comment]
No, it should work fine for most games.

**Comment by rbpaiett** [comment]
It doesn't work anymore because native fp16 doesn't exist in any form in the latest RPCS3.
