### ISSUE TITLE
FarCry Classic: No longer ingame

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#7607]
FarCry Classic [NPUB30737] no longer goes ingame, or even to the first menu.  The game is stuck on the screen that indicates "This game saves data automatically at certain points" i.e. pushing "X"  does nothing.  Attemps to remove all data (all caches, save game data, trophies) do not help.

Tested on rpcs3 commit 569e1c2df68f354f8dc2b9e2770bcf615f5458da.  Note this tested successfull on commit 2bab3afae00bef5bc28ae0ebc6b3669057b7f94a made just a few days earlier.

Note that FarCry has other issues such as #5968 though it seems unlikely to be related.

Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4258046/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
Likely a duplicate of #7588. Check if you can progress by disabling Native User Interface

**Comment by AniLeo** [comment]
Very likely a duplicate yes

**Comment by Shoegzer** [comment]
Ah yes, thanks.  Tested with NUI disabled and it works.  Closing.
