### ISSUE TITLE
Some games freeze when closing or stopping

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#7616]
## Quick summary
Closing some games completely freezes the emulator.
~~Possibly Vulkan only.~~ Edit: Also on openGl

## Details
100% reproducable in 0.0.13-11313
- SONIC THE HEDGEHOG [BLES00028]
- Call of Duty 3 [BLES00021]

Also possible in:
- Blazing Angels 2: Secret Missions of WWII [BLUS30052]
- Mercury Hg (Trial) [NPEB00473]

**Comment by money123451** [comment]
did you try without RSX multithreading ? as that seems to be the cause for my crashing right now might be related to https://github.com/RPCS3/rpcs3/issues/7613

**Comment by Nerboruto** [comment]
it happened to me several times with rsx multythreading off...
as soon as it happens again I see to post the log. however the emulator freezes and must be closed manually by the taskmanager after pressing stop.

**Comment by Nekotekina** [comment]
Does it still happen?

**Comment by Cervoxx** [comment]
Unsure if fixed yet (Haven't tested myself) however #7574 is related to this.

**Comment by Cervoxx** [comment]
Still occurs, tried closing the emulator while the game was running by doing File > Exit. Entire emulator locked up. Logs: https://files.catbox.moe/7jobaa.gz

**Comment by jeremybris** [comment]
Was this fixed by [#9773](https://github.com/RPCS3/rpcs3/pull/9773) ? I don't get this in Call of Duty 3.

**Comment by Nerboruto** [comment]
it seems much more stable it hasn't happened to me anymore...

**Comment by MSuih** [comment]
Might be because of PR's like #9773 and #9813. I'll let Mega decide when he wants to close the issue.

**Comment by Megamouse** [comment]
I'll close this, since I haven't really had that many issues with it lately

**Comment by dio-gh** [comment]
That's funny, I don't think anything fixed it, not so long ago I got it pretty often all the same. Not like it's worth tracking, it's a complete meme to repro.
