### ISSUE TITLE
Blackscreen on Launch Persona 5

### ISSUE THREAD

**Issue by Cosmic-Gary** [RPCS3/rpcs3#7619]
Launching Persona 5 I get a black screen but the fps is showing
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4265117/RPCS3.log)
![image](https://user-images.githubusercontent.com/61487890/75507551-45d86f00-5996-11ea-8f5b-ba4957eb934d.png)
Specs:
16.0GB RAM
Intel Core i7-7700 CPU
3.60 GHz
OS: Win 10
64 bit

**Comment by Cosmic-Gary** [comment]
Config Menu
CPU
![image](https://user-images.githubusercontent.com/61487890/75507759-d44cf080-5996-11ea-9bc8-24e8f7f13caa.png)
GPU
![image](https://user-images.githubusercontent.com/61487890/75507775-e75fc080-5996-11ea-8f13-5d8ca4da6a86.png)
Audio
![image](https://user-images.githubusercontent.com/61487890/75507792-f21a5580-5996-11ea-8794-47851cca643d.png)
Advanced
![image](https://user-images.githubusercontent.com/61487890/75507819-04948f00-5997-11ea-9b5c-2a5482d991a2.png)
Emulator
![image](https://user-images.githubusercontent.com/61487890/75507837-0fe7ba80-5997-11ea-9f20-d75fa63faa50.png)

**Comment by solarmystic** [comment]
From the log you provided, it seems you're using a very old build of rpcs3.

Try grabbing the latest build from https://rpcs3.net/download and try again.

Also, use Vulkan instead of OpenGL.

**Comment by Cosmic-Gary** [comment]
how do I use vulkan its not an option for me

**Comment by solarmystic** [comment]
> 
> 
> how do I use vulkan its not an option for me

Update/do a clean reinstall of your NVIDIA drivers, that should fix it.

**Comment by RainbowCookie32** [comment]
Really looks like a support case for discord rather than an actual issue

**Comment by RainbowCookie32** [comment]
And I can't reproduce on my end. Likely a broken dump.

Sorry for the extra message, can't edit on the GitHub app for some reason :D

**Comment by AniLeo** [comment]
GitHub is not the place to ask for support, read the issue templates
