### ISSUE TITLE
[Regression] Yakuza 5 fails to reach main menu

### ISSUE THREAD

**Issue by MsDarkLow** [RPCS3/rpcs3#7629]
##  Quick summary
Yakuza 5 fails to load the main menu since the merge of #7582, therefore can't get ingame anymore.

## Details
Not much of note here, its a straightfoward crash regression.
The game freezes in the main menu and the log shows the following Fatal Error
`F {RSX [0x03afaf4]} RSX: class std::runtime_error thrown: Allocation failed!`

Last working build: v0.0.8-9724-df1813b4
Regression build: v0.0.8-9726-569e1c2d (#7582)

Log from working build: [RPCS3 9724.log.gz](https://github.com/RPCS3/rpcs3/files/4268910/RPCS3.9724.log.gz)
Log from regressed build: [RPCS3 PR 7582.log.gz](https://github.com/RPCS3/rpcs3/files/4268912/RPCS3.PR.7582.log.gz)

**Comment by solarmystic** [comment]
Seems a lot similar to this latest development in Diablo 3 which i noted in its own megathread:-
https://github.com/RPCS3/rpcs3/issues/5593#issuecomment-592604012
