### ISSUE TITLE
Alien Isolation: Crash on boot

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#7630]
As of commit cb047fcc7596d5b83f2773d969b57cc34ff5a7be, Alien Isolation crashes on boot with the following message:

![Screenshot from 2020-02-29 00-36-50](https://user-images.githubusercontent.com/12475371/75601702-a1e5e500-5ab5-11ea-8db7-d5126bb2130a.png)

This is a recent regression as it was not happening just a few commits prior to this.

Tested with Linux Mint 19.3 kernel 5.3 self-compiled with gcc 9.2.1

Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4269968/RPCS3.log.gz)

**Comment by elad335** [comment]
Test #7628

**Comment by Shoegzer** [comment]
Thanks @elad335.  Re-tested with cb252b1ce2336c3cc77f445247c9048f8162cfcf but that didn't fix the issue.

Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4270594/RPCS3.log.gz)

**Comment by elad335** [comment]
Test with #7647

**Comment by Shoegzer** [comment]
Thanks again @elad335.  Re-tested with fbe6900b287423da98ae07278f9614734e151d67 but as before, it's still broken.

**Comment by elad335** [comment]
I can't reproduce, can you upload its savedata?

**Comment by Shoegzer** [comment]
You got it.  

[Alien Isolation Savedata.zip](https://github.com/RPCS3/rpcs3/files/4271385/Alien.Isolation.Savedata.zip)

**Comment by Shoegzer** [comment]
@elad335 I just tried deleting all 22 Alien Isolation savedata folders (per the above attached) and starting the game again without them.  Sure enough, the game booted just fine.  I then deleted the new savedata folders it had just created, and added back my original folders once again.  Strangely enough, this time the game started without the error above.  I'm trying to understand why though - apparently there are other save-related files/folders created somewhere that permitted this to happen?

I hope that helps.  I'm fine closing this issue if you are, but it would be nice to know why my process above fixed the issue in case you know.

**Comment by Shoegzer** [comment]
@elad335 Sorry, spoke too soon.  For some reason the problem started happening again even after I deleted/re-created/moved back my save directories.  Not sure what's wrong, but I don't think we should close this just yet.

**Comment by elad335** [comment]
If you specify a specific pull request which broke it will help.
Currently it just sounds like savedata corruption or something, I couldn't reproduce locally even with the given savedata.

**Comment by Shoegzer** [comment]
@elad335 This one will be tricky to track down the specific commit beyond what I mentioned above as it seems to be happening sporadically.  As an update, I did observe that when I move the savedata outside the rpcs3 directory, then start a game to let rpcs3 write it back, then *overwrite* (rather than replace) the new savedata with the original data, it works (even though I have no idea why).  Hope that made sense.  In any event I can close this if you don't feel it's an issue; I'm not even convinced this isn't something on my end at this point.

**Comment by Shoegzer** [comment]
Closing this issue as it doesn't appear to be happening on more recent builds.
