### ISSUE TITLE
Ratchet & Clank Trilogy regression: Freeze at game selection

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#7633]
Ratchet & Clank Trilogy starts up with a game selection which allows you to pick from one of the 3 games. Once a game is selected, it calls `_sys_process_exit2` to close the current executable and launches a .self file to start up the selected game.

This used to work fine but has recently regressed. Now the emulator doesn't end the first process automatically, only proceeding normally after user manually closes window for the game selection menu. With `git bisect` I narrowed down the issue to commit b59bb16fad0f7f253017eb7de1579cc54fa13510. When looking at with debugger, the main thread is paused in `sys_timer_destroy`.

This most likely affects other multi-game discs with similar game selector.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4270106/RPCS3.log.gz)

**Comment by Sgtbomber91** [comment]
same a #7613

**Comment by MSuih** [comment]
That issue is about multithreaded RSX, this happens even with it disabled.

**Comment by elad335** [comment]
Fixed by #7628

**Comment by MSuih** [comment]
Can confirm, the issue has been fixed
