### ISSUE TITLE
Last Of Us [BCES01585] Multiple Visual Artifacts

### ISSUE THREAD

**Issue by sampletext32** [RPCS3/rpcs3#7641]
I've recently decided to test run first couple of minutes in TLOU and discovered some visual bugs, which were meant fixed sometime ago, or occure in special cases.
Here is the video on Youtube.
Sorry for sound craziness, it's just my "slow" CPU.
May contain spoilers.
https://youtu.be/1ELrg0OlInM

1) 01:46 - Right before Joel's death we can clearly see Sarah disappearence and then T-Pose characters, which is not a desired game behaviour.
![image](https://user-images.githubusercontent.com/44116740/75611155-f2e2f100-5b28-11ea-96e4-6fabbe1ed84b.png)
2) 02:13 - Exactly the same problem. Sarah disappearence and then T-Pose.
![image](https://user-images.githubusercontent.com/44116740/75611163-042bfd80-5b29-11ea-9edb-5ce3c3806cbb.png)
3) 02:19 - Some weird shadows on screen disappering in a few seconds.
4) 03:12-03:36 - Extremely chunky Joel. Very blurry image, which is not supposed to be.
5) 05:26 and further - Black objects getting textured after some time, I think due to shader compilation. Might be non emulator problem, or emulator specific problem, not a game.
6) 06:46 - Weird blackscreen frame.
7) 07:05 - Weird background scyscrapers black area.
8) 07:17 and further - appearing military car cast weird flickering shadows.
9) 07:57 - exact same flickering shadow casted by a truck.
10) 08:06 - green explosion
![image](https://user-images.githubusercontent.com/44116740/75611065-15c0d580-5b28-11ea-88ca-3cf6850efa9f.png)
11) 08:20 - flickering shadow
12) 08:30 - abovementioned military car casts shadows, which displays over closer objects.
![image](https://user-images.githubusercontent.com/44116740/75611099-7c45f380-5b28-11ea-9b21-d90a19248225.png)
13) 08:40 - closer look at shadows. Looks like they are drawn over the same place, because camera movement immediately resets effect, which then accumulates again.
14) 09:08 - green dots on screen, which were considered corrected.
![image](https://user-images.githubusercontent.com/44116740/75611193-5ec55980-5b29-11ea-9e27-d506a2ddbefd.png)
15) 10:25 - weird all screen white lines.
![image](https://user-images.githubusercontent.com/44116740/75611213-89afad80-5b29-11ea-8689-1def7aa23b1a.png)
16) 12:24 - some movement craziness. Repeated frames or something.
17) Finally 14:30 - game freeze, which is a known issue.

PC Specs.
Intel Core I7 9750H
RTX 2060
16 Gb 2667 Mhz

Latest build

Log here.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4270570/RPCS3.log.gz)

**Comment by kd-11** [comment]
The first 2 are how the game works, you can find footage of people with hacked eboots running on hardware and that's how the engine has the cutscenes scripted. It's just in your face here because performance is so bad.

**Comment by sampletext32** [comment]
I will have to do a retest for all of these and probable make a checkbox version.
Closing as inconvenient.
