### ISSUE TITLE
RPCS3 does not compile with GCC-10

### ISSUE THREAD

**Issue by hedmo** [RPCS3/rpcs3#7642]
## Quick summary
hi. As all know gcc-10 is coming and i am on the road with gcc-10.To day i updated rpcs3 and it failed.It compiles fine with gcc-9 so the problem is with changes in gcc-10.as i have seen you are running rpcs3 with the pre Release of llvm-10 and think you are interested in add support for gcc-10 to.i will be happy to provide any info/help to move rpcs3 forward.i am running on gentoo and have a own ebuild for it so this is the only place for me to get support/help 
  

## Details
build log:

[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/4270568/rpcs3.zip)

best regards hedmo

**Comment by AniLeo** [comment]
I think this is a gcc-10 problem, not RPCS3 itself
It doesn't even have a release, it will be updated to when it has one

**Comment by hedmo** [comment]
i dont know if it is a gcc problem or rpcs3 but :

`warning: ‘template<class _Tp> struct std::is_pod’ is deprecated: use is_standard_layout && is_trivial instead [-Wdeprecated-declarations]`

this warning give me the info that rpcs3 needs to have some info about it and maybe needs to 
fix it in the now/future .regards gcc...it is going to be released soon "in March or April" and gentoo,fedora and debian has rolled it in to the unstable branches all ready .

**Comment by Nekotekina** [comment]
Feel free to reopen if other errors appear.

**Comment by hedmo** [comment]
@Nekotekina thanks. It compiled but not with llvm .
[build.log](https://github.com/RPCS3/rpcs3/files/4270849/build.log)
