### ISSUE TITLE
Sly Cooper Thieves In Time [NPEA00429] - Multiple stability issues

### ISSUE THREAD

**Issue by fearcraftor** [RPCS3/rpcs3#7648]
## Quick summary
Game freeze at some point then crash 

## Details
- Emulator started to loop with this issue :
`{RSX [0x0c015f0]} RSX: FIFO: CALL found inside a subroutine (last cmd = 0x11dac82)`
- Then Crashed with this message :
![image](https://user-images.githubusercontent.com/9964341/75615978-0737e580-5b4b-11ea-97ea-217fcea88b47.png)

- your system configuration (OS, CPU, GPU, driver versions, etc)
OS: Windows 10 1909
CPU: Intel Core i5-4440 CPU @ 3.10GHz
GPU: GTX 660 (v 432.00)
RAM: 8Go

- logs:
[rpcs3-v0.0.8-9665-171e6c6e_win64.zip](https://github.com/RPCS3/rpcs3/files/4271069/rpcs3-v0.0.8-9665-171e6c6e_win64.zip)

Hope this will help you :)

**Comment by kd-11** [comment]
This is the result if a desync, increase your wake delay to somthing like 200 or 500 and retry.

**Comment by fearcraftor** [comment]
I change the title of this issue as I encounter many more stability issues on Sly Cooper game

- Things OK 

1. Almost playable framerate
2. Graphics seems globally OK

- Things Going wrong

1. Audio very buggy
2. Sometimes game fail to reach Main menu at this point (note that this error append also when game boot well)
```
E {PPU[0x1000000] Thread (main_thread) [0x01200fa8]} SYS: 'cellAudioInit' failed with 0x80310701 : CELL_AUDIO_ERROR_ALREADY_INIT [1]
U {PPU[0x1000018] Thread (Discover AR Server) [0x01200a18]} cellNetCtl TODO: cellNetCtlGetInfo(code=0x10 (INFO_IP_ADDRESS), info=*0xd00e0528)
E {PPU[0x1000018] Thread (Discover AR Server) [0x01200a18]} SYS: 'cellNetCtlGetInfo' failed with 0x80130108 : CELL_NET_CTL_ERROR_NOT_CONNECTED [1]
U {PPU[0x1000018] Thread (Discover AR Server) [0x01861bc4]} sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd00e04b8)
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x11
E {PPU[0x100000a] Thread (fios mediathread 5) [0x014f2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEA00429/USRDIR/Levels/UI/Frontend/NavGraph.bfx_res” [1]
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x52
E {Network Thread} sys_net: Unknown/illegal socket error: 10051
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x11
E {Network Thread} sys_net: Unknown/illegal socket error: 10051
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x23
E {Network Thread} sys_net: Unknown/illegal socket error: 10051
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x14
E {Network Thread} sys_net: Unknown/illegal socket error: 10051
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x21
E {Network Thread} sys_net: Unknown/illegal socket error: 10051
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x19
E {Network Thread} sys_net: Unknown/illegal socket error: 10051
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x15
E {Network Thread} sys_net: Unknown/illegal socket error: 10051
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x24
E {Network Thread} sys_net: Unknown/illegal socket error: 10051
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x20
E {Network Thread} sys_net: Unknown/illegal socket error: 10051
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x16
E {Network Thread} sys_net: Unknown/illegal socket error: 10051
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x25
E {Network Thread} sys_net: Unknown/illegal socket error: 10051
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE
E {Network Thread} sys_net: Unknown/illegal socket error: 10049
E {Network Thread} sys_net: Unknown/illegal socket error: 10051 x99
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x100
E {Network Thread} sys_net: Unknown/illegal socket error: 10049
E {Network Thread} sys_net: Unknown/illegal socket error: 10051 x197
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x100
E {Network Thread} sys_net: Unknown/illegal socket error: 10051 x55
E {PPU[0x1000018] Thread (Discover AR Server) [0x0186032c]} sys_net: CLOSE x55
```

3. Emulator  crash almost every time on stop / close

Here are the logs with delay at 200µs as you recommended
[slycooper_test_delay200.zip](https://github.com/RPCS3/rpcs3/files/4271667/slycooper_test_delay200.zip)

**Comment by fearcraftor** [comment]
Game exited properly since version 0.0.9-9889, without error message

**Comment by Asinin3** [comment]
>1.  Audio very buggy

This doesn't affect me nor has it ever. You have a 4thread i5-4440 CPU, which is the problem. Not the game.
>2. Sometimes game fail to reach Main menu at this point (note that this error append also when game boot well)

This also has not happened to me.
>3. Emulator crash almost every time on stop / close

This affects other games, it's not related to sly cooper thieves in time. There was a regression ages ago.
>4. This error loops while ingame
  E {RSX [...]} RSX: Unsupported depth conversion (0x8B)

This is not an issue.

While Sly Cooper *does* have still have stability issues; mainly with the loading screens in some zones e.g the Turning Japanese stage everything listed in this issue seems to have either been fixed or was a non-issue to begin with.

**Comment by YuriNator557** [comment]
I think this can be closed now. I have played through the entire game in one sitting and never ran into a stuck loading screen or a crash. We have discovered that limiting the FPS to 60 can alleviate the hanging loading screens

**Comment by uaqlover** [comment]
Fixed @AniLeo
