### ISSUE TITLE
After Burner Climax freezes after #7627

### ISSUE THREAD

**Issue by digitaldude555** [RPCS3/rpcs3#7653]
## Quick summary
Game randomly freezes loading level or at the start of the level.

## Details
Broken with #7627 
[RPCS3AfterBurnerAfter.zip](https://github.com/RPCS3/rpcs3/files/4271599/RPCS3AfterBurnerAfter.zip)
[RPCS3AfterBurnerBefore.zip](https://github.com/RPCS3/rpcs3/files/4271601/RPCS3AfterBurnerBefore.zip)

**Comment by Nekotekina** [comment]
Fixed.
