### ISSUE TITLE
Skate 3 Freezing error

### ISSUE THREAD

**Issue by MakiSalonga** [RPCS3/rpcs3#7655]
Found this a couple of time whenever I tried to restart a challenge:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4271622/RPCS3.log)

F {PPU[0x1000011] Thread (render_thread) [0x0121b980]} VM: Access violation reading location 0xfffe8010 (unmapped memory)
Specs:
RPCS3 v0.0.9-9790-fbe6900b Alpha | HEAD | Firmware version: 4.85
Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz | 4 Threads | 3.90 GiB RAM | TSC: Bad | AVX+

**Comment by AniLeo** [comment]
Needs checking if it happens on decent specs, this is way below recommended and specially on Skate 3
