### ISSUE TITLE
Regression: Ratchet and Clank Future: Tools of Destruction freezes on boot

### ISSUE THREAD

**Issue by Cervoxx** [RPCS3/rpcs3#7667]
## Quick summary
The regression causes one single frame to be displayed, then nothing more. No audio, nothing.

## Details

This build and up has the regression: rpcs3-v0.0.9-9792-b05b16ae_linux64

This build and down does not have the regression: rpcs3-v0.0.9-9791-ffd5a9e9_linux64

Regressed build logs: https://files.catbox.moe/ip1kcz.gz

Working build logs: https://files.catbox.moe/aa6f0v.gz

Serial: BCUS98127

**Comment by elad335** [comment]
try #7663

**Comment by Cervoxx** [comment]
#7663 built from commit 4d8311b does not fix the issue. 

Logs: https://files.catbox.moe/mdsmqt.gz

**Comment by Cervoxx** [comment]
#7663 built from commit 51d2248 does not fix the issue, but now we get an error prompt. Progress?
![image](https://user-images.githubusercontent.com/12489208/75638369-3143e300-5bf1-11ea-8ce2-8beb35fedeec.png)

Logs: https://files.catbox.moe/5rzc9v.gz

(Also had to manually set read and write permissions to the log file so I could upload it)

**Comment by Cervoxx** [comment]
#7663 built from commit 70f8b34 fixes the issue! Ratchet and clank Boots just fine! 

Logs in case you're curious: https://files.catbox.moe/6nqjbs.gz

**Comment by Cervoxx** [comment]
Uh, this official build rpcs3-v0.0.9-9803-87c8d180_linux64 also seems to boot up the game just fine. Haven't tested any of the other builds though.

**Comment by Cervoxx** [comment]
@elad335 Should this issue be closed?

**Comment by Emulator-Team-2** [comment]
@Cervoxx 
This regression was fixed by build #7668.
You can close this issue.
