### ISSUE TITLE
assertion failed error when stop the game

### ISSUE THREAD

**Issue by narcissussic** [RPCS3/rpcs3#7682]
## Quick summary
assertion failed error  when stop the game on 0.0.9-9809 version
## Details
Please provide as much detail as you can here, including
- expected (real hw) and observed (emulator) behavior
- full logs (not from UI)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4282964/RPCS3.log)

- back traces (for hard crashes)
- screenshots, Renderdoc, and RSX captures (for visual issues)
![2020 03 04-02 09](https://user-images.githubusercontent.com/61244668/75806693-1de67280-5dbf-11ea-945e-058baab41fce.png)

- your system configuration (OS, CPU, GPU, driver versions, etc)
win10 ltsc2019
 i5 9600kf+rx5700
- anything else you deem to be important

**Comment by vaishnav67** [comment]
It looks like a memory leak error (judging from the code: Hitting it means you have some memory leak - unreleased VmaAllocation objects.)

**Comment by kd-11** [comment]
Do a regression bisect. There have been no changes to memory management which can only mean object lifetimes using our global object manager has changed. It would be helpful to identify the commit that introduced this. The renderers do their own cleanup on destruct which can only mean they're not getting unloaded correctly.

**Comment by narcissussic** [comment]
> Do a regression bisect. There have been no changes to memory management which can only mean global object lifetimes using our global object manager has changed. It would be helpful to identify the commit that introduced this. The renderers do their own cleanup on destruct which can only mean they're not getting unloaded correctly.


![2020-03-04 21 14 26 rpcs3 net 1d7287e86dc0](https://user-images.githubusercontent.com/61244668/75883322-cf3be580-5e5d-11ea-82dc-e557d1ef8a5d.jpg)
from version 0.0.8-9787，before is normal
[https://github.com/RPCS3/rpcs3/pull/7639](url)

**Comment by kd-11** [comment]
I'm unable to reproduce this issue, although I did see it some time ago. Gather a list of games that easily trigger the problem and maybe I could see if it happens for me.

**Comment by narcissussic** [comment]
> I'm unable to reproduce this issue, although I did see it some time ago. Gather a list of games that easily trigger the problem and maybe I could see if it happens for me.

to reproduce the issue you should,   don't replace  rpcs3 old files ,when I download the newest rpcs3 and replace the old files there is no problem if I stop the game, and the game is persona5[NPJB00769]

**Comment by AniLeo** [comment]
This doesn't make much sense, what files? If you don't fully update replacing qt dlls and such you're not updating properly

**Comment by narcissussic** [comment]
> This doesn't make much sense, what files? If you don't fully update replacing qt dlls and such you're not updating properly

I means you should just extract the  rpcs3 7z files  and don't use the old files

**Comment by kd-11** [comment]
Seems to have gotten fixed, can you confirm if it's still happening?

**Comment by narcissussic** [comment]
> Seems to have gotten fixed, can you confirm if it's still happening?

still happen
