### ISSUE TITLE
FINAL FANTASY XIII CANT LOAD SAVEDATA[BCAS25005]

### ISSUE THREAD

**Issue by Myoko** [RPCS3/rpcs3#7687]
today i test it again! using the latest build 0.0.9-9812 [BCAS25005] 
but still cant load save only can save

SPEC
9900K
RTX 2070
Driver 442.50
![FF](https://user-images.githubusercontent.com/3013386/75878298-5e440000-5e54-11ea-95db-581f3d234844.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4287173/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
https://github.com/RPCS3/rpcs3/issues/6610 you already created this issue.

**Comment by GiantEnemyCrab** [comment]
I am able to load a save game
build version: 10272

https://www.youtube.com/watch?v=5UvUsUVjqZA

**Comment by lextra2** [comment]
> I am able to load a save game
> build version: 10272
> 
> https://www.youtube.com/watch?v=5UvUsUVjqZA

This issue is for the asian versions of this game. the US version works fine

**Comment by Megamouse** [comment]
This might be the same issue as #6859

A possible fix was submitted already.
@Myoko please test both games again

**Comment by Megamouse** [comment]
assuming this was fixed .
Reopen if the issue persists.
