### ISSUE TITLE
Regression, Can Not Install Firmware

### ISSUE THREAD

**Issue by jeremybris** [RPCS3/rpcs3#7690]
## Quick summary
I _consistently_ can install PS3UPDAT.PUP, firmware 4.85, **On Build 0.0.8-9772**
I _inconsistently_ can install PS3UPDAT.PUP, firmware 4.85, **On Build 0.0.8-9774**
~~@Nekotekina, Since #7645~~, Since #7637

## Details
When setting up RPCS3 for the first time, the emulator stalls, crashes, or succeeds during compiling PPU modules.

![Capture](https://user-images.githubusercontent.com/11889359/75889233-99b1e080-5dfa-11ea-8680-e766f7fe04bd.PNG)
 

However, if I reopen the emulator, and try to install the firmware again, I can do so, and the emulator seems to work fine.

## Specifications
RPCS3 Build - 0.0.8-9779
OS - Windows 10, Latest Update
CPU - AMD 3900x
GPU - Nvidia RTX

**Comment by lextra2** [comment]
Can confirm. I have the same issue.

**Comment by AniLeo** [comment]
Probably fixed on latest

**Comment by jeremybris** [comment]
It still randomly crashes or stalls On Build 0.0.9-9824.

_But_, compiling PPU modules is _**A LOT** slower_ now for me.


-- | Time to Compile PPU modules On Build 0.0.9-9680 | Time to Compile PPU modules On Build 0.0.9-9824
-- | -- | --
Uncharted 3 [BCES01670] | 1 minute | 12 minutes

@AniLeo is this an issue? Or did RPCS3 developers intentionally compile the modules slower for accuracy?

**Comment by Nekotekina** [comment]
#7645 could not break anything. Please find build which really breaks things.

**Comment by lextra2** [comment]
I'm testing which build caused the issue. so far, 9754 is working fine. now I will go up from there.

**Comment by jeremybris** [comment]
After retesting, I agree, it is PR 7637.

_**However**_, as lextra said, the crashing happens less frequently on build 9774. I am getting more crashing on 9775. **It may be a separate regression causing the crashing.** We will know, once this regression is fixed.

**Comment by Nekotekina** [comment]
Please retest with #7706

**Comment by lextra2** [comment]
@Nekotekina 
I tested #7706 with the same testing procedure as above, delete old folder, extract 7z and install firmware on this fresh build. Worked 5 out of 5 times (no more stalling).

So this should be fixed.
