### ISSUE TITLE
Dead Island: No longer going ingame

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#7691]
Dead Island [NPUB31066] hangs shortly after the intro splash screens.  The first thing you will notice is that you cannot enter any gamepad inputs to skip those screens.  Eventually the game hangs on a black screen after the last one.

Bisecting shows the first bad commit is f1f5c91386e017f0a4fc1af4ba5ffeb2f575f0a9, which is from PR https://github.com/RPCS3/rpcs3/pull/7516. 

Also note this should have nothing to do with (https://github.com/RPCS3/rpcs3/issues/6798), a separate issue involving graphics which renders the game essentially unplayable.

Tested on linux mint 19.3, and kernel 5.3 x64, compiled using gcc 9.2.1

Log from bad build: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/4289327/RPCS3.log)

**Update:** This is "fixed" by setting Network status to "connected" and PSN status to "simulated" though it's unclear why, given that prior to the above commit the game was working with network set to "disconnected".  Also, even after this "fix", the game now takes much longer to go ingame (I've clocked it at 50 seconds, whereas prior to the above commit it was going ingame in 2-5 seconds).  This is possibly due to a network timeout on behalf of the game as it seeks a connection to PSN and eventually fails.

**Comment by elad335** [comment]
you really are not helping without specifying exact pull request..

**Comment by Megamouse** [comment]
tbf it's two clicks. so idk why you're upset XD

**Comment by elad335** [comment]
@Shoegzer is 54775d9 the first build not working or just the one you last tested?

**Comment by Shoegzer** [comment]
@elad335 https://github.com/RPCS3/rpcs3/commit/54775d91dc0809c0f3e9f7469f5e93ef77ca098b is the build I tested that exhibited the issue.  Again it wokred with commit https://github.com/RPCS3/rpcs3/commit/c7fa4e237520b0398460417f5f015bf453b03e6a which was recent, I was hoping that would help narrow it down rather than leaving it open-ended.  I can do a bisect to get the exact commit where the regression occurred if you need it, I just haven't had time to do that yet.

**Comment by elad335** [comment]
No, its just a waste of developer time and money to narrow down to exact commit/build instead of user which reported.

**Comment by dio-gh** [comment]
Long story short he says yes please.

**Comment by Shoegzer** [comment]
Yep, I suppose he is.  To be clear I AM offering to bisect when I have some more time to do that, in case the cause of this issue wasn't immediately apparent to him.  I take by his response that it is not, so I'll do that when I have time.

**Comment by dio-gh** [comment]
Have you tested setting the PSN connection status in the Network tab to `Simulated`? (With the regular connection status as both `Connected` and `Disconnected`?)

**Comment by Shoegzer** [comment]
@dio-gh Thanks, I hadn't thought to try that because I assumed the previous configuration (which worked fine) was the same as "Network: disconnected" and "PSN: disconnected".  However, when I changed it to "Network: connected" and "PSN: simulated", it worked.  It would be interesting to know why this is suddenly required, but apparently it is.

If the consensus is that this is expected behavior, I'll close this one.

**Comment by dio-gh** [comment]
Interesting. Nothing should have changed. I'll pass it over to @RipleyTom to decide.

**Comment by Shoegzer** [comment]
I've updated the post above with the latest findings re: network settings and also indicating that the game takes much longer to go ingame than it did prior to this commit (clocked at 50 seconds vs. 2-5 seconds).

**Comment by Asinin3** [comment]
@Shoegzer Please retest. You said it was fixed by changing network settings which you didn't have to change in previous builds. And since there has been a ton of networking related changed we'd like to know if this is still a problem.

**Comment by MsDarkLow** [comment]
The game goes ingame just fine, it doesn't matter which network setting you are using. 
Tested each network setting and result is always the same.
RPCN currently allows you to select the playstation network and go ingame but the online functionality doesn't currently work.
![pictor](https://user-images.githubusercontent.com/9060436/97777233-adb70900-1b66-11eb-8a06-5bbf997aea9a.jpg)

**Comment by Shoegzer** [comment]
@Asinin3 confirmed this is no longer an issue.  I was going to test it last night when checking in on another issue with this title (overbloom) but hadn't gotten to it in time.  There seems to be a performance regression (used to get 30fps, now at about 15fps) but that's something different.
