### ISSUE TITLE
compiling firmware prx sometimes cause emulator crash

### ISSUE THREAD

**Issue by Nerboruto** [RPCS3/rpcs3#7699]
## Quick summary
after cleaning cache folder including prx firmware files, 
emulator compiles the game-related files first, subsequently not finding the compiled firmware files in cache, emulator pause esecution and compile them..
5 cases randomly occur:
1) emulator crashes and closes itself the firmware prx file stuck on compile and is not write in cache.
[RPCS3 - case1.log](https://github.com/RPCS3/rpcs3/files/4292633/RPCS3.-.case1.log)

2) popup compilation message does not appear on the screen and the compilation process remains stalled until the correct focus is restored to the popup window (alt+tab and click with mouse on pupup)

3) error message
![error](https://user-images.githubusercontent.com/10599012/75972012-e832ae00-5ed2-11ea-992c-bf22de31f7b2.jpg)

4) emulator crash
![CASE4](https://user-images.githubusercontent.com/10599012/75976498-dbb25380-5eda-11ea-908c-f5a8269682b5.jpg)
[RPCS3 - Case4.log](https://github.com/RPCS3/rpcs3/files/4292601/RPCS3.-.Case4.log)

5) the compilation process is performed correctly and the emulation is resumed without problems

## Details
is a general stability error not related to a specific pr...
in more recent builds it happens more often....

**Comment by jeremybris** [comment]
I think this is the same issue as https://github.com/RPCS3/rpcs3/issues/7690.

**Comment by Nekotekina** [comment]
Please retest with #7706

**Comment by Nerboruto** [comment]
I just got a case1...
however I will do other tests to see if at least some other cases have improved ...
![folder](https://user-images.githubusercontent.com/10599012/76063261-a879ce00-5f87-11ea-85ef-8c7c45be44c0.jpg)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4297140/RPCS3.log)

**Comment by Nerboruto** [comment]
cache cleared and second attempt
i got a case3
![error](https://user-images.githubusercontent.com/10599012/76064539-250dac00-5f8a-11ea-9681-62acb100eff4.jpg)
[RPCS3-2.log](https://github.com/RPCS3/rpcs3/files/4297200/RPCS3-2.log)

**Comment by Nerboruto** [comment]
the most frequent case is 1...

**Comment by Nerboruto** [comment]
in my opinion the thing can be solved by checking before the game starts and in case by recompiling the firmware by itself ..

**Comment by Nekotekina** [comment]
Crash in Qt, maybe unrelated problem? I'll think more.

**Comment by Nerboruto** [comment]
i did further tests ... in case1 i noticed that
sometimes the crash emulator and the compiled firmware file is saved .. then I noticed that it does it randomly not always on the same file .. 7707 seems more stable to me I don't know if it's a placebo effect. 
case1, 3 and 4 could be the same problem. 2 has not yet occurred to me ...

**Comment by Yahfz** [comment]
@Nerboruto is this still an issue?

**Comment by Nerboruto** [comment]
crashes are still there ...
I have to deal with it every time I clean the cache folder...
sometimes the emulator quits without errors
others give the exception error message.
also lately when building the cache spu the window freezes. before he did it smoothly
![1](https://user-images.githubusercontent.com/10599012/97799782-4ebdc680-1c30-11eb-9b61-4468e5a91bae.jpg)
![2](https://user-images.githubusercontent.com/10599012/97799787-541b1100-1c30-11eb-9b08-83257cfd25cd.jpg)

**Comment by Nekotekina** [comment]
Hmm, is it even the same problem, or new regression?

**Comment by Nerboruto** [comment]
crashes never went away...
i don't know if it is a qt5 problem...
the problem of updating the spu cache window has been happening for quite some time

**Comment by Nerboruto** [comment]
I'm testing the latest version with llvm 11 ...
after cleaning cache folder
immediately a qt5gui.dll crash...

**Comment by Megamouse** [comment]
It seems like your hardware is extremely low spec. I don't know if it's worth investigating this

**Comment by Nerboruto** [comment]
I have five PC from 2 to 8 core. Rpcs3 run surprisingly good in all my machine. Crash are present in all pc. If you want i close the.Inviato dal mio Wind Smart 2018Il 21 mar 2021 18:07, Megamouse ***@***.***> ha scritto:
It seems like your hardware is extremely low spec. I don't know if it's worth investigating this

**Comment by Nerboruto** [comment]
I tested the latest builds on various pCs... the compilation seems much more stable thanks also to the latest changes to the osd there are no more qt5 crashes. can I close?
