### ISSUE TITLE
Cars have no audio in Gran Turismo 5 [BCUS98114]

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#7704]
Cars engines, crash sounds and the crowd have no sound during races in GT5. The menu music and sound effects work fine.

The regression happened on build 0.0.9-9806.
Specs: I7-4770, 8GB RAM, Windows 10 Pro Build 18362 GTX 1050ti.

Logs:

Last working version (9805):
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4294163/RPCS3.zip)

Broken version (9806):
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4294132/RPCS3.zip)

**Comment by dio-gh** [comment]
Referencing the offending PR: #7672.

**Comment by elad335** [comment]
was it always an issue with ASMJIT?

**Comment by Yahfz** [comment]
Just tested LLVM and ASMJIT and both using the latest master (9826) and both are fine.

**Comment by gtmaniacmda** [comment]
I have the same problem on build 0.0.9-9830. The audio was functioning perfectly normally on game version 2.01, but after updating to 2.17 I encountered these problems.

**Comment by dio-gh** [comment]
Needs retesting with #8316.

**Comment by Satan86** [comment]
accurate xfloat does bring back the audio, and I did try with #8316 but I simply didn't manage to get ingame with approximate xfloat, because the game has been extremely unstable on recent builds going as far as desyncing upon boot. with accurate xfloat the audio still stutters the same way.

**Comment by elad335** [comment]
Still an issue? I believe the pull request which fixed it got partially reverted.

**Comment by Satan86** [comment]
Not an issue anymore, audio still works
