### ISSUE TITLE
Unhandled win32 exception 0xC0000005

### ISSUE THREAD

**Issue by FluffyDiscord** [RPCS3/rpcs3#7710]
## Quick summary
click play button (any game) > game window pops in > freeze forever > win exception

## Details
its been like that as far as i know about rpcs3 (~2 months)
![Screenshot_2](https://user-images.githubusercontent.com/10332247/76115242-1655e200-5fe8-11ea-9833-77376b1359a1.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4300008/RPCS3.log)

**Comment by dio-gh** [comment]
To my absolute surprise this is a legit ticket, please don't close. I could also repro this on my machine.

**Comment by kd-11** [comment]
So, you get the crash by just starting rpcs3 and clicking play?

**Comment by FluffyDiscord** [comment]
> 
> 
> So, you get the crash by just starting rpcs3 and clicking play?

yes, on every start of every game i have (two)

**Comment by kd-11** [comment]
I cannot reproduce this. When you just press play it should play the last game you ran. Does it do that at least? On my side it just works, maybe it got fixed recently?

**Comment by FluffyDiscord** [comment]
no, same crash for when i click the button on top in the bar to play last game and same behavior when i directly right click on the game and select play from the menu, if i can somehow debug this for you, please tell me what i should do

**Comment by dio-gh** [comment]
@kd-11 I posted a screen recording into #staff-off-topic yesterday if that helps.

**Comment by kd-11** [comment]
Doesn't seem to happen on linux, maybe only windows is affected.

**Comment by RainbowCookie32** [comment]
I reproduced it once on Windows, and never got it again. Seems to be one of those nice issues

**Comment by jeremybris** [comment]
> yes, on every start of every game i have (two)

I tested on 10 different games, and I could not reproduce once. I'm on **Windows 10**. If you can reproduce it consistently, it may be an issue with your two games. So... **_what are your two games_** lol???

**Comment by FluffyDiscord** [comment]
This one from the report and persona 5

**Comment by elad335** [comment]
Try changing gpu settings.

**Comment by FluffyDiscord** [comment]
> 
> 
> Try changing gpu settings, or even test null renderer.

just updated to the latest version, null renderer works and even opengl works (starts at least), the vulkan is freezing, thats better then before, before the opengl did not work

**Comment by FluffyDiscord** [comment]
i have played the game for a minute or so with the opengl setting then i switched to vulkan and selected my rx 470, the game (persona 5) booted up, run for few seconds, then similar exception was thrown, maybe it has something to do with compiling/running the shaders ? the longed i am in the opengl version and the more shaders are compiled, the longer i can stay in vulkan mode

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4302995/RPCS3.log)

**Comment by FluffyDiscord** [comment]
Does the LLVM use Linux kernel ?

**Comment by RainbowCookie32** [comment]
Vulkan and OpenGL don't share shader caches, so that's probably not the issue

**Comment by FluffyDiscord** [comment]
UPDATE: from version 0.0.9-9925-a0612ff4 Alpha Vulkan renderer works correctly under Windows, gj guys

**Comment by ahmmad88** [comment]
i have the same problem did you manage to fix it?
