### ISSUE TITLE
using arrows in the On Screen Keyboard moves menus it's on top of

### ISSUE THREAD

**Issue by plonk264** [RPCS3/rpcs3#7711]
## Quick summary
using D Pad arrows and buttons in the On Screen Keyboard in Rock Band 3 navigates and traverses the menus behind while "typing" on the keyboard

## Details
Please provide as much detail as you can here, including

- screenshots, Renderdoc, and RSX captures (for visual issues)
https://www.youtube.com/watch?v=CDTmoyc96kw

- your system configuration (OS, CPU, GPU, driver versions, etc)
Win10 1903, Ryzen 1700X, Fury

**Comment by Megamouse** [comment]
Which version broke it?
