### ISSUE TITLE
Demon's Souls [BLES00932] regression on OpenGL

### ISSUE THREAD

**Issue by nivkner** [RPCS3/rpcs3#7713]
before #6744 Demon's Souls works on OpenGL
![BEFORE_Screenshot](https://user-images.githubusercontent.com/22821514/76132705-ea088880-601c-11ea-93db-915d637938c7.png)

after #6744 OpenGL only renders HUD elements, with constant black/white frame flickering
![AFTER_Screenshot](https://user-images.githubusercontent.com/22821514/76132760-263be900-601d-11ea-95f4-cb5a9f4ae1c1.png)

on vulkan there are no such graphical issues.

the build that introduced the regression is rpcs3-v0.0.7-8878-42aa4c50_linux64

[RPCS3.log before](https://github.com/RPCS3/rpcs3/files/4301197/BEFORE_RPCS3.log)

[RPCS3.log after](https://github.com/RPCS3/rpcs3/files/4301205/AFTER_RPCS3.log)

OS: linux 5.5.8
CPU: intel i5-4460
GPU: GeForce GTX 760
regression appears on both the nvidia driver 440.64.0.0 and mesa 19.3.4

**Comment by sampletext32** [comment]
Wow, thats incredible. You almost listed a thousand of versions to find this specific bug.

**Comment by RainbowCookie32** [comment]
He mentioned the specific PR that introduced the issue though

**Comment by sampletext32** [comment]
Yeah, and that of course is very handy. I'm just amazed with the amount of tests for such a bug.

**Comment by kd-11** [comment]
I did some preliminary debugging a few weeks ago on this issue but I had not yet completely solved it. A fix should be available soon.

**Comment by kd-11** [comment]
I forgot to uncomment something when debugging the PR. Fixed by https://github.com/RPCS3/rpcs3/pull/7716
