### ISSUE TITLE
Tales of Graces fails at title loading saved data after build 9830

### ISSUE THREAD

**Issue by lsycxyj** [RPCS3/rpcs3#7714]
## Quick summary
When I load saved data in title screen, I get "segfault reading location" error and I can't continue the game. It works in 9754.

## Details
I don't know which commit caused this problem.

**Comment by Cervoxx** [comment]
> I don't know which commit caused this problem.

Figure it out then: https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression.3F

**Comment by vsub** [comment]
Works fine here(tried all 5 of my saves in different areas of the game)
RPCS3 0.0.9-9832
There is a lot of errors in the console but the game works

**Comment by lsycxyj** [comment]
It happenen when I reach somewhere after I started to play "future arc" with build 9832. I saved game and closed RPCS3. But when I tried to load the game to continue, it said "segfault reading location", even with build 9830 (100% reproduced). Then I tried 9754, it worked.
It's strange that I played with 9754 for a while, saved the game and close RPCS3, and I tried to start the game with 9832, the error doesn't show up again. I will try to play with 9832 and see if I can reproduce it again.

**Comment by vsub** [comment]
Nope,9830 works fine too
From the tittle testing I have done on this game on different rpcs3 versions,I have seen it randomly(rarely)crashing while loading a save

Can you post your save if you have the BLUS30903 version

**Comment by lsycxyj** [comment]
@vsub I have seen it randomly crashing too. But it 100% happened using either 9830 or 9832 with my old save. Then I used 9754 to play the game. The save have changed and I can't find the save which can reproduce the problem again.

**Comment by AniLeo** [comment]
Still doesn't meet the guidelines, pending update, otherwise it will have to be closed for inactivity

**Comment by lsycxyj** [comment]
Unable to recur... Weird...
I close this issue and open it if this happens again
