### ISSUE TITLE
GUI UI options are not retained after closing emulator.

### ISSUE THREAD

**Issue by r9guy** [RPCS3/rpcs3#7715]
## Quick summary
GUI UI options are not retained after closing emulator.

## Details
during startup splash screen checkbox "do not show again" has no effect.
have tried from Config->GUI->UI options. apparently these settings do not retain their state.

**Comment by Megamouse** [comment]
Provide log

**Comment by MSuih** [comment]
The "Load Settings" dropdown is set to CurrentSettings and not default, right?

**Comment by r9guy** [comment]
No. It is set to default.I just tried with “current settings”, and splash screen checkbox “Show welcome Screen” turned off after restarting once, but check for updates on startup didn’t .After second restart check for updates also retained it’s state. It is confusing how load settings work.  -- From: MSuihSent: Saturday, March 7, 2020 12:03 PMTo: RPCS3/rpcs3Cc: r9guy; AuthorSubject: Re: [RPCS3/rpcs3] GUI UI options are not retained after closing emulator. (#7715) The "Load Settings" dropdown is set to CurrentSettings and not default, right?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by vsub** [comment]
Maybe it's permissions related...cannot write into the directory where rpcs3 is placed.

If I set CurrentSettings.ini to readonly(which imitates permission restriction)then obviously the changes will not be saved...and rpcs3 will also not mention anything about it in the log

**Comment by r9guy** [comment]
No. It's not permission related, because it is in user documents folder on
windows 10.

**Comment by vsub** [comment]
Ok then just for test,try changing the view mode and restart rpcs3
If it's not that then the view mode will be kept after restarting rpcs3

It works fine here

**Comment by Megamouse** [comment]
Please retest

**Comment by Megamouse** [comment]
This should be fixed now, the "default" option doesn't exist anymore.
Reopen with a proper explanation if this is still an issue in the latest build.
