### ISSUE TITLE
The Evil Within [BLUS31374] Regression without CPU blit emulation

### ISSUE THREAD

**Issue by dyno0** [RPCS3/rpcs3#7732]
Regression after #7722 when not forcing CPU blit emulation. Works on previous builds.

Working:
![working](https://user-images.githubusercontent.com/54358666/76167556-c1d97080-6167-11ea-8ec4-b7ea3e13a335.JPG)

Regressed:
![regressed1](https://user-images.githubusercontent.com/54358666/76167557-c7cf5180-6167-11ea-8da9-b363d40e3d5f.JPG)
![regressed2](https://user-images.githubusercontent.com/54358666/76167559-c867e800-6167-11ea-99b8-63dee1eb9707.JPG)
![regressed3](https://user-images.githubusercontent.com/54358666/76167560-c9007e80-6167-11ea-8b5c-fa48a555dd89.JPG)

[regressed.gz](https://github.com/RPCS3/rpcs3/files/4303550/regressed.gz)
[working.gz](https://github.com/RPCS3/rpcs3/files/4303551/working.gz)

RSX captures are over 500mb. Will upload additionally if needed.

**Comment by kd-11** [comment]
Check if it is fixed by https://github.com/RPCS3/rpcs3/pull/7737
