### ISSUE TITLE
WWE 2K14 [BLES01937] SHADERS NOT LOADED PROPERLY 

### ISSUE THREAD

**Issue by SteveChomu** [RPCS3/rpcs3#7735]
## Quick summary
GAME NOT ABLE TO COMPILE SHADERS PROPERLY

## Details

- GAME NOT ABLE TO COMPILE SHADERS PROPERLY
- LOW FPS
- DLC AND SAVEDATA IS WORKING FINE
- PLAYED ON RPCS3 v0.0.9-9872 Alpha [2020-03-08]

## LOG
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4304813/RPCS3.log.gz)

## SCREENSHOTS

- KICK-OFF!
![Annotation 2020-03-09 104649](https://user-images.githubusercontent.com/61686894/76185901-a4071c80-61f6-11ea-8d0c-e92c2230cd8f.png)

- 30 YEARS OF WRESTLEMANIA
![Annotation 2020-03-09 1046491](https://user-images.githubusercontent.com/61686894/76185897-a1a4c280-61f6-11ea-9aec-30fc61f83b25.png)

## SPECIFICATIONS
AMD RYGEN 3550H
NVIDIA GTX1650 4GB DDR5
8 GB RAM 2400MHZ
WINDOWS 10 64 BIT

**Comment by Satan86** [comment]
Requires force cpu blit + write colour buffers to fix the graphics and read colour buffers to stop the game from flashing black
![image](https://user-images.githubusercontent.com/61447828/97779923-38086880-1b79-11eb-8813-e89b41dc8ba3.png)
