### ISSUE TITLE
Haze [BLUS30094] regression as of 0.0.9-9791

### ISSUE THREAD

**Issue by ZachFett** [RPCS3/rpcs3#7738]
## Quick summary
An error message prevents you from continuing to the main menu now.

## Details
Haze was in a playable state until 0.0.9-9791, since then if you try to start the game you'll be met by this error message: 

![image](https://user-images.githubusercontent.com/29797689/76216228-6f329f80-61cd-11ea-8060-cd198ba19672.png)

It'll prompt you to delete the save data it just created, once you're done you back out and are met with the same error message because it created a save once again that it thinks is corrupt. No way around this error message.

I went through builds and found that the game was working fine all the way up to 0.0.9-9790, after that every version of RPCS3 going forward has had this issue. I've attached logs from both builds.

[RPCS3 0.0.9-9790 (good).log](https://github.com/RPCS3/rpcs3/files/4306741/RPCS3.0.0.9-9790.good.log)
[RPCS3 0.0.9-9791 (bad).log](https://github.com/RPCS3/rpcs3/files/4306742/RPCS3.0.0.9-9791.bad.log)

**Comment by elad335** [comment]
Upload log with #7742

**Comment by ZachFett** [comment]
> Upload log with #7742

I'm uber new to GitHub, you want me to post those two log files in that other thread?

**Comment by elad335** [comment]
here please.

**Comment by ZachFett** [comment]
Uh, alright? The two logs are already in my first post, though, at the bottom of it. Here they are again?

[RPCS3.0.0.9-9791.bad.log](https://github.com/RPCS3/rpcs3/files/4310198/RPCS3.0.0.9-9791.bad.log)

[RPCS3.0.0.9-9790.good.log](https://github.com/RPCS3/rpcs3/files/4310197/RPCS3.0.0.9-9790.good.log)

**Comment by elad335** [comment]
no, you were supposed to use #7742, I wouldn't have linked for nothing.

**Comment by ZachFett** [comment]
But then you said, "here please." 😕 But alright, I've now posted the logs in there as well.

**Comment by elad335** [comment]
Just use the build https://ci.appveyor.com/project/rpcs3/rpcs3/builds/31350713 which is what #7742 provided and upload log here.

**Comment by ZachFett** [comment]
Alright, I get what you're saying now.. however, like I said, I'm new to GitHub. How do I use that build you linked? I assume I replace one of RPCS3's files with that text, but I'm oblivious to which one.

**Comment by elad335** [comment]
Yes.

**Comment by ZachFett** [comment]
Yes..? What file do I replace with that linked text?

**Comment by elad335** [comment]
RPCS3.exe

**Comment by elad335** [comment]
A more direct link to the download build - https://ci.appveyor.com/api/buildjobs/ie15eiqchi0s8icg/artifacts/rpcs3-v0.0.9-eb8beeca_win64.7z

**Comment by ZachFett** [comment]
Got it figured out, didn't realize the artifacts tab was like the "releases" tab. 👍 Here's the log from that build (still getting the error message on that build):

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4310444/RPCS3.log)

**Comment by lainiwaku** [comment]
i confirm happen the same on bles version 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4310481/RPCS3.log)

**Comment by elad335** [comment]
Fixed by #7742 .

**Comment by lainiwaku** [comment]
#7742 did not fixe it

**Comment by elad335** [comment]
you sure using ghe pull re

**Comment by lainiwaku** [comment]
@elad335  nevermind i was thinking you have merged it  to mainbranch  just notice that it isn't merged yet 🤐
