### ISSUE TITLE
[Linux] PS1 Classic MGS crashes on boot after #6560

### ISSUE THREAD

**Issue by RainbowCookie32** [RPCS3/rpcs3#7743]
## Quick summary
After #6560 was merged, the game segfaults on boot. On current master it hangs for a few seconds, and then crashes the whole emu without any errors prompts.

## Details
Last working build, everything's fine here.
![MGS_Good](https://user-images.githubusercontent.com/16805474/76246451-7fbe3680-621c-11ea-8732-1279c4ab75b2.png)

0.0.7-8725 (#6560), segfault on boot.
![MGS_Segfault](https://user-images.githubusercontent.com/16805474/76246456-80ef6380-621c-11ea-94b6-11c4b02f3c5e.png)

## Logs
[Log from 0.0.7-8717](https://github.com/RPCS3/rpcs3/files/4308398/MGS_8717_Good.zip)
[Log from 0.0.7-8725](https://github.com/RPCS3/rpcs3/files/4308399/MGS_8725_Bad.zip)
[Log from master](https://github.com/RPCS3/rpcs3/files/4308401/MGS_Master_VeryBad.zip)

**Comment by incognitoh** [comment]
it works perfectly fine for me on latest master with Win 10 and nvidia gpu.  must be something wrong on your end...or perhaps its just a Linux or AMD gpu issue?

![mgsrpcs3](https://user-images.githubusercontent.com/39333810/76647313-fae05f00-6532-11ea-875e-7a3ea3b59fc5.JPG)

![mgsrpcs32](https://user-images.githubusercontent.com/39333810/76647318-fc118c00-6532-11ea-999c-42df7554d747.JPG)

**Comment by RainbowCookie32** [comment]
Just checked on Windows and it did boot just fine, I'll check latest master on Linux in a bit

**Comment by RainbowCookie32** [comment]
Yeah, no luck on Linux. Same settings but it crashes the whole emu on boot after a few seconds on a black screen.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4331010/RPCS3.log)

**Comment by AniLeo** [comment]
Needs updating

**Comment by RainbowCookie32** [comment]
Seems to be working fine now on latest master. Closing as fixed
![image](https://user-images.githubusercontent.com/16805474/79021970-4c403600-7b53-11ea-928f-45f3b52de423.png)
