### ISSUE TITLE
[Feature Request] sysinfo has_avx small optimization.

### ISSUE THREAD

**Issue by sampletext32** [RPCS3/rpcs3#7754]
I've looked through SPUASMJITRecompiler and found out that there are quite a lot of calls to has_avx functions and similar to them. I think that system capabilities don't change while compilation. So I thought about making those function results cached. This can help to compile quite a bit faster, since re-getting of this parameters go away. 
So I can offer a small optimization to sysinfo.cpp. Add bool array flags with system capabilities and fill it once emulator starts. Then add get_cached, or maybe change existing functions to obtain precalculated values. 
I ask for qualified answer, if this optimization worth working on, and if yes, should I try implementing it?

@Nekotekina , I think this is your qualification.

**Comment by Nekotekina** [comment]
CPUID is called only once, then its result is memoized in static variable. Next calls just check some guard variables and load existing value.

**Comment by sampletext32** [comment]
So, is it necessary to check guard variables? 
I think, that more calculations on runtime means slower working. 
I think that instead of calculating this values every time, caching them would give a bit of performance.

Example: 
get_cpuid(0, 0)[0] >= 0x7 && (get_cpuid(7, 0)[1] & 0xd0030000) == 0xd0030000 && (get_cpuid(1, 0)[2] & 0x0C000000) == 0x0C000000 && (get_xgetbv(0) & 0xe6) == 0xe6;

this line contains at least
2 array accessors, 3 bitwise operations, 5 boolean calculations, 4 function calls.
and replacing them with just 1 array accessor would really increase function speed.

I can see 10 functions with this kind of weird calculations and some of them call each other.
So optimizing them seems pretty worth of working.

Correct me, if I'm wrong.

**Comment by Megamouse** [comment]
The value is only calculated once

**Comment by sampletext32** [comment]
@Megamouse , could you please explain why. 
Logically I can see more calculations. 
Maybe it's because of my poor CPP knowledge. Or maybe it's a compile time optimization?

If it's not a right place to ask questions like this you can close the ticket, but I would really like to know the truth.

**Comment by Cereal-Killa** [comment]
In fact I would like to know how that work as well, seems to be calculated every time it gets called.

`

bool utils::has_avx()
--
30 | {
31 | static const bool g_value = get_cpuid(0, 0)[0] >= 0x1 && get_cpuid(1, 0)[2] & 0x10000000 && (get_cpuid(1, 0)[2] & 0x0C000000) == 0x0C000000 && (get_xgetbv(0) & 0x6) == 0x6;
… |  
68 | static const bool g_value = has_avx() && get_cpuid(0x80000001, 0)[2] & 0x800;
69 | return g_value;
70 | }

`

**Comment by MSuih** [comment]
The variables are marked as static, so they will be initialized only once. Meaning that when has_avx is called for the first time the g_value variable is created, and any subsequent calls will use the value which is currently defined for it.

https://www.google.com/search?q=c%2B%2B+static+variable+in+function

**Comment by Cereal-Killa** [comment]
> The variables are marked as static, so they will be initialized only once. Meaning that when has_avx is called for the first time the g_value variable is created, and any subsequent calls will use the value which is currently defined for it.
> 
> https://www.google.com/search?q=c%2B%2B+static+variable+in+function

Thank you, that answers the question 😁

**Comment by sampletext32** [comment]
@MSuih thanks for explanation. I can clearly understand this theme now. Idea came out of shortage of knowledge.
