### ISSUE TITLE
Nier [BLUS30481] crashing on exit with recent builds

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#7755]
I haven't checked when the regression began, but it seems to be related the recent exceptions-related changes. On the build just before #7753 RPCS3 was crashing for me on every game exit and the watchdog was really difficult to trigger. Now (after #7753) it only seems to crash after every second run, and the watchdog seems to trigger a bit more reliably. Still shouldn't crash though, ideally.

Log from 0.0.9-9886: [RPCS3-9886.log](https://cdn.discordapp.com/attachments/319224795785068545/687078668765364235/RPCS3.log)

Log from 0.0.9-9889: [RPCS3-9889.log](https://cdn.discordapp.com/attachments/319224795785068545/687081590118940745/RPCS3.log)

**Comment by dio-gh** [comment]
Still an issue, albeit much more rare.

**Comment by AniLeo** [comment]
Probably fixed by #8315

**Comment by dio-gh** [comment]
Will try to repro harder, but the issue is actually general, not specific to Nier at all - and I did get it last night.

**Comment by dio-gh** [comment]
Trash issue, games still die randomly on exit but it's pointless keeping track of it, it isn't even specific to Nier to begin with. Closing.
