### ISSUE TITLE
RDR Undead Nightmare

### ISSUE THREAD

**Issue by JonFoxy** [RPCS3/rpcs3#7759]
Exception: LLE function not set: _cellFiberPpuInitialize (0x255870804)
(in file Emu\SysCalls\Modules.cpp:140, in function execute_ppu_func_by_index)

I get this message after attempting to boot the game. I dont know what it is or what it means. But im guessing its keeping me from playing my game and would really love some help.

**Comment by AniLeo** [comment]
> Emu\SysCalls\Modules.cpp

In what museum did you obtain RPCS3?
