### ISSUE TITLE
Ps3 Controller Shanwan Clone  : Evdev button (NULLSTR) (302) is unknown.

### ISSUE THREAD

**Issue by dariocdj** [RPCS3/rpcs3#7760]
## Quick summary
Evdev button (NULLSTR) (302) is unknown. Please add it to the button list.

## Details
When i try to map button of this controller square is mapping with DEAD and works but cross, triangle and circle (responding to evtest at 301, 302, 303) give me the error: 
Evdev button (NULLSTR) (302) is unknown. Please add it to the button list.
Searching in the code the regarding error come from:

case EV_KEY:
{
m_is_button_or_trigger = true;

// get the button value and return its code
if (button_list.find(code) == button_list.end())
{
evdev_log.error("Evdev button %s (%d) is unknown. Please add it to the button list.", libevdev_event_code_get_name(EV_KEY, code), code);
return -1;
}

value = val > 0 ? 255 : 0;
return code;
}

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4318803/RPCS3.log)

Logs attached
- your system configuration (OS, CPU, GPU, driver versions, etc)

My Config is a Intel Core i5-6500 running at 3.20ghz with 8gb ram ddr4 and geforce gtx 1050

Thanks a lot

**Comment by Megamouse** [comment]
Your log does not contain the information for the button mapping

**Comment by dariocdj** [comment]
Sorry, wait a min and i put right log, thanks

**Comment by dariocdj** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4325490/RPCS3.log)
Here is log of frogger for example...
You can see easily
·E 0:00:32.809810 evdev: Evdev button (NULLSTR) (301) is unknown. Please add it to the button list.
Thanks
