### ISSUE TITLE
Tales of Xillia(BLJS10120) hangs after starting game

### ISSUE THREAD

**Issue by lsycxyj** [RPCS3/rpcs3#7763]
## Quick summary
Game can be played with build 8614.

## Details
TOX (eur version, BLES0181) can be played by latest build (9881), but when I try to play the jpn version(BLJS10120), the game hangs when the game starts. 
The jpn version can be played with build 8614.

**Comment by lextra2** [comment]
Have you tried playing with `PPU Threads` set to `1` (manually edit it inside config.yml)? I remember I too had some issues until I used that setting.

**Comment by lsycxyj** [comment]
@lextra2 Unfortunately, I changed the yml file in rpcs3\config\custom_configs, and it doesn't work for me.

**Comment by lextra2** [comment]
Alright. It was worth a try.

**Comment by AniLeo** [comment]
Still doesn't meet the guidelines, pending update, otherwise it will have to be closed for inactivity

**Comment by HerrHulaHoop** [comment]
In the absence of a log, I had to try the game out for myself and it works perfectly fine on latest master. This issue can be closed.

![rpcs3_10111_2020-04-05_15-53-11](https://user-images.githubusercontent.com/31934788/78472413-2df2c880-7756-11ea-93fc-52aaa5f0fa1d.png)
