### ISSUE TITLE
Unhandled Win32 exception since #7511 / e005581d

### ISSUE THREAD

**Issue by namarrgon** [RPCS3/rpcs3#7767]
## Quick summary
The last "good" build was 0dd417e5, all other more recent builds since e005581d, up until today, cause an immediate unhandled exception when starting a game:
![exception_e00ff81d](https://user-images.githubusercontent.com/3209906/76568279-d2b01c00-64b0-11ea-84dc-d8d7cb4aa18d.png)
After confirming this dialog the program is closed.

## Details
The last working build:
[RPCS3_0dd417e5_GOOD.log](https://github.com/RPCS3/rpcs3/files/4326681/RPCS3_0dd417e5_GOOD.log)
The first broken build:
[RPCS3_e005581d_BAD.log](https://github.com/RPCS3/rpcs3/files/4326675/RPCS3_e005581d_BAD.log)
The latest build is still broken:
[RPCS3_f0edcc16_BAD.log](https://github.com/RPCS3/rpcs3/files/4326679/RPCS3_f0edcc16_BAD.log)

This happens only on windows with the official builds, self-compiled versions on linux work fine.

I can't tell if this is the same issue as #7710 but the logs there seem to differ so I filed a separate issue.

**Comment by r00lz** [comment]
This happening in GUI when trying to select games by dragging left mouse button from empty space to game list

**Comment by ahmmad88** [comment]
did you fix it?

**Comment by AniLeo** [comment]
Windows builds are working regularly, try a clean install with latest build, make sure you extract everything since you report having issues with the commit that added the XAudio2 dll

**Comment by namarrgon** [comment]
Unfortunately the logs are from clean installs, freshly extracted. I assume that it's the windows install that is somehow special since it dies somewhere in KERNELBASE.dll.

**Comment by namarrgon** [comment]
I've reinstalled windows now, from scratch - nothing besides rpcs3 and the amd drivers are "custom", and i still get the crash with the same symptoms. I'm not sure what else i could try.

**Comment by namarrgon** [comment]
The issue has fixed itself automagically with build 0.0.11-10612-f8920edb or earlier, I will try to narrow it down to the first build that worked again in the next few days.

**Comment by AniLeo** [comment]
Hmm, if it's fixed, the issue can be closed
Ping if you can reproduce again on latest build
