### ISSUE TITLE
UI Improvement: When selected, make "Strict Rendering Mode" also fade/grey out Anisotropic Filtering and Anti-Aliasing

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#7768]
I came across this inconsistency when testing Strict Rendering Mode. Anisotropic Filtering can still be changed in the UI but in reality it defaults to "Automatic" (and ignores what ever the user has set), so it should "fade" or "grey" out like Resolution Scale & Resolution Scale Threshold. And I think the same is true for Anti-Aliasing as well so it should apply there too.

And a minor nitpick, why not have AF & AA both say "Auto" or "Automatic" instead (one term for the same thing).

**Comment by lextra2** [comment]
@riotflowerpew thanks for the additions. But I think "Framelimit" should also be greyed out as [pointed out by elad335 ](https://github.com/RPCS3/rpcs3/pull/7773#issuecomment-599024887)

**Comment by RainbowCookie32** [comment]
Framelimiter is not affected by SRM as far as I know, and elad was just pointing out that framelimiter uses "Auto" instead of "Automatic" on UI

**Comment by lextra2** [comment]
Oh ok thanks for clearing that up. I was about to edit my comment saying that I can't test it my self right now.

So I'll close this issue. Thanks again @riotflowerpew
