### ISSUE TITLE
Minecraft second player doesn't work

### ISSUE THREAD

**Issue by dariocdj** [RPCS3/rpcs3#7769]
## Quick summary
Using last version of rpcs3 with two working PS3 controller, tried Minecraft BLES01976 version 1.78 and latest 1.83, with PSN Status
Log;:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4329422/RPCS3.log.gz)

 simulated and not. When i press start on second controller (paired correctly) nothing happen. No second player enter in game and no split screen

## Details
expected that Screen split and appear a box with "press start to join game" or something similar.
CPU0: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz Geforce GTX1050 
GPU In Vulkan mode 

Thanks a lot

**Comment by 13xforever** [comment]
This issue is invalid. If you need help with proper emulator configuration, please ask in our discord server.

![image](https://user-images.githubusercontent.com/36445/76628458-920edc00-655e-11ea-8dfa-baf4af81f954.png)
