### ISSUE TITLE
UI is not displaying correctly 

### ISSUE THREAD

**Issue by gamrXerus** [RPCS3/rpcs3#7772]
Ever since 0.0.8-9549 the UI does not display correctly on my machine. Text and icons are cutoff in the menus. I'm running Lubuntu 19.10. RPCS3 0.0.8-9546 and earlier work fine.
![1](https://user-images.githubusercontent.com/19245344/76659460-e315d480-654c-11ea-9490-f4d3cbfda05d.jpg)
![2](https://user-images.githubusercontent.com/19245344/76659462-e3ae6b00-654c-11ea-8e0e-be68e17590e8.jpg)
![3](https://user-images.githubusercontent.com/19245344/76659463-e4470180-654c-11ea-894a-a87da9fb7f27.jpg)
![4](https://user-images.githubusercontent.com/19245344/76659464-e4470180-654c-11ea-8fbe-e23dd62ff25c.jpg)

**Comment by dio-gh** [comment]
Referencing the offending PR: #7459

**Comment by hcorion** [comment]
I'd like to know display backend (Wayland, X11), display resolution and whatever scaling setting LXDE has, graphics card and graphics drivers please.

**Comment by crtnr** [comment]
Having the same issue on GNOME 3.34.4 (X11, 1920x1080, RX560, amdgpu-pro) 
![Screenshot from 2020-03-16 14-33-32](https://user-images.githubusercontent.com/27908024/76729092-57da5000-6793-11ea-88e7-e28ba5e0afb4.png)
![Screenshot from 2020-03-16 14-33-36](https://user-images.githubusercontent.com/27908024/76729115-658fd580-6793-11ea-8c1b-4bf94ea247d5.png)

**Comment by gamrXerus** [comment]
1. Display backend: X11
2. Resolution: 3840x2160
3.  I didn't set any scaling setting for LXQT. I dont see any option for it in Configuration Center
4. GPU: NVIDIA GTX1060
5. Driver: 440.64

**Comment by qurious-pixel** [comment]
I had this issue with Lubuntu 19.10, X11 backend. 
The solution was to change the QT scaling environment variable.
`export QT_AUTO_SCREEN_SCALE_FACTOR=0`

**Comment by gamrXerus** [comment]
I added the command to my ".profile" file in the home directory and rebooted. I can confirm that it works properly now. :)
