### ISSUE TITLE
Shadow of the Colossus Classics HD Vulkan Device Lost

### ISSUE THREAD

**Issue by OPipoca** [RPCS3/rpcs3#7774]
Tried to boot the game with Vulkan and before the main menu, the game stops and it shows the device lost error. Both ICO and SOTC have this problem. On OpenGL the game works with no crashes so far. Tried Vulkan with Ninja Gaiden Sigma and the game works fine.

Thanks.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4331974/RPCS3.log)

**Comment by kd-11** [comment]
Please retest, there have been many bug fixes in recent times.

**Comment by OPipoca** [comment]
So, i gave it a try, and unfortunately, it didn't go well. Same error, but just to be sure i'm gonna be sending the log again. 

Thank you.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4790446/RPCS3.log)

**Comment by kd-11** [comment]
Ok, I know what's happening. We have a data copy hack used to speed up memory operations that is disabled on Turing cards, but you have a super card that is not yet registered in rpcs3's GPU detection tables. I'll just update with the super cards and invert the workaround condition to only apply for known GPU generations that are ok with the speedup.
To confirm this theory, enable the "High precision Z buffer" option in the debug tab.

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/8523 which registers super cards as well as RTX mobile and GTX 1600 series super and mobile as well.

**Comment by OPipoca** [comment]
Holy fucking shit. That's it! You did it, man! I tried enabling the "High Precision Z Buffer" and it didn't work, but that's because i was using custom configs and i changed the global config, but when i did it on custom, the game booted and everything is smooth and awesome! 

Thanks a lot, to you and the whole team behind RPCS3, you guys are fantastic, seriously.
