### ISSUE TITLE
[Regression] RSX fatal error when entering gameplay in Conan

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#7785]
Upon starting gameplay, emu crashes now with this error:

{RSX [0x0125ce0]} sig_log: Thread terminated due to fatal error: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:356)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4334783/RPCS3.zip)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by dio-gh** [comment]
Which build did it regress with?

**Comment by legend800** [comment]
Because of this issue:  https://github.com/RPCS3/rpcs3/issues/7733 it's nearly impossible to figure this out. I can only get to the menus maybe 1/10 times now (so about 15 mins to check). I did get in yesterday on a new mainline build and the issue was still present.

**Comment by legend800** [comment]
Got into gameplay on today's master build (after 5 attempts). I don't think I'll ever be able to find the build where it was broken since it takes like 10-15 mins to reach the menus. Hopefully the verification at that line can be a clue and checking the diffs to that file recently.

Exception:
·F 0:01:26.778448 {RSX [0x0163108]} SIG: Thread terminated due to fatal error: Verification failed: 
(in file d:\a\1\s\rpcs3\Emu\RSX\RSXThread.cpp:356)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4526590/RPCS3.zip)

**Comment by Loacoon1** [comment]
I'm having the same type of error with Killzone 3. A few seconds after the gameplay starts, it freezes and says :  F {RSX [0x08aef64]} SIG: Thread terminated due to fatal error: Verification failed (e=11): 
(in file /var/tmp/pamac-build-loacoon/rpcs3-git/src/rpcs3/rpcs3/Emu/RSX/RSXThread.cpp:359)

**Comment by legend800** [comment]
Interesting. Looks like it's around the same line of code as the exception in Conan. If we have a few mins, see if you can find the build that broke it:
https://rpcs3.net/compatibility?b
I think it's been broken since beginning of March.

**Comment by Loacoon1** [comment]
I'm up to 0.0.9-9861. Still happening but the error message is a but different. Though the cause seems to be the same. 
F {RSX [0x082ef64]} RSX: St13runtime_error thrown: Verification failed (e=11): 
(in file ../rpcs3/Emu/RSX/RSXThread.cpp:355)

**Comment by Loacoon1** [comment]
I went to end of December, still the exact same message... It's wierd...

**Comment by Loacoon1** [comment]
Ok it seems like I got it. It crashes since this version : 
#7102
kd-11kd-11
+1255-524
141 days ago (2019-12-29)
0.0.7-9271

The previous one on the website doesn't crash.

**Comment by Emulator-Team-2** [comment]
@legend800 
-Enable `Relaxed ZCULL Sync` in the `Advanced` tab to fix (RSXThread) fatal error.

**Comment by legend800** [comment]
Confirmed, nice find! It can now load gameplay which renders correctly now, assuming you can get past this: https://github.com/RPCS3/rpcs3/issues/7733
