### ISSUE TITLE
[Regression] Left click on mouse no longer works in PS Move mode

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#7786]
Left click is no longer functional on mouse when in PS Move mode, as made functional in this pr:
https://github.com/RPCS3/rpcs3/pull/6596#issuecomment-599226159

Confirmed by other users.

No input detected from left click:
![2020-03-15 11_39_01-FPS_ 60 59 _ Vulkan _ 0 0 9-9929 _ TIME CRISIS_ RAZING STORM  BLUS30528](https://user-images.githubusercontent.com/20983844/76708158-f55d5300-66b1-11ea-8f2e-450255610894.png)

![2020-03-15 11_41_06-RPCS3 0 0 9-9929-d25ba03e Alpha](https://user-images.githubusercontent.com/20983844/76708161-fbebca80-66b1-11ea-825e-550b48c68aed.png)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4334846/RPCS3.zip)

**Comment by Zangetsu38** [comment]
other button works ?

**Comment by legend800** [comment]
Right works

**Comment by Zangetsu38** [comment]
strange 🤔  you know wjhat commit have get this regression .?

**Comment by legend800** [comment]
No not sure, was reported by another user first, was working a couple months ago fine

**Comment by Zangetsu38** [comment]
need found exactly PR get this reggression

**Comment by legend800** [comment]
@Megamouse Confirmed fix, thanks! 

While you're in that section of code, I logged the remaining (known) issue with the emulated ps move implementation here if interested:  https://github.com/RPCS3/rpcs3/issues/7840

**Comment by dudesh34** [comment]
There is a regression in time crisis 4. "psmove mode" not work with it anymore.

**Comment by legend800** [comment]
It works fine, I tested yesterday, something on your end.

**Comment by dudesh34** [comment]
> It works fine, I tested yesterday, something on your end
you are right, just to clarify why it didnt work for me.
Time Crisis 4 is the only game you must select to use "motion controller no 7"  manually in game settings, it doesnt select it auto like in razing storm, so thats why it didnt work for me.
im sure this info will help other people:)
