### ISSUE TITLE
[0x6bab434]} RSX: Could not gather all required slices for cubemap/3d generation

### ISSUE THREAD

**Issue by SteveChomu** [RPCS3/rpcs3#7791]
## Quick summary
[0x6bab434]} RSX: Could not gather all required slices for cubemap/3d generation
E {RSX [0x6c29a7c]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300FD0

GAMES ARE RUNNING WITH GLITCHED TEXTURE and In menu sometimes games gets 0.50 or 1 fps 

LOG
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4343476/RPCS3.log.gz)

AMD RYGEN 3550H
NVIDIA GTX1650 4GB DDR5
8 GB RAM 2400MHZ
WINDOWS 10 64 BIT

**Comment by kd-11** [comment]
This report is not about booting an actual game. Seems to be an attempt to boot VSH which is currently not supported.

**Comment by AniLeo** [comment]
There's a WWE game boot down the log

**Comment by kd-11** [comment]
Then we ought to at least get a clean log. It's not possible to easily handle a log file with multiple game boots in it.

**Comment by kd-11** [comment]
Also ticket should be renamed, the problems mentioned here are cause by emu deadlock evasion and may have nothing to do with RSX.

**Comment by sirdanielk** [comment]
Any estimate when vsh will run on official build?

**Comment by cbull564** [comment]
Was there a resolution to this issue? I've had the same problem when attempting to run All Pro 2008 on the new PS# emulator.

**Comment by jacob1218** [comment]
MLB 2k12 has this same issue, log attached 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4746413/RPCS3.log.gz)

**Comment by Megamouse** [comment]
this issue is super old and unspecific.
@kd-11 is it even worth keeping?

**Comment by kd-11** [comment]
No point in keeping it open.
