### ISSUE TITLE
[BLES02997] Borderlands: The Pre-Sequel - Unknown stencil op

### ISSUE THREAD

**Issue by dyno0** [RPCS3/rpcs3#7794]
Instead of fifo desyncs, it now crashes with this message:

```
 Thread terminated due to fatal error: Unknown stencil op 0x8180
 (in file C:\projects\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:695)
```

First time getting an error like this, ever.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4346248/RPCS3.log.gz)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/8479
