### ISSUE TITLE
i5 dual core & HD Graphics 520 (linux crash error)

### ISSUE THREAD

**Issue by realnyym** [RPCS3/rpcs3#7795]
(I'm afraid I don't know how to generate a log file)

I've been using Ubuntu 19.10 OS to run many of my playable and trusty games. But since a few RPCS3 builds ago, I've been unable to run most of my trustworthy games, for I'm always getting a crashing error whenever I attempt to select the auto anti-aliasing option from GPU settings along with Vulkan renderer. I should point out I'm currently on a 64x architecture, limited to a dual core I5 processor and an integrated HD graphics-6200U. Terminal reads:

Debugger: 0
Thread '' terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Requested feature not available (VK_ERROR_FEATURE_NOT_PRESENT)
(in file ../rpcs3/Emu/RSX/VK/VKHelpers.h:913)
RPCS3: Assertion Failed! Vulkan API call failed with unrecoverable error: Requested feature not available (VK_ERROR_FEATURE_NOT_PRESENT)
(in file ../rpcs3/Emu/RSX/VK/VKHelpers.h:913)
posix_spawn() failed: 2
Aborted (core dumped)

I'm quite a newbie on the matters of this website, so I would appreciate any kind of aid.

## Quick summary
Please summarize the issue here

## Details
Please provide as much detail as you can here, including
- expected (real hw) and observed (emulator) behavior
- full logs (not from UI)
- back traces (for hard crashes)
- screenshots, Renderdoc, and RSX captures (for visual issues)
- your system configuration (OS, CPU, GPU, driver versions, etc)
- anything else you deem to be important

**Comment by AniLeo** [comment]
You have to disable MSAA. That is a driver issue.
