### ISSUE TITLE
"Enable Thread Scheduler" option does not work properly

### ISSUE THREAD

**Issue by conkis1** [RPCS3/rpcs3#7803]
First, I apologize for my English. It is not my mother tongue although I will try to be clear.

I think that "Enable Thread Scheduler " option does not work correctly in the current version of windows...I earn a lot of performance deactivating it in rpcs3.

GOW III 

Thread Scheduler DISABLED
![1](https://user-images.githubusercontent.com/62382999/77063994-eabafa80-69de-11ea-98c1-a4bbc2ba6ae6.png)

Thread Scheduler Enabled 

![2](https://user-images.githubusercontent.com/62382999/77064070-0c1be680-69df-11ea-8152-a8546b14cf80.png)

There are other examples, like The last of Us, where performance is better with the option turned off..
I hope this can help, if you need more information let me know.

My PC 

Ryzen 2700 (All cores OC 3900 )
16 Gb DDR4 3200
MSI Gtx 1060 6 Gb 
Driver 442.50
Wndows 10 ver. 1909

rpcs3 0.0.9 9947

**Comment by Zangetsu38** [comment]
is not issue, depending game, on feqw game is better disable it

**Comment by AniLeo** [comment]
It's not an issue, you're generally supposed to let the OS handle it. That's for older Windows versions where it didn't handle it correctly.

**Comment by conkis1** [comment]
ook. sorry and thanks you
