### ISSUE TITLE
Katamari Forever [BLES00658] " SYS: 'sys_fs_open' failed with 0x80010006".

### ISSUE THREAD

**Issue by hehehehehexd** [RPCS3/rpcs3#7804]
## Quick summary
Trying to play Katamari Forever [BLES00658] and after selecting a save file the game goes black screen and I get the error " SYS: 'sys_fs_open' failed with 0x80010006". The main 'new game' menu runs fine at 30fps and the game still clocks 30fps on the black screen. Im assuming this is a save file issue?

## Details
RPCS3 v0.0.9-9958-fd8cda0f Alpha | HEAD | FW 4.85 | Windows 10 1903
Intel Core i7-4790 | 8 Threads | 15.94 GiB RAM | AVX+
GPU: GeForce GTX 960 (441.66)

**Comment by RainbowCookie32** [comment]
Missing a log file from a run with the issue

**Comment by dio-gh** [comment]
Not a corrupted save, was tested with a fresh clean save too. See in #help starting from [here.](https://discordapp.com/channels/272035812277878785/277227681836302338/690326614806102087)

**Comment by hehehehehexd** [comment]
Sorry, heres the log. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4357303/RPCS3.log.gz)

**Comment by hehehehehexd** [comment]
FIXED IT. Just have to hit START when the game goes black screen for whatever reason.

**Comment by hehehehehexd** [comment]
Ran into another issue where after the tutorial I get another black screen, but this time with a loading mushroom in the bottom right.
E {PPU[0x1000010] Thread (_libsail-source_fs) [0x00af2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Movie/OsEn/MAIN_02.pam” [1] x3014

**Comment by hehehehehexd** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4357881/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Corrupted dump, not an issue with the emulator.

**Comment by abood1996-q** [comment]
SYS: 'sys_fs_open' failed with 0x80010006.
god of war 
please help me with these issue

**Comment by Mrelliot11** [comment]
I figured out a fix for this, cause I had the same problem. If you rename the PS3_GAME > USRDIR > Movie > OsFn folder to OsEn, it fixes it. It is trying to pull english movies for the game scenes but this is a french rip, so renaming the folder makes the emulator pull it correctly (although all the scenes will be in french).
