### ISSUE TITLE
Nier [BLUS30481] RSX: CB chain has run out of free entries!

### ISSUE THREAD

**Issue by daniel-fs** [RPCS3/rpcs3#7806]
Hi there.

I'm not sure if this is happening with other games, but when playing Nier I get seemingly random freezes which force me to quit the game.

This seems like a thread deadlock, similar to what was happening in #7427, but I'm still getting this error even with Multithreaded RSX disabled. In my case, it also seems unrelated with opening Grimoire Weiss/merchant menus. Sometimes I get the freezes without ever opening them. The last messages are something similar to:

`·E 2:47:20.769835 {PPU[0x1000000] Thread (main_thread) [0x00f66014]} RSX: [vulkan] vk::wait_for_event has timed out!
·E 2:47:20.771007 {RSX [0x0286264]} RSX: CB chain has run out of free entries!
·E 2:47:22.771032 {PPU[0x1000000] Thread (main_thread) [0x00f66038]} RSX: [vulkan] vk::wait_for_event has timed out!
·W 2:47:22.771477 {PPU[0x1000000] Thread (main_thread) [0x04b70688]} cellSysutil: cellVideoOutGetNumberOfDevice(videoOut=0)
·W 2:47:22.771486 {PPU[0x1000000] Thread (main_thread) [0x04b70660]} cellSysutil: cellVideoOutGetNumberOfDevice(videoOut=0)
·E 2:47:22.782879 {RSX [0x02d3d1c]} RSX: CB chain has run out of free entries!
·E 2:47:22.782929 {RSX [0x02d41b4]} RSX: CB chain has run out of free entries!
·E 2:47:22.787496 {RSX [0x02df0d8]} RSX: CB chain has run out of free entries!`

There really isn't a method to replicate the freeze. Yesterday I was getting it every 15-20 minutes, today I played nearly 2 hours until I got it.

I find that clearing the shaders cache before starting the game usually helps a bit, but I'm not sure if this is some sort of placebo or not... just that every time I do that, the game seems to last longer.

I can only test with Vulkan as OpenGL doesn't work for me for some reason. Changing emulator settings has no effect either. I don't think any recent version of RPCS3 broke as I've been having this issue since I started playing 1 week ago or so.

Attached is the log for further info. The log was too large to be uploaded, so I put only the initial part which shows system info and the last lines which show the freeze.

I also attached the log for OpenGL, the game freezes during the loading screen after selecting a save. This may be a problem with my Intel GPU and not RPCS3 however... still, it's there in case anyone wants to take a look.

If you need any other info let me know.

## Details
RPCS3 v0.0.9-9958-fd8cda0f
OS: Windows 10 64-bit
CPU: Intel Core i5-9300h
GPU: Intel UHD 630
RAM: 16 GB

[RPCS3_opengl.log](https://github.com/RPCS3/rpcs3/files/4357449/RPCS3_opengl.log)
[RPCS3_vulkan.log](https://github.com/RPCS3/rpcs3/files/4357455/RPCS3_vulkan.log)

**Comment by kd-11** [comment]
In this case the gpu is hung. It's actually unrelated to the other issue. Same superficial symptom, different cause.

**Comment by daniel-fs** [comment]
> In this case the gpu is hung. It's actually unrelated to the other issue. Same superficial symptom, different cause.

I see, thanks for the reply. Some areas of the game seem more prone to it (perhaps the more demanding areas for the GPU?), but otherwise the freezes aren't that frustrating if I'm lucky and the game can keep running for long. Hope it gets a fix soon :)

**Comment by kd-11** [comment]
Unfortunately with intel its a gamble if the application is at fault or the driver. I'll leave it open just in case I find something.

**Comment by benderscruffy** [comment]
please close due to inactivity
