### ISSUE TITLE
Nier [BLUS30481] P-33 boss disappears

### ISSUE THREAD

**Issue by lwrand** [RPCS3/rpcs3#7811]
During the fight vs P-33 (boss) in Heap Junk, after he is able to fly around, you get to the point where he vanishes from the screen and there is no way to move on.
Here you can check his health when he vanished during one of my multiple tries: https://i.imgur.com/vGOQwOp.jpg
I also posted this issue in the forum: https://forums.rpcs3.net/thread-181086-post-309370.html#pid309370
What I noticed, by using the homing magic (Dark Blast), is that the boss seems to be below the platform or behind one of the two unreachable doors. 

RPCS3 compressed log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4361947/RPCS3.log.gz)
System Information: [System_Information.txt](https://github.com/RPCS3/rpcs3/files/4361952/System_Information.txt)

Hope it helps, 
/lwrand.

**Comment by Whatcookie** [comment]
I fixed this issue in https://github.com/RPCS3/rpcs3/pull/7798. You'll need to clear your PPU cache to fix it though. 

Note that PPU compilation is broken as of https://github.com/RPCS3/rpcs3/pull/7810

**Comment by AniLeo** [comment]
Closing as already fixed
