### ISSUE TITLE
Thread terminate due to fatal error

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#7815]
Windows 10
9990KF with Nvidia GeForrce 1080

I can't launch a game anymore.

Each time I try, I have the msg 'F {PPU[0x1000000] Thread (main_thread) [0x019444e0]} sig_log: Thread terminated due to fatal error: Null function
(in file C:\projects\rpcs3\Utilities\JIT.cpp:570)' but the emulator still running.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4362720/RPCS3.log.gz)

**Comment by DwarvenNexus** [comment]
I am also having this issue, 
E {PPU[0x1000000] Thread (main_thread)} JIT: LLVM: Linkage failed: __0x100011bb4
F {PPU[0x1000000] Thread (main_thread) [0x016344e0]} sig_log: Thread terminated due to fatal error: Null function
(in file C:\projects\rpcs3\Utilities\JIT.cpp:570)
is there a fix for this?

**Comment by AniLeo** [comment]
Clear all PPU caches and retry, with latest build. Don't think this is an issue anymore, you just have bad caches.

**Comment by Pouncha** [comment]
I made new PPU files with a new RPCS3 folder (included new installation of the firmware)
Same issues

**Comment by Pouncha** [comment]
moved to #7829

**Comment by redisdwarf** [comment]
Hello, i've got the same problem only with the game Tekken Tag Tournament 2 since an update in 2020.
I tried to clear all caches especially PPU, update the bios to the last version, to reinstall RPCS3, to reinstall Windows but it I meet the same issue.
