### ISSUE TITLE
PC freezes completely trying to compile opengl shaders for Killzone 2

### ISSUE THREAD

**Issue by ank81** [RPCS3/rpcs3#7817]
Hi,

I am not following the emulator development too closely, but do download and try it occassionaly. Today I downloaded rpcs3-v0.0.9-9965-49d8731c_win64 and noticed that windows would freeze completely trying to compile opengl shaders for Killzone 2. Vulkan is ok, but is still stuck with various rendering bugs. My system is:

Windows 7 64
Ryzen 1600X
A320 based Motherboard
32GB DDR4 3000
RX570 4GB

PS3 FW 4.83

------------

It happened twice in a row when I tried running the game, required hard resetting the pc. But the 3rd time it got into the game alright. At any rate I don't recall rpcs3 freezing the pc before though.

**Comment by kd-11** [comment]
Unfortunately that is a bug that should be reported to the driver manufacturer and/or microsoft. An application compiling a shader, no matter how bad or broken, should not kill your operating system. I have a somewhat similar setup, I'll try and reproduce for a bug report.

**Comment by ank81** [comment]
I am just letting you guys know, since I haven't seen anything like this happen in the past. I haven't update my driver's in at least half year, certainly not since the last time I tried rpcs3. It's not much of an issue, but like I said, juts letting you know in case you may have changed something with your shader compiler bits and know what could be the cause.

**Comment by AniLeo** [comment]
If you haven't updated your drivers in a long time then it isn't a valid issue, you need to test on the latest GPU drivers

**Comment by kd-11** [comment]
I confirmed this issue with adrenalin 20.2.2. Either way, not our bug to fix, I'll file a report with AMD.

**Comment by ank81** [comment]
I have driver version 19.3.2 from March 2019.
