### ISSUE TITLE
RESIDENT EVIL 6 [BLUS30855] Whenever a box is broken, it will crash 

### ISSUE THREAD

**Issue by zombie167** [RPCS3/rpcs3#7819]
The problem happened in the first chapter of Chris and Piers.When the character enters the tenement, each time Chris breaks a box or uses a heavy weapon to cause an explosion, it must cause a crash with an error message "{ppu[0x100001f] Thread (physics[main])0x00ecaf44} VM: Access violation reading location 0x030 (unmapped memory)" This kind of error message seems to be familiar with the error message from the TLoU "Thread (highCellSpursKernel3) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)

![sshot-23](https://user-images.githubusercontent.com/22722505/77229267-e271e380-6bc7-11ea-8f89-454a80ef92be.jpg)

![sshot-64](https://user-images.githubusercontent.com/22722505/77229268-e3a31080-6bc7-11ea-8429-3d19017876ac.jpg)

[log.zip](https://github.com/RPCS3/rpcs3/files/4363151/log.zip)

**Comment by elad335** [comment]
Have you tried ppu precise interpreter + spul llvm + accurate xfloat on?

**Comment by zombie167** [comment]
> Have you tried ppu precise interpreter + spul llvm + accurate xfloat on?


Sorry for replying so late.I have tested it but the result is still the same

**Comment by Realmantik** [comment]
What about OpenGL, Force CPU Blit settings?

**Comment by digitaldude555** [comment]
![Screenshot (302)](https://user-images.githubusercontent.com/26138653/106278394-5434a800-6243-11eb-9663-911c48bdde04.png)
Boxes can be broken without crash now.

**Comment by Yahfz** [comment]
closing as fixed
