### ISSUE TITLE
vulkan-1.dll

### ISSUE THREAD

**Issue by pslaet** [RPCS3/rpcs3#7821]
cannot install the RPCS3 emulator because it gave the following error:

 rpcs3.exe - System error
Code execution cannot continue because vulkan-1.d11 was not found. Reinstalling the program to correct the problem.

(sorry if i wrote something wrong i'm brazilian)

**Comment by pslaet** [comment]
please help

**Comment by AniLeo** [comment]
Thanks for reading and following the issue tracker guidelines.
