### ISSUE TITLE
[Regression] Since PR #7758 Uncharted: Drake's Fortune no longer goes ingame 

### ISSUE THREAD

**Issue by TigiHof** [RPCS3/rpcs3#7828]
Since pull request #7758 Uncharted: Drake's Fortune no longer goes ingame.

Error message:
{SPU[0x3000100] Thread (CellSpursKernel3) [0x0422c]} sig_log: Thread terminated due to fatal error: Unknown STOP code: 0x3fff (Out_MBox is empty)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4365478/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1070
i7-6700k @ 4GHZ
16GB RAM

**Comment by elad335** [comment]
Hello, can you try running the game 5 times more to confirm this?

**Comment by TigiHof** [comment]
Thanks for the hint! Hmm, strange. I got this error with every update in the last couple of days, but I always tried it only once. Just tested it a couple of times with the latest build and sometimes the error occurs before I can go ingame (as reported), sometimes after a couple of seconds ingame.

**Comment by elad335** [comment]
And try playing with driver wake-up delay as well.

**Comment by AniLeo** [comment]
Closing since Uncharted is working fine
