### ISSUE TITLE
Mobile Suit Gundam Senki [BLJS10050] PR7784  Lines appear instead of the exhaust smoke from the turbine of the mobile suit.

### ISSUE THREAD

**Issue by Shuneferus** [RPCS3/rpcs3#7830]
Mobile Suit Gundam Senki [BLJS10050]
Hello KD-11 from this pr horizontal lines appear instead of the exhaust smoke from the turbine of the mobile suit.
Image is attached.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4366233/RPCS3.log)

![PR7784](https://user-images.githubusercontent.com/61365901/77258878-4fcf5400-6c5c-11ea-8315-716d48f57a6a.png)

**Comment by kd-11** [comment]
Hi, which PR exactly caused the regression?

**Comment by Shuneferus** [comment]
Hello Kd-11 this regression started from
do pr vk: Lazy evaluate renderpass scope # 7784 0.0.9-9929.

Em ter., 31 de mar. de 2020 às 07:51, kd-11 <notifications@github.com>
escreveu:

**Comment by kd-11** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/8563

**Comment by kd-11** [comment]
@Shuneferus Please provide RSX capture files.

**Comment by Shuneferus** [comment]
![1](https://user-images.githubusercontent.com/61365901/86980491-52e24780-c15a-11ea-9461-daa6585feb34.png)
![2](https://user-images.githubusercontent.com/61365901/86980545-75746080-c15a-11ea-83f6-6987d404da9f.png)
![3](https://user-images.githubusercontent.com/61365901/86980602-96d54c80-c15a-11ea-9b58-dda3a1499722.png)


Hello kd11 follows the captures you requested, please note the correct smoke effect in image 3.

**Comment by kd-11** [comment]
@Shuneferus While the glitch is present on-screen click on Utilities->"Create RSX Capture". A file will be created in the "captures" directory, zip it and attach to the report.

**Comment by Shuneferus** [comment]
Hello KD-11 the capture that you requested was 700MB, I compressed the
file to 234MB and I'm sending it as an attachment.

Em qui., 9 de jul. de 2020 às 12:26, kd-11 <notifications@github.com>
escreveu:

**Comment by dio-gh** [comment]
Email attachments dont really come through. Upload it to google drive or similar please, so that he can use it.

**Comment by Shuneferus** [comment]
Hello KD-11 follow the link to download rsx capture. A hug.


https://drive.google.com/file/d/1NXZdn-b8CjiQVxFgvHwxqhck7O06CmB1/view?usp=sharing

Em qui., 9 de jul. de 2020 às 12:26, kd-11 <notifications@github.com>
escreveu:

**Comment by Shuneferus** [comment]
Thanks for the tip dio-gh. A hug.

**Comment by kd-11** [comment]
I'm unable to reproduce this issue to debug, provide save files and instructions on how to load them.
![image](https://user-images.githubusercontent.com/15904127/87241659-09317f80-c42e-11ea-9d44-4277b3594299.png)

**Comment by Shuneferus** [comment]
save:
https://drive.google.com/drive/folders/1alk3L2Z2_41etdxrVWkrS7czKQ2n0e9u?usp=sharing

Hello KD-11 follows the game's save link.
When starting the game go to "free mission" / "offline mode" / Mission /
Choose the fourth stage from below "HLV6500Points" / Click on Mission Start
".
The bug occurs when the robot (Mobile Suit) moves using the turbines by
pressing the x once quickly and then in sequence holding it constantly
(Dash) when using the camera on the right lever (R3) that controls the
camera the bug always occurs in oblique angles .

Em dom., 12 de jul. de 2020 às 04:54, kd-11 <notifications@github.com>
escreveu:

**Comment by kd-11** [comment]
I am still unable to reproduce this locally. I've tried many things, the image is still correct when dashing. The game has other visual problems with image stability but that is unrelated. No horizontal lines noted. GPUs tested GTX 1050ti and RX470.
I have the exact same GPU driver, only difference is windows 10 build (18362 vs 19041) and GPU model. Unfortunately with cache control issues, I have to observe it happening to come up with a solution and any driver-level captures made on an affected system will just play back correctly on my system so this one I cannot fix at the moment.

**Comment by Shuneferus** [comment]
Hello KD-11, I appreciate all your efforts. In the future when I take a
new look at the problem I am available to help with some information.
If it is corrected by any driver or version of the operating system I will
let you know.
Congratulations for the quality and professionalism in the management of
this excellent emulator.
A hug.

Em seg., 13 de jul. de 2020 às 14:46, kd-11 <notifications@github.com>
escreveu:

**Comment by Shuneferus** [comment]
![rpcs3_2020_09_13_00_47_18_474](https://user-images.githubusercontent.com/61365901/93009950-1d444b00-f55d-11ea-882e-d51d2e4baa9b.jpg)

![rpcs3_2020_09_13_00_47_21_941](https://user-images.githubusercontent.com/61365901/93009989-9d6ab080-f55d-11ea-8fb1-ea79a38964ee.jpg)
![rpcs3_2020_09_13_00_47_22_741](https://user-images.githubusercontent.com/61365901/93010030-2b469b80-f55e-11ea-907d-d974f738847d.jpg)



Mobile Suit Gundam Senki [BLJS10050]

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5213599/RPCS3.log)

 Hello KD-11 I believe that this problem may be related to the resolution scale because when increasing the scale from 150 to 300 the lines become more apparent. (On scale 100, the error occurs more with less intensity)
 When reporting the first time I had not noticed the mirrored reflections
that occur when driving the turbines when playing in a low light stage (Moon / Space in the Game).
 I kindly ask you to analyze the attached images to see if you have any idea of the source of the error.
 A hug.

**Comment by kd-11** [comment]
Re-ran the tests again, I still cannot reproduce this issue (added RDNA2 GPU to the testing pool)
As with before, there are other problems with image stability, but nothing like reported in this ticket.

**Comment by Megamouse** [comment]
No kanna reproduce either
