### ISSUE TITLE
Silent Hill Downpour freeze after credits.

### ISSUE THREAD

**Issue by Anthony16End** [RPCS3/rpcs3#7848]
Hi, I have played Silent Hill Downpour from start till the end but, in every method and with many configuration (tried OpenGL, Vulkan etc.), if I press circle to close/skip the final credits the game freezes and I have to close the emulator from the task manager. No way to return to the main menu after finished the game.
I attach a part of the LOG when the emulator freezes.
[Downpour Credits Freeze RPCS3 LOG.txt](https://github.com/RPCS3/rpcs3/files/4375219/Downpour.Credits.Freeze.RPCS3.LOG.txt)

**Comment by AniLeo** [comment]
Missing log file and system specs

**Comment by digitaldude555** [comment]
@Anthony16End retest

**Comment by Megamouse** [comment]
Probably related to this:

E {PPU[0x1000000] Thread (main_thread) [0x01e35848]} LDR: SELF: Failed to decrypt metadata info!
E {PPU[0x1000000] Thread (main_thread) [0x01e35848]} LDR: SELF: Failed to load SELF file metadata!
E {PPU[0x1000000] Thread (main_thread) [0x01e35848]} sceNp: npDrmIsAvailable(): Failed to verify sce file /dev_hdd0/game/BLUS30565/USRDIR/SHGAME.SELF

**Comment by Megamouse** [comment]
Retest

**Comment by Megamouse** [comment]
I feel like this isn't getting us nowhere

**Comment by boozezela** [comment]
Hi.

For what is worth, this is the excerpt from the log from when the last cutscene finishes playing to when the game crashing upon pressing circle while the credits are running (as you can see, I am booting from a savestate).

I am using a default configuration and no patches. I also tried to enable LLE versions of the libsysutil_np* libraries one at the time, and the game still crashed. 

```
- {Emu State Load Thread: ''} RSX: Found Vulkan-compatible GPU: 'AMD Radeon RX 640 (RADV POLARIS12)' running on driver 23.99.99
- {Emu State Load Thread: ''} RSX: Found Vulkan-compatible GPU: 'llvmpipe (LLVM 17.0.6, 256 bits)' running on driver 0.0.1
- {Emu State Load Thread: ''} RSX: Found Vulkan-compatible GPU: 'Intel(R) UHD Graphics 630 (CML GT2)' running on driver 23.99.99
E {Emu State Load Thread: ''} RSX: AMDGPU kernel driver on Linux and INTEL driver on some platforms cannot support passthrough DMA buffers.
E {RSX [0x011d254]} RSX: set_memory_flags(0xc0840000, 0xc0bc3fff, 1): region_ptr == nullptr
E {PPU[0x1000012] Thread (TrophyInfo) [HLE:0x01e3659c, LR:0x018205e8]} SYS: 'sceNpTrophyUnlockTrophy' failed with 0x80022915 : SCE_NP_TROPHY_ERROR_ALREADY_UNLOCKED [1]
E {PPU[0x1000012] Thread (TrophyInfo) [HLE:0x01e365dc, LR:0x01820700]} SYS: 'sceNpTrophyGetTrophyInfo' failed with 0x80022913 : SCE_NP_TROPHY_ERROR_HIDDEN [1]
E {PPU[0x100000e] Thread (fios mediathread 5) [libfs: 0x02101ee4]} sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/INSTALL/___LOCK” [1]
E {PPU[0x100000e] Thread (fios mediathread 5) [libfs: 0x02101ee4]} sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/___LOCK” [1]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x01e35d64, LR:0x018203b8]} SELF: Failed to decrypt SELF metadata info!
E {PPU[0x1000000] Thread (main_thread) [HLE:0x01e35d64, LR:0x018203b8]} SELF: Failed to load SELF file metadata!
E {PPU[0x1000000] Thread (main_thread) [HLE:0x01e35d64, LR:0x018203b8]} sceNp: npDrmIsAvailable(): Failed to verify sce file “/dev_hdd0/game/BLUS30565/USRDIR/SHGAME.SELF”
E {PPU[0x1000000] Thread (main_thread) [HLE:0x01e35d64, LR:0x018203b8]} SYS: 'sceNpDrmProcessExitSpawn2' failed with 0x80029513 : SCE_NP_DRM_ERROR_NO_ENTITLEMENT, /dev_hdd0/game/BLUS30565/USRDIR/SHGAME.SELF [1]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x01e35d64, LR:0x018203b8]} SYS: 'sceNpDrmProcessExitSpawn2' failed with 0x80029513 : 0x80029513 [1]
F {PPU[0x1000000] Thread (main_thread) [0x0074c908]} SIG: Thread terminated due to fatal error: PPU Trap! Sometimes tweaking the setting "Stub PPU Traps" can be a workaround to this crash.
Best values depend on game code, if unsure try 1.
(in file /rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:2782[:3], in function ppu_trap) (errno=22=Invalid argument)
``` 

System configuration:
RPCS3 vrpcs3-v0.0.30-15918-74e084c8 | FW 4.90 | Fedora 39 | Intel i7-10700K 8 Core / 16 Threads | 16 GB RAM | AMD RADEON RX550 4GB

I am happy to test again incresing the verbosity to Trace if needed.
