### ISSUE TITLE
RPCS3 doesnt start if vulkan-1.dll is missing.

### ISSUE THREAD

**Issue by r9guy** [RPCS3/rpcs3#7852]
## Quick summary
RPCS3 doesnt start if vulkan-1.dll is missing.

## Details
on older graphics accelerator where vulkan is not supported but OpenGL is, emulator is not starting. 
in my case it's 
Processor	Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz, 1801 Mhz, 2 Core(s), 4 Logical Processor(s).
it's pretty old and I do not expect to actually play anything on it. but the problem illustrates that rpcs3 is hard coded to rely on vulkan.

**Comment by MSuih** [comment]
Related to #5953

You can get past this error by installing [Vulkan runtime](https://vulkan.lunarg.com/sdk/home), but keep in mind that the integrated GPU on 3337u is not compatible with OpenGL 4.3 and thus your only option is to use null renderer.

**Comment by r9guy** [comment]
I agree, thus my intention with submitting this issue was not to ask a support for GPU, but improve feature detection. should I have seen #5953 I wouldn't open duplicate.
