### ISSUE TITLE
PPU LLVM: Unsupported relocation 5

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#7855]
Trying to boot psp_emulator.self in the firmware (which doesn't work on RPCS3 right now) will hit this unimplemented relocation.

Mount host_root needs to be enabled in order to boot this self.

`Unsupported relocation(5) in 'PEmuCoreLib.sprx'. Please report.`

**Comment by elad335** [comment]
Send log with #7859

**Comment by AniLeo** [comment]
You can boot self on dev_flash/pspemu/psp_emulator.self with host_root enabled, otherwise I'll be able to test in a few hours

**Comment by xddxd** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4386830/RPCS3.log)

**Comment by Nekotekina** [comment]
It's in ADDIS instruction. May be a trivial fix.

**Comment by elad335** [comment]
Any update?

**Comment by xddxd** [comment]
From the look of it the .self boots properly now, but doesn't do anything since there is no game.

**Comment by MSuih** [comment]
After #7857 it should be possible to attempt booting games.

**Comment by AniLeo** [comment]
Closing as implemented, emulator doesn't hard crash anymore when booting a game through pspemu on LLVM
