### ISSUE TITLE
Armored core 4 (fatal error: Unknown stencil op 0x6)

### ISSUE THREAD

**Issue by dulsan** [RPCS3/rpcs3#7856]
## Quick summary
Upon loading into the tutorial, the player cannot interact with the target object, after exiting the tutorial and selecting the craft, the game hangs in the loading screen with this problem in the console:

F` 0:08:03.641753 {RSX [0x0030438]} sig_log: Thread terminated due to fatal error: Unknown stencil op 0x6
(in file `C:\projects\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:695)

I have also noticed that the player character is hovering (using thrusts), this should only happen when the character is above water. The character should be running not hovering.  Therefore, i believe the collision is still an issue in the game

This is how it should run:
[https://www.youtube.com/watch?v=LFJhWPSADFE]

## Details

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4384489/RPCS3.log)

*There might be other issue requests made by others that talk about the same issue. But, they are closed so, i opened a new one.

**Comment by AniLeo** [comment]
Requesting triaging from @kd-11 on this one

**Comment by kd-11** [comment]
I wasn't sure if it could be a desync or not, likely ignored by realhw. I'll have to run a hwtest on it.

**Comment by dulsan** [comment]
Is it possible to test using TSX? I heard that some people had successful runs on ACFA. I don't have a CPU that supports TSX.
