### ISSUE TITLE
Windows build 0.0.9-10029 shipped with debug Qt libs instead of release

### ISSUE THREAD

**Issue by ooa113y** [RPCS3/rpcs3#7864]
...and the executable is looking for release ones and not starting. Previous build is fine.

**Comment by AniLeo** [comment]
Build marked as broken, website now shows 10023

Tagging @Nekotekina to fix

**Comment by AniLeo** [comment]
Should be fixed, retest

**Comment by AniLeo** [comment]
Closing as fixed, ping if you still can reproduce on latest master
