### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by acidviews** [RPCS3/rpcs3#7867]
Hi I'm loving it so far works quite well just wanted to say thanx a lot
Anyway, I been playing diablo 3 ROS
Had it running very well been playing for hours with no crashes,
anyway I got a fatal error blah blah thought it let u know
I updated to the latest before it happened.

win 10 build 18363
ryzen 5 1600
rx 480
16gb ram

it wont let me upload a png so ill try an type it
Unhandled win32 exception0xcOOOOOOO5
Segfault reading location ffffffffff at 00000000005803a35f
emu thread name: 'PPU[0x1000000] Thread (main thread)
Thread id = 9128
instruction address 000000005803a35f
rpcs3 image base : 0000000000100000.

Thanks :)

**Comment by AniLeo** [comment]
Missing log file, steps to reproduce the crash

**Comment by acidviews** [comment]
ill email you ty

**Comment by RainbowCookie32** [comment]
Post them here, don't mail staff with it

**Comment by AniLeo** [comment]
Closing for lack of issue update
