### ISSUE TITLE
Emulation speed issues not using useplatformclock

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#7889]
When not using useplatformclock emulation speed is more slow than enabling useplatformclock.
With useplatformclock disabled the emulator not is using totally the cpu cores and GPU GT 640 temperature is high with less FPS than if enabling useplatformclock.

Starting Tekken 6 or Fist of North Star Ken's Rage 2 using ASMJIT or LLVM is the same result.
Disabled useplatformclock
CPU cores not are used totally all time and frame rate 24 to 50 FPS with GPU 80 % being used and 58 ºC.
Enabled useplatformclock
CPU cores are used totally several times and frame rate is 30 to 60 FPS with GPU less of 70 %  used and 52-54 ºC and some moments the GPU clock is lowered to 400 MHZ even rendering correctly all frames.
Several games run much more smooth with enabled useplatformclock
The system is FX-6300 4 GB RAM GT 640 1 GB Windows 10 64 1809.

An other detail is any racing game is extremely slow.
I see videos showing The Last of Us and is how run much more fast than racing games. but The Last of Us use extremely the Cell.
When enabling useplatformclock Motorstorm Pacific Rift run more fast, but detail strange is that games that use much more the SPUs run more fast than racing games.
Have reviews in some site showing enabling useplatformclock will slowdown performance in Zen and current Intel CPUs.
More mess is users enabling useplatformclock to "better GPU performance" saying that help in FPS. Is an big mess in internet about timers.

Here if enabling useplatformclock the emulator run more fast and GPU is less used and rendering more FPS.

I wait only report how the emulator is running in my system.
Have an nice day.

**Comment by lainiwaku** [comment]
i think you mean using HPET  instead of TSC
TSC was already proven better than HPET, but hey im not a dev so...

**Comment by Augusto7743** [comment]
If enabling useplatformclock HPET is used yes is exactly it.
Is an extreme mess the high number of post in internet about timers.
Strange that if enabling useplatformclock here is more fast and the GPU temperature is below of 58 ºC rendering more frames and RPCS3 run more smooth.
I remember enabling useplatformclock in the Windows 10 first version and the performance was extremely slow and now in version 1809 need enable useplatformclock to run more fast.

Have post in internet saying to not enable useplatformclock in Zen and Intel current CPUs.

**Comment by Yahfz** [comment]
This is not an emulator issue. Windows comes with HPET enabled as default for a reason, do not disable it.

**Comment by AniLeo** [comment]
Closing since that's related to Windows, not RPCS3
