### ISSUE TITLE
MSVC + Cmake no longer compiles

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#7892]
When linking, there is a mismatch between static and dynamic libraries. This is a recent issue, probably started with #7853.

```
discord-rpc.lib(discord_rpc.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mocs_compilation.cpp.obj
discord-rpc.lib(serialization.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mocs_compilation.cpp.obj
discord-rpc.lib(rpc_connection.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mocs_compilation.cpp.obj
```

<details>
 <summary>Full error</summary>
LINK: command "C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\rpcs3.dir\objects1.rsp /out:..\bin\rpcs3.exe /implib:rpcs3.lib /pdb:D:\Ohjelmointi\rpcs3\cmake-build-release\bin\rpcs3.pdb /version:0.0 /machine:x64 /NODEFAULTLIB:libc.lib /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libcd.lib /NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:msvcrtd.lib /SUBSYSTEM:WINDOWS /DYNAMICBASE:NO /BASE:0x10000 /FIXED /STACK:8388608,1048576 /INCREMENTAL:NO /subsystem:windows /ignore:4281 Emu\rpcs3_emu.lib rpcs3qt\rpcs3_ui.lib ..\3rdparty\libusb_cmake\libusb-1.0.lib ws2_32.lib Winmm.lib Psapi.lib gdi32.lib setupapi.lib Emu\rpcs3_emu.lib ..\..\rpcs3\..\3rdparty\XAudio2Redist\libs\xaudio2_9redist.lib ..\..\3rdparty\OpenAL\libs\Win64\OpenAL32.lib ..\3rdparty\llvm_build\lib\LLVMMCJIT.lib ..\3rdparty\llvm_build\lib\LLVMExecutionEngine.lib ..\3rdparty\llvm_build\lib\LLVMRuntimeDyld.lib ..\3rdparty\llvm_build\lib\LLVMX86CodeGen.lib ..\3rdparty\llvm_build\lib\LLVMAsmPrinter.lib ..\3rdparty\llvm_build\lib\LLVMDebugInfoDWARF.lib ..\3rdparty\llvm_build\lib\LLVMCFGuard.lib ..\3rdparty\llvm_build\lib\LLVMGlobalISel.lib ..\3rdparty\llvm_build\lib\LLVMSelectionDAG.lib ..\3rdparty\llvm_build\lib\LLVMCodeGen.lib ..\3rdparty\llvm_build\lib\LLVMTarget.lib ..\3rdparty\llvm_build\lib\LLVMBitWriter.lib ..\3rdparty\llvm_build\lib\LLVMScalarOpts.lib ..\3rdparty\llvm_build\lib\LLVMAggressiveInstCombine.lib ..\3rdparty\llvm_build\lib\LLVMInstCombine.lib ..\3rdparty\llvm_build\lib\LLVMTransformUtils.lib ..\3rdparty\llvm_build\lib\LLVMAnalysis.lib ..\3rdparty\llvm_build\lib\LLVMObject.lib ..\3rdparty\llvm_build\lib\LLVMBitReader.lib ..\3rdparty\llvm_build\lib\LLVMTextAPI.lib ..\3rdparty\llvm_build\lib\LLVMProfileData.lib ..\3rdparty\llvm_build\lib\LLVMCore.lib ..\3rdparty\llvm_build\lib\LLVMRemarks.lib ..\3rdparty\llvm_build\lib\LLVMBitstreamReader.lib ..\3rdparty\llvm_build\lib\LLVMX86AsmParser.lib ..\3rdparty\llvm_build\lib\LLVMX86Desc.lib ..\3rdparty\llvm_build\lib\LLVMX86Utils.lib ..\3rdparty\llvm_build\lib\LLVMMCDisassembler.lib ..\3rdparty\llvm_build\lib\LLVMX86Info.lib ..\3rdparty\llvm_build\lib\LLVMMCParser.lib ..\3rdparty\llvm_build\lib\LLVMMC.lib ..\3rdparty\llvm_build\lib\LLVMBinaryFormat.lib ..\3rdparty\llvm_build\lib\LLVMDebugInfoCodeView.lib ..\3rdparty\llvm_build\lib\LLVMDebugInfoMSF.lib ..\3rdparty\llvm_build\lib\LLVMSupport.lib psapi.lib shell32.lib ole32.lib uuid.lib delayimp.lib -delayload:shell32.dll -delayload:ole32.dll ..\3rdparty\llvm_build\lib\LLVMDemangle.lib ..\asmjitsrc\asmjit.lib Bcrypt.lib ..\..\3rdparty\ffmpeg\windows\x86_64\avformat.lib ..\..\3rdparty\ffmpeg\windows\x86_64\avcodec.lib ..\..\3rdparty\ffmpeg\windows\x86_64\avutil.lib ..\..\3rdparty\ffmpeg\windows\x86_64\swscale.lib dxgi.lib d2d1.lib dwrite.lib ..\Vulkan\glslang\SPIRV\SPIRV.lib ..\Vulkan\glslang\glslang\glslang.lib ..\Vulkan\glslang\OGLCompilersDLL\OGLCompiler.lib ..\Vulkan\glslang\glslang\OSDependent\Windows\OSDependent.lib C:\VulkanSDK\1.1.126.0\Lib\vulkan-1.lib ..\3rdparty\xxHash\cmake_unofficial\xxhash.lib ..\..\3rdparty\discord-rpc\lib\discord-rpc.lib C:\Qt\5.15.0\msvc2017_64\lib\Qt5Widgets.lib C:\Qt\5.15.0\msvc2017_64\lib\Qt5WinExtras.lib C:\Qt\5.15.0\msvc2017_64\lib\Qt5Gui.lib C:\Qt\5.15.0\msvc2017_64\lib\Qt5Concurrent.lib C:\Qt\5.15.0\msvc2017_64\lib\Qt5Core.lib C:\Qt\5.15.0\msvc2017_64\lib\qtmain.lib ..\3rdparty\hidapi\windows\hidapi-hid.lib setupapi.lib Shlwapi.lib ..\3rdparty\libusb_cmake\libusb-1.0.lib ..\3rdparty\yaml-cpp\yaml-cpp.lib ..\3rdparty\pugixml\pugixml.lib ..\3rdparty\libpng\libpng16_static.lib ..\3rdparty\zlib\zlibstatic.lib ..\3rdparty\3rdparty_7z.lib ..\3rdparty\curl\lib\libcurl.lib ..\3rdparty\wolfssl\libwolfssl-3.lib winmm.lib ws2_32.lib advapi32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:..\bin\rpcs3.exe.manifest" failed (exit code 1319) with the following output:<br/>
discord-rpc.lib(discord_rpc.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mocs_compilation.cpp.obj<br/>
discord-rpc.lib(serialization.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mocs_compilation.cpp.obj<br/>
discord-rpc.lib(rpc_connection.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mocs_compilation.cpp.obj<br/>
   Creating library rpcs3.lib and object rpcs3.exp<br/>
..\bin\rpcs3.exe : fatal error LNK1319: 3 mismatches detected<br/>
NMAKE : fatal error U1077: '"C:\Program Files\JetBrains\CLion 2019.3\bin\cmake\win\bin\cmake.exe"' : return code '0xffffffff'<br/>
Stop.<br/>
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64\nmake.exe"' : return code '0x2'<br/>
Stop.<br/>
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64\nmake.exe"' : return code '0x2'<br/>
Stop.<br/>
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64\nmake.exe"' : return code '0x2'<br/>
Stop.<br/>
</details>

**Comment by Nekotekina** [comment]
Try to rebuild with latest master

**Comment by MSuih** [comment]
Same error, only change being that it prints `cl : Command line warning D9025 : overriding '/MT' with '/MD'` for every file compiled.

**Comment by dio-gh** [comment]
If you're using prebuilt LLVM and/or glslang, you should update them; see #7872 for details. If you built them yourself, try doing a full clean + rebuild.

Can't repro otherwise, current master compiles for me just fine (with prebuilt llvm and glslang).

**Comment by MSuih** [comment]
Seems to have gotten fixed at some point, not sure how.
