### ISSUE TITLE
Regression huge slowdown between 0.0.9-9952 0.0.9-10057

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#7895]
In 0.0.9-9947 some games run smooth 60 FPS and others an few below of 100 % speed.
In 0.0.9-10057 now some games has huge speed slowdown and not start if using LLVM.
Fist of North Star Ken´s Rage 2 in 0.0.9-9947 run frame rate 45-60 FPS using both ASMJIT or LLVM. Now start only with ASMJIT and the framerate is below of 20 FPS. LLVM start the game, but stop emulation when begin the gameplay.
Motorstorm Pacific Rift is less 20 % speed in 0.0.9-10057 version.
NFS Hot Pursuit is less 10 % speed in 0.0.9-10057 version.
Unhappily I not have time to test what version was the regression.
If my post not was correct to post here excuse me.

**Comment by elad335** [comment]
New rule: no more huge ass build gaps on regression report otherwise closing issue as invalid.

**Comment by Augusto7743** [comment]
My report was only to say that is an huge slowdown in some games between 0.0.9-9952 and 0.0.9-10057 in an FX-6300 4 GB RAM Geforce GT 640 1 GB in Windows 10 1809 64 bits.
If recent changes was for better speed or optimize LLVM is more slow in 6 cores CPU.
I understand that FX6300 not have processing to emulate The Last of Us and I not had that game in my PS3, but for some games is fine and run in full speed in 60 FPS.
FX6300 is eaxctly 6 cores and not 3 cores.
Also if using LLVM an game not more start and other is much more slow.
Fist of the North Star: Ken’s Rage 2 only run if using ASMJIT being much slow and LLVM not begin the gameplay. Before of 0.0.9-9952 LLVM works fine and run between 45-60 FPS.
Need for Speed Hot Pursuit before of 0.0.9-9952 was between 7-11 FPS and in current version is less of 7 FPS.
Ultimate Marvel VS Capcom 3 is much more slow now.
Others games continue running 100 % speed, but using much more CPU than before of 0.0.9-9952. The games are :
Spelunker HD, TMNT: Turtles In Time Re-Shelled, MOTORSTORM PACIFIC RIFT DEMO and perhaps others.

I only wait report about it.
In an current CPU is more hardest to see if have an regression in speed and the FX-6300 and others CPUs is more easy to see if any optimization not is being more fast.
I see some videos showing emulating some games (The Last of US, Dark Souls and others) and look how racing games are more slow to emulate than an game using extremely the Cell.
RSX is totally emulated in CPU or partially and some features are using directly the GPU ?

Excuse me if was wrong to post about it above.
My reply was because AniLeo have posted an message.

**Comment by RainbowCookie32** [comment]
What elad and Ani mean is that you need to shrink the gap between builds, find in which one/s the regression started. Devs have better things to do than try to reproduce a performance regression that occured sometime in a range of almost 100 commits. 
If you have an issue, it's your job when opening it to figure out when it started, as stated in the guidelines.

**Comment by Augusto7743** [comment]
Thanks !
I will test the new current version and if is exactly the same issue when I have enough time I will test previous version to figure the regression.

**Comment by Augusto7743** [comment]
In latest versions the gameplay speed not is being huge slowdown and tested rpcs3-v0.0.9-10120 the speed is more fast than rpcs3-v0.0.9-9952.
Have an recent added code games are loading much more fast even between menus and gameplay.
Any new added code have fixed the huge slowdown.
Have an nice day.

**Comment by AniLeo** [comment]
Closing as reported fixed

**Comment by Augusto7743** [comment]
Thanks.
