### ISSUE TITLE
RSX: Dubious query data pushed to cond render

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#7896]
Hello, when compiling some shaders in RDR BLUS30418, the log gets spammed with
`E {RSX [0x00fa024]} RSX: Dubious query data pushed to cond render!, Please report to developers(q.pending=1)`
the spam stops when the shader gets compiled.
Ryzen 7 2700
RX 580
RPCS3 0.0.9-10068-6d32ebec
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4398891/RPCS3.log.gz)

**Comment by kd-11** [comment]
Its harmess if shaders are compiling. I'll change the error to a warning instead.

**Comment by AniLeo** [comment]
Maybe this can be only logged when shaders are not compiling, this could potentially cause a performance hit on shader compilation even if it's a warning
