### ISSUE TITLE
radv: Remove #7487 workaround

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#7897]
Mesa fixed the issue that caused a performance regression, worked around in RPCS3 on #7487. The source of the issue was a lack of clarification on the Vulkan specification itself, which has also been added as of Vulkan 1.2.134 @ https://github.com/KhronosGroup/Vulkan-Docs/commit/b27536168823d5e8b025fc5622eab7df54008589#diff-267e1eca473d7e2ecbce0bc657a44d37R1465

The bug fix commit has been part of upstream mesa since 20.0.2:
https://gitlab.freedesktop.org/mesa/mesa/-/commit/aa3fe28d05316a83637d8ecca71ed75c6977767f

It has been decided to wait out a few weeks for distros to push the new mesa to their repositories (f. ex: arch's mesa is still on 19.3.4, with 20.0.2 still on Testing) and for users to be able to upgrade

**Comment by AniLeo** [comment]
Ubuntu 20.04 Pre-Release was updated: https://launchpad.net/ubuntu/+source/mesa/20.0.2-1ubuntu1
Arch/Manjaro were updated: https://www.archlinux.org/packages/extra/x86_64/mesa/
openSUSE Tumbleweed was updated: https://software.opensuse.org/package/Mesa
Debian Unstable was updated: https://packages.debian.org/source/unstable/mesa

**Comment by kd-11** [comment]
Noted. Will update.

**Comment by Leopard1907** [comment]
Fwiw , users with Ubuntu 18.04 based distros should be ok too if they use this PPA that Valve maintains. It is on 20.0.2 too.

https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa

**Comment by Cervoxx** [comment]
> Fwiw , users with Ubuntu 18.04 based distros should be ok too if they use this PPA that Valve maintains. It is on 20.0.2 too.
> 
> https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa

If users will be required to update their mesa version, such as ubuntu 18.04 users, to use the application properly it would probably be wise to add a warning in the app to add this ppa and/or make a note about it in the quickstart guide. 

It should be as simple as telling them to:

`sudo add-apt-repository ppa:kisak/kisak-mesa`
`sudo apt upgrade` 
Then reboot.

The [lutris wiki](https://github.com/lutris/lutris/wiki/Installing-drivers) is a good source as well for getting updated video drivers on a linux distribution. 

I wonder if we can bundle the updated mesa with the appimage, or if thats too far fetched.

**Comment by kd-11** [comment]
I have added the fix for this in with another workaround for Nvidia GPUs that I was told was fixed.
