### ISSUE TITLE
Emulator freezes trying to play with two instruments connected

### ISSUE THREAD

**Issue by juangabreil** [RPCS3/rpcs3#7898]
## Quick summary
I'm playing Rock band 2 perfectly with guitar and drums separately. If I connect both at the same time and run the game, it doesn't start-

## Details
Please provide as much detail as you can here, including
Full logs: https://www.dropbox.com/s/njvaqvtd7bqdf5z/logs.zip?dl=0

These are the errors that the log in UI is throwing:

E {PPU[0x1000000] Thread (main_thread) [0x00e202e0]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLES00385”, errDialog=0x0, funcStat=*0xc0f240, container=4294967295)
S {PPU[0x1000000] Thread (main_thread) [0x010509ac]} PPU: LLVM: Loaded module v3-tane-GidnR56pzgun0Z5aqipN0L-000000-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x010509ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libusbd.sprx” (id=0x23007600)
S {PPU[0x1000000] Thread (main_thread) [0x012b6e2c]} sys_usbd: Ldd device matchup for < RockBandGuitar >
S {PPU[0x1000000] Thread (main_thread) [0x012b6e2c]} sys_usbd: Ldd device matchup for  < RockBandDrums >
U {PPU[0x1000000] Thread (main_thread) [0x00e25868]} sceNp TODO: sceNpBasicRegisterHandler(context=*0xd0020640, handler=*0xc10c08, arg=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00e202e0]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLES00385”, errDialog=0x0, funcStat=*0xc0f240, container=4294967295)
E {PPU[0x1000000] Thread (main_thread) [0x00e202e0]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLES00228”, errDialog=0x0, funcStat=*0xc0f240, container=4294967295)
E {PPU[0x1000000] Thread (main_thread) [0x00e202e0]} SYS: 'cellGameDataCheckCreate2' failed with 0x8002b604 : CELL_GAMEDATA_ERROR_PARAM [1]
U {PPU[0x1000000] Thread (main_thread) [0x0104ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0104ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000008] Thread (libusbd_usbd_thread) [0x012b2b44]} sys_usbd TODO: sys_usbd_attach(handle=0x115b) x2

**Comment by juangabreil** [comment]
After the fix, it goes a little bit furhter but then fails again :(

Full log here: https://www.dropbox.com/s/8yul1m3qqk8iv0h/logs-2.zip?dl=0

S {PPU[0x1000000] Thread (main_thread) [0x010509ac]} PPU: LLVM: Loaded module v3-tane-Azvpte0puqKSeF3SPfQ5z5-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x010509ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libhttp.sprx” (id=0x23006b00)
E {PPU[0x1000000] Thread (main_thread) [0x00e202e0]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLES00385”, errDialog=0x0, funcStat=*0xc0f240, container=4294967295)
S {PPU[0x1000000] Thread (main_thread) [0x010509ac]} PPU: LLVM: Loaded module v3-tane-GidnR56pzgun0Z5aqipN0L-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x010509ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libusbd.sprx” (id=0x23007600)
S {PPU[0x1000000] Thread (main_thread) [0x012b6e2c]} sys_usbd: Ldd device matchup for <RockBandGuitar>
S {PPU[0x1000000] Thread (main_thread) [0x012b6e2c]} sys_usbd: Ldd device matchup for <RockBandDrums>
U {PPU[0x1000000] Thread (main_thread) [0x00e25868]} sceNp TODO: sceNpBasicRegisterHandler(context=*0xd0020640, handler=*0xc10c08, arg=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00e202e0]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLES00385”, errDialog=0x0, funcStat=*0xc0f240, container=4294967295)
E {PPU[0x1000000] Thread (main_thread) [0x00e202e0]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLES00228”, errDialog=0x0, funcStat=*0xc0f240, container=4294967295)
E {PPU[0x1000000] Thread (main_thread) [0x00e202e0]} SYS: 'cellGameDataCheckCreate2' failed with 0x8002b604 : CELL_GAMEDATA_ERROR_PARAM [1]
U {PPU[0x1000000] Thread (main_thread) [0x0104ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0104ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000008] Thread (libusbd_usbd_thread) [0x012b2b44]} sys_usbd TODO: sys_usbd_attach(handle=0x115b) x2
U {PPU[0x1000000] Thread (main_thread) [0x00e25bc8]} sceNp TODO: sceNpManagerGetNpId(npId=*0xd0020680) x4
U {PPU[0x1000000] Thread (main_thread) [0x01161bc4]} sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd00205b8)
E {PPU[0x1000000] Thread (main_thread) [0x010454ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x010454ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x010454ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]

**Comment by ualtinok** [comment]
I have the same issue with 2 DJ Hero controllers. When both plugged in getting the same exact error. 
I got it working couple times by running the game with single dongle plugged in, then quitting the game and plugging the second dongle and restart the game. This works rarely. 

When it works both controller have different sets of lights as:
If one controller have 1st and 3rd light on, the other have 2nd and 4th. If that's the case then it works. (Not sure if it's helpful.)
