### ISSUE TITLE
[Regression] Metal Gear Soild HD Collection (BLUS30847) black-screens/hanging

### ISSUE THREAD

**Issue by ZionHelios** [RPCS3/rpcs3#7904]
## Quick summary
When arriving at the launcher for titles, the window will either show a black-screen or hang. Though it can be brute-forced into launching any of the titles eventually (in-game button press takes a long time to reach parity with the actual physical button-press), but upon launching a title (finally) the program will recompile and play flawlessly.

## Details
#6624 (0.0.7.8760) - Seems to be the last build I could find that runs without issue. It may occasionally black-screen only to run without issue upon restarting.

[RPCS3_0.0.7.8760.log](https://github.com/RPCS3/rpcs3/files/4404908/RPCS3_0.0.7.8760.log)

#6602 (0.0.7.8765) - Will black-screen/hang indefinitely with brute-force (& patience) not being an option.

[RPCS3_0.0.7.8765.log](https://github.com/RPCS3/rpcs3/files/4404910/RPCS3_0.0.7.8765.log)

#7899 (0.0.9.10071) - Current build (at time of posting), lacks booting to black-screen but hangs. Waiting for the program to react to button presses and launching a title will recompile RSX and run smoothly as-if nothing happened. 

[RPCS3_0.0.9.10071.log](https://github.com/RPCS3/rpcs3/files/4404912/RPCS3_0.0.9.10071.log)

## System Specs
i5-4690k (@3.5ghz)
16GB RAM
Radeon RX 590 8GB
Win 10 Pro

**Comment by psennermann** [comment]
Maybe an AMD issue? I have the same game, but at the laucher everything seems to be ok: no black screen here (rpcs 0.0.9.10072)...

Win 10
Intel i7 7700
RTX 2060 super 8gb

**Comment by ZionHelios** [comment]
> Maybe an AMD issue? I have the same game, but at the laucher everything seems to be ok: no black screen here (rpcs 0.0.9.10072)...

As I said in the last one, newer versions don't boot to a black-screen anymore. But it does hang when I press anything.

**Comment by psennermann** [comment]
It doesn't hang for me, go straight in-game

**Comment by ZionHelios** [comment]
Once it gets into one of the games, everything is slick like buttered marble. Runs without a hitch. Even if it's an AMD issue, it's still a regression. Though I'm better off responding to somebody more well-versed in the program.

**Comment by kd-11** [comment]
There is nothing wrong with your graphics card and/or drivers. The more obvious difference here is the CPU. I'd start by running with interpreters and see if it changes anything.

**Comment by ZionHelios** [comment]
I had a hunch that may be a thing considering recommended calls for anything with Hyperthreading, but seeing as it was fine with older builds I disregarded it. 

I switched the SPU from LLVM to ASMJIT, still some inconsistency but a much better reaction at the title-selection screen. Still works the same in-game, which is fine considering anything after the selection screen ran smooth.

For science, I switched the SPU back to LLVM and enabled Accurate Xfloat. A better reaction than LLVM alone, but worse than just using ASMJIT. My apologies if this ended up as more of a help-thread, I was asked to post it as an issue and do regression testing. If there's anything else you may need from me, let me know or else I'll just close it.
