### ISSUE TITLE
Gran Turismo 6 [BCUS98296] fatal RSX buffer size error

### ISSUE THREAD

**Issue by threedope** [RPCS3/rpcs3#7913]
## Quick summary
Upon loading into/out of races (course and event determines frequency) the game crashes and RPCS3 displays the below error.
Seems to always occur when attempting multi-course tournaments. Inconsistent occurrence in pre/post-race menus.

F {RSX [0x12ae1c0]} SIG: Thread terminated due to fatal error: [index buffer] Working buffer not big enough, buffer_length=16777216 allocated=1963776 requested=4294967290 guard=65536 largest_pool=38592
(in file d:\a\1\s\rpcs3\Emu\RSX\Common\ring_buffer_helper.h:91)

## Details
RPCS3 0.0.9-10084, Win10 18363, Ryzen 3700x, 16gb 2400mhz, 1080ti w/ 442.19

[log.zip](https://github.com/RPCS3/rpcs3/files/4411658/log.zip)

**Comment by StillOutOfMind** [comment]
Can confirm this, occurs as described with a variation of settings and builds

Ryzen 3700x, 1080, 32gb

**Comment by neonoxd** [comment]
can trigger it consistently by launching: novice, amateur race 2 (grand valley) and clicking driving options / car options a few times in the pre-race menu

0.0.10-10452
9700k,1080ti,16gb

**Comment by b1acksnow** [comment]
> can trigger it consistently by launching: novice, amateur race 2 (grand valley) and clicking driving options / car options a few times in the pre-race menu
> 
> 0.0.10-10452
> 9700k,1080ti,16gb

same error

game version BCES01893, 1.05
3700x, 970 gtx, 32gb
0.0.13-11222

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5525708/RPCS3.zip

**Comment by Megamouse** [comment]
probably fixed by #10617

**Comment by kd-11** [comment]
Heap corruption crash. Check requested size (it is negative)

**Comment by Megamouse** [comment]
is this still an issue?

**Comment by DaishinSilviaGT** [comment]
haven't seen this error in months, can be closed i guess
