### ISSUE TITLE
[Feature Request] Display hw FMA cpu support in processor features in log 

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#7916]

**Comment by lextra2** [comment]
For anyone who is wondering if your CPU has FMA support, on Windows you can use [CPU-Z](https://www.cpuid.com/softwares/cpu-z.html) to check (Until RPCS3 displays it in the log)
![Capture](https://user-images.githubusercontent.com/20690384/78178101-65642b00-745f-11ea-97ae-cf21ff92dfd0.PNG)

**Comment by illusion0001** [comment]
Fixed by #7937
