### ISSUE TITLE
NINJA GAIDEN 3 Razors Edge[BLJM61010] graphic issue

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#7920]
This game is plagued by serious smoke problems. When it's serious, nothing can be seen (only smoke full of the screen, especially STAGE 2). I hope transparency of smoke can be fixed soon. 

rpcs3 0.0.9-10084

8700k 16g 1070ti win10

![未标题-1](https://user-images.githubusercontent.com/47111657/78237423-e548ce80-750d-11ea-9264-94f91e9f4e76.jpg)
![未标题-2](https://user-images.githubusercontent.com/47111657/78237440-ea0d8280-750d-11ea-8637-2605efa1cba9.jpg)
![未标题-3](https://user-images.githubusercontent.com/47111657/78237450-eda10980-750d-11ea-876d-acddfcdca7ef.jpg)
![未标题-4](https://user-images.githubusercontent.com/47111657/78237461-f0036380-750d-11ea-848d-d78a8e8c3921.jpg)

**Comment by arcadee1977** [comment]
In addition, there is a certain chance of black screen after tecmo logo:            
F {PPU[0x1000000] Thread (main_thread) [0x0324c3c0]} VM: Access violation reading location 0x38 (unmapped memory)

**Comment by asp0909** [comment]
it's a shame, now that 1 and 2 work very well, I'm also waiting for some solution to this!

**Comment by Silanda** [comment]
It looks similar to #6626. No idea if the underlying cause is the same though.

**Comment by islandking2000** [comment]
Man how did you get in the game, mine was almost always frozen after TECMO logo

**Comment by arcadee1977** [comment]
> Man how did you get in the game, mine was almost always frozen after TECMO logo

Set Framelimit = off

**Comment by islandking2000** [comment]
Well, won't work for me...

**Comment by asp0909** [comment]
the game just doesn't work in any way, and it's not known if they fixed it
