### ISSUE TITLE
Dubious double check.

### ISSUE THREAD

**Issue by sampletext32** [RPCS3/rpcs3#7924]
I was looking through the code and found this small thing.
There is actually a check for !g_init inside an already checked !g_init, so it's useless. 
If it's useless, why keep it? 

https://github.com/RPCS3/rpcs3/blob/72c0aed4c1594804ae2b4c60f5f29b374e5275c2/rpcs3/util/logs.cpp#L345

**Comment by AniLeo** [comment]
g_init is atomic

**Comment by Realmantik** [comment]
https://en.wikipedia.org/wiki/Double-checked_locking

**Comment by sampletext32** [comment]
> g_init is atomic

Can you explain to me, how it influences this double check occurrence. Since all I know about atomics is that they are executed as one single unit. How it affects this check?

**Comment by sampletext32** [comment]
> https://en.wikipedia.org/wiki/Double-checked_locking

Well, my knowledge is super low for this kind of things. Will try to understand. Thanks for the explanation btw.
