### ISSUE TITLE
PPU Accurate FMA default setting of "true" has performance hit on older CPU (i7-3770)

### ISSUE THREAD

**Issue by greentop** [RPCS3/rpcs3#7925]
**OS:** Ubuntu 18.04
**CPU:** Intel i7-3770
**RPCS3 build:** Master 72c0aed 

PPU Accurate FMA: true (default setting)
This setting on the i7-3770 cpu results in a random fps drop by roughly 12 fps or greater in some areas while playing games. Setting this value within the config & custom config files to "false" removes the performance hit.

**Comment by dio-gh** [comment]
That is the correct behaviour.

**Comment by greentop** [comment]
This is a performance regression that was introduced in commit 92f821a - 
Games that were performing at a stable 30 fps before that commit are now dipping to a noticeable fps crawl. Manually setting PPU Accurate FMA to "false" returns the games back to their previous stable 30 fps performance.

**Comment by Yahfz** [comment]
Old cpus that doesn't support FMA natively now require the accurate FMA option set to false. So again, like dio said that is the correct behavior.

**Comment by AniLeo** [comment]
Note: All CPUs in the recommended specifications have the FMA extension

**Comment by AniLeo** [comment]
Closing since this is the correct behavior, accurate FMA on CPUs without support for the FMA instruction set will be slower as expected

**Comment by greentop** [comment]
An CPU auto detection for this setting and/or a GUI configuration option with notes about its setting would be helpful.

**Comment by AniLeo** [comment]
Automatically forcing inaccurate mode doesn't make sense since some games need it to be accurate in order to process logic properly
Adding to GUI is already being done on #7915
