### ISSUE TITLE
rpcs3 unhandled win32 exception 0xc0000005

### ISSUE THREAD

**Issue by ahmmad88** [RPCS3/rpcs3#7926]
I have the latest verisn of RPCS3, the latest PS3 firmware 4.86 and the latest VUlkan SDK and yet i get this error rpcs3 unhandled win32 exception 0xc0000005...etc, RPCS3 was working before on my rig but since the last few updates i dont remeber which version was it doesnt anymore and every once and while i try  a newer version hoping it will work again but the same error..

my rig specs:
I7 7700hq
16G RAM DDR4
Nvidia 1050TI(4G)

![image](https://user-images.githubusercontent.com/15073213/78320448-c4ae6200-7569-11ea-9442-1f2beaad38df.png)

 here is the logs:
[https://gofile.io/?c=XzzrKt](url)
i dont see any other option to update it

## Details
Please provide as much detail as you can here, including
- expected (real hw) and observed (emulator) behavior
- full logs (not from UI)
- back traces (for hard crashes)
- screenshots, Renderdoc, and RSX captures (for visual issues)
- your system configuration (OS, CPU, GPU, driver versions, etc)
- anything else you deem to be important

**Comment by RainbowCookie32** [comment]
Log is empty, and please stop flooding all other issues asking if they fixed their issue. Not all errors are the same ones, closed ones were fixed, the ones that are open, probably not

**Comment by ahmmad88** [comment]
> Log is empty, and please stop flooding all other issues asking if they fixed their issue. Not all errors are the same ones, closed ones were fixed, the ones that are open, probably not

thanks for replyin & Sorry for flooding the other issues asking i didnt mean to i just wanted to play some PS3 games during quarantine besides i post about my issue before and no replied here is the logs again its not empty i checked it my self 

https://gofile.io/?c=UCSXyO

hope you tell me why

**Comment by AniLeo** [comment]
Bad settings, closing since you have literally no idea what you're doing and this is not how you report an issue, this is a request for support which are not allowed in the tracker as indicated on the guidelines.

**Comment by ahmmad88** [comment]
> Bad settings, closing since you have literally no idea what you're doing and this is not how you report an issue, this is a request for support which is not allowed in the tracker as indicated on the guidelines.
 
firstly this is not the issue "a bad settings" i already tried the recommended settings for the game from RPCS3 Wikki it gave me the same error so i changed it, if you dont know what you talk about  you dont just go saying "you have literally no idea what you're doing", you are rude ,secondly if its a support request why the other issues that have the same complain before me wasnt closed, yet it still open and only mine is closed ,lastly the guys on discord doesnt know the answer or the reason and they reply after two hours
