### ISSUE TITLE
NPUA80019 (Gran Turismo HD Concept) Flickering grass sprites

### ISSUE THREAD

**Issue by PixelPickaxe** [RPCS3/rpcs3#7929]
## Quick summary
Well, the grass sprites outside the boundaries of the course flicker and change brightness rapidly.

## Details
Expected: No rapid flickering. No rapid brightness changes.
Reality: Flickering and rapid brightness changes.

## Log
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4425136/RPCS3.zip)
## RSX & Screenshot
(https://github.com/RPCS3/rpcs3/files/4425124/NPUA80019_20200403005800_capture.zip)
### as you can see, shits fucked. RSX capture here ↑
![i dont know what to fucking call this grass ass gif](https://user-images.githubusercontent.com/32438273/78326293-062e1580-7548-11ea-9885-c9141d15b679.gif)

## System Config
nVidia GTX 1050 2GB
AMD Ryzen 3 1200 Quad-Core Processor @ 3.10GHz
16.0 GB 3200 DDR4 sold by OLOy
Windows 10 Education x64 Version 1909 (OS Build 18363.720)

**Comment by Asinin3** [comment]
This video https://youtu.be/xb7q6dvkYhw?t=699 shows the grass behaving differently. It looks like there's no grass rendering when its close and the far away grass disappears as you get close. Would be nice to see someone do a proper retest

**Comment by Satan86** [comment]
still flickering here https://www.youtube.com/watch?v=rRdtAGtBlTA

**Comment by AniLeo** [comment]
Did you try Write Color Buffers and Strict Rendering Mode?

**Comment by PixelPickaxe** [comment]
> Did you try Write Color Buffers and Strict Rendering Mode?

Yeah. Just did. Same thing, but the game runs slower, as expected.

**Comment by Satan86** [comment]
Fixed By #11151

**Comment by PixelPickaxe** [comment]
Yessss!! LET'S GO!!!!
