### ISSUE TITLE
Gran Turismo 5 and 6 only go ingame if AA is disabled

### ISSUE THREAD

**Issue by jacob1218** [RPCS3/rpcs3#7943]
## Quick summary
This one may be on nvidia, since this now happens even in older builds. When you start GT5, the only way to go ingame is with AA disabled on Vulkan. Otherwise, RPCS3 loses the device.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4431320/RPCS3.zip)

## Details
There was no specific build that caused this, which makes me think it's something nvidia did.
CPU: Ryzen 5 3600X
GPU: Nvidia GTX 1050 Ti
RAM: 32GB

**Comment by jacob1218** [comment]
This looks very similar to #7891, maybe it's related?

**Comment by illusion0001** [comment]
Possible. it could be same issue.

**Comment by jacob1218** [comment]
This issue just gets weirder. If aa is enabled and the resolution is set to 1920x1080, the game works (and faster than in 720p).

**Comment by jacob1218** [comment]
with that, this is now a duplicate of #7891. closing
