### ISSUE TITLE
Sillent Hill Downpour - Save version incompatibility previous

### ISSUE THREAD

**Issue by DJRolly** [RPCS3/rpcs3#7954]
same problem as this post:
https://github.com/RPCS3/rpcs3/issues/6558

Please, I have the same problem, and practically 4:30 game completed. Did anyone find the solution to use the previous version save?

**Comment by digitaldude555** [comment]
My saves work and they were made a month ago, how old are your saves?

**Comment by DJRolly** [comment]
> My saves work and they were made a month ago, how old are your saves?

Was playing in version 0.7.9202
When updating the savegame does not load, it is in a loop

**Comment by digitaldude555** [comment]
That version is 123days old, all you can do is start the game again or try playing with that build again.

**Comment by DJRolly** [comment]
ok thank you very much for your help

**Comment by elad335** [comment]
need to upload old & broken savedata.

**Comment by Megamouse** [comment]
Closing. There was no update for 6 months.
