### ISSUE TITLE
GT5 crashes when building SPU Cache on Mega block size

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#7956]
RPCS3 crashes when building SPU Cache on Mega block size. Seems like it's Gran Turismo 5 only, as other games worked fine.

It broke after 0.0.9-10111. SPU Block Size Safe fixes the issue, but I use Mega for GT5. 
Offending pr: #7944
  
SPU Crash (0.0.9-10111):
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4433310/RPCS3.zip)
No crash (0.0.9-10105):
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4433338/RPCS3.log.gz)

**Comment by Satan86** [comment]
worked after 5 tries, probably something wrong on my end.

**Comment by Satan86** [comment]
Actually, it wasn't
I went for another try now and it's still broken, so I reopened

**Comment by xddxd** [comment]
Can reproduce here. With a fresh cache on Mega it locks up the game when entering a race. While it is building the SPU cache on Mega on a second launch it freezes and just closes to desktop.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4567533/RPCS3.log)

**Comment by Satan86** [comment]
fixed as of  #8296. closing

**Comment by malev-exe** [comment]
Sorry im kinda new to this, how did u fix it? Im having the same issue
