### ISSUE TITLE
Regression: Pirate Warriors 2 Seizuring Enemy AI [BLES01913] (Broken with SPU llvm Safe)

### ISSUE THREAD

**Issue by TheProtato923** [RPCS3/rpcs3#7958]
## Quick summary
Enemy AI seems to have a literal seizure and flicker around uncontrollably. 

## Details
Regression was introduced in build 9806, and was not present in 9805.

Log for 9806 - https://drive.google.com/file/d/1V1SY8WCLScuzhNbWtQmyeWA_DTB-ajPQ/view?usp=sharing
Log for 9805 - https://drive.google.com/file/d/17OxJqU6Wp4mRD1Dd7mQDRoaSMySdgI8K/view?usp=sharing

RSX Capture - https://drive.google.com/file/d/1wvM8fHEg_tXVAGoYOiFrDy2qHlOWmSph/view?usp=sharing

Screenshot
![78504776-296de600-773d-11ea-98e7-440b30812f07](https://user-images.githubusercontent.com/29867513/78504903-e2ccbb80-773d-11ea-8e18-86390f21c7bf.png)

**Comment by RainbowCookie32** [comment]
Offending PR is #7672 then

**Comment by AniLeo** [comment]
Note: This works with Accurate XFloat, but before it didn't require it to render properly

**Comment by arcadee1977** [comment]
> Note: This works with Accurate XFloat, but before it didn't require it to render properly

Dynasty Warriors: Gundam Reborn|BLES02057 have the same problem

**Comment by arcadee1977** [comment]
OPPW2 [BLAS50597] enemy still have seizuring Enemy AI :(

**Comment by Whatcookie** [comment]
Issue can be reopened, apparently the version I PR'd didn't solve this issue.

I can solve it now, but it will come with a noticeable performance loss. I think I can solve it without causing any performance loss at all, but it will take much longer to write. I'll probably work on some other stuff and revisit it at a later date.

**Comment by AniLeo** [comment]
For reference, One Piece was fixed by the FMA32x4 change and then rebroke with FM change

**Comment by digitaldude555** [comment]
Its fixed now with spu llvm accurate xfloat isnt needed.
