### ISSUE TITLE
Ratchet And Clank [NPEA00385] - FPS drops with large field of view

### ISSUE THREAD

**Issue by fearcraftor** [RPCS3/rpcs3#7959]
## Quick summary
Ratchet And Clank [NPEA00385] plays very well at 60FPS most of the time (needs to be limited though as it reach sky-high 400 FPS on small areas),

but suffers of massive FPS drops, so the game is slowed down on large areas with far depth of view

## Details

    full logs and back traces provided

your system configuration (OS, CPU, GPU, driver versions, etc)
OS: Windows 10 1909
CPU: Intel Core i5-4440 CPU @ 3.10GHz
GPU: GTX 660 (v 444.75
RAM: 8Go
[rpcs3-ratchet_trilogy.zip](https://github.com/RPCS3/rpcs3/files/4434481/rpcs3-ratchet_trilogy.zip)
)

**Comment by Yahfz** [comment]
That's literally how every single game works, emulated or not. On a "large area" the drawcalls will be higher which lowers the framerate. Consider closing the issue.

**Comment by MineSAT** [comment]
Whether they are large render areas or not, this problem is not present on PS3 or PS2. It is something that must be fixed since it is not the only game with that problem in the emulator.

I at least do not see it necessary to close the issue @Yahfz :/

**Comment by AniLeo** [comment]
There's no actual bug related to the game or something alike, it's natural as the draw call count increases the performance gets lower

Tagging @kd-11 to decide what they want to do with this

**Comment by kd-11** [comment]
We cannot open tickets for performance drops otherwise all issues would be complaints about fps drops below 60fps. They are also not directly actionable. The issue will slowly get better over time as optimizations continue.
