### ISSUE TITLE
Regression: Dante's Inferno no longer loads menus (#7552)

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#7960]
Starting with 9661, the game soft locks loading the main menu. Looks related to users with DLC installed as for some people it still loads correctly. Broke by this:  https://github.com/RPCS3/rpcs3/pull/7552

9661:
![2020-04-05 14_38_52-Settings](https://user-images.githubusercontent.com/20983844/78510684-0eef3900-774c-11ea-969f-9c1a505894fd.png)
[9661.gz](https://github.com/RPCS3/rpcs3/files/4434960/9661.gz)

9660:
![2020-04-05 14_37_01-FPS_ 59 91 _ Vulkan _ 0 0 8-9660 _ Dante's Inferno™ HDD  NPUB30478](https://user-images.githubusercontent.com/20983844/78510690-17477400-774c-11ea-8a84-fc53a42dd00d.png)
[9660.gz](https://github.com/RPCS3/rpcs3/files/4434961/9660.gz)

Shots of the messages that DON"T show in 9661:
![2020-04-05 14_31_49-Settings](https://user-images.githubusercontent.com/20983844/78510701-28908080-774c-11ea-964f-53c0f20bd195.png)
![2020-04-05 14_35_50-FPS_ 59 92 _ Vulkan _ 0 0 8-9660 _ Dante's Inferno™ HDD  NPUB30478](https://user-images.githubusercontent.com/20983844/78510702-2dedcb00-774c-11ea-8269-e405f5919e96.png)
![2020-04-05 14_34_26-FPS_ 60 03 _ Vulkan _ 0 0 8-9659 _ Dante's Inferno™ HDD  NPUB30478](https://user-images.githubusercontent.com/20983844/78510703-2f1ef800-774c-11ea-8565-cd55a4cf297c.png)
![2020-04-05 14_31_55-FPS_ 59 93 _ Vulkan _ 0 0 8-9657 _ Dante's Inferno™ HDD  NPUB30478](https://user-images.githubusercontent.com/20983844/78510723-55449800-774c-11ea-9444-d44adc262b26.png)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by elad335** [comment]
`·! 0:00:04.925952 SYS: Now disabling logging...` in 9661 log, please reupload log.

**Comment by legend800** [comment]
Apologies, here's the proper log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4435427/RPCS3.log.gz)

**Comment by legend800** [comment]
Not fixed - same behavior.

In console:
E {PPU[0x1000000] Thread (main_thread) [0x016702e0]} SYS: 'cellGameDataCheckCreate2' failed with 0x8002b606 : CELL_GAMEDATA_ERROR_BROKEN [1]

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4446582/RPCS3.log.gz)

**Comment by elad335** [comment]
Can you upload the PARAM.SFO in BLUS30405 game directory?

**Comment by legend800** [comment]
Dante's Inferno™ HDD [NPUB30478]
[PARAM.zip](https://github.com/RPCS3/rpcs3/files/4447815/PARAM.zip)

**Comment by elad335** [comment]
Try deleting dev_hdd0/game/BLUS30405 folder, yes I mean BLUS30405 not NPUB30478 because that's whats referenced by the cellGame functions in log.

**Comment by legend800** [comment]
Yep, works fine if I remove the Forest DLC. So that's the trigger.

![2020-04-08 09_46_22-Window](https://user-images.githubusercontent.com/20983844/78811029-1433ca00-797e-11ea-8e6c-61879a709f55.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4451736/RPCS3.log.gz)

**Comment by legend800** [comment]
Tracked it down to the DLCs param.SFO as you were mentioning. Redump fixed it.

So it got corrupted or something and newer versions are more strict with that (hence why it loads fine in older versions)?

[PARAM.zip](https://github.com/RPCS3/rpcs3/files/4451937/PARAM.zip)

**Comment by elad335** [comment]
Possibly, I suggest closing the issue for now.

**Comment by legend800** [comment]
Sure, that's fine. I'll close. Thanks for figuring that out. 

Do things get written to that file as the user progresses? Just curious if once I start playing the DLC if the issue might come back. 

Also, shameless plug for these other regressions here. Maybe you can take a look when you get some time, since they're right up your wheelhouse. ;)

[Regression] Jeremy McGrath's Offroad [NPUB30368] Freeze on loading menus now
https://github.com/RPCS3/rpcs3/issues/6681

[Regression] Conan can no longer load menus
https://github.com/RPCS3/rpcs3/issues/7733
