### ISSUE TITLE
Dualshock 3 Controller No Longer Connecting on RPCS3

### ISSUE THREAD

**Issue by nealsk** [RPCS3/rpcs3#7962]
Hi all,
I'm new to this so sorry if this was mentioned, but I haven't found a solution.

Today (4/5/2020) my Dualshock controller stopped being recognized on RPCS3. I was able to use it just fine yesterday, today it stopped working. I tried to even uninstall RPCS3 and start all over and that didn't help.
My computer recognizes the controller when its plugged into the computer however WinUSB and RPCS3 do not.

Thanks!

**Comment by AniLeo** [comment]
No changes were made to controller support from yesterday to today, therefore this falls under being a support request and must be done through the appropriate channels

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by nealsk** [comment]
What are the proper channels? How do I figure that out?
--
*Neal K*
he/him
nealsk@gmail.com

**Comment by sampletext32** [comment]
The best place is actually #help channel in discord.
https://discord.me/RPCS3

**Comment by AniLeo** [comment]
When opening an issue, that's the first line that appears on the commented text, and it's also mentioned on the support guidelines.
