### ISSUE TITLE
Kingdom Hearts 2.5 - Random softlocks [BLES02070]

### ISSUE THREAD

**Issue by molipoop** [RPCS3/rpcs3#7970]
Hi ,
kingdom hearts plays very well for some minutes but always crashes randomly (a black screen ) .
The game looses also at least ten fps when roxas attacks.
My hw :
Intel I5-7600K 3.8 Ghz
Gtx 1070
8gb ram ddr4.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4441042/RPCS3.log.gz)

**Comment by AniLeo** [comment]
> The game loses also at least ten fps when roxas attacks.
That is tracked on #7338

Is the log file from a black screen run? Also, make sure you're on latest build when retesting

**Comment by EmreXCoded** [comment]
I have the problem with shuttering when Roxas attacks too. And i'm using the latest build. (Current: 0.0.10-10341) But i don't know, which latest build has this fixed.

**Comment by Megamouse** [comment]
Is his still an issue?

**Comment by MSuih** [comment]
Roxas attacks are tracked in #7338. The random crashes shouldn't be happening anymore.
