### ISSUE TITLE
gui: Sorting broken on Time Played

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#7985]
Reproducing: Sort by Time Played, games with only seconds of play time will not sort correctly

![image](https://user-images.githubusercontent.com/10283761/78742518-2f89df80-7954-11ea-9bb5-4487fa17da05.png)

**Comment by Megamouse** [comment]
turns out, not sorting is broken, but the time string

**Comment by AniLeo** [comment]
Confirmed fixed
