### ISSUE TITLE
Ratchet & Clank:  Tools of distruction constant crashes

### ISSUE THREAD

**Issue by btrudgill** [RPCS3/rpcs3#7990]
Having constant crashes in R&C:ToD, cannot get past 1st level without hangs.
Screen hangs but music continues in background, computer still responsive (I can ctrl + alt + del to get out).
I have tried many different settings, coppied settings from different users videos on YouTube. Looked through GitHub feeds from a google search of the issue.

Other weird behaviour, despite selecting 16:9 and 1080p resolution the game shows up in what looks to be 1:1 ratio unless i click the option to stretch the display. 

Any thoughts?
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4452203/RPCS3.log)

**Comment by isJuhn** [comment]
try put this in `patch.yml` file next to rpcs3.exe (create it if it doesn't exist)
```
PPU-c4e26433d1eed9166eb0c67b6f66b2268f3704e2: #BCES00052 R&C ToD Freeze fix
  - [be32, 0x5056f0, 0x409efff0] #bne 0x5056e0
```

**Comment by btrudgill** [comment]
Unfortunately i have tried that and it doesnt help.
(tried it again just now to confirm).

**Comment by Bertanos** [comment]
Try using PPU Interpreter (fast)

**Comment by btrudgill** [comment]
Its beyond unplayable with the ppu interpreters (precise and fast).

I am getting 5 fps in menus and cutscreens. Dont fancy the wait to see if
it improved beyond the opening cutscene.

Pc specs:
I7 7700k @4.9
Rtx 2080 msi gaming x trio.
Game running off ssd.

**Comment by Bertanos** [comment]
I know cutscenes and menus are beyond laggy, but gameplay is fine (only ~10-20% slower than LLVM)

**Comment by btrudgill** [comment]
So I think I have fixed it, I have managed to complete the first planet at least.

I used the patch provided by isJuhn, and then cleared all caches in rpcs3 which forced the PPU to recompile on next launch.

**Comment by forgettableEgg** [comment]
Anyone find a fix for this? I am running into the same issue. I constantly crash while trying to boot up the game/ in the first level.

**Comment by Trustery** [comment]
I'm having the same problem :/

**Comment by isJuhn** [comment]
The only log in this issue is with a pirated game dump and bad settings with no patch applied. Please delete the log. Unless a new log is added with a good game dump, default + vulkan settings and patch applied this issue can be considered invalid.

**Comment by kd-11** [comment]
Closing as invalid, if there are updates, please add them correctly to a new ticket.
