### ISSUE TITLE
[NPEB00553] Resident Evil Code: Veronica X - RSX nv406e desyncs

### ISSUE THREAD

**Issue by dyno0** [RPCS3/rpcs3#7994]
## Quick summary

RE: CVX crashing with error code:

`RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300480`

## Details

The game crash is inconsistent but detectable. When the timeout is about to happen the ambience music sound cuts off while the game sfx plays accordingly. Semaphore timeout happens at the moment you proceed to the next area that requires a loading screen, not right when the sound cuts off. Also, changing the driver wake-up delay doesn't seem to effect this kind of desync. (tested to up to 3ms).

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4455488/RPCS3.log.gz)

**Comment by Evil0Dead** [comment]
can't confirm ..

I have this game and I've walkthrough  to Chris part with no single crash

everything is default .. except 4K res.

**Comment by dyno0** [comment]
Just tried to speedrun through the game and it still happens, crashed after 1h of play now. As I said it's inconsistent but detectable.

[TTY.log](https://github.com/RPCS3/rpcs3/files/4834292/TTY.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4834293/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
@dyno0 update needed

**Comment by dyno0** [comment]
I upgraded the cpu so I can't reproduce it anymore, guess that fixed it. Maybe someone with a weaker cpu can test it out.
Let's suppose it's fixed.
