### ISSUE TITLE
The last of us[BCAS20270] random crashes 

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#7995]
The last of us [BCAS20270] random crashes with following error log:

F {SPU[0x5000100] Thread (highCellSpursKernel5) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)
F {SPU[0x0000100] Thread (highCellSpursKernel0) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)
F {SPU[0x4000100] Thread (highCellSpursKernel4) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)
F {SPU[0x1000100] Thread (highCellSpursKernel1) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)
F {SPU[0x2000100] Thread (highCellSpursKernel2) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)
F {SPU[0x3000100] Thread (highCellSpursKernel3) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)

8700k 1070ti 16g win10

**Comment by AniLeo** [comment]
Doesn't mean anything by itself, already known that the game is unstable
