### ISSUE TITLE
The file rpcs3.exe has been removed without any explication

### ISSUE THREAD

**Issue by jesusvargas00** [RPCS3/rpcs3#8003]
Yesterday I downloaded RPCS3, and when I launched the .exe file, it was removed from the main folder without any explication, so I couldn't use RPCS3. When I tried it again, the same thing happens. I don't know the reason for this error. I attach the .log file where I have installed RPCS3 in case it helps for something. I hope your answer. Best regards. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4460764/RPCS3.log)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by jesusvargas00** [comment]
I don't understand. I cannot write an issue here for finding a solution for my RPCS3 problem?

**Comment by AniLeo** [comment]
**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).
