### ISSUE TITLE
Can I run rpcs3 on my computer which has the GPU of AMD hd6850

### ISSUE THREAD

**Issue by sunxiao2010n** [RPCS3/rpcs3#8007]
I installed rpcs3. But It was reported that I needed to install valkan. Likely my computer does not support valkan. Can I bypass the startup check and use OpenGl, is there any builds can help this? Looking forward for your help, thanks

**Comment by Asinin3** [comment]
This is a issue tracker, for reporting bugs with relevant technical information. Not a place to ask questions or for Discussion. GitHub is for Developers & Testers. If you want to discuss RPCS3, ask on our discord server: https://discord.me/rpcs3 . We also have a subreddit: https://www.reddit.com/r/rpcs3/ and forums: https://forums.rpcs3.net/ but... the discord is the most active by far and you'll be more likely to get a fast reply.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
