### ISSUE TITLE
Regression: inFAMOUS 2 [BCAS20181] now has no sound in-game (#7672)

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#8009]
0.0.7-9032 : SOUND OK
0.0.9-9930 : NO SOUND
0.0.9-10162 :  NO SOUND

WIN10 1803 
8700K 1070TI 16G

**Comment by AniLeo** [comment]
Missing build that introduced regression, log file, does not follow any guideline

**Comment by dio-gh** [comment]
wtf, it used to work before? there are *some* sounds btw, it's just that it's missing for the most part. that's how i saw it in a gameplay anyways.

**Comment by epicmoment** [comment]
Did some testing and found out that #7672 introduced this issue. The in-game sound disappears when using LLVM SPU decoder.

Turning on accurate xfloat causes heavily distorted audio, and turning that and approximate xfloat off fixes the audio but breaks the game.

**Comment by arcadee1977** [comment]
> Did some testing and found out that #7672 introduced this issue. The in-game sound disappears when using LLVM SPU decoder.
> Turning on accurate xfloat causes heavily distorted audio, and turning that and approximate xfloat off fixes the audio but breaks the game.

Thanks for your testing , hope @Nekotekina can be fixed this issue

**Comment by Graubek** [comment]
Try updating, now there is sound. I'm using 0.0.10.10442 and my InFamous serial is BCES01143

**Comment by Xcedf** [comment]
It's definitely fma32x4 in FMA instruction, set my FMA to xmuladd and issue gone

**Comment by bingcanxue** [comment]
Sorry to bother but im having the same problem，i want to know Is it ongoing or something?

**Comment by alexcastillo15** [comment]
made an account just to bump this thread. the issue still persists as of june 17 2020.

**Comment by dio-gh** [comment]
there's really no point in bumping it though, it's not like it gets fixed any faster

**Comment by Graubek** [comment]
Sound is working now

**Comment by ezooa** [comment]
Where is the link?
