### ISSUE TITLE
Problem: RPCS3 Castlevania Harmony of Despair All DLC Fix saving data

### ISSUE THREAD

**Issue by foxhuntercustoms** [RPCS3/rpcs3#8018]
Hello guys having issue. I can't get pass on saving data part How to fixed this? keep looking ong PPU compiling 0/4 then repeat [https://imgur.com/xiVxFvX](url)

**Comment by AniLeo** [comment]
Very old build, and this is not the place to ask for support

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
