### ISSUE TITLE
BLJS10260 Idolmaster One for All close up camera issue - blurry line down middle in close up camera

### ISSUE THREAD

**Issue by Osailor** [RPCS3/rpcs3#8020]
![screenshot](https://user-images.githubusercontent.com/18251643/79082268-cb0dbc80-7d67-11ea-894e-de2426151db8.jpg)

Hi Team. Having a visual glitch with one for all where a blurry line is in the middle of the screen during the close up camera and the lower third of the screen is also blurry. After a bit of a search it seems to be an unresolved issue from a while ago, but not sure if a resolution was found in the meantime. I have rrc files if required.

have tried on two pc's with intel CPU's one i5, one i7. Both with Nvidia GPU's (GTX970 and RTX2070). 

GPU renderer: Vulcan
resolution:1280x720
strict rendering mode: yes
framelimit: auto

I have tried all of the additional settings in many different combinations and none of them have worked. Open GL causes way too many graphical glitches to play on too.

please let me know if I can provide more info.

**Comment by digitaldude555** [comment]
#5890 #7591 3 of the same issue now......

**Comment by kd-11** [comment]
I've updated the two previous tickets to track crashing and visual glitches separately. Let's close this as duplicate.
