### ISSUE TITLE
BCUS98233 [Uncharted 3] sys_bnet errors when attempting to start offline co op or lan match

### ISSUE THREAD

**Issue by superepic32** [RPCS3/rpcs3#8028]
This is a consistent problem that happens whenever the match for offline modes are attempting to start. The game kicks me to main menu with a psn error despite the modes not requiring internet connection or psn access. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4471309/RPCS3.log)

**Comment by jeremybris** [comment]
Same thing happens to me. I've tried all the versions, and I get the same error.

But, I've found two youtube videos demonstrating offline lan play https://www.youtube.com/watch?v=4cuJpi1ygZQ and https://www.youtube.com/watch?v=yDfvx4TI1SE.

There must be a workaround.

**Comment by superepic32** [comment]
It was working before on earlier builds, and it stopped recently. Something was changed that broke it. Offline works on my PS3 so it seems to be an emulator error.

**Comment by jeremybris** [comment]
If it was working on earlier builds, then it is a regression. The YouTube video here https://www.youtube.com/watch?v=yDfvx4TI1SE shows it working on 0.0.7.9221 https://rpcs3.net/compatibility?b&p=22. I'll try to look for the regression.

**Comment by superepic32** [comment]
theres a custom build i had that it was working on but i cant open it anymore to see the build

**Comment by superepic32** [comment]
I have tested the 0.0.8-9651 custom build and the lan and co op work properly. Here's a log: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4497581/RPCS3.log)

Hopefully this can be fixed and the simple fact that it's uncharted doesn't deter anyone from checking it out.

**Comment by jeremybris** [comment]
Can you post your custom build please? I want to replace individual parts of RPCS3, and see if I can narrow down where the fix is.

**Comment by superepic32** [comment]
Issue is still present in latest master.

**Comment by jeremybris** [comment]
I was not able to play the game in offline split-screen using the link you provided.

> Link: https://youtu.be/JKVGZMbYtwA

I use default settings with Vulkan and Read Color Buffers on. So maybe it works because of your settings or your hardware?... (My specs are AMD Ryzen 3900x, and RTX GPU.)

**Comment by superepic32** [comment]
My settings are both network options OFF, WCB, liblv2 only and LLVM SPU/PPU. I don't know why it isn't working for you... I have a 3700x and RTX 2060S

**Comment by superepic32** [comment]
Seems to be fixed now with #8337

**Comment by jeremybris** [comment]
> Seems to be fixed now with #8337

You tried the PR and it worked? Because I tried it, and it did not work for me. 

Are you using any patches (patch.yml)? Maybe that is making the difference.

**Comment by superepic32** [comment]
Yes, I am using several patches but those do not affect networking in any way. I’m not sure what’s happening with your end. The only setting I had on dealing with networking was simulating PSN, which was left on by accident.

**Comment by jeremybris** [comment]
> Yes, I am using several patches but those do not affect networking in any way. I’m not sure what’s happening with your end. The only setting I had on dealing with networking was simulating PSN, which was left on by accident.

It's very strange. Maybe I have a bad rap file. @web1018 or @lainiwaku can you please test this issue, because we are getting mixed results.

I get the error 
- E {PPU[0x10000ba] Thread (NetInit) [0x01455d28]} SYS: 'sceNpScoreInit' failed with 0x8002a101 : SCE_NP_COMMUNITY_ERROR_ALREADY_INITIALIZED [1] 
- along with the sys_bnet error

I will try again with all the patches and update my comment, once megamouse's patch manager is added.

**Comment by jeremybris** [comment]
I tried with patches. No changes.

You can close this issue, if you want, since it doesn't effect you anymore. I will open a new issue.

The only thing I think of is that I have the European version, and you have the U.S. version.

**Comment by superepic32** [comment]
Let me know when you find out why exactly.
