### ISSUE TITLE
BLES01228 DMC 3 game breaking graphical bug

### ISSUE THREAD

**Issue by puffledude** [RPCS3/rpcs3#8030]
## Quick summary
In mission 7 of DMC3 there is a game breaking graphical issue.
## Details
In mission 7 of DMC3 there is a game breaking graphical issue. Instead of rendering the cursed skull chamber like normal, a flat texture is displayed. The game doesn't crash during this bug and sound is normal.
![dmc 3 RSX capture screenshot](https://user-images.githubusercontent.com/63147552/79158980-2cb54180-7dcf-11ea-9df7-7c4a4eff5ad1.PNG)

Here is an RSX capture for when the error happens.
[Devil may cry 3 RSX capture.zip](https://github.com/RPCS3/rpcs3/files/4471758/Devil.may.cry.3.RSX.capture.zip)

Log:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4472006/RPCS3.zip)

**Comment by dyno0** [comment]
I wouldn't say it's game breaking, if you break the wall or move away from that fixed camera angle as soon as you enter the room it continues normally.

**Comment by pidgey84** [comment]
Mmm i dont get that far on dmc3, but i notice that the game crash randomly when get onto a power up statue menu or even on customize screen before starting a mission, is random but i think is a bad issue too.

**Comment by digitaldude555** [comment]
@puffledude still issue?

**Comment by puffledude** [comment]
> @puffledude still issue?

Just tested, the issue is now fixed and everything works as it should.

**Comment by puffledude** [comment]
Closing the issue as it is resolved
