### ISSUE TITLE
[Possible Code Enhancement] Double check in RSXThread

### ISSUE THREAD

**Issue by sampletext32** [RPCS3/rpcs3#8038]
https://github.com/RPCS3/rpcs3/blob/20f53e65eb53248462bf0be17d90bf7e4b5a05b2/rpcs3/Emu/RSX/RSXThread.cpp#L2463-L2480

## Explanation
existing_range_valid check check is done twice in case of touches() returns false. 

## Suggestion
```
if (existing_range_valid)
{
	if (m_invalidated_memory_range.touches(unmap_range))
	{
		// Merge range-to-invalidate in case of consecutive unmaps
		m_invalidated_memory_range.set_min_max(unmap_range);
	}
	else
	{
		// We can only delay consecutive unmaps.
		// Otherwise, to avoid VirtualProtect failures, we need to do the invalidation here
		handle_invalidated_memory_range();
		m_invalidated_memory_range = unmap_range;
	}
}
```

I know that developers are busy and change is small, so I can fix it myself, if this is worth it.
@elad335, I think you are in charge of this kind of fixes.

**Comment by Megamouse** [comment]
your suggestion is incomplete, you are missing the entire else path of the condition

**Comment by sampletext32** [comment]
> your suggestion is incomplete, you are missing the entire else path of the first condition

Well, really. Didn't notice that small assignment. My bad.
