### ISSUE TITLE
I don't have internet in games.

### ISSUE THREAD

**Issue by thedanioner** [RPCS3/rpcs3#8044]
run some PKG games and I don't have internet, for example Spotify.

I have a desktop computer connected by network cable.

 any solution please?

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
