### ISSUE TITLE
[Persona5] Game lags and audio shutters 

### ISSUE THREAD

**Issue by ttwiwy** [RPCS3/rpcs3#8050]
I just have Persona 5 installed into rpcs3 emu, and I noticed that the game run in lag as the CPU utilization pinned at 100%, but the GPU seems ok, already tried with different solution I can find online but still have no luck, now what can I do to improve my gaming experience?

Computer Spec:
CPU:Intel(TM) Core i5-7600k 
RAM:32GB of hyperX DDR4 2400 (4x8GB)
GPU1:Inno3D GeForce GTX1070
GPU2:Gigabyte GeForce GTX1050
MOBO:MSI B250M bazooka
SSD: Corsair MP500 120GB 
HDD:WD 4TB Datacenter(Yellow)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
