### ISSUE TITLE
[GUI][Linux] Qt widgets are cropped.

### ISSUE THREAD

**Issue by y-salnikov** [RPCS3/rpcs3#8052]
## Quick summary
Something wrong with Qt interface in RPCS3.

## Details

![rpcs3_Qt](https://user-images.githubusercontent.com/5237022/79503117-af453780-8041-11ea-8450-2b8cf05bc705.png)

Arch linux. Changing theme in RPCS3 doesn't  help as well as changing Qt5 themes in system. Appimage v0.0.8-9445-a9162a3f look fine but same version built from sources with AUR (rpcs3-git aur package) already has this bug and it is not earliest version with it.

I think something might be wrong with my Qt settings, though. Qt version installed - 5.14.2-1.

**Comment by qurious-pixel** [comment]
#7772 The solution was to change the QT scaling environment variable.
`export QT_AUTO_SCREEN_SCALE_FACTOR=0`

**Comment by Megamouse** [comment]
`QT_AUTO_SCREEN_SCALE_FACTOR` was replaced with `QT_ENABLE_HIGHDPI_SCALING` in Qt 5.14.

I don't know why it can still have any influence on rpcs3

**Comment by y-salnikov** [comment]
QT_ENABLE_HIGHDPI_SCALING=0 work as well.
