### ISSUE TITLE
WWE 12 DLC

### ISSUE THREAD

**Issue by KennyKage** [RPCS3/rpcs3#8063]
WWE 12 Not Working When DLC Is Installed. It Gets Stuck On The Loading Video When Update 1.01 Is Installed.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
