### ISSUE TITLE
L.A Noire crashes with a fatal error

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8064]
Hello, L.A Noire BLES00933 doesn't get to the menu because of an SPU Thread Fatal error.

`Thread terminated due to fatal error: Unknown command (cmd=0xff, lsa=0x0, ea=0x2491c, tag=0x0, size=0x10)
(in file d:\a\1\s\rpcs3\Emu\Cell\SPUThread.cpp:2293)`

Ryzen 7 2700
RX 580
PPU Interpreter (fast), SPU LLVM
LLE libvdec.sprx
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4496915/RPCS3.log.gz)

**Comment by uaqlover** [comment]
could fix https://github.com/RPCS3/rpcs3/issues/5591 ?
