### ISSUE TITLE
Diablo 3 Reaper of Souls

### ISSUE THREAD

**Issue by TheWolfOW** [RPCS3/rpcs3#8067]
VM: Access violation reading location 0x60267570 (unmapped memory)
Game crashes after 8-10 minutes.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4500197/RPCS3.zip)

**Comment by AniLeo** [comment]
Clear PPU/SPU cache before retrying

**Comment by TheWolfOW** [comment]
I tried it and saw the error again:VM: Access violation reading location 0x427000c0 (unmapped memory) 
[RPCS32.zip](https://github.com/RPCS3/rpcs3/files/4500249/RPCS32.zip)

**Comment by AniLeo** [comment]
What build regressed this?

**Comment by TheWolfOW** [comment]
RPCS3 v0.0.9-10244-dbce10d0

**Comment by AniLeo** [comment]
Needs investigating

**Comment by TheWolfOW** [comment]
Is something required of me?
