### ISSUE TITLE
Alien Isolation [NPUB31440]: Sound cuts out ingame

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#8068]
Ingame audio is scratchy and stutters wildly during gameplay, and (crucially) eventually cuts out completely.  Note that these sound issues occur even when the game is running at full speed.

Aspects tested to no avail:

- ASMJIT SPU
- SPU loop detection (fixes sound in many games, just not this one)
- SPU block size
- SPU threads
- Multithreaded RSX
- Audio backend (FAudio, OpenAL, Pluseaudio, ALSA)
- Downmix to stereo
- Buffering/timestretching
- Relaxed ZCULL

This has happened as far back as I've been testing but has been encountered as recently as build dbce10d0e38bd623c56d81125b59cdb2c7bf3c60.

Tested with Linux Mint 19.3 kernel 5.3 self-compiled with gcc 9.3.0

Logfile: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/4500752/RPCS3.log)

**Comment by GitArUs** [comment]
What about alsa backend ? I use alsa because it simply works best for me.

**Comment by Shoegzer** [comment]
Thanks, performance with alsa is worse than with the others though, and I get even scratchier audio.  Have you tried it with this game in particular?

**Comment by GitArUs** [comment]
I don't own this game, I asked to make sure it happens with all audio backends. If You have tested other options (like number of spu threads, spu loop detection, size of audio buffer, various spu/ppu decoders), then I have no other ideas. You can find movies on Youtube showing this game running pretty smooth with perfect sound, but apparently on Windows, and different version (BLUS/BLES).

**Comment by Shoegzer** [comment]
Thanks, fair enough.  I've seen those videos too.  Note though, the game itself often runs at full speed on my system, though even during those times the sound is still quite scratchy/stuttery.  All other games tested that have had sound issues were either based on the game running at less than full speed or could be resolved by turning off spu loop detection.

I've updated the original post with more detail as to what's been tested.  As a point of reference it would help to have a video of the game running smoothly with another linux system **and also** a  recent build.

**Comment by isshininu** [comment]
Game runs full speed for me, no stutter sound at all, but sometimes extremely loud SFX happens and whole sound system of game literally dies until restart.

**Comment by isshininu** [comment]
After recent emulator updates and switching to Cubeb audio frontend I never experienced sound anomalies so far during extended play
