### ISSUE TITLE
Accurate RSX reservation access no longer works with Gran Turismo 5

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8076]
Hello, after build v0.0.9-10219-0f6a0d27 #8008 the setting "Accurate RSX reservation access", which helps with stability on GT5 BCES00569 no longer works with the game. If enabled, the game freezes in the intro stage, or if lucky, a little bit later.
The log with latest master - v0.0.9-10246-a203ff67 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4511626/RPCS3.log.gz)
Log with last working build - v0.0.9-10217-8cb1f4fe
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4511641/RPCS3.log.gz)

Settings used:
LLVM Recompilers
SPU Loop Detection
SPU Mega
Driver wake-up delay 200us

Specifications:
Ryzen 7 2700
RX 580

**Comment by shoey9998** [comment]
This also may have something to do with your CPU. GT5 and Ryzen don't play well yet

**Comment by elad335** [comment]
Update?

**Comment by xddxd** [comment]
Not sure what PR fixed it, but it works now. Closing.
