### ISSUE TITLE
Diablo 3 RoS

### ISSUE THREAD

**Issue by TheWolfOW** [RPCS3/rpcs3#8079]
Crash: "SIG: Thread terminated due to fatal error: Unknown STOP code: 0x20e (Out_MBox is empty)"
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4516505/RPCS3.zip)

**Comment by dio-gh** [comment]
Any extra information? The game hangs every now and then, that's a known issue, that's why it's kept in Ingame.

**Comment by AniLeo** [comment]
Duplicate of #5593
