### ISSUE TITLE
Ratchet & Clank: Future Tools of Destruction has missing models and other graphics during gameplay

### ISSUE THREAD

**Issue by UltimateKamaro** [RPCS3/rpcs3#8084]
![Screenshot 4_22_2020 4_41_56 PM](https://user-images.githubusercontent.com/64123339/80032148-c0b29780-84b8-11ea-8387-8e8361bee2db.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4518959/RPCS3.log.gz)

So the game runs perfectly fine but the models for all the characters (including NPCs and enemies) are invisible.

CPU: Intel Core i7-8750H
GPU: Nvidia GeForce RTX 2080 with Max Q Design

RCPS3 0.0.9-10256-18219afb Alpha

**Comment by NoXCxC** [comment]
Seems like you use OpenGL as Video Renderer. Switch to Vulkan, OpenGL don't work well with the R&C Saga
And if you want to have the game in Full HD, let default resolution to 1280x720 and use Resolution Scale and set it to 150% (1920x1080)
Last thing: if you experincing crash with the Game, try using the fix recommended by isJuhn, here's the link: https://github.com/RPCS3/rpcs3/issues/7990#issuecomment-611144772
I did all the game with these parameters so i don't think you will have any more problems :)

I think the issue can be closed?

**Comment by kd-11** [comment]
@UltimateKamaro Use the optimal settings suggested, we don't have an auto-configure system so the default options are set to the bare minimum to run some games. OpenGL renderer has fallen behind in recent times, but that is a metabug in itself and would need a separate ticket.
