### ISSUE TITLE
evdev support for Wii Classic Controller

### ISSUE THREAD

**Issue by Virusmater** [RPCS3/rpcs3#8089]
## Quick summary
Wii Classic Controller doesn't appear in the evdev controller list

## Details
There is a code in evdev_joystick_handler.cpp
```
if (libevdev_has_event_type(dev, EV_KEY) &&
	libevdev_has_event_code(dev, EV_ABS, ABS_X) &&
	libevdev_has_event_code(dev, EV_ABS, ABS_Y))
```
But Wii Classic Controller doesn't have ABS_X and ABS_Y. It has ABS_HAT1X and ABS_HAT1Y instead:
```
kompot@kompot-ThinkPad-T480s:~$ evtest /dev/input/event24
Input driver version is 1.0.1
Input device ID: bus 0x5 vendor 0x57e product 0x306 version 0x600
Input device name: "Nintendo Wii Remote Classic Controller"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 103 (KEY_UP)
    Event code 105 (KEY_LEFT)
    Event code 106 (KEY_RIGHT)
    Event code 108 (KEY_DOWN)
    Event code 304 (BTN_SOUTH)
    Event code 305 (BTN_EAST)
    Event code 307 (BTN_NORTH)
    Event code 308 (BTN_WEST)
    Event code 310 (BTN_TL)
    Event code 311 (BTN_TR)
    Event code 312 (BTN_TL2)
    Event code 313 (BTN_TR2)
    Event code 316 (BTN_MODE)
    Event code 407 (KEY_NEXT)
    Event code 412 (KEY_PREVIOUS)
  Event type 3 (EV_ABS)
    Event code 18 (ABS_HAT1X)
      Value      1
      Min      -30
      Max       30
      Fuzz       1
      Flat       1
    Event code 19 (ABS_HAT1Y)
      Value     -1
      Min      -30
      Max       30
      Fuzz       1
      Flat       1
    Event code 20 (ABS_HAT2X)
      Value     -2
      Min      -30
      Max       30
      Fuzz       1
      Flat       1
    Event code 21 (ABS_HAT2Y)
      Value     -2
      Min      -30
      Max       30
      Fuzz       1
      Flat       1
    Event code 22 (ABS_HAT3X)
      Value      6
      Min      -30
      Max       30
      Fuzz       1
      Flat       1
    Event code 23 (ABS_HAT3Y)
      Value      2
      Min      -30
      Max       30
      Fuzz       1
      Flat       1
```
I'm not sure if this is should be fixed in rpcs3 or in the linux driver, but i guess that changing it in the kernel wouldn't be possible.

**Comment by Virusmater** [comment]
After your change @Megamouse  it shows up, but as "disconnected". If devs don't have such specific hardware - then I would say don't put much effort in it. Linux driver for wii remotes is a little bit funky and all changes will require actual hardware testing on my "exotic" setup.

**Comment by Megamouse** [comment]
No. I actually forgot something

**Comment by Virusmater** [comment]
Almost there @Megamouse !
Wiimote sends few "KEY_*" events:
from https://github.com/torvalds/linux/blob/master/drivers/hid/hid-wiimote-modules.c
```
	KEY_NEXT,	/* WIIMOD_CLASSIC_KEY_PLUS */
	KEY_PREVIOUS,	/* WIIMOD_CLASSIC_KEY_MINUS */
	KEY_LEFT,	/* WIIMOD_CLASSIC_KEY_LEFT */
	KEY_RIGHT,	/* WIIMOD_CLASSIC_KEY_RIGHT */
	KEY_UP,		/* WIIMOD_CLASSIC_KEY_UP */
	KEY_DOWN,	/* WIIMOD_CLASSIC_KEY_DOWN */
```
My guess will be that in rpcs3 those events got filtered, so I cannot assign dpad and select/start buttons. During the game pressing those buttons generate log messages:
```
 E evdev: Evdev button KEY_DOWN (108) is unknown. Please add it to the button list.
E evdev: Evdev button KEY_UP (103) is unknown. Please add it to the button list.
E evdev: Evdev button KEY_LEFT (105) is unknown. Please add it to the button list.
E evdev: Evdev button KEY_RIGHT (106) is unknown. Please add it to the button list. x2
E evdev: Evdev button KEY_NEXT (407) is unknown. Please add it to the button list. x2
E evdev: Evdev button KEY_PREVIOUS (412) is unknown. Please add it to the button list. x2
```
So can you pls add them to the button_list? KEY_PREVIOUS should be select and KEY_NEXT should be start. Dpad button naming is pretty obvious.

Thank you!

**Comment by Megamouse** [comment]
Honestly, this looks more like the driver is crap

**Comment by Megamouse** [comment]
But yeah. I can add them

**Comment by Megamouse** [comment]
Probably Not today though

**Comment by Virusmater** [comment]
> Honestly, this looks more like the driver is crap

this is a less polite way of saying 

> Linux driver for wii remotes is a little bit funky

**Comment by Virusmater** [comment]
Works now, thanks! Also I wasn't able to dash in Scott Pilgrim (you need to tilt analog to the max), so create a small utility to calibrate evdev gamepads:
https://github.com/Virusmater/evdev-joystick-calibration

**Comment by Megamouse** [comment]
We also have something called stick multiplier for such extreme cases
