### ISSUE TITLE
freeze basara 4 sumeragi

### ISSUE THREAD

**Issue by TalayGG** [RPCS3/rpcs3#8091]
F {PPU[0x1000017] Thread (decodeProc) [0x00a87ea8]} VM: Access violation reading location 0x75b933b0 (unmapped memory)
how can i fix it?

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
