### ISSUE TITLE
RPCS3 UI Corruption (Linux)

### ISSUE THREAD

**Issue by Niroc** [RPCS3/rpcs3#8095]
Hi,

I've not used RPCS3 in about a year and it turns out the UI in most recent builds is like the following...
![Screenshot_2020-04-25_02-31-50](https://user-images.githubusercontent.com/12100786/80268157-092aaa80-869d-11ea-85ed-683af9d26d95.png)

I've spent a bit of time tracking down the last build that where the UI was drawn to screen correctly which is build "rpcs3-v0.0.8-9546-76271800_linux64.AppImage" as you can see below...
![Screenshot_2020-04-25_02-36-22](https://user-images.githubusercontent.com/12100786/80268257-953cd200-869d-11ea-93ad-c82da4a91c57.png)

I'm not aware of any debug commands I can run to make RPCS3 output logging info outside of a game but, I can confirm that the AppImage does not output any error to console when executed from the command line

The desktop is just a standard X-server using openbox as the window manager. Here some info about my pc... 

Processor Information:
    CPU Brand:  Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
    Speed:  3700 Mhz
    8 logical processors
    4 physical processors

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.34-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12008000
    X Window Manager:  Openbox

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 870M/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 430.64
    Primary VRAM: 6144 MB

Here's a link to more comprehensive details about my hardware...
https://gist.github.com/Niroc/ab1f133f7e79e9e0d7932670b5f6cdc5

**Comment by Niroc** [comment]
Also, I can still run games perfectly fine on the newest builds. I just can't configure anything.

**Comment by AniLeo** [comment]
For the record, I use Manjaro and I'm not getting any of these issues, regardless of using AppImage or local build

**Comment by Niroc** [comment]
ok, well I am running qt 5.14.2
![Screenshot_2020-04-25_03-23-36](https://user-images.githubusercontent.com/12100786/80269054-60804900-86a4-11ea-95cd-dc930a855efe.png)

**Comment by Megamouse** [comment]
My best guess is that this is yet another variation of #8052

**Comment by bustatu** [comment]
It happens to me too, but only if I run the app as root. Otherwise it runs normally.

**Comment by Megamouse** [comment]
Why would you run it as root?

**Comment by bustatu** [comment]
idk, I just told you when that happens to me. I don't usually run it as root but I did it once by mistake and the GUI got corrupted

**Comment by Niroc** [comment]
The export command worked, Thanks. 

Also, it definitely wasn't running as root as, it never asked me for a password.

**Comment by christianhassler** [comment]
similar issue here on arch linux i3wm. not exactly like your screenshot (even worse in my case: menu text totally unreadable), setting QT_AUTO_SCALE_FACTOR=0 as suggested in #8052 fixed it for me.

**Comment by Megamouse** [comment]
@Niroc can you please test PR #8649 ?
You should not need the export with the PR.
