### ISSUE TITLE
[Feature Request] Specific Analog Angle using Keyboard/Hotkeys

### ISSUE THREAD

**Issue by AkagiShiroe** [RPCS3/rpcs3#8096]
for example i did setup my analog with upper and left to a hotkey, pressing the two key will result in left direction rather than from up to left motion, so i want an option to make a certain button pointing a certain direction (for example 320 degree) of course if it was possible, if no.. just close this~

**Comment by Ghostotakoi** [comment]
Yes, is had to make a macro to play Ashura´s Wrath and make the 360 degrees stick rotation with my keyboard, but only had this issue with left stcik because my right stick is mapped to my mouse.

**Comment by Megamouse** [comment]
There's stick interpolation implemented, which is already a huge commitment towards keyboard users.
I don't see why anyone would need a key for 320° rotation or similar. That's both a horror GUI wise as well as codewise.

**Comment by sampletext32** [comment]
Of course if you don't want to implement it yourself.

**Comment by AkagiShiroe** [comment]
![image](https://user-images.githubusercontent.com/14356240/80273843-71fb3c80-8708-11ea-8ea8-fc000bd70731.png)
this is an specific example reason why i am needing a hotkey for specific analog angle, but interpolation does work, i guess its better to be closed and forgotten..

**Comment by Megamouse** [comment]
There's a simple fix. Use a controller xD

But seriously, this feature is not really feasible without implementing some really really really weird special snowflake settings

**Comment by AkagiShiroe** [comment]
got it, ill just bring my controller instead xD.. thanks for kind reply
