### ISSUE TITLE
"Local RSX REPORT offset out of range!" in BCES00664 - WipeOut HD Fury

### ISSUE THREAD

**Issue by andersfischernielsen** [RPCS3/rpcs3#8100]
## Quick summary
Awesome work guys, WipeOut HD Fury is very close to being completely playable! Though I'm seeing a crash after one or two races, usually. The emulator freezes, then crashes. The last output before the crash is: 

```
E {PPU[0x1000011] Thread (fios mediathread) [0x016e1ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00664DATA/USRDIR/data/ribboneffects/textures/smoke_trails_opacity_ramp.tga” [3]
E {PPU[0x1000036] Thread (LoadingScreenThread)} SYS: Stat: 'cellNetCtlGetState' failed with 0x80130101 : CELL_NET_CTL_ERROR_NOT_INITIALIZED [x65]
S {RSX Decompiler Thread} RSX: New program compiled successfully x12
E {RSX [0x052dfc0]} RSX: FIFO: CALL found inside a subroutine (last cmd = 0xc28a7d52)
E {RSX [0x05027c0]} RSX: FIFO error: possible desync event (last cmd = 0x401f9c6c)
S {RSX Decompiler Thread} RSX: New program compiled successfully x3
E {RSX [0x010b8f0]} RSX: Invalid NV4097_SET_INDEX_ARRAY_DMA value: 0x41680
E {RSX [0x0513bc0]} RSX: FIFO error: possible desync event (last cmd = 0x42d527a8)
F {RSX [0x00a24b8]} SIG: Thread terminated due to fatal error: rsx::get_address(offset=0x44130, location=0x66626660): Local RSX REPORT offset out of range!
(in file d:\a\1\s\rpcs3\Emu\RSX\rsx_methods.cpp:571)
```

I've also attached the full log(s). 

I'm running a Ryzen 5 3600 and a RTX 2070 Super w/ most recent drivers. Sometimes the game runs for a while with no issues then suddenly crashes. Sometimes it's in the very first race. Other than that, the game runs smooooth, even with 120 FPS+ (as seen in the recent [video](https://www.youtube.com/watch?v=XucwGzH9bN4)). 

I'll be happy to try to force the crash again, if you need me to. Really keen to see this game run!

[TTY.log](https://github.com/RPCS3/rpcs3/files/4533792/TTY.log)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4533791/RPCS3.log)

**Comment by elad335** [comment]
increase driver wake up delay (advanced settings) and close this issue.

**Comment by andersfischernielsen** [comment]
Thanks!
