### ISSUE TITLE
Suggestion: change the logic of Time Played function, cause it doesn't work as suppoused to (broken)

### ISSUE THREAD

**Issue by TonyAMG** [RPCS3/rpcs3#8104]
## Quick summary
**Time Played** is non informative due to crash in 80% times when you stop emulation (doesn't matter how - cross on window, **Stop** button, or **Send Exit CMD**) of any game.
In this case played time doesn't write in _persistent_settings.dat_ file. It will be written only if emulation stops correctly.

## Details
So I suggest to change the logic of saving played time data.
For example - save it every minute to _persistent_settings.dat_ file, instead of saving it once, only when emulation stops correctly.
In this case all time played will bee reliably saved no matter what.

sorry for my Eng

**Comment by marcoluc97** [comment]
So, just to ask, but why RPCS3 can not be close without crashing? If this question is spam, feel free to delete it.
