### ISSUE TITLE
Gran Turismo 6 no longer goes in-game

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8109]
Hello, after PR #8008 (rpcs3-v0.0.9-10219-0f6a0d27) Gran Turismo 6 BCES01893 v1.05 no longer goes in-game. The game just freezes at the SCE Presents screen.
Log from last working build (rpcs3-v0.0.9-10217-8cb1f4fe): 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4538255/RPCS3.log.gz)
Log from latest master (rpcs3-v0.0.9-10274-4f71c570):
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4538262/RPCS3.log)

Specifications:
Ryzen 7 2700
RX 580

**Comment by LaneSh4d0w** [comment]
Which game version ? I've seen around that people said not to update prior to v1.05.

I actually seem to get the same issues on ver. 1.08, and i want to see the reaction on the latest version.

I get thread softlocks in my side, with RPCS3 completely freezed, which is kind of annoying over time.

**Comment by LowOrbitNZ** [comment]
I get this error on all versions of the game. 

F {SPUW.1} SIG: Thread terminated due to fatal error: Verification failed (e=0x6): file::write
(in file d:\a\1\s\Utilities\File.cpp:1075)

**Comment by LaneSh4d0w** [comment]
Never ran into that issue before to be honest @LowOrbitNZ .
I got this : 
`E {PPU[0x1000000] Thread (main_thread) [0x019cff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]

E {PPU[0x100002c] Thread (PDI) [0x017a0278]} SYS: 'cellSaveDataAutoLoad2' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
E {PPU[0x100002d] Thread (PDI) [0x017a0278]} SYS: 'cellSaveDataAutoLoad2' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
E {PPU[0x1000009] Thread (kZC--) [0x01aa1f44]} SYS: 'sys_fs_unlink' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/tmp_db_work.dat” [1]
E {PPU[0x1000009] Thread (kZC--) [0x01aa1f44]} SYS: 'sys_fs_unlink' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/tmp_garage_work.dat” [1]
E {PPU[0x1000022] Thread (gFKsE) [0x008467cc]} SYS: '_sys_timer_start' failed with 0x8001000a : CELL_EBUSY [1]`

**Comment by LaneSh4d0w** [comment]
UPDATE : Latest commit known to make Gran Turismo 6 work is 10215 (10288 crashes ingame)

**Comment by LaneSh4d0w** [comment]
On my testings, pull #8008 (Build 10219) is the build that made GT6 unusable.

**Comment by xddxd** [comment]
Seeing as it hasn't been mentioned in the issue, I'll add that after pull #8008 the game *does* boot, but only if there is no savefile.

**Comment by arabek** [comment]
breaks always after this warning is thrown in the logs:
```
W {SPU[0x4000100] Thread (PDICellSpursKernel4) [0x0861c]} SIG: Page_fault writing location 0x611e0000 because of using unmapped memory
W {PPU[0x1000001] Thread (MpAnk) [0x01996908]} sys_mmapper: sys_mmapper_allocate_shared_memory(ipc_key=0xffff000000000000, size=0x10000, flags=0x200, mem_id=*0xd0014c10)
W {PPU[0x1000001] Thread (MpAnk) [0x01996948]} sys_mmapper: sys_mmapper_map_shared_memory(addr=0x611e0000, mem_id=0x8068200, flags=0x0)
```
tested on version v1.02 up to v1.05 of the game

**Comment by elad335** [comment]
Test with #8269

**Comment by elad335** [comment]
Figured the bug, will try to fix soon this *non-tsx* issue.
