### ISSUE TITLE
msvc build errors

### ISSUE THREAD

**Issue by garciaadrian** [RPCS3/rpcs3#8111]
## Quick summary
I get a bunch of linker errors when building the solution

## Details
[Build log](https://gist.github.com/garciaadrian/8cf1a4e2810f7b3fc63a63f76ca5a33a)

**Comment by Megamouse** [comment]
Clean and rebuild

**Comment by MSuih** [comment]
Make sure all submodules are up to date: `git submodule sync && git submodule update`. After executing this, clean and rebuild.

**Comment by garciaadrian** [comment]
I'm still getting linker errors, I've tried using the precompiled libraries and building them myself but I still get these errors

**Comment by clienthax** [comment]
What configuration are you using?

**Comment by garciaadrian** [comment]
Release - LLVM

**Comment by garciaadrian** [comment]
Okay, It looks like the latest version of the vulkan sdk brings those libraries so that's why I'm getting these errors

**Comment by DerTodIstEinDandy** [comment]
I built the solution on windows 10 with VS2019. I had to manually set Preferred Build Tool Architecture to 64 bit for the emucore project, otherwise the compiler threw out of heap space  error C1060. Am I missing some step in the build setup?
