### ISSUE TITLE
rpcs3 compile .obj files wrong Intel's codename 

### ISSUE THREAD

**Issue by Kojikun1** [RPCS3/rpcs3#8112]
Rpcs3 shows wrong name when  compile .obj files
my processor is Coffee-Lake 9 gen processor i5-9300H
and compiled files are skylake.obj
![rpcs3](https://user-images.githubusercontent.com/29433315/80498401-0e5c5380-8942-11ea-95f3-ebb8d77db5a5.png)
![compileobj](https://user-images.githubusercontent.com/29433315/80498412-12887100-8942-11ea-9ac7-bc9faf91f5e8.jpg)

**Comment by sampletext32** [comment]
I think this ain't a mistake, because my 9750H also produces skylake.obj
And 10210U does the same.

**Comment by Nekotekina** [comment]
Works as expected. Really "new" processors are cannonlake or icelake.
