### ISSUE TITLE
Demon's Souls no more in game since 0.0.9-10285

### ISSUE THREAD

**Issue by Dani1977** [RPCS3/rpcs3#8116]
Hi
Since 0.0.9-10285 (i also try 10286 and 10287) I have black screen on starting Demon's Souls, I have to kill rpcs3 with TaskManager.

Last working version is 0.0.9-10284

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4548234/RPCS3.log)

Regards

**Comment by kd-11** [comment]
10285 is from https://github.com/RPCS3/rpcs3/pull/8114, verify that turning off TSX hides the problem. Tagging @elad335 to take a look.

**Comment by LonelyDragon123** [comment]
@kd-11 I think it will, because I have problems with many of games after that PR.
Disabling TSX fixed a problems.

**Comment by Nekotekina** [comment]
@Dani1977 try https://github.com/RPCS3/rpcs3/pull/8117 if you don't mind

**Comment by Dani1977** [comment]
@Nekotekina , i tried 10290 
the problem is still here and the PC has become unstable and I had to turn it off, because I was unable to kill rpcs3 with TaskManager. I wasn't able to create log, sorry

**Comment by elad335** [comment]
its fixed in #8118

**Comment by Nekotekina** [comment]
Feel free to reopen if the problem still occurs
