### ISSUE TITLE
The Darkness [BLES00058] Broken color grading/LUT

### ISSUE THREAD

**Issue by Joris-truly** [RPCS3/rpcs3#8122]
The game is **fully playable,** stable frame rate and can be completed without tweaks. It only renders post-effects incorrectly. mainly bloom is over saturated.
 
![Untitled](https://user-images.githubusercontent.com/64547407/80622844-a729c680-8a49-11ea-80fc-fecb2b67b9ee.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4553068/RPCS3.log.gz)

Win 10
i7-5930k 12 thread 4ghz
GTX 1080

observation: The chronicles of riddick dark athena runs on the same engine (albeit newer) and renders bloom and colors correctly.

**Comment by mfdsrax2** [comment]
Did you enable 'Force CPU Blit' and 'Write Color Buffer'?

**Comment by dio-gh** [comment]
No need to test either cpu blit or wcb, they dont fix it. I'm surprised no ticket was opened about this previously, it's well known for quite some time. Good to hear its that close to reaching the Playable status though.

**Comment by Joris-truly** [comment]
Quick update: Tested vblank set to 120hz. Runs 60 fps quite smooth on mid range CPU!
Res scaling seems broken (everything turns green). probably in correlation with the post-processing issues.

**Comment by mfdsrax2** [comment]
I am using i7-7700HQ and GTX 1070. Only have ~20 fps

**Comment by Joris-truly** [comment]
> 
> 
> I am using i7-7700HQ and GTX 1070. Only have ~20 fps

Try Vulkan, vblank 120hz, Restricted rendering mode = on, 
I get 60fps (with high draw call exceptions) on a i7-5930k @4ghz from 2014

**Comment by dio-gh** [comment]
I used to get 60 fps on my 7700HQ, so thats probably miconfiguration.

**Comment by mfdsrax2** [comment]
Previously this game requires 'Force CPU Blit' and 'Write Color Buffer' or it won't go ingame.
As for now it seems fine without them. I have ~40 fps now. Thanks for the tip.

**Comment by dio-gh** [comment]
I tried creating a fresh RRC on latest master, but on replay it dies with concurrent access. Here it is anyways:

RRC: https://drive.google.com/file/d/1vOBRTATEy5LEhq2A9VIz-2oUXT4vUwFc/view?usp=sharing
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4706802/RPCS3.log.gz)

Something made RRCs insanely less compressible recently btw, no idea why.

**Comment by kd-11** [comment]
This game has broken color grading, there is nothing wrong with brightness adaptation. The LUT applied seems off.

**Comment by kd-11** [comment]
This game is naturally rather bloomy (it came out around *that* time) so the color grading LUT is actually fine. There is a dynamic exposure used to control the final post-processing shader that does both tone mapping and color grading in one pass and it is set too high (about 1.4-1.5 brightness which is insanely high) This means the post-processing itself is fine, its the input values that are problematic. I'll try and figure out where this calibration is done in-engine.

**Comment by Joris-truly** [comment]
Their later title **The Chronicles of Riddick: AoDA** uses the same engine. 
https://www.youtube.com/watch?v=0B-AjyNSc5w (2 year old upload)
Maybe non of this info is useful, but the color grading seems fine here.

**Comment by Shoegzer** [comment]
I wonder if this issue shares a common cause (high dynamic exposure settings) with Dead Island, as reported in #6798?

**Comment by Xpmaster2002** [comment]
The chronicles of riddick i remember having older shaders needed to run the game engine properly within windows early on before it was updated to handle the newer shader revisions, i'm wondering if the lighting commands are different for older shader revisions and if that would impact the emulation in anyway.... Idk how the graphic engine is programmed into rpcs3, So Not sure... :-)

**Comment by dio-gh** [comment]
@kd-11 This doesn't seem like an RSX bug in the slightest, so you may wanna unassign. A user posted this today to the main RPCS3 channel:
![image](https://user-images.githubusercontent.com/10439488/117367505-8dc02380-aec2-11eb-9d57-c63cb9d261cb.png)

As you can see, the same exposure issue happens on Xenia as well. The only thing I can think of then is that this is some PPU bug, as that's the only component the two emulators would share.

**Comment by Shoegzer** [comment]
Interesting.  I wonder too what Dead Island looks like in Xenia, if it really is related then I would expect it to have the same overexposure issue there too.

**Comment by kd-11** [comment]
@dio-gh Thanks, I suspected as much. The game is calculating calibration values that are way off, but I never got around to analyzing the cell code that deals with it. Interestingly, giving dummy data from RSX back to CELL does not improve the situation (it doesn't matter if all RSX->CELL transactions are replaced with 0s 1s or any other arbitrary value in any format I tried, the bloom is just always overdone. 
I'll keep it assigned to me anyway just in case, at the very least just so that it isn't forgotten.

**Comment by Anil1992-rgb** [comment]
Go to Manage, and game patches, then at bottom click download latest patches. Go to the darkness (BLES00058)or(BLUS30035) which ever one you have and set lower exposure to 0.6 or 0.3.

PPU-eb133a3b9430baa45d39e9e00ba8cf9cea89154c:
  Extended FOV:
    Games:
      "The Darkness":
        BLES00058: [ 01.03 ]
    Author: illusion
    Notes: 
    Patch Version: 1.0
    Patch:
      - [ bef32, 0x10AEAEC, 1.25 ]
  Lower Exposure:
    Games:
      "The Darkness":
        BLES00058: [ 01.03 ]
    Author: illusion
    Notes: 
    Patch Version: 1.0
    Patch:
      - [ bef32, 0x10AC328, 0.3 ]

PPU-9ef94f24f84f5923f9c88557e33c2ffab380fb7b:
  Extended FOV:
    Games:
      "The Darkness":
        BLUS30035: [ 01.03 ]
    Author: illusion, Aphelion
    Notes: 
    Patch Version: 1.0
    Patch:
      - [ bef32, 0x10AEAA4, 1.25 ]
  Lower Exposure:
    Games:
      "The Darkness":
        BLUS30035: [ 01.03 ]
    Author: illusion, Aphelion
    Notes: 
    Patch Version: 1.0
    Patch:
      - [ bef32, 0x10AC2F0, 0.3 ]

**Comment by dio-gh** [comment]
I'm aware that the game can be patched to look more correct, but
 - the exposure is dynamic throughout the game, so the correctness will vary,
 - that's a workaround not a fix.
 
I'm sure a fix will be eventually found in some years, that's what this tracking ticket is for.
