### ISSUE TITLE
arcade stick stuck after #7764 (linux)

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#8128]
After #7764, my custom arcade stick (dragonrise) always registers a left input as soon as I touch it.
rev9892 is working fine.
rev9895 has the problem.

Initial state:
![Capture_156](https://user-images.githubusercontent.com/7478580/80791070-d72fb180-8b90-11ea-9263-0088f5e20cf0.jpg)

When I press left: it's ok
![Capture_158](https://user-images.githubusercontent.com/7478580/80791073-d860de80-8b90-11ea-983a-3824d81d9ea0.jpg)

When I don't touch the stick, it's still sending a digital left (but not analog left, which is fine):
![Capture_157](https://user-images.githubusercontent.com/7478580/80791072-d7c84800-8b90-11ea-9ccb-946c0a92fe79.jpg)
[RPCS3-Gamepad.zip](https://github.com/RPCS3/rpcs3/files/4562938/RPCS3-Gamepad.zip)

Another problem (not related to the pr): the ds4 controller has a wrongly centered right analog stick with evdev (no pb with the Dualshock 4 handler, so it's a minor problem, but I wanted to report it nonetheless).

**Comment by Megamouse** [comment]
It would be more interesting to see what you configured in your gamepad settings

**Comment by Megamouse** [comment]
nevermind.
can you please test the mentioned Pull Request if you can ?

**Comment by Megamouse** [comment]
Reopen if the issue still exists.

For your ds4 issue there's a solution already.
See:
https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration#Analog_sticks_not_centered_with_evdev_pad_handler

**Comment by toccata10** [comment]
That was quick ! It's now fixed. Thanks.
