### ISSUE TITLE
Logging flood on some messages

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#8135]
Some log messages are flooded in the log file in a very fast rate, such as sys_net's exceptfds not implemented. It should be logged only once, or have reduced logging level

Ideally, other functions should be reviewed and have their logging adjusted, as in some cases there's nothing gained from a debugging standpoint from logging the same function many times when it's being executed in loop

**Comment by LaneSh4d0w** [comment]
You could do what you usually do in RPCS3's GUI user log, when the number of Times it repeats gets a number at it's right, and replicate it over the written log file.

(by the way, isn't sys_net_bnet_select actually socketselect (int socketselect(int nfds, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, struct timeval *timeout) ) ? I could be mistaking this one.)

**Comment by Megamouse** [comment]
The log mention log message was silenced already.
I feel like this is a very dynamic problem, so it's not really worth having an issue for no specific reason.
