### ISSUE TITLE
NPEB01356 bad timing (game too fast)

### ISSUE THREAD

**Issue by lemmel** [RPCS3/rpcs3#8143]
Hi !

It seems that there is some kind of bad timing as the game runs too fast to be playable, and the introductory video is not visible (some images here and there are visible; maybe the same problem of timing).
The game is noted as Playable in the https://rpcs3.net/compatibility.

I can provide more information if instructed because I'm myself a developper; I already built a debug version of RPCS3 (975 Mo !)

Thanks for all the fantastic work !

## Details
Tested behaviour with both Linux and Windows, but here is only data about Linux:
- git cloned from this : 2b75df22d92e386c55ca34fc08689a0125c17cec (04/09/20 19:05:43 +0300)
- OS: linux 5.5.0-2-amd64 SMP (Debian 5.5.17-1)
- logs: [RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/4567877/RPCS3.log.zip)
- ldd bin/rpcs3:
```
Qt5.14.1
libasound2:amd64         1.2.2-2.1      
libasyncns0:amd64        0.8-6+b1       
libatomic1:amd64         10-20200418-1  
libbsd0:amd64            0.10.0-1       
libc6:amd64              2.30-4         
libdbus-1-3:amd64        1.12.16-2      
libevdev2:amd64          1.9.0+dfsg-1   
libffi7:amd64            3.3-4          
libflac8:amd64           1.3.3-1        
libfreetype6:amd64       2.10.1-2       
libgcc-s1:amd64          10-20200418-1  
libgcrypt20:amd64        1.8.5-5        
libgl1:amd64             1.3.1-1        
libglew2.1:amd64         2.1.0-4+b1     
libglib2.0-0:amd64       2.64.2-1       
libglvnd0:amd64          1.3.1-1        
libglx0:amd64            1.3.1-1        
libgpg-error0:amd64      1.37-1         
libgraphite2-3:amd64     1.3.14-1       
libharfbuzz0b:amd64      2.6.4-1        
libicu63:amd64           63.2-3         
liblz4-1:amd64           1.9.2-2        
liblzma5:amd64           5.2.4-1+b1     
libogg0:amd64            1.3.2-1+b1     
libopenal1:amd64         1:1.19.1-1+b1  
libopengl0:amd64         1.3.1-1        
libpcre2-16-0:amd64      10.34-7        
libpcre3:amd64           2:8.39-12+b1   
libpng16-16:amd64        1.6.37-2       
libpulse0:amd64          13.0-5         
libsdl2-2.0-0:amd64      2.0.10+dfsg1-3 
libsndfile1:amd64        1.0.28-7       
libsndio7.0:amd64        1.5.0-3        
libstdc++6:amd64         10-20200418-1  
libsystemd0:amd64        245.5-1        
libtinfo6:amd64          6.2-1          
libudev1:amd64           245.5-1        
libvorbis0a:amd64        1.3.6-2        
libvorbisenc2:amd64      1.3.6-2        
libvulkan1:amd64         1.2.135.0-2    
libwayland-client0:amd64 1.18.0-1       
libwayland-cursor0:amd64 1.18.0-1       
libwayland-egl1:amd64    1.18.0-1       
libwrap0:amd64           7.6.q-30       
libx11-6:amd64           2:1.6.9-2      
libxau6:amd64            1:1.0.8-1+b2   
libxcb1:amd64            1.14-2         
libxcursor1:amd64        1:1.2.0-2      
libxdmcp6:amd64          1:1.1.2-3      
libxext6:amd64           2:1.3.3-1+b2   
libxfixes3:amd64         1:5.0.3-2      
libxi6:amd64             2:1.7.9-1      
libxinerama1:amd64       2:1.1.4-2      
libxkbcommon0:amd64      0.10.0-1       
libxrandr2:amd64         2:1.5.1-1      
libxrender1:amd64        1:0.9.10-1     
libxss1:amd64            1:1.2.3-1      
libxxf86vm1:amd64        1:1.1.4-1+b2   
zlib1g:amd64             1:1.2.11.dfsg-2
```

**Comment by Nekotekina** [comment]
Did you try to set Frame Limit?

**Comment by lemmel** [comment]
With Frame Limit and the release version, the game runs correctly.

Yes, I know ... I should have tested that ... Sorry :-S It's my first time with RPCS3
Nevertheless is it normal to have to set such a parameter ?

**Comment by MSuih** [comment]
We do not have game-specific default settings yet, so each game needs to be configured by the user. PS3 had a 60 fps cap and some games start to misbehave if you go above it.

Also, please refrain from removing vital imformation from logs such as operating system and hardware information.

**Comment by lemmel** [comment]
Ok for the 60fps cap, but how the ps3 detect when it must run at 30fps ? Or maybe the option is there but for consistency but will be not required ? (there is such a value in the selector)

I didn't remove information from the logs (I just replaced my name with XXXX); could you be more specifics ?

**Comment by sampletext32** [comment]
I've just realized. Maybe rpcs3 should include official settings for games? The ones that are already tested and confirmed to be correct. This can help newbies. And also should decrease #help channel questions.

**Comment by AniLeo** [comment]
Not an issue, works with frame limiter as expected

Some suggested settings are already on wiki, we don't bundle preset settings in the emulator
