### ISSUE TITLE
Skylanders Portal can't have 2 skylanders at the same time

### ISSUE THREAD

**Issue by Cerrebe** [RPCS3/rpcs3#8144]
In skylanders coop mode you're supposed to have 2 skylanders on the portal at the same time, you can load one skylander, but when you load another one, it removes the one loaded before.

**Comment by bevanweiss** [comment]
@Cerrebe are you able to supply a log for this?
And are you talking about having two portals installed (i.e. two USB devices) or a single USB device, but with more than one token on the portal?
I would expect that if it's the second, then this should be out of our control.  The game would then be talking directly to the portal, and any token additions / removals should be 'discussed' between the game and the portal.  We try to avoid getting down to the actual data structures sent backwards and forwards between these custom USB devices, it becomes wayyyyyyy toooo annoying to reverse engineer those protocols.

**Comment by bevanweiss** [comment]
@Cerrebe It would be great if you could try this again under my PR (note: it doesn't currently have emulation capability... so you'd need to have two Skylander USB devices plugged in).  PR #9096 
[Windows](https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzQ0MDEvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitXaW5kb3dz0/content?format=zip)
[Linux](https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzQ0MDEvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitMaW51eA2/content?format=zip)
