### ISSUE TITLE
BLUS30736 SoulCalibur V sub-60FPS inconsistent performance

### ISSUE THREAD

**Issue by rdeleonp** [RPCS3/rpcs3#8146]
## Environment

- CPU: Intel Core i7-6700K
- RAM: 32 GB
- SYS: Windows 10 (64 bit)
- GPU: AMD Radeon RX 480
- DRV: 2020.0421.1645.30151

## RPCS3

- RPCS3 v0.0.10-10321-72bef8dd Alpha | HEAD | Firmware version: 4.86
- API: Vulkan
- Write Color Buffers: true
- Strict Rendering Mode: true
- MLAA patch.

## Steps to reproduce/compare

- Boot BLUS30736.
- Expected behavior:
  - Consistent 60FPS.
- Observed behavior:
  - Sub-60FPS performance.
  - Wildly variable frametimes.

## Video Link 

- [Video Link](https://youtu.be/nmoxs29r_4M)

## Log:

- [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4568727/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Incorrect settings used (i.e. not using SPU LLVM), falls under support request

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by rdeleonp** [comment]
@AniLeo SPU LLVM provides same results.

Will try the other channels.

Cheers.
