### ISSUE TITLE
Dante's Inferno Freezes at some point

### ISSUE THREAD

**Issue by Skorpion96** [RPCS3/rpcs3#8147]
here is the log:
RPCS3 v0.0.10-10321-72bef8dd Alpha | HEAD | Firmware version: 4.86
Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz | 6 Threads | 7.87 GiB RAM | TSC: 2.904GHz | AVX+ | FMA3
S UPDATER: RPCS3 is up to date!
S DS4: Controllers found: 1
S Input: DualShock 4 device 0 connected
S GUI: Boot successful.
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-EihTyiCrMW1hfFUVt3mbfG-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-npuQgofGJj5sE1RVhfA6CG-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Yqes1cHZqWXVxWi5gGNcvS-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-2aXSktxVyYcf8S2J9GqGPN-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-noSnnhEo7XKXomjLYFJwkH-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Uq2sRngoiYtNQG6KrJGWqp-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-naWygp167CVdRcRazGQc4y-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-EH928hM2AgzAwC0QxS0UCr-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-rx5cnhJjYzJEMweuWkh7uf-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-NTqQociw7mtqKt7EH7ir0J-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-rddpGnx7Gj8iK2oQWht7fk-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-jJLJMSVMxwtFKsnjngQaFZ-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-qh5fwF2U8qQ3yPwvTM7X9Z-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-dVNx6GdjpNhMHFvsmCHGRa-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-tC5tcuUhAz0p2FK4yiqJN2-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Lvi1QNgd3zEhEL3ierb4it-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-p3PWxvLsnECJC2SC17QVMK-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-3f264u7yYvWUg26ZTeXPPf-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-aPK7r49z6vXZe6ufacWqgv-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Foj6xEqggkhJAvf8j7foiz-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-rze92djY7oSGr9YEVo1dvS-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-KRHR4pngeV4NkiPnTXvvPE-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ooAak81A8vnM66dsrGk4f0-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ebMUJRjm5Cn2V5RhuPWxcq-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-b5Q3HzfpvcRPeXMCS0zvXP-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Z4SHPm2ZEk1qkacduvXfrs-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-JFwZoZGmcgb7fso75QrzRn-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-nPeAYbGwU6SLWqwU8qRQaV-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-TNQyziCzEHJgK9Hbcf0NHq-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-PdnZRTgPs0L09pNN1riiYe-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-FbnS99ZuVqq7CNQNW6tQH3-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-5YMYWNWxLHrPm5kuu5E88v-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Hu1j7yj9jJgRUGd3XuErq3-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-U8M911r9iF4r3nPYV8kNZK-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-JSHztiE9UH1tFSmJM5Lsca-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-WSFE0A4C25aWj48waeuuTr-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-aK8vK4AuvGkciS4TVc1czf-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-rctXAYMEya6Z8NgcGWE9oH-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-RN8p6j9HHpoXSkxqKLqpLx-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-V1hKU3W8adEj4wc0MvjuHu-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-CM68Amxx7MtgV81FjNUpgA-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-CtYeQ7TEH5NZau3HaT998r-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-suGqpTCZq0H0060hGKpFs6-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-AN12EXqZisJ3rdZ4AphwMP-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Qsf6XyhT1GCgAYkSCxn2Ns-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-5TNwKGgyYcdkCjzLPJLuEK-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-CaieCXh5gKv2ygj9xSrnPe-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-rjWLSkcMcS7pK6zjE5dQ8y-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-nQQQnwwNV8u5fccJkwG7HP-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-JCG0V7jywjWgfzViXRkERM-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-0pz3KeHF2ZKdJ7TnYXxg31-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-6KMiFGejWSK162sbNMiSE9-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-LN4HHCbUzPfa1Kv4Kb7j5U-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-TXZWaPHztxNnngKERLLjY8-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-kVrEAL2kx70MiE3sdLdmva-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-QbG994uAHSw4Sy3VRMXjyo-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Pm0Wagx6QhVL8qzen0yJz0-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-9cJTCkHkzZcgafVRY8n7wF-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-FdYKq0cyLHTda0vczjjN1z-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-GXMmAAgWqyyoqQQP573vLi-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-aSLgW0gAh2xgxSC3rU5J31-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-8i0Ubb80GhgRU3XzNQ52tT-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-e0PUS481mpCsbFgkMAS0As-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-G5JPE8246X534QAUFGoaKZ-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-8t2X0VwtKe6oZ4zzzrRwZR-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-tvaGnAmkg2Hm7KEcq26wVt-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-69SnE5kR86Thx1gawGTNwN-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-U3XFvcCgkoh4vtvqjdEsmW-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-f24FYT18ayYGr74omJMFEN-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-evCNWGUMYfYNmMGF2hpTce-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-kH1XztVRjb0A3fR6trJ2Ar-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Twp7kQYsQxojVxAVx7ynth-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-FLE5XGk44TpVawRjJTQ7Wh-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-PfQGRzNrZ3060znNYp3aUH-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-2JNLVdH2tfmTF0EdGht045-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-SPmZ0m8qNrY42oN9HVHKZx-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-aqHCCToZ9WrgfLWk5h8sVk-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-jA3CRPrAubWhV8P7j5Y3at-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-JX6cuVSXmib31ofqo4E16z-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-1kzNb46bXwuXF1nkLo8sE2-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-0ALa0ER3jwb4i8TZEseow3-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-hx9LZ0eX59ffHVf75uTWKx-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-s0zzUJFYamrpAwxbxFybWF-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-d055gz96pu9K6As55TzCT9-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-eXCmPpitLScM3HE281Jiia-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-RC4EbW6pkoE3R7ThvvhKKX-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-HGyKyz9CeMRGn7CAhRnzsi-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-0YLH5ikY6gU40EK8WzG6FP-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-i9V0j0J4ya865HxiabAaVK-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Ybf571t94dTeQyddQxkj8e-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-SaQ5dWETSra4Rs4nmWisMX-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-sHM94aMtsaCaA05WS3pZad-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-48VT50tgUTN9SJJzuhz8oU-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-NF7i5Zw7KNKsgbqGGy2Kbi-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-0sZvF6iUY4dUG0VPJG3CcA-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Y2NHRnaJboMbwVkrJLFQ44-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-LzgsHuKgLe597072MS0w4U-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-PsK2uNCy2j4QM48jwoPSP6-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-KWCiJRaS1AzC1Ck6gQi2aM-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-sv1hWFj31GamapZbCGqjKb-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-qNtQXySfm2p5dozQpU86zG-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-V1Lmb6Pa60M9hApQs0EhSy-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-PC3TZ7uvmPMgufWwtwZuyj-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-K3UUTs8mtUNYUcSFWyAJL2-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-EUxSQG2NaXNFXGxbZ8Z97s-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-s6pFbrNew0PcPfPiMhj02s-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-VvCxEeaqeFirZxqnzu3qhm-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-HdzGhKT3KMvffQRtUfmZCP-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-bgoYdoLvoxwMGMzXESzHrZ-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-h4EY3cKiSTstS8bNZknLAa-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-5dLUorh83ti1anjyPh2J4F-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Gd0hKa61h75Z7FmML6kPEA-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-WrVRnKuvYpwVxkmxZZzoeo-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-E3HZzYLtSjoQNNMskq8Gta-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-qzSvmHFHp4ePwGRQ2wFGwa-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Wc0tnwYoTaE36tXdMpVCWv-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-JHZUAZERYiz84dhiZ8cjpV-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-Ad2k4RUCCfY18bFJNurMMH-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-P4n11GA39hjAc2cQNVHtkf-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-bE575zdJU8NauCcTeRwa5V-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-PC25XaZZvaohGznmRfALAh-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-HfkNLZpktjh4eX4eF0aCon-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-jwshA6GFTJNSpR0qcbs1kY-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-epnq9SHbRCLF3XTQSrMZUj-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-1gsNgA070QaU2x12y78XX0-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-5KQ02V1N2vCXS8ECgf62rp-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-1tQt1VsCEZN6qi05v8x4vU-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-CqP95tetQ1CaZmzuJKdhJu-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-5mphSkkK93mNwd8fp3Kvqf-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-GNJ6zNbjomvGMMtaRZhJy8-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-ZjPTswRamH8djpqcUn5hYH-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v3-tane-KCXPzQvyKS0TkKaAdvtP8r-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built the interpreter.
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built 1562 functions.
U {PPU[0x1000000] Thread (main_thread) [0x015efe64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x015f00bc]} sys_prx TODO: _sys_prx_register_library(library=*0x15f26a0)
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-1z3Pyu8YVnnorJiQ2hfu1e-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U {PPU[0x1000000] Thread (main_thread) [0x01633d8c]} sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0040a50)
E {PPU[0x1000000] Thread (main_thread) [0x01633d8c]} SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U {PPU[0x1000000] Thread (main_thread) [0x01633d24]} sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0040a50, a3=0x0)
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-XCgQWMc1s99n1WTwrpWvw4-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-TP3c8YsdNggjaG5WRjcboe-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-LWAKW9c35vXJad6uHkwzhK-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
U {PPU[0x1000000] Thread (main_thread) [0x015f061c]} sys_prx TODO: _sys_prx_register_module()
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-fLV79QqHgPi90UziTsWrHo-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23001400)
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-2my7r7Nd2rncZdtcuT9g60-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-aaAKL9HJRRAWFrQ1t0vFNk-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libnet.sprx” (id=0x23002b00)
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-ZAhea3FFhakpfMa36ZvaNx-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} sys_prx: Loaded module: “/dev_flash/sys/external/librtc.sprx” (id=0x23002e00)
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-Fw28ZLYjrm28jGkCjyP0Ew-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-SqhVEw8Eg0UcRMfygtcfjd-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-FotbZ1TdsVMNYskb7W12s6-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libssl.sprx” (id=0x23002f00)
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-95r7Juhw7niQj6t9SAfNTR-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-XuGVy2wEHwt3xmazyhQcgn-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-Azvpte0puqKSeF3SPfQ5z5-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libhttp.sprx” (id=0x23003000)
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-3dt5v1GUnYtexdcZ9VmbTW-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} PPU: LLVM: Loaded module v3-tane-cWzq9SFVhqTQTWZ7swxd0Y-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x015f09ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libpngdec.sprx” (id=0x23003400)
E {PPU[0x1000005] Thread () [0x016b2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BIGFILE3.VIV” [1]
E {PPU[0x1000005] Thread () [0x016b2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BIGFILE4.VIV” [1]
E {PPU[0x1000005] Thread () [0x016b2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BIGFILE5.VIV” [1]
E {PPU[0x1000005] Thread () [0x016b2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BIGFILE6.VIV” [1]
E {PPU[0x1000005] Thread () [0x016b2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BIGFILE7.VIV” [1]
E {PPU[0x1000005] Thread () [0x016b2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BIGFILE8.VIV” [1]
E {PPU[0x1000005] Thread () [0x016b2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BIGFILE9.VIV” [1]
E {PPU[0x1000005] Thread () [0x016b2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BIGFILE10.VIV” [1]
E {PPU[0x1000005] Thread () [0x016b2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BIGFILE11.VIV” [1]
E {PPU[0x1000005] Thread () [0x016b2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/BIGFILE12.VIV” [1]
U {PPU[0x1000000] Thread (main_thread) [0x015eff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x015eff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
E {PPU[0x100000e] Thread (Game Data Utility) [0x013c02e0]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLES00713”, errDialog=0x0, funcStat=*0xf0b830, container=4294967295)
U {PPU[0x1000000] Thread (main_thread) [0x013c5868]} sceNp TODO: sceNpBasicRegisterHandler(context=*0xd003fca0, handler=*0xefd190, arg=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x013c02e0]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLES00713”, errDialog=0x0, funcStat=*0xf20180, container=4294967295)
E {PPU[0x100001a] Thread (EARS::PDLC::InitTrophiesThr) [0x013c0018]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0xf201a8, arg=*0x30eb5580, options=0x0)
U {PPU[0x1000000] Thread (main_thread) [0x013c5bc8]} sceNp TODO: sceNpManagerGetNpId(npId=*0x36550c50) x3
E {PPU[0x100001d] Thread (PS3DiscoveryDriver Unlock C) [0x016b2000]} SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00713/USRDIR” [1]
E {PPU[0x100001d] Thread (PS3DiscoveryDriver Unlock C) [0x016b1360]} SYS: 'sys_fs_closedir' failed with 0x8001002a : CELL_EBADF [1]
S {RSX Decompiler Thread} RSX: New program compiled successfully x23

**Comment by RainbowCookie32** [comment]
If only we had some kind of guidelines that showed up when opening an issue... _oh wait, we do._

Post the proper log file from rpcs3's folder instead of copying a wall of text from the UI

**Comment by Skorpion96** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4568949/RPCS3.log.gz)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
