### ISSUE TITLE
Stuck on infinite loading screen on Persona 5.

### ISSUE THREAD

**Issue by Noorrm** [RPCS3/rpcs3#8156]
Hi! First of all - i'm new to rpcs3, so it might be a dumb bug thats easy to solve, but as of now i cannot do so.

I installed RPCS3 To play persona 5, Everything worked until now where it takes a long time to load in, or perhaps its a infinite loading screen. Im running the game on vulkan, with the LLVM recompiler. I own a i5-8600k and a 1050ti.
Upon loading the game, these logs pop up.
![image](https://user-images.githubusercontent.com/64860788/81096483-b788e800-8f06-11ea-9839-36bb584bec6d.png)

Is there any way to fix my game?

**Comment by RainbowCookie32** [comment]
Attach the log file from RPCS3's folder (RPCS3.log). A screenshot from the UI is useless.
It sounds like a support case for Discord though

**Comment by Noorrm** [comment]
> Attach the log file from RPCS3's folder (RPCS3.log). A screenshot from the UI is useless.
> It sounds like a support case for Discord though

Oh well, i see. Thanks!

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
