### ISSUE TITLE
[GUI][Feature Request] Quick shortcut access for rsx capture

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#8157]
Adding rsx capture to the debugger was not ideal, but it had a very quick access to it which is needed for this type of "real time debuggers tools interaction" experience.
I suggest adding a shortcut to the main rpcs3 toolbar menu.

**Comment by dio-gh** [comment]
On that note, perhaps it could also be made not to pause emulation. It's very confusing for the end user to see the game basically hang after taking a capture.

**Comment by dio-gh** [comment]
Actually, isn't this already implemented? It's been put under `Utilities`.

**Comment by elad335** [comment]
The issue is about that it's under `Utilities` actually.
