### ISSUE TITLE
AMD Vulkan driver crash

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8159]
After #8149 , while using the Async + Shader interpreter, during the initial interpreter freezes, sometimes the AMD graphics driver crashes. The GPU is an RX 580 on driver 20.4.1. This was tested on GT5 BCES00569. Debugging on VS yielded what is in the picture.
![Screenshot_21](https://user-images.githubusercontent.com/1712979/81108705-b4e7bc00-8f21-11ea-82cf-bddc45aa9366.png)
[RPCS3log.zip](https://github.com/RPCS3/rpcs3/files/4583269/RPCS3.zip) It's a custom build, but the RSX code has not been touched.

**Comment by kd-11** [comment]
This is not an rpcs3 bug it is a driver bug that goes back many years. It is also spurious making it difficult to properly file a report with AMD.

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/8679. I couldn't get it to crash anymore after disabling shader optimizations, so I think it should be back to the old state.

**Comment by kd-11** [comment]
Will revisit once the unified shader compiler is completed.

**Comment by kd-11** [comment]
Closing, this got fixed at some point. I didn't re-enable SPIRV optimizations, but we don't need this anymore.
