### ISSUE TITLE
Playstation Home: Build 1.60 offline mode. Graphics/keyboard issues.

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#8161]
*The dev build of Playstation Home 1.60 have some graphical issues under RPCS3.*

- Broken distant buildings/elements

![Issue 1 (2)](https://user-images.githubusercontent.com/26351275/81159069-e3e54880-8f88-11ea-9d59-58d78f2aa348.gif)

![image](https://user-images.githubusercontent.com/26351275/81164229-53126b00-8f90-11ea-8720-a5bb493d3200.png)

- Black screen when any UI elements are on screen (including dev console)

![Issue 2](https://user-images.githubusercontent.com/26351275/81158849-aaacd880-8f88-11ea-9d6e-0104a0be0b2b.gif)

- Water rendering issues

![image](https://user-images.githubusercontent.com/26351275/81161895-9ec31580-8f8c-11ea-8b94-d4c931e7b7d6.png)

- Keyboard issue which keep repeat the same letters when a keyboard button is pressed.

I am a noobie in RPCS3 so if you need other infos for debuging, don't hesitate asking me what you want.

**Comment by dio-gh** [comment]
Please attach RSX captures and a log.

**Comment by atomic83GitHub** [comment]
I am sorry to ask but, how can I do RSX captures and what log should I send?

**Comment by dio-gh** [comment]
It's under `Utilities`, with the name `Create RSX Capture`. You have to visit each problematic scene and click that. The emulation will pause once you take them, you can resume the emulation by clicking the big play button in the main RPCS3 window.

As for the log, after taking these captures, close the game and the emulator, then attach the rpcs3.log.gz file from the main RPCS3 folder. The RSX captures you'll find in the `/captures/` subfolder.

**Comment by atomic83GitHub** [comment]
Thanks for the awsome explaination, I will do this ASAP.

**Comment by atomic83GitHub** [comment]
- I solved the UI issue by enabling: read color buffers. But there is still a bit of artifact on screen.

![image](https://user-images.githubusercontent.com/26351275/81238612-c9e84c00-9002-11ea-98b4-c73b62b50b04.png)

![image](https://user-images.githubusercontent.com/26351275/81238637-d9679500-9002-11ea-8c54-f8f88163ba47.png)

**Comment by atomic83GitHub** [comment]
Sorry but I don't see where utility is 
![image](https://user-images.githubusercontent.com/26351275/81238791-3d8a5900-9003-11ea-8024-adf175cf36aa.png)

**Comment by dio-gh** [comment]
Oh right, it's a debug feature. Open `/GuiConfigs/CurrentSettings.ini`, and set `showDebugTab` to `true`. Then it will show (you'll need to restart RPCS3 though).

**Comment by atomic83GitHub** [comment]
While doing this, I must mention that game also suffer of random crashes when not moving for a long time.

**Comment by atomic83GitHub** [comment]
Here is the RPCS3 log:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4589990/RPCS3.log.gz)

**Comment by atomic83GitHub** [comment]
Here are all the RSX captures I have done for all of the 4 issues:

https://mega.nz/file/DdhCXK6b

**Comment by kd-11** [comment]
How many of these issues are still present?

**Comment by atomic83GitHub** [comment]
Sorry KD-11 I didn't see your previous message but yes, unfortunately a lot of graphics issues remain, it would be awsome to look at those after the regression is fixed.

**Comment by NicolasOmar974** [comment]
What modifications did you make to run it offline? 
can they be done on the ps3 itself with the home development kit 1.60?

**Comment by Jump-Suit** [comment]
> 
> 
> What modifications did you make to run it offline?
> can they be done on the ps3 itself with the home development kit 1.60?

Simply Lookup the group "Destination Home", the answers are there :). Short answer offline works for both PS3 (with target manager) and RPCS3 for PC as shown here.

**Comment by atomic83GitHub** [comment]
Just a quick update on this topic, all the issues are still happening with the most recent version of the emulator, I will try some settings still.

**Comment by SlyCooperReloadCoded** [comment]
Something to add to this is that every build of RPCS3 after 0.0.11-10669-f8d2d8ca fails to boot the offline build of Home discussed here.  It gets to the loading screen then immediately hangs.  By modifying Home's files you can trick it into progressing slightly further but it'll just hang again
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6988384/RPCS3.log.gz)
.  The log for latest master is attatched.

**Comment by NicolasOmar974** [comment]
> Algo que agregar a esto es que cada compilación de RPCS3 después de 0.0.11-10669-f8d2d8ca falla al arrancar la compilación fuera de línea de Home discutida aquí. Llega a la pantalla de carga y luego se cuelga inmediatamente. Al modificar los archivos de Home, puede engañarlo para que avance un poco más, pero simplemente se bloqueará nuevamente
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6988384/RPCS3.log.gz)
> . Se adjunta el registro del último maestro.
> 
> Algo a tener en cuenta es que cuando cada compilación posterior a 0.0.11-10669-f8d2d8ca se cuelga, se cuelga de esto:
> 
> E SYS: 'sys_ppu_thread_detach' falló con 0x80010001: CELL_EAGAIN [1]
> E SYS: 'sys_fs_stat' falló con 0x80010006: CELL_ENOENT, "/dev_usb/hubstartup.txt" [1]
> E SYS: 'sys_ENO6ENT falló con 0x80010006: CELL_ENOENT /dev_hdd0/game/NPIA00010/USRDIR/SCRIPTS/HUBSTARTUP.TXT ”[1]
> 
> 0.0.11-10669-f8d2d8ca y cada compilación anterior ni siquiera muestra este mensaje que yo sepa, o eso o no pasó más de un milisegundo en él.
> 
> La "modificación de los archivos de Home" implica copiar "hubstartup.txt" a la carpeta dev_usb000 / como dice el error, después de lo cual pasará ese paso y comenzará a buscar más archivos, solo para fallar con:
> 
> F VM: ubicación de lectura de infracción de acceso 0x2ffffff8 (memoria no asignada) [type = u64]
> 
> Este paso de copia no es necesario para arrancar correctamente en 0.0.11-10669-f8d2d8ca o anterior, pero vale la pena mencionarlo.


One question, where do I download the hubstartub.txt file?
I'm using build 1.86 and it gets stuck on the loading screen

**Comment by NicolasOmar974** [comment]
Install pshome development build 1.86.09 on my PS3, the problem is that after hitting offline it throws the following error:
![20210820_144401](https://user-images.githubusercontent.com/75269008/130274079-4204618e-ad13-4edc-9df6-9ebc68d3a3bc.jpg)
then copy the file hubstartup.txt from the folder NPIA00010 / USRDIR / Scrips to dev_usb000 but when I hit offline the loading screen gets stuck in an infinite loop, does anyone know what I have to do? I'm a few days ago and I can't fix it

**Comment by SlyCooperReloadCoded** [comment]
This issue is related to Home offline on RPCS3, take that issue elsewhere.

**Comment by NicolasOmar974** [comment]
ok, I'll ask you at the home destination discort :)
