### ISSUE TITLE
Demon's Souls "checking trophy set" freeze

### ISSUE THREAD

**Issue by LittleWendigo** [RPCS3/rpcs3#8163]
Hi, im at my wits end with that problem which im about to describe. 
I have played DS quite a few times and had no issues, and suddenly, every time i try to run the game, it freezes on "checking trophy set" text and nothing else loads, the fps number freezes too and i have to close the window. It does not happen on the first run, and then, after the character is made, it always does. It drives me insane, ive tried to mess with configuration, but to no avail, redownloaded the program, nothing works. 
The log after that error is as follows:

My specs are:
i5-4690k, Radeon r9 280 and 8gb ddr3

Please help me, i love Dark Souls and was to happy when Demon's Souls run on my pc, it sucks :( 
Also sorry for bad english lol, not a native english speaker here.

**Comment by RainbowCookie32** [comment]
Attach the full log from RPCS3's folder after you get your problem, as stated in the guidelines. A copied bit from the UI is not useful, it's just an incomplete, out of context wall of text in the issue

**Comment by jedinjapan** [comment]
Speculation, but what locale is your OS set to?

Assuming you are running Windows, if the file system is set to a non-english locale, it may be possible that when Demons Souls attempts to read/write to the trophy set in your file system is it encountering an error.

As @RainbowCookie32 mentioned, export the Log file, and give more detail on your install including your OS and Version number you are testing with.

**Comment by Aneimeth** [comment]
I am having the same problem. I am running windows 10, it was working fine until today and now it won't load past the trophy screen.
[DSTrophyFreezeLog.txt](https://github.com/RPCS3/rpcs3/files/4827620/DSTrophyFreezeLog.txt)

**Comment by m3g4ykt** [comment]
Removing custom config works to me

**Comment by RainbowCookie32** [comment]
Still missing a proper log containing the freeze.

Someone needs to update the issue with one, assuming it's still an issue in latest master.

**Comment by Asinin3** [comment]
No update on issue + haven't heard of other people having same issue lately. Closing.
