### ISSUE TITLE
Uncharted 1 and 2 VM: Access violation reading location 0x0 (unmapped memory)

### ISSUE THREAD

**Issue by natmos96** [RPCS3/rpcs3#8165]
Quick summary

Issue is VM: Access violation reading location 0x0 (unmapped memory) on both Uncharted 1 and 2 no variation in settings is fixing the issue and everything is running without extra hacks dlc etc just standard.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4588922/RPCS3.log)

**Comment by AniLeo** [comment]
> Resolution: 1920x1080

> Last function: cellVideoOutGetResolution

> ·F 0:00:05.656228 {PPU[0x1000000] Thread (main_thread) [0x00048934]} VM: Access violation reading location 0x0 (unmapped memory)

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
