### ISSUE TITLE
Goldeneye reloaded ps3

### ISSUE THREAD

**Issue by Campey91** [RPCS3/rpcs3#8168]
Recently got goldeneye reloaded on ps3 and trying to install the disc to start playing it and it stops at 3/4% and got plenty of memory on the console cleaned the disc etc.

Any ideas thanks

**Comment by sampletext32** [comment]
Sounds, like a Discord #help question.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
