### ISSUE TITLE
Performance Regression/Crash: Prince of Persia Sands of Time Since v0.0.9-10279, PR #8051

### ISSUE THREAD

**Issue by jeremybris** [RPCS3/rpcs3#8172]
## Quick summary
There are less frames per second on recent builds for Prince of Persia Sands of Time [NPUB30303]. In addition, if you try to continue to play at ~15 F.P.S., the game crashes.

## Details

- Latest build
- Default settings, with Vulkan and Vblank 120
- CPU: AMD, GPU: Nvidia RTX
- Sometimes I get a small regression, ~30 F.P.S., and sometimes I get a big one, ~15 F.P.S.
- The game received a performance boost shortly before it regressed. Maybe that is of significance. I don't know.
- #8133 is similar, but that was closed.

| RPCS3 Version | RPCS3 Commit | RPCS3 FPS | Screenshot |
| ------------- | ------------- | ------------- | ------------- |
| v0.0.9-10272 and Before  | -------------  | ~40 F.P.S. [RPCS3 1.log](https://github.com/RPCS3/rpcs3/files/4596378/RPCS3.1.log) | ![Capture](https://user-images.githubusercontent.com/11889359/81356039-3a907680-909e-11ea-92bf-8683d6e27287.PNG) |
| v0.0.9-10274 | #8103 | ~50 F.P.S. (Improvement) [RPCS3 2.log](https://github.com/RPCS3/rpcs3/files/4596382/RPCS3.2.log) | ![Capture2](https://user-images.githubusercontent.com/11889359/81356080-5bf16280-909e-11ea-8ac6-0b786c4c8e67.PNG) |
| v0.0.9-10279 and After | #8051 | ~15 F.P.S. or ~30 F.P.S. (Regression) [RPCS3 3.log](https://github.com/RPCS3/rpcs3/files/4596384/RPCS3.3.log) | ![Capture4](https://user-images.githubusercontent.com/11889359/81357392-8395fa00-90a1-11ea-9877-1b00fb338073.PNG) ![Capture3](https://user-images.githubusercontent.com/11889359/81356088-657aca80-909e-11ea-8479-644ff3188e24.PNG) |

Please see [below](https://github.com/RPCS3/rpcs3/issues/8172#issuecomment-630510152) for more information on the crash.

Let me know if any information is incorrect, or I can provide any more details.

**Comment by elad335** [comment]
Test with SPU loop detection off.

**Comment by jeremybris** [comment]
"CPU">"Additional Settings">"Enable SPU Loop Detection">Off, 


| Off  | On |
| ------------- | ------------- |
| 3/5 times, I got ~35 F.P.S., it worked  | 1/5 times, I got ~35 F.P.S., it worked |

I got inconsistent results. Here is the log of the times it worked with SPU Loop Detection 
[RPCS3 1.log](https://github.com/RPCS3/rpcs3/files/4600242/RPCS3.1.log) and the times it did not work [RPCS3 2.log](https://github.com/RPCS3/rpcs3/files/4600254/RPCS3.2.log) (this log was 1-5 F.P.S.).

**Comment by elad335** [comment]
Test with #8175

**Comment by jeremybris** [comment]
#8175 works better, but not fixed. 

Now, 2/5 times, ~50 F.P.S. it works, instead of 2/5 times, ~30 F.P.S.

**Comment by elad335** [comment]
Ok, make sure you tested with SPU loop detection **on** with the pr. My mistake for not telling you it.

**Comment by jeremybris** [comment]
Ok, my results were with SPU loop detection **on**. 

The other 3/5 times **it does not work,** I get ~15 F.P.S. with the PR from earlier. I'm not sure what TSX or non-TSX is, but I have an AMD Ryzen 3900x. I hope this helps.

**Comment by jokoputera** [comment]
https://github.com/RPCS3/rpcs3/pull/8175
Seems fix this issue. Remember to close thread.

**Comment by jeremybris** [comment]
Still happens on v0.0.10-10362, just happens 2/5 times. When it doesn't happen, it is still a performance regression in comparison to v0.0.9-10275. Any other testers want to confirm or deny my results? Maybe it is something on my end. This also effects Prince of Persia: Warrior Within [NPUB30388]

**Comment by jokoputera** [comment]
Strange. Im running the PoP TSoT in PoP Trilogy and seems to work just fine, except Warrior Within, but i think the gameitself capped for 30fps (3D glasses version)

**Comment by jeremybris** [comment]
What's wrong with Warrior Within for you? 

I am using the PSN version of PoP TSoT. And in order to get more than 30 F.P.S., I changed the VBlank under advanced to 120, to get ~50 F.P.S. on v0.0.9-10275.

**Comment by jeremybris** [comment]
After continuing to play when the game is at ~15 F.P.S., the game crashes with this.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4647601/RPCS3.log)

![Capture23](https://user-images.githubusercontent.com/11889359/82272497-cb8e0a00-9948-11ea-89e9-47ea64946b1c.PNG)

![Capture54](https://user-images.githubusercontent.com/11889359/82272503-cf219100-9948-11ea-89d2-75e3feda1daa.PNG)

**Comment by jokoputera** [comment]
Using ASMJIT can run this game around 30fps.
one thing that i notice, all three games (PoP trilogy 3D) is having sound effect like an inverted vocal (hall sound effect). I dont know if this is in this PR, or else...

**Comment by digitaldude555** [comment]
Any update on this?

**Comment by jeremybris** [comment]
Still happens 1/5 times. "Accurate RSX Reservation" fixes the frame drop, but it still crashes 1/10 times.

**Comment by jeremybris** [comment]
I think "Write Color Buffers" + "Read Color Buffers" fixes the crash. Closing.
