### ISSUE TITLE
[Feature Request] Handle better the game hangings

### ISSUE THREAD

**Issue by LaneSh4d0w** [RPCS3/rpcs3#8173]
Some games tend to hang for unmapped memory issues (can be seen on Euro version of Lightning Returns) and / or for CELL_EINVAL problems (can be seen on Euro version of Monopoly Streets).

Usually, the emulator tends to freeze and sometimes softlocks (happens on quoted games), and user needs to restart.

A workaround would be to trace and find when those kind of errors happen, and automatically closes down the game when an error of that sort occurs, causing the game to freeze and/or lock the emulator.

That will prevent the force close of RPCS3 and to restart it everytime, so that user can still test and debug some other games.

**Comment by elad335** [comment]
Not everything can be detected, although non-spu access violations are doable for this.

**Comment by LaneSh4d0w** [comment]
Indeed, there are a lot of possibilities related to those kind of issues.

**Comment by elad335** [comment]
On second thought, it may better for developers for it not be closed automatically, so maybe an option can be made.

**Comment by LaneSh4d0w** [comment]
Yes, I was even thinking about a log message being added when the game window closes. Something like GameWindow : Window closed abruptly : <ERROR_CAUSE>

**Comment by elad335** [comment]
This issue doesnt really make sense for developers, hang is not a segfault which can be detected, practically only the user can tell if the game is running normally or not.
Also access violations has been fixed to not lock up the whole emulator.
