### ISSUE TITLE
rsx: Crash on d3d11.dll

### ISSUE THREAD

**Issue by Bel25m** [RPCS3/rpcs3#8176]
hello I have a problem with the emulator lately, I have been playing person 5 as if nothing but today when alcutalizing the emulator I just got an error I tried to remove the update but it did not work, the error is that of this capture:
![imagen](https://user-images.githubusercontent.com/65053160/81460616-1b601a80-916c-11ea-85f0-dfca0d53fdb1.png).
log file: http://www.mediafire.com/file/38235o7sdyiu6wi/RPCS3.log/file

**Comment by AniLeo** [comment]
d3d11.dll is not used by RPCS3, makes no sense
@kd-11

**Comment by Bel25m** [comment]
So what can i do? and sorry for bad english

**Comment by Bel25m** [comment]
So what can i do? sorry if i bother you

**Comment by AniLeo** [comment]
Stop flooding, this is an issue tracker not a helpdesk

**Comment by Bel25m** [comment]
oh sorry my fault

**Comment by kd-11** [comment]
This is likely a sign of something outside rpcs3 hooked into the application somehow, maybe monitoring software or something like that. We do not use DirectX.

**Comment by jedinjapan** [comment]
Disable any overlay software you have in use (Nvidia, Steam, etc) and any enhancement software like ReShade or SweetFX.

**Comment by AniLeo** [comment]
I've seen this pop up a couple of times, but RPCS3 indeed does not use neither it ever used Direct3D 11, since it's a crash caused by an unknown 3rd party hook will be closing as it's not a crash on our side to fix
