### ISSUE TITLE
Hatsune Miku: Project DIVA F 2nd [NPEB02013] - RSX Decompiler Crash

### ISSUE THREAD

**Issue by korenkonder** [RPCS3/rpcs3#8183]
## Quick summary
For some reason it crashes now in that game

## Details
https://www.youtube.com/watch?v=GoKjZ0oxm5Y
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4605485/RPCS3.log)

**Comment by Fabianpaw** [comment]
Known regression, same as #8170
