### ISSUE TITLE
Eternal Sonata [BLES00444]

### ISSUE THREAD

**Issue by fargostz** [RPCS3/rpcs3#8184]
Hi,
I keep having random error from memory violation:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4605932/RPCS3.log)

Here's my setup and options in Rpcs3:
[Setup.log](https://github.com/RPCS3/rpcs3/files/4605935/Setup.log)

**Comment by AniLeo** [comment]
Log file shows pirated copy of the game, log file shows ancient RPCS3 build, garbage issue

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
