### ISSUE TITLE
Possible usage of null pointer in np_handler.cpp

### ISSUE THREAD

**Issue by qarmin** [RPCS3/rpcs3#8193]
`cur_ip = p;` should be used inside `else` statement because it delete previous value of `cur_ip` and may be `nullptr` when `.c_str()` will be executed

https://github.com/RPCS3/rpcs3/blob/5692c3de0482659e723e821338febd8c9b5d1255/rpcs3/Emu/NP/np_handler.cpp#L66-L75

**Comment by elad335** [comment]
I dont understand why creating these issues over small code changes which are obviously correct. regardless feel free to open a pull request to fix this.

**Comment by sampletext32** [comment]
@elad335 , since we are not professionals, we need an approval from the genius, maybe optimization is restricted for some reason. Please don't be angry at us. We are just trying to be helpful.

**Comment by Yahfz** [comment]
Even if the fix was wrong or not, you should always be encouraged to make a PR anyways hahah. That’s the whole reason why pull requests are a thing :p
