### ISSUE TITLE
rsx/vulkan: AMD driver crash while using ASync + Shader Interpreter mode

### ISSUE THREAD

**Issue by gudiofor** [RPCS3/rpcs3#8200]
**- full logs:**

https://textbin.net/aoahStRtgw

**- screenshots:**
https://i.imgur.com/4tdYbCS.png

**- System configuration**

OS: Windows 10 pro 1909
CPU: AMD Ryzen™ 5 3600 6-core processor 3.99 Ghz
GPU: Rx 590 8GB sapphire
Driver version: 20.2.2

**Comment by LaneSh4d0w** [comment]
What's the issue though ? Apart from the thread name, you litterally do not explain what's going on.

**Comment by RainbowCookie32** [comment]
I think that the Shader Interpreter can cause that kind of crash. Try using just Async

**Comment by gudiofor** [comment]
> Eu acho que o Shader Interpreter pode causar esse tipo de falha. Tente usar apenas Async

This solved the problem, but I had a minimal drop in performance, but I can play until then. After I did that I managed to get past the stage where I was giving the error, I will later continue the game and if there is an error again I will return here in this publication.

**Comment by kd-11** [comment]
Duplicate of https://github.com/RPCS3/rpcs3/issues/8159
