### ISSUE TITLE
input: Rock Band 3 MIDI Pro Adapter - Unable to use it, though it's semi-detected

### ISSUE THREAD

**Issue by Jademalo** [RPCS3/rpcs3#8201]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4618262/RPCS3.log)
## Quick summary
The Rock Band 3 MIDI Pro Adapter is detected in the log, but doesn't function at all ingame.

## Details
- Expected is that the game detects the adapter as whichever instrument is selected, and adds that instrument as a player.
- Logs are attached for booting the game with the device in each of the three modes
- Windows 10, i5-8086k, GTX970

Zadig was used to swap the device driver to WinUSB for all 3 modes (since all 3 are detected as different devices).
For Drums, the player icon shows in the menu, but none of the buttons respond at all. For keys and Guitar, nothing is shown.

**Comment by AniLeo** [comment]
May require sys_usbd whitelist

What's the VendorID and ProductID of the Rock Band 3 MIDI Pro Adapter

**Comment by Jademalo** [comment]
I believe they're actually on the whitelist already, at least according to the Wiki.

The device actually has three IDs, depending on whether or not Drum, Keyboard, or Guitar mode is selected.

Drum - `VID_12BA&PID_0218`
Keyboard - `VID_12BA&PID_2338`
Guitar - `VID_12BA&PID_2538`

**Comment by bevanweiss** [comment]
@Jademalo the log does indeed show up that it's loaded in the LDD handler for each of the three IDs you had.
But it does also shown an attempt to issue a usbd_attach, which I don't believe is fully implemented yet.

I was sure that others have reported these working, but perhaps that's the Guitar Hero stuff, and it might use a different mechanism.
I'll try to take a look at it in the next few week's, but I'm new to rpcs3 development, so don't expect miracles :)

**Comment by Jademalo** [comment]
Awesome, thank you!
Good luck, hope it's something simple =p

**Comment by yupitsnate** [comment]
> @Jademalo the log does indeed show up that it's loaded in the LDD handler for each of the three IDs you had.
> But it does also shown an attempt to issue a usbd_attach, which I don't believe is fully implemented yet.
> 
> I was sure that others have reported these working, but perhaps that's the Guitar Hero stuff, and it might use a different mechanism.
> I'll try to take a look at it in the next few week's, but I'm new to rpcs3 development, so don't expect miracles :)

@bevanweiss, do you know if any headway has been made on implementing the MIDI Pro adapter or sys_usbd_attach? Or if there's anything troubleshooting/logging I can do to help?

**Comment by Megamouse** [comment]
Is this still an issue ?

**Comment by Megamouse** [comment]
Superseded by #10220
