### ISSUE TITLE
Jak and Daxter Precursor Legacy HD isnt centric in full screen

### ISSUE THREAD

**Issue by jakrenegadex** [RPCS3/rpcs3#8204]
hello,
i try to play jak and daxter precursor legacy hd on rpcs3, but it doesnt work on full screen.
the game isnt centric.
it goes up  and to the right side of the screen and i cant see a lot anymore on the screen.
it only works on little screen around 22 inch.
my monitor is 31,5 inch.

can someone help me?

## Quick summary
Please summarize the issue here

## Details
Please provide as much detail as you can here, including
- expected (real hw) and observed (emulator) behavior
- full logs (not from UI)
- back traces (for hard crashes)
- screenshots, Renderdoc, and RSX captures (for visual issues)
- your system configuration (OS, CPU, GPU, driver versions, etc)
- anything else you deem to be important

**Comment by jakrenegadex** [comment]
why did you close this?

**Comment by AniLeo** [comment]
Ignored all the guidelines, thought it was pretty obvious

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
