### ISSUE TITLE
rsx/vulkan: Crash on Intel iGPUs with both free/nonfree drivers

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#8205]
| OS | GPU | Driver | Render | Crash |
| --- | ------ | ------- | ------ | ----- |
| Windows | Iris HD 530 | Proprietary | OpenGL | No |
| Windows | Iris HD 530 | Proprietary | Vulkan | **YES** |
| Windows | GTX 960M | Proprietary | OpenGL | No |
| Windows | GTX 960M | Proprietary | Vulkan | No |
| Manjaro | Iris HD 530 | Mesa (iris) | OpenGL | No |
| Manjaro | Iris HD 530 | Mesa (anv) | Vulkan | **YES** |
| Manjaro | R9 280X | Mesa (radeonsi) | OpenGL | No |
| Manjaro | R9 280X | Mesa (radv) | Vulkan | No |

A few seconds after getting in-game on `Yakuza 3 Demo` the game will completely freeze, and RPCS3 will go into non-responding mode.

Windows shows a `ig9icd64.dll` crash when trying to close the emulator, though this also happens when trying to close it pre-crash while it's rendering normally
![Screenshot_165](https://user-images.githubusercontent.com/10283761/81755549-fdb6ec00-94b0-11ea-8584-22968732025f.png)

Linux shows
```
Segfault writing location 0000000000000004 at 00007fbe4c70e5f5.
Emu Thread Name: 'rsx::thread'.
Thread id = 140454773954304.

RPCS3: Segfault writing location 0000000000000004 at 00007fbe4c70e5f5.
Emu Thread Name: 'rsx::thread'.
Thread id = 140454773954304.

Found exec link: /tmp/.mount_rpcs3.UEL2UY/usr/bin/rpcs3
posix_spawn() failed: 12
```

**Comment by kd-11** [comment]
I wonder if https://github.com/RPCS3/rpcs3/pull/8679 helps this game.

**Comment by AniLeo** [comment]
Unfortunately still happens, just reproduced on latest master

**Comment by AniLeo** [comment]
Stack trace:

```
Thread 52 "rsx::thread" received signal SIGSEGV, Segmentation fault.
Segfault writing location 0000000000000004 at 00007ffef81922cc.
Emu Thread Name: 'rsx::thread'.
Thread id = 140731323504192.


Thread 52 "rsx::thread" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff6ecbf75 in raise () from /usr/lib/libpthread.so.0

[#0] 0x7ffff6ecbf75 → raise()
[#1] 0x66559a → signal_handler(int, siginfo_t*, void*)()
[#2] 0x7ffff6ecc0f0 → __restore_rt()
[#3] 0x7ffef81922cc → mov DWORD PTR [rbx+0x4], edx
[#4] 0x7ffef819a4ef → mov rcx, QWORD PTR [rsp+0x8]
[#5] 0x10b6221 → VKGSRender::emit_geometry(unsigned int)()
[#6] 0x10b4e63 → VKGSRender::end()()
[#7] 0xb44667 → rsx::nv4097::set_begin_end(rsx::thread*, unsigned int, unsigned int)()
[#8] 0xb41af4 → rsx::thread::run_FIFO()()
[#9] 0x9d31ae → rsx::thread::on_task()()
```

**Comment by AniLeo** [comment]
Windows issue may be unrelated looking at the crash, tracking behavior only on Mesa anv

With mesa with debug symbols
```
[#0] 0x7ffedc540a18 → GEN8_VERTEX_BUFFER_STATE_pack(values=<optimized out>, dst=0x4, data=0x7fff404353f8)
[#1] 0x7ffedc540a18 → emit_vertex_bo.isra.1(cmd_buffer=0x7fff404353b0, size=0x0, index=0x1c, addr={
  bo = 0x0,
  offset = <optimized out>
}, addr={
  bo = <optimized out>,
  offset = <optimized out>
})
[#2] 0x7ffedc18e237 → gen9_CmdDrawIndexed(commandBuffer=0x7fff404353b0, indexCount=0xad, instanceCount=0x1, firstIndex=0x0, vertexOffset=0x0, firstInstance=0x0)
```

**Comment by kd-11** [comment]
Needs retesting.

**Comment by AniLeo** [comment]
Cannot reproduce any longer on Linux, no idea about Windows

Kernel: 5.12.2-1-MANJARO
Mesa: 21.1.2-0
RPCS3: v0.0.16-12382-20bd723e Alpha

Closing as solved, I'll reopen if I find it still happens somehow
