### ISSUE TITLE
Ridge Racer 7 3D [NPUB30457] DLC never loads at all

### ISSUE THREAD

**Issue by GrandGTA** [RPCS3/rpcs3#8208]
I was downloading the package for RR7 3D and also added the RAP file properly... I seem to notice that it was licensed but when I went into the BGM, Net Disc was unavailable... Here are the files for the USRDIR of my RR7 3D copy:
3D_txt_ES.edat
auroravision
BGM.nub
e3
EBOOT
ending
Game_DJ
intro
main.3d.self
main.self
RR7.DAT
text.edat
title
title2

is there something missing to my files???

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by GrandGTA** [comment]
Fixed it you weeb dude... I accidently pressed enter when the issue was still unfinished...

**Comment by AniLeo** [comment]
Stop spamming, read the guidelines
