### ISSUE TITLE
[GUI][Feature Request] Hiding "Forced TSX" and overwriting TSX setting for CPUs with no hw support

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#8212]
Hiding "Forced" option for CPUs which is not relevant to.
And forcefully overwriting the setting's value from enabled to disabled if not hw supported, so when viewing the setting's value in logs of games it would indicate the true state of TSX path usage.

**Comment by lextra2** [comment]
It would be great that who ever should pick this request up also takes a look at the gray out of anisotropic filtering and anti-aliasing options when the strict rendering mode is selected.

#7773 was supposed to make both, AF & AA gray out. Right now AA is not grayed out at all and AF is only grayed out for the time the GUI tab is still open. As soon as you close and reopen the GPU tab again, both AF & AA are changeable again which shouldn't be the case.

**Comment by elad335** [comment]
Move to another issue please.

**Comment by lextra2** [comment]
> 
> 
> Move to another issue please.

My bad. #8148 8213
