### ISSUE TITLE
UI Improvement: When selected, make "Strict Rendering Mode" also fade/grey out Anisotropic Filtering and Anti-Aliasing #2

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#8213]
#7773 was supposed to make both, AF & AA gray out when Strict Rendering Mode is enabled.

Right now AA is not grayed out at all and AF is only grayed out for the time the GUI tab is still open. As soon as you close and reopen the GPU tab, both, AF & AA are changeable again which shouldn't be the case.

With Strict Rendering Mode enabled, both settings should behave exactly like Resolution Scale & Resolution Scale Threshold.

**Comment by Megamouse** [comment]
As you can see, Anti Aliasing was never greyed out by that Pull Request.
I don't know why and I don't know if it even should be greyed out at all.
Maybe @kd-11 or @AniLeo can answer that.

**Comment by AniLeo** [comment]
The UI code is correct regarding AA:

Strict Rendering Mode does not force MSAA to be Enabled, even though it's the accurate path, you can choose between SRM + MSAA Enabled and SRM + MSAA Disabled.
Anisotropic Filtering is forcibly not enabled when you have SRM enabled.

https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/GL/GLTexture.cpp#L267

https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/VK/VKDraw.cpp#L192

**Comment by lextra2** [comment]
@AniLeo thanks for clearing that up. I didn't know that.

@Megamouse and thanks for fixing anisotropic filtering
