### ISSUE TITLE
Arcania: The Complete Tale - Broken textures.

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#8221]
[ ArcaniA - Vulkan/OpenGL ]
![1](https://user-images.githubusercontent.com/38318848/81952823-37017000-9607-11ea-940b-806d92f2f7e2.png)

RSX Capture:
**Link:** [RSX-Capture-(Build-0.0.10-10375)
](https://drive.google.com/open?id=18wSFVvQCNboc47RhAoFJ9bjUAZZdW8fR)

-------------------------------------------------------------------------------------------------------
[ ArcaniA: Fall of Setarrif - Vulkan/OpenGL ]
![2](https://user-images.githubusercontent.com/38318848/81953112-9495bc80-9607-11ea-9bfa-f69aa3bb61a7.png)

RSX Capture:
**Link:** [RSX-Capture-(Build-0.0.10-10375)](https://drive.google.com/open?id=19jkSYqztvTGXrYp9N-uCB6lbURpZBBgI)

## Details:
[ RPCS3 v0.0.10-10375-91d06a97 ]

OS: Windows 10 64-bit
CPU: Intel Core i5-8500
GPU: GTX 1660 - ( Driver version: 445.87 )

**Comment by Teriand** [comment]
ArcaniA + ArcaniA Fall of Setarrif in v0.0.13-11336 same textures glitches:
![image](https://user-images.githubusercontent.com/26705069/100984580-f560f400-355b-11eb-96f8-7921f2dd8a47.png)

**Comment by FinishedFragment** [comment]
Not a dev and no idea if this is even the right term for this, but some of this seems to be related to fresnel. The ocean for example only looks this way if you look at it from a specific angle.

![arcania fresnel](https://user-images.githubusercontent.com/44732327/118104184-15ce8d80-b3db-11eb-9754-d9b69005d809.png)

The textures also seem to change when you go near them and some of it may even look (vaguely) correct when being in in the proximity of the object.
There also seem to be some flickering shadows, but this may very well be a separate issue.

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/127718687-fb19e30e-f4f7-4ff1-93e9-345e0688d13c.png)
Interesting glitch caused by inconsistent texture control behavior.
