### ISSUE TITLE
[Regression] Ridge Racer 7 crashes in menus

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#8228]
RR7 now crashes once hitting the menus with the following error:
E {RSX [0x10af3d4]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300800

If it doesn't crash immediately, it will have navigating the menus some.

I tried adjusting the driver wake-up delay but no value helped stability and after 50, it prevented the game from booting. Tried various other settings like RSX reservation access but nothing worked. 

[RPCS3-menu crash.zip](https://github.com/RPCS3/rpcs3/files/4631990/RPCS3-menu.crash.zip)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by elad335** [comment]
find offending pr.

**Comment by legend800** [comment]
So I've spent the past 2 hours checking builds going back to half a year ago and I've come to the conclusion that the game has always had some desyncs, especially with no shader or spu cache built up. Once you get that, things seems fine enough.
