### ISSUE TITLE
Baja edge of control |BLES00359] serious graphical glitch

### ISSUE THREAD

**Issue by Snippy51** [RPCS3/rpcs3#8229]
A few months ago, i was trying out rpcs3 on my new computer, I got decent results on a sizeable amount of games, save for one in particular, who suffered a have regression. Said game happens to be BAJA - EDGE OF CONTROL [BLES00359] .
Game used to work as of the 0.0.7-8623 version I was using to play with regularly.

![Baja 3](https://user-images.githubusercontent.com/65389741/82037383-e3b70e00-9656-11ea-8f53-87bb67a6f881.PNG)

But Sometime before the 0.0.7-9053 version, important glitches have started to appear, preventing normal play.

![Baja 1](https://user-images.githubusercontent.com/65389741/82037400-eade1c00-9656-11ea-8f65-17e4e7e24391.PNG)

![Baja 2](https://user-images.githubusercontent.com/65389741/82037406-ed407600-9656-11ea-94fd-7fc73959a3fd.PNG)

[RPCS3 0.0.7-8623 log.log](https://github.com/RPCS3/rpcs3/files/4633829/RPCS3.0.0.7-8623.log.log)
[RPCS3 0.0.7-9053 log.log](https://github.com/RPCS3/rpcs3/files/4633831/RPCS3.0.0.7-9053.log.log)

Captures included in 7zip file linked below

https://drive.google.com/file/d/12R8HQyO5GY72rAT9Q4hnDykqzKx0wxX2/view?usp=sharing

PC :

AMD Ryzen 5 3600x
16 gb DDR4 ram
RX 590 8gb GPU
Windows 10 LTSC 1809

**Comment by kd-11** [comment]
Try and find the first broken release to help move this along faster.

**Comment by Snippy51** [comment]
I have found the Broken release.
It's the rpcs3-v0.0.7-8942 one.
There isn't much change in the log, but here they are anyways.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4634569/RPCS3.log)

**Comment by MSuih** [comment]
The related pull request is #6813
