### ISSUE TITLE
Ore no Imouto ga Konna ni Kawaii wake ga Nai. Happy End (JPN) [BLJS10238] PS3 ISO White screen

### ISSUE THREAD

**Issue by hun7326** [RPCS3/rpcs3#8233]
P.S I'm sorry that I copy that UI. I'll attatch it.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4637714/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4637715/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/4637716/TTY.log)

Game: Ore no Imouto ga Konna ni Kawaii wake ga Nai. Happy End (JPN) [BLJS10238] PS3 ISO

I use Windows 10 64 Bit, Nvdia Geforce GTX 750, Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz, 8GB RAM, DirectX 12

Problem: I'm so sorry that I don't know what have I got problem. When I use RPCS3 to run this game, Sounds pop up at time and got white screen on the RPCS3 and turned off. I want to know what did i do wrong. Here's the log.

And this is game screen.
![제목 없음](https://user-images.githubusercontent.com/65373045/82106140-2e6d7e80-975a-11ea-885d-dcc9548c7d2a.png)

**Comment by RainbowCookie32** [comment]
Attach RPCS3.log from RPCS3's folder. Don't copy from the emulator's UI. It's incomplete and its only use is as a wall of text.

**Comment by hun7326** [comment]
> Attach RPCS3.log from RPCS3's folder. Don't copy from the emulator's UI. It's incomplete and its only use is as a wall of text.

I'm so sorry. I edit it.

**Comment by RainbowCookie32** [comment]
Update your GPU drivers and test if Vulkan also has the issue.

**Comment by digitaldude555** [comment]
![Screenshot (304)](https://user-images.githubusercontent.com/26138653/106300589-5b69af00-625f-11eb-97e6-7f06dc4a2891.png)
It always worked. CLOSE.
