### ISSUE TITLE
AppImage 0.0.10-1038-db4414ca segfaults at open

### ISSUE THREAD

**Issue by thetargos** [RPCS3/rpcs3#8238]
## Quick summary

The latest appimage build segfaults as soon as launched, however, the emulator 'runs', and a fatal error window pops, so long as I don't click the OK button, I can run some games, but another window appears as soon as I close a game rendering window. All the information I have been able to get points to a segfault (obviously the location address varies with each boot of the machine), but it is consistent through out all my attempts to run the application. Strace log attached, as well as two screenshots of the error dialog and the output in the log window.

## Details
- your system configuration (OS, CPU, GPU, driver versions, etc)
OS: Fedora 32 (kernel 5.6.12)
CPU: Ryzen 7 1800X
Memory: 32 GiB
GPU: GTX 1080 driver 440.82

[rpcs3-0.0.10-1038-db441ca_linux64.appimage.txt]

(https://github.com/RPCS3/rpcs3/files/4638211/rpcs3-0.0.10-1038-db441ca_linux64.appimage.txt)
![Captura de pantalla de 2020-05-16 05-42-03](https://user-images.githubusercontent.com/4742429/82117748-fd7c5200-9737-11ea-9e02-d58cf7d83798.png)

![Captura de pantalla de 2020-05-16 05-42-26](https://user-images.githubusercontent.com/4742429/82117763-138a1280-9738-11ea-9140-c8e99e76ed37.png)

**Comment by AniLeo** [comment]
May be Fedora specific, no issues on Arch/Manjaro and Ubuntu

**Comment by thetargos** [comment]
Now that you mention it, it does seem that recent glibc updates in Fedora 'broke' compatibility with some things and I do remember reading up on it, maybe this behiavior stems from it, most likely. Though I have not had issues personally, it was documented in the beta, so most likely this is related. Just to make sure, the version of glibc I am currently using is 2.31

**Comment by thetargos** [comment]
Just wanted to add that indeed, seems an issue with distro-side libraries, as an update to pthread has solved all the segfaults on threads I had been getting.

**Comment by JohnHolmesII** [comment]
closable?

**Comment by AniLeo** [comment]
Does latest AppImage work for you on Fedora then?

**Comment by thetargos** [comment]
The latest 0.0.10-3d20ce70 appimage runs well and I do not see the threading problem. Thanks!

**Comment by AniLeo** [comment]
Closing then, assuming it was an OS issue and that they fixed it. If there's some way to reproduce this on the same updated Fedora version with the latest appimage, can ping for reopening.
