### ISSUE TITLE
Star Wars: The Force Unleashed II [NPUB30695]: Broken gfx

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#8244]
![2020-05-16 16_08_37-FPS_ 24 42 _ Vulkan _ 0 0 10-10397-d53a8191-mfc-interrupts _ Star Wars_ The Forc](https://user-images.githubusercontent.com/20983844/82132781-48c64d00-9798-11ea-843f-decb3bd386fd.png)

![2020-05-16 16_11_00-FPS_ 21 34 _ Vulkan _ 0 0 10-10397-d53a8191-mfc-interrupts _ Star Wars_ The Forc](https://user-images.githubusercontent.com/20983844/82132777-44019900-9798-11ea-91a5-30a1d4366524.png)

E {RSX [0x01e385c]} RSX: Unsupported depth conversion (0x84)
E {RSX [0x029314c]} RSX: FS exports depth component but depth test is disabled (INVALID_OPERATION)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4639436/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by Xcedf** [comment]
![4](https://user-images.githubusercontent.com/7060586/124361196-82754400-dc36-11eb-819d-ce0a68d230fd.jpg)
Looks not that bad with WCB Enabled these days, but still very obvious post effect or wahtever it is issues.
Accurate Xflot (Accurate FM to be certain) seems to help to avoid game processing fails.

**Comment by legend800** [comment]
The full game is still broken because of this regression from almost a year ago :( https://github.com/RPCS3/rpcs3/issues/9199

Tried on today's build and no change - it's either infinite spinner or if I can reach the menu freeze on pressing Start.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6759267/RPCS3.log.gz)

Infinite spinner:
![2021-07-03 18_57_31-Window](https://user-images.githubusercontent.com/20983844/124370976-ecd7b580-dc31-11eb-91a8-b2e945a44bd6.png)

Far as I can get now:
![2021-07-03 18_54_09-Window](https://user-images.githubusercontent.com/20983844/124370977-eea17900-dc31-11eb-9f4f-878f4b9157fc.png)

**Comment by kd-11** [comment]
> ![4](https://user-images.githubusercontent.com/7060586/124361196-82754400-dc36-11eb-819d-ce0a68d230fd.jpg)
> Looks not that bad with WCB enabled these days, but still very obvious post effect or wahtever it is issues.
> Accurate Xflot (Accurate FM to be certain) seems to help to avoid game processing fails.

It's borked SPU post-processing. I figured out what causes it a while back, but a performant implementation will take some time to get done properly. Same applies to all games with the honeycomb pattern.

**Comment by KBouder** [comment]
![image](https://user-images.githubusercontent.com/11525691/160268258-c914f55f-be97-4419-a4e6-9ab6207b120f.png)
It seems to be a little worse than it was previously even with WCB enabled.

**Comment by Andystew94** [comment]
Hello, just wanted to confirm if this was still being looked at. Cheers!

**Comment by Crytoz** [comment]
likewise, is this issue still being worked on?

**Comment by Darkhost1999** [comment]
No need to worry. This issue is still open. Afaik as long as star wars force unleashed 1 and 2 share the same/similar issues then the fix may already exist but is too slow. Let's give it some more time in the oven and realize things take months not weeks or days to fix sometimes.
Things won't change overnight. And I don't want a solution that makes the entire game unplayable at like 3fps even if it does look good. I'd rather play the game as is with the issues.

**Comment by Triticum0** [comment]
Can this be closed?
