### ISSUE TITLE
asuras wrath episode selection crash

### ISSUE THREAD

**Issue by mrmetapod** [RPCS3/rpcs3#8249]
Quick summary
whenever i try to enter the episode selection menu it crashes, other menus and the game dont crash and work perfectly.
Details

the expected response is it showing the unlocked episodes while in the emulator it freezes and does not respond to any imput
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4640541/RPCS3.log.gz)
more specificaly the line that caught my attencion is
F {PPU[0x1000019] Thread (MultiStream Update Thread) [0x00988304]} VM: Access violation reading location 0x21cb0120 (unmapped memory) 

![eqr](https://user-images.githubusercontent.com/65245715/82153682-6c909e00-983f-11ea-9ef7-5ec8a5139563.PNG)
![htds](https://user-images.githubusercontent.com/65245715/82153685-6d293480-983f-11ea-9275-d1ea3374b8fe.PNG)
![dfsdfs](https://user-images.githubusercontent.com/65245715/82153686-6dc1cb00-983f-11ea-8e80-acf6bc58aecd.PNG)
![Captura](https://user-images.githubusercontent.com/65245715/82153687-6e5a6180-983f-11ea-87f9-be7aa3044da2.PNG)
![dsfsd](https://user-images.githubusercontent.com/65245715/82153688-6e5a6180-983f-11ea-83e3-debebee96e50.PNG)
screenshots of my settings
running windows 10 the latest version by 17/5/2020

please help

**Comment by mrmetapod** [comment]
btw im running the european copy serial BLES01227 in the 1.02 update

**Comment by AniLeo** [comment]
Log file shows pirated game, removed.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by asdasdadsadsasdsd** [comment]
did you manage to solve the problem?

**Comment by Jonathan44062** [comment]
it makes no sense to answer that is already 2 years old, besides his copy was pirated, join the rpcs3 discord server to ask for help instead of here.

**Comment by asdasdadsadsasdsd** [comment]
> it makes no sense to answer that is already 2 years old, besides his copy was pirated, join the rpcs3 discord server to ask for help instead of here.

ok jonathan44062 go suck some toes bitch
