### ISSUE TITLE
Wolfenstein [BLUS30298]: Unable to read save files

### ISSUE THREAD

**Issue by TigiHof** [RPCS3/rpcs3#8251]
An old and known bug, but obviously there never was an issue opened for this.
In Wolfenstein [BLUS30298] you can not load save files, the game simply gets stuck (see screen shot). The automatic creation of save files at checkpoints seems to work fine, since the files are present on the hard disc.

![Wolfenstein](https://user-images.githubusercontent.com/31275840/82156101-78995180-9879-11ea-83b1-15e635a7af3b.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4640731/RPCS3.log.gz)

**Comment by elad335** [comment]
Still an issue? try to use newer savedata from latest master.

**Comment by TigiHof** [comment]
Yes, unfortunately the problem still persists!

**Comment by dcbryantmjkda** [comment]
Any updates folks?

**Comment by MateyBoi** [comment]
Are there any updates on this? It would be a shame for this game to not be supported, apart from the save issue everything else works 100% and emulation is pretty much the only way to play it safely now (it's not available to buy from any digital marketplaces).

**Comment by BrancuAlexandru** [comment]
I played 33% of it in one session yesterday, it would be a real shame to not be able to continue. No one's found a cause for this?

**Comment by FlexBy420** [comment]
v0.0.22-13595-524da5dc
Still an issue.
