### ISSUE TITLE
Update check causes RPCS3 Window lock

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#8252]
**Issue**
As the title says, when opening rpcs3, the update check causes the window to lock. This is a remnant of 90s feature, which was not present in previous rpcs3 versions.

**Recommendation**
Let the update check happen on background (Async update check).

**Comment by sampletext32** [comment]
Actual download happens asynchronously, but every following tasks, such as 7z unpack, file checks/writes etc. happens in a UI thread. update_manager::handle_rpcs3() is the thing that should be extracted to another thread. 
Of course if I understand everything clear in the code.
Of course if it's worth time spending. As for me it's absolutely ok.

**Comment by jobs-git** [comment]
when you lunch rpcs3, it first checks update and blocks the whole UI.
