### ISSUE TITLE
Feature Request: Blinking "update notif icon" instead of dialog box

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#8254]
**Issue**
The dialog box that displays "asking to update" is quite disturbing especial when using older builds.

It always shows up and blocks user flow.

**Recommendation**
If dev would like to force update notification, I would like to recommend a "blinking update icon." I dont know how would it look like, but this way, normal user flow would not get block every time.

Also, there must be enough reason why user would like to use an older build,

**Comment by AniLeo** [comment]
There is already a setting to disable check for updates if you want to stay on an older build without having the update checks

**Comment by Megamouse** [comment]
And why do you open 2 issues for the same thing?

**Comment by jobs-git** [comment]
This is to recommend to remove the dialog box notice. the other is to recommend "lock less update" check and does not bother if dev wants to keep the dialog box notice.

**Comment by Megamouse** [comment]
Has this been implemented to your liking?

**Comment by jobs-git** [comment]
W0w, that was a great pull! It does not block anymore, notification about new update was also present. I think this is ok now.
