### ISSUE TITLE
Mass Effect 2: red outlines on 3D elements edges.

### ISSUE THREAD

**Issue by atomic83GitHub** [RPCS3/rpcs3#8258]
In the game "Mass Effect 2", most of the 3D objects have a red outline on their edges.

![Mass](https://user-images.githubusercontent.com/26351275/82221954-f19fb400-9920-11ea-9af5-b0fa78f3cda1.JPG)

*Note: I am using the EU disc based version with all the DLCs enable*

Here is the RPCS3 log:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4644542/RPCS3.log.gz)

Here is the RSX captures from the main menu:

[Mass Effect red issue RSX capture.zip](https://github.com/RPCS3/rpcs3/files/4644545/Mass.Effect.red.issue.RSX.capture.zip)

My system configuration: OS: Windows 10 64bits, CPU: AMD FX 8350, GPU: Nvidia GTX TITAN SLI (latest driver)

**Comment by Emulator-Team-2** [comment]
@atomic83GitHub 
Try setting the Anisotropic Filter to `Auto`.

**Comment by atomic83GitHub** [comment]
That did the trick, for you a lot for your tips:

![image](https://user-images.githubusercontent.com/26351275/82246072-5587a400-9944-11ea-99ad-4150c8019e6e.png)

I am sorry for creating this issue.
