### ISSUE TITLE
God Of War Ascension Text Issue

### ISSUE THREAD

**Issue by pouncha** [RPCS3/rpcs3#8266]
Hi
I can't read any text again (only glitches) in GOW Ascension for some updates already
I use Fr Language.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4655744/RPCS3.log.gz)

This game has also broken issues when is emulated by LLVM but works well with ASMJIT

**Comment by mignolo4** [comment]
The issue with text appeared with build v0.0.10-10362 so with pull request #8199 by @kd-11
![Senza nome](https://user-images.githubusercontent.com/14029629/82712070-7b37e480-9c87-11ea-9a85-ac35ae06cb19.jpg)

**Comment by pouncha** [comment]
ok,thank you.
So,I close it

**Comment by mignolo4** [comment]
Wait... why you closed it? The problem has not been solved yet :-)

**Comment by pouncha** [comment]
I closed it cause kd-11 has already noticed this bug and pull it on request #8199,so I thought that to let it opening wasn't needed.
I see that I should let it open until it will be fixed ;)

**Comment by kd-11** [comment]
Please retest with the build from https://github.com/RPCS3/rpcs3/pull/8283 when its ready. It should fix this problem.

**Comment by mignolo4** [comment]
Yes, fixed!
Thanks :-)
