### ISSUE TITLE
Prince of Persia Forgotten Sands audio disappears randomly.

### ISSUE THREAD

**Issue by RebelliousX** [RPCS3/rpcs3#8267]
Game: [ BLES00840 ] Prince of Persia the Forgotten Sands.

Issue: audio disappears randomly, while playing or even while loading the game in the loading screen .Usually happens within few minutes or even seconds after the game starts. No matter how long you wait when the audio goes out, it will never come back.

First build that has broken audio: 10324 .. #8140
Last build that worked fine with no issues: 10321 .. #8137

I tested more than one build, going all the way back to v0.0.7, it took me almost an hour to pin point the broken build. I used binary search.

rpcs3-v0.0.10-10406-3d320aea_win64 .... BAD
rpcs3-v0.0.10-10350-b6e85605_win64  ..... BAD

rpcs3-v0.0.10-10324-edde7485_win64 ..... BAD #8140
rpcs3-v0.0.10-10321-72bef8dd_win64 .... OK  #8137

rpcs3-v0.0.10-10317-fc68c508_win64 .... OK
rpcs3-v0.0.9-10309-2b75df22_win64 ..... OK
rpcs3-v0.0.9-10297-f4f0fb88_win64  ..... OK
rpcs3-v0.0.9-10181-c69691f1_win64  ..... OK
rpcs3-v0.0.9-9958-fd8cda0f_win64  ..... OK
rpcs3-v0.0.8-9511-f8b3c48a_win64   .... OK
rpcs3-v0.0.7-8615-c4d99f93_win64 .... OK

I am attaching the two log files.
[10324 RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4656320/10324.RPCS3.log.gz)
[10321 RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4656323/10321.RPCS3.log.gz)

**Comment by marcussacana** [comment]
This commit cause audio issues with `Dengeki Bunko: Fighting Climax [BLUS31535]` too
In the build 10324 (#8140) the Audio stops after then intro (basically the press start screen)
In the build 10321 (#8137) the Audio works without problem.

My Specs:
`Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz | 4 Threads | 7.94 GiB RAM | TSC: 3.200GHz | AVX+ | FMA3`
`GTX 960 (4GB)`

**Comment by elad335** [comment]
Test with #8340

**Comment by elad335** [comment]
fixed, close.

**Comment by RebelliousX** [comment]
Thanks :)
