### ISSUE TITLE
main menu black screen(persona 5)

### ISSUE THREAD

**Issue by drakebreeze** [RPCS3/rpcs3#8270]
i was able to open the game but when i get on the new game load and config the character is all black and the mask is white
![98002306_608221900043697_4744634214224232448_n](https://user-images.githubusercontent.com/65721849/82570414-069d6280-9b2e-11ea-8f40-64288c23fd73.png)

**Comment by RainbowCookie32** [comment]
Missing PC specs and RPCS3.log

**Comment by drakebreeze** [comment]
any idea of how do i fix it?

**Comment by RainbowCookie32** [comment]
Maybe start by adding the missing stuff I just said?

**Comment by drakebreeze** [comment]
send pc specs and the log here?

**Comment by RainbowCookie32** [comment]
_Yes_

**Comment by drakebreeze** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4663090/RPCS3.log)
![97768277_233396058107973_2628300074236510208_n](https://user-images.githubusercontent.com/65721849/82571830-000fea80-9b30-11ea-8cbf-6c3fbc2d16ab.png)

**Comment by AniLeo** [comment]
Ancient AMD driver (over two years old), ancient version of Windows 10
