### ISSUE TITLE
Red Dead Redemption crashes with SPU Mega

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8286]
After PR #7944, SPU Mega no longer works on Red Dead Redemption. The game crashes in the loading screen with a fresh cache, and with a built cache the emulator crashes when compiling the SPU modules.
[RPCS3 10105.log.gz](https://github.com/RPCS3/rpcs3/files/4674081/RPCS3.10105.log.gz) Log from last working build v0.0.9-10105
[RPCS3 10111.log](https://github.com/RPCS3/rpcs3/files/4674082/RPCS3.10111.log) Log from build that broke it v0.0.9-10111
VS Debug window on latest master when compiling the SPU modules
![image](https://user-images.githubusercontent.com/1712979/82760886-3767eb00-9dff-11ea-9a64-b5f4a873ffda.png)

EDIT: added stacks view picture from VS
![stacksview](https://user-images.githubusercontent.com/1712979/82762100-c37e1080-9e07-11ea-8948-e167cfd903af.png)

**Comment by Satan86** [comment]
looks to be the same crash in #7956

**Comment by lainiwaku** [comment]
want to  add some information : mega  work with asmjit

llvm safe = ok 
llvm mega = crash 
asmjit safe = ok 
asmjit mega = ok 

btw nekotekina are working on LLVM improve, may be need to try with this PR !? 
https://github.com/RPCS3/rpcs3/pull/8263

**Comment by Xcedf** [comment]
RDR as well as some other games crash for me on Mega after https://github.com/RPCS3/rpcs3/pull/7944
commit ae140a1

**Comment by xddxd** [comment]
![image](https://user-images.githubusercontent.com/1712979/82809899-d63f2680-9e95-11ea-86eb-dba040578910.png)
reverting this specific piece of code in #7944 makes mega work again.

**Comment by Xcedf** [comment]
Yea reverting last line works, and GoW still able to create Mega cache from scratch

**Comment by Nekotekina** [comment]
Please upload the SPU cache that fails to build

**Comment by xddxd** [comment]
https://www.dropbox.com/s/vdafk8x2a7rs385/spu-mega-v1-tane.dat?dl=0

**Comment by Nekotekina** [comment]
Please test https://github.com/RPCS3/rpcs3/pull/8296

**Comment by xddxd** [comment]
With #8296 SPU LLVM Mega works on RDR.

**Comment by xddxd** [comment]
Closing as PR was merged into master.
