### ISSUE TITLE
Blazing Angels 2 Regression: VirtualProtect failed after #8281

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#8287]
## Quick summary
Blazing Angels 2 now crashes when booting with:
`SIG: Thread terminated due to fatal error: VirtualProtect failed (00000003c1c51000, 0x13c7e000, addr=0x3cea00000, error=0x1e7)`
after PR #8281

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4675953/RPCS3.log)

**Comment by xddxd** [comment]
Test with #8289?
