### ISSUE TITLE
issue with menus DiRT 3

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#8288]
RPCS3 v0.0.10-10427-865180e6 Alpha | HEAD | Firmware version: 4.85
Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz | 16 Threads | 15.91 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3 | TSX

![FPS_ 30 01 _ Vulkan _ 0 0 10-10427 _ DiRT 3  BLES01287  5_25_2020 3_13_23 AM](https://user-images.githubusercontent.com/45731484/82803751-ede6c280-9e35-11ea-91b1-b6b4fb6fefd3.png)

[RPCS3 menus DiRT 3.log.gz](https://github.com/RPCS3/rpcs3/files/4676701/RPCS3.menus.DiRT.3.log.gz)

capture

https://drive.google.com/file/d/1cRdfIsmmrzGO6PtjGA3t6kg2hXdLDcT8/view?usp=sharing

**Comment by kd-11** [comment]
This used to render correctly, try and find the first regressed commit.

**Comment by Fabianpaw** [comment]
Just tried this myself, and it is working fine for me.
![Screenshot](https://user-images.githubusercontent.com/62476228/82811908-22886780-9e92-11ea-96c3-6206deb61325.png)

I noticed something different though, the menus are all blurry, the same as in #7295. Not sure if this is a regression.
![Blurry Menus](https://user-images.githubusercontent.com/62476228/82812032-5b284100-9e92-11ea-9ab6-daffcd491977.png)

**Comment by kd-11** [comment]
This still looks like a regression. I know it wasn't perfect before, but it was pretty decent. I remember this game from the 3D swizzled texture decoding PR from a few years ago and I can recall some screenshots from that.
