### ISSUE TITLE
VK_ERROR_FEATURE_NOT_PRESENT

### ISSUE THREAD

**Issue by TegarOk** [RPCS3/rpcs3#8293]
First time using Github, so im sorry if my question is wrong or bad. My connection for discord is worse.
So i have a problem with some of  new version RPCS3 (Test on build rpcs3-v0.0.10-10428-f56b3627_linux64 and rpcs3-v0.0.8-9693-e772dde3_linux64 ), every time using Vulkan the RPCS3 show the error and force close or crash, but OpenGL is working properly.
I want with Vulkan cuz the FPS is better and Good, with OpenGL the FPS i get is only 40 with some lag.
## Something info
The game was running on some old RPCS3 ( rpcs3-v0.0.6-8441-4ad784d6_linux64 and rpcs3-v0.0.6-8513-500a4fa2_linux64).
The game was Hatsune Miku F NPUB31241 and Idolm@aster One For All NPJB00611.
## My computer specs
Intel i5-2320 (4 Core).
RAM DDR3 8GB 1333Mhz (8x1).
XFX R7 260x 1GB.
Running on Linux or Ubuntu 20.04 LTS with MESA 20.0.4 and Vulkan instance version 1.2.135 (Vulkan SDK 1.2.135).
KDE.
## Log
RPCS3.log https://pastebin.com/Xdy16rxA (New)
RPCS3.log https://controlc.com/d18aa559 (Old),I have reach limit of pastebin.
## Short Log of

> Debugger: 0
Log file open failed: /home/nvb/.cache/rpcs3/RPCS3.log.gz (error 13)
WARNING: radv is not a conformant vulkan implementation, testing use only.
WARNING: radv is not a conformant vulkan implementation, testing use only.
Thread '' terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Requested feature not available (VK_ERROR_FEATURE_NOT_PRESENT)
(in file ../rpcs3/Emu/RSX/VK/VKHelpers.h:913)
RPCS3: Assertion Failed! Vulkan API call failed with unrecoverable error: Requested feature not available (VK_ERROR_FEATURE_NOT_PRESENT)
(in file ../rpcs3/Emu/RSX/VK/VKHelpers.h:913)
Found exec link: /tmp/.mount_rpcs3-8qKQAl/usr/bin/rpcs3
Debugger: 0
Dibatalkan (core didump)

**Comment by AniLeo** [comment]
https://github.com/RPCS3/rpcs3/wiki/Graphics-Driver-Issues#amd-mesa-

Second point on Vulkan
