### ISSUE TITLE
Harmonix Keyboard causes Rock Band 3 (BLUS30463) to freeze "{Usb Manager Thread} sys_usbd: Transfer Error: 4"

### ISSUE THREAD

**Issue by LinosM** [RPCS3/rpcs3#8295]
## Quick summary

I'm having trouble getting the Rock Band Keyboard to work in Rock Band 3. It's one of the whitelisted devices and I made sure to use Zadig to replace the driver with WinUSB.

The problem is with the dongle connected, the game crashes before it gets to the title screen. This error was also being spammed in the log:

"{Usb Manager Thread} sys_usbd: Transfer Error: 4"

Without the Rock Band Keyboard connected the game runs just fine and is playable.

## Details
Specs:
Windows 10 Home 1909 Build 18363.836
NVIDIA GeForce RTX 2070 SUPER
Intel(R) Core(TM) i7-8700K @ 3.70GHz
16GB DDR4

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4685326/RPCS3.log)

**Comment by RipleyTom** [comment]
Please test with latest rpcs3 version again.

**Comment by LinosM** [comment]
The Keyboard controller is working now and I am able to play the game with it just fine, appreciate the fix for it.

However, as mentioned in https://github.com/RPCS3/rpcs3/issues/10220#issuecomment-1114157300 having a PS3 instrument connected will cause a fatal error when closing the game, which has also been consistent with me. Though the Keyboard is the only ps3 instrument I have to test, everything else I own is for 360.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8635451/RPCS3.log)

**Comment by Megamouse** [comment]
please open a new issue for that error.
I'll close this one

**Comment by wesmwitt** [comment]
Hi quick question, which version of the keyboard were you able to get it to work with? Wii PS3 or Xbox?
