### ISSUE TITLE
Working buffer not big enough BLUS31437

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#8300]
## Quick summary
Experienced a fatal error regarding working buffer not bing enough on BLUS31437

## Details
Vulkan LLVM SPU safe gtx 1060 avx non-tsx intel xeon sandy bridge EP 2670
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4699341/RPCS3.zip)

**Comment by Megamouse** [comment]
probably fixed by #10617

**Comment by kd-11** [comment]
Heap corruption crash. Check requested size (it is 1.6GB for 1 draw call)
