### ISSUE TITLE
PPU compilation crashes on exit

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#8306]
RPCS3 always crashes if you stop the ppu compilation.

This is obviously pretty bad if you accidentally start the wrong game and try to quit.

**Comment by Nekotekina** [comment]
Because of timeout? Or something else?

**Comment by Megamouse** [comment]
uhm I think so, yes

**Comment by RainbowCookie32** [comment]
Cancelling the cache creation causes the emulator to hang, and then the "Some thread has probably deadlocked" prompt pops up.

![imagen](https://user-images.githubusercontent.com/16805474/83362961-e65e7680-a36b-11ea-864e-0bca4db6fb0b.png)

Attaching log in case it's worth anything.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4708511/RPCS3.zip)
