### ISSUE TITLE
"Create PPU Cache" creates a different cache than normal disc game boot

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#8307]
It's really cool that the "Create PPU Cache" option finally seems to work as intended.

But sadly the created cache seems to have a different hash than the normal cache that is created on **disc** game boot.

![image](https://user-images.githubusercontent.com/23019877/83353659-5cef7a00-a354-11ea-8313-40124ddc1cae.png)

This means that you basically have to create the cache on boot again anyway, and the prior created cache is not used.

EDIT: This seems to be happening on disc games with updates only (afaict)

**Comment by Nekotekina** [comment]
Is it on all disc games? And only on them?

**Comment by Nekotekina** [comment]
Is it on all disc games? And only on them?

**Comment by Megamouse** [comment]
I just tested. I think it only happens on Disc games that have updates installed in dev_hdd0.
So you might have to use the patch eboot instead of the disc eboot (if there is one)
