### ISSUE TITLE
huge performance regression in titles that use MLAA

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#8314]
#8175 broke it.
non-tsx and tsx path is affected.

before 8175
![unknown (1)](https://user-images.githubusercontent.com/17715080/83364154-676e3b80-a375-11ea-948c-28e39bfd1269.png)

PR 8175
![unknown](https://user-images.githubusercontent.com/17715080/83364133-3beb5100-a375-11ea-8ecc-f2c6c6de650a.png)

log before 8175:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4708595/RPCS3.log.gz)
Log 8175: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4708598/RPCS3.log.gz)

**Comment by Emogop** [comment]
Not in ALL of them. ICO is fine for example but its brother SotC not so much.
I've already opened the Issue #8222 but my CPU is way WAY worse than yours.

**Comment by Megamouse** [comment]
closing as duplicate
