### ISSUE TITLE
[Feature Request] Option to make rpcs3 log output's filename by game ID and time

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#8321]
Option to spilt logs based on game id and current time so old logs wont be forgotten after 2 runs. For this option each run of a different game at the same run of rpcs3 need to ouput more than one file, currently the output is merged into one file in this case.
~~an option made for testers with huge disk space.~~

**Comment by Megamouse** [comment]
Duplicate of 2044

**Comment by elad335** [comment]
right.
