### ISSUE TITLE
RSX errors after #8309

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8324]
After PR #8309, when some games (tested RDR and GTA IV) are being stopped, an `RSX: Memory allocation underflow!` error or a verification error is thrown.
![Screenshot_3](https://user-images.githubusercontent.com/1712979/83513362-5ab72800-a4da-11ea-80c4-cfe3e848d537.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4716691/RPCS3.log) - RDR log, verification error
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4716743/RPCS3.log.gz) - GTA IV log, memory allocation underflow

Specs:
Ryzen 7 2700
RX 580 20.5.1
Windows 10 2004

**Comment by kd-11** [comment]
Just to be clear - this only happens when closing and not when playing the game normally, right?

**Comment by xddxd** [comment]
Correct
