### ISSUE TITLE
I have a laptop with Intel(R) Core(TM) i5-4210U-CPU @ 1.70GHz   2.40GHz with 4 GB ram which would be the best RPCS settings for my laptop?

### ISSUE THREAD

**Issue by DanGotTalent** [RPCS3/rpcs3#8327]
## Quick summary
Please summarize the issue here

## Details
Please provide as much detail as you can here, including
- expected (real hw) and observed (emulator) behavior
- full logs (not from UI)
- back traces (for hard crashes)
- screenshots, Renderdoc, and RSX captures (for visual issues)
- your system configuration (OS, CPU, GPU, driver versions, etc)
- anything else you deem to be important

**Comment by AniLeo** [comment]
Stop spamming
