### ISSUE TITLE
Which RPCS settings would be best?

### ISSUE THREAD

**Issue by DanGotTalent** [RPCS3/rpcs3#8328]
I have a laptop with Intel(R) Core(TM) i5-4210U-CPU @ 1.70GHz 2.40GHz with 4 GB ram which would be the best RPCS settings for my laptop? And I also dont have Vulkan GPU should I download it ,if yes then from where?

**Comment by RainbowCookie32** [comment]
Stop spamming the issue tracker, it's not the place for this. Move to the forums or [our Discord server](https://discord.me/RPCS3).

**Comment by AniLeo** [comment]
Banned from Git repository.
