### ISSUE TITLE
Demon's Souls - [BLUS30443] with HD font mod infinite loading screen after build 10321 

### ISSUE THREAD

**Issue by mshpakov** [RPCS3/rpcs3#8331]
## Quick summary
Build 10324-edde7485 introduces infinite loading screen for Demon's Souls - [BLUS30443] with HD Font Mod

## Details
rpcs3-v0.0.10-10324-edde7485_win64 - build is bad 
all builds with #8140 are showing infinite loading screen for Demon Souls with HD font Mod
rpcs3-v0.0.10-10321-72bef8dd_win64 - is ok. 

Reverting to original font files - fixes the issue. But on 4k display original font is ugly.

HD font source: https://github.com/SonofUgly/DeS-Texture-Pack/tree/master/font

[RPCS3-10321.log.gz](https://github.com/RPCS3/rpcs3/files/4720455/RPCS3-10321.log.gz)
[RPCS3-10324.log.gz](https://github.com/RPCS3/rpcs3/files/4720457/RPCS3-10324.log.gz)

**Comment by MSuih** [comment]
Did you follow the instructions in https://github.com/SonofUgly/DeS-Texture-Pack#install ?

Any issues with third-party game modifications should be reported to the creator of that modification first.

**Comment by mshpakov** [comment]
Yes. Sure, I've dropped cached folder each time I've tested new build.

This is issue is already known to mod's creator https://www.nexusmods.com/demonssouls/mods/7?tab=posts

Also I've tried few other mods which change graphics in DS (introduce HD textures) and they all started to show the same infinite loading screen after build 10321

**Comment by elad335** [comment]
Test with #8340

**Comment by dio-gh** [comment]
The issue isn't related to the mod, I'm having the same issue and I don't remember installing it. Will try that PR whenever the CI jobs finish.

**Comment by mshpakov** [comment]
Infinite loading screen is still here with rpcs3-v0.0.10-55708dc2_win64.7z 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4740004/RPCS3.log.gz)

**Comment by elad335** [comment]
fixed, close.
