### ISSUE TITLE
Killzone 2 [BCES00081] - regression after PR8299

### ISSUE THREAD

**Issue by davewuk** [RPCS3/rpcs3#8332]
Killzone 2 has visual artifacts after the implementation of stippled rendering. It looks like it should be using stippled rendering to fade in/out objects to avoid pop-in but it happens at incorrect distances or just randomly.

This issue exists in build rpcs3-v0.0.10-10439-c9a978a0_win64 but not in rpcs3-v0.0.10-10435-3df83e03_win64

Happens in all game modes and maps that I tested.

Screenshot of issue
![Image1](https://user-images.githubusercontent.com/55807111/83636352-c1e9e080-a59d-11ea-9a75-d099d85345e9.png)

Log from build with the issue
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4723224/RPCS3.log.gz)

Screenshot from earlier build
![Image2](https://user-images.githubusercontent.com/55807111/83636806-7be14c80-a59e-11ea-8f87-720a54746913.png)

Log from earlier build
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4723266/RPCS3.log.gz)

I can't provide an RSX capture for this as the glitch is so fast, barely enough time to take a screenshot.

**Comment by kd-11** [comment]
Are we talking about a performance issue? We don't pick the LOD swap distances and if it is that fast then its likely we're talking about a performance issue where the effect is just slow enough on rpcs3 to be noticeable.

**Comment by davewuk** [comment]
No not at all. This is happening on the ground and on buildings at both near and far distances. Basically as you are walking around parts of the map dissolve into and out of existence randomly.

**Comment by davewuk** [comment]
Link to video of issue

https://1drv.ms/v/s!Ah8-tXJT4RvZgrZQ0EmZIHTBNC31aw

**Comment by kd-11** [comment]
Ok, I think maybe the flag is stippling is staying on longer than it needs to. I'll investigate.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/8336
