### ISSUE TITLE
Regression: Gran Turismo 5 transparency issue in replays (#6224)

### ISSUE THREAD

**Issue by alexloxldlol** [RPCS3/rpcs3#8334]
Version that caused the problem: v0.0.6-8391 https://github.com/RPCS3/rpcs3/pull/6224
![image](https://user-images.githubusercontent.com/17052352/83659944-7bf44300-a5c4-11ea-937f-1838fbf22362.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4724709/RPCS3.log.gz)

Screenshot from earlier build: v0.0.6-8386

![image](https://user-images.githubusercontent.com/17052352/83660536-40a64400-a5c5-11ea-820c-a6894ba92217.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4724752/RPCS3.log.gz)

@kd-11

**Comment by illusion0001** [comment]
Missing rsx capture and log

**Comment by alexloxldlol** [comment]
rsx capture (cannot be uploaded here) 
https://mega.nz/file/GxJFBYzQ#Pdx1MdXJAySQFnT6V_oF51xsg2GvBvLSGIjvwKDH8MY

**Comment by aka2k** [comment]
This is odd: I've been getting these issues for over a year. I thought it was an expected issue.

**Comment by Satan86** [comment]
looks like 1080p resolution fixes the issue

720p RSX capture:
[BCUS98114_20200607041713_capture.zip](https://github.com/RPCS3/rpcs3/files/4741348/BCUS98114_20200607041713_capture.zip)
1080p RSX capture:
[BCUS98114_20200607042149_capture.zip](https://github.com/RPCS3/rpcs3/files/4741350/BCUS98114_20200607042149_capture.zip)

720p log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4741373/RPCS3.log.gz)
1080p log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4741375/RPCS3.log.gz)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/8438

**Comment by alexloxldlol** [comment]
Fixed
