### ISSUE TITLE
Another LLVM compilation issue

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#8343]
When trying to compile LLVM under Visual Studio versions 16.6.0 to 16.6.2 I get the following error output everytime.
[llvm.txt](https://github.com/RPCS3/rpcs3/files/4729799/llvm.txt)

I can't use precompiled objects because of #8111
I use "Release - LLVM" build configuration.

**Comment by xddxd** [comment]
Reset your llvm_build directory to like it is in the rpcs3 repo

**Comment by elad335** [comment]
Seems working, thanks.
