### ISSUE TITLE
The Last of Us frequent freezing in these two stages 

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#8345]
CHAPTERS : Pittsburgh 
STAGE : Financial District  & Escape the City 

In the above two stages, the game is random freezing and appear following logs : 
F {SPU[0x4000100] Thread (highCellSpursKernel4) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)
F {SPU[0x1000100] Thread (highCellSpursKernel1) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)
F {SPU[0x0000100] Thread (highCellSpursKernel0) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)
F {SPU[0x3000100] Thread (highCellSpursKernel3) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)
F {SPU[0x5000100] Thread (highCellSpursKernel5) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)
F {SPU[0x2000100] Thread (highCellSpursKernel2) [0x02464]} VM: Access violation reading location 0x0 (unmapped memory)

This problem has a long history and has not been fixed until the latest version

**Comment by illusion0001** [comment]
This is known and caused by disabling MLAA. Same behavior on realhw.
