### ISSUE TITLE
AMD OpenGL driver crashes in GT6

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8349]
On Gran Turismo 6, when using OpenGL, the AMD OpenGL driver crashes with an integer division by zero error when entering a track.
![Screenshot_4](https://user-images.githubusercontent.com/1712979/83813618-65361500-a6c6-11ea-8ea0-6e1f62b5ac35.png)
![Screenshot_6](https://user-images.githubusercontent.com/1712979/83813631-68310580-a6c6-11ea-8ef0-c957e12de825.png)
Log - [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4732885/RPCS3.zip)
Specs:
Ryzen 7 2700
RX 580 20.5.1
Windows 10 2004

**Comment by kd-11** [comment]
So much has changed since this report, we use compute shaders to decode textures now so this path shouldn't be hit anymore.

**Comment by DaishinSilviaGT** [comment]
Something is still there, crashes right at this spot shown on the screen on Tsukuba Curcuit Single Race, can be on other tracks too
GPU: RX 470 4 GB
Driver version: 22.9.2 Adrenalin Edition

[RPCS3 GT6 OpenGL Tsukuba.zip](https://github.com/RPCS3/rpcs3/files/9660475/RPCS3.GT6.OpenGL.Tsukuba.zip)

![unknown_2022 09 28-03 23](https://user-images.githubusercontent.com/89948611/192663797-27991312-1009-4a2b-ab61-3e12fd98472a.png)
