### ISSUE TITLE
rpcs3 appimage not opening ubuntu.

### ISSUE THREAD

**Issue by TheDarkKnightRise** [RPCS3/rpcs3#8353]
So i installed rpcs3 on ubuntu a while ago, but when i tried to reinstall it after uninstalling it, the appimage would just not open. Before you ask, I made sure that they got executable rights, but when i double click on it or open it when right clicking, nothing showed up. I tried another appimage from something else and it worked. I tried several older versions but nothing worked.

**Comment by AniLeo** [comment]
This is not the place to ask for support as indicated on the guidelines

The AppImage itself is working fine and you provide no debug information whatsoever even if it wasn't
