### ISSUE TITLE
Activision games have serious flickering problems

### ISSUE THREAD

**Issue by Josivan88** [RPCS3/rpcs3#8360]
Activision games show many similar vertex problems:
Goldeneye 007 reloaded:

![Goldeneye 007](https://user-images.githubusercontent.com/36341425/83920485-b2f85f00-a752-11ea-91c1-d9830d8512b4.jpg)

Log:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4738358/RPCS3.log.gz)

RSX Capture:

https://drive.google.com/file/d/1WbJJ5Aq5gk-O7xaJxgBEGUF8QSLOedsx/view?usp=sharing

007 Legends
![007 Legends](https://user-images.githubusercontent.com/36341425/83921466-c99fb580-a754-11ea-9314-a3750cdfd1f7.jpg)

log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4738435/RPCS3.log.gz)

RSX Capture:
https://drive.google.com/file/d/1pn5DrJtJJ82F11RewPDb8yK25SMAW_e4/view?usp=sharing

Call of duty Black ops 3

![BO 3](https://user-images.githubusercontent.com/36341425/84343393-6fe92200-ab7e-11ea-8500-6591a31ed683.jpg)

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4762494/RPCS3.log.gz)

RSX Capture:
https://drive.google.com/file/d/1F2nPE3tGTDh0RP24ytWjX90Wz3-IQv_7/view?usp=sharing

It seems to be something more prominent in weapons. This problem is old and came for years with these games

PC specs:
i7 9700K
32Gb of DDR4 memory
1070 GTX

Any other info required I am here to help.

**Comment by Josivan88** [comment]
the problem still exists on 0.0.11-10661

**Comment by kd-11** [comment]
Known issue with Z values outside 0-1 range rendered with a clip volume that holds values outside the 0-1 range. Seen in games using a floating type Z buffer, I'll run some hardware tests to figure out the correct solution. Currently rpcs3 is still using a hack I added many years ago, but the Z data compression introduced forces the excess data to be crammed inside something less than 10 bits of Z precision which is not enough when used by an engine to render everything.

**Comment by kd-11** [comment]
I forgot I had already researched this at depth a few years back. On PS3 depth buffer can store values outside the 0-1 range without issue if the format is floating point. This is an nvidia-specific extension to OpenGL so I chose to use the range compression to try and mitigate the problem in a universal manner. I'll just add support for extended range wherever possible in hardware, not much I can do about hardware that does not support this.

**Comment by kd-11** [comment]
At least its doable. Running on AMD GPU in this screen:
![image](https://user-images.githubusercontent.com/15904127/90063165-9f88e780-dcf1-11ea-95fd-07ab883ecc8b.png)

Unfortunately there are multiple driver/hw requirements to get this working means multiple code paths must be implemented for this to work. Requires more effort than I anticipated, but should be ready in a few more days.

**Comment by Josivan88** [comment]
Is highly probable that Goldeneye 007 reloaded and 007 Legends will become fully playable with this fix

**Comment by kd-11** [comment]
> Is highly probable that Goldeneye 007 reloaded and 007 Legends will become fully playable with this fix

Yes, at least graphics-wise there doesn't seem to be much that is broken.

**Comment by kd-11** [comment]
Implemented support for required features partially in https://github.com/RPCS3/rpcs3/pull/8741. Its a very large job, but its my fault for ignoring this rare set of features for so long as they were not used in many games.

**Comment by X4CD** [comment]
just tried to play Golden eye 007 reloaded and was getting graphical glitches, glad to see people are working on a fix!

**Comment by Josivan88** [comment]
Sorry for my mistake on the last post about COD BO3 in the last PR @kd-11 
007 Legends have the flickering solved but screens become black or gray depending on the situation (it may or may not be related)
![007 legends](https://user-images.githubusercontent.com/36341425/91486049-1ee5f180-e882-11ea-9064-e10334c66085.jpg)
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5138374/RPCS3.log.gz)
RSX Capture:
[BLUS30983_20200827162325_capture.zip](https://github.com/RPCS3/rpcs3/files/5138380/BLUS30983_20200827162325_capture.zip)

Goldeneye 007 reloaded seems to be pretty good and just waiting for ##8766 to be fully playable!
![007 reloaded](https://user-images.githubusercontent.com/36341425/91487005-7f296300-e883-11ea-825b-e017f3479d68.jpg)

Call of duty black ops 3 is good too:
![COD BO3](https://user-images.githubusercontent.com/36341425/91487728-961c8500-e884-11ea-8cda-eaa867ac58fd.jpg)

Call of duty black ops is near to perfect graphically now:
The weapon is not semi-transparent anymore
While targeting weapon is not excessively blurred anymore
Seems a little more stable now
![COD BO](https://user-images.githubusercontent.com/36341425/91488345-8d787e80-e885-11ea-9669-ab014c383d0c.jpg)

**Comment by X4CD** [comment]
@Josivan88 how do you fix it, is it just a patch

**Comment by Josivan88** [comment]
@X4CD this is not the right place to ask for help, please contact me on RPCS3 discord, modder, please, clear these comments
