### ISSUE TITLE
BLES01967-[Injustice Gods Among Us Ultimate Edition]   crash

### ISSUE THREAD

**Issue by EljugadorMisterioso** [RPCS3/rpcs3#8361]
## Quick summary
F {RSX [0x00106fc]} SIG: Thread terminated due to fatal error: Dead FIFO commands queue state has been detected!
Try increasing "Driver Wake-Up Delay" setting in Advanced settings.
(in file D:\a\1\s\rpcs3\Emu\RSX\RSXThread.cpp:2325)
## Details

Processor: AMD Ryzen 7 1700 Eight-Core Processor           (16 CPUs), ~3.0GHz
Memory: 16332MB RAM
Available OS Memory: 16332MB RAM
Operating System: Windows 10 Pro 64-bit (10.0, Build 18363)
Windows Dir: C:\Windows
GPU: GTX1060 6 GB
DirectX Version: DirectX 12

**Comment by EljugadorMisterioso** [comment]
![imagen](https://user-images.githubusercontent.com/66501574/83933188-075c0880-a76c-11ea-82a5-06bf33e149ac.png)

**Comment by elad335** [comment]
No log nor proper description, closing for now.
