### ISSUE TITLE
[FEATURE REQUEST] Database of patches

### ISSUE THREAD

**Issue by marcoluc97** [RPCS3/rpcs3#8366]
## Database of patches
Summary:
Related to PR #8335, #8405  and first Issue #7346
Improvement #8404 

@AniLeo just to know if this is stupid or a good feature request, do you think is possible to use the Compatibility database you use on the RPCS3 website, and add the patches for each GAMEID?

@Nekotekina @Megamouse do you think is something useful? maybe using github as backend/storage for add/push new patches. Dunno..

**Comment by HerrHulaHoop** [comment]
We already have a database of patches [on our wiki](https://wiki.rpcs3.net/index.php?title=Help:Game_Patches). Patches are stored on a per-game basis and open for contribution from anyone in the community.

The end-goal would be to bundle the patches with the emulator. But what gets included and what doesn't is still under discussion.

**Comment by Ghostotakoi** [comment]
What about a git repo with the patches, that you can just click update patches on the patch manager and if is there any update, it will be downloaded an replace the old file? 

**Like this on Cemu**
![ScreenShot_20200606234427](https://user-images.githubusercontent.com/20958581/83959881-292ebb80-a850-11ea-9e9b-39819cde1984.png)

**Comment by asp0909** [comment]
I vote for that!

**Comment by conkis1** [comment]
Yes please!

**Comment by illusion0001** [comment]
A separate repository for patches sounds like a good idea, allowing users to create their own patches and submitting pull request for it.

**Comment by Ghostotakoi** [comment]
Now related to this PR: https://github.com/RPCS3/rpcs3/pull/8504

**Comment by HerrHulaHoop** [comment]
Download button has been implemented by #8848. Wiki handles the database of patches. This issue can be closed.
