### ISSUE TITLE
Dark souls 2 - choppy audio effects

### ISSUE THREAD

**Issue by EljugadorMisterioso** [RPCS3/rpcs3#8368]
## Details
Processor: AMD Ryzen 7 1700 Eight-Core Processor (16 CPUs), ~3.0GHz
Memory: 16332MB RAM
Available OS Memory: 16332MB RAM
Operating System: Windows 10 Pro 64-bit (10.0, Build 18363)
Windows Dir: C:\Windows
GPU: GTX1060 6 GB
DirectX Version: DirectX 12

![imagen](https://user-images.githubusercontent.com/66501574/83951318-4a62be00-a7f6-11ea-8928-078a802b1cbb.png)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
