### ISSUE TITLE
dark souls 2 - choppy audio effects

### ISSUE THREAD

**Issue by EljugadorMisterioso** [RPCS3/rpcs3#8369]
## Quick summary
The game is playable at 50 and 60 fps there is only one problem in the sound effects that occur when you enter battle or the sound of swords when colliding with an enemy or some object or connecting two consecutive hits and when you leave and enter the water the sound is choppy try several settings the one that gave me the best results was to reduce the duration of the audio buffer by 10 ms and select convert to 16-bit in XAudio2 the choppy does not disappear; but it is less constant some occasions.

## Details
Processor: AMD Ryzen 7 1700 Eight-Core Processor (16 CPUs), ~3.0GHz
Memory: 16332MB RAM
Available OS Memory: 16332MB RAM
Operating System: Windows 10 Pro 64-bit (10.0, Build 18363)
Windows Dir: C:\Windows
GPU: GTX1060 6 GB
DirectX Version: DirectX 12

![imagen](https://user-images.githubusercontent.com/66501574/83951318-4a62be00-a7f6-11ea-8928-078a802b1cbb.png)

**Comment by kd-11** [comment]
I have the same CPU (but overclocked) and I am not experiencing this issue. This makes it likely to be a config problem. Provide logs for further analysis.

**Comment by LittleStinky123** [comment]
I had the same problem on my 8700K.
When I disabled SPU loop detection, it sounded normal.

**Comment by LittleStinky123** [comment]
I made some logs for DS2 with default settings except resolution where I either enabled SPU loop detection or disabled it.
The audio is choppy when loop detection is on.
I don't know if RSX captures are useful, but I made one before and after hitting the wall that led to the choppy audio with the setting on and off.
They are too big to be uploaded though.

[RPCS3_no_loop_detection.log](https://github.com/RPCS3/rpcs3/files/4742408/RPCS3_no_loop_detection.log)
[RPCS3_loop_detection.log](https://github.com/RPCS3/rpcs3/files/4742410/RPCS3_loop_detection.log)

**Comment by RainbowCookie32** [comment]
Audio issues are a potential side effect from using SPU Loop Detection, it's right there on the setting's description. If disabling it fixes the issue, then this can be closed

**Comment by kd-11** [comment]
SPU loop detection was added specifically because of low core CPUs at the time. With a 1700 you almost never need this option enabled, its likely to cause more problems than be helpful.
