### ISSUE TITLE
Smoke artefacts in menu of Metal Gear Solid HD Collection [BLUS30847]

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#8370]
![image](https://user-images.githubusercontent.com/23019877/83951526-49e81880-a832-11ea-94df-7617eefe6923.png)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/23019877/128616039-60fc417f-d346-481d-b26c-73801c3498c9.gif)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4740763/RPCS3.log)

[BLUS30847_20200606201344_capture.zip](https://github.com/RPCS3/rpcs3/files/4740767/BLUS30847_20200606201344_capture.zip)

**Comment by jokoputera** [comment]
confirm on BLUS30847 v1.03. even after you pres X (Start Game), its just blank.

**Comment by Megamouse** [comment]
That doesn't make any sense. I'm on version 1.03 already and pressing x works as intended

**Comment by jokoputera** [comment]
sorry, my mistake not to elaborate further.
it has a "wire" smoke, and after i press X button, it open a new window, then it blank. i dont think its for this PR. sorry.

**Comment by homedepotiraq** [comment]
have you found a fix to this problem yet?

**Comment by jokoputera** [comment]
any update about this one?

**Comment by RainbowCookie32** [comment]
Still an issue

![Screenshot from 2021-06-12 20-54-14](https://user-images.githubusercontent.com/16805474/121791479-6a268200-cbc0-11eb-8af4-bfe7fa1b1b1e.png)
[BLUS30847_20210612205409_capture.zip](https://github.com/RPCS3/rpcs3/files/6643032/BLUS30847_20210612205409_capture.zip)

**Comment by jokoputera** [comment]
as a fix for lines in https://github.com/RPCS3/rpcs3/pull/10676, maybe @kd-11 able to take a look at this?

**Comment by TideGear** [comment]
I can confirm this is still occurring with the current version (RPCS3 Version: 0.0.21-13527-e9570d1a Alpha | master). Is there any tweak to fix it?

**Comment by Machina74** [comment]
I can confirm this issue. I see the same using an RTX 3080 while gaming in 4K.

**Comment by z411** [comment]
Confirm with GTX 1660ti. It looks like there's something wrong with the alpha layer of those textures.

**Comment by kd-11** [comment]
Needs a newer RSX capture file. The provided ones do not load anymore.

**Comment by Jonathan44062** [comment]
New RSX Capture:
https://www.mediafire.com/file/23sfzuzzv5aqx31/BLUS30847_20221112144541_capture.rrc/file

**Comment by kd-11** [comment]
Ok, got it. It's a minor ROP rounding glitch.
I'll push a fix for it tomorrow.

**Comment by TideGear** [comment]
> Ok, got it. It's a minor ROP rounding glitch. I'll push a fix for it tomorrow.

You rock!
