### ISSUE TITLE
Splatterhouse [BLUS30335] Shadows render incorrect and constantly appear/disappear

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#8372]
Shadows render incorrect and constantly appear/disappear all over the place.

![2020-06-06 10_50_50-Settings](https://user-images.githubusercontent.com/20983844/83951778-e4236e80-a7e8-11ea-8adf-301613d1cd26.png)

![2020-06-06 10_51_01-FPS_ 29 94 _ Vulkan _ 0 0 10-d9d4a22b-rsx_volatile _ SPLATTERHOUSE  BLUS30335](https://user-images.githubusercontent.com/20983844/83951779-e4bc0500-a7e8-11ea-9224-3fc10e72589d.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4740782/RPCS3.log.gz)

[BLUS30335_20200606105113_capture-Splatter.zip](https://github.com/RPCS3/rpcs3/files/4740784/BLUS30335_20200606105113_capture-Splatter.zip)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by AniLeo** [comment]
What about #8367

**Comment by legend800** [comment]
Sadly the magical pr that fixes 100+ defects doesn't impact this. It's something else.

![2020-06-07 00_15_56-FPS_ 30 03 _ Vulkan _ 0 0 10-d9d4a22b-rsx_volatile _ SPLATTERHOUSE  BLUS30335](https://user-images.githubusercontent.com/20983844/83962672-2a61e780-a854-11ea-94a2-1dd4b13804f9.png)

**Comment by legend800** [comment]
Still present as of 5/15/21 build.

![2021-05-15 01_22_14-Window](https://user-images.githubusercontent.com/20983844/118353646-21759d80-b51c-11eb-90a3-0265cfe4e059.png)
![2021-05-15 01_22_35-Window](https://user-images.githubusercontent.com/20983844/118353650-23d7f780-b51c-11eb-99e6-ef15bc261db4.png)

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
Still present as of 9/23/21

**Comment by nitroos-ai** [comment]
Retest with latest master build.

**Comment by legend800** [comment]
Nope still doesn't render correctly. They just flicker and in wrong location every step.

![2021-12-04 16_59_00-PS3](https://user-images.githubusercontent.com/20983844/144729329-088ce51a-31f1-447f-8eab-5e14158652af.png)

**Comment by legend800** [comment]
Still an issue as of 0.24.14141 (Sep '22).
