### ISSUE TITLE
MotorStorm [BCES00006]: Misc gfx issues

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#8373]
Motorstorm has 2 remaining gfx issues:

1) The Boost hud area has corruption (not 100% repro, more like 80%) and pause/ranking areas in UI
2) Dirt clouds from other vehicles is purple at all times (sometimes it's correct color - brown)

![2020-06-06 11_10_28-FPS_ 29 40 _ Vulkan _ 0 0 10-d9d4a22b-rsx_volatile _ MotorStorm™  BCES00006](https://user-images.githubusercontent.com/20983844/83951947-3749f100-a7ea-11ea-9111-481d00314ed9.png)

![2020-07-19 12_33_09-Window](https://user-images.githubusercontent.com/20983844/87883897-7067aa80-c9bf-11ea-9c8b-b1b62ff55790.png)

![2020-06-03_00_08_29-rpcs3](https://user-images.githubusercontent.com/20983844/83952164-b4c23100-a7eb-11ea-835b-4cb5ab8f3fbb.png)

[RPCS3-MS.log.gz](https://github.com/RPCS3/rpcs3/files/4740797/RPCS3-MS.log.gz)

RSX capture:
https://drive.google.com/file/d/1ub34kYmQszwnbIytSzuAHdWkTdL83-P-/view?usp=sharing

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by dio-gh** [comment]
I'm not sure the vehicles shaking back and forth is a graphical issue, might be related to the crowd T-posing even (floating point issues?).

**Comment by incognitoh** [comment]
> I'm not sure the vehicles shaking back and forth is a graphical issue, might be related to the crowd T-posing even (floating point issues?).

pretty sure thats true since it doesnt happen if you use ppu interpreter (iirc)

**Comment by legend800** [comment]
Yeah, only happens with  PPU LLVM. Opened another issue to track that and updated this defect:
https://github.com/RPCS3/rpcs3/issues/8376

**Comment by legend800** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/11204
