### ISSUE TITLE
SPU,RSX & CellsThread making crashs

### ISSUE THREAD

**Issue by pouncha** [RPCS3/rpcs3#8380]
Can't play  MGS4 correctly.
Always crashes when SPU or RSX is compiled
Cells thread seem having a pb too

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4741731/RPCS3.log.gz)

I9 9900KF with Nvidia GTX1080 on Windows 10

**Comment by AniLeo** [comment]
This game is known to be unstable, generic issue saying it crashes doesn't help much. Use the support platforms.
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
