### ISSUE TITLE
BLES01114 Child of Eden hangs after first part of the first level

### ISSUE THREAD

**Issue by yacoob** [RPCS3/rpcs3#8394]
## Quick summary
BLES01114 boots, but freezes some way into the first level.

## Details
I've dumped the disc sitting on my shelf with Samsung SE-506. Game booted correctly, title and menu worked fine. Started playing, and things seemingly worked fine
![coe1](https://user-images.githubusercontent.com/190463/84183731-42b84900-aa84-11ea-9f68-2def1fe3bf81.png)
although the picture got progressively brighter and brighter as I played. At some point it became very hard to distinguish between the very hard background and the objects you're supposed to shoot at. 
![coe2](https://user-images.githubusercontent.com/190463/84183734-43e97600-aa84-11ea-945d-02cade2a3534.png)
The game decided to freeze past the first "tunnel" bit, although partially - the picture got frozen but the music continued.
![coe3](https://user-images.githubusercontent.com/190463/84183735-43e97600-aa84-11ea-8d67-a70cb202a83b.png)

Obviously, the real game works just fine. Or worked - I don't have a ps3 handy to verify whether my disc is still working as expected with the real hardware. Judging by [this thread](https://forums.rpcs3.net/archive/index.php/thread-182464.html) it's a common problem though. I've included a log trimmed down to last playthrough of the game.
[coe.log.gz](https://github.com/RPCS3/rpcs3/files/4753974/coe.log.gz)

I was running RPCS3 with `write color buffers`, `strict rendering mode`, `vsync` and `disable vertex cache` on. I can see that the log contains the full config anyway :) Running on Win10.0.19041.264, RTX 2070 Super with 3.20.3.63 nvidia drivers.

Happy to provide more data as necessary - I'd really love to see that game run flawlessly :D

**Comment by n1ckn4m3** [comment]
Of note, the crash doesn't always happen at the same spot (for me, anyways).  

I've been able to progress through the first level several times even on the current build, though it did crash where you indicated on the first run through.  It appears as though some kind of shader generation will soft-lock the emulator, but if you play the level again you will get through the tunnel just fine, progress to the boss fight, and then be able to beat the level. 

That said, the same thing happens on future levels as well.  It used to be more stable and I'm rolling back in builds to determine where the change happened, but about a year ago I played the first 3-4 levels in rpcs3 with little issue other than the over-bright blowout in a couple of places.  Once I find the build where this lost some stability, I'll add another reply or edit this one with the info.

If you keep trying, do you get past the tunnel in the Matrix level?  Or does yours consistently stop at that exact spot?

**Comment by yacoob** [comment]
I've attempted this level maybe ~15 times and it always locks up in roughly the same place, end of the tunnel.

**Comment by kurai021** [comment]
Fixed activating Asynchronous texture streaming in GPU options. some random crashes can occur in other parts of the game, but nothing fatal until the second part of stage Passion which will always end the process with the following error when you try to shoot:

F SIG: Thread terminated due to fatal error: Dead FIFO commands queue state has been detected!
Try increasing "Driver Wake-Up Delay" setting in Advanced settings.
(in file D:\a\1\s\rpcs3\Emu\RSX\RSXThread.cpp:2561[:25], in function recover_fifo)

**Comment by kurai021** [comment]
> Fixed activating Asynchronous texture streaming in GPU options. some random crashes can occur in other parts of the game, but nothing fatal until the third part of stage Passion which will always end the process with the following error when you try to shoot:
> 
> F SIG: Thread terminated due to fatal error: Dead FIFO commands queue state has been detected!
> Try increasing "Driver Wake-Up Delay" setting in Advanced settings.
> (in file D:\a\1\s\rpcs3\Emu\RSX\RSXThread.cpp:2561[:25], in function recover_fifo)

Increasing the driver wake-up delay didn't work for me

**Comment by cantoryakov** [comment]
After lots of fiddlng, I am able to get past the end of the first tunnel, but then my game craps out after I beat the first mini boss thing. The screen goes white and that's it. Thank you

**Comment by nitroos-ai** [comment]
On my end the crash has been fixed by reducing "Maximum number of SPURS threads" to 4 and enabling "HLE: libvdec.sprx".
[config_NPEB00649.zip](https://github.com/RPCS3/rpcs3/files/7575049/config_NPEB00649.zip)

**Comment by nitroos-ai** [comment]
Tried with #11754 but froze at the start of the game.
`E SYS: 'cellVdecDecodeAu' failed with 0x80610101 : CELL_VDEC_ERROR_ARG, vdec=1, auInfo=1, upper=0, startAddr=0x33adab00 [1]`
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8477398/RPCS3.log.gz)

**Comment by marcoluc97** [comment]
@Megamouse video tag?

**Comment by nitroos-ai** [comment]
with tag `Log: {cellVdec: Trace}`.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8481494/RPCS3.log.gz)

**Comment by Megamouse** [comment]
try again please

**Comment by nitroos-ai** [comment]
With #11754 the game can go now past first level without crashing and with no need of libvdec.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8483657/RPCS3.log.gz) 95Mb
