### ISSUE TITLE
Twisted Metal [BCUS98106]: Heavily broken graphics

### ISSUE THREAD

**Issue by gamax92** [RPCS3/rpcs3#8395]
## Quick summary
Twisted Metal has several graphical issues, broken text rendering, missing 3D graphics on title screen, and bad lighting in game. Lighting problems differ between what map you're on.

Tested on 0.0.10-10477-b75af69c
Using Vulkan renderer and Legacy Shader Mode
NVidia GTX 1050 Ti on 446.14 Driver
Windows 10 Pro 2004 (10.0.19041.264)

No amount of changing Read/Write Color/Depth Buffers settings improved graphics in any way.

## Details
Broken Text Rendering:
![2020-06-09_222627](https://user-images.githubusercontent.com/815145/84228147-7b1b4f80-aaa3-11ea-9b66-a7ab4aa2c716.png)
RSX Capture: https://drive.google.com/file/d/11wUYbmq0DG1btWwbVJgdYVE7YFlT5N38/view

Missing 3D Graphics:
![2020-06-09_222415](https://user-images.githubusercontent.com/815145/84228166-8cfcf280-aaa3-11ea-97db-f38cfa96b036.png)
RSX Capture: https://drive.google.com/file/d/1W1KrZC1U4YjaECV5MSFnKBC32SV_B2v1/view

Less broken lighting [Sunsprings, CA]:
![2020-06-09_223703](https://user-images.githubusercontent.com/815145/84228194-9f772c00-aaa3-11ea-8bbe-2a89e5f6be37.png)
RSX Capture: https://drive.google.com/file/d/1_IdXQ4fp0S_3jdK_AboT8tLQ03Kvw_c8/view

More broken lighting [Thrills and Spills]:
![2020-06-09_222957](https://user-images.githubusercontent.com/815145/84228211-aaca5780-aaa3-11ea-92c1-14aaed204344.png)

**Comment by illusion0001** [comment]
Missing rsx capture

**Comment by gamax92** [comment]
It's hard to get captures for this game, game tends to crash randomly and also tends to crash trying to get a capture, still working on it

**Comment by illusion0001** [comment]
Try increasing driver wake up delay

**Comment by gamax92** [comment]
It seems after #8575 the missing title screen graphics and the dark shadows have been fixed
The only thing that still remains is the broken text rendering.

**Comment by jeremybris** [comment]
Fixed by #10453 :

Before:
![Capture3](https://user-images.githubusercontent.com/11889359/122860137-31d32200-d2eb-11eb-8252-abe41a967a00.PNG)

After:
![Capture](https://user-images.githubusercontent.com/11889359/122860158-3992c680-d2eb-11eb-9336-74fadcb6fcfb.PNG)

**Comment by kd-11** [comment]
Thanks for updating.
Closing as fixed by https://github.com/RPCS3/rpcs3/pull/10453
