### ISSUE TITLE
Soulcalibur 4, Tekken 6, Tekken tag tournament 2 bad perfomance at i5-4670k Haswell

### ISSUE THREAD

**Issue by KingKingov** [RPCS3/rpcs3#8400]
## Quick summary
Please summarize the issue here

## Details
Please provide as much detail as you can here, including
- expected (real hw) and observed (emulator) behavior
- full logs (not from UI)
- back traces (for hard crashes)
- screenshots, Renderdoc, and RSX captures (for visual issues)
- your system configuration (OS, CPU, GPU, driver versions, etc)
- anything else you deem to be important

**Comment by KingKingov** [comment]
I found a temporary solution "maximum number spurs threads" 4

**Comment by AniLeo** [comment]
Do not spam

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
