### ISSUE TITLE
Lair [BCUS98112] - Broken 4:3 intro videos and menu

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#8401]
<details>
<summary>Intro Videos</summary>

![image](https://user-images.githubusercontent.com/23019877/84359465-fa567380-abc8-11ea-808d-1a9de6877fe2.png)
![image](https://user-images.githubusercontent.com/23019877/84359473-fd516400-abc8-11ea-91b1-4af19671c0d9.png)
![image](https://user-images.githubusercontent.com/23019877/84359523-0e9a7080-abc9-11ea-94d6-b8c66be911aa.png)

</details>
<details>
<summary>Menu</summary>

![image](https://user-images.githubusercontent.com/23019877/84359571-1d812300-abc9-11ea-944b-4a8aaae9c999.png)
![image](https://user-images.githubusercontent.com/23019877/84359941-a8621d80-abc9-11ea-9d07-ba53844f8a09.png)

</details>

[RSX Capture (Last Picture in Menu Slidedown)](https://drive.google.com/file/d/1wnTTJeUgk5dxjlfNQv1feC2yN5mq2Qtw/view?usp=sharing)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4763359/RPCS3.log)

**Comment by fuhuan416** [comment]
yes, same issues here.

**Comment by bujinkanrn** [comment]
Same here
