### ISSUE TITLE
Potential features to improve the Patch Manager

### ISSUE THREAD

**Issue by HerrHulaHoop** [RPCS3/rpcs3#8404]
Now that the base version of the Patch Manager has been merged, here are some ideas to improve it:

- [x] Ability to import, export and delete patches through the GUI. 
   - **Import** - Allow users to drag and drop new patches on the Patch Manager. 
     - Check for formatting errors.
     - Also check whether the patch already exists in the file. If it does, check the patch version, if the version of new patch is greater than old patch, overwrite the existing patch with the new one.
   - **Export** - Allow users to select a particular patch (or multiple) and export it into a separate file. Ensure the format of the exported file is the same as imported files. **UPDATE:** Seems like this feature won't be needed since users can just share the `imported_patch.yml` file for all custom patches that they have.
   - **Delete** - This is more of a bonus. Allow users to select a particular patch (or multiple) and delete it.
- [x] Button to download the latest patch file. Ideally, these patches are subjected to the same checks as the Import function (mentioned above).
- [x] Option to disable legacy patches in the Patch Manager. Currently, any legacy patch detected is always shown as enabled and can't be disabled. If it's not feasible disable legacy patches, a button to disable it globally would be preferred. This is mostly necessary for users who have old and new versions of RPCS3 in the same folder. To use patches on all versions, they will have the old patch.yml file in the base directory and the new patch.yml file in the patches folder. This way the old versions will work just as it did before. But new versions reads both files and applies the legacy file in addition to the new files.

**Comment by Megamouse** [comment]
1 and 2 kinda contradict each other:
Why would I need an import/export/delete functionality if there is a database that will be downloaded?
Where do you put imports... how do you name the files? How do you know which files to load? What happens to those imports if you download the latest database...

3:
Old patches are not shown in the patch manager, since they only work by hash and don't have a key to seperate them from each other.
Therefore it's only possible to disable all legacy patches, or maybe disable all legacy patches per hash.

**Comment by HerrHulaHoop** [comment]
> Why would I need an import/export/delete functionality if there is a database that will be downloaded?

A lot of people in the PR thread were pointing to a scenario where modders are sharing patches to users to test before it gets added to online database. So the patches in question ideally won't be present on the online database at all or will be a new version that is in testing. In these scenarios, the tester would be forced to interact with the YML file directly and we're trying to reduce that.

> Where do you put imports... how do you name the files? How do you know which files to load? What happens to those imports if you download the latest database...

My assumption was if a new patch was imported, it simply gets appended to the end of the current file. If it's an existing patch, then the patch version gets checked and whichever version is latest gets retained. If you download the latest online database, it would go through the same system. New patches get appended to the end as-is and existing patches go through a version check.

> Old patches are not shown in the patch manager, since they only work by hash and don't have a key to seperate them from each other. Therefore it's only possible to disable all legacy patches, or maybe disable all legacy patches per hash.

Yeah I feared as much. A checkbox to disable all legacy patches should suffice I think.

**Comment by Megamouse** [comment]
> My assumption was if a new patch was imported, it simply gets appended to the end of the current file. If it's an existing patch, then the patch version gets checked and whichever version is latest gets retained. If you download the latest online database, it would go through the same system. New patches get appended to the end as-is and existing patches go through a version check.

And how do you manage deleted patches?
You'll have to overwrite the old file to keep trash from piling up.

A solution would be to also load a second patch file (e.g. patches/custom_patch.yml) and keep the patches/patch.yml reserved for a possible database. (or use a different name for the database yml)

**Comment by HerrHulaHoop** [comment]
Hmm, a separate file dedicated to just the database would work.

Just to clarify though, if the database file had a patch with version 1.0 and custom file had the same patch with version 1.1, would the Patch Manager be able to use the latest one and ignore the other? Or will we have to force the custom files to use unique patch names that don't conflict with the database?

**Comment by Megamouse** [comment]
I asked you if there could be duplicates, you said no.
So the patch manager only uses one of them, which depends on where in the file it's located.

**Comment by Megamouse** [comment]
3. should be implemented in #8405

**Comment by HerrHulaHoop** [comment]
> 3. should be implemented in #8405

That was fast 😄 

> I asked you if there could be duplicates, you said no.
So the patch manager only uses one of them, which depends on where in the file it's located.
It's strictly hash->name right now

I know I said there won't be any duplicates and for 99% of our userbase there won't be. They'll download the database of patches and use what is present. These ideas are aimed towards that remaining 1% who want to do a little more. Some sort of system to allow users to add and remove custom patches would be useful.

So perhaps the potential feature would be being able to read patches for the same hash from two files (database_patch.yml and custom_patch.yml). We could potentially simplify things by reading only non-duplicate patch names from the second file.

**Comment by HerrHulaHoop** [comment]
#8848 addresses the final point. The PR itself seems ready but changes need to be made on the server side before the PR can be merged.
