### ISSUE TITLE
Uncharted 3: Can Not Play LAN or Offline Split-Screen

### ISSUE THREAD

**Issue by jeremybris** [RPCS3/rpcs3#8416]
# Quick summary
I can not play LAN or Offline split-screen in Uncharted 3.

## Details
Continuation of #8028 for me. Here is a comparison of the issue not present vs. the issue present.

| No Issue | Issue | 
| ------------- | ------------- | 
| [RPCS3.log](https://github.com/RPCS3/rpcs3/files/5502988/RPCS3.log) | [RPCS3.log](https://github.com/RPCS3/rpcs3/files/4771151/RPCS3.log) | 

![Capture525](https://user-images.githubusercontent.com/11889359/84510770-8b921c80-ac93-11ea-8823-d6f80eb9562b.PNG)

- Windows 10 Latest version, AMD Ryzen 9 CPU, RTX 2080 Super
- [RPCS3.log](https://github.com/RPCS3/rpcs3/files/4771151/RPCS3.log)
- It shows the error sometimes: **E {PPU[0x10000ba] Thread (NetInit) [0x01455d28]} SYS: 'sceNpScoreInit' failed with 0x8002a101 : SCE_NP_COMMUNITY_ERROR_ALREADY_INITIALIZED [1]**
- and **sys_bnet error**
- I found two videos https://www.youtube.com/watch?v=4cuJpi1ygZQ and https://www.youtube.com/watch?v=yDfvx4TI1SE overcoming this issue, but those were on custom builds. 
- This issue is not present for superepic32 randomly.

I have tried these things, and they did not work:
- ~Deleting my save~
- ~Deleting my cache~
- ~Deleting my config~
- ~Deleting everything. Reinstalling RPCS3~
- ~Changing the game update. I tried 1.00, 1.10, and 1.19~
- ~Changing the game version. I tried BCES01670 and BCES01175~
- ~With/without all patches~
- ~Multiple configuration settings. OpenGL/Vulkan, with/without Network activated, PPU and SPU Interpretter/LLVM~
- ~Matching the configuration found here https://forums.rpcs3.net/thread-196239.html~

**Comment by superepic32** [comment]
Did you ever figure this out? It’s happening to me again now that I’m on an entirely new pc. My old build was working since #8337. I even tried that PR on my new pc and it still doesn’t work. Maybe it’s an issue with settings or dlc content?

**Comment by jeremybris** [comment]
@superepic32 No! But that is good news. If it works on your old pc but not your new pc, and you copied your RPCS3 folder, then it is a hardware issue! If that is true, can you post your specs of your two computers, because that will bring us closer to identifying the issue.

**Comment by superepic32** [comment]
No, I didn’t copy my folder over. I don’t think it’s with hardware. It may be something to do with either DLC or some obscure occurrence within the game itself.

**Comment by jeremybris** [comment]
If you copy your RPCS3 folder to your "new" computer, with a USB drive or something, we can know for sure if it is the "DLC", because the files will be identical. It would not be an "some obscure occurrence", if it happens every time. Let me know if you figure it out!

**Comment by superepic32** [comment]
I don’t have the old folder anymore, unfortunately.

**Comment by jeremybris** [comment]
I see. If you get it to work again, and you figure out how, please let me know. Try to remember your old configuration and where you downloaded the files, and see if that works.

**Comment by superepic32** [comment]
I got them all from when ND released all U3 dlc for free. I remember my old config pretty 1:1 so I’m unsure of why this is happening.

**Comment by superepic32** [comment]
The error I'm getting as of master is this: {PPU[0x1000000] Thread (main_thread) [HLE:0x014537b0, LR:0x00945db8]} SYS: 'cellNetCtlGetInfo' failed with 0x80130108 : CELL_NET_CTL_ERROR_NOT_CONNECTED [3]
What error do you get?

**Comment by jeremybris** [comment]
The errors I get can vary. Here is the one I got most recently. The log at the bottom outputs "E {PPU[0x100000e] Thread (fios mediathread 9) [0x01741ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT"

[Errors.txt](https://github.com/RPCS3/rpcs3/files/5483442/Errors.txt)

Also, I am use this custom build, https://github.com/illusion0001/rpcs3/releases, not master.

**Comment by superepic32** [comment]
This is very strange then. That's an old error I'd get on my old pc before the pr I mentioned in my closed issue. I don't know what is causing the issue, and there isn't much help to pinpoint it, either.

**Comment by jeremybris** [comment]
Also, looking at your [old post](https://github.com/RPCS3/rpcs3/issues/8028#issuecomment-626362532), it looks like you had very similar specifications as me on your old computer,  and you got it to work on your old computer, I guess it is not a hardware problem. What's left? Could it be a driver problem? Do always keep your drivers up to date on Windows 10? I do.

**Comment by superepic32** [comment]
Yeah I keep drivers up to date. Only possible thing left is maybe something doing with the game itself. On what level? I don’t know. But it’s really annoying.

**Comment by superepic32** [comment]
Hey, it’s now working for me on latest master (:

**Comment by jeremybris** [comment]
Still does not work for me. The fact that it works and does not work randomly, for you, must mean something. I think you have a "workaround" that only works some of the time. Still, identifying the workaround, may make the bug clearer.

**Comment by superepic32** [comment]
I didn’t alter any settings or change anything within the game, or it’s files. I just booted it up like 30 mins ago, went into LAN, loaded a match up and it just works. Although, I will note something peculiar: The game reset all of my loadouts and legacy, but not the skins or taunt. Very weird.

**Comment by Darkhost1999** [comment]
Can we get a retest after RPCN 0.5

**Comment by jeremybris** [comment]
Still happens :(
![Screenshot 2021-12-04 181524](https://user-images.githubusercontent.com/11889359/144727689-2e350ed6-fbcc-4f99-b767-f6f1c20bc5a6.png)
[RPCN Log.log](https://github.com/RPCS3/rpcs3/files/7654909/RPCN.Log.log)
[Disconnected.log](https://github.com/RPCS3/rpcs3/files/7654910/Disconnected.log)

**Comment by RipleyTom** [comment]
·E 0:00:18.922001 {TID: 2412} rpcn: Login error: invalid username!

Please at least try to have a valid account to test RPCN...

**Comment by jeremybris** [comment]
How about now?

- [RPCN Offline Split-Screen log.log](https://github.com/RPCS3/rpcs3/files/7655073/RPCN.Offline.Split-Screen.log.log)
- [RPCN LAN log.log](https://github.com/RPCS3/rpcs3/files/7655072/RPCN.LAN.log.log)

If I recall correctly, on the PS3, this is an offline mode that you could play _without_ a PSN account, so I am dubious this error has to do with RPCN.

Also, I'm not sure if this is related, but everytime I play this game, it crashes after a couple of minutes. Here is the log for the crash:

- [Crash 1.log](https://github.com/RPCS3/rpcs3/files/7655074/Crash.1.log)
- [Crash 2.zip](https://github.com/RPCS3/rpcs3/files/7655080/Crash.2.zip)

**Comment by FlexBy420** [comment]
I believe this issue could be closed, just recently i got into splitscreen coop mode. Works both on 1.00 and 1.19
![image](https://user-images.githubusercontent.com/68403300/151051980-69887549-68c8-437a-b9a4-aa644c42ff8f.png)
![image](https://user-images.githubusercontent.com/68403300/151051990-4d63f751-42ed-4cba-870a-dc7823f9814b.png)
![image](https://user-images.githubusercontent.com/68403300/151053442-3bc749a9-48e7-4af7-9189-1ee77d3d103b.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7936883/RPCS3.log.gz)

**Comment by jeremybris** [comment]
I still can not go in-game. This bug randomly occurs, for some people, as you can read from the chat above, but always for me. No matter what I change. The only thing I have not tried is changing hardware. It's something on my end. 

Did this bug happen to you before? If so, what changed for it to be fixed?

![Screenshot 2022-01-25 220523](https://user-images.githubusercontent.com/11889359/151097820-83fa3f7f-e787-4c15-88b6-0936bbd194ea.jpg)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7938668/RPCS3.log)

**Comment by RainbowCookie32** [comment]
According to your log, both Network and PSN status are set to Disconnected. Did you try changing them to Connected and Simulated/RPCN respectively?

**Comment by jeremybris** [comment]
Yes, I can upload that log now.

Simulated (Offline Split-Screen): [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7938728/RPCS3.log) 
RPCN (Offline Split-Screen): [RPCS3 2.log](https://github.com/RPCS3/rpcs3/files/7938734/RPCS3.2.log)

**Comment by afroninjaen** [comment]
![image](https://user-images.githubusercontent.com/43121159/167931839-a4876c9d-3052-458a-a8e3-205bebe66b2d.png)

So im not sure if its the same issue or if its even still relevant lol. But I had issues with crashing when going into LAN. But after downloading an old version of RPCS3 (Specifically [#11738] or anything before [#11740], from https://rpcs3.net/compatibility?b&p=4 it seems to be working now.

**Comment by jeremybris** [comment]
> So im not sure if its the same issue or if its even still relevant lol. But I had issues with crashing when going into LAN. But after downloading an old version of RPCS3 (Specifically [#11738] or anything before [#11740], from https://rpcs3.net/compatibility?b&p=4 it seems to be working now.

It sounds like you are talking about #11960 . They may be related. Maybe the bug in the emulator here was exposed for everyone. Thanks for the update :) .

**Comment by Bommel24** [comment]
This problem still persists for me in the latest version (14057) with BCES01175 [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9354163/RPCS3.log). I even tried older rpcs3 versions mentioned above which didn't work either (but i remember there was a version where it worked previously).

**Comment by jeremybris** [comment]
> This problem still persists for me in the latest version (14057) with BCES01175 [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9354163/RPCS3.log). I even tried older rpcs3 versions mentioned above which didn't work either (but i remember there was a version where it worked previously).

Same here. I can't re-open this issue, because someone else closed it. 

If you find the build that works for you, let me know. It may help identify the problem.

**Comment by RipleyTom** [comment]
Set internet to Disconnected and PSN to Disconnected.

**Comment by Bommel24** [comment]
Tried everything disconnected too. Doesn't make a difference.

**Comment by RipleyTom** [comment]
Post a log with Internet set to Disconnected and PSN set to Disconnected.

**Comment by Bommel24** [comment]
Here is the log from NPEA00422 (which is the PSN Version patch enabled to unlock LAN Mode from the DISC Version). I uninstalled the disc version yesterday to try that one. Same thing happens. [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9358360/RPCS3.log)

**Comment by Darkhost1999** [comment]
Works on my machine. Here is without patches connected and RPCN. I don't know why anyone would want to play unpatched but issues with patches applied are invalid.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9358324/RPCS3.log.gz)
https://youtu.be/UXvgvS8d9pE
Disconnected and disconnected also working BCUS98233 v1.19
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9358426/RPCS3.log.gz)
All the patch does for me is prevent freezing when setting up my character or during a match.
Other patches fix graphical issues and they're all working. I'd have more photos and videos but GitHub has a 10MB limit at time of writing

**Comment by Bommel24** [comment]
If you use the PSN Version you have to patch it to Unlock LAN and offline modes. As far as I understand the game does a TITLE_ID check on the main menu to not show these options on the PSN Version.
There are a lot of videos of people playing it even through XLink Kai etc... 
But I've also met other people on uncharted discords who have the same problem as me and jeremybris so it must have to do something with hardware (network adapter, cpu etc) or software (windows 11? network drivers?) as i got it working some time before too.

**Comment by Darkhost1999** [comment]
My information provided isn't to disprove your information but mostly just to provide comparative information to aid in finding the difference between a working version and a not working version. Just gotta relax and see what happens. I don't envy network troubleshooting.

**Comment by jeremybris** [comment]
I have had this issue on 3 different computers, different versions of the game (BCUS, BCES, NPUB, 1.19, 1.0), default settings, [rpcs3 settings](https://wiki.rpcs3.net/index.php?title=Uncharted_3:_Drake%27s_Deception), save game, no save game, RPCN, no RPCN. Here is my log too. Hopefully, it can be compared with Darkhost's too. Thanks Darkhost. 

[RPCS3 Uncharted 3 Co-Op not Working Log.log](https://github.com/RPCS3/rpcs3/files/9359436/RPCS3.Uncharted.3.Co-Op.not.Working.Log.log)

Maybe it is related to an unimplemented function, like #8000 ? I don't know...

**Comment by Bommel24** [comment]
I can now get it working on a different computer too (which only has Intel Iris Integrated Graphics and so doesn't run it at full speed).
Fully disconnected default settings.

**Comment by sonikku** [comment]
Has anyone solved this problem yet? I'm having the same problem.

**Comment by ANTIBigBoss** [comment]
Yeah it's weird seems inconsistent when it works and when it doesn't work. I'm going to try a few things and see if I can find a definitive fix to this.

**Comment by sonikku** [comment]
I've managed to get it working. Do you have Logitech GHub? Close it and then try hosting. It worked for me even though I don't know why. Shout out to KASBER for the discovery.

**Comment by ANTIBigBoss** [comment]
Well I'm be damned it's working now lol nice find KASBER! Not in a million years would I have thought that would have been the issue.

**Comment by jeremybris** [comment]
I think it worked... Thank you for posting that!

**Comment by FlexBy420** [comment]
Interesting, i can use lan/split-screen just fine with logitech ghub running lol

**Comment by jeremybris** [comment]
> Interesting, i can use lan/split-screen just fine with logitech ghub running lol

It may be unrelated. I just got a new computer a new computer, and now it's working. I changed the motherboard, the cpu, the ram, t

**Comment by LSL1337** [comment]
For me it was also the Logi G Hub, which was causing the problem. pretty crazy idea, and it actually works. thank you!

**Comment by KASBER5511** [comment]
> Well I'm be damned it's working now lol nice find KASBER! Not in a million years would I have thought that would have been the issue.

I’m glad that it worked for you guys enjoy playing

**Comment by KASBER5511** [comment]
> I've managed to get it working. Do you have Logitech GHub? Close it and then try hosting. It worked for me even though I don't know why. Shout out to KASBER for the discovery.

First of all thanks for giving me credit for the solution!
I’m glad it helped you out.

You know it took for me 2 weeks to figure this out its so ridiculous how a program like this can give you an error on a 14 years old game on an emulator wow 😂

**Comment by thepronightly** [comment]
IT IS INSANE. CLOSING G HUB WORKS FOR ME ASWELL. Thanks mates!!
