### ISSUE TITLE
[NPUB31117] Dragon's Dogma: Dark Arisen - Wrong shadows

### ISSUE THREAD

**Issue by Andryshik345** [RPCS3/rpcs3#8420]
Wrong shadows behavior and only from a lantern light(looks like dynamic light sources issue). Tested on 0.0.10-10489 and Vulkan.

<details>
<summary>RPCS3</summary>

![изображение](https://user-images.githubusercontent.com/24612088/84541832-968b9200-ad11-11ea-9bda-0fa6ff76a51d.png)
![изображение](https://user-images.githubusercontent.com/24612088/84542612-40b7e980-ad13-11ea-8ab7-22fd30c99511.png)

</details>
<details>
<summary>PS3(sry for low quality from YT and not exact place)</summary>

![изображение](https://user-images.githubusercontent.com/24612088/84542112-33e6c600-ad12-11ea-938d-932d06a80c2d.png)
</details>

Logs and captures:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4773006/RPCS3.log.gz)
[RenderDoc](https://drive.google.com/file/d/1EfJNzj9ndbEat-dRcWoQ0bu0RDGAK4Bt/view?usp=sharing)

Specs:
AMD Ryzen 5 1600 3.4 GHz, GTX 750 Ti 2 GB, 16 GB RAM

**Comment by Asinin3** [comment]
Still an issue?

**Comment by Andryshik345** [comment]
@Asinin3 yes
![image](https://user-images.githubusercontent.com/24612088/97777890-f685b680-1b94-11eb-99fc-6e771695e53c.png)

**Comment by digitaldude555** [comment]
@Andryshik345 how about now?

**Comment by Andryshik345** [comment]
@digitaldude555 ¯\_(ツ)_/¯
![изображение](https://user-images.githubusercontent.com/24612088/107150260-c7929400-697e-11eb-80cb-9721fc90e1b0.png)

**Comment by Andryshik345** [comment]
still appears on v0.0.17-12687

![unknown](https://user-images.githubusercontent.com/24612088/131260299-4fa2beba-c118-4f0f-9b24-d22fd62023be.png)

[RenderDoc](https://disk.yandex.ru/d/Zwd1d8PyzIfXCw)

**Comment by Realmantik** [comment]
I think this issue is the same as #10458
