### ISSUE TITLE
Games Freeze

### ISSUE THREAD

**Issue by PNW-Redneck** [RPCS3/rpcs3#8423]
alright so i have a g3 3590 with i5 9300H, 1660ti, and 16GB.
after x amount of time playing it freezes. game audio persists just fine but my screen locks up and game is unplayable. i have tweaked with settings and sometimes itl play for a while till it locks up or only a few mins. i am running the latest Nvidia drivers as of writing this (446.14) i noticed in the console it shows memory allocation underflow as the last known error. not sure where to go, or how to fix this.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
