### ISSUE TITLE
[Feature request/Idea] PSP-style game quitting?

### ISSUE THREAD

**Issue by Blackbird88** [RPCS3/rpcs3#8425]
Since Guide button right now doesn't seem to do anything (to my knowledge). It would be nice if it could be used for exiting the game like PSP does
![image](https://user-images.githubusercontent.com/4414625/84565474-b2228700-ad69-11ea-9d55-be8dfa72dc0e.png)

Same thing could be mimicked with RPCS3's native UI and it'd nicely tie in with **Exit RPCS3 when process finishes** to make it more friendly to frontends.

**Comment by Megamouse** [comment]
duplicate of #5444
