### ISSUE TITLE
VM: Access violation reading location 0x42030000 (unmapped memory)

### ISSUE THREAD

**Issue by ProbeG17** [RPCS3/rpcs3#8428]
Hello, the emulator has stopped working since version 10. It always returns this type of error :
E {SPU[0x2000100] Thread (MGS4_MAINCellSpursKernel2) [0x0b9f4]} VM: Access violation reading location 0x42030000 (unmapped memory)
![84264871-400c3100-ab22-11ea-8db1-5aaae62f2723](https://user-images.githubusercontent.com/34166525/84577448-d2cbfa80-adc4-11ea-88c5-78ea9b2bf64d.jpg)

Please tell me how to fix it.
My system:
1070 gtx 8 gb, 16gb ram ddr4 3000, i5 6600k, ssd.

**Comment by Clarke2131** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4775424/RPCS3.log.gz)
i have the same error in gran turismo 5
ryzen 5 1600, 24GB ram and rx 570 latest driver 25.0.1

**Comment by ProbeG17** [comment]
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4775424/RPCS3.log.gz)
> i have the same error in gran turismo 5
> ryzen 5 1600, 24GB ram and rx 570 latest driver 25.0.1

Hi, could you fix this error? Everything used to work fine before, but after upgrading to version 10 it no longer works. I think I already tried everything) Someone wrote that the problem is with the log file.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
