### ISSUE TITLE
Gran turismo 5 crash at boot

### ISSUE THREAD

**Issue by Clarke2131** [RPCS3/rpcs3#8437]
gt5 can't boot anymore with the latest amd driver. although  i've downgraded the driver from 20.5.1 to 20.3.1 (that suppose to work) and nothing happened 

E {PPU[0x1000024] Thread (gFKsE) [0x00860530]} SYS: '_sys_timer_start' failed with 0x8001000a : CELL_EBUSY [2]
F {PPU[0x1000000] Thread (main_thread) [0x004961b8]} VM: Access violation reading location 0x0 (unmapped memory)

![RPCS3 0 0 10-10501-54308920 Alpha 14_06_2020 01_27_23 PM](https://user-images.githubusercontent.com/24876699/84598691-efa71300-ae42-11ea-8e93-506eae030352.png)
![RPCS3 0 0 10-10501-54308920 Alpha 14_06_2020 01_27_24 PM](https://user-images.githubusercontent.com/24876699/84598695-f6ce2100-ae42-11ea-8186-8dac9f635d79.png)
![RPCS3 0 0 10-10501-54308920 Alpha 14_06_2020 01_27_31 PM](https://user-images.githubusercontent.com/24876699/84598698-f9c91180-ae42-11ea-8323-f5355ff6235e.png)
![FPS_ 59 97 _ Vulkan _ 0 0 10-10501 _ Gran Turismo 5  BCES00569  14_06_2020 01_23_40 PM](https://user-images.githubusercontent.com/24876699/84598699-fc2b6b80-ae42-11ea-8283-4ee3ad5e7946.png)
[amd 20.5.1 RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4776837/amd.20.5.1.RPCS3.log.gz)
[amd 20.3.1 RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4776838/amd.20.3.1.RPCS3.log.gz)

**Comment by kd-11** [comment]
Likely unrelated to graphics, game still boots fine for me and others on AMD (see https://github.com/RPCS3/rpcs3/issues/8436) and the crash shown isn't coming from graphics threads. Likely a configuration issue.

**Comment by Clarke2131** [comment]
ok i'll try to reset all the settings to see if it works

**Comment by Clarke2131** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4776908/RPCS3.log.gz)
nothing really changed

**Comment by AniLeo** [comment]
If you says it happens regardless of driver then it's not related to the driver

**Comment by Clarke2131** [comment]
hmm, i thought this was related to "AMD Vulkan driver crash #8159"

**Comment by AniLeo** [comment]
It could be a driver bug, but it's not an issue on a specific driver version, so indicating an older driver version that works on title is a bit misleading
