### ISSUE TITLE
Mass Effect Blotch (Nvidia)

### ISSUE THREAD

**Issue by jeremybris** [RPCS3/rpcs3#8440]
## Quick summary
There is a blotch where there should not be a blotch. ~I combined bug reports because they act similarly, and I think they are the same bug.~

## Details
| Game | No Blotch & RSX Capture | Blotch & RSX Capture | Video of the Bug & Log | 
| ------------- | ------------- | ------------- | ------------- | 
| Mass Effect | ![Capture6589](https://user-images.githubusercontent.com/11889359/84609177-e5f1cf80-ae83-11ea-9af4-28828ace272f.PNG) | Camera angle moved ![Capture91](https://user-images.githubusercontent.com/11889359/84609184-ed18dd80-ae83-11ea-85d5-8d92c55db84f.PNG) [RSX Capture](https://drive.google.com/file/d/13ojqHmKl0GmpOHIi_10Mo-Wz6oQcbv1x/view?usp=sharing) | [Video of the Bug](https://www.youtube.com/watch?v=MXnavWjRdHg) & [RPCS3.log](https://github.com/RPCS3/rpcs3/files/4777556/RPCS3.log) | 
| Warhawk | **Not Moving** the Player ![Capture99](https://user-images.githubusercontent.com/11889359/84609223-18033180-ae84-11ea-8001-a4dd02b43973.PNG) [RSX Capture](https://drive.google.com/file/d/1q8FVEna5zgZhGjSY3t_pZEIT8D8dLRgF/view?usp=sharing) | **Moving** the Player ![Capture88](https://user-images.githubusercontent.com/11889359/84609230-218c9980-ae84-11ea-91d8-2e6c76d78232.PNG) [RSX Capture](https://drive.google.com/file/d/15uWTMWbHuZDtQEeTFnNaNO76bzIB8Qyv/view?usp=sharing) | [Video of the Bug](https://www.youtube.com/watch?v=HCVByvTV1Es) & [RPCS3 2.log](https://github.com/RPCS3/rpcs3/files/4777558/RPCS3.2.log) | 

- ~**This happens if I look at the blotch in Mass Effect**~ FIXED

- **Mass Effect on the PS3 and RPCS3**

| PS3 | RPCS3 | 
| ------------- | ------------- | 
| ![Capture6462](https://user-images.githubusercontent.com/11889359/84609392-d32bca80-ae84-11ea-97b8-1d39bfc41e6b.PNG) | ![Capture5353](https://user-images.githubusercontent.com/11889359/84609403-df178c80-ae84-11ea-9af1-cc0c057514e2.PNG) | 
| ![Capture3](https://user-images.githubusercontent.com/11889359/84609416-eb9be500-ae84-11ea-877e-464f706e4567.PNG) | ![Capture5](https://user-images.githubusercontent.com/11889359/84609427-f3f42000-ae84-11ea-85df-30645a95fa07.PNG) | 

- I have Windows 10 latest version, Ryzen 9 CPU, RTX GPU
- ~I saw this in Sly Thieves in Time, on flames, in the Feudal Japan world, but now I can not find it anymore.~
- ~Seems to have something to do with light sources. In Mass Effect, it surrounds lights, in Warhawk, it surrounds the sky, and in Sly Thieves in Time, it surrounded flames.~
- ~If you compare the Mass Effect images side by side (with the PS3), you will see a glow around the lights that is missing.~

**Comment by Basmurd** [comment]
Allmost same bug #8508

**Comment by Andryshik345** [comment]
Can confirm that color bursts(as OP's when he look at the blotch) are gone
![изображение](https://user-images.githubusercontent.com/24612088/94643904-4f95cc80-0301-11eb-9753-24b97445616e.png)

**Comment by lextra2** [comment]
Still no fix for this? Probably the only issue which stops it from being "playable".

**Comment by Darkhost1999** [comment]
Can those effected by this issue state which gpu, cpu they have?
Ryzen 9 and RTX cards are very vague and not the most helpful.
No one else has provided any additional information for their hardware.
Last message I see for trying to figure this out is "May be caused by CPU or GPU. Will have to check to make sure"
So it just may help to add some hardware information to the pile.

**Comment by jeremybris** [comment]
As far as I know, this issue is ubiquitous. So, I intentionally left my specs vague. (If you find a video on YouTube without this bug, you can disprove me). Here anyway: 
- RTX 2080 Super 
- Ryzen 9 3900x

**Comment by lextra2** [comment]
- AMD Radeon RX 5700
- AMD Ryzen 9 3900x

**Comment by ScottieD** [comment]
I've found that for WarHawk, enabling the Read Color Buffers setting in the advanced tab fixes the issue of black artifacts. It however does introduce the issue of clouds moving around erratically.

**Comment by ScottieD** [comment]
This bug is still ongoing after #11518 

One thing I noticed that has changed recently, but not in #11518 is that if you enable ATS and Write Color Buffers the clouds will have a checkerboard like appearance instead of a fixed sprite like appearance. ATS also makes the Island Outpost map completely broken, also not new from  #11518. I'd consider making a bug report for that, but that setting isn't really needed in this game.

**Comment by ScottieD** [comment]
After #11665 clouds no longer render with Anti-aliasing on. This removes the black blotches and weird erratic cloud glitches by causing the clouds to not render at all. I am not sure if this is a win or not. It certainly makes the game playable in flight modes.

**Comment by jeremybris** [comment]
Good catch. Warhawk is fixed for me now, with "Read Color Buffers". The two issues are not related, as I thought. I'm going to change the title and keep open until Mass Effect is fixed.

**Comment by Andryshik345** [comment]
![изображение](https://user-images.githubusercontent.com/24612088/167283564-9b87e045-9bf0-4786-b59d-03365f63cc48.png)
Black blotches are disappeared, but now it has a new glitch with colorful squares, idk if it's still related. Tried to fix, but none of the render settings are helped

**Comment by illusion0001** [comment]
Send captures

**Comment by Andryshik345** [comment]
Here you go: https://drive.google.com/file/d/1QPWXjv0PS3LLPTkLUA18NO2ODsoWgbxz/view?usp=sharing
I put both files in one archive

**Comment by jeremybris** [comment]
Fixed, for me, now, but you have to clear and rebuild all caches for the game. Closing, lest anyone protests.

![Screenshot 2022-05-08 133650](https://user-images.githubusercontent.com/11889359/167308437-ed3952e4-5d2d-44bc-8067-b42ca9608c59.png)

**Comment by Andryshik345** [comment]
@jeremybris nope, still the same on latest build. Just restored to default settings and completely cleared all the caches.
![изображение](https://user-images.githubusercontent.com/24612088/167309059-813127a0-160f-4db4-9ab1-307462c23f2e.png)

HW: R5 1600 3.4 GHz, GTX 750 Ti 2 GB

**Comment by jeremybris** [comment]
> @jeremybris nope, still the same on latest build. Just restored to default settings and completely cleared all the caches. 

I'm guessing it may be because you are on Linux or Mac (from the look of your window)...? The PR that fixed this issue for me is probably the same one that changed the issue for you. I don't want to track that PR (because rebuilding caches is time consuming), but I can help you on how to find the build that changed it. It's here: https://rpcs3.net/compatibility?b , v0.0.22-13563 or older.

**Comment by Andryshik345** [comment]
> I'm guessing it may be because you are on Linux or Mac (from the look of your window)...?

No, it's windows 10 with custom theme :)

**Comment by jeremybris** [comment]
#11916 , v. 0.0.22-13539 , fixed it for me. I have Windows 11, 3900x, 6900 xt .

**Comment by lextra2** [comment]
Tested on 0.0.22-13555
Fixed for me
W10, Ryzen 3900X, Radeon RX 5700 (22.4.2 Driver)

**Comment by Satan86** [comment]
Not fixed for me on a GTX 1050 Ti driver 511.79 and Windows 11

**Comment by marcoluc97** [comment]
@kd-11 maybe only Nvidia?

**Comment by Silanda** [comment]
Having this problem too. 

Ryzen 7 3700x, RTX 3070 Driver 516.59

Problem impacts both Vulkan and OpenGL backends. Using shader interpreter only solves the blotches problem but it doesn't render correctly (it looks like it's missing lighting or effects).

Link to Renderdoc capture of the title screen: https://mega.nz/file/dTQEUKBI#sPXtGlUSrEa5_MBKcI8UYz-hHOYCvZwLa2f-QCEEb-c

I've attached an RSX capture that I've made too, but for whatever reason I can't seem to open it myself. 

[BLES01774_20220711185718_capture.zip](https://github.com/RPCS3/rpcs3/files/9086474/BLES01774_20220711185718_capture.zip)

**Comment by ustrucx** [comment]
i7-8700K - GTX 1070
i7-11700K - RTX 3090
Win 10 & RPCS3 0.0.24-1421-92b08a4f Alpha | master on both.

Same rainbow blocks as the colleagues above. Has anyone found a setting to tweak that can help make Mass Effect playable? Mass Effect 2 seem to work great! Do Radeon generally work better with PS3 emulation? I have an RX540 but it doesn't feel like it would run PS3 games, would it?

**Comment by kd-11** [comment]
This is NVIDIA-only. I verified on my 6700XT and 1050Ti.

**Comment by kd-11** [comment]
This is a tough one. But I know how to fix it once and for all. If I fix it quickly, it will break other games on NVIDIA that need the low precision workaround. I'll make this one a high priority as it affects all games on NVIDIA.

**Comment by Triticum0** [comment]
Someone on the forums got the bug again. For reference there using a 1070.
https://forums.rpcs3.net/showthread.php?tid=196756&pid=325118#pid325118

**Comment by jamespilcher** [comment]
Hey, still experiencing the blotches on Mass Effect. Are there settings I should change for the fix?


Ryzen 5 3600
GTX 1060 6GB
RPCS3 0.0.37
