### ISSUE TITLE
[Feature Request] Backup save data before saving

### ISSUE THREAD

**Issue by gidan80** [RPCS3/rpcs3#8446]
Sometimes the emulator crashes right while saving data, corrupting it.
It could be a nice feature to backup the save folder of the game just before writing on it.
Then, if the user notices that his saves are lost, he can restore the saves from the backup folder (or by some button on the GUI).

**Comment by sampletext32** [comment]
Isn't this already present. While running games I can see save-file and backup files nearby.
Here is some log (truncated) from TLOU for example.
```
SYS: 'sys_fs_open' failed : CELL_ENOENT, “/dev_hdd0/game/BCES01585DATA2/USRDIR/users/VXNlcg==/autosave/10.save” [1]
SYS: 'sys_fs_open' failed : CELL_ENOENT, “/dev_hdd0/game/BCES01585DATA2/USRDIR/users/VXNlcg==/autosave/10.save-backup” [1]
SYS: 'sys_fs_open' failed : CELL_ENOENT, “/dev_hdd0/game/BCES01585DATA2/USRDIR/users/VXNlcg==/autosave/0.save” [1]
SYS: 'sys_fs_open' failed : CELL_ENOENT, “/dev_hdd0/game/BCES01585DATA2/USRDIR/users/VXNlcg==/autosave/0.save-backup” [1]
```

**Comment by lewa-j** [comment]
> Isn't this already present. While running games I can see save-file and backup files nearby.
> Here is some log (truncated) from TLOU for example.

I think it's feature of the game but not the emulator

**Comment by elad335** [comment]
Why? savedata writing is completely atomic, this shouldnt be an issue.

**Comment by gidan80** [comment]
When i wrote this issue i remember i was playing GT5 and it crashed/freezed while auto-saving after winning a cup. After restarting, my saves was corrupted. If, like you say, savedata writing is atomic, maybe GT5 could have generated corrupted savedata and then succesfully saved it.

**Comment by elad335** [comment]
So maybe rewrite the issue to be about this..

**Comment by Nekotekina** [comment]
Atomic savedata is only the game uses "standard" way to write it, but not alll do, unfortunately... What then, make the whole FS changes atomic? I'm honestly confused what to do

**Comment by Megamouse** [comment]
I think the best thing to do here would probably be to have some sort of backup folder that will always have maybe the 3 last states of the game's savedata folder.

**Comment by kd-11** [comment]
Pretty sure this is already implemented using fs::pending_file
