### ISSUE TITLE
The Last Of Us - graphic errors and flickering black squares

### ISSUE THREAD

**Issue by Squall1Titus** [RPCS3/rpcs3#8453]
## Quick summary
Game (BCES01584 v 1.11) starts and is Playable but with major graphical issues

## Hardware
AMD Ryzen 5 3600, 16GB DDR4, AMD Radeon RX 5700 XT

## Config
![image](https://user-images.githubusercontent.com/60219187/84868060-65e28a00-b07c-11ea-9324-fc3da64734d6.png)
![image](https://user-images.githubusercontent.com/60219187/84868082-7135b580-b07c-11ea-8d31-93dc25782c49.png)
![image](https://user-images.githubusercontent.com/60219187/84868108-7a268700-b07c-11ea-920d-6be92beca961.png)
![image](https://user-images.githubusercontent.com/60219187/84868140-84488580-b07c-11ea-930c-f04828464830.png)
![image](https://user-images.githubusercontent.com/60219187/84868169-90ccde00-b07c-11ea-909d-f382cb69bcaf.png)

I also tried to disable "Write Color Buffers" and "Force CPU blit emulation" but no change.
Installed latest patch.yml
SPU Cache has been rebuild 

## Detail

Massive graphical errors (flickering) and sound problems.

Startmenu
![image](https://user-images.githubusercontent.com/60219187/84868609-41d37880-b07d-11ea-9379-f5b3cd801cc9.png)

InGame
![image](https://user-images.githubusercontent.com/60219187/84869326-2cab1980-b07e-11ea-813e-49d0f62b2425.png)
![image](https://user-images.githubusercontent.com/60219187/84870144-32edc580-b07f-11ea-8fe1-6d549eae6463.png)

It should not be because of my computing power.

Best Regards 
Michael

**Comment by jokoputera** [comment]
this is not a place for support. please check Discord for help. please check rpcs3 faq.

**Comment by Squall1Titus** [comment]
But it's a rendering error, isn't it? If it doesn't look right even with the patches, something in the program must be changed.

**Comment by xddxd** [comment]
Why are you opening issues when using patches?

**Comment by Squall1Titus** [comment]
Because the patches allow the game to start. Without the game is even more unstable.

**Comment by AniLeo** [comment]
Patches and debug settings used, invalid issue

**Comment by illusion0001** [comment]
This is caused by a driver bug, use Linux with RADV or radeonsi instead.
