### ISSUE TITLE
GTA IV has broken graphics after #8438

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8456]
After PR #8438, GTA IV has broken graphics (mainly shadows, looks like DoF is broken as well since only black is rendered in the distance)

Screenshot and log from latest master:
![Screenshot_8](https://user-images.githubusercontent.com/1712979/84936871-97db0700-b0e3-11ea-88e2-b1458c35d997.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4794494/RPCS3.log.gz)
RSX Capture:
https://www.dropbox.com/s/hidin91k26ig8ys/NPEB00882_20200617212751_capture.rrc
Screenshot and log from last working build (v0.0.10-10506-717e851a):
![Screenshot_3](https://user-images.githubusercontent.com/1712979/84936964-c0630100-b0e3-11ea-8fae-91f8daec7916.png)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4794506/RPCS3.zip)

Specs:
Ryzen 7 2700
RX 580 20.5.1
Windows 10 2004

**Comment by kd-11** [comment]
Looks like a higher mip lod is being used.

**Comment by Drhycodan420** [comment]
It's not only the shadows and DoF, but the game now has lines all over the screen.  You can see the random lines behind niko's jacket as well as the ground and the green pole stands.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/8713 for Vulkan. OpenGL is also fixed but correct output is blocked by https://github.com/RPCS3/rpcs3/issues/8714.

**Comment by xddxd** [comment]
Yes, it's fixed on vulkan now.
