### ISSUE TITLE
Tekken Tag Tournament 2[BLJS10187] Graphic issues (FengWei)

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#8457]
When character **FengWei** is used, the image will be disorder
version: v0.0.10-10520 (But I tried the previous version (such as v0.0.10-10088), and still had the same error )

![未标题-1](https://user-images.githubusercontent.com/47111657/84985027-97d41900-b16e-11ea-811a-12f0bf162163.jpg)

![未标题-2](https://user-images.githubusercontent.com/47111657/84985034-9a367300-b16e-11ea-82ff-3a91b8a714dd.jpg)

**Comment by MarioSonic2987** [comment]
Enable Accurate xfloat to fix that bug.

**Comment by arcadee1977** [comment]
> Enable Accurate xfloat to fix that bug.

OK. thanks
