### ISSUE TITLE
VSH.[S]ELF Error

### ISSUE THREAD

**Issue by n00b7** [RPCS3/rpcs3#8461]
LOG: 
RPCS3 v0.0.10-10523-24968670 Alpha | HEAD | Firmware version: 4.86
Intel(R) Core(TM)2 Quad CPU Q6600 @ 2.40GHz | 4 Threads | 8.00 GiB RAM | TSC: Bad
E cellAudio: Audio backend Null does not support buffering, this option will be ignored.
S GUI: Boot successful.
E {PPU[0x1000000] Thread (main_thread) [0x0060be4c]} SYS: '_sys_process_get_paramsfo' failed with 0x80010006 : CELL_ENOENT [1]
U {PPU[0x1000000] Thread (main_thread) [0x006178d4]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x00617910]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641d14)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641d84)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641da0)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641dd8)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641df4)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641e10)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641e2c)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641e48)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641e64)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641e80)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641e9c)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641fd0)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641fec)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641fb4)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641f98)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641f7c)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641eb8)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641ed4)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641ef0)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641f0c)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641f28)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641f44)
U {PPU[0x1000000] Thread (main_thread) [0x00617490]} sys_prx TODO: _sys_prx_register_library(library=*0x641f60)
U {PPU[0x1000000] Thread (main_thread) [0x000c85d0]} sys_sm TODO: sys_sm_get_params(a=*0x70f000, b=*0xd0010230, c=*0xd0010238, d=*0xd0010190)
U {PPU[0x1000000] Thread (main_thread) [0x000c85d0]} sys_sm TODO: sys_sm_get_params(a=*0xd00100f0, b=*0xd00100f8, c=*0xd0010100, d=*0xd0010108) x3
S {PPU[0x1000000] Thread (main_thread) [0x00618944]} sys_prx: Loaded module: “/dev_flash/sys/internal/libfs_utility2.sprx” (id=0x2300d100)
F {PPU[0x1000000] Thread (main_thread) [0x39800000]} VM: Access violation reading location 0x39800000 (unmapped memory) x2

DEBUG:
r0 : 0x39800000
r1 : 0xd000f990 -> 00 00 00 00 d0 01 01 a0 
r2 : 0x658c006d
r3 : 0x20070000 -> 00 00 00 00 00 00 00 00 
r4 : 0x100000   -> function-code
r5 : 0xd000f780 -> 00 00 00 00 00 00 00 28 
r6 : 0x0       
r7 : 0xd000f870 -> 00 00 00 00 30 04 3a e0 
r8 : 0x747fc0   -> ff ff ff ff 00 00 00 00 
r9 : 0x100000000000000
r10: 0x1000000 
r11: 0x0       
r12: 0x6378c0   -> function-code
r13: 0x20007060 -> 00 00 00 00 00 00 00 00 
r14: 0x0       
r15: 0x0       
r16: 0x0       
r17: 0x0       
r18: 0x0       
r19: 0x0       
r20: 0x0       
r21: 0x0       
r22: 0x0       
r23: 0x0       
r24: 0x0       
r25: 0x0       
r26: 0x980010   -> 00 00 00 00 00 00 00 00 
r27: 0x980004   -> 00 00 00 00 00 00 00 00 
r28: 0x30043ae0 -> "/dev0;0sh/sys/inter"
r29: 0x30043ae0 -> "/dev0;0sh/sys/inter"
r30: 0x1       
r31: 0x1       
f0 : 0
f1 : 1
f2 : -2
f3 : 1
f4 : 1
f5 : -3
f6 : 3
f7 : -2
f8 : -1
f9 : 0
f10: 0
f11: 1
f12: 0
f13: 1
f14: 0
f15: 0
f16: 0
f17: 0
f18: 0
f19: 0
f20: 0
f21: 0
f22: 0
f23: 0
f24: 0
f25: 0
f26: 0
f27: 0
f28: 0
f29: 0
f30: 0
f31: 0
v0 : 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v1 : 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v2 : 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v3 : 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v4 : 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v5 : 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v6 : 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v7 : 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v8 : 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v9 : 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v10: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v11: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v12: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v13: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v14: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v15: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v16: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v17: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v18: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v19: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v20: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v21: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v22: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v23: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v24: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v25: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v26: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v27: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v28: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v29: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v30: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
v31: 0x00000000000000000000000000000000 [x: 0 y: 0 z: 0 w: 0]
CR: 0x28000042
LR: 0x6378e8
CTR: 0x39800000
VRSAVE: 0xffffffff
XER: [CA=0 | OV=0 | SO=0 | CNT=0]
VSCR: [SAT=0 | NJ=0]
FPSCR: [FL=0 | FG=1 | FE=0 | FU=0]
Reservation Addr: none
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Tried SPU and PPU on interpreter [precise], LLVM and ASMJIT which doesnt do anything, also tried changing video backend to null, opengl, vulkan. nothing seems to work

i also have FW Library selection set to manual, none selected

**Comment by RainbowCookie32** [comment]
VSH is not supported on master builds, invalid issue

**Comment by n00b7** [comment]
which branch/tag have the VSH Patches
