### ISSUE TITLE
Lollipop Chainsaw can't generate shader and crashes

### ISSUE THREAD

**Issue by randomgameguy** [RPCS3/rpcs3#8466]
Hey guys! Today, i was trying to play Lolipop Chainsaw, and everything was ok.... until the part where you kill two or more zombies in the same time. When the part ends, it goes into a white screen and it crashes. Seems to happen only in OpenGL and seems that it's a shader problem.

Here's my configuration:
- Windows 10
- Intel Core I3-8100
- Intel Graphics 630

Here's my log:

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4807168/RPCS3.zip)

**Comment by AniLeo** [comment]
Intel proprietary drivers are not supported, they're known to be broken
