### ISSUE TITLE
God of War Collection White Screen

### ISSUE THREAD

**Issue by kin-patsu** [RPCS3/rpcs3#8471]
## Quick summary
Launching the GoW collection in Italian freezes rpcs3

## Details
Trying to play the first GoW Collection in certain languages is impossible. Starting the collection is fine, you are greeted by the loading screens as expected. However, as soon as rpcs3 goes to load the game selection screen, a white screen is presented instead. I've tested the following languages: Italian, Spanish (result in white screen freeze); English UK, English US, French (give no issue)

#### 1. Please attach RPCS3's log.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4808329/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
Not a graphical issue I think?

#### 3. Please attach screenshots of your problem.
![immagine](https://user-images.githubusercontent.com/19828171/85208476-c0a00e00-b328-11ea-9e27-1428adf8574e.png)
Performance overlay won't appear once the issue starts

#### 4. Please provide comparison with real PS3.
I've ripped the disk myself from my CFW PS3. There, the issue will never present itself even if the system language is Italian

#### 5. Please provide your system configuration:
* OS: Windows 10 2004
* CPU: Intel(R) Core(TM) i7-3930K
* GPU: EVGA GeForce GTX 1070
* Driver version: 446.14
* Renderer: Vulkan

**Comment by Emogop** [comment]
Is this the screen you should see? Also it goes ingame just fine. Maybe a bad image?
![Screenshot_597](https://user-images.githubusercontent.com/42875723/85208858-45e0ee00-b33c-11ea-9978-5ba26f36dd79.png)

**Comment by RainbowCookie32** [comment]
The game logs `“fios read archive error, reading compressed block 27 in file '/data/I/gow_bonus1080.gtf' in archive '/bootloader.psarc': err = -2147416311` to TTY right before the Trap. Might be worth validating the dump, to make sure it doesn't have any bad files from the transfer.

**Comment by kin-patsu** [comment]
> 
> 
> Is this the screen you should see? Also it goes ingame just fine. Maybe a bad image?
> ![Screenshot_597](https://user-images.githubusercontent.com/42875723/85208858-45e0ee00-b33c-11ea-9978-5ba26f36dd79.png)

It's the screen before, where it promps you to select select between the first and second game. So far I've managed to ignore the error by booting straight into the game through the .self file



> 
> 
> The game logs `“fios read archive error, reading compressed block 27 in file '/data/I/gow_bonus1080.gtf' in archive '/bootloader.psarc': err = -2147416311` to TTY right before the Trap. Might be worth validating the dump, to make sure it doesn't have any bad files from the transfer.

Will definitely try to transfer again the faulty file, I still have the dumped BD on my PS3 so I can also check it there too if it works or not. About validating the dump, what's the best way to do that?

**Comment by RainbowCookie32** [comment]
Get the PS3-ISO-Rebuilder tool from [here](http://jonnysp.bplaced.net/), and the .ird for your game.
