### ISSUE TITLE
[Feature Request] in-game user selection

### ISSUE THREAD

**Issue by giuliano-oliveira** [RPCS3/rpcs3#8472]
## Details

A user selection dialog to select a user account for the current loaded game.

#### what part of RPCS3 would be affected by the feature:
* Gameplay

#### Why this feature is important to RPCS3.

Games like Scott Pilgrin,the LBP trilogy, and others in offline multiplayer requires the 2nd 3rd or 4th player to select a User to use so that it can load the desired characters levels, but, currently, no user dialog is shown in RPCS3, instead it loads a lvl 0 for all characters, apparently it loads a guest user account automatically.

Therefore, all players except player 1, can't save its progress along the gameplay.

#### screenshots:

in the PS3, the user selection dialog is shown as follow

![image](https://user-images.githubusercontent.com/13181797/85210227-14e8c500-b30c-11ea-8fc7-f7a092fc9ac6.png)

#### logs:
tested in SCOTT PILGRIM VS. THE WORLD: THE GAME [NPUB30162]

**full log file**
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/6350912/RPCS3.log.zip)

**log overview**

If I:
1. start the game
2. go to the "story mode" -> select any difficulty
3. in the 2nd player controller, i press X then click in "Select profile"
i get the following log info:
```
U cellUserInfo TODO: cellUserInfoSelectUser_SetList(setList=*0x216b1060, funcSelect=*0x10fffc8, container=0xffffffff, userdata=*0x216b0fe0)
U cellUserInfo TODO: cellUserInfoGetList(listNum=*0x216b10b4, listBuf=*0x216b1074, currentUserId=*0x216b1050)
E cellSaveData: cellSaveDataUserAutoLoad(version=0, userId=0, dirName=“NPUB30162”, errDialog=0, setBuf=*0x25f392d8, funcStat=*0x11045f8, funcFile=*0x1104690, container=0xffffffff, userdata=*0x25f39198)
E SYS: 'sys_ppu_thread_get_priority' failed with 0x80010005 : CELL_ESRCH [3]
```

#### system configuration:
* OS:Linux (5.9.16-1-MANJARO, Xfce 4.16)
* RPCS3 Version: 0.0.15-12138-efd38fa9 Alpha

**Comment by Ilovelbpcoopbutcantsaveplayertwoimsad** [comment]
Im having the same issue with lbp, can't save p2's data because of it

**Comment by Megamouse** [comment]
mssing log with the (not) appearing dialog

**Comment by giuliano-oliveira** [comment]
@Megamouse I only get info about my connected controller. is there some verbose option for RPCS3?

```
S HID: DualShock 4 Controllers found: 1
E sys_net: sys_net_bnet_select(): exceptfds not implemented x19087
```

**Comment by RainbowCookie32** [comment]
Should attach the log file too to make sure devs have access to all relevant info.

**Comment by giuliano-oliveira** [comment]
@RainbowCookie32 full log file included

**Comment by giuliano-oliveira** [comment]
Thank you guys, you guys rock !

**Comment by Megamouse** [comment]
@giuliano-oliveira I have one question.
What happens when you cancel the user selection in scott pilgrim on a real PS3 ?
Does it behave the same as in RPCS3 ?

**Comment by LoganRicardo** [comment]
How can I sign in player #2 to play AoT40th Day in split screen and save progress??
