### ISSUE TITLE
[Feature Request] Update using system proxy

### ISSUE THREAD

**Issue by kagurainroy** [RPCS3/rpcs3#8474]
Quick summary
Using system proxy when rpcs3 auto update, or add proxy settings.

1. Please describe, what part of RPCS3 would be affected by your feature:
Update.

2. Please tell us, why your feature is important to RPCS3.
Help people can't access github without proxy to auto update rpcs3.

Add on:
I have two network cards, a wired and a wireless, the wired card can't access some website by direct, must using proxy. 
I tried set system proxy to PAC or http, those both don't work in rpcs3, it check update successfully and insist 0% when updating. That didn't appear on cemu( it doesn't have proxy settings too). 
So I must disable my wired card in windows settings and re-enable it again after update done. And rpcs3 update is very frequently, so I wish you can add this feature to help update.

**Comment by clienthax** [comment]
It seems as a workaround you could try setting an environment var seen here https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

**Comment by kagurainroy** [comment]
> It seems as a workaround you could try setting an environment var seen here https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

Thx for ur help but sorry I can't understand this...
I am using windows 10 and for me update is just auto run when open rpcs3 or click help-check for updates. Does it using curl even I don't install it?
I know just download latest build from official website and replace the old files works too, but I still hope auto update = =

**Comment by clienthax** [comment]
It uses curl, you would need to lookup setting an environment variable for the proxy currently.

More info for devs: https://curl.haxx.se/docs/todo.html#auto_detect_proxy

**Comment by bevanweiss** [comment]
I wonder if we should possibly think about dropping cURL... we already have a large dependence on Qt, so the QtNetwork module might provide cURL functionality (plus proxy support) for not much additional burden (since we're already paying the cost of the QtCore.. I'm not sure what extra the QtNetwork adds though).
I also like the idea of it (QtNetwork) removing another separate 3rd party module, and the annoying CMake 'poorly supported' warning, and the cURL compiler warnings..

**Comment by clienthax** [comment]
> I wonder if we should possibly think about dropping cURL... we already have a large dependence on Qt, so the QtNetwork module might provide cURL functionality (plus proxy support) for not much additional burden (since we're already paying the cost of the QtCore.. I'm not sure what extra the QtNetwork adds though).
> I also like the idea of it (QtNetwork) removing another separate 3rd party module, and the annoying CMake 'poorly supported' warning, and the cURL compiler warnings..

We don't want any QT dependant code in the emulator module

**Comment by bevanweiss** [comment]
Do we actually use cURL within the emulator core?
This particular issue is around the Updater right, which I'm pretty sure is already in the Qt window environment, so QtNetwork shouldn't be an issue for that (unless for size/compatibility/etc reasons).
I expect (hope) that emulator core deals with raw sockets (and doesn't use cURL).
