### ISSUE TITLE
rpcs3 downloads as a 7z file instead of a zipped file

### ISSUE THREAD

**Issue by Pikachukiller27** [RPCS3/rpcs3#8477]
im trying to play skate 3 but the firmware installs as this instead of multiple files or zip
![image](https://user-images.githubusercontent.com/52088688/85263653-58365700-b424-11ea-843b-d8d7628c5f51.png)

**Comment by clienthax** [comment]
https://www.7-zip.org/

**Comment by sampletext32** [comment]
7Z are normally supported by any modern archive program. Install one and everything will be fine. This is not a RPCS3 problem. Can be closed as irrelevant.
