### ISSUE TITLE
KH 1.5 Remix f {ppu[0x1000000] thread (main_thread) [0x00165884]} vm: access violation reading location 0xc000000 (unmapped memory)

### ISSUE THREAD

**Issue by kaitoueresia** [RPCS3/rpcs3#8478]
The game keeps crashing with me. it happened almost 4~5 times.

I was playing KH 1.5 Remix completely normal the past 3~4 days but yesterday suddenly it crashed for the first time and then after that it kept crashing at various locations. i tried all the solutions on this link (  https://github.com/RPCS3/rpcs3/issues/8047  ) but nothing worked. please i need help.

i have win 10 
 i7-7700HQ CPU @ 2.80GHz
 GPU Nvidia GeForce GTX 1050 Ti

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4813632/RPCS3.log)

**Comment by nitroos-ai** [comment]
May be @elad335 comment could help in #9655.

**Comment by Darkhost1999** [comment]
I haven't been able to reproduce this crash. I've just been able to completely finish the entire game up until the final message not working where you can't get a progress report. But aside from that no issues at all that do not occur on PS3.

**Comment by nitroos-ai** [comment]
What about #4851 and  #6945?

**Comment by Darkhost1999** [comment]
#4851
Is valid
#6945
You can workaround by skipping the cutscenes and finish the game.

As for gameplay the game plays as a PS3 does just better performance.
