### ISSUE TITLE
GUI Glitches in Lubuntu Make RPCS3 very hard to use [sddm/lxqt]

### ISSUE THREAD

**Issue by n00b7** [RPCS3/rpcs3#8486]
The RPCS3 GUI is glitch and unusable on lubuntu [18.04(and probably 20.04)] RPCS3 VER: 0.10/rpcs3-v0.0.10-10549-628cb1c7_linux64.AppImage and looks like this:
![screen](https://user-images.githubusercontent.com/11874683/85432567-2373ee00-b551-11ea-8d95-3b7e9cb0e30d.jpg)
![screen2](https://user-images.githubusercontent.com/11874683/85432668-4a322480-b551-11ea-991f-ac848b05fc05.jpg)

**Comment by JohnHolmesII** [comment]
Unable to reproduce. Can you give any more information?

![2020-06-25-040130_4480x1440_scrot](https://user-images.githubusercontent.com/8901018/85652084-9323cf00-b65e-11ea-871a-dcbe11c85846.png)

**Comment by n00b7** [comment]
Qt 5.14  is installed this is probably the issue
