### ISSUE TITLE
Firmware Not Recognized if dev_flash is not in executable folder

### ISSUE THREAD

**Issue by billyea** [RPCS3/rpcs3#8490]
## Quick summary
When the dev_flash folder is in a separate directory from the RPCS3 executable, even if this directory is pointed to in the Virtual File System dialog and in config.yml, the firmware will not be recognized.

## Details

1. The config.yml is configured with the following values (the executable is in E:/Emulators/RPCS3):
  $(EmulatorDir): ""
  /dev_hdd0/: E:/Roms/PS3/dev_hdd0/
  /dev_hdd1/: E:/Roms/PS3/dev_hdd1/
  /dev_flash/: E:/Roms/PS3/dev_hdd1/dev_flash/
  /dev_usb000/: E:/Roms/PS3/dev_usb000/
See attachment: [config.zip](https://github.com/RPCS3/rpcs3/files/4822323/config.zip)
1. This is confirmed in the Manage > Virtual File System window.
![vfswindow_beforebootfailed](https://user-images.githubusercontent.com/4176375/85474081-2d621500-b582-11ea-8faf-e568b5c38679.png)
1. The firmware is installed using File > Install Firmware...
1. The firmware installs into E:/Roms/PS3/dev_hdd1/dev_flash/
1. Attempt to start game. Get Boot Failed error and firmware not installed.
![bootfailed](https://user-images.githubusercontent.com/4176375/85474264-68fcdf00-b582-11ea-9689-74769f527b24.png)
1. Also all the paths under the Manage > Virtual File System window have changed! (closing the emulator confirms it's just a visual bug, the config.yml paths are not changed)
![vfswindow_afterbootfailed](https://user-images.githubusercontent.com/4176375/85474079-2cc97e80-b582-11ea-9473-c876c362b1b5.png)
1. Copy the /dev_flash/ directory to the executable directory (E:/Emulators/RPCS3).
1. Attempt to start game. Game boots properly.

#### Please provide your system configuration:
* OS: Windows 10 Pro

**Comment by Megamouse** [comment]
your dev_flash folder is inside dev_hdd1. That is obviously wrong.

**Comment by billyea** [comment]
Yes, it is in the dev_hdd1 folder (for this test, I deleted the current settings in the GuiConfigs and that is the location it auto-populated in), but the issue also happens if I set the dev_flash path to locations other than the executable folder and install the firmware there too.

**Comment by Andryshik345** [comment]
Probably because VFS applies only for guest VM and not for RPCS3's backend.

**Comment by Megamouse** [comment]
cannot reproduce
