### ISSUE TITLE
Musou Orochi Z [BLAS50130] crashes before get in battle (very old issue)

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#8491]
This is the error log:
**F {PPU[0x1000000] Thread (main_thread) [0x001458d4]} VM: Access violation reading location 0x10000000 (unmapped memory)**

![未标题-1](https://user-images.githubusercontent.com/47111657/85507394-e2e5a480-b624-11ea-98bb-519ec72ec15c.jpg)

**Comment by elad335** [comment]
Thanks for reporting, please upload rpcs3.log.gz

**Comment by arcadee1977** [comment]
> Thanks for reporting, please upload rpcs3.log.gz
> And explain where this exception occurs in the game.

After selecting the characters and battlefields, choose to start the battle, and a scene demonstration will appear. After the demonstration, the game will crash when entering the battle 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4824973/RPCS3.log.gz)

**Comment by arcadee1977** [comment]
Crash occurs steps（Step 7 crash occues) ：

![未标题-1](https://user-images.githubusercontent.com/47111657/85552206-599a9600-b655-11ea-91db-284f9a38ebb8.jpg)
![未标题-2](https://user-images.githubusercontent.com/47111657/85552220-5ef7e080-b655-11ea-811d-7d841bbc1ac6.jpg)
![未标题-3](https://user-images.githubusercontent.com/47111657/85552244-63bc9480-b655-11ea-91f2-6654a9c08ffb.jpg)
![未标题-4](https://user-images.githubusercontent.com/47111657/85552251-661eee80-b655-11ea-818c-91d9dc080692.jpg)
![未标题-5](https://user-images.githubusercontent.com/47111657/85552262-6919df00-b655-11ea-8dde-44c26a679ac5.jpg)
![未标题-6](https://user-images.githubusercontent.com/47111657/85552277-6c14cf80-b655-11ea-9392-11b213ff6c64.jpg)
![未标题-7](https://user-images.githubusercontent.com/47111657/85552296-7040ed00-b655-11ea-9922-7c0bee27dabf.jpg)

**Comment by LadyDarkell** [comment]
hi , i have same problem... the game load fine.. when start frst mission...loading fine the intro cutscene...then...crash 
 any fix/update for this? 

i tried some new and old version of rpcs3.. same problem..crash ever

F {PPU[0x1000000] Thread (main_thread) [0x001d028c]} VM: Access violation reading location 0x10000000 (unmapped memory) [type=u32]

**Comment by Megamouse** [comment]
Is this still an issue?

**Comment by Sasha349** [comment]
Yes

**Comment by QJYEAH** [comment]
> Is this still an issue?

sure.

**Comment by sihunqu123** [comment]
Just confirmed that the the Japanese Version of this game(`BLJM-60139`, refer: https://www.play-asia.com/musou-orochi-z/13/7037gs) has the same issue.

**Comment by Sasha349** [comment]
Log with inrterpretiers 0.0.29-15466
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12289304/RPCS3.log)

**Comment by elad335** [comment]
Fixed by #14523
