### ISSUE TITLE
cellFSAccess

### ISSUE THREAD

**Issue by crystalct** [RPCS3/rpcs3#8492]
Inside official SDK Sony libs reference, cellFSAccess dosen't exists. Are you scure it works on real PS3 hardware?

**Comment by elad335** [comment]
Lots of functions used by VSH are not documented there as well for example, you cant rely on SDK alone.

**Comment by AniLeo** [comment]
I'm sure not everything is documented, if we have an implementation then it was found and reversed in the past

**Comment by clienthax** [comment]
If you look at the firmware modules the functions are present.

https://github.com/clienthax/Ps3GhidraScripts
