### ISSUE TITLE
Ratchet & Clank: A Crack in Time [BCES00511] - Missing particles & effects

### ISSUE THREAD

**Issue by revetix** [RPCS3/rpcs3#8500]
## Quick summary
Many particles and effects do not render ingame, such as weapon fire, forcefields, laser beams, etc.

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4832899/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
RSX capture: https://mega.nz/file/z50zEQaC#9_zCb9Jux2_7UeigOhu0K5ljLZ4d5TBhduNTQCl5MTc
RenderDoc capture: https://mega.nz/file/Dw0TjKxR#Jp8MwosTfwcAOsjhrVK0IwTN5j3513NgoAnZBU0f4XM

#### 3. Please attach screenshots of your problem.
Weapon fire, hoverboot and water effects are missing:
![Capture](https://user-images.githubusercontent.com/15834268/85768909-0aae3880-b709-11ea-86cf-9ac85ea2c224.PNG)

Laser effects are not rendered:
![Capture-2](https://user-images.githubusercontent.com/15834268/85768941-113cb000-b709-11ea-851c-7d428300d04d.PNG)

#### 4. Please provide comparison with real PS3.
![PS3_1](https://user-images.githubusercontent.com/15834268/85768985-1d287200-b709-11ea-90da-48bea45de1fa.png)
![PS3_2](https://user-images.githubusercontent.com/15834268/85769002-20236280-b709-11ea-8764-45de9735cd24.png)

#### 5. Please provide your system configuration:
* OS: Windows 10, version 1903
* CPU: Intel Core i7-6700K
* GPU: NVIDIA GTX 1080
* Driver version: 446.14
* RAM: 16 GB

#### Please include anything else you deem to be important.
Further testing shows that this issue is also present in other Ratchet & Clank games released after A Crack in Time, including All 4 One, QForce and Into the Nexus.

**Comment by lewa-j** [comment]
Double of #8086?

**Comment by arcadee1977** [comment]
I have encountered the same problem and hope it can be fixed as soon as possible

**Comment by Yaznae** [comment]
I tried messing with the options that contain the phrases "fixes missing or glitching textures". In addition to them not working, they crash the game. So, for now, there is no fix for it.

**Comment by SystemDii** [comment]
I have encountered the same problem ( weapon effect is missing) at the newest version (0.0.15-12096).
