### ISSUE TITLE
Mass Effect 2 very strange darkness

### ISSUE THREAD

**Issue by Basmurd** [RPCS3/rpcs3#8508]
Very strange darkness in some scenes, especially on Normandy at the very beginning of the game.

Details:

The problem appears immediately after the first cutscene. A dialogue begins with Shepard, and on the answer wheel the main character is just black, and as soon as we get to the cabin of the Joker, everything is absolutely normal.

RPCS3 Log: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4838277/RPCS3.log.gz)

Render Doc:
https://mega.nz/file/TZUiQAQJ#TnOa7JoIq445JRw89QJKwkzCdSCptfzXW6lWo_BJCkU

RSX Capture:
https://mega.nz/file/iRcEWIpL#o3qWIYOrg8D07zErSCrrlP-pMqvKkukDNRrJID6AiJE

System configuration:
* OS - Windows 10 1909
* CPU - AMD Ryzen R5 3600
* GPU - Geforce 1070 Ti 
* Driver version - 446.14

Screenshots:
![rpcs3_jopVbnJGTL](https://user-images.githubusercontent.com/61318181/85885527-2985fb00-b7ed-11ea-9b6c-d5b8834d5df5.png)
![rpcs3_wstnprwcg6](https://user-images.githubusercontent.com/61318181/85885543-2e4aaf00-b7ed-11ea-9a24-3d9846a94e62.jpg)
![rpcs3_jfTuHKTTLP](https://user-images.githubusercontent.com/61318181/85885552-30ad0900-b7ed-11ea-929e-5a688ecfa888.jpg)

**Comment by Andryshik345** [comment]
Please, provide a screenshots from real PS3 as it should be to work.

**Comment by Basmurd** [comment]
Sorry, but I do not have the original console. I can only search for videos on YouTube, or screenshots. :(

**Comment by Andryshik345** [comment]
It would be enough.

**Comment by Asinin3** [comment]
Screenshots from real hardware isn't really necessary. But renderdocs / rsx captures are

**Comment by Basmurd** [comment]
On the original console it looks like that, found on YouTube.
![image](https://user-images.githubusercontent.com/61318181/85926125-d1f79600-b8a5-11ea-88e1-10f84c28bb22.png)
![image](https://user-images.githubusercontent.com/61318181/85926131-e9368380-b8a5-11ea-8d9c-0e11708d3ecf.png)

**Comment by Basmurd** [comment]
> Screenshots from real hardware isn't really necessary. But renderdocs / rsx captures are

Files are attached, I hope it helps in finding an answer.

**Comment by galahadhiryu** [comment]
Apparently has been fixed.

Intel i5 12400
16gb ram
AMD rx 6600

1800p|framerate unlocked.
![Captura de Tela (6)](https://user-images.githubusercontent.com/51791923/174921112-8197bfd3-816a-450a-b499-523bc7ab679a.jpg)
![Captura de Tela (5)](https://user-images.githubusercontent.com/51791923/174921117-5d2dfa4c-c986-40bd-b7d0-d71666ede298.jpg)

**Comment by Megamouse** [comment]
closing assuming fixed
