### ISSUE TITLE
NCAA Football 14 [BLUS31159] crashes during startup

### ISSUE THREAD

**Issue by hineybush** [RPCS3/rpcs3#8521]
## Quick summary
I start the game, it loads, then crashes on the "cannot connect to EA servers" prompt directly after the "press start" prompt. 

## Details

See above. Game launches ok (it seems) then crashes before reaching the main menu. Game also worked fine with the same config on version v0.0.10-10565, however this issue persists on -10566 and -10567. The start menu/main menu audio keeps playing fine.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4842577/RPCS3.log)

#### 1. Please attach RPCS3's log.
* Run the game until you find the issue.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc. 

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc. 
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

![bug](https://user-images.githubusercontent.com/7409490/85952509-cce32700-b937-11ea-9379-20103e79013d.PNG)

#### 5. Please provide your system configuration:
* OS Windows 10 Pro Build: 18363
* CPU Intel i9-9900K CPU @ 3.60GHz
* GPU GeForce RTX 2070
* Driver version 451.48.0.0
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by elad335** [comment]
does it work with SPU interpreter?

**Comment by hineybush** [comment]
> does it work with SPU interpreter?

Same crash and much worse performance with the fast and precise interpreter, versus the recompilers.

**Comment by hineybush** [comment]
It is also worth mentioning that the only other game I've been playing, Skate 3 (BLES00760) has been working perfectly fine with the same settings as above.

**Comment by connorwalks** [comment]
@hineybush This is probably not an issue with the game, it's working with latest master (10573) for me. You probably enabled the network connectivity for some reason. This game needs PSN sign-in to connect to EA servers (AFAIK) so it causes a crash when you try to spoof it. Change network status to "disconnected" and it should work fine. If that is the case, simply close this issue

**Comment by illusion0001** [comment]
The log has all the used settings listed.

**Comment by connorwalks** [comment]
> 
> 
> The log has all the used settings listed.

My bad, totally missed it. Didn't see it under the log step so I assumed he forgot

Anyway, looks like I was right. He has the network enabled. It causes a crash on this game on that menu. If he disables it the game will work fine. This issue can be closed

**Comment by hineybush** [comment]
> > The log has all the used settings listed.
> 
> My bad, totally missed it. Didn't see it under the log step so I assumed he forgot
> 
> Anyway, looks like I was right. He has the network enabled. It causes a crash on this game on that menu. If he disables it the game will work fine. This issue can be closed

Yup, I disconnected both the Network Status and the PSN Status and it bypasses the EA Server prompt. Thanks!
