### ISSUE TITLE
MotorStorm [BCES00006] - VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#8522]
F 0:03:14.827776 {PPU[0x1000000] Thread (main_thread) [0x00298340]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file d:\a\1\s\rpcs3\Emu\RSX\VK\VKHelpers.cpp:957)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4842592/RPCS3.zip)

**Comment by uaqlover** [comment]
It's fixed @Megamouse , @AniLeo
