### ISSUE TITLE
Gran Turismo 5 crashes with VK_ERROR_DEVICE_LOST on specific tracks

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#8529]
The game crashes with VK_ERROR_DEVICE_LOST on specific tracks at night or with variable time as soon as you enter the track, and it happens regardless of AA on or off. I also want to note that AMD GPUs are not affected, it's an Nvidia-only problem, and Special Stage Route 7 is an easy place to reproduce that error. I tested as far back as v0.0.6-8384 and it still didn't work, so I assume it's not a regression either.
Specs: I7-4770, GTX 1050 Ti, Win 10 1909
Log: 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4847680/RPCS3.zip)

**Comment by illusion0001** [comment]
Need save file

**Comment by Satan86** [comment]
[BCUS98114-GAME.zip](https://github.com/RPCS3/rpcs3/files/4847752/BCUS98114-GAME.zip)

**Comment by gtgamer468** [comment]
I'm using version 2.11 with a mod that fixes hidden tracks from v1.00-v1.13 and also enables the hidden LAN mode. I also have some DLCs installed including for Special Stage Route X, the "Speed Test Course Pack". I get this issue on SSRX as well.
[SSRX.zip](https://github.com/RPCS3/rpcs3/files/4853676/SSRX.zip)

**Comment by Satan86** [comment]
Closing as fixed by #8545
