### ISSUE TITLE
RPCS3 0.0.10-10594 don't show any patches

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#8533]
Recently there was a chance to the patch system so I had to redownload the patch from the wiki page for Persona 5 and that fixed the problem but after I update rpcs3 again(to this version),rpcs3 don't show any codes again

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4850854/RPCS3.zip)
Also when I remove the file and try import it by drag-drop,validation says success and importing too but the only thing that is saved in the file is

```
Version: 1.2

PPU-e72e715d646a94770d1902364bc66fe33b1b6606:
  Patches:
    Games:
      {}
    Patch:
      []
```

**Comment by HerrHulaHoop** [comment]
The patch system was updated. So you need to replace the old patch files with the [new ones](https://cdn.discordapp.com/attachments/442667232489897997/727281709036601405/patch.yml). Also, that imported patch file looks weird. The format used is version 1.1 but it says version 1.2 at the top.

I tested 0.0.10-10594 and everything worked fine for me. Even importing patches.

**Comment by vsub** [comment]
Thanks but why do I see BLUS31604 and NPUB31848 for Persona 5,which codes are for my version
All game related is in BLUS31604 but the saves are in NPUB31848

And btw the Patch Manager don't remember the "Only shows owned games"(maybe a code is not added to remember it)

PS.I don't remember from where I get the patch and it says 1.2 because I was trying to make it work

**Comment by HerrHulaHoop** [comment]
The version that you see in the gamelist is the one that is relevant. Once you press "Only shows owned games", which version is still shown is the one that you have installed. 

With regards to making "Only shows owned games" persistent, it can definitely be done if Mega wants to do.

**Comment by vsub** [comment]
Well I am selecting that checkbox and those two are left visible
BLUS31604 is the game and NPUB31848 is when the game installed(NPUB31848DATA)
