### ISSUE TITLE
 Failed to create cache directory

### ISSUE THREAD

**Issue by MangoStevens** [RPCS3/rpcs3#8536]
When I try to boot up Persona 5 an error shows up that says Failed to create cache directory: D:/PS3/PS3 Emulator/cache/BLUS31604/ppu-p0mUcgwxCXK2cbrML0u1mkCmab8a-EBOOT.BIN/ (Access violation)

I had already opened the game before and played it and I even patched it and added a cpk mod. I had already tried to resolve the issue by unchecking the Read-Only box in the properties for the ppu-p0mUcgwxCXK2cbrML0u1mkCmab8a-EBOOT.BIN folder and the game was up and running again. However, this method only worked for that one time, if I try to do this again it would not work and the folder would revert back to Read-Only, I do not know if that is the part of the problem.

I have ownership of all files involved and they are all in the D drive. (RPCS3 0.06-7793-84d42ecb Alpha)

**Comment by sampletext32** [comment]
Looks like a prehistoric RPCS3 build. Latest is 0.0.10-10595. Consider updating your RPCS3. 
Can be closed as irrelevant
