### ISSUE TITLE
UFC Undisputed 3 freeze

### ISSUE THREAD

**Issue by J03lqm** [RPCS3/rpcs3#8540]
The game gets freeze after 2min fighting, menu works correctly
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4854435/RPCS3.log)

**Comment by Asinin3** [comment]
Please right-click the game and remove caches and retest.
From log there's a lot of: `·W 0:08:47.288308 {RSX [0xa437900]} RSX: Cache miss at address 0xC0000000. This is gonna hurt...` spam

**Comment by digitaldude555** [comment]
@J03lqm retest the game.

**Comment by J03lqm** [comment]
It still do the same.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5939371/RPCS3.zip)

**Comment by digitaldude555** [comment]
The bot said this reading your log.
"Multithreaded RSX is enabled along with Write Color Buffers which may cause crashes"
Might be why you are crashing also disable accurate xfloat.

**Comment by J03lqm** [comment]
@Asinin3 @digitaldude555 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5940228/RPCS3.zip)
now i get this one.

**Comment by MSuih** [comment]
Duplicate of #9740
