### ISSUE TITLE
Gran Turismo 6 Mirror Issue (mixed with map)

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#8546]
I found a mirror effect issue when you're driving inside the car.
It's strange coz the graphics seem to be mixed with the mini map on the left...
And this bug is only avalaible with this car view (the mirror works fine in any other views)

![GT6 Mirror](https://user-images.githubusercontent.com/67762812/86410485-1aa2bb00-bcbb-11ea-9fe3-088bc448ce7a.JPG)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4866734/RPCS3.log.gz)

**Comment by PY3AN** [comment]
With activated Read Color Buffers and Write Color Buffers checkboxes the mirror is displayed normally (On 1.06 version)
![Mirror](https://user-images.githubusercontent.com/76910089/103484896-4f770280-4e03-11eb-9c1d-d0a45528791c.png)

**Comment by kd-11** [comment]
Closing; fixed via configuration.
