### ISSUE TITLE
Dynasty Warriors Gundam Reborn

### ISSUE THREAD

**Issue by Basuru** [RPCS3/rpcs3#8554]
## Quick summary
Crashes when loading any map for any mode, even with various patch.yml's.

## Details

See above
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4873942/RPCS3.log.gz)

#### 4. Please provide comparison with real PS3.

Works without crashing

#### 5. Please provide your system configuration:
* OS Windows 10
* CPU i7 7700k
* GPU Nvidia 1080
* Driver version latest
* 32 Gb Ram

**Comment by reaper185** [comment]
The patch works just fine. Just place it in the patches folder. This works for BLES02057. I need to update the patch to the latest version 1.2. I have the legacy and the version1.0

Version 1.0
[patch.zip](https://github.com/RPCS3/rpcs3/files/4874439/patch.zip)

Legacy Patch
[patch.zip](https://github.com/RPCS3/rpcs3/files/4874437/patch.zip)

**Comment by elad335** [comment]
Duplicate of #4522
