### ISSUE TITLE
Tekken Tag Tournament 2 Feng texture issues

### ISSUE THREAD

**Issue by eatsports** [RPCS3/rpcs3#8556]
## Quick summary
In Tekken Tag 2, the texture on Feng's pants does not render properly and fills the screen

## Details
In Tekken Tag 2, the texture on Feng's pants does not render properly and fills the screen, the issue is only with his default outfit but it makes it pretty much unplayable because it covers the whole screen.
You can see the issue in the attached screenshot

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4875303/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4875304/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
[BLES01702_20200705201337_capture.zip](https://github.com/RPCS3/rpcs3/files/4875323/BLES01702_20200705201337_capture.zip)

#### 3. Please attach screenshots of your problem.
![fengtt2](https://user-images.githubusercontent.com/29803390/86538598-9db45300-beff-11ea-8723-f84f10ce9807.png)
![fengtt22](https://user-images.githubusercontent.com/29803390/86538716-5aa6af80-bf00-11ea-9f83-6ac480918338.png)

#### 4. Please provide comparison with real PS3.
![fengps3](https://user-images.githubusercontent.com/29803390/86538641-cfc5b500-beff-11ea-88dc-e51e7e9ccb6d.png)
#### 5. Please provide your system configuration:
* OS - Windows 10 version 2004 (19041.329)
* CPU - AMD Ryzen 7 3700x
* GPU - GTX 1080
* Driver version - 451.48

**Comment by MarioSonic2987** [comment]
Enable Accurate xfloat, in CPU settings.

**Comment by eatsports** [comment]
That fixed it, thanks!
