### ISSUE TITLE
Emulator doesn't open after pull #8399

### ISSUE THREAD

**Issue by EddyHg80** [RPCS3/rpcs3#8560]
Ok so I updated today after a while and the emulator didn't open after the process.

An older version worked for me so I found, after several version downloaded, that my problem started with rpcs3-v0.0.10-10479-1668900f, so after the pull #8399.

Since not a lot of people are talking about this I think it's a problem on my end, what should I do?

**Comment by Megamouse** [comment]
Duplicate of #8409
