### ISSUE TITLE
Dynasty Warriors Gundam Reborn rotating models

### ISSUE THREAD

**Issue by CoolEmuGuy** [RPCS3/rpcs3#8564]
Happens whenever I use LLVM Recompiler without accurate xfloat
![bug](https://user-images.githubusercontent.com/67999271/86890168-1a754600-c127-11ea-8b29-65fb7ccd4415.png)

last working build was 
rpcs3-v0.0.10-10464-d47d597b_win64

**Comment by zombie167** [comment]
Maybe your CPU lacks the tsx instruction

**Comment by CoolEmuGuy** [comment]
> Maybe your CPU lacks the tsx instruction
> https://www.youtube.com/watch?v=MXMc7seTvqw&t=682s

still the mentioned build worked perfectly without the TSX instruction.

**Comment by Asinin3** [comment]
Best to tag the pull request which caused this: https://github.com/RPCS3/rpcs3/pull/8338 (like i just did by including a link to the PR in the comment section/issue description) so dev is notified etc. 

I can confirm this issue, ran into it while trying to record comparison footage for the last rpcs3 video

**Comment by CoolEmuGuy** [comment]
Fixed in latest build
