### ISSUE TITLE
Resistance 2™ [BCES00226] jittery audio

### ISSUE THREAD

**Issue by MainTomato** [RPCS3/rpcs3#8565]
Resistance 2 version 01.00 has jittery audio on the default settings and even with time stretching enabled on the campaign intro cutscene.

Log: https://bin.snopyta.org/?e1c2cc3e458b7bf9#9eQhAJXjyJhemaEfpcB7hDCmgX8Y4AsX7G8JPoro83MF

Linux RPCS3 Version: 0.0.11-10627-5fae1b36 Alpha

**Comment by kd-11** [comment]
1. There is an actual log file generated in the ~/.cache/rpcs3 folder.
2. You did not mention your hardware setup.
3. Default settings has "spu loop detection" enabled to cater for low end laptop CPUs. This is the primary cause for jittery audio in most games, but ofc you lose fps if you're using a dual core.

Flagging as invalid until a proper log file is provided. In the meantime, also try the other recommendations.
