### ISSUE TITLE
BCES00052 Ratchet and Clank Future Tools of Destruction audio problems

### ISSUE THREAD

**Issue by TheVenixx** [RPCS3/rpcs3#8566]
## Quick summary
Game; Ratchet and Clank Future Tools of Destruction (BCES00052) Audio not playing correctly

## Details
Cut-scene dialogue not present for all characters, rest of the sounds are playing fine. Generally crashes within 5 minutes of starting with notable frame rate drops regardless. Main issue is audio based.

#### 1. Please attach RPCS3's log.
https://www.dropbox.com/t/oC7BPoIuHUKh6omg

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
RSX Capture File - https://www.dropbox.com/t/KtYZbQSH0qkD5lyZ

#### 3. Please attach screenshots of your problem.
Problem not demonstrable with screenshot

#### 4. Please provide comparison with real PS3.
https://www.youtube.com/watch?v=xG5oXGFt54k

#### 5. Please provide your system configuration:
Windows 7 64 bit
Intel i74790 @ 3.60ghz
Geforce GTX 1660ti
10.18.10.3540
32gb RAM

**Comment by Sonickyle27** [comment]
That can happen if the console language is set to a language the version of the game does not support. Try changing the console language to English (UK).

**Comment by TheVenixx** [comment]
> 
> 
> That can happen if the console language is set to a language the version of the game does not support. Try changing the console language to English (UK).

System language already set to English UK

**Comment by Sonickyle27** [comment]
What happens if you change the language back to English (US) if you haven't tried that yet? For me the console language was the reason why I had no prerendered cutscene dialogue.

**Comment by TheVenixx** [comment]
> 
> 
> What happens if you change the language back to English (US) if you haven't tried that yet? For me the console language was the reason why I had no prerendered cutscene dialogue.

Okay English US is now making the pre-rendered audio load in...

There is a difference between UK and US audio apparently. Instances of "comforter" replaced with "duvet" or "trunk" replaced with "boot" maybe? Seems silly to me
