### ISSUE TITLE
Unusable global menu.

### ISSUE THREAD

**Issue by ahmubashshir** [RPCS3/rpcs3#8567]
## Quick summary
Menu shows only "Update Available"

## Details
Global menu shows only "Update Available!".
![Regressed](https://user-images.githubusercontent.com/24864366/86921862-a0a48300-c14d-11ea-8cbf-4b22cd309a18.png "Regressed")
![Expected](https://user-images.githubusercontent.com/24864366/86922799-f75e8c80-c14e-11ea-81db-762af3c1bc8e.png "Expected")

Build: 0.0.11-10607
PR: #8541 

#### logs:
* With regression: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4890857/RPCS3.log.gz)
* Expected: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4890861/RPCS3.log.gz)

#### system configuration:
* OS: Manjaro Linux 20.0.3
* CPU:   Pentium G3250
* Graphics: iGPU
* version: 4.5 Mesa 20.0.7

**Comment by illusion0001** [comment]
try https://github.com/RPCS3/rpcs3/pull/8569

**Comment by Megamouse** [comment]
reopen if still an issue
