### ISSUE TITLE
[BCES00008] Warhawk RPCS3 and Warhawk Reborn Service

### ISSUE THREAD

**Issue by krazynez** [RPCS3/rpcs3#8570]
## Quick summary
Warhawk Reborn and RPCS3 would work together, now there is an issue with the same port being used.

## Details
Could use the Warhawk Reborn service with RPCS3 until version 0.0.8-9549, for some reason that version and beyond causes a the same port being used issue for Warhawk reborn and  RPCS3. 

version 0.0.8-9546 successful:
![image](https://user-images.githubusercontent.com/39999447/86968204-c9228200-c139-11ea-8782-0d85f70863e5.png)

version 0.0.8-9549 failed:
![image](https://user-images.githubusercontent.com/39999447/86968393-1e5e9380-c13a-11ea-9142-e43a3fd12e64.png)

#### 6. Please provide your system configuration:
* OS: Pop!_OS 20.04 LTS x86_64
* CPU: Intel i7-3930K (12) @ 4.700GHz
* GPU: NVIDIA GeForce GTX 960
* Driver version: 440.100

https://www.youtube.com/watch?v=KInEo1hLxMA&feature=youtu.be

**Comment by krazynez** [comment]
[rpcs3-v0.0.8-9549-d3abff54_linux64_failed.gz](https://github.com/RPCS3/rpcs3/files/4893222/rpcs3-v0.0.8-9549-d3abff54_linux64_failed.gz)
[rpcs3-v0.0.8-9546-76271800_linux64_successful.gz](https://github.com/RPCS3/rpcs3/files/4893223/rpcs3-v0.0.8-9546-76271800_linux64_successful.gz)

**Comment by krazynez** [comment]
RPCN and custom DNS for Warhawk Reborn work for this now.

**Comment by MSuih** [comment]
Closing this as the issue seems to have been fixed.
