### ISSUE TITLE
[BLES00425] Sonic Unleashed freezes on start-up

### ISSUE THREAD

**Issue by nextuntouchable** [RPCS3/rpcs3#8573]
When Sonic Unleashed is booted, the game briefly shows the loading screen before freezing. No inputs are accepted and sound can not be heard.

[RSPC3.log](https://drive.google.com/file/d/1QkTa6Di0MUhIt0DZhz0alQ31ZigUsaUV/view?usp=sharing)

![image](https://user-images.githubusercontent.com/57555789/87024395-f66e3f00-c1d0-11ea-8f89-c2d19d2f3221.png)

* OS - Windows 10 Home v 1903, OS Build 18362.900
* CPU - Intel Core i5-9400f CPU @ 2.9GhZ (6 cores)
* GPU - Nvidia GeForce GTX 1650 
* Driver version - 26.21.14.4587

**Comment by elad335** [comment]
Try with TSX disabled

**Comment by AniLeo** [comment]
Is this a regression? If so, what build? Can you try 0.0.11-10636 vs 0.0.11-10639?

**Comment by Yahfz** [comment]
![image](https://user-images.githubusercontent.com/17715080/87025768-31f91100-c1b1-11ea-8269-7eee4a67b58d.png)
Works fine here with TSX enabled. As ani said, can you provide more info?

**Comment by Yahfz** [comment]
![image](https://user-images.githubusercontent.com/17715080/87026072-987e2f00-c1b1-11ea-852b-9373ad2c4726.png)
TSX Disabled is also fine.

**Comment by nextuntouchable** [comment]
Sorry for the late reply. Downloaded both .10636 and .10639 and the issue still happens on both of these builds, so I don't believe it's a regression. The build for the OP screenshots is 0.0.11-10641. No custom configuration.

**Comment by Megamouse** [comment]
Pirated content
