### ISSUE TITLE
God Mode [NPUB31140] - Graphical issues

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#8574]
## Quick summary
The game doesn't look good at the moment. And no settings I tried helped.
RSX capture is pitch black. Tell me if you need it anyway.

## Details
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4897692/RPCS3.zip)

![image](https://user-images.githubusercontent.com/23019877/87056509-08b6a000-c206-11ea-9725-36e21d6c88a1.png)
![image](https://user-images.githubusercontent.com/23019877/87056608-2552d800-c206-11ea-9025-5c2f9198b810.png)

**Comment by kd-11** [comment]
This weird game doesn't load anymore. It seems to use cellSpursJq without linking it the usual way, so it ends up using the HLE version which is very incomplete.

**Comment by Megamouse** [comment]
I tested it yesterday or the day before....

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/issues/10432 has my result. I'll keep trying, maybe its just some setting.

**Comment by kd-11** [comment]
Was able to load this.
The graphical commands are executed correctly, but we're obviously missing a bunch of draw commands. The missing stuff is simply never drawn at all, similar to sonic 06. I'll keep checking if zcull maybe has something to do with it.

**Comment by kd-11** [comment]
Needs accurate ZCULL implemented. The game is doing some math with the occlusion sample counts and making decisions based on that, obviously passing the same dummy value each time is not going to work. Passing specially crafted input stream gets things to start rendering, but obviously a proper implementation is needed.
