### ISSUE TITLE
Win32 Error 0xc00005,fatal error,cannot play the game

### ISSUE THREAD

**Issue by lax23** [RPCS3/rpcs3#8576]
I cannot play my persona 5 16.6gb game bcoz of this error i have.It is  common error everyone faces.i Downloaded the emulator and extracted the rar file properly and also i installed the game properly.It worked in the beginning,but after adjusting the settings it stopped working.I kept the settings on default ,still shows this error.Unhandled Win32 Exception 0xc0000005 is the error i get

My rpcs3 info and my computers
RPCS3 v0.0.11-10647-ab3d36f0 Alpha | HEAD | Firmware version: 4.86
Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz | 4 Threads | 7.92 GiB RAM | TSC: 1.992GHz | AVX+ | FMA3
S UPDATER: RPCS3 is up to date!

plz fix it soon as possible

**Comment by Shinobi2499** [comment]
do you have bandicam installed?
