### ISSUE TITLE
TSX on Red Dead Redemption. I7-8700k

### ISSUE THREAD

**Issue by mika123565** [RPCS3/rpcs3#8577]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4907616/RPCS3.log)

Hello, RPCS3 Team.

I posted this on Reddit first - https://www.reddit.com/r/rpcs3/comments/hp2216/tsx_on_red_dead_redemption_not_working_8700k/fxqjbw4/

It seems like sort of regression with tsx enabled on RDR. Like you see from the Reddit's thread- I am not the only one. Please advise. 

Thank you

**Comment by RainbowCookie32** [comment]
TSX-FA (newer microcode TSX) is known to have issues with rpcs3

**Comment by mika123565** [comment]
Down graded the microcode and deleted the dll in sys32 folder. Fixed the issue

**Comment by illusion0001** [comment]
Can this be closed?
