### ISSUE TITLE
RPCS3 Crashes with the following error.

### ISSUE THREAD

**Issue by Nilot352** [RPCS3/rpcs3#8588]
`Debugger: 0
Log file open failed: /home/nilot/.cache/rpcs3/RPCS3.log.gz (error 13)
Segfault reading location 0000000000000000 at 00007ff8940d4fd0.
Emu Thread Name: 'rsx::thread'.
Thread id = 140702172305152.`

`WARNING: QApplication was not created in the main() thread.
[1]    5079 segmentation fault (core dumped)  /home/nilot/.local/share/lutris/runners/rpcs3/rpcs3.AppImage`

The Game being tested is Zone of the Enders HD Edition(NPUB31313).
The OS is Ubuntu 19.04
The Qt version is:
`Qt 5.12.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 8.3.0) on "xcb" 
OS: Ubuntu 19.04 [linux version 5.0.0-38-generic]`

**Comment by AniLeo** [comment]
You're using an old EOL Ubuntu Beta, update to latest (20.04) for this to be valid, we are on Qt 5.14 and not 5.12, but it's bundled with the AppImage either way so system QT doesn't matter. 

Missing log file too.

**Comment by AniLeo** [comment]
Closing as invalid, submit this as a support request on one of our support platforms

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
