### ISSUE TITLE
NFS Undercover occasional z-fighting(?) and FS export error spam

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#8596]
Example for the FS errors:

```
·E 0:00:20.512011 {RSX [0x458e46c]} RSX: FS exports depth component but depth test is disabled (INVALID_OPERATION)
```

Full log (not much more informative though): [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4940903/RPCS3.log.gz)

A perhaps connected phenomenon of z-fighting / texture flicker can also be observed at the right areas of the map:

![image](https://user-images.githubusercontent.com/10439488/87841313-d0b5f980-c8a4-11ea-875d-fd8d9779cf65.png)
![image](https://user-images.githubusercontent.com/10439488/87841316-d57aad80-c8a4-11ea-891e-4830ef873b04.png)

Note the difference on the distant wall on the right side of the images.

RSX Capture: [BLES00450_20200718025710_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/4940906/BLES00450_20200718025710_capture.rrc.gz)

**This ticket is not to be investigated until the next maintenance sprint.**

**Comment by kd-11** [comment]
FYI depth export error is a game bug - rpcs3 does what PS3 also does (export/write doesn't do anything if depth test is disabled). I suppose the fix for that would be to just lower the error to a warning.

**Comment by dio-gh** [comment]
I suppose, but that's not really the meat of the issue here, that'd be the z-fighting in the background. While I don't have a reference footage, I'm doubtful it looks like this on realhw.

**Comment by kd-11** [comment]
Test https://github.com/RPCS3/rpcs3/pull/12788

**Comment by Megamouse** [comment]
needs update

**Comment by dio-gh** [comment]
Savefiles (to be extracted to `/dev_hdd0/home/00000001/savedata`):
[BLES00450-NFS_UNDERCOVER.zip](https://github.com/RPCS3/rpcs3/files/10923217/BLES00450-NFS_UNDERCOVER.zip)

Just back up a bit and steer the car to the right, the situation shown above will be right there.

Might be important to note is that I have the game updated to the latest version (v1.02).

**Comment by Satan86** [comment]
Hello. Need For Speed Undercover is a very broken game, regardless of platform, so it did not surprise me to find out that this issue is also present on PS3, and is not an emulador bug. This video was recorded on my console.

https://user-images.githubusercontent.com/61447828/224507372-12edd6ea-5a17-4654-a169-3f283350e574.mp4

**Comment by dio-gh** [comment]
Ah, I see. Thanks for checking, sorry about it.
