### ISSUE TITLE
SIREN Blood Curse BCES00294 - Vulkan Graphics Issue

### ISSUE THREAD

**Issue by Betchplsss** [RPCS3/rpcs3#8599]
## Quick summary
The graphics of the game is corrupted when using Vulkan api. The issue is not present though during cutscenes.
When using "strict rendering", the issue is resolved but drops the framerate to half on certain areas. 
When using opengl, there is a diagonal artifact during the gameplay and random crashing.

## Details

Please describe the problem as accurately as possible.

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4942027/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture.

Here: https://www.mediafire.com/file/4n3jbyvhhsqlr74/BCES00294_20200719003418_capture.rrc/file

#### 3. Please attach screenshots of your problem.
Vulkan:
https://bit.ly/2ZDR35B
https://bit.ly/3fHKLrf

Open GL: 
https://bit.ly/2ZERuMP

#### 5. Please provide your system configuration:
* OS - Windows 10 Version 2004
* CPU - Ryzen 3700X
* GPU - AMD RX 5700XT 
* Driver version - 20.7.1(latest)
* RAM - 16GB

#### Please include.
* Let me know if I missed something.

**Comment by jokoputera** [comment]
Did you tried using older version? And what version that worked well? Or never?
Any savegame so developer easy to see right away ?

**Comment by Betchplsss** [comment]
@jokoputera - I've tried that version and the game was covered with some kinda in-game effects then turns all black.
Screenshot: https://bit.ly/2WBw6WS 

I've found this working version though. [rpcs3-v0.0.6-8151-7de3c410_win64.zip](https://github.com/RPCS3/rpcs3/files/4943091/rpcs3-v0.0.6-8151-7de3c410_win64.zip)
But there is a certain area in the game where there is a bright white light on certain objects and it's game breaking.
Screenshot: https://bit.ly/30oMrPT 

Logs and saved game of the bright light issue:
[BCES00294SIREN-DATA.zip](https://github.com/RPCS3/rpcs3/files/4943099/BCES00294SIREN-DATA.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4943100/RPCS3.log.gz)


Found the forum below where it says version "**RPCS3 0.0.7-8935-d4ba7f37**" fixed the bright light issue but the issue from my original post is there when I tried it. https://forums.rpcs3.net/archive/index.php/thread-180907.html 
(Note: Issue will be on the very start of the game except on cutscenes.)

**Comment by NudeNULL** [comment]
I have the same issue right now!
And have nearly the same setup:
Ryzen 3600X
RX 5700XT
Latest Windows
Latest Graphics Drivers

**Comment by Betchplsss** [comment]
@NudeNULL 
- it seems like this is on the CPU. Users with Intel CPU doesn't have this issue. We'll find out though when the developer check this.

**Comment by RainbowCookie32** [comment]
So far everyone that commented on this issue has a Navi GPU. We'd need someone with another architecture family to test so we can confirm it's not another Navi issue

**Comment by illusion0001** [comment]
I encountered random freezes just switching between the menus, hard to reproduce but possible

**Comment by Betchplsss** [comment]
Uhhmmm sorry new on this forum. What does the label "Need Information" means? need more info regarding the issue?

**Comment by RainbowCookie32** [comment]
Indeed. It'd be nice for someone with a non-Navi GPU could test if they can reproduce the issue.

**Comment by y-salnikov** [comment]
I think non-Navi GPU owners have no reason to search for this issue.

My specs are:
- Ryzen 2700x
- Linux
- Radeon RX580

Vulkan:
![Vulkan](https://user-images.githubusercontent.com/5237022/104808794-f8f5c500-5801-11eb-9c69-4c2a51f32c9b.png)

OpenGL:
![Снимок экрана_2021-01-16_13-50-30](https://user-images.githubusercontent.com/5237022/104808876-77eafd80-5802-11eb-97f7-a4857adcc6e9.png)

**Comment by kd-11** [comment]
Any intel CPU users affected?

**Comment by Stormspirit98-lgtm** [comment]
hi can u help me for a full version for this game siren blood curse on rpcs3 ?
thanks

**Comment by Chaython** [comment]
10900f / RTX 3080 vulkan
Image is very noisy. I looked up a playthrough and there wasn't all this noise. Seems to be an issue with the scaler. As when in a window, it's hardly noticeable.
Native res is 4k so either it's too small, or to mpeg noisey
![image](https://user-images.githubusercontent.com/6486343/128626699-78bc075d-e98c-4439-a13b-373cb83a4a0a.png)

**Comment by kd-11** [comment]
In this case this issue should be closed.
Obviously the scaler is an addition not present on real PS3 software so problems are expected in some cases there. As long as 720p renders correctly as it would on a PS3 of the era, we can consider the issue resolved.

**Comment by Betchplsss** [comment]
hmmm..   no idea why I'm seeing this on my end. Can you explain it to me again? I didn't quite understand your last comment. Sorry

![rpcs3_AcMaNDIO3T](https://user-images.githubusercontent.com/66388734/129079070-d1ddb9d0-4565-4c8d-8a41-193078cb2e1d.jpg)

**Comment by RainbowCookie32** [comment]
Resolution scaling isn't a thing on the PS3, it's a hack from RPCS3's side. Games might react badly to it.

If the game works fine at 720p with 100% scaling, then there's no issue there. We don't accept issues with resolution scaling since they are not emulator bugs per-se, but rather the game not being able to properly handle. Not something we can fix.

**Comment by Puxirepublic** [comment]
I can confirm it's Navi GPU related issue. 

I am a consistent intel CPU user, used owned an Nvidia GPU and also post another issue of this game #8978 at that time, At that time I don't have these artifact glitch colors covered while in this game. 

Now I own a RX580, with latest RPCS3 build, use default 720p, I got these gray artifact colors covered whole time in this game.

![Annotation 2023-06-09 123409](https://github.com/RPCS3/rpcs3/assets/5261049/d40771ac-6431-4ebc-9f81-59d044fe561e)
![Annotation 2023-06-09 123426](https://github.com/RPCS3/rpcs3/assets/5261049/ecabee04-a72f-46c3-b9af-7796cc3d4ad9)
