### ISSUE TITLE
[Feature Request] Motion sensor for other controller than sixaxis

### ISSUE THREAD

**Issue by jokoputera** [RPCS3/rpcs3#8600]
## Quick summary
Motuon sensor  controller emulation

## Details
Some games maybe need a motion sensor stick kike sixaxis, such as Heavenly Sword on the Bridge level part or Entering the Banquet level to aim the thrown object.

This will be hard or or even luck if youre using PS2 controller or some controller that dont have motion sensor (my Sixaxis controller is broke, so im using my PS2 controller)

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay : for the games that need motion sensor, will not work properly if you dont have a motion sensor stick
* UI : maybe a tick button under the Controller setting to turn off and turn on key combination to make analog controller act like a sensor? Such as combination press L3 with movement will act also as motion sensor?

#### 2. Please tell us, why your feature is important to RPCS3.
To add some features to fill up all the emulation

#### 3. Please attach screenshots of the feature implemented in other projects.
None, i haven't check the Switch Emulator or other emulator since i dont have neither console or games

#### 4. Please provide your system configuration:
* OS Windows latest update
* CPU Ryzen 5 3600
* GPU GTX1660 Super
* Driver version latest

#### Please include.
* I have nothing to expect, i think i can just buy the controller :) im just curious.tq

**Comment by nitroos-ai** [comment]
May be try to implement the motion sensor app with android phones that is used on CEMU.
[https://cemuhook.sshnuke.net/padudpserver.html](url)

**Comment by legend800** [comment]
Cemu + these other modern emulators. Look forward to seeing this for rpcs3!

Citra:
https://github.com/citra-emu/citra/pull/4059

Yuzu:
https://github.com/yuzu-emu/yuzu/pull/4382#pullrequestreview-451144574

Ryu:
https://github.com/Ryujinx/Ryujinx/pull/1363

**Comment by Krishster** [comment]
Any progess till date @Megamouse ?

**Comment by drago338** [comment]
This would be really useful hopefully its implemented

**Comment by Darkhost1999** [comment]
Some notes that may or may not help.
https://www.github.com/ViGEm/DsHidMini/tree/master/docs%2FSIXAXIS.md

**Comment by bschoenmaeckers** [comment]
SDL2 controller api has native support for motion sensors.
https://github.com/libsdl-org/SDL/blob/4cd981609b50ed273d80c635c1ca4c1e5518fb21/WhatsNew.txt

**Comment by IndegoRune** [comment]
This would also be fantastic since PS3 runs pretty damned good on the Steam Deck, just needs that gyro, and it'll be golden!

Good job on the emulator so far, though. Love it!

**Comment by darthcircuit** [comment]
I agree. the Steam Deck has built in Gyro support and would greatly benefit from having support.

**Comment by DanHolli123** [comment]
Potential middle ground until Valve allows for a standard gyro output: allow mouse as basic gyro input as pitch and yaw

**Comment by eVenent** [comment]
Thanks to SDL2 controller API and Cemu, more and more emulators are receiving support for motion controls. Adding this support could enable native support for Steam Controller, Switch Pro Controller, Joy-Cons and even Android/iPhone smartphones (Cemuhooks). It's worth to consider to implement these features. At least SDL2.

**Comment by Megamouse** [comment]
I've enhanced the existing evdev handler to also be able to do motion controls.
See #12502

**Comment by Megamouse** [comment]
Implemented with the addition of SDL
