### ISSUE TITLE
Lightning Returns: Final Fantasy XIII [BLES01811] - Small sections of black flickering

### ISSUE THREAD

**Issue by bevanweiss** [RPCS3/rpcs3#8603]
Hi,

1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4947027/RPCS3.log.gz)

2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.

Three RSX captures from similar scenes, but hopefully still useful
[RSX Capture 1](https://drive.google.com/file/d/1OJrGp14JMLSlsKFJB6hlRB7tuJLTJ7UM/view?usp=sharing)
[RSX Capture 2](https://drive.google.com/file/d/1JPiKRvCCP1iW3Jgn2ZLX1lLEBGRKb4u3/view?usp=sharing)
[RSX Capture 3](https://drive.google.com/file/d/1V2R4JuI6rzkKbSx6jXsWwem7-ADbIPSN/view?usp=sharing)

[RenderDoc Capture](https://drive.google.com/file/d/150gIiVud3o4XWH1-6Csh2u3rR3lXR5Ks/view?usp=sharing)

3. Please attach screenshots of your problem.
Image below showing some of the black flickering sections, certain areas it gets worse.. like the tree of life is quite distracting.
![image](https://user-images.githubusercontent.com/2055446/87927435-89a74e80-cac6-11ea-8edd-9f3d9a1f9275.png)

4. Please provide comparison with real PS3.
PS3 shows clean edges / faces, no black flickering

5. Please provide your system configuration:
OS - Windows 10 Version 1909 (18363.959)
CPU - Intel Core i7-9750H
GPU - Nvidia GeForce RTX 2060 (Notebook, PCI\VEN_10DE&DEV_1F11&SUBSYS_08EA1028&REV_A1)
Driver version - 442.23
RAM - 8GB

Here's a short youtube video (from someone else) that also shows the black flickering.
https://www.youtube.com/watch?v=wMVeQ9EkKYg

Thanks

**Comment by bevanweiss** [comment]
Here's a short youtube video (from someone else) that also shows the black flickering.
https://www.youtube.com/watch?v=wMVeQ9EkKYg

**Comment by kd-11** [comment]
That looks to be z fighting, known to be an issue with nvidia cards.

**Comment by Asinin3** [comment]
This is an old issue that has been around since the game first started going ingame. I have an Nvidia GPU as well and experienced it. There's also an old github issue for this already https://github.com/RPCS3/rpcs3/issues/6886 which probably should be closed as this issue provides more info.

**Comment by GitArUs** [comment]
Probably not helpful information: it does not happen when "Shader Mode" it set to "Shader interpreter only" (very slow of course).

**Comment by Darkhost1999** [comment]
Please retest on latest master.

**Comment by GitArUs** [comment]
Still broken. Black patches (smaller and bigger) appear on moving surfaces or when camera is slightly moved.

![screenshot-2021_08_22_21_05_58](https://user-images.githubusercontent.com/12022598/130367744-5c047e71-972a-4b08-88c4-73d2f93979e6.png)
![screenshot-2021_08_22_21_06_01](https://user-images.githubusercontent.com/12022598/130367746-7ae2b706-0522-4547-b423-ae62a156e112.png)
![screenshot-2021_08_22_21_06_54](https://user-images.githubusercontent.com/12022598/130367748-b973fb71-8624-4cfd-87b3-000f24661406.png)
![screenshot-2021_08_22_21_07_00](https://user-images.githubusercontent.com/12022598/130367750-dcac0f4c-15b9-489c-a544-3b8780e9c8d9.png)

**Comment by GitArUs** [comment]
@kd-11 the cause of this must be similar like in case of Your issue #12752. I have changed the line:

`properties2.require_explicit_invariance = dev_caps.vendor_MESA`

to

`properties2.require_explicit_invariance = dev_caps.vendor_NVIDIA`

and that "fixed" the issue on nvidia for opengl render, but of course it still occurs when using vulkan.

**Comment by kd-11** [comment]
@GitArUs Thanks for checking.
I'll enable the invariant option unconditionally if "High" shader quality is selected. I think now that we have an option for that, we should make use of it.

**Comment by kd-11** [comment]
Test if https://github.com/RPCS3/rpcs3/pull/12868 fixes the problem.

**Comment by GitArUs** [comment]
Yes, looks good for both opengl and vulkan, with "Shader Quality" set to "High".

**Comment by kd-11** [comment]
Thanks for confirming.
