### ISSUE TITLE
RPCS3 crashes before relaunching itself after the updater finishes

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#8604]
In the past weeks me and mslow have both noticed a strange crash that happens right after the auto-updater finishes updating to the latest build. Right as I click on `OK` on the successful update message, the emulator crashes out. Once I hit `OK` on that message by Windows, RPCS3 restarts as if nothing happened during the update process.

I cannot reproduce this on my laptop, so this means some leftover files or configuration files are causing this issue. I'll try to isolate the reason later this week, but help would be appreciated.

RPCS3 version: ~~any~~ 0.0.11-10607 and up
OS: any / Windows

![](https://cdn.discordapp.com/attachments/512315214901936140/757051447912431626/unknown.png)

**Comment by dio-gh** [comment]
Still an issue, has to be some kind of file corruption. Might gonna try investigating it later this week if I don't forget.

**Comment by dio-gh** [comment]
Did some investigation, it's definitely not file corruption - I can repro it with a clean build perfectly. It was also noticed that while I get the crash 100% of the time reliably on pressing the `OK` button before RPCS3 restarts, @MsDarkLow gets it while in the download phase.

I do have non-latin characters in my username, but the path to RPCS3 doesn't contain any such characters; @MsDarkLow doesn't have any odd characters either, nor in his username. I'm on Win8.1, he's on Win10 - however, I cannot repro the crash on my Win10 machine.

**Comment by dio-gh** [comment]
Ok, turns out it's a regression from #8541 :p

**Comment by MsDarkLow** [comment]
I'm not sure when but I've noticed lately that I haven't been crashing when trying to update. **Probably** has been a month by now.

**Comment by dio-gh** [comment]
It disappeared for a while, but I just tested and can still repro after all.

**Comment by dio-gh** [comment]
Can't repro anymore.
