### ISSUE TITLE
Top Spin 4 Opponent Faces Render Incorrectly 

### ISSUE THREAD

**Issue by cooperate** [RPCS3/rpcs3#8605]
## Quick summary
The opponents face renders white lines.

## Details

The opponents characters face renders white lines. The first player renders correctly.

#### 1. Please attach RPCS3's log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4951585/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.

[BLUS30427_20200720230408_capture_2.zip](https://github.com/RPCS3/rpcs3/files/4951607/BLUS30427_20200720230408_capture_2.zip)

#### 3. Please attach screenshots of your problem.
![TS_4_render_issue_2](https://user-images.githubusercontent.com/13011766/88019048-bd41a300-cadd-11ea-87d3-59f40d0b891f.png)

#### 5. Please provide your system configuration:
OS Name	Microsoft Windows 10 Home
Version	10.0.19041 Build 19041
Ryzen 3700x
EVGA 2070 Super
Driver 451.67

**Comment by kd-11** [comment]
This game requires read color buffers to render correctly. I'm considering forcing this option on by default as it is rarely checked.
![image](https://user-images.githubusercontent.com/15904127/92787711-06152a00-f3b2-11ea-81be-1113ed0fa08b.png)
