### ISSUE TITLE
Tales of Graces f - Anti-Aliasing is broken

### ISSUE THREAD

**Issue by capriots** [RPCS3/rpcs3#8612]
Enabling Anti-Aliasing causes artifacts to appear in this game.
[Log](https://github.com/RPCS3/rpcs3/files/4962600/RPCS3.zip)
[RSX Capture](https://github.com/RPCS3/rpcs3/files/4962278/NPUB31133_20200722205806_capture.zip)

AA Auto:
![screenshot](https://user-images.githubusercontent.com/29807355/88223336-931bec80-cc67-11ea-8708-b5100768f804.png)

AA Disabled:
![screenshot2](https://user-images.githubusercontent.com/29807355/88223745-3e2ca600-cc68-11ea-9fc4-dbdb1cda8b46.png)

realhw:
![realhw](https://user-images.githubusercontent.com/29807355/88223351-9ca55480-cc67-11ea-9b90-bdd7e516b22f.png)

**Comment by kd-11** [comment]
Needs retesting from someone with a more modern GPU. MSAA has several workarounds to facilitate support for maxwell and kepler GPUs as they have some weird problems when doing resolve/unresolve.

**Comment by digitaldude555** [comment]
@capriots can you retest it?

**Comment by capriots** [comment]
Nothing changed on my GTX 970. It's the same on a laptop with a mobile GTX 1050.
[Log](https://github.com/RPCS3/rpcs3/files/6795772/Log.GTX.1050.zip)
[RSX Capture](https://github.com/RPCS3/rpcs3/files/6795773/RSX.Capture.GTX.1050.zip)

To test with an Intel UHD 620 I had to use an old build because #8741 broke graphics in this game when using this card. Here, edges are noticeably smoother with MSAA enabled but the exact same artifacts still appear and colors are all wrong.
[Log](https://github.com/RPCS3/rpcs3/files/6795789/Log.UHD.620.zip)
[RSX Capture](https://github.com/RPCS3/rpcs3/files/6795791/RSX.Capture.UHD.620.zip)

FYI there is a demo for this game on the Japanese PSN store in case anyone who doesn't have the game wants to test it.

**Comment by Megamouse** [comment]
Can confirm that there seems to be some weird grass on the road with MSAA

**Comment by kd-11** [comment]
Need some fresh captures for this. The provided ones can no longer be loaded.

**Comment by Megamouse** [comment]
[Tails_of_Graces_f.zip](https://github.com/RPCS3/rpcs3/files/7833311/Tails_of_Graces_f.zip)
![NPEB01288_screenshot_2021_12_15_23_27_21](https://user-images.githubusercontent.com/23019877/148646589-fa02c948-ab19-47e5-afa7-f16b8d85dd15.png)

You can see it in the top left corner of the path

**Comment by Megamouse** [comment]
Seems to be working with #11373. Haven't tested other games.

![NPEB01288_screenshot_2022_01_14_01_06_14](https://user-images.githubusercontent.com/23019877/149428332-cacb8b28-005c-4fe1-85b6-0900eb7788c0.png)

**Comment by capriots** [comment]
Glitchy pixels are gone for me too, but on my GTX 970 at least, there is still no actual AA applied. AA enabled or disabled looks identical. GPU usage is increased with AA enabled though, especially at higher resolutions.
It seems to be working on the UHD 620 in my laptop.

<details><summary>GTX 970 Screenshot</summary>
<p>

![screenshot_Graces_GTX970](https://user-images.githubusercontent.com/29807355/149588136-85b20213-f9e9-4c8a-9057-de1afbbc3ecf.png)

</p>
</details>

<details><summary>UHD 620 Screenshot</summary>
<p>

![screenshot_Graces_UHD620](https://user-images.githubusercontent.com/29807355/149590516-4e536b4f-5010-44f8-9f79-4578d47becc4.png)

</p>
</details>

[RSX capture](https://github.com/RPCS3/rpcs3/files/7873473/Graces_capture.zip)


I noticed the exact same issue in Tales of Xillia:

<details><summary>GTX 970 Screenshot</summary>
<p>

![screenshot_Xillia_GTX970](https://user-images.githubusercontent.com/29807355/149590852-5b33a138-d345-4947-be14-d32e5c8c73ce.png)

</p>
</details>

<details><summary>UHD 620 Screenshot</summary>
<p>

![screenshot_Xillia_UHD620](https://user-images.githubusercontent.com/29807355/149590829-5b2d4aec-8423-49e0-b67f-4178c608eb29.png)

</p>
</details>

[RSX capture](https://github.com/RPCS3/rpcs3/files/7873490/Xillia_capture.zip)
