### ISSUE TITLE
RPCS3 Crashes when HWInfo is open

### ISSUE THREAD

**Issue by kimberly990** [RPCS3/rpcs3#8614]
Newer builds of RPCS3 crash when HWInfo is open or opened. I tested 10666, 10667, and 10670. All of these builds crash. I tested 10610 and that build does not crash. 

![RPCS3 VS Error](https://user-images.githubusercontent.com/62084776/88243710-49c79f00-cc5f-11ea-8e25-36da40f644b2.png)

**Comment by Yahfz** [comment]
Works fine here..? I've tried all sorts of ways to get it to crash, opening Hwinfo before/after opening RPCS3, everything and it doesn't crash no matter what. Maybe you have some specific device that gets hooked by hwinfo and RPCS3 doesn't like that

**Comment by kimberly990** [comment]
I don't know, but it crashes consistently. Every single time

**Comment by digitaldude555** [comment]
@kimberly990 update the issue.

**Comment by kimberly990** [comment]
I no longer use RPCS3, and my hardware configuration has changed since this post. The theory was that it was specific to certain sets of hardware, at the time there had been similar reports on the RPCS3 discord with the same error code, but no one had connected the two as causing the issue. It was just speculation, so that wasn't included in the original post.
