### ISSUE TITLE
PS3 Launcher doesn't show up

### ISSUE THREAD

**Issue by jenci8888** [RPCS3/rpcs3#8615]
## Quick summary ##
It used to work opening PS3 Launcher before don't work.

## Details
Before that always work the PS3 Launcher opening, until now doesn't work which didn't show up window when emulation has started while running a PS3 Launcher program.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
Only culprit is #8415 .

#### 2. Please attach TWO logs:
Before: [RPCS3-before.log.gz](https://github.com/RPCS3/rpcs3/files/4964212/RPCS3-before.log.gz)
After: [RPCS3-after.log.gz](https://github.com/RPCS3/rpcs3/files/4964196/RPCS3-after.log.gz)

#### 4. Please attach screenshots of your problem.
![pcRMlJ5CFn](https://user-images.githubusercontent.com/40495799/88257746-c178e680-ccbe-11ea-87f4-d6ad2b71f39c.gif)

#### 6. Please provide your system configuration:
* OS: Windows 10 64-bit Enterprise 2004 build
* CPU: i5-4690k @ 4.5ghz
* GPU: Nvidia GTX 1050Ti 4GB
* Driver version: 451.48

**Comment by anseesaw** [comment]
Try this
roll back the nvdia drivers，
for example 446.14，or older!
======================
Or wait for a new qt version

**Comment by Megamouse** [comment]
Is this still an issue?

**Comment by jenci8888** [comment]
The issue has already resolved long ago (after 2021). I will close now.

**Comment by StillLindemann** [comment]
> The issue has already resolved long ago (after 2021). I will close now.

How did you solve this problem? I have the same problem with this PS3 Launcher v2.38.
