### ISSUE TITLE
[Feature Request] Add slowmo/turbo on-the-fly feature.

### ISSUE THREAD

**Issue by Zero-Tang** [RPCS3/rpcs3#8616]
## Quick summary
Set up two hot-keys - as a short-cut for in-game situation - to toggle slow-motion mode and turbo mode.

## Details
Like PCSX2 did, pressing Shift+Tab (by default, subject to user's change) will toggle on slow-motion - for example, 50% slower (subject to change by user's custom setting.) Pressing again will disable slow-motion mode. The rate value can be an irregular one - like 23%.
Duly note that I request this feature to be toggling on-the-fly - with some short-cuts to toggle clock rate in game. I'm not going to toggle the rate prior to starting the game.
This seems to be partial duplicate of issue #5114, though.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.
I suppose this feature will be listed in "Advanced" setting tab.

#### 2. Please tell us, why your feature is important to RPCS3.
Toggling slowmo smooths experience to cheat on timing-essential parts of games.
Toggling turbo helps to skip exhausting parts of games.

#### 3. Please attach screenshots of the feature implemented in other projects.
PCSX2 implemented this feature so it is easy for noobs like me to beat Drakengard Ending E within five attempts.
![pcsx2st](https://user-images.githubusercontent.com/37060901/88287787-6201f180-cd25-11ea-8137-57147145e1d6.PNG)

#### 4. Please provide your system configuration:
* OS Microsoft Windows 10 x64 LTSC-2019
* CPU AMD Ryzen Threadripper 2950X
* GPU Leadtek WinFast Nvidia GeForce GTX1080Ti
* Driver version 451.67
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by AniLeo** [comment]
And how do you know exactly what does the game require to run at half speed? This is not PS2

**Comment by Zero-Tang** [comment]
This depends on how user set the rate. If player thinks that a certain rate is hard, tweak it slower. Otherwise, tweak it faster.
Half-speed can be a default option as the screenshot demonstrated above.

**Comment by AniLeo** [comment]
That has nothing to do with the question, how do you know exactly what to change in order for the game to run at different speeds?

What you want is done through changing VBlank or Clocks Scale settings, and if neither of those work you need to make a specific game patch.

**Comment by Zero-Tang** [comment]
I am looking for a "toggle on-the-fly" feature - that is, I want a hot-key to toggle clock-scale in game. This is the reason I mention it seems to be partial duplicate with #5114

**Comment by AniLeo** [comment]
Then that has nothing to do with what you asked here, you want shortcuts to change specific settings while in-game

**Comment by Zero-Tang** [comment]
I think I failed to explain what does phrase "on the fly" mean. I edited the issue in order to convey my request.

**Comment by AniLeo** [comment]
I think you don't understand, there's no way of having a setting that globally speeds or slows a game, therefore the "slowmo" and "turbo" mentions on this request don't make sense - as I see it you want hotkeys for settings in general

**Comment by Zero-Tang** [comment]
In this regard, I shall close the issue in that the feature I requested is impossible to be implemented as you duly pointed.
