### ISSUE TITLE
[NPUB30988] DMC3 surface invalidation regression

### ISSUE THREAD

**Issue by dyno0** [RPCS3/rpcs3#8619]
Since #8479 orbs, flames and some other objects can be seen through walls.
Master build prior to the aforementioned pr works as intended.

![broke](https://user-images.githubusercontent.com/54358666/88343947-e020c100-cd42-11ea-899f-3733c7d80b47.png)
![works](https://user-images.githubusercontent.com/54358666/88343956-e3b44800-cd42-11ea-8ece-6d8769dbea65.png)

edit:

[NPUB30988_20201018180301_capture.zip](https://github.com/RPCS3/rpcs3/files/5397791/NPUB30988_20201018180301_capture.zip)
[RPCS3broke.log.gz](https://github.com/RPCS3/rpcs3/files/5397792/RPCS3broke.log.gz)
[RPCS3good.log.gz](https://github.com/RPCS3/rpcs3/files/5397793/RPCS3good.log.gz)

**Comment by kd-11** [comment]
RSX captures and log files are missing.

**Comment by Asinin3** [comment]
Capture and log are there now. But no comment for notifying that this was done. Removed label.
I tested and can confirm the issue is still occurring on latest master.
