### ISSUE TITLE
Stuck after water horser crab

### ISSUE THREAD

**Issue by allanjales** [RPCS3/rpcs3#8624]
I keep stuck on the scene after the first part of the water horse crab boss  on **God of War III [BCES00510 - 1.03]**. At some point audio keeps repeating until next cutscene is executed. Next a loading screen appears and still. Nothing happens.

Scene were I keep stucked:

![Screenshot of the scene](https://user-images.githubusercontent.com/30681577/88449090-868bc580-ce1a-11ea-880d-6e393aae5bc0.png)

To be clear what I am talking, I recorded a [video showing the bug and uploaded on youtube](https://youtu.be/-PGM1gFF7Tc) 

My disk usage is not increased at this time (always below 5%, usually 0%) so it is not trying to read anything hard... I do not know what may causing this. Is that any bug on RPCS3 in my specific system configurations?

---

System config:
Windows 10
Intel i5-9600K
16 GB RAM
GTX 1050 Ti (driver: 451.67)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4974917/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
A lot of settings were changed, some might cause issues. Test again with Default settings (+Vulkan and WCB)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by allanjales** [comment]
I have already requested help. Seems like it's a neew problem. Also I applied the new config and does not work. I replaced the files of the game but the problem persists.  Here is the new log. I did not find anything about this bug.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4979735/RPCS3.log.gz)
