### ISSUE TITLE
RPCS3 when run with --headless still produces exception error dialogs

### ISSUE THREAD

**Issue by bevanweiss** [RPCS3/rpcs3#8645]
## Quick summary
Expectation is that when run with '--headless' command line argument, that all feedback would be via the same command line, and a windows dialog would be undesired behaviour.

## Details
I've been looking to get the autotests back operational... and potentially expanding on them, however when running some of the existing test cases in this repo (https://github.com/RPCS3/ps3autotests) they are throwing exceptions, as shown below:
![image](https://user-images.githubusercontent.com/2055446/88624025-97be2600-d0e9-11ea-8588-52de26e35689.png)

This obviously results in an inconvenience for an automated (CLI) test since clicking on the 'OK' button is very difficult.
When run headless, I believe we should just be throwing these error messages out on stderr

Example of command line provided was:
rpcs3.exe --headless D:\Projects\ps3autotests\tests/lv2/sys_semaphore\sys_semaphore.ppu.elf

which is badly formed (my bad Pythoning), but raises a separate issue I think.

**Comment by bevanweiss** [comment]
Headless seemed like the right argument at the time... but --no-gui seems to work for the purpose required at the moment.
It looks like headless is a bit short of implementation in the code-base.

I'm unsure what the intended difference between --headless and --no-gui is.
My naive interpretation was that --headless would have produced no graphical output (output only via commandline [stdout/stderr] / TTY stream / filesystem), and that --no-gui would have simply not shown the UI interface to launch applications (i.e. application path would need to be passed via command line, but would still create a graphical window to render to).

**Comment by Megamouse** [comment]
No-gui only shows the game window if necessary (useful for 3rd party launchers).
Headless is supposed to run without any user interaction and does not create any dialogs whatsoever
