### ISSUE TITLE
`RPCS3_ROOT/patches/*_patch.yml` patches are not applied on game launch

### ISSUE THREAD

**Issue by ZeeWanderer** [RPCS3/rpcs3#8665]
Patches contained in `RPCS3_ROOT/patches/*_patch.yml` are not applied on game launch despite being enabled.

On emu init `patch_engine::m_map` is populated by `patch_engine::append_global_patches` and on title load it is populated by `patch_engine::append_title_patches` and both do not load `RPCS3_ROOT/patches/*_patch.yml` patches.
On the other hand `patch_manager::m_map` is in fact also populated from `RPCS3_ROOT/patches/*_patch.yml` on patch manager GUI load so these patches can be selected and enabled but since they are not contained in `patch_engine::m_map` they do not pass [check](https://github.com/RPCS3/rpcs3/blob/master/Utilities/bin_patch.cpp#L683) and thus are not actually applied.

**Comment by Megamouse** [comment]
Show me your patches folder

**Comment by ZeeWanderer** [comment]
<details>
  <summary>File list</summary>
Directory: E:\PS3Emu\Source\rpcs3\bin\patches

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            8/1/2020  5:44 PM              8 __patches.hash
-a---            8/1/2020  5:44 PM            935 Army of TWO_ The 40th Day_patch.yml
-a---            8/1/2020  5:44 PM            758 Asura's Wrath_patch.yml
-a---            8/1/2020  5:44 PM           1539 Dark Souls II_patch.yml
-a---            8/1/2020  5:44 PM           3090 Dark Souls_patch.yml
-a---            8/1/2020  5:44 PM           8517 Demon's Souls_patch.yml
-a---            8/1/2020  5:44 PM            448 Destroy All Humans! Path of the Furon_patch.yml
-a---            8/1/2020  5:44 PM           9701 Disable SPU MLAA_patch.yml
-a---            8/1/2020  5:44 PM           1614 DJ Hero 2_patch.yml
-a---            8/1/2020  5:44 PM           2861 Drakengard 3_patch.yml
-a---            8/1/2020  5:44 PM           1041 Folklore_patch.yml
-a---            8/1/2020  5:44 PM            491 Genji_ Days of the Blade_patch.yml
-a---            8/1/2020  5:44 PM            307 Gran Turismo 5_patch.yml
-a---            8/1/2020  5:44 PM            297 Gran Turismo HD Concept_patch.yml
-a---            8/1/2020  5:44 PM            387 Grand Theft Auto IV_patch.yml
-a---            8/1/2020  5:44 PM            872 Hatsune Miku_ Project DIVA Dreamy Theater_patch.yml
-a---            8/1/2020  5:44 PM           3266 Hatsune Miku_ Project Diva F 2nd_patch.yml
-a---            8/1/2020  5:44 PM           1396 Hatsune Miku_ Project Diva F_patch.yml
-a---            8/1/2020  5:44 PM            702 Iron Man_patch.yml
-a---            8/1/2020  5:44 PM            870 JoJo's Bizarre Adventure_ All Star Battle_patch.yml
-a---            8/1/2020  5:44 PM            694 JoJo's Bizarre Adventure_ Eyes of Heaven_patch.yml
-a---            8/1/2020  5:44 PM           1711 Kingdom Hearts HD 1.5 ReMIX_patch.yml
-a---            8/1/2020  5:44 PM            838 Kingdom Hearts HD 2.5 ReMIX_patch.yml
-a---            8/1/2020  5:44 PM            269 LittleBigPlanet 2_patch.yml
-a---            8/1/2020  5:44 PM            947 Lollipop Chainsaw_patch.yml
-a---            8/1/2020  5:44 PM            312 Metal Gear Solid 2_ Sons of Liberty - HD Edition_patch.yml
-a---            8/1/2020  5:44 PM           1109 Motorstorm_ Pacific Rift_patch.yml
-a---            8/1/2020  5:44 PM            917 Motorstorm_patch.yml
-a---            8/1/2020  5:44 PM           4929 NieR_patch.yml
-a---            8/1/2020  5:44 PM          33697 Persona 5_patch.yml
-a---            8/1/2020  5:44 PM            292 Ratchet & Clank_ Quest for Booty_patch.yml
-a---            8/1/2020  5:44 PM           1184 Ratchet & Clank_ Tools of Destruction_patch.yml
-a---            8/1/2020  5:44 PM            384 Red Dead Redemption_patch.yml
-a---            8/1/2020  5:44 PM            928 Resistance 2_patch.yml
-a---            8/1/2020  5:44 PM           1152 Resistance_ Fall of Man_patch.yml
-a---            8/1/2020  5:44 PM            455 Sengoku Basara 4_ Sumeragi_patch.yml
-a---            8/1/2020  5:44 PM            929 Shadows of the Damned_patch.yml
-a---            8/1/2020  5:44 PM            690 Sonic Adventure_patch.yml
-a---            8/1/2020  5:44 PM           1570 Sonic The Hedgehog_patch.yml
-a---            8/1/2020  5:44 PM           6014 Sonic Unleashed_patch.yml
-a---            8/1/2020  5:44 PM            340 Space Channel 5_ Part 2_patch.yml
-a---            8/1/2020  5:44 PM            514 The Elder Scrolls IV_ Oblivion_patch.yml
-a---            8/1/2020  5:44 PM           5956 The ICO & Shadow of the Colossus Collection_patch.yml
-a---            8/1/2020  5:44 PM          15357 The Last of Us_patch.yml
-a---            8/1/2020  5:44 PM          17473 Uncharted 2_ Among Thieves_patch.yml
-a---            8/1/2020  5:44 PM          18963 Uncharted 3_ Drake's Deception_patch.yml
-a---            8/1/2020  5:44 PM           2375 Uncharted_ Drake's Fortune_patch.yml
-a---            8/1/2020  5:44 PM            643 Unreal Tournament 3_patch.yml
-a---            8/1/2020  5:44 PM            332 WipEout HD_patch.yml  

</details>

**Comment by Megamouse** [comment]
Well. You aren't using the proper nomenclature.
It has to be something like:
BLES12345_patch.yml

**Comment by ZeeWanderer** [comment]
Ok then, but some patches can be grouped into files by purpose and not by title. For example all title spu mlaa patches. They won't work unless imported. And since wether nomenclature is followed or not patches are visible in gui which makes this approach nonintuitive. Besides, i looked through patch wiki and did not found nomenclature description.
