### ISSUE TITLE
Firmware Installation Failed (Access Violation)

### ISSUE THREAD

**Issue by Hackerknownas4** [RPCS3/rpcs3#8673]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5013241/RPCS3.log)

## Quick summary
Upon install of the newest Firmware Rpcs3 crashes around 20%-30% (Tar contents invaild)

## Details
![image](https://user-images.githubusercontent.com/35648348/89135872-85375880-d4fe-11ea-8316-dc8fd2d64985.png)
Assuming that this was due to a file that was dead I both reinstalled the EMU and redownloaded the firmware with no change
#### 1. Please attach RPCS3's log.
* Run the game until you find the issue.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc. 

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc. 
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 5. Please provide your system configuration:
* Windows 10
* i5-7500
* 1050-ti
* 451.67

**Comment by AniLeo** [comment]
If this happens then the update is corrupt, even if you've already redownloaded it. You need to checksum it and make sure it's not.
If you can't get it to work still, ask for support on one of the appropriate platforms.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
