### ISSUE TITLE
[Feature Request] stream for PSV

### ISSUE THREAD

**Issue by liangx8rx** [RPCS3/rpcs3#8678]
PS3 & PS4 can use PSV to control，is the emulator provide yet？

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
