### ISSUE TITLE
Fifa Street freezing at the starting load screen (NPEB00822)

### ISSUE THREAD

**Issue by closewall** [RPCS3/rpcs3#8686]
## Quick summary
Fifa Street (EU) freezes at the opening loading screen.

## Details

Once I get past the opening splash screen, it freezes at the next load screen and my CPU gets locked at 100%.

* Attach the log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5023240/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.
https://i.imgur.com/kqIEz19.jpg

#### 5. Please provide your system configuration:
Visible in the log.
i5-8600K
RTX 2070 Super.

#### Please include.
* Anything else you deem to be important

**Comment by MSuih** [comment]
Please validate your game files, some of them seem to be missing.

**Comment by incognitoh** [comment]
this happens only when the 1.01 is installed iirc.  try 01.00, should work

**Comment by Amudon** [comment]
I have the same issue
