### ISSUE TITLE
[Feature Request] Unofficial online servers for any game

### ISSUE THREAD

**Issue by Hackerknownas4** [RPCS3/rpcs3#8690]
## Quick summary
(I am aware that Online functions are beginning to be enabled)
Unofficial online servers for any game

## Details
A separate client or something built in to RPCS3 like what Dolphin has. It would allow friends to connect to each other privately or just allow anyone in the RPCS3 community to host servers for any game that allows it. Persona 5,Dark Souls etc, for dedicated servers

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.

#### 4. Please provide your system configuration:
* Windows 10
* R9 3900x
*1070ti
*451.67
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by AniLeo** [comment]
P2P servers are already being implemented on #8663 , you can create lobbies and join other people's lobbies if the game allows you to do so

Persona 5 doesn't require any custom server, just unimplemented sceNp functionality

Games that require extra servers besides PSN servers require those to be created outside of RPCS3, such as desse for Demon's Souls

I don't see anything else that could be implemented on RPCS3 itself here

**Comment by dio-gh** [comment]
Yes, this ticket is pretty much non-sensical. Either should be closed or the RPCN PR should close it on merge.
