### ISSUE TITLE
Sonic Unleashed - VM: Access violation reading location 0x0 (unmapped memory)

### ISSUE THREAD

**Issue by pastelaura** [RPCS3/rpcs3#8693]
I can't even boot into the main menu of Sonic Unleashed. I only get the loading screen after booting up the game and then it freezes after a couple of seconds. 

My specs:
CPU: Intel core i7-9700KF
RAM: 32GB
GPU: Radeon RX 5700 XT 8GB
OS: Windows 10

[Log - Sonic Unleashed.txt](https://github.com/RPCS3/rpcs3/files/5028391/Log.-.Sonic.Unleashed.txt)

**Comment by bevanweiss** [comment]
Are you sure the dump was good?
E {PPU[0x1000002] Thread (_fs_aio_thread) [0x02c61174]} EDAT: EDAT: Block at offset 0x110 has invalid hash!
E {PPU[0x1000002] Thread (_fs_aio_thread) [0x02c61174]} EDAT: Error Decrypting data

RPCS3 had issue decrypting the data.

**Comment by MSuih** [comment]
This is text copypasted from emulator window. You need to provide a proper log file.

**Comment by pastelaura** [comment]
> Are you sure the dump was good?
> E {PPU[0x1000002] Thread (_fs_aio_thread) [0x02c61174]} EDAT: EDAT: Block at offset 0x110 has invalid hash!
> E {PPU[0x1000002] Thread (_fs_aio_thread) [0x02c61174]} EDAT: Error Decrypting data
> 
> RPCS3 had issue decrypting the data.

It should be a good dump, but just do be sure, I re dumped it and had the same issue with the brand new dump as well.

**Comment by pastelaura** [comment]
> This is text copypasted from emulator window. You need to provide a proper log file.

How would I get the proper log file?

**Comment by RainbowCookie32** [comment]
Upload RPCS3.log from the emulator's folder after the crash

**Comment by RainbowCookie32** [comment]
Works fine here on latest master
![image](https://user-images.githubusercontent.com/16805474/89488308-05b7bc80-d77e-11ea-8174-6f13c0e32a68.png)

**Comment by bevanweiss** [comment]
@pastelaura what BD reader did you use, and what program to do the dumping?
It sounds like it's not an issue with rpcs3, given there is a 'works for me' report from @RainbowCookie32 
So... I think you should close this ticket, and investigate the dump situation to get that working (and validating) correctly.

**Comment by RainbowCookie32** [comment]
You might want to come to [our Discord server](https://discord.me/RPCS3), where we can provide help fixing the issue.

**Comment by pastelaura** [comment]
> Upload RPCS3.log from the emulator's folder after the crash

I actually got it working now. Even though I already had the latest build, I went ahead and re-downloaded it and then re-added the game, and doing that seemed to make it work. Have no idea why it wouldn't work on the latest build that I already had installed, but oh well I suppose.

**Comment by Mathieu015** [comment]
I have the same issue since version 0.0.33-17029. Going back to version 0.0.33-17024 doesn't give me that error and makes the game not working.
