### ISSUE TITLE
Modnation Racers - Tutorial Race cannot be completed due to a glitch wall

### ISSUE THREAD

**Issue by closewall** [RPCS3/rpcs3#8695]
## Details

When doing the tutorial race, a big gray glitch wall blocks you from progressing half way through the race. It has a collider so you cannot drive through it. The other computers seem to be able to explode themselves driving into it, but it's impossible for the player.

This makes accessing the rest of the game impossible because it's impossible to get past the wall.

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5029544/RPCS3.log.gz)

* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc. 

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 5. Please provide your system configuration:
Windows 10
RTX 2070 Super
i5-8600K

#### Please include.
* Anything else you deem to be important

**Comment by RainbowCookie32** [comment]
You need to enable Write Color Buffers
