### ISSUE TITLE
Tekken Tag Tournament 2 Feng Wei Texture Bug

### ISSUE THREAD

**Issue by ArmaKu** [RPCS3/rpcs3#8701]
## Quick summary
I have been told to use accurate xfloat to fix the texture problem for feng but it still doesnt work, the rcps3 log was too big so i cant attach it

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.
![IMG_2123 1](https://user-images.githubusercontent.com/69329658/89593812-fa5ba400-d804-11ea-8d9b-a53b0f5acbe1.JPG)

#### 4. Please provide comparison with real PS3.
nothing
#### 5. Please provide your system configuration:
* OS: Windows 10
* CPU: Intel core i7-6900K
* GPU: Gtx 1080
* Driver version: geforce driver 451.67
* etc.

**Comment by jokoputera** [comment]
Rsx and log will be helpful

**Comment by ArmaKu** [comment]
> Rsx and clear cache and log may put in Google Drive or something

@jokoputera so apprently one of the new versions with accurate xfloat it fixes this issue, dont disable accurate xfloat but thanks for commenting
![Ee1k8_nVoAAuwVC](https://user-images.githubusercontent.com/69329658/89675715-43603680-d89f-11ea-9220-be4d13378e08.jpg)
