### ISSUE TITLE
Regression: Cannot delete save data in Sly 2 [NPUA80664] (#7623)

### ISSUE THREAD

**Issue by jeremybris** [RPCS3/rpcs3#8708]
## Quick summary
I can not delete save data correctly in v0.0.8-9755, PR #7623, and after in Sly 2 [NPUA].

## Details

| RPCS3 Version | RPCS3 Commit | Log | Description & Screenshot(s) |
| ------------- | ------------- | ------------- | ------------- |
| v0.0.8-9754 and Before  | -------------  | [RPCS3 1.log](https://github.com/RPCS3/rpcs3/files/5046033/RPCS3.1.log) | Deletes save data correctly. The save in slot 2 is gone. ![Capture2](https://user-images.githubusercontent.com/11889359/89717327-88f62f80-d983-11ea-9600-3daf8ac4d22b.PNG) |
| v0.0.8-9755 and After | [#7623](https://github.com/RPCS3/rpcs3/pull/7623) | [RPCS3 2.log](https://github.com/RPCS3/rpcs3/files/5046035/RPCS3.2.log) | **_Does not_** delete save data correctly. The save in slot 2 is still there. This message appears after trying to delete the save in slot 2 twice. ![Capture](https://user-images.githubusercontent.com/11889359/89717330-94495b00-d983-11ea-8e2b-a810d1d3520a.PNG) |

## Other Details
* If I restart the game, the save data is correctly not there, after deletion.
![Capture3](https://user-images.githubusercontent.com/11889359/89717390-46812280-d984-11ea-9325-5deed276332e.PNG)
* Sly 2 has another, save data bug where you can not overwrite your old saves. I think that is unrelated.

#### System Configuration:
* OS - An atari Jaguar
* CPU - A potato
* GPU - A lemon

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by Mew8000** [comment]
@AniLeo @Megamouse @kd-11Yeah guys fixed for save files bug in sly 2 go to adv tab and turn SPURS Threads for  Unlimited to 3 and once do that the game is playable saving bug is fixed. It has done by gaming time

**Comment by Mew8000** [comment]
Can we close this problem to because fixed for it by SPURD threads to 3.

**Comment by jeremybris** [comment]
No, the bug's still there with SPURS threads to 3.

![Capture142](https://user-images.githubusercontent.com/11889359/124361726-91400480-dbfe-11eb-8a6d-682beeac0e18.PNG)

![Capture152](https://user-images.githubusercontent.com/11889359/124361731-969d4f00-dbfe-11eb-8ebf-b57e54e0fac1.PNG)
