### ISSUE TITLE
Linux: Checkboxes not appearing in Patch Manager 

### ISSUE THREAD

**Issue by slapnuts99** [RPCS3/rpcs3#8716]
## Quick summary
When I access the Patch Manager menu with the default stylesheet, the checkboxes are not visible.

![screenshot 19](https://user-images.githubusercontent.com/69492745/89850789-fad3a200-db58-11ea-958b-52c26454fe39.jpg)

* OS: Arch Linux x86_64
* CPU: AMD Ryzen 7 3700X
* GPU: RTX 2070 Super 
* Driver version: 450.57

**Comment by AniLeo** [comment]
### Windows
Works regardless of theme

![image](https://user-images.githubusercontent.com/10283761/89851121-a72a7e00-db83-11ea-9d63-e968bf0b397b.png)

---

### Manjaro
Default spreadsheet: Displays properly
![image](https://user-images.githubusercontent.com/10283761/89851141-b3aed680-db83-11ea-90a3-8ee0bfb07474.png)

Other themes: Displays without any tick inside when it's ticked
![image](https://user-images.githubusercontent.com/10283761/89851183-c6c1a680-db83-11ea-904b-7eb543b1a755.png)


**OS: Manjaro 20.0.3 Gnome (Default theme)**

Probably requires specific styling override on the emulator itself and possibly all the stylesheets to fix this.

**Comment by HerrHulaHoop** [comment]
> Other themes: Displays without any tick inside when it's ticked

If you look closely, the tick is present.

**Comment by Megamouse** [comment]
@AniLeo you need to do the same for QTreeWidget as you did for #lleList

**Comment by Megamouse** [comment]
is this still an issue?

**Comment by HerrHulaHoop** [comment]
Closed due to inactivity.
