### ISSUE TITLE
RPCS3 freezes in DeS loading screen

### ISSUE THREAD

**Issue by whsmk54** [RPCS3/rpcs3#8717]
**Issue:**
I've been playing Demon's Souls for 2 weeks, but now I'm trying to start the game and it freezes on the loading screen right before the intro video. The only thing I can do is kill the process in the task manager. Yesterday everything was fine, I didn't update anything, I just went to bed, and today the game won't start

![image](https://user-images.githubusercontent.com/55182172/89922381-629cf200-dc18-11ea-9339-aab5874f66ec.png)

**RPCS3's log file:**

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5058059/RPCS3.log)

**System configuration:**

Windows 10 2004
Ryzen 5 2600
RX 590

**Comment by RainbowCookie32** [comment]
Can't reproduce here on latest master, game boots fine.
![Screenshot_20200811_132931](https://user-images.githubusercontent.com/16805474/89923304-c6063000-dbd6-11ea-970a-dc045efab3d2.png)
Try removing disk cache from `File->All Titles->Remove disk cache`. It can cause issues sometimes

**Comment by whsmk54** [comment]
> Can't reproduce here on latest master, game boots fine.
> ![Screenshot_20200811_132931](https://user-images.githubusercontent.com/16805474/89923304-c6063000-dbd6-11ea-970a-dc045efab3d2.png)
> Try removing disk cache from `File->All Titles->Remove disk cache`. It can cause issues sometimes

didn't help

**Comment by Whatcookie** [comment]
Post the contents of TTY.log here, in your log it says the game is writing something there

**Comment by whsmk54** [comment]
> Post the contents of TTY.log here, in your log it says the game is writing something there

There's nothing there.
I have cleared all the cache in "all titles" section, now RPCS3 freezes on compiling ppu modules

**Comment by whsmk54** [comment]
I don’t understand what could happened, I didn't update anything, installed only Acronis disk image

**Comment by illusion0001** [comment]
Check hdd cache, dev_hdd1

**Comment by whsmk54** [comment]
> Check hdd cache, dev_hdd1

I cleared1 the dev_hdd folder

**Comment by RainbowCookie32** [comment]
Did you find a solution for the issue? Otherwise you should keep this open until it's solved

**Comment by RainbowCookie32** [comment]
> Post the contents of TTY.log here, in your log it says the game is writing something there

Reconstructing a bit from the log:

```
EDGE ZLIB ERROR: inflate error (-5)
===================================
Dump CompBuffer Size[5452] ExpectedUncompSize[416]
-----------------------------------
ErrorMsg[No Error Msg]
avail_in[5315] total_in[137] avail_out[0]
```

So there's clearly something on TTY. The printing goes on for a lot longer, but I'm not going to go through who knows how many lines of hex dump.

**Comment by whsmk54** [comment]
I solved the problem: completely deleted Acronis True Image 2020.
