### ISSUE TITLE
Regression: Multiple Games Crashing After v0.0.11-10625

### ISSUE THREAD

**Issue by jeremybris** [RPCS3/rpcs3#8719]
## Quick summary
When "Exit RPCS3 when process finishes"(config>emulator tab) is checked, it causes crashing during PPU Compilation in Call of Duty 3, 2010 FIFA World Cup, Splinter Cell: Blacklist, and others.

## Details
In v0.0.11-10625 and after, so #8550 @Megamouse, when you check "Exit RPCS3 when process finishes"(config>emulator tab), it will crash the emulator during PPU compilation in certain games. It's because the emulator thinks the process is over and closes itself before PPU compilation can ensue. Please let me know if I have misspoken.

#### Known Effected Games:
- Call of Duty 3
- 2010 FIFA World Cup
- Splinter Cell: Blacklist
- Metal Gear Solid 4 (Digital)
- Red Dead Redemption: Game of the Year Edition [BLES01294]
- Resistance: Fall of Man
- Call of Duty 4: Modern Warfare

#### System Configuration:
* OS - Windows 10
* CPU - AMD
* GPU - RTX

**Comment by jacdx** [comment]
Still happening in .13
