### ISSUE TITLE
The Last Guy [NPEA00080] randomly freezing, sound continues

### ISSUE THREAD

**Issue by oliacym** [RPCS3/rpcs3#8723]
Game: The Last Guy [NPEA00080]
After a seemingly random amount of time playing, the game will freeze. Any audio currently playing will loop. No inputs are recognised. If the pad is rumbling, it will continue. I am able to Alt+F4 to exit the emulator.

System Config:
Windows 10
Intel(R) Core(TM) i7-9700 CPU @ 3.00 GHz
GeForce GTX 1660 Ti
Version 451.67

Log here: [RPCS3_Log.zip](https://github.com/RPCS3/rpcs3/files/5069673/RPCS3_Log.zip)

**Comment by digitaldude555** [comment]
@oliacym any update?

**Comment by oliacym** [comment]
Actually there was a development - I set PPU decoder to Interpreter (fast) and the freezng hasn't happened since.

**Comment by benderscruffy** [comment]
this can be closed
