### ISSUE TITLE
[Feature Request] Proper support for anamorphic video modes

### ISSUE THREAD

**Issue by NicknineTheEagle** [RPCS3/rpcs3#8725]
480p and 576p are anamorphic video modes on a real PS3, they're used on SDTVs (CRTs) which rescale the image to fill the screen (which is usually 4:3 but there are some 16:9 SDTVs). RPCS3 simply displays these modes in pixel aspect ratio which is incorrect and makes the game appear distorted. You can get around this by forcing a specific window size and enabling "Stretch to Display Area" but this is far from optimal.

Example from SONIC THE HEDGEHOG 4 Episode I [NPEB00153] (running in 480p 4:3):
![image](https://user-images.githubusercontent.com/6665256/90166286-a6bbfe00-dda2-11ea-9044-49c9a85bc8bf.png)

Correct aspect ratio:
![image](https://user-images.githubusercontent.com/6665256/90166448-f13d7a80-dda2-11ea-8c96-a8156cb9f214.png)

Same game running in 720p:
![image](https://user-images.githubusercontent.com/6665256/90166547-1af6a180-dda3-11ea-85a9-2d647932f1b7.png)

**Comment by kd-11** [comment]
This is a known issue, but its rather complicated to implement. Some games don't render the full surface requested (letterboxing) and not enforcing pixel-correct aspect ratio becomes very tricky. Needs some investigation to determine the best way to stretch any output image depending on a variety of inputs.
