### ISSUE TITLE
Uncharted 3 [BCES01175] Splitscreen weird white Buffers?

### ISSUE THREAD

**Issue by Alessioc3l** [RPCS3/rpcs3#8731]
## Quick summary
When my friend and i were playing Uncharted 3 Splitscreen we noticed some weird white lights that appeared if we shot our weapon or on some light spots.

## Details
This only happens if we start Splitscreen. Before that everything works fine. Once we played splitscreen it will be like that the whole game. It occurs on almost every light on every map. I have tried disabling some of the patches but nothing worked.
#### 1. RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5074175/RPCS3.log)

#### 2. RSX capture (graphical issue)
https://drive.google.com/file/d/1ldqJeLXehZNlo59NAj8VRcdGEoVlSoHs/view?usp=sharing
https://drive.google.com/file/d/1pTTm_Q23J7cQie8QPMBxAKUZ9Y8iF7tz/view?usp=sharing
here i have 2 RSY captures
#### 3. Screenshots
![graphic issue_1](https://user-images.githubusercontent.com/69675939/90244258-b1bd6f80-de30-11ea-9b07-d7fef4c852c8.png)
![graphic issue_2](https://user-images.githubusercontent.com/69675939/90244283-be41c800-de30-11ea-8281-2abe7236ecd1.png)
![graphic issue_3](https://user-images.githubusercontent.com/69675939/90244291-c26de580-de30-11ea-8087-6ac7ea6769f5.png)
here are some examples

#### 4. My System:
* OS: Windows 10 Home
* CPU: Ryzen 7 3700x
* GPU: Radeon Rx580
* RAM: 16GB DDR4 3200
* MB: X570 Aorus Elite
* SSD: Samsung 970 evo plus

#### 5. Additional information:
I am using every setting of the Patch that is provided on the site.
Also the Game Version is 01.19
![RPCS3 settings](https://user-images.githubusercontent.com/69675939/90245297-b2ef9c00-de32-11ea-8af6-e534acc56deb.png)
![RPCS3 settings1](https://user-images.githubusercontent.com/69675939/90245306-b551f600-de32-11ea-8a27-d08feb7ca9ce.png)
![RPCS3 settings2](https://user-images.githubusercontent.com/69675939/90245314-b97e1380-de32-11ea-9bf2-a0b8814c0a1c.png)
![RPCS3 settings3](https://user-images.githubusercontent.com/69675939/90245321-bc790400-de32-11ea-8f7e-71b604be2fb2.png)

**Comment by illusion0001** [comment]
Thanks for reporting, will fix in upcoming patch.

**Comment by Xcedf** [comment]
@Alessioc3l are you using cheat engine or somne other tool?

**Comment by Alessioc3l** [comment]
> @Alessioc3l are you using cheat engine or somne other tool?

No.

**Comment by illusion0001** [comment]
Please test @Alessioc3l [patch.yml](https://cdn.discordapp.com/attachments/319224795785068545/744493460811415612/patch.yml)

**Comment by Alessioc3l** [comment]
@illusion0001 yes the patch fixed the problem. Thank you very much!

**Comment by Alessioc3l** [comment]
Well it works but now the game crashes frequently
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5080567/RPCS3.zip)

**Comment by nitroos-ai** [comment]
Is this still an issue?

**Comment by Darkhost1999** [comment]
Technically the crashes are a separate issue. This issue was already closed with "it works" just needs a separate ticket for the separate issue

**Comment by Megamouse** [comment]
closing as original issue is fixed
