### ISSUE TITLE
[Feature Request] Better Debugger

### ISSUE THREAD

**Issue by theclub654** [RPCS3/rpcs3#8737]
I would pay top dollar to have a way better debugger with a more better memory viewer with memory breakpoint support and with a callstack you know just like the one on pcsx2

**Comment by elad335** [comment]
theres a callstack - on ppu's.
And theres a memory viewer just for memory viewing in Utilities.
Only memory breakpoints is a valid point here.

**Comment by theclub654** [comment]
but its very shitty

**Comment by elad335** [comment]
This issue is not very unhelpful because it doesnt state specific goals to be acheived. Saying current debugger "is very shitty" and we want "a way better debugger" doesn't mean anything to me to me either.
