### ISSUE TITLE
(BLES00424) Harry Potter and the Half-Blood Prince - Light issue

### ISSUE THREAD

**Issue by Cursinal** [RPCS3/rpcs3#8740]
While Harry is running or flying a broom (Motion Blur) and in cutscenes (Depth Of Field) lights e.g. Lumos spell or fire is going through the walls and any other object. I suppose It is happening because of blur as I mentioned in brackets but still I have no idea how to fix It. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5080997/RPCS3.log.gz)

Here's RSX
https://drive.google.com/file/d/1erBpA9vVmnJcHg4JbRLaZdIi47SCKty2/view?usp=sharing

not running
![image](https://user-images.githubusercontent.com/69763060/90339269-fba08400-dfef-11ea-85e8-fe057cd85762.png)
![image](https://user-images.githubusercontent.com/69763060/90339402-cba5b080-dff0-11ea-9f73-436ec9d9eb38.png)

running
![image](https://user-images.githubusercontent.com/69763060/90339272-fd6a4780-dfef-11ea-9858-1990e2e44b09.png)
![image](https://user-images.githubusercontent.com/69763060/90339403-d06a6480-dff0-11ea-9669-74206449e22d.png)

Here's PS3 screenshot (sorry for quality I had to use youtube video cause my ps3 blueray drive died recently and I can't run game my self anymore) and Harry is running at this screenshot.
![image](https://user-images.githubusercontent.com/69763060/90339359-8aad9c00-dff0-11ea-9ad4-ad34321111b6.png)

OS: Windows 10
CPU: i5-8400
GPU: GTX 1070
Driver version: latest

**Comment by illusion0001** [comment]
Try various rsx buffer settings, wcb, rdb.. etc

**Comment by Cursinal** [comment]
> Try various rsx buffer settings, wcb, rdb.. etc

Where are these settings?

**Comment by MarioSonic2987** [comment]
Write Color Buffers is in GPU tab and the others in Advanced tab (Read Color Buffers, Write Depth Buffers and Read Depth Buffers).

You should select Write Color Buffers only.

**Comment by Cursinal** [comment]
Sadly, It made no difference

**Comment by kd-11** [comment]
This looks like a depth issue, I would start with Read Depth Buffer option. Or just enable all 4 of them and see if it makes any difference. If it does, disable one at a time until you find out which one fixes it.

**Comment by jeremybris** [comment]
seems similar to #8619 and #8668

**Comment by Cursinal** [comment]
> This looks like a depth issue, I would start with Read Depth Buffer option. Or just enable all 4 of them and see if it makes any difference. If it does, disable one at a time until you find out which one fixes it.

It doesn't :( I tried every 4 at the same time, I tried Read Depth Buffer only, I tried 3 (Read Color Buffers, Write Depth Buffers and Read Depth Buffers). Literally no difference

**Comment by kd-11** [comment]
This should be fixed now, retest.

**Comment by Cursinal** [comment]
> This should be fixed now, retest.

Still not working properly.

**Comment by jokoputera** [comment]
Fix by https://github.com/RPCS3/rpcs3/pull/9354 please close

**Comment by RainbowCookie32** [comment]
Don't close until the PR is merged
