### ISSUE TITLE
[Feature Request] Binding pressure sensitive buttons at different levels

### ISSUE THREAD

**Issue by K900** [RPCS3/rpcs3#8746]
## Quick summary
Some games, notably Metal Gear Solid 2/3, use pressure sensitive face buttons on the PS3 controllers to perform different actions based on the depth of the button press. Right now those games are effectively only playable correctly with a real DualShock 3, as no other controller has pressure sensitive face buttons. 

It would be nice to provide a way to instead bind a "full press" or "partial press" of a face button to a separate button on a controller/keyboard.

## Details

I see three main approaches here:

1. Allow binding the pressure of a button to a specific axis (e.g. a stick or a trigger)
2. Allow binding multiple levels of pressure to separate inputs (e.g. A to half press X, RT+A to long press X, etc.)
3. Allow binding multiple levels of pressure to the number of _time_ a button is held for (quick press to half press, longer press to  full press)

All of those would make the games playable, at least, but a combination might be the best option for a universally good experience.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* UI

#### 2. Please tell us, why your feature is important to RPCS3.
Games that support pressure sensitivity are not currently able to be played as intended using non-DS3 controllers. Implementing this would allow them to be playable on a lot more hardware

#### 3. Please attach screenshots of the feature implemented in other projects.
![image](https://user-images.githubusercontent.com/386765/90549764-a2735480-e197-11ea-87cf-9f0c06064f79.png)

PCSX2 implements option 2, and nothing else.

**Comment by Megamouse** [comment]
If I recall correctly we already use the first option natively.

The third option seems easily feasible too. Although I don't know if it would be intuitive to use in regular gameplay.

The second option seems kinda silly imo and does not fit the original behaviour of the ps3

**Comment by K900** [comment]
The second option is unfortunately the only way for some games :( MGS3, for example, uses half press O to hold an enemy in a choke hold, and a full press to kill the enemy currently being choked. This means you need a way to keep O half-pressed for an effectively indefinite amount of time.

**Comment by Dormant-Hero** [comment]
Please please consider this. Option 2 for MGS would be great.

 My personal preference would be a button like up on the dpad to toggle the config so that when u press l1 r1 it will use the maximum sensitivity and vice versa for down.

Not having options for this feature breaks games like MGS4 and it would be really appreciated for the fans of the online component!
