### ISSUE TITLE
Skate 3 random system reboots

### ISSUE THREAD

**Issue by TheFranks** [RPCS3/rpcs3#8747]
## Quick summary
Will be playing just fine, but between 5 nd 30 minutes of gameplay my whole system will reboot. 

## Details
This does not seem to be related to anything happening in game, and can come at any time.  I cannot get a log, as the whole PC reboots, so I do not know the cause.  Running a system monitor while gaming shows it is not an overheating issue.  Put my RAM back to 3600, to see if is timing issue, but that did not help.
.

#### 1. Please attach RPCS3's log.
Cannot get a log, as pc shuts down and restarts

#### 3. Please attach screenshots of your problem.
Cannot get screenshot as problem is PC rebooting  Works fine up until that point

#### 4. Please provide comparison with real PS3.
The PS3 does not reboot randomly

#### 5. Please provide your system configuration:
Windows 10 64bit 2004 build up to date
Ryzen 3600x
MSI Armor RX-580
driver 20.7.2

**Comment by Yahfz** [comment]
This is not RPCS3 fault. Something is unstable on your system and RPCS3 only makes it more pronounced since it is a very demanding application.

**Comment by TheFranks** [comment]
I have to doubt that, as this is the first and only application that has ever caused this issue, and it is in an alpha state.  It really isn't that demanding of a program.  But that's fine.  If I can't use it, I can't use it... and I will make sure to tell others to avoid it as well, as random reboots can cause actual instability issues, disc error, and other unwanted problems.  Thanks for the input.

**Comment by CrabLugo** [comment]
5 to 30min period of time makes sense in case of for example overheating any part in your computer. You gotta troubleshoot it on your own, pay somebody else to do that for you or ignore that insability in your configuration like you are prone to do.

RPCS3 is demanding. Claiming otherwise makes you look dumb

Close issue as it's invalid

**Comment by Yahfz** [comment]
> I have to doubt that, as this is the first and only application that has ever caused this issue, and it is in an alpha state. It really isn't that demanding of a program. But that's fine. If I can't use it, I can't use it... and I will make sure to tell others to avoid it as well, as random reboots can cause actual instability issues, disc error, and other unwanted problems. Thanks for the input.

What you said is equivalent to ignoring a stress test app detecting an instability. Would you blame the stress test too like you're trying to blame RPCS3? Come on man.

**Comment by TheFranks** [comment]
Yeah, I would probably trust a stress test.  And the ones I have run don't show any issues.  Seems weird that all you automatically assume an instability issue, but since this has been no help, I'll close the issue.  I have wasted enough time on this Y'all can all eat a bag of dicks, choke on them, die, go to hell, get tortured, get reincarnated, and choke on another dick and die again.

**Comment by Yahfz** [comment]
Enjoy your unstable system

**Comment by AniLeo** [comment]
Ah the fresh cringe, thanks for the comedy gold
