### ISSUE TITLE
Resistance 2 works well but randomly freezes. [BCES00226]

### ISSUE THREAD

**Issue by blu3m00n1** [RPCS3/rpcs3#8753]
The game is running well and according to one of the compatibility reports it is playable and I do agree. Almost. 
There is this one bug that is making the game play experience not so great. The game freezes at the first screen you see when loading the game, whether it takes 30 seconds or 5 minutes, it eventually will freeze. When going through the menu and organising a 2 player coop, you can play the game fine until it suddenly freezes at any random point, it doesn't seem to have a trigger. The audio (like the music) will continue to play and no further input will be accepted. 

I have tried a multitude of different settings (not everything), including fast ppu decoder amsjit spu compiler and the fast spu compiler. I have tried the game with xfloat ticked to see if it would change anything. not much luck. The latest thing I have tried was Driver wake up delayed. I started at 100 and worked my way all the way till 7000 and it still presents its random freeze. 

I have attached 1 screenshot and 3 logs. 
log (1) and log (2) tests the coop.
the normal log without the corresponding numbers added is just of the first screen when loading the game. 
The screenshot is a perfect representation of what it looked like in real time lol, nothing happening, fps counter unchanged. nothing, except audio.
<img width="1920" alt="frozen game" src="https://user-images.githubusercontent.com/69975574/90974574-e4254600-e56f-11ea-8af9-71c6d5c90257.png">

Build Info
RPCS3 v0.0.11-10766-bcddbc15 Alpha | HEAD | FW 4.85 | Windows 10 1909
Intel Core i9-9900K | 16 Threads | 15.92 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3 | TSX
GPU: AMD Radeon RX 5700 XT (20.3.1 - 20.5.1)

**Comment by blu3m00n1** [comment]
I have basically tried every setting I can now, and now I'm out of ideas on how to fix this

**Comment by illusion0001** [comment]
Try increasing driver wake up delay

**Comment by blu3m00n1** [comment]
I did that until I maxed out at 7000 and still hadn't fixed the issue

**Comment by blu3m00n1** [comment]
This possibly is a issue on my end.
I can't confirm just yet but after testing every possible option I have, I decided to disconnect the second controller and load the net version of rpcs3 to see if it would replicate the same issues. So far I haven't had any freezing so I need to do further testing but it's likely that this is a issue on my end if nobody else has run into this same issue.

**Comment by blu3m00n1** [comment]
I have tried without player 2s controller connected and on a different version of rpcs3. The random freeze still occurs and makes this Coop mode basically unplayable.
I'm simply not smart enough to understand why it's happening and I'm not smart enough to find a solution. 
At this point, I have run out of options and will wait until someone can help.

**Comment by blu3m00n1** [comment]
Now has a bounty! https://www.bountysource.com/issues/92347190-resistance-2-works-well-but-randomly-freezes-bces00226

**Comment by isJuhn** [comment]
any fast way to reproduce?

**Comment by illusion0001** [comment]
Load into coop mode, usually between 10 to 20 minutes before it will crash with no errors in console (didn't check log)

**Comment by blu3m00n1** [comment]
I'm not sure if it's the same error that causes it but if you simply load the game and leave it, the flashing symbol in centre of the screen will freeze and you won't be able to continue the game. I haven't experienced this issue in campaign.
Otherwise a Coop playthrough is the fastest way to produce the issue.

**Comment by illusion0001** [comment]
I forgot to mention that it has to be the split screen mode for the crash to occur @isJuhn

**Comment by blu3m00n1** [comment]
It actually can occur in the normal Coop without split screen

**Comment by AniLeo** [comment]
Pirated copy detected, removed log files. Needs log file from a clean copy.

**Comment by blu3m00n1** [comment]
I have a copy of the game, I didn't have a external disk drive so yep. I downloaded it.
Since I do want support for the game I have a external disk drive arriving from ebay in about a week. A log from a clean copy will be avaliable soon.

**Comment by nitroos-ai** [comment]
I found a temporary fix for uncharted 3 by reducing Max SPURS Threads from 'Unlimited' to 3. Try it may be it will fix the problem.

**Comment by blu3m00n1** [comment]
It is possible that the issue is from the copy I have. I will be getting my disk drive soon so I can get a clean copy to see if the problem will replicate itself.
But it did happen with illusion as well, 
I decided to test more with the unclean copy and it happens in all modes of play and your suggestion hasn't been able to solve it. 
So I need a clean log in order to proceed with this.

**Comment by elad335** [comment]
if its an really an SPU threads cuncurency issue try #8822

**Comment by blu3m00n1** [comment]
Need someone with a clean copy to test for me otherwise I'm getting my drive in a couple of weeks to dump the game.

**Comment by nitroos-ai** [comment]
> if its an really an SPU threads cuncurrency issue try #8822 with the option enabled. @nitroos-ai

Your solution didn't solve my problem but instead introduced new error codes in log.
PPU: LWARX took too long
PPU: LDARX took too long

intel core i5-4590 4 threads tsx.

**Comment by nitroos-ai** [comment]
I tried Resistance 2 BCUS98120 and it works fluidly with only one problem. Each time I boot the game it tells me that game data has been corrupted and that I have to delete it, so I go into '.config/rpcs3/dev_hdd0/game' and delete BCUS98120 file.

**Comment by blu3m00n1** [comment]
Thanks to covid I'm still waiting for my new bluray reader. I decided to test the resistance 2 copy I have. After the new update it does not freeze. So it wasn't due to the illegally downloaded copy but due to a actual issue. But that isn't the point, I spoke to someone who highlighted that these copies can be edited and broken and people can really waste alot of time trying to find a solution.

Anyway I will be using the bluray player (when it actually arrives) to dump the game so I have a clean copy and can get some further support, like the map being weird or the green flashes of graphics lol. Thanks anyway and if anyone's reading this, don't pirate the game even if you own it. It'll save you alot of trouble in the future.

**Comment by asherhutt** [comment]
This issue is still persistent today, RPCS3 even mentioned it in their latest video about Z-Cull and Texel remapping issues being improved which fixed several issues such as the water texture being broken in every Insomniac title. They mentioned that the Resistance games are still labeled as in game since they suffer from crashes. Is this an RPCS3 issue, a pirated copy issue, a game issue, or something else?
