### ISSUE TITLE
Game list size bug at start.

### ISSUE THREAD

**Issue by Oznatsoc** [RPCS3/rpcs3#8755]
Since an update of around 3 days ago whenever I start RPCS3 the size of the game list is like the first screenshot (notice the size bar).
Increasing and decreasing the bar again fixes the problem, setting the size as the second screenshot.

![a](https://user-images.githubusercontent.com/56119377/90830326-c2df1280-e341-11ea-8fce-901bf2531923.png)
![b](https://user-images.githubusercontent.com/56119377/90830429-f1f58400-e341-11ea-9ce0-a07959998f0f.png)

**Comment by Megamouse** [comment]
The Trophy and Save managers look even worse 🙈 
Try https://github.com/RPCS3/rpcs3/pull/8756
