### ISSUE TITLE
Multiple crashed on different Locations in Kingdom Hearts1.5 HD Final Mix

### ISSUE THREAD

**Issue by Jeromebas** [RPCS3/rpcs3#8761]
Actually im in Wonderland and there was no issue till this Point. First the game crashed on entering Queens Palace but after serveral Tries i could enter.
Now when the Court Changes as she told everyone is guilty it crashes everytime with the error:

·E 0:02:36.593578 {RSX [0x004a6c0]} RSX: A texture was found in cache for address 0xc45d8000, but swizzle flag does not match
·F 0:02:36.593591 {RSX [0x004a6c0]} SIG: Thread terminated due to fatal error: Assertion failed: !region.is_locked()
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTextureCache.h:1173)

#### 4. Please provide comparison with real PS3.
It shouldnt Crash?

#### 5. Please provide your system configuration:
* OS: Windows 10 Pro 64 Bit
* CPU Intel Core i7 6700K
* GPU Geforce RTX 2080 Super
* Driver version 452.06

**Comment by darkash** [comment]
I have no issue entering queen's palace at all, but I have been long past that story part. Can you post your RPCS3.log after the crash happen and upload your save data so others can try replicating the issue?

If it doesn't crash for others, it might be hardware/driver-specific issue

**Comment by Jeromebas** [comment]
For now i cant get the Crash anymore. Some of the later Updates seems to have fixed it? Because i didnt changed anything on my Config.

**Comment by Rhylar** [comment]
I am also having this error on KH 1.5. @Jeromebas what did you do to fix it?

**Comment by kd-11** [comment]
This was fixed some time ago by https://github.com/RPCS3/rpcs3/pull/8927. This issue was also a duplicate.
