### ISSUE TITLE
Fatal Error on launch RPCS3 [Win 10 - 2004 + AMD driver 20.4.2 and 20.8.2]

### ISSUE THREAD

**Issue by MineSAT** [RPCS3/rpcs3#8765]
## Quick summary 
I have updated the version of Windows 10 through Update to the most recent, version 2004. I have installed the latest drivers for the graphics card to avoid compatibility problems (AMD RX 5700 XT with Adrenaline Soft drivers. 20.8.2) .

I run the emulator to try to play and a crash window appears.

In the previous version of Windows I have not had this problem. I have also performed a clean installation of the operating system and drivers, I have tried to change the graphics drivers using DDU to correctly uninstall them and reinstall another version.

The operating system is stable and original, other programs and games that use Vulkan are not giving me problems.

## Details

When starting the emulator, an error / crash windows appear indicating a crash in something and that it cannot recognize the Vulkan.

#### 1. RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5113257/RPCS3.log)

#### 3. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/626020/90967245-a6c3a880-e4dc-11ea-9fc9-0d841a2d4db4.png)

#### 5. Please provide your system configuration:
* OS: Windows 10 PRO X64 update 2004
* CPU: AMD Threadripper 2990WX
* GPU:  AMD SHAPPHIRE RX 5700 XT
* Driver version: 20.4.2[Stable] and 20.8.2[Beta]
* MB: GIGABYTE X399 DESIGNARE EX

**Comment by MineSAT** [comment]
Any news or progress on this problem? I want to enjoy my games again with this great emulator. I was also recording a series for my channel and I can't continue it T.T

**Comment by xddxd** [comment]
Well there's definitely a problem on your end, I have a Ryzen 7 2700 and RX 580 rig and both 20.8.2 and 20.8.3 work fine for me. Could be chipset drivers perhaps? Did you disable the internet after DDUing so Windows Update doesn't install drivers on it's own?

**Comment by MineSAT** [comment]
Hello @xddxd, I am going to try to reinstall the chipset, the graphics drivers did not install themselves with Windows until I downloaded and installed them myself from the official AMD website.

**Comment by MineSAT** [comment]
I have reinstalled the chipset but it still does not work... ->
![image](https://user-images.githubusercontent.com/626020/91715193-7db2b000-eb8d-11ea-812a-554f2456195a.png)

**Comment by MineSAT** [comment]
The issue appears in #7710 (https://github.com/RPCS3/rpcs3/issues/7710) and fixed with update in emulator. @kd-11 (?) Sorry if I have bothered you by putting you in copy of this problem.

**Comment by kd-11** [comment]
Then we can close this as it is not reproducible.
