### ISSUE TITLE
Controllers do not respond properly on 007 games

### ISSUE THREAD

**Issue by Josivan88** [RPCS3/rpcs3#8766]
The problem happens when you try to move the character, you can't move to the up/left diagonal. when it moves, stop, or not move at all, others diagonals work properly, tested on Dinput controllers and Xinput controllers using MMJoystck and Xinput Handle
![Problem](https://user-images.githubusercontent.com/36341425/90967699-7b7b9200-e4b9-11ea-9bdb-42bd5bf0acf2.jpg)
007™ Legends [BLUS30983] Log Single player
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5113279/RPCS3.log.gz)
007™ Legends [BLUS30983] Log split-screen
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5113280/RPCS3.log.gz)
GoldenEye 007™: Reloaded [BLES01292] split-screen
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5113281/RPCS3.log.gz)

System configuration:
Windows 10 64 bits (1903)
Core i7 9700K
32 Gb of DDR4 RAM
Nvidia GTX 1070
GPU Driver 452.06

These games are being graphically fixed by KD-11 in the PR #8741 and the final problem to they become fully playable is that controller issue

**Comment by Josivan88** [comment]
I don't think that a bad dump is the problem, because these two games have the same problem independently.

**Comment by Krishster** [comment]
why the thread has been closed ? the controller movement issue (up left diagonal) is still there. i think megamouse can sort it out.

**Comment by RainbowCookie32** [comment]
This issue is open though

**Comment by Josivan88** [comment]
Maybe we can ping @Megamouse to take a look

**Comment by Krishster** [comment]
Golden eye 007 reloaded both version BLUS30755 and NPUB30752 has same controller issue. @Megamouse plz look into the matter.

**Comment by Josivan88** [comment]
Hello, nothing new here for almost 4 months, We think that the only one capable to help is @Megamouse
So, please, take a look.

**Comment by RainbowCookie32** [comment]
Stop pinging Megamouse, it won't get it fixed any faster.

**Comment by Josivan88** [comment]
This was not my intention, the idea here is just to know if he knows the problem and can help, if not just an "I can't help" or "I searched and I don't know what is causing this problem"  is enough, just any word about that is enough for us.

**Comment by Megamouse** [comment]
This seems to be a game bug. It can't handle both axis of a stick being 0 at the same time.
It probably has some amateurish check that exits the internal input function early if both values are 0.

You can "fix" this by setting the stick multipliers to 0.99
