### ISSUE TITLE
Battle Fantasia [BLES00253] and [NPUB30126]: black screen after the opening

### ISSUE THREAD

**Issue by legolas119** [RPCS3/rpcs3#8772]
## Quick summary
When I load it, after the intro, I can only hear the sound, but the screen is always black. 

## Details

After the opening intro, that correctly works, I can only hear the sound of the game, but the screen is always black. Sometime it appears "compilying shaders" but nothing happens. It continues to run because I can hear the demo mode and I can enter input with my joypad, but I can't view anything. I can view only the opening intro when it started again after the demo mode...
I have same issue both with pkg and folder format.

#### 1. Please attach RPCS3's log.
See log file attached

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
Black screen after the opening intro

#### 3. Please attach screenshots of your problem.
see image attached

#### 4. Please provide comparison with real PS3.
N.A.
#### 5. Please provide your system configuration:
I selected Vulkan as suggested in the compatibility list https://wiki.rpcs3.net/index.php?title=Battle_Fantasia and this is my pc config:
CPU: AMD Ryzen 3700X
Motherboard: Gigabyte X570 I AORUS PRO WIFI
RAM: 2 x 8 GB Kingston HyperX Predator 3200-16
GPU: RTX 2060 Super

#### Please include.
* Anything else you deem to be important

**Comment by legolas119** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5133129/RPCS3.log)
![Immagine](https://user-images.githubusercontent.com/48774386/91366209-67aa9580-e803-11ea-9358-1c0c0d800dcf.png)

I added again the files, I don't know if they were attached on my first post

**Comment by AniLeo** [comment]
Try with default settings with both OpenGL and Vulkan (no resolution scale, no multithreaded rsx)

**Comment by legolas119** [comment]
thanks, i tried both Vulkan and OPENGL with these settings. I have disabled Multithreaded rsx (resolution scale is set by default):
https://i.postimg.cc/pTZMfNjH/Immagine.png

but I still have the issue :(

**Comment by legolas119** [comment]
Does anyone can help me please?

**Comment by legolas119** [comment]
well. this is my current config: https://i.postimg.cc/YqVTrvFK/Immagine.png
what I need to change in order to solve the isssues?  Probably I have to put Resolution Scalte = 100% )

thanks

**Comment by digitaldude555** [comment]
![Screenshot (322)](https://user-images.githubusercontent.com/26138653/107145213-d3636380-6948-11eb-9e18-a6b069bdadb9.png)
It needs write color buffer.
