### ISSUE TITLE
Game title doesn't show up on Discord Rich Presence after #8707

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#8781]
After PR #8707 game title doesn't show up on Discord Rich Presence anymore. This issue only affected some of the games in my library though, and the only pattern I could notice is that they are all disc games. Digital games don't seem to be affected at all.

before:
![before regression](https://user-images.githubusercontent.com/61447828/91468521-8000cb80-e868-11ea-880f-e0517b692850.png)

after:
![after regression](https://user-images.githubusercontent.com/61447828/91468537-842ce900-e868-11ea-8006-55abdd8c2c9c.png)

Specs: i7-4770, GTX 1050 Ti, 12gb RAM, Windows 10 2004

**Comment by illusion0001** [comment]
Also game titles
![](https://cdn.discordapp.com/attachments/644808568561729550/748582827645468782/unknown.png)
![](https://cdn.discordapp.com/attachments/644808568561729550/748583443004260492/unknown.png)

**Comment by RainbowCookie32** [comment]
Probably also causes the broken titles I've seen before in my game window, haven't had the time to properly bisect though.

https://media.discordapp.net/attachments/272875751773306881/746921211686158356/unknown.png
https://cdn.discordapp.com/attachments/528905341744709642/747167538139365496/unknown.png

**Comment by elad335** [comment]
Fixed in #8780
