### ISSUE TITLE
Vertex explosions caused by accurate xfloat in RDR

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8782]
After some time when accurate xfloat is enabled, vertex explosions in horses (and in some environment objects?) begin to happen.

![Screenshot_10](https://user-images.githubusercontent.com/1712979/91500318-f256c780-e8cb-11ea-9eb2-6d6627399955.png)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5138971/RPCS3.zip)
RSX Capture: https://www.dropbox.com/s/2j3mldprhi2szi7/BLUS30418_20200828010111_capture.7z?dl=0
Ryzen 7 2700
RX 580
Windows 10 2004

**Comment by Megamouse** [comment]
is this still happening?

**Comment by Ordinary205** [comment]
> is this still happening?

No, it seems fixed.

![Red dead redemption](https://user-images.githubusercontent.com/125112932/228770359-29312762-0832-44a7-beb5-28a7138c7729.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11109256/RPCS3.log.gz)
