### ISSUE TITLE
Gundam Side Stories - [BLAS50710] VM Acess Violation No Booting

### ISSUE THREAD

**Issue by Shuneferus** [RPCS3/rpcs3#8785]
F {PPU[0x1000004] Thread (GaMTaskParallelWorker0) [0x000262f0]} VM: Access violation reading location 0x0 (unmapped memory)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5139532/RPCS3.log)

**Comment by RainbowCookie32** [comment]
How to reproduce? Can you provide saves for easier reproduction? Is this a regression? Has it always happened?

Please read the guidelines when opening an issue. They are not there as a decoration you delete, but rather a guide to get complete issues to make devs' lifes a bit easier.

**Comment by Shuneferus** [comment]
I don't know when this error started, I haven't played it for a while.
The game freezes after the first loading screen and when trying to close it the emulator crashes generating the message:
"Fatal error when stopping the emulator for a long time.
Some topic probably came to a halt. Aborting. "

[savedata.zip](https://github.com/RPCS3/rpcs3/files/5139731/savedata.zip)

**Comment by AniLeo** [comment]
Missing RPCS3 version when this issue started

**Comment by Shuneferus** [comment]
The game is starting up normally, in fact, I ended up reducing the number of spu threads to 2 (a long time ago)
 and I had forgotten and when I increased to 3 the game starts up normally.
You can close this issue # 8785.
 I apologize for what happened and a big hug to the whole RPCS3 team.

**Comment by RainbowCookie32** [comment]
You can close it yourself if it's fixed
