### ISSUE TITLE
Unhandled Win32  exception 0xC000001D.

### ISSUE THREAD

**Issue by RPPCSJOJOASBUSER** [RPCS3/rpcs3#8792]
![2020-08-28_20-55-16](https://user-images.githubusercontent.com/70323746/91603104-7452f900-e97d-11ea-9c2e-7fb4524e1351.png) when i use this Option being white screen fast black screen and fatal error
![2020-08-28_20-58-34](https://user-images.githubusercontent.com/70323746/91603183-9a789900-e97d-11ea-90c2-afc9b25ee2ff.png) guys help me what aim need to do?;(

My PC:Pentium Dual-Core 
CPU E5500
@2.80Hz,
2,0GB
AMD Radeon HD 5450
dont have vulkan

**Comment by RainbowCookie32** [comment]
0.0.4 build, get that back to the museum where you stole it from

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
