### ISSUE TITLE
BLES01047 - Castlevania Lord of Shadows: a lot of slowdowns

### ISSUE THREAD

**Issue by legolas119** [RPCS3/rpcs3#8797]
## Quick summary
starting from the Opening, there are a lot of slowdowns.

## Details
The opening runs at 4/8 fps! Ant after the opening, the games lost 15fps, it runs at about 45fps instead of 60. I tried to disable Multithreaded RSX and use bot Vulkan and Open GL, but nothing is changed...

#### 1. Please attach RPCS3's log.
see attached log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5145598/RPCS3.log.gz)

#### 5. Please provide your system configuration:
CPU: AMD Ryzen 3700X
Motherboard: Gigabyte X570 I AORUS PRO WIFI
RAM: 2 x 8 GB Kingston HyperX Predator 3200-16
GPU: RTX 2060 Super

#### Please include.
* Anything else you deem to be important

**Comment by legolas119** [comment]
Does anyone can help me please?

**Comment by kd-11** [comment]
You're running 4K internal resolution + MSAA - essentially you're probably rendering at 8K res with this combination!!. Start with stock settings (720p) and disabled SPU loop detection. Once you have it running ok, then you tweak up your settings.
Also, this is a support issue, not a bug report. Use discord or forums for performance tuning help.
