### ISSUE TITLE
BLES01060 - Crysis 2: the game doesn't start, white sceen at the beginning

### ISSUE THREAD

**Issue by legolas119** [RPCS3/rpcs3#8798]
## Quick summary
As soon as I load the game, it appears a blanck screen and nothing happens...

## Details

I tried also Open Gl and to disable multithreatening, but nothing is changed, I still have this issue

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
see log attacheched
#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 5. Please provide your system configuration:
CPU: AMD Ryzen 3700X
Motherboard: Gigabyte X570 I AORUS PRO WIFI
RAM: 2 x 8 GB Kingston HyperX Predator 3200-16
GPU: RTX 2060 Super

#### Please include.
see picture attached
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5145624/RPCS3.log.gz)
![Immagine](https://user-images.githubusercontent.com/48774386/91642239-129c9880-ea2a-11ea-8196-662a9783ac64.png)

**Comment by elad335** [comment]
Disable spu loop detection, its also mentioned in forums somewhere.

**Comment by legolas119** [comment]
thanks, I disabled it but the issue is still here...white screen, game freezed... :(
Do you have any other suggestion?

thanks!
