### ISSUE TITLE
vk: SOCOM 4 crashing by hitting an unreachable assert in VKTextureCache

### ISSUE THREAD

**Issue by illusion0001** [RPCS3/rpcs3#8803]
Socom 4 will only go ingame on OGL but VK crashed with
```
Thread terminated due to fatal error: Unreachable
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTextureCache.h:231)
```
VK: [RPCS3.zip](https://cdn.discordapp.com/attachments/319224795785068545/749498582448472064/RPCS3.zip)
VK with SRM: [RPCS3.zip](https://cdn.discordapp.com/attachments/319224795785068545/751083931343912980/RPCS3.zip)
OGL: [RPCS3.zip](https://cdn.discordapp.com/attachments/319224795785068545/749500112362799167/RPCS3.zip)
![](https://cdn.discordapp.com/attachments/319224795785068545/749500047086846023/unknown.png)

**Comment by sampletext32** [comment]
Hey, could someone please remove "In Progress" label from this one?
