### ISSUE TITLE
Regression: GTA V graphical glitches (#8794)

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8805]
After PR #8794, GTA V has graphical glitches around the character (a square) and a line going across a hill.

Master:
![Screenshot_11](https://user-images.githubusercontent.com/1712979/91669300-861ed280-eb1c-11ea-9c9a-2386ecb8ace2.png)
https://www.dropbox.com/s/q3zy3tgg9lrf2x2/BLES01807_20200830235457_capture.rrc?dl=0
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5147457/RPCS3.log.gz)

v0.0.11-10801-6952be5c:
![Screenshot_12](https://user-images.githubusercontent.com/1712979/91669404-650ab180-eb1d-11ea-9e52-7656fa28012a.png)
Log: [10801.gz](https://github.com/RPCS3/rpcs3/files/5147460/10801.gz)

**Comment by kd-11** [comment]
There is a nicer way to do filtering; I'll rework it to filter in hardware.
