### ISSUE TITLE
[BLES01702] TEKKEN Tag Tournament 2: game crash after arcade mode

### ISSUE THREAD

**Issue by Moonalesca** [RPCS3/rpcs3#8806]
The game crashes immediately when skipping any character's ending movie after finishing Arcade Mode.

System specs are:

Intel i7-9700K
Nvidia GTX 1070 Ti
Windows 10

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5147461/RPCS3.log.gz)

**Comment by arcadee1977** [comment]
Ending movie random freezing problem did not exist before. I don't know when it began to appear

**Comment by Megamouse** [comment]
i don't see any crash in the log.
Please upload a log file with the crash included.
