### ISSUE TITLE
Regression: Disgaea 3 SPU stall caused by waitable atomics changes (#8507)

### ISSUE THREAD

**Issue by HybridEidolon** [RPCS3/rpcs3#8807]
## Quick summary
Upon entering the lobby area after loading a save or starting a new game, the game will freeze just after giving the player control of the character. Found on NPUB31766 (PSN download version), both updated and not updated.

## Details
This appears to be caused by the changes in PR #8507; this game works perfectly on the build before the one that includes them. It doesn't appear to be connected to the save/load UI, since it happens after the opening dialog cutscene on a new game as well.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
* Works: Build 10670 (commit 3157a10)
* Does not work: Build 10672 (PR #8507 commit 54b87b6)

* 10672 log: [RPCS3-bad-10672.log.gz](https://github.com/RPCS3/rpcs3/files/5147533/RPCS3-bad-10672.log.gz)
* 10670 log: [RPCS3-good-10670.log.gz](https://github.com/RPCS3/rpcs3/files/5147536/RPCS3-good-10670.log.gz)

#### 5. Please provide comparison with real PS3.
Well, the game doesn't stall... at least, on _my_ PS3

#### 6. Please provide your system configuration:
* OS: Windows 10.0.18362 Build 18362
* CPU: Intel i7-7700K
* GPU: GeForce GTX 1080
* Driver version: 445.87

**Comment by elad335** [comment]
Test with #8821

**Comment by escape209** [comment]
No change with #8821.

**Comment by elad335** [comment]
Fixed by #8821
