### ISSUE TITLE
Thread Scheduler should be disabled by default

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#8808]
The Thread Scheduler setting should be disabled by default at this point, as RPCS3 tends to perform better with this disabled

Some points to consider:
- The OS scheduler is aware of what is the best CCX on the CPU (bin dependent)
- [Windows 10 1809 becomes EOL on November 2020](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet), the last version of Windows 10 to not have Ryzen support on the Scheduler
- The OS scheduler tends to work better than the Thread Scheduler setting in most cases

**Comment by RipleyTom** [comment]
Ryzen 3950X performs better in spurs_test.self with Thread Scheduler on:
Scheduler ON:
```
SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 7549 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2575 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 10900 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 16367 ms (PS3: 4443 ms)
SPU Integer Perf completed in 2732 ms (PS3: 8666 ms)
SPU Float Perf completed in 599 ms (PS3: 2379 ms)
SPU SpinLock completed in 9602 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 9098 ms (PS3: 3853 ms)
PUTLLC Perf completed in 1023 ms (PS3: 3364 ms)
PUT Perf completed in 8264 ms (PS3: 3984 ms)
--Completed 10 tests in 68710 ms--
```
Scheduler OFF:
```
SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 7095 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 3234 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 15759 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 21145 ms (PS3: 4443 ms)
SPU Integer Perf completed in 2786 ms (PS3: 8666 ms)
SPU Float Perf completed in 602 ms (PS3: 2379 ms)
SPU SpinLock completed in 12029 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 12991 ms (PS3: 3853 ms)
PUTLLC Perf completed in 1052 ms (PS3: 3364 ms)
PUT Perf completed in 15958 ms (PS3: 3984 ms)
--Completed 10 tests in 92652 ms--
```

This is on linux but I remember getting similar results on windows.
We have different [custom configs](https://github.com/RPCS3/rpcs3/blob/21b535b5c5637224855404b459f6eb1a1aa7a3a1/Utilities/Thread.cpp#L2232) depending on detected cpu so performance may vary depending on those.

**Comment by kd-11** [comment]
Maybe we need another audit of how it impacts performance. However, without hardware auto-configuration, this is going to be difficult as each user may have a different experience. On my 1700, windows scheduler is much better for some games but 1-2 fps slower in others for example. On 6-thread CCX designs the variance can be much worse either better or worse.
Taking it as a completely binary choice, we need to audit which systems benefit from it always on, vs which ones get hurt by it and compare pros vs cons.

**Comment by isJuhn** [comment]
yes it seems like there are benefits and drawbacks to it, overall it depends on the games specific workload. Perhaps users should be encouraged to experiment with it in the tooltip? 3700X on windows 2004.

Scheduler on:
```
SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 5399 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2000 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 4222 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 5666 ms (PS3: 4443 ms)
SPU Integer Perf completed in 4137 ms (PS3: 8666 ms)
SPU Float Perf completed in 922 ms (PS3: 2379 ms)
SPU SpinLock completed in 5249 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 4431 ms (PS3: 3853 ms)
PUTLLC Perf completed in 1636 ms (PS3: 3364 ms)
PUT Perf completed in 4900 ms (PS3: 3984 ms)
--Completed 10 tests in 38562 ms--
```

Scheduler off:
```
SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 4864 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2287 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 8081 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 9878 ms (PS3: 4443 ms)
SPU Integer Perf completed in 2840 ms (PS3: 8666 ms)
SPU Float Perf completed in 597 ms (PS3: 2379 ms)
SPU SpinLock completed in 6415 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 9966 ms (PS3: 3853 ms)
PUTLLC Perf completed in 1575 ms (PS3: 3364 ms)
PUT Perf completed in 8354 ms (PS3: 3984 ms)
--Completed 10 tests in 54858 ms--
```

**Comment by paulosouuza** [comment]
Here on Ryzen 3600 with
Scheduler on:
`SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 6225 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2296 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 4891 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 6502 ms (PS3: 4443 ms)
SPU Integer Perf completed in 5529 ms (PS3: 8666 ms)
SPU Float Perf completed in 1186 ms (PS3: 2379 ms)
SPU SpinLock completed in 6610 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 4921 ms (PS3: 3853 ms)
PUTLLC Perf completed in 2527 ms (PS3: 3364 ms)
PUT Perf completed in 4998 ms (PS3: 3984 ms)
--Completed 10 tests in 45685 ms--`

Scheduler off:
`SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 5908 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2877 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 9080 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 11316 ms (PS3: 4443 ms)
SPU Integer Perf completed in 18704 ms (PS3: 8666 ms)
SPU Float Perf completed in 6095 ms (PS3: 2379 ms)
SPU SpinLock completed in 7461 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 12514 ms (PS3: 3853 ms)
PUTLLC Perf completed in 6497 ms (PS3: 3364 ms)
PUT Perf completed in 6000 ms (PS3: 3984 ms)
--Completed 10 tests in 86453 ms--`

**Comment by paulosouuza** [comment]
Here on Ryzen 3600 with
Scheduler on:

```
SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 6225 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2296 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 4891 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 6502 ms (PS3: 4443 ms)
SPU Integer Perf completed in 5529 ms (PS3: 8666 ms)
SPU Float Perf completed in 1186 ms (PS3: 2379 ms)
SPU SpinLock completed in 6610 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 4921 ms (PS3: 3853 ms)
PUTLLC Perf completed in 2527 ms (PS3: 3364 ms)
PUT Perf completed in 4998 ms (PS3: 3984 ms)
--Completed 10 tests in 45685 ms--
```
Scheduler off:
```
SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 5908 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2877 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 9080 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 11316 ms (PS3: 4443 ms)
SPU Integer Perf completed in 18704 ms (PS3: 8666 ms)
SPU Float Perf completed in 6095 ms (PS3: 2379 ms)
SPU SpinLock completed in 7461 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 12514 ms (PS3: 3853 ms)
PUTLLC Perf completed in 6497 ms (PS3: 3364 ms)
PUT Perf completed in 6000 ms (PS3: 3984 ms)
--Completed 10 tests in 86453 ms--
```

**Comment by xddxd** [comment]
Ryzen 7 2700 @ 3.8GHz

TS Off

`SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 5412 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2688 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 7729 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 8925 ms (PS3: 4443 ms)
SPU Integer Perf completed in 3109 ms (PS3: 8666 ms)
SPU Float Perf completed in 688 ms (PS3: 2379 ms)
SPU SpinLock completed in 6516 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 12347 ms (PS3: 3853 ms)
PUTLLC Perf completed in 4260 ms (PS3: 3364 ms)
PUT Perf completed in 9326 ms (PS3: 3984 ms)
--Completed 10 tests in 61001 ms--`

TS On

`SPU Test v1.0.0 by GalCiv
SPU Task Avalanche completed in 4137 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2370 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 4866 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 5871 ms (PS3: 4443 ms)
SPU Integer Perf completed in 5414 ms (PS3: 8666 ms)
SPU Float Perf completed in 1147 ms (PS3: 2379 ms)
SPU SpinLock completed in 3766 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 5404 ms (PS3: 3853 ms)
PUTLLC Perf completed in 2591 ms (PS3: 3364 ms)
PUT Perf completed in 4709 ms (PS3: 3984 ms)
--Completed 10 tests in 40275 ms--`

**Comment by z0z0z** [comment]
Just had someone in discord with bad audio but fine fps on MGS HD Collection. Ryzen 1600.

Said turning off thread scheduler fixed the audio problems.

**Comment by bevanweiss** [comment]
Somewhat painful suggestion here, but perhaps we could run something like the SPU Test at first launch, once with TS on, once TS off, if there is a >20% difference then we default to the TS On setting.

Or we just add details to the tooltip saying pretty much the same... and have the user set the 'default'

**Comment by VelocityRa** [comment]
@bevanweiss The issue is variability in _games_. The microbenchmarks are consistently faster with TS on all Ryzen CPUs tested above.

**Comment by RipleyTom** [comment]
As a side note, spurs_test doesn't test RSX usage and the TS puts RSX threads on a separate CCX on the 3950X.
This may account for the difference between spurs_test results and game performance results.

**Comment by Asinin3** [comment]
I managed +4 FPS consistently on MotorStorm Pacific Rift and MotorStorm Apocalypse with Thread Scheduler Enabled.
Also noticed around another 3fps at the starting location in RDR. It's not *always* better for me, but almost always is.

R7 3700X, Windows 10 2004.

**Comment by Megamouse** [comment]
Disabled by default on latest master (or rather set to OS scheduler)
