### ISSUE TITLE
Ryū ga Gotoku Kenzan! (Yakuza Kenzan) red texture bug

### ISSUE THREAD

**Issue by Madvillain47** [RPCS3/rpcs3#8812]
## Quick summary
In certain areas's my game has glitched textures and lighting with a strange red tint/filter over everything

## Details

Preformance and visuals are perfect aside from many area's where the textures are completely replaced with a red tint, I've attempted to change around the settings even copying other friends settings who have no issues on their end and nothing seams to fix the textures. Any help would be greately appreciated.

#### 1. RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5150830/RPCS3.log.gz)

#### 2. RenderDoc capture that demonstrates the issues

https://mega.nz/fm/xU4FXRRb

#### 3. Screenshots of the problem.
Vulkan
![image](https://user-images.githubusercontent.com/70523013/91736337-68498000-eba5-11ea-9493-4cdde19fbb00.png)
![image](https://user-images.githubusercontent.com/70523013/91736550-c1191880-eba5-11ea-808f-44a2016c030f.png)

Opengl
![image](https://user-images.githubusercontent.com/70523013/91737674-481ac080-eba7-11ea-930e-dfa5dd9ce75c.png)

#### 4. Comparison with real PS3.
![image](https://user-images.githubusercontent.com/70523013/91736393-7eefd700-eba5-11ea-87a1-492a7dd52b58.png)
![image](https://user-images.githubusercontent.com/70523013/91736622-e148d780-eba5-11ea-8631-6fc43e1de6a1.png)

#### 5. System configuration:
* OS Windows 10
* CPU Ryzen 2600x
* GPU RTX 2070
* Driver version 452.06

**Comment by Asinin3** [comment]
This issue only affects Nvidia Turing GPU's as far as I know.

**Comment by AniLeo** [comment]
> Anisotropic Filter Override: 16

Invalid test, needs resting with default settings

**Comment by Asinin3** [comment]
Strict Rendering mode is on though, which should disable anisotropic filtering. It's not caused by it anyway

**Comment by AniLeo** [comment]
This red tint usually is caused by AF, but not applicable if using SRM

**Comment by Madvillain47** [comment]
I still have the red tint issue with Anisotropic Filtering turned off 
![image](https://user-images.githubusercontent.com/70523013/91745320-b1540100-ebb2-11ea-9b76-28f89b0afa7f.png)

**Comment by Satan86** [comment]
This problem can be fixed by selecting "Disable native float16 support" in the advanced tab. Author of the issue came to our Discord server and the bug was fixed there. Can close this issue.

**Comment by Madvillain47** [comment]
Thanks Satan, you're the man 👍
