### ISSUE TITLE
Black screen with compiling shaders for Katamari Forever

### ISSUE THREAD

**Issue by fruitpenninja** [RPCS3/rpcs3#8816]
I'm trying to run Katamari Forever through Windows on my Macbook Pro mid 2015 with the Intel Core I7-4770HQ at 2.2GHz. When I try launching the game, it just shows a continuous black screen with "Compiling shaders..." in the bottom left corner. I have attached the log.
<img width="742" alt="log" src="https://user-images.githubusercontent.com/32855559/91825704-7624f280-ebf1-11ea-98f4-e9dd14a5653f.PNG">

**Comment by AniLeo** [comment]
Hardware below minimum requirements
