### ISSUE TITLE
[NPUA70250] Sly Copper Thieves in Time Demo now throws RSX: Undefined format class for depth texture is not allowed

### ISSUE THREAD

**Issue by woj1993** [RPCS3/rpcs3#8819]
## Quick summary
Sly Copper Thieves in Time Demo now prints "RSX: Undefined format class for depth texture is not allowed". Previously it wasn't.

## Details
Sly Copper Thieves in Time Demo has a new error in console it's: Sly Copper Thieves in Time now throws RSX: Undefined format class for depth texture is not allowed. This error is repeatedly printed in main menu and while in game. I was thinking that it should be reported.
Also after this error RPCS3 is printing RSX: Unsupported depth conversion (0x8B) .

Game id is NPUA70250

## Log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5156343/RPCS3.log)

## RSX Capture (compressed to 7zip then to zip, because 7z is not allowed format):
[captures_2.zip](https://github.com/RPCS3/rpcs3/files/5156759/captures_2.zip)

## System configuration:
* OS: Windows 10 64 bit newest
* CPU: i5 2300
* GPU: Nvidia 440
* Driver version: Newest possible (391.35)

@kd-11 you should look at this because if I remember correctly you inserted this error massage. 

I'm rely sorry if my report is invalid for some reason. If you need additional information I am ready to give them.

**Comment by kd-11** [comment]
OpenGL support is temporarily blocked by https://github.com/RPCS3/rpcs3/issues/8714
I'm working on it but it's a large task. Should be completed in the next few days.
