### ISSUE TITLE
P4AU locking up on opening/skipping FMV. All fixes on closed thread don't work.

### ISSUE THREAD

**Issue by RobinOWie** [RPCS3/rpcs3#8825]
I've tried every fix in this thread and even tried some in duplicate threads but BLUS31469 (US ver. of P4AU) is still giving me this issue

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5164142/RPCS3.log.gz)

_Originally posted by @RobinOWie in https://github.com/RPCS3/rpcs3/issues/4706#issuecomment-685923639_

**Comment by Fabianpaw** [comment]
Looks like an issue with your settings, I got it to crash after copying them aswell.
Reset your config, then use Vulkan, Framelimiter to Auto and all else default instead, then it should work.

**Comment by 13xforever** [comment]
You're using an ancient build with a bunch of nonsense settings, this issue is invalid
