### ISSUE TITLE
Error F {PPU[0x1000000] Thread (main_thread) [0x00829de0]} VM: Access violation reading location 0xc (unmapped memory) When Playing Persona 5 

### ISSUE THREAD

**Issue by pyrokinesisv** [RPCS3/rpcs3#8838]
it immediately crash when tutorial stage at kamoshida palace 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5178317/RPCS3.log)

My spec is 
core i7 3770
8gb ram
gtx1060 3gb zotac

**Comment by pyrokinesisv** [comment]
sorry i forgot to put my rpcs3 version. 0.0.12-10826-baf96b3e 
and here my save data file if you want to reproduce it 
[NPUB31848-00--001--.zip](https://github.com/RPCS3/rpcs3/files/5178322/NPUB31848-00--001--.zip)

**Comment by nitroos-ai** [comment]
Try the 'strict rendering mode' in GPU tab in config.

**Comment by RipleyTom** [comment]
You:
-Have set PSN Status to RPCN which may lead to weird behaviour, this is an experimental feature...
-Are using patches. Have you tried disabling the patches and trying again?

**Comment by elad335** [comment]
Closing until relevant information on how to reproduce is posted, and it must be a valid situation. (if its caused by patches for example its not valid unless it works on ps3)

**Comment by Mugi4ok** [comment]
The Ratchet & Clank Trilogy, Ratchet & Clank 1 - confirmed, crash was fixed by setting PSN Status to "Disconnected".
Also note that RPCS3 restart was required, as otherwise error became more severe and crashed the whole emulator.

**Comment by Ayush98675** [comment]
F {PPU[0x1000000] Thread (main_thread) [0x002dc72c]} VM: Access violation reading location 0x4 (unmapped memory) 
and its crashing the ps3 . game name is the last of us.....



Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
8.00 GB
Windows 11
nvidia geforce gtx 1650

**Comment by FreshlyFishedBread** [comment]
F {PPU[0x1000000] Thread (main_thread) [0x00af2e84]} VM: Access violation reading location 0x200 (unmapped memory)

crashes ps3. game name: WET. happens when creating a new game.

Intel 12th gen i3
16.00 GB
Win11
6650 XT

**Comment by AniLeo** [comment]
Locking due to spam with completely different crashes on completely different games
