### ISSUE TITLE
Crashing in Persona 4 arena ultimax

### ISSUE THREAD

**Issue by Yumeora** [RPCS3/rpcs3#8845]
OS: Windows 10 x64
CPU: AMD Ryzen 7 4700u @2Ghz
GPU: AMD [Radeon]
Ram: 8GB

All my drivers are updated

The game opens normally and perfectly as usual but as soon as a skip the intro the game freezes and the screen goes black for about 5 seconds and the emulator crashes as well as the game. This didn't happen before(about a week or two ago) the game was working perfectly, It started up and I could play the game, But then the day after I tried starting up the game and it just didn't work(Did the same thing as described in the beginning. I tried a whole bunch of combination of CPU and GPU emulator settings and none of them worked. I tried re downloading and nothing changed. I really wanna play this game again :(.
 

I have the latest version of RPCS3

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5179956/RPCS3.log): Current version

![crashv2](https://user-images.githubusercontent.com/70852584/92330038-f6a48280-f039-11ea-820d-1628463e8c32.PNG): Current version

![Capture](https://user-images.githubusercontent.com/70852584/92330087-38cdc400-f03a-11ea-9746-f92b6b1f765d.PNG):Settings

![crashh](https://user-images.githubusercontent.com/70852584/92330091-471be000-f03a-11ea-85d4-e8d4eb560222.PNG): Settings

![ddadadad](https://user-images.githubusercontent.com/70852584/92330101-57cc5600-f03a-11ea-942c-3b9c6e947068.PNG): Downloaded old version, still didn't work (0.0.11)

(https://github.com/RPCS3/rpcs3/files/5179930/RPCS3.log) :old version 0.0.11(20 days ago)

This doesn't happen in other games.

**Comment by kd-11** [comment]
Sounds like corrupted cache or savedata, I would suggest to clean all the caches and rebuild afresh (right click game-> clear all caches). If it was just a regression with the program then going back to an older build would have fixed the issue.
If nothing else works you can move everything in /dev_hdd0/home/000001/savedata somewhere else, let the game boot and if it does so correctly, try copying back your persona saves one at a time (they are numbered based on save slot)

**Comment by kd-11** [comment]
Update or close.

**Comment by digitaldude555** [comment]
![Screenshot (321)](https://user-images.githubusercontent.com/26138653/107143204-68ac2b00-693c-11eb-9ad3-913fb362f5f3.png)
It doesnt crash.

**Comment by kd-11** [comment]
Request to reopen if issue persists.
