### ISSUE TITLE
Regression: PPU: LWARX took too long in Yakuza: DS

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8861]
After PR #8849 (v0.0.12-10837-2f3e0044), Yakuza: DS spams PPU: LWARX took too long.
Latest master log: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5187211/RPCS3.log.gz)
Last working build log (0.0.12-10836-5060c779):
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5187205/RPCS3.log.gz)

**Comment by elad335** [comment]
because it adds the logging of it which was previously exclusive for TSX.

**Comment by elad335** [comment]
Close issue
