### ISSUE TITLE
Call of Duty Black Ops Green Screen when changing Resolution Scale

### ISSUE THREAD

**Issue by gamrXerus** [RPCS3/rpcs3#8865]
## Quick summary
Call of duty Black Ops works normal in 720p but changing the resolution scale causes the the game to turn green. Happens on both Lubuntu 20.04 and Windows 10.
720p:
![screen](https://user-images.githubusercontent.com/19245344/92484066-84f24300-f1b7-11ea-80b7-ca3960f586b0.jpg)
4k:
![screen](https://user-images.githubusercontent.com/19245344/92484387-9cc9c700-f1b7-11ea-8cf5-d41c20dbf876.jpg)

720p log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5188663/RPCS3.log.gz)
4k log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5188664/RPCS3.log.gz)
720p RSX capture:
https://drive.google.com/file/d/1BXF75ekYbKj_0KXE5nbJm4G14jOD1TXw/view?usp=sharing
4k RSX capture:
https://drive.google.com/file/d/15tK6C3AX7Osf2efK2UjnHhBeRV9TRWtK/view?usp=sharing

* OS: Lubuntu 20.04 and Windows 10
* CPU: Core i5 8600K
* GPU: Nvidia GTX1060 6GB
* Driver version: 450.66 and 452.06

**Comment by jeremybris** [comment]
Same effect in:
- Stranglehold
- James Bond 007: Blood Stone
- Turok

**Comment by RainbowCookie32** [comment]
Test if increasing Resolution Scale Threshold fixes it (64x, 128x, 256x, 512x).

I don't think issues with scaling are really supposed to be reported since it's technically a hack, and games might show unexpected results sometimes.

**Comment by gamrXerus** [comment]
> Test if increasing Resolution Scale Threshold fixes it (64x, 128x, 256x, 512x).
> 
> I don't think issues with scaling are really supposed to be reported since it's technically a hack, and games might show unexpected results sometimes.

Tested with increased Resolution Scale Threshold. No Luck.

**Comment by kd-11** [comment]
Unless it is a regression there is no point in reporting these. Not all data can be upscaled without causing issues and games often have hardcoded values internally for the resolution they were compiled to run at.

**Comment by jeremybris** [comment]
@gamrXerus set "Resolution Scale Threshold" x512 to fix.

**Comment by gamrXerus** [comment]
@jeremybris  yeah, setting it to 1024 makes the game look the same as it does without any resolution scaling. I guess I'll have to settle for setting the default resolution to 1080p and checking Stretch to Display Area. Thanks.

**Comment by Asinin3** [comment]
I know this is closed, but should be fixed with https://github.com/RPCS3/rpcs3/pull/9337 should work with res scaling, no need for threshold change

**Comment by gamrXerus** [comment]
I can confirm pr 9337 fixes this issue. :)
