### ISSUE TITLE
Black Ops 3 Crashing, please help!

### ISSUE THREAD

**Issue by TNTMinecart54** [RPCS3/rpcs3#8870]
So, I tried playing Black Ops 3 for some reason, I guess because I started on the last gen version. And whenever it compiles shaders it crashes. Or it just crashes out of nowhere. I don't know how to fix it or how to make it actually work without crashing. 

[Black Ops 3 Log.txt](https://github.com/RPCS3/rpcs3/files/5191182/Black.Ops.3.Log.txt)

![Wow](https://user-images.githubusercontent.com/26980863/92529752-159d4300-f1f9-11ea-94fb-caf2154cffdd.PNG)

Graphics aside, it should be running fine, but the game crashes at very random moments.

Normally, on a real PS3, the game would run perfectly fine with no issues whatsover. Now I never played it on PS3, I had a 360, but the game runs the same no matter what.

PC Specs:
Windows 10 Pro 64-Bit
Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz, 2496 Mhz, 4 Core(s), 8 Logical Processor(s)
NVIDIA GeForce GTX 1650
Driver Version: 452.06 (latest)
8 gigs of Ram

Wanting to run this to make a comparison video for next gen as I currently do not have the capability of recording last gen on real hardware and I don't have the last gen game anymore.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
