### ISSUE TITLE
Grand Theft Auto IV [NPEB00882] Broken Lights on Vulkan

### ISSUE THREAD

**Issue by MsDarkLow** [RPCS3/rpcs3#8877]
## Quick summary
GTA 4's car lights seem to be broken on Vulkan and nvidia only. On OpenGL they render Correctly.

## Details
Windows 10 v2004
8700k @ 4.7GHz
GTX 1070 (452.06)
RPCS3 0.0.12-10852  (10857 already tested)

Bug is shown right at the start of the game during nighttime, when you are in the car, the lights projected by the car's headlights seem to not show correctly. The pictures will explain my themselves.
They were tested with WCB enabled.

Known to be Nvidia bug only.

[GTA4 Lights OpenGL.log.gz](https://github.com/RPCS3/rpcs3/files/5197446/GTA4.Lights.OpenGL.log.gz)
[GTA4 Lights Vulkan.log.gz](https://github.com/RPCS3/rpcs3/files/5197447/GTA4.Lights.Vulkan.log.gz)

## The Graphical Issue
On Vulkan
![Vulkan](https://user-images.githubusercontent.com/9060436/92641712-0bea0d00-f2d7-11ea-8bcf-110afba57309.jpg)

On OpenGL
![OpenGL](https://user-images.githubusercontent.com/9060436/92641722-0e4c6700-f2d7-11ea-8343-9453a350099c.jpg)

RRC Vulkan: https://cdn.discordapp.com/attachments/442667232489897997/753329643678859354/Vulkan_NPEB00882_20200909194450_capture.7z
RRC OpenGL: https://cdn.discordapp.com/attachments/442667232489897997/753329555346948126/OpenGL_NPEB00882_20200909195056_capture.7z

Very Important:
I'm gonna buy a 3080 :o)

**Comment by kd-11** [comment]
Still an issue after shader decompiler rewrite?

**Comment by MsDarkLow** [comment]
I'm now with a RTX 3080, the issue seems to not occur, closing the issue.
Nice one!
![Fixed](https://user-images.githubusercontent.com/9060436/96374214-31d1bf80-1169-11eb-8fbf-76ee7ba49567.jpg)

**Comment by kd-11** [comment]
Can we identify which generations of hardware are affected? Also, try enabling "High precision Z" option and disabling fp16 emulation, which is the main difference in handling between GPU generations.

**Comment by MarioSonic2987** [comment]
It's still bugged even with High precision Z-buffer and disabling fp16 emulation. GTX 1060 and driver version 456.71:
![image](https://user-images.githubusercontent.com/20027681/96375772-49b23f00-117b-11eb-871d-45046ead23e9.png)

**Comment by kd-11** [comment]
So only turing and ampere are immune to this? Could be a driver issue afterall.

**Comment by MsDarkLow** [comment]
I did the same, enabled High Precision Z-Buffer and disable fp16 emulation. RTX 3080 (456.71)
The game still shows correctly to me.
![Fixed](https://user-images.githubusercontent.com/9060436/96375924-ebce2900-1173-11eb-9456-26ec39e195a5.jpg)

**Comment by Asinin3** [comment]
![image](https://user-images.githubusercontent.com/15137035/106307338-22f1c180-62af-11eb-8786-c82cde59c29c.png)
Fixed on Pascal (tested by me)
Fixed on Maxwell (Tested by Mario Sonic)
![image](https://cdn.discordapp.com/attachments/442667232489897997/804763043665018910/unknown.png)
