### ISSUE TITLE
Bug: Watch_Dogs graphical glitches

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8902]
Watch_Dogs has some weird shadows overlaid on top of the screen and the player shadow is bugged. Tested on latest master (RPCS3 v0.0.12-10876-fe9c61fe) with CPU Blit, all buffers and SRM.

![Screenshot_10](https://user-images.githubusercontent.com/1712979/93027852-82a94200-f618-11ea-8c0a-983c7c9a7b91.png)
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5215043/RPCS3.log.gz)
RRC: https://www.dropbox.com/s/swyypp2b0d86xtt/BLES01854_20200913232530_capture.7z?dl=0

EDIT: tested with accurate xfloat in addition to the settings mentioned above and it made no difference. Disabling every setting mentioned also makes no difference.

**Comment by xddxd** [comment]
one more bug: the game is very blurry on a GTX 960 running driver 496.49, while it's fine on an RX 580 driver 21.10.3:

GTX 960 496.49:
![watchdogs960](https://user-images.githubusercontent.com/1712979/140643391-ef6640fc-3121-4828-b823-b559ceb38bde.png)

RX 580 21.10.3
![watchdogs580](https://user-images.githubusercontent.com/1712979/140643402-75d4c2ea-85e0-462d-a4e8-887f9e6bcb6d.png)

RSX captures:
https://www.dropbox.com/s/m9nh1b50fmlpwdc/watchdogs.7z

**Comment by SlyCooperReloadCoded** [comment]
That's interesting, it's blurry on my RTX 2080 Super.

**Comment by SlyCooperReloadCoded** [comment]
Yeah, this is still an issue by the way.  I assume that's what his RenderDoc captures are for.
