### ISSUE TITLE
Text/General Sprite Misalignments(Ace Combat, Assault Horizon, Infinity)

### ISSUE THREAD

**Issue by Rythus711** [RPCS3/rpcs3#8905]
Both games are developed on the same engine, Ace Combat Assault Horizon is a standalone game that can run in-game with graphical glitches, when Ace Combat Infinity is a already defunct F2P online service game with both new and reused assets from ACAH, until now the game didn't reached into gameplay by the strict coding that it needs connection to the server always, even for offline mode checks like campaign missions.

Both games, despite i'm unsure of ACI file containers by both begin heavy encrypted with XOR, so most of the analysis was made with CE memory research, uses in-house files from Bandai Namco, some textures is based on the GIDX technology, which are in a nutshell DDS textures, and the fonts mostly are rendered with a fontsheet for all the languages included, in Vulkan and GL, the fonts will glitch mostly getting random glyphs from the Asian countries typefaces. another common texture containers, are .nut and the NTP3 header. correcting the texts both on Vulkan and GL currently are the most on my wishlist, due i'm trying my best to datamine ACI, but couldn't be sure of the error messages thanks to the glitched text, as overall in-game models graphical issues will take a bit more fix, understand clearly, ACAH still they got a suprising perfomance by begin playable despite with those glitches in a mid-tier computer, the glitched glyphs occurs in all the menus in game(show on the pictures below), each font glyph is different depending of the UI menu, along as image, logo and BG sprite assets are also glitched in wrong orietation.

[captures.zip](https://github.com/RPCS3/rpcs3/files/5216921/captures.zip)
![screenshot-2020_09_14_04_31_02](https://user-images.githubusercontent.com/61708808/93059301-e5b1cd80-f646-11ea-803b-3608822917ed.png)
![screenshot-2020_09_14_04_31_04](https://user-images.githubusercontent.com/61708808/93059304-e6e2fa80-f646-11ea-89fc-4d3a36e0b939.png)
![screenshot-2020_09_14_04_31_06](https://user-images.githubusercontent.com/61708808/93059308-e6e2fa80-f646-11ea-9004-6502bcdfd2ed.png)
![screenshot-2020_09_14_04_32_09](https://user-images.githubusercontent.com/61708808/93059309-e77b9100-f646-11ea-8894-7a709e2df1a6.png)
![screenshot-2020_09_14_04_32_15](https://user-images.githubusercontent.com/61708808/93059311-e8142780-f646-11ea-838d-97675e2cf4c6.png)
![screenshot-2020_09_14_04_32_21](https://user-images.githubusercontent.com/61708808/93059312-e9455480-f646-11ea-973f-cf1b110f1b4f.png)
![screenshot-2020_09_14_04_32_59](https://user-images.githubusercontent.com/61708808/93059315-e9ddeb00-f646-11ea-8542-d25ba42ca625.png)
![screenshot-2020_09_14_04_33_36](https://user-images.githubusercontent.com/61708808/93059318-e9ddeb00-f646-11ea-9454-8e0001de9e64.png)
![screenshot-2020_09_14_04_34_45](https://user-images.githubusercontent.com/61708808/93059320-ea768180-f646-11ea-922f-b59ca155964b.png)
![screenshot-2020_09_14_04_34_47](https://user-images.githubusercontent.com/61708808/93059324-eb0f1800-f646-11ea-900e-9d74c3a27e3a.png)
![screenshot-2020_09_14_04_34_50](https://user-images.githubusercontent.com/61708808/93059325-eb0f1800-f646-11ea-829d-123bda268476.png)
![screenshot-2020_09_14_04_34_54](https://user-images.githubusercontent.com/61708808/93059327-eba7ae80-f646-11ea-8a40-397a013548fa.png)
![screenshot-2020_09_14_04_35_04](https://user-images.githubusercontent.com/61708808/93059328-ec404500-f646-11ea-8abb-a9dae9958154.png)
![screenshot-2020_09_14_04_35_18](https://user-images.githubusercontent.com/61708808/93059332-ecd8db80-f646-11ea-80e3-e1a2a89603da.png)
![screenshot-2020_09_14_04_35_32](https://user-images.githubusercontent.com/61708808/93059334-ed717200-f646-11ea-932b-5897a4f8d2df.png)
![screenshot-2020_09_14_04_36_15](https://user-images.githubusercontent.com/61708808/93059335-eea29f00-f646-11ea-901a-069a9c74435b.png)
![screenshot-2020_09_14_04_36_25](https://user-images.githubusercontent.com/61708808/93059338-ef3b3580-f646-11ea-9722-726956c87c72.png)
![screenshot-2020_09_14_04_36_49](https://user-images.githubusercontent.com/61708808/93059342-f06c6280-f646-11ea-85c3-aa2d5b79fa44.png)
![screenshot-2020_09_14_04_37_34](https://user-images.githubusercontent.com/61708808/93059354-f2cebc80-f646-11ea-9f20-00a8b0d7d5e1.png)

ACI and ACAH Correct UI samples will be linked on YT links :
https://youtu.be/_puDZJYNRtw
https://www.youtube.com/watch?v=wqKf9fHEB7A

Font Glyphs Texture ripped sample :
![Tex_0061](https://user-images.githubusercontent.com/61708808/93059636-62dd4280-f647-11ea-968a-bdfaa977245e.png)

**Comment by MarioSonic2987** [comment]
GTA V has this similar bug with the UI. It's already reported in #3959.

![image](https://user-images.githubusercontent.com/20027681/93190783-10ce1700-f744-11ea-9e07-33811e89c3f8.png)
![image](https://user-images.githubusercontent.com/20027681/93190809-17f52500-f744-11ea-8f82-e135147cc479.png)

**Comment by jeremybris** [comment]
#8718 and #8395 . Scott Pilgrim is similar, but fixed by "Disable Vertex Cache".
