### ISSUE TITLE
[Feature Request] SYCL implementation

### ISSUE THREAD

**Issue by nitroos-ai** [RPCS3/rpcs3#8912]
Is it possible to implement hipSYCL or any other SYCL library to accelerate shader or/and SPU compiling at the beginning of each game.

https://www.khronos.org/sycl/

https://github.com/illuhad/hipSYCL/commits/develop

**Comment by kd-11** [comment]
RPCS3 does not leverage HSA and likely never will. Until we get large enough GPUs on-die this is just a fading dream. I would have loved for this to happen, but as long as the GPU is a PCI-e bus away, it is not useful for us.
SYCL does not accelerate shader or other code compilation, it just offers an abstraction convencience around other compilers. Where rpcs3 is slow e.g in shader compilation is not the compilation step, it is the GPU driver itself acccepting the code we generated.

**Comment by nitroos-ai** [comment]
Thank you for the clarifications.

**Comment by nitroos-ai** [comment]
Could this library help or is it based on the same concept as SYCL.

https://ispc.github.io/perf.html
