### ISSUE TITLE
hello can you help me to solve my issue i get fatal error every time i try to run any game at vulkan

### ISSUE THREAD

**Issue by halwest355** [RPCS3/rpcs3#8914]
here is my log ;
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5232026/RPCS3.log)

**Comment by bevanweiss** [comment]
You should retest (and resubmit log) with the latest version of rpcs3,  and the latest Nvidia graphics drivers.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
