### ISSUE TITLE
[Feature Request] implement NVIDIA c++ library to use CUDA.

### ISSUE THREAD

**Issue by nitroos-ai** [RPCS3/rpcs3#8936]
NVIDIA has open sourced their c++ library. I though it could be helpful.

https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-libcuxx-Cpp-Standard-Lib

https://github.com/NVIDIA/libcudacxx

**Comment by clienthax** [comment]
![image](https://user-images.githubusercontent.com/1056270/93689252-9a734100-fac4-11ea-9e59-7b8c827a6ab9.png)
