### ISSUE TITLE
[BLES00029] Virtua Fighter 5 Crash and Graphical Issues

### ISSUE THREAD

**Issue by LodanZark** [RPCS3/rpcs3#8939]
Virtua Fighter 5 crashes always when it's displayed the "Now Saving ..." Screen
![saving](https://user-images.githubusercontent.com/11250310/93710892-db5d6b00-fb41-11ea-9c5a-495b0d256dda.png)
[RPCS3 log.zip](https://github.com/RPCS3/rpcs3/files/5251628/RPCS3.log.zip)

**Comment by LodanZark** [comment]
The water in this map gets glitched when the resolution scale option gets increased.
![vf5_1](https://user-images.githubusercontent.com/11250310/93711092-3e9bcd00-fb43-11ea-8cd2-2a7211fd60be.png)

**Comment by LodanZark** [comment]
Snow disappears randomly after the match start in this map:
Before
![vf5_2](https://user-images.githubusercontent.com/11250310/93716960-900b8280-fb6a-11ea-8f8c-53d64344ee6c.png)
After
![vf5_3](https://user-images.githubusercontent.com/11250310/93716965-96016380-fb6a-11ea-9cbe-3723e7ca6185.png)

**Comment by kd-11** [comment]
Only report glitches that are present running at the native resolution without upscaling. Leave all graphics options at default and see if the issue still occurs. If it does, provide the required information for filing bug reports (log files and RSX captures)

**Comment by LodanZark** [comment]
@kd-11 with native resolution and scale, the crash remains, here the log and capture:
[BLES00029_20201020003155_capture.zip](https://github.com/RPCS3/rpcs3/files/5405419/BLES00029_20201020003155_capture.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5405418/RPCS3.log.gz)

**Comment by LodanZark** [comment]
The snow stills disappear:
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5405426/RPCS3.log.gz)
Capture: https://www2.zippyshare.com/v/HFn6heoZ/file.html

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by Monsterclip** [comment]
Still getting the issue where the game stops responding when it says Now Saving...

**Comment by scju** [comment]
> Tested in 0.0.31-16300 not any issue so being both bugs are fixed. That issue can be closed.

In 0.0.33-17071, the graphical issues still remain when I change the resolution scale to 150% (1920*1080), but they seem to be fixed when I change the resolution scale to 125%, 175%, 200% or 225%. 

However, when I change the resolution scale to above 150%, the lights in some stages look like "grids", for example in the Aurora stage.

**Comment by scju** [comment]
> Resolution scaling issues are not valid. Some games just don't like it if the output is tampered with, nothing we can do about that.

[Updated]
At native resolution without upscaling, when I repeatedly switch between windowed and fullscreen mode using ctrl+enter, the water in the stage becomes glitchy.

If you don't mind, could you please consider reopening this issue?

![2024-11-01_211526](https://github.com/user-attachments/assets/e43e3d2a-6902-42ee-9b37-d13d970c19c3)



[RPCS3.log.gz](https://github.com/user-attachments/files/17599976/RPCS3.log.gz)
[BLES00029_20241101211535_capture.rrc.gz](https://github.com/user-attachments/files/17599978/BLES00029_20241101211535_capture.rrc.gz)

**Comment by Augusto7743** [comment]
You are using what GPU and API ? Opengl or Vulkan ?

**Comment by scju** [comment]
> You are using what GPU and API ? Opengl or Vulkan ?

3060Ti and Vulkan. Please check my log file. I think you will find all the information you need there.
