### ISSUE TITLE
Ratchet & Clank: ACiT [BCES00511] regression after #8769

### ISSUE THREAD

**Issue by isJuhn** [RPCS3/rpcs3#8944]
## Quick summary
The game didn't use to crash with "Incompatible source and destination format" before PR, now it does.

## Details
When starting the graphically broken and impossible time fixing minigame in the clank section it didn't use to crash, now it does, 100% reproduction rate. Crashes with:
```
Thread terminated due to fatal error: Verification failed: Incompatible source and destination format!
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTexture.cpp:1057)
```
(Line number in master build is now 1129)
#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
#8769

#### 2. Please attach TWO logs:
[Working log](https://github.com/RPCS3/rpcs3/files/5256729/ACiT.10781.gz)
[Broken log](https://github.com/RPCS3/rpcs3/files/5256739/ACIT.10790.zip)

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
I'm not but I have a 16GB renderdoc of the graphical problems in the game that will devour your pagefile and kill your pc if you want it.

#### 4. Please attach screenshots of your problem.
![rpcs3_10790_nR1uy84VOj](https://user-images.githubusercontent.com/26828095/93794495-720c5380-fc38-11ea-805e-1aeec26416fd.png)

#### 5. Please provide comparison with real PS3.
No

#### 6. Please provide your system configuration:
Windows 10 2004
Ryzen 7 3700X
Nvidia GTX 1080 ti
Driver 451.67.0.0

#### Please include.
[Save file](https://github.com/RPCS3/rpcs3/files/5256770/BCES00511_SAVE_2.zip)
Follow the guy, you have quadruple jump to clear large gaps.
Throw a time slow down grenade on the spinning wheel to walk over it.
Kill 2 thingys in the next room with square.
Do the puzzle or pay to bypass by walking over the thingys on the floor and holding triangle.
Walk over to the couch, skip 3 cutscenes.
Walk into the thingy that opens and go into dream world.
Skip dialogue and jump to the big planet.
Start planet time minigame and observe crash 5 seconds later.
Takes 3 minutes.

**Comment by isJuhn** [comment]
This might very well be the same issue as #8846 since they use the same(ish) engine, perhaps this is easier to reproduce?

**Comment by kd-11** [comment]
@isJuhn It needs to be 100% reproducible otherwise we can get lost wondering if its fixed yet or not like that other ticket. Is it really easy to repro? If it is, I can fix it much faster.

**Comment by isJuhn** [comment]
never had it not happen on new builds, probably something like 6-7 times in a row. Only takes a few minutes to get there too, can stream on discord if you want walkthrough, can debug with VS if you want some special info.

**Comment by kd-11** [comment]
So it happens at a specific place? In that case yea, a video of it happening would be helpful.

**Comment by isJuhn** [comment]
Here is a video https://www.youtube.com/watch?v=ZLtbsUmB4IY

**Comment by kd-11** [comment]
Issue confirmed.

**Comment by kd-11** [comment]
PR https://github.com/RPCS3/rpcs3/pull/8949

**Comment by kd-11** [comment]
I have also optimized the image functions, although I have no idea if it makes any difference for this game.
