### ISSUE TITLE
RPCN (Demon's Souls): Issues when using two PCs on the same network. 

### ISSUE THREAD

**Issue by Lil-Sassy** [RPCS3/rpcs3#8952]
## Quick summary
Unable to connect two PCs that are on the same network together through games that use RPCN (Demon's Souls).

## Details

Trying to play Demon's Souls with my roommate

We can connect to other people without any errors but if we try to connect to each other it will always fail but only through RPCS3/RPCN. Fog wall will go up as will the Summoning Phantom / Being Summoned message

 If we use two PS3s and connect to Yuvi's server, it works just fine.

##  Log files

[My Log.zip](https://github.com/RPCS3/rpcs3/files/5258925/My.Log.zip)

[Roommate Log.zip](https://github.com/RPCS3/rpcs3/files/5258924/Roommate.Log.zip)

#### 4. Please provide comparison with real PS3.

When using two real PS3s (on the same network) connected to Yuvi's server. We can play together perfectly fine.
![20200926_015115](https://user-images.githubusercontent.com/2836215/94334045-22fa5180-ff9d-11ea-830a-61a86b28e6b5.jpg)
![20200926_015032](https://user-images.githubusercontent.com/2836215/94334079-25f54200-ff9d-11ea-863d-21a0e6894977.jpg)

#### 5. Please provide your system configuration:
* RPCS3 v0.0.12-10910-34eff440 Alpha
* OS: Windows 10
* CPU: Intel Core i9-9900K
* GPU: GeForce RTX 2080 Ti 
* Driver version: 456.38
* 63.93 GiB RAM

**Comment by bevanweiss** [comment]
Are you both on the same shared internet connection? (I assume so, but want to confirm).
I'm not familiar with rpcs3 / rpcn networking, but it sounds like it might be using a fixed public facing port, and given you're sharing a single internet connection, only one of you gets to have that port.

**Comment by bevanweiss** [comment]
Looking at the rpcs3 side of the commits for rpcn, it does appear that UDP port 3658 is being used for the connection.
I suspect that a regular PS3 possibly does some UPnP 'magic' to negotiate a unique UDP port for the situation where there is more than one PS3 behind a NAT gateway.
Ideal situation would be if you could use wireshark or something  similar (maybe even just checking UPnP status of your router) to see what UDP ports the PS3s are using when you have more than one on the same network.

**Comment by Lil-Sassy** [comment]
> Looking at the rpcs3 side of the commits for rpcn, it does appear that UDP port 3658 is being used for the connection.
> I suspect that a regular PS3 possibly does some UPnP 'magic' to negotiate a unique UDP port for the situation where there is more than one PS3 behind a NAT gateway.
> Ideal situation would be if you could use wireshark or something similar (maybe even just checking UPnP status of your router) to see what UDP ports the PS3s are using when you have more than one on the same network.

I've never used Wireshark before but I'll give it a shot and see what the PS3s are doing. Thank you for the response.

**Comment by bevanweiss** [comment]
Wireshark might be 'tricky'.  You'd essentially need an old-fashioned ethernet 'hub' to connect the 2x PS3s to your internet and to connect a PC into that hub also.  Or a switch with port mirroring (which is how I'd do it).
If you can get information from your internet router on the ports exposed from your PS3s it would be easier.

**Comment by Lil-Sassy** [comment]
> 
> 
> Wireshark might be 'tricky'. You'd essentially need an old-fashioned ethernet 'hub' to connect the 2x PS3s to your internet and to connect a PC into that hub also. Or a switch with port mirroring (which is how I'd do it).
> If you can get information from your internet router on the ports exposed from your PS3s it would be easier.

I wasn't able to get any information from the PS3s via Wireshark nor could my router show me what they were doing. However I ran Wireshark while attempting to connect to my roommate and the error shows up perfectly fine in it.

It basically shows 
Source: My external IP Destination: My PCs Internal IP Protocol: ICMP and then Destination Unreachable (Port unreachable).

Source Port and Destination port are 3658 just as you said.

**Comment by bevanweiss** [comment]
We'd really need to see a full 'conversation' at startup of the two PS3s to identify who negotiates the alternate ports.
I suspect that it might be in the STUN protocol (if it's used here) and a server hint provided back to the second client based upon it already having a a registered entry for the first client on that particular port.

I'm sure it's something that @RipleyTom likely has in a 'todo' list somewhere.

**Comment by tofdz** [comment]
Same problem for me. 2 on the same network and impossible to join.
Got a vpn (vpntunnel) but it doesn't work.

**Comment by aggregate1166877** [comment]
> Which VPN did you guys use ? Would you mind describing the process roughly ? @Lil-Sassy @Mimickal

NordVPN for me. Works well, no latency that I could see. You open it click, click a dot somewhere in your country, and you're done.

You can try the trial if you don't want to commit, just remove your c.card afterwards so you don't get charged for not using it.

**Comment by Mimickal** [comment]
I realize I was asked this several months ago at this point, but I set my own basic VPN up on a remote server I own. I set up an iptables rule on the remote server to forward port 3658 to port 13658 on my local router, which then redirected to my machine on port 3658. This freed up external port 3658 on the local router to forward to my friend's PC.

Kind of elaborate, but it does work.

**Comment by aggregate1166877** [comment]
> > Which VPN did you guys use ? Would you mind describing the process roughly ? [@lil-sassy](https://github.com/lil-sassy) [@Mimickal](https://github.com/Mimickal)
> 
> NordVPN for me. Works well, no latency that I could see. You open it click, click a dot somewhere in your country, and you're done. Used for a whole month without issues, just make sure you log into the VPN _before_ you open RPCS3 or the servers will get confused and think you're already logged in.
> 
> You can try the trial if you don't want to commit, just remove your c.card afterwards so you don't get charged for not using it.

The NordVPN solution no longer works for me :(. Don't know what changed, but we came back after a two year break for a new run and summoning fails with two computers on the same network no matter what we do. Have tried all sorts of things including explicit port binds, meshnet setups, forced UDP focused VPN protocols; nothing works. Can log in and see signs fine, but summoning fails.
