### ISSUE TITLE
RPCN Demon's Souls: multiplayer sessions does not work.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#8954]
I am not really sure if this bug report is not a duplicate of #8952 as I can't compare logs, so I open new issue. 

I got multiplayer invasion working once, but all other attempts to invade or to be summoned failed. I have attached a log with a few attempts to invade someone.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5261660/RPCS3.log.gz)

**Comment by Lil-Sassy** [comment]
This isn't related to my issue because my issue #8952 is clearly about two PCs unable to connect to each other on the same network and no problems to invade or summon outside of that network.

**Comment by isshininu** [comment]
Log with successful multiplayer session (user disconnects in the end)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5285028/RPCS3.log.gz)

**Comment by RipleyTom** [comment]
There is only one JoinRoom in the log which means the DeS server only matched you once, not a RPCN/RPCS3 issue as far as I can see.
