### ISSUE TITLE
Regression Soldner-X Himmelssturmer  [NPEB00074] no long get passed the Trophy sceen

### ISSUE THREAD

**Issue by pppppppppyfv** [RPCS3/rpcs3#8957]
## Quick summary
Please briefly describe what has stopped working correctly.
games stick at Trophy sceen

## Details
Please describe the regression as accurately as possible.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
* Please see [How to find the build that caused a regression](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression.3F) in our wiki.
* rpcs3-v0.0.12-10918-418968d9_win64 cause it
.rpcs3-v0.0.12-10909-0b42cf06_win64 works fine

#### 2. Please attach TWO logs:
* [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5263218/RPCS3.log.gz)
* [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5263225/RPCS3.log.gz)

##### How to obtain RPCS3's log:
* Run the game until you find the regression.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc. 

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc. 
	And drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 4. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.
![Screenshot (77)](https://user-images.githubusercontent.com/66808720/93920220-ded92980-fcdc-11ea-9264-5b7858d7776b.png)
![Screenshot (79)](https://user-images.githubusercontent.com/66808720/93920276-f44e5380-fcdc-11ea-9826-c88d5c597e79.png)

#### 6. Please provide your system configuration:
* windows 10 2004
* ryzen 9 4900hs 
* rtx 2060 max q
* 450.7
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by pppppppppyfv** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5263228/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5263231/RPCS3.log.gz)
here are the logs

**Comment by pppppppppyfv** [comment]
it has been new update

**Comment by AniLeo** [comment]
Removed screenshot that showed piracy website
