### ISSUE TITLE
[Feature Request] debug tab on by default

### ISSUE THREAD

**Issue by pppppppppyfv** [RPCS3/rpcs3#8961]
## 
Can you turn on debug tab first get the emulator because playable games will start useing debug tab like goldeneye 007 reloaded so some please turn on Debug tab on by default open the emulator first time

#### 1. Please describe, what part of RPCS3 would be affected by your feature:UI
* Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.

#### 4. Please provide your system configuration:
* windows 10 2004 
* ryzen 9 4900hs 
* rtx 2060 max q
* 456.30
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by RainbowCookie32** [comment]
Most games don't need anything from the Debug tab, but the Debug tab has a lot of options that can cause issues. Considering users love to touch all settings at random already, I'd rather have it hidden by default for the sake of everyone offering help to other users. It's not like enabling it is too hard either

**Comment by pppppppppyfv** [comment]
Then say goldeneye 007 reloaded is unplayable because lighing debug settings when the game is playable

**Comment by RainbowCookie32** [comment]
You can always enable it for the games that need it. The "cost" doesn't outweigh the benefit here.

**Comment by pppppppppyfv** [comment]
have a settings in the emulator in emulator settings called turn on debug tab so easy turn debug tab for gui of the emulator after a restart

**Comment by RainbowCookie32** [comment]
If you can easily show the hidden tab from the UI it pretty much defeats the whole purpose of hiding it. If anything  moving some settings (like CPU Blit, Disable Zcull queries) could be considered, but I'm not really a big fan of it either.

**Comment by pppppppppyfv** [comment]
Move Disable Zcull queries to the gpu tab because like goldeneye 007 reloaded needs it to be playable

**Comment by pppppppppyfv** [comment]
Find make a pr to trun on debug tab on myself trorrow I do it

**Comment by AniLeo** [comment]
What part of stop spamming you don't understand? Go away
