### ISSUE TITLE
Regression Hot Shots Golf: World Invitational [NPUA80864] not getting passed initial loading screen (cant get in main menu)

### ISSUE THREAD

**Issue by Ethorsen** [RPCS3/rpcs3#8965]
## Quick summary
Hot Shots Golf: World Invitational [NPUA80864] not getting passed initial loading screen (cant get in main menu)
It stays stuck on Auto-Loading.   Tried to erase all home directory with no difference.

## Details
Please describe the regression as accurately as possible.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
This PR created the problem.
https://github.com/RPCS3/rpcs3/pull/8937  -> Build  0.0.12-10918
Was working fine on  Build  0.0.12-10915

#### 2. Please attach TWO logs:
Log with regression Build  0.0.12-10918
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5268603/RPCS3.log.gz)

Log from working Build  0.0.12-10915
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5268607/RPCS3.log.gz)

#### 4. Please attach screenshots of your problem.
![Screenshot_1](https://user-images.githubusercontent.com/1493968/94022610-48137800-fd83-11ea-89ef-aff99e2b0cbc.png)

#### 6. Please provide your system configuration:
* Win 10 x64 1909
* Intel i7-7700
* Nvidia 1060

**Comment by Ethorsen** [comment]
Sure can.  Here's the log from RPCS3 v0.0.12-10924-04deb97f
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5269738/RPCS3.log.gz)

Thx

**Comment by elad335** [comment]
> sceNpTrophyRegisterContext(): Failed to install trophy context '/dev_hdd0/home/00000001/trophy/NPWR04447_00' (Unknown system error)
hmm, also could be fixed by lin latest master by other changes.

**Comment by Ethorsen** [comment]
Just tried with RPCS3 v0.0.12-10941-6164b3d2 ,  no luck

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5279221/RPCS3.log.gz)

**Comment by Ethorsen** [comment]
Seems to be fixed in 0.0.12-10978-2a258dc2.

Thx this can be closed.
