### ISSUE TITLE
[BLES00707] - WET - VM: Access Violation Reading Location 0x3c (unmapped memory)

### ISSUE THREAD

**Issue by web1018** [RPCS3/rpcs3#8969]
## Quick summary
The game appears to experience random freezing/crashes at any given time during gameplay or simply navigating through the main menu. 

## Details
The game has experienced **F {PPU[0x1000015] Thread (During Anim SPU Task Thread) [0x008a61b8]} VM: Access violation reading location 0x3c (unmapped memory)** since 2017 according to RPCS3 compatibility forum posts. It happens at random and no known fix exists to this day in order to get this game to be properly playable. 

## Screenshots
![Capture11](https://user-images.githubusercontent.com/51851411/94177110-11af2900-fe67-11ea-8a50-bd7a84b91aff.PNG)

## Log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5277901/RPCS3.log.gz)

## System Specs 
RPCS3 v0.0.12 - 10939 - 183aa313 Alpha | Hardware Specs :
Nvidia GeForce GTX 960M | Intel Core i7 6700HQ | 16GB of Ram | Windows 10

**Comment by bevanweiss** [comment]
If you try without TSX enabled, does it make it better/worse/same-same?

**Comment by web1018** [comment]
With the TSX being set to "OFF" it makes no difference. It still freezes and this time in a loading screen.

**Comment by mew22-gitch** [comment]
S

**Comment by Loacoon1** [comment]
Same problem with Killzone 3 on a Rizen 3700X CPU. Thing is, it used to work a few monthes ago. Though I didn't finish it, I've been able to play way longer than today.

**E {SPU[0x2000100] Thread (HiPrioCellSpursKernel2) [0x1ac40]} VM: Access violation reading location 0x5ba8e750 (unmapped memory) [type=u0]**

**Comment by nitroos-ai** [comment]
I tried the demo but it crashes with a `VM: Access violation reading location` and this message is spamming the log `PPU: 'sys_interrupt_thread_eoi' aborted`.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/8642875/RPCS3.zip)

**Comment by Darkhost1999** [comment]
Someone shared they're completion of this game in #media sharing information that the game ran well and without this issue can someone retest and validate?

**Comment by Jonathan44062** [comment]
I've been playing it and I haven't run into any crashes, the stability is good, I've played it for 2-3 hours and it didn't stop me from finishing it, I guess that bug is gone and fixed, we can close this ticket for now, reopen it in case if someone has it
No using driver wake up or RSX FIFO, my settings are default
![image](https://user-images.githubusercontent.com/78843189/206814513-3fc150ba-0c17-4f94-ae33-d25cb2bae223.png)

**Comment by elad335** [comment]
Others have not encountered any issues either recently, closing.

**Comment by Jonathan44062** [comment]
It seems the error crash is back
I got the `F {PPU[0x1000016] Thread (During Anim SPU Task Thread) [0x008a61b8]} VM: Access violation reading location 0x3d (unmapped memory)` didn't have it on the past, now is happening, needs this to reopen

[RPCS3.log](https://github.com/user-attachments/files/31404821/RPCS3.log)
