### ISSUE TITLE
Emulator crashes when trying to view config

### ISSUE THREAD

**Issue by toddas90** [RPCS3/rpcs3#8971]
## Quick summary
When I try to open the configuration to edit it, the emulator crashes.

## Details
When clicking on Configuration at the top, or trying to create a custom config for a specific game, the emulator crashes.
```
Assertion failed: var_list.size() == 2 && var_list[0].canConvert<QString>()
(in file ../rpcs3/rpcs3qt/settings_dialog.cpp:648)
```

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5279374/RPCS3.log)

#### 2. Please attach screenshots of your problem.
![Screenshot from 2020-09-24 14-35-13](https://user-images.githubusercontent.com/14827898/94202800-327d7b80-fe73-11ea-8015-316e4dfebee3.png)

#### 3. Please provide your system configuration:
* OS: Pop OS
* AMD Ryzen 9 3900x
* Nvidia GTX 1080ti
* Driver 450.66

**Comment by toddas90** [comment]
Looking at it now, I think I grabbed the wrong log file. I'll find the new one and edit my post soon.

**Comment by toddas90** [comment]
New log is up.

**Comment by bevanweiss** [comment]
If you open your settings file (config.yml from memory, next to the rpcs3 application), do you have an entry in that file which indicates XAudio2?
If so, you should try to delete that line with XAudio2, and then re-run rpcs3 and advise if the problem remains.

**Comment by toddas90** [comment]
Removing the line with X Audio2 fixed it. Any idea why that would cause the issue?

**Comment by toddas90** [comment]
Removing the line with X Audio2 fixed it.

**Comment by sampletext32** [comment]
Likely - something went wrong with file. As exception and log say - parsing error has occurred. Nothing really serious. But I suppose it needs some checks.

**Comment by bevanweiss** [comment]
I suspect the file was copied from a Windows OS computer, where XAudio2 is the default (from memory).
Then when run on the Linux OS it had a stored value to use, but it wasn't within the allowed range.

There is definitely still a bug there however (rpcs3 shouldn't throw exceptions for this), and I'd say that this issue probably shouldn't have been closed.

**Comment by toddas90** [comment]
Sorry, first time posting anywhere. Not really sure how all of this works yet.

**Comment by bevanweiss** [comment]
> Sorry, first time posting anywhere. Not really sure how all of this works yet.
> 
> Yes, the configuration was copied from an old windows pc. I didn't think anything of it at the time.

No need to apologise, it was a good issue report.
