### ISSUE TITLE
Prince Of Persia 2008 - game randomly freezing

### ISSUE THREAD

**Issue by jy95** [RPCS3/rpcs3#8985]
## Quick summary

The game freezes (sound & video) and then crashes
![bug](https://user-images.githubusercontent.com/9306961/94344406-6dbcad80-001f-11eb-8477-d6b6da89e7f2.PNG)

## Details

Please describe the problem as accurately as possible.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5286917/RPCS3.log)

#### 3. Please attach screenshots of your problem.
See above

#### 4. Please provide comparison with real PS3.

No crash

#### 5. Please provide your system configuration:
* OS: Windows 10 - build version 18363
* CPU : Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz | 12 Threads | 15.85 GiB RAM | TSC: 2.208GHz | AVX+ | FMA3
* GPU : GeForce GTX 1050 
* Driver version : 456.38.0.0
* etc.

#### Please include.
Applied game patch "Disable MLAA"

**Comment by AniLeo** [comment]
Is it not an issue without the patch? Needs to be checked

**Comment by jy95** [comment]
Cannot say - last time I check this game, it was on v0.0.7-8689 Alpha [2019-09-10] (and without the patch) and it works :
[Test RPCS3 - Prince of Persia](https://www.youtube.com/watch?v=ihDdJ7tOCe8)
[Test RPCS3 - Prince of Persia Epilogue](https://www.youtube.com/watch?v=PZfDuxgmGfU)

**Comment by AniLeo** [comment]
But if it is a patch issue, then the patch itself needs to be fixed

**Comment by digitaldude555** [comment]
@jy95 update the issue.

**Comment by jy95** [comment]
@digitaldude555 What kind of update do you wish ? 
- Re-test the game with the most recent RPCS3 build (without the game patch)
- Re-test the game with the most recent RPCS3 build (with the game patch)
- ...

**Comment by RainbowCookie32** [comment]
Both

**Comment by jy95** [comment]
@RainbowCookie32 To check if it wasn't relevant to a specific region, I test NPUB30424 and there is also a memory violation, at startup [RPCS3.log](https://github.com/RPCS3/rpcs3/files/5978521/RPCS3.log). I will retry BLUS30214 later ...

![image](https://user-images.githubusercontent.com/9306961/107889124-0097af00-6f11-11eb-92e2-6bbbb772b51c.png)
