### ISSUE TITLE
[Feature Request] Compile mself modules before start of the game

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#8991]
We need to compile mself modules before starting games.
Seems like it's only some "multi self" with a header that points towards self data in the data part?

For example ninja gaiden sigma 2 has a single mself file and occasionally loads single selfs from that file during gameplay, which is very annoying.
So it would be a great quality of life improvement if all modules in that file could get compiled before the game starts.

**Comment by AniLeo** [comment]
Compiling application/game's own sprx modules would also be useful, much like the Create PPU Cache but for every recompilable executable

**Comment by mew22-gitch** [comment]
@
![Screenshot_20200929-101856](https://user-images.githubusercontent.com/72000879/94570446-dcc31d80-023c-11eb-8388-151f4eaed643.jpg)

**Comment by elad335** [comment]
Fixed by #9664
