### ISSUE TITLE
Trophies failed to initialize on linux

### ISSUE THREAD

**Issue by stumts** [RPCS3/rpcs3#8995]
## Quick summary
**Trophies** stop working on **linux** after commit 3a96d9918792051327e150f1382c7e6cf4ff6596.
![Captura de tela de 2020-09-29 09-46-07](https://user-images.githubusercontent.com/30453661/94561708-c1efa980-023a-11eb-9cdd-e039e2e732b3.png)

## Details
Until commit a50ea09053084c536b5b098de6a5b426d26a6c57 trophies works properly, but after commit 3a96d9918792051327e150f1382c7e6cf4ff6596 it won't.

#### Logs:
* Commit a50ea09053084c536b5b098de6a5b426d26a6c57: [RPCS31.log](https://github.com/RPCS3/rpcs3/files/5299135/RPCS31.log)

* Commit 3a96d9918792051327e150f1382c7e6cf4ff6596: [RPCS32.log](https://github.com/RPCS3/rpcs3/files/5299131/RPCS32.log)

#### System configuration:
* OS: Ubuntu 20.04.1
* CPU: i9 9900K
* GPU: RX 580
* Driver version: Mesa 20.3.0-devel (git-62ba074ff514acd93bd3d4f14864a67f813ccab4) / LLVM 12.0.0-devel (git-a2578e92e2928eefa108939b15a7a28c8a8cb4b3)

**Comment by mew22-gitch** [comment]
L

**Comment by stumts** [comment]
I found out the problem. I was using a symbolic link to use the same dev_hdd0 on windows and linux. Instead of doing this, I use Virtual File System in the emulator what solves the problem.
