### ISSUE TITLE
[Feature Request] More performance

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#9000]
Seems like we could get massive performance gains if we implement this:
https://www.youtube.com/watch?v=32UGD0fV45g&ab_channel=6lamborghini
or this:
https://www.youtube.com/watch?v=SiMHTK15Pik&ab_channel=chowderrockz

**Comment by sampletext32** [comment]
Yeah, boost is insane.

**Comment by Megamouse** [comment]
https://www.youtube.com/watch?v=SiMHTK15Pik&ab_channel=chowderrockz

**Comment by illusion0001** [comment]
This is valid issue, as a tracker for performance boost PRs

**Comment by dio-gh** [comment]
As a wise man once said: "more performance, more good". I approve.

**Comment by elad335** [comment]
Moar performance moar good!!!

**Comment by Sylk** [comment]
Less word, more performance. Please.

**Comment by digitaldude555** [comment]
Close it.

**Comment by Satan86** [comment]
:sqvat:

**Comment by elad335** [comment]
This is not very funny as time passes by, close.

**Comment by Thor-x86** [comment]
Well... that will cause pointer to lose its mind. Anyway, stick with binder as shown on video

https://www.youtube.com/watch?v=Tt7bzxurJ1I

It's a lot safer :)
