### ISSUE TITLE
Regression: Audio crackling in Nier Replicant below 30 FPS

### ISSUE THREAD

**Issue by GetBucked** [RPCS3/rpcs3#9001]
Audio issues when framerate drops while using framerate patch.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
