### ISSUE TITLE
A black screen error appeared in Chapter 2 Verse 4 of Drakengard 3

### ISSUE THREAD

**Issue by Gokou-Ruri** [RPCS3/rpcs3#9006]
## Quick summary
Starting from version v0.0.12-12953, a black screen error appeared in Chapter 2 Verse 4 of Drakengard 3.
There is no such problem on 0.0.12-12950 and earlier versions.

#### 2. Please attach TWO logs:
Problem version log (v0.0.12-10953): [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5309743/RPCS3.log.gz)
Normal version log (v0.0.12-10950): [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5309747/RPCS3.log.gz)

#### 4. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/26711804/94773355-2b63e980-03ee-11eb-8105-1b06e7ea203a.png)

#### 6. Please provide your system configuration:
* OS                   Windows 10 LTSC 2019
* CPU                  Ryzen 1700X
* GPU                  GTX1060 6G
* Driver version       451.67

**Comment by AniLeo** [comment]
Update your GPU drivers

**Comment by Gokou-Ruri** [comment]
> Update your GPU drivers

Thank you for your help, everything is fine so far.
