### ISSUE TITLE
AppImage not working on ubuntu 16.04 Lts

### ISSUE THREAD

**Issue by cmatomic** [RPCS3/rpcs3#9008]
Appimages must be generated in order to be compatible with GLIBC 2.23, an older version of Ubuntu LTS must be used as a standard to build appimages.
In this case, as standard, the Lts Uuntu xenial version is currently used.
any doubts see here
https://github.com/AppImage/awesome-appimage

**Comment by AniLeo** [comment]
We already build AppImages on Xenial, but we obviously don't have anyone with such an outdated version to test

**Comment by cmatomic** [comment]
Is not outdated to builld AppImages should be done this way if it is not compatible with other linux distributions

**Comment by AniLeo** [comment]
And what did I just say, we already build on Xenial

**Comment by cmatomic** [comment]
```

user@userpc:~/Transferências$ ./rpcs3-v0.0.12-10967-56cebd99_linux64.AppImage
Debugger: 0
Log file open failed: /home/antonio/.cache/rpcs3/RPCS3.log.gz (error 13)
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

user@userpc:~/Transferências$ 
```
and
unzipped the AppImage and put my own App Run

```
rpcs3: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by rpcs3)
rpcs3: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by rpcs3)
rpcs3: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by rpcs3)
```

**Comment by AniLeo** [comment]
`sudo apt-get install libx11-xcb1 libxcb1 libxcb-xinerama0`

Don't think these can be bundled with AppImage, but feel free to provide a solution if they are, we already ran into issues regarding that before.

Also, we use c++20a, so you need updated glibcxx if you're not launching RPCS3 through AppImage.
We bundle the updated .so, it works when launched from the AppImage on systems with older glibcxx.

**Comment by AniLeo** [comment]
I've just tested that from a clean live setup of Xenial

![image](https://user-images.githubusercontent.com/10283761/94873164-5e39cc00-0446-11eb-8b60-0daf7e9fa8ff.png)

**Comment by cmatomic** [comment]
**What version of ubuntu xenial ?**

![Captura de ecrã de 2020-10-05 17-44-31](https://user-images.githubusercontent.com/33186553/95108521-478bc180-0733-11eb-8c5f-6d4e43a76794.png)

**Comment by AniLeo** [comment]
Latest - 16.04.7

You're missing libxcb-xinerama0, as I've explained in the previous comment

**Comment by hcorion** [comment]
The reason it doesn't work out of the box is because of https://github.com/RPCS3/rpcs3/issues/4509 and the solution to that was not bundling the xcb libs.
It's an unfortunate issue with Ubuntu/Mesa, but it's not something we can really fix. You just have to install the three libraries on Ubuntu and friends to get RPCS3 to work. It's not a big deal.

**Comment by AniLeo** [comment]
Note that the only lib that is not present by default on Xenial 16.04.7 is `libxcb-xinerama0`, the other two are already preinstalled

**Comment by hcorion** [comment]
Gonna close this issue, not really something we can fix on our side, since it's an issue with how Mesa works.
