### ISSUE TITLE
Regression: TES V: Skyrim Legendary Edition crashes the emulator when starting a game (#7939)

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#9009]
After rpcs3-v0.0.9-10114-72d1efa3 (#7939), the game crashes the emulator with no error when the game loading finishes.
Last working build is rpcs3-v0.0.9-10113-f36686b1.
Log from last working build: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5315130/RPCS3.log.gz)
Log from master (RPCS3 v0.0.12-10967-56cebd99): [RPCS3.log](https://github.com/RPCS3/rpcs3/files/5315133/RPCS3.log)

**Comment by elad335** [comment]
Fixed by #9023
