### ISSUE TITLE
Linkage failed: Compute shader(s) were not successfully compiled before glLinkProgram() was called.

### ISSUE THREAD

**Issue by Jerbear077** [RPCS3/rpcs3#9012]
[Log.txt](https://github.com/RPCS3/rpcs3/files/5315954/Log.txt)

Game: Star Wars: The Force Unleashed II (BLUS30534)
Render: OpenGL

**Comment by AniLeo** [comment]
Completely disrespects issue guidelines, also ignores minimum GPU requirements in the Quickstart Guide.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
