### ISSUE TITLE
Ratchet and Clank: Tools of Destruction [BCES00052] - Missing some audio in both cutscenes and gameplay.

### ISSUE THREAD

**Issue by jjw410** [RPCS3/rpcs3#9017]
## Quick summary
Dialogue in cutscenes is missing, as well as dialogue and other SFX in gameplay (notably: Ratchet's wrench swing and the grind rail sound). Changes to decoders or the "audio out" settings did not change this.

#### System configuration:
* OS - Microsoft Windows 10 Pro
* MOBO - ASRock B450 Steel Legend
* CPU - AMD Ryzen 5 3600 6-Core Processor
* GPU - Geforce GTX 970
* Driver version - 456.38

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5318812/RPCS3.log.gz)

**Comment by Bertanos** [comment]
Change the language to english (US) to get working sound. Other languages also work just not uk english.

**Comment by jjw410** [comment]
Fantastic, so it does, I'll be sure to make a note of this in the wiki then! Cheers @Bertanos :)
