### ISSUE TITLE
God of War III lighting becomes extremely oversaturated at beginning of game

### ISSUE THREAD

**Issue by aaronjwood** [RPCS3/rpcs3#9022]
## Quick summary

Right after you kill the first water horse the lightning immediately becomes saturated when the camera pans over to Gaia getting stuck on the mountain side.

![lighting1](https://user-images.githubusercontent.com/446283/94984645-f09fa580-0502-11eb-96e6-9b1221c0f463.png)
![lighting2](https://user-images.githubusercontent.com/446283/94984647-f2696900-0502-11eb-9627-b649ad0d8a5c.png)

## System configuration:
Windows Server 2019 Datacenter
Ryzen 3950x
Nvidia 2080 Ti
GPU driver 456.55
64GB DDR4

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5321179/RPCS3.zip)

**Comment by Asinin3** [comment]
You're not using the correct settings for this game. God of War 3 requires Write Color Buffers be enabled. https://wiki.rpcs3.net/index.php?title=God_of_War_III in the future, ask in our discord server: https://discord.me/rpcs3

Reporting rendering issues on GitHub is typically reserved for regressions, or at the very least tested with multiple settings first and then provide a renderdoc / rsx capture before reporting.

**Comment by aaronjwood** [comment]
Sounds good, my fault on not using the right settings.
