### ISSUE TITLE
BLUS30784 Crashing

### ISSUE THREAD

**Issue by Dorky106** [RPCS3/rpcs3#9025]
## Quick summary
Crashing around the same part every time.

## Details
I boot up White Knight Chronicles 2 (BLUS30784), load in no issues.  I start playing get to the first video after the intro and it crashes. 

#### 1. Please attach RPCS3's log.
http://www.mediafire.com/file/747q77qmjpo3z6k/PS3_Emu.zip/file

#### 3. Please attach screenshots of your problem.
[Error Here](http://www.mediafire.com/view/rin8sexhcd2a22o/ps3error.png/file)
[Error With CPU Util](http://www.mediafire.com/view/btkz8zjxrjrz5ck/ps3error2.png/file)

#### 4. Please provide comparison with real PS3.
No crash, not really sure what else I can put here...
When I played on console before it crapped out the game never had issues.

#### 5. Please provide your system configuration:
* Windows 10
* Ryzen 5 2600
* GTX 1660
* 465.55 (9/28/2020)

#### Please include.
* Anything else you deem to be important

**Comment by digitaldude555** [comment]
@Dorky106 Still crashing?

**Comment by Dorky106** [comment]
@digitaldude555 I can check, as I just check and leave the game for a bit if it happens too often.

**Comment by Dorky106** [comment]
So now not even able to get into the menu for some reason.

**Comment by digitaldude555** [comment]
okay can you put a log here at least.

**Comment by Dorky106** [comment]
Sorry was in the middle of making breakfast.
https://www.mediafire.com/file/4hwh6ac3326kqaf/PS3_Emu-2.zip/file

**Comment by Dorky106** [comment]
Issues seems to be fixed now, as I'm able to get to the game menu.  Getting a new issue but I'll make a new issue regarding that.
