### ISSUE TITLE
Dark Souls II - Black screen when ingame using Vulkan

### ISSUE THREAD

**Issue by Krusher97** [RPCS3/rpcs3#9029]
#### Details
When you get in the game, nothing except the HUD is visible. You can move your character around but nothing is rendered. This happens only with the vulkan backend. The game renders properly using the opengl one.

#### RPCS3's log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5322227/RPCS3.log.gz)

#### Screenshot
![rpcs3_2020-10-04_00-55-21](https://user-images.githubusercontent.com/25664221/95000302-4b0d3480-05dd-11eb-8f7e-11cc7f89fce7.png)

#### System configuration:
CPU:i5 6500 3.2Ghz
GPU:Nvidia GeForce 750 Ti
OS:Windows 7 Ultimate 64-bit SP1

**Comment by AniLeo** [comment]
Not using latest NVIDIA driver

**Comment by Krusher97** [comment]
Updating the drivers actually fixed it
