### ISSUE TITLE
Regression: Freezing in Persona 5

### ISSUE THREAD

**Issue by Kevga** [RPCS3/rpcs3#9042]
## Quick summary
The last few builds freeze Persona 5 after about a minute of gameplay.

#### Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
The issue started occurring with #8265 (build v0.0.12-10957-f4ca6f02)

#### Please attach TWO logs:
[working_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5336832/working_RPCS3.log.gz)
[freezing_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5336849/freezing_RPCS3.log.gz)

#### Please provide your system configuration:
Windows 10 version 2004
Intel i7 8700K
Nvidia GTX 1080 (driver 456.71)

#### Please include anything else you deem to be important
The above log files included patches. Just to rule it out I disabled the patches and tested again. It took a lot longer to freeze, but it did eventually.
Log without patches:
[freezing_no_mods_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5336906/freezing_no_mods_RPCS3.log.gz)

**Comment by elad335** [comment]
Try to disable TSX in CPU settings.

**Comment by Kevga** [comment]
It does not seem to freeze with TSX disabled.

**Comment by Nekotekina** [comment]
Hi, can you test #9048

**Comment by Kevga** [comment]
I can confirm it runs without freezing with that build with TSX enabled. Thanks for your great work.

In case you need it, I have attached a log of a 5 minute play session with that build.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5349342/RPCS3.log.gz)

**Comment by Kevga** [comment]
I tested the newer build from 5 hours ago for a bit longer. After about an hour the screen didn't freeze, but the audio did and FPS reduced from the usual 60 fps down to 10-15. This happened during combat.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5355682/RPCS3.log.gz)

**Comment by Nekotekina** [comment]
Hello, can you retest the same PR?

**Comment by Kevga** [comment]
I played for over an hour with the latest build with no issues. I only tested with TSX enabled.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5359911/RPCS3.log.gz)

**Comment by sampletext32** [comment]
I thing this one can be closed, because PR was merged.
