### ISSUE TITLE
Heavenly Sword™ [BCES00078] - Crash at Picture-in-Picture Moment, VRAM-Related?

### ISSUE THREAD

**Issue by jjw410** [RPCS3/rpcs3#9050]
## Quick summary
Consistent and repeatable crashing at the first PiP section of the game.

## Details
The game used to suffer from a memory leak problem fixed by #8309 and as @kd-11 mentioned in #6253 it uses a lot VRAM. My question is if these crashes are expected behaviour. Another user on the forum had the same issue with a 10GB 3080, but he didn't attach any logs so if he was having the issue presumably he had the render resolution cranked.

The attached log is from 150% resolution scale, scale set to 125% crashed as well. Only 100% (720p) spiked the VRAM up to about 3.3/3.4GB (differed on 2 different runs). I wouldn't expect the render scale increase of 25% to be a big enough jump to cause a crash considering I have a 4GB GTX 970 and the VRAM usage during gameplay before the spike was very similar to the VRAM usage at 720p. Oh, also VBlank rate didn't seem to affect things.

Would love to get a definitive answer on this since there was no response on the forum and I'd like to make a table on the settings that can be used based on your cards VRAM for the wiki :)

#### System Config
* OS - Microsoft Windows 10 Pro
* MOBO - ASRock B450 Steel Legend
* CPU - AMD Ryzen 5 3600 6-Core Processor
* GPU - Geforce GTX 970
* Driver version - 456.38

#### Log
[Heavenly Sword Crash on PiP.log.gz](https://github.com/RPCS3/rpcs3/files/5357461/Heavenly.Sword.Crash.on.PiP.log.gz)

**Comment by Asinin3** [comment]
` MSAA: Auto`
Turn Anti-Aliasing to Off. MSAA + Resolution scaling is where vram gets hit hard when they're used in conjunction with eachother as if it's e.g 8x MSAA internally then res scaling at 200% doubles it.. you can see how that works out poorly in the dual-screen sections in heavenly sword which is then rendering two screens at the same time.

**Comment by lainiwaku** [comment]
kd-11 said 
" I could in theory make the allocation threshold used to detect overallocation dynamic, but it should work just fine as it is right now. There is a balancing act between being aggressive with cleanup and keeping performance good which is why I'm allowing VRAM to grow to 3GB at 720p."

i'm neither a dev neither a native english but if i understand correctly he can't  do better rightnow (btw 3/4 gb Vram  are not much for a gaming pc)

**Comment by jjw410** [comment]
@Asinin3 Woah, you're right! Just ran through it with MSAA off on different resolutions and it really hits VRAM, thankfully with it off VRAM only spikes to 3.2GB at 175% resolution scaling, no crash, which is perfect. Thanks a bunch, I will get some details in the wiki so others aren't left scratching their heads 😄

**Comment by Asinin3** [comment]
I already updated the wiki when i made my last post. Should've done it earlier, but I did post about it allover the forum threads for the game previously.

**Comment by jjw410** [comment]
So you did man, awesome! Yeah, I looked through the forum, but evidently it's super easy for info to get lost in there. The wiki and the discord bot are always my first port of call. Makes everything so much easier being centralised! Thanks a bunch 😄
