### ISSUE TITLE
Ninja Gaiden 3 Razor's Edge freezes

### ISSUE THREAD

**Issue by vanderleivieirainacio** [RPCS3/rpcs3#9056]
![Captura de tela 2020-10-10 162313](https://user-images.githubusercontent.com/46516229/95663359-01f53d00-0b15-11eb-8e41-960420764817.png)

The game (Ninja Gaiden 3 Razor's Edge) is experiencing crashing issues when compiling shaders or just moments after compiling quite frequently (on loading screens, for example).

My PC specifications:
Graphics: AMD Radeon RX 580 4GB (latest version of the video driver)
Processor: AMD Ryzen 7 1700
Motherboard: MSI X370 SLI PLUS.

Could you please take a look at this problem?

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5359802/RPCS3.log)

**Comment by Asinin3** [comment]
At least post RPCS3's RPCS3.log.gz file.

**Comment by vanderleivieirainacio** [comment]
how do i create this log file please?

**Comment by AniLeo** [comment]
Read the issue guidelines, it even has images

**Comment by vanderleivieirainacio** [comment]
I reissued it with the log and an image and I don't know if the image will be of any use (highlighting the error that appears in red in the last line of the log) but I hope it's right.

**Comment by vanderleivieirainacio** [comment]
Finally!! Ninja Gaiden 3 Razor's Edge crashes and freezes fixed in RPCS3 version 0.0.12-11140! Thank you very much for your great work and effort! maybe it was the same error of crashes and freezes in GTA V. Thank you!

**Comment by AniLeo** [comment]
It was probably fixed on 11138, or on an earlier build, since 11140 only changes the debugger
Closing as fixed
