### ISSUE TITLE
KILLZONE 3 freezes with VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by TylerJaacks** [RPCS3/rpcs3#9060]
## Quick summary
KILLZONE 3 freezes with "Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKQueryPool.cpp:45)" when trying to skip the Intro Campaign Cutscene, I am not having issues with any other games that I know of.

UPDATE 1: This happens with the cutscene ends the only difference is the screen is black.
UPDATE 2: This happens when I try to load a bot game to. So I think this happens everytime I try to start the game.
 
## Details

Error: "Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKQueryPool.cpp:45)" 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5362397/RPCS3.log)

![rpcs3_iyg7HxxKxf](https://user-images.githubusercontent.com/1505374/95694461-c8e1c900-0bf7-11eb-88cb-597f1e276792.png)

## System Configuration
* RPCS3 Version: 0.0.12-11001-5bd5a382 Alpha
* OS: Windows 10 Version 2004 (OS Build 19041.508)
* CPU: AMD Ryzen 7 3800X
* GPU: RTX 2080 Ti
* Driver version: 456.71

**Comment by TylerJaacks** [comment]
Any idea what's going on here sometimes I even BSODs here.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/9748
FTR BSODs should be reported to the driver vendor, bad usermode code cannot cause BSODs.
