### ISSUE TITLE
[Feature Request] Working HLE CellSpurs implementation

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#9063]

**Comment by Megamouse** [comment]
We might as well open a feature request for any other module.
I'm gonna close this ticket for that reason.

**Comment by elad335** [comment]
This is important for performance

**Comment by kd-11** [comment]
I believe the end goal for rpcs3 is to completely reverse the PS3 hardware and software, which will mean running without any sony proprietary blobs. So every module will (ideally) be fully HLE in the far future.
