### ISSUE TITLE
Persona 5 not playing sound when using Blue Yeti Microphone

### ISSUE THREAD

**Issue by cherrydonutxo** [RPCS3/rpcs3#9064]
The in-game sound works fine when not plugging in my microphone and use just my headphones instead, but as soon as I plug my mic in, the game no longer plays sound even if I connect the emulator to my microphone in configuration.

I want to be able to play Persona 5 with my microphone plugged in so that I can talk to my friends and play at the same time whilst streaming it to discord, but, it doesn't seem to want to work. I've tried looking up countless guides but the only ones I get are for "Audio stuttering" and that's not the issue I'm dealing with.

**Comment by Asinin3** [comment]
Sounds like a computer problem not a RPCS3 problem...

**Comment by MSuih** [comment]
Yeti has a headphone jack and thus it gets added to windows as audio playback device, and maybe that'll override whatever you have as the default. Make sure that the default is set to whichever device you want audio out from.

![image](https://user-images.githubusercontent.com/19759300/95734426-1c9df200-0c8c-11eb-946b-12122d1ea1b8.png)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
