### ISSUE TITLE
The last of us  all in game sound setting are set to the lowest 

### ISSUE THREAD

**Issue by Nini002** [RPCS3/rpcs3#9067]
The last of us  all in game sound setting are set to the lowest and can not be changed when SPURS is not set to unlimited
system configuration:
* OS Windows 10 Pro
* CPU i7 4770k@4,2
* GPUGTX 1060 3gig
* Driver version 456.71

**Comment by RainbowCookie32** [comment]
> when SPURS is not set to unlimited

Then it's not a valid issue. I can reproduce it here as well, but the setting itself is a hack that games usually don't like.
Games expect a certain amount of SPURS threads to be there, and usually break when it's not the number they expect.
It's impressive that the game even works without it set to Unlimited.

**Comment by AniLeo** [comment]
Closing as Invalid
