### ISSUE TITLE
Regression: Uncharted 1 (#9048)

### ISSUE THREAD

**Issue by nitroos-ai** [RPCS3/rpcs3#9068]
## Quick summary
Game freezes during loading screens with TSX ON but works fine TSX OFF on Linux.

[savegame.zip](https://github.com/RPCS3/rpcs3/files/5366767/savegame.zip)

#### 2. Please attach TWO logs:

[RPCS3_TSX_ON_11002.zip](https://github.com/RPCS3/rpcs3/files/5366675/RPCS3_TSX_ON_11002.zip)
[RPCS3_TSX_OFF_11002.zip](https://github.com/RPCS3/rpcs3/files/5366679/RPCS3_TSX_OFF_11002.zip)

[RPCS3_TSX_ON_10989.zip](https://github.com/RPCS3/rpcs3/files/5366715/RPCS3_TSX_ON_10989.zip)
[RPCS3_TSX_OFF_10989.zip](https://github.com/RPCS3/rpcs3/files/5366716/RPCS3_TSX_OFF_10989.zip)

#### 6. Please provide your system configuration:

* OS:     Lubuntu 20.04.1
* CPU:   i5-4590
* RAM:  12gb
* GPU:   GTX 1070 ti / version: 455.28

**Comment by Nekotekina** [comment]
Can you identify last working build more precisely? Thanks.

**Comment by Nekotekina** [comment]
Please provide log from latest master build.

**Comment by nitroos-ai** [comment]
[RPCS3_TSX_ON_11007.zip](https://github.com/RPCS3/rpcs3/files/5368144/RPCS3_TSX_ON_11007.zip)
[RPCS3_TSX_OFF_11007.zip](https://github.com/RPCS3/rpcs3/files/5368145/RPCS3_TSX_OFF_11007.zip)

**Comment by nitroos-ai** [comment]
[RPCS3_TSX_ON_11007.zip](https://github.com/RPCS3/rpcs3/files/5368177/RPCS3_TSX_ON_11007.zip)
[RPCS3_TSX_OFF_11007.zip](https://github.com/RPCS3/rpcs3/files/5368179/RPCS3_TSX_OFF_11007.zip)

**Comment by Nekotekina** [comment]
Thanks, is it possible to get not truncated logs? Close Emu via exit?

**Comment by Nekotekina** [comment]
Did your last logs even reach the freezing point?
Anyway there is a new PR to test: #9070

**Comment by nitroos-ai** [comment]
The game didn't freeze during loading screen but froze ingame.
[RPCS3_TSX_ON_11012.zip](https://github.com/RPCS3/rpcs3/files/5375322/RPCS3_TSX_ON_11012.zip)

**Comment by Nekotekina** [comment]
Thanks, maybe try https://github.com/RPCS3/rpcs3/pull/9073

**Comment by nitroos-ai** [comment]
Fixed with #9073.
[RPCS3_TSX_ON_#9073.zip](https://github.com/RPCS3/rpcs3/files/5377015/RPCS3_TSX_ON_.9073.zip)
