### ISSUE TITLE
Bug: Need for Speed: Shift stuck on intro

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#9072]
After selecting the language in the game, it proceeds and gets stuck on a black screen.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5374553/RPCS3.log.gz)

Ryzen 7 2700
RX 580 20.9.2
Windows 10 20H2

**Comment by xddxd** [comment]
Needs LLE libsysutil_np_trophy.sprx

**Comment by elad335** [comment]
LLE of any sysutil lib is a horrible hack, reopen.

**Comment by elad335** [comment]
I should explain: the reason we HLE those libraries is that they are based on multi-process communication with VSH which is not implemented atm. Thus the actual functionality of those libraries does not exist with LLE. 
If some games are working with LLE it means both HLE is bugged and that the game may not need this functionality in a way it "just works" with LLE. If you encounter such cases in the future it is important to tell the developers about it.

**Comment by benderscruffy** [comment]
RPCS3 v0.0.26-14704-2f7a2d51 Alpha
goes ingame now 
can be closed

**Comment by YuriNator557** [comment]
Does it go ingame even without using the above LLE? Or removing the trophy files from the game

**Comment by benderscruffy** [comment]
didn't have to do anything at all
just loaded it chose my language and it goes ingame 
no problems at all
