### ISSUE TITLE
Instability after #9048

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#9074]
Modnation Racers can no-longer get Ingame after https://github.com/RPCS3/rpcs3/pull/9048 merged.
Very easy to reproduce, as the game locks up during first few seconds of the game starting up as it's showing a few of the startup graphics.

Another user also on Ryzen had the same issue. So no TSX obviously.
Created general issue as other people have reported instability issues from same Pull Request.
![image](https://user-images.githubusercontent.com/15137035/96009584-5b989700-0e88-11eb-8c97-c619d03a6f38.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5379180/RPCS3.log.gz)

**Comment by Aphelion725** [comment]
#9048 is also causing Fallout 3 to lock up on loading screens with TSX enabled - disabling TSX resolves this issue.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5379927/RPCS3.log.gz)
![Untitled](https://user-images.githubusercontent.com/61633628/96024739-c494f600-0e19-11eb-9d66-f27c04ede3ac.png)

This PR also seems to be causing the black screen after the Sony Computer Entertainment logo in God of War 3 with TSX enabled. It's less common after #9070, but it still occurs on occasion. Disabling TSX also resolves this issue.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5379928/RPCS3.log.gz)
![Untitled](https://user-images.githubusercontent.com/61633628/96024938-18074400-0e1a-11eb-959a-0f7fad0ac886.png)

**Comment by Nekotekina** [comment]
Please test #9075

**Comment by Asinin3** [comment]
Same issue with Modnation racers I'm afraid.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5383450/RPCS3.log.gz)

**Comment by Aphelion42069** [comment]
#9075 seems to have resolved the freezing during loading screens in Fallout 3.

**Comment by Asinin3** [comment]
Closing as issues are resolved.
