### ISSUE TITLE
PPU module in Persona 5 crashes with the LLVM recompiler

### ISSUE THREAD

**Issue by evandark** [RPCS3/rpcs3#9077]
## Quick summary
Persona 5 fails to launch, using the LLVM recompiler. After compiling the last PPU object RPCS 3 displays a Fatal Error Window, and exits.

## Details
Interpreter works, and the LLVM recompiler used to work too. Reproducible on a fresh install, with no patches or other hacks enabled. After crashing, trying to run the game again, compiles a PPU object and crashes again. The name of the compiled objects changes in the non working version from "v3-tane-" something to "v3-kusa-" something, so my guess for the cause is an LLVM compiler update.

* The crash happens both with TSX enabled and with disabled.
* The SPU recompiler does not seem to have an issue, or at least the game still gets in-game with it.

#### Versions
* Not working release: 0.0.12-11001-5bd5a382 Alpha
* Last working release: 0.0.12-10997-3c935f78 Alpha

#### Logs
3 logs are attached:
* [RPCS3-success.log](https://github.com/RPCS3/rpcs3/files/5385529/RPCS3-success.log)  – A clean (all caches cleared) start in the working release
* [RPCS3-error.log](https://github.com/RPCS3/rpcs3/files/5385533/RPCS3-error.log) – A clean (all caches cleared) start in the non-working release
* [RPCS3-minimal-error.log](https://github.com/RPCS3/rpcs3/files/5385534/RPCS3-minimal-error.log) – A minimal start in the non-working release (maybe useful for filtering out the noise?)

#### System configuraion
* OS:  Windows 10 (Version 1909)
* CPU: Intel i7 6700K
* GPU: NVidia GTX 1060 6 GB

**Comment by MsDarkLow** [comment]
Gave a quick test, it seems like the anti-virus (Windows Defender) is blocking a very specific ppu module that is compiled. Feel free to check your antivirus and allow the file, it's a false positive report.

**Comment by evandark** [comment]
Well, I'll be damned! Why Windows Defender, why?!

Thank you! Lately Windows defender just deletes files without ever showing a notification. I've checked, notifications are turned on. I've never guessed that it could be that.

It works when I disable it, I guess I'll add RPCS3 to the exclusions. It may be a good idea for the quickstart guide, or the FAQ, if the antivirus react to the LLVM compiled code in such a rude way, to suggest excluding RPCS 3. This *is* a rather popular game after all.
