### ISSUE TITLE
[GitHub] Automatic git submodule dependency update PRs (dependabot)

### ISSUE THREAD

**Issue by bevanweiss** [RPCS3/rpcs3#9085]
## Quick summary

Really just an issue for discussion around whether it might have some benefits to having something a dependabot configuration for the rpcs3 git submodules so that there is something like a weekly (or fortnightly, or monthly) PR raised for updated git submodules
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

## Details

At the moment, submodules are only updated manually, which isn't terrible.  But it does mean that there can be a tendency for our in-tree dependencies to get significantly out of date with the latest source top-of-tree in the source repository.
This then results in additional complexity to try to get back in-step with the latest.

If we had something that was keeping the dependencies a little closer to top-of-tree by automatically raising a submodule update on some scheduled basis, then it should be easier to identify if a dependency has produced a breaking change for our build configuration, to allow us to keep on top of that.
Breakages not identifiable in the build system will still be a problem... but I think that would be no worse than what we currently have.

**Comment by elad335** [comment]
"if it ain't broken don't fix it", theres no point in updating submodules all the time unless theres a good reason behind it.
1. It may introduce bugs didn't exist in previous version.
2. It wastes developer time of updating them locally and compiling them as well.
3. Newer versions may contain code breaking changes (e.g. a function name was changed) in thos case newer build will just fail to compile, or worse if the breaking change is a functionality change it might introduce bugs.

Thats why it very much needs to be updated manually.
