### ISSUE TITLE
[Feature Request] Really simple check for eboot.bin presence

### ISSUE THREAD

**Issue by Firestorm7893** [RPCS3/rpcs3#9094]
## Quick summary
This is a really minor annoiance but that would be awesome if it were to be added:). Rpcs3 right now threats a file named "eboot.bin" and "EBOOT.BIN" like they aren't the same thing.

## Details
The issue occurs when trying to launch a game from steam. Steam for some reason everytime you create a library with steam rom manager replaces the all caps EBOOT.BIN with an all lowercase one in the path.
So what happens is that instead of launching "rpcs3.exe" "path/to/game/EBOOT.BIN" it launches "rpcs3.exe" "path/to/game/eboot.bin". Windows from what i understand doesn't really make a difference between filenames with different uppercase/lowercase letters but rpcs3 does, so the game will not boot from the shortcut. 
Is it possible then to just add a little check for eboot.bin? Regardless off uppercase/lowercase letters? Or would that break something

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Installation (i think) 
#### 2. Please tell us, why your feature is important to RPCS3.
It would be really handy (at least in my case) because the only solution i found was to rename every EBOOT.BIN to eboot.bin.
This way i can launch the game from steam BUT i cannot launch it anymore from rpcs3 itself, it says no bootable content was found.

Yes this request is a little dumb i know 😅 Sorry for the trouble

**Comment by AniLeo** [comment]
> Rpcs3 right now threats a file named "eboot.bin" and "EBOOT.BIN" like they aren't the same thing.

They aren't. On unix files are case sensitive, you can have both on the same directory.

I think you should file this to Steam ROM Manager.

**Comment by Firestorm7893** [comment]
Ok i'll do that
