### ISSUE TITLE
RDR - SPU block size giga crashes with no errors while compiling

### ISSUE THREAD

**Issue by nathanaccidentally** [RPCS3/rpcs3#9098]
## Quick summary
When choosing the SPU block size "giga" for Red Dead Redemption, RPCS3 crashes to desktop with no errors during the SPU compilation.

## Details
Used to be able to use the giga block size around May but now it's broken again. Clearing SPU cache and restarting doesn't change anything. 

Build 0.0.12-11042

#### 6. Please provide your system configuration:
* Windows 10
* Ryzen 9 3950x
* Radeon 5700xt

**Comment by AniLeo** [comment]
Giga never worked properly, even if you happened to get it to work on one run or another

**Comment by dio-gh** [comment]
Cannot reproduce, closable.
