### ISSUE TITLE
Blitz: The League II [BLUS30203]: VKTextureCache Verification failed

### ISSUE THREAD

**Issue by Hinkiii** [RPCS3/rpcs3#9100]
## Quick summary
Please briefly describe what is not working correctly.

When loading from menus into anything with 3d rendering, rpcs3 crashes with VKTextureCache verification errors

## Details

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5406024/RPCS3.log)

#### 3. Please attach screenshots of your problem.

![image](https://cdn.discordapp.com/attachments/272875751773306881/753205566569971752/unknown.png)
![image](https://i.imgur.com/z5qu6nP.png)
#### 4. Please provide comparison with real PS3.

Can't atm

#### 5. Please provide your system configuration:
* OS Windows 10
* CPU Ryzen 7 3700x
* GPU GTX 970
* Driver version 456.71
* etc.

#### Please include.
* Anything else you deem to be important

https://youtu.be/1vV-kZgZCBE

**Comment by Hinkiii** [comment]
![image](https://cdn.discordapp.com/attachments/272875751773306881/767976403979075594/unknown.png) 

ingame without texture cache verification

**Comment by Hinkiii** [comment]
Game also still suffers from mutex errors but that's off-topic

**Comment by Hinkiii** [comment]
Still crashing on #9738
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7590117/RPCS3.log)

**Comment by kd-11** [comment]
This game does not boot on master. Stops at data installation screen each time and tries to reinstall data forever.

**Comment by Hinkiii** [comment]
Assuming you reached the installation complete/back out to dashboard prompt you can just grab INSTALL_COMPLETE.DAT and put it into the USRDIR folder. But if it's stopping before that well that's just cause the game randomly freezes on any release afaik.

**Comment by kd-11** [comment]
It's a SFO issue with application version. I'll just add the fix for this with the other patches.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/11349
