### ISSUE TITLE
[REGRESSION] Global & Custom configuration for games

### ISSUE THREAD

**Issue by Killer-9000** [RPCS3/rpcs3#9110]
## Quick summary
When opening the custom configuration for a game an assert is now thrown.

## Details
When opening up the configuration after the performance commits, the four commits around that time, it now fails an assertion,

`SIG: Thread terminated due to fatal error:
Assertion failed: var_list.size() == 2 && var_list[0].canConvert<QString>()
(in file C:\Users\luke\Desktop\rpcs3\rpcs3\rpcs3qt\emu_settings.cpp:294)`

## Extension
Just checked to see if the global configuration was doing it, should have done that before hand I know.

`CFG: EnhanceComboBox 'MSAA' tried to set an invalid value: false. Setting to default: false
CFG: EnhanceCheckBox 'Stretch To Display Area' was used with an invalid emu_settings_type
CFG: EnhanceCheckBox 'Multithreaded RSX' was used with an invalid emu_settings_type
SYS: 
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000010 at 00007ff80977fa86.
Thread id = 15356.
Instruction address: 00007ff80977fa86.
Module name: 'Qt5Core.dll'.
Module base: 00007ff8096c0000.
RPCS3 image base: 0000000000010000.`

**Comment by bevanweiss** [comment]
Remember... when raising regressions you need to supply logs for the commit before the issue, and logs for the commit that causes the issue.

For this particular issue you might want to try the new release after deleting your configuration file also, I haven't seen this error in my testing.

**Comment by Killer-9000** [comment]
Not getting this issue anymore after pulling latests changes, so it was either fixed, or my clone was messed up, so I think we can close this if you want.
