### ISSUE TITLE
Ni No Kun [NPUB30932}i: Graphical Error with Vulcan

### ISSUE THREAD

**Issue by chanfriendly** [RPCS3/rpcs3#9115]
## Quick summary
Everything turns blue in Vulcan

## Details
Title Screen, set up, and opening movies all display properly. As soon as I can take control, everything loads blue with random lines and almost see through, like a blueprint. If I switch to OpenGL it doesn't persist, but runs ~10fps.

#### 1. Please attach RPCS3's log.
Attempted to attach, but it was an empty GZ file

#### 3. Please attach screenshots of your problem.
Attached![Screenshot (2)](https://user-images.githubusercontent.com/73314445/96931190-e847e400-148a-11eb-8cb0-74c25ed13938.png)

#### 5. Please provide your system configuration:
* OS Windows 10
* CPU Ryzen 2600x
* GPU AMD Radeon RX 5700XT
* Driver version 20.9.1 (Up to date)

**Comment by chanfriendly** [comment]
![Screenshot 2020-10-22 172924](https://user-images.githubusercontent.com/73314445/96931977-298cc380-148c-11eb-9063-164f2db34d37.png)

For what it's worth, if I try to play on in OpenGL, it will sometimes hit 30 fps, but I'll also get the diagonal line seen in screenshot.

**Comment by xddxd** [comment]
Try disabling MSAA (Anti-aliasing) and retest with Vulkan

**Comment by chanfriendly** [comment]
> Try disabling MSAA (Anti-aliasing) and retest with Vulkan

That.... was such an easy fix and has to be the only thing I haven't tried.

You're the best!

**Comment by xddxd** [comment]
It's a duplicate of #6999
