### ISSUE TITLE
rain [NPUA80719] Locker Hideout Bug

### ISSUE THREAD

**Issue by Evil0Dead** [RPCS3/rpcs3#9123]
there's mission that you have to hide in locker to prevent killer from seeing you .. but the character is hide outside of the locker which killer can see you and downs you , once you press hide button , you can no longer get out or do anything .

this is how it looks in RPCS3

![2](https://user-images.githubusercontent.com/54598787/97096596-754f9080-1677-11eb-8d0b-4fb1ade38bc5.jpg)

this what it should be 

![11](https://user-images.githubusercontent.com/54598787/97096604-87313380-1677-11eb-8a0e-6e4bbaf33eda.jpg)

log

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5433986/RPCS3.log.gz)

rsx

https://gofile.io/d/1yk1Oy

**Comment by Megamouse** [comment]
looks like this is an old bug. I had the same issue back in 2017

**Comment by Realmantik** [comment]
@Evil0Dead , I didnt experienced any bugs in this scene. Played with accurate xfloat on v.0.0.12-11088, but my version is NPEA00394.

**Comment by Asinin3** [comment]
Retest with Accurate Xfloat on @Evil0Dead close if fixed.

**Comment by Evil0Dead** [comment]
@Asinin3 No .. still have the problem .

**Comment by Megamouse** [comment]
Please test again

**Comment by AniLeo** [comment]
I didn't have this issue while playing the game, needs retest otherwise will close as solved

**Comment by Evil0Dead** [comment]
its fixed now .. still showing your character visual if you stand still but most importantly its works now thanks guys
