### ISSUE TITLE
[Bug Report] Dualshock 4 is not detected in-game unless "Gamepad Settings" is brought up first.

### ISSUE THREAD

**Issue by jjw410** [RPCS3/rpcs3#9130]
## Quick summary

Unless your controller is connected before you launch a game, the gamepad will not be detected automatically in-game.

## Details

Maybe more an overlooked feature than a bug, but something I've been dealing with throughout my time RPCS3. If your controller is not connected by the time you launch a game, and then you connect your controller, the game will not detect a gamepad input. You have to then open the gamepad settings and then the game will recognise the controller.

This comes up every time I use the emulator as I use only use the keyboard before a game is launched. Would be a great QOL update.

#### System Configuration:

* OS - Microsoft Windows 10 Pro
* MOBO - ASRock B450 Steel Legend
* CPU - AMD Ryzen 5 3600 6-Core Processor
* GPU - Geforce GTX 970
* Driver version - 456.38

**Comment by Megamouse** [comment]
You didn't post your RPCS3.log file.
Start rpcs3, do repeat the steps you described above until the DS4 works and then close rpcs3.
Then upload the log file here.

Also, you didn't mention how your DS4 is connected to the PC and if you have additional DS4 drivers or software like DS4Windows installed.

**Comment by jjw410** [comment]
Apologies @Megamouse completely slipped my mind, here's the log for the described issue while loading up Prince of Persia (2008).

[Controller_Not_Dected_POP2008.log.gz](https://github.com/RPCS3/rpcs3/files/5435626/Controller_Not_Dected_POP2008.log.gz)

Also, my DS4 is connected via Bluetooth, I do use DS4Windows with other programs but make sure that's turned off for RPCS3, and also make sure that Steam is closed as well. I have my DS4 set up with some special desktop controls in Steam so if I leave it open it'll interfere with RPCS3.

**Comment by Megamouse** [comment]
seems to work with usb for me.
I'll try to use it wirelessly.
I guess that's the issue, since it seems to be the only difference

**Comment by jjw410** [comment]
Thanks @Megamouse I actually just tried it wired there and still had the same problem! So it seems to be more complicated than I thought :/

[Wired-Controller-Not-Detected.log.gz](https://github.com/RPCS3/rpcs3/files/5435648/Wired-Controller-Not-Detected.log.gz)

**Comment by Megamouse** [comment]
I opened a Pull Request that might tell us more by logging more errors.
Please test that version and send another log as before.
If you don't know how to test it, I'm sure someone on the discord server can help you out.

**Comment by jjw410** [comment]
Aphelion gave me a hand since I know nearly nothing about Github! Here's the new log with the #9135 build 😃 

[#9135_Controller_Test.log.gz](https://github.com/RPCS3/rpcs3/files/5435961/9135_Controller_Test.log.gz)

**Comment by Megamouse** [comment]
Well, I know why it doesn't auto-connect, but I'll have to rewrite some stuff to make it work.
It might take a while (not today for sure)

**Comment by jjw410** [comment]
Had this problem for as long as I could remember. Thanks a bunch! You're a superstar @Megamouse  😄
