### ISSUE TITLE
Unable to run app in WIN 10

### ISSUE THREAD

**Issue by kyxap** [RPCS3/rpcs3#9140]
## Quick summary
Unable to open app in windows 10
## Details

Please describe the problem as accurately as possible.

Steps to reproduce:
1) Open app
***Expected*** app is up and running
***Actual*** error displayed, no log is created 

Screens:

![image](https://user-images.githubusercontent.com/3080529/97126215-7aeabc00-16f3-11eb-81fc-80c34b4d9b97.png)
![image](https://user-images.githubusercontent.com/3080529/97126229-84742400-16f3-11eb-9f58-0eb2198d9c8c.png)
![image](https://user-images.githubusercontent.com/3080529/97126245-8fc74f80-16f3-11eb-95ec-81ca494bbd20.png)
![image](https://user-images.githubusercontent.com/3080529/97126295-ad94b480-16f3-11eb-9901-b3c5b286ed6a.png)

PS: 

* OS Windows 10
* CPU i7
* GPU HD
* Driver version ??

#### Please include.
* Anything else you deem to be important

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by kyxap** [comment]
@AniLeo 
did I ask for the help? oh yeah.... I've reported problem. 

to anyone with same issue:
since coders do not check what libs you have on your local machine and do not write any precondition before running this software the simple fix is to download libs from Microsoft: https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by AniLeo** [comment]
There is no problem here, you clearly can't read since the MSVC 2019 link is on the Readme as well as the Quickstart Guide.

You're also completely clueless about what you're saying since you're suggesting installing the MSVC 2015 redistributable for a MSVC 2019 project using C++2a.
