### ISSUE TITLE
Ryzen APUs' GPU VRAM detection problem

### ISSUE THREAD

**Issue by mikairyuu** [RPCS3/rpcs3#9142]
## Quick summary
Playing on Ryzen's apu's gpu constantly throws "Video memory usage exceeding 90%. Will attempt to reclaim resources", which is obviously false as igpu is designed to be drawing its video memory from the RAM.

## Details

Well, I was playing persona on my new ryzen 4500u laptop and had an issue with it. A fatal one. A constant crash on any battle in the palace, and also, just after like 10 minutes of playing. I've tried to change all the settings (like really, almost all of first two tabs, trust me), and it didn't change a thing. Only changing SPU Threads seemed to make a significant improvement on lower values (think it happens because 4500u is a 6 core cpu and rpcs3's default layout is made to match 8 cores but I'm in no way familliar with emulator's concepts of working so just give it a laugh probably and move on). So, then, I've read the logs and have noticed waaaalls of that warning, and checking it up with task manager has led me to that only conclusion - RPCS3 is thinking that dedicated memory on vega is only 512mb, which is true, but vega is made to use RAM as its GPU memory so it shouldn't be an issue. Thus, it seems like RPCS needs to consider ryzen's APUs' GPU with that feature and get around it. Probably it should just ignore the fact that it's overflowing the VRAM, and let the driver handle things, although that sounds amateur as hell. I hope I'm not wrong, but that's probably the furthest I'm able to go myself. Thanks in advance.

#### 1. Please attach RPCS3's log.
It's not going to be of any use probably, but here it is.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5439061/RPCS3.log)

#### Please provide your system configuration:
* OS Windows 10
* CPU Ryzen 4500U
* GPU Radeon Vega Graphics, integrated in 4500u.
* Driver version 20.10.1

**Comment by kd-11** [comment]
Well, we need some kind of limit to avoid running out of memory. The garbage collector basically checks against this value and chooses to allow or reject. Even if we add an option to disable it, there is risk that the GPUOpen memory manager we use may not be able to cope with this unknown amount of available memory that is going to fluctuate constantly as the application runs. Something to remember is that if we allow it to just steal RAM from say an 8GB pool, then its going to be stealing RAM that other processes require. Only that 512MB is dedicated and provided to rpcs3 as memory that is safe to use so I think the collector is right in trying to budget with that limit.
Now, vulkan does allow us to check whether a device is dedicated or integrated, we can use that to allow the user to set their own VRAM limit for integrated GPUs - assuming GPUOpen allows over-allocations which is doubtful.

**Comment by XSonicRU** [comment]
Again, I'm in no way familiar with frameworks you're using there and their limitations, so everything below might be a total nonsense, so you've been warned, but there's just a solid fact that *might* be something too look for - almost all the apps on windows just use their vram 'as usual', they've never ever even been adapted specially for iGPU, and windows/drivers are doing all the allocation stuff for them, solving all the issues. Like, you said there, "allow it to steal the ram", well, it feels against this scheme to me - you shouldn't even start to allocate ram bu yourself, just continue to draw more vram, and windows should theoretically do everything itself, as it does with other apps.

**Comment by kd-11** [comment]
Unfortunately vulkan does not get any driver assistance. If you want to allow over-allocation, you have to implement moving data to and from system memory yourself for example which is a PITA. Its a common theme with the new low-level APIs, which is also why not many games are using them - you're basically on your own, you just get a driver to do basics with the hardware.

**Comment by MineSAT** [comment]
GPU of APU's AMD RYZEN is only have 512Mb memory dedicated for all things, but have a shared ram memory and is slow.
@XSonicRU you don't have a dedicated GPU in your laptop o desktop?

**Comment by AniLeo** [comment]
APUs use system RAM as they please

**Comment by XSonicRU** [comment]
> GPU of APU's AMD RYZEN is only have 512Mb memory dedicated for all things, but have a shared ram memory.
Well, it's not true. These GPUs don't have dedicated memory AT ALL. These 512mb are, too, from the RAM, with the exception of it being fully allocated for the GPU's needs.
>and is slow
Is it really though? Just look up a number of benchmarks - it performs better then GT 1030(GDDR5 memory), and is actually quite decent being able to run any demanding game in 720p (for example, it runs rdr2 45fps). So, the it's not as weak as you'd probably imagine, and certainly its raw power isn't a reason of rpcs crashing.
> @XSonicRU you don't have a dedicated GPU in your laptop or desktop?
I've said that it's a laptop. And yes, it doesn't have any dedicated gpu. Actually, this approach is quite popular - a lot of intel laptops with iGPU run shared memory as well, so it's not only my little problem - a lot of people are facing it potentially, almost every ultrathin laptop user. Sadly, impossible to overcome as it stands...

**Comment by NielsGx** [comment]
Still no workaround ? Persona 5 runs great on Vega 8, but it crash because of vram "limitation"

**Comment by XSonicRU** [comment]
@NielsGx Hello there! Unfortunately, I've finished persona like 3 months ago (on 4500u laptop btw) and have a vague memory of what workaround I've used...   So, for the first thing, it works better on linux. Just because it is lighter so it doesn't consume your precious vram apart from your current process. And what affected things the most for me was changing SPU thread number. iirc on lower numbers crashes were more rare or non-existent, but it lead to rather laggy experience.

**Comment by grzchw** [comment]
> Still no workaround ? Persona 5 runs great on Vega 7+Ryzen 4700u, but it crash because of vram "limitation"
> Vega 7/8 apu are limited to 512mb of "vram", even if you have 16gb of ram.
> 
> The OS/program should automatically allocate more to it, afaik.
> 
> My main laptop doesn't let me allocate more in the BIOS.
> But I can on my work laptop, but even there, I can only choose Auto/256mb/512mb, and not more.
> 
> All games are basically unplayable more than some few minutes.
> If we could just disabke the vram limiter, like in some modern games, it would be a rather straightforward workaround
> 
> Thanks for your hard work.

Please try #8617 build,

**Comment by kd-11** [comment]
> The OS/program should automatically allocate more to it, afaik.

No it does not, you get a readback of how much VRAM is available from the system. Now, it is possible to just bind the 'fake' shared VRAM as video memory in the case of IGPs as a workaround, though this may fail with horrible results depending on the driver. Some device-specific workarounds will be required for this with whitelisting of hardware and drivers. Sigh.
Part of this is an rpcs3 limitation, we only store textures on memory marked as video memory, because using the shared pool on anything other than IGPs will usually slow everything down to a crawl and you can also get the driver simply refusing to allow you to put stuff there. Unfortunately I don't own a ryzen APU that can test workarounds for this, but I will try on my intel laptop.

**Comment by kd-11** [comment]
@mikairyuu @NielsGx 
Please retest current master. If you still have vram problems, download vulkan tools from https://github.com/KhronosGroup/Vulkan-Tools/releases and run "vulkaninfo --show-formats > vulkaninfo.txt" in a command prompt from the same folder. Attach the generated vulkaninfo.txt file for further analysis.

**Comment by kd-11** [comment]
Closing. Video memory management has been improved with ryzen APU VRAM detection being significantly better.
If there are still playable games that cannot be run on this chip, then ask to reopen.
