### ISSUE TITLE
TTY does not get written to the log UI

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#9143]
TTY output currently does not get logged to the log UI
It gets correctly written to TTY.log

Tested on Linux (~/.cache/rpcs3/TTY.log) with spurs_test.self on RPCS3 v0.0.12-11088-8307f82f

**Comment by Megamouse** [comment]
Can't reproduce on windows

**Comment by RainbowCookie32** [comment]
Can't reproduce on Linux either, Manjaro KDE. Everything got logged fine

![image](https://user-images.githubusercontent.com/16805474/97226055-3bcf7000-17b2-11eb-8d10-45fca3c17735.png)

**Comment by AniLeo** [comment]
Solved, there's a TTY option on the Log tab alone that disables TTY and is not available when you right click on the TTY tab itself, weird
