### ISSUE TITLE
[Feature Request] Detect and inform users about Vulkan issues

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#9152]
Users seem to have Vulkan-related software or driver issues that can interfere with RPCS3 operation, such as screen recorders which register misconfigured vulkan layers. The symptoms of such errors include emulator window not displaying at all or fatal errors when opening emulator or booting games.

An [external tool for these issues](https://github.com/13xforever/vkdiag) was created by 13xforever, but I think it would be useful to include this information in the emulator itself as well. The detection should be done early in the emulators startup process, preferably before [this block](https://github.com/RPCS3/rpcs3/blob/2e18df7223444b9068f8639996ad6222ecb28f5b/rpcs3/rpcs3qt/render_creator.cpp#L23) is executed. If possible, the user should be informed about these issues straight away so that they can fix them without needing to contact our support channels. Also, we should research if it were possible to fix some of these issues programmatically, such as disabling unwanted layers if any are found.

**Comment by birdcat87** [comment]
Agreed @MSuih, I have been having problems using the Vulkan renderer with it giving a 
![RPCS3_Vulkan_Demon_Souls_Error_2_vulkan_version_1 2 154 1-21](https://user-images.githubusercontent.com/73905602/99123110-72511b80-25f7-11eb-86bd-fa4677fd37e4.png) for this line of code [](https://github.com/RPCS3/rpcs3/blob/0c7f9458c0bc81dc2b07f50bb84d3e0c0d1889d2/rpcs3/Emu/RSX/VK/VKHelpers.h#L1017).  It shows up whenever I try to start a game with Vulkan.  I have up to date versions of the Vulkan loader and the linux-current kernal.  More advanced Vulkan configurations in the options menu and in emulator vulkan debug tools would be very helpful.  I would note, however, that Vulkan Environment Tools by LunarG does help one detect configuration errors in Vulkan.  What do you think about this idea, @AniLeo?

**Comment by AniLeo** [comment]
That's probably because you're trying to use an Intel iGPU while having Anti-Aliasing enabled, which is not supported by anv.

**Comment by kd-11** [comment]
Just to add to this: we do detect that the hw does not support the feature and log an error message, but some drivers will work around such problems without crashing. e.g old nvidia cards can be forced to use half-floats using emulation and it works fine, or AMDs incomplete support of some MSAA features but it still renders fine. I suppose an exception can be made for intel specifically as they have a record of crashing if you enable something they do not support.

**Comment by birdcat87** [comment]
@AniLeo, sorry for taking so long to reply.  What you said turned out to be correct.  When I turned off Anti-Aliasing, my game booted in Vulkan.  Now that I've heard about it, I've realized that this was documented in the RPCS3 GitHub Wiki under Graphics Driver Issues.  Thank you for your advice.

**Comment by MSuih** [comment]
Closing this as the original idea wasn't as straightforward as I had hoped
