### ISSUE TITLE
Regression: Ion Assault HD no longer goes ingame after RPCN changes (#8663)

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#9155]
After https://github.com/RPCS3/rpcs3/pull/8663 merged, Ion Assault HD can no-longer go ingame, and crashes right before starting a single-player match with the following error:
`·F 0:00:12.696832 {PPU[0x1000000] Thread (main_thread) [0x00856020]} SIG: Thread terminated due to fatal error: Assertion failed: ctx`

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5451778/RPCS3.log.gz) 10790 (Before regression)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5451812/RPCS3.zip) 10791 (After regression)

**Comment by RipleyTom** [comment]
Yeah that's a weird one, it tries to send a room message, having joined no room and having created no context. Probably just need to add error check for context value.

**Comment by Asinin3** [comment]
Still broken on the RPCN pr `RPCS3 v0.0.13-fea54a83 Alpha | rpcn_0.3.5`
