### ISSUE TITLE
RPCS3 allows param.sfo modification in /dev_hdd0/game

### ISSUE THREAD

**Issue by 13xforever** [RPCS3/rpcs3#9157]
## Quick summary
After booting Super Puzzle Fighter 2 Turbo HD Remix (or Super Street Fighter II Turbo HD Remix), game's param.sfo will be corrupted.

## Details
Original and modified param.sfo files [NPEB00020.zip](https://github.com/RPCS3/rpcs3/files/5452620/NPEB00020.zip)
Log [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5452624/RPCS3.log.gz)
Expected behavior: anything under /dev_hdd0/game/ is mounted read-only

**Comment by MSuih** [comment]
Does #9151 fix this?

**Comment by 13xforever** [comment]
It's crashing with 
```
Thread terminated due to fatal error: Verification failed: 
(in file D:\a\1\s\rpcs3\Emu\Memory\vm.cpp:771)
```
but param.sfo is unmodified afterwards, so maybe? but can't be sure

**Comment by RipleyTom** [comment]
Something similar happened with Bomberman Ultra which is why I made this revert.
Crash is probably unrelated.

**Comment by AniLeo** [comment]
> anything under /dev_hdd0/game/ is mounted read-only

Doesn't make sense, why should it be read-only, games can read and write to that directory, some games create extra $gameid . "DATA" folders

**Comment by elad335** [comment]
Fixed in latest master.

**Comment by elad335** [comment]
vm verification failure is s different issue.
