### ISSUE TITLE
[Feature Request] Sync save game to Google Drive

### ISSUE THREAD

**Issue by jokoputera** [RPCS3/rpcs3#9163]
## Quick summary
It will be nice to have a sync profile or even save game to Google Drive or somewhere in cloud services

## Details

Whenever rpcs3 need to close, it sync to cloud services, and evertime you run rpcs3, it will ask whether you have an account to be sync first. For save game, it will be catalogue by game serial

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* Debugging
* UI
* Patches
* Installation : rpcs3 will ask whether you want to sync your data
* Github
* CI
* etc.

#### 2. Please tell us, why your feature is important to RPCS3.
It will be nice to have 😅

#### 4. Please provide your system configuration:
* OS Windows 10
* CPU Ryzen 5 3600
* GPU nVidia 1660 Super
* Driver version latest

#### Please include.
* If the files to big, i think better to be compressed, but ill leave it to you guys, you surely understand this better than me

**Comment by Asinin3** [comment]
Uhh why should rpcs3 implement this? Just use some third party tool to sync the savedata folder to the cloud.

**Comment by jokoputera** [comment]
😅less hassle perhaps? Actually im already very happy with RPCS3, so it won't matter if this get implement or not. Cheers ☺️

**Comment by Asinin3** [comment]
Why make a request for something difficult to implement when there's fully fleshed out tools that can do this easily with lots of functionality and support. It would mean we have a feature that relies on a third party service as well. Close the issue or wait for a moderator to close it
