### ISSUE TITLE
Regression: Skate 3 freezes on non-TSX CPUs (#9139)

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#9166]
## Summary
Skate 3 is freezing constantly after #9139 was merged, either during loading screens or menus or in few seconds after getting ingame. When frozen, music continues and the fps counter is changing, but screen doesn't update and inputs aren't working. I've gotten confirmation that this only affects people who have disabled TSX or have CPUs which do not support it.

#### Logs
[working-RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5460257/working-RPCS3.log.gz)
[broken-RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5460250/broken-RPCS3.log.gz)

#### Details
In debugger, there are 6 SPU threads constantly executing instructions, but all PPU threads are stuck on waiting.

**Comment by xddxd** [comment]
Regressed by 4966f6d
