### ISSUE TITLE
SYS: 'sys_fs_open' failed with 0x80010006.  Skate 3

### ISSUE THREAD

**Issue by Megacattt** [RPCS3/rpcs3#9167]
I get these kind of errors everytime I boot the game, it gets passed the logos then either goes black or to the start page.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
