### ISSUE TITLE
Ninja Gaiden Sigma- Regression

### ISSUE THREAD

**Issue by a21407097** [RPCS3/rpcs3#9172]
With the new emulator version, game crashes constantly, sometimes after 2 minutes of gameplay, sometimes after 5 minutes of gameplay.

I have 2 diferent log files here: One in the newest version of the emulator, other using the version "0.0.12-10989" Which is 19 days old.

I am playing in windows 10, my graphic card is a Nvdia Geforce GTX 765M. Total of memory is 12GB.

My nvdia drivers are "425.31  WHQ"

A friend of mine is playing this game on a laptop MSI, Nvdia force 980M and 8 GB of ram memory. Windows 10.

He had exactly the same problem and the same solution also worked in his laptop: Using a older version of the emulator (namely 0.0.12-10989) stoped the crashes. 

[RPCS3_v012_10908.log](https://github.com/RPCS3/rpcs3/files/5464753/RPCS3_v012_10908.log)
[RPCS3_newest.log](https://github.com/RPCS3/rpcs3/files/5464754/RPCS3_newest.log)

**Comment by Asinin3** [comment]
Your "newest" build of rpcs3 is old. Update it again to latest and try again. There has been some stability improvements today/yesterday

**Comment by a21407097** [comment]
First, thank you mister/miss Asinin3 for the fast answer. I am gonna test it write now and give you input on it.

**Comment by a21407097** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5464821/RPCS3.log)

Just crashed not even 4 minutes into the game. The log with the newest version is there. If you want any more information, by all means ask :)

Going back to "0.0.12-10989" emulator version in the meanwhile.

**Comment by Asinin3** [comment]
Played for 20min, cant reproduce. This issue is gonna get nowhere unless we can reproduce it.
![image](https://user-images.githubusercontent.com/15137035/97703241-3b134280-1b00-11eb-9e52-f900b33093c0.png)

**Comment by Shfty** [comment]
I'm seeing this as well, across the last ~4 versions to hit the auto-updater at the time of this post. The game will hard-freeze, and stopping emulation from the UI or via task manager will cause a "thread deadlocked, please report" popup to appear.

Here's a pastebin of my most recent crash log, taken about 30min ago:
[Pastebin](https://pastebin.com/YBL1sjz0)

This appears to happen regardless of whether RSX mode is set to ASMJIT or LLVM. Subjectively, the crashes seem more common under LLVM, but I suspect that's coincidental to where I was in the game while swapping between the two settings.

Starting my run yesterday, Chapter 1 as screenshotted above was stable for me; the freezes started during Chapter 2 after reaching the hayabusa village section. The auto-updater popped twice between crashes, ultimately bringing me up to version 0.0.13-11275.

For the most part they seem unpredictable, but the burning area at the end of the chapter was a hotspot - after fighting Masakado on the bridge (the horseback samurai in red armor) and reaching the save point, I experienced 3 lockups during the next fight, and another 3-4 during the cutscene before the scripted encounter with Doku that ends the chapter.

Chapters 3 and 4 were also lock-free, with another one occurring near the start of Chapter 5.

Chapter 6 seems to be another hotspot; after crossing the drawbridge to the Dworku area and using the save point, the critical path takes you through a fight with military enemies outside the cathedral, and then down a side road through two consecutive ninja encounters before you reach the boss area. These ninja encounters crashed 4 times in total.

Picking up today, I was able to pass the area and reach Chapter 7 under 0.0.13-11280, but I assume this was down to chance as another lock occurred after the first imp encounter in the monastery courtyard.

**Comment by Asinin3** [comment]
Well, we need to know what build started causing it if possible. I know that is a huge pain in the ass with issues like this but for regression reports it helps a lot in terms of letting devs know where the cause is

**Comment by digitaldude555** [comment]
@Shfty @a21407097 retest

**Comment by a21407097** [comment]
@digitaldude555 

I got now a "VK_ERROR_INCOMPATIBLE_DRIVER"

I will try to see what's wrong with the new emulator/configuration but unfortunatelly, I am full of work at the moment. 

Expect any news only in some days from now. In the meanwhile, here is the log:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5953780/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Is this still an issue?
