### ISSUE TITLE
Dragon Ball Raging Blast 2 Freeze

### ISSUE THREAD

**Issue by JDario16** [RPCS3/rpcs3#9193]
## Quick summary

When I'm playing the game freeze

## Details

I'm not doing something weird, I was playing normally in the Galaxy Mode and then freeze. I've tried 3 settings and none of those fixed the problem

#### 1. RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5470128/RPCS3.log)

#### 2. Please provide your system configuration:
* OS: Windows 10
* CPU: I7 4790K
* GPU: GTX 970
* Driver version: 457.09

**Comment by Asinin3** [comment]
None of the info here is helpful for determining what is causing the crash. No info on if it is an old or new issue. No info on if it only started happening on a certain build no fatal error in the log. Essentially this issue report means one of the devs has to try and replicate a crash you received without knowing if it is the same crash, that is if they can even hit it.

I don't like reports like this. What are we supposed to do with this information? No steps to easily reproduce the issue etc.
Can re-open if you identify that it started happening after a specific build/pull request or there's a log with more info or some steps to reproduce.
