### ISSUE TITLE
Disgaea 3 Music Dissapear

### ISSUE THREAD

**Issue by pidgey84** [RPCS3/rpcs3#9196]
When you enter on a stage map sometimes the music no play, this no happen on real ps3 hardware since i do this game on my death ps3. For example, on real ps3 hardware on the dialogs between characters, the voices sometimes dissapears but the music never do that. Also i cant confirm this because i just barely start the game on rpcs3, but i read on the forum that some people get a crash on some maps of chapter 4 if im no mistaken.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
