### ISSUE TITLE
Regression: Star Wars: The Force Unleashed II [NPUB30695], game hangs in menus now (#9117)

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#9199]
Once in menus, game freezes on pressing A (to invoke save selector). 

Broken by:
https://github.com/RPCS3/rpcs3/pull/9117

[11077.gz](https://github.com/RPCS3/rpcs3/files/5471792/11077.gz)

Fine on previous build:
[11069.gz](https://github.com/RPCS3/rpcs3/files/5471793/11069.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by Nekotekina** [comment]
Try #9205

**Comment by legend800** [comment]
Still hangs:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5485103/RPCS3.log.gz)

**Comment by Nekotekina** [comment]
Sorry about that, cause I reverted commit that was potential fix. So basically last version of 9205 changes nothing...

**Comment by Nekotekina** [comment]
Maybe test #9206 please

**Comment by legend800** [comment]
Sorry, no change, still hangs when pressing start on the menu.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5491807/RPCS3.log.gz)

**Comment by Nekotekina** [comment]
Pausing/unpausing doesn't help I presume?

**Comment by legend800** [comment]
I'm in the menus. It freezes there and have to close the game.

**Comment by AniLeo** [comment]
Can you retest on current build?

**Comment by legend800** [comment]
No change, still locks up here:
![2020-12-18 12_32_24-](https://user-images.githubusercontent.com/20983844/102658846-38f75880-412d-11eb-9bdc-7b2e449cb624.png)

**Comment by legend800** [comment]
Now it's back to just looping here. Restarted numerous times and tried various configs:

![2021-01-30 13_20_48-FPS_ 30 00 _ Vulkan _ 0 0 14-11647 _ Star Wars_ The Force Unleashed II  NPUB3069](https://user-images.githubusercontent.com/20983844/106368388-02048d00-62fe-11eb-957d-1d2ffb7db615.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5898737/RPCS3.log)

**Comment by legend800** [comment]
Still active as of 0.0.16-12427.

**Comment by Xcedf** [comment]
@legend800 did you try with TSX disabled?

**Comment by legend800** [comment]
I have amd now. No diff

**Comment by Xcedf** [comment]
@legend800 Ok, have the same issue with full game, but enabling Acurate SPU DMA helps to get ingame
![4](https://user-images.githubusercontent.com/7060586/127554082-ef5901d6-dfe6-4b35-96c6-c91d18f37d3b.jpg)

**Comment by legend800** [comment]
EXCELLENT find! Yep, that makes the game rock solid now it appears. I can close this then if we're fine needing that On to get in-game now. 

That leaves just the gfx issue as the last thing to get this game fully playable. Tracking here:
https://github.com/RPCS3/rpcs3/issues/8244

**Comment by Megamouse** [comment]
If an accuracy setting fixes the game, then it should be ok to close the issue

**Comment by 4mulala** [comment]
Forgive me but I would like to update this. I have been playing around with the settings and it seems to load & run game clearly with a few visual bugs in the start menu with letters not showing. 
![bandicam 2024-06-18 03-50-28-127](https://github.com/RPCS3/rpcs3/assets/110870075/b9abee8d-cc68-4723-a71f-278b98653596)
![bandicam 2024-06-18 03-50-36-101](https://github.com/RPCS3/rpcs3/assets/110870075/efb98261-ce8c-4c0a-91a0-eebf3fa65b41)
![bandicam 2024-06-18 03-50-51-786](https://github.com/RPCS3/rpcs3/assets/110870075/dfdf777e-1fa2-455e-a404-bbb76e272731)
![bandicam 2024-06-18 03-52-52-325](https://github.com/RPCS3/rpcs3/assets/110870075/c6dccee5-3972-486d-94fb-c1e74d1a7df9)
![bandicam 2024-06-18 03-53-04-303](https://github.com/RPCS3/rpcs3/assets/110870075/9295da9c-e2d4-4038-a1db-2a0fa8bad32a)

**Comment by legend800** [comment]
That issue is not related to this one, that was closed 3 years ago, other than it's the same game, and that issue is logged here: https://github.com/RPCS3/rpcs3/issues/14684
