### ISSUE TITLE
Armored Core 4 Graphical issue

### ISSUE THREAD

**Issue by ConorMoschella** [RPCS3/rpcs3#9203]
## Quick summary
Graphical issues on Characters - half the textures are frazzled

## Details

I have the entire game running perfectly fine. I have only done the first 5 levels but it's great once I cap the framerate, otherwise it runs at 1200.

Everything else looks flawless, ty for the emulator.

The characters themselves are missing half of the textures, turning on Write Color Buffers works, and it functions entirely in the tutorial and every menu, but the actual levels won't load, it crashes within 2 seconds of trying to start a level after the briefing and cut scenes.

#### 1. Please attach RPCS3's log.
* Run the game until you find the issue.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5479211/RPCS3.log.gz)

[BLUS30027_20201102224938_capture.zip](https://github.com/RPCS3/rpcs3/files/5479219/BLUS30027_20201102224938_capture.zip)

![proper Graphics](https://user-images.githubusercontent.com/41309607/97948461-a8241380-1d5e-11eb-95bb-853db9c98ea2.png)
![graphical error](https://user-images.githubusercontent.com/41309607/97948465-ab1f0400-1d5e-11eb-9d25-79738d2fb329.png)
![graphical error](https://user-images.githubusercontent.com/41309607/97948468-ace8c780-1d5e-11eb-8003-8bec660273a1.png)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc. 
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 5. Please provide your system configuration:
* OS
* CPU
* GPU
* Driver version
* etc.

I don't know how to find this, please let me know and I will get it

hope this helps

OS Name	Microsoft Windows 10 Home
Version	10.0.18363 Build 18363
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-A6IDKQD
System Manufacturer	MSI
System Model	MS-7A39
System Type	x64-based PC
System SKU	To be filled by O.E.M.
Processor	AMD Ryzen 7 1700 Eight-Core Processor, 3000 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 2.30, 3/24/2017
SMBIOS Version	3.0
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	MSI
BaseBoard Product	B350M GAMING PRO (MS-7A39)
BaseBoard Version	1.0
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.18362.752"
User Name	DESKTOP-A6IDKQD\***** *********
Time Zone	Eastern Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	16.0 GB
Available Physical Memory	10.1 GB
Total Virtual Memory	18.3 GB
Available Virtual Memory	7.76 GB
Page File Space	2.38 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not Modern Standby, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes

#### Please include.
* Anything else you deem to be important

**Comment by dulsan** [comment]
I've already opened a thread for this. 

Some of the graphical issues could be fixed with shader interpreter. It usually breaks for all armored core games.

**Comment by ConorMoschella** [comment]
ahh I tried to look but thanks for the information, I actually figured it out for 4 and got that fixed, on acfa atm, same issue but it seems to crash a bit if you go through menus too fast or watch a cutscene longer than 30 seconds.

**Comment by Severancedrums** [comment]
Any updates on this? almost seems to be tied with the weird save file thumbnail issue.
