### ISSUE TITLE
LLVM SPU decoder does not work correctly on Zen 3

### ISSUE THREAD

**Issue by noahc3** [RPCS3/rpcs3#9210]
## Quick summary
LLVM SPU decoder causes extreme lag or crashing on Zen 3 (tested with Ryzen 7 5800X).

## Details

I've been able to test three games showing different behavior:

* LittleBigPlanet 2 Extras Edition (BCES01693) - Extreme lag, running at <4FPS in the Pod. There is no lag during the opening video or loading screen animations. The game maintains a stable 30FPS with ASMJIT.
* Red Dead Redemption GOTY (BLES01294) - Extreme lag, running at <2FPS on the main menu. There is no lag during the opening text and Rockstar logo animations. The game reaches 10FPS with ASMJIT.
* Persona 5 (BLUS31604) - Game crashes and RPCS3 exits about a second into the main menu animation. The game runs correctly with ASMJIT.

Observations:
* All three titles worked correctly on my Ryzen 5 3600 with LLVM SPU decoder immediately before swapping the CPU with a 5800X.
* All three games work correctly when the SPU decoder is set to ASMJIT with my 5800X.
* LLVM PPU decoder works fine as far as I can tell.

#### RPCS3 logs

[LittleBigPlanet 2 Extras Edition](https://github.com/RPCS3/rpcs3/files/5498083/LittleBigPlanet2EE-RPCS3.log)
[Red Dead Redemption GOTY](https://github.com/RPCS3/rpcs3/files/5498101/RDRGOTY-RPCS3.log)
[Persona 5](https://github.com/RPCS3/rpcs3/files/5498088/Persona5-RPCS3.log)

#### Screenshots

![LittleBigPlanet 2 Extras Edition - Pod](https://user-images.githubusercontent.com/6082749/98310309-39c79700-1f92-11eb-817d-92833b6fd4b3.png)

![Red Dead Redemption GOTY - Main Menu](https://user-images.githubusercontent.com/6082749/98310424-83b07d00-1f92-11eb-9e27-ce1302de7b95.png)

#### System Configuration
* OS: Windows 10 20H2
* CPU: Ryzen 7 5800X
* AGESA revision: 1.1.0.0
* Motherboard: MSI B550i Gaming Edge WiFi
* Motherboard BIOS version: v1.41
* GPU: RTX 2060 SUPER
* GPU driver version: 456.38
* RPCS3 version: 0.0.13-11166-fc77fb9b

#### Other

I have a few extra games I can try if that would help. Let me know if there's anything else I can do to help.

**Comment by xddxd** [comment]
Try putting znver2 in one of the config game files where it says Use LLVM CPU: "", like Use LLVM CPU: "znver2"

**Comment by noahc3** [comment]
> Try putting znver2 in one of the game config files where it says Use LLVM CPU: "", like Use LLVM CPU: "znver2"

Yep, that fixes it in all three games. I suppose RPCS3 needs to be updated to detect the new CPUs and set that automatically?

**Comment by xddxd** [comment]
As far as I can tell the LLVM backend needs to be updated to support the new cpus.

**Comment by Yahfz** [comment]
@noahc3 to be honest we are pretty excited that you have a 5800X, would you mind joining our discord server to post results about how the cpu performs? :P

**Comment by Zangetsu38** [comment]
i want know too, go on discord for show your peromance :)

**Comment by Nekotekina** [comment]
I will add some workaround, situation looks horrible. It compiles with SSSE2 generic.

**Comment by AniLeo** [comment]
Zen 3 is a new family (19H) as opposed to Zen 2 / Zen + / Zen (17H).
LLVM doesn't have Zen 3 support yet at all, neither on Stable 11.0.0 which is what our fork is based on, nor on their latest git master.

Worked around on https://github.com/RPCS3/llvm-mirror/pull/4

**Comment by elad335** [comment]
Better to still keep being tracked of, that workaround may hurt perf in the future when Zen3 is supported.

**Comment by AniLeo** [comment]
When Zen 3 is supported then the dependency will be updated, probably on LLVM 12 Stable release, no use in keeping this opened, we also worked around Zen 2 back then

**Comment by AniLeo** [comment]
Note that latest artifact needs to be rebuilt on CI as I merged before llvmlibs compiled to newer version, you can keep using znver2 on config, on the next artifact it will use the newer llvmlibs with the workaround

**Comment by Nekotekina** [comment]
Doubt they'll have such a good perf tuning compared to znver2...
