### ISSUE TITLE
fs::escape_path doesnt work on network locations

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#9228]

**Comment by n1ckn4m3** [comment]
Adding a description for clarity:

Specifics:

    Windows 10 Pro x64, latest feature update
    Disc game data being hosted on SMB share on NAS - not directly mapped.  E.g., "\\servername\ROMs\Sony Playstation 3\3D Dot Game Heroes (BLUS30490)\"
    Emulator installed locally on HDD, \dev_hdd0\ and \dev_hdd1\ have not been relocated in any way (they exist as subfolders in the emulator's directory)

Example:

    Global configuration set to use Vulkan.
    Create custom configuration for game (in this case, BLUS30490 - 3D Dot Game Heroes). 
    Set renderer to OpenGL in custom configuration.
    Right click on game and choose "Boot with custom configuration"

Result:

    Emulator boots game in Vulkan mode and not OpenGL mode.
    rpcs3 log misidentifies game as "EBOOT.BIN"
    rpcs3 log does not show any attempt to use custom configuration file
    Game fails to launch

On PR#8982, Build 0.0.12-10945, however, it upholds the custom config, reflects the name properly, and boots the game in OpenGL mode. 

Working and non-working logs attached.

[RPCS3.log.non-working.pr8975.build.0.0.12-10946.gz](https://github.com/RPCS3/rpcs3/files/5507072/RPCS3.log.non-working.pr8975.build.0.0.12-10946.gz)
[RPCS3.log.working.pr8982.build.0.0.12-10945.gz](https://github.com/RPCS3/rpcs3/files/5507073/RPCS3.log.working.pr8982.build.0.0.12-10945.gz)

**Comment by ruthan** [comment]
Its just regression and its reported for more and 2.5 months and some people can really play or test without fixing it, local SSDs are still not cheap Nas drives are..

**Comment by Nekotekina** [comment]
Maybe fs::get_parent_dir should be rolled back to the version which didn't depend on this functions.

**Comment by ruthan** [comment]
WIth new version, i have in log right after start this, its not network patch, but its valid:
E SYS: Booting 'D:/Games/!Emulators/PS3 - Rpcs3/-' with cli argument failed: reason: Invalid file or folder.. i guess that is has problem when locally with "-" or even space and that is not great.

**Comment by Nekotekina** [comment]
@ruthan hi, can you try #9767 with network path?

**Comment by ruthan** [comment]
@Nekotekina Error after emulator start is gone, i tested 2 games (Skyrim + Unreal Tournament 3) they are now running fine, so its very probably that all other games will be fine too, thanks.

   Otherwise for testing im using just normal Windows sharing, so if make some Windows virtual machine with bridge networking (to get own ip address) and right click on folder - share a copy some game dump here.. and test availability with \\{virtualMachineIPAddre}\{SharedFolderName} and open same path from PRCS3, to make your own tests quickly.

**Comment by elad335** [comment]
Removed function.
