### ISSUE TITLE
games dont boot, give's error below

### ISSUE THREAD

**Issue by snesgab** [RPCS3/rpcs3#9229]
U {PPU[0x1000000] Thread (main_thread) [0x00019f94]} sys_mutex TODO: sys_mutex_create(): unexpected adaptive (0x1000)
U {PPU[0x1000001] Thread (temperature_thread) [0x0001772c]} PPU TODO: Unimplemented syscall sys_game_get_temperature -> CELL_OK (r3=0x0, r4=0xd0202f70, r5=0x0, r6=0x0, r7=0x0, r8=0x0, r9=0x0, r10=0x0)
U {PPU[0x1000001] Thread (temperature_thread) [0x00017744]} PPU TODO: Unimplemented syscall sys_game_get_temperature -> CELL_OK (r3=0x1, r4=0xd0202f74, r5=0x0, r6=0x0, r7=0x0, r8=0x0, r9=0x0, r10=0x0)
F {RSX [0x0000000]} SIG: Thread terminated due to fatal error: Could not bind OpenGL context
(in file D:\a\1\s\rpcs3\rpcs3qt\gl_gs_frame.cpp:78)

ive tried so many ways around it, and my computer specs meet more than the minimum requirements, but it constantly give's me the same error, if i could get any help on this, that would be awesome!

**Comment by RainbowCookie32** [comment]
Looks like either an unsupported GPU or bad drivers. Regardless, this is not the place for support, move to [our discord server](https://discord.me/RPCS3) for assistance and close this issue

**Comment by elad335** [comment]
Invalid report.
