### ISSUE TITLE
Regression: GT6 freeze on intro after #8909

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#9237]
After PR #8909, Gran Turismo 6 freezes on the SCE Presents intro part. TSX is unaffected.
![image](https://user-images.githubusercontent.com/1712979/98706436-8262c400-2387-11eb-805b-3dc669c7003b.png)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5518932/RPCS3.zip)
Last working build is rpcs3-v0.0.13-11186-a28ab0a4

Ryzen 7 2700
RX 580 20.10.1
Windows 20H2

**Comment by Satan86** [comment]
If there is no save data, the game gets past the intro and works normally

**Comment by elad335** [comment]
Should be fixed by #9239 didnt test though
