### ISSUE TITLE
Regression - The Tomb Raider Trilogy [BLES01195], Underworld hangs in any cutscene after a few seconds 

### ISSUE THREAD

**Issue by kotn3l** [RPCS3/rpcs3#9248]
## Quick summary
The game is The Tomb Raider Trilogy [BLES01195]. If you go in-game in Underworld, and start playing, it's working really well, but when you trigger an in-game cutscene, the game freezes with
`E {SPU[0x2000100] Thread (PriCellSpursKernel2) [0x09260]} VM: Access violation writing location 0xc2142000 (read-only memory)[type=u128]`
error, and the game stops moving, the audio is repeating, and I have to close the game. The emulator doesn't crash though.

## Details
It was working before, like maybe a a week or 2 ago, so probably a newly implemented fix is causing this to happen. Only happens in Underworld, not in Legend or Anniversary.
You can really easily replicate this if you go in-game, start a new game. After it loads, and the first cutscene begins, it will freeze in like 2 seconds.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5524226/RPCS3.log)

#### 4. Please provide comparison with real PS3.
Well, the cutscenes shouldn't freeze.

#### 5. Please provide your system configuration:
* OS W10 64bit 2004
* CPU Ryzen 5 1600X
* GPU GTX 1070
* Driver version 456.55

#### Please include.
Like I said, it was working before. Unfortunately I don't know for sure when it went wrong, but hopefully from the log it will be visible what is causing the issue.

**Comment by lainiwaku** [comment]
since recently the last of us crash at start 
I just got same error 
"E {SPU[0x5000100] Thread (highCellSpursKernel5) [0x069f4]} VM: Access violation writing location 0xc46d0040 (read-only memory) [type=u128]"

**Comment by Asinin3** [comment]
If it's a regression then you need to find where it broke. It's up to you to test and provide accurate information.
https://rpcs3.net/compatibility?b
Go there, test some builds find where it broke, update issue report and post log of befoore/after.

**Comment by MSuih** [comment]
Can you also check if #9246 fixes it?

**Comment by kotn3l** [comment]
Yes, #9246 fixes the issue. That was fast, thank you guys!
