### ISSUE TITLE
Debug Overlay bug on window resize

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#9251]
![image](https://user-images.githubusercontent.com/23019877/98855526-6f6df380-245c-11eb-8f2e-0821666fdc38.png)

![image](https://user-images.githubusercontent.com/23019877/98855737-c5429b80-245c-11eb-90d1-7b0c2bfaee26.png)

**Comment by kd-11** [comment]
#ItWorksForMe #CannotReproduce
![image](https://user-images.githubusercontent.com/15904127/99987702-d75bfc80-2dc1-11eb-84aa-5d67f0b65ddf.png)

**Comment by Megamouse** [comment]
Maybe it's fixed on your branch, but master still has the issue.
My own builds still fail with Vulkan, so I can't test the commit.

**Comment by Megamouse** [comment]
I forgot to mention that it seems to be fixed on OpenGl on your ogl branch

**Comment by Megamouse** [comment]
nvm I'll test the azure build

**Comment by Megamouse** [comment]
When testing with your ogl branch, the issue seems to appear when I use 
**Debug Overlay + Vulkan + Performance Overlay**
It doesn't happen with OpenGl at all as far as I can tell

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/102121623-4ecafc00-3e55-11eb-8639-79d1c8148458.png)
Renders fine with both performance overlay and debug overlay. This may be some specific hw/driver problem.

**Comment by Megamouse** [comment]
still happening.
deleted config and only enabled those two overlays:
![image](https://user-images.githubusercontent.com/23019877/102132805-6950a580-3e54-11eb-977a-fb9180b43701.png)

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/102259724-85ba1400-3f20-11eb-9ca6-36491e625ed4.png)
Linux just for fun. Also using the same program just in case.

**Comment by Megamouse** [comment]
stop mocking me 😠

**Comment by kd-11** [comment]
Lol. We need more people who can reproduce the bug, maybe I have a GPU that can run captured renderdoc for someone.

**Comment by VelocityRa** [comment]
I can repro on GTX 970 (note that this is not on master).

RD: [debug_overlay_resize_issue_vk.zip](https://github.com/RPCS3/rpcs3/files/5698124/debug_overlay_resize_issue_vk.zip)

**Comment by Megamouse** [comment]
I'm assuming that this is NoVideo shenanigans.
Did you only try AyEmDee @kd-11 ?
Also, there's a renderdoc attached to the last comment.

**Comment by Megamouse** [comment]
Getting the same issue on my laptop btw.

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/106188383-f444ef80-61b7-11eb-832a-344b9a3c0840.png)
1050Ti is also ok.
On nvidia renderdocs are not shareable between pascal and maxwell unfortunately. I'm wondering if some other condition is causing this. Like 3rd party software maybe?

**Comment by kd-11** [comment]
Easiest way to verify is to get a pascal renderdoc going and I can replay. Second, we can have someone with nvidia+linux try as well.

**Comment by Megamouse** [comment]
I can try on my laptop. probably gonna take some time, as I have no idea if my system supports RPCS3

**Comment by Megamouse** [comment]
Also happens on Ubuntu 20.10 with my Intel iGPU.
![image](https://user-images.githubusercontent.com/23019877/106210070-6d4b4380-61c6-11eb-9250-70abbea91f29.png)

**Comment by Megamouse** [comment]
@kd-11 this doesn't happen if I move the debug overlay section in front of the ui_renderer section.
Maybe some bit that's not reset after the ui_renderer ?
