### ISSUE TITLE
Drakengard 3: Random freezes when disabling "Accurate LLVM DFMA"

### ISSUE THREAD

**Issue by scrubbrush** [RPCS3/rpcs3#9253]
System: 
Win7
i7-3770k
Geforce GTX 1060 6gb
16GB ram

I've been testing **[rpcs3-v0.0.7-8841-278050f8_win64]**  and the latest builds of RPCS3 for the past few weeks **~[rpcs3-v0.0.13-11222-829a697c_win64]**. The older version (0.0.7) is running at a stable framerate close to the PS3 and 60 fps in less demanding areas. The newer version of RPCS3 however is running significantly worse with extremely bad stuttering/CPU spikes and low FPS in many areas.

I'm using the recommended settings on both builds, with the FPS patch and VBlank at 120. I've also tested it without the FPS patch and still had the same performance problems in the newer version.

**Comment by AniLeo** [comment]
Missing what build introduced this performance regression

**Comment by Yahfz** [comment]
Pretty sure that this is caused by the fact that we are now using accurate LLVM DFMA in the newer builds, his CPU lacks the FMA instruction set so i'm almost sure that its the issue. @scrubbrush Try downloading the latest RPCS3 version and disabling "Accurate LLVM DFMA" and see if that helps. To do that go to Settings -> Advanced Tab -> and untick the option "Accurate LLVM DFMA"

**Comment by scrubbrush** [comment]
> Pretty sure that this is caused by the fact that we are now using accurate LLVM DFMA in the newer builds as default, his CPU lacks the FMA instruction set so i'm almost sure that its the issue here. @scrubbrush Try downloading the latest RPCS3 version and disabling "Accurate LLVM DFMA" and see if that helps. To do that go to Settings -> Advanced Tab -> and untick the option "Accurate LLVM DFMA"

I disabled that option which fixes the framerate but makes the game randomly freeze in the latest build, 0.0.7 doesn't have this issue.

I guess it's just down to me using an outdated CPU.

**Comment by uaqlover** [comment]
Yes because outdated cpu , needs to close @AniLeo

**Comment by Megamouse** [comment]
log missing anyway
