### ISSUE TITLE
Sly 4 broken visuals with SPU LLVM

### ISSUE THREAD

**Issue by CapitaineBidouille** [RPCS3/rpcs3#9254]
Config (GPD Win Max) : 
![image](https://user-images.githubusercontent.com/58107469/98891258-1f178580-249e-11eb-8e28-fcad8e7a436b.png)
- eGPU Nvidia RTX 2070

OS : Windows 10, Driver Nvidia 457.30

Build : RPCS3 0.0.13-11222

Repro : 
1) Enable SPU Decoder Recompiler LLVM
2) Try to play Sly 4 on this configuration
3) Textures are broken.
4) Changing the SPU Decoder to ASMJIT fix the issues, but performance is devided per 2 :/

I've already tried to disable AA and change many other options, without any success. Only switch to ASMJIT can fix temporarly the issue, so I'm sure that something go wrong with the LLVM decoder on this configuration.

![image](https://user-images.githubusercontent.com/58107469/98891512-a238db80-249e-11eb-936b-ad5d2d432699.png)

Thanks for reading

**Comment by CapitaineBidouille** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5528082/RPCS3.log)
Here is my logs. I stayed a bit on the intro scene which has the issue : 
![image](https://user-images.githubusercontent.com/58107469/98892205-22ac0c00-24a0-11eb-993c-d0d21adf46e8.png)

**Comment by Angelleo** [comment]
i couldn't reproduce the bug with the exact same config.yml (the one detailed in your logs)
![test BCES01284 001311222](https://user-images.githubusercontent.com/8673240/98928887-a1be3600-24da-11eb-8221-012979236f98.jpg)
![test BCES01284 001311232](https://user-images.githubusercontent.com/8673240/98928897-a71b8080-24da-11eb-82fd-61c6049a4f4e.jpg)
![setup](https://user-images.githubusercontent.com/8673240/98933602-27dd7b00-24e1-11eb-8488-4ba1e3dde6ca.jpg)

try to lower the rendering resolution from 150% to 100% you will reduce the cpu load and maybe it'll fix it for you

**Comment by CapitaineBidouille** [comment]
![image](https://user-images.githubusercontent.com/58107469/98943079-3f236500-24ef-11eb-94c6-5a5fdbc955f7.png)

No changes, it's still glitchy.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5530703/RPCS3.log)

**Comment by CapitaineBidouille** [comment]
I have just tried to run the game without the eGPU (on the Intel Iris Pro), i can see the same exact glitches. So I think LLVM recompiler seems to have a bug with this particular or with all Intel Ice Lakes CPU.
