### ISSUE TITLE
Demon's Souls crashing Vblank thread

### ISSUE THREAD

**Issue by ArkamTheBard** [RPCS3/rpcs3#9262]
## Quick summary
Game crashes at random on startup. Sometimes can make it to the main menu, but sometimes crashes on intro videos.

## Details
E {VBlank Thread} SYS: 'Unknown function' failed with 0x00000000 : 0

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.13-11240-0c7f9458

#### 2. Please attach TWO logs:
* One for the build with regression.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5538264/RPCS3.log.gz)

#### 6. Please provide your system configuration:

Windows 10 latest update
i7 6700k @ stock clock
GTX 1060 6GB

E {VBlank Thread} SYS: 'Unknown function' failed with 0x00000000 : 0

**Comment by elad335** [comment]
Duplicate if #9238
