### ISSUE TITLE
Add PPU threads to GUI

### ISSUE THREAD

**Issue by AphelionWasTaken** [RPCS3/rpcs3#9263]
## Details
I know this has been brought up before with PR #9018, but I think it's worth revisiting the idea.

Changing PPU threads to 1 can cause issues in quite a few games, however it is required for games in the "Tales" series in order for audio to work properly (and possibly for stability). 

To apply this change to a specific game, users are currently required to create a custom configuration for the game (even if no other settings need to be changed) and then manually edit that game's config_xxxx.yml file, which is buried in the config folder.

I understand that we want to dissuade users from messing with settings that can cause issues, but I think the benefits are worth it if there is a warning or a good description of why users should change the setting. The current method of changing PPU threads for these games is likely too advanced to some users and these games are marked as "playable". ~~Plus, we already have quite a few other settings in the GUI that can cause major issues if improperly configured.~~

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay - Audio works properly in the "Tales" games  with 1 PPU thread. It is possible that this makes them more stable as well, as I was getting softlocks in Xillia 2 with this set to 2.

* UI - A drop-down menu to change PPU threads, either in the advanced or debug tab.

#### 2. Please tell us, why your feature is important to RPCS3.
* This feature would make it easier for the end user to configure games in the "Tales" series properly.

**Comment by AniLeo** [comment]
I'll move these games back to Ingame, I forgot to do it earlier
It's probably best if the actual issue is looked into, specially since we just have this game with this issue, so it can work properly with 2 PPU threads

**Comment by AphelionWasTaken** [comment]
It would be awesome if the underlying issue could be worked out and these games could run properly with 2 threads. It's a shot in the dark, but it may be related to how the game is meant to switch from 30 to 60 FPS; I am using the 60 FPS patch with 2 PPU threads and the issue is not present. I think it needs more testing before I can say for sure that the patch fixes it though.

I'm not sure if the audio issue is enough to push it back to in-game, but that may be the best course of action for now. If it makes a difference, stability doesn't seem to be affected by this setting after all, even without the patch - the softlocks appear to have been a recent TSX issue, which seems to have been resolved. 

The audio issue also only affects the background music and a some sound effects - most sound effects and things like voices remain. The games are still quite playable, albeit a little annoying with the volume up.

**Comment by HerrHulaHoop** [comment]
It isn't the audio issue, but rather requiring Vblank change to fix the framerate issue. That's what moves this game back to in-game.

**Comment by AniLeo** [comment]
Closing as it's on debug tab already
