### ISSUE TITLE
Full screen not working anymore.

### ISSUE THREAD

**Issue by Braindead82** [RPCS3/rpcs3#9264]
Just noticed this today. I am trying to play ratchet and clank trilogy but i can not use full screen anymore. The game works with full screen when the intro plays. After you select which game you want to play it gives only white screen. When you press alt+enter to smaller screen then image comes back and works normally. If you go back to full screen again the image just freezes. So the game is still running, only the screen hangs. 

This issue seems to be only with vulkan renderer. Opengl works fine.

Last working build was: 0.0.13-11232
0.0.13-11234 has this problem. 

My pc is:
cpu: i7-7700k 4.20ghz
ram: 16gb
gpu: amd radeon r9 200 series. Driver: 2.0.154
os: win10

Thanks for reading! Just wanted to report this.

**Comment by Braindead82** [comment]
This problem still exists in the latest builds but i was able to get it working by sarting the game in smaller window. After you have chose the ratchet and clank game that you want to play then you can use the emulator in full screen mode. So at least you can play it again with this method. So it not a big issue but maybe this bug can be fixed someday. I only have 1 other game r&c: tools of destruction and it works normally.

**Comment by JCChamo** [comment]
v0.0.13-11308-5076da8f solved.

**Comment by Braindead82** [comment]
Not yet solved, still the same issue but It will be fixed someday. Gladly it is not a big problem.

**Comment by HenriqueLJ** [comment]
Not yet solved, the screen freezes when fullscreen, but the game keeps running on the background, and when I exit fullscreen it works normally

**Comment by HenriqueLJ** [comment]
Just noticed that if the game loses focus, the screen will resume updating.
Steps to reproduce in case you are experiencing this problem:
1- Boot up a game, in my case is Kingdom Hearts 2.
2- Go fullscreen and verify that the screen is not refreshing anymore, but the game sounds are still playing in the background.
3- Do something that will cause the game screen to lose focus, such as opening the Windows start menu or alt-tabbing to another program.
4- The game should still be running on fullscreen, but now refreshing normally. 

RPCS3 Version:  v0.0.14-11595-241989c5 Alpha

**Comment by Braindead82** [comment]
I do not have this problem anymore. I upgraded my gpu from amd to nvidia gtx 1070ti. So i guess this might be a amd issue. Or maybe they just got it fixed.

**Comment by kd-11** [comment]
Any update on this? I cannot reproduce this issue on multiple GPUs.

**Comment by Darkhost1999** [comment]
5 months no update? Anybody?
