### ISSUE TITLE
[Feature Request] Uninstall game update

### ISSUE THREAD

**Issue by Krishster** [RPCS3/rpcs3#9268]
After installing updates to game via .pkg, there is no menu to uninstall the updates from the particular game. Atleast i have not see any menu in rpcs3. sometimes it is required to uninstall the updates from the games for experiment purpose.

kindly look into the matter and bring particular menu for uninstalling updates from each games.

regards

**Comment by AniLeo** [comment]
You can use Show Categories -> Game Data and then right click it to Remove.
You can't remove individual updates, if it's a digital game you have to remove the whole game and reinstall the base version.
