### ISSUE TITLE
Regression: Grand Theft Auto IV w/ TSX-FA (#9161)

### ISSUE THREAD

**Issue by MsDarkLow** [RPCS3/rpcs3#9269]
## Quick summary
Grand Theft Auto IV started showing occasional exploding vertices with TSX-FA.

## Details
GTA IV started having occasional exploding vertices when the build #9161 was merged to master.
When TSX is disabled, this issue no longer occurs.

#### The logs:
Regression Build: [GTAIV11117.log](https://github.com/RPCS3/rpcs3/files/5541317/GTAIV11117.log)
Working/Previous Build: [GTAIV11107.log](https://github.com/RPCS3/rpcs3/files/5541318/GTAIV11107.log)

#### Visual preview of the issue
![GTAIVExplodingVerticesTSX-FA](https://user-images.githubusercontent.com/9060436/99155159-5f008780-26ad-11eb-8289-997f23dfa035.gif)

#### System
* OS Windows 10 - v2004
* CPU i7 8700k
* GPU RTX 3080 (457.30)

**Comment by nitroos-ai** [comment]
Is it fixed?

**Comment by MsDarkLow** [comment]
No it's not fixed. It still occurs but less often.

**Comment by MsDarkLow** [comment]
Closing this issue since I haven't had the 8700k since forever and I haven't seen anyone ever complain about it on discord.

If someone else can reproduce this issue, then ask for this to be reopened.
