### ISSUE TITLE
God of war 3 BLUS98111 black screen

### ISSUE THREAD

**Issue by Krishster** [RPCS3/rpcs3#9270]
Kindly note GOW 3 does not go ingame and infinite black screen occurs just after sony logo.

Screen Shots -
1. 
![Screenshot_1](https://user-images.githubusercontent.com/64323517/99155212-eebd2a80-26db-11eb-92e0-e5c98e4d9ee4.jpg)
2. 
![Screenshot_2](https://user-images.githubusercontent.com/64323517/99155214-f7156580-26db-11eb-90fd-e43de4ffc423.jpg)

RPCS3 LOG-
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5541325/RPCS3.log.gz)

Plz advise me what to do.

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by Krishster** [comment]
why it has been closing ? What i have done wrong ?

**Comment by AniLeo** [comment]
You've just been answered, there's no point in pasting the same reply. This is not a help desk, this is an issue tracker. Use the appropriate platforms for support.
