### ISSUE TITLE
Regression: Installing firmware crashes RPCS3 (#9261)

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#9272]
After PR #9261, the emulator crashes when finishing up the module compilation after the firmware files were installed.
![image](https://user-images.githubusercontent.com/1712979/99156628-13f56d00-26cb-11eb-9adf-57aceb064928.png)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5541439/RPCS3.zip)

**Comment by windwhirl94** [comment]
Adding my log here just in case it's useful for comparing any differences between a Zen+ and a Zen2 platform.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5541518/RPCS3.log)
In fact, the emulator crash on Windows is bad enough that it calls for the process to be killed through Task Manager or the taskkill command. For some reason, it doesn't trigger the usual dialog box that most non-responsive processes do (the one where Windows asks if you want to wait it out or just close it and send a report to Microsoft).

**Comment by xddxd** [comment]
Fixed by #9273
