### ISSUE TITLE
Last cutscene in Metal Gear Solid Peace Walker HD Edition has graphical issues.

### ISSUE THREAD

**Issue by m4st3rP** [RPCS3/rpcs3#9274]
## Quick summary
The last cutscene "Outer Haven" in Metal Gear Solid Peace Walker HD Edition has graphical issues.

#### 4. Please provide comparison with real PS3.
https://youtu.be/IljxOISbGyw?t=199

#### 5. Please provide your system configuration:
* OS: Windows 10 Version 2004 Build 19041.572
* CPU: AMD Ryzen 7 3700x
* GPU: AMD Radeon RX 5700 XT
* Driver version: Adrenalin 2020 Edition 20.10.1

#### Please include.
I can upload my savegame if necessary since it would take about 21 hours to get to the point in the game where you can see the issue.

Log, RenderDoc capture, RSX capture and screenshot: https://mega.nz/file/Rw5izTKD#jVfksy6l_UPbcEcL5YX1HR5YqbWu_AQHRmRTup4S_P0

**Comment by Jonathan44062** [comment]
Old ticket, this should be closed, it works fine in the latest build
![image](https://user-images.githubusercontent.com/78843189/190498414-e1fd4a4c-0974-48d5-8be5-ef16dda523bd.png)
