### ISSUE TITLE
[Device support Request] Add DualSense Support

### ISSUE THREAD

**Issue by Zangetsu38** [RPCS3/rpcs3#9275]
- [x] Basic support for button: #9308
# Gyro
- [ ] Wired:
- [ ] Wireless: 

# Custom Led:
- [ ] Wired:
- [ ] Wireless: 

# Rumble
- [x] Wired:  #9308
- [x] Wireless:  #9308

# Accelerometer
- [ ] Wired:
- [ ] Wireless: 

# Player Position
- [ ] Wired:
- [ ] Wireless: 

# Information 
SDL code
>https://hg.libsdl.org/SDL/file/48a20e91f82e/src/joystick/hidapi/SDL_hidapi_ps5.c
Init code for DS
https://hg.libsdl.org/SDL/rev/adcda5f6b6f8
Other  for full support on bt:
https://hg.libsdl.org/SDL/rev/e1b358a416f1
Implemented PS5 effects over Bluetooth 
https://hg.libsdl.org/SDL/rev/5fb1fc261bf5
Fixed updating LED state when starting application with Bluetooth PS5 controller connected 
https://hg.libsdl.org/SDL/rev/629f0b71fa80
SDL get other info added relate gyro and accelerometer
https://hg.libsdl.org/SDL/rev/f5cd7123618a

no listed all check directly
https://hg.libsdl.org/SDL/shortlog with looking ps5/dualsense commit name 

found some info on device support for button mapping inside this issue
https://github.com/Ryochan7/DS4Windows/issues/1545?ref=dtf.ru

DS4Window now good support DualSense directly in main branch
https://github.com/Ryochan7/DS4Windows

Can found also lot information inside this repo
https://github.com/Ohjurot/DualSense-Windows
is App testing, all works on it like rumble/led/gyro and trigger addaptatic, can very help for implement it on rpcs3

**Comment by Zangetsu38** [comment]
Some new link added with globally new 100 % code support code for get good works on rpcs3

**Comment by Megamouse** [comment]
Please retest

**Comment by Zangetsu38** [comment]
test what exactly ? i have not see any news code for dualsense 🤔

**Comment by RainbowCookie32** [comment]
See #9717

**Comment by Zangetsu38** [comment]
i see i check after

**Comment by Megamouse** [comment]
I don't know if you noticed, but this is already available on master builds

**Comment by Zangetsu38** [comment]
yes sorry

**Comment by Megamouse** [comment]
closing as implemented.
Open a new issue if there are still problems.
