### ISSUE TITLE
Games crashing after #9259

### ISSUE THREAD

**Issue by RainbowCookie32** [RPCS3/rpcs3#9282]
## Quick summary
Uncharted 1 to 3 all seem to crash a few seconds after booting them, on the first loading screen.

## Details
Uncharted 1 crashes right after the game boots since #9259 on the first loading screen. 2 and 3 load for a few seconds but they also crash on it.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.13-11239 (#9259)

#### 2. Please attach TWO logs:

[UC1_11236_Good.zip](https://github.com/RPCS3/rpcs3/files/5549185/UC1_11236_Good.zip)
[UC2_11236_Good.zip](https://github.com/RPCS3/rpcs3/files/5549186/UC2_11236_Good.zip)

[UC1_Master_Broken.zip](https://github.com/RPCS3/rpcs3/files/5549187/UC1_Master_Broken.zip)
[UC2_Master_Broken.zip](https://github.com/RPCS3/rpcs3/files/5549193/UC2_Master_Broken.zip)

#### 4. Please attach screenshots of your problem.

Uncharted 1's error message when crashing.
![UC1_Master](https://user-images.githubusercontent.com/16805474/99298533-9b0c2780-2828-11eb-9594-e8f0803bf270.png)
Uncharted 2's error message when crashing.
![UC2_Master](https://user-images.githubusercontent.com/16805474/99298563-a95a4380-2828-11eb-8dc6-bfabc4e9c237.png)

* Manjaro Linux
* Ryzen 7 1700
* RX 570
* Driver version

**Comment by AniLeo** [comment]
Happens with other games such as Yakuza 3 Demo

**Comment by RainbowCookie32** [comment]
Also seems to be happening with Modnation Racers Demo and Sonic Unleashed.

Sonic Unleashed did work a few times though, refuses to boot now though.

**Comment by psennermann** [comment]
Tried 0.0.13-11265 and for me Uncharted 3 seems to work again, but now lighting is broken (too much light) even when "write color buffers" is enabled (culprit #9281)

**Comment by RainbowCookie32** [comment]
The problematic commit seems to be ab365fe494a67000bfb97c97d688c90137868e5c, couldn't reproduce the crash on the other ones from the PR.

**Comment by Nekotekina** [comment]
Seems fixed in PR, I identified the problem. Please test.

**Comment by RainbowCookie32** [comment]
Seems fixed on my side too :+1:
