### ISSUE TITLE
[BLUS30009] Full Auto 2: Battlelines. Crashes after https://github.com/RPCS3/rpcs3/pull/8893

### ISSUE THREAD

**Issue by z0z0z** [RPCS3/rpcs3#9285]
## Details
A user reported that this game (status: playable) crashes after the PR mentioned with:

`·F 0:00:11.045259 {PPU[0x1000000] Thread (main_thread) [HLE:0x008c07f0, LR:0x000fe1ac]} PPU: Function aborted: cellGameDataCheckCreate`

Which seems to make sense with the mentioned PR.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
https://github.com/RPCS3/rpcs3/pull/8893

i.e. build 0.0.12-11068

#### 2. Please attach TWO logs:
I am reporting this on behalf of someone else, I only have the log after the regression.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5551290/RPCS3.log.gz)

#### 4. Please attach screenshots of your problem.
N/A

#### 5. Please provide comparison with real PS3.
N/A

#### 6. Please provide your system configuration:
* OS: Windows 10
* CPU: i7 6700K
* GPU: 2080 Super
* Driver version: 457.30.0.0

**Comment by elad335** [comment]
should be fixed by #9287 (didnt test).

**Comment by Megamouse** [comment]
Reopen if the error still persists
