### ISSUE TITLE
Regression: Batman Arkham Asylum black screen with disconnected network (#9258)

### ISSUE THREAD

**Issue by AphelionWasTaken** [RPCS3/rpcs3#9293]
## Details
As of #9258, loading a save or starting a new game in Batman Arkham Asylum will produce a black screen and cause the emulator to be unresponsive for about 20 seconds before progressing to the loading screen and into gameplay. 

This only occurs if Network Status is set to "Disconnected"; if Network Status set to "Connected" then the game will transition from the menu to the loading screen normally. PSN Status does not seem to matter.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.13-11236-debfae06 (#9258)

#### 2. Please attach TWO logs:
First Broken Build - [RPCS3 - 9258.log](https://github.com/RPCS3/rpcs3/files/5557637/RPCS3.-.9258.log)
Last Working Build - [RPCS3 - 9255.log](https://github.com/RPCS3/rpcs3/files/5557638/RPCS3.-.9255.log)
Current Master w/ Networking Disconnected - [RPCS3 - Master Disconnected.log](https://github.com/RPCS3/rpcs3/files/5557640/RPCS3.-.Master.Disconnected.log)
Current Master w/ Networking Connected - [RPCS3 - Master Connected.log](https://github.com/RPCS3/rpcs3/files/5557639/RPCS3.-.Master.Connected.log)

#### 4. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/61633628/99481890-b5c1c780-2920-11eb-9c8a-5717b0d2f3a2.png)

#### 6. Please provide your system configuration:
* OS - Win 10
* CPU - 9900K
* GPU - 1080 Ti
* Driver version - 456.71.0.0

**Comment by Zeith78** [comment]
Tried #11822 with BLES00503 and the blackscreen no longer appears
