### ISSUE TITLE
Hyperdimension Neptunia VIctory [BLUS31150] - Broken graphics

### ISSUE THREAD

**Issue by Drvx** [RPCS3/rpcs3#9299]
VFX and UI are rendered incorrectly (e.g. missing/corrupted dialogue box, black squares in place of portraits messed up visual effects, etc.)  at the native resolution w/o additional settings.
Strict Rendering Mode and Write Color Buffer make no difference.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5568227/RPCS3.log.gz)
RSX capture:  
https://drive.google.com/file/d/1H4J5aJYDtNAG00aLz1F4Od1MgLYtv-vg/view?usp=sharing
rpcs3 version: 0.0.13-11265cbba5a

Some screenshots and comparison with an actual hardware:
## RPCS3
![screenshot-2020_11_19_15_04_47](https://user-images.githubusercontent.com/74725652/99695718-8e8d0680-2a96-11eb-857d-764b0e376045.png)
## PS3
![1](https://user-images.githubusercontent.com/74725652/99695667-7e752700-2a96-11eb-8470-7da674e9c208.png)

## RPCS3
![screenshot-2020_11_19_15_06_20](https://user-images.githubusercontent.com/74725652/99697921-dca30980-2a98-11eb-8593-15912dd0804a.png)
## PS3
![2](https://user-images.githubusercontent.com/74725652/99695981-dd3aa080-2a96-11eb-955d-0cd8e6ae2e91.png)

## RPCS3
![screenshot-2020_11_19_15_07_17](https://user-images.githubusercontent.com/74725652/99698051-02301300-2a99-11eb-87e3-1a8ed9746d36.png)
## PS3
![3](https://user-images.githubusercontent.com/74725652/99696072-f3486100-2a96-11eb-8275-606a48aeb94a.png)

## RPCS3
![screenshot-2020_11_19_15_47_59](https://user-images.githubusercontent.com/74725652/99698061-065c3080-2a99-11eb-860a-93259d483d00.png)
## PS3
![4](https://user-images.githubusercontent.com/74725652/99696087-f7747e80-2a96-11eb-8b13-1277705de570.png)

## RPCS3
![screenshot-2020_11_19_15_51_12](https://user-images.githubusercontent.com/74725652/99698080-09efb780-2a99-11eb-8241-89ce1aa832df.png)
## PS3
![5](https://user-images.githubusercontent.com/74725652/99697579-88982500-2a98-11eb-8682-83a4cb4f7f97.png)

## RPCS3
![screenshot-2020_11_19_15_55_58](https://user-images.githubusercontent.com/74725652/99698112-1247f280-2a99-11eb-8bbf-db39eef0fb33.png)
## PS3
![6](https://user-images.githubusercontent.com/74725652/99697586-8c2bac00-2a98-11eb-8b42-b457dd0f7528.png)

## RPCS3
![screenshot-2020_11_19_15_57_47](https://user-images.githubusercontent.com/74725652/99698192-2ab80d00-2a99-11eb-8bad-ffc906f0e461.png)
## PS3
![7](https://user-images.githubusercontent.com/74725652/99697597-8df56f80-2a98-11eb-8107-950de2d8b2ef.png)

## RPCS3
![screenshot-2020_11_19_16_06_25](https://user-images.githubusercontent.com/74725652/99698212-30155780-2a99-11eb-9109-fa9dace946c2.png)
## PS3
![8](https://user-images.githubusercontent.com/74725652/99697717-a796b700-2a98-11eb-8f23-d33dc478a146.png)

## RPCS3
![screenshot-2020_11_19_16_12_33](https://user-images.githubusercontent.com/74725652/99698223-33104800-2a99-11eb-9776-d69e93a1e815.png)
## PS3
![9](https://user-images.githubusercontent.com/74725652/99697732-abc2d480-2a98-11eb-92da-427d06b69d75.png)

Windows 10 pro 2004, x64
Ryzen r5 1600x
GTX 1070
Driver version: 457.09

**Comment by kd-11** [comment]
Seems to be another nvidia-only bug related to precision.
The capture replays fine on my AMD card and resembles the PS3 output. NVIDIA output is however incorrect.
