### ISSUE TITLE
Games with pkg update installed do not load.

### ISSUE THREAD

**Issue by Shuneferus** [RPCS3/rpcs3#9300]
Hello Megamouse, this pr prevents the game with pkg update installed from loading breaking along the emulator this behavior occurs in 3 games:
Phantom Breaker ファントムブレイカー：エクストラ [BLJM61098]
MOBILE SUIT GUNDAM SIDE STORIES [BLAS50710]
Gundam 0081 Battlefield Record [BLJS10050]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5569889/RPCS3.log)

**Comment by Megamouse** [comment]
The log doesn't contain any information
