### ISSUE TITLE
Win32 exception since latest update

### ISSUE THREAD

**Issue by WaschBaer0395** [RPCS3/rpcs3#9302]
Like title says , im getting a win32 exception since the latest update ..
only game i can start is demonsouls ( and that runs perfectly fine ) 
when i try to start any other game , for example Ratchet and clank, Last of us , or god of war 3  , the emulator freezes instantly and i get that error ( also no output on the console at the bottom ) 

drivers are up to date ( my gpu driver is up to date as it gets , since that gpu wont get any more updates, but i never had issues and before the update i was able to start the games ) 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5570193/RPCS3.log)

**Comment by Megamouse** [comment]
This bug should already be fixed. try to update the emulator again

**Comment by WaschBaer0395** [comment]
nevermind .. literally when i was done posting this, i got another update and now it works again
