### ISSUE TITLE
Fake PSN just to access locked levels and items offline and that doesn't need real P2P connection

### ISSUE THREAD

**Issue by Shuneferus** [RPCS3/rpcs3#9304]
Some games have content that can only be accessed in online mode new stages and extremely important items is the example of the game Gundam 0081 機動 戦 士 ガ ン ダ ム 戦 記 [BLJS10050].
 It is not so important to play with other "P2P" players but actually accessing the levels to pick up exclusive items in online mode but accessing the phase alone "offline - solo mode".
 If there was a way to cheat the game just to access the level even without having a real connection it would be very important and there are several other games in the same situation.
 Attached log of the game above trying to access online mode.
Log acess "RPCN"
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5570549/RPCS3.log)
Log acess "Simuled"
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5570566/RPCS3.log)

**Comment by lextra2** [comment]
You could probably trick the game (via patch/cheat engine) into loading a specific level.

**Comment by Shuneferus** [comment]
Hello lextra2 i appreciate the answer but this is not the case.
There are games that playing in offline mode we can only access the levels
in normal difficulty (Offline), but when accessing these same levels in
online mode it releases new levels: difficult (Online), Hell (Online).
 Accessing the difficult levels (Online) and Hell (Online) release
exclusive and unacceptable items in normal mode (Offline), in which case
specific to Gundam 0081 are essential.
I only opened this question because in this case you can access these
phases from online mode playing alone just to pick up the items and no real
P2P implementation is necessary.
There are several games that have a similar situation and if in the future
it is possible for developers to implement a solution (Fake PSN) for these
games it would be very cool.
  A hug.

Em sex., 20 de nov. de 2020 às 04:31, lextra2 <notifications@github.com>
escreveu:

**Comment by lextra2** [comment]
You seem to misunderstand.

You can, for sure, manipulate memory in such a way, that the game loads an online exclusive map (it might even be as simple as to change a single address' value). This would also be true for the games difficulty.

**Comment by Shuneferus** [comment]
Thanks for the answer I will research about it. A hug.

Em sáb., 21 de nov. de 2020 às 01:54, lextra2 <notifications@github.com>
escreveu:

**Comment by Shuneferus** [comment]
Thanks for the tip lextra2 I managed to release all the items I wanted through cheatengine. A hug and thanks.

**Comment by PartTimeCanadian** [comment]
> Thanks for the tip lextra2 I managed to release all the items I wanted through cheatengine. A hug and thanks.

Hey Shune, do you still have the table you made to achieve this?

**Comment by epyon102** [comment]
i would like to know this as well
