### ISSUE TITLE
Falhas graficas ao utilizar upscaling in game Gundam 0081 機動戦士ガンダム戦記 [BLJS10050]

### ISSUE THREAD

**Issue by Shuneferus** [RPCS3/rpcs3#9305]
When using upscaling from scale 150, these two failures are intensified as the scale increases.
1- Reflections of the turbine reflected.
2- Squares across the screen as shown in the attached image.
![Upscaling](https://user-images.githubusercontent.com/61365901/99740461-d4a19480-2aad-11eb-83b2-f0f3158ffcbf.jpeg)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5570481/RPCS3.zip)

**Comment by RainbowCookie32** [comment]
Check if increasing scale threshold fixes it

**Comment by Shuneferus** [comment]
In fact it is the opposite when increasing the scoring, the failures are
intensified.
I tested with the scales 150/200/250/300/400/500/600.

Em qui., 19 de nov. de 2020 às 22:11, Matias <notifications@github.com>
escreveu:

**Comment by AniLeo** [comment]
Title makes no sense, also you're not being clear enough, it seems as if you're just increasing resolution scale and not the threshold.

**Comment by pietroluongo** [comment]
The title is in Portuguese. It roughly translates to: "Graphical issues when upscaling Gundam 0081 機動戦士ガンダム戦記 [BLJS10050]"

**Comment by AniLeo** [comment]
Closing for failure to properly update the issue

This could have been fixed by #9337, but regardless it needs proper testing with changed thresholds and clarity on the provided information
