### ISSUE TITLE
Wild frametime and threading issues in the menu of Motorstorm: Pacific Rift

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#9314]
This is **not** a regression, the issue has been present for a very long time. The cutscene before the main menu and the main menu of the game both suffer from remarkably erratic frametimes and threading issues. The frametimes show a noticable pattern too, further hinting at an underlying threading issue.

![image](https://user-images.githubusercontent.com/10439488/99889334-592e1780-2c54-11eb-842f-c7f725fe9134.png)

![image](https://user-images.githubusercontent.com/10439488/99889335-5df2cb80-2c54-11eb-9721-369840026b32.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5578586/RPCS3.log)

Originally tested with 2 preferred spu threads, 3 spurs threads, and with spu loop detection off. Retested later with auto preferred spu threads, unlimited spurs threads and spu loop detection on, arrived to the same patterns and results.

The issue was recorded on my 7700HQ-based laptop, running a recent version of Windows 10, and on the latest master build of the emulator. The GPU driver is not up to date, but that shouldn't have been an issue considering this problem has been present for long. The game itself runs near-fullspeed on my system.

I also reached out to Fabian for a test on his 8400, he says he also experiences this issue but to a much lesser extent. For him that rollercoaster of a frametime graph only presents itself as rare(r) momentary spikes during that initial cutscene, and in the main menu he only gets spikes upon selecting submenus.

Not super high priority, but it has to do with threading, so I felt it was important to document as an edge-case.

**Notes:**
- this does not seem related to the unfocused window issue at a glance
- the problem persists with patches off
- Fabian's better / less severe results might be the result of him running at higher clocks, with a bigger cache and dual channel ram (mine is single ch.)
- the problem persists on other os-level process priorities too (tested: low, normal, high, realtime)
- the problem persists when launched from an SSD
- the problem persists on different blocksizes (safe, mega, giga)
- the problem persists on a "generic" LLVM target
- in these affected scenes, the game loves to hang the emu on exit (and crash it afterwards)

**Comment by Fabianpaw** [comment]
Spikes during the intro videos:
![grafik](https://user-images.githubusercontent.com/62476228/99889480-19682f80-2c56-11eb-9d83-9236ca9e016a.png)

Spikes in the Menus, which happen after selecting anything:
![spikes](https://user-images.githubusercontent.com/62476228/99889506-43b9ed00-2c56-11eb-9dae-5c7b96940a63.gif)

Both of these are often up to a second long.
Also worth mentioning this happens on both my 8400 and 8300H with the game on an SSD, though both to a much lesser extent than for Dio. I tested the game on PS3 and wasn't able to notice these frametime issues at all.
Not sure if it could be related, but there are RSX Cache misses showing up in the log after trying to open a file every time it spikes up in the menu.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5578626/RPCS3.zip)

**Comment by dio-gh** [comment]
After a bit of testing, I'd say there are 3 separate threading/frametime issues at play here.

- One would be the spikes Fabian experiences during that initial cutscene - on my end, this manifests as an extra high spike during the otherwise already high frametime sections (the image is misleading, as it is just as periodic for me as for him):

![image](https://user-images.githubusercontent.com/10439488/99892154-3f033200-2c72-11eb-87e3-acd11c0a31ae.png)

- The second issue is the one Fabian shows on his gif. I can reproduce those same momentary pauses on entering submenus, but only when entering them for the first two times. After that, it remains smooth.

- The third issue then is the one the ticket was originally opened for, which is the remarkably erratic, rollercoaster-like frametimes during the initial cutscene, and the extremely variable frametimes in the menu. Fabian doesn't seem to be able to repro that. 

From what we could wager, it could be down to the minor architectural differences between skylake and coffee lake, the cache size differences, the frequency differences (he's running .4 GHz faster) or RAM differences (he has a high latency but dual channel memory, i have a single channel meme tier stick).

Overall, seems like a pretty contrived case. Hope these can be investigated by a dev, or at least be independently repro'd by someone other than us.

**Comment by Fabianpaw** [comment]
Tried entering the same submenu multiples times, but even after like 7-8 times, still spiking.
![grafik](https://user-images.githubusercontent.com/62476228/99892367-838fcd00-2c74-11eb-8f06-b2c3d562ceb3.png)

Also worth mentioning someone on the RPCS3 Discord had the same issue some time ago, so it's not just us two.

**Comment by Satan86** [comment]
I have the same issue here with my i7-4770. TSX on or off makes no difference, I have terrible memory (mismatched 12gb 1333mhz) and I had the same issues with 8gb single channel as well, can't remember how bad it was compared to now. also, I noticed the game really likes to freeze if the window is in the background during the intro for me
![unknown](https://user-images.githubusercontent.com/61447828/99919618-73302e80-2d16-11eb-9405-3f0eb94343ab.png)

**Comment by Satan86** [comment]
New PC with 5600x and 16gb ram: Issue is a lot less present, still happens here and there throughout the intro video
![Screenshot_4](https://user-images.githubusercontent.com/61447828/102757909-bf3fb480-4350-11eb-881b-5886bb663ac8.png)
And after switching between game modes for an entire minute in the menus I only got one frametime spike

**Comment by dio-gh** [comment]
This issue is very vague, I don't think there's merit in keeping this ticket open. Frametime issues are difficult to triage and fix, and my PC is also way under the renewed recommended requirements of the product.

Closing.
