### ISSUE TITLE
[Issue] LBP:K upscaling better, but not perfect after #9281

### ISSUE THREAD

**Issue by Crafty-The-Fox** [RPCS3/rpcs3#9318]
## Quick summary
Please briefly describe what is not working correctly.

## Details

LBP:K upscaling is better after #9281 , but not Perfect.

#### 1. 
I made sure to use 1024 res scale threshold, and this only happens when you go into a race.

#### 2. 

[RSX 
Capture](https://cdn.discordapp.com/attachments/698041456451125281/780017200500572170/BCUS98254_20201122052816_capture.7z)

#### 3. Please attach screenshots of your problem.
https://youtu.be/FV3-xMrG0uc

#### 4. Please provide comparison with real PS3.
https://youtu.be/doG-EoPJemo

#### 5. Please provide your system configuration:
* Windows 10
* 9700k @ 4.9GHZ
* 2070 super
* 457.09

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/9337
