### ISSUE TITLE
Windows 10 HPET causes great negative impact on Ryzen 5 5600x performance

### ISSUE THREAD

**Issue by bruno-berchielli** [RPCS3/rpcs3#9320]
## Quick summary

Windows 10 HPET seems to cause great negative impact on Ryzen 5600x. 

## Details

After disabling HPET usin the command line` bcdedit /set useplatformclock false` and rebooting, performance seems to be back to normal. After reactivating HPET, the performance drops again. 

**Video:** https://www.youtube.com/watch?v=wloBqODDUuQ

HPET ON
![unknown 2](https://user-images.githubusercontent.com/34753722/99916193-6cd68e00-2ce7-11eb-952f-a4690ab3c239.png)

HPET OFF
![unknown](https://user-images.githubusercontent.com/34753722/99916195-6e07bb00-2ce7-11eb-81b5-84e67e14dcba.png)

Log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5580278/RPCS3.log)

**Comment by Yahfz** [comment]
Not an rpcs3 issue.
