### ISSUE TITLE
#9276 Broke the Resistance 3 BCES01118

### ISSUE THREAD

**Issue by coolllman** [RPCS3/rpcs3#9323]
## Quick summary
Freezes when the level starts after 0.0.13-11253 #9276, in 0.0.13-11249 all work

## Details
Freezes when the level starts after 0.0.13-11253 #9276

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.13-11253 #9276

#### 2. Please attach TWO logs:
0.0.13-11249 works
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5581985/RPCS3.log)

0.0.13-11253 not works
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5582010/RPCS3.log)

#### 6. Please provide your system configuration:
* Windows 10
* i5 8400
* Nvidia GTX 1660
* 457.30
* etc.

**Comment by MSuih** [comment]
You forgot to attach log files.

**Comment by coolllman** [comment]
Update, attach logs.

**Comment by Yahfz** [comment]
More games have regressed with this PR, we are gonna close it and create a new issue with all the games that regressed with it.

**Comment by Asinin3** [comment]
Ratchet & Clank A Crack in Time also broke with the https://github.com/RPCS3/rpcs3/issues/9323 Pull Request.
Dies with this error after it boots before showing title-screen.
`E {SPU[0x1000200] Thread (igCellSpursKernel1) [0x0f1a8]} VM: Access violation reading location 0x4003006 (unmapped memory) [type=u0]`
100% reproduce-able, confirmed by multiple users.
[After 11253.log.gz](https://github.com/RPCS3/rpcs3/files/5583945/RPCS3.log.gz)

**Comment by isJuhn** [comment]
eaf0bbc108c10f79a16b17240986d7afd6338fd1 is the broken commit.

**Comment by coolllman** [comment]
#9326 fix this
