### ISSUE TITLE
Upscaling making Threads glitches error again

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#9327]
When you upscale some games (like here GOW 3 or Motorstorm...), it appears some graphical glitches around sprites like before with normal scale.
![GOW3UPSCALEGLITCHE](https://user-images.githubusercontent.com/67762812/100001424-6f0e1a80-2dc3-11eb-8bf0-dcb1ee73cc19.jpg)
I'm using Windows 10 20H2 with Nvidia GTX 1080 and 32go RAM.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5585058/RPCS3.log)

**Comment by RainbowCookie32** [comment]
That looks like mesh trimming. You can't notice it at 720p, since that's where it was meant to be used, but you will when scaling.
Not an emulator issue, would need to be patched out, like how it was done on The Last of Us.

**Comment by kd-11** [comment]
You have some patches enabled that delete unused triangles. Not an rpcs3 bug.

**Comment by kd-11** [comment]
To clarify for future readers: This is the correct render. The missing pixels are from unused (degenerate) triangles that the game removes from the pipeline for performance reasons. It does this math assuming 720p resolution so ofc once you go over that you break Sony's optimizations.
