### ISSUE TITLE
RPCS3 fails to start if kernel was compiled with CONFIG_TRANSPARENT_HUGEPAGE=n

### ISSUE THREAD

**Issue by papjul** [RPCS3/rpcs3#9333]
## Quick summary
RPCS3 does not start

## Details
RPCS3 does not start if Linux kernel is compiled with CONFIG_TRANSPARENT_HUGEPAGE=n. This config is disabled by default on default kernel config.
According to madvise man, the MADV_HUGEPAGE and MADV_NOHUGEPAGE operations are available only if the kernel was configured with CONFIG_TRANSPARENT_HUGEPAGE.
Indeed, recompiling the kernel after enabling the config solved the issue.

#### 1. Commit that introduced the regression
https://github.com/RPCS3/rpcs3/commit/ab248e170cdedf1c3772e28566cae43a8987a4cb

#### 2. Logs
Directory ~/.cache/rpcs3 does not exist.
Crash with an error message on rpcs3/util/vm_native.cpp:114

#### 3. System configuration:
* OS: Gentoo Linux, kernel 5.4.x

**Comment by AniLeo** [comment]
Should be fixed on current master, ping to reopen if still an issue

**Comment by papjul** [comment]
I confirm it is fixed by using my old kernel for testing.

**Comment by Nekotekina** [comment]
Should work with any kernel now.
