### ISSUE TITLE
About BLJS10284 Masou Kishin F, when use ultimate skills,low fps

### ISSUE THREAD

**Issue by Xporen2** [RPCS3/rpcs3#9345]
## Details

hi, i have tried to play this game, it's really good  and stable but when i use ultimate skills，it will become very very slow,even 5-15 fps,and The sound and picture are not synchronized.Although it still can run.
And I find out that the ultimate skills is read in the folder which named "movies",and its file format is xxxxx.pam.
So I think maybe there are some problems in rpcs3 reading PAM  file format.
By the way,i use rpcs3 0.0.9-9929

#### 5. Please provide your system configuration:
RPCS3 v0.0.9-9929-d25ba03e Alpha | HEAD | Firmware version: 4.86
Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz | 4 Threads | 11.88 GiB RAM | TSC: Bad | AVX+ | TSX
Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0
·! 0:00:00.000000 RSX: Found vulkan-compatible GPU: 'GeForce GTX 960M' running on driver 442.50.0.0
·! 0:00:00.000028 RSX: Found vulkan-compatible GPU: 'Intel(R) HD Graphics 530' running on driver 0.401.295
os WIN 10

**Comment by AniLeo** [comment]
Closing as invalid since that's an old build plus your hardware is well below recommended specs
