### ISSUE TITLE
rsx: Resolution scale broken above 600% when using MSAA

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#9349]
Tested games
- Burnout Paradise: The Ultimate Box
- Catherine

![image](https://user-images.githubusercontent.com/10283761/100518334-cb3cba00-3188-11eb-9a5d-59d1856413c3.png)

**600% + MSAA**
![image](https://user-images.githubusercontent.com/10283761/100518317-b19b7280-3188-11eb-8827-7c4cb499a8e4.png)

**650% + MSAA**
![image](https://user-images.githubusercontent.com/10283761/100518307-a6484700-3188-11eb-9651-fcc06b820708.png)

**700% + MSAA**
![image](https://user-images.githubusercontent.com/10283761/100518320-b7915380-3188-11eb-892d-04df389adade.png)

**800% + MSAA**
![image](https://user-images.githubusercontent.com/10283761/100518330-bfe98e80-3188-11eb-81af-5bd76da5fd9c.png)

**Comment by AniLeo** [comment]
I think it's because of u16 usage on apply_resolution_scale

**Comment by kd-11** [comment]
It's not because of u16 in apply_resolution_scale. I can confirm correct upscaling of very large sizes, way past the PS3 limit of 4096x4096 pixels and it does scale the values correctly. The fact that it only happens with MSAA just means something else is fucked. I do not have enough VRAM to run the tested games at such high resolution scaling however, so I will have to pick this up later.

**Comment by AniLeo** [comment]
Catherine's menu uses 4.8G of VRAM on radv, unfortunately can't think of a smaller example to use

**Comment by AniLeo** [comment]
Validation layers show

·E 0:12:09.938810 {RSX [0x0002858]} RSX: ERROR: [Validation] Code 0 : Validation Error: [ VUID-VkImageCreateInfo-extent-02252 ] Object 0: handle = 0x7fb6bdab4df0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x49991c2f | vkCreateImage(): extent.width 16640 exceeds allowable maximum image extent width 16384. The Vulkan spec states: extent.width must be less than or equal to imageCreateMaxExtent.width (as defined in Image Creation Limits) (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkImageCreateInfo-extent-02252)

**Comment by kd-11** [comment]
The fix here is to simply refuse to upscale when the hardware limit is reached. Not the most elegant solution, but should avoid using different scaling factors on different data sets.

**Comment by kd-11** [comment]
If upscaling is impossible the program will abort with an error. This is a stop-gap solution until renderer restart is implemented some time in the future for savestate support.
