### ISSUE TITLE
The Dantes inferno Bridge glitch

### ISSUE THREAD

**Issue by Zekowind** [RPCS3/rpcs3#9356]
Hey everyone I need help. Im playing Dantes Inferno and I want to continue playing after the bridge bug but I cant cause it crashes over and over again so I want one thing and that is a Save file that is saved right after the section with the bridge. If you dont know what I am talking about the vid is here https://youtu.be/n0sHwu0tzOk . Its the most easy fix till this get fixed pls someone help. I know this might get removed but devs pls help me out guys .

**Comment by RainbowCookie32** [comment]
The place to go to for support, or requesting saves is [our Discord server](https://discord.me/RPCS3) or [the forums](https://forums.rpcs3.net/), not here. Please close the issue and move over to the proper channels.
