### ISSUE TITLE
Minor FPS regression in Demon's Souls after #9241

### ISSUE THREAD

**Issue by mshpakov** [RPCS3/rpcs3#9358]
## Quick summary
FPS in Demon's Souls drops from 54-55 FPS to 46-47 FPS at starting bonfire in Boletaria Palace 1-1 after #9241 

## Details
I see almost constant 60 fps in all location of DS. But in Boletaria on the starting bridge it was 55 FPS when watching towards boss location.
After #9241 build 11217 FPS dropped to 46-47 FPS in this location
Build 11216 works fine , the same as usual 54-55 FPS in this location

[rpcs3-v0.0.13-11216-52fa69d9.7z.zip](https://github.com/RPCS3/rpcs3/files/5622335/rpcs3-v0.0.13-11216-52fa69d9.7z.zip)
[rpcs3-v0.0.13-11217-c047ab61.7z.zip](https://github.com/RPCS3/rpcs3/files/5622336/rpcs3-v0.0.13-11217-c047ab61.7z.zip)

![изображение](https://user-images.githubusercontent.com/33029350/100737091-624d8000-33dc-11eb-8ea2-dbe155795db7.png)

![изображение](https://user-images.githubusercontent.com/33029350/100737125-6c6f7e80-33dc-11eb-829e-d3512e12a876.png)

**Comment by Nekotekina** [comment]
Okay, what's perf on master?

**Comment by mshpakov** [comment]
Same as on #9241

**Comment by Nekotekina** [comment]
Try https://github.com/RPCS3/rpcs3/pull/9361

**Comment by mshpakov** [comment]
> 
> 
> Try #9361
[RPCS3.log.7z.zip](https://github.com/RPCS3/rpcs3/files/5627707/RPCS3.log.7z.zip)

Unfortunately DS doesn't start with #9361 build
It stalls on black screen after starting.

**Comment by Nekotekina** [comment]
You can try to disable TSX in that case.

**Comment by Nekotekina** [comment]
Oh wait, nvm. Found some bug.

**Comment by Nekotekina** [comment]
Can you try again?

**Comment by mshpakov** [comment]
I've just tested 3 builds again.
Seems that #9361 fixes a bit but fps in that location is still not as with 11217 build.

Build 11336 (current master)
![изображение](https://user-images.githubusercontent.com/33029350/100938061-ad5eb480-34fc-11eb-8111-ea43e0939bad.png)
Build 11216
![изображение](https://user-images.githubusercontent.com/33029350/100938118-d0896400-34fc-11eb-9a9c-9b06a5ca9965.png)
Build from pull request #9361 (0.0.13-542fd1f6)
![изображение](https://user-images.githubusercontent.com/33029350/100938202-f3b41380-34fc-11eb-9dfe-3df6566cc371.png)

Logs from 9361 pull request build
[RPCS33-#9361.log.7z.zip](https://github.com/RPCS3/rpcs3/files/5632392/RPCS33-.9361.log.7z.zip)

**Comment by Nekotekina** [comment]
Very interesting, I didn't expect it to ever affect win10.

**Comment by Nekotekina** [comment]
Merged what I have for now, can't have full idea about what is happening. Maybe some bug will be found later.

**Comment by mshpakov** [comment]
"Silence All Logs" = OFF - is the reason for FPS drop in this case.
Checked with recent builds. FPS is as expected with "Silence All Logs" = OFF. Enabling logs drops few frames per second for some reason, it is bit spammy.

issue can be closed as for now.
