### ISSUE TITLE
Regression: Rock Band 3 [BLUS30463] 20s waiting delay on menus (#9258) 

### ISSUE THREAD

**Issue by pilonexyz** [RPCS3/rpcs3#9360]
There's a problem with Rock Band 3 [BLUS30463], starting from build 0.0.13-11236 #9258, not a game breaking bug but still annoying.
Each time i choose a song to play there is a waiting time delay of 20 seconds before i can choose which instrument, difficulty and play the song. During this delay the game is not responding at all and i must wait 20 seconds for every song i want to play.
Normally there is no waiting time at ll and until previous build 0.0.13-11235 #9255 everything was fine.
I tested the most recent build 0.0.13-11336 #9355 also and the problem is still there.

OS Windows 10 Pro 64-bit v1909
CPU i5 8400
GPU GTX1060
Driver 451.98

Here are the logs:

[rpcs3-v0.0.13-11235-e6f2f8ad_win64 [working].log](https://github.com/RPCS3/rpcs3/files/5623410/rpcs3-v0.0.13-11235-e6f2f8ad_win64.working.log)

[rpcs3-v0.0.13-11236-debfae06_win64 [not working].log](https://github.com/RPCS3/rpcs3/files/5623414/rpcs3-v0.0.13-11236-debfae06_win64.not.working.log)

https://drive.google.com/drive/folders/10kkn_3OOXPeczPkm9KpsWmXTElljHTBv?usp=sharing

**Comment by jeremybris** [comment]
Same with Resistance 3 and Arkham Asylum , #9293, @RipleyTom .

**Comment by dxzdxz1** [comment]
A simple workaround just this issue is enable network connection on rpcs3

![image](https://user-images.githubusercontent.com/5876517/104864752-ba9ef980-5918-11eb-8851-afe5bf4e4ba2.png)

**Comment by pilonexyz** [comment]
Thanks a lot for the Workaround tip.
Working fine.

Best Regards

Il giorno lun 18 gen 2021 alle ore 03:07 dxzdxz1 <notifications@github.com>
ha scritto:

**Comment by YuriNator557** [comment]
Fixed by #11822
