### ISSUE TITLE
Launching EBOOT.bin from command line/shortcut no longer working

### ISSUE THREAD

**Issue by michaelhagen** [RPCS3/rpcs3#9363]
## Quick summary
Apologies if this has already been reported. A few months ago (not sure of the exact version, whatever was the latest stable version at the time), launching an EBOOT.bin file directly from a shortcut or command line worked perfectly. This is most useful when using a frontend to run games on RPCS3.

## Details
Launching a game immediately by executing `"A:\Program Files\RPCS3\rpcs3.exe" "R:\PS3\SOME_GAME\PS3_GAME\USRDIR\eboot.bin"` in the command line or as a shortcut taget is no longer working starting with 0.0.12-10857. Launching a game from the GUI works fine.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.12-10857

#### 2. Please attach TWO logs:
[RPCS3_NOT_WORKING.log](https://github.com/RPCS3/rpcs3/files/5632402/RPCS3_NOT_WORKING.log)
[RPCS3_WORKING.log](https://github.com/RPCS3/rpcs3/files/5632410/RPCS3_WORKING.log)

#### 6. Please provide your system configuration:
Windows 10
Intel i7 7700K
Nvidia GTX 1080
Driver 457.30

**Comment by MSuih** [comment]
Files are now case sensitive. Try changing the eboot.bin to `EBOOT.BIN`

**Comment by michaelhagen** [comment]
That makes perfect sense, and correcting it resolved the "issue". I'm surprised it worked before with the wrong case!

Thank you for your help!
