### ISSUE TITLE
Ryzen 5XXX (Zen 3) series CPUs are misdetected as Zen/Zen+ by the built in thread scheduler

### ISSUE THREAD

**Issue by aqxa1** [RPCS3/rpcs3#9364]
## Quick summary
Ryzen 5XXX series CPUs such as the 5900x are detected as Zen/Zen+ by the built in thread scheduler. In my local builds I've modified the code such that the the scheduler assigns threads in the same way as Zen 2, although I'm not sure if that is optimal or not for Zen 3.

As a workaround to get Zen 2 like scheduling with the 5900X:
https://github.com/RPCS3/rpcs3/blob/13a0b88755e8043b959b1ac8f9d9b7be451003e7/Utilities/Thread.cpp#L2524

can be changed to:
```if (system_id.find("3900X") != umax || system_id.find("5900X") != umax)```

This does improve performance in some games on Linux with CFS too, so there is some merit to keeping the scheduler around as discussed in https://github.com/RPCS3/rpcs3/issues/8808.

**Comment by kd-11** [comment]
Actually, I forgot to merge some experimental work that rewrites the whole scheduler.
See https://github.com/RPCS3/rpcs3/pull/9313

**Comment by aqxa1** [comment]
Thanks, I'll test it out.

**Comment by MSuih** [comment]
This should be resolved now.
