### ISSUE TITLE
Patch incompatible with Patch Manager

### ISSUE THREAD

**Issue by Tachmag** [RPCS3/rpcs3#9365]
Despite following the instructions stated here: https://wiki.rpcs3.net/index.php?title=Help:Game_Patches, I can't seem to import a patch properly.
![Capture](https://user-images.githubusercontent.com/74123035/100950087-82c42a00-3503-11eb-803d-5b3b02668ab7.PNG)

The patch in question is the Disgaea D2" speed-patch.
I named the patch "imported_patch.yml" and added the required version indicator on the first line ("Version: 1.2") yet the patch manager can't seem to detect the patch.
![Capture2](https://user-images.githubusercontent.com/74123035/100949896-219c5680-3503-11eb-8ee6-ffca704216fd.PNG)

Attached to this is the patch in question, in .txt format due to GitHub's attachment format limitations.
[imported_patch.txt](https://github.com/RPCS3/rpcs3/files/5632997/imported_patch.txt)

RPCS3 version: 0.0.13-11336-13a0b887 Alpha

**Comment by MSuih** [comment]
The imported_patch.txt file you uploaded is in the old patch format. You just can't declare it as version 1.2, you need to modify it so that it actually follows the version 1.2 formatting.
