### ISSUE TITLE
Everytime i try to hangout with yoshida the game crashes, everything else is fine[Persona 5]

### ISSUE THREAD

**Issue by eylmaoxdxd** [RPCS3/rpcs3#9383]
So yea, everytime i try to hangout with him the game crash, i thought at first is was because of the new version but after downgrading it, it still the same so i dont know what is goiing on. Everything else in the game working completely fine
![Untitled](https://user-images.githubusercontent.com/45202750/101295664-93e99f80-3851-11eb-8ce1-055b408da869.png)
I get this error everytime                   
[savedata.zip](https://github.com/RPCS3/rpcs3/files/5649709/savedata.zip)
[config_NPEB02436_2.zip](https://github.com/RPCS3/rpcs3/files/5649711/config_NPEB02436_2.zip)
Here are my save file(the latest one is no.6 standing right next to yoshida) and settings i have all the dlc, play on 60 fps, and only have the spirtes fix mod installed
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5649722/RPCS3.zip)
here is my log file

**Comment by AniLeo** [comment]
Log shows settings different from default, specially some you shouldn't change and game patches enabled.

Needs restesting with default settings and no patches.

**Comment by digitaldude555** [comment]
@eylmaoxdxd retest with default setting and no patches.

**Comment by Megamouse** [comment]
closing. no test was provided
