### ISSUE TITLE
Restore Default Setting wont reset Resolution Scale Treshold

### ISSUE THREAD

**Issue by jokoputera** [RPCS3/rpcs3#9389]
## Quick summary
whenever i clicked "Restore Default Setting" in Configuration - GUI - UI Setting, the Resolution Scale Threshold stay the same (1x1)

## Details

ive tried to move the slider of Resolution Scale and Resolution Scale Threshold, then i try to restore default configuration. but the Resolution Scale Threshold remain into 1x1, then i need to click the Reset button to make slider back to default setting.

#### 5. Please provide your system configuration:
* OS Windows 10
* CPU Ryzen 5 3600
* GPU GTX 1660 Super
* Driver version Latest

**Comment by Megamouse** [comment]
That's because you are resetting the UI settings and not the emulator settings (which is not possible at the moment).
