### ISSUE TITLE
Game not loading at all Prince of Persia Epilogue [NPUB30424]

### ISSUE THREAD

**Issue by blueobelix1** [RPCS3/rpcs3#9392]
## Please do not ask for help or report compatibility regressions here, use [RPCS3 Discord server](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/) instead.
I don't know what that means, I hope this is not the case <3

## Quick summary
I am simply loading the game into the emulator and at after it compiles it doesn't start up, I will attach the error.

## Details

There is no long description, it simply doesn't load. I have tried modifying the default, starting with default RCPS3 settings, nothing worked.

#### 1. Please attach RPCS3's log.
Attached
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5660744/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
NOT the case I think
#### 3. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/75677333/101516556-491e7380-3988-11eb-8394-b978c8f4f97e.png)

#### 4. Please provide comparison with real PS3.
I don't have it in the house at the moment, I asked my siblings to download it for me from the PS3 
#### 5. Please provide your system configuration:
* OS Win 10
* CPU Processor	AMD Ryzen 7 2700 Eight-Core Processor, 3200 Mhz, 8 Core(s), 16 Logical Processor(s)

* GPU Adapter Description	Radeon RX 580 Series

* Driver version 20.9.1
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by AniLeo** [comment]
You mentioned Prince of Persia but your log only has a run for "Journey"

**Comment by blueobelix1** [comment]
> You mentioned Prince of Persia but your log only has a run for "Journey"

dont hate me, i updated now . cheers

**Comment by nitroos-ai** [comment]
The game loads fine and needs ZCULL Accuracy to be 'Precise' or 'Approximate' only!
Shows a white screen and freezes with 'Relaxed'.

**Comment by nitroos-ai** [comment]
Seems to work now.
https://www.youtube.com/watch?v=0I48jwdIlHY

**Comment by Megamouse** [comment]
I guess we can close it then
