### ISSUE TITLE
Regression: PS1 Classics don't work

### ISSUE THREAD

**Issue by Nekotekina** [RPCS3/rpcs3#9394]
## Quick summary
Black screen.

## Details
Under investigation...

**Comment by elad335** [comment]
Fixed something in it in #9398, similar to fw installation fix.

**Comment by elad335** [comment]
Needs testing though.

**Comment by elad335** [comment]
Yep it fixes it
![image](https://user-images.githubusercontent.com/18193363/101982982-4ff70000-3c80-11eb-9562-9547da6971e9.png)
