### ISSUE TITLE
Some verification error instead of startup

### ISSUE THREAD

**Issue by gaussandhisgun** [RPCS3/rpcs3#9411]
## Quick summary
Actually, I just can't open RPCS3 because of this.

## Details

Please describe the problem as accurately as possible.

#### 1. Please attach RPCS3's log.
No logs are present. Probably its because RPCS3 cant start?

#### 3. Please attach screenshots of your problem.
https://imgur.com/a/k4YCg45

#### 5. Please provide your system configuration:
* OS: Windows 7 x64
* CPU: Intel Core(TM) 2 Duo T8300 (dual-core 2.40GHz)
* GPU: NVidia RX 440 (or something like that)
* Driver version: as new as old, these drivers weren't updating since 2014
* etc.: 4G of ram, so my pc is just barely better than minimals. Also, some time ago it DID run, but nothing changed since then (apart from free space, probably).

#### Please include.
* Anything else you deem to be important

**Comment by gaussandhisgun** [comment]
p.s. build 11367, latest while writing this

**Comment by kd-11** [comment]
Duplicate of https://github.com/RPCS3/rpcs3/pull/9410. Request to reopen if fix provided there doesn't work for you.

**Comment by gaussandhisgun** [comment]
yup, I found the exact time when it DID run, it was Dec 2nd 2020 around 3AM GMT. So it was build 11336 which did work.

**Comment by gaussandhisgun** [comment]
aaand - you guess it, it doesn't! https://imgur.com/a/KaGCBaH

**Comment by gaussandhisgun** [comment]
Closed. Please add that users should reboot after installation. I rebooted, RPCS3 works now.
