### ISSUE TITLE
Regression: Implemented Trophy cause Splinter Cell Trilogy HD stuck at Intro

### ISSUE THREAD

**Issue by jokoputera** [RPCS3/rpcs3#9415]
## Quick summary
sceNpTrophyAbortHandle and sceNpTrophyRegisterContext cause Playable status to Intro in Splinter Cell Trilogy HD

## Details
It loads intro (including movie) and automatically stuck at choose game screen. it shows "Please Wait".
works on rpcs3-v0.0.7-9298-71c4a2a1_win64
but not working one commit after that, rpcs3-v0.0.7-9299-7cc6881a_win64

_exact_ build (or commit) information that introduced the regression you're reporting.
rpcs3-v0.0.7-9299-7cc6881a_win64 
https://github.com/RPCS3/rpcs3/pull/7111 (Implement sceNpTrophyTerm resources deallocation, sceNpTrophyAbortHandle)
![Screenshot 2020-12-11 183353](https://user-images.githubusercontent.com/59791277/101898994-a6603200-3bdf-11eb-9b81-b0242cc45a12.png)

#### 6. Please provide your system configuration:
* OS Windows 10
* CPU Ryzen 5 3600
* GPU GTX Super 1660
* Driver version latest

#### Please include.
tried using default setting, just run it, it will stuck at opening screen, while one commit before able to play up the first Splinter Cell until finish
i think Elad tried to improve this commit on https://github.com/RPCS3/rpcs3/pull/7087 but still not solve the problem

**Comment by frankyfife** [comment]
I also wanted to mention that it is no longer possible to load the individual (for example sc1.ppu.self). It gets the message "slected file or folder is corrupt" but it definitely is not.

Otherwise i can only confirm the error as stated above (for Tom Clancy's™ Splinter Cell® Trilogy HD [BLES01146], Disc Version).

**Comment by elad335** [comment]
missing log

**Comment by jokoputera** [comment]
sorry for report delay. last time my pc crashed and i need to reformat everything, since then i cant find my Splinter Cell anymore, so i cant give a logfile. but if you still want to try, please just run the game (BLES01146) and after intro (10sec) it will stuck.

last playable (v0.0.7-9298) :
https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-71c4a2a15ffcfd5a0d51ac0dbd8207d840419c9e/rpcs3-v0.0.7-9298-71c4a2a1_win64.7z 

broken (v0.0.7-9299): 
https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-7cc6881a579869ad544e8b7f7fd81b99d4983116/rpcs3-v0.0.7-9299-7cc6881a_win64.7z

thanks

**Comment by elad335** [comment]
reopen?

**Comment by elad335** [comment]
Also no logs, upload logs from before and after.

**Comment by taneofpain** [comment]
before (working)
U {PPU[0x1000002] Thread (Load Texture Thread) [0x00741038]} sys_prx TODO: _sys_prx_unload_module(id=0x23003e00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000002] Thread (Load Texture Thread) [0x00741038]} sys_prx TODO: _sys_prx_unload_module(id=0x23003d00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000002] Thread (Load Texture Thread) [0x00741038]} sys_prx TODO: _sys_prx_unload_module(id=0x23003c00, flags=0x0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00516790]} 'cellPadInit' failed with 0x80121103 : CELL_PAD_ERROR_ALREADY_INITIALIZED [1]
E {PPU[0x1000000] Thread (main_thread) [0x000513cc]} 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY [1]
E {PPU[0x1000000] Thread (main_thread) [0x0003e344]} 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY [2]
E {PPU[0x1000000] Thread (main_thread) [0x0003e350]} 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY [3]
E {PPU[0x1000000] Thread (main_thread) [0x005102f8]} cellSysutil: “Please wait...”
E {PPU[0x1000006] Thread (Trophy_Init_Thread_1) [0x00510078]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x390370, arg=*0xd0038f38, options=0x0)
U {PPU[0x1000006] Thread (Trophy_Init_Thread_1) [0x005100a8]} sceNpTrophy TODO: sceNpTrophyAbortHandle(handle=0x1)
E {PPU[0x1000006] Thread (Trophy_Init_Thread_1) [0x00510078]} 'sceNpTrophyRegisterContext' failed with 0x8002290f : SCE_NP_TROPHY_ERROR_PROCESSING_ABORTED [1]
E {PPU[0x1000007] Thread (Trophy_Init_Thread_2) [0x00510078]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x2, handle=0x2, statusCb=*0x390370, arg=*0xd0038f38, options=0x0)
U {PPU[0x1000007] Thread (Trophy_Init_Thread_2) [0x005100a8]} sceNpTrophy TODO: sceNpTrophyAbortHandle(handle=0x2)
E {PPU[0x1000007] Thread (Trophy_Init_Thread_2) [0x00510078]} 'sceNpTrophyRegisterContext' failed with 0x8002290f : SCE_NP_TROPHY_ERROR_PROCESSING_ABORTED [1]
E {PPU[0x1000008] Thread (Trophy_Init_Thread_3) [0x00510078]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x3, handle=0x3, statusCb=*0x390370, arg=*0xd0038f38, options=0x0)
U {PPU[0x1000008] Thread (Trophy_Init_Thread_3) [0x005100a8]} sceNpTrophy TODO: sceNpTrophyAbortHandle(handle=0x3)
E {PPU[0x1000008] Thread (Trophy_Init_Thread_3) [0x00510078]} 'sceNpTrophyRegisterContext' failed with 0x8002290f : SCE_NP_TROPHY_ERROR_PROCESSING_ABORTED [1]
E {PPU[0x1000000] Thread (main_thread) [0x00511098]} cellGame: cellGameCreateGameData(init=*0xd0010a20, tmp_contentInfoPath=*0xd0010920, tmp_usrdirPath=*0xd00109a0)
S {PPU[0x1000000] Thread (main_thread) [0x00511098]} cellGame: cellGameCreateGameData(): temporary directory '/dev_hdd0/game/_GDATA_14831461950000' has been created
E {PPU[0x1000000] Thread (main_thread) [0x005102f8]} cellSysutil: “Please wait...”

after:
U {PPU[0x1000002] Thread (Load Texture Thread) [0x00741038]} sys_prx TODO: _sys_prx_unload_module(id=0x23003e00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000002] Thread (Load Texture Thread) [0x00741038]} sys_prx TODO: _sys_prx_unload_module(id=0x23003d00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000002] Thread (Load Texture Thread) [0x00741038]} sys_prx TODO: _sys_prx_unload_module(id=0x23003c00, flags=0x0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x000513cc]} SYS: 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY [1]
E {PPU[0x1000000] Thread (main_thread) [0x0003e344]} SYS: 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY [2]
E {PPU[0x1000000] Thread (main_thread) [0x0003e350]} SYS: 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY [3]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x00510834, LR:0x000158b4]} cellSysutil: “Please wait...”
E {PPU[0x1000006] Thread (Trophy_Init_Thread_1) [HLE:0x005100d4, LR:0x000116c8]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x390370, arg=*0xd003cf38, options=0x0)
U {PPU[0x1000006] Thread (Trophy_Init_Thread_1) [HLE:0x00510104, LR:0x00011448]} sceNpTrophy TODO: sceNpTrophyAbortHandle(handle=0x1)

**Comment by elad335** [comment]
Nice, I'll fix quickly.

**Comment by elad335** [comment]
Test #9586

**Comment by taneofpain** [comment]
confirmed splinter cell is working now thanks very much

**Comment by Ian-DBarrett** [comment]
I have this problem with the splinter cell intro. how can i download this patch?

**Comment by jokoputera** [comment]
Use the newest release of RPCS3, then try it. If the problem still persists, then try open new case.

**Comment by Ian-DBarrett** [comment]
Hi thank you for your timely response. As far as I can tell I have the latest version of RPCS3 the firmware is the latest version, unless you were referring to something other than the firmware version? I'm a little new to RPCS3 when you say open a new case what exactly do you mean?

**Comment by RGB00255** [comment]
> Hi thank you for your timely response. As far as I can tell I have the latest version of RPCS3 the firmware is the latest version, unless you were referring to something other than the firmware version? I'm a little new to RPCS3 when you say open a new case what exactly do you mean?

Hello I'm late but what happens is if you have to disc version of this collection the game will install to the HDD but the progress won't display. You will just have to wait at the dimmed screen until it finishes installing, you can look at your storage access activity in task manager or something if you want to keep an eye on it.
