### ISSUE TITLE
Regression: Lighting problems in the crowd BLES00137 (#9377)

### ISSUE THREAD

**Issue by JosephMvit** [RPCS3/rpcs3#9418]
Hello, I would like to report some lighting corruption problems on WWE SmackDown vs. RAW 2008, since the 11347 build.
Tested in lastest build and has the same bug.

This also happens on BLES00361 and BLES00492

My pc
i7 7700 
16 gb ram
rx 580 8gb
windows 10

![image](https://user-images.githubusercontent.com/74170567/101968961-a6245e80-3c00-11eb-866d-d8582065a628.png)
as you can see in the image, the crowd looks too dark. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5682283/RPCS3.log.gz)

Thanks

**Comment by Asinin3** [comment]
So you're saying 11347 broke it, and 11346 was working, correct?
If that's the case you should link to the pull request in the top post so the dev gets tagged like this: https://github.com/RPCS3/rpcs3/pull/9377

**Comment by JosephMvit** [comment]
Yes, 11347 broke the lighting in those games, in 11346 the lighting works fine.

Thank you very much for link the issue to the pull request

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/9426 might fix this issue if the game changed shaders during a draw call for some reason. If its not fixed, I'll need an RSX capture to proceed.

**Comment by kapdap** [comment]
Providing RSX captures for [NPJB00135] Biohazard Code: Veronica

[0.0.13-11388](https://github.com/RPCS3/rpcs3/files/5685255/NPJB00135_20201214075211_capture.zip)
[0.0.13-11346](https://github.com/RPCS3/rpcs3/files/5685273/NPJB00135_20201214082045_capture.zip)

**Comment by JosephMvit** [comment]
> #9426 might fix this issue if the game changed shaders during a draw call for some reason. If its not fixed, I'll need an RSX capture to proceed.

Tested lastest build 11389 and Smackdown vs raw 2008 (BLES00137) has the same broken lighting.
How can i give you a rsx capture?
Thanks in advance

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/9434

**Comment by JosephMvit** [comment]
> Retest with #9434

which build is contains that fix? I tested the game on 11400, and still the same :/

**Comment by MSuih** [comment]
It will be on the next build after that. The build is still being compiler, but if nothing goes wrong it should appear in updater and downloads section within next 30 minutes

**Comment by JosephMvit** [comment]
> It will be on the next build after that. The build is still being compiler, but if nothing goes wrong it should appear in updater and downloads section within next 30 minutes

ok thank you

**Comment by JosephMvit** [comment]
![image](https://user-images.githubusercontent.com/74170567/102320928-bbc8b980-3f5b-11eb-9939-531531f05d04.png)


same graphical error :(

**Comment by kapdap** [comment]
No change with NPJB00135. Log and RSX capture from build 0.0.13-1109 attached. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5701820/RPCS3.log.gz)
[NPJB00135_20201216230158_capture.zip](https://github.com/RPCS3/rpcs3/files/5701829/NPJB00135_20201216230158_capture.zip)

Anything else we can provide to help debug this issue?

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/9450

**Comment by JosephMvit** [comment]
Got fixed, thank you.
