### ISSUE TITLE
Guitar hero: warrior of rock  - Access violation reading location 0x11de0008

### ISSUE THREAD

**Issue by sauza45** [RPCS3/rpcs3#9429]
Guitar hero: warriors of rock - BLES00801 version 1.00
When i launch this games its dosent work, black screen or just the first image, after it freeze.
i trie some random config but all time the same issue, and i see this:
F {PPU[0x1000004] Thread (Async Renderer Thread) [0x0063bb64]} VM: Access violation reading location 0x11de0008 (unmapped memory) [type=u32]

* OS: window 10
* CPU: intel i7 7700 3.6Ghz
* GPU: gtx 1070
* Driver version: 451.67.0.0
* RAM: 32Go
* RPCS3 v0.0.13-11388-e321765c Alph
* Firmware version: 4.86

(sorry its my first game on rpcs3)

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
