### ISSUE TITLE
Armored Core 4 [BLUS30027] save games with Write/Read Color Buffers can Dereference null memory

### ISSUE THREAD

**Issue by rpcstest8** [RPCS3/rpcs3#9441]
## Quick summary
Several issues reported about Armored Core 4 [BLUS30027] might very well be connected with a root issue caused by W/RCB.

## Details
#9395 
#9391 
#9387 
#9385 

Combined testing with forum user dofits has produced a save game (attached) that causes any mission launched to crash while W/RCB is enabled.  Loading the other saves from the forums for the crashing mission show them loading successfully with W/RCB disabled.  

#### 1. Please attach RPCS3's log.
See the logs of the attached issues.
Here's the save where, with W/RCB enabled, crashes when attempting to launch any mission.
[BLUS30027GAMEDAT000000F5K7M4001.zip](https://github.com/RPCS3/rpcs3/files/5698861/BLUS30027GAMEDAT000000F5K7M4001.zip)

**Comment by kd-11** [comment]
Known issue with an unmerged fix. See https://github.com/RPCS3/rpcs3/pull/9107

**Comment by nitroos-ai** [comment]
Are the issues fixed now?

**Comment by kd-11** [comment]
A permanent solution was committed several months ago. Closing.
