### ISSUE TITLE
Regression: MGS4 High Precision Z-buffer (#8869)

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#9447]
Issue requested by kd-11
MGS4 requires High Precision Z-buffer to properly emulate lightning in some levels of the game:
Incorrect behaviour
![42](https://user-images.githubusercontent.com/7060586/102386254-e6f4ec80-3fdf-11eb-9fb8-e1a6ed75e521.jpg)
Correct behaviour via using High Precision Z-buffer
![41](https://user-images.githubusercontent.com/7060586/102386326-012eca80-3fe0-11eb-9534-d2b9eb619219.jpg)
Yet game no longer reacts on using this option, regressed since
https://github.com/RPCS3/rpcs3/pull/8869

**Comment by kd-11** [comment]
Game uses depth-float and worked by accident before. The current code treats Z buffer as int when doing compare, this needs to be modified for depth-float games like this one. With the rest of the pipeline being float-aware, it's likely the last remaining part that doesn't obey floating point rules.
I'll push a fix soon.

**Comment by kd-11** [comment]
Please retest with https://github.com/RPCS3/rpcs3/pull/9512. Unfortunately the last PR introduced a general regression with shadows in all games. I'm not able to verify this game directly as it can be quite annoying to work with on some hardware configurations.

**Comment by kd-11** [comment]
The regression part was fixed previously, but some undefined behavior remained that is fixed with https://github.com/RPCS3/rpcs3/pull/9631. Technically it never worked correctly.
