### ISSUE TITLE
Regression: minimap interior in Final Fantasy XIII is blinking while character is moving/turning (#9450)

### ISSUE THREAD

**Issue by GitArUs** [RPCS3/rpcs3#9456]
Since commit 0a865bd9d (included in PR #9450) interior of minimap in Final Fantasy XIII is blinking unpleasantly when character moves or turns. I mean - minimap interior disappears for short moments.

OS: Linux
GPU: NVidia RTX 2070
Driver: 450.80.02
Renderer: Vulkan

I think I have managed to take rsx capture at the moment when the problem was visible (minimap invisible), but can't check it because every rsx capture I open is black...
[RSXcapture](https://drive.google.com/file/d/1DYpvZmiINPSdqTYuNydlscVWCOkQGOvi/view?usp=sharing)

Edit: Sorry, I forgot that I set VBlank Frequency to 120Hz instead of default 60Hz on advanced tab (helps with different graphics issue). With default settings it does not happen. Close it if You think the report is invalid.

Edit2: Sorry again. It happens also for default vblank frequency, but much less.

**Comment by kd-11** [comment]
You mention a commit as guilty trigger, can you confirm that reverting said commit fixes the problem?

**Comment by GitArUs** [comment]
Yes, I recompiled 6b3f722ff0a2a3a15ae62ab293d19ade84d9e65f and 0a865bd9dcad8a6cf2bdb2a867e2cf23baef58ea numerous times, because it was hard to belive that such change could cause it. But it looks like it did. I can check again later today if You really think it can not be a culprit.

**Comment by kd-11** [comment]
It could be a driver bug or spec bug. Khronos validation layers are testing the bound pipeline against the renderpass at bind time and throwing a bunch of pointless error messages at the emulator. They should move the check to when the pipeline is actually used for the first time instead, but I can also filter out such noise from the emulator though other means.
I'm not sure why nvidia cares when I bind the pipeline, this makes it a possible driver bug, but from past experience it is a waste of effort filing a bug with them, so I'll just revert the fix and use another approach.

**Comment by GitArUs** [comment]
Maybe it is worth trying with short lived driver branch (455.45.01) or beta (460.27.04) ?

**Comment by kd-11** [comment]
No harm in trying.

**Comment by kd-11** [comment]
I can confirm only happens on nvidia.

**Comment by GitArUs** [comment]
Tried with drivers 455.45.01 and 460.27.04 - no change, happens as well.

**Comment by kd-11** [comment]
Try with https://github.com/RPCS3/rpcs3/pull/9469. I cannot reproduce the issue locally, only seems present on Turing and newer.

**Comment by GitArUs** [comment]
Looks good. Thanks.
