### ISSUE TITLE
Regression: God of War Collection graphics not rendering properly on Vulkan (#9450)

### ISSUE THREAD

**Issue by YuriNator557** [RPCS3/rpcs3#9457]
## Quick summary
Please briefly describe what has stopped working correctly.
Graphics render correctly in OpenGL, but not in Vulkan. Issue happens on both games.

## Details
Is a video acceptable?
https://youtu.be/N3bo77tLngk

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
Regression happened in version 0.0.13-11412

#### 2. Please attach TWO logs:
[working.gz](https://github.com/RPCS3/rpcs3/files/5711431/working.gz)
[not working.gz](https://github.com/RPCS3/rpcs3/files/5711432/not.working.gz)

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
[BCES00800_20201217183100_capture.zip](https://github.com/RPCS3/rpcs3/files/5711465/BCES00800_20201217183100_capture.zip)
[RenderDoc, too big for github so it's on google drive](https://drive.google.com/file/d/1nKEzBDSc-p2op5UF2vV19Ybl75uqu9k_/view?usp=sharing)

#### 4. Please attach screenshots of your problem.
![capture2](https://user-images.githubusercontent.com/76178650/102528733-d784aa80-4096-11eb-9297-90bcef0c4a30.png)
![capture3](https://user-images.githubusercontent.com/76178650/102528736-d8b5d780-4096-11eb-94a8-ab1688a7d7b3.png)
![capture1](https://user-images.githubusercontent.com/76178650/102528737-d94e6e00-4096-11eb-8e38-90f7fcfdcf2a.png)

#### 5. Please provide comparison with real PS3.
Not entirely sure if I need to for this but just to be safe:
[comparison](https://youtu.be/UB7XmJyoq00)

#### 6. Please provide your system configuration:
Windows 10 2004
Ryzen 7 5800X
16GB DDR4-3600 CL18
EVGA FTW3 2070 SUPER
Game Ready Driver 460.79

i hope i did this right lol

**Comment by kd-11** [comment]
Try with https://github.com/RPCS3/rpcs3/pull/9469

**Comment by YuriNator557** [comment]
Looks like that fixed it, thanks.
![fix1](https://user-images.githubusercontent.com/76178650/102660651-4800f980-4173-11eb-9f3f-fece0f1570d3.png)
![fix2](https://user-images.githubusercontent.com/76178650/102660676-52bb8e80-4173-11eb-8c15-d3c80464e6ba.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5718015/RPCS3.log.gz)
