### ISSUE TITLE
[Feature Request] Patch/option to disable Ninja Gaiden 3: Razor's Edge polygon culling

### ISSUE THREAD

**Issue by Hammerhead88** [RPCS3/rpcs3#9458]
## Quick summary
On Ninja Gaiden 3:RE, there's a optimization function that culls polygons from character's models. Normally it's not visible in the game's native 720p resolution, however when upscaled in RPCS3 past that it becomes very visible on the playable character's faces and some bosses.
![20201212013745_1](https://user-images.githubusercontent.com/76188234/102559610-def78400-4095-11eb-85b0-4628fa5c3b03.jpg)
![20201213220009_1](https://user-images.githubusercontent.com/76188234/102561086-6692c200-4099-11eb-937f-023e07890b15.jpg)  ![20201212013349_21](https://user-images.githubusercontent.com/76188234/102561098-6db9d000-4099-11eb-94ff-2b42baa9f80f.jpg)

## Details
The game is working as intended by the devs, so this isn't a glitch however it's quite an eyesore when brought up to modern resolutions. 

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
A patch file, memory cheat, or a menu in RPCS3 for game specific fixes in the same vein as the gamefixes for PCSX2 would be good solutions for this. It can either be a part of the emulation settings, a built in cheat file for this game, or an automatic fix that applies when this specific game is launched. 

#### 2. Please tell us, why your feature is important to RPCS3.
So that Ninja Gaiden 3: RE can be emulated properly at resolutions over 720p.
One of the main reasons why I love emulation is the ability to play older games with modern enhancements.

#### 3. Please attach screenshots of the feature implemented in other projects.
Something along the line of PCSX2's game fixes menu might work. 
![Screenshot (611)](https://user-images.githubusercontent.com/76188234/102562480-c8a0f680-409c-11eb-9d6c-52e6b8fca05f.png)
However it also comes with .pnach files that contain fixes for most games in the PS2 library, mostly widescreen hacks, but also some fixes that make games playable at modern resolutions without crashing. They activate when the emulator sees the ID of what game is being booted up.

#### 4. Please provide your system configuration:
I'm not really sure if that will actually be required for this, but if a dev comes here and asks me post it, then I guess I will. 

First time posting here, sorry if I messed something up. plz no bully.

**Comment by RainbowCookie32** [comment]
This is not an issue with the emulator. 

When using upscaling things like this can break, expected behavior. The workaround would be a community patch, like the ones seen on Uncharted or TLoU, which is not something tracked here (or anywhere really).

**Comment by AniLeo** [comment]
Closing as explained above, this is a request for a game patch which shouldn't be here on the tracker
