### ISSUE TITLE
Error compiling RPCS3 on MacOS

### ISSUE THREAD

**Issue by tanner02** [RPCS3/rpcs3#9468]
> Scanning dependencies of target rpcs3_emu
> [ 79%] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cmake_pch.hxx.pch
> In file included from <built-in>:1:
> In file included from /Users/_name_/Downloads/rpcs3/rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cmake_pch.hxx:5:
> In file included from /Users/_name_/Downloads/rpcs3/rpcs3/stdafx.h:16:
> /Users/_name_/Downloads/rpcs3/rpcs3/util/types.hpp:769:13: error: use of undeclared identifier
>       '__builtin_LINE'
>         u32 line = __builtin_LINE(),
>                    ^
> /Users/_name_/Downloads/rpcs3/rpcs3/util/types.hpp:771:21: error: use of undeclared identifier
>       '__builtin_FILE'
>         const char* file = __builtin_FILE(),
>                            ^
> /Users/_name_/Downloads/rpcs3/rpcs3/util/types.hpp:772:21: error: use of undeclared identifier
>       '__builtin_FUNCTION'
>         const char* func = __builtin_FUNCTION()) noexcept
>                            ^
> /Users/_name_/Downloads/rpcs3/rpcs3/util/types.hpp:856:13: error: use of undeclared identifier
>       '__builtin_LINE'
>         u32 line = __builtin_LINE(),
>                    ^
> /Users/_name_/Downloads/rpcs3/rpcs3/util/types.hpp:858:21: error: use of undeclared identifier
>       '__builtin_FILE'
>         const char* file = __builtin_FILE(),
>                            ^
> /Users/_name_/Downloads/rpcs3/rpcs3/util/types.hpp:859:21: error: use of undeclared identifier
>       '__builtin_FUNCTION'
>         const char* func = __builtin_FUNCTION())
>                            ^
> /Users/_name_/Downloads/rpcs3/rpcs3/util/types.hpp:874:13: error: use of undeclared identifier
>       '__builtin_LINE'
>         u32 line = __builtin_LINE(),
>                    ^
> /Users/_name_/Downloads/rpcs3/rpcs3/util/types.hpp:876:21: error: use of undeclared identifier
>       '__builtin_FILE'
>         const char* file = __builtin_FILE(),
>                            ^
> /Users/_name_/Downloads/rpcs3/rpcs3/util/types.hpp:877:21: error: use of undeclared identifier
>       '__builtin_FUNCTION'
>         const char* func = __builtin_FUNCTION())
>                            ^
> In file included from <built-in>:1:
> In file included from /Users/_name_/Downloads/rpcs3/rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cmake_pch.hxx:5:
> In file included from /Users/_name_/Downloads/rpcs3/rpcs3/stdafx.h:17:
> /Users/_name_/Downloads/rpcs3/rpcs3/util/atomic.hpp:496:47: error: invalid output constraint '=@ccc' in
>       asm
>                 __asm__ volatile ("lock btsl %2, 0(%1)\n" : "=@ccc" (result) : "r" (dst), "Ir" (b...
>                                                             ^
> /Users/_name_/Downloads/rpcs3/rpcs3/util/atomic.hpp:518:47: error: invalid output constraint '=@ccc' in
>       asm
>                 __asm__ volatile ("lock btrl %2, 0(%1)\n" : "=@ccc" (result) : "r" (dst), "Ir" (b...
>                                                             ^
> /Users/_name_/Downloads/rpcs3/rpcs3/util/atomic.hpp:547:47: error: invalid output constraint '=@ccc' in
>       asm
>                 __asm__ volatile ("lock btcl %2, 0(%1)\n" : "=@ccc" (result) : "r" (dst), "Ir" (b...
>                                                             ^
> /Users/_name_/Downloads/rpcs3/rpcs3/util/atomic.hpp:993:6: error: invalid output constraint '=@ccz' in asm
>                         : "=@ccz" (result)
>                           ^
> In file included from <built-in>:1:
> In file included from /Users/_name_/Downloads/rpcs3/rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cmake_pch.hxx:5:
> In file included from /Users/_name_/Downloads/rpcs3/rpcs3/stdafx.h:19:
> /Users/_name_/Downloads/rpcs3/Utilities/StrFmt.h:310:15: error: use of undeclared identifier
>       '__builtin_LINE'
>                         u32 line = __builtin_LINE(),
>                                    ^
> /Users/_name_/Downloads/rpcs3/Utilities/StrFmt.h:312:23: error: use of undeclared identifier
>       '__builtin_FILE'
>                         const char* file = __builtin_FILE(),
>                                            ^
> /Users/_name_/Downloads/rpcs3/Utilities/StrFmt.h:313:23: error: use of undeclared identifier
>       '__builtin_FUNCTION'
>                         const char* func = __builtin_FUNCTION())
>                                            ^
> In file included from <built-in>:1:
> In file included from /Users/_name_/Downloads/rpcs3/rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cmake_pch.hxx:5:
> In file included from /Users/_name_/Downloads/rpcs3/rpcs3/stdafx.h:20:
> /Users/_name_/Downloads/rpcs3/Utilities/File.h:237:15: error: use of undeclared identifier
>       '__builtin_LINE'
>                         u32 line = __builtin_LINE(),
>                                    ^
> /Users/_name_/Downloads/rpcs3/Utilities/File.h:239:23: error: use of undeclared identifier
>       '__builtin_FILE'
>                         const char* file = __builtin_FILE(),
>                                            ^
> /Users/_name_/Downloads/rpcs3/Utilities/File.h:240:23: error: use of undeclared identifier
>       '__builtin_FUNCTION'
>                         const char* func = __builtin_FUNCTION()) const
>                                            ^
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 20 errors generated.
> make[2]: *** [rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cmake_pch.hxx.pch] Error 1
> make[1]: *** [rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/all] Error 2
> make: *** [all] Error 2

OS: MacOS Mojave 10.14.6

**Comment by AniLeo** [comment]
Unsupported platform, this is not the only issue you'll hit as new commits haven't been taking MacOS in account for a long time, better to discuss at #5361
