### ISSUE TITLE
Emulated Portal "disconnects" during gameplay

### ISSUE THREAD

**Issue by Frozenreflex** [RPCS3/rpcs3#9473]
I've seen this happen in Giants and Swap Force, but likely happens in SuperChargers and Imaginators. At some point during gameplay, at seemingly random times, the emulated portal will not swap characters. Attempting to swap in a new character will keep whatever previous character you were using. I've also seemingly had character data corrupted from this (the manage menu reports that the character has an insane amount of XP and money, and the game says that the toy is messed up), but I haven't had it happen consistently.

**Comment by Megamouse** [comment]
Why is there no log attached?

**Comment by Frozenreflex** [comment]
Whoops... this should a log of the latest I've had it happen. In case it helps to find stuff in the log, I was originally playing as Swarm (ID 101), then tried to switch to Dark Stealth Elf (ID 26).
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5720265/RPCS3.log)

**Comment by Frozenreflex** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5726219/RPCS3.log)
Swap Force seems to drop character swaps every time
