### ISSUE TITLE
0.0.13-11467-0055d84b Alpha Fatal Firmware Error 

### ISSUE THREAD

**Issue by TimNether64** [RPCS3/rpcs3#9488]
As far as I am aware, this is the first documentation of this error.
![Screenshot (1)](https://user-images.githubusercontent.com/50605401/102972313-f4195a80-454e-11eb-921c-2ebb33d28d71.png)
I am trying to run Metal Gear HD Collection, downloaded from Vimm's Lair (https://vimm.net/vault/25247).
If it helps I'm on a Lenovo 370 with a dualshock 4 plugged into a USB port. V-tx is enabled. Nothing else but Dolphin, 7-Zip, Steam and Chrome are installed apart from pre-installed programs.

**Comment by elad335** [comment]
Install firmware!

**Comment by AniLeo** [comment]
Ah yes let's pirate a game and not only ask for support for it but also link to the illegal download

**Comment by TimNether64** [comment]
its technically not piracy bc theyre not for profit
