### ISSUE TITLE
vk: Spec violations with Strict Rendering Mode enabled

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#9495]
- [ ]  `ERROR: [Validation] Code 0 : Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x10213c80, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Result type component width must be 32 bits %484 = OpDPdy %v4half %483` (Triggered on Linux Intel, Games: Skate 3 Demo) Note: Harmless, glslang compiler limitation, just boot the game, appears before title screen

- [ ] `ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkDestroyImage-image-01000 ] Object 0: handle = 0x2166bbf8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf2d29b5a | Cannot call vkDestroyImage on VkImage 0x950f1c0000044b9d[] that is currently in use by a command buffer. The Vulkan spec states: All submitted commands that refer to image, either directly or via a VkImageView, must have completed execution` (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkDestroyImage-image-01000) (Triggered on Windows AMD/NVIDIA, Games: NieR, God of War 3)

- [ ] `ERROR: [Validation] Code 0 : Validation Error: [ UNASSIGNED-CoreValidation-DrawState-QueryNotReset ] Object 0: handle = 0x12407f020, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x9cacd67a | vkCmdBeginQuery(): VkQueryPool 0x7020e900000ac023[] and query 0: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.` (Triggered on Windows AMD, Games: Call of Duty Black Ops)

- [ ] `E RSX: ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkCmdBlitImage-srcOffset-00244 ] Object 0: handle = 0x15205ea80, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x50d6adcd | vkCmdBlitImage(): region [0] srcOffset[].y values (0, 720) exceed srcSubresource height extent (360). The Vulkan spec states: For each element of pRegions, srcOffsets[0].y and srcOffsets[1].y must both be greater than or equal to 0 and less than or equal to the height of the specified srcSubresource of srcImage (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkCmdBlitImage-srcOffset-00244)` - Triggered in GOWA with Nvidia

**Fixed by #10900**
- [X] `ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkAllocateMemory-deviceCoherentMemory-02790 ] Object 0: handle = 0x7ff139925100, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x8830dc95 | vkAllocateMemory: attempting to allocate memory type 7, which includes the VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD memory property, but the deviceCoherentMemory feature is not enabled. The Vulkan spec states: If the deviceCoherentMemory feature is not enabled, pAllocateInfo->memoryTypeIndex must not identify a memory type supporting VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD` (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkAllocateMemory-deviceCoherentMemory-02790) (Triggered on Linux AMD, Games: Drakengard 3, Minecraft) Note: Just boot the games, appears before title screen or when going in-game

- [X] `ERROR: [Validation] Code 0 : Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0xab34340, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (StencilExportEXT) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied` (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091) (Triggered on Linux AMD, Games: Sonic Unleashed)

- [X] `ERROR: [Validation] Code 0 : Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-04147 ] Object 0: handle = 0xab34340, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x3d492883 | vkCreateShaderModule(): The SPIR-V Extension (SPV_EXT_shader_stencil_export) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the SPIR-V extensions listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied` (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-04147) (Triggered on Linux AMD, Games: Sonic Unleashed)

- [X] `ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkCmdClearAttachments-aspectMask-02503 ] Object 0: handle = 0x34d9dd08, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x873171ec | vkCmdClearAttachments() pAttachments[0] aspectMask has VK_IMAGE_ASPECT_STENCIL_BIT but there is no stencil attachment in subpass The Vulkan spec states: If the aspectMask member of any element of pAttachments contains VK_IMAGE_ASPECT_STENCIL_BIT, then the current subpass' depth/stencil attachment must either be VK_ATTACHMENT_UNUSED, or must have a stencil component`(https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkCmdClearAttachments-aspectMask-02503) (Triggered on Windows NVIDIA, Games: Killzone 2 Demo)

- [X] `ERROR: [Validation] Code 0 : Validation Error: [ VUID-VkSamplerCreateInfo-addressModeU-01079 ] Object 0: handle = 0x2e5028a8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x1aa95c2b | vkCreateSampler(): addressModeU is set to VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE but the VK_KHR_sampler_mirror_clamp_to_edge extension or samplerMirrorClampToEdge feature has not been enabled. The Vulkan spec states: If samplerMirrorClampToEdge is not enabled, and if the VK_KHR_sampler_mirror_clamp_to_edge extension is not enabled, addressModeU, addressModeV and addressModeW must not be VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE` (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-VkSamplerCreateInfo-addressModeU-01079) (Triggered on Windows NVIDIA, Games: Need for Speed: Rivals)

- [X] `ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkCmdDrawIndexed-None-02699 ] Object 0: handle = 0xe0b7720000034a39, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xa44449d4 | Descriptor set VkDescriptorSet 0xe0b7720000034a39[] encountered the following validation error at vkCmdDrawIndexed() time: Descriptor in binding #15 index 0 requires UINT component type, but bound descriptor format is VK_FORMAT_B8G8R8A8_UNORM. The Vulkan spec states: Descriptors in each bound descriptor set, specified via vkCmdBindDescriptorSets, must be valid if they are statically used by the VkPipeline bound to the pipeline bind point used by this command` (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkCmdDrawIndexed-None-02699) (Triggered on Windows/Linux NVIDIA/AMD, Games: Sonic Unleashed, Sonic Unleashed Demo) Note: Happens in the middle of the demo, on the part with chairs

- [X] `ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkCmdCopyBufferToImage-imageOffset-00200 ] Object 0: handle = 0xf95345000003cc48, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x7239f3a5 | vkCmdCopyBufferToImage(): Both pRegion[1] imageoffset.z (0) and (imageExtent.depth + imageOffset.z) (8) must be >= zero or <= image subresource depth (4). The Vulkan spec states: For each element of pRegions, imageOffset.z and (imageExtent.depth + imageOffset.z) must both be greater than or equal to 0 and less than or equal to the depth of the specified imageSubresource of {imageparam}` (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkCmdCopyBufferToImage-imageOffset-00200) (Triggered on Windows/Linux NVIDIA/AMD, Games: Sonic Unleashed, GTA V) Note: Happens on the second cutscene of Sonic Unleashed after you press new game

- [X] `ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkCmdCopyBufferToImage-pRegions-06217 ] Object 0: handle = 0xf95345000003cc48, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xb9c95d3e | vkCmdCopyBufferToImage(): pRegion[1] exceeds image bounds. The Vulkan spec states: The image region specified by each element of pRegions must be contained within the specified imageSubresource of dstImage` (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-vkCmdCopyBufferToImage-pRegions-06217) (Triggered on Windows/Linux NVIDIA/AMD, Games: Sonic Unleashed) Note: Happens on the second cutscene of Sonic Unleashed after you press new game

- [X] `ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkCmdCopyBufferToImage-pRegions-00172 ] Object 0: handle = 0x964e4500000683f4, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x86fa53ce | vkCmdCopyBufferToImage(): pRegion[1] exceeds image bounds. The Vulkan spec states: The image region specified by each element of pRegions must be a region that is contained within dstImage` (https://vulkan.lunarg.com/doc/view/1.2.182.0/windows/1.2-extensions/vkspec.html#VUID-vkCmdCopyBufferToImage-pRegions-00172) (Triggered on Windows AMD, Games: GTA V)

**Fixed by #10382**
- [X] https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDraw-None-04584 (Triggered on Minecraft, The Last of Us)

**Fixed by #9471**
- [X] https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDraw-magFilter-04553 (Triggered on GT5 v1.00 menu)
- [X] https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDraw-None-02698 (Triggered on GT5 v1.00 menu)

---

**Not issues, can be ignored:**
- `WARNING: [Validation] Code 0 : Validation Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0x9f6655000000144f, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | fragment shader writes to output location 1 with no matching attachment` (Triggered on Windows NVIDIA, Games: NieR and seemingly all games)
Note: This is how the PlayStation 3 works and it's not actually an error. Ignore and don't report duplicates of this one.

- `ERROR: [Validation] Code 0 : Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x38eb6020, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (Float16) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)` (Triggered by compiling shaders with float16 enabled)
This is a spec issue, we have met the requirements but the documentation failed to update some structure aliases. https://github.com/KhronosGroup/Vulkan-Docs/issues/1739

**Comment by kd-11** [comment]
Will fix soon. Requires a proper temporary register redirect in glsl output. Technically this is the result of all major components shifting blame to each other. Rpcs3 assumes the SPIRV compiler will correctly handle the vec4->half4 conversion but it actually does not.

**Comment by AniLeo** [comment]
Added `E RSX: ERROR: [Validation] Code 0 : Validation Error: [ VUID-vkAllocateMemory-deviceCoherentMemory-02790 ] Object 0: handle = 0x7ff139925100, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x8830dc95 | vkAllocateMemory: attempting to allocate memory type 7, which includes the VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD memory property, but the deviceCoherentMemory feature is not enabled. The Vulkan spec states: If the deviceCoherentMemory feature is not enabled, pAllocateInfo->memoryTypeIndex must not identify a memory type supporting VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD` (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkAllocateMemory-deviceCoherentMemory-02790), happens when starting and going in-game on Drakengard 3, Minecraft, probably other games.

**Comment by AniLeo** [comment]
Added 6 new errors and 1 new warning

**Comment by Yahfz** [comment]
ERROR: [Validation] Code 0 : Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x38eb6020, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (Float16) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091) - Triggered in GOWA on Nvidia

**Comment by kd-11** [comment]
The spirv issue is a spec issue. External issue: https://github.com/KhronosGroup/Vulkan-Docs/issues/1739

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/11425 Should fix vkCmdBlitImage/vkCmdCopyImage/vkCmdCopyBufferToImage violations which complain about region sizes.
@Yahfz Check if the error disappears from GOWA

**Comment by Yahfz** [comment]
![image](https://user-images.githubusercontent.com/17715080/150642829-df9bfcb8-26de-437e-b5ae-af215192a159.png)


> #11425 Should fix vkCmdBlitImage/vkCmdCopyImage/vkCmdCopyBufferToImage violations which complain about region sizes. @Yahfz Check if the error disappears from GOWA

yep, still happens with #11425

**Comment by kd-11** [comment]
I meant the other error about image dimensions being out of bounds. This one (float16) is a bug in the SDK.

**Comment by Yahfz** [comment]
Oh, i can't read apparently. The PR fixes vkCmdBlitImage, the other ones you mentioned weren't triggered on master for me.

**Comment by kd-11** [comment]
I fixed most if not all of these. Let's have a new tracker if more errors are found.
