### ISSUE TITLE
controller only works as root out of the box on debain

### ISSUE THREAD

**Issue by nonetrix** [RPCS3/rpcs3#9507]
I'm getting this error message I have tried the link it suggested and edited said files

E DS4: hid_open_path failed! Reason: 0000000000000000
E DS4: One or more DS4 pads were detected but couldn't be interacted with directly
E DS4: Check https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration for intructions on how to solve this issue

running as sudo fixes the issue I have tried adding my user to the plugdev group as well with no luck also it works fine on arch and gentoo

if I find out how to fix this it would be nice if it was added to the website for other dumbs like me

**Comment by AniLeo** [comment]
This seems like a non-RPCS3 issue and something wrong with your distro from the way you're describing it

**Comment by AniLeo** [comment]
Closing since it's not something that's worth tracking here as it's not our bug
