### ISSUE TITLE
Regression: Dynamic shadows bug in BLES00137, BLES00361, BLES01045, BLUS30443 (#9471)

### ISSUE THREAD

**Issue by JosephMvit** [RPCS3/rpcs3#9509]
Hello everyone, I would like to report a regression. The games listed in the title, seem to have dynamic shadows bugs, in WWE SvR 2008,2009 and 2011 there are no longer dynamic shadows, and in demon souls the shadows are bugged.
![screenshot-2020_12_27_18_56_40](https://user-images.githubusercontent.com/74170567/103180644-5be4e380-4876-11eb-9e50-c9fdac9f6d8a.png)
![screenshot-2020_12_27_19_02_03](https://user-images.githubusercontent.com/74170567/103180646-5d161080-4876-11eb-9836-c7eb08ed1252.png)

Here are some screenshots

My pc
i7 7700
Rx 580 8gb ddr5
Windows 10 64 bit
16 gb ram

Tested on lastest build 11480. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5745331/RPCS3.log.gz)

Regression started in build 11473

**Comment by AniLeo** [comment]
Missing in what build it regressed

**Comment by JosephMvit** [comment]
> Missing in what build it regressed

Regression starts in build 11473
