### ISSUE TITLE
Linux compilation fails

### ISSUE THREAD

**Issue by Blad3forc3** [RPCS3/rpcs3#9511]
## Quick summary
Linux compilation fails

## Details

[ 98%] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/register_editor_dialog.cpp.o
[ 98%] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/render_creator.cpp.o
/media/ade/Temp/rpcs3/rpcs3/rpcs3qt/render_creator.cpp:16:12: error: expected constructor, destructor, or type conversion before ‘(’ token
   16 | LOG_CHANNEL(cfg_log, "CFG");
      |            ^
/media/ade/Temp/rpcs3/rpcs3/rpcs3qt/render_creator.cpp: In member function ‘void render_creator::update_names(const QStringList&)’:
/media/ade/Temp/rpcs3/rpcs3/rpcs3qt/render_creator.cpp:105:4: error: ‘cfg_log’ was not declared in this scope
  105 |    cfg_log.error("render_creator::update_names could not update renderer %d", i);
      |    ^~~~~~~
make[2]: *** [rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/build.make:692: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/render_creator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:18561: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by arabek** [comment]
Compiles for me:
```
$ make
(…)
[100%] Built target rpcs3
~/src/rpcs3
$ git rev-parse HEAD
4a8a161a43a1ffd5acc572d4ff63304bc4b7c1be
```

**Comment by AniLeo** [comment]
Missing full build log, system information, used compiler

**Comment by Blad3forc3** [comment]
Vulkan Instance Version: 1.2.148
Cmake version 3.19.1
GCC:9
There are 2 choices for the alternative gcc (providing /usr/bin/gcc).

  Selection    Path             Priority   Status
------------------------------------------------------------
  0            /usr/bin/gcc-10   100       auto mode
  1            /usr/bin/gcc-10   100       manual mode
* 2            /usr/bin/gcc-9    90        manual mode
QT Version: 5.15.2
SDL2 Dev libraries: 2.0.12
libglvnd : 1.3.1-1ubuntu0.20.04.1

nvidia GPU: 
KDE Neon 5.20.4

I am getting this error during cmake ..

CMake Error at 3rdparty/CMakeLists.txt:489 (add_library):
  add_library cannot create ALIAS target "3rdparty::yaml-cpp" because target
  "yaml-cpp" does not already exist.

What is the log file you require?

**Comment by JohnHolmesII** [comment]
Just redirect the cmake and other commands to a file and post it.
Also, why did this issue start as an issue with the compiling, but now it's a CMake issue? What *exactly* is the problem?

**Comment by Blad3forc3** [comment]
Please accept my apologies. I updated to the 460 driver series and somehow lost the libvulkan library. Compiles fine now
