### ISSUE TITLE
 AugustoRPCS3 0.0.13-11483 NPUA80918 GOW Ascension not progress in an area in first stage

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#9516]
RPCS3 0.0.13-11483 NPUA80918 GOW Ascension using patch 1.04.
Exactly when the player character reach the area of screenshot first stage the game continue running with sound, but not is possible move the player and not continue the progress how if is missing any processing.
Perhaps has an bug in game boot executable related with sound because has several lines about sound in message log.
Happen all times using multiple settings (interpreters, recompilers and any othres settings lesse vblank and driver wake up to high number settings).
![screen](https://user-images.githubusercontent.com/21184987/103293760-42a37a80-49cf-11eb-879b-c36c0bc1ea3c.jpg)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5751152/RPCS3.log)

**Comment by AniLeo** [comment]
Known issue on hardware that can't perform well enough, specially looking at the FPS on your counter
> AMD FX(tm)-6300 Six-Core Processor
