### ISSUE TITLE
Guilty Gear Xrd titles giving "unmapped memory"-error

### ISSUE THREAD

**Issue by ZheksOne** [RPCS3/rpcs3#9520]
The Guilty Gear Xrd-titles fail to start anymore on latest revisions on default config with an "unmapped memory"-error. I unfortunately don't know from which revision this started but I'd say a few weeks. The compatibility guide also mentions it as playable. Sometimes it does starts once after reinstalling firmware I believe but then the 2nd time it fails with this error again, even after removing all caches.

Happens on for instance BLUS31588 and NPUB31555
![2020-12-29 23_14_32-rpcs32](https://user-images.githubusercontent.com/76754465/103317890-ea9b6100-4a2c-11eb-9dd9-ee7b8f150ce3.png)

MMy specs:
![2020-12-29 23_21_35-RPCS3 0 0 13-11490-c952e99f Alpha](https://user-images.githubusercontent.com/76754465/103317921-fb4bd700-4a2c-11eb-86d7-178f865332e9.png)

I hope I filled this in correctly, thank you.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5752409/RPCS3.log)

**Comment by AniLeo** [comment]
Missing build that introduced the regression to be labeled as a regression

**Comment by GitArUs** [comment]
Maybe setting "Accurate PPU 128 Reservations" on Debug tab to anything other than "Disabled" will help like in other cases ?

**Comment by ZheksOne** [comment]
> Maybe setting "Accurate PPU 128 Reservations" on Debug tab to anything other than "Disabled" will help like in other cases ?

Thanks for the suggerstion mate but does not work unfortunately.

**Comment by GitArUs** [comment]
One more try - in addition to above set "Driver wake-up Delay" to 600 us on advanced tab (or experiment with different values).

**Comment by ZheksOne** [comment]
> One more try - in addition to above set "Driver wake-up Delay" to 600 us on advanced tab (or experiment with different values).

Nope...thanks

**Comment by Leggo87** [comment]
The memory issue happened in the build 0.0.11-10791-190822c2

In v-0.0.11-10790-d000d648 boots and runs as inteded.

**Comment by Leggo87** [comment]
![unknown](https://user-images.githubusercontent.com/73044361/105082644-a53de280-5a72-11eb-9cd1-1bae6ad0e2a9.png)

**Comment by RainbowCookie32** [comment]
That'd be PR #8663

**Comment by Augusto7743** [comment]
unmapped memory error also happen in others games and look how the emulator in few seconds try to allocate more of 1 GB RAM being that not had need to do it.
Ultimate Marvel VS Capcom 3 selecting an stage with few details and even not moving both players characters randomly the game crash with "unmapped memory" or "trying to allocate 1 GB and was possible only 200 MB" (the values are example because the "trying value" is 5 times the current allocated).
Is how if the emulator try to allocate memory not need because of wrong code.

**Comment by assortedkingdede** [comment]
This issue appears to be present again.

**Comment by ZheksOne** [comment]
I don't think it ever left since I reported this?

**Comment by assortedkingdede** [comment]
I starting to wonder if the issue could be related to timing since the emulator is trying to read unmapped memory which could imply that something could be happening before it is supposed to.

**Comment by CallMeHercules** [comment]
I had the same issue, the problem was solved by simulating a psn network.  You can see the orange warnings where the matchmaking threw an error.
