### ISSUE TITLE
Shader cache loading will fail if corrupted shader is encountered

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#9529]
## Issue:
If a null file (file with entry but no contents) is encountered when loading shaders, it will crash the shader loader. Null files can get created if the emulator crashes when writing shaders to disk, or if the operating system crashes before it has finished storing cached writes (because of f.ex. unstable overclock).

This can occur in at least these two locations:
https://github.com/RPCS3/rpcs3/blob/2b8eb8deb6e86deca9c677c8b300da3762532075/rpcs3/Emu/RSX/rsx_cache.h#L683
https://github.com/RPCS3/rpcs3/blob/2b8eb8deb6e86deca9c677c8b300da3762532075/rpcs3/Emu/RSX/rsx_cache.h#L698

## Solution:
Check if the file is null before trying to read data from it. If the file cannot be read, discard it and continue loading. If the shader is neccessary, it will be compiled again during execution.

**Comment by elad335** [comment]
I think it just  need to **write** the file atomically, looking into.
