### ISSUE TITLE
Regression: Shader compilation failure - 'min' ambiguous function (#9530)

### ISSUE THREAD

**Issue by MineSAT** [RPCS3/rpcs3#9534]
## Details
When entering a planet, the emulator stops responding, before this latest update (11511) this did not happen.
In the previous version 11506 it worked perfectly.
I have tried to erase all the Caches and generate them again in case it was a problem with that but it is not like that...
The configuration that I show in the screenshots I have not changed in any of the versions, it is the same since I played the game.

The error:
E {RSX [0x20e01ec]} RSX: ERROR: 0:228: 'min' : ambiguous best function under implicit type conversion 
ERROR: 0:228: 'assign' : cannot convert from ' temp 4-component vector of float16_t' to ' temp float16_t'
ERROR: 0:228: '' : compilation terminated 
ERROR: 3 compilation errors. No code generated.

E {RSX [0x20e01ec]} RSX: 
F {RSX [0x20e01ec]} SIG: Thread terminated due to fatal error: Failed to compile fragment shader
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKProgramPipeline.cpp:29[:25], in function compile)

####  Logs:
The first log I have taken directly from the emulator and the second from the one generated by the emulator itself when closing.
[log.txt](https://github.com/RPCS3/rpcs3/files/5762013/log.txt)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5762014/RPCS3.log)

#### Screenshots.
![image](https://user-images.githubusercontent.com/626020/103485074-11bead80-4df4-11eb-8b01-ad4b8892db6b.png)
![image](https://user-images.githubusercontent.com/626020/103485025-9826bf80-4df3-11eb-942b-b18ec9d0b2a4.png)
![image](https://user-images.githubusercontent.com/626020/103485137-90b3e600-4df4-11eb-9239-0df06719a701.png)
![image](https://user-images.githubusercontent.com/626020/103485144-98738a80-4df4-11eb-9cda-65eb07aaa50d.png)
![image](https://user-images.githubusercontent.com/626020/103485148-9dd0d500-4df4-11eb-9402-c403f95eddc9.png)
![image](https://user-images.githubusercontent.com/626020/103485159-ae814b00-4df4-11eb-80fc-10c7e3eb36b3.png)
![image](https://user-images.githubusercontent.com/626020/103485162-b4772c00-4df4-11eb-8e2a-f57759fabca4.png)

#### System conf.:
* OS: Windows 10 PRO x64 1909
* CPU: AMD RYZEN THREADRIPPER 2990WX 32 core 3Ghz (4.2Ghz Auto-OC)
* GPU: AMD RX 5700 XT 8GB GDDR6
* Driver version: Tested w/ 20.11.3(stable) and 20.12.1(latest)

**Comment by AniLeo** [comment]
Wrong report, 11511 can't have caused this, #9530 (11509) did

**Comment by MineSAT** [comment]
Thank you for changing it and letting you know what the cause really is, I don't get used to putting the reports right. Sorry for any inconveniences caused :S

**Comment by MineSAT** [comment]
PD: I could not prove due to lack of time that it was (11509). Before updating if everything worked fine and when giving update is when it has failed.

**Comment by kd-11** [comment]
So the game works fine if you delete the shader cache? That PR in question only changed the shader cache behavior.

**Comment by MineSAT** [comment]
It doesn't work even clearing the shader cache.

**Comment by kd-11** [comment]
Then it regressed much further back than that. I know what the issue is though, I'll fix it asap.

**Comment by MineSAT** [comment]
Thanks! @kd-11

**Comment by kd-11** [comment]
Check if https://github.com/RPCS3/rpcs3/pull/9535 fixes the issue. The build should be ready in about 20-30 minutes.

**Comment by MineSAT** [comment]
Ok, ready for try #9535

**Comment by kd-11** [comment]
Download the build from [this link](https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzU3MjQvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitXaW5kb3dz0/content?format=zip) and confirm.

**Comment by MineSAT** [comment]
@kd-11 Works fine! 👍 thanks
![image](https://user-images.githubusercontent.com/626020/103489911-5eb47b00-4e18-11eb-9550-14d7ca3e9c7e.png)
![image](https://user-images.githubusercontent.com/626020/103489918-71c74b00-4e18-11eb-80eb-9172e15861f5.png)
