### ISSUE TITLE
Full screen button put in full screen the wrong window

### ISSUE THREAD

**Issue by nougator** [RPCS3/rpcs3#9537]
## Quick summary
When I press the full screen button it make the windows with settings and etc full screen but not the game window.

## Details
Full screen button doesn't put the right window in full screen.

#### 5. Please provide your system configuration:
* Windows 10
* Intel core i5 6600
* Nvidia GeForce GTX 750
* 460.89

#### Please include.
* Small feature request, adding a key bind for full screen.

**Comment by AniLeo** [comment]
UI fullscreen isn't for Render window but for UI, that part is correct

Key bind to fullscreen is Alt + Enter or double clicking inside the render window

**Comment by nougator** [comment]
Thanks
