### ISSUE TITLE
Double clicks are not responding correctly.

### ISSUE THREAD

**Issue by Buzzbeamer4** [RPCS3/rpcs3#9540]
Dragon Ball HD Collection
ROCS3 Ver: 0.0.13-11442
System: I can provide shortly.
Actions like dashing, charging ki, taunting, and teleport guarding don't seem to work with accuracy. It seems as if the initial press is recognized, but the input of the 2nd input seems to be ignored or not registering. When releasing the button, sometimes if releasing very quickly it will activate, but most times, it seems like a dead response. Any ideas on what to do to fix this?

**Comment by AniLeo** [comment]
Does not follow issue guidelines, needs to be properly remade with these before it's triaged

**Comment by MSuih** [comment]
Closing this since no update has been provided
