### ISSUE TITLE
Enabling Read Color Buffers and Write Color Buffers causes frequent emulator crashes in GT 6 

### ISSUE THREAD

**Issue by PY3AN** [RPCS3/rpcs3#9543]
After enabling Read Color Buffers and Write Color Buffers (RCB + WCB) the emulator starts to crash frequently in the menu with an error: 
F {PPU[0x1000002] Thread (_gcm_intr_thread) [0x00bc0a44]} VM: Access violation reading location 0x0 (unmapped memory) [type=u32]

[GT6_error1.log](https://github.com/RPCS3/rpcs3/files/5762118/GT6_error1.log)

Or 

F {RSX [0x0cc363c]} SIG: Thread terminated due to fatal error: [index buffer] Working buffer not big enough, buffer_length=16777216 allocated=320256 requested=4294967290 guard=65536 largest_pool=6144
(in file D:\a\1\s\rpcs3\Emu\RSX\Common\ring_buffer_helper.h:92[:24], in function alloc)

[GT6_error2.log](https://github.com/RPCS3/rpcs3/files/5762107/GT6_error2.log)

Also after enabling RCB + WCB decreases performance (about 12%)

The issues that remove by Enabling Read Color Buffers and Write Color Buffers:

Mirror Issue (mixed with map) #8546 (Only on game version 1.06 and higher);

https://youtu.be/mScoUWhRS_U

Black screen when rendering 3D graphics (Only on game version 1.06 and higher);

![Black screen in 3D on the track](https://user-images.githubusercontent.com/76910089/103486289-e21c9f00-4e0d-11eb-906f-fd09dd17fe3b.png)

[Black screen in 3D.log](https://github.com/RPCS3/rpcs3/files/5762085/Black.screen.in.3D.log)

System configuration:
* RPCS3 v0.0.14-11509
* OS Windows 10 20H2, 19042.685
* CPU AMD Ryzen 5 3600
* GPU AMD Radeon RX 580 8G
* Memory Crucial Ballistix Sport 16G
* Driver version 2.0.168

**Comment by Megamouse** [comment]
The "Working buffer not big enough" crash is most likely fixed by #10617

**Comment by kd-11** [comment]
Heap corruption crash. Check requested size (it is negative)

**Comment by kd-11** [comment]
Pre-emptively closing. I fixed the invalid heap sizes a long time ago. It was actually expected behavior for a corner case we forgot about.
