### ISSUE TITLE
Uncharted 3 Drakes Deception Game of the Year Edition crash~~

### ISSUE THREAD

**Issue by kyh96403** [RPCS3/rpcs3#9544]
## Quick summary
Uncharted 3 Drakes Deception Game of the Year Edition is crash..
So cannot boot it..

## Details
F {PPU[0x1000000] Thread (main_thread) [0x0063dae0]} SIG: Thread terminated due to fatal error: PPU Trap!
(in file D:\a\1\s\rpcs3\Emu\Cell\PPUThread.cpp:1165[:23], in function ppu_trap) (e=0x0000007e[126])

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5767456/RPCS3.log.gz)

![222](https://user-images.githubusercontent.com/21171837/103593976-a8958200-4f3a-11eb-9288-dcc222cb1903.png)

#### 5. Please provide your system configuration:
* OS: Windows 10 1909/Windows 10 20H2
* CPU i5-6600/i5-1035g7
* GPU nVidia 1050/intel iris
* Driver version
* etc.

#### Please include.
Desktop(i5-6600) and GPD Win Max(i5-1035g7) same crash...
So that is not depend PC...
Thanks^^

**Comment by kyh96403** [comment]
Sorry..
I use invalid rom..
If use valid rom, no problem at all~~

**Comment by JavedSKhan** [comment]
I'm having the same problem. Where'd you get a valid rom from? DM me please
