### ISSUE TITLE
Error F {PPU[0x1000000] Thread (main_thread) [0x005b80c4]} VM: Access violation writing location 0x3ba00040 (unmapped memory) [type=u32] When trying to start LBP2

### ISSUE THREAD

**Issue by relt-1** [RPCS3/rpcs3#9546]
## Quick summary
I cannot successfully boot LBP2 due to a access violation

## Details
When i try boot LBP2 i get past the warnings and the intro normally, but after that, it freezes
 and
F {PPU[0x1000000] Thread (main_thread) [0x005b80c4]} VM: Access violation writing location 0x3ba00040 (unmapped memory) [type=u32]
appears in console. If i try to unpause the game, the error keeps happening. This doesn't happen always, one time i actually did manage to get into the pod, but after a little while it did the same thing again

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5769470/RPCS3.log)

#### 3. Please attach screenshots of your problem.

![image](https://user-images.githubusercontent.com/60782515/103634142-f87a4600-4f46-11eb-9bb4-4c07d33d0d89.png)

#### 5. Please provide your system configuration:
OS: Windows 10 Build 20279
CPU: Intel Core i5-4670
GPU: AMD Radeon R7 240
Driver version: 2.0.168

**Comment by MSuih** [comment]
Wrong settings and issues with the game dump. Ask for support in Discord, do not open a Github issue.
