### ISSUE TITLE
rpcs3 fails to build (GCC-11)

### ISSUE THREAD

**Issue by hedmo** [RPCS3/rpcs3#9557]
## Quick summary
Please briefly describe what is not working correctly.

rpcs3 fails to build 

## Details

asmjit_apibegin.h:102:15: error: expected unqualified-id before ‘const’
  102 |   __VA_ARGS__(const __VA_ARGS__& other) = delete;            \
                       |               ^~~~~

[build.log](https://github.com/RPCS3/rpcs3/files/5776905/build.log)

**Comment by Nekotekina** [comment]
Maybe use newer gcc or clang?

**Comment by hedmo** [comment]
> Maybe use newer gcc or clang?

@Nekotekina i cannot use use a newer gcc as i am using GCC-11 :) . i am reporting this issue because you are going to face this problem sooner or later if you dont just stick to clang only. i did try to compile asmjit only and it compiled fine .

**Comment by Nekotekina** [comment]
Got it, maybe updating asmjit will help, I'll take a look.

**Comment by hedmo** [comment]
> Got it, maybe updating asmjit will help, I'll take a look.

i will double check the version that was compiled from my side and report back

**Comment by hedmo** [comment]
i compiled asmjit from https://github.com/asmjit/asmjit right now and it worked . i will try to build spcs3
with commit 70e80b18a5cc05d566e6c90dde200472c9325113 from https://github.com/asmjit/asmjit
to see what is happend. if it fails i give you the build.log. do you want clean flags in the log?.

**Comment by Nekotekina** [comment]
Or it's just a gcc bug, I'm not an expert to tell. But I think I understood the pattern. Usually, inside the template classes, to name current class we don't type `Vector<N>`, we just type `Vector`. But asmjit does in several places, in certain macro expansios.
@kobalicek sorry to bother, maybe it's a bug from asmjit side? Is it worth updating from old asmjit?

**Comment by Nekotekina** [comment]
@hedmo you probably should try to compile in C++20 mode

**Comment by hedmo** [comment]
i provide the build log that i compiled  from git . the odd thing is when it is compiled it in rpcs3 it will fail .
[buildasmjit.log](https://github.com/RPCS3/rpcs3/files/5788327/buildasmjit.log)

**Comment by hedmo** [comment]
compiling ATM . seems to work :)

**Comment by hedmo** [comment]
it went allot longer but failed again :( 
[nextup.log](https://github.com/RPCS3/rpcs3/files/5788651/nextup.log)

**Comment by Nekotekina** [comment]
Yes, the same pattern. I can make a workaround for LLVM, just need to wait for asmjit maintainer.

**Comment by Nekotekina** [comment]
I guess you can try latest master again

**Comment by hedmo** [comment]
still fails... but you are almost there : [1891/1997] . next is rpcs3/Emu/RSX/Overlays/overlay_utils.h.

thank you for holding out. if i did understand what to remove i would help you.
[next.log](https://github.com/RPCS3/rpcs3/files/5790557/next.log)

**Comment by hedmo** [comment]
as this is quite time killing for us .. can  you tell me what to be removed in this snip : 

template<typename T>
struct vector3_base : public position3_base<T>
{
	using position3_base<T>::position3_base;

	vector3_base<T>(T x, T y, T z)
	{
		this->x = x;
		this->y = y;
		this->z = z;
	}

	vector3_base<T>(const position3_base<T>& other)
	{
		this->x = other.x;
		this->y = other.y;
		this->z = other.z;
	}

	T dot(const vector3_base<T>& rhs) const
	{
		return (this->x * rhs.x) + (this->y * rhs.y) + (this->z * rhs.z);
	}

	T distance(const vector3_base<T>& rhs) const
	{
		const vector3_base<T> d = *this - rhs;
		return d.dot(d);
	}
};

**Comment by Nekotekina** [comment]
I believe I'll fix, give me a sec

**Comment by hedmo** [comment]
> I believe I'll fix, give me a sec

:+1:

**Comment by Nekotekina** [comment]
You can try the PR, if there are more errors post new logs.

**Comment by hedmo** [comment]
[build.log](https://github.com/RPCS3/rpcs3/files/5790819/build.log)

**Comment by Nekotekina** [comment]
This is master, you need to apply patch from the pull request.

**Comment by hedmo** [comment]
sorry ... i was building the old one.

**Comment by hedmo** [comment]
> This is master, you need to apply patch from the pull request.

i am just using the commits you have done...

**Comment by hedmo** [comment]
as i am using your releases and they do not provide the submodules i have to make a big ass soup
to follow your releases. this is what i am working with : 

file:///home/hedmo/Documents/rpcs3-0.0.14_p20210109.txt

**Comment by Nekotekina** [comment]
Just 1 commit to cherry pick on current master: https://github.com/RPCS3/rpcs3/pull/9574/commits/9d74d42f2a8f7509a4a9000ea472475f71c059fa

**Comment by hedmo** [comment]
ATM it errors out with something that is not from rpcs3 but qt : 

[qterror.log](https://github.com/RPCS3/rpcs3/files/5791026/qterror.log)

**Comment by kobalicek** [comment]
Does it make sense trying to fix compiling under a compiler, which hasn't been released yet? What if it's a bug that will be fixed making all the fixes unnecessary?

**Comment by Nekotekina** [comment]
Waiting for compiler fix could take longer than quickly workaround oddities...
But now seeing it failing in Qt code I don't know what to do.

**Comment by hedmo** [comment]
> Waiting for compiler fix could take longer than quickly workaround oddities...
> But now seeing it failing in Qt code I don't know what to do.

@Nekotekina  that is my problem . i will fix it an report back if i got more rpcs3 error.

**Comment by kobalicek** [comment]
I think you should report that to GCC bugzilla and verify it's how it's supposed to be or whether it's a compiler bug. I'm not really convinced the asmjit patch was necessary. There is no other compiler (even regular GCC release) that would have problem with the code.

**Comment by Nekotekina** [comment]
Yes, I think it only happens in C++20 mode (or gnu equivalent).

**Comment by hedmo** [comment]
> I think you should report that to GCC bugzilla and verify it's how it's supposed to be or whether it's a compiler bug. I'm not really convinced the asmjit patch was necessary. There is no other compiler (even regular GCC release) that would have problem with the code.

ATM this is the only package that fails on me . But others i have patched to and manage get them compile just fine . I am updating and rebuilding my systems every month with the new GCC-11 commits . If it was a GCC fault it often falls with ICE . I think this is the new GCC standard now . I dont know about your asmjit but i can compile asmjit from https://github.com/asmjit/asmjit without problems . ATM i have a bug at QT for them to check out and hoping to get some answers from them  to.

**Comment by kobalicek** [comment]
You may be interested in this: https://gcc.gnu.org/pipermail/gcc/2021-January/234703.html

**Comment by hedmo** [comment]
@Nekotekina 
the build error from qt  has been fixed. 

[log.txt](https://github.com/RPCS3/rpcs3/files/6159250/log.txt)

**Comment by Nekotekina** [comment]
Looks like another gcc bug but I can make a workaround.

**Comment by hedmo** [comment]
are you going to add it to 0.0.15?. do you have the other ones there to or just an other commit for me to use ?.

**Comment by Nekotekina** [comment]
Try latest master

**Comment by hedmo** [comment]
@Nekotekina 

thanks . i can confirm it is done and installed now .
