### ISSUE TITLE
Graphical Issue in the race setup menu at 1080p in Gran Turismo 5 Prologue [NPUA80075]

### ISSUE THREAD

**Issue by PY3AN** [RPCS3/rpcs3#9559]
Graphical Issue in the race setup menu at 1080p in Gran Turismo 5 Prologue spec II [NPUA80075]

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5777051/RPCS3.log.gz)

![Graphical_Issue_at_1080p_in_GT5P](https://user-images.githubusercontent.com/76910089/103797014-f4d6e400-5058-11eb-8069-4ab7003a3d38.png)

System configuration:

RPCS3 v0.0.14-11518
Firmware version: 4.86
OS Windows 10 20H2, 19042.685
CPU AMD Ryzen 5 3600
GPU AMD Radeon RX 580 8G
Memory Crucial Ballistix Sport 16G
Driver version 2.0.168

**Comment by xddxd** [comment]
Looks like a duplicate of #8297.

**Comment by PY3AN** [comment]
Conducted a test, in GT5P Strict rendering mode also solved the problem. Closing Issue.
