### ISSUE TITLE
Microbot [NPUB30336] Unplayable+Crash

### ISSUE THREAD

**Issue by MetallicBox** [RPCS3/rpcs3#9565]
It boots up but then it frozes up without even showing anything (it stays black) then the game closes and rpcs3 crashes.
System
CPU: (Dual) x5660
Ram: 8gb ddr3
GPU: gtx 970 4gb
Windows 10 and latest drivers installed.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5784011/RPCS3.log)

**Comment by RainbowCookie32** [comment]
Issue isn't following the template for bug reports, and the log is empty.

Please fix your log and properly follow the templates when opening issues.

**Comment by AniLeo** [comment]
Driver is not the latest version, that's why you use a version on report and not "latest"

Log file is also empty
