### ISSUE TITLE
poopoo

### ISSUE THREAD

**Issue by denis-hash** [RPCS3/rpcs3#9566]
## Quick summary
poopo kinda brown doe
## Details

you see, when poop you pooped out, it appears brown
#### 1. Please attach RPCS3's log.
poop kinda big
#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
i think my piss is also an issue
#### 3. Please attach screenshots of your problem.
google poop mate kinda ez
#### 5. Please provide your system configuration:
* OS: poopo 10
* CPU: ipoop
* GPU: rtpoopandpiss
* Driver version: A̷̛̙̲̬̫͖̹̱̘̪̿̄͌̈́̎̏̚͠n̶̨̯͉͙͚̭͔̭̰̯̖̹̙͍̬̿͋̐̄ ̷̝͚̗̹͍̖̋̎͛̑̔̅͐̃͑́̈́̃̽͝͠ͅę̶̨̗͚͍̝͔͉̞̠̂̿̀͜ỷ̸̪̟͂̃̀̾͌͑̋̓̊̎̅̕e̶͈̯͙̯̲̠̯̎l̸̛͎͍̜̹̻̫̥͌̔̾̅̈́̂́̃ȩ̵̢̤̘͚̝̠̹̪̜̈́s̶͓̙̙͇̈́̈́͆͜s̵̫̳̠̫͙͍̠̮̪̘̳̆̀̔̔̎͊̎ͅ ̸̧̧̼̙̙͕̮͔̼̞̻͊a̷̞͗̓̒̑̊̓̆͑͘̕̕͠͝b̷͇̏̊̕o̷͖̪̫̅̔̑m̶̛̹̟͕͚̙̲͕̾̂̉́̆͐i̸̪̘̠͚͍̍̑́n̵̨̛͈̓̍̐̃͆̃̽̕͘a̸̧̡̛̹̙̞̙̱̝̼̯͕̫̫̓̓̆̄̓̈́̀̄͌͊͐̔̋͝ẗ̵̨̘̙̠̦̱̪̦̻͕͎̺̗͓́̂͐͂͑́i̸̢̦͓̱̣͎̩̜͕̻͋̿̊̓͊̽̽͑o̵̙̊͂̂̽̋̈́̀̅̔͗̄̚̚͝n̵͎̯͛̓̓̔̉͆͑̾ ̷̜̦͖̍̓͊͊͗̓́͘ẇ̸̱̳̭̼̪̟̱̦̘̳̉̆͊̀̆̚͠i̸͖̪̪̼͙̰̩̤͈̝̻͈̮̍͛̆͑t̶̻͚̯͕͔̳̜̀̅̔̐͊̄̕͜h̴̯̭͉͓̪͈̥̻͕̞̪̩̏̄̏ ̵͚̗͇͎̝͓̖͉̩̰̱̹̩̤̈́̿͒͒̉́̾̌̊͛̈́͌̔͘s̵͖̟̲̝͐̑ë̵̗̰͒͑́̊͘͘͝v̵̢̢̡̯̭̯̱͖̻̭̦͙͊͂̊́̐̅͊̆͆̀͘͘ę̶̢̫̣̬͕͍͇͎̝͔͌͋̂́̆͐̉̂̈́̃̑͋̚͝͝n̶̛̦͇͑͆̽̿͊̃͒̒͊͜͝͠ ̵̨̩̖̠̣̠̙͎̰͙̹́̋̐́͋͛́̆͗͆͋̈́̍͆̃͜m̸̖̱̗̹̫͚̹̱͛̇̈́͐͒̽̍̕̕o̶͚̘̰̼͖̊ư̷̩͍͉̳͍͖̟͍̘̣̫̩̈́̓̎̓̏̎͊̀̽̀̑t̵̛̻̦̙̙̣̲͉̼͗̋̍̀̂̿̒̋̆͐̊́͜͜͠ͅḧ̵̯̞̥̱̦͎̖̝͉̩̱̗̑̉̾̑́͒̋͒ṣ̴̡͈̹̙̼͙͔͈͍̗̾̍̃̿̀̒̄̊.̷̢̯̙͉͎̤͖͙̜̙̖͛̈́͜ͅ* etc.

#### Please include.
kinky

**Comment by clienthax** [comment]
Fuck off.
