### ISSUE TITLE
errors in Hatsune Miku Project DIVA F (BLUS31319)

### ISSUE THREAD

**Issue by Meiko-Chan** [RPCS3/rpcs3#9572]
Hi 
Since an update for rpcs3, there have been bugs in the project diva game, such as the wall appearing and disappearing, sometimes a previous scenario flashes and sometimes there is lag in scene changes

which in old versions of the emulator did not happen, still not fixed with each update and hopefully solve it thanks.

my pc specifications: 

Procesador Intel Core i5-9300H 4 x 2.4 - 4.1 GHz, Coffee Lake-H
Adaptador gráfico NVIDIA GeForce GTX 1650 Mobile - 4096 MB, GDDR5 ver: 460.89
Memoría 8192 MB 

ps: my english is not that good so I took the translator and there are about 2 images of how those 2 pvs should look

![FPS_ 29 99 _ Vulkan _ 0 0 14-11519 _ Hatsune Miku_ Project DIVA F  BLUS31319  08_01_2021 20_21_02](https://user-images.githubusercontent.com/77177086/104074666-73658a00-51ef-11eb-8ab1-50758c9e277f.png)
![FPS_ 30 00 _ Vulkan _ 0 0 14-11519 _ Hatsune Miku_ Project DIVA F  BLUS31319  08_01_2021 20_27_03](https://user-images.githubusercontent.com/77177086/104074848-ef5fd200-51ef-11eb-88f2-a4529e3d3b65.png)

https://user-images.githubusercontent.com/77177086/104074978-4fef0f00-51f0-11eb-82c9-52a3d3e9c849.mp4

![Captura de pantalla 2021-01-08 205305](https://user-images.githubusercontent.com/77177086/104076110-ca6d5e00-51f3-11eb-9a15-3935a1babcfa.png)
![Captura de pantalla 2021-01-08 205446](https://user-images.githubusercontent.com/77177086/104076115-d22d0280-51f3-11eb-8dcf-e7d71d72d0b4.png)

**Comment by AniLeo** [comment]
Missing everything required by the guidelines

**Comment by kd-11** [comment]
Needs rpcs3.log, likely another unknown GPU.

**Comment by MsDarkLow** [comment]
I only tested the Room scenario (E, A sou?) and the same occurs with i7-8700k and RTX 3080
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5792608/RPCS3.log.gz)

For some reason the wall on the right flickers
![e a sou](https://user-images.githubusercontent.com/9060436/104123730-c735b780-5344-11eb-96aa-71e14c754053.gif)

**Comment by kd-11** [comment]
I suppose we have to find the regression trigger then. Looks to be nvidia-only so far.

**Comment by kd-11** [comment]
I can confirm this issue does not happen with RADV

**Comment by kd-11** [comment]
Is this still an issue? Another nvidia-only flicker bug was fixed recently.

**Comment by MsDarkLow** [comment]
The issue still occurs for me.

**Comment by Meiko-Chan** [comment]
> The issue still occurs for me.

Yes, it still happens to me too

**Comment by kd-11** [comment]
Still need to know when it broke guys.

**Comment by MsDarkLow** [comment]
The PR that broke this was #8741
Previous working Build (8852) - [RPCS3 10844.log.gz](https://github.com/RPCS3/rpcs3/files/6291707/RPCS3.10844.log.gz)
PR that broke it (8741) - [RPCS3 10846.log.gz](https://github.com/RPCS3/rpcs3/files/6291708/RPCS3.10846.log.gz)
Current Master - [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6291715/RPCS3.log.gz)

**Comment by kd-11** [comment]
I'll try and re-enable hardware clip control. It was implemented at some point but those commits are lost for a long time now.
This is likely just some rounding error specific to NVIDIA's fp implementation.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/10111

**Comment by MsDarkLow** [comment]
Sweet Devil heart part and Hm ah yes bedroom part are indeed fixed.

But the two kids with the instruments where they show up for a single frame isn't. I tested all the way back to 0.0.7 and the issue seems present there so I guess it's just something that has been consistent the whole time, both opengl and vulkan.
I'm not even sure if this kind of bug shows anywhere else in the game. No setting seems to fix it.


![STOPPOSTINGANIMEINOFFTOPIC](https://user-images.githubusercontent.com/9060436/114620218-44a1f880-9ca3-11eb-9a1e-7f35b2cc7cd8.jpg)

https://user-images.githubusercontent.com/9060436/114620208-42d83500-9ca3-11eb-8109-d768e40a79a9.mp4

https://user-images.githubusercontent.com/9060436/114620226-466bbc00-9ca3-11eb-88d8-8523a2d4afba.mp4
