### ISSUE TITLE
Persona five boot issue

### ISSUE THREAD

**Issue by 3eech** [RPCS3/rpcs3#9575]
![image](https://user-images.githubusercontent.com/77198266/104092902-feaf5000-52c1-11eb-9291-6c1b9d11de4b.png)
Im getting this issue and i dont know why while trying to run persona 5
specs: 2060 latest drivers
ryzen 5 3600
16 gigs 3200 ram

**Comment by elad335** [comment]
Install firmware! it says in the boot error you should have read.
