### ISSUE TITLE
NCAA Character Creation

### ISSUE THREAD

**Issue by mattbcraft** [RPCS3/rpcs3#9583]
## Quick summary
Every time I enter character creation for Road to Glory in NCAA 14 I get the same error message and the emulator freezes entirely.

## Details

The game freezes at random times when entering the create a player mode in Road to Glory. It allows you to play existing roster players but does not allow you to be a highschool student. I have gotten as far as equipment customization in this mode but it is most common for the emulator to freeze as soon as you enter the mode or as you are typing a name.

#### Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5793482/RPCS3.log)

#### Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/64975010/104138397-0a9e1f00-5361-11eb-94f4-f489ab7d4f4e.png)

#### Please provide comparison with real PS3.
I have played NCAA 14 on my friends PS3 and it has let us create each other as characters without freezing

#### Please provide your system configuration:
* OS Windows 10
* CPU AMD Ryzen 5 3600X 6-Core Processor
* GPU NVIDIA GeForce RTX 2060 SUPER
* Driver version 27.21.14.5206
* 16 GB

**Comment by AniLeo** [comment]
Settings differing from default are being used, needs a log file with every setting on default

**Comment by mattbcraft** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5793508/RPCS3.log)
This was a log with normal settings ... I've used normal settings before and had the same issue however this time I was able to get through the creation completely. Is there any apparent difference in the logs that I can use for my custom configuration?

**Comment by AniLeo** [comment]
GPU driver is still not updated - upload a new log after updating driver and reproducing the crash, the log you uploaded doesn't have any crash

**Comment by mattbcraft** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5793538/RPCS3.log)
does this provide what you need?

**Comment by AniLeo** [comment]
Still shows out of date NVIDIA driver being used

**Comment by mattbcraft** [comment]
Alright I downloaded the game ready drivers and studio drivers from nvidia site for my RTX 2060 Super is this what I need to update?

**Comment by mattbcraft** [comment]
And my next uploaded log will have updated GPU with default settings or my custom config settings?

**Comment by AniLeo** [comment]
Default settings, updated game drivers. Studio drivers are not for gaming hence they're not even tested, let alone supported.

If you are using DLC, ensure you have dumped their respective RAP licenses.

**Comment by mattbcraft** [comment]
Okay thanks. The default settings and new drivers work and the game is now able to progress past character creation. I will still upload my log and some screenshots of the performance of the game now in case despite no crash.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5793565/RPCS3.log)

[NCAA 14 Screen Shots.zip](https://github.com/RPCS3/rpcs3/files/5793568/NCAA.14.Screen.Shots.zip)
