### ISSUE TITLE
Games crashing when loading save data (Use Native User Interface)

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#9584]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5793781/RPCS3.log)
CPU FX-6300 Ubuntu 20.04 64 4 GB GT 640
Using 0.0.14-11534 and current 

Fist of the North Star: Ken’s Rage 2 BLES01801
First game run works fine almost 60 FPS, but when starting an second time crash the emulator. Is displayed an screen to select save game using "Use Native User Interface" and when selected the game save freeze the emulator and in few seconds crash.

Some versions after 0.0.14-11574 the problems was fixed for that game.
Now in 0.0.14-11626 is crashing with Ratchet & Clank Future Quest For Booty NPUA80145
Perhaps more games crash when using User Native User Interface for load game save data.

In configuration emulator disabling Use Native User Interface "fix" the problem.

Here the log for Fist of the North Star: Ken’s Rage 2 BLES01801 ... last lines message about trouphy

·W 0:00:39.220285 {PPU[0x100000a] Thread (CThread) [HLE:0x00a46524, LR:0x004276a8]} sceNpTrophy: sceNpTrophyInit(pool=*0x0, poolSize=0x0, containerId=0xffffffff, options=0x0)
·W 0:00:39.220330 {PPU[0x100000a] Thread (CThread) [HLE:0x00a4657c, LR:0x00427768]} sceNpTrophy: sceNpTrophyCreateContext(context=*0x32f9e238, commId=*0x69a351, commSign=*0x69a35d, options=0x0)
·! 0:00:39.220339 {PPU[0x100000a] Thread (CThread) [HLE:0x00a4657c, LR:0x00427768]} sceNpTrophy: sceNpTrophyCreateContext(): commSign = { 0xB9, 0xDD, 0xE1, 0x3B, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x18, 0x64, 0xD6, 0xCE, 0x0C, 0xE3, 0xC5, 0x36, 0x7B, 0x9D, 0x8B, 0xD4, 0x86, 0xEA, 0x06, 0x0C, 0x72, 0x08, 0x07, 0x67, 0xBB, 0xE1, 0x62, 0xCA, 0x76, 0x3F, 0x9E, 0x75, 0xBD, 0x63, 0xB2, 0x01, 0x5D, 0x6E, 0x92, 0x80, 0xFC, 0x37, 0x61, 0xB1, 0x4C, 0x22, 0xBE, 0xAC, 0x12, 0xDC, 0x0E, 0x1E, 0x41, 0x32, 0x53, 0xBD, 0xF0, 0x8C, 0x13, 0xC7, 0xE4, 0xE7, 0x91, 0xEA, 0xB7, 0xBC, 0x02, 0x43, 0x89, 0x9A, 0x42, 0x9D, 0x96, 0xF0, 0x5F, 0x13, 0x76, 0x1F, 0x7E, 0x16, 0x35, 0x3C, 0x3C, 0x32, 0x3F, 0xD9, 0xF5, 0x9E, 0x10, 0x9C, 0x2B, 0x28, 0x94, 0x2D, 0x91, 0x5D, 0xEF, 0x78, 0x4D, 0x54, 0x7E, 0x65, 0xD8, 0x87, 0x18, 0x3A, 0x27, 0x19, 0xA2, 0xBC, 0x85, 0x7D, 0x58, 0xE3, 0x02, 0x9B, 0xC7, 0x1C, 0x99, 0x3D, 0x5B, 0x9C, 0xDD, 0x36, 0xA9, 0xF1, 0xAE, 0xFC, 0xF9, 0xE2, 0xB6, 0x0A, 0x6C, 0xD3, 0x7D, 0xDC, 0xB3, 0xD5, 0xE1, 0xB6, 0x22, 0x82, 0x5D, 0xDB, 0x27, 0xC5, 0x3F, 0xF9, 0x58, 0x85, 0x17, 0xB4 }
·W 0:00:39.220355 {PPU[0x100000a] Thread (CThread) [HLE:0x00a4657c, LR:0x00427768]} sceNpTrophy: sceNpTrophyCreateContext(): data='NPWR04298' term='

**Comment by Augusto7743** [comment]
Removing the trophy folder the start and works fine, but in next start crash again.
Possibly related with trophy.

**Comment by Augusto7743** [comment]
in configuration emulator disabling Use Native User Interface "fix" the problem and not need remove trophy folder.

**Comment by Augusto7743** [comment]
The issue was fixed in 0.0.14-11574.
Please not close ... perhaps the bug return because current version is having strange issues

**Comment by UbiSergei** [comment]
Ken' Can't Do Hadouken

Apply A++, -67byte

**Comment by Augusto7743** [comment]
You are saying that player character not does an attack move in RPCS3 ?
I remember an "hadouken" move on PS3 being the the one of last special attacks.

**Comment by Augusto7743** [comment]
That reply above not related exactly with the bug in Use Native User Interface.

**Comment by kd-11** [comment]
Worth testing with https://github.com/RPCS3/rpcs3/pull/11491

**Comment by Megamouse** [comment]
Assuming this is fixed.
Noone else has this issue, including me.

**Comment by Augusto7743** [comment]
Using several versions since 06-2021 and not happening that bug.
Probably was fixed.
