### ISSUE TITLE
For some games "sys_fs_open' failed"

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#9585]
CPU FX-6300 Ubuntu 20.04 64 4 GB GT 640
Using 0.0.14-11534

Several games in message log display lines how if the emulator is trying to load files, but the game not has the files.
When happen an update to an game that message line is displayed more yet.
Games are installed correctly.
In few times games crash being the last lines exaclty related with "sys_fs_open' failed".

The lines are
·E 0:00:26.146300 {PPU[0x1000000] Thread (main_thread) [0x01082090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30107/USRDIR/PS3_CommandLine.txt” [1]
·E 0:00:26.146310 {PPU[0x1000000] Thread (main_thread) [0x00fb54ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
·! 0:00:26.146321 {PPU[0x1000000] Thread (main_thread) [0x01080ec0]} sys_fs: sys_fs_fcntl(0xc0000006): /dev_hdd0
·W 0:00:26.146325 {PPU[0x1000000] Thread (main_thread) [0x01081ee4]} sys_fs: sys_fs_stat(path=“/dev_hdd0/game/NPUB30107/USRDIR/TMNT_PS3.bf”, sb=*0xd00802a8)
·E 0:00:26.146347 {PPU[0x1000000] Thread (main_thread) [0x01081ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30107/USRDIR/TMNT_PS3.bf” [1]
·! 0:00:26.146355 {PPU[0x1000000] Thread (main_thread) [0x01080ec0]} sys_fs: sys_fs_fcntl(0xc0000006): /dev_hdd0
·W 0:00:26.146359 {PPU[0x1000000] Thread (main_thread) [0x01081ee4]} sys_fs: sys_fs_stat(path=“/dev_hdd0/game/NPUB30107/USRDIR/TMNT_PS3.bf.EDAT”, sb=*0xd00802a8)
·E 0:00:26.146379 {PPU[0x1000000] Thread (main_thread) [0x01081ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30107/USRDIR/TMNT_PS3.bf.EDAT” [1]

Logs are for Teenage Mutant Ninja Turtles: Turtles in Time Re-Shelled and GOW Ascension
[RPCS3 Teenage Mutant Ninja Turtles: Turtles in Time Re-Shelled.log](https://github.com/RPCS3/rpcs3/files/5793790/RPCS3.Teenage.Mutant.Ninja.Turtles.Turtles.in.Time.Re-Shelled.log)
[RPCS3 GOW Ascension.log](https://github.com/RPCS3/rpcs3/files/5793791/RPCS3.GOW.Ascension.log)

**Comment by RainbowCookie32** [comment]
A lot of games just check whether or not the files exist by trying to open them. It's not an issue most of the times
