### ISSUE TITLE
several repeated process in cellVoice thread without end

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#9587]
In some games in message log is displayed for cellvoice thread processing, but has some times is created how SPU cache for cellvoice where repeated times the time cellvoice process in same memory address at extreme without end. Allways the next message logs lines will be about the same cellvoice in same memory address.
When restarting the game all process is done again. Is how not is being cached and thus use very much CPU resources.
Have games that process is done, but not is repeated several times instead few lines and after others process being RSX or others SPU cache tasks thus is only wait for few seconds and CPU resources are free and the game run in good speed again.

Other strange detail is that in message log has the cellvoice threads being done without end with several lines, but not is in log file.
the log is about GOW ascension, but has several others games also having that result.
For machines using "old CPUs" that issue crash game some times or less gameplay speed.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5798416/RPCS3.log)

I will post soon the message logs that not are in log file

**Comment by AniLeo** [comment]
No issue, just standard TODO being called by the game in a loop
