### ISSUE TITLE
Naughty Dog games Shadow map issue

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#9588]
In Uncharted 2,3 and The last of Us there's a second type of shadow maps that is look broken.
here's the examples:
Uncharted 3:
![39](https://user-images.githubusercontent.com/7060586/104239609-d7948200-546b-11eb-8443-926a6de3595e.jpg)

The Last of Us:
![40](https://user-images.githubusercontent.com/7060586/104239636-e4b17100-546b-11eb-9e41-5a725c223d99.jpg)
![41](https://user-images.githubusercontent.com/7060586/104239648-e9762500-546b-11eb-8565-9ff11407149b.jpg)

During research this issue, by using patch, I was able to separate this thing from normal working shadow maps and disable it, while analyzing elf in Ghidra i've found "DrawCubemapShadowBuffer" string in the function which seems to manages this broken effect, not sure if it's connected, hope it'll help.

RSX Captures:
Uncharted 3:
https://mega.nz/file/eJInWabT#v6MovbtaUP_hWm5w37vkNZ3SxAc_XxKG-XglNFS5sPk
The Last of Us:
https://mega.nz/file/uFRlwArL#lITxRu-Hdu4OxBULW_4o91JqMMYXwokcYQTHxVdNOyQ

**Comment by kd-11** [comment]
While I can't personally run this game, this looks like typical RCB/RDB issue. Try different combinations of all the buffer options and no patches.

**Comment by Xcedf** [comment]
As far as i remember this thing was never working fine, evem when i played this game with no patches long ago, but i'll try

**Comment by Xcedf** [comment]
No patches and any RCB/RDB combination looks this way
![image](https://user-images.githubusercontent.com/7060586/104244738-234b2980-5474-11eb-81b3-e240b498ce8b.png)

**Comment by kd-11** [comment]
Try with https://github.com/RPCS3/rpcs3/pull/9631

**Comment by UbiSergei** [comment]
They Use 2047x cube maps Insteaad Of POWER OFT WOO!!

Use #define ps model 3.0

**Comment by Linear524** [comment]
Hi Xcedf and KD-11 !
I'm testing Naughty Dog games with every new revision of RPCS3 and this particular issue is a long standing bug in shadow map function translation. Looks like some lower vertices of shadow map body is not clipped properly and overall result is ether missing clipped vertices (clipped to dynamic object like player's body) , or this vertices is blown away like SPS syndrome... 
![screenshot-2021_05_19_23_05_49](https://user-images.githubusercontent.com/84367301/119081609-2788e400-ba1e-11eb-8aa3-978f4226f27e.jpg)
![screenshot-2021_05_19_23_10_08](https://user-images.githubusercontent.com/84367301/119081611-2952a780-ba1e-11eb-90e8-132a3dcc9688.jpg)
![screenshot-2021_05_18_20_46_57](https://user-images.githubusercontent.com/84367301/119081612-29eb3e00-ba1e-11eb-9d75-4f45718fc11a.jpg)
![screenshot-2021_05_18_20_51_38](https://user-images.githubusercontent.com/84367301/119081614-2a83d480-ba1e-11eb-9212-5bd17106cc3c.jpg)
![screenshot-2021_05_18_21_44_37](https://user-images.githubusercontent.com/84367301/119081615-2bb50180-ba1e-11eb-9f85-7e70f3d5ce26.jpg)
![screenshot-2021_05_18_21_44_49](https://user-images.githubusercontent.com/84367301/119081616-2c4d9800-ba1e-11eb-9035-09562e8d75ae.jpg)
![screenshot-2021_05_18_21_45_14](https://user-images.githubusercontent.com/84367301/119081617-2d7ec500-ba1e-11eb-8362-7d23ebf58e4d.jpg)

**Comment by Linear524** [comment]
Notice how unusual this bug behaves on Joel's body - it is always missing lower parts of body and arms from the spotlights or omni-based lights. 
I think this issue can be fixed without serious changes in GPU-side emulation, just some little tweaks to shadow maps are needed, or maybe vertex calculation function rewrite... But all this magic can be done only by KD-11, so if you're reading this - help us please :) Resolving this issue will help all NaughtyDog games to jump closer into playable state (^_^)

**Comment by Linear524** [comment]
P.S. - WCB and RDB are still required together to fix some missing lighting effects with dynamic sprites and this combination also brings back beautiful velocity blur effects ! (I don't use depth buffer patches because they breaks velocity blur effects)

**Comment by Xcedf** [comment]
@Linear524 I moddified my Motion Blur patch not so long ago, now it disables Motion Blur only (1 of 3 effects) which is broken and interferes with depth buffer viewport, velocity blur effects were always rendered properly on RPCS3 so you can use Depth Buffer patch - which is actually SPU lightning patch without loosing velocity blur.

**Comment by Linear524** [comment]
> 
> 
> @Linear524 I moddified my Motion Blur patch not so long ago, now it disables Motion Blur only (1 of 3 effects) which is broken and interferes with depth buffer viewport, velocity blur effects were always rendered properly on RPCS3 so you can use Depth Buffer patch - which is actually SPU lightning patch without loosing velocity blur.

Thanks, I'll try that )
But there is more important issue - is there any way to make MLAA work correctly in TLoU ? Current implementation doesn't work at all, but MLAA works fine in Uncharted series and all other titles I've tested (GoW3, GoWA, Killzone2,3, etc)
The reason I asking this - original image result with MLAA+720p looks way better than 4K scaled image without MLAA... A lot of distant pixels are not antialiased and overall picture looks too sharp and unnatural...

**Comment by Xcedf** [comment]
@Linear524 MLAA is being processed on SPU, and it doesn't work correctly anywhere on RPCS3 including Uncharteds, GoWs, Killzones, etc, but since MLAA is a shader, perhaps using ReShade is a solution for now.

**Comment by Linear524** [comment]
> 
> 
> @Linear524 MLAA is being processed on SPU, and it doesn't work correctly anywhere on RPCS3 including Uncharteds, GoWs, Killzones, etc, but since MLAA is a shader, perhaps using ReShade is a solution for now.

Nope, it works ! :) I mean MLAA works on many titles via RPCS3, I've tested it with more than 15 games by myself. I know that it is Shader antialiasing - Morphological AA, running on CPUs, and it was clever step by game developers to use SPU power to run MLAA... The thing is - something broken in MLAA instruction on RPCS3 when TLoU is being launched, while other games emulates this thing correctly. Here is some screens with working MLAA on RPCS3:
![screenshot-2021_05_18_19_03_31](https://user-images.githubusercontent.com/84367301/120441278-37051700-c3a6-11eb-9d20-728ca241d49b.jpg)
![screenshot-2021_05_18_19_13_35](https://user-images.githubusercontent.com/84367301/120441289-38364400-c3a6-11eb-866c-e033ae978769.jpg)
![screenshot-2021_05_18_19_16_09](https://user-images.githubusercontent.com/84367301/120441297-39677100-c3a6-11eb-9ee8-e14c59482c65.jpg)
![screenshot-2021_05_18_19_16_42](https://user-images.githubusercontent.com/84367301/120441302-3a000780-c3a6-11eb-8d2c-54d0b8a10790.jpg)
![screenshot-2021_05_18_19_17_03](https://user-images.githubusercontent.com/84367301/120441309-3b313480-c3a6-11eb-9207-3e1b301e0bc2.jpg)
![screenshot-2021_05_18_19_17_40](https://user-images.githubusercontent.com/84367301/120441313-3bc9cb00-c3a6-11eb-9266-006ca07b281e.jpg)
![screenshot-2021_05_18_19_17_43](https://user-images.githubusercontent.com/84367301/120441319-3cfaf800-c3a6-11eb-931a-c71de2ac4672.jpg)
![screenshot-2021_05_18_19_21_17](https://user-images.githubusercontent.com/84367301/120441322-3d938e80-c3a6-11eb-9c6a-cb11ec7d6a5e.jpg)
![screenshot-2021_05_18_19_23_07](https://user-images.githubusercontent.com/84367301/120441324-3ec4bb80-c3a6-11eb-94e9-5ffd2339561b.jpg)
![screenshot-2021_05_18_20_20_23](https://user-images.githubusercontent.com/84367301/120441331-408e7f00-c3a6-11eb-81c0-6ec36ef93eb9.jpg)
![screenshot-2021_05_18_20_21_04](https://user-images.githubusercontent.com/84367301/120441337-41bfac00-c3a6-11eb-97ed-ae6cac605799.jpg)

**Comment by Linear524** [comment]
I've also tried ReShade and it is not the right solution, because real PS3 games uses MLAA only on dedicated output layers, some geometry is antialiased by MLAA and some other things like GUI layers or FX layers are not affected... ReShade just takes everything and tries to smooth every edged pixels, resulting in crappy image... 
The right solution would be to find and fix broken MLAA code in RPCS3, but I don't have enough brains to do this :P

**Comment by kd-11** [comment]
Guys, rpcs3 is not finished yet. This will be fixed but there are many other tickets on my queue at the moment. While this bug may be distracting, there are many other issues that completely break games and therefore have higher priority, but I'll get to this one soon. As long as the ticket is assigned, it has visibility on my queue.

**Comment by Xcedf** [comment]
@kd-11 We never meant to hurry you on this one, sorry if it happened to be a bit off-top.

**Comment by kd-11** [comment]
I'm looking at the Z sampling problems left, and this seems related. I need some updated traces.
If possible, RDC captures using the build from https://github.com/RPCS3/rpcs3/pull/10964 would also be nice.

**Comment by Linear524** [comment]
I would like to help with RDC capture data, but I don't know how to make this procedure correctly with renderDoc capture...  Is there any manuals or instructions about this ?

**Comment by Linear524** [comment]
Confirm - this PR fixes some shadow cubemaps:
![1623](https://user-images.githubusercontent.com/84367301/136731213-e005e1a0-b6eb-4571-9844-33336d23f76d.jpg)
![1624](https://user-images.githubusercontent.com/84367301/136731227-4ad7baad-1566-4df0-beae-e5cd119fcad1.jpg)
![1625](https://user-images.githubusercontent.com/84367301/136731229-c287bddf-e07e-41f1-b18f-ce80333bc823.jpg)

But not all, spotlight cubemaps still broken:
![1626](https://user-images.githubusercontent.com/84367301/136731377-7bc11236-6f62-41b4-9851-6b20e92803c1.jpg)
![1627](https://user-images.githubusercontent.com/84367301/136731378-b05edcc8-365e-47c6-9617-4f41be6d2087.jpg)
![1628](https://user-images.githubusercontent.com/84367301/136731381-275261cc-9364-4360-9159-1b4ccca451da.jpg)

Notice how Joel's shadow missing lower parts of his body and no fingers in this type of shadows...
Is it possible to fix this spotlight cubemaps just like previous type of shadowmaps was fixed ?

Spotlight shadow cubemaps located on every bright-blinking light bulbs in TLoU.

**Comment by MSuih** [comment]
@Linear524 Open a new issue with fresh captures for the spotlights
