### ISSUE TITLE
Tomb Raider Trilogy - Tomb Raider Legend Shadows/Lighting issue

### ISSUE THREAD

**Issue by Boogie90** [RPCS3/rpcs3#9590]
Shadows/Lighting showing incorrectly in Tomb Raider Legend - Trilogy

Latest version of RCPS3:

Correct:

![Correct](https://user-images.githubusercontent.com/76414866/104242389-c77aa380-5467-11eb-9f35-083e2250ab2e.jpg)

Incorrect:

![Incorrect](https://user-images.githubusercontent.com/76414866/104242411-ce091b00-5467-11eb-8596-7260f55f82b9.jpg)

![Incorrect](https://user-images.githubusercontent.com/76414866/104242866-6ef7d600-5468-11eb-9065-6419ba6b4cc5.jpg)

Already tried with Write Color Buffers on. Tried default resolution. Tried different Shader mode.

The flickering is happening when moving around.

Update: Noticed on older builds, from approximately 2 months ago, there are no issues, ex: 0.0.13-11325, but obviously, the performance is worse.

**Comment by AniLeo** [comment]
Does not follow regression guidelines, missing what build it regressed on

**Comment by Boogie90** [comment]
Build: 0.0.14-11536-838cbe18 Alpha

**Comment by AniLeo** [comment]
Impossible it regressed in that build since it just changes an include

**Comment by Boogie90** [comment]
I'm sorry, but I do not understand your response.

**Comment by AniLeo** [comment]
Read the regression issue template again: https://github.com/RPCS3/rpcs3/blob/master/.github/ISSUE_TEMPLATE/1-regression-report.md

**Comment by Boogie90** [comment]
I've provided the captures. It still happens with latest build: 0.0.14-11579-3567c43f Alpha and I've provided the older build on which it worked. I think it has to do with the shader compilaton (improvement).

**Comment by digitaldude555** [comment]
@Boogie90 retest now

**Comment by FrankyMc** [comment]
Still happens as of September 2021.

**Comment by Asinin3** [comment]
Even with precise zcull on gpu tab? no log provided.

**Comment by BlueBomberX** [comment]
> 
> 
> Even with precise zcull on gpu tab? no log provided.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7252595/RPCS3.log.gz)

Here's a log with a few different configurations. 

It seems to occur regardless of any settings. Even defaults, and in both Vulkan and OpenGL.

**Comment by kd-11** [comment]
This problem is related to the bug with condemned: criminal origins. Proper shaders are loaded by the game for the wrong draw call. It seems to be that we're loading them too early? It's just weird, but at least we have more cases so I can cross-analyze the issue. Only 3 applications are known to exhibit this behavior so far.

**Comment by BlueBomberX** [comment]
> 
> 
> This problem is related to the bug with condemned: criminal origins. Proper shaders are loaded by the game for the wrong draw call. It seems to be that we're loading them too early? It's just weird, but at least we have more cases so I can cross-analyze the issue. Only 3 applications are known to exhibit this behavior so far.

Interesting. I can say that it did work properly in much older builds. So I don't know if that could be used as a point of reference. It stopped working in one of the builds just before Dualsense support was added. I want to say within a week or so. If you like, I can try to find the exact build where it stopped working. If more logs are needed, let me know.

**Comment by BlueBomberX** [comment]
So it appears to be v0.0.13-11347-3a0b3a85 where the issues started. Lighting appearing incorrect and flickering with camera movement. The version before, v0.0.13-11346-15a12afe, seems to work as intended. 

I will add that in more recent iterations the lighting flickers without input from the player, so it has evolved since then. However, it is more stable in recent versions than in ones from months back. At some point, the character model also began flashing a bring white/blue as do some random, moveable, objects here and there.

[RPCS3 v0.0.13-11346-15a12afe Working lighting.gz](https://github.com/RPCS3/rpcs3/files/7489781/RPCS3.v0.0.13-11346-15a12afe.Working.lighting.gz)
[RPCS3 v0.0.13-11347-3a0b3a85 incorrect lighting-flickering with camera movement.gz](https://github.com/RPCS3/rpcs3/files/7489782/RPCS3.v0.0.13-11347-3a0b3a85.incorrect.lighting-flickering.with.camera.movement.gz)

**Comment by Xcedf** [comment]
@BlueBomberX if it's 11347 regression and has flickering, can you please check this build, it has some code from 11347 reverted
https://mega.nz/file/nRQk1TTR#CaeY-hOpag7ctdRns6mLjnZIKMZ9EGBf_yoyUMlwA_c
Just want to know if my issue is the same
https://github.com/RPCS3/rpcs3/issues/10796

**Comment by BlueBomberX** [comment]
> 
> 
> @BlueBomberX if it's 11347 regression and has flickering, can you please check this build, it has some code from 11347 reverted https://mega.nz/file/nRQk1TTR#CaeY-hOpag7ctdRns6mLjnZIKMZ9EGBf_yoyUMlwA_c Just want to know if my issue #10796 is the same

You're on to something here. The flickering and lighting being broken is 100%, gone, but there appears to be a related, much more minor issue where some lighting is now visible through some smaller/thinner physical objects. For example, walking towards the exit of a cave, you can see the sunlight on the ground outside the cave through the wall to the side of the exit. This is a huge step in the right direction. 

The character flickering/becoming a flash of blue/white and some random objects is still present, but I think it may be a different, though related, issue. I believe that has always been an issue with some builds being better than others. This one appears to be on the better end as well.

**Comment by Xcedf** [comment]
@BlueBomberX, Thanks for info, and sunlight through objects could be the result of some other hacks inside this build.

**Comment by kd-11** [comment]
Interesting findings. I'll push a fix later today.

**Comment by brad86m** [comment]
The flickering issues are back in Anniversary and Legend.

**Comment by uncaged9000** [comment]
Sadly, the flickering issues mentioned above are still there with RPCS3 v0.0.28-15172-5d7e75c5 Alpha.
I've been watching them for approx 12 last revisions.

**Comment by readywer** [comment]
> Sadly, the flickering issues mentioned above are still there with RPCS3 v0.0.28-15172-5d7e75c5 Alpha. I've been watching them for at least 12 last revisions. Didn't try any older ones, the comment above makes me think its not required.

Don't leave comment under closed issues create a new one with all the required information.
