### ISSUE TITLE
rpcs3 (flatpak) is unable to update to the newest version when trying to update using rpcs3's ui.

### ISSUE THREAD

**Issue by FireRacing** [RPCS3/rpcs3#9597]
## Quick summary
Updating process of rpcs3 (flatpak version)

## Details
rpcs3 (flatpak) is unable to update to the newest version when trying to update using rpcs3's ui.

#### 1. Please attach RPCS3's log.
   RPCS3 v0.0.13-1-bd269bcc Alpha | HEAD | Firmware version: 4.87 
 AMD Ryzen 5 3600X 6-Core Processor | 12 Threads | 15.65 GiB RAM | TSC: 3.800GHz | AVX+ | FMA3
   Operating system: POSIX, Name: Linux, Release: 5.4.0-60-generic, Version: #67-Ubuntu SMP  Tue Jan 5 18:31:36 UTC 2021
   RSX: Found vulkan-compatible GPU: 'GeForce GTX 1660' running on driver 460.32.3.0
   E UPDATER: Failed to create new AppImage file: /app/bin/rpcs3

## 3. Please attach screenshots of your problem.
![Screenshot from 2021-01-13 14-37-05](https://user-images.githubusercontent.com/33418792/104431710-35c97e00-55ae-11eb-8796-c3bcebea1b5a.png)

#### 5. Please provide your system configuration:
* OS : Linux Mint 20
* CPU: Ryzen 5 3600x
* GPU : Geforce GTX 1660
* Driver version: 460.32.3.0

**Comment by MSuih** [comment]
On linux the updater is trying to update to latest appimage. If you are using flatpak then you must use other means to update your rpcs3, or switch over to appimage versions.

**Comment by AniLeo** [comment]
To clarify, the only ways we officially distribute RPCS3 on Linux are AppImage and the rpcs3-git AUR

**Comment by FireRacing** [comment]
I see. Thank you for your patience.
