### ISSUE TITLE
NCAA 14 unable to load save - Access violation reading location 0x4 (unmapped memory) [type=u32]

### ISSUE THREAD

**Issue by hawth33** [RPCS3/rpcs3#9599]
Game loads up fine, but when loading into any Dynasty save (I've tried 6 different files), I get the following error:

> F {PPU[0x1000014] Thread (FGGameSim) [0x00a4e4fc]} VM: Access violation reading location 0x4 (unmapped memory) [type=u32]

This issue began after updating to the current build when asked (11568). I have rolled back to several different builds that worked before, but with no luck.

**Comment by dmilliner92** [comment]
Same issue here, hopefully we can get this fixed

**Comment by elad335** [comment]
Hopefully we can get a log for this to be fixed.

**Comment by dmilliner92** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5811258/RPCS3.log)

is this helpful? never done this before

**Comment by dmilliner92** [comment]
windows security quarantined my files. restored them and now it works

**Comment by erikhiggy** [comment]
@dmilliner92 how did you restore them? I think I may be having the same issue.

**Comment by dmilliner92** [comment]
open windows defender, click on protection history, then you'll see a list
and filter by quarantined items and you'll  see the files that have been
quarantined and restore them

**Comment by AniLeo** [comment]
I've seen this issue reported a few times from people saying it was the AV that ate one game file
You also mentioned rolling back to builds where it worked before and the issue persisting, so it's definitely not a regression

Perhaps we need a way to detect these anti virus and emit warnings

**Comment by user28111999** [comment]
> I've seen this issue reported a few times from people saying it was the AV that ate one game file You also mentioned rolling back to builds where it worked before and the issue persisting, so it's definitely not a regression
> 
> Perhaps we need a way to detect these anti virus and emit warnings

No way anti-viruses are doing this, I have none installed and completely disabled the Windows one and I still get this error

**Comment by AniLeo** [comment]
Do not golden shovel 2 year old issues, even if you have similar symptoms it doesn't mean it has the same cause. This particular issue was indeed caused by AV 2 years but that cause shouldn't happen anymore as it was reported as a false positive to the vendor.
