### ISSUE TITLE
MRC The Great Wall

### ISSUE THREAD

**Issue by PoorMansConsole** [RPCS3/rpcs3#9607]
![MRC Patch 1 11](https://user-images.githubusercontent.com/77487037/104711247-12443600-575c-11eb-9254-991fc6fca219.png)

![MRC 02](https://user-images.githubusercontent.com/77487037/104711197-ff316600-575b-11eb-9f0b-87bbd22272cf.png)

E {PPU[0x1000000] Thread (main_thread) [0x0096b74c]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98167/USRDIR/Data/FE_Kart/TutorialPopUp.gfx” [1]
E {PPU[0x1000000] Thread (main_thread) [0x0096b74c]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98167/USRDIR/Data/FE_Kart/TutorialPopUp.gfx” [2]
E {PPU[0x1000000] Thread (main_thread) [0x0096b74c]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98167/USRDIR/Data/FE_Kart/RaceCountdown.gfx” [1]
E {PPU[0x1000000] Thread (main_thread) [0x0096b74c]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCUS98167/USRDIR/Data/FE_Kart/RaceCountdown.gfx” [2]

**Comment by Satan86** [comment]
Enable Write Colour Buffers

**Comment by PoorMansConsole** [comment]
> Enable Write Colour Buffers
Got it.
It dissapeared.
Thank You!

**Comment by Asinin3** [comment]
In future, check game wiki pages, this was already documented https://wiki.rpcs3.net/index.php?title=ModNation_Racers or atleast check forum posts before making a bug report.
