### ISSUE TITLE
Lone survivor director's cut

### ISSUE THREAD

**Issue by Varon9** [RPCS3/rpcs3#9614]
## Quick summary
not properly working

## Details

at the very begining of the game when you have to drink the spresso, can't interact with anythin, keeps saying "i can't see anything" feature that appears later on the game when you try to interact with something in a dark place without turning on the flashlight, which shouldn't happen here, letting you stuck at the begining of the game
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5824611/RPCS3.log)

#### 1. Please attach RPCS3's log.
* Run the game until you find the issue.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc. 

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc. 
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.
![imagen](https://user-images.githubusercontent.com/22385635/104815737-9f4bc580-5816-11eb-9c87-ed3c46a40cba.png)
#### 4. Please provide comparison with real PS3.
![imagen](https://user-images.githubusercontent.com/22385635/104815814-2862fc80-5817-11eb-96cf-60ab0057f30b.png)

#### 5. Please provide your system configuration:
* OS Windows 10 LTSC build 17763.1697
* CPU Intel Core i7-8750H
* GPU nVidia GTX 1070 max-q 8gb
* Driver version 461.09
* RAM 16Gb ddr4
* Omen 15-dc0xxx

#### Please include.
* Anything else you deem to be important

**Comment by kd-11** [comment]
I think you just need to enable write color buffers which allows the CPU to read GPU data. It's how brightness is calculated in games, they read the image that was drawn and average brightness. Without write color buffers enabled, the CPU only sees black output where there is data rendered on the GPU but we save time by not having to copy things over.

**Comment by Varon9** [comment]
didn't fixed it, i guess i didn't explained myself well, it's a bug from the game that only happens when it's emulated, not in real hardware. It's no a graphical glitch or a matter of brightness, in that (literally) second screen of the game, you don't have flashlight nor you need it, you should be able to interact whit that mean with a box in his head or the couch, or the expresso (which you need to drink to pass that area)

**Comment by digitaldude555** [comment]
![Screenshot (251)](https://user-images.githubusercontent.com/26138653/105860386-2b6ba300-5ff6-11eb-81b5-4330518e3fd2.png)
I dont get the bug are you sure the Write color buffer option doesnt work?

**Comment by Varon9** [comment]
my bad, the game had custom configuration and i've enabled write color
buffer in general settings [FacePalm] now it works! thanks so much!
[image: imagen.png]

**Comment by Megamouse** [comment]
Closing
