### ISSUE TITLE
Tekken Evolution NPEB01406 graphical issue

### ISSUE THREAD

**Issue by fuhuan416** [RPCS3/rpcs3#9617]
Quick Summary:
Character's clothing is black

Details:
Whether it’s the automatic demonstration of the game or the scene image, the sound is almost perfect, only the character’s clothing is black, which is obviously wrong

#### 1. Please attach RPCS3's log.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5825794/RPCS3.zip)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
Regarding Renderdoc, it took me about half an hour to inject into Rpcs3, but I found that the graphics problem may be similar to the previous Tekken Tag 2.
https://github.com/RPCS3/rpcs3/issues/5900

#### 3. Please attach screenshots of your problem.
![rpcs3 2021-01-17 16-36-54-593](https://user-images.githubusercontent.com/6281757/104835641-f15a1d00-58e2-11eb-9008-846820b1fadd.png)
![rpcs3 2021-01-17 16-36-59-881](https://user-images.githubusercontent.com/6281757/104835642-f4550d80-58e2-11eb-8502-9769bb0a537c.png)
![rpcs3 2021-01-17 16-37-06-822](https://user-images.githubusercontent.com/6281757/104835644-f6b76780-58e2-11eb-9a24-df8650722167.png)

#### 4. Please provide comparison with real PS3:
The picture above is Rpcs3, the picture below is PS3, one of the characters is the same, the guy without the shirt, his belt should be red and the pants should be patterned.
![rpcs3 2021-01-17 16-37-06-822](https://user-images.githubusercontent.com/6281757/104835593-a7713700-58e2-11eb-8fdd-07dc22858234.png)
![tekken-revolution-s11](https://user-images.githubusercontent.com/6281757/104835595-aa6c2780-58e2-11eb-9f5a-cca17f8a0f0d.jpg)

#### 5. Please provide your system configuration:
* Win10 64bit 20H2
* Ryzen 5 3550H
* nVidia GTX 1650
* 460.89

#### Please include.
* This game is an online game, the official server has been suspended, but some people are repairing offline playability, so there is still hope to solve the network problem, and finally successfully play this game, then the compatibility status can also be set Ingame or Playable or even Perfect
If you have to say what is the most important, for an online game, it is undoubtedly an online battle.

**Comment by fuhuan416** [comment]
![rpcs3 2021-01-17 17-21-37-416](https://user-images.githubusercontent.com/6281757/104836387-9aefdd00-58e8-11eb-8b09-4e4b35f4e199.png)
When I opened Write color buffers, the character’s clothing issue was resolved, then the title of this issue should be changed to 'Networks issues'
👍

**Comment by Asinin3** [comment]
Networking not working due to a private server being required should definitely not be tracked on GitHub as an issue.
