### ISSUE TITLE
Alone in the Dark Inferno save issue BLAS50043

### ISSUE THREAD

**Issue by fuhuan416** [RPCS3/rpcs3#9618]
## Quick summary
The game save issue

## Details
When I tried to save the progress in the game, the console prompts this message and the game freezes

#### 1. Please attach RPCS3's log.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5825852/RPCS3.zip)

#### 3. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/6281757/104837478-bf02ec80-58ef-11eb-8b2d-1a216ca32332.png)

#### 5. Please provide your system configuration:
* Win10 64bit 20H2
* Ryzen5 3500H
* nVidia GTX1650
* 460.89

#### Please include.
* As for the specific saving mechanism of the game, I am not quite sure. As far as the actual situation is concerned, this game can be saved at any time in the game menu.

**Comment by fuhuan416** [comment]
As for the specific saving mechanism of the game, I am not quite sure. As far as the actual situation is concerned, this game can be saved at any time in the game menu. No matter if I save manually (tested at any time, free control of time, or during cutscenes), or the prompt to save in the game, the PRCS3 console will prompt access violation and the game will get stuck

**Comment by Augusto7743** [comment]
Try disable "Use Native User Interface" in options or move your trophy folder.

**Comment by fuhuan416** [comment]
> Try disable "Use Native User Interface" in options or move your trophy folder.

Thanks for your suggestion, I found the option "Use Native User Interface" in the "Emulator" tab of the emulator and I disabled it, but it doesn't work

Then your second suggestion,'move my trophy folder', after I started the game, I changed the name of the'dev_hdd0\home\00000001\trophy' folder

I did the above 2 suggestions at the same time, but the problem remains

**Comment by fuhuan416** [comment]
This issue has been fixed.

**Comment by Jacobson1985** [comment]
Hi,

I followed your instructions but savegames still stuck for me. What did you do to solve that ? Thanks in advance
