### ISSUE TITLE
Fatal errors with so many other errors and white screen

### ISSUE THREAD

**Issue by Hamado201** [RPCS3/rpcs3#9639]
Hey,
I am using a MacBook Pro with Parallel desktop windows 10 and I have done with downloading, installing for RPCS3 but I cannot play any game cause of white screen appears with so many errors failed. something like that.

E {RSX [0x0000000]} RSX: OpenGL: initialization of glTextureBarrier failed.
E {RSX [0x0000000]} RSX: OpenGL: initialization of glTextureBarrierNV failed.
E {RSX [0x0000000]} RSX: OpenGL: initialization of glMemoryBarrier failed.
E {RSX [0x0000000]} RSX: OpenGL: initialization of glDispatchCompute failed.
E {RSX [0x0000000]} RSX: OpenGL: initialization of glDepthRangedNV failed.
E {RSX [0x0000000]} RSX: OpenGL: initialization of glDepthBoundsdNV failed.
F {RSX [0x0000000]} SIG: Thread terminated due to fatal error: Unknown context dma 0x0
(in file D:\a\1\s\rpcs3\Emu\RSX\gcm_enums.cpp:1176[:22], in function to_context_dma)

My MacBook Pro Specs;
MacBook Pro (16-inch, 2019)
processor: 2.4 GHz 8-Core Intel Core i9
Memory: 32 GB 2667 MHz DDR4
GPU: AMD Radeon Pro 5500M 8 GB

Regards.
<img width="1792" alt="Screen Shot 2021-01-22 at 9 55 50 PM" src="https://user-images.githubusercontent.com/77853245/105534656-3e852700-5d07-11eb-80c0-5810b62e3f64.png">

**Comment by kd-11** [comment]
Your environment does not provide OpenGL 4.x as per the emulator requirements. Obviously running things in a virtual environment isn't going to go smoothly.
Also missing log, but honestly there is no point. Rpcs3 cannot run without proper hardware support.

**Comment by kingemini** [comment]
what kind of hardware would be needed for this issue ??? I am having the same error.

Windows 10 pro 64-bit
Intel core i5-3230M 
CPU @ 2.60ghz
intel HD graphics 4000

**Comment by AniLeo** [comment]
Also below minimum requirements.
See https://rpcs3.net/quickstart

**Comment by kydaguy** [comment]
> Also below minimum requirements.
> See https://rpcs3.net/quickstart

well my pc specs are:
Windows 10 home 64-bit
AMD Ryzen 5 1600 six-core processor
CPU @ 3.20GHz
Nvidia GeForce GTX 1080

and i get this issue, 

F SIG: Thread terminated due to fatal error: Unknown context dma 0x0
(in file D:\a\1\s\rpcs3\Emu\RSX\gcm_enums.cpp:1176[:22], in function to_context_dma) (e=0x0000007e[126])

any ideas?

**Comment by YuriNator557** [comment]
> > Also below minimum requirements.
> > See https://rpcs3.net/quickstart
> 
> well my pc specs are:
> Windows 10 home 64-bit
> AMD Ryzen 5 1600 six-core processor
> CPU @ 3.20GHz
> Nvidia GeForce GTX 1080
> 
> and i get this issue,
> 
> F SIG: Thread terminated due to fatal error: Unknown context dma 0x0
> (in file D:\a\1\s\rpcs3\Emu\RSX\gcm_enums.cpp:1176[:22], in function to_context_dma) (e=0x0000007e[126])
> 
> any ideas?

Please ask for help in the discord server. If you don't use discord, you can also ask in the forums.

**Comment by Renaldo-Paulo** [comment]
Thread terminated due to fatal error: Unknown context dma 0x0
(in file D:\a\1\s\rpcs3\Emu\RSX\gcm_enums.cpp:1176[:22], in function to_context_dma) (e=0x0000007e[126])

please Help me with this issue. you already have my email.
