### ISSUE TITLE
White Screen after visibility change during Emu.Pause

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#9641]
This is more a question than an issue:

If I minimize the game window (on windows) and then pause the emulation, the game window is blank.
Is it possible to show the last frame instead when we show the game window?

If yes then this would be a nice improvement.

**Comment by Megamouse** [comment]
The same thing happens when I minimize the game window with an already paused emulation

**Comment by MSuih** [comment]
Somewhat similar to #9596, since they're both about redrawing the window when game isn't rendering any frames

**Comment by kd-11** [comment]
RSX is also paused when emulation is paused. We can only have one or the other; either pausing emulation pauses rendering as well or it doesn't.

**Comment by elad335** [comment]
It's technically a bug because of lost information/frame.

**Comment by Nekotekina** [comment]
I think it depends heavily on window manager. May be win10-specific.

**Comment by kd-11** [comment]
Yea, its because dwm hands over hw-accelerated drawing to the application, so the application must respond to redraw messages. The contents are held in a hw context, but since the window changed, the contents are now invalid (which is why minimize/resize triggers swapchain recreation). This is why its white when you resize, the renderer needs to rebind the context to the window because it logically behaves like its a different one.

**Comment by Megamouse** [comment]
I assume we should know what the last frame was.
So can't we just render it when the window is shown?

**Comment by kd-11** [comment]
RSX is still paused (not flipping). This is what I was talking about, we either pause everything or we don't and let RSX keep running.

**Comment by kd-11** [comment]
Something to note: the renderer (vulkan in this case) is only made aware that window geometry has changed by the driver when submitting present requests (flip). So it would need to keep presenting to respond to such changes.
Or we re-add the win32 msq hooks I had some time in the past, but win32 msqs are cancer.

**Comment by auranticus** [comment]
It seems like Dolphin does not have this issue.
yuzu, while not using a separate render window, suffers this also when minimize/show to desktop after pausing.

**Comment by Megamouse** [comment]
Since we now flip at ~30fps on pause, this issue is obsolete.
