### ISSUE TITLE
[Feature Request] [Longterm] Software rendering support (GPU not required)

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#9642]

**Comment by AniLeo** [comment]
This can be done on Vulkan since lavapipe already works to some extent, for OpenGL not yet besides using zink which runs on top of Vulkan

**Comment by Augusto7743** [comment]
software render help in future bug reports

**Comment by AniLeo** [comment]
Technically with #9761 you can now use both OpenGL and Vulkan on software mode with Mesa

**OpenGL:** llvmpipe (Mesa's OpenGL software driver)
**Vulkan:** lavapipe (Mesa's Vulkan software driver)

It works properly for samples

**Vulkan (lavapipe)**
![image](https://user-images.githubusercontent.com/10283761/107589663-6842b700-6bfe-11eb-9726-2d886b117a8d.png)

There's also Zink which is an OpenGL on Vulkan layer which you can run on top of lavapipe

**Comment by AniLeo** [comment]
I think this can be closed as solved as is, llvmpipe (OGL) works on Windows too and lavapipe (VK) will eventually as well. These are both CPU-only drivers.

**Comment by kd-11** [comment]
A true sw renderer is also possible (that is integrated directly into the renderer core) and I could technically write one, but its unfulfilling work to spend a month plumbing in code that will never be used. The biggest challenge with sw renderers in my experience has always been the texture mapping side of things. It can get slow even with assembly optimizations, although maybe modern CPUs with their monstrous caches may not be as negatively impacted. I agree that we may close it for now as we have solved the major use of a sw pipe which is largely for CI/CD and automated testing.

**Comment by AniLeo** [comment]
Yeah, there would be no gain in having and maintaining something software side on RPCS3 itself. 
We can simply rely on already existent CPU-only drivers to do the job.
