### ISSUE TITLE
What's taking so long?

### ISSUE THREAD

**Issue by idgas01** [RPCS3/rpcs3#9645]
I heard about RPCS3 a long time ago when I was looking for a way to play "The Last of Us".  I saw that RPCS3 was working on porting "The Last of Us" and that they were making "some progress".  So I've been keeping my eye on it.  But there has bee NO PROGRESS at all in over a year.  If I go to this link (https://rpcs3.net/compatibility?g=the+last+of+us), it shows that one "The Last of Us" version hasn't been updated in over two years.  And the Blu-Ray version were last updated 8 months ago.  What's taking so long?  I get that it is a lot of work, but 1-2 years is a long time to wait for an update.  At this rate it will take 20 years before it it reaches the "Playable" state and I'm not sure 60% playability is worth looking into.

**Comment by AniLeo** [comment]
Play good games instead

**Comment by Asinin3** [comment]
Updated date on the compatibility page just states when the game was last moved category. So that date is when it was first confirmed to go ingame, it doesn't mean anything at all about there being no progress. Of course there has been lots of progress, which you would know if you followed the RPCS3 youtube channel, and other media.

You're very wrong about almost everything you wrote. look at this channel for footage of the new patches for instance: https://www.youtube.com/user/ZEROx2085/videos the game can be played from start to finish with relatively decent graphics/performance if you have a high-end PC and use the correct settings + patches.

If you want help setting it up don't ask here though, GitHub is for proper issue reports not tech support or spam like your post is. Read: https://wiki.rpcs3.net/index.php?title=The_Last_of_Us

**Comment by idgas01** [comment]
> You're very wrong about almost everything you wrote

> The game can be played from start to finish.


Yeah, really?  I appreciate some of the useful information, but a lot of the crap you typed is just condescending nonsense.

I dismissed most of what you wrote, but I do want to say a few things.  One, why would an individual need to follow a YouTube channel just to get an accurate update on the progress of a game port?  Or other media for that matter.  It's just plain stupid.  I should be able to go to the RPCS3 website to get that accurate information.  Two, yeah I know what GitHub is for.  But if I need to contact someone and there is no contact info on their website, best believe I will use their GitHub for whatever the Hell I feel like.  Next.  You claim that the game is playable from beginning to end.  Maybe that is true.  But shouldn't their Compatibility page also reflect that? https://rpcs3.net/compatibility?g=the+last+of+us  On their page, it says that In-Game is basically 33% done and furthermore "Games that either can't be finished, have serious glitches or have insufficient performance".  If the game is playable, don't you think that maybe they should update that status to Playable (66-100%)?  I really get tired of turds with attitudes.  Spend less time talking down to people and acting like a know-it-all when you are a know-very-little.  I don't feel like being lectured at.  I just wanted to know what was taking so long.  I haven't visited your links, but I get that they are still working on the game and have made a lot of progress.  So that helped.  But all the other crap you typed.  Well if I could say two works, I would.  But I can't.  But I bet you can guess what those words would be.

**Comment by idgas01** [comment]
Oh, and I want to add one more thing.  This website https://wiki.rpcs3.net/index.php?title=The_Last_of_Us  I visited that a week ago.  Guess what it says on the bottom?  "Known Issues: This game is currently not playable."

**Comment by Megamouse** [comment]
This is a platform for developers, not for random status updates for your highness.
It's even in the FAQ on the website, which ironically says you should not ask for or submit status updates on The Last of Us.
![image](https://user-images.githubusercontent.com/23019877/106064889-c5b50f00-60fa-11eb-9675-65c72db4d24b.png)

Btw, the percentage for Ingame does not mean that a game is "33% done", but that 30% of all games are going at least ingame.

**Comment by MSuih** [comment]
>Guess what it says on the bottom? "Known Issues: This game is currently not playable."
>You're very wrong about almost everything you wrote (ROFL)
>The game can be played from start to finish. (ROFL)

Our definition of playable is "Games that can be completed with playable performance and no game breaking glitches". TLOU suffers from performance issues and major visual glitches, so it cannot be considered playable yet, but it can still be played from start to finish.

>  Two, yeah I know what GitHub is for. But if I need to contact someone and there is no contact info on their website, best believe I will use their GitHub for whatever the Hell I feel like. 

Visit our discord server instead.
