### ISSUE TITLE
[Bug] utils::shm::unmap_critical does not work on the 2 64k egdes of reserved memory (Win32)

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#9653]
This function relies on the existance of upper and lower memory in reserved memory block. A workaround can be found in SPU LS mapping and unmapping by extending the edges but it's just that, a workaround.

**Comment by Nekotekina** [comment]
It's not correct to call a bug, because of a simple assumption that first and last 64k are invalid. It was simplified with that in mind.
SPU LS can be possibly rewritten (and optimized) to not use these routines at all in order to make 3 contiguous mirrors.

**Comment by Nekotekina** [comment]
Maybe I'll implement ``shm::try_map`` for this purpose

**Comment by Nekotekina** [comment]
Implemented in #9654

**Comment by sampletext32** [comment]
May be closed as implemented?

**Comment by Megamouse** [comment]
I guess we can close this ?
@elad335
