### ISSUE TITLE
Castlevania: Lords of Shadow [BLUS30339]: Multiple issues

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#9656]
Three issues with this game:

1. **Game freezes after second level.** Game locks up entirely after the second level is completed.

2. **Pre-rendered cutscenes stutter.**  Framerate drops from a consistent 60fps ingame to 3-10fps during pre-rendered cutscenes.

3. **Fonts don't render properly.**  Whenever the game presents a second line of text, only the first line is rendered.  
Not sure if this is related, but the ingame gamma "slider" doesn't render test images either.

Test system details:

* OS: Linux Mint 20.1 / kernel 5.8
* CPU: Intel i7-7820HK
* GPU: Nvidia GTX-1070M / driver 460.32
* Compiler: gcc 10.2.0
* Build: 848067470882b8967629ab52703df6b4dab0bef9

Logfile, taken immediately after game freeze: [here](https://github.com/RPCS3/rpcs3/files/5870108/rpcs3.log.gz)
Save file, taken in the scene leading to the game freeze (also shows cutscene stuttering after fight is completed): [here](https://github.com/RPCS3/rpcs3/files/5870114/Save.zip)

**Comment by Megamouse** [comment]
the dump seems corrupted, no licenses are found

**Comment by Shoegzer** [comment]
@Megamouse can you please reopen?  This dump should be okay but all issues noted above still occur.  I've updated the original post with new information.  Thanks.
