### ISSUE TITLE
SYS: 'cellSpursInitializeWithAttribute2' failed

### ISSUE THREAD

**Issue by kbruno89** [RPCS3/rpcs3#9659]
Hi,

I'm try play Dragon Ball Z: Battle of Z (SERIAL BLUS31314) and get error on boot.

When install firmware, its hangs on:

E {PPU[0x1000000] Thread (main_thread) [HLE:0x01023914, LR:0x004b9bcc]} SYS: 'cellSpursInitializeWithAttribute2' failed with 0x80010002 : CELL_EINVAL [1]

I'm using latest appImage, running on Ubuntu 20.04.

i7 3770
RX 580 8GB

Already change limits.conf.

S {PPU[0x1000000] main_thread } SPU: SPU Runtime: Built the interpreter.
E {PPU[0x1000000] Thread (main_thread) [HLE:0x01023914, LR:0x004b9bcc]} SYS: 'cellSpursInitializeWithAttribute2' failed with 0x80010002 : CELL_EINVAL [1]
U {PPU[0x1000000] Thread (main_thread) [0x0086908c]} PPU TODO: Unimplemented syscall syscall_988 -> CELL_OK (r3=0x1, r4=0x0, r5=0x888310, r6=0xe674a8, r7=0xe674ac, r8=0xe674a4, r9=0xe674a8, r10=0x18)
U {PPU[0x1000000] Thread (main_thread) [HLE:0x01026eec, LR:0x00619aa8]} sysPrxForUser TODO: sys_prx_exitspawn_with_level()
U {PPU[0x1000000] Thread (main_thread) [0x0086dec0]} PPU TODO: Unimplemented syscall syscall_988 -> CELL_OK (r3=0x1, r4=0x0, r5=0xe23448, r6=0x621468, r7=0x0, r8=0xf586a8, r9=0x0, r10=0xe22b98)
S sys_process: Process finished
E SIG: Thread [RSX.W1] is too sleepy. Took 6.259µs to wake it up!
E SIG: Thread [RSX.W2] is too sleepy. Took 7.653µs to wake it up!
E SIG: Thread [CPU Profiler] is too sleepy. Took 6.390µs to wake it up!
E SIG: Thread [MsgDialog Close Thread] is too sleepy. Took 6.500µs to wake it up!
E SIG: Thread [Usb Manager Thread] is too sleepy. Took 1.448µs to wake it up!
E {SPU LLVM} SIG: Thread [SPU LLVM Profiler] is too sleepy. Took 6.662µs to wake it up!
E SIG: Thread [SPU LLVM] is too sleepy. Took 3.015µs to wake it up!

**Comment by AniLeo** [comment]
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Comment by elad335** [comment]
Firmware is not installing in your log, you are missing it and running the game without it.
