### ISSUE TITLE
Depth_read.elf regression

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#966]
It should be light green color in background instead of black

![depth_read](https://cloud.githubusercontent.com/assets/3000282/5792204/7101406c-9f47-11e4-8cfd-e99f8096322d.jpg)

**Comment by raven02** [comment]
It renders correct in rsx branch now and will close once merged

**Comment by vlj** [comment]
With master the clear color is correct but the right hand corner depth preview is black (ie it's not properly read) with GL backend.

**Comment by raven02** [comment]
It works well in GL backend sometimes ago so it is a regression with one of commit but bit difficult to track back :(

**Comment by Syphurith** [comment]
@raven02 If you can remember when that is correct, and can find the corresponding functions or files. You may track it down. BTW you can find all those compiled versions on the forum..

**Comment by raven02** [comment]
Later today i may have time to track it down . Probably @vlj faster than me spot out the bug :)

**Comment by Syphurith** [comment]
@raven02 well maybe you would need to download many versions of the executable. Good luck.

**Comment by tambry** [comment]
@raven02 @vlj Has this been fixed?

**Comment by vlj** [comment]
It was fixed in GL but now it's broken again (but in a different way).
D3D12 is fine.

**Comment by tambry** [comment]
Still an issue?

**Comment by raven02** [comment]
Fine now .Closed
