### ISSUE TITLE
Call of Duty 3 Crash

### ISSUE THREAD

**Issue by gamerfreak147** [RPCS3/rpcs3#9666]
Game freezes within a minute of gameplay on several levels. Levels 2-5 it has crashed for me.

    System:
    OS: Windows 10 (20H2)
    CPU: Intel i9-9900K
    GPU: Nvidia GTX-2080ti / driver 460.79
    Default settings; Vulkan

Broken #11619
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5884064/RPCS3.log)

Crashed once on #11605 couldn't get it to crash again.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5884137/RPCS3.log)

Working #11603
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5884130/RPCS3.log)

**Comment by RainbowCookie32** [comment]
Is this still an issue?

Also, assuming correct bisecting, issue was introduced on 0.0.14-11619 (#9613, seems weird considering the fatal is related to shader compilation).

The error itself:

```
·F 0:02:25.562594 {RSX [0x0345f00]} SIG: Thread terminated due to fatal error: Unknown register name: unk
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKCommonDecompiler.cpp:151[:23], in function get_varying_register_location)
```

**Comment by gamerfreak147** [comment]
Tested it on #12060 did not crash.

**Comment by RainbowCookie32** [comment]
So this is fixed? Close the issue then.

**Comment by gamerfreak147** [comment]
Yeah, you can close it.

**Comment by RainbowCookie32** [comment]
_You can close it yourself with that nice red button_
