### ISSUE TITLE
Regression: Uncharted 2 Title Screen Flickering with WCB (#9613)

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#9668]
When WCB is enabled, Uncharted 2's title screen now flickers between having proper and broken lighting.
Confirmed to be caused by: https://github.com/RPCS3/rpcs3/pull/9613

Tried to capture a renderdoc but it kept freezing, RSX capture wasn't working either. At least it's easy to reproduce.
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5886040/RPCS3.log.gz)

Unknown if it affects AMD GPU's as well.

**Comment by sampletext32** [comment]
Please check the mentioned PR id, 9648 is an issue.

**Comment by Asinin3** [comment]
Closing. Caused by mesh trimming patch but it did only start happening after that pr merged.
