### ISSUE TITLE
Skate 3 running at 1-2 FPS after (#9640)

### ISSUE THREAD

**Issue by AphelionWasTaken** [RPCS3/rpcs3#9675]
## Quick summary
Skate 3 is now running at single-digit FPS after PR #9640

## Details
Pretty self-explanatory. The build causing this issue has already been marked as "bad", but this issue is persisting in the current master build. 

log is spamming semaphore timeout errors with multiple addresses, example:
`E {RSX [0x0082940]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x50300410`

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
Broken by: PR #9640 - build 0.0.14-11636-06528702 Alpha
Last working build: PR #9667 - build 0.0.14-11635-67dd6754 Alpha

#### 2. Please attach TWO logs:
Broken build: [RPCS3 - 9640.log](https://github.com/RPCS3/rpcs3/files/5891534/RPCS3.-.9640.log)
Last working build: [RPCS3 - 9667.log](https://github.com/RPCS3/rpcs3/files/5891539/RPCS3.-.9667.log)

#### 4. Please attach screenshots of your problem.
<img width="961" alt="Untitled" src="https://user-images.githubusercontent.com/61633628/106230038-4552e480-61b4-11eb-99a3-d93d65a15ba2.png">

#### 6. Please provide your system configuration:
* OS - Windows 10
* CPU - 9900K
* GPU - 3080
* Driver version 460.79.0.0

**Comment by MSuih** [comment]
@elad335 can you look into this issue? Seems like your debugger changes broke rsx synchronization.

**Comment by elad335** [comment]
Fixed by #9677
