### ISSUE TITLE
[Feature Request] Multithreaded (multi-files) overlay modules precompilation

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#9694]
Only one overlay file can be precompiled at a time at the moment, unlike PRX.
This is inefficient for small OVL files with little amount of modules in each, so not all threads are being utilized as they should for it.
Memory management of OVL precompilation is completely single threaded because of it as well, which is not desired.

**Comment by dio-gh** [comment]
Could you provide some insight on this? Is the compilation of overlay modules IO bound or something, that it won't saturate people's CPU cores the way things are right now (with PPU modules already compiling in a multithreaded fashion)? Or what's the rationale here?

**Comment by elad335** [comment]
The issue is that only one overlay file can be precompiled at a time, unlike PRX.

**Comment by Megamouse** [comment]
Please just write a description in the op.
1. Current state with short explanation.
2. Ideal state

**Comment by elad335** [comment]
I will close it because it was tested and it performed worse under Windows. Implementation is quite accessible in the future due to a recent rewrite. (commenting single mutex guard)
