### ISSUE TITLE
KILLER IS DEAD [BLUS31186] won't boot on new builds

### ISSUE THREAD

**Issue by Basmurd** [RPCS3/rpcs3#9700]
After compile PPU modules game not boot at all. On logs F {PPU[0x1000000] Thread (main_thread) [0x00092f58]} VM: Access violation reading location 0x0 (unmapped memory) [type=u0].

**Comment by Nekotekina** [comment]
Can you tell what build introduced the regression? You can download any build and test.

**Comment by Basmurd** [comment]
> Can you tell what build introduced the regression? You can download any build and test.

Last boot on 0.0.12-10857 and older.

**Comment by Megamouse** [comment]
log missing

**Comment by digitaldude555** [comment]
![Screenshot (311)](https://user-images.githubusercontent.com/26138653/107038290-f82ece00-67c4-11eb-9426-0685eb093dfc.png)
Working on latest master here.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5932854/RPCS3.log.gz)

**Comment by Basmurd** [comment]
Here the log on my hardware.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5936483/RPCS3.log)
![rpcs3_KKy8Vx2YD3](https://user-images.githubusercontent.com/61318181/107113112-dd646400-686d-11eb-963b-20ea605972ff.png)
