### ISSUE TITLE
Demon's Souls [BLES00932] segfaults on launch since 58eef983e23

### ISSUE THREAD

**Issue by Oschowa** [RPCS3/rpcs3#9704]
## Quick summary
Title.

## Details
```
·F 0:00:25.988856 {PPU[0x1000000] Thread (main_thread) [0x0001c530]} SIG: Thread terminated due to fatal error: Segfault executing location 00000004016c9f50 at 00000004016c9f50.
```

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
first bad commit: 58eef983e23c
reverting 58eef983e23c on master makes it work again, it's also broken with the latest appimage rpcs3-v0.0.14-11676-8c6aa9db

#### 2. Please attach TWO logs:
[RPCS3_bad.log](https://github.com/RPCS3/rpcs3/files/5907158/RPCS3_bad.log)
[RPCS3_good.log](https://github.com/RPCS3/rpcs3/files/5907168/RPCS3_good.log)

#### 6. Please provide your system configuration:
* Arch Linux
* Ryzen 3700x
* RX580
* RADV from git

used config: 
[config_BLES00932.yml.txt](https://github.com/RPCS3/rpcs3/files/5907179/config_BLES00932.yml.txt)
patches:
[patch_config.yml.txt](https://github.com/RPCS3/rpcs3/files/5907181/patch_config.yml.txt)

**Comment by YuriNator557** [comment]
Regression happens specifically in v0.0.14-11675-58eef983.

[RPCS3_bad.log](https://github.com/RPCS3/rpcs3/files/5907298/RPCS3_bad.log)
[RPCS3_good.log](https://github.com/RPCS3/rpcs3/files/5907300/RPCS3_good.log)

**Comment by YuriNator557** [comment]
> Regression happens specifically in v0.0.14-11675-58eef983.
> 
> [RPCS3_bad.log](https://github.com/RPCS3/rpcs3/files/5907298/RPCS3_bad.log)
> [RPCS3_good.log](https://github.com/RPCS3/rpcs3/files/5907300/RPCS3_good.log)

oops, didn't realise that the commit was referenced already

**Comment by Satan86** [comment]
Apparently the crash only happens when the Unlock FPS patch is enabled

**Comment by elad335** [comment]
Test #9706

**Comment by Oschowa** [comment]
Fixed with 08aaae79, thanks!

**Comment by Nekotekina** [comment]
@Oschowa hi, can you test https://github.com/RPCS3/rpcs3/pull/9709

**Comment by Oschowa** [comment]
Crashes again 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5913860/RPCS3.log)

**Comment by Nekotekina** [comment]
@Oschowa hello, I made some changes in that PR, maybe it will work now?

**Comment by Oschowa** [comment]
@Nekotekina It gets further but still crashes when it reaches the intro cutscene  
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5936921/RPCS3.log.gz)

**Comment by Nekotekina** [comment]
@Oschowa Interesting, I think I figured it out. Try next commit please.

**Comment by Oschowa** [comment]
Commented on the PR.
