### ISSUE TITLE
 persistent startup errors

### ISSUE THREAD

**Issue by sett-xp** [RPCS3/rpcs3#9711]
E SIG: Thread [RSX.W1] is too sleepy. Took 4.380µs to wake it up!
E SIG: Thread [RSX.W2] is too sleepy. Took 5.480µs to wake it up!
E SIG: Thread [RSX.W3] is too sleepy. Took 5.100µs to wake it up!
E SIG: Thread [RSX.W4] is too sleepy. Took 5.360µs to wake it up!
E SIG: Thread [Usb Manager Thread] is too sleepy. Took 1.190µs to wake it up!
E {SPU LLVM} SIG: Thread [SPU LLVM Profiler] is too sleepy. Took 5.150µs to wake it up!
E SIG: Thread [SPU LLVM] is too sleepy. Took 3.320µs to wake it up!
E SIG: Thread [MsgDialog Close Thread] is too sleepy. Took 4.530µs to wake it up!
E SIG: Thread [CPU Profiler] is too sleepy. Took 4.240µs to wake it up!

these errors appear every time! launched in the game GT-6

when launching ps1 games errors

E {PPU[0x1000000] Thread (main_thread) [0x0007a898]} SYS: 'sys_event_port_connect_ipc' failed with 0x80010005 : CELL_ESRCH [1]
U {PPU[0x1000000] Thread (main_thread) [HLE:0x01df0b4c, LR:0x0004a6ec]} cellSysutil TODO: cellAudioOutGetDeviceInfo(audioOut=0, deviceIndex=0, info=*0xd0010908)
E {PPU[0x1000000] Thread (main_thread) [0x0011b33c]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_flash/data/font/SCE-PS3-RD-R-LATIN2.ccd” [1]
E {PPU[0x1000000] Thread (main_thread) [0x0011b33c]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_flash/data/font/SCE-PS3-NR-R-JPN.ccd” [1]
E {PPU[0x1000000] Thread (main_thread) [0x0011b33c]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_flash/data/font/SCE-PS3-YG-R-KOR.ccd” [1]
E {PPU[0x1000000] Thread (main_thread) [0x0011b33c]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_flash/data/font/SCE-PS3-DH-R-CGB.ccd” [1]
E {PPU[0x1000000] Thread (main_thread) [0x0011b33c]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/SLUS00715/USRDIR/CONTENT/DOCUMENT.DAT” [1]
U {PPU[0x1000005] Thread (_xcdrom_thread) [0x0201ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000005] Thread (_xcdrom_thread) [0x0201ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
E {PPU[0x1000000] Thread (main_thread) [0x0011b33c]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/SLUS00715/USRDIR/CONFIG” [1]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x01df67dc, LR:0x00029084]} SYS: 'cellPadSetActDirect' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [1]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x01df67dc, LR:0x00029084]} SYS: 'cellPadSetActDirect' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [2]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x01df67dc, LR:0x00029084]} SYS: 'cellPadSetActDirect' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [3]

E {PPU[0x1000000] main_thread } SYS: Stat: 'cellPadSetActDirect' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [x7]
E {PPU[0x1000008] Thread (_libadec_at3SpursHdlr0) [0x02015ae0]} SYS: '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000006] Thread (_xMcThread) [0x00029a60]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000002] Thread (MenuThread) [0x0004fbe4]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000007] Thread (_libadec_at3SpursHdlr1) [0x0212b604]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000004] Thread (libusbd_usbd_thread) [0x001124a8]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000005] Thread (_xcdrom_thread) [0x0004ebac]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000003] Thread (libusbd_callback_thread) [0x00115b50]} SYS: 'sys_usbd_receive_event' failed with 0x00000000 : 0 [1]
E {PPU[0x100000a] Thread (_PSPiStorageThread) [0x000387e4]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000001] Thread (_gcm_intr_thread) [0x0007aaf8]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000009] Thread (_at3dec_adapter_decode_thr_) [0x02183384]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]

RPCS3 v0.0.14-11683-714eb6dc Alpha | HEAD | Firmware version: 4.87
AMD Ryzen 5 1600 Six-Core Processor | 12 Threads | 7.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
Operating system: Windows, Major: 10,  Build: 19042, Service Pack: none, Compatibility mode: 0
RSX: Found vulkan-compatible GPU: 'GeForce GT 1030' running on driver 461.40

**Comment by MSuih** [comment]
If you do not understand the messages in log, then don't pay attention to them. If you want to ask about what they mean, join the Discord server and don't open useless issues. If you need help with the emulator, use the appropriate support channels.

---

@Nekotekina Could we hide the "X is too sleepy" messages? (move from error to warning) They're causing a lot of confusion as they appear every time a process finishes and do not contain any useful information to end users.

**Comment by Nekotekina** [comment]
@MSuih some of them were supposed to be fixed by one of the elad's PRs, so I didn't touch them.
