### ISSUE TITLE
Connecting second DualSense resets device assignment

### ISSUE THREAD

**Issue by sampletext32** [RPCS3/rpcs3#9719]
## Quick summary
Connecting second DualSense controller via USB (both via USB) resets device assignment, input for `DualSense Pad 1` comes from last connected controller, not the actually `Pad 1`

## Details

`DualSense Pad 1` starts receiving input from second controller, and first one is left abandoned.

May be relevant: I connect first controller via TypeC port -> OTG -> USB to TypeC cable -> controller, and second via normal USB port -> Usb to TypeC cable -> controller.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5929453/RPCS3.log)

#### 5. Please provide your system configuration:
Test purposes laptop (irrelevant for the issue).
* Win 10
* Core I5 10210U
* NVidia MX250 2G
* Driver 460.79.0.0
* etc.

#### Please include.
Any additionals test for you is a pleasure

**Comment by sampletext32** [comment]
Doesn't happen, when connected both via Bluetooth

**Comment by sampletext32** [comment]
Strange behavior: when first controller is connected via USB and second via Bluetooth, everything is normal, input is not lost.
But when first controller is via Bluetooth and second via USB, `DualSense Pad 1` starts receiving from USB controller

**Comment by sampletext32** [comment]
btw, seems similar to #7412

**Comment by Megamouse** [comment]
Closing as duplicate
