### ISSUE TITLE
VFS layer doesn't respect user locations, or installing to /usr/bin doesn't work with linux

### ISSUE THREAD

**Issue by chaoskagami** [RPCS3/rpcs3#972]
This piece of code is the offender in rpcs3/Emu/FS/VFS.cpp (maybe):

                // TODO: This shouldn't use current dir
                fmt::Replace(mpath, "$(EmulatorDir)", Emu.GetEmulatorPath());
                fmt::Replace(mpath, "$(GameDir)", cwd);

I'm not sure what upstreaming standards are here, but I'm maintaining an ebuild in my gentoo overlay, and considering where the binary ends up, this is a big issue on gentoo and linux in general.

We need a way to install to a prefix and not run only from folders.

**Comment by paulsapps** [comment]
wouldn't use that ini config file class I've seen hanging around be better solution? That would work for all platforms too.

**Comment by chaoskagami** [comment]
Whatever the best solution is, provided it can be adapted for rpcs3 to allow being located inside /usr/bin and not attempting to install packages to the cwd. I haven't seen the ini config, since I've mostly been watching the github rather than emunews

Also, apparently my patch doesn't actually work after testing. This is still an issue though. Directories can be manually configured, but it's kind of a pain.

**Comment by latot** [comment]
Hi, if some one can test this patch for linux plis, is the fix of the patch the @chaoskagami , https://github.com/latot/rpcs3/commit/bd3561ab3bd51b383f698f85e4a2d4dcb6990ffb
working for me, and now can run with optimus.

**Comment by chaoskagami** [comment]
From the author of that crappy patch himself - no, that is not okay to apply globally. It was a hacky fix for linux, and will function abnormally for every other configuration. Come up with something better. In fact, I'll remove the pastebin link since I don't think it works correctly to resolve the VFS issue even then.

I'll repeat - that patch should not be merged. Period.

**Comment by Syphurith** [comment]
@chaoskagami so what you expected is a patch that calls OS for `which rpcs3` or similiar to get where rpcs3 really is. Or you want an option to setup the RootDir for rpcs3 (sounds better maybe)?

**Comment by chaoskagami** [comment]
@Syphurith - Not exactly. _which rpcs3_ would only work if it's in the path. The issue is that the ini file by default considers RootDir to be the same as the current location of the executable. Not only does the current build script not allow for system-wide installation (e.g. cmake -DCMAKE_INSTALL_PREFIX=/usr, there's not even an install) but having the default ini attempt to install packages to /usr/bin/hddx is unacceptable. It also doesn't allow for putting a default ini in a system-wide config directory like /etc.

On Windows and Mac this is largely not an issue. An editable box is okay. Both of those systems don't have the same concept of system-wide versus user-only like linux. And if I run it from a folder, this isn't an issue. However, it prevents any form of proper packaging, because the default settings in those boxes NEED to be changed by the user unless they like permission denied spam and incorrect behavior.

I would propose properly checking for CMAKE_INSTALL_PREFIX and adjusting either the default ini or the way it considers paths accordingly. This is how most software works.

**Comment by Syphurith** [comment]
@chaoskagami Well install to /usr/bin/.... is quite unacceptable i know.
I wanna know where is your `rpcs3.ini` file. Just edit the INI would be easier to implement..

**Comment by chaoskagami** [comment]
I'm really not sure why asking for my ini has any relevance to this issue, since this is a problem against the default configuration and build system.

My ini seems to get dropped in the default location - ~/.config/rpcs3. I find it strange that config files get dropped there, but not HDD data. Regardless, it makes no difference. What if a user wants to install to /usr/local? /opt? /thisrandomfolder? Mine only covers redirecting to my home folder.

Specifically, what needs to happen - $(EmulatorDir) can redirect to the executable's location in a unpack or self-contained install, but it should go to ~/.config/rpcs3 in a system wide install. Right now, it's parsed simply as 'Get executable location' which gives /usr/bin if the binary is in /usr/bin.

**Comment by Syphurith** [comment]
I asked for its location only to ensure that is easily accessable path that don't need priviledges.
Thus, you could have a choice:
* let those HDD be with in the same folder with your rpcs3 ini file.
* let it read the INI and find setting for the actual EmulationDir.
* wait for someone make an option for you with Graphic UI.

That's it. 'Cause i have not enough skill/exp. with UI, i may not be the guy in the 3rd choice.

**Comment by tambry** [comment]
@chaoskagami Is this still an issue?

**Comment by chaoskagami** [comment]
I haven't been playing around with rpcs3 much lately, but I'll re-clone the source and test.

**Comment by chaoskagami** [comment]
Apparently, it's impossible to build at the moment due to lack of precompiled header support in my current compiler. Looking at the code in PR #1060, this should be fixed, although may require user configuration. I can't be sure until I rebuild gcc so I can build rpcs3.

The joys of using a handmade LFS system. (sarcasm)

**Comment by latot** [comment]
i can't compile too...

**Comment by tambry** [comment]
@latot What's the problem, with compiling, for you?

**Comment by latot** [comment]
nothing, was a problem in my system, i forget rpcs3 use wxwidgets-3 and was using 2.8, i change it and works fine, are some way to check from cmake the wx version?

**Comment by tambry** [comment]
@chaoskagami Have you managed to build and confirm, that this is fixed? You could also try asking someone to build one for you.

**Comment by chaoskagami** [comment]
Unfortunately, no. My system LLVM is 3.7 and is apparently incompatible with rpcs3 due to removed code. I can't/will not downgrade since literally my entire graphics stack is built against it.

Kinda stuck, sorry. Unless someone else is capable of verifying this, I can't help much.

I honestly haven't been keeping up with rpcs3 lately, so if you want to close this report it's fine. I can't test until rpcs3 is made compatible with 3.7.

**Comment by tambry** [comment]
@chaoskagami I'll look into updating RPCS to LLVM 3.7, if it's not very hard.

**Comment by latot** [comment]
mm, i try this, rpcs3 show the option to change the eulationdir but don't works fine, i try change but don't works, the dir don't show any change after a restart.

**Comment by Zangetsu38** [comment]
@tambry I have already try this, But i have several problem 
https://github.com/Zangetsu38/rpcs3/tree/llvm37

**Comment by danilaml** [comment]
@tambry I had something done back in July (warning: "dirty" branch, haven't properly orgonized commits): https://github.com/danilaml/rpcs3/commit/4ab4b013360ddb7396d8007aad411e3f8c18a881

**Comment by chaoskagami** [comment]
@danilaml I'm not a fan of the whole #defining method of getting things to work. Seems like a compatibility hack. I also notice you enabled the test suite and then COMMENTED the entire thing. Seriously, disabling is one thing, but just use `#if 0 #endif` next time you need to disable large blocks of code. *cringes* That said, does your branch work, since @Zangetsu38 says his branch has issues? And what are the issues there, @Zangetsu38?

Something tells me the LLVM issue needs its own issue at this point, unless there's a reason to not upgrade.

**Comment by danilaml** [comment]
@chaoskagami As I said, it was a test branch done a long time ago. Back then MCJIT had certain issues and I did it to see if llvm3.7 (not yet released at the time) fixed them. Since it didn't I abandoned it.
The main issue is that llvm guys decided to remove CreateCallN (for N args) and leave only CreateCall(..., ArrayRef). Manually replacing numerous (~100) appearances of calln with call(..., {args}) was problematic so I just did quick a dirty define hack.

**Comment by chaoskagami** [comment]
I went through the LLVM headers to verify when I posted, I just didn't feel like making a fix. But yeah, by 'removed code' I primarily meant CreateCallN. Those functions have been marked for deprecation for a while, before they were even deleted.

Anyways, I'll attempt to rebase @danilaml's tree onto master and build to see if the primary issue here with directories is fixed.

**Comment by danilaml** [comment]
@chaoskagami I suggest just taking `PPULLVMRecompilerXXXX` changes. Rebasing would be more troublesome, since there were a lot of changes to rpcs3 (and llvm back-end specifically) since July (and also not very clean state of that working branch).
