### ISSUE TITLE
Slowness after update (Yakuza 5)

### ISSUE THREAD

**Issue by Kultigin123** [RPCS3/rpcs3#9724]
Although it was 30 FPS after the update, Yakuza 5's cinematics freezes, in-game freezes occur.

**Comment by MSuih** [comment]
Missing: emulator version which caused the regression and log files from both versions

**Comment by Kultigin123** [comment]
Version 0.0.14-11688
Log ; 
RPCS3 v0.0.14-11688-7e0fdbbe Alpha | HEAD | Firmware version: 4.87
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz | 12 Threads | 7.81 GiB RAM | TSC: 2.592GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19042, Service Pack: none, Compatibility mode: 0
Qt version: Compiled against Qt 5.15.2 | Run-time uses Qt 5.15.2
·! 0:00:00.000000 SIG: Thread time: 0.000000s (0.001163Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]
·! 0:00:00.005941 SYS: Initialization times before main(): 0.150985Gc
·A 0:00:00.581170 RSX: Found vulkan-compatible GPU: 'GeForce GTX 1650' running on driver 461.40.0.0
·A 0:00:00.581191 RSX: Found vulkan-compatible GPU: 'Intel(R) UHD Graphics 630' running on driver 0.402.976
·! 0:00:00.588869 CFG: Setting the default renderer to Vulkan. Default GPU: 'GeForce GTX 1650')
·! 0:00:00.594510 SYS: Logged in as user '00000001' with the username 'User'
·! 0:00:00.633595 GUI: Current language changed to English (en)
·! 0:00:01.026871 Compat: Finished reading database from file: C:/Users/name/Downloads/rpcs3-v0.0.13-11470-567d23d8_win64/GuiConfigs/compat_database.dat
·! 0:00:02.783695 SYS: Option passed via command line: updating = 
·! 0:00:02.783722 SYS: Booting application from command line: Paris
·! 0:00:02.783732 SYS: Optional command line argument 1: Balkıs\Downloads\rpcs3-v0.0.13-11470-567d23d8_win64\rpcs3.exe
·E 0:00:02.797526 SYS: Booting 'C:/Users/name/Downloads/rpcs3-v0.0.13-11470-567d23d8_win64/Paris' with cli argument failed: reason: Invalid file or folder
·E 0:00:14.137611 NETWORK: Curl error: Couldn't resolve host name
·! 0:01:56.491925 {Progress Dialog Server} SIG: Thread time: 0.000000s (1.141159Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]; Wait:[0.000s, spur:0]

**Comment by MSuih** [comment]
log FILES, not copypaste from emulator window

**Comment by Kultigin123** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5932375/RPCS3.log)

**Comment by 13xforever** [comment]
ok, let's try slowly
2 (TWO) log files
one for the last good version, and one for the first bad version
log files of the running game, not empty files of simply opening the emulator

**Comment by MsDarkLow** [comment]
Just tested Yakuza 5 on my system and performance is still exactly the same as a couple months ago, which is good.
Please provide more information about your issue and bisect the build that made occur your problem (just like 13xforever mentioned), otherwise close the issue.
Tested without any patches on one of the heaviest sceneries.
![hidiscordusers](https://user-images.githubusercontent.com/9060436/107069451-e86db480-67d9-11eb-868c-e8c345b4e25f.jpg)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5934306/RPCS3.log.gz)

**Comment by Kultigin123** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5953176/RPCS3.log)

**Comment by Kultigin123** [comment]
[Uploading RPCS3.log…]()

**Comment by Kultigin123** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5953190/RPCS3.log)
Sorry ı'm late but ı have log file
