### ISSUE TITLE
All Pro Football 2k8 [BLUS30049] weird rendering

### ISSUE THREAD

**Issue by belezaW** [RPCS3/rpcs3#9729]
Player and uniform models won't properly render when I'm choosing players for a team. 

It only happens in the creating teams menus. In other menus there's just no models at all, and in some menus they look fine.   But in game they're completely normal.

I'm new to RPCS3, I'd appreciate some help.

![apf2k8bug](https://user-images.githubusercontent.com/78632261/107108999-72754780-67f1-11eb-87ce-b1e45debc7bb.png)

![apf2k8bug2](https://user-images.githubusercontent.com/78632261/107109221-2f1bd880-67f3-11eb-8013-2e43fd73f63a.png)

I have an AMD Ryzen 5-2600 CPU and a Nvidia GeForce GTX 1060 graphics card.

**Comment by digitaldude555** [comment]
You just didnt enable write color buffers, its not an issue.
![Screenshot (319)](https://user-images.githubusercontent.com/26138653/107116934-6afc7f80-687f-11eb-8794-c284d9047f15.png)
![Screenshot (320)](https://user-images.githubusercontent.com/26138653/107116935-6cc64300-687f-11eb-86a6-7338bf7ca3f5.png)

**Comment by belezaW** [comment]
@digitaldude555 

Thank you for your advice, but I already had that option enabled.

**Comment by digitaldude555** [comment]
I have the exact same gpu as you, so it might be a driver issue for you.

**Comment by paidneverfull** [comment]
> Player and uniform models won't properly render when I'm choosing players for a team.
> 
> It only happens in the creating teams menus. In other menus there's just no models at all, and in some menus they look fine. But in game they're completely normal.
> 
> I'm new to RPCS3, I'd appreciate some help.
> 
> ![apf2k8bug](https://user-images.githubusercontent.com/78632261/107108999-72754780-67f1-11eb-87ce-b1e45debc7bb.png)
> 
> ![apf2k8bug2](https://user-images.githubusercontent.com/78632261/107109221-2f1bd880-67f3-11eb-8013-2e43fd73f63a.png)
> 
> I have an AMD Ryzen 5-2600 CPU and a Nvidia GeForce GTX 1060 graphics card

**Comment by paidneverfull** [comment]
Excuse me were you able to solve the  issue with the players and models that won’t showing up properly?
