### ISSUE TITLE
Dengenki Bunko Fighting Climax Ignition(NPJB00785) multiplayer doesn't work

### ISSUE THREAD

**Issue by YJSNPI1145141919** [RPCS3/rpcs3#9733]
After logging in through RPCN,the game could access the network mode ,search and see other players'room
if a network problem appear when accessing the room,there will be an in-game error, but the game goes on.
**but when there's no network problem , the RPCS3 will stuck , it seems room accessing is ok,but it just doesn't work**

```
RPCS3 FAILURE Log:
F {PPU[0x1000000] Thread (main_thread) [HLE:0x0111601c, LR:0x000f32cc]} sceNp2: 
sceNpMatching2SignalingGetConnectionInfo Unimplemented code: 4

RPCS3 Version:
 0.0.14-11698-fad89f1c Alpha
```

**Comment by nitroos-ai** [comment]
Is it fixed now?

**Comment by Ninetime** [comment]
This is working as of RPCN 0.6 #12073
