### ISSUE TITLE
Textures and/or MLAA regressions in AMY

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#9736]
This game introduce severe bugs now : glitches,flickering,glitches,textures.
I'm wondering if the MLAA fixes made this happens.
Windows 10,GTX 1080 (last drivers) and I9 9900KF
![IMG_8509](https://user-images.githubusercontent.com/67762812/107146008-b8432480-6945-11eb-8c13-8890fbc95eec.JPG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5938947/RPCS3.log.gz)

**Comment by Asinin3** [comment]
`This game introduce severe bugs now`
Sounds like you're saying it was working before. In which case this means you're making a regression report... Which means you need to find what build broke it. Check your settings first. I see similar pink issue on forum in a very old test: https://forums.rpcs3.net/thread-177015-post-292101.html#pid292101

Maybe its setting related. Did you try 100% res scale?

**Comment by Pouncha** [comment]
I tried differents settings for the same results.WCB ON,WCB OFF,LLVM,ASMJIT,...bugs still present and yes,they wasn't here before (but I can't remember when exactly coz I tested this game just yesterday after a long time).
I also tried 100% rescale like I tried strict rendering mode or Vsync,or disable Vertex,...
Another bugs on this game that it makes new config's save folder each time you launch it : the result is if you play 10 times,you'll get 20 folders on your HDD0 folder...
You seems to get right with the related post : the pics I saw are similar,so maybe you can close mine (but notice the save bug) and wait fort fix.

**Comment by Pouncha** [comment]
I tested it with OpenGL : No graphical pbs but only serious FPS drops (around 10-17 fps)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5951280/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Not a regression as shown by the 2017 forum post

If there is indeed a regression you need to file a Regression Report following the template for one

**Comment by mysteria25** [comment]
confirmed the regression of this game was caused by #9613

**Comment by mysteria25** [comment]
@kd-11  confirmed the regression of this game was caused by #9613

AMY NPUB30613:
0.0.14-11605- works fine
0.0.14-11619- flickering graphics/textures

(nvidia Pascal GPU, Vulkan, Windows 10)

**Comment by mannyca05** [comment]
Lana (main character) flickers when near any light source + every time I close the game it gives me fatal error message.

[RPCS3.zip](https://github.com/user-attachments/files/23017884/RPCS3.zip)

https://github.com/user-attachments/assets/80651034-51c6-41ff-91a9-8763804fae6f

<img width="793" height="262" alt="Image" src="https://github.com/user-attachments/assets/e23aa3fc-fc77-4b17-83fc-9ccbd541cad1" />

**Comment by kd-11** [comment]
@mannyca05 Create a new ticket, this is clearly a different issue.
