### ISSUE TITLE
The Last of Us BCES01585 v01.11

### ISSUE THREAD

**Issue by sett-xp** [RPCS3/rpcs3#9747]
no played game -code error

{PPU[0x1000000] Thread (main_thread) [0x00af055c]} VM: Access violation reading location 0x0 (unmapped memory) [type=u32]
{PPU[0x1000000] Thread (main_thread) [0x009e9540]} VM: Access violation reading location 0x0 (unmapped memory) [type=u32]

**Comment by sett-xp** [comment]
this is the third time when you don’t explain why I can’t talk about it, just blocking messages!

**Comment by sett-xp** [comment]
I can't see all the messages that are sent to you and I only want to help, but you just took it and blocked it without explanation!

**Comment by AniLeo** [comment]
You were answered on one of your previous issues plus there are guidelines in the repository to follow that also appear when creating an issue

Furthermore none of your issues are reply locked, that's why you're able to comment in the first place

**Comment by sett-xp** [comment]
you just closed a topic! the game just freezes at the beginning of the launch, to start it came and showed what I see - maybe it will help - if it didn't help or you think that the topic is irrelevant .. just erase the messages. Yes, I'm not a programmer, but isn't it in this thread to go to support? You talked about discord before, yes, I was there, but I can't write anything there!

**Comment by AniLeo** [comment]
I closed it because you ignored the issue guidelines in the repository which are also a template when you create an issue.
Yes, this isn't the place to go for support, this is an issue tracker, not a help desk, we have other platforms for support.
You can write in Discord after 10 minutes of joining the server.

**Comment by sett-xp** [comment]
thanks for your patience - a good time of day.
