### ISSUE TITLE
Little Big Planet 3 can't support upsacling anymore

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#9751]
I tested LBP 3 some month ago and it was working with a 200% resolution scale (2K).
Now,I must put settings on 'Strict Rendering Mode'  coz,if not, the meulator crashes (and it's no possible to send a log coz of this crash).

**Comment by MSuih** [comment]
You can always send a log file. If the compressed log disappears, the uncompressed version will remain. Compress it manually and upload to here.

Also it would be vital to know which exact emulator version caused this regression.

**Comment by Pouncha** [comment]
Ok,sorry for didn't notice that.
So,I could make a log (zip format).
IUnfortunatly,I can't saiy exactly the emulator version which changes it (I test games when I can find time for that).
But,I found that  the game made a file in USERDIR directory from july 2019.So,maybe it's around this emulator version time.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5951369/RPCS3.zip)

**Comment by AniLeo** [comment]
Does not follow the Regression Report template
https://github.com/RPCS3/rpcs3/blob/master/.github/ISSUE_TEMPLATE/1-regression-report.md

Does not indicate which build broke the issue you're describing, which is one of the main things we need to know
