### ISSUE TITLE
Conflicts/violation memory access between Threads and/or Shader Hints compilation

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#9753]
It's difficult to explain but I took the MGS4's example to explain.
In this game,I needed to restart it 5 times before getting it as playable.
During these retries,I noticed that  the game crashed each time it made shaders compilation in memory and back them to work with PPU threads already compiled.
I know that MGS4 is not perfectly playable yet but maybe you'll find here a way to improve the emulator.
I used Recompiler LLVM for PPU and SPU,TSX enable,200% upscaling and nothing more (Zcull relaxing make the game crashes all the time,so I disable it).
Windows 10 with I9 9900KF,GTX 1080 (last drivers) and 32go RAM.
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/5951963/RPCS3.log.zip)

**Comment by Asinin3** [comment]
This issue doesn't help developers find an issue. As such it's not relevant for our issue tracker. If you want support use https://discord.me/rpcs3 GitHub is messy enough as it is.
