### ISSUE TITLE
I've tried everything and I can't get Madden 25 to work

### ISSUE THREAD

**Issue by BigScrungus** [RPCS3/rpcs3#9758]
Every f**king time it's a different error code and I have to go down another rabbit hole. I have two different versions of RPCS3 installed on my computer at this point, one for College Football Revamped and a much earlier one for Madden 25 because Madden 25 is COMPLETELY unplayable on newer versions. Sometimes the game freezes when going loading a franchise game. Sometimes it freezes just prior to kickoff. Sometimes it only freezes if I use custom playbooks. Once it ran perfectly and then froze on the loading screen after the game.

I have a 2070 Max Q and can run Cyberpunk on max settings, so it isn't my computers problem

First I started out trying to use the settings and the RPCS3 version here that chidreams uses here, but to no avail. It would let me play some franchise games, but not others. Sometimes it would freeze loading into the game when using a custom playbook and force me to have to use default playbooks. Other times it would freeze on loading while using default playbooks. *I am still using and tweaking version 0.0. 10-10518* because it is the only one I've tried that has been playable. https://forums.rpcs3.net/thread-189158-page-2.html**

I found one thread on github suggesting that I turn on Write Depth Buffers and Read Color Buffers, and that had the game running the best it has ever ran (even let me use a custom playbook on a franchise game that would previously crash when attempting to do so) but then it froze on the loading screen AFTER the game, which led me to this thread: https://github.com/RPCS3/rpcs3/issues/8047

I attempted the config tweak posted there by Ghostotakoi by editing the config.yml and changing
LLVM Accurate DFMA: 'True' to 'false.' 
Doing so made things substantially worse, and changing the setting back hasn't fixed this, so I am currently stuck in purgatory.  85% of the time the game will crash loading into a franchise game, and if it gets past that, it will crash after the coin toss cutscene transitions into a kickoff. 

I want to try using this fix: https://github.com/RPCS3/rpcs3/pull/8066

but I know nothing about code and can't figure out how to download it.

Here's the log of my most recent crash, during loading into a game: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/5958758/RPCS3.log)

Someone please help before I pull my hair out. I just want to be able to play Madden 25 with imported draft classes from College Football Revamped, and doing so is proving to be so much more complicated than I bargained for.

**Comment by AniLeo** [comment]
If you want to ask for support, then you need to use one of the support platforms, not the issue tracker

If you have the game working on an older build and it doesn't work on a newer one you can submit a [Regression Report](https://github.com/RPCS3/rpcs3/blob/master/.github/ISSUE_TEMPLATE/1-regression-report.md)

---

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
