### ISSUE TITLE
Regression: Car missing hood on Gran Turismo 5 (#9377)

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#9765]
After 0.0.13-11347-3a0b3a85 (#9377), the Ford Mustang GT's hood goes missing. More cars could be affected, but it's pretty hard going through 1000+ others. Worth noting that it only happens with the red colour.
![Screenshot_47](https://user-images.githubusercontent.com/61447828/107752503-9a870e00-6cfd-11eb-98a6-c724a5f95008.png)
It's also missing in the garage, dealerships, etc. Easiest way to view the car is by the dealerships in GT Mode, Ford manufacturer. Hood is present on OGL 
RSX capture: https://drive.google.com/file/d/1rdoaCqHU7dDmnT5nq9knUBBPxkb-dE4J/view?usp=sharing
log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5971023/RPCS3.log.gz)
5600x, 1050 ti driver version 461.40, win 10 20H2

**Comment by xddxd** [comment]
![image](https://user-images.githubusercontent.com/1712979/108254335-8c087e80-7163-11eb-892a-dce81a383f8a.png)
Can't repro here. Nvidia only bug?

**Comment by xddxd** [comment]
So while the mustang is fine on AMD, another car's hood was broken by this PR. The hood of the red M3 is silver when looking at the front of the car. To repro, get a red M3, go to arcade, world tracks, la sarthe. Then look at the car like in the picture.
![Screenshot_14](https://user-images.githubusercontent.com/1712979/111011313-a409a180-83a1-11eb-8517-691d0e03d65d.png)
RRC: https://www.dropbox.com/s/mfxv57srublu8c4/BCES00569_20210313020954_capture.rrc

**Comment by kd-11** [comment]
Please test with https://github.com/RPCS3/rpcs3/pull/10285

**Comment by Satan86** [comment]
Fixed
![image](https://user-images.githubusercontent.com/61447828/118374357-0e051980-b592-11eb-9f38-5c9c894440d6.png)
