### ISSUE TITLE
GT HD Prototype/Debug ELF fails to start

### ISSUE THREAD

**Issue by Nenkai** [RPCS3/rpcs3#9768]
While #9764 now properly parses and boots the ELF, it seems to immediately crash upon start with an Access Violation error.

## Details
These ELFs dates from mid 2006, possibly compiled with prototype sdks.
Upon research it would appear that the toc address/r2 is incorrectly fetched.
Expected should be `0x6c6908`, RPCS3 finds `0x6d68e0`.

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5971850/RPCS3.log.gz)

Binaries (note: both of them uses the same toc address):
https://cdn.discordapp.com/attachments/807830839756455937/807855596333563936/GTHD_debug_elf.zip

**Comment by elad335** [comment]
Dont open issues about non-master builds.
