### ISSUE TITLE
SSX [BLUS30849]: Low performance (possibly Linux only)

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#9786]
Testing this title at roughly 6-7fps during cutscenes and 15-20fps ingame.  Apparently this game can run fullspeed on a system of lesser specs than this one, so this may possibly be a linux-specific issue.  

System specs:

* OS: Linux Mint 20.1 / kernel 5.8
* CPU: Intel i7-7820HK
* GPU: Nvidia GTX 1070M / driver 460.32
* Compiler: gcc-10.2.0
* Build: 76518d4c590051944ff978b594361c0a65059002
* Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5984754/RPCS3.log.gz)

**Comment by MSuih** [comment]
SSX is not playable yet, thus some sort of issues can be expected. If you want to ask for settings recommendations, use the help channel on our Discord. If you just want to report the current status of the game, do so in our forums.
