### ISSUE TITLE
Last Of Us still desync sound in some cutscenes

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#9788]
In The Last Of Us BCES01584,I thought that issue was fixed but I still have it.
At 'Bidonvilles' cutscene, the sound of the bad guy's voice is desync.
I tried to change sound options,sound drivers,...nothing change and it's always at this cutscene (all other cutscenes work well).
If someone can help...
I'm running it on Windows 10 with GTX 1080 lastest drivers and 32go RAM.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5988154/RPCS3.log.gz)

**Comment by MSuih** [comment]
Github is not the place for help requests. If you need help, use our Discord instead.
