### ISSUE TITLE
Wangan Midnight [BLJM60028] hangs on boot.

### ISSUE THREAD

**Issue by makerbeleg** [RPCS3/rpcs3#9789]
Wangan Midnight hangs on boot with following screen saying about inability to save.
![2021-02-16-134700_1920x1080_scrot](https://user-images.githubusercontent.com/2441195/108056785-cccc9e80-7062-11eb-99bb-c92444962a07.png)

Log included.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5988199/RPCS3.log)

RPCS3 v0.0.14-11759-1446254a Alpha | makepkg | Firmware version: 4.87
Linux system.

**Comment by Asinin3** [comment]
![image](https://user-images.githubusercontent.com/15137035/108058517-138eb880-70a4-11eb-93b1-a1ee4a261869.png)
Works on my machine. Also why are you using precise interpreters? They run like 💩

**Comment by makerbeleg** [comment]
Does not matter if I use interpreter or recompiler. Results are the same. But it might be something on my end. Going to check on windows machine

**Comment by makerbeleg** [comment]
Same issue on Windows machine.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5988356/RPCS3.log)

**Comment by Asinin3** [comment]
Well, did you check if moving save files out of the folder helps (Go to Manage > Save Data to find the folder for the saves)? If it does maybe the saves are corrupted, or they were taken off a real PS3 and weren't decrypted properly.
