### ISSUE TITLE
Neverdread graphic glitch on AMD cards

### ISSUE THREAD

**Issue by dante3732** [RPCS3/rpcs3#9790]
Artifacts like this appear next to light sources and rays
Windows 10 Pro x64 20H2 
AMD Ryzen 5 3600 4.2 Ghz
MSI Radeon VEGA 64 8 Gb HBM2 
2x8 Gb DDR4 3200

![unknown](https://user-images.githubusercontent.com/66036249/108064919-5afa5200-706e-11eb-9591-8aa8ffbfac81.png)

Screenshot ps3 version 
![image](https://user-images.githubusercontent.com/66036249/108073326-f7c1ed00-7078-11eb-83b7-12f262807aab.png)

Nvidia 
![image](https://user-images.githubusercontent.com/66036249/108073523-348de400-7079-11eb-8b10-304122dd8ba2.png)
AMD
![image](https://user-images.githubusercontent.com/66036249/108073551-3c4d8880-7079-11eb-8592-7c4d681707f1.png)
Video with same this glith rx580.
https://www.youtube.com/watch?v=pM9SkMC2ZeI

RSX capture
https://drive.google.com/file/d/1r4wE5noJv17g8Jjj8E3Igow2gPPxfQXK/view?usp=sharing
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5988627/RPCS3.log.gz)
renderdoc https://drive.google.com/file/d/1T6jPiP1heMiAlJeqrB1ymrDln1ST6MZ7/view?usp=sharing

**Comment by dante3732** [comment]
This place from PS3, not have blue artefacts.
![image](https://user-images.githubusercontent.com/66036249/108065567-436f9900-706f-11eb-8f22-8c1ba5cf8eaf.png)

**Comment by dante3732** [comment]
Video with same this glith rx580.
https://www.youtube.com/watch?v=pM9SkMC2ZeI

**Comment by AniLeo** [comment]
Complete the regression template in the main post with the edit functionality

**Comment by DanteBC** [comment]
Can confirm the same bug on vega56 GPU

**Comment by dante3732** [comment]
> Complete the visual bug template in the main post with the edit functionality

I add renderdoc

**Comment by AniLeo** [comment]
Please retest and update this issue with AMD drivers 23.2.1 or newer as recently there have been changes that positively impact RPCS3.

**Comment by dante3732** [comment]
> Please retest and update this issue with AMD drivers 23.2.1 or newer as recently there have been changes that positively impact RPCS3.

Yep, looks fine.
