### ISSUE TITLE
Regression: Rainbow Flashing Textures on Killzone 3 on AMD (#9613)

### ISSUE THREAD

**Issue by dante3732** [RPCS3/rpcs3#9791]
I have graphic flickering in Killzone 3.
![Снимок экрана (529)](https://user-images.githubusercontent.com/66036249/108065158-a3b20b00-706e-11eb-8c35-b7d0263b03ed.png)
![Снимок экрана (530)](https://user-images.githubusercontent.com/66036249/108065160-a4e33800-706e-11eb-82d5-0ee78fbfb1b9.png)
![Снимок экрана (531)](https://user-images.githubusercontent.com/66036249/108065163-a57bce80-706e-11eb-9894-9371fbb88740.png)
![Снимок экрана (532)](https://user-images.githubusercontent.com/66036249/108065166-a6146500-706e-11eb-8b6c-4094916c4aea.png)
Windows 10 Pro x64 20H2 
AMD Ryzen 5 3600 4.2 Ghz
MSI Radeon VEGA 64 8 Gb HBM2 
2x8 Gb DDR4 3200

rsx capture no flickering 
https://drive.google.com/file/d/15mGskj1LcrHEDfVVi2xiTq6SvCOJhQYV/view?usp=sharing
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5989804/RPCS3.log.gz)
rsx capture flickering https://drive.google.com/file/d/1WFhBeUxht9sbR2xyuZydRQv5rpvgJZ-F/view?usp=sharing
[RPCS3 (2).log.gz](https://github.com/RPCS3/rpcs3/files/5988632/RPCS3.2.log.gz)
On 0.0.14-11605 and previous no flickering.
After 0.0.14-11619 start flickering.

**Comment by Asinin3** [comment]
No RSX Capture, No renderdoc. No testing if it was happening in old builds. And we didn't get to confirm on discord if other AMD users were affected or not.. Why open an issue when lacking such crucial info?

**Comment by dante3732** [comment]
On 0.0.16-12431 no flickering.
