### ISSUE TITLE
Black Screen on Kane & Lynch: Dead Men

### ISSUE THREAD

**Issue by TheRizzano** [RPCS3/rpcs3#9795]
I have a powerful computer.  I can run Cyberpunk on Max.  I have Kane & Lynch: Dead Men. At first I opened it, and it was a black screen with multiple red errors.  I updated with the official PSN update. Same result. Black screen, nothing else.

U {PPU[0x1000000] Thread (main_thread) [0x0145fe64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x014600bc]} sys_prx TODO: _sys_prx_register_library(library=*0x14626a0)
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} PPU: LLVM: Loaded module v4-kusa-1z3Pyu8YVnnorJiQ2hfu1e-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U {PPU[0x1000000] Thread (main_thread) [0x014a3d8c]} sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0010a50)
E {PPU[0x1000000] Thread (main_thread) [0x014a3d8c]} SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U {PPU[0x1000000] Thread (main_thread) [0x014a3d24]} sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0010a50, a3=0x0)
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} PPU: LLVM: Loaded module v4-kusa-XCgQWMc1s99n1WTwrpWvw4-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} PPU: LLVM: Loaded module v4-kusa-GsbjiwC5Sm3exFcR5udHpE-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} PPU: LLVM: Loaded module v4-kusa-gRWSbPdZHFQq5essKqQVjk-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
U {PPU[0x1000000] Thread (main_thread) [0x0146061c]} sys_prx TODO: _sys_prx_register_module()
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} PPU: LLVM: Loaded module v4-kusa-fLV79QqHgPi90UziTsWrHo-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23003400)
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} PPU: LLVM: Loaded module v4-kusa-GidnR56pzgun0Z5aqipN0L-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libusbd.sprx” (id=0x23004a00)
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} PPU: LLVM: Loaded module v4-kusa-t1xTtC1PVoW6Jh636RxJVQ-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} PPU: LLVM: Loaded module v4-kusa-2wS6UCQGvL8KpqZwEg6HX7-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libnet.sprx” (id=0x23004c00)
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} PPU: LLVM: Loaded module v4-kusa-UnNP3fZh95wiCGy3Q0csRy-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x014609ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libresc.sprx” (id=0x23004d00)
U {PPU[0x1000000] Thread (main_thread) [0x0145ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0145ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000000] Thread (main_thread) [0x0145ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0145ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x012307fc, LR:0x003ae028]} cellGame: cellGameDataCheckCreate2(version=0x0, dirName=“BLES00167”, errDialog=0x0, funcStat=*0xa7b170, container=1056964608)
E {PPU[0x1000000] Thread (main_thread) [HLE:0x012367bc, LR:0x003ac8e4]} SYS: 'cellPadClearBuf' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [1]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x012367bc, LR:0x003ac8e4]} SYS: 'cellPadClearBuf' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [2]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x012367bc, LR:0x003ac8e4]} SYS: 'cellPadClearBuf' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [3]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x01230b3c, LR:0x003b4e14]} SYS: 'cellAudioOutGetSoundAvailability' failed with 0xffffffff8002b246 : CELL_AUDIO_OUT_ERROR_UNSUPPORTED_SOUND_MODE [1]
E {PPU[0x1000000] Thread (main_thread) [0x014554ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x014554ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x014554ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000000] Thread (main_thread) [0x006341a0]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/SCENES/KaneAndLynch_LS_Default.WHD” [1]
E {PPU[0x1000000] Thread (main_thread) [0x006341a0]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/SCENES/KaneAndLynch_LS_Default.WHD” [2]
E {PPU[0x1000000] Thread (main_thread) [0x006341a0]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/SCENES/AllLevels/Loader_Sequence.zip” [1]
E {PPU[0x1000000] Thread (main_thread) [0x006341a0]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/SCENES/AllLevels/Loader_Sequence.zip” [2]
E {PPU[0x1000000] Thread (main_thread) [0x006341a0]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/SCENES/AllLevels/Loader_Sequence.zip” [3]

**Comment by TheRizzano** [comment]
I have all default settings. Wiki says no known issues.  Dualshock 4 plugged in and also took it out because I noticed the unsupported sound mode error.  Other games work fine.

**Comment by TheRizzano** [comment]
WHat does meta invalid mean? Why was this closed?

**Comment by AniLeo** [comment]
Read the repository guidelines and the issue template

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
