### ISSUE TITLE
Games crashing when using scaling on radv after #9738

### ISSUE THREAD

**Issue by RainbowCookie32** [RPCS3/rpcs3#9800]
## Quick summary
Any increase to scaling causes games to segfault after boot. Only happens on radv, amdvlk works fine.

## Details
So far I managed to get it on TLoU, but someone else on Discord reports it also happens on ICO (and was also on Linux), but I couldn't reproduce that one. Game always segfaults before getting to the menu when increasing resolution scaling above 100%.

Trying to find other games with the issue, but no luck so far.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.14-11736 (#9738)

#### 2. Logs

Logs for 100% scaling (no crash)
[TLoU Master no Scaling](https://github.com/RPCS3/rpcs3/files/6004627/rpcs3_master_tlou_noscale.zip)
[TLoU Master no Scaling with Debug Output](https://github.com/RPCS3/rpcs3/files/6004629/rpcs3_master_tlou_noscale_debug.zip)

Logs for over 100% scaling (crash)
[TLoU Master with Scaling](https://github.com/RPCS3/rpcs3/files/6004632/rpcs3_master_tlou_scale.zip)
[TLoU Master with Scaling and Debug Output](https://github.com/RPCS3/rpcs3/files/6004633/rpcs3_master_tlou_scale_debug.zip)

Logs for over 100% scaling before #9738 (good)
[TLoU Old Build with Scaling](https://github.com/RPCS3/rpcs3/files/6004653/rpcs3_old_tlou_scale.zip)
[TLoU Old Build with Scaling and Debug Output](https://github.com/RPCS3/rpcs3/files/6004654/rpcs3_old_tlou_scale_debug.zip)

* OS: Arch Linux
* CPU: Ryzen 7 1700
* GPU: RX 570

**Comment by jr1991-g** [comment]
This is still present on current build 0.0.15-11958, is there an ETA on this?

**Comment by titan-91** [comment]
I see there has been some success using the AMDVLK driver over RADV. So I followed the below Reddit post to work around this on my machine:

https://www.reddit.com/r/linux_gaming/comments/fddt2n/tutorial_how_to_use_amds_pro_vulkan_driver_or_the/

Using the below terminal command when I put both amdvlk64.so and amd_icd64.json in my home directory:

VK_ICD_FILENAMES=/home/user/amd_icd64.json ./RPCS3.AppImage

I have confirmed no more segfault crashes with the AMDVLK driver. LittleBigPlanet at 150% scaling runs amazing with zero stability and performance issues. I haven't tested my other games yet.
