### ISSUE TITLE
Unable to Access Network File Shares

### ISSUE THREAD

**Issue by baltimoresports** [RPCS3/rpcs3#9803]
RPCS3 Version: 0.0.14-11767-b86ec2ff Alpha

When I clean install the application, I can load files on my Network File shares. After running a game and closing the app, I lose access to network file shares. It looks like this:

![image](https://user-images.githubusercontent.com/1420685/108523103-8c0b9a00-729b-11eb-923b-cac4dda13f4f.png)

There is no error and they won't open. If I try and explore using the "Network" its blank.

**Comment by Andryshik345** [comment]
I just checked with some SMB drives here and they still accessible after running RPCS3, so it's likely an issue with only you

**Comment by baltimoresports** [comment]
Reinstalled on a clean version of Windows 11 and using version 0.0.17. This is repeatable on a clean version of RPC3.

**Comment by Mrlinkwii** [comment]
can this be rechecked on latest release ?

**Comment by baltimoresports** [comment]
> can this be rechecked on latest release ?

Looks good now. Version 0.0.29-15877
