### ISSUE TITLE
NieR [BLUS30481] audio disappears leading to freeze on the next loading screen

### ISSUE THREAD

**Issue by no1d** [RPCS3/rpcs3#9807]
## Quick summary
Rarely in-game audio will completely stop playing and game will freeze on the next loading screen.

## Details

Happened to me only a handful of times, but in one instance it occurred few times in a row in the same spot. I believe each time it was during combat.

#### My settings
* 60 fps patch
* Resolution Scale 150%
* Resolution Scale Threshold 512x512
* Write Color Buffers
* Audio Stretching 75%
* Native user interface disabled

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6014094/RPCS3.log.gz)

#### 5. Please provide your system configuration:
* Windows 10 20H2 19042 64bit
* Intel i7-6700K
* GeForce GTX 970
* 460.79
* Xbox One Controller

**Comment by Mzartek** [comment]
I have the same problem, I’ve tried to set SPU Threads to 1 and I’ve been able to play like 1 hour without any problem. Of course that doesn’t mean it fixed the issue as for me the problem could occur 5 min or 1h after the game start. But you could give it a try we never know.

**Comment by Megamouse** [comment]
issues using patches are not allowed
