### ISSUE TITLE
Dualsense Controller Support Interfering

### ISSUE THREAD

**Issue by Dormant-Hero** [RPCS3/rpcs3#9809]
I can no longer use my dualsense controller for anything other than RPCS3 since the dualsense handler updates. 

It seems the dualsense handler works even when the emulator is closed. I think this is the case as when I first plugged in my controller with PS3 emu it lights up blue. Now when the PS3 emu is closed my controller still lights blue after reset.

I think the handler is interfering with my 3rd party controller app I like to use for other games. The 3rd party dualsense app I use can be found here https://github.com/Ryochan7/DS4Windows/releases. 

My discord is Dormant_Hero#0230 if anyone would have the spare time to help me and this project I suppose in regards to this minor issue...

**Comment by 13xforever** [comment]
Just because RPCS3 doesn't reset LEDs on exit, doesn't mean it's still using it. I have no issues using DualSense with other games and/or Steam along or after closing RPCS3. This sounds more like an issue with DS4Windows (what a surprise).

**Comment by Dormant-Hero** [comment]
"Just because RPCS3 doesn't reset LEDs on exit, **doesn't mean** it's still using it" Okay no need to be rude...

Actually I can plug in DualSense on entry of windows with RPCS3 closed and it still lights us like a Christmas tree... 

The issue may be DS4 windows, but RPCS3 I think caused the issue I now have with it, as my controller never used to do that when plugged in, This is why I assumed rpcs3 installed a driver on my pc which clashes.

I was hoping there was some way to make DS4windows act normally again, however I assume you do not use this application and use the steam handler which I have never liked for any of my controllers for input latency reasons in the past (sorry if that is false logic).

**Comment by RainbowCookie32** [comment]
RPCS3 doesn't install any drivers, or does any modifications like that to the system.

**Comment by Dormant-Hero** [comment]
> RPCS3 doesn't install any drivers, or does any modifications like that to the system.

Arr okay. Then it must be something else causing it. Thank you Rainbow!
