### ISSUE TITLE
MGS4 Photo Album random crash, and Camera doesn't work as it should.

### ISSUE THREAD

**Issue by ComplexS1** [RPCS3/rpcs3#9814]
## Quick summary
Metal Gear Solid 4 Camera will not save the image. It will only show up as a complete black snapshot no matter what I capture.

## Details

Issues with the camera in gameplay. Doesn't seem to save the photo captured during the moment and only captures the shutter. Only shows up as black photos. Tried on both the modified ver. of RPCS3 and the current ver. of RPCS3 to no avail. Also received a random crash when trying to covert photo to jpg for some reason. The album works fine now, but will still post incase.

I will post a log for the crash on the photo album, but no major gameplay issues rise from the Camera function besides no photos.

I also have a photo of my photo gallery with nothing but the black photos in all.

My ps3 shows the camera functions as normal, as photo gallery saves it as is.

System configuration:
* OS -WINDOWS 10 PRO
* CPU - RYZEN 5 3600
* GPU - EVGA RTX 3070 FTW
* RAM - 16 GB CORSAIL REVENGANCE PRO RGB
* RPCS3 Version: 0.0.11-10814-903e109b Alpha
* NVIDIA GEFORCE VERSION - 461.40

I just wanted to report this as I'm unsure if it could be hardware or software issues.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6017111/RPCS3.log.gz)
<img width="960" alt="MGS4 PHOTO ALBUM BLACK IMAGES" src="https://user-images.githubusercontent.com/79387558/108613976-5d7ce480-73ab-11eb-89f4-57b934d308b4.PNG">

**Comment by illusion0001** [comment]
Try enabling write color buffers

**Comment by ComplexS1** [comment]
> Try enabling write color buffers

Alright enabling write color buffers fix the camera issue, but when exporting to jpg through photo album still crashes for some reason. I got a photo of the warning to show.

<img width="958" alt="MGS4 PHOTO ALBUM EXPORT JPG CRASH" src="https://user-images.githubusercontent.com/79387558/108614594-c6b32680-73b0-11eb-9694-15a075b3d92c.PNG">
