### ISSUE TITLE
Problems to open Persona 5.

### ISSUE THREAD

**Issue by Lolsie** [RPCS3/rpcs3#9815]
I've been trying to look for information about my problem and haven't find, even with other people with the same errors as the one i receive, a proper and concrete solution, so i prefer to open this thread issue and see if somebody could help me, and thank you in advance.

![Imagen1](https://user-images.githubusercontent.com/79389187/108614689-25899780-73d3-11eb-81a4-4703571c282e.png)

**Specific error:** 
F {RSX [0x0000000]} SIG: Thread terminated due to fatal error: Unknown context dma 0x0
(in file D:\a\1\s\rpcs3\Emu\RSX\gcm_enums.cpp:1176[:22], in function to_context_dma) (e=0x0000007f[127])

**My laptop settings:** 
Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz | 4 Threads | 3.84 GiB RAM | TSC: 1.796GHz | AVX

**Comment by RainbowCookie32** [comment]
Judging by the CPU and error, hardware below minimum requirements. 

GitHub is not the place for support, use our Discord server instead (not like you can fix that without new hardware anyways).

**Comment by Lolsie** [comment]
> Judging by the CPU and error, hardware below minimum requirements.
> 
> GitHub is not the place for support, use our Discord server instead (not like you can fix that without new hardware anyways).

Thank you for helping me!
