### ISSUE TITLE
Seeming Error Loop

### ISSUE THREAD

**Issue by Techmaster3000** [RPCS3/rpcs3#9830]
I recently tried out this emulator, and tried to make Sonic Generations work. In the compatibility list it says it's supposed to work mostly, (Status: Ingame). 
I installed the game package and rap files, but when it created all PPU caches, it gets stuck in a seeming loop of the same 2 errors. One says: "Decrypting data", the other says " block at offset 0x120 error". The game doesnt load. When i stop running the game the emulator still spams the same error. 

I saw this problem on an older issue, but that one was closed without a clear solution.

**Comment by AniLeo** [comment]
---

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
