### ISSUE TITLE
LittleBigPlanet with PSMove set to Fake causes button presses to pause the game

### ISSUE THREAD

**Issue by ruvaldak** [RPCS3/rpcs3#9837]
## Quick summary
Basically, if Move support is set to Fake while playing LittleBigPlanet2, button presses (face buttons, l1, l2, r1, r2) all cause the game to pause (in-game pause, not rpcs3 pause). Not sure why.

## Details

Quick summary pretty much describes it.

#### 5. Please provide your system configuration:
* Windows 10 Pro x64
* i7-9700k
* Nvidia GTX 1660 Super
* Latest Drivers
* 16gb DDR4 3200MHz

#### Please include.
* Anything else you deem to be important
Tested with a Switch Pro controller through XInput and a genuine PS4 controller connected by a wire, both cause the same problems. I did notice that Fake specifically said DS3, so if it absolutely requires a DS3 only, then disregard this obviously. If that is the case, certainly hope support for other controller types is planned.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6033456/RPCS3.log.gz)

**Comment by Megamouse** [comment]
Regarding your last paragraph: The fake move stuff is unaffected by your choice of controllers.

**Comment by ruvaldak** [comment]
> Regarding your last paragraph: The fake move stuff is unaffected by your choice of controllers.

Got it, so this is indeed a bug/issue with move.

**Comment by Kilowog01** [comment]
I can confirm the problem with Dualshock 4 and Dualsense. It's very annoying.

**Comment by Megamouse** [comment]
I noticed something similar when I tested Time Crisis.

**Comment by Megamouse** [comment]
Hi @ruvaldak , can you test this with https://github.com/RPCS3/rpcs3/pull/12308 please?

**Comment by ruvaldak** [comment]
> Hi @ruvaldak , can you test this with #12308 please?

will do

**Comment by ruvaldak** [comment]
> Hi @ruvaldak , can you test this with #12308 please?

I'll need a compiled version to test with. Don't have the means or time to compile atm, unfortunately.

**Comment by ruvaldak** [comment]
SEems to work fine, although I can't seem to figure out how to move the cursor. I assumed it would be the right stick, but that doens't seem to do anything. Worth noting that I am using a Dualsense controller.

**Comment by ruvaldak** [comment]
left stick cursor doesn't seem to work well at all in 12308. Tried using it ingame, seems stuck in the bottom right corner.
