### ISSUE TITLE
Buzz junior controllers issue

### ISSUE THREAD

**Issue by nevespt** [RPCS3/rpcs3#9839]
The buzz junior already have controller mode, with this "feauture" the game is not playable at all, just pass the language selector, but in the mini games the keys are wrong

maybe adding something like this!
Image: https://user-images.githubusercontent.com/2995486/103174034-7cf20800-4867-11eb-8a40-f2fbeb6d16ad.png

**Comment by RipleyTom** [comment]
You realize the buzz feature is to play buzz games with a normal controller, not a buzz controller?

If you want to use the real buzz controllers just follow the instructions here: https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories#cellUsbd_Set-up_Instructions

**Comment by nevespt** [comment]
im talking about emulation controller the "normal controller", open any buzz junior and try using, you will see on menus the rpcs3 plugin works fine, but in game (on the mini games) you keys are wrong

**Comment by Megamouse** [comment]
should be fixed with the new settings introduced with #9862
