### ISSUE TITLE
God of War Collection : Ghost of Sparta  [BCES01277]

### ISSUE THREAD

**Issue by vlahka1** [RPCS3/rpcs3#9841]
## Quick summary

The game freezes whenever a cinematic plays. 

## Details

When a cinematic starts to play the game will just freeze.  The time of the freeze is random.  I could load it up and restart from a checkpoint, get to the same cinematic and it would freeze randomly throughout it.  But I cant get passed it.  Sometimes I could pass one and go to the next one after the emulator would update itself a few times.  But now its been stuck for the past 4 months and wont move on, no matter what options I choose in the audio of the emulator.  I've tried grabbing older versions of the emulator and all of them do the exact same thing.

As this is just a freezing of the game I cant provide screenshots or anything else that might be useful.  Graphics are fine without any corruption.  Sound is great, no problem with playback or quality.  The only thing it does is freeze during cinematics, of which also run smoothly.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6038600/RPCS3.log.gz)

#### 5. Please provide your system configuration:
* OS  - Win10
* CPU- i7 8700K
* GPU- nVidia 1660
* Driver version - 460.79
* 16GB Ram

**Comment by kd-11** [comment]
May be a regression; I ran through the GoW series in its entirety less than 6 months ago on the emulator without issues (any issues found were fixed). If that is the case, try a build from about a year ago and if it works, find the first broken build. No patches were used for these PSP ports.

**Comment by vlahka1** [comment]
Thanks for the reply.  I have tried man revisions, including the ones that were listed as having worked at the time.  I cant seem toget it to work.

**Comment by Nerboruto** [comment]
it works fine for me..
maybe something related to tsx...
or a corruption of the game archives

**Comment by kd-11** [comment]
I'd try with maybe LLE libvdec in the advanced settings. From the logs its hanging during video decoding.
Note that using LLE libvdec will use the virtual CPUs to do image processing using original sony code. Video playback performance may not be so good.

**Comment by vlahka1** [comment]
> 
> 
> I'd try with maybe LLE libvdec in the advanced settings. From the logs its hanging during video decoding.
> Note that using LLE libvdec will use the virtual CPUs to do image processing using original sony code. Video playback performance may not be so good.


Thanks for the reply.  Could you tell me where I would find that in the emulator options as I've checked around but dont see any LLE option.

**Comment by Nerboruto** [comment]
> > I'd try with maybe LLE libvdec in the advanced settings. From the logs its hanging during video decoding.
> > Note that using LLE libvdec will use the virtual CPUs to do image processing using original sony code. Video playback performance may not be so good.
> 
> Thanks for the reply. Could you tell me where I would find that in the emulator options as I've checked around but dont see any LLE option.

![Nuova immagine bitmap](https://user-images.githubusercontent.com/10599012/109385453-416dcb80-78f4-11eb-98ca-f7eb43de6f0f.jpg)

**Comment by Nerboruto** [comment]
GOW-GOS works perfectly for me while GOW2 HD freezes in videos...
GOW GOS should be h264 while GOW 2 HD mpeg2...

**Comment by vlahka1** [comment]
> 
> 
> > > I'd try with maybe LLE libvdec in the advanced settings. From the logs its hanging during video decoding.
> > > Note that using LLE libvdec will use the virtual CPUs to do image processing using original sony code. Video playback performance may not be so good.
> > 
> > 
> > Thanks for the reply. Could you tell me where I would find that in the emulator options as I've checked around but dont see any LLE option.
> 
> ![Nuova immagine bitmap](https://user-images.githubusercontent.com/10599012/109385453-416dcb80-78f4-11eb-98ca-f7eb43de6f0f.jpg)



Thanks for that.  I checked it and ran the game.  The FMV part started up pretty sluggishly but after about 10-15sec it became smooth.  Sadly it froze again.  Seemed to get a little further this time as it made me think my issue was fixed but then backhand to the face.

**Comment by nitroos-ai** [comment]
Try to run the game with TSX disabled. I had few problem with TSX as it freezes many games without warning or error.

**Comment by RainbowCookie32** [comment]
You might be on to something there. OP's log shows that they have TSX-FA, which is known for causing random freezes and other issues.

**Comment by Megamouse** [comment]
please retest with the suggestions above

**Comment by vlahka1** [comment]
> Try to run the game with TSX disabled. I had few problem with TSX as it freezes many games without warning or error.

Thanks heaps for this.  Sorry it took me a while to answer as I'd erased my progress while trying to fix it.  I now managed to play fro the beginning right to the part it refused to load passed.  Usually I'd have frozen a half dozen areas or so by now but it went smoothly through it all.  Really appreciate the help.

Now if only I could find a way to figure out why my Macross games dont auto save my progress when I reload the game.  This is the one problem that really upsets me as those games are glorious.

**Comment by Megamouse** [comment]
So does this mean this issue here is fixed?

**Comment by vlahka1** [comment]
The god of war issue I had seems to be fine for now.  Hopefully no more surprises down the line but it looks solid.  Just wish I could figure out why the macross games dont autosave.



________________________________

**Comment by Megamouse** [comment]
I don't see how this is related to macross
