### ISSUE TITLE
DS3 Controller Issue

### ISSUE THREAD

**Issue by Luis-Douet** [RPCS3/rpcs3#9844]
## Quick summary
The analog sticks on the DS3 controller no longer work properly after #9194.

## Details
Opening the gamepad config and selecting the DualShock 3 handler shows the "blue dot" analog sticks flickering  between the center of the deadzone and upper left corner of the squircle.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.14-11784

#### 2. Please attach TWO logs:
* One for the build with regression.
[Regression RPCS3.log](https://github.com/RPCS3/rpcs3/files/6040297/Regression.RPCS3.log)

* One for the build that works as expected.
[Working RPCS3.log](https://github.com/RPCS3/rpcs3/files/6040300/Working.RPCS3.log)

#### 3. Please provide your system configuration:
* OS - Linux (Debian Sid)
* CPU - Ryzen 7 1700
* GPU - Radeon RX 580
* Driver version - Mesa RADV (ACO) 20.3.4

#### Please include.
This issue does not happen on a DS4 controller with the DualShock 4 handler.

**Comment by Luis-Douet** [comment]
**An example where you can see the DS3 analog sticks moving on its own between the center of the deadzone and upper left corner of the squircle.** 

![Example](https://user-images.githubusercontent.com/73673372/109371418-c2997400-789c-11eb-9798-fdc235dd297d.gif)

This random movement is continuous and prevents playing games with the DS3 controller.

**Comment by sfjuocekr** [comment]
I chime in the report the same issue with the DS3 controller, if you use EVDEV it works as intended but I can not shake the controller in for example Heavy Rain (if that even works at all, I never played the game and wanted to play it)

**Comment by drizzt** [comment]
I have the same issue with DS3 controller and I had to downgrade to rpcs3-v0.0.14-11773-b7c2bfbc_linux64_db803eb20a0c6c5d7791ba6fab08563a.AppImage

**Comment by kattjevfel** [comment]
While indeed fixing the gamepad seizures, using a DS3 now have several seconds of delay, I'll be looking into bisecting this.
