### ISSUE TITLE
Regression: Verification failed crash on Gran Turismo 5 (#9738)

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#9845]
After version 0.0.14-11736-195fb1cf (#9738) Gran Turismo 5 crashes with `SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTextureCache.h:812[:4], in function create_new_texture)` in the pre-race menu of Suzuka circuit and possibly other tracks.
Latest master log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6041350/RPCS3.zip)
last working version log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6041446/RPCS3.zip)
5600x, 1050 ti driver 461.60, Win 10 20h2

**Comment by kd-11** [comment]
I cannot reproduce this issue. Please retest. If it still happens please give instructions on how to trigger it, it works fine for me somehow (AMD GPU)
On an unrelated note, there was talk of vertical lines and other artifacts - can you check if they still happen with MSAA set to Auto? I just tested this and there were no problems with default options.

**Comment by Satan86** [comment]
Graphics with MSAA are fine 
![unknown](https://user-images.githubusercontent.com/61447828/119558118-f0596080-bd98-11eb-9142-4227e44275ab.png)
Crash still happens, it's really simple to reproduce, just select the suzuka circuit in any game mode and it should crash in the pre-race screen as already mentioned. Other users have reported this crash in the Madrid Circuit as well, though I didn't get the crash there iirc

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6541964/RPCS3.zip)

**Comment by kd-11** [comment]
Needs an update (still cannot reproduce)

**Comment by Satan86** [comment]
Still happens
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6956445/RPCS3.zip)

**Comment by Satan86** [comment]
Maybe you could update the game to 2.11 and see if it crashes?
