### ISSUE TITLE
Black or White screen on all games

### ISSUE THREAD

**Issue by AD010** [RPCS3/rpcs3#9853]
i have black or white screen on all games without sound on Intel HD GT1 (Haswell), my GPU have full harfware support OpenGL 1.0-4.3, i try all settings, latest drivers, runtime libraries, codecs etc. Do you remove support for intel HD ?

**Comment by AniLeo** [comment]
Haswell doesn't have OpenGL 4.3 support on Windows.

---

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
