### ISSUE TITLE
Regression: Demon's Souls [BLUS30443] Stuttering/freezing when switching between inventory, equipment menus, during item pickups, walking around some archstones (#9819)

### ISSUE THREAD

**Issue by PootsUndead** [RPCS3/rpcs3#9857]
## Quick summary
Stuttering in-game while switching / closing certain menus and by certain archstones.

## Details
It will stutter / freeze (picture and sound) when closing out of or switching (L2 & R2) from the inventory or the equipment menus. There is also significant stuttering when moving around the 2nd archstone in world 4-2 and 2-2. 

Note: this does not occur while in the tutorial area.

#### build that introduced the regression.
#9819 build 0.0.14-11799

#### build that works as expected.
#9802 build 0.0.14-11791

#### Attached log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6061517/RPCS3.log.gz)

**Notice log:**
I experimented switching the log viewer and when selecting "Notice", I found these 2 white line of text would come up for only a second every time I forced the stutter to happened when switching menus. I had to take screenshot and then type it out below:

! {PPU[0x1000019] Thread (SLSession) [HLE:0x01d3079c, LR:0x00eb7d7c]} cellSaveData: SECUREFILE: 2USER.DAT -> 0x0123456789abcdeffedcba9876543210

! {PPU[0x1000019] Thread (SLSession) [HLE:0x01d3079c, LR:0x00eb7d7c]} cellSaveData: SECUREFILE: 1USER.DAT -> 0x0123456789abcdeffedcba9876543210

#### my system configuration:
- RPCS3 v0.0.15-11884-87af9050 Alpha | Firmware version: 4.87
- CPU i7-7800X @ 3.50GHz 
- RAM 16GB DDR4
- GPU GeForce GTX 1080 running on driver 461.72.0.0
- OS: Windows 10 Home | Version 20H2

**Comment by AniLeo** [comment]
Missing log file, removed huge wall of text which wasn't the log file

**Comment by PootsUndead** [comment]
> Missing log file, removed huge wall of text which wasn't the log file

Apology. Added log.

**Comment by PootsUndead** [comment]
@AniLeo I've updated the log and added a more concise description on the issue. Please advise.

**Comment by hanimeister** [comment]
I've noticed the exact same issue @PootsUndead and I realized you can "force" it to happen by switching said menus (inv and equip), when openned, with L2 / R2. By doing this and enabling Log for warnings I spotted this line:

`W {PPU[0x1000019] Thread (SLSession) [HLE:0x01d3079c, LR:0x00eb7d7c]} cellSaveData: cellSaveDataAutoSave2(version=0, dirName=“BLUS30443DEMONSS005”, errDialog=0, setBuf=*0x3461d7b8, funcStat=*0x1982500, funcFile=*0x19824e8, container=0xffffffff, userdata=*0x3461d760)`

I hope there's some hint on this to help solve this issue.

**Comment by PootsUndead** [comment]
So I tried rolling back to older builds to find where precisely this started occurring but unfortunately I couldn't download some of the older builds that had a line strike through them for some reason. But I did find that build #9802 [0.0.14-11791] for sure does NOT have the stutter/freeze issue so I am hoping this will help us narrow down what is the cause of this.

**Comment by PootsUndead** [comment]
> I've noticed the exact same issue @PootsUndead and I realized you can "force" it to happen by switching said menus (inv and equip), when openned, with L2 / R2. 

You can also "force" it to happen when confirming items you pickup.

**Comment by dae685** [comment]
I have the same issue, and have noticed that the stutter is significantly reduced, almost to the point of being imperceptible, when moving my RPCS3 installation from a mechanical HDD to a SSD. Version: 0.0.15-11987-2c05e971 Alpha. 

[RPCS3-Logs.zip](https://github.com/RPCS3/rpcs3/files/6176305/RPCS3-Logs.zip)

**Comment by PootsUndead** [comment]
> I have the same issue, and have noticed that the stutter is significantly reduced, almost to the point of being imperceptible, when moving my RPCS3 installation from a mechanical HDD to a SSD. Version: 0.0.15-11987-2c05e971 Alpha.
> 
> [RPCS3-Logs.zip](https://github.com/RPCS3/rpcs3/files/6176305/RPCS3-Logs.zip)

The game ran perfectly before. It wasn’t until an update that introduced the stutter/freeze. 

As mentioned in my original post. If you roll back to an older build the game runs like a dream.

**Comment by Asinin3** [comment]
Work out where it broke exactly, shouldn't be up to developers to fix users issue reports.

**Comment by PootsUndead** [comment]
> Work out where it broke exactly, shouldn't be up to developers to fix users issue reports.

Problem I had when trying to find the exact update that caused this regression was I wasn’t able to download them because they had a strike through them so I could do was put that it was between these builds #9802 and #9835. 

If it was just my system that was causing this issue I would agree but I have asked on discord and other users have experienced the same issue so it is not a user issue it is a regression that introduced in one of the updates.

**Comment by PootsUndead** [comment]
The latest build 0.0.15-12026 made the loading times 3 times as long as before.

These newer builds are making DeS less and less playable. :( 

Playing on the last stable build (0.0.14-11791) is a must now for those of us with the stuttering/freezing issue.

**Comment by pcdlin** [comment]
The issue seems to have been introduced in 0.0.14-11799, it was not present in the previous build (0.0.14-11795)

**Comment by daedrixxx2** [comment]
@Asinin3 Hello. It broke exactly after version 0.0.14-11791. This is the last version where the bug doesn't occur.

**Comment by Peduls** [comment]
Came here to open an issue about this problem but saw one already open. It seems like every time the game auto-saves it freezes for a second or two.

**Comment by BeeTheImmortal** [comment]
I have the exact same issue, the game used to work fine before. I just want to add that a significant freeze also happens when I pick up any item, same as with the inventory tab switching. Console shows no errors for me.

**Comment by PootsUndead** [comment]
> Came here to open an issue about this problem but saw one already open. It seems like every time the game auto-saves it freezes for a second or two.

You should post your issue because 1) it could be unrelated to what I’ve experienced and 2) this is a dead post now and the devs can’t do anything with it (hence the tag “Need Information”.

**Comment by AniLeo** [comment]
Tagging @elad335 since it regressed on #9819

**Comment by PootsUndead** [comment]
> I have the exact same issue, the game used to work fine before. I just want to add that a significant freeze also happens when I pick up any item, same as with the inventory tab switching. Console shows no errors for me. More specifically, it happens when I close the popup telling me what item I picked up, so I have hunch it may be related to UI elements.

Exactly what I experienced as well. Try opening a new issue because no one is looking into this issue anymore. Good luck!

**Comment by Peduls** [comment]
I don't think opening a duplicate issue would help. Don't be so negative. I'm sure they'll get around to fixing the issue soon enough.

**Comment by YuriNator557** [comment]
Raising another issue will just get it closed immediately. Just because it is old, it doesn't mean no progress is being made to fix it.

**Comment by segikun** [comment]
Hello, guys. Same here.
Tried this 0.0.14-11791 version and game plays normally. Without freezzes on menu and when pick up items.

**Comment by segikun** [comment]
Guys. I also tried run new version emulator and DeS on SSD and its work nice...

**Comment by Peduls** [comment]
Just tested this on RPCS3 0.0.16-12375 and this issue is still present. My game files and emulator have never been stored on a SSD but the issue only showed up recently.

**Comment by kd-11** [comment]
This happens because DeS saves the player state one every action. Picking up items or navigating menus forces a savepoint. I suppose slow drive access is what is causing the stutter on some systems.

**Comment by Peduls** [comment]
But I didn't move the game to a new HDD or anything. The stuttering problem is new as of 0.0.14-11799 according to @PootsUndead

**Comment by daedrixxx2** [comment]
Until version 0.0.14-11791 there was no problem playing the game from a HDD. Now you get stuttering everytime the game saves if you're not on a SSD, which the vast majority of players use only for the OS.

**Comment by Peduls** [comment]
That seems like it can't be correct. I mean it's not like the PS3 had a SSD inside.

**Comment by Peduls** [comment]
@elad335
I just mean that the game shouldn't suffer from stuttering on a reasonably fast HDD since the PS3's hardware wasn't as fast as a modern SSD right?

**Comment by kd-11** [comment]
The PR in question adds something not present on PS3 to keep your saves from breaking if rpcs3 crashes while saving data, or the usual other causes (power loss, etc) that normally corrupt saves. Not saying it can't be improved, just pointing out why it exists and why PS3 is unaffected.

**Comment by jakura-nuva** [comment]
I'm experiencing the same issue. Not a big deal, but hopefully it gets smoothed out eventually.

**Comment by BeanButCoffee** [comment]
> The PR in question adds something not present on PS3 to keep your saves from breaking if rpcs3 crashes while saving data, or the usual other causes (power loss, etc) that normally corrupt saves. Not saying it can't be improved, just pointing out why it exists and why PS3 is unaffected.

Is there any way to disable this feature apart from downgrading the rpcs3 version? As it is now the only way to play without stuttering for me (I don't have an SSD) is to put the emulator on the RAM disk. Not really convenient, but works. Not sure if it's possible to just turn this feature off in some config file or something.

**Comment by Nekotekina** [comment]
Please try #10479 someone who can reproduce or experiences the issue.

**Comment by Peduls** [comment]
Just tried with the latest dev build (0.0.16-12408) and the issue is still present.

**Comment by Nekotekina** [comment]
To test a pull request, download artifact from https://cirrus-ci.com/task/5005243478966272 please

**Comment by Peduls** [comment]
Oops. I'll test it as soon as I get back home from work.

**Comment by BeanButCoffee** [comment]
> To test a pull request, download artifact from https://cirrus-ci.com/task/5005243478966272 please

Completely fixes stuttering for me. Tried to pick up items on the mainline build, it stutters every single time any item is picked up outside of the tutorial area, but in this build it doesn't happen anymore. Scrolling through items in inventory doesn't cause stuttering anymore either.
[Toshiba HDWD110 7200rpm, Xeon E5-2689]

**Comment by Peduls** [comment]
I have the same experience. The stuttering is not present using this build!

**Comment by jakura-nuva** [comment]
Updated to v0.0.16-12409-3c614d95 today, and the stuttering is almost entirely gone. I say "almost" because there's a split second (must be a single frame) where freezing is noticeable, but it's _much_ better than before.

**Comment by Peduls** [comment]
I think this issue can be closed now. After updating to the latest dev build I have no stuttering.

**Comment by ShlomiToren** [comment]
I can also confirm the dev build fixed the issue for me.
I'm not familiar with how bugs work in this project: will this fix be included in the next official version?

**Comment by MSuih** [comment]
The pull request got merged and thus the changes are already in official versions.

**Comment by ShlomiToren** [comment]
Cool, thanks.

**Comment by Nekotekina** [comment]
If it resurrects old problems again we might have to revert it though. In that case I'll probably implement postponed savedata writing so it doesn't pause the game (but this approach has its own downsides since it creates new uncertainness about savedata persistence).
