### ISSUE TITLE
[Feature Request] Setup rpcs3.net to be able to take donations from Brave Rewards

### ISSUE THREAD

**Issue by XenoFantom** [RPCS3/rpcs3#9864]
## Quick summary
The Brave Browser has a feature that allows users to watch ads and donate to certain sites. However, these sites have to be verified creators in the Brave Rewards system in order to take donations.

## Details
Brave, by watching ads, allows you to gain money and donate that money to their list of verified partners. However, in order to be able to receive donations, you must register within their program and become a verified partner. RPCS3 could potentially gain more support by registering.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
This wouldn't affect the software, but it would help the devs.
#### 2. Please tell us, why your feature is important to RPCS3.
Even if there is a Patreon, some people are tight on money and can't donate. This program not only adds more ways to donate, but allows people to support the devs even if they don't have money to spare.
#### 3. Please attach screenshots of the feature implemented in other projects.
![image](https://user-images.githubusercontent.com/79477721/109426423-ef3bb180-79aa-11eb-908a-5aac614e1388.png)
![image](https://user-images.githubusercontent.com/79477721/109426472-0d091680-79ab-11eb-8ce6-63e8be2e3843.png)
![image](https://user-images.githubusercontent.com/79477721/109426491-227e4080-79ab-11eb-9b7f-000b0340518c.png)

#### 4. Please provide your system configuration:
(This part is redundant for this issue)
* OS
* CPU
* GPU
* Driver version
* etc.

#### Please include.
(This was not sponsored by Brave Browser)

**Comment by elad335** [comment]
🏠 -> https://github.com/DAGINATSUKO/www-rpcs3

**Comment by XenoFantom** [comment]
OK, I'll move it over there.
