### ISSUE TITLE
[Feature Request] Show PPU access violation regardless of log output mode

### ISSUE THREAD

**Issue by illusion0001** [RPCS3/rpcs3#9870]
Couldn't find anything related to silence log output to filter fatals

**Comment by elad335** [comment]
SPU access violation is an error in order to not pause the emulation because SPU access violation is not fatal in reality.

**Comment by illusion0001** [comment]
Fwiw, only show fatal on silence log output to reduce log spam in file

**Comment by illusion0001** [comment]
Perhaps I could just make fatal on always.
