### ISSUE TITLE
Massive delays using DS3 handler

### ISSUE THREAD

**Issue by kattjevfel** [RPCS3/rpcs3#9878]
As of 930895a218100e81db2ab85b3a131cc4047c907a, using the DS3 handler, the gamepad has several seconds of delay, still happens on git master (ea5e837b)

```
930895a218100e81db2ab85b3a131cc4047c907a is the first bad commit
commit 930895a218100e81db2ab85b3a131cc4047c907a
Date:   Tue Mar 2 00:54:38 2021 +0100

    DS3: fix LED battery status

 rpcs3/Input/ds3_pad_handler.cpp | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)
```

https://user-images.githubusercontent.com/6226312/109663216-260cf580-7b6c-11eb-8a05-f80fcab12669.mp4

**Comment by Megamouse** [comment]
there's no log provided....
why do people expect that we magically know how their system is configured and if there are errors or not...

**Comment by kattjevfel** [comment]
I just figured a log would be pointless in this type of regression, since nothing's crashing. Anyways:
[RPCS3_good.log](https://github.com/RPCS3/rpcs3/files/6072113/RPCS3_good.log)
[RPCS3_bad.log](https://github.com/RPCS3/rpcs3/files/6072114/RPCS3_bad.log)

**Comment by RipleyTom** [comment]
Several people have tested DS3 PR(including me) and definitely didn't notice any lag.
The commit you pointed to is definitely not the cause though, please at least find the real culprit.

Out of curiosity do you have a particular usb setup or anything other than the ds3/keyboard/mouse of note connected through usb?

**Comment by kattjevfel** [comment]
The commit prior to it works perfect, no seizures and what-not like before (#9844), and it happens ever since that commit.

It happens both via bluetooth and usb, I also made sure to unplug all other gamepads while testing.

**Comment by Megamouse** [comment]
Please test if #9898 helps

**Comment by kattjevfel** [comment]
@Megamouse Tested and it works perfectly, if anything it feels a bit snappier than before!
