### ISSUE TITLE
Ratchet and Clank Quest for Booty [BCES00301/NPUA80145]: water visual glitch

### ISSUE THREAD

**Issue by kebabdubai** [RPCS3/rpcs3#9892]
## Quick summary
Water visual glitch in R&C Quest for Booty, also present in Tool of Destruction

#### Description
The glitch appears in every terrain with stable water like ocean, lake, or puddle
- it does not seem to reduce performance
- it is present in the disc and PSN versions
- it is not affected by any settings, even __Write Color Buffers__
- it reacts to player movement and FOV
- it works exactly the same in both games  

It seems to appear when water is in FOV, even if covered by objects.

#### Background
The issue has been already present a year ago with older and newer drivers, it does not appear in YT gameplays recorded on Windows like this one: https://youtu.be/0ut4izrugkQ, so it seems to be platform, not emulator/driver version dependent. While most users report R&C Quest for Booty and Tools of Destruction as almost playable, I'm not able to even play Quest for Booty as it crashes regularly. I was able to complete Tools of Destruction, with rare crashes, but again with unique visual glitches, which I will report in a separate issue.

## Platform
* OS Ubuntu 20.04 Linux 5.4.0-42-generic
* CPU Intel Core i7-7700
* GPU GeForce GTX 1060 6GB
* DRIVER 450.102.04

## Files
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6078929/RPCS3.log)
https://drive.google.com/file/d/1eO0T_i0fN0S5hOemOml9RzoZ7KNIzvBM/view?usp=sharing

## Screenshots
![Screenshot at 2021-03-03 21-15-52](https://user-images.githubusercontent.com/61200862/109866797-0a861580-7c66-11eb-9282-af4cc6bf79ef.png)
![Screenshot at 2021-03-03 21-15-57](https://user-images.githubusercontent.com/61200862/109866799-0bb74280-7c66-11eb-970a-b1272e03d9e3.png)
![Screenshot at 2021-03-03 21-16-46](https://user-images.githubusercontent.com/61200862/109866802-0c4fd900-7c66-11eb-90ec-aa953a0df356.png)

I'm not able to provide PS3 footage. RenderDoc does not work for me, AppImage encounters an issue.

**Comment by mvxxx** [comment]
I have also noticed similar issue. It would be great if it will be fixed. Thank you.

**Comment by ruvaldak** [comment]
I played through Quest for Booty a couple days ago and didn't see anything like this. I notice you're on linux, perhaps it's related to that?

**Comment by kebabdubai** [comment]
As mentioned above, I believe so: "(...) so it seems to be platform, not emulator/driver version dependent"

**Comment by doesthisusername** [comment]
fwiw, i am not getting this on my current kernel (5.11.6) and rpcs3 master, and have not seen it on earlier versions of either before.
gpu is turing running on driver 460.67.0.0.

**Comment by kebabdubai** [comment]
@doesthisusername was ur driver manually installed, or from a repo?

**Comment by kebabdubai** [comment]
![image](https://user-images.githubusercontent.com/61200862/112636127-f4bad900-8e3c-11eb-8e9c-58ad546c1215.png)
 issue disappeared with driver update 460.67
