### ISSUE TITLE
Muv luv alternative total eclipse [BLJM60579] breaks and closes

### ISSUE THREAD

**Issue by DensetsuOtoko** [RPCS3/rpcs3#9894]
So far I was playing normally until I got to that part of the game.
In a dialogue with the character Cui Yifei, the game is stopped and ended. I tried several settings and I can't move on.
Follow the logs and video demonstrated what is happening.

https://drive.google.com/file/d/1frMxxNZ0EYgjBndmVFgD6hqn8I5mBJlr/view?usp=sharing

Log

AND {PPU [0x1000000] Thread (main_thread) [0x00771ee4]} SYS: 'sys_fs_stat' failed with 0x80010006: CELL_ENOENT, “/ dev_bdvd / PS3_GAME / USRDIR / StandardGuestUser” [1]
U {PPU [0x1000000] Thread (main_thread) [0x00300d5c]} PPU TODO: Unimplemented syscall syscall_988 -> CELL_OK (r3 = 0x4, r4 = 0x0, r5 = 0x15, r6 = 0xd000fed0, r7 = 0x2869647829000000 0x100000000000000, r10 = 0x1000000)
S sys_process: Process finished
AND {PPU [0x1000000] main_thread} SYS: Stat: 'sys_fs_stat' failed with 0x80010006: CELL_ENOENT, “/ dev_bdvd / PS3_GAME / USRDIR / aaa” [x8]

TTY

Display resolution: 1280x720 (16: 9)
libusbpad supported pad (0) detected
sensor supported pad
New Mouse 0 is connected: VENDOR_ID = 4660 PRODUCT_ID = 4660
abort () is called from 0x00000000002fdaf0
                  from 0x0000000000300c58
                  from 0x00000000000b6b0c
                  from 0x000000000030aa28
                  from 0x0000000000179fdc
                  from 0x00000000000e9b74
                  from 0x00000000000e9d38
                  from 0x00000000000e9e3c
                  from 0x000000000048000c

Continue ... (Lv-2 is still running.)

**Comment by RainbowCookie32** [comment]
Proper log is inside the google drive rar, attaching here for easier access.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6079820/RPCS3.log)

**Comment by Asinin3** [comment]
Still an issue?

**Comment by DensetsuOtoko** [comment]
Test today on the latest version available: RPCS3 Version: 0.0.21-13475-6a671554 Alpha | teacher
It's working fine now I'll keep testing and see if I can get to the end of the game.
Thank you!
