### ISSUE TITLE
Phantom Breaker Extra [BLJM61098] Sold out gpu memory breaking emulator 

### ISSUE THREAD

**Issue by Shuneferus** [RPCS3/rpcs3#9899]
The memory of the vga is depleted every time it loads a new phase / fight of the game until the point of the emulator breaks as described in the attached log. 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6094852/RPCS3.zip)

The log is compressed because it was 44mb. 
System: Windows 10 x64 Cpu Intel E5-2660 v3 @ 3.3Ghz 32GB ram Gpu GTX 1060 6GB render Vulkan

**Comment by Shuneferus** [comment]
Attached is another log with the same error: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6094949/RPCS3.log)

**Comment by kd-11** [comment]
Time to retest, memory management has been changed recently.

**Comment by Shuneferus** [comment]
Hello KD-11 the problem is solved, now the game only uses 4gb of the 6gb of vram available on gtx 1060 6GB. I'm closing this topic. A hug and thanks.
