### ISSUE TITLE
[Regression] Hatsune Miku Project Diva F and F2nd - freeze since v0.14-11619

### ISSUE THREAD

**Issue by Leopard20** [RPCS3/rpcs3#9901]
The game freezes completely after the shader preload screen.

I traced the responsible commit to: https://github.com/RPCS3/rpcs3/pull/9613

v0.14-11605 works fine.

Log:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6094913/RPCS3.zip)

**Comment by Leopard20** [comment]
I noticed that a lot of other games are also broken by that commit. Maybe you should consider reverting it?

**Comment by Andryshik345** [comment]
Hmm...
![изображение](https://user-images.githubusercontent.com/24612088/110199644-2c0c1a80-7e7b-11eb-9777-a874a29a26e1.png)

**Comment by Andryshik345** [comment]
Try to update your GPU drivers.

**Comment by Leopard20** [comment]
@Andryshik345 My GPU is discontinued by NVidia. That's the latest driver.

**Comment by 13xforever** [comment]
Then your only option is to use the last build that worked for you. We can't support every legacy gpu driver and workaround every bug in the drivers.

**Comment by Leopard20** [comment]
@13xforever Who are you again? You've only made 3 commits to this repository. You're certainly not eligible to speak for the team.

**Comment by xddxd** [comment]
Please test with #9914 once it builds.

**Comment by xddxd** [comment]
Please try this build @Leopard20 https://www.dropbox.com/s/y41zr9lge0jcyr9/rpcs3.7z

**Comment by Leopard20** [comment]
@xddxd Thanks. It works.

**Comment by Megamouse** [comment]
The fix is not in the master branch. So this issue should stay open.

**Comment by Leopard20** [comment]
Oh I thought it was merged. Ok

**Comment by kd-11** [comment]
Retry with a build from the PR https://github.com/RPCS3/rpcs3/pull/9959
