### ISSUE TITLE
NCAA14 not booting as of build 11675

### ISSUE THREAD

**Issue by huskereurocat** [RPCS3/rpcs3#9917]
Build 11673 seems to boot up normally, but as of build 11675 coming forward  it will not.  I would think that the reason this hasn't been conveyed before this is that the vast majority of RPCS3 users that run NCAA14 with the CFBR mod installed use build version 11605, since I've been told that any builds after that the bowl endzones graphics are messed up on. I will try to verify that though. I just know that most of the NCAA14 users do not have builds newer than 11605. 

Sorry I can't be more help, I'm merely a user and not a programmer. If there's something else that you feel I am capable of getting to you, please let me know what that might be. 

Here is a log with build 11675:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6096520/RPCS3.log)

And here is a log with build 11673:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6096529/RPCS3.log)

Here is what I run RPCS3 on if that helps:
![image](https://user-images.githubusercontent.com/52609668/110228428-a7df8480-7ec6-11eb-9614-1f22d133f9c8.png)

**Comment by Asinin3** [comment]
If that's the case then it was broken by https://github.com/RPCS3/rpcs3/pull/9699 . Best to link the offending pull request so the developer who made the change is aware and can look into it.

**Comment by benderscruffy** [comment]
RPCS3 v0.0.29-15444-6672499d Alpha | master
goes ingame now
can be closed
![Screenshot 2023-08-06 101950](https://github.com/RPCS3/rpcs3/assets/2696404/03eb4db6-08b2-40be-8e33-6ee29603f039)

**Comment by Triticum0** [comment]
Seem like this bug fixed https://youtu.be/BCdrcpkslXU?t=980

**Comment by Triticum0** [comment]
Can This be closed then?

**Comment by AniLeo** [comment]
Game seen booting normally on current RPCS3 version, closing as completed
