### ISSUE TITLE
Emulator Crashes when trying to start up Road to Glory mode in NCAA 14

### ISSUE THREAD

**Issue by MrFuzzihead** [RPCS3/rpcs3#9918]
## Quick summary
Please briefly describe what is not working correctly.

## Details

In NCAA 14, attempting to start a Road to Glory mode crashes the game/emulator. Sometimes I can get past the 'Auto Save highlights screen' (and crash right after) or sometimes it crashes on that screen.

#### 1. Please attach RPCS3's log.
* Run the game until you find the issue.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6096560/RPCS3.log)

	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc. 

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc. 
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.
![image](https://user-images.githubusercontent.com/56515000/110229617-766bb680-7ed0-11eb-81db-c17cb1fe6ba3.png)

#### 4. Please provide comparison with real PS3.
Normally, I would choose if I want to save auto highlights or not, create my character, and go on to play some games.

#### 5. Please provide your system configuration:
* OS: Win 10 Pro
* CPU: 3900x
* GPU: 2060S
* Driver version: 461.72
* etc.

#### Please include.
Using Vulcan

**Comment by MrFuzzihead** [comment]
curious to see if this issue was ever resolved/noticed, or if my original post was incorrectly formatted and needs to be retested/resubmitted

**Comment by benderscruffy** [comment]
RPCS3 v0.0.26-14723-bb2c9196 Alpha | master
goes ingame now with Road to Glory mode

![BLUS31159_screenshot_2023_02_19_18_04_54](https://user-images.githubusercontent.com/2696404/219941618-e11ced11-ff2f-4049-a096-fd57f4321deb.png)
![BLUS31159_screenshot_2023_02_19_18_07_36](https://user-images.githubusercontent.com/2696404/219941622-f86cdea3-7bfb-456f-a804-ba236290cd21.png)
![BLUS31159_screenshot_2023_02_19_18_08_08](https://user-images.githubusercontent.com/2696404/219941623-14f1f8a3-bc63-451e-8f1d-80247b6ad08c.png)
