### ISSUE TITLE
Patch Manager Suggestions

### ISSUE THREAD

**Issue by BSoDGamingYT** [RPCS3/rpcs3#9919]
Just a few suggestions (If any are possible for the patch manager and GUI options)

1. Change "Configure Game Patches" to "Manage Game Patches"

My reason for requesting this is to better draw the users eye to the patches when they right click a game in the GUI. Maybe its just me, but my eye always misses the patch option at a glance since all 4 options start with a capitol C (I understand that this is a weird request, if you think its pointless...feel free to ignore)

![Capture](https://user-images.githubusercontent.com/38402209/110241339-8b882a00-7f50-11eb-983e-a26863b20607.PNG)

2. When you open a specific games patches from the "Configure Game Patches" option, expand the tree view for the currently installed version of the game

How the list looks when opening now:
![tlou old](https://user-images.githubusercontent.com/38402209/110241428-f9345600-7f50-11eb-96d5-ec22632bc6b4.PNG)

How I think it should look:
![tlou new](https://user-images.githubusercontent.com/38402209/110241437-02bdbe00-7f51-11eb-8932-2f63b43e5085.PNG)

**Comment by Megamouse** [comment]
should be implemented now. please test

**Comment by BSoDGamingYT** [comment]
> should be implemented now. please test

Works as expected, thanks
