### ISSUE TITLE
[Feature Request] GUI option for "Import Custom Icon"

### ISSUE THREAD

**Issue by BSoDGamingYT** [RPCS3/rpcs3#9923]
Since RPCS3 now supports custom game icons, perhaps a right click GUI option can be added for each game. 

Right Click/Import Custom Icon

This could create the folder format (RPCS3 Master\Icons\game_icons\GAME SERIAL), then prompt the user to select the .PNG they wish to use as a replacement. (This .PNG needs to be named ICON0.PNG, I'm not sure if its possible to have the emulator rename any selected .PNG to this. But if it were, that would be very useful)

Example of icons before replacement
![EjwLQHIX0AIc0sW](https://user-images.githubusercontent.com/38402209/110302809-f0e42580-7ff9-11eb-9970-78d38c80106c.png)

Example of icons after replacement
![EjwLQ1FWoAI2LZd](https://user-images.githubusercontent.com/38402209/110302835-f9d4f700-7ff9-11eb-9294-b3bd531ac85c.jpg)

As always, if you think this feature request is a stupid idea, feel free to ignore.

**Comment by Megamouse** [comment]
The folder is already used. "/Icons/game_icons/ABCD12345/ICON0.PNG"

So there only needs to be an import function that copies and renames the icon. Maybe also some size checks. idk

**Comment by BSoDGamingYT** [comment]
> The folder is already used. "/Icons/game_icons/ABCD12345/ICON0.PNG"
> 
> So there only needs to be an import function that copies and renames the icon. Maybe also some size checks. idk

I see. I wasn't sure if the emulator created that folder by default at the moment. So I included the info I was aware of.  Hopefully something like this can be added, and isn't too much of a hassle
