### ISSUE TITLE
[BLUS30847][v1.00][DISC] Metal Gear Solid HD Collection - infinite loading screen

### ISSUE THREAD

**Issue by SpaceDockFondue** [RPCS3/rpcs3#9924]
everytime i start up MGS3, the game starts loading infinitely and the MGSHD Collection logo appears. These are the errors i got from the last time is happened 

E {PPU[0x100000c] Thread (fios mediathread 2) [0x02401ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/FIOSCACHE” [1]
E {PPU[0x100000c] Thread (fios mediathread 2) [0x02401ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/FIOSCACHE” [2]
E {PPU[0x100000f] Thread (fios mediathread 5) [0x02402090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/MGS3/mgs3_misc.psarc” [1]
E {PPU[0x100000f] Thread (fios mediathread 5) [0x02402090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/MGS3/mgs3_misc.psarc” [2]
E {PPU[0x100000f] Thread (fios mediathread 5) [0x02402090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/MGS3/mgs3_misc.psarc” [3]
E {PPU[0x100000f] fios mediathread 5 } SYS: Stat: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/MGS3/mgs3_misc.psarc” [x2587]
E {PPU[0x1000000] main_thread } SYS: Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x31]

**Comment by MsDarkLow** [comment]
Do us a favor and follow the template written when you're creating an issue. This is almost absolutely useless.
If you're looking for support join the discord server.
