### ISSUE TITLE
Metal Gear Solid 4 GOTP - DualSense "Shake" Doesn't Remove Octocamo

### ISSUE THREAD

**Issue by curryking3** [RPCS3/rpcs3#9934]
## Quick summary
"Shake" of DualSense sixaxis/gyroscope feature does not remove octocamo in MGS4 (in-game or in-cutscene) using RPCS3 version 11903

## Details

1. Shake DualSense controller up and down
2. Octocamo does not reset (in-game or in-cutscene)

This functionality is working on DualShock 4

#### 1. Please attach RPCS3's log.
Uploaded, but this is probably related to a crash of switching Stealth Camo on/off many times very quickly

#### 3. Please attach screenshots of your problem.
Not a graphical bug
Controller functionality of DualSense not currently working

#### 4. Please provide comparison with real PS3.
On a PS3 Sixaxis/DualShock 3, while in-game or in-cutscene, you can shake the controller (controller buttons facing player, and shaking the controller up and down) to reset Octocamo appearance

#### 5. Please provide your system configuration:
* Win10 pro
* 5950x
* 1080 ti
* nvidia 461.72

#### Please include.
There is a boss battle (Screaming Mantis) I believe that also requires Sixaxis to progress, can't remember if this used shaking or other functionality of Sixaxis

**Comment by Megamouse** [comment]
The dual sense seems to have a different default orientation. Try to shake the controller in different angles

**Comment by curryking3** [comment]
Thanks Megamouse, that is a good suggestion. I just tried as many shake configurations vertical and horizontal forward and sideways as I could holding the controller sideways, upside down.

I couldn't find a method that worked unfortunately. Unless I missed something, but I tried many different shake directions.

My controller is wired connection as DualSense, but I don't think that would affect anything, I also use my DualShock 4 wired.

I can try Folklore and see if "shake" is working there with DualSense.

**Comment by curryking3** [comment]
Just tested in Folklore to compare, it is actually working there (in Folklore it is a direct vertical motion holding the controller normally with face buttons facing upwards).

In MGS4, the method that works best for me with the DualShock 4 at least is holding the controller with one hand (I usually use right), and then swinging it up and down as a fulcrum on the right side of controller.

**Comment by curryking3** [comment]
Have noticed only one other game now where a similar function is not working, which is rotating the gyroscope (if the controller was laid on a flat plane in front of the player), forward and back on left and right side alternating, in Call of Duty 3, in the first level (not tutorial area), when you walk through a doorway and get a QTE-like event where you fight off an enemy soldier in melee. This does work with the DualShock 4 it seems as well, just like the Octocamo in MGS4, and neither work with the Dualsense.

**Comment by Megamouse** [comment]
This might be fixed now

**Comment by curryking3** [comment]
This is fixed, just tested on 0.0.24-14286, cheers :)
