### ISSUE TITLE
Jak 2 and 3 Hangs when saving/loading

### ISSUE THREAD

**Issue by dmeagher101** [RPCS3/rpcs3#9936]
Whenever you try to save or load a file in Jak 2 and 3, the game hangs at the save/loading screen and never finishes.

**Comment by dmeagher101** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6111364/RPCS3.log)
![jak2_saving](https://user-images.githubusercontent.com/24301135/110537374-7689d300-80d7-11eb-945e-d7e5312b7109.png)
On a real PS3, the game saves successfully and then exits the save dialog.
Specs
OS: Windows 10 64-bit
CPU: Intel Core i7-9500K 8-core
GPU: Nvidia Geforce 1660 Super
Driver Version: 461.72

**Comment by asp0909** [comment]
it is a problem of always ... it is in the wiki of compatible. I don't know fixed

**Comment by SadTransGirl** [comment]
Hi, I did alot of testing with jak 2. When you save the game the does actually save however it seems to hang on the screen.
Loading games also works not a issue.
The game also has issues with some textures or effects not working as intended.

**Comment by jy95** [comment]
I finished Jak 2 and Jak 3 on RPCS3 (as I explained in the [wiki](https://forums.rpcs3.net/thread-199496-post-315262.html#pid315262)). Just as explained previously, only the save feature hangs

**Comment by Decards** [comment]
Yes the auto-save works fine. the game gets stuck when manually trying to save in the start menu only but if you stop the game and restart the save will be there. When you first create your save it's the same it gets stuck but the save will be there upon restarting the game.

**Comment by Decards** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6345481/RPCS3.log)

I linked my log, the only things i did was starting rpcs3, starting jak and daxter collection, choosing jak2 and i created a new save  i waited around 15sec stuck on the "creating save screen" and after that  i closed the game and the emulator

**Comment by JimScript** [comment]
I think the game is not receiving a callback to close the menu when it is done saving. I don't know much about it, but after the savedata_op in the ppu syscall usage thread Jak 1 ends its threads with sys_fs_fstat, while Jak 2 has it around 19 lines earlier.

Jak 1:[RPCS3-1.log](https://github.com/RPCS3/rpcs3/files/7824196/RPCS3-1.log)
Jak 2:[RPCS3-2.log](https://github.com/RPCS3/rpcs3/files/7824201/RPCS3-2.log)
 
Then again it could be anything, I'm not an expert in these things.

**Comment by guiguiconqueror** [comment]
new info ?

**Comment by LifeIsStrange** [comment]
Just saying that it would be really cool if this bug was fixed

**Comment by JimScript** [comment]
> Just saying that it would be really cool if this bug was fixed @kd-11 feel free to ignore my request, also thank you for your amazing work, you are a modern hero :)

I'm not so sure this is kd-11's area of expertise, they seem to focus on the RSX emulation and all that relates to it for the emulator. Now this could be something of an RSX readback issue or something, but this seems to relate more towards the VFS(Virtual File System) and how the game doesn't get the message that it is done saving, since saves are perfectly usable after you restart.

**Comment by ISuckGood** [comment]
yikes

**Comment by tylerjm917** [comment]
Any update on this? It would be nice to resolve this considering it's a playstation exclusive and hard to come by on a real ps3

**Comment by jaybo626** [comment]
I doubt it's been updated man been 2yrs for me since I asked and no response

**Comment by asp0909** [comment]
I don't think they want to fix it

**Comment by Asinin3** [comment]
Stop spamming and complaining. GitHub is primarily for developers and testers. This is an issue tracker, not a forum. There are hundreds of games out there and only a few active developers on the project. What's stopping you from fixing it? The code is open source. This will get locked if you guys continue only making it worse.

**Comment by elad335** [comment]
![image](https://user-images.githubusercontent.com/18193363/222917786-ea6db3ec-d0a7-4afe-9305-33c3fbc28197.png)
WIP

**Comment by elad335** [comment]
![image](https://user-images.githubusercontent.com/18193363/222917921-19050f5b-9bd3-46e5-980f-14aecccfcc9f.png)
WIP

**Comment by elad335** [comment]
Test with #13492
