### ISSUE TITLE
Disable Async for older GPUs after #9928

### ISSUE THREAD

**Issue by Kravickas** [RPCS3/rpcs3#9947]
#9928
Asynchronous Texture Streaming needs to be auto-disabled for GPUs like 980ti and older on nvidia side, not sure about AMD side.

With that option on, it causes soft freezing with both ''device'' and ''host'' options for Q Scheluder. 😞

**Comment by isJuhn** [comment]
Same on my 1080ti, Killzone even managed to kill my driver on device mode.

**Comment by davewuk** [comment]
Having this option enabled causes freezes on my GTX 970

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/9959 and upload log file if it works.

**Comment by Nerboruto** [comment]
I noticed that I crash in particular on movies shenes ... tested on kepler and maxwell...
I'm talking about version # 9928...
