### ISSUE TITLE
Compilation errors on Azure+MSVC

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#9952]
Regarding Vulkan SPIRV submodule, see https://github.com/RPCS3/rpcs3/runs/2093939827 for more details. C++20 warnings were treated as errors and failed compilation.
The weird thing is that it's random.

**Comment by Nekotekina** [comment]
That C++17->20 transition is gonna be such a mess...

**Comment by Nekotekina** [comment]
For now restarted build 2 times.

**Comment by elad335** [comment]
I haven't encountered it recent CI builds, closing for now.

**Comment by Megamouse** [comment]
I did in my last PR

**Comment by elad335** [comment]
I mean in the Windows build specifically, not clang.

**Comment by Megamouse** [comment]
Yes. It was the windows build
