### ISSUE TITLE
Crash ncaa 14

### ISSUE THREAD

**Issue by daddygoatmilk** [RPCS3/rpcs3#9957]
## Quick summary
Whenever i start up the game it now crashes, i was able to play it before with no problems then an update came and it doesnt work? idk how to fix this

**Comment by RainbowCookie32** [comment]
The template wasn't there for decoration. 

If you need support, use [Discord](https://discord.me/RPCS3). If you want to report a regression, follow the template and provide all the required info, this ticket is useless as is.

**Comment by digitaldude555** [comment]
Duplicate of #9917
