### ISSUE TITLE
Killzone 3 Lighting Issues

### ISSUE THREAD

**Issue by Relentless1978** [RPCS3/rpcs3#9958]
The most recent update is causing lighting issues with Killzone 3. Resolution Scale is at 300 percent, Write Color Buffer is uncheck, and I have the patch, Disable MLAA checked. It worked great until the current update. Thanks for your support. You guys are amazing!

**Comment by Asinin3** [comment]
This issue is fairly useless without a log file or screenshot or without you saying the build you were on that broke it and confirming build before was okay.

Regardless, should be fixed by disabling asynchronous texture streaming on gpu settings tab. Closing As this is already reported
