### ISSUE TITLE
Regression: Artifacts in TLOU (#9613)

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#9960]
After PR #9613 (rpcs3-v0.0.14-11619-22584fb2), garbage is being rendered in the TLOU menu.
Last working build (rpcs3-v0.0.14-11601-7f28489c):
![Screenshot_15](https://user-images.githubusercontent.com/1712979/111031534-b1aa4000-8410-11eb-84eb-39a6a516ce7d.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6134841/RPCS3.log.gz)
Latest master (RPCS3 v0.0.15-11945-aff63028):
![Screenshot_16](https://user-images.githubusercontent.com/1712979/111031591-f7ff9f00-8410-11eb-850d-d1848ccf43bb.png)
[RPCS3broken.log.gz](https://github.com/RPCS3/rpcs3/files/6134849/RPCS3broken.log.gz)
RRC: https://www.dropbox.com/s/1qoe1kndsmpfzhw/BCES01584_20210313152531_capture.7z

Ryzen 7 2700
RX 580 21.2.2

**Comment by kd-11** [comment]
Superseded by https://github.com/RPCS3/rpcs3/issues/9968.

**Comment by Pouncha** [comment]
I don't have those artefacts by using Nvidia GTX 1080 with lastest drivers (including different enalbed patchs) and I9 9900 KF.
For settings, I use PPLLVM,SPULLVM,SPU Loop Detection,SPU cache,TSX Enabled,Mega Block Save.
For graphics,I use Vulkan Renderer with 60 fps limit, not antialiasing and auto anisotropic filter.Upscaled to 200% with 160x160 scale Threshold and Async shader mode (nothing else).
I also use Read Color Buffer option,driver wake up at 200 and 240 Hz Vblank frequency.

the only pb I found (for a while) is that the game have delay dialog in bidonville cut scene and impossible to solve it (so,if a solution for this issue has been found,please tell me).
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6173620/RPCS3.log.gz)

**Comment by xddxd** [comment]
Did some testing, RADV is unaffected.

**Comment by kd-11** [comment]
Anything running on top of the AMDGPU kernel driver has passthrough DMA disabled so this shouldn't be an issue.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/9959
This PR blocks use of passthrough DMA when async streaming is disabled. It doesn't make much sense to use passthrough without async - or rather, its too risky. Since async streaming does not block to wait for CPU operations, it makes it much safer to use passthrough with it.
