### ISSUE TITLE
Persona 5 font issue with Asynchronous Texture Streaming

### ISSUE THREAD

**Issue by kaninhot004** [RPCS3/rpcs3#9961]
Game: PERSONA 5 BLUS31604 V.01.00
Emu Version: RPCS3 0.0.15-11945-aff63028 Alpha
Game Status: Playable

## Quick summary
Font are show with white square sometimes.

## Details
Some font is missing. Happened when enabled Asynchronous Texture Streaming only.

## Logs
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6134891/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6134892/RPCS3.log.gz)

## Screenshots
![Screenshot](https://user-images.githubusercontent.com/9493525/111032070-314e0400-843d-11eb-9762-36b97f7c290f.png)

## System configuration:
* OS: Windows 10
* CPU: Intel(R) Core(TM) i5-10400F
* GPU: GeForce GTX 1650 SUPER
* Driver version: 461.72

**Comment by aschereT** [comment]
Also ran into this issue yesterday on `11937-e3a7fddd`. Had to revert to the backed up `11920-cd6ef295`.
![RPCS3 Version 0 0 15-11937-e3a7fddd Alpha](https://user-images.githubusercontent.com/12742227/111043410-38522380-83f7-11eb-9953-f988e0d22847.PNG)

System configuration:
- OS: Windows 10
- CPU: AMD Ryzen 5900X
- GPU: Geforce RTX 2070
- Driver: 461.40

**Comment by yungpolvo** [comment]
Yeah, I've been encountering this lately too. Just made an account to see if this was happening to others. 
![image](https://user-images.githubusercontent.com/80600736/111043513-fcc45300-8410-11eb-9de5-670f491c6270.png)

System configuration:

OS: Windows 10
CPU: Intel i7-8750H
GPU: Geforce RTX 2080 with Max-Q
Driver: 461.72

**Comment by kd-11** [comment]
Superseded by https://github.com/RPCS3/rpcs3/issues/9968
