### ISSUE TITLE
Asura's wrath freezing in Episode 13 at a specific point.

### ISSUE THREAD

**Issue by Alpha-And-The-Omega** [RPCS3/rpcs3#9971]
## Quick summary

I am playing Asura's wrath on RPCS3, and I have noticed that although the games run smoothly 30 FPS with good audio, there is a certain point in Episode 13 which causes the emulator to freeze.

## Details

Every time I play episode 13 of Asura's wrath, just after the first fight with yasha's QTE event, it freezes in the next cutscene with olga watching the screen as in the below screenshot
![Screenshot](https://user-images.githubusercontent.com/80668290/111113696-2784e780-8588-11eb-9b55-b15992df0de8.png)

 And I get the below error (attached screenshot)
![log3](https://user-images.githubusercontent.com/80668290/111111413-44b7b700-8584-11eb-99a4-010d44dd22bb.png)
I have tried this with both the US and EUR versions (BLUS30721 and BLES01227). And I get the same error in both of them. 

here is my log(attaching drive link as getting error trying to upload zip file):
https://drive.google.com/file/d/1rWMa9i0c-Ow_PqZPMk_WgBGSIMNtjABP/view?usp=sharing

## System Configuation

* OS - Windows 10 Home Single Language 64 bit (10.0, build 18363)
* CPU - Inter(R) Core(TM) i5-9300H CPU @2.40GHz (CPUs), ~2.4GHz 8 GB RAM
* GPU - NVIDIA GeForce GTX 1650
* Driver version - 26.21.14.4223
* RPCS3 version -  0.0.15-11912

Note: I am using 11912(10th March) build of RPCS3 as the latest build gives me black screen with no start menu.

**Comment by Megamouse** [comment]
Then why aren't you reporting the black screen instead of reporting some old build

**Comment by Alpha-And-The-Omega** [comment]
> Then why aren't you reporting the black screen instead of reporting some old build

Well this is the issue I am facing with most of the previous builds of RPCS3. Just the recent one from 11th March onwards which gives black screen but on the 10th march build it atleast runs.

**Comment by Alpha-And-The-Omega** [comment]
I just updated to the latest version 11958 to check it again with today's version, and this issue is fixed and running now.
