### ISSUE TITLE
Vulkan plugin causes Fatal Error crash whenever selecting a game to start 

### ISSUE THREAD

**Issue by DTK21** [RPCS3/rpcs3#9978]
## Quick summary
Vulkan plugin causes Fatal Error crash whenever selecting a game to start 

#### 1. Please provide _exact_ build (or commit) information that introduced the ressregion you're reporting.

RPCS3 v0.0.15-11963-a9b0d25c Alpha

#### 2. Please attach TWO logs:

The GZ file just disappears and the file size is 0 anyways
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6150790/RPCS3.log)

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc. 
	And drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

#### 4. Please attach screenshots of your problem.

![RPCS3_ Fatal Error 03_16_2021 12_51_04](https://user-images.githubusercontent.com/24620064/111348184-5073ae00-8656-11eb-91a5-349482b37c5f.png)

#### 5. Please provide comparison with real PS3.
No Crash

#### 6. Please provide your system configuration:
* OS Windows
* CPU Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 CPUs), ~3.7GHz
* GPU NVIDIA GeForce RTX 3090
* Driver version 461.92
* etc. 32 Ram

#### Please include.
I tested out OpenGL and that works but Vulkan was always what I used so far and I'm guessing the last build it worked for me was 0.0.14-11621 considering that was the same date as my latest save game

**Comment by DTK21** [comment]
I have work now so I'll check back later in the day

**Comment by AniLeo** [comment]
Not an RPCS3 issue, external software issue (broken vulkan layer). Use vkdiag https://github.com/13xforever/vkdiag to fix it.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
