### ISSUE TITLE
[Feature Request] Log unused config.yml entries, possibly remove on saving new config

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#9981]
Title says it all.

**Comment by Megamouse** [comment]
What's an "unused entry"

**Comment by Megamouse** [comment]
Removal should have used confirmation, as it might brake testing older builds

**Comment by elad335** [comment]
like a line in config.yml: "This setting is not used by rpcs3: 0x12345678", these entries are 99% of the time settings which were removed or renamed in order to invalidate their values.

**Comment by Megamouse** [comment]
I can probably implement something like this at the weekend
