### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by drazzo** [RPCS3/rpcs3#9984]
Hey guys, I'm having a trouble with textures in Skylanders Giants
![image](https://user-images.githubusercontent.com/80849162/111517515-ea5d5880-8733-11eb-9d8a-d9498018eeef.png)

here's the log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6158758/RPCS3.log)

My specs:
Windows 10 PRO
Intel HD Graphics 520
Intel Core I7 6500
8 GB RAM

pls help

**Comment by jokoputera** [comment]
RSX Capture please

**Comment by Megamouse** [comment]
![image](https://user-images.githubusercontent.com/23019877/111794558-a2226f80-88c6-11eb-881e-bb65292c2ad0.png)

**Comment by Asinin3** [comment]
Closing, OP hasn't updated this issue with a RSX capture or tested with ANV.
