### ISSUE TITLE
Persona 5 runs smoothly in 4k 60fps, but prerendered cutscenes are stuttering

### ISSUE THREAD

**Issue by Krounder** [RPCS3/rpcs3#9987]
Persona 5 runs smoothly in 4k 60fps, but prerendered cutscenes are stuttering
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6162556/RPCS3.log.gz)
How can i fix it?

**Comment by MSuih** [comment]
Github isn't the place for support, ask your questions on Discord instead. And besides, any issues related caused by patches aren't accepted either.
